### ISSUE TITLE
The find and replace toolbar button is using a split button instead of dropdown button

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10007]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html

### ✔️ Expected result

The find and replace button is using a `DropdownButtonView` same as `insertTable` button.

### ❌ Actual result

It's using a `SplitButtonView` and action for both sides is the same.

![](https://user-images.githubusercontent.com/1232187/123961259-724c3300-d9b0-11eb-8267-d87e0e87517a.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Fixed in #10099.
