### ISSUE TITLE
[HTML comments] Add unit tests for changes introduced in DOMConverter

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10006]
## Provide a description of the task

A follow-up for #9666 #9665 . The task related to updating `DOMConverter` methods is done, however, changes are still missing tests.

**Comment by psmyrek** [comment]
Unit tests have been merged to feature branch in https://github.com/ckeditor/ckeditor5/commit/c666792663021437fe46c87ff89daf3ed0bfba45.
