### ISSUE TITLE
`ckeditor5-metadata.json` files are not published on NPM

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#10004]
### ❌ Actual result

The file is published only for CF packages, it is not published in `CKEditor 5` and `ckeditor5-internal` due to the fact that this file is not added to the `files` array in the `package.json`.

### ❓ Possible solution

Add `ckeditor5-metadata.json` file to the `files` array in `package.json` array.

## 📃 Other details

Currently, the Online builder can work on metadata files that are taken from GH and saved locally, but for the 3rd-party integrators, these files won't be available. Also it's planned to use the NPM-based versions in the OB as well. 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
If Online Builder uses metadata files from GitHub and works, I don't think that the issue is a blocker. I agree OB should use the file from packages instead of GH. But if it works, why should the issue block the release?
Am I missing anything?
