### ISSUE TITLE
The find and replace checkboxes are missing focus styles

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10009]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html
2.  open the "find and replace" view
3.  toggle the focus using the tab key multiple times

### ✔️ Expected result

Checkboxes outline look consistent with other focus outlines.

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/123962691-04a10680-d9b2-11eb-90fb-95fdde951cf8.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This will no longer be necessary because of #10229.
