### ISSUE TITLE
Image contextual toolbar hides out of the editor window

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#10003]
## 📝 Provide detailed reproduction steps (if any)

1.  Clicking on the image
2.  Contextual toolbar appears
3.  Use the toolbar

### ✔️ Expected result

The toolbar appears within the editor's editing area.

### ❌ Actual result

The toolbar appears out of the editing area (namely behind the main toolbar) as pictured in the screencast below.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Safari 14.0
*   OS: MacOS Catalina
*   First affected CKEditor version: pre v29.x release
*   Installed CKEditor plugins: default in the image feature guide (namely image styles guide)

also on:

*   Browser: Chrome 91.0.4472.114
*   OS: MacOS Catalina
*   First affected CKEditor version: pre v29.x release
*   Installed CKEditor plugins: default in the image feature guide (namely image styles guide)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by godai78** [comment]
[https://cksource.slack.com/files/U017DJLU7NX/F026KCBN6J1/2021-06-30_14.09.39.gif](https://cksource.slack.com/files/U017DJLU7NX/F026KCBN6J1/2021-06-30_14.09.39.gif)

**Comment by godai78** [comment]
@ckeditor/ckeditor-5-triage

**Comment by godai78** [comment]
![](https://user-images.githubusercontent.com/68123541/123962002-40879c00-d9b1-11eb-9161-f4f933772efe.gif)

**Comment by Mgsy** [comment]
Yeah, it's an old issue with balloons :disappointed:  - #5328.
