### ISSUE TITLE
The find and replace view animates "find in text" label on view opening

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10008]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html
2.  Click the "find and replace" toolbar button

### ✔️ Expected result

The input field label should not animate as in other features (for example table properties).

### ❌ Actual result

It's animating (slow motion recording):

![](https://user-images.githubusercontent.com/1232187/123961919-2a79db80-d9b1-11eb-9502-66412c8ef00c.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Closed in #10097
