### ISSUE TITLE
Bring back code coverage to 100% in find and replace

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10000]
## Provide a description of the task

When finishing find and replace we didn't hit 100% CC. We decided to do this in the next iteration.

**Comment by Reinmar** [comment]
Missing:

*   1 method
*   4-5 branches
*   Some coverage may be accidental, need to be reviewed

Complete:

*   UI

Note: The `debounce()` for `scrollToHighlightedResult` is unnecessary. A more straightforward option would be to prevent `change:highlightedResult` while "replace all".

Note: It seems that "Replace" does "find" first so "Replace all" does "find" even dozens of times. This makes "replace all" take 10s on medium long content.

We need to resolve these issues first and then fix the coverage.

**Comment by Reinmar** [comment]
> Note: The `debounce()` for `scrollToHighlightedResult` is unnecessary. A more straightforward option would be to prevent `change:highlightedResult` while "replace all".

Let's ignore it (via istanbul's comment) so to achieve 100% for now without resolving this debt.
