### ISSUE TITLE
Editor isn't shown in built-in WebView on Android 4.4

### ISSUE THREAD

**Issue by balszab** [ckeditor/ckeditor5#1000]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

ckeditor5-build-classic-1.0.0-beta.3

## 📋 Steps to reproduce

1. Create an Android WebView (https://developer.android.com/reference/android/webkit/WebView.html)
2. Load the following html page into it:
 https://docs.ckeditor.com/ckeditor5/latest/builds/guides/quick-start.html#example

## ❎ Actual result
The editor isn't created only the html textarea is shown.

## 📃 Other details that might be useful

- If I open mentioned html page above with newer Android version than it works fine.
- It also work on Android 4.4 if I open it with Chrome browser. Chrome version: 60.0.3112.107.

**Comment by Reinmar** [comment]
AFAIR that Android version came with an extremely old V8 which didn't support ES6 and some other things we rely on (mutation observer). I know some people compile CKEditor 5 to ES5 (see the [docs](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target)) and load some polyfills for the missing things. But I don't know how good it works.

**Comment by Reinmar** [comment]
I can see that Android 4.4 still has around 10% of Android's market, but it's unsupported already: https://en.wikipedia.org/wiki/Android_version_history

**Comment by f1ames** [comment]
As mentioned in this issue description:

> If I open mentioned html page above with newer Android version than it works fine.

I have checked this issue on Android `6.0.1` and `8.0.0` with latest Chrome (`67`) and a `WebView` and editor works fine. Since we support [all officially supported Android versions](https://en.wikipedia.org/wiki/Android_version_history) which ATM are `Android 6+` I'm closing this issue.
