### ISSUE TITLE
The find and replace view looks un-styled when there is not enough space (responsive design)

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10019]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html
2.  shrink the window width
3.  open the find and replace view

### ✔️ Expected result

UI should stay readable

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/123968766-d3c3d000-d9b7-11eb-89e9-1720c0b56225.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It stays "okayish" on https://github.com/ckeditor/ckeditor5/pull/10344 so I'll consider it resolved by this PR. It's not mobile-friendly, but at least it doesn't break.
