### ISSUE TITLE
The find and replace view does not indicate that no matches were found

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10014]
## 📝 Provide a description of the improvement

[http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html](http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html)

if you search for anything that has no matches there is no UI response of any kind. It would be nice to see `0 of 0` in the input view as for found matches. 

![](https://user-images.githubusercontent.com/1232187/123965507-cfe27e80-d9b4-11eb-9892-68edc063e2c8.gif)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Fixed with [#10047](https://github.com/ckeditor/ckeditor5/pull/10047).
