### ISSUE TITLE
The find and replace view checkboxes are to small for mobile and inconsistent with other UI elements

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10010]
## 📝 Provide a description of the improvement

The find and replace checkboxes are too small for mobile, and inconsistent with toggles used for links manual decorators

![](https://user-images.githubusercontent.com/1232187/123963182-809b4e80-d9b2-11eb-8ece-bf660b04cea8.png)

the link edit view with manual decorator:

![](https://user-images.githubusercontent.com/1232187/123963373-ad4f6600-d9b2-11eb-8cc7-a8197f90c5b3.png)

Also, buttons are inconsistent with those for example in table properties:

![](https://user-images.githubusercontent.com/1232187/123963567-e1c32200-d9b2-11eb-894d-88937b1e9b5c.png)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This will no longer be an issue because of #10229.
