### ISSUE TITLE
Crash after toggling the image caption while the image is still being loaded

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#10013]
## 📝 Provide detailed reproduction steps (if any)

1. Open http://fake.ckeditor.com:8080/ckeditor5/latest/examples/builds/classic-editor.html.
2. Insert a large image.
3. While the image is still being loaded, click on "Toggle caption" button.

### ✔️ Expected result

Editor is not crashed.

### ❌ Actual result

Editor crashes:

https://user-images.githubusercontent.com/56868128/123964727-09ff5080-d9b4-11eb-95b5-1a323bed0e8d.mp4

```
ckeditorerror.js:69 Uncaught TypeError: Cannot read property 'is' of undefined
    at Mapper.findPositionIn (mapper.js:550)
    at Mapper.on.priority (mapper.js:117)
    at Mapper.fire (emittermixin.js:208)
    at Mapper.toViewPosition (mapper.js:344)
    at DowncastDispatcher.eval (downcasthelpers.js:683)
    at DowncastDispatcher.fire (emittermixin.js:208)
    at DowncastDispatcher.convertSelection (downcastdispatcher.js:348)
    at eval (editingcontroller.js:105)
    at View.change (view.js:508)
    at Document.EditingController.listenTo.priority (editingcontroller.js:103)
```

This is not a regression, because the "Toggle caption" button has been added recently to image's toolbar.

## 📃 Other details

* Browser: Firefox 89, Chrome 91
* OS: Win
* First affected CKEditor version: not released yet

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
@ckeditor/ckeditor-5-triage

**Comment by oleq** [comment]
For anyone interested, there were two problems addressed in https://github.com/ckeditor/ckeditor5/pull/10071/files:

1.  The `ImageTypeCommand` didn't work on selected images that have no `src` (we consider `src`\-less image a broken image). But during the upload, the `src` is not there yet and instead, we have an `uploadId` associated with the uploading process. So one part of the fix was letting the image type change while being uploaded but still `src`\-less.
2.  There is a code in the `ImageUploadEditing` that reacts on model document change and does the following:
    1.  If an image was inserted in the change (but not in `$graveyard`) and the loader didn't start yet (idle), start uploading the image.
    2.  If an image was inserted in the change into a `$graveyard` (deleted by the user), abort the loader related to that image because it is no longer in the main document.
        1.  This piece caused problems because when the image changes its type during the upload, we don't rename it but use `insertContent()` and replace the old image element with a new one (with the same `uploadId`). The old image went to the `$graveyard` so the loader was aborted. To fix this, the image replacement must be detected based on change event data, the loader must not be aborted and the upload resolution must happen in the context of the new model image (that replaced the old one).

**Comment by maxbarnas** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/10071.
