### ISSUE TITLE
The editor does not work in old Edge versions (<16)

### ISSUE THREAD

**Issue by balszab** [ckeditor/ckeditor5#1001]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

ckeditor5-build-classic-1.0.0-beta.3

## 📋 Steps to reproduce

1. Open the example page with Edge which version is
- **v38**
- **v40**

Example page:
https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html

## ✅ Expected result

![win_pc](https://user-images.githubusercontent.com/38686188/39193079-ff2f7b44-47da-11e8-8ad4-921ad83fd412.JPG)

## ❎ Actual result
With **v38**:
See the screenshot below.

<img width="1016" alt="capture" src="https://user-images.githubusercontent.com/38686188/39194101-3a9cfeca-47dd-11e8-8d4c-249edf6cd260.PNG">

With **v40**:
- The editor is create but it doesn't have content. 
- If you type something into the edit you cannot delete it later.
- The toolbar buttons don't work. You cannot activate them at all.

![wp_ss_20180424_0001](https://user-images.githubusercontent.com/38686188/39193086-07f38202-47db-11e8-97bc-ab758c772a66.png)

**Comment by Reinmar** [comment]
cc @Mgsy

**Comment by Mgsy** [comment]
I can confirm that the editor doesn't work in Edge <16 and behaves as described in the issue. 

In Edge 15 (v40.15063) and Edge 14 (v38.14393) there is the error in the console:

![image](https://user-images.githubusercontent.com/20988892/39231233-acf655f2-4869-11e8-986e-dad4a2538c12.png)

**Comment by oleq** [comment]
Is this still an issue for us?
