### ISSUE TITLE
Find and Replace package contains an invalid CSS file import

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#10011]
See [https://github.com/ckeditor/ckeditor5/blob/62f68f7d2effcf8dd31d750147be615779194bf2/packages/ckeditor5-find-and-replace/src/findandreplaceui.js#L13](https://github.com/ckeditor/ckeditor5/blob/62f68f7d2effcf8dd31d750147be615779194bf2/packages/ckeditor5-find-and-replace/src/findandreplaceui.js#L13.)

**Comment by mlewand** [comment]
It should be ignored, more context:

> I understand this is a linter error being thrown by Online Builder?
> That make sense because have ignore statement anywhere we use it except this one place:
> https://github.com/ckeditor/ckeditor5/blob/d903bc52c96a2726e4b130dafe7d10ba49ee0851/packages/ckeditor5-image/src/imagetextalternative/ui/textalternativeformview.js#L25-L27
> https://github.com/ckeditor/ckeditor5/blob/d903bc52c96a2726e4b130dafe7d10ba49ee0851/packages/ckeditor5-media-embed/src/ui/mediaformview.js#L23-L25
> 
> textalternativeformview.js
> <https://github.com/ckeditor/ckeditor5|ckeditor/ckeditor5>ckeditor/ckeditor5 | Added by GitHub
> 
> mediaformview.js
> <https://github.com/ckeditor/ckeditor5|ckeditor/ckeditor5>ckeditor/ckeditor5 | Added by GitHub
> 
> m.lewandowski  1 minute ago
> So the line you pointed is missing
> // See: #8833.
> // eslint-disable-next-line ckeditor5-rules/ckeditor-imports
> 
> m.lewandowski  1 minute ago
> I don't know why it didn't blow on CI or somewhere. We tested and have built it in so many different places :smile:

**Comment by mlewand** [comment]
Fixed in 0b9e98f

**Comment by mlewand** [comment]
This hotfix has been released in [@ckeditor/ckeditor5-find-and-replace@28.0.1](https://www.npmjs.com/package/@ckeditor/ckeditor5-find-and-replace/v/28.0.1) package.
