### ISSUE TITLE
The find and replace view does not appear when the toolbar button is inside the dots menu

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10017]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html
2.  shrink the page width so that the find and replace button is not visible
3.  press `ctrl/cmd+f`

### ✔️ Expected result

The find and replace view appears

### ❌ Actual result

Nothing happens (but the browser native search is blocked):

![](https://user-images.githubusercontent.com/1232187/123967402-91e65a00-d9b6-11eb-84d7-9b2b3f00ffcc.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Implementing a modal will solve this issue. ATM the cost of implementation (because the find and replace dropdown does not know anything about the place it was rendered in) is too high.
