### ISSUE TITLE
The find and replace does not support ctrl/cmd+g to go to next match (and reversed with shift)

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10012]
## 📝 Provide a description of the improvement

[http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html](http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/find-and-replace.html)

the find and replace supports `ctrl/cmd+f` keystroke but it does not support `ctrl/cmd+g` and `shift+ctrl/cmd+g`

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Also, enter key should move to the next result while search input was not changed but enter was pressed.

**Comment by oleq** [comment]
Let's figure out the enter key support in this issue.

**Comment by Reinmar** [comment]
We should listen on Enter / Shift+Enter (TODO @oleq???) when the focus is on the search input
