### ISSUE TITLE
Pagination lines stopped scrolling with content (also the page navigation buttons stopped working)

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10027]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/pagination.html
2.  scroll the page to see pagination lines

### ✔️ Expected result

Pagination lines are scrolling with the content (are at fixed positions for content)

### ❌ Actual result

Pagination lines are not reacting to scroll.

### ❓ Possible solution

It's working correctly in the manual test so it might be related to some changes in the docs. Looks like the feature was unable to properly find the scrollable area.

## 📃 Other details

*   Browser: Chrome
*   OS: macOS
*   First affected CKEditor version: latest master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
@ckeditor/ckeditor-5-triage

**Comment by niegowski** [comment]
I briefly checked it and it tries to find the closest scrollable element before the dynamically injected styles are applied.

Styles in that snippet are injected here: [https://github.com/cksource/ckeditor5-internal/blob/2b83a78c4e5171e25c9a4773c3f0ca738ee1a61b/packages/ckeditor5-pagination/docs/_snippets/features/pagination.js#L172-L175](https://github.com/cksource/ckeditor5-internal/blob/2b83a78c4e5171e25c9a4773c3f0ca738ee1a61b/packages/ckeditor5-pagination/docs/_snippets/features/pagination.js#L172-L175)

I can see that it was changed recently. I guess we should revert that change and find a better solution for the original problem.

**Comment by pomek** [comment]
I wouldn't mark the issue as a blocker because it occurs only in the documentation, and we can merge a fix directly to the `#stable` branch at any stage of the testing/release process.

**Comment by pomek** [comment]
Fixed in https://github.com/cksource/ckeditor5-internal/pull/800.
