### ISSUE TITLE
Use icons instead of buttons with text in find and replace dropdown

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10029]
## 📝 Provide a description of the improvement

I think should go back to icon based buttons as proposed in [https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-857557024.](https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-857557024.)

The labels are localizable (just like any other part of our UI) and I expect it will mess layout rather quickly. Although not sure if this is a real issue, I checked labels in German (produced by automatic translator so might not be correct)

![](https://user-images.githubusercontent.com/5353898/124081412-d07a2400-da4b-11eb-851a-3cbe246dbf27.png)

And it still fits right. Not sure if there are languages that will have more spacious labels :thinking:

Reason why we went with text labelled buttons instead of icons was that it's difficult to make obvious icons for replace / replace all.

So the question is, should we move to icon-based buttons with text showing up as a tooltip?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
The new design in #10229 will address this issue.
