### ISSUE TITLE
find and replace - different font size on buttons

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#10028]
font size for "FIND" is 13px, while for "REPLACE / REPLACE ALL" is 11.7px 

<img width="261" alt="Screen Shot 2021-06-30 at 6 27 57 PM" src="https://user-images.githubusercontent.com/545175/123998250-953b0f00-d9d1-11eb-8f44-2fb5676a9c9c.png">

**Comment by oleq** [comment]
This will be addressed in #10229.
