### ISSUE TITLE
Source editing - the undo is not available in the source mode

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10026]
## 📝 Provide a description of the improvement

Currently, if you change some data in the source editing mode and make the data invalid, it's lost after switching to the WYSIWIG mode. You can undo it in WYSIWIG mode but if you switch to source editing you can't undo the changes you made previously.

![](https://user-images.githubusercontent.com/1232187/123987329-61f38280-d9c7-11eb-82ea-7012daea996c.gif)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Closing as duplicate, as there's a ticket with more votes: #13700.
