### ISSUE TITLE
The find and replace unexpected behavior on toggling "match case"

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10021]
## 📝 Provide a description of the improvement

If I toggle the "match case" button the state of other buttons change but markers are still there, and when I toggle it back the UI switches to the previous state. The same for the input field - when changed, only the UI state changes but not occurrences, and while changed back to previous input, the UI gets back to the previous state. 

I'm not sure what should be the best UX but I guess the search results should clear every time the input field or checkbox state changes and should not be brought back after getting back to the previous state.

![](https://user-images.githubusercontent.com/1232187/123970663-9a8c5f80-d9b9-11eb-9420-ef06c0b0c43a.gif)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Expected behavior: Check how others do. But probably: On changing the options, re-search automatically.

**Comment by Reinmar** [comment]
After #10344 the behavior is improved. The results are reset on the change in the options.
