### ISSUE TITLE
Source editing doesn't work on Safari

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#10033]
## 📝 Provide detailed reproduction steps (if any)

It touches both Safari Desktop and Safari mobile. Clicking the source editing button throws an error:

![image](https://user-images.githubusercontent.com/10279586/124094185-d3c7dc80-da58-11eb-9e95-cbcbf7c617d7.png)

https://user-images.githubusercontent.com/10279586/124094530-2608fd80-da59-11eb-9441-14f1710313b5.mov

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
It looks like it's an issue with the look behind :disappointed: [https://caniuse.com/js-regexp-lookbehind.](https://caniuse.com/js-regexp-lookbehind.)

cc @psmyrek

**Comment by psmyrek** [comment]
It's funny, but the lookbehind and lookahead are not needed in the regex anymore 😅

**Comment by pomek** [comment]
Fixed in https://github.com/ckeditor/ckeditor5/commit/31f6ae969cc8ff20f26e84326e63e750397d0111.
