### ISSUE TITLE
It should be possible to enforce tables to contain a header row by default

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10039]
## 📝 Provide a description of the new feature

I've had a discussion with two independent CKEditor 5 users who would like the tables to be inserted with a header row and a regular row by default.

That's something that should definitely go behind an opt-in configuration option.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by godai78** [comment]
We don't have this covered in the documentation, right? Would be nice to at least add a mention for that.

**Comment by 108signals** [comment]
Amazing - thank you @mlewand for making this happen!
