### ISSUE TITLE
Track changes plugin is not compatible with inline widget (code from demo)

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#10036]
## 📝 Provide detailed reproduction steps (if any)

![CPT2107011210-1881x98](https://user-images.githubusercontent.com/11577626/124107407-7d14cf80-da65-11eb-8a31-7408a53b492a.gif)

1. Install track changes plugin
2. Implement code from demo: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html
3. Click on track changes icon

### ✔️ Expected result

Inline widget should be enable

### ❌ Actual result

Inline widget is disabled

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: …
* Installed CKEditor plugins: **TrackChanges**, CommentsAdapter, **Placeholder**,
  HorizontalLine, SpecialCharacters, SpecialCharactersEssentials, PageBreak, Highlight, RemoveFormat, Font,
  TableProperties, TableCellProperties, Table, TableToolbar, SimpleUploadAdapter, Image, ImageToolbar, ImageCaption, ImageStyle, ImageResize, LinkImage, FindReplace, WordCount, Link,
  AutoLink, Alignment, ListStyle, Indent, IndentBlock, Essentials, Bold, Italic, Underline, Strikethrough, Code, Subscript, Superscript, Paragraph

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! All features should have a custom integration with Track Changes. It means that if you introduce a new feature, it won't work with Track Changes out-of-the-box - you should provide an integration. We have a [guide explaining this process](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-custom-features.html), so feel free to read it and try it out!

Apart from that, please note that Track Changes is our commercial feature and this repository is dedicated to an open-source part of it. If you'd have more questions, please reach us [via our support channel](https://ckeditor.com/contact/), where our dedicated team will assist you with your query.

**Comment by Madejczyk** [comment]
@Mgsy Thank you very much.
The above problem resolved.
My client uses CKEditor4 with Loopindex plugin and we have a plan to migrate to CKEditor5 with this feature, so If I will have more questions I will reach you on support channel.
