### ISSUE TITLE
Inconsistent demo section in our package's README.md

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10045]
## 📝 Provide a description of requested docs changes

Some feature have mentioned section:

*   [https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-image/README.md#L12](https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-image/README.md#L12)
*   [https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-mention/README.md#L12](https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-mention/README.md#L12)
*   [https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-page-break/README.md#L12](https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-page-break/README.md#L12)

While (vast majority) others don't:

*   [https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-code-block/README.md#L10](https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-code-block/README.md#L10)
*   [https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-restricted-editing/README.md#L10](https://github.com/ckeditor/ckeditor5/blob/3e63cf3681ada2eef9fa548a50436658fb8ceabd/packages/ckeditor5-restricted-editing/README.md#L10)

We should unify this and add demo section to all applicable packages.

**Comment by godai78** [comment]
The image feature link is invalid, by the way.

**Comment by godai78** [comment]
We may want to make it a part of #9793
