### ISSUE TITLE
Q: Define the position of the editor's first line

### ISSUE THREAD

**Issue by balszab** [ckeditor/ckeditor5#1004]
## Is this a bug report or feature request? (choose one)

Other, question

## 💻 Version of CKEditor

ckeditor5-build-classic-1.0.0-beta.3

## Question
 
Could you tell us how we could insert text into the first line of editor? We have a button/plugin which should always insert a timestamp into the first line.

We can insert the timestamp like this:

editor.model.change( writer => {
    const insertPosition = editor.model.document.selection.getFirstPosition();
    writer.insertText(timestamp, insertPosition);
} );

The insertPosition should be the position of the editor's first line. Could you help us how we can define it please?

**Comment by Reinmar** [comment]
I think that alternative solution to @scofalik's 2nd scenario is using the `getNearestSelectionRange()` like I explained in https://stackoverflow.com/questions/49358150/is-there-any-way-to-select-all-the-content-of-ckeditor-5-by-code.

However, if an image (or another object) starts the content, then you'll get a non-collapsed range which will contain this image). In such situation, you'll want to insert a paragraph before it like in @scofalik's first scenario.

**Comment by Reinmar** [comment]
So you always want to insert **one paragraph** at the very beginning of the content and then make sure to place the selection in another paragraph (empty as well, so if it's missing you will need to insert it too).

To underline this – you have to insert `<paragraph>TIMESTAMP</paragraph>` not just some text node. Like this:

```js
editor.model.change( writer => {
    const p = writer.createElement( 'paragraph' );
    writer.insertText( 'TIMESTAMP', p );
    writer.insert( p, editor.model.document.getRoot() );
} );
```

Then, you need to check what's the 2nd element in the root and if it's not an empty paragraph, then create another one and finally set the selection in the 2nd element of the root.

**Comment by scofalik** [comment]
I will only add that you can create `paragraph` element with text already in one step:

```javascript
editor.model.change( writer => {
    const p = writer.createElement( 'paragraph', null, 'TIMESTAMP' );
} );
```

Above should work.

**Comment by scofalik** [comment]
Wow, I was sure this is possible. Weird.
