### ISSUE TITLE
Source editing can freeze the editor when pasting some table html

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#10042]
## 📝 Provide detailed reproduction steps (if any)

1. Open all-features manual test.
2. Open source editing mode.
3. Replace the current source with the one from the snippet below.
4. Go back to editable.

```html
<figure class=\"table\" style=\"width:597px;\"><table><thead><tr><th style=\"background-color:hsl(0, 0%, 60%);\" colspan=\"2\"><span style=\"color:hsl(0,0%,100%);\">Saturday, July 14</span></th></tr></thead><tbody><tr><td style=\"background-color:hsl(0, 0%, 90%);text-align:center;\">9:30 AM - 11:30 AM</td><td><p><strong>Americano vs. Brewed - “know your coffee”</strong> with:&nbsp;</p><ul><li>Giulia Bianchi</li><li>Stefano Garau</li><li>Giuseppe Russo</li></ul></td></tr><tr><td style=\"background-color:hsl(0, 0%, 90%);text-align:center;\">1:00 PM - 3:00 PM</td><td><p><strong>Pappardelle al pomodoro</strong> - live cooking</p><p>Incorporate the freshest ingredients&nbsp;<br>with Rita Fresco</p></td></tr><tr><td style=\"background-color:hsl(0, 0%, 90%);text-align:center;\">5:00 PM - 8:00 PM</td><td><strong>Tuscan vineyards at a glance</strong> - wine-tasting&nbsp;<br>with Frederico Riscoli</td></tr></tbody></table></figure><p>&nbsp;</p>
```

### ✔️ Expected result

The editor opens with new content set during source editing.

### ❌ Actual result

Editor freezes, browser tab is unresponsive. There are no errors in the console.

## 📃 Other details

* Browser: Chrome
* OS: macOS BigSur 11.4
* Content from the above snippet was taken from Export-to-Pdf demo from our docs. It was escaped by default in Chrome dev tools console.
* If this string will be unescaped before pasting to source editing then it works correctly
* It looks like the issue is related to this attribute: `colspan=\"2\"`, changing it to `colspan="2"` without changing anything else will correctly open new content in the editor

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
It seems that this issue is not related to the source editing feature. It is quite easy to reproduce it even without this feature:

1. Open table guide: https://ckeditor.com/docs/ckeditor5/latest/features/table.html.
2. In the browser console call: `editor.setData('<table><tr><td colspan="abc"></td></tr></table>')`.

or

1. Find any manual test that has table feature enabled.
2. Set the following content as the editor initial data: `<table><tr><td colspan="abc"></td></tr></table>`.
3. Open this test.

**Comment by psmyrek** [comment]
From what I have discovered so far, the problem arises when a `rowspan` or `colspan` values exist but they cannot be converted to a number with `parseInt()`, so `parseInt()` returns `NaN`. Therefore, `TableWalker#next()` runs over and over on the same table cell, indefinitely.

**Comment by LukaszGudel** [comment]
If you:
1. Open table guide: [https://ckeditor.com/docs/ckeditor5/latest/features/table.html](https://ckeditor.com/docs/ckeditor5/latest/features/table.html).
2. Set content with: `editor.setData('<table><tr><td colspan=\"2\"></td></tr></table>')`.

it will work, but if you:

1. Open editor with source editing plugin.
2. Edit source and set it to: `<table><tr><td colspan=\"2\"></td></tr></table>`.
3. Go back to editable.

then it will freeze.

**Comment by psmyrek** [comment]
> If you:
> 
>     1. Open table guide: https://ckeditor.com/docs/ckeditor5/latest/features/table.html.
> 
>     2. Set content with: `editor.setData('<table><tr><td colspan=\"2\"></td></tr></table>')`.
> 
> 
> it will work [...]

Yeah, but this is only related to how quotes are escaped/unescaped in the browser's console. If you set content with `editor.setData('<table><tr><td colspan=\\"2\\"></td></tr></table>')` then it also hangs the editor in the table guide in the docs.

**Comment by psmyrek** [comment]
This problem also exists when `colspan` is 0: `<table><tr><td colspan="0"></td></tr></table>`.
According to the HTML spec, `colspan` value must be a valid non-negative integer greater than zero and less than or equal to 1000.

**Comment by Mgsy** [comment]
**Note**: It's not a regression (checked on version 22.0.0).
