### ISSUE TITLE
Then ? appeared in the ck editor and &nbsp; came out instead of

### ISSUE THREAD

**Issue by itgmnew** [ckeditor/ckeditor5#10052]
## Provide a description of the task

I copied my word text 
And i was paste it by  ctrl + v or mouse paste

Then ? appeared in the ck editor and &nbsp; came out instead of

Is there a way to replace the ? with a space Or is there any way to prevent this?

This is a symptom that occurs when using the Euk-kr environment and changing the ck editor to Euk-kr.

## 📃 Other details

* CKEditor version: CKEditor 5

**Comment by FilipTokarski** [comment]
Hi, could you describe precisely, step by step, how to reproduce this issue?

**Comment by itgmnew** [comment]
@FilipTokarski 
thank you~!


Help- me! 
Help+ me! 
Help_ me! 

1. If you copy and import the above sentences from OneNote,


2. It becomes like the picture below. **? is appended** and **converted to italics.**

![image](https://user-images.githubusercontent.com/33151558/124438646-6cd95900-ddb3-11eb-9d12-58f4b50ca28a.png)


 'help me! ' (There is a space after the exclamation mark.)


3. If you check it in Chrome, you will find something like this:

`<p style="margin-left:0in;"><span lang="en-US" dir="ltr">Help-</span><span lang="ko" dir="ltr"> me</span><span lang="en-US" dir="ltr">!?</span></p>`


4. Since it is an Euc-kr environment, it seems to occur when changing ckedior5 to Euc-kr.

Is there any way to solve this problem?

**Comment by FilipTokarski** [comment]
Currently CKEditor5 does not officially support pasting from OneNote ( which I suppose is the main problem here ) and I don't think there is some go-to workaround. I would kindly ask you then to confirm that this issue happens only when pasting from OneNote and not with other apps ( MS Word, etc. ). If that's the case and you would like to see this implemented, we can turn this issue into a feature request.
