### ISSUE TITLE
GHS Research: Applying attributes to existing features - table

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10072]
## Provide a description of the task

A research ticket for the main task - #9914.

> Due to the complex model structure of the [Table](https://ckeditor.com/docs/ckeditor5/latest/features/table.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.

**Comment by jacekbogdanski** [comment]
The integration is very similar to what we did for CodeBlock feature. I don't really see any hard-to-solve issues. I will follow up research results with PR for https://github.com/ckeditor/ckeditor5/issues/9914
