### ISSUE TITLE
GHS Research: Applying attributes to existing features - image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10074]
## Provide a description of the task

A research ticket for the main task - #9916.

> Due to the complex model structure of the [Image](https://ckeditor.com/docs/ckeditor5/latest/features/image.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.

## Goals
- [x] Conversion of block images.
- [x] Conversion of inline images.
- [x] Conversion of a linked image.
- [ ] Problematic cases:
  - [x] Issue: Creation of an empty `<figure>` element.
  - [ ] Issue: Changes on inline image attributes are clearing the caption and its attributes. ( [comment](https://github.com/ckeditor/ckeditor5/issues/10074#issuecomment-893281691) )
  - [x] Issue: Upcasting `<figure>` element in ImageBlockEditing and MediaEmbedEditing.
  - [ ] Issue: Empty `href` attribute of image makes the link disappear. ( [comment](https://github.com/ckeditor/ckeditor5/issues/10074#issuecomment-893281691) )
  - [x] How the image model will behave when switching between those two image model types above?
  - [x] Turning the caption on/off and switching between image model types.

## Decisions
- The `picture` element. Are we planning to support this feature as a part of this task?
  - We'll postpone this part for now.

**Comment by maxbarnas** [comment]
The best way to find problems is to start implementation, which I did :) Current table integration is a really good place to start the work off. With a rough manual test in place, I updated conversion methods to use `img` HTML element; also got rid of all the helper calls preserving attributes on table-related elements, like `th`, `td`, etc.

I focused on block image, as it is using `figure` element, similarly to a table. This became a quick win and soon after I just added upcast and then downcast converters for inline image. All worked fine almost with no additional work.

**Comment by maxbarnas** [comment]
While testing I came across a case, which later got included in the goals - what will happen if we switch an image from one type to another, e.g. block to inline? Initial checks in the manual test show that it works fine and preserves all the attributes.

Still, this definitely should be covered by unit tests, along with other other possible cases like adding a caption to block image, then changing it to inline image, then back to block - we should have the caption preserved and also have all the attributes of caption restored.

**Comment by maxbarnas** [comment]
Found a problem with editing `<figcaption>` classes in Source Editing mode. The changes are not preserved, even though changed on e.g. a data attribute or the contents of `<figcaption>` are.

**Comment by maxbarnas** [comment]
Another case: 
1. Add caption to the block image, set some allowed classes, attributes, or styles on it.
1. Change image from block to inline.
1. In source editing mode change class on the image (or attribute or style.)
1. Change back to block image and turn on the caption.

All the custom attributes on the caption are now gone. I expect the image caption feature to have something to do with that.

**Comment by maxbarnas** [comment]
The problem happens because the map storing previously created captions cannot match `imageModelElement`:
https://github.com/ckeditor/ckeditor5/blob/v29.1.0/packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js#L228-L232

Need to figure out why exactly the image model is recreated when changing one of its attribute's value. Is it related to the differ forcing new conversion on image?

**Comment by maxbarnas** [comment]
The initial check shows that linking images needs more work. There's an empty `<figure>` element created each time the markup of `<img>` in source editing mode is changed. Later on, even without changes, it keeps adding that empty `<figure>` when toggling on/off the source editing mode.

On the other hand, upcasting seems to work fine and the attributes of image are preserved when the link is added.

**Comment by maxbarnas** [comment]
While testing linking images and how GHS handles that, I found that on upcast we were constantly having extra `<figure>` elements. With the help of @niegowski we chased the problem - apparently some features either do even care about if their main element is in figure or try to upcast it but do not consume the figure - which then is handled by GHS and thus the empty figure element.

**Comment by maxbarnas** [comment]
Another case with image linking - when `href` attribute is empty, going back and forth from Source Editing mode removes the link altogether.

**Comment by maxbarnas** [comment]
Just cleaned up the code a bit and updated the state of ongoing issues in the task description. 
To summarize:
- need to add unit tests for linked images,
- decide whether we want to do something with disappearing caption data when editing the image in inline mode,
- take care of a bug with an empty `href`, which removes the link from the image.

**Comment by Mgsy** [comment]
The research is done. The rest of the work will be covered in #9916.

**Comment by Reinmar** [comment]
Some remaining decisions:

*   Decide whether we want to do something with disappearing caption data when editing the image in inline mode,
    *   Test case:
        *   Change a block image (with a caption) to the inline.
        *   Enter the source editing and add some new attribute to the `<img>` element. NOTE: It's enough to change anything. It doesn't have to be related to the `<img>`.
        *   Leave the source editing and add the caption to the image.
        *   We've lost the caption content with all attributes (only on the caption).
    *   **Decision**: It's unrelated with GHS and we won't handle it.

**Comment by maxbarnas** [comment]
Regarding **Issue: Empty href attribute of image makes the link disappear.**:
- This can be reproduced outside of GHS scope and seems to be a problem with Link Image plugin.

**Therefore I marked it as done.**
