### ISSUE TITLE
GHS Research: Applying attributes to existing features - lists

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10073]
## Provide a description of the task

A research ticket for the main task - #9917.

> Due to the complex model structure of the [Lists](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.
> 
> For now, it's possible to extend `li` elements. `ul` and `ol` elements are removed during upcasting to the model. We could probably preserve them on e.g. the first list item of the list and restore them during downcast conversion.

**Comment by Reinmar** [comment]
Let's assume it's done :) We'll now work on a real implementation in #9917.
