### ISSUE TITLE
Wrong date on main website (2017)

### ISSUE THREAD

**Issue by eahrold** [ckeditor/ckeditor5#1009]
Sorry if this isn't the place to post the issue, but date says 2017 on https://ckeditor5.github.io

<img width="208" alt="screen shot 2018-04-29 at 11 46 07 am" src="https://user-images.githubusercontent.com/3740088/39408890-06676a5e-4ba3-11e8-940f-e48462cb03ba.png">

**Comment by Reinmar** [comment]
Thanks for reporting! Fixed.
