### ISSUE TITLE
Autolink documentation is invalid

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10098]
## 📝 Provide a description of requested docs changes

Currently, our docs say that Autolink is not available by default and should be installed:

> Unlike the base link feature, the autolink plugin is not available in any of the builds. Refer to the [Installation](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#installation) section to learn how to enable it.

> The autolink feature is not available in any of the builds and needs to be installed first. Read more about [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

That's not true since we've [added Autolink as a required plugin](https://github.com/ckeditor/ckeditor5/commit/8d3ac892e398279f2c65166c864cb218cb880f8d#diff-97393c91b72ff9111d433dd5ec6bd2871d522aa211a9ef3ec586210462d2e67b) for the Link plugin.

Should the Autolink feature be enabled by default? If yes, we should update the documentation.

**Comment by pomek** [comment]
Related https://github.com/ckeditor/ckeditor5/issues/9791.
