### ISSUE TITLE
HTML comments: compatibility with empty table cell

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#10116]
## Provide a description of the task

Comment inside empty table cell throws an error after calling `editor.getData()`.

Steps to reproduce:
1. Open `HtmlComment` manual test: http://localhost:8125/ckeditor5-html-support/tests/manual/htmlcomment.html.
2. Call `editor.setData( '<table><tr><td><!-- Comment --></td></tr></table>' )`.
3. Call `editor.getData()`.

Error:

```
Uncaught TypeError: Cannot read property 'name' of undefined
    at Mapper.getModelLength (mapper.js:486)
    at Mapper.findPositionIn (mapper.js:550)
    at Mapper.on.priority (mapper.js:108)
    at Mapper.fire (emittermixin.js:199)
    at Mapper.toViewPosition (mapper.js:335)
    at DowncastDispatcher.<anonymous> (downcasthelpers.js:876)
    at DowncastDispatcher.fire (emittermixin.js:199)
    at DowncastDispatcher.convertMarkerAdd (downcastdispatcher.js:413)
    at DataController.toView (datacontroller.js:260)
    at DataController.stringify (datacontroller.js:213)
```

**Comment by psmyrek** [comment]
This issue is caused because a single paragraph, located inside a table cell, is bound to its parent (to the table cell), so comment's position is pointing to a non-existent model offset in that table cell.

https://github.com/ckeditor/ckeditor5/blob/9b44100696ce09d61bf2442319dc4cf15c2146c1/packages/ckeditor5-table/src/converters/downcast.js#L380-L387

I think that the simplest solution would be to create a post fixer in the `HtmlComment` plugin and move such comments to the beginning of the table cell.

**Comment by psmyrek** [comment]
After a f2f call we decided to try solving this issue in more generic way by using the [`modelToViewPosition`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_mapper-Mapper.html#event-modelToViewPosition) event in `Table` plugin instead of a post-fixer in `HtmlComment` plugin.

**Comment by ma2ciek** [comment]
Closed by https://github.com/ckeditor/ckeditor5/pull/10187.
