### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules: node_modules/@ckeditor/ckeditor5-find-and-replace

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#10112]
## 📝 Provide detailed reproduction steps (if any)
![image](https://user-images.githubusercontent.com/11577626/124953831-c50f9580-e015-11eb-9402-fb3384f1f7c4.png)

1. Install ckeditor5-find-and-replace
2. Add import FindAndReplace from '@ckeditor/ckeditor5-find-and-replace/src/findandreplace';
3. Use import in plugins and add 'FindAndReplace' into toolbar config

### ✔️ Expected result

Application is not crash

### ❌ Actual result

Crash application

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: 29.0.0
* Installed CKEditor plugins: …
    "@ckeditor/ckeditor5-inspector": "^2.2.2",
    "@ckeditor/ckeditor5-revision-history": "^29.0.0",
    "@ckeditor/ckeditor5-alignment": "^29.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^29.0.0",
    "@ckeditor/ckeditor5-comments": "^29.0.0",
    "@ckeditor/ckeditor5-core": "^29.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^29.0.0",
    "@ckeditor/ckeditor5-essentials": "^29.0.0",
    **"@ckeditor/ckeditor5-find-and-replace": "^29.0.0",**
    "@ckeditor/ckeditor5-font": "^29.0.0",
    "@ckeditor/ckeditor5-highlight": "^29.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^29.0.0",
    "@ckeditor/ckeditor5-image": "^29.0.0",
    "@ckeditor/ckeditor5-indent": "^29.0.0",
    "@ckeditor/ckeditor5-link": "^29.0.0",
    "@ckeditor/ckeditor5-list": "^29.0.0",
    "@ckeditor/ckeditor5-page-break": "^29.0.0",
    "@ckeditor/ckeditor5-paragraph": "^29.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-remove-format": "^29.0.0",
    "@ckeditor/ckeditor5-restricted-editing": "^29.0.0",
    "@ckeditor/ckeditor5-special-characters": "^29.0.0",
    "@ckeditor/ckeditor5-table": "^29.0.0",
    "@ckeditor/ckeditor5-track-changes": "^29.0.0",
    "@ckeditor/ckeditor5-ui": "^29.0.0",
    "@ckeditor/ckeditor5-upload": "^29.0.0",
    "@ckeditor/ckeditor5-widget": "^29.0.0",
    "@ckeditor/ckeditor5-word-count": "^29.0.0",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, I just checked Find and Replace package and I cannot reproduce this issue. Plugin works as expected both in React integration and in a standalone editor. Maybe you could try removing `package-lock.json` ( or `yarn.lock` ) together with `node_modules` and install everything again.
If that does not help, we'll need more information and a detailed step-by-step description to reproduce this.

**Comment by Madejczyk** [comment]
Hello Filip. 
Problem resolved. I have installed package second times and all works fine :)
