### ISSUE TITLE
Will there be a code insertion function later?

### ISSUE THREAD

**Issue by 13146595984** [ckeditor/ckeditor5#1011]
Try to write it yourself, trapped by the code........

**Comment by Reinmar** [comment]
What do you mean by code insertion function? Just like https://ckeditor.com/cke4/addon/codesnippet?

**Comment by 13146595984** [comment]
yes

**Comment by Reinmar** [comment]
Then it's a DUP of https://github.com/ckeditor/ckeditor5/issues/436 :)
