### ISSUE TITLE
HTML comments: Blockquote containing only a comment is removed

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#10121]
## Provide a description of the task

Steps to reproduce:

1. Open `HtmlComment` manual test: http://localhost:8125/ckeditor5-html-support/tests/manual/htmlcomment.html.
2. Call `editor.setData('<blockquote><!-- comment --></blockquote>')`. Blockquote has not been added.
3. Call `editor.setData('<blockquote><!-- comment --><p>Paragraph</p><!-- comment --></blockquote>')`. Blockquote is added and `editor.getData()` returns both comments from blockquote, as expected.

**Comment by Reinmar** [comment]
An empty blockquote (the comment has little value here) is always removed by the editor. So, I'd say this is correct. A blockquote must be filled with some kind of a block (paragraph, heading) to be preserved.
