### ISSUE TITLE
Comments feature: Whole placeholder message is not visible

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#10132]
## 📝 Provide a description of the improvement

Inline comment popup should display whole placeholder message
![image](https://user-images.githubusercontent.com/11577626/125314568-9a378100-e336-11eb-9cc2-b05bcc35545b.png)

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 29.0.0
* Installed CKEditor plugins:
    "@ckeditor/ckeditor5-alignment": "^29.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^29.0.0",
    "@ckeditor/ckeditor5-comments": "^29.0.0",
    "@ckeditor/ckeditor5-core": "^29.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^29.0.0",
    "@ckeditor/ckeditor5-essentials": "^29.0.0",
    "@ckeditor/ckeditor5-find-and-replace": "29.0.0",
    "@ckeditor/ckeditor5-font": "^29.0.0",
    "@ckeditor/ckeditor5-highlight": "^29.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^29.0.0",
    "@ckeditor/ckeditor5-html-support": "^29.0.0",
    "@ckeditor/ckeditor5-image": "^29.0.0",
    "@ckeditor/ckeditor5-indent": "^29.0.0",
    "@ckeditor/ckeditor5-link": "^29.0.0",
    "@ckeditor/ckeditor5-list": "^29.0.0",
    "@ckeditor/ckeditor5-page-break": "^29.0.0",
    "@ckeditor/ckeditor5-paragraph": "^29.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-remove-format": "^29.0.0",
    "@ckeditor/ckeditor5-restricted-editing": "^29.0.0",
    "@ckeditor/ckeditor5-source-editing": "^29.0.0",
    "@ckeditor/ckeditor5-special-characters": "^29.0.0",
    "@ckeditor/ckeditor5-table": "^29.0.0",
    "@ckeditor/ckeditor5-track-changes": "^29.0.0",
    "@ckeditor/ckeditor5-ui": "^29.0.0",
    "@ckeditor/ckeditor5-upload": "^29.0.0",
    "@ckeditor/ckeditor5-widget": "^29.0.0",
    "@ckeditor/ckeditor5-word-count": "^29.0.0",

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We checked it but couldn't reproduce the issue, however it looks like a wrong styling on the comment item, which could be adjusted with the proper css.
  
Apart from that, please keep in mind that Comments is a commercial feature and this issue tracker is mainly for the purpose of the open source part of the CKEditor project. If you already have a license and need any assistance, please [contact our support team](https://ckeditor.com/contact/). We'll be happy to investigate the problem and get back to you as soon as possible.
