### ISSUE TITLE
Consider introducing single file DLL builds

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#10142]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

  
At the moment DLL builds generate main build (essentials) and separate build file each plugin. If a user would like to create a build out of it, he has to create a script which will copy all required files into single folder or will concatenate these files into a single one (in order to reduce number of requests to server).  
  
_If DLL builds become more popular, we will probably get users wanting this to work out of the box especially if it will reduce the number of requests._   
  
_Perhaps this could be done with the help of some extra config_ listing all plugins which should be concatenated.  

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by quicksketch** [comment]
Hi @jswiderski, I'm looking for this exact feature. I'd like the convenience of loading a single JS file but also have the ability to expose and add additional plugins on top of those in the bundled JS file. For now I've done exactly as you described, tediously concatenating all the build JS files together with `ckeditor-dll.js` as the first file, followed by all other build JS files.

I notice that when using the online builder tool, it includes the webpack.config.js and package.json to reproduce the downloaded monolithic `ckeditor.js`. This is great. Can I modify the included `webpack.config.js` to instead produce a DLL-compatible editor, where the editor is name-spaced under `CKEditor5` instead of `ClassicEditor`, with the plugin list exposed?

**Comment by Witoso** [comment]
Hey @quicksketch! I noticed a similar approach in this [SO question](https://stackoverflow.com/questions/76148541/advice-on-creating-custom-base-dll-build). 

> Where I landed was a DLL-compat package that bundles all our plugins/config: [github.com/craftcms/ckeditor/pull/97/files](https://github.com/craftcms/ckeditor/pull/97/files) The worst part was having to mimick what the package-tools webpack config does. I couldn't use it directly because it expects a specific package file structure. If [github.com/ckeditor/ckeditor5-package-generator/blob/master/…](https://github.com/ckeditor/ckeditor5-package-generator/blob/master/packages/ckeditor5-package-tools/lib/utils/get-webpack-config-dll.js) had more args to make a more flexible, I could have used it directly.

Probably you could use exactly this method.

**Comment by quicksketch** [comment]
I read the StackOverflow post and seems like CraftCMS is trying to do pretty much the same thing (I'm for Backdrop CMS :smile:). Are you suggesting that I could adapt their webpack.config.js ([latest version here](https://github.com/craftcms/ckeditor/blob/main/src/web/assets/ckeditor/webpack.config.js)) to get the desired single-file DLL build?

I'm not very familiar with webpack so I'm not sure what is happening there, but if it's worth looking into I'll make that my starting point.

**Comment by Witoso** [comment]
As far as I can see what is happening there is that our webpack was readopted to produce a DLL build that joins [their editor's package](https://github.com/craftcms/ckeditor/blob/main/src/web/assets/ckeditor/src/ckeditor5-craftcms.js) as well as [the main `ckeditor5` DLL package](https://github.com/craftcms/ckeditor/blob/main/src/web/assets/ckeditor/webpack.config.js#L58) into one that will be used in their platform.

But this is a custom setup that may later require some webpack tweaking. If you're not comfortable with it, I would suggest the concat option I think.

**Comment by Reinmar** [comment]
With the introduction of New Installation Methods in v42.0.0, we don't need to invest in DLLs more (as they will be sun set).
