### ISSUE TITLE
Find and replace multiroot support

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10146]
## 📝 Provide detailed reproduction steps (if any)

The find and replace feature should support editor with multiple document roots.

Surely we'd have to ignore special roots (that starting with the $ sign).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by JayNathSF** [comment]
This feature would be very helpful for our users who have large, quasi-legal documents in the hundreds of pages. We use the multi root editor to create a seamless experience. Currently they use the browser for finding content which is not a good workaround.
