### ISSUE TITLE
HTML Comments: `editor.getData()`cuts out  all comments when there is no more content

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#10152]
When there is no content except HTML comments these comments are lost in `editor.getData()`. I'm not sure if this is expected behavior.

**Comment by Reinmar** [comment]
Currently, `getData()` returns an empty string, which is the expected behavior. The idea behind trimming is that thanks to that it's possible to check (e.g. on a backend) whether the editor was empty by a simple `.lenght` check.
