### ISSUE TITLE
HTML comments: write docs guide

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#10159]
## Provide a description of the task

The docs guide must be created.

**Comment by Reinmar** [comment]
Scope:

*   Featured in the GHS's guide. For discoverability it might make more sense to give it a separate guide, but:
    *   it going to be marked as experimental for a longer time than GHS itself and thus promoting it too much for the broad audience may make little sense,
    *   it will be used very often with GHS anyway (similar to source editing).
*   Content:
    *   "It's an experimental feature..." box. Ask for feedback.
    *   Short description (2-3 sentences).
    *   Demo.
    *   Installation guide.
    *   Links to known issues / limitations.

**Comment by ma2ciek** [comment]
Closed by #10224.
