### ISSUE TITLE
PRs to epic branches are not tested on CI

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#10150]
With the current Travis configuration, the CI doesn't run checks for PRs pointing to the epic branch

[https://github.com/ckeditor/ckeditor5/blob/75d54796e80e4c2a92027b5d32d8089bd4289dfe/.travis.yml#L5-L10](https://github.com/ckeditor/ckeditor5/blob/75d54796e80e4c2a92027b5d32d8089bd4289dfe/.travis.yml#L5-L10)

Perhaps we should force the naming convention for the epic branches to allow testing PRs to the epic branches.

Some ideas:

*   `ck/[issue-number]-epic-[issue-name]`
*   `epic/[issue-number]-[issue-name]`

**Comment by pomek** [comment]
As we don't have any convention for that, I'd suggest adding the feature branch name to the `.travis.yml` file for feature branches.

Unfortunately, we must remember reverting the change before merging the feature branch into `#master`. It isn't a big deal if we forget it, though. A fix can push the change to the main branch later.

**Comment by Reinmar** [comment]
> *   `ck/[issue-number]-epic-[issue-name]`

I'd prefer if we prefixed those branch names with something so they are easier to spot on the list and autocomplete (I use zsh :((()

> *   `epic/[issue-number]-[issue-name]`

In this option we miss the info about the repo (`ck`, `ci`, `cf`)

So, taking both these aspects we'd end up with:

`epic/ck/[issue-number]-[issue-name]`

WDYT?

**Comment by Reinmar** [comment]
> Unfortunately, we must remember reverting the change before merging the feature branch into `#master`. It isn't a big deal if we forget it, though. A fix can push the change to the main branch later.

Perhaps that's a reason why I'd focus on finding the convention as this should be rather easy.

**Comment by mlewand** [comment]
Honestly both `ck/epic/[issue-number]-[issue-name]` and `ck/[issue-number]-epic-[issue-name]` sounds good to me.

I like the idea of running cron CI based on branch name convention - much quicker and less commiting.

**Comment by Reinmar** [comment]
> I like the idea of running cron CI based on branch name convention - much quicker and less commiting.

Why cron? I was thinking only about the CI for PRs made to feature branches – those jobs are currently not executed at all. But we don't need cron for that.

Do you mean that you'd also like cron jobs for more than `master` and `stable`? Sounds like something that might be useful but I'd ask for more clarification on the "whys". Also, to avoid scope creep in this ticket, it could be split.

**Comment by scofalik** [comment]
1.  Do we need those to be epics?
2.  I prefer `ck/epic/[issue-number]` or `ck/fb/[issue-number]` convention.

**Comment by Reinmar** [comment]
> *   Do we need those to be epics?

Not necessarily. You may have a feature branch for a single ticket, assuming that it has e.g. a longer todo-list included. But still, I think that the branch name can use the word "epic".



> 2\. I prefer `ck/epic/[issue-number]` or `ck/fb/[issue-number]` convention. (fb = feature branch)

Someone has to make the call. So let it be: `[ck|cf|ci]/epic/[issue-number]`

**Comment by pomek** [comment]
I wrote a few simple tests for this regexp for future reference - https://regex101.com/r/6AtJvN/1.
