### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by tkutyanov** [ckeditor/ckeditor5#10162]
## 📝 Provide detailed reproduction steps (if any)

1. See the attched screenshot
![2021-07-15 18_01_16-CKeditor _ Brand new board](https://user-images.githubusercontent.com/72975029/125810985-95d5b14d-f7ae-4749-80fa-4dc91c8f987f.png)
2. Make different levels of indentation: first level is numbering, second is bulleting, third one is checkbox
3. Go backwards.

### ✔️ Expected result

When going from second to first level (i.e. bulleting to numbering), to have bulleting continued.

### ❌ Actual result

Bulleting 

## 📃 Other details

* Browser: Chrome
* OS: Win 10
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. This bug is known and [is tracked in another ticket](https://github.com/ckeditor/ckeditor5/issues/7922). I'll close this as a duplicate.
