### ISSUE TITLE
user urgent problem

### ISSUE THREAD

**Issue by fangyuan-zheng** [ckeditor/ckeditor5#10164]
**Urgent**
Hi, 
We are a Chinese Company named ToE and currently using CKeditor5 for our product. However,  there is a problem with the track changes feature in IEM when the language is Chinese.  This is a very serious and urgent problem for our product so we message you to get help. Could you provide your contact info or arrange an online meeting for us? 
Thank you for reading and looking forward to your reply.

**Comment by FilipTokarski** [comment]
Hi, if you are a licensed customer, you can always [reach out to our support team](https://ckeditor.com/contact/), which will get back to you as soon as possible.

**Comment by KevinWang15** [comment]
Same as: https://github.com/ckeditor/ckeditor5/issues/10219

**Comment by FilipTokarski** [comment]
Closing as a duplicate, will be resolved by https://github.com/ckeditor/ckeditor5/issues/7462.
