### ISSUE TITLE
It's hard to escape from link areas

### ISSUE THREAD

**Issue by ralfbeine** [ckeditor/ckeditor5#1016]
🆕 Feature request

## 💻 Version of CKEditor
ckeditor5/10.0.0
classic build

## 📋 Steps to reproduce

1. type a text
2. mark the last word and make it a link\
3. continue typing
4. now we are still in the link  and need to type right 2 times to escape of the link

## ✅ Expected result
if i continue to type i would not expect to enlarge the link area i just defined. It would be totally o.k. to redo the link actions if i need to change this.

## ❎ Actual result
I'm prisoner of a link and had much difficulties to find out how to escape.

## 📃 Other details that might be useful
none... just change it please. And thank you for your great work!

**Comment by scofalik** [comment]
If I understood you correctly, this is an expected behavior - a feature, rather than a bug. This way we are giving the user a possibility - to write inside or outside the link - when the caret is at the end of it. Highlight behind the link denotes whether the caret is inside the link or not. We could discuss if this should be a configurable option but the gain provided by this feature is much bigger than the loss.

**Comment by ralfbeine** [comment]
My concern on this is that the majority of Users will not understand why they have to double tap the right button to continue writing as normal. Well its only a Problem if you mark the last text symbols and make it a link and then try to write further without expanding the link. double Tap right is not really intuitive. i pressed space escape, but nothing helped. If it would be the bold or italic button you just hit it again. with links its more complicated. So, yes its a very unexpected behavior. Not a Bug. 
I think this should be a configurable option if not the default, in my opinion this would be much easier for the non experts out there.

greetings, Ralf

**Comment by scofalik** [comment]
I agree that at the end of the block it might be less intuitive to discover this feature. Thanks for your input. We'll discuss what to do next.

**Comment by ralfbeine** [comment]
After some thinking about it, i would suggest a combination of both behaviors, the caret could be placed just right outside of the link, so you can type further without the need of do anything else, but if i want to exand the link i have to place the caret with mouse or keyboard inside the link, if i do i do it intentional. In my Opinion that would be a great option.

**Comment by theigl** [comment]
I'd be very interested in the solution suggested by @ralfbeine or in a configurable option to place the caret after the link.

@Reinmar: Is there any workaround I can use for now until this is implemented? I tried manually triggering an arrow-right keyboard event on the source element but that doesn't work.

**Comment by jswiderski** [comment]
I had the same idea as @ralfbeine - put caret outside of the link by default. This will allow users to type standard text and enter the link if they want to further edit it.

**Comment by wwalc** [comment]
Okay, I just faced the same issue as others. My use case:

I'm writing a text and then hit the "Link" button, type `https://ckeditor.com` (the domain name that I know, I did not copy it from anywhere), click "Save".

I'm inside the link so I press `arrow right` (to escape from the selection), `space` (to get out of the link). 

![](https://user-images.githubusercontent.com/545175/70507859-8958d500-1b2d-11ea-8637-6b023acddeae.png)

![](https://user-images.githubusercontent.com/545175/70507877-95449700-1b2d-11ea-8e02-c7c44ff20290.png)

![](https://user-images.githubusercontent.com/545175/70507888-9970b480-1b2d-11ea-983d-2b169b167156.png)

![](https://user-images.githubusercontent.com/545175/70507897-9d043b80-1b2d-11ea-984a-f9f38396c360.png)

Conclusion: maaaaybe we should consider something like user intention or sth. I just inserted a link, the link is at the end of the paragraph, in 99.9999% of cases I simply want to type plain text after it.

**Comment by scofalik** [comment]
There are two things here:

1. You should be able to do that simply pressing right arrow key. No doubt about it. In this regard, I'd consider current situation a bug.
2. The other thing is behavior of the feature after you add a link. I personally don't like that the whole link is selected and there's tooltip shown. I'd be perfectly fine if the selection is collapsed after the link (so that you also don't write in a link).

**Comment by wwalc** [comment]
@scofalik

> The other thing is behavior of the feature after you add a link. I personally don't like that the whole link is selected and there's tooltip shown. I'd be perfectly fine if the selection is collapsed after the link (so that you also don't write in a link).

+100
