### ISSUE TITLE
About translation service ，-->editor.t( 'code segment' )

### ISSUE THREAD

**Issue by 13146595984** [ckeditor/ckeditor5#1017]
![qq 20180510113556](https://user-images.githubusercontent.com/15777183/39850950-ac482e62-5446-11e8-8d6b-6d482469092f.png)

If I create a plugin that wants to use him, how should I configure it?

**Comment by ma2ciek** [comment]
Hi, @13146595984.

Unfortunately, we don't have docs for that topic for now, but I hope it'll change soon.

To use localization features you'll need to do following steps:

First, create `locale/translations` directory and create there your localization files.

```
-root-of-the-plugin
   |-locale
       |-translations
```

These translations have to follow the *PO* format. See e.g. one of these *PO* files https://github.com/ckeditor/ckeditor5-block-quote/tree/master/lang/translations to easily write your own.

You can use existing translations listed in the https://github.com/ckeditor/ckeditor5-core package. They always load first.

Second, use the `this.editor.t()` function in the plugin or `locale.t()` function inside the component factory callback (https://github.com/wwalc/ckeditor5-emoji/blob/master/src/emoji.js#L53)

Important: 
1. The `t()` function has to be named `t`. It can be a method, like `locale.t()` or passed somewhere as a standalone function (used as `t()` later.
2. The `t()` function takes only literal string arguments. Webpack process later all `t()` functions found in the code and replaces their arguments. E.g. `t( label )` is forbidden, but the `const label = someCondition ? t( 'x' ) : t( 'y' )` is allowed.

Then it's possible to create a localized build with your own plugin following instructions from https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/ui-language.html#building-the-editor-using-a-specific-language.

**Comment by 13146595984** [comment]
Thanks
