### ISSUE TITLE
Docs: Typo in Real-time collaborative comments guide

### ISSUE THREAD

**Issue by BBlackwo** [ckeditor/ckeditor5#10175]
In the [Real-time collaborative comments guide](https://ckeditor.com/docs/ckeditor5/12.0.0/features/collaboration/real-time-collaboration/real-time-collaborative-comments.html) there is a typo.

>When using it, you do not need to create any adapters to define how to store the comments data since they are saved in CKEditor Could Services.

It should say `Cloud Services` instead of `Could Services`.

I couldn't find the docs on your repo, otherwise I would have just created a PR to fix it :slightly_smiling_face:

**Comment by FilipTokarski** [comment]
Hi, thanks for the report! We'll fix it soon.

**Comment by FilipTokarski** [comment]
Actually, I just noticed that this link refers to the documentation in version `12.0.0`. As the current version is `29.0.0` and docs were changed significantly since then, I'll close this as invalid.

**Comment by BBlackwo** [comment]
Sorry about that @FilipTokarski. I didn't realise I was on version `12.0.0`. Don't even know how I managed to open that version :thinking:

**Comment by FilipTokarski** [comment]
No problem, it happens sometimes that google search shows older versions. 
A tip for the future - if you would like to check any other version of the docs, you can just change this part of URL to for example `15.0.0` or `17.1.0`. I sometimes find it very useful. By default this part should always be `latest`.
