### ISSUE TITLE
Remove code artifacts from find and replace source code

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10170]
## Provide a description of the task

There are some leftover creeps like `activeResults` member in editing plugin: https://github.com/ckeditor/ckeditor5/blob/927c24a294e70d1a5d8a666a9a8d8651be20fba0/packages/ckeditor5-find-and-replace/src/findandreplaceediting.js#L97

**Comment by Reinmar** [comment]
I can see that it's used. Did you mean to make it protected?

Also, what other code artifacts did you mean? How should we look for them now?

**Comment by Reinmar** [comment]
Let's work on such artifacts as side-quests of other tasks. It's unclear here what are we supposed to do and searching this seems to make no sense.
