### ISSUE TITLE
Find & replace + RTC: cannot replace after editing the word and undo on another client

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10185]
### Steps to reproduce:
On branch `ck/10023`

1. Open editor with Find & Replace on two clients
2. On client A search for some word (it gets highlighted)
3. On client B edit this word so that the highlight on A disappears
4. On B undo (highlight on A appears again, everything seems to be ok for now)
5. On A click `Replace`

### Expected:
The word on A is replaced.

### Actual:
The word is properly highlighted but you cannot replace it. You need to close the dropdown, open it again and click `Find` - then it works.

### Screencast:

https://user-images.githubusercontent.com/34380544/126306771-0450fe74-9d93-4547-a568-24c27e4bab1a.mp4

**Comment by LukaszGudel** [comment]
Changes from branch `ck/10023` were not merged to master and this issue can not be currently reproduced.
