### ISSUE TITLE
Find & replace: Match case and whole words do not work after recent merges

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#10188]
## 📝 Provide detailed reproduction steps (if any)

1. Open editor with F&R plugin with ckeditor5 repo on branch `ck/10023`
2. Search a character `a` with "Whole words only" flag.

### ✔️ Expected result

Only single words ` a ` will be highlighted.

### ❌ Actual result

Every `a` character is highlighted, while UI is not showing any results and there are no arrow buttons to go through the results.
![image](https://user-images.githubusercontent.com/58658048/126323154-736d8802-d7df-4c05-9f73-6c028113c167.png)

## 📃 Other details

The same result will be produced when searching for `A` with "Match case" flag.

This regression on branch `ck/10023` was introduced after merging `origin/ck/10024-find-and-replace-followups` into `ck/10023` with commit `5c2b2db`. Before this commit, these search flags are working correctly.

**Comment by Reinmar** [comment]
We dropped ck/10023 during the feature handoff. I'm closing this ticket as it's not reproducible on `master.`
