### ISSUE TITLE
Switching to source editing scrolls to the end of the content

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10180]
## 📝 Provide detailed reproduction steps (if any)

1.  Have some visibly long content in the editor
2.  Be at the beginning of it
3.  Click the "Source editing" button

### ✔️ Expected result

The scroll either stays intact or scrolls to the top.

### ❌ Actual result

The scroll moves to the end of the content.

![](https://user-images.githubusercontent.com/156149/126148472-365b5610-93e0-4005-a828-cb993dbe9913.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
To be checked: How it works in CKEditor 4.

**Comment by maxbarnas** [comment]
Just checked how this feature behaves in CKE4
- Default Source Editing Area (which resembles Source Editing in CKE5 the most) always scrolls to the top,
- Source Dialog always scrolls to the end of the text.

**Comment by maxbarnas** [comment]
The point #4 explains current behavior of textarea: https://html.spec.whatwg.org/multipage/form-elements.html#dom-textarea-value
