### ISSUE TITLE
Default table properties are not applied to data

### ISSUE THREAD

**Issue by piyushk96** [ckeditor/ckeditor5#10196]
## 📝 Provide detailed reproduction steps (if any)

https://user-images.githubusercontent.com/41179062/126403195-c00a4096-02c4-4012-8f4e-d832be637f7f.mov

I'm using ckeditor built from source with react and using following config for editor:
```
<CKEditor
  editor={ClassicEditor}
  config={{
    plugins: [
      Table,
      TableCellProperties,
      TableProperties,
      TableToolbar,
      TextTransformation,
    ],
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableProperties',
        'tableCellProperties',
      ],
      tableProperties: {
        defaultProperties: {
          borderWidth: '4px',
          borderStyle: 'solid',
          borderColor: 'red',
        },
      },
      tableCellProperties: {
        defaultProperties: {
          borderWidth: '1px',
          borderStyle: 'solid',
          borderColor: 'black',
        },
      },
    },
  }}
/>
```

### ✔️ Expected result

Editor data obtained by using `editor.getData()` should contain default table styles provided in `defaultProperties` of config.

### ❌ Actual result

The table is created without any styles. Styles are only applied after changing them in popup.

## 📃 Other details

* Browser: Google Chrome
* OS: MacOS
* First affected CKEditor version: using v29.0.0
* Installed CKEditor plugins: Table, TableCellProperties, TableProperties, TableToolbar, TextTransformation

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I can confirm that default properties don't seem to work as expected. After using [example from the docs](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#default-table-and-table-cell-styles) I got:
![table](https://user-images.githubusercontent.com/34380544/126747140-802befe4-7804-4b06-86ba-79b0af7007d0.png)

cc @pomek could you take a look at this?

**Comment by pomek** [comment]
Are you sure that the editor's configuration and content styles are synchronized?

**Comment by pomek** [comment]
> Editor data obtained by using editor.getData() should contain default table styles provided in defaultProperties of config.

The feature does not work this way. The default properties are not applied in the model. The editor assumes that these properties are specified in CSS and that's why they must be specified in the configuration.

**Comment by piyushk96** [comment]
@pomek then what is the purpose of `defaultProperties` if we don't get the styles in the generated data. If we have to add separate content styles then in that case I have to add styles everywhere wherever I'm using that data (different applications).

**Comment by piyushk96** [comment]
Also, if `defaultProperties` are set in config I can't just open the cell/table settings and save it with same configuration so that I get the styles appliend in data.

**Comment by pomek** [comment]
> what is the purpose of defaultProperties

The main goal of the feature is to force the table or cell properties UI window to display proper values for properties if an integrator specified custom rules for the `.ck-content table (td)` structure.

If appropriately configured, the UI is aligned with the styles defined for a particular page. Before introducing the feature, the integrator could redesigned tables/cells on its page, and the UI showed invalid values.

**Comment by piyushk96** [comment]
@pomek I think this looks a little misleading. The control should be present in the editor. Whatever is defined in editor should be reflected in data. Currently you have to add both styles and config just to show correct values in editor but at the end you will be using data for showing content on your website(which could be multiple) and that data doesn't contain any styles and you have to update stylesheets everywhere.

**Comment by Reinmar** [comment]
I understand that you find this misleading and inconvenient. I wish it could work differently and maybe one day we'll work on inlining all content styles in the content. For now, though, it's the integrator's responsibility to take care of this.

Besides, default table styles are not the only situation in which the integrator has to take care of this. It's the same for image styles, media embed styles, etc. That's what the [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) guide explains. Default table styles are in line with this. This feature, documented in [https://ckeditor.com/docs/ckeditor5/latest/features/table.html#default-table-and-table-cell-styles,](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#default-table-and-table-cell-styles,) also requires from you to maintain the content stylesheet but in this case it also allows configuring the editor so it **knows** what the default styles are like.
