### ISSUE TITLE
Find/Replace dialog should not have buttons labels all in upper case 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#10199]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html 
2.  Open Find/Replace dialog

### ✔️ Expected result

Button lables should start  only start with capital letter like in other dialogs.

![](https://user-images.githubusercontent.com/5314687/126609192-98d40087-d113-4d57-92b9-5211e2963b73.png)

### ❌ Actual result

Button names are all capital letters.

![](https://user-images.githubusercontent.com/5314687/126608864-913db1e2-d1be-41ce-8a7e-af89837ab245.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: 29.0.0
*   Installed CKEditor plugins: find-and-replace

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This is no longer valid because of #10229.

**Comment by AnnaTomanek** [comment]
I'd rather say, the issue was valid and was fixed by https://github.com/ckeditor/ckeditor5/issues/10229.
