### ISSUE TITLE
CKEditor 5 integration for Angular 2+

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1020]
**Note**: This issue is a piece of https://github.com/ckeditor/ckeditor5/issues/1002.

---

The current status of implementation, which allows some very basic interactions is as follows (see the "**Problems**" section below):

### JS code of the component

```js
import {
	Component,
	Input,
	NgZone,
	OnInit, OnDestroy,
	ElementRef
} from '@angular/core';

import {
	ControlValueAccessor
} from '@angular/forms'

@Component( {
	selector: 'ckeditor',
	template: '<div [id]="id">{{ data }}</div>'
} )
export class CKEditorComponent implements OnInit, OnDestroy, ControlValueAccessor {
	@Input() build: String = 'classic';
	@Input() config: { [ key: string ]: any } = {};
	@Input() data: String = '';
	@Input() id: String = 'editor';

	public editor: any = null;

	private componentElement: ElementRef;
	private element: HTMLElement = null;
	private ngZone: NgZone = null;
	private cvaOnChange: any = null;
	private cvaOnTouched: any = null;

	constructor( componentElement: ElementRef, ngZone: NgZone ) {
		this.componentElement = componentElement;
		this.ngZone = ngZone;
	}

	// Implementing the OnInit interface.
	ngOnInit() {
		const buildName = this.build;

		this.element = this.componentElement.nativeElement.firstChild;

		import( `../../../node_modules/@ckeditor/ckeditor5-build-${ buildName }/build/ckeditor.js` )
			.then( EditorBuild => this.createEditor( EditorBuild ) );
	}

	// Implementing the OnDestroy interface.
	ngOnDestroy() {
		if ( this.editor ) {
			return this.editor.destroy();
		}
	}

	// Implementing the ControlValueAccessor interface
	writeValue( value: any ): void {
		if ( this.editor ) {
			this.editor.setData( value );
		}
	}

	// Implementing the ControlValueAccessor interface
	registerOnChange( callback: any ): void {
		this.cvaOnChange = callback;
	}

	// Implementing the ControlValueAccessor interface
	registerOnTouched( callback: any ): void {
		this.cvaOnTouched = callback;
	}

	private createEditor( EditorBuild: any ): Promise {
		return EditorBuild.create( this.element, this.config )
			.then( editor => {
				this.editor = editor;
				this.setUpEditorEvents( editor );
			} )
			.catch( err => {
				console.error( err.stack );
			} );
	}

	private setUpEditorEvents( editor: any ): void {
		editor.on( 'change', () => {
			// See https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change.
			if ( editor.model.document.differ.getChanges().length > 0 ) {
				this.ngZone.run( () => this.cvaOnChange( editor.getData() ) );
			}
		} );

		editor.on( 'blur', () => {
			this.ngZone.run( () => this.cvaOnTouched() );
		} );
	}
}
```

### Usage in the template
```html
<h2>CKEditor demos</h2>

<h3>Classic (default)</h3>
<ckeditor data="A classic editor."></ckeditor>

<h3>Inline (also custom cfg)</h3>
<ckeditor
	build="inline"
	data="An inline editor"
	[config]="{ toolbar: [ 'heading', '|', 'bold', 'italic' ] }"
></ckeditor>

<h3>Balloon (custom id)</h3>
<ckeditor build="balloon" id="some-editor" data="A balloon editor"></ckeditor>
```

## Problems

The most important problem we face ATM is the delivery of different builds of the editor. Developers should be able to either:
* use [existing builds](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/installation.html) that we provide via NPM (e.g. `@ckeditor/ckeditor5-build-classic`) 
* use [customized editor builds](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html), e.g. to narrow or extend the set of the features, which can be achieved in 2 ways:
   * building the editor beside the Angular project, and then including it like an official build,
   * integration of the building process witin the Angular project

ATM only the first option is possible and yet it is very, very ugly:

```js
import( `../../../node_modules/@ckeditor/ckeditor5-build-${ buildName }/build/ckeditor.js` )
	.then( EditorBuild => this.createEditor( EditorBuild ) );
```

```html
<ckeditor build="name-of-the-build"></ckeditor>
```

1. Is there anything in Angular which can help us deliver a particular build (constructor) to the component? AFAIR the following is impossible in the template because it is strictly scoped to the component:
   ```html
   <ckeditor build="ClassicEditor"></ckeditor>
   ```
2. How to implement the CKEeditor component so it can be used for custom build use-cases? How to pass the editor (build) to such component? How to make the component as generic as possible? What is the most convenient solution which follows the Angular architectural conventions?

cc @Reinmar @szymonkups

**Comment by ma2ciek** [comment]
> ATM only the first option is possible and yet it is very, very ugly:
> ```
> import( `../../../node_modules/@ckeditor/ckeditor5-build-${ buildName }/build/ckeditor.js` )
>	.then( EditorBuild => this.createEditor( EditorBuild ) );```

Isn't better to statically specify the editor type and use the static import? Does someone want to dynamically pick the editor type? Or you did it to create a lighter bundle and import editor's build when the it's needed?

**Comment by ma2ciek** [comment]
Note, that in TS lowercase is used for basic types and uppercase for e.g. boxed types (like `new String()`), so you should use `string` instead of `String` - https://www.typescriptlang.org/docs/handbook/basic-types.html.

**Comment by Reinmar** [comment]
> Isn't better to statically specify the editor type and use the static import? Does someone want to dynamically pick the editor type? Or you did it to create a lighter bundle and import editor's build when the it's needed?

The `import` should be somewhere in the component's consumer code. It must not be in the component's code itself. The component must work with any build of your choice.

**Comment by Reinmar** [comment]
To exemplify what I mean – that's how we see the use of the React component:

```js
import React, { Component } from 'react';
import './App.css';
import CKEditor from 'cke5-react';
import ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic';


class App extends Component {
	render() {
		return (
			<div className="App">
				<h2>CKEditor 5 using build-classic</h2>
				<CKEditor
					editor={ ClassicEditorBuild }
					data="<p>Hello from CKEditor 5</p>"
					onChange={ data => console.log( data ) }
				/>
			</div>
		);
	}
}

export default App;
```

The `ClassicEditorBuild` is imported by the consumer and passed to the component in one of its attributes.

**Comment by ma2ciek** [comment]
So it can be done similarly from the parent component:

```ts
import { Component } from '@angular/core';

import * as ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic';

@Component( {
	selector: 'my-app',
	template:
		`<main>
			<ckeditor [editor]="editor" [data]="data"></ckeditor>
		</main>`
} )
export class AppComponent {
	private editor = ClassicEditorBuild;
	private data = "<p>Some content</p>"
}
```

The only thing is, that we don't have any TS typings for our JS files, so there is a warning when importing some CKEditor5 stuff.

**Comment by pburrows** [comment]
I think for:

> use customized editor builds, e.g. to narrow or extend the set of the features, which can be achieved in 2 ways:
> building the editor beside the Angular project, and then including it like an official build,
> integration of the building process witin the Angular project

you will need to use an implementation of an abstract factory with `componentFactoryResolver`  where either a known build name is passed in (such as `ckeditor5-build-classic`) or another component is passed in (for people who are building their own and including it in their projects) and you make the decision on which to instantiate. 

You might do it with a switch statement around your dynamic import in `ngOnInit`, or, more elegantly, as separate named components of their own (where there is a `CkEditorClassBuildComponent` installed via a separate npm package).

**Comment by keatkeat87** [comment]
Glad you guys are going to implement Angular!
i just play around ckeditor 5 and face some problem in Angular.
i try to Installing plugins by "[build your editor from source.](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/installing-plugins.html)"
is it possible to do that now? 
this is my simple code.
`import { Component } from '@angular/core';
// import * as ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic'; it work 
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  start() {
    ClassicEditor
      .create(document.querySelector('#editor'), {
        plugins: [Bold],
        toolbar: ['bold']
      })
      .then(editor => {
        console.log('Editor was initialized', editor);
      })
      .catch(error => {
        console.error(error.stack);
      });
  }
}`
and i get this error 
![image](https://user-images.githubusercontent.com/8691013/40038508-0d4836ce-5845-11e8-8cbe-2b87f6dfbd7b.png)
![image](https://user-images.githubusercontent.com/8691013/40038540-395058e6-5845-11e8-8602-04380e37e76e.png)

**Comment by oleq** [comment]
@keatkeat87 Are you using

```
            {
                // Or /ckeditor5-[^/]+\/theme\/icons\/[^/]+\.svg$/ if you want to limit this loader
                // to CKEditor 5 icons only.
                test: /\.svg$/,

                use: [ 'raw-loader' ]
            },
```

in your webpack config?

**Comment by pomek** [comment]
`/ckeditor5-[^/]+\/theme\/icons\/[^/]+\.svg$/` isn't correct on Windows. Not sure if it does matter but I recommend to use: `/ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/`

**Comment by Reinmar** [comment]
@keatkeat87, your question is out of the scope of this ticket (which is about creating the Angular component). Please open a new ticket (unless, of course, guys already solved your issue).

I'll remove these 4 comments to keep this thread clean.

**Comment by Reinmar** [comment]
EDIT: Actually, GH allows now to hide comments so I'll do that :)

**Comment by ayyash** [comment]
Looking at it, I assume (change)="something()" is the way to catch event, but that did not fire anything, what is the way to catch events?

**Comment by ma2ciek** [comment]
@ayyash, I guess, for that `CKEditorComponent` would need a property `@Output change = new EventEmitter<void>();` and then you should delegate the CKEditor's `change` event inside the `setUpEditorEvents` method via `this.change.emit()`.

**Comment by ayyash** [comment]
Okay I have a problem, this line `editor.on( 'change', () => { ... ` never really gets caught, nor did 'blur', am I missing anything?

**Comment by ma2ciek** [comment]
There's `editor.model.document.on( 'change', () => {} )` event, which you can use. See https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_document-Document.html.

**Comment by Reinmar** [comment]
And we've got a first pull request: https://github.com/ckeditor/ckeditor5-angular/pull/2 by @oleq. 

**Feedback needed** :)

**Comment by piernik** [comment]
Any updates on this??

**Comment by ma2ciek** [comment]
> Any updates on this??

I'm actively working on this, so I'll keep you updated.

**Comment by piernik** [comment]
@ma2ciek That's great news - **powodzenia!**

**Comment by ma2ciek** [comment]
@piernik, you can check out the current implementation on the https://github.com/ckeditor/ckeditor5-angular/pull/2 I've updated many things and this implementation should work well with `angular@6` :) We'll be releasing it soon.

**Comment by piernik** [comment]
Is it available on npm?

**Comment by oleq** [comment]
@piernik Not yet, but there's an [issue](https://github.com/ckeditor/ckeditor5-angular/issues/7) for that.

**Comment by ma2ciek** [comment]
**Update**: The `ckeditor5-angular` package has just been published - https://www.npmjs.com/package/@ckeditor/ckeditor5-angular 🎉

Run `npm install @ckeditor/ckeditor5-angular` to play with it.

If you have any trouble, please, report it in the https://github.com/ckeditor/ckeditor5-angular.

All feedback is welcome!

**Comment by Sovai** [comment]
Does it work with Angular 6?

**Comment by pomek** [comment]
Yes, it should work.

**Comment by ma2ciek** [comment]
Hi, @AlanObject.

Could you post the issue in the `https://github.com/ckeditor/ckeditor5-angular`?
Docs for the `ckeditor5-angular` package are available [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html).
