### ISSUE TITLE
Track changes + IME result in unwanted repeated characters

### ISSUE THREAD

**Issue by KevinWang15** [ckeditor/ckeditor5#10219]
## 📝 Provide detailed reproduction steps (if any)

When "track changes" is enabled, if I switch to Chinese IME, there will be unwanted repeated characters

![2021-07-27_01-16-27 (1)](https://user-images.githubusercontent.com/10173472/127031440-b1f1c2fa-fcd3-4255-ad2e-45119ac67bf6.gif)

### ✔️ Expected result

As is shown in the above clip, when I type `nihao`, I expect `你好` to be added. 

### ❌ Actual result

`n你好` was added, there was an unwanted character `n`.

### ❓ Possible solution

I believe this is due to a bug in the track-changes plugin, since it works fine without the track-changes plugin enabled.

## 📃 Other details

* Browser: Chrome 92.0.4515.107
* OS: MacOS 11.2.2

I have tried multiple Chinese IMEs, they all have the same problem. You can use the MacOS built-in Chinese IME to reproduce this issue.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by KevinWang15** [comment]
The problem seems to be worse in Safari / Firefox.. Track changes + Chinese IME is unusable..

**Comment by KevinWang15** [comment]
FYI, you can workaround this problem by 
1. Using Chrome / Safari, and
2. Configuring the Chinese IME to not display Pinyin in the textbox
   <img src="https://user-images.githubusercontent.com/10173472/127035882-e2405429-6a89-41a5-bfa4-fb0b9aeec31d.png" width="300"/>


But this is not a real solution as we cannot ask all the users to do this. 

And things would still break in Firefox.

I really like this feature, hoping to see a real fix soon..

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this bug, as it's a part of a bigger issue with IME in general. This one and similar bugs will most probably be resolved when we get back to work on [migration to `beforeInput`](https://github.com/ckeditor/ckeditor5/issues/7462). Unfortunately right now we cannot guarantee any ETA for this, as we have lots of other obligations and ongoing work.
  
Apart from that, Track Changes is a commercial plugin and this issue tracker is mainly for the purpose of open source part of the CKEditor project. If you are a licensed user and have any problems when using the editor, feel free to [contact us through the support channel](https://ckeditor.com/contact/). Our dedicated support team will investigate the problem and get back to you as soon as possible.  
  
For now, I'll close this issue as a duplicate.

**Comment by KevinWang15** [comment]
@FilipTokarski Thanks. Chinese IME works fine in other situations, it is only broken in track changes plugin. Yeah I too believe migration to `beforeInput` will fix many IME related bugs and make CKEditor a lot better for Chinese users. Really looking forward to that feature.

P.S. I am a licensed commercial user, I have contacted through the support channel but there was no reply yet. I guess there was not much the support channel can do, since it's a very difficult issue. I have to use the workarounds which I figured out (and posted in the issue comment) now.

**Comment by Mgsy** [comment]
> P.S. I am a licensed commercial user, I have contacted through the support channel but there was no reply yet. I guess there was not much the support channel can do, since it's a very difficult issue. I have to use the workarounds which I figured out (and posted in the issue comment) now.

Hi @KevinWang15! I'm really sorry to hear that you didn't receive a response from our support team. I've searched our support tickets and couldn't find you there, so I believe your message has not arrived in our inbox. Some time ago we had an issue with our contact form, so some messages might be missed. Please, take my apologies for this situation. 

Our support team responds to all inquiries and tries to do it as soon as possible. In case of further questions/issues (even difficult ones), don't hesitate to contact us! 

P.S. You can also use a direct contact - support@cksource.com.

**Comment by KevinWang15** [comment]
@Mgsy Thanks! I will contact the support team again

**Comment by KevinWang15** [comment]
@Mgsy I just sent another technical support inquiry through https://ckeditor.com/contact/, would you please help check if the message arrived in the inbox? Thanks.

**Comment by Mgsy** [comment]
> [**@Mgsy**](https://github.com/Mgsy) I just sent another technical support inquiry through [https://ckeditor.com/contact/](https://ckeditor.com/contact/), would you please help check if the message arrived in the inbox? Thanks.

I've checked our system and unfortunately didn't find any ticket associated with your email address from GitHub and GitHub name. Also, we have checked our contact form and it sends messages properly, so could you please make sure that you fill the form correctly? As mentioned before, you can also try to send a direct message to support@cksource.com.

**Comment by KevinWang15** [comment]
> > [**@Mgsy**](https://github.com/Mgsy) I just sent another technical support inquiry through https://ckeditor.com/contact/, would you please help check if the message arrived in the inbox? Thanks.
> 
> I've checked our system and unfortunately didn't find any ticket associated with your email address from GitHub and GitHub name. Also, we have checked our contact form and it sends messages properly, so could you please make sure that you fill the form correctly? As mentioned before, you can also try to send a direct message to [support@cksource.com](mailto:support@cksource.com).

@Mgsy Thanks, I will try to send an email to support@cksource.com directly.
I think I did fill out the form correctly in https://ckeditor.com/contact/, and it said something like "we will contact you as soon as possible", but the response I got from `POST https://ckeditor.com/cke4/contactus` was quite strange, it was 200 but said `{"error":false,"msg":"Test user ignored."}`. Not sure what went wrong..

![image](https://user-images.githubusercontent.com/10173472/128148347-ad977ddd-d7a1-45c9-9c7b-d1447a0608f4.png)

**Comment by KevinWang15** [comment]
Nevermind, I have sent an email to support@cksource.com with email address from my GitHub, now I received a reply saying:

```
Your request (#69621) has been received and will be reviewed by our team as soon as possible.
```

**Comment by huzedong2015** [comment]
现在是不是还没好？
