### ISSUE TITLE
Extra paragraph and break elements when copy/pasting from Google Docs

### ISSUE THREAD

**Issue by AleksBeliun** [ckeditor/ckeditor5#10217]
## 📝 Provide detailed reproduction steps

1. Go to https://docs.google.com/document/d/1abo1Ca_RHEmuXnAX6k_z0itHihQb3g9rJRM3x4vQ25w/edit
2. Copy some text
3. Go to https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html#demo
4. Paste the text

### ✔️ Expected result

![image](https://user-images.githubusercontent.com/58173995/127014866-0caf973b-d8bc-49ef-8a56-559aecfadfad.png)

![image](https://user-images.githubusercontent.com/58173995/127015003-5acc8acf-cbf7-4b8d-996f-aac8d8346989.png)

### ❌ Actual result

![image](https://user-images.githubusercontent.com/58173995/127013063-e04126ff-9915-4f39-a993-8fd9472db89e.png)

![image](https://user-images.githubusercontent.com/58173995/127013171-71ca26e6-88c7-48f0-a3ea-1bff1165771c.png)

## 📃 Other details

* Browser: Tested on Google Chrome Version 91.0.4472.164, Firefox 91.0b7 (64-bit), Safari Version 14.1.1 (16611.2.7.1.4)
* OS: macOS Big Sur Version 11.4
* First affected CKEditor version: 26.0.0
* Installed CKEditor plugins: 

```JSON
    "@ckeditor/ckeditor5-alignment": "^29.0.0",
    "@ckeditor/ckeditor5-autoformat": "^29.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^29.0.0",
    "@ckeditor/ckeditor5-block-quote": "^29.0.0",
    "@ckeditor/ckeditor5-build-classic": "^29.0.0",
    "@ckeditor/ckeditor5-core": "^29.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^25.2.6",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^25.2.6",
    "@ckeditor/ckeditor5-editor-classic": "^29.0.0",
    "@ckeditor/ckeditor5-essentials": "^29.0.0",
    "@ckeditor/ckeditor5-font": "^29.0.0",
    "@ckeditor/ckeditor5-heading": "^29.0.0",
    "@ckeditor/ckeditor5-highlight": "^29.0.0",
    "@ckeditor/ckeditor5-indent": "^29.0.0",
    "@ckeditor/ckeditor5-link": "^29.0.0",
    "@ckeditor/ckeditor5-list": "^29.0.0",
    "@ckeditor/ckeditor5-media-embed": "^29.0.0",
    "@ckeditor/ckeditor5-paragraph": "^29.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^29.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-remove-format": "^29.0.0",
    "@ckeditor/ckeditor5-special-characters": "^29.0.0",
    "@ckeditor/ckeditor5-table": "^29.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^29.0.0",
    "@ckeditor/ckeditor5-typing": "^29.0.0",
    "@ckeditor/ckeditor5-ui": "^29.0.0",
```

Built from source for React with Webpack as per official guideline.

Trying to update from 23.1.0 to the latest. Currently updated up to 25.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It's reproducible on [paste from GDocs docs](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html) since version `26.0.0`, so seems like a regression we missed.

**Comment by Reinmar** [comment]
Thanks for checking it @FilipTokarski. Could you try to bisect it? It may help prioritizing it.

**Comment by oleq** [comment]
Input:

![](https://user-images.githubusercontent.com/1099479/151143332-788bf47b-2456-4d4d-854b-58ce193911f1.png)

Result in v31.1.0:

![](https://user-images.githubusercontent.com/1099479/151143397-059a51c5-1da8-4875-a83d-3bd2aa72966a.png)

**Comment by Reinmar** [comment]
In the above case, it'd make sense for this paragraph to be empty (have no `<softBreak />` in the model).

**Comment by arkflpc** [comment]
Guilty commit: 74d1d15e819524914cedf9d6d9a799368d137437

**Comment by Reinmar** [comment]
Unfortunately, we had to revert this change. See https://github.com/ckeditor/ckeditor5/pull/12183.

**Comment by Reinmar** [comment]
Let's try to narrow the scope and target only this markup coming specifically from Google Docs.

The fix may land in the PFO package and use the normalization step where we clean up those specific weird HTML thingies that Google Docs or Word produce.

This way we'll avoid touching the more fragile logic of `<br>` conversion.
