### ISSUE TITLE
"Text part language" Why is Arabic not starting from the right?？ 

### ISSUE THREAD

**Issue by Sarmay** [ckeditor/ckeditor5#10222]
## 📝 I used the Text part language function but the text always starts from the left. I found that the dir at the top of the editor is always ltr. How to set this to auto

<img width="1434" alt="iShot2021-07-27 10 44 44" src="https://user-images.githubusercontent.com/45422903/127087401-b8fb7896-7918-4324-a0cd-21edeedcd9ef.png">

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Current implementation of _Text part language_ plugin unfortunately doesn't allow to change direction of text fragments/blocks. There is a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/2008) - feel free to add there anything you find important and add 👍  to increase its popularity.  
If you want to set the content's language/direction, please refer to the [docs on UI language](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#setting-the-language-of-the-content).
