### ISSUE TITLE
Tracking changes (suggestion mode)

### ISSUE THREAD

**Issue by dileep8014** [ckeditor/ckeditor5#1022]
does current version of ckeditor5 support tracking changes ? something similar to http://nytimes.github.io/ice/demo/

**Comment by dileep8014** [comment]
@Reinmar

**Comment by Reinmar** [comment]
No, not yet. But that's a feature we'd definitely like to see one day.

**Comment by Reinmar** [comment]
No, not yet. We plan to work on this feature this year.

**Comment by dileep8014** [comment]
@Reinmar - Thank you, i am trying to implement this feature and tried creating a plugin which will enable Track Changes if turned on , should i follow below approach and get the position of caret and track down the key input behavior or i can use Typing plugin in a way to handle this to get the current position and track down key input ? 

editor.editing.view.document.on( 'keydown', ( event, data ) => {
})

**Comment by pjasiun** [comment]
The feature is very complex. Typing is only the tip of the iceberg. There is a long list of actions to be handled: typing, deletion, paragraph split or merge, wrapping into a blockquote, image insertion or changing a style of an image, just to name few. Then, all of these features need to have UI to show the difference between the old and the new version of the document. There is also the problem how to represent the document with changes. What should the user get when he call `getData`? (the document without changes, or maybe there should be a flag to get the document with changes before they are applied?). Finally, what with third-party plugins, and how to make them work fine with suggestions? In fact, suggestion mode is one of the biggest challenge ahead we have at this point.

**Comment by dileep8014** [comment]
Any idea when this is going to be moved forward, any timeline ?

**Comment by pjasiun** [comment]
We plan to start working on it still this year, but, since it is a very big task, for sure it will not be ready this year. And for sure it will be ready next year, hopefully, closer to the beginning of it. I know that it is not much information but since the task, if very big and we are still at the research stage, I can promise nothing more.

**Comment by dileep8014** [comment]
this is great

**Comment by Mgsy** [comment]
Hi, @dileep8014! Last week we had a release and the track changes plugin was a part of it. Check it out on our [documentation page](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html). Hope you'll enjoy it!
