### ISSUE TITLE
Using the Chinese input method, input special symbols such as "., @" and there will be repeated characters

### ISSUE THREAD

**Issue by chenyongcai** [ckeditor/ckeditor5#10221]
## 📝 Provide detailed reproduction steps (if any)
1.Wrap before entering
2. Using the Chinese input method, enter ", @" Equal symbol

### ✔️ Expected result

Show only one symbol

### ❌ Actual result

Only two symbols are displayed

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by chenyongcai** [comment]
![11111](https://user-images.githubusercontent.com/43628444/127083104-f181f53e-3f03-4410-9a1e-74508f611169.gif)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this problem ([tracking it here](https://github.com/ckeditor/ckeditor5/issues/8839)) as it's a part of a bigger issue with IME in general. Those issues will most probably be resolved when we get back to work on [beforeInput](https://github.com/ckeditor/ckeditor5/issues/7462). Unfortunately right now we cannot guarantee any ETA for this, as we have lots of other obligations and ongoing work.  
I'll close this one as a duplicate.
