### ISSUE TITLE
The contrast between selected and unselected find and replace result is too low

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10242]
## 📝 Provide detailed reproduction steps (if any)

First result selected

![](https://user-images.githubusercontent.com/1099479/127308026-68422c90-2c7b-43b5-a954-e4a59ee372b9.png)

Second result selected

![](https://user-images.githubusercontent.com/1099479/127308044-2a546c7a-73e1-4cff-a75b-bb6bc0aeeee1.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
Some other products use different colors for selected and unselected search results:

<table><tbody><tr><td>Google Docs</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/8916871/129902234-c95ba52a-af90-488e-bf6f-781956cdbf9f.png"></figure></td></tr><tr><td>Google Chrome native search</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/8916871/129902263-e80fe100-efce-47c1-ba31-9e5c2a24f032.png"></figure></td></tr><tr><td>Firefox native search</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/8916871/129902312-971d9f64-bb66-4ea3-b127-f5c6660d60b3.png"></figure></td></tr><tr><td>TinyMCE</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/8916871/129902327-75e13a01-2f99-40e7-8c2d-df7dffcc2879.png"></figure></td></tr></tbody></table>

**Comment by Reinmar** [comment]
Standards.... standards everywhere :D

**Comment by Reinmar** [comment]
My 2 cents: Google Chrome's native colors are closest to what we have now, so this would be the smallest change and thus easiest to accept. I'd go this way. Fortunately, this is something we can revisit easily too, so there's little point to process it more thoroughly.

**Comment by Reinmar** [comment]
One thing that I checked: Chrome's colors are standardized across at least Linux (where you checked them, I suppose) and macOS. This is a good news :D
