### ISSUE TITLE
 Editor's behavior when canceling  indentation

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#10250]
## 📝 Provide detailed reproduction steps (if any)
Below is a video that shows the editor's behavior when canceling indentation:
https://user-images.githubusercontent.com/59637560/127430025-eea2e5cc-0a61-4f28-ab32-6bcb91da5a80.mp4

### ✔️ Expected result
I expected the behavior to be as seen in the next video (word):
https://user-images.githubusercontent.com/59637560/127430057-69e28cc9-21a4-48ba-99f5-704818a7878a.mp4

* Browser: chrome 92
* OS: windows 1-
* First affected CKEditor version: v 29.0.0.0

---
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. This issue known and is being tracked in https://github.com/ckeditor/ckeditor5/issues/7922. I'll close this as a duplicate.
