### ISSUE TITLE
GHS demo does not load on Android 9

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10259]
## 📝 Provide detailed reproduction steps (if any)

1. Open http://fake.ckeditor.com:8080/ckeditor5/latest/features/general-html-support.html

### ✔️ Expected result

The page is fully loaded, snippets are rendered.

### ❌ Actual result

The loading freezes.

![image](https://user-images.githubusercontent.com/2270764/127452317-0bd0d16c-d595-4fba-8e8f-6197b2a5a4aa.png)

## 📃 Other details

Browser: Chrome 91.0.4472.101
OS: Android 9.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
I have the same issue with the Code block guide, but after some time it finally loaded.

**Comment by maxbarnas** [comment]
Just checked this on a native device and had no issues whatsoever. Closing as it seems to be a problem with the device.
