### ISSUE TITLE
How to upload image? thanks

### ISSUE THREAD

**Issue by LIYonghui1992** [ckeditor/ckeditor5#1025]
Where can I download a demo for php? Now I really don't know how to configure uploading image plugin? Could you tell me how to upload image?  and after I uploaded mage, how to receive the response in the fron-end code?  I don't know where should I add my javascript code to get the response and solve it~ thanks!

**Comment by Reinmar** [comment]
Hi!

How to enable image upload is explained in https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5.

**Comment by Reinmar** [comment]
And your question kinda duplicates the discussion in https://github.com/ckeditor/ckeditor5/issues/555 (where you can find more information).
