### ISSUE TITLE
Inline image crashes after changing its type

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#10269]
There are two scenarios and they both look like regressions in `29.1.0` as they work in [`29.0.0` docs](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html#semantical-styles).

### Scenario 1

1. Go to 29.1.0 semantic styles demo (`/ckeditor5/latest/features/images/images-styles.html#semantical-styles`).
2. Change the type of the first google pin from `In line` to `Centered Image`.
3. Try to change the type back to `In line`.

### ✔️ Expected result

Image is converted back to the inline one.

### ❌ Actual result

There is an error in the console that crashes the editor:
![Screenshot 2021-07-29 at 13 44 47](https://user-images.githubusercontent.com/10883184/127486388-d107c2fb-1431-44b8-9a01-5224ade59447.png)

**Please note it doesn't happen for two other google pins in the demo:**
![semantic-styles-1](https://user-images.githubusercontent.com/10883184/127486673-7cc6bea8-6162-4ef8-b020-9b1a955f697c.gif)

### Scenario 2

1. Go to 29.1.0 semantic styles demo (`/ckeditor5/latest/features/images/images-styles.html#semantical-styles`).
2. Change the type of the **second** google pin from `In line` to `Centered Image`.
3. Press the Backspace before the image to move it back to the previous line.
4. Navigate with keyboard arrows to move caret after the image.

### ✔️ Expected result

Navigation works fine.

### ❌ Actual result

When trying to move caret after the image, there is an error in the console that crashes the editor:
![Screenshot 2021-07-29 at 13 51 25](https://user-images.githubusercontent.com/10883184/127487107-76e58966-7fc7-410c-883f-c30f4499d3a0.png)

![semantic-styles-2](https://user-images.githubusercontent.com/10883184/127487214-b2775c4d-8dae-4931-8bca-8be0e0d6f018.gif)

## 📃 Other details

* Browser: all
* OS: any
* First affected CKEditor version: 29.1.0
* Installed CKEditor plugins: `Image`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Dup of #10266.
