### ISSUE TITLE
Doubled "and" word in Table feature guide

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#10277]
## 📝 Provide a description of requested docs changes

There is doubled `and` word just at the beginning of [the guide](https://ckeditor.com/docs/ckeditor5/latest/features/table.html):

![Screenshot 2021-07-30 at 09 11 20](https://user-images.githubusercontent.com/10883184/127615391-e7abfb31-1b68-4e19-8bf1-1f1d0b018b9e.png)

**Comment by godai78** [comment]
Closed in 8b58f1c
