### ISSUE TITLE
HTML comment is lost after dragging the content

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10276]
## 📝 Provide detailed reproduction steps (if any)

1. Add two paragraphs with text
2. Add an html comment between those paragraphs
3. Select those paragraphs and drag somewhere else

### ✔️ Expected result

Comment stays between the paragraphs

### ❌ Actual result

There's no comment in the editable (source mode) and in `$root` it's `undefined`.

### Screencast

https://user-images.githubusercontent.com/34380544/127613553-4f692218-77d1-42e8-8d94-9df2865d3b35.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
This case is not supported yet - clipboard integration is tracked here: https://github.com/ckeditor/ckeditor5/issues/10127.

**Comment by ma2ciek** [comment]
Connected / duplicate: #10274.
