### ISSUE TITLE
[GHS] Figure tag gets duplicated when GHS config allows all

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10279]
## 📝 Provide detailed reproduction steps (if any)

1. Modify `all-features` manual test, so that it has GHS plugin and configuration that allows all:
```js
		htmlSupport: {
			allow: [
				{
					name: /.*/,
					attributes: true,
					classes: true,
					styles: true
				}
			]
		}
```
2. Open the test in the browser and switch to source editing mode

Alternatively you can load the editor, or `setData()` with the following content:
```html
<figure class="media">
           <oembed url="https://www.youtube.com/watch?v=ZVv7UMQPEWk"></oembed>
</figure>
```

### ✔️ Expected result

Content is source editing mode is the same as in the source html file.

### ❌ Actual result

First case: there is an empty `<figure>` tag at the end of the content.
Alternative case: figure tag with `class="media"` is wrapped in the same duplicated figure tag.

![ghs_2](https://user-images.githubusercontent.com/34380544/127646766-c817d3be-ee41-42c8-b0e4-d8981c682ba5.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
I can't reproduce it on the latest master and in [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/general-html-support.html). However, it's reproducible in the live docs. @FilipTokarski can you re-check it?

**Comment by Mgsy** [comment]
After F2F talks we consider it as still valid issue.

**Comment by FilipTokarski** [comment]
The case with `setData()` seems to be gone, but I can still reproduce the scenario from steps 1-2. After switching to source editing view, there is:
```html
<figure>
    &nbsp;
</figure>
```
At the very bottom of the source editing area.

**Comment by jswiderski** [comment]
I have tested this on https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html as well as locally (with specific GHS settings and allow all) but in all cases result was the same:

![works](https://user-images.githubusercontent.com/5314687/134310434-840bba7f-ad70-4179-9e07-fa19fef63168.gif)

**Comment by filipnestak** [comment]
I have the same problem. When i use GHS then `editor.getData()` return empty `<figure>`
