### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5#10283]
## 📝 Provide detailed reproduction steps (if any)
**webpack.config.js**
```

const path = require('path');
const { styles } = require('@ckeditor/ckeditor5-dev-utils');

module.exports = {
  devtool: 'source-map',
  entry: path.resolve(__dirname, 'src', 'app.js'),
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
  },
  module: {
    rules: [
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        use: ['raw-loader'],
      },
      {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
        use: [
          {
            loader: 'style-loader',
            options: {
              injectType: 'singletonStyleTag',
              attributes: {
                'data-cke': true,
              },
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: styles.getPostCssConfig({
                themeImporter: {
                  themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
                },
                minify: true,
              }),
            },
          },
        ],
      },
    ],
  },
};

```

**package.json**
```
{
  "name": "cke-craco",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "webpack --mode development",
    "start": "webpack serve --open",
    "build": "webpack --mode production",
    "deploy": "gh-pages -d dist",
    "publish-demo": "npm run build && npm run deploy"
  },
  "dependencies": {
    "@babel/core": "^7.12.13",
    "@babel/preset-env": "^7.12.13",
    "@babel/preset-react": "^7.12.13",
    "@ckeditor/ckeditor5-alignment": "^29.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^29.0.0",
    "@ckeditor/ckeditor5-block-quote": "^29.0.0",
    "@ckeditor/ckeditor5-code-block": "^29.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.5",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^25.3.0",
    "@ckeditor/ckeditor5-editor-classic": "^29.0.0",
    "@ckeditor/ckeditor5-essentials": "^29.0.0",
    "@ckeditor/ckeditor5-font": "^29.0.0",
    "@ckeditor/ckeditor5-heading": "^29.0.0",
    "@ckeditor/ckeditor5-highlight": "^29.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^29.0.0",
    "@ckeditor/ckeditor5-link": "^29.0.0",
    "@ckeditor/ckeditor5-paragraph": "^29.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-theme-lark": "^29.0.0",
    "@ckeditor/ckeditor5-utils": "^29.0.0",
    "babel-loader": "^8.2.2",
    "raw-loader": "^3.1.0",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "react-scripts": "3.2.0",
    "style-loader": "1",
    "webpack": "^5.47.1",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "css-loader": "^6.2.0",
    "file-loader": "^6.2.0",
    "postcss-loader": "^6.1.1"
  }
}

```

**babel.config.json**
```
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ]
}
```
### ✔️ Expected result
The project has to load without errors

### ❌ Actual result
**Getting more errors like below**
![image](https://user-images.githubusercontent.com/67726510/127732136-a7159636-2a56-489f-9132-b001b4f004c7.png)

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details
```
"webpack": "^5.47.1",
    "webpack-cli": "^4.7.2",
```
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, could you add more details on how you use the editor and what are the steps to reproduce this issue? Thanks!

**Comment by pomek** [comment]
The `postcss-loader` starting from version 4.0.0 (https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0) requires an additional loader that will inject the produced CSS to the bundle file.

> loader output only CSS, so you need to use css-loader/file-loader/raw-loader to inject code inside bundle


So, to resolve the issue, add the `css-loader` above `postcss-loader`, in the configuration.

```diff
  // ...
  module: {
    rules: [
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        use: ['raw-loader'],
      },
      {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
        use: [
          {
            loader: 'style-loader',
            options: {
              injectType: 'singletonStyleTag',
              attributes: {
                'data-cke': true,
              },
            },
          },
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: styles.getPostCssConfig({
                themeImporter: {
                  themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
                },
                minify: true,
              }),
            },
          },
        ],
      },
    ],
  }
  // ...
```

**Comment by Rajesh-Thiyagarajan** [comment]
> The `postcss-loader` starting from version 4.0.0 (https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0) requires an additional loader that will inject the produced CSS to the bundle file.
> 
> > loader output only CSS, so you need to use css-loader/file-loader/raw-loader to inject code inside bundle
> 
> So, to resolve the issue, add the `css-loader` above `postcss-loader`, in the configuration.
> 
> ```diff
>   // ...
>   module: {
>     rules: [
>       {
>         test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
>         use: ['raw-loader'],
>       },
>       {
>         test: /\.(js|mjs|jsx|ts|tsx)$/,
>         exclude: /node_modules/,
>         use: ['babel-loader'],
>       },
>       {
>         test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
>         use: [
>           {
>             loader: 'style-loader',
>             options: {
>               injectType: 'singletonStyleTag',
>               attributes: {
>                 'data-cke': true,
>               },
>             },
>           },
> +         'css-loader',
>           {
>             loader: 'postcss-loader',
>             options: {
>               postcssOptions: styles.getPostCssConfig({
>                 themeImporter: {
>                   themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
>                 },
>                 minify: true,
>               }),
>             },
>           },
>         ],
>       },
>     ],
>   }
>   // ...
> ```

Thanks @pomek
