### ISSUE TITLE
Paste performance for large images

### ISSUE THREAD

**Issue by FlowIT-JIT** [ckeditor/ckeditor5#10287]
## 📝 Provide detailed reproduction steps (if any)

You can increase paste performance in Chrome with a very simple optimization.
Due to missing caching in DataTransfer's implementation in Chrome ([see bug report here](https://bugs.chromium.org/p/chromium/issues/detail?id=1034292)), accessing the _files_ propery is expensive.
On my fairly fast MacBook Pro 2017 (2,8 GHz Intel Core i7, 16 Gigs of memory) it takes abount 1 second to read the _files_ collection of the DataTransfer object if I paste an image with a size of approx. 17 MB. So the paste operation takes about 2 seconds in CKEditor 5.

![image](https://user-images.githubusercontent.com/10479064/127835762-05fd5c97-92a7-40e0-af96-4439653b61ca.png)

If you avoid accessing the _files_ collection more than once, you can halve the time.

![image](https://user-images.githubusercontent.com/10479064/127836491-38eddd8c-9f10-41de-97e2-8de4a78fc43a.png)

The test was performed on the official online demo:
https://ckeditor.com/ckeditor-5/demo/

A similar bug report has been filed for CKEditor 4:
https://github.com/ckeditor/ckeditor4/issues/4807
-- Although the problem is much more noticable in v4 since the _files_ collection is being accessed multiple times.

In CKEditor 5 this is a minor problem since the collection is only accessed twice. But it's also easy to fix to give us a noticable performance improvement for large images.

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome Version 92.0.4515.107 (Official Build) (x86_64)
* OS: macOS 10.13.6 (17G14033)
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thanks for the tip :heart:
