### ISSUE TITLE
Track changes + 'input' event listener breaks Chinese IME

### ISSUE THREAD

**Issue by KevinWang15** [ckeditor/ckeditor5#10284]
## 📝 Provide detailed reproduction steps (if any)

When "track changes" is enabled, and there is an "input" eventListener on any ancestor of the CKEditor DOM node, Chinese IME is broken completely, to the point that it is impossible to input Chinese any more.

![2021-08-01_12-59-40 (1)](https://user-images.githubusercontent.com/10173472/127759869-1a233d01-aa37-4aa2-aaac-a72f5ad75132.gif)

This is an important bug, because ReactDOM will add "input" eventListener to the react root DOM node. So it is impossible to use track changes plugin in React projects.

Related: https://github.com/ckeditor/ckeditor5/issues/10219

I think track changes plugin is really not compatible with IME at the current stage.. Hoping to see a fix soon.

### ✔️ Expected result

I expect to be able to use Chinese IME with track changes plugin.

### ❌ Actual result

It's impossible to use Chinese IME with track changes plugin.

## 📃 Other details

* Browser: Chrome 92.0.4515.107
* OS: MacOS 11.2.2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by KevinWang15** [comment]
A workaround to make it usable in react (with performance penalties and limitations):

```javascript
class CKEditor extends React.Component {
  ckeditor = null;
  ckeditorDom = null;
  componentDom = null;

  componentDidMount() {
    this.ckeditorDom = document.createElement("div");
    document.body.append(this.ckeditorDom);
    window.ClassicEditor.create(this.ckeditorDom, CKEditorConfig).then(
      (editor) => {
        this.ckeditor = editor;
      }
    );
    requestAnimationFrame(this.alignCKEditorDomToComponentDom);
  }

  componentWillUnmount() {
    this.ckeditor.destroy().then(() => {
      document.body.removeChild(this.ckeditorDom);
      this.componentDom = null;
    });
  }

  render() {
    return <div {...this.props} ref={(r) => (this.componentDom = r)} />;
  }

  lastBoundingClientRect = null;
  lastCkEditorHeight = null;

  alignCKEditorDomToComponentDom = () => {
    if (!this.componentDom) {
      return;
    }

    let currentCkEditorHeight =
      this.ckeditor.ui.view.element.getBoundingClientRect().height;
    let currentBoundingClientRect = this.componentDom.getBoundingClientRect();

    if (
      this.boundingClientRectChanged(
        currentBoundingClientRect,
        this.lastBoundingClientRect
      )
    ) {
      this.lastBoundingClientRect = currentBoundingClientRect;
      Object.assign(this.ckeditor.ui.view.element.style, {
        position: "fixed",
        top: currentBoundingClientRect.y + "px",
        left: currentBoundingClientRect.x + "px",
        width: currentBoundingClientRect.width + "px",
      })
    }

    if (this.lastCkEditorHeight !== currentCkEditorHeight) {
      this.lastCkEditorHeight = currentCkEditorHeight;
      this.componentDom.style.height = currentCkEditorHeight + "px";
    }

    requestAnimationFrame(this.alignCKEditorDomToComponentDom);
  };

  boundingClientRectChanged(rect1, rect2) {
    if (!rect1 && !rect2) {
      return false;
    } else if (!rect1 || !rect2) {
      return true;
    }
    return (
      rect1.height !== rect2.height ||
      rect1.width !== rect2.width ||
      rect1.x !== rect2.x ||
      rect1.y !== rect2.y
    );
  }
}
```

**Comment by FilipTokarski** [comment]
Hi, please see my [comment in your other ticket](https://github.com/ckeditor/ckeditor5/issues/10219#issuecomment-890830510).
