### ISSUE TITLE
Export to Word should mention about supported MS Word versions

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#10293]
## 📝 Provide a description of requested docs changes

Export to Word feature is tested on the latest MS Word versions. Documents generated by HTML - MS Word converter should open correctly with older MS Word instances or any other app supporting `.docx` format (like Libre Office) but it's something we can't ensure. For example, it seems like images in the footer are not supported on MS Word 2010:
![image](https://user-images.githubusercontent.com/10279586/128002939-3ff99b7f-0944-44f4-9d0f-d9042a63d0f1.png)
so there may be some smaller or bigger rendering issues.

It would be good to mention that information in the documentation for [Export to Word](https://ckeditor.com/docs/ckeditor5/latest/features/export-word.html) feature.

**Comment by AnnaTomanek** [comment]
This looks like a pretty minor correction - @godai78 can you update the export to Word guide with this information?

**Comment by godai78** [comment]
Seems like it works (no issue reported) in Word 2019 and Word 365. I'll just add this information in the guide lead.

**Comment by godai78** [comment]
Merged: cksource/ckeditor5-internal#1321
