### ISSUE TITLE
Add docs to the new auto headings feature

### ISSUE THREAD

**Issue by dawidurbanski** [ckeditor/ckeditor5#10292]
## 📝 Provide a description of requested docs changes

Recently we added a new feature to set table headings automatically when inserting tables (#10039). It would be great to mention it in the docs, ideally [somewhere in this place](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/table.html#basic-table-features-2).

**Comment by dawidurbanski** [comment]
@godai78 let's start with this one and discuss if necessary #10295

**Comment by godai78** [comment]
I rewrote the demo itself to look more lifelike. We need to wait until after code release to merge it into `stable`, so I'll do it today later.

**Comment by godai78** [comment]
Closed in #10295
