### ISSUE TITLE
The `gulp docs` task should print errors and warnings

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#103]
Right now it doesn't produce any output. So whatever nonsense I write in the API docs it is silent. I hope that it isn't JSDoc's normal behaviour, but the gulp plugin's issue ;|.

**Comment by Reinmar** [comment]
It seems that JSDoc does not produce any warnings ;/ You can link to anything and use undefined types.

I haven't found any thread in JSDoc issues about validation, so perhaps it makes sense to start some. But I found https://github.com/jscs-dev/jscs-jsdoc which solves some of the issues, so perhaps the idea that JSDoc authors had is that JSCS-like plugin s should handle the validation.

**Comment by Reinmar** [comment]
We'll be switching to ESLint some time in the future (since JSCS and ESLint merged), so using the JSCS plugin doesn't make sense. Also, AFAICS, it only checks some stylistic things, while this we do pretty well manually. What we can't do manually, is verifying that links work – both, as param types references and in MD.

It seems that the only way to go will be writing a [JSDoc plugin](http://usejsdoc.org/about-plugins.html).

A thing that worries me is whether it is possible to validate links which are created using `{@link}`. AFAIR, if JSDoc doesn't find a token to which such a link directs, it simply doesn't make it a link.

**Comment by Reinmar** [comment]
The plugin should be implemented initially in https://github.com/cksource/docs-builder. We can later move it outside.

**Comment by Reinmar** [comment]
PS. One more thing that I'd like to check in the future, so it's worth to keep it in mind now, is whether it'd be possible to learn JSDoc that class members described after class definition belongs to that class.

E.g.

```js
/** 
 * @class Foo
 */
class Foo {
    constructor() {
        /**
         * @member {Number} namespace.Foo#foo
         */
       this.foo = 1;
    }
}
```

It's super irritating that you have to write `namespace.Foo#` before the property name and every time you link to other properties/methods of the same class, in the documentation of that specific property.

If we could make there magic which automatically assigns every item to its parent class and works with links, I'd be more than happy.

**Comment by Reinmar** [comment]
And another PS.

Before we go any further with JSDoc, I'd check those two tools:

* https://github.com/documentationjs/documentation
* https://github.com/esdoc/esdoc

Please create a simple project where we could these those for the things I mentioned in this issue – validation and automatic assigning properties to classes.

**Comment by Reinmar** [comment]
Status of things (the code is in https://github.com/ckeditor/ckeditor5-design/tree/api-docs-tests-jsdoc):

1. Reporter for the references validator. By default it can print out the results on the console (to the std output), but we need to be able to plug there a custom reporter (which should be able to format the output – add colors). [H]
1. The validator reporter should also be given the LOC in which the problem appeared and full path to the file. It must be possible to quickly find where is the problem in the code. [H]
1. TODO:
  * Short `@member` and `@method` and `@event` (of interfaces and classes). Assigns properties to the closest class (the one defined right above that member) or by the specified class/interface name (e.g. `@member ~Editor#name`). [H]
  * Validate that a `@member` or `@method` or `@event` is not assigned to any class or interface. [M]
  * Validate that a variable (see f.js) or a function (see e.js) was not exported correctly. [L]
  * Validate duplicated properties and stuff (e.g. it was possible in e.js to export to s2 functions). [L]
  * Readme and documentation for the plugins.
1. Check the results:
  * whether all "items" can be listed under their namespaces (on their namespace page),
  * validation – whether all important things are caught (create a second `ckeditor5/` directory with invalid stuff inside – `@param`s, `@implements`, `@extends`, `{@link}`, `@member`, etc.).

**Comment by ma2ciek** [comment]
Update of the status:

1. It's hard to make a custom reporter due to missing NodeJS API in [jsdoc3](https://github.com/jsdoc3/jsdoc) ([issue1](https://github.com/jsdoc3/jsdoc/pull/548), [issue2](https://github.com/jsdoc3/jsdoc/issues/691)) and [gulp-jsdoc3](https://github.com/mlucool/gulp-jsdoc3) which produces a wrapper around the jsdoc binary. So this point has to wait a little bit longer.
2. The validator is already done [here](https://github.com/ckeditor/ckeditor5-design/commit/b90573606f0aac4d00cdfeea72d29911ccd771c7) and formatted [here](https://github.com/ckeditor/ckeditor5-design/commit/a8eaa8778d904184ab5ca3bace509ea1db3aa742), so for now it only prints errors to stderr
3. I enabled short `@link` names in modules, classes and interfaces with tests for various scenarios. Fixed also issue with interfaces (all members, methods and events inside interfaces got fixed references). Rest is still missing.

**Comment by Reinmar** [comment]
https://github.com/jsdoc3/jsdoc/issues/691#issuecomment-255315442 turned out to be an interesting discussion. I recommend following it, @ma2ciek.

**Comment by ma2ciek** [comment]
Short summary of last commits:

1. Short names are fully done for `@member` `@method` `@fires` `@event` `@link` inside classes and interfaces. E.g. `@member ~Editor#name` and `@member #name` are correct and will be concatenated with outer class / interface name and path, so the result is equal to `@member module:someDir/someNamespace~Editor#name`
1. For now the validation is available for: `@member`, `@fires`, `@link`, `@param`, `@implements`. References have to match with an existing element. (`@fires` with events, `@implements` with interfaces and rest with any kind of element)

Now I'm working on the readme and directory with invalid stuff inside.

**Comment by ma2ciek** [comment]
Ok, so few more things added:

* More accurate type checking, introduced some 'basic types', validator correctly checks simple generic types (`Array.<Object>`) and union types (`String|Number`). Throws an error if the type is unknown.
* Class constructor is visible now as a method `#constructor`. This is some workaround that enables the following task. 
* Properties and methods defined in the constructor are now correctly binded to the class, not to the module or the constructor function.
* Modules cannot export documented inner `member`, this will throw an error to the console. The only available exports in module are: `function`, `namespace`, `class`, `constant`.
* `@returns` types are checking if they exist.
* Shorter type names in mixins are now supported, e.g. `@method #on`. 
* Methods in the classes don't need now `@method` tag.

**Comment by Reinmar** [comment]
I guess this is done already. Great job, @ma2ciek!

**Comment by ma2ciek** [comment]
I've added few more fixes and improvements since the last summary:
* Added validation of inherited methods and props.
* Fixed validation of multi-word and multi-line links.
* Splitted types into basic types and generic types with more accurate validation. Now `String.<String>` will throw an error and `Map.<String>` will not.
* Fixed short references in `@event` and `@fires` tags.
* Fixed creating external events with full path to the event.
* Added string literal types, e.g. `'left'|'right'` and `Array.<'left'>` types are correct now.
* Added `*` type as a wildcard.
