### ISSUE TITLE
Implement list styles

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1031]
The user should be able to choose the style of a list.

E.g. a bulleted list may use circles, squares, dots, etc. as its bullets. A numbered list can use roman, lower-roman, decimal, etc.

Also, there's a [`list-style-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position) and custom numbering using CSS counters.

## Markup

This feature is about styles, but we cannot tell what styles precisely (as I mentioned above it can be the list style type, but also more styling can be used). Therefore, it seems to be a good idea if this feature will use classes (on `<ol/ul>` elements) because it gives the most flexibility.

## Styling nested lists

Document editors like GDocs allow styling more than one list at a time:

![image](https://user-images.githubusercontent.com/156149/40367036-c3acf66e-5dd8-11e8-941e-de368187567f.png)

This ensures better consistency between documents and, in general, may bring a better UX to the user. We could consider how this can be implemented by us (if we'll use classes then it should be pretty straightforward).

## UI

To be discussed.

Related: https://github.com/ckeditor/ckeditor5/issues/1028#issue-325032492

**Comment by SKGGitHub** [comment]
@Reinmar 

We also in an eed of providing such roman numbers and lower alpha lists in CKEditor5. Is it available to use now?

**Comment by ymsstudios** [comment]
This is the only reason I don't use CKEditor in my projects

**Comment by skerbis** [comment]
Ping - please

**Comment by joachimdoerr** [comment]
That is a important feature like dl dd dt text lists.

**Comment by tbredin** [comment]
My team needs this too 👍

**Comment by dick-airlink** [comment]
This is a very important feature - indents have FULL outline#ing path - because we often in chats amongst colleagues say things like - "see 1.2.2.3 - we need to change the color....".

With multipage documents, it really impossible to know the full #ing.  

ALSO - and I don't know this would be a new issue/thread or relate here, but it would be EXTREMELY HELPFUL to be able to "collapse" an indent.  Is that currently possible at all?  Is this an issue that has been raised before?

Thanks!

**Comment by skerbis** [comment]
From our point of view it is the only missing feature to call CKE5 a professional editor.

**Comment by mlewand** [comment]
@joachimdoerr In reply to https://github.com/ckeditor/ckeditor5/issues/5653#issuecomment-549047594: list styles is indeed a nice feature that we'd really like to have in v5. However, as a team, we don't have unlimited time so the features we can ship each release are unfortunately limited. For instance, this release we're preparing much anticipated code blocks feature, alongside with table styling which is critical foundation for our further table improvements.

In case this feature is critical for your business you can also [contact us](https://ckeditor.com/contact/) to check if there is any way to speed up the development of the feature you or your customer needs.

That being said, list styles feature is on our radar for some time, and we definitely want to have it implemented soon. But we don't have any precise ETA now.

**Comment by joachimdoerr** [comment]
@mlewand thanks for your answer. I work only in open source context with your product because in the professional usage it is not usable without that list styling option. It is really unfortunate that your focus isn't exactly on the important basic functions. With all basics your product will be get the first place on the list of rich text editors.

**Comment by mlewand** [comment]
@joachimdoerr happy to hear that you do open source too. In this case there's also a straight way to speed things up: we're open for pull requests, so feel free to contribute to the feature of your choice.

**Comment by Reinmar** [comment]
> It is really unfortunate that your focus isn't exactly on the important basic functions.

We follow the feedback that we get from the community and our business partners. For us, "important" means things that most people/companies request. This specific feature is high on this list but there were ones which are higher and we focus on those at the moment. As soon as we'll resolve those blockers, we will be able to focus on list styles. 

> With all basics your product will be get the first place on the list of rich text editors.

That's our goal but it does not happen overnight ;) There are as many use cases as there are projects out there so we have to gather feedback, listen to it but still make decisions that will best work in a long term

> so feel free to contribute to the feature of your choice.

I'd add that to increase the likelihood of such a contribution landing in the official code base, it helps if it's designed and implemented in sync with the core team. If you'd be considering investing your time in it, please ping us so we can share some thoughts. But it's, of course, completely fine if it just stays a 3rd party addition (and it's easier this way).

**Comment by pshurygin** [comment]
I wonder if this thread also covers a similar issue with lists (mostly numbered lists) - atm there is no way to change numbering color/font-style/font-weight etc. So when the user changes styles of text within list item (like color), the color of the numbers does not change(and there is no other way to change it). 

This problem has been very frustrating for our users and I would like to know if it is on the roadmap and part of this issue.

I was going to implement some plugin to fix this based on Font and/or List plugins, but it seems like a pretty challenging task to do. I would appreciate some advice and directions on how this can be implemented and if it is possible at all at the current state of the ckeditor5.

**Comment by Reinmar** [comment]
That's a separate issue. It's how browsers render list bullets/numbers. None of the HTML-based editors I know handle this as it's pretty ugly. But with CKEditor 5's engine features we could actually solve this. Please report a separate ticket for this so we can discuss it there.

**Comment by pshurygin** [comment]
@Reinmar created a new ticket here: https://github.com/ckeditor/ckeditor5/issues/5752

**Comment by MiKr13** [comment]
Hi, can we know about the timeline for this feature development? I along with my team even had a meeting with your team about some features and Ckeditor5 is going to be our editor prime time even for professional usage. Please give us a timeline of this feature, it's long overdue. Thank you.

**Comment by Reinmar** [comment]
@MiKr13 please contact the CKSource team using the means that you used previously (most likely, through the contact form or support@cksource.com). This will allow the team to respond with necessary details.

**Comment by joachimdoerr** [comment]
@Reinmar what is the status of this feature?

**Comment by rootlinux2** [comment]
Any advance here???

**Comment by skerbis** [comment]
I like CKE5 but because of the missing "standard" formatting features, I can use it not the way I and our editors would like. 
Because of the missing list features our editors can not use it for complex documents.

**Comment by dick-airlink** [comment]
Because I have requested this feature numerous times for several years, I would guess this will never happen.A real pity. I'm assuming that it is perhaps either impossible to do or that just too few of us really need it and/or have voiced our support of it.I'm 67, so I must pass the torch to a younger generation of seekers. Hopefully I will be able to peer in from the great beyond from time to time to see if they have arrived into the promised land.Godspeed to you all.On Jul 8, 2020 2:08 AM, Thomas Skerbis <notifications@github.com> wrote:
I like CKE5 but because of the missing "standard" formatting features, I can use it not the way I and our editors would like.
Because of the missing list features our editors can not use it for complex documents.

**Comment by MiKr13** [comment]
I switched to TinyMCE because of this. I have given Ckeditor5 as other option in my app, whichever client wants to use. It's great that data is compatible between these two completely.

**Comment by Reinmar** [comment]
Hi all! I know it's disappointing if a single feature missing in the product makes that product unusable in your case. I also understand how bizarre it may seem that CKE5 still does not implement this feature. 

Yet, here we are, still planning it, among many other things.

But to move things forward, I'd like to ask you for feedback on what do you actually expect from "List styles". It's a wide topic and for sure we won't be able to tackle it all at once. I'd like to ensure that we get the most in the shortest time.

I can see the following sub-features:

*   **(A)** ability to change the type of bullet (dot, circle, square, etc.) or number (decimal, roman, whatever) or a single list item or all selected items,
*   **(B)** ability to change the start number of a numbered list (option **B2**: the "reverse" option),
*   **(C)** ability to have lists automatically numbered like this `1., 1.1., 1.2., 1.2.1., ...`,
*   **(D)** ability to chose one of predefined setups of entire list with nested lists (like what you have in e.g. Google Docs, when you can at once define that the first level will use dots, the second level will use circles, etc.),
*   anything else?

**Please write** which of these (A, B, B2, C, D) are must-have, nice-to-have or I-dont-care to you.

**Also,** I'd be interested whether you'd like this feature to use classes or inline styles.

Your feedback will help us properly prioritise these sub-features. Thank you in advance!

**Comment by skerbis** [comment]
(A) is the biggest feature missing. Change form 1. 2. to a) b) oder I II IV .. 
I think (B), (C) and (D) will be very difficult to implement in html context. But, it would be very very cool 😃

> Also, I'd be interested whether you'd like this feature to use classes or inline styles.
Classes would be nice and let us keep the markup "cleaner"

**Comment by joachimdoerr** [comment]
From my opinion (A) and (C) get the most benefit for users.

**Comment by wwalc** [comment]
I'd like to add that we receive quite a lot of requests where list styles are mentioned in the context of Paste from Word support. It looks like it is expected that CKEditor supports not only editing list styles in CKEditor itself, but that CKEditor has also a decent support for pasting content from MS Word that contains styled lists in MS Word.

When adding a reply please confirm if a very good support for pasting lists from MS Word is also important for you.

**Comment by rootlinux2** [comment]
In my case (A, B, C)
![image](https://user-images.githubusercontent.com/24574267/86941828-6669c000-c112-11ea-8f9e-41113a51dab2.png)

**Comment by pomek** [comment]
* Research: https://github.com/ckeditor/ckeditor5/issues/7736 
* Feature editing part: https://github.com/ckeditor/ckeditor5/issues/7801
* Feature UI part: https://github.com/ckeditor/ckeditor5/issues/7803
* Docs: https://github.com/ckeditor/ckeditor5/issues/7804

**Comment by CZKishan** [comment]
dfdfffff****
dgdf

- gfgfdg

- gfgfgfg

- gfgf

fgfgfgfg
dgfd

1. dgdfg
2. fgfhf
3. [https://youtu.be/aMoBxEUmcjA](url)
