### ISSUE TITLE
List element (ul) disappears in the slot reconversion guide

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10314]
## 📝 Provide detailed reproduction steps (if any)

1.  https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/element-reconversion.html
2.  make a list inside some of the card section
3.  click the "change type" button

![](https://user-images.githubusercontent.com/1232187/128344973-bccbb033-2bb2-4909-b638-18fddd89afc0.gif)

### ✔️ Expected result

The `<ul>` is still there.

### ❌ Actual result

The `<ul>` is no longer in the view, only `<li>` with its content remains.

### ❓ Possible solution

This is happening because of reusing the old view elements that were mapped to the model element (and `ul` elements are not mapped - only `li`s are).

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It will be fixed by #10568.
