### ISSUE TITLE
Add width and height attribute to img element in "Simple upload adapter"

### ISSUE THREAD

**Issue by doanhquang2005** [ckeditor/ckeditor5#10324]
In lighthouse Chrome:
Image elements do not have explicit width and height
Set an explicit width and height on image elements to reduce layout shifts and improve CLS. Learn moreCLS

**Is there any solution to solve the above problem with "Simple upload adapter"?**

**Comment by mmichaelis** [comment]
I assume, this is related to current restrictions, that width/height cannot be set for an image. For reference, see for example:

* #10838
* #5154
* #11393

**Comment by Witoso** [comment]
🎉 This feature was merged to the `master` and is available on the [nightly releases](https://github.com/ckeditor/ckeditor5/issues/14724) and [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) to test.

After the release, `width` and `heigh` will be set automatically after the upload.

[In a comment in another issue](https://github.com/ckeditor/ckeditor5/issues/14146#issuecomment-1632607316), you can find more details about the changes.
