### ISSUE TITLE
Wrong selection position

### ISSUE THREAD

**Issue by masterj3y** [ckeditor/ckeditor5#10325]
## 📝 Provide detailed reproduction steps (if any)

When I insert some text to the editor programmatically, it places at the beginning of editor
I use this code:
`editor.model.change((writer) => {
    const insertPosition = editor.model.document.selection.getFirstPosition();
    writer.insertText('some string', insertPosition);
  });`

## 📃 Other details

* Browser: Chrome
* OS: Windows 10, Android
* First affected CKEditor version: 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, the code you used inserts text at the current selection position. The only way to reproduce the scenario you described, is to initialise the editor and use the code before focusing it for the first time (then by default selection is at the very beginning of the editor's content). Then whenever you click inside the editor, the selection changes and the code inserts the content at the current selection position, as expected. So I'm not sure why would you consider it as a bug.
Here you can read more about the [model](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#model) and [DocumentSelection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html).
