### ISSUE TITLE
Remove language option is the last in the dropdown

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10338]
## 📝 Provide a description of the improvement

Currently the option to remove language markup is the last option in language dropdown.

![](https://user-images.githubusercontent.com/5353898/129003867-75c4285a-bb57-4bfd-ba6d-8423f4404846.png)

Plugin is configurable to contain as many languages as desired. So option to remove language will be inconvenient if there's say 20 or more languages.

A common pattern is to place such _"reset option"_ as the first one in cases like that. And we actually do this in other features like code blocks, heading etc.

![](https://user-images.githubusercontent.com/5353898/129004463-8da51fcb-1681-40da-98f0-df20e18da7d3.png)

![](https://user-images.githubusercontent.com/5353898/129004542-73c58e2f-3010-4025-8a05-44792cbb8378.png)

Google Docs also follows this pattern (I didn't check other editors though):

![](https://user-images.githubusercontent.com/5353898/129004831-3e2411c9-2c7f-494f-8ca2-52b8bce4f884.png)

You can see current implementation in https://ckeditor.com/docs/ckeditor5/29.1.0/features/language.html

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
A bit similar situation can be found in the highlight feature, but it's not comparable and we shouldn't touch it.
