### ISSUE TITLE
Add script for publishing ckeditor5

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1033]
There are a couple of steps which I need to perform manually now:

1. Run `npm version major|minor` (choose the bump based on the changes in deps).
1. `npm publish` **IMPORTANT** See notes below.
1. Create a release on `ckeditor5`'s GitHub (copy there the changelog section).
1. Update the mention of the last released version in the README.
1. Update all `stable` branches: `git co stable && git merge master && git co master` and `mgit exec 'git co stable && git merge master && git co master'`.
1. Now, make sure that `mgit.json` has the right content in `master` and `stable`:
   1. `git co stable` and add `#stable` to all packages in `mgit.json`; commit this with `git commit -a -m "Internal: Use stable branches. [skip ci]"`. 
   1. `git co master && git merge stable` and remove `#stable` from `mgit.json`; commit this with `git commit -a -m "Internal: Use master branches. [skip ci]"`
   1. `git push origin stable master && mgit exec 'git push origin stable'`
   1. Add stable branches in all repos which don't have them yet: `mgit exec 'git co -b stable && git push origin stable && git co master'`

## Contents of this package?

This package is meant to be empty on npm. This means:

* No dependencies (neither dev nor prod ones).
* `package.json` should contain a description, keywords, license, links, etc.
* No files except `README.md` and `LICENSE.md`.

And that's it. This means that publishing it straight from this repo (which I mistakenly did in v10.0.1) publishes far too many things.

## What I need?

I need one script which will automate this process.

**Comment by Reinmar** [comment]
BTW, we can also improve one thing – instead of forcing us to do all that mess with adding `#stable` to `mgit.json` we could configure there which main repo's branches should be treated as "standard" ones. The setting will include `[ 'master', 'stable' ]` so:

* if package's branch is specified in `mgit.json`, that branch should be used,
* if package's branch is not specified and if `ckeditor5` is on one of the standard branches `mgit update` will check out the sub package to that branch,
* if `ckeditor5` is on a different branch than these two, the first of the specified ones will be used for the sub package.

**Comment by Reinmar** [comment]
The above will allow us to keep `mgit.json` clean and will simplify the gitology after the release.

**Comment by pomek** [comment]
> Run `npm version major|minor` (choose the bump based on the changes in deps).

Because the changelog is already generated, we can extract the version from the file. So, the called command could be `npm version [latest-version-from-changelog]`.

ATM I have no questions.
