### ISSUE TITLE
Is the latest version of the ckeditor-clipboard(29.1.0) published to npm?

### ISSUE THREAD

**Issue by atomiclab0000** [ckeditor/ckeditor5#10346]
## 📝 Provide detailed reproduction steps (if any)

1. npm install @ckeditor/ckeditor5-clipboard

### ✔️ Expected result

Latest version should remove all comments when copy/paste from google docs, I see code for it in github.
![currentCode](https://user-images.githubusercontent.com/88828874/129179509-bf62ab7b-5918-4eb5-85b4-54b05f2102fb.png)

### ❌ Actual result

I still get old code when install plugin via npm
![versionFromNpm](https://user-images.githubusercontent.com/88828874/129179547-edd4d64a-7669-4b93-82de-cbd7ec5c36a3.png)
![codeFromNpm](https://user-images.githubusercontent.com/88828874/129179550-95081a72-9e82-4d45-8fbd-fc32d5792926.png)

## 📃 Other details

* OS: Windows10
* First affected CKEditor version: 29.1.0
* Installed CKEditor plugins: @ckeditor/ckeditor5-clipboard

**Comment by pomek** [comment]
> Latest version should remove all comments when copy/paste from google docs, I see code for it in github.

This is what you see on master: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-clipboard/src/utils/normalizeclipboarddata.js

https://github.com/ckeditor/ckeditor5/blob/db4c718490ad4551c17e188be7cd02960486b7b3/packages/ckeditor5-clipboard/src/utils/normalizeclipboarddata.js#L17-L30

The `v29.1.0` does not contain this change: https://github.com/ckeditor/ckeditor5/blob/v29.1.0/packages/ckeditor5-clipboard/src/utils/normalizeclipboarddata.js

https://github.com/ckeditor/ckeditor5/blob/d159b11b8ac308b39f5dad9560f16bd9cb419a4d/packages/ckeditor5-clipboard/src/utils/normalizeclipboarddata.js#L16-L27

Everything is fine.

**Comment by mlewand** [comment]
And I can confirm it had been released as it is [listed on npm](https://www.npmjs.com/package/@ckeditor/ckeditor5-clipboard) 🙂
