### ISSUE TITLE
View table cell names are different to the initial data

### ISSUE THREAD

**Issue by shady-cansultant** [ckeditor/ckeditor5#10343]
## Steps
Load the following HTML into the editor
  ```
<table>
      <tbody>
         <tr>
             <th>1</th>
             <td>2</td>
         </tr>
         <tr>
             <td>3</td>
             <th>4</th>
         </tr>
      </tbody>
</table>
```
### ✔️ Expected result

The table nodes to remain unchanged.

###  ❌   Actual result: the editor will change the view table cell names of 3 & 4 to be `<th>` and `<td>` respectively:
```
<table>
      <tbody>
         <tr>
             <th>1</th>
             <td>2</td>
         </tr>
         <tr>
             <th>3</th> // this should be td
             <td>4</td> // this should be th
         </tr>
      </tbody>
</table>
```

**Comment by FilipTokarski** [comment]
Hi, this is not a bug, that's how tables in CKEditor 5 work. After setting the markup, editor will check if the content is correct (according to the [model's schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#schema)), which in this case doesn't make much sense to have header in 1st and 4th cell. So the table post-fixer will thus make sure to have a proper header and change the cell types. You can read more about this in the [schema docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html).
