### ISSUE TITLE
Docs: The source editing demo misses the LinkImage plugin

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10349]
## 📝 Provide a description of requested docs changes

Currently, there's no support for linking images in the demo [`https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html`](https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html). We should add the plugin to the editor configuration.

**Comment by godai78** [comment]
Closed in #10351
