### ISSUE TITLE
[Docs] Add a guide about exiting the editor, saving data, pending actions etc.

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1035]
We're introducing lots of cool stuff recently to deal with handling changes in the editor, like the auto save or the pending actions plugin. Without proper guides and examples I'm afraid they will not be discovered by developers. It's hard to find such things in API docs, even if they are well-explained there too.

**Comment by pjasiun** [comment]
It should cover two ways of saving data: autosave and using save button. Answer question: how to observe changes and pending actions in the context of saving. We should mention `change:data` event, pending actions and autosave plugins.

**Comment by Reinmar** [comment]
And one more thing to cover – integration with forms. It was reported somewhere, but I can't find it. Nevertheless, it makes sense to cover these things together.

**Comment by Reinmar** [comment]
Thanks @dkonopka and @oleq for this lovely demo!

![jul-18-2018 10-17-31](https://user-images.githubusercontent.com/156149/42868922-d291651c-8a73-11e8-9604-b503dcc343cd.gif)
