### ISSUE TITLE
Mathtype CORS issue

### ISSUE THREAD

**Issue by jongjunpark** [ckeditor/ckeditor5#10366]
## 📝 Provide detailed reproduction steps (if any)

1. using React
2. add CKEditor5 ClassicEditor
3. add MathType plugin

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

I was faced by CORS issue about www.wiris.net (Mathtype). I am using free version ckeditor5 editor. 
Is it possible to solve the problem if I switch to the paid version? How can I solve this problem ?
![image](https://user-images.githubusercontent.com/60080679/129651996-61c88617-c2f7-478e-bced-306ea919aeed.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. Please note, that MathType is not maintained by CKEditor 5 team, but our partners - Wiris, so please report any issues with the plugin to the [plugin's repository](https://github.com/wiris/html-integrations/issues). Thanks!

**Comment by Kasiyliy** [comment]
Same issue here :( @FilipTokarski how did you resolve this issue?
