### ISSUE TITLE
Introduce `triggerBy` for `elementToElement()` and `elementToStructure()`

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10360]
## Provide a description of the task

**Scope**

*   Introduce: `triggerBy` property for `elementToElement()`, `elementToStructure()`
    *   Necessary to handle `<th>` ↔ `<td>` changes triggered by `<table>` attr change
    *   Necessary to handle `<p>` ↔ `<span>` changes inside a `<td>`

**Comment by Reinmar** [comment]
We approached it in a different way. We listen to model changes and trigger reconversion via calling `editor.editing.reconvertItem()`. It's more flexible than the declarative API we initially had in mind
