### ISSUE TITLE
Accessibility Support

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1036]
As of v10.0.0 the editor is not the most accessible application in the world, especially when compared to its [predecessors from the 4.x line](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_a11y.html). Step–by–step, we should improve the UI of the editor to provide the best experience possible.

This umbrella ticket collects issues related to the accessibility.

**Comment by oleq** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Feature Request: High Contrast Highlighting #1029](https://github.com/ckeditor/ckeditor5/issues/1029) | N/A | N/A | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Re-add the "accessibility instructions" modal #1014](https://github.com/ckeditor/ckeditor5/issues/1014) | unknown | N/A | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Toolbar button labels not read by screen readers #1013](https://github.com/ckeditor/ckeditor5/issues/1013) | N/A | N/A | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by Reinmar** [comment]
I can see we're tracking all of those issues in https://github.com/ckeditor/ckeditor5/labels/feature%3Aaccessibility now, so I guess this ticket is not needed.
