### ISSUE TITLE
Unclear whether we can use imports from index.js files of core (DLL) packages?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10375]
See: 
_Originally posted by @Reinmar in https://github.com/ckeditor/ckeditor5/pull/10352#r691284235_

The below change does not trigger a linter warning, so it's unclear to me how the code should be written:

![image](https://user-images.githubusercontent.com/156149/129915422-0c6c219a-d3fa-4304-8770-986c7c4a327d.png)

**Comment by Reinmar** [comment]
![](https://user-images.githubusercontent.com/156149/129915293-01af0fc7-0e66-458d-8c9a-80151f34efda.png)

**Comment by pomek** [comment]
Core DLL packages can import between themselves using any import condition. 

- through the `ckreditor5` package,
- an import from package `index.js`,
- a direct import of requires thing.

**Comment by pomek** [comment]
A rule to update:

https://github.com/ckeditor/eslint-plugin-ckeditor5-rules/blob/268126ecbed8e18b954cd4ba70cb816fae1ed97b/lib/rules/ckeditor-imports.js#L65-L68

**Comment by Reinmar** [comment]
There's a history behind the inconsistency. The problem is that core DLL packages may want to import something from another core DLL package that is not exposed in `index.js` (because we didn't want to make it a public API yet). So, at least some imports would have to use the `@ckeditor/ckeditor5-.../src/` notation. Hence, all should.

Let's create a rule checking for that. And document the "why" briefly in the documentation introduced in #10051.

Finally, create a followup to check what kind of imports between core DLL packages block us from moving to `index.js`\-based imports.

**Comment by pomek** [comment]
PRs:
- https://github.com/ckeditor/eslint-plugin-ckeditor5-rules/pull/7
- https://github.com/ckeditor/ckeditor5/pull/10468

> Finally, create a followup to check...

https://github.com/ckeditor/ckeditor5/issues/10469
