### ISSUE TITLE
Custom build with General HTML Support feature

### ISSUE THREAD

**Issue by nguacon90** [ckeditor/ckeditor5#10379]
I've got problem with custom build ckeditor5 with plugin General HTML Support. I follow the document in link [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html](url). I've configured customer build as follow:
```
import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';
export default class DecoupledEditor extends DecoupledEditorBase {
}

// Plugins to include in the build.
DecoupledEditor.builtinPlugins = [
	GeneralHtmlSupport,
	Essentials,
	Alignment,
.... ]
```

After run `yarn run build` and open sample index.html. I've got error in console log and ckeditor not working:
```
ckeditorerror.js:64 Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
    at Object.<anonymous> (version.js:151)
    at Object.<anonymous> (ckeditor.js:5)
    at o (bootstrap:19)
    at Module.<anonymous> (ckeditor.js:5)
    at o (bootstrap:19)
    at bootstrap:83
    at ckeditor.js:5
    at universalModuleDefinition:9
    at universalModuleDefinition:1
i @ ckeditorerror.js:64
(anonymous) @ version.js:151
(anonymous) @ ckeditor.js:5
o @ bootstrap:19
(anonymous) @ ckeditor.js:5
o @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ ckeditor.js:5
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1
index.html?_ijt=elo8hmi9dvphnbcqkt3ti2pc0u:60 Uncaught ReferenceError: DecoupledEditor is not defined
    at index.html?_ijt=elo8hmi9dvphnbcqkt3ti2pc0u:60
```
Eeveryone can help me to resolve problem?
BR.

**Comment by Reinmar** [comment]
Have you seen the documentation of the error that is thrown [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules)?

It goes through what's usually wrong.

**Comment by nguacon90** [comment]
Thanks @Reinmar. However, I've read it but there's no solution to resolve the problem when i try add the plugin into build the `DecoupledEditor`. Document guide also not clear to add the above plugin into existed build. Have you any idea?

**Comment by nguacon90** [comment]
Thanks @Reinmar.
I've found my problem and find out the solution for this. 
BR.
