### ISSUE TITLE
Invalid cell property after pasting a table to the editor from Word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10383]
## 📝 Provide detailed reproduction steps (if any)

1.  Open the [sample Word document](https://ckeditor.com/docs/ckeditor5/latest/assets/CKEditor5.PFO.Sample.Recognition_of_Achievement.docx) from our documentation.
2.  Select the table and copy it.
3.  Paste the table to the editor, e.g. in the [Paste from Word demo](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo).
4.  Put the caret in the first cell.
5.  Open the table cell properties window.

### ✔️ Expected result

It displays correct values.

### ❌ Actual result

The border color field has `windowtext` value and is highlighted as invalid.

## 📃 Other details

It's not a regression.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
CKE4: https://github.com/ckeditor/ckeditor4/issues/2923

**Comment by Reinmar** [comment]
`windowtext` is listed in https://www.w3.org/TR/css-color-3/#:~:text=4.5.%20CSS%20system%20colors so we may add it to the list of valid colors (I suppose it's this: https://github.com/ckeditor/ckeditor5/blob/be2339d/packages/ckeditor5-engine/src/view/styles/utils.js#L24).

**Comment by arkflpc** [comment]
Shall we add all depreciated system colors from the spec?

**Comment by Reinmar** [comment]
Yes, I see no point in adding just one color. These are valid color values. They are deprecated (so we wouldn't use them), but we can accept them as values.

**Comment by Reinmar** [comment]
However, just to be sure: do you see a problem with adding all the colors?
