### ISSUE TITLE
Simplify builds' source repos

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1038]
Two pain points:

* `build-config.js` vs `src/ckeditor.js`. I feel that leaving only the latter will make these repos easier to understand. It's a simple JS file, no magic there. Right now, we need to explain that you normally use `build-config.js` unless something. This is tricky and we've seen people doing mistakes because of that.
* Change the `EditorClass.build`'s form to something clearer. First of all, the list of plugins there seems to be the same as `config.plugins` while it's not. Second, the `build` property is a bit unclear. Perhaps, we can merge this all into something like:

```js
BalloonEditor.buildConfig = {
	availablePlugins: [
		EssentialsPlugin,
		UploadadapterPlugin,
		AutoformatPlugin,
		BoldPlugin,
		ItalicPlugin,
		BlockquotePlugin,
		EasyimagePlugin,
		HeadingPlugin,
		ImagePlugin,
		ImagecaptionPlugin,
		ImagestylePlugin,
		ImagetoolbarPlugin,
		ImageuploadPlugin,
		LinkPlugin,
		ListPlugin,
		ParagraphPlugin
	],
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'bulletedList',
			'numberedList',
			'imageUpload',
			'blockQuote',
			'undo',
			'redo'
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	language: 'en'
};
```

For comparison: https://github.com/ckeditor/ckeditor5-build-classic/blob/7e54c8d9f365a983d00fcf0da2102d761f37f7b6/build-config.js

**Comment by pjasiun** [comment]
Big :+1: from me. The current state is very misleading. I've already seen the wrong configuration because of it (someone put configuration option next to `plugins`).

**Comment by Reinmar** [comment]
Fun fact – the `language: 'en'` part of the current `src/ckeditor.js` wasn't necessary. Changing the setting of the `CKEditor5WebpackPlugin()` is enough. So, I confirmed we can remove `build-config.js` and avoid confusing duplication.

**Comment by ma2ciek** [comment]
Yes and no. If the only one language is provided, CKEditor5 will take that one. But if you feed CKEditor5 with many languages, then you need to specify which one should be loaded via the `language` option.

**Comment by Reinmar** [comment]
Are you sure? Cause I just checked :D 

```js
		new CKEditorWebpackPlugin( {
			// UI language. Language codes follow the https://en.wikipedia.org/wiki/ISO_639-1 format.
			// See: https://docs.ckeditor.com/ckeditor5/latest/features/ui-language.html
			language: 'en',
			additionalLanguages: 'all'
		} ),
```

With this configuration and no `config.language` passed to the editor, I can control the language by changing it in `CKEditorWebpackPlugin()`.

**Comment by Reinmar** [comment]
OK, there's a first PR: https://github.com/ckeditor/ckeditor5-build-classic/pull/46

Please verify it before I'll update other repos. 

PS. There's quite a lot of documentation to update now... ❤️

**Comment by Reinmar** [comment]
I know you won't read that so I'll repeat it here:

> BTW, I was also thinking about `Editor.builtinPlugins` and `Editor.builtinConfig` which, at least for me, are more precise. I'm not sure, though, whether it isn't me only.

**Comment by Reinmar** [comment]
Part of the work is done in https://github.com/ckeditor/ckeditor5-core/issues/140. Tomorrow I'll remove `build-config.js`, `createEntryFile()` utils and do all the other changes. I'll have to review the docs too...

**Comment by Reinmar** [comment]
I merged code changes but I'm reopening because there's still documentation to be updated.
