### ISSUE TITLE
Tests not working in ckeditor5-dev on Windows OS

### ISSUE THREAD

**Issue by przemyslaw-zan** [ckeditor/ckeditor5#10388]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to `ckeditor5-dev` repository on Windows OS
2.  Launch `npm run test`

### ✔️ Expected result

Tests start normally.

### ❌ Actual result

This error is thrown:

![](https://user-images.githubusercontent.com/69513154/130225381-1e4f0cac-b259-490c-96a9-1f9c843e6690.png)

It happens, because inside `package.json`, line: `"test": "mocha packages/*/tests --recursive --timeout 5000",` contains `*` wildcard that does not work on windows. 

#### Furthermore...

For testing purposes we can replace `*` with eg. `ckeditor5-dev-utils`, which reveals that many tests fail on Windows OS,  for example:

![](https://user-images.githubusercontent.com/69513154/130226879-26b76ebf-56a4-4a98-83f0-387d972955fa.png)

### ❓ Possible solution

Since many tests fail due to path problems, they can be fixed quite simply, eg. by replacing `path.` with `path.posix.` that ensures universal separators that work on both, Unix and Windows systems.

## 📃 Other details

*   OS: Windows

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Scope of the ticket:

- `npm run test` should not end with an error. Find a way how to execute tests from `packages/*/tests` on all OS.
- Correct all failing tests to pass.
- Should we create tests for Windows paths?

**Comment by pomek** [comment]
To verify: replacing a wildcard with the following command:

```
    "test": "mocha 'packages/*/tests/**/*.js' <...other options>"
```

**Comment by przemyslaw-zan** [comment]
Some tests fail, because they use `rm -rf` or `touch` commands - are there any universal cross-platform replacements for those?

**Comment by pomek** [comment]
- `rm -rf` => `rimrar` or `fs.unlinkSync()`
- `touch` => `fs.writeSync()`

**Comment by przemyslaw-zan** [comment]
Progress so far: [https://github.com/ckeditor/ckeditor5-dev/compare/ck/10388](https://github.com/ckeditor/ckeditor5-dev/compare/ck/10388)  
10 / 18 fixed so far.

Following test currently started failing, since timeout is 5000ms, and it happens to take 13830ms - I'll need to investigate why.

*   dev-env/release-tools/utils
    *   getCommits()
        *   branch for releasing is other than the main branch
            *   collects commits from the main branch and the release branch

**Comment by pomek** [comment]
Perhaps adding the `--no-verify` modifier to the `git commit ...` command will help. I'm not sure whether husky tries to check changes.

**Comment by przemyslaw-zan** [comment]
I've tried that and few other options, but it did not improve. However, that might be local problem, as it passes on travis. Could someone with MacOS verify, if [the changes](https://github.com/ckeditor/ckeditor5-dev/compare/ck/10388) caused any tests to fail, that currently work on master branch?

**Comment by przemyslaw-zan** [comment]
Last failing test:

![](https://user-images.githubusercontent.com/69513154/133430723-c98c54ea-7529-46e8-b7ca-f89403d0d0fc.png)

[https://github.com/ckeditor/ckeditor5-dev/blob/cac06588df7607e4050dbb1abb1c543d6b2[…]keditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js](https://github.com/ckeditor/ckeditor5-dev/blob/cac06588df7607e4050dbb1abb1c543d6b2[…]keditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js)

This line throws the error, no idea why would it throw the test on windows, since the path is correct.

**Comment by pomek** [comment]
> Could someone with MacOS verify

```
711 passing (17s)
```
