### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by vignesh-cloud-prog** [ckeditor/ckeditor5#10395]
I got the following errors while working with the next js

(node:14624) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
error - ./node_modules/@ckeditor/ckeditor5-clipboard/theme/clipboard.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@ckeditor\ckeditor5-clipboard\src\dragdrop.js

**Comment by FilipTokarski** [comment]
Hi, please note that  currently we don't have full support for Next.js. There's a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/7376), so you can check the discussion there - there are some [solutions proposed to the problem you mentioned](https://github.com/ckeditor/ckeditor5/issues/7376#issuecomment-802460193).
  
For the time being, I'll close this ticket as a duplicate.
