### ISSUE TITLE
ckeditor5-source-editing 模块编辑含有图片内容时表现异常

### ISSUE THREAD

**Issue by 874992019** [ckeditor/ckeditor5#10394]
![image](https://user-images.githubusercontent.com/12825352/130308533-1b86ecd6-d16f-49d3-8e4e-2435bd96f1d2.png)

![image](https://user-images.githubusercontent.com/12825352/130308566-7d21fd43-313f-4e05-9b37-5a487fc867aa.png)
htmlSupport 使用这个模块是 每上传一张图片 最后就会追加一个 <figure>&nbsp;</figure>  上传30张图片 最后出现了30个<figure>&nbsp;</figure>

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this case and [we are tracking it here](https://github.com/ckeditor/ckeditor5/issues/10279). I'll close this one as a duplicate.
