### ISSUE TITLE
Border style reducer does not return all possible shorthands for CSS properties

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#10399]
## 📝 Provide detailed reproduction steps (if any)

Assuming this GHS pattern:

```js
styles: {
  'border-left': /.*/
}
```

and markup like below:

```html
<p style="border-left: 1px solid;">
  foobar
</p>
```

There is a bug where border style reducer returns only style properties like ` border-left-width: 1px` and `border-left-style: solid`, but not `border-left: 1px solid` which prevents Matcher from correctly matching pattern to the style of the element.

The source of this behavior can be found here: https://github.com/ckeditor/ckeditor5/blob/e6cd6e4/packages/ckeditor5-engine/src/view/styles/border.js#L331-L362 .

This is a follow-up to [this comment](https://github.com/ckeditor/ckeditor5/issues/10282#issuecomment-903706092).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
> border-left: 1px solid

This definition is not valid. If you define an element with such style, a browser will use `#000` color as default instead of the specified in CSS. 

See the attached image:

![image](https://user-images.githubusercontent.com/2270764/130473341-8918bfe3-f451-4c12-a7ff-a580436268a0.png)

Border-color: `#000` (not specified anywhere, should be `#ff0`)

vs.

![image](https://user-images.githubusercontent.com/2270764/130473454-66a05b73-15ad-415e-aa1b-9af5611d60f7.png)

Border-color: `#ff0` (as the specified for `p`).

The short notation must contain all three definitions: width, style, and color.

**Comment by maxbarnas** [comment]
When stating that it's valid syntax, I was referring to https://drafts.csswg.org/css-backgrounds-3/#border-shorthands.

**Comment by pomek** [comment]
I read the [spec](https://drafts.csswg.org/css-backgrounds-3/#border-shorthands), and now I see that these values are not obligatory.

So there must be a reason why browsers inherit the initial value instead of the last specified in a tree.

**Comment by maxbarnas** [comment]
What the style reducers do now might be fine for our needs and they might be not in line with the spec. It's just that for now, Matcher is incorrectly working because of the missing style. We might as well modify the Matcher instead of reducers - I just wanted to point out that there's a problem.

**Comment by 108signals** [comment]
@maxbarnas @pomek wanted to see if there are any updates on this issue? Unfortunately our users have flagged this a few times since we first reported it [here](https://github.com/ckeditor/ckeditor5/issues/9790)

cc @magda-chrzescian @mlewand

**Comment by 108signals** [comment]
@maxbarnas @pomek wanted to see if are any updates on this issue? We are getting users flagging this issue on a monthly basis.

cc @magda-chrzescian @mlewand @mdabkowska88

**Comment by katypodbielski** [comment]
Hi CKE Team, I'm writing to see if there are any updates on this issue? Our users continue to flag and follow-up about this ticket. Resolving would improve the experience of using tables. Thank you

@maxbarnas @pomek @magda-chrzescian @mdabkowska88 @mlewand
