### ISSUE TITLE
OutdentList command inserts a paragraph despite paragraph being blocked by schema

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10405]
## 📝 Provide detailed reproduction steps (if any)

1.  Open https://ckeditor.com/docs/ckeditor5/29.1.0/examples/builds/document-editor.html
2.  Execute following JS code:
    1.  `editor.setData( '<ul><li>first</li><li>second</li><li></li></ul>' )`
    2.  `editor.model.schema.addChildCheck( ( context, item ) => { if ( context.endsWith( '$root' ) && item.name == 'paragraph' ) { return false; } } );` (it adds a schema rule that **prevents** placing paragraphs directly in root).
3.  Place the selectin in the last (empty) list item.
4.  Press enter.

### ✔️ Expected result

No paragraph is created.

### ❌ Actual result

A paragraph is created despite it is forbidden by schema.

You can verify this by calling `editor.model.schema.checkChild( '$root', 'paragraph' )` it will return `false`.

### ❓ Possible solution

The problem comes from the `IndentCommand`.

[https://github.com/ckeditor/ckeditor5/blob/0b9f989e86079cb755f6bbdc1a905aba9d3c9adf/packages/ckeditor5-list/src/indentcommand.js#L87](https://github.com/ckeditor/ckeditor5/blob/0b9f989e86079cb755f6bbdc1a905aba9d3c9adf/packages/ckeditor5-list/src/indentcommand.js#L87)

We should check if the paragraph is allowed. If not, the behavior is up to a debate.

For example we could look for any item that would be a block (see [`isBlock()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html#function-isBlock)). At least logically it should be possible to insert a `listItem` instead.

That's just a hotfix. The question is if there's a way to find the source of the problem. And the problem here is that we don't check schema when inserting stuff into the model (at least using the rename method, don't know about other methods).

## 📃 Other details

*   Browser: Any
*   OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
The `paragraph` element is the default model element to be used for many things. Enter key will also create it in some scenarios. Pasting, backspace, etc may too. It's the default block element and wherever any block element is allowed, paragraph must be too.

If you allow lists in the root, you must also allow paragraphs. These are interchangeable. Same for headings – if you want to allow ANY kind of block in the root, the paragraph must be allowed too. 

If you don't want paragraphs in the root you need to:

*   disallow other types of block elements too – e.g. make only limit objects (widgets) allowed in the root
*   convert paragraph to something else in the view – i.e. still allow it in the model but customize the view
