### ISSUE TITLE
Indent Block can't work with Nuxt.JS

### ISSUE THREAD

**Issue by quanghuy14399** [ckeditor/ckeditor5#10403]
## 📝 Provide detailed reproduction steps (if any)

1. I download CKEditor 5 by link https://ckeditor.com/ckeditor-5/download/?undefined-addons=
2. Add CkEditor5 to my Nuxt.JS like link https://blowstack.com/blog/ckeditor-5-nuxt-integration
3. Every thing is perfect expect Indent ( increase indent, decrease indent, bulleted list, numbered list doesn't work )

### ✔️ Expected result

Increase indent, decrease indent, bulleted list, numbered list work like link https://ckeditor.com/ckeditor-5/demo/

### ❌ Actual result

increase indent, decrease indent, bulleted list, numbered list doesn't work 

## 📃 Other details

* First affected CKEditor version: @ckeditor/ckeditor5-vue2
* Installed CKEditor plugins: 
+ @ckeditor/ckeditor5-build-classic
+ ckeditor5-build-full
+ @ckeditor/ckeditor5-indent": "^29.1.0"

I have already try to custom build with online builder https://ckeditor.com/ckeditor-5/online-builder/ but it have the same issue
Please help me to fix my issue.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Please check #5658. The classic build does not include the block indent plugin. The demo on [https://ckeditor.com/ckeditor-5/demo/](https://ckeditor.com/ckeditor-5/demo/) includes it. Hence, the difference.
