### ISSUE TITLE
We need a migration guide for changes in `viewportOffset` config.

### ISSUE THREAD

**Issue by dawidurbanski** [ckeditor/ckeditor5#10401]
## 📝 Provide a description of requested docs changes

This issue is a follow-up on [this PR](10352).

Previously setting `viewportTopOffset` was part of the `toolbar` config ([docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-toolbar)).

From now on it will be an object and set inside a new namespace `ui` like so:

```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		ui: {
			viewportOffset: {
				top: 100
			}
                 }
	} )
	.then( ... )
	.catch( ... );
```

We need to write a migration guide for this change.

**Comment by dawidurbanski** [comment]
@Reinmar pinging you as per your request.

**Comment by Reinmar** [comment]
> @Reinmar pinging you as per your request.

I meant, on Slack :d

**Comment by Reinmar** [comment]
Note: The upcoming release will be a major (30.0.0)
