### ISSUE TITLE
Decide what to do with duplicated translation contexts

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#10400]
## Provide a description of the task

There are 2 translation contexts with the same ID now. I missed that while reviewing and now this is on master branch.

One is in the `ui` package: https://github.com/ckeditor/ckeditor5/blob/1302e2b/packages/ckeditor5-ui/src/panel/balloon/contextualballoon.js#L420

The other in `find-and-replace`: https://github.com/ckeditor/ckeditor5/blob/1302e2b/packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.js#L479

We can either merge them and move to the `core` package, but then we should come up with general enough context or we can call `t()` with custom ID, e.g.

```js
t( {
	string: '%0 of %1',
	id: 'Custom %0 of %1'
} )
```

**Comment by Reinmar** [comment]
We agreed to merge both translations and move them to `core`. Let's also make the context a bit more generic, e.g.:

> Label for a ‘X of Y’ status of a typical next/previous navigation. For instance, ‘Page 5 of 20’.
