### ISSUE TITLE
App is crashing in windows 10 surface

### ISSUE THREAD

**Issue by ramana1240** [ckeditor/ckeditor5#1040]
## Is this a bug report or feature request? (choose one)

🐞 Bug report
 
   The app is crashing after click the app icon when CKEditor is used.

## 💻 Version of CKEditor

  CKEditor5 v10.0.0

## 📋 Steps to reproduce

1. Integrate the CKEditor 5 build classic in the IONIC1 app
2. Build the windows app
3. install the app in windows surface
4. click on the app icon. it will display the Splashscreen and then it will close 

## ✅ Expected result
      
    It should the app without any issue

## ❎ Actual result

   The app is crashing after click the app icon

**Comment by Reinmar** [comment]
How do you create an IONIC1 app? And how do you debug it? We have no experience with it and we're not able to test it.

First, we'd need to see an error that the app throws. Perhaps it will give us some ideas.

Then, we need to know how you use the editor. You need to post here the code, but not the entire app. Just a reduced sample of how you interact with the editor with a proof that the error occurs there.

Finally, it'd be good if we knew how to test a potential patch. So quick intro to building IONIC1 app, a sample repo, etc. would be greatly welcomed.
