### ISSUE TITLE
Tour Balloon error on feature documentation pages

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#10417]
## 📝 Provide detailed reproduction steps (if any)

1. Go to:
    1.  http://localhost:8080/ckeditor5/latest/features/find-and-replace.html
    2. http://localhost:8080/ckeditor5/latest/features/images/images-overview.html
2. Open dev tools/console.

### ❌ Actual result

There's an error like below (**or similar - depending on the URL**) in the console:

```
[attachTourBalloon] The target DOM node for the feature tour balloon does not exist. {text: "Click to find and replace anything you need."}
```

## 📃 Other details

A similar problem happens under links below, but is related to mobile device's narrow screen.
1. http://localhost:8080/ckeditor5/latest/features/images/image-upload/image-upload.html
1. http://localhost:8080/ckeditor5/latest/features/math-equations.html
1. http://localhost:8080/ckeditor5/latest/features/special-characters.html

* Browser: Chrome 92
* OS: MacOS X, Android 11

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Issue still occurs. I'm adding `ccx` label.

Tour balloon is missing since version 29.1.0. It's there on 29.0.0. Between these versions there was a change to button type for Find&Replace button toolbar. It used to be SplitButton, but since 29.1.0 it's using the Dropdown button.

**Comment by godai78** [comment]
Both guides merged in https://github.com/ckeditor/ckeditor5/pull/11079
