### ISSUE TITLE
Text transformation: Allow reverting by pressing backspace

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10413]
## 📝 Provide a description of the improvement

Currently, we allow reverting an automatic transformation result by pressing undo. It's a separate undo step.

However, it's common among other editors to also allow reverting text transformation by pressing backspace immediately after transformation happened.

It works this way in GDocs and Word:

1.  Type "1/2"
2.  Type space
3.  It gets converted to "½ "
4.  Press backspace
5.  You get: "1/2 "

Note: It's super smart in Word where this 1/2 never gets converted back to a fraction again, even if you remove that space and type it again. However, GDocs doesn't implement this mechanism and you can again trigger transformation again by typing another space. We can do KISS as both options make some sense, plus going in a Word-like direction would require more work.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Note: In GDocs and Word backspace behaves like undo – this is – you can redo that change.

Note: What about autolinking, auto media embed, etc.

**Comment by arkflpc** [comment]
Are we sure about Autoformat yet?

**Comment by Reinmar** [comment]
I'd go without autoformat for now because this will be safer. But, it'd be good to test how this works with autoformat to see whether the UX is good or confusing.

Hence, if you could create a PR for the features that we want to cover and then a second draft PR (based on that former PR) for autoformat?

**Comment by arkflpc** [comment]
PR to test autoformat: #10508
