### ISSUE TITLE
Schema deep dive guide mentions "image" element

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10419]
## 📝 Provide a description of requested docs changes

[http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html#defining-additional-semantics](http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html#defining-additional-semantics) - there is a mention of an `image` but currently we have `imageBlock` and `imageInline`.

![](https://user-images.githubusercontent.com/1232187/130791517-987ca757-bc36-4ba1-b294-009dcf24ce78.png)

**Comment by godai78** [comment]
Merged in #10549
