### ISSUE TITLE
 Strange behavior when user inputs "<sometexthere>" in ckeditor, data is sent to the server, and rewriten in ckeditor

### ISSUE THREAD

**Issue by NicolasCast** [ckeditor/ckeditor5#1043]
ckeditor handles text between char '<' and '>' (less than / more than signs) strangely.

## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

* CKEditor version: CKEditor 5 classic editor build v10.0.0
* Installed CKEditor plugins: none

## 📋 Steps to reproduce

ckeditor handles text between char '<' and '>' (less than / more than signs) strangely.

CASE 1

1. setup ckeditor 5 on a textframe inside a html form
2. in ckeditor, the user write :
> <script>
3. send the data to the server (POST method)
4. print the received POST data in the same textframe (where ckeditor acts), without any modification

CASE 2

1. setup ckeditor 5 on a textframe inside a html form
2. in ckeditor, the user write :
> \<blablahello\>
3. send the data to the server (POST method)
4. print the received POST data in the same textframe (where ckeditor acts), without any modification

## ✅ Expected result

CASE 1

ckeditor should display :
> <script>

CASE 2

ckeditor should display :
> \<blablahello\>

## ❎ Actual result

CASE 1

ckeditor displays :
> \<\p\>

CASE 2

ckeditor displays nothing (empty)

## 📃 Other details that might be useful
* Browser: Firefox 60.0.1 quantom
* OS: windows

**Comment by Reinmar** [comment]
> print the received POST data in the same textframe (where ckeditor acts), without any modification

I'm afraid that you have a mistake in this step. It's a common mistake to not encode the textarea's value correctly.

Check out this JSFiddle how the content of a textarea needs to be encoded: https://jsfiddle.net/adsvfnn0/

E.g. the `<p>Some text: &lt;foo&gt;</p>` data needs to be printed in HTML as:

```html
<textarea>&lt;p&gt;Some text: &amp;lt;foo&amp;gt;&lt;/p&gt;</textarea>
```

The following ARE NOT CORRECT:

```html
<textarea><p>Some text: &lt;foo&gt;</p></textarea>
<textarea>&lt;p&gt;Some text: &lt;foo&gt&lt;/p&gt;</textarea>
```
