### ISSUE TITLE
LabeledFieldView with a value renders label incorrectly when disabled

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10431]
## 📝 Provide detailed reproduction steps (if any)

A generalization of #10429.

We didn't notice this before because the only place where `LabeledFieldView` was getting disabled was the table properties form and we reset the value there automatically when the field gets disabled. Now we have this use-case in find and replace and probably more will come

![](https://user-images.githubusercontent.com/69513154/130956334-914e4a2d-bc65-4317-991d-b69d464fc185.png)

### ❓ Possible solution

Most likely this will require only changes in CSS.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Refinement notes:

*   Tricky to reproduce
*   Sometimes happens... sometimes not
*   Not clear what may be wrong here (focus or emptiness detection? browser bug?)
*   Estimate: 1pt as the top ROI margin
