### ISSUE TITLE
The `getEnvKeystrokeText` utility breaks for certain combos starting in v26

### ISSUE THREAD

**Issue by jzempel** [ckeditor/ckeditor5#10439]
## 📝 Provide detailed reproduction steps (if any)

```js
import { getEnvKeystrokeText } from '@ckeditor/ckeditor5-utils/src/keyboard';

getEnvKeystrokeText('CTRL+[');
getEnvKeystrokeText('CTRL+]');
```

Prevents Zendesk Garden from updating the demo [Editor](https://github.com/zendeskgarden/ckeditor/blob/c8e7c6f34733d35da9a5f86ad001ac4e315960ed/src/stories/Editor.js#L43-L44).

### ✔️ Expected result

Successfully parse this common keystroke for indent/outdent. This used to work in v25.

### ❌ Actual result

```
Unexpected error while loading ./stories/index.stories.js: CKEditorError: keyboard-unknown-key {"key":"["}
```

### ❓ Possible solution

Debug changes made in https://github.com/ckeditor/ckeditor5/compare/v25.0.0...v26.0.0#diff-8a8feb9905511e353215fac103af1ff8dbf4ed40e7e24d3994c63e28f1a8f756.

## 📃 Other details

* Browser: any
* OS: any
* First affected CKEditor version: v26
* Installed CKEditor plugins: not relevant

Possibly related to #9412 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. It seems that `[` and `]` characters are not supported, so the editor doesn't know how to translate them to key codes. 

For now, you can add it on your own by adding them manually to the [`generateKnownKeyCodes()`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-utils/src/keyboard.js#L216) function:

```javascript
keyCodes[ '[' ] = 219;
keyCodes[ ']' ] = 221;
```

**Comment by jzempel** [comment]
@Mgsy that seems to patch the runtime parsing error. However [EditingKeystrokeHandler](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-core/src/editingkeystrokehandler.js) still seems to be affected as [setting the corresponding UI shortcuts](https://github.com/zendeskgarden/ckeditor/blob/c8e7c6f34733d35da9a5f86ad001ac4e315960ed/src/stories/Editor.js#L98-L99) results in `undefined`.

<img width="250" alt="Screen Shot 2021-08-30 at 12 34 20 PM" src="https://user-images.githubusercontent.com/143773/131373118-bb7ea3b8-25dc-4577-bff6-6e618e8e2264.png">

**Comment by jzempel** [comment]
also apologies, I misspoke. This used to work in v24.0.0.

**Comment by jzempel** [comment]
> I've checked it at versions < 26.0.0 and it seems to behave the same, so it doesn't seem to be a regression.

- Please see the successful [deployment](https://612d0bdc31e6570097c78ec9--zendeskgarden-ckeditor.netlify.app/?path=/story/demo--default) connected with the https://github.com/zendeskgarden/ckeditor/commit/8bfbc528641382a192227412c847af59a389859b bump to **v25**. As you can see, [existing square bracket key strokes](https://github.com/zendeskgarden/ckeditor/blob/c8e7c6f34733d35da9a5f86ad001ac4e315960ed/src/stories/Editor.js#L40-L48) work as expected.
- Now see the follow-on [deployment](https://612d0e4386eca7008e008c79--zendeskgarden-ckeditor.netlify.app/) on that same branch with the https://github.com/zendeskgarden/ckeditor/commit/b365b8ce18a77c46ba494cf1c58d30f850ff3774 bump to **v26**. Open the browser dev console to see the runtime error when attempting to parse [the same lines](https://github.com/zendeskgarden/ckeditor/blob/c8e7c6f34733d35da9a5f86ad001ac4e315960ed/src/stories/Editor.js#L43).

This history is documented in https://github.com/zendeskgarden/ckeditor/pull/17. What am I missing?

**Comment by Mgsy** [comment]
Thanks for the details! I've checked it once again and indeed, `getEnvKeystrokeText` was working properly with `[` and `]` characters before version 26.0.0. It looks like this is a regression introduced by this change 5c2a69a.

**Comment by Reinmar** [comment]
We can go in two directions:

*   Somehow revert the change that we made so keys that our tool does not recognize (`[` and `]` would not work when e.g. trying to set such a keystroke – they only worked in `getEnvKeystrokeText()`).
*   Add more keys to the [list of known keys](https://github.com/ckeditor/ckeditor5/blob/1fc2435/packages/ckeditor5-utils/src/keyboard.js#L216-L255).

I'm for the latter to be consistent. If we went with the first option, `getEnvKeustrokeText()` would work, but `parseKeystroke()` e.g. wouldn't. It makes no sense.

So the characters to add, at least looking at my keyboard layout: `` `[];',./\`` 

I simply went through all the special characters. We should also scan 2-3 other common keyboard layouts.

Question: How to support characters that require Shift? E.g. `{}` on my keyboard at least. Can they be used for keystrokes? What for other keyboard layouts?

**Comment by Reinmar** [comment]
BTW, @jzempel, are you sure that you want to override Cmd+\[? This keystroke is used by some people to navigate back/forth in the browser history.

**Comment by Reinmar** [comment]
> I simply went through all the special characters on my keyboard. We should also scan 2-3 other common keyboard layouts.
> 
> Question: How to support characters that require Shift? E.g. `{}` on my keyboard at least. Can they be used for keystrokes? What about other keyboard layouts?

Since this is the first issue in this category for a long time, let's ignore these doubts for now. Let's:

*    add the aforementioned characters to the list
    *   don't forget about updating `export const keyCodes` documentation,
*   make sure that the utils in `keyboard.js` throw a meaningful error when passed an unknown key
