### ISSUE TITLE
Accessing the editor object for multiple instances

### ISSUE THREAD

**Issue by thdoan** [ckeditor/ckeditor5#1044]
## Is this a bug report or feature request? (choose one)

Other (documentation question)

## 💻 Version of CKEditor

CKEditor 5, v10.0.1

## 📃 Other details that might be useful

I was not able to find the answer in the documentation, so hoping someone could answer it here: you can usually access the the API through `window.editor`; however, when there are multiple instances ([example](https://docs.ckeditor.com/ckeditor5/latest/examples/builds/inline-editor.html)), how do I, for example, use `setData()` on the first inline editor? `window.editor.setData()` updates the contents for the third inline editor only.

**Comment by Reinmar** [comment]
Hi! This question was already answered on https://stackoverflow.com/questions/48575534/ckeditor-5-get-editor-instances/48682501#48682501 and https://stackoverflow.com/questions/46816098/how-to-get-data-from-ckeditor5-instance.

**Comment by thdoan** [comment]
Thanks @Reinmar .
