### ISSUE TITLE
Version 10

### ISSUE THREAD

**Issue by karoltarasiuk** [ckeditor/ckeditor5#1045]
Just a simple question, and didn't know where to ask. Why from `v1.0.0-beta.4`, did you move to `10.0.0`? Is there a reason that your major is `10`, or is it just a mistake?

**Comment by AnnaTomanek** [comment]
It's not a mistake. It was done on purpose, to avoid any collision with [CKEditor 4](https://ckeditor.com/ckeditor-4/) versions.
