### ISSUE TITLE
[Docs] Fix regexp in webpack configuration

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1046]
The regexps here: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-configuration do not handle Windows paths (unless webpack normalizes them – this must be verified first!)

The other thing is that I'd replace those CKEditor 5-only regexps from comments to the normal code because in majority of situations people will be integrating this webpack config with their projects, so let's make sure that only CKEditor 5 files are treated in this way.

Finally, we need to add a note at the end of this section that if you're adding CKEditor 5 to an existing project where there are other loaders for SVG or CSS files already you need to take care of excluding CKEditor 5 files from those loaders' configuration. Just like @szymonkups described in https://github.com/ckeditor/ckeditor5-react#changes-that-need-to-be-made-to-both-config-files-webpackconfigdevjs-and-webpackconfigprodjs.

However, what I'd also like to have checked here is whether having loaders needed for CKEditor 5 at the top of the loaders definitions will not be enough. I mean  – can a single file be handled by multiple loaders? Or is only the first loader applied?

**Comment by ma2ciek** [comment]
>I mean – can a single file be handled by multiple loaders? Or is only the first loader applied?

All matching loaders are applied to the given file by default. But this option can be changed by using: https://webpack.js.org/configuration/module/#rule-oneof.

>The regexps here: docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-configuration do not handle Windows paths (unless webpack normalizes them – this must be verified first!)

I guess, webpack doesn't normalize paths, but I couldn't find any additional information in docs.

**Comment by Reinmar** [comment]
> All matching loaders are applied to the given file by default. But this option can be changed by using: https://webpack.js.org/configuration/module/#rule-oneof.

Unfortunately, we can't enforce that. Loader configuration for CKEditor 5 assets will be added to existing webpack configs and will remain a flat list of loaders. So, mentioning `exclude` is our only hope.

**Comment by ma2ciek** [comment]
I tried the following config

```
rules: [
	{
		test: /\.svg$/,
		use: [ 'raw-loader' ]
	},
	{
		test: /\.svg$/,
		use: [ 'raw-loader' ]
	}
]
```

and it resulted in an error.

> Unfortunately, we can't enforce that. Loader configuration for CKEditor 5 assets will be added to existing webpack configs and will remain a flat list of loaders. So, mentioning exclude is our only hope.

Yep, with that approach `oneof` doesn't solve anything. But the developer will need to be careful to not cover CKE5 files with his own loader anyway e.g. by excluding `node_modules`.

**Comment by Reinmar** [comment]
I'll move this ticket to it19 cause I have to think on it a bit. Docs need to make sure when read from top to bottom.

**Comment by ma2ciek** [comment]
The other thing I see now is that we provide two `@ckeditor/ckeditor-...` packages and the JS code from both of them won't be transpiled using the `/ckeditor5-[^\/\\]+[\/\\].+\.js$/` test. Not sure though if anyone needs the transpilation to ES5 at all 😅

cc @Reinmar.
