### ISSUE TITLE
paste-from-office not work

### ISSUE THREAD

**Issue by xiamo0201** [ckeditor/ckeditor5#10460]
## 📝 Provide detailed reproduction steps (if any)

1. Download the sample Word document
2. Select all and copy
2. Paste to the example editor

### ✔️ Expected result
reserved style and text

### ❌ Actual result
reserved style but missing text,as shown in the picture.

![image](https://user-images.githubusercontent.com/13410651/131627393-85d039ae-2d30-4060-990e-04aa84cf7065.png)

**Comment by Mgsy** [comment]
Hi! Thanks for the report. I've checked this scenario and the example content pastes properly:

![](https://user-images.githubusercontent.com/20988892/131628180-df721503-6cba-40b4-9363-d511ea8c599b.png)

Could you please tell me, which version of MS Word are you using?

**Comment by xiamo0201** [comment]
> Hi! Thanks for the report. I've checked this scenario and the example content pastes properly:
> 
> ![](https://user-images.githubusercontent.com/20988892/131628180-df721503-6cba-40b4-9363-d511ea8c599b.png)
> 
> Could you please tell me, which version of MS Word are you using?

I use WPS Office，version 3.8.1

**Comment by xiamo0201** [comment]
> Hi! Thanks for the report. I've checked this scenario and the example content pastes properly:
> 
> ![](https://user-images.githubusercontent.com/20988892/131628180-df721503-6cba-40b4-9363-d511ea8c599b.png)
> 
> Could you please tell me, which version of MS Word are you using?

I use WPS Office，version 3.8.1
* Browser: chrome

**Comment by xiamo0201** [comment]
> Hi! Thanks for the report. I've checked this scenario and the example content pastes properly:
> 
> ![](https://user-images.githubusercontent.com/20988892/131628180-df721503-6cba-40b4-9363-d511ea8c599b.png)
> 
> Could you please tell me, which version of MS Word are you using?

Just now I tried. ckeditor4 supports WPS and MS word, but ckeditor5 does not support WPS

**Comment by Mgsy** [comment]
CKEditor 5 doesn't support pasting from WPS, however, we have a feature request for it - #2488. Feel free to add :+1: to the first post to bump its popularity.
