### ISSUE TITLE
ckeditor5-core/plugincollection: get() misses `undefined` as return type

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#10478]
## 📝 Provide a description of requested docs changes

The documentation of `PluginCollection.get()` states, that it will always return `PluginInterface`. From implementation, this is not true, as it will return `undefined` if a plugin cannot be found.

An alternative would be throwing an exception, as (referring to the documentation) it is recommended using `has` before `get`, thus any check for `undefined` is irrelevant after using `has`. This is especially relevant to CKEditor-Typings as can be found at DefinitilyTyped.

**Comment by mlewand** [comment]
@mateuszzagorski be sure to target this change at `stable` branch as this is a docs only change.

**Comment by mateuszzagorski** [comment]
Hi @mmichaelis, it shouldn't be possible for that method to return as `undefined`. As you can see below:

[https://github.com/ckeditor/ckeditor5/blob/66a28aba0536628ddfb182865d68a7f5110eda35/packages/ckeditor5-core/src/plugincollection.js#L116-L138](https://github.com/ckeditor/ckeditor5/blob/66a28aba0536628ddfb182865d68a7f5110eda35/packages/ckeditor5-core/src/plugincollection.js#L116-L138)

If a plugin is not found, an `exception` will be thrown.
