### ISSUE TITLE
add copyformatting

### ISSUE THREAD

**Issue by JSNU-Bighead** [ckeditor/ckeditor5#10476]
There is copyformatting function in ckeditor4 but not in ckeditor5，Can you add this feature？
https://ckeditor.com/docs/ckeditor4/latest/examples/copyformatting.html

**Comment by shahzebgit** [comment]
You can see the information on whether it's making to an iteration in its #1901 issue. Make sure to add +1 reaction if you haven't already to show your support

**Comment by mlewand** [comment]
Thanks @shahzebgit - this is indeed a duplicate.
