### ISSUE TITLE
Calling `editor.setData( editor.getData() )` during image upload without content makes editor unusable

### ISSUE THREAD

**Issue by dawidurbanski** [ckeditor/ckeditor5#10487]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the all features manual test.
2.  Remove the whole content.
3.  Start uploading some big image. I'm using a 15Mb image ([https://effigis.com/wp-content/uploads/2015/02/DigitalGlobe_WorldView1_50cm_8bit_BW_DRA_Bangkok_Thailand_2009JAN06_8bits_sub_r_1.jpg](https://effigis.com/wp-content/uploads/2015/02/DigitalGlobe_WorldView1_50cm_8bit_BW_DRA_Bangkok_Thailand_2009JAN06_8bits_sub_r_1.jpg)).
4.  During the upload call `editor.setData( editor.getData() )`.

### Other, simpler way to reproduce:

1.  Call `editor.setData( '<figure class="image"><img></figure>' )`.

### ✔️ Expected result

Editor should be usable after this

### ❌ Actual result

The empty element is inserted, however, it's not possible to type anything or create a new paragraph. The image toolbar is attached to this empty element.

### ❓ Possible solution

This is a problem with a selection postfixer which cannot fix `<figure class="image"><img>[]</figure>`;

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Most likely, it's browser-specific. SO far we were reproducing this on Chrome.

**Comment by Reinmar** [comment]
*   `<imageBlock>` is a limit element.
*   The selection ends up inside it: `<imageBlock>[]</imageBlock>`.

![](https://user-images.githubusercontent.com/156149/132475542-9a0ff164-cb99-4a83-a9eb-7e73286f7290.png)

There are two issues here:

1.  The selection is not fixed.
2.  The widget has height of 0px and hence it's not clickable.
    1.  It only happens for images with no `src` or empty `src`
    2.  Images with non-empty src (even if we get 404) are displayed like this:

![](https://user-images.githubusercontent.com/156149/132476087-02e1f4a1-6e9e-4417-b582-e69c9c471183.png)

The first issue is more general and if we fix it we will partially resolve the general UX problem. The second issue is browser-specific (happens only in Chrome) and it would require some odd hacking to be resolved.

Hence, let's focus on the first issue.

**Comment by Reinmar** [comment]
The piece of code that we should probably fix: [https://github.com/ckeditor/ckeditor5/blob/1fc24358c2bc70f0dbc674a49213bfbf955f67b9/packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js#L131-L135](https://github.com/ckeditor/ckeditor5/blob/1fc24358c2bc70f0dbc674a49213bfbf955f67b9/packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js#L131-L135)

In such a case, consider going out of the limit element (imageBlock is a limit element). Go up the tree and find the closest ancestor that is a selectable element.

```
<superBox>
	<section>[]</section>
	<section></section>
</superBox>
```

Assuming that `section` is a limit element (`isLimit`), but not selectable itself (`!isSelectable`) and that it does not allow text inside and that `superBox` is an object (and hence, a selectable element), we should select `superBox`.
