### ISSUE TITLE
Weird whitespace underneath editor when wrapped in flex container

### ISSUE THREAD

**Issue by TimHav** [ckeditor/ckeditor5#10484]
## 📝 Provide detailed reproduction steps (if any)

1. Use Material UI
2. Create a vertical container
3. Create a horizontal container inside the vertical container
4. Add the CKEditor inside an item of the horizontal container

### ✔️ Expected result

The editor behaves normally, not taking up more space than its bounding border.

### ❌ Actual result

Weird whitespace appears underneath the editor, depending on what you type.

### ❓ Possible solution

Other than using another solution than Material UI, I'm at a loss as to why this whitespace appears. I cannot locate it using the browser inspector.

## 📃 Other details

* Browser: Tested in Firefox and Chrome (latest)
* OS: Windows
* Used dependencies:
 @ckeditor/ckeditor5-build-classic: 29.2.0 (current latest)
 @ckeditor/ckeditor5-react: 3.0.2 (current latest)

Code sandbox showing this behavior: https://codesandbox.io/s/ckeditor-with-whitespace-ycd77

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! Please try to recreate this issue with minimal page styles. We can look into a problem if we see that it's clearly caused by the editor. But in the demo that you linked there's Material UI included so it's hard to understand where the problem is.

**Comment by TimHav** [comment]
Hi @Reinmar, thanks for your reply.
The combination of the Material UI wrappers with the CKEditor is the cause of this issue, the issue is not present without the wrappers. However, I would like to use the CKEditor with these wrappers. Other content inside these wrappers do not have this issue, so it is clearly caused by the CKEditor, as is shown when you add or remove content.

**Comment by TimHav** [comment]
For anyone experiencing the same issue, here are two workarounds:

1. Disable wrapping on the column container by adding `wrap="nowrap"`
2. Use floats for the horizontal container

**Comment by TimHav** [comment]
Closing this, as there is a workaround and I do not see priority going to this issue.
