### ISSUE TITLE
Cannot type after inline widget

### ISSUE THREAD

**Issue by lucasriondel** [ckeditor/ckeditor5#1049]
I tried to create a plugin that uses an inline widget. The plugin should insert an inline, non-editable HTML element with some text into the editor content. I used `toWidget` to widgetize the element. However I have a weird issue:

* if I put the widget straight after some text (`blablabla<variable>myVar</variable>`) without any whitespace between text and widget, I am able to type text after the widget,
* but if I put a whitespace (`blablabla <variable>myVar</variable>`), I cannot type anything after the widget, I only can put a caret there and press <kbd>Enter</kbd>.

Here's a video of what's happening : https://streamable.com/2l4hz

And here's the code:

My plugin: 

```
function downcastInsertVariable(options: { asWidget?: boolean } = {}) {
  return dispatcher =>
    dispatcher.on(
      'insert:variable',
      (evt, data, conversionApi) => {
        const variable = data.item

        if (!conversionApi.consumable.consume(variable, 'insert')) {
          return
        }

        conversionApi.consumable.consume(variable, 'attribute:id:variable')

        const asWidget = options && options.asWidget

        const variableElement = conversionApi.writer.createContainerElement('variable')

        let variableWidget

        if (asWidget) {
          variableWidget = toWidget(variableElement, conversionApi.writer)
        }

        const viewPosition = conversionApi.mapper.toViewPosition(data.range.start)

        conversionApi.mapper.bindElements(variable, asWidget ? variableWidget : variableElement)
        conversionApi.writer.insert(viewPosition, asWidget ? variableWidget : variableElement)
      },
      { priority: 'normal' }
    )
}

class InsertVariable extends Plugin {
  public init() {
    const editor = this.editor

    editor.model.schema.register('variable', {
      inheritAllFrom: '$text',
      allowAttributes: ['id'],
      isObject: true
    })

    editor.model.schema.extend('$text', {
      allowIn: 'variable'
    })

    editor.conversion.for('upcast').add(upcastElementToElement({ model: 'variable', view: 'div' }))
    editor.conversion.for('editingDowncast').add(downcastInsertVariable({ asWidget: true }))
    editor.conversion.for('dataDowncast').add(downcastInsertVariable())
    editor.conversion.attributeToAttribute({ model: 'id', view: 'id' })

    editor.ui.componentFactory.add('insertVariable', locale => {
      const view = new ButtonView(locale)

      view.set({
        label: 'Insert variable',
        icon: imageIcon,
        tooltip: true
      })

      view.on('execute', () => {
        editor.model.change(writer => {
          const variableElement = writer.createElement('variable', {
            id: 'some-id'
          })

          writer.insertText('variable', { bold: true }, variableElement, 'end')

          editor.model.insertContent(variableElement, editor.model.document.selection)
        })
      })

      return view
    })
  }
}
```

And here's my editor initialization (with a bit of React code, sorry about that) : 

```
  public async initEditor() {
    this.editor = await DecoupledEditor.create(
      ReactDOM.findDOMNode(this.editorRef.current as HTMLDivElement),
      {
        plugins: [
          Essentials,
          Bold,
          Italic,
          Underline,
          Paragraph,
          Heading,
          HeadingUI,
          Alignment,
          InsertVariable
        ],
        toolbar: [
          'heading',
          'bold',
          'italic',
          'underline',
          'alignment:left',
          'alignment:right',
          'alignment:center',
          'insertVariable'
        ],
        fontFamily: {
          options: 'Montserrat sans-serif'
        },
        heading: {
          options: [
            { model: 'heading1', view: 'h4', title: 'Titre de section', class: 'section-title' },
            { model: 'paragraph', title: 'Texte', class: 'ck-heading_paragraph' }
          ]
        }
      }
    )
    const el = ReactDOM.findDOMNode(this.toolbarRef.current as HTMLDivElement)
    if (el instanceof Element) {
      el.appendChild(this.editor.ui.view.toolbar.element)
    }
  }
```

Any idea?

**Comment by Reinmar** [comment]
I created a separate ticket to track inline widgets support: https://github.com/ckeditor/ckeditor5/issues/1050.

**Comment by lucasriondel** [comment]
a new weird behavior (with the same code) : https://streamable.com/a780v
when i click on my element, i am able to delete text from it using backspace or delete.

**Comment by lucasriondel** [comment]
while watching the dom, i have also found what might be a weird behavior related to my issue (it's not happening with images, by example) https://streamable.com/8sv43

**Comment by lucasriondel** [comment]
more tests... https://streamable.com/lepds

**Comment by Reinmar** [comment]
@scofalik why did you recommend using text attribute for this? I don't think that you can reliably handle this this way. There's no way then to mark this piece of content as an object in the model. Perhaps, one day we could make this possible, but IMO widgets should be elements.

**Comment by Reinmar** [comment]
I removed my comment because it was completely incorrect.

**Comment by Reinmar** [comment]
> ```
>     editor.conversion.for('editingDowncast').add(downcastInsertVariable({ asWidget: true }))
>     editor.conversion.for('dataDowncast').add(downcastInsertVariable())
> ```

@scofalik, why did we need custom converters here?

> but if I put a whitespace (blablabla <variable>myVar</variable>), I cannot type anything after the widget, I only can put a caret there and press Enter.

It may be related to https://github.com/ckeditor/ckeditor5/issues/1024. cc @pomek

**Comment by scofalik** [comment]
We need custom converters to widgetize the inserted element. There's no `elementToWidget` converter AFAIR :)

**Comment by Reinmar** [comment]
Can't we provide a callback to `elementToElement()`?

**Comment by Reinmar** [comment]
Just like in one of the tests:

```js
		conversion.for( 'editingDowncast' ).add( downcastElementToElement( {
			model: 'fancywidget',
			view: ( modelItem, viewWriter ) => {
				const widgetElement = viewWriter.createContainerElement( 'figure', { class: 'fancy-widget' } );
				viewWriter.insert( ViewPosition.createAt( widgetElement ), viewWriter.createText( 'widget' ) );

				return toWidget( widgetElement, viewWriter );
			}
		} ) );
```

**Comment by scofalik** [comment]
Oh, yeah, we could.

**Comment by lucasriondel** [comment]
Any updates ? @scofalik @Reinmar

**Comment by lucasriondel** [comment]
I've been able to find a workaround which makes my code work but involves more bugs. It is working if I force a `Text` element next to my Variable element.

```
editor.model.insertContent(variableElement, editor.model.document.selection)
editor.model.insertContent(new Text(' '), editor.model.document.selection)
```

unfortunately, when I click on my variable element, and press enter, it breaks my element in two.

before : 
`<variable class="ck-widget" contenteditable="false"><strong>Variable1</strong></variable>`

after : 
`<variable class="ck-widget" contenteditable="false"><strong>Vari</strong></variable><variable class="ck-widget" contenteditable="false"><strong>able2</strong></variable></p>`

also, if I press backspace while on my element, it breaks in two but differently: 

`<variable class="ck-widget" contenteditable="false"><strong>Vari</strong><p><br data-cke-filler="true"></p><strong>ble1</strong></variable>`

And in that case, if I try to fix it, this error is thrown: 

`Uncaught CKEditorError: move-operation-node-into-itself: Trying to move a range of nodes into one of nodes from that range.` Then, I can't do anything with the editor, it's messed up.

The wanted behavior is close, actually. If only I could stop CKEditor from handling key presses such as `enter` or `backspace` when my element is clicked, it would be perfect !

**Comment by Reinmar** [comment]
I found one more issue – attributes get applied inside this element:

![image](https://user-images.githubusercontent.com/156149/40926372-57af469e-681c-11e8-9197-0fa74b4a2f4c.png)

And this is tricky... We need to think how to resolve this because so far we didn't have attribute elements used next to container elements. What's more, in the model it's the text inside the `<placeholder>` element what gets the attribute, while this text shouldn't actually be styleable. It's non-editable. If anything, the `<placeholder>` should get this attr :D

cc @scofalik @oskarwrobel @pjasiun

**Comment by Reinmar** [comment]
OK, two ideas:

1. Disallow attributes on `placeholder>$text` and allow them on the `placeholder` itself (via Schema).
2. Move the text of the placeholder to its attribute to keep this element empty in the model.

**Comment by Reinmar** [comment]
Buuut... if we want to allow generating data like this:

```html
<p><strong>xx <placehoder>yy</placeholder> yy</strong></p>
```

we have a problem now because AFAIR a `ContainerElement` cannot be inside an `AttributeElement`. So, should we use `UIElement` here? It doesn't seem to be right too.

**Comment by scofalik** [comment]
1. I don't think that `<placeholder>` should be a `ContainerElement`.
2. How did you define `placeholder` in `Schema`? I thought as `inheritAllFrom: '$text'`?
3. Both solutions (disallowing attributes inside placeholder and moving placeholder text to attribute) are fine. As long as placeholder texts are only taken from dropdowns (and are not editable through typing) we will be fine. If they were editable through typing, we won't have a perfect OT then.

**Comment by scofalik** [comment]
Okay I see that your placeholder definition does not inherit attributes allowance from `$text`. I think it should.

**Comment by scofalik** [comment]
`ContainerElement` should not be inside `AttributeElement`. This will not work. We can prevent merging `AttributeElement`s, we already have mechanisms for that (`id`s, that we introduced quite recently, we were thinking about them in `abbr` context, they should work).

If you don't like `AttributeElement`s (and I don't blame you for that), we need a new type of element.

**Comment by Reinmar** [comment]
OK, let's wait for @pjasiun with this. This is an important decision.

**Comment by lucasriondel** [comment]
@Reinmar I've tried your code, and i'm still facing the typing issue.

**Comment by Reinmar** [comment]
What do you mean by typing issues? I've just tested typing right after a widget and it worked just fine.

**Comment by lucasriondel** [comment]
Well I still have this issue..

**Comment by Reinmar** [comment]
Would it be possible that you created a repo with all the code needed for us to reproduce it. Plus, please include the exact steps to reproduce this issue. The devil may be in the details.

**Comment by lucasriondel** [comment]
Sure, i'll try.

**Comment by lucasriondel** [comment]
@Reinmar there you go https://github.com/lucasriondel/issue-placeholder-ckeditor

**Comment by Reinmar** [comment]
I'll get back to this ticket once we'll release v10.1.0. It's a busy week, sorry.

**Comment by lucasriondel** [comment]
I understand, don't worry. Thanks again for your time.

**Comment by Reinmar** [comment]
BTW, do you test this in Firefox maybe?

**Comment by lucasriondel** [comment]
No, I am using chrome.

**Comment by dkrahn** [comment]
@Reinmar I replicated the case by having the inline widget at the end of the paragraph. If the widget has a space(\&nbsp;) right before it, no text can be added after it.
It works fine If you already have some text after the widget, or no space right before it.
Hope my description helps.

**Comment by jodator** [comment]
It's kinda funny to see that if inline widget is glued to some text you can type after it.

But if there is a space before you cannot:

![peek 2019-01-24 14-51](https://user-images.githubusercontent.com/247363/51682409-a81ead80-1fe7-11e9-9e76-0f17981efad5.gif)

**Comment by jodator** [comment]
@Reinmar yep it might be also related to how spaces are handled - it looks like they are not normalized and there's change detected in the `'Hello&nbsp'` part alone.

**Comment by top-dev830** [comment]
I've read above. It seems I need to create element using `AttributeElement`, coz I need to stylize (bold, italic, font, font-size, font color) for the placeholder text.
How can I approach this?

**Comment by top-dev830** [comment]
> `ContainerElement` should not be inside `AttributeElement`. This will not work. We can prevent merging `AttributeElement`s, we already have mechanisms for that (`id`s, that we introduced quite recently, we were thinking about them in `abbr` context, they should work).
> 
> If you don't like `AttributeElement`s (and I don't blame you for that), we need a new type of element.

Is there any new Element to overcome this?

**Comment by stasyabezruk** [comment]
The cursor doesn't work in chrome in the end of placeholder - for span, in Firefox - it works
I've used the source code from documation
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

**Comment by stasyabezruk** [comment]
on you demo this line is added every time after placeholder
![image](https://user-images.githubusercontent.com/10813820/84759260-2742c600-afcf-11ea-8d30-ef5ecf712d7c.png)

and when I use you source code, I have another behavior
![image](https://user-images.githubusercontent.com/10813820/84759851-f2833e80-afcf-11ea-908d-ae094f4b4d22.png)
