### ISSUE TITLE
Methods name syntax in git commit messages

### ISSUE THREAD

**Issue by EwelinaD** [ckeditor/ckeditor5#10503]
Please add description to git commit message convention docs (https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html) to explain how method name should be marked in git commit messages.

e.g: `MarkerCollection#has()`

**Comment by pomek** [comment]
A note that may help – when generating a changelog, I wrap classes, functions, method names, getters, etc., in backticks.

Example:

![image](https://user-images.githubusercontent.com/2270764/132696359-7ab463e8-e1b0-4360-9c0a-e05ff30eb3c3.png)

**Comment by EwelinaD** [comment]
It's about the syntax of method names. I used `class.foo()` (dot between class name and method) instead of `class#foo()` and I got the comment that we use # sign to separate class name and it's method. 

I think it's worth writing it down in docs for newcomers and update code snippets to avoid misleading

![](https://user-images.githubusercontent.com/11716070/132810432-597536f2-f417-4bb3-8d76-028e2c1eb014.png)

**Comment by pomek** [comment]
Oh. Ok, thanks for the clarification.

**Comment by EwelinaD** [comment]
Sorry, my description was misleading. I changed the issue name to be more descriptive.
