### ISSUE TITLE
The underline functionality is misbehaving

### ISSUE THREAD

**Issue by rpkoller** [ckeditor/ckeditor5#10506]
It is an issue i've stumbled across when I was testing the CKEditor 5 contrib module in Drupal 9. I've initially reported it in the according issue tracker ( https://www.drupal.org/project/ckeditor5/issues/3229172 ) but Wim Leers asked me today if I could report it upstream.

## 📝 Provide detailed reproduction steps (if any)

1. Write a sentence `One word to underline in here` and you could also create a table underneath with one cell containing the phrase `Please underline me`
2. select in both phrases the word underline and hit the underline button
3. select the word `me` in the table cell and hit the strikethrough button
4. click save 

### ✔️ Expected result

At first i would expect while being in the editor to see the selected words underlined and strikethrough. Identical to the output i would expect when i switch to the front end in Drupal. 

### ❌ Actual result

In the Editor there is no underline visible at all. The other problem is when i switch to the frontend not the selected word is underlined but instead the whole string/phrase each time. Means the selection of words underlined got extended (when i switch back into the edit mode the active underline button also indicates/confirms the extension from the single word to the whole string). in contrast the strikethrough styling displays correctly as selected

## 📃 Other details

* Browser: Tested with Firefox 91.0.2 and Safari 13.1.2
* OS: MacOS 10.13.6
* First affected CKEditor version: I am not sure at which CKEditor 5 version the Drupal module was at the time I've reported the issue in the modules issue tracker. But I've retested it with the current version today and the issue persists: 
```
  "dependencies": {
    "dllCkeditor5": "https://github.com/ckeditor/ckeditor5.git#v29.2.0"
  }
```
* Installed CKEditor plugins: In regards of used CKEditor plugins I don't know ( I don't consider myself a developer more into content strategy but tried to help testing the CKEditor 5 module for Drupal). The listed dependencies in the CKeditor 5 module package.json are: 
```
"devDependencies": {
    "@ckeditor/ckeditor5-dev-utils": "^25.2.0",
    "raw-loader": "^4.0.2",
    "terser-webpack-plugin": "^5.2.0",
    "webpack": "^5.51.1",
    "webpack-cli": "^4.4.0"
  }
```
If you need more informations please let me know. 

p.s. sorry i've copy and pasted the `other details` part i've also used in https://github.com/ckeditor/ckeditor5/issues/10505 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by wimleers** [comment]
This does not seem to be reproducible in either CKEditor 5 on https://ckeditor.com/ckeditor-5/demo/#document nor in Drupal.

Which CKEditor 5 plugins did you enable?

```
<p>One word to <u>underline</u> in here</p><figure class="table"><table><tbody><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>Please <u>underline</u> <s>me</s></td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table></figure>
```

**Comment by rpkoller** [comment]
It seems it is an issue on the Drupal end downstream interfering. Sorry for the false alarm :(
