### ISSUE TITLE
Add support for inline widgets

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1050]
For now we only tested block widgets (e.g. images, tables). We would also like to support inline widgets so features such as placeholders (as [known from CKEditor 4](https://ckeditor.com/cke4/addon/placeholder)) are possible to implement.

Known issues:

* https://github.com/ckeditor/ckeditor5/issues/1049
* TODO...

**Comment by Mgsy** [comment]
I'm closing this one as inline widgets have been [introduced in CKEditor 5 v12.0.0](https://ckeditor.com/blog/CKEditor-5-v12.0.0-with-inline-widgets-and-distraction-free-editor-released/). 

More information could be found in the [implementing an inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html) guide.
