### ISSUE TITLE
Making changes directly in the source view drops the made changes on save

### ISSUE THREAD

**Issue by rpkoller** [ckeditor/ckeditor5#10505]
It is an issue i've stumbled across when I was testing the CKEditor 5 contrib module in Drupal 9. I've initially reported it in the according issue tracker (  https://www.drupal.org/project/ckeditor5/issues/3229174 ) but Wim Leers asked me today if I could report it upstream. 

## 📝 Provide detailed reproduction steps (if any)

1. Enter text `Three bold words`
2. Select the three words and hit the bold button
3. Save
4. Open the document again
5. Click the `source` button 
6. The markup looks like: 
```
<p>
    <strong>Three bold words</strong>
</p>
```
7. Change the markup to: 
```
<p>
    <strong>Three bold</strong> words
</p>
```
or you could also change the string to `Three bold words plus two`
8. Hit directly save and dont switch back to the regular mode beforehand

### ✔️ Expected result

I would expect that `Three bold` is displayed in bold and `words` not in bold. And in case that I've extended the phrase the `plus two` would be also shown.  

### ❌ Actual result

All changes are lost if the document is saved directly in the source view. If I switch back to the regular view beforehand and save all changes are properly saved.  

## 📃 Other details

* Browser: Tested with Firefox 91.0.2 and Safari 13.1.2
* OS: MacOS 10.13.6
* First affected CKEditor version: I am not sure at which CKEditor 5 version the Drupal module was at the time I've reported the issue in the modules issue tracker. But I've retested it with the current version today and the issue persists: 
```
  "dependencies": {
    "dllCkeditor5": "https://github.com/ckeditor/ckeditor5.git#v29.2.0"
  }
```
* Installed CKEditor plugins: In regards of used CKEditor plugins I don't know ( I don't consider myself a developer more into content strategy but tried to help testing the CKEditor 5 module for Drupal). The listed dependencies in the CKeditor 5 module package.json are: 
```
"devDependencies": {
    "@ckeditor/ckeditor5-dev-utils": "^25.2.0",
    "raw-loader": "^4.0.2",
    "terser-webpack-plugin": "^5.2.0",
    "webpack": "^5.51.1",
    "webpack-cli": "^4.4.0"
  }
```
If you need more informations please let me know. 
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thanks. To rephrase: `editor.setData()` returns the content of the model, not the source editing area. It should return the latter if we're in a source mode.

**Comment by Reinmar** [comment]
Question: Should the content of the textarea be passed through the model?

*   Pros: You'll always get a valid HTML, aligned with what's allowed in the editor.
*   Cons: You may be surprised that something that you wrote in source mode wasn't saved (might've been filtered out).

CKEditor 4 returns exactly what's in the textarea, so this is possible:

![](https://user-images.githubusercontent.com/156149/135242394-db2f73f6-259f-4707-890f-7f6f039e2a07.png)

Is it a feature or a bug?

**Comment by wimleers** [comment]
~So what could we possibly be doing differently?~

> I tried to reproduce the original bug here (https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html) and it seems to work. I guess the specific scenario that @niegowski mentioned may be still broken, but it's quite a specific one.

~How can you simulate `Hit directly save and dont switch back to the regular mode beforehand` from the original bug on that page?~

Confirmed that `editor.getData()` is working, and the `<textarea>` is updated, but … the `POST` request still contains the stale data 🤯 

For now I'm concluding that this is a problem on the Drupal side, but it sure is mysterious! Thank you and _sorry_ for the false alarm! 🙈 

If you want to follow along: https://www.drupal.org/project/ckeditor5/issues/3229174#comment-14280987
