### ISSUE TITLE
How secure is the token endpoint?

### ISSUE THREAD

**Issue by gumatias** [ckeditor/ckeditor5#10504]
Hi everyone,

We're having a security concern regarding the [token endpoint](https://ckeditor.com/docs/cs/latest/guides/security/token-endpoint.html) that we're using for the Word export.

It seems like once we have our token endpoint in place, then anyone who happens to know what that endpoint is would be able to make requests, therefore retrieve the token that can be then used to generate the Word document.

Is that assumption correct? If so, what are the options that we have to implement and make it more secure, so that only CKEditor from our app gets the token (and not someone else's app making requests to our token endpoint)?

Thanks!

**Comment by Mgsy** [comment]
Hi @gumatias! Sorry for the late reply. Your question is related to the Export to Word service, which is our premium feature, while this repository is dedicated to CKEditor 5 and its open-source part of the project. It would be appreciated if you could reach us [through the support channel](https://ckeditor.com/contact/), so a dedicated support team could answer all your questions.
