### ISSUE TITLE
URLs to BrowserStack got changed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1051]
![image](https://user-images.githubusercontent.com/156149/40845009-b40a3c0a-65b5-11e8-965c-43c0123f559b.png)
![image](https://user-images.githubusercontent.com/156149/40845019-ba9cdc80-65b5-11e8-9d66-67a122bac3e3.png)

**Comment by pomek** [comment]
They changed something but their API don't match to those changes…

https://www.browserstack.com/automate/status-badges

![image](https://user-images.githubusercontent.com/2270764/40901605-3d3df77e-67d1-11e8-82c3-f25528c3c6b0.png)

> We have changed the URL structure for the undefined dashboard. Please note the new URL and add it to your bookmarks.

Where is the new URL? Did you notice anything? I cannot find it. Is everything hide here or I'm just blind? 😨

**Comment by pomek** [comment]
It can be even simpler: `s/www/automate`.

**Comment by pomek** [comment]
The final badge: [![BrowserStack Status](https://automate.browserstack.com/automate/badge.svg?badge_key=d3hvenZqQVZERFQ5d09FWXdyT0ozVXhLaVltRFRjTTUyZGpvQWNmWVhUUT0tLUZqNlJ1YWRUd0RvdEVOaEptM1B2Q0E9PQ==--c9d3dee40b9b4471ff3fb516d9ecf8d09292c7e0)](https://automate.browserstack.com/public-build/d3hvenZqQVZERFQ5d09FWXdyT0ozVXhLaVltRFRjTTUyZGpvQWNmWVhUUT0tLUZqNlJ1YWRUd0RvdEVOaEptM1B2Q0E9PQ==--c9d3dee40b9b4471ff3fb516d9ecf8d09292c7e0)
