### ISSUE TITLE
CK finder file manager for react and node express

### ISSUE THREAD

**Issue by sunialshrestha** [ckeditor/ckeditor5#10516]
## 📝 Provide a description of the new feature
I am developing a blog in MERN stack. I have succesfully integrated ckeditor 5. I have been searching to integrate file manager to upload and edit image for ckeditor. Unfornately, there are no node connector for ckfinder so that I can browse folder using node express server.
_What is the expected behavior of the proposed feature?_
Node Connector for the ckfinder
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! This repository is related to CKEditor 5, while CKFinder is an [independent project](https://github.com/ckfinder/ckfinder). If you're a licensed CKFinder user, please contact [our support channel](https://ckeditor.com/contact/), so our dedicated support team could answer all your questions.
