### ISSUE TITLE
Pasting text with newlines is either blocked, or newlines converted to "@"

### ISSUE THREAD

**Issue by laszlovl** [ckeditor/ckeditor5#10527]
## 📝 Provide detailed reproduction steps (if any)

What I'm seeing is probably related to #9836 but #10273 but the result is very different.

I'm using (the latest) Firefox and am testing with the classic editor as deployed on https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html.

Let's take the following text containing newlines:

```
br
br

p

p
```

Copying that from a basic text editor (gedit) into ckeditor results in the following content being pasted:

```
br@br@@p@@p
```

Copying it from a rich-text clipboard source such as Libreoffice or Firefox does nothing at all. No content is pasted, no errors are shown in the console. Using "paste as plaintext" (ctrl-shift-v) then results in the same behavior as above: the newlines are converted to the "@" sign instead.

### ✔️ Expected result

Newlines are preserved and converted to either BR or P tags.

### ❌ Actual result

Newlines are converted to the "@" sign or paste is broken.

## 📃 Other details

* Browser: Latest Firefox
* OS: Ubuntu
* First affected CKEditor version: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
* Installed CKEditor plugins: classic build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I suspect that @laszlovl, you have the wrong encoding on your page (you should use utf-8). That's when these kinds of issues occur.

**Comment by laszlovl** [comment]
Ouch, I figured it out: the problem was caused by my preference of `dom.events.clipboardevents = false` (to work around a couple of websites that annoyingly prevent you from copy/pasting in their forms). Resetting it to the default and everything works fine. I don't suppose you care enough for that edge case to be supported?

**Comment by niegowski** [comment]
This problem should not happen anymore in [v35.3.0](https://github.com/ckeditor/ckeditor5/releases/tag/v35.3.0).

It was most probably caused by:

[https://github.com/ckeditor/ckeditor5/blob/v35.2.1/packages/ckeditor5-typing/src/utils/injecttypingmutationshandling.js#L153-L154](https://github.com/ckeditor/ckeditor5/blob/v35.2.1/packages/ckeditor5-typing/src/utils/injecttypingmutationshandling.js#L153-L154)
