### ISSUE TITLE
The editor import statement could be simplified

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1052]
In order to use the editor, we need to write: 

```js
import InlineEditor from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';
```

We could add to `package.json` the `main` key that could point to the `src/inlineditor` file.

It could simplify the import statement to:

```js
import InlineEditor from '@ckeditor/ckeditor5-editor-inline';
```

I know, it isn't a big change but it will be unified with [the builds](https://github.com/ckeditor/ckeditor5-build-inline#quick-start) (see the part about JavaScript application).

**Comment by Reinmar** [comment]
In other words, this would be a feature mainly for us. Most of the 3rd party developers will not be aware of this or may get even confused. I'm not sure if this is worth the saved keypresses in such a case.

**Comment by ma2ciek** [comment]
IMO, the `main` field should point the distribution build (in the front-end world),  it doesn't make sense for the source files.

**Comment by Reinmar** [comment]
> IMO, the main field should point the distribution build (in the front-end world), it doesn't make sense for the source files.

Good point. So it makes limited sense in other packages than ckeditor5-build-*.

**Comment by Reinmar** [comment]
I'm closing this issue because I think we more or less agree that it won't help much.
