### ISSUE TITLE
Remove extra find and replace title header

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10525]
## 📝 Provide detailed reproduction steps (if any)

The find and replace dropdown has a title header that takes extra horizontal space is inconsistent with design language of other features (no other dropdown has it).

![](https://user-images.githubusercontent.com/5353898/133214068-58e0f662-6a06-476f-9b11-1f32ec718c5c.png)

Hinting the open option with toolbar button and the 

I don't think there's a need for such explicit hinting as:

*   There's already word "Find" in a button (and "Replace" in other).
*   The active toolbar icon is suggestive enough to tell what feature the user clicked.

### ✔️ Expected result

Removing the header causes more content to be visible and it look more like other features.

![](https://user-images.githubusercontent.com/5353898/133214216-11a54caa-8c73-48b2-8386-17270c073bec.png)

For comparison other dropdowns:

![](https://user-images.githubusercontent.com/5353898/133214305-d9c75229-67c1-4124-ac86-e749163e11b3.png)

![](https://user-images.githubusercontent.com/5353898/133214369-60cf5de1-7e4c-4252-af1d-c76b96419f99.png)

![](https://user-images.githubusercontent.com/5353898/133214726-70ef8c2d-d7d4-4eba-958d-dbbac1fde9d2.png)

### ❓ Possible solution

Just remove it.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: 29.2.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
> is inconsistent with design language of other features (no other dropdown has it).

![](https://user-images.githubusercontent.com/1099479/133386919-242be317-5bdf-4f41-a4ae-2dd30c97540a.png)

![](https://user-images.githubusercontent.com/1099479/133386939-da763357-9f2f-4199-8328-0c86b7232670.png)

![](https://user-images.githubusercontent.com/1099479/133386958-8a5331d1-1781-4942-9f89-ed8978f52f9e.png)
