### ISSUE TITLE
No syntax highlighting in "Saving data without suggestions" guide

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#10537]
## 📝 Provide a description of requested docs changes

Open [https://ckeditor.com/docs/ckeditor5/29.2.0/features/collaboration/track-changes/track-changes-data.html](https://ckeditor.com/docs/ckeditor5/29.2.0/features/collaboration/track-changes/track-changes-data.html) (permalink to latest release) - there's no syntax highlight for code listings.

![](https://user-images.githubusercontent.com/5353898/133421786-ec4a43bc-321f-4608-8e24-7adaa632ad38.png)

**Comment by FilipTokarski** [comment]
Fixed and merged in CF.
