### ISSUE TITLE
Onclick to paste into ckeditor

### ISSUE THREAD

**Issue by cletuskingdom** [ckeditor/ckeditor5#10554]
Good Day,
Please I've been trying to paste it into the creditor but it isn't working properly.

I'm using `Js onclick` method.
![image](https://user-images.githubusercontent.com/38631504/133882059-b3ca1404-f7ad-47a3-ab2b-0d229bd209c6.png)

if i'm to alert it using `alert('Dear ' + user_name + '\r\r' + message + '.')`; here's what i get:
![image](https://user-images.githubusercontent.com/38631504/133882153-4041936f-fa44-4b96-a4c7-30ab634cf5d4.png)
I'm getting it properly, `but inserting it into the field; doesn't work.`

**Comment by Mgsy** [comment]
Hi, the content in CKEditor 5 shouldn't be modified directly through the DOM. As I can see you simply try to set the specific data in the editor. CKEditor 5 implements the [`Editor#setData()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-setData) method which allows passing HTML string which will be used as content, so it should solve your issue.

**Comment by cletuskingdom** [comment]
![IMG_20210920_093415_457](https://user-images.githubusercontent.com/38631504/133975532-3ebbbc19-d2fa-4b45-a242-98a3499cbb42.jpg)

Here's what's been displayed; $.... is not a function

**Comment by Mgsy** [comment]
> Here's what's been displayed; `$.... is not a function.`  
> And here's what I wrote: `$('.editor').setData( '<p>This is editor!</p>' )`

You try to call `setData` on the native DOM element, which won't work. You have to access the editor instance. You can assign it to the `window` object, while creating the editor:

```
ClassicEditor.create( element ).then( editor => window.editor = editor );
```

Then, call `editor.setData( html )` in your application context.

**Comment by cletuskingdom** [comment]
Okay, here i am now but noticed it always creates a new instance; please how do I stop that? `The code is meant to rewrite the previous one.`
![image](https://user-images.githubusercontent.com/38631504/133988669-84479b5e-d7f1-4ef1-83c7-6b0d087b0cbb.png)

**Comment by cletuskingdom** [comment]
> Okay, here i am now but noticed it always creates a new instance; please how do I stop that? `The code is meant to rewrite the previous one.`
> ![image](https://user-images.githubusercontent.com/38631504/133988669-84479b5e-d7f1-4ef1-83c7-6b0d087b0cbb.png)

Please i didn't get your response here.

**Comment by Mgsy** [comment]
@cletuskingdom, in your snippet you create a new instance after clicking on the button. If you'd like to change the content on click, you have to initialize the editor first and expose the editor instance, as I mentioned above, then use only `editor.setData()` after clicking on the button.

**Comment by cletuskingdom** [comment]
> @cletuskingdom, in your snippet you create a new instance after clicking on the button. If you'd like to change the content on click, you have to initialize the editor first and expose the editor instance, as I mentioned above, then use only `editor.setData()` after clicking on the button.

Please help me wth the snippet, i tried this
 `CKEDITOR.setData('Dear ' + user_name + '\n\n' + message );` but not working.

Thank you so much for your time.
