### ISSUE TITLE
Spike for generating proper docs for overridden methods

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10560]
## Provide a description of the task

A spike for https://github.com/ckeditor/ckeditor5/issues/8691.

The goal: Understand what is returned by JSDoc + how to parse it.

Scope:
* An example class: `class Foo { /* ... */ }`
* Another class: `class Bar extends Foo { /* ... */ }`
* Override the same method: `Bar#example()` overrides `Foo#example()`
* Generate JSDoc using our tooling
* Understand the output produced by JSDoc and how to detect overrides

**Comment by ma2ciek** [comment]
The question is if we remove or do not remove the "unwanted" symbols from the JSDoc output.

**Comment by przemyslaw-zan** [comment]
There does not seem to be any unambiguous way of pinpointing which doclet is missing it's override based on the doclet alone. The faulty doclet does not have `override`, `inherited` or `mixed` values. Combining all values of all `descendants` fields, and then comparing `memberof` value to check if it is a descendant of some other function, and then further filtering for missing `overridde` `inherited` or `mixed` does not yield specifically the faulty doclets either. Final idea was to modify `getmissingdocletdata.js` so that `docletsOfSameMember` would have a new custom property at the end, that we could use to find the one we want, but that does not yield what we want either.

Faulty `DataController#set()` doclet for reference.

```json
"comment": "/**\n\t * Sets input data parsed by the {@link module:engine/controller/datacontroller~DataController#processor data  processor} and\n\t * converted by the {@link module:engine/controller/datacontroller~DataController#upcastDispatcher view-to-model  converters}.\n\t * This method can be used any time to replace existing editor data by the new one without clearing the\n\t * {@link module:engine/model/document~Document#history document history}.\n\t *\n\t * This method also creates a batch with all the changes applied. If all you need is to parse data, use\n\t * the {@link module:engine/controller/datacontroller~DataController#parse} method.\n\t *\n\t * When data is passed as a string it is set on a default `main` root:\n\t *\n\t *\t\tdataController.set( '<p>Foo</p>' ); // Sets data on the `main` root.\n\t *\n\t * To set data on a different root or multiple roots at once, object containing `rootName` - `data` pairs should be passed:\n\t *\n\t *\t\tdataController.set( { main: '<p>Foo</p>', title: '<h1>Bar</h1>' } ); // Sets data on the `main` and `title` roots.\n\t *\n\t * To set the data with preserved undo stacks and set the current change to this stack, use the `{ batchType: 'default' }` option.\n\t *\n\t *\t\tdataController.set( '<p>Foo</p>', { batchType: 'default' } ); // Sets data as a new change.\n\t *\n\t * @fires set\n\t * @param {String|Object.<String,String>} data Input data as a string or an object containing `rootName` - `data`\n\t * pairs to set data on multiple roots at once.\n\t * @param {Object} [options={}] Options for setting data.\n\t * @param {'default'|'transparent'} [options.batchType='default'] The batch type that will be used to create a batch for the changes.\n\t * When set to `default`, the undo and redo stacks will be preserved. Note that when not set, the undo feature (when present) will\n\t * override it to `transparent` and all undo steps will be lost.\n\t */",
"meta": {
	"range": [
		15632,
		16955
	],
	"filename": "datacontroller.js",
	"lineno": 365,
	"columnno": 1,
	"path": "D:\\Repo\\ckeditor5\\packages\\ckeditor5-engine\\src\\controller",
	"code": {
		"id": "astnode100012219",
		"name": "DataController#set",
		"type": "MethodDefinition",
		"paramnames": [
			"data",
			"options"
		]
	},
	"vars": {
		"": null
	}
},
"description": "<p>Sets input data parsed by the {@link module:engine/controller/datacontroller~DataController#processor data  processor} and\nconverted by the {@link module:engine/controller/datacontroller~DataController#upcastDispatcher view-to-model  converters}.\nThis method can be used any time to replace existing editor data by the new one without clearing the\n{@link module:engine/model/document~Document#history document history}.</p>\n<p>This method also creates a batch with all the changes applied. If all you need is to parse data, use\nthe {@link module:engine/controller/datacontroller~DataController#parse} method.</p>\n<p>When data is passed as a string it is set on a default <code>main</code> root:</p>\n<pre><code>dataController.set( '&lt;p&gt;Foo&lt;/p&gt;' ); // Sets data on the `main` root.\n</code></pre>\n<p>To set data on a different root or multiple roots at once, object containing <code>rootName</code> - <code>data</code> pairs should be passed:</p>\n<pre><code>dataController.set( { main: '&lt;p&gt;Foo&lt;/p&gt;', title: '&lt;h1&gt;Bar&lt;/h1&gt;' } ); // Sets data on the `main` and `title` roots.\n</code></pre>\n<p>To set the data with preserved undo stacks and set the current change to this stack, use the <code>{ batchType: 'default' }</code> option.</p>\n<pre><code>dataController.set( '&lt;p&gt;Foo&lt;/p&gt;', { batchType: 'default' } ); // Sets data as a new change.</code></pre>",
"fires": [
	"module:engine/controller/datacontroller~DataController#event:set"
],
"params": [
	{
		"type": {
			"names": [
				"String",
				"Object.<String, String>"
			]
		},
		"description": "<p>Input data as a string or an object containing <code>rootName</code> - <code>data</code>\npairs to set data on multiple roots at once.</p>",
		"name": "data"
	},
	{
		"type": {
			"names": [
				"Object"
			]
		},
		"optional": true,
		"defaultvalue": "{}",
		"description": "<p>Options for setting data.</p>",
		"name": "options"
	},
	{
		"type": {
			"names": [
				"'default'",
				"'transparent'"
			]
		},
		"optional": true,
		"defaultvalue": "'default'",
		"description": "<p>The batch type that will be used to create a batch for the changes.\nWhen set to <code>default</code>, the undo and redo stacks will be preserved. Note that when not set, the undo feature (when present) will\noverride it to <code>transparent</code> and all undo steps will be lost.</p>",
		"name": "options.batchType"
	}
],
"name": "set",
"longname": "module:engine/controller/datacontroller~DataController#set",
"kind": "function",
"memberof": "module:engine/controller/datacontroller~DataController",
"scope": "instance"
```

**Comment by pomek** [comment]
Over the last few days, together with @przemyslaw-zan, we tried to implement a new validator that would detect missing `@override` annotation when an inherited method overrides a parent method.

Unfortunately, due to lack of knowledge and missing unit tests for jsdoc plugins we created, it's hard to change anything as we don't know whether the generated docs are correct.

However, we tried and implemented something that looks for the missing `@override` annotation, as I mentioned.

Here is a working prototype that returns 182 errors – https://github.com/ckeditor/ckeditor5-dev/compare/ck/10560. If you want to use it, please, do not forget about linking the `@ckeditor/ckeditor5-dev-docs` and `@ckeditor/jsdoc-plugins` packages in the CKEditor 5 project.

<details>
<summary>182 invalid docs</summary>

* Missing `@override` annotation for the `module:alignment/alignmentcommand~AlignmentCommand#value` docs.
* Missing `@override` annotation for the `module:alignment/alignmentcommand~AlignmentCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:basic-styles/attributecommand~AttributeCommand#value` docs.
* Missing `@override` annotation for the `module:basic-styles/attributecommand~AttributeCommand#constructor` docs.
* Missing `@override` annotation for the `module:basic-styles/attributecommand~AttributeCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:block-quote/blockquotecommand~BlockQuoteCommand#value` docs.
* Missing `@override` annotation for the `module:block-quote/blockquotecommand~BlockQuoteCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:code-block/codeblockcommand~CodeBlockCommand#value` docs.
* Missing `@override` annotation for the `module:core/editingkeystrokehandler~EditingKeystrokeHandler#constructor` docs.
* Missing `@override` annotation for the `module:editor-balloon/ballooneditor~BalloonEditor#constructor` docs.
* Missing `@override` annotation for the `module:editor-balloon/ballooneditorui~BalloonEditorUI#constructor` docs.
* Missing `@override` annotation for the `module:editor-balloon/ballooneditoruiview~BalloonEditorUIView#constructor` docs.
* Missing `@override` annotation for the `module:editor-classic/classiceditor~ClassicEditor#constructor` docs.
* Missing `@override` annotation for the `module:editor-classic/classiceditorui~ClassicEditorUI#constructor` docs.
* Missing `@override` annotation for the `module:editor-classic/classiceditoruiview~ClassicEditorUIView#constructor` docs.
* Missing `@override` annotation for the `module:editor-decoupled/decouplededitor~DecoupledEditor#constructor` docs.
* Missing `@override` annotation for the `module:editor-decoupled/decouplededitorui~DecoupledEditorUI#constructor` docs.
* Missing `@override` annotation for the `module:editor-decoupled/decouplededitoruiview~DecoupledEditorUIView#constructor` docs.
* Missing `@override` annotation for the `module:editor-inline/inlineeditor~InlineEditor#constructor` docs.
* Missing `@override` annotation for the `module:editor-inline/inlineeditorui~InlineEditorUI#constructor` docs.
* Missing `@override` annotation for the `module:editor-inline/inlineeditoruiview~InlineEditorUIView#constructor` docs.
* Missing `@override` annotation for the `module:find-and-replace/findcommand~FindCommand#constructor` docs.
* Missing `@override` annotation for the `module:find-and-replace/findnextcommand~FindNextCommand#constructor` docs.
* Missing `@override` annotation for the `module:find-and-replace/replacecommand~ReplaceCommand#constructor` docs.
* Missing `@override` annotation for the `module:font/fontcommand~FontCommand#constructor` docs.
* Missing `@override` annotation for the `module:font/fontcommand~FontCommand#value` docs.
* Missing `@override` annotation for the `module:font/fontcommand~FontCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:heading/heading~HeadingOption#model` docs.
* Missing `@override` annotation for the `module:heading/heading~HeadingOption#view` docs.
* Missing `@override` annotation for the `module:heading/headingcommand~HeadingCommand#constructor` docs.
* Missing `@override` annotation for the `module:heading/headingcommand~HeadingCommand#value` docs.
* Missing `@override` annotation for the `module:heading/headingcommand~HeadingCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:highlight/highlightcommand~HighlightCommand#value` docs.
* Missing `@override` annotation for the `module:highlight/highlightcommand~HighlightCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:indent/indentblockcommand~IndentBlockCommand#constructor` docs.
* Missing `@override` annotation for the `module:language/textpartlanguagecommand~TextPartLanguageCommand#value` docs.
* Missing `@override` annotation for the `module:language/textpartlanguagecommand~TextPartLanguageCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:link/linkcommand~LinkCommand#value` docs.
* Missing `@override` annotation for the `module:link/linkcommand~LinkCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:list/checktodolistcommand~CheckTodoListCommand#isEnabled` docs.
* Missing `@override` annotation for the `module:list/checktodolistcommand~CheckTodoListCommand#value` docs.
* Missing `@override` annotation for the `module:list/checktodolistcommand~CheckTodoListCommand#event:change:isEnabled` docs.
* Missing `@override` annotation for the `module:list/checktodolistcommand~CheckTodoListCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:list/indentcommand~IndentCommand#constructor` docs.
* Missing `@override` annotation for the `module:list/listcommand~ListCommand#value` docs.
* Missing `@override` annotation for the `module:list/listcommand~ListCommand#constructor` docs.
* Missing `@override` annotation for the `module:list/listcommand~ListCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:list/liststylecommand~ListStyleCommand#constructor` docs.
* Missing `@override` annotation for the `module:minimap/minimapiframeview~MinimapIframeView#constructor` docs.
* Missing `@override` annotation for the `module:minimap/minimapview~MinimapView#constructor` docs.
* Missing `@override` annotation for the `module:paragraph/paragraphcommand~ParagraphCommand#value` docs.
* Missing `@override` annotation for the `module:paragraph/paragraphcommand~ParagraphCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:restricted-editing/restrictededitingmodenavigationcommand~RestrictedEditingModeNavigationCommand#constructor` docs.
* Missing `@override` annotation for the `module:typing/deletecommand~DeleteCommand#constructor` docs.
* Missing `@override` annotation for the `module:typing/inputcommand~InputCommand#constructor` docs.
* Missing `@override` annotation for the `module:ui/viewcollection~ViewCollection#constructor` docs.
* Missing `@override` annotation for the `module:ui/viewcollection~ViewCollection#delegate` docs.
* Missing `@override` annotation for the `module:ui/viewcollection~ViewCollection#delegate` docs.
* Missing `@override` annotation for the `module:watchdog/contextwatchdog~ContextWatchdog#constructor` docs.
* Missing `@override` annotation for the `module:watchdog/editorwatchdog~EditorWatchdog#constructor` docs.
* Missing `@override` annotation for the `module:engine/controller/datacontroller~DataController#set` docs.
* Missing `@override` annotation for the `module:engine/model/element~Element#is` docs.
* Missing `@override` annotation for the `module:engine/model/liveposition~LivePosition#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/liveposition~LivePosition._createAfter` docs.
* Missing `@override` annotation for the `module:engine/model/liveposition~LivePosition._createBefore` docs.
* Missing `@override` annotation for the `module:engine/model/liveposition~LivePosition._createAt` docs.
* Missing `@override` annotation for the `module:engine/model/rootelement~RootElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/text~Text#is` docs.
* Missing `@override` annotation for the `module:engine/view/attributeelement~AttributeElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/containerelement~ContainerElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/editableelement~EditableElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/element~Element#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/element~Element#is` docs.
* Missing `@override` annotation for the `module:engine/view/element~Element#isSimilar` docs.
* Missing `@override` annotation for the `module:engine/view/element~Element#_clone` docs.
* Missing `@override` annotation for the `module:engine/view/emptyelement~EmptyElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/rawelement~RawElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/rooteditableelement~RootEditableElement#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/text~Text#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/text~Text#is` docs.
* Missing `@override` annotation for the `module:engine/view/text~Text#isSimilar` docs.
* Missing `@override` annotation for the `module:engine/view/text~Text#_clone` docs.
* Missing `@override` annotation for the `module:engine/view/uielement~UIElement#constructor` docs.
* Missing `@override` annotation for the `module:find-and-replace/ui/findandreplaceformview~FindAndReplaceFormView#constructor` docs.
* Missing `@override` annotation for the `module:font/ui/colortableview~ColorTableView#constructor` docs.
* Missing `@override` annotation for the `module:font/ui/colorui~ColorUI#constructor` docs.
* Missing `@override` annotation for the `module:image/imagestyle/imagestylecommand~ImageStyleCommand#constructor` docs.
* Missing `@override` annotation for the `module:image/imagetextalternative/imagetextalternativecommand~ImageTextAlternativeCommand#value` docs.
* Missing `@override` annotation for the `module:image/imagetextalternative/imagetextalternativecommand~ImageTextAlternativeCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:link/ui/linkformview~LinkFormView#constructor` docs.
* Missing `@override` annotation for the `module:media-embed/ui/mediaformview~MediaFormView#constructor` docs.
* Missing `@override` annotation for the `module:mention/ui/domwrapperview~DomWrapperView#constructor` docs.
* Missing `@override` annotation for the `module:special-characters/ui/charactergridview~CharacterGridView#constructor` docs.
* Missing `@override` annotation for the `module:special-characters/ui/specialcharactersnavigationview~SpecialCharactersNavigationView#constructor` docs.
* Missing `@override` annotation for the `module:ui/colorgrid/colorgrid~ColorGridView#constructor` docs.
* Missing `@override` annotation for the `module:ui/dropdown/dropdownview~DropdownView#constructor` docs.
* Missing `@override` annotation for the `module:ui/editableui/editableuiview~EditableUIView#constructor` docs.
* Missing `@override` annotation for the `module:ui/editorui/bodycollection~BodyCollection#constructor` docs.
* Missing `@override` annotation for the `module:ui/editorui/editoruiview~EditorUIView#constructor` docs.
* Missing `@override` annotation for the `module:ui/formheader/formheaderview~FormHeaderView#constructor` docs.
* Missing `@override` annotation for the `module:ui/iframe/iframeview~IframeView#constructor` docs.
* Missing `@override` annotation for the `module:ui/labeledfield/labeledfieldview~LabeledFieldView#constructor` docs.
* Missing `@override` annotation for the `module:ui/labeledinput/labeledinputview~LabeledInputView#constructor` docs.
* Missing `@override` annotation for the `module:ui/toolbar/toolbarview~ToolbarView#constructor` docs.
* Missing `@override` annotation for the `module:utils/dom/emittermixin~ProxyEmitter#_addEventListener` docs.
* Missing `@override` annotation for the `module:utils/dom/emittermixin~ProxyEmitter#_removeEventListener` docs.
* Missing `@override` annotation for the `module:table/commands/insertcolumncommand~InsertColumnCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/commands/insertrowcommand~InsertRowCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/commands/mergecellcommand~MergeCellCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/commands/setheadercolumncommand~SetHeaderColumnCommand#value` docs.
* Missing `@override` annotation for the `module:table/commands/setheadercolumncommand~SetHeaderColumnCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:table/commands/setheaderrowcommand~SetHeaderRowCommand#value` docs.
* Missing `@override` annotation for the `module:table/commands/setheaderrowcommand~SetHeaderRowCommand#event:change:value` docs.
* Missing `@override` annotation for the `module:table/commands/splitcellcommand~SplitCellCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/ui/colorinputview~ColorInputView#constructor` docs.
* Missing `@override` annotation for the `module:table/ui/formrowview~FormRowView#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/attributeoperation~AttributeOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/attributeoperation~AttributeOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/attributeoperation~AttributeOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/attributeoperation~AttributeOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/detachoperation~DetachOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/insertoperation~InsertOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/insertoperation~InsertOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/insertoperation~InsertOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/insertoperation~InsertOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/markeroperation~MarkerOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/markeroperation~MarkerOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/markeroperation~MarkerOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/markeroperation~MarkerOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/mergeoperation~MergeOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/mergeoperation~MergeOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/mergeoperation~MergeOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/mergeoperation~MergeOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/moveoperation~MoveOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/moveoperation~MoveOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/moveoperation~MoveOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/moveoperation~MoveOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/nooperation~NoOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/nooperation~NoOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/renameoperation~RenameOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/renameoperation~RenameOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/renameoperation~RenameOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/renameoperation~RenameOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/rootattributeoperation~RootAttributeOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/rootattributeoperation~RootAttributeOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/rootattributeoperation~RootAttributeOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/rootattributeoperation~RootAttributeOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/model/operation/splitoperation~SplitOperation#constructor` docs.
* Missing `@override` annotation for the `module:engine/model/operation/splitoperation~SplitOperation#clone` docs.
* Missing `@override` annotation for the `module:engine/model/operation/splitoperation~SplitOperation#getReversed` docs.
* Missing `@override` annotation for the `module:engine/model/operation/splitoperation~SplitOperation.fromJSON` docs.
* Missing `@override` annotation for the `module:engine/view/observer/bubblingeventinfo~BubblingEventInfo#constructor` docs.
* Missing `@override` annotation for the `module:engine/view/observer/fakeselectionobserver~FakeSelectionObserver#constructor` docs.
* Missing `@override` annotation for the `module:image/imageinsert/ui/imageinsertformrowview~ImageUploadFormRowView#constructor` docs.
* Missing `@override` annotation for the `module:image/imageinsert/ui/imageinsertpanelview~ImageInsertPanelView#constructor` docs.
* Missing `@override` annotation for the `module:ui/editableui/inline/inlineeditableuiview~InlineEditableUIView#constructor` docs.
* Missing `@override` annotation for the `module:ui/editorui/boxed/boxededitoruiview~BoxedEditorUIView#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellbackgroundcolorcommand~TableCellBackgroundColorCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellbordercolorcommand~TableCellBorderColorCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellborderstylecommand~TableCellBorderStyleCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellborderwidthcommand~TableCellBorderWidthCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellheightcommand~TableCellHeightCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellhorizontalalignmentcommand~TableCellHorizontalAlignmentCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellpaddingcommand~TableCellPaddingCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellpropertycommand~TableCellPropertyCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellverticalalignmentcommand~TableCellVerticalAlignmentCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/commands/tablecellwidthcommand~TableCellWidthCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tablealignmentcommand~TableAlignmentCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tablebackgroundcolorcommand~TableBackgroundColorCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tablebordercolorcommand~TableBorderColorCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tableborderstylecommand~TableBorderStyleCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tableborderwidthcommand~TableBorderWidthCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tableheightcommand~TableHeightCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tablepropertycommand~TablePropertyCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/commands/tablewidthcommand~TableWidthCommand#constructor` docs.
* Missing `@override` annotation for the `module:table/tableproperties/ui/tablepropertiesview~TablePropertiesView#constructor` docs.
* Missing `@override` annotation for the `module:table/tablecellproperties/ui/tablecellpropertiesview~TableCellPropertiesView#constructor` docs.
* Missing `@override` annotation for the `module:comments/commentsonly~CommentsOnly#isEnabled` docs.
* Missing `@override` annotation for the `module:comments/commentsonly~CommentsOnly#event:change:isEnabled` docs.
* Missing `@override` annotation for the `module:track-changes/ui/view/basesuggestionthreadview~BaseSuggestionThreadView#constructor` docs.
* Missing `@override` annotation for the `module:comments/comments/ui/view/basecommentthreadview~BaseCommentThreadView#constructor` docs.
* Missing `@override` annotation for the `module:comments/comments/ui/view/basecommentview~BaseCommentView#constructor` docs.
</details>

I checked a few random cases, and all of them were reported successfully. However, we don't see the `Command#execute()` case here. Because, the base `Command` class defines the `#execute()` method, all `*Command#execute()` doclets contain the `#inherited=true` property, which the validator filters out at the beginning.

Hence, I'd suggest changing `Command#execute` to an abstract method or moving it to an interface (like we do with `Plugin#init`.

https://github.com/ckeditor/ckeditor5/blob/89b5315550e1dbcf26bc9cb4678931670b9bb52c/packages/ckeditor5-core/src/command.js#L216-L232

The `#inherited=true` flag is implemented by one of our plugins, and without having it covered by tests, we don't want to touch it, as we aren't sure what we break.
