### ISSUE TITLE
Research inline fillers staying longer in text nodes to reduce glitches when creating selection in Chrome using mouse drag

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10563]
## Provide a description of the task

A follow-up of the #10430 research issue to unblock #10230 (a twin of #10562).

Scope of the research as in [https://github.com/ckeditor/ckeditor5/issues/10430#issuecomment-922986492](https://github.com/ckeditor/ckeditor5/issues/10430#issuecomment-922986492:):

*   Play with `_needsInlineFillerAtSelection()` and `_isSelectionInInlineFiller()` (and other helpers) to make the inline filler stay longer in place.
    *   Assumption: If the inline filler stays longer, the **DOM** selection in Chrome will **less likely** collapse to the focus position and break the flow of the user creating a selection using the mouse when the block starts with a link/mention/marker.
    *   Make sure the fillers are correctly removed when no longer necessary.
*   Assess the risks related to more permanent inline fillers.

**Comment by Reinmar** [comment]
It will be done as part of #10562. The easiest approach seems to be to avoid removing the filler when the selection is in progress. It should have the smallest impact.
