### ISSUE TITLE
SourceEditing Plugins - how to config withText: false

### ISSUE THREAD

**Issue by huyit88** [ckeditor/ckeditor5#10573]
Hello team,
I want to config toolbar button with no text.
![image](https://user-images.githubusercontent.com/5257960/134287343-0103ea5b-f950-46cc-9715-357510286bc4.png)

like other toolbar button. 
buttonView.set( {
				label: t( 'Source' ),
				icon: sourceEditingIcon,
				tooltip: true,
				withText: true,
				class: 'ck-source-editing-button'
			} );

change: withText: false

How can i do it?
Or any hack can apply as workaround?
PS: I build ckeditor online.

Thanks!

**Comment by shahzebgit** [comment]
I assume you don't want the text `Source` beside the icon, so instead of writing `withText: false` just remove the line and you won't have the text in toolbar.
if you want the text `Source` name again just add the line `withText: true`

Check out the [docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/ui-library.html#templates) for more examples

**Comment by huyit88** [comment]
Hello @shahzebgit ,
I use the online builder.
https://ckeditor.com/ckeditor-5/online-builder/
In my code, i only included the source ckeditor.js.
Do we have any functions that i can do it without interfering the source code.
onCkEditorReady(editor) {
   // few methods can change default config of plugins?    
}

Thanks!

**Comment by dawidurbanski** [comment]
@huyit88 you can set this in runtime.

Check for `editor.ui.view.toolbar.items` property. Find the one you want to update, and just do it.

For example ( I replaced editor config with `{ ... }`):

```js
ClassicEditor
	.create( document.querySelector( '.editor' ), { ... } )
	.then( editor => {
		window.editor = editor;

		const button = editor.ui.view.toolbar.items.find( item => item.class === "ck-source-editing-button" );

		if ( button ) {
			button.withText = false;
		}
	} );
```

**Comment by huyit88** [comment]
@dawidurbanski :
Thanks. It work like a charm. 
Have a nice day
