### ISSUE TITLE
Writing on the marker position on the highlight boundary inside a link produces unexpected result

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#1057]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`v10.0.1` (tested on `dev` version so more like latest `master`).

## 📋 Steps to reproduce

**See gif below**:

![link-highlight-marker](https://user-images.githubusercontent.com/1061942/41239548-cf107826-6d98-11e8-9eaf-19282b81b7fa.gif)

**Steps**:

1. Having HTML like

```
<p>F<mark class="marker-yellow">oo </mark><a href=""><mark class="marker-yellow">Bar</mark> Baz</a> some additional text...</p>
```
2. Put the selection in 2nd client to the end boundary of the highlight inside a link (so the marker will be placed there in 1st client).
1. Put the selection (1st client) in the marker position (highlight boundary).
1. Type something.

## ✅ Expected result

Character is typed.

## ❎ Actual result

Marker and highlight element moves/jumps somewhere after typing. 

## 📃 Other details that might be useful

Tested on Chrome `66.0.3359.181`.

**Comment by Mgsy** [comment]
This bug doesn't occur anymore.
