### ISSUE TITLE
Add image resize to all editor builds

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10590]
## 📝 Provide a description of the improvement

Currently ImageResize plugin is available by default only in decoupled document build. Other builds have a possibility of creating an inline image, but without ability to resize it, it kinda defeats the purpose of having an inline image in the first place.
You can check it on [examples docs page](https://ckeditor.com/docs/ckeditor5/latest/examples/index.html).
  
My suggestion is to add ImageResize to all editor builds.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This would mean a very serious breaking change for integrators using classic or inline who create CSS class-driven semantic content. There’s no way to opt-out for them unless they build editor from source, which contradicts the idea of a ready-to-use build.

**Comment by Reinmar** [comment]
This is the kind of problem that makes me think that we shouldn't have any builds because whatever we'd do will be wrong. I'd seriously do our "reasonable" best to avoid talking about builds and promoting them as they are so limited. You can always miss this or that.
