### ISSUE TITLE
The SVGO config used by "yarn clean-up-svg-icons" is deprecated

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10601]
## Provide a description of the task

This is what you get these days in the command output

```
"extendDefaultPlugins" utility is deprecated.
Use "preset-default" plugin with overrides instead.
For example:
{
  name: 'preset-default',
  params: {
    overrides: {
      // customize plugin options
      convertShapeToPath: {
        convertArcs: true
      },
      // disable plugins
      convertPathData: false
    }
  }
}
```

**Comment by pomek** [comment]
I guess we need more details. At least, the package version.

```
# release (c664719)

$ yarn run clean-up-svg-icons
yarn run v1.22.5
$ sh ./scripts/clean-up-svg-icons.sh
✨  Done in 0.10s.


$ ./node_modules/.bin/svgo --version
2.6.1
```

**Comment by oleq** [comment]
When you run `yarn run clean-up-svg-icons` without args it does not use the config :) [https://github.com/ckeditor/ckeditor5/blob/596f9f63d4be8149083cf8affedcdcc723f9e074/scripts/clean-up-svg-icons.sh#L26-L26](https://github.com/ckeditor/ckeditor5/blob/596f9f63d4be8149083cf8affedcdcc723f9e074/scripts/clean-up-svg-icons.sh#L26-L26)

```
 oleq@MBP16  ~/.../5/ckeditor5  ↓  release (a7d90db)  M1  yarn clean-up-svg-icons external/ckeditor5-internal/packages/ckeditor5-export-pdf/theme/icons/exportpdf.svg
yarn run v1.22.10
$ sh ./scripts/clean-up-svg-icons.sh external/ckeditor5-internal/packages/ckeditor5-export-pdf/theme/icons/exportpdf.svg

"extendDefaultPlugins" utility is deprecated.
Use "preset-default" plugin with overrides instead.
For example:
{
  name: 'preset-default',
  params: {
    overrides: {
      // customize plugin options
      convertShapeToPath: {
        convertArcs: true
      },
      // disable plugins
      convertPathData: false
    }
  }
}


exportpdf.svg:
Done in 18 ms!
0.907 KiB - 0% = 0.907 KiB
✨  Done in 0.40s.
```

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/134886285-6581220e-79eb-4078-bd6d-bd741160bba0.png)

**Comment by pomek** [comment]
Do I do anything wrong? :D

**Comment by oleq** [comment]
You got to specify which icon you want to clean up :D

**Comment by pomek** [comment]
Ok, got it.

![image](https://user-images.githubusercontent.com/2270764/134899052-659aebdc-2651-47f9-bd35-e91505059856.png)

This command is too fast, and I didn't notice the warning. Now I understand :D
