### ISSUE TITLE
image insert problem

### ISSUE THREAD

**Issue by chujian521** [ckeditor/ckeditor5#10622]
## 📝 Provide detailed reproduction steps (if any)

editor.model.change( writer => {
    const image = writer.createElement( 'image', { src: '...' } );
    editor.model.insertContent( image );
} );

### ✔️ Expected result

Insert image in editor

### ❌ Actual result

No images are inserted

## 📃 Other details

* First affected CKEditor version: 30.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dexelirsas** [comment]
Additional details as I experiment the same bug:

- Tested with default build (inline editor)
- Tested with a custom build, generated today

**Comment by chujian521** [comment]
@dexelirsas You're welcome ~ , more detail :https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageutils-ImageUtils.html#function-insertImage
