### ISSUE TITLE
[Safari] Broken selection render when widget is last element

### ISSUE THREAD

**Issue by EwelinaD** [ckeditor/ckeditor5#10626]
## 📝 Provide detailed reproduction steps (if any)

1.  Add widget (image or HTML embed) as last element in editor.
2.  Press `cmd+A` to select whole content.
3.  For first time there will be selection blink on elements, second time only widgets will be selected.
4.  Press `backspace` - whole content is removed (as expected).

### ✔️ Expected result

Whole content should be selected (like in Chrome)

![](https://user-images.githubusercontent.com/11716070/135578266-4f763daf-082b-42f2-a7f3-9e1e739f11ae.png)

### ❌ Actual result

Only widgets are selected

![](https://user-images.githubusercontent.com/11716070/135578301-baf254c8-1b20-4afc-9d30-cc6f7fdd76af.png)

## 📃 Other details

*   Browser: Safari
*   OS: MacOS Big Sur
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Related/DUP of https://github.com/ckeditor/ckeditor5/issues/7349?

**Comment by EwelinaD** [comment]
You're probably right. Thanks @FilipTokarski!
