### ISSUE TITLE
'svg' files not working with Base64UploadAdapter

### ISSUE THREAD

**Issue by blairjanis** [ckeditor/ckeditor5#10624]
## 📝 Provide detailed reproduction steps (if any)

1. Follow instructions at [https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/base64-upload-adapter.html](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/base64-upload-adapter.html) to use the `Base64UploadAdapter`
2. Add the following to the configuration:
```
		image: {
			upload:  { types: [ 'svg', 'png']
		}
```

The resource listed above says:

> Use the image.upload.types configuration option to define the allowed image MIME types that can be uploaded to CKEditor 5.  By default, users are allowed to upload jpeg, png, gif, bmp, webp and tiff files, but you can customize this behavior to accept, for example, SVG files.

Which is what I'm trying to do.

3. Run the editor and click the upload image button

### ✔️ Expected result

_What is the expected result of the above steps?_

In the file selector dialog, I expected that in addition to 'png' file types I would see 'svg' file types as selectable.

### ❌ Actual result

_What is the actual result of the above steps?_

'svg' file types are not selectable ... additionally, if I modify the file selector dialog to be able to select an svg file, nothing happens in the editor when I select an svg.  No image.

## 📃 Other details

* Browser: Chrome (latest)
* OS: Mac OS (latest)
* Installed CKEditor plugins: 29.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It works when you use `svg+xml` option type, instead of just `svg`. I can see now that it is not clearly explained in the docs, we will fix this soon.

**Comment by FilipTokarski** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/10627.
