### ISSUE TITLE
Mention `ckeditor5-package-generator` in the "Quick start" guide

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10641]
## 📝 Provide a description of requested docs changes

It is extracted from: https://github.com/ckeditor/ckeditor5-package-generator/issues/20.

Let's add an `<info-box>` below the "[How to install the framework?](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/quick-start.html#how-to-install-the-framework)" section with the following content:

<pre><code>We're currently working on a [package generator](https://www.npmjs.com/package/ckeditor5-package-generator) that will automate the steps described in this guide. If you wish, you can test it already. Remember to share your feedback with us.
		    
```bash
npx create-ckeditor5-plugin <packageName>
```</code></pre>

☝️ However, we published [the beta release](https://github.com/ckeditor/ckeditor5-package-generator/releases/tag/v1.0.0-beta.1), so we could rewrite it a little bit.

**Comment by godai78** [comment]
Merged in #10641
