### ISSUE TITLE
New API for #refreshItem() and #refreshMarker()

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#10659]
## 📝 Provide a description of the improvement

When researching [#9901](https://github.com/ckeditor/ckeditor5/issues/9901) we concluded that it would be good to have a dedicated method in the API to refresh, or rather reconvert, a marker.

At the moment, the way to do it is to call `writer.updateMarker( markerOrMarkerName )`. We don't like that for three reasons:

1.  The method name suggest that something about the marker should change. It is hard to discover that this method should be used if we want to reconvert a marker.
2.  Reconverting a marker is not really about changing something in the model, while writer's responsibility is to change the model. (Re)conversion is a different process, that is managed by a different entity.
3.  We already have similar case with `Differ#refreshItem()`. It also reconverts, but in that case, a model item.

When we discussed this, we concluded that:

1.  We want to have a dedicated method to reconvert a marker.
2.  Both methods should be most probably called `reconvertMarker()` and `reconvertItem()`.
3.  Neither `Differ` nor `model.Writer` are good place for them.
4.  We also thought about adding this API on `EditingController` or `Conversion` classes.

**Comment by Reinmar** [comment]
Merged to \`[ck/10294/reconversion](https://github.com/ckeditor/ckeditor5/tree/ck/10294/reconversion)\`
