### ISSUE TITLE
Connect sidebar to div using React ref - Error: ﻿﻿sidebar-attachtocontainer-missing-container

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#10660]
## Provide a description of the task
Adding  document.querySelector( '#sidebar' ) is ok when we use only one editor on page. 
IMO refs are better performance solution, so is it possible to attach container using react ref?
eg.
config: {...
  sidebar: {
    container: this.sidebarRef.current
  },
}
...
<div ref={this.sidebarRef} ></div>

Or if I understand I should set container using https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-Sidebar.html#function-setContainer inside onReady method?
## 📃 Other details

* Browser: Google Chrome
* OS: Windows 
* CKEditor version: 30
* Installed CKEditor plugins: …
    "@ckeditor/ckeditor5-alignment": "^30.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^30.0.0",
    "@ckeditor/ckeditor5-comments": "^30.0.0",
    "@ckeditor/ckeditor5-core": "^30.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^30.0.0",
    "@ckeditor/ckeditor5-essentials": "^30.0.0",
    "@ckeditor/ckeditor5-find-and-replace": "30.0.0",
    "@ckeditor/ckeditor5-font": "^30.0.0",
    "@ckeditor/ckeditor5-highlight": "^30.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^30.0.0",
    "@ckeditor/ckeditor5-html-support": "^30.0.0",
    "@ckeditor/ckeditor5-image": "^30.0.0",
    "@ckeditor/ckeditor5-indent": "^30.0.0",
    "@ckeditor/ckeditor5-link": "^30.0.0",
    "@ckeditor/ckeditor5-list": "^30.0.0",
    "@ckeditor/ckeditor5-page-break": "^30.0.0",
    "@ckeditor/ckeditor5-paragraph": "^30.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^30.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-remove-format": "^30.0.0",
    "@ckeditor/ckeditor5-special-characters": "^30.0.0",
    "@ckeditor/ckeditor5-table": "^30.0.0",
    "@ckeditor/ckeditor5-track-changes": "^30.0.0",
    "@ckeditor/ckeditor5-ui": "^30.0.0",
    "@ckeditor/ckeditor5-upload": "^30.0.0",
    "@ckeditor/ckeditor5-widget": "^30.0.0",
    "@ckeditor/ckeditor5-word-count": "^30.0.0",

**Comment by salihkiraz** [comment]
> Right now, I resolved the issue using editor.plugins.get( 'Sidebar' ).setContainer( this.sidebarElementRef.current );

thank you.
