### ISSUE TITLE
[Edge] The upload complete animation doesn't display properly

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1066]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Upload an image.

## ✅ Expected result
The upload complete animation displays properly.

## ❎ Actual result
The upload complete animation is corrupted. 

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/41585585-d36a39f8-73aa-11e8-94ee-4f07386688ac.gif)

**Other information**
OS: Windows 10
Browser: Edge 17

cc @dkonopka

**Comment by dkonopka** [comment]
ATM there is no way to properly play this `animation` because Edge has rendering issues `@keyframes` with changed `width` and `height` value. I'll try to find some solution and still keep "drawing check" animation.

**Comment by Reinmar** [comment]
If we're not able to fix it maybe we could hide it in Edge? That will require a browser-specific class (and we could add those) or hiding this from JS (where we'll have access to env.isEdge very soon).

**Comment by dkonopka** [comment]
> If we're not able to fix it maybe we could hide it in Edge?

or just disable animation and display only fadeIn/out instead of fancy tick animation.

> we'll have access to env.isEdge very soon

🎉 waiting then!

**Comment by Reinmar** [comment]
Here you are: https://github.com/ckeditor/ckeditor5-utils/commit/13d4af44297b9a2e6bc0c5761e42d0c1cecc6101 :)
