### ISSUE TITLE
NPM Js is down - Service unavailable

### ISSUE THREAD

**Issue by FabianReyesSP** [ckeditor/ckeditor5#10663]
## 📝 Provide detailed reproduction steps (if any)

1. npm install
2. return error ‘@ckeditor/ckeditor5-watchdog@24.0.0’ is not in the npm registry.
3. go to https://www.npmjs.com/~ckeditor and return error Service Unavailable.

**Comment by Reinmar** [comment]
Either way, it's not CKEditor 5's problem but npm's so I'm closing this issue.
