### ISSUE TITLE
[Edge] Can't put the selection inside a table cell

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1067]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Create new table.
2. Try to put the selection inside a cell.

## ✅ Expected result
It's possible.

## ❎ Actual result
It's impossible.

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/41586681-a7b3c880-73ad-11e8-9320-8f78b6bbeed4.gif)

**Other information**
OS: Windows 10
Browser: Edge 17

**Comment by Reinmar** [comment]
Can you type there? I can see the editable gets the blue border. So maybe the issue is that the caret isn't visible?

**Comment by Mgsy** [comment]
>Can you type there? I can see the editable gets the blue border. So maybe the issue is that the caret isn't visible?

Nope, typing is not possible.

**Comment by Reinmar** [comment]
Damn... This is something we'll need to understand.

**Comment by jodator** [comment]
I've found that:
1. model selection is set as expected
2. view selection is set as expected
3. DOM selection is set as expected
4. typing does not work
5. selection is not visible

Setting `contentediable="true"` on widget helps.

**Comment by jodator** [comment]
So this does not work on Edge (you cannot type) inside `contenteditable`:
```html
<figure contenteditable="false">
	<table>
		<tbody>
			<tr>
				<td contenteditable="true">
```
while this does:
```html
<figure>
	<table contenteditable="false">
		<tbody>
			<tr>
				<td contenteditable="true">
```

**Comment by Reinmar** [comment]
:/

OK, let's postpone this to it19. I don't think that MS devs will fix it soon so we need to figure out a workaround.

**Comment by jodator** [comment]
[Reported](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17965212/) to Microsoft Edge issue tracker.

**Comment by jodator** [comment]
@Reinmar I'd go with this if it's easy to change:

```js
<figure>
	<table contenteditable="false">
		<tbody>
			<tr>
				<td contenteditable="true">
```
