### ISSUE TITLE
Custom Font Sizes with classes in CKEditor Custom Build

### ISSUE THREAD

**Issue by rastafan** [ckeditor/ckeditor5#10680]
Hi,

sorry to hijack the issues here, but i feel like this question in stackoverflow did not get enough visibility.

I'm trying to put a list of custom font sizes in a ckeditor5 custom build.

Aside from the css and the configuration in the build ckeditor.js file, i think i need to override the `namedPresets` const declared in `ckeditor5-font/src/fontsize/utils.js` , to include the custom classes and sizes, but i can not seem to get how to do it.

I checked-out the ckeditor5 repo and customized the ClassicBuild package to add the required plugins. Then i tried editing the `@ckeditor5-font package` in the same repo and adding it to custom build by npm install ../ckeditor5-font, but then after `yarn build`, the editor is not initialized in the web page because of "duplicate modules". I guess it is because other plugins require the original font plugin, and having required my customized font plugin version causes a double font plugin to be imported (but i'm just guessing).

So, the question is: how do i add one or more custom classes to the font size list?

Thanks everyone.

([Original post](https://stackoverflow.com/questions/69429008/custom-font-sizes-with-classes-in-ckeditor5-custom-build) )

**Comment by rastafan** [comment]
@Reinmar sorry to ping, but i believe the "task" tag is making this issue less relevant, and also i can not seem to find anything in the docs to achieve what we need.
Can you (or someone else) please remove the tag? And maybe point me in the right direction?

Thank you very much.

**Comment by jswiderski** [comment]
@[**rastafan**](https://github.com/rastafan) **we have reported a feature request based on your report** #11213.  If you have any comments, please feel free to leave them there. 

We will close this ticket as this is not the right place to seek technical support. You should rather use [Commercial Support channel](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/getting-support.html) for that.
