### ISSUE TITLE
[Docs] Narrow toolbar prevents creating table 10x10

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1069]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. Execute `npm run docs -- --production`
2. Open built Docs > Examples > Document Editor
3. Try to insert a table 10x10

## ✅ Expected result

The grid should be visible.

## ❎ Actual result

![image](https://user-images.githubusercontent.com/2270764/41589251-5170a13a-73b4-11e8-82ad-bd71a7a23dd9.png)

## 📃 Other details that might be useful

Reproducible on Safari, Chrome, Firefox (Mac OS)

**Comment by Reinmar** [comment]
We need to fix this before the release because it looks bad.

**Comment by oleq** [comment]
Related https://github.com/ckeditor/ckeditor5-ui/issues/199#issuecomment-398358473

**Comment by oleq** [comment]
Let's remove `overflow: hidden` from the `.document-editor` container as a quick fix. It slightly breaks the bottom of the scrollbar but we can live with that.
