### ISSUE TITLE
Search panel from Find and replace plugin should be movable

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#10694]
## 📝 Provide a description of the improvement

In current version search panel has static position and hides some part of editor. Can we move this panel movable?

I recorded gif where I'm trying to find all matched words, but unfortunately one is always behind panel.

![CPT2110141228-1024x472](https://user-images.githubusercontent.com/11577626/137300527-77aa08a0-29ee-47bd-a847-151afd14cdbd.gif)
## 📃 Other details

* Browser: Chrome
* OS: Windows

* CKEditor version: 30.0.0
* Installed CKEditor plugins: @ckeditor/ckeditor5-find-and-replace

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by RebeckaHall** [comment]
Any news on priority for this improvement?

**Comment by scofalik** [comment]
We'd like to inform everyone waiting for this feature that we are working on it and we aim to deliver this with the January release.
