### ISSUE TITLE
Document observable property with @observable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#107]
Reincarnation of #26, but in the new reality.

So, it does not make sense to use some other tag than `@property` to document observable properties, because it will be a mess. Let's simply use the `@observable` tag and later on we'll implement a feature for JSDoc which will add info about this to tagged properties.

**Comment by pomek** [comment]
I found one class - [`headings.HeadingsCommand`](https://github.com/ckeditor/ckeditor5-headings/blob/master/src/headingscommand.js#L17).

Should I create an issue in proper repo?

**Comment by szymonkups** [comment]
@pomek - there is a pull request https://github.com/ckeditor/ckeditor5-headings/pull/10 with documentation for this class.
It is outdated because we changed the repository name, and also this observable is not documented :(
Can you please add comment on this and put review- tag?

**Comment by Reinmar** [comment]
Is this ticket on review? Or should it be closed?

**Comment by pomek** [comment]
There is no review. I'll close it.
