### ISSUE TITLE
Find and replace does not find whole words that are next to each other

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10719]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html
2. Remove all content from the editor
3. Type `foo foo`
4. Try to find `foo` with `Whole words only` turned on

### ✔️ Expected result:

There are two search results, because there are two whole words `foo` in the content.

### ❌ Actual result:

Only the first `foo` is found, the second is ignored. If you insert another space or some character between the two `foo`, it will work as expected and find two results.

### Screencast:

https://user-images.githubusercontent.com/34380544/137890705-ae21ae60-2d3e-4cfb-8ad9-1eae8e084070.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
BTW, Visual Studio Code has implemented the "whole words" option in their IDE in the following way:

https://github.com/microsoft/vscode/blob/f74ad40a3e98ebd8f2a70df093560e835d92cdaa/src/vs/base/common/strings.ts#L180-L187

**Comment by przemyslaw-zan** [comment]
The change:

[https://github.com/ckeditor/ckeditor5/pull/10796/files#diff-b29e977371fccccb6e1f01427567edfc2522d0ad6c5f338e484a029474d978efR153](https://github.com/ckeditor/ckeditor5/pull/10796/files#diff-b29e977371fccccb6e1f01427567edfc2522d0ad6c5f338e484a029474d978efR153)

Explanation:

Changed non-capturing group `(?:...)` to a positive lookahead `(?=...)`.  
Non-capturing group prevents following matches from matching same characters, while positive lookahead checks if they are there, but does not capture them, thus allowing future matches to occur there.

Non-capturing  group `(?:...)`:

![](https://user-images.githubusercontent.com/69513154/140094971-ef1d4aca-7d0f-4af3-9ad1-e7474b3a2dcb.png)

Positive lookahead `(?=...)`:

![](https://user-images.githubusercontent.com/69513154/140095017-219751b8-b57b-4c4e-9110-3e665e2958cf.png)
