### ISSUE TITLE
Safari - The caret jumps in the image's caption

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1072]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. Upload the image.
2. Click on the caption element.

## ✅ Expected result

The caret should be displayed in the middle of the container.

## ❎ Actual result

The caret remembers the position of placeholder. After a few seconds, it backs to center.

![safari-caret](https://user-images.githubusercontent.com/2270764/41592501-0e6e7a7a-73bd-11e8-9390-2e6a726ab8e5.gif)

## 📃 Other details that might be useful

Safari, MacOS.

**Comment by Mgsy** [comment]
It's a DUP of https://github.com/ckeditor/ckeditor5-engine/issues/964.
