### ISSUE TITLE
Image placeholder during image upload is hidden

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#10726]
## 📝 Provide detailed reproduction steps (if any)

1. Go to any demo with image upload in our nightly docs, for example: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/balloon-block-editor.html
2. Upload a heavy image anywhere in the content.

### ✔️ Expected result

Image preview shows right after starting the upload, there is a visible progress bar at the top.

### ❌ Actual result

Image preview is not showing until the upload is done.

Example with balloon block editor and Chrome:

https://user-images.githubusercontent.com/58658048/138098280-fcdfe7d3-2599-4611-a6ba-cae4ddef6c0a.mp4

## 📃 Other details

* Browser: any
* Results are a little different depending on the editor type and browser, but all of them seems to render image placeholder incorrectly
* First affected CKEditor version: current `release` branch
* This issue is not occurring on 30.0.0.
* In the case of base64 image upload there is no image visible after upload, but it's added to the content (`editor.getData()` returns it).

**Comment by Reinmar** [comment]
Info from @Mgsy that it's not reproducible anymore.
