### ISSUE TITLE
Table properties is covered by inline-build toolbar

### ISSUE THREAD

**Issue by molog** [ckeditor/ckeditor5#10739]
## 📝 Provide detailed reproduction steps (if any)
![image](https://user-images.githubusercontent.com/5474410/138428886-550afa1d-947d-41c1-befa-5cdc29000323.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jake-fieldguide** [comment]
cc @Reinmar 

I'm seeing the same thing when using the mentions plugin, where both have the same z-index. It does not cause an issue in the demo app, but in our implementation it looks like this:

<img width="1199" alt="Screen Shot 2021-11-29 at 12 32 18 PM" src="https://user-images.githubusercontent.com/88674247/143939379-e374960f-c13b-473a-afcb-c920678ba2b1.png">

**Comment by namoscato** [comment]
@Reinmar, @FilipTokarski – do you have any plans to fix this bug?

**Comment by Reinmar** [comment]
Related issues: #14886, #6423.

**Comment by mabryl** [comment]
Issue no longer reproducible as of CKEditor 5 v40.0.0:

![image](https://github.com/ckeditor/ckeditor5/assets/72079603/02bbdd7b-82aa-43ab-b47d-911f840c7872)

Hence, closing this ticket.
