### ISSUE TITLE
Mathematical formulas don't display properly

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10738]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to http://localhost:8125/ckeditor5/tests/manual/mathtype.html.
2.  Insert a new equation.

### ✔️ Expected result

![](https://user-images.githubusercontent.com/20988892/138413398-2a366e0b-5599-4385-a097-380fb6d8cdf2.png)

### ❌ Actual result

![](https://user-images.githubusercontent.com/20988892/138414431-7ca4b1d3-9dcf-40ba-9bf4-9967d5d4c7d5.png)

## Notes

It works properly on v30.0.0 and on live docs. It's broken on `release` branch and on nightly docs.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Info from @Mgsy that it's not reproducible anymore.
