### ISSUE TITLE
Cannot unbold when selection spans over a widget

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1073]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Select any part of paragraph **below** a widget and a widget contents (ie image caption).
2. Use `ctrl+b` to bold it - text get bold for the whole selection.
3. Use `ctrl+b` again to unbold it.

**Note** It only happens when selecting text below widget (image, table). If a selection start above a widget you can easily bold/unbold the selection :expressionless:...

## ✅ Expected result

The selection is not bold anymore.

## ❎ Actual result

The selection is bold (and beautiful).

## 📃 Other details that might be useful

The same happens with other basic styles.

Example selection:

![selection_029](https://user-images.githubusercontent.com/247363/41592834-3f8ddc30-73be-11e8-8773-4f7f28d765b5.png)

**Comment by Reinmar** [comment]
It's a dup of that ticket about attribute command's state – https://github.com/ckeditor/ckeditor5-basic-styles/issues/56.
