### ISSUE TITLE
Link Bug after i Save my content

### ISSUE THREAD

**Issue by Arttemys** [ckeditor/ckeditor5#10762]
## 📝 Provide detailed reproduction steps (if any)

1. Add a link
2. Save and close aou modal with classic editor
3. Open again the modal, this shows up the old content with the "link" but as <p> format only, wihtout the link tag

### ✔️ Expected result

_What is the expected result of the above steps?_
when the user open the editor modal, added link show without correct format, and do not remain active

### ❌ Actual result

_What is the actual result of the above steps?_
when i save the content, links disabled

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._
i still search for the solution for this bug 

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
