### ISSUE TITLE
Building nightly docs stopped working

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1076]
https://travis-ci.org/ckeditor/ckeditor5/builds/393668908#L1507

```
$ travis_wait npm run docs:build-and-publish-nightly
Still running (13 of 20): npm run docs:build-and-publish-nightly
The command npm run docs:build-and-publish-nightly exited with 1.
Log:
> ckeditor5@10.0.1 docs:build-and-publish-nightly /home/travis/build/ckeditor/ckeditor5
> node ./scripts/docs/build-and-publish-nightly.js
Cloning ckeditor5.github.io repository...
Building documentation...
Copying files...
mkdir: cannot create directory ‘ckeditor5.github.io/docs/nightly/ckeditor5/latest’: File exists
/home/travis/build/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/lib/tools.js:42
			throw new Error( `Error while executing ${ command }: ${ ret.stderr }` );
			^
Error: Error while executing mkdir ckeditor5.github.io/docs/nightly/ckeditor5/latest: mkdir: cannot create directory ‘ckeditor5.github.io/docs/nightly/ckeditor5/latest’: File exists
```

Besides, we must make sure that this task fails the build when it crashes.

**Comment by pomek** [comment]
Now failed `npm run docs` which is called inside `npm run docs:build-and-publish-nightly`…

![image](https://user-images.githubusercontent.com/2270764/41835742-00d364ac-7859-11e8-98a7-7f1c49788194.png)

![image](https://user-images.githubusercontent.com/2270764/41835485-0c842f8a-7858-11e8-94a5-e9af05a78152.png)

Is possible that this error breaks the build? 

cc: @msamsel

**Comment by Reinmar** [comment]
This is Umberto's issue. Can you report a ticket there, @pomek?
