### ISSUE TITLE
Right-click functionality in tables for text across multiple cells (balloon block editor)

### ISSUE THREAD

**Issue by OLCadlywydd** [ckeditor/ckeditor5#10770]
## 📝 Provide a description of the improvement

When editing a table using ballon block editor, is it be possible to provide right-click functionality for text when multiple cells are selected? 

It's currently possible to do this in the classic editor with the `TableSelection` plugin, but there is no way to do this in the balloon block editor (unsure about other editors). So, when changing text properties in tables using the ballon block editor, you currently have to change each cell's text one-by-one, by selecting the text and then right-clicking to change it. This is very time-consuming if you want to change large amounts of text across different cells. When multiple cells are selected, you can change some properties, such as the cell background colour, but you are unable to change the text properties within those cells at all.

See the below example when attempting to change cell text colour:

![example](https://user-images.githubusercontent.com/72607789/139209701-62d327ed-a1e8-4737-af86-84ae810b9ea2.gif)

(I've marked this as an improvement, since (as mentioned above) this functionality is already available for the classic editor.)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Three quite random thoughts from me, but I'd also like to hear @oleq's opinion.

*   When using tables, don't use the balloon-based editors. While sexy and seemingly user-friendly, the balloons are in fact a terrible UX mess and cause various interaction conflicts.
*   We do not want to touch the right-click (context menu). CKEditor 4 does this and if you try clicking the "Paste" option in the overridden context menu you'll get a warning. Plus there are other issues when hiding native UI. So this is not the way to go.
*   Isn't your case solvable by configuring the table toolbar to contain the same buttons that are used in the content toolbar? I mean [https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-contentToolbar](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-contentToolbar) and [https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-tableToolbar](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-tableToolbar).

**Comment by Reinmar** [comment]
BTW, this is a DUP of #7549. Let's continue the discussion there.
