### ISSUE TITLE
可以自定义添加numbered list项吗

### ISSUE THREAD

**Issue by Xiaoxiaoaiya** [ckeditor/ckeditor5#10778]
是否可以自定义添加一些office的编号列表项？

**Comment by FilipTokarski** [comment]
Translation:

> Can I add a numbered list item by myself
> 
> Is it possible to add some Office numbered list items customized?

Hi, unfortunately currently it is not possible to do it by default, there's a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/8687).
