### ISSUE TITLE
Add support for content not to be processed through the conversion pipeline

### ISSUE THREAD

**Issue by shabab477** [ckeditor/ckeditor5#10787]
## 📝 Provide a description of the improvement

We are looking to refactor our Email editor to CKEditor5 from CKEditor4. Now our email content can come from anywhere, for example, Outlook, Gmail, etc, each having its own way of representing its HTML data. What we want is to show these HTML content as is, without the HTML tags going through the conversions to CK5 custom model.

So far, I have got suggestions to just create a custom converter but it's extremely tedious to go through all email clients and how each email client generates HTML. Ideally, we would like to wrap our email content with a `<div class='transparent'></div>` and CK5 should understand not to put any underlying HTML through the conversion pipeline.

Is there any plugin that is readily available for this or am I missing something?

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
There are two features that you can check:

*   [https://ckeditor.com/docs/ckeditor5/latest/features/html-embed.html](https://ckeditor.com/docs/ckeditor5/latest/features/html-embed.html)
*   [https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html)

There's a high chance that they will somehow work for your case. We don't plan doing more in this area, though.
