### ISSUE TITLE
The `shift` + `enter` at the end of a content with a link will prevent typing

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1078]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Select whole editor content.
2. Add a link.
3. Place a selection at the end of a content.
4. Press `shift` + `enter`.
5. Try to type something.

## ✅ Expected result

The letters you type appears.

## ❎ Actual result

The letters you type does not appear or are removed shortly after you type.

## 📃 Other details that might be useful

It looks like this happens at random as I cannot reproduce it consistently. But happens ie in Document editor example in docs.

Edit: Happens with `shift` + `enter` only.

**Comment by Reinmar** [comment]
What's ctrl+shift+enter?

**Comment by jodator** [comment]
@Reinmar I've updated the title/description. I've found it using `ctrl` + `shift` but happens also when pressing `shift` + `enter`. 

After this situation you can:
- press `shift` + `enter` again and it will insert `<br>` - typing still is not possible
- pressing `enter` will create a paragraph and you can type there
- type when exiting two-step block o link (the `<br>`'s created before will loose link attribute)

**Comment by jodator** [comment]
The same happens at the end of a nested editable - ie in the table cells content.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore.
