### ISSUE TITLE
[Edge] Selection moves to a block before an image after dragging it to a next block

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1079]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the classic editor example in docs.
1. Change the image to the side image.
1. Start the selection in the block below the image and move it to the next block.

## ✅ Expected result
Two blocks are selected.

## ❎ Actual result
The selection moves to the block above the image.

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/41594051-5a0581b8-73c2-11e8-8b19-e1102446ed63.gif)

**Comment by jodator** [comment]
@Reinmar: I was debugging this and I didn't find a reason why although selection is fixed and set to proper new selection it is later changed by either a browser or something else.

The thing is that after selection post-fixer fix the selection that spans over widget (and ends on it) the selection is either wrongly set in the view or the browser "fixes" it so the selection observer detects new selection. It also sets it the collapsed selection at the end of selection (either end of a widget or end of text - when selection starts on widget).

One thing helps a bit: removing `contenteditable` `false/true` attribute combination on widgets.

Now the selection "stops" on the widget BUT is properly rendered in the view.

Below are screenshoots of the same salection - starting in paragraph and moving it below the the image:
1. Current (with selection post-fixer fixes)
![selection_005](https://user-images.githubusercontent.com/247363/42315830-b14ebb96-8048-11e8-887f-922db8a2dd8c.png)

2. As above but without `contenteditable=false` in the editing area:
![selection_004](https://user-images.githubusercontent.com/247363/42315841-b48bdcb2-8048-11e8-8357-99690f80c7f2.png)

Unfortunately in both cases selection stops...

ps.: Oh and also removing `contenteditable=false` actually fixes the bug described here.
