### ISSUE TITLE
Prefix attributes that are considered unsafe

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10801]
We introduced a mechanism that strips unsafe attributes, this is attributes that might break the editing experience in some way.

Right now, it's stripping them completely when the content is being rendered in the editing view (they are preserved in the data just fine).

The idea is – instead of stripping them, prefix them with some meaningful `data-ck-unsafe-attribute-` prefix to give developers a pointer to why this thing does not appear in the view.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Also, in the `<script>` element that we replace with a `<span>` let's replace the `data-ck-hidden` attribute that we use right now with a `data-ck-unsafe-element=script` attribute.

**Comment by abishek007** [comment]
> I am trying to use ckEditor5 in my web application, that makes client able to send email in our platform. this feature or what ever it is, does not allow user to type text in the editor, because it has found some text which calls unsafe! even in old emails body which we want to reply on it.
> 
> Is here any chance to disable this process?

[HoushanG6](https://github.com/HoushanG6) have you found any solution? how disable this?
