### ISSUE TITLE
Add support for editable content which should not go through the CK5 Data processing engine

### ISSUE THREAD

**Issue by shabab477** [ckeditor/ckeditor5#10804]
## 📝 Provide a description of the new feature

Hi @Reinmar, thank you for the outstanding work with CKE5.

We are trying to use CKE5 as the editor in our email client. Currently, we use CKE4 but want to upgrade to the latest version available.

Our email client users receive very complex HTML content from different marketing automation tools, which do not abide by the CKE5 schema. For example, custom divs inside table element. 

Users can **REPLY** on those email content which show up as "quoted text".

When we are showing those "quoted text" HTML content CKE5 is picking up those components as CKE5 widgets and doing its upcasting, thus breaking the HTML content.

What we ideally want is creating "quoted email" parts of the content area to be free from CKE5 conversion engine. No conversion should take place in those parts. But users should be able to inline edit those quoted text with no problem, like done on CKE4.

We have been directed towards:

- [HTML embed](https://ckeditor.com/docs/ckeditor5/latest/features/html-embed.html): This doesn't work for us because HTML embed makes the "quoted text" read only. Users should be able to edit "quoted text".
- [General HTML Support](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html): This doesn't work for us because the content goes through the conversion and breaks stuff. We also noticed this plugin doesn't support <html> tag elements. We sometimes have a full html page as quoted text, with <head>, <style> tags that need to be present inside the DOM. GHS seems to not support these plugins. We need the full page editing support as done in CKE4.

Would be great if you guys could nudge us towards a solution. Thank you for taking the time to go through our issue.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I'm sorry, but you will need to change your approach if you want to keep using CKEditor. With CKEditor 5 we changed the direction and the "don't get in my HTML's way" approach from CKEditor 4 is not possible anymore. CKEditor 5 can take care of the textual part of your content, but not the entire page. You can consider e.g. loading into the editor only part of that HTML and introducing some pre and post-processing.

**Comment by andreak** [comment]
> I'm sorry, but you will need to change your approach if you want to keep using CKEditor. With CKEditor 5 we changed the direction and the "don't get in my HTML's way" approach from CKEditor 4 is not possible anymore. CKEditor 5 can take care of the textual part of your content, but not the entire page. You can consider e.g. loading into the editor only part of that HTML and introducing some pre and post-processing.

This is very sad news as it makes CKEditor5 not suited for creating email-applications which need to compose emails.

**Comment by andreak** [comment]
@Reinmar In general I like the strict approach, and understand that what we're asking is not _currently_ possible. Let me have one more try at explaining, just in case:-) What @shabab477 suggests is adding support (by contributing to) in the framework for a concept of:
If a certain element is encountered, like e.g. `<div class="my-special-component">` then the processing pipeline will just "lay off" and "accept" all sub-elements verbatim when descending the DOM-tree from that element until that element is closed (`</div>`). 
Will such an addition be welcomed by this project?
