### ISSUE TITLE
Angular - Classic ckeditor: Fixed toolbar on click should change to listen on scroll

### ISSUE THREAD

**Issue by anhtuanbui** [ckeditor/ckeditor5#10815]
## 📝 Provide detailed reproduction steps (if any)

1. Using classic editor the toolbar fixed to top after srolling down.

### ✔️ Expected result

The toolbar get back to it position when scroll over its origin position

### ❌ Actual result

The toolbar only change the position set when the editor is out focus and in focus.

### ❓ Possible solution

Clear show the toolbar on focus only.
Use listen on scroll instead of click.

## 📃 Other details

* Browser: Chrome
* OS: Window
* First affected CKEditor version: 5 @31 angular
* Installed CKEditor plugins: custom

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, I'm not sure I understood correctly. Could you attach a movie or a gif file showing the problem exactly?

**Comment by anhtuanbui** [comment]
Oh, sorry for putting this issue.
I think it's the problem when I added CKeditor in Angular app with a flex box which is scrollable inside. 
I couldn't find the code for attaching the toolbar on top so I made guesses. I got my way around the problem. So I don't have the problem sample now.

CkEditor worked fine on the sample but in the Angular app, its listener on scrolling inside a flex box does not seem to be working so the toolbar didn't change it position on scrolling but clicking on and out focus of the ck-content made it change.

In reproducing this problem, you may want to 
> 1. Create a angular material sidebar content box. 
> 2. Put the editor inside with height to make the box scrollable. 

You will see the problem on scrolling over the toolbar.

**Comment by ashotgalstyanTR** [comment]
How did you fix this issue?

**Comment by anhtuanbui** [comment]
> How did you fix this issue?

I turned off fixed toolbar from CKeditor and rewrite CSS code to make it fixed from the app.
