### ISSUE TITLE
Tour balloon stopped working on docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10810]
## 📝 Provide detailed reproduction steps (if any)

1.  Checkout to `master` or `stable`
2.  Build docs
3.  Go to any feature that uses tour balloon

### ✔️ Expected result

Tour balloon shows up, no errors.

### ❌ Actual result

Tour balloon does not show up. Error in the console:

```javascript
TypeError: window.umberto.createTooltip is not a function
    at window.attachTourBalloon (assets.js:86)
    at eval (block-quote.js:12)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
I checked nightly and stable docs:

- https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/text-alignment.html
- https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html

My guessing to fix the issue is to reinstall dependencies.

**Comment by FilipTokarski** [comment]
Turns out it was caused by outdated dependencies. After `yarn reinstall` tour balloons work fine.
