### ISSUE TITLE
[Document lists] Introducing DocumentListEditing

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10812]
Part of #2973.

Implement the editing part of the document lists feature:

*   Schema
*   Converters (upcast, downcast)
*   Support for:
    *   indent
    *   type
*   Error when loading DocLists and PlainLists/ToDoList/PlainListStyle together

**Comment by Reinmar** [comment]
Scope that has been covered in this ticket:

*   Downcast ✅
*   Upcast ✅
*   Basic schema
    *   First draft of `$container` ✅
*   Model
    *   Postfixing taking care of fixing types and indentations and list structure correctness ✅
        *   Missing: Fixing ids 🟡
    *   Change listener reconverting on parent thing changes ✅
        *   Refreshing the bogus span 🟡
*   Conversion
    *   Removing isAllowedAttributeElement ✅
        *   And link converters ✅
    *   Element creator callback in `attributeToElement()` and `elemenToElement()` and other helpers gets the `data` object ✅
*   Differ
    *   Old/new attributes need to be provided in the differ output ✅
*   Basic Enter integration (escaping list) ✅
*   Manual tests ✅

**Comment by Reinmar** [comment]
No merge needed, we’ll use git co `ck/10812-document-list-editing` as a feature branch.
