### ISSUE TITLE
[GHS] The `DataFilter#_consumeAllowedAttributes()` should be public to allow 3rd party features integration

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10827]
## 📝 Provide a description of the improvement

The `DataFilter#_consumeAllowedAttributes()` is marked as a private method but it's used in most of the features' integrations. Currently, those integrations for our plugins are all in the same package but for the external features, this must be publicly available.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
*   How's this method used?
*   Review the method name. Does it reflect how this method is used?
*   Add meaningful docs with realistic examples.
*   Make it public.
