### ISSUE TITLE
Manual decorators for LinkImage lost upon upcast

### ISSUE THREAD

**Issue by wimleers** [ckeditor/ckeditor5#10828]
## 📝 Provide detailed reproduction steps (if any)
Discovered while working on https://www.drupal.org/project/ckeditor5/issues/3247683.

1. Load the following CKE5 plugins: `image.Image`, `image.ImageToolbar`, `image.ImageUpload`, `link.Link`, `link.LinkImage`, with the following `Link` config:
```
"{"decorators":[{"mode":"manual","label":"Foobarize","attributes":{"foo":"bar"}}]}"
```
2. Instantiate CKEditor 5 on a textarea containing markup like:
```
<p><a href="http://www.drupal.org/association" foo="bar">test link</a> and <a href="http://www.drupal.org/association" foo="bar"><img src="/sites/default/files/inline-images/dark_14.png"></a></p>
```

### 🎥 Screencast

![image link decorators](https://user-images.githubusercontent.com/14240/140946402-709e6b60-9d82-45f0-b016-4180d49d6266.gif)

### ✔️ Expected result

Same markup as before, with `foo="bar"` retained on both the linked text _and_ the image.

### ❌ Actual result

`foo="bar"` is retained only on the linked text _not_  on the image.

### ❓ Possible solution

Bug in upcasting.

## 📃 Other details

* Browser: N/A — reproduced in Chrome and Firefox.
* OS: N/A — reproduced in macOS Big Sur
* First affected CKEditor version: `v31.0.0`
* Installed CKEditor plugins: see above.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by wimleers** [comment]
#6571 seems related?

**Comment by rmaxx** [comment]
👍seeing same results on link classes after installing imagelink plugin
