### ISSUE TITLE
Popover is still visible while scrolling

### ISSUE THREAD

**Issue by jesben** [ckeditor/ckeditor5#10832]
Check demos for "document editor" on ckeditor website:

If you click on an element, who show an popover for options of the element:

![image](https://user-images.githubusercontent.com/11041965/141144510-e0cc279d-1ea4-48a4-adb3-7745d41873af.png)

if you scroll further, the popover is still visible in "hidden" area:

![image](https://user-images.githubusercontent.com/11041965/141142554-52433f6e-52a2-482b-9e3a-5641cea68cb8.png)

### ✔️ Expected result

Not visible

### ❌ Actual result

Visible

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: 5
* Installed CKEditor plugins:

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It's a known bug and there's an open [ticket for this](https://github.com/ckeditor/ckeditor5/issues/5328). I'll close this one as a duplicate.
