### ISSUE TITLE
[FF] Typing space after inline element boundary doesn't work

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1083]
1. Press bold (on),
2. Type "a",
3. Press bold (off),
4. Press <kbd>Space</kbd>

**Expected**: `<p><b>a</b> []</p>`

**Actual**: `<p><b>a</b>[]</p>`

**Comment by Reinmar** [comment]
I pushed `ckeditor5-typing@t/ckeditor5/1083` with a temporary fix.

**Comment by Reinmar** [comment]
FFS... this is FF's bug because we set the selection in the right place: 

![image](https://user-images.githubusercontent.com/156149/41598774-858b04a2-73d1-11e8-85a5-0fe0acd634a1.png)

And I think I know it already. It's super old...

**Comment by ma2ciek** [comment]
It looks like a regression - it was fixed here: https://github.com/ckeditor/ckeditor5-engine/pull/1204
