### ISSUE TITLE
Table toolbar shows off the viewport when dealing with large table 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#10846]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-and-cell-styling-tools
2.  Set table width to 2700px or 4700px
3.  Click outside the editor and then on the table

![](https://user-images.githubusercontent.com/5314687/141782458-697690f6-eed5-4013-8630-4fa9d97a8a1e.gif)

### ✔️ Expected result

Table toolbar is shown in the editor area

### ❌ Actual result

Table toolbar shows off the page in the middle of the table

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: …
*   Installed CKEditor plugins: table

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Related/dup of #5328?

**Comment by Reinmar** [comment]
SIde note: When the table has width over 3200px in the docs (https://ckeditor.com/docs/ckeditor5/latest/features/table.html) the page layout breaks:

![](https://user-images.githubusercontent.com/156149/147079073-33d6b37b-e827-4405-ba1c-73e949be2285.png)

This is weird, because it works well until ~3000px.

**Comment by Reinmar** [comment]
*   Two potential options:
    *   When the table's width exceeds the editable width, position the balloon in the center of the editable.
    *   Use the editable as a limiter for the balloon position (don't let the balloon leak out of the editable's area).
*   The fix needs to land in WidgetToolbarRepository so it's generic for all widgets.
*   Does fixing the positioning of the toolbar fixes the positioning of the table properties balloon?
    *   Maybe. The latter should inherit the position of the former. But who knows.
*   This case seems to be similar to the vertical scrolling where we switch to fixed position where the table's height exceeds the editable area.
    *   Maybe. But it's complicated and may be contextual.
    *   Thought: When the thing to which the balloon is pinned disappears from the viewport, the balloon should disappear too.

**Comment by shenyi-dra** [comment]
> Related/dup of #5328?

First of all, thanks for the hard working and amazing project.

yep, it's seems related to #5328 open issue. However that issue opened at 2017. And unforurnally it is still open in 2023.
That's part of issue which related to my desicion whether to use ckeditor or find something else (Even it's really hard to find something as good as CKEditor).

**Comment by Witoso** [comment]
Thanks for the good words, the https://github.com/ckeditor/ckeditor5/issues/5328 is in our investigation pipeline, and we should have some thoughts soon.
