### ISSUE TITLE
Duplicated version of docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#10849]
## 📝 Provide a description of requested docs changes

1.  Go to [https://ckeditor.com/docs/ckeditor5/latest/features/page-break.html#related-features](https://ckeditor.com/docs/ckeditor5/latest/features/page-break.html#related-features) and click on _pagination feature_ link.

The link takes you to the old docs, which still have old navigation and old pagination page (with no subsections):

*   proper link: [https://ckeditor.com/docs/ckeditor5/latest/features/pagination/pagination.html](https://ckeditor.com/docs/ckeditor5/latest/features/pagination/pagination.html)
*   actual, bad link: [https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html)

We should keep this in mind, as there might be more such links in the docs.

**Comment by godai78** [comment]
Corrected in ea155e1

**Comment by wwalc** [comment]
There should be a proper redirect too?

**Comment by wwalc** [comment]
Any chance that more redirects are missing here? https://github.com/ckeditor/ckeditor5/blob/master/docs/umberto.json#L15

**Comment by godai78** [comment]
I'll look into it.

**Comment by godai78** [comment]
Added redirect and corrected link in a readme in `internal`, too.  
  
No other redirects seem missing at the moment, but I'll put it on the back burner and check some more.

**Comment by godai78** [comment]
Seem to be covered and already on prod.

**Comment by pomek** [comment]
https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html still points to old docs. It didn't redirect to the new page.

**Comment by godai78** [comment]
@vokiel - can you please check it? I added the redirect but must have done something wrong...

**Comment by vokiel** [comment]
Docs builder does not remove files from S3, so I removed it manually and created redirection. Seems to be fine now.
