### ISSUE TITLE
List Style plugin doesn't seem to show  dropdown in the latest classic build

### ISSUE THREAD

**Issue by KshamaShrey** [ckeditor/ckeditor5#10840]
Steps to Reproduce :

1. Go to https://ckeditor.com/ckeditor-5/online-builder/
2. Choose editor type as Classic
 
3. Choose editor plugins required.
4. Select both List and List style plugin
5. Go to Next step and check that both bulleted and numerical listing are without dropdowns as shown below

<img width="937" alt="Liststylenew" src="https://user-images.githubusercontent.com/39548087/141736016-e6ae94e0-7c94-4611-839d-65bff7042bd3.png">

Expected Result:

Since list style and list plugins are included in the build , both numerical and bulleted listing should include 3 styles for unordered lists and 6 styles for ordered list as mentioned in the document

#List styles
The list style feature introduces some more styles for the list item markers. When enabled, it adds 3 styles for unordered lists and 6 styles for ordered lists to choose from. The styles can be changed via the dropdown that opens when you click the arrow next to the appropriate list button in the toolbar.

<img width="676" alt="liststyleold" src="https://user-images.githubusercontent.com/39548087/141736043-3af46615-da98-4edb-9468-e2326ce260e0.png">
Actual Result:

No dropdown is displayed for both bulleted and numerical listing as shown in the first screenshot.

**Comment by Manjunatha123** [comment]
I am also facing the same issue.
User is unable to change numeric listing from 1. 2. 3. to a. b. c.
Also user is not having flexibility on list style type as per their needs.

**Comment by FilipTokarski** [comment]
Hi, I just checked it and if you actually build and download the editor, then the list styles dropdown is shown and works as expected. Could you confirm?

**Comment by KshamaShrey** [comment]
It works as expected. Thanks

**Comment by shubhjhawar** [comment]
i am facing the same issue, can someone guide me how to fix it?
