### ISSUE TITLE
Bold is continued in a new line (after <br>) even though being disabled before that <br>

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1084]
1. Ctrl+b and type "foo".
2. Ctrl+b again to disable bold.
3. Shift+enter
4. Type "bar"

Expected: "bar" is not bolded.

Actual: "bar" is bolded; bold switches on right after you press shift+enter.

**Comment by FilipTokarski** [comment]
I tried it on every browser and cannot reproduce it. It looks like everything is working fine and we can close this issue.
