### ISSUE TITLE
[Feature] Block content (multiple paragraps) in image captions

### ISSUE THREAD

**Issue by dvlpr91** [ckeditor/ckeditor5#1086]
Please add the ability to insert the previous / next paragraph into the caption when clicking the image widget.

Thanks.

**Comment by Reinmar** [comment]
This behaviour (what's allowed inside image captions) is controlled by the schema. After changing these lines:

https://github.com/ckeditor/ckeditor5-image/blob/master/src/imagecaption/imagecaptionediting.js#L49-L53

to:

```js
schema.register( 'caption', {
	allowIn: 'image',
	allowContentOf: '$root',
	isLimit: true
} );
```

I've got it working easily:

![image](https://user-images.githubusercontent.com/156149/41729313-36e7c9b2-7579-11e8-967a-4a31d206c78b.png)

However, [it's not possible at this moment to easily reconfigure the schema](https://github.com/ckeditor/ckeditor5-engine/issues/1367). Currently, you'd need to patch the code of the image caption plugin. But we'll improve this situation over time.

**Comment by Reinmar** [comment]
I'll close this ticket as it DUPs https://github.com/ckeditor/ckeditor5-engine/issues/1367 and because I kinda answered it.

Still, if something isn't clear, let us know.
