### ISSUE TITLE
ordered list with Roman numbers or Alphabetical type is not working as excepted when editor is in track-change status

### ISSUE THREAD

**Issue by LysaFeng** [ckeditor/ckeditor5#10868]
1.enter any text in editor 
2.select the text and click "ordered list with Roman numbers" icon, then trackchanges appear and show "change to: numbered list".
3.accept these trackchanges
4.observe only single digit number are coming rather than Roman number
5.no matter what kind of list type I choosed, finally got the same result when it's in track-changes status

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Track changes is a commercial plugin and if you are a licensed user, we encourage to use our dedicated [support channel](https://ckeditor.com/contact/) if you encounter any problems.

As it comes to the reported behaviour, we are aware of this issue and we're tracking it already in another repository. I'll close this one as a duplicate.
