### ISSUE TITLE
Find And Replace widget does not pop up on Ctrl/Cmd+F when in overflow menu

### ISSUE THREAD

**Issue by stefandobre** [ckeditor/ckeditor5#10874]
Given a toolbar with lots of entries, if the Find And Replace toolbar entry is pushed into the overflow menu, hitting Ctrl/Cmd+F won't open the widget. Nothing happens. On manual click it works as expected.

Classic Editor 31.0.0, Chrome 96

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. This is a known case and we're already [tracking it here](https://github.com/ckeditor/ckeditor5/issues/10645).

I'll close this one as a duplicate.
