### ISSUE TITLE
[iOS] Holding the Delete button makes the deleting action slower

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10888]
## 📝 Provide detailed reproduction steps (if any)

1.  Put the caret in some long sentence.
2.  Hold the delete button.

### ✔️ Expected result

After a while, whole words are removed.

### ❌ Actual result

After a while, deleting becomes slower and removes characters one by one.

## 📃 Other details

Tested on iPhone (iOS 15) and iPad (iOS 12).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This is no longer reproducible in the latest documentation (v42.0.0) and iOS 17.5.1.
