### ISSUE TITLE
Copy paste from google docs with double tabs.

### ISSUE THREAD

**Issue by Shisyr** [ckeditor/ckeditor5#10884]
## 📝 Provide a description of requested docs changes

I added two tabs in google docs and copied it to ckeditor5, but I have got only one space instead of two tabs in ckeditor5.

<img width="1480" alt="Screen Shot 2021-11-23 at 17 28 04" src="https://user-images.githubusercontent.com/22312494/143016569-10140cd0-d97d-4d3d-a4e7-1272f675d55f.png">

<img width="843" alt="Screen Shot 2021-11-23 at 17 28 37" src="https://user-images.githubusercontent.com/22312494/143016562-dfe494c9-cbba-443d-9b32-f9f5c451d264.png">

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. This use case is currently not supported in CKEditor 5. We have a feature request for this - https://github.com/ckeditor/ckeditor5/issues/7541, so if you find this to be important, let's continue the discussion there.

You might also be interested in comments from this thread: https://github.com/ckeditor/ckeditor5/issues/457.
