### ISSUE TITLE
[Document lists] Editing part - tab, shift+tab

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10880]
Part of #2973.

Based on https://miro.com/app/board/o9J_lVbklBg=/

**Comment by Reinmar** [comment]
Consider adding an integration test for how tab/shift+tab behaves in:

```
<td><ul><li>x</li><li>x[]</li></ul></td><td></td>
```

**Comment by Reinmar** [comment]
Difference between previous list implementation and the new one: Now we can have a table or code block inside a list item. So far, we could only have a list inside a table cell. So, the order may now be reversed.

**Comment by Reinmar** [comment]
Current Tab listeners: lists, table, code block, restricted editing.

**Comment by Reinmar** [comment]
Remark: There's a functional conflict between indenting lists and indenting blocks. For simplicity, we decided to give list indentation absolute precedence over indenting blocks.

We can review this later when we can see the behavior live. We're aware that indenting blocks will not be possible in some scenarios.

**Comment by Reinmar** [comment]
There are two places where we'll need to handle these priorities:

* keystroke handling (problem: we don't use editing view's events here but the keystroke handler which has no support for priorities)
* multicommand for indent

This gets more complex, so let's split the integration with indent block to a separate ticket. For now, let's focus on scenarios where only indent list is enabled.

**Comment by niegowski** [comment]
Closed in #11244.
