### ISSUE TITLE
[GHS] Support <caption>'s additional attributes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10896]
As we figured out in #10893 we already support upcasting `<caption>`. But then in #10892 we found out that GHS will not upcast `<caption>`'s attributes.

Target: https://github.com/ckeditor/ckeditor5/blob/89b5315550e1dbcf26bc9cb4678931670b9bb52c/packages/ckeditor5-html-support/src/integrations/table.js

**Comment by Reinmar** [comment]
When researching this topic we found out that we don't even support `<figcaption>`'s attributes?

**Comment by Reinmar** [comment]
@niegowski could you check whether this issue is valid? We've been checking the code, but maybe it works OOTB.

**Comment by niegowski** [comment]
> [**@niegowski**](https://github.com/niegowski) could you check whether this issue is valid? We've been checking the code, but maybe it works OOTB.

It's handled by the default element to element handlers, it does not need a specific integration.
