### ISSUE TITLE
[Docs] Lists are missing in the features documentation

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1089]

**Comment by Reinmar** [comment]
So is the enter feature. And pasting, and undo. Headings have their own section only because there's an important config option.

Are we sure that we want to document all features? Does it bring value to anyone?

**Comment by Stalq** [comment]
I think that having the docs brings value as our users are asking about lists feature regularly.

**Comment by Reinmar** [comment]
Thanks for the feedback @Stalq. I think that a natural moment to introduce this guide will be when we'll add list styles, which should happen in a reasonably close future.

**Comment by Mgsy** [comment]
The list feature [has been added](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html) to the CKEditor 5 features list, so this issue is no longer valid.
