### ISSUE TITLE
[GHS] Handle <script>

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#10891]
\<script> is now ignored by GHS and cannot be enabled with it in any way.

**Comment by Reinmar** [comment]
Remarks:

*   So far, we skipped `<script>` element when defining the data schema for GHS (https://github.com/ckeditor/ckeditor5/blob/89b5315550e1dbcf26bc9cb4678931670b9bb52c/packages/ckeditor5-html-support/src/schemadefinitions.js#L48-L49).
*   Editing view:
    *   The renderer will turn this element into a hidden span.
*   Model:
    *   `<script>` element can exist in block and inline contexts. This is - e.g directly in the root or inside `<p>`.
    *   Model definition:
        *   Allowed everywhere.
        *   `isInline: true, isBlock: false, isObject: false`
    *   Let's set the content of the script as an attribute of that model element.
*   We need to support `<script>` element attributes too.

**Comment by Reinmar** [comment]
The behavior of this feature will be somehow similar to the behavior of the soft break.

**Comment by wimleers** [comment]
This will unblock https://www.drupal.org/project/drupal/issues/3245950 👍
