### ISSUE TITLE
Can (plain)text be upcasted?

### ISSUE THREAD

**Issue by JanWennrichPCSG** [ckeditor/ckeditor5#10898]
The HTML I pass to the editor via `setData()` contains non-HTML placeholder tags from the [Smarty Template Engine](https://www.smarty.net/). Those tags look like this: `{{brick id=123}}`.
I would like to replace/upcast those custom tags with/to valid HTML elements in the editor.  
As I couldn't find documentation about this and all my approaches did not work, I was wondering if this is even possible.

At the moment I do replace those tags manually, before passing the HTML to the editor (e.g. replace `{{brick}}` with `<brick>`). My plugin then has an upcast "rule" for `<brick>` tags. A data-downcast "rule" converts the `<brick>`-tags back to `{{brick}}`-tags.
This approach works but causes problems further down the line: If the user moves one of those elements around in the editor via drag-and-drop, it turns the `<brick>` into a plaintext `{{brick}}` (because of the data-downcast and the missing upcast I guess).

Is there an upcast possibility for plain-text - maybe something like this:
```js
editor.conversion.for('upcast').elementToElement({
    view: {name: '$text'},
    model: this.upcastPlainText
});
```
----

Edit: Sorry for using the wrong label. I couldn't figure out how to open an issue with the `type:question` label.

**Comment by niegowski** [comment]
You can override the text nodes default upcast that is registered here: [https://github.com/ckeditor/ckeditor5/blob/1e68ad742379620df014d564dce32e91034730ac/packages/ckeditor5-engine/src/controller/datacontroller.js#L142](https://github.com/ckeditor/ckeditor5/blob/1e68ad742379620df014d564dce32e91034730ac/packages/ckeditor5-engine/src/controller/datacontroller.js#L142) and is implemented like this: [https://github.com/ckeditor/ckeditor5/blob/f11eb3c7215349cd95bbbcd6b49291d0d34e5eb1/packages/ckeditor5-engine/src/conversion/upcasthelpers.js#L452-L481](https://github.com/ckeditor/ckeditor5/blob/f11eb3c7215349cd95bbbcd6b49291d0d34e5eb1/packages/ckeditor5-engine/src/conversion/upcasthelpers.js#L452-L481)

Here is an example of how it could be done:

```javascript
function TemplatedText( editor ) {
	editor.model.schema.register( 'templateTag', {
		allowWhere: '$text',
		allowAttributes: [ 'tag' ],
		allowAttributesOf: '$text',
		isInline: true
	} );

	editor.conversion.for( 'upcast' ).add( dispatcher => {
		dispatcher.on( 'text', ( evt, data, { schema, consumable, writer } ) => {
			let position = data.modelCursor;

			// When node is already converted then do nothing.
			if ( !consumable.test( data.viewItem ) ) {
				return;
			}

			if ( !schema.checkChild( position, '$text' ) ) {
				if ( !isParagraphable( position, '$text', schema ) ) {
					return;
				}

				position = wrapInParagraph( position, writer );
			}

			consumable.consume( data.viewItem );

			// The following code is the difference from the original text upcast converter.
			let modelCursor = position;

			for ( const part of data.viewItem.data.split( /(?={{.*?}})|(?<=}})/ ) ) {
				const node = part.startsWith( '{{' ) ?
					writer.createElement( 'templateTag', { tag: part } ) :
					writer.createText( part );

				writer.insert( node, modelCursor );

				modelCursor = modelCursor.getShiftedBy( node.offsetSize );
			}

			data.modelRange = writer.createRange( position, modelCursor );
			data.modelCursor = data.modelRange.end;
		} );
	} );

	editor.conversion.for( 'editingDowncast' ).elementToElement( {
		model: 'templateTag',
		view: ( element, { writer } ) => writer.createEmptyElement( 'span', {
			'data-template-tag': element.getAttribute( 'tag' )
		} )
	} );

	editor.conversion.for( 'dataDowncast' ).elementToElement( {
		model: 'templateTag',
		view: ( element, { writer } ) => writer.createUIElement( 'span', null, domDocument => {
			return domDocument.createTextNode( element.getAttribute( 'tag' ) );
		} )
	} );
}

function isParagraphable( position, nodeOrType, schema ) {
	const context = schema.createContext( position );

	// When paragraph is allowed in this context...
	if ( !schema.checkChild( context, 'paragraph' ) ) {
		return false;
	}

	// And a node would be allowed in this paragraph...
	if ( !schema.checkChild( context.push( 'paragraph' ), nodeOrType ) ) {
		return false;
	}

	return true;
}

function wrapInParagraph( position, writer ) {
	const paragraph = writer.createElement( 'paragraph' );

	writer.insert( paragraph, position );

	return writer.createPositionAt( paragraph, 0 );
}
```

```css
span[data-template-tag]::after {
	display: inline-block;
	content: attr( data-template-tag );
	background: hsl(60, 100%, 50%);
}
```

**Comment by JanWennrichPCSG** [comment]
Thanks a lot @niegowski, your solution does exactly what I was looking for so desperately!

As this is resolved now, I will close this issue.
