### ISSUE TITLE
Find and Replace

### ISSUE THREAD

**Issue by jianhee** [ckeditor/ckeditor5#10894]
## 📝 Provide detailed reproduction steps (if any)

1. Add content `test test test test`
2. Find and Replace
3. Check `Whole words only` option
4. Find in text `test`

### ✔️ Expected result

Four should be found

### ❌ Actual result

Only two were found

## 📃 Other details

* Browser: Google Chrome 95.0.4638.54
* OS: Windows 10
* First affected CKEditor version: the latest version

![AF126C16-8A00-48b5-BA40-5FAE9B1DB3D9](https://user-images.githubusercontent.com/30864934/143210336-d2ab0618-c17c-4d88-92f6-d2632ffe0865.png)

**Comment by Reinmar** [comment]
This is already fixed on master:

![](https://user-images.githubusercontent.com/156149/143230410-197587b1-b61a-4844-86cf-bebcea7a7940.png)

You can check it in the nightly docs: [https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/find-and-replace.html](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/find-and-replace.html)

We'll release this fix in ~2 weeks.
