### ISSUE TITLE
Create a script for bumping a year in license headers

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10909]
### Why

To avoid copying the same script over and over repositories.

### What

The goal is to create a script that will update the year in license headers in our files.

See: https://github.com/ckeditor/ckeditor5/blob/5e8257ce9ff51265b28cedffdcd3a4e638f3c23b/scripts/bump-year.js

It should accept a few parameters:

- Starting year, some of our projects began in 2003, some later. It should be configurable.
- Glob patterns for sources to update.
- Perhaps a callback for customizing the license.

**Comment by psmyrek** [comment]
@wwalc It looks like we have 2 different sentences in the license header in our repositories:

1. `For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license`
2. `For licensing, see LICENSE.md.`

Can we unify them to have one common global license for all our files?
