### ISSUE TITLE
NL Translation issue in word-count plugin

### ISSUE THREAD

**Issue by ronnievdc** [ckeditor/ckeditor5#10905]
## 📝 Provide detailed reproduction steps (if any)

1. Add the WordCount plugin to the Editor
2. Attach the wordCountContainer to the DOM

### ✔️ Expected result

Text with the Word and Character counters

### ❌ Actual result

Woorden: 0%
Tekens: 0%

### ❓ Possible solution

The translation https://github.com/ckeditor/ckeditor5-word-count/blob/master/lang/translations/nl.po has `0%` instead of `%0`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
It make sense to do a `[\d]+%` search query in all localization to fix similar issues. I'm seeing couple more examples:

*   [https://github.com/ckeditor/ckeditor5/blob/060fb245d6826406b7857c0d4951579002606bf1/packages/ckeditor5-image/lang/translations/pt-br.po#L85](https://github.com/ckeditor/ckeditor5/blob/060fb245d6826406b7857c0d4951579002606bf1/packages/ckeditor5-image/lang/translations/pt-br.po#L85)
*   [https://github.com/ckeditor/ckeditor5/blob/060fb245d6826406b7857c0d4951579002606bf1/packages/ckeditor5-ui/lang/translations/nl.po#L21](https://github.com/ckeditor/ckeditor5/blob/060fb245d6826406b7857c0d4951579002606bf1/packages/ckeditor5-ui/lang/translations/nl.po#L21)
*   https://github.com/ckeditor/ckeditor5/blob/060fb245d6826406b7857c0d4951579002606bf1/packages/ckeditor5-core/lang/translations/ko.po#L41

**Comment by pomek** [comment]
Please, do not modify any `*.po` file as these changes will be lost when downloading translations from Transifex.

The reported issue should be fixed on Transifex:

![image](https://user-images.githubusercontent.com/2270764/144188892-4f4ff3da-fd33-49c0-9f7c-57a6cd7d2930.png)

However, we could improve the download script. It could validate whether a number of variables in context and translated message are the same.

**Comment by mlewand** [comment]
I downloaded the latest translations: mentioned and quite few more occurrences like that were fixed. Good job finding these mistakes! 👏
