### ISSUE TITLE
Indent with list items not wokring

### ISSUE THREAD

**Issue by Hiaslafson** [ckeditor/ckeditor5#10901]
## 📝 Provide detailed reproduction steps (if any)

1. Create a paragraph and indent it. 
2. Create a list below (bullet points) 
3. List should be indented like the paragraph
4. Save everything and reopen the editor
5. Paragraph is still indented but list not
6. When displaying the content in a div indention works (saved correctly with the margin) 
7. CKEditor somehow strips the margin

### ✔️ Expected result

List should look the same after reloading it

### ❌ Actual result

List is not indented and margin is stripped 
In Div:
![image](https://user-images.githubusercontent.com/16558283/143403388-6423c1d5-ea38-4bd2-88c2-3b9526fcb8ea.png)
in CK Editor
![image](https://user-images.githubusercontent.com/16558283/143403965-9e9738c7-4d2e-40ec-bc9e-e10d46b2d02c.png)

### ❓ Possible solution

Allow margin-left on li items

## 📃 Other details

CKEditor5 Angular
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. This issue is know and [we're tracking it here](https://github.com/ckeditor/ckeditor5/issues/6761). If you'd like to add any further details, please add them in the ticket I linked.

I'll close this one as a duplicate.
