### ISSUE TITLE
[Docs] Lack of cross-links between API docs and features documentation

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1090]
In order to make the API browsing less painful we should have correct crosslinks between the relevant API classes and features description.

Here we have it:
 * https://docs.ckeditor.com/ckeditor5/latest/api/heading.html
 * https://docs.ckeditor.com/ckeditor5/latest/api/module_heading_heading-Heading.html

While here, for example, links are missing:
 * https://docs.ckeditor.com/ckeditor5/latest/api/basic-styles.html
 *  https://docs.ckeditor.com/ckeditor5/latest/api/module_basic-styles_bold-Bold.html

**Comment by Reinmar** [comment]
Yeah, we needed a couple of changes:

![image](https://user-images.githubusercontent.com/156149/45705277-700ae800-bb79-11e8-8daf-65af5b175b62.png)

But in general most things were cross-linked.

**Comment by wwalc** [comment]
🎉
