### ISSUE TITLE
Creating table header row scroll the page up

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#10902]
## 📝 Provide detailed reproduction steps (if any)

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/table.html#basic-table-features
2.  Right click on table and create header row

### ✔️ Expected result

Header row gets created

### ❌ Actual result

_Header row gets created and page scrolls up._

![](https://user-images.githubusercontent.com/5314687/143420139-a6178f77-8ab2-4f7d-9c87-564a5183210a.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Chrome (Firefox works ok)
*   OS: Any
*   First affected CKEditor version: …
*   Installed CKEditor plugins: table

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
This issue is not reproducible anymore.
