### ISSUE TITLE
mentions - after typing space - list disappears

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#10917]
## 📝 Provide detailed reproduction steps (if any)

Attached is a video demonstrating the problem
The demonstration of the problem was done from the editor's documentation
https://user-images.githubusercontent.com/59637560/143765275-9aed6993-8cd1-4b09-bb7f-3714b0ca1b57.mp4

### ✔️ Expected result

The list will continue to be displayed, taking into account the space typed

### ❌ Actual result
The list disappears

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. This issue is known and there's a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/9741). If you'd like to see it implemented, please add  👍   and any other information you find important.
I'll close this one as a duplicate.
