### ISSUE TITLE
Make it possible to disable CKEditor editing and filtering my HTML

### ISSUE THREAD

**Issue by philip-sorokin** [ckeditor/ckeditor5#10916]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

I want to write my HTML with classes and other attributes without any filtering. I handle the validation and filtration by myself. CKEditor 5 documentation suggest me overriding the model with a custom plugin. I would like to see the example of complete implementation such a plugin, that disables the editor to strip my elements and attributes.

**Comment by FilipTokarski** [comment]
Hi, did you try [General HTML Support plugin](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html)?

**Comment by Tarek-Adra** [comment]
any simple implementation with vanilla JS ,  I can't use import

**Comment by ukalpa** [comment]
+1 
Or please extend General HTML Support plugin to make it support some special cases like:

Currently, the editor auto removes empty content element: "<i class="fa fa-icon"></i>" which is pretty common used as icons in Bootstrap

**Comment by derekvawdrey** [comment]
+1

**Comment by Witoso** [comment]
I will close this issue because there's a [General HTML Support plugin](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html) that can handle most cases, [as well as a config option to keep empty inline elements](https://ckeditor.com/docs/ckeditor5/latest/api/module_html-support_generalhtmlsupportconfig-GeneralHtmlSupportConfig.html#member-allowEmpty).

**Comment by pulse-mind** [comment]
I do not consider it as the same. General HTML support plugin is great but does not allow to disable filtering HTML. It allows to redefine tags...

**Comment by pulse-mind** [comment]
This is what I did : 
In src/ckeditor.js I have 
```
// Editor configuration.
Editor.defaultConfig = {
	htmlSupport: {
		allow: [
			{
				name: /.*/,
				attributes: true,
				classes: true,
				styles: true
			}
		]
	},
	toolbar: {
		items: [
			'undo',
			'redo',
			'|',
			'heading',
...
```
I run ```npm run build```. 
I use the sample.html to test it quickly. I click on the Source button to display the source and I add:
```
<ul>
<li>First li</li>
{% if my_condition %}<li> SOME TEXT HERE </li>{% endif %}
</ul>
```
Because it is a template that is used by an application.
At the end I get : 
```
<ul>
    <li>
        First li
    </li>
    <li>
        SOME TEXT HERE
    </li>
</ul>
```
The templating data are gone because it is in the ul. In some other cases it works fine without adding htmlSupport...

**Comment by Witoso** [comment]
The example that you showed [is not valid HTML](https://validator.w3.org/nu/#textarea) according to its spec:

> **Text not allowed in element** [**`ul`**](https://html.spec.whatwg.org/multipage/#the-ul-element) **in this context.**
> 
> Content model for element [`ul`](https://html.spec.whatwg.org/multipage/#the-ul-element): Zero or more [`li`](https://html.spec.whatwg.org/multipage/#the-li-element) and [script-supporting](https://html.spec.whatwg.org/multipage/#script-supporting-elements-2) elements.

The editor will not preserve it in the list.

**Comment by pulse-mind** [comment]
Yes I know, but I am looking for a solution, and this is also why I was interesting by the possibility to "disable CKEditor editing and filtering my HTML".

**Comment by Witoso** [comment]
At the current moment, I think it's safe to say we will not implement this feature in the foreseeable future. The GHS plugin is our main proposal for preserving HTML. The editor itself needs to conform to the HTML standards, otherwise core editing features like typing, selection, etc. would require some costly edge cases handling.

**Comment by Witoso** [comment]
> It's a valid HTML, but this is what I get (i tag need not have a separate closing tag)

It's not, per [W3 HTML checker](https://validator.w3.org/nu/#textarea):

`Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.`

The following markup works correctly with the `allowEmpty`:

```html
<ul>
    <li>
        <i class="ti ti-check"></i> Learn From Expert in details
    </li>
    <li>
        <i class="ti ti-check"></i> 16 Chapters included
    </li>
    <li>
        <i class="ti ti-check"></i> eBook includes iBooks, PDF &amp; ePub versions
    </li>
    <li>
        <i class="ti ti-check"></i> Audio book with every purchase
    </li>
</ul>
```

**Comment by SilverFoxA** [comment]
@Witoso Would there be a workaround for the 2nd use case? where we can add loops or conditions?

**Comment by SilverFoxA** [comment]
I have used a code editor, if anyone is interested - [React Ace](https://github.com/securingsincity/react-ace)

**Comment by Witoso** [comment]
>  @Witoso Would there be a workaround for the 2nd use case? where we can add loops or conditions?

For such input, you could try to utilize [the HTML embed feature](https://ckeditor.com/docs/ckeditor5/latest/features/html/html-embed.html).

**Comment by replaysMike** [comment]
I too would like the option to disable HTML validation, same use case as @SilverFoxA - an email template editor. It messes up the HTML when using Handlebars type tags such as:

```
<table>
<tbody>
{{#rows}}
 <tr><td>{{name}}</td><td>{{email}}</td></tr>
{{/rows}}
</tbody>
</table>
```
gets modified by the editor as
```
<p>
        <br>
{{#rows}}{{/rows}}
</p>

<table>
<tbody>
 <tr><td>{{name}}</td><td>{{email}}</td></tr>
</tbody>
</table>
```

**Comment by FocusThen** [comment]
@Witoso I am deeply sorry to adding directly however, those HTMLS above let's say "is not vaild HTML" how about this, a tag behaviour changes completely given html,

```html
  <div class="buttons">
      <a class="btn btn-primary" href=""
        ><span>CEPTETEB</span> İNTERNET ŞUBESİ</a
      >
      <div class="buttons-hover" style="opacity: 0">
        <span class="label">Bireysel Giriş</span>
        <a class="btn-header" href="">
          <img src="/_assets/dist/images/icons/password.svg" class="me-3" />
          <span class="text">Parola Al / Unuttum</span>
        </a>
        <a class="btn-header" href="">
          <img src="/_assets/dist/images/icons/mobile.svg" class="me-3" />
          <span class="text">CEBTETEB’i Hemen İndir</span>
        </a>
        <a class="btn-header" href="">
          <img
            src="/_assets/dist/images/icons/clipboard-tick.svg"
            class="me-3"
          />
          <span class="text">Müşteri Ol</span>
        </a>
        <span class="label">Kurumsal Giriş</span>
        <a class="btn-header" href="">
          <img src="/_assets/dist/images/icons/password.svg" class="me-3" />
          <span class="text">Parola Al / Unuttum</span>
        </a>
        <a class="btn-header" href="">
          <img src="/_assets/dist/images/icons/mobile.svg" class="me-3" />
          <span class="text">CEBTETEB’i Hemen İndir</span>
        </a>
        <a class="btn-header" href="">
          <img
            src="/_assets/dist/images/icons/clipboard-tick.svg"
            class="me-3"
          />
          <span class="text">Müşteri Ol</span>
        </a>
      </div>
      <div
        class="hamburger hamburger--squeeze ml-auto"
        tabindex="0"
        aria-label="Menu"
        role="button"
        aria-controls="navigation"
      >
        <div class="hamburger-box">
          <div class="hamburger-inner"></div>
        </div>
      </div>
    </div>
```

result like this. (I tried in official docs as well)


```html
    <div class="buttons">
      <p>
        <a class="btn btn-primary" href=""
          ><span>CEPTETEB</span> İNTERNET ŞUBESİ</a
        >
      </p>
      <div class="buttons-hover" style="opacity: 0">
        <span class="label">Bireysel Giriş</span>
        <a class="btn-header" href=""
          ><img class="me-3" src="/_assets/dist/images/icons/password.svg" />
          <span class="text">Parola Al / Unuttum</span>
          <img class="me-3" src="/_assets/dist/images/icons/mobile.svg" />
          <span class="text">CEBTETEB’i Hemen İndir</span>
          <img
            class="me-3"
            src="/_assets/dist/images/icons/clipboard-tick.svg"
          />
          <span class="text">Müşteri Ol</span> </a
        ><span class="label">Kurumsal Giriş</span>
        <a class="btn-header" href=""
          ><img class="me-3" src="/_assets/dist/images/icons/password.svg" />
          <span class="text">Parola Al / Unuttum</span>
          <img class="me-3" src="/_assets/dist/images/icons/mobile.svg" />
          <span class="text">CEBTETEB’i Hemen İndir</span>
          <img
            class="me-3"
            src="/_assets/dist/images/icons/clipboard-tick.svg"
          />
          <span class="text">Müşteri Ol</span>&nbsp;</a
        >
      </div>
      <div
        class="hamburger hamburger--squeeze ml-auto"
        tabindex="0"
        aria-label="Menu"
        role="button"
        aria-controls="navigation"
      >
        <div class="hamburger-box">
          <div class="hamburger-inner">&nbsp;</div>
        </div>
      </div>
    </div>
```

**Comment by olstjos** [comment]
ok so a workaround we disabled the tableInsert plugin, not sure if this is pure ck5 or where this plugin comes from but by disabling it, we no longer have a table mangling problem , reduced severity of the mangling of markup. 

![Image](https://github.com/user-attachments/assets/9b4413d2-c46e-4b6a-8852-75c1abf3495d)
