### ISSUE TITLE
DecoupledEditor is not Defined  on Chrome( 72.0.3626.121   32bit)

### ISSUE THREAD

**Issue by Chainery** [ckeditor/ckeditor5#10918]
## 📝 Provide detailed reproduction steps (if any)

1.  On other version Chrome，it is  normal , but on Chrome ( 72.0.3626.121   32bit), it  occur a error  that DecoupledEditor is not Defined

## 📃 Other details

* Browser: Chrome ( 72.0.3626.121   32bit)
* OS: Win10
* First affected CKEditor version:CKEditor 5 decoupled document editor build v29.0.0

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Chainery** [comment]
And  i try again ； download offical demo   , open on Chrome( 72.0.3626.121 32bit) , it is orccur same issue. 
![image](https://user-images.githubusercontent.com/18424249/143798544-adb0776a-dce5-4113-ad7e-d0329af60e35.png)

**Comment by FilipTokarski** [comment]
Hi, I checked it and had no problems with the zip package version of CKEditor 5 on Chrome. Could you add some more information and precise steps to reproduce this issue?
On a side note, Chrome 72 is quite an old version, did you try updating to the latest?

**Comment by Chainery** [comment]
@FilipTokarski   Thanks a billion ; Latest Chrome no Problem . i said **on this version( 72.0.3626.121 32bit)** occur this issue. Cause   some user use this version of Chrome.  So we should update Chrome, this not CKEditor5's  problem?

**Comment by FilipTokarski** [comment]
Yes the problem is not with the editor itself, so we recommend to use the latest version of Chrome.
I'll close the ticket as solved.

**Comment by Chainery** [comment]
@FilipTokarski  Thank you again.
