### ISSUE TITLE
Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by isyoungxl** [ckeditor/ckeditor5#10927]
## 📝 Provide detailed reproduction steps (if any)

1.I use the Multi-root editor in vue2. Before that, the Inline editor can be used normally
2. I follow the example to quote the code to the project

![image](https://user-images.githubusercontent.com/40622507/144194961-e9911391-54c2-44c2-8442-aa8ca114b480.png)

The following error occurred：

![image](https://user-images.githubusercontent.com/40622507/144195054-a8338606-863b-41d7-acb5-18f212c8b2f5.png)
3. This is my webpack configuration
![image](https://user-images.githubusercontent.com/40622507/144196147-4559a21c-4402-4096-b32f-cab2f1882869.png)

### ✔️ Expected result

_What is the expected result of the above steps?_
Can be used normally
### ❌ Actual result
Report an error
_What is the actual result of the above steps?_
Report an error
### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: chrome
* OS: windows 10
* First affected CKEditor version: CKEditor5
* Installed CKEditor plugins: @ckeditor/ckeditor5-build-classic、@ckeditor/ckeditor5-build-inline、@ckeditor/ckeditor5-vue2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Most probably, the `file-loader` handles CKEditor 5 icons. You need to exclude CKEditor 5 assets from this loader. But it's hard to say more as we don't see the full webpack config.

**Comment by isMrcat** [comment]
I think it may be the introduction of SVG or icon. I hope to see a more complete configuration

**Comment by isMrcat** [comment]
`let name = 'youngxl'`

**Comment by isyoungxl** [comment]
> Most probably, the `file-loader` handles CKEditor 5 icons. You need to exclude CKEditor 5 assets from this loader. But it's hard to say more as we don't see the full webpack config.

Sorry to let you check in this way

Please see attachment：

[webpack.base.conf.zip](https://github.com/ckeditor/ckeditor5/files/7632271/webpack.base.conf.zip)

**Comment by ZSH-95** [comment]
I think it may be the introduction of SVG or icon. I hope to see a more complete configuration

**Comment by isyoungxl** [comment]
![image](https://user-images.githubusercontent.com/40622507/144204881-fda9b611-2f79-4d0d-b488-fb9984805df9.png)

**Comment by pomek** [comment]
The regular expression used for testing a path for the `raw-loader` should be specified as patterns to `exclude` for the `file-loader`.

**Comment by isyoungxl** [comment]
> The regular expression used for testing a path for the `raw-loader` should be specified as patterns to `exclude` for the `file-loader`.

Is it this way?
`

       {
        test: /\.(svg)(\?.*)?$/,
        exclude: [
          /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
          /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,
        ],
        use: [
          {
            loader: 'file-loader',
            options: {
              name: utils.assetsPath("img/[name].[hash:7].[ext]")
            }
          }
        ]
      },
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        use: ['raw-loader'] 
      }
`

Doing so does not seem to report an error，But the browser page cannot be refreshed, did I do something wrong?

![image](https://user-images.githubusercontent.com/40622507/144345373-418c4285-3805-4d8e-a192-8415e9e5b5a4.png)

Unless these codes are commented out, they cannot be refreshed.

![image](https://user-images.githubusercontent.com/40622507/144345469-94a65e12-348e-4fd0-9d00-d73cdbd6a4c5.png)

**Comment by pomek** [comment]
> Is it this way?

Almost, this `/ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,` is not needed.

**Comment by isyoungxl** [comment]
> > Is it this way?
> 
> Almost, this `/ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,` is not needed.

I have tried it, and removing this sentence has the same effect.

This is my package.json，

`

    "@ckeditor/ckeditor5-build-classic": "^31.0.0",
    "@ckeditor/ckeditor5-build-inline": "^31.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^26.1.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^26.1.0",
    "@ckeditor/ckeditor5-vue2": "^1.0.5",


`

This situation occurs when I perform initialization.


`

initEditor() {
      MulitirootEditor.create(
        {
          header: document.querySelector('#header'),
          content: document.querySelector('#content'),
          footerleft: document.querySelector('#footer-left'),
          footerright: document.querySelector('#footer-right'),
        },
 .....)
 }


`

**Comment by taf2** [comment]
Is there not just a simple way to include plugins... like:

<script type="module" src="plugin?"></script>
... why does it have to be so hard... can't these plugins just be hosted on cdn?

**Comment by range-of-motion** [comment]
@isyoungxl how did you ever fix this?

**Comment by Jyboer13** [comment]
Hello, @isyoungxl! How did you fix it? I am trying to fix this in React but no luck

**Comment by xuxusheng** [comment]
same+1

**Comment by Master-Y0da** [comment]
same problem here...I spend almost a week trying to solve this and my project is completly stoped. Please any help!

**Comment by mertvoo** [comment]
bende de aynı sorun var

**Comment by huzedong2015** [comment]
> i have the same problem

1、[click href](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html#editor-example-configuration)
2、Expand collapse
3、copy code

**Comment by mertvoo** [comment]
> > i have the same problem
> 
> 1、[click href](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html#editor-example-configuration)
> 2、Expand collapse
> 3、copy code

I guess I can't use it. This doesn't work for me

**Comment by huzedong2015** [comment]
> > > i have the same problem
> > 
> > 
> > 1、[click href](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html#editor-example-configuration)
> > 2、Expand collapse
> > 3、copy code
> 
> I guess I can't use it. This doesn't work for me

[ckeditor5-build-multi](https://github.com/huzedong2015/ckeditor5-build-multi)I uploaded an example

**Comment by mertvoo** [comment]
> > > > i have the same problem
> > > 
> > > 
> > > 1、[click href](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html#editor-example-configuration)
> > > 2、Expand collapse
> > > 3、copy code
> > 
> > 
> > I guess I can't use it. This doesn't work for me
> 
> [ckeditor5-build-multi](https://github.com/huzedong2015/ckeditor5-build-multi)I uploaded an example

Thanks, i reviewed it.  I'm using Laravel with inertia/vuejs. Is there anything extra I need to do for this?

**Comment by huzedong2015** [comment]
> > > > > i have the same problem
> > > > 
> > > > 
> > > > 1、[click href](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html#editor-example-configuration)
> > > > 2、Expand collapse
> > > > 3、copy code
> > > 
> > > 
> > > I guess I can't use it. This doesn't work for me
> > 
> > 
> > [ckeditor5-build-multi](https://github.com/huzedong2015/ckeditor5-build-multi)I uploaded an example
> 
> Thanks, i reviewed it. I'm using Laravel with inertia/vuejs. Is there anything extra I need to do for this?

I don't continue to develop. If you need to use it, you can consider publishing build to NPM and then installing it
[Introduce the multi-root editor build](https://github.com/ckeditor/ckeditor5/issues/11493)

**Comment by ilearnio** [comment]
I have the same issue with vite. The debugger shows that it doesn't load the icons properly

![image](https://github.com/ckeditor/ckeditor5/assets/14331216/ab0898c0-83c1-4d03-9c96-4a0d5e7ccab2)

**Comment by Witoso** [comment]
@ilearnio do you use [our Vite plugin](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html)?

**Comment by ilearnio** [comment]
@Witoso Yes I was using the plugin

**Comment by oscarcornejo** [comment]
Hi! I have the same issue than @ilearnio 🤔

**Comment by VaclavS16** [comment]
Hi, I had the same problem with Vite and ckeditor, solution was move vite plugin vite-svg-loader after plugin ckeditor5 in vite. Here is my vite configuration.

`
import { createRequire } from 'node:module';
import { defineConfig } from 'vite';
import vue from "@vitejs/plugin-vue";
import svgLoader from "vite-svg-loader";
import ckeditor5 from "@ckeditor/vite-plugin-ckeditor5";

const require = createRequire( import.meta.url );

export default defineConfig( {
  plugins: [
    vue(),
    ckeditor5({ theme: require.resolve("@ckeditor/ckeditor5-theme-lark") }),
    svgLoader(),
  ],
} );
`

**Comment by reccrea** [comment]
> Hi, I had the same problem with Vite and ckeditor, solution was move vite plugin vite-svg-loader after plugin ckeditor5 in vite. Here is my vite configuration.
> 
> ```
> import { createRequire } from 'node:module';
> import { defineConfig } from 'vite';
> import vue from "@vitejs/plugin-vue";
> import svgLoader from "vite-svg-loader";
> import ckeditor5 from "@ckeditor/vite-plugin-ckeditor5";
> 
> const require = createRequire( import.meta.url );
> 
> export default defineConfig( {
>   plugins: [
>     vue(),
>     ckeditor5({ theme: require.resolve("@ckeditor/ckeditor5-theme-lark") }),
>     svgLoader(),
>   ],
> } );
> ```

Hi,I used your method and the editor loaded normally, but text cannot be entered in the editor.

**Comment by gregg-cbs** [comment]
Im in a new create react app.. The react ckeditor doesnt allow the 'editor-classic' editor. So i tried this in a useEffect but I see this error:
```
  ClassicEditor.create(container, {
    plugins: [
      Essentials, Paragraph, Heading, BlockQuote
    ],
    toolbar: ["heading", "blockQuote"]
  })
```

**Comment by Witoso** [comment]
> The react ckeditor doesnt allow the 'editor-classic' editor.

Could you share your full setup?

**Comment by reccrea** [comment]
> > The react ckeditor doesnt allow the 'editor-classic' editor.
> 
> Could you share your full setup?

```
// vite.config.ts

import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

import svgLoader from 'vite-svg-loader'
import ckeditor5 from '@ckeditor/vite-plugin-ckeditor5'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
    ckeditor5({ theme: require.resolve('@ckeditor/ckeditor5-theme-lark') }),
    svgLoader()
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})


// App.vue

<template>
  <div class="app-container">
    <ckeditor :editor="InlineEditor" v-model="editorData" :config="editorConfig"></ckeditor>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { InlineEditor } from '@ckeditor/ckeditor5-editor-inline'

import { Essentials } from '@ckeditor/ckeditor5-essentials'
import { Bold, Italic } from '@ckeditor/ckeditor5-basic-styles'
import { Link } from '@ckeditor/ckeditor5-link'
import { Paragraph } from '@ckeditor/ckeditor5-paragraph'

const editorData = ref('<p>hello world</p>')

const editorConfig = ref({
  plugins: [Essentials, Bold, Italic, Link, Paragraph],

  toolbar: {
    items: ['bold', 'italic', 'link', 'undo', 'redo']
  }
})
</script>

<style lang="less" scoped></style>
```

![QQ截图20231207143034](https://github.com/ckeditor/ckeditor5/assets/56736458/645b567b-819d-477c-abdc-489c0e6e6636)
![QQ截图20231207143105](https://github.com/ckeditor/ckeditor5/assets/56736458/420c2d14-1574-4c5a-b678-924e12767544)
