### ISSUE TITLE
[FF] Link's URL input incercepts arrow keys despite being closed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1092]
The link balloon is closed and still the up/down arrow keys get locked in this balloon (check the left top corner of the screen):

![image](https://user-images.githubusercontent.com/156149/41658598-28a562b6-7497-11e8-91c9-2581f6a3e54d.png)

This is the same autocompletion panel:

![image](https://user-images.githubusercontent.com/156149/41658612-37e79c6c-7497-11e8-8e3a-221315ff1e85.png)

I'm not 100% sure how to reproduce it, but creating a link, submitting it and then pressing up/down around the content usually triggers it.

@Mgsy could you try to reproduce it?

**Comment by Mgsy** [comment]
> @Mgsy could you try to reproduce it?

I'm able to reproduce it. Here are exact steps:

1. Open the article sample.
1. Put the caret inside the link.
1. Edit it.
1. Click on the save button.
1. Press <kbd>Arrow up</kbd>.

**Comment by FilipTokarski** [comment]
I tried to reproduce it but with no success. Pressing `Arrow up` moves the caret up, just like you would expect it. I guess we can close this.
