### ISSUE TITLE
Reopen CKE5 with Table i get empty figure tags at the End of the Table

### ISSUE THREAD

**Issue by skerbis** [ckeditor/ckeditor5#10928]
## 📝 Provide detailed reproduction steps (if any)

Saving Table i get empty figure tags at the End of the Table when i reopen the Editor. 
When I look into the dataset this empty figure tags do not exist. So they are added when i open the Editor 

Version: v31

Example:

```html
<figure class="table">
    <table>
        <tbody>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        </tbody>
    </table>
</figure>
```

When I reopen the Dataset in the Editor I get: 

```html
<figure class="table">
    <table>
        <tbody>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        </tbody>
    </table>
</figure>
<figure>
    &nbsp;
</figure>
```

this 
```
<figure>
    &nbsp;
</figure>
```

Will be added each time I open the Editor. 
It only happens on tables.

**Comment by FilipTokarski** [comment]
Hi, could you share more details on your editor configuration (which plugins do you use, do you have any custom code, etc.)? Also, do you use General HTML Support plugin (and if yes, how is it configured)?

It reminds me of this case - https://github.com/ckeditor/ckeditor5/issues/10279#issuecomment-893372820

**Comment by skerbis** [comment]
hi @FilipTokarski 
Yes it looks like #10279 and
https://github.com/ckeditor/ckeditor5/commit/634d4241544a7278a085c820720c8abb35f426c3

**Comment by FilipTokarski** [comment]
Thanks for confirming. The issue was fixed in this iteration (you can check on latest `master`) and will be released in the next editor version, which is planned for next week. 
I'll close this ticket for now and if you encounter this problem after the next release, please let us know.
