### ISSUE TITLE
Weird error in manual tests

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1093]
```
inject.preload.js:373 GET blob:http://localhost:8125/a1113310-7be6-4e12-9620-fc3b31dca527 0 ()
splitSelector.splitSelector @ inject.preload.js:373
__webpack_require__ @ bootstrap 459d30130528313280ec:19
(anonymous) @ common.js:103
__webpack_require__ @ bootstrap 459d30130528313280ec:19
exports.textToRegExp @ bootstrap 459d30130528313280ec:62
(anonymous) @ bootstrap 459d30130528313280ec:62
```

![image](https://user-images.githubusercontent.com/156149/41659107-a80d653e-7498-11e8-8ad6-081109537577.png)

Does anyone see it too?

**Comment by alexeremeev** [comment]
adblock plus bug... i've got same issue on some sites and even on my project running locally with disabled adblock. Try other browsers and see there'll be no errors

**Comment by Reinmar** [comment]
Thanks for the info! Confirmed.
