### ISSUE TITLE
How to trigger an event just before content gets pasted into the editor?

### ISSUE THREAD

**Issue by timtempel** [ckeditor/ckeditor5#10946]
I'm trying to sanitise pasted content before it gets added to the editor. This is a feature in CK4 that I've been using and now want to recreate in CK5. 

My code looks like this but unfortunately triggers too late, the content is already pasted. Can somebody guide me into the right direction? Any help is much appreciated!

`.then(
                editor => {
                    editors[element].editing.view.document.on('paste', (evt, data) => {
console.log('trigger');
});`

**Comment by dkrahn** [comment]
I have not tried to implement it, but ckeditor5 team has made a detailed deep dive guide into to the paste pipeline which may help you.
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/clipboard.html

**Comment by timtempel** [comment]
> I have not tried to implement it, but ckeditor5 team has made a detailed deep dive guide into to the paste pipeline which may help you. https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/clipboard.html

Thank you for reaching out. I've looked into that article and this should indeed contain the solution somewhere. However I'm not fully understanding how this works. This snippet from the article for example is throwing a "UpcastWriter undefined". Shouldn't that be included in the core build of CK5? I don't understand what I'm doing wrong here.

`const writer = new UpcastWriter( viewDocument );
const text = writer.createText( 'foo!' );

writer.appendChild( text, someViewElement );`

**Comment by FilipTokarski** [comment]
Hi, not sure what exactly you want to do, but you can intercept the paste event with code like this:

```js
editor.editing.view.document.on( 'clipboardInput', ( evt, data ) => {
        console.log( 'Triggered before pasting!' );

        console.log( evt );
	console.log( content );
} );

```

**Comment by timtempel** [comment]
@FilipTokarski Thanks for reaching out! That is exactly what I'm trying to achieve indeed and I actually have been using that event snippet as well. However, the results seem to show me that the pasting is still triggered before this scripts gets triggered.

The usecase I want to achieve is as follows; when pasting content into the editor, it needs to be sanitised. For example styling of tables and inline color needs to be stripped. This should only happen for the pasted text, not for the already present content. Our users should be able to alter styling of elements but only if they were created from the editor itself, not when it was pasted from an external source. This was working in CK4 in the paste event but I can't reproduce it in CK5 so far:

`
.then(
                editor => {
editors[element].editing.view.document.on( 'clipboardInput', ( evt, data ) => {               
                        var divContentContainer = document.createElement('div');
                        divContentContainer.innerHTML = data.dataTransfer.getData('text/html');

                        //Remove inline style from table, th and td elements from pasted content
                        var elementTableComponents = divContentContainer.querySelectorAll('table,td,th'), i;
                        for (i = 0; i < elementTableComponents.length; ++i) {
                            elementTableComponents[i].style = '';
                        }

                        // Remove inline color style from pasted content
                        var elementComponents = divContentContainer.querySelectorAll('p,span,a,h2,h3,h4,h5,h6,table,td,th,ul,ol,li'), i;
                        for (i = 0; i < elementComponents.length; ++i) {
                            elementComponents[i].style.color = '';
                        }

                        // Remove anchors from pasted content if no href is present
                        var elementAnchorComponents = divContentContainer.querySelectorAll('a'), i;
                        for (i = 0; i < elementAnchorComponents.length; ++i) {
                            if (!$(elementAnchorComponents[i]).attr('href')) {
                                $(elementAnchorComponents[i]).contents().unwrap();
                            }
                        }

                        editors[element].setData(divContentContainer.innerHTML);

                    } );
}`

The outcome of above code is that the pasted content gets pasted twice. The original content and then the sanitised version. 
**Expected behaviour:**
`<p>testing</p>`

**Actual behaviour**
```
<p style="color:red;">testing</p>
<p>testing</p>
```

**Comment by dkrahn** [comment]
From what I could understand from this part of the docs(https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/clipboard.html#handling-clipboard-input-differently), you should not use the setData, but instead, set it's content in the data variable using `data.content = viewContent;`. Being `viewContent = divContentContainer.innerHTML`.
Does this look right @FilipTokarski ?

**Comment by timtempel** [comment]
> `data.content = viewContent;`. Being `viewContent = divContentContainer.innerHTML`

I've tried that but get this error in return unfortunately: 
`r.content.getChildren is not a function`

**Comment by timtempel** [comment]
Small update, I managed to "solve" the duplication issue by stopping the paste event right after the setData() event has taken place. I'm not sure if this is the way to go but it seems to do the trick:

`editors[element].setData(divContentContainer.innerHTML);
                        evt.stop();`

**Comment by timtempel** [comment]
Closing the issue as the original question has been resolved. Creating a new issue to address the problem with setting the paste data

**Comment by johnflux** [comment]
instead of:

>                        editors[element].setData(divContentContainer.innerHTML);

you should be able to just do:

data.content = divContentContainer.innerHTML
