### ISSUE TITLE
Image upload confirmation tick looks wrong

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1095]
Chrome / Retina

![image](https://user-images.githubusercontent.com/545175/41659903-d2312376-749a-11e8-9076-f696037cb6a8.png)

Note: found in http://localhost:8080/ckeditor5/latest/features/headings.html so it may be a conflict with docs styles.

**Comment by Reinmar** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/1066.
