### ISSUE TITLE
Implement IndentDocumentListCommand

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10974]
## Provide a description of the task

*   Scope
    *   Copy and paste the original `IndentList` implementation
        *   \+ Handle multiple blocks.
    *   Copy and paste tests
        *   \+ Add another few dozens of tests for multiple blocks.

**Comment by Reinmar** [comment]
Special case to take care of:

```
Before:

* A
   * B
  C
  
Outdent "B":

* A
  B
  C
```

**Comment by niegowski** [comment]
Closed in #11057.
