### ISSUE TITLE
Implement DocumentListCommand

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10975]
## Provide a description of the task

*   Scope
    *   Copy and paste the original implementation.
        *   \+ Some bits of the algorithm could be extracted to common utils (Kuba thinks he's been doing some of the things before while implementing the editing).
        *   \+ Probably some branches of the algorithm could be removed.
        *   \+ Adapt for multiple blocks
    *   Copy and paste tests
        *   \+ Adapt for multiple blocks

**Comment by niegowski** [comment]
Closed in #11057.
