### ISSUE TITLE
Drop "resolutions" definitions from package.json

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10979]
## Provide a description of the task

Having the following structure of the project:

```
workspace/
└── ckeditor5
        └── external
            ├── ckeditor5-internal
            ├── collaboration-features
            └── ckeditor-cloud-services-collaboration
```

Causes issues when installing packages (due to workspaces).

The `ckeditor-cloud-services-collaboration` repository defines `devDependencies` that do not match our environment. For an unknown reason, its dependencies have priority over packages from the remaining repositories.

Due to the above, our environment does not work as expected.

Possible solutions:

* Ignore hoisting all packages from `ckeditor-cloud-services-collaboration` (require research)
* Remove all `devDependencies`: https://github.com/cksource/ckeditor-cloud-services-collaboration/blob/c73d6877cccd3c8c00c99510ee76e9edc3e6ecf3/package.json#L57-L97

Workaround:

As for now, we use the [`resolutions`](https://github.com/ckeditor/ckeditor5/blob/master/package.json#L174) option for selecting a version when a package does not know which one is correct. However, it's more like a workaround than a proper fix to the problem.

**Comment by psmyrek** [comment]
Maybe changing the workspace definition to specify the most nested ones first could solve it?

```
"workspaces": {
    "packages": [
        "external/*/packages/*",
        "external/*",
        "packages/*",
        "."
    ]
}
```

**Comment by pomek** [comment]
@psmyrek, I checked the proposal. Unfortunately, it does not help.

**Comment by pomek** [comment]
Done in https://github.com/ckeditor/ckeditor5/commit/68e427257f1e7b2952952a308969c860adb34e99.
