### ISSUE TITLE
Table Toolbar doesn't show when you have nested tables

### ISSUE THREAD

**Issue by letdowncrush** [ckeditor/ckeditor5#10983]
Tested this on latest version at: https://ckeditor.com/docs/ckeditor5/latest/features/table.html

The test HTML is below.

We seem to be able to access the toolbar for the top level table and the inner most table but not for the one in the middle.

```
<figure class="table">
    <table style="background-color:hsl(120, 75%, 60%);">
        <tbody>
            <tr>
                <td>
                    <figure class="table">
                        <table>
                            <tbody>
                                <tr>
                                    <td style="background-color:hsl(0, 0%, 100%);">
                                        <figure class="table">
                                            <table>
                                                <tbody>
                                                    <tr>
                                                        <td style="width:500px;">TEST</td>
                                                        <td style="background-color:hsl(180, 75%, 60%);width:500px;">Here is some text&nbsp;</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="width:500px;">TEST</td>
                                                        <td style="background-color:hsl(180, 75%, 60%);width:500px;">Here is more text</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </figure>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </figure>
                </td>
            </tr>
        </tbody>
    </table>
</figure>
```

**Comment by FilipTokarski** [comment]
For me it's the most outer table which has no toolbar when selected:


https://user-images.githubusercontent.com/34380544/148040078-05d7abdc-4255-4b3b-a50c-44ae21d2c164.mp4

**Comment by letdowncrush** [comment]
any ideas if / when you might be able to look at a fix for this?

**Comment by jestrick123** [comment]
Hello also looking for an issue to above - would you be able to advise when this might get looked at please.

**Comment by Reinmar** [comment]
I assume that when a table is selected, it should show just one option: "table properties". All other options do not make sense (col menu, row menu, merge, cell props).

Isn't it enough then to configure [`config.table.tableToolbar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-tableToolbar) to contain that option? NOTE: There are two configuration options for table toolbars. The one we see on the screencast above is the [content toolbar](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-contentToolbar).

It may resolve this issue, although I have a feeling that it needs a more holistic review of the UX around table toolbars in such cases so I'd keep this ticket open
