### ISSUE TITLE
`model.insertContent()` method does not work without passing a position

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#10993]
## 📝 Provide detailed reproduction steps (if any)

1. Open an editor instance.
2. Run
```js
editor.model.change( writer => {
	editor.model.insertContent( writer.createText( 'x' ), editor.model.document.getRoot(), 2 );
} );
```
in the console.

### ✔️ Expected result

`x` was inserted to the editor. According to [`model.insertContent()` docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent) such shorthand for `editor.model.insertContent( writer.createText( 'x' ), writer.createPositionAt( editor.model.document.getRoot(), 2 ) );` should work.

### ❌ Actual result

There is an error breaking the editor in the console instead:

```
snippet.js:4 Uncaught CKEditorError: model-selection-setto-required-second-parameter
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-selection-setto-required-second-parameter
    at u.setTo (snippet.js:4)
    at new u (snippet.js:4)
    at ft.createSelection (snippet.js:4)
    at ft._ (snippet.js:4)
    at ft.fire (snippet.js:4)
    at ft.<computed> [as insertContent] (snippet.js:4)
    at Object.callback (<anonymous>:2:15)
    at ft._runPendingChanges (snippet.js:4)
    at ft.change (snippet.js:4)
    at <anonymous>:1:14
```

### ❓ Possible solution

@niegowski suggests there is an invalid integration with the list feature.

## 📃 Other details

* Browser: any
* OS: any
* First affected CKEditor version: already present in `20.0.0`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
It's a duplicate - #6838.
