### ISSUE TITLE
Source maps are not loaded in manual and automated tests

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#11006]
## 📝 Provide detailed reproduction steps (if any)

It looks like after upgrading to webpack v5, it is not possible to load source maps in manual tests, because the path to the `.js.map` file is incorrect in the generated source file.

Example:

After calling `yarn manual -f alignment` to start manual tests server for the `ckeditor5-alignment` package, on the bottom of the generated `build/.manual-tests/ckeditor5-alignment/tests/manual/alignment.js` file there is the `//# sourceMappingURL` comment, that should point to the source map. Currently, it contains the invalid path: `//# sourceMappingURL=ckeditor5-alignment/tests/manual/alignment.js.map`, so the HTTP request from the browser is `/ckeditor5-alignment/tests/manual/ckeditor5-alignment/tests/manual/alignment.js.map` which does not exist.

It looks like the URL to the source map file should be just the file name, because the source map is located in the same directory as the test file, e.g. `//# sourceMappingURL=alignment.js.map`.

### ✔️ Expected result

Source maps work in manual tests.

### ❌ Actual result

Source maps does not work in manual tests.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
Configuring [`output.sourceMapFilename`](https://webpack.js.org/configuration/output/#outputsourcemapfilename) in the webpack config as:

```js
output: {
    sourceMapFilename: '[base].map'
}
```

changes the `/# sourceMappingURL` comment in the generated files, so that it only contains the name of the file (e.g. `//# sourceMappingURL=alignment.js.map`), but this generated map file is created in the test root directory `build/.manual-tests` instead of in the package directory, so this does not solve the problem. The path to the map file is still invalid.

**Comment by oleq** [comment]
FYI: It's the same deal in automated tests.
