### ISSUE TITLE
[GHS] Alignment Feature Clashes with General HTML Support

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#11000]
## 📝 Provide detailed reproduction steps (if any)

The following is only a rough sketch, as we use a rather complex custom build of CKEditor (with custom data-processing, many plugins, ...).

1. Create a ClassicEditor instance with GeneralHTMLSupport, Alignment feature, Table Plugin, and (for testing) Source Editing enabled.

2. Possibly not relevant: Configure Alignment feature to use classes:

    ```javascript
    alignment: {
      options: [
        {
          name: "left",
          className: "align--left",
        },
        {
          name: "right",
          className: "align--right",
        },
        {
          name: "center",
          className: "align--center",
        },
        {
          name: "justify",
          className: "align--justify",
        },
      ],
    }
    ```

3. Configure GHS to support all classes/attributes on any element.

4. In Source Code Editing add a table with `<tbody>` as follows:

    ```html
    <table>
      <tbody dir="ltr" align="right" valign="bottom" class="grs xmp" lang="en">
        <tr><td>All Attributes</td></tr>
      </tbody>
    </table>
    ```

5. Leave Source editing, possibly change the text in the table, return to source editing.

### ✔️ Expected result

* Table is kept unchanged.
* Inspector shows attribute `htmlTbodyAttributes` for table element.

### ❌ Actual result

* All attributes from `tbody` are removed.
* Having an inspector, you will see that `htmlTbodyAttributes` are missing.

The `<tbody>` is stored correctly, if you skip the `align` attribute.

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: 31.0.0
* Installed CKEditor plugins:
    * **Alignment**,
    * Autosave,
    * BlockQuote,
    * Bold,
    * CodeBlock,
    * Essentials,
    * Heading,
    * Highlight,
    * Indent,
    * Italic,
    * AutoLink,
    * Link,
    * **GeneralHtmlSupport**,
    * List,
    * Paragraph,
    * PasteFromOffice,
    * RemoveFormat,
    * Strikethrough,
    * **SourceEditing**,
    * Subscript,
    * Superscript,
    * **Table**,
    * TableToolbar,
    * Underline,
    * and several custom plugins, for example for adapting data-processing, configuring HTML Support to our needs, ...

This relates to:

* #9856
* #9914

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Actually, the Alignment plugin isn't necessary here. This also doesn't work:

```
/**
 * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

/* globals console:false, window, document */

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableCaption from '@ckeditor/ckeditor5-table/src/tablecaption';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';

import GeneralHtmlSupport from '../../src/generalhtmlsupport';

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [
			Bold,
			Essentials,
			GeneralHtmlSupport,
			Italic,
			Paragraph,
			SourceEditing,
			Strikethrough,
			Table,
			TableCaption,
			// Alignment
		],
		toolbar: [ 'insertTable', '|', 'bold', 'italic', 'strikethrough', '|', 'sourceEditing' ],
		// alignment: {
		// 	options: [
		// 		{
		// 			name: 'left',
		// 			className: 'align--left'
		// 		},
		// 		{
		// 			name: 'right',
		// 			className: 'align--right'
		// 		},
		// 		{
		// 			name: 'center',
		// 			className: 'align--center'
		// 		},
		// 		{
		// 			name: 'justify',
		// 			className: 'align--justify'
		// 		}
		// 	]
		// },
		htmlSupport: {
			allow: [
				{
					name: /^(figure|table|tbody|thead|tr|th|td|caption|figcaption)$/,
					attributes: true,
					classes: true,
					styles: true
				}
			]
		}
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```

This is odd, because at the same time, the following manual tests work just fine: [https://github.com/ckeditor/ckeditor5/blob/acfb3e0b543add02050340116b2c375ff891ac9e/packages/ckeditor5-html-support/tests/manual/table.js](https://github.com/ckeditor/ckeditor5/blob/acfb3e0b543add02050340116b2c375ff891ac9e/packages/ckeditor5-html-support/tests/manual/table.js)

**Comment by Reinmar** [comment]
OK, the reason why attributes are lost on `<tbody>` is that the markup provided by the origin @mmichaelis does not include the `<figure>` element. This works fine:

```html
<figure class="table">
    <table>
        <tbody class="grs xmp" lang="en" valign="bottom" align="right" dir="ltr">
            <tr>
                <td>
                    All Attributes
                </td>
            </tr>
        </tbody>
    </table>
</figure>
```

**Comment by Reinmar** [comment]
So, the scope of this ticket will be to make sure that `<figure>` is not necessary for `<tbody>`'s attributes to be preserved.

**Comment by Reinmar** [comment]
I hid all my previous comments. I had some problems with browser cache when checking this initially. 

I hope I test it correctly now. What I found is that `Alignment` is necessary. However, it doesn't have to be configured to anything.

The use of `<figure>` or not does not affect this scenario. When `Alignment` is enabled `<tbody>`'s attributes are always lost.

Manual test:

```
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableCaption from '@ckeditor/ckeditor5-table/src/tablecaption';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';

import GeneralHtmlSupport from '../../src/generalhtmlsupport';

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [
			Bold,
			Essentials,
			GeneralHtmlSupport,
			Italic,
			Paragraph,
			SourceEditing,
			Strikethrough,
			Table,
			TableCaption,
			Alignment
		],
		toolbar: [ 'insertTable', '|', 'bold', 'italic', 'strikethrough', '|', 'sourceEditing' ],
		htmlSupport: {
			allow: [
				{
					name: /^(figure|table|tbody|thead|tr|th|td|caption|figcaption)$/,
					attributes: true,
					classes: true,
					styles: true
				}
			]
		}
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```

**Comment by Reinmar** [comment]
It happens only when `align=*` is used.

**Comment by Reinmar** [comment]
We discussed this internally and agreed that we have no idea why this is happening and need some time to research it.

**Comment by niegowski** [comment]
After debugging this issue we found out that the problem is with:
https://github.com/ckeditor/ckeditor5/blob/c4695eae1a22eed293935c901830da0328f68575/packages/ckeditor5-html-support/src/converters.js#L145-L159
it tries to set a model attribute on the collapsed `data.modelRange`, consumes those attributes. The `modelRange` is collapsed because a `tbody` element is not converted directly to the model.

The suggested solution for the above function:
```diff
diff --git a/packages/ckeditor5-html-support/src/converters.js b/packages/ckeditor5-html-support/src/converters.js
index 4de1040f7d..d87e73e60a 100644
--- a/packages/ckeditor5-html-support/src/converters.js
+++ b/packages/ckeditor5-html-support/src/converters.js
@@ -138,21 +138,21 @@ export function attributeToViewInlineConverter( { priority, view: viewName } ) {
  *
  * All matched attributes will be preserved on `htmlAttributes` attribute.
  *
  * @param {module:html-support/dataschema~DataSchemaBlockElementDefinition} definition
  * @param {module:html-support/datafilter~DataFilter} dataFilter
  * @returns {Function} Returns a conversion callback.
 */
 export function viewToModelBlockAttributeConverter( { view: viewName }, dataFilter ) {
        return dispatcher => {
                dispatcher.on( `element:${ viewName }`, ( evt, data, conversionApi ) => {
-                       if ( !data.modelRange ) {
+                       if ( !data.modelRange || data.modelRange.isCollapsed ) {
                                return;
                        }
 
                        const viewAttributes = dataFilter._consumeAllowedAttributes( data.viewItem, conversionApi );
 
                        if ( viewAttributes ) {
                                conversionApi.writer.setAttribute( 'htmlAttributes', viewAttributes, data.modelRange );
                        }
                }, { priority: 'low' } );
        };
```
