### ISSUE TITLE
Docs revamp: Menu/TOC adjustments for docs redesign

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#11001]
A part of: https://github.com/cksource/ckeditor5-internal/issues/1261

Make changes to the menu / TOC structure of CKE5 docs

- [x] Change the top menu
- [x] Split left TOC support section in Installation
- [x] Split main Migration section

**Comment by godai78** [comment]
Working branch https://github.com/ckeditor/ckeditor5/tree/ck/11001

**Comment by Mgsy** [comment]
Closed by #11011.
