### ISSUE TITLE
How to stop editor inserting no-break-space in empty elements?

### ISSUE THREAD

**Issue by shahzebgit** [ckeditor/ckeditor5#11018]
## Provide a description of the task

1. Setup any editor.
2. Enter "hello" and  create an  empty element `p` tag for example
```html
<p>hello</p><p></p>
```
3. use `editor.getData` in console
```html
<p>hello</p><p>&nbsp;</p>
```
is there a way to stop the editor to not insert `&nbsp;` after `editor.getData` ?

## 📃 Other details

* Browser: Chrome
* OS: Unbuntu
* CKEditor version: v31.1.0
* Installed CKEditor plugins: …

**Comment by shahzebgit** [comment]
@FilipTokarski Hey Is there way to configure this or way to stopping adding the `&nbsp;` in empty tag's

**Comment by milfar** [comment]
Hi, were you able to stop the editor from adding &nbsp; in empty tags?

**Comment by R2-D1** [comment]
Same problem, is there a solution?

**Comment by shahzebgit** [comment]
@milfar @R2-D1 Unfortunately AFAIK i didn't find a way to stop it as its a part of their engine you will have to look for NBSP block changes something.
