### ISSUE TITLE
Upgrade puppeteer version for compatibility with M1 devices

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#11014]
## Provide a description of the task

There are issues with running our development environment on M1 devices with arm Node.js binary. If someone is using M1+native Node it will crash on package installation. The reason is that some of the packages are not compatible with arm architecture. One of these packages is `node-sass` which we get rid of recently. The other is puppeteer@8.0.0.

Puppeteer fixed this in version [9.0.0](https://github.com/puppeteer/puppeteer/blob/main/CHANGELOG.md#900-2021-04-21). 

After locally bumping this package, it can now be correctly installed on M1 devices with native Node.js binary and it seems like everything is still working.

If `ckeditor5-dev-docs` will use puppeteer >=9.0.0 then we should be able to run our development environment on M1 devices without any Rosetta 2 workarounds.

**Comment by pomek** [comment]
It looks, we can upgrade to the latest (13.x.x) version. See breaking changes notes:

- https://github.com/puppeteer/puppeteer/releases/tag/v9.0.0
- https://github.com/puppeteer/puppeteer/releases/tag/v10.0.0
- - https://github.com/puppeteer/puppeteer/releases/tag/v11.0.0
- - https://github.com/puppeteer/puppeteer/releases/tag/v12.0.0
- - https://github.com/puppeteer/puppeteer/releases/tag/v13.0.0

**Comment by pomek** [comment]
Scope:

* `package.json` to update: https://github.com/ckeditor/ckeditor5-dev/blob/750d400fa642db7820bfdafa7382d9d2823330e9/packages/ckeditor5-dev-docs/package.json#L11
* Let's bump to the latest and verify whether it works.
