### ISSUE TITLE
Raw html visible prior to being replaced in the editor

### ISSUE THREAD

**Issue by vitality82** [ckeditor/ckeditor5#11021]
## 📝 Provide detailed reproduction steps (if any)

1. open the example: [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)
2. reload the page again and watch closely to the html content of the editor
3. observe how the initial html is moved inside the editor ( reminds of font loading flicker )

### ✔️ Expected result

The page loads, the element is replaced with an RichTextEditor and the elements html is now applied to the editing area of the editor - no visible UI shifts/glitches happened, it was all one smooth page load and editor transition. 

### ❌ Actual result

The html content is visible for a split moment, which creates a non-pleasant UI experience.

### ❓ Possible solution

1. Re-order the timing so that CKEDITOR doesn't try to transform the element and show the content at the same time - this would mean changing dom data prior to being transformed into the editor, probably wouldn't fly.
2. Transition hooks for the editable area?

The idea I'm still going to try:

1. save the html content inside a hidden div just under `<textarea><!-- this is now empty--></textarea>` and setData() after the promise was fulfilled at .create()
2. inspect the current classes in order to see if I can set opacity: 0 to the editing area until CKEDITOR has completed the transformation.

## 📃 Other details

* Browser: Chrome 96
* OS: macOS Big Sur
* First affected CKEditor version: Try the latest Classic or Document editor online (page load and observe)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by vitality82** [comment]
Let me know if this should be an improvement rather and I'll move it (or you can if this makes sense - at all). Thanks!

**Comment by Reinmar** [comment]
You don't need to replace with the editor an existing element. That's convenient for some people (and also for us in the docs) but as you noticed leads to such glitches. You can use [`config.initialData`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData) instead.

**Comment by vitality82** [comment]
Thanks @Reinmar. I agree, but in a classic MVC application the model is passed to the View and any existing content if first inside the HTML (in contrast to SPA applications where everything is JSON based). The way I've worked around this is to store the content inside a visually hidden element (this way it won't be visible at the initial rendering) and implemented a wrapper component around ClassicEditor that retrieves the hidden content and serves it up as 'initialData' for the target element.
