### ISSUE TITLE
Applying styles on a table row/column in Safari breaks when doing it the second time

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#11048]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-and-cell-styling-tools
2. Select a column or a row in a table and apply e.g. background style to it.
3. Select another column or a row and try to do it again.

### ✔️ Expected result

The style is applied to the selection.

### ❌ Actual result

The style is removed from the selection and new style is only applied to the last cell.

https://user-images.githubusercontent.com/1112966/147470661-14c61144-737b-4bd9-a158-463249a24407.mov

## 📃 Other details

* Browser: Confirmed in Safari 15.0 on MacOS, confirmation on iPad/iPhone still needed.
* OS: MacOS, iOS (?)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
No longer reproducible (Safari 15.5):

![](https://user-images.githubusercontent.com/10883184/182839846-127fd54c-4171-49f0-ac45-e25d7733e05a.gif)
