### ISSUE TITLE
Auto-link correction

### ISSUE THREAD

**Issue by net3000** [ckeditor/ckeditor5#11040]
## 📝 Provide detailed reproduction steps (if any)

1. …type www.google.com in content (without http)
2. …inspect the link, you'll find it with href='www.google.com' which is invalid

### ✔️ Expected result

href='https://www.google.com'

### ❌ Actual result

href='www.google.com'

### ❓ Possible solution

Either auto-link would add https:// to the link, or doesn't link www.google.com

**Comment by Reinmar** [comment]
I can confirm this issue. Thank you for reporting it.

**Comment by Reinmar** [comment]
The question we could ask is whether we can assume that a website supports https? Maybe we shouldn't create the link at all in this case.

I'd agree, though, that going with https makes more sense as if someone typed a link, then it's most likely to a well-known website that most likely support https already. Also, this is more future-oriented.

**Comment by net3000** [comment]
It’s safer not to make the link since the user didn’t type a valid link.

 

The second option to automatically add: https means it can still potentially load an invalid URL and user will blame it on editor.

Wael Hallag

Phone: +1-416-875-4044 (WhatsApp, Viber, IMO, Line)
Skype: Net3000.ca
Facebook Messenger:  ***@***.***> ***@***.***

**Comment by neongreen** [comment]
I think I've seen this being solved with a "defaultProtocol" config option in some other library (can choose `http` if you want to err on the side of caution or `https` if you don't care). Don't remember what it was though. Maybe a Markdown library or another editor widget.

**Comment by pomek** [comment]
Couldn't we re-use already implemented the [`config.link. defaultProtocol`](https://ckeditor.com/docs/ckeditor5/latest/api/module_link_link-LinkConfig.html#member-defaultProtocol) option?

**Comment by scofalik** [comment]
`config.link.defaultProtocol` is actually used (if set) when autolinking.

**Comment by scofalik** [comment]
We decided to cancel auto-linking if: there's no default protocol and the URL does not contain protocol:

1.  www.ckeditor.com will not get autolinked if default protocol is not set.
2.  It will get autolinked using default protocol, if default protocol is set.
3.  ckeditor.com will never get autolinked.
4.  http://ckeditor.com and http://www.ckeditor.com will get autolinked with `http://` no matter what default protocol is used.
