### ISSUE TITLE
[Docs] Consider splitting Quick Start into two parts

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1104]
I was scanning quickly the documentation to find the guide about creating a plugin, because I remembered it was there, somewhere.
 
It took me a few moments to find it.

I wonder if instead:
![screen shot 2018-06-22 at 12 58 44](https://user-images.githubusercontent.com/545175/41773725-5b079bf2-761d-11e8-9368-c2fc380f3ebf.png)

It wouldn't be better to have something like:
![screen shot 2018-06-22 at 13 07 38](https://user-images.githubusercontent.com/545175/41773728-5c77cd9a-761d-11e8-883a-0d9509d4d5ad.png)

**Comment by AnnaTomanek** [comment]
Totally makes sense 👍 . We'd just have to track down all the places where we link to it as it's a pretty popular reference 😄 .

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/pull/1639
