### ISSUE TITLE
[Docs] Provide a simple guide on how to add support for new HTML elements in plugins

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1105]
I know it's a complex topic. In any case it could be very simple starting point for people to understand some additional parts of the engine and possibly also an opportunity for people to create their first **real**  plugins without having to understand too much.

In CKEditor 4 for example we used the `<abbr>` element.

**Comment by Reinmar** [comment]
This is one of many tutorials we need to write. Let's have them covered in one place, please.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5/issues/515.
