### ISSUE TITLE
Anchor on image stripped out when wrapped in <figure> element

### ISSUE THREAD

**Issue by timtempel** [ckeditor/ckeditor5#11050]
## 📝 Provide detailed reproduction steps (if any)

1. Add image to textblock without paragraphs, generates this HTML block:
```
<figure class="image image_resized image-style-align-left" style="width:200px;">
        <img src="path-to-image">
</figure>
```
2. When adding an anchor to the image, it generates this HTML:
```
<figure class="image image_resized image-style-align-left" style="width:200px;">
    <a href="https://www.google.com" target="_blank">
        <img src="path-to-image">
    </a>
</figure>
```
3. When reloading the page, the anchor gets stripped out:
```
<figure class="image image-style-align-left" style="width:200px;">
    <img src="path-to-image">
</figure>
```

### ✔️ Expected result

Anchor should stay intact:
```
<figure class="image image_resized image-style-align-left" style="width:200px;">
    <a href="https://www.google.com" target="_blank">
        <img src="path-to-image">
    </a>
</figure>
```

### ❌ Actual result

Anchor gets stripped out:
```
<figure class="image image-style-align-left" style="width:200px;">
    <img src="path-to-image">
</figure>
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
You're probably missing one of the plugins. Check out https://ckeditor.com/docs/ckeditor5/latest/features/images/images-linking.html.

**Comment by timtempel** [comment]
> You're probably missing one of the plugins. Check out https://ckeditor.com/docs/ckeditor5/latest/features/images/images-linking.html.

Thanks for the reply. I just found out that it has something to do with the allowed htmlSupport settings. I'll close the issue as it is not a bug with CK, my apologies.

**Comment by timtempel** [comment]
Hmm maybe I was too quick with closing this issue. It definitely is something within the contentfilter because when I disable it, the problem is gone. However, even if I allow everything (see below) in the contentfilter, the anchor still gets stripped out if an Image is wrapped inside a <figure> element. Any clue what could be the cause of this behaviour?

```
htmlSupport: {
                            allow: [
                                {
                                    name: /.*/,
                                    attributes: true,
                                    classes: true,
                                    styles: true
                                }
                            ]
                        },
```

**Comment by timtempel** [comment]
OK found the problem, no clue why this is causing the anchor to be stripped out though. If I remove the "attributes" part from the allowed anchor section, then it is fixed. This means, I can't allow "rel" which is a small sacrifice to make but not ideal.

```
{
        name: 'a',
        attributes: {
            'rel'       :true,
            'href'      :true,
            'target'    :true,
        },
```
