### ISSUE TITLE
Backspace on Android doesn't delete new lines if cursor placed before some text

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5#1106]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

> **This doesn't happen on Desktop Chrome or Firefox**

> **This seems to happen only if there is text on the line, if line is empty then lines delete properly**

## 💻 Version of CKEditor

v10.1.0

Chrome for Android: 67.0.3396.87
Android: 7.1.1

## 📋 Steps to reproduce

1. Open https://ckeditor5.github.io/ that is running CKEditor 5 (v10.1.0)
2. Type a line of text, press enter a few times, type a single letter
3. put the cursor before the single letter
4. press "Delete" on the Android keyboard

## ✅ Expected result

The editor should delete new lines created in step `2`

## ❎ Actual result

Nothing happens when you press delete

## 📃 Other details that might be useful

Below I'm pressing "Backspace" or the "Delete" key in the Android keyboard

![](http://v14d.com/a/5b2e6b771d339.gif)

**Comment by f1ames** [comment]
Similar to #613 (there is already some analysis starting in https://github.com/ckeditor/ckeditor5/issues/613#issuecomment-398363722).
