### ISSUE TITLE
Balloon editor gets overlapped with native Android text controls

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5#1107]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

> Doing some experimentation on Android and noticed this issue, feel free to close if this use case is not supported...

## 💻 Version of CKEditor

v10.1.0

Chrome for Android: 67.0.3396.87
Android: 7.1.1

## 📋 Steps to reproduce

1. Start up the Balloon editor!
2. highlight some text

## ✅ Expected result

Balloon controls should be usable.
Should the balloon go below the text?

## ❎ Actual result

You can see a bit of the balloon on the right there, behind the Copy / Paste controls

![image](https://user-images.githubusercontent.com/128755/41811382-86ca459a-76dc-11e8-9b60-08d69f8d0709.png)

**Comment by f1ames** [comment]
I have also encounter this issue while testing editor on `Huawei MediaPad M5` device (`Android 8`, `Chrome`). It may not be trivial to solve, but definitely affects UX.

**Comment by Reinmar** [comment]
Additional information can be found in https://github.com/ProseMirror/prosemirror/issues/7.
