### ISSUE TITLE
[Document lists] indent list + indent block integration

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#11072]
## Provide a description of the task

Follow-up of #10880.

Original comment: https://github.com/ckeditor/ckeditor5/issues/10880#issuecomment-1003975067

**Comment by CatStrategist** [comment]
Rewrite usage of keystrokes to view listeners in plugins that listen to 'Tab' / 'Shift+Tab' and may cause issues when being used as list item in document lists. This way we can execute commands being aware of context. Also add manual tests.

All possible required changes are in:
* Table plugin's keyboard handling
* Code block editing - if code block is in a list it should have priority (whatever closest to selection)
* Restricted mode (possible not an issue, but need to verify it)

**Comment by niegowski** [comment]
Closed in #11244.
