### ISSUE TITLE
How To Install Source Editor Plugin In Native JavaScript

### ISSUE THREAD

**Issue by AnderSco01** [ckeditor/ckeditor5#11071]
Hello,

Regarding the CKEditor 5 documentation, for the source editing plugin, I noticed it only describes how to install it via npm. How would I be able to install it via native JavaScript code that isn't a React project?

Thanks.

**Comment by fspreck-indiscale** [comment]
You have to manually include the SourceCode Plugin.  You can use [the online builder](https://ckeditor.com/ckeditor-5/online-builder/) to select all plugins that you want to use.

**Comment by AnderSco01** [comment]
That's worked! Thank you very much!
