### ISSUE TITLE
Ordering problem when block quote is being inserted into the middle of the list

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11082]
## 📝 Provide detailed reproduction steps (if any)

1. Prepare six lines of text
2. Create numbered list (one number for each text line)
3. Select lines 3 and 4 and add a "Block quote"
4. Change the order of the list in the block quote.

### ✔️ Expected result

Order changes only in the block quoted list.

### ❌ Actual result

Order changes are also in the list below.
![block quote order issue](https://user-images.githubusercontent.com/32898551/148522113-235325fa-2c69-4413-9d5c-da14aa0faaa4.gif)
Changing the order of the list above or below the block quote impacts only desired list. 

## 📃 Other details

Browser: Chrome, Firefox, Safari
OS: Mac Os Monterey
First affected CKEditor version: 31.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by CatStrategist** [comment]
Possible issue is in a `listwalker.js`

**Comment by t-mangoe** [comment]
I did some research on this issue.
It seems that when a block quote is inserted, the ol tag that makes up the list is split into two.
It looks like this.

Before inserting:
```HTML
<ol>
  <li>aaa</li>
  <li>bbb</li>
  <li>ccc</li>
  <li>ddd</li>
</ol>
```

After inserting:
```HTML
<ol>
  <li>aaa</li>
  <li>bbb</li>
</ol>
<blockquote>block quoting<blockquote>
<ol>
  <!-- the order of the list is restarted from the beginning. -->
  <li>ccc</li>
  <li>ddd</li>
</ol>
```

It may be necessary to prevent the ol tag from being split into two.

**Comment by Reinmar** [comment]
Usually we use `Schema#getSelectedBlocks()` that trims the trailing block if the selection starts at the very beginning of it. Here, as you can see, blockquote uses this method but there's a chance that the "reversed order" feature does not. Disclaimer: I haven't seen any code, just base on my experience.
