### ISSUE TITLE
Add Special Characters feature

### ISSUE THREAD

**Issue by jannakha** [ckeditor/ckeditor5#1110]
🆕 Feature request 

can you please add SpecialChars feature.
University of Queensland uses CKEditor 4 for Thesis Submission form and which requires special characters scientific papers. It would be great to migrate to CKEditor 5.

Thanks!

PS: Emojis are not required, but I'm sure people will love 'em too!

---

Add 👍reaction to this post if you want this feature to be implemented.

**Comment by Reinmar** [comment]
Thanks for reporting. It'd be great to have this feature.

BTW, it's a fairly simple feature to be implemented. Apart from the UI, it just requires calling [`writer.insertText()`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-insertText) or, more generally (to handle non-collapsed selections and selection attributes), [`model.insertContent()`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent). If you'd like to give it a try, we'll be happy to give you more hints.

**Comment by gcoluni** [comment]
Has there been any update on when this might be supported?

**Comment by ma2ciek** [comment]
I'm afraid that this feature isn't on our pipeline yet. But we'd be glad seeing the community trying to implement it.

**Comment by jodator** [comment]
@gcoluni & @jannakha could you write also which type of special characters you refer to? It might be a case for https://github.com/ckeditor/ckeditor5/issues/1490.

**Comment by gcoluni** [comment]
I am referring to the toolbar Omega icon that was in version 4 that allowed for selecting the special character from the pop-up.

**Comment by Reinmar** [comment]
Related thread: inserting non-breaking spaces: https://github.com/ckeditor/ckeditor5/issues/1669.

With a code sample how to bind Alt+space to inserting an nbsp: https://github.com/ckeditor/ckeditor5/issues/1669#issuecomment-478934583. May be useful if someone wants to write their own "special char" plugin.

**Comment by pomek** [comment]
This is how the feature looks in CKEditor 4:

![image](https://user-images.githubusercontent.com/2270764/67843377-26baf500-fafc-11e9-9b57-fa5beb2ca509.png)

In CKEditor 5 we could use the same dropdown mechanism which is used for displaying font/background colors:

![image](https://user-images.githubusercontent.com/2270764/67843485-5a961a80-fafc-11e9-8035-e6bcbecc7949.png)

Each square could have a special character. After clicking on it, the character will be inserted to the editor (is `model.insertContent()` safe in such case?).

It would be good to use panes here. In the first one, we could keep special characters, in the second one – emoji. I am not sure whether it is possible.

My question is – what are special characters? Should we include `0-9`, `A-z`, and other "standard" combinations that could be added to the editor by pressing `SHIFT+[0-9]`?

Also, the Special Characters plugin will provide a list of special characters. How would like we to give a user the ability to extend the list?

Should we allow defining all items by the user (as an array `config.specialCharacters.symbols`) or provide a default set of the special character and items listed in `config.specialCharacters.symbols` will be appended to our default set?

**Comment by jodator** [comment]
> Each square could have a special character. After clicking on it, the character will be inserted to the editor (is `model.insertContent()` safe in such case?).

Yes - we're using this in text transformations and AFAIR it's a preffered way.

> My question is – what are special characters? Should we include `0-9`, `A-z`, and other "standard"

I had the same doubts when looking at CKE4 but it might be that what's standard in western languages might not be in other languages (Arabic, Chinese, ?) - but I'm not 100% sure on this.

**Comment by oleq** [comment]
> It would be good to use panes here. In the first one, we could keep special characters, in the second one – emoji. I am not sure whether it is possible.

We don't have this kind of component yet (namely: tabs) but probably we'll expect something similar to the native MacOS selector

![image](https://user-images.githubusercontent.com/1099479/67858119-b1115200-fb18-11e9-8ef9-39917714987d.png)

The implementation should be fairly simple.

As for categories, both MS Word and other WYSIWIG editor on the market use similar categories like "arrows", "mathematical", "punctuation". This is a good place to start because people will a UX they're familiar with. A sane set of defaults (a couple of categories with entries) and a possibility to configure your own should do the trick. 

P.S. This could be also the right place to provide the emoji feature.

**Comment by Reinmar** [comment]
# MVP

- Command?
    - It's very similar to the `input` command, but we can create it anyway.
    - would insert by item's name: `execute( { item: 'arrow right' } )`
    - Should be disabled if the `input` command is disabled.
        - Example: `MultiCommand`
- UI
    - No tabs (more complicated to implement, width limits their number, would have to use singular character as a label what would cause some confusion)
    - Dropdown (all, mathematical, arrows, ...)
    - Grid with characters
- Docs
- Essential + atomic categories
    - There will be a base `SpecialCharacters` plugin implementing the architecture, UI, etc.
    - Groups of special chars will be delivered by plugins – `SpecialCharactersMathematical`, `SpecialCharactersArrows`. The goal is to have them delivered in a granular fashion so you can load only these that you want and reduce code size.
    - However, to make it easy to enable all the groups at once, we can also have `SpecialCharactersEssentials`.
- Translations
    - Group names (not a problem)
    - Item names... 💥
        - Can we extract translations from some database (official unicode spec or some other, open database)?
- API:

        // MVP
        ClassicEditor.create( foo, {
        	plugins: [ SpecialCharacters, SpecialCharactersEssentials ]
        } );
        
        // MVP
        ClassicEditor.create( foo, {
        	plugins: [ SpecialCharacters, SpecialCharactersMathematical, SpecialCharactersEmojis ]
        } );
        
        // MVP (just because we need this API for the above mentioned options)
        // Adding new group
        ClassicEditor.create( foo, {
        	plugins: [ SpecialCharacters, SpecialCharactersMathematical, SpecialCharactersEmojis, MyPlugin ]
        } );
        class MyPlugin extends Plugin {
        	init() {
        		editor.plugins.get( 'SpecialCharacters' ).addItems( 'My group', [
        			{
        				title: 'arrow right',
        				character: '🤜'
        			},
        			// ...
        		] );
        	}
        }
        
        // MVP (just because we need this API for the above mentioned options)
        // Adding item to an existing group
        ClassicEditor.create( foo, {
        	plugins: [ SpecialCharacters, SpecialCharactersMathematical, SpecialCharactersEmojis, MyMathematicalPlugin ]
        } );
        class MyMathematicalPlugin extends Plugin {
        	init() {
        		editor.plugins.get( 'SpecialCharacters' ).addItems( 'Mathematical', [
        			{
        				title: 'arrow right',
        				character: '🤜'
        			},
        			// ...
        		] );
        	}
        }

# Future

- Keyboard navigation
- Search
- Configurability

        ClassicEditor.create( foo, {
        	plugins: [ SpecialCharacters, SpecialCharactersMathematical, SpecialCharactersEmojis ],
          specialCharacters: {
        		// non MVP
        		groups: [ 'All', 'Emojis', 'Mathematical' ],
        		// non MVP
        		extraGroups: {
        			'Custom characters': [
        				{
        					title: 'arrow right',
        					character: '🤜'
        				}
        			]
          }
        } );

- How to remove pre-defined characters?

        ClassicEditor.create( foo, {
        	plugins: [ SpecialCharacters, SpecialCharactersMathematical, SpecialCharactersEmojis ],
          specialCharacters: {
        		removeItems: [ 'arrow right', ... ]
          }
        } );

- Preview?

**Comment by mlewand** [comment]
Hey everyone, during the testing phase we decided that we need to polish our special character plugin a little bit before releasing. So it means that improved version will be released in iteration 29th. Sorry for the delay, but we hope it will be worth it!

**Comment by Reinmar** [comment]
TODO:

* [ ] Decide about the command
* [ ] Translations
* [ ] Default character set
* [ ] Review internal data model
* [ ] Finish the UI (get rid of the tooltip by intrucing a status bar)
* [ ] Griiiidddddddd
* [ ] Feature guide

**Comment by pomek** [comment]
Reopening because there are still things TODO (https://github.com/ckeditor/ckeditor5/issues/1110#issuecomment-560429211).

**Comment by pomek** [comment]
> Decide about the command

There is no point in keeping a command that executes another command. Let's remove it. Also, the editing part of the feature could be removed because it only adds the command. I will remove it as well.

**Comment by pomek** [comment]
> Translations

I wrapped all Unicode names in the `t()` function. Not sure, what I could do more.

**Comment by pomek** [comment]
> Default character set

![image](https://user-images.githubusercontent.com/2270764/70131516-bb2bf080-1682-11ea-8425-af2510e7adda.png)

I guess it is not enough but TBH I have no idea which special characters we should include. There are many of them…

**Comment by ma2ciek** [comment]
>> Translations

> I wrapped all Unicode names in the t() function. Not sure, what I could do more.

I don't know if the `lang/contexts.json` file is already created, but if not, then it should be 😄 Based on this file the translations are uploaded on the Transifex, so the translation context is known better for the translator.

**Comment by pomek** [comment]
@ma2ciek, I didn't mention about the file because it's obvious for us. We remember about it :D
