### ISSUE TITLE
HTML comments are wrapped into `<p>` elements in the demo

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#11108]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html#demo-2 
2. Switch to Source.
3. Check the HTML comment that is in the content.

### ✔️ Expected result

The HTML comment should not be wrapped into a `<p>` element.

### ❌ Actual result

The HTML comment is wrapped into a `<p>` element.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by AnnaTomanek** [comment]
@ckeditor/qa-team could you have a look as this is probably something with the source content that we have for the demo in the docs? Thanks!

**Comment by godai78** [comment]
In the content, the comment was wrapped with `<p>` tags. I'll just remove them and test it.

**Comment by FilipTokarski** [comment]
Fix ready: https://github.com/ckeditor/ckeditor5/pull/11113

**Comment by FilipTokarski** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/11113.
