### ISSUE TITLE
Incorrect value of `[aria-pressed]` attribute in switch

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#11115]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Open a dialog for inserting links.
3. Inspect the "Downloadable" switch element.

### ✔️ Expected result

The element has `[aria-pressed]` attribute with a value of `false`.

### ❌ Actual result

The element has `[aria-pressed]` attribute with a value of `undefined`.

## 📃 Other details

* Browser: 97.0.4692.71 (Official Build) (x86_64)
* OS: macOS 12.0.1
* First affected CKEditor version: 31.1.0 (tested only on this one)
* Installed CKEditor plugins: link

It seems that the attribute's value fixes itself the moment user interacts with the switch.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by NaincyKumariKnoldus** [comment]
Hey @Comandeer Can I do this?

**Comment by Comandeer** [comment]
@NaincyKumariKnoldus, yes, you can! Please note that your PR should include tests for the change. You can check [our docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/testing-environment.html) for more info about the testing environment.

**Comment by NaincyKumariKnoldus** [comment]
Hey @Comandeer Having a CLA is important for contributing? I dont have

**Comment by Reinmar** [comment]
You will be asked to sign it after you make a PR. It can be done completely online :) It's a standard procedure that secures the project from odd copyrights problems.

**Comment by NaincyKumariKnoldus** [comment]
Hey @Reinmar I am not able to find aria-pressed undefined here.

**Comment by pomek** [comment]
* Possible solution. Cast the `value` variable to boolean, then to a string.
https://github.com/ckeditor/ckeditor5/blob/e391ddb70d6f55c2c7465a84fd3e830265b3279d/packages/ckeditor5-ui/src/button/buttonview.js#L148
* However, is it a workaround? Perhaps we should see whether we have a bug in the `ObservableMixin` object which decline `false` values and passed `undefined` instead.
