### ISSUE TITLE
Securety issue in dependency (marked@1.1.1) of @ckeditor/ckeditor5-markdown-gfm

### ISSUE THREAD

**Issue by alfredriesen** [ckeditor/ckeditor5#11124]
Please refer to [snyk](https://security.snyk.io/vuln/SNYK-JS-MARKED-2342082)

**Comment by FilipTokarski** [comment]
cc @pomek Could you take a look?

**Comment by pomek** [comment]
We should consider bumping the version (https://www.npmjs.com/package/marked). But definitely, it's not a devops-related task.

https://github.com/ckeditor/ckeditor5/blob/c22446984fde4dfc9ba62d2f6a8217bcd85202e4/packages/ckeditor5-markdown-gfm/package.json#L16

Do not forget to verify whether Github Writer will still work except for a bump.

**Comment by Reinmar** [comment]
Looking at https://github.com/markedjs/marked/security/advisories we need to upgrade to at least 4.0.10.

**Comment by Reinmar** [comment]
It may affect GH Writer. As a followup ping @mlewand and @mateuszzagorski that we're doing this.
