### ISSUE TITLE
Not able to select whole paragraph with triple click when there is a table right after it

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11130]
## 📝 Provide detailed reproduction steps (if any)

1. Add some text in paragraph
2. Add a table right after the paragraph
3. Triple click on the paragraph to select it

### ✔️ Expected result

Whole paragraph is selected.

### ❌ Actual result

Paragraph is not selected. Selection collapses and jumps to the beginning of the paragraph.

### Screencast

https://user-images.githubusercontent.com/34380544/149969165-4aad13d7-6d15-418b-be0d-0112ca44a3ab.mp4

## 📃 Other details

* First affected CKEditor version: `27.0.0`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by JasaNiklanovic** [comment]
Hi all, this is a serious bug in the core functionality and we would really appreciate this being solved asap.

**Comment by Witoso** [comment]
Possible fix or approach: inline fillers around widgets.

**Comment by Witoso** [comment]
Possible place to solve this as it's related to widgets: https://github.com/ckeditor/ckeditor5/blob/8d8a5730a5d40dae350d00d9605c3ab2c2df6e91/packages/ckeditor5-widget/src/widget.ts#L210-L221
