### ISSUE TITLE
Full-featured editor uses ListStyles but should ListProperties

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#11142]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

### ✔️ Expected result

No warning in the console.

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/150341627-db9c64fe-81a7-4aa7-8e10-22a8ae5c7b8d.png)

### ❓ Possible solution

PR was not merged: cksource/ckeditor5-internal#1273

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Typo - `User` => `Use`? :D

**Comment by niegowski** [comment]
> Typo - `User` => `Use`? :D

Ahh in the warning message, missed that :D

**Comment by AnnaTomanek** [comment]
Actually while working on this example now (we want to change the content a bit), Bartek added the list properties to the demo itself: cksource/ckeditor5-internal#1335

**Comment by godai78** [comment]
@niegowski @pomek - i'll be mergin' it today, you don't need to do it.

**Comment by niegowski** [comment]
Typo fixed in f2be033.
