### ISSUE TITLE
Inline Toolbar overlaps table menu

### ISSUE THREAD

**Issue by ajssd** [ckeditor/ckeditor5#11159]
## 📝 Provide detailed reproduction steps (if any)

1. go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html
2. in the bottom right, insert a table
3. bring up the table row menu using the 'v' icon in the floating toolbar
4. make sure you're scrolled to a point where the table row menu renders "up" not "down"

### ✔️ Expected result

Correctly layered toolbars

### ❌ Actual result

Toolbar overlaps menu

### ❓ Possible solution

none known

## 📃 Other details

* Browser: safari
* OS: macos

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ajssd** [comment]
https://user-images.githubusercontent.com/10245941/150864727-3a05b94d-cc58-4804-8af7-8777661ee57b.mov

**Comment by dufipl** [comment]
Hello @ajssd, thank you for reporting this issue!
We are aware of that problem, it has been reported here: https://github.com/ckeditor/ckeditor5/issues/10739
If you want to track the current status of the issue, please use the issue link above.
Closing this issue as a duplicate.
