### ISSUE TITLE
CKeditor changes original HTML structure by converting div elements to p

### ISSUE THREAD

**Issue by gh-andre** [ckeditor/ckeditor5#11154]
## 📝 Provide detailed reproduction steps (if any)

Make sure your build includes `Source editing` plug-in to make verification easier. Open a document, switch to source and type this.
```html
<blockquote>
    <div>
        This is supposed to be an outer &lt;div&gt;
        <div>
            This is supposed to be an inner &lt;div&gt;
        </div>
    </div>
</blockquote>
```
Click the source button twice and the HTML gets converted to this:
```html
<blockquote>
    <p>
        This is supposed to be an outer &lt;div&gt;
    </p>
    <p>
        This is supposed to be an inner &lt;div&gt;
    </p>
</blockquote>
```
Note that `Source editing` is just mentioned as an easy way to verify this behavior. The editor mangles `div` elements without using this plug-in.

### ✔️ Expected result

I expect CKeditor v5 to keep the original HTML structure intact and just provide ways to edit it predictably. Some non-structural changes are expected, like converting colors in attributes, but the overall HTML structure should not be changed from what was typed.

### ❌ Actual result

Not only all `div` elements are converted to `p` elements, but because of the different structure of `p` elements, all inner `div` elements are brought out to the same level as the outer `div` element. This make it absolutely impossible to even run a script to convert it back once this change is noticed in the saved source.

### ❓ Possible solution

N/A

## 📃 Other details

* Browser: FireFox v96, Chrome v97
* OS: Windows 11
* First affected CKEditor version: 31.1.0
* Installed CKEditor plugins: Source editing

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, this behaviour is not a bug. Editor has its own data model, which is specified by the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html), and does not preserve all html elements and attributes by default. You can [read more about it in the docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/intro.html).
  
If you want to preserve custom html and attributes, you can use [general html support plugin](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html).

**Comment by wimleers** [comment]
Note that even when you are using GHS, CKE5 will convert

```
<blockquote>thoughtful quote here</blockquote>
```

to

```
<blockquote>
  <p>thoughtful quote here</p>
</blockquote>
```

That too is a problem, because it can break existing CSS selectors.

**Comment by gh-andre** [comment]
@FilipTokarski Thanks for responding. 

I'm trying to migrate from CKeditor v2.6, which served my purposes really well for many years, and I'm sorry to hear about this shift in paradigm in which CKeditor now follows the MS Word HTML editing path in reshaping the HTML structure and forcing a massive style sheet on people to use even outside of the editor.

The General HTML Support (GHS) plug-in is an experimental feature and it doesn't work very well. As @wimleers describes above, it still mangles the HTML. With my example, it takes this:
```html
<blockquote>
    <div>
        This is supposed to be an outer &lt;div&gt;
        <div>
            <div>XYZ</div>
            This is supposed to be an inner &lt;div&gt;
        </div>
    </div>
</blockquote>
```
, and generates this:
```html
<blockquote>
    <div>
        <p>
            This is supposed to be an outer &lt;div&gt;
        </p>
        <div>
            <div>
                XYZ
            </div>
            <p>
                This is supposed to be an inner &lt;div&gt;
            </p>
        </div>
    </div>
</blockquote>
```
This is not the same HTML, as the plug-in name suggests it would generate, and it's not even consistent at what it does. Now CSS writers have to guess what CKeditor would emit to make it work or use carpet bombing styles that reach any level. The original HTML is valid HTML and the fact that CKeditor restructures it to fit some model somebody on CKeditor's dev team considered better than what the user supplied is disappointing to say the least.

I'm puzzled by this change and will need to find a way forward, but I'm not willing to sacrifice my HTML structure to follow what the editor dictates, which would be a never-ending chase of the structure, as new versions of the editor emerge. 

Fortunately for me, CKeditor v2.6 is written exceptionally well and still works in most parts, which some minor issues in Chrome, so I guess I will stay with it until I find a way to keep my original HTML structure.

**Comment by shahzebgit** [comment]
@gh-andre could you provide me the link for CK v2.6?

>I'm not willing to sacrifice my HTML structure to follow what the editor dictates, which would be a never-ending chase of the structure, as new versions of the editor emerge.

Even I'm having issues with this in current version of CK5, it's really hard to work with [GHS] as they suggest the inline-styles are just put into attribute objects which makes it hard to work on the model side of editor with it.

**Comment by gh-andre** [comment]
@shahzebgit You can find a few v2.6 versions here.

https://sourceforge.net/projects/fckeditor/files/FCKeditor/

I would advise against going back to these old versions, though. As good as v2.6 is, it' still very old software.

**Comment by gh-andre** [comment]
Well, not seeing much enthusiasm from the CKeditor team in keeping user's HTML structure I started researching other editors and chose TinyMCE. Not only it keeps my HTML structure, but it also allows custom CSS, just like CKeditor v2.6 does, and supports other features I use, like source edit, customizable menus/toolbars without separate builds, etc. There's one thing to keep in mind - it drops inline events and rewrites URLs by default, so some configuration is required to disable these "helpful" things.

I will close this issue now. Thanks for all the insights.

**Comment by Charuru** [comment]
@gh-andre how does TinyMCE keep your HTML? I'm looking for an editor that keeps HTML too but TinyMCE also adds <p> everywhere as per my experimentation. The code cleanup setting was removed back in version 3 and now it no longer has it. Unless you're using an old version of it?

**Comment by gh-andre** [comment]
@Charuru Not sure what's going on in your case. I'm using v5.10.2 and I'm not seeing any modifications in HTML beyond those in URLs and inline event handlers I mentioned. I use a form post with `textarea`, but I also just tried `editor.getContent()` and it's giving me back correct HTML.
