### ISSUE TITLE
Lost formatting of newlines after upgrading to CKEditor5

### ISSUE THREAD

**Issue by vitality82** [ckeditor/ckeditor5#11168]
## 📝 Provide detailed reproduction steps (if any)

1. open existing ckeditor4 content using ENTER_MODE.DIV in ckeditor5
2. notice that all new lines,` <div>&nbsp;</div>` are removed (sanitized)
3. now, original content has lost it's formatting

### ✔️ Expected result

if the new way is to always use `<p>` tags then by all means, replace `<div>&nbsp;</div>` with `<p>&nbsp;</p>`

### ❌ Actual result

`<div>&nbps;</div>` are completely removed from existing content (stored in our database) using CKEditor4

* Browser: Chrome
* OS: MacOS
* First affected CKEditor version: CKEditor5
* Installed CKEditor plugins: classic editor

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. CKEditor 4 and CKEditor 5 are completely separate apps with different data model and the way they handle content. For more detailed explanation and features comparison, please see the [docs on migrating from CKEditor 4](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-from-ckeditor-4.html).

**Comment by vitality82** [comment]
I solved this by replaced all occurrences of the old newlines in the db with empty paragraphs (since <p> tags are not sanitised).
