### ISSUE TITLE
[Document Lists] Implement list properties commands

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#11166]
Commands to implement:
- `listStyle`
- `listStart`
- `listReversed`

These commands should be modeled after existing commands in `list` package. Verification if they work with existing `ListPropertiesUI` is in scope.

Behavior of these commands for collapsed vs non-collapsed selection differ between MS Word and Google Docs. We should go for easiest approach.

**Comment by niegowski** [comment]
Closed in #11249.
