### ISSUE TITLE
How to process Clipboard data copied from word

### ISSUE THREAD

**Issue by shahzebgit** [ckeditor/ckeditor5#11161]
## Provide a description of the task

I'm trying to copy and paste from Google Docs, and i want to extract the plain text from the `Element` which is getting pasted,
Clipboard Data i got,
```html
<p>
    <span style="color: #000000;">Third Avenue Value Fund seeks long-term capital appreciation.</span>
</p>
<p>
    <span style="color: #000000;">
        This table describes the fees and expenses that you pay if you buy and hold shares of Third Avenue Value Fund. Investors transacting in Fund shares through a financial intermediary acting as a broker in an agency capacity may be
        required to pay a commission directly to the broker.
    </span>
</p>
```
I want to paste the clipboard content but i don't want the `p`,`span` tags or even the `attributes`, all i want is to get the plain text from the `Element` which is,
```
Third Avenue Value Fund seeks long-term capital appreciation.

This table describes the fees and expenses that you pay if you buy and hold shares of Third Avenue Value Fund. Investors transacting in Fund shares through a financial intermediary acting as a broker in an agency capacity may be
required to pay a commission directly to the broker.
```

I found some info about the clipboard contents here,regarding the `data.content`
https://github.com/ckeditor/ckeditor5/blob/aca6ab6f548e0a4c7334f59588f165beea6829a7/packages/ckeditor5-clipboard/src/clipboardpipeline.js#L206-L221

But I'm not able to manipulate the `data.content` from it.
https://github.com/ckeditor/ckeditor5/blob/aca6ab6f548e0a4c7334f59588f165beea6829a7/packages/ckeditor5-clipboard/src/clipboardpipeline.js#L226-L228

## 📃 Other details

* Browser: Chrome
* OS: Ubuntu 20.04LTS
* CKEditor version: v31.1.0
* Installed CKEditor plugins: …

**Comment by FilipTokarski** [comment]
Hi, you could use code like this:
```js
editor.editing.view.document.on( 'clipboardInput', ( evt, data ) => {
	const dataTransfer = data.dataTransfer;
	const content = dataTransfer.getData( 'text/plain' );

	console.log( content );
} );
```

**Comment by shahzebgit** [comment]
@FilipTokarski Thanks for the help and yeah this is pretty much what i needed 👍🏽 
 but i wanted to know how can paste the content in the editor? either with `model.change` or `view.change`
