### ISSUE TITLE
Build fails with --dev flag

### ISSUE THREAD

**Issue by lauriii** [ckeditor/ckeditor5#11170]
## 📝 Provide detailed reproduction steps (if any)

Run: `yarn dll:build --dev`

### ✔️ Expected result

Should build DLL with dev configuration

### ❌ Actual result

```
$ yarn dll:build --dev
yarn run v1.22.17
$ node ./scripts/dll/build-dlls.js --dev
🛠️️  Development mode is active.

📍 Creating the base DLL build...

[webpack-cli] Error: Unknown option '--dev'
[webpack-cli] Did you mean '--env'?
[webpack-cli] Run 'webpack --help' to see available commands and options

```
## 📃 Other details

* OS: MacOS
* Node version: v16.10.0
* Yarn version: 1.22.17

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
It should be fixed in https://github.com/ckeditor/ckeditor5/pull/11202.
