### ISSUE TITLE
[Conversion docs] Misc polishing

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#11173]
- Mention the Widget API in a couple of important places, e.g. in examples where we create something that would normally use widgets (we can link to the tutorial about block widgets)
- Add something about GHS in the [main introduction](https://www.notion.so/Introduction-c466d9194ddf469696c26431815d6b11)
    - You can get inspiration from [**Introduction**](https://www.notion.so/Introduction-35f39a6972ff45df8cf97022c30569ea)

**Comment by oleq** [comment]
Closed in #11430.
