### ISSUE TITLE
[Conversion] Add information about breaking changes in the conversion system to the migration guide

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11188]
Goal: All breaking changes need some explanation with tips (if possible) on how to migrate from the previous version to the new.

The information will base on the description of a PR for #11187.

BCs that we remember now:

*   You should update to e2S when possible (story: e2E will support only a single-element output in the future, right now it supports creating multiple elements for legacy reasons)
*   Removed `triggerBy`
*   Recursively firing downcast events (instead of having a loop in DowncastDispatcher)

Misc:

* Link to #11268 explaining that the reader can find there a higher-level overview of the changes.

**Comment by Reinmar** [comment]
Since we'll also have #11268, we can be a bit more concise here. We don't need to duplicate things like "whys". But:

* we need both things cross-linked,
* the migration guide must not fail to mention some BC, even if that BC wasn't covered in the summary.

**Comment by Reinmar** [comment]
### Changes

> MAJOR BREAKING CHANGE (list): The `ListEditing`, `ListUI`, `ListStyleEditing`, `ListStyleUI`, `TodoListEditing`, `TodoListUI` plugins were moved to the dedicated subdirectories (`list`, `liststyle`, `todolist`).

High risk.

> MAJOR BREAKING CHANGE (engine): Removed the Differ#refreshItem() method from the public API. Replaced by EditingController#reconvertItem() (see [#10659](https://github.com/ckeditor/ckeditor5/issues/10659)).

Low risk.

> MAJOR BREAKING CHANGE (engine): The `DowncastDispatcher` will throw an error if any of the model items were not consumed while converting. Read the [`conversion-model-consumable-not-consumed`](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#conversion-model-consumable-not-consumed) error documentation for more information.

High risk.

> MAJOR BREAKING CHANGE (engine): The `DowncastDispatcher#conversionApi` property is no longer available. The instances of `DowncastConversionApi` being created at the start of conversion.

Low risk.

> MAJOR BREAKING CHANGE (engine): The support for the `triggerBy` option for downcast helpers is removed and replaced with the new `elementToStructure()` options.

High risk. 

Also, not only `e2S()` but also the `attributes` and `children` options in `e2E()`.

> MINOR BREAKING CHANGE (media-embed): The `createMediaFigureElement` helper function first argument has been changed from `writer` object to `conversionApi` object.

Super low risk

> MINOR BREAKING CHANGE (table): The downcast converters of the table feature has been rewritten with the use of `elementToStructure()` and the re-conversion mechanism. See [#10502](https://github.com/ckeditor/ckeditor5/issues/10502).

Moderate risk.

> Other (engine): The attribute and child nodes conversion events are fired by the lowest priority handler for the insert event instead of by `DowncastDispatcher` itself. Closes [#10376](https://github.com/ckeditor/ckeditor5/issues/10376).
> 
> Other (engine): Events are fired by the `DowncastDispatcher` even if they were previously consumed. It's the conversion handler's responsibility to check if it can be consumed or if it was already consumed by other converters.

Moderate risk.

People might've been canceling these events because we even mentioned this in the docs. Make it clear to never cancel.

### Features

It's worth mentioning some of the most important features like passing children to `createContainerElement()`, `e2S()` and `children/attributes` prop of `e2E()`, etc.

**Comment by oleq** [comment]
Closed in #11423.
