### ISSUE TITLE
TypeError: this.props.editor.create is not a function

### ISSUE THREAD

**Issue by nimaes80** [ckeditor/ckeditor5#11185]
## 📝 Provide detailed reproduction steps (if any)
 Im Using react app after I download my custom  build from [CKEditor 5 online builder](https://ckeditor.com/ckeditor-5/online-builder/) then I follow [these](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder) steps, I got this err on console 

```
TypeError: this.props.editor.create is not a function
    at Rr._createEditor (bundle.js:5640:34)
    at Pr._creator (bundle.js:5624:176)
    at bundle.js:5363:187 {phase: 'initialization', willEditorRestart: false}
onError @ bundle.js:5736
(anonymous) @ bundle.js:5633
Promise.catch (async)
_initializeEditor @ bundle.js:5633
componentDidMount @ bundle.js:5606
commitLifeCycles @ bundle.js:75584
commitLayoutEffects @ bundle.js:78312
callCallback @ bundle.js:58988
invokeGuardedCallbackDev @ bundle.js:59037
invokeGuardedCallback @ bundle.js:59097
commitRootImpl @ bundle.js:78046
unstable_runWithPriority @ bundle.js:93233
runWithPriority$1 @ bundle.js:66394
commitRoot @ bundle.js:77889
performSyncWorkOnRoot @ bundle.js:77231
(anonymous) @ bundle.js:66448
unstable_runWithPriority @ bundle.js:93233
runWithPriority$1 @ bundle.js:66394
flushSyncCallbackQueueImpl @ bundle.js:66443
flushSyncCallbackQueue @ bundle.js:66431
scheduleUpdateOnFiber @ bundle.js:76795
enqueueSetState @ bundle.js:67571
Component.setState @ bundle.js:90431
(anonymous) @ bundle.js:139
Promise.then (async)
componentDidMount @ bundle.js:138
commitLifeCycles @ bundle.js:75584
commitLayoutEffects @ bundle.js:78312
callCallback @ bundle.js:58988
invokeGuardedCallbackDev @ bundle.js:59037
invokeGuardedCallback @ bundle.js:59097
commitRootImpl @ bundle.js:78046
unstable_runWithPriority @ bundle.js:93233
runWithPriority$1 @ bundle.js:66394
commitRoot @ bundle.js:77889
performSyncWorkOnRoot @ bundle.js:77231
scheduleUpdateOnFiber @ bundle.js:76783
updateContainer @ bundle.js:80320
(anonymous) @ bundle.js:80852
unbatchedUpdates @ bundle.js:77335
legacyRenderSubtreeIntoContainer @ bundle.js:80851
render @ bundle.js:80934
./src/index.js @ bundle.js:3811
options.factory @ bundle.js:96307
__webpack_require__ @ bundle.js:95767
(anonymous) @ bundle.js:96882
(anonymous) @ bundle.js:96884

```

I just copy and past steps and dont change enything by myself...

### ✔️ Expected result

render editor

### ❌ Actual result

render null or not thing

### ❓ Possible solution

I think it cant extends custom class in to base class...

## 📃 Other details

* Browser: chrome
* OS: ubuntu
* First affected CKEditor version: lastest
* Installed CKEditor plugins: custom build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by EllipticElysium** [comment]
I'm having the same issue

**Comment by iamsimonlangham** [comment]
We're having the same issue. Nothing to really add to the original comment. Would be good to have this resolved as we're currently looking at alternatives or rolling back to an older version.

**Comment by dufipl** [comment]
Hello @nimaes80, thank you for reporting the issue. 
I was following our guide you've linked in the issue about React integration with online built CKEditor5, but did not face any problems and integration is working fine. 
Could you please provide more details about the exact configuration of the build you generated using the online tool?
Is the package with the build located properly and linked using yarn? 
I will be grateful for such information.

**Comment by nimaes80** [comment]
> Hello @nimaes80, thank you for reporting the issue. I was following our guide you've linked in the issue about React integration with online built CKEditor5, but did not face any problems and integration is working fine. Could you please provide more details about the exact configuration of the build you generated using the online tool? Is the package with the build located properly and linked using yarn? I will be grateful for such information.

Hello @dufipl, I added every plugins available (for free)
 in [CKEditor5 Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) in to my editor 
heres my code in App.js like [example] 
![Screenshot from 2022-02-03 09-49-43](https://user-images.githubusercontent.com/22503761/152291929-900c14d3-47fc-4c30-9900-941765c2a4da.png)
and what I got from browser
![Screenshot from 2022-02-03 09-50-06](https://user-images.githubusercontent.com/22503761/152292178-b1339799-ff0b-4a8e-ae32-280dfe1cac2e.png)

but when using default choices there is no error also I try to create my costum build editor by my self and it cuse err wich I mentioned it befor.

**Comment by dufipl** [comment]
Thank you for these details @nimaes80.
I was able to get reproduction using the same plugin set as you did. 
I'm investigating this issue in order to find out what is wrong.

**Comment by nimaes80** [comment]
Thanks, but can you record video of what your doing so that its work for you but not me? like in send youtube video link or etc...?

**Comment by nimaes80** [comment]
Ok I solve problem and noticed that its not bug or similar thing.
If you add **Watchdog** plugin to your build if you check `ckeditor5-custom-build/build/ckeditor` you notice that **Watchdog** exported as default wich says `export default {Editor, Watchdog};` so you should not use Watchdog or you should change import to `import {Editor as ClassicEditor} from 'ckeditor5-custom-build/build/ckeditor';` wich I ref to [stackoverflow.com](https://stackoverflow.com/a/67580200/12160182) 
I hope it solve outhers problems.

**Comment by dufipl** [comment]
@nimaes80 yes, the Watchdog plugin was the problem, you should not use it in your build because it is already being used within CKEditor 5 with react integration feature. Adding it to the build cause the error you've submitted. 
For future reference this information is available here: 
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-ckeditor-5-online-builder
Anyway, I'm glad your build is working now! :)

**Comment by hxtruong6** [comment]
> @nimaes80 yes, the Watchdog plugin was the problem, you should not use it in your build because it is already being used within CKEditor 5 with react integration feature. Adding it to the build cause the error you've submitted. For future reference this information is available here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-ckeditor-5-online-builder Anyway, I'm glad your build is working now! :)

I got the same issue although I didn't use Watchdog plugin.
![image](https://user-images.githubusercontent.com/24609363/173094467-4d81a519-3f09-4aaa-973e-5b8fc282f1a1.png)
Do you have any other solutions?

**Comment by vnchnk** [comment]
> > @nimaes80 yes, the Watchdog plugin was the problem, you should not use it in your build because it is already being used within CKEditor 5 with react integration feature. Adding it to the build cause the error you've submitted. For future reference this information is available here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-ckeditor-5-online-builder Anyway, I'm glad your build is working now! :)
> 
> I got the same issue although I didn't use Watchdog plugin. ![image](https://user-images.githubusercontent.com/24609363/173094467-4d81a519-3f09-4aaa-973e-5b8fc282f1a1.png) Do you have any other solutions?

Have the same issue

**Comment by nimaes80** [comment]
Check source code which online build gives to you, Make sure there is no multiple exports on it if there is any, import module like blow
```
import { * as myModule } from "myCkeditorOnlineBuild";
// or
import { firstModule, secondModule } from "myCkeditorOnlineBuild";

```

**Comment by ashishforgrz** [comment]
> 
@hxtruong6 @vnchnk @gbradley @nimaes80
Is your issue fixed? I have excluded watchdog plugin but still getting the same issue

**Comment by nimaes80** [comment]
> > 
> 
> @hxtruong6 @vnchnk @gbradley @nimaes80 Is your issue fixed? I have excluded watchdog plugin but still getting the same issue for build. It is working fine for local development

Yes, If you have noticed after that  I close issue.

**Comment by ashishforgrz** [comment]
@hxtruong6 @vnchnk @gbradley @nimaes80 i am getting

 ( TypeError: this.props.editor.create is not a function
    at n.value (2.e5d18696.chunk.js:2:165954)
    at n._creator (2.e5d18696.chunk.js:2:165449)
    at 2.e5d18696.chunk.js:2:154412 {phase: 'initialization', willEditorRestart: false} ) 

for _createEditor inside **@ckeditor/ckeditor5-react**

I have imported my custom build as import * as Editor from "ckeditor5-custom-build/build/ckeditor" after adding the file into npm and I don't have watchdog plugin inside my build. 
How can i fix this? Currently after creating build it's not working but working fine with local.

**Comment by Witoso** [comment]
@ashishforgrz the problem may be in your import statement `import * as Editor from "ckeditor5-custom-build/build/ckeditor"` which gets all exports of js file, whereas you should just get the default export `import Editor from "ckeditor5-custom-build/build/ckeditor"` (this depends of course how you structured the build).

**Comment by ashishforgrz** [comment]
@Witoso for import * as Editor from "ckeditor5-custom-build/build/ckeditor"
It is showing ---->

Creating an optimized production build...
Failed to compile.
./src/components/ckeditor/Ckeditor.jsx
Attempted import error: 'ckeditor5-custom-build/build/ckeditor' does not contain a default export (imported as 'Editor')

**Comment by Witoso** [comment]
Please follow this tutorial, as it will be hard to debug the whole structure of your project: https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/react.html#integrating-a-build-from-the-online-builder

**Comment by abduraufsherkulov** [comment]
@ashishforgrz were you able to fix it? The issue is still present. But it doesn't work after building for prod.

**Comment by MinhVuong68** [comment]
> @ashishforgrz were you able to fix it? The issue is still present. But it doesn't work after building for prod.

I am also facing the same error, have you resolved this issue now?

**Comment by indomitableXiaoNan** [comment]
2024-05-09 
https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react/react.html#integrating-a-build-from-the-online-builder
Following the tutorial, there are still the same issues
