### ISSUE TITLE
Merge the reconversion branch to master

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11187]
Goal: Merge `ck/10294/reconversion` to `master` and ensure that CI works

TODO:

*  [x] Merge latest `master` to that branch.
*  [x] Merge the documentation branch to `ck/10294/reconversion`.
*  [x] Update license headers to 2022.
*  [x] Check that all CIs pass (including CF and cke5-internal).
*  [x] If slotFor() is already moved to writer, update all its occurrences in the docs.
*  [x] Create a changelog entry summing up all the changes.
*  [x] Prepare merge commit message
*  [x] Remove `conversion-element-to-element-created-multiple-elements` warning and bring back `conversion-element-to-structure-disallowed-text` with better docs (explain to use `elementToElement()` instead) https://github.com/ckeditor/ckeditor5/issues/11163.
*  [x] Review and merge https://github.com/ckeditor/ckeditor5/pull/11236 to `ck/10294/reconversion`.
*  [x] Remember to merge corresponding CF pull request https://github.com/cksource/collaboration-features/pull/4261

Idea: Use the tool that @oleq wrote when working on inline images to extract merge commits from specific tickets to the `ck/10294/reconversion` branch.

**Comment by dawidurbanski** [comment]
> > * [x]  Create a changelog entry summing up all the changes.
> 
> Where is it done?

After consultation with @pomek I've been told that the merge message I prepared is enough for the changelog entry.

> > * [x]  Prepare merge commit message
> 
> Where is it done?

Here: https://github.com/ckeditor/ckeditor5/pull/11211

**Comment by Reinmar** [comment]
> After consultation with @pomek I've been told that the merge message I prepared is enough for the changelog entry.

Right :) Makes sense. Probably my mistake to have two actions for the same thing :)
