### ISSUE TITLE
Add a name with a space to the mentions guide demo

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#11182]
In #9741 we've introduced support for mentions with spaces. Let's show it in the demo by adding e.g. "Mary Ann" to the feed(s). For the further demos with the full name, this can be "Mary Ann Lewis" or something. Don't forget to update both the snippets responsible for the demos as well as the code examples and text in the guide.

**Comment by dufipl** [comment]
@AnnaTomanek I was thinking about the way how to include information about mentions with spaces functionality to our feature docs, and I propose adding one additional sentence to the configuration section. It might look like this: 
<img width="889" alt="Zrzut ekranu 2022-02-3 o 09 47 46" src="https://user-images.githubusercontent.com/32898551/152309864-0e9719ea-cfd6-4d40-b834-4eb2cb6d1989.png">
I was not able to find such information in the current version of docs so maybe it would be beneficial to add such a comment. What do you think about that?
