### ISSUE TITLE
Wrong plugin development guides order

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#11192]
## 📝 Provide a description of requested docs changes

In our docs we have the [Creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/creating-simple-plugin.html) guide which is a easiest possible introduction into making the plugin.

There are also more recent [Implementing a block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html) and other tutorials that expands on this. However, we first show these more complicated examples and after this we list the simpler guides.

![](https://user-images.githubusercontent.com/5353898/151970991-78b6f8ab-ac1f-4d62-8398-726190f9116e.png)

We should start with simplest things and carry the reader to more advanced things.

**Comment by godai78** [comment]
@mlewand what say you?

![](https://user-images.githubusercontent.com/68123541/153171533-fb7c9b88-b766-4945-8ab0-5a08c4885009.png)

**Comment by mlewand** [comment]
@godai78 I say this is the order that I'd expect :slightly\_smiling\_face: Interesting that you choose to change the category name, sounds good to me as well.

**Comment by godai78** [comment]
I proceed with it, then.

**Comment by godai78** [comment]
Merged in https://github.com/ckeditor/ckeditor5/pull/11255
