### ISSUE TITLE
How to add a link to CKEditor 5 editor programatically?

### ISSUE THREAD

**Issue by gkapoor121212** [ckeditor/ckeditor5#11199]
## Provide a description of the task
I am trying to port a CKEditor 4 plugin to 5 and while I am doing that I am not able to figure out how a link can be placed in the editor. Here is the code snippet I am using right now:
```
// Logic to convert input into a tweetable text.
const twitterBaseUrl = 'http://twitter.com/intent/tweet?';
const encodedValue = encodeURI( tweetableTextVal );
const linkUrl = twitterBaseUrl + 'text=' + encodedValue;

const linkElement = viewWriter.createAttributeElement( 'a', { linkUrl }, { priority: 5 } );
const innerText = viewWriter.createText(displayText, { linkHref: linkElement });
viewWriter.insert(viewWriter.createPositionAt(tweetableTextView, 0), innerText);
```

I got this hint from a thread on Stackoverflow. When this is executed only the link text gets placed but no anchor tag or href attribute is added. Here is the link for the [plugin](https://github.com/gkapoor121212/ckeditor5-tweetable-text) and the [editing](https://github.com/gkapoor121212/ckeditor5-tweetable-text/blob/master/src/tweetabletextediting.js) file which I have added.

_What steps should be taken to fulfill the task?_
It is a support request but not anything specific related to CKEditor5. Although, these can be documented somewhere.
## 📃 Other details

* Browser: Chrome
* OS: Mac
* CKEditor version: 5
* Installed CKEditor plugins: Tweetable Text

**Comment by FilipTokarski** [comment]
Hi, I'm not sure I fully understand the use case but did you try leveraging the existing link command? If you just want to insert a link with a given url at the current cursor/selection position, you could execute the [link command](https://ckeditor.com/docs/ckeditor5/latest/api/module_link_linkcommand-LinkCommand.html) like this:
```js
editor.commands.get( 'link' ).execute( 'http://example.com' );
```
