### ISSUE TITLE
Missing comma in the GHS configuration snippet docs

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11209]
## 📝 Provide a description of requested docs changes

In our GHS docs, in the configuration section, there is a missing comma after `allow`, so it will cause errors if someone decides to copy and paste the snippet.

![](https://user-images.githubusercontent.com/20988892/152490730-0d74624e-8e51-4812-856d-0bb8c19a4960.png)

**Comment by godai78** [comment]
Merged: #11227
