### ISSUE TITLE
Paste from Office should deduce start attribute value based on HTML passed from MS Word document / List start attribute / List break when content between them (table, image, etc.)

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11210]
## 📝 Provide detailed reproduction steps (if any)

1.  Open attached MS Word file ([cke paste example.zip](https://github.com/ckeditor/ckeditor5/files/8001632/cke.paste.example.zip)) and paste it into CKEditor 4 sample - https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html
2.  Next paste the same content into https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

### ✔️ Expected result

HTML lists despite being separated by other tags (in MS Word this is one list but in HTML these will be multiple lists) should keep the numbering just like in MS Word document.

### ❌ Actual result

CKEditor 4 does its job  
 

![obraz](https://user-images.githubusercontent.com/5314687/152507069-4cfec4ec-e877-429a-b4ed-03a2b945a83d.png)

but CKEditor 5 does not  
 

![obraz](https://user-images.githubusercontent.com/5314687/152507128-bbf270af-c817-40c1-ad08-6502dfbea9bb.png)

It seems that CKEditor 4 is capable of deduicng start attribute value based on below HTML:

```
<p class=MsoNormal style='margin-left:36.0pt;text-align:justify;text-indent:
-36.0pt;mso-list:l2 level1 lfo2'><![if !supportLists]><span lang=EN-CA
style='font-size:10.0pt;font-family:"Arial","sans-serif";mso-fareast-font-family:
Arial'><span style='mso-list:Ignore'>3.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span dir=LTR></span><u><span lang=EN-CA
style='font-size:10.0pt;font-family:"Arial","sans-serif";mso-fareast-font-family:
Arial'>Test3</span></u><span lang=EN-CA style='font-size:10.0pt;font-family:
"Arial","sans-serif";mso-fareast-font-family:Arial'><o:p></o:p></span></p>
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: from the very start
*   Installed CKEditor plugins: paste-from-office

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Here is a parsing of the start attribute for lists that have an explicit start set (it is defined in the stylesheet as a mso custom rule `@list ... mso-level-start-at: ...`:

https://github.com/ckeditor/ckeditor5/blob/9da565cb6a0b40a379a48940a34bfa93ba63257b/packages/ckeditor5-paste-from-office/src/filters/list.ts#L209-L211

Unfortunately, in the above case, this list numbering is not set explicitly. It is continuing the previous list and it's addressed by the same mso-list: inline style. We could assume that list items that share the same mso-list: value are a single list that should keep the numbering even if split by some other non-list elements.

**Comment by Witoso** [comment]
I am curious if this is how CKE4 interprets this. @Comandeer is it something you would be able to check?

**Comment by sbelms** [comment]
Is there a possible workaround for this?

**Comment by Witoso** [comment]
Not that we know of, it was added to our support queue.

**Comment by Mgsy** [comment]
Adding another case:

**MS Word**

![](https://github.com/ckeditor/ckeditor5/assets/20988892/5d4fac56-91de-4e04-a9af-50ac9ea0995c)

**CKE5 + PfOE**

![](https://github.com/ckeditor/ckeditor5/assets/20988892/895a620f-9f80-4bdf-bcdd-eb065784895d)

**Clipboard**

```html
<h2 style='margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1'><a
name="_yxjxqwegugl8"></a><![if !supportLists]><span lang=EN><span
style='mso-list:Ignore'>1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;
</span></span></span><![endif]><span dir=LTR></span><span lang=EN>Foo<o:p></o:p></span></h2>

<p class=MsoNormal style='margin-left:36.0pt'><span lang=EN-US>Some content<o:p></o:p></span></p>

<h2 style='margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1'><a
name="_ma5cm0u0bu46"></a><![if !supportLists]><span lang=EN><span
style='mso-list:Ignore'>2.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;
</span></span></span><![endif]><span dir=LTR></span><span lang=EN>Bar<o:p></o:p></span></h2>

<p class=MsoNormal style='margin-left:36.0pt'><span lang=EN-US>Some content<a
name="_57jx0jmqu774"></a><o:p></o:p></span></p>
```

**CKE5 (**[**PfOE demo**](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html#demo)**)**

```
<ol><li style="break-after:avoid;font-weight:normal;line-height:115%;margin:18pt 0cm 6pt 36.0pt;"><span style="font-family:Arial, sans-serif;font-size:16pt;"><span lang="EN" dir="ltr">Foo</span><o:p></o:p></span></li></ol><p style="line-height:107%;margin:0cm 0cm 8pt 36.0pt;"><span style="font-family:Calibri, sans-serif;font-size:11pt;"><span lang="EN-US" dir="ltr">Some content</span><o:p></o:p></span></p><ol><li style="break-after:avoid;font-weight:normal;line-height:115%;margin:18pt 0cm 6pt 36.0pt;"><span style="font-family:Arial, sans-serif;font-size:16pt;"><span lang="EN" dir="ltr">Bar</span><o:p></o:p></span></li></ol><p style="line-height:107%;margin:0cm 0cm 8pt 36.0pt;"><span style="font-family:Calibri, sans-serif;font-size:11pt;"><span lang="EN-US" dir="ltr">Some content</span><o:p></o:p></span></p>
```

**CKE4 (**[**PfO demo**](https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html)**)**

```
<ol style="margin-top:24px; margin-bottom:8px">
	<li style="margin-left:8px; margin-top:24px; margin-bottom:8px"><span style="font-size:16pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif"><span style="font-weight:normal"><a name="_yxjxqwegugl8"></a> Foo</span></span></span></span></li>
</ol>

<p style="margin-left:48px; margin-bottom:11px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Calibri,sans-serif">Some content</span></span></span></p>

<ol start="2" style="margin-top:24px; margin-bottom:8px">
	<li style="margin-left:8px; margin-top:24px; margin-bottom:8px"><span style="font-size:16pt"><span style="line-height:115%"><span style="font-family:Arial,sans-serif"><span style="font-weight:normal"><a name="_ma5cm0u0bu46"></a> Bar</span></span></span></span></li>
</ol>

<p style="margin-left:48px; margin-bottom:11px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Calibri,sans-serif">Some content<a name="_57jx0jmqu774"></a></span></span></span></p>
```

**Comment by Witoso** [comment]
We could experiment with this:

1.  If there are blocks between list items with the same ID we could add them as a block to the previous list item.
2.  As for the paragraphs after the last list item, we could deduce if they are part of the list by their `margin-left`.

**Comment by 108signals** [comment]
@Witoso were you able to conduct a test with this approach:

> We could experiment with this:
> 
> If there are blocks between list items with the same ID we could add them as a block to the previous list item.
> As for the paragraphs after the last list item, we could deduce if they are part of the list by their margin-left.
> The above could help us preserve "clean", semantic HTML, without the need to split the list to separate ol's. At the same time, it poses risks if we understand users' intentions well enough.

**Comment by Witoso** [comment]
This is in progress, we are investigating this option, but we don't have yet thoughts to share.
