### ISSUE TITLE
Description disappears - https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils.html

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#11214]
## 📝 Provide a description of requested docs changes
Something is incorrect with loading document: https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils.html
Description is visible for one second and then disappear.

**Comment by dufipl** [comment]
Hello @Madejczyk,
Thank you for reporting this issue. I can confirm that issue reproduces as shown below:
![docs disappear ](https://user-images.githubusercontent.com/32898551/152770238-0eaf6f56-122b-426f-b9cd-0183271808f8.gif)
 We will take a closer look at that.

**Comment by niegowski** [comment]
Please note that those functions are marked as protected and their visibility might be toggled by the button on the bottom of the screen.

**Comment by dufipl** [comment]
Yes, but it would be great to correct the rendering and in effect do not have blinking effect when loading the page.

**Comment by dufipl** [comment]
Yes, @Madejczyk we have to work on the rendering to avoid the blinking effect while loading the page but in general behaviour is correct.
As @niegowski said, you might toggle visibility in the bottom filters toolbar: 
<img width="389" alt="Zrzut ekranu 2022-02-7 o 11 55 41" src="https://user-images.githubusercontent.com/32898551/152775132-3270452e-61fb-4f3d-9e2b-0a01009eb521.png">
According to above, I'm closing this issue.
