### ISSUE TITLE
Karma throws an error if CC is "unknown"

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#11221]
## 📝 Provide detailed reproduction steps (if any)

Execute: 
```bash
node --max_old_space_size=8192 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test.js -f ckeditor5 --reporter=dots --production --coverage
```

which is a command that Travis uses to execute tests.

### ✔️ Expected result

Unknown/Zero coverage and no errors.

### ❌ Actual result

Unknown coverage and _Unexpected error while generating coverage report_.

### ❓ Possible solution

The coverage mechanism fails when CC is unknown.

It works fine if a package is covered:

```bash
node --max_old_space_size=8192 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test.js -f autoformat --reporter=dots --production --coverage
```

**Comment by psmyrek** [comment]
It looks like it is caused by the latest [`karma-coverage@2.1.1`](https://github.com/karma-runner/karma-coverage/releases/tag/v2.1.1) update (from 2022-02-05) which handles unexpected error during generating the code coverage differently since v2.1.1.
