### ISSUE TITLE
Docs: Add source editing to the markdown processor demo

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11231]
## 📝 Provide a description of requested docs changes

Currently, [our Markdown demo](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html) allows previewing the markdown output in a special box below the editor. However, if someone would like to test the markdown data processor and use some predefined markdown content, it would require using `editor.setData`, which might be difficult to discover for people without experience in CKEditor 5. Such a demo could be found in Source editing documentation, however, it would be hard to find if someone lands directly in the Markdown guide.

It would be nice to add Source editing to the demo with a proper infobox saying that Source editing is a separate plugin not required to use the Markdown data processor and explain how to enable support for other elements/attributes.

**Scope**

*   Add Source editing to the Markdown demo.
*   Add an info-box above the demo saying that Source editing is not a part of the feature and if the integrator would like to use it, it should be installed separately.
*   Add a new section about extending support for additional attributes/elements with GHS, e.g. when someone would like to support the `title` attribute on links (in Markdown, it would be represented as `[Something](https://foo.bar "My title")`.

**Comment by godai78** [comment]
Merged in #11238
