### ISSUE TITLE
Line break characters around <script> and <style> should be ignored

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#11248]
## 📝 Provide detailed reproduction steps (if any)

1. Set in Source Editing mode in `ckeditor5-html-support/tests/manual/ghs-all-features.html`:
```html
<p>
    x
</p>
<script>a</script>
<style>a</style>
<p>
    x
</p>
```
2. Retrieve the data back.

### ✔️ Expected result

Output is the same as the input.

### ❌ Actual result

Notice the extra paragraph with `&nbsp;` and `<style>` inside it:
```html
<p>x</p><script>a</script><p>&nbsp;<style>a</style></p><p>x</p>
```

**Comment by niegowski** [comment]
A very similar glitch happens to HTML comments.
