### ISSUE TITLE
The document with just `<script>` or `<style>` element becomes empty

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#11247]
## 📝 Provide detailed reproduction steps (if any)

In `ckeditor5-html-support/tests/manual/ghs-all-features.html`:

1. Set in Source Editing mode (whitespace before or after does not matter):
```html
<script>foo</script>
```
or 
```html
<style>foo</style>
```
2. Switch to regular mode and then back to source editing mode (or call `editor.getData()`).
### ✔️ Expected result

Same data as set.

### ❌ Actual result

Empty string.

**Comment by niegowski** [comment]
Seems like those model elements should be marked as `isContent` in the model schema (those do not contain any text, their content is stored inside a model element attribute).
