### ISSUE TITLE
[Conversion] Pre-release polishing of conversion system and its documentation

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11271]
### Why

In #10294 and #10911 we introduced many changes to the conversion system and completely new documentation for it.

The great majority of the work has been done and a nearly year-old feature branch has been merged to `master` recently.

We're now gathering internal feedback and feedback from early adopters. 

In this ticket we'll try to compile a list of improvements to be done before the release of these changes.

**Comment by godai78** [comment]
My notes and comments from the review process shall be added in this issue: #11275
