### ISSUE TITLE
Review new conversion docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11275]

**Comment by godai78** [comment]
For reference, this is the task scope that was covered: https://github.com/ckeditor/ckeditor5/issues/10911

**Comment by godai78** [comment]
https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/deep-dive/conversion/upcast.html

![](https://user-images.githubusercontent.com/68123541/154063244-1eecc5d4-48bb-4b68-871d-6cefdeaefeb1.png)

This ^ is the same snippet as the downcast guide. For the sake of clarity, it would look much better if these were switched around, i.e. the View left and the Model right instead.

**Comment by godai78** [comment]
Same file as above:

![](https://user-images.githubusercontent.com/68123541/154063452-833b96bb-0b11-42ce-92e7-d149bb34bacc.png)

**Comment by FilipTokarski** [comment]
> This ^ is the same snippet as the downcast guide. For the sake of clarity, it would look much better if these were switched around, i.e. the View left and the Model right instead.

I had exactly the same thoughts. I'm not sure if this would be so easy to achieve though, as this is the mini-inspector, but I also thought about adding some kind of arrow there, indicating which way the conversion goes.

**Comment by FilipTokarski** [comment]
I think that in _Model to view_ and _View to model_ sections, every time a helper is mentioned, we should link it to the corresponding detailed explanation in _Conversion helpers_ section.

**Comment by FilipTokarski** [comment]
These explanations are a great reference but I lack a bit a real-life scenario to sum up everything that has been said. If I want to add my custom element, how should I set up all the converters together inside a plugin? Could we add a section with a mini guide?

**Comment by godai78** [comment]
Some kind of demo to test out the newly gained knowledge?

**Comment by godai78** [comment]
@Reinmar - you may be interested in this ^.

**Comment by AnnaTomanek** [comment]
Am I right to think you missed the API docs in the scope of this task? #10911 is about the conversion docs only, but then the documentation branch was merged to #11211 where you can find the entire code as well as the API docs.

**Comment by godai78** [comment]
Only the guides were done so far, yes. Thanks for the PR, will make it much easier working on API.

**Comment by godai78** [comment]
OK, I'm done.

**Comment by FilipTokarski** [comment]
I added links for helpers. I'm done as well.
