### ISSUE TITLE
Odd error from Travis when publishing nightly docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1128]
https://travis-ci.org/ckeditor/ckeditor5/builds/399616072#L1388

![image](https://user-images.githubusercontent.com/156149/42237888-6c0f5cec-7eff-11e8-9b3d-df1a89dd6944.png)

This error doesn't mean that the docs are not built (https://github.com/CKEditor5/ckeditor5.github.io/commit/e2ff28942702f8e9119ab80f7213bfecf120d63a looks good), but it looks bad and is confusing.

**Comment by pomek** [comment]
I don't think that it's error.

https://github.com/travis-ci/travis-ci/issues/5441#issuecomment-171986649

**Comment by pomek** [comment]
I spent some time trying to understand whether it is an error or something else.

I didn't find anything interesting. Many people say that this is just a side effect of `travis_wait` command.
