### ISSUE TITLE
[Styles dropdown] Create command for the styles dropdown feature

### ISSUE THREAD

**Issue by dawidurbanski** [ckeditor/ckeditor5#11296]
### **Why**

Implementation needed for [#5700](https://github.com/ckeditor/ckeditor5/issues/5700).

### **What** 

Based on the UI (#11269). Implement the engine layer of the feature.

### **Scope and other notes**

The UI part will come with a mock of a command.

In this task we should rewrite it. 

- Command properties:
    - value: which styles are applied (array of style names)
    - enabledStyles: array of all currently applicable styles (including the ones already applied)
    - disabledStyles: styles that are not available in this context
    - execute()
- Applying a style
    - TODAY: No block renaming (e.g. paragraph into heading)
        - For now: the heading style must be disabled when the caret is in a paragraph.
- **Multiple styles** vs single style
    - Should we allow applying multiple styles (e.g. “marker” and “big text”) to a single selection?: Yes.
    - The initial spec tried to oversimplify this and disallow applying multiple styles. But there are no strong reasons for going that far with simplification.
    - In fact, forcing single style only makes it harder when working with text attributes. Doable, but harder.
    - Let’s go with multiple styles from day one, as we’d go there anyway.
- Understanding which style can be applied in the current path
    - Styles are defined by HTML names
    - In the model, we have model element names
    - model ≠ HTML
    - There are even more tricky cases like figure>table>thead where 2 of these 3 elements don’t exist in the model
        - GHS handles these cases, but the command would need to figure out which attribute to use (htmlFigureAttributes, htmlAttributes or htmlTheadAttributes)
        - This case SHOULD NOT BE COVERED NOW (dropped in MVP1)
    - Information GHS’s data schema should be used here to map model and HTML element names

**Comment by oleq** [comment]
Closed in #11349.
