### ISSUE TITLE
(Bug report) The first symbol of each paragraph will be input repeatedly, when inputting with Chinese keyboard.

### ISSUE THREAD

**Issue by jinnnyang** [ckeditor/ckeditor5#11290]
## 📝 Provide detailed reproduction steps (if any)

1. Open the [ckeditor-demo](https://ckeditor.com/ckeditor-5/demo/) and remove the default content in the editor.
2. Switch the input method to Microsoft Pinyin input method
3. Press the '[' key

### ✔️ Expected result

Press once to appear a symbol，looks like:
![expected](https://user-images.githubusercontent.com/78803748/154267330-e255a397-9a68-4a99-8cc2-b664c3fc96f0.png)

### ❌ Actual result

Press once to appear two symbols！！！

![accually](https://user-images.githubusercontent.com/78803748/154267486-5158de6e-aa9b-4ba5-b5d0-67bf66bce74d.png)

## 📃 Other details

* Browser: Mirosoft Edge 98.0.1108.43
* OS: Windows 10 version 19044.1526

I came from another project called [trilium](https://github.com/zadam/trilium/issues/2659)(original issue) and initially found this bug in this editor project, but I also found the bug in your demo. More information:
- This bug doesn't happen all the time, but it happens quite frequently.
- This bug does not appear on edge browsers on android phones.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this problem ([tracking it here](https://github.com/ckeditor/ckeditor5/issues/8839)) as it's a part of a bigger issue with IME in general. Those issues will be resolved when we get back to work on [beforeInput](https://github.com/ckeditor/ckeditor5/issues/7462), which is currently high on our priorities list.  
I'll close this one as a duplicate.
