### ISSUE TITLE
Finding functionality of Find and replace plugin doesn't work in commentsOnly mode

### ISSUE THREAD

**Issue by disjunction** [ckeditor/ckeditor5#11303]
## 📝 Reproduction steps

1. install comments and find-and-replace plugins
2. enable `commentsOnly` mode

### ✔️ Expected result

Find and Replace toolbar button should be enabled and the find functionality should work, similarly as it does in readonly mode (see #9975)

### ❌ Actual result

- Find and Replace toolbar is disabled
- Even if forcefully enabled the find does nothing 

### ❓ Possible solution

It seems like `commentsonly` plugin only allows certain commands to be executed. Probably adding the find*-commands will solve it?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report!

cc @dawidurbanski I can see that find command has `affectsData: true`. Did we miss it or is there a reason for this?
