### ISSUE TITLE
Invalid code example in Mentions API documentation

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11306]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/latest/api/module_mention_mentioncommand-MentionCommand.html
2.  Try using code examples from the initial description.

### ✔️ Expected result

Mention gets inserted. 

### ❌ Actual result

Error gets thrown.

### ❓ Possible solution

In both code examples `range: model.createRange( focus, focus.getShiftedBy( -1 ) )` should be changed to   
`range: editor.model.createRange( focus, focus.getShiftedBy( -1 ) )`

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: N/A
*   Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by godai78** [comment]
Merged in #11310
