### ISSUE TITLE
TypeError: Cannot read property 'model' of undefined     at Proxy.$_setUpEditorEvents (ckeditor.js:formatted:1)     at ckeditor.js:formatted:1

### ISSUE THREAD

**Issue by fang2023** [ckeditor/ckeditor5#11313]
<template>
  <div class="home">
    <ckeditor
      :editor="editor"
      v-model="editorData"
      :config="editorConfig"
    ></ckeditor>
  </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";

import CKEditor from "@ckeditor/ckeditor5-vue";
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";

import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";

@Options({
  components: {
    ckeditor: CKEditor.component,
  },
  data() {
    return {
      editor: ClassicEditor,
      editorData: "<p>Content of the editor33.</p>",
      editorConfig: {
        plugins: [
          EssentialsPlugin,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin,
        ],

        toolbar: {
          items: ["bold", "italic", "link", "undo", "redo"],
        },
      },
    };
  },
})
export default class Home extends Vue {}
</script>

**Comment by DeepakTNG** [comment]
I am also experiencing the same error.

**Comment by O-Hooman** [comment]
this is also happen to me

**Comment by O-Hooman** [comment]
just solve it, in my case downgrade the Vue version to vue@3.2.30 if you using Vue 3

**Comment by fang2023** [comment]
> just solve it, in my case downgrade the Vue version to vue@3.2.30 if you using Vue 3

thanks

**Comment by wc-matteo** [comment]
> just solve it, in my case downgrade the Vue version to vue@3.2.30 if you using Vue 3

same issue and this solves it

**Comment by wc-matteo** [comment]
fixed by: https://github.com/ckeditor/ckeditor5-vue/releases/tag/v3.0.0

**Comment by pomek** [comment]
As @wc-matteo, we fixed the issue and released the new version of the Vue integration. I'm closing this issue as resolved.

**Comment by abduallahnoorsayket** [comment]
I am also experiencing the same error.
