### ISSUE TITLE
Support syntax highlighting in the Source Editing plugin

### ISSUE THREAD

**Issue by sunesimonsen** [ckeditor/ckeditor5#11312]
## 📝 Provide a description of the new feature

I would like a way to provide syntax highlighting and maybe a generally improved source code editing experience. It might be provided by an addition plugin that makes use a source code editor like [Monaco](https://github.com/microsoft/monaco-editor). A solution like that might require to lazy load Monaco and show it in a modal instead.  

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by sunesimonsen** [comment]
We managed to make our own integration plugin, it was super easy, so I'll just withdraw this feature request.

**Comment by Reinmar** [comment]
Awesome :) Would you be able to share with the community your solution? I know that more people were looking for this feature.

**Comment by sunesimonsen** [comment]
@Reinmar it is a bit hard to shared the actual source code editor as that is entangled with Zendesk stuff. But I guess  open sourcing a very simple plugin that calls out to open the source code editor could be done.

I'm basically just doing this:

```js
import Plugin from "@ckeditor/ckeditor5-core/src/plugin";
import ButtonView from "@ckeditor/ckeditor5-ui/src/button/buttonview";
import OpenSourceCodeEditorCommand from "./OpenSourceCodeEditorCommand";
import MarkupIcon from "@zendeskgarden/svg-icons/src/16/markup-stroke.svg";

export default class SourceCodeEditorPlugin extends Plugin {
  get pluginName() {
    return "SourceCodeEditor";
  }

  init() {
    const editor = this.editor;

    editor.commands.add(
      "openCodeEditorEditor",
      new OpenSourceCodeEditorCommand(editor)
    );

    this.createToolbarButton();
  }

  show() {
    this.editor.fire("openSourceCodeEditor");
  }

  createToolbarButton() {
    const editor = this.editor;
    const t = editor.t;

    editor.ui.componentFactory.add("openSourceCodeEditor", locale => {
      const button = new ButtonView(locale);

      button.set({
        isEnabled: true,
        label: t("Source code"),
        icon: MarkupIcon,
        tooltip: true,
      });

      this.listenTo(button, "execute", () => {
        this.show();
      });

      return button;
    });
  }
}
```

Then I'm listening for `openSourceCodeEditor` in the outside application. 

So I think it is mostly an example of how to do this that would be really useful.
