### ISSUE TITLE
The default configuration options for `ImageStyle` plugin are not properly cloned

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#11328]
## 📝 Provide detailed reproduction steps (if any)

It's difficult for me right now to prepare a few short steps to reproduce this bug, so let me just describe the problem.

The problem occurred during updating CKE5-related dependencies in the `ckeditor5-angular` repository, because one test started to fail in this line: https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/ckeditor.component.spec.ts#L324.

This test fails because unexpectedly the second component in this test also started to emit an error, but it shouldn't. The reason for this is that since CKE5 v29 we have an `ImageInline` plugin and the default options for `ImageStyle` have changed. It looks like they are not properly cloned when they are created, but they share the same arrays as `modelElements` in each editor, i.e. https://github.com/ckeditor/ckeditor5/blob/f52226ff5f6015c8736255debf1e39c2e0bb1ed3/packages/ckeditor5-image/src/imagestyle/utils.js#L47

### ✔️ Expected result

Editors do not share common properties.

### ❌ Actual result

Editors share common properties from `ImageStyle` plugin.

### ❓ Possible solution

Make sure that default options are properly cloned.

## 📃 Other details

* First affected CKEditor version: v29

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
A similar problem we had in the font-size feature: https://github.com/ckeditor/ckeditor5/blob/f52226ff5f6015c8736255debf1e39c2e0bb1ed3/packages/ckeditor5-font/src/fontsize/utils.js#L29-L39.

### Scope:

* Add getters for default options.
* Write a test that covers the change.

**Comment by Reinmar** [comment]
We'd need a better description of what's wrong from the editor's perspective (in the editor's code). This is, extending this:

> It looks like they are not properly cloned when they are created, but they share the same arrays as `modelElements` in each editor, i.e.

**Comment by Reinmar** [comment]
Actually, what's needed is – how to crash the editor without Angular. Naturally, Angular uses its API, but then how it uses its API to make it crash.

**Comment by psmyrek** [comment]
I probably did not describe the problem exactly.

The problem is not that the editor crashes. The problem is that if we have a context watchdog that watches over at least 2 editors, then an error in one of them causes that all of them are restarted (not as expected). The necessary condition for such incorrect reboots to take place is that each of these editors must have `Image` and `ImageStyle` plugins. The `ImageStyle` plugin shares some of its default options among all editor instances, but it should clone it.

I will prepare an integration test with `Watchdog` and `ImageStyle` plugins.
