### ISSUE TITLE
Image button : open a popup window

### ISSUE THREAD

**Issue by jpdupont** [ckeditor/ckeditor5#1132]
🆕 Feature request  or  Other
5.1  💻 Version of CKEditor

I would like to insert a popup window filled with the CMS existing images, from the "images" button of CKEditor 5.1.
How to replace the opening of the dialog (choice of file) by the opening of a popup window?

**Comment by Reinmar** [comment]
You can implement your own button and implement in it the logic that you want. You can find inspiration in:

* the original [Image upload button's code](https://github.com/ckeditor/ckeditor5-image/blob/master/src/imageupload/imageuploadui.js) when it comes to how to upload an image and insert it into the editor
* the [CKEditor 5 Framework's Quick start](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html#creating-a-simple-plugin) for how to create a button.
