### ISSUE TITLE
Sticky toolbar doesn't work correctly when editor is inserted inside element with scroll

### ISSUE THREAD

**Issue by milling** [ckeditor/ckeditor5#1133]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

CKEditor 5 10.1.0 classic build 

## 📋 Steps to reproduce

Using [this jsFiddle](http://jsfiddle.net/milling/wsrvakdg/), which contains an instance of CKEditor inserted inside an element with overfow:auto and a top margin

1. Set focus in the editor
2. Scroll down, and the toolbar doesn't follow along
3. Move focus out of the editor and focus again, and the toolbar is now visible and is stuck to the top of the editor when scrolling

## ✅ Expected result
The toolbar should stick to the top when scrolling down, without needing to remove focus and re-focus. It works fine when the scrolling element is body, like it is in the [demo on the ckeditor website](https://ckeditor.com/ckeditor-5/#classic).

**Comment by oskarwrobel** [comment]
Related https://github.com/ckeditor/ckeditor5-ui/issues/405.

**Comment by Reinmar** [comment]
Isn't it a DUP, @oskarwrobel?

**Comment by oskarwrobel** [comment]
Yep, it is.
