### ISSUE TITLE
Testing environment - upgrade Karma to the latest version

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#11337]
## 📝 Provide a description of the new task

As in the title, due to:

```
(node:60317) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
```

Unfortunately, Karma@6 introduced a few breaking changes that touch our env.

**Comment by pomek** [comment]
After upgrading to Karma 6, the following warning is reported:

```
16 03 2022 12:15:34.369:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.
```

**Comment by pomek** [comment]
### Scope

* Upgrade karma from 5 to 6
* When executing tests, it prints the deprecated warning.
* Rewrite a part of the code to drop the "deprecated warning".
* Make sure all supported options still work (see [the testing env. guide](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/contributing/testing-environment.html#running-automated-tests)).
* The [`intellijkarmarunner`](https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/ckeditor5-dev-tests/bin/intellijkarmarunner) plugin must work.
* Perhaps it's a good occasion to refactor the [`runautomatedtests.js`](https://github.com/ckeditor/ckeditor5-dev/blob/4b66ccf50809a6fe7559b029de78dc67663756a2/packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js#L122-L139) file (e.g. a function should not be defined as a string).

**Comment by pomek** [comment]
TODO: Report a follow-up issue for upgrading karma in the following repositories:

* Package generator
* Inspector
* Integrations (2x Vue, React, perhaps Angular too).

**Comment by psmyrek** [comment]
Issues for upgrading Karma have been created:
- Package generator
   https://github.com/ckeditor/ckeditor5-package-generator/issues/92
- Integrations
   https://github.com/ckeditor/ckeditor5-vue/issues/210
   https://github.com/ckeditor/ckeditor5-vue2/issues/18
   https://github.com/ckeditor/ckeditor5-angular/issues/308
   https://github.com/ckeditor/ckeditor5-react/issues/292
- Inspector
   (no issue, Karma is already up-to-date 🎉)
