### ISSUE TITLE
[Styles dropdown] Create the feature guide

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11331]
- We can take some inspiration from a CKE4’s guide for the Styles combo.
- Let’s have the minimum content for now:
    - E.g. “This feature allows you apply classes to existing elements in the content”
    - “This is how you configure it”
    - “This is how it looks”
- Meaningful example content
- Reasonable style examples
    - Block
        - Colored headings
        - Something for paragraphs too (e.g. callout?)
    - Object
        - Some table styles?
    - Inline
        - kbd, del, ins?
        - some “pill-like” style
- Inspiration:
    - Wikipedia
    - Blogs
    - Large documentation systems

**Comment by godai78** [comment]
The demo starts with "article category" style, hence the styles dropdown is fired like this:

![](https://user-images.githubusercontent.com/68123541/163572516-92979e92-755f-4b44-b7c1-d771b4dde7b4.png)

This is not the best-looking thing.  
  
Note to self - add balloon tooltip to dropdown.

**Comment by godai78** [comment]
Scratch that. I cheated. Also: the tooltip is already there.![](https://user-images.githubusercontent.com/68123541/163573558-90f3aff1-deb0-46fe-b14a-befecb5c9ebb.png)

**Comment by godai78** [comment]
The Sidequote style produces different results depending on the number of lines inside it:  
  
![](https://user-images.githubusercontent.com/68123541/164179396-55742748-47e7-46ad-b657-a051ab3845cb.png)![](https://user-images.githubusercontent.com/68123541/164179397-e792f8f2-0417-4ed2-b3e4-71994fed4501.png)![](https://user-images.githubusercontent.com/68123541/164179398-ffbe474b-24c4-4145-b821-7c34b4a9f165.png)
