### ISSUE TITLE
Insert SPAN Element

### ISSUE THREAD

**Issue by sarankup** [ckeditor/ckeditor5#1134]
Hi Team,

I am using CKEditor5 InlineEditor. I would like to insert <span> element at my cursor positon. By using the following code, I can insert paragraph. Please advise how to insert span element.

```
var myElem = writer.createElement( 'paragraph', { "data-cool": 'my-' }, text );
    writer.insert( myElem, GlobalEditor.model.document.selection.getFirstPosition() )
```

**Comment by Reinmar** [comment]
In exactly the same way. But you need to register this element in the schema and writer converters for it. Please refer to the [CKEditor 5 Framework Architecture](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/architecture/intro.html) guide and the code of existing features.

Also, please do note that bold, italic and other inline styles should be represented in the model as text attributes, not elements. You can find more about this in the linked guide.

**Comment by Gayudhaya** [comment]
my code was

 editor.model.change(writer =>{
                       const spanele = writer.createElement('span');
                      const docFrag = writer.createDocumentFragment();
                         writer.append(spanele,docFrag);
                        writer.insertText( 'myselectedtext', spanele );
editor.model.insertContent( docFrag );  
})
