### ISSUE TITLE
Cannot insert text before or after a widget inside a list item

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11353]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing`
2. Create a list with widget inside one of the list items
3. Try using fake caret to insert the text before or after the widget

### ✔️ Expected result

When using fake caret/pressing `enter` you are still in the same list item and are able to type.

### ❌ Actual result

A new paragraph is created, list gets split into two separate lists.

### Screencast

https://user-images.githubusercontent.com/34380544/155969120-93fd41cc-7fb5-4969-b7c9-bb177c5aa7dc.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Fixed on latest `ck/11198-make-sure-list-isnt-split`.

**Comment by oleq** [comment]
Closed in #11425.
