### ISSUE TITLE
List items misaligned and covered after aligning table or image to the left

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11361]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing`
2. Add a few list items
3. Add a table inside one of the list items
4. Align table to the left

### ❌ Actual result

LIst items are misaligned and covered by the table

https://user-images.githubusercontent.com/34380544/155997113-8cf1b8dc-43fa-4f21-9f1e-879ced3915e1.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
Same behaviour when aligning the image to the left:
![image overlapping](https://user-images.githubusercontent.com/32898551/156411269-df726489-c00b-4b3f-9a9e-77de6a596024.gif)

**Comment by Reinmar** [comment]
This is CSS. There are numerous tickets in which we tried to do something with this, but it's... CSS. They're going to fix this in 2033.
