### ISSUE TITLE
how to disable a default shortcut in CKeditor5?

### ISSUE THREAD

**Issue by RocSeb** [ckeditor/ckeditor5#11373]
## Provide a description of the task

how to disable a default shortcut in CKeditor5? for example I would like to delete CTRL+B which puts the selected characters in bold.*
Thank you in advance.

## 📃 Other details

* CKEditor version: 5
* Framework: Vue.JS
* Installed CKEditor plugins: ClassicEditor

**Comment by dawidurbanski** [comment]
You can provide your own keystroke handler for any shortcut like shown in the docs: https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#member-keystrokes

So in your case it could be something like this:

```js
function CustomCtrlB( editor ) {
	editor.keystrokes.set( 'Ctrl+B', ( data, cancel ) => {
		console.log( data.keyCode );
		cancel();
	} );
}

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ..., CustomCtrlB ],
		...
	} );
```

**Comment by RocSeb** [comment]
Thank you very much for your answer,
i'm just trying to allow the mark tag in preprocessing of ckeditor, as I failed, I modified the CSS of the strong tags to highlight the content when the component is loaded and I wanted to disable the shortcut so that you can't highlight words by doing CTRL+B

**Comment by Reinmar** [comment]
You can also just skip the Bold feature and (if you need to be able to process `<strong>`), use General HTML Support feature instead)
