### ISSUE TITLE
Angular 11 ckeditor5-build-inline  toolbar not showing

### ISSUE THREAD

**Issue by nadeemamin** [ckeditor/ckeditor5#11376]
## 📝 Provide detailed reproduction steps (if any)

1. … package json 
 "@ckeditor/ckeditor5-angular": "^2.0.2",
 "@ckeditor/ckeditor5-build-classic": "^32.0.0",
    "@ckeditor/ckeditor5-build-inline": "^32.0.0",
2. … import * as InlineEditor from '@ckeditor/ckeditor5-build-inline'  in editor component
 public Editor = InlineEditor;
 public editorConfig = { toolbar: {items: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', '|', 'indent', 'outdent', '|', 'blockQuote', 'insertTable', 'mediaEmbed', 'undo', 'redo']}, image: {toolbar: ['imageStyle:full', 'imageStyle:side', '|', 'imageTextAlternative']}, table: {contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells']}, language: 'en', link: { defaultProtocol: 'https://', } };

3.   html has  <ckeditor [editor]="Editor" 
        (change)="onChange($event)" 
        [(ngModel)]="htmlModel"
        [config]="editorConfig"
        ></ckeditor>
4. …

### ✔️ Expected result
editor should show with toolbar when editing. 
note: if i switch to ClassicEditor  it works fine. 
![image](https://user-images.githubusercontent.com/8780620/156258080-8b28d2c3-de0f-47fd-a26f-66a97f79a687.png)

_What is the expected result of the above steps?_

### ❌ Actual result
inline editor is showing without toolbar when field is edited 
![image](https://user-images.githubusercontent.com/8780620/156257695-bfbc5158-7291-427a-bb79-9d89e22d5ca5.png)

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: version 32.0.0
* Installed CKEditor plugins: …
"@ckeditor/ckeditor5-build-classic": "^32.0.0",
    "@ckeditor/ckeditor5-build-inline": "^32.0.0",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jswiderski** [comment]
Thank you for your report, however, please note that Github is not a place to report implementation problems. From what we can see you are licensed user and you have also reported this problem on our technical support channel. We will reply there.
