### ISSUE TITLE
[Issue tracker] Label for issues resolved a long time ago (can't assign a milestone)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11382]
### Why

When browsing old issues we often find ones that are already resolved for a long time.

We close such issues but then we need to assign either a milestone or a `resolution:` label. Otherwise, our ZH automation will be pinging us to take an action.

Example: #511

### What

I propose to agree to use a new label for that.

So far we have these:

*   `resolution:invalid` – I was sometimes using this label stretching its meaning to "an issue that was resolved in the meantime is not anymore a valid issue". But that's too far and loses the meaning (can be confusing for a person who sees it).
*   `resolution:expired` – No feedback from the issue author.
    *   BTW I can see there are two versions of this label: "expired" and "expires". It'd be good to clean this up.
*   `resolution:wontfix` – Rarely used for stuff we are sure we will never work fix.
*   `resolution:cantfix` – Rarely used for stuff we can't fix due to external limitations (e.g. browser bug or stuff outside our control like no content in the clipboard when pasting from Acrobat Reader).
*   `resolution:duplicate` – Clear. But interestingly, I'd sometimes use it in the aforementioned situation if I can find the ticket that resolved the issue (and was closed by then).

I miss something like `resolution:resolved`. I think it will be a time-saver, because doing archeology in order to be able to use `resolution:duplicate` is irritating.

**Comment by pomek** [comment]
+1 for `resolution:resolved.

**Comment by Reinmar** [comment]
Done: https://github.com/ckeditor/ckeditor5/labels/resolution%3Aresolved
