### ISSUE TITLE
HTML snippet does not work with document-list

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11385]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing`
2. Create a few list items
3. In one of the middle list items press `shift` + `enter` a couple of times 
4. Try to put HTML snippet into free place between list elements

### ✔️ Expected result

HTML snippet does not break document list and become part of one of list elements.

### ❌ Actual result

HTML snippet breaks the list and is not within any list element:
![document list HTML snippet issue](https://user-images.githubusercontent.com/32898551/156418404-4893d736-659a-4ef9-ba34-07ba94622ed6.gif)

## 📃 Other details

* Browser: Chrome, Firefox
* OS: Mac OS Monterey
* First affected CKEditor version: 32.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Fixed on latest `ck/11198-make-sure-list-isnt-split`.

**Comment by dufipl** [comment]
The fix is only partial, similar as shown here: https://github.com/ckeditor/ckeditor5/issues/11386#issuecomment-1085823671

**Comment by oleq** [comment]
Closed in #11425.
