### ISSUE TITLE
CKEditor inline toolbar issue

### ISSUE THREAD

**Issue by thomasFjorstad** [ckeditor/ckeditor5#11409]
## 📝 Provide detailed reproduction steps (if any)
1. I can not find a good solution for MarkDown here in this Editor.
I got duplicates of versions when I use the standard build, so I switch over to ckeditor5-editor-inline, and that's working.
BUT the toolbar is broken.

### ✔️ Expected result

Expected the normal toolbar

### ❌ Actual result

Big icons toolbar

### ❓ Possible solution

`/* eslint-disable @typescript-eslint/no-var-requires */
// import { CKEditor } from "@ckeditor/ckeditor5-react";
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
// import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import InlineEditor from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import { useState } from 'react';
import Markdown from '@ckeditor/ckeditor5-markdown-gfm/src/markdown';

export default function CKEditorComponent() {
    const [editorText, setEditorText] = useState('__BOLD__');
    const isEditing = false;
    return (
            <CKEditor
                editor={InlineEditor}
                config={{
                    plugins: [Paragraph, Bold, Italic, Essentials, Underline, Markdown],
                    toolbar: ['bold', 'italic', 'underline'],
                    contentEditable: true,
                }}
                data={editorText}
                onReady={(editor) => {
                    editor.ui
                        .getEditableElement()
                        .parentElement.insertBefore(
                            editor.ui.view.toolbar.element,
                            editor.ui.getEditableElement()
                        );
                    editor.ui.viewportOffset = {
                        bottom: 0,
                        left: 0,
                        right: 0,
                        top: 250,
                    };
                }}
            />

    );
}`

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, in order to look into this issue we need detailed steps to reproduce it, together with editor config, plugins used, etc. It would be also helpful if you could show some screenshots/screencasts of the problem.

**Comment by jswiderski** [comment]
Closing due to lack of feedback.
