### ISSUE TITLE
Migrate to beforeInput vol 2

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11438]
## 📝 Provide a description of the new feature

An epic for revival of #7462 and further work.

*   Feature branch: [`ck/epic/11438-migrate-to-beforeinput`](https://github.com/ckeditor/ckeditor5/tree/ck/epic/11438-migrate-to-beforeinput)
*   Draft PR: #11456

### ToC

*   #11448
*   #11626
*   #11636
*   #11736
*   #12058 
*   ckeditor/ckeditor5#11904
*   Post-MVP: #12425 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by wimleers** [comment]
@oleq Will this also address #2045?

**Comment by huzedong2015** [comment]
In the tracking mode, how long will this problem take? Currently, it seriously affects the use

**Comment by Reinmar** [comment]
> *   Check out the snapshot of the docs from June: https://ckeditor5.github.io/misc/ime-snapshot-220610/ckeditor5/34.1.0/

If you have any feedback, especially for CJK languages, we'll appreciate if you share it here. The earlier we know about something, the better :)

**Comment by Reinmar** [comment]
> *   Check out the snapshot of the docs from June: https://ckeditor5.github.io/misc/ime-snapshot-220610/ckeditor5/34.1.0/

If you have any feedback, especially for CJK languages, we'll appreciate if you share it here. The earlier we know about something, the better :)
