### ISSUE TITLE
[Styles dropdown] Finish converters for modifying html* attributes

### ISSUE THREAD

**Issue by dawidurbanski** [ckeditor/ckeditor5#11449]
### Why

At the moment GHS works only as a one-way transformation. We do accept general HTML elements and attributes. We create model from them and we generate data out of them.

Until now there was no need to modify already created GHS attributes stored in `htmlAttribues`. With the new [styles dropdown feature](https://github.com/ckeditor/ckeditor5/issues/5700) we need exactly this.

A [research](https://github.com/ckeditor/ckeditor5/issues/11260) to this topic was already made before. Here we try to implement it.

This issue is blocking https://github.com/ckeditor/ckeditor5/issues/11296.

### What

In the current state, if you try to update `htmlAttributes` with the `model.writer` it will work fine. It breaks when you try to remove it completely.

✅  Works fine:
```js
writer.setAttribute( 'htmlAttributes', { classes: [ 'one', 'two' ] }, selectedBlockElement );
```

❌  Breaks the editor:
```js
writer.removeAttribute( 'htmlAttributes', selectedBlockElement );
```

This happens because the `modelToViewBlockAttributeConverter()` does not support removing `htmlAttributes` causing `viewAttributes` to be `null`.

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-html-support/src/converters.js#L168-L183

We need to add support for removing `htmlAttributes`  in GHS converter .

### Scope

- Add tests in GHS to cover cases for modifying and removing `htmlAttributes`,
- Add tests to all integrations for these cases as well,
- Cover changing the value, and completely removing `htmlAttributes`,
- Add tests for changing values of text nodes attribute values,
- Implement / update converters to support the above cases.

**Comment by Reinmar** [comment]
Note: Classes and inline styles MUST be managed by `writer.setStyle()`, `writer.addClass()`, `writer.removeClass()`, etc. NOT BY `writer.setAttribute( 'class|style', ... )`.

**Comment by dawidurbanski** [comment]
We have a situation here with inline text attribute elements that there are two opposing approaches, and we need to decide on one of them for the time being.

Let's say we have some text attribute element (for example `<cite>`) which has been enabled in GHS alongside with `classes` attribute.

If we have one in the content:

```html
<cite class="foo">bar</cite>
```

And now we somehow manipulate the `<htmlCite>` GHS model element, to remove all classes from it, it will become:

```html
<cite>bar</cite>
```

Or should it?

_____________

For the case of styles dropdown, which this ticket is part of, one may say that such scenario:

```html
[bar]
```
-> apply style: `element: cite, class: foo`

```html
[<cite class="foo">bar</cite>]
```
-> remove style: `element: cite, class: foo`

```html
Should become

[foo] not [<cite>bar</cite>]
```

The first one makes more sense in this case, because just applying and removing style should result in the same model as before applying.

Case can be made for both: leaving the element with no classes or removing element completely.

@niegowski We had this discussed. If you can chime in it would be welcome.

**Comment by dawidurbanski** [comment]
Just FYI, for now I went with the styles dropdown preferred way, which is removing attribute element when we get no attributes after update.
