### ISSUE TITLE
Mac multiline text replacement shortcuts not working

### ISSUE THREAD

**Issue by slotterbackW** [ckeditor/ckeditor5#11443]
## 📝 Provide detailed reproduction steps (if any)

On macs, you can create multiline text replacement shortcuts. (See accepted answer here: https://superuser.com/questions/1541755/multi-line-text-replacement-on-macos-or-ios). When using these shortcuts in CKEditor the shortcuts aren't expanded.

For example, if my shortcut is: `mline` which is replaced with:
```
make

multiline

magic
```

(Only the first line of the shortcut is displayed)
![image](https://user-images.githubusercontent.com/14916556/157513490-435a20c7-1f8e-4858-848a-dfe52f945f15.png)

then when using that shortcut in CKEditor:
![Screen Shot 2022-03-09 at 12 06 54 PM](https://user-images.githubusercontent.com/14916556/157513667-61ec0c5b-c759-4dba-8594-91299d486f24.png)

the result is:
![Screen Shot 2022-03-09 at 12 06 58 PM](https://user-images.githubusercontent.com/14916556/157513694-f516813f-1116-4046-8ccf-9b2cbc6f4432.png)

### ✔️ Expected result

The shortcut is expanded and all lines are entered into the editor.
![image](https://user-images.githubusercontent.com/14916556/157513828-9abe4905-7ab4-453e-9efa-e18099faa633.png)

### ❌ Actual result

Only the first line is inserted:
![Screen Shot 2022-03-09 at 12 06 58 PM](https://user-images.githubusercontent.com/14916556/157513712-dd4acb12-041a-4916-a8f9-e4ef037aa70d.png)

### ❓ Possible solution

I'm pretty sure Apple doesn't really support multiline shortcuts, however, you can sort've trick the text replacement input field into using a multiline shortcut by seperating lines with soft-breaks. My guess is that something with the soft-break is messing up some logic in CKEditor.

## 📃 Other details

* Browser: Chrome Version 98.0.4758.109 (Official Build) (x86_64)
* OS: macOS Big Sur 11.6.2
* First affected CKEditor version: …
* Installed CKEditor plugins: was able to reproduce on the classic editor build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jswiderski** [comment]
I have checked the problem and the MAC feature is working fine inside native contenteditable element or CKEditor 4 but not in CKEditor 5.
