### ISSUE TITLE
[b͓̲̐͐͐̐̑e̩̼͕͈̗ͥ̄̑f̲̮̠ͯor̗̲͕̝ͨ̑̆̉͆e̬̜inp̖̗̦͆ͤu̗̞̬̺̮t͎] Revive the old beforeinput branch

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11448]
## Provide a description of the task

The branch has tons of refactoring in it that does not make sense anymore because all browsers support beforeinput and mutation observer is no longer needed. Merging master into it means hell and it's not worth it.

https://github.com/ckeditor/ckeditor5/tree/i/7462-beforeinput-wip

**Comment by Reinmar** [comment]
Available now in https://github.com/ckeditor/ckeditor5/pull/11456
