### ISSUE TITLE
Research possibility to use donut CSS rule to exclude pieces of DOM from our CSS reset

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11451]
The case is that someone may want to use their UI inside our UI. Their UI may expect no reset rules to be used.

How can they say that starting from some container our CSS reset rules should not apply?

**Comment by Reinmar** [comment]
The idea to verify is changing

```
.ck.ck-reset_all *
```

to:

```
.ck-reset_all *:not(.ck-reset_exclude *)
```

**Comment by Reinmar** [comment]
Does it work? Doesn't it change the rule's specificity (which would break some other styles that rely on the reset having specificity 020)? Does it really allow switching of the reset rules inside the `.ck-reset_exclude` container?

**Comment by oleq** [comment]
*   Both selectors have specificity 0,2,0.
*   I named the class `.ck-reset_all-excluded`.
*   PR in #11461 (with manual test).
*   Needs QA.

**Comment by oleq** [comment]
If the PR is merged, there's an optional followup about taking advantage of this feature #11462.
