### ISSUE TITLE
a fake container is added to textarea

### ISSUE THREAD

**Issue by Just1pman** [ckeditor/ckeditor5#11453]
a fake-container is added to textarea, the best way is not to insert it into textarea but ignore it

**Comment by Reinmar** [comment]
I'm sorry, but I do not understand what is the issue. Please open a new issue by using the [template for a bug report](https://github.com/ckeditor/ckeditor5/issues/new?assignees=&labels=type%3Abug&template=1-bug-report.md&title=) and fill all sections.
