### ISSUE TITLE
CKEditor + Magnific Popup. Link editing does not work

### ISSUE THREAD

**Issue by DarkRiDDeR** [ckeditor/ckeditor5#1147]
🐞 Bug report 

## 💻 Version of CKEditor ckeditor5 10.1.0

Hello. Link editing does not work. How can I solve this problem?

Example https://codepen.io/anon/pen/vaEBKe

**Comment by dkonopka** [comment]
Yes, it's true, [here is bootstrap4 & CKE5demo](https://codepen.io/k0n0pka/full/yqBXOz/) after clicking link URL there is no way to edit or create new one.

**Comment by Reinmar** [comment]
I haven't debugged this issue, but with CKE4 we had to use a hack to stop Bootstrap from stealing focus from our controls: https://stackoverflow.com/questions/31678662/ckeditor-issue-with-bootstrap-modal/31679096

Most likely, a similar hack needs to be developed to make CKE5 work in Bootstrap and other libraries which provide modals.

**Comment by Reinmar** [comment]
And it's not a bug of CKEditor 5, so I'm re-labeling this to a question.

**Comment by DarkRiDDeR** [comment]
Thank you. Solution:
``$.magnificPopup.instance._onFocusIn = function(e) {
  if( $(e.target).hasClass('ck-input') ) {
     return true;
  } 
  $.magnificPopup.proto._onFocusIn.call(this,e);
};

**Comment by dkonopka** [comment]
FYI: for bootstrap 4 there are three ways to solve "stealing focus":

1) Set modal option focus to false: https://getbootstrap.com/docs/4.1/components/modal/#options
2) `$.fn.modal.Constructor.prototype.enforceFocus = function () {};`

**Comment by ytliuSVN** [comment]
I am unable to edit links on CKEditor. The Link dialog window was covered by the Bootstrap modal.

![image 8](https://user-images.githubusercontent.com/13102859/43234976-991b6f50-90b1-11e8-9ad1-fa09160c30c1.png)

Here is what I try so far:
[https://jsfiddle.net/ytliuSVN/ox8hvs1w/](https://jsfiddle.net/ytliuSVN/ox8hvs1w/)

Any help would be appreciated!

**Comment by Reinmar** [comment]
@dkonopka, your codepen isn't complete. Z-index is fixed, but there's still a focus problem:
![jul-26-2018 10-39-36](https://user-images.githubusercontent.com/156149/43251440-354e9100-90c0-11e8-8442-d4ad389639b4.gif)

**Comment by dkonopka** [comment]
☝️ I've updated demo, it's working now (I mean stealing focus problem).

**Comment by oleq** [comment]
@lcetinsoy If the library causes the issue and provides no configuration, I'm afraid there's hardly anything we can do to help you out. It's the problem of the library, not CKEditor 5. 

Check out [this article](https://hackernoon.com/finding-that-pesky-listener-thats-hijacking-your-event-javascript-b590593f2a83), maybe you'll figure out what exactly happens when the focus is stolen. You could then fork the library and implement some mechanism that prevents that.

**Comment by dkonopka** [comment]
@lcetinsoy [We've created a demo with Materialize.css](https://codepen.io/ckeditor/pen/gZebwy), it's all about `dismissible: false` option.

**Comment by riajha1** [comment]
I am unable to edit link in modal pop using angular -- import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

please help !

**Comment by riajha1** [comment]
I am unable to edit link in modal pop using angular -- import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
please help !
@Reinmar @lcetinsoy 
@nicolasiac @oleq @dkonopka @dkonopka @Reinmar @ytliuSVN @dkonopka  @ytliuSVN

**Comment by nicolasiac** [comment]
Does not work when ckeditor is in popup! You need to create a custom popup, by just creating a div that is on top of the rest of your application (z-index) and place the ckeditor inside that.

**Comment by codythecoder-teslagovt** [comment]
For those with React + CKEditor 5 and using reactstrap/bootstrap modals:

1. set autofocus on your modal to false:
`<Modal autofocus={false} ...>`
2. add the following styling:
`:root {
  --ck-z-default: 100;
  --ck-z-modal: calc( var(--ck-z-default) + 999 );
}`

read more [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html#compatibility-with-bootstrap)

**Comment by reddyCe** [comment]
For BootstrapVue users:
 Add the 'no-enforce-focus' prop on the modal and set the z-index of .ck-balloon-panel to a value greater than your modal's z-index.

**Comment by AllMight0027** [comment]
> ☝️ [I've updated demo](https://codepen.io/k0n0pka/pen/yqBXOz), it's working now (I mean stealing focus problem).

Hey, getting 404, can you give another demo link, please.

**Comment by digilanceer** [comment]
> > ☝️ [I've updated demo](https://codepen.io/k0n0pka/pen/yqBXOz), it's working now (I mean stealing focus problem).
> 
> Hey, getting 404, can you give another demo link, please.

this code helped me

```javascript
  $(document).ready(function(){
      $.fn.modal.Constructor.prototype._initializeFocusTrap = function() {
        modal_this = this
        $(document).on('focusin.modal', function (e) {
          if (modal_this.$element[0] !== e.target && !modal_this.$element.has(e.target).length 
          && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_select') 
          && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_text')) {
            modal_this.$element.focus()
          }
        })
      };
  });
```

**Comment by SARM256** [comment]
> > ☝️ [I've updated demo](https://codepen.io/k0n0pka/pen/yqBXOz), it's working now (I mean stealing focus problem).
> 
> Hey, getting 404, can you give another demo link, please.

this code helped me

```javascript
  $(document).ready(function(){
      $.fn.modal.Constructor.prototype._initializeFocusTrap = function() {
        modal_this = this
        $(document).on('focusin.modal', function (e) {
          if (modal_this.$element[0] !== e.target && !modal_this.$element.has(e.target).length 
          && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_select') 
          && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_text')) {
            modal_this.$element.focus()
          }
        })
      };
  });
```

**Comment by SARM256** [comment]
> > ☝️ [I've updated demo](https://codepen.io/k0n0pka/pen/yqBXOz), it's working now (I mean stealing focus problem).
> 
> Hey, getting 404, can you give another demo link, please.

according to this [link](https://stackoverflow.com/a/76178988) if `data-focus="false"` did not work use `data-bs-focus="false"` instead.

**Comment by thn312** [comment]
> > > ☝️ [I've updated demo](https://codepen.io/k0n0pka/pen/yqBXOz), it's working now (I mean stealing focus problem).
> > 
> > 
> > Hey, getting 404, can you give another demo link, please.
> 
> first of all remove tabIndex from modal div and according to this [link](https://stackoverflow.com/a/76178988) add `data-focus="false"` or `data-bs-focus="false"` to it.

It works well. Thank you so much <3

**Comment by ChaitanyaBinmile** [comment]
autoFocus={false} enforceFocus={false} add these properties on Modal and it will work

**Comment by maneeshtiwari-ve** [comment]
Just Remove: tabindex="-1"

And Add: data-bs-focus="false"

I hope your Problem Solved :)
