### ISSUE TITLE
[GHS] document form MS Word causes error being thrown 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11477]
## 📝 Provide detailed reproduction steps (if any)

1. Open attached sample MS Word file.
2. Paste its contents into demo with GHS fully enabled - https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html#demo

[sample 2.zip](https://github.com/ckeditor/ckeditor5/files/8283116/sample.2.zip)

### ✔️ Expected result

Dosument gets pasted

### ❌ Actual result

JS error gets thrown -> CKEditorError: target[key] is undefined

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: 
* Installed CKEditor plugins: paste-from-office

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
We'll be working soon on a bug that throws the same error (#11450) so hopefully this issue will be resolved too.
