### ISSUE TITLE
Same heading with different classes: tags removed when reloading editor

### ISSUE THREAD

**Issue by Mattho25** [ckeditor/ckeditor5#1148]
Hi,

I encountered a problem while defining custom headings. As soon as we have more than one `p` or `div` tag, the editor is not working as expected. In fact, it works well at first glance, styles are applied and tags well present in the editing area. Saving it works well too. But once we want to edit a content containing these tags with different classes, ckeditor is transforming them all back to a simple `<p></p>` (even when we defined a `<div class="____"><div>`)

Exemple : 
```
heading: {
	options: [
		{ model: 'paragraph', view: "p", title: "Paragraph" },
		{
			model: 'lead',
			view: {
				name: 'p',
				classes: 'lead'
			},
			title: 'Lead',
			class: 'ck-heading_lead',
			priority: 'high'
		}
	...
```

It seems that ckeditor is not able to match the element it founds in the html content with a heading configuration. Is there something to do to avoid that? Thanks!

**Comment by jodator** [comment]
It looks like [problem with our docs](https://github.com/ckeditor/ckeditor5-heading/issues/110#issuecomment-404428705) - sorry for that. The updated [docs are on review](https://github.com/ckeditor/ckeditor5-heading/pull/111) so they'll land in upcoming release.

ps.: it should be `converterPriority` not `priority` as we recently updated [`ConverterDefinition` API](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_conversion_conversion-ConverterDefinition.html).
