### ISSUE TITLE
Introduce the multi-root editor build

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11493]
## 📝 Provide a description of the new feature

The multi-root editor is a perfect fit for specific use cases, however, we don't introduce an easy way to integrate it - it requires [creating the custom editor](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/custom-editor-creator.html), which might be difficult, time-consuming and hard to maintain.

It would be nice to introduce a new type of build for the multi-root editor.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by huzedong2015** [comment]
How long can it be realized

**Comment by huzedong2015** [comment]
@Mgsy This function is urgently needed

**Comment by Mgsy** [comment]
Hi @huzedong2015, unfortunately, due to our priorities and commitments, I can't promise any ETA. We will observe this feature request and track how many :+1: it receives. If it will become popular, we might consider adding it to our roadmap.

**Comment by huzedong2015** [comment]
I always have requirements, but my own construction is always wrong, so now I can only use the inline mode to solve it in disguise

**Comment by csxxbhm** [comment]
+1

**Comment by AxxxxxxA** [comment]
+1

**Comment by ViLi230** [comment]
+1+1

**Comment by nawein** [comment]
how to load and save comment data in predefined multi-root code

**Comment by scofalik** [comment]
Do you mean HTML comment feature (\) or do you mean Comments (collaboration) feature?
