### ISSUE TITLE
Unexpected token 'const'

### ISSUE THREAD

**Issue by winzig** [ckeditor/ckeditor5#1149]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Stock build of CKEditor balloon 10.0.

Starting July 4 we began seeing these errors in our Sentry logs (JS error tracking):

`Unexpected token 'const'`

It seems to only be generated by people using recent versions of Chrome on Windows. The error shows in Sentry like this:

<img width="694" alt="screen shot 2018-07-11 at 10 03 57 am" src="https://user-images.githubusercontent.com/127062/42588149-cd6806c2-84f1-11e8-8853-35aa76504de7.png">

Since we didn't change anything in July, with a sudden spike in this error, I would have expected maybe it was generated by a new browser release that has a bug of some sort, but we're seeing it in Chrome versions 57–64.

Does anyone have any insight that might explain the sudden influx of these errors?

**Comment by Reinmar** [comment]
We haven't seen this on our side. And it's the first time it got reported as well. Let's wait and see.

For the reference – how did you install that build?
