### ISSUE TITLE
track-changes-suggestion-data-mismatch

### ISSUE THREAD

**Issue by shaklin-essenvia** [ckeditor/ckeditor5#11508]
## 📝 Provide detailed reproduction steps (if any)

1. I have been following this [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html#implementation) and currently getting [track-changes-suggestion-data-mismatch](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-track-changes-suggestion-data-mismatch) not sure what is wrong and neither the error nor the description is helpful in debugging the issue any help to resolve the issue would be great.

To add to it, i inspected both the data which was generated and saved in backend, there is no changes.

### ✔️ Expected result

_What is the expected result of the above steps?_
No Errors

### ❌ Actual result
`track-changes-suggestion-data-mismatch` error

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by imtiazwazir** [comment]
Same here, anyway to resolve this?

<img width="1526" alt="Screenshot 2022-03-30 at 1 42 44 AM" src="https://user-images.githubusercontent.com/1964969/160703790-5e101360-51f2-4520-a5d5-09763668fca0.png">

**Comment by FilipTokarski** [comment]
Hi, thank you for the reports. Track Changes is a premium plugin and this issue tracker is mainly for the purpose of the open source part of the project. If you are a licensed user or using a trial version and encounter any problems when integrating Track Changes, we highly recommend to contact us via [the official support channel](https://ckeditor.com/contact/). Our support team will analyse the problem and get back to you as soon as possible.

**Comment by Mgsy** [comment]
The conversation has been moved to the support channel.

**Comment by huzedong2015** [comment]
I also encountered this problem. How can I solve it

**Comment by Mgsy** [comment]
Hi @huzedong2015! It would be appreciated if you could [send a message](https://ckeditor.com/contact/) to our support team and describe the issue - we will get back to you and help solve the problem.
