### ISSUE TITLE
Moving render calls out of EditorUIView constructors

### ISSUE THREAD

**Issue by alexeckermann** [ckeditor/ckeditor5#1150]
_**Other - Comment/Feedback**_

A problem arose when I was testing the [alexeckermann/ckeditor5-emptyness](https://github.com/alexeckermann/ckeditor5-emptyness) plugin where I wanted to extend the editors view template to bind a class name to a property.

The initial implementation passed with the `ClassicEditor` as the test case. However, when subsequently integrated into a project using a `BalloonEditor` it hit a wall because the plugin couldn't call to extend a template that was already rendered.

In debugging I came across an inconsistency which explained why the classic editor passed and why the balloon editor didn't. The classic editor does not call any methods in its `constructor` that render the `InlineEditableUIView` instance. That, the `ClassicEditorUIView` defers calls to add a child view until its own `render` is called.

[`BalloonEditorUIView`](https://github.com/ckeditor/ckeditor5-editor-balloon/blob/8779438f0ba70986d277d539e6c03edc565e9c84/src/ballooneditoruiview.js#L37), [`InlineEditorUIView`](https://github.com/ckeditor/ckeditor5-editor-inline/blob/2a193daca4440178ee614c04884e47c9b55a9400/src/inlineeditoruiview.js#L135), and [`DecoupledEditorUIView`](https://github.com/ckeditor/ckeditor5-editor-decoupled/blob/2d748b005634e2192b6bf4158ae34b8b2d300969/src/decouplededitoruiview.js#L64) all call `registerChild` with the `InlineEditableUIView` in their constructor.

Is it possible that any child view (or specifically editable views) rendering is moved to `render` and not called in scope of `constructor`?

I suspect there may be some wider ramifications of such a change I may not be aware of, so I'm raising it for comment/feedback.

**Comment by Reinmar** [comment]
cc @oleq @oskarwrobel

**Comment by Reinmar** [comment]
cc @oleq @oskarwrobel @jodator

**Comment by oleq** [comment]
Sounds like a good idea to me. I hope what we have ATM (like registering children in the constructor) is purely accidental.

**Comment by alexeckermann** [comment]
Fantastic.

If theres no class depending on a views element being available in that scope and placing `registerChild` in `render` is appropriate then it could be ok to move.

In a basic test on my local development environment I moved `registerChild` to `render` in the balloon editor with passing automated and manual tests. If that is acceptable then maybe I can go ahead and start some PRs?

**Comment by oleq** [comment]
> If that is acceptable then maybe I can go ahead and start some PRs?

Sure, you're welcome! 👍

**Comment by alexeckermann** [comment]
There's a potential conflict.

In these editors there is a computed property `editableElement` which will return `null` until the parent is rendered. Is this an acceptable condition?

Noticed this in the `InlineEditorUIView` tests as being a problem -- same test for `editableElement` not present in the `BalloonEditorUIView`.

**Comment by oleq** [comment]
Huge 👏 for your contribution, @alexeckermann!

**Comment by alexeckermann** [comment]
🍻 Cheers @oleq
