### ISSUE TITLE
Standard cell td gets converted to header cell th when both are placed inside tbody tag

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11536]
## 📝 Provide detailed reproduction steps (if any)

1. Use below source code to initialise the editor (according to https://validator.w3.org/nu/ this HTML is valid)
```
<table>
<tbody>
<tr>
<th> </th>
</tr>
<tr>
<td> </td>
</tr>
</tbody>
</table>
```

### ✔️ Expected result

One row should contain `th` and the other `td` tags.

### ❌ Actual result

Both rows contain `th` tags
```
    <table>
        <tbody>
            <tr>
                <th>
                    &nbsp;
                </th>
            </tr>
            <tr>
                <th>
                    &nbsp;
                </th>
            </tr>
        </tbody>
    </table>
```
### ❓ Possible solution

The workaround is to use place rows with `th` tags inside `thead` section:
```
<table>
<thead>
<tr>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
</tr>
</tbody>
</table>
```

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: N/A
* Installed CKEditor plugins: table

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ChristopherChudzicki** [comment]
I'm running into what I think is the same issue when making body rows the headers. Below, note that the 2nd row (A1, B1, C1) turns into a header row.

https://user-images.githubusercontent.com/9010790/165175296-0fc173a5-bd7b-477b-97cf-02589e500659.mov

Thanks for CKEditor—it's great!

**Comment by karlshea** [comment]
This happens regardless of any thead/tbody structure.

I have complicated tables that need to be entered through Drupal using CKEditor 5 which have both header columns and rows, but CKEditor is converting all `<td>` tags to `<th>`.

**Comment by wimleers** [comment]
Also reported by @karlshea against Drupal — tracking this upstream blocker at https://www.drupal.org/project/drupal/issues/3339763.

**Comment by Reinmar** [comment]
Let's merge this into #3172

**Comment by wimleers** [comment]
And #3172 landed, so updated the `drupal.org` issue: https://www.drupal.org/project/drupal/issues/3339763#comment-14957663 🥳
