### ISSUE TITLE
[Docs] Add required JWT payload properties to collaboration token endpoint guide

### ISSUE THREAD

**Issue by alexeckermann** [ckeditor/ckeditor5#1154]
_**Other - Documentation addition**_

On the [Creating token endpoint](https://docs.ckeditor.com/cs/latest/guides/token-endpoints/tokenendpoint.html) guide for collaboration services, under [Creating tokens for CKEditor Cloud Services](https://docs.ckeditor.com/cs/latest/guides/token-endpoints/tokenendpoint.html#creating-tokens-for-ckeditor-cloud-services) there should be a list of required payload properties.

- `iss`
- `iat`
- `user` with the minimum CS needs
- `services` with `ckeditor-collaboration`

Whilst that is mostly self explanatory given the purpose of the token to provide permissions and user info, there was one small annoyance in a typical/default implementation using `ruby-jwt` where `iat` will not be defined in the payload. This raises an `Invalid token` error in CK with no detail that it was the missing `iat` property.

It was a minor hiccup in our implementation, it didn't take much time to identify and fix, but we could spare others the time to figure out the issue in future with this minor addition to the guide.

I couldn't find the repo location of these guides, as I would have happily submitted a PR.

**Comment by Reinmar** [comment]
cc @pjasiun @czerwonkabartosz

**Comment by pjasiun** [comment]
Actually cc @wwalc, who is the author of this guide.
