### ISSUE TITLE
[Document list] Improve deleting block widgets in nested lists

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11543]
Part of #11377.

## 📝 Provide a description of the improvement

**Update**: I checked this briefly again on the epic branch and it looks better. Perhaps this issue is no longer relevant, needs confirmation.

---

In #11346, the handling of delete was improved for lists by leaving everything up to the widget plugin.

This is not always the best strategy, though. It results in a bad UX with nested lists. Take a look:

![](https://user-images.githubusercontent.com/1099479/161246091-7a5b36e8-d802-4fb3-b871-64e21f9c1897.gif)

I'd rather expect the lowest level of the list ("a", "b") to be unaffected and the selection moved to "aa\[\]" on backspace instead.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
No longer reproducible. Closing.

https://github.com/ckeditor/ckeditor5/assets/9881379/d9830c37-c7ad-4d78-8027-f070b00a538b
