### ISSUE TITLE
Image is not inserted via 'Insert image' button when selection is inside table cell

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#1155]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`v10.1.0`

## 📋 Steps to reproduce

It basically started when I have discovered that you can use `Insert image` button when some image caption is selected. The new image is then inserted before/after image which caption was selected. Works fine but maybe we could consider just disabling `Insert image` in such cases? Anyway, same can be done when selection is inside table cell, but then image is simply not inserted at all.

1. Go to https://docs.ckeditor.com/ckeditor5/latest/examples/builds/document-editor.html.
1. Focus any table cell.
1. Click `Insert image` button and insert an image.

![image5](https://user-images.githubusercontent.com/1061942/42685618-c671a6c2-8693-11e8-8b39-eec3de442d57.gif)

## ✅ Expected result

Image is inserted before/after/inside table? Alternatively button is disabled.

## ❎ Actual result

Nothing happens.

## 📃 Other details that might be useful

Tested on Chrome `67.0.3396.99`.

**Comment by Reinmar** [comment]
Wasn't it reported yesterday that this button should be disabled?

**Comment by f1ames** [comment]
Awwww, it was here - https://github.com/ckeditor/ckeditor5-image/issues/225, closing.
