### ISSUE TITLE
I can't paste tables and text at same time

### ISSUE THREAD

**Issue by vitor-99** [ckeditor/ckeditor5#11558]
I know I need to use Ctrl + shift + v to paste from word, and this work. Unfortanally, when I use this command, the tables turn into text :/. I would like the text and tables remain the same

**Comment by FilipTokarski** [comment]
Hi, `ctrl+shift+v` pastes the content as plain text, to preserve the styling use just `ctrl+v`.

**Comment by vitor-99** [comment]
Yes! But when I use ctrl + v, the text isn't pasted, only the table

**Comment by FilipTokarski** [comment]
I cannot reproduce this. 
Could you add detailed steps on how to reproduce the issue, console errors if any, editor configuration, plugins used, os, Word version, etc. The more details the better. It would be also nice to see some screencast/screenshot of the problem if that's possible.
Also, are you able to reproduce this on our [paste from Word docs](https://ckeditor.com/docs/ckeditor5/latest/features/export-word.html) or only in your environment?

**Comment by vitor-99** [comment]
Actually, it was bug of my text editor! I try a lot of things, but I dont think change him... Sorry for this. I will close the question.
