### ISSUE TITLE
Incorrect html output from code block with text part language plugin enabled

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#11563]
## 📝 Provide detailed reproduction steps (if any)

1. Open the `all-features` manual test.
2. Remove the whole content and add a single code block with some text.
3. Call `editor.getData()`

### ✔️ Expected result

It should return the following data:
```
<pre><code class="language-plaintext">foo</code></pre>
```

### ❌ Actual result

It returns the following data:
```
<span lang="plaintext" dir="undefined"><pre><code class="language-plaintext">foo</code></pre></span>
```

Note: If the code block has a different language set (e.g c++), then the lang attribute in the span will have the chosen language value.

## 📃 Other details

* Browser: any
* OS: any
* First affected CKEditor version: current `master` branch, it works correctly in v33 editor
* Installed CKEditor plugins: CodeBlock, TextPartLanguage (it works correctly without text part language plugin)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
This is the root cause of #11538.
