### ISSUE TITLE
Issue typing Korean after two space characters

### ISSUE THREAD

**Issue by slotterbackW** [ckeditor/ckeditor5#11569]
## 📝 Provide detailed reproduction steps (if any)

When typing Korean in CKEditor, after typing two spaces vowels stop being combined.

1. Set keyboard language to 2-set Korean
2. Press "d", "k", "t" keys on keyboard
3. Notice vowels are combined into a single character
4. Press space twice
5. Type "d", "k", "t" again.
6. Notice vowels are not combined

![korean_ime_bug](https://user-images.githubusercontent.com/14916556/161845850-05d215b0-20c0-4dc3-bf54-43bed5fcf219.gif)

### ✔️ Expected result

The vowels should be combined again, and produce the same character which was produced when typing them before the spaces.

### ❌ Actual result

The vowels are not combined.

## 📃 Other details

* Browser: Chome
* OS: MacOS 11.6.2
* First affected CKEditor version: …
* Installed CKEditor plugins: Reproducible on classic editor and possibly others?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of issues with IME and we plan to address them in [migration to `beforeInput`](https://github.com/ckeditor/ckeditor5/issues/7462), which is currently very high on our priority list.

**Comment by Acrophost** [comment]
The issue is no longer reproducible on branch `ck/11438-beforeinput-ime-research-vol1.1-android`

**Comment by joniel** [comment]
Still problems...
even in ckeditor hompage too... T_T;

**Comment by Witoso** [comment]
Related issue reported for Android Chrome: #13693.

**Comment by niegowski** [comment]
The work for this issue and others related is completed in the https://github.com/ckeditor/ckeditor5/pull/16289, and we finalized the round of internal (successful) tests. I encourage everyone to test the PR if you have a chance. It should be merged in the following days, and will be a part of the next release.
