### ISSUE TITLE
[Style dropdown] Stabilization

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11574]
This issue aggregates bugs and improvements to the ckeditor5-style feature.

# ToC

*   [x] #11607
*   [x] #11576
*   [x] #11581
*   [x] #11584
*   [x] #11582
*   [x] #11575
*   [x] #11588
*   [x] #12441 
*   [x] #11748
*   [x] #11578
*   [x] #11585
*   [x] #11590
*   [x] #11580
*   [x] #11709

**Comment by jameswilson** [comment]
Should [#13341](https://github.com/ckeditor/ckeditor5/issues/13341) be added to this list?

**Comment by wimleers** [comment]
+1

**Comment by Witoso** [comment]
Closing this to add it to the iteration in which we fixed a significant amount of issues. Tracking further improvements here: https://github.com/ckeditor/ckeditor5/issues/14274.
