### ISSUE TITLE
[Style dropdown] Missing integration for block quotes

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11576]
![Screenshot 2022-04-07 at 10.21.06.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/b638e2ad-ee36-4de3-8c45-64098d475456)

It works in the upcast but the command (and the UI that works on top of it) does not allow for any interaction. I guess this could be more that just block quotes: AFAIR the command starts from `getSelectedBlocks()` which is shallow and does not include selection parents so this could spread to the nested editable > widget case and others.

**Comment by wimleers** [comment]
I was going to report this one! 😄  Thanks for fixing it before I could 🤓 Thanks — linking here from https://www.drupal.org/project/drupal/issues/3222797#comment-14505686 _and_ from Drupal core code, to ensure we expand our test coverage once we update to a release of CKEditor 5 that includes this. 👍
