### ISSUE TITLE
[Style dropdown] Incorrect style retained after creating a new paragraph

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11578]
## 📝 Provide detailed reproduction steps (if any)

1. Open style plugin manual test
2. Create a H1 heading and apply `Large heading` style
3. Press `Enter`

### ✔️ Expected result

A new paragraph with no style is created.

### ❌ Actual result

A new paragraph with `Large heading` style is created (although it's not possible to do it with the dropdown). You are not able to simply turn it off. You need to change paragraph to H1, turn off the style and again change H1 to paragraph.

### Screencast

https://user-images.githubusercontent.com/34380544/162154462-f4b5ed97-66b9-4dc2-971d-b107bd549c1b.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This will probably be resolved by #11606.

**Comment by Witoso** [comment]
~~This will probably be resolved by #11606.~~ (we decided to fix it as below).

Heading feature: splits, and changes it to paragraph, and let's clean all of the styles (integration of GHS with Headings).
