### ISSUE TITLE
[Style dropdown] Inline style can't be removed after adding any paragraph styling (e.g. highlight, bold, italic)

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#11588]
## 📝 Provide detailed reproduction steps (if any)

https://user-images.githubusercontent.com/11699569/162178693-4973d7cc-6d1c-41c3-985f-21e58c91af1f.mp4

### ✔️ Expected result

_Should be possible to remove `marker` from the selected text_

### ❌ Actual result

_Marker can't be removed, unless you remove the highlight/bold/italic etc. first_

---

📃 Other details

- If you do it the other way around (add highlight/bold/italic etc. to text first, and after that marker on part of the text) - there is no problem as described/shown above.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
The issue applies to any paragraph styling. After applying e.g. bold to text you are not able to unselect any of the previously chosen styles from the style dropdown.
