### ISSUE TITLE
[Style dropdown] Some styles overwrite "Multiple styles" text in the styles dropdown and make the user unable to choose another style

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11586]
## 📝 Provide detailed reproduction steps (if any)

1. Open manual test (http://localhost:8125/ckeditor5-style/tests/manual/styledropdown.html)
2. Insert text
3. Try to apply some text styles and then `strong.Baz` or `code.Qux`

### ✔️ Expected result

"Multiple styles" message in styles dropdown and every style possible to undo by pressing it in the styles dropdown

### ❌ Actual result

Only one style is displayed in the dropdown and not possible to apply/undo other styles anymore:
![styles dropdown issue multiple styles](https://user-images.githubusercontent.com/32898551/162169395-68d8bb9d-1383-4964-871c-b5fc7bb03cc3.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Sounds like it could be related to #11588
