### ISSUE TITLE
[Style dropdown] Should apply block style to all selected blocks

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#11582]
## 📝 Provide a description of the improvement

The style dropdown applies block style only to the first block but it should apply it to all selected blocks (for example as headings dropdown does).

## 📃 Other details

![2022-04-07 10 54 26](https://user-images.githubusercontent.com/1232187/162161307-6b134f5b-d412-494b-bb20-517e683e78f1.gif)

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
Happening as well inside the table, and with multiple cells selected:

https://user-images.githubusercontent.com/11699569/162171224-62b25aac-731b-45b9-b462-1564b8e46409.mp4
