### ISSUE TITLE
Crash on init when using Style and DocumentLists together

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11589]
## 📝 Provide detailed reproduction steps (if any)

1. Add Style and DocumentLists plugins to all-features manual test
2. Open the test

### ✔️ Expected result

Editor works.

### ❌ Actual result

Editor crashes:
```js
TypeError: Cannot read properties of undefined (reading 'push')
    at DocumentListEditing.registerDowncastStrategy (documentlistediting.js:167:1)
    at DocumentListElementSupport.init (documentlist.js:46:1)
```
After removing one of those plugins editor works fine again.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Closed in #11593.
