### ISSUE TITLE
[Style dropdown] Inline style can't be removed from an inline widget itself

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#11584]
## 📝 Provide detailed reproduction steps (if any)

![2022-04-07 11 05 43](https://user-images.githubusercontent.com/1232187/162163571-39b6600c-8d01-4b2e-ab88-9c7a75b48d08.gif)

### ✔️ Expected result

Should be possible to wrap inline widgets same as text (it's all wrapped with a dedicated AttributeElement).

### ❌ Actual result

You can set inline style when more than just an image is selected, but you can't modify inline style while an inline widget is selected itself.

### ❓ Possible solution

Blocking of styles should be only for block styles, inline styles should be enabled if allowed by the schema.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
Other example with `highlight` and `text style - marker`

https://user-images.githubusercontent.com/11699569/162175830-b4fbc6f0-bc03-4f2b-b2cf-5fb08888621a.mp4
