### ISSUE TITLE
[Style dropdown] Integration with document (advanced) lists

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11590]
## 📝 Provide a description of the new feature

Document (advanced) lists use different model attribute names than the default `htmlAttributes`. This is why the styles feature (command) does not interact with them. A dedicated integration is necessary.

**(edited by @Witoso, 30.03.2022)**

Acceptance criteria:
* given I have Document lists plugin and the style definition of `ol`, when I'm in a list item, or select multiple list items or multiple lists, and select the style, then style should be applied to one (or more) `ol` elements.
* given I have Document lists plugin and the style definition of `ul`, when I'm in a list item, or select multiple list items or multiple lists, and select the style, then style should be applied to one (or more) `ul` elements.
* given I have Document lists plugin and the style definition of `li`, when I'm in a list item, or select multiple list items or multiple lists, and select the style, then style should be applied to one (or more) `li` elements.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
To be hyper-precise, this should support elements: `ol`, `ul`, and `li` defined by the Style dropdown.

**Comment by Witoso** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/12668
