### ISSUE TITLE
[Style dropdown] Inline styles retained when changing heading, inserting codeblock

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#11591]
## 📝 Provide detailed reproduction steps (if any)

Changing heading:

https://user-images.githubusercontent.com/11699569/162199263-c12ecc9f-a9e9-4684-b792-7ac24e785a65.mov

Inserting codeblock:

https://user-images.githubusercontent.com/11699569/162199797-3b6465a4-9074-4d2e-9ece-5bd82c45bb35.mov

### ✔️ Expected result

I'd expect that by changing the heading/inserting codeblock:
1. All of the added htmlAttributes will be removed.
2. At least all of the htmlAttributes that cant be unchecked should be removed.

### ❌ Actual result

All of the htmlAttributes added are available, even though there is no way of removing them.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This will probably be resolved by #11606.

**Comment by Witoso** [comment]
Solved by: https://github.com/ckeditor/ckeditor5/issues/14216.
