### ISSUE TITLE
Orders in translation files are different for Classic and Inline Editors

### ISSUE THREAD

**Issue by alexander-sessa** [ckeditor/ckeditor5#1159]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor: CKEditor 5 ver. 10.1.0

For my Comments System I use Classic and Inline editors on same page becase Inline Editor 5 has no more ability to replace textarea and Classic Editor can't more be an inline editor.
But orders in tranlation files are different for Classic and Inline Editors.
So in one instance I have correct translated texts and in other some translations are reversed.

## 📋 Steps to reproduce

1. Use Classic and Inline Editors on same page.
2. Use any translation for CKEditor 5.
3. Check texts in toolbars.

## ✅ Expected result
Translated texts must be same

## ❎ Actual result
Some translated texts are confused.

## 📃 Other details that might be useful
CKEditor 4 works great as Basic (Classic) and Inline Editor in same script. Why not add inline funtions in CKEditor 5 Classic?

**Comment by oleq** [comment]
> For my Comments System I use Classic and Inline editors on same page

Can you share with us how you use them in your app? I mean the webpack config, the code to run editors and their configs etc.

**Comment by Reinmar** [comment]
You can only use multiple editor types on one page if you build them together. It was discussed in https://github.com/ckeditor/ckeditor5/issues/923, but the code samples there are outdated. They should allow you to grasp the concept though.
