### ISSUE TITLE
Glue all the pieces of the data model

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#116]
Moved from https://github.com/ckeditor/ckeditor5-core/issues/230

We need a helper for instantiating the data model, data view, document, etc. and glueing all those pieces.

Things to instantiate:

* document
* add two pipelines:
  * editable:
    * converter controller
    * editable tree view
    * position mapper
    * features injecting observers (ckeditor5-treeview-observer)
  * output:
    * converter controller
    * data tree view
    * data processor

**Comment by Reinmar** [comment]
While thinking about #119 I realised that we'll need a core `Editable` class which will implement the `Observable` interface as well as a `EditableCollection` which will store them and knew things such as which is the currently focused one.

That's not a news for some of us, because these classes were proposed a long time ago by @fredck, but for a while we've seen them only in the UI library and as a completely separate set of classes in the engine. We wanted to keep an order in what goes to the UI and what to the engine, but I see that we'll need an integration layer in the core. Actually, not integration, because it won't know about the UI ofc, but a base architecture.

How the UI and engine will interact with the editables defined in the editor?

The UI will simply use that as part of the model, binding its behaviour (such as class changes on the editable elements, or toolbar positioning) to the observable attributes of the editables.

The engine does not know anything about the core, so it's the core who will keep the integration logic (such as – add a focus observer to the tree view in order to know when to change `isFocused` attribute). This logic will be defined in the `Editable` class, so it will be more than just a dry model.

**Comment by pjasiun** [comment]
We also agreed that the "editable pipeline" will be renamed to the "editing pipeline", to avoid naming collisions. Note that editing pipeline handle all roots of editable so the `EditingController` is not the same as `EditableController`.

**Comment by Reinmar** [comment]
It's a tricky task finding good names for all these classes, but I think that the current idea is good:

* "root" means an editing root,
* "editable" means editing roots and nested editable elements,
* "editing controller" (and "pipeline") controls the whole editing experience.

**Comment by pjasiun** [comment]
You should create a dictionary.

**Comment by Reinmar** [comment]
Right after yours :D.

**Comment by Reinmar** [comment]
That was fast – I published very first version: https://github.com/ckeditor/ckeditor5-design/wiki/Project-Dictionary

**Comment by Reinmar** [comment]
Closed by #125.
