### ISSUE TITLE
[Style dropdown][GHS] Clean up disallowed attributes upon editing

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11606]
Based on a scenario from #11578, it's visible that GHS's attributes should be cleared from elements on which they are not allowed.

**Comment by Reinmar** [comment]
Another scenario: #11591

**Comment by Witoso** [comment]
For now, let's only handle style dropdown cases for blocks.

**Comment by Witoso** [comment]
When I think about it the reason to prioritize this is the actions we took to improve Style dropdown. We will have more blocks that could be styled, e.g. tables, and lists, therefor the issue may appear more and more often.

**Comment by Witoso** [comment]
Create a ul list:
 ![image](https://github.com/ckeditor/ckeditor5/assets/9881379/e8a7dc20-1521-4bd9-8dbe-3094b62585d2)

Creata an ol list:
![image](https://github.com/ckeditor/ckeditor5/assets/9881379/3a62a41a-c6a0-4353-b3a0-bb72f8042113)

**Comment by Witoso** [comment]
Another case for lists: https://github.com/ckeditor/ckeditor5/issues/14216

**Comment by Witoso** [comment]
All cases were solved by the PRs in https://github.com/ckeditor/ckeditor5/issues/14216. Closing.
