### ISSUE TITLE
Upgrade to Node 8 (LTS) on CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1160]
Right now we've got this:

```
$ nvm install 6
Downloading and installing node v6.14.3...
Downloading https://nodejs.org/dist/v6.14.3/node-v6.14.3-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v6.14.3 (npm v3.10.10)
$ node --version
v6.14.3
$ npm --version
3.10.10
$ nvm --version
0.33.11
```

This applies to ckeditor5, ckeditor5-* and ckeditor5-dev-*

**Comment by pomek** [comment]
Let's see how it will work: https://travis-ci.org/ckeditor/ckeditor5/builds/404907556

**Comment by pomek** [comment]
```
$ node --version
v8.11.3
$ npm --version
5.6.0

...

Chrome 67.0.3396 (Linux 0.0.0): Executed 8989 of 8989 SUCCESS (2 mins 47.073 secs / 25.071 secs)
```

I will update everything tomorrow.

**Comment by Reinmar** [comment]
Looking at this:

![image](https://user-images.githubusercontent.com/156149/42843384-39db0ab6-8a10-11e8-9996-649c238230ea.png)

We're about to observe a nice performance boost :)

**Comment by pomek** [comment]
It works for the `ckeditor5`. However, it won't for the rest packages (`ckeditor5-*`).

I don't understand what happened and why it does not work.

After upgrading the version to 8, everything works fine until we call [`ckeditor5-dev-tests-install-dependencies`](https://github.com/ckeditor/ckeditor5-adapter-ckfinder/blob/9c19abd4c4afc15abdb8be8831aecf8852a4e327/.travis.yml#L20). After working of this script, the next step (which is [`ckeditor5-dev-tests-travis`](https://github.com/ckeditor/ckeditor5-adapter-ckfinder/blob/9c19abd4c4afc15abdb8be8831aecf8852a4e327/.travis.yml#L22)) throws an error: 

```bash
$ ckeditor5-dev-tests-travis
ckeditor5-dev-tests-travis: command not found
```

Somehow `node_modules/.bin/` is empty. Some weird things happen between bootstrapping and testing. I will debug it…

**Comment by pomek** [comment]
A version of NPM must be at least `@5.7.1` (https://github.com/npm/npm/issues/17929#issuecomment-367924287).

**Comment by Reinmar** [comment]
Why did you lock the version of npm to ^5.7.1? What about 5.8.0, 6.0.0, etc?

**Comment by pomek** [comment]
I locked `npm@^5.7.1`.

**Comment by Reinmar** [comment]
I know. That will install `5.8.0` (my mistake above), but won't install 6.0.0. Was that on purpose?

**Comment by pomek** [comment]
Yes. Node 8 installs NPM 5 by default. I just upgraded it to the latest version.

**Comment by Reinmar** [comment]
But did you limit that version to npm 5.x on purpose?

**Comment by pomek** [comment]
I decided to go with npm `5.x` but at least `5.7.1` because I thought that npm 5 is somehow connected to Node 8.

If we would go with `npm >=5.7.1`, most probably everything should work as well.

Let me know whether I should update it or leave it as it is now.
