### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by addsimm** [ckeditor/ckeditor5#1161]
This ticket is about introducing an "Export to PDF" feature in CKEditor 5. We haven't done a deeper research yet, but the overall requirements are:
 - There must be a possibility of printing documents that look exactly as inside the editor, including the formatting and line breaks.
 - The produced PDFs must contain real text inside, which is selectable and searchable.
 
If you would like to see such an addon for CKEditor 5, please add 👍 to this issue. If you have any additional requirements, please add a comment.

Original issue reported by addsimm:

> 🆕 Feature request 

> It would be nice to have this built in, in my opinion. How hard would it be?  Alternatively, what is the easiest way to do this as it stands?

**Comment by addsimm** [comment]
i agree it would be difficult; that, however, has to be weighed against the benefit.  If you take a look at the main ckeditor 5 page you see: 

![screen shot 2018-07-18 at 8 53 22 am](https://user-images.githubusercontent.com/2389450/42893023-1c7bec08-8a68-11e8-95a4-6e50a20ef927.png)

Which appears to be a wysiwyg word processor.  That implies that the time users put into formatting a document is reflected in the output. The developers duty is to ensure this problem is kept. PDFs for all their problems are the de facto document file standard 

  I have just started upgrading our site to 5 from 4.  With 4 I used a third party package WeasyPrint to create the pdf and solved this problem by matching the width of the editor to the width of an 8.5in page in the pdf.  However with 5 I a running into a fatal problem, namely that the margins in the developer server do not match the margins in the production server, meaning that I do not even know where to start.  

You could say this is a problem with WeasyPrint; however, it worked well enough in version 4 and I do not want to take a step backward with version 5.

Here is an illustration:

Base document - the soft returns are highlighted in pink:

Development:

![screen shot 2018-07-18 at 9 01 50 am](https://user-images.githubusercontent.com/2389450/42893457-3b4d2fba-8a69-11e8-8ee0-b3cb998137a5.png)
 server:


![screen shot 2018-07-18 at 9 00 43 am](https://user-images.githubusercontent.com/2389450/42893415-19304778-8a69-11e8-8cf7-0e9e6816479c.png)

Now the pdfs:

Development:
![screen shot 2018-07-18 at 9 02 32 am](https://user-images.githubusercontent.com/2389450/42893502-5eceb990-8a69-11e8-8e53-8bab1e4c19e8.png)

Production:
![screen shot 2018-07-18 at 9 03 10 am](https://user-images.githubusercontent.com/2389450/42893524-6b30d894-8a69-11e8-8745-cc555e837de8.png)

Notice the soft breaks are working neatly in the development but not the production server and worse, the results are inconsistent.  Also the pink highlight has changed to yellow, which I have not investigated.

Thoughts?

**Comment by jodator** [comment]
> Also the pink highlight has changed to yellow, which I have not investigated

The standard representation in browsers of the `<mark>` element is a yellow background AFAIR - the highlight feature uses [CSS classes to change color of a highlighter](https://docs.ckeditor.com/ckeditor5/latest/features/highlight.html#colors-and-styles). So you might need to provide a class or define the styling in PDF yourself.

As for the inconsistency of dev/prod - AFAICS the fonts are different so the calculation of lines will differ. So maybe check if you have the same fonts used and/or available on both environments.

**Comment by Reinmar** [comment]
:tada: https://ckeditor.com/blog/How-to-print-WYSIWYG-editor-content-to-PDF-Export-to-PDF-feature-released/

**Comment by Just1pman** [comment]
Export the pdf plugin does not use default ckeditor styles.

The ckeditor and the export to pdf plugin have different styles, the export to pdf plugin does not use the default styles of the ckeditor
