### ISSUE TITLE
Newlines are replaced by "`@`" character.

### ISSUE THREAD

**Issue by dreirund** [ckeditor/ckeditor5#11614]
Whenever I copypaste text into any message field in the demo at https://ckeditor.com/ckeditor-5/demo/ or on [BeWelcome.org](http://bewelcome.org/) (which uses CHKEditor 5), each newline is replaced by an "`@`" character.

This does not happen when I have JavaScript disabled (on [BeWelcome.org](http://bewelcome.org/) only, since on https://ckeditor.com/ckeditor-5/demo/ no imput field appears at all with JavaScript disabled).

I use Firefox version 100.0b3 (64-bit) on GNU/Linux, but it existed for long time for me already.  
It does also happen if I start Firefox with extensions disabled.  
It does not happen in Chromium.

What could I do/ help to track it down?

Here is an example where I copypasted a text with two paragraphs, the second paragraph has one newline within:

---

> ```
> This is the first paragraph of a test text.@@This is the second paragraph of a test text, paragraphs are separated by two consecutive newlines.@This is a new line within the second paragraph.
> ```

---

## 📝 Provide detailed reproduction steps (if any)

1. I go to https://ckeditor.com/ckeditor-5/demo
2. I copypaste a text with newlines that I have pre-written in a local text editor
3. I observe that each newline is replaced by `@`.

### ✔️ Expected result

Newlines are kept.

### ❌ Actual result

Newlines are removed, and an "`@`" character is inserted instead for each newline.

## 📃 Other details

* Browser: *Firefox version 100.0b3 (64-bit)*
  - *It does also happen if I start Firefox with extensions disabled.*
  - *It does not happen in Chromium.*
* OS: *Artix GNU/Linux*
* First affected CKEditor version: *n/a*
* Installed CKEditor plugins: *I don't know*
* This does not happen when I have JavaScript disabled (on [BeWelcome.org](http://bewelcome.org/) only, since on https://ckeditor.com/ckeditor-5/demo/ no imput field appears at all with JavaScript disabled).
* There exist other users which use Firefox on Linux which don't experience this. So I would be happy with advice how to track this down, since I suspect that more specific information is needed to identify the problem.

---

*If you'd like to see this fixed sooner, add a reaction to this post.*

**Comment by niegowski** [comment]
This problem should not happen anymore in [v35.3.0](https://github.com/ckeditor/ckeditor5/releases/tag/v35.3.0).

It was most probably caused by: 

[https://github.com/ckeditor/ckeditor5/blob/v35.2.1/packages/ckeditor5-typing/src/utils/injecttypingmutationshandling.js#L153-L154](https://github.com/ckeditor/ckeditor5/blob/v35.2.1/packages/ckeditor5-typing/src/utils/injecttypingmutationshandling.js#L153-L154)

**Comment by dreirund** [comment]
> This problem should not happen anymore in [v35.3.0](https://github.com/ckeditor/ckeditor5/releases/tag/v35.3.0).

But now I cannot paste at all with Firefox (neither via `<CTRL>`+`<V>` nor with middle mouse (X.org X11 on GNU/Linux)). (Tested at https://ckeditor.com/ckeditor-5/demo/.) With Chromium, I can paste.
