### ISSUE TITLE
[Document list] How to expose its DLL?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11610]
Part of #11377.

The problem right now is that list's `src/index.js` exposes only the old list feature.

How can we expose document list's DLL?

Options:

### Option 1. Add to `ckeditor5-list/src/index.js`

*   Pros:
    *   KISS
    *   Will motivate us to sunset old lists faster ;)
*   Cons:
    *   Doubled size of the DLL (and you'll never use two of these features at once)
    *   If we'll go this way, moving to opt 2 or 3 later on will be a BC

### Option 2. Move entire DocLists to a new package

*   Pros:
    *   Clean
    *   Optimal size
*   Cons:
    *   Both features depend on the same UI, so where would we keep it and how would we import it? Answer: we'd import from `ckeditor5-list/src/...`.
    *   What will we do once the old lists are sunset in the future?

### Option 3. Create a new `ckeditor5-document-list` package just for the DLL

And have only `src/index.js` there. It'd import module directly from `ckeditor5-list`. We'd ignore the cross-package import rule there.

*   Pros:
    *   Smart
    *   Optimal size
    *   No issue with sharing the same UI
*   Cons:
    *   Slightly confusing (it's a workaround rather than a solution)

**Comment by wimleers** [comment]
Sounds like this should be decided/fixed tomorrow since otherwise this crucial aspect of CKEditor 5 `v34.0.0` will not be available to Drupal? 😅

**Comment by Reinmar** [comment]
Unfortunately, we'll not be able to fix it by tomorrow. I know that it blocks you from testing this feature straight from npm, but it wasn't enough time for us to process this.

The good news may be that with options 2 and 3 we don't have to wait till the next release.

**Comment by Reinmar** [comment]
It's been an interesting discussion and it turns out that great majority of us are for the KISS option, so option 1. Let's do this and see if we can release a patched version ASAP.

**Comment by arkflpc** [comment]
DLL grew from 65705 to 92104 bytes (18122 to 24631 gzipped).
