### ISSUE TITLE
Remove `UglifyJsWebpackPlugin` from builds

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1162]
Current webpack uses `uglifyjs-webpack-plugin@^1.2.4"`, so it should install the latest version of the `uglifyjs-webpack-plugin` (1.2.7), which contains an important fix for us (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/compare/v1.2.5...v1.2.6#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR11).

So now it can be removed from `package.json` from builds and we can use it via `webpack.optimize.UglifyJsPlugin` (https://webpack.js.org/plugins/uglifyjs-webpack-plugin).

**Comment by ma2ciek** [comment]
Actually, I can't remove this from `package.json`, because of that warning: `webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.`. But I can remove these comments: https://github.com/ckeditor/ckeditor5-build-classic/blob/cba7c4a49406d9d16ed7596fb1af547a9dd0424f/webpack.config.js#L34

**Comment by ma2ciek** [comment]
Fixes are on branches:
* https://github.com/ckeditor/ckeditor5-build-inline/tree/t/ckeditor5/1162
* https://github.com/ckeditor/ckeditor5-build-decoupled-document/tree/t/ckeditor5/1162
* https://github.com/ckeditor/ckeditor5-build-classic/tree/t/ckeditor5/1162
* https://github.com/ckeditor/ckeditor5-build-balloon/tree/t/ckeditor5/1162

**Comment by Reinmar** [comment]
All merged.
