### ISSUE TITLE
Add code snippets for full featured and bottom toolbar editor examples

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11622]
## 📝 Provide a description of requested docs changes

Currently, there is no easy way for learning more about re-creating full-featured and bottom toolbar examples. It would be great to add code snippets, so all interested people could use it.

TO-DO

*   [x] bottom toolbar example code listing
*   [x] full-featured example code listing
*   [x] cleaning sensitive data from listing

**Comment by godai78** [comment]
Both changes deployed to `stable` and on prod.
