### ISSUE TITLE
The "get-latest-changelogs" script removes links to blogposts

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#11643]
## 📝 Provide detailed reproduction steps (if any)

1. This issue does not depend on the environment. It occurs on local, staging, and production docs.
2. `yarn run docs --skip-api --guides updating/changelog`
3. Review the built page. 

### ✔️ Expected result

Entries for each version should contain a URL to the blogpost:

```md
Please refer to the [Migration to v34.x](https://ckeditor.com/docs/ckeditor5/latest/updating/migration-to-34.html) guide to learn more about these changes.
```

### ❌ Actual result

These links are not available.

### ❓ Possible solution

While transforming changelog entries, we remove too much.

https://github.com/ckeditor/ckeditor5/blob/fa26e7cac134bbd42691038c0f9fed0ad0fa2253/scripts/docs/get-latest-changelogs.js#L38-L44

**Comment by psmyrek** [comment]
The blog post link is something like:

> Read about release highlights in a dedicated blog post: https://ckeditor.com/blog/ckeditor-5-v34.0.0-with-redesigned-lists-new-styles-implementation-and-extended-dll-builds/

#### Proposal

Show single paragraph, extracted from the "Release highlights" section, containing a link to the blog post. This single paragraph will be displayed between the release header and the next section. If there is no blog post link in the "Release highlights" section, the output will the same as it is now.

#### Example with blog post link
![1](https://user-images.githubusercontent.com/56868128/173046318-d53a2bef-9c06-407e-a8c1-4cb511bf5480.png)

#### Example without blog post link
![2](https://user-images.githubusercontent.com/56868128/173047631-6f85b6a8-42cc-481f-a2c8-60b7b665e39a.png)

@godai78 Is it OK?

**Comment by godai78** [comment]
I believe it should be OK.
