### ISSUE TITLE
allowedContent=true not working in React CKEditor

### ISSUE THREAD

**Issue by nikhilthakur001** [ckeditor/ckeditor5#11642]
I'm using CKEditor in react. I'm trying to add `<p style="background:'red'">Test</p>`. But the CKEditor removes my style tag and background colour. I passed a config 'allowedContent=true' but it is not working.

```
import { CKEditor } from '@ckeditor/ckeditor5-react';
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';

<CKEditor
    data={props.value}
    onReady={editor => {
	    editor.ui.getEditableElement().parentElement.insertBefore(
		    editor.ui.view.toolbar.element,
		    editor.ui.getEditableElement()
	    );
    }}
    onChange={(event, editor) => handleChange(event, editor)}
    editor={DecoupledEditor}
    onBlur={handleBlur}
   config={{
       allowedContent: true
}}
  />
```

I was expecting that the allowedContent true will not remove my 'style' attribute from p tag.

**Comment by Reinmar** [comment]
`allowedContent:true` is CKEditor 4's option.

CKEditor 5 works completely differently. Refer to the [Migration guide](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/migration-from-ckeditor-4.html#configuration-options-compatibility-table) for more information.
