### ISSUE TITLE
Most Chinese use WPS，I hope to support the paste function

### ISSUE THREAD

**Issue by add2ws** [ckeditor/ckeditor5#11650]
Most Chinese use WPS，I hope to support the paste function

_Originally posted by @xunyidaixu in https://github.com/ckeditor/ckeditor5/issues/2488#issuecomment-841703225_

**Comment by PKXZ** [comment]
Yes, I'm also looking for one that supports WPS replication. Please support

**Comment by yoyo837** [comment]
Duplicate of #2488

**Comment by yoyo837** [comment]
@add2ws 本地编译修改一下代码能解决。

**Comment by PKXZ** [comment]
> @add2ws 本地编译修改一下代码能解决。

For example? I can't use WPS stickers

**Comment by yoyo837** [comment]
https://github.com/ckeditor/ckeditor5/pull/10471

**Comment by Mgsy** [comment]
As mentioned above, it's a duplicate of #2488.
