### ISSUE TITLE
how to use local folder image upload in this script ?

### ISSUE THREAD

**Issue by suatsuphi** [ckeditor/ckeditor5#1165]
Hi,
how to use local folder image upload in this script ?
 do anyone have any idea ? is it possible ? 

<script src="~/ckeditor5/ckeditor.js"></script>
    <style>
        .ck-content {
            /*color: teal;*/
            min-height: 300px;
        }
    </style>
    @if (Model.Setting.Language.ShortLang != "en")
    {
        <script src="~/ckeditor5/translations/@(Html.Raw(Model.Setting.Language.ShortLang)).js"></script>
    }
    <script>
         
        ClassicEditor
            .create(document.querySelector('#editor'), {

                language: '@(Html.Raw(Model.Setting.Language.ShortLang))',

                ckfinder: {
                    uploadUrl:  '@Html.Raw(Model.Setting.UploadUrlEditor)'
                }
            })
            .then((a) => {
                window.editor = a;
                
                a.isReadOnly = @(Model.NewQuestionDisabled ? "true" : "false");

                //a.model.change(writer => {
                //    const insertPosition = editor.model.document.selection.getFirstPosition();
                //    writer.insertText('CKEditor 5 rocks!', { linkHref: 'https://ckeditor.com/' }, insertPosition);
                //});

            })
            .catch(error => {
                console.error(error);
            });

    </script>

**Comment by Reinmar** [comment]
I'm sorry, but this question is too much detached from CKEditor 5 itself. I don't even know what you tried to do (cause it's not JS). 

I recommend asking it on StackOverflow, but you'll certainly need to explain more clearly what you're doing.

**Comment by suatsuphi** [comment]
My aim is too easy but there is no forum and there is no answer anywhere. 
I can use this
 ckfinder: {
                uploadUrl:  '@Html.Raw(Model.Setting.UploadUrlEditor)'
            }

so I can upload in cksource.com but I want to upload my folder in my iis server ? how to use ckeditor5 for this aim ?

thank you
