### ISSUE TITLE
[Document list] Inconsistent look between browsers of table inserted into the list 

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11663]
## 📝 Provide detailed reproduction steps (if any)

1. Create a new list element with `document list` enabled filled with some text.
2. Create another empty document list element with a few empty paragraphs.
3. Add the table to the second paragraph of the second element.

### ✔️ Expected result

Table added in the correct place and looking the same in Chrome, Firefox and Safari.

**Safari:**

![document list table position issue - correct ](https://user-images.githubusercontent.com/32898551/164706179-724ea909-4207-4a41-a2f8-47199afd5571.gif)

### ❌ Actual result

Table added into the correct place only in Safari, Firefox and Chrome it looks like being above the first paragraph of the second list element, even though it was added inside of the second paragraph.

**Chrome, Firefox:**

![document list table position issue - incorrect ](https://user-images.githubusercontent.com/32898551/164706170-b5d5f9f2-888a-4a50-b8ae-9f78068650d0.gif)

## 📃 Other details

* Browser: Firefox, Chrome

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Similar to #11361 – "can't fix".
