### ISSUE TITLE
How to use placeholder message in this editor ? 

### ISSUE THREAD

**Issue by suatsuphi** [ckeditor/ckeditor5#1166]
Hi,
How to use placeholder message in this editor ? 

<script src="~/ckeditor5/ckeditor.js"></script>
<style>
    .ck-content {
        /*color: teal;*/
        min-height: 300px;
    }
</style>
@if (Model.Setting.Language.ShortLang != "en")
{
    <script src="~/ckeditor5/translations/@(Html.Raw(Model.Setting.Language.ShortLang)).js"></script>
}
<script>
     
    ClassicEditor
        .create(document.querySelector('#editor'), {

            language: '@(Html.Raw(Model.Setting.Language.ShortLang))',

            ckfinder: {
                uploadUrl:  '@Html.Raw(Model.Setting.UploadUrlEditor)'
            }
        })
        .then((a) => {
            window.editor = a;
            
            a.isReadOnly = @(Model.NewQuestionDisabled ? "true" : "false");

            //a.model.change(writer => {
            //    const insertPosition = editor.model.document.selection.getFirstPosition();
            //    writer.insertText('CKEditor 5 rocks!', { linkHref: 'https://ckeditor.com/' }, insertPosition);
            //});

        })
        .catch(error => {
            console.error(error);
        });

</script>

**Comment by Reinmar** [comment]
The same thing as in https://github.com/ckeditor/ckeditor5/issues/1165.
