### ISSUE TITLE
It's possible to edit table (insert columns, rows, merge cells) in the restricted mode in manual test

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#11672]
1.  Go to http://localhost:8125/ckeditor5-restricted-editing/tests/manual/restrictedediting.html
2.  Switch to restricted mode
3.  it's possible to edit the table.

![](https://user-images.githubusercontent.com/2768047/165262695-146e22f9-d076-4f42-a7e4-9bd1420d9aa7.png)

I reproduced it on master but I could not reproduce it on https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/restricted-editing.html...

**Comment by niegowski** [comment]
This is a test of enabling selected commands in restricted mode: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-restricted-editing/tests/manual/restrictedediting.md?plain=1#L10-L15
