### ISSUE TITLE
@types/ckeditor__ckeditor5-core missing definitions for `Editor#enableReadOnlyMode()` and `Editor#disableReadOnlyMode()`

### ISSUE THREAD

**Issue by Tsuk1ko** [ckeditor/ckeditor5#11683]
v34 add some new methods for editor but typescript definitions is not updated.

![image](https://user-images.githubusercontent.com/24877906/165478495-d98c57fd-f1cc-4ee8-b833-19d974757bd3.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
The typings are actually not maintained by us for now (cc @fedemp). They are developed on https://github.com/DefinitelyTyped/DefinitelyTyped.

This is going to change in #11708 but it'll take a couple of months so for now

**Comment by fedemp** [comment]
@Tsuk1ko Please report this at https://github.com/DefinitelyTyped/DefinitelyTyped/discussions so I'll be automatically tagged.
