### ISSUE TITLE
Improve the error for using `Editor.isReadonly` setter

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11695]
Currently it can be found here: [https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-editor-isreadonly-has-no-setter](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-editor-isreadonly-has-no-setter)

And looks like this:

> `Editor#isReadOnly` does not have a setter and should be set using `Editor#enableReadOnlyMode( lockId )` and `Editor#disableReadOnlyMode( lockId )`.

There are at least a couple of things that can be improved here:

*   Those should be links to the methods. Save people time whenever you can.
*   We should clearly state that this is a change introduced in a version XYZ. That before this you should use the setter. But starting from XYZ you need to use these methods.
*   You can add a code example of how you used it before and how it looks now. Again, save the time.

**Comment by mesith-glowbify** [comment]
@Reinmar were you able to manage this error? I am also having the same issue.

**Comment by Reinmar** [comment]
> @Reinmar were you able to manage this error? I am also having the same issue.

Please check out https://github.com/ckeditor/ckeditor5/issues/11680
