### ISSUE TITLE
insertContent seems to not working as expected

### ISSUE THREAD

**Issue by wehmoen** [ckeditor/ckeditor5#1169]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Version: 10.1.0
Plugins:

		Alignment,
		CodePlugin,
		StrikePlugin,
		UnderlinePlugin,
		EssentialsPlugin,
		UploadadapterPlugin,
		AutoformatPlugin,
		BoldPlugin,
		ItalicPlugin,
		BlockquotePlugin,
		EasyimagePlugin,
		HeadingPlugin,
		ImagePlugin,
		ImagecaptionPlugin,
		ImagestylePlugin,
		ImagetoolbarPlugin,
		ImageuploadPlugin,
		LinkPlugin,
		ListPlugin,
		ParagraphPlugin,
		EmbedUI // the example plugin for an image upload. icon shows up and i get prompted for the url

## 📋 Steps to reproduce

1. Setup your editor
2. Use the browser console or create a plugin to invoke this code:

```
editor.model.change(writer => {

					let url = prompt("Enter the Video URL:");


					const embed = writer.createElement( 'iframe', {
						src: url
					} );

					console.log(embed)

					editor.model.insertContent( embed, editor.model.document.selection );
				} );
```

## ✅ Expected result

See an iFrame added to the editor.

## ❎ Actual result

Nothing happens. The console shows no error. The console just logs undefined. But this seems to be ok. However i was not able to make this work. I had a look in your docs and copied the basic example for an image upload and changed only the element.

**Comment by Reinmar** [comment]
The code that you posted does one thing – it appends an `<iframe src>` to the editor's model. The model is abstract, it does not itself mean that something will be rendered. For that to work you also need to define how that model element is defined to the view. That process is called a conversion and it's not described well in the [documentation](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/architecture/editing-engine.html#conversion). However, I still recommend reading that guide.

The other thing that you need to do is to tell the editor where this element is allowed in the model and what's its nature. That's done in the [schema](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/architecture/editing-engine.html#schema).

I'll work later on improving the docs for `insertContent()` so to mention those things there. I also want to add a snippet how to insert a piece of HTML (string) using it (this method is used e.g. when you paste).

**Comment by wehmoen** [comment]
Thanks for the reply. Unfortunately it seems not that easy to do this.

WIll wait for the documentation update. Maybe you could add some more code examples :)

**Comment by bryantwells** [comment]
Having the same trouble here. I'm unable to get `insertContent` working with an argument of anything other than an image element from the documented example — including the element returned from `writer.createElement( 'p', null, 'foo' )` .

**Comment by bryantwells** [comment]
For anyone having trouble with this issue until the docs are more complete — after digging around this is what I came up with to implement a simple Horizontal Rule insert:

```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
import hrIcon from './theme/icons/horizontalrule.svg';

import { upcastElementToElement } from '@ckeditor/ckeditor5-engine/src/conversion/upcast-converters';
import { downcastElementToElement } from '@ckeditor/ckeditor5-engine/src/conversion/downcast-converters';


export default class HorizontalRule extends Plugin {
    init() {
        const editor = this.editor;
        const model = editor.model;
        const conversion = editor.conversion;
        const doc = model.document;
        const schema = model.schema;
		
        // Register horizontal rule schema
        schema.register( 'horizontalRule', {
            allowIn: '$root',
            isObject: true,
            isBlock: true,
        } );

        // Configure upcast converter.
		conversion.for( 'upcast' )
            .add( upcastElementToElement( {
                model: 'horizontalRule',
                view: 'hr'
            }));

        // Configure downcast converter.
        conversion.for( 'downcast' )
			.add( downcastElementToElement( {
				model: 'horizontalRule',
				view: ( modelElement, viewWriter ) => {
                    return viewWriter.createEmptyElement( 'hr' );
                }
            }));


        // Do work
        editor.ui.componentFactory.add( 'horizontalRule', locale => {
            const view = new ButtonView( locale );

            view.set( {
                label: 'Insert Horizontal Rule',
                icon: hrIcon,
                tooltip: true
            } );

            // Callback executed once the image is clicked.
            view.on( 'execute', () => {

                model.change( writer => {
                    const horizontalRuleElement = writer.createElement( 'horizontalRule' )

                    // Insert the hr at the end of the selection
                    writer.insert( horizontalRuleElement, doc.selection.focus );
	                writer.setSelection( horizontalRuleElement, 'after' );
                } );

            } );

            return view;
        } );
    }
}
```
