### ISSUE TITLE
getData() returns error

### ISSUE THREAD

**Issue by MaximSemikov** [ckeditor/ckeditor5#1170]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 💻 Version of CKEditor
ckeditor5-build-classic-10.1.0

## 📋 Steps to reproduce

I use jquery and CKEditior5. Try to get editor content with getData method when I click on the button, but it returns error.

Here is my code. It is very simple. Everything according to documentation.
<pre>
<script src="js/ckeditor5/ckeditor.js"></script>
<script src="js/jquery-3.3.1.js"></script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
	$("#btn").on("click",function(e){
	    e.preventDefault();
		const data = editor.getData();
		console.log($('#editor').val());
	})
</script>
</pre>

## ✅ Expected result
string in the variable or something like that...

## ❎ Actual result
TypeError: editor.getData is not a function

**Comment by pomek** [comment]
The error occurs because the `editor` is not defined.

Please, look at the code below (the `.then()` section):

```js
ClassicEditor
	.create( document.querySelector( '#editor' ) )
	.then( editor => {
		$( "#btn" ).on( "click", function ( e ) {
			e.preventDefault();
			const data = editor.getData();
			console.log( $( '#editor' ).val() );
		} );
	} )
	.catch( error => {
		console.error( error );
	} );
```

**Comment by pomek** [comment]
You can read more about [`ClassicEditor.create()`](https://docs.ckeditor.com/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#static-function-create) method in [the documentation](https://docs.ckeditor.com/ckeditor5/latest/).

**Comment by MaximSemikov** [comment]
Thanks a lot!
