### ISSUE TITLE
[Advanced lists] add guide to CKE5 documentation

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#11705]
Add the advanced list information and demo.

Based on talk in the core team, this should be added to the existing lists guide to ultimately replace the old feature once it's extinguished.

**Comment by godai78** [comment]
Base user-oriented info and sample: https://ckeditor.com/blog/ckeditor-5-v34.0.0-with-redesigned-lists-new-styles-implementation-and-extended-dll-builds/#new-redesigned-lists

**Comment by apadol-cksource** [comment]
The feature is used by [import from Word](https://github.com/cksource/ckeditor5-internal/issues/1993) so should be also available in the documentation

Known issues:

- No support for track changes
- No support for todo lists
- Not used in any of the builds. All builds use the old lists for now

**Comment by godai78** [comment]
Merged: Merged: https://github.com/ckeditor/ckeditor5/pull/12489
