### ISSUE TITLE
[Style dropdown] `<a>` text style can be applied to any text node, instead of only `<a>` elements

### ISSUE THREAD

**Issue by wimleers** [ckeditor/ckeditor5#11709]
## 📝 Provide detailed reproduction steps (if any)

1. Configure `Style` to set a class on a link: 
```
{name: "Reliable source", element: "a", classes: ["reliable"]}
```
2. Edit content like this:
```
<p>Hello world.</p>
```
3. Click on the paragraph

### ✔️ Expected result

The `Reliable source` style is not available (`aria-disabled="true"`).

### ❌ Actual result

1. It _is_ available:
![Screenshot 2022-05-05 at 15 36 55](https://user-images.githubusercontent.com/14240/166939052-1a8ba92a-54c4-41bc-855c-cf2bf7f9502b.png)

2. It generates invalid markup, like so: 
```
<p><a class="reliable">Hello world.</a></p>
```
![Screenshot 2022-05-05 at 15 36 51](https://user-images.githubusercontent.com/14240/166939092-589005f6-108d-405d-a6bb-5bffc4e3b1f3.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: N/A
* OS: N/A
* First affected CKEditor version: `34.0.0`
* Installed CKEditor plugins: `Style`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by wimleers** [comment]
Discovered while working on the functional JS test coverage for Drupal: https://www.drupal.org/project/drupal/issues/3222797#comment-14505463.

**Comment by RichardDavies** [comment]
Another interesting behavior that I've observed is that if you select some text then apply a style with `<a>` as its defined element it wraps the selected text in an anchor tag without an `href` attribute as already described. Without deselecting the text, if you then click the link button and provide a URL to link to, after doing this whenever you click inside the link text the usual link bubble showing the URL and allowing you to edit the link does not appear in the editor.

However, if you perform those steps in the opposite order (i.e. create a link first and then apply the style) the link bubble does appear as expected when the link text is clicked. Interestingly, either order of operations results in the exact same HTML being applied to the text.

**Comment by Witoso** [comment]
We decided that the `a` element will be treated as an object (CKE4 reference). This means it will behave differently than other inline elements in the Style dropdown:
* You will not be able to apply `a` style to other elements, like `p`. It will not rename the element. The reasoning behind it is that you almost never want to create an `a` without a link.
* When you will have a cursor inside already present `a`, the Style dropdown should apply the class to the element you're in, not create an empty one that allows you to type in a new style as it's happening right now.

**Comment by Witoso** [comment]
Cases:
* collapsed: clear.
* ranges with more than one link
  * enabled: at least one link.
  * active: similar behavior as a block (first applicable decides).
