### ISSUE TITLE
[TS MVP] Automated tests should be able to cover code written in TypeScript

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#11716]
We need the possibility of running automated tests for packages that contain TypeScript code (like #11715).

Tests themselves doesn't have to be in TypeScript (imo, reimplementing them has the lowest value).

**Comment by Reinmar** [comment]
Will cover:

* the general support
* should work: code coverage, source maps
* the CK_DEBUG flag (the if statements)

Potentially useful link: https://istanbul.js.org/docs/tutorials/typescript/
