### ISSUE TITLE
[TS MVP] Rewrite ckeditor5-core

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#11727]
Rewrite `ckeditor5-core` to TypeScript.

Make sure that automated and manual tests run after the rewrite. Tests themselves are out of scope.

This would be the first serious application of `EmitterMixing` and typing of `Emitter` done in #11715.

**Comment by arkflpc** [comment]
Partially done on branch ck/11727-ts-core (https://github.com/ckeditor/ckeditor5/compare/ck/11727-ts-core?expand=1). It doesn't build because `ComponentFactory` (`ckeditor5-ui`) is not in TypeScript and I haven't figured out how to force it to compile. `index.js` is not in TypeScript because we import _\*.svg_ files there (I don't know how to approach this).

**Comment by arkflpc** [comment]
Partially done on branch ck/11727-ts-core (https://github.com/ckeditor/ckeditor5/compare/ck/11727-ts-core?expand=1). It doesn't build because `ComponentFactory` (`ckeditor5-ui`) is not in TypeScript and I haven't figured out how to force it to compile. `index.js` is not in TypeScript because we import _\*.svg_ files there (I don't know how to approach this).

**Comment by Reinmar** [comment]
Probably a solution here: https://stackoverflow.com/questions/42631645/webpack-import-typescript-module-both-normally-and-as-raw-string

**Comment by niegowski** [comment]
It might be connected with `raw-loader` being deprecated: https://v4.webpack.js.org/loaders/raw-loader/

**Comment by arkflpc** [comment]
Solution: https://stackoverflow.com/questions/44717164/unable-to-import-svg-files-in-typescript
