### ISSUE TITLE
[TS MVP] Rewrite ckeditor5-engine

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#11724]
Rewrite `ckeditor5-engine` to TypeScript.

Make sure that automated and manual tests run after the rewrite. Tests themselves are out of scope.

This would be the first serious application of `EmitterMixing` and typing of `Emitter` done in #11715.

**Comment by arkflpc** [comment]
Let's try to think about `Emitter` being more statically typed.

**Comment by Inviz** [comment]
nice work
