### ISSUE TITLE
Style command should check if the classes overlap with other active styles while removing

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11748]
## 📝 Provide detailed reproduction steps (if any)

1.  Open the styles guide.
2.  Apply a bright code block style (added `.fancy-code.fancy-code-bright`).
3.  Apply a dark code block style (there's no exclusive styles support yet), (added `.fancy-code.fancy-code-dark`).
4.  Remove the bright code block style.

### ✔️ Expected result

The code block is dark.

### ❌ Actual result

It's neither bright or dark. 

Removing the bright code style removed both `.fancy-code.fancy-code-bright`. Only `.fancy-code-dark` is left.

### ❓ Possible solution

When removing, style command should check if the classes overlap with other active styles. If another style was also applied that shares the same class, the class should be preserved.

**Comment by Witoso** [comment]
The OP example may be a bit confusing as it shows adding two styles that are actually exclusive. But a user may make this error by mistake, and correcting it (turning off one style), should result in proper styling.

Another example where this would be troublesome is when someone uses Tailwind CSS that is not using semantic class names, and classes tend to duplicate quite a lot.

**Comment by Witoso** [comment]
Acceptance criteria:
* given I applied two styles from the dropdown and those styles overlapping classes when I remove one style, then the overlapping classes stay on the element.
