### ISSUE TITLE
Column resize plugin should retain widths set by individual cells

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#11752]
## 📝 Provide detailed reproduction steps (if any)

When running today's `column-resize-master` (60b1ed9885) branch the tables pasted from other sources (e.g. CKE4, Word) with column widths customized

Issue based on today's `column-resize-master` (60b1ed9885) branch.

1. Copy a table that has varied cell widths from other source (e.g. CKE4, Word).
2. Paste it into editor with column resize enabled.

https://user-images.githubusercontent.com/5353898/168210715-bec57a21-bf76-425e-9c88-76c35c133e37.mp4

### ✔️ Expected result

Table layout (cell widths) should be retained.

### ❌ Actual result

Widths are lost.

### ❓ Possible solution

There's a [postfixer](https://github.com/ckeditor/ckeditor5/blob/60b1ed9885377fc86efb7ad8313ffde9f2f1c68e/packages/ckeditor5-table-resize/src/tablecolumnresize/tablecolumnresizeediting.js#L221-L227) that is meant to enforce `columnWidths` attribute presence for each table.

If there's no `columnWidths` attribute it enforces it with proportionally distributed width.

## 📃 Other details

* Browser: Any
* OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Branch [ck/epic/11857-table-resize-improvements](https://github.com/ckeditor/ckeditor5/tree/ck/epic/11857-table-resize-improvements) holds fixes for pasting tables with resized columns from CKE4 and Word. Pasting from Google Docs was extracted to a separate issue - #12023.
