### ISSUE TITLE
CKEditor v5 and DropZone, what is equivalent of UpdateElement?

### ISSUE THREAD

**Issue by kirk-quinbar** [ckeditor/ckeditor5#1176]
🐞 Bug report  |  🆕 Feature request  |  Other
Not sure which this is...

## 💻 Version of CKEditor

CKEditor v5 11.0.1 Classic build

## 📋 Steps to reproduce
I have an application where i am using CKEditor v4 and DropZone together so that there is an text editor that users can type in a message and then the UI will also allow attaching files. This is all done within the context of a form so both the text of the message and the file attachments will get posted to my server together. I recently upgraded this application to CKEditor v5 so we could support Content Security Policy (v4 is not compliant), but i found out that part of the code i had used in v4 does not work in v5. 

Dropzone will typically override submit and will do an ajax request on its own to the action of the form. With CKEditor v4 it was necessary to add something like this within the setup of Dropzone so when I clicked a button, it would process the queue which means it puts together an ajax post with the text and the files and posts it.

```
// First change the button to actually tell Dropzone to process the queue.
            this.element.querySelector("button[type=submit]").addEventListener("click", function (e) {
                // Make sure that the form isn't actually being sent.
                //UpdateBody();
                e.preventDefault();
                e.stopPropagation();

                var form = $("#replyForm");
                var isValid = form.valid();
                if (isValid) {
                    if (self.getQueuedFiles().length > 0) {
                        self.processQueue();
                    } else {
                        //pass an empty file to submit the form
                        var blob = new Blob();
                        blob.upload = { 'chunked': self.options.chunking };
                        self.uploadFile(blob);
                    }
                }
            });

function UpdateBody() {
         for (instance in CKEDITOR.instances) {
               CKEDITOR.instances[instance].updateElement();
           }
    }

```
With v5, obviously the code in the UpdateBody method no longer works. I tried calling updateElement on the new ckeditor class but that does not exist. I thought i saw something about an updateEditorElement method, but that seems to not exist either. If i dont do any kind of update like this with CKEditor v5, it never posts the value that i typed in the editor. it always posts blank.

Is there an equivalent for UpdateElement in v5 or is this possibly a bug or an implementation issue.

## ✅ Expected result
the form value for my text editor should post to the server

## ❎ Actual result
the form value for my text editor is always blank when it posts to the server.

**Comment by jodator** [comment]
@kirk-quinbar: This method is not available in CKEditor 5. You can enforce updating source element by using [`updateSourceElement()`](https://docs.ckeditor.com/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-updateSourceElement).

You can read more on [integrating editor with HTML forms](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/saving-data.html#automatic-integration-with-html-forms) in the integration guide. Also you can check [the migration from CKEditor 4 to CKEditor 5 guide](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/migrate.html).

If this will not help please reply here with more information about you setup (the HTML markup of the form and how do you integrate it with CKEditor).

**Comment by Reinmar** [comment]
There's [`editor.updateSourceElement()`](https://docs.ckeditor.com/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-updateSourceElement) :)

**Comment by kirk-quinbar** [comment]
In my testing updateSourceElement is slightly different than updateElement.  
- updateElement will set the textarea to blank/null if the CKEdtior only contains the base P tag, in other words if its empty, the textarea will be empty (no html code)
- updateSourceElement will always copy the html from CKEditor into the textarea, even if its consider "empty" meaning that base P tag is copies to the textarea.

Was this an intentional change in how these two methods work?

Because my backend service has a Required check to see whether the text is blank it will always not fail and ends up saving the base P tag to our db. i dont want to have to check whether that base P tag exists in my service code, so i ended up doing this:

```
function documentHasContent(doc) {
        return doc.model.hasContent(doc.getRoot());
    };

    function UpdateBody() {
        var doc = replyEditor.model.document;
        var isEmpty = !documentHasContent(doc);
        if (!isEmpty) {
            replyEditor.updateSourceElement();
        }

        //    for (instance in CKEDITOR.instances) {
        //        CKEDITOR.instances[instance].updateElement();
        //    }
    }
```

So that method will work, but for my purposes i just needed it to behave similar to how the old one did.
