### ISSUE TITLE
Docs issue report from "api/font.html"

### ISSUE THREAD

**Issue by PraRWS** [ckeditor/ckeditor5#11774]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/font.html

### Is there something missing in the guide? What is it?

How to add custom fonts in cke5, custom fonts are reflecting in the font style dropdown but the font style is not getting applied on text.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Could you add precise steps to reproduce the issue? It would be also good to see your editor configuration (especially font plugin). In the meantime, please make sure that apart from api docs you also read the [font family feature  docs](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-family-feature).

**Comment by Mgsy** [comment]
Closing due to a lack of feedback.
