### ISSUE TITLE
[Document list] Data conversion adds ck-list-bogus-paragraph span

### ISSUE THREAD

**Issue by pkliesch** [ckeditor/ckeditor5#11786]
## 📝 Provide detailed reproduction steps (if any)

1. Given an editor with the DocumentList plugin and SourceEditing plugin enabled. (There is no (default) list plugin enabled)
2. Use SourceEditing to set the following data in the editor: 
  ```
<ul>
        <li>
            Lorem
        </li>
        <li>
            Ipsum
        </li>
        <li>
            Dolor
        </li>
    </ul>
```
4. Switch to the editor and back to SourceEditing. The data will look as follows:
 ```
 <ul>
        <li>
            <span class="ck-list-bogus-paragraph">Lorem</span>
        </li>
        <li>
            <span class="ck-list-bogus-paragraph">Ipsum</span>
        </li>
        <li>
            <span class="ck-list-bogus-paragraph">Dolor</span>
        </li>
    </ul>
```

### ✔️ Expected result

The string, returned by the editor's toData() method, should not change its result.
This also applies for block elements, such as tables or paragraphs.
The expected result is the exact string, used to set the data in the editor in the first place:

  ```
<ul>
        <li>
            Lorem
        </li>
        <li>
            Ipsum
        </li>
        <li>
            Dolor
        </li>
    </ul>
```

### ❌ Actual result

The actual result like already shown above with additional spans and `ck-list-bogus-paragraph` class:

 ```
 <ul>
        <li>
            <span class="ck-list-bogus-paragraph">Lorem</span>
        </li>
        <li>
            <span class="ck-list-bogus-paragraph">Ipsum</span>
        </li>
        <li>
            <span class="ck-list-bogus-paragraph">Dolor</span>
        </li>
    </ul>
```

## 📃 Other details

* Browser: Chrome 97
* OS: Mac OS
* First affected CKEditor version: 34
* Installed CKEditor plugins:
Alignment, Autosave, BlockQuote, Bold, CodeBlock, Essentials, Heading, Highlight, ImageInline, ImageStyle, ImageToolbar, Indent, Italic, AutoLink, Link, DocumentList, Paragraph, PasteFromOffice, RemoveFormat, Strikethrough, SourceEditing,  Subscript, Superscript, Table, TableToolbar, Underline

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mmichaelis** [comment]
Just to state: Yes, we observed this problem and still can reproduce it with recent CKEditor versions (35.0.1). It is not only related to Source-Editing but effects the result of corresponding data read from server, when, when writing to server, contain this `ck-list-bogus-paragraph`.

Unfortunately, I was not able to reproduce this with a similar setup in JSFiddle:

* https://jsfiddle.net/zcy5fj3t/8/

For us, `editor.getData()` would return with these bogus class set.

It may be important to note, that we use a custom data-processor, which implements the `DataProcessor` interface similar to the example of the Markdown DataProcessor.

If we find any more details, we will provide them.

**Comment by niegowski** [comment]
> It may be important to note, that we use a custom data-processor, which implements the `DataProcessor` interface similar to the example of the Markdown DataProcessor.

This might be related to:

[https://github.com/ckeditor/ckeditor5/blob/bcf3d443f51fa33983eebde99c10f9859297b487/packages/ckeditor5-engine/src/view/domconverter.ts#L558-L562](https://github.com/ckeditor/ckeditor5/blob/bcf3d443f51fa33983eebde99c10f9859297b487/packages/ckeditor5-engine/src/view/domconverter.ts#L558-L562)

So this leads to some questions:

1.  Do you use `DomConverter` in your custom `DataProcessor`?
2.  If yes, is it initialized with `renderingMode` = `'data'` option?
3.  If you are not using `DomConverter` in your custom `DataProcessor` then maybe your implementation is missing the code linked above?

**Comment by mmichaelis** [comment]
Hi @niegowski,

thanks! This did the trick. We used the same approach as in old `XmlDataProcessor`:

https://github.com/ckeditor/ckeditor5/blob/06ab990ed66808ace2aedc2af045fa6e1c3f424e/packages/ckeditor5-engine/src/dataprocessor/xmldataprocessor.js#L57

which nowadays is, as you suggested:

https://github.com/ckeditor/ckeditor5/blob/19e609434f1fbc0755236d06b39dd8e9b0f8376a/packages/ckeditor5-engine/src/dataprocessor/xmldataprocessor.js#L54

Change introduced with: 021f3eda3fae9c0dd227b3e13eccb54109ab9cee, so as it seems, also the `blockFillerMode` should/could now be removed.

**Comment by yasirrose** [comment]
It seems that it is ckeditor issue. I am using `41.2.1` and getting this error. A temporary solution implemented by me is the following 

`ul li span.ck-list-bogus-paragraph {
    display: contents !important;
}`

I am using the same build for the inline editor and classic editor, and I am encountering this error only in the classic editor.

@niegowski

**Comment by nishioka-shinji** [comment]
I encountered the same error even with version 42.2.1. Implementing the solution provided in the previous comment resulted in a new bug where I couldn't input anything.

**Comment by Witoso** [comment]
This ticket should be closed. The editor will add `ck-list-bogus-paragraph`, we need this `span` due to various list editing reasons, and it only shows during the editing in the editor.

You **will not get it in the data** (i.e. `getData`), as could be tested in our [demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html). If you get it in the data, most likely you have a custom data processor. In this case, see the [comment](https://github.com/ckeditor/ckeditor5/issues/11786#issuecomment-1211573808) for the potential solution.
