### ISSUE TITLE
Custom UI (with Bootstrap) - read-only mode cannot be turned off

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#11791]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to: Custom UI (with Bootstrap) http://fake.cksource.com:8080/ckeditor5/latest/examples/framework/custom-ui.html
2.  Turn on read-only mode.
3.  Press the button again to turn read-only mode off.

### ✔️ Expected result

Read-only mode is turned off.

### ❌ Actual result

Read-only mode is still on and cannot be turned off: the editor remains grayed out however the button label changes after each click.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: All
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by godai78** [comment]
This is due to the API changes to the feature: https://ckeditor.com/docs/ckeditor5/latest/updating/migration-to-34.html#changed-mechanism-for-setting-and-clearing-the-editor-read-only-mode
