### ISSUE TITLE
Not possible to resize a table column anymore after undoing a cell merging operation

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#11797]
## 📝 Provide detailed reproduction steps (if any)

1. Open table column resize manual test: http://localhost:8125/ckeditor5-table/tests/manual/tablecolumnresize.html.
2. Merge a few full columns into one cell.
3. Undo.

### ✔️ Expected result

Each table column can be resized.

### ❌ Actual result

The right edge of the last selected column can't be resized anymore.

https://user-images.githubusercontent.com/56868128/169459428-222cf2bb-befd-4e81-bf5c-a87b3e7bdbcf.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
Another similar case:
1. In the same manual test select all cells in a table and merge them together.
2. Undo.

Error: no column can be resized anymore.

https://user-images.githubusercontent.com/56868128/169463021-ccb7b320-4522-4412-b379-804a29410d18.mp4

**Comment by Dumluregn** [comment]
Both cases are fixed on [ck/epic/11857-table-resize-improvements](https://github.com/ckeditor/ckeditor5/tree/ck/epic/11857-table-resize-improvements):

![](https://user-images.githubusercontent.com/10883184/182838667-0001a771-026a-4a31-b2a2-d9c94b528f8b.gif)
