### ISSUE TITLE
Consider using #!/bin/bash in scripts instead of #!/bin/sh

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1179]
On my computer `sh` points to the `bash` shell:

```
sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

I suspect on yours as well. The problem is that on other operating systems this is not always true (e.g. on some linux distrubutions there is [dash](https://askubuntu.com/questions/976485/what-is-the-point-of-sh-being-linked-to-dash)). It may cause various issues as  the shell linked by `sh` and `bash` may support in fact different syntax.

**Comment by oleq** [comment]
Which scripts are you referring to in particular? I only found two that would benefit from that and they're for internal use only.

```
ckeditor5/scripts/release-ckeditor5.sh
  1,1: #!/bin/sh

ckeditor5/scripts/switch-to-dev-dev.sh
  1,1: #!/bin/sh
```

**Comment by wwalc** [comment]
Whatever scripts we have and will create in the future :) - to avoid situation like we had with docs where @vokiel was unable to build&deploy them due to using a linux system. I'm proposing more a general rule/guidance here.
