### ISSUE TITLE
Remove a note stating that GHS is not production-ready from the source editing demo

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11806]
## 📝 Provide a description of requested docs changes

General HTML Support is production-ready and we have removed the warning in the guide, however, we missed one in the [source editing demo](https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html#demo).

Additionally, it would be good to scan all feature guides to make sure there are no more leftovers.

**Comment by godai78** [comment]
GHS status updated: 1e2f467
