### ISSUE TITLE
 how to upload image in my folder in my iis server ? 

### ISSUE THREAD

**Issue by suatsuphi** [ckeditor/ckeditor5#1180]
I can use this
ckfinder: {
uploadUrl: '@Html.Raw(Model.Setting.UploadUrlEditor)'
}

so I can upload in cksource.com but I want to upload my folder in my iis server ? how to use ckeditor5 for this aim ?

second question is how to close image button (that for upload image). 

thank you

**Comment by IamMK** [comment]
You need to use CKFinder from https://ckeditor.com/ckeditor-4/download/#ckfinder
Next, put it in your server/localhost, and as uploadUrl type: 'FOLDER_PREVIOUS_YOUR_CKFINDER_FOLDER/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'

**Comment by suatsuphi** [comment]
but this is ckeditor 4

**Comment by suatsuphi** [comment]
can I disable image button ?

**Comment by IamMK** [comment]
Yes. It's ckfinder for ckeditor4, but it works with ck5 too. And yes. You can disable image button. Then you will have to upload images by drag and drop.

**Comment by Reinmar** [comment]
Configuring the toolbar: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html#toolbar-setup
