### ISSUE TITLE
Feature Request - Math Equation

### ISSUE THREAD

**Issue by MahediSabuj** [ckeditor/ckeditor5#1181]
Is there any plan to introduce math equation like

![screen shot 2018-07-27 at 10 01 50 pm](https://user-images.githubusercontent.com/35859676/43332079-1688f218-91e9-11e8-995a-eeb6e08545df.png)

**Comment by ma2ciek** [comment]
It's a DUP of https://github.com/ckeditor/ckeditor5/issues/963.
