### ISSUE TITLE
[Safari] Broken toolbar UI on Safari 13

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11815]
## 📝 Provide detailed reproduction steps (if any)

1. Use Safari 13
2. Go to any editor demo page

### ❌ Actual result

The toolbar is broken:
![0_toolbar1_safari13](https://user-images.githubusercontent.com/34380544/169763479-3b342b71-1433-4e3e-9806-637e78bd434f.png)

## 📃 Other details

* Browser: Safari 13
* Introduced in version `34.0.0`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
What does the console say?

**Comment by FilipTokarski** [comment]
Nothing, unfortunately.

**Comment by oleq** [comment]
Most likely comes down to this one #11730.
