### ISSUE TITLE
TypeError: t is not a constructor

### ISSUE THREAD

**Issue by lokize** [ckeditor/ckeditor5#11812]
Hi, i have this error using vue 3 and quasar 2.6.0 with ckeditor/ckeditor5-build-classic": "^34.0.0" and @ckeditor/ckeditor5-vue": "^4.0.0",

![image](https://user-images.githubusercontent.com/19701630/169672137-c2a0ed03-2e76-40e8-86e5-9d62f22592d7.png)

**Comment by c4b4d4** [comment]
I'm experiencing the same issue. Happens when I add Custom Uploader Extra Plugin:

```
extraPlugins: [ (editor)=>{editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
    return new MyUploadAdapter( loader );
} } ]
```

**Comment by duongtq1909** [comment]
any one have a solution for this

**Comment by loves990** [comment]
https://github.com/ckeditor/ckeditor5-angular/issues/233
it works for me. (vue3)

   extraPlugins: [ function(editor) {editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
      return new [MY_ADAPTER]( loader );
   }}]

**Comment by raineorshine** [comment]
Believe it or not, changing the plugin from an arrow function to an old-school `function` definition fixed it for me. Thanks @loves990.

**Comment by Witoso** [comment]
Closing for now, no new information appeared from the OP, and we have information about fix in two comments.
