### ISSUE TITLE
custom editor creator example crashes 

### ISSUE THREAD

**Issue by cmak9149** [ckeditor/ckeditor5#11821]
## 📝 Provide detailed reproduction steps (if any)

1. Follow instructions in https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html#building-the-editor-from-source to create a editor (version 34)
2. Follow example in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/custom-editor-creator.html
3. Run the example and see the custom editor crashes in its constructor in this line "this.editor.config.set( 'initialData', initialData );" because "this.editor" is undefined. 

Note that our last version 15 works well, but there are many new plugins are not available in version 15.  

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._
I wonder "this.editor.config" should read "this.config".  

## 📃 Other details

* Browser: Chrome
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, you mentioned two separate guides - so which one is failing for you? Do you get errors when following both of them?

Apart from that, I see that the custom editor creator guide says `this.config.set( 'initialData', initialData );` not `this.editor.config.set( 'initialData', initialData );`, so there is no `editor` there:
  
![Screenshot 2022-05-31 at 13 49 56](https://user-images.githubusercontent.com/34380544/171166484-6e73e5f4-448e-4d96-bab3-184569b70f6d.png)

**Comment by cmak9149** [comment]
It was there when I copied it. In my post, I suggested the fixes. Is it
fixed after I reported it?
