### ISSUE TITLE
Unable to place the caret between inline images in Firefox

### ISSUE THREAD

**Issue by petrovich2k** [ckeditor/ckeditor5#11830]
It seems that the [issue#6532](https://github.com/ckeditor/ckeditor5/issues/6532) is still valid. I'm able to reproduce it in Firefox 100.0.2. I added 3 inline images, but I was unable to place the caret between them by clicking.
![mouse](https://user-images.githubusercontent.com/72270591/170390894-f9d83843-fc18-4296-95d1-6f1d18b29ffe.gif)

However, I could place the caret between images when I navigated with arrow key on my keyboard.
![keyboard](https://user-images.githubusercontent.com/72270591/170390965-760b7987-904d-4341-81e7-125c2cdfa1ce.gif)

## 📝 Reproduction steps

1. Open Ckeditor 5 in Firefox
2. Add a few inline images
3. Try to place the caret between them

### ✔️ Expected result

You are able to place the caret between inline images by clicking

### ❌ Actual result

You are unable to place the caret between inline images by clicking

### ❓ Possible solution

Workaround: If I add spaces between the images from keyboard, I can place the caret between the images with mouse.
![space](https://user-images.githubusercontent.com/72270591/170391004-8503eb0b-4860-4bd8-9413-6812954e744d.gif)

## 📃 Other details

* Browser: Firefox 100.0.2
* OS: Windows 10
* First affected CKEditor version: 34.0.1
* Installed CKEditor plugins: Essentials, UploadAdapter, Autoformat, Bold, Italic, BlockQuote, CKFinder, EasyImage, Heading, Image, ImageCaption, ImageStyle,ImageToolbar, ImageUpload, Indent, Link, List, MediaEmbed, Paragraph, PasteFromOffice, Table, TableToolbar, TextTransformation, CloudServices, Base64UploadAdapter

---

**Comment by jswiderski** [comment]
This is not only the case in Firefox but in all browsers. If images are next to each other and there is no space between them, it is rather normal that you won't be able to put caret there but you will be able to do it with keyboard arrows. 

For me this is a standard behaviour thus I'm marking this issue as won't fix.
