### ISSUE TITLE
Outdated mobile support information

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1183]
In [CKEditor 5 v. 11.0.0](https://ckeditor.com/blog/CKEditor-5-v11.0.0-released/) we significantly improved support for Android. Earlier on (e.g. in 10.1.0) we worked on reasonable iOS support.

Unfortunately the documentation states a really outdated information about the mobile support: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/support/browser-compatibility.html#mobile-environment

I think the documentation should be shortened, mentioning which versions of Android/iOS are supported and that's it. Mentioning "Special UI, designed for mobile." is heavily misleading as we had no time for it for the past two years and it does not seem to change.

**Comment by f1ames** [comment]
We have discussed this some time ago with @Reinmar and come to the conclusion that for mobile browsers we could state it the same way as for desktop, using **latest stable release**. However, as we are in fact supporting Android 6 - 8 (so all [officially supported versions](https://en.wikipedia.org/wiki/Android_version_history)) we could use something like **all officially supported versions** (so it will be Android 6 - 8 and iOS 11 AFAIR).

We can describe version numbers explicitly (so in fact skipping **all officially supported versions**), but then it will need to be updated from time to time.
From the other hand, if we just say **all officially supported versions**, the user will need to find on his own which versions are officially supported. I'm not sure which will work better 🤔

**Comment by wwalc** [comment]
what with using something like:

> all officially supported versions (see [Android vendor support](#) and [iOS vendor support](#))

Of course as long as we can find some reliable links.

Cons: we never now when a link to 3rd party site breaks. Unless Umberto checks it already, don't remember. Also don't know

**Comment by f1ames** [comment]
> all officially supported versions (see [Android vendor support](#) and [iOS vendor support](#))

If Umberto checks for broken links and we will be able to find official information (e.g. Google and Apple sites) about supported versions that would be perfect.

If not still it seems like a good idea to link to some reasonable site (Wikipedia might be ok as there is a very low chance that the page will disappear), so 👍

**Comment by AnnaTomanek** [comment]
Since I cannot seem to be able to find any reliable links (apart from Wikipedia which, while reliable, is not a vendor site), I'd propose to go with the "all officially supported versions".

If someone reports an issue for mobile, we already ask for an env version number, and this will be quick to verify. At the same time, maintaining the site with explicit version numbers will be yet another thing that we will need to remember about, and which we will - sooner or later - fail to keep up to date at some point, just like we did this time.

**Comment by AnnaTomanek** [comment]
Updated the compatibility page in https://github.com/ckeditor/ckeditor5/commit/179a3a2990a48e8a01f36c5bb0c64ac659ead4a4.
