### ISSUE TITLE
Inline images don't get the .image-inline class applied to them

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#11840]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html
2. Insert an inline image anywhere
3. Click "view source"

### ✔️ Expected result

The source includes an element with a class `.image-inline`.

### ❌ Actual result

The source just includes an `<img>` with no classes assigned. When rendered using the styles from https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html, inline images show up as block images. This happens regardless of "view source" — in our app we just use `getData` — but "view source" is the easiest way to replicate the issue.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1523306/170823715-b3c588e3-b1b4-4a89-886f-eb2b645c50d1.png">

## 📃 Other details

I'm using CKEditor 34.1.0.

* Browser: Chrome
* OS: macOS
* First affected CKEditor version: ?
* Installed CKEditor plugins: ?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
For us, this is a show-stopper for upgrading to CKEditor 34.

**Comment by mlewand** [comment]
@neongreen why is it a show-stopper for upgrading to v34? Did CKEditor 5 ever work in a way that it included the `image-inline` class in output data pipeline?

I don't think it was ever the case, take a look at 31.0.0 docs permalink: [https://ckeditor.com/docs/ckeditor5/31.0.0/features/source-editing.html](https://ckeditor.com/docs/ckeditor5/31.0.0/features/source-editing.html)

There's no such class added as well.

Basically what you'd want to do is to add an extra `data` downcast converter that would add such class for the `imageInline` model element. You can find the documentation on conversion here: [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/intro.html.](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/intro.html.) 

However, you wrote the issue like it would be a regression while I can't see that. Is there something I'm missing?

**Comment by neongreen** [comment]
@mlewand I assumed that that class was responsible for images being displayed as inline, since it's present in content styles (https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html) and the name seemed self-explanatory.

I just tried copying the content styles and the source code emitted for text including inline images, and it turns out that the image is correctly displayed as inline. The issue must be elsewhere then. (I'm also using the same content styles in my app and inline images broke after the 34.1.0 upgrade.)

Sorry for the false alarm!
