### ISSUE TITLE
Enhance the discoverability of keystroke to focus the toolbar

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#11846]
## 📝 Provide a description of the improvement

Currently the toolbar is focusable by pressing <kbd>Alt</kbd> + <kbd>F10</kbd>. However, the information about that keystroke is not conveyed in any way. In CKEditor 4 it is placed inside the accessibility help dialog and it could be done the same here (after the dialog is implemented and made discoverable also for non-screen reader users, see #1014). Alternatively, it can be done the same method we'll choose for making the a11y dialog discoverable to keyboard-only users.

## 📃 Other details

* Browser: all
* OS: all
* CKEditor version: all
* Installed CKEditor plugins: N/A

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This issue will be solved by #1014.
