### ISSUE TITLE
Color button focusing order doesn’t follow any logic

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#11841]
## 📝 Provide detailed reproduction steps (if any)

1. Open [full-featured editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html).
2. Navigate to Font color button using keyboard.
3. Try to navigate between: "remove color" button, color pallette and document colors section.

### ✔️ Expected result

1. Navigation between "remove color" button, color pallette and document colors section is intuitive.

### ❌ Actual result

1. You can switch between "remove color" button and color pallette by using arrow down key, but to access document colors below, you have to press arrow up key.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by tony1377** [comment]
Any idea when a fix for this this might be released?

**Comment by mlewand** [comment]
@tony1377 we plan to ship it on August 31st.

You can always find the overview (including dates) in our [iteration roadmap issues](https://github.com/ckeditor/ckeditor5/issues/12107) for each release. We also pin these issues for better visibility.
