### ISSUE TITLE
CKEditor Ecosystem Documentation could not to search

### ISSUE THREAD

**Issue by caifu23** [ckeditor/ckeditor5#11854]
## 📝 CKEditor Ecosystem Documentation 
https://ckeditor.com/docs/index.html
![image](https://user-images.githubusercontent.com/32030031/171136675-550d770e-67f7-46cf-87bc-2925c412d5e9.png)

**Comment by FilipTokarski** [comment]
Hi, not sure why you get the error, docs seem to work fine. I'm able to search on every sub-page without any errors. Did you try clearing cache and reloading?
Regarding line height, currently such feature is not available by default. There is a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/1429), so feel free to add 👍  to bump its popularity.

**Comment by caifu23** [comment]
I clear cache and reload, but mistakes remain

**Comment by caifu23** [comment]
now it‘s resolved !
