### ISSUE TITLE
The cursor does not move to the correct location after a click

### ISSUE THREAD

**Issue by zhebil** [ckeditor/ckeditor5#11864]
## 📝 Provide detailed reproduction steps (if any)

1.  Make sure you have the "Tap to click" option enabled in macOS's trackpad settings
2.  Open demo https://ckeditor.com/collaboration/demo/
3.  Click in different places in the text

### ✔️ Expected result

Cursor immediately jumps to the clicked location

### ❌ Actual result

Cursor jumps after 2-3 clicks

## 📃 Other details

*   Browser: Chrome or Opera (safari and firefox are ok)
*   OS: MacOS 12.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

https://user-images.githubusercontent.com/63890293/171416253-2f53632a-9b51-47c9-a5a5-1bf88fd991b8.mov

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I was not able to reproduce this. Selection reacts to every click and the cursor shows up accordingly. Maybe you have some browser addons that cause the issue?

**Comment by zhebil** [comment]
Hi. 
No, even without addons the bug remains. Could this be related to the OS version?
I have a macbook m1 Monterey 12.1

**Comment by FilipTokarski** [comment]
I checked it on m1 Monterey 12.2, so I guess it's not the case of OS. Does it happen on every demo or just the one with real-time collaboration? Does it also happen for you on [docs demos](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)?

**Comment by zhebil** [comment]
Yes, this happens every time for me and my colleagues. And it happens the same way without collaborations mode

**Comment by Reinmar** [comment]
cc @scofalik 

BTW, AFAIR @mmotyczynska discovered at some point that this "tap to click" setting changes something in mouse events. Do you remember what it was?

**Comment by mmotyczynska** [comment]
Unfortunately it wasn't me, I didn't even have this option turned on. The last time I was working on different behaviour for mousedown was that in Safari we had to fire the focus() manually (in BuToonView), but this is not the case here unfortunately as the issue relates to Chrome and Opera.

**Comment by Reinmar** [comment]
It can be reproduced easily without any richer editor features.

1.  Select something in the editor.
2.  Tap in another place in the editor.

It sometimes work, but most of the time it doesn't. We'll take a look.

**Comment by Reinmar** [comment]
The tapping that works:

```
mousedown 136306.79999995232
selectionchange 136313
mouseup 136368.5
click 136375.40000009537
```

This is the tapping that does not move the selection:

```
mousedown 150447.09999990463
mouseup 150465.40000009537
click 150469.29999995232
selectionchange 150473.79999995232
selectionchange 150476.20000004768
selectionchange 150477.70000004768
```

Mind the different order of events. In the event that worked, the selectionchange was before mouseup and click.

**Comment by Reinmar** [comment]
Hypothesis: ckeditor/ckeditor5#12175 might've resolved this issue.

**Comment by Reinmar** [comment]
Confirmed :point\_up: 

The problem existed because we were re-rendering the DOM (and thus moving the selection back to its previous place) on `mouseup`, before we got `selectionchange`. Now, we force upcasting the selection on that `mouseup` and thus update the model so the render back to the DOM doesn't revert the selection change.

**Comment by rafalsk** [comment]
We're experiencing the very same issue on Windows / Chromium, when classic editor is embedded within an obsoletely positioned container.

Do builds produced by the 'online builder' already take use of these changes?

**Comment by scofalik** [comment]
This change was released just a few hours ago in `v35.2.0` of CKEditor 5. At the moment, online builder already creates build of the new version of CKE5. Make sure that you are testing using this version.

**Comment by rafalsk** [comment]
@scofalik glad see lots of Poles behind the project!
Anyway, is there any way to 'update' the local build without the need of re-applying all of the custom settings ?

**Comment by rafalsk** [comment]
@scofalik @Reinmar well... from the user's perspective, in our case, the experience in the current release is even worse.

The cursor does follow each click/tap now... but... it only guess to the beginning of each line. Beginning only.

**Comment by carlosixcsoft** [comment]
Hello everyone, I am also facing the issue. Is there already a solution for this error?

**Comment by filipsobol** [comment]
I couldn't reproduce this. I've tested it on Fedora 39 with both Chrome 120 and Firefox 121 and it works fine. The cursor doesn't jump, one click puts the caret at the mouse position, two clicks selects the word, three clicks selects the paragraph.

**Comment by thienhuynh1314** [comment]
Hello everyone, I'm using version 43.1.1 of CKEDITOR 5 and this issue still occur. I'm using Google Chrome on MacOS and my colleague are using Google Chrome on Window
