### ISSUE TITLE
Toggle TrackChanges outside of CKEditor toolbar

### ISSUE THREAD

**Issue by metinmayi** [ckeditor/ckeditor5#11877]
## Provide a description of the task
I've installed TrackChanges and can toggle it through the CKEditor toolbar.
I want to toggle TrackChanges from an element that is not contained in the CKeditor itself. Is there any neat way of doing this currently?

_What steps should be taken to fulfill the task?_
An eventlistener that fires to toggle the TrackChanges.

## 📃 Other details

* CKEditor version: 5

**Comment by FilipTokarski** [comment]
Hi, Track Changes is a commercial plugin and this repository is mainly for the open-source part of the CKEditor 5 project. If you are a licensed user and have any problems or questions, we highly recommend to [contact us through the support channel](https://ckeditor.com/contact/). Our customer care team will analyse the request and get back to you as soon as possible.

Now, regarding the toggling of the track changes mode, you can always use the trackChanges [command](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html):
```js
editor.execute( 'trackChanges' );
```

**Comment by metinmayi** [comment]
Hi Filip!

Thanks for replying, I did find that command later, turns out I’m just horrible at reading documentation.
We are indeed licensed and are very satisfied with the CKEditor.

Have a good day
