### ISSUE TITLE
Memory Leak in TableColumnResize

### ISSUE THREAD

**Issue by aStewartDesign** [ckeditor/ckeditor5#11870]
## 📝 Provide detailed reproduction steps (if any)

1. Create editor
2. Destroy editor
3. Event listeners leak

### ✔️ Expected result

No leaking listeners

### ❌ Actual result

Listeners on a `domEmitter` instance are not removed and leak.

### ❓ Possible solution

Make sure `domEmitter.stopListening()` is called on destroy.  (PR coming soon)

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: 34.1.0
* Installed CKEditor plugins: Table, TableColumnResize

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Done in https://github.com/ckeditor/ckeditor5/pull/11871.
