### ISSUE TITLE
how to use colorPicker in fontColor plugins

### ISSUE THREAD

**Issue by caifu23** [ckeditor/ckeditor5#11887]
## 📝 Provide detailed reproduction steps (if any)

1. use plugins of fontColor or backgroundColor，how to use Color Picker？
2. Below is an example of version  ckeditor4
![image](https://user-images.githubusercontent.com/32030031/172351077-a0b97f06-b0c2-46e2-b722-980b3241cde9.png)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, currently the ability to open an additional color picker is not available. You can always [adjust the configuration](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-color-and-font-background-color-features) of the font color/background color plugins to contain the colors you need. Would that be sufficient for your use case?

**Comment by ThiefMaster** [comment]
I'm also missing the option to open a color picker or AT LEAST let people enter a custom color code... Power users may not appreciate suddenly no longer being able to use whatever color they want...

**Comment by AliaksandrBortnik** [comment]
There is already built-in option starting from 38th version.

**Comment by FilipTokarski** [comment]
Yes, thank you @AliaksandrBortnik for mentioning this :) 

[In version 38.0.0 we have introduced color picker for font color and font bacground color.](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-38.html#introduction-of-color-pickers-to-font-color-and-font-background-color-features) For anyone interested in this issue, please see the [font plugin documentation](https://ckeditor.com/docs/ckeditor5/latest/features/font.html) for more details.

I'll close this ticket, as it's no more relevant.
