### ISSUE TITLE
[TS] Allow running tests written in TS (automated, manual)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11888]
For instance
* `yarn test --browsers="ChromeHeadless" --reporter="dots" --files="utils/dom/iswindow.ts"`
* `yarn manual --files="utils/manual/diff/diff.ts"`

**Comment by Witoso** [comment]
fyi @pomek, we have this issue.

**Comment by pomek** [comment]
Closing as done (see: #14170, #14171).
