### ISSUE TITLE
Remove format and source buttons not working in custom build

### ISSUE THREAD

**Issue by neilmulhy** [ckeditor/ckeditor5#11890]
## 📝 Provide detailed reproduction steps (if any)

1. …Go to https://ckeditor.com/ckeditor-5/online-builder/
2. …Select options as per, note the remove format and source editing features added
![image](https://user-images.githubusercontent.com/33902835/172382379-b90e634e-170d-4e31-aa6f-d05f82d3d0fd.png)
3. …Add buttons to the picked toolbar items
![image](https://user-images.githubusercontent.com/33902835/172382445-251765df-c29b-47b0-b600-4c7850e3e0d4.png)
4. ...Choose English (United Kingdom) as the language
5. ...Download the custom build
6. ...Open the sample\index.html file from the downloaded zip file in a browser and try clicking the remove format / source buttons.
![image](https://user-images.githubusercontent.com/33902835/172382479-59ee3f60-fb95-4951-9be0-8189fd4904a1.png)

### ✔️ Expected result
Remove format button would remove the style formats from the selected text. 
Source should display the raw html behind the CKEditor content / data.

### ❌ Actual result
The buttons are visible and the tooltip hover text displays but nothing happens when the buttons are clicked.

## 📃 Other details

* Browser: …Chrome 102.0.5005.63
* OS: …Windows 10 Pro 21H2
* No errors / warnings are displayed  in the browser console.

**Comment by neilmulhy** [comment]
Apologies, I missed that the source editor is only supported for the classic style. I was using the Decoupled style.
![image](https://user-images.githubusercontent.com/33902835/172391170-d79739aa-1b30-4bae-91fd-514b1f3407f6.png)

I've created another build, using the classic style. The source button does work now.

Also, I thought the remove format would change a heading style to normal but it doesn't. Not sure if this should be an enhancement but I guess it's not a bug as it does remove bold / italics / etc.

I'll close this issue.

**Comment by Reinmar** [comment]
> Also, I thought the remove format would change a heading style to normal but it doesn't. Not sure if this should be an enhancement but I guess it's not a bug as it does remove bold / italics / etc.

Visual formatting and semantical formatting are differentiated here. The remove format cleans up the former. The latter - headings, lists, blockquotes, even links will remain untouched.
