### ISSUE TITLE
Insert Content from external Button

### ISSUE THREAD

**Issue by skerbis** [ckeditor/ckeditor5#1189]
## Feature request? / Question

  🆕 Feature request  

## 📃 Is it possible to insert content into the editor from external e.g. Buttons to the cursor position?
Example i have generated markup from a dataset (perhaps Textsnippets, or Links) and i would like to insert it into the editor. This would make it possible to add features to the editor in our CMS project specific without the need of a new build.

**Comment by oleq** [comment]
Inserting content is possible using the model/writer API as [explained in the FAQ](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#where-are-the-editorinserthtml-and-editorinserttext-methods-how-to-insert-some-content).
