### ISSUE TITLE
customize comment html structure

### ISSUE THREAD

**Issue by amitShimon1983** [ckeditor/ckeditor5#11892]
## 📝 Provide a description of the new feature
using KC editor 5
_What is the expected behavior of the proposed feature?_
Hey I'm using the Comments plugin, do you have a way I can change the appearance of the comment HTML?

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, Comments is a commercial feature and this repository is mainly for the open-source part of the CKEditor 5 project. If you are a licensed user, please reach out to us through the [official support channel](https://ckeditor.com/contact/). Our support team will analyse the request and get back to you as soon as possible.
