### ISSUE TITLE
[IME@Android] Enter doesn't work at the end of the line while using GBoard

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11906]
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`.

## 📝 Provide detailed reproduction steps (if any)

1.  Use Android with GBoard.
2.  Put the caret at the end of the block.
3.  Press Enter.

### ✔️ Expected result

The new line is inserted.

### ❌ Actual result

Nothing happens.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Acrophost** [comment]
Still persists on branch `ck/11438-beforeinput-ime-research-vol1.1-android` as mentioned [here](https://github.com/ckeditor/ckeditor5/issues/12058#issuecomment-1220904956).

Enter does work in an instance where a whitespace is added at the end of a line (sometimes spacebar has to be pressed twice for that).

**Comment by Acrophost** [comment]
Works correctly after fixes on `ck/11438-beforeinput-ime-research-vol1.1-android`
