### ISSUE TITLE
Deleting content spanning different tags messes up html structure

### ISSUE THREAD

**Issue by jbalsas** [ckeditor/ckeditor5#1190]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Tested directly on https://ckeditor.com/ckeditor-5/

## 📋 Steps to reproduce

1. Navigate to https://ckeditor.com/ckeditor-5/
2. Select content spanning different tags, header and paragraph (see animated attachment) making sure all the content in the header block is selected
3. Press backspace to delete the selection

## ✅ Expected result

The second block of content remains untouched and inside a `<p>` element rather than collapsing into the `<h*>` element.

## ❎ Actual result

The second block of content remains untouched and inside a `<p>` element rather than collapsing into the `<h*>` element.

## 📃 Other details that might be useful

This might make sense when partially selecting a preceding tag, but when selecting it completely the expectation is more likely to remove the tag completely.

Browser: Chrome, Firefox
OS: OSX
CKEditor version: CKEditor5 & CKEditor4
Installed CKEditor plugins: Out of the Box Demo

Based on some discussion in this [report for CKEditor 4](https://github.com/ckeditor/ckeditor-dev/issues/2279#issuecomment-409893970), this is default browser behaviour: https://codepen.io/msamsel/pen/YjLGKz

![delete_h1](https://user-images.githubusercontent.com/905006/43585003-487d196e-9664-11e8-86fd-c127f677575b.gif)

**Comment by Mgsy** [comment]
Hello, this is a DUP of https://github.com/ckeditor/ckeditor5-typing/issues/146. Feel free to join the discussion!
