### ISSUE TITLE
[IME@Android] Typing over a widget in Japanese automatically transforms a word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11908]
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`.

## 📝 Provide detailed reproduction steps (if any)

1.  Use Android, Swiftkey and Japanese.
2.  Open http://localhost:8125/ckeditor5/tests/manual/all-features.html.
3.  Select the image below the _Image_ header.
4.  Type "mo".

### ✔️ Expected result

The composition works properly.

### ❌ Actual result

The header _Image_ has been partially transformed into a Japanese word.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

Works fine in GBoard.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Acrophost** [comment]
Issue is no longer reproducible on branch [ck/11438-beforeinput-ime-research-vol1.1-android](https://github.com/ckeditor/ckeditor5/compare/ck/epic/11438-migrate-to-beforeinput...ck/11438-beforeinput-ime-research-vol1.1-android).

Fixed as a part of [#12058](https://github.com/ckeditor/ckeditor5/issues/12058)
