### ISSUE TITLE
Suggestion: docs should provide an example of keeping data-* or data-xyz attributes, on links / anchor tags

### ISSUE THREAD

**Issue by hangtwenty** [ckeditor/ckeditor5#11903]
## 📝 Provide a description of requested docs changes

As mentioned here, https://github.com/ckeditor/ckeditor5-react/issues/209 , you cannot use `extraAllowedContent` with CKEditor5; and in the CKEditor5 FAQ there's this section:

> Why does the editor filter out my content (styles, classes, elements)? Where is config.allowedContent = true?
> Unlike [CKEditor 4](https://ckeditor.com/ckeditor-4/), CKEditor 5 implements a custom [data model](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html). This means that every piece of content that is loaded into the editor needs to be converted to that model and then rendered back to the view.
> 
> Each kind of content must be handled by some feature [...]
> 
> If you load some content unknown to any editor feature, it will be dropped. If you want all the HTML5 elements to be supported, you need to write plugins to support them. Once you do that, CKEditor 5 will not filter anything out.

It would be great if this provided an example of allowing `data-*` attributes (or just one attribute, like  `data-auto="1"`), on `<a>` elements / Links.

Is there a way that's lighter weight than a "custom plugin"?

I'm unclear how to do it with a "plugin" for example, because when I've tried to make a custom plugin, I've gotten this error (due to `import Plugin` or something, I'm not totally sure):

```
Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at version.js:151:8
```

**Comment by hangtwenty** [comment]
Forgot to mention, this page in the docs is very helpful — https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/intro.html — but does not have an example. I think if an example were added, this would be a good place for it; and the FAQ question about conversion/custom-attributes could link there.

**Comment by jswiderski** [comment]
Please have a look at https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html. 

Instead of building custom plugins you can create a custom build using CKEditor 5 online builder which includes General HTML Support (GHS) feature. Once you have that, you can use the following configuration to preserve your attribute:
```
		htmlSupport: {	
			allow: [
				{
					name : 'a',
					attributes: {
						'data-auto' : true
					}
				}
...

```
