### ISSUE TITLE
[IME@Android] Chinese text is not inserted after choosing a word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11909]
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`.

## 📝 Provide detailed reproduction steps (if any)

1.  Use Android, Swiftkey and Chinese simplified.
2.  Type "moji".
3.  Choose the first proposition from the composition box.

### ✔️ Expected result

The word is inserted.

### ❌ Actual result

The composition doesn't end, there is "mo" converted to Chinese and not-converted "i" in the composition box.

## 📃 Other details

It works properly on the non-collapsed selection.
It works properly with GBoard.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Acrophost** [comment]
Issue still persists on branch [ck/11438-beforeinput-ime-research-vol1.1-android](https://github.com/ckeditor/ckeditor5/compare/ck/epic/11438-migrate-to-beforeinput...ck/11438-beforeinput-ime-research-vol1.1-android).

**Comment by Acrophost** [comment]
Issue is no longer reproducible on branch `ck/11438-beforeinput-ime-research-vol1.1-android`
