### ISSUE TITLE
[IME] Writing in a language that uses composition in the non-empty paragraphs crash writing functionality

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11911]
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`.

## 📝 Provide detailed reproduction steps (if any)

1. Open http://localhost:8125/ckeditor5/tests/manual/all-features.html in Firefox
2. Put the cursor into the middle of the text and try to write something in e.g. Japanese

### ✔️ Expected result

Composition shows up and text is being inserted

### ❌ Actual result

Composition shows up, but text is not being inserted and multiple errors as below are thrown into the console: 
```
Uncaught TypeError: domParent.parentNode is null
    domPositionToView domconverter.js:828
    domRangeToView domconverter.js:782
    targetRanges inputobserver.js:90
    onDomEvent inputobserver.js:89
    observe domeventobserver.js:79
    fire emittermixin.js:200
    domListener emittermixin.js:293
    attach emittermixin.js:219
    _addEventListener emittermixin.js:264
    addEventListener emittermixin.js:688
    listenTo emittermixin.js:118
    listenTo emittermixin.js:68
    listenTo emittermixin.js:65
    observe domeventobserver.js:77
    observe domeventobserver.js:76
    attachDomRoot view.js:294
    init classiceditorui.js:104
    create classiceditor.js:205
    promise callback*__webpack_modules__</create/< classiceditor.js:205
    create classiceditor.js:200
    <anonymous> all-features.js:52
    <anonymous> all-features.js:154811
    <anonymous> all-features.js:154813
domconverter.js:828
```
![IME Firefox issue](https://user-images.githubusercontent.com/32898551/173051084-de326480-d817-4f74-9590-21100720f96a.gif)

## 📃 Other details

* Browser: Firefox

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Acrophost** [comment]
Can't be reproduced at branch [ck/11438-beforeinput-ime-research-vol1.1-android](https://github.com/ckeditor/ckeditor5/compare/ck/epic/11438-migrate-to-beforeinput...ck/11438-beforeinput-ime-research-vol1.1-android) - the mechanism changed and there are no longer any errors thrown in console.

https://user-images.githubusercontent.com/66953380/187214841-7212c65e-75f5-463d-bc62-d7a677ec119f.mov
