### ISSUE TITLE
Use github issues templates (like in CKEditor 4)

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1191]
As current template is used in various way - not always we the creator's intention - we could use the issue templates as this is [already implemented by the CKEditor 4 team](https://github.com/ckeditor/ckeditor-dev/issues/new/choose).

**Comment by oleq** [comment]
cc @wwalc

**Comment by jodator** [comment]
Explore if we can use the query params to further enhance issues (ie when linking from docs or other repositories): https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters
