### ISSUE TITLE
[IME] Composition doesn't show up or show up above the editor toolbar when trying to write with the widget selected

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#11910]
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`.

## 📝 Provide detailed reproduction steps (if any)

1. Open http://localhost:8125/ckeditor5/tests/manual/all-features.html on Safari
2. Select the image and start to type in the language that requires composition e.g. Japanese

### ✔️ Expected result

The image disappears and the composition shown in its place.

### ❌ Actual result

The image is still present, but the composition doesn't show up or show up above the editor's toolbar, and the image disappears only after enter is pressed.

## 📃 Other details

* Browser: Safari
Does not reproduce on Chrome, Firefox and Safari@Mobile

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Acrophost** [comment]
Not reproducible on branch [ck/11438-beforeinput-ime-research-vol1.1-android](https://github.com/ckeditor/ckeditor5/compare/ck/epic/11438-migrate-to-beforeinput...ck/11438-beforeinput-ime-research-vol1.1-android).
Currently the image disappears after starting typing and the composition shows up, but it needs to be accepted with enter.
