### ISSUE TITLE
Pasting multiple images or full content from MS Word 2013 skips images

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11921]
## 📝 Provide detailed reproduction steps (if any)

1. Open attached file and copy/paste its content into editor.

### ✔️ Expected result

Whether you are copying single image, multiple images or all content, images should get pasted in all cases.

### ❌ Actual result

Copying single image works fine.
Copying/Pasting more than one image doesn't paste images.
Copying/Pasting full content doesn't paste images.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: N/A
* Installed CKEditor plugins: paste-from-office
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Closed as mentioned here: https://github.com/ckeditor/ckeditor5/issues/2493#issuecomment-1459981600
