### ISSUE TITLE
Docs issue report from "features/images/image-upload/images-inserting.html"

### ISSUE THREAD

**Issue by jensenbox** [ckeditor/ckeditor5#11933]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/images-inserting.html

### Project version

34.1.0

### Is the information outdated? How?

No

### Is there something missing in the guide? What is it?

I am implementing a solution with CKEditor but only want users to be able to use images hosted elsewhere - I rather not handle all the upload logic and everything that entails.

Thus far I have `insertImage` working as desired BUT the main image button still opens an OS File browser.

If I only enable `insertImage` the button is disabled and I am unable to use URLs for images.

I would like to be able to disable the file browser (upload) function but still retain the ability to insert images from a URL.

Am I missing a setting?

### Is there anything else you would like to add?

I really REALLY love this software!

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by dufipl** [comment]
Hello @jensenbox,
I'm really glad to see that you enjoy using CKEditor 5! :) 

Unfortunately, such kind of behaviour cannot be achieved without modification of our standard image plugins e.g. `InsertImage`. So one of your options is to create your custom modification of the plugin which will work in a way that you want or, as a workaround, you can use `AutoImage` (https://ckeditor.com/docs/ckeditor5/latest/api/module_image_autoimage-AutoImage.html, https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/images-inserting.html#inserting-images-via-pasting-url-into-editor), which dynamically detects image links pasted to the editor and changes them to pictures. If you decide on the second option, probably you would like to not have an image button in the toolbar at all.

I hope that helps, but if something remains unclear please let me know in a comment.
