### ISSUE TITLE
Balloon panel wrong position

### ISSUE THREAD

**Issue by rafalolszewski94** [ckeditor/ckeditor5#1193]
🐞 Bug report
## 💻 Version of CKEditor

Editor used: `@ckeditor/ckeditor5-editor-classic`, version `11.0.0`

Plugins used in build:
```javascript
Essentials,
UploadAdapter,
Heading,
Paragraph,
Bold,
Code,
Italic,
BlockQuote,
Image,
ImageCaption,
ImageStyle,
ImageToolbar,
ImageUpload,
Link,
List,
Alignment,
Autosave,
KbArticles,
```

Dependencies and versions:
```json
"@ckeditor/ckeditor5-alignment": "10.0.2",
"@ckeditor/ckeditor5-autosave": "10.0.0",
"@ckeditor/ckeditor5-basic-styles": "10.0.2",
"@ckeditor/ckeditor5-block-quote": "10.0.2",
"@ckeditor/ckeditor5-build-classic": "11.0.1",
"@ckeditor/ckeditor5-core": "11.0.0",
"@ckeditor/ckeditor5-editor-balloon": "11.0.0",
"@ckeditor/ckeditor5-editor-classic": "11.0.0",
"@ckeditor/ckeditor5-essentials": "10.1.1",
"@ckeditor/ckeditor5-heading": "10.0.2",
"@ckeditor/ckeditor5-image": "10.2.0",
"@ckeditor/ckeditor5-link": "10.0.3",
"@ckeditor/ckeditor5-list": "11.0.1",
"@ckeditor/ckeditor5-paragraph": "10.0.2",
"@ckeditor/ckeditor5-theme-lark": "11.0.0",
"@ckeditor/ckeditor5-ui": "11.0.0",
```

Webpack version (if needed):
```bash
➜ npx webpack --version
3.11.0
```

There's 2 custom plugins (`UploadAdapter` and `KbArticles`), none of them make any difference while included or excluded within the build.

## 📋 Steps to reproduce

1. Unfortunately none, since it randomly happens while building with Webpack (haven't tested it with any other bundler).

## ✅ Expected result
Position balloon panel always at the right position.

## ❎ Actual result
Balloon panel goes crazy, and positions itself at the end of the page.
For me it seems like it's related somehow to cache(?!), since last friday till now, balloon panel was positioning itself correctly.

## 📃 Other details that might be useful
This is how it looks, it's calculating wrong the offset to put balloon panel near image / link / anywhere else where it's used.
![image](https://user-images.githubusercontent.com/37925892/43717005-6788471e-9986-11e8-9f23-a55aeeba6967.png)

**Comment by pjasiun** [comment]
CKEditor 5 attach balloon panels not to the editor container but to the pages `body` element, you can check it using the inspector:

![screen shot 2018-08-06 at 17 05 58](https://user-images.githubusercontent.com/1166967/43724748-0f1492f8-999b-11e8-881e-30b63f395d2a.png)

Maybe you changed styles of the body element?

**Comment by oleq** [comment]
It looks to me like some problem with styles but I can't put my finger on it. I'm afraid without the live snippet, we won't be able to reproduce and address the issue. Some jsFiddle/CodePen, @rafalolszewski94?

**Comment by rafalolszewski94** [comment]
I think it was somehow connected to the configuration / or even browser cache, we've got it running smooth with styles a for a while now. Thank you for your contribution to this anyway 👍

**Comment by Reinmar** [comment]
Thanks for letting us know!
