### ISSUE TITLE
[Safari] Typing with check spelling option causes JavaScript error being thrown

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11949]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html in Safari on Mac
2. Make sure that browser has "Check Spelling while Typing" enabled
<img width="514" alt="Screenshot 2022-06-22 at 15 21 29" src="https://user-images.githubusercontent.com/5314687/175039701-cb3a5acc-971d-459b-924d-9b9ce782bb8b.png">
3. Start typing fast + try appying bold and italic. Please also see attached screen-cast:
[ckeditor_data_loss_issue_on_ckeditorsite.mov.zip](https://github.com/ckeditor/ckeditor5/files/8958025/ckeditor_data_loss_issue_on_ckeditorsite.mov.zip)

### ✔️ Expected result

No error gets thrown.

### ❌ Actual result

JavaScript error gets thrown and editor stops working.
<img width="1323" alt="Screenshot 2022-06-22 at 15 21 42" src="https://user-images.githubusercontent.com/5314687/175040227-096dfa1d-fab5-4ea2-9d93-a13af695e608.png">

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Safari
* OS: MacOs
* First affected CKEditor version: N/A
* Installed CKEditor plugins: typing

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Fixed.
