### ISSUE TITLE
need to know is any changes are happened in CKeditor or not

### ISSUE THREAD

**Issue by Jayasurya260528** [ckeditor/ckeditor5#11958]
I need to check, Is there any changes are made by user in editor(like type, even space also)

**Comment by jswiderski** [comment]
CKEditor Github is not a place for seeking advice. This is a place for reporting bugs and new feature requests. 

Please also refer to our documentation which covers many basic cases, including this one - https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/basic-api.html#listening-to-changes
