### ISSUE TITLE
Tour balloon for Highlight missing - target DOM node does not exist

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#11956]
## 📝 Provide detailed reproduction steps (if any)

1.  Open Highlight feature docs http://fake.cksource.com:8080/ckeditor5/latest/features/highlight.html

### ✔️ Expected result

No warnings in the console, tour balloon in place:  
![](https://user-images.githubusercontent.com/95343030/175324383-ec095b07-a1e4-4beb-8332-f671efc772f2.png)

### ❌ Actual result

Missing tour balloon:

![](https://user-images.githubusercontent.com/95343030/175324617-048612c2-789a-4fdb-9536-33800efd9f46.png)

warning in the console:

```
[Warning] [attachTourBalloon] The target DOM node for the feature tour balloon does not exist. – {text: "Click to add highlight."} (assets.js, line 4)
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: all
*   OS: …
*   First affected CKEditor version: current
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
Fixed by #11986. Closing.
