### ISSUE TITLE
SetData() removes empty P tags 

### ISSUE THREAD

**Issue by mariselvanm** [ckeditor/ckeditor5#1195]
🐞 Bug report

## 💻  CKEditor 4.6.1

1.CKEDITOR.instances['editor1'].setData(`<p><br></p>`);

## 📃 I'm trying to insert empty para inside the CKEditor.But after the methode complition it removes the empty P tag from the document.I already ask this question in [Stackoverflow](https://stackoverflow.com/questions/51684527/ckeditor-automatically-remove-empty-p-tag?noredirect=1#comment90331289_51684527)

**Comment by pjasiun** [comment]
This is CKEditor 5 repository. Issues related to CKEditor 4 should be reported to https://github.com/ckeditor/ckeditor-dev/issues.
