### ISSUE TITLE
The caret moves to a different block when pressing a space after a word with a grammar error (WSC)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11951]
## 📝 Provide detailed reproduction steps (if any)

0. Open full-featured-editor.html.
1. Type regular text
2. Change the format, for instance select text language or color.
3. Type "something in french" (should be **F**rench).
4. Press Space.

### ✔️ Expected result

Well, anything but a random selection change. Preferably a space after the word.

### ❌ Actual result

The selection moves to a weird position in the next block.
![2022-06-23 12 57 29](https://user-images.githubusercontent.com/1099479/175285044-4be56335-a029-4b9d-a858-8eeafbde5866.gif)

![2022-06-23 13 01 11](https://user-images.githubusercontent.com/1099479/175284986-596bd835-a6d4-4eea-92c5-fd51cc2aca0c.gif)

### ❓ Possible solution

This has something to do in WSC. I checked the [past version](https://ckeditor5.github.io/docs/nightly/ckeditor5/34.0.0/examples/builds-custom/full-featured-editor.html) of the editor on gh.io and WSC didn't load there and the bug was not reproducable.

## 📃 Other details

* Browser: Chrome
* OS: Mac
* First affected CKEditor version: ?
* Installed CKEditor plugins: Full featured editor sample

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by AAbakumov** [comment]
@oleq We have reproduced this issue or our end and released the fix yesterday. Could you please recheck the issue and confirm if it looks good on your end also?

Regards,

**Comment by Reinmar** [comment]
Thanks @AAbakumov!

cc @ckeditor/qa-team could you retest it?

**Comment by dufipl** [comment]
@Reinmar I can't reproduce the issue anymore on our docs, so it looks like working now 👍
