### ISSUE TITLE
Docs issue report from "api/module_image_imagecaption_imagecaptionediting.html"

### ISSUE THREAD

**Issue by thisismeonmounteverest** [ckeditor/ckeditor5#11950]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_imagecaptionediting.html

### Project version

34.1.0

### Is there something missing in the guide? What is it?

This is the whole text on the ImageCaptionEditing page:

(https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_imagecaptionediting-ImageCaptionEditing.html)
The image caption engine plugin. It is responsible for:

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by dufipl** [comment]
Hello @thisismeonmounteverest,

Thank you for reporting the issue. I can confirm it's reproducing and we might handle it internally in future. An update will be written in this report in case it is fixed, however, no specific dates for that can be provided at the moment.

**Comment by dufipl** [comment]
Hello @thisismeonmounteverest, we've decided that the description will be available only here: https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_imagecaptionediting-ImageCaptionEditing.html, change has been already deployed.
Closing as fixed, but if you have any additional questions, do not hesitate to ask.
