### ISSUE TITLE
Image upload error - image disappears when moved

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#11953]
## 📝 Provide detailed reproduction steps (if any)

1.  Enter the demo in image upload overview: https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/image-upload.html
2.  Upload a large image
3.  Drag the image immediately to move around

### ✔️ Expected result

The image is relocated

### ❌ Actual result

The image disappears

![image](https://user-images.githubusercontent.com/68123541/175490457-6e28a284-a2b3-4ce3-8c58-d38d6f04675f.png)

### ❓ Possible solution

Most probably this happens because the image is not yet fully uploaded. This may happen if the upload is slow due to user connection speed and the size of the file.

## 📃 Other details

*   Browser: Latest Firefox
*   OS: MacOS
*   First affected CKEditor version: tested on 34.1.0
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
If the image is not yet uploaded before moving it, is this issue even valid?

**Comment by godai78** [comment]
Probably not, but I believe we need into look at it at some point just in case.

**Comment by godai78** [comment]
After a further check, this is most probably just a loading delay effect.
