### ISSUE TITLE
Image insert bug

### ISSUE THREAD

**Issue by bukaOK** [ckeditor/ckeditor5#1196]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor 
11.0.1
example maked in ckeditor-5 demo page

## 📋 Steps to reproduce

1. Paste image
2. Choose image side 
3. Type something
4. Delete typed

## ❎ Actual result
![ck_bug](https://user-images.githubusercontent.com/20228182/43894854-1dcded6a-9bdc-11e8-976b-a112b8b0fe65.gif)

## 📃 Other details that might be useful

**Comment by Mgsy** [comment]
Hi, @bukaOK. It looks like a bug which we know and it occurs only in Firefox. Could you confirm that you're using Firefox? Are you able to reproduce it in other browsers?

**Comment by bukaOK** [comment]
@Mgsy in chrome all works fine, thanks.
