### ISSUE TITLE
List attributes are moved to list items

### ISSUE THREAD

**Issue by webdev51** [ckeditor/ckeditor5#11970]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html
2. In the 1st editor, empty it and switch to **Source** formatting
3. In the source box, insert below valid HTML
```
<h2>Table of Contents</h2>
<ul class="toc-parent-list">
    <li><a href="#heading-1">This is an h2 heading</a>
        <ul class="toc-inner-list">
            <li><a href="#heading-2">H3 Heading</a></li>
            <li><a href="#heading-3">H3 Heading 2</a></li>
        </ul>
    </li>
    <li><a href="#heading-4">Some heading</a></li>
</ul>
```
4. Switch back to editor view so the html gets processed.
5. Now go back again to source view to see the HTML.

### ✔️ Expected result

The HTML should've been same as its valid HTML and `toc-parent-list` should've remained on the parent `ul` element

### ❌ Actual result

The HTML is processed to wrong markup. `toc-parent-list` class is applied to child `li` for no reason.

![image](https://user-images.githubusercontent.com/49054601/175885702-c3f8af5a-d3db-488d-aef1-9fd155561897.png)

## 📃 Other details

Browser: Chrome, Version 102.0.5005.63 (Official Build) (64-bit)
* OS: Windows 11, 64 Bit

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
You can try out the new [`DocumentList`](https://ckeditor.com/docs/ckeditor5/latest/api/module_list_documentlist-DocumentList.html) plugin. It's not yet documented as it's not yet compatible with some of the features, but it resolves the issue that you mentioned. And it's the plugin to replace the old List feature soon.

We're not planning to work on GHS support for the old List feature (and this issue is about this topic) so I'm closing this ticket.

**Comment by qipengwei** [comment]
> 您可以试用新[`DocumentList`](https://ckeditor.com/docs/ckeditor5/latest/api/module_list_documentlist-DocumentList.html)插件。由于它尚未与某些功能兼容，因此尚未记录，但它解决了您提到的问题。而且它很快就会取代旧的 List 功能。
> 
> 我们不打算为旧列表功能提供 GHS 支持（并且这个问题与此主题有关），因此我将关闭此票。
How can it be used, as a stand-alone plugin for command introduction?
For example:
 **npm i List
 import list@ckeditor List** 
 Is that right
