### ISSUE TITLE
Column resize interoperability

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#11975]
How can we retain width for tables that have `td[style=width:x]` (Paste from Word, CKEditor 4 paste)?

We need to handle a case where user will paste table from e.g. [https://ckeditor.com/docs/ckeditor4/latest/examples/table.html](https://ckeditor.com/docs/ckeditor4/latest/examples/table.html) example and will attempt to resize it.

1.  Pasted table should retain column width (this requires table cell property plugin to be loaded).
2.  User should be able to further resize any column (any column width must not be reset when doing this).

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
👆 if you select it using elements path in CKEditor 4 then it works 😄 but you're right it might be tricky due to #11878. That being said fix proposed for #11858 should also fix this issue 👍

**Comment by Dumluregn** [comment]
Done in #11914.
