### ISSUE TITLE
Docs issue report from "api/module_source-editing_utils_formathtml.html"

### ISSUE THREAD

**Issue by asifPhp** [ckeditor/ckeditor5#11987]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_source-editing_utils_formathtml.html

### Project version

34.1.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by Mgsy** [comment]
Hi! Could you share some description of your issue?

**Comment by godai78** [comment]
Can't reproduce, no follow-up from poster.
