### ISSUE TITLE
Review entries in `.gitignore`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#11985]
## Provide a description of the task

See https://github.com/ckeditor/ckeditor5/pull/11884#issuecomment-1169712461.

We could redefine entries specified in the `.gitignore` file to avoid such PRs in the future. It is not the first time and not the last one if we do nothing.

Let's define specific rules that can be shared across CKEditor 5 repositories. Then, add rules dedicated for a particular repository.

```.gitignore
# Rules for CKEditor 5 repositories.
# Ignore all dot directories.
.*/
!.github/
# ... and more.

# Rules for CKEditor 5 repository.
yarn.lock
mrgit.json
# ... and more.
```

When preparing a PR, make sure to target it to the `#stable` branch.

**Comment by przemyslaw-zan** [comment]
Some historical discussion on the topic -> https://github.com/ckeditor/ckeditor5/issues/4074
