### ISSUE TITLE
How can I configure toolbar's size?

### ISSUE THREAD

**Issue by Luberen** [ckeditor/ckeditor5#1198]
## 💻 Version of CKEditor - v11.0.1

![ck5](https://user-images.githubusercontent.com/26616056/43934083-6d5b0bd6-9c88-11e8-8582-df1e6db10ce4.png)
```
<style>
  .ck-editor__editable {
    width: 700px;
    min-height: 400px;
  }
</style>
```
I've configured editor's size, but toolbar's width isn't changed.
How can I set the with of toolbar and editor same?

**Comment by jodator** [comment]
@Luberen You should style the top-most container of the editor, like:

```css
.ck.ck-editor {
    max-width: 700px
}
```

See below (I've set `500px` there):

![selection_036](https://user-images.githubusercontent.com/247363/43945954-1bfe9bd0-9c84-11e8-8899-d71b9eae8cd2.png)

**Comment by jodator** [comment]
To avoid confusion I've added [an answer about controlling width](https://stackoverflow.com/a/51781929/2273046) to the @wwalc's question about configuring height of the editor.

**Comment by jodator** [comment]
@Luberen you should be able to set `min-height` on the `.ck-editor__editable` as in [the SO answer](https://stackoverflow.com/a/46559355/2273046). As you control height/width of the editor with CSS the proper selectors for configuring would be:

- `ck.ck-editor` for `width` (whole toolbar + editing area)
- `.ck-editor__editable` - for `height` (it will set the height of the editing area so it will not mess with toolbar's height)
