### ISSUE TITLE
Accessibility fixes batch 1

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#11981]
This is an epic to list of accessibility issues that we'd like to solve first.

The parent ticket covering the entire topic: #11712.

## ToC

*   Focus in dropdowns:
    *   #11838 
    *   #2000
    *   #11568 
    *   #3215
    *   #5859 
    *   #1037 
*   Grids:
    *   #3184 (DUP of the other ones)
    *   #11851 
    *   #3176 
    *   #11041
*   Focusing toolbars:
    *   #10368 
    *   #5146
*   Colors:
    *   #11989
    *   #1405
*   Misc:
    *   #5581 
    *   #12067 
    *   #2045
    *   #12258

**Comment by Reinmar** [comment]
All the issues from this Epic except ckeditor/ckeditor5#2045 which is blocked by ckeditor/ckeditor5#11438 were resolved so I'm closing it.
