### ISSUE TITLE
ckeditor-duplicated-modules error appears when SourceEditing plugin added

### ISSUE THREAD

**Issue by Lilia0000** [ckeditor/ckeditor5#11983]
## 📝 Provide detailed reproduction steps (if any)

1. Create online editor build with only SourceEditing included  
```
/**
 * @license Copyright (c) 2014-2022, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting.js';

class Editor extends ClassicEditor {}

// Plugins to include in the build.
Editor.builtinPlugins = [Essentials, Paragraph, SourceEditing];

// Editor configuration.
Editor.defaultConfig = {
	toolbar: {
		items: ['undo', 'redo', '|', 'sourceEditing'],
	},
	language: 'en',
};

export default Editor;
```
2. Install as npm package to angular project
```
"dependencies": {
    "ckeditor5-custom-build": "file:client/ckeditor5",
}
```
4. Add to angular project according to [documentation ](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/angular.html)
```
import * as ClassicEditor from 'ckeditor5-custom-build/build/ckeditor';
```

### ✔️ Expected result

Working and ready to use

### ❌ Actual result

![image](https://user-images.githubusercontent.com/54148921/176387299-5a91607a-5d92-4ae7-bf25-fbbff83d645d.png)

## 📃 Other details

* Browser: Goggle Chrome 102.0.5005.115
* OS: Windows 10
* First affected CKEditor version: 34.0.0
* Installed CKEditor plugins: 34.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Are all your CKE5 deps in exactly the same version?

Make sure to clean package/yarn lock, remove node\_modules and make a clean installation. In 99% cases it helps.

**Comment by Lilia0000** [comment]
> Are all your CKE5 deps in exactly the same version?
> 
> Make sure to clean package/yarn lock, remove node_modules and make a clean installation. In 99% cases it helps.

You're right! SourceEditing version was 34.1.0. Update all plugin versions to 34.1.0 solves the problem. Thanks.
