### ISSUE TITLE
How to link URL images extracted from Google Drive in ckeditor5

### ISSUE THREAD

**Issue by iyagicom** [ckeditor/ckeditor5#1199]
## Is this a bug report or feature request? (choose one)

Feature request

## 💻 Version of CKEditor

/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js

## 📋 Steps to reproduce

I extracted the Google Drive image address with a URL extraction program.

I want to import the url address from CKEditor 5.
not the local image upload.
I need to be able to enter the Url address when the insert image button is pressed.

I want to see the image in the textarea.

**Comment by Reinmar** [comment]
Hi! This is a DUP of https://github.com/ckeditor/ckeditor5-image/issues/229.
