### ISSUE TITLE
Text with images pasted from Word 2016 doesn't preserve images.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#11993]
## 📝 Provide detailed reproduction steps (if any)

1. Got to https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html
2. Extract attached file press Ctrl+A, Ctrl+C and paste its content into editor. 
3. You can also select some text with an image. It doesn't have to be the whole document
[copy_paste_image_+_text.docx.zip](https://github.com/ckeditor/ckeditor5/files/9018075/copy_paste_image_%2B_text.docx.zip)

### ✔️ Expected result

Image with text gets pasted.

### ❌ Actual result

Only text gets pasted.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

From what we have checked, this MS Word file has been created with MS Word 2016 - https://superuser.com/a/1144401

* Browser: Any
* OS: Any
* First affected CKEditor version: N/A
* Installed CKEditor plugins: paste-from-office

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Is it a regression?

Is there a workaround (e.g. converting to a different format)?

Is it perhaps related to #2493 and #11921?

**Comment by Reinmar** [comment]
Is it a regression?

Is there a workaround (e.g. converting to a different format)?

Is it perhaps related to #2493 and #11921?

**Comment by jswiderski** [comment]
> Is it a regression?

I don't see it as a regression. THis is rather specific to this document of that type of documents. I based that on client comments:

> Don’t see a issue if we create new document.
> ...
>Even if I copy paste contents from old word file to new one – Don’t see a issue.  But Save As old documents to new doesn’t help.

--
> Is there a workaround (e.g. converting to a different format)?

According to the client "Even if I copy paste contents from old word file to new one – Don’t see a issue" but this is a weak workaround as not everyone has multiple MS word versions and the online one is not yet supported.

--
> Is it perhaps related to https://github.com/ckeditor/ckeditor5/issues/2493 and https://github.com/ckeditor/ckeditor5/issues/11921?

It can be related to https://github.com/ckeditor/ckeditor5/issues/2493 because from what we have checked, this file has been created with MS Word 2016.

**Comment by arkflpc** [comment]
This is the content of the pasted clipboard from attached document: [old.txt](https://github.com/ckeditor/ckeditor5/files/9046625/old.txt)  
This is the one after pasting it to empty document and copying it again: [new.txt](https://github.com/ckeditor/ckeditor5/files/9046626/new.txt)

The new one encodes images as:

```html
<!--[if gte vml 1]>... <v:shape ...><v:imagedata src="file:///Path.jpg" /></v:shape><![endif]-->
<![if !vml]><img src="file:///Path.jpg"><![endif]>
```

`v:shape` is ignored during processing, and what the `paste-from-office` plugin actually supports is `<img>`

The old format is just:

```html
<v:shape ...><v:imagedata src="file:///Path.jpg" /></v:shape>
```

**Comment by nileshawtade** [comment]
@mdabkowska88 - Any update on this ?

**Comment by Reinmar** [comment]
*   The support for these images (`v:imagedata`) will need to land probably in [https://github.com/ckeditor/ckeditor5/blob/d40dbad5f599c736e741466dd67d7c9d20656c00/packages/ckeditor5-paste-from-office/src/filters/image.js#L21-L22.](https://github.com/ckeditor/ckeditor5/blob/d40dbad5f599c736e741466dd67d7c9d20656c00/packages/ckeditor5-paste-from-office/src/filters/image.js#L21-L22.)
*   The ultimate goal is to replace an entire `<v:shape>` with `<img>`.
*   There's a slight risk that some images will get duplicated after doing the above. In the payloads mentioned by @arkflpc, the duped images are marked with a `<!--[if gte vml 1]>` but no one can predict what mess would Word produce in other cases.
*   We're unsure whether we'll not run into issues with identifying which DOM node representing an image is represented by which image in the RTF format (from which we extract image data).
