### ISSUE TITLE
Builder configuration

### ISSUE THREAD

**Issue by gregpabian** [ckeditor/ckeditor5#12]
This topic reminds me why I wanted to reuse some of the existing grunt tasks for the build process instead of writing the builder task on our own... Right now there's no way to configure the build process from the Gruntfile. The only way to change anything (e.g. disable uglify during r.js optimization, change the output path etc.) is to play with the builder's source code.

**Comment by Reinmar** [comment]
After we migrated to gulp this issue doesn't make much sense.
