### ISSUE TITLE
how to insert non-editable text

### ISSUE THREAD

**Issue by ArtemNyanchenkov** [ckeditor/ckeditor5#12004]
Hi, in my project on Vue 3, I am trying to insert a non-editable variable, this is necessary so that after inserting the variable, the user cannot edit it because in the future I use find and replace the function.
Tell me how to insert a non-editable variable. Thanks!

`

> addCodeInMsg(name, id) {
>       this.variables.push({pres: name, guid: id})
>       for (let item of this.variables) {
>         if (item.guid === id) {
>           let content = `<span contenteditable="false" style="color: red; user-select: none">${item.pres}</span>  `;
>           let viewFragment = this.editor.data.htmlProcessor.toView(content, {isReadOnly: true});
>           console.log(viewFragment);
>           let modelFragment = this.editor.data.toModel(viewFragment);
>           this.editor.model.insertContent(modelFragment)
> 
>         }
>       }
>     }`

> `createDoc() {
>        for (let itm of this.passport.childs) {
>         for (let cas of this.variables) {
>           if (itm.id === cas.guid) {
>             let edata = this.editor.getData();
>             let replaced_text = edata.replace(cas.pres, itm.value); 
>             this.editor.setData(replaced_text);
>           }
>         }
>       }
>     }`

**Comment by jswiderski** [comment]
CKEditor Github is not a palce for seeking technical support but a place for reporting bugs and features. 

Having said that, please have a look at the widgets tutorials which do exactly what you want and are the only way to have non-editable parts inside editable area - https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html
