### ISSUE TITLE
merge-operation-how-many-invalid when undo insertContent()

### ISSUE THREAD

**Issue by renderpci** [ckeditor/ckeditor5#12001]
## 📝 Provide detailed reproduction steps (if any)

1. convert the html img string in model

```
const html = '<img id="[note-a-1-6]" class="note" data-type="note" data-tag_id="1" data-state="a" data-label="1" src="../tag/note-a-1-6.jpg">'
const view_fragment = editor.data.processor.toView( html );
const model_fragment = editor.data.toModel( view_fragment );
```

2. insert the img at end position of the user selection

```
const position = editor.model.document.selection.getLastPosition()
editor.model.insertContent( model_fragment, position );
```

3. Redo the process creating a second html img node and insert in the same way that step 1 and 2

```
const html = '<img id="[note-a-2-6]" class="note" data-type="note" data-tag_id="2" data-state="a" data-label="2" src="../tag/note-a-2-6.jpg">'
const view_fragment = editor.data.processor.toView( html );
const model_fragment = editor.data.toModel( view_fragment );
const position = editor.model.document.selection.getLastPosition()
editor.model.insertContent( model_fragment, position );
```

6. Undo to remove the second img node. It done ok, the first undo work properly.
7.  Undo again to remove the first img node, error arise and block the editor to do any other task

### ✔️ Expected result

Undo the insertContent of the first img node 

### ❌ Actual result

```
mergeoperation.js:161 Uncaught CKEditorError: merge-operation-how-many-invalid
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-merge-operation-how-many-invalid
    at Bl._validate (mergeoperation.js:161:10)
    at on.priority (model.js:92:14)
    at vd.fire (emittermixin.js:200:30)
    at <computed> [as applyOperation] (observablemixin.js:262:16)
    at og._undo (basecommand.js:197:11)
    at Object.callback (undocommand.js:41:9)
    at vd._runPendingChanges (model.js:952:58)
    at vd.enqueueChange (model.js:271:10)
    at og.execute (undocommand.js:40:21)
    at og.<anonymous> (observablemixin.js:258:32)
_validate @ mergeoperation.js:161
on.priority @ model.js:92
fire @ emittermixin.js:200
<computed> @ observablemixin.js:262
_undo @ basecommand.js:197
(anonymous) @ undocommand.js:41
_runPendingChanges @ model.js:952
enqueueChange @ model.js:271
execute @ undocommand.js:40
(anonymous) @ observablemixin.js:258
fire @ emittermixin.js:200
<computed> @ observablemixin.js:262
execute @ commandcollection.js:69
execute @ editor.js:415
(anonymous) @ service_ckeditor.js:754
```

## 📃 Other details

* Browser: Chrome  103.0.5060.53 (Official Build) (x86_64),  Safari  15.5 (17613.2.7.1.8)
* OS: macOs 12.4
* First affected CKEditor version: 34.1.0
* Installed CKEditor plugins:
BoldEditing,
	Essentials,
	FindAndReplace,
	GeneralHtmlSupport,
	Image,
	ImageStyle,
	ItalicEditing,
	Link,
	LinkImage,
	Paragraph,
	PasteFromOffice,
	SourceEditing,
	TextPartLanguage,
	UnderlineEditing,
	WordCount,
	PendingActions,

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thanks @renderpci. One question from me - what do you mean in step 3 by "Redo the process"? Just to be sure - you mean "Repeat the steps 1 and 2 to insert a second image"? Not like the undo's "redo"?

cc @niegowski, do you want a brain teaser? :D

**Comment by renderpci** [comment]
Thanks @Reinmar.

The answer: Repeat the process 1 and 2.
(sorry for the confusion I used Redo and it's confusing... Repeat it's better....)

Overview the process:
- Insert image 1
- Insert image 2
- Undo the insert of the second image <--- correct
- Undo the insert of the first image <--- error appear

Best

**Comment by Reinmar** [comment]
I tried this case again on 35.0.1 and the editor didn't crash this time. Could you retest it?

**Comment by renderpci** [comment]
Hi Reinmar.

Yes, it's working perfectly on 35.0.1!

Thanks for the work.
Best
