### ISSUE TITLE
url validation

### ISSUE THREAD

**Issue by rakeshgujjar** [ckeditor/ckeditor5#12002]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/images-inserting.html

### Project version

34.2.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**Comment by FilipTokarski** [comment]
Hi, could you add information on what actually the problem is?
