### ISSUE TITLE
Angular - module parse failed

### ISSUE THREAD

**Issue by R2-D1** [ckeditor/ckeditor5#12019]
## 📝 Provide detailed reproduction steps (if any)

1. Install @ckeditor/ckeditor5-angular, @ckeditor/ckeditor5-build-classic, @ckeditor/ckeditor5-source-editing
2. Init ckeditor with source-editing plugin

### ✔️ Expected result

editor builds without problems

### ❌ Actual result

Application is down

### Details
My .ts file
```
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import * as SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting';

 editor: any;

 ClassicEditor.builtinPlugins = [SourceEditing];
    ClassicEditor.defaultConfig = {
      toolbar: {
        items: ['undo', 'redo', '|', 'sourceEditing'],
      },
      language: 'en',
    };

    this.editor = ClassicEditor;
```

My .html file
`<ckeditor [editor]="editor" data="<p>Hello, world!</p>"></ckeditor>`

Console after build
<img width="1568" alt="Screenshot 2022-07-06 at 09 26 10" src="https://user-images.githubusercontent.com/46542768/177483239-ea88fec1-a7bc-47f9-a5fd-b515c341bee1.png">

## Important
If I remove SourceEditing plugin - everything work fine

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. There are two issues here. First, it's not possible to just add a plugin to the editor build, as it will result in [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules). Second, it's not possible to customise the editor within the Angular app. In such case, you first need to create a custom editor and then add it as a dependency your app. The easiest way to achieve this is to create an editor with online builder - please [see the docs](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/angular.html#integrating-a-build-from-the-online-builder) for the detailed instructions.
