### ISSUE TITLE
Example ClassicEditor Configuration incorrect

### ISSUE THREAD

**Issue by sillyfrog** [ckeditor/ckeditor5#1201]
🐞 Bug report

## 💻 Version of CKEditor

5, stock example.

## 📋 Steps to reproduce

Following the quick start documentation with, then adding in the example Configuration from https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html , you get an error:
```
TypeError: "t.model is undefined"
```

## ✅ Expected result
No error, a custom menu

## ❎ Actual result
The error above.

## 📃 Other details that might be useful
I found replacing `modelElement` with `model` and `viewElement` with`view` made it work. eg:
```
--- before.html	2018-08-11 12:25:22.000000000 +1000
+++ working.html	2018-08-11 12:26:40.000000000 +1000
@@ -17,9 +17,9 @@
         toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote' ],
         heading: {
             options: [
-                { modelElement: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
-                { modelElement: 'heading1', viewElement: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
-                { modelElement: 'heading2', viewElement: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' }
+                { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
+                { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
+                { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' }
             ]
         }
     } )
```

So all I think needs to happen is the documentation be updated to match at https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html

The sample files for the diff are in the attached [Archive.zip](https://github.com/ckeditor/ckeditor5/files/2279848/Archive.zip)

**Comment by jodator** [comment]
Fixed by: 69c47c33d9f69f60eb340dd93bf759d4eed33c5a.
