### ISSUE TITLE
Add inspector bookmarklet code to the development tools/inspector section

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#12032]
## 📝 Provide a description of requested docs changes

ATM [the section](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/development-tools.html#ckeditor-5-inspector) only contains information inspector imported from npm or using `<script>`. There's another option: a bookmarklet that we use every day in the team that allows running inspector on any webpage without modifying its source.

```js
javascript:(function(){let script=document.createElement('script');script.src='https://unpkg.com/@ckeditor/ckeditor5-inspector/build/inspector.js';script.onload=()=>CKEditorInspector.attachToAll();document.head.appendChild(script);})()
```

**Comment by Reinmar** [comment]
The bookmarklet fails if CSP is set. I wonder how many projects have it set - it may happen that too many for the bookmarklet to be useful. 

That doesn't mean we shouldn't document it. But perhaps some more info is necessary.

**Comment by mlewand** [comment]
Big +1 for this - many external developers that I'm talking with are very happy with this trick.
