### ISSUE TITLE
why can't I add the image.

### ISSUE THREAD

**Issue by pheaktra002** [ckeditor/ckeditor5#12035]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

### Project version

34.2.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**Comment by godai78** [comment]
Can you provide more details? Adding images works fine in the demo. We would need more data to assess the problem.

**Comment by godai78** [comment]
Can't recreate the issue; gone stale.
