### ISSUE TITLE
Java 11 Compatibility check: ckeditor

### ISSUE THREAD

**Issue by KryniuPL** [ckeditor/ckeditor5#1204]
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 💻 Version of CKEditor

5

## 📋 Steps to reproduce

Hi,
We are reaching out to you to check Java 11 compatibility of the library ckeditor.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

**Comment by Reinmar** [comment]
CKEditor 5 is a JavaScript library. We can talk about browser compatibility here, not about Java compatibility. In other words, if your Java application is able to serve a website, then CKEditor 5 is compatible with it.
