### ISSUE TITLE
Paste from Word should preserve or inline user defined styles

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#12042]
## 📝 Provide a description of the new feature

_What is the expected behaviour of the proposed feature?_

When user pastes contents from MS Word with his custom defined styles, our filter could for example inline them. 

This is related to https://github.com/ckeditor/ckeditor5/issues/10577 and https://github.com/ckeditor/ckeditor5/issues/9879

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is a DUP of those tickets.
