### ISSUE TITLE
Create editor state viewer (model, view, schema, commands, etc)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1205]
Intro: we made some work on this in the past but it wasn't ever designed with UX in mind. It was more of an internal tool and went too far into the "show model tree + selection" direction. See the previous ticket: https://github.com/ckeditor/ckeditor5-engine/issues/170

## Why it's needed?

CKEditor 5's model and views are abstract structures which people are not familiar with. Especially the model is tricky to grasp because its structure is different than that of the HTML (DOM). We often see developers trying to write plugins without understanding what's the structure of the model, what elements are there and how they relate to what they see in the DOM. That must be frustrating and confusing for them because it's like writing plugins for a black box. We must change this.

## Plug and play

This tool should be super easy to use with any editor running on any page, JSFiddle, etc. It must be easy to plug without building anything and without changing anything in an editor. What's more, it should not only be easy to initialize, but it should also automatically render itself on the page.

Naturally, this tool will be useful for us too but it's our first goal to enable it for other developers. Therefore, I think that it should be available via our CDN. So, e.g. when you work on something on JSFiddle or in your app you need to:

1. Add `<script src="https://cdn.ckeditor.com/ckeditor5/[version.number]/viewer/ckeditor.js">`
2. Run `CKViewer.start( editor )`

And that's it. It should appear on the page and should be fully functional, styled, etc.

## Implementation details

* It needs to be versioned together with the editor so developers are always able to use a version compatible with the build/editor they use. That's why I proposed exactly the same CDN URL format as to builds. In some sense, this will be a build, just not an editor build.
* There are more similarities to builds. It will also require to be rebuild before publishing (it can be available via npm too). However, unlike builds, it must have **zero dependencies** to CKEditor 5. Since it must work with any editor, it must work based solely on the public API.
* I think that we may or even should use React or Vue plus perhaps CSS libs to build it because it may be more encouraging to further extend it. Also, the whole thing needs to be build to a singe JS file, so at least webpack is highly justified. This all means that it becomes a project itself, but I'd keep it within our dev env so the tool is also always available to us too. That, in turn, means that it should be build and committed with every (significant) commit, so you don't have to do anything to use it (except importing it).
* During releasing we'll have to remember that it must follow the version of `ckeditor5`. That, most likely, it's easiest to do manually.
* It should be build to an UMD format.

## Features

MVP:

* Automatically render on an existing page without affecting its layout. IDK which viewport side to choose initially – perhaps bottom cause then there's the biggest chance that you'll be able to scroll the page to see the editor which you want to investigate.
* You must be able to hide the viewer (cause it's going to cover at least 50% of the page).
* It may be worth to check whether there's a tool for showing a dockable element, with resizing, hiding, viewport side choice features. That would help a lot if we didn't have to reinvent the wheel.
* I imagine the UI build around tabs. Just like in the browser's dev tools.
* The bare minimum of tabs:
   * Model tree viewer. Static, no folding, no selection, nothing. Just elements, text nodes and their attributes.
   * Editing view tree viewer. The same basic form as in the model tree viewer.
   * Data view tree viewer. The same as above. (Note: this tree is not live, so perhaps a "refresh" button would be needed or a change-based automatic refreshing).

Next steps:

* Allow controlling the viewer's size and position (docking).
* Initially, you'll be able to show just one tab at a time, but I think that in the future it would be useful if you'd be able to see the model and the view at the same time. That might be achieved in multiple ways but perhaps it'd be easiest to allow splitting the view of the viewer into two columns where in both of them you'd have the same set of tabs to choose from. Then, you'd be able to choose the model tab in the first column and the view tab in the second column.
* More tabs and ideas:
   * Schema viewer.
   * Commands viewer – list of commands + their `is*` properties + "execute" buttons (not sure if doable cause command params).
   * Show the selection (and its attributes) in the model and editing views.
   * Blink in the right trees place when something changes.
   * Make trees foldable.
   * Add event viewer. E.g. a list of some most popular events that you can select using checkboxes and then they get automatically printed to the console. That could be useful for quickly tracking focus, etc.
   * Editor state viewer – list of most important editor props.
   * Something for conversion?
   * Display more info about offsets of nodes in the tree (e.g. after hovering them).

**Comment by pjasiun** [comment]
I like this idea very much. Some notes:
1. We may consider making it Chrome/Firefox Dev Tools extension

On the one hand, it might be harder: we need to learn how to do it, it might not be that simple to support both Chrome and FF at the same time and need two separate tools ([or not](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension)). Also, users would have to install the extension to use it.

On the other, we should at least do the research what benefits we can get. To name few potentials:
 - tabs and docking working out of the box,
 - better screen organization: if one enable both dev tools are the editor viewer there might be no space on the screen anymore,
 - debugging on the mobile system could be easier.

I am not telling that it is a good direction, but that we should consider it.

2. Other small notes:

I think that the file with the viewer should not be called  `ckeditor.js` since it might be misleading. I think something like this will be better:

```
<script src="https://cdn.ckeditor.com/ckeditor5/[version.number]/ckeditor-viewer.js">
```

**Comment by ma2ciek** [comment]
> We may consider making it Chrome/Firefox Dev Tools extension

I was just writing the same. There're few existing extensions for frameworks/libraries, which improve the DX, e.g.:

* https://chrome.google.com/webstore/detail/augury/elgalmkoelokbchhkhacckoklkejnhcd
* https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
* https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd

**Comment by wwalc** [comment]
Maintaining browser extension may be more time consuming (releasing new versions, changes in browsers etc), so although that's a nice idea it may be worth estimating how much extra time it would cost us.

Also:

> It needs to be versioned together with the editor so developers are always able to use a version compatible with the build/editor they use. 

may be a bit problematic.

**Comment by pjasiun** [comment]
Yea. For sure we should not build a browser extension:
 1. because we can,
 2. because other do so.

We should check and calculate all the pros and cons and make our decisions based on them.

**Comment by ma2ciek** [comment]
> Yea. For sure we should not build a browser extension:
because we can,
because others do so.
We should check and calculate all the pros and cons and make our decisions based on them.

Sure, I just pointed out these examples to illustrate how these libs solve a simillar problem (i.a. visualizing the virtual DOM tree).

**Comment by Reinmar** [comment]
The first version of the inspector is out: https://github.com/ckeditor/ckeditor5-inspector. Let's move this ticket to its repo.
