### ISSUE TITLE
Toolbar button tooltips should also be visible for keyboard users – let's try again

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#12067]
We first introduced tooltips to focus buttons in https://github.com/ckeditor/ckeditor5/issues/5581. It seemed very simple.

However, in https://github.com/ckeditor/ckeditor5/issues/12066 we figured out that it introduces some annoying UX-glitches.

We decided to revert the original fix for #5581. And try again.

Steps:

1. Let's try to figure out a better, more sophisticated but feasible solution.
2. Let's implement it.
3. If the outcome of step 1. will be "it's damn tricky, we don't have enough time now", let's go with an original solution to #5581 but with some small improvements:
   * turning the alignment menu to horizontal
   * removing tooltips for buttons with visual text labels

**Comment by oleq** [comment]
FYI: A new implementation preview in #12262.
