### ISSUE TITLE
How can I upload Image?

### ISSUE THREAD

**Issue by Luberen** [ckeditor/ckeditor5#1206]
## Is this a bug report or feature request? (choose one)

Other: Question

## 💻 Version of CKEditor

11.0.1

-----

![imageupload](https://user-images.githubusercontent.com/26616056/44244157-7cfc8a80-a20d-11e8-83f6-ec52957e5c66.png)

Currently image uploading doesn't work. File browser is opened normally but selected image doesn't appear in the editor.
How can I upload images?

**Comment by Reinmar** [comment]
This question is covered in the [docs](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload.html) and on [SO](https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5).
