### ISSUE TITLE
Table border - for all the table cells at a time

### ISSUE THREAD

**Issue by ganeshkg** [ckeditor/ckeditor5#12075]
I have implemented a CKEditor in react and installed all the required plugins for table properties. I tried to add a border to the table by selecting table properties and adding the border.
This displays the outer border of the table, and if I want to show a border for the cells then I need to go to each cell and add the border manually. Can we do it in a single way? I mean if I add a table border, can it be for all the borders in the table? Any way to do that?

Thanks,
Ganesh.

**Comment by FilipTokarski** [comment]
You can select all the cells and then apply cell border.

**Comment by ganeshkg** [comment]
Oh okay, got it. Thanks for the workaround @FilipTokarski!
