### ISSUE TITLE
how do you add radio,checboxes, textarea, selects to the toolbar?

### ISSUE THREAD

**Issue by stccorp** [ckeditor/ckeditor5#1208]
Using CKEditor5,

Cant seem to find how to add the html standard input to the editor radio,checboxes, textarea, selects,text

Thank you

**Comment by Reinmar** [comment]
cc @oleq & @oskarwrobel

**Comment by stccorp** [comment]
I was able to do it using ck4

https://ckeditor.com/cke4/builder

**Comment by Reinmar** [comment]
Now I don't understand what you want to do. I thought you want to write CKEditor 5 plugins which add some other things to the toolbar than simple buttons or split buttons. After your last comment I don't think that this is it.

Could you explain what you want to achieve?

**Comment by stccorp** [comment]
Thats what I was looking for. But since I didnt find it, I found that nice builder for ck4( there is no ck5 builder as far as I know), So using the ck4 builder I got what I wanted , which was the editor with form elements. using the form plug in

**Comment by Reinmar** [comment]
Oh, I understand now. So you wanted the form plugin (ability to insert inputs/radio/buttons/etc into the content). It does not exist for CKEditor 5 and it's very low chance that we'll implement it. If you need it, CKEditor 4 is the way to go.

I'll close this ticket due to low chance that we'll ever work on this.

**Comment by oskarwrobel** [comment]
Each [View](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/view.js) instance with a focusable interface ([we are going to define such one](https://github.com/ckeditor/ckeditor5-ui/issues/256)) should work as a toolbar item.

To add a view to the toolbar you need to: 
1. Add it to the [ComponentFactory](https://github.com/ckeditor/ckeditor5-ui/blob/5f77883840c25b9fdf0f3ac05a56eff9581ecff8/src/componentfactory.js#L70-L93). [See](https://github.com/ckeditor/ckeditor5-link/blob/7a5503b1eb31f3afedf3a4076ceb7190bb4680d6/src/linkui.js#L179-L195).
2. Add this component to the toolbar through [Editor config](https://github.com/ckeditor/ckeditor5-core/blob/09da4d727508d8c36edac987f89b4d95115664a6/src/editor/editorconfig.jsdoc#L17).
