### ISSUE TITLE
Add docs landing pages as overview guide

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#12081]
Include documentation sections landing pages as "Overview" guides in the left TOC tree.

**Comment by godai78** [comment]
Noticed error: the quiz tends to hang after a negative reply.

**Comment by Mgsy** [comment]
Done.

**Comment by godai78** [comment]
The selected way to redirect the \`index\` pages turned out to be causing problems. Rewriting the redirect scheme and changing links to overviews instead globally.

**Comment by godai78** [comment]
Follow-up: relink the main docs landing page to overviews.

**Comment by godai78** [comment]
All merged.
