### ISSUE TITLE
Docs issue report from "installation/getting-started/frameworks/angular.html"

### ISSUE THREAD

**Issue by Musadiq114** [ckeditor/ckeditor5#12092]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/angular.html

### Project version

34.2.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62

**Comment by godai78** [comment]
No reproducible, no follow-up, closing as stale.
