### ISSUE TITLE
Example too little, document could not be understood

### ISSUE THREAD

**Issue by 8427003** [ckeditor/ckeditor5#1209]
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 💻 Version of CKEditor

5

## ✅ Expected result
Example too little , document could not be understood

**Comment by AnnaTomanek** [comment]
Hi,

Thank you for your report. However, could you please be more specific about the examples that you are missing?

CKEditor 5 documentation is still in progress, however, you can already find plenty of examples there:
* Using CKEditor 5 Builds: start with [Quick start guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html)
* Using CKEditor 5 Framework: start with [Quick start guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)
* [Examples of some CKEditor 5 builds](https://ckeditor.com/docs/ckeditor5/latest/examples/index.html)
* [Examples for some editor features](https://ckeditor.com/docs/ckeditor5/latest/features/index.html), with code snippets and demos
