### ISSUE TITLE
[Abbreviation tutorial] Should we cover the t() function?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#12102]
Right now it's mentioned and used but it won't work automatically.

To have translations you have to still put in a lot of work. The [package generator](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/package-generator.html) that we developed provides tooling to make translations work, but it's a next step, I believe.

So, I'd either remove the `t()` use from the tutorials or add one more part where we teach about this. But I'm not 100% sure how that part should look like.

**Comment by barbaramistrz** [comment]
Good point, I'll remove it from the Abbreviation guide. What about advanced guides? Do they need an additional section? For instance https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#creating-a-button

**Comment by Mgsy** [comment]
The main task is done.

> What about advanced guides on inline and block widgets? They use the `t()` function. Maybe there it would make more sense to add an additional section?

Let's create a follow-up issue for it.
