### ISSUE TITLE
Online builder and PictureEditing plugin

### ISSUE THREAD

**Issue by smalloff** [ckeditor/ckeditor5#12105]
When assembling classic version in an [online builder](https://ckeditor.com/ckeditor-5/online-builder/). I am getting a file without the PictureEditing plugin. When [downloading the archive](https://ckeditor.com/ckeditor-5/download/), PictureEditing is there. This is problem. Is it possible to solve it?

### ✔️ Expected result

The plugin is included in the assembly, after selecting the necessary components.

### ❌ Actual result

The plugin is missing. Which is confirmed by looking at the ckeditor.js source code and searching for PictureEditing.

## 📃 Other details

* Browser: google chrome
* OS: windows 10
* First affected CKEditor version: 5
* Installed CKEditor plugins: classic build with free plugins

**Comment by jswiderski** [comment]
The Picture Editing plugin is part of ckeditor5-image package and it is integrated with Image Upload plugin meaning that builder adds it if appropriate upload adapter is also included e.g. CKFinder, CKBox, EasyImage - 
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_pictureediting-PictureEditing.html

If you are not using any of these features, you can either:
- edit ckeditor-build-folder/src/ckeditor.js by adding import PictureEditing from '@ckeditor/ckeditor5-image/src/pictureediting.js'; there and rebuilding downloaded package (it contains package.json and webpack.config.js so it will work)
- build CKEditor from source code manually and include this plugin - https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source.html
