### ISSUE TITLE
Toolbars disappearing on Safari

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#12115]
## 📝 Provide detailed reproduction steps (if any)

1. Open the editor, and scroll up, so that the toolbar sticks on top.
2. Use any feature from the toolbar on a portion of the content (eg. insert a link, apply formatting)

### ✔️ Expected result

The feature works as expected and the toolbar stays put.

### ❌ Actual result

The toolbar disappears (probably "jumps" to the top, out of viewport).

![2022-07-21 07 42 33](https://user-images.githubusercontent.com/68123541/180191569-ade2f6d6-39a6-490d-a8c4-ed88dbae7558.gif)

### ❓ Possible solution

@FilipTokarski suggested this might be due to changes in the focus area.

## 📃 Other details

* Browser: Safari
* OS: MacOS
* First affected CKEditor version: 35.0.0
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
It looks really bad, it  also prevents from using table toolbars and image toolbars:

https://user-images.githubusercontent.com/34380544/180219236-173c30b7-023f-4cd1-953a-fd56fa69f3c4.mov

**Comment by FilipTokarski** [comment]
It also makes inline, balloon and balloon block editors unusable.
