### ISSUE TITLE
Log error in test should not be visible

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1211]
![image](https://user-images.githubusercontent.com/2270764/44386078-bb51bc80-a521-11e8-91ae-7c2da6bced4c.png)

https://travis-ci.org/ckeditor/ckeditor5/builds/418559646

However, tests pass. But this log is ugly.

**Comment by scofalik** [comment]
Yes the tests checks whether the error is logged but it could be silenced in some way.

**Comment by pomek** [comment]
You can stub `console.error` and restore it before checking assertions (`expect()`).
