### ISSUE TITLE
Typing, styling behind the text then selecting the text causes error being thrown

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#12114]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/ckeditor-5/demo/#document
2. Type a word anywhere
3. When cursor is stil behind typed text, press bold button
4. Try selecting part of the typed text

NOTE: Any style can be used - one of basic styles, color, background-color, font-size, font-name.

### ✔️ Expected result

Text get selected and no error gets thrown.

### ❌ Actual result

Error gets thrown - TypeError: Cannot read properties of null (reading 'parent') 
<img width="1074" alt="Screenshot 2022-07-21 at 09 52 08" src="https://user-images.githubusercontent.com/5314687/180160601-2ef00457-74f3-47fb-9a7f-ae557d327af1.png">

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: 
* Installed CKEditor plugins:

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This looks like a DUP of recently solved https://github.com/ckeditor/ckeditor5/issues/12026 
Can you verify it on latest master?

**Comment by FilipTokarski** [comment]
Fixed on latest `release`.
