### ISSUE TITLE
Unexpected token: name (Alignment) while building

### ISSUE THREAD

**Issue by rafal-olszewski** [ckeditor/ckeditor5#1212]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor
`ckeditor5-editor-classic v11.0.0`
I've got custom upload adapter and a plugin to list and insert articles from a dropdown menu (none of above are using `Alignment`)

## 📋 Steps to reproduce

Clone repo and follow readme:
https://github.com/rafal-olszewski/ckeditor5-build-issue-reproduction/

## ✅ Expected result
Go through the build successfully without any `ERROR`s while building for production

## ❎ Actual result
```
ERROR in js/app.2dde70e4524477afd31a.js from UglifyJs
Unexpected token: name (Alignment) [../node_modules/@ckeditor/ckeditor5-alignment/src/alignment.js:25,0][js/app.2dde70e4524477afd31a.js:35,6]
error Command failed with exit code 2.
```

## 📃 Other details that might be useful
Reproduction repo should be enough example

**Comment by Reinmar** [comment]
You need to use `uglifyjs-webpack-plugin` in version 1.2.7+. I can see webpack 3 in your `package.json` which comes with an older version of UglifyJS – one that doesn't support ES6. We'd recommend upgrading to webpack 4 or at least using a newer version of UglifyJS. You can read more about this in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html. 

Let us know if this helps.

**Comment by rafal-olszewski** [comment]
We can't go for webpack 4 yet in our app (unfortunately).

I will try with UglifyJS higher version tomorrow and report back.

**Comment by Reinmar** [comment]
The other options are using babel-minify instead of UglifyJS or passing CKEditor 5's code through Babel.

**Comment by wilpat** [comment]
In my case, the uglify that came with webpack by default was being used so i installed `uglifyjs-webpack-plugin`
Then in my webpack.config for production i replaced the 
```
new webpack.optimize.UglifyJsPlugin({
      ...
    }),
```
to 

```
new UglifyJsPlugin({
      test: /\.js($|\?)/i,
      sourceMap: true,
      uglifyOptions: {
        mangle: {
          keep_fnames: true,
        },
        compress: {
          warnings: false,
        },
        output: {
          beautify: false,
        },
      },
    })
```
And my build ran completely
