### ISSUE TITLE
Manual test and the feature guide for Restricted Editing Fails - data cleared when switching modes

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#12120]
## 📝 Provide detailed reproduction steps (if any)

1. Run manual test for Restricted Editing feature
2. Open http://localhost:8125/ckeditor5-restricted-editing/tests/manual/restrictedediting.html
3. Insert extra non-restricted part and switch to Restricted mode or just switch to restricted mode without doing anything

### ✔️ Expected result
Data is preserved.

### ❌ Actual result

Data is cleared
<img width="710" alt="Screenshot 2022-07-21 at 15 24 51" src="https://user-images.githubusercontent.com/5314687/180226058-7f81d5cd-eb8f-4734-a1ea-eddafa4ea703.png">

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: …
* Installed CKEditor plugins: restricted-editing

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
That's due to the recent change in how `destroy()` works.

cc @Mgsy

**Comment by Reinmar** [comment]
@jswiderski This change isn't even released yet. It works fine on `stable`. And it's not an issue with restricted editing itself, but a problem with the manual test itself.

**Comment by Reinmar** [comment]
The same issue can be reproduced in the guide for restricted editing. It's nearly identical with the manual test so both things need to be updated.

**Comment by Reinmar** [comment]
In this specific case, we can use the new option: [https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-updateSourceElementOnDestroy](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-updateSourceElementOnDestroy)

**Comment by Reinmar** [comment]
Let's merge this to the `release` branch.

Scope: manual test + feature guide.

**Comment by Mgsy** [comment]
Fixed.
