### ISSUE TITLE
Word Count in PHP 

### ISSUE THREAD

**Issue by partha200619** [ckeditor/ckeditor5#12131]
Please can u please help me getting the word count in php 

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
	$(document).ready(function(){
		$("#aitextbox").on('input change keyup blur',function(){
			var words = $(this).val().split(" ");
			$('.ck-word-count__words').html('Words: '+words.length);
			$('.ck-word-count__characters').html('Characters: '+$(this).val().length);
		});
		
	});
	
</script>

I want to save the word count in database please help

**Comment by Reinmar** [comment]
I'm sorry but assisting you with PHP is far beyond supporting the project's community.
