### ISSUE TITLE
Styles dropdown does not apply block style for block element nested in non-limit element

### ISSUE THREAD

**Issue by CatStrategist** [ckeditor/ckeditor5#12158]
## 📝 Provide detailed reproduction steps (if any)

1. Example model:
```
<div> // schema of div: inherit all from $block
   [<paragraph>Well hello there!</paragraph>]
</div>
```
2. Selection is on paragraph, not inside.
3. Execute block style for paragraph

### ✔️ Expected result

Block style is applied on paragraph

### ❌ Actual result

No style is applied, following warning is logged to a console: `style-command-executed-with-incorrect-style-name`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
It seems that #12430 fixed the issue.
