### ISSUE TITLE
SourceEditing plugin not working with decoupled document editor example downloaded from online-builder

### ISSUE THREAD

**Issue by AndreMailhoPlaneta** [ckeditor/ckeditor5#12150]
## 💬 Description

I'm trying to implement the SourceEditing plugin in my ckEditor 5 Decoupled Document Editor. In order to understand what I should do, I've downloaded the example from the online builder, but the SourceEditing button seems to not work.

## 📝 Provide detailed reproduction steps (if any)

1. Generate and download Ckeditor5 Decoupled document build from https://ckeditor.com/ckeditor-5/online-builder/ adding the following plugins to the default list:
         General HTML Support
         HTML comment
         HTML embed
         Source editing
2. Include the "Source"  "toolbar  item" to the "picked toolbar items"
3. English language selected
4. Extract the downloaded folder
5. Open the index.html from the sample folder 
6. Click the "Source" button in the toolbar, it does nothing 

### ✔️ Expected result

Clicking  the "Source" button in the toolbar should open the html/source view. 
Like it does with the Classic Editor version:

![image](https://user-images.githubusercontent.com/78096926/180976702-00775c5f-82ff-4b48-a8ca-681cb1838cd8.png)

### ❌ Actual result

Clicking the "Source" button in the toolbar using the Decoupled Document Editor does nothing, the html/source view won't load, and there are no errors in the DevTools:

![image](https://user-images.githubusercontent.com/78096926/180976894-cf33977d-7500-438d-8202-d427d6fd1c98.png)

### ❌ Aditional information

Also, I've tried to download the Decoupled Document Editor for CKeditor 5, with only the following plugins, and it won't work either:
- General HTML Support
- HTML comment
- HTML embed
- Source editing
( The insert HTML work tho 🤷‍♂️ )
![image](https://user-images.githubusercontent.com/78096926/180978354-e6b7c37a-c045-45bc-b1fa-36bd7f29e483.png)

## 📃 Other details

* Browser: Chrome 103.0.5060.134 (Build oficial) (64 bits)
* OS: Windows 10
* Installed CKEditor plugins: Download and tested directly from the CKEditor 5 online-builder

---

**Comment by huzedong2015** [comment]
Local builds don't work either

**Comment by huzedong2015** [comment]
SourceEditing + ClassicEditor   => work
SourceEditing + InlineEditor   => Not working

**Comment by huzedong2015** [comment]
Local build also has this problem. Is there any quick solution

**Comment by huzedong2015** [comment]
@Reinmar @scofalik  Can you help me look at it, local build

**Comment by Reinmar** [comment]
See #9703 and #11789. Source editing works only with the classic editor for now.

I'd close this ticket as DUP, but one more thing was a surprise to me – that Online builder allowed adding source editing to the decoupled editor. I thought we don't allow that. cc @pomek

**Comment by Reinmar** [comment]
@pomek clarified to me that OB doesn't currently handle excluding plugins by the editor type. So, while this could be improved in its UX, it's what's currently expected.
