### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'wrongRequestId')

### ISSUE THREAD

**Issue by jc-harbour** [ckeditor/ckeditor5#12169]
## 📝 Provide detailed reproduction steps (if any)

I'm using 34.2.0 version of ckeditor 5 with real time collab plugins. Also using the 4.0 ckeditor5-vue2 integration. I've tested 34.0 and 34.1 with the same javascript error. I see a javascript error in the `cloudservicesrevisionhistoryadapter.js` file. The Revision History does work properly but this javascript error comes up on first instantiation.

### ✔️ Expected result

Not see error in javascript console.

### ❌ Actual result

When using Revision History Realtime collab plugin, I see the following javascript error.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'wrongRequestId')
    at cloudservicesrevisionhistoryadapter.js:23:4079
```

### ❓ Possible solution

Code is obfuscated so I cannot see what `wrongRequestId` means in this context.

## 📃 Other details

* Browser: Chrome/Safari both have this error.
* OS: MacOS
* First affected CKEditor version: 34.0 that I've tried.
* Installed CKEditor plugins:
```

	Alignment,
	Autoformat,
	Base64UploadAdapter,
	BlockQuote,
	Bold,
	CKFinder,
	CKFinderUploadAdapter,
	CloudServices,
	Comments,
	Essentials,
	ExportPdf,
	ExportWord,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	GeneralHtmlSupport,
	Heading,
	Highlight,
	Image,
	ImageCaption,
	ImageResize,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	Italic,
	Link,
	List,
	ListProperties,
	MediaEmbed,
	PageBreak,
	Pagination,
	Paragraph,
	PresenceList,
	PasteFromOffice,
	RealTimeCollaborativeComments,
	RealTimeCollaborativeEditing,
	RealTimeCollaborativeRevisionHistory,
	RealTimeCollaborativeTrackChanges,
	RevisionHistory,
	RemoveFormat,
	Strikethrough,
	Table,
	TableCellProperties,
	TableProperties,
	TableToolbar,
	TextTransformation,
	TodoList,
	TrackChanges,
	Underline,
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
Hello,

just letting you know that we looked at the issue and found a potential problem. We will update you when there's progress with this problem.

**Comment by scofalik** [comment]
The fix for the problem should be available in the next CKE5 version (which should be released shortly).
