### ISSUE TITLE
Docs issue report from "features/page-break.html"

### ISSUE THREAD

**Issue by rodneyhickman** [ckeditor/ckeditor5#12170]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/page-break.html

### Project version

34.2.0

### Is the information outdated? How?

This doesn't show the HTML code needed to add a page break.  I generate a report and use the editor for users to refine or enhance the generated report. These reports a multiple pages long and I'd like to insert a page break in my HTML that I populate the editor with. What does that HTML look like. I can't seam to get anything to work. 

### Is there something missing in the guide? What is it?

I don't know what I don't know. I want you to put the stuff I don't know in it. 

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**Comment by godai78** [comment]
I'm not sure why anyone would need the actual HTML code for a pagebreak. It's supposed to be added via the toolbar item. It can also be fired with the `editor.execute( 'pageBreak' );` command.  
  
Now, this is the actual code generated by the feature that gets into the HTML:  
  
`</p>`  
`<div class="page-break" style="page-break-after:always;">`  
 `<span style="display:none;"> </span>`  
`</div>`  
  
Sometimes, if you need to see the source code for some features, you can also refer to the full-featured demo which sports most features except the collaboration ones: [https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) Try out the plugins you need and have a peek at the HTML underneath.  
  
That said, I do not recommend adding HTML code to the documents by hand, as this may create certain problems and get filtered during the conversion. Using the toolbar button for a command is always the right choice.  
  
Should you need anything else, please let me know.
