### ISSUE TITLE
Building manual tests causes "JavaScript heap out of memory" error

### ISSUE THREAD

**Issue by przemyslaw-zan** [ckeditor/ckeditor5#12189]
## 📝 Provide detailed reproduction steps (if any)

1. `yarn run manual`

### ✔️ Expected result

Manual tests build as expected. 

### ❌ Actual result

```
Processing 'D:\Repo\ckeditor5\tests\manual\performance\setdata'...
Finished writing 'D:\Repo\ckeditor5\build\.manual-tests\ckeditor5\tests\manual\performance\setdata.html'
Processing 'D:\Repo\ckeditor5\tests\manual\wproofreader'...
Finished writing 'D:\Repo\ckeditor5\build\.manual-tests\ckeditor5\tests\manual\wproofreader.html'
[Webpack] Starting scripts compilation...

<--- Last few GCs --->

[2360:000001D02659FE30]   110572 ms: Mark-sweep 7977.1 (8234.2) -> 7975.3 (8226.4) MB, 327.7 / 0.0 ms  (average mu = 0.759, current mu = 0.129) allocation failure scavenge might not succeed
[2360:000001D02659FE30]   111204 ms: Mark-sweep 7991.0 (8226.4) -> 7989.3 (8251.4) MB, 594.9 / 0.0 ms  (average mu = 0.508, current mu = 0.058) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7148C7B7F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF714854546 DSA_meth_get_flags+65542
 3: 00007FF7148553FD node::OnFatalError+301
 4: 00007FF71518B29E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF71517587D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF715018C4C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF715015D64 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF7150136E0 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF7150313F0 v8::internal::FreeListManyCached::Reset+1408
10: 00007FF715031AA5 v8::internal::Factory::AllocateRaw+37
11: 00007FF71504736F v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString+79
12: 00007FF714D2385B v8::internal::StringStream::ClearMentionedObjectCache+9147
13: 00007FF714F447E4 v8::sampler::Sampler::Stop+3924
14: 00007FF714F4783A v8::sampler::Sampler::Stop+16298
15: 00007FF714F46C7A v8::sampler::Sampler::Stop+13290
16: 00007FF714F47BA0 v8::sampler::Sampler::Stop+17168
17: 00007FF714F4A516 v8::base::TimeDelta::operator!=+7430
18: 00007FF71512517F v8::internal::Builtins::code_handle+38911
19: 00007FF715219091 v8::internal::SetupIsolateDelegate::SetupHeap+494673
20: 000001D029414AC5
error Command failed with exit code 134.
```

### ❓ Possible solution

This issue was discussed and partially fixed previously (https://github.com/ckeditor/ckeditor5/issues/10982) as it broke our CI. The fix was to [disable the watch mode on CI](https://github.com/ckeditor/ckeditor5/blob/master/scripts/check-manual-tests.sh#L17) by using `--disable-watch` option. This workaround also works locally. **Without this option however, the script still fails.**

### Scope:
- Find a way to fix `JavaScript heap out of memory` error that happens without the `--disable-watch` option.
   - [As previously discussed](https://github.com/ckeditor/ckeditor5/issues/10982#issuecomment-988809559), perhaps it would be possible to split the build process into chunks.
- `--disable-watch` option is very unintuitive. Normally, watch mode is disabled by default, and then enabled by using `--watch` option. This anti-pattern should be fixed.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
> --disable-watch option is very unintuitive. Normally, watch mode is disabled by default, and then enabled by using --watch option.> --disable-watch option is very unintuitive. This anti-pattern should be fixed.

I disagree. When running a manual test server, I will modify a test file as often as I check everything I want to verify. Hence, the watcher should be enabled by default.

**Comment by pomek** [comment]
### Scope

* When calling `yarn run manual` (without the `--files` option), let's pass the `--disable-watch` option automatically.
* A place to update: https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-tests/bin/test-manual.js.
