### ISSUE TITLE
[spelling bug] Correct "sceneries" to "scenarios"

### ISSUE THREAD

**Issue by Bellisario** [ckeditor/ckeditor5#12187]
There is a spelling error here (on the classic demo): https://ckeditor.com/ckeditor-5/demo/

On the image description there is "sceneries", but instead it should be "scenarios".

**Comment by dufipl** [comment]
Hello @Bellisario, thank you for the report!
I think "sceneries" in this context was used as the plural form of the word "scenery", which according to the Cambridge dictionary means "the general appearance of the natural environment, especially when it is beautiful" (https://dictionary.cambridge.org/dictionary/english/scenery). With such context and the picture showing such a beautiful area:
<img width="432" alt="Zrzut ekranu 2022-08-1 o 12 55 24" src="https://user-images.githubusercontent.com/32898551/182133342-b9a40610-88a5-424b-adb1-46be1f439904.png">
the word "sceneries" is correct.
I will close the issue for now, but if you still have a comment on that matter, please feel free to ping us here.
