### ISSUE TITLE
Can't close the block toolbar

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12184]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to http://localhost:8081/ckeditor5/34.2.0/examples/builds/balloon-block-editor.html.
2.  Focus the editor.
3.  Open the block toolbar with a mouse click.
4.  Close the block toolbar with a mouse click.

### ✔️ Expected result

The block toolbar disappears.

### ❌ Actual result

It's impossible to close the block toolbar.

### Notes

It's possible to close the block toolbar with `Esc`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
The difference is that during the (this side) button's `execute` event the toolbar is already hidden and focus is brought back to the button itself.

So `this.panelView.isVisible` is evaluating to `false` here:

https://github.com/ckeditor/ckeditor5/blob/d6e41d5dba56d2a472911be1fac5ced0ed2acb59/packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.js#L287

![](https://user-images.githubusercontent.com/5353898/181739742-839eea5a-2f05-47eb-a49b-95dd75741f83.png)

This sounds to me like a result of focus management brought in #12162

**Comment by Dumluregn** [comment]
> This sounds to me like a result of focus management brought in [#12162](https://github.com/ckeditor/ckeditor5/pull/12162)

I'd be surprised if that's true as we only touched the dropdown behaviour. I'll check if this issue was reproducible before merging that PR.

**Comment by Dumluregn** [comment]
I checked the manual test http://localhost:8125/ckeditor5-build-balloon-block/tests/manual/ckeditor.html at the a0244b0 commit (so before all commits from [#12162](https://github.com/ckeditor/ckeditor5/pull/12162)) and this problem is already present there.

**Comment by mlewand** [comment]
A patch that fixes (this particular issue) is in [https://github.com/ckeditor/ckeditor5/tree/ck/12184-closing-balloon-block-toolbar-focus](https://github.com/ckeditor/ckeditor5/tree/ck/12184-closing-balloon-block-toolbar-focus)

**Comment by mateuszzagorski** [comment]
The patch in [https://github.com/ckeditor/ckeditor5/tree/ck/12184-closing-balloon-block-toolbar-focus](https://github.com/ckeditor/ckeditor5/tree/ck/12184-closing-balloon-block-toolbar-focus) does not seem to resolve the issue on Safari.
