### ISSUE TITLE
Table column resize doesn't work well with GHS

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12191]
## 📝 Provide detailed reproduction steps (if any)

1.  Add `TableColumnResize` to http://localhost:8125/ckeditor5-html-support/tests/manual/ghs-all-features.html.
2.  Open the manual test.
3.  Insert a table and resize the columns.
4.  Run `editor.setData( editor.getData() )`.

### ✔️ Expected result

The column remains resized.

### ❌ Actual result

The column is not resized.

### Notes

It works fine after removing GHS.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Done in #12214.
