### ISSUE TITLE
Add a hint to use "dll:build" script

### ISSUE THREAD

**Issue by przemyslaw-zan** [ckeditor/ckeditor5#12190]
When using `yarn run manual` following errors might show up:

```
Module not found: Error: Can't resolve 'ckeditor5/build/ckeditor5-dll.js' in 'D:\Repo\ckeditor5\tests\manual'
Module not found: Error: Can't resolve 'ckeditor5/build/ckeditor5-dll.js' in 'D:\Repo\ckeditor5\tests\manual'
Module not found: Error: Can't resolve 'ckeditor5/build/translations/de' in 'D:\Repo\ckeditor5\tests\manual'
Module not found: Error: Can't resolve 'ckeditor5/build/translations/pl' in 'D:\Repo\ckeditor5\tests\manual'
```

Those happen because the `yarn run dll:build` script was not called beforehand. Sometimes after running that script, the errors still happen, because they have to be used in the `external/...` repository as well. It would be nice to display some message that informs why the error happens, and what has to be done to prevent it.

### Scope
- When the error happens, inform the user that he has to run `yarn run dll:build` first.
- It would be ideal that running the script in the root also runs it for all of the repos in the `external/...` folder.
   - If that is not possible, a hint could just tell the user where the script has to be run. (In the root, and in the `external/...` repositories.)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I've run into the same issue in ckeditor/ckeditor5#12398.

**Comment by pomek** [comment]
### Scope

* We would like to ask a user whether build DLL files based on manual tests to compile.
* How to detect if a manual test requires DLL files?
	* So far, we can assume it contains the `dll` word in a path.
* If so, let's execute `yarn run dll:build` for each repository where the script is specified in `package.json`.
	* `ckeditor5` => `yarn run dll:build`
	* Find all repositories in the `external/` directory
	* For each repository, check if the `dll:build` script exists.
	* If so, execute it.
* By default, the script should suggest the "No" answer.
* For non-interactive consoles, use the default answer.
	* For detecting whether the user can answer questions, see the [create-spinner](https://github.com/ckeditor/ckeditor5-dev/blob/2faea249a20f4bca55ff86020cadf5fefa6a6c5a/packages/ckeditor5-dev-utils/lib/tools/create-spinner.js#L30) function.
