### ISSUE TITLE
Deleting a table throws an error

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#12201]
## 📝 Provide detailed reproduction steps (if any)

1. Checkout branch `ck/epic/11857-table-resize-improvements`
2. Open manual test with table column resize feature: http://localhost:8125/ckeditor5-table/tests/manual/tablecolumnresize.html.
3. Delete a table.

### ✔️ Expected result

Table was deleted.

### ❌ Actual result

There's an error in the console:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/10883184/182314694-35c7cd31-5056-452c-bd78-6cc2f4fa9c42.png">

### ❓ Possible solution

In one of the PRs refactoring the feature we removed the line checking if `tableNode` is nullish: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-table/src/tablecolumnresize/utils.js#L60. Seems it was necessary for the case of removing the node from model. Restoring it (with comment and tests this time) should be enough.

## 📃 Other details

* Browser: all
* OS: all
* First affected CKEditor version: `ck/epic/11857-table-resize-improvements` branch
* Installed CKEditor plugins: `TableColumnResize`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/pull/12205
