### ISSUE TITLE
Add image on ClassicEditor is not working

### ISSUE THREAD

**Issue by rstrapasson** [ckeditor/ckeditor5#1220]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor: 5

V11.0.1

## 📋 Steps to reproduce

1. I used the instructions to create a page using the classic editor but I can't add a image on my textarea. I select the image and click in open, but the image is not added.

**Comment by Reinmar** [comment]
Did you check JS console?

When you drop files to the editor you should see an error on the console which links to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-filerepository-no-upload-adapter

Please read that guide. Also, you can see https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5 for more information.

Let us know if this helped.
