### ISSUE TITLE
Comments goes out the editor veiw

### ISSUE THREAD

**Issue by amitShimon1983** [ckeditor/ckeditor5#12203]
## 📝 Provide detailed reproduction steps (if any)

mark the document several times at the higher point   

### ✔️ Expected result

the first comment shouldn't go outside the editor

### ❌ Actual result

comment goes out the container

### ❓ Possible solution

set first comment to position top 0 on the container

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---
![image](https://user-images.githubusercontent.com/87275582/182336695-a308d5e3-1cfc-4f26-a6fa-1fc02aee7187.png)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @scofalik

**Comment by scofalik** [comment]
Try using [`sidebar.preventScrollOutOfView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-SidebarConfig.html#member-preventScrollOutOfView) configuration option.

This isn't a bug but intended behavior. The comments are positioned in a way, so that selected comment is at the same height as related part of the content. This is how other popular text editing solutions work too. However, if you do not like this default behavior, there's the configuration option.

**Comment by amitShimon1983** [comment]
Yo

> Try using [`sidebar.preventScrollOutOfView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-SidebarConfig.html#member-preventScrollOutOfView) configuration option.
> 
> This isn't a bug but intended behavior. The comments are positioned in a way, so that selected comment is at the same height as related part of the content. This is how other popular text editing solutions work too. However, if you do not like this default behavior, there's the configuration option.

THX dude

**Comment by amitShimon1983** [comment]
This is creating a new bug where the comment lay at the bottom of the container


![image](https://user-images.githubusercontent.com/87275582/182570704-ab5e5016-5be1-4c00-a8e6-4fa25a08c0e6.png)

**Comment by scofalik** [comment]
Certainly this does not look like a correct or intended behavior. However, it's difficult to advise anything on that if we are having only a partial screenshot, no reproduction steps and no information about your integration (type of editor build, used plugins, whether you use multiple editors -- looks like so on the screenshot, whether you use custom plugins, and anything else that you might do in a custom way).

It would be best to have reproduction steps that use snippets from our docs or [our samples](https://github.com/ckeditor/ckeditor5-collaboration-samples).

Keep in mind that if you are our customer, you can [contact us](https://ckeditor.com/contact/) directly for technical assistance.
