### ISSUE TITLE
Not possible to insert image URL with keyboard

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#12215]
## 📝 Provide detailed reproduction steps (if any)

1.  Open editor with Insert Image feature, e.g. https://ckeditor.com/docs/ckeditor5/30.0.0/features/images/image-upload/images-inserting.html
2.  Navigate to toolbar with keyboard (alt/opt + F10)
3.  Navigate to Insert Image button with arrow keys
4.  Press arrow down to open the dropdown

### ✔️ Expected result

The dropdown opens and is fully visible.

https://user-images.githubusercontent.com/95343030/182612417-10c88621-7391-40b6-a7ce-8b655a2e70cb.mov

### ❌ Actual result

The dropdown opens but is empty.

https://user-images.githubusercontent.com/95343030/182612049-7a7a46a8-5b8c-43a0-a7fc-4ce58964ff6f.mov

### ❓ Possible solution

According to @oleq it's _likely_ that rendering is done in `execute` event.

However, pressing down arrow doesn't cause `execute` event (unlike space and enter key).

If that's the case we should simply fire `execute` event as well (for down arrow too) to make sure that other/future implementations doesn't fall into the same issue.

## 📃 Other details

Be sure to check whether nothing in CF broke after this.

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Is it a regression?

**Comment by mmotyczynska** [comment]
No, it's not a regression.

**Comment by mlewand** [comment]
According to @oleq it's _likely_ that rendering is done in `execute` event.

However, pressing down arrow doesn't cause `execute` event (unlike space and enter key).

If that's the case we should simply fire `execute` event as well (for down arrow too) to make sure that other/future implementations doesn't fall into the same issue.
