### ISSUE TITLE
Getting `CKEditorError: svg is null` with a custom build of CKEditor5

### ISSUE THREAD

**Issue by zubozrout** [ckeditor/ckeditor5#12211]
Hi,
I am trying to build CKEditor5 with a combination of craco + react-scripts.
Building the project works using various approaches, but I am trying for this craco conf as it seems to be the most up to date one anyone shared online: https://github.com/ckeditor/ckeditor5/issues/7836#issuecomment-1171455584

However, no matter the building approach I try CKEditor5 fails to load.

### ✔️ Expected result

The app is build-able and runs without an issue.

### ❌ Actual result

The app is build-able without a single error during that process, but CKEditor5 doesn't load. Seeing the following error in the web dev console:
```
CKEditorError: svg is null
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-svg is null
    _updateXMLContent iconview.js:100
    render iconview.js:76
    node_modules bundle.js:100023
    fire emittermixin.js:200
    node_modules bundle.js:100031
    _renderViewIntoCollectionParent viewcollection.js:204
    ...
```

## 📃 Other details

Here is a basic demo where the issue reproducible:
https://gitlab.com/zubozrout/craco-react-scripts-ckeditor5

I am not sure if it is in any way related to any of these issues:
https://github.com/ckeditor/ckeditor5/issues/7836
https://github.com/ckeditor/ckeditor5/issues/12123

but maybe not. Hence this report as it may be a separate issue.

Unfortunately I am unable to make this work even with older versions of react-scripts, craco and ckeditor5 now. It [worked for me a while ago](https://stackoverflow.com/questions/73051885/react-scripts-ckeditor5-latest-stable-versions-incompatibility) I guess (when I used these older versions and `"@ckeditor/ckeditor5-dev-utils": "^29.0.0"`, but no more.

Thank you very much for any hints/help.

**Comment by zubozrout** [comment]
Update:
I've also tried in Chrome. The above log is specific to Firefox. Whereas Chrome seems closer to #7836, but still not the same.
```
TypeError: Cannot read properties of null (reading 'getAttribute')
    at IconView._updateXMLContent (iconview.js:100:1)
    at IconView.render (iconview.js:76:1)
    at IconView.<anonymous> (observablemixin.js:258:1)
    at IconView.fire (emittermixin.js:200:1)
    at <computed> [as render] (observablemixin.js:262:1)
```

**Comment by zubozrout** [comment]
I was able to make this work with a combination of:
- `"@ckeditor/ckeditor5-dev-utils": "^28.0.0"`
- `"@craco/craco": "^6.1.2"`
- `"react-scripts": "^4.0.3"`
as seen in this branch: https://gitlab.com/zubozrout/craco-react-scripts-ckeditor5/-/tree/old-but-working

**Comment by jaireth** [comment]
I don't know if this helps anyone else, but this is what happened in my project.

The official documents say to add a number of things into chainWebpack in the vue.config.js file. There is one line in there:
`svgRule.exclude.add(path.join(__dirname, 'node_modules', '@ckeditor'))`

My project has multiple configs and I keep them in a /config sub directory. So that line resolves to:
`[my project]/config/node_modules/@ckeditor`

So I changed it to:
`svgRule.exclude.add(path.join(__dirname, '..', 'node_modules', '@ckeditor'))`

And now my CKEditor works again.

**Comment by zubozrout** [comment]
So, I am not sure what was it I was doing wrong initially, however now that I retried after some time I am able to build and run CKEditor5 just fine: https://gitlab.com/zubozrout/craco-react-scripts-ckeditor5

I have to use this craco config approach: https://github.com/ckeditor/ckeditor5/issues/7836#issuecomment-1171455584
Thank you to its author for that!

So I am closing this as all is good and I was likely simply doing something wrong or maybe I was using incompatible versions of packages/had some junk on my computer, not idea.
