### ISSUE TITLE
Styles (font, size) lost on new paragraphs

### ISSUE THREAD

**Issue by DaveInMaine** [ckeditor/ckeditor5#1222]
🐞 Bug report 

Inline styles (font, size, bold, marker colors, etc) get lost at the end of paragraphs. Pressing Enter in the middle when not positioned at beginning or end preserves the styles in both parts of the "split" paragraph, which is good. If you are at the end of the paragraph (which will be the usual case if typing a new document, everything gets reset to the default when you press Enter. Based on the behavior of popular word processors, the inline styles should be copied to new paragraphs.

I'm using a version built from the framework installed a couple weeks ago. Not sure if there is a global version number or not. In any case all builds seem to behave the same, so version shouldn't matter.

📋 Steps to reproduce

1. Type a few words of text on an empty page
2. Select all, and set custom font, size, marker colors, or any similar inline styles
3. Move to end of content, and type a few more words. All will show with the newly set styles as expected.
4. Then press Enter to start a new paragraph. 
5. The styles are all reset to default now.

✅ Expected result
The inline styles should be preserved on the new paragraph, as is the standard behavior of MS Word, Google Docs, and other popular document editors. I believe this is the behavior that most people will expect and desire.

❎ Actual result
The styles are all reset to default upon pressing Enter. Not a big deal for Bold/Italic, since those rarely need to span multiple paragraphs, but very annoying if you need to keep re-selecting the desired font,  size and/or color.

📃 Other details that might be useful

The same thing happens if you delete the last letter in a paragraph (so it becomes empty), and then type some more. In a blank page, type "Hi", then select it, set font & size. Then move to end, press backspace twice, and type "Hello" - your font and size are reset to default again.

**Comment by Reinmar** [comment]
Hi! Thanks for a very detailed ticket.

The problem with enter is described here: https://github.com/ckeditor/ckeditor5-enter/issues/40

The backspace behaves like this on purpose. If you think that backspace should work differently please report a new ticket in https://github.com/ckeditor/ckeditor5-typing/issues.

**Comment by Reinmar** [comment]
PS. 👍 the linked ticket so we can prioritise it. I reported it a long time ago and to my surprise we got just a single DUP of it reported and no other activity.
