### ISSUE TITLE
How to dynamically add an editable element in a multi root editor

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#12235]
## 📝 Provide a description of the improvement

1、Dynamically add or delete editable elements on the page ？
2、How can I listen for data changes in an root

[ckeditor5-build-multi](https://github.com/huzedong2015/ckeditor5-build-multi)

## 📃 Other details

* Browser:  Chrome 103
* OS: windows 11
* CKEditor version:  34.2.0
* Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by huzedong2015** [comment]
If I have 100 editable areas and I change the content of one of them, how can I listen

**Comment by scofalik** [comment]
Closed in favor of #13388
