### ISSUE TITLE
How to use ckeditor5-core in superbuild with cdn

### ISSUE THREAD

**Issue by hhllee** [ckeditor/ckeditor5#12245]
import Plugin from "@ckeditor/ckeditor5-core/src/plugin" but it thorw error
![image](https://user-images.githubusercontent.com/57935206/183560800-6e854286-a70c-4885-aa00-f7ffe122e74f.png)
Thanks

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. Could you add precise steps to reproduce this error?

**Comment by hhllee** [comment]
> Hi, sorry for the late reply. Could you add precise steps to reproduce this error?

Thank you for your reply
I am using creditor5 superbuild
`<script src="https://cdn.ckeditor.com/ckeditor5/34.2.0/super-build/ckeditor.js"></script>`

I want to customize a plugin and install the package
`"dependencies": {
    "@ckeditor/ckeditor5-core": "^34.2.0",
    "@ckeditor/ckeditor5-engine": "^34.2.0",
    "@ckeditor/ckeditor5-ui": "^34.2.0",
    "axios": "^0.27.2",
    "prop-types": "^15.5.8"
  }`

This is my customPlugin code
`import React, { useEffect, useState } from "react";
import Plugin from "@ckeditor/ckeditor5-core/src/plugin";

export default class CustomPlugin extends Plugin {
  init() {
    console.log('init');
  }
}`

ckeditor config
`image: {
      toolbar: [
        "imageStyle:inline",
        "imageStyle:alignLeft",
        "imageStyle:alignCenter",
        "imageStyle:alignRight",
      ],
      styles: ["inline", "alignLeft", "alignCenter", "alignRight"],
      resize: false,
      upload: {
        types: ["png", "jpeg"],
      },
    },
    // The "super-build" contains more premium features that require additional configuration, disable them below.
    // Do not turn them on unless you read the documentation and know how to configure them and setup the editor.
    removePlugins: [
      // These two are commercial, but you can try them out without registering to a trial.
      // "ExportPdf",
      // "ExportWord",
      "CKBox",
      // "CKFinder",
      // "EasyImage",
      // This sample uses the Base64UploadAdapter to handle image uploads as it requires no configuration.
      // https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/base64-upload-adapter.html
      // Storing images as Base64 is usually a very bad idea.
      // Replace it on production website with other solutions:
      // https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/image-upload.html
      "Base64UploadAdapter",
      "RealTimeCollaborativeComments",
      "RealTimeCollaborativeTrackChanges",
      "RealTimeCollaborativeRevisionHistory",
      "PresenceList",
      "Comments",
      "TrackChanges",
      "TrackChangesData",
      "RevisionHistory",
      "Pagination",
      "WProofreader",
      // Careful, with the Mathtype plugin CKEditor will not load when loading this sample
      // from a local file system (file://) - load this site via HTTP server if you enable MathType
      "MathType",
    ],
    plugin: [CustomPlugin]
`
create editor 
` window.CKEDITOR.ClassicEditor.create(
        document.getElementById(`ck-editor`),
        config
      ).then((editor) => {
          editor.model.document.on("change:data", () => {
          const value = editor.getData();
          console.log(value);
        });

        editor.ui.focusTracker.on(
          "change:isFocused",
          (evt, data, isFocused) => {
            console.log(isFocused);
          }
        );
      });
    }`
When I create an editor, it throws an error
![image](https://user-images.githubusercontent.com/57935206/185020530-bb9d42e7-a800-4a07-b768-481f8b64dddd.png)

Thanks

**Comment by FilipTokarski** [comment]
The [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules) happens because you are trying to add a plugin to and already bundled editor (editor build). If you would like to create an editor with a custom plugin, you would need to either [create the editor from source](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html) or download it from the [online builder](https://ckeditor.com/ckeditor-5/online-builder/), [modify the source files](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/installing-plugins.html#adding-a-plugin-to-an-editor) and rebuild it again.

**Comment by hhllee** [comment]
> [发生重复模块错误](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules)是因为您尝试将插件添加到已捆绑的编辑器（编辑器构建）。如果您想使用自定义插件创建编辑器，您需要[从源代码创建编辑器或从](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)[在线构建器](https://ckeditor.com/ckeditor-5/online-builder/)下载它，[修改源文件](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/installing-plugins.html#adding-a-plugin-to-an-editor)并重新构建它。

Ok I get it. Thanks
