### ISSUE TITLE
Highlight buttons doesn't work with a collapsed selection

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#12246]
## 📝 Provide detailed reproduction steps (if any)

1. Open an example with latest editor and the highlight feature: https://ckeditor.com/docs/ckeditor5/35.0.1/examples/builds-custom/full-featured-editor.html
2. Focus the editor.
3. Place a collapsed selection anywhere in the text.
4. Click down arrow in highlight dropdown button.
5. Choose green marker button from the dropdown.
6. Type "foo"

### ✔️ Expected result

Foo gets typed with green highlight.

### ❌ Actual result

No highlight is applied.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

You can see that the `highlight` attribute doesn't get applied to the selection model when the button is clicked.

It got broken with 35.0.0 (or 35.0.1 if you will), works well with 34.2.0:

https://ckeditor.com/docs/ckeditor5/34.2.0/examples/builds-custom/full-featured-editor.html

* Browser: Any
* OS: Win10
* First affected CKEditor version: 35.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Related https://github.com/ckeditor/ckeditor5/issues/12265 ?

**Comment by mlewand** [comment]
@ckeditor/qa-team since #12265 has been merged can you check if it resolved also this issue (I do ~believe~ hope it did)?

**Comment by dufipl** [comment]
@mlewand Looks like working correctly now:
![foo](https://user-images.githubusercontent.com/32898551/186108675-68418142-7e9c-4994-babc-71d0e5b41dfc.gif)
