### ISSUE TITLE
Styles feature is missing in the full-featured demo

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#12249]
## 📝 Provide a description of requested docs changes

The https://ckeditor.com/docs/ckeditor5/35.0.1/examples/builds-custom/full-featured-editor.html and new demo for collaborative document editing is missing styles feature from https://ckeditor.com/docs/ckeditor5/35.0.1/features/style.html.

**Comment by godai78** [comment]
Postponed until stabilized.
