### ISSUE TITLE
Insert image at the end of document and then unable to type text under it?

### ISSUE THREAD

**Issue by margorpi** [ckeditor/ckeditor5#1224]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

CKEditor 5.0 all builds

## 📋 Steps to reproduce

1. Insert a image at the last line of doc
2. How to type message under it?

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/407.
