### ISSUE TITLE
Table resize after column insert undo crashes the editor

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12266]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a table
2.  Insert a new column somewhere in the middle of created table
3.  Change the width of new column with `column resize`
4.  Undo to the point before adding new column
5.  Attempt to resize the table with rightmost `column resize`

### ✔️ Expected result

Table will properly resize without any jumps.

### ❌ Actual result

Column resize doesn't budge no matter how much force is used on it.  
Console throws a wall of errors.  
The editor is now working in an extremely bugged way.

https://user-images.githubusercontent.com/66953380/184334313-c4f03274-5c14-463b-aeaa-9159dbed7827.mov

## 📃 Other details

Console error:

```javascript
Uncaught TypeError: Cannot read properties of undefined (reading '\_setStyle')  
at DowncastWriter.setStyle (downcastwriter.ts:378:1)  
at tablecolumnresizeediting.js:534:1  
at View.change (view.ts:427:1)  
at TableColumnResizeEditing.\_onMouseMoveHandler (tablecolumnresizeediting.js:531:1)  
at invokeFunc (debounce.js:95:1)  
at trailingEdge (debounce.js:144:1)  
at timerExpired (debounce.js:132:1)  
```

If in step 5 a different resize is used, the columns jump a bit and table resizes in a bugged way.  
After that everything works as expected.

https://user-images.githubusercontent.com/66953380/184334529-42069972-be31-45b0-a41d-900e481db90f.mov

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Fixed with ckeditor/ckeditor5#12288
