### ISSUE TITLE
Paste Handler

### ISSUE THREAD

**Issue by SKGGitHub** [ckeditor/ckeditor5#1226]
Hi Team,

CKEditor5 is looking very nice in my application and I am glad that I have used it.
Can you guide me on how to capture Paste event on editor, so that I can write some handle on it to make changes after pasting the data.

**Comment by Reinmar** [comment]
The clipboard input mechanism is described in the Clipboard plugin docs: https://ckeditor.com/docs/ckeditor5/latest/api/module_clipboard_clipboard-Clipboard.html

See especially the `inputTransformation`'s example.

**Comment by Reinmar** [comment]
BTW, a more up to date docs are available here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_clipboard_clipboard-Clipboard.html
