### ISSUE TITLE
Remove highlight applies the currently chosen highlight type instead or removing it

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#12265]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html
2. Try to remove highlight on any selection

It was introduced in version 35

### ✔️ Expected result

Highlight is removed.

### ❌ Actual result

https://user-images.githubusercontent.com/34380544/184306764-6de06015-32ed-47df-8bce-4167d95cd9b0.mov

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This regression is **probably** caused by the changes introduced in ckeditor/ckeditor5#12125 (see the explanation that we wrote down there). However, I'd recommend bisecting first.

**Comment by arkflpc** [comment]
The first bad commit is 618bb417481b377cae88c66b57c8006241dffb0d
