### ISSUE TITLE
Using multiple editors with Context 

### ISSUE THREAD

**Issue by amitShimon1983** [ckeditor/ckeditor5#12276]
## 📝 Provide a description of requested docs changes
using multiple editors with context, the documentation not show how I need to integrate users and comments
_What is the purpose and what should be changed?_

how I can implement users and comments with multiple editor  and context

**Comment by Reinmar** [comment]
Hi @amitShimon1983! Comments is a commercial plugin and this issue tracker is mainly for the open source part of the project. If you are a licensed user and encounter any problems, we encourage to contact us via the [official support channel](https://ckeditor.com/contact/). Our customer care team will handle your request as soon as possible.
