### ISSUE TITLE
cant create new comment sometimes

### ISSUE THREAD

**Issue by amitShimon1983** [ckeditor/ckeditor5#12272]
## 📝 Provide detailed reproduction steps (if any)
my setup includes editor classic build I'm using the comment-only mode, I have multiple editors but only one sidebar
 the plugins I use are 
BalloonToolbar,
  Comments,
  Mention,
  Essentials,
  Heading,
  Image,
  List,
  MediaEmbed,
  PasteFromOffice,
  GeneralHtmlSupport,
  Link,
this is my config ` htmlSupport: {
    allow: [
      {
        name: /.*/,
        attributes: true,
        classes: true,
        styles: true,
      },
    ],
  },
  balloonToolbar: {
    items: ['comment'],
    shouldNotGroupWhenFull: true,
  },
  comments,
  extraPlugins: [CommentsIntegration],
  plugins,
  removePlugins: ['Markdown'],
  collaboration: {
    channelId: 'channel-id-3',
  },`

[video](https://www.loom.com/share/15016b806a884cee802d16d7396286c4)
[second details video](https://www.loom.com/share/7826267c46aa40d3b7361ed2c9434209)
<img width="276" alt="image" src="https://user-images.githubusercontent.com/87275582/184534055-bccc7c95-2f98-41eb-8e21-900177e9b82b.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/87275582/184534222-3063df37-a3a3-4f77-be80-be694b637783.png">

### ✔️ Expected result
new comments should push other comments
_What is the expected result of the above steps?_

### ❌ Actual result
sometimes comment get stuck under other comment
_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi [**@amitShimon1983**](https://github.com/amitShimon1983)! Comments is a commercial plugin and this issue tracker is mainly for the open source part of the project. If you are a licensed user and encounter any problems, we encourage to contact us via the [official support channel](https://ckeditor.com/contact/). Our customer care team will handle your request as soon as possible.
