### ISSUE TITLE
Users Docs

### ISSUE THREAD

**Issue by amitShimon1983** [ckeditor/ckeditor5#12273]
## 📝 Provide a description of requested docs changes
Hey, as I'm flowing your docs trying to find a way to give users dynamic color for comments and annotation,
I read this doc [Adding user color doc](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/users.html#adding-more-user-colors)

but when I'm following the instruction I get a sass error on that lin of code: @mixin userColor hsla(61, 90%, 43%, 1), hsla(61, 90%, 43%, 0.15), 9; the error SassError: expected "{". 

my questions are 
1. can it help me to give dynamic color to user annotation color and comment color? 
2. I need a different color for each user.

my setup is react app 

_What is the purpose and what should be changed?_

**Comment by Reinmar** [comment]
Hi [@amitShimon1983](https://github.com/amitShimon1983)! Comments is a commercial plugin and this issue tracker is mainly for the open source part of the project. If you are a licensed user and encounter any problems, we encourage to contact us via the [official support channel](https://ckeditor.com/contact/). Our customer care team will handle your request as soon as possible.
