### ISSUE TITLE
[Safari] Applying text format on 3 separately formatted fragments causes breaking error

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12294]
## 📝 Provide detailed reproduction steps (if any)

1.  Apply text formatting to 3 parts of text (separately)
2.  Select the 3 parts and attempt to apply another format

### ✔️ Expected result

Selected part of text will format accordingly, editor will work as it should afterwards

### ❌ Actual result

The formatting goes through, but the editor crashes in process

https://user-images.githubusercontent.com/66953380/185591677-cde73daa-1579-4279-8fc2-82c0a64ce818.mov

## 📃 Other details

Safari only.

Console errors:

```javascript
CKEditorError: The index is not in the allowed range.
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-The index is not in the allowed range.

CKEditorError: cannot-change-view-tree
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-cannot-change-view-tree
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
I think, I have just fixed that in #12375. @Acrophost, will you re-test it? On PR #12579 branch.

**Comment by Acrophost** [comment]
The issue doesn't seem to occur anymore 🎉

**Comment by arkflpc** [comment]
> The issue doesn't seem to occur anymore tada

Thanks, @Acrophost, I'll close it as soon as this PR is done.
