### ISSUE TITLE
Split Editor into BaseEditor and Editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#123]
As described here https://github.com/ckeditor/ckeditor5-design/issues/140#issuecomment-199713534

**Comment by Reinmar** [comment]
Actually, the base class should be called `Editor`. Otherwise we'll need to use the type `BaseEditor` everywhere in the docs. So we need a good name for the "headfull" editor (as opposed to headless editor).

**Comment by pjasiun** [comment]
`FrontendEditor`?

**Comment by Reinmar** [comment]
We've done enough changes to the Editor class in #185. There's Editor and StandardEditor at the moment, but we may introduce more classes in the future. Those are enough for the cases that we have currently on our hands.
