### ISSUE TITLE
Add Undo/Redo feature guide

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#12301]
Make a dedicated Undo/Redo feature guide

- [x] overview
- [x]  demo
- [x] keyboard shortcuts

**Comment by Reinmar** [comment]
Assuming this is a feature guide and covers mostly the feature overview + information for integrators I'd cover the basics of the API:

*   The `Undo` plugin that enables this feature.
*   The `UndoCommand` and `RedoCommand` available as `'undo'` and `'redo'` that allow programmatically call the undo/redo feature. Code examples:
    *   `editor.execute( 'undo' );`
    *   `editor.execute( 'redo' );`
    *   `editor.execute( 'undo', batchToUndo );` – example of a selective undo (I explained it below)
*   The buttons.

Some other tid bits:

*   The undo feature in CKEditor 5 is capable of selectively reverting past changes – i.e. other changes than just the last ones made. This is very powerful feature allowing to handle asynchronous actions such as image uploads without blocking the user.
*   The selective undo is also heavily used by real time collaboration. In this scenario, a specific user should only be able to revert their changes, while keeping the changes made by other users (assuming they are not conflicting). This is another example of selective undo where you omit some changes going down the stack.

There's hardly any more material I can think of.
