### ISSUE TITLE
npm run reinstall without changing branches

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#1232]
## Is this a bug report or feature request? (choose one)

 🆕 Feature request 

## 💻 Version of CKEditor

N/A

## 📋 Feature

`npm run reinstall` changes all the branches to the ones defined in `package.json` (AFAIR, the important part is that they change). I'd like to have a command that does everything that needs to be done to "clean" the project (what `reinstall` does) but without changing branches. Now it is not possible. It leads to a situation that you need to know what `reinstall` does to do it by hand.

My proposal is: change `reinstall` to one of: `init`, `reinit`, `reset`, `clean` and then make `reinstall` do what it does but without branches changing.

**Comment by pomek** [comment]
I would like to go with `init` and `reinstall`. Init will do the same what reinstall now, the reinstall will remove node_modules/ in all packages (and ckeditor5 itself) then re-install it once again.

**Comment by pjasiun** [comment]
I do not like `init`. I rarely use this script to init. Usually, I use it to reset the project, so I propose to go with `reset`. `reset` makes also some sense in the first usage (as a reset after the initialization).
