### ISSUE TITLE
Can't unhighlight text in Chrome-based browsers

### ISSUE THREAD

**Issue by nickautomatic** [ckeditor/ckeditor5#12331]
## 📝 Provide detailed reproduction steps

1. Enter some text in an instance of CKEditor (eg. on [this demo page](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html))
2. Highlight the text
3. Select the highlighted text and click the "remove highlight" (eraser) button in CKEditor

### ✔️ Expected result

The highlight should be removed

### ❌ Actual result

In Chrome-based browsers nothing happens - the highlight remains.

### ❓ Possible solution

This functionality seems to work as expected in Firefox, so it's likely this is a browser bug.

## 📃 Other details

* Browser: Chrome / Edge / Vivaldi
* OS: Windows + MacOS
* First affected CKEditor version: 5?
* Installed CKEditor plugins: 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Does it sound like a DUP of ckeditor/ckeditor5#12265? You can check whether your problem is already resolved in the nightly docs: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/highlight.html

**Comment by nickautomatic** [comment]
@Reinmar Ah, yes, that does look like it's probably the same issue. I've only got one highlight colour, so can't confirm the other aspects, but the unhighlighting issue seems the same. Can also confirm that it seems to be working ok on the page in the nightly docs that you linked to. I'll close this issue for now. Thanks for the quick response 👍
