### ISSUE TITLE
Text formatting not disabled on image in heading/paragraph

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12332]
## 📝 Provide detailed reproduction steps (if any)

1.  Enter [Classic editor](http://127.0.0.1:8080/ckeditor5/latest/examples/builds/classic-editor.html), [Inline editor](http://127.0.0.1:8080/ckeditor5/latest/examples/builds/inline-editor.html) or [Document editor](http://127.0.0.1:8080/ckeditor5/latest/examples/builds/document-editor.html) in documentation
2.  Create a heading/paragraph with random text content
3.  Add an image to the heading

### ✔️ Expected result

Toolbar buttons adding text formatting (e.g. bolding, italic, link...) should be disabled unless caption is added

### ❌ Actual result

The text formatting toolbar buttons are not disabled even when there is no image caption

https://user-images.githubusercontent.com/66953380/186473696-3f1569c0-31bd-4a3f-8325-2f39089f28a2.mov

## 📃 Other details

*   Browser: Chrome, Mozilla Firefox, Safari
*   OS: MacOS
*   First affected CKEditor version: 32.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
That's actually expected. E.g. you may want to link the image, so the link feature should be enabled. Similarly, if the image is part of a phrase that should be empasized, you may need to use bold (semantically, it makes sense – e.g. the image may be some sort of emoji or other word-like thingy).
