### ISSUE TITLE
Allow hiding individual list items in the UI for better focus management

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#12357]
## 📝 Provide a description of the new feature

*   ATM only `ButtonView` has observable `isVisible` property. 
*   This causes problems with focus tracking when certain list items should be hidden but in reality only their children (buttons) are hidden
    *   `FocusTracker` focuses (visible)  `ListItemView` with an invisible button inside which results in a focus loss.
        *   `ListItemView` always tries to focus its first child when `focus()` is called.
    *   If `ListItemView` was truly invisible, `FocusTracker` could skip it.

See https://github.com/cksource/collaboration-features/pull/4731#issue-1352307814

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Closed with ckeditor/ckeditor5#12355.
