### ISSUE TITLE
Docs issue report from "framework/guides/plugins/creating-simple-plugin-timestamp.html"

### ISSUE THREAD

**Issue by msvi** [ckeditor/ckeditor5#12351]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/creating-simple-plugin-timestamp.html

### Project version

35.0.1

### Is there something missing in the guide? What is it?

The article is referred to in `Features -> Toolbar -> Editor toolbar -> Adding a custom button`. However, following the instructions using a build from the online build tool leads to an error: `ckeditor-duplicated-modules`.

### User agent

Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0

**Comment by apadol-cksource** [comment]
Hi @msvi ,

Thank you for reporting the problem. It looks like you're trying to add a plugin to an editor that's already built, or there's some version mismatch between the editor's build and other dependencies you're trying to add as [described here](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules). If this is not the case then we would need more details to investigate the problem further.
