### ISSUE TITLE
Add ESLint to build repos

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1236]
Is there a reason why we don't have ESLint + precommit hook in build repos? Or we just forgot about that?

**Comment by pomek** [comment]
I guess we forgot about it.

**Comment by pomek** [comment]
We could skip ESLint and pre-commit hook because the source of the build was generated by some scripts. In fact, there was only one file to check. But I'm not sure. I don't remember exactly how it was.

**Comment by pomek** [comment]
After merging PRs above (4), this ticket should be closed.

**Comment by wwalc** [comment]
It looks like all repositories mentioned above are already enabled.

<img width="829" alt="screenshot 2019-01-04 at 18 04 33" src="https://user-images.githubusercontent.com/545175/50700633-5c618f80-104b-11e9-8671-12a99508218e.png">

**Comment by pomek** [comment]
I forgot about adding badges to the README…

**Comment by Reinmar** [comment]
> I forgot about adding badges to the README…

I'll reopen the ticket to not forget about this – it's actually crucial :D

**Comment by pomek** [comment]
READMEs have been updated.
