### ISSUE TITLE
error char repeat in the IME between multiple spaces

### ISSUE THREAD

**Issue by comvir** [ckeditor/ckeditor5#12360]
## 📝 Provide detailed reproduction steps (if any)

1. input more than 3 spaces;
2. use chinese IME input between these spaces；

### ✔️ Expected result

no repeat char when input

### ❌ Actual result

look this image
![image](https://user-images.githubusercontent.com/7907986/187345716-f6f1700f-4394-4564-bc0a-2ffb9b1e116d.png)

### ❓ Possible solution

no repeat char when input

## 📃 Other details

* Browser: chrome latest
* OS: win10
* First affected CKEditor version:35.0.0
* Installed CKEditor plugins: look like the offical demo
*
![image](https://user-images.githubusercontent.com/7907986/187346166-529a5897-3874-45d6-810e-075e6496e652.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by comvir** [comment]
thanks,issue are close

**Comment by Reinmar** [comment]
Thanks for letting us know! We're still grooming old tickets related to IME after releasing [v35.3.0](https://ckeditor.com/blog/ckeditor-5-v35.3.0-with-a-revamped-typing-and-ime-handling-better-external-annotations-handling/).
