### ISSUE TITLE
[Android/IME] Selecting a column/row clears its content

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12369]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the all features manual test.
2.  Put the caret in a table cell.
3.  Use the table toolbar and click on the Select column button.

### ✔️ Expected result

The column is selected.

### ❌ Actual result

The column content disappears.

## 📃 Other details

The same scenario applies to table rows.

Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`  
Language: English  
Keyboards: GBoard, Android keyboard  
Device: Nexus 10 emulator@Android v12

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I can reproduce this in the all features manual test, but it doesn't happen always. It seems to depend on the content of a table.

E.g. I can only reproduce this in the first column here:

![](https://user-images.githubusercontent.com/156149/187642256-14c7808f-7c00-45d8-8eef-64d169fcd996.png)

We observed that Chrome fires `compositionstart` and `compositionend` events right after clicking the "Select column" button. Probably, the content gets cleared on `compositionstart` by our handler.

**Comment by Reinmar** [comment]
Fix for this issue may also resolve ckeditor/ckeditor5#12383.

**Comment by Reinmar** [comment]
Idea: For Android only, replace the [`compositionstart` listener](https://github.com/ckeditor/ckeditor5/blob/3f2a8b0fe92b3eca8bff402ca10308bb504c597d/packages/ckeditor5-typing/src/input.js#L99-L113) with a `keydown:229` listener.

The current listener that calls `deleteContent()` is executed before the moment when we change the `isComposing` flag to `true`. The `keydown:229` is fired before `compositionstart` so we'll not affect the order here.

**Comment by Reinmar** [comment]
Something like this seems to work (of course, we still need the compositionstart for other browsers and do the new thing only on Android).

```
diff --git a/packages/ckeditor5-typing/src/input.js b/packages/ckeditor5-typing/src/input.js
index a7a644bd93..32f3f46853 100644
--- a/packages/ckeditor5-typing/src/input.js
+++ b/packages/ckeditor5-typing/src/input.js
@@ -97,19 +97,20 @@ export default class Input extends Plugin {

 		// Note: The priority must precede the CompositionObserver handler to call it before
 		// the renderer is blocked, because we want to render this change.
-		this.listenTo( view.document, 'compositionstart', () => {
+		this.listenTo( view.document, 'keydown', ( evt, data ) => {
 			if ( modelSelection.isCollapsed ) {
 				return;
 			}

-			// @if CK_DEBUG_TYPING // if ( window.logCKETyping ) {
-			// @if CK_DEBUG_TYPING // 	console.log( '%c[Input]%c Composition start -> model.deleteContent()',
-			// @if CK_DEBUG_TYPING // 		'font-weight: bold; color: green;', '',
-			// @if CK_DEBUG_TYPING // 		`[${ modelSelection.getFirstPosition().path }]-[${ modelSelection.getLastPosition().path }]`
-			// @if CK_DEBUG_TYPING // 	);
-			// @if CK_DEBUG_TYPING // }
-
-			model.deleteContent( modelSelection );
+			if ( data.keyCode === 229 ) {
+				// @if CK_DEBUG_TYPING // if ( window.logCKETyping ) {
+				// @if CK_DEBUG_TYPING // 	console.log( '%c[Input]%c Composition start -> model.deleteContent()',
+				// @if CK_DEBUG_TYPING // 		'font-weight: bold; color: green;', '',
+				// @if CK_DEBUG_TYPING // 		`[${ modelSelection.getFirstPosition().path }]-[${ modelSelection.getLastPosition().path }]`
+				// @if CK_DEBUG_TYPING // 	);
+				// @if CK_DEBUG_TYPING // }
+				model.deleteContent( modelSelection );
+			}
 		} );
 	}
 }
```

Make sure to add a comment pointing to this issue cause this will be WTH in the future.

**Comment by Mgsy** [comment]
Fixed on `ck/11438-beforeinput-ime-research-vol1.1-android` branch.
