### ISSUE TITLE
Focus handling of buttons in "Show more items" tray is broken

### ISSUE THREAD

**Issue by lauriii** [ckeditor/ckeditor5#12363]
## 📝 Provide detailed reproduction steps (if any)

1. Enable enough buttons in the toolbar to get the "Show more items" tray to show up
2. Click a button inside the "Show more items" tray 
3. Focus is returned to the "Show more items" tray toggle button, not where it was actually intended to return.

### ✔️ Expected result

For example, if a list is added from a button that is in the "Show more items" tray, focus should return to list in the editor.

### ❌ Actual result

Focus is returned to the "Show more items" tray toggle button

## 📃 Other details

Tested on HEAD, f811d49616

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Thanks, we're aware of this issue it's reported as ckeditor/ckeditor5#12178.

Meanwhile we have a PR proposal to address this issue so you can see if the problem is gone there: ckeditor/ckeditor5#12319
