### ISSUE TITLE
Not possible to undo and IndexSizeError when the background colour is applied on Safari in the all-feature manual test

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12375]
## 📝 Provide detailed reproduction steps (if any)

1. Open on master http://localhost:8125/ckeditor5/tests/manual/all-features.html
2. Select this text:
<img width="645" alt="Zrzut ekranu 2022-08-31 o 12 34 09" src="https://user-images.githubusercontent.com/32898551/187659298-010d1fb7-6ca9-400c-bd37-2bfd50f0e857.png">

3. Try to apply background colour

### ✔️ Expected result

Background colour applied, no errors in the console, possibility to undo. 

### ❌ Actual result

Background colour applied, errors in the console, undo not possible. 
![background colour issue](https://user-images.githubusercontent.com/32898551/187656693-f1dab351-8c54-4ccd-80be-2058314c4cd8.gif)

```
[Error] IndexSizeError: The index is not in the allowed range.
	fire (all-features.js:1936)
	domListener (all-features.js:29602)
[Error] CKEditorError: cannot-change-view-tree
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree
	fire (all-features.js:1936)
	set (all-features.js:871)
	(anonimowa funkcja) (all-features.js:33708)
```

## 📃 Other details

* Browser: Safari
* OS: Mac OS Monterey
Checked that it is reproducing from at least version `31.0.0`
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
Might be related to: #12294

**Comment by Reinmar** [comment]
I wonder if it's i any way related to ckeditor/ckeditor5#12328.

**Comment by arkflpc** [comment]
> I wonder if it's i any way related to #12328.

It does not seem to be related to that.

**Comment by arkflpc** [comment]
> Might be related to: #12294

Yes, it does. This fix that bug as well.
