### ISSUE TITLE
[IME] Placeholders are visible while typing in the composition

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12389]
## 📝 Provide detailed reproduction steps (if any)

1. Open all features manual test
2. Add a caption to any table/image
3. Start inputting the caption

### ✔️ Expected result

The placeholder disappears as soon as any content is added to caption.

### ❌ Actual result

The placeholder is still visible while adding content to caption.

https://user-images.githubusercontent.com/66953380/187865684-cb1df308-486f-4af5-a20c-96dc411d7112.mov

## 📃 Other details

* Browser: Chrome, Safari, Mozilla Firefox
* OS: MacOS Monterey 12.5.1
* Language: any language with non latin based alphabet (Japanese, Chinese, Korean) - although in case of Korean the placeholder disappears after adding 3 signs
* Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
Actually, this applies to all placeholders e.g. editor placeholder or comment placeholder. Changing the title accordingly.

**Comment by dufipl** [comment]
Issue looks like resolved on the `ck/12389` branch. 👍

**Comment by Acrophost** [comment]
Can't reproduce, so I confirm :D Closing

**Comment by niegowski** [comment]
I want to complete this issue in a separate PR (it's not complete yet) so I'm reopening this.
