### ISSUE TITLE
[IME]Undo deletes to many characters at once

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12382]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the all features manual test.
2.  Start typing random characters as shown on the GIF below or just write English sentences using composition

### ✔️ Expected result

Undo deletes one composition result at once.

### ❌ Actual result

Undo deletes multiple characters at once:
![undo ime swift](https://user-images.githubusercontent.com/32898551/187689920-a4b36e86-73e8-41eb-9e6a-ad6e35ad680f.gif)

## 📃 Other details

Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`  
Language: Japanese
Keyboards: Tested on Swift and GBoard
Device: Pixel C emulator@Android v13 (API 33)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
The same happens if you write English sentences using compositions: 
![undo to many words](https://user-images.githubusercontent.com/32898551/187885220-03c42fcf-0a24-47ae-99ff-f521aa5d3d24.gif)

**Comment by Acrophost** [comment]
Issue is not reproducible on branch `ck/11438-beforeinput-ime-research-vol1.1-android` anymore
