### ISSUE TITLE
[Android/IME] Widgets disappear on click when no other content is present in container

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12383]
## 📝 Provide detailed reproduction steps (if any)

1. Go to all features manual test
2. Scroll down to Link images + Link decorators table
3. Select image in the middle column
4. Click in the same cell somewhere outside the image/caption

### ✔️ Expected result

Nothing will happen.

### ❌ Actual result

Image disappears.

https://user-images.githubusercontent.com/66953380/187703041-3a1fb97d-901b-4fce-b0c0-8ead0d455383.mov

## 📃 Other details

This occurs when image/media/page break/horizontal line is in editor or table cell with no other content.

Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`
Language: English
Keyboards: GBoard only
Device: Galaxy Tab A8@Android 11

**Comment by Mgsy** [comment]
Fixed on `ck/11438-beforeinput-ime-research-vol1.1-android`.
