### ISSUE TITLE
Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by VCodepp** [ckeditor/ckeditor5#1240]
I reading documentation. I use vue but not include tools 'aligment'.

my code
```
<template>
  <div>
    <textarea ref="editor"></textarea>
  </div>
</template>

<script>
import Editor from '@ckeditor/ckeditor5-build-classic';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
export default {
  mounted() {
    Editor.create(this.$refs.editor, {
      plugins: [Alignment],
      toolbar: ['alignment']
    })
      .then(ed => {
        console.log('editor was hered');
      })
      .catch(error => {
        console.error(error.stack);
      });
  }
};
</script>
```
use $ npm install --save @ckeditor/ckeditor5-alignment

**Comment by Reinmar** [comment]
You cannot add plugins to an existing build. Please see https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html. Recent discussion about this topic: https://github.com/ckeditor/ckeditor5/issues/1237.

**Comment by pritamgudekar** [comment]
I am using Angular 6 and I am getting same issue, i.e.'Cannot read property 'getAttribute' of null'.
I used following way:


In template:
<ckeditor #editor *ngIf="tabInformation.showEditor" [(ngModel)]="tabInformation.text" [style]="{'height':'400px'}" [editor]="ckeditor"
        [config]="ckeditorConfig"></ckeditor>

In typescript:
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily';

this.ckeditorConfig = {
      plugins: [FontFamily],
      toolbar: [
        'fontFamily'
      ]
    }

any idea?

**Comment by oleq** [comment]
@pritamgudekar @jonataslubec How is that relevant to this discussion? If you're having troubles with the [official Angular component](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html), please submit an issue to https://github.com/ckeditor/ckeditor5-angular/issues. Thanks!
