### ISSUE TITLE
Change icon of the alternative text to more accurate.

### ISSUE THREAD

**Issue by pszczesniak** [ckeditor/ckeditor5#12410]
## 📝 Provide a description of the improvement

The best we came up with years ago but maybe we could do a little bit better now.

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by CharlesBelov** [comment]
I'm guessing you are referring to the slashed eye icon. I note that Mastodon uses that icon to mean "Hide this media", so there's apparently not even a standard meaning for that icon.

I would suggest rather than an icon replace it with the letters ALT, which would be unambiguous.

**Comment by Witoso** [comment]
@dagdzi food for thought!

**Comment by pszczesniak** [comment]
Solved in #15253
