### ISSUE TITLE
CkEditor5 - Text Indentation

### ISSUE THREAD

**Issue by SKGGitHub** [ckeditor/ckeditor5#1241]
Feature Request:

We are integrating CKEditor5 in our React Application. There is a need of Indentation button to control text indentation in editor for our project. I am unable to find any plugin available for the same. 

Do we have it if I may have missed out it in my search?
Any plan to make it available in near future?
Any pointer through how I can achieve to meet my project requirement?

**Comment by Reinmar** [comment]
Such a feature does not exist yet.

See:

* https://github.com/ckeditor/ckeditor5/issues/1217
* https://github.com/ckeditor/ckeditor5/issues/1197
