### ISSUE TITLE
No polish translation for Font plugin

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#1242]
There is no polish translation for Font plugin.

I'm using `"@ckeditor/ckeditor5-font": "^10.0.2",`

**Comment by Reinmar** [comment]
The translations are managed on https://www.transifex.com/ckeditor/ckeditor5/. All help is always welcomed :) Although, I can see that right now the translation is complete, so I guess it wasn't yet complete when we made the last release. But it will be complete after the upcoming one.

PS. Pozdrowienia z Warszawy :)

**Comment by piernik** [comment]
Great.

P.S. Dzięki - super jest te wasze narzędzie - życzę Wam powodzenia.
