### ISSUE TITLE
Docs issue report from "api/markdown-gfm.html"

### ISSUE THREAD

**Issue by kwanso-adeel72** [ckeditor/ckeditor5#12423]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/markdown-gfm.html

### Project version

35.1.0

### Is there anything else you would like to add?

Please give an complete example how to add markdown 

### User agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**Comment by dufipl** [comment]
Hello @kwanso-adeel72,

The easiest way to add the Markdown plugin is to use our online builder available here: https://ckeditor.com/ckeditor-5/online-builder/ and just select the Markdown plugin from the plugin list. 

If you however would like to add this plugin to your existing build, here you have a guide for plugins installation: https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/installing-plugins.html and the specific guide for installing the Markdown plugin: https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html#installation.

Please let me know if that helped.
