### ISSUE TITLE
Auto-link undo correction

### ISSUE THREAD

**Issue by kbinieda** [ckeditor/ckeditor5#12447]
## 📝 Provide detailed reproduction steps (if any)

1. type "https://ckeditor.com abc" in content (hyperlink should be created for ckeditor.com, while "abc" still remains as text, which is fine)
2. slowly (one character at a time) hit backspace to remove " abc" text (including space).
3. Instead of removing space, editor undo character removal to initial "https://ckeditor.com abc" situation.

### ✔️ Expected result

just "https://ckeditor.com" in editor

### ❌ Actual result

"https://ckeditor.com abc" in editor

**Comment by kbinieda** [comment]
@arkflpc @scofalik While working with the task, I've found that in various places requestUndoOnBackspace function is enclosed in enqueueChange while in some other it is not. Is there a reason to that?

autolink.js
`model.enqueueChange( () => {
	deletePlugin.requestUndoOnBackspace();
} );`

automediaembed.js
`editor.plugins.get( 'Delete' ).requestUndoOnBackspace();`

**Comment by kbinieda** [comment]
@arkflpc @scofalik While working with the task, I've found that in various places requestUndoOnBackspace function is enclosed in enqueueChange while in some other it is not. Is there a reason to that?

autolink.js
`model.enqueueChange( () => {
	deletePlugin.requestUndoOnBackspace();
} );`

automediaembed.js
`editor.plugins.get( 'Delete' ).requestUndoOnBackspace();`

**Comment by arkflpc** [comment]
`requestUndoOnBackspace` should be called after current `Batch` is applied. So if it happens inside `model.change()` or `mode.enqueueChange()`, it has to be wrapped with another `model.enqueueChange()` to delay its execution to another `Batch`. If not, it's not needed.
