### ISSUE TITLE
[Docs] The content in the document editor example is broken

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1246]
![image](https://user-images.githubusercontent.com/156149/45643186-be0ce680-baba-11e8-9c89-8eb63d7d4170.png)

Something's wrong with that table. It looked differently:

![image](https://user-images.githubusercontent.com/156149/45643218-d3821080-baba-11e8-9ca2-0fb9b8f883b1.png)

I know that we changed the default alignment to left. But previously there were two lines of text in each table cell and now it's some mess.

cc @m-kr @dkonopka This same issue may occur on ckeditor.com

**Comment by Reinmar** [comment]
I'm assigning this to you, @jodator cause first it'd be good to check why it looks like this now. But we also have to agree on how the initial content is supposed to look and for that we need @m-kr and @dkonopka

**Comment by jodator** [comment]
@Reinmar so the examples are broken since table cells get block content support and - I don't know why for now - it is kinda broken.

Any inline content breaks auto-paragraph there: for instance:
```js
<td>foo <strong>bar</strong></td>
```
is upcasted to:
```js
<td><p>foo&nbsp;</p><p><strong>bar</strong></p></td>
```
So it:

- creates 2 `<paragraph>`s
- insert `&nbsp;` in one...

**Comment by jodator** [comment]
So the culprit was the way Table feature upcasted it's content. Now it is left to conversion API as it should be. Now the Table feature will only add empty `<paragraph>` to table cells that after conversion does not have any children. 

PR: https://github.com/ckeditor/ckeditor5-table/pull/112. (I've added @scofalik for review).

**Comment by jodator** [comment]
The docs will be fixed by that:
![selection_045](https://user-images.githubusercontent.com/247363/45682496-ad06b880-bb40-11e8-9959-6974f10fab72.png)
