### ISSUE TITLE
Capture the log from the script that builds the DLLs while preparing manual tests

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#12469]
## 📝 Provide a description of the improvement

Follow-up from the https://github.com/ckeditor/ckeditor5-dev/pull/787#issuecomment-1246675952.

**Context** 👉🏻 Currently, if the error is thrown during building the DLLs while preparing manual tests, it is not shown. User has to run the DLL build script manually to get more details. To improve the DX, it could be captured or the full output log from the `yarn run dll:build` could be displayed. Also, the number of repositories where the DLL build is required, could be displayed as well.

**Original idea** 👇🏻 

> It would be better to show the actual error message, as it might not happen every time, and make debuging much harder. Also, the instalation is taking a while. Even though the spinners warns the user about it taking a while, it would help to at least show counter to let the user know how far along the process is. I would not see a problem in simply showing the entire output of the `dll:build` script, since it shows which package is being processed at the moment, and length of its whole output is acceptable.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
### Scope

* Message

```
⚠️ (yellow) Some tests require DLL builds.

You don't have to update these builds every time unless you want to check changes in DLL tests.

You can use the following flags to skip this prompt in the future: --dll / --no-dll.
```

* When executing `yarn run dll:build` for each repository, let's pass all stdout produced by these scripts.
* Consider removing the spinner due to the above.
* Consider executing the DLL builder in the development mode (`--dev`)
