### ISSUE TITLE
Nested lists pasted from Word don't display properly while using Document lists and Indent block

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12466]
## 📝 Provide detailed reproduction steps (if any)

1.  Enable Document lists, Document list properties, Indent block and Paste from Office.
2.  Paste the content from the example - [Lorem ipsum.docx](https://github.com/ckeditor/ckeditor5/files/9565456/Lorem.ipsum.docx)

### ✔️ Expected result

The list displays properly.

### ❌ Actual result

There is an additional margin for the nested list items.

![](https://user-images.githubusercontent.com/20988892/190130401-07f744ca-f51f-4636-bcc9-dfd7b3b13c8d.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Actually, I've just noticed that this issue is caused by the Indent block feature that maintains the `margin-left` attribute on `paragraph`.

**Comment by Witoso** [comment]
The potential scope would be dropping `margin-left` in cases when it's on `ol/ul/li` (and Paste from Office). This aligns also with @jacekbogdanski goals.

**Comment by Witoso** [comment]
Potential blocker for @jacekbogdanski - we would fix it paste, and they need it for the data pipeline as well.

**Comment by Reinmar** [comment]
I think the plan minimum is to make IndentBlock stop upcasting margin-left from \<li> to a paragraph. Dunno how this could be technically achieved, but logically speaking, it does too eager upcast conversion.

**Comment by 108signals** [comment]
Would be great to see this addressed. We've had several customers flag this issue

**Comment by Witoso** [comment]
Scope:

IndentBlock stop upcasting margin-left from \<li> to a paragraph.

Rel: #14155
