### ISSUE TITLE
direction & auto direction

### ISSUE THREAD

**Issue by xxyyzz2050** [ckeditor/ckeditor5#1249]
ckEditor must support default direction to support rtl & ltr languages as well
and add a feature to auto set direction based on the first detectable characher (or use dir="auto")

**Comment by jodator** [comment]
@xxyyzz2050 could you post your requirements (`dir="auto"`) in the [RTL feature request issue](https://github.com/ckeditor/ckeditor5/issues/1151)? We're planning to work on this based on community feedback (more :+1:).
