### ISSUE TITLE
Empty value is getting added as a link to a text.

### ISSUE THREAD

**Issue by vanathishiv** [ckeditor/ckeditor5#12501]
## 📝 Provide detailed reproduction steps (if any)

1. …Enter any text in the editor
2. …Click and select on Link in toolbar without entering anything.
3. …Empty hyperlink is getting added.

### ✔️ Expected result
Empty value shouldn't be getting added as a link.
![Emptylink_Cke5issue](https://user-images.githubusercontent.com/45788491/191741990-d983631f-afab-4d55-a11b-e98b64173dca.JPG)

### ❌ Actual result
Empty value is getting added as a link to a text.

## 📃 Is this the expected behavior or is there anyway we could have validation?

* Browser: … Google Chrome 105
* OS: … Windows 10 Pro/Win64; x64
---
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by vanathishiv** [comment]
It would be great, if we could get any update on this.

**Comment by Reinmar** [comment]
CKE5 needs to preserve empty links as they unfortunately may exist in a content. 

As for the UI, there's no validation indeed. How do you think it should work? And why do you think there should be validation?

**Comment by joegl** [comment]
This is a big regression for us going from CKEditor 4 to CKEditor 5. We allow content editors to put button styles on `<a>` elements and previously they were not allowed to create links without URL's. Now users are complaining there are buttons on their site that don't link anywhere. It's certainly user error and you'd want users to to not do that, but that's not how users work. And this didn't use to even be a possible, so it's definitely a regression.

**Comment by joegl** [comment]
> CKE5 needs to preserve empty links as they unfortunately may exist in a content. 

Preserving empty links in the editor isn't a problem, it's being allowed to create them in the first place. We don't want to strip them if they're in the editor, and meant to be there. We just don't want our users to be allowed to create them without manually editing the source code.

**Comment by Witoso** [comment]
Thanks @joegl for feedback! I will bring it for discussions internally on our side.

**Comment by Witoso** [comment]
Internally, we decided on the future scope:
* there's gonna be a configuration option that manages that, for example `allowEmptyLinksCreation`.
* by default, the editor should not allow creation of empty links via the UI (form validation, `allowEmptyLinksCreation:false`).
* to allow it (and disable validation) set `allowEmptyLinksCreation:true`
* migration guide needs to be prepared.

Editor will still preserve empty links when loaded.

**Comment by joegl** [comment]
@Witoso That sounds wonderful! Thanks for your considerations and responding to this. When would you anticipate this change being completed and release?

**Comment by Witoso** [comment]
No ETA yet, this will enter our support queue as an improvement.
