### ISSUE TITLE
Support for the `@error` tag

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12525]
### Scope

- The content of the [error codes](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html) page is collected from the source code, from the `@error` tags.
- An error definition may contain the `@param` tag. It must be processed too.
- JSDoc plugin: `@ckeditor/jsdoc-plugins/lib/custom-tags/error`

**Comment by psmyrek** [comment]
Done in ckeditor/ckeditor5-dev#790.
