### ISSUE TITLE
Support for the `@module` tag

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12523]
### Scope

- The following _files_ may contain different values for the `@module` tag depending on the position of the definition.

	```ts
	/**
	 * @module fixtures/customerror
	 */
	
	import Error from './error';
	
	export default class CustomError extends Error {
	}
	```
	☝️ `module = fixtures/customerror`

	```ts
	import type Error from './error';
	
	/**
	 * @module fixtures/logger
	 */
	```
	☝️ `module = relative/path/to/file`

- To unify this behavior, let's create a plugin that reads the module name directly from the code.

**Comment by pomek** [comment]
After upgrading to `typedoc@0.23`, all modules were parsed incorrectly. That's good we implemented this plugin.

**Comment by psmyrek** [comment]
Done in ckeditor/ckeditor5-dev#790.
