### ISSUE TITLE
Broken code sample in full featured editor example

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#12530]
![](https://user-images.githubusercontent.com/156149/192749339-a79751e5-a048-4914-b4b3-713bacc52092.png)

We don't publish this file: [https://unpkg.com/browse/@ckeditor/ckeditor5-core@35.0.1/](https://unpkg.com/browse/@ckeditor/ckeditor5-core@35.0.1/)

There's no way it's going to work.

**Comment by dufipl** [comment]
That's not the only problem: `ImageInsert` is present in the `plugins` array in the example config, but is not being imported. That should also be fixed within this ticket.

**Comment by dufipl** [comment]
Also `<script src="dist/bundle.js"></script>` was missing in the `View editor content listing`.
