### ISSUE TITLE
Use of plugin in CKEditor5, toolbar is not visible

### ISSUE THREAD

**Issue by hari457627** [ckeditor/ckeditor5#1253]
Hi,

I'm using CKEditor5 Inline editor,

I want to use some plugins like Font (i.e.., font style and font size etc..,). so i'm importing those plugins by import statement.

After Importing plugins, the toolbar is not visible on the screen on focus of #editor div.
can we use plugins for inline editor, if we can, then I need a sample example code of usuage of plugin. 

need a sample code of inline editor with plugins like font.

Can anyone help me to resolve this issue?

**Comment by Reinmar** [comment]
Hi! Unfortunately, I don't understand your ticket. Could you provide steps to reproduce the issue?
