### ISSUE TITLE
Docs issue report from "api/module_revision-history_revisionhistory-RevisionHistoryConfig.html"

### ISSUE THREAD

**Issue by appl4e** [ckeditor/ckeditor5#12540]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_revision-history_revisionhistory-RevisionHistoryConfig.html

### Project version

35.1.0

### Is there something missing in the guide? What is it?

How to show revision history preview manually from my own event. Not from the toolbar icon dropdown.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

**Comment by scofalik** [comment]
This is not documented yet at the API for customizations has not been set in stone, so please note, that this could change in the future (and/or proper API will be made public).

At the moment, you can call `editor.config.get( 'revisionHistory' ).showRevisionViewerCallback()`. It will return a `Promise` that resolves when revision history view is ready.
