### ISSUE TITLE
Auto correcting a typo causes styles attribute to be cleared

### ISSUE THREAD

**Issue by uriklar** [ckeditor/ckeditor5#12543]
## 📝 Provide detailed reproduction steps (if any)

1. Go to [this codesandbox](https://codesandbox.io/s/ckeditor-fontfamilly-auto-correct-bug-lmt84w?file=/src/App.js)
2. Focus on the word weere
3. Right click
4. Auto correct the word (to any of the suggested words)

I added the font in the original data, but this also happens if starting from a blank data and adding the font family via the toolbar.

### ✔️ Expected result

Text is corrected and retains font family

### ❌ Actual result

style attribute is stripped and font family returns to default

## 📃 Other details

* Installed CKEditor plugins: FontFamily
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team Could you retest this? This could be fixed by migration to beforeInput.

**Comment by mabryl** [comment]
Just tested it on one of our online demos - [https://ckeditor.com/docs/ckeditor5/latest/features/font.html#demo](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#demo) - and it no longer reproduces
