### ISSUE TITLE
Docs: toolbarview-item-unavailable warning in console when undo/redo guide is opened

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12558]
## 📝 Provide a description of requested docs changes

`toolbarview-item-unavailable` warning is present in the console when undo/redo guide https://ckeditor.com/docs/ckeditor5/latest/features/undo-redo.html is opened:
```
snippet.js:4 toolbarview-item-unavailable {name: 'wproofreader'} 
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-toolbarview-item-unavailable
```

**Comment by godai78** [comment]
Fixed in 94d1995
