### ISSUE TITLE
Docs: Migration from CKE4 guide contains outdated plugins compatibility table

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12553]
## 📝 Provide a description of requested docs changes

Some elements of the plugins compatibility table in the Migration from CKEditor 4 guide (https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/migration-from-ckeditor-4.html) are outdated, e.g. stylescombo, uploadfile, filebrowser, format. This needs to be updated.

**Comment by godai78** [comment]
Covered in https://github.com/ckeditor/ckeditor5/pull/13672
