### ISSUE TITLE
Docs issue report from "features/code-blocks.html"

### ISSUE THREAD

**Issue by zgpnuaa** [ckeditor/ckeditor5#12580]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html

### Project version

35.2.0

### Is the information outdated? How?

Cannot insert new text cursor after code block.

### User agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by apadol-cksource** [comment]
Ii can be done as described here: https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#editing-text-around-code-blocks

**Comment by zgpnuaa** [comment]
> Ii can be done as described here: https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#editing-text-around-code-blocks

OK, thank you @apadol-cksource. Maybe it would be better to add the Enter button to the front and back of the code block, just like the two buttons in the picture.
![g](https://user-images.githubusercontent.com/38033949/195972306-c061187f-565a-4c02-9e5c-cbb486008bfa.png)
