### ISSUE TITLE
When adding hyperlink without link text, editing the link doesn’t show a change in the link.

### ISSUE THREAD

**Issue by vanathishiv** [ckeditor/ckeditor5#12588]
## 📝 Provide detailed reproduction steps (if any)

1. Click 'link' from the toolbar and type https://www.google.co.in and enter
2. Then click on link to reedit and enter https://about.google/
3. Editing the link doesn’t show a change in the link.

### ✔️ Expected result

On editing the link it should be changed.

### ❌ Actual result

but on editing the link doesn’t show a change in the link.
<img width="1137" alt="Screenshot 2022-10-06 at 12 32 36 PM" src="https://user-images.githubusercontent.com/45788491/194236132-dbc44c43-5ec1-43c8-9cf5-ae974a6312df.png">

Browser: Google Chrome latest.
OS: macOS Monterey v12.3.1 

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It'd be a good UX improvement if we'd also update the text of a link when the previous text was equal to the link's `href`. 

I agree it must be confusing now.

**Comment by Reinmar** [comment]
Also, CKE4 did update the link text in such cases.

**Comment by Reinmar** [comment]
Also, CKE4 did update the link text in such cases.
