### ISSUE TITLE
CDN offline

### ISSUE THREAD

**Issue by ESEEG** [ckeditor/ckeditor5#12596]
FYI your entire CDN seems to be offline

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Could you please share more details about the issue? Which URL are you checking? I've just checked [https://cdn.ckeditor.com/ckeditor5/35.2.0/classic/ckeditor.js](https://cdn.ckeditor.com/ckeditor5/35.2.0/classic/ckeditor.js) and it loads properly.

**Comment by ESEEG** [comment]
Sorry I didn't post any URL, i can reach v5 now and pretty fast loading times. Thanks!
v4 doesnt seem to be loading yet, 
https://cdn.ckeditor.com/4.14.1/full/ckeditor.js 
or 
cdn.ckeditor.com/4.20.0/standard/ckeditor.js
I'd say it first occured about yesterday morning. Maybe longer

**Comment by Mgsy** [comment]
Thanks for the details. CDN for CKEditor 4 works for me as well, both via HTTP and HTTPS.

**Comment by Mgsy** [comment]
I'm closing this ticket, as it seems everything works fine. Let me know if you still have issues.
