### ISSUE TITLE
[Docs] Document how to style the content

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1259]
We need to document better how to style the content produced by the editor. The overview of this problem is discussed in https://github.com/ckeditor/ckeditor5/issues/773. In this ticket I'd only want to gather ideas what we can document now and where.

**Comment by Reinmar** [comment]
BTW, there's https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#what-happened-to-the-contentscss-file-how-do-i-style-the-content-of-the-editor but it's CKEditor 4 oriented (you need to know what `contents.css` was) and is hidden in a FAQ which we know people have problem finding.

**Comment by jodator** [comment]
I had a problem in finding this in the docs - I've stopped reading the question after `content.css` as I thought the answer was only for the editing part.

I'd expected it to be in ["Integration"](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installation.html) section of the docs. Maybe in the "Getting and saving data" or the "Installation" articles.

**Comment by Reinmar** [comment]
Let's actually merge this into https://github.com/ckeditor/ckeditor5/issues/773. I was surprised now that we have two tickets for that.
