### ISSUE TITLE
GHS should mark formatting elements (so that remove format works with it)

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#12626]
## 📝 Provide a description of the improvement

Currently GHS doesn't work well with remove format feature.

That's because this feature [determines whether something should be removed by looking up at `isFormatting` attribute property](https://github.com/ckeditor/ckeditor5/blob/4a52f6c079c7d4a518aee4d87f15bdb8ae2cc575/packages/ckeditor5-remove-format/src/removeformatcommand.js#L109).

Our [hand-created features add this attribute](https://github.com/ckeditor/ckeditor5/blob/4a52f6c079c7d4a518aee4d87f15bdb8ae2cc575/packages/ckeditor5-basic-styles/src/underline/underlineediting.js#L40) but runtime attributes created by GHS does not:

![](https://user-images.githubusercontent.com/5353898/194904585-e4d5206a-76a0-44fa-949c-e3e0eeb1ce68.png)

If GHS would include a map of known formatting elements this would enable it to work well with remove formatting.

Now, I know there are dozens of formatting elements and attributes in HTML. To keep things simple we don't have to necessarily implement all possible. Just having parity with our hand-crafted features (basic styles, font size/color/bg/face) would be a good start.

## 📃 Other details

*   Browser: Any
*   OS: Any

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@niegowski do you recall whether you had any discussion on that during initial feature implementation?

**Comment by niegowski** [comment]
AFAIR we only considered this part:
```
attributeProperties: {
    copyOnEnter: true
}
```
I don't remember why we skipped the `isFormatting` property.

**Comment by niegowski** [comment]
This should be possible to update the schema definitions here: 
https://github.com/ckeditor/ckeditor5/blob/4a52f6c079c7d4a518aee4d87f15bdb8ae2cc575/packages/ckeditor5-html-support/src/schemadefinitions.js#L664-L671

**Comment by mlewand** [comment]
We could check paste as plain text as it also uses `isFormatting` property.
