### ISSUE TITLE
toggleImageCaption button dont show in contextual image toolbar using online builder

### ISSUE THREAD

**Issue by rmrosa** [ckeditor/ckeditor5#12650]
## 📝 Provide detailed reproduction steps (if any)

1. Select Image and Image Caption plugin in the Online Builder
2. Download ZIP and open the sample html
3. Button  Toggle caption on/off not shown in contextual image toolbar when image selected

### ✔️ Expected result

Similar to "Toggle caption on/off" button on https://ckeditor.com/docs/ckeditor5/latest/features/images/images-captions.html

### ❌ Actual result

Button Toggle caption on/off not shown in contextual image toolbar

## 📃 Other details

* Browser: Chrome/Edge
* OS: Windows
* First affected CKEditor version: CKEditor 5 (last available)
* Installed CKEditor plugins: Image, ImageToolbar, Image Caption, Image Style

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi rmrosa,

Thank you for bringing this issue to our attention. I tested it on my end and I can confirm that the button is missing. I've reported this issue in our online builder repo but can't provide an ETA on when it will get fixed.  
  
In the meantime, you can use this solution to make sure that the button shows up in the toolbar:

1.  Open the \`sample/index.html\` file and edit the script that initialized the CKEditor.
2.  Your script should look similar to the example provided in our docs [here](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html#image-contextual-toolbar). Just provide the items that you want to see on the toolbar, including `toggleImageCaption`.
3.  Save the file and refresh the browser.

Please let me know if you found this solution helpful.

**Comment by mabryl** [comment]
Alternatively, you can also include `toggleImageCaption` in the editor's default configuration in \`src/ckeditor.js\` by adding it to the image toolbar:  
 

> // Editor configuration.  
> Editor.defaultConfig = {  
>  toolbar: {  
>    items: \["undo", "redo"\],  
>  },  
>  language: "en",  
>  image: {  
>    toolbar: \[  
>      "toggleImageCaption",  
>      "imageTextAlternative",  
>      "imageStyle:inline",  
>      "imageStyle:block",  
>      "imageStyle:side",  
>    \],  
>  },  
> }

  
Then, rebuild the editor by running  `npm run build`, refresh the page and the button should show up.
