### ISSUE TITLE
[Style dropdown] Cannot set block style on unordered and ordered lists

### ISSUE THREAD

**Issue by dcmouyard** [ckeditor/ckeditor5#12668]
## 📝 Provide detailed reproduction steps (if any)

1. Open an editor with bulleted list, numbered list, and styles dropdown (e.g. from styles manual tests).
2. Create an unordered or ordered list.
3. Select the whole list.
4. Open "Styles" from the toolbar.

### ✔️ Expected result

It should be possible to select block styles for unordered and ordered lists.

### ❌ Actual result

All block styles are disabled.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by davidloop** [comment]
Can this get fixed, relatively soon please?
