### ISSUE TITLE
Translation error when generating `master` locally

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#12671]
## 📝 Provide detailed reproduction steps (if any)

1.  Checkout the `master` branch
2.  `yarn docs`

### ✔️ Expected result

The docs generate without errors.

### ❌ Actual result

The generation returns the following errors:

```
Executing the snippet adapter for "ckeditor5".
Preparing to build snippets...
⡂⠀ Building next group of snippets (51) for language "en"...Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`).
✔️  Building next group of snippets (51) for language "en"...
⠅⠀ Building next group of snippets (52) for language "en"...Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`).
✔️  Building next group of snippets (52) for language "en"...
⡃⠀ Building next group of snippets (51) for language "en"...Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`).
✔️  Building next group of snippets (51) for language "en"...
⠅⠀ Building next group of snippets (53) for language "en"...Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`).
✔️  Building next group of snippets (53) for language "en"...
⡀⠀ Building next group of snippets (7) for language "en"...Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`).
✔️  Building next group of snippets (7) for language "en"...
⢀⠀ Building next group of snippets (1) for language "ar, es, en"...Cannot find the CKEditor 5 core translation package (which defaults to `@ckeditor/ckeditor5-core`).
✔️  Building next group of snippets (1) for language "ar, es, en"...
```

However, the output local docs work correctly it appears.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: latest Chrome
*   OS: Monterey on Intel
*   First affected CKEditor version: latest `master` branch
*   Installed CKEditor plugins: generic as in docs

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
### Scope

- It would be good to understand why the `Cannot find the CKEditor 5 core translation package (which defaults to @ckeditor/ckeditor5-core).` log appears. [Git bisect](https://git-scm.com/docs/git-bisect) could help.
	- Then, we can try to fix it.
- A place where the log is being displayed: https://github.com/ckeditor/ckeditor5-dev/blob/916fda33a2a0a00949329358233db53875c225c0/packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js#L59-L93.
- It causes translations are not loaded in the bundled editor.
	
	![image](https://user-images.githubusercontent.com/2270764/196623267-2d7e3686-ca7f-4d37-8a4a-3d79e3738d46.png)

	Even if they are defined https://github.com/ckeditor/ckeditor5/blob/6a32372b3d4f0f1ecee1399066dc8f880ee179bb/packages/ckeditor5-core/lang/translations/ar.po#L19-L21
