### ISSUE TITLE
Docs issue report from "api/module_engine_conversion_modelconsumable-ModelConsumable.html"

### ISSUE THREAD

**Issue by timblack1** [ckeditor/ckeditor5#12677]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_modelconsumable-ModelConsumable.html#function-consume

### Project version

35.2.1

### Is there anything else you would like to add?

The sentence "Have you spotted an outdated information?" would read more smoothly in English if the word "an" was omitted, like this:  "Have you spotted outdated information?"

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by pomek** [comment]
We fixed the wrong sentence in our documentation builder. It should be released soon.
