### ISSUE TITLE
Code examples for the bind function are mysterious 

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1271]
Code examples for the [bind function](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_observablemixin-ObservableMixin.html#function-bind) are very academic.

```js
A.bind( 'a' ).to( B );
A.bind( 'a' ).to( B, 'b' );
A.bind( 'a', 'b' ).to( B, 'c', 'd' );
A.bind( 'a' ).to( B, 'b', C, 'd', ( b, d ) => b + d );
```

Some real-world examples and some descriptions, explanations of the results would be useful IMO.

**Comment by Reinmar** [comment]
Totally agree. The examples should showcase some understandable scenarios and explain what happens in those cases. A pure code (with no explanation) is hard to understand in this case.
