### ISSUE TITLE
ERROR: unknown Statement of type "ForOfStatement"

### ISSUE THREAD

**Issue by shymkovayu** [ckeditor/ckeditor5#12711]
## 📝 Provide detailed reproduction steps (if any)

1. Build CKEditor from source in a separate repo
2. Release as an NPM package
3. Add to another project as dependency

### ✔️ Expected result

Project builds.

### ❌ Actual result

`Error: dist/ckeditor.js: unknown Statement of type "ForOfStatement"`

### ❓ Possible solution

?

## 📃 Other details

* CKEditor: 35.2.1
* @babel/core: 7.19.3
* @babel/generator: 7.19.5
* Node: 16.13.0

---

Hello! I'm trying to build CKEditor from source and use it my main project. It builds separately just fine, but the main project build fails when I'm using it. Could you please help me understand which way should I look?

**Comment by mabryl** [comment]
Hi shymkovayu,

Thank you for bringing this issue to our attention. I tried recreating it on my end but, unfortunately, I wasn't able to do it.

Could you provide us with more information regarding this issue? Particularly, could you share your editor and babel configs?

I did some googling regarding the error that you're getting and to me it seems like it might be an issue related to your babel configuration. Maybe you'll find these GitHub threads useful in your debugging:

facebook/regenerator#229

parcel-bundler/parcel#1269

Please let me know whether you found this response useful.

**Comment by shymkovayu** [comment]
@mabryl Thank you for the reply! Adding `IE 11` to the `.browserlistrc` helped to resolve this issue.

**Comment by fuze210699** [comment]
Thanks to @mabryl and @shymkovayu  for adding `IE 11` to the `.browserlistrc`. This actually resolved the issue.
