### ISSUE TITLE
Multiple editors on the same page

### ISSUE THREAD

**Issue by jerauf** [ckeditor/ckeditor5#1272]
I'm trying to use multiple editors on the same page but I don't see anything in the documentation to address that.

How can I do that?

**Comment by Reinmar** [comment]
Hi! Do you mean multiple editors of the same type? For example, a couple of classic editors?

Or, do you mean multiple editor types (e.g. classic, inline, balloon) used on one page?

**Comment by Reinmar** [comment]
> Or, do you mean multiple editor types (e.g. classic, inline, balloon) used on one page?

This is covered in https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors (note: these are nightly docs; this guide was not yet published in the official documentation at the moment of writing this comment)

**Comment by jerauf** [comment]
Sorry. I mean 2 classic editors.

**Comment by Reinmar** [comment]
Ah, then it's a matter of using `ClassicEditor.create()` multiple times. Like this:

```js

<div id="editor1">
	<h2>Editor 1</h2>
</div>

<div id="editor2">
	<h2>Editor 2</h2>
</div>

<script src="../build/ckeditor.js"></script>
<script>
	ClassicEditor.create( document.querySelector( '#editor1' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );

	ClassicEditor.create( document.querySelector( '#editor2' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
```

**Comment by jerauf** [comment]
Got it. Thank you for the fast response.

**Comment by robertunyx** [comment]
@Reinmar Is this also the case with DecoupledEditor? Can I stack two Decoupled Editors into a single page?

**Comment by ysct** [comment]
@Reinmar Is it possible to execute the above code for DecoupledEditor multiple times, while making sure they're all sharing the same `editor.ui.view.toolbar.element`? 

Note: MultirootEditor doesn't fit my use case, as it calls Editor.create() once by passing an object as the first parameter, whereas I need to be able to call Editor.create() multiple times as I'm implementing a React Component.

**Comment by martijnpieters** [comment]
@ysct We had the same requirements as you:
- One toolbar in the UI
- Multiple editing fields on one page
- Dynamic addition of fields
- Being able to use default builds of CKEditor (less maintenance on our side)

We've solved it by using a context that keeps zero or one toolbar elements. When an editor receives focus, the toolbar will be set in the context and can be rendered anywhere under the `<TextEditorProvider>`.

In this gist you can find our React components: https://gist.github.com/martijnpieters/92e16ccfc9071f408140f4dba55f133a, which can be used like this:

```tsx
<TextEditorProvider>
  <h1>External toolbar</h1>
  <TextEditorToolbar />
  <h2>First editor with external toolbar</h2>
  <TextEditorContent
    editor={DecoupledEditor}
    config={config}
    data={text}
    onChange={(event, editor) => {
      const data = editor.getData();

      console.log(data);
    }}
  />
  <h2>Second editor with external toolbar</h2>
  <TextEditorContent
    editor={DecoupledEditor}
    config={config}
    data={text}
    onChange={(event, editor) => {
      const data = editor.getData();

      console.log(data);
    }}
  />
</TextEditorProvider>
```

**Comment by EricCoetzee** [comment]
/*HTML CODE*/

/*
<script src="https://cdn.ckeditor.com/ckeditor5/18.0.0/classic/ckeditor.js"></script>

<p><textarea  placeholder="Description"  id="body1" name="body"></textarea></p>
<p><textarea  placeholder="Description"  id="body2" name="body"></textarea></p>
<p><textarea  placeholder="Description"  id="body3" name="body"></textarea></p>
*/

document.addEventListener("DOMContentLoaded", function(event) { 
var numb = 0;
  do {
    ClassicEditor
    .create( document.querySelector( '#body'+ numb ), {
      removePlugins: [ 'insertImage', 'insertMedia', 'Link', 'blockQuote' ],
      toolbar: [ 'Heading', 'bold', 'italic', 'bulletedList', 'numberedList',  ]
    } ) 
    .catch( error => {
      console.error( error );
    } )
    numb++;
  }
  while (numb < 3);
});

**Comment by sochan-tenten** [comment]
@Reinmar
Hi, I'm also using Decoupled Editors and gonna locate another Decoupled Editors on the same page
```Javascript
DecoupledEditor
  .create( document.querySelector( '.document-editor__editable' ), {
    plugins: plugins_op,
    toolbar: {
      items: toolbar_items_op
    },
    table: {
      contentToolbar: table_contentToolbar_op
    },
    image: {
      resizeOptions:image_resizeOptions_op,
      styles: image_styles_op,
      toolbar: image_toolbar_op
    },
    fontFamily: {
      options: fontFamily_options_op
    }
  } )
  .then( editor => {
    const toolbarContainer = document.querySelector( '.document-editor__toolbar' );
    toolbarContainer.appendChild( editor.ui.view.toolbar.element );
    window.editor = editor;
  } )
  .catch( error => {
    console.error( error );
  } );
```
And wonder how can I adopt the multiple method above in my case. Sorry for bothering you.
