### ISSUE TITLE
Support for counting two byte characters

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#12721]
## 📝 Provide a description of the improvement

Currently the word count plugin counts two byte asian characters as a one character. It is requested by some users, to actually count it as 2.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I'm unsure whether two-byte characters should be counted by us as two characters. Our word count is an end user feature. While technically these may be two characters, and may need to be treated as two characters by a developer/system, the user will (most likely) still see this as single character.

**Comment by Reinmar** [comment]
Twitter:

![](https://user-images.githubusercontent.com/156149/203512647-12205e87-3eb1-4a82-bfe4-20a53f09c227.png)

Word:

![](https://user-images.githubusercontent.com/156149/203512726-ca0a99c6-7f84-4c75-8595-dbb3f107c67c.png)

I think we should follow Word in this case.

**Comment by Reinmar** [comment]
CKE5 for reference:

![](https://user-images.githubusercontent.com/156149/203513160-22f4e396-5d58-4e78-ba5b-4289f22740c6.png)

So, in fact, we've got a different issue – these should be apparently 2 words. We count it as one.
