### ISSUE TITLE
New list plugin doesn't convert subsequent lists with a different type properly (aka resetting numbering, splitting lists)

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#12738]
## 📝 Provide detailed reproduction steps (if any)

For context this is a simplified markup produced by MS Word.

1.  Copy following HTML to your clipboard:

```html
<p style="margin-top: 0px; margin-bottom: 0px; line-height: 1">foo</p>

<p style="margin-top: 0px; margin-bottom: 0px; margin-left: 24px; line-height: 1">&nbsp;</p>
<ol style="list-style-type: decimal">
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar</p>
    </li>
</ol>

<p style="margin-top: 0px; margin-bottom: 10.67px; margin-left: 24px; line-height: 1.05">&nbsp;</p>
<ol style="list-style-type: lower-latin">
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar</p>
    </li>
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar</p>
    </li>
</ol>
<ol start="2" style="list-style-type: decimal">
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">Decimal list item again</p>
    </li>
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">Decimal list item again
        </p>
    </li>
</ol>

<p style="margin-top: 0px; margin-bottom: 10.67px; margin-left: 48px; line-height: 1.05">&nbsp;</p>
<ol style="list-style-type: lower-latin">
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar</p>
    </li>
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar</p>
    </li>
</ol>
<ul style="list-style-type: disc">
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar</p>
    </li>
</ul>
<ol start="3" style="list-style-type: lower-latin">
    <li>

        <p style="margin-top: 0px; margin-bottom: 10.67px; line-height: 1.05">foobar
        </p>
    </li>
</ol>
```

1.  Open a demo that has new list (a.k.a. document list) implementation in it. [Import from Word guide](https://ckeditor.com/docs/ckeditor5/latest/features/import-word/import-word.html) is a good example.
2.  Open js dev console.
3.  Execute ``editor.setData( `<copiedMarkupHere>` )``.

### ✔️ Expected result

List with two "Decimal list item again" items should be a numbered list.

![](https://user-images.githubusercontent.com/5353898/198069987-e3d2614a-55e4-48d0-8506-740fbdf75f86.png)

### ❌ Actual result

List goes on as alphanum list.

![](https://user-images.githubusercontent.com/5353898/198070238-e92efedb-45a7-443a-bada-4f04a3a4eb84.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
There's a chance we're running here into a limitation of the current implementation – that it does not allow having two subsequent lists of the same type.

@niegowski or @arkflpc, could you confirm that I'm right? Or perhaps this is indeed a bug (as opposed to a missing feature)?

**Comment by niegowski** [comment]
> There's a chance we're running here into a limitation of the current implementation – that it does not allow having two subsequent lists of the same type.

You are right. We even implemented a post-fixer to make sure this would not break in RTC: [https://github.com/ckeditor/ckeditor5/blob/13d98de12b265f25eb1cc82c4020c013b207564c/packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.js#L150-L151](https://github.com/ckeditor/ckeditor5/blob/13d98de12b265f25eb1cc82c4020c013b207564c/packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.js#L150-L151)

I could imagine a case where one user is modifying a style of the list and some other user is at the same time adding a new list item. 

This probably could be someday resolved by adding `listId` attribute to mark strict boundaries for lists, but currently, it's a missing feature.

**Comment by jacekbogdanski** [comment]
Just theoretically, how feasible would be that fix if IFW would mark lists with an additional attribute? Like a unique ID or something, so it's possible to distinguish different lists?

**Comment by niegowski** [comment]
> Just theoretically, how feasible would be that fix if IFW would mark lists with an additional attribute? Like a unique ID or something, so it's possible to distinguish different lists? Would that help?

It's not the input problem, it's internally stored in the model (in an input-compatible way) and fixed by the post-fixer.

**Comment by Reinmar** [comment]
Very old DUP of this ticket: #3000.

**Comment by Witoso** [comment]
## Scope

### Enablement

How this should be enabled?

- DocumentList configuration?
- Paste from Office configuration?
- New plugin?

### ul's

Two `ul`’s next to each other

```html
<ul>
	<li>LOREM</li>
	<li>IPSUM</li>
</ul>
<ul>
	<li>LOREM</li>
	<li>IPSUM</li>
</ul>
```

**Outcome**: This should be merged (as it works now).

---

Two `ul`’s next to each other, different styles (only `list-style-type:` or more styles?)

```html
<ul style="list-style-type: square;">
	<li>LOREM</li>
	<li>IPSUM</li>
</ul>
<ul style="list-style-type: disc;">
	<li>LOREM</li>
	<li>IPSUM</li>
</ul>
```

**Outcome**: This should ********not******** be merged.

### ol's

Two `ol`’s next to each other

```html
<ol>
	<li>LOREM</li>
	<li>IPSUM</li>
</ol>
<ol>
	<li>LOREM</li>
	<li>IPSUM</li>
</ol>
```

**Outcome**: This should **not** be merged.

---

Two `ol`’s next to each other, different styles (only `list-style-type:` or more styles?)

```html
<ol>
	<li>LOREM</li>
	<li>IPSUM</li>
</ol>
<ol style="list-style-type:decimal-leading-zero;">
	<li>LOREM</li>
	<li>IPSUM</li>
</ol>
```

**Outcome**: This should **not** be merged.

## TBD

- How this should be enabled?
- What about start index?
    - Two `ol`’s next to each other with start index
    
    ```html
    <ol>
    	<li>LOREM</li>
    	<li>IPSUM</li>
    </ol>
    <ol start="2">
    	<li>LOREM</li>
    	<li>IPSUM</li>
    </ol>
    ```
    
    **Outcome**: This could be merged.
