### ISSUE TITLE
Manual test server does not watch for file changes

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#12735]
## 📝 Provide detailed reproduction steps (if any)

1. Run manual test server for a specified package, e.g. `yarn run manual -f alignment`.
2. Change something in the source code in the `ckeditor5-alignment` package to check if manual tests are re-built.

### ✔️ Expected result

Manual tests are re-built.

### ❌ Actual result

Manual tests are NOT re-built after the change.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
See: https://lightrun.com/answers/webpack-webpack-watching-symlinks-doesnt-work-in-dev-mode

The following change helps.

```
watchOptions: {
	aggregateTimeout: 500,
	followSymlinks: true
},
```

Note: The error can be reproduced only when links packages (`yarn link`).

**Comment by pomek** [comment]
I found a test that is ignored even if the webpack configuration contains the proposed change. So, verify whether the following command: `yarn run manual -f adapter-ckfinder` recompiles a test after updating its sources.

PS: The following watch options do not work for me either:

```
poll: true,
ignored: /node_modules/
```

PS 2: I use macOS@13.

**Comment by przemyslaw-zan** [comment]
Notes so far:
- watcher seems to work rather randomly: when running `yarn run manual -f alignment` several times without any webpack config changes in between, the watcher sometimes works, and sometimes does not.
  - `followSymlinks: true` fixes this issue
- when running `yarn run manual -f adapter-ckfinder` the watcher does not work, except for one specific file: modying `packages/ckeditor5-adapter-ckfinder/tests/manual/uploadadapter.html` does activate the watcher

**Comment by psmyrek** [comment]
After the manual tests have been compiled and the server has started, the watcher works fine. The problem is that sometimes the re-compilation fails and throws this error:

```
Error: The loaded module contains errors
    at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\dependencies\LoaderPlugin.js:109:11
    at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\Compilation.js:1935:5
    at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\util\AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (D:\Projekty\ckeditor5-dev\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._handleResult (D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\util\AsyncQueue.js:322:21)
    at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\util\AsyncQueue.js:305:11
    at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\Compilation.js:1396:15
    at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (D:\Projekty\ckeditor5-dev\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.store (D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\Cache.js:107:20)".
```

The log above can be obtained by adding to `WebpackNotifierPlugin#apply()` in `ckeditor5-dev-tests` a new hook:
```js
compiler.hooks.failed.tap( this.constructor.name, error => {
    const inspect = require( 'util' ).inspect;

    this.log.info( inspect( error ) );
} );
```

**Comment by psmyrek** [comment]
I tried to get a more specific description of the error and the name of the module that failed. I added some additional logs to the [webpack source](https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/lib/dependencies/LoaderPlugin.js#L107-L111):

```js
if (referencedModule.getNumberOfErrors() > 0) {
    console.log(referencedModule.getErrors());
    console.log(referencedModule.toString());

    return callback(
        new Error("The loaded module contains errors")
    );
}
```
Then, when the re-compilation error appeared, in the logs I had hundreds of entries like this:

```
Module[5185: D:\Projekty\ckeditor5\node_modules\ts-loader\dist\stringify-loader.js!D:\Projekty\ckeditor5-dev\packages\ckeditor5-dev-webpack-plugin\lib\translatesourceloader.js?{}!D:\Projekty\ckeditor5\packages\ckeditor5-engine\src\view\typecheckable.ts]
[
  ModuleBuildError: Module build failed (from ../ckeditor5-dev/packages/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js):
  TypeError: this.query.translateSource is not a function
      at Object.translateSourceLoader (D:\Projekty\ckeditor5-dev\packages\ckeditor5-dev-webpack-plugin\lib\translatesourceloader.js:16:20)
      at processResult (D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\NormalModule.js:758:19)
      at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\NormalModule.js:860:5
      at D:\Projekty\ckeditor5-dev\node_modules\loader-runner\lib\LoaderRunner.js:400:11
      at D:\Projekty\ckeditor5-dev\node_modules\loader-runner\lib\LoaderRunner.js:252:18
      at runSyncOrAsync (D:\Projekty\ckeditor5-dev\node_modules\loader-runner\lib\LoaderRunner.js:156:3)
      at iterateNormalLoaders (D:\Projekty\ckeditor5-dev\node_modules\loader-runner\lib\LoaderRunner.js:251:2)
      at D:\Projekty\ckeditor5-dev\node_modules\loader-runner\lib\LoaderRunner.js:224:4
      at D:\Projekty\ckeditor5-dev\node_modules\webpack\lib\NormalModule.js:834:15
      at eval (eval at create (D:\Projekty\ckeditor5-dev\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
]
```

Only our TypeScript modules are listed here.
It seems that the compilation error is related to our `TranslateSource` loader.
