### ISSUE TITLE
[IME] Comments only mode removes selected content

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#12739]
## 📝 Provide detailed reproduction steps (if any)

1. Select some text in comments only mode
2. start composing some text (IME)
3. accept composition

### ✔️ Expected result

The text should be restored to the state before composition.

### ❌ Actual result

The selected text is removed.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Fixed with #12740
