### ISSUE TITLE
Docs issue report from "framework/guides/plugins/creating-simple-plugin-timestamp.html"

### ISSUE THREAD

**Issue by hjy1210** [ckeditor/ckeditor5#12744]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/creating-simple-plugin-timestamp.html

### Project version

35.2.1

### Is the information outdated? How?

```
class Timestamp extends Plugin {
    init() {
        const editor = this.editor;
.........
```
I just wonder about `this.editor`, 
1. What is `this`?
2. Where come from the property name `editor` of `this`?

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by apadol-cksource** [comment]
We will add link to API reference of [Plugin](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_plugin-Plugin.html) The mechanism presented in the guide is using basic JS inheritance.
