### ISSUE TITLE
Numbered/Bulleted lists are not enabled for use in Track changes if document lists are used

### ISSUE THREAD

**Issue by glynam1** [ckeditor/ckeditor5#12754]
1. Create an environment with track changes and document lists enabled
2. Toggle on track changes
3. Note that numbered and bulleted lists are not enabled in the toolbar

### ✔️ Expected result
These plugins are enabled and usable in Track Changes

### ❌ Actual result

Numbered and bullet points are unusable in Track changes mode

### ❓ Possible solution
Document lists should have the same integration with track changes as regular list.js does

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi @glynam1, sorry for the late reply. In latest releases ([35.3.0](https://github.com/ckeditor/ckeditor5/releases/tag/v35.3.0) and [35.4.0](https://github.com/ckeditor/ckeditor5/releases/tag/v35.4.0)) we added integration for document lists in track changes. 

You can update your editor to unblock document lists in track changes mode. However, please keep in mind that there are still a few follow-ups to make it behave 100% like without track changes and currently we cannot promise ETA for this.
