### ISSUE TITLE
Jumping empty Import from Word demo

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12750]
### Steps:

1.  [https://ckeditor.com/docs/ckeditor5/latest/features/import-word/import-word.html](https://ckeditor.com/docs/ckeditor5/latest/features/import-word/import-word.html)
2.  Focus editor
3.  Slowly scroll down

The editor starts violently changing width when toolbar gets detached. The visual bug is present since docs version 35.2.1.

https://user-images.githubusercontent.com/66953380/198242198-b647707d-c0cf-4d43-95c3-6aef964a857d.mov

**Comment by pszczesniak** [comment]
Adding `width: 100%` to `.live-snippet .ck.ck-editor {...` eliminates that issue.

**Comment by godai78** [comment]
@pszczesniak, like this:

![](https://user-images.githubusercontent.com/68123541/198263202-343ea5e7-aa7c-4863-be1b-554b9d0a700c.png)

**Comment by pszczesniak** [comment]
@godai78 exactly :+1:

**Comment by godai78** [comment]
I'm testing it right now.

**Comment by godai78** [comment]
Fixed in cksource/ckeditor5-internal#2147
