### ISSUE TITLE
Problems with Enter Chinese dots

### ISSUE THREAD

**Issue by chaohui2** [ckeditor/ckeditor5#12762]
## 📝 Provide detailed reproduction steps (if any)

1. Open [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) in browser 

2. Clear editor content

3. Switch the input method to Microsoft Pinyin

4. Enter a "。" (Chinese dot)

### ✔️ Expected result

_What is the expected result of the above steps?_
The editor content is "。" 

### ❌ Actual result

_What is the actual result of the above steps?_
The editor content is "。。" 
(Verified on at least three computers)

## 📃 Other details

* Browser: Microsoft Edge 106.0.1370.52 
* OS: Windows 11 21H2
* First affected CKEditor version: 10.0.0

https://user-images.githubusercontent.com/17821872/198577151-fb5b5125-515d-4e6d-a4e6-2f03018aca6a.mp4

https://user-images.githubusercontent.com/17821872/198578053-ade15079-4cc9-4d29-abaa-eaf1a291e939.mp4

**Comment by FilipTokarski** [comment]
Hi @chaohui2, sorry for the late reply. [In version 35.3.0 we introduced enhancements and fixes for IME](https://github.com/ckeditor/ckeditor5/releases/tag/v35.3.0), so this bug should be already fixed. Can you confirm that you no longer reproduce it?

**Comment by chaohui2** [comment]
@FilipTokarski The issue has been resolved.
