### ISSUE TITLE
[TS] Remove `I` type parameter from `Collection`

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#12763]
Currently the `Collection` class has two generic parameters: `T` - item type and `I` - its id property name. It was inspired by [community types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ckeditor__ckeditor5-utils/src/collection.d.ts). However, it seems redundant and overthought. I'd remove it.

Part of #12027.

**Comment by Reinmar** [comment]
Scope:

*   Remove the param from the class definition.
*   Review existing usage.
*   Review existing Collection documentation (API docs).
