### ISSUE TITLE
Docs issue report from "features/collaboration/track-changes/track-changes.html"

### ISSUE THREAD

**Issue by timblack1** [ckeditor/ckeditor5#12768]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html

### Project version

35.2.1

### Is there anything else you would like to add?

The following two sentences:

"After you managed to run track changes feature in your editor, you might want to learn more about the feature. Find oud how it works, how it can be configured, customized, and extended, to fit your application the best way possible."

could be improved as follows:

"After you run the track changes feature in your editor, you may want to learn more about the feature. Find out below how it works, how it can be configured, customized, and extended, to fit your application the best way possible."

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by godai78** [comment]
Thanks for the suggestion, incorporated it into the guide.
