### ISSUE TITLE
Write file containing PHP

### ISSUE THREAD

**Issue by DubStepMad** [ckeditor/ckeditor5#1276]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

4.10.1

Current setup, I have file contents displayed in the editor but when writing the file after editing, it comments all the PHP.

I need some help resolving this

**Comment by Reinmar** [comment]
Hi! This is CKEditor 5's bug tracker. For CKEditor 4 issue tracker see http://github.com/ckeditor/ckeditor-dev
