### ISSUE TITLE
Docs issue report from "features/style.html": Extend "see also" by Headings Feature

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#12772]
### Origin URL

https://ckeditor.com/docs/ckeditor5/35.2.1/features/style.html

### Project version

35.2.1

### Is there something missing in the guide? What is it?

The Related Features section has references to alternative features/plugins to consider instead of using the Styles Feature:

* [Basic text styles](https://ckeditor.com/docs/ckeditor5/35.2.1/features/basic-styles.html)
* [Font styles](https://ckeditor.com/docs/ckeditor5/35.2.1/features/font.html)
* [Remove format](https://ckeditor.com/docs/ckeditor5/35.2.1/features/remove-format.html)
* [General HTML support](https://ckeditor.com/docs/ckeditor5/35.2.1/features/general-html-support.html)

In addition to that, I think, the Headings Feature should be referenced, too:

* [Headings](https://ckeditor.com/docs/ckeditor5/35.2.1/features/headings.html)

Especially the section [Configuring custom heading elements](https://ckeditor.com/docs/ckeditor5/35.2.1/features/headings.html#configuring-custom-heading-elements) is relevant here, as it provides a similar feature of adding custom classes to headings.

### Is there anything else you would like to add?

It would be good having a good overview of features and when to use which, or which is the recommended plugin to use for several use-cases.

The overview should also provide some warnings on possible misconfigurations due to feature clashes:

```javascript
style: {
  definitions: [
    {
      name: 'Fancy',
      element: 'h2',
      classes: [ 'fancy' ],
    },
  ],
},
heading: {
  options: [
    { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
    { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
    { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
    {
      model: 'headingFancy',
      view: { name: 'h2', classes: 'fancy' },
      title: 'Heading 2 (fancy)',
      class: 'ck-heading_heading2_fancy',
      converterPriority: 'high'
    }
 ]
},
```

This will provide a collision with hard to understand effects:

* **Styles Feature:** You may mark `<h2>` as being of fancy style.

* **Headings Feature:** You may mark a block as being `<h2 class="fancy">` via headings features.

* Both will be represented in data view as:

  ```xml
  <h2 class="fancy">Fancy</h2>
  ```

* **Apply Styles While Editing:** Directly after editing, as the model representation is different, either the Styles combo will show "Fancy" or the headings-combo will show active fancy heading.

* **Set Data:** But if this ambiguous state is loaded from data (e.g., via source editing), one of them will "take the lead", which (in my experiments) is the Styles feature.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by godai78** [comment]
@oleq - can you please confirm this clash of styles thing works like this? I intend to mention that in the docs.

**Comment by godai78** [comment]
The full list is not very full at the moment, I see. How about we just mention it in the Known Issues section, for now, exactly voicing that "this feature may not respect styles applied by other features?
