### ISSUE TITLE
Nested lists errors (wrong list-style-type and unable to change)

### ISSUE THREAD

**Issue by gnat42** [ckeditor/ckeditor5#12785]
## 📝 Provide detailed reproduction steps (if any)

1. When loading the editor with nested lists, sub-lists are not able to be to be changed and sometimes the numbers are not incrementing

What is interesting to note is that building an identical list is possible within the editor itself that works properly but even feeding that markup back to the editor does not result in a 

For example I provided the following markup

```
<p>list-i</p>
<ol style="list-style-type: lower-roman;" class="list-i">
    <li>Should be i</li>
    <li>
        Should be ii
        <ol style="list-style-type: lower-alpha;" class="list-1"><li>Should be a</li></ol>
    </li>
</ol>

<p>list-1</p>
<ol style="list-style-type: decimal;" class="list-1">
    <li>Should be 1</li>
    <li>Should be 2
        <ol style="list-style-type: lower-roman;">
            <li>Should be i</li>
        </ol>
    </li>
</ol>
```

### ✔️ Expected result

Sub lists that respect the style="list-style-type: X" and users are able to change them via the list editor plugin/features
![Screenshot from 2022-11-02 13-51-59](https://user-images.githubusercontent.com/325591/199589178-7eefefa3-cc7a-4980-a9ff-07f687d4c432.png)

I should also be able to click on any of the sublist items and change their formatting. Currently I can click to select something else but it doesn't actually change anything.

As an aside, with the 'correct' results built from scratch in the editor if I `editor.getData()` in the browser I get the following content

```
<ol>
    <li>First
        <ol style="list-style-type:lower-roman;">
            <li>first roman
                <ol style="list-style-type:lower-latin;">
                    <li>first alpha</li>
                </ol>
            </li>
        </ol>
    </li>
</ol>
```

The markup may not be 100% the same as I've been playing around with some of these so the issue is specifically that loading an editor with markup with sub-lists doesn't work.

### ❌ Actual result

I see the following:

![Screenshot from 2022-11-02 13-49-25](https://user-images.githubusercontent.com/325591/199588763-ac76c631-cfd9-443e-9a34-5e8474510004.png)

## 📃 Other details

* Browser: Chrome
* OS: Fedora 36 / Mac OS X

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Note: this happens when using general HTML support plugin together with list properties.

**Comment by Reinmar** [comment]
We tested GHS + [Document lists](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html) and all worked correctly in that setup.

The problem reported in this ticket (GHS + List) is that the old List feature does not support GHS. Trying to use GHS to extend lists will result in weird issues, like the one seen here.

So, the recommended solution is to migrate to [Document lists](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html).

**Comment by Reinmar** [comment]
See: #14767. We're sunsetting the old lists implementation.
