### ISSUE TITLE
Nested upcasting issues with image captions

### ISSUE THREAD

**Issue by theodoreb** [ckeditor/ckeditor5#12797]
## 📝 Provide detailed reproduction steps (if any)

1. use data-caption to store some text
2. Switch to source editing and add a `<br>` to the caption text
3. Click on the source button to switch back to wysiwyg

### ✔️ Expected result

Switch back to the WYSIWYG and see a newline in the caption text.

### ❌ Actual result

JS Crash prevent from going back to the WYSIWYG editing.

### ❓ Possible solution

No idea unfortunately

## 📃 Other details

Reproduced in a failing test at #12796

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Unfortunately, it is not possible to fix this on our side. You need to update your custom converter for `data-caption` upcast in the same way as I updated the test: #12798
