### ISSUE TITLE
Docs issue report from "features/toolbar/toolbar.html"

### ISSUE THREAD

**Issue by dil-it21** [ckeditor/ckeditor5#12814]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/toolbar.html#listing-available-items

### Project version

35.3.0

### Is the information outdated? How?

Cannot read properties of undefined (reading 'componentFactory')

### Is there something missing in the guide? What is it?

In the documentation they recommend me to use this to get the complete list of the items for the editor toolbar:

Array.from( editor.ui.componentFactory.names() );

But when I use it, it gives me this error:

Cannot read properties of undefined (reading 'componentFactory')

### User agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36

**Comment by Reinmar** [comment]
![](https://user-images.githubusercontent.com/156149/200511879-523355cd-6b7e-4d46-b032-02d03a355932.png)

Works for me in [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) where the `editor` instance is exposed as a global variable.

Could you verify what's under your `editor` variable?
