### ISSUE TITLE
[Docs] Tutorials do not reflect "new" schema generic items.

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#12810]
## 📝 Provide a description of requested docs changes

https://github.com/ckeditor/ckeditor5/blob/4940e901e89e996895a6211b5d13fa510b2ceb62/docs/framework/guides/tutorials/implementing-a-block-widget.md?plain=1#L331-L337

should be:
```js
schema.register( 'simpleBox', {
	inheritAllFrom: '$blockObject'
} );
```

https://github.com/ckeditor/ckeditor5/blob/4940e901e89e996895a6211b5d13fa510b2ceb62/docs/framework/guides/tutorials/implementing-an-inline-widget.md?plain=1#L269-L284

should be:
```js
schema.register( 'placeholder', {
	inheritAllFrom: '$inlineObject',
	// The placeholder can have many types, like date, name, surname, etc:
	allowAttributes: [ 'name' ]
} );
```

(note that the same snippet is repeated multiple times on those pages).

**Comment by Reinmar** [comment]
@niegowski I think it'd need to be handled in the core team for now.
