### ISSUE TITLE
Embedded media should be reflected in the markdown output

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#1281]
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 💻 Version of CKEditor

`11.0.1`

## 📋 Steps to reproduce

1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/markdown.html.
2. Paste YouTube link inside the editor.

![image](https://user-images.githubusercontent.com/1061942/46416842-aecba100-c728-11e8-875a-bce1c9424ee3.png)

## ✅ Expected result

Link gets auto-embedded and embedded media is reflected in the markdown output.

## ❎ Actual result

Link gets auto-embedded but embedded media is missing in the markdown output.

## 📃 Other details that might be useful

Tested on Chrome and Firefox.

**Comment by Reinmar** [comment]
The Markdown GFM data processor is an experimental feature and we do not plan to work on extending it. Especially that neither CM nor MD support such features as media embeds. We'd have to generate HTML for that and this a bigger change and we'd have to start from resolving https://github.com/ckeditor/ckeditor5-markdown-gfm/issues/16 first.
