### ISSUE TITLE
With GHS disabled table's styles are moved to figure's styles

### ISSUE THREAD

**Issue by szewczukk** [ckeditor/ckeditor5#12812]
## 📝 Provide detailed reproduction steps (if any)

1. With GHS disabled, enter Source mode and paste the following code:
```html
<figure class="table" style="width:75%">
    <table style="width:100%">
        <tbody>
            <tr>
                <td>
                    A cell
                </td>
            </tr>
        </tbody>
    </table>
</figure>
```

2. Exit Source mode, the content is parsed to:
<img width="916" alt="Screenshot 2022-11-07 at 16 28 18" src="https://user-images.githubusercontent.com/25493355/200348893-ccb09ed3-5961-4f0e-b748-3d5cd1fbfb0f.png">

And its source is:

<img width="911" alt="Screenshot 2022-11-07 at 16 28 25" src="https://user-images.githubusercontent.com/25493355/200348926-ea0236b3-faf2-4d5a-884b-55c2bf6d83fc.png">

### ✔️ Expected result

The figure's width should be set to `75%`.

### ❌ Actual result

The figure's width is set to `100%`.

## 📃 Other details

This issue blocks a fix for a IFW bug.

**Comment by Reinmar** [comment]
We're probably copying this style from the `<table>` element, regardless of whether it's already set on the `<figure>`.

It'd most likely make more sense to only copy it if it's not present there already. Might be a slightly better heurstic.

Would that resolve this issue for you, @szewczukk ?

**Comment by szewczukk** [comment]
I think so @Reinmar, thanks!
