### ISSUE TITLE
CSS property 'ck-overflow-visible' causing editor to overlap in Firefox

### ISSUE THREAD

**Issue by GowrishankarNittala** [ckeditor/ckeditor5#12816]
## 📝 Provide detailed reproduction steps (if any)

We have configured 2 CKE fields side by side in a PanelFormLayout component in Oracle ADF application. 

![image](https://user-images.githubusercontent.com/37432770/200564084-c9a48ff7-0c3e-4d4a-b47e-ecb4632c1f39.png)

If we add new lines to either of the two editors then that is overlapping the other.

![image](https://user-images.githubusercontent.com/37432770/200564312-c332dfcb-c234-4cab-8510-130f9dd134e5.png)

This behavior is seen in Firefox browser and things are working fine on Chrome.

The issue seems to be with the CSS property **.ck-overflow-visible{overflow: visible !important;}**.

### ✔️ Expected result

The editors should not get overlapped as we add new lines.

### ❌ Actual result

Behavior as seen in Firefox.

![image](https://user-images.githubusercontent.com/37432770/200563035-40bc21d3-5623-4d69-b9d2-340d470b8693.png)

![image](https://user-images.githubusercontent.com/37432770/200563072-686f81fd-eaa5-4656-99eb-c833dc9a3017.png)

### ❓ Possible solution

The property **.ck-overflow-visible{overflow: visible !important;}** seems to be the root cause. Removing **!important** is disabling overflow: visible property on .ck-overflow-visible and is overridden by overflow: hidden property on the parent component af_panelFormLayout and things are working fine.

Below is the CSS for both the components:

```
.af_panelFormLayout.p_AFPanelSizeMd .AFPanelFormLayoutContentCell {
  box-sizing: border-box;
  overflow: hidden;
  text-overflow: ellipsis;
  align-self: center;
  height: auto;
  width: calc(100% - 145px);
  padding-left: 8px;
  white-space: noWrap;
}
.ck-overflow-visible {
  overflow: visible !important;
}
```

Initially **overflow: hidden** is overridden by **overflow: visible !important**. When removing **!important** then **overflow: hidden** is enabled and the overlapping does not happen. Why is **overflow: visible** causing issue on Firefox?

1. With **!important**

![image](https://user-images.githubusercontent.com/37432770/200563358-2bdfbe9b-9a06-4047-bf8a-fde54be98634.png)

2. Without **!important**

![image](https://user-images.githubusercontent.com/37432770/200563400-030d8e8e-275d-418d-90c3-c1fc50ce05f1.png)
 

## 📃 Other details

* Browser: Firefox
* First affected CKEditor version: 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Thank you for your bug report!

`.ck-overflow-visible` is not a core CSS class of CKEditor 5. It is brought by some (?) 3rd-party integration or a plugin making it impossible for the CKEditor team to help you out. I recommend you contact maintainers of that code for further assistance.
