### ISSUE TITLE
TypeError: n is not iterable

### ISSUE THREAD

**Issue by signalpoint** [ckeditor/ckeditor5#12817]
When trying the [Quick start CKEditor 5 Documentation](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html) inside my Single Page Application (SPA), I kept running into the following JavaScript Console error:

```
    TypeError: n is not iterable
    at new Au (focuscycler.js:120:30)
    at new Mu (toolbarview.js:192:23)
    at new Tg (classiceditoruiview.js:49:18)
    at new Sg (classiceditor.js:80:16)
    at new eC (ckeditor.js:36:16)
    at classiceditor.js:204:19
    at new Promise (<anonymous>)
    at eC.create (classiceditor.js:203:10)
```

I tried researching/debugging the issue for a couple of hours yesterday, and then decided to skip it for now. Today, I moved onto the Google Maps implementation of my app and noticed they threw this JavaScript Console error:

```
This site adds property `foo` to Object.prototype. Extending Object.prototype breaks JavaScript for..in loops, which are used heavily in Google Maps JavaScript API v3.
```

That was true, I had added an e.g. `foo` property to the JavaScript `Object` prototype:

```
Object.prototype.foo = function() {
  // ...
};
```

I went ahead and removed `foo` from the prototype, and both Google Maps and **CK Editor 5 started to work properly**!

It would be nice if I could keep `foo`, but I'm not surprised it had unintended side effects. I feel lucky that Google Maps told me about it though.

Feel free to close this issue, I just wanted to document it in the hopes of helping others (and my future self).

## 📝 Reproduction steps

1. Add property `foo` to JavaScript `Object.prototype`
2. Call `ClassicEditor.create(...)`

### ✔️ Expected result

The classic editor is shown.

### ❌ Actual result

The classic editor does not show, and the `TypeError: n is not iterable` console error is thrown.

### ❓ Possible solution

Removed my e.g. `foo` property from JavaScript's `Object.prototype`.

**Comment by Reinmar** [comment]
Thanks for posting this :heart:

From my experience, people really do find such issues when debugging their own problems and they help a lot.

As for extending `Object.prototype` – this is tempting but it's gonna break many things. This concept was popular back in 00s' and e.g. PrototypeJS or Mootools did that, but the community understood with the time that it's making things not interoperable and it's an unsafe thing to do.
