### ISSUE TITLE
Autolink selected text on URL paste

### ISSUE THREAD

**Issue by robbens** [ckeditor/ckeditor5#12821]
## 📝 Provide a description of the improvement
When a URL in the clipboard is pasted to a selection of text, the text should be converted to a link with the text as its content.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/12089594/200811396-773e900b-813e-48ed-bdf6-2a245b967418.png">
`CMD + V`
<img width="677" alt="image" src="https://user-images.githubusercontent.com/12089594/200811598-d9364a90-be8a-41c8-bf17-119b4d1a0529.png">

_How the feature works now and what you'd like to change_?
Right now, the clipboard URL is pasted as plain text and overwrites the selected text.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/12089594/200811501-3ff93819-71c3-4a1c-bb63-e2a4a70d797d.png">

## 📃 Other details

* Browser: Chrome 107.0.5304.87
* OS: MacOS 12.4
* CKEditor version: 35.2.1
* Installed CKEditor plugins: N/A

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi @robbens,

Thanks for reaching out and for bringing this feature request to our attention.

We already have such a request open and you can find it [here](https://github.com/ckeditor/ckeditor5/issues/5656).

While we can't offer any concrete ETA on when this feature will be implemented, the linked GitHub thread will undoubtedly get updated when this happens, so feel free to follow it.

In light of this, I'll be closing this issue. You're welcome to join the discussion in the linked thread.
