### ISSUE TITLE
Allow to start list index from 0

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#12827]
## 📝 Provide a description of the improvement

Currently when setting [list start index](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#demo-3), you cannot go below value `1`. However, some use cases require starting list numbering from value `0`.
  
It would be good to enhance this feature and allow starting lists from `0`.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@FilipTokarski can you provide what are those use cases that require 0 start?

**Comment by Reinmar** [comment]
I checked Google Docs too. Negative numbers are not allowed, but 0 is. 

I don't think it requires more analysis. It's a simple and safe change.

![](https://user-images.githubusercontent.com/156149/202148006-c73263bd-d329-40fd-9802-620542e19872.png)

![](https://user-images.githubusercontent.com/156149/202148057-f0339680-3654-4e84-8391-2499494ac6c2.png)

**Comment by Reinmar** [comment]
Scope:

*   We've got one UI for both types of lists (List and DocumentList). So this change need to be made in two of them.
*   One potential issue is that `0` might be treated as a falsy value at some point during a conversion.
