### ISSUE TITLE
Check the Vue 3+ integration guide if it works with the new `create-vue` tooling instead of Vue CLI

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#12834]
As mentioned on the [Vue CLI start page](https://cli.vuejs.org/#getting-started), Vue CLI is in Maintenance Mode.
![obraz](https://user-images.githubusercontent.com/56868128/201596988-c6edf088-6cc6-4b40-85f0-97dbb1181138.png)

The integration guide for Vue 3+ should be checked if it works with this new tooling.

**Comment by przemyslaw-zan** [comment]
`create-vue` works fine. We have already updated our docs With mention of this tool, and integrating our Vue integration with Vite in https://github.com/ckeditor/ckeditor5/pull/13397
