### ISSUE TITLE
[Edge] Link editing does not work in table cells

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1283]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

master

## 📋 Steps to reproduce

1. Paste a link into a cell.
2. Click the link to open the link preview.
3. Click "edit".

## ✅ Expected result

Link eiting UI should show up.

## ❎ Actual result

Everything goes wrong:
* The selection moves outside of the table to the preceding paragraph,
* No link UI is displayed, the editing is impossible,
* The table toolbar remains but all buttons are disabled.

## 📃 Other details that might be useful

It's also impossible to create a new link from scratch in the cell using <kbd>Ctrl</kbd>+<kbd>K</kbd> shortcut. Nothing happens in that situation.

![kapture 2018-10-04 at 10 24 20](https://user-images.githubusercontent.com/1099479/46461809-edf90100-c7bf-11e8-840d-3742bb72be80.gif)

**Comment by Reinmar** [comment]
Is it a regression?

**Comment by oleq** [comment]
Nope, I checked current stable release and it's broken too.

**Comment by FilipTokarski** [comment]
This bug still exists on old Edge, however it is fixed in the new upcoming version (79.0.309.56)

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
