### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by minyoung90** [ckeditor/ckeditor5#12830]
## 📝 Provide a description of requested docs changes

Every vue3 related link are not working now.
(e.g. https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/vuejs-v3.html)

I got ERR_TOO_MANY_REDIRECTS

_What is the purpose and what should be changed?_

URL should be working

**Comment by arieltoledo** [comment]
Same

**Comment by mssayari** [comment]
same here!
On FireFox I'm getting this. 

```
The page isn’t redirecting properly

An error occurred during a connection to ckeditor.com.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by varxzy** [comment]
I also had the same problem.

**Comment by arieltoledo** [comment]
Meanwhile, this may have the information we need, https://github.com/ckeditor/ckeditor5/blob/master/docs/installation/frameworks/vuejs-v3.md

**Comment by godai78** [comment]
We did have a problem with a redirect last week but it is fixed now and the link works on our side.  
  
Please let me know if it should happen again after you clean the cache. Sorry for the inconvenience.

**Comment by varxzy** [comment]
> We did have a problem with a redirect last week but it is fixed now and the link works on our side.
> 
> Please let me know if it should happen again after you clean the cache. Sorry for the inconvenience.

Yes, it's already working properly.
