### ISSUE TITLE
Duplicated entry in the list of available professional translations

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12843]
## 📝 Provide a description of requested docs changes

There is a duplicate entry in the list of available professional translations table - _Hebrew_ is declared twice.

![](https://p28.zdusercontent.com/attachment/1606744/ubU0cjHpLnXGbMhrguUftaDii?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..wKLnazQTNRNgmZIqoIJxvw.Uu00bFSqHErWEkbeEk4CRYWi8_-Xp1Ldsx_OTMDY145y0dR7Om1SjAW24WPAcrDw9t8ltVA07ohPgyCEiYyLoUe8Z3pRoAsrX1cQkCNRp8pW6GsPnPQTLjMZBHRZwiqT4Dj8ZlJcZNvDV09qpRNl3MBrkbIdV7JH6alqxod3BsAIM_RjZzpy8KxSQ8ppahv2tEtJ6SKmcqy6hJpiPN9BooXDD1Aoz9i35lk0EZKiowBq9jLWnr7jzoAlk8LeSL_3pFKE0ydqWA0SlDdGu2LGBDLdMUZ49g2Bb19fv4NkxAg.ctVqJVb2L8GdvNyEbD1RrA)

**Comment by godai78** [comment]
Fixed in cksource/ckeditor5-internal#2224
