### ISSUE TITLE
Conversion Model Consumable Not Consumed

### ISSUE THREAD

**Issue by sashokbg** [ckeditor/ckeditor5#12847]
## 📝 Provide detailed reproduction steps (if any)

1. Create the following model
```
        schema.register('placeholderBox', {
            // Behaves like a self-contained object (e.g. an image).
            isObject: true,

            // Allow in places where other blocks are allowed (e.g. directly in the root).
            allowWhere: '$block'
        });
        schema.register('placeholderBoxHeader', {
            // Cannot be split or left by the caret.
            isLimit: true,

            allowIn: 'placeholderBox',

            // Allow content which is allowed in blocks (i.e. text with attributes).
            allowContentOf: '$block'
        });
```
2. Create the following converters

```
        conversion.for('upcast').elementToElement({
            model: 'placeholderBox',
            view: {
                name: 'section',
                classes: 'placeholder-box'
            }
        });
        conversion.for('dataDowncast').elementToElement({
            model: 'placeholderBox',
            view: {
                name: 'section',
                classes: 'placeholder-box'
            }
        });
        conversion.for('editingDowncast').elementToElement({
            model: 'placeholderBox',
            view: (modelElement, {writer: viewWriter}) => {
                const section = viewWriter.createContainerElement('section', {class: 'placeholder-box'});

                return toWidget(section, viewWriter, {label: 'simple box widget'});
            }
        });

        conversion.for('upcast').elementToElement({
            model: 'placeholderBoxHeader',
            view: {
                name: 'div',
                classes: `placeholder-box-header`
            }
        });
        conversion.for('dataDowncast').elementToElement({
            model: 'placeholderBoxHeader',
            view: {
                name: 'div',
                classes: `placeholder-box-header`
            }
        });
        conversion.for('editingDowncast').elementToElement({
            model: 'placeholderBoxHeader',
            view: (modelElement, {writer: viewWriter}) => {
                // Note: You use a more specialized createEditableElement() method here.
                const div = viewWriter.createEditableElement('paragraph', {class: `placeholder-box-header`});

                return toWidgetEditable(div, viewWriter);
            }
        });
```

3. And the following command (the callback function)
```
function createSimpleBox(writer, props) {
    const {header} = props;

    const box = writer.createElement('placeholderBox');
    const headerBox = writer.createElement('placeholderBoxHeader');

    writer.append(headerBox, box);

    // There must be at least one paragraph for the description to be editable.
    // See https://github.com/ckeditor/ckeditor5/issues/1464.


    //writer.appendElement('paragraph', headerBox); // **<-- This wroks**
    const p1 = writer.createElement('paragraph');
    writer.appendElement(p1, headerBox);

    return box;
}

```
4. When I append an empty paragraph to my **placeholderBoxHeader** then everything works.
If I try to create a paragraph using "writer.createElement" and then append it to the header then an exception is raised (conversion-model-consumable-not-consumed)

### ✔️ Expected result

To insert a box with a header that has a paragraph with text "lala time".

### ❌ Actual result

`bundle.js:103545 Uncaught CKEditorError: conversion-model-consumable-not-consumed {"items":[{"event":"insert","item":{"name":"paragraph","children":[{"data":" lalal time"}]}}]}`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
> ```
> const p1 = writer.createElement('paragraph');
> writer.appendElement(p1, headerBox);
> ```
The above usage of `writer.appendElement()` is invalid, [`appendElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-appendElement) expects an element name to create and append, you should use [`writer.append()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-append) if you want to pass the element instance.

Apart from that, you specify in the schema that `placeholderBoxHeader` should `allowContentOf: '$block'` so it's the content of a single paragraph and you should not insert a paragraph inside that model element, or if you want to have multiple blocks inside that element then you should modify the schema to sth like `allowContentOf: '$root'`.

**Comment by sashokbg** [comment]
Hello @niegowski thank you for the prompt response - you helped me resolve my problem.
You were right - it was the way I was using the writer - when I used writer.append with the object reference it started working.
Cheers !
Closing the issue
