### ISSUE TITLE
Improve data change visibility in the "Data from external source" tutorial

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#12869]
## 📝 Provide a description of requested docs changes

It's been noted by multiple people that the updates in this tutorial are not visible enough.

There are few things I'll suggest:

- [x] Reduce the listing interval to 10s. It's 15s currently. (I hope we won't exceed any limits from the service provider?)
- [x] Make the purple outline animation a slower.
- [x] Add &nbsp; before the widget (to avoid #12850).
- [ ] Add an outline to the widget so that it is more visible.

We need to cooperate with CCX on this.

**Comment by apadol-cksource** [comment]
It maybe worth to expose the final product of the tutorial on example page in the framework section so there will be higher chance that developers will discover the tutorial
