### ISSUE TITLE
[IME Android Gboard] A new typing character is inserted in the wrong position after toggling bold on and off

### ISSUE THREAD

**Issue by 0xc22b** [ckeditor/ckeditor5#12865]
## 📝 Provide detailed reproduction steps (if any)

1. Type a word + space + toggle bold on
2. Type a word + space + toggle bold off
3. Type a word

https://user-images.githubusercontent.com/1229910/202443106-a68f8948-4ccd-4df2-8b89-7245daead8bd.mp4

### ✔️ Expected result

The character is inserted at the end

### ❌ Actual result

The character is inserted not at the end

## 📃 Other details

* Browser: Chrome & Firefox + Gboard
* OS: Android 13, 12 & 9
* CKEditor version: https://ckeditor.com/ckeditor-5/demo

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi @0xc22b,

Thanks for reaching out and for bringing this issue to our attention. We can confirm that we were able to reproduce it on Android on Chrome and Firefox.

Doesn't appear on Safari on iPhone.

**Comment by 0xc22b** [comment]
This issue seems to be fixed by #14569. Thank you. 🙏

**Comment by mabryl** [comment]
Just retested this on this kind of setup:

Device: Samsung A52s 5G
OS: Android 13
Keyboard: Gboard 13.2.04
Browsers: Chrome 116.0.5845.92 | Firefox 116.3.0

And I can confirm that the issue is no longer reproducible.
