### ISSUE TITLE
BalloonPanelView  Out of editor range

### ISSUE THREAD

**Issue by chenyx1934** [ckeditor/ckeditor5#12864]
![image](https://user-images.githubusercontent.com/12790656/202401510-a49fb029-1ad2-4d42-bf9e-790843181762.png)

**expect：Hide when out of editor range**

**Comment by mabryl** [comment]
Hi @chenyx1934,  
  
Thank you for your report. We're aware of this issue and are tracking it in [this thread](https://github.com/ckeditor/ckeditor5/issues/5328). Feel free to join the discussion there. I'll close your ticket since it's a duplicate of the linked issue.

**Comment by chenyx1934** [comment]
来信已收到。

**Comment by shenyi-dra** [comment]
Anything new about this issue? Seems this issue comes from 2017... but still open, is there any information about this? Hope it can be resolved asap.

**Comment by chenyx1934** [comment]
来信已收到。

**Comment by Witoso** [comment]
@shenyi-dra the issue will be most probably researched by us pretty soon in #5328. Thanks for your message!

**Comment by shenyi-dra** [comment]
@Witoso 
ok, great, i thought that one is not updated anymore.
I will keep following issue #5328
