### ISSUE TITLE
Typedoc - do not use numerical values produced by TypeDoc

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#12877]
## Provide a description of the task

Currently, `tag-error` detects an inline tag inside the `@error` annotation [by checking the numerical value](https://github.com/ckeditor/ckeditor5-dev/blob/409d91603d20a37cb0a9fd7cd9ad7a49bdba207f/packages/typedoc-plugins/lib/tag-error/index.js#L139). This number has changed between TypeDoc v0.23.15 and v0.23.21 from **324** to **327**.

Also the `module-fixer` tries to find a JSDoc block code that represents a module definition [by checking the numerical value](https://github.com/ckeditor/ckeditor5-dev/blob/409d91603d20a37cb0a9fd7cd9ad7a49bdba207f/packages/typedoc-plugins/lib/module-fixer/index.js#L53). This number has changed between TypeDoc v0.23.15 and v0.23.21 from **141** to **142**.

This is not safe.

**Comment by psmyrek** [comment]
This problem could be related to changes in TypeScript itself and not necessarily in TypeDoc.

**Comment by pomek** [comment]
Done in https://github.com/ckeditor/ckeditor5-dev/pull/818.
