### ISSUE TITLE
Plugins - List - Toggling list styles and properties will throw an error and fail to update list

### ISSUE THREAD

**Issue by GoProduction** [ckeditor/ckeditor5#12872]
## 📝 Provide detailed reproduction steps (if any)
When toggling the list styles or list properties, an error will throw and the list will fail to update. I am using both a decoupled editor and a more custom multiroot editor (on different pages), and they run into the same issue.
![image](https://user-images.githubusercontent.com/51327899/202541904-9dc00b3e-f70e-45bb-9c43-0c7041551858.png)

### ✔️ Expected result

The list style should change the selected list.

### ❌ Actual result

The list style does not change and an error is thrown, "model-position-path-incorrect-format {"path":[]}"
![image](https://user-images.githubusercontent.com/51327899/202542529-7016e85e-c8eb-4af2-a3cb-209c31d47fbc.png)

### ❓ Possible solution

After looking through the migration documentation, I observed that the focus on drop-downs have changed for v35.x. Maybe it has something to do with that?

## 📃 Other details

* Browser: Chrome 107.0.5304.107, Firefox 107.0
* OS: Windows 10
* First affected CKEditor version: 35.2.1
* Installed CKEditor plugins: 
* Alignment,
          Autoformat,
          AutoLink,
          Autosave,
          BlockQuote,
          Bold,
          Clipboard,
          Essentials,
          FindAndReplace,
          FontBackgroundColor,
          FontColor,
          FontFamily,
          FontSize,
          GeneralHtmlSupport,
          Heading,
          Highlight,
          HorizontalLine,
          Image,
          ImageCaption,
          ImageResize,
          ImageStyle,
          ImageToolbar,
          Indent,
          IndentBlock,
          Italic,
          LineHeight,
          Link,
          List,
          ListProperties,
          PageBreak,
          PasteFromOffice,
          SpecialCharacters,
          SpecialCharactersArrows,
          SpecialCharactersCurrency,
          SpecialCharactersEssentials,
          SpecialCharactersLatin,
          SpecialCharactersMathematical,
          SpecialCharactersText,
          StandardEditingMode,
          Strikethrough,
          Subscript,
          Superscript,
          Table,
          TableCaption,
          TableCellProperties,
          TableProperties,
          TableToolbar,
          TextTransformation,
          TodoList,
          Underline    

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
We were not able to reproduce this error. Are you able to reproduce it on [docs demo](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#demo-2)?

**Comment by GoProduction** [comment]
> We were not able to reproduce this error. Are you able to reproduce it on [docs demo](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#demo-2)?

I was not able to reproduce the issue from the demo. Can I ask what version the demo is currently using? The only reason I ask is because I didn't run into this issue until I upgraded my ckeditor packages from v33.x to v35.x. Just in case, here is what my dependencies look like:

```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-autosave": "35.2.1",
    "@ckeditor/ckeditor5-basic-styles": "35.2.1",
    "@ckeditor/ckeditor5-build-classic": "35.2.1",
    "@ckeditor/ckeditor5-build-decoupled-document": "35.2.1",
    "@ckeditor/ckeditor5-cloud-services": "35.2.1",
    "@ckeditor/ckeditor5-comments": "35.2.1",
    "@ckeditor/ckeditor5-dev-utils": "28.1.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "28.1.1",
    "@ckeditor/ckeditor5-editor-classic": "35.2.1",
    "@ckeditor/ckeditor5-engine": "35.2.1",
    "@ckeditor/ckeditor5-essentials": "35.2.1",
    "@ckeditor/ckeditor5-export-word": "35.2.1",
    "@ckeditor/ckeditor5-find-and-replace": "35.2.1",
    "@ckeditor/ckeditor5-highlight": "35.2.1",
    "@ckeditor/ckeditor5-horizontal-line": "35.2.1",
    "@ckeditor/ckeditor5-html-support": "35.2.1",
    "@ckeditor/ckeditor5-inspector": "^4.1.0",
    "@ckeditor/ckeditor5-link": "35.2.1",
    "@ckeditor/ckeditor5-list": "35.2.1",
    "@ckeditor/ckeditor5-page-break": "35.2.1",
    "@ckeditor/ckeditor5-pagination": "35.2.1",
    "@ckeditor/ckeditor5-paragraph": "35.2.1",
    "@ckeditor/ckeditor5-real-time-collaboration": "35.2.1",
    "@ckeditor/ckeditor5-restricted-editing": "35.2.1",
    "@ckeditor/ckeditor5-special-characters": "35.2.1",
    "@ckeditor/ckeditor5-theme-lark": "35.2.1",
    "@ckeditor/ckeditor5-vue": "4.0.1",
    "@ckeditor/ckeditor5-watchdog": "35.2.1",
    "@ckeditor/ckeditor5-word-count": "35.2.1",
    "@fortawesome/fontawesome-svg-core": "1.2.36",
    "@fortawesome/free-solid-svg-icons": "5.15.4",
    "@fortawesome/vue-fontawesome": "3.0.0-4",
    "@he-tree/vue3": "1.2.4",
    "@popperjs/core": "2.9.3",
    "@vueform/multiselect": "^2.3.4",
    "@vueform/slider": "^2.0.9",
    "@vueform/toggle": "^2.0.1",
    "@vuelidate/core": "^2.0.0-alpha.41",
    "@vuelidate/validators": "^2.0.0-alpha.29",
    "axios": "0.26.0",
    "axios-extensions": "3.1.1",
    "bootstrap": "4.1.3",
    "core-js": "3.25.2",
    "debounce": "1.2.1",
    "jquery": "3.6.0",
    "json-editor-vue": "^0.8.0",
    "lodash": "4.17.21",
    "moment": "2.29.1",
    "popper.js": "1.16.1",
    "postcss-loader": "3",
    "raw-loader": "0.5.1",
    "register-service-worker": "1.7.1",
    "smart-tagz": "file:smart-tagz-0.3.1.tgz",
    "splitpanes": "3.0.6",
    "v-calendar": "3.0.0-alpha.5",
    "vanilla-jsoneditor": "^0.9.0",
    "vue": "3.2.29",
    "vue-loader": "16.8.3",
    "vue-loading-overlay": "5.0",
    "vue-router": "4.0.12",
    "vue-toastification": "^2.0.0-rc.5",
    "vue-tree-list": "1.5.0",
    "vue3-perfect-scrollbar": "1.5.5",
    "vue3-popper": "1.4.2",
    "vue3-treeview": "0.3.5",
    "vuex": "4.0.2",
    "vuex-persistedstate": "4.0.0",
    "webpack-remove-serviceworker-plugin": "^1.0.0"
  },
  "devDependencies": {
    "@vue/cli": "4.5.15",
    "@vue/cli-plugin-babel": "4.5.15",
    "@vue/cli-plugin-eslint": "4.5.15",
    "@vue/cli-plugin-pwa": "4.5.15",
    "@vue/cli-plugin-router": "4.5.15",
    "@vue/cli-plugin-vuex": "4.5.15",
    "@vue/cli-service": "4.5.15",
    "@vue/compiler-sfc": "3.2.24",
    "@vue/eslint-config-prettier": "6.0.0",
    "babel-eslint": "10.1.0",
    "clean-webpack-plugin": "3.0.0",
    "eslint": "6.7.2",
    "eslint-plugin-prettier": "3.3.1",
    "eslint-plugin-vue": "7.0.0",
    "html-replace-webpack-plugin": "2.5.6",
    "html-webpack-harddisk-plugin": "1.0.1",
    "html-webpack-plugin": "3.2.0",
    "prettier": "2.2.1",
    "webpack": "4.42.0"
  }
}
```

**Comment by FilipTokarski** [comment]
Editors on documentation demos are in version `35.3.1`. You might be interested in checking the [latest changelog and update guides on docs](https://ckeditor.com/docs/ckeditor5/latest/updating/index.html) and detailed changelog for previous versions [on the GitHub page](https://github.com/ckeditor/ckeditor5/releases).

Apart from that, I see that you use some of the premium plugins. If you are a licensed user, we'd highly recommend to [contact our support channel](https://ckeditor.com/contact/) in case of any problems.
