### ISSUE TITLE
Undo, redo after paste crashes the editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1287]
There are two TCs here:

## TC1

Similar to https://github.com/ckeditor/ckeditor5/issues/1278 but paste happens on a non-collapsed selection:

![oct-05-2018 11-00-06](https://user-images.githubusercontent.com/156149/46526199-de47ee00-c88d-11e8-9a5d-4ad234983b58.gif)

Undo and redo causes:

```
ckeditorerror.js:46 Uncaught CKEditorError: merge-operation-how-many-invalid: Merge operation specifies wrong number of nodes to move. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-merge-operation-how-many-invalid


CKEditorError @ ckeditorerror.js:46
_validate @ mergeoperation.js:164
Model.on @ model.js:83
fire @ emittermixin.js:196
(anonymous function) @ observablemixin.js:253
_undo @ basecommand.js:161
editor.model.enqueueChange @ redocommand.js:44
_runPendingChanges @ model.js:496
enqueueChange @ model.js:205
execute @ redocommand.js:38
on @ observablemixin.js:249
fire @ emittermixin.js:196
(anonymous function) @ observablemixin.js:253
execute @ commandcollection.js:67
execute @ editor.js:292
listenTo @ undoui.js:58
fire @ emittermixin.js:196
ButtonView.setTemplate.on.click.bind.to.evt @ buttonview.js:149
callback @ template.js:946
fire @ emittermixin.js:196
domListener @ emittermixin.js:235
```

## TC2

The same scenario as in https://github.com/ckeditor/ckeditor5/issues/1278 but keep doing undo, redo after pasting. First, that makes the content invalid and then crashes the editor:

![oct-05-2018 11-09-22](https://user-images.githubusercontent.com/156149/46526703-4cd97b80-c88f-11e8-9a1e-bb75199d5be3.gif)

The error:

```
ckeditorerror.js:46 Uncaught CKEditorError: merge-operation-target-position-invalid: Merge target position is invalid. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-merge-operation-target-position-invalid


CKEditorError @ ckeditorerror.js:46
_validate @ mergeoperation.js:157
Model.on @ model.js:83
fire @ emittermixin.js:196
(anonymous function) @ observablemixin.js:253
_undo @ basecommand.js:161
editor.model.enqueueChange @ redocommand.js:44
_runPendingChanges @ model.js:496
enqueueChange @ model.js:205
execute @ redocommand.js:38
on @ observablemixin.js:249
fire @ emittermixin.js:196
(anonymous function) @ observablemixin.js:253
execute @ commandcollection.js:67
execute @ editor.js:292
listenTo @ undoui.js:58
fire @ emittermixin.js:196
ButtonView.setTemplate.on.click.bind.to.evt @ buttonview.js:149
callback @ template.js:946
fire @ emittermixin.js:196
domListener @ emittermixin.js:235
```

**Comment by scofalik** [comment]
I created a PR which fixes TC1. However after you do steps form TC1 and click undo again, it will create unexpected content and then redo crashes. That error and the one from TC2 look similar, so I believe it may be the same thing. However, they get so complicated that I am having difficulty debugging it. As sad and laughable as it may sound, I am not sure if I will be able to fix it without bigger change connected with undo&OT.

**Comment by scofalik** [comment]
I managed to fix TC2, but unfortunately it didn't fix undo-redo-undo in TC1.

**Comment by scofalik** [comment]
I managed to fix all those bugs. I hope.
