### ISSUE TITLE
Clipboard content which has \r\n not results new line

### ISSUE THREAD

**Issue by fazil3295** [ckeditor/ckeditor5#12874]
## 📝 Provide detailed reproduction steps (if any)

1. Save below HTML and render the HTML in chrome browser.
   Attaching the HTML text in comments
2.Then copy the page contents in ckeditor https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

### ✔️ Expected result
The Date text should come in new line as it is displaying in the page.

### ❌ Actual result

The Date text is appending with the txt and new line is ignored.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by fazil3295** [comment]
[copy_pasting_new_lines_scenario.txt](https://github.com/ckeditor/ckeditor5/files/10038379/copy_pasting_new_lines_scenario.txt)

**Comment by Reinmar** [comment]
Interesting case. It works better when loading that HTML via the source editing feature. But worse when pasting from another website.

**Comment by Reinmar** [comment]
BTW, that has nothing to do with that content using `\r\n`. It's most likely about `<div>` being used in that HTML right after `<a>`.

For the reference, this is the HTML that was provided by @fazil3295:

```
<!DOCTYPE html>
<html>
    <style>
		.test{
		  text-transform: uppercase;
		  font-weight: 700;
		  font-size: 1.2rem;
		  color: #7A7464;
		}
	</style>
	<body>
		<div class="test">
			<ul>
				<li>
					<a data-lbl="test1" data-client-link="true" href="www.google.com">Google Home Page1</a>
					<div class="test">2 Nov 2022</div>
				</li>
				<li>
					<a data-lbl="test2" data-client-link="true" href="www.google.com">Google Home Page2</a>
					<div class="test">2 Nov 2022</div>
				</li>
			</ul>
		</div>
	</body>
</html>
```

**Comment by Reinmar** [comment]
I checked again and it works fine when using GHS + Document lists.

I checked before either with disabled GHS (no support for `<div>`s) or the old List feature (no support for two blocks inside an `<li>`).

You need the combination of two and then pasting the content copied from an HTML page will render this markup in CKE5:

```
<ul style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);color:rgb(122, 116, 100);font-family:Times;font-size:19.2px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:uppercase;white-space:normal;widows:2;word-spacing:0px;">
    <li>
        <p>
            <a href="https://fiddle.jshell.net/_display/www.google.com" data-lbl="test1" data-client-link="true"><strong>GOOGLE HOME PAGE1</strong></a>
        </p>
        <div class="test" style="color:rgb(122, 116, 100);font-size:1.2rem;text-transform:uppercase;">
            <strong>2 NOV 2022</strong>
        </div>
    </li>
    <li>
        <p>
            <a href="https://fiddle.jshell.net/_display/www.google.com" data-lbl="test2" data-client-link="true"><strong>GOOGLE HOME PAGE2</strong></a>
        </p>
        <div class="test" style="color:rgb(122, 116, 100);font-size:1.2rem;text-transform:uppercase;">
            <strong>2 NOV 2022</strong>
        </div>
    </li>
</ul>
```

Or this markup when pasting HTML directly via the source editing model:

```
<div class="test">
    <ul>
        <li>
            <p>
                <a href="www.google.com" data-lbl="test1" data-client-link="true">Google Home Page1</a>
            </p>
            <div class="test">
                2 Nov 2022
            </div>
        </li>
        <li>
            <p>
                <a href="www.google.com" data-lbl="test2" data-client-link="true">Google Home Page2</a>
            </p>
            <div class="test">
                2 Nov 2022
            </div>
        </li>
    </ul>
</div>
```

The difference being caused by what Chrome puts into the clipboard when coping a piece of a page.
