### ISSUE TITLE
Plugin - Tables - Selecting table caption button fails to insert caption and throws an error

### ISSUE THREAD

**Issue by GoProduction** [ckeditor/ckeditor5#12873]
## 📝 Provide detailed reproduction steps (if any)

When enabling and selecting the table caption button, the table will fail to create a caption and will throw an error in the console. I am using both a decoupled editor as well as a custom multiroot editor, and the same results happen.

![image](https://user-images.githubusercontent.com/51327899/202546566-f9c267ce-c659-4b4c-8a88-7bd7318828ec.png)

### ✔️ Expected result

Selecting the table caption button should display the caption field.

### ❌ Actual result

The table caption field will fail to display and will throw an error in the console, "model-selection-setto-required-second-parameter".

![image](https://user-images.githubusercontent.com/51327899/202547005-2b596d5e-4094-48bb-a251-aaf3b215c92d.png)

## 📃 Other details

* Browser: Chrome 107.0.5304.107, Firefox 107.0
* OS: Windows 10
* First affected CKEditor version: 35.2.1
* Installed CKEditor plugins: 
* Alignment,
          Autoformat,
          AutoLink,
          Autosave,
          BlockQuote,
          Bold,
          Clipboard,
          Essentials,
          FindAndReplace,
          FontBackgroundColor,
          FontColor,
          FontFamily,
          FontSize,
          GeneralHtmlSupport,
          Heading,
          Highlight,
          HorizontalLine,
          Image,
          ImageCaption,
          ImageResize,
          ImageStyle,
          ImageToolbar,
          Indent,
          IndentBlock,
          Italic,
          LineHeight,
          Link,
          List,
          ListProperties,
          PageBreak,
          PasteFromOffice,
          SpecialCharacters,
          SpecialCharactersArrows,
          SpecialCharactersCurrency,
          SpecialCharactersEssentials,
          SpecialCharactersLatin,
          SpecialCharactersMathematical,
          SpecialCharactersText,
          StandardEditingMode,
          Strikethrough,
          Subscript,
          Superscript,
          Table,
          TableCaption,
          TableCellProperties,
          TableProperties,
          TableToolbar,
          TextTransformation,
          TodoList,
          Underline  

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
We were not able to reproduce the error. Are you sure it is not caused by your customisations? Are you able to reproduce it on [docs demo](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-caption)?

**Comment by GoProduction** [comment]
It appears that including the "ckeditor/ckeditor5-table" dependency inside the package.json file resolved the issue. Closing this out. Thanks!
