### ISSUE TITLE
Cannot drop between widgets

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#12894]
## 📝 Provide a description of the improvement

1. Create a content when there are two block object widgets (e.g. two images).
2. Try to drag&drop something (another widget) between them.
3. This is impossible, there's no drop target, when dropped the dragged widget will overwrite one of the existing widgets.

**Comment by leonkj** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/11737
Moreover, you can select part of the text and drag'n'drop it on the image - the image will be replaced by the text. So if you have several images (widgets) in a row it is impossible to drop an image (or text) between existing ones.

**Comment by Witoso** [comment]
We've improved drag-and-drop of blocks in \[v40.0.0\](https://github.com/ckeditor/ckeditor5/releases/tag/v40.0.0), which has just been released, and the placement between widgets is possible!

Got more thoughts or feedback? There are still improvements we would like to make, follow and 👍 the #15110, if you're interested.
