### ISSUE TITLE
Consider adding HTML sample to zip packages

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1290]
Possible benefit: without looking into the quick start guide etc. one can run and play with CKEditor 5 
 instantly, simply by opening the attached html sample.

Additionally, in such a sample we could add a couple of links to the most critical pages, like docs etc.

**Comment by Reinmar** [comment]
I wouldn't go with this in npm releases because I expect its audience to be more experienced JS developers. But in case of zip packages, this sounds like a good idea.

**Comment by oleq** [comment]
Ping @wwalc and @pomek. AFAIR the templates are ready and what we need is a script that will use them in zips.

**Comment by pomek** [comment]
Where are the templates? I would like to see a structure of those files because it is required for creating an archive.

**Comment by wwalc** [comment]
Let's consider this as done.
