### ISSUE TITLE
Counter/progress bar feature for "Data from external source" guide.

### ISSUE THREAD

**Issue by pszczesniak** [ckeditor/ckeditor5#12906]
> I was thinking about adding a text with dynamic counter above the editor. Something like "Bitcoin rate will be refreshed in X seconds". But that should be extracted to a followup.
> 
> Be aware that there could be 2 digits so in order to prevent "seconds" from going left and right I'd put the number in a fixed width container where the number will be right aligned.  
> Be sure not to show "Bitcoin rate will be refreshed in 0 seconds." but "Bitcoin rate will be refreshed in 10 seconds." instead.  
> Even better idea would be to some graphical counter (e.g. in a widget) that would do this job. E.g. a progress bar line below the widget or a circle timer.

_Originally posted by @mlewand in https://github.com/ckeditor/ckeditor5/issues/12869_

**Comment by mlewand** [comment]
After some time has passed we are happy with the completeness of this example 👍
