### ISSUE TITLE
Add custom label option for SourceEditing Plugin

### ISSUE THREAD

**Issue by BenjaminAbt** [ckeditor/ckeditor5#12905]
## 📝 Provide a description of the new feature

First of all: I'm not sure if this is really a feature or if I just haven't found the appropriate documentation.

We have the CKEditor5 in use and want to use it - despite certain problems - as a Markdown editor; or evaluate it.
For the beginners just the WYSIWYG function and for the professionals want to enable a "Raw Markdown Editor".

For the Markdown part, we would like to simply use the Source Editing plugin feature.
By default, the button shows up as "Source", though "Markdown" would be a better fit as a label.

According to the source code, the plugin does not allow direct options, thus no custom label text.
How can the label be customized here?

Is this possible via a translation functionality of the CKEditor as a workaround?
If so, I can't find it in the docs.

If not, then this would be a feature request/improvement.

Thanks.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
You can try something along the lines of:

```javascript
editor.ui.view.toolbar.items.find( item => item.label && item.label.startsWith( 'Source' ) ).label = 'My label'
```

**Comment by BenjaminAbt** [comment]
Thank you very much, that works great.

I have now put this into the editor initialization.

```javascript
MarkdownEditor
    .create(document.querySelector('#Editor'), {
        toolbar: MarkdownEditor.Presets.Messages.ToolbarItems,
    }).then(editor=>{
        editor.ui.view.toolbar.items.find(item => item.label && item.label.startsWith('Source')).label = 'Markdown';
    })
```

Is there also a way to put this directly into the editor definition?

```javascript
export default class MarkdownEditor extends ClassicEditorBase {}
```

At the time of the constructor, the necessary components don't seem to exist yet, which is why this is in `then()`, right?

**Comment by oleq** [comment]
Editor instances usually fire the [`ready`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#event-ready) event when they finish initialization, for instance [https://github.com/ckeditor/ckeditor5/blob/10f9f865e9b5830876529c0572b72e4e18300c5c/packages/ckeditor5-editor-classic/src/classiceditor.ts#L220.](https://github.com/ckeditor/ckeditor5/blob/10f9f865e9b5830876529c0572b72e4e18300c5c/packages/ckeditor5-editor-classic/src/classiceditor.ts#L220.)

You can make the editor listen to itself in `MarkdownEditor's` constructor, 

```javascript
this.on( 'ready', () => { 
	// do the thing 
} );
```

**Comment by BenjaminAbt** [comment]
Thank you

```javascript
export default class MarkdownEditor extends ClassicEditorBase {
    constructor(sourceElementOrData, config) {
        super(sourceElementOrData, config);

        this.on( 'ready', () => {
            this.ui.view.toolbar.items.find(item => item.label && item.label.startsWith('Source')).label = 'Markdown';
        } );
    }
}
```

did the trick.
