### ISSUE TITLE
Wrong url to contribute on full-feature editor example

### ISSUE THREAD

**Issue by pszczesniak** [ckeditor/ckeditor5#12913]
## 📝 Provide a description of requested docs changes

1.  Go to [https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)
2.  Click on "Contribute to this guide" 
<img width="963" alt="Screenshot 2022-11-23 at 12 20 29" src="https://user-images.githubusercontent.com/7074833/203534296-8784e742-6883-415a-b402-e77fd6a526b2.png">

3. It leads to GitHub 404: https://github.com/ckeditor/ckeditor5/blob/master/https://github.com/docs/cksource/ckeditor5-internal/examples/builds/full-featured-editor.md

**Comment by godai78** [comment]
This should not be there at all. Fixing this.

**Comment by godai78** [comment]
Merged in cksource/ckeditor5-internal#2255

**Comment by godai78** [comment]
Thanks for catching this.
