### ISSUE TITLE
Missing info about properties rename in migration guide to 35.1.0

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#12918]
## 📝 Provide a description of requested docs changes

See 3rd bullet from [35.1.0 changelog](https://github.com/ckeditor/ckeditor5/blob/master/CHANGELOG.md#minor-breaking-changes-%E2%84%B9%EF%B8%8F-2):

> *   [**ui**](https://www.npmjs.com/package/@ckeditor/ckeditor5-ui): The static properties of `BalloonPanelView` have been renamed. `BalloonPanelView.arrowVerticalOffset` is now `heightOffset` and `BalloonPanelView.arrowHorizontalOffset` is now `sideOffset`.

It should be mentioned also in the [migration guide](https://ckeditor.com/docs/ckeditor5/latest/updating/migration-to-35.html#migration-to-ckeditor-5-v3510).

**Comment by godai78** [comment]
Yeah, I'll add it.
