### ISSUE TITLE
Pasted links that had no protocol become relative in the editor

### ISSUE THREAD

**Issue by vanathishiv** [ckeditor/ckeditor5#12912]
## 📝 Provide detailed reproduction steps (if any)
When text with hyperlink without protocol example: just "oracle.com" is
pasted from MS Word to CKE the hyperlink for the text in CKE is changing to
"[https://fuscdrmsmc30-fa-ext.us.oracle.com/hcmUI/faces/oracle.com"]

## 📃 Other details
When adding links like oracle.com in microsoft word from mac the hyperlink
automatically adds the http protocol to the link in mac based microsoft word,
but in windows based microsoft word this does not happen.

The behaviour is similar in CKe5 and CKe4.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
I was not able to reproduce this behaviour. CKEditor 5 preserves the original link added to Word file. 

If you are a licensed user, we highly recommend to [contact us throught the official support channel](https://ckeditor.com/contact/).

**Comment by vanathishiv** [comment]
Uploading Hyperlink_windows_ckeditor.mp4…


https://user-images.githubusercontent.com/45788491/203899851-e7843dad-f3f8-4045-8454-23535ea4adbc.mp4

**Comment by vanathishiv** [comment]
When adding links like oracle.com in microsoft word from mac the hyperlink automatically adds the http protocol to the link in mac based microsoft word

more like how the microsoft word process the link in both mac and windows?

https://user-images.githubusercontent.com/45788491/204525686-2cc611ab-5e61-4ee4-a0b0-f9ec4e1d2fcf.mp4



https://user-images.githubusercontent.com/45788491/204525686-2cc611ab-5e61-4ee4-a0b0-f9ec4e1d2fcf.mp4

**Comment by Reinmar** [comment]
IMO, when [https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-default-link-protocol-to-external-links](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-default-link-protocol-to-external-links) is turned on, we can also use it during paste.

I was initially worried that this would disallow the user to create relative links, but AFAIR how that option works, the user wouldn't be able to create a relative link starting from e.g. `ckeditor.com` with that option on anyway. Upon link creation, the protocol would be added.

Hence, it's not a problem if we do this on paste, even if the source of the data was the editor itself.

**Comment by Reinmar** [comment]
Idea: When `config.link.defaultProtocol` is on, apply it to all pasted links. Let's do this for all pasted content, not only content coming from Word.

**Comment by arkflpc** [comment]
To fix the editor's behavior in the case specified in the description above, set [link.defaultProtocol](https://ckeditor.com/docs/ckeditor5/latest/api/module_link_link-LinkConfig.html#member-defaultProtocol) config as `"http://"` or `"https://"`.
