### ISSUE TITLE
Typedoc: do not remove doclets marked with the `@publicApi` annotation

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12932]
## 📝 Provide a description of the new feature

* In https://github.com/ckeditor/ckeditor5/issues/12931, we want to add a new plugin for removing doclets from private packages.
* When the `@publicApi` annotation occurs next to the `@module` tag, we do not want to purge these docs.
* ~However, if a module, class, method, property, etc., are marked with the `@publicApi` annotation, we should not remove its docs.~

**Comment by pomek** [comment]
When detecting a signature from a private package, add the `@skipSource` annotation.

**Comment by psmyrek** [comment]
Done in ckeditor/ckeditor5-dev#823.
