### ISSUE TITLE
Typedoc plugin for removing doclets from private packages

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12931]
## 📝 Provide a description of the new feature

* See: https://github.com/ckeditor/ckeditor5-dev/blob/3600c7ed7049fb352c7ac79140f12997490438a4/packages/jsdoc-plugins/lib/purge-private-api-docs.js.
* For detecting a private package, we can read a `package.json` file and the `private` property.
* The goal is to remove the entire module if it belongs to a private package.

**Comment by pomek** [comment]
So far, so good.

![image](https://user-images.githubusercontent.com/2270764/205644003-fb19c021-07e9-4224-be19-b7e8a674275c.png)

![image](https://user-images.githubusercontent.com/2270764/205644017-ac5953d0-dc68-47df-a7fc-77c288fa7424.png)

**Comment by psmyrek** [comment]
Done in ckeditor/ckeditor5-dev#823.
