### ISSUE TITLE
Scroll appeared in inspectors used in the conversion guides

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#12949]
Here https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/upcast.html

![](https://user-images.githubusercontent.com/156149/204765599-a3024a3b-c654-49c2-b5ac-4f5cfc7c12b8.png)

**Comment by godai78** [comment]
These don't seem to appear now on macOS/recent Chrome.

**Comment by ldrobnik** [comment]
The scroll bar doesn't seem to appear on macOS (Chrome or Safari), but I've checked on Windows 11, and it does show in Chrome (version 108.0.5359.125). Curiously, the scroll bar doesn't appear on Windows 11 when viewed in Firefox.

**Comment by FilipTokarski** [comment]
> These don't seem to appear now on macOS/recent Chrome.

Happens for me

**Comment by godai78** [comment]
Merged in #13733
