### ISSUE TITLE
Broken README in editor builds

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#1294]
## Is this a bug report or feature request?

🐞 Bug report 

## 📋 Steps to reproduce

1. Let's check README.md of every build.
https://github.com/ckeditor/ckeditor5-build-classic/blob/master/README.md
https://github.com/ckeditor/ckeditor5-build-inline/blob/master/README.md
https://github.com/ckeditor/ckeditor5-build-balloon/blob/master/README.md
https://github.com/ckeditor/ckeditor5-build-decoupled-document/blob/master/README.md

## ❎ Actual result
![screen shot 2018-10-10 at 13 43 11](https://user-images.githubusercontent.com/10219857/46734076-74b34f80-cc92-11e8-899c-85b7a09669b1.png)

**Comment by Reinmar** [comment]
Doh... my fault.

**Comment by Reinmar** [comment]
My guess is I've been doing some `mgit exec 'git merge stable'` thing and missed some warnings. We need to make sure that at the end of `mgit exec` there's some well visible warning about all tasks which finished with errors. cc @pomek Could you check what happens if you do `mgit exec 'git merge stable'` which ends with conflicts in some repos? Does `git` return an error code?

**Comment by Reinmar** [comment]
> Does `git` return an error code?

If `git merge` ends with no error, then we need to fix our release process to make `git merge` fail loud on conflicts.

Also, I'd love to see a static check for such issues somewhere on Travis. Sadly, builds are not covered by CI now, but this kind of issue may happen everywhere.

**Comment by pomek** [comment]
> If git merge ends with no error, then we need to fix our release process to make git merge fail loud on conflicts.

https://stackoverflow.com/a/4917997/3388924

If `git merge` ends with conflicts, response code should equal to 1.

But I can see that mgit does not detect it and does not handle such cases.

**Comment by Reinmar** [comment]
@pomek Could you report a ticket in mgit2 to improve how errored commands are logged?

I'm closing this one because it's fixed.
