### ISSUE TITLE
Why does the content styles changes at different times under the same version?

### ISSUE THREAD

**Issue by yoyo837** [ckeditor/ckeditor5#12942]
Why does the content styles changes at different times under the same version? When I check out the document on https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html#the-full-list-of-content-styles, it shouldn't change over time.

![image](https://user-images.githubusercontent.com/6134547/204493886-9553de3f-7a14-4d1e-9f1f-7603ef21a153.png)

**Comment by Reinmar** [comment]
It's due to the way how we build the docs. These styles are not cached but generated on the fly from the source code.

@yoyo837, out of curiosity (although I think I know the answer) why do you see this as a problem?

@pomek maybe we could actually commit this to the repo when built on `stable`?

**Comment by yoyo837** [comment]
Is there a way to rebuild the css from the stable repo?

**Comment by pomek** [comment]
Execute `node -e "require('./scripts/docs/build-content-styles.js')();"`, then see `build/content-styles/content-styles.css`.

**Comment by yoyo837** [comment]
> Execute `node -e "require('./scripts/docs/build-content-styles.js')();"`, then see `build/content-styles/content-styles.css` (from CKEditor 5 root directory point of view).

Thanks for your reply and your hard work for the repo, this solution solved me.

**Comment by yoyo837** [comment]
Note:

Since `build-content-styles.js` has been rewritten as ESM in https://github.com/ckeditor/ckeditor5/pull/17132, the calling method needs to be changed.

```shell
node --input-type=module -e "import('./scripts/docs/build-content-styles.mjs').then(module => module.default?.());" `
```

**Comment by pomek** [comment]
@yoyo837, I do not have to specify the `input-type` for Node on my machine.

```
$ node -v
v20.18.1

$ yarn run docs:content-styles
yarn run v1.22.19
$ node -e "import( './scripts/docs/build-content-styles.mjs' ).then( m => m.default() );"
(node:10694) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Building content styles...
Content styles have been extracted to /home/pomek/Projects/ckeditor/ckeditor5/build/content-styles/content-styles.css
Done in 4.53s.
```

Is it needed?

**Comment by yoyo837** [comment]
> yarn run docs:content-styles

Oh, yes, It is. I was missing this script `docs:content-styles`. 

Thank you so much.

**Comment by yoyo837** [comment]
I found the problem reappeared, the CSS of the second run `docs:content-styles` was inconsistent with the first.
