### ISSUE TITLE
Check and update Migration from CKEditor 4

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#12941]
Compare the [Migration from CKEditor 4](https://ckeditor.com/docs/ckeditor5/latest/updating/migration-from-cke4.html) guide with the current state of the editors and update if needed.

**Comment by godai78** [comment]
Taken over by https://github.com/cksource/ckeditor5-internal/issues/2752

**Comment by wimleers** [comment]
That's a non-public issue 😭

**Comment by godai78** [comment]
The updated has been completed, the guide should now be as up-to-date as available.
