### ISSUE TITLE
Update CKEditor 34 -> 35: SyntaxError: Identifier 'global' has already been declared

### ISSUE THREAD

**Issue by alexander-schranz** [ckeditor/ckeditor5#12971]
## 📝 Provide detailed reproduction steps (if any)

I run into the follwoing issue:

> SyntaxError: Identifier 'global' has already been declared

When running our tests with Jest after updating CKEditor 34 -> 35.

1. Run jest tests on https://github.com/sulu/sulu/pull/6926

### ✔️ Expected result

_What is the expected result of the above steps?_

Tests should not fail.

### ❌ Actual result

_What is the actual result of the above steps?_

```bash
● Test suite failed to run

    /home/runner/work/sulu/sulu/node_modules/@ckeditor/ckeditor5-utils/src/dom/global.js:29
    let global;
        ^

    SyntaxError: Identifier 'global' has already been declared

      2 | import React from 'react';
      3 | import log from 'loglevel';
    > 4 | import AlignmentPlugin from '@ckeditor/ckeditor5-alignment/src/alignment';
        | ^
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: only jest Tests
* OS: MacOS
* First affected CKEditor version: 35
* Installed CKEditor plugins: https://github.com/sulu/sulu/blob/8ed3425211e8b72b4ac7ecc5239842408927fc42/src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js#L4-L18

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by carlartz** [comment]
We are having the same issue when running our Jest Tests with CKEditor 35.

**Comment by otto10** [comment]
Same Issue with Jest when upgrading to CKEditor 35. Keeping an eye here. Following the thread.

**Comment by alexander-schranz** [comment]
@otto10 can you test if the rename would also fix it in your case?

**Comment by carlartz** [comment]
This should work, we renamed the variable locally and our tests ran successfully.  Would this impact CKEditor running in our application?

**Comment by alexander-schranz** [comment]
@carlartz Thx for testing. As `let` normally defines `scoped variables` this should have zero effect if we rename the variable in that file as it is private variable. Lets wait what the CKEditor core team says about the change :).

**Comment by alexander-schranz** [comment]
@Reinmar @pomek Let me know if you need any more information and if I can do something to push this forward :)

**Comment by pomek** [comment]
cc: @arkflpc

**Comment by Reinmar** [comment]
Apologies to everyone – I forgot about this issue. Fortunately, @mremiszewski and @arkflpc corrected my mistake :) Sorry it took so long!

**Comment by Reinmar** [comment]
BTW, I wonder what's the root cause of this problem? Why does Jest have a problem with that variable? I'm a bit afraid that we fixed this particular issue but we'll hit the same problem elsewhere later on too.

**Comment by alexander-schranz** [comment]
@Reinmar jest defines a global const called `global` so you can not use `let global` somewhere. So it coule maybe be catches with a eslint rule to avoid this.
