### ISSUE TITLE
`ContextualBalloon` conflict with the latest releases

### ISSUE THREAD

**Issue by cedx** [ckeditor/ckeditor5#1297]
## Is this a bug report or feature request? (choose one)
🐞 Bug report

## 💻 Version of CKEditor
Classic Editor v11.0.1

## 📋 Steps to reproduce
1. Create a custom build of the Classic Editor.
2. Upgrade your dependencies to the latest versions available. See my [package.json](https://github.com/sab-international/rich-text-editor/commit/9fcf317ca724983edc74c04421477917edb8bcf8) file : it shows what modules were updated and their current version.
2. Compile the sources and open an instance of the editor in your browser.

## ✅ Expected result
Everything works as previously.

## ❎ Actual result
The editor does not work at all, and the browser console displays :

```
plugincollection-plugin-name-conflict: Two plugins with the same name were loaded.
  plugin1: function contextualballoon_ContextualBalloon()
​  plugin2: function balloon_contextualballoon_ContextualBalloon()
​  pluginName: "ContextualBalloon"

CKEditorError: "model-selection-set-ranges-not-range: Selection range set to an object that is not an instance of model.Range.
```

## 📃 Other details that might be useful
I did a clean install of Node.js modules (i.e. `rm -rf node_modules && npm install` : no change (the error is still there).
The custom editor uses the following plugins : [source code](https://github.com/sab-international/rich-text-editor/blob/9fcf317ca724983edc74c04421477917edb8bcf8/src/editor.ts#L50)

**Comment by Reinmar** [comment]
You've got an outdated table package in https://github.com/sab-international/rich-text-editor/blob/9fcf317ca724983edc74c04421477917edb8bcf8/package.json. It's trying to load an older version of ckeditor5-ui so ckeditor5-ui gets duplicated.

We're planning to implement a webpack plugin (or recommend existing one) which will warn about such situations

But for now, make sure to run a tool like npm-check to verify whether you're using the latest packages.

**Comment by cedx** [comment]
Thanks @Reinmar for pointing the source of this problem. Updating the `image` and `table` packages fixed the issue 👍
