### ISSUE TITLE
[Firefox] Find and replace tour balloon wrong positioning

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#12976]
## 📝 Provide detailed reproduction steps (if any)

1. Open Firefox browser
2. Go to https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html

### ❌ Actual result

Tour balloon is attached too low:
![Screenshot 2022-12-06 at 14 51 49](https://user-images.githubusercontent.com/34380544/205930593-43383389-8ca8-4693-a039-561c20359f5c.png)

## 📃 Other details

* Browser: Firefox

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by godai78** [comment]
Appears to be working properly on a recent 108.xxx Fire![Screenshot 2022-12-21 at 14.08.42.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/d3ed0414-d212-4bc5-a275-baa1a54dc3b3)fox under macOS.

**Comment by FilipTokarski** [comment]
Maybe it was some weird glitch. If you cannot reproduce it anymore, feel free to close the issue.

**Comment by godai78** [comment]
Thanks for the confirmation!
