### ISSUE TITLE
No information on how to get tokenUrl in CKE5 CKBox feature page

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12988]
## 📝 Provide a description of requested docs changes

There is no description on how to get tokenUrl on this page: https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/ckbox.html#providing-the-token-url
You have to go as far as to CloudServicesConfig api to get any useful links for that matter (CKBox config is not helpful either).
It would be good to include more detailed information on this page, pointing to Cloud Services docs https://ckeditor.com/docs/cs/latest/guides/export-to-pdf/quick-start.html#creating-token-endpoint to make CKBox feature page clearer to CKE5 users.

**Comment by godai78** [comment]
This is basically written at the very beginning of the guide together with applicable links (not to API, too). DO you think adding this info again in a single sentence would be useful? If so, I can do it![Screenshot 2022-12-21 at 14.09.55.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/68600f8c-a2b6-4aa8-a4d7-ef776df49763).
