### ISSUE TITLE
Wordcount plugin

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1301]
It looks like people are looking for "word count" or "character count" in our documentation and can't find it. I'm creating this issue to track demand for such a plugin. If anyone is looking for such plugin, add 👍. Also please write a comment what's your use case for it, so that we could better understand what's the purpose of this plugin.

**Comment by vivekn-procentris** [comment]
I need the word/character count plugin to limit the user to 7000 characters. Something similar to the word count plugin available for CKEditor 4 - https://ckeditor.com/cke4/addon/wordcount

**Comment by Maqsyo** [comment]
Our customers asks explizit for such a functionality - so we need it :P

**Comment by webplease** [comment]
I need it too :)

**Comment by NadaSokkar** [comment]
We need this functionality too. We're currently using the word count plugin in ckeditor 4 to show the count of paragraphs, words, & characters, & it would be great to have this feature available in ckeditor 5

**Comment by venkateshwarans** [comment]
Is it still an open issue? Or we have a solution for it now? We are trying to create a dynamic template for creating multiple choice questions where we have to restrict user by characters for the 'Options' field.

**Comment by wwalc** [comment]
@venkateshwarans yes the issue is still open and seeing the 👍 under it makes it quite probable that we'll handle it at some point. Unfortunately there is no ETA for it yet as we scheduled many things already. If you'd like to speed things up and sponsor the development of the plugin, then please  [contact us](https://ckeditor.com/contact).

If you'd like to work on the plugin by yourself, then sharing with others a link to the repository in a comment may help, maybe other interested users would like to help somehow once you provide some starting point.

**Comment by msamsel** [comment]
I scan through some word count features and I see some different approach in each of them. There are few things worth considering:
1. Non-whitespace word separators:
   * `foo/bar`
   * `foo(bar)`
   * `foo-bar` <- (this probably should be considered always as single word)
2. Non alphanumeric strings:
   * `#^&()`

**Comment by jodator** [comment]
@msamsel the unicode has some preatty neat article about detecting word boundaries - maybe it could be taken into consideration. Also there's a algorithm to skip words in `modifySelection()`.

**Comment by msamsel** [comment]
I've provide specification for the plugin in:
https://github.com/ckeditor/ckeditor5-word-count/issues/1

**Comment by mlewand** [comment]
This feature recently was merged to the `master` branch 🎉 It now provides a convenient API to track amount of words in the editor.

Basic configuration should looks something like that:

```js
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        // Configuration details.
    } )
    .then( editor => {
		const wordCountPlugin = editor.plugins.get( 'WordCount' );
		// Your custom element where the word count should be applied to:
        const wordCountWrapper = document.getElementById( 'word-count' );

        wordCountWrapper.appendChild( wordCountPlugin.wordCountContainer );
    } )
    .catch( ... );

```

Or you can just observe `words` and `characters` properties of the `WordCount` instance if you need more control.

More info will be available in the docs.

Sample screencast:
![Screencast showing text statistics as end user types in the editor](https://user-images.githubusercontent.com/5353898/60579367-37906f80-9d83-11e9-937b-a4d2890ead1b.gif)

**Comment by pritijha17** [comment]
<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/classic/ckeditor.js"></script>
its not worked for me after napm save ? can any one send me steps to display character count for ckeditor 5th version.

**Comment by zomby22** [comment]
how do you integrate the word count like the footer of the textarea box. The ckeditor demo page has it display like that.

My current setup, the wordcount works but the html format, is not the way I want it to be.

**Comment by KellsCodes** [comment]
Please how can I use this in react app?

**Comment by mohsenbh67** [comment]
> Please how can I use this in react app?

i used this approach:

    const editorConfiguration = {
        wordCount: {
            onUpdate: (stats) => {
                const wordCountElement = document.getElementById("word-count");
                if (wordCountElement) {
                    wordCountElement.innerText = `Characters: ${stats.characters}, Words: ${stats.words}`;
                }
            },
        },
    };
    
<CKEditor
 editor={Editor}
data={editorData}
 config={editorConfiguration}
/>
<div id="word-count" ></div>
