### ISSUE TITLE
Firefox: Shift+Enter displays cursor in invalid location

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#1302]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

v11.0.0 from https://ckeditor5.github.io/

## 📋 Steps to reproduce

1. Open demo page https://ckeditor5.github.io/
2. Clear editor contents with `Ctrl+A+Del`
3. Type 'test' and press `Shift+Enter`
4. Type 'test'

1. Open demo page https://ckeditor5.github.io/
2. Clear editor contents with `Ctrl+A+Del`
3. Type 'test' and press `Shift+Enter`
4. Press `Shift+Enter`
5. Type 'test'

## ✅ Expected result

TC1: Cursor should be shown in the new line (the second line)
TC2: Cursor should be shown in the third line

## ❎ Actual result

TC1: Cursor is shown at the end of first line and when you start typing it jumps to correct location
TC2: Cursor is shown in the second line and jumps to correct 
third when you start typing

## 📃 Other details that might be useful

Problem can only be reproduced in Firefox.

This is confusing to user because he reacts to what he sees on the screen. User will try to move to second line with another `Shift+Enter` not realizing he has already moved to third.

Screen-cast: [test.zip](https://github.com/ckeditor/ckeditor5/files/2478356/test.zip)

**Comment by Reinmar** [comment]
This is a DUP of https://github.com/ckeditor/ckeditor5-engine/issues/1439
