### ISSUE TITLE
Q: BIDI in ckeditor 5

### ISSUE THREAD

**Issue by mohamedsabil83** [ckeditor/ckeditor5#1305]
Does ckeditor 5 support RTL language? I guess it's auto supported it and just need switch langguage but not. Also, try to find bidi package but there is one for ckeditor4 not 5.

How or When V5 support RTL language?

**Comment by Reinmar** [comment]
Please upvote and comment under https://github.com/ckeditor/ckeditor5/issues/1151. We'd like to hear what's missing in how CKEditor 5 works right now.
