### ISSUE TITLE
[Typing] WProofreader autocorrection stopped working 

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#13051]
## 📝 Provide detailed reproduction steps (if any)

1. https://ckeditor.com/docs/ckeditor5/latest/features/spelling-and-grammar-checking.html
2. Enable "Correct spelling automatically" in WProofreader settings (and choose "British English" language).
3. Type "somthing" in the editor

### ✔️ Expected result

It should get replaced with "something" after pressing space.

### ❌ Actual result

It is not replaced automatically.

### ❓ Possible solution

The flow of events:
1. The user presses the space
2. WProofreader is recording the typed word and the DOM Range on it and requests the backend for suggestions
3. Editor processes the `beforeinput` event and updates the model and then renders model changes. The renderer is replacing the DOM text node (instead of updating the data of the text node).
4. WProofreader is trying to apply auto-correction but the stored DOM Range is no longer valid. It got automatically updated by the browser and collapsed in the container element instead of the text node).

To fix the above scenario we should update the Renderer to update existing text nodes while handling `Renderer#_updateChildren()`: 

https://github.com/ckeditor/ckeditor5/blob/0297e9cf575e087f84132e889c959203a092856e/packages/ckeditor5-engine/src/view/renderer.ts#L730-L732

Changing the condition in the above line fixes the issue.

## 📃 Other details

* First affected CKEditor version: 35.3.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I'm wondering what would be the implications of this change:

*   Performance impact. Let's check if it's significant. Cases: long paragraphs with formatted text+images, long children lists. Typing, large structure changes (e.g. large table modifications), formatting long text, etc.
*   IME. Let's do some smoke testing at least (a couple of browsers/OSes).
*   Other spell checkers potentially. Worth at least checking Grammarly and Language Tool for similar cases.

**Comment by Reinmar** [comment]
Alternative solutions:

*   Ask WSC's team to listen on `beforeInput` and not on `keydown`. WSC listens on `keydown` which happens before we modify the content. Listening on `beforeInput` with a low enough priority might help. However, additional thing to consider here is how not to break support for previous CKEditor versions.
*   ?

**Comment by Reinmar** [comment]
Research extracted to #13081.

**Comment by Reinmar** [comment]
We made good progress in #13081. We'll close the research task soon and proceed with a final implementation in this ticket.

**Comment by Reinmar** [comment]
Idea: Let's push the PR with a fix ASAP (without waiting for the automated tests that have to be added) and ask the QA team to verify it.
