### ISSUE TITLE
ckEditor5 online build works in development, not in production mode

### ISSUE THREAD

**Issue by Anandhu1991** [ckeditor/ckeditor5#13093]
## 📝 Provide detailed reproduction steps (if any)

1. Download final build with required plugins from https://ckeditor.com/ckeditor-5/online-builder/
2. Extracted build content into a folder name ckeditor5 in root of project
3. Installed the local package with this command npm add file:./ckeditor5
4. Used these commands in nextjs to genarate production build `npm run build `and `npm run export`

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

Getting the follwoing error in production build of next js

```
849.02b0292964587ed3.js:1 TypeError: this.props.editor.create is not a function
    at ir._createEditor (849.02b0292964587ed3.js:1:27553)
    at Ge._creator (849.02b0292964587ed3.js:1:27214)
    at 849.02b0292964587ed3.js:1:19557
    at async ir._initializeEditor (849.02b0292964587ed3.js:1:27356)
    at async ir.componentDidMount (849.02b0292964587ed3.js:1:26738) 
Object
phase: "initialization"
willEditorRestart: false
[[Prototype]]: Object
```

console.log of editor module return the following

```
Module
__esModule: true
Symbol(Symbol.toStringTag): "Module"
```

But it works perfectly in development mode

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: … Google Chrome Version 103.0.5060.134 (Official Build) (64-bit)
* OS: … Ubuntu 16.04
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi @Anandhu1991,

Thanks for reaching out. As of right now, we don't provide official support for integrating our editor with Next.js, so some errors might pop up.

You can join [this discussion](https://github.com/ckeditor/ckeditor5/issues/7376) (which is the main thread that we use to track this) to learn more about integrating CKE5 with Next.js, as there are some solutions provided by our community members there for issues similar to yours.
