### ISSUE TITLE
Angular - When I use simple upload in component, an error is reported

### ISSUE THREAD

**Issue by sarlemon** [ckeditor/ckeditor5#13094]
## 📝 Provide detailed reproduction steps (if any)

1.
![image](https://user-images.githubusercontent.com/20472625/208376545-9877fde8-bced-4842-ba5c-aaab11c9299f.png)
2. 
![image](https://user-images.githubusercontent.com/20472625/208376269-6672d826-24db-474f-9ffa-b0b45bef6cbf.png)
3.
![image](https://user-images.githubusercontent.com/20472625/208376385-94dd5f15-2cbd-4c79-9011-a04dbcbd1c61.png)

### ✔️ Expected result

The simple uplod can be used normally in the angular

### ❌ Actual result

When using simple uplod in the angular, it will report a build error

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome
* OS: windows10
* First affected CKEditor version:"@ckeditor/ckeditor5-angular": "^1.2.3",
    "@ckeditor/ckeditor5-build-classic": "^18.0.0",
    "@ckeditor/ckeditor5-list": "^26.0.0",
    "@ckeditor/ckeditor5-upload": "^35.4.0",
* Installed CKEditor plugins:"@ckeditor/ckeditor5-angular": "^1.2.3",
    "@ckeditor/ckeditor5-build-classic": "^18.0.0",
    "@ckeditor/ckeditor5-list": "^26.0.0",
    "@ckeditor/ckeditor5-upload": "^35.4.0",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
As the error message says, it seems that Webpack loader has problems with parsing svg files.

Another thing is that you are using heavily outdated packages and all of them are in different versions, which will produce another errors. Please make sure you use [latest CKEditor 5 packages](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/updating-ckeditor-5.html) and all of them have the same version.

Apart from that, if you would like to use a custom editor build (with additional plugins) in Angular, please check the [integration documentation](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/angular.html#integrating-a-build-from-the-online-builder).

**Comment by sarlemon** [comment]
@FilipTokarski Thank you for your patience. I have updated lib and tried to define custom adapter to solve this problem.
