### ISSUE TITLE
Update build screenshots

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1311]
Since we added screenshots of builds to their readmes we also added two new features to these builds – tables and media embed. Unfortunately, we now need to update all these screenshots with these new features.

**Comment by dkonopka** [comment]
I've spent some time to prepare and update CKEditor 5 UI for Sketch, so ATM it's easy to update toolbar/content and I have idea to mockup editor into browser window? WDYT?

### Current design
![build-proposal0](https://user-images.githubusercontent.com/10219857/47288954-c942bd00-d5f8-11e8-8a8b-88a8e3fab3c6.png)

### Proposal
![build-proposal1](https://user-images.githubusercontent.com/10219857/47288967-d8c20600-d5f8-11e8-8333-486ad06924c1.png)

**Comment by Reinmar** [comment]
I think it's a good idea. It separates the screenshot from the surrounding and adds some scale to it (so when the image is small e.g. on npm, it doesn't look like we meant it to be that way).

**Comment by dkonopka** [comment]
Ok, so let's stay with browsers mockup, but (as I talked with oleq) we should familiarize users with our logo:

### 1) Logo outside editor 
![build-balloon-logo](https://user-images.githubusercontent.com/10219857/47489573-3a77af80-d847-11e8-9a72-55b4f335a8f1.jpg)

### 2) Logo inside editor
![build-balloon](https://user-images.githubusercontent.com/10219857/47489575-3a77af80-d847-11e8-9330-793dc49ed159.jpg)

**Comment by oleq** [comment]
I'm also for 2. Let's see what it looks like with other creators.

**Comment by dkonopka** [comment]
It looks good, except document editor, but IMHO is acceptable.

![build-document](https://user-images.githubusercontent.com/10219857/47494213-6dbf3c00-d851-11e8-86d4-65094fe2d064.jpg)

![build-balloon](https://user-images.githubusercontent.com/10219857/47494211-6d26a580-d851-11e8-9680-8b4e966840da.jpg)

![build-classic](https://user-images.githubusercontent.com/10219857/47494212-6d26a580-d851-11e8-95e2-f48b682405ba.jpg)

![build-inline](https://user-images.githubusercontent.com/10219857/47494214-6dbf3c00-d851-11e8-8735-fdc4c756c9e6.jpg)
