### ISSUE TITLE
Shift+enter line break

### ISSUE THREAD

**Issue by KeeyanBaseelyo** [ckeditor/ckeditor5#1312]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor 
5

## 📋 Steps to reproduce
1. Type in 1 + . (this triggers the numbering function)
2. Type the content and then hit enter (this creates a 2. as part of the numbering function)
3. Move the cursor back to the far-right of the content/text you just enter in number 1.
4. Hit shift+enter (this should create a tight line break.
5. Hit the arrow down key and the line break pops back up and disappears.

Issue: 
Creating tight breaks between lines (using shift+enter)

In CKEditor 4, all you had to do to create a small space between lines is to hit shift+enter with the cursor before the bullet or number to move down a line.

For CKEditor 5, you have to hit shift+enter+enter to get just 1 tight line break.

## ✅ Expected result
Get a tight line break in between the numbering.

## ❎ Actual result
Not getting the line break.

**Comment by Reinmar** [comment]
Sorry for a late answer, but I missed your ticket. I can confirm this issue:

![nov-07-2018 16-42-18](https://user-images.githubusercontent.com/156149/48141938-20f54f80-e2ac-11e8-99be-78edf60ef02c.gif)

I can bet that the list feature overrides `getFillerOffset()`... And I'm right: https://github.com/ckeditor/ckeditor5-list/blob/master/src/utils.js#L18

Most likely, we updated the default `getFillerOffset()` when we added support for soft breaks and we didn't update this specific function.
