### ISSUE TITLE
How to get the img url from CKEditor 5 getData method?

### ISSUE THREAD

**Issue by zmqcherish** [ckeditor/ckeditor5#1313]
stackoverflow.com question: [https://stackoverflow.com/questions/52846588/how-to-get-the-img-url-from-ckeditor-5-getdata-method](https://stackoverflow.com/questions/52846588/how-to-get-the-img-url-from-ckeditor-5-getdata-method)

I use my own UploadAdapter to upload img in CKEditor 5. The implementation method upload is below, just like the the official guideline description.

`upload() {
    const data = new FormData();
    data.append('file', this.loader.file);
    data.append('token', this.token);
    data.append('key', guid() + '.jpg');

    return new Promise((resolve, reject) => {
        axios({
            url: '{my server url}',
            method: 'post',
            data,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            withCredentials: false
        }).then(res => {
            var resData = eval("("+res.data+")");
            resData.url = 'my own domain' + resData.url;
            resolve(resData);
        }).catch(error => {
            reject(error)
        });
    });
}`

My server response is like: {uploaded: true url: "***.jpg"} And the code above work well. The CKEditor can get the response.I can see the img in the editor:
![1](https://user-images.githubusercontent.com/6880848/47068327-8d85ad00-d21e-11e8-89d7-74d33e50f4f0.jpg)

But, view the img html code is not my expect, it's src attribute has the base64 otherwise my given url param:
![3](https://user-images.githubusercontent.com/6880848/47068343-9d04f600-d21e-11e8-97ee-dedaa33633d1.jpg)

And the editor's getData method can not get the img data: 

![2](https://user-images.githubusercontent.com/6880848/47068362-ab531200-d21e-11e8-8707-82cac21407d0.jpg)

**Comment by koyta** [comment]
@zmqcherish how did you solve this?

**Comment by Shynobee** [comment]
up, i'm actually stuck here and i don't know how to solve this, so if anyone know the answer, i'll offer him a beer for that =D
