### ISSUE TITLE
Disabled buttons should not be focusable

### ISSUE THREAD

**Issue by ChristopherChudzicki** [ckeditor/ckeditor5#13133]
## 📝 Reproduction Steps

*We came across the following behavior when using an attribute check to disable simultaneous subscripts and superscripts: We noticed that when the superscript tool was active, the subscript tool was correctly disabled, but the button could still receive focus, which seems potentially confusing. I'll describe the reproduction for a simpler scenario on the demo page.*

1. Visit https://ckeditor.com/ckeditor-5/demo/, viewing the classic editor
2. Do not make any edits
3. Click "Undo"

### ✔️ Expected result
Undo button should not receive focus; it is disabled.

### ❌ Actual result

Undo button receives focus.

### ❓ Possible solution

Maybe add the `disabled` attribute to toolbar buttons whenever they have class `'ck-disabled" or `"ck-off"`, if that doesn't have other undesirable consequences.

## 📃 Other details

* I've tested this on Chrome 108 on a mac, but i imagine the browser doesn't matter much.

## Other info:
These seem related: 
- https://github.com/ckeditor/ckeditor5/pull/10682
- https://github.com/ckeditor/ckeditor5/issues/6200 _this one is about focusing the editing area itself, i think_

Thanks for CKEditor! It's been great to work with.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is correct behavior that disabled buttons are focusabled. The reason being accessibility.

IDK whether any of these articles is particularly good, but googling for "disabled buttons accessibility" returned e.g.:

*   [https://css-tricks.com/making-disabled-buttons-more-inclusive/](https://css-tricks.com/making-disabled-buttons-more-inclusive/)
*   https://a11y-101.com/development/aria-disabled

**Comment by Reinmar** [comment]
Maybe @Comandeer may chime in if I misremembered something.

**Comment by ChristopherChudzicki** [comment]
@Reinmar Thanks for the explanation—makes sense!
