### ISSUE TITLE
TypeError: client\node_modules\@ckeditor\ckeditor5-build-decoupled-document\build\ckeditor.js: Cannot read properties of null (reading 'scope')     at Array.filter (<anonymous>)

### ISSUE THREAD

**Issue by nitagr** [ckeditor/ckeditor5#13144]
## 📝 Provide detailed reproduction steps (if any)

1.Cannot read properties of null (reading 'scope') , got this error without upgrading any version changes of those packages.
2.  "@ckeditor/ckeditor5-build-decoupled-document": "^33.0.0",
    "@ckeditor/ckeditor5-react": "^4.0.0",

3. Error: TypeError: D:\PB\MtxDash22Dec22\client\node_modules\@ckeditor\ckeditor5-build-decoupled-document\build\ckeditor.js: Cannot read properties of null (reading 'scope')
    at Array.filter (<anonymous>)
Node version : 16.17.0
"react": "17.0.2",

## 📃 Other details

* Browser: … Chrome
* 
* OS: … Windows
* First affected CKEditor version: … "@ckeditor/ckeditor5-react": "^4.0.0",
* Installed CKEditor plugins: …"@ckeditor/ckeditor5-build-decoupled-document": "^33.0.0",

**Comment by jaideepr47** [comment]
I am facing the same issue

**Comment by nhanhuynh-everfit** [comment]
Me too

**Comment by giomv** [comment]
Me too, can't build my project.
ckeditor-9cb1fef5.js: Cannot read properties of null (reading 'scope')

**Comment by Chostus77** [comment]
any updates?

**Comment by nitagr** [comment]
> any updates
New Issue came after they resolved the existing bug>>
TypeError: /client/node_modules/@floating-ui/core/dist/floating-ui.core.browser.min.mjs: Cannot set properties of undefined (setting 'kind')

for the above issue, I added a new package for the resolution:=-
"@fortawesome/fontawesome-svg-core": "^6.2.1",
It works

**Comment by Reinmar** [comment]
> got this error without upgrading any version changes of those packages

Doesn't it indicate that this issue was caused by some other (non CKE5-related) dependency upgrade? I suppose that's what you tried to prevent by doing this:

> for the above issue, I added a new package for the resolution:=-  
> "@fortawesome/fontawesome-svg-core": "^6.2.1",

Did you report this issue to [https://github.com/FortAwesome/Font-Awesome](https://github.com/FortAwesome/Font-Awesome) too? Maybe they should be aware of it too?
