### ISSUE TITLE
how to upload local video

### ISSUE THREAD

**Issue by cao1057791962** [ckeditor/ckeditor5#13143]
Videos are only online and do not have local upload capabilities
![image](https://user-images.githubusercontent.com/37286914/209254789-77f9e8f8-96b4-4e36-a024-bebec154d784.png)

**Comment by mabryl** [comment]
Hi @cao1057791962,

Thanks for reaching out. Unfortunately, uploading videos that are hosted locally on your machine is not something that we currently support.

However, demand for implementing such a feature has been brought to our attention in the past and we're tracking it in [this thread](https://github.com/ckeditor/ckeditor5/issues/7873).

I'll close your issue now - feel free to join the discussion in the thread linked above.
