### ISSUE TITLE
[Docs] Simplify docs for the Angular integration

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1315]
The following option isn't necessary:
 
```
"compilerOptions": {
	"allowJs": true
}
```

It should be used only when we'd like to validate the local JS files for TS errors.
 Actually, it's useful only during migrating projects from JS to TS and type checking JS files (it's doable with JSDoc tags).

**Comment by Reinmar** [comment]
Closed by https://github.com/ckeditor/ckeditor5/pull/1316.
