### ISSUE TITLE
Consume typescript types when writing a customised build

### ISSUE THREAD

**Issue by Georgegriff** [ckeditor/ckeditor5#13150]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

---

I see that many of the packages including core are now written in typescript but i'm not seeing any types when I do `npm install` im not seeing any type definitions in the node_modules, do you have any plans to ship the types, or have I missed some other package?

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
We don't publish the types so far because we're still migrating: #11704. More than half of the packages are already migrated, including all the biggest ones. 

So we're ~75% done in terms of a progress. Once all packages are migrated, we'll start publishing the types.

**Comment by Reinmar** [comment]
For now, if you'd like to use the types, consider integrarting CKE5 via a cloned GH repo. It's a typical monorepo so you can configure yarn to source packages directly from inside of it. It won't be much different than installing them from npm.
