### ISSUE TITLE
Downcast conversions may not be consumed correctly

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#1317]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`Latest`

## 📋 Steps to reproduce

It seems that the downcast conversions may not be consumed correctly. 

Not working code (which is expected to work):

```js
this.editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
    model: {
        key: ITEMPROP,
        name: '$text'
    },
    view: ( value, writer ) => writer.createAttributeElement( 'span', { [ ITEMPROP ]: value } )
} ) );

this.editor.conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
    model: ITEMPROP,
    view: ITEMPROP
} ) );
```

Working code (more specific downcast conversions):

```js
this.editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
    model: {
        key: ITEMPROP,
        name: '$text'
    },
    view: ( value, writer ) => writer.createAttributeElement( 'span', { [ ITEMPROP ]: value } )
} ) );

this.editor.conversion.for('downcast').add(downcastAttributeToAttribute({
    model: {
        key: ITEMPROP,
        name: 'tableCell'
    },
    view: ITEMPROP
} ) );

this.editor.conversion.for('downcast').add(downcastAttributeToAttribute({
    model: {
        key: ITEMPROP,
        name: 'paragraph'
    },
    view: ITEMPROP
} ) );
```

cc @dimaip (if you have anything more to add or some additional comments feel free to add anything related).

## 📃 Other details that might be useful

Bugfix which was applied to this issue: https://github.com/psmb/SfiDistr/commit/82fca7281d604a8ea354ad26d4b8a5b542940a83

**Comment by f1ames** [comment]
I have analyzed the provided code to see how it works and if there are any issue. I did a simple test adding conversions as mentioned in a bug report:

```js
ClassicEditor
    .create( ... )
    .then( editor => {
        const ITEMPROP = 'itemprop';

        editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
            model: {
                key: ITEMPROP,
                name: '$text'
            },
            view: ( value, writer ) => writer.createAttributeElement( 'span', { [ ITEMPROP ]: value } )
        } ) );

        editor.conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
            model: ITEMPROP,
            view: ITEMPROP
        } ) );
    } );
```

and then changing editor model like:

```js
editor.model.change( writer => {
    const ITEMPROP = 'itemprop';
    const root = editor.model.document.getRoot();

    const p = writer.createElement( 'paragraph' );
    const text = writer.createText( 'FooBar' );

    writer.setAttribute( ITEMPROP, 10, p );
    writer.insert( text, p );
    writer.insert( p, root );

    const table = writer.createElement( 'table' );
    const tableRow = writer.createElement( 'tableRow', { itemprop: 10 } );
    const tableCell = writer.createElement( 'tableCell', { itemprop: 10 } );

    writer.setAttribute( ITEMPROP, 10, table );
    writer.insert( tableCell, tableRow );
    writer.insert( tableRow, table );
    writer.insert( table, root );
} );
```

and the resulting HTML in this case is (omitted some elements/tags for clarity):

```html
<figure itemprop="10">
    <table>
        <tbody>
            <tr itemprop="10">
                <td itemprop="10"></td>
            </tr>
        </tbody>
    </table>
</figure>
<p itemprop="10">FooBar</p>
```

which seems that `itemprop` attribute have been correctly downcasted from `model` to `view` and `DOM`. It also works with more specific converter (second one mentioned in the report) but generic ones also works fine. I also checked the same code inside `Plugin.init()` method and results are identical.

@dimaip could you take a look? Maybe I'm missing something or your issue is not related directly to converters?

---

One thing not related directly to the above, when conversions are defined like:

```js
const ITEMPROP = 'itemprop';

editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
    model: {
        key: ITEMPROP,
        name: '$text'
    },
    view: ( value, writer ) => writer.createAttributeElement( 'span', { [ ITEMPROP ]: value } ) 
} ) );

editor.conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
    model: ITEMPROP,
    view: ITEMPROP
} ) );
```

and changes to model are applied:

```js
editor.model.change( writer => {
	const root = editor.model.document.getRoot();
	const p = writer.createElement( 'paragraph', { itemprop: 10 } );
	const text = writer.createText( 'FooBar', { itemprop: 10 } );

	writer.insert( text, p );
	writer.insert( p, root );
} );
```

the `TypeError: Cannot read property '_setAttribute' of undefined` error is thrown. Initially I thought it is related to having two converters for the same property and different element types. However, it works for

```js
writer.insert( text, root );
writer.insert( p, root );
```

so it means nesting those elements causes some issue here.

**Comment by dimaip** [comment]
Hi @f1ames, thanks for looking into it!

Well, `TypeError: Cannot read property '_setAttribute' of undefined` is exactly what I meant by "not working", it just got lost in the bug report.
So I guess this issue can be closed and I'd just follow https://github.com/ckeditor/ckeditor5-engine/issues/1587

**Comment by Reinmar** [comment]
Yup!
