### ISSUE TITLE
Update Special characters demos

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#13207]
Some demos on [https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html](https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html) refer to foreign exchange rates for some currencies (which, in general, is a good use case for the special characters functionality). However, they were created a long time ago (10.02.2020) so we could update them.

**Comment by godai78** [comment]
This would be a cute case to have live feed via external data plugin.
