### ISSUE TITLE
Docs issue report from "framework/guides/plugins/abbreviation-plugin/abbreviation-plugin-level-2.html"

### ISSUE THREAD

**Issue by bajahranks** [ckeditor/ckeditor5#13212]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/abbreviation-plugin/abbreviation-plugin-level-2.html

### Project version

35.4.0

### Is there anything else you would like to add?

The _showUI function is placed in the wrong place in the documentation, although it is in the correct place in the code base on Github.

The document placed it here
`editor.ui.componentFactory.add( 'abbreviation', () => {
            this._showUI();
        } );`

but it should have been there....
`this.listenTo( button, 'execute', () => {
				this._showUI();
			} );`

This can be confusing to newcomers following the documentation religiously. It also gave the impression that the buttonView code that was written in first section was removed and replaced with this.showUI(); which is not the case.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54

**Comment by dufipl** [comment]
Hello @bajahranks,

Thank you for the report and, therefore, for contributing to the community! We verified this submission, and I can confirm that this particular example you are referring to is incorrect at the moment (the final code in the example repository is correct, though).

We will work on improving this example. You can track the progress by following this ticket.😊
