### ISSUE TITLE
Space character before block element inside paragraph is removed when setting data

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#1323]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`Latest` - `11.1.1`

## 📋 Steps to reproduce

1. Go to https://ckeditor5.github.io/.
2. Run `editor.setData( '<p>Foo Bar: <img src="#baz"/></p>' );` in the browser dev console.

## ✅ Expected result

New content is set, image is moved outside the paragraph. Paragraph content stays unchanged:

```html
<p>Foo Bar: </p>
<figure class="image"><img src="#baz"></figure>
```

## ❎ Actual result

New content is set, image is moved outside the paragraph. Space on the end of the paragraph content disappears:

```html
<p>Foo Bar:</p>
<figure class="image"><img src="#baz"></figure>
```

## 📃 Other details that might be useful

Tested on Chrome. Looks like some issue during conversions (`view` to `model`). It happens when block element preceded by a space character is moved outside its parent element.

**Comment by Reinmar** [comment]
I don't think this is a bug. You load incorrect content. That data would not be produced by CKEditor. And it's actually a trailing space so no one would even notice it.

**Comment by Reinmar** [comment]
I mean – as a rule of thumb, incorrect data does not have to be handled in some exceptional way. Unless it should because of pasting :D But in this case, as I wrote above, this is a nearly invisible change. And I'd actually say the result we give is better.

**Comment by f1ames** [comment]
> I mean – as a rule of thumb, incorrect data does not have to be handled in some exceptional way. 

I agree, but it is incorrect from the editor point of view. From HTML point of view, it is completely fine.

> Unless it should because of pasting :D

Yes, that was the place where I have encountered this issue (HTML generated by MS Word), but it may also happen with any HTML copied from a website.

> this is a nearly invisible change. And I'd actually say the result we give is better.

I was thinking about it... You can't basically see that it was removed so it has very low impact. And  as the block splits the paragraph this last space is usually redundant and won't make any difference in most cases.

Should we left this issue for future reference or just close it @Reinmar?

**Comment by Reinmar** [comment]
> I agree, but it is incorrect from the editor point of view. From HTML point of view, it is completely fine.

Yes, of course. But our first goal should be to make the editor compatible with the content it created itself. Then, we can work on improving compatibility with "any HTML", but usually a good, but still imperfect support for that will satisfy nearly everyone.

> Should we left this issue for future reference or just close it @Reinmar?

I'd close it. If someone will ever report it's going to be a DUP of this one anyway cause it's nearly impossible to match such tickets.
