### ISSUE TITLE
Duplicate characters inserted and cursor jumping when typing on Android

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#13247]
## 📝 Provide detailed reproduction steps (if any)

1. Open one of our demos (e.g. our [Full-featured editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html))
2. Place the cursor at the end or in the beginning of a paragraph
3. Start typing

### ✔️ Expected result

You should be able to type normally.

### ❌ Actual result

The cursor jumps unexpectedly and duplicate characters are inserted. See attached video for details.

## 📃 Other details

* Browser: Firefox Mobile 108.2.0
* OS: Android 13
* First affected CKEditor version: [v32.0.0](https://github.com/ckeditor/ckeditor5/releases/tag/v32.0.0)
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

https://user-images.githubusercontent.com/72079603/211785184-f42300e4-4f32-4ddd-aa62-66f25dbb06b7.mp4

**Comment by mabryl** [comment]
While I was able to replicate this issue only on mobile Firefox, one of our users (reached out to us via [Zendesk](https://ckeditor.zendesk.com/agent/tickets/80008)) seems to have encountered a similar problem on mobile Chrome.

See the recording attached to this message for reference.

https://user-images.githubusercontent.com/72079603/211785694-719e69f1-6676-4c1f-b07a-30f4a59b8d9b.mp4

**Comment by mabryl** [comment]
Just retested this and it looks like the issue is no longer reproducible, hence closing the issue.

Tested on Android 13 running Chrome 112.

If anyone still experiences this, feel free to reopen and provide info on OS and browser version.

**Comment by mssayari** [comment]
I still have the problem with Firefox on Android 13 (Samsung S21 Ultra), but chrome is working fine

**Comment by mabryl** [comment]
I just retested this on this kind of setup:

Device: Samsung A52s 5G
OS: Android 13
Keyboard: Gboard 13.1.07
Mobile browsers: Chrome 114.0.5735.196 | Firefox 115.2.1

I was unable to reproduce the issue in our full-featured demo: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

If anyone here is still facing issues with the duplicate characters, could you share more information about your setups? Perhaps there's some software&hardware configuration that triggers the issue?

Additionally, which version of the editor are you using? The one available in our documentation is always the latest release, so perhaps there is some older version of the editor that has this issue?

**Comment by mssayari** [comment]
I also still have the problem. 
I'm using Samsung keyboard 5.6.10.31

**Comment by mabryl** [comment]
Thanks for the replies.

So I tested this one more time and I was able to reproduce the issue in Firefox, while using Samsung Keyboard v5.6.10.31.

I think this is more of a Keyboard issue rather than an issue with CKEditor, since I was able to resolve the problem by disabling the Predictive text option in the keyboard settings.

Take a look at the recording and notice how the "t" letter gets repeated initially but doesn't when Predictive text is disabled:

https://github.com/ckeditor/ckeditor5/assets/72079603/db715e33-8874-4756-aa2d-82c38c778637

Could you check whether the issue is still present when you disable the Predictive text option @meichthys @mssayari?

**Comment by mssayari** [comment]
Yeah, in Firefox without the Predictive option, it works fine. but I just test it again in Chrome and surprisingly it works fine even with the Predictive option! 

should we still consider it a keyboard issue?

**Comment by Witoso** [comment]
> should we still consider it a keyboard issue?

The keyboard might not produce proper `beforeInput` events, the ones that we really on in the text composition.
