### ISSUE TITLE
[Docs] Incorrect `viewportTopOffset` of sticky toolbar

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#1326]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 📋 Steps to reproduce

1. See some live examples of editor with sticky toolbar

<img width="1597" alt="screen shot 2018-10-29 at 11 10 06" src="https://user-images.githubusercontent.com/10219857/47643259-37443280-db6b-11e8-9ae5-67f93ab80862.png">

## 📃 Other details that might be useful

Required: `umberto` update to `0.9.1.` version

**Comment by dkonopka** [comment]
Fixed in https://github.com/ckeditor/ckeditor5/commit/fdccb01490336a47c5dff87d39e4190b6b128e08.

**Comment by Reinmar** [comment]
Other repos: 

![image](https://user-images.githubusercontent.com/156149/47650094-75e3e800-db7f-11e8-88b2-bac69fa49724.png)

**Comment by Reinmar** [comment]
Fixed.
