### ISSUE TITLE
[Safari] Pasting mixed content (text+images) does not preserve images

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#13306]
## 📝 Provide detailed reproduction steps (if any)

This is a follow-up of #11993 but for Safari

1.  Reproduce steps from #11993 in Safari.

### ✔️ Expected result

See #11993. It should work like in Chrome.

### ❌ Actual result

The bug persists.

![](https://user-images.githubusercontent.com/1099479/213480179-7922d7cc-9886-4459-8940-b3692cd167ae.png)

## 📃 Other details

*   Browser: Version 16.2 (17614.3.7.1.7, 17614)
*   Word: 16.69.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by filipsobol** [comment]
I tested it on Windows and it works fine on Firefox (CKEditor 4 and 5), but doesn't on Chrome with the following errors in the console:

```
Cannot load local resource
```

Chrome: 109  
Firefox: 109

Word: 16.0, version 2212

**Comment by niegowski** [comment]
In this case, Safari is not providing `text/rtf` so we can not extract image data from it.
