### ISSUE TITLE
Docs refer to heading1-headingN commands that don't exist

### ISSUE THREAD

**Issue by adamerose** [ckeditor/ckeditor5#13300]
This [page](https://ckeditor.com/docs/ckeditor5/latest/api/module_heading_headingediting-HeadingEditing.html) says `It introduces heading1-headingN commands` but it seems like those commands don't exist when I try running them, and instead there is only the `heading` command which specifies the heading level with an extra argument like `{ value: 'heading2' }` as described [here](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#common-api).

**Comment by Reinmar** [comment]
cc @apadol-cksource
