### ISSUE TITLE
Docs issue report from "framework/guides/plugins/creating-simple-plugin-timestamp.html"

### ISSUE THREAD

**Issue by j2s** [ckeditor/ckeditor5#13319]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/creating-simple-plugin-timestamp.html

### Project version

35.4.0

### Is the information outdated? How?

The file LICENSE.md appears to be missing. It's mentioned in most of the example plugins as in: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/abbreviation-plugin/abbreviation-plugin-level-1.html

### User agent

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0

**Comment by godai78** [comment]
Just to clarify, do you mean it is missing in the `ckeditor5-tutorials-examples` repository?

**Comment by j2s** [comment]
@godai78  yes that's right

**Comment by godai78** [comment]
@j2s - here it goes: https://github.com/ckeditor/ckeditor5-tutorials-examples/blob/ck/13319/LICENSE.md

**Comment by j2s** [comment]
cool
