### ISSUE TITLE
Shift enter not inserting <br>'s in Safari

### ISSUE THREAD

**Issue by DEfusion** [ckeditor/ckeditor5#13321]
## 📝 Provide detailed reproduction steps (if any)

1. Goto the feature rich editor example in Safari & another browser
2. Remove all content
3. Type something
4. Press shift and enter a few times:

### ✔️ Expected result

In Chrome you get the expected `<br>`s

```
<p data-placeholder="Type or paste your content here!">Something<br><br><br><br><br><br><br><br data-cke-filler="true"></p>
```

### ❌ Actual result

In Safari you get multiple `<p>`s

```
<p data-placeholder="Type or paste your content here!">Something</p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p>
```

## 📃 Other details

* Browser: Safari 15.6.1 (OSX), Chrome 109.0.5414.87 (OSX)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by DEfusion** [comment]
Started digging, but I can't track down the origin of the problem.

At [`KeyObserver#onDomEvent`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/observer/keyobserver.ts#L29) it detects the shift key correctly.

At [`InputObserver` `beforeInput`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/observer/inputobserver.ts#L32) in chrome it gets an `insertLineBreak` `inputType`, in Safari it is `insertParagraph`

At [`EnterObserver` `beforeinput`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-enter/src/enterobserver.ts#L38) has same `inputType` as above in each browser.

**Comment by Reinmar** [comment]
> At [`InputObserver` `beforeInput`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/observer/inputobserver.ts#L32) in chrome it gets an `insertLineBreak` `inputType`, in Safari it is `insertParagraph`

That's the origin. Safari fires a wrong event. I remember it doing this in some case but I don't remember what we did about this. I'm afraid we may need to be listening to Shift key too and if we see it's pressed, turn `insertParagraph` into `inputType`. cc @niegowski

**Comment by mremiszewski** [comment]
Cannot reproduce on Windows using either Maxthon or Midori browsers. Someone with Apple should take this.
