### ISSUE TITLE
CKEditor 5 wrong custom build anatomy

### ISSUE THREAD

**Issue by ansocha** [ckeditor/ckeditor5#13320]
Hi,

I've been following the custom build procedure
https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source

but after running webpack

**./node_modules/.bin/webpack --mode development**

I do not get a generated

**build/ckeditor.js and
src/ckeditor.js –**

Instead I get a
**/dist** folder with **bundle.js** and **bundle.js.map**

I'm using webpack version

**webpack: 5.75.0
webpack-cli: 4.10.0
webpack-dev-server not installed**

I've tried this several times.

Online web builder works fine though, but I need more granular control of the build.

**Comment by FilipTokarski** [comment]
`/dist` and `bundle.js` names are specified in the Webpack configuration `output` property in the docs you linked. You can rename them if that is your requirement.
