### ISSUE TITLE
data-ck-unsafe-element on plugin custom tag

### ISSUE THREAD

**Issue by j2s** [ckeditor/ckeditor5#13340]
## 📝 Provide detailed reproduction steps (if any)

1. Add any custom tag to ckeditor (ie using source-edit facility), switch back to normal editing. The text disappears and inspecting the element shows <span data-ck-unsafe-element="mytag" ...
2. I have created a custom ckeditor5 plugin (run with Drupal 9) based on the Abbreviation example plugin and that all works fine for initial editing and output. It creates a custom tag eg: `<bbref ver="RSV">Ex 2:32</bbref>`

A couple of days later (possibly after an update?) the editor now rejects my tag when it loads saved HTML (or creating new bbref) and replaces it with `<span data-ck-unsafe-element="bbref" ver="RSV">Ex 2:32</span>` which is styled to be invisible in the editor.

ckeditor's domconverter.js seems to have a hand in this.
V31 has a note about applying this change to 'script' tags (https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-31.html#the-table-and-tablecell-attributes-names-change)  It seems to be applying it to all non-standard tags.

There is a method for handling a similar thing with data-ck-unsafe-attribute- (eg [https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-31....](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-31.html#the-table-and-tablecell-attributes-names-change)) but not for unsafe-element and trying the unsafe-attribute method does not seem to work:

```
// Callback function provides access to the model attribute value
            // and the DowncastWriter
            view: (modelAttributeValue, conversionApi) => {
                const {writer} = conversionApi;
                const cae =  writer.createAttributeElement(
                        'bbref',
                        {
                            ver: modelAttributeValue
                        },
                        {
                            renderUnsafeAttributes: ['ver', 'bbref']
                        });
                console.log('cae');
                //console.dir(cae);        
                return cae;
            }
```

Current Drupal core: 9.5.2

### ✔️ Expected result
_What is the expected result of the above steps?_
see text eg Ex 2:32 and when cursor is in it, clicking the plugin button brings up the edit dialog (as was happening)

### ❌ Actual result
_What is the actual result of the above steps?_
hidden text with tag converted to  <span data-ck-unsafe-element="mytag" ... 
As noted for unsafe-attribute, this does not affect the html when being viewed outside editor (ie custom tag is seen correctly).

### ❓ Possible solution
_If you have ideas, you can list them here. Otherwise, you can delete this section._
provide code to allow custom tags to avoid being flagged as unsafe-element

## 📃 Other details

* Browser: any
* OS: Ubuntu
* First affected CKEditor version: (current seems to be 35.4.0 - not sure what previous one was)
* Installed CKEditor plugins: just standard ones

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @niegowski

**Comment by j2s** [comment]
| :+1:
-- | --

**Comment by niegowski** [comment]
It looks like you did not implement an upcast converter that would translate provided HTML data into a valid data model. Seems like your custom element falls back into a GHS custom element handling that is hiding those elements in the view and keeps them in the model just to preserve them. You could check how the editor model structure looks like using the [CKEditor5 Inspector](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/development-tools.html#ckeditor-5-inspector) to verify if your custom element got converted to the expected model element and/or attribute.

**Comment by j2s** [comment]
Hi @niegowski 
Thanks, I didn't include the upcast code - but it's:
```
        // Conversion from a view element to a model attribute
        conversion.for('upcast').elementToAttribute({
            view: {
                name: 'bbref',
                attributes: ['ver']
            },
            model: {
                key: 'bibleref',
                // Callback function provides access to the view element
                value: viewElement => {
                    const ver = viewElement.getAttribute('ver');
                    return ver;
                }
            }
        }); 
```
The inspector seems to be interpreting it correctly:
![bbref_model](https://user-images.githubusercontent.com/1070770/216286279-551c166c-70cf-467a-9974-ba6c3cf3eaf2.png)

Actual HTML:
`It is inspired bbref (<bbref ver="RSV">Ex 2:32</bbref>)`
CKE HTML:
![image](https://user-images.githubusercontent.com/1070770/216287303-dc688b00-3f39-4ef2-a5f0-8611fb78e768.png)

**Comment by niegowski** [comment]
Can you share the full source code of your plugin? I'd need to debug it.

**Comment by j2s** [comment]
@niegowski thanks - as this runs under Drupal the import paths needed to be tweaked. I'll create a standalone version so it runs eg as the abbreviation example.

**Comment by j2s** [comment]
Standalone version with local paths attached.  This one works fine so something to do with the Drupal environment I guess.

However it would be good to figure out how to have the ver attribute as optional.  CKE (and as seen in Inspector) does not recognise the tag unless the ver attribute is present (though it can have a value of "")
[bbref_6feb.zip](https://github.com/ckeditor/ckeditor5/files/10664785/bbref_6feb.zip)

**Comment by j2s** [comment]
Update: I've since been able to install a debug environment for ckeditor and Drupal - see https://www.drupal.org/docs/core-modules-and-themes/core-modules/ckeditor-5-module/ckeditor-5-development#comment-14932011 
The constant `const UNSAFE_ELEMENT_REPLACEMENT_ATTRIBUTE = 'data-ck-unsafe-element-XXX';` in `mydev/ckeditor5/packages/ckeditor5-engine/src/view/domconverter.ts` seems central - but I can't see where it is being set only where compared (all in domconverter.ts. Adding my block tag (bbref) to what I thought was the 'allowed' list here (this.blockElements[]) did not exclude it from still being flagged and hidden in the browser.   
Changing 'data-ck-unsafe-element' to 'data-ck-unsafe-element-XXX' did defeat the CSS that hides the element so it can be seen and edited as it should be.

**Comment by j2s** [comment]
In Drupal ckeditor is configured via 'Text formats and editors' page. Each format instance includes a filter 'Limit allowed HTML tags and correct faulty HTML' If this is enabled the problem goes away...
It's not clear what this filter is doing to cke5...

**Comment by j2s** [comment]
With the latest versions of drupal the conversion is there but the editor recognises the tag and you can edit it via the plugin
However the 'Limit allowed HTML tags and correct faulty HTML' filter must be **dis**abled

If additional metadata is added to the drupal module, the filter can be used, if needed and both edit and view work ok - see https://www.drupal.org/project/drupal/issues/3336644
