### ISSUE TITLE
Mention text bug - v36.0.0

### ISSUE THREAD

**Issue by PeterNelsonT** [ckeditor/ckeditor5#13354]
## 📝 Provide detailed reproduction steps (if any)

1. Create a mention feed with format {id:xx,text:yy}
2. Try adding the mention item to editor

### ✔️ Expected result

if text is present in feed, then text should get rendered.

### ❌ Actual result

id is getting rendered instead of text.

### ❓ Possible solution

None. But issue happens with version 36. Works fine in previous version.
I can see text as undefined in custom itemRenderer as well.

## 📃 Other details

* First affected CKEditor version: v36.0.0
* Installed CKEditor plugins: @ckeditor/ckeditor5-mention

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! Did you find a solution? What was it?

**Comment by PeterNelsonT** [comment]
Sorry. This was not related to version. 
This happened because the feeds i was passing to the mentions had the text initially as undefined and later will recreate the feeds with with correct text. But the editor will be initialized by that time, hence it picked the initial config.
Though i am still checking, how i can dynamically change the config for ckeditor in react.
