### ISSUE TITLE
Docs issue report from "features/source-editing.html"

### ISSUE THREAD

**Issue by SirishaInturi** [ckeditor/ckeditor5#13364]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html

### Project version

36.0.0

### Is there something missing in the guide? What is it?

Can we identify if we have switched between normal mode to source  and source to normal mode? any event that can be used to know if the mode switched?Could you mention if it is feasible/ not.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by godai78** [comment]
Not sure if that's what you're looking for, but here's a comment from the plugin code, that may be of some use:  
  
``Currently, the plugin handles the source editing mode by itself only for the classic editor. To use this plugin with other integrations, listen to the `change:isSourceEditingMode` event and act accordingly.``
