### ISSUE TITLE
Image drag & drop extremely sluggish in Firefox 109

### ISSUE THREAD

**Issue by tmiller02** [ckeditor/ckeditor5#13366]
## 📝 Provide detailed reproduction steps (if any)

1. Open the CKEditor 5 image demo page at https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html in Firefox 109.0.1
2. Click the image and drag it around the document

### ✔️ Expected result

The caret should move around the page quickly to show where the image will be dropped

### ❌ Actual result

The caret moves extremely slowly, lagging behind the movement of the cursor by several seconds

## 📃 Other details

This issue may be related to changes to `dataTransfer.files` in Firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1812611 

Here's the stack chart while dragging the image:

<img width="1919" alt="Screenshot 2023-01-31 at 4 46 52 pm" src="https://user-images.githubusercontent.com/6973800/215828335-e00f8120-fc34-4df2-82b3-a1cfac4b2c98.png">

* Browser: Firefox 109.0.1
* OS: macOS 12.6.2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This looks like we could easily fix this just by not accessing native `DataTransfer#files` in every `dragging` event (it’s not even used there). 

Branch to verify this: [https://github.com/ckeditor/ckeditor5/compare/ck/13366](https://github.com/ckeditor/ckeditor5/compare/ck/13366)

So if we move the access to the getter and populate the list on demand, then there is a concern about whether anyone could access those files in case the `DataTransfer` instance was stored in some variable and used later.

I checked the doubt about accessing the `File` outside the `drop` event and it looks like access to the `DataTransfer#files` is limited to the `drop` event but if we store the `File` reference then we can access that file even after a `setTimeout` so this could be a breaking change for some crazy integrations that store the entire `DataTransfer` and access `files` sometime later, but if they store the `files` in the `drop` event handler then they still can access those files. This applies to Chrome, in Firefox it looks like we can access `files` after a timeout, without the need to store `File` references.

I'll check if we could cache the files in case of `drop` event and leave it in the getter for other events when the `DataTransfer` wrapper is used.
