### ISSUE TITLE
Model#insertContent() Maximum call stack size exceeded

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#13379]
## 📝 Provide detailed reproduction steps (if any)

In TC `Uncaught RangeError: Maximum call stack size exceeded.` is thrown on typing.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This issue was introduced in #13274. This code was not even released yet. It was merged to master yesterday and fixed with #13382 right after the merge. 

In #13274 we modified the `Model#insertContent()` and `Model#insertObject()` in the way that they were no real decorated methods, instead, they pretend to be decorated to maintain backward compatibility. It normalizes the event parameters fired on those methods' calls. What we missed is a dynamic augmentation of that event parameters (as we do in TC) - so some additional parameters were not supported and we fixed this in #13382.

**Comment by Reinmar** [comment]
> In #13274 we modified the `Model#insertContent()` and `Model#insertObject()` in the way that they were no real decorated methods, instead, they pretend to be decorated to maintain backward compatibility. It normalizes the event parameters fired on those methods' calls. What we missed is a dynamic augmentation of that event parameters (as we do in TC) - so some additional parameters were not supported and we fixed this in #13382.

I don't mean to derail the migration to TS here by revisiting this decision, but out of curiosity: Isn't this something we should do in the method decoration system if we had more time? Like – is there a feture missing there?
