### ISSUE TITLE
Highlight plugin version 36 doesn't compile with webpack

### ISSUE THREAD

**Issue by jirivinduska** [ckeditor/ckeditor5#13373]
## 📝 Provide detailed reproduction steps (if any)

1. install newest version of highlight plugin with typescript
2. run webpack build with basic configuration from custom editor build

### ✔️ Expected result

Should compile normally

### ❌ Actual result

Multiple TS2339 errors in HeadingUI.ts 

Property 'listenTo' does not exists on type 'HighlighUi'

### ❓ Possible solution

Include d.ts files

## 📃 Other details

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Thanks for reporting the issue. Unfortunately, the Highlight package contains more than it should. By mistake, we published the source code (TypeScript) too. We expect to publish only JavaScript files so far.

We already fixed the code (https://github.com/ckeditor/ckeditor5/commit/508929b2354a8e2b3890740351423149c2326a6f), but the package needs a new release.

A temporary workaround - force your bundler (webpack / rollup / etc.) to load JavaScript files first.

In the case of webpack, the following configuration could help:

```json
resolve: {
	extensions: [ '.js', '.ts', '.json' ]
}
```

Unfortunately, it might impact other packages, so I wonder whether it is a proper solution.

I will let you know once we decide to push a hotfix on npm.

**Comment by pomek** [comment]
We plan to release a new version of CKEditor 5 packages on Tue (Feb 7th).

**Comment by jirivinduska** [comment]
Thanks for news

**Comment by pomek** [comment]
👉 https://github.com/ckeditor/ckeditor5/releases/tag/v36.0.1
