### ISSUE TITLE
Allow for adding and removing roots from multi-root editor after it was initialized

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#13388]
## 📝 Provide a description of the new feature

Currently, the roots' structure for multi-root is static, i.e., new roots cannot be added after the editor was initialized. Similarly, already exisiting roots cannot be removed.

This makes multi-roots very limiting in how they can be used.

Some important notes:

*   This solution should work in real-time collaboration. If a remote client creates a root, all other connected clients should be appropriately updated.
*   Adding / removing roots should work well with undo. In perfect scenario, you would be able to decide if creating a root is undoable or not, as the expected result may vary from application to application.

---

Related ticket / duplicates: #12235, #6291

**Comment by Inviz** [comment]
new roots can be added, but can't be removed. Additionally detaching root from dom element does not detach observers

**Comment by Inviz** [comment]
https://github.com/ckeditor/ckeditor5/issues/13141 here's reported issue

**Comment by scofalik** [comment]
Thanks for bringing up this issue, I haven't seen it while searching for "multi-root" keyword.

We want to simplify this process, so that multi-root feels natural and there's API that will do most of the work for you.

**Comment by Inviz** [comment]
i'm super excite about it. we have to make a lot of workarounds, e.g. hiding roots instead of deleting them. it's pretty painful
