### ISSUE TITLE
Typescript compiler is removing some important comments.

### ISSUE THREAD

**Issue by mremiszewski** [ckeditor/ckeditor5#13381]
## 📝 Provide detailed reproduction steps (if any)

Some code in `*.ts` files that is marked with `CK_DEBUG` is being removed by Typescript compiler because it's treated as a comment.

### ✔️ Expected result

No lines with `CK_DEBUG` are being removed during compilation.

### ❌ Actual result

Some lines with `CK_DEBUG` are being removed during compilation.

### ❓ Possible solution
Workaround:
```
/**
 * @license 
 */

/**
 * @module 
 */

// ✅ comment followed by an used import

import usedFunc from 'foo'

// ❌ comment followed by an unused import

import unusedFunc from 'bar'

// ❌ comment followed by a type import

import type SomeType from 'sometype'

// ✅ comment followed by a class

/**
 * 
 */
class A {

	// ✅ comment at the beginning of a class 

	constructor() {

	}

	// ✅ comment in the middle of a class 

	/**
	 * doc
	 */
	public method() {
		// ✅ comment inside a method 
		while (true) {
			usedFunc();
			// ✅ comment inside a loop 
		}
	}

	// ❌ comment at the end of a class 
}

// ❌ comment followed by an interface

/**
 * 
 */
interface B {

	/**
	 * doc
	 */
	readonly x: string;
	// ❌ comment inside interface

}

// ✅ comment followed by an export;

export { A };

// ❌ comment followed by a type export;

export type { A as A2 };

// ✅ comment at the end of file
```
Comments with ❌ would be deleted during compilation, and comments with ✅ would be preserved.
All lines in `*.ts` files with `CK_DEBUG` or `CK_DEBUG_<something>` should be investigated whether they are being removed during compilation and moved to a place where they wouldn't.
The same should be done for `*.js` files as the same issue will affect them when they are rewritten to Typescript.

Actual solution:
We should think about a different approach to code that should be available only in debug mode.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by przemyslaw-zan** [comment]
It seems that this behavior cannot be easily disabled:

- [FAQ: Why some comments are not preserved in emitted JavaScript even when --removeComments is not specified?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-some-comments-are-not-preserved-in-emitted-javascript-even-when---removecomments-is-not-specified)

Possibly related:

- [Trivia - Typescript Deep Dive](https://basarat.gitbook.io/typescript/overview/ast/ast-trivia#trivia-apis)
- https://github.com/microsoft/TypeScript/issues/3844
- https://github.com/microsoft/TypeScript/issues/843
- https://github.com/microsoft/TypeScript/issues/23373

**Comment by przemyslaw-zan** [comment]
Solution that seems to work is changing the order of `ck-debug-loader` and `ts-loader` in our [webpack config](https://github.com/ckeditor/ckeditor5-dev/blob/ace62204d8bb3e5e965d45efb14da80b6ae4728b/packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js#L89-L111). Thanks to this, `CK_DEBUG` lines which are needed, will be uncommented before being passed on to TS compiler, and thus will be preserved.

Some caveats:
- We need to ensure that all of the `CK_DEBUG` comments inside TS files are valid TS code that will not throw an error during compilation.
- Comments inside interfaces and other structures that only exist in TS will not be preserved.

**Comment by przemyslaw-zan** [comment]
PRs: _(they have to be used together, either one without the other will not work)_
- https://github.com/ckeditor/ckeditor5/pull/13477
- https://github.com/ckeditor/ckeditor5-dev/pull/840

Despite there being `ck-debug-loader` in manual tests webpack config, there are no `CK_DEBUG` inside manual tests.

**Comment by przemyslaw-zan** [comment]
@mremiszewski Were you you dealing with a specific case when describing this issue? If so, could you please check whether those PRs fix the issue?
