### ISSUE TITLE
Allow for storing additional data related to roots

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#13395]
## 📝 Provide a description of the new feature

Allow for storing additional data related to roots. We already have `RootAttributeOperation` and it is possible to set an attribute on a root element using `writer.setAttribute()`. However it is hard to use them outside of the editing pipeline. There's no simple API that would allow to store "metadata" that is connected with the document but is not the document data itself.

This is especially important for applications that might want to use multi-root editors. If an application "document" is built from multiple, separated editing areas, it is common that these editing areas may also have their own properties that can be changed by users as they edit the document.

It should be possible to easily save and load such additional data and it also should be propagated in real-time collaborative editing.

**Comment by scofalik** [comment]
Some final decisions to be made regarding the API. Do you have an opinion on naming for "additional data" and APIs related with it? We've been talking about root attributes, but currently I call it `metadata`.Why not `attributes` but `metadata`?

1.  I wanted to cut any connotations with regular attributes and how they are used. Also, we have some features that use root attributes, and I don't want it to be mixed with the new thing.
2.  I want to it to be clear that we are introducing something new with new possibilities/different purpose (someone who heard about root attributes would think that this isn't something new).
3.  I want to have a different API for this (esp. on writer to differentiate from regular attributes) and have it easier to be used (so you don't need for example specify a converter or somehow tell the editor that given root attribute is special).
4.  I want people to think about it as data, as something custom, arbitrary, to be saved and loaded.

Another proposal is `properties` but that's close to `attributes`. `metadata` OTOH is close to just "data".

One problem with `metadata` in general is that this concept is new to rich-text editor integrators. Data is pretty obvious, you want to save what you edited and you know that you have to. With `metadata` it is not obvious why or when you should save it, especially since no official plugins use it yet (I see us coming up with some multi-root specific plugins e.g. roots ordering or something). In docs, for such plugins, we will need to visibly highlight that the plugin uses metadata and that data must be saved.

**Comment by oleq** [comment]
Reposting my comment from Slack:

> TBH I’m not sure if this new API should be in the `Editor` namespace. For instance `editor.getMetadata();` .To me, the `Editor` namespace feels like a place for the integrators only, e.g. `setData()`, `getData()` , `enableReadOnlyMode()`, `destroy()`.This whole metadata concept is for developers who build things using the framework. This is an advanced API. It should be behind `editor.model` and `editor.editing` (I know it touches both, so probably somewhere else).
> 
> ---
> 
> A separate topic is that “metadata” is very vague. It could be anything: content/document metadata? Editor (as a HTML component) metadata? Something related to SEO? I think we should make it clear that this is related to multiple roots and the structure of the edited document.

**Comment by Reinmar** [comment]
What worries me here is:

*   On the view layer we have attributes and custom data
*   On the model we have attributes and (? is there something more ?)
*   On the editor level and model root level we have data and metadata

It’d IMO look better if metadata would be only visible on the editor level. If they didn’t leak anyhow to the writer. Then, we would have data and the accompanying metadata. Do you think there’s an option to rething what we have in the writer?Another problem I can see: when looking at the editor intereface, there’s data and then there’s metadata. If you saw it for the first time would you expect comments or track changes information to be metadata? I’m afraid so. Is this mechanism (on the editor layer) capable of becoming a store for comments too?

I remember you were thinking about the future applications of metadata and how the editor interface could look like. That’s where I’d move back for a moment.

**Comment by scofalik** [comment]
Fantastic, a two opposite opinions on where it should go ;).

Let's first clarify, that the changes must go through the model, so they are:

1.  Propagated to other (remote) clients.
2.  Synchronized (made in a correct order) with other changes that are happening in the model/editor.
3.  Probably, it would be beneficial to have a reasonable API to react to them, hopefully resembling/using other mechanisms that we have.

In the end, metadata is kind of data, just stored in a different way.

Thankfully, this is a part where we all agree (as I clarified with @Reinmar in F2F talk).

The question is: do we know everything about metadata? What kind of uses for it can we imagine? Do we think there are more requirements we can learn and how probably it is that it can evolve in a "breaking" way?

Here, I have to admit to @Reinmar that we do not have the whole data gathered. We focused on multi-root uses, with some very strict use cases, like section editing. It may be risky to introduce it heavily on the engine/core side as this might mean more breaking changes in the future.

I personally think that root attributes -- or maybe general data stored synchronized between remote clients -- will be beneficial even for "single root" editors, and something that we may want to have. But I don't have good examples on hand. Instead, it will be better to focus on multi-root use cases.

This means that it will be better to keep as much of the API as possible in multi-root editor. If breaking change happens (e.g. we will introduce a similar (but different) general scenario and what is proposed here will be obsolete) then it will concern smaller audience.

Now, answering some of your questions:

> A separate topic is that “metadata” is very vague. It could be anything: content/document metadata? Editor (as a HTML component) metadata? Something related to SEO? I think we should make it clear that this is related to multiple roots and the structure of the edited document.

1.  Initially, I didn't want to have it just for multi-roots, I wanted it to have in "single root" editors too.
2.  I also didn't want to suggest what can be there and what cannot be there. OTOH, guides and API docs should explain it because, as I wrote, this is a less intuitive topic than just "data".

> To me, the `Editor` namespace feels like a place for the integrators only.

And you are correct. But it has the same reason to be on `Editor` as `Editor.getData()`. It is kind of data, it is something that you want to save with regular data, keep and load to the editor. If you treat the document in a more holistic way and you accept e.g. structured document with sections as a document, it is natural, that sections properties are part of the document data. After saving the document, you may want to use the properties to display things in a different way on your website, or have them handled, managed, post-processed, shared in a different way, etc.

I think that what confuses you and why you don't like it is because we don't have any official plugins using it. I can imagine this may change if we want to explore "section editing space" more and propose some own solutions.

> If you saw it for the first time would you expect comments or track changes information to be metadata? I’m afraid so.

Yes, and I don't have a great idea how to communicate it in a better way other than just have good docs (and examples). As I wrote, it is a problem that you don't know when you should be interested in saving this metadata.

> Is this mechanism (on the editor layer) capable of becoming a store for comments too?

Not in its current form, where metadata is related to roots.

> I remember you were thinking about the future applications of metadata and how the editor interface could look like. That’s where I’d move back for a moment.

I... don't remember it exactly :D, not sure if I had some concrete ideas :D.

**Comment by scofalik** [comment]
New proposal (in PR):

1.  Removed concept of metadata. There's no metadata anywhere. No changes in writer. Root attributes are called root attributes. Simply.
2.  There's much less new code compared to before, which is a plus.
3.  Minimal changes in core/engine. Introduced changes outside multi-root editor are:
    1.  Added `RootAttributeOperation` handling in the `Differ`. However, it should be treated as a past omission.
    2.  Added `EditorConfig#rootsAttributes`. This has a note that it is handled only in multi-root editor.
    3.  There will be changes in `RealTimeCollaborationClient`. It will check if `rootsAttributes` is set.
4.  Other changes are on multi-root editor:
    1.  Added callback for `DataController#init` which uses `rootsAttributes` config value.
    2.  Added `MultiRootEditor#getRootsAttributes()`.
5.  `Writer#setAttribute()` is used to set root attributes. You don't need to add any prefix, etc.
6.  `MultiRootEditor#getRootsAttributes()` return these attributes, that were set in `rootsAttributes` config value.
    1.  Integrator will need to specify all "special" root attribute keys there.
    2.  If root doesn't have an attribute, `null` value must be passed and the attribute must be set.

This way we have:

1.  Much smaller PR.
2.  The solution is more focused on the actual problem-to-solve.
3.  Changes limited mostly to `MultiRootEditor` scope. The only addition is config prop.
4.  The feature is still easy to use (I wanted to avoid things like `editor.registerDataRootAttributeKey( 'foo' )`).
5.  RTC does not need to be heavily changed.
6.  There's no new concept so there's less confusion. `config.rootsAttributes` and `editor.getRootsAttributes()` are better at hinting what are you dealing with.

**Comment by Reinmar** [comment]
> 6\. There's one small drawback. If we introduce a feature that uses roots attributes, the integrator will have to know that they have to start using `config.rootsAttributes` and "init" it with `null` values.

Why do they have to init attributes with `null`? 

Also, it sounds like it applies e.g. to HTMLComments too. So I guess I misunderstood something.

**Comment by scofalik** [comment]
> Why do they have to init attributes with `null`? 

Since `getRootsAttributes()` returns only what was set in `config.rootsAttributes`, then, if we introduce a feature requiring to load and save an attribute, it will have to be specified in `rootsAttributes`. It doesn't have to be `null` but it have to be set.

Unless, of course, at that point, we introduce something like `editor.registerRootAttributeKey( 'foo' )`.

> Also, it sounds like it applies e.g. to HTMLComments too. So I guess I misunderstood something.

HTML comments feature uses roots attributes without any changes. Attributes used by that feature will not be available in `getRootsAttributes()`.
