### ISSUE TITLE
Docs issue report from "api/module_widget_utils.html"

### ISSUE THREAD

**Issue by timblack1-WC** [ckeditor/ckeditor5#13399]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_widget_utils.html#function-viewToModelPositionOutsideModelElement

### Project version

36.0.0

### Is there something missing in the guide? What is it?

The text currently reads:

> cannot be correct mapped to the model

The text should read:

> cannot be correctly mapped to the model

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by godai78** [comment]
Thanks for catching that!
