### ISSUE TITLE
Allow to turn a particular root to read-only mode

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#13390]
## 📝 Provide a description of the new feature

Currently, we support read-only mode for the editor. The limitation is that you have to put the entire editor into this mode. This is not flexible enough for integrations using multi-root editor. It is easy to come up with cases, where you would need to put only some of the editables into read-only mode (e.g. you don't have permissions to change some of the content but you can still comment on it, etc.).

**Comment by kbinieda** [comment]
After doing initial research, I've found out that currently readonly feature is used by plugins in following cases:
- `return null or undefined` after assessing that editor is in read only mode
- binds editor readonly to some property ex. `isEnabled` (usually as one of requirements for flag change).
- implicit usage by disabling commands
- there are also more advanced usages, eg. `watchdog`.

Initial idea of implementation / architectural modelling is to leave current implementation of readonly flag in editor to avoid breaking changes and give possibility to easily block all roots (eg. disabling everything on internet failure). Additionally, it might be beneficial for plugin creators to have knowledge of an active editable and track read only state there. This new attribute will be probably accessible in `editor.ui` space. For more in-depth operations on model there should be also an option to disable particular root. Initial idea is to have a similar flag in `RootElement` model.
