### ISSUE TITLE
Update karma runner config to disable Chrome backgrounding optimizations

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#13407]
## Provide a description of the task

Extracted from https://github.com/ckeditor/ckeditor5/issues/13347.

Karma config should provide additional flags to Chrome:

```
'--disable-renderer-backgrounding', '--disable-backgrounding-occluded-windows'
```

**Comment by pomek** [comment]
👉 https://github.com/ckeditor/ckeditor5-dev/releases/tag/v33.0.1
