### ISSUE TITLE
htmlSupport type not existing but is in docs

### ISSUE THREAD

**Issue by archasek** [ckeditor/ckeditor5#13406]
## 📝 Provide detailed reproduction steps (if any)

![image](https://user-images.githubusercontent.com/2247211/216949134-91b551aa-1926-4f6a-9fd5-384d6d6ea953.png)

### ✔️ Expected result

Typing correct ;-).

### ❌ Actual result

1. [Docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-htmlSupport) - existing
2. Code - missing:
![image](https://user-images.githubusercontent.com/2247211/216949062-2fdb4105-e469-458c-b8f0-a18ead8579bb.png)

### ❓ Possible solution

Add typing

## 📃 Other details
![image](https://user-images.githubusercontent.com/2247211/216949314-32d46bf4-6740-4c8a-9cee-3c5640c9549f.png)

![image](https://user-images.githubusercontent.com/2247211/216949339-8c427209-9175-49f2-9548-7f9aaeab7d5a.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! We're currently [migrating to TypeScript](https://github.com/ckeditor/ckeditor5/issues/11704) and our official typings will be published in ~2 months. From what I can see you used community typings that unfortunately have missing bits and pieces.

What I'd recommend for now is either working around that missing type or making a PR to the [community typings](https://github.com/DefinitelyTyped/DefinitelyTyped).
