### ISSUE TITLE
LinkUI: ContextualBalloon lazy view initialization breaks third party link customisations.

### ISSUE THREAD

**Issue by leevigraham** [ckeditor/ckeditor5#13412]
@niegowski https://github.com/ckeditor/ckeditor5/commit/55d77f10bbdbcd0449d08988b03b5f6f7f596dfe broke custom link plugins as documented by @oleq here: https://github.com/ckeditor/ckeditor5/issues/4836#issuecomment-387718887

Is there an event we can listen to to manipulate the balloon?

// @Reinmar

**Comment by niegowski** [comment]
Here is a new snippet: https://github.com/ckeditor/ckeditor5/issues/4836#issuecomment-1422740830
