### ISSUE TITLE
[TS] Add linter rules for enforcing imports of module augmentation and no explicit return type

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#13434]
This is a follow-up of #13433.

Let's create `eslint` rules that will help to avoid errors described in #13433.
[Error] Eslint rules should throw an error if we import from `src`. 

[Error] We should also have a rule that will enforce no explicit return type in requires() methods. Return type should be inferred. Related to #13714.

Third case: as const, and TBD what to do there (rule, types specs).

Fourth case:
[Error] PluginName returns a specific name (string literal), not a generic string.

**Comment by filipsobol** [comment]
We should also have a rule that will enforce **no explicit return type** in `requires()` methods. Return type should be inferred.

**Comment by Witoso** [comment]
Third case: `as const`, and TBD what to do there.
