### ISSUE TITLE
Remove event does not have documented data

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#1346]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. Use the document example
2. Add an event listener
`editor.editing.downcastDispatcher.on('remove:table', (eventInfo, data, conversionApi) => console.log(data))`
3. Remove the table widget

## ✅ Expected result
According to the DowncastDispatcher documentation, the console should show:
```
{
  sourcePosition: Position, // Position from where the range has been removed.
  range: Range // Removed range (in graveyard root).
}
```

## ❎ Actual result
```
{
  position: Position, // Position from where the range has been removed.
  length: number
}
```

## 📃 Other details that might be useful
Also for attribute changes, they get fired when a element with attributes are inserted, but not when the element get removed. The documentation says the attribute event gets fired when they are added/changed/removed.
Since the adding of an element with attributes fires the attribute event for each one, it seams fair that the removing of an element also fired it.

**Comment by scofalik** [comment]
Thank you for pointing this out! Those are sometimes overlooked when doing multiple refactorings. You are right that `remove` event parameters have changed.

As for attribute events, I am not sure if I understand you correctly or maybe you misread the documentation. It says:

> Fired when attribute has been added/changed/removed from a node. Also fired when collapsed model selection attribute is converted.

So the attribute is fired whenever *an attribute* is added, changed or removed from a node.

It is true, however, that the documentation is missing the fact that the event is also fired when a node with an attribute is inserted.

> it seams fair that the removing of an element also fired it.

From our experience, it didn't matter yet. Most elements are removed in a default way (well... they are just removed) and there is no need to handle attribute removal in any way. For example, there is no need to unbold some text before removing it from view/DOM.

I could imagine a complex feature that would want to do something if an attribute is removed, though. In that case, you could listen to `remove` event and check if removed nodes had that attribute. It might be a little inefficient but is doable. It would be less inefficient if the attribute can be set only on certain elements (then you could listen to `remove:myElement`).

**Comment by dkrahn** [comment]
Thanks for the fast reply @scofalik.

> From our experience, it didn't matter yet. Most elements are removed in a default way (well... they are just removed) and there is no need to handle attribute removal in any way. For example, there is no need to unbold some text before removing it from view/DOM.

The insertion method goes through the work of firing the attribute events, but the remove doesn't. It would be important to have this information on removal for example with an image, I could remove the image from the server once it is removed from the editor. So IMHO, it seams fair/desired to have some kind of control over who is being removed.

**Comment by scofalik** [comment]
You can listen to `remove:image` event in that case. Of course, if this is a general attribute that could be attached to any element, then you need to listen to `remove`.

As I wrote, this is more hassle, but is doable right now. I can see us providing this in the engine if there is high demand for this.

**Comment by dkrahn** [comment]
This gives me that an image was removed... not which image was removed.

**Comment by scofalik** [comment]
You are right, actually, getting to the model image is not straightforward. What's more, you don't really know if the image was actually removed or moved around (this will be the case when we will introduce drag and drop).

I guess the workaround for now could be this:

```javascript
downcastDispatcher.on( 'remove:image', ( evt, data, conversionApi ) => {
    const viewPosition = conversionApi.mapper.toViewPosition( data.position );
    // Here it would be good to actually "look right" until the image element is found, because there
    // might be some empty elements or UI elements between `viewPosition` and the image.
    const viewElement = viewPosition.nodeAfter;
    const modelElement = conversionApi.mapper.toModelElement( viewElement );
    
    // Read model attributes from `modelElement`.
    // ...
} );
```

Mind you, I haven't tested the code above, but this is the first that came from the top of my head. Let me know if it was useful.

Unfortunately, the `Differ` (it feeds dispatcher with information) does not provide the info where the elements were moved, only what has changed. This could turn out into an issue in the future, so we will need to think about it.

**Comment by scofalik** [comment]
I've updated snippet above with removal check.

**Comment by dkrahn** [comment]
Perfect @scofalik! Works like a charm.

I was almost checking changes in the `$graveyard`:
```
modelDocument.on('change:data', (evt, batch) => {
	const changes = modelDocument.differ.getChanges({ includeChangesInGraveyard: true });

	for (const entry of changes) {
		if (entry.type == 'insert' && entry.name == 'image' && entry.position.root.rootName == '$graveyard') {
			const modelElement = entry.position.nodeAfter;
			// Read model attributes from `modelElement`.
		}
	}
});
```

Thanks for all the help!

**Comment by scofalik** [comment]
@dkrahn To be honest, I got fixed on the conversion part and getting attributes there.

I actually think that in your use case, checking `change:data` is a better place to check for what you want to check. So I guess that your code is fine too (or maybe even better... if it works :)).

**Comment by dkrahn** [comment]
Complementing, I found this solution after checking the ImageUploadEditing plugin that cancels the upload if it was still processing. =)

**Comment by scofalik** [comment]
So, to sum this whole discussion up, I think that checking `change:data` event is, let's call it, more semantically correct. Conversion is processing changes from model to view. `change:data` is a place to do something extra in a reaction to the model changes.

So as I said above, I wanted to try to solve this attributes-during-remove-conversion problem, but it would be better to use your original solution.

**Comment by scofalik** [comment]
PS. I think that you are right that listening to `remove:image` might be a little more efficient, but the difference is hugely marginal.

**Comment by dkrahn** [comment]
Thanks for all the help @scofalik!
