### ISSUE TITLE
[TS] Verify & fix API Docs via umberto

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#13464]
After all tasks, that are part of #12027 are done, let's verify if API docs are actually working with `umberto`.

Scope:

*   Build docs with flag to use TypeDoc.
*   Fix all the errors and warnings.
*   Click thought all the API Docs and check if they seem ok (TBD, how exactly).

**Comment by niegowski** [comment]
> Click thought all the API Docs and check if they seem ok (TBD, how exactly).

**Comment by Reinmar** [comment]
We resolved 99% of issues so far. I think the remaining 1% deserve a separate issue. Let's celebrate here the progress we made :)
