### ISSUE TITLE
[Docs] Problem with sticky toolbar placement on mobile

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1348]
Cross posting since we're not sure which side is responsible (Umberto or CKE5):

![2018-11-09 13 01 33](https://user-images.githubusercontent.com/247363/48261681-2a9fc400-e420-11e8-88ce-f83d3485212d.jpg)

**Comment by Reinmar** [comment]
This is tricky. We need to know whether the docs are rendered in a narrow viewport or normal and reconfigure the toolbar offset.

**Comment by Reinmar** [comment]
PS. I'd ignore for now the case when someone resizes the viewport. Let's only care about the initial position.
