### ISSUE TITLE
ckeditor5 pre code or highlight.js | prism.js

### ISSUE THREAD

**Issue by woisk** [ckeditor/ckeditor5#1354]
How to integrate code to highlight? <pre><code></pre></code>

HTML, c++, C, PHP

**Comment by Reinmar** [comment]
This is a DUP of https://github.com/ckeditor/ckeditor5/issues/436

**Comment by woisk** [comment]
Thank you! Does the support plan have accurate time schedule? Well, look forward to coming soon.

[or] can now provide a simple implementation of Pre code...

Now that there are many kinds of code manufacturers, it is very convenient for us to integrate quickly.

Another: If the documents of ckeditor 5 are organized or easy to understand, just like those of ckeditor 4, fans around the world can also make better wheels. Is that OK?

**Comment by woisk** [comment]
Thanks for the answer! Lovers from Pingdingshan, Henan, China

**Comment by Reinmar** [comment]
> Does the support plan have accurate time schedule? Well, look forward to coming soon.

No. This feature is not planned at the moment. It's high on our priority list, but so do many other features.

> [or] can now provide a simple implementation of Pre code...

Please refer to the ticket I linked. It contains links to community attempts at implementing this feature.
