### ISSUE TITLE
Avoid extending build by importing their `src/ckeditor` file

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13552]
## Provide a description of the task

Several snippets extend the `@ckeditor/ckeditor5-build-*` packages.

https://github.com/ckeditor/ckeditor5/blob/bb91227a4fdc727a235bf0eadf59193fd7497451/docs/_snippets/examples/balloon-block-editor.js#L8

However, the `src/*` directory is not published on npm. So, it accidentally works on local environments.

When uber CI builds snippets, it behaves like it uses packages from npm, but takes the code from the master branches and prepares JavaScript packages.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/2270764/221188638-d0c08ff3-03b4-4df5-ae6d-23155b9c3ef0.png">

It causes uber CI fails because these snippets try to import a TypeScript file, so the `tscofnig.json` is required. We do not publish internal things.

I was trying to make a temporary fix by adding the `tsconfig.json` to the `ckeditor5` package to fix the following error:

```
[tsl] ERROR
      TS6053: File 'ckeditor5/tsconfig.json' not found.
 @ ./node_modules/umberto/source/ckeditor5/36.0.1/_snippets/features/blocktoolbar.js 8:0-75 14:0-15:8 16:11-46
ERROR in ./node_modules/@ckeditor/ckeditor5-build-balloon/src/ckeditor.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
```

Unfortunately, it generates another one:

```
[tsl] ERROR in /Users/pomek/Projects/cksource/ckeditor5-integration-ci/ckeditor5/node_modules/@ckeditor/ckeditor5-build-classic/src/ckeditor.ts(91,2)
      TS2322: Type '{ toolbar: { items: string[]; }; image: { toolbar: string[]; }; table: { contentToolbar: string[]; }; language: string; }' is not assignable to type 'EditorConfig'.
  Object literal may only specify known properties, and 'image' does not exist in type 'EditorConfig'.
 @ ./node_modules/umberto/source/ckeditor5/36.0.1/_snippets/build-classic-source.js 8:0-75 12:23-36 13:0-33 14:0-33
```

So, we need to fix snippets.

**Comment by Reinmar** [comment]
> When uber CI builds snippets, it behaves like it uses packages from npm, but the takes the code from the master branches and prepares JavaScript packages.

Why does it work this way?

It may be confusing, unfortunately. I vaguely remember some reasons, but it might have not matured well.

**Comment by pomek** [comment]
Mhm. Because we want to obfuscate private packages.

**Comment by pomek** [comment]
Another possibility to resolve the issue is to migrate builds to JavaScript packages. TypeScript does not provide any value here. We can still generate typings from JS files.

**Comment by pomek** [comment]
If we do as you type, the snippet adapter will use the code from #master. It includes private repositories too.

**Comment by pomek** [comment]
> ```
> [tsl] ERROR in /Users/pomek/Projects/cksource/ckeditor5-integration-ci/ckeditor5/node_modules/@ckeditor/ckeditor5-build-classic/src/ckeditor.ts(91,2)
>       TS2322: Type '{ toolbar: { items: string[]; }; image: { toolbar: string[]; }; table: { contentToolbar: string[]; }; language: string; }' is not assignable to type 'EditorConfig'.
>   Object literal may only specify known properties, and 'image' does not exist in type 'EditorConfig'.
>  @ ./node_modules/umberto/source/ckeditor5/36.0.1/_snippets/build-classic-source.js 8:0-75 12:23-36 13:0-33 14:0-33
> ```

We may have some issues with typings. Should the entry point of the image package include its configuration?

https://github.com/ckeditor/ckeditor5/blob/bb91227a4fdc727a235bf0eadf59193fd7497451/packages/ckeditor5-image/src/index.ts#L6-L33

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-image/src/imageconfig.ts

**Comment by pomek** [comment]
Steps to reproduce the mentioned issue on local env:

* Clone the uber CI repo.
* Check out to `ck/13552-debug`.
* Execute `./scripts/bootstrap-repositories.sh` from the uber CI root dir.
* Go to cloned ckeditor5 dir (`cd ckeditor5`).
* Execute `node ../scripts/transpile-typescript-packages.js` - converts TS to JS (including the obfuscation step).
* Converted packages will be moved to `ckeditor5/node_modules/`
* Execute `yarn run docs --skip-api --dev --guides "**/examples/**"`

Notes:

* The transpile script also obfuscates the CS client. If you need to rerun the script, reinstall deps in CKE 5 and reset the CS client repo (`git checkout .` is enough) before.

**Comment by Reinmar** [comment]
I'm still trying to understand the problem, what brought us here and why. So I'll try to go one by one and correct me if I got something wrong.

I'll start from the end.

1.  The resulting issue. On uber CI, when building snippets in the documentation, the build crashes. It crashes because some snippets extend `ckeditor5-build-*/src/*.ts` files. Those files are not available in that type of CI build. Importing them in snippets code causes an error.
2.  Why aren't those TS files available there? They are present in our dev env and exist on GitHub? Why aren't they present on uber CI?
    1.  Answer: They aren't available on uber CI because we tried to avoid leaking closed-source code to nightly docs. In other words: On nightly docs we should not have snippets built straight from closed-source code like we have it on GitHub.
3.  Why?
    1.  Answer: That's because that code isn't secured with license checks and is not properly obfuscated.
4.  When do we secure and obfuscate closed-source code?
    1.  Answer: When publishing it to npm.
5.  To completely prevent any chance of closed-source code landing in nightly docs, the uber CI scripts prepares the code of each private package by doing similar steps that are done during publishing the code to npm.
6.  Finally, that wipes out the `src/` directory of each build. (in fact, it does more – it also turns TS into JS so that'd be another difference)

Did I get it right?

**Comment by Reinmar** [comment]
Assuming that my above comment is correct – question: We want to secure the commercial features here. Why aren't we obfuscating only them? Why do we change the content of other packages too? Wouldn't the simplest solution be to narrow the scope of packages that we're touching?

**Comment by pomek** [comment]
The production and nightly docs should differ only one thing – the source of the code. Production = `#stable`, while nightly means `#master`. The entire process of building them should be the same.

If we do not change anything here, the production docs will crash once we publish CKEditor 5 builds as TypeScript.

Everything worked fine before migrating builds to TS accidentally because JavaScript does not have to be converted by any loader in webpack. When builds are specified as TS files, they go through webpack. They try to load `tsconfig.json`, which should not be published and causes errors.

In fact, we have two independent issues:

1. A way of how we extend builds in snippets.
2. Missing typings in the `EditorConfig` interface (https://github.com/ckeditor/ckeditor5/issues/13552#issuecomment-1443709230).

The first is needed before publishing a new major (stable) release, but unfortunately, it breaks the uber CI. A workaround could work for some time when we resolve the second problem, which is a blocker of the alpha release, as an integrator cannot create a custom build in TS using CKEditor 5 JS + typings.

**Comment by pomek** [comment]
> 2. Missing typings in the `EditorConfig` interface (https://github.com/ckeditor/ckeditor5/issues/13552#issuecomment-1443709230).

A temporary fix published on the [`#ck/11722-fix-ci`](https://github.com/ckeditor/ckeditor5/compare/master...ck/11722-fix-ci) branch helps.

**Comment by Reinmar** [comment]
> The production and nightly docs should differ only one thing – the source of the code. Production = `#stable`, while nightly means `#master`. The entire process of building them should be the same. It means that nightly docs should treat the code as it would come from npm.

I totally agree that the processes should be as close to identical as possible. That gives us foundation for predictability. Something works here, it will work there.

However, I wonder if we really need to try to make it work like the code was installed from npm.

We build docs in 3 environments:

*   development (locally, when we test things)
*   `#stable` when publishing docs to ckeditor.com
*   `#master` when publishing nightly docs

In the first case we are naturally using everything straight from GH. We won't change that, of course.

So, maybe building docs for the two other channels could work like locally but with an additional step that secures, obfuscates and verifies that no source code leaked through that? This way we would make the CIs more "familiar" to us.

Are we far from there? Would this be possible?

NOTE: I'm not talking here about doing it today but rather about a longer term vision.

**Comment by pomek** [comment]
Mhm. Github closed the issue due to `Closes` annotation that pointed to another issue. I am reopening and marking it as a release blocker (next major).

**Comment by pomek** [comment]
Quoting myself to answer why it must be resolved:

> If we do not resolve the issue mentioned in the first post, the production docs will crash once we publish CKEditor 5 builds as TypeScript.

**Comment by pomek** [comment]
Our code snippets in docs are invalid too. CKEditor 5 builds cannot be extended this way. We cannot add plugins to existing builds without rebuilding them.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/2270764/225052030-ea9b6017-c7ee-4c5b-bde7-e3e1355aa50b.png">

**Comment by pomek** [comment]
PRs:

* https://github.com/ckeditor/ckeditor5/pull/13683
* https://github.com/cksource/collaboration-features/pull/5058

I didn't touch guides. I focused on snippets only.

**Comment by apadol-cksource** [comment]
> PRs:
> 
> *   [Do not extend builds by importing their `src/ckeditor` files #13683](https://github.com/ckeditor/ckeditor5/pull/13683)
> *   [Do not extend builds by importing their `src/ckeditor` files cksource/collaboration-features#5058](https://github.com/cksource/collaboration-features/pull/5058)
> 
> I didn't touch guides. I focused on snippets only.

Doing it this way we're not presenting predefined builds in examples. The previous way also was using source so actually, there is no regression but the final solution should be rethought or we will need to change the category from predefined builds to editor types.

**Comment by pomek** [comment]
That's fair point. So, in Examples I should import a compiled build instead of its sources.

**Comment by pomek** [comment]
Example of "Document editor" in our documentation contains the `TableColumnResize` plugin while the decoupled-document build [does not include it](https://github.com/ckeditor/ckeditor5/blob/49f65a755e2eb0d7c20c9d61b8a589fdf1bfb1db/packages/ckeditor5-build-decoupled-document/src/ckeditor.js).

**Comment by pomek** [comment]
I reverted the following samples:

* docs/_snippets/examples/balloon-block-editor.js
*  docs/_snippets/examples/balloon-editor.js
*  docs/_snippets/examples/inline-editor.js
*  docs/_snippets/examples/multi-root-editor.js

The "Document editor" sample needs much more work.

**Comment by Reinmar** [comment]
As for the PR itself. Do we need that much duplication? I can see that the contents of `build-*/src/ckeditor.js`  was copied to every place where that file was imported.

What if we created `ckeditor5/docs/_snippets/build-classic-source.js` **with the contents of** `build-*/src/ckeditor.js` and imported `ckeditor5/docs/_snippets/build-classic-source.js` wherever where `ckeditor5-build-classic/src/ckeditor.js` was used before? That would keep the entire logic still in one place.

**Comment by pomek** [comment]
I will figure out how to decrease the size of the PR.
