### ISSUE TITLE
The demo CK editor 5 on ckeditor.com is inactive in both Chrome and Firefox

### ISSUE THREAD

**Issue by serena-yu17** [ckeditor/ckeditor5#1355]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

ckeditor5-build-classic-1.0.0 (i.e. the version used on https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html#classic-editor)

## 📋 Steps to reproduce

1. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html in Chrome 70.0.3538.102 (Official Build) (64-bit)
2. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html in Firefox 63.0.1 (64-bit)

## ✅ Expected result
To see  a CK editor functional

## ❎ Actual result
The webpage is shown as regular HTML and is not editable if click or type on the test paragraph

![1](https://user-images.githubusercontent.com/12408446/48463250-8fe42280-e82f-11e8-9942-8f5233b1401a.PNG)

## 📃 Other details that might be useful

Console error message from Chrome:
----------------
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
classic-editor.js:21 Error: Network Error
    at XMLHttpRequest.i.addEventListener (token.js:178)
ClassicEditor.create.then.catch.e @ classic-editor.js:21

------------------------
Console error message from Firefox:
---------
Error: "Network Error"
	_refresh https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:325556
classic-editor.js:21
<anonymous>
classic-editor.js:21

**Comment by Reinmar** [comment]
All green in my case:

![image](https://user-images.githubusercontent.com/156149/48471661-b5076f80-e7f4-11e8-86cb-0bfe7ff0108e.png)

Don't you have some DNS/network issues? Did you try on different machines/networks?

**Comment by serena-yu17** [comment]
I posted that in the afternoon at my company and now I am at home. It works perfectly at home.

Since my company used some third-party content filtration service, I guess something was classified as inappropriate and was blocked by the firewall.

**Comment by Reinmar** [comment]
Thanks for letting us know!
