### ISSUE TITLE
Improving module augmentation

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#13565]
We need to improve how we deal with module augmentation ([explained in more details here](https://github.com/ckeditor/ckeditor5/issues/13433)), to:

*   ensure that module augmentation kicks in when importing individual plugins from packages,
*   all types are available in tests,
*   avoiding arbitrary `import './config'` imports.

To encourage best practices and ensure that the `.d.ts` file with module augmentation is always imported, we will require importing all package contents from the main `index` file instead from individual files in the built package, eg.:

```
// ✔️
import { Table } from '@ckeditor/ckeditor5-table';

// ❌
import Table from '@ckeditor/ckeditor5-table/src/table';
```

**Comment by filipsobol** [comment]
Checklist for migrating packages to the new structure:

*   [ ] Copy `tsconfig.json` and `tsconfig.release.json` from `table` plugin.
*   [ ] Create `src/augmentation.ts` file.
*   [ ] Search for all `declare module '@ckeditor/ckeditor5-core'` declarations and move them to the `src/augmentation.ts` as done in [this file](https://github.com/ckeditor/ckeditor5/pull/13568/files#diff-d5a4789418e06b3d342d850f83c33c3abed982ab24fd88a14059b72e69f68979).
*   [ ] Remove all `import '../xxxconfig'` imports.
*   [ ] Add `import './augmentation';` at the very bottom of the main `index.ts`.
*   [ ] Replace **all imports in the monorepo** referencing individual files in the `src` of the package to use the package name instead. See example and regex below.

Example:

```typescript
// BEFORE
import Table from '@ckeditor/ckeditor5-table/src/table';

// AFTER
import { Table } from '@ckeditor/ckeditor5-table';
```

  
Regex (**commit your changes before trying this**):

```
Search for: import (.*) from '<PACKAGE_NAME>/src/(.*)';
Replace with: import { $1 } from '<PACKAGE_NAME>';

⚠️ Make sure that all files imported this way are actually exported from the main `index.ts` file.
```

**Comment by filipsobol** [comment]
Below is the summary of the changes introduced in PR #13568 to fix module augmentation and tests within monorepo. The same changes (following the checklist above) will be applied to all packages using module augmentation.

### Module augmentation not being loaded in all cases

Previously, module augmentation was spread between many files and not visible in some other files. To mitigate this, we added `import 'xxxconfig';` declarations to load files containing needed augmentations. However, because imports in source `.ts` files and output `.d.ts` files are different, the code that worked fine during the development didn't always work when the package was built and published.   
  
 

### Fix loading of `tsconfig.json` in manual and automated tests

While investigating issues with tests, we [noticed that it loads seemingly arbitrary `tsconfig.json` files](https://github.com/ckeditor/ckeditor5/pull/13568#issuecomment-1450154751). Once this issue was fixed, we no longer needed to have `tsconfig.json` (used for testing and loaded by IDE) and `tsconfig.release.json` (used for building) for each package. Because tests are always ran from the root-level of the whole project, we not have `tsconfig.test.json` file used specifically for that purpose, and each package now only have a single `tsconfig.json` file used by IDE and for building.

**Comment by Reinmar** [comment]
Status page of porting all the packages to the new format: https://chill-saturn-f1f.notion.site/Augmentation-migration-62971d5b535e4f7c982fe78d2acd3f0e
