### ISSUE TITLE
Image caption plugin uses translations from table caption plugin

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#13588]
## 📝 Provide detailed reproduction steps (if any)

A German user reported on Transifex that the “Toggle caption on/off” labels are in the [table plugin language files](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-table/lang/translations/en.po#L251) (so in the case of German, they were translated to “Tabellenüberschrift aktivieren/deaktivieren” = “Toggle table caption on/off”) while it seems the same translations are being used by the image caption plugin.

This seems to be confirmed in the German demo on https://ckeditor.com/ckeditor-5/demo/internationalization/.

1.  Open the German demo on https://ckeditor.com/ckeditor-5/demo/internationalization/.
2.  Create a table, check the table toolbar, see "Tabellenüberschrift aktivieren/deaktivieren" as a label for the "Toggle caption on/off".
3.  Add an image, check the image toolbar, see "Tabellenüberschrift aktivieren/deaktivieren" as a label for the "Toggle caption on/off".

### ✔️ Expected result

_Image caption should not use a translation from the table caption._

### ❌ Actual result

_Image caption uses a translation from the table caption which, in some languages, was translated to "Toggle table caption on/off"._

### ❓ Possible solution

_Image caption should use its own translation or a common one. Note that the meta description from the table caption describes it as "The button label for the table toolbar showing/hiding caption attached to the table." so it's hard to understand why it is used by the image caption plugin._

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by goapunk** [comment]
Any update on this one? The German wording doesn't make sense and is misleading. Would be awesome to have a fix :)

**Comment by Witoso** [comment]
Yes, we will take a look at this together with #15397.

**Comment by goapunk** [comment]
@Witoso thanks!
