### ISSUE TITLE
CKEditor5 on copy pasting table from excel sheet or word doc doesnt retain table cell background color and looses all formating

### ISSUE THREAD

**Issue by vijendrapatil** [ckeditor/ckeditor5#13586]
[Sample Test Table Data.xlsx](https://github.com/ckeditor/ckeditor5/files/10860341/Sample.Test.Table.Data.xlsx)

## 📝 CKEditor5 on copy pasting table from Excel Sheet or word doesnt retain table cell background color\formating

1.Copy table from attached excel sheet 
2.Paste it in CKEditor5 Demo page https://ckeditor.com/ckeditor-5/demo/html-support/
3.Table looses background color and text font format

### ✔️ Expected result

Table after copying to ckeditor5 should retain the text formating.

### ❌ Actual result

Table looses background color and text font format

### ❓ Possible solution

CKEditor4 retain text and column formatting of table after copying the same table from attached file into CKEditor4 https://ckeditor.com/ckeditor-4/demo/

## 📃 Other details

* Browser: Chrome, MS Edge, Firefox, Opera
* OS: Windows, Ubuntu, Mac
* First affected CKEditor version: Unknown (So far observed in CKEditor 5)
* Installed CKEditor plugins: N\A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by vijendrapatil** [comment]
[
[Sample Test Table Data.xlsx](https://github.com/ckeditor/ckeditor5/files/10860293/Sample.Test.Table.Data.xlsx)
](url)

**Comment by tuannmNhanhDev** [comment]
We have same this issue , when i copy table from google sheet and paste it to the editor , nothing happen after paste and i check the console log tab of broswer show this error message like image
![image](https://user-images.githubusercontent.com/66460998/227836215-b8944fab-2e0f-4a35-ab04-4a46b70e203d.png)
and google sheet file like imge:
![image](https://user-images.githubusercontent.com/66460998/227836310-6b61b3f7-c076-4094-8754-d881fde0c100.png)
Any idea or solution for this issue?
My config Html Support is:
![image](https://user-images.githubusercontent.com/66460998/227836487-3d7bc79a-f8b9-4c02-87ea-5ab9e82350b5.png)

**Comment by Reinmar** [comment]
Resolved by [Paste from Office Enhanced](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html).
