### ISSUE TITLE
Prevent plugins from crashing when used with multi-root editor due to using "default root"

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#13596]
## 📝 Provide detailed reproduction steps (if any)

Following plugins are not compatible with multi-root editor because they use "default root" (they assume there is just one root named `'main'`):

*   table resize,
*   word count,
*   title,
*   PDF/Word export,
*   block toolbar,
*   mini-map,
*   html comments.

There is also full page editing but I wouldn't consider integrating with it necessary. As for PDF/Word export, this can be integrated using custom data callback but it would be nice to improve it, so providing custom callback is not necessary.

Also, it would be good to search the code for `.getRoot()` and `.getDomRoot()` usages and maybe similar if you will stumble upon any.

**Comment by huzedong2015** [comment]
Will table resizing not support multi root editor in the future?
