### ISSUE TITLE
Feature request: Toolbar customization

### ISSUE THREAD

**Issue by ZeGregg** [ckeditor/ckeditor5#136]
Would be nice to provide a way to let users/developpers build their own toolbar from scratch by using dropdown, switcher… Sometime we want to have basic style (Bold - Italic - Underline…) grouped under a dropdown, color and background-color grouped in a dropdown with a switcher to switch from color to background-color. Also it would be nice to have popover to edit link, td, img…

**Comment by Reinmar** [comment]
Hey, thanks for the ideas!

We're certainly thinking about these features. In general, the whole architecture has been redesigned to be a lot more flexible so even if we won't code some things ourselves, that will be fairly easily doable.

I opened an issue for the toolbar configuration thing – https://github.com/ckeditor/ckeditor5-design/issues/143. We'll be discussing the topic there. As for link, td and img, we'll start discussion once we have something more to say about them. Feel free to open more tickets in https://github.com/ckeditor/ckeditor5-design and comment on existing ones if you have more ideas.
