### ISSUE TITLE
Loading HTML with ids in heading tags fails to recognize headings

### ISSUE THREAD

**Issue by Zlkva** [ckeditor/ckeditor5#13607]
## Preface

I already have a custom function that appends the content of a heading tag with an ID, the ID is then set to a sluggified version of the heading tag content.

Ex:
`<h1>Welcome!</h1>`
Converts to:
`<h1 id="welcome">Welcome1</h1>`

This is the piece that accomplishes that

```js
function setHOne(editor) {
  editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on('insert:model_h1', (evt, data, conversionApi) => {
    let head = 'heading1'
    if (data.item._children._nodes.length > 0 && data.item._children._nodes[0]._data !== null && data.item._children._nodes[0]._data !== undefined && data.item._children._nodes[0]._data.length > 0) {
      head = slugify(data.item._children._nodes[0]._data, {replacement: '_', lower: true, strict: true}) 
    }
    const viewWriter = conversionApi.writer; 
    viewWriter.setAttribute( 'id', `${head}`, conversionApi.mapper.toViewElement(data.item) )
    });
  });
}
```

See more here: #8451

## 📝 Provide detailed reproduction steps (if any)

1. Project is using the following:

@ckeditor/ckeditor5-react
Custom build of ckeditor5 from ckeditor website

2. Have the editor load existing (saved) HTML content from server that contains a heading tag (`<h1>` etc) that also includes an ID

### ✔️ Expected result

Content is loaded exactly as it was saved previously

### ❌ Actual result

All headings (that contain ID tags) are stripped and are replaced with `<p>` tags

### Thoughts

I believe the issue here is that the ID on the heading element is the problem when loading content. I need to tell CKEditor that the ID is allowed/expected.

I've seen issues that bring this up and their answer was to modify the schema, however I believe this requires building a custom version of CKEditor. 
(Something I've tried and failed at doing. I hit duplicate modules errors just by using the provided documentation...)

Hopefully there's a middle ground someone can inform me of.

**Comment by Witoso** [comment]
Hey @Zlkva, thanks for reaching out! Actually, the behavior you are trying to achieve may work out of the box with some of the plugins:

1.  [**General HTML Support**](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html) **-** it will enable the id on the h\* tag.
2.  [**Headings**](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-custom-heading-elements) - enable h1, as by default we are starting the headings from h2.

GHS is not a part of the classic build, so you would need to prepare a build with it ([online builder](https://ckeditor.com/ckeditor-5/online-builder/) may help here).

If you still want to create your own customization, I highly recommend the [abbreviation](https://ckeditor.com/docs/ckeditor5/latest/framework/plugins/abbreviation-plugin/abbreviation-plugin-level-1.html) tutorial which explains the details of how to inform the model about the new schema.

**Comment by Zlkva** [comment]
@Witoso Thanks for the assistance on my issue.

I went ahead and built a new custom version of CKEditor5 that included GHS (I already had Headings).
Unfortunately this did not seem to resolve the problem I'm having, so at this point I'm mostly stumped.

I've recorded a video of the behavior I'm seeing in hopes that it assists either yourself or someone else in diagnosing the problem.
https://www.youtube.com/watch?v=aNPSIpPd6ec

Additional information that I did not include originally is that I am building with React/NextJS, I'm unsure if that would affect anything.

The editor is being called by using a NextJS dynamic import with ssr disabled. 

```js
import dynamic from "next/dynamic";
const Editor = dynamic(() => import("../TextEditorAdvanced"), {
  ssr: false
});```

**Comment by Zlkva** [comment]
@Witoso I also wanted to ask if it would be possible to re-open this ticket in case someone else has an answer for my problem.

Thanks!

**Comment by Witoso** [comment]
What I see from the video is that:
* On launching the editor with content the headings are gone.
* The editor accepts the change to the heading, but onBlur those are gone.

which kind of points to the direction that something is off in the data layer.

Unfortunately, I cannot debug it remotely but I will try to give you some directions:
* check the bare editor without any changes to its logic, custom plugins, etc. You can even test your content in our demo, just paste it to the Source, and see what happens: https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html. Maybe even add the source plugin to your version.
* play with our inspector ([bookmarklet](https://ckeditor.com/docs/ckeditor5/latest/framework/development-tools.html#ckeditor-5-inspector)), it will allow you to see how the model and view are understood by the editor.

**Comment by Zlkva** [comment]
@Witoso Thanks for your response!

I started tearing apart my configuration and found that removing the Heading configuration from my editorConfiguration constant resolved the issue (kinda, it still stripped the existing ID from headings)

I'm including my heading configuration in case you see something that may be causing an issue.

```js
      heading: {
        options: [
          { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
          {
            model: 'model_h1',
            view: {
              name: 'h1',
              attributes: {
              }
            },
            title: 'Heading 1',
            class: 'ck-heading_heading1',
            converterPriority: 'high'
          },
          {
            model: 'model_h2',
            view: {
              name: 'h2',
              attributes: {
              }
            },
            title: 'Heading 2',
            class: 'ck-heading_heading2',
            converterPriority: 'high'
          },
          {
            model: 'model_h3',
            view: {
              name: 'h3',
              attributes: {
              }
            },
            title: 'Heading 3',
            class: 'ck-heading_heading3',
            converterPriority: 'high'
          },
          {
            model: 'model_h4',
            view: {
              name: 'h4',
              attributes: {
              }
            },
            title: 'Heading 4',
            class: 'ck-heading_heading4',
            converterPriority: 'high'
          }
        ]
      }
```

**Comment by Witoso** [comment]
```
{
  model: 'model_h1',
  view: {
    name: 'h1',
    attributes: { id: 'welcome' } // <- id added to attributes
  },
  title: 'Heading 1',
  class: 'ck-heading_heading1',
  converterPriority: 'high'
}
```
Looks like the problem lies in the empty attribute object. I tested this configuration, and it looks like it's working. Btw in this setup, the General HTML Support plugin is not needed.

**Comment by Reinmar** [comment]
The goal wasn't to apply the same id to all \<h1> headings, so it cannot be specified in the Heading feature config.

But you're right @Witoso that the `attributes` key cannot be an empty object (as used by @Zlkva  in [https://github.com/ckeditor/ckeditor5/issues/13607#issuecomment-1472809109).](https://github.com/ckeditor/ckeditor5/issues/13607#issuecomment-1472809109).) It breaks the upcast conversion.

So, we need two things here:

*   An improved version of the code adding slugs (there are some issues in it).
*   And a correct config for headings that will enable h1-hX headings.

Example below works correctly.

Please read the comments that I added.

```javascript
/**
 * @license Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

/* globals console, window, document */

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import ArticlePluginSet from '@ckeditor/ckeditor5-core/tests/_utils/articlepluginset';

function slugify( str ) {
	return str.replace( /[^\w]/g, '-' );
}

function setHOne(editor) {
	editor.conversion.for( 'dataDowncast' ).add( dispatcher => {
	  dispatcher.on('insert:model_h1', (evt, data, conversionApi) => {
		let head = 'heading1';

		// DO NOT USE PRIVATE PROPERTIES.
		// There are public methods/properties exposing the same data.
		if (data.item._children._nodes.length > 0 && data.item._children._nodes[0]._data !== null && data.item._children._nodes[0]._data !== undefined && data.item._children._nodes[0]._data.length > 0) {
			head = slugify(data.item._children._nodes[0]._data);
		}

		const viewWriter = conversionApi.writer;

		viewWriter.setAttribute( 'id', `${head}`, conversionApi.mapper.toViewElement(data.item) )

	  },
	  // Important to use a low priority observer so the default converter for headings
	  // is executed before this one. Otherwise, there will be no view element yet
	  // when we try to set a slug on it.
	  { priority: 'lowest' } );
	});
  }

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ArticlePluginSet, setHOne ],
		toolbar: [
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'bulletedList',
			'numberedList',
			'|',
			'outdent',
			'indent',
			'|',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'undo',
			'redo'
		],
		image: {
			toolbar: [ 'imageStyle:inline', 'imageStyle:block', 'imageStyle:side', '|', 'imageTextAlternative' ]
		},
		table: {
			contentToolbar: [
				'tableColumn',
				'tableRow',
				'mergeTableCells'
			]
		},
		heading: {
			options: [
			  { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
			  { model: 'model_h1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
			  { model: 'model_h2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
			  { model: 'model_h3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
			]
		  }
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```
