### ISSUE TITLE
Soft break (shift+enter) does not work on Safari

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#13625]
## 📝 Provide detailed reproduction steps (if any)

1. Use Safari browser
2. Open [demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)
3. Try using `shif+enter` to add soft break

### ✔️ Expected result

`<br>` is inserted.

### ❌ Actual result

New paragraph is inserted.

## 📃 Other details

* Browser: Safari
* First affected CKEditor version: `35.3.0` - the one with IME changes

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/13321
