### ISSUE TITLE
Laravel 5.7 installation problem (don't install jeroennoten/laravel-ckeditor v3.8.1)

### ISSUE THREAD

**Issue by DavitMK** [ckeditor/ckeditor5#1363]
- Conclusion: don't install jeroennoten/laravel-ckeditor v3.8.1
- Conclusion: remove laravel/framework v5.7.13

**Comment by pomek** [comment]
`jeroennoten/laravel-ckeditor` contains CKEditor 4. This is the repository for CKEditor 5. 

Btw, `laravel-ckeditor`[supports Laravel 5.4.0, not higher](https://github.com/jeroennoten/laravel-ckeditor/blob/b29cb3971e1f7b9e9323685a228d0c9fe608f4b9/composer.json#L23).
