### ISSUE TITLE
Html document content into Ckeditor5 

### ISSUE THREAD

**Issue by Govardhan9814s** [ckeditor/ckeditor5#13657]
When I set html document to Ckeditor5 content as a string it strips style tag and inline style and kept thair own styles ,is it any possible way to provide our html styles and can i  render my html document as it is , we are going to use in our application for real time collaboration, there I am going to provide html document as document content , I need to apply my styles in the document. Please suggest me any example or any idea to apply
 My example content like:
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8" />
    <title>Test page</title>
    <style>
      p {
        color: red;
      }
    </style>
  </head>
  <body>
    <p>This is my paragraph.</p>
  </body>
</html>

**Comment by Witoso** [comment]
Hey @Govardhan9814s, thanks for reaching out. Please check the capabilities of the [General HTML Support](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html) plugin, which will allow you to use inline styles.
