### ISSUE TITLE
Remove Nullish coalescing and safe navigation operators.

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#13656]
Nullish coalescing operator (`??`) and safe navigation (`?.`) operators are nice features, but cause few issues:

- When the TypeScript target is >= ES2020 – they are translated to JavaScript as they are, but the output cannot be parsed by webpack 4.x.x without additional loaders.
- When the TypeScript target is <= ES2019 – they are translated to conditional (ternary) operator with checks for `null` and `undefined` values. Because the result checks both values in separate branches (`x === null || x === void 0`), the code coverage drops unless we test **both** `null` and `undefined` cases.

Because we only have a few places when we use those operators, let's remove them.

**Comment by Witoso** [comment]
Let's make sure before closing that internal ADR is review and announced.
