### ISSUE TITLE
Preprocess text while (editing)

### ISSUE THREAD

**Issue by nikitalarionov** [ckeditor/ckeditor5#1366]
Hello everyone.

I just trying to do simple thing with text, while editing the text.

For example imagine that we have outside from editor a function preProcess(text) which just does return text + "a"; It can be typograf library or something else.

I need to call this function before model handles it, and changes will be transformed to view.
As suggested on official docs for extend functional in CkEditor, i should create plugin.

As mented about architecture of CkEditor, we have two different layers dataController - which handles input, output data operations. And EditingController which handles changes while you editing.

I tred out to "monkey patch" parse method of processor by decorator function - but it is only works when it begin initialised.

I think i need to look at model level little bit closer, for example: subscribe to model changes, get input text string, preprocess value and throw it next on data pipeline.

It's just simple thing for other editors, but in CKEditor its looks like a hell. I need to look at few thousand rows of code. To solve this problem i need just push myself to understand how system works under hood. But i dont have a time.

Please can anyone help me and explain simple way to achive text preprocessing feature while editing on fly?

## 💻 Version of CKEditor

CKEditor 5

**Comment by Reinmar** [comment]
Hi! Could you give a more specific example? When the transformation should happen? When you're typing those characters? Or for all text in the editor, not matter how it's added there (pasting, data loading, deleting a fragment of text so "foxo" becomes "foo" when you try to do `s/foo/bar` on the whole content)?

Listening on typing can be done via observing the `InputCommand#execute` event (which is fired when `InputCommand#execute()` method is executed, cause it's [decorated](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_observablemixin-Observable.html#function-decorate)). You can get the input command instance from `editor.commands.get( 'input' )`.

Fixing on the fly all the content by [`registerPostFixers()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#function-registerPostFixer).

**Comment by nikitalarionov** [comment]
Hello again, thanks for fast reaction.

I can give a specific example. 

For example we have editor without text. User starts typing new text, adds few words or ending editing line of text.

I need show to user how text is transforming, on the fly, when word, or line is added. For example double quotes is transformed to single. Or dash is transformed to long dash.

Text transforming depends of some rules which is used in our project as element of required typography. 

Our user is editor. He need see how text willbe look at finaly variant in CkEditor. 

Because text styles and content on frontend side of project will be equal.

I'm worried about perfomance issues if i will replacing all editor text on each one symbol change event.

**Comment by nikitalarionov** [comment]
@scofalik @Reinmar Thanks for advices, and good work at CKEditor. 

Now i know which parts of editor can help me to implement feature.
