### ISSUE TITLE
List item with text wrapped in `<p></p>` is not displayed as a list item

### ISSUE THREAD

**Issue by agradl** [ckeditor/ckeditor5#13669]
## 📝 Provide detailed reproduction steps (if any)

1. Set the instance data with an ordered or unordered list that has at least one list item with a <p> tag in it. `document.querySelector('.ck-content').ckeditorInstance.setData('<ul><li>hello</li><li><p>hello2</p></li><li>hello3</li></ul>')`

### ✔️ Expected result

A list with three items, each with a bullet point

### ❌ Actual result

Only the list items without `<p>` are treated as list items

<img width="236" alt="image" src="https://user-images.githubusercontent.com/1896844/224748928-3216a706-9e5c-4b1d-bb2b-34f7b7f4edc1.png">

## 📃 Other details
We are migrating from Ckeditor 4 to Ckeditor 5. Sometimes Ckeditor 4 will wrap the list item text in `<p></p>`. This displays correctly as a list in Ckeditor 4, but not once we upgrade to 5

* Browser: Chrome, Safari
* OS: MacOS 13.2.1 
* First affected CKEditor version: 5
* Installed CKEditor plugins: N/A (issue present in demo)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey @agradl, thanks for reaching out. Could you mention in which demo you're using? I tested your HTML on this one: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html, and it showed the list correctly.

**Comment by agradl** [comment]
I was using this demo - https://ckeditor.com/ckeditor-5/demo/feature-rich/

It looks like they are both version `36.0.1` - so maybe it's a plugin?

**Comment by Mgsy** [comment]
Hi @agradl! CKEditor 5 supports two types of list plugin - [standard lists](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html) and [document lists](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html). The standard one doesn't support block elements inside list items, so if you want to handle your markup properly, you need to install the document lists plugin.

**Comment by agradl** [comment]
great thanks, we will go ahead and swap plugins.
