### ISSUE TITLE
Multiple lists are merged together id they are created directly after each other.

### ISSUE THREAD

**Issue by gheydon** [ckeditor/ckeditor5#13670]
## 📝 Provide detailed reproduction steps (if any)

```
<ul>
    <li>
        list 1, item 1
    </li>
    <li>
        list 1, item 2
    </li>
</ul>

<ul>
    <li>
        list 2, item 1
    </li>
    <li>
        list 2, item 2
    </li>
</ul>
```

When converting back to the view this will merge the 2 lists into 1.

### ✔️ Expected result

When converting the model back to the view it should keep the 2 lists as they are.

### ❌ Actual result

The HTML structure should remain the same.

### ❓ Possible solution

When upcasting add a list id to the element and then when doing the downcast you can keep lists separated and discarding the id as it is not required in the view.

## 📃 Other details

* Browser: chrome
* OS: MacOs
* First affected CKEditor version: not sure.
* Installed CKEditor plugins: current version with Drupal 9.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/12738.
