### ISSUE TITLE
Composition breaks when typing a Korean phonetic radical after typing `space` key on Android Chrome

### ISSUE THREAD

**Issue by byeokim** [ckeditor/ckeditor5#13693]
## 📝 Provide detailed reproduction steps (if any)

1. Launch any CKEditor, e.g. [this demo](https://ckeditor.com/ckeditor-5/demo/mobile-support/), on Android Chrome
2. Put caret at the start of any empty line
3. Use GBoard keyboard
4. Add keyboard language: select Korean then 2-Bulsik
5. Change keyboard language to Korean
6. Type `ㄱ`
7. Type `ㅏ`
8. Type `space`
9. Type `ㄱ`
10. Type `ㅏ`

[screenrecording.webm](https://user-images.githubusercontent.com/29354589/225513821-4b0b753b-52c0-4274-be4b-133ffa9e2d03.webm)

### ✔️ Expected result

`가 가`

### ❌ Actual result

`가 ㄱㅏ`

### ❓ Possible solution

Not updating Text node when composing, i.e. after `compositionstart` event and before `compositionend` event, by adding the following code into `renderer.ts`:

https://github.com/ckeditor/ckeditor5/blob/1bbb4dfb66395f9de41d9d6353bd8e69293621e0/packages/ckeditor5-engine/src/view/renderer.ts#L714-L728

```diff
else if ( action === 'replace' ) {
+ if (!this.isComposing) {
    updateTextNode( actualDomChildren[ i ] as DomText, ( expectedDomChildren[ i ] as DomText ).data );
+ }
  i++;
```

On Android Chrome, when a character is typed and the typing triggers a `compositionstart` event, IME seems to put the character into the Text node sometime after `compositionupdate` event. Meanwhile CKEditor also effectively puts the character into the node by invoking `updateTextNode`. So there would be two same characters. `MutationObserver` detects the DOM mutation and invokes another `updateTextNode`. Because of that invocation one of the two characters is removed. This can be confirmed by uncommenting `CK_DEBUG_TYPING` `console.log`s. I suspect that which character is removed affects whether the current composition should break, i.e. IME seems to be keeping track of which character instance is involved in the current composition.

The suggested solution will prevent the character duplication. IME will put the character while CKEditor won't. Thus there would be no removal of the duplicated character. Neither be composition-breaking.

## 📃 Other details

* Browser: Chrome 91.0
* OS: Android 12
* First affected CKEditor version: 36.0.1
* Installed CKEditor plugins: Essentials, Paragraph

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by tkmin** [comment]
[bug: typing Korean on Safari](https://github.com/ckeditor/ckeditor5/issues/8031) at v34 was resolved in v35,
but the Android bug described above was not occured when the version was 34.

**Comment by Almyk** [comment]
CKEditor version 35.4.0 is also affected by this bug.

**Comment by bungabear** [comment]
Your solution seems works well.

**Comment by noncelab-tiger** [comment]
👍🙏

**Comment by tkmin** [comment]
@noncelab-tiger 
@bungabear

could you please tell me which method is used to build the editor?
I used the online builder and the **renderer.ts** file cannot be found in my project.

Thanks in advanced! 🙇‍♂️

![Screen Shot 2023-05-08 at 2 55 32 PM](https://user-images.githubusercontent.com/83566566/236745089-f34defb3-986d-4763-8bcf-afd0e3764848.png)

**Comment by bungabear** [comment]
> @noncelab-tiger @bungabear
> 
> could you please tell me which method is used to build the editor? I used the online builder and the **renderer.ts** file cannot be found in my project.
> 
> Thanks in advanced! 🙇‍♂️
> 
> ![Screen Shot 2023-05-08 at 2 55 32 PM](https://user-images.githubusercontent.com/83566566/236745089-f34defb3-986d-4763-8bcf-afd0e3764848.png)

You should edit `node_modules/@ckeditor/ckeditor5-engine/src/view/renderer.js` file.

**Comment by noncelab-tiger** [comment]
> 

I used the online builder. I modified the code in the path below. The code is minified so it may be hard to find.
In my case, it looked like this.

`node_modules/ckeditor5-custom-build/build/ckeditor.js`

```javascript
if (t === "insert") {
    bc(n, c, r[c]);
    c++
} else if (t === "replace") {
    Uf(o[c], r[c].data); // this code
    c++
} else if (t === "equal") {
    this._markDescendantTextToSync(this.domConverter.domToView(r[c]));
    c++
}
```

**Comment by dancinlife** [comment]
@noncelab-tiger Very helpful!!!

**Comment by dancinlife** [comment]
Very helpful!

**Comment by justplayboard** [comment]
> > 
> 
> I used the online builder. I modified the code in the path below. The code is minified so it may be hard to find. In my case, it looked like this.
> 
> `node_modules/ckeditor5-custom-build/build/ckeditor.js`
> 
> ```js
> if (t === "insert") {
>     bc(n, c, r[c]);
>     c++
> } else if (t === "replace") {
>     Uf(o[c], r[c].data); // this code
>     c++
> } else if (t === "equal") {
>     this._markDescendantTextToSync(this.domConverter.domToView(r[c]));
>     c++
> }
> ```

If the following error occurs, correct it as follows:

```
Uncaught Error: Failed to execute 'setStart' on 'Range': The offset 2 is larger than the node's length (1).
    at Dm.viewRangeToDom (ckeditor.js:13564:1)
    at wb.scrollToTheSelection (ckeditor.js:15308:1)
    at e.<anonymous> (ckeditor.js:32234:1)
    at e.fire (ckeditor.js:3605:1)
    at Af (ckeditor.js:11685:1)
    at xf.fire (ckeditor.js:11638:1)
    at e.<anonymous> (ckeditor.js:32156:1)
    at e.fire (ckeditor.js:3605:1)
    at Af (ckeditor.js:11685:1)
    at xf.fire (ckeditor.js:11638:1)
```

solution: 

`node_modules/ckeditor5-custom-build/build/ckeditor.js`

```js
    if (n === o) {
        yield this._getBlockFiller()
    }
}
viewRangeToDom(t) {
    const e = this.viewPositionToDom(t.start);
    const n = this.viewPositionToDom(t.end);
    const o = this._domDocument.createRange();
	if(e.offset > 0){
		o.setStart(e.parent, e.offset - 1);
		o.setEnd(n.parent, n.offset - 1);
	} else {
		o.setStart(e.parent, e.offset);
		o.setEnd(n.parent, n.offset);
	}
        return o
}
viewPositionToDom(t) {
    const e = t.parent;
    if (e.is("$text")) {
        const n = this.findCorrespondingDomText(e);
```

**Comment by niegowski** [comment]
The work for this issue and others related is completed in the https://github.com/ckeditor/ckeditor5/pull/16289, and we finalized the round of internal (successful) tests. I encourage everyone to test the PR if you have a chance. It should be merged in the following days, and will be a part of the next release.
