### ISSUE TITLE
French localization: Overlapped labels on flash properties windows

### ISSUE THREAD

**Issue by NatalyaBalenko** [ckeditor/ckeditor5#137]
Repro steps:
1) Change localization to French
2) Click on Flash icon
3) Click on flash icon on CKE editor. Flash properties window will open
Actual Result:
Horizontal spacing and vertical spacing strings are getting overlapped.
Expected Result:
Horizontal spacing and vertical spacing strings should not overlap
![image](https://cloud.githubusercontent.com/assets/5136213/14557626/e3747b72-0306-11e6-979d-0153aa3e0d00.png)

Problem:
French localization for flash plugin(plugins/flash/lang/fr-ca.js) is using too long label (in another languages are using short version - hSpace: 'HSpace'):	
hSpace: 'Espacement horizontal',
As possible solution can be make this text shorter.

**Comment by Reinmar** [comment]
Hey! This is CKEditor 5's issue tracker. The version you use is 4.x, which has the issue tracker on http://dev.ckeditor.com/. I moved the ticket to http://dev.ckeditor.com/ticket/14591#ticket
