### ISSUE TITLE
Access to the editor instance don't work

### ISSUE THREAD

**Issue by Captainfl4me** [ckeditor/ckeditor5#1370]
## Is this a bug report or feature request?

🐞 Bug report

## 💻 Version of CKEditor
ckeditor5 version : 11.1.1, classic editor

## 📋 Steps to reproduce

1.I've create a textarea element with id="editor"

2.Then, I initialized the editor with : 
let myEditor;
ClassicEditor
            .create(document.querySelector( '#editor' ))
            .then( editor => {
                myEditor = editor;
            } );
3. A function update who update the content of the preview element : 

function Update(){   
                document.getElementById('content').innerHTML = myEditor.getData();
                setTimeout('Update();','10');
}

## ✅ Expected result
A function who update the preview section of the page by getting the content of the ckeditor and paste it in <a></a> element.
## ❎ Actual result
When I try to use myEditor.getData() that told me that 'myEditor' is not defined. So, I think that's because javascript is in strict mode so I can't use global variable and get the instance of the editor But if someone can maybe solve this problem, that were very cool :)

## 📃 Other details that might be useful
It work with ckeditor 4 with:
var editor = CKEDITOR.replace('editor');  //to get the instance

**Comment by ma2ciek** [comment]
Hi, @Captainfl4me.

The `ClassicEditor.create()` function is asynchronous and it might happen, for sure, that the editor isn't created within the 10ms. The second issue is that using `setTimeout` is very ineffective for getting the data synced.

I'd suggest you to use the `editor.model.document.on( 'change:data' )` event:

```js
ClassicEditor.create( element ).then( editor => {
	editor.model.document.on( 'change:data', () => {
		someUpdateFn( editor.getData() );
	} );
} );
```

See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#interacting-with-the-editor for more details.
