### ISSUE TITLE
Expose `Context`, `EditorWatchdog`, and `ContextWatchdog` as static editor properties.

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#13707]
## 📝 Provide a description of the improvement

To simplify integrations and consistency with editor builds, we should expose `Context`, `EditorWatchdog`, and `ContextWatchdog` as static editor properties. Expose them on editors (not on the base `Editor` class) so we won't have a dependency from the `core` package to `watchdog`.

**Comment by pomek** [comment]
I think it will be fine if all integrations will drop importing Watchdog from its package. It means a breaking change, so an editor must be loaded in version 37+. As for now, we require 34+, so the check is ready. We need to update a number and a few tests. Even more than a few.

**Comment by Reinmar** [comment]
Do you mean this mechanism?

[https://github.com/ckeditor/ckeditor5-react/blob/09d8b80da7c33a2cc9d42fa573ebe248ea43a864/src/ckeditor.jsx#L43-L52](https://github.com/ckeditor/ckeditor5-react/blob/09d8b80da7c33a2cc9d42fa573ebe248ea43a864/src/ckeditor.jsx#L43-L52)

I think it's completely reasonable to make the new version of the integration work with the new version of CKE only.
