### ISSUE TITLE
[XWiki] CreateError: observable-bind-to-properties-length: The number of properties must match.

### ISSUE THREAD

**Issue by wuguokai** [ckeditor/ckeditor5#1372]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

ckeditor5/11.1.1/classic/ckeditor.js

## 📋 Steps to reproduce

1. create ckeditor5 follow  [quick-start](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html).
create code : 
```JavaScript
ClassicEditor
            .create('<p>Hello world!</p>')
            .then(editor => {
                console.log('Editor was initialized', editor);

                // Initial data was provided so `editor.element` needs to be added manually to the DOM.
                document.body.appendChild(editor.element);
            })
            .catch(err => {
                console.error(err.stack);
            });
```

## ✅ Expected result
create success!

## ❎ Actual result
throw error : observable-bind-to-properties-length: The number of properties must match. 
![image](https://user-images.githubusercontent.com/30334643/48989881-2f29e380-f167-11e8-8aff-13b27fd2db14.png)

## 📃 Other details that might be useful
What may cause this error(observable-bind-to-properties-length: The number of properties must match. )?

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
I followed the guide but I couldn't reproduce the issue. 

Is that really all you did @wuguokai? Just followed the quick start guide? Anyway, where do you run the editor? Chrome? Electron? Something else? Can you create a JSFiddle or CodePen that would allow us to reproduce the issue?

Anyway, most likely the error comes from [these lines](https://github.com/ckeditor/ckeditor5-engine/blob/bbfed9d490659e047ef3f3b2193020ac8c6ef6ff/src/controller/editingcontroller.js#L112-L125) but we need more information about the case to understand it.

**Comment by wuguokai** [comment]
Thanks for your  @oleq  answer! Actually I created the editor  followed the  guide is fine because it  in a simple html page.  
![image](https://user-images.githubusercontent.com/30334643/49015151-2b28b080-f1bd-11e8-8e29-31fd46c4f16a.png)
This problem appear when I try to use ckeditor in [XWiki](https://www.xwiki.org/xwiki/bin/view/Main/) (It uses ckeditor4 fine now .But  ckeditor5 is too cool ,So I want to try it  ).
Then I add  `<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/classic/ckeditor.js"></script>`  to html head and try to create an editor. But failed ,got above issue.
I don't know what will cause it  probably.

**Comment by oleq** [comment]
I created a [raw fiddle](https://jsfiddle.net/oleq/n9posL46/) and it simply works. 

I'm not familiar with XWiki but it does not seem like a tricky use–case for our editor (at first glance). Still, to track this issue down, I'd need a working XWiki environment, best with an uncompressed build of the editor. Or at least some meaningful stack trace because I'm not sure where the error comes from. Is there any chance we could get some details?

**Comment by wuguokai** [comment]
Yes! I have create a demo [XWiki](https://wuguokai.demo.xwiki.com/xwiki/bin/view/Main/) environment and add script link of ckeditor to all page header.
![image](https://user-images.githubusercontent.com/30334643/49055844-1b987e80-f234-11e8-8211-b52bbdb62724.png)
  You could try on it, excute code :
```javascript
ClassicEditor
      .create('<p>Hello world!</p>')
      .then(editor => {
        console.log('Editor was initialized', editor);

        // Initial data was provided so `editor.element` needs to be added manually to the DOM.
        document.body.appendChild(editor.element);
    } )
    .catch(err => {
      console.error(err.stack);
    } );
```
and then got the error :
![image](https://user-images.githubusercontent.com/30334643/49055972-96619980-f234-11e8-898d-d1af2625f611.png)
 . But it possible has expired, look this 
![image](https://user-images.githubusercontent.com/30334643/49055924-6e723600-f234-11e8-9fc2-ec5a12fa0fc2.png)
So you also could create a demo XWiki yourself by this step : 
 1. Make a [try-xwiki-cloud](https://www.xwiki.com/en/products/try-xwiki-cloud)
![image](https://user-images.githubusercontent.com/30334643/49056103-2dc6ec80-f235-11e8-8aa8-baaec4ee63ee.png)
2. Fill in your information and  `Create`.
![image](https://user-images.githubusercontent.com/30334643/49056167-77173c00-f235-11e8-82fc-aea36a0bedd4.png)
3. Wait a moment , You should go into the new XWiki Main Home. Then follow this step, you should got the error:
![20181002_112820](https://user-images.githubusercontent.com/30334643/49056759-f60d7400-f237-11e8-9df1-3f69359440f4.jpg)

Thank you very much for your help!

**Comment by wuguokai** [comment]
👍  @oleq  Thanks you very much !
I have  add an `iframe`  label to create the CKEditor5.  It is success and I'm  trying to use other features and plugins .
Nice experience！

**Comment by oleq** [comment]
Just for the record, I submitted an [issue](https://jira.xwiki.org/browse/XWIKI-15915) to the XWiki bug tracker.
