### ISSUE TITLE
Image insert does not work in certain guides

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#13722]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html#configuring-the-remove-format-feature

### Project version

36.0.1

### Is the information outdated? How?

n/a

### Is there something missing in the guide? What is it?

Insert image doesn't work on the removeFormat demo.

### Is there anything else you would like to add?

n/a

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by godai78** [comment]
I can confirm this problem show up in several more demos, will update the list in here when I identify all of them.  
  
\* remove formatting  
\* restricted editing  
  
I cannot identify any differences in the snippet code. These got recently image upload during the toolbar revamp, but many snippets got it, and only SOME of those are not working.  
  
@ckeditor/qa-team - can you have a look at this, too?
