### ISSUE TITLE
The headings is not true

### ISSUE THREAD

**Issue by vahidmotamen** [ckeditor/ckeditor5#13725]
**heading 1 output is heading 2
heading 2 output is heading 3
...**

**example:**
heading 1:
asd
Code output in the source:
`<h2>asd</h2>`

**i use:**
https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js

**I made some changes in ckeditor.js and it works fine...**

**this code:** 
{model:"heading1",view:"h2",title:"Heading 1",class:"ck-heading_heading1"},
{model:"heading2",view:"h3",title:"Heading 2",class:"ck-heading_heading2"},
{model:"heading3",view:"h4",title:"Heading 3",class:"ck-heading_heading3"}

**to this:**
{model:"heading1",view:"h1",title:"Heading 1",class:"ck-heading_heading1"},
{model:"heading2",view:"h2",title:"Heading 2",class:"ck-heading_heading2"},
{model:"heading3",view:"h3",title:"Heading 3",class:"ck-heading_heading3"},
{model:"heading4",view:"h4",title:"Heading 4",class:"ck-heading_heading4"}

Thank you team

**Comment by Witoso** [comment]
Hey @vahidmotamen, thanks for reaching out.
This is actually intended behavior, as our [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html) states:

> By default, this feature is configured to support `<h2>`, `<h3>`, and `<h4>` elements which are named: “Heading 1”, “Heading 2” and “Heading 3”, respectively. The rationale behind starting from `<h2>` is that `<h1>` should be reserved for the [page’s main title](https://ckeditor.com/docs/ckeditor5/latest/features/title.html) and the page content will usually start from `<h2>`.

You can either change your configuration (as you did) or use the [Title](https://ckeditor.com/docs/ckeditor5/latest/features/title.html) plugin.
