### ISSUE TITLE
Can't add youtube with bootstrap

### ISSUE THREAD

**Issue by startong21** [ckeditor/ckeditor5#1373]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

https://cdn.ckeditor.com/ckeditor5/11.1.1/classic/ckeditor.js

## 📋 Steps to reproduce

1. I use the following Bootstrap CDN(http://getbootstrap.com/)'s CSS, JS, Popper.js, and jQuery. This is default links in Bootstrap CDN.

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

I can't add any youtube videos on CKEditor5 editor.

2. If I remove the bootstrap.min.css from my site source, I can add youtube videos.

## ✅ Expected result
youtube video

## ❎ Actual result
no video

**Comment by Reinmar** [comment]
Hi! Could you create a sample on e.g. JSFiddle on which we could reproduce this issue?

**Comment by programad** [comment]
I am having this problem too. Confirmed not working with bootstrap 4.1.3

**Comment by Reinmar** [comment]
See https://github.com/ckeditor/ckeditor5/issues/1391#issuecomment-444116727. Apparently Bootstrap sets some styles for `.media` which breaks the media widgets in CKEditor 5. If you'd style `.ck-content .media { heigh: (not sure what here) }`, the problem should be resolved.

cc @oleq

**Comment by dkonopka** [comment]
Yes, it's true bootstrap 4 overwrites `.media` class. 

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_media.scss#L1-L4

With:
```css
.ck-widget.media {
  display: block;
}
```

Anyways we could introduce this fix by default in our [ckeditor5-media-embed CSS](https://github.com/ckeditor/ckeditor5-media-embed/blob/master/theme/mediaembed.css#L6).

**Comment by startong21** [comment]
Thank you!

**Comment by linucle** [comment]
In my webpage doesn't work... 

<figure class="media"><oembed url="https://www.youtube.com/watch?v=H08tGjXNHO4"></oembed></figure>

we can't see the movie.
