### ISSUE TITLE
Large text hanging the page

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#1374]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  Other

## 💻 Version of CKEditor

From latest examples(https://ckeditor.com/ckeditor-5/#document)
Compared to CKEditor4 lastest examples (https://ckeditor.com/ckeditor-4/#document)

## 📋 Steps to reproduce

1. Have some huge text (Lorem ipsum >100 paragraphs)
2. Paste them in the editor
3. Select all the text
4. Apply some style(Ex. Bold)

## ✅ Expected result
Have CKEditor5 apply it as quick as CKEditor4.

## ❎ Actual result
CKEditor4 applies it instantly, while CKEditor5 takes a while, hanging the page.

## 📃 Other details that might be useful
I know CKEditor5 has a lot more constrains reflecting the changes into the model. But is seams that this could impact some cases with where the documents are big. For this reason I was split between bug and other, for it seams to be JavaScript performance limitation.

**Comment by oleq** [comment]
Related to https://github.com/ckeditor/ckeditor5-engine/issues/494 and https://github.com/ckeditor/ckeditor5/issues/693. cc @Reinmar

**Comment by Reinmar** [comment]
We didn't make any research on this yet so I guess there are some low hanging fruits out there. Let's keep the discussion in https://github.com/ckeditor/ckeditor5-engine/issues/494

**Comment by Reinmar** [comment]
PS. Some initial profiling may help to understand what kind of issues we're dealing with. If you're struggling with performance issues in real use cases, you may try to dig into this.
