### ISSUE TITLE
Mention determine focus after drag ansd drop

### ISSUE THREAD

**Issue by PolgunE** [ckeditor/ckeditor5#13742]
## 📝 Mention by drag and drop

Here is example how we determine position . Where we put mention item.
It would be great to determine the focus in the place where the element was thrown on the drag drop.

const focus = editor.model.document.selection.focus;
editor.execute( 'mention', {
	marker: '#',
	mention: {
		id: '#1234',
		name: 'Foo',
		title: 'Big Foo'
	},
	range: model.createRange( focus, focus.getShiftedBy( -1 ) )
} );

_What is the expected behavior of the proposed feature?_

It would be great to determine the focus in the place where the element was thrown on the drag & drop
and inserting a mention in the place where it is thrown. 
Is this possible for now ?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This page should help you: https://ckeditor.com/docs/ckeditor5/latest/features/pasting/drag-drop.html along with the example js file.

Dropping behaves like pasting, here's a deep dive: https://ckeditor.com/docs/ckeditor5/latest/features/pasting/drag-drop.html
