### ISSUE TITLE
CKBox: Ignore filename extension letter case when looking for the category

### ISSUE THREAD

**Issue by zaak** [ckeditor/ckeditor5#13751]
## 📝 Provide a description of the improvement

Currently, when the file upload is managed by the plugin (Image button, drag & drop, paste from clipboard), the category the uploaded file is assigned based on the file extension:

https://github.com/ckeditor/ckeditor5/blob/617497a8ebe03a9f66f327479dff92c3dd10fe1c/packages/ckeditor5-ckbox/src/ckboxuploadadapter.ts#L186-L208

We have recently changed this logic in CKBox and the letter case of the extension no longers matters. The logic in the plugin should be adjusted to work the same way and ignore the checked extension letter case.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by zaak** [comment]
@Witoso: Sorry for not being clear enough. No, it's only about allowed extensions. E.g. if CKBox allows `.jpg`, should be able to upload `.JPG`, `.Jpg`, etc. Currently it is not possible in the plugin logic linked above.

**Comment by Witoso** [comment]
Gotcha, but all the extension names will be lowercase at your end, right? Because as far as I can see we will need to find the id by name.

**Comment by zaak** [comment]
> all the extension names will be lowercase on your end, right?

Not necessarily, but it's not a problem. You can still match both after applying `.toLowerCase()`, e.g.:

```js
allowedExtensions
    .map( allowedExtension => allowedExtension.toLowerCase() )
    .includes( checkedExtension.toLowerCase() );
```

**Comment by Witoso** [comment]
To summarize the scope:

Ignore letter casing in matching the category based on the file extension.
