### ISSUE TITLE
Support the Core in TS migration in the React integration

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13768]
## Provide a description of the task

* https://github.com/ckeditor/ckeditor5-react/pull/367

**Comment by pomek** [comment]
Done. We released a new version: https://github.com/ckeditor/ckeditor5-react/releases/tag/v6.0.0-alpha.0.

**Comment by martnpaneq** [comment]
I was requested to provide a description of the new features that integration with TypeScript provides for React component:
https://github.com/ckeditor/ckeditor5/issues/13546
