### ISSUE TITLE
Update links to CKFinder

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1376]
We use https://ckeditor.com/ckfinder/ for now, but soon there will be CKE5's CKF page so let's link to that one.

TODO: confirm with @wwalc or @m-kr the link.

**Comment by wwalc** [comment]
Where is the link used / located?

**Comment by Reinmar** [comment]
In a dozen places in CKE5 and its packages docs.

**Comment by Reinmar** [comment]
OK, @wwalc explained to me that there will be just a single CKF page and we're linking to the right one.
