### ISSUE TITLE
No documentation on how to integrate CKEditor5 into Next.js

### ISSUE THREAD

**Issue by navidmadannezhad** [ckeditor/ckeditor5#13769]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/react.html

### Project version

36.0.1

### Is there something missing in the guide? What is it?

The title explains it all: **No documentation on how to integrate CKEditor5 into Next.js**

Well Next.js is built on React.js, which means we can almost use the React integration on Next, but there are also key differences between these two technologies.

Just try to integrate it into Next js, the first warnings you get are typescript warnings, or you're going to get `self is not defined` error because of Server-Client differences on Next.

I know there are some good solutions on [here](https://stackoverflow.com/questions/62690188/error-could-not-find-a-declaration-file-for-module-ckeditor-ckeditor5-build-c) or [here](https://stackoverflow.com/questions/72658294/referenceerror-self-is-not-defined-while-using-ckeditor) or [here ](https://robiokidenis.medium.com/how-to-use-ckeditor-on-your-nextjs-or-react-app-525664cdb1d7), but wait, if I'm supposed to look for Community-based solutions for these major integration problems, then what is the use of CKEditor docs?

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by godai78** [comment]
We're currently working on expanding the integration docs to host additional guides, but it will be done incrementally. We are also in process of updating the documentation toward the TypeScript introduction. This will, however, take some more time, so feel free to drop in and check out periodically.
