### ISSUE TITLE
Clearing document is very slow on firefox (60)

### ISSUE THREAD

**Issue by elliarbtan** [ckeditor/ckeditor5#1377]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

https://ckeditor.com/ckeditor-5/#document

With firefox.

## 📋 Steps to reproduce

1. copy paste 300 lines like this one 

Morbi tristique sodales tellus et fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fringilla dapibus molestie. Sed cursus vulputate dignissim. Maecenas rhoncus quam tortor, a placerat libero imperdiet non. Proin egestas fringilla placerat. Suspendisse condimentum nulla ut consequat pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

2. select all line with "ctrl + a"
3. delete with "del"

## ✅ Expected result

empty document in a short time.

## ❎ Actual result

Takes about 40 seconds to complete. Larger document hangs the browser.

## 📃 Other details that might be useful

This happens only when using firefox (60.3.0 esr), not when using chromium (70.0.3538.110).

**Comment by Reinmar** [comment]
Please see my comments in https://github.com/ckeditor/ckeditor5/issues/1374.

Closing as DUP of https://github.com/ckeditor/ckeditor5-engine/issues/494.
