### ISSUE TITLE
Google Input Tools extension doesn't work with CKEditor 5

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#13785]
## 📝 Provide detailed reproduction steps (if any)

1.  Install Google Input Tools - https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab?hl=en.
2.  Configure it to use, for example, arabic.
3.  Go to [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html.](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html.)
4.  Try to type something and confirm the word to insert it to the editor.

### ✔️ Expected result

_The text is inserted._

### ❌ Actual result

_Nothing happens._

## 📃 Other details

*   Can't reproduce it in CKEditor 5 without changes related to IME and beforeInput.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/13234 ?
