### ISSUE TITLE
Extended attributes do not persist on imageBlock elements

### ISSUE THREAD

**Issue by MichaelHeydon** [ckeditor/ckeditor5#13792]
### imageInline

I'm adding extra attributes to the `imageInline` element: 
```
const attributes = getExtraAttributes(); // returns an array of attributes

this.editor.model.schema.extend("imageInline", {
    allowAttributes: [attributes],
});

attributes.forEach((attribute) => {
    this.editor.conversion.for("downcast").attributeToAttribute({
        model: {
            name: "imageInline",
            key: attribute,
        },
        view: {
            name: "img",
            key: attribute,
        },
    });
    this.editor.conversion.for("upcast").attributeToAttribute({
        view: {
            name: "img",
            key: attribute,
        },
        model: {
            name: "imageInline",
            key: attribute,
        },
    });
});
```
When I add an `imageInline` and add the attributes, the _Model_ correctly displays:
![imageInline-model](https://user-images.githubusercontent.com/74880856/228719917-2fc63742-6cd8-482a-8b76-b15729b4f715.png)

And in the _View_, the attributes are added to the wrapped `<span>` tag: 
![imageInline-view](https://user-images.githubusercontent.com/74880856/228720003-ff27805f-6880-4275-a226-3d0ed137a9fe.png)

On save, CKEditor5 via [updateSourceElement](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-updateSourceElement) (or however) converts the data to:
```
<p>
    <img
        src="/cms/videoThumb.php?size=poster&amp;id=55508bc98a00f615dbe9bd4c84a253ba4238b021&amp;type=storage"
        alt="file_example_MP4_480_1_5MG"
        data-schoolboxresource-type="video"
        data-schoolboxresource-filesystem="store"
        data-schoolboxresource-thumbnail="/cms/videoThumb.php?size=poster&amp;id=55508bc98a00f615dbe9bd4c84a253ba4238b021&amp;type=storage"
        data-schoolboxresource-source="/cms/sendVideo.php?id=55508bc98a00f615dbe9bd4c84a253ba4238b021&amp;type=store"
        data-schoolboxresource-width="512"
        data-schoolboxresource-height="288"
        data-schoolboxresource-fullwidth="false"
    />
</p>
``` 
So all the added `data-` attributes are added to the `<img>` element as expected. 

### imageBlock

Using the same approach for `imageBlock` does not work. So using the same approach, but for `imageBlock`: 
```
const attributes = getExtraAttributes(); // returns an array of attributes

this.editor.model.schema.extend("imageBlock", {
    allowAttributes: [attributes],
});

attributes.forEach((attribute) => {
    this.editor.conversion.for("downcast").attributeToAttribute({
        model: {
            name: "imageBlock",
            key: attribute,
        },
        view: {
            name: "img",
            key: attribute,
        },
    });
    this.editor.conversion.for("upcast").attributeToAttribute({
        view: {
            name: "img",
            key: attribute,
        },
        model: {
            name: "imageBlock",
            key: attribute,
        },
    });
});
```
Having added the `imageBlock`, the _Model_ displays the expected attributes:
![imageBlock-model](https://user-images.githubusercontent.com/74880856/228721083-514970a6-cf44-46c4-aeff-974601707901.png)

And the _View_ adds the attributes to the wrapped `<figure>` element:
![imageBlock-view](https://user-images.githubusercontent.com/74880856/228721142-518bbea4-3fb6-4cfe-8245-5f5c031a2af4.png)

However on save, the attributes stay on `<figure>`, and are not moved to the `<img>` element like they do for `imageInline`: 
```
<figure
    class="image"
    data-schoolboxresource-type="video"
    data-schoolboxresource-filesystem="store"
    data-schoolboxresource-thumbnail="/cms/videoThumb.php?size=poster&amp;id=55508bc98a00f615dbe9bd4c84a253ba4238b021&amp;type=storage"
    data-schoolboxresource-source="/cms/sendVideo.php?id=55508bc98a00f615dbe9bd4c84a253ba4238b021&amp;type=store"
    data-schoolboxresource-width="512"
    data-schoolboxresource-height="288"
    data-schoolboxresource-fullwidth="false"
>
    <img
        src="/cms/videoThumb.php?size=poster&amp;id=55508bc98a00f615dbe9bd4c84a253ba4238b021&amp;type=storage"
        alt="file_example_MP4_480_1_5MG"
    />
</figure>
```

So as a result, the code relying on the attributes elsewhere fails to function. Also when this data comes into the editor again, the extra attributes are of course stripped from the `<figure>` as they aren't in the schema. 

### ✔️ Expected result

On save, the attributes are added to the `<img>` element like they are for `imageInline` elements. 

### ❌ Actual result

The attributes stay on the `<figure>` element. 

### ❓ Possible solution

Match the same save behaviour for extra attributes added to the `<img>` element used in `imageInline` for `imageBlock`. 

## 📃 Other details

* First affected CKEditor version: 36.0.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey, `imageBlock` is a bit different than the inline one, as we wrap `img` in `figure` element as you noticed. Therefore on the model’s downcasting all attributes land in the figure. If you wish to have attributes in an `img`, you need to alter the downcasting of the `imageBlock`. Here’s an example:
```ts
import { Plugin } from "ckeditor5/src/core";

export default class TestPlugin extends Plugin {
  private attributes = ["data-abc", "data-def"];

  init() {
    console.log("plugin on");
    this.defineSchema();
    this.defineConverters();
  }

  private defineSchema() {
    this.editor.model.schema.extend("imageBlock", {
      allowAttributes: this.attributes,
    });
  }

  private defineConverters() {
    const conversion = this.editor.conversion;
    // setup upcast for all attributes
    for (const attr of this.attributes) {
      conversion.for("upcast").attributeToAttribute({
        view: attr,
        model: attr,
      });
    }
    // setup dataDowncast for the imageBlock. This will only work in editor.getData()
    conversion.for("dataDowncast").elementToElement({
      model: {
        name: "imageBlock",
        attributes: this.attributes,
      },
      view: (modelElement, { writer }) => { 
        const imgAttr: { [key: string]: string } = {};
        for (const [key, value] of modelElement.getAttributes()) { // here we get attributes from <figure>
          if (typeof value === "string") {
            imgAttr[key] = value;
          }
        }

        // we create an image with attributes, and then wrap it in figure
        const image = writer.createEmptyElement("img", imgAttr);
        return writer.createContainerElement("figure", { class: "image" }, [
          image,
        ]);
      },
      converterPriority: "high", // to make sure this will be the conversion that will fire first
    });

  }
}
```
Two quirks here: first, I’m only altering dataDowncast which influences editor.getData(), to not change how the image is shown as a widget on editing. Second, this example is in TS, feel free to strip all types if you write in plain js.

**Comment by MichaelHeydon** [comment]
Sorry for the delayed reply. Thanks for looking into the issue @Witoso. For now we are just using `imageInline` as we don't currently need any of the features `imageBlock` provides.
