### ISSUE TITLE
Wrong editor's path in multi-root installation full example in predefined builds guide

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#13795]
## 📝 Provide a description of requested docs changes

Branch: `release`
In the predefined builds guide http://127.0.0.1:8080/ckeditor5/latest/installation/getting-started/predefined-builds.html#installation-example-6 full installation example of Multi-root editor contains incorrect path:
`<script src="../build/ckeditor.js"></script>`

It should be a link to the CDN instead, as in the other examples.

**Comment by godai78** [comment]
Fixed in 7addf08
