### ISSUE TITLE
ckeditor5-block-quote plugin BUG

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#13807]
## 📝 Provide detailed reproduction steps (if any)

1. open https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Insert “code block” at the end
3. Insert a new paragraph after the block

### ✔️ Expected result

New paragraph appears after codeblock

### ❌ Actual result

The inserted paragraph appears in codeblock

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: chrome 110
* OS: windows 11
* First affected CKEditor version: 36.0
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey, as mentioned here: https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#demo
To escape a code block you need to type enter three times. This is due to the fact that code blocks often need to have empty paragraphs that split code. I hope this helps!
