### ISSUE TITLE
Keep support for Node 14 for 37.0

### ISSUE THREAD

**Issue by alexander-schranz** [ckeditor/ckeditor5#13810]
## 📝 Provide a description of the new feature

I did read in the `RC` tag that you want to drop support for Node 14 here:

https://github.com/ckeditor/ckeditor5/releases/tag/v37.0.0-rc.0

Is there any case that this break is maybe not required. We @sulu are still required to run on `npm 6` some builds as other npm version does local dependencies not longer the way we expect. Currently it was easy as we just needed to tell our users to be on Node 14 as there NPM 6 was still default.

So if it is easy for you still support Node 14, it would be nice to still have it. Else we mostly will stuck on older ckeditor version.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi Alexander. We didn't anticipate this :( In a hindsight, I think we dropped the Node 14 support too hastily. 

Unfortunately, from what I heard from the team, that's 16 PRs to revert and as many releases to trigger to have a clean situation (CKE 5 + dev deps + integrations + some other tooling). We won't be able to do that before the upcoming release.

Out of curiosity:

*   Do I read correctly that you support only npm 6?
*   And if so, wouldn't it be easier to just ask developers to downgrade npm and use any Node version? Is there a problem with this?
*   How long would you need us to support Node 14? Node 14's EOL will be in 2 month time. As I understand, this means no security fixes.

**Comment by Witoso** [comment]
One point to mention as there's some conflicting information on the Internet. As per the official release schedule (https://github.com/nodejs/release#release-schedule), Node 14 EOL is this month, 2023-04-30.

**Comment by pomek** [comment]
I am closing the issue as 37.0.0 is out, and it requires Node@16.
