### ISSUE TITLE
shift + enter for line break do not work on iOS 16.4

### ISSUE THREAD

**Issue by jesben** [ckeditor/ckeditor5#13825]
1. shift + enter adds new paragraph instead of br in iOS Safari

### ✔️ Expected result

Adds <br>

### ❌ Actual result

Adds new paragraph <p></p>

## 📃 Other details

* Browser: Safari
* OS: iOS 16.4

**Comment by Witoso** [comment]
Hey, thanks for the report, this is gonna be fixed in the next release #13321.

**Comment by Witoso** [comment]
Sorry for the confusion, it will be ready in the next one.
