### ISSUE TITLE
[Docs] The page jumps

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1382]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

latest master @ Chrome

## 📋 Steps to reproduce

1. Go to the Deep Dive > User interface > Third-party UI guide
2. Change header

## ✅ Expected result

The page does not jump.

## ❎ Actual result

The page jumps.

## 📃 Other details that might be useful

![peek 2018-11-30 10-44](https://user-images.githubusercontent.com/247363/49281449-e0dd5300-f48c-11e8-86b3-fe06e478853c.gif)

**Comment by Reinmar** [comment]
That's a known issue with Bootstrap. We had to accept it :(
