### ISSUE TITLE
List breaks when you paste content as plain text

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#13826]
## 📝 Provide detailed reproduction steps (if any)

1. Go to [demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html).
2. Create a list with two nested list items
3. Copy two list items from some other list
4. Put the cursor at the beginning of the first nested list item
5. Paste as plain text (`cmd+shift+v`)

### ✔️ Expected result

Content gets pasted as new list items or at least inside the list item. Example from Google Docs.
  
First paste is normal, second is pasted as plain tex:

https://user-images.githubusercontent.com/34380544/230026525-f03b6eb8-9078-4a90-b8aa-2c8c00baf8eb.mov

### ❌ Actual result

List breaks (happens for both normal and document lists).
  
First paste is normal, second is pasted as plain text:

https://user-images.githubusercontent.com/34380544/230026602-5f2d86b5-a00c-46b7-81d9-5e9e1272754d.mov

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
We could handle this in the `PastePlainText`.

The outcome is to create the same style of list items when pasting with plain text.

Ref: 

*   [https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-clipboard/src/utils/plaintexttohtml.ts](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-clipboard/src/utils/plaintexttohtml.ts)
*   https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-clipboard/src/pasteplaintext.ts
