### ISSUE TITLE
[TS] Update README

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#13831]
Add a section to quickstart and describe this project is written in typescript, provides types, and link to: https://ckeditor.com/docs/ckeditor5/latest/installation/working-with-typescript.html

A badge maybe could be added to catch the sight earlier: https://github.com/microsoft/TypeScript/issues/31569

**Comment by Witoso** [comment]
Questions to answer:
* should we add the badge?
* should it be added to all READMEs?

**Comment by apadol-cksource** [comment]
@Witoso will do. We may make it clearer it the overview section tho.
