### ISSUE TITLE
The output properties of angular component do not accept editor types from predefined builds

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#13838]
## Reproduction step:
1. Create a new project using Angular CLI
2. Install @ckeditor/ckeditor5-angular @ 6.0.0 or alpha
3. Install any of the predefined builds @ 37.0.1
4. Import the build and put the editor somewhere in the HTML. Create a handler for the ready event with the editor as an argument and provide types coming from predefined builds.
```
// app.component.ts

import { Component } from '@angular/core';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

@Component( {
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.scss' ]
} )
export class AppComponent {
  title = 'angular';
  public Editor = ClassicEditor;

  public onReady( editor: ClassicEditor ): void {
    console.log('test');
  }
}
```
```
<ckeditor [editor]="Editor" data="<p>Hello, world!</p>" (ready)="onReady($event)"></ckeditor>
```
5. Run the app

## Current result:
Compiler throws an error:
```
Argument of type 'Editor' is not assignable to parameter of type 'ClassicEditor'.
Type 'Editor' is missing the following properties from type 'ClassicEditor': sourceElement, updateSourceElement, setData, getData

<ckeditor [editor]="Editor" data="<p>Hello, world!</p>" (ready)="onReady($event)"></ckeditor>
```

## Expected result:
The app compiles correctly and the component accepts editor types coming from predefined builds. Alternatively: there is another way to make it work without installing additional dependencies.

**Comment by pomek** [comment]
Couldn't the implementation be simplified?

https://github.com/ckeditor/ckeditor5-angular/blob/bcccc0e84c2a1dfa35b693ac441e741c600b6adc/src/ckeditor/ckeditor.component.ts#L75

See [vue](https://github.com/ckeditor/ckeditor5-vue/blob/8d94b65e56893338cabdddd5c432f691a324ea78/src/ckeditor.ts#L30) and [react](https://github.com/ckeditor/ckeditor5-react/blob/bd6d9a9b6ba79de4d02120198106976d941f4eea/src/ckeditor.tsx#L310).

We must ensure that the passed object contains the `.create()` function and resolves a promise with an editor. That's all.

**Comment by mremiszewski** [comment]
If that would solve the issue, then it's even better.

I was rather thinking about changing the component declaration to 
```
export class CKEditorComponent<TEditor extends Editor = Editor> ...
```

and all (or almost all because `watchdog`) occurrences of `Editor` to `TEditor`, so using this component compiler will know that the `ready` event is emitting exactly the same type as the `editor` input property.

**Comment by apadol-cksource** [comment]
Just discovered that we can also set `strictTemplates` to `false` in the default AngularCLI configuration and that would be actually more elegant than using `any`.

**Comment by mremiszewski** [comment]
I created a PR in `ckeditor5-angular` repository https://github.com/ckeditor/ckeditor5-angular/pull/363.

**Comment by Reinmar** [comment]
> Just discovered that we can also set `strictTemplates` to `false` in the default AngularCLI configuration and that would be actually more elegant than using `any`.

This isn't a viable solution for some people. Changing the tsconfig of one's project to loosen the checks might not be accepted by its maintainers as it affects the entire project.

So, in my opinion this should be reverted: d862032

And this is the correct workaround for now: 633eb37

**Comment by gorzelinski** [comment]
Yeah, changing the config works. But I didn't advise it because of the mentioned reasons.
