### ISSUE TITLE
Save Content Into JSON Format

### ISSUE THREAD

**Issue by fadsel** [ckeditor/ckeditor5#13843]
Currently uou can only serialize the saved data into HTML or to Markdown, 
Now Imagine if you even save the content in your own custom JSON format that is tailored to your use case.

_What is the expected behavior of the proposed feature?_
I Should have an option to eaither save your content in MarkDown, Raw HTML or JSON
---

You can Checkout 
https://docs.slatejs.org/walkthroughs/06-saving-to-a-database
or even in Keystone
https://keystonejs.com/docs/guides/document-field-demo#content

Open the Document Field Structure to learn more.

Goal is to use separate elements in Android without having to get WebView render it all via a single HTML , You see sometimes you mightr want to include elements in between e.t.c like for a pro version , they just need to read the first part or paragraph e.t.c the possiblities are endless

**Comment by Reinmar** [comment]
There's currently no official data processor for that but #620 contains working examples of how one can approach this.
