### ISSUE TITLE
When using TypeScript all imports must go through package main file (src/index.js)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#13849]
Applies to:

*   [https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html#typescript-2](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html#typescript-2) (imports need to be corrected)
*   [https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-webpack.html#typescript-2](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-webpack.html#typescript-2) (imports need to be corrected)
*   [https://ckeditor.com/docs/ckeditor5/latest/installation/working-with-typescript.html](https://ckeditor.com/docs/ckeditor5/latest/installation/working-with-typescript.html) (missing section about the rule that all imports must go through the src/index.js – ask the core team for more clarification why if needed)

This rule is mentioned in the 2nd point of this migration guide: [https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-37.html#typescript-typings](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-37.html#typescript-typings)

![](https://user-images.githubusercontent.com/156149/231086979-9ba419c3-516b-4b6e-bf21-8f148c3a0397.png)

Without adhering to it one may stumble upon weird typing errors (it's actually worth quoting somewhere in the docs the exact error that would be thrown because people may be googling it). Again, consult the core team for more info.

**Comment by stefanseeger** [comment]
Migrating to 27 with typescript is literally impossible at the moment.

As mentioned by @Reinmar we are supposed to not use the src paths anymore and remove all @types. But at the same time not all packages were updated to export the types like `@ckeditor/ckeditor5-special-characters`. https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html#demo

This should not happen for a paid software.
