### ISSUE TITLE
Multi-root editor Data changes cannot be traced to which node changed

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#13848]
## 📝 Provide a description of the improvement

_How the feature works now and what you'd like to change_?

## 📃 Other details

* Browser: chrome 112
* OS: windows 11
* CKEditor version: 37
* Installed CKEditor plugins: …

---

If using search and replace, it will trigger data changes across multiple nodes

**Comment by Reinmar** [comment]
cc @scofalik

**Comment by scofalik** [comment]
Please explain exactly what is your issue and what you would like to achieve. I understand that this is something related to search and replace and mulit-root editor but please add more explanation.

**Comment by scofalik** [comment]
A proper way to check it is by using model differ and check each change that was introduced in given change event. This is the best way, as the changes may be introduced to the document in places different than current selection (undo and real-time collaboration comes to my mind first).

```javascript
editor.model.on( 'change:data', () => {
	const differ = editor.model.document.differ;
	const changes = differ.getChanges();
	
	for ( const change of changes ) {
		// Iterate through changes and see which roots are affected.
		// See the API to see what properties are in `change`.
	}
} );
```

I recommend getting familiar with [`model.Differ` API](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_differ-Differ.html#function-getChanges). You may also want to use `differ.getChangedRoots()` and `differ.getChangedMarkers()` here, depending on what exactly you want to achieve.

BTW. I wonder if maybe you are trying to implement a flag, that would check whether given root was changed, to make save only the changed roots? If so, this is something that we will also want to introduce in later releases (other things has bigger priority now but such flag will be very useful for integrators).

Please close the ticket if this helps.

**Comment by huzedong2015** [comment]
Yes, I just want to save only the modified roots. Because we actually have dozens of roots, we cannot save all of them.
Also, it is not possible to disable specified root editing

**Comment by huzedong2015** [comment]
How can I obtain the root of the changed content now?

I am currently using `MutationObserver` and the results are not very good

**Comment by scofalik** [comment]
I already explained how to do it using `Differ#getChanges()` in the `change` event. You should never observe changes in DOM or view, only in the model.

**Comment by huzedong2015** [comment]
> I already explained how to do it using `Differ#getChanges()` in the `change` event. You should never observe changes in DOM or view, only in the model.

But I don't know which root caused the change

**Comment by scofalik** [comment]
Each item in `getChanges()` has position or range where the change happened. Both position and range has `root` property.
