### ISSUE TITLE
Expose Watchdog and Context on Editor class and update integrations. 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#13852]
Notes: 
* We exposed Watchdog on the editor class in order to remove that specific dependency on the package. See #13707.
* The Angular integration still has cke5-watchdog in its dependencies and imports it directly. 
* Most likely, the same changes would make now sense in the React integration too.
* There's also ckeditor/ckeditor5-angular#364, but to my knowledge seems unrelated.

**Comment by Reinmar** [comment]
How was that supposed to work in Angular integration?

**Comment by Witoso** [comment]
Scope:
* Expose `Context`, `EditorWatchdog`, and `ContextWatchdog` as static editor properties of the base `Editor` class.
* Remove `Context`, `EditorWatchdog`, and `ContextWatchdog` from editor implementations (e.g., `ClassicEditor`).
* In the integrations, use the `Context`, `EditorWatchdog`, and `ContextWatchdog` from the main editor class.
