### ISSUE TITLE
Add a simple method to insert HTML content to the editor

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [ckeditor/ckeditor5#13877]
I'm trying to insert the simplest possible html content into the editor. I've been looking through the docs and other support sections but it's so messy I can't find an easy way to do this.

So I want to append `<span class="badge-badge-secondary">example</span>` to the beginning of the editor. It won't work with `innerHTML` as you are creating your own editor object and it will break the whole flow. It's ok, let's use the methods of editor object but it shouldn't be this complicated and hard to do.

There is also no simple focus method for the editor. It's unbelievable! I'm talking about the most basic need. There should be a simple `focus()` in the editor.

**Comment by urbanspr1nter** [comment]
IMO, I don't think it is particularly necessary to have an `insertHtml` helper. It can probably be done our own. I think it can be done in something like 3 lines:

```
const viewFragment = editor.data.processor.toView(html);
const modelFragment = editor.data.toModel(viewFragment);

editor.model.insertContent(modelFragment);
```

**Comment by Witoso** [comment]
Hey, thanks for the feedback @g-u-r-k-a-n!

There are several methods to add content:
1. you can just use `editor.setData()`.
2. you can include HTML in the editor element on the page like:
  ```
    <div id="editor">
      <h1>Hello, world!</h1> <!-- this will be loaded to the editor-->
    </div>
```
3. if you want a placeholder, use [this](https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html#styling-the-placeholder).
4. More direct work with views and models, as showed in the comment above.

As for the focus, it's [there](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_view-View.html#function-focus). I'm a bit surprised it was hard to discover (search on our docs works quite well). Use `editor.editing.view.focus()`.

FYI @apadol-cksource (docs feedback).

**Comment by g-u-r-k-a-n** [comment]
I've had tried `insertContent()` with different fragments but it's overriding the html tags, I was starting to think it was completely prevented for security. To be honest I never would have guessed that 'setData()' method would be able to inject html since it has 'data' in its name. 🤦‍♂️Even I used `editor.data.set()` before posting this issue :) Probably, usage of placeholders in the list you sent seems to work for me. I will review them separately.

I tried the [focus](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-focus)`here, but it wasn't focusing on the editor. I can't find that you have different focusing methods in the engine section, I'll try and post the result. Thanks for your help @Witoso 👍

**Comment by g-u-r-k-a-n** [comment]
> Hey, thanks for the feedback @g-u-r-k-a-n!
> 
> There are several methods to add content:
> 
> 1. You can just use `editor.setData()`.
> 2. You can include HTML in the editor element on the page like:
> 
> ```
>   <div id="editor">
>     <h1>Hello, world!</h1> 
>   </div>
> ```
> 
> 3. If you want a placeholder, use [this](https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html#styling-the-placeholder).
> 4. More direct work with views and models, as shown in the comment above.
> 
> As for the focus, it's [there](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_view-View.html#function-focus). I'm a bit surprised it was hard to discover (search on our docs works quite well). Use `editor.editing.view.focus()`.
> 
> FYI @apadol-cksource (docs feedback).

Hello @Witoso,

I didn't remember that I have already used the placeholder. You can see the editor from https://gurkantuna.com/article/1/soluk-mavi-nokta#write-comment

I created a simple project from your starter template. You can review it from https://codepen.io/g-u-r-k-a-n/pen/oNabwbz
I tried your list but they don't allow html tags, focus doesn't work either. Do I need to change some parameters, can you tell me the solution to this project in codepen?

**Comment by Witoso** [comment]
Sorry for the late reply, if you want to load HTML like `span`'s you need to add a [GeneralHtmlSupport](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html) as by default editor doesn't except those elements.
