### ISSUE TITLE
Spaces are removed after typing a character in ckeditor5.

### ISSUE THREAD

**Issue by csharpee** [ckeditor/ckeditor5#13875]
The spacebar works, but after I hit the spacebar then type a character, the space is removed and the letters scrunch together. It happens in both FF and GC.

One way to temp allow me to write an article with cke5 is by the following:

step 1: type character a as an example
step 2: goto beginning of line by hitting the home key
step 3: type your characters and words without spaces being cleared.

If I apply the spacebar twice, then the space is inserted.

**Comment by Witoso** [comment]
I could not reproduce the issue in our editor here: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
At the same time, I'm not sure I understand the case correctly. Please write more about your setup, and it would be best if you use our bug template. Thanks!
