### ISSUE TITLE
CDN certificate is expired

### ISSUE THREAD

**Issue by shmokmt** [ckeditor/ckeditor5#13887]
The certificate for https://cdn.ckeditor.com/ is expired

same issue: https://github.com/ckeditor/ckeditor4/issues/5459

**Comment by sajimavelil** [comment]
https://cdn.ckeditor.com/4.19.1/standard-all/ckeditor.js says "Warning: Potential Security Risk Ahead" due to certificate expiry

**Comment by arunvc** [comment]
Editors not working in sites using cdn url

**Comment by arunvc** [comment]
work around, 

download ck editor js eg https://cdn.ckeditor.com/4.19.1/standard-all/ckeditor.js
copy ckeditor.js to **assets/js**  folder
search for **cdn.ckeditor.com** in your source code
```
change
this.editorUrl="https://cdn.ckeditor.com/4.19.1/standard-all/ckeditor.js"
to
this.editorUrl="https://yourdomain.com/assets/js/ckeditor.js"
```
yourdomain is your site url

**Comment by sajimavelil** [comment]
It worked !!! Thank you Arun

**Comment by shmokmt** [comment]
I am not very familiar with CKEditor, but I've come up with a workaround as follows.

First, download the CKEditor package that matches the version you are currently using from the download page:
https://ckeditor.com/ckeditor-4/download/

Next, create a CloudFront distribution with AWS S3 as the origin, and upload all the downloaded files to S3.

If you want to match the patch version completely, you can download it from here: https://download.cksource.com/CKEditor/CKEditor/

**Comment by sajimavelil** [comment]
Work Around in detail is below:

	(1) download ckeditor_4.19.1_standard.zip from https://ckeditor.com/ckeditor-4/download/releases/index.html
	(2) extract the "ckeditor_4.19.1_standard.zip" file you will get "ckeditor" folder
	(3) copy paste ckeditor" folder to application folder -> sub folder "assets"
	(4) download all required skins & plugins and put the corresponding folders inside skins subfolder or plugins subfolder inside ckeditor folder
	(5) in angular folder edit file "features-user-user-module.js" then replace "https://cdn.ckeditor.com/4.19.1/standard-all/ckeditor.js" with "assets/ckeditor/ckeditor.js"

**Comment by wwalc** [comment]
We are checking it with the CDN provider, the new SSL certificate was uploaded there several days ago :/ Thank you for reporting it.

**Comment by wwalc** [comment]
We are updating the DNS now - in order to bring back to live CDN ASAP we decided to immediately switch to a new vendor. The DNS propagation may take a while (usually \<1h, but sometimes up to 24h) so if you need an instant fix, change the URL to start with [https://d3vxtqk803u6i6.cloudfront.net](https://d3vxtqk803u6i6.cloudfront.net/ckeditor5/37.0.1/multi-root/ckeditor.js). Remember to change it back to [https://cdn.ckeditor.com](https://cdn.ckeditor.com) after April, 20th 2023.

**Comment by wwalc** [comment]
We should be back live. Unfortunately, the DNS propagation may take a while as explained above. Restarting the browser, and flushing the DNS etc. may help to see the results immediately. Of course, it's very unlikely you will be able to instruct all your users to do so, so depending on the urgency you may change the URL as instructed above or just wait for max a couple of hours.

Apologies for the inconvenience. I guess I will not need any more ☕ today.

**Comment by sajimavelil** [comment]
Thank you for supporting team !! :-)
