### ISSUE TITLE
Font plugin: support of point to set font-size

### ISSUE THREAD

**Issue by TatianaAU** [ckeditor/ckeditor5#1389]
🆕 Feature request  
Font plugin: support for points to set the font-size

💻 Version of CKEditor

inline build v11.1.1, font-plugin v10.0.3

 📋 Steps to reproduce

1. call setData() with html text:
 `<p><span style=\"font-size:10pt;\">some text </span></p>`

 ✅ Expected result
Font size applied.

 ❎ Actual result
Font size remains unchanged for this element.

**Comment by jodator** [comment]
You can achieve this [using configuration](https://ckeditor.com/docs/ckeditor5/latest/api/module_font_fontsize-FontSizeOption.html):

```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ArticlePluginSet, FontSize ],
		toolbar: [
			'heading', '|', 'fontSize' //..., 
		],
		fontSize: {
			options: [
				generatePtSetting( '10' ),
				generatePtSetting( '12' ),
				generatePtSetting( '14' ),
				'default',
				generatePtSetting( '18' ),
				generatePtSetting( '20' ),
				generatePtSetting( '22' ),
			]
		}
	} );

function generatePtSetting( size ) {
	return {
		model: size,
		title: size,
		view: {
			name: 'span',
			styles: {
				'font-size': `${ size }pt`
			}
		}
	};
}
```

In action:
![selection_082](https://user-images.githubusercontent.com/247363/49292160-c61ad680-f4ac-11e8-89aa-9603cef812ff.png)
