### ISSUE TITLE
Document List Numbered List properties not working

### ISSUE THREAD

**Issue by yashsinghal** [ckeditor/ckeditor5#13898]
## 📝 Provide detailed reproduction steps (if any)

Properties for DocumentList plugin on numbered list are disable, so I am unable to change the start index and if the list is reversed. Same issue on the Ckeditor Website.

![image](https://user-images.githubusercontent.com/10118581/232578693-e7425e18-bfcd-466a-a3be-d7fd44043c9a.png)

### ✔️ Expected result

Expect to be able to change the start index of the numbered list
### ❌ Actual result

List properties is disabled.

**Comment by yashsinghal** [comment]
Update: The properties become enabled when a list is selected, but changing the start number does nothing.

**Comment by Witoso** [comment]
Hey, thanks for the feedback, I couldn't replicate the issue:
![image](https://user-images.githubusercontent.com/9881379/232695901-7e988fa5-10fd-48a2-bb10-a91dc09db804.png)

Please check other browsers, and let us know which one are you using.

**Comment by yashsinghal** [comment]
Using chrome, this doe snot work on my local system when I use a build from the online ckeditor builder. When I try to use the API, it get the error:
`commandcollection-command-not-found {"commandName":"documentListStart"}`

**Comment by yashsinghal** [comment]
Also, the the start index increment works in the sample index file provided with the build, but when I try to integrate it with a Vue 2 application, it stops working. Everything else was working as far as I know.

**Comment by yashsinghal** [comment]
Incrementing issue solved, internal css was setting the counter-increment value
