### ISSUE TITLE
Find and replace replace all & undo

### ISSUE THREAD

**Issue by kbinieda** [ckeditor/ckeditor5#13892]
Currently, find-and-replace `replace all` feature does not work well with undo feature, that is a single undo step rollbacks only one change instead of all changes.

That makes scenarios with lots of changes hard to rollback, ex. 1k changes with single `replace all` click will need 1k undo clicks to rollback to previous state.

Steps to reproduce:
1. Use find-and-replace replace all command on any manual test with a keyword that returns multiple results.
2. Try to rollback the changes using undo button.

**Comment by mlewand** [comment]
Fixing it should be as simple as wrapping [`_replace()` call in replace all command](https://github.com/ckeditor/ckeditor5/blob/97e7815e182d14a49d557771191349dc64f36cf2/packages/ckeditor5-find-and-replace/src/replaceallcommand.ts#L53-L55) with a `model.change()` call that will batch it into one transaction.

**Comment by Ruman-Al** [comment]
I don't know how to use replace all.because as I am implemented it didn't do anything.can you show me the implementation.
