### ISSUE TITLE
There's a space left after the autoformatting and pressing 2x undo 

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1390]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Create a new paragraph
2. Type <kbd>></kbd> and <kbd>Space</kbd>
3. 3x undo.
4. Hit <kbd>Enter</kbd>

## ✅ Expected result
After the second undo the autoformat (and possibly the `>` and a space to create that format should be removed too - https://github.com/ckeditor/ckeditor5/issues/834
After the next undo the paragraph should be removed.
After pressing <kbd>Enter</kbd> new empty paragraph should be created

## ❎ Actual result
After the first undo there's a `>` and space.
After the second undo there's one space in the paragraph.
After the third undo the result is as before changes
Now, after pressing enter, the new paragraph also contains a space. 

## 📃 Other details that might be useful

Connected with the https://github.com/ckeditor/ckeditor5/issues/834.

It's possibly a regression - on the https://ckeditor5.github.io/ it works fine.

**Comment by Mgsy** [comment]
It's not reproducible anymore.
