### ISSUE TITLE
[Docs] Check Bootstrap guide

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1391]
According to https://stackoverflow.com/questions/53556541/ckeditor-5-popup-controls-not-working-in-bootstrap-3-2018 the information in our docs may not be sufficient to make CKE5 work in Bootstrap modal. That's odd, because it worked. We should verify that.

**Comment by va5ja** [comment]
I'm not sure if this was addressed already but there's also an issue with "Insert media" feature and Bootstrap 4.

CKEditor inserts `<figure class="media ck-widget ck-widget_selected" contenteditable="false">`. So there's a `media` class.
Bootstrap also has a class `media` defined and this makes the figure have 0px height. You basically don't see anything.

**Comment by Reinmar** [comment]
It'd be good to cover this too. Thank you for pointing this out.

**Comment by Reinmar** [comment]
The problem with Bootstrap and media embedding was reported in https://github.com/ckeditor/ckeditor5/issues/1373. Once we'll have a solution, please post it there too.

**Comment by dkonopka** [comment]
> I confirm that https://codepen.io/ckeditor/pen/vzvgOe doesn't work.

By 'doesn't work' you mean editing the second step inside link balloon? Because it is working for me.

[I even created a codepen with Bootstrap 4 integration and it's working for me too.](https://codepen.io/k0n0pka/pen/yqBXOz)
