### ISSUE TITLE
[TS] Document "augmentation.ts" as Best Practice for Plugin Developers

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#13929]
## 📝 Provide a description of the improvement

Reading through your TypeScript sources, the `augmentation.ts` pattern seems to be a very nice one, developers of custom plugins may want to adapt.

I suggest extending the documentation accordingly around here:

* [TypeScript package - CKEditor 5 Documentation](https://ckeditor.com/docs/ckeditor5/37.1.0/framework/plugins/package-generator/typescript-package.html)

And, if not already part of it, I would suggest, that the package-generator just also creates this file as one of the artifacts.

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 37.0.1
* Installed CKEditor plugins: Custom Ones

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
> And, if not already part of it, I would suggest, that the package-generator just also creates this file as one of the artifacts.

👍 That's the plan: https://github.com/ckeditor/ckeditor5-package-generator/issues/144
We will also update the docs there.

Thanks for the feedback!
