### ISSUE TITLE
[TS] Make `bodyCollectionContainer ` public

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#13928]
Make `bodyCollectionContainer ` public.
https://github.com/ckeditor/ckeditor5/blob/fba274b35d542764148c1996a74c91df01e4151b/packages/ckeditor5-ui/src/editorui/bodycollection.ts#L44

Rel: #9539 

> several use cases where developers need to access it:
> * to add a class there, 
> * to move the entire container e.g. to the same parent w/ overflow: hidden that hosts the editing root so all the pieces of the UIs get cut in the same way,
> * to move the entire container to a different CSS context (e.g. to inherit styles), right now it's always straight in body > .

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
Agreed with @oleq , that this property should be read-only.
