### ISSUE TITLE
Find a way to clean up ckeditor5.github.io repo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1392]
We publish new docs to https://github.com/CKEditor5/ckeditor5.github.io every day and this repo became extremely heavy. I think it should be possible to make `master` point to a subtree of the current master containing e.g. only the last `10` commits and completely clean up refs to other commits.

**Comment by wwalc** [comment]
Or... just publish nightly docs on S3.

**Comment by Reinmar** [comment]
And what we would do with `ckeditor5.github.io`? Besides, at various times we're building that page manually and publish docs manually. Right now we use GH credentials for that. We'd need to figure out how to best do that with S3. I think that cleaning up the commits history will be easier.

Anyway, I'm quite sure someone had to do this already. Creating new `master` tree should not be a big deal. Removing old refs as well.

**Comment by pomek** [comment]
We could use a Travis CRON for do that.

**Comment by Reinmar** [comment]
It's enough if we do it manually every couple of months, but sure, we could have a monthly job that does it. But the clue is – how to get rid of old commits.

**Comment by pomek** [comment]
Checkout to an empty branch and cherry pick 10 last commits from current master. Then rename those branches and the new one will be a new master.

**Comment by pomek** [comment]
> Did you test it?

Yea. It didn't work. But I spend some time and I finally found a solution.

There is a bash script that can be run on the CI as CRON job.

```bash
# Thanks to: https://stackoverflow.com/a/41953383/3388924.

# Copy the last one commit. Known as <commit> in the instruction.
git log --oneline -n 10

# Checkout to the status of the git repo at commit. Create a temporary branch.
git checkout --orphan temp <commit> 

# Create a new commit that is to be the new root commit.
git commit -m 'Documentation build.'

# Rebase the part of history from <commit> to master on the temporary branch.
git rebase --onto temp <commit> master

# Remove the temporary branch.
git branch -D temp

# YOLO.
git push -f

# Commands specified below are optional. I guess those touch local repository only.

# Delete all the objects w/o references.
git prune --progress

# Aggressively collect garbage.
git gc --aggressive
```

It even works – https://github.com/pomek/ckeditor5.github.io/commits/master.

**Comment by pomek** [comment]
When cloning a repository with 10 last commits:

```
git clone git@github.com:pomek/ckeditor5.github.io.git
Cloning into 'ckeditor5.github.io'...
remote: Enumerating objects: 81312, done.
```

vs. this full repo:

```
git clone git@github.com:CKEditor5/ckeditor5.github.io.git
Cloning into 'test'...
remote: Enumerating objects: 119796, done.
```

 I guess we should take 5 last commits instead of 10. Do we really need that history?

**Comment by oleq** [comment]
> I guess we should take 5 last commits instead of 10. Do we really need that history?

I don't think so.

**Comment by Reinmar** [comment]
> When cloning a repository with 10 last commits:

How much time did it take to clone that?

> Do we really need that history?

Nope. 5 will be enough.

**Comment by pomek** [comment]
For the entire repository:

```basg
time git clone git@github.com:CKEditor5/ckeditor5.github.io.git
Cloning into 'ckeditor5.github.io'...
remote: Enumerating objects: 122312, done.
remote: Total 122312 (delta 0), reused 0 (delta 0), pack-reused 122312
Receiving objects: 100% (122312/122312), 180.30 MiB | 2.69 MiB/s, done.
Resolving deltas: 100% (114556/114556), done.
Checking out files: 100% (15171/15171), done.

real	2m25.894s
user	1m22.581s
sys	0m19.112s
```

For the repo with 10 commits:

```bash
time git clone git@github.com:pomek/ckeditor5.github.io.git forked
Cloning into 'forked'...
remote: Enumerating objects: 81312, done.
remote: Total 81312 (delta 0), reused 0 (delta 0), pack-reused 81312
Receiving objects: 100% (81312/81312), 88.13 MiB | 2.30 MiB/s, done.
Resolving deltas: 100% (76522/76522), done.
Checking out files: 100% (15131/15131), done.

real	1m40.170s
user	0m52.775s
sys	0m14.020s
```

**Comment by pomek** [comment]
Should I set-up a monthly task in CRON on CI or clear the repository manually?

**Comment by Reinmar** [comment]
👍  That'd be great.
