### ISSUE TITLE
v37.1.0 fills empty text in reverse (CI / Splinter / Selenium)

### ISSUE THREAD

**Issue by tony** [ckeditor/ckeditor5#13926]
## 📝 Provide detailed reproduction steps (if any)

This may take time for a recreation repo - unless someone else confirms it first

**Tuesday, June 27th, 2023:** [Recreated here](https://github.com/ckeditor/ckeditor5/issues/13926#issuecomment-1609368297) by @urbanspr1nter by throttling CPU 4x/6x (see [Chrome Docs](https://developer.chrome.com/docs/devtools/performance/reference/#cpu-throttle) re: CPU throttling)

### ✔️ Expected result

As of v37.0.1 and earlier, text filled in empty fields, e.g. splinter's [`ElementAPI.fill()`](https://splinter.readthedocs.io/en/latest/api/driver-and-element-api.html?highlight=fill#splinter.driver.ElementAPI.fill) worked as such:

`el.fill('Text should be in order')`

> Text should be in order

As in v37.0.1:

https://user-images.githubusercontent.com/26336/233174074-98bb8978-143c-4e5c-9950-2a5bddf67a64.mp4

### ❌ Actual result

Having [splinter](https://splinter.readthedocs.io/en/latest/index.html) (selenium wrapper) with v37.1.0 in an empty field:

> redro ni eb dlouhs txet

in v37.1.0

https://user-images.githubusercontent.com/26336/233174138-f9b786d7-f6ab-467a-866e-e505d10d6cf9.mp4

### ❓ Possible solution

Is there any changes to the input / engine that could cause text to seemingly be typed in reverse?

## 📃 Other details

* Browser: Chrome 112.0.5615.138 
* OS: Windows 11
* First affected CKEditor version: 37.1.0
* Installed CKEditor plugins: Core, engine, image, table, etc.
* Related: https://github.com/ckeditor/ckeditor5/issues/13994
* Possible recreation: Set CPU throttling on Chrome dev tools to 4x/6x (see [here](https://github.com/ckeditor/ckeditor5/issues/13926#issuecomment-1609368297))

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Most likely related to #13913. And sounds very similar to the issues that we've seen after migrating to beforeInput. Unfortunately, these tools seem to mimic user typing in a poor way ;/ With the spell checkers it helped when they started firing correct events.

cc @niegowski

**Comment by Witoso** [comment]
We discussed this within the team. @tony it would be great if you could prepare for us some example repo in which we could test the behavior.

**Comment by urbanspr1nter** [comment]
> Most likely related to #13913. And sounds very similar to the issues that we've seen after migrating to beforeInput. Unfortunately, these tools seem to mimic user typing in a poor way ;/ With the spell checkers it helped when they started firing correct events.
> 
> cc @niegowski

I've been able to reproduce an effect of "reverse typing" on much slower machines. It's not that the typing is "reversed", but more like the cursor is "stuck" and isn't updating -- so text just keeps getting added behind the cursor. Seems to be something with setting the DOM selection. The behavior seems to be more obvious when the JS thread is very busy and the user is typing during this time. Funny enough, when things settle slightly, the cursor is able to update again, and the user doesn't really need to do anything.

**Comment by Witoso** [comment]
Interesting! We have the report for Android as well: #13994. Did you test it on the desktop @urbanspr1nter?

**Comment by urbanspr1nter** [comment]
@Witoso yes- this is on desktop/web too. :) 

I was able to actually repro it a couple times in the inline editor demo here: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html 

Simulating throttling of CPU by 4x/6x on DevTools, and loading the page before the content has settled allowed me to briefly reproduce the issue at some point.

**Comment by urbanspr1nter** [comment]
Any update on this one?

**Comment by Witoso** [comment]
Hey @urbanspr1nter, no, we haven't started investigating it yet, and when I think about it, this deserves a separate issue (#14569) as it's not related to automated tests.

If you could briefly comment there how much it affects your product, or how often it occurs, it would be great. It would help us to prioritize it better, as we didn't get any reports about it so far.

**Comment by urbanspr1nter** [comment]
@Witoso  Sure I'll take the discussion over to there.

**Comment by Witoso** [comment]
Hey @tony! I would appreciate it if you could confirm it after the release. I'm not sure if the fix will help this automated testing use case, but there is a chance.

**Comment by Reinmar** [comment]
Is this still relevant? I didn't see any feedback about this for the last months.

**Comment by urbanspr1nter** [comment]
@Reinmar @Witoso @tony  I'd like to point out that there is still a corner case here:

https://github.com/ckeditor/ckeditor5/issues/14702

It actually happens in several other instances. The main problem here is that the reverse typing is always going surface up if somehow CKE5 loses connection with the real DOM selection. 

We've had several instances of this occurring even after the initial fix, but have gotten around it by listening on `beforeInput` and manually performing the necessary steps to restore selection. The effect in restoring the selection is pretty transparent -- so it works kind of well, but there are cases where it is impossible to avoid this reverse typing due if DOM selection update/focus is trapped. 

One way to actually simulate this is to forcefully blur the editable while the selection is active:

```
// In 5 seconds, this will cause reverse typing
setTimeout(() => {
  const editable = document.querySelector("div.ck-editor__editable");
  editable.dispatchEvent(new FocusEvent("blur"));

  console.log("Now, try to type!");
}, 5000);
```

See the animated GIF here in the official Inline editor demo:
![backwards](https://github.com/ckeditor/ckeditor5/assets/1388415/dbda9756-3ee7-435c-82f3-1bb5c531a26d)

Some JS libraries don't play nice and actually perform something similar to my synthetic repro above.

Wondering what can be done to be more resilient here? Happy to help with that. :)

**Comment by urbanspr1nter** [comment]
@tony , that's a great idea. I'll create a new issue and give the same details. 😊
