### ISSUE TITLE
Issue Regarding Comments Archive and Revision History.

### ISSUE THREAD

**Issue by Govardhan9814s** [ckeditor/ckeditor5#13939]
we are using Ckeditor5 with comments and Revision history with trail licence, once our project got stabled we will buy premium. we are facing issue with CommentsArchive, we are saving resolved and unresolved threads using commentsRepository into database.

const commentsRepository = this.editor.plugins.get( 'CommentsRepository' );
     // Get the data on demand.
         const editorData = this.editor.data.get();
         console.log(editorData);
         const commentThreadsData = commentsRepository.getCommentThreads( {
             skipNotAttached: true,
             skipEmpty: true,
             toJSON: true
         } );
         const trackChanges = this.editor.plugins.get( 'TrackChanges' ).getSuggestions( {
          skipNotAttached: true,
          toJSON: true
      } ); 
again we reload the  into editor it is giving error like
getCommentsAndTrackChangesData(collaborationEditorModel: any) {
    return class TrackChangesAdapter {
      public editor: CKEditor5.Editor;
      public constructor(editor: CKEditor5.Editor) {
        this.editor = editor;
      }

      public init(): void {
        const usersPlugin = this.editor.plugins.get('Users');
                // Load the users data.
                for (const user of collaborationEditorModel.users) {
                  usersPlugin.addUser(user);
                }
        const commentsRepositoryPlugin = this.editor.plugins.get('CommentsRepository');

        // In order to load comments added to suggestions, you
        // should also configure the comments integration.
        // Load the comment threads data.
        if(collaborationEditorModel.comments !== '' && collaborationEditorModel.comments !== undefined){
          for (const commentThread of collaborationEditorModel.comments) {
                commentsRepositoryPlugin.addCommentThread(commentThread);
            }
        }
        const trackChangesPlugin = this.editor.plugins.get('TrackChanges');
        if(collaborationEditorModel.isFromPreview === 'n'){
             // Set permissions.
             const permissions = this.editor.plugins.get( 'Permissions' );
              // "Commentator" role.
              permissions.setPermissions( ['document:write','comment:write']);
              this.editor.commands.get( 'acceptSuggestion' ).forceDisabled( 'suggestionsMode' );
              this.editor.commands.get( 'acceptAllSuggestions' ).forceDisabled( 'suggestionsMode' );
              this.editor.commands.get( 'discardAllSuggestions' ).forceDisabled( 'suggestionsMode' );
              this.editor.commands.get( 'discardSuggestion' ).forceDisabled( 'suggestionsMode' );
        }

        // Set the current user.
        usersPlugin.defineMe(collaborationEditorModel.userId);

        // Load the suggestions data.
        if(collaborationEditorModel.suggestions !== ''){
        for (const suggestion of collaborationEditorModel.suggestions) {
          trackChangesPlugin.addSuggestion(suggestion);
        }
      }
      }
    };
  }
iam unable to found api or any doc on how to push resolved threads into comments archive and how to make content available.

Error:
====
re.mjs:8416 ERROR Error: Uncaught (in promise): CKEditorError: Cannot read properties of null (reading 'name')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of null (reading 'name')
TypeError: Cannot read properties of null (reading 'name')
    at new cv (userview.js:23:802)
    at new Uw (commentthreadinputview.js:23:1275)
    at hA._createCommentThreadInputView (basecommentthreadview.js:23:2566)
    at new uA (basecommentthreadview.js:23:2072)
    at new hA (commentthreadview.js:23:1602)
    at Pu._createCommentThreadView (commentsrepository.js:23:70075)
    at Pu._attachCommentThread (commentsrepository.js:23:68880)
    at UD.attachTo (commentsrepository.js:23:84926)
    at Pu.<anonymous> (commentsediting.js:23:4507)
    at Pu.fire (emittermixin.js:146:47)
    at xe (zone.js:1262:35)
    at xe (zone.js:1216:21)
    at zone.js:1329:21
    at T.invokeTask (zone.js:443:35)
    at Object.onInvokeTask (core.mjs:24193:33)
    at T.invokeTask (zone.js:442:64)
    at T.runTask (zone.js:214:51)
    at ue (zone.js:632:39)
    at T.invokeTask [as invoke] (zone.js:529:25)
    at I (zone.js:1727:22)
h

Revision History
===========
how to set Initial and current revision with our editor content.
at very first time it is giving empty document as current and intial version.
if we save our data as current revision then it will follows the flow.
after i loaded both editor data and existing revision from data base  and if i save new revision the flow is disconnected with existing revisions.

const revisionHistory = this.editor.plugins.get( 'RevisionHistory' );
    console.log(revisionHistory);

    // Load revisions data
    if(collaborationEditorModel.revisionHistory !== '' && collaborationEditorModel.revisionHistory !== undefined){
			for ( const revisionData of collaborationEditorModel.revisionHistory ) {
				revisionHistory.addRevisionData( revisionData );
			}

 save: async editor => {
            const revisionTracker = editor.plugins.get( 'RevisionTracker' );
            await revisionTracker.update();
            console.log(revisionTracker);
          }
        }

please lets me know the solutions.

**Comment by FilipTokarski** [comment]
Hi @Govardhan9814s , please note that comments and revision history are premium plugins and this issue tracker is intended for the open source part of the CKEditor 5 ecosystem. 

If you are a licensed user or using the free trial, please [contact our support team](https://ckeditor.com/contact/) and describe the issue together with detailed steps on how to reproduce it.
