### ISSUE TITLE
How to change "i" to "em" output behavior?

### ISSUE THREAD

**Issue by Karla121** [ckeditor/ckeditor5#1394]
In CKE4Editor that was pretty straight forward, however I can't find a way to do the same in CKEditor5.

Currently "i" tag is reserved in my project for icons and that is why I would like to have "em" for italics.

Is it possible?

**Comment by oleq** [comment]
A simple [downcast converter](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcast-converters.html#static-function-downcastAttributeToElement) should do the trick but you'll have to wrap it [as a plugin](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/plugins.html) and load it in your [custom editor build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html):

```js
import { downcastAttributeToElement } from '@ckeditor/ckeditor5-engine/src/conversion/downcast-converters';

function ItalicAsEmPlugin( editor ) {
	editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
		model: 'italic',
		view: ( modelAttributeValue, viewWriter ) => {
			return viewWriter.createAttributeElement( 'em' );
		}
	} ) );
}
```

then

```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ..., ItalicAsEmPlugin ],
		// ...
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```

**Comment by ansorensen** [comment]
This appears to be out of date, and it's a very frustrating feature. In creating content for display on webpages, <em> is more commonly used for italics, and <i> has come to be used for icons.  To avoid strange icons popping up on our site we either have to write a new plugin make sure we have special styles overriding icon styling for ck-editor content (and that we have a way of distinguishing content that was originally produced by ck-editor from other content).

I'm trying to go the plugin route, but this solution is out of date (downcastAttributeToElement is no longer exported), and even the examples in the downcasthelpers.js file don't appear to work as is.

I'm trying to repurpose some an example from /@ckeditor/ckeditor5-engine/src/conversion/conversionhelpers.js:

```
editor.conversion.for( 'downcast' ).attributeToElement( {
  model: 'bold',
  view: ( modelAttributeValue, viewWriter ) => {
    return viewWriter.createAttributeElement( 'span', {
      style: 'font-weight:' + modelAttributeValue
    } );
  }
} );

```
Here's my plugin:
```
export default class ItalicsAsEm extends Plugin {
	static get pluginName() {
		return 'ItalicsAsEm';
	}
  init() {
    console.log( 'ItalicsAsEm#init() got called' );

    export default class ItalicsAsEm extends Plugin {
	static get pluginName() {
		return 'ItalicsAsEm';
	}
  init() {
    console.log( 'ItalicsAsEm#init() got called' );

    this.editor.conversion.for( 'downcast' ).attributeToElement( {
			model: 'italic',
			view: ( modelAttributeValue, viewWriter ) => {
				return viewWriter.createAttributeElement( 'em' );
			}
		} );
     }
  }
}
```

**Comment by oleq** [comment]
The API has been simplified, check out

```js
function ItalicAsEmPlugin( editor ) {
	editor.conversion.for( 'downcast' ).attributeToElement( {
		model: 'italic',
		view: 'em',
		converterPriority: 'high'
	} );
}
```

**Comment by ansorensen** [comment]
Okay, I think I tried that at one point, but I didn't have the converterPriority piece. Maybe that's why it was being ignored.
