### ISSUE TITLE
Handle copy image from source (Not download, just copy)

### ISSUE THREAD

**Issue by bauhuynhdev** [ckeditor/ckeditor5#13944]
## 📝 Provide detailed reproduction steps (if any)
1. Copy image from Google Image (Not download, Right click and select "Copy image")
2. Paste it to Ckeditor 5
### ✔️ Expected result
Render to html tag with src from copied it
### ❌ Actual result
I want give a blob file -> upload to server -> custom html before render to editor.
I can't find any documentation about this

**Comment by Witoso** [comment]
Please make sure you added an [image upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/image-upload.html).

> There are two main strategies of getting the image upload to work that you can adopt in your project:
>  * [Official upload adapters](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/image-upload.html#official-upload-adapters) – There are several features like CKBox providing upload adapters developed and maintained by the CKEditor team. Pick the best one for your integration and let it handle the image upload in your project.
>  * [Custom upload adapters](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/image-upload.html#implementing-your-own-upload-adapter) – Create your own upload adapter from scratch using the open API architecture of CKEditor 5.
