### ISSUE TITLE
Release process: Prepare the repository to release

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13954]
## 📝 Provide a description of the new feature

**🎯 The goal is to prepare the release directory containing the packages we want to publish.**

- We want to copy all files because we will modify the code, and git should not track these changes.
- Create the `release/` directory with the following packages:
    - Copy all selected packages from the `packages/` directory
    - Create the root package if releasing the entire repository
        - Copy files specified in an argument object. We do not want to copy the entire repository.
        - Create a new `package.json` file based on [a template file](https://github.com/ckeditor/ckeditor5-dev/blob/564de3d72ecab882326d2934576a7e48b5c2b36e/packages/ckeditor5-dev-release-tools/lib/templates/release-package.json) and [specified values](https://github.com/ckeditor/ckeditor5/blob/c1202768be7fe8b795d560456551ea9fc87bc441/scripts/release/publish.js#L44-L48) in the argument object.
- Possible arguments:
    - a directory where to look for packages (string)
    - a directory where to store copied packages (string)
    - an object describing the root package

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
Done in https://github.com/ckeditor/ckeditor5-dev/pull/868.
