### ISSUE TITLE
Release process: Update dependencies

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13953]
## 📝 Provide a description of the new feature

**🎯 The goal is to update all dependencies that will be released, including the root package.**

- It mostly covers CKEditor 5 packages. We can simplify the [`updateCKEditor5Dependencies()`](https://github.com/ckeditor/ckeditor5-dev/blob/564de3d72ecab882326d2934576a7e48b5c2b36e/packages/ckeditor5-dev-release-tools/lib/tasks/updateckeditor5dependencies.js) script.
    - It would be good to extract a util `isCKEditor5Package()` that can be reused in the future in DLLs.
- We agreed to pass [a version range](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#dependencies). Examples:
    - the latest from the stable channel: `^37.0.0`
    - the latest of an alpha release: `^37.0.0-alpha.0`
    - the latest nightly release: ~`@nightly`~ `^0.0.0-nightly-20230425.0`
- Possible arguments:
    - a new version range (string)
    - a directory where to look for packages (string)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
The step for updating dependencies, located in `ckeditor5-dev-*`, should not be aware of which package belongs to the CKE5 ecosystem. Therefore, this util may receive an additional argument (a callback), in which we will pass the name of the dependency, and the callback will return information whether to update it.

**Comment by pomek** [comment]
Done in https://github.com/ckeditor/ckeditor5-dev/pull/871.
