### ISSUE TITLE
setData doesn't update editor and breaks other JS code

### ISSUE THREAD

**Issue by toxpal** [ckeditor/ckeditor5#1397]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

5.11.1.1 Classic

## 📋 Steps to reproduce

1. Call **editor.setData('somestring');** after creating editor

## ✅ Expected result
Textarea should contain 'somestring' now

## ❎ Actual result
Nothing is changed in textarea.
Remaining JavaScript code (if any) on page doesn't even execute.

## 📃 Other details that might be useful
Created test code right from documentation ( https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html ), without any modifications. It still fails.

JSFiddle here - https://jsfiddle.net/8ckdefta/

Tested with latest versions of Vivaldi and FireFox, setData function doesn't work (and breaks other JS code from working) in both browsers.

**Comment by Reinmar** [comment]
Tha's because the code from your JSFiddle is incorrect:

```js
ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
    
editor.setData( '<p>Some text.</p>' );
alert('ok');
```

There's no `editor` defined in the scope where you try to access it. It actually logs this out:

![image](https://user-images.githubusercontent.com/156149/49594724-ce748500-f976-11e8-944c-43b9342317c6.png)

You need to  move `editor.setData()` to where the `editor` is available. E.g. this:

```js
ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .then( editor => {
        console.log( editor );

        editor.setData( '<p>Some text.</p>' );

        alert('ok');
    } )
    .catch( error => {
        console.error( error );
    } );
    
```

**Comment by Reinmar** [comment]
Actually, the error says that `editor` is accessible. But that's not the editor that was created. It's the `#editor` element because (unfortunately) elements with `id` attributes are accessible in the global scope via their id name.

In other words, in the code above the `editor` equals:

* the `<div id=editor>` element,
* or the CKEditor 5 instance if you're in the `then()` callback.

**Comment by toxpal** [comment]
Thanks for the explanation, I was going crazy about this all day long.

So if I need to update CKeditor content after Ajax call (in other words, I need to set textarea's content to some string returned by Ajax), I'll need to terminate editor and then re-create it after Ajax call?

Because if I call only setData() after Ajax call, nothing will happen.

**Comment by Reinmar** [comment]
I'm sorry, but I don't understand your question. You cartainly don't have to destroy and recreate the editor. `editor.setData()` can be called whenever you need, but you need to have access to the `editor` variable. How you can access it depends on your app's logic – I can't help you with that.

**Comment by zamansarker** [comment]
What's the way to call editor.setData() otside the .then( editor => { } ) block?

**Comment by zamansarker** [comment]
> 
> 
> I'm sorry, but I don't understand your question. You cartainly don't have to destroy and recreate the editor. `editor.setData()` can be called whenever you need, but you need to have access to the `editor` variable. How you can access it depends on your app's logic – I can't help you with that.

I want to set data in my document editor several times based on condition. So, I need to call the function editor.setData() otside the .then( editor => { } ) block. How can I achieve this?

**Comment by scofalik** [comment]
Simply, store `editor` variable in some place you can reach later. For example

```js
ClassicEditor.create( ... ).then( editor => { window.editor = editor; } );

// ... Later ...

window.editor.setData( ... );
```

**Comment by zamansarker** [comment]
Thanks scofalik

**Comment by Tyler-Washington888** [comment]
How to prefill data in ckeditor?

**Comment by Woodehh** [comment]
> Simply, store `editor` variable in some place you can reach later. For example
> 
> ClassicEditor.create( ... ).then( editor => { window.editor = editor; } );
> 
> // ... Later ...
> 
> window.editor.setData( ... );

I've been searching for over ann hour. Thanks <3
