### ISSUE TITLE
Performance issue with setData and large content

### ISSUE THREAD

**Issue by code-chris** [ckeditor/ckeditor5#1398]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Current classic build (https://ckeditor.com/ckeditor-5/)

## 📋 Steps to reproduce

`editor.setData(...)` is very slow if called multiple times with a large document.
Use this gist for testing (anonymized real-world email) https://gist.github.com/code-chris/982dd128e5fe3eb58adaac5da947e0a1

1. Call `editor.setData(...)` with the above gist. This takes about 3-4 seconds.
2. Call `setData` again with the same content. This takes about 25-30 seconds.

Perf-dump when `setData` is directly called from the console
![image](https://user-images.githubusercontent.com/14875968/49722213-7c787b80-fc64-11e8-86ee-c8f270e2a9c0.png)

## ✅ Expected result
Calls with large contents are processed faster, even if there's already data in the editor.

## ❎ Actual result
All future-calls of the method are really slow and the browser hangs.

## 📃 Other details that might be useful
In our application this happens always if a user changes some data in the form (not only in the editor) and saves its changes. The save triggers a full data-reload which then calls `setData` again. This is maybe not ideal and we have to change this behavior in the future. However, the editor should not hang for about half a minute.

Maybe releated to #1041

**Comment by aschiffmann** [comment]
This jsfiddle reproduces the behavior: https://jsfiddle.net/Localhorstl/wjgm8xdr/

**Comment by oleq** [comment]
@code-chris @aschiffmann Thanks for the feedback! We're aware of some performance issues in the editor. We're tracking them all in https://github.com/ckeditor/ckeditor5-engine/issues/494. Please subscribe to stay updated.
