### ISSUE TITLE
How to use Autocomplete plugin of Classic Ck-Editor 5 in asp.net core mvc.

### ISSUE THREAD

**Issue by Ruman-Al** [ckeditor/ckeditor5#13981]
## 📝 Provide detailed reproduction steps (if any)

1. I have downloaded the Autocomplete plugin for classic editor 5 but don't have idea where i have to keep it after extraction.

### ✔️ Expected result

I want whenever I type @ in the editor then it will show the dropdown list.
<script>
        function createEditor(elementToReplace) {

            return ClassicEditor
                .create((elementToReplace),{
                plugins: [Mention],
                mention:{
                    feeds:[
                        {
                            marker:'@@',
                            feed:['Ruman','Daryl','Jitesh'],
                            minimumCharacters:1
                        }
                    ]
                }
                })
                .then(editor => {
                    editors.set(elementToReplace, editor);

                })
                .catch(err => console.error(err.stack));
        }
</script>
### ❌ Actual result

By applying the above js code i didn't get anything.

### ❓ Possible solution

I want after the ajax call the response i get from the controller to show in the editor to mention that person.
Like you can see in the Microsoft teams if you type @ then a dropdown list has open to mention the message that person.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
It's quite hard to help right now as we don't understand your full setup.
What is the installation method of the editor on your side (predefined build, npm, online builder, DLLs)? And how does your app handle js?

**Comment by Ruman-Al** [comment]
it's a .cshtml file in .net core mvc. I used @@ because single @ used for razor syntax.But it shows the error on plugins.

<script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>

<div class="card-body areacls cardBox" contenteditable="true" id="@areaId" data-href="@item.Id" onclick="createEditor(@areaId)">
                        @Html.Raw(item.Description)
</div>

<script>
    var editors = new Map();

        function createEditor(elementToReplace) {
            return ClassicEditor
                .create((elementToReplace),{
                plugins: [Mention],
                mention:{
                    feeds:[
                        {
                            marker:'@@',
                            feed:['@@Ruman','@@Daryl','@@Jitesh'],
                            minimumCharacters:1
                        }
                    ]
                }
                })
                .then(editor => {
                    editors.set(elementToReplace, editor);

                })
                .catch(err => console.error(err.stack));
        }
</script>

**Comment by Ruman-Al** [comment]
> It's quite hard to help right now as we don't understand your full setup. What is the installation method of the editor on your side (predefined build, npm, online builder, DLLs)? And how does your app handle js?

it's a .cshtml file in .net core mvc. I used @@ because single @ used for razor syntax.But it shows the error on plugins.

<script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>

 <div class="card-body areacls cardBox" contenteditable="true" id="@areaId" data-href="@item.Id" onclick="createEditor(@areaId)">
                        @Html.Raw(item.Description)
                    </div>

<script> 
var editors = new Map(); 

function createEditor(elementToReplace) { 
return ClassicEditor .create((elementToReplace),{
 plugins: [Mention], 
mention:{
 feeds:[ 
{ marker:'@@',
 feed:['@@ruman','@@daryl','@@jitesh']
, minimumCharacters:1 } 
]
 } 
}) 
.then(editor => { editors.set(elementToReplace, editor); })
 .catch(err => console.error(err.stack)); }
 </script>

**Comment by Witoso** [comment]
You are using a build from CDN. Mention [is not part of this build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#list-of-plugins-included-in-the-ckeditor-5-predefined-builds), if you want to use mentions change the build type to the superbuild, or create [your own custom build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html).

**Comment by Ruman-Al** [comment]
Hello,
I have download the ck classic editor and add the plugin to ckeditor .js.
I removed plugins: [ Mention ] from editor-create method.
and used both single @ and double @@.
you can seee in image in line 27.
![image](https://user-images.githubusercontent.com/131847160/234852625-28f3bbd1-31b5-4cb2-ba90-7c90afadde1a.png)
![image](https://user-images.githubusercontent.com/131847160/234852750-d5bfc3c2-48ca-4f46-ae17-f7f56adc9d5d.png)
![image](https://user-images.githubusercontent.com/131847160/234852922-1c40e0ab-0c85-446e-b26d-4a39f8cfacb0.png)

**Comment by Ruman-Al** [comment]
hey @Witoso check the above comment once.where I am wrong?

**Comment by Witoso** [comment]
I see that your IDE shows a problem with the line with Mention and import. Make sure that you installed packages with npm/yarn, and that you're building the editor with webpack (recommened builder).

**Comment by Witoso** [comment]
If you have a license with our support, please reach out to us via support channels. Otherwise, please make sure you follow one of the [custom build guides](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#introduction).

**Comment by Ruman-Al** [comment]
> @Mgsy I remember you mentioned something about the .NET guides, was there anything specific in the setup?
