### ISSUE TITLE
How to obtain all BlockQuote elements

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#13999]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_
I have some batch operations that require obtaining all BlockQuote elements. Then execute unwrap
Currently, only one operation can be selected.
Alternatively, convert editor. getData() to HTML for processing. Update data editor. setData() again

I hope to have an API that can retrieve elements like `document. querySelectorAll.`
For example:
editor.getElement("BlockQuote");

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by huzedong2015** [comment]
```javascript
function getElementByName(editor, name, rootName = "main") {
  const root = editor.model.document.getRoot(rootName);

  return root._children._nodes.filter((val) => val.name === name);
}

```

**Comment by arkflpc** [comment]
Actually, the code could be simpler.

```javascript
function* getElementsByName( editor, name, rootName = "main" ) {
  const root = editor.model.document.getRoot( rootName );

  // Create a range spanning the entire root.
  const range = editor.model.createRangeIn( root );

  for ( const value of range ) {
    if ( value.item.is( 'element', name ) ) {
      yield value.item;
    }
  }
}

```

**Comment by niegowski** [comment]
This could be simplified (no imports needed):

```js
function* getElementsByName( editor, name, rootName = "main" ) {
  const root = editor.model.document.getRoot( rootName );

  // Create a range spanning the entire root.
  const range = editor.model.createRangeIn( root );

  // range.getItems() is using TreeWalker.
  for ( const item of range.getItems() ) {
    if ( item.is( 'element', name ) ) {
      yield item;
    }
  }
}
```

**Comment by arkflpc** [comment]
@niegowski , race condition :smile: ?

**Comment by niegowski** [comment]
> @niegowski , race condition 😄 ?

:D 

both solutions are good with only slight difference in what the final loop is iterating, `TreeWalkerValue` or `Item`.
