### ISSUE TITLE
Is it possible to upgrade to the latest typedoc?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13992]
## Provide a description of the task

The latest _major_ of the `typedoc` package contains several breaking changes. See: https://github.com/TypeStrong/typedoc/releases/tag/v0.24.0.

I upgraded it locally to see if it crashed. Good news – it didn't. Bad news, docs are empty.

![image](https://user-images.githubusercontent.com/2270764/234853994-d621f124-d029-40e0-b9ac-41333c3d1883.png)

While processing API docs, the module validator reported screens of warnings.

```
./packages/ckeditor5-utils/src/dom/iscomment.ts:15:0 - [warning] Invalid module name: "packages/ckeditor5-utils/src/dom/iscomment"

15    export default function isComment( obj: any ): obj is Comment {

./packages/ckeditor5-utils/src/dom/isnode.ts:13:0 - [warning] Invalid module name: "packages/ckeditor5-utils/src/dom/isnode"

13    export default function isNode( obj: any ): obj is Node {
```

I checked the produced JSON output, and I am not happy…

```
{
	"id": 0,
	"name": "ckeditor5",
	"variant": "project",
	"kind": 1,
	"flags": {},
	"children": [
		{
			"id": 75958,
			"name": "collaboration-core/collaborationoperation",
			"variant": "declaration",
			"kind": 2,
			"flags": {},
			"comment": {
				"summary": [],
				"modifierTags": [
					"@publicApi"
				]
			},
			"children": [ 
			]
		}
	]
}
```

We do not have the modules' definitions. So, the entire parser we wrote in Umberto cannot process the output produced by typedoc.

**Comment by pomek** [comment]
As `kindString` no longer exists, we must compare `kind` against numeric constants from the `typedoc` package.

**Comment by psmyrek** [comment]
On `ck/13992-new-typedoc` branches there is experimental support for events:

<img src="https://github.com/ckeditor/ckeditor5/assets/56868128/36922fe3-5b0e-44b8-bfb8-dcf9a32d6bb4" width="650px">
