### ISSUE TITLE
Mention Plugin not working.

### ISSUE THREAD

**Issue by Ruman-Al** [ckeditor/ckeditor5#13993]
## 📝 Provide detailed reproduction steps (if any)

1. I download the classic ediotr 5.
I add the plugin to the ck-editor.js by simply writing the 
import Mention from '@ckeditor/ckeditor5-mention/src/mention;
you can see in image lino no 27
![image](https://user-images.githubusercontent.com/131847160/234854353-b86f7108-2357-408d-a2d1-ef3d70a423b5.png)
![image](https://user-images.githubusercontent.com/131847160/234854455-db8a60bd-fc2c-4462-a083-375c2eee371d.png)
I removed plugins: [ Mention ] from editor-create method.
and used both single @ and double @@.
![image](https://user-images.githubusercontent.com/131847160/234854729-7bd71379-8245-4293-ac11-085ed8c31dfc.png)

### ✔️ Expected result

I want whenever I type @ in the editor a dropdown will  be shown to select the names.

### ❌ Actual result

But when I type @ or @@ no one is working here.
I think there is error in the plugin tell me the whole process to add the plugin in Asp .net core mvc.
![image](https://user-images.githubusercontent.com/131847160/234855765-a0affc76-b0f6-4628-9699-7159b8ad641d.png)

### ❓ Possible solution

I want to see the dropdown list of names on writing of @.
Here I use @@ because single @ considered for razor syntax.
## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Please don't create duplicate issues. 
DUP: #13981
