### ISSUE TITLE
how can i insert html with styles in editor

### ISSUE THREAD

**Issue by daomiaru** [ckeditor/ckeditor5#14001]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by daomiaru** [comment]
i try to 
const content = '<p style="color: "red";">A paragraph with <a href="https://ckeditor.com">some link</a>.';
const viewFragment = editor.data.htmlProcessor.toView( content );
const modelFragment = editor.data.toModel( viewFragment );

editor.model.insertContent( modelFragment );

but style is gone,the text is not red,why?

**Comment by Reinmar** [comment]
The font color plugin won't upcast style on a block element. It will only grab inline content. So this one would need https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html

**Comment by Witoso** [comment]
You're right 🤦  For future reference, we mean that if your content has `<span style="color: red">Text</span>` the color will be properly upcasted to the model and shown. If styles are on the block, you need to enable [GHS](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html).
