### ISSUE TITLE
Insert table button is inaccessible

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#1400]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

## 📋 Steps to reproduce

1. Click "Insert table" button.

## ✅ Expected result

The grid for drawing a table should be presented in an alternative way for AT.

## ❎ Actual result

The grid is not presented at all.

## 📃 Other details that might be useful

The simplest solution would be to make the dimensions below the grid editable.

**Comment by oleq** [comment]
DUP of https://github.com/ckeditor/ckeditor5-table/issues/22, gentleman 😛
