### ISSUE TITLE
Add Custom Support in Automatic Text Transformation

### ISSUE THREAD

**Issue by parikshittestbook** [ckeditor/ckeditor5#14009]
If you'd like to see this improvement implemented, add a 👍 reaction to this post.
In Automatic Text Transformation, we can give user customisation feature. Suppose on that key I want to add an image , some predefined elements. Please if there is any way possible let me know. I am on deadline. @arkflpc @niegowski @mremiszewski @pomek @filipsobol

**Comment by Witoso** [comment]
Hi! Tagging team members will not necessarily speed up the process of fixing or doing something as this is a large project and we have a lot of issues and work in progress.

However, we do offer premium support for those who would like additional assistance. If you feel that you need more support, please don't hesitate to contact us.

Additionally, it would be great if you provide more details in your tickets if you're seeking an improvement. It's challenging to understand what you want to achieve without more information.
