### ISSUE TITLE
How to check which one option is selected from mention plugin drop-down in js.

### ISSUE THREAD

**Issue by Ruman-Al** [ckeditor/ckeditor5#14014]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_
I just want to know which one option is selected from mention plugin drop-down.
I want to send an email to the user selected from dropdown using js.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
One of the options is to [listen to events](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/event-system.html#listening-on-namespaced-events), for example, create a plugin that listens to the mention executions:

```js
    editor.commands.get( 'mention' ).on( 'execute', (eventInfo, data) => {
      console.log(eventInfo)
      console.log(data)
    })
```
