### ISSUE TITLE
Google Input tools Key board extension in chrome browser not working for CKEditor5

### ISSUE THREAD

**Issue by sree-ownprops** [ckeditor/ckeditor5#14011]
## 📝 Provide detailed reproduction steps (if any)

1. I have google input tools Chrome browser extension. This extension I was using to enter different language content for my website. Older CKEditor versions are supporting this way of content editing. Recently upgraded ckEditor5 Decoupled Editor. Now content from Google Input tool extension not appearing in the ckEditor.

### ✔️ Expected result

Other language content entered through Google input tools extension should appear in the ckEditor.

### ❌ Actual result

No content typed through Input tools extension appears

**Comment by Witoso** [comment]
@ckeditor/qa-team could you confirm this regression?

**Comment by niegowski** [comment]
This looks like a DUP of https://github.com/ckeditor/ckeditor5/issues/13234.

**Comment by Witoso** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/13234.
