### ISSUE TITLE
Feature look

### ISSUE THREAD

**Issue by parikshittestbook** [ckeditor/ckeditor5#14010]
I'd like to use a feature where whenever I input some "backsash+predefined_text" and push the spacebar, it checks to see if there is a value for predefined text and replaces it with plain text or a combination of image and text. 
for example "\testbook " it will replace it with <div.> <img. src="testbook_logo"><p.> Testbook </p.>. "

**Comment by Witoso** [comment]
We released this feature recently (slash commands). You can play with it [in the documentation](https://ckeditor.com/docs/ckeditor5/latest/features/slash-commands.html). This premium feature is a part of the Productivity Pack available only for customers with a commercial license. [Contact us](https://ckeditor.com/contact/?sales=true#contact-form) for more details.
