### ISSUE TITLE
Multiple mentions in the last table cell results in a selection error 

### ISSUE THREAD

**Issue by MichaelHeydon** [ckeditor/ckeditor5#14025]
## 📝 Provide detailed reproduction steps (if any)

1. Visit https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html
2. In the first Demo, remove _Hello @Ted._
3. Create a table with a single cell
4. Add two mentions 
5. Add a new line so the editor looks like:
![screenshot-ckeditor com-2023 05 04-10_23_48](https://user-images.githubusercontent.com/74880856/236078993-e061311f-fa14-4dc6-95d9-7d8932dd11ba.png)
6. Attempt to select the table by pressing backspace.
7. The following error is logged in the console:
![mention-error](https://user-images.githubusercontent.com/74880856/236079231-8162607f-841c-422e-8ffd-d134d57f872e.png)
```
snippet.js:4 Uncaught CKEditorError: model-nodelist-offset-out-of-bounds {"offset":6,"nodeList":[{"name":"table","children":[{"name":"tableRow","children":[{"name":"tableCell","children":[{"name":"paragraph","children":[{"attributes":{"mention":{"uid":"e4dc38be825796bd7007c8c3f16e9ba63","_text":"@Ted","id":"@Ted","text":"@Ted"}},"data":"@Ted"},{"data":"  "},{"attributes":{"mention":{"uid":"e6f4dc4a2dde9a5bfed0aa66b11e6f9dc","_text":"@Barney","id":"@Barney","text":"@Barney"}},"data":"@Barney"},{"data":" "}]}]}]}]}]}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
    at ol.offsetToIndex (snippet.js:4:153446)
    at Eh.offsetToIndex (snippet.js:4:156105)
    at ul (snippet.js:4:166656)
    at get nodeAfter [as nodeAfter] (snippet.js:4:161159)
    at snippet.js:4:441773
    at fm.<anonymous> (snippet.js:4:441834)
    at fm.fire (snippet.js:4:5541)
    at fm._evaluateTextBeforeSelection (snippet.js:4:432441)
    at Ph.<anonymous> (snippet.js:4:432049)
    at Ph.fire (snippet.js:4:5541)
```

### ✔️ Expected result
I can continue to select / manipulate the table. 

### ❌ Actual result

The above error occurs. In this scenario the table can still be selected with the mouse, however in our setup that led to this bug report, the editor becomes entirely unusable.  

The issue does not occur when: 
- Having one mention in the table cell 
- Having a column to the right 
- Having a row below 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This most probably should be fixed by replacing this:

https://github.com/ckeditor/ckeditor5/blob/ce9b09c631bbdd8afe304573f1e9ef5dd94fc1d4/packages/ckeditor5-typing/src/utils/getlasttextline.ts#L42-L51

with:

```javascript
const text = Array.from( range.getWalker( { ignoreElementEnd: false } ) ).reduce( ( rangeText, { item } ) => {
	// Trim text to a last occurrence of an inline element and update range start.
	if ( !( item.is( '$text' ) || item.is( '$textProxy' ) ) ) {
		start = model.createPositionAfter( item );

		return '';
	}

	return rangeText + item.data;
}, '' );
```
