### ISSUE TITLE
editor pulldown menus are left aligned even when editor language is set to a rtl value

### ISSUE THREAD

**Issue by githubalbumman** [ckeditor/ckeditor5#14023]
I don't see this being tracked anywhere so note that when ckeditor5 language is set to a rtl language, the pulldown lists from the toolbar are still being incorrectly left aligned.  

https://github.com/ckeditor/ckeditor5/issues/1151 seems to indicate this was fixed, but if you look at your own example https://ckeditor.com/ckeditor-5/demo/internationalization/ the pulldown menus in the arabic example are still left aligned, as are the font picker, font size pulldown, and pretty much every pulldown when added to an editor.
### ✔️ Expected result

When editor is set to a rtl language, the menus are supposed to be right aligned.

### ❌ Actual result

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
DUP: #10416
