### ISSUE TITLE
styles gets removed when inserting html using insert content

### ISSUE THREAD

**Issue by parikshittestbook** [ckeditor/ckeditor5#14030]
const _data = x[mtext]
                    const content = `<span style="display: flex; gap: 6px; align-items: center;"><img src="${_data.imageProps.source}" height="${_data.imageProps.height}" width="${_data.imageProps.width}""></span><strong><span style="font-size:${_data.textProps.fontSize}; vertical-align:'middle';"> "${_data.textProps.text}" </span></strong>`; 
                    const viewFragment = editor.data.processor.toView( content );
                    const modelFragment = editor.data.toModel( viewFragment );
                    model.insertContent( modelFragment ,range);
     
                    
                    

### ✔️ Expected result

it should insert content with styles

### ❌ Actual result

all styles are removed

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by anubhavmalik** [comment]
Hey, @parikshittestbook did you find a solution to this?
