### ISSUE TITLE
[Experimental] Drag and Drop of blocks

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14033]
We aim to have a working experimental feature/plugin/configuration flag that we could test. It's an MVP, this would be a starting point for future capabilities with a limited scope.

### Use cases

As a user of the **Balloon block editor**, when I select a block e.g. a paragraph, image, or table, I can drag it, and place it between other blocks.

### Out of scope

* Hover to pick the block - due to complexity we decided that we will stay with select.
* Working on all editors, now we will focus on the Balloon block editor.
* Moving the mouse outside of the editable (e.g. left side).

### Scope

1. Finding the block to move:
    1. Showing the d&d action
        1. the icon should show on selecting the block(s) (as now).
        2. placement of the icon will be configurable via CSS (as now).
    2. D&D of multiple selected blocks
        1. the icon shows near the first of the selected blocks (as now).
2. When I hover over the icon, the hand appears.
    1. Actions - on click: open toolbar, hold: d&d.
    2. Change the tooltip’s text to mention "open toolbar" and "drag and drop" actions.
3. The logic of the drag & drop:
    1. if an inline element is selected, possible drop locations:
        1. between blocks,
        2. inline.
    2. if one block or multiple block elements are selected, possible drop locations:
        1. between blocks
4. Visual indication (blue line) appears where the block will be placed for the before/after placements possibility.
    1. as you move the cursor the dimmed block/element should move with the mouse (default browser's behavior).
    2. the blue line appears between blocks (MVP: it's possible that it will be on some elements like floated images)
    3. the placement of the line logic should be applied, see **Moving** ([internal Miro](https://miro.com/app/board/uXjVMWG-W7M=/?moveToWidget=3458764551341037627&cot=14)). For example, if I'm moving the cursor in the first half of the multiline block, it should suggest above the block placement. If the lower half, show below the block placement.
5. Enabling the block d&d.
6. Maturity of pilcrow handling.
7. On scrolling behavior (line adapts).

### Other thoughts

* blue line’s height should be as the width of the current drag and drop cursor.
* showing line with position absolute? (ref: pagination, magic line CKE4). Other CSS may cause layout shifts.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@niegowski could you update the TBD section on decisions we need to make?

**Comment by wimleers** [comment]
Videos/GIFs here would be _really_ valuable 😇 🤓

**Comment by Witoso** [comment]
@wimleers here you go!

https://user-images.githubusercontent.com/9881379/236452449-95df5e46-f845-4dd0-9391-8d5b74a2379a.mov
