### ISSUE TITLE
Semantic Versioning Issue: Caret Transitive Dependencies May Raise `ckeditor-duplicated-modules`

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#14046]
## 📝 Provide detailed reproduction steps (if any)

As reproduction step, it is important, that you have set a specific (fixed) CKEditor 5 version in your project setup, such as `37.0.1`, while a newer minor version (here: `37.1.0`) is already available.

**Motivation:** Thus, we don't rely on "^37.0.1" (as it ships via Online Builder, for example), but always use "37.1.0" in our dependency management, as our experience was, that we struggled with `ckeditor-duplicated-modules` prior to that a lot. This especially happens, when you add a new plugin, which on `(p)npm install` suddenly gets the new version `37.1.0`, while all others are at `37.0.1`.

### ✔️ Expected result

If setting all directly used dependencies of CKEditor 5 artifacts to `37.0.1`, only CKEditor 5 dependencies at version `37.0.1` are installed.

### ❌ Actual result

We again and again get artifacts of mixed versions, which is, so our assumption due to transitive dependencies all set to caret-version. Such as `ckeditor5-alignment` at `37.0.1` as a dependency on `ckeditor5` with version `^37.0.1`.

### ❓ Possible solution

Our solution is pretty awkward: We scan through the dependencies and add all, even transitive ones, at the exact version that we require.

We think, that CKEditor 5 dependencies, but also results of the online-builder should always only set fixed versions and never use the caret. This is because, while it may work theoretically to have `ckeditor5-alignment` at version `37.0.1` while `ckeditor5-link` is at `37.1.0` CKEditor 5 will complain at runtime, that they don't match.

Thus, your own policy requires that no versions shall ever be mixed - and thus, transitive dependencies should always set the version explicitly.

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: 37.0.1 (currently under test, soon updating to 37.1.0, where the issue would vanish)
* Installed CKEditor plugins: Alignment, for example; also custom ones, which again come with transitive dependencies (but only as peers)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks, @mmichaelis! Have we ever thought about pinning to a specific version @pomek @Reinmar?

**Comment by Reinmar** [comment]
Interestingly @arkflpc, brought up recently this:

> TBD: Remove `^` from `eslint-config-ckeditor5` dependency (because backward-incompatible rule breaks `stable`).

My response to this was this:

> If the rule is backward-incompatible - it should not be released as a patch. It wouldn't be installed then.

But from a pragmatic pov, if we had it locked to a specific version, it wouldn't affect `stable`. It'd be more predictable.

So, I already talked f2f with @pomek that we'll need to decide which dependencies we want to change lock on specific versions. Only the ones to let's say "client-side" code. Or environment-related dependencies too?

**Comment by pomek** [comment]
All CKEditor 5 dependencies will require a strict version starting from the upcoming release. We will need an exact version (`X.Y.Z`) instead of caret ranges (`^X.Y.Z`, `~X.Y.Z`, or even `>=X.Y.Z`).

The question remains – should the upcoming release be marked as a major bump due this versioning change

**Comment by mmichaelis** [comment]
> The question remains – should the upcoming release be marked as a major bump due to this versioning change

Although my input may not be relevant here, some thoughts on this:

* [Versioning policy - CKEditor 5 Documentation](https://ckeditor.com/docs/ckeditor5/37.1.0/updating/versioning-policy.html)
Does not really cover this use-case (it may require some enhancement here?)

For us (as custom plugin provider as well as integration into our rich-web-application), it means, that we may but don't need to adapt our `package.json`, as we were forced to hard-wire also transitive dependencies. But we should do it, to get rid of additional overhead in `package.json`. Thus, gut feeling is at least minor, not necessarily major release.

The main question would be, if it is expected to make any build fail, thus, requires action for developers.

**Comment by Reinmar** [comment]
> *   [Versioning policy - CKEditor 5 Documentation](https://ckeditor.com/docs/ckeditor5/37.1.0/updating/versioning-policy.html)  
>     Does not really cover this use-case (it may require some enhancement here?)

I'd say it falls under:

> **The integration layer.** This is the most commonly used API which is used to integrate and customize existing builds or editors built from source. It also includes their setup (whose features are included and their default configuration).

It's not mentioned explicitly, so this could be indeed added, but how dependencies are installed is the first layer of the integration layer :)

**Comment by pomek** [comment]
Starting from the latest published release (https://github.com/ckeditor/ckeditor5/releases/tag/v38.1.0), CKEditor 5 packages do not use caret ranges when defining their dependencies.

<img width="441" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/2270764/6ef04fa8-fa02-463c-985b-426ac0afeb53">
