### ISSUE TITLE
Applying code styles in a specific order doesn’t have effect

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#14042]
## 📝 Provide detailed reproduction steps (if any)

1.  Visit [`http://localhost:8125/ckeditor5-style/tests/manual/styledropdown.html`](http://localhost:8125/ckeditor5-style/tests/manual/styledropdown.html).
2.  Put the caret inside the code block. 
3.  Apply the Code (bright) style from the styles dropdown.
4.  Apply the Code (dark) style from the styles dropdown.

### ✔️ Expected result

The Code (dark) style is applied:

![](https://user-images.githubusercontent.com/132071257/236421252-b3e3862a-1e59-46be-a67d-3a74f0bce632.png)

### ❌ Actual result

Applying the Code (dark) style has no effect:

![](https://user-images.githubusercontent.com/132071257/236425102-9494eeda-f74d-45b2-aefe-14bf6f179f49.gif)

## 📃 Other details

*   The behaviour is different when applied in the reverse order - when choosing first Code (dark) and Code (bright) second, the style changes to Code (bright).
*   It can be reproduced in all common browsers.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Most likely related to #11748.
@charlttsie could you paste your style config?

**Comment by Witoso** [comment]
@charlttsie, this is not a bug, although it's a very confusing UX 😓. 

You applied two styles (both are selected) that style the same thing. Therefore, one is taking precedence (probably class order, etc.). We don't plan to introduce conflicting styles that toggle off each other (too complex for now).

Thanks for the report!
