### ISSUE TITLE
Need help on remove event

### ISSUE THREAD

**Issue by pranavmappoli** [ckeditor/ckeditor5#14053]
As a part of project development, i have created a custom  plugin as show in the image. I can add the object with class "placeholder". `<span class="placeholder">Loop-ANS(Q2)</span>` . Now when someone remove this from the editor i need to generate an event (call a function) so that i can mark this item has removed in some state. Could you please let me know what change i have to do for this ?
<img width="661" alt="Screenshot 2023-05-08 at 11 27 43 AM" src="https://user-images.githubusercontent.com/25036043/236745436-b436fb9e-e0ef-412f-8cb2-9128952fc5f6.png">

inline widget created from
 [Created from](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html)

**Comment by Witoso** [comment]
Hey!

The best way would probably be to observe [the graveyard root](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#member-graveyard) and its changes. Here's an example that listens to removals of inline images:

```js
editor.model.document.on( 'change:data', () => {  // Listen to all changes in model.
	// Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
	const changes = editor.model.document.differ.getChanges( { includeChangesInGraveyard: true } );

	for ( const change of changes ) {
		// Check items moved to the graveyard (so they are removed from the document root).
		if ( change.type == 'insert' && change.name != '$text' && change.position.root.rootName == '$graveyard' ) {

			// The element that we are looking for could be nested in some block-quote or a table cell
			// so we need to walk through the whole element content and check if our element was removed or not.
			const range = editor.model.createRangeOn( change.position.nodeAfter );

			for ( const item of range.getItems() ) {
				if ( item.is( 'element', 'imageInline' ) ) { // Here you change the value to your element's name.
					console.log( 'inline image removed', item );
				}
			}
		}
	}
} );
```

We will think how to include it to the docs.

**Comment by Witoso** [comment]
Thanks @niegowski for help!

**Comment by pranavmappoli** [comment]
I have seen this code in some post
```
      const myEvent = new Event("my-custom-event");
      document.dispatchEvent(myEvent);
```
But not sure i can use this

**Comment by Witoso** [comment]
> How we can pass a callback function to component and call it inside your code. ?

Do you use some kind of a react setup? You can pass a function that behaves like a plugin to the plugins list of the editor.
```js
function myPlugin(editor) {
    // your logic
}

<CKEditor
    editor={ClassicEditor}
    config={{
        plugins: [myPlugin, ...otherPlugins], // <- added here.
        toolbar: ['bold','italic']
    }}
    // other config
/>
```

Or create your own plugin but this is gonna be an object, not a function.

> Is there anyway to block the deletion of this Inline item (ie: user cant delete the item once it added) ?

Maybe watching [the delete event makes sense](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/event-system.html#listening-to-bubbling-events). WDYT @niegowski, is there some more proper way? 
```js
function watchDelete(editor: Editor) {
  editor.listenTo(
    editor.editing.view.document,
    "delete",
    (evt, data) => {
      // Execute the logic and stop the event.
      evt.stop()
    }, {context: "$text"} // Set the context to your widget.
  );
}
```

> how we can handle cntrl+z ? , is there any same way to detect if the placeholder come back and call another callback?

Not sure I understand this scenario.

**Comment by pranavmappoli** [comment]
> ```js
> Do you use some kind of a react setup? You can pass a function that behaves like a plugin to the plugins list of the editor.> ```

**Comment by Witoso** [comment]
I think there may be several methods here. But I think the easiest is that you add this functionality to your plugin and if you have any external code, you just import it. So no need to pass the function around as you operate on event listeners mostly.

**Comment by pranavmappoli** [comment]
@Witoso I added this in my plugin only. Still once i get the deleted placeholders, i need to send back to my ui components right ?. Is there any example that is useful in this scenario.

**Comment by Witoso** [comment]
Not sure I understand, do you mean some UI components outside the editor?

**Comment by pranavmappoli** [comment]
```
function myPlugin(editor) {
    // your logic
}

<CKEditor
    editor={ClassicEditor}
    config={{
        plugins: [myPlugin, ...otherPlugins], // <- added here.
        toolbar: ['bold','italic']
    }}
    // other config
/>
```

Suppose if i pass the myPlugin function like this, how i can use this fuction inside my custom plugin. Is there any alternative way to pass callback function other than this.?

**Comment by Witoso** [comment]
Hey, sorry for the late reply!

I think the best way if you already have your own plugin is to include the additional logic in this plugin, and not pass this plugin-function. Just centralize the whole logic in one Plugin, or multiple plugins just as our tutorials show: one plugin for editing, one for command, etc.

**Comment by pranavmappoli** [comment]
@Witoso Is there any way to get the key pressed in the event object ?. I need to check wether user clicked Enter
```
editor.model.document.on( 'change:data', (ev) => {
//need to get which key pressed 
})
```

**Comment by pranavmappoli** [comment]
Whenever i add some add a new placeholder span like this,

```
const taggedQuestion = `<p> ${prevQuestion} <span class="placeholder">Loop-ans-(2)</span></p>`;
```
all the existing placeholders are moved to graveyard root, and triggering the function you provided above. Is there any other way we can add the tagging like this and prevent existing placeholder to move to graveyard?

**Comment by Witoso** [comment]
> @Witoso Is there any way to get the key pressed in the event object ?. I need to check wether user clicked Enter

Depends on what you want to achieve. The event you mentioned is too late to get the key that was pressed. [Here's an example how to listen to enter ](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/event-system.html#listening-to-bubbling-events).

> Is there any other way we can add the tagging like this and prevent existing placeholder to move to graveyard?

Unfortunately, we don't have an API for placeholders right now. If you replace the content, it's gonna land in the graveyard. I will think if there's any other way to prevent it but why do you want to keep it out of the graveyard?

**Comment by pranavmappoli** [comment]
@Witoso basically, when someone add this placeholder, i'm setting some state variable in react indicating placeholder has added. So when someone delete this placeholder, i need to change the state back (state contain count of placeholder). Thats why i have asked the functionality for track which all placeholder removed.

Now the issue is, whenever i add a new placeholder (replace the text), the old getting removed, which will trigger the event change the state variable (count will reduce).

**Comment by pranavmappoli** [comment]
```
function myPlugin(editor) {
    // your logic
}

<CKEditor
    editor={ClassicEditor}
    config={{
        plugins: [myPlugin, ...otherPlugins], // <- added here.
        toolbar: ['bold','italic']
    }}
    // other config
/>
```

I have tried this methoad, create a plugin from application and pass to ckEditor. When i do this, i'm getting the error
```
CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
```
But, when i created this plugin and added in the custom build like below, it worked without any issue.

```
class Editor extends ClassicEditor {}
  // Plugins to include in the build.
Editor.builtinPlugins = [
  Alignment,
  Bold,
  List,
  Essentials,
  FontSize,
  Italic,
  Link,
  Paragraph,
  RemoveFormat,
  Underline,
  Placeholder,
  CustomEventsHandlers
];
```

My placeholder widget:
import Plugin from "@ckeditor/ckeditor5-core/src/plugin";
import {
  toWidget,
  viewToModelPositionOutsideModelElement,
} from "@ckeditor/ckeditor5-widget/src/utils";
import Widget from "@ckeditor/ckeditor5-widget/src/widget";

import "./theme/placeholderWidget.css";

export default class PlaceholderWidgetEditing extends Plugin {
  static get requires() {
    return [Widget];
  }

  init() {
    this._defineSchema();
    this._defineConverters();
    this.editor.editing.mapper.on(
      "viewToModelPosition",
      viewToModelPositionOutsideModelElement(this.editor.model, (viewElement) =>
        viewElement.hasClass("placeholder")
      )
    );
  }

  _defineSchema() {
    const schema = this.editor.model.schema;

    schema.register("placeholder", {
      // Allow wherever text is allowed:
      allowWhere: "$text",

      // The placeholder will act as an inline node:
      isInline: true,

      // The inline widget is self-contained so it cannot be split by the caret and can be selected:
      isObject: true,

      // The inline widget can have the same attributes as text (for example linkHref, bold).
      allowAttributesOf: "$text",

      // The external data widget can have many attributes
      allowAttributes: ["name"],
    });
  }

  _defineConverters() {
    const conversion = this.editor.conversion;

    conversion.for("upcast").elementToElement({
      view: {
        name: "span",
        classes: ["placeholder"],
      },
      model: (viewElement, { writer: modelWriter }) => {
        const text = viewElement.getChild(0).data;
        return modelWriter.createElement("placeholder", { name: text });
      },
    });

    // upcast
    // <span class="placeholder">abc</span> -> <placeholder name="abc"></placeholder>

    // downcast
    // <placeholder name="abc"></placeholder> -> <span class="placeholder">abc</span>

    conversion.for("editingDowncast").elementToElement({
      model: "placeholder",
      view: (modelItem, { writer: viewWriter }) => {
        const widgetElement = createPlaceholderView(modelItem, viewWriter);

        // Enable widget handling on a placeholder element inside the editing view.
        return toWidget(widgetElement, viewWriter);
      },
    });

    conversion.for("dataDowncast").elementToElement({
      model: "placeholder",
      view: (modelItem, { writer: viewWriter }) =>
        createPlaceholderView(modelItem, viewWriter),
    });

    // Helper method for both downcast converters.
    function createPlaceholderView(modelItem, viewWriter) {
      const name = modelItem.getAttribute("name");

      const placeholderView = viewWriter.createContainerElement("span", {
        class: "placeholder",
      });

      // Insert the placeholder name (as a text).
      const innerText = viewWriter.createText(name + "");
      viewWriter.insert(
        viewWriter.createPositionAt(placeholderView, 0),
        innerText
      );

      return placeholderView;
    }
  }
}

```

**Comment by pranavmappoli** [comment]
@Witoso I'm passing the plugin to custom build only. There is no way to pass a plugin like this to custom build ?.  

```
import {
  toWidget,
  viewToModelPositionOutsideModelElement,
} from "@ckeditor/ckeditor5-widget/src/utils";
```

this import make thud dependencies issue, Is there any alternative way i can fullfill this function requirement?

**Comment by pranavmappoli** [comment]
@Witoso I have resolved the dependency issue. Thanks a lot for your help.

`Unfortunately, we don't have an API for placeholders right now. If you replace the content, it's gonna land in the graveyard. I will think if there's any other way to prevent it but why do you want to keep it out of the graveyard?`

regarding this, is there any other way i can add this text `<span class="placeholder">Loop-ANS(Q2)</span>` to the existing content without replacing?. If so, all the previous placeholders that existing in text wont goto graveyard .

**Comment by pranavmappoli** [comment]
If anyone need this in later stage. use `editor.execute( 'placeholder', { value: 'time' } );` to create a placeholder. so it wont goto grevyard. you can get the 'editor' value on init methoad. Read more in [
](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/using-react-in-a-widget.html)

**Comment by pranavmappoli** [comment]
@Witoso 

when i use this code

```
editor.model.document.on( 'change:data', () => {  // Listen to all changes in model.
	// Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
	const changes = editor.model.document.differ.getChanges( { includeChangesInGraveyard: true } );

	for ( const change of changes ) {
		// Check items moved to the graveyard (so they are removed from the document root).
		if ( change.type == 'insert' && change.name != '$text' && change.position.root.rootName == '$graveyard' ) {

			// The element that we are looking for could be nested in some block-quote or a table cell
			// so we need to walk through the whole element content and check if our element was removed or not.
			const range = editor.model.createRangeOn( change.position.nodeAfter );

			for ( const item of range.getItems() ) {
				if ( item.is( 'element', 'imageInline' ) ) { // Here you change the value to your element's name.
					console.log( 'inline image removed', item ); // Here you execute your logic.
				}
			}
		}
	}
} );
```
when i try to change the pposition placeholder using drag and drop, then also it come as removed element. Is there any fix available for this?

**Comment by Witoso** [comment]
The problem you're experiencing happens because when you drag and drop a node, it is technically removed from its initial position and reinserted at the new location. The model does not distinguish between deletion and moving of nodes; both are treated as two operations - remove from the old position and insert at the new one.

I'm a bit cautious to offer some proposals here. It fills a bit like hacking, so I leave it up to you to decide if you can handle it this way, as you know your context best.

**Brute force**, you can work around this by checking if the moved element reappears in the document after the 'change:data' event is triggered. This can be done by waiting for the next JavaScript event loop cycle, allowing the model to finish all its current operations (including the reinsertion of the dragged and dropped element) before checking for its existence.

```javascript
editor.model.document.on( 'change:data', () => {
    // Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
    const changes = editor.model.document.differ.getChanges( { includeChangesInGraveyard: true } );
    
    const removedElements = [];

    for ( const change of changes ) {
        // Check items moved to the graveyard (so they are removed from the document root).
        if ( change.type == 'insert' && change.name != '$text' && change.position.root.rootName == '$graveyard' ) {
            // The element that we are looking for could be nested in some block-quote or a table cell
            // so we need to walk through the whole element content and check if our element was removed or not.
            const range = editor.model.createRangeOn( change.position.nodeAfter );

            for ( const item of range.getItems() ) {
                if ( item.is( 'element', 'imageInline' ) ) { // Here you change the value to your element's name.
                    removedElements.push(item);
                }
            }
        }
    }

    // Wait for the next event loop cycle to check if the removed elements are reinserted.
    setTimeout(() => {
        for (const element of removedElements) {
            // Check if the element is in the root again (not removed permanently)
            if (!editor.model.document.getRoot().contains(element)) {
                console.log('inline image removed', element); // Here you execute your logic.
            }
        }
    }, 0);
});
```

**Comment by pranavmappoli** [comment]
I have tried to implement the logic as you suggested. But it giving the error, 
`Uncaught TypeError: editor.model.document.getRoot(...).contains is not a function`


Complete Code
```
function pipingDeletionChecker(editor, questionId, callback) {
  let model = editor.model;
  let removedPlaceHolders = [];
  model.document.on("change:data", () => {
    // Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
    const changes = editor.model.document.differ.getChanges({
      includeChangesInGraveyard: true,
    });
    let removedItems = [];
    for (const change of changes) {
      // Check items moved to the graveyard (so they are removed from the document root).
      if (
        change.type == "insert" &&
        change.name != "$text" &&
        change.position.root.rootName == "$graveyard"
      ) {
        // The element that we are looking for could be nested in some block-quote or a table cell
        // so we need to walk through the whole element content and check if our element was removed or not.
        const range = editor.model.createRangeOn(change.position.nodeAfter);
        for (const item of range.getItems()) {
          if (item.is("element", "placeholder")) {
            removedItems.push(item);
          }
        }
      }
    }
    // Wait for the next event loop cycle to check if the removed elements are reinserted.
    setTimeout(() => {
      const removedPipings = [];
      for (const element of removedItems) {
        // Check if the element is in the root again (not removed permanently)
        if (!editor.model.document.getRoot().contains(element)) {
          window.console.log("inline image removed", element);
          removedPipings.push(element);
          // Here you execute your logic.
        }
      }
      removedPlaceHolders = removedPipings.map((item) =>
        item._attrs.get("name")
      );
      if (removedPlaceHolders.length) {
        window.console.log(removedPlaceHolders);
        callback(questionId, removedPlaceHolders); 
      }
    }, 0);
  });
}

export default pipingDeletionChecker;
```

**Comment by Witoso** [comment]
Sorry, forgot that we are not implementing contains. In this case, you will need to iterate through children of the Root. [TreeWalker](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_treewalker-TreeWalker.html) may be used here.

Side note if you're worried about the `setTimeout`, check how we solved similar problems [for the image upload](https://github.com/ckeditor/ckeditor5/blob/f7772b42581874c57bf8da906ae5e9e9331994c0/packages/ckeditor5-image/src/imageupload/imageuploadediting.ts#L172-L225).

**Comment by pranavmappoli** [comment]
@Witoso Not sure how i can reuse the logic in image upload here. Can you through some insights on this.
Is there any code snippet available to see, how we can use the TreeWalker.

**Comment by pranavmappoli** [comment]
I have used a different method for this scenario. Hope this works for all cases

```
function _getPlaceholderChanges(editor, inGraveyard) {
  const changes = editor.model.document.differ.getChanges({
    includeChangesInGraveyard: inGraveyard,
  });
  let changedItems = [];
  for (const change of changes) {
    if (
      inGraveyard
        ? change.type == "insert" &&
          change.name != "$text" &&
          change.position.root.rootName == "$graveyard"
        : change.type == "insert" && change.name != "$text"
    ) {
      const range = editor.model.createRangeOn(change.position.nodeAfter);
      for (const item of range.getItems()) {
        if (item.is("element", "placeholder")) {
          changedItems.push(item);
        }
      }
    }
  }
  const changedPlaceholders = changedItems.map((item) =>
    item._attrs.get("name")
  );
  return changedPlaceholders;
}

function pipingDeletionChecker(editor, questionId, callback) {
  const model = editor.model;
  model.document.on("change:data", () => {
    // Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
    const removedPlaceHolders = _getPlaceholderChanges(editor, true);
    const addedPlaceHolders = _getPlaceholderChanges(editor, false);

    //if a placeholder deleted and added on same time means, this is happend due to reposition of item (drag and drop).
    //In this case we wont call the callback
    if (removedPlaceHolders.length && !addedPlaceHolders.length) {
      callback(questionId, removedPlaceHolders);
    }
  });
}

export default pipingDeletionChecker;

```

**Comment by pranavmappoli** [comment]
@Witoso Thank you somuch for your time and efforts. Your ideas and code snippets helped me a lot to arrive the final solution. :)

**Comment by huzedong2015** [comment]
> Hey!
> 
> The best way would probably be to observe [the graveyard root](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#member-graveyard) and its changes. Here's an example that listens to removals of inline images:
> 
> ```js
> editor.model.document.on( 'change:data', () => {  // Listen to all changes in model.
> 	// Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
> 	const changes = editor.model.document.differ.getChanges( { includeChangesInGraveyard: true } );
> 
> 	for ( const change of changes ) {
> 		// Check items moved to the graveyard (so they are removed from the document root).
> 		if ( change.type == 'insert' && change.name != '$text' && change.position.root.rootName == '$graveyard' ) {
> 
> 			// The element that we are looking for could be nested in some block-quote or a table cell
> 			// so we need to walk through the whole element content and check if our element was removed or not.
> 			const range = editor.model.createRangeOn( change.position.nodeAfter );
> 
> 			for ( const item of range.getItems() ) {
> 				if ( item.is( 'element', 'imageInline' ) ) { // Here you change the value to your element's name.
> 					console.log( 'inline image removed', item ); // Here you execute your logic.
> 				}
> 			}
> 		}
> 	}
> } );
> ```
> 
> We will think how to include it to the docs.

Enable tracking changes, e.stop() is invalid
