### ISSUE TITLE
"t is null" when trying to delete first bullet

### ISSUE THREAD

**Issue by alexc-pub6** [ckeditor/ckeditor5#14050]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-5/demo/feature-rich/
2. Press the bullet point button
3. Click onto bullet point
4. Press delete
5. Nothing happens, observe console error

### ✔️ Expected result
Bullet gets deleted

### ❌ Actual result

Bullet doesn't get deleted and console error

### ❓ Possible solution
No idea

## 📃 Other details

* Browser: Firefox
* OS: Windows 10
* First affected CKEditor version: CKEditor Website
* Installed CKEditor plugins: Default

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
WFM just fine. Could you record a screencast maybe? Maybe I don't understand the exact steps.

**Comment by Reinmar** [comment]
Also, you can try to disable browser addons if you have any.

**Comment by johanneswilm** [comment]
Is this a bug in Firefox? If so, has it been filed with Firefox?

**Comment by arkflpc** [comment]
> Is this a bug in Firefox? If so, has it been filed with Firefox?

cc: @niegowski

**Comment by niegowski** [comment]
> > Is this a bug in Firefox? If so, has it been filed with Firefox?

https://github.com/ckeditor/ckeditor5/issues/14411#issuecomment-1772068736

https://bugzilla.mozilla.org/show_bug.cgi?id=1860210
