### ISSUE TITLE
Cannot disable uploadImage button in the toolbar

### ISSUE THREAD

**Issue by RM6SS62** [ckeditor/ckeditor5#14051]
## 📝 Provide detailed reproduction steps (if any)

```
editor.ui.view.toolbar.items.get(14).isEnabled = false; 
```
The code above disables the dropdown at the right (insertImage which I want to keep), then I set the index 13, and it disables the separator at the left. Basically the uploadImage button is being ignored.

### ✔️ Expected result

To get this specific button disabled

### ❌ Actual result

The button is not being targeted

**Comment by Reinmar** [comment]
The state of the button is bound to the state of the command:

[https://github.com/ckeditor/ckeditor5/blob/ce9b09c631bbdd8afe304573f1e9ef5dd94fc1d4/packages/ckeditor5-image/src/imageupload/imageuploadui.ts#L55](https://github.com/ckeditor/ckeditor5/blob/ce9b09c631bbdd8afe304573f1e9ef5dd94fc1d4/packages/ckeditor5-image/src/imageupload/imageuploadui.ts#L55)

You can use [https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html#function-forceDisabled](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html#function-forceDisabled) to get that command disabled. It will disable the button too.
