### ISSUE TITLE
The state of toggle buttons is conveyed only via color with low contrast

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#1405]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

## 📋 Steps to reproduce

1. Press "Bold" button.

## ✅ Expected result

The contrast between the button's background and toolbar is at least 3:1.

## ❎ Actual result

The contrast between the button and toolbar is around 1.28:1

**Comment by mlewand** [comment]
A way that CKE4 mitigates this issue is by adding an extra outline to the button.

Let's see if it really is an issue and if is what are the options to satisfy this requirement.

**Comment by wimleers** [comment]
The outline sounds like a fine solution but IIRC @Reinmar indicated that this was considered too visually disruptive for the design.

@lauriii indicated similar challenges in the work he did on https://www.drupal.org/project/claro — this aspect was one of _the_ most challenging problems!

FYI: tracking this at https://www.drupal.org/project/drupal/issues/3283803 😊

**Comment by mlewand** [comment]
Lets mock quick and dirty examples based on [https://github.com/ckeditor/ckeditor5/issues/1405#issuecomment-1152234595](https://github.com/ckeditor/ckeditor5/issues/1405#issuecomment-1152234595) and put screenshots here.

**Comment by mlewand** [comment]
Blocked by #11989
