### ISSUE TITLE
Export to Word & Export to PDF：exported result is incorrect

### ISSUE THREAD

**Issue by zhoujingfu** [ckeditor/ckeditor5#14062]
## 📝 Provide detailed reproduction steps (if any)

1. Custom Build  with DecoupledDocumentEditor

### ✔️ Expected result

The export result is consistent with the page

### ❌ Actual result

The export result is inconsistent with the page，Style replaced by symbols

pdf:
![image](https://user-images.githubusercontent.com/43539608/236805815-5514baf5-3937-45e9-af68-44ea6b6a5b4a.png)

word:
![image](https://user-images.githubusercontent.com/43539608/236806240-7d809fa9-d3df-4a60-aae9-6ec54ec66ccd.png)

## 📃 Other details

* Browser: Google 111.0.5563.111
* OS:  win 11
* First affected CKEditor version: 37.1.0
* Installed CKEditor plugins: 
    "@ckeditor/ckeditor5-alignment": "^37.1.0",
    "@ckeditor/ckeditor5-autoformat": "^37.1.0",
    "@ckeditor/ckeditor5-autosave": "^37.1.0",
    "@ckeditor/ckeditor5-basic-styles": "^37.1.0",
    "@ckeditor/ckeditor5-block-quote": "^37.1.0",
    "@ckeditor/ckeditor5-cloud-services": "^37.1.0",
    "@ckeditor/ckeditor5-code-block": "^37.1.0",
    "@ckeditor/ckeditor5-comments": "^37.1.0",
    "@ckeditor/ckeditor5-dev-translations": "^32.1.2",
    "@ckeditor/ckeditor5-dev-utils": "^32.1.2",
    "@ckeditor/ckeditor5-document-outline": "^37.1.0",
    "@ckeditor/ckeditor5-editor-decoupled": "^37.1.0",
    "@ckeditor/ckeditor5-essentials": "^37.1.0",
    "@ckeditor/ckeditor5-export-pdf": "^37.1.0",
    "@ckeditor/ckeditor5-export-word": "^37.1.0",
    "@ckeditor/ckeditor5-find-and-replace": "^37.1.0",
    "@ckeditor/ckeditor5-font": "^37.1.0",
    "@ckeditor/ckeditor5-format-painter": "^37.1.0",
    "@ckeditor/ckeditor5-heading": "^37.1.0",
    "@ckeditor/ckeditor5-highlight": "^37.1.0",
    "@ckeditor/ckeditor5-horizontal-line": "^37.1.0",
    "@ckeditor/ckeditor5-html-embed": "^37.1.0",
    "@ckeditor/ckeditor5-html-support": "^37.1.0",
    "@ckeditor/ckeditor5-image": "^37.1.0",
    "@ckeditor/ckeditor5-import-word": "^37.1.0",
    "@ckeditor/ckeditor5-indent": "^37.1.0",
    "@ckeditor/ckeditor5-link": "^37.1.0",
    "@ckeditor/ckeditor5-list": "^37.1.0",
    "@ckeditor/ckeditor5-markdown-gfm": "^37.1.0",
    "@ckeditor/ckeditor5-media-embed": "^37.1.0",
    "@ckeditor/ckeditor5-mention": "^37.1.0",
    "@ckeditor/ckeditor5-page-break": "^37.1.0",
    "@ckeditor/ckeditor5-pagination": "^37.1.0",
    "@ckeditor/ckeditor5-paragraph": "^37.1.0",
    "@ckeditor/ckeditor5-paste-from-office": "^37.1.0",
    "@ckeditor/ckeditor5-remove-format": "^37.1.0",
    "@ckeditor/ckeditor5-restricted-editing": "^37.1.0",
    "@ckeditor/ckeditor5-revision-history": "^37.1.0",
    "@ckeditor/ckeditor5-select-all": "^37.1.0",
    "@ckeditor/ckeditor5-slash-command": "^37.1.0",
    "@ckeditor/ckeditor5-special-characters": "^37.1.0",
    "@ckeditor/ckeditor5-style": "^37.1.0",
    "@ckeditor/ckeditor5-table": "^37.1.0",
    "@ckeditor/ckeditor5-template": "^37.1.0",
    "@ckeditor/ckeditor5-theme-lark": "^37.1.0",
    "@ckeditor/ckeditor5-track-changes": "^37.1.0",
    "@ckeditor/ckeditor5-typing": "^37.1.0",
    "@ckeditor/ckeditor5-watchdog": "^37.1.0",
    "@ckeditor/ckeditor5-word-count": "^37.1.0",
    "@wiris/mathtype-ckeditor5": "^8.2.6",
    "@ckeditor/ckeditor5-ui":"^37.1.0"
* CKEditor Config: 
    exportWord: {
    stylesheets: ["EDITOR_STYLES"],
    fileName: "doc.docx",
    converterOptions: {
      header: [
        // Header template for all headers (without the `type` property).
        {
          html: '<p class="styled">header-test</p>',
          css: templateCSS,
        },
      ],
      footer: [
        // Footer template for all footers (without the `type` property).
        {
          html: '<p class="styled">footer-test</p>',
          css: templateCSS,
        },
      ],
    },
  }
    
---

**Comment by Reinmar** [comment]
That's due to the fact that you use Markdown output. Exports will work with HTML output only. Markdown does not guarantee 100% data preservation (it has its issues as a format), so it's not the best idea to use it if you want exports to work well too.

**Comment by zhoujingfu** [comment]
> * markdown
I see. Due to the Markdown  plugin. thank you！
