### ISSUE TITLE
[Docs] The @see tag is not rendered

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1408]
I've stumbled upon a curious thing: I can see plenty of `@see` tags defined, yet in the rendered docs they are not present.
- docs: https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_template-Template.html#function-apply
- code: https://github.com/ckeditor/ckeditor5-ui/blob/84393ac7f10a253e773922385f80fad22786528f/src/template.js#L178-L182.

It looks like we lack of information on docs pages and/or bloat docs with useless information.

/cc @Reinmar, @oleq

**Comment by oleq** [comment]
cc @msamsel

**Comment by Reinmar** [comment]
cc @pomek

**Comment by Reinmar** [comment]
Actually, it's fixed already.
