### ISSUE TITLE
I want to develop an emoji plugin but I am encountering some issues.

### ISSUE THREAD

**Issue by Y2zz** [ckeditor/ckeditor5#14083]
I want to develop an emoji plugin that allows users to input `[happy]` or select emojis from a panel to insert into the editor. When retrieving the content using `editor.getData()`, the emojis should be converted to text such as `[happy]`. I have been reading the documentation for a while but I am not sure where to start. I would appreciate it if someone could provide me with some guidance on how to proceed.

**Comment by Witoso** [comment]
Nice idea :)

Start with our tutorials on how to create plugins. Although most likely you will not create widgets, the tutorials explain how to operate with the model and its outputs.
1. [Abbrevation](https://ckeditor.com/docs/ckeditor5/latest/framework/plugins/abbreviation-plugin/abbreviation-plugin-level-1.html)
2. [Inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html).
3. [ Block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-a-block-widget.html).

As far as I understand your use case: 
1. Selecting emojis from the panel could be handled by [Special characters](https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html).
2. You need to handle conversion of setting data into editor, and getting data from the editor (data pipeline).
3. But also typing, this will probably require listening to the [events](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/event-system.html), to mark the text with some attribute. Maybe [AutoLink](https://github.com/ckeditor/ckeditor5/blob/6b6bbaa634/packages/ckeditor5-link/src/autolink.ts#L71) could be some useful reference.

**Comment by Witoso** [comment]
You need to set a proper [dataDowncast](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/conversion/downcast.html) during conversion, and most probably [insert text](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-insertText:WITHOUT_ATTRIBUTES). 

I don't have time for an exact example. This is an example from the [docs]:(https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-for):
```js
editor.conversion.for( 'dataDowncast' ).add( dispatcher => {
	dispatcher.on( yourElement,  ( evt, data, conversionApi ) => {
		// Do something with a view your element element.
	} );
} );
```

**Comment by Witoso** [comment]
@Y2zz great that you were able to develop something, and congratulations on developing such a plugin! I apologize I couldn't support you better.

I will take this feedback to think about how to improve the docs.
