### ISSUE TITLE
Unexpected "Misplaced dependencies" error

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14090]
In the [`packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts#L12-L14) file we have two imports from the `utils` package:

```ts
import type { Collection, GetCallback, ObservableChangeEvent } from 'ckeditor5/src/utils';
// eslint-disable-next-line ckeditor5-rules/ckeditor-imports
import { scrollViewportToShowTarget } from '@ckeditor/ckeditor5-utils/src/dom/scroll';
```

It can be simplified to:

```ts
import {
  scrollViewportToShowTarget,
  type Collection,
  type GetCallback,
  type ObservableChangeEvent
} from 'ckeditor5/src/utils';
```

However doing so will throw following error from pre-commit hook:

```text
🔥 Found some issue with dependencies in @ckeditor/ckeditor5-find-and-replace.

❌ Misplaced dependencies (`dependencies` or `devDependencies`):

The following packages are not used in the source and should be moved to `devDependencies`
- @ckeditor/ckeditor5-utils
```

**Comment by Witoso** [comment]
LGTM, you deleted the `@ckeditor/ckeditor5-utils`, and you only use `ckeditor5/src/utils` (a different package) after the change.
