### ISSUE TITLE
Link plugin doesn't work if the editor runs in the React-Modal

### ISSUE THREAD

**Issue by Oleg-Nagornov** [ckeditor/ckeditor5#1409]
🐞 Bug report 
## 💻 Version of CKEditor
Used versions:
`"@ckeditor/ckeditor5-core": "~11.1.0",
    "@ckeditor/ckeditor5-ui": "~11.2.0",
    "@ckeditor/ckeditor5-react": "~1.1.0",
    "@ckeditor/ckeditor5-dev-utils": "~11.0.1",
    "@ckeditor/ckeditor5-utils": "~11.1.0",
    "@ckeditor/ckeditor5-basic-styles": "~10.1.0",
    "@ckeditor/ckeditor5-theme-lark": "~12.0.0",
    "@ckeditor/ckeditor5-editor-classic": "~11.0.2",
    "@ckeditor/ckeditor5-alignment": "~10.0.4",
    "@ckeditor/ckeditor5-essentials": "~10.1.3",
    "@ckeditor/ckeditor5-heading": "~10.1.1",
    "@ckeditor/ckeditor5-link": "~10.1.0",
    "@ckeditor/ckeditor5-paragraph": "~10.0.4",`

Editor initializations:
<CKEditor
                config={{
                    plugins: [Essentials, Heading, Paragraph, Bold, Italic, Strikethrough, Underline, Alignment, Link],
                    toolbar: ['Heading', '|', 'Bold', 'Italic', 'Strikethrough', 'Underline', 'Alignment', 'Link', 'Undo', 'Redo'],
                }}
                editor={ClassicEditor}
                data={''}
                onChange={(e, editor) => {}}
            />
## 📋 Steps to reproduce
1. Use any React App
2. Create the editor instance into React-Modal body
3. Try to add a link using standart UI
4. You will see standart Link-Add UI 
5. The url-input field won't have focus. Also, there is no way to set focus into this field.

## ✅ Expected result
The input focus can be setted to the url-input field
## ❎ Actual result
It cant'be setted
## 📃 Other details that might be useful
Running in the React-Modal:
![screenshot_20181213_134342](https://user-images.githubusercontent.com/17454234/49933603-25311000-fedd-11e8-9541-2ff8fd818a96.png)
Running without the React-Modal:
![screenshot_20181213_134400](https://user-images.githubusercontent.com/17454234/49933630-3548ef80-fedd-11e8-8777-948526090d23.png)

**Comment by oleq** [comment]
Hi, could you provide a working sample? (JSFiddle, CodePen, etc.)

Anyway, we had a similar issue with the [Bootstrap modals](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/overview.html#compatibility-with-bootstrap), maybe that will help you.

**Comment by Oleg-Nagornov** [comment]
Yes, you are right and it's the same issue.
The plugin works correctly after I add 'enforceFocus = false' property to the Modal.

**Comment by zomby22** [comment]
for me when I enforcefocus, the ckeditor plugin stops working, I get a blank field. without it plugin works but the link button popup window appears outside the modal box.

**Comment by deepanshu-ddreg** [comment]
how can i set enforce focus to false in mui modal
