### ISSUE TITLE
Garbage letters shown in the dialog when clicking link button from toolbar👍

### ISSUE THREAD

**Issue by lizeng999** [ckeditor/ckeditor5#14099]
## 📝 Provide detailed reproduction steps (if any) 👍

1. …Online customer builder
2. …click link widge from toolbar items
3. …

### ✔️ Expected result
Link pop up shown up, allows the user to enter link URL
_What is the expected result of the above steps?_

### ❌ Actual result
garbage letters are displayed first , see attached file
After entering link url and click Save, it should save the link info..
_What is the actual result of the above steps?_
From console log, it threw up the following error:
ckeditor.js:5 Uncaught CKEditorError: view-renderer-filler-was-lost
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-view-renderer-filler-was-lost
    at zg._removeInlineFiller (ckeditor.js:5:491931)
    at zg.render (ckeditor.js:5:489702)
    at Fp._render (ckeditor.js:5:532200)
    at Fp.<anonymous> (ckeditor.js:5:528535)
    at Fp.fire (ckeditor.js:5:349049)
    at Fp.change (ckeditor.js:5:531448)
    at Fp._disableRendering (ckeditor.js:5:532101)
    at listenTo.priority (ckeditor.js:5:605970)
    at kA.fire (ckeditor.js:5:349049)
    at kA._runPendingChanges (ckeditor.js:5:723319)
### ❓ Possible solution
👍
_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …Chrome
* OS: …WIN10
![garbageLetter_link](https://github.com/ckeditor/ckeditor5/assets/26714210/a46e0ad9-f1a5-4d7d-9bb2-5712455d1d2f)

* First affected CKEditor version: …37.1.0
* Installed CKEditor plugins: …customized plugins

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Make sure to use UTF8 in your entire setup: from the server to HTML page.

CKE5 will not work with any other encoding.
