### ISSUE TITLE
inserthtml attribute conversion...mousedown to data-cke-pa-mousedown..

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [ckeditor/ckeditor5#141]
1.ckeditor.insertHTML('table tr td mousedown="customfunction()">cheking for mousedown td tr table).

converted after pasting table tr td data-cke-pa-mousedown="customfunction()">cheking for mousedown td tr table..and event not triggered on mouse down how to trigger custom function on mousedown?

**Comment by Reinmar** [comment]
Hey, this is CKEditor 5's bug tracker. Please report your issue on http://dev.ckeditor.com

**Comment by luzfcb** [comment]
@Reinmar enable "Issue Template" (https://github.com/blog/2111-issue-and-pull-request-templates ) might be a good option to tell/teach CKEditor users how to report an issue and also indicate where the CKEditor 4 bugs should be reported

**Comment by Reinmar** [comment]
Thanks, we can consider. Especially that we've got so many repos that it may be confusing where you should report an issue.
