### ISSUE TITLE
Unable to edit

### ISSUE THREAD

**Issue by winterant** [ckeditor/ckeditor5#14108]
## 📝 Provide detailed reproduction steps (if any)

1. I edit something into classic ckeditor5, source html code is:
```html
<ol>
    <li>
        Why the content cannot be edited?
    </li>
</ol>
<figure class="image image_resized">
    <img src="/img/643a00e74c177.png">
    <figcaption>Picture</figcaption>
</figure>
```
2. Save it into database mysql.
3. Load the content from database:
```html
<textarea id="my-ckeditor5">
  <ol>
      <li>
          Why the content cannot be edited?
      </li>
  </ol>
  <figure class="image image_resized">
      <img src="/img/643a00e74c177.png">
      <figcaption>Picture</figcaption>
  </figure>
</textarea>
```
4. Then, I initialize the ckeditor:
```javascript
ClassicEditor.create(document.querySelector("#my-ckeditor5")).then(editor => {

      }).catch(error => {
        console.error(error);
      })
    })
```
5. Unfortunately, the editor can't be edit.
<img width="1014" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/37205944/a5d8f5c9-ceee-4f9d-82ae-462e470d5a5c">

Report the wrong information:
<img width="1326" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/37205944/e941a2ab-6e24-4ddf-928b-e7fb3e3519b7">

Report the wrong information:
<img width="1185" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/37205944/ab1e20e9-9ceb-4100-829b-5468c97900f3">

### ✔️ Expected result

It should be able to edit.

### ❌ Actual result

Any content cannot be selected or edited.

### ❓ Possible solution

I think there are some characters have conflicts.

## 📃 Other details

* Browser: Chrome
* OS: MacOS 13.2.1 (22D68)
* First affected CKEditor version: ckeditor5-37.1.0
* Installed CKEditor plugins: 
```
"heading", "bold", "italic", "underline", "horizontalLine", "fontColor", "fontBackgroundColor",
"highlight", "|", "alignment", "outdent", "indent", "numberedList", "bulletedList", "todoList", "|",
"code", "codeBlock", "link", "blockQuote", "pageBreak", "insertTable", "imageUpload",
"mediaEmbed",
"|", "removeFormat", "undo", "redo"
```

**Comment by Witoso** [comment]
@winterant please share your plugins as well, we only see the toolbar configuration, and the way how you install and build the editor.

**Comment by winterant** [comment]
![image](https://github.com/ckeditor/ckeditor5/assets/37205944/efafe473-d842-48db-b16f-5ca71ea742eb)
The picture shows plugins all I selected. Thanks.

**Comment by Witoso** [comment]
Could you send the build that is not working for you? I think the problem is in the webpackUniversalModuleDefninition, why do you use it?

**Comment by winterant** [comment]
I'm sorry. I can't reproduce this problem anymore after I rebuilt the project. Maybe I made some thing wrong before.
