### ISSUE TITLE
Preserve selected font properties (style, size, etc.) after inserting a widget

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#14106]
## 📝 Provide a description of the improvement

Currently, when non-defualt font properties are selected, and then a widget (e.g. image, math formula) is inserted into the document, the font reverts back to its default state.

This behavior could be improved in such a way, that the selected font family, size, background color etc. would be preserved upon inserting a widget.

Steps to reproduce this behavior are as follows:

1. Select some non-default font property, e.g. by changing the font family
2. Type something into the editor to see the non-default font
3. Insert a widget element, e.g. an image
4. Continue typing and notice how the font family changed back to default

![image](https://github.com/ckeditor/ckeditor5/assets/72079603/8b3c0760-b644-4bf7-8105-aece88294a13)

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* CKEditor version: N/A
* Installed CKEditor plugins: N/A
---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
What we would need to do:
1. Model document selection can pull attributes from inline widgets (only those that may be applied to text).
2. Prepare issue for MathType should change the schema to extend $inlineObject, insert widget using model insert object (TBD). Rel: https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html#defining-the-schema

**Comment by niegowski** [comment]
> 1. Model document selection can pull attributes from inline widgets (only those that may be applied to text).

This part requires update:

https://github.com/ckeditor/ckeditor5/blob/8ad29ada029c0dd748b4f3c6eed6dc899445323e/packages/ckeditor5-engine/src/model/documentselection.ts#L1125-L1192

**Comment by filipsobol** [comment]
Request to fix MathType integration: https://github.com/wiris/html-integrations/issues/811
