### ISSUE TITLE
When switching list effects, a bug occurred

### ISSUE THREAD

**Issue by yixiaco** [ckeditor/ckeditor5#14123]
### Screenshot

https://github.com/ckeditor/ckeditor5-vue/assets/30982989/9c835846-bbdb-4a5e-9d02-03a7fa66dbf4

### Reproduce Link

https://stackblitz.com/edit/vitejs-vite-zi6yrv?file=src/App.vue

### Custom build repository

https://gitee.com/yixiacoco/ckeditor5-overall-build

**Comment by Witoso** [comment]
As you're using General HTML Support, and you're setting the inline styles on `li`, those styles will preserve even if you change the list style to paragraph. 
![image](https://github.com/ckeditor/ckeditor5/assets/9881379/184b7690-06b6-43d6-bd97-bfb2aad3302b)

Consider more granular HTML control and disabling some styles.

**Comment by yixiaco** [comment]
> 当您使用 General HTML Support 并在 上设置内联样式时`li`，即使您将列表样式更改为段落，这些样式也会保留。 ![图像](https://user-images.githubusercontent.com/9881379/237955944-184b7690-06b6-43d6-bd97-bfb2aad3302b.png)
> 
> 考虑更精细的 HTML 控制并禁用某些样式。

https://github.com/ckeditor/ckeditor5/assets/30982989/2bdcc83f-2e0f-4ff0-8c52-01eada36cc9a

**This text is copied from the web side, and in fact, there is no way to disable this method, right**
