### ISSUE TITLE
Background color doesn't cover whole letters

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14126]
## 📝 Provide detailed reproduction steps (if any)

1. Open the `font-color` test.
2. In the form below the editor change the color and background color to `red`.
3. Copy the red block into the editor.

### ✔️ Expected result

Whole letters should be covered by the red background.

### ❌ Actual result

Parts of the letters "p", "y", and "g" are outside the red block.

## 📃 Other details

* Browser: Chrome 113 (can't reproduce in Firefox)
* OS: Linux

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is how the Chrome engine works. And most likely, only on Linux.

This is what I can see:

![](https://github.com/ckeditor/ckeditor5/assets/156149/d926b7e6-1501-4ca8-86a4-056b6b123d69)
