### ISSUE TITLE
Pasting table from Google Sheets creates table with 0px width

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14122]
This is related to the [bug](https://github.com/ckeditor/ckeditor5/issues/13746) which was partially fixed in https://github.com/ckeditor/ckeditor5/pull/13915.

## 📝 Provide detailed reproduction steps (if any)

1. Change the `htmlSupport` object in `ghs-all-features.js` test to:
    ```
    allow: [
      {
        name: /^(table|thead|tbody|td|th|tr|col|colgroup)$/,
        styles: true,
        attributes: true,
        classes: true
      }
    ]
    ```
2. Run `yarn manual -f html-support` and open the `ghs-all-features` test.
4. Select and copy few cells from Google Sheets to paste them into the editor.

### ✔️ Expected result

Table should be properly pasted.

### ❌ Actual result

Table has 0px width.

![Screenshot_20230512_091247](https://github.com/ckeditor/ckeditor5/assets/4145208/4f3d96a0-ee09-4601-aa42-ceb9830cd175)

### ❓ Possible solution

This bug is already fixed in the PasteFromOffice plugin (see links above), so part of it may need to be ported back to the Table plugin.

## 📃 Other details

* Browser: Firefox 113.0
* OS: Linux
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
I'm torn, it's the data that we get from Google, want to make it better? Enable `PasteFromOffice` which AFAIK is a part of all builds and website demos and docs. At the same time someone may not have this plugin 🤔

**Comment by filipsobol** [comment]
We discussed this internally and decided that `PasteFromOffice` is required plugin when working with data from Office, Google Docs and Google Sheets. This bug is fixed in this plugin, so we are closing this issue.
