### ISSUE TITLE
SimpleUploadAdapter CDN ?

### ISSUE THREAD

**Issue by mittal-sahab-sudo** [ckeditor/ckeditor5#14125]
Is there any CDN via which I can install SimpleUploadAdapter. All I can find in documentation is installing it via npm.

**Comment by Witoso** [comment]
Unfortunately, it's not part of the builds, and it's not that easy to add (unless you use [a DLL setup](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html)).

Let's close it as a duplicate of https://github.com/ckeditor/ckeditor5/issues/5751, and we will gather interest there.
