### ISSUE TITLE
Request: How do I use plugins in non-npm environments

### ISSUE THREAD

**Issue by Eusen** [ckeditor/ckeditor5#1413]
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 💻 Version of CKEditor

latest

## 📋 Steps to reproduce
For example: 
![image](https://user-images.githubusercontent.com/14822175/50073394-6a25b100-0213-11e9-9064-722e2f19e568.png)
I want to use this plugin, but I do not want to build it into my project, I hope I can use them from CDN, like ckeditor.js:
`https://cdn.ckeditor.com/ckeditor5/11.2.0/classic/ckeditor.js`
If u provide ckeditor CDN link, why not provide all plugins?

## ✅ Expected result
I hope I can load plugin from CDN

## ❎ Actual result
I didn't find any way.

## 📃 Other details that might be useful
nop

**Comment by oleq** [comment]
Unfortunately, it's impossible. Check out the [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html), especially:

> One of the possible mistakes is trying to add a plugin in this way to an existing (bundled) editor build. Installing an existing build and then trying to add a plugin to it may not work if that plugin needs to import any of the source editor modules.
> The reason why this method will not work is that dependencies of the added plugin may duplicate the code already bundled in the used editor build. In the best scenario, this is going to raise the overall code size. In the worst scenario, an application built this way may be unstable.

CKEditor 5 is an ultra–modular framework. The classes delivered by the `ckeditor5-upload` package use other classes and utilities of the framework. They `import` them at the very beginning of their files. If you use a plugin (classes) with an editor build made by webpack (like `ckeditor5-build-classic`) those imports make no longer sense (how to resolve them?). [Only standalone (import–less) features can be added that way](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html#adding-simple-standalone-features) to the build.

You should create an editor build if you want to add extra plugins. Besides, the classes of ckeditor5-upload are available in all ready–to–use editor builds we provide. Maybe your editor already has them? (e.g. try `editor.plugins.get( 'FileRepository' )`).

Also see https://github.com/ckeditor/ckeditor5/issues/1047#issuecomment-393068327.

**Comment by Eusen** [comment]
Thanks for reply

**Comment by sandeepimpressads** [comment]
but the editor build is not having the Font plugin. I just want to add font plugin, I am in a pure html and Jquery environment cannot use npm.

**Comment by olitomas** [comment]
Just build a bundle and download it with the online builder: https://ckeditor.com/ckeditor-5/online-builder/

**Comment by riniculous** [comment]
> Just build a bundle and download it with the online builder: https://ckeditor.com/ckeditor-5/online-builder/
@olitomas 
I bundled and downloaded but you are still left with a having to use ES6 modules
![image](https://user-images.githubusercontent.com/25195/90690009-94c0dc00-e236-11ea-86b1-4fd7722396e1.png)

**Comment by ujjwalgarad** [comment]
any solution on this? or should I change the entire stack of my web applications?

**Comment by Eusen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PubliAlex** [comment]
@ujjwalgarad you can change, without node.js, npm, webpack and all that stuff, you are stuck with standard prebuild editor.

**Comment by Eusen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by akash-magar-dev** [comment]
same issue I am using cdn and don't have npm setup please suggest the best approach

**Comment by Eusen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
