### ISSUE TITLE
Typo on docs page

### ISSUE THREAD

**Issue by eszczygiel** [ckeditor/ckeditor5#1414]
## 📋 Typo in Balloon editor section

1.  https://ckeditor.com/docs/ckeditor5/latest/examples/builds/balloon-editor.html
2. "apprears" instead of "appears"

**Comment by AnnaTomanek** [comment]
Fixed with https://github.com/ckeditor/ckeditor5/commit/d1521dac577335f2d588beac7fbfb4277adae2a5. Thanks!
