### ISSUE TITLE
Please add an Accessibility Conformance Report

### ISSUE THREAD

**Issue by mgifford** [ckeditor/ckeditor5#14141]
## 📝 CKEditor 4 had a VPAT & CKEditor 5 needs an ACR

You can see the VPAT here:  
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_section508.html

Something similar needs to happen.  
  
I would recommend using tool from the GSA [https://gsa.github.io/openacr-editor/](https://gsa.github.io/openacr-editor/) 

I'm a bit biased though as our team built it. 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Page published: https://ckeditor.com/docs/ckeditor5/latest/features/accessibility.html
