### ISSUE TITLE
List markers should "stick" to list items when a list is indented

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#14155]
## 📝 Provide a description of the improvement

Currently, in Chromium-based browsers and in Firefox, when a list is indented, the list items move but the list markers keep their position:

![indent_chromium](https://github.com/ckeditor/ckeditor5/assets/72079603/6866291f-8ee7-46c0-9176-1a4e85b49ca8)

In Safari, the markers "stick" to the items:

![indent_safari](https://github.com/ckeditor/ckeditor5/assets/72079603/f95e7cac-5bd5-47f3-b32d-f6c7617ae266)

Could this behavior be normalized across browsers? The default behavior should probably be the one that's present in Safari.

## 📃 Other details

* Browser: Chromium, Firefox, Safari
* OS: cross-OS
* CKEditor version: N/A
* Installed CKEditor plugins: List, Document list, Indent block

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Scope:

For now, we will turn off the block indentation of the \`Document list\`, it doesn't work in \`Lists\`, and it's actually indenting paragraphs, and not \`li\` or whole `ul/ol` which would be an expected result.

Rel: #12466
