### ISSUE TITLE
Flood of source map related 404s when loading an editor with color picker

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#14160]
## 📝 Provide detailed reproduction steps (if any)

I built docs with simple `yarn docs --skip-api` and served them with `yarn docs:serve`:

![](https://github.com/ckeditor/ckeditor5/assets/156149/072f0800-635a-404b-b1b7-65e2a210108b)

All these are new:

```
DevTools failed to load source map: Could not load content for webpack://ckeditor5/node_modules/vanilla-colorful/hex-color-picker.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

Interestingly, I don't see them on: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
All clear for me - manual test:

![](https://github.com/ckeditor/ckeditor5/assets/10883184/4d7e90ec-7c1d-4837-bb9e-7168ddb27f69)

Docs:  
 

![](https://github.com/ckeditor/ckeditor5/assets/10883184/66840915-e031-4e3f-8d29-a7f6b79d216d)

Notably, I use different URL in docs - [http://192.168.100.6:8080/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](http://192.168.100.6:8080/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) (so other domain and editor version) - I'm not sure if it can matter anyhow though.

**Comment by Dumluregn** [comment]
I see you also got other issues in the console like API search unavailable, which works for me. Maybe it is a domain issue?

**Comment by Reinmar** [comment]
Could you check with a fake domain (e.g. fake.ckeditor.com)? :|

**Comment by Dumluregn** [comment]
Sure, I'll set it up and let you know.

**Comment by Dumluregn** [comment]
Still works:

![](https://github.com/ckeditor/ckeditor5/assets/10883184/28877522-bb21-481f-b187-ba44a03b81a3)
