### ISSUE TITLE
"Failed to resolve module specifier" when trying to setuo SimpleUploadAdapter

### ISSUE THREAD

**Issue by Flagmans1990** [ckeditor/ckeditor5#14165]
## 📝 Provide detailed reproduction steps (if any)

1. I installed CKEditor by using `npm i @ckeditor/ckeditor5-build-decoupled-document`
2. Then installed SimpleUploadAdapter by `npm install --save @ckeditor/ckeditor5-upload`
3. Used [these instructions](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html) to import SimpleUploadAdapter module.
How I imported:
`import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';`

### ❌ Actual result

`Uncaught TypeError: Failed to resolve module specifier "@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter". Relative references must start with either "/", "./", or "../".`

### ❓ Possible solution

I was trying to add `.js` prefixes and slashes. It seemed, that problem was been solving, but then appeared more and more the same errors.

Waiting for your solution.
Regards,
Tom

**Comment by Reinmar** [comment]
You're trying to add a plugin to an existing build, which isn't possible. A build is a closed, ready-to-use preset. Refer to [https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html](https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html) on how to install plugins.
