### ISSUE TITLE
The `equalMarkup` doesn't return any error when test fails

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14175]
## 📝 Provide detailed reproduction steps (if any)

1. Open the `packages/ckeditor5-list/tests/documentlist/documentlistseparator.js` test.
2. [In the last test](https://github.com/ckeditor/ckeditor5/pull/14174/files#diff-6f31b674ea28a8cb0070f94303437be072b2e6fa4f399df9d5d342dba81e2c1eR297), add a space so that the last closing tag is `</paragraph >` instead of `</paragraph>`.
3. Run `yarn test -f list`.

### ✔️ Expected result

The test result should indicate why the assertion failed. Example from the `.equal()` method:

![expected](https://github.com/ckeditor/ckeditor5/assets/4145208/abde834a-86c4-4324-a306-2449ac93cb62)

### ❌ Actual result

There's no meaningful message to help debug the error.

![actual](https://github.com/ckeditor/ckeditor5/assets/4145208/414b3d4d-4725-4814-a12d-2d292097ea7e)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-tests/lib/utils/automated-tests/assertions/equal-markup.js
