### ISSUE TITLE
Support for running automated tests written in TS

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#14171]
## 📝 Provide a description of the improvement

Similiar to #14170.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
We discussed it briefly, and I guess this ticket is more about trying and checking if it's possible then solving this problem fully.

**Comment by pomek** [comment]
Done in https://github.com/ckeditor/ckeditor5-dev/pull/886.
