### ISSUE TITLE
How to enable pasteFromOffice in the CDN version Super Build.

### ISSUE THREAD

**Issue by beshoo** [ckeditor/ckeditor5#14183]
Greetings everyone,

Currently, I'm utilizing Ckeditor5 in my VueJs project from CDN, since I've encountered some issues with the NPM version, which led me to choose the CDN version. I'm now seeking guidance on how to enable the pasteFromOffice feature in the CDN.

If you're interested, let me provide a brief summary of the issues I encountered with the NPM version.

I installed the build version, and it worked fine, but I couldn't install any plugins as documented. As a result, I had to install the **source** version and import it. However, the editor didn't appear in the DOM, and there were no console errors to indicate the problem. 

Thank you for your help in advance.

**Comment by Witoso** [comment]
> I'm now seeking guidance on how to enable the pasteFromOffice feature in the CDN.

It's added by default [to all predefined builds](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#list-of-plugins-included-in-the-ckeditor-5-predefined-builds).

> but I couldn't install any plugins as documented.

Not sure which doc di you use, [adding plugins to predefined builds requires rebuilding](https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html#adding-a-plugin-to-a-build).

> However, the editor didn't appear in the DOM, and there were no console errors to indicate the problem.

To better understand this one, we would need more details. Have you used our [Vue integration](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/vuejs-v3.html)?
