### ISSUE TITLE
I want to set the default input font color. What should I do with this change?

### ISSUE THREAD

**Issue by Allen-yuFeng** [ckeditor/ckeditor5#1419]
I want to set the default input font color. What should I do with this change?

**Comment by f1ames** [comment]
Hello @Allen-yuFeng,
I'm not exactly sure what do you mean by changing default input color. If the case is that you would like to change the default editor content (text) color, please refer to [our docs FAQ and styling CKEditor content]( https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#what-happened-to-the-contentscss-file-how-do-i-style-the-content-of-the-editor).

In short it can be done by attaching additional styles to the page where editor is used like:

```css
.ck-content {
    color: green;
}
```

Please remember that both page with the editor itself and the page on which editor content will be displayed should have the same styles attached.

**Comment by Allen-yuFeng** [comment]
我想达到这样的效果，就是学生写的作业需要老师批改，学生默认输入的字体颜色是黑色。老师默认输入的是红色字体。

I want to achieve the effect that the homework written by the students needs to be corrected by the teacher. The default font color input by the students is black. The teacher defaults to enter the red font.

**Comment by oleq** [comment]
@Allen-yuFeng You didn't tell us much about your use–case, so it's hard to help you. Wouldn't the [Hightlight](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html) feature be enough for your needs? (you can configure the highlighters so different users use different colors)

For more advanced collaboration features, check out https://ckeditor.com/collaboration/. It kinda feels like what you probably gonna need is the comments/suggestion mode features in your application.
