### ISSUE TITLE
Review the raw-loader dependency version in the project documentation

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1420]
[We had a bug report concerning installing the editor with the Vue CLI from source](https://github.com/ckeditor/ckeditor5-vue/issues/16) (plenty of errors). 

As it turned out the culprit was the `raw-loader` dependency, which has been [updated to v1.0.0](https://www.npmjs.com/package/raw-loader/v/1.0.0) a week ago by the maintainers (our project uses v0.5.1).

I updated the Vue.js feature guide so it tells the users to install `raw-loader@0.5.1` but I also noticed that there are other guides that require installing `raw-loader` from npm and, in theory, they all could suffer from the same bug:

```
ckeditor5/docs/builds/guides/frameworks/react.md
ckeditor5/docs/builds/guides/frameworks/vuejs.md
ckeditor5/docs/builds/guides/integration/advanced-setup.md
ckeditor5/docs/framework/guides/quick-start.md
```

Things to do:
* Check if this is actually an issue for these guides if people install 1.0.0 instead of 0.5.x (I'm pretty sure it is),
* If so, update the guides replacing `raw-loader` with `raw-loader@0.5.1`.
* Alternatively, we could figure out what's wrong with v1.0.0 and update our configs instead, effectively migrating the project to the latest `raw-loader`.

**Comment by jodator** [comment]
I'l update the docs as there are few minor issues:
1. I think the SVG part is not correct on how to use `raw-loader`:
	```js
 	chainWebpack: config => {
		// Vue CLI would normally use its own loader to load .svg files. The icons used by
		// CKEditor should be loaded using raw-loader instead.
		config.module
			.rule( 'svg' )
			.test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
			.use( 'file-loader' )
			.loader( 'raw-loader' );
	}
	```
	Should at least `.use( 'raw-loader' )` (not `file-loader`) and then chain `.loader( 'raw-loader' )` - that was causing the [wrong `config` object error](https://github.com/ckeditor/ckeditor5-vue/issues/16).

2. Remove (or use better `.test()` ) the [Vue's base loader for SVG](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/base.js#L106-L113). The base loader is used instead of the one from docs and just [replaces SVG file's path](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/base.js#L8-L13).

**Comment by oleq** [comment]
@jodator But what's the actual conclusion? 

Is it OK that we recommend `npm install raw-loader` and it comes as v1.0.0? 

Or should we state there that `npm install raw-loader@0.5.1` is required?

**Comment by jodator** [comment]
Testing
