### ISSUE TITLE
Erratic arrow movement in color picker

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14217]
## 📝 Provide detailed reproduction steps (if any)

1.  Open manual test with color picker: [http://localhost:8125/ckeditor5-font/tests/manual/font-color.html](http://localhost:8125/ckeditor5-font/tests/manual/font-color.html)
2.  Open font color dropdown.
3.  Set random color in color picker with mouse.
4.  Start pressing arrow down/up multiple times.

### ✔️ Expected result

Color picker slider follows the arrows pressed.

### ❌ Actual result

There are small departures - in the video below I always press arrow down:

https://user-images.githubusercontent.com/10883184/234572550-13d4eb48-4c6e-493a-882a-11a4ca29ce2f.mp4

**Comment by Dumluregn** [comment]
Done in #14215.
