### ISSUE TITLE
Unable to get custom plugin working

### ISSUE THREAD

**Issue by Rockatweb** [ckeditor/ckeditor5#14212]
Hi,
i just want to create a plugin that will give you the posibility to add a  single quote-author paragraph-tag with a css-class at the end of a blockquote-block.

But i don't know what i am doing wrong.
Either i get an error
`Uncaught CKEditorError: conversion-model-consumable-not-consumed {"items":[{"event":"insert","item":{"attributes":{"class":"author"},"name":"paragraph"}}]}`
or the plugin adds an paragraph-element that is not editable or the cursor jumps before the quote-author block.
I don't know what i am doing wrong and the documentation doesn't help me at all.

So i just created a codesandbox with my plugin-code, but i don't know why this isn't working.

Please have a look at the following link
[https://codesandbox.io/s/cocky-austin-c7chpc?file=/src/editor.js](https://codesandbox.io/s/cocky-austin-c7chpc?file=/src/editor.js)

Please help me with this, because after hours and days of searching i couldn't find any solution.

Cheers

**Comment by Witoso** [comment]
I just did a quick look but maybe it will help. I notice that in the command `insertquoteAuthorCommand.js`
```
    const elm = writer.createElement("paragraph", { class: "author" });
```

You're inserting HTML but you should actually create a model element, `quoteAuthor` is what you use if I see it correctly.

**Comment by Witoso** [comment]
This tutorial should be helpful: https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html#command

**Comment by Rockatweb** [comment]
thanks for your answer. So i reworked the whole plugin and now it is working. 
Here is the new code, maybe it will help others with their plugins

`
import { Command, Plugin } from '@ckeditor/ckeditor5-core';
import { ButtonView } from '@ckeditor/ckeditor5-ui';
import { Widget, toWidgetEditable } from '@ckeditor/ckeditor5-widget';

export default class QuoteAuthor extends Plugin {
  static get requires() {
    return [ QuoteAuthorEditing, QuoteAuthorUI ];
  }
}

class QuoteAuthorUI extends Plugin {
  init() {
    const editor = this.editor;
    const t = editor.t;

    editor.ui.componentFactory.add( 'quoteAuthor', locale => {
      const command = editor.commands.get( 'insertQuoteAuthor' );

      // The button will be an instance of ButtonView.
      const buttonView = new ButtonView( locale );

      buttonView.set( {
        // The t() function helps localize the editor. All strings enclosed in t() can be
        // translated and change when the language of the editor changes.
        icon: '<svg viewBox="0 -960 960 960" xmlns="http://www.w3.org/2000/svg"><path d="M730-400v-130H600v-60h130v-130h60v130h130v60H790v130h-60Zm-370-81q-66 0-108-42t-42-108q0-66 42-108t108-42q66 0 108 42t42 108q0 66-42 108t-108 42ZM40-160v-94q0-35 17.5-63.5T108-360q75-33 133.5-46.5T360-420q60 0 118 13.5T611-360q33 15 51 43t18 63v94H40Z"/></svg>',
        withText: true,
        tooltip: t( 'Quote Author' ),
      } );

      // Bind the state of the button to the command.
      buttonView.bind( 'isOn', 'isEnabled' ).to( command, 'value', 'isEnabled' );

      // Execute the command when the button is clicked (executed).
      this.listenTo( buttonView, 'execute', () => editor.execute( 'insertQuoteAuthor' ) );

      return buttonView;
    } );

    // Overwrite default Enter key behavior.
    this.listenTo( this.editor.editing.view.document, 'enter', ( evt, data ) => {
      const doc = this.editor.model.document;
      const positionParent = doc.selection.getFirstPosition();

      if ( positionParent.parent.parent.name === 'blockQuote' && !data.isSoft ) {
        this.editor.execute('insertParagraph', {
          position: editor.model.createPositionAfter(positionParent.parent.parent)
        });
        this.editor.editing.view.scrollToTheSelection();

        data.preventDefault();
        evt.stop();
      }

    } );
  }
}

class QuoteAuthorEditing extends Plugin {
  static get requires() {
    return [ Widget ];
  }

  init() {
    this._defineSchema();
    this._defineConverters();

    this.editor.commands.add( 'insertQuoteAuthor', new InsertQuoteAuthorCommand( this.editor ) );
  }

  _defineSchema() {
    const schema = this.editor.model.schema;

    schema.register( 'quoteAuthor', {
      allowIn: 'blockQuote',
      allowContentOf: '$block',
      isLimit: true,
      isObject: true,
    } );
  }

  _defineConverters() {
    const conversion = this.editor.conversion;

    conversion.for( 'upcast' ).elementToElement( {
      model: 'quoteAuthor',
      view: {
        name: 'p',
        classes: 'author'
      }
    } );
    conversion.for( 'dataDowncast' ).elementToElement( {
      model: 'quoteAuthor',
      view: {
        name: 'p',
        classes: 'author'
      }
    } );
    conversion.for( 'editingDowncast' ).elementToElement( {
      model: 'quoteAuthor',
      view: ( modelElement, { writer: viewWriter } ) => {
        const section = viewWriter.createEditableElement( 'p', { class: 'author' } );

        return toWidgetEditable( section, viewWriter );
      }
    } );
  }
}

class InsertQuoteAuthorCommand extends Command {
  execute() {
    this.editor.model.change( writer => {
      const quoteAuthor = writer.createElement( 'quoteAuthor' );
      writer.insertText('Author', quoteAuthor, 0);

      this.editor.model.insertObject(quoteAuthor, null, null, {
        setSelection: 'on'
      });

      writer.setSelection(quoteAuthor, 'in');
      this.editor.editing.view.focus();
      writer.setSelectionFocus(writer.createPositionAt(quoteAuthor, 'end'), 0);
    } );
  }

  refresh() {
    const model = this.editor.model;
    const selection = model.document.selection;
    const allowedIn = model.schema.findAllowedParent( selection.getFirstPosition(), 'quoteAuthor' );

    this.isEnabled = allowedIn !== null;
  }
}
`
