### ISSUE TITLE
Docs: Extend the bootstrap modal integration docs to consider other frameworks (or generalise it)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1421]
A follow-up of https://github.com/ckeditor/ckeditor5/issues/1409.

It seems that there are other frameworks providing modals have the same problem with CKEditor5.  We mention in our [docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/overview.html#compatibility-with-bootstrap):

> Configure Bootstrap to not steal focus from rich text editor fields.

And it is actually done in the linked code sample (but for Bootstrap only). 

I think we need do something because more users will have the same problem in the future with other frameworks:

* We could either make a [FAQ entry](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html) explaining the topic in a more generic manner.
* We could extend the [frameworks compatibility guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/overview.html) to consider other frameworks.

cc @AnnaTomanek @dkonopka @Reinmar

**Comment by AnnaTomanek** [comment]
A good catch. I'd probably recommend extending the [Integrating CKEditor 5 with JavaScript frameworks](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/overview.html) guide as it's the natural place where I'd be looking for this information. 

It won't hurt to have it in FAQ either, my issue with FAQ is that it's a bit unreadable as it's packed with text.

**Comment by dkonopka** [comment]
I've created codepens with some additional frameworks:
- [Foundation](https://codepen.io/ckeditor/pen/VqXYQq) - no issues ATM
- [Materialize](https://codepen.io/ckeditor/pen/gZebwy) - overridden input design + need to hack stealing focus issue

**Comment by oleq** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/1147
