### ISSUE TITLE
ckeditor5 custom build Error This module is declared

### ISSUE THREAD

**Issue by rlucky469** [ckeditor/ckeditor5#14223]
error TS7016: Could not find a declaration file for module 'ckeditor5-custom-build/build/ckeditor'.
 
![image](https://github.com/ckeditor/ckeditor5/assets/77981064/e82591d1-4d8d-4ae7-a531-3c138d8ef242)

**Comment by Witoso** [comment]
It looks like you're creating a custom build (from typescript). In this case, you need to make sure that you actually produce the `d.ts`. You could follow the steps [as described in one of the comments](https://github.com/ckeditor/ckeditor5/issues/13548#issuecomment-1486284270.) to alter the webpack, and prepare tsconfig for emitting types.

@apadol-cksource I think we need to add this example webpack config to building from source/custom build.

**Comment by Reinmar** [comment]
The source of any of our builds have now configuration that make them emit type definitions. E.g. [https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-build-classic](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-build-classic)

But we indeed could have that scenario (migrating from an old custom build) covered in the migration guide so we can send people there.

At the same time, we're talking about getting rid of the concept of customizing builds this way, so I think it does not make sense to spend time now on documenting how to get that work.

**Comment by Witoso** [comment]
But we don't have info here this is our build (or customizing our build). AFAIK this is a problem for the Online builder as well, you will download a package from there, use it in the Angular project, and it will not emit the types, as the webpack is not prepared.

I couldn't find in our docs anywhere an example of webpack that will emit the editor's types. I think it should be mentioned in [building from the source at least](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source).

**Comment by Reinmar** [comment]
Hm... I forgot about online builder. We'll get there with it, but you're right that there are types of custom builds so more potential problems.

What do you think we should add where, then?

**Comment by apadol-cksource** [comment]
We will [address the issue](https://github.com/cksource/ckeditor5-internal/issues/3029) by adding a section on how to adapt builds from the online builder in [the online builder guide](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#creating-custom-builds-with-online-builder).
