### ISSUE TITLE
Prepare for Edge 18

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1423]
The Edge 18 already caused some problems: https://github.com/ckeditor/ckeditor5-engine/issues/1607. 

The solution for now was to enforce Edge 17 in test on Browser Stack as we do not have tools other then BrowserStack to test CKEditor 5 on Edge 18 (at least easy to use).

Some of the issues with test were fixed (in very naive way) here: https://github.com/ckeditor/ckeditor5-engine/pull/1603.

**Comment by mlewand** [comment]
We're supporting the latest Edge for some time already.
