### ISSUE TITLE
Ability to display PBC despite having license check

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14235]
## 📝 Provide a description of the new feature

We have some needs where we'd want to display PBC logo despite having a premium license in place (e.g. some of our demos).

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
There are 3 options that can work for us:

1.  Simple config option `enforcePBC` set to `false` by default;
2.  If PBC is configured anyhow, enforce showing it;
3.  Hidden prop on `window` (like `open.closed` for CF features).

Let's confirm with business what we'd like most.

**Comment by Dumluregn** [comment]
Let's remember about documentation and communication.

**Comment by mlewand** [comment]
Let's implement it as a new opt-in config option (in PBC namespace) to enforce PBC visibility. Let it be `config.ui.poweredBy.forceVisible`.

**Comment by oleq** [comment]
@usqr FYI you will be able to set `config.ui.poweredBy.forceVisible: true`. Currently only available in development code, available for the public in the upcoming release.
