### ISSUE TITLE
The "insert image via URL" form layout is broken

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#14230]
### ✔️ Expected result

![](https://github.com/ckeditor/ckeditor5/assets/156149/3cde36d6-e59d-4a74-82ea-c4e7575e2eca)

Can be seen here: https://ckeditor.com/docs/ckeditor5/36.0.0/features/images/image-upload/images-inserting.html

### ❌ Actual result

Can be seen here: https://ckeditor.com/docs/ckeditor5/latest/features/images/images-inserting.html

![](https://github.com/ckeditor/ckeditor5/assets/156149/3960545c-5699-45bd-800b-9236c7fce594)

## 📃 Other details

*   First affected CKEditor version: 38.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
BTW, there was a second issue:

![](https://github.com/ckeditor/ckeditor5/assets/156149/61d3f811-10e1-429d-b80f-69eb5a6d210f)

(should look like this:)

![](https://github.com/ckeditor/ckeditor5/assets/156149/02bc0fa3-f40a-4261-87a3-1b573dff32eb)

But I can see you fixed this too (I checked it on master and it looks good).

**Comment by pszczesniak** [comment]
@Reinmar yes, more inputs could have been broken because we overwrite a generic input `CSS` class - scoping it only to color picker we resolve all those regressions.
