### ISSUE TITLE
I am getting a the below issue while I am build my application (ng build)...ERROR in ./src/assets/ckeditor5-29.0.0/packages/ckeditor5-build-classic/build/ckeditor.js Module parse failed: Unexpected token (5:551666) You may need an appropriate loader to handle this file type. And the ckeditor.js whole file logs in the terminal

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5#14241]
## Provide a description of the task

I am using CustomBuild CKEditor with the version 29.0.0 and Angular version 5.1 And CKEditor-angular version 1.2.3. 
steps:
I download the ckeditor zip file from git. I exported to that in my project assests folder. 
Then I went to the package ckeditor-build-classic and I did npm install ..And Next I imported required items in ckeditor.js file in src folder.
Then I did npm run build..After that I run ng build in my root project folder...then the above given error is coming..
Then I add the property allowJS:true in tsconfig.json file..then that error is gone..but the new error is coming like this..

ERROR in node_modules/chalk/types/index.d.ts(92,16): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.

I don't understand how to resolve this issue. Can anyone help me to resolve this issue?

Thanks in advance

**Comment by Witoso** [comment]
I think `chalk` is not our dependency. `skipLibCheck: true` may help here.

**Comment by Tiru150837** [comment]
Hi Witoso,

That chalk error is gone..but I am getting this error in the terminal while running ng build
An error occured during the build:
Error: EMFILE: too many open files, open '..\assets\ckeditor5-28.0.0\packages\ckeditor5-build-classic\node_modules\es-set-tostringtag\.eslintrc'

without running ng build ..directly running ng s command then that time  I didn't get this error..but when I opened the application and in network tap I am getting the errors like this

ERROR Error: Uncaught (in promise): TypeError: e is undefined
Ha/<@webpack-internal:///./src/assets/ckeditor5-28.0.0/packages/ckeditor5-build-classic/build/ckeditor.js:5626:259
using/<@webpack-internal:///./src/assets/ckeditor5-28.0.0/packages/ckeditor5-build-classic/build/ckeditor.js:820:233
i@webpack-internal:///./src/assets/ckeditor5-28.0.0/packages/ckeditor5-build-classic/build/ckeditor.js:827:32...

Is there anypossibility to resolve these issues?

**Comment by Witoso** [comment]
It's tough to debug such errors in such an old editor version. Please consider an update.
