### ISSUE TITLE
How to add PasteFromWord configurations to this CKEditor5

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5#14256]
pasteFromWordRemoveFontStyles: true,
forcePasteAsPlainText: true,
    removeButtons: ''

The above three properties from CKEditor4..But I want to same functionality can add to the CKEditor5. How can I achieve it?. I refer the document but I didn't get it. Can anyone help for this?

Thamks in Advance

**Comment by Witoso** [comment]
Currently, CKEditor 5 has [Paste from Office](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#automatic-content-filtering) plugin that clears and sanitizes content from Word.

If you **don't enable it**, the formatting from Word won't be preserved, for example, font family and font size will be automatically stripped off when you paste content from Microsoft Word and other sources (e.g. other websites).

**Comment by Tiru150837** [comment]
I checked the document .  But I am unable to clear how to use that for those specific properties which I mentioned before.

**Comment by Tiru150837** [comment]
And I am using that plugin Paste From Office. 
Is there anything configure explicitly to work it?

**Comment by Witoso** [comment]
We don't have exact replacements for the CKE4 options:

```
pasteFromWordRemoveFontStyles: true,
forcePasteAsPlainText: true,
removeButtons: ''
```

Paste as plain text is achieved with ctrl+shift+v. Font styles are removed if the [Font](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-size-feature) feature is configured in a proper way (you decide which ones you want to accept.) There's also a [remove format](https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html) feature for users.
