### ISSUE TITLE
PBC API docs in UiConfig are not rendered properly

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14254]
## 📝 Provide a description of requested docs changes

Go to: [https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-UiConfig.html](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-UiConfig.html)

If you click `poweredBy` prop there's no docs for it.

![](https://github.com/ckeditor/ckeditor5/assets/5353898/bff76eda-86a1-4d10-96c0-27a14298ee70)

Ensure that the changes are headed to `stable` branch so that we can deploy as soon as it's ready.

**Comment by Dumluregn** [comment]
Let's cover `viewportOffset` as well. It should be simply the matter of extracting the subinterface.

**Comment by oleq** [comment]
I briefly checked if the default Typedoc renderer can document such "nested" interfaces and it can. W could do the same in Umberto if the ROI was right. 

<img width="911" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1099479/b0dd1526-2ad0-47dd-a4d3-f251a4f5480b">

**Comment by Witoso** [comment]
Rel: https://github.com/cksource/umberto/issues/1129#issuecomment-1514540282

**Comment by Dumluregn** [comment]
Closed in #14284.
