### ISSUE TITLE
CKBox plugin: Tiff file uploaded by image button is not displayed correctly, works when inserted by ckbox plugin

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#14251]
## 📝 Provide detailed reproduction steps (if any)

1. Open: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Insert `.tiff` image using "Insert image" 

### ✔️ Expected result

Image visible and converted to `.webp` by CKBox plugin.

### ❌ Actual result

Image not visible, displayed like broken image, CKBox plugin not converting image to .webp:
<img width="807" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/32898551/5006ea0c-ac59-46c8-a882-0804e0ff5649">

## 📃 Other details

If the image is added to the CKBox plugin and then inserted into the editor, everything works fine (the image is converted to .webp and visible in the editor). 

* Browser: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Works right now.

![](https://github.com/ckeditor/ckeditor5/assets/9881379/741fe145-53c8-4ad5-8f66-595af72be468)

The problem that's still there is [that some browsers don't support showing TIFF](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support), therefor during upload there's still a missing image icon. After upload, it shows. Closing as this was related to the CKBox.
