### ISSUE TITLE
Can't type after 'isObject' entity at the end of the paragraph or before <br>

### ISSUE THREAD

**Issue by Oleg-Nagornov** [ckeditor/ckeditor5#1426]
🐞 Bug report 
## 💻 Version of CKEditor
Used versions:
`"@ckeditor/ckeditor5-core": "~11.1.0",
    "@ckeditor/ckeditor5-ui": "~11.2.0",
    "@ckeditor/ckeditor5-react": "~1.1.0",
    "@ckeditor/ckeditor5-dev-utils": "~11.0.1",
    "@ckeditor/ckeditor5-utils": "~11.1.0",
    "@ckeditor/ckeditor5-basic-styles": "~10.1.0",
    "@ckeditor/ckeditor5-theme-lark": "~12.0.0",
    "@ckeditor/ckeditor5-editor-classic": "~11.0.2",
    "@ckeditor/ckeditor5-alignment": "~10.0.4",
    "@ckeditor/ckeditor5-essentials": "~10.1.3",
    "@ckeditor/ckeditor5-heading": "~10.1.1",
    "@ckeditor/ckeditor5-link": "~10.1.0",
    "@ckeditor/ckeditor5-paragraph": "~10.0.4",`

Editor initializations:

```
<CKEditor
                config={{
                    plugins: [Essentials, Heading, Paragraph, Bold, Italic, Strikethrough, Underline, Alignment, Link],
                    toolbar: ['Heading', '|', 'Bold', 'Italic', 'Strikethrough', 'Underline', 'Alignment', 'Link', 'Undo', 'Redo'],
                }}
                editor={ClassicEditor}
                data={''}
                onChange={(e, editor) => {}}
            />
```

## 📋 Steps to reproduce

1. Register a new type of block, which is object and can be used into paragraph.
`editor.model.schema.register('myTag', {`
`            allowWhere: '$text',`
`            allowContentOf: '$block',`
`            allowIn: '$text',`
`            allowAttributes: ['tag', 'title', 'value'],`
`            isObject: true,`
`        });`

2. Pass sample text into editor:
`<p><myTag>xyz<myTag></p>`
`<p>Test text <myTag>xyz<myTag></p>`
`<p>Test text <myTag>xyz<myTag> test text test text</p>`
`<p><myTag>xyz<myTag><br>xyz</p>`

It means:
1. Object is one entity into `<p>`
2. Object is the last entity into `<p>`, prepended by text
3. Object is the last entity into `<p>`, prepended  and appended by text
4. `<br>` tag is the next of Object.

## ✅ Expected result
I can type after objectTag and data:change will fired.
## ❎ Actual result
I can type only in cases 1 and 3, In cases 2 and 4 - i can't.
## 📃 Other details that might be useful
I suppose, it's closely connected with this issue: https://github.com/ckeditor/ckeditor5/issues/407

**Comment by oleq** [comment]
What does your conversion to the view look like? What does `myTag` actually represent in your content?

**Comment by Oleg-Nagornov** [comment]
I suppose, that `myTag` will be in-text 'block', which should be non-editable.
These features have be already implemented, but there is an issue about typing after `myTag` element.

So, there are two cases:
1. ![screenshot_20190109_120247](https://user-images.githubusercontent.com/17454234/50888584-10299d00-1407-11e9-9b52-e91c34e99aa4.png)
If there is any text after `myTag`  and before the end of the paragraph, all works fine.
2. ![screenshot_20190109_120324](https://user-images.githubusercontent.com/17454234/50888649-364f3d00-1407-11e9-8051-ac6db5a5bbb6.png)
If there isn't any text after `myTag`  and before the end of the paragraph, i can't type after `myTag`.
The html code in the editor field will be something like this: 
`<p>Some text, some other text <myTag>myTag Content</myTag></p>`


I use the next conversions:

`editor.model.schema.register('myTag', {`
 `           allowWhere: '$text',`
`            allowContentOf: '$block',`
`            allowIn: '$text',`
`            allowAttributes: ['myTag', 'title', 'value'],`
`            isObject: true,`
`        });`

`       editor.conversion.elementToElement({`
`            model: 'myTag',`
`            view: {`
`                name: 'myTag',`
`                styles: {`
`                    'background-color': '#ececec',`
`                },`
`            },`
`        });`

`        editor.conversion.for('upcast').add(upcastElementToElement({`
`            view: {`
`                name: 'myTag',`
`            },`
`            model: 'myTag'`
`        }));`

`        editor.conversion.for('downcast').add(downcastAttributeToAttribute({`
`            model: {`
`                name: 'myTag',`
`                key: 'myTag'`
`            },`
`            view: 'myTag'`
`        }));`

`        editor.conversion.for('upcast').add(upcastAttributeToAttribute({`
`            model: {`
`                name: 'myTag',`
`                key: 'myTag'`
`            },`
`            view: 'myTag'`
`        }));`

**Comment by scofalik** [comment]
Inline object elements are not much supported as of now -- we haven't took time yet to research this and fix all the things that are not clicking there as there were other priorities. We look forward to fix those issues but AFAIK this is not on our short term timeline ATM (I might be wrong, though).

**Comment by Reinmar** [comment]
@jodator isn't this fixed in one of your PRs?

**Comment by jodator** [comment]
Looks like the issue should be fixed after closing all PRs of: https://github.com/ckeditor/ckeditor5-widget/pull/70. Basically it boils down to #1049.

The only change would be to mark `myTag` as an inline element:

```js
editor.model.schema.register( 'myTag', {
    allowWhere: '$text',
    allowContentOf: '$block',
    allowIn: '$text',
    allowAttributes: [ 'myTag', 'title', 'value' ],
    isObject: true,
    isInline: true // <- this will mark it as a text-like element
} );
```

I didn't check how the inserting contents will work inside there but if this would be non-editable element then it should be OK.
