### ISSUE TITLE
Docs issue report from "examples/builds/document-editor.html"

### ISSUE THREAD

**Issue by zhawzid-ottj** [ckeditor/ckeditor5#14264]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html

### Project version

38.0.1

### Is there anything else you would like to add?

replace all 
`.document-editor__editable.ck-editor__editable`
with just 
`.ck-editor__editable`

within the css then it also works with the React component as that one doesn't work with 
`.document-editor__editable.ck-editor__editable`
And I think with stripping that part of the path it's precise enough.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Thanks for reporting. This CSS is aligned with the HTML in the _View editor content listing_:

```html
<div class="document-editor">
    <div class="document-editor__toolbar"></div>
    <div class="document-editor__editable-container">
        <div class="document-editor__editable"> 
            Editor content is inserted here.
        </div>
    </div>
</div>

<!-- style definitions below -->
```

If you have a different HTML, the styles should be redefined to fit your classes/ids.
