### ISSUE TITLE
自定义上传适配器 上传失败后编辑框不会清除对应的文件，而且编辑框不能编辑

### ISSUE THREAD

**Issue by zhyit** [ckeditor/ckeditor5#1428]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

ckeditor5-build-classic": "^11.2.0"

## 📋 Steps to reproduce

根据官网自定义上传适配器，由于后台限制上传文件的大小，所以会返回错误信息
  class MyUploadAdapter {
     constructor(loader) {
       this.loader = loader;
     }
    
   upload() {
      return new Promise((resolve, reject) => {
        // let size = this.loader.file.size;
        // if (size / 1024 > 2048) {
        //   reject("图片不能大于2M");
        // }
        const genericErrorText = 'can not upload file: ' + this.loader.file.name;
        const data = new FormData();
        const config = {
          headers: {'content-type': 'multipart/form-data'}
        };
        data.append('imageFile', this.loader.file);
        axios.post('xxxxxx', data, config).then(res => {
          if (res) {
            if (res.data.code == 200) {
              resolve({
                default: res.data.data
              });
            } else {
              return reject(res.data.msg);
            }
          } else {
            return reject(genericErrorText);
          }
        }).catch(error => {
          return reject(error)
        });
      }).catch(error => {
        console.log(error);
      });
    }

    abort() {
    }
  }
function MyCustomUploadAdapterPlugin( editor ) {
    editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
      // Configure the URL to the upload script in your back-end here!
      return new MyUploadAdapter( loader );
    };
  }

## ✅ Expected result
报错时编辑框清除对应的上传文件

## ❎ Actual result
没有清除对应的上传文件，而且编辑框不能编辑,并且控制台会报“Cannot read property 'default' of undefined” 这个错误

**Comment by scofalik** [comment]
Please create an issue in English.
