### ISSUE TITLE
Getting error in console

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5#14298]
ROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'rootName')
TypeError: Cannot read properties of undefined (reading 'rootName')
    at eval (ckeditor.js:5626:254)
    at eval (ckeditor.js:820:225)
    at i (ckeditor.js:827:1)
    at Zi._setUpBindToBinding (ckeditor.js:845:1)
    at Object.using (ckeditor.j

Other error is 

ROR TypeError: Cannot read properties of undefined (reading 'setData')
    at eval (ck-editor.component.ts:60:29)
    at ZoneDelegate.invokeTask (zone.js:421:1)
    at Object.onInvokeTask (core.js:4747:1)
    at ZoneDelegate.invokeTask 

How to resolve these?

Thanks in Advance

**Comment by Witoso** [comment]
> Cannot read properties of undefined (reading 'setData')

This means that js doesn't have access to the `editor`. Either editor is not initialized, or the reference to it is not proper.

**Comment by Tiru150837** [comment]
I initialized it . The editor is working for some plugins . And for some it is not working

**Comment by Witoso** [comment]
We need more information on the setup of the editor, plugins, etc. As far as I remember you're previous tickets ,your editor's version was v28. We cannot unfortunately debug such an old version, and we recommend an update.
