### ISSUE TITLE
Find and replace feature

### ISSUE THREAD

**Issue by addsimm** [ckeditor/ckeditor5#1430]
🆕 Feature request

## CKEditor 5

as the title says ..

I googled around and looked in the docs, but nothing on document search

if not how can I / we make one?

Thanks!

---

If you'd like this feature to be introduced add 👍  to this ticket.

**Comment by oleq** [comment]
Hi @addsimm! There's no such feature in CKEditor 5. And quite likely you're the first one to request it so we're gonna keep track of thumbs-ups here in this issue.

Anyway: 
* Could you tell us what would the users of your app use the feature for? (in other words: what's the use-case?) 
* What would you like to see in this feature? Just find or find&replace? What options?
* Have you used the [Find/Replace](https://ckeditor.com/cke4/addon/find) plugin in CKEditor 4 before? If so, what was it like to use it? (OK/so–so/total distaster)

As for the implementation, we'd probably use the [markers API](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#markers
) to highlight the results and the [`TreeWalker`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html#function-getWalker) to traverse the model to search for matches.

Slightly related https://github.com/ckeditor/ckeditor5/issues/1257.

cc @Reinmar

**Comment by Reinmar** [comment]
This feature requires https://github.com/ckeditor/ckeditor5/issues/1257.

**Comment by mlewand** [comment]
🎉 We published the feature today as [@ckeditor/ckeditor5-find-and-replace npm package](@ckeditor/ckeditor5-find-and-replace) 🎉

We deployed it to our docs, so you can give it a try in [our latest find and replace feature guide](https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html).

Fixed with 2528e72.
