### ISSUE TITLE
Allow URLs with custom protocols to be linkable using Link plugin

### ISSUE THREAD

**Issue by mikkicom** [ckeditor/ckeditor5#14304]
## 📝 Provide a description of the improvement
The improvement I'd like to propose is adding the ability to customize which URL protocols the Link plugin considers safe so that URLs using them are properly linked in the Link Balloon and take the user to the intended destination upon clicking. 

_How the feature works now and what you'd like to change_?

Currently, the Link Balloon relies a `SAFE_URL` regex to determine if a link, upon click, should take the user to the set URL, or to `#` 

```js
const SAFE_URL = /^(?:(?:https?|ftps?|mailto):|[^a-z]|[a-z+.-]+(?:[^a-z+.:-]|$))/i;
```

Because the list of "safe" protocols are baked into the `SAFE_URL` regex, URLs using uncommon protocols such as `tel`, cannot be linked.

In order to address this, there could be an option added to the link configuration that might look something like this: 

```js
<CKEditor
  config={{
    link: {
      safeUrlProtocols: 'https?|ftps?|mailto|tel' // or alternatively ['http', 'ftp', 'mailto', 'tel']
    }
  }}
/>
```

With this approach, the regex currently used to determine if a URL is safe might be replaced with a function that receives `safeUrlProtocols` to dynamically build and return a regex. 

## 📃 Other details

* Browser: All
* OS: All
* CKEditor version: All
* Installed CKEditor plugins: Link, AutoLink

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the detailed request, we will gather the interest for it.

**Comment by Witoso** [comment]
Another case that could be added, mentioned in #11855, is `sms`.

**Comment by Witoso** [comment]
+13 👍 for `tel`: [#1019](https://github.com/ckeditor/ckeditor5/issues/1019).

**Comment by Witoso** [comment]
+43 👍 from #8248

**Comment by arglgruml** [comment]
+1 
AFAIU ckeditor is used in OpenProject. We need to link to different internal applications. These use custom URL schemes.

https://community.openproject.org/projects/openproject/work_packages/52674/activity
