### ISSUE TITLE
Border color parser does not work correctly in some cases

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#14309]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables.html
2. Choose any cell in table
3. Go to cell properties
4. Choose style of border and define width e.g. "5px"
5. Paste this "hsl( 0, 100%, 50% )" into color input for borders

### ✔️ Expected result

<img width="579" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/cb4352fc-a27b-4018-ba00-bdaa14035439">

### ❌ Actual result

<img width="563" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/84e1a784-dd47-4fd7-a80f-1d3e69208552">

-------------------------------

Look, if we remove spaces in color format like this "hsl(0, 100%, 50%)" instead "hsl( 0, 100%, 50% )" it works well.

[screen-capture (2).webm](https://github.com/ckeditor/ckeditor5/assets/47000454/a08cc3fd-72ff-4cd9-93f8-1c81eb1bc8a8)

Problem is actually in this part of code.

https://github.com/ckeditor/ckeditor5/blob/8ac3b11ef6370958e295f9d4adb50af2eebe15a8/packages/ckeditor5-engine/src/view/styles/utils.ts#L251-L256

So for `'hsl( 0, 100%, 50% )'` it returns array `[ 'hsl(' , ',0, 100%, 50%', ')' ]`

<img width="813" alt="Screenshot 2023-06-01 at 13 46 27" src="https://github.com/ckeditor/ckeditor5/assets/47000454/65131ade-b5e5-4c61-b705-e3cadfcecd2a">

It suppose to parse few colors for border (top, bottom, left and right) like:
`getShorthandValues( 'red blue RGB(0, 0, 0)');` -> `[ 'red', 'blue', 'RGB(0, 0, 0)' ]` 

### ❓ Possible solution

`return Array.from( string.matchAll( /rgb\([^\)]+\)|hsl(a)?\([^\)]+\)|(#)?\w+/gi ) ).map( i => i[ 0 ] );`

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
The more general regex from the refinement call `\w+\([^)]+\)|(#)?\w+`. Should work with colors and with stuff like

```
calc(10vh - 50px) min(30vh, 100px)
```
(margins, paddings).
