### ISSUE TITLE
Paste Plain Text

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5#14303]
Is there any other possibility to change the ctrl+shift+V shortcut to the ctrl+v to paste the plain text without formatting?

I want ctrl+v instead of ctrl+shift+v .

If there is possibility , what files I need to change?

I am using CKEditor5-28.0.0

Thanks in Advance

**Comment by Witoso** [comment]
Here's an example of how to handle a clipboard differently: https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/clipboard.html#handling-clipboard-input-differently. And there's [paste as plain text plugin example](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/clipboard.html#paste-as-plain-text-plugin-example).

**Comment by lasivtech** [comment]
This worked for me :) 

`<CKEditor
        editor={Editor}
        onReady={(editor: any) => 
        {
          editorRef2.current = editor;
          editor.plugins.get("ClipboardPipeline").on("inputTransformation", (evt: any, data: any) => 
          {
            const { dataTransfer } = data;
            const content = dataTransfer.getData("text/plain");
            data.content = editor.data.htmlProcessor.toView(content);
          });
        }}  
      />`

**Comment by Tiru150837** [comment]
@lasivtech ..Thank you so much..Now it is working as expected

**Comment by Witoso** [comment]
Thanks @lasivtech for the code example! :+1:
