### ISSUE TITLE
Allow urls with protocols to be auto-linkable using the AutoLink plugin

### ISSUE THREAD

**Issue by mikkicom** [ckeditor/ckeditor5#14316]
## 📝 Provide a description of the improvement
The improvement I'd like to propose is adding the ability to provide additional URL protocols to the AutoLink plugin so that a wider variety of URLs can be automatically linked.

_How the feature works now and what you'd like to change_?

At the moment, the AutoLink plugin uses a regex to determine if a URL should be automatically linked, which currently only matches http(s) and ftp URLs.

Because of this, URLs with uncommon protocols such as `tel`, cannot be automatically linked.

In order to address this, there could be an option added to the autolink configuration that might look something like this: 

```js
<CKEditor
  config={{
    autolink: {
      autoLinkableUrlProtocols: 'https?|ftp?|tel' // or alternatively ['https', 'ftp', 'tel']
    }
  }}
/>
```

With this approach, the regex currently used to determine if a URL should automatically linked might be replaced with a function that receives `autoLinkableUrlProtocols` to dynamically build and return a regex.

## 📃 Other details
* Browser: All
* OS: All
* CKEditor version: All
* Installed CKEditor plugins: AutoLink

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Merging with: #14304.
