### ISSUE TITLE
Docs issue report from "examples/builds/multi-root-editor.html"

### ISSUE THREAD

**Issue by umitturkyilmaz** [ckeditor/ckeditor5#14328]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/multi-root-editor.html

### Project version

38.0.1

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

**Comment by Witoso** [comment]
@umitturkyilmaz please specify what's the issue.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
