### ISSUE TITLE
Change highlight affects previous text

### ISSUE THREAD

**Issue by moyuanhuang** [ckeditor/ckeditor5#1433]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor
```
    "@ckeditor/ckeditor5-alignment": "^10.0.4",
    "@ckeditor/ckeditor5-basic-styles": "^10.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^11.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^11.0.2",
    "@ckeditor/ckeditor5-essentials": "^10.1.3",
    "@ckeditor/ckeditor5-highlight": "^10.0.4",
    "@ckeditor/ckeditor5-link": "^10.1.0",
    "@ckeditor/ckeditor5-list": "^11.0.3",
    "@ckeditor/ckeditor5-paragraph": "^10.0.4",
```

## 📋 Steps to reproduce
![ckeditor](https://user-images.githubusercontent.com/14947870/50546155-efc43c00-0bd7-11e9-971b-89c2d9304c2a.gif)

1. Select a highlight style `styleA` and type something
2. change the highlight style to `styleB`

## ✅ Expected result
The following things you type should be highlighted as `styleB`, while the previous typed text shouldn't be affected

## ❎ Actual result
Change of highlight actually affects previous text to change

**Comment by oleq** [comment]
Hi @moyuanhuang! What you see has been implemented by design. 

But maybe we should reconsider and apply some different behavior at the boundaries of highlighted regions or event implement a 2–step–caret–movement (typing around links) like we [did in case of the Link feature](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#typing-around-links).

cc @dkonopka @Reinmar

**Comment by moyuanhuang** [comment]
@oleq Thanks for the explanation! IMO, I feel like the way it works now it's inconvenient: once you choose a marker and start typing, you can't change the highlight on the same line at will, you'd have to break the line and go back to change it. I kinda expected a implementation that allows me to change the   highlight without extra operations (hit `enter` and go back for example).

**Comment by jodator** [comment]
> That makes sense (inside). But what about the boundaries?

It seems that we didn't think about such cases (typing with highlight on and changing a highlight as you type). I worry that adding two-step caret movement would complicate this feature too much. Also I'm not sure if such use-case is valid in terms of how this feature is described. But adding two-step caret movement looks like a way to go for solving this issue so I'm not against it - just raising a concern about possible bugs that it could bring ;).

ps.: If we implement the text/bg color plugin it probably will act differently in such cases.

**Comment by oleq** [comment]
> I worry that adding two-step caret movement would complicate this feature too much.

I agree.

> ps.: If we implement the text/bg color plugin it probably will act differently in such cases.

👍
