### ISSUE TITLE
Language config not affecting the findAndReplace and the sourceEditing plugin language

### ISSUE THREAD

**Issue by dpankratz96** [ckeditor/ckeditor5#14344]
## 📝 Provide detailed reproduction steps (if any)

1. Set 'de' as language in the config
2. Open the find and replace popup

1. Look at the sourceEditing toolbar icon

### ✔️ Expected result

All texts in the popup are in german.
The sourceEditing toolbar icon has the text "Quellcode"

### ❌ Actual result

All texts in the popup are in english.
The sourceEditing toolbar icon has the text "Source"

## 📃 Other details

* Browser: Chrome
* OS: Win10
* First affected CKEditor version: 5
* Installed CKEditor plugins: FindAndReplace, SourceEditing

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Unfortunately, I cannot reproduce it. The fresh install from the [online builder](https://ckeditor.com/ckeditor-5/online-builder/) has a correct localization:

![image](https://github.com/ckeditor/ckeditor5/assets/9881379/33e63aa6-0fb0-4fc8-97ea-91241be6c1b3)

Please make sure you [correctly set up translations.](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#loading-additional-languages-from-cdn-npm-and-a-zip-file)
