### ISSUE TITLE
Implement the block toggling

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#14348]
## 📝 Provide a description of the new feature

Pressing the toolbar button should execute the command that will toggle the visibility of the blocks.

**Comment by mlewand** [comment]
*   Pressing the toolbar button should execute the command that will toggle the visibility of the blocks.
*   Let's abide to the desings from [#14290 (comment)](https://github.com/ckeditor/ckeditor5/issues/14290#issuecomment-1573388162)
    *   Ensure that blocks that are part of widget layout (e.g. `div`) **are not** showing up as `div` blocks.
    *   Labels can be generated at runtime using SVG as mentioned in [#9398 (comment)](https://github.com/ckeditor/ckeditor5/issues/9398#issuecomment-1564865207).
*   Let's handle just basic elements:
    *   'p', 'div', 'pre', 'address', 'blockquote', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ul', 'ol', 'section'

**Comment by pszczesniak** [comment]
Resolved in #14373
