### ISSUE TITLE
Adding a paragraph between list items with enter removes style from the list after paragraph

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#14349]
## 📝 Provide detailed reproduction steps (if any)

1. Add a list with few items
2. Apply a style from styles dropdown to the list
3. Place caret in the end of the first item and press enter(return) twice

### ✔️ Expected result

A paragraph will be inserted between two list items, list made from the part of the list after paragraph will retain its styles

### ❌ Actual result

Styles get removed from the list after the paragraph.
If the paragraph is pasted instead of added via pressing enter twice, the styles remain on the list after the pasting as well

https://github.com/ckeditor/ckeditor5/assets/66953380/056067b8-7539-4b3a-8eca-b5b0d11d7918

## 📃 Other details

* Likely connected to https://github.com/ckeditor/ckeditor5/issues/14346
* First affected CKEditor version: current `master` branch. Behavior on v38.0.1:

https://github.com/ckeditor/ckeditor5/assets/66953380/f15d397b-3f9b-4af9-bbb4-49bd77c2fcf3

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
The same effect can be obtained by removing the list from any of the list items:

https://github.com/ckeditor/ckeditor5/assets/32898551/279ff48f-1c21-4c65-b384-ee5355050bcc
