### ISSUE TITLE
Don't close DropdownView when interacting with scrollbars

### ISSUE THREAD

**Issue by Anamon** [ckeditor/ckeditor5#14364]
## 📝 Provide a description of the improvement

Currently, if the content of a `DropdownView` exceeds its size and scrollbars are shown, trying to interact with those scrollbars using the mouse will close the dropdown (without any action being triggered).

The behaviour seems to have been added in commit 633dead6b6d1a2d8deedd08ae47ea6d0de83092e – I assume for accessibility, because closing the dropdown on `blur` ensures that it will close if focus is moved away from it e.g. using the Tab key. If I remove the listener on the `blur` event of the dropdown, it stays open when using the Tab key to move away the focus. On the other hand, even with the `blur` event listener disabled, the dropdown will still close correctly if the user clicks outside of the dropdown with the mouse, or selects one of the elements of the dropdown.

The improvement I'd like to see is for mouse interaction with a scollbar that is part of the `DropdownView` to not trigger the `blur` handler, so the list can be proberly scrolled by dragging the scrollbar slider or clicking one of the scrollbar buttons. Currently, a dropdown view's content can only be scrolled using the keyboard arrow keys, or the scroll wheel of the mouse.

Here's a screencast to visualise. In it, I first scroll the dropdown using the cursor keys (work fine), then using the mouse wheel (works fine), then by trying to drag the scrollbar slider (closes the dropdown), and finally by trying to click a scrollbar stepper (closes the dropdown).
https://github.com/ckeditor/ckeditor5/assets/517549/0a5735a9-e020-4dc9-a5bc-a547a1ca255c

## 📃 Other details

* Browser: tested on Firefox 114.0, Chrome 114.0.5735.110, and Edge 114.0.1823.41
* OS: Windows 10 x64 (10.0.19044 Build 19044)
* CKEditor version: 38.0.1
* Installed CKEditor plugins: Track Changes, Comments, some custom ones (including custom toolbar elements)

Since our custom UI dropdowns can contain lists whose length exceeds the height of the element containing CKEditor (and well exceeds common screen size), we allow scrollbars in dropdowns through CSS:

```
.ck.ck-reset.ck-list {
    overflow-y: auto;
}
```

I assume that this is a pretty common requirement and setup.

Currently, since for our users it's much more imporant that the scrollbars can be interacted with properly, than keyboard focus changes behaving properly, I worked around the issue by simply removing the `closeDropdownOnBlur()` function from `ckeditor5-ui/src/dropdown/utils.ts` in our fork of CKEditor code, but of course this is not ideal.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks @Anamon for the report! I will change the issue type to bug.

**Comment by niegowski** [comment]
This is happening because the `panelView` of the dropdown is not focusable (missing `tabindex="-1"` attribute) on the panel DOM element. DOM element is already added to the `FocusTracker` here:

https://github.com/ckeditor/ckeditor5/blob/48e43b36638e2dcc52aa1da3837e84594f0e051b/packages/ckeditor5-ui/src/dropdown/dropdownview.ts#L251-L252

It could be reproduced in any dropdown by adding `overflow-y: auto; max-height: 200px` to any dropdown. Note that on MacOS to make it happen you need to enable scrollbars in system settings:

![Screenshot 2023-06-26 at 12 54 51](https://github.com/ckeditor/ckeditor5/assets/1232187/ac2e90be-d5d0-4c74-b643-013128cb69ff)
