### ISSUE TITLE
inserted item is surrounded by span with :before HTML object

### ISSUE THREAD

**Issue by reeveng** [ckeditor/ckeditor5#14370]
## 📝 Provide detailed reproduction steps (if any)

- can't provide a detailed reproduction, although, I heard from a colleague he had a similar issue with adding a div
-  I added the `<Iframe />` plugin, but now when I insert an Iframe, I always get this weird `<span class="html-object-embed ck-widget" data-html-object-embed-label="HTML object" contenteditable="false">` surrounding my element, see image:
<img width="432" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/36441093/1fe1f9a5-1e9b-471c-9d8b-bd032b008288">

- I already added the `iframe` to the html support config and am aware that ckeditor doesn't offer the `iframe` functionality at the moment.

### ✔️ Expected result

For there to not be a span around it, ruining my otherwise beautiful page 🙃 

### ❌ Actual result

<img width="432" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/36441093/1fe1f9a5-1e9b-471c-9d8b-bd032b008288">

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: chrome, firefox, all of them, since its not a browser related thing
* OS: windows 11, latest
* Installed CKEditor plugins: 
- adapter-ckfinder
- ckeditor5-alignmen
- ckeditor5-autoformat
- ckeditor5-basic-styles
- ckeditor5-block-quote
- ckeditor5-ckbox
- ckeditor5-ckfinder
- ckeditor5-cloud-services
- ckeditor5-easy-image
- ckeditor5-editor-decoupled
- ckeditor5-essentials
- ckeditor5-font
- ckeditor5-heading
- ckeditor5-image
- ckeditor5-indent
- ckeditor5-link
- ckeditor5-list
- ckeditor5-media-embed
- ckeditor5-paragraph
- ckeditor5-paste-from-office
- ckeditor5-table
- ckeditor5-typing
- ckeditor5-iframe

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by reeveng** [comment]
> Hey, thanks for the report. Could you show the converters for your custom plugin? Most likely in your [downcast pipeline](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/conversion/downcast.html#downcast-pipelines) you should drop the `span` in the data view and it should only show in the editing view.

Thanks for the quick response! I am using [this plugin](https://github.com/FTRPRF/ckeditor5-iframe), and I believe that this should be the correct file https://github.com/FTRPRF/ckeditor5-iframe/blob/main/src/IframeEditing.js ?

Thanks in advance!

**Comment by Witoso** [comment]
Yep, so this line is the problem:

https://github.com/FTRPRF/ckeditor5-iframe/blob/ee106e837bb28cfdcba858be3149cc69fb1dd3f6/src/IframeEditing.js#LL45C9-L45C9

It outputs the iframe as a widget to the editing view as well as to the data output. It should be split into two downcasts `editingDowncast` and `dataDowncast`.

**Comment by reeveng** [comment]
I'll create a PR to fix it 👍 , thanks for helping out!
