### ISSUE TITLE
Docs issue report from "features/collaboration/users.html"

### ISSUE THREAD

**Issue by ahmedelhadi** [ckeditor/ckeditor5#14375]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/users.html

### Project version

38.0.1

### Is there something missing in the guide? What is it?

How can i set the users list from my side ?

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
As the guide suggests, you need to create your own plugin, that fetches the users from your database, and then use the `Users` plugin to add them.

```js
    init() {

        const myDbUsers = getMyDatabaseUsers() // <-- this is what you need to create

        const users = this.editor.plugins.get( 'Users' );

        // Provide user data from your database. For example:
        myDbUsers.map( user => users.addUser( user ) )
      

        // Define the local user.
        users.defineMe( 'u1' );
    }
}



```
