### ISSUE TITLE
Why i got a message error Error [TypeError]: domDocument.createElement is not a function nextjs in CKEditor5-engine

### ISSUE THREAD

**Issue by nguyenvuhoang** [ckeditor/ckeditor5#14387]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
It's extremely hard to help here without any description or details. Please file a proper issue.
