### ISSUE TITLE
Feedback loop in color picker in table properties

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#14389]
## 📝 Provide detailed reproduction steps (if any)

Visually everything is fine.

Problem actually is in color format which our table property apply to model. When we type **HEX** value into input we expect **HEX** value in model, but color picker listens on input to reflect actual color and it converts into **HSL**. Table property also listen on color picker changes and apply value in model.

### ✔️ Expected result

<img width="464" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/b3500735-9913-4872-9615-f8dab4ae45fb">

<img width="320" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/958d293e-8964-48be-b3b6-eb631e848b9d">

### ❌ Actual result

<img width="464" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/b3500735-9913-4872-9615-f8dab4ae45fb">

<img width="453" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/dd0fb195-d6db-467e-84f6-7c6b82a27179">

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Closed in #14416.
