### ISSUE TITLE
Table content is rendered differently in Chrome & Firefox

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#14386]
## 📝 Provide detailed reproduction steps (if any)

1. use firefox
2. go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html
3. use cke5-inspector to set data
4. paste in **set editor data** this content:
`<figure class="table" style="width:100%;"><table class="ck-table-resized"><colgroup><col style="width:4.57%;"><col style="width:4.56%;"><col style="width:4.56%;"><col style="width:39.11%;"><col style="width:47.2%;"></colgroup><tbody><tr><td>111111</td><td>222222</td><td style="width:400px;">999999</td><td>sample text</td><td>sample text</td></tr></tbody></table></figure>`

### ✔️ Expected result

<img width="1260" alt="Screenshot 2023-06-14 at 13 17 40" src="https://github.com/ckeditor/ckeditor5/assets/47000454/63312dc6-fdcd-4d3f-8b43-047a23411d57">

### ❌ Actual result

![Screenshot 2023-06-14 at 13 17 25](https://github.com/ckeditor/ckeditor5/assets/47000454/eb987278-8ef5-45d1-a3f0-9001f084a10f)

### ❓ Possible solution

Define `overflow-wrap: breaking-word` in `table` package.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Let's wait with closing the issue until the PR gets merged :slightly\_smiling\_face:
