### ISSUE TITLE
How can we restrict sha values in ckeditor 5 while adding content security policy header

### ISSUE THREAD

**Issue by PriyankaTalapaneni** [ckeditor/ckeditor5#14381]
## 📝 Provide detailed reproduction steps (if any)

1. …Added ckeditor5(v 38.0.1) in javascript project 
2. …Added content security policy header
3. …After adding content security policy header while running the javascript project sha values are generating in bulk number
4. How can we restrict the sha values 

### ✔️ Expected result
should restrict genarating sha values

### ❌ Getting these issues while running
![image](https://github.com/ckeditor/ckeditor5/assets/136562041/d4fcb596-d8b4-43c2-8357-0414981d23c6)

Added this Script
<script src="https://cdn.ckeditor.com/ckeditor5/38.0.1/inline/ckeditor.js"></script>

Please respond ASAP
@AnnaTomanek 
@jacekbogdanski 
@Mgsy 
@oleq

**Comment by Witoso** [comment]
Please check [our documentation about the Content Security Policy](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/csp.html), and set it accordingly.

**Comment by Witoso** [comment]
Could you show what's the CSP that server returns?

**Comment by PriyankaTalapaneni** [comment]
"default-src 'none';font-src 'self'; script-src 'self'  https://cdn.ckeditor.com;img-src * data: ; style-src 'self'; style-src-attr 'unsafe-inline'; object-src 'none'; connect-src 'self'; frame-src 'self'; frame-ancestors 'self';

these details I am using in content security policy header in my javascript project  

I am getting bulk number sha values and ckeditor issue
<img width="953" alt="CSPIssue" src="https://github.com/ckeditor/ckeditor5/assets/136562041/8d8951b6-ecbd-4517-bfa8-528bcc8d0aa6">

please check and respond ASAP @Witoso

**Comment by PriyankaTalapaneni** [comment]
If I put 'unsafe-inline' for style-src I am getting below issues
![image](https://github.com/ckeditor/ckeditor5/assets/136562041/b7638fd9-6ff7-4ad3-8a1a-7567306f8840)

can you please check @Witoso

**Comment by Witoso** [comment]
All needed information is here: [Content Security Policy](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/csp.html). It fails on several scripts that are not related to CKEditor. Please spend some time and read more about [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
