### ISSUE TITLE
blockedkeystroke is available in ckeditor 5??

### ISSUE THREAD

**Issue by pranavmappoli** [ckeditor/ckeditor5#14394]
I have seen this link [blockedkeystroke ](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-blockedKeystrokes), which is useful to block some keyactions. Is there any method available in CK-editor 5 for blocking some key action like cntr+z etc ?

**Comment by Witoso** [comment]
Something like this could be used
```jsx
editor.editing.view.document.on( 'keydown', ( event, data ) => {
        if ( data.keyCode === 46 || data.keyCode === 8 ) {
            event.stop();    
            data.preventDefault();
        }
}, { priority: 'high' } );
```

Another example of blocking keystrokes:
```js
editor.keystrokes.set( 'Ctrl+B', ( evt, cancel )=> {
		evt.preventDefault();
		evt.stopPropagation();
		cancel();
}, { priority: 'high' } );
```

There's also a [Keystroke handler](https://ckeditor.com/docs/ckeditor5/latest/framework/architecture/ui-library.html#keystroke-handler).
