### ISSUE TITLE
Implement inlining mechanism

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14402]
There's a [reference stylesheet parsing implementation in CKE4](https://github.com/ckeditor/ckeditor4/blob/4ec334ebc8ed38a935406b87044c1c1b0788eaa4/plugins/pastetools/filter/common.js#L539).

*   Parse CSS stylesheets in data transfer.
*   Inline them into `data.body` tree.
*   Test coverage - basic, make sure the implementation works.
*   Filter out MSO styles.

Note:

There's no need for full fledged CSS selector parsing (we don't have anything like that in our view lib implementation). Given that selectors in Office-produced content are simple we need to only handle two selector cases:

*   element name (only) (`p`)
*   element name + class (`p.MsoNormal`)
*   class only (e.g. `.MsoNormal`)

KISS, let's just implement simple handling for these cases.

**Comment by pszczesniak** [comment]
Solved in cksource/ckeditor5-internal#3380
