### ISSUE TITLE
Selected color is not propagated to the color table and color picker

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#14415]
## 📝 Provide detailed reproduction steps (if any)

Only present at [ck/epic/2978-integrate-color-picker-with-tables](https://github.com/ckeditor/ckeditor5/tree/ck/epic/2978-integrate-color-picker-with-tables).

1.  Put selection in a table cell with cell background color set.
2.  Open color picker in the table cell properties.

### ✔️ Expected result

Currently selected color is marked.

### ❌ Actual result

No color is marked, the "Remove color" button is focues.

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/14455.
