### ISSUE TITLE
Polish `ColorPickerViewConfig` type

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#14417]
## Provide a description of the task

Concerns [ck/epic/2978-integrate-color-picker-with-tables](https://github.com/ckeditor/ckeditor5/tree/ck/epic/2978-integrate-color-picker-with-tables).

Currently there's `ColorPickerConfig` and `ColorPickerViewConfig`. The latter has an extra prop: `hideInput`, which is actually not accessible for the user to configure. They are also inconsistently used in the codebase, e.g. here: [https://github.com/ckeditor/ckeditor5/blob/c0b8afaa050d157260df25046085f1d86620626d/packages/ckeditor5-ui/src/colortable/colortableview.ts#L850](https://github.com/ckeditor/ckeditor5/blob/c0b8afaa050d157260df25046085f1d86620626d/packages/ckeditor5-ui/src/colortable/colortableview.ts#L850) the `colorPickerConfig` property is indicated to have the type of `ColorPickerViewConfig`, not `ColorPickerConfig`.

I think there are two ways we can go:

1.  Stick with two types. Clean up the codebase to be consistent. Think about the name for `ColorPickerViewConfig` that won't indicate it can be configured in editor creator.
2.  Merge the types. Make `hideInput` configurable for the user with defaults of `true` for table and `false` for font packages.

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

**Comment by oleq** [comment]
I went with two types and addressed this in [0860e66](https://github.com/ckeditor/ckeditor5/pull/14491/commits/0860e661eaf97620846bb646611914f89c55934c).
