### ISSUE TITLE
Pagination module automatically skips a page with large tables which results in bad representation in the exported pdf

### ISSUE THREAD

**Issue by Noeeeeeee** [ckeditor/ckeditor5#14426]
When a large table is added, the pagination module automatically skips a page, whereas this is not the case in pdf. 
In other words, the pagination module doesn't handle tables optimally.

<img width="949" alt="Capture d'écran 2023-06-20 104910" src="https://github.com/ckeditor/ckeditor5/assets/91610776/4c17fb9f-e18a-4ef8-9415-05fbc840bf0a">

https://ckeditor.com/docs/ckeditor5/latest/features/pagination/pagination.html

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thank you for the report, I changed it to a bug, and not docs issue.

**Comment by spacelist-ca** [comment]
@Witoso is this being resolved?

**Comment by Witoso** [comment]
Not yet, it is on our bug fixing queue, as a workaround explicit page breaks can be used.

**Comment by spacelist-ca** [comment]
@Witoso  > Not yet, it is on our bug fixing queue, as a workaround explicit page breaks can be used.

How do you insert a pagebreak into a table? The issue is a single table extends over multiple pages and the pagination doesn't handle that case. 

Can you explain the workaround a bit more?

**Comment by Witoso** [comment]
Adding a page break before and after a long table may help align export to PDF to the editor's content. Just as the content in the linked demo.

**Comment by Noeeeeeee** [comment]
> Adding a page break before and after a long table may help align export to PDF to the editor's content. Just as the content in the linked demo.

If you insert 6 extra lines in the table on the demo, even if you put a page break before and after the table, the pagination indication is buggy and doesn't reflect reality when the PDF is generated.

**Comment by Noeeeeeee** [comment]
> Try this CSS fix
> 
> ```
> .ck-content .table table {
>   height: unset !important;
>   width: unset !important;
> }
> ```

Doesn't seem to correct the problem...

**Comment by spacelist-ca** [comment]
@Witoso This is a pretty major piece of having pagination be a working premium feature. Essentially pagination doesn't meet basic success criteria at this time, as even in your demo you have tables that are showing pagination incorrectly placed. How can this be expedited to be resolved? If you look at MS Word or GDocs you can see how it splits the table, and per your own website, "This placement is calculated using intelligent algorithms, which effortlessly handle the complexity of images and tables (for example, it avoids breaking table cells)." That unfortunately is not how your pagination plugin currently works.

**Comment by Witoso** [comment]
@spacelist-ca we're currently discussing this internally. While the plugin is functional, it's important to note that it's designed for the HTML, and thus, might not fully align with the functionalities of MS Word and Google Docs (which operate on blank canvas). We'll explore potential enhancements to address this.

**Comment by spacelist-ca** [comment]
@Witoso The pagination is simply a visual marker, it's not actually 'cutting' or 'splitting' the content (like MS-Word/GDocs), so it should be working as an 'overlay' instead of part of the Document HTML itself. No?

Maybe you can share why the pagination markers are jumping to before/after tables instead of being displayed 'over' them? The concept and purpose of pagination is to visualize where natural page breaks are based on the configuration set for that document (i.e, 8.5"x11" page size). But the pagination plugin isn't respecting that...and especially when combined with the premium PDF Export plugin things are very inconsistent and create a poor/confusing user experience.

Maybe pagination should become a free plugin for the community to help improve in the interim?

**Comment by Witoso** [comment]
If you have more questions regarding this, feel free to reach to our [support](https://ckeditor.com/contact/) :) We don't plan to share details or open the source of this plugin. We are aware of its corner cases, and will try to improve them over time.

**Comment by stevenrai** [comment]
Any updates on this issue and a potential solution? We have noticed that the pagination jumps whenever a table spans parts of two pages (can have a little on the first page and then more on the second page) leading to the pagination jumping to the top of the table everytime - which is inaccurate to the exported pdf. 


https://github.com/ckeditor/ckeditor5/assets/89600027/437f2be8-9e56-44cf-851c-2d43092a6fc3

**Comment by Mati365** [comment]
**Debug notes:**

1. Works fine on Firefox

**Comment by Mati365** [comment]
@Noeeeeeee / @spacelist-ca I think I fixed the issue. Please check [comment](https://github.com/ckeditor/ckeditor5/issues/14426#issuecomment-2205687266) above.

**Comment by spacelist-ca** [comment]
@ckeditor how come @Mati365 comment was deleted? If it's a valid fix we'd love to see it!

**Comment by spacelist-ca** [comment]
> @spacelist-ca we are testing the fix, and it has some internal feature info that we usually don't share. Fix and PR is being prepared by our team, so stay tuned.

Amazing to hear! Looking forward to a quick deployment, this bug has been frustrating for users for a long time!
