### ISSUE TITLE
Docs issue report from "api/module_engine_conversion_downcasthelpers-DowncastHelpers.html"

### ISSUE THREAD

**Issue by wongjn** [ckeditor/ckeditor5#14438]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-elementToStructure

### Project version

38.0.1

### Is the information outdated? How?

> The `slorFor()` function can also take a callback that allows filtering which children of the model element should be converted into this slot.

Could see or find any other mention of the mentioned `slorFor()` function – could this be a typo?

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Thanks for the report! It's a typo, should be `slotFor`. Will try to fix it asap.

**Comment by niegowski** [comment]
This should be `createSlot()`.

**Comment by Witoso** [comment]
My bad... I was pretty sure `slotFor` existed :face\_exhaling:. Fixing...

**Comment by Witoso** [comment]
Fixed.
