### ISSUE TITLE
Feedback loop while color dropdown is open in table properties

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#14432]
## 📝 Provide detailed reproduction steps (if any)

You could reproduce this behaviour on this `epic`: https://github.com/ckeditor/ckeditor5/tree/ck/epic/2978-integrate-color-picker-with-tables

1. Go to http://localhost:8125/ckeditor5-table/tests/manual/tableproperties.html
2. Choose any cell in table
3. Click on `cell properties button` ( <img width="20" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/31880376-03f1-4ce1-85e1-5654e2a11966"> )
4. Type in background color input any **HEX** value e.g. `#ffaaff`
5. Next to input will be button with color panel  (<img width="25" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/b8e61a6a-ba12-42d5-8daa-ba091552dac3"> ), click on it
6. Click on `color picker button` ( <img width="22" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/ef22348d-9bc5-425b-a66d-f67a9f5cc6ee"> )
7. Start choosing any color
8. Click on `cancel button` ( <img width="14" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/4ee5df3e-6e42-4969-901f-2e355c6776a0"> )

### ✔️ Expected result

In model on this cell should be applied **HEX** value as it was

<img width="367" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/1effccd7-b96a-4244-b36c-441196d70323">

### ❌ Actual result

<img width="434" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/47000454/c46663d9-ef34-4799-ac57-825d8f9ab468">

----------------------------

The same problem with `remove color button`, so when we set default color, e.g. ( `rgb(255,0,0)` ) and after color changes and removing color it will apply in model color in **HSL** format or that format which was defined in color picker as output.

This problem is directly related with **feedback loop** which was partially resolved by this PR: https://github.com/ckeditor/ckeditor5/pull/14416
But it was temporarily fix, we need something more generic and bulletproof solution which cover all cases.  

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/14455.
