### ISSUE TITLE
Infinite post-fixer loop after pressing enter in a nested list item

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#14434]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Type: `* a` <kbd>Enter</kbd> <kbd>Tab</kbd> `b` <kbd>Enter</kbd>

### ✔️ Expected result

Created a second nested list item.

### ❌ Actual result

Infinite post-fixer loop. Browser tab frozen.

## 📃 Other details

* Browser: any
* OS: …
* First affected CKEditor version: nightly
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/14441.
