### ISSUE TITLE
Inline element drag and drop

### ISSUE THREAD

**Issue by pranavmappoli** [ckeditor/ckeditor5#14444]
I have created a custom  plugin as show in the image. I can add the object with class "placeholder". `<span class="placeholder">Loop-ANS(Q2)</span>` .

inline widget created from
 [Created from](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html)

<img width="661" alt="Screenshot 2023-05-08 at 11 27 43 AM" src="https://user-images.githubusercontent.com/25036043/236745436-b436fb9e-e0ef-412f-8cb2-9128952fc5f6.png">

Now when someone remove this from the editor i need to generate an event (call a function) so that i can mark this item has removed in my redux state. I got a solution for this with the code below.

```
editor.model.document.on( 'change:data', () => {  // Listen to all changes in model.
	// Get changes buffered in Differ. Include items moved to the graveyard (removed from document).
	const changes = editor.model.document.differ.getChanges( { includeChangesInGraveyard: true } );

	for ( const change of changes ) {
		// Check items moved to the graveyard (so they are removed from the document root).
		if ( change.type == 'insert' && change.name != '$text' && change.position.root.rootName == '$graveyard' ) {

			// The element that we are looking for could be nested in some block-quote or a table cell
			// so we need to walk through the whole element content and check if our element was removed or not.
			const range = editor.model.createRangeOn( change.position.nodeAfter );

			for ( const item of range.getItems() ) {
				if ( item.is( 'element', 'imageInline' ) ) { // Here you change the value to your element's name.
					console.log( 'inline image removed', item ); // (**I will add a callback here**)
				}
			}
		}
	}
} );
```
The issue is, when i try to drag and drop the inline-widget, that time also it is considered as removed. ie, the element is moving to Graveyard, which shouldn't.
Is there any way to prevent this ? the placeholder not to move on gravyard while drag and drop to other position. Or to check the event is generated due to drag and drop and not call the callback.

If it is not possible, any way to stop the drag n drop event of inline widget

**Comment by Witoso** [comment]
Please don't create duplicated issues as it will not result in a faster response from our side (https://github.com/ckeditor/ckeditor5/issues/14053#issuecomment-1596607723). We are aware of your comment, and will try to help when we finish other topics. Consider our commercial support if you want to get a faster response time.
