### ISSUE TITLE
[Internal] Improve writing tests using TypeScript

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14451]
There are two issues with writing tests using TypeScript:

* `chai` globals like `expect()` are not declared in TypeScript, so it raises an error,
* TypeScript tests use the same eslint rules as the source code, raising issues when importing from `src/..` paths or relatively from other packages.

**Comment by psmyrek** [comment]
Done in:
- https://github.com/ckeditor/ckeditor5-linters-config/pull/23
- https://github.com/ckeditor/ckeditor5-dev/pull/895
- https://github.com/ckeditor/ckeditor5/pull/14452
