### ISSUE TITLE
Docs issue report from "features/read-only.html"

### ISSUE THREAD

**Issue by sabreu-teknorix** [ckeditor/ckeditor5#14450]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html#common-api

### Project version

38.0.1

### Is there anything else you would like to add?

how do I have the editor open in readonly mode?
This is for ReactJS

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.55

**Comment by Witoso** [comment]
Check our react demo [https://github.com/ckeditor/ckeditor5-react/tree/master/demo-react-18](https://github.com/ckeditor/ckeditor5-react/tree/master/demo-react-18), there's an implementation of read-only in [`EditorDemo`](https://github.com/ckeditor/ckeditor5-react/blob/master/demo-react-18/src/EditorDemo.tsx).
