### ISSUE TITLE
Color picker in table and cell properties doesn't display on iOS

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#14468]
## 📝 Provide detailed reproduction steps (if any)
Reproducible at `ck/14415-selected-color-propagation)`
1.  Open e.g. http://localhost:8125/ckeditor5-table/tests/manual/tableproperties.html
2.  Tap a table to open table or cell properties 
3.  Open the color selection modal
4.  Tap the "color picker" button

### ✔️ Expected result

Color picker opens upon tapping the button

### ❌ Actual result

Color picker doesn't open, nothing happens:

https://github.com/ckeditor/ckeditor5/assets/132071257/1394f5d3-8f1d-4168-a795-386dadb8e933

## 📃 Other details

*   Probably related with #14462

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This is the same issue as https://github.com/ckeditor/ckeditor5/issues/14462.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/14474.
