### ISSUE TITLE
Infinite loop while in source editing mode

### ISSUE THREAD

**Issue by corymharper** [ckeditor/ckeditor5#14469]
Note: I originally opened this, and still have the issue open in the `@ckeditor/ckeditor5-react` repo [here](https://github.com/ckeditor/ckeditor5-react/issues/391). I believe the solution lies most likely in this repository at this point, but it might lie somewhere between both.

## 📝 Provide detailed reproduction steps (if any)

*Warning: These steps cause an infinite loop in the browser*

1. Run `yarn start` locally after cloning [this repository](https://github.com/corymharper/ckeditor5-source-editing-bug) and visit the URL indicated by the command, or visit the [Github Pages website](https://corymharper.github.io/ckeditor5-source-editing-bug/#/).

2. Open the browser console.

2. Enter any text into the displayed editor.

3. Switch to "source editing" mode using the toolbar.

4. Make any change to the text in the editor now that source editing is active.

5. The infinite loop may have already started, if it has you will see that displayed in the console, otherwise hit the submit button and it should start.

I used React Router for the reproduction because in my tests it was the most consistent way to reproduce the problem.

### ✔️ Expected result

No infinite loop.

### ❌ Actual result

An infinite loop.

### ❓ Possible solution

See https://github.com/ckeditor/ckeditor5-react/issues/391#issuecomment-1608462386 for some detailed thoughts/observations but no definite solution yet.

## 📃 Other details

* Browser: Google Chrome Version 114.0.5735.133 (Official Build) (arm64)
* OS: Mac OSX 13.3.1
* First affected CKEditor version: Whichever version source editing was released, probably?
* Installed CKEditor plugins: My example's editor only uses the source editing plugin.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
For now, we will take a look at it in the React repo.

**Comment by niegowski** [comment]
This issue can be reproduced without React and without the Watchdog. This happens when there is a listener for data change:
```js
editor.model.document.on( 'change:data', () => {
	console.log( 'data changed:', editor.getData() );
} );
```
And it's enough to trigger an infinite loop when triggering `editor.getData()` while in source editing mode with any content modification.

**Comment by niegowski** [comment]
This should be fixed by adding:

```js
this._dataFromRoots.set( rootName, newData );
```

below this line:

https://github.com/ckeditor/ckeditor5/blob/d7c24d06330bdc1f7cee7f811520c390e371e866/packages/ckeditor5-source-editing/src/sourceediting.ts#L204
