### ISSUE TITLE
Error ckeditor-duplicated-modules when add plugin in Next JS (Type Script)

### ISSUE THREAD

**Issue by p-jirayusakul** [ckeditor/ckeditor5#14470]
## 📝 Provide detailed reproduction steps (if any)

1. install @ckeditor/ckeditor5-react, @ckeditor/ckeditor5-build-classic, @ckeditor/ckeditor5-source-editing
![package.json](https://i.ibb.co/drpHsK8/Ckeditor.png)
2. add SourceEditing to CKEditor component
```
import { CKEditor } from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import { SourceEditing } from "@ckeditor/ckeditor5-source-editing";

interface CKeditorProps {
  onChange: (data: string) => void;
  value: string;
}

export default function CKeditor({ onChange, value }: CKeditorProps) {
  return (
    <CKEditor
      editor={ClassicEditor}
      data={value}
      onChange={(_, editor: ClassicEditor) => onChange(editor.getData())}
      config={{
        plugins: [SourceEditing],
        toolbar: ["sourceEditing"],
      }}
    />
  );
}
```
3. dynamic import to my page
```
"use client";
import { useState } from "react";
import dynamic from "next/dynamic";

const CEditor = dynamic(() => import("./CKeditor"), {
  ssr: false,
});

export default function Home() {
  const [data, setData] = useState<string>("");

  return (
    <>
      <CEditor
        onChange={(data: string) => {
          setData(data);
        }}
        value={""}
      />
      {JSON.stringify(data)}
    </>
  );
}
```

### ✔️ Expected result

Get the editor and working with sourceEditing

### ❌ Actual result

None of the solution works properly

### ❓ Possible solution

Make the implementation of the Source Editing plugin

## 📃 Other details

* Browser: Google Chrome
* OS: MacOS Ventura 13.4.1
* First affected CKEditor version: 38.0.1
* Installed CKEditor plugins: 38.0.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks @p-jirayusakul for the report, [as the error page states](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules), you **you must never add plugins to an existing build** unless your plugin has no dependencies. Adding plugins to a build is done by taking the source version of this build (so, before it was built with webpack) and adding plugins there. In this situation, webpack will know that it only needs to load each plugin once. Read more in the [Installing plugins](https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html) guide.
