### ISSUE TITLE
Image contextual toolbar is missing when integrating ckeditor5 classic-build from online builder to Angular project

### ISSUE THREAD

**Issue by Mike20403** [ckeditor/ckeditor5#14490]
1.Here's my ckeditor.js 
![image](https://github.com/ckeditor/ckeditor5/assets/57946382/8d793192-a060-4439-9be1-c42793d7fff0)
![image](https://github.com/ckeditor/ckeditor5/assets/57946382/bb0905e3-67a6-4e25-9cf2-3057a35b3c57)
![image](https://github.com/ckeditor/ckeditor5/assets/57946382/5d09016d-d5bb-49ae-8c6a-e7fb9bddabe1)
![Uploading image.png…]()

2. Here's how i setup my editor : 
![image](https://github.com/ckeditor/ckeditor5/assets/57946382/7b058bf3-2e5a-454a-9c91-482a4af5762f)
![image](https://github.com/ckeditor/ckeditor5/assets/57946382/999aa2d9-ae22-4276-a636-22ec7a4d3421)

### ❌ Actual result:  Image toolbar on the sample test which generated from online builder all works fine but when integrate to angular apps the image toolbar is missing somehow
![image](https://github.com/ckeditor/ckeditor5/assets/57946382/5f7bc823-4c8c-490c-ab10-7ff1eff95446)

## 📃 Other details

* Browser: Brave
* OS: Window
* First affected CKEditor version:![image](https://github.com/ckeditor/ckeditor5/assets/57946382/7daaaa9d-c622-42c8-ac05-14742acb45e1)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@Mike20403 I assume the problem was solved, as [you commented on the other issue](https://github.com/ckeditor/ckeditor5/issues/7446#issuecomment-1619386894). Closing for now. Let me know if it works for you.

**Comment by Mike20403** [comment]
> @Mike20403 I assume the problem was solved, as [you commented on the other issue](https://github.com/ckeditor/ckeditor5/issues/7446#issuecomment-1619386894). Closing for now. Let me know if it works for you.

thanks you, it works now
