### ISSUE TITLE
🚀 CKEditor 5 nightly releases

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#14502]
I’d like to announce that starting today, the CKEditor 5 project will publish its nightly version.

A version of nightly packages matches the following pattern: `0.0.0-nightly-YYYYMMDD.X`, where:

* `YYYYMDD` represents a current date, e.g., `20230630`,
* `X` is the sequential number starting from 0.

Nightly packages are being built directly from the `#master` branch and land to npm under the `@nightly`  [distribution tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag).

Releases will be created daily, so integration tests using nightly packages might fail. Please create an issue in the CKEditor 5 issue tracker in such a case. We may have merged a regression, and our tests did not catch it.

To avoid a mess in the [CKditor 5 release page](https://github.com/ckeditor/ckeditor5/releases), we did not generate the changelog for a nightly release or create a release page.

We appreciate any feedback that will help us improve the project's final form.

<img width="749" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/2270764/ab7c14f1-aa78-4615-a702-1fa26a0cd1cd">

**Comment by wimleers** [comment]
🙏 👏 

This means Drupal is now able to get a heads-up long before a CKEditor 5 release! 🤝 

**Semi-automated testing of nightly CKEditor 5 releases in Drupal: https://www.drupal.org/project/drupal/issues/3379104 🚀**
