### ISSUE TITLE
Selection on Chrome behaves differently when paragraph or heading is placed above a widget vs when it's not 

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#14507]
## 📝 Provide detailed reproduction steps (if any)

1.  Open e.g. [http://localhost:8125/ckeditor5/tests/manual/all-features.html](http://localhost:8125/ckeditor5/tests/manual/all-features.html) or https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2.  Click three times on a paragraph or heading that **is** placed right above a widget
3.  Click three times on a paragraph or heading that **is not** placed right above a widget

### ✔️ Expected result

The result after steps 2. and 3. is the same - the whole paragraph or heading is selected 

### ❌ Actual result

After the third click, the result differs between steps 2 and 3:  

- if the paragraph/heading is above a widget (step 2.), it doesn't show as selected
- if the paragraph/heading is not above a widget (step 3.), it shows as selected 

https://github.com/ckeditor/ckeditor5/assets/132071257/ca0b0feb-6840-40c2-b6b5-0b3d234356ed

## 📃 Other details

*   Browser: Chrome
*   OS: MacOS
*   It's not a fresh regression

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/11130.
