### ISSUE TITLE
CKBox: Add support for workpaces

### ISSUE THREAD

**Issue by zaak** [ckeditor/ckeditor5#14504]
## 📝 Provide a description of the new feature

In the upcoming version 1.6.0 of CKBox, we are going to introduce the Workspaces feature. Workspaces create independent data spaces within the same website environment, which covers multiple scenarios, like private user spaces and support for multi-tenant applications. The REST API of this feature is already complete and the beta version is available in production, so we can start work on adding support for it in the CKBox plugin.

### 🔗 Buidling file URL-s

Until now, URL-s to files and responsive versions of images used `environmentId` ([1](https://github.com/ckeditor/ckeditor5/blob/6fa1dd3d44706a82b0342e16a78c4d2fb4aeba57/packages/ckeditor5-ckbox/src/ckboxcommand.ts#L406-L417), [2](https://github.com/ckeditor/ckeditor5/blob/6fa1dd3d44706a82b0342e16a78c4d2fb4aeba57/packages/ckeditor5-ckbox/src/utils.ts#L125-L137)). This has changed, and the `environmentId` has been replaced with `workspaceId` ([1](https://api.ckbox.io/api/beta/docs#tag/Assets/operation/getAssetFile), [2](https://api.ckbox.io/api/beta/docs#tag/Assets/operation/getImageHandler)).

The most optimal way would be using CKBox's JS API to obtain these URLs, but it is possible only when choosing assets directly from the CKBox dialog window. In case of uploads from the _Image_ feature, paste from the clipboard, or through D&D, the whole process is controlled by the CKEditor plugin itself.

From now on, **CKBox backend will return all the required URLs** in the API responses, so it won't be required to assemble them on the frontend side.

### ⬆️ Choosing workspace for uploads

In the case of uploads from the _Image_ feature or through D&D the whole process is controlled by the CKEditor plugin itself, so it must properly determine the workspace when [building the URL for upload](https://github.com/ckeditor/ckeditor5/blob/6fa1dd3d44706a82b0342e16a78c4d2fb4aeba57/packages/ckeditor5-ckbox/src/ckboxuploadadapter.ts#L232-L236).

To choose the workspace for upload, it is required to add the `workspaceId` parameter to the URL query, i.e. `POST /assets?workspaceId=XXXXXXXXXXXXX`.

### ⬇️ Fetching info about categories

As the plugin determines the target category to upload, it must [fetch the info about the available categories](https://github.com/ckeditor/ckeditor5/blob/6fa1dd3d44706a82b0342e16a78c4d2fb4aeba57/packages/ckeditor5-ckbox/src/ckboxuploadadapter.ts#L142-L145).

To obtain the list of categories for a workspace, it is required to add the `workspaceId` parameter to the URL query, i.e. `GET /categories?limit=500&workspaceId=XXXXXXXXXXXXX`. 

### ℹ️ How to obtain the `workspaceId`?

The list of available workspaces is defined in the `auth.ckbox.workspaces` of the JWT token payload:

```json
{
  "aud": "...",
  "sub": "...",
  "auth": {
      "ckbox": {
        "role": "user",
        "workspaces": [ "pHUSQFj_QIvc" ]
      }
  }
}
```

There might be multiple scenarios:

#### ➤ No `auth.ckbox.workspaces` defined

In this case `workspaceId` matches the `environmentId`. It can be either set in the `workspaceId` query param or skipped.

#### ➤ One workspace ID present in `auth.ckbox.workspaces`

If only one value is present in the list, it should be included in all the URLs mentioned above.

#### ➤ Multiple workspace IDs present in `auth.ckbox.workspaces`

This one is a little tricky because users in CKBox can have access to multiple workspaces and the plugin will not be able to determine the target workspace for files uploaded through _Image_, D&D, or paste from the clipboard.

I think the best option to cover this scenario is to introduce an option similar to [`defaultUploadCatgories`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ckbox_ckboxconfig-CKBoxConfig.html#member-defaultUploadCategories), which defines the categories to which the uploaded images will be assigned.

We can add `defaultUploadWorkspaceId` option controlling on the plugin level which workspace should be used in this case:

 - If `defaultUploadWorkspaceId` is not set, the first one from the `auth.ckbox.workspaces` should be used as a fallback.
 - If the `defaultUploadWorkspaceId` is not present on the list of workspaces in `auth.ckbox.workspaces`, an error should be thrown, just like we do in case when invalid category ID is provided in `defaultUploadCategories` ([1](https://github.com/ckeditor/ckeditor5/blob/6fa1dd3d44706a82b0342e16a78c4d2fb4aeba57/packages/ckeditor5-ckbox/src/ckboxuploadadapter.ts#L226-L230)).

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Todo:

1.  @Witoso create the flowchart of `defaultUploadWorkspaceId` and scenarios.
2.  Consult the case of the new editor integration supporting the old CKBox. In this case, integration needs to be able to work with not updated CKBox (e.g. on-prem). @zaak wdyt about this case?
3.  @zaak what's the timeline for the new upload endpoint/parameter to appear
4.  @zaak could you point to the staging implementation of the workspaces, etc.

**Comment by Witoso** [comment]
Scope of the issue:

1.  Add `defaultUploadWorkspaceId` configuration option to the `ckbox` config.
    *   If the `defaultUploadWorkspaceId` is not present on the list of workspaces in `auth.ckbox.workspaces`, an error should be thrown, just like we do in case when invalid category ID is provided in `defaultUploadCategories`.
2.  Change the **upload URL and category fetching** mechanism to include the `workspaceId`.
3.  `workspaceId` will be determined via the following method:

```mermaid
flowchart TB
id1{Is defaultUploadWorkspaceId\ndefined in config?}
id2{Are there values in\nauth.ckbox.workspaces?}
id3{Is there one or multiple values?}
Start -->id1
id1 -->|Yes|E[Use it as workspaceId]
id1-->|No|id2
id2-->|No|Env[In this case `workspaceId` matches\n the `environmentId`]
Env-->E
id2-->|Yes|id3
id3-->|One|O[Use the value provided]
O-->E
id3-->|Multiple|M[Fallback to the first one]
M-->E

```

4\. Change the mechanism of constructing urls to images. From now on, **CKBox backend will return all the required URLs** in the API responses, so it won't be required to assemble them on the frontend side.
