### ISSUE TITLE
PoweredBy is shown outside parent with overflow while scrolling horizontally.

### ISSUE THREAD

**Issue by pszczesniak** [ckeditor/ckeditor5#14524]
## 📝 Provide detailed reproduction steps (if any)

1.  Create a test case when editor has a parent with overflow (for example editor with set to 1000px and parent width to 300px)
2.  Focus the editor.
3.  Scroll horizontally

### ✔️ Expected result

_When "PoweredBy" is outside should not be visible._

### ❌ Actual result

https://github.com/ckeditor/ckeditor5/assets/7074833/f02252b3-088b-4d89-834d-6cb6fb6ecda2

### ❓ Possible solution

Extend the "visibility" check - now its only checks the vertical scrolling (height/top/bottom).

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
The code to fix: [https://github.com/ckeditor/ckeditor5/blob/c0d13553b3d3beea18cf6cf2c1add4868d5c20af/packages/ckeditor5-ui/src/editorui/poweredby.ts#L342-L361.](https://github.com/ckeditor/ckeditor5/blob/c0d13553b3d3beea18cf6cf2c1add4868d5c20af/packages/ckeditor5-ui/src/editorui/poweredby.ts#L342-L361.) In line 357 we need to take the horizontal rect into account. Remember about the "inside" position as well (check and fix if necessary).
