### ISSUE TITLE
Docs issue report from "framework/tutorials/implementing-an-inline-widget.html"

### ISSUE THREAD

**Issue by 2Who** [ckeditor/ckeditor5#14535]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html#final-solution

### Project version

36.0.1

### Is there something missing in the guide? What is it?

There are changes to the webpack.config.js missing, since adding the placeholder.css causes an error in the npm run build command:
```
ERROR in ./placeholder/theme/placeholder.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 
See https://webpack.js.org/concepts#loaders
```

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67

**Comment by Witoso** [comment]
I assume it may be related to the ckeditor/ckeditor5-react#395. Let's debug it there, and close it for now as I assume this is a setup issue, not the docs one.
