### ISSUE TITLE
Powered by logo considers only the first scrollable ancestor while managing visibility

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#14536]
## 📝 Provide detailed reproduction steps (if any)

![2023-07-06 11 52 39](https://github.com/ckeditor/ckeditor5/assets/1099479/48f3f602-4d76-46b2-853e-b072e1febc3a)

### ✔️ Expected result

It should hide when the outer ancestor is scrolled.

### ❌ Actual result

It stays visible but attached to the void.

### ❓ Possible solution

The problem is the logic considers the first scrollable ancestor only while it should consider all of them.

https://github.com/ckeditor/ckeditor5/blob/f72fdf4f406c2f5a9164f3f224002793944dd2e2/packages/ckeditor5-ui/src/editorui/poweredby.ts#L350-L361

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This issue will also be fixed by #14755
