### ISSUE TITLE
Can I use CKEditor as a RTE in my commercial app for free witthout attribution & without releasing my own source code ?

### ISSUE THREAD

**Issue by sandeep-kr-kgp** [ckeditor/ckeditor5#14537]
I'd like a simple and straightforward answer. License docs are way too confusing.

**Comment by Witoso** [comment]
@[sandeep-kr-kgp](https://github.com/sandeep-kr-kgp) thank you for your question. I really do understand your concerns regarding the conditions of GPL licensing. I would love to give you a simple and straightforward answer, however, the GPL requires every use case to be well understood and thoroughly analyzed in the spirit of the License.

Taking your use case into consideration, we can split the answer into two areas: “attribution” and “releasing your source code”. 

### Attribution 

There is no doubt that attribution needs to be provided. Such requirements can be found in Section 4 of the License: 

> “You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice” 

[Moreover, the GPL FAQ says is clear](https://www.gnu.org/licenses/gpl-faq.en.html#IWantCredit): 

> ‘(...) Part of releasing a program under the GPL is writing a copyright notice in your own name (assuming you are the copyright holder). The GPL requires all copies to carry an appropriate copyright notice.

### Releasing source code

If you decided to convey the product that contains the GPL-covered code to other users, the final product indeed must be published under the same (or compatible) license. So, [as per the Preamble of the GPL itself](https://www.gnu.org/licenses/gpl-3.0.en.html): 

> ‘(…) you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.’

So, yes, if you use a GPL library in a project that’s conveyed, the GPL requires that you make publicly available the source code of your entire project.

It's crucial to remember that the GPL is designed to foster a community of sharing and improvement. By honoring its principles, we not only comply with the legal requirements, but also contribute to a larger goal of open collaboration and continual advancement of technology. However, given the complexities of licensing laws and the GPL in particular, I'd highly recommend consulting a legal expert if you still have concerns. For now, we will not be responding individually to queries about this license topic on GitHub, but hope this explanation provides a thorough understanding of the general principles at play.
