### ISSUE TITLE
Fix warnings logged by yarn

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1454]
`yarn install` outputs:

```
warning "@ckeditor/ckeditor5-dev-tests > babel-loader@8.0.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "@ckeditor/ckeditor5-dev-tests > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
```

**Comment by ma2ciek** [comment]
Not sure about the first, but for the karma-webpack we need still to wait on the next release, as the karma@3.0.5 has `"webpack": "^2.0.0 || ^3.0.0"` in its peer deps (https://github.com/webpack-contrib/karma-webpack/blob/v3.0.5/package.json#L28)

**Comment by pomek** [comment]
> `warning "@ckeditor/ckeditor5-dev-tests > babel-loader@8.0.4" has unmet peer dependency "@babel/core@^7.0.0".`

It should disappear after releasing a new version of `@ckeditor/ckeditor5-dev-tests` package. With the second warning, we can do nothing on our side as @ma2ciek pointed out.
