### ISSUE TITLE
problems when dynamic load and delete ckeditor5-build-inline component with vue

### ISSUE THREAD

**Issue by muyi911** [ckeditor/ckeditor5#1456]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

@ckeditor/ckeditor5-build-inline

## 📋 Steps to reproduce

I want to create a new inline editor when I click button, and when mouse blurs, the inline editor can be deleted. But when mouse blurs,  the data in console is right, the content on page is in a wrong presentation.

First I add three lines
![image](https://user-images.githubusercontent.com/20811746/51071573-25fcc380-168e-11e9-8149-63d34f14329e.png)

Then I delete the  second line, the data is right. There are two elements, but the content is not correct. 
![image](https://user-images.githubusercontent.com/20811746/51071578-3dd44780-168e-11e9-98e1-1eab65a3e778.png)

![image](https://user-images.githubusercontent.com/20811746/51071584-5d6b7000-168e-11e9-9e25-97b5d7139b9a.png)

![image](https://user-images.githubusercontent.com/20811746/51071610-dd91d580-168e-11e9-9efa-784f184f267c.png)

### my code
child component:
```
<template>
  <ckeditor
    :editor="editor"
    v-model="editorData"
    :config="editorConfig"
    @blur="handleBlur"
  ></ckeditor>
</template>

<script>
import "../../plugins/ckeditor";
import InlineEditor from "@ckeditor/ckeditor5-build-inline";
import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";

export default {
  props: ["index", "inner"],
  components: {},
  data() {
    return {
      editor: InlineEditor,
      editorData: "",
      editorConfig: {
        plugins: [
          EssentialsPlugin,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin
        ],
        toolbar: {
          items: ["bold", "italic", "link", "undo", "redo"]
        }
      }
    };
  },
  mounted: function() {
 
  },
  watch: {
    editorData: function(curVal, oldVal) {
      this.$emit("change", this.index, curVal);
    }
  },
  methods: {
    handleBlur: function() {
      if (this.editorData == "" || this.editorData == "<p>&nbsp;</p>") {
        this.$emit("blur", this.index);
      }
    }
  }
};
</script>

```

parent component:
```
<template>
  <div
    class="draft"
    id="draft"
  >
    <button
      class="testbutton"
      @click="create('editor')"
    ></button>

    <component
      :id="item.id"
      :is="item.component"
      v-for="(item,index) in items"
      :key="index"
      :index="index"
      :inner="item.inner"
      @blur="destory"
      @change="update"
    ></component>
  </div>
</template>

<script>
import Editor from "../../components/editor/CKEditor";
export default {
  data() {
    return {
      items: [],
      i: 0
    };
  },
  components: {
    editor: Editor
  },
  methods: {
    create: function(name) {
      this.items.push({
        id: this.i + "",
        component: name,
        inner: ""
      });
      this.i = this.i + 1;
      console.log(JSON.stringify(this.items));
    },
    destory: function(n) {
      this.items.splice(n, 1);
      console.log(JSON.stringify(this.items));
    },
    update: function(n, data) {
      this.items[n].inner = data;
      console.log(JSON.stringify(this.items));
    }
  }
};
</script>

<style>
.testbutton {
  width: 50px;
  height: 30px;
}
</style>

```

**Comment by oleq** [comment]
I read your description and I'm not sure what is the expected result. What does

> the content on page is in a wrong presentation.

mean?

**Comment by muyi911** [comment]
I want to dynamically add an inline editor on the page. Here are my steps.

- I add 3 inline editors by clicking the button. 
- Then I deleted the second one ( Delete by judging that there is no content in the editor ), you can see that the second and third lines on the page are gone. 
- The output of the console and the dom on the web page look correct, but the value in the editor is not displayed correctly, I expect that there should be 1 and 3. 

It looks like the third editor was deleted or the value of the second editor is assigned to the third editor.

**Comment by oleq** [comment]
It this a CKEditor 5 bug or your application issue?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
