### ISSUE TITLE
Why do we have the `engine` property in pkg.json?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#14586]
## Provide a description of the task

As in the title. AFAIR, we have it from day 1.

https://github.com/ckeditor/ckeditor5/blob/26214b329d3c2904836d7c8657979349f9b4f9c4/package.json#L86-L89

However, I do not understand why need it. CKEditor 5 packages do not use Node features at all. Also, we do not use npm, except for publishing packages.

I believe we can drop the entire object, or for sure, the `npm` description if for some reason keeping `node` is valuable.

**Comment by Reinmar** [comment]
I think we could drop this, indeed.

I don't remember any reasons for including it. It might've been our eagerness to be safer. But we don't rely on any of the npm/node features ourselves. Our dependencies might (e.g. if you need webpack to build CKE5). But that should be included in their checks.

**Comment by pomek** [comment]
### Scope

* We agree to remove the `engine` property from all `ckeditor5-*` packages.
* Keeping the property in the development environment makes sense, as it points to a minimal version that a developer needs to run the CKEditor 5 project.
	* Drop the property While publishing the `ckeditor5` package on npm.
