### ISSUE TITLE
Right-Click Paste Option Limited to Selected Area

### ISSUE THREAD

**Issue by Kranthi32** [ckeditor/ckeditor5#14581]
Currently, the right-click paste option is only visible and accessible within the selected area of the editor. When a user attempts to right-click and paste outside of the selected area, the normal right-click options are displayed instead.

how to get the right click option in entire content Area. 

in below images highlighted mark outside of the selected area with in the content in that place normal options showing,

![image](https://github.com/ckeditor/ckeditor5/assets/99165841/f618fec4-c428-4601-ae10-54769d6c1141)
![image](https://github.com/ckeditor/ckeditor5/assets/99165841/5090ab87-d172-4cc8-bbcc-b1098bc4deb2)
<img width="960" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/99165841/b6c74e3f-68d1-4ec3-8166-7911e7bfcb65">

**Comment by Witoso** [comment]
Hi, the pictures you attached reflect the CKEditor 4 which is now in the EOL stage. This repository accepts only issues related to the CKEditor 5.
