### ISSUE TITLE
Mentions content is not displayed in HTML format

### ISSUE THREAD

**Issue by sreedhar-annam** [ckeditor/ckeditor5#14589]
## 📝 Provide detailed reproduction steps (if any)

1. We are using CKEditor 38.0.0 version.
2. Found issue when we use mentions in the project. We have configured mentions as **key:** mention1 **text**: 
![image](https://github.com/ckeditor/ckeditor5/assets/77439012/259d1ce6-1912-41b4-8fa2-5afd36f85d33)
3. When i select key mention1, text displaying with html tags instead of html content.

### ✔️ Expected result

![correct](https://github.com/ckeditor/ckeditor5/assets/77439012/301ab293-3ce7-4976-a75b-1d9324c09b07)

### ❌ Actual result

![wrong](https://github.com/ckeditor/ckeditor5/assets/77439012/95d96b16-7574-4870-8647-0aa09f34cf8a)

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
[Please read the section of the documentation that informs how to customize the output of the Mentions plugin.](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#customizing-the-output) The text in the configuration, as the name suggests, is for the text representation, not an HTML one.

**Comment by sreedhar-annam** [comment]
Text supposed to be converted as HTML content when it render to the UI
