### ISSUE TITLE
What's the recommended way of extending plugin features?

### ISSUE THREAD

**Issue by Juljus777** [ckeditor/ckeditor5#14588]
## 📝What's the recommended way of extending plugin features? 

As a developer who needs to extend the table plugin it would be really helpful if the documentation would include something about the possible ways of doing it. 

In CKEditor4 it was simple to add extra functionality by listening to events and extending the dialogs or updating the editor DOM directly but I've read from the documentation that it's not recommended way in CKEditor5. I tried extending the table plugin and ran into multiple problems and that made it seems as if extending plugins really shouldn't be done.

I also read from here (https://github.com/ckeditor/ckeditor5/pull/9864) that extending the table plugin is not possible yet. Is that still true?

**Comment by Juljus777** [comment]
Thank you for the answer. I managed to develop the plugin I needed. The extension I talked about was being able to change the tables output markup to include an overflow wrapper around the table so when the table becomes wider than the websites content area it gets a scrollbar so it would work on mobiles.

What tripped me up was that when I migrated some of the table plugin code over to my own plugin I thought that all the downcast converters would be in /converters folder. I didn't even consider searching for them anywhere else since I thought only one converter can be used for a model (there's something about that in the docs) which caused my viewmodel to have the correct wrapped tables but the actual output wouldn't since the converter that handles the final output was in the plaintableoutput.js and I hadn't overwritten it yet.

In the future I'll probably have to extend the plugin even more, like making it possible to add some custom data-attributes to the table and it's headings, so that I could integrate [sortable.js](https://github.hubspot.com/sortable/docs/welcome/), with my tables and add a custom color palette to the cell color picker. Haven't really looked into extending the UI/UX yet (hopefully wont be a headache) but it's probably possible to hack something together if its not directly supported.

**Comment by Witoso** [comment]
> In the future I'll probably have to extend the plugin even more, like making it possible to add some custom data-attributes to the table and it's headings, so that I could integrate [sortable.js](https://github.hubspot.com/sortable/docs/welcome/), with my tables and add a custom color palette to the cell color picker. Haven't really looked into extending the UI/UX yet (hopefully wont be a headache) but it's probably possible to hack something together if its not directly supported.

The UI part may get tricky, and a lot depends on the context of the feature. It's actually an area in which we plan to smoothen the experience. So when you start and catch some issues or problems, please let us know.
