### ISSUE TITLE
[Yarn] @ckeditor/ckeditor5-build-decoupled-document 404 when installing

### ISSUE THREAD

**Issue by avilesj** [ckeditor/ckeditor5#14590]
## 📝 Provide detailed reproduction steps (if any)

1. Make new directory
2. `yarn init`
3. `yarn add @ckeditor/ckeditor5-build-decoupled-document`

### ✔️ Expected result

_What is the expected result of the above steps?_
* The package installs.

### ❌ Actual result

_What is the actual result of the above steps?_
* A HTTP 404 is thrown because the package does not exists in the yarn registry.
* Request URL used by yarn [https://registry.yarnpkg.com/@ckeditor%2fckeditor5-build-decoupled-document
](https://registry.yarnpkg.com/@ckeditor%2fckeditor5-build-decoupled-document)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._
* Check if something happened in the publishing of this package in the yarn registry

## 📃 Other details

* Browser: N/A
* OS: MacOS
* First affected CKEditor version: 34.0.0
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
I'm uncertain if that was a temporal problem on the yarn's side, but right now, the URL you posted works, and doesn't 404.
