### ISSUE TITLE
I'm want to change cursor position but ; Cannot read property 'clone' of undefined getting error ; what is the cause of the error

### ISSUE THREAD

**Issue by hurkan-sert** [ckeditor/ckeditor5#1459]
var selection=editor.view.document.selection;
var start=0;
var end =4;

range = editor.view.writer.createRange( start, end ); /* error on this line  " Cannot read property 'clone' of undefined "*/
selection.setTo( range );

/* I don't know how to give the start and end parameters */

**Comment by scofalik** [comment]
1. You should operate on the model, not on the view.
2. You need to pass proper parameters (positions) not just numbers.
3. Please read documentation https://ckeditor.com/docs/ckeditor5/latest/framework/guides/overview.html and https://ckeditor.com/docs/ckeditor5/latest/api/index.html

**Comment by hurkan-sert** [comment]
okey I'm understand thank you.

**Comment by ajayshukla** [comment]
Here is the correct code if anyone interested to know:-

editor.model.change( writer => {
    writer.setSelection( editor.model.document.getRoot(), 'end' );
} );
