### ISSUE TITLE
Height restricted editor does not scroll when the text escapes into the overflow

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14606]
## 📝 Provide detailed reproduction steps (if any)

1. Open the online demo on https://ckeditor.com/ckeditor-5/demo/feature-rich/.
2. Apply `max-height: 200px` and `overflow: auto` on the `.ck-content` element.
3. Scroll to a position where the line of text is at the bottom of the editor viewport.
4. Type some text and watch it disappear in the overflow.
5. Pressing `Enter` or `Backspace` will fix the scroll position.

https://github.com/ckeditor/ckeditor5/assets/208610/1f46b3b2-60b4-4fe4-ba51-4c7655a310bf

### ✔️ Expected result

The editor should scroll when the caret escapes the visible part of the editor while typing.

### ❌ Actual result

No scrolling occurs unless specific actions like adding a new paragraph or hitting backspace is executed.

## 📃 Other details

* Browser: All browsers
* OS: Not OS specific
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Not relevant

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Duplicate: #13411.
