### ISSUE TITLE
Ckeditor 5 what to get cursor position and set again after replacing text.

### ISSUE THREAD

**Issue by hurkan-sert** [ckeditor/ckeditor5#1460]
I want cursor will be there, where the text is replaced. Is this possible?

**Comment by oleq** [comment]
Please use [StackOverflow or our Gitter channel](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/getting-support.html) for questions concerning editor API. This issue tracker is for bugs and feature requests only.
