### ISSUE TITLE
Support for Indenting entire code blocks

### ISSUE THREAD

**Issue by meichthys** [ckeditor/ckeditor5#14616]
## 📝 Provide a description of the new feature
It is often useful to add code blocks to a list, but the code blocks currently cannot be indented to the same indentation level as the list, and they interrupt the list numbering (i.e. codeblock after 3 causes numbering to return to 1)

Current:
![image](https://github.com/ckeditor/ckeditor5/assets/10717998/4526e2c8-317f-4e0b-9965-4d646d963545)

Proposed:
![image](https://github.com/ckeditor/ckeditor5/assets/10717998/cce6587f-dd53-4365-aab3-179ae23249c4)

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Blocks inside the lists are implemented in the [Document list](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html). It can be tested with code blocks in [the full-featured editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html). I hope it works for you!
