### ISSUE TITLE
Document lists should have a “simple list” config option

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14634]
As we decided to make the Document list the only plugin that introduces the lists, we need to add a config option that still allows creating simple lists.

### Why?

Integrators may want to allow simpler content editing, and block creation of blocks in the lists. We have a similar use case in our comments' system. You rarely may want to have a complex markup in small editors. etc.

### Scope

*   This option should be opt-in. By default, lists will allow blocks.
*   After setting this option
    *   I can only insert list items. Simplified data output `<ul><li>a</li><li>b</li></ul>` (for `ol` as well).
    *   Typing actions that we have in the document lists (e.g., enter+backspace creates a block) should work differently (as current lists).
*   Documentation.
    *   Simple list config in the feature.
    *   Release and update guide information.

**Comment by Witoso** [comment]
Refinement notes:

*   `forceDisable` approach with the command that merges blocks.
*   schema needs to change (e.g,. no heading in the list item).
*   postfixers: all id's in list items need to be unique.

**Comment by niegowski** [comment]
Should we deny multiple types of nested lists in a single list item? Shall simple list allow such structure or should it not (in legacy lists it was not possible):
```html
<ul>
    <li>
        a
        <ol>
            <li>
                b
            </li>
        </ol>
        <ul>
            <li>
                c
            </li>
        </ul>
    </li>
</ul>
```

**Comment by Witoso** [comment]
I don't see a reason why not. I see it as a good enhancement for the user that they can have a bulleted list and inside it have a numbered one. It still matches my definition of simple.

@Reinmar do you remember why Lists v1 didn't have it? Or was it only scope cutting?
