### ISSUE TITLE
[Drag & drop, intro] Improve the drop target line

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14645]
We want to improve the drop target line for both horizontal and vertical lines:

*   Symmetrical approach – arrow should also be added in the horizontal line, 
    * RTL, the arrow should be on the other side.
*   For darker background
    * The lines vertical and horizontal by default should be surrounded by the white stroke (0.5-1px).
    * Outline may be tricky to style, intersections, etc., SVG?
    * _Possible scope cut._
*   I should be possible to style both line color and the surrounding stroke by the CSS.

[Internal Figma file.](https://www.figma.com/file/B20B2kvXTDzzO0zvNZmPE4/Enhanced-drag-and-drop-of-block?type=design&node-id=13-755&mode=design&t=9mSNImGgnYAmLhXL-4)
---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@dagdzi very worthwhile comment from @niegowski, having half-pixels could look messy (antialiasing, and other subpixel rendering magic), and it would be better to use full pixels.

**Comment by dagdzi** [comment]
@Witoso In that case, I'd stick with the 2 px line. I think it will be more visible and consistent with the rest of the interface elements.
