### ISSUE TITLE
What's the right way to remove image upload via drag and drop ?

### ISSUE THREAD

**Issue by Joshuajrodrigues** [ckeditor/ckeditor5#14654]
## 📝 Provide detailed reproduction steps (if any)

I've seen many answers online, some no longer work, others seem to be for the old version. I dont need any form of image upload on my rich text editor. I managed to get rid of the toolbar button. but the drag and drop is tricky.
currently the way I'm doing this is
`
   removePlugins: ['ImageUploadEditing', 'ImageUpload', 'ImageInsert', 'Comment'],
`
this sadly on load throws an error saying
`
Uncaught CKEditorError: plugincollection-plugin-not-loaded {"plugin":"ImageUploadEditing"}
`
everything works fine, If I drag and drop an image it doesn't upload anything or throw errors but that uncaught error is kinda an issue 

### ✔️ Expected result

Should prevent image drag and drop in a clean way, or an official way

### ❌ Actual result

Throws annoying error

### ❓ Possible solution

Maybe provide this as a plugin ? Or a way to handle this error atlest

## 📃 Other details

* Browser: Chrome, Edge, Firefox
* OS: Windows
* First affected CKEditor version: 5
* Installed CKEditor plugins: 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey, just to clarify, you want to remove all image features from the editor, right? Which build are you using?

**Comment by Joshuajrodrigues** [comment]
Yup all image functionality from the classic build if possible

**Comment by Witoso** [comment]
TBH, in such case I suggest [creating your own build, with cherry-picked plugins.](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/installation/getting-started/quick-start-other.html#creating-custom-builds-with-online-builder) This would be the closest to "the official way". If you need some specific set of plugins, create your own build.
