### ISSUE TITLE
Firefox: Native spell checker only refreshes when the editor regains focus

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14657]
## 📝 Provide detailed reproduction steps (if any)

1. Visit https://ckeditor.com/ckeditor-5/demo/editor-types/ or any demo that does not include the paid spell checker plugin.
2. With a proper dictionary selected, write something that includes a typo. No errors are shown.
3. Blur the editor and move the focus back in, the typo is now marked as erroneous.
4. Fix the typo and notice that the error marker stays in place.
5. Blurring and focusing the editor again will refresh the spell check result once more.

https://github.com/ckeditor/ckeditor5/assets/208610/59203289-f7af-4f7f-8a05-7fdb90e95dab

### ✔️ Expected result

The native spell checker should run while you type, similar to how its work with native text input elements and vanilla `contenteditable`.

### ❌ Actual result

The native spell checker only runs when the editor is being focused.

## 📃 Other details

* Browser: Firefox 115.0.2
* OS: Confirmed on both macOS and Windows.
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Online demo without paid spell checker plugin

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@Mgsy and @ckeditor/qa-team, how would you classify this? I think it's upstream on WProofreader side, but I want to check with you.

**Comment by dtdesign** [comment]
@Witoso This isn’t about WProofreader at all but the native spell checker of the browser.

**Comment by Witoso** [comment]
Ok, sorry, I got confused :face\_exhaling:.

**Comment by cadeyrn** [comment]
@Witoso This issue was fixed by Mozilla in Firefox 118:

https://hg.mozilla.org/mozilla-central/rev/01837134e47e

**Comment by Witoso** [comment]
Confirmed, thank you, @cadeyrn, for the ping :bow:.
