### ISSUE TITLE
Unexpected behavior in splitting cells in certain tables

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#14658]
## 📝 Provide detailed reproduction steps (if any)

1. Pass the HTML attached to this issue to create a table with a certain layout or create one from scratch that resembles the one that you can see in the recording in `Actual result`
2. Try splitting the cell on the left side

### ✔️ Expected result

The cell should probably split in two, as is the case in CKE4:

https://github.com/ckeditor/ckeditor5/assets/72079603/c815a285-9f5d-49fc-a608-9f3807210bd7

### ❌ Actual result

The cell splits into multiple ones. The structure of the table is further altered and an additional column gets inserted on the right:

https://github.com/ckeditor/ckeditor5/assets/72079603/d472c5e1-72d0-4019-8b3f-f8701685b46c

### ❓ Possible solution

It might have something to do with the number of cells to the right of the cell that is being split. The smallest possible table configuration that reproduces this issue needs 7 rows and two columns. Notice that the issue doesn't appear when there are 6 rows:

https://github.com/ckeditor/ckeditor5/assets/72079603/a17d219c-d37e-47c8-8448-c90c2f76df40

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

[table_example.html.zip](https://github.com/ckeditor/ckeditor5/files/12161421/table_example.html.zip)

**Comment by Witoso** [comment]
Probably some rounding issue.

**Comment by 108signals** [comment]
@Witoso do you have any update on this issue? Our users are experiencing this fairly often as they use/paste complex tables. Also have a formal ticket on this [#88562](https://support.ckeditor.com/hc/requests/88562)

**Comment by Witoso** [comment]
Thanks for the question! We haven't started the investigation.
