### ISSUE TITLE
CI is red because of the scripting plublishing nightly docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1465]
https://travis-ci.org/ckeditor/ckeditor5/builds/479475326#L1105

![image](https://user-images.githubusercontent.com/156149/51250404-8fcee300-1996-11e9-8710-c579ef6ba4ad.png)

Something weird happens there.

**Comment by pomek** [comment]
```bash
node ./scripts/docs/build-docs.js --production
JSDoc started...
No errors found during the validation.
Documented 410 files!
(node:6987) UnhandledPromiseRejectionWarning: Error: Cannot find module 'hexo'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/ckeditor/ckeditor5/node_modules/umberto/hexo/hexo-shim.js:8:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
(node:6987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 21.88s.
```

That's the reason why this script stopped working.

**Comment by pomek** [comment]
We can't use yarn for installing mgit. I have no idea why it does not work. 

When I switched to `npm install mgit2`, it started working.

https://github.com/ckeditor/ckeditor5/compare/89046f0b4378...1839d1f8e676

**Comment by Reinmar** [comment]
It'd be good to learn why it does not work. Could you investigate it further? I saw some warnings regarding mgit in yarn logs on CI, so that should give you some ideas. Perhaps, since we're installing it twice (first via a separate `yarn add mgit2` and then when we call `yarn install`) there are some conflicts.

I can see in #1470 that you also added `rm -rf node_modules`. Doesn't this line alone fix this issue? Perhaps switching to `npm` isn't necessary.

**Comment by pomek** [comment]
It works – https://travis-ci.org/ckeditor/ckeditor5/builds/480847653.

But I added reset for `package.json` and `yarn.lock` because `yarn add`will modify it anyway.
