### ISSUE TITLE
CKEditor removes internal CSS

### ISSUE THREAD

**Issue by anchal04** [ckeditor/ckeditor5#14661]
Hi,

I am upgrading CKEditor from version 4 to 5.
When I paste any HTML and click on source button It ignores the internal style applied and render only plain html.

```
<style>
    .some-class {
      ...
     }
  </style>
  <div class = "some-class">
    ...
  </div>
```
Here, class style is ignored and div is rendered without style

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
The editor will not preserve the style, and will mark it as unsafe. We would recommend adding the styles to the page's head or CSS file.

There's a workaround (using [FullPage](https://ckeditor.com/docs/ckeditor5/latest/features/html/full-page-html.html) plugin), [that was proposed in one comment as a custom plugin](https://github.com/ckeditor/ckeditor5/issues/13482#issuecomment-1561232707).

**Comment by anchal04** [comment]
@Witoso Thanks for replying. I have checked this plugin [FullPage](https://ckeditor.com/docs/ckeditor5/latest/features/html/full-page-html.html) but its not supporting internal CSS.
Example
```
<html>
<head>
<style>
body {background-color: powderblue;}
h1   {color: blue;}
p    {color: red;}
</style>
</head>
<body>

<h1>This is a heading</h1>
<p>This is a paragraph.</p>

</body>
</html>
```
When I click on source, editor ignores style and render whatever is inside body.

Expected
<img width="848" alt="Screenshot 2023-08-03 at 3 09 04 PM" src="https://github.com/ckeditor/ckeditor5/assets/29730388/b72f2e2c-2ac0-4ee6-be8a-fe5af9e289e3">

Actual
<img width="765" alt="Screenshot 2023-08-03 at 3 09 25 PM" src="https://github.com/ckeditor/ckeditor5/assets/29730388/15da2a5a-ed77-4ff4-9921-ebacf6cd95cf">

**Comment by corey-Robinson1337** [comment]
> The editor will not preserve the style, and will mark it as unsafe. We would recommend adding the styles to the page's head or CSS file.
> 
> There's a workaround (using [FullPage](https://ckeditor.com/docs/ckeditor5/latest/features/html/full-page-html.html) plugin), [that was proposed in one comment as a custom plugin](https://github.com/ckeditor/ckeditor5/issues/13482#issuecomment-1561232707).

I used this workaround and it causes styles to "bleed" outside the editor. To me that solution isn't good enough to be promoting to solve the desired use.

**Comment by anchal04** [comment]
@Witoso I have tried this workaround for the [above html code](https://github.com/ckeditor/ckeditor5/issues/14661#issuecomment-1663642106) https://github.com/ckeditor/ckeditor5/issues/12838#issuecomment-1473417306
Only `script` is there inside` editor.editing.view.domConverter.unsafeElements`
<img width="1676" alt="Screenshot 2023-08-09 at 10 43 45 AM" src="https://github.com/ckeditor/ckeditor5/assets/29730388/92f6952f-9a61-428e-a07c-8c82fdf569fe">

**Comment by anchal04** [comment]
@Witoso yes it is enabled

**Comment by Witoso** [comment]
But does the config allows it? In the full configuration:

```
  allow: [
    {
      name: /.*/,
      attributes: true,
      classes: true,
      styles: true,
    },
  ],
```

`style` is under the `editor.editing.view.domConverter.unsafeElements`.

**Comment by Sherry-Lee** [comment]
Hi @Witoso,
I have tried the GeneralHtmlSupport as you provided above and the [workaround](https://github.com/ckeditor/ckeditor5/issues/12838#issuecomment-1473417306), but it still does not work in terms of keeping the class attribute.
Are there any updates on this issue?

**Comment by Witoso** [comment]
Did you add this function to plugins list of the editor?

**Comment by srav09** [comment]
Hi @Witoso,
I have added "RenderStyleElements" method to CKeditor config file.

`
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment.js';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat.js';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold.js';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor.js';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor.js';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily.js';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize.js';
import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport.js';
import Heading from '@ckeditor/ckeditor5-heading/src/heading.js';
import HorizontalLine from '@ckeditor/ckeditor5-horizontal-line/src/horizontalline.js';
import HtmlEmbed from '@ckeditor/ckeditor5-html-embed/src/htmlembed';
import Image from '@ckeditor/ckeditor5-image/src/image.js';
import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic.js';
import Link from '@ckeditor/ckeditor5-link/src/link.js';
import List from '@ckeditor/ckeditor5-list/src/list.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice.js';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat.js';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting.js';
import SpecialCharacters from '@ckeditor/ckeditor5-special-characters/src/specialcharacters.js';
import SpecialCharactersArrows from '@ckeditor/ckeditor5-special-characters/src/specialcharactersarrows.js';
import SpecialCharactersCurrency from '@ckeditor/ckeditor5-special-characters/src/specialcharacterscurrency.js';
import SpecialCharactersEssentials from '@ckeditor/ckeditor5-special-characters/src/specialcharactersessentials.js';
import SpecialCharactersLatin from '@ckeditor/ckeditor5-special-characters/src/specialcharacterslatin.js';
import SpecialCharactersMathematical from '@ckeditor/ckeditor5-special-characters/src/specialcharactersmathematical.js';
import SpecialCharactersText from '@ckeditor/ckeditor5-special-characters/src/specialcharacterstext.js';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough.js';
import Subscript from '@ckeditor/ckeditor5-basic-styles/src/subscript.js';
import Superscript from '@ckeditor/ckeditor5-basic-styles/src/superscript.js';
import Table from '@ckeditor/ckeditor5-table/src/table.js';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar.js';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation.js';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline.js';
import EditorWatchdog from '@ckeditor/ckeditor5-watchdog/src/editorwatchdog.js';
import InsertDropDown from '../src/ckeditor5-insertdropdown/src/insertdropdown.js';
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';
import { ImageUpload, ImageUploadUI, ImageResize } from '@ckeditor/ckeditor5-image';
import FullPage from '@ckeditor/ckeditor5-html-support/src/fullpage.js';
import HtmlComment from '@ckeditor/ckeditor5-html-support/src/htmlcomment.js';

class Editor extends ClassicEditor {}

function RenderStyleElements( editor ) {
	// Remove the 'style' name from the list of unsafe elements.
	const unsafeElements = editor.editing.view.domConverter.unsafeElements;
	const indexOfStyle = unsafeElements.indexOf( 'style' );

	if ( indexOfStyle > -1 ) {
		unsafeElements.splice( indexOfStyle, 1 );
	}
}

// Plugins to include in the build.
Editor.builtinPlugins = [
	Alignment,
	Autoformat,
	Bold,
	Code,
	Essentials,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	GeneralHtmlSupport,
	RenderStyleElements,
	Heading,
	HorizontalLine,
	HtmlEmbed,
	Image,
	Indent,
	Italic,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	RemoveFormat,
	SourceEditing,
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersMathematical,
	SpecialCharactersText,
	Strikethrough,
	Subscript,
	Superscript,
	Table,
	TableToolbar,
	TextTransformation,
	Underline,
	InsertDropDown,
	SimpleUploadAdapter,
	ImageUpload,
	ImageUploadUI,
	ImageResize,
	FullPage,
	HtmlComment
];

// Editor configuration.
Editor.defaultConfig = {
	toolbar: {
		items: [
			'undo',
			'redo',
			'|',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'subscript',
			'superscript',
			'removeFormat',
			'|',
			'sourceEditing',
			'|',
			'bulletedList',
			'numberedList',
			'outdent',
			'indent',
			'alignment',
			'|',
			'link',
			'|',
			'insertTable',
			'specialCharacters',
			'|',
			'heading',
			'fontFamily',
			'|',
			'fontColor',
			'fontBackgroundColor',
			'|',
			'insertDropDown',
			'imageUpload'
		]
	},
	language: 'en',
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	dropdownlist: [],
	htmlEmbed: {
		showPreviews: [ true ]
	},
	htmlSupport: {
        allow: [ 
		    { 
				name: /^(a|abbr|address|area|article|aside|audio|b|bdi|bdo|blockquote|br|button|canvas|caption|cite|code|col|colgroup|data|datalist|dd|del|details|dfn|dialog|div|dl|dt|em|fieldset|figcaption|figure|footer|form|h[1-6]|header|hr|i|img|input|ins|kbd|label|legend|li|link|main|map|mark|meter|nav|ol|optgroup|option|output|p|param|picture|pre|progress|q|rb|rp|rt|rtc|ruby|s|samp|section|select|small|source|span|strong|style|sub|summary|sup|table|tbody|td|template|textarea|tfoot|th|thead|time|tr|track|u|ul|var|video|wbr|head|html|center|body)$/,
				attributes: true,
				classes: true,
				styles: true
            } 
	    ]
    }
};


export default { Editor, EditorWatchdog };
`

But it still removes internal CSS. Any suggestions if anything is wrong here?

**Comment by srav09** [comment]
Hi @Witoso,
I have added "RenderStyleElements" method to CKeditor config file.

`
/**
 * 
 * 
 */
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment.js';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat.js';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold.js';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor.js';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor.js';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily.js';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize.js';
import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport.js';
import Heading from '@ckeditor/ckeditor5-heading/src/heading.js';
import HorizontalLine from '@ckeditor/ckeditor5-horizontal-line/src/horizontalline.js';
import HtmlEmbed from '@ckeditor/ckeditor5-html-embed/src/htmlembed';
import Image from '@ckeditor/ckeditor5-image/src/image.js';
import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic.js';
import Link from '@ckeditor/ckeditor5-link/src/link.js';
import List from '@ckeditor/ckeditor5-list/src/list.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice.js';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat.js';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting.js';
import SpecialCharacters from '@ckeditor/ckeditor5-special-characters/src/specialcharacters.js';
import SpecialCharactersArrows from '@ckeditor/ckeditor5-special-characters/src/specialcharactersarrows.js';
import SpecialCharactersCurrency from '@ckeditor/ckeditor5-special-characters/src/specialcharacterscurrency.js';
import SpecialCharactersEssentials from '@ckeditor/ckeditor5-special-characters/src/specialcharactersessentials.js';
import SpecialCharactersLatin from '@ckeditor/ckeditor5-special-characters/src/specialcharacterslatin.js';
import SpecialCharactersMathematical from '@ckeditor/ckeditor5-special-characters/src/specialcharactersmathematical.js';
import SpecialCharactersText from '@ckeditor/ckeditor5-special-characters/src/specialcharacterstext.js';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough.js';
import Subscript from '@ckeditor/ckeditor5-basic-styles/src/subscript.js';
import Superscript from '@ckeditor/ckeditor5-basic-styles/src/superscript.js';
import Table from '@ckeditor/ckeditor5-table/src/table.js';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar.js';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation.js';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline.js';
import EditorWatchdog from '@ckeditor/ckeditor5-watchdog/src/editorwatchdog.js';
import InsertDropDown from '../src/ckeditor5-insertdropdown/src/insertdropdown.js';
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';
import { ImageUpload, ImageUploadUI, ImageResize } from '@ckeditor/ckeditor5-image';
import FullPage from '@ckeditor/ckeditor5-html-support/src/fullpage.js';
import HtmlComment from '@ckeditor/ckeditor5-html-support/src/htmlcomment.js';

class Editor extends ClassicEditor {}

function RenderStyleElements( editor ) {
	// Remove the 'style' name from the list of unsafe elements.
	const unsafeElements = editor.editing.view.domConverter.unsafeElements;
	const indexOfStyle = unsafeElements.indexOf( 'style' );
	if ( indexOfStyle > -1 ) {
		unsafeElements.splice( indexOfStyle, 1 );
	}
}

// Plugins to include in the build.
Editor.builtinPlugins = [
	Alignment,
	Autoformat,
	Bold,
	Code,
	Essentials,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	GeneralHtmlSupport,
	RenderStyleElements,
	Heading,
	HorizontalLine,
	HtmlEmbed,
	Image,
	Indent,
	Italic,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	RemoveFormat,
	SourceEditing,
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersMathematical,
	SpecialCharactersText,
	Strikethrough,
	Subscript,
	Superscript,
	Table,
	TableToolbar,
	TextTransformation,
	Underline,
	InsertDropDown,
	SimpleUploadAdapter,
	ImageUpload,
	ImageUploadUI,
	ImageResize,
	FullPage,
	HtmlComment
];

// Editor configuration.
Editor.defaultConfig = {
	toolbar: {
		items: [
			'undo',
			'redo',
			'|',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'subscript',
			'superscript',
			'removeFormat',
			'|',
			'sourceEditing',
			'|',
			'bulletedList',
			'numberedList',
			'outdent',
			'indent',
			'alignment',
			'|',
			'link',
			'|',
			'insertTable',
			'specialCharacters',
			'|',
			'heading',
			'fontFamily',
			'|',
			'fontColor',
			'fontBackgroundColor',
			'|',
			'insertDropDown',
			'imageUpload'
		]
	},
	language: 'en',
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	dropdownlist: [],
	htmlEmbed: {
		showPreviews: [ true ]
	},
	htmlSupport: {
        allow: [ 
		    { 
				name: /^(a|abbr|address|area|article|aside|audio|b|bdi|bdo|blockquote|br|button|canvas|caption|cite|code|col|colgroup|data|datalist|dd|del|details|dfn|dialog|div|dl|dt|em|fieldset|figcaption|figure|footer|form|h[1-6]|header|hr|i|img|input|ins|kbd|label|legend|li|link|main|map|mark|meter|nav|ol|optgroup|option|output|p|param|picture|pre|progress|q|rb|rp|rt|rtc|ruby|s|samp|section|select|small|source|span|strong|style|sub|summary|sup|table|tbody|td|template|textarea|tfoot|th|thead|time|tr|track|u|ul|var|video|wbr|head|html|center|body)$/,
				attributes: true,
				classes: true,
				styles: true
            } 
	    ]
    }
};


export default { Editor, EditorWatchdog };
`

But, it still removes internal css, any suggestions if anything is wrong here?

**Comment by srav09** [comment]
Hi @anchal04, did you find any solution for this? I have tried above but it didn't work.

**Comment by anchal04** [comment]
yes,  Above workarounds(https://github.com/ckeditor/ckeditor5/issues/13482#issuecomment-1561232707 & https://github.com/ckeditor/ckeditor5/issues/12838#issuecomment-1473417306) solves the issue. Not fully supports all the internal css but solves the issue. Thanks @Witoso
