### ISSUE TITLE
Migration guide for changed placeholder text API

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14675]
## 📝 Provide a description of requested docs changes

Add a [migration guide](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/updating-ckeditor-5.html) that describes what action should be taken by developer to move from old format to new format.

PR that added this: #14627

**Comment by MZalfred** [comment]
Hey there! Hopefully this helps migration guide to assist you in moving from the old format to the new format introduced in PR #14627. Follow these steps to ensure a smooth transition:

Review the changes in the PR to understand the new format's benefits.
Back up your codebase to avoid any data loss during migration.
Update dependencies and libraries to the latest versions.
Modify configuration files to match the new structure.
Adjust the file structure, if necessary, to align with the new format.
Update code syntax to adhere to the new requirements.
Replace deprecated methods/functions with recommended alternatives.
Update API endpoints and payloads to match the new format.
Plan and execute data migration if the format involves changes to data structures or database schemas.
Test your codebase thoroughly and debug any issues that arise during migration.
Update your project's documentation to reflect the changes.
Communicate the changes to your development team and provide support if needed.

**Comment by Witoso** [comment]
@[MZalfred](https://github.com/MZalfred) our comment was deleted because it didn't provide any value and looked straight out of the LLM generator. Please don't add such comments in the future.

**Comment by mlewand** [comment]
Merged with #14686
