### ISSUE TITLE
Recursive insertion of &nbsp; (non-breaking space) character because of spaces around <br> (break) tag

### ISSUE THREAD

**Issue by jameslpetersen** [ckeditor/ckeditor5#14680]
## 📝 Provide detailed reproduction steps (if any)

1. Paste the following HTML when the editor is in source mode:
`<p>Hello <br> World</p>`
2. Switch out of and back into source mode

### ✔️ Expected result

_What is the expected result of the above steps?_

```
<p>
    Hello
    <br>
    World
</p>
```
### ❌ Actual result

_What is the actual result of the above steps?_

```
<p>
    Hello&nbsp;
    <br>
    World
</p>
```
Furthermore, the above HTML will re-trigger the bug when you re-open the editor and switch to source mode. This will lead to multiple &nbsp; (non-breaking space) tags in the HTML when the user does not want or need them.

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: 5
* Installed CKEditor plugins: None. This happens in the reference implementation.

**Comment by niegowski** [comment]
This issue should be fixed by https://github.com/ckeditor/ckeditor5/pull/14406. It was recently merged and should be released soon.

**Comment by Witoso** [comment]
I confirm that recursive behavior doesn't happen on the master ([check the nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)) but `nbsp` will be inserted. I guess this is added to allow editing the content before the `br`. Closing for now, as the issue reported the recursive behavior.

**Comment by raq007** [comment]
Hi @Witoso is there a way to avoid the single `nbsp` also ? I am trying to match with CKEDitor 4 behaviour so any workaround would be really appreciated. Thanks!

**Comment by navr84** [comment]
yes, is there any way to avoid the single nbsp also ? Any workarounds ?
