### ISSUE TITLE
Add style (Styles-Plugin) to anchor leads to unuseable behaviour

### ISSUE THREAD

**Issue by sascha-meissner** [ckeditor/ckeditor5#14683]
## 📝 Provide detailed reproduction steps (if any)

Make a ckeditor5 build with the Styles-plugin included

take this codesnippet
``` 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      .button {
        padding:25px;
        background:#eaeaea;
      }
    </style>
  </head>
<body>
  <div id="editor"></div>
  <!-- Make sure this points to the built ckeditor.js -->
  <script src="/ckeditor/ckeditor.js"></script>
  <script>
    ClassicEditor
      .create( document.querySelector( '#editor' ), {
        toolbar: {
            items: [
                'style',
                'link'
            ],
        },
        style: {
            definitions: [
                {
                  name: 'Button',
                  element: 'a',
                  classes: [ 'button' ]
                }
            ]
        }
      } )
      .then( editor => {
        window.editor = editor;
      } )
      .catch( err => {
        console.error( err.stack );
      } );
  </script>
</body>
</html>
``` 

Now, add some text, select it and make a link out of it, now when selecting the link-text, the style "button" will get avaiblable in the styles-dropdown, select the style - Now see  the "Actual result" part of this issue.

### ✔️ Expected result

When applying the "button-style" to an anchor, a hit on return should "leave the anchor and exit the style" (like in ckeditor4)

### ❌ Actual result

When applying the "button-style" to an anchor, **there is no way to continue writing without the style**, when hitting return,  the style will further be applied but cannot be removed (the style in the styles button is greyed out, even though you see visually that it is applied).

![jithub__1](https://github.com/ckeditor/ckeditor5/assets/4175470/18242f45-f0f2-4c98-a4ec-80242147dfa0)

### ❓ Possible solution
When hitting enter the style should not be further applied

## 📃 Other details

* Browser: FF / Chrome
* OS: Windows/Mac
* First affected CKEditor version: Ckeditor5
* Installed CKEditor plugins: Styles

---
I really hope this is no duplicate, i can reproduce this with the latest 38.1 Version

**Comment by Witoso** [comment]
I wonder @sascha-meissner [why don't you use `Link` plugin?](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) With it, everything works correctly, and escape is possible.

https://github.com/ckeditor/ckeditor5/assets/9881379/abf4432f-2054-4ec4-84b1-2688b52ed79c

(@niegowski 's case is to fix anyway)

**Comment by wimleers** [comment]
This seems like a similar behavior/bug to #14216, but based on https://github.com/ckeditor/ckeditor5/issues/14683#issuecomment-1660657804 by @niegowski, it sounds like it'll need to be fixed upstream anyway?

> I wonder @sascha-meissner [why don't you use Link plugin?](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) With it, everything works correctly, and escape is possible.

I'm confused by this statement 😅 @sascha-meissner is showing that he's using the `link` + `style` plugins, and based on your video, you're doing the same? 🤔 

What am I missing? 🙈

**Comment by Witoso** [comment]
@sascha-meissner showed an example w/o `Link` plugin, only with GHS where a link is an `htmlA` element in the model. I'm not certain how impactful this is for Drupal, do you have a link plugin that behaves differently than our link (uses `htmlA`?)

**Comment by niegowski** [comment]
> @sascha-meissner showed an example w/o `Link` plugin, only with GHS*, where a link is an `htmlA` element in the model. I'm not certain how impactful this is for Drupal, do you have a link plugin that behaves differently than our link (uses `htmlA`?)

@Witoso. It's not that. The Link feature uses the `linkHref` attribute but GHS can extend the link behavior by storing additional data in `htmlA` attribute. The existence of both is completely valid and does not mean that the Link feature is not used.

**Comment by Witoso** [comment]
Gotcha, got confused about the minimal build mentioned above, I thought it's very minimal :) 

1.  `Link` plugin and `GHS` are enabled.
2.  Additional attributes `htmlA` may be preserved: 
    ![](https://github.com/ckeditor/ckeditor5/assets/9881379/03b8de6a-63ad-4ded-97d9-2372980af188)
3. And are copied on enter which shouldn't happen (_This line should not be here same as for the linkHref attribute._)

**Comment by Witoso** [comment]
Workaround: removing the flag from the schema after initialization:

`editor.model.schema.setAttributeProperties( 'htmlA', { copyOnEnter: false } )`

**Comment by wimleers** [comment]
@Witoso Is that enough to completely fix the problem, without side effects for other functionality?

**Comment by Witoso** [comment]
Attaching video of what happens after the workaround:

https://github.com/ckeditor/ckeditor5/assets/9881379/5633e597-8af0-4dbb-8e5f-eae798214433

* Pressing enter inside the link, splits it and the style is copied. Possible to disable style (as before).
* Pressing enter at the end of the link creates a new line without any `htmlA` properties.

> without side effects for other functionality?

No, it shouldn't affect other features unless someone created something that expects this is the way it works 🤔. But that would be an extremely rare case, I think. This is a bug, for sure.

**Comment by wimleers** [comment]
If it's really a one-liner to fix, can we please get this in the upcoming release? 🙏

**Comment by el7cosmos** [comment]
apply the suggestion workaround, but still have the problem when clicking outside the link

and also when backspace after hitting the enter button.


https://github.com/ckeditor/ckeditor5/assets/284115/afe8e7a8-9247-4e18-95b1-a685d4b70701
