### ISSUE TITLE
Incorrect example in `elementToStructure()` API docs

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#14682]
## 📝 Provide a description of requested docs changes

In API docs of [\`elementToStructure()\` conversion helper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-elementToStructure) there's a following code example:

```
An example converter that converts the following model structure:

<wrappedParagraph>Some text.</wrappedParagraph>

into this structure in the view:

<div class="wrapper">
	<p>Some text.</p>
</div>

[...]
```

The proposed converter doesn't work though and throws the `conversion-element-to-structure-disallowed-text` [error](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-conversion-element-to-structure-disallowed-text).

**Comment by Witoso** [comment]
I wonder how much this relates to the schema definition. How did you define `wrappedParagraph`?

**Comment by Dumluregn** [comment]
With:
```
editor.model.schema.register( 'wrappedParagraph', {
	allowIn: '$root',
	allowChildren: '$text'
} );
```

It fails at the compilation level and the editor doesn't initialise. If you remove the `allowChildren` prop, text is not put inside `wrappedParagraph` (it's just lost in translation).

**Comment by Witoso** [comment]
@niegowski I guess we shouldn't show an example with the text wrapper?

**Comment by Spirit04eK** [comment]
@Dumluregn  
need to use:  
```
schema.register('wrappedParagraph', {
  inheritAllFrom: '$container'
})
```
@Witoso Why you shouldn't show an example with the text wrapper?

**Comment by Witoso** [comment]
Because this example was for the [\`elementToStructure()\` conversion helper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-elementToStructure) API docs, and we showed an example that resulted in an error. We try to be concise in those docs, and there was another example that didn't need a specific schema definition.
