### ISSUE TITLE
TypeError: .../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js: Cannot read properties of null (reading 'scope')

### ISSUE THREAD

**Issue by dyedwiper** [ckeditor/ckeditor5#14691]
## 📝 Provide detailed reproduction steps (if any)

I integrated CKEditor 5 in my react app. It works fine using `react-scripts start` but the build with `react-scripts build` always breaks with the same error: `TypeError: .../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js: Cannot read properties of null (reading 'scope')`. It breaks locally and on Heroku. 

I tried to boil it down to a smaller example but couldn't, so I reference my real app here.

I tried it with Node version 16 and 18.

1. Clone this repo: https://github.com/dyedwiper/rineuto-react-app
2. Go to client folder
3. Run `npm install`
4. Run `npm run build`

### ✔️ Expected result

The build succeeds.

### ❌ Actual result

Getting: `TypeError: .../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js: Cannot read properties of null (reading 'scope')`

**Comment by dyedwiper** [comment]
I just found out, it was because of my browserslist config. Changing it from `> 0.2%, not dead, not op_mini all` to `defaults`, fixed the problem.

**Comment by Reinmar** [comment]
Awesome, thanks for sharing :heart:
