### ISSUE TITLE
Backspacing on Android with Samsung keyboard misplaces the caret

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14707]
## 📝 Provide detailed reproduction steps (if any)

1. Open the online demo using Android with the Samsung keyboard.
2. Type some text into the editor ending with the word `test`
3. Try to backspace the last letter of `test` by hitting the backspace key once.

https://github.com/ckeditor/ckeditor5/assets/208610/dbe5cd2c-d08d-4e2f-bc3b-e81ad0cc3075

### ✔️ Expected result

The trailing `t` should be removed with the caret being placed behind `tes`.

### ❌ Actual result

The trailing `t` is removed, but the caret advanced by another character and is now between `te` and `s`. The editor will now look like this: `te|s` where the `|` denotes the caret position.

### ❓ Possible solution

This sounds an awful lot like #14567 which is similar but no the same.

## 📃 Other details

* Browser: Chrome 114
* OS: Android 13
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Not relevant

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dtdesign** [comment]
These “reverse typing” issues are more widespread than I thought, we’re receiving reports of users every 1-2 days in the last few weeks. Is there something we can do to either mitigate the issue or to help you identify the root cause of it?

**Comment by Witoso** [comment]
Is it "reverse typing" after the deletion? I thought it's moving the caret by one, but when typing the letters, they will be in the correct order.

**Comment by dtdesign** [comment]
I’m sorry, I confused the issues.

There are actually three distinct issues on Android that we have received repeated reports for recently:
 * This one.
 * #14567
 * #13994

It’s sometimes a bit annoying to figure out what exactly is going wrong because these reports are mostly from users of our customers. This adds a lot of “latency” when asking for more information and the instructions to reproduce the issue are often _imprecise_.

**Comment by niegowski** [comment]
The work for this issue and others related is completed in the https://github.com/ckeditor/ckeditor5/pull/16289, and we finalized the round of internal (successful) tests. I encourage everyone to test the PR if you have a chance. It should be merged in the following days, and will be a part of the next release.
