### ISSUE TITLE
Error thrown while using widget type around from a nested widget

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#14714]
## 📝 Provide detailed reproduction steps (if any)

1. Go to http://fake.ckeditor.com:8125/ckeditor5/tests/manual/article.html.
2. Create a table
3. Create a nested one (or add an image, any widget will do)
4. Click a widget type around button

### ✔️ Expected result

A paragraph is added.

### ❌ Actual result

An error is thrown.

![2023-08-02 11 07 04](https://github.com/ckeditor/ckeditor5/assets/1099479/586aca68-159b-4de7-a0e9-01051a2eb58e)

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This is caused by trying to set selection into the not attached element:

https://github.com/ckeditor/ckeditor5/blob/b82334152d0f6a4ba1a334d8a33bb15b81c82d43/packages/ckeditor5-paragraph/src/insertparagraphcommand.ts#L107

**Comment by niegowski** [comment]
This code:
https://github.com/ckeditor/ckeditor5/blob/b82334152d0f6a4ba1a334d8a33bb15b81c82d43/packages/ckeditor5-paragraph/src/insertparagraphcommand.ts#L97-L100
Is trying to insert paragraph after the table cell (not the table itself).

**Comment by oleq** [comment]
Most likely a regression after https://github.com/ckeditor/ckeditor5/pull/14510.
