### ISSUE TITLE
Docs issue report from "installation/getting-started/getting-and-setting-data.html"

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#14727]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/getting-and-setting-data.html

### Project version

39.0.0

### Is the information outdated? How?

<img width="989" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/156149/491c0ac8-29d6-4bd2-ba4e-1aeeaa972ef5">

The first code snippet misses its critical piece. Compare it with its source:

<img width="739" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/156149/94f5af33-9f0c-4fc3-a7ab-63785fe43999">

The 2nd one should show &entities; like here:

<img width="1124" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/156149/3db46dac-c2b9-4dcd-9612-61262e5f6f4a">

This was definitely rendered correctly in the past :O I wonder what has changed.

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by Reinmar** [comment]
You can compare how this should be rendered with this documentation from v20.0.0: https://ckeditor.com/docs/ckeditor5/20.0.0/builds/guides/integration/saving-data.html

**Comment by godai78** [comment]
Visual hotfix applied to this guide during the post-release 39.0.2 docs review to make the docs usable again. We can work on workaround in the meantime, now.
