### ISSUE TITLE
[Drag & drop] Upload image issues

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14740]
## 📝 Provide detailed reproduction steps (if any)

❌ dropping an image to the table from the external source doesn’t work if you want to drop the image below or above the code block (but the drop target line is visible).

❌ when you want to drop an image under or above text or block quote, the image appears inline (even if the drop target line is visible).

*   the logic if it's inline or block should be joined with the pasting of images. Initial logic: paragraph with text, always inline, etc.

https://github.com/ckeditor/ckeditor5/assets/9881379/f82df7be-f259-42fd-98b8-75e8779d2997

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by illia-stv** [comment]
This issue is resolved by another PR: https://github.com/ckeditor/ckeditor5/pull/14986
So after merging it could be closed

**Comment by Witoso** [comment]
AFAIK @illia-stv you can close two issues with one PR.
