### ISSUE TITLE
[Drag & drop] Improve images preview

### ISSUE THREAD

**Issue by dagdzi** [ckeditor/ckeditor5#14744]
We want to improve the image preview (especially for large images) so that they do not cover the content during using drag and drop feature.

We have chosen the following approach: **Image preview cannot be bigger than 50% of editor area.** 
The preview is smaller when the image is bigger than 50% of editor area, and the user drags the image by clicking on it.

In the Balloon block editor, when the user uses the drag handle to drag an image, the preview is the same size as the image size. 

[Figma prototype ](https://www.figma.com/proto/B20B2kvXTDzzO0zvNZmPE4/Enhanced-drag-and-drop-of-block?type=design&node-id=191-484&t=6RLoxFqczYmzUYzf-1&scaling=min-zoom&page-id=191%3A428&starting-point-node-id=191%3A484&show-proto-sidebar=1&mode=design)(click on the image to see the preview).

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by pszczesniak** [comment]
Will be solved by #14968 (native browser solution was chosen).
