### ISSUE TITLE
Update enablePlaceholder() usage in existing docs

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14742]
## 📝 Provide a description of requested docs changes

There are places in our docs that use `enablePlaceholder()` and were not changes with the last release where we changed the API of this helper.

All of these occurrences needs to be found and fixed.

**Comment by mlewand** [comment]
Be sure to make a PR to the `stable` branch so that we can deploy docs changes asap.

**Comment by pszczesniak** [comment]
Solved in #14754.
