### ISSUE TITLE
Font type and size keeps reverting to default despite user manually changing it.

### ISSUE THREAD

**Issue by Nuwan-access** [ckeditor/ckeditor5#14746]
After we changed font type and size If I navigate away and come back, or if I backspace to ensure I'm at the start of the paragraph, the font type and size reverts back to the default.
As a expected behavior, we would expect the font type and size to remain as what the user has changed them to. Could you please give that expected option for us.
![ckeditor4-](https://github.com/ckeditor/ckeditor5/assets/141401095/5867733f-9d87-4e78-afb0-890c30ec8e47)

**Comment by AliaksandrBortnik** [comment]
It is CKE5 repo. The page you showed us is a legacy CKE4 version.
