### ISSUE TITLE
Update documentation for Using a React component in a block widget page

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#14749]
## 📝 Provide a description of requested docs changes

Guide with a problem: https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/using-react-in-a-widget.html

Following this guide results in a lot of errors in the console.
This line:
```javascript
{% raw %}}}{% endraw %}
```
from `app.js` file prevents application from building. After getting adjusted, this wall of errors appear instead:
<img width="709" alt="Screenshot 2023-08-04 at 11 24 40" src="https://github.com/ckeditor/ckeditor5/assets/66953380/d52d662b-52b3-4c43-8722-4e0ce5c5b867">

Please look into this tutorial and adjust it so that it's fully functional on latest packages (or adjust it so that the guide will suggest installing specific versions of used packages) :)

**Comment by Witoso** [comment]
cc @apadol-cksource
