### ISSUE TITLE
Backspacing at the front of a list item merges with preceding block element

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14757]
## 📝 Provide detailed reproduction steps (if any)

1. Set up the editor using the quick start guide at https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html#sample-implementation
2. Inserts a block quote and type in `test`.
3. Hit Return twice to exit the quote.
4. Inserts a list item with the content `test`.
5. Move the caret to the front of the list item.
6. Hit Backspace once.

**Important**: For whatever reason this is not reproducible with the online demo. It can however be reproduced with all quick start guides as well as manual editor builds.

https://github.com/ckeditor/ckeditor5/assets/208610/7d4cd8b5-7d97-4691-98d3-5738e4bb15c6

### ✔️ Expected result

```
> test
|test
```

### ❌ Actual result

```
> test|test
```

## 📃 Other details

* Browser: Chrome 115
* OS: macOS 13.5
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Quick start/Full-featured/Custom build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This is a difference between [`Lists`](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html) and [`Document lists`](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html). As we plan to replace the former with the latter, I will close it as won't do. Soon, this week, we will create a pinned issue communicating the details.
