### ISSUE TITLE
CKEditor 5 - error coping parragraph styles with copy from office plugin

### ISSUE THREAD

**Issue by DanMerillas** [ckeditor/ckeditor5#14771]
## 📝 Provide detailed reproduction steps (if any)

Using CKEditor in React, we copy an email from Outlook where the 'P' elements have the 'style' attribute, and when we paste it into CKEditor, the styles are lost in the 'P' elements.

This behavior doesn't occur in the 'span' element. I've tried using pasteFilter and extraAllowedContent: 'p()[]{};div()[]{};li()[]{};ul()[]{};ol()[]{};span()[]{};' but it doesn't work.

Thank you so much

**Comment by DanMerillas** [comment]
Hi, im uding CKEditor 5. Thanks!!

**Comment by Reinmar** [comment]
> This behavior doesn't occur in the 'span' element. I've tried using pasteFilter and extraAllowedContent: 'p()\[\]{};div()\[\]{};li()\[\]{};ul()\[\]{};ol()\[\]{};span()\[\]{};' but it doesn't work.

But this is CKEditor 4's configuration.

**Comment by DanMerillas** [comment]
Sorry, you're right... And how could I keep the styles of the p tags in version 5?

**Comment by Reinmar** [comment]
Check out https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html

**Comment by DanMerillas** [comment]
The problem is that if I copy an email from the office client where the paragraphs have a font family, it disappears. However, if I copy it to Outlook web and then to the ckeditor component, it respects the styles of the <p>.

**Comment by Witoso** [comment]
To dig into the problem you're experiencing, it would be really helpful if we could get a bit more context. Specifically, we need to know:

*   Which version of CKEditor 5 you're using,
*   Some key details about your setup (plugins, etc.) and which installation path you followed (predefined builds, online builder, DLLs).
*   The steps we should follow to reproduce the issue.
*   Any relevant code snippets or a link to a repository that illustrates the issue.

These details will allow us to get a clearer picture of what's going wrong and how we might fix it. Without this information, it becomes quite tricky to pinpoint the issue and provide a useful solution.

**Comment by DanMerillas** [comment]
First of all, thank you for your help!!
It is not possible to give you a repository in which to see the code since it is being implemented for sharepoint using spfx and you would need an office 365 tenant to test it. 

However, I'll give you an easy way to reproduce it. I attached a zip file with an email with a text, the font-family is "Calibri". If I copy and paste it on the official ckeditor page of the "Copy from Office" plugin (https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office.html), you can see how the text is copied but in the <p> elements it creates it does not preserve the styles. If we do the same in the web version of outook(outlook.office.com/), we can see the <p> with the correct styles. I include screenshots of everything I say. 

Thank you so much
[CKEditorPasteFromOfficeError.zip](https://github.com/ckeditor/ckeditor5/files/12358623/CKEditorPasteFromOfficeError.zip)

**Comment by DanMerillas** [comment]
Hello, I have done a test, using the paste event and writing the html that is copied and the result is attached in the following file. It seems that the problem is that it does not copy the styles of the MsoNormal class that has the paragraph

ditor.editing.view.document.on( 'clipboardInput', ( evt, data ) => {
                                        if ( editor.isReadOnly ) {
                                            return;
                                        }
                            
                                        const dataTransfer = data.dataTransfer;
                                        const content = dataTransfer.getData( 'text/html' )
                                        console.log(content);
                                    } );

I have seen that this same test when carried out in the paid version of CKEditor works well, wrapping the paragraphs in span with the styles that did not work in the free version.

Thanks for your help
[OnPasteHtml.txt](https://github.com/ckeditor/ckeditor5/files/12451707/OnPasteHtml.txt)

**Comment by Witoso** [comment]
Ok, thanks for the info, the paid version was developed for more complex Word/MS content and translates the stylesheets to inline styles. Glad to hear it supports your case!
