### ISSUE TITLE
Make events consistent by introducing `data.ready` and `plugins.ready`

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#1477]
Extracted from #1449.

In #1449 the `editor.uiReady` event was moved from `Editor` to `EditorUI` and renamed to `ready` which means `editor.uiReady` was replaced with `editor.ui.ready` event.

To improve the API and keep it consistent, same could be done with `dataReady` and `pluginsReady` events (first is fired by specific editor creators and second by the `Editor` instance).

The `dataReady` should become `editor.data.ready` (fired by `DataController` class) and `pluginsReady` should become `editor.plugins.ready` (fired by `PluginCollection` class).

**Comment by f1ames** [comment]
When it comes to `dataReady` event and moving it to `DataController` class - it should be fired on the end of the `init` method ([somewhere here probably](https://github.com/ckeditor/ckeditor5-engine/blob/f537b89587ca1fc09614f8aca1226258d04282bf/src/controller/datacontroller.js#L252)). Now, there is another event already used in `DataController` called `init` [created by decorating the `init()` method](https://github.com/ckeditor/ckeditor5-engine/blob/f537b89587ca1fc09614f8aca1226258d04282bf/src/controller/datacontroller.js#L105).

This means there will be two events -  `init` and `ready` fired in the exact same moment (btw. `ready` could be also implemented using `decorate`). IMHO it doesn't make sense, because these two events just indicates the same thing (data initialization has finished). Should we get rid of `init` event?

The second thing, is it possible to have editor creator which does not use `data.init` method ([such `create()` method is used in `Editor` class](https://github.com/ckeditor/ckeditor5-core/blob/9433c4ba49b41f7922e38fc6c7e91f9a7ecf6ba7/src/editor/editor.js#L310-L317))? In such cases, `data#ready` event will not be fired. Should it be mandatory to use `data.init()` method or fire `data#ready` event manually when implementing editor creator (maybe it already is)?

cc @pjasiun @Reinmar

**Comment by pjasiun** [comment]
> When it comes to `dataReady` event and moving it to `DataController` class - it should be fired on the end of the `init` method ([somewhere here probably](https://github.com/ckeditor/ckeditor5-engine/blob/f537b89587ca1fc09614f8aca1226258d04282bf/src/controller/datacontroller.js#L252)). Now, there is another event already used in `DataController` called [`init`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_controller_datacontroller-DataController.html#event-init) [created by decorating the `init()` method](https://github.com/ckeditor/ckeditor5-engine/blob/f537b89587ca1fc09614f8aca1226258d04282bf/src/controller/datacontroller.js#L105).

`init` event is needed to make it possible to overwrite this method. However, we could fire `ready` in the `init` listener with the `LOWEST` priority. It makes sense that at the end of the initialization data controller says it is ready. It would also work with custom listeners which adds additional functionality to the `init` method.

> The second thing, is it possible to have editor creator which does not use `data.init` method ([such `create()` method is used in `Editor` class](https://github.com/ckeditor/ckeditor5-core/blob/9433c4ba49b41f7922e38fc6c7e91f9a7ecf6ba7/src/editor/editor.js#L310-L317))?

I think each editor should init engine using `data.init`. We should remove this `Editor.create` method since it is simply incorrect.
