### ISSUE TITLE
Image caption breaking layout

### ISSUE THREAD

**Issue by yitbareck** [ckeditor/ckeditor5#14775]
## 📝Details

Whenever I try to insert a caption to an image,  the caption container expands to take 50% of the figure breaking the layout of the whole content.

### ✔️ Expected result

![image](https://github.com/ckeditor/ckeditor5/assets/45262070/182d0759-f91a-4ab5-8e3c-d814e3dc1401)

### ❌ Actual result
![image](https://github.com/ckeditor/ckeditor5/assets/45262070/e1b0b774-cde2-4867-8838-f7094303a49e)

**Comment by Reinmar** [comment]
Can you create a fiddle oj codepen or jsfiddle to show this? 

This issue does not occur in our demos or samples, so it's most likely something related to styling of your page. You may be able to figure this out when inspecting the styles of that figure element in your dev tools.

**Comment by yitbareck** [comment]
Thank you. Yes, it was related to styling of my page. It had nothing to do with CKEditor. Fixed now!
