### ISSUE TITLE
Something wrong in dev mode about `getData` method documentation

### ISSUE THREAD

**Issue by fabienwnklr** [ckeditor/ckeditor5#14788]
## 📝 How can i use `getData` method ?

Hi, i try to create a plugin, but i have an issue when i try to import `getData` method as mentionned in doc [here](https://ckeditor.com/docs/ckeditor5/latest/framework/development-tools.html#testing-helpers)

This error appear.. what's i supposed to do ? I didn't find any solution for getting data of `editor`, if i try `editor.getData` i have an error `Property 'getData' does not exist on type 'Editor'`
![image](https://github.com/ckeditor/ckeditor5/assets/49644785/279c85ab-42b7-4607-9cc5-a833a51fb26d)

Thanks !

**Comment by Witoso** [comment]
Thanks for reaching out. To dig into the problem you're experiencing, it would be really helpful if we could get a bit more context. Specifically, it would be great to see any relevant code snippets or a link to a repository that illustrates the issue :)

`Property 'getData' does not exist on type 'Editor'` this is a TypeScript error. I would recommend resolving it before using _the `getData` method as mentioned in doc_ [_here_](https://ckeditor.com/docs/ckeditor5/latest/framework/development-tools.html#testing-helpers)_,_ as this one is strictly a development helper. Could you share on which line this shows up?

**Comment by fabienwnklr** [comment]
hi, first thanks for your answer ! So, i give you more context, i try to create ckeditor5 plugin for personal use, and i need to fetch current data of editor (cf [read code here](https://github.com/fwcie/ckeditor5-preview/blob/master/src/preview.ts#L30) i just remove code error because it prevents me from committing in case of typescript error) 

then i didn't find solution for resolving this TypeScript error.. any solutions ? Thanks again !

**Comment by Witoso** [comment]
I highly recommend [using the package generator](https://ckeditor.com/docs/ckeditor5/latest/framework/plugins/package-generator/using-package-generator.html).

> then i didn't find solution for resolving this TypeScript error.. any solutions ?

Without the context of where do you call it, I cannot  help :(

**Comment by fabienwnklr** [comment]
I've used packages generator ! You can check code here : [https://github.com/fwcie/ckeditor5-preview/](https://github.com/fwcie/ckeditor5-preview/)

**Comment by Witoso** [comment]
Gotcha, in this case you can use [`editor.data.get`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_controller_datacontroller-DataController.html), TypeScript doesn't know which specific Editor it will get, and only those (e.g., `ClassicEditor`) have `editor.getData`. We have a plan to fix it: #13904.

**Comment by fabienwnklr** [comment]
okay, thanks for answer, it work !
