### ISSUE TITLE
Docs issue report from "installation/integrations/other.html"

### ISSUE THREAD

**Issue by yj-10** [ckeditor/ckeditor5#14786]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/other.html

### Project version

39.0.1

### User agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Please open an issue with an exact description of the problem.
