### ISSUE TITLE
Loading very long table created in CKEditor 4 freezes the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#14785]
## 📝 Provide detailed reproduction steps (if any)

1.  Use the following content as the initial data - [https://gist.github.com/Mgsy/7a8cb809e34c1595d5bec788804091e5](https://gist.github.com/Mgsy/7a8cb809e34c1595d5bec788804091e5) (it's a table with ~3000 rows) or copy/paste it to the editor.

### ✔️ Expected result

_The table loads._

### ❌ Actual result

_The browser freezes. It might also throw errors after some time:_

![](https://support.ckeditor.com/attachments/token/ebAL9Ny8etJfZ4wPB3E6XqqqU/?name=image001.png)

## 📃 Other details

The same table loads almost immediately in CKEditor 4.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@Mgsy I cannot access the gist :(

**Comment by AliaksandrBortnik** [comment]
@Witoso me neither
