### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by AndrewSmir** [ckeditor/ckeditor5#14780]
Hi!

I'm trying customizing the build using built from source but faced the error ckeditor-duplicated-modules. I've followed the docs but it didn't help. Then I tried to use config from the example repo that mentioned in the documentation: https://github.com/ckeditor/ckeditor5-react-example assuming, that it should work. But there is the same issue)

Steps to reproduce:

- git clone https://github.com/ckeditor/ckeditor5-react-example
- npm i
- npm run start

I've checked the installed versions of ckeditor packages - all the same (38.1.1) except @ckeditor/ckeditor5-dev-utils (38.3.1)

What might be the reason?

![image](https://github.com/ckeditor/ckeditor5/assets/49587118/50efd054-9586-4e66-b6a5-67f1c71fe005)

**Comment by trinath-katari** [comment]
Hi [AndrewSmir](https://github.com/AndrewSmir)

Please go through the link; it may be helpful
https://github.com/ckeditor/ckeditor5/issues/8386

**Comment by AndrewSmir** [comment]
No solution there, unfortunately

**Comment by Mgsy** [comment]
Hi @AndrewSmir! 

I've updated the dependencies in the project, and I can't reproduce the duplicated modules error anymore. Can you please pull the latest changes, remove your `node_modules` and `package-lock.json` (or `yarn.lock`), then try to re-install packages and start the project again?

**Comment by AndrewSmir** [comment]
Hi @Mgsy ! Yep, it works! Going to update deps and .lock file in my project too.
Thank you!

**Comment by Ankur1326** [comment]
I am also facing this same issue, not able to solve it
