### ISSUE TITLE
Advice: How to create plugin for a custom web component?

### ISSUE THREAD

**Issue by chhill-redhat** [ckeditor/ckeditor5#14792]
## Question
What's the best way to create a plugin for a custom web component that wraps only links? I have a web component with a single attribute (tag `<cta variant=[text]>`) which should only contain `<a>` elements.

I followed the helpful, 3-part Abbreviation guide (suggested in #14782 ).

Here are my remaining problems:
- How can I limit my plugin to contain only `<a>` elements? My current version is an Attribute that extends all text elements (`editor.model.schema.extend('$text', { allowAttributes: 'cta' }))`. Is this the correct approach?
- Similarly, the abbreviation example allows only text inside it. How do I allow it to container `<a>` element instead of plain text?

Or, is mimicking the abbreviation example even a good idea for my use case? Open to any architectural advice here.
Thanks your any help!

**Comment by Witoso** [comment]
Hey! Thanks for reaching out! TBH, I would advise against using the abbreviation guide as an example for your use case. As you noticed, it works only on text (as it's using attributes). For your case, it looks like the block widget could be better. [There's a tutorial for it as well](https://ckeditor.com/docs/ckeditor5/latest/tutorials/widgets/implementing-a-block-widget.html), with an example of how to define the schema.

**Comment by chhill-redhat** [comment]
Great. Thank you for the suggestion, @Witoso !
