### ISSUE TITLE
CKEditor 5 how to insert HTML into mention?

### ISSUE THREAD

**Issue by eldiyar312** [ckeditor/ckeditor5#14795]
> @jodator you can see here: editor.conversion.for('downcast').attributeToElement({ model: 'mention', view: (modelAttributeValue, { writer }) => { if (!modelAttributeValue) { return; }
> 
> ```
>         var linkElement = writer.createAttributeElement('a', {
>             class: 'mention',
>             'data-mention': modelAttributeValue.id,
>             'data-user-id': modelAttributeValue.userId
>         }, {
>             priority: 20,
>             id: modelAttributeValue.uid
>         });
> 
>         return linkElement;
> 
>     },
>     converterPriority: 'high'
> });
> ```
> 
> It only replaces <span> tag to <a> tag, I want to add a nested element like <a...><img...></a>

also i have same problem, i need insert html into mention

_Originally posted by @eldiyar312 in https://github.com/ckeditor/ckeditor5/issues/4658#issuecomment-1679421885_

**Comment by eldiyar312** [comment]
How insert html as html to into mention ? i tryed with conversions but it's didn't work. Help me. How i can resole this problem ?
Maybe youre will be add new attribe for html content ? not only text

`editor.conversion.for('editingDowncast').attributeToElement({
        model: 'mention',
        view: (modelAttributeValue, { writer }) => {
            // Do not convert empty attributes (lack of value means no mention).
            if (!modelAttributeValue) return

            const element = writer.createAttributeElement('span', { class: 'mention', 'data-mention': modelAttributeValue.id }, { id: modelAttributeValue.uid })

            console.log('===element', element)
            // const viewFragment = editor.data.processor.toView(modelAttributeValue._text)
            // const modelFragment = editor.data.toModel(viewFragment)
            const body = writer.createRawElement('span', null, (domElement) => (domElement.innerHTML = modelAttributeValue._text))
            element._appendChild(body)
            element._insertChild(0, body)
            element._fireChange('children', body)

            const position = writer.document.selection.getFirstPosition()
            if (position) writer.insert(position, body)
            const range = writer.document.selection.getFirstRange()
            if (range) writer.wrap(range, element)

            return null
        },
        con`

**Comment by Witoso** [comment]
Could you describe what kind of HTML you want to achieve?

**Comment by eldiyar312** [comment]
In this code `editor.conversion.for('editingDowncast').attributeToElement({model: 'mention'})` i can return only attribute element, not rawElement or any.
And i need push into mention content any html, example:
&lt;span class="mention"&gt;&lt;h4&gt;Som title&lt;/h4&gt;
&lt;ul&gt;
&lt;li&gt; &lt;/li&gt;
&lt;/ul&gt;
&lt;blockquote&gt;
&lt;p&gt;Content text and maybe html&lt;/p&gt;&lt;/span&gt;

**Comment by eldiyar312** [comment]
![image](https://github.com/ckeditor/ckeditor5/assets/48121350/ba3f3d47-946b-4711-ae59-cc713b18bd6d)

**Comment by eldiyar312** [comment]
@Witoso

**Comment by Witoso** [comment]
You cannot achieve what you want with the Mention/Autocomplete plugin, as this is not its purpose. Mention internally is stored in the data model as an attribute on text. You can tweak its representation via the⁣ `attributeToElement`, but you cannot alter its children (which should be text).

In the case you have shown, it looks like [our premium templates feature](https://ckeditor.com/docs/ckeditor5/latest/features/template.html), or you could write your plugin with our [framework](https://ckeditor.com/docs/ckeditor5/latest/framework/index.html).
