### ISSUE TITLE
Editor toolbar Outside parent div. 

### ISSUE THREAD

**Issue by compjotr** [ckeditor/ckeditor5#14794]
## 📝 Provide detailed reproduction steps (if any)
1. add a table.
2.Scroll down so the editor toolbar is above the screen
3. highlight a table cell. 

### ✔️ Expected result

the toolbar editor dosen't move outside parent. 

### ❌ Actual result

toolbar is outside parent. It shouldn't be visible at this point. 

### ❓ Possible solution
it is possible to  edit the values here: .ck.ck-toolbar>.ck-toolbar__items {
    display: flex;
    flex-flow: row wrap; REMOVE THIS LINE
    align-items: center;
    flex-grow: 1; REMOVE THIS LINE }
but then the items in the toolbar overflows. 

## 📃 Other details
![Screenshot 2023-08-15 at 16 18 21](https://github.com/ckeditor/ckeditor5/assets/8794897/d7149b09-b5b6-42da-9d4f-564a5b1ba701)

* Browser: Chrome
* OS: MacOS monterey, Windows 10
* First affected CKEditor version: …
* Installed CKEditor plugins: 

---

**Comment by Witoso** [comment]
Could you create some recording? Just by looking at the picture it's hard to tell what's wrong as it shows correct behavior.

**Comment by compjotr** [comment]
@Witoso  ![Screenshot 2023-08-16 at 10 29 10](https://github.com/ckeditor/ckeditor5/assets/8794897/6bc1b0df-1bfe-4209-99fa-5533e9d01d21)
This picture is better. as you see the toolbar has moved itself about 300px to high.

**Comment by Witoso** [comment]
What version are you using? #5465 was fixed in the version `39.0.0` and it's possible it solves this issue.

**Comment by compjotr** [comment]
nice, that solved it!
