### ISSUE TITLE
Config#define and #get are not very useful for feature developers

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#148]
I wanted to do this:

```js
editor.config.define( 'typing', {
	undoStep: 10
} );
```

And later get the value:

```js
editor.config.get( 'typing.undoStep' );
```

I get `undefined` which means there are two serious issues:

1. `define( 'a', obj )` doesn't work with `config.get( 'a.b.c.d' )` and `config.a.b.c.d`,
2. there's no validation – I'd expect an error, but instead I got silent `undefined`.

**Comment by oskarwrobel** [comment]
Moved to https://github.com/ckeditor/ckeditor5-utils/issues/33
