### ISSUE TITLE
Using callbacks as tokenUrl value in ckbox is not possible

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#14804]
## 📝 Provide detailed reproduction steps (if any)

1. Use CKEditor 5 with CKBox plugin.
2. Provide [tokenUrl](https://ckeditor.com/docs/ckeditor5/latest/api/module_ckbox_ckboxconfig-CKBoxConfig.html#member-tokenUrl) as a callback. 

Example:
```
ckbox: {
  tokenUrl: () => new Promise( ( r ) => { setTimeout( ( ) => r( 'token_string' ), 500 ) } )
}
```

### ✔️ Expected result

The provided callback is executed and the value from the resolved promise is used as a token.

### ❌ Actual result

The editor tries to fetch the token from `./[object%20Object]` url

### ❓ Possible solution

Could be caused by https://github.com/ckeditor/ckeditor5/issues/12835 as there is nested name used in `editor.config.get` in the plugin source code: 
https://github.com/ckeditor/ckeditor5/blob/a8b1e91ba6855507b9d703a7e55076a05b2159be/packages/ckeditor5-ckbox/src/ckboxediting.ts#L74

## 📃 Other details

* Not a regression

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
If the problem is indeed with #12835, fix both tickets.

**Comment by illia-stv** [comment]
I can confirm, https://github.com/ckeditor/ckeditor5/issues/12835 is related with current issue.
