### ISSUE TITLE
Missing name `global` when scrolling ckeditor - header does not stick

### ISSUE THREAD

**Issue by FreexD** [ckeditor/ckeditor5#14801]
## 📝 Provide detailed reproduction steps (if any)

1. Trrying to scroll ckedtor-5 on version 39.0.1.

### ✔️ Expected result

The header sticks properly and no error is in the console.

### ❌ Actual result

The header does not stick and it errors in the console - missing name `global`.

### ❓ Possible solution

Missin global import  `import global from './global';` in https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-utils/src/dom/getelementsintersectionrect.ts .

## 📃 Other details

* Browser: Chrome
* OS: MacOS
* First affected CKEditor version: 39.0.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for reporting! cc @filipsobol

**Comment by Witoso** [comment]
We noticed it doesn't work in the Vite setup (ckeditor/vite-plugin-ckeditor5#17). @FreexD could you share the details about your setup?

**Comment by FreexD** [comment]
@Witoso I was testing on a Vite setup as well.

**Comment by filipsobol** [comment]
This issue will be fixed by PR #14808.

**Comment by filipsobol** [comment]
The fix for this issue has been merged (PR #14808) and will be available in the next release.
