### ISSUE TITLE
Docs issue report from "framework/plugins/abbreviation-plugin/abbreviation-plugin-level-1.html"

### ISSUE THREAD

**Issue by philippemouchel** [ckeditor/ckeditor5#14802]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/plugins/abbreviation-plugin/abbreviation-plugin-level-1.html

### Project version

39.0.1

### Is there something missing in the guide? What is it?

At this step, the line `import { ButtonView } from "@ckeditor/ckeditor5-ui";` is missing right after the `import { Plugin } from '@ckeditor/ckeditor5-core';`.
As is, this would trigger an error as **ButtonView** is not imported.

![image](https://github.com/ckeditor/ckeditor5/assets/3852750/425f7baa-bc4d-4cfc-b2ec-dfe80a5e393f)

It's added in the next code block though, but should already be present in this one.

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Thanks! Fixed in #14626.
