### ISSUE TITLE
Error - Cannot find module 'ckeditor5/src/utils' or its corresponding type declarations.

### ISSUE THREAD

**Issue by lokopinagar** [ckeditor/ckeditor5#14822]
On using command "npm install --save @ckeditor/ckeditor5-angular" i am getting error
**Cannot find module 'ckeditor5/src/utils'** or its corresponding type declarations in the package

on line import type { CKEditorError } from 'ckeditor5/src/utils'; in watchdog.d.ts file in folder node_modules\@ckeditor\ckeditor5-watchdog\src

Thank you

**Comment by Witoso** [comment]
Angular package has a set of [peerDependencies (in package.json)](https://www.npmjs.com/package/@ckeditor/ckeditor5-angular?activeTab=code), I think that installing a watchdog package and others may solve this issue. Let me know if it helped.

**Comment by Witoso** [comment]
npm v7+ installs peer dependencies by default, so I wonder if this could be an issue. Check your npm version if you can.

**Comment by lokopinagar** [comment]
I ran this command with --legacy-peer-deps
npm install --save @ckeditor/ckeditor5-core @ckeditor/ckeditor5-engine @ckeditor/ckeditor5-utils @ckeditor/ckeditor5-watchdog
I double checked the peerDependency i have all of them installed but still error remains.

I changed the Line from --> ckeditor5/src/utils
to -->@ckeditor/ckeditor5-utils
in package the error was gone but i do not want to make change in the package file (_editorwatchdog.d.ts_).

I am using npm 9+

please let me know what i am doing wrong?

Thank you

**Comment by Witoso** [comment]
Please try installing `npm install --save ckeditor5`. I'm not sure why it's missing on your side, do you have any other editor's packages?

The problem should be solved in #13852, in which we will clean up the Watchdog dependencies.

**Comment by lokopinagar** [comment]
Thank you it solved the problem

I was following [this ](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html) page and yes i have installed some other text editor which i am planning to unistall

**Comment by Witoso** [comment]
Great, I meant other CKEditor 5 packages, it's possible that with a build or plugins installed you wouldn't see this problem. But we need to fix this on some other level. JFYI @pomek.

**Comment by murithicollins** [comment]
i am trying to run ckeditor5 in svelte and i am encountering this error "Error: Cannot find module '@wiris/mathtype-ckeditor5/dist/wirisplugin.css' imported from '/home/locco/Documents/demos/math5/src/lib/components/ckeditor.svelte"
