### ISSUE TITLE
Append data functional

### ISSUE THREAD

**Issue by TessDevAcc6** [ckeditor/ckeditor5#14838]
Hello, is it possible to use the setData functionality in parts? For example, for large documents, split the HTML into several parts and add them as needed, just like setData works(with up and down casters) but add and not replace. (to implement lazy loading or at least not block the main thread during setData)

Sorry if I'm asking this question in the wrong section.

**Comment by Witoso** [comment]
Hey @TessDevAcc6, that a good question. Looks like your use case could use [the multi-root editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/multi-root-editor.html). It's an editor type that has multiple editable roots under one instance.

Quoting the [`39.0.0` release](https://github.com/ckeditor/ckeditor5/releases/tag/v39.0.0):

> #### Multi-root editor - delayed root loading \[experimental\]
> 
> It is now possible to initialize the multi-root editor with just one or a few of the document roots and load the other roots later on.
> 
> This solution is useful for huge documents that are split into chapters or sections, where each chapter or section is a separate document root.
> 
> Real-time collaboration and revision history features are supported. Users can join the same document but have different parts of the document loaded initially.
> 
> (...)
> 
> Note: this is an experimental feature. Its API and details of its behavior may change in the upcoming releases.

You can dive into details on the [API page](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-multi-root_multirooteditor-MultiRootEditor.html). Let us know what you think :)

**Comment by Reinmar** [comment]
You beat me by 1 second, Witek :D 

Another thing I wanted to mention is not relying on HTML as data. Currently, the slowest part of data loading is parsing and conversion to the model. We don't have an official guide for this yet, but it's relatively easy to achieve anyway: #620.

**Comment by TessDevAcc6** [comment]
Thanks, Multi-root great solution for the first time.
