### ISSUE TITLE
Comments added to same word causes issue where the top comment wont remain open

### ISSUE THREAD

**Issue by Joshuajrodrigues** [ckeditor/ckeditor5#14848]
## 📝 Provide detailed reproduction steps (if any)

I have classic editor implemented and my comments (narrow) work fine until you add 2 comments 2 1 word

### ✔️ Expected result

comment should remain open

### ❌ Actual result

the first comment closes as soon as you click to open it

### ❓ Possible solution

I might be doing something wrong with the css ? because this doesnt replicate on the demo

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Could you share some recording of the behavior? It will help us understand the issue.

**Comment by Joshuajrodrigues** [comment]
> Could you share some recording of the behavior? It will help us understand the issue.

here you go @Witoso 
As you can see the the first comment doesnt remain open

https://github.com/ckeditor/ckeditor5/assets/54748294/ac9869f9-37a5-402d-8bf8-a1902c812b30

**Comment by scofalik** [comment]
Unfortunately, I am unable to reproduce it either in our internal manual samples or docs (https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments.html) or demos (https://ckeditor.com/collaboration/demo/) so it might be something more specific.

1.  What is your editor version?
2.  What kind of the editor this is (I assume Classic from the looks of it).
3.  Does it also happen when the comment is not on the first/only word of the editor?
4.  Do you use any customizations (outside of CSSes)?
5.  Do you use any of the framework integrations (React, Angular, Vue)?
6.  Will it be possible to for you to provide us a minimal demo that we could use to reproduce the issue? Please reach us on our support channel (https://ckeditor.com/contact/) if you do not want to share that publicly.

**Comment by scofalik** [comment]
Hi, @Joshuajrodrigues, my colleague directed you to contact our support team for some of your issues. It's the same case here. That will be the fastest way to fix the issue.
