### ISSUE TITLE
Docs issue report from "examples/builds-custom/full-featured-editor.html"

### ISSUE THREAD

**Issue by billpeace** [ckeditor/ckeditor5#14842]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

### Project version

39.0.1

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
There's no information about the issue or feedback. Please provide additional details in the future.
