### ISSUE TITLE
Docs issue report from "features/autosave.html"

### ISSUE THREAD

**Issue by clairefields15** [ckeditor/ckeditor5#14853]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/autosave.html

### Project version

39.0.1

### Is there something missing in the guide? What is it?

This guide does not cover how to configure autosave in react/typescript or when using a custom build.  My custom build includes autosave plugin but I don't have a means to control the save function.  To try to integrate typescript I imported { EditorConfig } from '@ckeditor/ckeditor5-core'; butwhen trying to add autosave to the config object I see the typescript error that ` 'autosave' does not exist in type 'EditorConfig'`.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Closing as a duplicate for now of the #14854 issue. If it turns out we need to update docs, we will do it there.
