### ISSUE TITLE
Docs issue report from "installation/getting-started/quick-start.html"

### ISSUE THREAD

**Issue by anaysah** [ckeditor/ckeditor5#14850]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html

### Project version

39.0.1

### Is the information outdated? How?

The CKEditor 5 superbuild code is no longer functioning correctly. An error is being displayed: "Uncaught CKEditorError: paste-from-office-enhanced-invalid-license-key." I believe this issue arises because certain features require a license key. However, the superbuild is intended for testing purposes, so it should ideally work through simple copy-pasting without requiring a license key.

### Is there something missing in the guide? What is it?

By adding 'PasteFromOfficeEnhanced' to the removePlugins configuration, the issue should be resolved.

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
> However, the superbuild is intended for testing purposes, so it should ideally work through simple copy-pasting without requiring a license key.

Take into account this is used also by a paying commercial customers but I agree it needs to be more explicit.

@ckeditor/ckeditor-5-ccx, could you take a look at this?

**Comment by godai78** [comment]
This is what it is at the moment. There is an option to use Premium Features Free Trial for 30 days: https://ckeditor.com/docs/trial/latest/guides/overview.html and get a license key for PfOE this way.

This is larger than just CCX, considering the inclusion of the PropPack.

**Comment by Witoso** [comment]
I was thinking about adding some info to the docs,(e.g, [here](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html#using-the-ckeditor-5-superbuild)).

**Comment by godai78** [comment]
I'll do it.
