### ISSUE TITLE
Font family should change the font of list items

### ISSUE THREAD

**Issue by bradleyfindeis** [ckeditor/ckeditor5#14852]
## 📝 Provide detailed reproduction steps (if any)

1. Load Editor with existing ordered list
2. Highlight the text in ordered list
3. Change the Font Family
4. You will notice that the text changes font to your selection but the numbers in the ordered list do not change to match the font

### ✔️ Expected result

No matter what I font I select for the each number, the number would match the selected font family. I.e. if I have a list 1 - 3 and each text is a different font the number would be the font selected.

### ❌ Actual result

![Screenshot 2023-08-23 at 11 03 09 AM](https://github.com/ckeditor/ckeditor5/assets/36309766/f2333dab-d7f8-40ed-b02e-9523532d7646)

### ❓ Possible solution

Instead of setting the font family on the child <span> element set it on the <ol> and the <span> should inherit that value

## 📃 Other details

* Browser: Chrome
* OS: Ventura
* First affected CKEditor version: 5
* Installed CKEditor plugins: 
  Alignment,
  Autoformat,
  AutoImage,
  AutoLink,
  AutoSave,
  BlockQuote,
  Bold,
  CloudServices,
  Code,
  CodeBlock,
  Comments,
  CommentsIntegration,
  CommentsAdapter,
  DocumentList,
  DocumentListProperties,
  DocumentOutline,
  Essentials,
  FileRepository,
  FindAndReplace,
  Font,
  Heading,
  Highlight,
  HorizontalLine,
  HtmlEmbed,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  MediaEmbed,
  PageBreak,
  Paragraph,
  PasteFromOffice,
  PictureEditing,
  RemoveFormat,
  SimpleUploadAdapter,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableOfContents,
  TableProperties,
  TableToolbar,
  TextPartLanguage,
  TextTransformation,
  Underline,

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey @bradleyfindeis, thanks for the request! I will change this to an improvement request, the Font family is right now feature related to text via the application of `spans`.

**Comment by Witoso** [comment]
I found a duplicate: #5752. Closing this one.
