### ISSUE TITLE
Support for the `div` element

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14873]
Currently, the editor doesn't have a support for the `div` element. This is an issue to gather the interest.

This is often asked in context of escaping a div (paragraph before/after), which is currently not possible. CKEditor 4 had a "Special container" style and a magic line that provided an ability to add a paragraph after a div.

We need to remember about the usage of a `div` in two contexts:

```html
<!-- Paragraph-like div -->
<div>This is a text.</div>

<!-- Container div -->
<div>
  <p>This is a text.</p>
</div>
```

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
DUP of #6462?

**Comment by Witoso** [comment]
Yep, I hate GH search :face\_exhaling: To all that bumped this issue, move your votes to the [#6462](https://github.com/ckeditor/ckeditor5/issues/6462).
