### ISSUE TITLE
Image link "Open in a new tab"

### ISSUE THREAD

**Issue by sirsquall** [ckeditor/ckeditor5#14871]
## 📝 Provide detailed reproduction steps (if any)

1. In the latest version of Drupal 10
2. Install the module https://www.drupal.org/project/editor_advanced_link
3. Install the module https://www.drupal.org/project/imce
4. Now add an image 
5. Add link to this image and tick the option "open in a new tab"
6. Save 

### ✔️ Expected result

The link should open in a new window

### ❌ Actual result

The link is not opened in a new window

### ❓ Possible solution

the add the target="_blank" in the link of the image

Thanks

**Comment by Witoso** [comment]
Hey @sirsquall, looks like an issue related to Drupal. We don't maintain those modules and as far as I know Drupal has its own implementation of images and links on them. It would be best to reach the core or module maintainers with questions.
