### ISSUE TITLE
Erroneous Finnish translation in ordered list start index error message

### ISSUE THREAD

**Issue by jusla** [ckeditor/ckeditor5#14881]
## 📝 Provide detailed reproduction steps (if any)

1. Create an ordered list in a Finnish-language CKEditor instance that allows setting the list start index.
2. Try to set the start index of the list to zero.
3. Read the error message.

### ✔️ Expected result

The Finnish translation matches the English-language message ("Start index must be greater than 0").

### ❌ Actual result

The Finnish translation
"Aloitusindeksi ei saa olla suurempi kuin 0."
actually translates to: "Start index cannot be greater than 0".

### ❓ Possible solution

Change the translation here
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-list/lang/translations/fi.po#L119
to e.g.
"Aloitusindeksin pitää olla suurempi kuin 0."

## 📃 Other details

* Browser: Edge
* OS: Windows

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the report! @ckeditor/ckeditor-5-devops is this something you could replace?

**Comment by pomek** [comment]
Fixed in Transifex:

![image](https://github.com/ckeditor/ckeditor5/assets/2270764/d9adc8bb-457d-492a-b874-7682adc106b9)
