### ISSUE TITLE
IndentBlock plugin breaks formatting of list items when pasting from desktop Word

### ISSUE THREAD

**Issue by mikkicom** [ckeditor/ckeditor5#14888]
## 📝 Provide detailed reproduction steps (if any)

1. Enable the `IndentBlock` plugin along with `PasteFromOffice` and any other essential plugins necessary for creating lists in CKEditor
2. Create a ordered or unordered list in word with multiple levels of indentation. Copy and paste into a CKEditor instance

### ✔️ Expected result

The formatting/indentation of the list items in CKEditor should be virtually the same as Word:
<kbd>
![localhost_8856_ (21)](https://github.com/ckeditor/ckeditor5/assets/127138745/2b465c56-8e2b-4532-bf9b-5b9df873c570)
</kbd>

### ❌ Actual result

The formatting/indentation of the list items in CKEditor is off:
<kbd>
![localhost_8856_ (22)](https://github.com/ckeditor/ckeditor5/assets/127138745/e764b19a-29bc-4ecb-bb1e-09d42d3dbad1)
</kbd>

## 📃 Other details
At a certain level of indentation, the `IndentBlock` plugin seems to be adding a `margin-left` to the `p` tags that wrap the text within list items.

* Browser: Chrome 116
* OS: Ventura 13.4.1
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Paragraph, Indent, IndentBlock, AutoFormat, PasteFromOffice
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is fixed in #12466. You can test the fix in the [nightly version](https://github.com/ckeditor/ckeditor5/issues/14724) or on [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/).
