### ISSUE TITLE
Remove temporarily ckbox focus solution

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#14890]
## Provide a description of the task

Remove `focusCKBoxItem` function in ckbox package.

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-ckbox/src/ckboxcommand.ts#L394-L424

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by arkflpc** [comment]
Revert of #14718 should be enough.
