### ISSUE TITLE
We can remove 'use strict' since we use ES6 modules

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#149]
AFAIR (needs to be confirmed) ES6 modules enable strict mode out of the box.

**Comment by oskarwrobel** [comment]
According to documentation http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code 

> Module code is always strict mode code.

So looks like we can remove 'use strict' from source code, but probably we need to add it automatically to CommonJS and AMD versions of builded packages.

We can also configure eslint for it http://eslint.org/docs/rules/strict

**Comment by Reinmar** [comment]
Thanks for confirming this.

> We can also configure eslint for it http://eslint.org/docs/rules/strict

We use JSHint (and JSCS).

**Comment by Reinmar** [comment]
TODO: Update https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style#strict-mode.

**Comment by Reinmar** [comment]
Wiki updated: https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style/_compare/c5276b3bec1bcd7a8f8408c2cf0be0e3d6735417...466587838d548bb9e716eb67e32c2575719c840d
