### ISSUE TITLE
Creating indentation in list is broken 

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#14905]
## 📝 Provide detailed reproduction steps (if any)

1. Go to Safari
2. Go to http://127.0.0.1:8080/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
3. Create simple list.
4. Put selection into first indentation and press `Tab`

https://github.com/ckeditor/ckeditor5/assets/47000454/569a08cf-ac39-4004-9a5f-8267ad6d2fdb

### ✔️ Expected result

Should not scroll away

### ❌ Actual result

It scrolls away and put focus outside editor

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It's an expected behavior for the Tab key to leave the editor (if it has no other action assigned within it). It's part of the accessibility requirements.
