### ISSUE TITLE
Pasting table into a list results in numbers going into the table

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#14909]
## 📝 Provide detailed reproduction steps (if any)

1. Open full features example in docs (or any other example including paste from office/table/list plugins): https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Copy a table from Word/Excel
3. Paste the table into a list

### ✔️ Expected result

The numbers/bullets will not go into the table

### ❌ Actual result

Numbers/bullets appear inside the table
<img width="982" alt="Screenshot 2023-08-31 at 14 28 25" src="https://github.com/cksource/ckeditor5-commercial/assets/66953380/f7551498-3dd7-44d2-996b-023de9b05498">

## 📃 Other details

* Browser: Chrome, Firefox
* OS: MacOS
* First affected CKEditor version: 39.0.0 (so it's not a recent regression)

Introduced by this: https://github.com/ckeditor/ckeditor5/pull/14564

**Comment by Reinmar** [comment]
This is not related to Word itself, but CSS of list bullets.

![](https://github.com/ckeditor/ckeditor5/assets/156149/86cb625d-3332-47e8-96ff-45182376d733)

For this HTML:

```html
<figure class="table" style="float:left;width:11.49%;">
    <table class="ck-table-resized">
        <colgroup><col style="width:33.33%;"><col style="width:33.33%;"><col style="width:33.34%;"></colgroup>
        <tbody>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        </tbody>
    </table>
</figure>
<ol>
    <li>
        sdfsd
    </li>
    <li>
        sdf
    </li>
    <li>
        sdf
    </li>
    <li>
        sdf
    </li>
</ol>
```

**Comment by Reinmar** [comment]
There were issues reported for list bullets rendering inside tables or images, AFAIR. 

This is a sad CSS issue without an easy solution.

CKE4 for comparison:

![](https://github.com/ckeditor/ckeditor5/assets/156149/dfa590af-860e-493e-bf1a-6dfc9d772bbf)

**Comment by Reinmar** [comment]
DUP of #8412.
