### ISSUE TITLE
SyntaxError: Cannot declare a const variable twice: 'x'. on some old device like iphone with 10.3.x

### ISSUE THREAD

**Issue by steve3d** [ckeditor/ckeditor5#1491]
## Is this a bug report or feature request? (choose one)

this is  a 🐞Bug report 

## 💻 Version of CKEditor

all latest version till up today. and any build version, either official or custom build

## 📋 Steps to reproduce

1. simple way to reproduce, use a ios simulator with 10.3.x version and navigate to any demos on ckeditor.com, then you will see this error. of course the actual variable name changes between different builds.
```
SyntaxError: Cannot declare a const variable twice: 'x'
```

## ✅ Expected result
ios simulator with ios 10.3.x is not a stone age version, it should run the editor without any problem.

## ❎ Actual result
none of the official demo can run under this version. they all give the exact same error.

**Comment by steve3d** [comment]
and I think this is a webpack code generation problem?

**Comment by Reinmar** [comment]
Safari in iOS10 had a very nasty bug in its JS parser. If you need to support it, the only thing that will work is transpiling to ES5.

Also, please note that we don't support iOS10: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/browser-compatibility.html#mobile-environment
