### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by ArtemDid** [ckeditor/ckeditor5#14929]
## 📝 Provide detailed reproduction steps (if any)

```
const response = await axios.post("https://docx-converter.cke-cs.com/v1/convert", {
				html: htmlContent,
				conversion: "dynamic",
			}, {
				responseType: "arraybuffer",
				headers: {
					"Authorization": `${token}`,
					maxBodyLength: Infinity,
					maxContentLength: Infinity,
				},
				maxBodyLength: Infinity,
				maxContentLength: Infinity,
			});
```

When I send a request to this endpoint, I get a response:

```
response: {
    status: 413,
    statusText: 'Payload Too Large',
    headers: {
      date: 'Tue, 05 Sep 2023 09:19:03 GMT',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'access-control-allow-methods': 'POST, OPTIONS, PATCH',
      'access-control-allow-origin': '*',
      'access-control-allow-headers': 'Content-Type, Authorization, X-CS-App-Id'
    },
```
What should be the maximum length of the body if I have for htmlContent.length = 20471078?
Or maybe there are additional settings to get a successful result with such an html length?

**Comment by FilipTokarski** [comment]
Hello @ArtemDid, thank you for the report. Please note that our document conversion services are a premium feature and this issue tracker is dedicated for the open source part of the CKEditor 5 ecosystem.
If you are a licensed or trial user, please [contact our support channel](https://ckeditor.com/contact/) and describe the issue in details, together with reproduction steps - our team will get back to you as soon as possible.
