### ISSUE TITLE
Cannot build in Nuxt 3

### ISSUE THREAD

**Issue by duongxinh2003** [ckeditor/ckeditor5#14936]
## 📝 Provide detailed reproduction steps (if any)

Hi,
I made an effort to set up CKEditor 5 based on Nuxt 3. I ran by command `npm run dev` with no problem. But, when I built my project by the command `npm run build`, an error occurred: ENOENT: no such file or directory. 
Here is my reproduction: [https://stackblitz.com/edit/github-xuxuvn](https://stackblitz.com/edit/github-xuxuvn)
<img width="1680" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/25058528/d8d09da0-46e8-4f8b-b7d0-660a26e1fd71">

### ✔️ Expected result

Project build success

### ❌ Actual result

Project build error

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome
* OS: MacOS Ventura 13.5
* First affected CKEditor version: 39.0.1
* Installed CKEditor plugins: 39.0.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Hi @duongxinh2003,

are you using Vite in your Nuxt 3 project? Are you using [our Vite plugin](https://github.com/ckeditor/vite-plugin-ckeditor5) for building CKEditor 5 from source?

We also have an example of building CKEditor 5 from source using Nuxt 3 + Vite + our Vite plugin you can refer to: https://github.com/ckeditor/vite-plugin-ckeditor5/tree/master/playground/nuxt-sample

Please, let me know if this helps with your issue

**Comment by duongxinh2003** [comment]
Hi @LukaszGudel ,
I resolved in this mention
[https://github.com/nuxt/nuxt/issues/23029#issuecomment-1707953697](https://github.com/nuxt/nuxt/issues/23029#issuecomment-1707953697)
Thanks!
