### ISSUE TITLE
Pasting from Word  creates an anchor link in ckeditor

### ISSUE THREAD

**Issue by suhailk4** [ckeditor/ckeditor5#14934]
When we paste text from Microsoft word in ckeditor5, sometimes pasted text appears under ** anchor tag ** when it is not link in office. Is there any config to override that?

The do for pasted text looks like below:

```
<a name="OLE_LINK47">
    <span style="font-family:Calibri, sans-serif;font-size:24.0pt;">
        <span style="mso-ansi-language:EN-US;mso-bookmark:OLE_LINK46;" lang="EN-US" dir="ltr">This is a dummy text</span>
    </span>
</a>
```

**Comment by suhailk4** [comment]
This usually happen when same text is copy and pasted twice , therefore adding <a> tag .

**Comment by Witoso** [comment]
Thanks for the report, could you share your editor's setup (plugins used), and ideally the source Word file with an example. It will help us to understand the problem better.

**Comment by suhailk4** [comment]
`Editor.builtinPlugins = [
  Alignment,
  Autoformat,
  Autosave,
  Link,
  AutoLink,
  Bold,
  DataSchema,
  Essentials,
  FindAndReplace,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  Indent,
  IndentBlock,
  Italic,
  List,
  ListProperties,
  MediaEmbed,
  Paragraph,
  RemoveFormat,
  SourceEditing,
  SpecialCharacters,
  SpecialCharactersArrows,
  SpecialCharactersCurrency,
  SpecialCharactersEssentials,
  SpecialCharactersLatin,
  SpecialCharactersMathematical,
  SpecialCharactersText,
  StandardEditingMode,
  Style,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  TodoList,
  Underline,
];

// Editor configuration.
Editor.defaultConfig = {
  toolbar: {
    items: [
      'bold',
      'italic',
      'underline',
      'link',
      'removeFormat',
      '|',
      'heading',
      'style',
      'fontFamily',
      'fontSize',
      'fontColor',
      'fontBackgroundColor',
      'highlight',
      '|',
      'bulletedList',
      'numberedList',
      'alignment',
      'outdent',
      'indent',
      '|',
      'insertTable',
      'undo',
      'redo',
      'annotation',
    ],
  },
  language: 'en',
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'tableCellProperties',
      'tableProperties',
    ],
  },
};

export default Editor;`

**Comment by Witoso** [comment]
It's highly unlikely that we insert the content on paste, most likely it exists in the Word doc (check the copied content in some clipboard viewer software). As I can see, you're using `GeneralHtmlSupport`, most likely your config allows this attribute.
