### ISSUE TITLE
ImageInline attribute conversion is not correct

### ISSUE THREAD

**Issue by VitaliyYurakh** [ckeditor/ckeditor5#14938]
## 📝 Provide detailed reproduction steps (if any)

# ImageInline

I'm adding extra attribute (size) to the imageInline element:
![code](https://github.com/ckeditor/ckeditor5/assets/109657047/6eb0944e-0c51-4b5e-b805-03347b46645f)

When I add ImageInline, everything is displayed normally in **Model**
![model](https://github.com/ckeditor/ckeditor5/assets/109657047/34a3f3f9-4f7c-47bd-aeab-13fb3487b581)

But in **View**, the attribute was added to the `<span>` tag instead of the `<img>` tag as expected. Also if you call **getData** method to get html then the attribute will already be in `<img>` as it should be.
![view](https://github.com/ckeditor/ckeditor5/assets/109657047/ff9af829-19f4-49e2-bc73-eff7f51a1e43)

I may have made some mistake, I'll wait for an answer. Thank you for your attention. 

P. S. Sorry for my bad English 

### ✔️ Expected result

When adding **ImageInline**, the _size_ attribute is added to the `<img>` tag

### ❌ Actual result

When adding **ImageInline**, the _size_ attribute is added to the `<span>` tag

## 📃 Other details

* First affected CKEditor version: 39.0.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by VitaliyYurakh** [comment]
I apologize, I didn't express what I meant correctly enough. I'm not talking about the specific `"sizes"` or `"size"` attributes, but in general when adding attributes that are not originally part of the ImageInline element's schema, then they are all added to the `span` tag. (I'm using ClassicEditor )
![2](https://github.com/ckeditor/ckeditor5/assets/109657047/9672192d-e097-4868-9e23-bff0eab4ed01)

**Comment by mmotyczynska** [comment]
OK, now I understand 🙂 

If you want to add a new attribute to the `ImageInline` model element, which in editing view is added to the `<img>` instead of `<span>`, then you should create two converters. The first one is for data (this is the same as you have already created, but in `.for` change it from `downcast` to `dataDowncast`). The second one, for editing view, is a bit more complicated, see the code below (I named the new attribute "newAttribute" to make this example look more generic):
```
editor.conversion.for( 'dataDowncast' ).attributeToAttribute( {
	model: 'newAttribute',
	view: 'newAttribute'
} );

editor.conversion.for( 'editingDowncast' ).add( dispatcher => {
	dispatcher.on( 'attribute:newAttribute:imageInline', ( evt, data, conversionApi ) => {
		if ( !conversionApi.consumable.consume( data.item, evt.name ) ) {
			return;
		}

		const viewWriter = conversionApi.writer;
		const viewElement = conversionApi.mapper.toViewElement( data.item );
		const img = editor.plugins.get( 'ImageUtils' ).findViewImgElement( viewElement );

		if ( data.attributeNewValue !== null ) {
			viewWriter.setAttribute( 'newAttribute', data.attributeNewValue, img );
		} else {
			viewWriter.removeAttribute( 'newAttribute', img );
		}
	} );
} );
```

**Comment by VitaliyYurakh** [comment]
Anyway, problem solved, thank you very much for your attention.
