### ISSUE TITLE
startupMode config missing in CKE5

### ISSUE THREAD

**Issue by raq007** [ckeditor/ckeditor5#14930]
## 📝 Provide a description of the new feature
[startupMode](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-startupMode) was available in CKE4 but seems N/A in [CKE5](https://ckeditor.com/docs/ckeditor5/latest/updating/ckeditor4/ckeditor4-configuration-compatibility.html) 

We are migrating from CKE4 to CKE5 and our customers widely use this config. 

Since its missing, is there an alternate solution available ? If not, what are plans for its inclusion in CKE5 ? 

_What is the expected behavior of the proposed feature?_

Copied as-is from CKE4 [startupMode](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-startupMode)

**_The mode to load at the editor startup. It depends on the plugins loaded. By default, the wysiwyg and source modes are available._**

`E.g, config.startupMode = 'source';`

**_Defaults to 'wysiwyg'_**

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team  – any ideas for a workaround?

Let's also link to this ticket (or post the workaround) in https://ckeditor.com/docs/ckeditor5/latest/updating/ckeditor4/ckeditor4-configuration-compatibility.html.

**Comment by FilipTokarski** [comment]
What about [switching to source editing mode](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-source-editing/src/sourceediting.ts#L126) right after the initialization?
```js
ClassicEditor.create( element, {
     ...
} ).then( editor => {
    editor.plugins.get( 'SourceEditing' ).isSourceEditingMode = true;
} );
```

**Comment by raq007** [comment]
Thanks @FilipTokarski and @Reinmar, looks like the above solution/workaround does what we need.

**Comment by Witoso** [comment]
@FilipTokarski could you contribute it to the docs. I think link to your comment will be enough.

**Comment by raq007** [comment]
@Witoso @FilipTokarski @Reinmar sorry to open conversation on this thread again.

Although the above workaround allows us to switch to source mode right after initialization, it does not keep the 'Find and Replace' and 'Select All' enabled in source mode.

In CKE4, when we are in source mode, the 'Find', 'Replace' and 'Select All' plugins were always kept enabled, so that we can easily edit the content.

Is there a plan to enable these options in CKE5 also ?

**Comment by Witoso** [comment]
Not right now, please check #10329.

**Comment by raq007** [comment]
Thank you!!
