### ISSUE TITLE
About hiding the "Powered by CKEditor" logo

### ISSUE THREAD

**Issue by satohironori** [ckeditor/ckeditor5#14945]
## hide the "Powered by CKEditor" logo
I would like to hide the "Powered by CKEditor" logo. Is there a problem with the terms and conditions?
I don't use paid plugins.

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser: …Not relevant
* OS: …Not relevant
* CKEditor version: …Not relevant
* Installed CKEditor plugins: …Not relevant

**Comment by Reinmar** [comment]
Why do you want to hide the logo?

**Comment by satohironori** [comment]
This is because you want to avoid confusion by being redirected to an unknown URL when an uninformed user clicks on it.

Is it against the rules to remove the logo?

**Comment by Reinmar** [comment]
While I understand that it may be concerning to you, CKEditor 5 is deployed already in many projects that use it on the open-source license and we didn't see negative feedback from the end users.

Also, as far as I understand, you use CKEditor 5 under the open-source license, which means using it for free. We consider it a fair thing to ask in advance to display the logo. This helps us increase brand awareness among the users which in turn helps us ensure the sustainability of the project.

**Comment by lipingshan** [comment]
This logo affects the aesthetics of the interface.

Aren't your most direct users developers?

For users who only use basic functions，

My suggestion is that you should provide options to show or hide this logo.

This is more conducive to the promotion of your product.

Otherwise, I would rather pinch my nose and use version 37.

**Comment by Witoso** [comment]
@lipingshan we kindly disagree. We have many types of users. If you wish you can change the look, [there's a guide for that](https://ckeditor.com/docs/ckeditor5/latest/support/licensing/managing-ckeditor-logo.html#how-to-configure-the-layout-of-the-powered-by-ckeditor-logo), and if you want to hide it, consider buying the license, and supporting our project.
