### ISSUE TITLE
"docData;DOCY" blobs from onlyoffice are pasted in the editor field

### ISSUE THREAD

**Issue by CptLausebaer** [ckeditor/ckeditor5#14947]
## 📝 Provide detailed reproduction steps (if any)

We use Drupal as our CMS and using ckeditor as a WYSIWG field for content creation.
Our editors are preparing their work in documents provided and shared via onlyoffice (backed by our ownclud instance).

We have found blobs in the class attributes of HTML elements on some pages. These blobs seem to contain metadata from the document from which the content was copied. If you take the blob and decode it with base64 and encode the result as 'utf-16' you can read some text fragments. These fragments can contain **chat, comments** or parts of the onlyoffice document, which would result in a leak of data.

Links that indicate how the blob is structured:
https://github.com/ONLYOFFICE/sdkjs/blob/master/word/apiDefines.js#L139
https://github.com/ONLYOFFICE/sdkjs/blob/master/word/Editor/Serialize2.js#L7553

1. Go to https://www.onlyoffice.com/de/see-it-in-action.aspx to see the onlyoffice demo page.
2. Select some random text from the document "https://www.onlyoffice.com/de/see-it-in-action.aspx" (i used "uffällige Schlag") and copy it to your clipboard (`ctrl+c`)
3. Go to https://ckeditor.com/ckeditor-5/demo/feature-rich/ to see the demo page.
4. Paste the clipboard in the editor field (`ctrl+v`)
5. Look at the source of the pasted element in dev-tools.

If you look into your clipboard, there is a target "text/html" which contains the copied content with the blob. There is an additional target with only the blob under "chromium/x-web-custom-data" or "application/x-moz-custom-clipdata"

### ✔️ Expected result

_What is the expected result of the above steps?_

The copied content is pasted into the editor.

### ❌ Actual result

_What is the actual result of the above steps?_

The pasted content contains a blob in the class attribute. This blob contains unwanted data.

```
<span style="color:#3a1d15;font-family:'Georgia';font-size:24pt;">
<span style="mso-style-textfill-fill-color:#3a1d15;" class="docData;DOCY;v5;2575;BQiAAgAAEZMGAAAGlwYAAAMTCAAABSEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8EAAAACgQAAAEEAAAAAAAAAAMQAAAASwBhAHIAaQBuACAATABpAAIEAAAASwBMAARIAAAAOABjADMAMwBkADUANQAxAC0AOAAyADAAMQAtADQAZQBjAGQALQA5ADMANwBiAC0AOAAzADIAMQA2AGMANQA3AGQANwA0ADMADA4AAABUAGUAYQBtAGwAYQBiAAUoAAAAMgAwADIAMAAtADAAMQAtADEANABUADEANQA6ADQAOAA6ADAAMABaAAgBAAAAAAsEAAAA72DrIQZcAAAASAD2AHIAdAAgAHMAaQBjAGgAIABlAGkAbgAgAGIAaQBzAHMAYwBoAGUAbgAgAGgAbwBjAGgAZwBlAHMAdABvAGMAaABlAG4AIABhAG4ALAAgAG8AZABlAHIAPwAJtAIAAAA+AQAAAxQAAABMAHUAdAB6ACAASwByAGEAdQBzAAIEAAAATABLAARIAAAANQBiADkAMAA3ADEAMgBmAC0AYgA3AGIAMwAtADQAYQA0ADQALQBhADUAZgBmAC0ANwBlAGYAMQAzAGUAZgAwADUANwA5ADAADA4AAABUAGUAYQBtAGwAYQBiAAUoAAAAMgAwADIAMAAtADAAMQAtADEANABUADEANQA6ADUAMgA6ADAAMABaAAgBAAAAAAsEAAAARi67KAZOAAAARQBpAG4AdgBlAHIAcwB0AGEAbgBkAGUAbgAuACAATQBhAGMAaABlAG4AIAB3AGkAcgAgAGUAcwAgAGUAaQBuAGYAYQBjAGgAZQByAC4ADigAAAAxADkANwAwAC0AMAAxAC0AMAAxAFQAMAAwADoAMAAwADoAMAAwAFoAAGwBAAADFAAAAEwAdQB0AHoAIABLAHIAYQB1AHMAAgQAAABMAEsABEgAAAA1AGIAOQAwADcAMQAyAGYALQBiADcAYgAzAC0ANABhADQANAAtAGEANQBmAGYALQA3AGUAZgAxADMAZQBmADAANQA3ADkAMAAMDgAAAFQAZQBhAG0AbABhAGIABSgAAAAyADAAMgAwAC0AMAAxAC0AMQA0AFQAMQA1ADoANQAzADoAMAAwAFoACAEAAAAACwQAAACmKLRIBnwAAABEAGkAZQBzAGUAcgAgAFMAYQB0AHoAIABpAHMAdAAgAHMAdQBwAGUAcgAhACAARQByACAAZwBlAGYA5ABsAGwAdAAgAG0AaQByAC4AIABCAGkAdAB0AGUAIADkAG4AZABlAHIAbgAgAFMAaQBlACAAbgBpAGMAaAB0AHMADigAAAAxADkANwAwAC0AMAAxAC0AMAAxAFQAMAAwADoAMAAwADoAMAAwAFoADigAAAAxADkANwAwAC0AMAAxAC0AMAAxAFQAMAAwADoAMAAwADoAMAAwAFoAAAAAAHgBAAAAcwEAAAGHAAAAAAEAAQYAAAAABQEACQYAAAAAGgZmAAAAAAEBBAYQAAAARQBsAGUAcABoAGEAbgB0AAUGEAAAAEUAbABlAHAAaABhAG4AdAAHBhAAAABFAGwAZQBwAGgAYQBuAHQABgYQAAAARQBsAGUAcABoAGEAbgB0AAkDDQ0NJgQGAAAAGwYAAAAALAEAAuIAAAAFvwAAAAGQAAAAAAEBBAYOAAAARwBlAG8AcgBnAGkAYQAFBg4AAABHAGUAbwByAGcAaQBhAAcGDgAAAEcAZQBvAHIAZwBpAGEABgYQAAAARQBsAGUAcABoAGEAbgB0AAgEMAAAAAkDOh0VDQYIAAAAMgAwADEANQAmBAYAAAAZBgoAAABkAGUALQBEAEUAHAYGAAAAAQEQAwG/CCUAAAAAIAAAAHUAZgBmAOQAbABsAGkAZwBlACAAUwBjAGgAbABhAGcABQoAAAABAAAAAAgAAAAABQoAAAAIBQAAAA0AAAAACgAAAAAAAAAAEQAAAADqAQAAAC0AAAABBgAAAAAJBhsAAAAnBBQBAAALAQEcAQAoBAAAAAAdAQApBMgAAAAbBgAAAAABfwAAAAQGCgAAAEEAcgBpAGEAbAAFBgoAAABBAHIAaQBhAGwABwYKAAAAQQByAGkAYQBsAAYGCgAAAEEAcgBpAGEAbAATAQEIBBYAAAAWBBYAAAAZBgoAAABkAGUALQBEAEUAGgYKAAAAYQByAC0AUwBBABsGCgAAAGUAbgAtAFUAUwACLwEAAAAqAQAAAQgAAAAyADAAMQA1AAIYAAAASAAxAF8AYwBoAGEAcgBhAGMAdABlAHIACQEAAAABEggAAAAyADAAMQA2AAXLAAAABAYmAAAATwBwAGUAbgAgAFMAYQBuAHMAIABFAHgAdAByAGEAYgBvAGwAZAAFBiYAAABPAHAAZQBuACAAUwBhAG4AcwAgAEUAeAB0AHIAYQBiAG8AbABkAAcGJgAAAE8AcABlAG4AIABTAGEAbgBzACAARQB4AHQAcgBhAGIAbwBsAGQABgYmAAAATwBwAGUAbgAgAFMAYQBuAHMAIABFAHgAdAByAGEAYgBvAGwAZAAIBDwAAAAJA+9BNhkGCgAAAGUAbgAtAEcAQgAGEgAAAAEGAAAAAAkGAAAAABsGAAAAABMBAAAAAQ==">
<strong>uffällige Schlag</strong>
</span>
</span>
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

I am unsure if this is an issue for ckeditor or that onlyoffice should look into it.

But there is a potential security risk of leaking data and information.

Is there a way to strip these classes when copying content to the editor?

## 📃 Other details

* Browser: Firefox 117.0 (64-Bit), Chromium 116.0.5845.140 (Offizieller Build) snap (64-Bit)
* OS: Ubuntu 20.04.6 LTS (Focal Fossa)
* First affected CKEditor version: 4.18.0 (bundle with drupal 9.5.10)
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
What you see is precisely the content that is in the clipboard (can be checked with a clipboard viewer software). Therefore this is what OnlyOffice provides when copying.

> We use Drupal as our CMS and using ckeditor as a WYSIWG field for content creation.

I'm not sure 100% how config work in Drupal, but on the CKEditor side we have [quite granular control what is accepted](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html#configuration). So you could decide whether this class is not allowed, etc. You could also consult OnlyOffice team.
