### ISSUE TITLE
Depreciate Old `List` Plugins in Favor of `DocumentList` Equivalents

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#14942]
## Provide a description of the task

Part of #14632.

### Scope
1. Rename existing `List*` plugins to `LegacyList*` plugins.
  This change will allow integrators to fall back to the old solution if they encounter any issues after an update.
2. Promote `DocumentList*` Plugins (by renaming them to `List*`)
  This should enable document lists for all integrations. Assuming we achieved feature parity, users should not miss any feature.
3. Support current configurations:
    - Introduce `DocumentList*` plugins that pull the new `List*` plugins as a requirement.
    - If an integration currently uses the `DocumentList`, it should continue to work without necessitating any configuration changes.
    - `console.warn`ing should suggest updating configurations.
4. Completely remove the `ListStyle` plugin. It has been deprecated for some time now.
5. Write migration guide. 
    * Mention the possibility of using `LegacyList` in case of issues.
    * Mention the `multiBlock` config.
 

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by arkflpc** [comment]
Migration guide can be developed in parallel with the list renaming.

**Comment by godai78** [comment]
Can you have a look at changes in the docs, too, after this is done? Probably needs some tinkering in the Common API sections: https://github.com/ckeditor/ckeditor5/issues/14960
