### ISSUE TITLE
How to create dialog for custom plugins

### ISSUE THREAD

**Issue by raq007** [ckeditor/ckeditor5#14951]
## Provide a description of the task
We developed a good number of custom plugins in CKE4 using [CKEDITOR.dialog](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog.html)

_What steps should be taken to fulfill the task?_

Now we are migrating to CKE5 and were wondering if there's a way to develop such custom dialogs in CKE5 also ? I searched the documentation and tried to find examples on your repository but could not find any.

## 📃 Other details

An example of a dialog that we developed in CKE4 looks like this -

![Screenshot 2023-09-07 at 5 34 30 PM](https://github.com/ckeditor/ckeditor5/assets/12660692/ab0a396d-b770-412c-a250-b2cd65c32e87)

To give more context, this dialog should show a varying length list of options to user and should have a scrollbar if the list exceeds dialog size.

Likewise, there's another custom plugin developed in CKE4 whose dialog looks like this - 

![Screenshot 2023-09-08 at 11 08 34 AM](https://github.com/ckeditor/ckeditor5/assets/12660692/073afebe-0b04-49a3-89ef-7efd40a4dd80)

**Comment by Witoso** [comment]
We don't have dialog system for the CKEditor 5. Other components, like balloons, need to be used right now. We gather the interest right now, so please +1 the #14973. As a side note, it most probably will come sooner than later as we started internal discussions about this.
