### ISSUE TITLE
Docs issue report from "tutorials/crash-course/events-and-observables.html"

### ISSUE THREAD

**Issue by EZsuhan** [ckeditor/ckeditor5#14952]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/tutorials/crash-course/events-and-observables.html#binding-properties

### Project version

39.0.2

### Is the information outdated? How?

Look like sample code have error , Because the button in toolbar default will become Active.
```
command.on( 'change:isEnabled', ( event, propName, newValue, oldValue ) => {
    button.isOn = newValue;
} );
```
Maybe is it?
```
command.on( 'change:isEnabled', ( event, propName, newValue, oldValue ) => {
    button.isEnabled = newValue;
} );
```

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by filipsobol** [comment]
Thank you for taking the time to report this issue. I submitted a PR to fix it.
