### ISSUE TITLE
What is the earliest version of chrome that you think CK 5 will work with?

### ISSUE THREAD

**Issue by addsimm** [ckeditor/ckeditor5#1495]
Other: question:

What is the earliest version of chrome that you think CK 5 will work with?

I know windows XP is limited to version49 or so, would you expect CK 5 to work with that, or should I give up?

**Comment by pjasiun** [comment]
Unfortunately, CKEditor 5 supports only the latest stable release of the Chrome browser, which is Chrome 71 at the moment. See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/browser-compatibility.html

**Comment by Reinmar** [comment]
What @pjasiun meant was that only the latest version of Chrome is officially supported. However, CKEditor 5 should work in older versions too. In which of them? We don't test that, so we can't answer this question.
