### ISSUE TITLE
codemirror missing in CKE5

### ISSUE THREAD

**Issue by raq007** [ckeditor/ckeditor5#14967]
## 📝 Provide a description of the new feature

[CodeMirror](https://ckeditor.com/cke4/addon/codemirror) plugin seems missing in CKE5, it is not listed on the [Plugin compatibility](https://ckeditor.com/docs/ckeditor5/latest/updating/ckeditor4/ckeditor4-plugin-compatibility.html) page either. 
 
_What is the expected behavior of the proposed feature?_

We would like to see Syntax Highlighting in 'Source' mode, similar to how CKE4 did. 

Is this configurable somehow or planned to be included in CKE5 ? I could not find it listed on [Roadmap](https://github.com/ckeditor/ckeditor5-design/issues/172) either.

Also I see that there is an issue open to implement [CodeSnippet](https://github.com/ckeditor/ckeditor5/issues/5769) feature which is supposed to add Syntax Highlighting for [CodeBlocks](https://github.com/ckeditor/ckeditor5/issues/436), so might as well do it for the 'Source editing' plugin ?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thank you for info! There are no immediate plans for this right now, please +1 the following issue: #13077.

**Comment by raq007** [comment]
Hi @Witoso thank you for the quick response and link to open issue.
