### ISSUE TITLE
Undo (CTRL + Z) and Redo (CTRL + Y) not working in source edit mode

### ISSUE THREAD

**Issue by Chiragp185** [ckeditor/ckeditor5#14971]
I am currently using CKEditor 5 as a core module on my Drupal site. The content writer toggles the source editing mode to make changes to the HTML structure or the content inside the HTML tags. The undo/redo option is very useful to track changes and edit. This used to work for CKEditor 4 but not after upgrading to 5. 

Reproduction Steps 

1. Toggle the CKEditor 5 source editing plugin
2. Make some changes in the HTML code
3. Press CTRL + Z to undo the changes or CTRL+Y to redo the changes.

✔️ Expected result

CTRL + Z should undo the changes in source editing mode.
CTRL + Y should redo the changes in source editing mode

❌ Actual result

No change in the editor.

📃 Other details

* First affected CKEditor version: CKEditor 5. Undo worked in the previous version (CKEditor 4).

**Comment by Witoso** [comment]
Not possible right now, we are gathering interest here: #13700.
