### ISSUE TITLE
nested editor

### ISSUE THREAD

**Issue by wangnan0916** [ckeditor/ckeditor5#14987]
## I want to use two different editors nested.

I now have a scene. I wrote a plugin in CKEditor5 to insert a div in the editor and render a React APP. The DOM inside this div will be taken over by React.

But within these React apps, I also need to handle some simple text input such as bold and oblique.

At first I thought of a solution. In these places that need to be inputed, create a Ballon Editor to use it to process simple text input.

But I found that this nested situation could not input the content. Seems to be intercepted.

One of the main reason I inserted into the React component in CKE is in the processing logic processing. The efficiency is much more convenient than CKE.

![iShot_2023-09-13_21 59 13](https://github.com/ckeditor/ckeditor5/assets/48309229/8795429f-183b-4a48-9fe8-a1b5d6beff66)

```javascript
// plugin code
_defineSchema() {
    const { schema } = this.editor.model;
    schema.register('ReactWidget', {
      inheritAllFrom: '$blockObject',
      allowAttributes: [
        REACT_WIDGET_ATTR.DATA_WIDGET_ID,
        REACT_WIDGET_ATTR.DATA_WIDGET_NAME,
      ],
    });
  }

_defineConversation() {
  const { editor } = this;
  const { conversion } = editor;
  conversion.for('upcast').elementToElement({
    model: 'ReactWidget',
    view: {
      name: 'div',
      classes: ['react-widget'],
    },
  });
  conversion.for('dataDowncast').elementToElement({
    model: 'ReactWidget',
    view: {
      name: 'div',
      classes: ['react-widget'],
    },
  });
  conversion.for('editingDowncast').elementToElement({
    model: 'ReactWidget',
    view: (modelElement, { writer }) => {
      const attribute = new Map(modelElement.getAttributes());
      const widgetId = attribute.get(
        REACT_WIDGET_ATTR.DATA_WIDGET_ID,
      ) as string;
      const widgetName = attribute.get(
        REACT_WIDGET_ATTR.DATA_WIDGET_NAME,
      ) as string;
      const div = writer.createContainerElement('div', {
        class: 'react-widget',
        [REACT_WIDGET_ATTR.DATA_WIDGET_ID]: widgetId,
        [REACT_WIDGET_ATTR.DATA_WIDGET_NAME]: widgetName,
      });
      const reactDiv = writer.createRawElement('div', {
        class: 'widget-container',
      });
      writer.insert(writer.createPositionAt(div, 0), reactDiv);

      setTimeout(() => {
        this.renderReactWidget(widgetId, widgetName);
      }, 0);
      return toWidget(div, writer, { label: 'react-widget' });
    },
  });
}

renderReactWidget(widgetId: string, widgetName: string) {
  const container = document.querySelector(
    `[${REACT_WIDGET_ATTR.DATA_WIDGET_ID}=${widgetId}] .widget-container`,
  );
  const root = createRoot(container as HTMLElement);
  const Comp = REACT_CK_WIDGET[widgetName];
  root.render(<Comp />);
  activeManager.add(widgetId, {
    widgetId,
    widgetName,
    root,
  });
}
```

```javascript
// React Component
function ButtonLink(props) {
  const onToolbarItemClick = (name: string) => {
    console.log('onToolbarItemClick', name);
  };

  return (
    <ReactWidgetContainer>
      <ReactWidgetToolbar tools={toolbarConfig} onClick={onToolbarItemClick} />
      <div className={css.buttonLinkContainer}>
        <div
          className={css.buttonLink}
          contentEditable={true}
          ref={(ref) => {
            CKEDITOR.BalloonEditor.create(ref as HTMLElement);
          }}
        >
          input text
        </div>
      </div>
    </ReactWidgetContainer>
  );
}
```

## 📃 Other details

* Browser: Chrome
* OS: MacOS
* CKEditor version: 5

**Comment by Witoso** [comment]
You used `createRawElement` which, [as per docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_rawelement-RawElement.html):

> The raw elements work as data containers ("wrappers", "sandboxes") but their children are not managed or even recognized by the editor.

If you need to create some feature with editing capability, you need to use the editor's API and widgets.

**Comment by wangnan0916** [comment]
Thank you for your answer.

According to the explanation in the document, my understanding is that RawElement should have no relation with his editor, but now his editor will affect the input behavior of the editor inside RawElement....💔

Should the editor not handle anything that happened in RawElement?

> The raw elements work as data containers ("wrappers", **"sandboxes"**) but their children are not managed or even recognized by the editor.

PS:I was also heartbroken💔 by the complexity of the UI operations of CKE.

**Comment by Witoso** [comment]
Hey, thanks for feedback, this is something that we plan to enhance in the future.

TBH, I'm not entirely sure what may cause an issue with writing, my bet is something going on in the intersection of the editors and typing. cc @niegowski / @DawidKossowski, food for thought.

**Comment by wangnan0916** [comment]
If the UI could be chosen by the developers themselves, such as React, Vue, etc., and CKE provided some APIs to interact with it, that would be great. The mental burden would be less.

PS: This is a personal opinion and may not necessarily be correct. I look forward to your improvements.

**Comment by Witoso** [comment]
Being fully headless is one of the solutions that we are considering. Remember that the mental burden would shift towards other areas you don't need to think about right now, accessibility, focus/selection management, etc. There's no silver bullet.

**Comment by wangnan0916** [comment]
That makes sense, it requires finding a good balance point. 🤔️
