### ISSUE TITLE
Sticky panel incorrect positioning when scrolling

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#14984]
## 📝 Provide detailed reproduction steps (if any)

1. Open http://localhost:8125/ckeditor5-ui/tests/manual/poweredby/poweredby.html
2. Scroll to make the toolbar sticky

### ✔️ Expected result

Sticky toolbar starts from the top-left corner.

### ❌ Actual result

Sticky toolbar incorrectly positioned:

https://github.com/ckeditor/ckeditor5/assets/32898551/08af8ddf-ec12-4e99-9408-f41575759acc

<img width="589" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/32898551/8a225c01-165d-44c5-a337-40d064d905f5">

## 📃 Other details

* Browser: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Duplicate: #14570.
