### ISSUE TITLE
Div Container Manager plugin missing in CKE5

### ISSUE THREAD

**Issue by raq007** [ckeditor/ckeditor5#14982]
## 📝 Provide a description of the new feature
[Div Container Manager](https://ckeditor.com/cke4/addon/div) was an official plugin provided and supported in CKE4.

It is widely used in our product by customers. We have also integrated it with some of our custom plugins.

_What is the expected behavior of the proposed feature?_

Looks like this plugin is not yet available and we were wondering if there is a plan to introduce this functionality in CKE5 ?

Thanks in advance!

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
We are gathering the interest here: #6462.

**Comment by raq007** [comment]
Thank you !! @Witoso
