### ISSUE TITLE
How would you add/remove a class attribute from the table tag and not just the figure element?

### ISSUE THREAD

**Issue by matbk49751** [ckeditor/ckeditor5#14990]
When I apply a class attribute onto the table tag, ckeditor5 instead applies it to the figure element. So now, when I remove the attribute, it only removes it from the figure element not the table tag after I save in Drupal. How can I solve this. My code is below. Let me know if you have questions. Thank you.

If you choose to not read the below code. Below are screenshots of what it's doing.

Before:
![before](https://github.com/ckeditor/ckeditor5/assets/114105349/435a0577-1789-43dd-a9be-fc257684849f)

After:
![after](https://github.com/ckeditor/ckeditor5/assets/114105349/e0989ada-b411-41fb-837c-0ad8fbb42282)

Source:
![source](https://github.com/ckeditor/ckeditor5/assets/114105349/fd479600-d898-4552-94ad-3da3e27c55e3)

`		

    const editor = this.editor;
    const model = editor.model;
    const schema = model.schema;
    
    schema.extend('table', {
        inheritAllFrom: '$blockObject',
        allowAttributes: ['class'],
    });
    
    const conversion = this.editor.conversion;
    
    conversion.for( 'editingDowncast' )
    .attributeToAttribute({
        model: 'class',
        view: 'class'
    });
    
    conversion.for( 'dataDowncast' )
    .attributeToAttribute({
        model: 'class',
        view: 'class'
    });
    
    conversion.for( 'upcast' ).attributeToAttribute({ 
        view: 'class',
        model: 'class'
    });
     
    editor.commands.add('setClass', new SetClassCommand(editor));

    constructor(editor) {
        super(editor);
    }

    refresh() {
        const model = this.editor.model;
        const tableUtils = this.editor.plugins.get('TableUtils');
        const selectedCells = tableUtils.getSelectionAffectedTableCells(model.document.selection);
        const isInTable = selectedCells.length > 0;
        this.isEnabled = isInTable;
        const selection = model.document.selection;
        const table = selection.getFirstPosition().findAncestor('table');
        this.value = this._getValue(table);
    }

    execute(options = {}) {
        const editor = this.editor;
        const model = this.editor.model;
        const selection = model.document.selection;
        const value = 'custom-class';
        const table = selection.getFirstPosition().findAncestor('table');
        model.change(writer => {
            if (this.value) {
                writer.removeAttribute('class', table);           
            }
            else {
                writer.setAttribute('class', value, table);
            }
        });
    }

    _getValue(table) {
        if (!table) {
            return;
        }
        const value = table.getAttribute('class');
        if (value === 'custom-class') {
            return true;
        }
        return false;
    }
`

* Browser: Chrome
* OS: Windows 10
* CKEditor version: "ckeditor5": "~35.1.0",
* Installed CKEditor plugins: Classic editor

**Comment by matbk49751** [comment]
Hi Everyone, what a crazy day. I figured out the solution for this. The below thread was extremely helpful!
https://github.com/ckeditor/ckeditor5/issues/3235

Below is the corrected code:

`const editor = this.editor;
const model = editor.model;
const schema = model.schema;

schema.extend('table', {
    inheritAllFrom: '$blockObject',
    allowAttributes: ['class'],
});

const conversion = this.editor.conversion;

        conversion.for( 'upcast' ).attributeToAttribute({ 
            view: {
                name: 'table',
                key: 'class',
                value: 'custom-class'
            },
            model: {
                key: 'class',
                value: viewElement => viewElement.getAttribute( 'class' )
            }
        })

        conversion.for( 'dataDowncast' ).add( dispatcher => {
            dispatcher.on('attribute:tableStriped:table', ( evt, data, conversionApi ) => {
                const { item, attributeNewValue } = data;
                const { mapper, writer } = conversionApi;
                if (!conversionApi.consumable.consume(item, evt.name)) {
                    return;
                }
                const table = mapper.toViewElement(item);

                if (attributeNewValue) {
                    writer.setAttribute('class', attributeNewValue, table);
                }
                else {
                    writer.removeAttribute('class', table);
                }
            }, { priority: 'highest' });
        });
 
editor.commands.add('setClass', new SetClassCommand(editor));

constructor(editor) {
    super(editor);
}

refresh() {
    const model = this.editor.model;
    const tableUtils = this.editor.plugins.get('TableUtils');
    const selectedCells = tableUtils.getSelectionAffectedTableCells(model.document.selection);
    const isInTable = selectedCells.length > 0;
    this.isEnabled = isInTable;
    const selection = model.document.selection;
    const table = selection.getFirstPosition().findAncestor('table');
    this.value = this._getValue(table);
}

execute(options = {}) {
    const editor = this.editor;
    const model = this.editor.model;
    const selection = model.document.selection;
    const value = 'custom-class';
    const table = selection.getFirstPosition().findAncestor('table');
    model.change(writer => {
        if (this.value) {
            writer.removeAttribute('class', table);           
        }
        else {
            writer.setAttribute('class', value, table);
        }
    });
}

_getValue(table) {
    if (!table) {
        return;
    }
    const value = table.getAttribute('class');
    if (value === 'custom-class') {
        return true;
    }
    return false;
}`

**Comment by Witoso** [comment]
Hey @matbk49751, sorry for no reply, it somehow slipped my radar. Glad you found a working solution, we will turn it into a how-to for other users.

**Comment by matbk49751** [comment]
Sounds good! Thank you.
