### ISSUE TITLE
Add "ck ck-content" classes to all snippets in the docs

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14995]
Currently, the snippets in the documentation don't have the `"ck ck-content"` classes, so they look different before and after loading the editor, which is not an ideal representation of the What You See Is What You Get (WYSIWYG) editor.

To prevent layout shifting and to display the same content in both scenarios, we should add the `"ck ck-content"` classes to all snippets in the documentation.

**Comment by godai78** [comment]
Actually it seems like there is this class present in the snippets style sheet:

https://github.com/ckeditor/ckeditor5/blob/dd2e92dd25ed169221ccabc287afc01240fa26de/docs/assets/snippet-styles.css#L20

**Comment by pszczesniak** [comment]
It has to be added into `HTML` , for example:

```
<div id="snippet-classic-editor">
```

:point\_down: 

```
<div class="ck ck-content" id="snippet-classic-editor">
```
