### ISSUE TITLE
Character Limit (maxLength)to the specific instance of CKEditor

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5#14996]
Hi Team,
I use Custom CKEditor in my application. I am using multiple instances of this CKEditor. I want to set a character limit to specific instance not for all.  Is there any way to add this maxLength property?

If anyone knows, please let me know.

Thanks in advance

**Comment by Reinmar** [comment]
See https://github.com/ckeditor/ckeditor5/issues/2573#issuecomment-1633694582.

**Comment by Tiru150837** [comment]
Hi Reinmar,

How to use the above package ?..Because I am using CKEditor version 28.0.0

Can you tell me the exact procedure?

Thanks in advance
