### ISSUE TITLE
The SOURCE button changes my contents when I switch between html code and Design.

### ISSUE THREAD

**Issue by Joaquim3** [ckeditor/ckeditor5#15005]
## 📝 The SOURCE button changes my contents when I switch between html code and Design.

1. …I downloaded a build versrion of Ckeditor 5 from : https://ckeditor.com/ckeditor-5/online-builder/
2. …I displayed the page `index.html` on my browser
3. …I clicked on the button `SOURCE` to edit the html code
4. …I typed : 
```
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
BLABLABLA
</body>
</html>
```
5. …I clicked TWICE on the button `SOURCE`
6. …The Editor changed my contents to :
```
<p>
    BLABLABLA
</p>
```

### ✔️ Expected result
```
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
BLABLABLA
</body>
</html>
```

### ❌ Actual result

```
<p>
    BLABLABLA
</p>
```

## 📃 Other details

* Browser: `BRAVE 1.57.64 (latest)`
* OS: `LINUX MINT 21.2 (apt update)`
* First affected CKEditor version:` 5.39.0.2`
* Installed CKEditor plugins: `FullPage, Alignment, BlockQuote, Bold, Essentials, FontBackgroundColor, FontColor, FontSize, GeneralHtmlSupport, HorizontalLine, HtmlComment, HtmlEmbed, Image, ImageInsert, ImageResize, ImageStyle, ImageToolbar, ImageUpload, Indent, Italic, Link, LinkImage, List, ListProperties, Paragraph, PasteFromOffice, SimpleUploadAdapter, SourceEditing, SpecialCharacters, Table, TableCellProperties, TableColumnResize, TableProperties, TableToolbar, Underline`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
By default, the editor will not work for the full-page content, but we have a plugin for this: [Full page HTML](https://ckeditor.com/docs/ckeditor5/latest/features/html/full-page-html.html).

**Comment by Joaquim3** [comment]
Thanks a lot @Witoso.
