### ISSUE TITLE
Docs issue report from "tutorials/crash-course/plugin-configuration.html"

### ISSUE THREAD

**Issue by smartyskon** [ckeditor/ckeditor5#15006]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/tutorials/crash-course/plugin-configuration.html

### Project version

39.0.2

### Is the information outdated? How?

<img width="764" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/127234710/a1d50e12-15e1-4ec6-b9c9-3eb707e74d1f">

I believe this highlighted line in the tutorial should be erased initially. When testing functionality of the default config: `editor.config.define( 'highlight', {
		keystroke: 'Ctrl+Alt+H'
	} );`, having `keystroke: '...'` will cause an error.

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
As far as I understand this is an intro to what you will do in the tutorial, maybe the whole line should be a comment? WDYT @filipsobol?

**Comment by filipsobol** [comment]
The intention was to show an example in the intro section, but I agree that showing a code that causes an error is not a good practice.

I suggested a small improvement to fix this: https://github.com/ckeditor/ckeditor5/pull/15017
