### ISSUE TITLE
Migration guide for images

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#15003]
## Provide a description of the task

Add changes from [images](https://github.com/ckeditor/ckeditor5/pull/14763) to [migration guide](https://github.com/ckeditor/ckeditor5/pull/14981).

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by godai78** [comment]
The groundworks have been done in this commit: https://github.com/ckeditor/ckeditor5/pull/14981/commits/f62ccc68feba3fde88ad040e8f9451969590544c

**Comment by Witoso** [comment]
DUP: #15010
