### ISSUE TITLE
Cannot use up and down arrow key after adding a link

### ISSUE THREAD

**Issue by elliarbtan** [ckeditor/ckeditor5#1501]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
as of 1 february 2019.

## 📋 Steps to reproduce

1. write text
2. select some and use the "link" button or Ctrl-k 
3. try up and down navigation key

## ✅ Expected result

up goes up, down goes down

## ❎ Actual result

up and down keys have no effect

## 📃 Other details that might be useful
firefox 60.4.0esr (64 bits)

**Comment by oleq** [comment]
Confirmed in 65.0. This is pretty serious actually. The arrow keys movement is also locked after moving the selection somewhere else after inserting the link. The URL input preview (?) is also displayed like the focus never left the balloon.

![kapture 2019-02-05 at 10 58 06](https://user-images.githubusercontent.com/1099479/52265711-feb7b000-2934-11e9-8e1b-93d8149155a8.gif)

**Comment by Reinmar** [comment]
Is it a regression?

**Comment by oleq** [comment]
Same in 11.1.1.

**Comment by oskarwrobel** [comment]
Disabling autocomplete for the link input solves the issue but it's a workaround, not a fix.
It could be an FF issue, I'll prepare a sample with input and editable out of CKE5 to check this out.

**Comment by oskarwrobel** [comment]
FF has some problems with blur when focused element is removed from DOM (https://github.com/ckeditor/ckeditor5-link/issues/193).

**Comment by oskarwrobel** [comment]
It's possible to reproduce this issue outside of the CKE5. When focused input is removed from the DOM then focus partially stays in this removed input?! When there is an autocomplete it takes control over the arrow keys. I'm afraid it won't be possible to fix it without some hacks.

**Comment by oskarwrobel** [comment]
See https://jsfiddle.net/pkmozwr5/2/

**Comment by oskarwrobel** [comment]
Reported https://bugzilla.mozilla.org/show_bug.cgi?id=1527628.

**Comment by oskarwrobel** [comment]
It turns out the fix is very simple. All we need to do is blur the input (focus the other element) before removing it.

**Comment by oskarwrobel** [comment]
We should fix it also for the `ImageTextAlternative` balloon.
