### ISSUE TITLE
Update image and migration guides

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#15010]
Add info about automatic height and width to image guide.

**Comment by Witoso** [comment]
I would give a bit more of :heart: to the migration guide. It's a huuuge change, and if I were an integrator, I think I would miss it.

1.  I would prioritize bullet points over long sentences. I'm a bit lost to the narrative. Add some bolds.
2.  I truly miss the HTML here (before/after) the markups changes are important.
    1.  Show even two scenarios (without resize / with resize)
    2.  I would reference maybe: [https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/installation/plugins/features-html-output-overview.html](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/installation/plugins/features-html-output-overview.html)
    3.  explanation why we added `aspect-ratio`, this is an unusual style decision.
3.  Inform the API integrators in more details on the attributes changes.
4.  Better explanation about the content styles changes (and potentially why they were needed).
5.  And I think the most significant piece, add info that current images are not altered.

I think [the comment](https://github.com/ckeditor/ckeditor5/issues/14146#issuecomment-1632607316), could be copied and pasted and slightly tweaked.

We shouldn't be afraid of the length of this page, it's a special one, and we can go into weeds :blush: 

cc @Reinmar as we discussed this.

**Comment by godai78** [comment]
> 5\. And I think the most significant piece, add info that current images are not altered.

OK, so how about adding the attributes to any images that do now sport these on any interaction?

**Comment by godai78** [comment]
> 2\. I truly miss the HTML here (before/after) the markups changes are important.

WOuldn't the Migration guide be the best place for that?

**Comment by Witoso** [comment]
> I would give a bit more of ❤️ to the migration guide

All of the comments are to the migration guide :) sorry for not making it clear.

**Comment by godai78** [comment]
I have just redone the whole part of the image guide, Witek.

Actually I think we'll keep it anyway.

**Comment by godai78** [comment]
> don't close the issue to add a HTML markup as a follow-up.
