### ISSUE TITLE
Image resizing doesn't work properly

### ISSUE THREAD

**Issue by MohamedKarrab** [ckeditor/ckeditor5#15028]
## 📝 Provide detailed reproduction steps (if any)

1. Insert an image using the editor
2. Resize it
3. Load it from the database within an article

### ✔️ Expected result

The image size should be as it looks in the editor
![Screenshot 2023-09-20 000856](https://github.com/ckeditor/ckeditor5/assets/107933631/a0876b58-0a87-4245-b9be-ac384f59e43c)

### ❌ Actual result

Image takes it's full size, sometimes bigger than the browser screen and stretching all along
![Screenshot 2023-09-20 000927](https://github.com/ckeditor/ckeditor5/assets/107933631/1509ac02-9696-47ab-b65d-05ddfc3a9586)

## 📃 Other details

* Browser: Chrome
* OS: Windows 11
* First affected CKEditor version: 5-39.0.2
* Installed CKEditor plugins: a lot

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi, please make sure the side you're publishing to [a page that has included CKEditor content styles as well](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html).

**Comment by MohamedKarrab** [comment]
> Hi, please make sure the side you're publishing to [a page that has included CKEditor content styles as well](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html).

Thanks that solved the problem, maybe it should be clearer that we should consider that
