### ISSUE TITLE
Creation of collapsible section's

### ISSUE THREAD

**Issue by FrauleinGela** [ckeditor/ckeditor5#1504]
## 🆕 Feature request 
Creation of collapsible section's to create content that is visible by clicking on its header ##
## 📃 Other details that might be useful
it would be good if you can add other elements, such as bold, tables, images to that content 
Here, an example on bootstrap: https://getbootstrap.com/docs/4.1/components/collapse/
By the way, you guys have done a good job. thanks.

**Comment by oleq** [comment]
Thanks! We're doing our best 😊

As for the request, I think managing the layout (collapsibles) is beyond the default scope of the  editor. In theory you could develop a [widget](https://ckeditor.com/docs/ckeditor5/latest/api/widget.html) that somehow provides 2 spaces (nested editables) for the buttons and for the content but I think it would be much easier if you handled the accordion layout on the web–page template–side and activate CKEditor 5 on the area that displays the "foldable" content only. 

CKEditor 5 is a content editor not a template editor so using it for template tasks is a challenge. That being said, we're not considering this kind of feature in our roadmap at this moment.

**Comment by Teslafly** [comment]
Now that easyredmine is using ckeditor5, not having this is a huge regression where we used to have the {{collapse}} macro.

It is even accessible in markdown with
```
# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
  collapsed text
</details>
```
