### ISSUE TITLE
Adjacent <span> tags are merged together

### ISSUE THREAD

**Issue by sahal-va** [ckeditor/ckeditor5#15046]
## 📝 Provide detailed reproduction steps (if any)
When we add two adjacent <span> tags using HTML source editing mode (General HTML Support (“GHS”) feature)
ckeditor5 merges those spans together.
For eg, try following code
`<span>
<span>aaaa</span>
<span>bbbb</span>
</span>`

1. Copy above code and paste into editor with source mode.
2. Turn off source editing mode.
3. Turn ON source editing again and see above html changes.

### ✔️ Expected result

It should stay as seperate <span>s

### ❌ Actual result

Got merged into single span

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi, due to technical constraints, we do the merging of those. I'm curious what's the use case in which you need such content.

**Comment by sahal-va** [comment]
Hey,

We were using ckeditor4 in a decoupled Drupal project. Currently we are in the process of migrating ckeditor4 to 5.

It is possible to create frontend html pages using ckeditor in backend admin interface. Client has access to create dynamic html pages as they wish.

This was asked by the client while testing the ckeditor5.

May I know the reasons for such merging? Is there any option to accept the user input as it is without rewriting?

Thanks.

**Comment by Witoso** [comment]
> May I know the reasons for such merging? Is there any option to accept the user input as it is without rewriting?

In CKE5, we operate on an abstract data layer, not HTML directly. If you use [GHS](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html), the inline elements of HTML are added as attributes on the text nodes.

![](https://github.com/ckeditor/ckeditor5/assets/9881379/16f776e9-9d3a-4c3a-b6c4-85f5067d444c)

There's no easy way to represent the surrounding `span` around all text nodes. The engine seeing identical attributes merges them. When we add classes, it interprets it differently:

```html
<span> <span class="1">aaaa</span> <span class="2">bbbb</span> </span>
```

Will result in:

```
<span class="1">aaaa</span><span> </span><span class="2">bbbb</span>
```

The surrounding span will be assigned to the space between the tags. Spans with classes will be preserved. 

I hope this helps.

**Comment by sahal-va** [comment]
Thanks for this.

When I tested with following code.
`<span id="wrapper"> <span class="1">aaaa</span> <span class="2">bbbb</span> </span>`

Results in 3 spans with same id
`<p>
    <span class="1" id="wrapper">aaaa</span><span id="wrapper"> </span><span class="2" id="wrapper">bbbb</span>
</p>`

**Comment by Witoso** [comment]
This is the engine's logic how to handle such scenario. It cannot create a surrounding span, but dropping it would result in a data loss. Therefore, it adds the `id` to all spans.

**Comment by Witoso** [comment]
This is the engine's logic how to handle such scenario. It cannot create a surrounding span, but dropping it would result in a data loss. Therefore, it adds the `id` to all spans.

**Comment by devkinetic** [comment]
This is still an active issue. I see these nested spans used often when placing icons within html. like `<span class="icon-facebook"><span class="visually-hidden">Facebook<span></span>` becomes `<span class="icon-facebook visually-hidden">Facebook</span>`

**Comment by Witoso** [comment]
Let's merge it into https://github.com/ckeditor/ckeditor5/issues/15408.
