### ISSUE TITLE
The nested span element is broken on ckeditor 5

### ISSUE THREAD

**Issue by chalice-x** [ckeditor/ckeditor5#15053]
## 📝 Provide detailed reproduction steps (if any)

When I upgraded from CKEditor 4 to 5, the following code got broken.

`<p><span class="a"><span id="b">yes</span></span></p>`

In fact, I don't want ckeditor to automatically merge <span> tags. Where can I prevent this behavior?

### ✔️ Expected result

`<p><span class="a"><span id="b">yes</span></span></p>`

### ❌ Actual result

`<p><span class="a" id="b">yes</span></p>`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Closing as a duplicate #15046. Please let's move the discussion there. We have a technical blocker in the CKE5 to implement this easily, as CKE5 is not operating on the data model based on HTML.
