### ISSUE TITLE
i am doing custom ui for ckeditor but there i am doing `editor.execute( fontSize, {value:'big'} );` but it's not worknig

### ISSUE THREAD

**Issue by balunaidu** [ckeditor/ckeditor5#1506]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Reinmar** [comment]
What does it mean that it's not working? Does it throw some error?

Also, are you sure you executed this?

```js
editor.execute( 'fontSize', {value:'big'} );
```

Because your ticket says you tried this (which is wrong):

```js
editor.execute( fontSize, {value:'big'} ); // INCORRECT!
```
