### ISSUE TITLE
Upgrade to Node 8

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1507]
LTS support for Node is moving towards the end. See https://github.com/nodejs/Release.

We should upgrade our minimal Node version to `>=8.0.0`.

**Comment by ma2ciek** [comment]
IMO we shouldn't do that before the official date of dropping support.

**Comment by Reinmar** [comment]
I think we'll be fine. 8+ was released in 2017.05 so you've got to have a very old local env to not be compatible with that. We don't have to support the oldest LTS – it's our choice to drop it.

**Comment by pomek** [comment]
What about NPM support? https://github.com/ckeditor/ckeditor5/blob/1fb5f632e82fb53bb7747c65e2166aae6083f39a/package.json#L90-L93

If we will bump the version of Node, we should also consider bumping a version of NPM. Node 8 comes with NPM@5.

**Comment by Reinmar** [comment]
Also +1. None of use npm3 anyway and we don't even know if it works.

**Comment by pomek** [comment]
And one more thing. Should I mark this bump version as BC? I guess so.

**Comment by Reinmar** [comment]
Yes, you can. It's worth mentioning that we dropped support for older versions of Node. However, it isn't about out dev env (which would be internal) but about building CKE5 – I assume in this case the version of Node might make a difference as well.
