### ISSUE TITLE
Drag-and-drop throws errors in GHS demo

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#15087]
## 📝 Provide detailed reproduction steps (if any)

1. Open GHS demo http://localhost:8080/ckeditor5/latest/features/html/general-html-support.html 
2. Drag one of the tiles from responsive column layout out of the columns
3. Try to drag the tile back inside

### ✔️ Expected result

There will be no errors during step 3. It's possible to drag the tile around the responsive column area. The tile will not disappear into nothingness

### ❌ Actual result

Dragging the tile around the responsive columns generates a lot of errors. If the tile is dropped right above the responsive columns (under the "Responsive column layout" text), it disappears.

https://github.com/ckeditor/ckeditor5/assets/66953380/504742bd-cb2c-4847-b39d-5cdc8ca41f0f

Stack trace:
```javascript
Uncaught TypeError: Cannot read properties of undefined (reading '_source')
    at new Bn (rect.ts:108:29)
    at Cw (dragdroptarget.ts:437:15)
    at Aw (dragdroptarget.ts:423:4)
    at yw (dragdroptarget.ts:392:11)
    at vw.updateDropMarker (dragdroptarget.ts:129:23)
    at listenTo.priority (dragdrop.ts:348:19)
    at Object.fire (emittermixin.ts:241:31)
    at _r (bubblingemittermixin.ts:207:10)
    at kr.fire (bubblingemittermixin.ts:118:5)
    at Object.<anonymous> (clipboardobserver.ts:68:18)
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: All
* OS: macOS 14.0
* First affected CKEditor version: current `release` branch
* Installed CKEditor plugins: -

This issue is not present on current production docs

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
We will not block the release with this, but we will follow up right after.

**Comment by niegowski** [comment]
Closed by https://github.com/ckeditor/ckeditor5/pull/15126.
