### ISSUE TITLE
Add image width and height on image paste

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#15088]
## Provide a description of the task

Image width and height should be added when the copied image is pasted into the editor.

Some background:
An image should get `width` and `height` attributes when it is added to the editor or when the user modifies an image.
We've already introduced these changes e.g.:
[Setting image width and height on image upload](https://github.com/ckeditor/ckeditor5/issues/14202)
[Setting image width and height on image change (resize, style, type...)](https://github.com/ckeditor/ckeditor5/issues/14557)

However, these changes did not cover pasting the image into the editor. So, for consistency, we should cover this case as well.

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by niegowski** [comment]
Closed by https://github.com/ckeditor/ckeditor5/pull/15092.
