### ISSUE TITLE
Resizing an image to make it smaller sometimes does the opposite

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#15081]
## 📝 Provide detailed reproduction steps (if any)

1. Add an **inline image**.
2. Grab the resize handler in the lower right corner.
3. Start dragging it towards the upper left corner.

### ✔️ Expected result

I should be able to make the image as small as possible.

### ❌ Actual result

At some point, the image starts getting bigger instead of smaller.

[recording.webm](https://github.com/ckeditor/ckeditor5/assets/4145208/178f824a-fa28-40cf-b8f0-13f74db950f2)

## 📃 Other details

* Browser: Chrome 117 / Firefox 117
* OS: Linux Fedora 38

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
DUP: #10267
