### ISSUE TITLE
[iOS] Drag-and-drop preview is blackened when using the block balloon.

### ISSUE THREAD

**Issue by michalbilik** [ckeditor/ckeditor5#15085]
## 📝 Provide detailed reproduction steps (if any)

1.  Open http://localhost:8080/ckeditor5/latest/examples/builds/balloon-block-editor.html on iOS.
2.  Drag something by the toolbar icon.

### ✔️ Expected result

The preview looks the same as default dragging.

### ❌ Actual result

First drags are done with the toolbar icon ⠿, last one is with selecting and then dragging.  

https://github.com/ckeditor/ckeditor5/assets/50703222/fae04539-aae0-421b-ab1b-3d9acdda7b79

## 📃 Other details

*   Browser: Safari iOS
*   OS: iOS 17.0.2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
Check both themes (light & dark).

**Comment by illia-stv** [comment]
It works well for me as on Safari and as on Chrome,  so I can not reproduce this issue on my phone ( iphone se 2020, iOS version 16.6.1 )
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDcxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87563dc4f21b11f45b98d5e76762f4b1ad75e9ca/image.png)

**Comment by Witoso** [comment]
@illia-stv change the system theme to the dark one.

**Comment by illia-stv** [comment]
> @illia-stv change the system theme to the dark one.

Yeah you right, now I can reproduce it😅

**Comment by arkflpc** [comment]
Closed by #15112.
