### ISSUE TITLE
how to do text-transformation lowercase to uppercase and upper case to lowercase

### ISSUE THREAD

**Issue by balunaidu** [ckeditor/ckeditor5#1508]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.i am doing thirdparty ui using ckeditor. In that  am not able to do initCap lowerCase to uppercase and uppercase toLower case 
2.

**Comment by Mgsy** [comment]
Hi, could you describe exactly what are you trying to achieve?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
