### ISSUE TITLE
Images appearing outside of the demo on image styles docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#15086]
## 📝 Provide a description of requested docs changes

1. Open [image styles demo](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html#demo) on a wide screen
2. Scroll down to the code snippets below the demo

Result:

https://github.com/ckeditor/ckeditor5/assets/34380544/2291ea09-d745-4f9e-9cc0-a65ec98bc0e8

**Comment by godai78** [comment]
Fixed in https://github.com/ckeditor/ckeditor5/commit/59d3630c5a6d52b48939e757c3feaa15750edd8a
