### ISSUE TITLE
Source code view causes <pre><code> to gain leading whitespace if inside <li>

### ISSUE THREAD

**Issue by wimleers** [ckeditor/ckeditor5#15084]
## 📝 Provide detailed reproduction steps (if any)

1. Create `<li><pre><code>` markup, for example:
```
<h2>
    Good:
</h2>
<pre><code class="language-plaintext"># From any path:
something --flag</code></pre>
<h2>
    <strong>Bad:</strong>
</h2>
<ol>
    <li>
        <p>
            preformatted code block in list gains leading whitespace 😬
        </p>
        <pre><code class="language-plaintext"># From any path:
something --flag</code></pre>
    </li>
</ol>
```
2. Enable source view
3. Change *anything at all*, e.g. change "Good:" to "Good!"
4. Disable source view

### ✔️ Expected result

The only change is the one you made.

### ❌ Actual result

The `something --flag` has been indented with additional spaces:
![li pre code](https://github.com/ckeditor/ckeditor5/assets/14240/69fdf1dc-0045-4df7-ad8d-54ae9d484d42)

## 📃 Other details

* Browser: Chrome
* OS: macOS
* First affected CKEditor version: Unknown.
* Installed CKEditor plugins: Reproduced at https://ckeditor.com/ckeditor-5/demo/html-support/

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by wimleers** [comment]
Note that the only possible work-around is to _disable JavaScript_ to prevent CKEditor 5 from loading, and instead do markup tweaks in the `<textarea>` directly 🙈

**Comment by Witoso** [comment]
I guess [`formatHtml`](https://ckeditor.com/docs/ckeditor5/latest/api/module_source-editing_utils_formathtml.html) is the root cause here. Most likely, (?) we should take unformatted HTML as a data to not have white spaces to appear in the code blocks.

**Comment by Reinmar** [comment]
Between `<pre>` and `</pre>` we should indeed use the very raw data of that data and not use indentation of anything that preceded those elements.

**Comment by niegowski** [comment]
DUP: https://github.com/ckeditor/ckeditor5/issues/10945

**Comment by wimleers** [comment]
I searched, but didn’t find that one!
