### ISSUE TITLE
Fix multiple files insertion via CKBox

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15094]
When we select in CKBox files, and add them, they become joined together:
![image](https://github.com/ckeditor/ckeditor5/assets/9881379/b90b4719-11d3-4393-a1ea-5d4b33c9e6ba)

### Scope
Add each file in a separate paragraph, this way it may be easier to create a list.

**Comment by arkflpc** [comment]
Inserting links when selection is not collapsed is out of scope.
