### ISSUE TITLE
Inserted image from the CKBox has a brief empty widget

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15090]
Inserted image from the CKBox has a brief empty widget. The time depends on the size of the image (and networks speed).

![image](https://github.com/ckeditor/ckeditor5/assets/9881379/d4b02b74-7f42-4d7c-a36a-5db2b19e4423)

### Scope
* Create a preview of an image before it's loaded into the editor.

### Solution
We could try to use  [[blurhash](https://github.com/woltapp/blurhash/tree/master/TypeScript#api)](https://github.com/woltapp/blurhash/tree/master/TypeScript#api), as it's already used in the CKBox. And we have an access to it:
![image](https://github.com/ckeditor/ckeditor5/assets/9881379/845a6ecd-0546-4ecf-b825-3f9e297b24be)

**Comment by arkflpc** [comment]
Possible solution: use output from blurHash as image background.

- [ ] [ckeditor5-image] Add `placeholder` option to `InsertImageCommand`.
- [ ] [ckeditor5-ckbox] Create data url from image metadata (`blurHash` + `width` + `height`) and pass to `"insertImage"` command.
