### ISSUE TITLE
Switch the CKBox theme to the lark one

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15096]
CKBox introduced a dedicated theme to the CKEditor 5. 

### Scope

*   Use \`lark\` as a default theme in the CKBox integration.
*   It should be possible for the integrator to switch it back.
*   (Sidenote: This should switch it automatically in our docs in the CKBox usages)

```
ckbox: {
        tokenUrl: '<https://your.token.url>',
        theme: 'lark'
},
```

**Comment by arkflpc** [comment]
It boils down to adding default config
