### ISSUE TITLE
Focus goes nowhere after inserting something from the CKBox.

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15091]
Focus goes nowhere after inserting something from the CKBox.

https://github.com/ckeditor/ckeditor5/assets/9881379/7b9d5316-1562-4857-988b-1a64308e7a7a

### Scope
- After choosing an image, focus the editor.
    - Place the selection on the image (as now when pasting)
- After selecting multiple images, focus the editor.
    - Place the selection on the last image (as now when pasting).
- After selecting file/files, focus the editor (selection will move after them anyway).

**Comment by arkflpc** [comment]
Probably `editor.editing.view.focus()` somewhere here: https://github.com/ckeditor/ckeditor5/blob/57f2a6833f334c49b9c52e56b0c9f46ec0bfd67e/packages/ckeditor5-ckbox/src/ckboxcommand.ts#L227
