### ISSUE TITLE
How to create a Span with several attributes in the plugin?

### ISSUE THREAD

**Issue by asemandeveloper** [ckeditor/ckeditor5#15098]
Hello to all
I am a beginner in ckeditor5
Please guide me how to add a span tag with multiple attributes in the plugin.
I have problems in downcast and upcast and I cannot write them with the help of CKEditor5 guide.
The span tag is as below.

`<span class="books" data-id="0001" data-publisher="Oxford" data-city="Londan">Artificial intelligence</span>`

**Comment by Witoso** [comment]
Hey, let's use one issue for this case: [#15103](https://github.com/ckeditor/ckeditor5/issues/15103). Please don't create duplicates. Thanks! 🙌
