### ISSUE TITLE
Update metadata for TodoDocumentList

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#15107]
### Tasks
- [x] Update metadata. See [docs](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/package-metadata.html)
- [x] Verify whether TodoDocumentList will work correctly in the Online builder (appear on the list and will be installable).

**Comment by niegowski** [comment]
Closed by https://github.com/ckeditor/ckeditor5/pull/15114.
