### ISSUE TITLE
Ensure there is `main` field in the `package.json` for each released package

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#15127]
## 📝 Provide a description of the improvement

Currently, release tools do not check if the `package.json` contains the `main` field. Publishing such a package will succeed, but the package may not be usable. So, it would be nice to ensure that the `main` field is present when it is needed.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
### Scope

* Let's add a new validator in https://github.com/ckeditor/ckeditor5-dev/blob/43eabd25001505b8c83574b1842284897840658a/packages/ckeditor5-dev-release-tools/lib/tasks/publishpackages.js#L65-L67.
	* By default, it is disabled. It requires switching a flag to enable it.
* Fix CKEditor 5 release tools by passing the new flag set to `true`.

**Comment by pomek** [comment]
PRs:

* https://github.com/ckeditor/ckeditor5-dev/pull/926
* https://github.com/ckeditor/ckeditor5/pull/15191
* https://github.com/cksource/ckeditor5-commercial/pull/5630
