### ISSUE TITLE
Create an example of generating nested div tags with classes

### ISSUE THREAD

**Issue by vadimud** [ckeditor/ckeditor5#1512]
Please create an example of generating nested div tags with classes

[CKEditor 5, plugin example]

I try create a plugin for implementation collapsible widget (or just collapsible block). 
I based on blockquote plugin [https://github.com/ckeditor/ckeditor5-block-quote/tree/master/src](url)
At first step I try just overwrite DOM nodes generator. I need create something like:

` <div class="collapsible">`
`   <div class="header">Custom editable header of block</div>`
`     <div class="content" style="display: none;">`
`        Custom editable and collapsible content.`
`   </div>`
`</div>`

Multiple attempts failed.

For example, I do not found way for custom class name implementation for nested div tags. 
I guess, generator method call located on method with name
_applyQuote( writer, blocks )
on file blockquotecommand.js

conversion located on blockquoteediting.js

I need just a small worked example for creating above DOM nodes on editor.
Thanks.

**Comment by scofalik** [comment]
Hi,

I think that you are trying to solve your problem in an incorrect way. You don't need generic nested divs. You need a widget and a proper definition of the data in the model.

To be honest, you'd be better by checking how image and image caption are implemented as it seems that your case is very similar: you have a fixed widget structure with two editable areas (it is only one in case of image caption).

Your plugin stores two data values: title and content. I'd suggest this model structure:

```html
<collapsible>
    <collapsibleHeader>Header data.</collapsibleHeader>
    <collapsibleContent isCollapsed="true/false">Content data.</collapsibleContent>
</collapsible>
```

You will need to define a proper schema for those elements (`collapsible` inheriting all from `$block`, allowing its children, `collapsibleHeader` and `collapsibleContent` allowing `$text`, `collapsibleContent` allowing `isCollapsed` attribute).

Conversion of such element shouldn't be that difficult but you will have to provide your own converter.

For downcast, you can downcast every element separately. For `collapsible` you will need own converter so you can use `toWidget()`. You will also need to provide a different conversion for `editingDowncast` and `dataDowncast` pipelines. `isCollapsed` attribute should be converted using attribute conversion, of course.

For upcast, you might be good with the regular converters available in `Conversion` class. However, I'd change `header` and `content` classes to something like `collapsible-header` and `collapsible-content` so there won't be any conflict with any other element with `header` or `content` class names. Same for hiding/showing, introduce something like `collapsible-collapsed` class.

Link to docs:
* [Schema](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html),
* [Conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) (you will have to use converters with `for()`)

As I earlier said, investigate what is going on in the image plugin, as your case is similar.

**Comment by scofalik** [comment]
A link to a tutorial covering implementing a similar widget: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html

**Comment by vadimud** [comment]
Thank you. After long and deep research I implemented something similar, month ago. I will try to publish my code next month, after 'brushing'. You current instruction is very clear and, I guess, will help other developers too.
