### ISSUE TITLE
How to create unwrappable element?

### ISSUE THREAD

**Issue by devraj112** [ckeditor/ckeditor5#15128]
Expected result:
`<primary data-selected="selected data" data-type="value"></primary>`

Result I am getting: 
`<primary data-info="selected data" data-type="value">selected data</primary>`

The schema and conversion: 

```
`_schemaDefinition(){
        const schema = this.editor.model.schema

        schema.extend('$text', {
            allowAttributes: ['info']
        })
    }

    _conversionDefinition(){
        const conversion = this.editor.conversion;

        conversion.attributeToAttribute({
            model: 'info',
            view: 'data-info'
        })
        

        conversion.for('upcast').elementToAttribute({
            view: {
                name: 'primary',
                attributes: ['data-info']
            },
            model: {
                key: 'info',
                value: (viewElement, conversionApi)=>{
                    const value = viewElement.getAttribute('info')
                    return value;
                }
            }
        })
        conversion.for('downcast').attributeToElement({
            model: {
                key: 'info'
            },
            view: (value, {writer})=>{
                const attributeEl = {}
                attributeEl['data-info'] = value

                return writer.createAttributeElement('primary', attributeEl)
            },
            converterPriority: 'high'
        })` 
```
But in this case, the selected data is getting passed as the child node of the plugin. I tried using `createEmptyElement()` also. But, I got this error 
`ckeditorerror.js:86 Uncaught CKEditorError: view-writer-wrap-invalid-attribute`

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser: Chrome updated version
* OS: Windows 10 Pro
* CKEditor version: 5
* Installed CKEditor plugins: …

**Comment by Witoso** [comment]
Did you implement all [Styles](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/ui/document-editor.html#styles)?

**Comment by devraj112** [comment]
> Did you implement all [Styles](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/ui/document-editor.html#styles)?

Styles for what? 
By the way, my problem is solved and I have successfully created the empty element. 
Thanks.

**Comment by Witoso** [comment]
What I meant is that you didn't show `styles.css`, and I was unsure if you implemented them. Glad you found the solution.
