### ISSUE TITLE
Docs issue report from "features/converters/import-word/import-word.html"

### ISSUE THREAD

**Issue by anu9901998** [ckeditor/ckeditor5#15125]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/converters/import-word/import-word.html

### Project version

39.0.2

### Is the information outdated? How?

when import second word file its content get appended to the existing one, It is not replacing the first one

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
This is a version we decided upon as some user may want to import a few files into one editable. If you think some other option is better, feel free to open an improvement ticket in our repo. Thanks!
