### ISSUE TITLE
Document editor - destroy 

### ISSUE THREAD

**Issue by tejashapani** [ckeditor/ckeditor5#1513]
Hello,

This is not for a bug or any feature request.
I would like to know if it is possible to toggle the Document editor.

## 💻 Version of CKEditor 5

I am trying to use CKEditor 5, in one of my application.
And i want an option to toggle the Editor.
So is it possible to destroy the Document editor?
I got it working with Classic editor but not with Document editor.

Is there any way to achieve this option?

```js
var edi = DecoupledEditor
                    .create(document.querySelector('#editor'), {
                        // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
                    })
                    .then(editor => {
                        const toolbarContainer = document.querySelector('main .toolbar-container');
                        toolbarContainer.prepend(editor.ui.view.toolbar.element);
                        window.editor = editor;
                        edi.distroy();
                    })
                    .catch(err => {
                        console.error(err.stack);
                    });
```

**Comment by jodator** [comment]
At first I thought that it was a bug but it looks like intentional behavior and you must [remove toolbar and editable when destroying decoupled editor](http://localhost:63342/ckeditor5/build/docs/ckeditor5/11.2.0/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html#function-destroy):

```js
editor.destroy()
    .then( () => {
        // Remove the toolbar from DOM.
        editor.ui.view.toolbar.element.remove();

        // Remove the editable from DOM.
        editor.ui.view.editable.element.remove();

        console.log( 'Editor was destroyed' );
    } );
```
