### ISSUE TITLE
[Docs] Write a guide solving common conversion problems reported by the users

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1514]
This is an extension of https://github.com/ckeditor/ckeditor5-link/issues/202. In fact, it includes that and more general cases.

Related
* https://github.com/ckeditor/ckeditor5/issues/760
* https://stackoverflow.com/questions/51303892/how-to-add-target-attribute-to-a-tag-in-ckeditor5/51365516#51365516
* https://github.com/ckeditor/ckeditor5/issues/1462
* https://stackoverflow.com/questions/49366292/ckeditor-5-links-set-default-target-for-links-or-edit-target

**Comment by oleq** [comment]
Requires https://github.com/ckeditor/ckeditor5/issues/1520.

**Comment by oleq** [comment]
Another idea to include in the guide https://github.com/ckeditor/ckeditor5/issues/1606.

**Comment by Reinmar** [comment]
One more idea: table classes.

**Comment by Reinmar** [comment]
☝️@jodator, would you like to add it to the PR?

**Comment by Reinmar** [comment]
Also, there's a question whether classes should be on `<figure>` or `<table>`. It'd be great if the guide would actually show both so people could see what happens.

**Comment by jodator** [comment]
I could try with this one. Sure.

**Comment by oleq** [comment]
[Another case](https://github.com/ckeditor/ckeditor5/issues/1673): `<a rel="...">` (twin to target).
