### ISSUE TITLE
Forked CKEditor 5 build and used in SPfx project has grayed out toolbar buttons.

### ISSUE THREAD

**Issue by DigitalSa1nt** [ckeditor/ckeditor5#1515]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

Forked from classic, with following items:

- '@ckeditor/ckeditor5-editor-classic/src/classiceditor'
- '@ckeditor/ckeditor5-essentials/src/essentials'
- '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter'
- '@ckeditor/ckeditor5-autoformat/src/autoformat'
- '@ckeditor/ckeditor5-basic-styles/src/bold'
- '@ckeditor/ckeditor5-basic-styles/src/italic'
- '@ckeditor/ckeditor5-block-quote/src/blockquote'
- '@ckeditor/ckeditor5-ckfinder/src/ckfinder'
- '@ckeditor/ckeditor5-easy-image/src/easyimage'
- '@ckeditor/ckeditor5-heading/src/heading'
- '@ckeditor/ckeditor5-image/src/image'
- @ckeditor/ckeditor5-image/src/imagecaption'
- @ckeditor/ckeditor5-image/src/imagestyle'
- @ckeditor/ckeditor5-image/src/imagetoolbar'
- '@ckeditor/ckeditor5-image/src/imageupload'
- '@ckeditor/ckeditor5-link/src/link'
- '@ckeditor/ckeditor5-list/src/list'
- '@ckeditor/ckeditor5-media-embed/src/mediaembed'
- '@ckeditor/ckeditor5-paragraph/src/paragraph'
- '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice'
- '@ckeditor/ckeditor5-table/src/table'
- '@ckeditor/ckeditor5-table/src/tabletoolbar'

## 📋 Steps to reproduce

1. Fork the classic repo.
2. start: npm run build.
3. place translations, ckeditor.js and ckeditor.js.map in SPfx project
4. reference cheditor.js
5. replace a div with the editor using:

```
ClassicEditor.create(document.querySelector('#editor'), {
    })
      .then(editor => {
        console.log(editor);
      })
      .catch(error => {
        console.error(error);
      });
```
6. editor loads up

## ✅ Expected result

All toolbar buttons are use-able.

## ❎ Actual result

ALL toolbar buttons are greyed out

## 📃 Other details that might be useful

I'm likely being dense and have missed something, but this should happily run performing the above steps right. I've looked into if it's running in readonly mode, and I've checked the build using the built index.html page and it runs fine there, just not when placed inside of a SPfx project, so I'm assuming I've missed some crucial part of the set up, any advice is appreciated. 

Please close if this is not the right place for this. Thank you.

**Comment by DigitalSa1nt** [comment]
Looking at the debugger, we get the following error:

```
TypeError: Cannot read property 'length' of undefined
    at Object.get [as anchor] (ckeditor.js:6651)
    at na.get [as anchor] (ckeditor.js:7014)
    at ea.get [as anchor] (ckeditor.js:6886)
    at ckeditor.js:11418
    at Jl.refresh (ckeditor.js:11425)
    at Ac.<anonymous> (ckeditor.js:11305)
    at Ac.fire (ckeditor.js:1276)
    at Fc.<anonymous> (ckeditor.js:9591)
    at Fc.fire (ckeditor.js:1276)
    at Fc._runPendingChanges (ckeditor.js:10187)
```

**Comment by Reinmar** [comment]
Hi! We miss a couple of things to be able to reproduce it. Ideally, if you could share `package.json`, `webpack.config.js`, `ckeditor.js`, and the `index.html` file that'd be great.

Also, you write:

> ALL toolbar buttons are greyed out

And:

> I've looked into if it's running in readonly mode, and I've checked the build using the built index.html page and it runs fine there, just not when placed inside of a SPfx project

So, I'm a bit lost whether this issue happens on a plain simple index.html or in SPfx project.

**Comment by DigitalSa1nt** [comment]
> Hi! We miss a couple of things to be able to reproduce it. Ideally, if you could share `package.json`, `webpack.config.js`, `ckeditor.js`, and the `index.html` file that'd be great.
> 
> Also, you write:
> 
> > ALL toolbar buttons are greyed out
> 
> And:
> 
> > I've looked into if it's running in readonly mode, and I've checked the build using the built index.html page and it runs fine there, just not when placed inside of a SPfx project
> 
> So, I'm a bit lost whether this issue happens on a plain simple index.html or in SPfx project.

It seems to happen specifically in the SPfx project, it works in the Index.html. But it should in theory still work in a SPfx project as far as I can see. Anyway here are the requested files.

[ckeditor.txt](https://github.com/ckeditor/ckeditor5/files/2851190/ckeditor.txt)
[webpack.config.txt](https://github.com/ckeditor/ckeditor5/files/2851191/webpack.config.txt)
[index.txt](https://github.com/ckeditor/ckeditor5/files/2851195/index.txt)

I've changed their file extensions from .html/.js to .txt so that I can attach them.

I'm just trying to figure out, what is potentially missing in the SPfx template that I might need to try and implement etc.

**Comment by Reinmar** [comment]
OK, so you've got a basic build of CKEditor 5. I see nothing in it that looks suspicious. Unfortunately, there's a big chance that there's something in SPfx's environment which breaks the editor. It's impossible to guess what it is – could be the data that you load, some weird changes in the DOM, etc.

**Comment by DigitalSa1nt** [comment]
> OK, so you've got a basic build of CKEditor 5. I see nothing in it that looks suspicious. Unfortunately, there's a big chance that there's something in SPfx's environment which breaks the editor. It's impossible to guess what it is – could be the data that you load, some weird changes in the DOM, etc.

After continuing to tinker around with it, I'm inclined to agree that it would be nearly impossible for me to determine what's causing those particular issues. But thank you for having a quick look either way.

**Comment by Reinmar** [comment]
Out of curiosity – on which browser does it happen? Have you tested other browsrers?

Also, can you post an unminified stack trace? There's a source map generated for the `ckeditor.js` file so you should actually see in your browser a stack trace from with references to the source code. Since you posted a minified stack trace, I'd guess you're not using Chrome?

**Comment by DigitalSa1nt** [comment]
> Out of curiosity – on which browser does it happen? Have you tested other browsrers?
> 
> Also, can you post an unminified stack trace? There's a source map generated for the `ckeditor.js` file so you should actually see in your browser a stack trace from with references to the source code. Since you posted a minified stack trace, I'd guess you're not using Chrome?

Apologies for the delayed response, we tested this in all three browsers, the debugging console shows similar undefined errors.

The stack trace above was actually from Chrome. I guess it's possible however that the SPfx project and SharePoint handles error throwing differently? I could potentially look to see if I can get a more verbose stack trace that might highlight something useful.

**Comment by Reinmar** [comment]
Thanks for the info. It's possible to handle errors differently, but I think the case here is different – SharePoint's server may not be serving source maps. 

Since you created your own build, you can actually choose to not minify it. It's enough to run webpack in development mode:

```js
./node_modules/.bin/webpack --mode development
```

You can execute this command assuming that you're inside a build repo (or a similar setup).

Try using such a build of CKEditor in SPfx and the stacktrace should be better.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
