### ISSUE TITLE
Insert image as block by default

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15158]
To summarize the current behavior:

*   When I'm in an empty paragraph, the image is inserted as a block one.
*   When I'm at the beginning/middle/end, the image is inserted as an inline one.

### Rational for the change

The current behavior is confusing, and can hide from the user that the image is, in fact, inline.

![image](https://github.com/ckeditor/ckeditor5/assets/9881379/eaf56efc-dbc6-445e-9da7-ec2be115ccfc)

**Comment by Witoso** [comment]
On our design guild meeting, we decided that the block behavior is much more intuitive, and leads to fewer surprises.

Scope:

*   Change [the default behavior](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageinsert-ImageInsertConfig.html#member-type) to block.
*   Name the `undefined` option to something like `auto`
*   Create a documentation on inserting images and default option.

This is a breaking change.

**Comment by godai78** [comment]
Follow-up: update [image guide](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-installation.html#inline-and-block-images).

**Comment by arkflpc** [comment]
If the config is `'block'` and the `ImageBlockEditing` plugin is not enabled, the determined type would be inline and there will be a console warning. I would skip this warning in case the config is `undefined` and only keep it when it is explicitly given as `'block'`.
@Witoso, what do you think?

**Comment by Witoso** [comment]
> in case the config is `undefined`

New 'auto', right?

> only keep it when it is explicitly

Shouldn't it be the same case for 'inline' when `ImageInlineEditing`?
