### ISSUE TITLE
Docs issue report from "api/module_cloud-services_cloudservicesconfig-TokenUrl.html"

### ISSUE THREAD

**Issue by gurbandev** [ckeditor/ckeditor5#15155]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_cloud-services_cloudservicesconfig-TokenUrl.html

### Project version

40.0.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Please open issues with a more detailed description.
