### ISSUE TITLE
toolbar's popup is hidden

### ISSUE THREAD

**Issue by zhi437404** [ckeditor/ckeditor5#15152]
## 📝 Provide detailed reproduction steps (if any)

1. When the container is **overflow: hidden** or **overflow: auto**, the toolbar's popup will be hidden
<img width="557" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/121606387/8674e91c-86e6-4944-8f91-94985a6e64f4">

### ✔️ Expected result

1. Toolbar's popup display correctly

### ❌ Actual result

1. Toolbar's popup is hidden

### ❓ Possible solution

1. Maybe the toolbar's popup should be renderred in body?

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Which version of the editor are you using?

**Comment by zhi437404** [comment]
@Witoso Thanks Reply，my editor version is 40.0.0
The officail demo can reproduce this case also (I set **overflow:hidden**) to the **class=live-snippet** element, part of toolbar's popup will be hidden:
<img width="1231" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/121606387/9e676c07-9833-461d-a0d7-0cc07fbaaedd">

**Comment by Witoso** [comment]
Thanks for the reply, there's an issue for this already: #9499. Please +1 it to bump its priority.
