### ISSUE TITLE
Docs issue report from "features/source-editing.html"

### ISSUE THREAD

**Issue by nqt1998tez** [ckeditor/ckeditor5#15162]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html#demo

### Project version

40.0.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Please provide additional information in the future issues. We cannot do much without details.
