### ISSUE TITLE
Typescript and ckeditor5

### ISSUE THREAD

**Issue by DMITRYTISHKIN** [ckeditor/ckeditor5#1516]
How can I use [@types/ckeditor__ckeditor5-core](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ckeditor__ckeditor5-core) for ckeditor5-core? 
When I do import:
`import { Plugin } from '@ckeditor/ckeditor5-core';`
webpack show following error:
`Module not found: Error: Can't resolve '@ckeditor/ckeditor5-core'`

**Comment by Reinmar** [comment]
The proper import would look like this:

```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
```

CKEditor 5 is published on npm in a source version, so all modules are kept separately.

Usually, you can check the import path in the API docs (e.g. https://ckeditor.com/docs/ckeditor5/latest/api/module_core_plugin-Plugin.html):

![image](https://user-images.githubusercontent.com/156149/52552412-6dd34f80-2de0-11e9-968c-ad347b1c0200.png)
