### ISSUE TITLE
Table properties balloon not showed in latest release 40.0.0 for Vite

### ISSUE THREAD

**Issue by tonprince** [ckeditor/ckeditor5#15172]
I am using ClassicEditor with Vite setup with TableProperties and TableCellProperties plugins. In release 39.0.2 everything worked fine and the table properties balloon has been showed, but with the latest version 40.0.0 no balloon is displayed.

I am using the Vite integration.

### ✔️ Expected result
Show table and table cell properties balloon.

### ❌ Actual result
No table balloons are showed.

* Browser: Firefox 118.0.2
* OS: iMac Pro macOS Sonoma
* Installed CKEditor plugins: @ckeditor/ckeditor5-table": "^40.0.0", @ckeditor/vite-plugin-ckeditor5": "^0.1.3"

**Comment by Witoso** [comment]
I cannot this reproduce [in our demos](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) on Firefox 118.0.2.

![](https://github.com/ckeditor/ckeditor5/assets/9881379/57ddb7a7-d019-4d75-9778-fe89a9a76fc9)

Could you share more info about your setup, or provide some reproducible sample? Is there some error in the console?

**Comment by tonprince** [comment]
I create a repo for reproduction:

https://github.com/tonprince/ckeditor-table-vite

Run: `npm i && npm run dev`

**Comment by tonprince** [comment]
When checking the inspector, it seems the balloon rotator content element is missing from the dom.

![image](https://github.com/ckeditor/ckeditor5/assets/6906225/e55a6a2e-8609-4f62-9314-bb604a0d5036)

Here is how it should be:
![image](https://github.com/ckeditor/ckeditor5/assets/6906225/a2dcb3d2-f1b9-4344-ac56-3ba2a23035a5)

**Comment by tonprince** [comment]
Looks like the position attribites top, left are not set properly:
If I overwrite those settings, they are displayed:

:global(.ck.ck-balloon-panel) {
    top: 100px !important;
    left: 100px !important;
  }
  
  
 
![image](https://github.com/ckeditor/ckeditor5/assets/6906225/c68d3e6a-0d9c-42a5-9d08-e58098087b2e)

**Comment by tonprince** [comment]
The issue was the overwrite of the viewport from the placeholder plugin.

**Comment by Witoso** [comment]
Thanks for checking, is this an override that you introduced, or was it somewhere in the docs?

**Comment by tonprince** [comment]
It was somewhere in the docs.

Am Fr., 13. Okt. 2023 um 15:26 Uhr schrieb Witek Socha <
***@***.***>:
