### ISSUE TITLE
Allow <tbody> <th> in any column

### ISSUE THREAD

**Issue by jameswilson** [ckeditor/ckeditor5#15171]
## Summary

When I paste in CKE5 Source mode the following table, and switch out of source mode and then back into source mode, the `<th>` is converted to a `<td>`.

```html
<table>
    <tbody>
        <tr>
            <td><a href="#">edit</a></td>
            <th scope="row">I AM THE IMPORTANT CELL</th>
            <td>things</td>
            <td>more things</td>
        </tr>
    </tbody>
</table>
```

## Context

It appears that currently a `<th>` must START the rows, and you cannot have a `<td>` followed by a `<th>`.

However, this is NOT a requirement of the HTML5 spec. In fact, the [example in the specification](https://www.w3.org/TR/2014/REC-html5-20141028/tabular-data.html#the-th-element) uses a `<th>` after a `<td>`.

```html
  <tr> <td> <th scope=rowgroup> Cats <td> <td>
```

## 📝 Detailed reproduction steps

This bug can be confirmed without the Source mode button by using the Table widget balloon toolbar operations in the Classic Editor example.

1. Open the [Classic Editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) and clear out all contents.
1. Use the toolbar to insert a table with 4 rows and 2 columns.
2. Enter data in all cells.
3. Select the second column, then select the "Column" icon from the Table widget balloon toolbar. Then enable the Header column toggle.

### ✔️ Expected result

Only the selected 2nd column becomes a header column (visually indicated by bold text and a light gray cell background color).

### ❌ Actual result

Both the 1st and 2nd column become header columns.

## Video recording

https://github.com/ckeditor/ckeditor5/assets/243532/2ca120e6-4ea6-4c46-b1ee-e44360f4de27

## 📃 Other details

* Browser: Google Chrome Latest
* OS: macOS Monterrey 12.6.6
* First affected CKEditor version: unknown.
* Installed CKEditor plugins: Table widget.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jameswilson** [comment]
This issue was first detected on Drupal 10 and related in a [Drupal community slack thread here](https://drupal.slack.com/archives/C01GWN3QYJD/p1697059098286609).

**Comment by Witoso** [comment]
Thanks, I think it's a dup of #15022. I tweaked its title to be more findable.

**Comment by jameswilson** [comment]
Thanks @Witoso. Apologies for the dupe. My search fu was weak or I just plain missed that one.

**Comment by jameswilson** [comment]
Anyone who thumbed this up please go thumb up #15022 Thanks!
