### ISSUE TITLE
Editor placeholder should be created from "placeholder" attribute only when source element is <textarea>

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1517]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

master

![image](https://user-images.githubusercontent.com/1099479/52554531-6d8a8280-2de7-11e9-8422-70407a73731d.png)

The `placeholder` attribute is invalid in this case. We must make sure we use a valid HTML.

**Comment by Reinmar** [comment]
I've got second thoughts. If it's named `data-placeholder` it's not going to work with textarea's `placeholder`. Do we need support for this attribute at all? Can't we handle this via the config only? And then, only for textareas, from an attribute.

**Comment by Reinmar** [comment]
:trollface: 

https://github.com/ckeditor/ckeditor5/issues/479

> and even reading the `placeholder` from the editor element if the editor was initialised on a textarea.

**Comment by oleq** [comment]
![image](https://user-images.githubusercontent.com/1099479/52556530-1e475080-2ded-11e9-8507-63e00597b30a.png)
