### ISSUE TITLE
Docs issue report from "installation/integrations/vuejs-v3.html"

### ISSUE THREAD

**Issue by DedicatedManagers** [ckeditor/ckeditor5#15183]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/vuejs-v3.html#quick-start

### Project version

40.0.0

### Is the information outdated? How?

I'm trying to follow the [Integrating a build from the online builder](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/vuejs-v3.html#integrating-a-build-from-the-online-builder)

When I run my app (I am using Javascript not TS) I get an error:
`SyntaxError: The requested module '/ckeditor5/build/ckeditor.js?t=1697411269402' does not provide an export named 'default'`

 The import statement in the doc link above is:
`import Editor from 'ckeditor5-custom-build/build/ckeditor';`

If you look at that file (ckeditor5-custom-build/build/ckeditor.js), it start with:
`(function(t){const e=t["en"]=t["en"]||{};e.dictionary=Object.assign(e.`
Which does not look like a javascript module file that has an `export`

Is this documentation possibly missing something?

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by filipsobol** [comment]
Hey @DedicatedManagers,

Could you give a little more detail about your setup, please?

I created the following setup with a custom build and it worked fine for me:

```bash
npm create vue@latest
cd <DIR_NAME>
yarn
yarn add file:./ckeditor5
yarn add @ckeditor/ckeditor5-vue
```

**src/main.js**
```js
// Import plugin
import CKEditor from '@ckeditor/ckeditor5-vue';

createApp(App)
  .use(CKEditor)  // Register plugin
  .mount('#app');
```

**src/App.vue**
```vue
<template>
  <div id="app">
    <ckeditor :editor=" editor " v-model=" editorData " :config=" editorConfig "></ckeditor>
  </div>
</template>

<script>
import Editor from 'ckeditor5-custom-build/build/ckeditor';

export default {
  name: 'app',
  data () {
    return {
      editor: Editor,
      editorData: '<p>Content of the editor.</p>',
      editorConfig: {
        // The configuration of the editor.
      }
    };
  }
}
</script>
```

**Comment by DedicatedManagers** [comment]
Thanks for the quick reply... I work on this project on weekends, so I'll reply with more then.

For now, maybe this info will be helpful:
I created the project using[ Vuetify's setup](https://vuetifyjs.com/en/getting-started/installation/#installation) using NPM (not yarn - maybe the issue is `npm add file` works differently from `yarn add file`?).

**Comment by DedicatedManagers** [comment]
@filipsobol - I was able to get the editor to work using your steps above.  However, if I repeat the process using "npm" instead of "yarn", I get the error I was having.  My project uses npm, not yarn.  So how can I get this to work using npm?

npm create vue@latest
cd <DIR_NAME>
npm install
npm add file:./ckeditor5
npm add @ckeditor/ckeditor5-vue

**Comment by DedicatedManagers** [comment]
@filipsobol - interestingly running `yarn add @ckeditor/ckeditor5-vue` at the end solves the issue.  

npm create vue@latest
cd <DIR_NAME>
npm install
npm add file:./ckeditor5
npm add @ckeditor/ckeditor5-vue
yarn add @ckeditor/ckeditor5-vue

So apparently something is different about installing `@ckeditor/ckeditor5-vue` with npm vs yarn
