### ISSUE TITLE
markdown demo => ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by chrislosinger** [ckeditor/ckeditor5#15181]
1. follow install and build steps from https://github.com/ckeditor/ckeditor5-demos/tree/master/markdown#installation-steps. No errors reported.
2. yarn start. No errors reported.
3. Chrome shows unformatted markdown sample text, no editor (ditto on Firefox)
4. browser console shows:

Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    CKEditorError ckeditorerror.js:57
    node_modules main.js:152448
    Webpack 12
[ckeditorerror.js:57](webpack://markdown/node_modules/@webspellchecker/wproofreader-ckeditor5/node_modules/@ckeditor/ckeditor5-utils/src/ckeditorerror.js)
    CKEditorError ckeditorerror.js:57
    js version.js:149
    Webpack 12

**Comment by chrislosinger** [comment]
Command line history:

chlosi@d78022 MINGW64 /c/dev/src/editors/ckeditor5-demos/markdown (master)
$ yarn
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning @ckeditor/ckeditor5-dev-utils > terser-webpack-plugin > cacache > @npmcli/move-file@1.1.2: This functionality ha
s been moved to @npmcli/fs
warning @ckeditor/ckeditor5-dev-utils > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS
 already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: ht
tps://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning @ckeditor/ckeditor5-markdown-gfm > turndown > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.
now() and performance.timeOrigin.
warning webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > babel-loader@9.1.3" has unmet peer dependency "@babel/core@^7.12.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 23.78s.

chlosi@d78022 MINGW64 /c/dev/src/editors/ckeditor5-demos/markdown (master)
$ yarn start
yarn run v1.22.19
$ webpack serve --open /index.html --mode development
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9090/
<i> [webpack-dev-server] On Your Network (IPv4): http://10.26.12.72:9090/
<i> [webpack-dev-server] Content not from webpack is served from 'C:\dev\src\editors\ckeditor5-demos\markdown\' director
y
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
asset main.js 8.34 MiB [emitted] [big] (name: main) 1 related asset
orphan modules 472 KiB [orphan] 460 modules
runtime modules 1 KiB 6 modules
modules by path ./node_modules/ 6.67 MiB 1208 modules
./index.js 10.7 KiB [built] [code generated]
jsdom (ignored) 15 bytes [built] [code generated]
webpack 5.88.2 compiled successfully in 37816 ms

**Comment by Witoso** [comment]
Hey! Thanks for the report, checking `yarn why`

```
yarn why @ckeditor/ckeditor5-paragraph
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@ckeditor/ckeditor5-paragraph"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@ckeditor/ckeditor5-paragraph@39.0.2"
info Has been hoisted to "@ckeditor/ckeditor5-paragraph"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "ckeditor5#@ckeditor#ckeditor5-paragraph"
   - Hoisted from "@ckeditor#ckeditor5-build-classic#@ckeditor#ckeditor5-paragraph"
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "3.32MB"
info Disk size with transitive dependencies: "10.19MB"
info Number of shared dependencies: 9
=> Found "@webspellchecker/wproofreader-ckeditor5#@ckeditor/ckeditor5-paragraph@40.0.0"
info Reasons this module exists
   - "@webspellchecker#wproofreader-ckeditor5#ckeditor5" depends on it
   - Hoisted from "@webspellchecker#wproofreader-ckeditor5#ckeditor5#@ckeditor#ckeditor5-paragraph"
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "3.32MB"
info Disk size with transitive dependencies: "10.19MB"
info Number of shared dependencies: 9
✨  Done in 0.18s.
```

Looks like `@webspellchecker/wproofreader-ckeditor5` dependency forces a newer version. If you don't plan to use it, remove it from the dependencies.

Most likely, we will remove this from the demos.

**Comment by chrislosinger** [comment]
Removed the dependency from package.json. 

Restarted node.

... yarn start.

Browser shows:

> Compiled with problems:
> ERROR
> Cannot find module '@webspellchecker/wproofreader-ckeditor5/src/wproofreader'
> webpackMissingModule@http://localhost:9090/dist/main.js:121285:50
> @http://localhost:9090/dist/main.js:121285:181
> @http://localhost:9090/dist/main.js:121580:3
> @http://localhost:9090/dist/main.js:121582:12
> ERROR in ./index.js 41:0-84
> Module not found: Error: Can't resolve '@webspellchecker/wproofreader-ckeditor5/src/wproofreader' in 'C:\dev\src\editors\ckeditor5-demos\markdown'

**Comment by Witoso** [comment]
Sorry for the lack of details. Make sure you remove it from the plugins lists in the editor configuration.

**Comment by Witoso** [comment]
Scope of the fix:
* bump versions of the packages
* remove `@webspellchecker/wproofreader-ckeditor5`
