### ISSUE TITLE
Inline Editor Issue - Editor loses focus when clicking on the bubble toolbar

### ISSUE THREAD

**Issue by balean12** [ckeditor/ckeditor5#15180]
I'm using CKEditor with React and for the onBlur event of the editor, im making a POST (save) request to the backend. However, I'm expecting that onBlur to be triggered only when I click outside the editor (textbox, toolbar included). In reality, if I'm pressing for example Bold button from the toolbar, the editor (textbox) loses focus and the onBlur method is triggered. How can I make it that when clicking the toolbar the onBlur function is not triggered?

**Comment by Witoso** [comment]
Hey, thanks for the request. Unfortunately, it won't be possible. `onBlur` is using an event implemented by the editor's core which reacts on blurring the editable. @filipsobol is there any other event that could be used?

**Comment by filipsobol** [comment]
Hey @balean12,

This can be achieved using FocusTracker. See this section for more information: https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/ui/focus-tracking.html#a-note-about-the-global-focus-tracker
