### ISSUE TITLE
How to prevent a certain part of the label from being deleted or cut in a document

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#15196]
## Provide a description of the task

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser:  chrome 118
* OS: Win10 21H2
* CKEditor version: 40
* Installed CKEditor plugins: …

I use some tags in the document to mark some data, but he should not be deleted or cut directly by the user
```html
<p>Hello<span data-value="100">user name</span></p>
```

**Comment by Witoso** [comment]
Just to better understand, you want to prevent users to be prevent deleting the text node `<span data-value="100">user name</span>`?

**Comment by huzedong2015** [comment]
> Just to better understand, you want to prevent users to be prevent deleting the text node `<span data-value="100">user name</span>`?

Yes, prevent users from editing or deleting
![image](https://github.com/ckeditor/ckeditor5/assets/14806813/336b85f2-ea93-4867-a4b7-1901e6e41d0e)

**Comment by Witoso** [comment]
I think this might be achieved by watching changes happening in `graveyard`. There was an example provided before [in a community issue](https://github.com/ckeditor/ckeditor5/issues/14053#issuecomment-1539976080).
