### ISSUE TITLE
When copying text, only part of it is copied.

### ISSUE THREAD

**Issue by topi09** [ckeditor/ckeditor5#15192]
## 📝 Provide detailed reproduction steps (if any)

1. …sample url >>> https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html
2. …
![image](https://github.com/ckeditor/ckeditor5/assets/121141493/88ab77f9-fd9d-4a55-936f-18b0fea43d7a)

3. …
![image](https://github.com/ckeditor/ckeditor5/assets/121141493/604ae272-a0cf-4e3a-83f2-d6aa99f7f01c)

After clicking Turn on read-only mode, if you select the entire text with a mouse click, the entire text will be copied.
However, if you click Turn off read-only mode and then select the entire text with a mouse click, only part of it will be copied.

If there is a space under the p tag surrounding the text, the entire text is copied, but if it is located at the end without a space, only part of it is copied.

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
I cannot reproduce this behavior, could you provide a video showing this and the browser details?

**Comment by topi09** [comment]
https://github.com/ckeditor/ckeditor5/assets/121141493/840c85b6-cbf3-4c5e-abff-ae59f5808da8

Attached is a video.
Browser is Chrome
Version 118.0.5993.70 (Official Build) (64-bit)


1. Copy the ckeditor5 address and paste it into the editor.
2. Click the switch to read-only mode button.
3. Click the address three times with the mouse and copy it.
4. When pasting, only words are pasted, not the entire address.
