### ISSUE TITLE
Provide information on the `text` property in the docs for the Mention feature

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15207]
## 📝 Provide a description of requested docs changes

Currently the [documentation for the Mention plugin](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html) makes no mention of the possibility to use the `text` property to customize how the mention will look in the editable.

We should include this information somewhere in the article.

**Comment by Witoso** [comment]
Could you link API docs that have this `text` or have some example?

**Comment by mabryl** [comment]
I believe it's this one: https://ckeditor.com/docs/ckeditor5/latest/api/module_mention_mention-MentionFeedItem.html#member-text

In the config it can look like this:

```
{ id: '@lilypad', userId: '2', name: 'Lily Aldrin', link: 'https://www.imdb.com/title/tt0460649/characters/nm0004989', text: 'Custom text' },
```

And this is the result in the editor:

https://github.com/ckeditor/ckeditor5/assets/72079603/da901dbc-a8d8-4880-bff4-8d7cd3a7e270

**Comment by mabryl** [comment]
Change on production: https://github.com/ckeditor/ckeditor5/pull/15227
