### ISSUE TITLE
Failure on installation for node 20+

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15203]
## 📝 Provide detailed reproduction steps (if any)

Node v20 is [the current active LTS](https://nodejs.dev/en/about/releases/), our engine allows `>=18`.

1.  Make sure your node is in 20+ version
2.  Launch `yarn reinstall` in `ckeditor5` repo.

### ✔️ Expected result

Install works correctly.

### ❌ Actual result

```shell
error @es-joy/jsdoccomment@0.36.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.8.1"
```

### ❓ Possible solution

```
yarn why @es-joy/jsdoccomment
=> Found "@es-joy/jsdoccomment@0.36.1"
info Reasons this module exists
   - "_project_#eslint-config-ckeditor5#eslint-plugin-ckeditor5-rules" depends on it
   - Hoisted from "_project_#eslint-config-ckeditor5#eslint-plugin-ckeditor5-rules#@es-joy#jsdoccomment"
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Let's see if upgrading https://github.com/ckeditor/ckeditor5-linters-config/blob/7852374add49fe23c9f7a436d7f119b35f5c6aa0/packages/eslint-plugin-ckeditor5-rules/package.json#L40 to the latest version helps.
