### ISSUE TITLE
CK EDITOR INTRODUCES NEW HTML TAGS FOR EXISTING TEXT AND MAKES THE ATTRIBUTE UPDATED WITHOUT USER ACTION

### ISSUE THREAD

**Issue by AdityaAmrutiyaOracle** [ckeditor/ckeditor5#15216]
## 📝 Provide detailed reproduction steps (if any)

We employ the CKE API to retrieve user-input data, which we then store in our database. When the page is loaded, we check for any existing data in the database and display it in the CKE. The problem arises from data that users entered using earlier versions of CKEditor several years ago. We recently transitioned to CKEditor 5 (CKE5), and as a result, when users load the page and leave it without making any updates, the data in the database still undergoes changes.

Essentially, the previous CKEditor versions encoded data differently from CKEditor 5. Although the displayed content in CKE5 may appear the same on the user interface, the underlying XML structure has been modified to align with CKEditor 5's standards. Consequently, this change triggers a database transaction even when the user has not made any alterations to the CKEditor data. 

For example this is a DB data we extracted for a user : 
```
<span style="color:rgb(51,51,51);font-family:Tahoma, Verdana, Helvetica, sans-serif;">
(See attachment for more details)</span><span style="color:rgb(51,51,51);font-family:Tahoma, Verdana,
Helvetica, sans-serif;">
<p class="MsoNormal" style="margin-bottom:0pt;line-height:normal;"><span style="mso-fareast-font-family:';;;
times new roman&ampquotmso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin;">EOS --  
EOS results improved for Principal Funds and Compliance.
<span style="mso-spacerun:yes;"> 
</span>Overall satisfaction increased to 75.9% (RIS 74.2%).  All index scores improved and are above both RIS and PFG scores.  
(See attachment for more details)</span></p></span>
```

### ✔️ Expected result

```
<span style="color:rgb(51,51,51);font-family:Tahoma, Verdana, Helvetica, sans-serif;">
(See attachment for more details)</span><span style="color:rgb(51,51,51);font-family:Tahoma, Verdana,
Helvetica, sans-serif;">
<p class="MsoNormal" style="margin-bottom:0pt;line-height:normal;"><span style="mso-fareast-font-family:';;;
times new roman&ampquotmso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin;">EOS --  
EOS results improved for Principal Funds and Compliance.
<span style="mso-spacerun:yes;"> 
</span>Overall satisfaction increased to 75.9% (RIS 74.2%).  All index scores improved and are above both RIS and PFG scores.  
(See attachment for more details)</span></p></span>
```

### ❌ Actual result

```
<p>
    <span style="color:rgb(51,51,51);">(See attachment for more details)</span>
</p>
<p>
    <span style="color:rgb(51,51,51);">EOS --  EOS results improved for Principal Funds and Compliance. 
Overall satisfaction increased to 75.9% (RIS 74.2%).  All index scores improved and are above both RIS and PFG scores.  
(See attachment for more details)</span>
</p>
```

### ❓ Possible solution

Please provide us with a script that can be used to transform the old format data to a format that is acceptable to cke5. 
Also share any other solution that you can come up with to avoid this issue. 

## 📃 Other details

* Browser: Any
* OS:Any
* First affected CKEditor version: 5
* Installed CKEditor plugins: WordCount

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by filipsobol** [comment]
As stated in the [migration guide](https://ckeditor.com/docs/ckeditor5/latest/updating/ckeditor4/migration-from-ckeditor-4.html) "CKEditor 5 should be considered a totally new editor" and "data produced with CKEditor 4 may not be compatible with CKEditor 5 which may lead to data loss".

Please refer to this document for help, especially the "Migrating existing data" and "Recommended migration strategy" sections.

> Please provide us with a script that can be used to transform the old format data to a format that is acceptable to cke5.

You can create a script using Puppeter (or a similar tool) to load each document from the backend, pass it to the editor instance using `editor.setData('<DATA>')`, then call `editor.getData()` to get the new data and update the database record.

However, I don't recommend this approach because every document opened in CKEditor 5 but coming from CKEditor 4 should be checked for data loss.

**Comment by anilahuja** [comment]
We are observing same issue even with CKE4 where text formatting is changed. Please see the attached document. We are trying to understand which CK Editor version we can use that can guarantee that the underlying text is not changed  as this is disrupting our business process or let us know any option that we can select to not convert the data.

**Case 1 with ASCII Code characters – HTML Entities are replaced with the actual Character.**

_Original Text:_

`<p>-Toimintaj&auml;rjestelm&auml;n mukainen Ainon kustannushallinta k&auml;ynniss&auml; ty&ouml;mailla. Ennuste sis&auml;lt&auml;&auml; riskit ja mahdollisuudet</p>`

Modified Text:

`<p>-Toimintajärjestelmän mukainen Ainon kustannushallinta käynnissä työmailla. Ennuste sisältää riskit ja mahdollisuudet</p>`
 
**Case 2.  Formatting removal – No change in the text display in the UI**

Original Text

```
<ol>
	<li>Upskill in the project management area&nbsp;</li>
	<li><span style=""font-size:11pt""><span><span style=""font-family:Calibri,sans-serif""><span style=""font-family:&quot;Shape Sans&quot;"">Prince2 certification</span></span></span></span></li>
	<li><span style=""font-size:11pt""><span><span style=""font-family:Calibri,sans-serif""><span style=""font-family:&quot;Shape Sans&quot;"">Lead and deputise PMs on projects</span></span></span></span></li>
	<li><span style=""font-size:11pt""><span><span style=""font-family:Calibri,sans-serif""><span style=""font-family:&quot;Shape Sans&quot;"">Look for and express interest in secondment opportunities</span></span></span></span></li>
</ol>
```

Modified Text:

`<ol><li>Upskill in the project management area&nbsp;</li><li>Prince2 certification</li><li>Lead and deputise PMs on projects</li><li>Look for and express interest in secondment opportunities</li></ol>
`

**Comment by filipsobol** [comment]
1. `Case 1 with ASCII Code characters` - from our perspective, this is expected and valid behavior. If this doesn't work for you, you can work around it by changing the encoding yourself on data returned from the editor.
2. `Case 2. Formatting removal – No change in the text display in the UI` - These attributes can be maintained using a [General HTML Support plugin](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html). You can see it in action (with configuration available below the editor) on this page: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html. Note that the original text you provided is not valid HTML (double `"` in `style`) and needs to be fixed before it can be used.
