### ISSUE TITLE
Autosave demo broken

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15238]
The [autosave](https://ckeditor.com/docs/ckeditor5/latest/features/autosave.html) panel is too wide:

![image](https://github.com/ckeditor/ckeditor5/assets/9881379/3b98aa40-f5e7-42a2-8bed-0a6ce19734ea)

**Comment by godai78** [comment]
Can you provide background info? Like browser and OS? I cannot recreate it neither on Chrome, nor on Firefox or Safari.

**Comment by Witoso** [comment]
MacOS, Chrome Version 118.0.5993.88

Same in the [Save](https://github.com/ckeditor/ckeditor5/issues/15238) demo:

![](https://github.com/ckeditor/ckeditor5/assets/9881379/41ab9da6-c2f4-4866-a3e6-02cda1fc1c27)

**Comment by godai78** [comment]
@Witoso what is wrong with the picture you posted? They look exactly the same width for me...

**Comment by pszczesniak** [comment]
@godai78 maybe it will look better after removing some `ck -ck-content` CSS classes from this `autosave` bar? WDYT?

cc @Witoso 

![](https://github.com/ckeditor/ckeditor5/assets/7074833/969d2c04-cfda-4a14-933b-329ac78b5bdf)

**Comment by godai78** [comment]
Might work. We added the `ck -ck-content` class for a purpose, but it's not that needed here, actually.

**Comment by godai78** [comment]
Only kept the first div style:
![Screenshot 2023-10-30 at 08 38 59](https://github.com/ckeditor/ckeditor5/assets/68123541/550a8644-a5ea-41d8-afad-cfeb25eb71f0)

**Comment by pszczesniak** [comment]
For me it looks ok :+1:

**Comment by Witoso** [comment]
This was a regression, look how it worked in [https://ckeditor.com/docs/ckeditor5/36.0.1/installation/getting-started/getting-and-setting-data.html#demo](https://ckeditor.com/docs/ckeditor5/36.0.1/installation/getting-started/getting-and-setting-data.html#demo)

I think that fixes you applied, worked :)
