### ISSUE TITLE
Images can't be selected inside tables in certain scenarios

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1523]
![feb-12-2019 15-27-31](https://user-images.githubusercontent.com/156149/52642218-d999e300-2eda-11e9-964d-35789b752b5e.gif)

**Comment by jodator** [comment]
@Reinmar to be 100% sure - it's a single image in table cell that cannot be selected, right?

**Comment by Reinmar** [comment]
Yes.

And the problem  is that fake selection isn't created at all in those cases. Just like we noticed for inline widgets.

**Comment by Reinmar** [comment]
Another one: https://github.com/ckeditor/ckeditor5/issues/1524

I'm going to review those changes with inline widgets now :D

**Comment by Reinmar** [comment]
The PRs for inline widgets don't help here. This is a separate issue.

After some more investigation, it turned out that it is reproducible when clicking on an image in a blurred table cell (when the selection is in another cell or outside table). It's not visible when the image is the only/first element of that cell because then it gets automatically selected when the browser tries to make a collapsed selection at the beginning of that cell.

This issue can be caused by the order in which we render things. I guess that it may look like this:

1. the user clicks on an image
2. we decide to select that image
3. we start rendering this
4. we remove the old fake selection container (note: selection containers are rendered in the closest editable parent element; in CKE4 they were always rendered in the root editable – this is a coincident and perhaps could be changed)
5. we focus the editable in which the new selection will be rendered
6. this causes some selection change (perhaps because the old fake sel container was removed)
7. this breaks the rendering or perhaps causes another rendering to be triggered
