### ISSUE TITLE
Example Customize the undo|redo function

### ISSUE THREAD

**Issue by China-Robin** [ckeditor/ckeditor5#15239]
## 📝 Provide a description of the new feature

We need to implement the operation experience similar to Microsoft Office Word in use. I have checked the source code and found that the current undo|redo does not meet our requirements. We expect batch to be saved once the user enters one character, but batch is saved once the user enters 20 characters at present. We want to have a configuration that we can choose for ourselves, and an upper limit on the weak set that can be saved, such as the following configuration:
{
    undo:  {
        batch: 1,
        stepNumber: 200,  
    }
}

My English level is not very good, if not particularly clear, please feel free to contact me 😜

Or is there another way to do it? 😋

**Comment by China-Robin** [comment]
By looking at the source code, you can see that you can use configuration control:
typing: {
  undoStep: 5,
}

**Comment by Witoso** [comment]
Thanks for posting your solution. 

Internal sidenote: I think we need to rethink into which section of a feature guild we should add information about the possible configuration.
