### ISSUE TITLE
[Dev] Enable environment setup replacement in docs building process

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1525]
It will allow reusing the `snippetadapter.js` file in other umberto projects without much hacking.

The snippet adapter should be able to replace variables (aka preprocess variables) in the compilation step so we'll be able to build docs with different environment setups.

**Comment by Reinmar** [comment]
Custom comment loader? What is it?

**Comment by ma2ciek** [comment]
Custom comment loader is a webpack loader that will be able to parse special JS comments and for the given values (passed directly to the `snippetadapter.js` file) will be able to uncomment such comment lines and injects there values.

E.g. for the given options `{ SOME_CONSTANT: 'VALUE' }` and the following code:

```js
// @if SOME_CONSTANT // x = SOME_CONSTANT
```

It will be processed by webpack during the `yarn docs` command to the following:

```js
x = 'VALUE'
```

**Comment by ma2ciek** [comment]
The snippet adapter should be able to replace variables (aka preprocess variables) in the compilation step so we'll be able to build docs with different environment setups.
