### ISSUE TITLE
Docs issue report from "features/drag-drop.html"

### ISSUE THREAD

**Issue by mahdi-esmaeelnezhad** [ckeditor/ckeditor5#15270]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/drag-drop.html

### Project version

40.0.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
DUP: #15271
