### ISSUE TITLE
Multiple root editors searching for replacement revocation issues

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#15299]
## 📝 Provide detailed reproduction steps (if any)

1. For example, I have three roots, each containing apple content
2. Replace 'apple' with 'apple2'
3. revoke

### ✔️ Expected result

All substitutions in the root were successfully revoked

### ❌ Actual result

Only the last root has been revoked
I need to revoke it three times
### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: v38
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Could you elaborate what do you mean by `Replace 'apple' with 'apple2'`? What is this action?

**Comment by huzedong2015** [comment]
![image](https://github.com/ckeditor/ckeditor5/assets/14806813/bd027229-859d-42cb-aa97-004c92ed0157)

**Comment by huzedong2015** [comment]
> ![image](https://user-images.githubusercontent.com/14806813/280441121-bd027229-859d-42cb-aa97-004c92ed0157.png)

When there are substitutions in multiple roots, undo can only undo one substitution

**Comment by Witoso** [comment]
@scofalik could you comment this behavior?

**Comment by huzedong2015** [comment]
https://github.com/ckeditor/ckeditor5/issues/13892 Above version 39 has been fixed
