### ISSUE TITLE
Paragraph is created inside paragraph when pressing Enter on a selected inline widget

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1529]
1. Go to http://localhost:8125/ckeditor5-widget/tests/manual/inline-widget.html
1. Select an inline widget.
1. Press enter.
1. Check the model/DOM structure. You will find a paragraph inside a paragraph (or other block element).

**Comment by Reinmar** [comment]
Reproducible on https://github.com/ckeditor/ckeditor5-widget/pull/70/files and related PRs (listed in the former one).

**Comment by oskarwrobel** [comment]
It's caused by the widget enter handler

https://github.com/ckeditor/ckeditor5-widget/blob/master/src/widget.js#L274-L279.
