### ISSUE TITLE
`gulp update` could do a `fetch all` in all repos (including the core)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#153]
I've seen that I miss such thing. I run `gulp update` and then I expect that all repos are fully fetched, that I don't have to do anything more there if I want to switch to some other branch.

**Comment by Reinmar** [comment]
One thing that hasn't been added in #156 was fetching in the main repo `ckeditor5`.

**Comment by oskarwrobel** [comment]
Right now `gulp update` does nothing with `ckeditor5` repo. It handles only dependency repos, that's why I didn't add fetching for it. We can't update or checkout main branch in this task, but sure, we can do fetch. I'm on it.
