### ISSUE TITLE
When selecting a heading (h1,h2,h3) in a list, the list turns into a paragraph and 'Choose a heading' dropdown button appears

### ISSUE THREAD

**Issue by balean12** [ckeditor/ckeditor5#15300]
1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/headings.html
2. Choose Heading 2
3. Select bulleted list

### ✔️ Expected result

**A list that contains a Heading 2. <ul><li><h2>Text</h2></li></ul>**

### ❌ Actual result

**Text turns into a paragraph and dropdown button turn into 'Choose a heading'**

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

However, if you go to: https://ckeditor.com/ckeditor-5/demo/feature-rich/ and to the exact same steps, the expected result is the correct one.

How can this be fixed? I am using a CKEditor5 custom build of an inline editor with react

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by balean12** [comment]
I guess this can be achieved with https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html

**Comment by Witoso** [comment]
That's true, document list will soon become the main implementation: https://github.com/ckeditor/ckeditor5/issues/14767
