### ISSUE TITLE
InputTextView value property does not update automatically

### ISSUE THREAD

**Issue by tomegz** [ckeditor/ckeditor5#15314]
[InputTextView.value](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_inputtext_inputtextview-InputTextView.html#member-value) is an observable property, I would expect it to be updated automatically on every `input` event, however it is not. My use case: I would like to process input's value property and bind it to button.isEnabled property.

Repro steps:
1. Create input text view `const inputTextView = new InputTextView();`
2. Listen for event: `inputTextView.on('change:value', () => console.log('value changed'));`
3. Render the input

### ✔️ Expected result

'change:value' is emitted on every `input` event

### ❌ Actual result

The `value` property is not updated

### ❓ Possible solution and my current workaround

`inputTextView.on('input', () => inputTextView.set('value', inputTextView.element?.value);`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@oleq could you share the reasoning behind it?

**Comment by oleq** [comment]
Our UI library does not support two-way data binding. We're more on the React-side on this: we set values via props (observables, e.g. [`InputTextView#value`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_inputtext_inputtextview-InputTextView.html#member-value)) and we fire events upon user actions (e.g. [`InputTextView#input`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_inputtext_inputtextview-InputTextView.html#event-input))

I [described this issue a few years back](https://github.com/ckeditor/ckeditor5/issues/5276) with possible solutions and problems that would need to be addressed.

**Comment by Witoso** [comment]
@tomegz thanks for the issue! We plan to work on our UI library experience and enhancements next year. For now this is something we will not work on but is a valid feedback for our plans.

**Comment by tomegz** [comment]
@oleq @Witoso Understood, thanks for quick replies
