### ISSUE TITLE
can we have lists automatically numbered?

### ISSUE THREAD

**Issue by feikerwu** [ckeditor/ckeditor5#15342]
lists automatically numbered link in gdocs
<img width="370" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/39146693/7cab55bc-c0f8-48b1-a24a-6c9f2cee9590">

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Duplicate of https://github.com/ckeditor/ckeditor5/issues/10859.
