### ISSUE TITLE
Build from source fails: ERESOLVE could not resolve dev @ckeditor/ckeditor5-react@"^6.0.0" from the root project

### ISSUE THREAD

**Issue by sergiks** [ckeditor/ckeditor5#15357]
## 📝 Provide detailed reproduction steps (if any)

1. clone the ckeditor/ckeditor5 repository
2. I used Docker to have fresh version of NodeJS, npm. Inside the cloned folder run `docker run --rm -it -v $PWD:/ckeditor -w /ckeditor node:21 bash` — this opens shell in the repo folder. node v21.1.0, npm 10.2.0
3. `npm install` 

### ✔️ Expected result

I'd expect successful installation of the dependencies, to be able to proceed with `npm run build`

### ❌ Actual result

Error resolving ckeditor/ckeditor5-react:

    root@51c01b1f124c:/ckeditor# npm install
    npm notice 
    npm notice New patch version of npm available! 10.2.0 -> 10.2.4
    npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
    npm notice Run npm install -g npm@10.2.4 to update!
    npm notice 
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE could not resolve
    npm ERR! 
    npm ERR! While resolving: ckeditor5@40.1.0
    npm ERR! Found: dev @ckeditor/ckeditor5-react@"^6.0.0" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! dev @ckeditor/ckeditor5-react@"^6.0.0" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! 
    npm ERR! For a full report see:
    npm ERR! /root/.npm/_logs/2023-11-16T08_50_17_920Z-eresolve-report.txt

### ❓ Possible solution

Automated tests should have catch this conditions so that dependencies have no conflicts in a release.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@pomek there was some issue regarding the usage on `npm` vs `yarn` in our monorepo. Do you remember?

@sergiks what's your use case? Why do you clone the repo, and not use the published packages?

**Comment by sergiks** [comment]
> @sergiks what's your use case? Why do you clone the repo, and not use the published packages?
We're using customized mods of some of the components, hence the build from sources. The current task was to add the Ai Assistant plugin, leading to update of the CKEditor version we were using.
Already solved the task. This issue is no more a stopper for us. Thanks!

**Comment by Badlapje** [comment]
> > @sergiks what's your use case? Why do you clone the repo, and not use the published packages?
> 
> We're using customized mods of some of the components, hence the build from sources. The current task was to add the Ai Assistant plugin, leading to update of the CKEditor version we were using. Already solved the task. This issue is no more a stopper for us. Thanks!

@sergiks how did you solve it?
