### ISSUE TITLE
Question: How to listen SourceEditingPlugin isSourceEditingMode change 

### ISSUE THREAD

**Issue by yoyo837** [ckeditor/ckeditor5#15375]
## Provide a description of the task

I want to sense in real time whether the source code mode is turned on to control some external behaviors.

## 📃 Other details

* Browser:  Chrome 119
* OS: MacOS 14
* CKEditor version: 40.1.0
* Installed CKEditor plugins: 
```js
        Essentials,
	Base64UploadAdapter,
	FileUploadSupport,
	SimpleUploadAdapter,
	Autoformat,
	Bold,
	Italic,
	BlockQuote,
	Heading,
	Image,
	AutoImage,
	ImageResize,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	ImageInsert,
	Indent,
	IndentBlock,
	Link,
	LinkImage,
	LinkImageEditing,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	PictureEditing,
	Table,
	TableToolbar,
	TextTransformation,
	Alignment,
	Highlight,
	Font,
	SourceEditing,
	ExtendHTMLSupport,
	HtmlComment,
```

**Comment by yoyo837** [comment]
Thanks for your reply, but I tried this case (case 1), it doesn't work:

```js
window.ClassicEditor.create(document.getElementById("ckeditor5"), config).then(
  (editor) => {
    // 
    editor.on("change:isSourceEditingMode", () => {
      // 
    });
  }
);

```

It' works by(case 2):

```js
import { Command } from '@ckeditor/ckeditor5-core';

const cmd = 'xiumiImporter';

export default class XiumiImporterCommand extends Command {
	refresh() {
		const editor = this.editor;
		const SourceEditing = editor.plugins.get('SourceEditing');
		this.isEnabled = !SourceEditing?.isSourceEditingMode;
	}

	execute() {
		//
	}
}

XiumiImporterCommand.Command = cmd;

```

In the previous case 1, how to make it work?

**Comment by Witoso** [comment]
Like this

```javascript
const sourceEditing = editor.plugins.get('SourceEditing');
sourceEditing.on('change:isSourceEditingMode', () => {
      console.log('changed source editing')
    });
```

**Comment by yoyo837** [comment]
> Like this
> 
> ```js
> const sourceEditing = editor.plugins.get('SourceEditing');
> sourceEditing.on('change:isSourceEditingMode', () => {
>       console.log('changed source editing')
> });
> ```

It works. You saved me. Thank you so much.

**Comment by jokerham** [comment]
For react, following I added onReady as following 
`
      <CKEditor 
        id='editor'
        editor={ ClassicEditor }
        config={ CKEditorConfig }
        data={content}
        onReady={(editor) => {        
          const sourceEditing = editor.plugins.get('SourceEditing');
          
          // Listen for when source mode is activated
          sourceEditing.on('change:isSourceEditingMode', (eventInfo, name, value) => {
            console.log(eventInfo);
            console.log(name);
            console.log(value);
            if (value) {
              const container = document.querySelector('.ck-source-editing-area');
              if (container) {
                const textarea = container.querySelector('textarea');
                console.log(textarea);
                if (textarea) {
                  textarea.addEventListener('blur', () => {
                    sourceEditing.updateEditorData(); // Sync changes
                    setContent(editor.getData());
                  });
                }
              }
            } else {
              console.log('Source editing mode is disabled');
            }
          });
        }}
        onChange={(event, editor) => {
          setContent(editor.getData());
        }}`

**Comment by jokerham** [comment]
For React, I added the following `onReady` setup:

```js
<CKEditor 
  id="editor"
  editor={ClassicEditor}
  config={CKEditorConfig}
  data={content}
  onReady={(editor) => {
    const sourceEditing = editor.plugins.get('SourceEditing');

    // Listen for source mode toggle
    sourceEditing.on('change:isSourceEditingMode', (eventInfo, name, value) => {
      console.log(eventInfo);
      console.log(name);
      console.log(value);

      if (value) {
        const container = document.querySelector('.ck-source-editing-area');
        if (container) {
          const textarea = container.querySelector('textarea');
          console.log(textarea);
          if (textarea) {
            textarea.addEventListener('blur', () => {
              sourceEditing.updateEditorData(); // Sync changes
              setContent(editor.getData());
            });
          }
        }
      } else {
        console.log('Source editing mode is disabled');
      }
    });
  }}
  onChange={(event, editor) => {
    setContent(editor.getData());
  }}
/>
```
