### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules error when i tried to import Alignment plugin

### ISSUE THREAD

**Issue by floinay** [ckeditor/ckeditor5#15374]
## 📝 Provide detailed reproduction steps (if any)

1. …Install ckeditor
2. …Add Alignment plugin
Playground: https://playcode.io/1667247

```
import {ClassicEditor} from '@ckeditor/ckeditor5-editor-classic';
import {Alignment} from "@ckeditor/ckeditor5-alignment";


const element = document.querySelector('#app');
ClassicEditor.create(element, {
    ui: {poweredBy: {forceVisible: false}},
    plugins: [
        Alignment
    ] 
});

window.editor = editor;
console.log(Array.from(editor.ui.componentFactory.names()), editor.commands);
```

### ✔️ Expected result

Editor works with Alignment feature

### ❌ Actual result

CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at <anonymous>:118:11
    at window.<computed>./node_modules/@ckeditor/ckeditor5-utils/src/version?_v=40.1.0&_env=dev (<anonymous>:123:3)
    at BFSRequire (<anonymous>:25:89171)
    at <anonymous>:286:24
    at window.<computed>./node_modules/@ckeditor/ckeditor5-engine?_v=40.1.0&_env=dev (<anonymous>:27988:3)
    at BFSRequire (<anonymous>:25:89171)
    at <anonymous>:963:33
    at window.<computed>./node_modules/@ckeditor/ckeditor5-core?_v=40.1.0&_env=dev (<anonymous>:1504:3)
    at BFSRequire (<anonymous>:25:89171)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thanks for sharing a working example :) It helps a ton to debug.

And the issue is here:

```
{
  "dependencies": {
    "@ckeditor/ckeditor5-alignment": "40.1.0",
    "@ckeditor/ckeditor5-editor-classic": "40.0.0"
  }
}
```

Both packages are installed in different versions.

You need all CKE5 packages (official ones) to be installed in the exactly the same version.

**Comment by floinay** [comment]
thx for reply, i updated version, but error did not disappear 
https://playcode.io/1667247

**Comment by floinay** [comment]
> Does it happen in your local environment as well? I assume playcode may be doing something strange to caching packages.

Yes, you're right, thanks
