### ISSUE TITLE
Drag-and-drop text does not work in CKEditor 5.

### ISSUE THREAD

**Issue by Tom-Robinson** [ckeditor/ckeditor5#1538]
I consider it a 🐞 Bug, but maybe I'm asking for a new 🆕 Feature.
💻 Version of CKEditor 5: 11.2.0 in the online demos.
📋 Steps to reproduce:
Go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
Scroll to bottom, then select the sentence "You learn to adapt as you go. " in 2nd-last paragraph.
Include the trailing space in the selection.
Now drag the selection and drop it in front of "Going to a new..." in the last paragraph.
✅ Expected result:
During dragging, a precise insertion point shows where the selection will be inserted when dropped.
The old location closes up around the deletion, leaving "...skills. Here's..." with a single space between sentences.
After the insertion, the new location shows a single space between sentences in "...go. Going...".
❎ Actual result:
Firefox 65.0.1 64-bit
Dropping the text does not move anything.
The space at the end of the selection is deleted, leaving "...go.Here's..."

Chrome 72.0.3626.109 64-bit
No drop insertion point is shown during dragging.
Dropping the text does not move anything.
The space at the end of the selection is deleted, leaving "...go.Here's..."

Edge 44.17763.1.0
As soon a dragging starts, the window scrolls almost to the top, with the video visible but "...years of travelling." still scrolled out of view.
Dropping the text anywhere at all causes it to be inserted at the very beginning of the editor, in front of "The three greatest...", with no separating space.
The text still exists at its old location.

Moving text with Ctrl-x/Ctrl-v works fine in all browsers.
CKEditor 4 works as expected. Plain vanilla contenteditable works as expected in Chrome and Firefox.

**Comment by Mgsy** [comment]
Hi, @Tom-Robinson! Thanks for the report. Currently, CKEditor 5 doesn't support the content drag & drop, so you might experience some unexpected behaviour after using it. However, it's on our roadmap, you can track progress and join the discussion in [this ticket](https://github.com/ckeditor/ckeditor5-clipboard/issues/23).
