### ISSUE TITLE
HTMLSupport: Confliction on whether this is supported or not

### ISSUE THREAD

**Issue by gregg-cbs** [ckeditor/ckeditor5#15389]
## 📝 Confused by HtmlSupport config property. Its not working.
In the docs [there is a page for HTMLSupport](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html):
![image](https://github.com/ckeditor/ckeditor5/assets/57114335/74bd26a2-e67b-4691-9ec7-eb6e27bcda11)

In your api core [config docs HtmlSupport](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html) is there:
![image](https://github.com/ckeditor/ckeditor5/assets/57114335/cbb5cda4-d79a-402b-a4bd-c2bbcd648243)

in the [other api docs](https://ckeditor.com/docs/ckeditor5/latest/api/html-support.html), it says it is experimental and not production ready (confused now)
![image](https://github.com/ckeditor/ckeditor5/assets/57114335/bdaf15b2-0052-4c09-8d19-fe4b959f8a7e)

In the CKEditor Classic this property is not available:
![image](https://github.com/ckeditor/ckeditor5/assets/57114335/9d0a2640-c859-4b81-9f03-a86397abd789)

I cannot seem to get htmlSupport to work. Its an old feature because CK4 had allowed property.

Using React how do i enabled htmlSupport?

**Comment by Witoso** [comment]
Thanks for the feedback, we will fix the docs. GHS is production ready.

As for adding it, you're trying to extend [a predefined build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html). It's not possible, and you need to go [the custom build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html) route. It's a confusing setup, we are in the process it fixing it, with an ETA early next year.

**Comment by gregg-cbs** [comment]
I see Strapi has started using CKEditor or at least has a plugin for it now. Congrats on that. I tried custom build route but eventually gave up. Hoping these upcoming changes make it easier to extend 👍 Thank you.

**Comment by Witoso** [comment]
Link to the related RFC #15502
