### ISSUE TITLE
Docs issue report from "support/error-codes.html"

### ISSUE THREAD

**Issue by ABorovenskyi** [ckeditor/ckeditor5#15386]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-presencelist-missing-container

### Project version

40.1.0

### Is there something missing in the guide? What is it?

error code is missing `presencelist-missing-container`

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
You need to create a container for the presence list, as [described in the guide](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/users-in-real-time-collaboration.html#users-presence-list).

@scofalik why this error is not in the error-codes list? Is it an old one?

**Comment by oleq** [comment]
> @scofalik why this error is not in the error-codes list? Is it an old one?

Error code doclets for the `PresenceListUI` plugin were private indeed. I changed that and they should show up on the [error code](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html) reference list when the documentation page re-generates. Sorry for the inconvenience, @ABorovenskyi.
