### ISSUE TITLE
The contextual toolbar is suspended and suspended, causing the toolbar to occasionally disappear

### ISSUE THREAD

**Issue by luckygilrhpp** [ckeditor/ckeditor5#15394]
## 📝 Provide detailed reproduction steps (if any)

When I use the rich text editor in my project, the version of ckeditor5 custom build causes the contextual toolbar to hover and disappear occasionally when scrolling content up and down.
![image](https://github.com/ckeditor/ckeditor5/assets/142486524/6ef11f45-bf53-41fa-80c9-1e3dc13008a7)

### ✔️ Expected result
![image](https://github.com/ckeditor/ckeditor5/assets/142486524/4c116c36-f2db-44ec-b1ad-e87244de115a)

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser:Chrome
* OS: …
* First affected CKEditor version:  ckeditor5 custom build
* Installed CKEditor plugins:"@ckeditor/ckeditor5-alignment": "^33.0.0",
    "@ckeditor/ckeditor5-autoformat": "^33.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^33.0.0",
    "@ckeditor/ckeditor5-block-quote": "^33.0.0",
    "@ckeditor/ckeditor5-cloud-services": "^33.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^30.5.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^30.5.0",
    "@ckeditor/ckeditor5-editor-classic": "^33.0.0",
    "@ckeditor/ckeditor5-essentials": "^33.0.0",
    "@ckeditor/ckeditor5-font": "^33.0.0",
    "@ckeditor/ckeditor5-heading": "^33.0.0",
    "@ckeditor/ckeditor5-html-support": "^33.0.0",
    "@ckeditor/ckeditor5-image": "^33.0.0",
    "@ckeditor/ckeditor5-indent": "^33.0.0",
    "@ckeditor/ckeditor5-link": "^33.0.0",
    "@ckeditor/ckeditor5-list": "^33.0.0",
    "@ckeditor/ckeditor5-media-embed": "^33.0.0",
    "@ckeditor/ckeditor5-paragraph": "^33.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^33.0.0",
    "@ckeditor/ckeditor5-source-editing": "^33.0.0",
    "@ckeditor/ckeditor5-table": "^33.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^33.0.0",
    "@ckeditor/ckeditor5-typing": "^33.0.0",
    "@ckeditor/ckeditor5-upload": "^33.0.0",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Please upgrade the editor to the newest version, there were some improvements to the handling of toolbars and balloons.
