### ISSUE TITLE
Entering ins_user_ in ckeditor5 will be recognized as italic insuser

### ISSUE THREAD

**Issue by shuai1123** [ckeditor/ckeditor5#1539]
Entering ins_user_ in ckeditor5 will be recognized as italic insuser (the underline will be recognized as italic before and after the word). Entering Ins_user_attr in the input method in the table will also produce a weird effect, and insuserins_user_ains_user_attr will appear.

**Comment by Reinmar** [comment]
This feature is called autoformatting and you can:

* disable it completely,
* press Ctrl+Z to undo the formatting action after typing `_user_` – example:
   1. you type `_user`
   2. you type `_`
   3. editor makes `user` italic and removes `_` characters,
   4. press Ctrl+z,
   5. you get `_user_` (no italic).

**Comment by shuai1123** [comment]
How do I disable autoformatting

**Comment by Reinmar** [comment]
See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html#removing-features

The plugin name in this case is `'Autoformat'`.

**Comment by shuai1123** [comment]
> See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html#removing-features
> 
> The plugin name in this case is `'Autoformat'`.

Thank you very much, the worship from a Chinese girl.

**Comment by MuhammadAsadUllah821** [comment]
I am having similar issue but with numbers, when I right 1/2 it automatically converts to ½

**Comment by travis-brooks** [comment]
Anyone have a link to this that isn't dead?

**Comment by Witoso** [comment]
Hmm: https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/configuration.html#removing-features

Works for me 🤔

**Comment by travis-brooks** [comment]
Yes, the one I posted works, the ones above don't anymore (at least for me).
