### ISSUE TITLE
Gulp watch tasks fails on temporary files created by IDE

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#154]
I have some problems with `gulp build --watch` when using it inside IDE (PHPStorm).

The problem is that probably PHPStorm creates temporary file when saving source file.
Example error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat '/home/jodator/projects/cksource/ckeditor5/git/ckeditor5-engine/src/treemodel/delta/insertdelta.js___jb_tmp___'
    at Error (native)
```

To address this we could specify patterns of files to watch only for those that matters (js, jsdoc, html, scss, etc) but this might be cubersome. Also we could exclude `jb_tmp` as this is probably used by JetBrains products.

**Comment by Reinmar** [comment]
We can't whitelist files that must be included, so we must blacklist them. We simply won't be able to predict all kinds of files which needs to be copied by the builder.

**Comment by szymonkups** [comment]
I had similar problem with WebStorm - I've disabled `Use "safe write" (save changes to a temporary file first)` in `Apperance & Behavior` -> `System Settings`. It's not the best solution but it's working for me for a while without any problems.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev-compiler/issues/21.
