### ISSUE TITLE
Create an executable script for the stale bot

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#15402]
## Provide a description of the task

The goal is to create a friendly command line interface that allows running the stale bot.

```bash
yarn ckeditor5-dev-stale-bot --config-path ./path/to/config.js
```

The configuration file should export an object containing properties that are required by sub-tasks (find stale and close stale items).

_Part of ckeditor/ckeditor5#15399._

**Comment by psmyrek** [comment]
Done in:
- https://github.com/ckeditor/ckeditor5-dev/pull/931
- https://github.com/ckeditor/ckeditor5-dev/pull/932
