### ISSUE TITLE
Undo leaks one element (which should be removed when undoing but isn't)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1540]
![feb-18-2019 09-59-41](https://user-images.githubusercontent.com/156149/52939275-0418ef80-3364-11e9-910b-5aded399d456.gif)

1. Remove all contents.
2. Paste a couple of blocks.
3. Press ctrl+a.
4. Paste the same content  again.
5. Undo twice.

Expected: empty editor.

Actual: the last block is still visible.

**Comment by Reinmar** [comment]
This is not a regression and I don't think this is causing some crashes, but it seems quite easy to reproduce.

**Comment by scofalik** [comment]
The problem occurs just for two block elements (two paragraphs are enough).
