### ISSUE TITLE
Ckeditor 5 custom build in angular 16 library

### ISSUE THREAD

**Issue by Dovernh** [ckeditor/ckeditor5#15413]
📝 Provide detailed reproduction steps (if any)

I have created an angular 16 library with a custom ckeditor5 build.

- ckeditor5-custom-build
- projects
-    abc-editor
-         lib
-            abc-editor
-             component
-                 abc-component.ts
-                 abc-component.html
-  showcase
-      src
-          app
-              editor
-                  editor.component.ts
-                  editor.component,html

If I run the showcase the editor works, no issues
If I try and build the abc-editor it fails

✔ Compiling with Angular sources in Ivy partial compilation mode.
✖ Generating FESM bundles
Could not load C:\appdev\otised\ABC.Editor\ckeditor5-custom-build\build\ckeditor.js (imported by dist/abc-editor/esm2022/lib/abc-editor/component/abc-editor.component.mjs): Could not load 'C:\appdev\otised\OtisEd.Editor\ckeditor5-custom-build\build\ckeditor.js' from memory.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this com

### ✔️ Expected result

build library

### ❌ Actual result

build error

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._
????

## 📃 Other details

* Browser: any
* OS: windows
* Version 5
*Plugins: custom build

I've tried angular 15 and 17, same error

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Dup https://github.com/ckeditor/ckeditor5-angular/issues/399
