### ISSUE TITLE
Improve CKEditor 5 metadata files

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#15414]
## 📝 Provide a description of the improvement

I noticed that some packages miss the metadata file or contain invalid entries. Examples:

* [Undo registers two buttons](https://github.com/ckeditor/ckeditor5/blob/dd4a5dea1c395a6267dd4937dd57c685b5077e10/packages/ckeditor5-undo/src/undoui.ts#L38-L39) and [they are not described](https://github.com/ckeditor/ckeditor5/tree/dd4a5dea1c395a6267dd4937dd57c685b5077e10/packages/ckeditor5-undo).
* Some entries are empty, while others aren't.
	* https://github.com/ckeditor/ckeditor5/blob/4854443c0ab304833cfeba302faf458f1e2a5243/packages/ckeditor5-image/ckeditor5-metadata.json#L26
	* https://github.com/ckeditor/ckeditor5/blob/4854443c0ab304833cfeba302faf458f1e2a5243/packages/ckeditor5-image/ckeditor5-metadata.json#L163
* Improve the metadata validator by forcing passing a value. [Empty strings should not pass.](https://github.com/ckeditor/ckeditor5/blob/dd4a5dea1c395a6267dd4937dd57c685b5077e10/scripts/ci/validate-metadata-files.js#L149)
	* `iconPath` may not exist at all, and it's fine. 

Hence, we need to create missing files and fill in empty ones.

The ticket touches both repos.

**Comment by pomek** [comment]
I wrote a simple script to find the missing ckeditor5-metadata.json` file for packages providing a UI layer.

```js
'use strict';

const glob = require( 'glob' );
const { existsSync } = require( 'fs' );
const { relative } = require( 'path' );

console.log(
	glob.sync( [ 'packages/*/', 'external/ckeditor5-commercial/packages/*/' ], { absolute: true } )
		// Ignore build-* and editor-* packages as they not provide any feature.
		.filter( dirName => !dirName.match( /ckeditor5-(?:build|editor)-/ ) )
		// Keep packages that miss the "ckeditor5-metadata.json" files.
		.filter( dirName => !existsSync( dirName + '/ckeditor5-metadata.json' ) )
		// Find all files that could register a UI component.
		.map( relativeDirName => ( {
			directory: relativeDirName,
			files: glob.sync( relativeDirName + '/**/*ui.ts' )
		} ) )
		// And filter out invalid packages.
		.filter( ( { files } ) => files.length )
		.map( ( { directory } ) => directory )
		// Calculate a relative path.
		.map( dirName => relative( process.cwd(), dirName ) )
);
```

Results:

```js
[ 'packages/ckeditor5-undo' ]
```

**Comment by wimleers** [comment]
🙏 👏
