### ISSUE TITLE
CKEditor version collision in the placeholder guide

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1542]
Open console in https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/placeholder.html.

![image](https://user-images.githubusercontent.com/1099479/53020201-b4ffb700-3456-11e9-9804-de5854e4cdad.png)

The solution is most likely creating a single editor build with 2 `create()` rather than 2 separate builds in each snippet.

**Comment by majordesigner** [comment]
When I use ckeditor5 in react. still has same error on console.

**Comment by oleq** [comment]
@majordesigner Can you tell us more about your use case?
