### ISSUE TITLE
Cannot undo in empty content in Balloon block editor [mobile]

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1543]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Go to the ballon block editor docs page
2. Select all content
3. Cut it
4. Try to undo

## ✅ Expected result

The undo button be somewhere

## ❎ Actual result

No undo button

## 📃 Other details that might be useful

Chrome@Android

I can see only native menu on long touch, the `backwards-P` toolbar has no undo/redo buttons:
![2019-02-19 14 58 34](https://user-images.githubusercontent.com/247363/53020432-28a1c400-3457-11e9-90f2-e10222f664f7.jpg)

**Comment by jodator** [comment]
I'd move the undo/redo buttons from selection toolbar to the block toolbar which is always visible

**Comment by Reinmar** [comment]
It may be a good idea. But... then we violate the "block" thing in "block toolbar" cause undo/redo are just generic buttons.

It's also a part of bigger issue with contentEditable that we cannot listen to the native undo/redo: https://github.com/w3c/editing/issues/150

**Comment by Reinmar** [comment]
cc @oleq @dkonopka

**Comment by oleq** [comment]
It does not feel like a big issue to me moving those buttons to the block toolbar. Sooner or later other buttons not quite related to block will need to land there, like, for instance, track changes controls.

**Comment by pomek** [comment]
A serious question - do I need a device with Android to reproduce this issue?

**Comment by Reinmar** [comment]
I think the same issue is reproducible on iOS. The only requirement is the lack of hardware keyboard.
