### ISSUE TITLE
Upcasting a custom HTML element to text trims an adjacent white space if present

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#15435]
## 📝 Provide detailed reproduction steps (if any)

Our software supports “BBCodes” as a way to add additional functionality to messages without requiring a tighter integration into the editor. These BBCodes are parsed on the server-side and converted into the custom HTML element `<woltlab-metacode data-name="…" data-attributes="…">`.

The opposite happens inside the editor, these custom elements are upcasted into regular text, for example `[foobar='abc'][/foobar]`.

There are actual two types of BBCodes, the first one acts as a block wrapper can consume larger parts of HTML. The second type are “inline“ BBCodes which are also the ones that cause issues. The upcast process appears to strip away one whitespaces that follows such an inline BBCode.

My initial instinct was to check the shifting of the model cursor because I suspected I was being stupid and accidentally consumed more from the source than I should (classic “off by one” issue). However, upon further inspection I could prove that this is not what is happening because inserting any other character after the closing tag does not trigger this problem.

You can find the standalone plugin in full at https://github.com/WoltLab/editor/blob/d294a96e69584a1fe22629d967dacc5e7dcd00ec/plugins/ckeditor5-woltlab-metacode/src/woltlabmetacode.ts

Use this HTML to reproduce the issue:

```html
<p>left <woltlab-metacode data-name="email" data-attributes="WyJ0ZXN0QGV4YW1wbGUuY29tIl0="></woltlab-metacode> right</p>
<p>left <woltlab-metacode data-name="email" data-attributes="WyJ0ZXN0QGV4YW1wbGUuY29tIl0="></woltlab-metacode>.right</p>
```

These two lines are identical except for one difference: The first line has a single space (0x20) between the closing tag and the word “right”. The second line has a period (0x2E) between the closing tag and the word “right”.

### ✔️ Expected result

The whitespace following the closing tag `</woltlab-metacode>` should be preserved.

### ❌ Actual result

If there is an adjacent whitespace after the closing tag `</woltlab-metacode` then it is removed. However, this does not happen when there is any other character at this position.

## 📃 Other details

* Browser: Not browser dependent
* OS: Not OS dependent
* First affected CKEditor version: v39, possibly earlier versions are affected to. Can be reproduced in v40.1.0
* Installed CKEditor plugins: Custom plugins for upcasting of text.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dtdesign** [comment]
That sounds an awful lot like the problem I am facing but your suggestion did not work out for me. The documentation suggests that there is a default instance of the `DomConverter` which I am using to register the custom element inside the `init()` method of the plugin:

```ts
  init() {
    this.editor.editing.view.domConverter.inlineObjectElements.push(
      "woltlab-metacode",
    );

    this.#setupConversion();
  }
```

I have verified with the step debugger that the custom element is present in the array while the upcast event is running. I’ve inspected the `data` and `conversionApi` parameters to see if there is another instance of `DomConverter` present but could not locate any.

Your advice sounds to fitting that I’m unsure if I am making a mistake here. Do you by any chance have any suggestion where I could start debugging to see if it is me doing something dumb or if there is an actual issue?

**Comment by niegowski** [comment]
There is a data pipeline `DomConverter` instance in the `HtmlDataProcessor`: https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_dataprocessor_htmldataprocessor-HtmlDataProcessor.html#member-domConverter

**Comment by dtdesign** [comment]
@niegowski Thank you very much that was indeed the solution.

My first thought was to propose to add this to the documentation but I don’t think this is something that can be documented _in a meaningful way_. I’ve added the following line to my `init()` method to get it working:

```ts
this.editor.data.htmlProcessor.domConverter.inlineObjectElements.push(
  "woltlab-metacode",
);
```

**Comment by Witoso** [comment]
Adding a how-to label to keep track of this.
