### ISSUE TITLE
Undo does not work in the CKEditor5 editor window in Source mode

### ISSUE THREAD

**Issue by jayeshlimaye** [ckeditor/ckeditor5#15449]
## 📝 Provide detailed reproduction steps (if any)

1. Open a CKEditor5 editor.
2. Click on Source tool in the toolbar.
3. Type anything inside the editor.
4. Click Ctrl-Z to undo.

### ✔️ Expected result

The typed content should get removed.

### ❌ Actual result

Nothing happens.

## 📃 Other details

* Browser: Google Chrome Version 119.0.6045.200 (Official Build) (64-bit)
* OS: Windows 11 Pro Version 10.0.22000.2538
* First affected CKEditor version: 5
* Installed CKEditor plugins: NA

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Duplicate: #13700.
