### ISSUE TITLE
Build folder naming used for distribution files

### ISSUE THREAD

**Issue by slejnej** [ckeditor/ckeditor5#15456]
## 📝 Ask a question

_There is a `js/build` folder that is misleading. Shouldn't this be renamed to `dist`?_

Build folders are used for something that can be done on every deployment of the code. Shouldn't files that are the same (related to a version) be inside `dist` folder?
Any deployment "best practice" has defined that should build "all that can be built" on the fly. Buiding this module is just to "hungry" to do during the deployment and not modify "the standard" of not pushing `build` folders to server.

**Comment by Witoso** [comment]
> Any deployment "best practice" has defined that should build "all that can be built" on the fly.

I don't know if I would call it a best practice, or maybe I don't fully understand your wording. But that's true, the `dist` is much more popular in the distribution of packages, and we actually plan to migrate to it quite soon.

The `build` folder right now keeps a quite advanced setup of [DLLs](http://192.168.1.188:8082/ckeditor5/40.1.0/installation/advanced/alternative-setups/dll-builds.html). Usually, we recommend using the source code (`src`) to create your own build pipeline. That's said, this will be replaced by something new, and it will be announced next week! :)
