### ISSUE TITLE
Paste image copied from another web page doesn't upload?

### ISSUE THREAD

**Issue by michalrus** [ckeditor/ckeditor5#15454]
### Reproduction:

1. When I right click any image on any web page, and select "Copy Image",
2. and go to CKEditor 5, and press Ctrl+V,
3. the image is not uploaded, but instead the pasted HTML snippet **references the original image URL**.

On the other hand, when I copy an image to clipboard from, say, GIMP, or make a screenshot, it is uploaded on Ctrl+V.

### Question:

How to make CKEditor 5 upload these images copied within a web browser to my server? I wouldn’t want to break my docs, in case those URLs go offline in the future.

**Comment by Witoso** [comment]
Hi! For now, we only allow so called hotlinking, there's a PR waiting for us from the community. Read the #5152 for more details.

**Comment by michalrus** [comment]
Great, I’ll try that branch out, thank you 🙇
