### ISSUE TITLE
The balloon block editor is hard to find without content.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1545]
Dunno if an issue per se but the editor without the content is not present:

![2019-02-19 14 51 01](https://user-images.githubusercontent.com/247363/53020941-589d9700-3458-11e9-8118-cf656ec46423.jpg)

**Comment by Reinmar** [comment]
Doesn't it apply to all inline editors?

**Comment by jodator** [comment]
@Reinmar the inline editor sample has borders around editable areas so you see where you can type:
![selection_202](https://user-images.githubusercontent.com/247363/53087875-7aeeed80-3508-11e9-920a-5835ba7651d1.png)

ps.: the same is for balloon editor sample

**Comment by Reinmar** [comment]
So I think this is a problem with the docs only? We cannot propose any default styling for the editable ourselves. Or can we? Would people want to kill us? :D cc @oleq

**Comment by oleq** [comment]
Nah, we shouldn't style anything by default. But we can make our docs better by giving editors some bg/outline.
