### ISSUE TITLE
Custom isolated buttons that triggers the default toolbar features of the ckeditor container that gets rendered.

### ISSUE THREAD

**Issue by jasmeet2021** [ckeditor/ckeditor5#15462]
## description of the task

Given that I am using a custom build via online builder, I want to have a  separate isolated buttons say Paragraph, quotes, table which when interacted i.e. clicked on triggers the corresponding paragraph, quotes ,table in the default toolbar of the ckeditor container and we need to do this on a single page where both the isolated buttons & ckeditor container will render how can this be achieved in Nextjs13 with the custom build setup that I already have via online builder.

**Comment by jasmeet2021** [comment]
✅ The way to achieve the above is to use the exposed api via the Editor instance for example for paragraph reff: https://ckeditor.com/docs/ckeditor5/latest/api/module_paragraph_paragraph-Paragraph.html#member-editor 

🪜 laying down steps for future dev's to achieve the same below :) !

**Follow these steps to create a isolated paragraph button which when clicked on triggers the toolbar paragraph in the ckeditor container rendered on the page in Nextjs13 with custom ckeditor5 build via online builder:**

1. In your custom-editor.tsx file component in nextjs13 , you need to grab & lift the state up for editor instance to a shared parent component and pass it down to the CustomEditor component. 

```
'use client';

import React from 'react';
import { CKEditor } from "@ckeditor/ckeditor5-react";
import Editor from "ckeditor5-custom-build";


export function CustomEditor( {initialData,onEditorChange}: any ) {
        return (
            <CKEditor
                editor={ Editor }
                data={ initialData }
                onChange={ (event, editor ) => {
                    const data = editor.getData();
                    console.log( { event, editor, data } );
                    onEditorChange(editor); // passing the editor instance
                } }
            />
        )
}

export default CustomEditor;
```

2. Now in parent component where the CustomEditor is used the editor state can be managed and also passed down to other components in a similar fashion.

```
// pages/index.js
import React, { useState } from 'react';
import CustomEditor from '../components/CustomEditor';
import AnotherComponent from '../components/AnotherComponent';
import Editor from "ckeditor5-custom-build";
import { Button } from '@mui/material';

function Home() {
  const [editorInstance, setEditorInstance] = useState<Editor|null>(null);
  
  const handleEditorChange = (editor) => {
    setEditorInstance(editor);
  };
  
  function handleParagraphClick() {
        if (!editorInstance) return;
        console.log(editorInstance);
        // Use CKEditor Instace API to insert paragraph
        editorInstance?.execute('paragraph');
   };

  return (
    <div>
       <Button onClick={handleParagraphClick} >Paragraph</Button>
      <CustomEditor initialData="<p>Hello CKEditor!</p>" onEditorChange={handleEditorChange} />
      <AnotherComponent editor={editorInstance} />
    </div>
  );
}

export default Home;
```

**NOTE- Their is a small caveat though in order to enable the triggers and get access to that editor instance in parent component , their shud be at least an interaction with the actual ckeditor container of the CustomEditor.tsx file which in turn will populate the editor instance and then that state gets passed on & lifted up to the parent component to be used as per the requirements.**

**Comment by Witoso** [comment]
I am not sure if that was the goal, but we have this [headless demo](https://ckeditor.com/ckeditor-5/demo/headless/), and the [example codebase](https://github.com/ckeditor/ckeditor5-demos/tree/master/headless).

**Comment by jasmeet2021** [comment]
this was a good share will keep in mind for future reff, though the goal is not the same.
