### ISSUE TITLE
Selection is moved out of a table when touching/clicking in table cell with an image

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1546]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. create a table
2. insert image
3. optionally align image to left/rigth
4. click in the table cell with an image

## ✅ Expected result

The selection is put in table cell before (or after) an image

## ❎ Actual result

The selection is moved to first element in root

## 📃 Other details that might be useful

- Chrome on Android
- Chrome on Ubuntu
- Firefox on Ubuntu - the selection is set in right place (you can type in table cell) but is not rendered/visible

**Comment by f1ames** [comment]
I have noticed very similar / same behaviour, when trying to focus table cell with widget:

**Firefox**:
![ff issue1](https://user-images.githubusercontent.com/1061942/53030843-f5b5fb00-346b-11e9-9750-dd3d36827102.gif)

In Firefox selection jumps between table cell with widget and cell after using mouse click on cell with widget.

**Chrome**:
![chrome issue1](https://user-images.githubusercontent.com/1061942/53030858-f9e21880-346b-11e9-83b5-97f283ff4c12.gif)

On Chrome selection moves to the first root element and @jodator described.

**Comment by Reinmar** [comment]
Needs https://github.com/ckeditor/ckeditor5/issues/407

**Comment by jodator** [comment]
@Reinmar but the problem is that selection is not set inside the table cell and I suspect some bug there. If you click other table cell with text only you can set the selection in there by clicking on table cell.

**Comment by jodator** [comment]
![peek 2019-02-20 12-06](https://user-images.githubusercontent.com/247363/53087686-0451f000-3508-11e9-82f1-fffcb37eb807.gif)

**Comment by Reinmar** [comment]
Are  there any paragraphs where it can be set? Or just this media?

**Comment by jodator** [comment]
Only media.
