### ISSUE TITLE
CKEditor 5 Input Issues on Android 7 - Lack of 'beforeinput' event support?

### ISSUE THREAD

**Issue by wangzhenzhen111** [ckeditor/ckeditor5#15463]
## 📝 Provide detailed reproduction steps (if any)

can't input on android7 chrome55

While conducting my investigation, I have observed that this issue arises seemingly due to the browser's lack of support for the 'beforeinput' event, which CKEditor5 heavily relies upon for handling user input.

I understand that CKEditor5 has some form of fallback mechanism for browsers that don't support the 'beforeinput' event. Yet, it appears that this fallback approach isn't working properly in Android 7's default setup, causing users to be unable to enter any text.

Can we confirm whether CKEditor5 has compatibilities for browsers/devices that do not support 'beforeinput' events, and if so, why such a mechanism is not executing its function properly when operating under Android 7?

Any information or assistance surrounding this issue would be greatly appreciated. Thank you very much for your time and help in this matter.

## 📃 Other details

* Browser: chrome55
* OS: android 7
* First affected CKEditor version: 39.2.1
* Installed CKEditor plugins: @ckeditor/ckeditor5-editor-inline ，@ckeditor/ckeditor5-essentials，@ckeditor/ckeditor5-paragraph

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Unfortunately, we won't be able to help you here. We [support the latest browsers,](https://ckeditor.com/docs/ckeditor5/latest/support/browser-compatibility.html) and backward compatibility to versions from 2016 would be too costly for us. If you need to make it work, I recommend checking versions pre-`beforeInput` migration (`35.4` if I recall correctly).
