### ISSUE TITLE
Provide support for <tfoot> in tables

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#15489]
## 📝 Provide a description of the new feature

CKEditor 5 does not support the [standard HTML5 tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot) `<tfoot>`, yet.

Observed this in practice, and the [tests (here 40.1.0)](https://github.com/ckeditor/ckeditor5/blob/v40.1.0/packages/ckeditor5-table/tests/converters/upcasttable.js) seem to second that (`<tfoot>`) is just removed.

Comments in #3162 seem to denote, that there was some reason, not to support `<tfoot>`.

Please, if possible, add support for `<tfoot>`. Naive suggestion would be similar to heading support, that is encoded as attribute `headingRows` in model. Wouldn't `footerRows` be a feasible addition to that?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Duplicate in #12952, we have a community PR there we will take a look at, but it doesn't contain UI. Anyway, this would still be a first step to at least preserve it in a proper place.

**Comment by joejoseph00** [comment]
There's a pull request that was generously created by the Government of Ontario (while it is a province the Ontario government is larger, richer and more powerful than most european countries) https://github.com/ckeditor/ckeditor5/pull/14276
