### ISSUE TITLE
Cannot type over inline widget on Android

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1548]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 📋 Steps to reproduce

1. Go to the inline widget manual test
2. Touch the inline widget (place selection over it)
3. Type

## ✅ Expected result

The typed characters appears in the editor in place of the selected inline widget.

## ❎ Actual result

Can't type this... (the text does not appear)

## 📃 Other details that might be useful

- happens randomly
     - I was able to type over inline widget in some scenarios (ie when freshly inserted into the table cell and still selected).
    - sometimes the typed content appears on the end of a parent block (ie editing root or table cell)

**Comment by Mgsy** [comment]
This issue is fixed.
