### ISSUE TITLE
CKEditor automatically adds a dot in specific scenario (every browser seems to be affected)

### ISSUE THREAD

**Issue by cadeyrn** [ckeditor/ckeditor5#15499]
## 📝 Provide detailed reproduction steps (if any)

When typing code, the CKEditor 5 automatically adds a dot in specific scenario. I can neither reproduce in the CKEditor 4 nor in TinyMCE.

1. Press the button for a code block
2. Enter `.foo {`
3. Press two times the `Enter` key
4. Enter `}`
5. Press the `arrow up` key
6. Press two times the `space` key

The same can be reproduced without code block. Then you have to make sure that you use line breaks instead of paragraphs, so slightly different STR:

1. Enter `.foo {`
2. Press two times the `Shift` + `Enter` combination
3. Enter `}`
4. Press the `arrow up` key
5. Press two times the `space` key

### ✔️ Expected result

Just two spaces in the current line.

### ❌ Actual result

A dot in the current line.

Screencast: https://www.youtube.com/watch?v=gJgWYMN_2bY

## 📃 Other details

* Browser: Reproduced in Firefox 120, Chrome 120 and Safari 17.1.2
* OS: macOS 14.1.2
* First affected CKEditor version: unknown, but reproducible in the demo on https://ckeditor.com/ckeditor-5/demo/feature-rich/
* Installed CKEditor plugins: unknown, but reproducible in the demo on https://ckeditor.com/ckeditor-5/demo/feature-rich/

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! This is a feature of your macOS, [check the web how to disable it](https://www.google.com/search?q=period+with+double+space+mac&sca_esv=589720406&ei=2cZ2ZZT3D-SExc8PqIWJ-A8&ved=0ahUKEwjUx8Kd-oaDAxVkQvEDHahCAv8Q4dUDCBA&uact=5&oq=period+with+double+space+mac&gs_lp=Egxnd3Mtd2l6LXNlcnAiHHBlcmlvZCB3aXRoIGRvdWJsZSBzcGFjZSBtYWMyBhAAGAUYHjILEAAYgAQYigUYhgMyCxAAGIAEGIoFGIYDMgsQABiABBiKBRiGA0ixC1DBBFjlCXABeAGQAQCYAXOgAecDqgEDMi4zuAEDyAEA-AEBwgIKEAAYRxjWBBiwA8ICCBAAGAgYBxgewgIIEAAYBRgHGB7CAggQABgIGB4YDeIDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp).
