### ISSUE TITLE
The custom UI (Bootstrap) example is broken

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1549]
1. Visit https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/framework/custom-ui.html
2. It's dead :D

Most likely due to changes in EditableUIView API in this iteration https://github.com/ckeditor/ckeditor5-ui/pull/463.

**Comment by dkonopka** [comment]
Remember about broken sample here too: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/deep-dive/ui/external-ui.html
