### ISSUE TITLE
How to make only the ckeditor container scrollable when the content inside it grows instead of having the scroll on the entire page.

### ISSUE THREAD

**Issue by jasmeet2021** [ckeditor/ckeditor5#15500]
## 📝 Ask a question

Given that I am using a custom build from online builder, How can one make the ckeditor container scrollable when the content inside it grows? instead of having the scroll applied on the entire page.

**Comment by flaviubln** [comment]
You should have a class something like this `class="ck ck-content ck-editor__editable`. Add to this in css 'overflow-y: scroll'

**Comment by Witoso** [comment]
Check this: [How to set the height of CKEditor 5?](https://ckeditor.com/docs/ckeditor5/latest/examples/how-tos.html#how-to-set-the-height-of-ckeditor-5)

**Comment by jasmeet2021** [comment]
Thanks guyz @flaviubln  @Witoso   it worked!
