### ISSUE TITLE
Remove H1/H2 from Blockquote when selected.

### ISSUE THREAD

**Issue by flaviubln** [ckeditor/ckeditor5#15507]
I am using CKEditor5 with React. I have an inline editor. What I'm trying to achieve is this

I enter a text in the editor - a `<p>text</p>` tag which is a paragraph.
Then I press the blockquote button which makes it `'<block><p>text</p></block>'`
Then I press enter and Im still inside the blockquote. And now I select from toolbar a Header (Let's say H1).
Now I want the styling to be reset. So the H1 tag is outside the blockquote.
Practically, I want to disable the possibility of having H1 tags inside a blockquote.
I've succeeded in disabling the blockquote button from toolbar when the H1 tag is selected, but if Im doing the steps above I can actually make a H1 a blockquote

If you have any idea, please do suggest me a solution. 
Thank you

**Comment by Witoso** [comment]
Hello! Please look at the API of schema: [**`addChildCheck`**](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html#function-addChildCheck). This is the best method to disable the headings in a block quote.

**Comment by flaviubln** [comment]
Works just fine
