### ISSUE TITLE
Cannot type after image/media in table [Android]

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1552]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Open any docs with tables & Images/media
2. create table
3. insert an image or media into empty table cell
4. try to put selection after the image

## ✅ Expected result

I can type after an image

## ❎ Actual result

I'm not able to type after an image

## 📃 Other details that might be useful

- probably this is an issue with fake selection as when cursor is moved over the widget the cursor disappears.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/407
