### ISSUE TITLE
How can I use CDN to add a plugin into ckeditor editor.

### ISSUE THREAD

**Issue by sachinkumar121** [ckeditor/ckeditor5#15529]
## 📝 Ask a question

I am using CDN to set up CKEditor on my HTML pages. Now I want to add the `specialCharacters` plugin into the editor, but I didn't find the correct way to add a plugin into the editor. 

Can someone tell me how can I use special characters or any plugin that imports using CDN and uses it in the editor?

**Comment by Witoso** [comment]
CDN (or so called [predefined builds](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html)) are not extensible, you need to create [a custom build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html) to add the plugins.

We are working on changing our approach to installations in: #15502.
