### ISSUE TITLE
Unable to remove an image placed inside of an editable field in restricted editing mode

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15521]
## 📝 Provide detailed reproduction steps (if any)

1. Create some content in which you specify editable and non-editable areas via restricted editing
2. Enable the `'insertImage'` and/or `'uploadImage'` commands in `restrictedEditing`
3. Turn on restricted editing mode
4. Place the caret at the beginning or end of the editable field
5. Insert an inline image in this position
6. Try removing the image once it's inserted

### ✔️ Expected result

You should be able to remove the image, as is the case when it's inserted somewhere in the middle of the editable field:

https://github.com/ckeditor/ckeditor5/assets/72079603/9da9b4ff-d717-4eb4-9b4a-b79f91c9e805

### ❌ Actual result

If the caret is at the beginning or end of the editable field, the image cannot be removed:

https://github.com/ckeditor/ckeditor5/assets/72079603/7526efbc-da7b-4c4c-ac7a-fa5906f841bc

### ❓ Possible solution

When the caret is placed at the beginning or end of the editable field, the image gets inserted outside of the `span` with the `restricted-editing-exception` class. In this case, the markup can look like this:

```
<p>Non-editable</p><p><picture><source srcset="https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/ZD-j86KZtZQ8/images/80.webp 80w,https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/ZD-j86KZtZQ8/images/160.webp 160w,https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/ZD-j86KZtZQ8/images/240.webp 240w,https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/ZD-j86KZtZQ8/images/256.webp 256w" sizes="(max-width: 256px) 100vw, 256px" type="image/webp"><img data-ckbox-resource-id="ZD-j86KZtZQ8" src="https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/ZD-j86KZtZQ8/images/256.png" width="256" height="256"></picture><span class="restricted-editing-exception">Editable content here</span></p><p>Non-editable</p>
```

When the caret is placed somewhere in the middle of the editable field, the image is placed inside of the span and the markup can look like this:

```
<p>Non-editable</p><p><span class="restricted-editing-exception">Editable content&nbsp;</span><picture><source srcset="https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/5wtlAcRPSgai/images/80.webp 80w,https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/5wtlAcRPSgai/images/160.webp 160w,https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/5wtlAcRPSgai/images/240.webp 240w,https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/5wtlAcRPSgai/images/256.webp 256w" sizes="(max-width: 256px) 100vw, 256px" type="image/webp"><img data-ckbox-resource-id="5wtlAcRPSgai" src="https://ckbox.cloud/4NCAhHInx1m9uHJjNYDz/assets/5wtlAcRPSgai/images/256.png" width="256" height="256"></picture><span class="restricted-editing-exception">here</span></p><p>Non-editable</p>
```

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by stevenrai** [comment]
Do we have any updates or work arounds for this? its a critical issue for people trying to insert images to restricted documents. It essentially breaks the document if someone inserts an image (beacuse they can't remove or do anything with it)
