### ISSUE TITLE
Ckeditor5 table properties center alignment do not work

### ISSUE THREAD

**Issue by Sumit7991** [ckeditor/ckeditor5#15535]
## 📝 Provide detailed reproduction steps (if any)

1. Add a table in ckeditor5 editor.
2. Choose center alignment in table properties.
3. View the generated content outside of editor.

### ✔️ Expected result
The table should be centered on the page.
### ❌ Actual result
The table is shown left aligned due to lack of appropriate style properties. (As implemented in #9555)
Inside editor:
![image](https://github.com/ckeditor/ckeditor5/assets/25252393/dd959e94-7f3c-4c11-8fcd-560e884cbd5b)
On page:
![image](https://github.com/ckeditor/ckeditor5/assets/25252393/b5552102-8cfa-4792-bcba-39bc13733699)

### ❓ Possible solution
To implement below suggestions from [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table) instead of using CSS float property.

> Set _margin-left_ and _margin-right_ to achieve an effect that is similar to the align attribute:
> 
> left: margin-right: auto; margin-left: 0;
> center: margin-right: auto; margin-left: auto;
> right: margin-right: 0; margin-left: auto;

## 📃 Other details

* Browser: Google Chrome
* OS: Windows 11
* First affected CKEditor version: 39.0.1(with drupal 10.1.6)
* Installed CKEditor plugins: Table

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@Sumit7991 I suggest to create (or find issue) on the Drupal side. Everything works on the CKEditor 5 side, and it's unlikely we will change our implementation right now.

**Comment by jaydip89051** [comment]
Hello @Witoso ,
For my perspective it is an important miss from ckeditor5. Because if we don't specify any styling within a tag, browser will render the table left aligned as mentioned in issue description. For my case I am working on headless site where to fix this, I might need to write custom plugin as I can not handle table alignment with custom CSS(everything must be part of ckeditor5 generated html). This feels like a downgrade as it was working as expected in ckeditor4.
Better to use recommended way to align the table,

```
left: margin-right: auto; margin-left: 0;
center: margin-right: auto; margin-left: auto;
right: margin-right: 0; margin-left: auto;
```
Seems center alignment of table is not handled in ckeditor5 library which was part of ckeditor4.

I would very much like to fix this in ckeditor5 library.

**Comment by nitesh-voya** [comment]
It works fine within the editor but when render in browser its not

**Comment by zalaksanghani1** [comment]
is there any way to change behavior of alignment 

here i want to align using below css.

left: margin-right: auto; margin-left: 0;
center: margin-right: auto; margin-left: auto;
right: margin-right: 0; margin-left: auto;

**Comment by Reinmar** [comment]
Just in case, we extended recently the table alignment options:

<img width="1187" height="815" alt="Image" src="https://github.com/user-attachments/assets/183e76af-3f1c-4cb6-be5f-3723a20996e4" />

* There are now 5 options.
* Hence, it's possible to replicate CKEditor 4's configuration where a new table was aligned to left (without being wrapped by text). 

In v47 these are shipped as experimental options. They'll land as defaults in v48 (next month).

Here's a snippet how to turn them in v47: https://github.com/ckeditor/cke4-to-cke5/commit/0ebdbee183ecb190ce14f0481929540af95e38bd

And more info in https://github.com/ckeditor/ckeditor5/issues/6174#issuecomment-3627200119

**Comment by nitesh-voya** [comment]
how we can enable this in drupal 10
