### ISSUE TITLE
addListToDropdown causing type casting error

### ISSUE THREAD

**Issue by dchun** [ckeditor/ckeditor5#15533]
I'm using the most recent version of ckeditor5 40.2.0 on a classic build. When I try to compile after adding a dropdown component, I get the following error:

```
        TS2345: Argument of type 'Collection<Record<string, any>>' is not assignable to parameter of type 'Collection<ListDropdownItemDefinition> | (() => Collection<ListDropdownItemDefinition>)'.
  Type 'Collection<Record<string, any>>' is not assignable to type 'Collection<ListDropdownItemDefinition>'.
    Type 'Record<string, any>' is not assignable to type 'ListDropdownItemDefinition'.
      Type 'Record<string, any>' is missing the following properties from type 'ListDropdownGroupDefinition': type, label, items
```

I'm using the example found in the code here: https://github.com/ckeditor/ckeditor5/blob/851d4b37e6752a86087b7e82340fe4e0031c88b2/packages/ckeditor5-ui/src/dropdown/utils.ts#L262

```typescript
  const items = new Collection();
 
  items.add( {
  	type: 'button',
  	model: new Model( {
  		withText: true,
  		label: 'First item',
  		labelStyle: 'color: red'
  	} )
  } );
 
  items.add( {
  	 type: 'button',
  	 model: new Model( {
  		withText: true,
  		label: 'Second item',
  		labelStyle: 'color: green',
  		class: 'foo'
  	} )
  } );
 
  const dropdown = createDropdown( locale );
 
  addListToDropdown( dropdown, items );
```

Are there any quick fixes to this problem?

**Comment by arkflpc** [comment]
Hi @dchun.

Thanks for noticing this.

It seems like we missed this example when we were porting CKEditor 5 from JavaScript to TypeScript. The fix is quick and easy, just don't let the compiler infer `items` type to be more general than accepted by `addListToDropdown`.

```ts
const items = new Collection<ListDropdownItemDefinition>();

// ...
```

I hope it will work for you, but don't close this ticket yet. I'll create a PR to fix the example.
