### ISSUE TITLE
Can't install Plugins using MacOS 14

### ISSUE THREAD

**Issue by giob135** [ckeditor/ckeditor5#15534]
I am no coder although a little tech savvy and don't mind getting my hands dirty a little. I have just downloaded Homebridge and followed all the steps to the letter on the Hombridge Wiki page. I then tried to install my first Plugin, however every time I try I get the following message 

[12/14/2023, 5:07:45 PM] [Homebridge UI] Running Command: npm install -g homebridge-ewelink@12.0.0
[12/14/2023, 5:07:45 PM] [Homebridge UI] Operation failed. Please review log for details.

So then I tried to install ANY plugin but It doesn't matter what I try to install I get the same error. What am I doing wrong? 

I am running MacOS 14, Homebridge version 1.7, NodeJs version 20.9

**Comment by Witoso** [comment]
Hi! This is a wrong repo for this issue, try using the [https://github.com/homebridge/homebridge](https://github.com/homebridge/homebridge) :)

**Comment by giob135** [comment]
Hi … sorry i went to the link below and I can’t find a place to post my question. Can you tell me where I can do that? I created new correspondence but it took me to a coding site which I don’t think is what i need. I also don’t think I need to create a new repository. I did search this site for any information on my issue but couldn’t find anything relating to MacOS. Appreciate your help.

**Comment by Witoso** [comment]
Create an issue in the repo: https://github.com/homebridge/homebridge/issues
