### ISSUE TITLE
The image upload icon is too high

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#15549]
Since 41.2.0 it looks like this:

![](https://github.com/ckeditor/ckeditor5/assets/156149/c5eb34e3-f2b1-4f47-b510-8cd307a8c42f)

In 40.0.0 it looked like this:

![](https://github.com/ckeditor/ckeditor5/assets/156149/34c92199-6e4a-484d-9baf-15a297a903fd)

The top of the image was aligned to the top of the table.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
BTW, something that I didn't notice in the past, but we also have some issues with vertical alignment here:

![](https://github.com/ckeditor/ckeditor5/assets/156149/2e75bd99-2007-428e-b37a-3e702210d818)

It's definitely less important to me than the main icon. And probably really tricky to get right in case of this specific toolbar :(.

**Comment by dagdzi** [comment]
I improved alignment of the following icons: 

- image edit
- image asset manager
- image url
- media
- object size
- table
- text alternative

You can see icons preview on the screenshot, and the improved icons can be found in the attached package.

[improved-icons.zip](https://github.com/ckeditor/ckeditor5/files/13754373/improved-icons.zip)

<img width="1146" alt="improved-alignment" src="https://github.com/ckeditor/ckeditor5/assets/135701960/8b2980c7-86c6-4fb5-ba1d-238dd511ac84">

CC @Witoso

**Comment by Witoso** [comment]
Thanks! Looks great!

**Comment by pszczesniak** [comment]
Hi @dagdzi :wave: 

Could you take a look at the `image-url.svg` ? The height of the image is lower than in the others.

Below two screens to compare:

From manual test:

![](https://github.com/ckeditor/ckeditor5/assets/7074833/3b2b36b5-6427-4432-827c-5bb8d482a86a)

From your comment but i've zoomed it:

![](https://github.com/ckeditor/ckeditor5/assets/7074833/875d257b-4809-49c4-97cb-ec7ca36344fb)

All other icons are looking great :+1:

**Comment by dagdzi** [comment]
@pszczesniak 

Thanks for catching that!

I've noticed that edit icon also had the same issues, so I improved both of them. Hope that now the whole package is ok. 

![image-url](https://github.com/ckeditor/ckeditor5/assets/135701960/fbd738bc-810c-496e-baf5-9083ec9bc76f)
![ckbox-image-edit](https://github.com/ckeditor/ckeditor5/assets/135701960/535bcb63-6304-4055-8093-d007d4abd279)

[edit-url-icons-improved.zip](https://github.com/ckeditor/ckeditor5/files/13820440/edit-url-icons-improved.zip)
