### ISSUE TITLE
Docs issue report from "api/module_engine_model_operation_splitoperation-SplitOperation.html"

### ISSUE THREAD

**Issue by jonmenard** [ckeditor/ckeditor5#15543]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_operation_splitoperation-SplitOperation.html

### Project version

40.2.0

### Is there anything else you would like to add?

We are using CKEditor5 from drupal 10.1.6 Core. There is no way to disable split operation. 

We have many instances where a <br> is defined within an inline elemnt such as 

    <a  href="#" target="_blank">First Line<br> Second Line</a>
    
   however the editor auto formats this to:
       <a  href="#" target="_blank">First Line</a><br>
       <a  href="#" target="_blank"> Second Line</a>

which is incorrect. There should be an option to disable this auto formating

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Hi, thanks for the report. See: #1068.
