### ISSUE TITLE
Separate configuration for styles in `ol` and `ul` list properties

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15554]
## 📝 Provide a description of the improvement

Add a possibility to configure the styles of list properties separately. For example, allow content editors to choose for list of styles for `ol` but not for `ul`'s. Currently, [the configuration affects both](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists-installation.html#list-properties).

[Requested by Drupal](https://www.drupal.org/project/drupal/issues/3274635#comment-15340172).

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by bkosborne** [comment]
Yes! This would be great. The "type" attribute on unordered lists is deprecated and we don't want our users to use it, but we _do_ want them to use the attribute on ordered lists, where it has semantic meaning. This is one of the remaining blockers for us to upgrade ~1000 sites to CKEditor 5.

**Comment by wimleers** [comment]
One crucial part of information is missing from this issue: this is a **hard blocker** for `Drupal` to adopt the native `<ol type>` and `<ul type>` functionality over at https://www.drupal.org/project/drupal/issues/3274635

@Witoso This seems so bafflingly trivial to add … can you perhaps point to some prior art so that @bkosborne can contribute the changes himself?

**Comment by Witoso** [comment]
While I understand the impact, I wouldn't judge this as trivial (maybe in LoCs). We need to create a non-breaking API change in one of the most used features. As of now, I don't have manpower to push this, but I will try to add it as a subissue to a current larger initiative.

AFAICS, it was ecosystem's decision to block this based on the non-separate config, as the `type` feature is provided by CKE5. Perhaps you could change the decision you made based on the feedback you got?

I'm also not sure where I could point, tactical cc to @arkflpc as I think you participated in the implementation.

**Comment by Witoso** [comment]
Ok, let's discuss it, and I will ping you @wimleers and @bkosborne.

**Comment by wimleers** [comment]
Great! Appreciate it :)

> AFAICS, it was ecosystem's decision to block this based on the non-separate config, as the type feature is provided by CKE5. Perhaps you could change the decision you made based on the feedback you got?

This is not just "a decision" as if it's subjective and could've gone either way without consequences. Without this, it's an objective fact that we'd make some use cases impossible.

> We need to create a non-breaking API change in one of the most used features. 

Not breaking BC should be trivial:
```
{ list: { properties: { styles: true } } }
```
can remain supported, just also allow:
```
{ list: { properties: { styles: ['ol', 'ul'] } } }
```
(and make that the new internal representation, just map `true` to `['ol', 'ul']` … or one of many other approaches one could think of 😄)
