### ISSUE TITLE
Docs issue report from "installation/getting-started/quick-start.html"

### ISSUE THREAD

**Issue by ShanePark** [ckeditor/ckeditor5#15557]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html#running-a-full-featured-editor-from-cdn

### Project version

40.2.0

### Is the information outdated? How?

'link', 'insertImage', 'blockQuote', 'insertTable', 'mediaEmbed', 'codeBlock', 'htmlEmbed', '|',

Looking at the docs, it says `insertImage` , but it should be `uploadImage`

### User agent

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

**Comment by godai78** [comment]
That's right, thanks for catching that. We'll have it updated today.

**Comment by godai78** [comment]
Fixed in 8c1f196
