### ISSUE TITLE
[iOS] Selection is stuck in a table

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1556]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Insert a new table.
1. Put the selection in a cell.
1. Try to move the selection to a paragraph.

## ✅ Expected result
It's possible.

## ❎ Actual result
The selection is still inside the table cell.

## 📃 Other details that might be useful
Reproducible in Safari@iOS

**Comment by Reinmar** [comment]
Is it a regression? If yes, please move it to it22.

**Comment by jodator** [comment]
> Try to move the selection to a paragraph.

How do you move the selection?

**Comment by Mgsy** [comment]
>Is it a regression?

I see that it's a regression.

>How do you move the selection?

Just by a quick tap on the paragraph, but it occurs also if you hold a finger on the text and try to put the selection at some position.

At the moment on our live docs it looks like that:
- Put the selection in a table cell
- Tap on some text
- The table is deselected
- Tap once again on the text
- You're able to change the selection

On the latest master:
- Put the selection in a table cell
- Tap on some text
- The table is deselected
- Tap once again on the text
- The selection is still in the cell

This is interesting because I'm able to reproduce it in docs in the Classic Editor example, but can't in Features/Tables sample.

**Comment by oleq** [comment]
I couldn't reproduce this issue in the Classic Editor exampole. iOS 12.1.4, native device (not a simulator).

**Comment by Mgsy** [comment]
>I couldn't reproduce this issue in the Classic Editor exampole. iOS 12.1.4, native device (not a simulator).

Funny thing, because now I'm not able to reproduce it. The behaviour is different and the selection changes immediately, so everything works as expected. Closing.
