### ISSUE TITLE
After updating to `40.x` having both `paste-from-office` and `essentials` plugins enabled throws `plugincollection-plugin-name-conflict` error

### ISSUE THREAD

**Issue by MartinL83** [ckeditor/ckeditor5#15568]
## 📝 Provide detailed reproduction steps (if any)

We encountered an error after updating all packages to `40.2.0` from `39.0.2`. The error appears in our editors and is as follows:
```
CKEditorError: plugincollection-plugin-name-conflict {"pluginName":"ClipboardPipeline"}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-plugincollection-plugin-name-conflict
```

Seems like there is a conflict between `essentials` and `paste-from-word` plugins.

We noticed that disabling the`essentials` or `paste-from-word` plugins resolves the issue. Previously, this functionality worked seamlessly without any problems. However, after the update, the mentioned error crashes the editor. We couldn't find any relevant information in the changelogs or documentation regarding changes to the clipboard in version `40.x`.

It seems that the `essentials` plugin includes the `Clipboard` plugin. Is it recommended not to include`essentials` when using `paste-from-word` and instead include the necessary plugins individually?

### ✔️ Expected result

To not have any errors thrown when upgrading

### ❌ Actual result

Name conflict error

### ❓ Possible solution

Including the specific plugins needed from `essentials` instead of relying on `essentials`. 🤷 

## 📃 Other details

I have tried to find similar issues already reported but found none.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi, thank you for your patience!

> It seems that the `essentials` plugin includes the `Clipboard` plugin. Is it recommended not to include `essentials` when using `paste-from-word` and instead include the necessary plugins individually?

If plugins require the same plugin, there shouldn't be any issue with that, the dependency mechanism will resolve it.

In version 40 we changed some workings of the `Clipboard` by introducing the drag and drop of blocks. But I cannot reproduce your specific issue. Do you have some custom plugins? What is `paste-from-word` (is it a typo? We have `ckeditor5-paste-from-office`)

**Comment by MartinL83** [comment]
> Hi, thank you for your patience!
> 
> > It seems that the `essentials` plugin includes the `Clipboard` plugin. Is it recommended not to include `essentials` when using `paste-from-word` and instead include the necessary plugins individually?
> 
> If plugins require the same plugin, there shouldn't be any issue with that, the dependency mechanism will resolve it.
> 
> In version 40 we changed some workings of the `Clipboard` by introducing the drag and drop of blocks. But I cannot reproduce your specific issue. Do you have some custom plugins? What is `paste-from-word` (is it a typo? We have `ckeditor5-paste-from-office`)

Sorry for late reply @Witoso , holidays :) 
Yes sorry my bad, its a typo `ckeditor5-paste-from-office` is correct.

We do have custom plugins. But nothing really touching `ckeditor5-paste-from-office` (other than importing it as a plugin) or `ClipboardPipeline`. Let me try to dig some more now when im back at work.

**Comment by MartinL83** [comment]
I see that your `ckeditor5-paste-from-office` requires `ClipboardPipeline` from `ckeditor5/src/clipboard`. And `essentials` requires `Clipboard` from  `ckeditor5/src/clipboard`. 

Could this be a problem? 🤔

**Comment by Witoso** [comment]
Shouldn't be, `clipboard.js` is an export

[https://github.com/ckeditor/ckeditor5/blob/ec2d7059d4e8d038f880715572748c650c96c1c6/src/clipboard.ts#L10C37-L10C37](https://github.com/ckeditor/ckeditor5/blob/ec2d7059d4e8d038f880715572748c650c96c1c6/src/clipboard.ts#L10C37-L10C37)

And those are two different classes:

[https://github.com/ckeditor/ckeditor5/blob/6d9ec4202f077a5dea278351f642aa04182d7c2e/packages/ckeditor5-clipboard/src/index.ts#L10-L19](https://github.com/ckeditor/ckeditor5/blob/6d9ec4202f077a5dea278351f642aa04182d7c2e/packages/ckeditor5-clipboard/src/index.ts#L10-L19)

Could you send the full plugins list? I created a minimal sample with `Essentials` and `PasteFromOffice`, and couldn't reproduce.

**Comment by MartinL83** [comment]
These are the official plugins we use

```js
// Plugins
export { Essentials } from '@ckeditor/ckeditor5-essentials';
export { Bold, Italic, Strikethrough, Underline } from '@ckeditor/ckeditor5-basic-styles';
export { Table } from '@ckeditor/ckeditor5-table';
export { Heading } from '@ckeditor/ckeditor5-heading';
export { DocumentList } from '@ckeditor/ckeditor5-list';
export { Paragraph } from '@ckeditor/ckeditor5-paragraph';
export { Alignment } from '@ckeditor/ckeditor5-alignment';
export { PageBreak } from '@ckeditor/ckeditor5-page-break';
export { Link } from '@ckeditor/ckeditor5-link';
export { Comments } from '@ckeditor/ckeditor5-comments';
export { Autosave } from '@ckeditor/ckeditor5-autosave';
export { Mention } from '@ckeditor/ckeditor5-mention';
export { Indent, IndentBlock } from '@ckeditor/ckeditor5-indent';
export { RestrictedEditingMode } from '@ckeditor/ckeditor5-restricted-editing';
export { TrackChanges } from '@ckeditor/ckeditor5-track-changes';
export { Users } from '@ckeditor/ckeditor5-collaboration-core';
export { Notification } from '@ckeditor/ckeditor5-ui';
export { PasteFromOffice } from '@ckeditor/ckeditor5-paste-from-office';
```

**Comment by Witoso** [comment]
Thanks, what about the build process (bundler), do you use webpack, or something else? Some reproducible sample would help. Also, if you're a premium customer and want to take it off GitHub, feel free to [email us](https://ckeditor.com/contact/).

**Comment by MartinL83** [comment]
Our build setup for the editor is pretty simple. We export the plugins mentioned above, plus `DecoupledEditor` and then build it with webpack.

In our (React) application we then import this and compose together different editors using the `DecoupledEditor` and plugins exported.

Our WP config for bundling editor
```js
'use strict';

/* eslint-env node */

const path = require('path');
const webpack = require('webpack');
const { bundler, loaders } = require('@ckeditor/ckeditor5-dev-utils');
const { CKEditorTranslationsPlugin } = require('@ckeditor/ckeditor5-dev-translations');

module.exports = {
  devtool: 'source-map',
  performance: { hints: false },

  entry: path.resolve(__dirname, 'src', 'index.ts'),

  output: {
    path: path.resolve(__dirname, 'build/src'),
    filename: 'index.js',
    libraryTarget: 'umd',
  },

  plugins: [
    new CKEditorTranslationsPlugin({
      language: 'en',
    }),
    new webpack.BannerPlugin({
      banner: bundler.getLicenseBanner(),
      raw: true,
    }),
  ],

  module: {
    rules: [
      loaders.getIconsLoader({ matchExtensionOnly: true }),
      loaders.getStylesLoader({
        themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
        minify: true,
      }),
      loaders.getTypeScriptLoader(),
    ],
  },

  resolve: {
    extensions: ['.ts', '.js', '.json'],
  },
};
```

We do have a lot of other custom built plugins, and yes we are premium customers so lets see if we need to take it of GH if you need more from me.

**Comment by Witoso** [comment]
@MartinL83, please reach out to our support, we need to dig deeper into this.

**Comment by MartinL83** [comment]
Alright will do, thank you @Witoso
