### ISSUE TITLE
Update copyright headers

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1557]
Instead of:

> For licensing, see LICENSE.md.

Use:

> For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license

(just like we already do in CKEditor 4)

Reasons why:

 * When loading from a CDN there is no clear reference how to find LICENSE.md
 * At some point `ckeditor.js` will be mixed with samples, which will be distributed under a more permissive license (MIT), explained in... LICENSE.md so the lack of a reference to a CKEditor 5 license available online can cause confusion.

**Comment by pomek** [comment]
Should we change `ckeditor5-dev` repository and all integrations (React, Angular, Vue, and Inspector) as well?
