### ISSUE TITLE
Security level issue

### ISSUE THREAD

**Issue by satyavan-i2techs** [ckeditor/ckeditor5#15593]
A cross-site request forgery (CSRF) vulnerability occurs when:
1. A web application uses session cookies.

2. The application acts on an HTTP request without verifying that the request was made with the user's consent.

In this case, the application generates an HTTP request at ckeditor.js line 5.

A nonce is a cryptographic random value that is sent with a message to prevent replay attacks. If the request does not contain a nonce that proves its provenance, the code that handles the request is vulnerable to a CSRF attack (unless it does not change the state of the application). This means a web application that uses session cookies has to take special precautions to ensure that an attacker can't trick users into submitting bogus requests. Imagine a web application that allows administrators to create new accounts as follows:

<span class="code">
  var req = new XMLHttpRequest();
  req.open("POST", "/new_user", true);
  body = addToPost(body, new_username);
  body = addToPost(body, new_passwd);
  req.send(body);
</span>

An attacker might set up a malicious web site that contains the following code.

<span class="code">
  var req = new XMLHttpRequest();
  req.open("POST", "http://www.example.com/new_user", true);
  body = addToPost(body, "attacker");
  body = addToPost(body, "haha");
  req.send(body);
</span>

If an administrator for <span class="code">example.com</span> visits the malicious page while she has an active session on the site, she will unwittingly create an account for the attacker. This is a CSRF attack. It is possible because the application does not have a way to determine the provenance of the request. Any request could be a legitimate action chosen by the user or a faked action set up by an attacker. The attacker does not get to see the Web page that the bogus request generates, so the attack technique is only useful for requests that alter the state of the application.

Applications that pass the session identifier in the URL rather than as a cookie do not have CSRF problems because there is no way for the attacker to access the session identifier and include it as part of the bogus request.
CSRF is entry number five on the 2007 OWASP Top 10 list.

**Comment by Witoso** [comment]
Hi! There's nothing specific in this report, and to be honest, it looks a bit like spam.

Please report security issues according to our [security policy](https://github.com/ckeditor/ckeditor5/security/policy):

> If you believe you have found a security issue in the CKEditor software, please contact us immediately.
> 
> When reporting a suspected security problem, please bear this in mind:
> 
> *   Make sure to provide as many details as possible about the vulnerability.
> *   Please do not disclose publicly any security issues until we fix them and publish security releases.
> 
> Contact the security team at [security@cksource.com](mailto:security@cksource.com). As soon as we receive the security report, we will work promptly to confirm the issue and then to provide a security fix.
