### ISSUE TITLE
Security level issue related to math.random in ckEditor Build

### ISSUE THREAD

**Issue by satyavan-i2techs** [ckeditor/ckeditor5#15594]
I'm getting below error when test vulncheck on casa.

Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in a security-sensitive context.

In this case, the function that generates weak random numbers is <a href="event:file=fortify/6ca25115-7120-4b09-a722-c793e9646707/work/Src/CASA-2/Frontend/bixpand/ckEditorNew/build/ckeditor.js&amp;lineNo=5" rel="nofollow">random()</a> in ckeditor.js on line 5.

Computers are deterministic machines, and as such are unable to produce true randomness. Pseudorandom Number Generators (PRNGs) approximate randomness algorithmically, starting with a seed from which subsequent values are calculated.

There are two types of PRNGs: statistical and cryptographic. Statistical PRNGs provide useful statistical properties, but their output is highly predictable and form an easy to reproduce numeric stream that is unsuitable for use in cases where security depends on generated values being unpredictable. Cryptographic PRNGs address this problem by generating output that is more difficult to predict. For a value to be cryptographically secure, it must be impossible or highly improbable for an attacker to distinguish between the generated random value and a truly random value. In general, if a PRNG algorithm is not advertised as being cryptographically secure, then it is probably a statistical PRNG and should not be used in security-sensitive contexts, where its use can lead to serious vulnerabilities such as easy-to-guess temporary passwords, predictable cryptographic keys, session hijacking, and DNS spoofing.

<b>Example:</b> The following code uses a statistical PRNG to create a URL for a receipt that remains active for some period of time after a purchase.

<span class="code">
function genReceiptURL (baseURL){
  var randNum = Math.random();
  var receiptURL = baseURL + randNum + ".html";
  return receiptURL;
}
</span>

This code uses the <span class="code">Math.random()</span> function to generate "unique" identifiers for the receipt pages it generates. Since <span class="code">Math.random()</span> is a statistical PRNG, it is easy for an attacker to guess the strings it generates. Although the underlying design of the receipt system is also faulty, it would be more secure if it used a random number generator that did not produce predictable receipt identifiers, such as a cryptographic PRNG.

**Comment by Witoso** [comment]
Hi! There's nothing specific in this report, and to be honest, it looks a bit like spam.

Please report security issues according to our [security policy](https://github.com/ckeditor/ckeditor5/security/policy):

> If you believe you have found a security issue in the CKEditor software, please contact us immediately.
> 
> When reporting a suspected security problem, please bear this in mind:
> 
> *   Make sure to provide as many details as possible about the vulnerability.
> *   Please do not disclose publicly any security issues until we fix them and publish security releases.
> 
> Contact the security team at [security@cksource.com](mailto:security@cksource.com). As soon as we receive the security report, we will work promptly to confirm the issue and then to provide a security fix.
