### ISSUE TITLE
Provided I am using a custom build for ckeditor5 how can I add the feature of card previews of the link copy/pasted inside the editor.

### ISSUE THREAD

**Issue by jasmeet2021** [ckeditor/ckeditor5#15596]
## 📝 Ask a question

for instance if I pasted this https://ui.shadcn.com/ in the editor a card preview shud be their in the ckeditor rather than just a link

![image](https://github.com/ckeditor/ckeditor5/assets/92725379/3edac808-e33d-41df-83a9-cd11db153104)

i want to have this kind of card preview
![image](https://github.com/ckeditor/ckeditor5/assets/92725379/d9362e48-8d89-46c1-8756-092011b3adec)

**Comment by Witoso** [comment]
Hi! I would recommend taking a look at the [Media embed](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html), and defining an [`extraProvider`](https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembedconfig-MediaEmbedConfig.html#member-extraProviders). Keep in mind that to achieve such preview (image/description), a backend service is also needed to provide those.

**Comment by jasmeet2021** [comment]
Hello ! appreciate the prompt response buddy.

![image](https://github.com/ckeditor/ckeditor5/assets/92725379/19c04ef1-d73c-4368-9e23-ce074162bcd2)


🎈 though these videos are not playable is their some way I can make these playable also in the editor itself ?

**Comment by Witoso** [comment]
We haven't implemented it yet but it's on our radar, some workarounds are proposed in the #2743.
