### ISSUE TITLE
How to disallow changes in specific selection position (reverse restricted editing)

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#15598]
_Edit by @scofalik:_

_Below is the original issue as posted by the author. In next posts it was clarified that the author wanted to disable editing at certain selection positions. Go to_ [_https://github.com/ckeditor/ckeditor5/issues/15598#issuecomment-1884908016_](https://github.com/ckeditor/ckeditor5/issues/15598#issuecomment-1884908016) _for the possible solution._

## 📝 Provide detailed reproduction steps (if any)

```javascript
 editor.model.document.on('change:data', (e) => {
      e.stop();
  });
```

### ✔️ Expected result

Block all modifications

### ❌ Actual result

The suggestion position can still be further modified  
The suggestion card has been deleted

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
Please describe in more detail what exactly you wanted to achieve with this snippet:

```javascript
 editor.model.document.on('change:data', (e) => {
     e.stop();
 });
```

Now, I can only guess, that you wanted to prevent (cancel) all the changes that could be done to the document (model). So, kind of similar to what [readonly mode](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-enableReadOnlyMode) does.

Did you want to achieve something else? Is there something that prevents you from using the readonly mode?

**Comment by huzedong2015** [comment]
f the cursor is in certain positions, I want to block all changes made by the user.
But still modify the text at the suggestion position.

**Comment by huzedong2015** [comment]
![image](https://github.com/ckeditor/ckeditor5/assets/14806813/7d4458f8-1e4b-481c-b82e-b084fa205cd9)

**Comment by huzedong2015** [comment]
https://github.com/ckeditor/ckeditor5/assets/14806813/e55a671c-cea5-4578-abde-b9315bf9e0c8

**Comment by huzedong2015** [comment]
@scofalik Will this be fixed

**Comment by scofalik** [comment]
> If the cursor is in certain positions, I want to block all changes made by the user.

The way you are doing it is incorrect. You are blocking the event after the changes has been done to the model but before they are rendered. This is not a track changes bug -- the changes are in the model and if you would call `editor.getData()` you would get them there. You simply blocked rendering and callbacks that react to changes. `change` event effectively works as "after changes".

From what I understand, you want to do a "reverse" of our restricted editing feature, i.e., you want to block editing at specific positions. See [https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html](https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html) (switch to "Mode: Restricted").

I can advise you two things:

*   You can overwrite `canEditAt` decorated method on model. We use it in multi-root editor to allow to put certain roots in read-only mode. However, please, be advised, that we haven't tested this with your scenario. Below is an example snippet that allows editing only if selection is at the end of a paragraph:

```javascript
editor.model.on( 'canEditAt', ( evt ) => {
    const selection = editor.model.document.selection;
    const canEdit = selection.isCollapsed && selection.focus.isAtEnd;

    if ( !canEdit ) {
        evt.return = false;
    	evt.stop();
    }
}, { priority: 'highest' } );
```

*   If not that, try to get inspiration from the restricted editing plugin. It is open source, you can look at it, how exactly we block editing.

I will also change the title of this issue so other people have a chance to find this solution in case they have similar request.

**Comment by scofalik** [comment]
I edited the snippet and added note about undo.
