### ISSUE TITLE
[Edge] Can't insert a link inside a widget

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1560]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Insert a table.
1. Put the caret in a cell.
1. Try to insert a link. 

## ✅ Expected result
It's possible.

## ❎ Actual result
The selection moves to the beginning of the editor.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/53092335-c9a28480-3514-11e9-853f-6f9cf6b0a558.gif)

Might be related - https://github.com/ckeditor/ckeditor5/issues/1283. It's not a regression.

**Comment by Mgsy** [comment]
The same for a caption.

**Comment by FilipTokarski** [comment]
This bug still exists on old Edge, however it is fixed in the new upcoming version (79.0.309.56)

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
