### ISSUE TITLE
How to call the Mention panel directly without the space before?

### ISSUE THREAD

**Issue by Congb19** [ckeditor/ckeditor5#15611]
## 📝 Ask a question

How to call the Mention panel directly? As default, I have to type a space first, then type a marker(like '#'), the mention panel will appear. Or typing double marker will call it too.

I want to call the Mention panel without the space before, what should I do?

**Comment by Witoso** [comment]
Hi! This is precisely how it works [in the demo](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#demo) (space not needed). Could you share some config and a video?

Have you tried `minimumCharacters: 0`?

**Comment by Congb19** [comment]
> Hi! This is precisely how it works [in the demo](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#demo) (space not needed). Could you share some config and a video?
> 
> Have you tried `minimumCharacters: 0`?

'minimumCharacters' is not what I mean.

In this demo, if I type '@' at the beginning of the editor, it works. But if I type some charactors first before type '@', the mention list will not appear, unless a space between the charactors and the '@'.

**Comment by Congb19** [comment]
@Witoso 

Video: 
https://github.com/ckeditor/ckeditor5/assets/32233144/935a6d28-0c82-4377-9f3c-7b72d8ce1261

**Comment by Congb19** [comment]
Video here:

https://github.com/ckeditor/ckeditor5/assets/32233144/a8c89fef-9b6d-4975-9139-97b0560eb408

**Comment by Witoso** [comment]
Gotcha! Unfortunately, it won't be possible. Mention's suggestion will only be fired when there's a space between some other text and the mark. Otherwise, writing such characters in the text would be troublesome. Similar pattern appears in Slack, Google Docs, etc.

**Comment by Congb19** [comment]
> Gotcha! Unfortunately, it won't be possible. Mention's suggestion will only be fired when there's a space between some other text and the mark. Otherwise, writing such characters in the text would be troublesome. A similar pattern appears in Slack, Google Docs, etc.

thank you!

**Comment by Congb19** [comment]
> Gotcha! Unfortunately, it won't be possible. Mention's suggestion will only be fired when there's a space between some other text and the mark. Otherwise, writing such characters in the text would be troublesome. A similar pattern appears in Slack, Google Docs, etc.

Hi! In fact, there are also some patterns available in some products just like Notion, that not need to write a space before mention something. Otherwise, I agree that writing such characters would be troublesome just like you said, but only in Language based on Latin alphabet(like English, Spanish), not in other languages(Japanese, Chinese, etc)

If I still hope to fire the mention's list without a space before the marker, what can I do to redefine the trigger, or fire the list manually? 

Can you give some suggestions, thank you!

**Comment by Witoso** [comment]
Unfortunately, `Mention` plugin doesn't provide an extension point like this. Theoretically, you could write your trigger for the [mention command](https://ckeditor.com/docs/ckeditor5/latest/api/module_mention_mentioncommand-MentionCommand.html), and listen for [data changes.](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change:data)
