### ISSUE TITLE
Formatting done using CKEditor 4 is not visible in CKEditor 5

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1562]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

1. Create a content in ckeditor 4 version. Format the content like set the font as Comic Sans, Set the fone color, highlight some of the text etc
2. Save this content.
3. Open this content with ckeditor 5. The formatting done in ckeditor 4 (as mentioned in above steps) is not seen in ckeditor 5
4. If we see that content on web page, it is seen properly.

## ✅ Expected result
The content saved using the older version of ckeditor (before 5), when opened in ckeditor 5 for editing should retain the formatting

## ❎ Actual result
The below formatting which was done with ckeditor 4 is not shown when the content is opened in ckeditor 5 for editing purpose.
1. Text is not showing in correct font type.
2. The font color is not showing
3. The background color of the text used for highlighting is not showing
![ckeditor4](https://user-images.githubusercontent.com/47845224/53159024-03de5580-35eb-11e9-8e5a-528c5a625656.png)
![viewedinckeditor5](https://user-images.githubusercontent.com/47845224/53159031-0771dc80-35eb-11e9-8b96-bb12f01595b7.png)

## 📃 Other details that might be useful
We are upgrading from ckeditor 4 to 5. There are lot of content (notes) which was created using ckeditor 4. This content can be edited in our product.
We want to make sure that when our users will open this old content in ckeditor5, they should not feel that loss of formatting.

**Comment by Mgsy** [comment]
Hello, @chetan-rflx, thanks for a report. Please, be aware that CKEditor 5 has a different architecture than CKEditor 4, so the content created in CKEditor 4 will have a distinct form and might not be recognized by CKEditor 5. 

You can read more about it in our [migration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html) and consider whether CKEditor 5 is a good choice for your project.

**Comment by Reinmar** [comment]
We're planning to work on migration tools and setup for CKEditor 5 which will make the migration path from CKE4 to CKE5 smoother. But right now, @Mgsy is right that there are differences how both editors work and what kind of content they accept. Migration is possible, but require a deeper understanding of what content you have in CKEditor 4 and how it can be handled in CKEditor 5.

**Comment by moyuanhuang** [comment]
@chetan-rflx I was have the same problem where CKE4 highlight and coloring styles are dropped when mounting the html elements to CKE5. I was able to manually manipulate the elements to a CKE5 compatible format so that it can be rendered correctly.

Not really a good idea but it works if you really need it.


```ruby
module WysiwygHelper
  class << self
    COLOR_REG = /pen-(.*)/.freeze
    HIGHLIGHT_REG = /marker-(.*)/.freeze

    # Convert the highlight and color style added by CKE5 to a format that CKE4 accepts. We need
    # this step for note inline eiditing. We can remove this helper one we stop using CKE4.
    def to_cke4_compatible(text)
      fragment = Nokogiri::HTML.fragment(text)
      recursively_replace_mark_tag(fragment)
      fragment.to_s
    end

    def to_cke5_compatible(text)
      fragment = Nokogiri::HTML.fragment(text)
      recursively_recover_mark_tag(fragment)
      fragment.to_s
    end

    private

    def recursively_recover_mark_tag(fragment)
      if fragment.name == 'span'
        fragment.name = 'mark'
        return
      end

      fragment.children.each { |elem| recursively_recover_mark_tag(elem) }
    end

    def recursively_replace_mark_tag(fragment)
      if fragment.name == 'mark'
        # replace <mark></mark> with <span></span>
        fragment.name = 'span'

        # replace class="pen-color" with style="color:color"
        # replace class="marker-color" with style="background-color:color"
        color = nil
        highlight = nil
        fragment.classes.each do |c|
          color = c.match(COLOR_REG) { |m| m[1] }
          highlight = c.match(HIGHLIGHT_REG) { |m| m[1] }
        end
        fragment['style'] = "background-color:#{highlight}" if highlight
        fragment['style'] = "color:#{color}" if color

        return
      end

      fragment.children.each do |elem|
        recursively_replace_mark_tag(elem)
      end
    end
  end
end
```
