### ISSUE TITLE
The <br data-cke-filler="true"> appearance in the source build editor causes anything entered to not appear in the editor

### ISSUE THREAD

**Issue by aurora-engine-org** [ckeditor/ckeditor5#15624]
## 📝 Provide detailed reproduction steps (if any)

<template>
  <div class="fit">
    <div class="fit" id="editor"></div>
  </div>
</template>
<script setup lang="ts">

import {onMounted, onUnmounted, ref} from "vue";

import BalloonEditor from '@ckeditor/ckeditor5-editor-balloon/src/ballooneditor';
import Mention from "@ckeditor/ckeditor5-mention/src/mention";

const content = ref('message content');
const editorRef = ref()

const editorConfig = ref({
  extraPlugins: [Mention],
  toolbar: [],
  mention: {
    feeds: [
      {
        marker: '@',
        feed: ['@Barney', '@Lily', '@Marry Ann', '@Marshall', '@Robin', '@Ted'],
        minimumCharacters: 1
      }
    ]
  }
})

onMounted(() => {
  let container = document.getElementById('editor');
  BalloonEditor.create(container, editorConfig.value)
      .then(editor => {
        console.log('Editor was initialized', editor);
        // editor.execute( 'fontSize', { value: 'tiny' } );
        editor.setData('<p>message...</p>')
        editorRef.value = editor
      })
      .catch(error => {
        console.error(error.stack);
      });
})

### ✔️ Expected result

在使用其他扩展时候,希望能够正常使用编辑器

### ❌ Actual result

Enter any alphanumeric and no data appears in the editor

## 📃 Other details

In 'import BalloonEditor from '@ckeditor/ckeditor5-editor-balloon'; The way is normal, because using the extension will cause ckeditor5 to load twice
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by kkyusuftk** [comment]
Hey what was the resolution for this?
I was facing the same issue.

**Comment by Witoso** [comment]
@kkyusuftk create new issue if needed and provide some videos or reproducible sample.

**Comment by aurora-engine-org** [comment]
@kkyusuftk You should be through the source code, no import base components resulting in input can not enter anything, I was the problem, 'import {Essentials} from '@ckeditor/ckeditor5-essentials';
