### ISSUE TITLE
When setting the html using the setData method, the span tag is set to the data-ck-unsafe element attribute

### ISSUE THREAD

**Issue by huyu456** [ckeditor/ckeditor5#15636]
## 📝 Provide detailed reproduction steps (if any)

1.
![1704441579960](https://github.com/ckeditor/ckeditor5/assets/40507582/04d2502c-eab0-4810-bc7c-c0985b2e3ea1)
I use RE to replace 【】 with <span data-value="test"></span> for page presentation

### ✔️ Expected result

![1704442131369](https://github.com/ckeditor/ckeditor5/assets/40507582/f8567091-8b37-4752-8ef5-f659a5c06806)

### ❌ Actual result

When returning to the edit page, replace <span data-value="test"></span> with <span data-value="test"> 【】</span>
![1704441891854](https://github.com/ckeditor/ckeditor5/assets/40507582/d9435d49-77cc-462b-af62-54e3993ceb7f)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: chrome
* First affected CKEditor version:36.0.1 - 40.2.0

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! Please provide some reproducible samples and content, as well as your configuration.

**Comment by huyu456** [comment]
> 你好！请提供一些可重现的示例和内容，以及您的配置。

Sorry, my code does not contain additional logic for ckeditor, just plain html insertion, this error occurred during the conversion process. Now that I'm showing unsafe nodes in css, that solves my problem, so I'll close it. As to why this is a problem, it may be more complicated. If someone else encounters it, you can open the issue again. Thank you for your reply

**Comment by kglickman** [comment]
@huyu456 when you say "Now that I'm showing unsafe nodes in css" it solves your problem, what do you mean? How did you specify that.  I'm experiencing the same issue.  My content looks like this:
```
<div>
    <style type="text/css>.myclass { color: red;}</style>
    <p class='myclass'
<div>
```

My config includes:
```
htmlSupport: { allow: [{
        name: 'div',
        classes: true
    },{
        name: 'p',
        classes: true
    },{
        name: 'style',
        attributes: true,
        styles: true
    }
]}
```

The `style` tag gets changed to a `span` tag with the attribute `data-ck-unsafe-element`

**Comment by huyu456** [comment]
@kglickman I can't solve the problem from the editor level, but I have solved the problem I encountered from the business, I wonder if I can solve the problem you encountered
···css
:deep(span[data-ck-unsafe-element][data-value]) {
  display: inline !important;
}
```
![1717136210645](https://github.com/ckeditor/ckeditor5/assets/40507582/39158a7e-1f06-46b8-8a73-65c027219e0b)

**Comment by kglickman** [comment]
Thanks for your suggestions.  I really appreciate the time you took to look into it.  

Unfortunately, displaying the hidden span won't help because the whole purpose of the style tag was to avoid using inline styles.  We're removing 'unsafe-inline' from our Content-Security-Policy and are setting the nonce attribute on the style tag.

The style.html doesn't work for us, for various reasons.

I had already gone with your suggestion of mvoing the style tag outside.  I guess I'll have to stick with that.
