### ISSUE TITLE
Table border is not showing on web page

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1563]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

1. Add a table in ckeditor 5 with content in each cell. It showing the broder for each cell and table.
2. Save the content.
3. Open the saved content on web page. The table/cell borders are not showing.

## ✅ Expected result
The table/cell border should be visible as is when the content is seen on web page.

## ❎ Actual result
No table/cell borders are showing

**Comment by Reinmar** [comment]
Hi! CKEditor 5 outputs semantic data and styles are not part of it. It's your responsibility to style the content on the target page.

We're planning, however, to document how to achieve similar results as in the editor: https://github.com/ckeditor/ckeditor5/issues/1259

**Comment by chuckdu21** [comment]
So what i see is not what i get. Unfortunately is just the purpose of this kind of service....

**Comment by chetan-rane-zebra** [comment]
> So what i see is not what i get. Unfortunately is just the purpose of this kind of service....

Yes ckeditor is becoming a pain...and they just resolve issues without any rational and keep resolving issues giving some references which are still pending since years...its a pathetic tool and become such a pain to maintain
How can they miss any feature which was present in earlier version?

**Comment by Reinmar** [comment]
This issue is resolved for a long time. But it requires a bit of effort to find the guide that addressed this problem. Which is:

#1259 -> #773 -> 6330ffb -> [https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/css.html](https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/css.html)
