### ISSUE TITLE
Docs issue report from "installation/getting-started/getting-and-setting-data.html"

### ISSUE THREAD

**Issue by anbrusi** [ckeditor/ckeditor5#15666]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/getting-and-setting-data.html

### Project version

40.2.0

### Is there anything else you would like to add?

Your docu:

<?php
	$data = str_replace( '&', '&', $data );
?>

<textarea name="content" id="editor"><?= $data ?></textarea>

Did You possibly mean: 

<?php
       $data = str_replace('&', &amp;', $data) ?
?>

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15

**Comment by anbrusi** [comment]
My comment was corrupted.

Inside the php tags Your docu reads "str_replace('&', '&', $data)", but should it not rather be str_replace('&', '&amp;', $data)" i.e. should not the second ampersand be encoded?

**Comment by Witoso** [comment]
Thanks for the request, you're right, the `v35.4` is correct. @mateuszzagorski I remember some changes were done there recently.
