### ISSUE TITLE
getting error ./node_modules/@ckeditor/ckeditor5-widget/theme/widgetresize.css:6:0 - Error: Module parse failed: Unexpected token (6:0)

### ISSUE THREAD

**Issue by mustafagaut** [ckeditor/ckeditor5#15663]
Hello, i am getting Error while integrating ckeditor5 to my angular@15 getting this type of errors 
./node_modules/@ckeditor/ckeditor5-widget/theme/widgetresize.css:6:0 - Error: Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| 
> .ck .ck-widget_with-resizer {
|       /* Make the widget wrapper a relative positioning container for the drag handle. */
|       position: relative;

**Step to produce **
my app.component.ts file 
import { Component,OnInit, EventEmitter, Output } from '@angular/core';
import Editor from '../../../../ckeditor5';
import * as ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic';
import CKEditorInspector from '@ckeditor/ckeditor5-inspector';
import { ChangeEvent } from '@ckeditor/ckeditor5-angular/ckeditor.component';
// import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import { FormControl } from '@angular/forms';
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
@Component({
  selector: 'app-ckeditor',
  templateUrl: './ckeditor.component.html',
  styleUrls: ['./ckeditor.component.css']
})
export class CkeditorComponent {
  @Output() contentChange = new EventEmitter<string>();
  public Editor;
 
  ngOnInit() {
    const editorElement:any = document.querySelector('#editor');

    if (editorElement) {
      this.Editor = ClassicEditor.create(editorElement, {
        plugins: [Essentials, Paragraph, Bold, Italic],
        toolbar: ['bold', 'italic']
      })
        .then(editor => {
          console.log('Editor was initialized', editor);
        })
        .catch(error => {
          console.error(error.stack);
        });
    } else {
      console.error('Element with id "editor" not found.');
    }
  }
  // public Editorial =Editor.defaultConfig;
public name = new FormControl();

  
  public onReady(editor: ClassicEditor) {
    console.log('CKEditor5 Angular Component is ready to use!', editor);
    
  }
  onContentChange({ editor }: ChangeEvent) {

   console.log("here data" , this.name);
  this.contentChange.emit(editor.data.get());
  }
}

**html file**
<ckeditor 
id="editor"
(change)="onContentChange($event)" 
[editor]="Editor" 
data="<p>Hello, world!</p>"
formControlName="name"
     >
    </ckeditor>

**Comment by Witoso** [comment]
Hi! Your're mixing a [predefined build](https://ckeditor.com/docs/ckeditor5/36.0.1/installation/getting-started/predefined-builds.html) with a [custom build](https://ckeditor.com/docs/ckeditor5/36.0.1/installation/getting-started/quick-start-other.html) (`@ckeditor/ckeditor5-build-classic`)

If you want to define a list of plugins, a custom build needs to be used with a different editor package: `@ckeditor/ckeditor5-editor-classic`.
