### ISSUE TITLE
API docs for `LabeledView` are still available, even though the class was renamed to `LabeledFieldView`

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15670]
## 📝 Provide a description of requested docs changes

API docs for `LabeledView` are still available here: https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_labeledview_labeledview-LabeledView.html

This can cause confusion since the correct name for the class is now `LabeledFieldView`: https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_labeledfield_labeledfieldview-LabeledFieldView.html

This change was introduced in [v19.0.0](https://github.com/ckeditor/ckeditor5/releases/tag/v19.0.0) but it looks like the API docs weren't correctly altered to reflect the change.

**Comment by pomek** [comment]
According to internal talks, we can create a redirect from the old page to the new one.

**Comment by godai78** [comment]
Redir added in 9ea1bb7
