### ISSUE TITLE
Editor is freezing after hitting left or right arrow when the cursor is at the beginning or end of the caption.

### ISSUE THREAD

**Issue by frknkara** [ckeditor/ckeditor5#1568]
Using arrow keys in image captions causes a problem. Hitting left or right arrow when the cursor is at the beginning or end of the caption, respectively, causes a temporary freeze. 

Append a lot of paragraphs/tables/lists to demo editor, then keep down-arrow pressed while cursor is on monk picture's caption and it will freeze. Up arrow would not cause a freeze in this case. Insert content before the image and keeping up-arrow pressed will cause a freeze this time. This suggests processing time is correlated with the amount of content in the direction of the arrow key pressed. 

We found that the `skip `function in ckeditor5-engine\src\model\treewalker.js is the culprit. Depending on the length of the document, the loop may take 100K iterations, till it reaches the first or last element of the document. If we change the passed in parameter in `tryExtendingTo `function of ckeditor5-engine\src\model\utils\modifyselection.js to `false`, the problem vanishes. It can be the problem.

**Comment by Reinmar** [comment]
There's a discussion about this issue on https://stackoverflow.com/questions/54689603/any-side-effects-of-changing-a-parameter-in-modifyselection-of-ckeditor-5. Maybe some more details too.

**Comment by Mgsy** [comment]
Hello! I've checked your scenario and I'm not able to reproduce the issue. The selection changes quickly after hitting an arrow key at the beginning/at the and of the caption.

>Append a lot of paragraphs/tables/lists to demo editor

What do you understand by `a lot`? Could you call `editor.getData()` in your console and share the result on Gist? It will be very helpful. I assume you're using our demo on the CKEditor website?

**Comment by frknkara** [comment]
We tried it again. We can't reproduce it now.  I think, behaviour of editor was changed or we tried a different case that time.

**Comment by Mgsy** [comment]
>We tried it again. We can't reproduce it now.

That's great news :D Thanks for the information!
