### ISSUE TITLE
代码块无法高亮显示.

### ISSUE THREAD

**Issue by adairhmj** [ckeditor/ckeditor5#15694]
## 📝 Ask a question

我使用cdn在线版本搭配prism.js正常可以使插入的代码块高亮显示.
![image](https://github.com/ckeditor/ckeditor5/assets/44510632/33930671-2ad7-4512-ae82-09b02f70854d)

但是我把编辑器安装在本地就失效了.有时我重新下载一个只有Code blocks插件的英文版编辑器.他又正常工作了.
![image](https://github.com/ckeditor/ckeditor5/assets/44510632/1ce5c218-ee44-4b90-b7cf-aed1adea841b)
我发现它好像缺少 < code class="language-*" > ,但是我不知道应该怎样添加他们,或者问题在哪里?
![image](https://github.com/ckeditor/ckeditor5/assets/44510632/fb907b6f-8502-4ff3-a134-8857c01faf9a)

**Comment by Witoso** [comment]
DUP: #15695
