### ISSUE TITLE
Remove EditorConfig

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#157]
The idea behind `EditorConfig` was that we could have global `CKEDITOR.config` object and specific `editor.config` objects. When accessing the specific config, first that one would be checked and, if the value hasn't been defined there, the global one. That was meant to allow easier configuration setting if you have repeating needs on your website.

But, I consider this an overcomplication for couple of reasons:

1. We want `Config.get()` to throw errors if an option wasn't defined. This means that `EditorConfig`'s implementation would require `Config.has()`, because we shouldn't control correct code flow by `try-catch`.
2. We have circular dependency between Editor -> EditorConfig -> CKEDITOR -> Editor (see https://github.com/ckeditor/ckeditor5/issues/118).
3. We want to allow instantiating standalone `Editor`s (without using `CKEDITOR`).
4. It's trivial to pass the same config options to multiple editors, so the whole global thing isn't necessary in the first place.

So IMO the `Editor` should use and instance of `Config`. KISS.

**Comment by fredck** [comment]
> That was meant to allow easier configuration setting if you have repeating needs on your website.

That's not actually true.

The reason for that is mainly for having a global `config.define` that plugins will use to define their own configurations and defaults. In other words, plugins define their defaults globally and retrieve configurations from editor instances instead.

**Comment by Reinmar** [comment]
> The reason for that is mainly for having a global config.define that plugins will use to define their own configurations and defaults. In other words, plugins define their defaults globally and retrieve configurations from editor instances instead.

The plugins should call `define()` on `editor.config`. Plugins operate on editor instances that were specified to them. We got totally rid of the `CKEDITOR` global from our minds, so I haven't even thought about it when implementing recent features. So that features were directly defining defaults on `editor.config`, what in fact makes it even more clear for me that `CKEDITOR.config` has to be removed.

**Comment by pjasiun** [comment]
> The plugins should call define() on editor.config. Plugins operate on editor instances that were specified to them. We got totally rid of the CKEDITOR global from our minds, so I haven't even thought about it when implementing recent features. So that features were directly defining defaults on editor.config, what in fact makes it even more clear for me that CKEDITOR.config has to be removed.

:+1: Thanks to it plugins may have different default depending in the type of the editor. Also having too many reference to the global `CKEDITOR` would make it a God object what is a bad smell.

**Comment by pjasiun** [comment]
> That was meant to allow easier configuration setting if you have repeating needs on your website.

On the other hand, letting user to having a global config sounds like a useful feature, but I believe we will be able to introduce it later. Also I remember that when I was starting to use CKEditor it was unclear which config it use and which I should modify. We could limit the number of configuration files CKE5 use, at least at the beginning.

**Comment by Reinmar** [comment]
> We could limit the number of configuration files CKE5 use, at least at the beginning.

That's the idea that came to my mind. The more alternatives we create, the more confusing the thing is. Requiring specifying the config while creating and editor will KISS. Shorter docs, less code, less issues like the one we are handling right now and other ones like circular deps, less confusion, less possible bugs. Much win.
