### ISSUE TITLE
Code Snippets and image upload

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor5#1570]
## Is this a bug report or feature request? (choose one)

  🆕 Feature request  |  Other

## 💻 Version of CKEditor

CKEditor5

Hi, Is there any image sizing (adjusting height|width|rotating) feature on upload in CKEditor5 and Is there any code snippet plugin which is available in CKEditor4.

**Comment by scofalik** [comment]
Hello,

as of now, there are neither image resizing nor code block features. We want to bring in those but as of now, we don't have any date on that. Those features are on our long-term to-do list.
