### ISSUE TITLE
[FF] The caret isn't visible between inline widgets

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1571]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. http://localhost:8125/ckeditor5-widget/tests/manual/inline-widget.html
2. Insert two inline widgets nearby to each other.
3. Using keyboard arrows – put the selection between them.

## ✅ Expected result

The cursor should be visible.

## ❎ Actual result

But it isn't.

## 📃 Other details that might be useful

After adding `margin: 0 1px;` to `placeholder` selector, the selection appeared.

Firefox 65.0.1 (20190211233335)

**Comment by jodator** [comment]
Just to be clear - it's the manual test CSS issue (implementation) not the editor itself.
