### ISSUE TITLE
Paste image from excel to ckeditor5, can not display

### ISSUE THREAD

**Issue by youcanping** [ckeditor/ckeditor5#15719]
## 📝 Provide a description of the new feature

<img width="757" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/30832864/18f7fdd7-0289-4f36-ae80-332074b96f5d">

**Comment by Witoso** [comment]
Hi! Could you elaborate on how you copied the image? What kind of upload adapters you have enabled?

**Comment by youcanping** [comment]
You can reproduce it from the example of pasting any image from excel to the official website.
Step.1
![image](https://github.com/ckeditor/ckeditor5/assets/30832864/7cf8659a-8018-46b0-bcbb-fcfc64321dbc)
Step.2
https://ckeditor.com/ckeditor-5/demo/editor-types/#classic
![image](https://github.com/ckeditor/ckeditor5/assets/30832864/a9c84ebb-85a1-46e5-a4c0-ca92c6ebaca2)

**Comment by Witoso** [comment]
Duplicate #15758
