### ISSUE TITLE
[New installation methods] Rollup CSS plugin

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#15711]
The scope of this task is to create a Rollup plugin to extract the editor and content classes from the final CSS bundle (`styles.css`) and generate separate CSS files for them (`editor.css` and `content.css`).

If given package doesn't register any styles, this plugin should output empty `styles.css`, `editor.css` and `content.css` CSS files.

**Comment by pszczesniak** [comment]
Solved in ckeditor/ckeditor5-dev#939.
