### ISSUE TITLE
Broken styling of dialogs when using dark theme from docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#15730]
## 📝 Provide detailed reproduction steps (if any)

1. Use CSS from the [custom theme guide](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/ui/theme-customization.html)

### ❌ Actual result

Styling of the Find & Replace and AI Assistant dialogs is broken:

![Screenshot 2024-01-19 at 16 19 50](https://github.com/ckeditor/ckeditor5/assets/34380544/4547413a-b0ac-461f-88bc-6836000996e6)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* First affected CKEditor version: 41.0.0
* Installed CKEditor plugins: Find & Replace

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Done in #15747.
