### ISSUE TITLE
Docs issue report from "tutorials/crash-course/view.html"

### ISSUE THREAD

**Issue by timdadd** [ckeditor/ckeditor5#15731]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/tutorials/crash-course/view.html

### Project version

41.0.0

### Is the information outdated? How?

The bind...to generates an [error](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-observable-bind-to-parse-error) 

Offending line:
` button.bind( 'isOn', 'isEnabled' ).to( command, 'value', 'isEnabled' );
`

### User agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by filipsobol** [comment]
Hi @timdadd, thank you for reporting this issue. Unfortunately, I cannot reproduce it. Would it be possible for you to share the code you got after following our tutorial?

**Comment by timdadd** [comment]
Apologies for slow reply, I don't play with this very often.
The error is invalid number of attributes.
I changed the line to remove 'value'
`button.bind( 'isOn', 'isEnabled' ).to( command, 'isEnabled' );`
