### ISSUE TITLE
how to disable ck-widget draggable

### ISSUE THREAD

**Issue by Bloomingg** [ckeditor/ckeditor5#15748]
## 📝 Ask a question

_What is your question? Please be as specific as possible to help us understand it._

I found that when the inserted picture or other widget is clicked, a draggable="true" will be added, causing the event I attached to the picture to not be triggered. I am using `@ckeditor/ckeditor5-editor-classic`. Not sure how to solve this problem

**Comment by Witoso** [comment]
Hi! Could you describe a bit more the event you're using? I don't think it will be possible to disable this draggable for our images easily without overriding the whole image pipeline or some nasty hacks.

**Comment by Bloomingg** [comment]
I achieved what I needed with this example, thank you very much for your guidance!
