### ISSUE TITLE
Widget toolbar covers editor's sticky toolbar when scrolling

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#15744]
## 📝 Provide detailed reproduction steps (if any)

1. [Go to demo](https://ckeditor.com/ckeditor-5/demo/feature-rich/)
2. Add a table
3. Focus table and scroll the content down

### ✔️ Expected result

Table toolbar detects editor's sticky toolbar and moves down to the bottom of the table.

### ❌ Actual result

Table toolbar does not detect sticky toolbar and covers it. It only moves to the bottom of the table when it reaches top border of the editor (or rather the top website navigation bar). This happens also for other widget toolbars, for example image.

https://github.com/ckeditor/ckeditor5/assets/34380544/9ecd627d-2dd3-451c-84b5-1ccc03a3ca49

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
We already have two integrations for `Dialog` positioning and `scrollToTheSelection()`

https://github.com/ckeditor/ckeditor5/blob/dd3b278ece67f714b7f440801b4b770fa2ac804a/packages/ckeditor5-editor-classic/src/classiceditorui.ts#L184-L251

Maybe there’s a similar way to hook into the `ContextualBalloon` system?
