### ISSUE TITLE
Docs issue report from "api/module_ui_focuscycler-FocusCycler.html"

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#15740]
### Origin URL

https://ckeditor.com/docs/ckeditor5/41.0.0/api/module_ui_focuscycler-FocusCycler.html

### Project version

41.0.0

### Is the information outdated? How?

The documentation is outdated with 41.0.0 and the Dialog System, if I get it correctly.

The examples state:

```ts
const focusables = new ViewCollection();
const focusTracker = new FocusTracker();

// Add focusable views to the focus tracker.
focusTracker.add( ... );
```

and

```ts
const cycler = new FocusCycler( { focusables, focusTracker } );

// ...
```

The second statement won't compile, because `focusables` changed from type `ViewCollection` to `ViewCollection<FocusableView>`:

```text
error TS2322: Type 'ViewCollection<View<HTMLElement>>' is not assignable to type 'ViewCollection<FocusableView>'.
   Type 'View<HTMLElement>' is not assignable to type 'FocusableView'.
     Property 'focus' is missing in type 'View<HTMLElement>' but required in type '{ focus(direction?: 1 | -1 | undefined): void; }'.
```

If it is not the documentation, that is outdated, then it is the implementation/typing.

41.0.0 version:

https://github.com/ckeditor/ckeditor5/blob/v41.0.0/packages/ckeditor5-ui/src/focuscycler.ts#L77

39.0.2 version (we are upgrading from):

https://github.com/ckeditor/ckeditor5/blob/v39.0.2/packages/ckeditor5-ui/src/focuscycler.ts#L76

Changed with reference to: #14973

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by Dumluregn** [comment]
Thank you for the report. The docs were indeed outdated. They were fixed in 24d57ed. The update should be live soon.
