### ISSUE TITLE
Can we create our own plugin as a DLL while using the angular wrapper?

### ISSUE THREAD

**Issue by jeandat** [ckeditor/ckeditor5#15745]
## 📝 Ask a question
Hi there, need feedback from experienced people before we enter the rabbit hole…

We started migrating from version 4 to 5. Right now for simplicity we are using the angular wrapper and a custom build downloaded from the online builder.

In our legacy code, we have two custom plugins which essentially do the same job:
- we want to propose either buttons or a select with options which when clicked insert a content in the editor.
- for instance in our report editor we have widgets. One of them is a text editor: we want to be able to insert the current date, or the page number, etc.

After reading the documentation, I have several questions:
- Is it possible to create an independent DLL package while using a custom build and the angular wrapper? One very important constraint is that we want to be able to limit the plugins (and maybe the translations) we include in the final build.
- Regarding our need, which do not seems very exotic, is there an already existing plugin that would do the job? In that case we wouldn't have to create our own DLL. 
- The DLL way seems to be the right approach. Is it?

Thanks guys.

**Comment by Witoso** [comment]
Hi! Thanks for reaching out!

> *   Is it possible to create an independent DLL package while using a custom build and the angular wrapper? One very important constraint is that we want to be able to limit the plugins (and maybe the translations) we include in the final build.

No, those installation methods cannot be mixed, if you decide to use the DLLs, you cannot use the online builder. DLLs need to be set up as described [in the docs](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html). That said, we will soon replace the DLLs and other installation methods with something more intuitive (#15502). When you choose something right now, the migration later should be simple anyway.

> *   we want to propose either buttons or a select with options which when clicked insert a content in the editor.

We have a similar premium feature called Templates, but it's for the HTML structure. What you're describing is also similar to our [placeholders tutorial](https://ckeditor.com/docs/ckeditor5/latest/tutorials/widgets/implementing-an-inline-widget.html#the-model-and-the-view-layers).

**Comment by jeandat** [comment]
Thanks a lot @Witoso, just reading your response after being ill. Big help and avoid us a lot of headaches. Hope you will find a more friendly way. We are going to play and test the placeholder plugin until then. It might be enough for our need.
