### ISSUE TITLE
Revision History v41.0.0 integration failing in Angular version 15

### ISSUE THREAD

**Issue by raziahmadansari** [ckeditor/ckeditor5#15743]
## 📝 Provide detailed reproduction steps (if any)

Followed the steps listed on the official CKEditor5 docs to integrate a custom CKEditor build with `Angular`
1. Used `npm install ./ckeditor` to add the package located in the ckeditor directory as a dependency to my project
2. Then added `Comments` and `Track changes` plugin, and everything till here worked just fine.
3. Proceeded with integrating `Revision History`, used `npm install --save-dev @ckeditor/ckeditor5-revision-history
` to install the package and added it in the `CustomEditor` `builtinPlugins` list. Then ran `npm run build` (as mentioned in docs). The build is done without any error. But when I did `npm start` in my `Angular` project, it is throwing a lot of `export errors` in `Revision History` library.

`package.json`
```
{
    "devDependencies": {
            "@ckeditor/ckeditor5-revision-history": "^41.0.0"
     }
}
```
`Note: All the library versions are same 41.0.0`

### ✔️ Expected result

The `Angular` project should build without any error.

### ❌ Actual result

Getting internal import errors in `Revision History` library.
```
Error: node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:19:9 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

19         [RevisionViewer.pluginName]: RevisionViewer;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:20:9 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

20         [RevisionViewer.pluginName]: RevisionViewer;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/index.d.ts:10:10 - error TS2305: Module '"./revisionviewer.js"' has no exported member 'default'.

10 export { default as RevisionViewer, type RestoreRevisionCommand, type ShowChangeCommand } from './revisionviewer.js';
            ~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/index.d.ts:10:42 - error TS2305: Module '"./revisionviewer.js"' has no exported member 'RestoreRevisionCommand'.

10 export { default as RevisionViewer, type RestoreRevisionCommand, type ShowChangeCommand } from './revisionviewer.js';
                                            ~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/index.d.ts:10:71 - error TS2305: Module '"./revisionviewer.js"' has no exported member 'ShowChangeCommand'.

10 export { default as RevisionViewer, type RestoreRevisionCommand, type ShowChangeCommand } from './revisionviewer.js';
                                                                         ~~~~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/ui/revision/revisionview.d.ts:10:8 - error TS1192: Module '"C:/Code/DV_MVC_REST/node_modules/@ckeditor/ckeditor5-revision-history/src/ui/revision/revisionnameview"' has no default export.

10 import RevisionNameView from './revisionnameview.js';
          ~~~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/ui/revisionssidebar/revisionssidebar.d.ts:9:8 - error TS1192: Module '"C:/Code/DV_MVC_REST/node_modules/@ckeditor/ckeditor5-revision-history/src/revisionviewer"' has no default export.

9 import RevisionViewer from '../../revisionviewer.js';
         ~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-revision-history/src/ui/revisionviewer/revisionviewerui.d.ts:9:8 - error TS1192: Module '"C:/Code/DV_MVC_REST/node_modules/@ckeditor/ckeditor5-revision-history/src/revisionviewer"' has no default export.

9 import RevisionViewer from './../../revisionviewer.js';
         ~~~~~~~~~~~~~~




× Failed to compile.
```

### ❓ Possible solution

The required `export` statements might be missing in `Revision History` library.

## 📃 Other details

* Browser: Firefox Developer Edition
* OS: Windows 11
* First affected CKEditor version: …
* Installed CKEditor plugins: 
```
"dependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^41.0.0",
    "@ckeditor/ckeditor5-autoformat": "^41.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^41.0.0",
    "@ckeditor/ckeditor5-block-quote": "^41.0.0",
    "@ckeditor/ckeditor5-ckbox": "^41.0.0",
    "@ckeditor/ckeditor5-ckfinder": "^41.0.0",
    "@ckeditor/ckeditor5-cloud-services": "^41.0.0",
    "@ckeditor/ckeditor5-easy-image": "^41.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^41.0.0",
    "@ckeditor/ckeditor5-essentials": "^41.0.0",
    "@ckeditor/ckeditor5-heading": "^41.0.0",
    "@ckeditor/ckeditor5-image": "^41.0.0",
    "@ckeditor/ckeditor5-indent": "^41.0.0",
    "@ckeditor/ckeditor5-link": "^41.0.0",
    "@ckeditor/ckeditor5-list": "^41.0.0",
    "@ckeditor/ckeditor5-media-embed": "^41.0.0",
    "@ckeditor/ckeditor5-mention": "^41.0.0",
    "@ckeditor/ckeditor5-paragraph": "^41.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^41.0.0",
    "@ckeditor/ckeditor5-table": "^41.0.0",
    "@ckeditor/ckeditor5-typing": "^41.0.0",
    "rxjs": "~6.6.0"
  },
  "devDependencies": {
    "@ckeditor/ckeditor5-comments": "^41.0.0",
    "@ckeditor/ckeditor5-core": "^41.0.0",
    "@ckeditor/ckeditor5-dev-translations": "^39.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^39.0.0",
    "@ckeditor/ckeditor5-revision-history": "^41.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^41.0.0",
    "@ckeditor/ckeditor5-track-changes": "^41.0.0",
    "terser-webpack-plugin": "^4.2.3",
    "typescript": "5.0.4",
    "webpack": "^5.58.1",
    "webpack-cli": "^4.9.0"
  }
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! Thanks for the report we will investigate it. One thing that came to mind is to bump the TypeScript version to `5.0.0` in the **online builder folder's** `package.json`, reinstall dependecies, and rebuild. Could you check if this solves the problem?

**Comment by raziahmadansari** [comment]
Hi @Witoso , I tried with the `latest typescript` version at present which is `5.3.3`. I didn't find `v5.0.0` in stable release but have tried with the versions which are in stable release, such as `v5.0.2` and `v5.0.3`. Still getting the same error which I've mentioned earlier.

**Comment by Witoso** [comment]
We cannot reproduce the issue, could you provide some reproducible sample for us?

**Comment by raziahmadansari** [comment]
# Reproduction steps:
1. Navigate to the official CKEditor online builder integration with Angular - [Integrating a build from the online builder](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html#integrating-a-build-from-the-online-builder)
2. Used few basic plugins only to generate the custom online build.
3. Then added CKEditor - Comments and Tracking changes plugin. Used `Adapter Integration` approach with both the plugins.
4. Till here everything was working as expected.

## [Revision History Plugin Integration]
1. Started with installing the `CKEditor - Revision History` plugin via `npm` and just added it in the `builtinPlugins` array.
2. Below are the scripts used in `package.json` to build the custom editor.
```
"scripts": {
    "development": "webpack --mode development",
    "build": "webpack --mode production",
    "postbuild": "tsc --declaration --declarationDir build --stripInternal --emitDeclarationOnly"
}
```
3. Commands used frequently to build the custom ckeditor - `npm run development` and `npm run postbuild`
4. Till here, nothing breaks but when I start building my `Angular project`, the above mentioned error pops-up in console. Hence, resulting in build failure.
5. And if I just remove the `Revision History` plugin from custom CKEditor `buildinPlugins` array (which is located in file: `ckeditor.ts`) then these console errors are gone.

## [Project Structure]
| custom-ckeditor-build
|-- build
|-- sample
|-- src
|---- plugins
|------ (custom plugins)
|---- ckeditor.ts
|-- package.json
|-- tsconfig.json
|-- webpack.config.cjs
| node_modules
| src (angular-project)
|-- app
|---- assets
|---- environments
| package.json
| tsconfig.app.json
| tsconfig.json

**Comment by Witoso** [comment]
Please reach out through [our support](https://ckeditor.com/contact/), we need to take a closer look at this.
