### ISSUE TITLE
How to properly establish a connection with custom html

### ISSUE THREAD

**Issue by iskatel-ua** [ckeditor/ckeditor5#15751]
I have the following task:
I insert custom tags for the Angular component and have already ensured that they are displayed as expected and when clicked, a modal appears that adds attributes with data to the component tag. Unfortunately, I just can’t get the model to understand that the html has changed and this data is lost and not saved to the server. I tried different attributeToAttribute options, nothing helps. I'll be grateful for any ideas.

![image](https://github.com/ckeditor/ckeditor5/assets/11649125/18d4207a-ff62-4cce-a59d-e01ddbe1b848)
![image](https://github.com/ckeditor/ckeditor5/assets/11649125/64e20fc1-0f4d-4925-8c6c-c458875cae07)

**Comment by Witoso** [comment]
Hi!

> I insert custom tags for the Angular component and have already ensured that they are displayed as expected and when clicked

How do you insert them? Editor will not "understand" the manipulation on the HTML level. If you create some customization, you need to operate on the model's data, that is later rendered to HTML, not the other way around.

**Comment by iskatel-ua** [comment]
> Hi!
> 
> > I insert custom tags for the Angular component and have already ensured that they are displayed as expected and when clicked
> 
> How do you insert them? Editor will not "understand" the manipulation on the HTML level. If you create some customization, you need to operate on the model's data, that is later rendered to HTML, not the other way around.

Is it possible to create a modal window by clicking on my custom block to set parameters there?
