### ISSUE TITLE
[Docs] Image upload animation is displayed incorrectly in Safari

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1575]
Safari:

![feb-22-2019 17-08-19](https://user-images.githubusercontent.com/156149/53254845-90a91200-36c4-11e9-9687-8352c34b1040.gif)

Chrome: 
![image](https://user-images.githubusercontent.com/156149/53254885-ab7b8680-36c4-11e9-9ab8-7ff588fe4f33.png)

**Comment by dkonopka** [comment]
It's all about `offset-path` inside [animation](https://ckeditor.com/docs/ckeditor5/latest/assets/img/image-upload-animation.svg) https://caniuse.com/#feat=css-motion-paths. Firefox is rendering it wrongly too.

**Comment by RyszardB** [comment]
[ie-anim-1.svg.zip](https://github.com/ckeditor/ckeditor5/files/2900120/ie-anim-1.svg.zip)
