### ISSUE TITLE
Conflict between GeneralHtmlSupport and FontBackgroundColor

### ISSUE THREAD

**Issue by sunesimonsen** [ckeditor/ckeditor5#15757]
## 📝 Provide detailed reproduction steps (if any)

 On the branch [ssimonsen/general-html-support](https://github.com/sunesimonsen/ckeditor-bugs/tree/ssimonsen/general-html-support) the editor renders the background color for the heading:

<img width="918" alt="Screenshot 2024-01-25 at 10 49 58" src="https://github.com/sunesimonsen/ckeditor-bugs/assets/90802/3cfdffcb-6f1a-4eea-a106-b357d195fcb9">

But when the [BackgroundFontColor](https://ckeditor.com/docs/ckeditor5/41.0.0/features/font.html) plugin is added the background color is no longer rendered:

<img width="919" alt="Screenshot 2024-01-25 at 10 53 32" src="https://github.com/sunesimonsen/ckeditor-bugs/assets/90802/a774eac2-70d0-48f1-b378-2ec2001e0c32">

I tracked the problem do to [this line](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-font/src/fontbackgroundcolor/fontbackgroundcolorediting.ts#L105), when removed everything works again.

Minimal reproduction can be found [here](https://github.com/sunesimonsen/ckeditor-bugs/pull/1).

Notice that the table plugin also introduces the bug, as it also makes use of [addBackgroundRules](https://github.com/ckeditor/ckeditor5/blob/b4a74134b58042cb5e394f7a95dad9c4be00993f/packages/ckeditor5-engine/src/view/styles/background.ts#L37).

This bug is currently blocking Zendesk customers from applying background styles.

### ✔️ Expected result

That the background color is maintained.

### ❌ Actual result

The background inline style is stripped.

### ❓ Possible solution

Make [addBackgroundRules](https://github.com/ckeditor/ckeditor5/blob/b4a74134b58042cb5e394f7a95dad9c4be00993f/packages/ckeditor5-engine/src/view/styles/background.ts#L37) compatible with the general HTML support plugin.

## 📃 Other details

* First affected CKEditor version: probably all
* Installed CKEditor plugins: `@ckeditor/ckeditor5-basic-styles`, `@ckeditor/ckeditor5-essentials`, `@ckeditor/ckeditor5-paragraph`, `@ckeditor/ckeditor5-html-support`, `@ckeditor/ckeditor5-font`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by sunesimonsen** [comment]
@Witoso the background also conflicts with the table plugin, so maybe this issue should also have the `package:table` label.

**Comment by niegowski** [comment]
> I was able to reproduce it.
> 
> The only way to make it work for me, was to change GHS config to:
> 
> ```js
> allow: [
>   {
>        name: "h1",
>        styles: true,
>    }
> ]
> ```
> 
> This also converted original `background` property to `background-color`.

This would also work with the following GHS config:

```js
allow: [
  {
       name: "h1",
       styles: [ 'background-color' ],
   }
]
```
The above would properly handle both `background: red` and `background-color: red`.

This is happening because the editor (while loading data) parses the styles and normalizes values so that shorthand notations can be handled transparently as longhand notations (`background: red` => `background-color: red`). Since we handle only the `background-color` style then we can't reduce it to the shorthand notation because we do not know if there is no other rule for background that could interfere.

**Comment by sunesimonsen** [comment]
> This is happening because the editor (while loading data) parses the styles and normalizes values so that shorthand notations can be handled transparently as longhand notations (background: red => background-color: red). Since we handle only the background-color style then we can't reduce it to the shorthand notation because we do not know if there is no other rule for background that could interfere.

I just checked, using the following configuration also conflicts:

```js
      htmlSupport: {
        allow: [
          {
            name: "h1",
            styles: ["background-color"],
          },
        ],
      },
```

**Comment by sunesimonsen** [comment]
@Witoso do you have any timeline for when this bug will be fixed? The reason why I'm asking is because Zendesk is currently holding back on realizing a new feature because of this bug ☺️

**Comment by Witoso** [comment]
@niegowski is doing a research right now, as it turned out to be more complex than we anticipated. Should know soon the scope, and then we will decide on the next steps. cc @arkflpc

**Comment by sunesimonsen** [comment]
🥇 thanks a lot - I'll test it as soon as it have been released.
