### ISSUE TITLE
FullPage plugin not available in Online Builder?

### ISSUE THREAD

**Issue by replaysMike** [ckeditor/ckeditor5#15767]
## 📝 Provide detailed reproduction steps (if any)

1. Using the [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/)
2. Configure Plugins in Step 2
3. FullPage is missing from the selection

### ✔️ Expected result

FullPage should be available as a plugin according to the [FullPage](https://ckeditor.com/docs/ckeditor5/latest/features/html/full-page-html.html) demo docs 

### ❌ Actual result

It's missing. It's not listed as an available plugin on the editor instance confirming this.
Trying to add it manually as follows does not work (I wouldn't expect this would work when using the custom online build):

```
npm install --save @ckeditor/ckeditor5-html-support
```
```js
import { FullPage } from '@ckeditor/ckeditor5-html-support';
```

### ❓ Possible solution

in `src/ckeditor.ts` generated by the [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) modify the lines to:

`import { DataFilter, GeneralHtmlSupport, HtmlComment, FullPage } from '@ckeditor/ckeditor5-html-support';`

```
class Editor extends ClassicEditor {
  public static override builtinPlugins = [
/*...*/
    FontSize,
    FullPage, // <-- add this
    GeneralHtmlSupport,
/*...*/
];
}
```

and rebuild the custom build using:
```
yarn install
yarn run build
```

and FullPage should now be listed as an available plugin on the editor instance.

## 📃 Other details

* Chrome 120.0.6099.225
* OS: Windows 11
* First affected CKEditor version: 5
* Installed CKEditor plugins: [alignment,autoformat,basic-styles,block-quote,cloud-services,editor-classic,essentials,find-and-replace,font,heading,horizontal-line,html-support,image,indent,link,list,paragraph,paste-from-office,remove-format,select-all,show-blocks,source-editing,style,table,typing,undo]

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! As far as I know, this was a conscious decision, this plugin can be quite non-intuitive for the beginners, and people not familiar with the HTML editing, and it was hidden. We will not add it to the current builder, but we are rethinking the experience for it, and we will reconsider this. Thanks for the report!
