### ISSUE TITLE
Online Builder README.md has a broken link

### ISSUE THREAD

**Issue by replaysMike** [ckeditor/ckeditor5#15766]
## 📝 Provide a description of requested docs changes

_What is the purpose and what should be changed?_

The README.md that is included in the zip file from the Online Builder has a broken link.
In the section `Adding or removing plugins` the link to [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor) does not exist.

**Comment by pomek** [comment]
I fixed the issue in the original repository. It will be fixed after the next CKEditor 5 release that is scheduled for the next week (Wed).
