### ISSUE TITLE
The splitbutton divider is not placed correctly when toolbar is decoupled

### ISSUE THREAD

**Issue by NvanWeeghel** [ckeditor/ckeditor5#15779]
## 📝 Provide detailed reproduction steps (if any)

1. install a plugin with a splitbutton (like ListProperties)
2. Decouple the toolbar from the editor

### ✔️ Expected result

![image](https://github.com/ckeditor/ckeditor5/assets/131269144/2464dd70-2d36-442f-bf7c-8e0a79d2104e)

### ❌ Actual result

![image](https://github.com/ckeditor/ckeditor5/assets/131269144/da8004b7-1d5c-4f66-8b17-255585fe7e30)

## 📃 Other details

* Browser: Firefox 122.0
* OS: Windows 10
* First affected CKEditor version: ? (my current version is 40.2.0)
* Installed CKEditor plugins:
   ckeditor5-angular
    ckeditor5-basic-styles
    ckeditor5-editor-classic
    ckeditor5-essentials
    ckeditor5-paragraph
    ckeditor5-theme-lark
    ckeditor5-list

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
> I've found out that it has something to do with that the toolbar does not know the UI language direction. While it is set

Could you elaborate on your setup, I cannot reproduce the issue in our demos?

**Comment by NvanWeeghel** [comment]
In my script.js: 
`ClassicEditor
	.create( document.querySelector( '.editor' ), {
		// Editor configuration.
        
	} )
	.then( Neweditor => {
		editor = Neweditor;
       document.getElementById("toolbar").appendChild(editor.ui.view.toolbar.element);

	} )
	.catch( handleSampleError );`

and in my index.html i have just above the editor class: 
`<div id="toolbar"></div>`

i am able to fix it to set the text direction manualy by:
`<div id="toolbar" dir="ltr"></div>`

**Comment by Witoso** [comment]
I cannot reproduce it in a blank Angular project:
![image](https://github.com/ckeditor/ckeditor5/assets/9881379/6dea6241-2466-4c17-8563-1b5266adc5d5)

Please provide a reproducible sample (repo, zip, etc.) where we can observe the issue.

**Comment by NvanWeeghel** [comment]
i have a reproduction here https://github.com/NvanWeeghel/CKE5

**Comment by Witoso** [comment]
I haven't had an opportunity to check the code in detail, but when I skimmed through it, I noticed you're attaching a toolbar to a `ClassicEditor`, whereas in this case you should be using the [`Decoupled`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html) one.

**Comment by NvanWeeghel** [comment]
Unfortunately the DecoupledEditor has the same style as the [DocumentEditor](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#document-editor), and that's not what i'm looking for. So that's why i use the ClassicEditor
