### ISSUE TITLE
Editor styling isn't like expected

### ISSUE THREAD

**Issue by paolo-05** [ckeditor/ckeditor5#15770]
## 📝 Provide detailed reproduction steps (if any)

1. I've made a custom build using the official tool, and followed the instructions for the NextJS setup.
2. It's not a new project, but it's still in its early phase.
3. I'm using tailwind css

### ✔️ Expected result

Following the docs the lists (both ordered and unordered) have visible markers and indentation, also the headings are bigger than normal paragraphs and are bold.

### ❌ Actual result

Lists result in almost null indentation and invisible markers and headings are rendered as normal paragraphs.

![Screenshot from 2024-01-28 22-58-36](https://github.com/ckeditor/ckeditor5/assets/78367917/1f80b4fb-0c1f-460c-a125-1d5ce69b4cc7)

### ❓ Possible solution

Well, I might be wrong but I think it's tailwind that is causing this problem.
However I've no idea how to fix it....

Another possible solution was to import the styles that are provided in the sample code in the folder downloaded from the editor builder tool. Again, where do I have to put it?

## 📃 Other details

* Browser: Google Chrome Last Version
* OS: Ubuntu 22.04
* First affected CKEditor version: Lastest
* Installed CKEditor plugins: Custom build from the online tool

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Looks like some style clashes, you would need to check the browsers console to investigate why certain styles are not applied. The editor itself attaches the styles (it will change in #15502) but for now there's no need to import them.

**Comment by paolo-05** [comment]
Well, after some research, I found out that Tailwind css has a plugin that lets you "reset" the styles. 

## I'll provide the solution that worked for me here:

1. Modify the `tailwind.config.js` file like so:
```js
const config: Config = {
  //...
  plugins: [
      require("@tailwindcss/typography"),
      // other plugins...
  ],
  //...
```

**Be sure to install it**
```bash
npm install -D @tailwindcss/typography
```
 For more, go to [Tailwind docs](https://tailwindcss.com/docs/typography-plugin)

2. Wrap your custom CKEditor in the **prose** class from Tailwind like so:

```js
<div className="prose">
  <CKEditor
     editor={Editor}
     data={props.initialData}
     onChange={(event, editor) => {
       const data = editor.getData();
       console.log({ event, editor, data });
     }}
  />
</div>
```

And that's all. Hope this will help someone.
