### ISSUE TITLE
Method to convert view to model.

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#15780]
I want to make simple button plugin that adds `<div class="row"><div class="col"></div><div class="col"></div></div>` to document.
I want to use `https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html` plugin for that.

So in my plugin I want to use Your internal "brain" to modify my html text to Your model.
```
this.listenTo(buttonView, 'execute', evt => {
                model.change(writer => {
                    editor.model.insertContent((writer.createText("<div>sd</div>")))
                });
                editor.editing.view.focus();
            });
```
It does not work.
 Is there an internal method that makes it easy way using You internal `View to Model` transformation?
I hope I don't have to do my own conversions because all is there with `GeneralHtmlSupport` plugin.

EDIT: The same way as using `Source` button. If in source mode I type anything as pure HTML Your engine is switching it to model when turning that mode off.

**Comment by Witoso** [comment]
Hello! The third example in [one of our how-tos](https://ckeditor.com/docs/ckeditor5/latest/examples/how-tos.html#how-to-insert-some-content-into-the-editor) shows the insertion of pure HTML through View and Model layers.

**Comment by piernik** [comment]
Great! I'll try it. Think it will be good that You put link to that on https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html
