### ISSUE TITLE
The toolbar is obscured by a custom head

### ISSUE THREAD

**Issue by 2367076952** [ckeditor/ckeditor5#15798]
## 📝 Ask a question

Hello author, I have a question. I defined a fixed head to obscure the toolbar, which makes it difficult for me to control the style of the editor when scrolling down. I just saw that your website has implemented the effect I want. Can you tell me how to do it? Thank you!

![10614c8427c4e89587a51fe5956d2f3](https://github.com/ckeditor/ckeditor5/assets/101549074/ca26228c-59be-4eee-84b9-bc4c457a882a)
![eba7d7ffa559c6002a33412b0e6ee8b](https://github.com/ckeditor/ckeditor5/assets/101549074/aaf69da6-b686-4dec-8d1b-ebe4da8a825d)

**Comment by Witoso** [comment]
Hi! The example that you're showing is using inline editor. Check [the configuration in the docs](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html) or [via online builder](https://ckeditor.com/ckeditor-5/online-builder/).
