### ISSUE TITLE
Table/cell properties hsl values don't honour RTL

### ISSUE THREAD

**Issue by lau11123** [ckeditor/ckeditor5#15801]
## 📝 Provide detailed reproduction steps (if any)

1. Create a CKEditor build in a RTL language, e.g. Arabic 
2. Create a table
3. Open the Table properties
4. Set the background color using the custom color picker
5. A hsl value is inserted into the input box with the % sign to the right of the numbers

### ✔️ Expected result
The % sign should be written to the left of numbers represented as percentages in most RTL languages

### ❌ Actual result

![image](https://github.com/ckeditor/ckeditor5/assets/71884380/775c909d-b512-4108-a88b-40f7d329ae05)

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! It won't be possible as this is a standard format in which `hsl` coloring is presented. If you wish, you can change the formatting via [the table properties](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_tableconfig-TablePropertiesConfig.html#member-colorPicker) to something like `rgb`.
