### ISSUE TITLE
Not able to Increase Hight of Editor

### ISSUE THREAD

**Issue by MohammedAdnankhan** [ckeditor/ckeditor5#15803]
<div style={{ height: "50vh" }}>
          <CKEditor
            editor={ClassicEditor}
            onReady={(editor) => {
              // console.log("Editor is ready to use!", editor);
            }}
            data={editorData}
            onChange={handleEditorChange}
            style={{ height: "50vh" }}
          />
        </div>
        
       This basic approach is not working

**Comment by Witoso** [comment]
Hi! This is not the way to do it, as we don't provide a style property in React integration. [Use stylesheets to affect the height](https://ckeditor.com/ckeditor-5/online-builder/).
