### ISSUE TITLE
Content is incorrect after pasting specific HTML

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1581]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Copy the following HTML:
```
<blockquote>A quote</blockquote><p>No quote</p>
```
2. Paste it to the editor.

## ✅ Expected result
The paragraph with `No quote` is outside of the quote.

## ❎ Actual result
The paragraph with `No quote` is inside the blockquote.

## 📃 Other details that might be useful
Related - https://github.com/ckeditor/ckeditor5/issues/1580

**Comment by Mgsy** [comment]
It's not a regression.

**Comment by Reinmar** [comment]
It's indeed not a regression. Strange, because it's very similar to https://github.com/ckeditor/ckeditor5/issues/1580.

Anyway, I think that both issues will be fixed at once, so I'm adding this one to the current iteration too.
