### ISSUE TITLE
Object literal may only specify known properties, and 'table' does not exist in type 'EditorConfig'.

### ISSUE THREAD

**Issue by AbineshDorustree** [ckeditor/ckeditor5#15832]
1. …After integration it in angular
2. …create a custom ckeditor for mentions.
3. …

### ✔️ Expected result

A normal running Angular application.

### ❌ Actual result

Class static side 'typeof Editor' incorrectly extends base class static side 'typeof ClassicEditor'.
  The types of 'defaultConfig.context' are incompatible between these types.
    Type 'import(".../CK editor/queue-management-system/Frontend/node_modules/@ckeditor/ckeditor5-core/src/context").default | undefined' is not assignable to type 'import(".../CK editor/queue-management-system/Frontend/node_modules/ckeditor5/node_modules/@ckeditor/ckeditor5-core/src/context").default | undefined'.
      Type 'import(".../CK editor/queue-management-system/Frontend/node_modules/@ckeditor/ckeditor5-core/src/context").default' is not assignable to type 'import(".../CK editor/queue-management-system/Frontend/node_modules/ckeditor5/node_modules/@ckeditor/ckeditor5-core/src/context").default'.
        Types of property 'config' are incompatible.
          Type 'import(".../CK editor/queue-management-system/Frontend/node_modules/@ckeditor/ckeditor5-utils/src/config").default<import(".../CK editor/queue-management-system/Frontend/node_modules/@ckeditor/ckeditor5-core/src/context").ContextConfig>' is not assignable to type 'import(".../CK editor/queue-management-system/Frontend/node_modules/ckeditor5/node_modules/@ckeditor/ckeditor5-utils/src/config").default<import(".../CK editor/queue-management-system/Frontend/node_modules/ckeditor5/node_modules/@ckeditor/ckeditor5-core/src/context").ContextCo...'.
            Types have separate declarations of a private property '_config'.

### ❓ Possible solution

Not yet found

## 📃 Other details

* Browser: …
* OS: …linux
* First affected CKEditor version: …5
* Installed CKEditor plugins: …41.0.0
![Screenshot from 2024-02-12 09-48-49](https://github.com/ckeditor/ckeditor5/assets/120079115/1ce6d05d-8679-4163-8bf7-3e9dddcd8011)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by AbineshDorustree** [comment]
This was working fine till last month, but after building it with the latest npm it is throwing an error.
And there were no code-level changes in it.

**Comment by AbineshDorustree** [comment]
Here is the finding on the previous working node_modules and current non-working node_modules

The interface EditorConfig is been mispointed  out in the generated node_modules package.

![Screenshot from 2024-02-13 16-27-57](https://github.com/ckeditor/ckeditor5/assets/120079115/12a563d0-2fbb-463e-bca9-e7983218d211)

![Screenshot from 2024-02-13 16-18-28](https://github.com/ckeditor/ckeditor5/assets/120079115/951e2cec-9798-4130-8e77-98888db69f6d)

**Comment by Witoso** [comment]
The new version \`41.0.0\` provides types with TypeScript 5.0, the screenshots that you provided are of little help TBH. Most likely, we would need some reproducible sample to dig into this. @filipsobol any thoughts?

**Comment by tranphuquy19** [comment]
I confirm that this issue has been resolved in the new version 41.1.0.

**Comment by AbineshDorustree** [comment]
> I confirm that this issue has been resolved in the new version 41.1.0.

Thanks for the breakthrough, we were using TypeScript 4.9.5 and the CKEditor version 41.0.0.

Once the "ckeditor5-editor-classic" version is been updated to 41.1.0 and the above issues have been resolved.

Thanks a lot, @Witoso   @tranphuquy19 Your input has been invaluable throughout this process. I especially appreciate your thorough testing and attention to detail. 🙌

**Comment by Witoso** [comment]
Hmm, I must say, I'm surprised the bump helped, as I cannot find any related work on our side, but I'm glad this is resolved. I'm closing, if anyone in the future will stumble upon this problem in some version, please comment, and we will reopen.
