### ISSUE TITLE
I am unable to get the attribute value of the selected text. Can someone suggest example for this issue.

### ISSUE THREAD

**Issue by Nadeem2299** [ckeditor/ckeditor5#15830]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_selection-Selection.html

### Project version

41.1.0

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Hi! Could you describe a bit more your use case? Selection is quite a tricky subject. I wonder as well what exactly you mean by the attribute value.

**Comment by Nadeem2299** [comment]
thanks its done
