### ISSUE TITLE
Template with fields to edit

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#1584]
I was wondering if there is a way to implement a template editing.
Basically what I want is to have is the possibility of creating/editing a template and lock it so that only certain parts of the document able to change.

Editor view result example:
```
<p contenteditable="false">Hi <span contenteditable="true" field="name">YOUR NAME</span>. Nice to meet you.</p>
```

The editable part would only allow simple text, all the styling is already done.

Is this possible?

**Comment by Mgsy** [comment]
Hi, @dkrahn! It's not possible to define templates in CKEditor 5. We have opened feature request for it, so it would be great if you could leave a comment [here](https://github.com/ckeditor/ckeditor5/issues/1585) and describe your use case.
