### ISSUE TITLE
Can't run tests due to outdated version of @ckeditor/ckeditor5-dev-tests

### ISSUE THREAD

**Issue by jonscheiding** [ckeditor/ckeditor5#15864]
## 📝 Provide detailed reproduction steps (if any)

1. Clone the repo fresh
2. Follow the [Development Environment guide](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/development-environment.html)
  1. Run `yarn install`
  2. Run `yarn run test --files=engine` 

### ✔️ Expected result

Tests run and pass

### ❌ Actual result

Several hundred errors of the form:

```
ERROR in ./packages/ckeditor5-utils/tests/_utils/utils.js 10:0-87
Module not found: Error: Can't resolve '../../src/areconnectedthroughproperties.js' in '/Users/jonscheiding/Code/ExamSpark/ckeditor5/packages/ckeditor5-utils/tests/_utils'
 @ ./packages/ckeditor5-engine/tests/view/treewalker.js 15:0-93 58:3-29 62:3-29 66:3-29 72:3-29
 @ ./build/.automated-tests/entry-point.js 5:0-105
```

### ❓ Possible solution

This is caused by the change made in 5c00fe1 and an outdated version of `@ckeditor/ckeditor5-dev-tests`. The `yarn.lock` file installs version 39.2.1 of that package, but the [change](https://github.com/ckeditor/ckeditor5-dev/commit/899c8e6964c7719944ff285c4d904f5fbab1bc0e) that fixes this issue was introduced in 39.5.1. When I forced my installed version to the latest, I could run the tests again.

## 📃 Other details

* Browser: n/a
* OS: MacOS
* First affected CKEditor version: 41.1.0
* Installed CKEditor plugins: n/a

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jonscheiding** [comment]
I see that the `yarn.lock` file is no longer tracked so I guess the solution to this is just delete and reinstall. If anybody wants to comment why that file was removed from git I'd be curious to know.

**Comment by pomek** [comment]
Related topics: #8087, #11500.
