### ISSUE TITLE
On adding plugins in ckeditor5 giving error.

### ISSUE THREAD

**Issue by g7crservice-Binni-kumari** [ckeditor/ckeditor5#15873]
This is my configuration where I need the ImageResize plugin for of course resizing the image that I have uploaded in the editor.
 
  import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
  
**Approch 1 -**

ckeConfig: any = {
    plugins: [ImageResize],
    image: {
      toolbar: [
        'imageStyle:alignLeft',
        'imageStyle:alignCenter',
        'imageStyle:alignRight',
        '|',
        'imageStyle:full',
        'imageStyle:side',
        '|',
        'imageTextAlternative',
      ],
      styles: ['full', 'side', 'alignLeft', 'alignCenter', 'alignRight'],
    },
    resizeOptions: [
      {
        name: 'resizeImage:original',
        value: null,
        label: 'Original',
      },
      {
        name: 'resizeImage:40',
        value: '40',
        label: '40%',
      },
      {
        name: 'resizeImage:60',
        value: '60',
        label: '60%',
      },
    ],
    toolbar: [
      'resizeImage',
      'underline',
      'Source',
      'undo',
      'redo',
      '|',
      'heading',
      'fontFamily',
      'fontSize',
      '|',
      'bold',
      'italic',
      'fontColor',
      'fontBackgroundColor',
      'highlight',
      '|',
      'link',
      'imageUpload',
      '|',
      'alignment',
      'bulletedList',
      'numberedList',
      '|',
      'indent',
      'outdent',
      '|',
      'insertTable',
      'blockQuote',
    ],
    language: 'id',
 
  };

  
  **Approach 2 -** 
  
    ngOnInit() {
    const ckeditorElement = document.querySelector(
      '#myckeditor'
    ) as HTMLElement | null;
    if (ckeditorElement) {
      ClassicEditor.create(ckeditorElement, {
        plugins: [ImageResize],
      })
        .then((newEditor) => {
          this.ckEditorInstance = newEditor;
        })
        .catch((error) => {
          console.error(error);
        });
    } else {
      console.error('CKEditor element not found');
    }
  }

### ✔️ Expected result

_At least on dragging the image resize should happen, or on fixed value with dropdown._

_What is the expected result of the above steps?_

### ❌ Actual result

Getting only alignment tools.

_What is the actual result of the above steps?_

PF image Attached of what error I am getting from both approaches.

<img width="923" alt="Screenshot 2024-02-19 120713" src="https://github.com/ckeditor/ckeditor5/assets/98733632/33c97a39-c576-4d27-adf8-011c5db68a1a">

### ❓ Possible solution

No Idea.. But there should be some solution there, why Ckeditor5 get released when there is no proper solution in their documents? I got most of the solutions from different platforms, ckeditor5 docs not helping.

## 📃 Other details

* Browser: … Windows
* OS: …
* First affected CKEditor version: … 
* Installed CKEditor plugins: …

 "@ckeditor/ckeditor5-angular": "^7.0.1",
 "@ckeditor/ckeditor5-build-classic": "^41.1.0",
 "@ckeditor/ckeditor5-image": "^41.1.0",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by g7crservice-chinmayee-hanashi** [comment]
Facing same issue is there any way to solve these?

**Comment by Witoso** [comment]
> "@ckeditor/ckeditor5-build-classic": "^41.1.0",
 
You're trying to add a plugin to [a predefined build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html) which is not possible. A [custom build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#creating-custom-builds-with-online-builder) needs to be prepared if you want to add additional plugins.
