### ISSUE TITLE
ckeditor5-image augmentation not "resolved" when using moduleResolution NodeNext

### ISSUE THREAD

**Issue by Sanderovich** [ckeditor/ckeditor5#15880]
## 📝 Reproduction details

I created a repository to demonstrate the bug https://github.com/Sanderovich/ckeditor5-41.1-module-resolution-reproduction. See the commits for the working situation and the reproduction.

Currently, I am updating CKEditor 5 version 40.2 to 41.1, and I am getting Typescript errors when getting the ImageUtils. `const imageUtils = this.editor.plugins.get('ImageUtils') // results in type PluginInterface` (See repo, file src/ckeditor.ts, line 41, error reproduction state). I have found that the errors could be caused by the moduleResolution setting in our tsconfig.ts. Currently, it is on NodeNext, and when I change it to bundler, Typescript is happy. However, this has never been a problem before, and we have the preference to keep using NodeNext

### ✔️ Expected result

`this.editor.plugins.get('ImageUtils')` resulting in a `ImageUtils` type.

### ❌ Actual result

`this.editor.plugins.get('ImageUtils')` resulting in a `PluginInterface` type.

### ❓ Possible solution

Something that worked for me is to change the import in `@ckeditor5/ckeditor5-image/src/augmentation.d.ts`  to import from '`/index.js'`instead of  `'.'`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Fix present in the next release.
