### ISSUE TITLE
Confusing behavior of CKEditor 5 when launching the editor on a <textarea> element

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1591]
There are several places where we show an example of Classic editor being launched on top of a `<textarea>` element:

 * https://cdn.ckeditor.com/#ckeditor5
 * https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html#classic-editor

If someone takes such an example and later tries to change the editor type (e.g. the Balloon editor), then will see that the editor no longer shows up:

```html
<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <title>CKEditor</title>
                <script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/balloon/ckeditor.js"></script>
        </head>
        <body>
                <textarea name="content" id="editor">This is some sample content.</textarea>
                <script>
                        BalloonEditor
                                .create( document.querySelector( '#editor' ) )
                                .then( editor => {
                                        console.log( 'hello' );
                                        console.log( editor );
                                        console.log( editor.getData() );
                                } )
                                .catch( error => {
                                        console.error( error );
                                } );
                </script>
        </body>
</html>
```

## Result in a browser:

![screenshot 2019-03-04 at 17 48 49](https://user-images.githubusercontent.com/545175/53748613-f906a900-3ea5-11e9-9f79-cf30c05f007d.png)

## Expected result

1. <a href="https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-balloon_ballooneditor-BalloonEditor.html#static-function-create">BalloonEditor.create()</a> documentation could mention if there are any limitations on what can be passed as ` sourceElementOrData` argument.

2. The editor could log some meaningful error into the console when unsupported element is passed.

**Comment by Reinmar** [comment]
Related issues:

* https://github.com/ckeditor/ckeditor5-editor-inline/issues/3
* https://github.com/ckeditor/ckeditor5-editor-inline/issues/5

Also, I'd remove all mentions of `<textarea>` from the docs, except one page where it makes sense: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#automatic-integration-with-html-forms

**Comment by Reinmar** [comment]
@wwalc, I know that it's you in https://stackoverflow.com/questions/55142625/creating-decouplededitor-passing-textarea-as-parameter :D I don't believe in such coincidences ;)

**Comment by vinkann** [comment]
Reached here with a google search. So CKEditor5 won't support if used with <textarea> tag is it?

**Comment by sidrakshe28** [comment]
I want the output of the Ckeditor in a different textarea ,but it's getting displayed with html tags. any idea how to avoid that?
