### ISSUE TITLE
Clean stable branch yields React dependency errors

### ISSUE THREAD

**Issue by alexc-pub6** [ckeditor/ckeditor5#15920]
## 📝 Provide detailed reproduction steps (if any)

1. Checkout Stable branch
2. Go to the decoupled document package
3. Run npm install

### ✔️ Expected result

No Errors

### ❌ Actual result
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: ckeditor5@41.1.0
npm ERR! Found: dev @ckeditor/ckeditor5-react@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @ckeditor/ckeditor5-react@"^6.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
```

### ❓ Possible solution

Downgrading to version 38.1.1 works. All versions below that don't run. My guess is that, maybe, a dependency down the chain might depend on a different node version?

## 📃 Other details

* Browser: …
* OS: Windows 10
* First affected CKEditor version: stable branch
* Installed CKEditor plugins: none
* node version: 18.19.0

I have to be honest: CKEditor5 not building correctly is the expectation for me at this point, and not the norm. It seems like every single time I go to build a clean stable branch (i.e. every few months), something new is broken.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! We are not using internally `npm` but `yarn` so we are not testing regularly how the repository works with other package managers. My suggestion would be to switch to `yarn` or try `npm` with `--legacy-peer-deps` as `npm` has some real troubles with resolving peer deps.

**Comment by qiqicat** [comment]
Not solved yet

**Comment by Witoso** [comment]
Please read my comment, and let me know if the proposal doesn't work.

**Comment by DeltekDavid** [comment]
Was just bitten by this when trying to build from source in order to use real-time collab. The [docs page](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration-integration.html) uses `npm`. I tried `--legacy-peer-deps` and then `--force`, but no luck.

**Comment by DeltekDavid** [comment]
Update: Tried running `yarn` from the `stable` branch and it worked :D

Can you update your docs page to recommend `yarn` and avoid this pain point? Thanks.
