### ISSUE TITLE
Docs issue report from "tutorials/crash-course/model-and-schema.html"

### ISSUE THREAD

**Issue by thienquach** [ckeditor/ckeditor5#15922]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/tutorials/crash-course/model-and-schema.html

### Project version

41.1.0

### Is the information outdated? How?

Then, when the [**model**.getData()](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_utils_dataapimixin-DataApi.html#function-getData) method is called, the model is converted back to HTML.
********
model.getData() should be editor.getData()

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Thanks!
