### ISSUE TITLE
Copying content with comment marker triggers `change:data`

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#15943]
## 📝 Provide detailed reproduction steps (if any)

It is better visible if you configure comments to copy markers on copy-paste (`config.comments.copyMarkers: [ 'cut', 'copy' ]`). 

1. Create some content and add marker on it.
2. Select some content so that markers intersects with the selection (or is inside).
3. Ctrl+C

### ✔️ Expected result

Nothing happens.

### ❌ Actual result

1. Autosaved is triggered.
2. Empty undo step is created.
3. Other callbacks may be called unnecessarily.

## 📃 Other details

This is probably due to the fact that we temporarily insert `$marker` elements into the content. I hoped that `change:data` will not fire because in the end there are no real changes in the differ (the element is added and removed in the same batch). So either differ works differently than I thought, or something extra happens.

**Comment by michalbilik** [comment]
## Comment markers pasted into a table even when a marker already exists in the table

### Steps
1. Open a manual test with comments - e.g. [all-features-rtc.html](http://localhost:8125/ckeditor5/external/ckeditor5-commercial/packages/ckeditor5-collaboration/tests/manual/all-features-rtc.html).
2. Set copyMarkers: 'default'.
3. Comment Cell 1.1.
4. Use `cmd + x` to cut Row 1.
5. Use Undo.
6. Select Column 2 and paste content.

### Result
Comments are duplicated

https://github.com/ckeditor/ckeditor5/assets/50703222/561d471e-61fe-4a77-bda2-ea5b2d98bdcb
