### ISSUE TITLE
The "Powered by CKEditor" logo is displayed after upgrading to CKEditor v41

### ISSUE THREAD

**Issue by joyfeel** [ckeditor/ckeditor5#15951]
## 📝 Provide detailed reproduction steps (if any)

I have obtained a commercial license, and the logo is not displayed for versions prior to v41. 
But after upgrading to v41, it shows up.

![Screenshot 2024-02-29 at 12 32 12 pm](https://github.com/ckeditor/ckeditor5/assets/5734920/250dc62d-fa5e-4a25-bbea-df2d9f550ad3)

### ✔️ Expected result

The logo should not be displayed for customers with commercial licenses.

### ❌ Actual result

The logo is displayed after upgrading CKEditor v41

**Comment by Witoso** [comment]
Hi! Please reach out to [our support](https://ckeditor.com/contact/), as we need to ask a few follow-up questions. Thank you!
