### ISSUE TITLE
Nested lists sometimes broken when pasting from Word

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15964]
## 📝 Provide detailed reproduction steps (if any)

1. Download the sample files: [broken-list.docx](https://github.com/ckeditor/ckeditor5/files/14479654/broken-list.docx), [working-list.docx](https://github.com/ckeditor/ckeditor5/files/14479655/working-list.docx)
2. Paste the contents into the [Paste from Office Enhanced demo](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html#demo)
3. Compare the results

### ✔️ Expected result

The subitems should be retained when pasting the contents of the first file, as is the case in CKE4, for example:

![image](https://github.com/ckeditor/ckeditor5/assets/72079603/e60e5ee9-d89c-4e06-ae3a-98736a77b435)

### ❌ Actual result

The first two subitems change into regular list items and move to the bottom of the document:

![image](https://github.com/ckeditor/ckeditor5/assets/72079603/bafddb5e-6276-4106-b40f-f8088926d2e8)

### ❓ Possible solution

I wasn't able to reproduce this behavior with a fresh Word file (working-list.docx). Not sure what the difference is between these two lists.

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by filipsobol** [comment]
When pasting content from Office, we detect list items when they are `<p>` or `<h1>` to `<h6>` elements with a `mso-list` style. This works fine in `working-list.docx` document from above, as all items are `<p>` tags.

However, for whatever reason, the first **nested** list in `broken-list.docx` is a `<ul>` with `<li>` elements. This does satisfy our [current requirements](https://github.com/ckeditor/ckeditor5/blob/f8c1f21ac8061f35e9639dfa4ae5416ffcdb8fd3/packages/ckeditor5-paste-from-office/src/filters/list.ts#L125-L130).

Simply adding `li` to the RegExp detects bunch of other elements as list items, so this needs further investigation.

**Comment by dgibbons** [comment]
I have found another document from a different source that has a similar but different problem. In this case, several of the bullets are re-ordered in the document.

Here is a screenshot of the behaviour:

<img width="1917" alt="Screenshot 2024-03-04 at 3 25 58 PM" src="https://github.com/ckeditor/ckeditor5/assets/479823/b7aac214-9a43-44fe-a53b-24618b654936">

Note that this appears to be a bug with the "paste from office enhanced" plugin, as the "without paste from office enhanced" plugin is not showing this issue. Paste from office enhanced is not getting the bullet nesting correct, however.

CK4 gets the order correct, and the nesting correct:

<img width="1332" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/479823/c9dd0fe0-43b4-416d-ad14-51338738aadc">



Ideally the Paste from Office plugin would work as well as CK4 does here.

Test word doc here: [Missing bullets example.docx](https://github.com/ckeditor/ckeditor5/files/14499626/Missing.bullets.example.docx)
