### ISSUE TITLE
[Windows Edge] encountered TypeError: Cannot convert undefined or null to object while using CKEditor

### ISSUE THREAD

**Issue by 12306ylg** [ckeditor/ckeditor5#15962]
### ✔️ Expected result

_editor display correctly _

### ❌ Actual result

_build id "t50r9gqt9aih-gr5fbyqgqtlm" and the error stack trace:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SA.init (***\webpack\universalModuleDefinition:1:1)
    at SA.<anonymous> (***\webpack\universalModuleDefinition:1:1)
    at SA.fire (***\webpack\universalModuleDefinition:1:1)
    at <computed> [as init] (***\webpack\universalModuleDefinition:1:1)
    at file:///***/ckeditor/build/ckeditor.js:5:1069830 {name: 'CKEditorError', context: SA, data: undefined, stack: 'TypeError: Cannot convert undefined or null t…vent2023/ckeditor/build/ckeditor.js:5:1069830', message: 'Cannot convert undefined or null to object
R…r-Cannot convert undefined or null to object'}
_

## 📃 Other details

* Browser: Edge
* OS: Windows
* First affected CKEditor version: 41.1.0
* Installed CKEditor plugins: 
                Alignment,
		AutoLink,
		Autoformat,
		Base64UploadAdapter,
		BlockQuote,
		Bold,
		CodeBlock,
		Essentials,
		FindAndReplace,
		FontColor,
		FontSize,
		FullPage,
		GeneralHtmlSupport,
		Heading,
		Highlight,
		Image,
		ImageCaption,
		ImageStyle,
		ImageToolbar,
		ImageUpload,
		Indent,
		Italic,
		Link,
		List,
		Markdown,
		MediaEmbed,
		Paragraph,
		PasteFromOffice,
		ShowBlocks,
		Table,
		TableToolbar,
		TextTransformation,
		Undo

---

**Comment by Witoso** [comment]
Hi! There's too little information to start debugging, please provide additional information about your setup, and best, some reproducible minimal sample.

**Comment by 12306ylg** [comment]
Thanks, I found that **putting the ckeditor.js reference after the textarea** solved it.
