### ISSUE TITLE
[Docs] Does CRA2 still require replacing webpack.optimize.UglifyJsPlugin? 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1597]
![image](https://user-images.githubusercontent.com/156149/53875318-8c55f080-4004-11e9-8156-5eefcb5618f2.png)

Is it still needed? Could we review the guide and move all pieces which are required for CRA1 to a separate section at the end?

**Comment by pomek** [comment]
I've just checked, production build (`yarn/npm run build`) does not throw any error and the built application works fine if a user will use ready-to-use build. It can be one of our builds or a totally custom build.

I will let you know what about using CKEditor 5 Framework inside the CRA.

**Comment by pomek** [comment]
This guide needs to be improved. CRA@2 has an only single webpack configuration that could be more complicated to editing than CRA@1.

**Comment by pomek** [comment]
I have an answer to the question:

> Is it still needed? Could we review the guide and move all pieces which are required for CRA1 to a separate section at the end?

No, it isn't. But we need to create two separate sections (guides) for both CRA versions. The existing one is fine. I will move it at the end of the guide and write another one for CRA@2.
