### ISSUE TITLE
CKEditor production build contains >200kB unneeded strings 

### ISSUE THREAD

**Issue by tuomassalo** [ckeditor/ckeditor5#15986]
## 📝 Provide detailed reproduction steps (if any)

1. Build Ckeditor or grab a pre-built version
2. Inspect what `ckeditor.js` contains

### ✔️ Expected result

The production build of `ckeditor.js` should be strictly optimized for production, containing minimal amount of sourcemaps and other information only useful for debugging.

### ❌ Actual result

The production build seems to contain at least:

- unminimized source code of all css files (>200kB)
- `mappings` strings

Verify this by searching for e.g. `Copyright` in e.g. https://raw.githubusercontent.com/ckeditor/ckeditor5/e2e1d8be40b3dfa69cfd84cfbfb027b0f5d6b02f/packages/ckeditor5-build-inline/build/ckeditor.js
or https://ckeditor.com/assets/libs/ckeditor5-external/ck-demo-external-feature-rich-a54efe2a01.js - use should find unminimized CSS strings and long mappings strings such as `mappings:"AASA,sDAEC,yFAAoG[...]"`.

### ❓ Possible solution

Tweak the build process (webpack config?) to only include minimal data (`//# sourceMappingURL=...`?) in the production build file.

Is this possible with the current webpack based build system?

## 📃 Other details

* Browser: N/A
* OS: N/A
* First affected CKEditor version: Quick bisecting shows that for InlineEditor, v32 is the first version that contains these strings. The production build jumps from 758k ([v31](https://raw.githubusercontent.com/ckeditor/ckeditor5/v31.0.0/packages/ckeditor5-build-inline/build/ckeditor.js)) to 967k ([v32](https://raw.githubusercontent.com/ckeditor/ckeditor5/v32.0.0/packages/ckeditor5-build-inline/build/ckeditor.js)).
* Installed CKEditor plugins: N/A

With current `master`, I tried removing all `sourcesContent` and `mappings` entries in `packages/ckeditor5-build-inline` with this quick and dirty oneliner (please close your eyes, it's horrible):

    cp build/ckeditor.js build/ckeditor.js.orig
    perl -pe 's/,sourcesContent:\[ ( ( "(\\.|[^"])*?" ,? ) | ( '"'"'(\\.|[^'"'"'])*?'"'"' ,? ))+\]//gx; s/,mappings:"[^"]*"//g' < build/ckeditor.js.orig > build/ckeditor.js

This reduces the file size by about 250 kB, from 1269710 to 1019133 bytes. (Gzip compressed size is reduced by about 51 kB). Everythings in the actual editor *seems* to work, but debugging support is probably affected.

NB: Possibly there are also other things than `sourcesContent` and `mappings`, too. I didn't get into the details.

Since this issue has been around for about three years, I expected finding issues and discussion on bundle size optimization. I only found these: https://github.com/ckeditor/ckeditor5/issues/435 and https://github.com/ckeditor/ckeditor5/issues/14280.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! Thanks for the request. The majority of the work in relation to this problem is happening in the #15502 which will introduce the new installation methods, as well as will put the predefined builds on the deprecation path. It will also strip the editor of styles, which will be provided via an additional stylesheet file.

@filipsobol is closely [monitoring the sizes](https://github.com/ckeditor/ckeditor5/issues/15708#issuecomment-1959401764), in relation to different bundlers, and we will also provide minified browser build.  
  
Follow the RFC for the latest updates, soon we should have `alpha` release.

**Comment by filipsobol** [comment]
The predefined builds (which this issue concerns) and other legacy installation methods are on the deprecation path. For this reason, we will not update the configuration for generating predefined builds, so as not to risk breaking them.

We recommend that you migrate to the [new installation methods introduced in 42.0.0](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-42.html), which do not have the problem described in this issue.
