### ISSUE TITLE
Watchdog crashes when `destroy` is called before finishing the editor initialization

### ISSUE THREAD

**Issue by DawidKossowski** [ckeditor/ckeditor5#15980]
## 📝 Provide detailed reproduction steps (if any)

1. Call `watchdog.create` without waiting for the processing to finish.
2. Call `watchdog.destroy()`.

### ✔️ Expected result

Editor is destroyed.

### ❌ Actual result

TypeError: Cannot read properties of null (reading 'model')

### ❓ Possible solution

Watchdog should wait for the completion of the creation process before initiating destruction.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Rel: ckeditor/ckeditor5-react#370

**Comment by glynam1** [comment]
This still occurs in context watchdog. I think this should reopened, or a ticket created for the context use case specifically.

![Screenshot 2024-04-17 at 13 56 35](https://github.com/ckeditor/ckeditor5/assets/91141450/1d9e5ef9-b45d-42b8-82f5-b54831b89239)

**Comment by DeltekDavid** [comment]
I'm getting this as well in `v41.3.1`. We aren't using watchdog, but we're trying out the real-time collab. We get this on render:
![image](https://github.com/ckeditor/ckeditor5/assets/143453251/7ea1e264-864c-4262-844f-5f3bf39ab928)
