### ISSUE TITLE
Widgets (Including the widget demo) throws Uncaught CKEditorError: undefined has no properties

### ISSUE THREAD

**Issue by mtilsted** [ckeditor/ckeditor5#15996]
## 📝 Provide detailed reproduction steps (if any)

Open the inline widget demo:
https://ckeditor.com/docs/ckeditor5/latest/tutorials/widgets/implementing-an-inline-widget.html#demo

Paste some extra text into the editor. I used the history section from https://en.wikipedia.org/wiki/MOS_Technology_6581

Now grab the "First name" widget,  and drag it around in circles without letting it go.

At one point, typical within a minute, the editor throws 

### ✔️ Expected result

No exception

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Dup: #15997
