### ISSUE TITLE
Pasting image from link in CKBox throws an error

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#15990]
Images that are predefined in docs and uploaded via URL (both from toolbar and AutoImage) are not CKBox Image Editable. The button is greyed out. Images uploaded from disk and from CKBox work alright.

No errors in the console, so this must be configuration thing.

CKBox team suggests it's on the CKE5 side.

---

Originated from

I got this error when pasting a link for an image instead (paste alright) and trying to edit it:  

![](https://github.com/ckeditor/ckeditor5/assets/68123541/a29cab2c-1244-40ef-9de5-1c57792a9e7b)

@mpytel-cksource - any ideas where to start with it? Is this, again, permission problem?

It also throws `Failed to determine category of edited image.`

The permissions are `allowExternalImagesEditing: [ /^data:/, 'origin', /ckbox/ ]`

_Originally posted by @godai78 in https://github.com/ckeditor/ckeditor5/pull/15932#discussion_r1510629769_

**Comment by godai78** [comment]
In reply to: [https://github.com/ckeditor/ckeditor5/pull/15932#discussion_r1514101503](https://github.com/ckeditor/ckeditor5/pull/15932#discussion_r1514101503)

Isn't there, like, default category? It only happens with images from links.

**Comment by arkflpc** [comment]
The exception seems not reproducible.
However, the behavior is by design. The images pasted via URL are not fetchable in general, because of same-origin policy. The domains, known to have CORS setup allowing the fetch, should be specified in `ckbox.allowExternalImagesEditing`.
