### ISSUE TITLE
Improvements to the editor with multiple roots example and guide

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1599]
A follow–up of 
* https://github.com/ckeditor/ckeditor5/pull/1586#discussion_r262557133 
* https://github.com/ckeditor/ckeditor5/pull/1586#discussion_r262558374.

cc @pjasiun @f1ames 

As for https://github.com/ckeditor/ckeditor5/pull/1586#discussion_r262862775

> If you want to change it, that's fine, but TBH I like it this way. It stresses the fact that this is a single editor.

The user does not care what's underneath. They navigate and fill the text in a **form** and the expect things to behave like a form. They focus one field at a time and they expect just a single field to be visually focused. 

Besides, this way it's very hard to tell which editable (form field) is focused (Where's my caret? Am I typing the email address or the message yet?).

**Comment by pjasiun** [comment]
It is fine for me to focus one element. But to clarify what I meant:

> The user does not care what's underneath.

I believe that there was a reason why it was created as a single multi-root editor, not by multiple separated editor. And I believe that the reason was to provide the single-editor experience. This is why I suggest that the editor should act like this - like a single editor.

> Besides, this way it's very hard to tell which editable (form field) is focused (Where's my caret? Am I typing the email address or the message yet?).

That's a good point, in fact.

**Comment by oleq** [comment]
Anyway, check out screencasts in https://github.com/ckeditor/ckeditor5/pull/1600#issuecomment-470165214.

**Comment by oleq** [comment]
I'd give the toolbar some space because now it looks like it belongs to the first root only 
![image](https://user-images.githubusercontent.com/1099479/53895683-d8b82500-4032-11e9-8e41-640282f172ca.png)

WDYT?

**Comment by Reinmar** [comment]
Isn't this ticket a DUP of https://github.com/ckeditor/ckeditor5/issues/1596 (or vice versa)?

**Comment by oleq** [comment]
This one is a DUP but since there's a lot going on here, I marked the other one as DUP.
