### ISSUE TITLE
Font and Text Alignment plugins should not require unsafe-inline in the Content-Security-Policy

### ISSUE THREAD

**Issue by kglickman** [ckeditor/ckeditor5#16004]
Your documentation states that the font and text-alignment plugins are not supported without unsafe-inline in the CSP.  Our product must not require unsafe- inline so we are forced to disable these plugins that our customers have come to expect.

According to this comment, https://github.com/ckeditor/ckeditor5/issues/15509#issuecomment-1876800147, it looks like it wouldn't be that difficult to fix the problem, and it would be a huge, huge improvement for us and everyone else who wants to have a strict CSP.

**Comment by Witoso** [comment]
I think the issue you linked was not closed correctly, let's treat it as main ticked. We don't have this in our immediate plans, but I will keep it in the loop in #15979, maybe we will squeeze it in there.
