### ISSUE TITLE
"View Source" feature request again.

### ISSUE THREAD

**Issue by bs-thomas** [ckeditor/ckeditor5#1601]
## Is this a bug report or feature request? (choose one)

🆕 Feature request 

## 💻 Version of CKEditor

As the other ticket #592 is locked, and #629 is closed, I'd hope to open a new ticket here express my interest in the popular "View Source" feature in CKEditor 4 and older versions.

We operate a web design firm here, and build CMS systems for our clients.  In general, we limit our clients to only some basic CKEditor features, but us as super admin, we have a special privileged login to access advanced features such as View Source, so that in case our client messes something up really badly, we can follow this up and debug their work by looking at the actual generated source.

The generated source is also a confirmation for us to ensure that the HTML being saved is "semantic" and "SEO-friendly".  Just by looking at the WYSIWYG editor, I cannot confirm this.

So I feel that it is important for advanced users to have this feature, and has always been one of the most popular features in CKEditor 4 and below.

You guys have been great for developing a great tool like this, and I really appreciate this a lot and want to say thank you.

This is really a mandatory feature for us here, and without this, we cannot manage our clients.  We do not want to give up the CKEditor / CKFinder combo, as we use that for almost every project at our company.  Without this, we would have to seek for an alternative, and it's not easy to find an alternative editor with all of these nicely integrated features in one bundle.

I sincerely hope you guys will reconsider the decision of dropping such an important feature on CKEditor 5.

For everyone who thinks the same way as I do, please kindly give this issue a thumbs up, or +1.  And no abusive language please because it's irrelevant and I don't want to see this thread being locked again.

Thanks guys!

**Comment by Reinmar** [comment]
Hi Thomas! To keep all the discussion in one place, I'll reply to you in https://github.com/ckeditor/ckeditor5/issues/592 and unlock this thread.
