### ISSUE TITLE
Move Install and Configuration sections in docs

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#16011]
In all guides that sport both the Installation and Configuration section, move the former over the latter to make more sense.

**Comment by Witoso** [comment]
I think we can either look at this in a chronological order of setup:

1.  Install
2.  Config

Or make some assumption about the user who is visiting those pages:

1.  That they already have the plugin/feature (coming from builder maybe, demos, or some other ecosystems like Drupal)
2.  They are mostly interested in config options they have.

Usually installation sections are short, so I wouldn't be worried about changing the order, more worried about longer ones that would move config quite low.

Thoughts?

**Comment by godai78** [comment]
The long ones are usually because of some special config needs. The really long ones are often split into a separate guide. It's judge 90% install sections are now a single paragraph + a snippet + infobox.

**Comment by godai78** [comment]
Looks like plenty of guides already employ the Install > Config order.
