### ISSUE TITLE
Can you publish a page created with ckeditor.

### ISSUE THREAD

**Issue by tgmueller** [ckeditor/ckeditor5#1603]
After content has been created with CK edit, how would the end user publish this page.  I don't want website viewers to have access to the the edit boxes.  Sorry if this is the wrong place to ask.  

By the way, this is really cool!

## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
Hello, CKEditor 5 is a rich-text editor for creating content. Saving/displaying it on the website lays on the user's side. 

Take a look at our [documentation page](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/intro.html) to get familiar with the architecture and data model, so you'd be able to understand how you should handle the content created with CKEditor 5.
