### ISSUE TITLE
Docs issue report from "framework/deep-dive/upload-adapter.html"

### ISSUE THREAD

**Issue by ngraczyk** [ckeditor/ckeditor5#16042]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/upload-adapter.html

### Project version

41.2.0

### Is there anything else you would like to add?

In the Superbuild version it is not possible to use the MyCustomUploadAdapterPlugin. The following function does not get called:

`editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
       return new MyUploadAdapter( loader );
};`

If we use the ClassicEditor version or one of the other prebuild versions the function gets called as expected and we are able to implement a custom upload adapter.

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Hi! You need to remove already present adapter `Base64UploadAdapter` via `removePlugins`.

Important mention, soon the predefined builds will be marked as legacy, and a new installation method will be present. #15502.
