### ISSUE TITLE
Export a few more types/classes from the mention package

### ISSUE THREAD

**Issue by Cyperghost** [ckeditor/ckeditor5#16044]
## 📝 Provide a description of the new feature
There are currently no exports for a few types and classes that can be used in other auto-completion features similar to the mention auto-completion.
These types/classes are interesting
```
MentionsView from "@ckeditor/ckeditor5-mention/src/ui/mentionsview";
MentionFeedObjectItem from "@ckeditor/ckeditor5-mention/src/mentionconfig";
MentionListItemView from "@ckeditor/ckeditor5-mention/src/ui/mentionlistitemview";
DomWrapperView from "@ckeditor/ckeditor5-mention/src/ui/domwrapperview";
```

_What is the expected behavior of the proposed feature?_
We would use this to create our own auto-completion for others, then mention, but not completely rewrite everything.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the request! @arkflpc @filipsobol , I'm not sure if we need to investigate this further, or just add it?

**Comment by filipsobol** [comment]
I'm not too familiar with this feature, so I can't make the final call, but in general I see no reason why we shouldn't do this.
