### ISSUE TITLE
Headless editor still requires css/svg loaders

### ISSUE THREAD

**Issue by stonebk** [ckeditor/ckeditor5#16045]
## 📝 Provide detailed reproduction steps

I am trying to build an editor with a completely custom UI following the [Headless editor demo](https://ckeditor.com/ckeditor-5/demo/headless/). Unfortunately, I'm running into build issues due to various *.css and *.svg imports in the index files that the decoupled editor imports from.

### ✔️ Expected result

Using `@ckeditor/ckeditor5-editor-decoupled` should not require any special css/svg loaders or loader configuration.

### ❌ Actual result

![Screenshot 2024-03-15 at 11 51 09 AM](https://github.com/ckeditor/ckeditor5/assets/1432010/8464511b-114a-4a5f-a162-239a9aa16023)

![Screenshot 2024-03-15 at 11 51 39 AM](https://github.com/ckeditor/ckeditor5/assets/1432010/4ba6f84f-33aa-4ee2-8f7a-04419cde22dd)

### ❓ Possible solution

I believe the problem stems from imports like these in [decouplededitor](https://github.com/ckeditor/ckeditor5/blob/54eae6a1bb1a72d42f00b43fcf7f7f0b167507ba/packages/ckeditor5-editor-decoupled/src/decouplededitorui.ts#L10-L17):

```
import {
	type Editor
} from 'ckeditor5/src/core.js';

import {
	EditorUI,
	type EditorUIReadyEvent
} from 'ckeditor5/src/ui.js';
```

Even though decouplededitor doesn't use any of the css or svgs provided by core.js or ui.js, those rollup files [reference a lot of those files](https://github.com/ckeditor/ckeditor5/blob/54eae6a1bb1a72d42f00b43fcf7f7f0b167507ba/packages/ckeditor5-core/src/index.ts#L45-L120). Decouplededitor could import from a more direct path rather than using the index rollup to avoid the need to handle *.css or *.svg files that are never used, for example:

```diff
  import {
  	type Editor
+ } from 'ckeditor5/src/editor/editor.js';
- } from 'ckeditor5/src/core.js';
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
The issues you see will be resolved in #15502, when the editor won't be webpack-dependent and CSS will be stripped to a separate file.#15502, when the editor won't be webpack-dependent, and CSS will be moved to a separate file.

**Comment by stonebk** [comment]
Great to hear @Witoso! Should the alpha already be addressing these issues? I just tried out `41.3.0-alpha.1` and the same errors exist.

**Comment by Witoso** [comment]
> Should the alpha already be addressing these issues? I just tried out 41.3.0-alpha.1 and the same errors exist.

Yes, it should. I would need additional information about your setup to see what's wrong. Here's [an example webpack setup](https://github.com/ckeditor/new-installation-methods/tree/main/webpack).

**Comment by stonebk** [comment]
> > Should the alpha already be addressing these issues? I just tried out 41.3.0-alpha.1 and the same errors exist.
> 
> Yes, it should. I would need additional information about your setup to see what's wrong. Here's [an example webpack setup](https://github.com/ckeditor/new-installation-methods/tree/main/webpack).

Nice, I got it to work by importing everything from `ckeditor5` rather than from the `@ckeditor/ckeditor5-*` packages!

**Comment by Witoso** [comment]
Great! I will close this one, and follow #15502 for release information.
