### ISSUE TITLE
Configure italic button style generation

### ISSUE THREAD

**Issue by gfoo** [ckeditor/ckeditor5#1606]
Hi,
is there a quick way [like in CKEditor 4](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-coreStyles_italic) to configure the Italic button to generate `<em>` instead of `<i>`?
thanks

**Comment by oleq** [comment]
You need another converter for that

```js
editor.conversion.for( 'downcast' ).attributeToElement( {
	model: {
		key: 'italic',
	},
	view: {
		name: 'em'
	}
} );
```

You can load it as a plugin:

```js
function ItalicAsEm( editor ) {
    editor.conversion.for( 'downcast' ).attributeToElement( ... );
}   

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [
			// ...
			ItalicAsEm
			// ...
		]
	} );
```

**Comment by gfoo** [comment]
Using a [custom built editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html), prefer to use `extraPlugins` config:
```typescript
config = {
    extraPlugins: [ItalicAsEm],
   // ...
}
```

Many thanks.
