### ISSUE TITLE
Vitest + Vite: test failed with "Unknown file extension ".svg" "

### ISSUE THREAD

**Issue by ArutaGerman** [ckeditor/ckeditor5#16075]
## 📝 Provide detailed reproduction steps (if any)

1. I use Vue.js v3 + Vite v5.0.11 + Vitest v1.3.1
2. I run a unit test and all tests with CkEditor5 will be canceled with an error.

### ✔️ Expected result

Unit test pass successfully

### ❌ Actual result

TypeError: Unknown file extension ".svg" for C:\projectFolder\node_modules\@ckeditor\ckeditor5-core\theme\icons\cancel.svg

## 📃 Other details

I tried to run tests with CkEditor5 v41.2.1 and v34.2.0.
With v34.2.0 all tests pass successfully, but with 41.2.1 I have the error.

* First affected CKEditor version: 41.2.1 (maybe not 41.2.1, but I only tried with this)
* Installed CKEditor plugins: 
![image](https://github.com/ckeditor/ckeditor5/assets/48782221/0cd6692f-58f0-4447-9a9d-bbebcd0391c3)

editorComponent: 

```
<template>
        <ck-editor
          ref="editor"
          :model-value="localValue"
          :editor="editor"
          :config="editorConfig"
          @ready="onReady"
          @update:model-value="emitValue"
        />
</template>

<script>
import { DecoupledEditor } from '@ckeditor/ckeditor5-editor-decoupled';
import config from './ckeditorBuildConfig';

export default {

  data() {
    return {
      editor: DecoupledEditor,
      editorConfigBase: {
        ...config,
        formId: this.formId,
      },
      localValue: this.modelValue,
    };
  },
}
```

Ttests don't fail, if delete the raw `import { DecoupledEditor } from '@ckeditor/ckeditor5-editor-decoupled';`

For webpack we have this code in the docs:

```
config.module
            .rule( 'cke-svg' )
            .test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
            .use( 'raw-loader' )
            .loader( 'raw-loader' );
```

but we can't use it in Vite. 

Is there a way for us to do this or is there nothing we can do about it for Vite?

----------
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lcoq** [comment]
I encounter similar problem with `.css` extension (without using Vue) : https://github.com/vitest-dev/vitest/discussions/5422

> TypeError: Unknown file extension ".svg" for /app/node_modules/@ckeditor/ckeditor5-ui/theme/icons/accessibility.svg


> TypeError: Unknown file extension ".css" for /app/node_modules/@ckeditor/ckeditor5-ui/theme/components/editorui/accessibilityhelp.css

> ...

**Comment by lcoq** [comment]
@ArutaGerman I believe you can you [the same fix I used](https://github.com/vitest-dev/vitest/discussions/5422#discussioncomment-8891605) until CKEditor fixes it properly.

Just update your `vite.config.ts` with the following : 

```
export default defineConfig({
  /* ... */
  test: {
    /* ... */
    server: {
      deps: {
        inline: [/@ckeditor\/.*/i, /ckeditor5\/.*/i],
      },
    },
  },
});
```

**Comment by ArutaGerman** [comment]
> @ArutaGerman I believe you can you [the same fix I used](https://github.com/vitest-dev/vitest/discussions/5422#discussioncomment-8891605) until CKEditor fixes it properly.
> 
> Just update your `vite.config.ts` with the following :
> 
> ```
> export default defineConfig({
>   /* ... */
>   test: {
>     /* ... */
>     server: {
>       deps: {
>         inline: [/@ckeditor\/.*/i, /ckeditor5\/.*/i],
>       },
>     },
>   },
> });
> ```

I wanna say just... It's alive!
Thank you, kind man!👍

**Comment by Witoso** [comment]
I encourage everyone to follow #15502, as it will resolve issues with SVG's and CSS :)

**Comment by mahovsson** [comment]
Hello I have today migrated to 41.3.0 and I get same error: 
` TypeError: Unknown file extension ".css" for /node_modules/@ckeditor/ckeditor5-editor-classic/theme/classiceditor.css.`  
I have also tried suggestion below, but still does not help any suggestions?
```
export default defineConfig({
  /* ... */
  test: {
    /* ... */
    server: {
      deps: {
        inline: [/@ckeditor\/.*/i, /ckeditor5\/.*/i],
      },
    },
  },
});
```
