### ISSUE TITLE
[Docs] Promote CKE5 inspector

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1608]
@oleq developed this [amazing tool](https://www.npmjs.com/package/@ckeditor/ckeditor5-inspector), we started using it and now it's time to promote it in the docs.

The minimum will be to mention it in a separate page and link to this page from some other pages (e.g. quick start, arch intro, etc.). 

What would be much cooler, is if we enabled the inspector for the samples that are in the docs. However, this'd require some nice UI cause we cannot just show it to everyone.

**Comment by scofalik** [comment]
I think the link is incorrect :P.

**Comment by Reinmar** [comment]
Good that I didn't paste my banking site password ;)

**Comment by Reinmar** [comment]
If we want to add the inspector to all demos of the editor in our docs, we should/could try to do that together with displaying the source code of these samples (reported in https://github.com/ckeditor/ckeditor5/issues/625). Therefore, let's for now focus on mentioning the inspector in a couple of places, rather than on enabling it.

**Comment by Reinmar** [comment]
1. Add "Development tools" below "Quick start" in the Framework section of the docs. Note: It may also be a good time to split "Quick start" into two parts: "QS" and "Implementing a simple plugin". Then, "Development tools" could be a continuation of those two guides.

2. What should be covered in "Development tools"?
 
   * the inspector (adding it to the setup created in previous guides)
   * setData/getData (view/model) utils (note: there's already a section about those things in the block widget tutorial)
   * whatever else that we find useful during development (ask guys).

3. In which other places we could mention the inspector?

   * https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/testing-environment.html (section or info box)
   * https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html (info box)
   * https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/core-editor-architecture.html#commands (infobox)
   * In every "Common API" section of the Features part of the docs.

4. Let's add the inspector to CDN under `https://cdn.ckeditor.com/ckeditor5/12.0.0/inspector.js`. In the docs we can show using it from CDN and npm. cc @vokiel

**Comment by Reinmar** [comment]
> 4\. Let's add the inspector to CDN under `https://cdn.ckeditor.com/ckeditor5/12.0.0/inspector.js`. In the docs we can show using it from CDN and npm. cc @vokiel

Actually, it'd be good to somehow automate this (or grant one of us the rights to publish there) because we're releasing the inspector more often than we release CKE5.

**Comment by vokiel** [comment]
What about updating the lib on the server after 'Release published.' webhook?

**Comment by Reinmar** [comment]
The only problem I see with this is where to get the built version of this lib from. It'd have to be installed from npm. Where would we run this script?
