### ISSUE TITLE
getData doesn't correctly append children to template elements

### ISSUE THREAD

**Issue by not-paul-v** [ckeditor/ckeditor5#16083]
## 📝 Provide detailed reproduction steps (if any)

1. Downcast custom container element to html `template` element:
```typescript
downcastHelpers.elementToElement( {
    model: 'container',
    view: 'template'
} );
```
2. Set editor data
```typescript
setData( model, '<container><paragraph>foo</paragraph></container>' );
```
3. Get editor data
### ✔️ Expected result

`<template><p>foo</p></template>`

### ❌ Actual result

`<template></template>`

### ❓ Possible solution

After looking into the source code it seems like the cause is inside `domconverter.ts` which always appends the children using `appendChild`. This does not work when the dom element is a template since you need to append the children using `content.appendChild`.

I already opened a PR (https://github.com/ckeditor/ckeditor5/pull/16039) with a possible fix and a test case that shows the problem.

**Comment by Witoso** [comment]
I'm always hesitant to specific cases `if`'s but in the case of `template` it looks like the only way? And I think it is the only "document fragment" element that we should support. WDYT @niegowski @scofalik?

**Comment by scofalik** [comment]
Interesting use case. I didn't spend much time analyzing it, but the fix makes sense. Although I'd also add a test somewhere in the upcasting tests that would check whether `<template>` element is properly upcasted (as it behaves a bit differently than regular HTML elements).

**Comment by not-paul-v** [comment]
I guess that makes sense. I can add a test case in the coming days.

**Comment by not-paul-v** [comment]
While addind the test case I noticed that the upcasting also didn't work as expected. This was because in `domChildrenToView` the children were only read from `childNodes` but for templates they would need to be read from `content.childNodes`.  https://github.com/ckeditor/ckeditor5/pull/16039/commits/4059117ee68b341ee3374c89e44ef58b14b89bcb

Let me know if you need anything else.

**Comment by not-paul-v** [comment]
@Witoso any updates on this?

**Comment by scofalik** [comment]
I merged the PR. Thank you for providing the fix and tests!

Sorry for missing the update, I had a busy time after returning from holidays :).
