### ISSUE TITLE
ckeditor4 function not working in ck editor5

### ISSUE THREAD

**Issue by developerpin** [ckeditor/ckeditor5#1611]
this function is not been working in ckeditor5

 onmousedown="CKEDITOR.tools.callFunction(1, event)"

using this function to make div expandable.let me know how i can join ckeditor4 function with ckeditor 5

**Comment by mlewand** [comment]
CKEditor 5 is not compatible with CKEditor 4 API. You can find full reference in our [API docs](https://ckeditor.com/docs/ckeditor5/latest/api/index.html).
