### ISSUE TITLE
Uncaught CKEditorError: model-nodelist-offset-out-of-bounds

### ISSUE THREAD

**Issue by darithpen** [ckeditor/ckeditor5#1612]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

    "@ckeditor/ckeditor5-autoformat": "^11.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^11.0.0",
    "@ckeditor/ckeditor5-block-quote": "^11.0.0",
    "@ckeditor/ckeditor5-core": "^12.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^12.0.0",
    "@ckeditor/ckeditor5-engine": "^13.0.0",
    "@ckeditor/ckeditor5-essentials": "^11.0.0",
    "@ckeditor/ckeditor5-heading": "^11.0.0",
    "@ckeditor/ckeditor5-link": "^11.0.0",
    "@ckeditor/ckeditor5-list": "^12.0.0",
    "@ckeditor/ckeditor5-media-embed": "^11.0.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^11.0.0",
    "@ckeditor/ckeditor5-table": "^12.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^12.0.0",
    "@ckeditor/ckeditor5-ui": "^12.0.0",
    "@ckeditor/ckeditor5-widget": "^11.0.0"

## 📋 Steps to reproduce
I have this simple plugin, a modified version of example from CKEditor5 documentation:

```javascript
import imageIcon from '@ckeditor/ckeditor5-core/theme/icons/image.svg';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

import { findOptimalInsertionPosition } from '@ckeditor/ckeditor5-widget/src/utils';

export default class Test extends Plugin {

    init() {
        const editor = this.editor;

        // register model
        editor.model.schema.register('test', {
            allowWhere: '$block',
            isBlock: true,
            isObject: true,
            isLimit: true,
            allowAttributes: ['id']
        });

        // editing downcast
        editor.conversion.for('editingDowncast').elementToElement({
            model: 'test',
            view: (modelElement, viewWriter) => {
                const paragraph = viewWriter.createContainerElement('p');
                const text = viewWriter.createText('Hello World!');
                viewWriter.insert(viewWriter.createPositionAt(paragraph, 0), text);
                return paragraph;
            }
        });

        // add toolbar button
        editor.ui.componentFactory.add( 'test', locale => {
            const view = new ButtonView( locale );

            view.set( {
                label: 'Insert image',
                icon: imageIcon,
                tooltip: true
            } );

            // on click
            view.on( 'execute', () => {

                // change model
                editor.model.change( writer => {
                    const selection = editor.model.document.selection;

                    // create data model
                    const data = writer.createElement('test', {id: '123'});
                    const insertPosition = findOptimalInsertionPosition( selection, editor.model );

                    // insert to editing view
                    writer.insert(data, insertPosition);

                } );
            } );

            return view;
        } );
    }
}
```
It worked as expected: 

![image](https://user-images.githubusercontent.com/32172535/54057352-b81dd580-41c0-11e9-8e95-e55257e0c803.png)

Until I focused (clicked) on the text node "Hello World!", It gave me the following error:

![image](https://user-images.githubusercontent.com/32172535/54057572-5316af80-41c1-11e9-9880-31457a9ad43a.png)

**Comment by Reinmar** [comment]
What happened here is that you have an empty model element `<test></test>` and in the view you have `<p>Hello World!</p>`. That means that position inside that paragraph won't be able to map to any positions inside the model element.

This situation is explained in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#fixing-position-mapping. There's a util which lets you change the position mapping, however, I don't know if it will work in your case. That's because in the inline widget scenario (covered in the documentation) we create a widget. A widget can only be selected from outside, so you don't need to be able to map positions inside that view element to the model. In your case, you created a normal paragraph. So:

* if you want the text inside that paragraph to be selectable, you need to have the same text inside the model `<test>` element,
* if not, you need to make that paragraph a widget.

Let me know if this helps.

**Comment by darithpen** [comment]
Thank you, I really appreciate your help. As you pointed out, the problem is whatever views that are created should be mapped to models.

### Solution
So, I managed to fix the above plugin by creating a text node model rather than a text node view when downcasting:

```javascript
import imageIcon from '@ckeditor/ckeditor5-core/theme/icons/image.svg';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

import { findOptimalInsertionPosition } from '@ckeditor/ckeditor5-widget/src/utils';

export default class Test extends Plugin {

    init() {
        const editor = this.editor;

        // register model
        editor.model.schema.register('test', {
            allowWhere: '$block',
            isBlock: true,
            isObject: true,
            isLimit: true,
            allowAttributes: ['id']
        });

        //============ allow Paragraph in test block
        editor.model.schema.extend('paragraph', {allowIn: 'test'});
        //============
        // editing downcast
        editor.conversion.for('editingDowncast').elementToElement({
            model: 'test',
            view: (modelElement, viewWriter) => {
                return viewWriter.createContainerElement('div');
            }
        });

        editor.conversion.for('dataDowncast').elementToElement({
            model: 'test',
            view: (modelElement, viewWriter) => {
                return viewWriter.createContainerElement('test', {id: modelElement.getAttribute('id')});
            }
        });

        // add toolbar button
        editor.ui.componentFactory.add( 'test', locale => {
            const view = new ButtonView( locale );

            view.set( {
                label: 'Insert image',
                icon: imageIcon,
                tooltip: true
            } );

            // on click
            view.on( 'execute', () => {

                // change model
                editor.model.change( writer => {
                    const selection = editor.model.document.selection;

                    // create data model
                    const data = writer.createElement('test', {id: '123'});

                    //============ create a text node model inside a paragraph rather than 
                    //============ a text node view (in editingDowncast conversion)
                    const paragraph = writer.createElement('paragraph');
                    writer.appendText('Hello World!', {}, paragraph);
                    writer.append(paragraph, data);
                    //============
                    const insertPosition = findOptimalInsertionPosition( selection, editor.model );

                    // insert to editing view
                    writer.insert(data, insertPosition);

                } );
            } );

            return view;
        } );
    }
}
```

### Using Widget
I also tried using a widget and it works as you suggested, no error when clicked (left click) on the text node because the widget masked the entire block from focusing on the text node. 
But the same error occurs when right-click. My guess is when right-clicking on the text, the widget doesn't prevent it from selecting the text. This behavior only happen on MacOS:

![image](https://user-images.githubusercontent.com/32172535/54315778-76709e80-45b5-11e9-90fb-aee76feda892.png)

**Comment by scofalik** [comment]
> Using Widget
>
> I also tried using a widget and it works as you suggested, no error when clicked (left click) on the text node because the widget masked the entire block from focusing on the text node.
> But the same error occurs when right-click. My guess is when right-clicking on the text, the widget doesn't prevent it from selecting the text. This behavior only happen on MacOS

This is interesting. I can believe that something like this could happen but it doesn't happen on our widgets demo https://ckeditor5.github.io/misc/placeholder-demo/index.html 🤔

**Comment by darithpen** [comment]
I tested the demo link above with 4 browsers on macOS 10.12.6, here is the result:
### Firefox 65.0.1
![image](https://user-images.githubusercontent.com/32172535/54362152-d19aa380-463e-11e9-8cc8-ab619e98d4fc.png)
### Chrome 72.0.36
![image](https://user-images.githubusercontent.com/32172535/54362163-d7908480-463e-11e9-8263-9575dcbd8f05.png)
### Safari 12.0.1
![image](https://user-images.githubusercontent.com/32172535/54362188-e0815600-463e-11e9-8389-aa598b920461.png)
### Opera 56.0.3
![image](https://user-images.githubusercontent.com/32172535/54362549-7d43f380-463f-11e9-8ad3-0788b1e739be.png)

Only **Firefox** that is not selected when right-click. I hope this help.

**Comment by scofalik** [comment]
Yes, that happen. I mean that there is no error in the console when right-clicking the widget (in our demo). So this must be specific to your implementation.
