### ISSUE TITLE
on edit in ckeditor CSS not shows in HTML

### ISSUE THREAD

**Issue by hassan209** [ckeditor/ckeditor5#16121]
when get my ckeditor data after editing ckeitor then my CSS in html gone.

     if (this.editorComponent && this.editorComponent.editorInstance) {
       innerdocbody= this.editorComponent.editorInstance.getData();
    }
    
    my innerdocbody has data but with out css in my html in angular.
    Please help me out

**Comment by Witoso** [comment]
Editor doesn't output [content styles](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html#sharing-content-styles-between-frontend-and-backend), and those need to be implemented on the place where the content is shown. Inline styles are tracked here: #1627

**Comment by hassan209** [comment]
> Editor doesn't output [content styles](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html#sharing-content-styles-between-frontend-and-backend), and those need to be implemented on the place where the content is shown. Inline styles are tracked here: #1627
