### ISSUE TITLE
How can I preview the entire content in the editor at once with an isolated independent preview  button to generate a preview in a separate section.

### ISSUE THREAD

**Issue by jasmeet2021** [ckeditor/ckeditor5#16139]
## 📝 Ask a question

**I have a requirement of previewing the entire content in the editor area via  an independent html preview button which when clicked shows the preview of the editors entire content in a separate preview section with keeping the security & sanitizations in check**

I am using Nextjs with CKeditor-5-40.1.0 custom build.

To give more context I want to achieve the "preview editor data" button feature of previewing the content editor's like  this https://ckeditor.com/docs/ckeditor5/latest/features/html/html-embed.html#demo

![image](https://github.com/ckeditor/ckeditor5/assets/92725379/8f84f947-32b0-4eb8-9b63-458ccac292ac)

**Comment by Witoso** [comment]
Implementation of the demo is publicly available:

https://github.com/ckeditor/ckeditor5/blob/a1364cca836f01ae84e150404d1a7f7a395a26bc/packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js#L133-L167

**Comment by jasmeet2021** [comment]
Hi Witoso ! 

Appreciate it Thanks for pointing that out.

**Comment by jasmeet2021** [comment]
bugging you again ! :)

Is their any optimal approach or ideal approach that you can share to apply styles and stylesheets to the custom iframe preview section rendered dynamically for the editorData apart from the one mentioned in the example.
