### ISSUE TITLE
Can I use a React component in an inline widget?

### ISSUE THREAD

**Issue by DeltekDavid** [ckeditor/ckeditor5#16148]
## 📝 Ask a question

Per your [very nice tutorial](https://ckeditor.com/docs/ckeditor5/latest/tutorials/widgets/using-react-in-a-widget.html), CKEditor5 supports block-level widgets that host a React component. But what about inline components? We want to create some specialized components with complex logic and render them inline with the text. It would be really helpful if we could build them as React components.

Edit: See also my [SO post](https://stackoverflow.com/questions/78312625/ckeditor5-how-do-i-find-the-element-node-i-want-to-update-from-my-react-widget).

**Comment by DeltekDavid** [comment]
@Witoso thanks--I was able to create an inline widget hosting a React component (call it `BracketOption`). It's basically a button with a ternary state that changes when the user clicks the button. I set an attribute called `data-opted-state` in the `span` rendered by the component.

![image](https://github.com/ckeditor/ckeditor5/assets/143453251/aa0129d7-e053-4c80-88cf-b9cd77aef9bb)


Now I'm trying to figure out how to update the model when the view changes (i.e., when the user interacts with the component and changes its state). Is there a way to do this using a converter? The outermost `span` isn't the actual component whose state I'm manipulating; rather, the `span` rendered by the React component contains the `data-opted-state` attribute.

Do I need to give the React component a reference to its parent `span` and have it set attributes on that element, so that the upcast converter will see it? That seems kinda hacky...is there a cleaner way?

The view looks something like this in the inspector:
![image](https://github.com/ckeditor/ckeditor5/assets/143453251/b23d3c06-8053-467e-8039-3661388e34fd)

In the actual HTML, I can see the attribute of that inner `span` changing when I click the button. So how do I update the state in CKEditor as well?
![image](https://github.com/ckeditor/ckeditor5/assets/143453251/112a60a1-93aa-4076-a273-7aeb2018ea02)

Any help would be greatly appreciated. Thanks.

**Comment by DeltekDavid** [comment]
I managed to [figure this out](https://stackoverflow.com/a/78312940/284743). It would be nice if the tutorial included an example of how to update the model state correctly when using a React component to represent a model node.

**Comment by Witoso** [comment]
Hi! Glad you worked out a solution. Exactly, model's change via editor's API is a correct way to edit editor's data. This is the only source of truth that then is converted to vDOM, and rendered. Converters are pipelines, a way to input the data to the model and how it should be outputted, for example to HTML. [More in the docs](https://ckeditor.com/docs/ckeditor5/latest/framework/architecture/editing-engine.html#model).

**Comment by DeltekDavid** [comment]
> Hi! Glad you worked out a solution. Exactly, model's change via editor's API is a correct way to edit editor's data. This is the only source of truth that then is converted to vDOM, and rendered. Converters are pipelines, a way to input the data to the model and how it should be outputted, for example to HTML. [More in the docs](https://ckeditor.com/docs/ckeditor5/latest/framework/architecture/editing-engine.html#model).

Right...an example of roundtripping data with a React component would have saved me some headache. I kind of stumbled on the answer. Thanks though!
