### ISSUE TITLE
_rwd.css not found

### ISSUE THREAD

**Issue by jdmr** [ckeditor/ckeditor5#1614]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

ckeditor 5

## 📋 Steps to reproduce

1. vue create demo
2. yarn add @ckeditor/ckeditor5-vue @ckeditor/ckeditor5-build-classic
3. yarn add @ckeditor/ckeditor5-image
4. yarn add @ckeditor/ckeditor5-theme-lark
5. Initialize ckeditor in main.js (import, vue.use)

`import Vue from 'vue'
import CKEditor from '@ckeditor/ckeditor5-vue'

Vue.use(CKEditor)
`

6. Use it in the home page

`<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />

    <ckeditor
      v-model="editorModel"
      :editor="editor"
      :config="editorConfig"
    ></ckeditor>

    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from "@/components/HelloWorld.vue";
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';

export default {
  name: "home",
  components: {
    HelloWorld
  },
  data() {
    return {
      editorModel: null,
      editor: ClassicEditor,
      editorConfig: {
        plugins: [Image, ImageToolbar, ImageCaption, ImageStyle],
        image: {
          toolbar: [
            'imageTextAlternative',
            '|',
            'imageStyle:full',
            'imageStyle:side'
          ]
        }
      },
    }
  }
};
</script>
`
## ✅ Expected result
Load the page
## ❎ Actual result
 ERROR  Failed to compile with 1 errors                                                                                                      7:06:18 AM

This dependency was not found:

* -!../../../css-loader/index.js??ref--6-oneOf-3-1!../../../postcss-loader/src/index.js??ref--6-oneOf-3-2!./@ckeditor/ckeditor5-theme-lark/theme/mixins/_rwd.css in ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/@ckeditor/ckeditor5-image/theme/textalternativeform.css

To install it, you can run: npm install --save -!../../../css-loader/index.js??ref--6-oneOf-3-1!../../../postcss-loader/src/index.js??ref--6-oneOf-3-2!./@ckeditor/ckeditor5-theme-lark/theme/mixins/_rwd.css

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Did you follow https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html? What is your webpack config?

**Comment by jdmr** [comment]
I'm using vue cli to create my app, and followed the steps to reproduce, I **did not modify** the default webpack config through the vue.config.js.

**Comment by oleq** [comment]
I see that you use 

```
@ckeditor/ckeditor5-build-classic
@ckeditor/ckeditor5-image
```

next to each other which will not work in any configuration (Vue or not Vue) because you're mixing a pre-compiled editor **build** with a feature from the **source code.**

To [add features to the build](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/installing-plugins.html), you must create a new one, build it and import it in your Vue app or [build the editor along with Vue CLI app](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source).

Besides, why you import `ckeditor5-theme-lark` and `ckeditor5-image` anyway? What is your goal? I'm asking because they're both shipped by default in build-classic.

**Comment by jdmr** [comment]
I was following a tutorial to try and get the image to pop up a url input box, but got stuck. I'll try these options instead... Thanks!

**Comment by maharzan** [comment]
@jdmr I am encountering the same issue. I added the editor but when I tried adding image, it wouldn't embed in the editor or do anything. I tried to import Image and got the same _rwd.css error. I guess, you do not have to import other modules as it should be there by default. But how do you get the image working? How did you fix it?
