### ISSUE TITLE
Menu bar items are truncated on Firefox

### ISSUE THREAD

**Issue by Mati365** [ckeditor/ckeditor5#16151]
## 📝 Provide detailed reproduction steps (if any)

1. Open http://localhost:8125/ckeditor5-ui/tests/manual/menubar/menubar.html
2. Menu is truncated

![obraz](https://github.com/ckeditor/ckeditor5/assets/3949262/960eabd2-c915-4351-93f6-3e5c7b5193f1)

### ✔️ Expected result

Menu bar items are not truncated on Firefox

### ❌ Actual result

Menu bar items are truncated on Firefox

### ❓ Possible solution

Incorrect flex and baseline CSS properties on menu buttons. Setting bigger `line-height` (e.g.: `line-height: normal;`) fixes issue.    

## 📃 Other details

1. The issue does not happen in incognito mode.
2. Possible font rendering issue on Linux (it happens quite often).
3. Can be reproduced using LiveCD Fedora 39 XFCE.

* Browser: Firefox 124.0.1
* OS: Linux / Fedora 39 XFCE

![obraz](https://github.com/ckeditor/ckeditor5/assets/3949262/b41c5c02-5c41-4271-b10c-30a61781f9ec)
![obraz](https://github.com/ckeditor/ckeditor5/assets/3949262/5d27e390-69dd-4091-a308-34b0cbc294ec)

**Comment by Mati365** [comment]
@oleq While, overflow issue has been fixed, the new regression has been introduced. Vertical align of menu items is incorrect on Firefox, and titles are not centered properly in the menu bar list. 

![Image](https://github.com/user-attachments/assets/fc963e47-b054-493f-bcfc-569263a7537d)

**Comment by oleq** [comment]
I couldn't reproduce it in FF on Mac or Windows.

**Comment by oleq** [comment]
I couldn't reproduce it in Ubuntu either

![Image](https://github.com/user-attachments/assets/6383ac83-3157-4773-9fc3-cfbf8007cce3)

**Comment by Mati365** [comment]
Weird, maybe

**Comment by Mati365** [comment]
It may be related to my local setup. Closing for now
