### ISSUE TITLE
The menu bar doesn't wrap on the narrower screens and goes outside the toolbar

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#16159]
## 📝 Provide detailed reproduction steps (if any)

1. Open menu bar manual test: http://localhost:8125/ckeditor5-ui/tests/manual/menubar/menubar.html
2. Narrow the browser window or use the device with a small screen e.g. mobile. 

### ✔️ Expected result

The menu bar wraps on the narrower screens and doesn't go outside the toolbar.

### ❌ Actual result

The menu bar doesn't wrap on the narrower screens and goes outside the toolbar:
![IMG_C04EDADDBD9A-1](https://github.com/ckeditor/ckeditor5/assets/32898551/d881c68e-3d62-4337-a7a4-304c1ecf1067)

## 📃 Other details

* Browser: Any
* Branch: `release`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pszczesniak** [comment]
Just a suggestion, WDYT?


https://github.com/ckeditor/ckeditor5/assets/7074833/9e53d29d-fc0b-4bae-8966-b1a88e485570
