### ISSUE TITLE
Visual glitches while editing an image using CKBox

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#16153]
## 📝 Provide detailed reproduction steps (if any)

https://github.com/ckeditor/ckeditor5/assets/1099479/78caf9aa-a9b3-4d3d-98e0-47df10cd8f4a

### ✔️ Expected result

1. The loading spinner in CKBox staying centered.
2. The image toolbar staying attached to the image after closing CKBox.

## 📃 Other details

* Browser: Chrome
* OS: MacOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by gorzelinski** [comment]
I've investigated these problems a little.

1. The spinner is probably only related to this one particular example. I guess there is a CSS conflict of some sort.
2. The problem with the toolbar might be more broad. I tested some other demos with CKBox image editing enabled, and the results were the same. It may be related to the `position: fixed` property. When you turn it off on the CKBox dialog, the toolbar works correctly. It also fixes itself after some action on the page, like scrolling or clicking it. The toolbar is misplaced for 100px from the top.

Examples of other demos with the second problem:
- https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html
- https://ckeditor.com/docs/ckeditor5/latest/features/file-management/ckbox.html
- https://ckeditor.com/docs/ckeditor5/latest/features/show-blocks.html

**Comment by oleq** [comment]
> 2\. The problem with the toolbar might be more broad. I tested some other demos with CKBox image editing enabled, and the results were the same. It may be related to the `position: fixed` property. When you turn it off on the CKBox dialog, the toolbar works correctly. It also fixes itself after some action on the page, like scrolling or clicking it. The toolbar is misplaced for 100px from the top.

We may want to call `editor.ui.update()` when CKBox closes. Various parts of the editor UI (including `BalloonToolbar`) [react to that and re-position themselves](https://github.com/ckeditor/ckeditor5/blob/c93633b41fae6480dc27eff6cd777e944acc1c1a/packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.ts#L256-L258).
