### ISSUE TITLE
Failed to install autosave plugin to document editor build

### ISSUE THREAD

**Issue by emiltsang** [ckeditor/ckeditor5#1616]
## Other
I have followed the instructions to install plugin to editor build on
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html
After importing the required plugin and build the document editor,
I failed to install the custom editor build to my project.
Did I build the editor incorrectly?

## 💻 Version of CKEditor
ckeditor 5 
@ckeditor/ckeditor5-build-decoupled-document
@ckeditor/ckeditor5-autosave
vue-cli-3

## 📋 Steps to reproduce

1. cd to my project directories
2. git clone -b stable https://github.com/ckeditor/ckeditor5-build-decoupled-document.git
3. cd ckeditor5-build-decoupled-document
4. npm install
5. npm install --save @ckeditor/ckeditor5-autosave
7. import the plugin
8. Add to the builtin plugin arrays
9. npm run build
10. cd back to my project directories
11. npm install ./ckeditor5-build-decoupled-document
12. npm run serve

## ✅ Expected result
Successfully install the document editor build with autosave plugin
## ❎ Actual result
![image](https://user-images.githubusercontent.com/17539949/54170876-4f31a880-44b3-11e9-9041-c45fc89333ef.png)

## 📃 Other details that might be useful
Directories structure
![image](https://user-images.githubusercontent.com/17539949/54170989-cf580e00-44b3-11e9-8536-d12e5aed4eb2.png)

**Comment by Mgsy** [comment]
Hello, did you check our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)?

**Comment by emiltsang** [comment]
Yes, I have followed the Vue integration guide to install CKEditor and I can successfully integrate the document editor (without installing any plugins) build to my project.

But, I have the above problems when I tried to add the autosave plugin and install the custom build.

**Comment by emiltsang** [comment]
After consulting the **Using CKEditor from source** section in Vue.js integration guide.
I was able to integrate the autosave plugin to my project.
Thanks for support!

**Comment by Mgsy** [comment]
>After consulting the Using CKEditor from source section in Vue.js integration guide.
I was able to integrate the autosave plugin to my project.
Thanks for support!

That's great to hear 👍
