### ISSUE TITLE
[Chrome + Mac] Copying non-ASCII characters from CKEditor and then pasting them produces different symbols

### ISSUE THREAD

**Issue by slotterbackW** [ckeditor/ckeditor5#16202]
## 📝 Provide detailed reproduction steps (if any)

1. Paste these Japanese characters into the [CKEditor demo](https://ckeditor.com/ckeditor-5/demo/feature-rich/): `お世話になっております` (I don't think the issue is specific to these exact characters, but this is how it was reported to me.)
2. Select all and Copy (`cmd + c`) the characters from within the CKEditor demo editor
3. Paste into the notes app or TextEdit in MacOS
4. The pasted content is `ãŠä¸–è©±ã«ãªã£ã¦ãŠã‚Šã¾ã™`

### ✔️ Expected result

I would expect the pasted content to be the same as the characters which were copied.

### ❌ Actual result

The pasted content is `ãŠä¸–è©±ã«ãªã£ã¦ãŠã‚Šã¾ã™`

### ❓ Possible solution

Chrome recently released [some changes](https://developer.chrome.com/blog/css-i18n-features) for Japanese characters which we've seen cause other problems, so I'm wondering if this is related? Curiously though this issue does not happen if I paste these characters into Gmail, and then copy them into the notes app.

## 📃 Other details

* Browser: I can only reproduce this on Chromium based browsers (Chrome, Edge)
* OS: MacOS
* First affected CKEditor version: I can reproduce this on v36.0.1 and also the current demo editor

Added by @wwalc: This is a critical upstream issue :( - https://issues.chromium.org/issues/333989067 
**Please upvote the ticket in the Chromium issue tracker so that it is prioritized.**

---
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the report! I could reproduce it as well.

Affected:

*   Chrome: yes
*   Safari: no
*   Firefox: no
*   Edge: yes

Moreover, I reproduced it with other languages like Chinese, Malayalam, Ukrainian, as well as diacritical marks in Polish or French :warning:  Investigating...

**Comment by Witoso** [comment]
Doesn't work in other editors on Chrome as well

*   Tiny
*   Slate
*   ProseMirror

also are affected.

**Comment by arkflpc** [comment]
I've tested it on Chrome, Firefox and Edge on Windows and Chrome and Firefox on Linux. It works as expected there.

**Comment by Witoso** [comment]
Reported: https://issues.chromium.org/issues/333989067

**Comment by Witoso** [comment]
It was confirmed as a regression in Chromium, it got P1 priority, and is worked on right now.

**Comment by Witoso** [comment]
This was fixed on the Chromium tracker, and ported to the current stable version 124. Verified on their side as well:

> Verified the fix on the latest Stable M124#124.0.6367.81 using Mac 14.4.1 (...)

Closing, there may be a need to wait a bit for the full distribution of Chrome. Thanks again for reporting!
