### ISSUE TITLE
Table cell discards custom text alignment

### ISSUE THREAD

**Issue by felipegiotto** [ckeditor/ckeditor5#1620]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor 5, Decoupled build, v12.0.0

## 📋 Steps to reproduce

1. Edit "sample/index.html" and create a link to "reload" the editor content: `window.editor.setData(window.editor.getData());`
2. Open the file in the browser, create a table and set the "center" text alignment in one or more cells.
3. Click the link

## ✅ Expected result

The editor content (including the centered text alignment) should be retained.

## ❎ Actual result

The text changes to left (default) alignment.

## 📃 Other details that might be useful

The editor uses the HTML `<td style="text-align:center;">Ce</td>` to denote a table cell with centered text. But, it fails to parse this HTML, and discards the text align information.

**Comment by Mgsy** [comment]
I can confirm this behaviour. 

cc @jodator

**Comment by jodator** [comment]
Such feature is not implemented (styling table cells). You can style paragraphs inside table cells.

```html
<td>
    <p style="text-align:center">foo</p>
</td>
```

Related issue: https://github.com/ckeditor/ckeditor5-table/issues/122.

**Comment by felipegiotto** [comment]
@jodator, the problem is that the editor itself is styling the table cells, when I create a table and change the alignment, as I'm setting the same editor document, without changing anything.
Maybe the `Table` plugin should create this `<p>` element, with the `style` attribute?

**Comment by jodator** [comment]
> Maybe the `Table` plugin should create this `<p>` element, with the `style` attribute?

Well this is exactly how table feature ~works~ should work with alignment feature.

@Reinmar: Unfortunatelly we have a regression. 
The expected behavior is that `ediotr.getData()` should return:

```html
<figure class="table">
	<table>
		<tbody>
		<tr>
			<td>
				<p style="text-align:right;">a</p>
			</td>
		</tr>
		</tbody>
	</table>
</figure>
```
but it's returning
```html
<figure class="table">
	<table>
		<tbody>
		<tr>
			<td style="text-align:right;">a</td>
		</tr>
		</tbody>
	</table>
</figure>
```
