### ISSUE TITLE
Image is missing the restricted exception class in the data

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#16218]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the editor with Restricted editing and configuration allowing inserting inline images to the exception fields
2.  Set the following initial data: `<span class="restricted-editing-exception">This is example content</span>`
3.  Put the caret inside the exception marker
4.  Insert an image
5.  Call `editor.getData()`

### ✔️ Expected result

The image markup includes the `restricted exception` class, so it could be properly recognized during editor initialization

### ❌ Actual result

The image markup is missing the `restricted exception` class, so after reloading the editor (or calling `editor.setData( editor.getData() )`) it's impossible to edit the image.

It is correct in the editing view.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by stevenrai** [comment]
This effectively makes the fix for https://github.com/ckeditor/ckeditor5/issues/15521 unusable. Timeline to resolve this so images can be successfully inserted in to restricted docs?
