### ISSUE TITLE
Set default config fonts.

### ISSUE THREAD

**Issue by JarMaj** [ckeditor/ckeditor5#1623]
I have project with ckeditor 5. I try to set default config for family and size font's. In ckeditor 4 we could set default config fonts by

`font_defaultLabel` and `fontSize_defaultLabel`

So how i can set this same in ckeditor 5 ?

 ```
function SetDefaultFont(fontSize) {
        CKEDITOR.config.fontSize_defaultLabel = fontSize;
    }

function SetDefaultFontFamily(fontFamily) {
    CKEDITOR.config.font_defaultLabel = fontFamily;
}
```

**Comment by Mgsy** [comment]
Hello, please check the [font feature configuration guide](https://ckeditor.com/docs/ckeditor5/latest/features/font.html).

**Comment by JarMaj** [comment]
I know this but how i config 'default' fonts ? I need this to set fonts from database. In example above i have functions which set size and family font's. In parameters i set values from db. But in ckeditor 5 we don't have similar opportunities. Yes we have option like 'default' but where i can manipulate with this ?

**Comment by Mgsy** [comment]
>Use the special 'default' keyword to use the default font size defined in the web page styles. 

As you can read in the documentation the default option is defined in your web page styles.

**Comment by shivakantshukla55** [comment]
@Mgsy I am also running with same issue. But in my case default value of my web page styles is different and i want to set default value for the text editor something different. Is it possible to achieve it? if YES then how. Thanks in advance.

**Comment by asolace** [comment]
@Mgsy Same issue, as you can read, we don't want the default value to be the web page but custom-defined font that's not reliant on the web page.

For those using React, I discovered a method called execute but it's not working as expected. Maybe someone would like to give it a try and debug it.

```
onReady={editor => {
  const fontFamily = editor.commands.get('fontFamily')
  fontFamily.execute({value: 'Segoe UI'})
}}
```

Execute Command was found here https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-execute

Font Command was found here https://ckeditor.com/docs/ckeditor5/latest/api/module_font_fontcommand-FontCommand.html

If anyone finds a solution please let us know! It'd be more help full than sending some documentation. Thanks in advance.

**Comment by AbdulDotKhan** [comment]
> @Mgsy Same issue, as you can read, we don't want the default value to be the web page but custom-defined font that's not reliant on the web page.
> 
> For those using React, I discovered a method called execute but it's not working as expected. Maybe someone would like to give it a try and debug it.
> 
> ```
> onReady={editor => {
>   const fontFamily = editor.commands.get('fontFamily')
>   fontFamily.execute({value: 'Segoe UI'})
> }}
> ```
> 
> Execute Command was found here https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-execute
> 
> Font Command was found here https://ckeditor.com/docs/ckeditor5/latest/api/module_font_fontcommand-FontCommand.html
> 
> If anyone finds a solution please let us know! It'd be more help full than sending some documentation. Thanks in advance.

+1 to this post... it would be very helpful to be able to set the default font to "Arial" for example. This is important for things like PDF export where we would prefer "document-oriented" fonts rather than web fonts.

**Comment by ameralaamar** [comment]
You can do that by setting a css variable and set the variable as your preferred one.

css class:

.ck-editor__editable_inline p
{
  font-size: var(--fontSize) !important;
  font-family: var(--fontFamily) !important;
}

and then ngOnInit (I'm using Angular version)

 ngOnInit() { 
  document.documentElement.style.setProperty('--fontSize', '15px');
  document.documentElement.style.setProperty('--fontFamily', 'Cairo');
 }

**Comment by Rajesh-Thiyagarajan** [comment]
> const fontFamily = editor.commands.get('fontFamily')
>   fontFamily.execute({value: 'Segoe UI'})

const fontFamily = editor.commands.get('fontFamily');
fontFamily.execute({ value: 'Arial, Helvetica, sans-serif' });

It's too late answer. This code worked for me.

**Comment by berendengelbrecht** [comment]
> I know this but how i config 'default' fonts ? I need this to set fonts from database. In example above i have functions which set size and family font's. In parameters i set values from db. But in ckeditor 5 we don't have similar opportunities. Yes we have option like 'default' but where i can manipulate with this ?

I had a similar problem and fixed it by using generated css. To apply default font and size for all children of the editor class, you can use something like this:
`.editor * { font-family: Open Sans; font-size: 11pt; }`

My css generator is an old-style Asp.Net http handler:
``` csharp
        context.Response.ContentType = "text/css";
        context.Response.Write(".editor * { font-family: Open Sans; font-size: 11pt; }");
        context.Response.Flush();
```
(css in the example is static, but of course easily made dynamic)

Then simply include the URL to the generated css in the web page hosting your editor.
