### ISSUE TITLE
Addressing Localization Challenges: Enhancing CKEditor with Region-Specific Icons for Swedish Users 

### ISSUE THREAD

**Issue by Neelakanth-S** [ckeditor/ckeditor5#16248]
## 📝 Provide detailed reproduction steps (if any)

1.Opening the editor in sweden region.

_What is the expected result of the above steps?_
The icons for sweden locale are B(Bold), I(italic) and S(with strike through) but we expect
F (fet stil) instead of B,
K (kursiv) instead of I and
ab (with strike through) (genomstruken) instead of S(with strike through) 
for the sweden region.

### ❌ Actual result
The icons for sweden locale are B(Bold), I(italic) and S(with strike through)

### ❓ Possible solution
we expect
F (fet stil) instead of B,
K (kursiv) instead of I and
ab (with strike through) (genomstruken) instead of S(with strike through) 
for the sweden region.
_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: IE and Edge
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Neelakanth-S** [comment]
We are using ckeditor-dev version 4.8.0

**Comment by Reinmar** [comment]
Do you mean CKEditor 4? This is CKEditor 5's issue tracker. They are separate projects.

CKEditor 4 is tracked in [https://github.com/ckeditor/ckeditor4](https://github.com/ckeditor/ckeditor4) but it's actually past its end of life. There's a commercial LTS version available, though. 

You can learn more here: https://ckeditor.com/ckeditor-4-support/

**Comment by Neelakanth-S** [comment]
Does CKEditor 5 support changing the toolbar icons for Bold (B), Italic (I), and Underline (U) to Swedish language? Additionally, are there any specific reasons why these icons might not translate well into Swedish environment ?
