### ISSUE TITLE
Classic editor toolbar overflow renders partially off screen when in table with fixed layout

### ISSUE THREAD

**Issue by lnmp4000** [ckeditor/ckeditor5#16245]
![image](https://github.com/ckeditor/ckeditor5/assets/2903591/62c5cd13-9b50-4412-aed0-797078a7e91c)

## 📝 Provide detailed reproduction steps (if any)

[Code sandbox to reproduce the issue can be found here...](https://codesandbox.io/p/sandbox/ckeditor-hl9rvc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv5albk100062v6i3wb718kn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv5albk000022v6imhs9xena%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv5albk000032v6isac8o8fx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv5albk000052v6ixbcadr5j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv5albk000022v6imhs9xena%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv5albjz00012v6iwicx5m84%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clv5albk000022v6imhs9xena%2522%252C%2522activeTabId%2522%253A%2522clv5albjz00012v6iwicx5m84%2522%257D%252C%2522clv5albk000052v6ixbcadr5j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv5albk000042v6ipeg29d3m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv5albk000052v6ixbcadr5j%2522%252C%2522activeTabId%2522%253A%2522clv5albk000042v6ipeg29d3m%2522%257D%252C%2522clv5albk000032v6isac8o8fx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv5albk000032v6isac8o8fx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.875%257D)

1. … Within a table with css style `table-layout: fixed;` reduce screen size so toolbar elements hidden to menu.
2. … In left most editor, expand menu
3. … Observe that the expanded menu renders with the menu cut off against the left side of the screen.

### ✔️ Expected result

The menu should either wrap, or re-position itself, so the left hand side of the menu never renders beyond the left hand side of the screen.

### ❌ Actual result

The menu left hand side of the menu renders off the screen.

## 📃 Other details

* Browser: Chrome Version 124.0.6367.60 (Official Build) (64-bit)
* OS: Ubuntu
* First affected CKEditor version: 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Dup: #9763
