### ISSUE TITLE
Update eslint to version 8 or higher

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#16258]
In PR #16107, we had to wrap our code in IIFE in the `scripts` folder because the version of eslint we use doesn't support top-level await syntax.

Top-level await support was added in eslint 8 with `ecmaVersion: 2022` or higher. We are currently using eslint 7 and `ecmaVersion: 2020` and upgrading would require a lot of work that we don't have the capacity for at this time.

Source: https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0/#support-for-es2022-class-fields%2C-top-level-await%2C-and-regexp-matching-indices

**Comment by filipsobol** [comment]
Another reason to update to eslint >= 8 is that we could use [this Markdown plugin](https://github.com/eslint/markdown) to format and validate code blocks in Markdown files.

**Comment by Witoso** [comment]
Please keep in mind `eslint` 8.53+ [deprecates formatting rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules/), and it would force us to rethink the entire formatting approach.

**Comment by pomek** [comment]
Closing as done. At some point (#17132), we upgraded it.

https://github.com/ckeditor/ckeditor5/blob/b6f6dcb3daf5c157e6446ffe74111ee97e6b4476/package.json#L134
