### ISSUE TITLE
Enable the undo/redo commands in Source Editing mode

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#16250]
## 📝 Provide a description of the new feature

Currently, there is no way to undo/redo actions done when the editor is in the Source Editing mode.

We could consider enabling these commands and their associated keyboard shortcuts in Source Editing.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Dup: #13700
