### ISSUE TITLE
&shy; is rendered hidden after save

### ISSUE THREAD

**Issue by maxstrebel** [ckeditor/ckeditor5#16299]
## 📝 Provide detailed reproduction steps (if any)

1. Write a text that should contain soft hyphens (`&shy;`)
2. Switch to html/source editing and add `&shy;` in a word in order to add a soft hyphen
3. Save
4. Open html editor again. The hyphen works but it has been converted. The `&shy;` is not visible anymore.

### ✔️ Expected result

Similar to `&nbsp;` the `&shy;` should still be visible. Otherwise authors will be unable to change the position of a soft-hyphen or correct a mistake. This would be a huge relief for my german authors as `hyphens: auto;` is not viable. They need control when words break.

### ❌ Actual result

In opposite to `&nbsp;` the `&shy;` is not visible in the source code anymore. 

### ❓ Possible solution

Do not convert `&shy;` to an invisible character and at least keep it in the source. I know it is very niche (for languages that have long words), but the soft hyphen is part of the standard and a good solution: ["soft" hyphen at MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens?retiredLocale=de#u00ad_shy)

## 📃 Other details

**Before save**

<img width="630" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/910594/7550e6c0-3e30-4bd4-be6e-15ba912b00ef">

**After save**

<img width="630" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/910594/891b3002-8bf3-4ee7-ba43-9d285c2f0936">

**Related**

https://stackoverflow.com/questions/77793285/why-does-ckeditor-5-replace-soft-hyphen-shy-how-can-i-stop-this

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post. Thanks 1000.

**Comment by niegowski** [comment]
This is how the browser is handling that entity. Our default implementation of `HtmlWriter` (`BasicHtmlWriter`) is using `innerHTML` to stringify the DOM fragment:

https://github.com/ckeditor/ckeditor5/blob/ecaeaa970b4878b5a4ff8cd535f38dec7d80ccbe/packages/ckeditor5-engine/src/dataprocessor/basichtmlwriter.ts#L27

You could override the default writer or you could add a post-processing listener to the `DataController#get()`:

```js
editor.data.on( 'get', evt => {
	evt.return = evt.return.replace( /\u00AD/g, '&shy;' );
}, { priority: 'low' } );
```

**Comment by maxstrebel** [comment]
Hey @niegowski, thank you for the explanation. That's unfortunate. I will then try to open a feature request for the CMS I'm working with.
