### ISSUE TITLE
We are evaluating the CK Editor, We have performance issue after reaching 10, 0000 lines

### ISSUE THREAD

**Issue by pandithuraik** [ckeditor/ckeditor5#16301]
Dear Support,

 We noticed performance issue after reaching 10, 0000 lines in the CK Editor 5 while evaluating the product

After 10000 lines pasted into the editor when we type a letter in the CKEditor , it takes few seconds to appear in the screen. 

Please advise us any fix or solution to this issue. We are considering to purchase CK editor if there is a solution for this issue.

Thanks and regards
Pandithurai K
Muscat , Oman,

**Comment by Witoso** [comment]
Hi! Please reach out via [our support channel](https://ckeditor.com/contact/), this is a usual way we provide support for commercial offering, we also need to ask a few follow-up questions about your setup, and plugins enabled. Thank you!
