### ISSUE TITLE
[Docs] Lack of source code in read only feature

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#1631]
## 📋 Steps to reproduce

1. See: https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html

## ✅ Expected result

It should be a code block.

## ❎ Actual result

No source code 😢 

## 📃 Other details that might be useful
It's a request via our feedback widget, anyway it's weird because above the demo we can see:
> The editor can be set into a read-only mode by changing the value of the Editor#isReadOnly property.

**Comment by mlewand** [comment]
I believe someone simply misunderstood the feature, which is a good hint for us - because it tells us what needs to be improved. We could add literally one sentence explaining what readonly mode is, like so:

> Readonly mode means that user can not modify the content, but can still view, select or copy the text contained in editor.

**Comment by scofalik** [comment]
Yeah, I don't understand this issue, TBH. Maybe we should add a line that "switching to read-only mode is done through editor property", so that people won't think it is an additional plugin? 🤔 🤔

**Comment by ma2ciek** [comment]
People always look for copy-paste solutions 😞 Maybe we could link here to https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html to present how to get the `editor`.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/625. All snippets should be accompanied with source code.

**Comment by dkonopka** [comment]
FYI: again request for source code 😄 
<img width="855" alt="Screenshot 2019-04-05 at 09 24 29" src="https://user-images.githubusercontent.com/10219857/55611098-d1e11700-5784-11e9-9815-748e815e9b54.png">

**Comment by irsyadrdp** [comment]
I was trying so hard to understand how to set the readOnly properties in ckeditor 5 by the click of a button using JQuery. In the documentation, it's said that we should use this:

`editor.isReadOnly = true;`

But everytime I tried that code in my own enable or disable function code , I always get an error:

`Uncaught ReferenceError: editor is not defined`

Then I tried to put the jquery selector to my button inside the then promise, and it worked:
```
// Create Ckeditor
ClassicEditor.create( document.querySelector( '#myCkeditorId' ), {
    removePlugins: [ 'Heading'],
    toolbar: [ 'bold', 'italic', 'numberedList', 'blockQuote', 'link' ]
}).then(editor => { 
    // Make Ckeditor disable by default at first creation
    editor.isReadOnly = true; 
        
    // Enable ckeditor by button click
    $('#enable-editor-btn').on('click', function () {
        // Make Ckeditor editable
        editor.isReadOnly = false;
    });
        
    // Disable ckeditor by button click
    $('#disable-editor-btn').on('click', function () {
        // Make CkEditor disable
        editor.isReadOnly = true;
    });
}) 
.catch( error => { console.log( error ); });
```

Idk if this is the correct method, but maybe it'll help
