### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by noxsii** [ckeditor/ckeditor5#16339]
Hi Guys,
i dont know why i get the error: `CKEditorError: ckeditor-duplicated-modules` in this section:

`import BalloonEditor from "@ckeditor/ckeditor5-build-balloon-block"
import {Alignment} from "@ckeditor/ckeditor5-alignment";

class Editor extends BalloonEditor {

    public static override builtinPlugins = [
        Alignment,
        ...BalloonEditor.builtinPlugins
    ]

    public static override defaultConfig  = {
        blockToolbar: [
            'undo',
            'redo',
            '|',
            'heading',
            '|',
            'insertTable',
            'blockQuote',
            'bulletedList',
            'numberedList',
            'alignment',
            '|',
            'link',
        ],
        toolbar: {
            items: [
                'bold',
                'italic',
                'underline',
                'link',
            ]
        },
        table: {
            contentToolbar: [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableCellProperties',
                'tableProperties'
            ]
        },
        language: 'en',
        image: {
            toolbar: [
                'imageTextAlternative',
                'toggleImageCaption',
                'imageStyle:inline',
                'imageStyle:block',
                'imageStyle:side'
            ]
        },
        alignment: {
            options: ['left', 'right']
        },
    }
}

export default Editor`

**Comment by Reinmar** [comment]
Replace:

```
import BalloonEditor from "@ckeditor/ckeditor5-build-balloon-block"
```

With:

```
import BalloonEditor from "@ckeditor/ckeditor5-editor-balloon"
```

The build-\* packages are compiled builds of CKE5. The editor-\* packages contain the source of those. When you build the editor, you need to start with the source and as a result you get a build.

This is confusing and we're currently in the process of changing this :) You can read more in #15502 about the upcoming changes.
