### ISSUE TITLE
ckeditor5-editor-balloon is not interactive after initialization

### ISSUE THREAD

**Issue by lexuzieel** [ckeditor/ckeditor5#16332]
## 📝 Provide detailed reproduction steps (if any)

I am trying to use `@ckeditor/ckeditor5-editor-balloon` package in a Vite project. I've configured Vite [according to the the docs](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html#vite-configuration).

Here is the code I use:

```js
import { BalloonEditor } from '@ckeditor/ckeditor5-editor-balloon';

BalloonEditor.create(textInput, {
}).then(editor => {
  console.log('Editor was initialized', editor);
}).catch(error => {
  console.error(error);
});
```

The editor gets initialized, however it is empty (`textInput` is a div with HTML inside, so normally the editor must get populated with its content). I am also unable to edit it. It's essentially an empty text field into which I cannot insert any text.

### ✔️ Expected result

I get an editable text editor.

### ❌ Actual result

Here is how it looks:
![image](https://github.com/ckeditor/ckeditor5/assets/3730149/07af2025-e02c-4c69-a2e4-29763fe00dad)

This is resulting HTML:

```html
<div id="text-input-container" class="initialized">
        <!-- <div class="grid">
          <div></div>
          <div>
            <a href="#" role="button" title="reset">
              <ion-icon name="search"></ion-icon>
            </a>
          </div>
          <div></div>
        </div> -->
        <div id="text-input" contenteditable="true" class="ck ck-content ck-editor__editable ck-rounded-corners ck-editor__editable_inline ck-blurred" lang="en" dir="ltr" role="textbox" aria-label="Rich Text Editor. Editing area: main"><br data-cke-filler="true"></div>
      </div>
```

### ❓ Possible solution

It works if I use build version instead:
```js
import BalloonEditor from '@ckeditor/ckeditor5-build-balloon';
```

However I need extra plugins for my use case.

## 📃 Other details

* Browser: Firefox
* OS: Windows
* First affected CKEditor version: 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
When setting up an editor from source (via the bare `ckeditor5-editor-balloon` creator), you need to specify all the plugins yourself. The build of the editor balloon has those plugins built in (that's why the "Possible solution" exists).

You'll find the list of plugins that are originally built into the build here: [https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-balloon/src/ckeditor.ts](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-balloon/src/ckeditor.ts)

PS. Yes, this is confusing. We know that and by pure coincidence within the next two months the concept of "editor builds" will be nuked.

**Comment by lexuzieel** [comment]
Thank you for quick response!

Actually, I was pretty close :) I was following the docs but missed that I needed `Paragraph` plugin. After adding it text editing got enabled.

**Comment by mbrodala** [comment]
Same here when trying to set up a `Markdown` editor. After adding the `Paragraph` plugin, all is well. Thanks for the hint!

I wonder if `Paragraph` should be added to `Essentials` since no input is possible otherwise ...
