### ISSUE TITLE
Development version of Collaboration

### ISSUE THREAD

**Issue by GlauberF** [ckeditor/ckeditor5#1634]
as well as the ckeditor, is there any development version of Collaboration

**Comment by Reinmar** [comment]
Collaboration plugins are commercial, propertiary software. They are available on npm, in a built form:

* https://www.npmjs.com/package/@ckeditor/ckeditor5-comments
* https://www.npmjs.com/package/@ckeditor/ckeditor5-track-changes
* https://www.npmjs.com/package/@ckeditor/ckeditor5-real-time-collaboration

However, to use them you need a license key. [Contact us](https://ckeditor.com/contact/) to learn more.
