### ISSUE TITLE
[Docs] Obsolete entry in documentation

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor5#1635]
In guide: https://github.com/ckeditor/ckeditor5/blob/master/docs/framework/guides/architecture/core-editor-architecture.md
this note is not valid any longer:
> Observable properties are marked in API documentation strings with the @observable keyword but we do not mark them in API documentation (yet).

**Comment by Reinmar** [comment]
Thanks! Good catch :) Waiting for a PR now 🏖
