### ISSUE TITLE
Block toolbar's handle tooltip misaligned

### ISSUE THREAD

**Issue by ivukasinovic** [ckeditor/ckeditor5#16365]
We have an issue with the tooltip. 
It happens just on the initial loading of the page and while selecting the rich content (hovering over the handle). 
After that hovers align correctly.

This is also an issue on the official example from [here](https://ckeditor.com/ckeditor-5/demo/editor-types/#balloon-block)  (check last image)

![image](https://github.com/ckeditor/ckeditor5-react/assets/32752225/6a0be5c3-4e76-4dab-9bf3-f1f8f258d3e6)
![image](https://github.com/ckeditor/ckeditor5-react/assets/32752225/87252901-c617-4c62-891b-3807cff6b4a7)
<img width="1261" alt="image" src="https://github.com/ckeditor/ckeditor5-react/assets/32752225/438087d2-77e2-42cb-9183-653f2a7a49ef">

**Comment by Witoso** [comment]
Done.

**Comment by ISilviu** [comment]
Thank you!

**Comment by ISilviu** [comment]
Has anyone managed to have a look at it?

**Comment by Mati365** [comment]
@ISilviu Yep, it's queued. I'll take a look, probably tomorrow.

**Comment by Mati365** [comment]
Notes for further testing. It's fully reproducible on our demos.

**Steps:**

1. Edit this file https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-balloon-block/tests/manual/ckeditor-cjs-version.html#L1
2. Add `margin` and `width` to `#editor` div. Like this: `<div id="editor" style="width: 400px; margin-left: 200px">`
3. Open http://localhost:8125/ckeditor5-build-balloon-block/tests/manual/ckeditor-cjs-version.html
4. Hover tooltip
