### ISSUE TITLE
CKEditor5 v41.4.0 pulls in too many dependencies

### ISSUE THREAD

**Issue by bnf** [ckeditor/ckeditor5#16360]
With v41.4.0 many packages get pulled in by `ckeditor5` npm package, see https://unpkg.com/browse/ckeditor5@41.4.0/package.json compared to https://unpkg.com/browse/ckeditor5@41.3.1/package.json – `@ckeditor/ckeditor5-build-*` is added many more packages which were not pulled in before.

This means a plugin like `@ckeditor/ckeditor5-word-count` (which has a dependency to `ckeditor5`) will pull in all those unneeded dependencies.

_What steps should be taken to fulfill the task?_

Ideally the bundled dependencies should be reverted back to the state from 41.3, or at least `@ckeditor/*` packages should stop requiring and importing from the `ckeditor5` meta package and instead require and import from `@ckeditor/ckeditor5-core` directly (allowing to use `@ckeditor/*` packages only, without the big-meta-package).

_Background info regarding our (TYPO3) usecase_
Note that we package all `@ckeditor/*` packages in TYPO3 core into native ESM modules and this update is problematic, as the (code-wise required) `ckeditor5` package now pulls in too many dependencies, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/84281/1 "Update ckeditor to 41.4"
```
Build/package-lock.json +1788 -310
```
BTW, we already patch CKEditor5 sources build-time to replace `ckeditor5/src` imports by `@ckeditor/ckeditor5-` – see https://github.com/TYPO3/typo3/blob/415f2e93a656e524d45cabf8f766058c41354676/Build/rollup/ckeditor.js#L59-L60 – if `ckeditor5` is now transformed to a meta package – pulling in all packages by design – it would be awesome to get our correction/improvement – to modify all modules to avoid the `ckeditor5/src/` indirection – into CKeditor upstream.

Edit: Further info regarding usage CKeditor5 usage in TYPO3: We ship each `@ckeditor/*` package as one ESM (bunled) per-package ES6 module, loaded via browser native importmaps: https://github.com/TYPO3/typo3/blob/415f2e93a656e524d45cabf8f766058c41354676/typo3/sysext/rte_ckeditor/Configuration/JavaScriptModules.php#L18-L55 (This way we can provide all plugins, but only load those that are configured to be loaded by the TYPO3 integrator)

**Comment by Witoso** [comment]
`v41.4.0` is a broken release, and was marked as such, please don't use it (issues are not related to dependencies).

`v41.4.0` is the first release which “silently” adds [new installation methods](https://github.com/ckeditor/ckeditor5/issues/15502) into the `dist`. `ckeditor5` will be used as an aggregate package, but we are still testing this pre-release. If you expect changes to the TYPO3 ecosystem, please read the whole thread in the linked issue, as other installation methods will be put on the deprecation path.

> we already patch CKEditor5 sources build-time to replace `ckeditor/src` imports by `@ckeditor/ckeditor5-`

AFAIK, we do the same in our Rollup bundling step, and it's already incorporated into our build step, @filipsobol?

**Comment by filipsobol** [comment]
More details: https://github.com/ckeditor/ckeditor5/issues/15502#issuecomment-2114973315

**Comment by filipsobol** [comment]
As per the new design, the `ckeditor5` package has all open source plugins as it's dependencies. To reduce the download size, we have removed unnecessary `@ckeditor/ckeditor5-build-*` packages from `dependencies`.

Once we deprecate the old installation methods, the packages will no longer contain the `src` and `build` folders, further reducing the overall download size.
