### ISSUE TITLE
Why view-position-after-root?

### ISSUE THREAD

**Issue by mulatmar** [ckeditor/ckeditor5#1637]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

ckeditor5@12.0.0 
classic or inline
use @ckeditor/ckeditor5-vue locally
plugins: Essentials, Bold, Italic, Underline, Strikethrough, LinkPlugin, ParagraphPlugin, Alignment, Font, PasteFromOffice, Table, TableToolbar, Listediting, ListUi, Blockquote, Highlight, Autoformat, Image,  ImageToolbar, ImageCaption, ImageStyle, ImageUpload

## 📋 Steps to reproduce

1. Copy text from various sources (CMD + C or CTRL + C or Copy in menu right mouse click)
2. Paste text to editor 

## ✅ Expected result
text is inserted

## ❎ Actual result
text isn't inserted
console message:
Uncaught CKEditorError: view-position-after-root: You can not make position after root. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-position-after-root

## 📃 Other details that might be useful
1. There may be several editor components on the same page.
2. Use v-model directive for vue ckeditor component

Thank you.

**Comment by Reinmar** [comment]
Hi! Could you describe the exact environment and steps to reproduce this? You mention pasting some content into editor, but that's not enough for us to reproduce this.

**Comment by kl3sk** [comment]
I think related to https://github.com/ckeditor/ckeditor5-vue/issues/37

**Comment by mulatmar** [comment]
> I think related to [ckeditor/ckeditor5-vue#37](https://github.com/ckeditor/ckeditor5-vue/issues/37)

Yes. Same problem.

**Comment by mulatmar** [comment]
If I do not use and do not import ImageUpload insert text works. @kl3sk thank you.

**Comment by kl3sk** [comment]
@mulatmar you are welcome, but it still a problem ;)

**Comment by mulatmar** [comment]
> Hi! Could you describe the exact environment and steps to reproduce this? You mention pasting some content into editor, but that's not enough for us to reproduce this.

Hi. When copying text from any source and pasting it to any place in the editor. This view-position-after-root error occurs: You can not make position after root. @kl3sk suggested why the problem occurs. If I import and use ImageUpload plugin occurs this problem. Environment apparently similar to @kl3sk environment.

**Comment by mulatmar** [comment]
> @mulatmar you are welcome, but it still a problem ;)

Yes unfortunately. I think the @Reinmar will help us.

**Comment by kl3sk** [comment]
> 
> 
> > @mulatmar you are welcome, but it still a problem ;)
> 
> Yes unfortunately. I think the @Reinmar will help us.

I hope too.

**Comment by ezhulkov** [comment]
Any progress regarding this issue? I have the same problem with ImageUpload plugin enabled. I can not paste text, getting `You can not make position after root` all the time. 
image dep is: "@ckeditor/ckeditor5-image": "^13.0.0"

**Comment by Reinmar** [comment]
Hm... Could you create a test repo with all the setup needed to reproduce this issue? Neither this ticket, nor the linked one contain all the steps and code.

**Comment by ezhulkov** [comment]
@Reinmar yes sure, here it is https://github.com/ezhulkov/issue1637

This is a brand new project created with vue-init. The only deps installed are ckeditor ones, installation process is taken from https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html

You can npm run dev and try to paste any text. I'm getting this error
Chrome Version 73.0.3683.86, macos 10.14.3

Please pay attention to this line also https://github.com/ezhulkov/issue1637/blob/a7a411a0b893a065cb069aee4cd6013d41749cbf/src/App.vue#L49
Without this rule icons have zero size and invisible.

**Comment by Reinmar** [comment]
The bug is here: https://github.com/ezhulkov/issue1637/blob/master/src/App.vue#L9

You must not add plugins to an existing build. You should use a source editor there.

In fact, in `package.json` you have it installed:

```
    "@ckeditor/ckeditor5-build-classic": "^12.0.0",              // You don't need this
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.0.0",             // It's here
```

So, start using the source editor, not the build and the errors should be gone.

**Comment by Reinmar** [comment]
I checked the guide to be sure and https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source uses `editor-classic`, not `build-classic`. But I'll add a comment there to bring more attention to that fact.

**Comment by Reinmar** [comment]
Done: https://github.com/ckeditor/ckeditor5/commit/5e95b3813daca44f9185852e6c778a353a93597d

I'll close the ticket. If you'll still encounter some issue, let us know – I can reopen it.

**Comment by ezhulkov** [comment]
Oh thanks it works now!
I've seen so many issues regarding adding plugins to ckeditor5-build-classic build :) I think you should double emphasise this pitfall in docs, it's too easy to misread the tutorial. 
Thank you for this beautiful component and thorough docs! cheers

**Comment by Reinmar** [comment]
Thanks. We know we've got to improve this situation. We'll have two mechanisms soon which will warn developers about this:

1. In runtime, some critical modules will check the global scope if they are not duplicated. That's the precise reason why issues occur – some modules are being duplicated. Developers will be warned with a clear information what's wrong.

2. During build time, our webpack plugin will check if there are no duplicated version of some deps. This happens when `package.json` contains conflicting versions of some packages and it leads to the same issue as in 1. However, we would like to warn about this situation ASAP because we can then explain it more precisely what happened.

**Comment by mulatmar** [comment]
@Reinmar, thanks! It works now!
