### ISSUE TITLE
https://www.wiris.net/demo/plugins/app/configurationjs net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by yangjinping1-tal** [ckeditor/ckeditor5#16381]
POST https://www.wiris.net/demo/plugins/app/configurationjs net::ERR_TIMED_OUT

Oops, something went wrong!

**Comment by Reinmar** [comment]
MathType and ChemType (developed by our partner Wiris) are commercial plugins. If this happened in production, please contact support@cksource.com.
