### ISSUE TITLE
Online demos not loading

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#1638]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Online demos

## 📋 Steps to reproduce

1. Open page https://ckeditor5.github.io/

## ✅ Expected result
See the editor

## ❎ Actual result
Error message

## 📃 Other details that might be useful
Yesterday is was working fine.
Tried using Chrome and Firefox.

**Comment by Reinmar** [comment]
![image](https://user-images.githubusercontent.com/156149/54680459-32781f00-4b0a-11e9-94cb-8d3666d02bb8.png)

That's new :O Checking...

**Comment by scofalik** [comment]
We checked and fixed the issue, looks that it is working now.

**Comment by dkrahn** [comment]
Thanks! All ok here too!
