### ISSUE TITLE
Intercept text removal to "keep" comments, attached to it

### ISSUE THREAD

**Issue by nikitin-** [ckeditor/ckeditor5#16392]
Hello! 
I'm looking for the feature in ckeditor to keep track of "deleted comments"
1. Create a text and add comment over it
2. Delete the text - this will also delete the comment (comment thread), attached to it.

I need to somehow intercept the text removal to "keep" comments, attached to it.

[Screencast from 20.05.2024 16:16:04.WEBM](https://github.com/ckeditor/ckeditor5/assets/4816390/125e9442-25d6-41b4-9759-9fe6beb5b368)

Thank you in advance!

**Comment by nikitin-** [comment]
Now I'm playing around with **registerPostFixer** and **getMarkersToRemove** but not sure that this is a good way. ...

```const document = this.editor.model.document
document.registerPostFixer( writer =>  {
    const changes = document.differ.getChanges();
    const del_markers = document.differ.getMarkersToRemove()
    if (del_markers) {
        debugger;
    }
});
```

**Comment by Witoso** [comment]
Hi! As per [docs](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-walkthrough.html#unlinked):

> When you remove the document content related to a comment thread from the document, the comment thread becomes unlinked. It is then moved to the comments archive. Since it has not been technically resolved, it does not display the usual related information.

You can access those comments via [**`archivedThreads`**](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_comments_commentsarchive-CommentsArchive.html#member-archivedThreads). Hope this helps!

**Comment by nikitin-** [comment]
@Witoso - Thank you for the answer! 
Is **CommentsArchive** (@ckeditor/ckeditor5-comments/src/comments/commentsarchive) a _separate_ plugin or it comes bundled to ckeditor5 "core" ? 

As for now I have ckeditor5 version 35.4.0-1 (in some entreprise software :) ) - so  I can not "upgrade" it.

**Comment by Witoso** [comment]
`CommentsArchive` appeared in [v37.0.0](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-37.html#comments-archive), with changes in the deleted content in [v40.0.0](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-40.html#changes-to-the-comments-feature). I strongly suggest upgrading; otherwise you would need to duplicate the feature that is provided out of the box :)

**Comment by nikitin-** [comment]
@Witoso 
ok - in case when I can not upgrade to these versions ... Is it a good start point to grab the deleted comments like this ? https://github.com/ckeditor/ckeditor5/issues/16392#issuecomment-2120489360
