### ISSUE TITLE
Problem installing the plugin

### ISSUE THREAD

**Issue by karaka200** [ckeditor/ckeditor5#16399]
Hello. I want to add a plugin with the `https://ckeditor.com/docs/ckeditor5/latest/features/font.html#installation` directive. When I use the following code:
```
import { Controller } from "@hotwired/stimulus";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import '@ckeditor/ckeditor5-build-classic/build/translations/fr.js';
import { Font } from "@ckeditor/ckeditor5-font";

/* stimulusFetch: 'lazy' */
export default class extends Controller {
  static targets = ["editor", "test"];

  connect() {
    ClassicEditor
        .create(this.editorTarget,  {
            language: 'fr',
            ui: {
                viewportOffset: { top: 58 },
                poweredBy: {
                    label: null,
                    side: 'left',
                }
            },
            plugins: [ Font, /* ... */ ],
            toolbar: [ 'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', /* ... */ ]
        })
        .then(editor => {
            console.log(editor);
        })
        .catch((error) => {
          console.log(error);
        });
  }
}
```
this error was displayed:

> Uncaught CKEditorError: ckeditor-duplicated-modules
> Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
>     CKEditorError ckeditorerror.js:57
>     node_modules vendors-node_modules_ckeditor_ckeditor5-build-classic_build_ckeditor_js-node_modules_ckeditor-d9cbfd.js:103264
>     Webpack 32

How can I fix this problem?

**Comment by kerwin-ly** [comment]
I encountered the same error recently, as [error details](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules) mentioned, u cant import a built ckeditor which might cause duplicated compilation issue. So im thinking u can try to replace
```js
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
```
with below one first and move on.
```js
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
```
There's a basic plugin [demo](https://github.com/ckeditor/ckeditor5-tutorials-examples/tree/main/timestamp-plugin/final-project), btw.

**Comment by Witoso** [comment]
That's right, build packages cannot be extended with plugins. We are improving this issue with #15502, and it should be gone soon.

**Comment by Witoso** [comment]
@kerwin-ly, you can use the cleaner index import: 
```js
import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic';

```

**Comment by kerwin-ly** [comment]
@Witoso , ye, thanks for remind

**Comment by karaka200** [comment]
Thanks a lot
