### ISSUE TITLE
Install media-embed using CDN or Yarn in CKEditor

### ISSUE THREAD

**Issue by conangithub** [ckeditor/ckeditor5#1642]
Hello, I am using CKEditor 5 that installed using CDN
`<script src="https://cdn.ckeditor.com/ckeditor5/10.1.0/classic/ckeditor.js"></script>`

How could I install this media-embed package using CDN?
https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html

If cannot, how do I install it using yarn?

**Comment by Mgsy** [comment]
Hello, it's not possible to install a plugin via CDN. You have to prepare a build which includes your plugin. Please, take a look at our [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) guide.

**Comment by conangithub** [comment]
By using update to version 12.2.0, it has default button/function to embed-media. Thank you. My problem is solved.
