### ISSUE TITLE
Weird case with attribute removal in model post-fixer

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1645]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Register attribute post-fixer:

```js
editor.model.document.registerPostFixer( writer => {
	const changes = editor.model.document.differ.getChanges();

	let wasChanged = false;

	for ( const change of changes ) {
		if ( change.type == 'insert' || change.type == 'remove' ) {
			const textNode = change.position.textNode;

			if ( change.name == '$text' && textNode && textNode.hasAttribute( 'bold' ) ) {

				writer.removeAttribute( 'bold', textNode );
				wasChanged = true;
			}
		}
	}

	return wasChanged;
} );
```
2. bold text ie `bold`
3. delete some char, ie `l` (forward or backward delete)
4. the model has correct state `<paragraph><$text bold="true">bo[]d</$text></paragraph>`
5. the view has incorrect state: `<p>bo[]l</p>`
6. execute undo

## ✅ Expected result

The text after deletion is `bod` in the view.
The text after undo id `bold` in the view.
The text after undo has `bold` attribute in the model.

## ❎ Actual result

The text after deletion in the editing area is `bol`.
The text after undo id `boll` in the view.
The text after undo doesn't have `bold` attribute.

## 📃 Other details that might be useful

Screen cast:
![Peek 2019-03-22 10-15](https://user-images.githubusercontent.com/247363/54812942-a6423500-4c8c-11e9-963d-6577f0589b75.gif)

**Comment by jodator** [comment]
ps.: The same happens on FF and Chrome.

**Comment by scofalik** [comment]
I confirm the bug.

Quick observation: when removing, always the last letter is removed, unless the first letter is removed. When typing, the typing itself is fine but undo fails.

**Comment by scofalik** [comment]
This is a bug in `Differ`. A quite serious one, it is funny that it didn't come up earlier but I guess we never had a scenario where a word changed an attribute and also got something removed/added.

**Comment by scofalik** [comment]
Okaaay, so https://github.com/ckeditor/ckeditor5-engine/pull/1705 this fixes the issue with `Differ`. Attribute change was incorrectly stored if there was a remove change with intersecting range.

However, this does not fix not-bolding on undo. In fact, everything works correctly. The bold **is** applied, but since also there is a letter inserted (or removed) during the undo, the bold is immediately taken off.

So the post-fixer like this for mentions is not correct.
