### ISSUE TITLE
CKEditor removes mark-styles

### ISSUE THREAD

**Issue by Maqsyo** [ckeditor/ckeditor5#1646]
## Is this a bug report or feature request? (choose one)
🐞 Bug report

## 💻 Version of CKEditor
        "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.0",
        "@ckeditor/ckeditor5-autoformat": "^11.0.0",
        "@ckeditor/ckeditor5-basic-styles": "^11.0.0",
        "@ckeditor/ckeditor5-block-quote": "^11.0.0",
        "@ckeditor/ckeditor5-ckfinder": "^11.0.0",
        "@ckeditor/ckeditor5-core": "^12.0.0",
        "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
        "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
        "@ckeditor/ckeditor5-easy-image": "^11.0.0",
        "@ckeditor/ckeditor5-editor-classic": "^12.0.0",
        "@ckeditor/ckeditor5-essentials": "^11.0.0",
        "@ckeditor/ckeditor5-font": "^11.0.0",
        "@ckeditor/ckeditor5-heading": "^11.0.0",
        "@ckeditor/ckeditor5-highlight": "^11.0.0",
        "@ckeditor/ckeditor5-image": "^13.0.0",
        "@ckeditor/ckeditor5-link": "^11.0.0",
        "@ckeditor/ckeditor5-list": "^12.0.0",
        "@ckeditor/ckeditor5-media-embed": "^11.0.0",
        "@ckeditor/ckeditor5-paragraph": "^11.0.0",
        "@ckeditor/ckeditor5-paste-from-office": "^11.0.0",
        "@ckeditor/ckeditor5-table": "^12.0.0",
        "@ckeditor/ckeditor5-theme-lark": "^13.0.0",
        "@ckeditor/ckeditor5-upload": "^11.0.0",

## 📋 Steps to reproduce

1. Mark some Content
2. Save it
3. Load it again

## ✅ Expected result
Marked Content is still visible in editor

## ❎ Actual result
Marked content get filtered out of editor
![image](https://user-images.githubusercontent.com/19644698/54833670-da364e00-4cbe-11e9-952f-ca459bb08193.png)
This content is correctly stored in the database

On reloading the marked element gets unmarked
![image](https://user-images.githubusercontent.com/19644698/54833748-fcc86700-4cbe-11e9-985a-56dda9c27753.png)

This string is stored in the database:
```
<p>This is a <mark class="marker yellow">marked </mark>text.</p><p>&nbsp;</p><p>This isn't</p>
```

My highlight-config:
```
highlight: {
        options: [
            {
                model: 'yellowMarker',
                class: 'marker yellow',
                title: 'Gelber Marker',
                color: '#ffeb3b',
                type: 'marker'
            }
        ]
}
```

**Comment by Mgsy** [comment]
Hi, I believe there is a problem in your class name - `marker yellow`. It appears properly after adding a highlight, but is not set after using `editor.setData()`. See below:

![bug_cke5](https://user-images.githubusercontent.com/20988892/54908286-d20d2700-4ee7-11e9-883e-37bb234b5df8.gif)

@Reinmar, is it expected behaviour? 

@Maqsyo, try to convert your class name to a single word, i.e. `marker-yellow` and check whether a marker is preserved after a reload.

**Comment by Maqsyo** [comment]
It worked in the previous version and was good for me to have one main class (marker) for the same css-properties.
So for example i could combine a text-color with a pen:
`pen text-gray-500`
It would be a shame if i had to redefine text-gray-500 only for pen

with marker-yellow it works perfectly ...

**Comment by Mgsy** [comment]
>It worked in the previous version and was good for me to have one main class (marker) for the same css-properties.

Are you sure it was ok in the previous version? I've checked two previous releases and I was able to reproduce it.

**Comment by Maqsyo** [comment]
It worked perfectly before the update. I'm pretty sure. It was tested multiple times.

These were the package.json before:
```
        "@ckeditor/ckeditor5-adapter-ckfinder": "^10.0.4",
        "@ckeditor/ckeditor5-autoformat": "^10.0.4",
        "@ckeditor/ckeditor5-basic-styles": "^10.1.0",
        "@ckeditor/ckeditor5-block-quote": "^10.1.1",
        "@ckeditor/ckeditor5-ckfinder": "^10.0.0",
        "@ckeditor/ckeditor5-core": "^11.1.0",
        "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
        "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.0",
        "@ckeditor/ckeditor5-easy-image": "^10.0.4",
        "@ckeditor/ckeditor5-editor-classic": "^11.0.2",
        "@ckeditor/ckeditor5-essentials": "^10.1.3",
        "@ckeditor/ckeditor5-font": "^10.0.4",
        "@ckeditor/ckeditor5-heading": "^10.1.1",
        "@ckeditor/ckeditor5-highlight": "^10.0.4",
        "@ckeditor/ckeditor5-image": "^12.0.0",
        "@ckeditor/ckeditor5-link": "^10.1.0",
        "@ckeditor/ckeditor5-list": "^11.0.3",
        "@ckeditor/ckeditor5-media-embed": "^10.1.0",
        "@ckeditor/ckeditor5-paragraph": "^10.0.4",
        "@ckeditor/ckeditor5-paste-from-office": "^10.0.0",
        "@ckeditor/ckeditor5-table": "^11.0.1",
        "@ckeditor/ckeditor5-theme-lark": "^12.0.0",
        "@ckeditor/ckeditor5-upload": "^10.0.4"
```

But yeah.. i couldn't get it to work again with these packages ...
I'm confused..
Thank you anyway.. so i have to do it with single classes... mhpf

**Comment by Mgsy** [comment]
Thanks for sharing your `package.json`. I've checked it and this behaviour is still the same as now, so it's not a regression.
