### ISSUE TITLE
CKEditor cannot be used when deploying IIS

### ISSUE THREAD

**Issue by nguyentienanh59** [ckeditor/ckeditor5#16464]
Hello @Reinmar , I have a question. I used ckeditor custombuild, everything was fine until I deployed them to IIS, then CK almost stopped working and reported the error below. I couldn't find a solution, so I came here. Here to seek help from everyone.!!!!

Below is my config file and error, please see
![image](https://github.com/ckeditor/ckeditor5/assets/59440694/2d933dba-60d7-4b1e-8cd8-29be052bd694)
![image](https://github.com/ckeditor/ckeditor5/assets/59440694/a6eac2fc-24a3-4d00-a541-45ed29e77e92)
![image](https://github.com/ckeditor/ckeditor5/assets/59440694/1814cc63-2eaf-42af-927d-cba222fe61d3)

**Comment by Reinmar** [comment]
I'm sorry, but I have no idea what might've gone wrong upon deploy to IIS to give such errors.

I'm afaraid you need to investigate the issue yourself.

**Comment by nguyentienanh59** [comment]
I have resolved the above errors but now it is reporting an error when I deploy: "TypeError: Failed to resolve module specifier "ckeditor5-custom-build". Relative references must start with either "/", "./", or "../".
below is my vite file, how do i need to repair it. Hope you help!
`import commonjs from 'vite-plugin-commonjs';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';

export default defineConfig({
  plugins: [react(), commonjs()],
  base: '/',
  optimizeDeps: {
    include: ['ckeditor5-custom-build/build/ckeditor'],
    esbuildOptions: {
      target: 'esnext'
    }
  },
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html')
      },
      external: ['ckeditor5-custom-build']
    },
    commonjsOptions: {
      include: [/node_modules/, 'ckeditor5-custom-build/build/ckeditor']
    }
  },
  css: {
    preprocessorOptions: {
      less: {
        math: 'always',
        globalVars: {},
        javascriptEnabled: true
      },
      scss: {
        additionalData: `
        @import "./src/common/assets/scss/variables/_variables.scss";
        @import "./src/common/assets/scss/variables/_mixin.scss";`
      }
    }
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      'app-admin': resolve(__dirname, './src/app-admin'),
      '@fonts': resolve(__dirname, 'src/common/assets/font')
    }
  },
  assetsInclude: ['**/*.svgx']
});
`
![image](https://github.com/ckeditor/ckeditor5/assets/59440694/e3675035-ead3-4195-bef7-b1d90b1a4bc3)
![image](https://github.com/ckeditor/ckeditor5/assets/59440694/311837c9-3ea1-43b5-ba79-a9deb84e6502)
![image](https://github.com/ckeditor/ckeditor5/assets/59440694/bb60926f-5942-4bc2-99f8-3d3900eb2b3a)
