### ISSUE TITLE
Plug-ins using viewwriter.createContainerElement and SVG

### ISSUE THREAD

**Issue by fairmutex** [ckeditor/ckeditor5#1647]
🐞 Bug report  

## 💻 Version of CKEditor

    "@ckeditor/ckeditor5-basic-styles": "^11.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.0.0",
    "@ckeditor/ckeditor5-essentials": "^11.0.0",
    "@ckeditor/ckeditor5-heading": "^11.0.0",
    "@ckeditor/ckeditor5-list": "^12.0.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^13.0.0",
    "@ckeditor/ckeditor5-widget": "^11.0.0",
   "@ckeditor/ckeditor5-inspector": "^1.3.0"

## 📋 Steps to reproduce

During downcast loading SVG as below causes it not to render. It can be seen with inspector as in the picture below.

` const svg = viewWriter.createContainerElement("svg",{ class:"tag-svg", focusable:"false", viewBox:"0 0 24 24"});
  const path = viewWriter.createEmptyElement("path",{d:"M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm5 13.59L15.59 17 12 13.41 8.41 17 7 15.59 10.59 12 7 8.41 8.41 7 12 10.59 15.59 7 17 8.41 13.41 12 17 15.59z"});
  viewWriter.insert( viewWriter.createPositionAt(svg , 0 ),  path);`

![svggg](https://user-images.githubusercontent.com/4706582/54865565-774cc180-4d67-11e9-8092-203856a40585.PNG)

...

## ✅ Expected result

The SVG gets rendered

## ❎ Actual result

SVG does not get rendered

## 📃 Other details that might be useful

Creating widgets one might want interaction. SVGs are perfect to style on hover etc.

**Comment by Mgsy** [comment]
Hi, just to clarify - you're able to see your SVG in the model, but it's not rendered in the view, right? Could you share with us your converters code?

>Creating widgets one might want interaction

Did you see our [creating widgets guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html)?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by farcry550** [comment]
I believe I'm running into the same thing, looks to be because viewBox is being lowercased to viewbox during downcasting.
