### ISSUE TITLE
React "Multi-root integration" guide is still based on editor build package

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#16479]
## 📝 Provide a description of requested docs changes

React "Multi-root integration" guide is still based on editor build package (`@ckeditor/ckeditor5-build-multi-root`), see https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/installation/react/react-multiroot.html.

It's not in "Legacy" section and marked as `New` so probably not the way we want.

**Comment by Witoso** [comment]
This should be rewritten to `-editor` package.

**Comment by Witoso** [comment]
Solved by: https://github.com/ckeditor/ckeditor5/pull/16526
