### ISSUE TITLE
Broken Crash Course repo link (Framework > Tutorials)

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#16477]
## 📝 Provide a description of requested docs changes

The crash course link leads to 404, on this page - https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/tutorials/crash-course/editor.html:
![image](https://github.com/ckeditor/ckeditor5/assets/1061942/2c0cee75-4a65-4d54-9c23-bfb1cd7e9299)

From what I see in stable docs it should lead to different repo - https://github.com/ckeditor/tutorial-setup. Also backlink in this repo README points to old structure (where `Tutorials` were top level category).

**Comment by Witoso** [comment]
Some PRs are not merged, and wait for the release date:

*   [https://github.com/ckeditor/ckeditor5-tutorials-examples/tree/new-installation-methods](https://github.com/ckeditor/ckeditor5-tutorials-examples/tree/new-installation-methods)

**Comment by gorzelinski** [comment]
It's expected (for now) - I would close the issue.
