### ISSUE TITLE
"Editor builds" are mentioned in tables overview guide

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#16489]
## 📝 Provide a description of requested docs changes

In https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/tables/tables.html#table-contextual-toolbar, there's a mention of "editor builds":
<img width="858" alt="editor-build-tables" src="https://github.com/ckeditor/ckeditor5/assets/132071257/9f8f353d-aee3-402b-bc6c-544aa58047a9">

**Comment by godai78** [comment]
Fixed in d360ae7
