### ISSUE TITLE
Style import snippet in "Styling the published content" seems vague/confusing

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#16488]
## 📝 Provide a description of requested docs changes

The "Editor and content styles" page (https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/setup/css.html) describes how content is styled, showing first how to import styles (via CDN and npm):

![image](https://github.com/ckeditor/ckeditor5/assets/1061942/72e85c3b-08a5-4b45-8db3-a09c19a697ac)

Then it describes how to apply those styles to editor output:

![image](https://github.com/ckeditor/ckeditor5/assets/1061942/f3dcdab7-9608-497e-9ef7-086b2606cb5e)

This 2nd code snippet is quite confusing (at least for me 😅). Because I assume here, one would either use CDN (if it was used to import editor) like:

```html
<link rel="stylesheet" href="https://cdn.ckeditor.com/ckeditor5/41.4.2/ckeditor5-content.css">

<!-- If you are using premium features: -->
<link rel="stylesheet" href="https://cdn.ckeditor.com/ckeditor5/41.4.2/ckeditor5-premium-features-content.css">
```

or npm import:

```js
import 'ckeditor5/ckeditor5-content.css';

// If you are using premium features:
import 'ckeditor5-premium-features/ckeditor5-premium-features-content.css';
```

Having customized paths to CSS files like `path/to/assets/ckeditor5-content.css` would require some customized build process, moving those files manually or similar. Which makes it confusing and hard to understand since it's not default approach. And there is no mention how those files would "land" in this path.

**Comment by Witoso** [comment]
Good feedback! Let me think about it!

**Comment by Witoso** [comment]
The confusion was caused by the order of section, I think. I changed it, as I'm not sure if @f1ames you caught that this is not related to the editor or builds. It's only related to the place that the content is published to. I also added more explanatory texts around this section.
