### ISSUE TITLE
Inconsistent spacing between imports

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#16486]
## 📝 Provide a description of requested docs changes

The spacing between imports in docs snippets is not always consistent, for example:
- In https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/installation/quick-start.html, there's no empty line above style imports:
<img width="1230" alt="empty-line-quick-start" src="https://github.com/ckeditor/ckeditor5/assets/132071257/c2552279-61b2-40da-9270-5c8c2d0deeef">

- In integration guides - e.g. https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/installation/angular.html, the line is present:
<img width="1231" alt="empty-line-angular" src="https://github.com/ckeditor/ckeditor5/assets/132071257/3d7069f5-4c23-484d-adf0-3ad57247e0a2">

- In https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/setup/ui-language.html, there's no empty line above translation imports:
<img width="1219" alt="ui-language-translations" src="https://github.com/ckeditor/ckeditor5/assets/132071257/421fc122-7fb5-408b-b1ea-a67fb655eb80">

**Comment by godai78** [comment]
Fixed in 3c945a4
