### ISSUE TITLE
Link to builder for integrations docs redirects user to CKE4 online builder

### ISSUE THREAD

**Issue by michalbilik** [ckeditor/ckeditor5#16484]
## 📝 Provide a description of requested docs changes

The link to the builder for integrations redirects to CKE 4 builder: https://ckeditor.com/builder?redirect=docs
The links will be updated, but I think this should point to the correct builder already. 

![Screenshot 2024-06-05 at 13 16 00](https://github.com/ckeditor/ckeditor5/assets/50703222/8ff04849-e35a-477f-b95b-dc702813d8a5)

**Comment by Witoso** [comment]
We should use the proper link: [https://ckeditor.com/ckeditor-5/builder/](https://ckeditor.com/ckeditor-5/builder/) I think to not hit redirect.

**Comment by Witoso** [comment]
Done
