### ISSUE TITLE
[Docs] Broken React snippet in the New Installation Methods guide

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#16495]
## 📝 Provide a description of requested docs changes

In typescript this [snippet](https://github.com/ckeditor/ckeditor5/blob/master/docs/getting-started/integrations/react.md?plain=1#L188-L225) causes some errors, like this:

![Screenshot 2024-06-05 at 14 40 31](https://github.com/ckeditor/ckeditor5/assets/47000454/153d7fec-b3fe-4b2e-888c-3b7f4b1d403b)

so that caught our attention and we come to the conclusion snippet was simply wrong.

We need to update it to:

```
import React, { useCallback, useRef } from 'react';
import { DecoupledEditor, Bold, Essentials, Italic, Paragraph } from 'ckeditor5';
import { CKEditor } from '@ckeditor/ckeditor5-react';

import 'ckeditor5/ckeditor5.css';

function App() {
    const editorToolbarRef = useRef( null );
    const editorRef = useRef( null );

    const isLayoutReady = useCallback( () => {
        return [ editorRef, editorToolbarRef ].every( Boolean );
    }, [ editorRef, editorToolbarRef ] );

    return (
        <div>
            <div ref={ editorToolbarRef }></div>
            <div ref={ editorToolbarRef }>
                { isLayoutReady() && (
                    <CKEditor
                        onReady={ ( editor ) => {
                            Array.from( editorToolbarRef.current!.children ).forEach( child => child.remove() );
                            editorToolbarRef.current!.appendChild( editor.ui.view.toolbar.element! );
                        }}
                        editor={ DecoupledEditor }
                        data='<p>Hello from CKEditor 5 decoupled editor!</p>'
                        config={ {
                            plugins: [ Bold, Italic, Paragraph, Essentials ],
                            toolbar: [ 'undo', 'redo', '|', 'bold', 'italic' ]
                        } }
                    />
                ) }
            </div>
        </div>
    );
}

export default App;
``` 

_What is the purpose and what should be changed?_

**Comment by Witoso** [comment]
What is TypeScript doing here? @gorzelinski do you remember if the snippet was taken from Builder, maybe something is wrong there as well.

**Comment by gorzelinski** [comment]
I re-paste my comment:
I was raising the same question during online builder tests. As far I remember, React snippets from the builder look similar and contain the useState hooks for refs. The same hooks in the docs are for unification. Or we have a situation where the snippets from the builder should differ from those in the docs?

**Comment by Witoso** [comment]
We need to discuss the impact of this on the Builder, cc @pomek

**Comment by pomek** [comment]
```
const editorToolbarRef = useRef( null );
const editorRef = useRef( null );

const isLayoutReady = useCallback( () => {
    return [ editorRef, editorToolbarRef ].every( Boolean );
}, [ editorRef, editorToolbarRef ] );
```

This is wrong too. `editorToolbarRef` is an object (`{ current: null }`). It should be:

```
const isLayoutReady = useCallback( () => {
    return [ editorRef.current, editorToolbarRef.current ].every( Boolean );
}, [ editorRef, editorToolbarRef ] );
```

However, we should still use `useState()` instead of `useRef()`. This is done purposely. We can talk about it before updating.

As for TypeScript errors, Builder output produces JSX, not TSX. It's almost the same but a bit different.

**Comment by Mati365** [comment]
In my opinion, @illia-stv is correct. Using `useState` is not the “React” way to solve this issue, but his snippet needs a slight adjustment. Here’s why:

1. **Purpose of `useState`:** `useState` was designed to store serializable data that is later used in creating an interface.
2. **Compatibility Concerns:** Assigning `useState` setters to `ref={}` is not guaranteed to work in future React versions. It’s likely to change.
3. **Strict Mode Behavior:** The approach generates a cascade of re-renders and may behave incorrectly in **StrictMode** (where hooks are called twice).
4. **Ref Timing:** Checking an array of refs using `useCallback` doesn’t make sense because refs are filled after rendering all children nodes of the component.

I recommend using the `useIsLayoutReady` approach, which works correctly in `StrictMode` and aligns with React’s philosophy for managing state.

```tsx
import React, { useCallback, useRef } from 'react';
import { DecoupledEditor, Bold, Essentials, Italic, Paragraph } from 'ckeditor5';
import { CKEditor } from '@ckeditor/ckeditor5-react';

import 'ckeditor5/ckeditor5.css';

function App() {
    const editorToolbarRef = useRef( null );
    const isUIReady = useIsLayoutReady();

    return (
        <div>
            <div ref={ editorToolbarRef }></div>
            <div>
                { isUIReady && (
                    <CKEditor
                        editor={ DecoupledEditor }
                        data='<p>Hello from CKEditor 5 decoupled editor!</p>'
                        config={ {
                            plugins: [ Bold, Italic, Paragraph, Essentials ],
                            toolbar: [ 'undo', 'redo', '|', 'bold', 'italic' ]
                        } }
                        onReady={ ( editor ) => {
                            editorToolbarRef.current!.appendChild( editor.ui.view.toolbar.element! );
                        }}
                        onAfterDestroy={ ( editor ) => {
                            if ( editorToolbarRef.current ) {
                                Array.from( editorToolbarRef.current.children ).forEach( child => child.remove() );
                            }
                        }}
                    />
                ) }
            </div>
        </div>
    );
}

function useIsLayoutReady() {
    const [ isMounted, setMounted ] = useState( false );
    
    useEffect( () => {
       setMounted( true );
       
       return () => {
           setMounted( false );
       };
    }, [] );

   return isMounted;
}

export default App;
```

**Comment by Mati365** [comment]
@Witoso / @pomek / @illia-stv / @filipsobol I created example with `minimap` / `toolbar` / `menubar` / `editorOutlineRef` and it works absolutely normal. 

![obraz](https://github.com/ckeditor/ckeditor5/assets/3949262/85c04267-7878-48b5-b525-a15f24ec7a77)

**Source code:**

[Example.zip](https://github.com/user-attachments/files/15617123/Example.zip)

1. `npm install`
2. `npx parcel index.html`

**Comment by Mati365** [comment]
@pomek yep

**Comment by pomek** [comment]
TBH, that's sounds good. It's unified between the frameworks now. _Set the flag once after rendering for the first time._

**Comment by pomek** [comment]
You can regenerate the snippet using the tool you used before. It now produces the `useRef` output instead of `useState`.
