### ISSUE TITLE
Quick start snippet and smoother Quick start > Setup > Crash course flow

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#16497]
## 📝 Provide a description of the improvement

Our Quick start snippet won't run as we have the license key in there. The road becomes bumpy as someone needs to divert to a trial sign up.

Potential solutions:

*   split premium and OSS,
*   trial license key created by us?

**Comment by godai78** [comment]
I'm against splitting, we have only just put it together last week or so and this was a right decision. If we can afford a free trial key, then maybe it is a solution. But while I see the point, maybe we should just put a comment "remove it, if you don't need it" which is quick, effective and does not redirect the user for a whole of 10 minutes.  
  
Yes for the editor type guide, however, it would either be pretty dry - one liners with an image or duplicating the Examples demos (the latter would be much cooler, not sure, tho, whether we can put all that stuff on the same page and it would make the guide LONG). I'd rather be in for the short version linking examples.  
  
Right now QS directs the users to the Setup section with two links at the bottom, this is IMHO much better than the Crash course, cause everyone will need that (unlike the Course).  
  
Further directing from Setup to CC would require having a user path - we used to have one in the old docs, but gradually abandoned it preparing NIM docs.

**Comment by Witoso** [comment]
> Yes for the editor type guide, however, it would either be pretty dry.
One way I could think of adding it is by tweaking Configuring features. We should treat the possibility of changing the editor UIs as a feature, so it fits there.

**Comment by Witoso** [comment]
Export to PDF as it doesn't need license.

**Comment by Witoso** [comment]
Split the free and premium setup paths.

ToC:

*   Installing CKEditor 5 using npm
*   Installing CKEditor 5 from CDN
*   Installing premium features (or similar)
    *   Obtaining license key
    *   npm
    *   CDN
*   Next steps

In premium features, we decided to use `Font` and `FormatPainter`. I think the OSS should reflect Premium so we should add `Font` to OSS as well.

**Comment by Witoso** [comment]
Closed by: #16517
