### ISSUE TITLE
The toolbar does not resize itself when the CKEditor's width is changing.

### ISSUE THREAD

**Issue by miskotam** [ckeditor/ckeditor5#1650]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

I use 11.1.1, but it also can be reproduced with the version which is used for the CKEditor examples.

## 📋 Steps to reproduce

1. Open [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html](url) in Mozzilla Firefox (65.0.2)
2. Shrink the browser window.
3. Click inside the editor.
4. Scroll the text under the CKEditor's toolbar
5. Expand the browser window to increase its width.

## ✅ Expected result
The toolbar is expanding with the browser
## ❎ Actual result
The toolbar is not resizing
## 📃 Other details that might be useful

![2019-03-26_09-29-15](https://user-images.githubusercontent.com/17469169/54982198-85d6eb00-4faa-11e9-92ff-77b77f52e321.gif)

**Comment by Mgsy** [comment]
Hello, thanks for the report. We are aware of this issue and there is a proper ticket for this case - https://github.com/ckeditor/ckeditor5-ui/issues/411.
