### ISSUE TITLE
Mention of "ready–to–use builds" in Third-party UI guide

### ISSUE THREAD

**Issue by kubaklatt** [ckeditor/ckeditor5#16519]
## 📝 Provide a description of requested docs changes

The following guide includes a mention of "ready–to–use builds":

http://127.0.0.1:8080/ckeditor5/latest/framework/deep-dive/ui/external-ui.html#readying-the-editor-side

![image](https://github.com/ckeditor/ckeditor5/assets/90427796/69dfbf04-241f-437e-b5fe-8f5d4b1655d2)

**Comment by godai78** [comment]
Covered by #16514
