### ISSUE TITLE
DataController usage

### ISSUE THREAD

**Issue by Espumisan** [ckeditor/ckeditor5#1651]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other
Please make DataController documentation with usage samples!

## 💻 Version of CKEditor
@ckeditor/ckeditor5-build-classic": "^12.0.0
@ckeditor/ckeditor5-vue": "^1.0.0-beta.1

## 📋 Steps to reproduce

1. import DataController from '@ckeditor/ckeditor5-engine/src/controller/datacontroller'
2. console.log('DataController', DataController.model)

## ✅ Expected result
_https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_controller_datacontroller-DataController.html_ features
## ❎ Actual result
**Undefined**

**Comment by Reinmar** [comment]
Hi! `DataController` is a class. Classes need to be instantiated before they can be used. So the right way to use it is to do it like this:

```js
import DataController from '@ckeditor/ckeditor5-engine/src/controller/datacontroller';

const dataController = new DataController( editor.model, someDataProcessor );

console.log( dataController.model );
```

Meaning that you also have to have an instance of a data processor (the second param) and, first of all, an editor instance. To learn what kind of data processors are available you need to browse the API docs, check the type of `dataProcessor` param of the `DataController`'s `constructor()` and you'll get to https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_dataprocessor_dataprocessor-DataProcessor.html where there's a list of classes which implement this interface.

To be honest, this is a fairly basic OOP case. Also, this isn't actually a class to be often used by developers – there's a tone of other things one would need to understand before starting to creating their own data controller. Most of those things can be found in the existing source code of existing editor implementations. I'd recommend looking for examples there.

However, you're right that the API docs for this class could be better. This is true for most of the classes and this is an issue that we're aware of so to avoid fragmentation, I'll close this ticket.

**Comment by Espumisan** [comment]
It's not about OOP it's about explaining if this is already initialized by default when editor loads, what does this calls accepts etc.

**Comment by Reinmar** [comment]
You're right. That's the part of docs we're missing – showing that an instance of this class is available in `editor.data`. I'll add a note about it.

**Comment by Reinmar** [comment]
Done in https://github.com/ckeditor/ckeditor5-engine/commit/606827cf0b907e3a82121c166a31928ae2edb4f4.
