### ISSUE TITLE
New Next.js integration guide seems incomplete

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#16527]
## 📝 Provide a description of requested docs changes

The previous guide was mostly about integrating build from online builder with "Preparing a build" section and then detailed section on "Integrating the build in your Next.js project" - https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/next-js.html.

![image](https://github.com/ckeditor/ckeditor5/assets/1061942/92fa6f79-f9c3-4e6d-98b2-d7c22a7ca187)

The new one, adjusted to NIM also starts with "Using CKEditor 5 Builder" (which is previous "Preparing a build"), but then shows how to integrate with next.js using npm installed packages ("Installing from npm"), there is nothing about how to integrate build from builder. See https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/installation/next-js.html.

![image](https://github.com/ckeditor/ckeditor5/assets/1061942/12813fd1-a060-4be4-9c6c-1b55dea9fb47)

Maybe it's intended, but seems incomplete. Especially that first "Using CKEditor 5 Builder" section seems to promote this way of integrating, but then there is nothing about it further.

**Comment by Witoso** [comment]
I guess we assumed, that if someone goes to Builder they will not return, but we may smooth out this path as well by adding some sentences.

**Comment by Witoso** [comment]
Closed with #16579
