### ISSUE TITLE
Multi-level lists plugin doesn't recognize license key

### ISSUE THREAD

**Issue by dt-salvador-diaz** [ckeditor/ckeditor5#16530]
## 📝 Provide detailed reproduction steps (if any)

1. Clone `https://github.com/DiliTrust/ckeditor-license-checker`
2. inside the newly cloned project, run `yarn install` then `yarn dev`
3. open the url displayed by the `yarn dev` command (typically `http://localhost:5173`)
4. put a valid license key in the text input
5. check the `multi-level list` checkbox
6. click on "Apply config"

### ✔️ Expected result

The editor should display in read-write mode, with the multi-level list toolbar button

### ❌ Actual result

The editor displays in read-only mode, and the javascript console shows the following error (the link is dead by the way)
```
CKEditorError: multi-level-list-invalid-license-key
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-multi-level-list-invalid-license-key
```

When using the same valid license key, without enabling the multi-level list plugin, the editor doesn't display the "Powered by ckeditor" logo, which proves that the license is valid (am I wrong in thinking this ?)

## 📃 Other details

* Browser: Tested on chrome 125.0.6422.142 but should be reproducible in any browser
* OS: Mac OS 14.5 (23F79)
* First affected CKEditor version: only tested 41.4.2
* Installed CKEditor plugins: 
```
    "@ckeditor/ckeditor5-basic-styles": "^41.4.2",
    "@ckeditor/ckeditor5-editor-classic": "^41.4.2",
    "@ckeditor/ckeditor5-essentials": "^41.4.2",
    "@ckeditor/ckeditor5-link": "^41.4.2",
    "@ckeditor/ckeditor5-list": "^41.4.2",
    "@ckeditor/ckeditor5-list-multi-level": "^41.4.2",
    "@ckeditor/ckeditor5-paragraph": "^41.4.2",
    "@ckeditor/ckeditor5-theme-lark": "^41.4.2",
    "@ckeditor/ckeditor5-vue": "^5.1.0",
    "@ckeditor/vite-plugin-ckeditor5": "^0.1.3",
```
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dt-salvador-diaz** [comment]
> Hey @dt-salvador-diaz! Could you please reach out directly to our support channel ([support@cksource.com](mailto:support@cksource.com)) and describe the problem? Our dedicated support team will investigate your issue.

Thanks @Mgsy , that's the first thing I did, but the support told me it was part of the productivity pack and that they had to regenerate my license, which they did but it didn't solve my problem. Did you try reproducing the bug ? It only takes a couple of minutes with the example project I shared.

**Comment by Mgsy** [comment]
@dt-salvador-diaz, the multi-level lists plugin is not a part of the Productivity Pack, so the key won't work. I have asked our support team to analyze your case and contact you again to discuss the issue, so please let's move the discussion to the support channel.
