### ISSUE TITLE
More graceful handling of people landing in the legacy method guides

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#16539]
The warning at the top of this guide is hard to spot:

![](https://github.com/ckeditor/ckeditor5/assets/156149/dc603006-738a-423c-835d-aad60425a7e8)

I mean the yellow one in the content of the guide.

The huge problem here is that people Googling for "ckeditor5 vite" will most likely end up here. AFAIK, there's no way to deprioritize those results in Google other than by `robots.txt`.

Moreover: the info box does not actually give the short answer. It sends the reader to the quick start guide where that person won't find a definitive answer for the question "how to  ... with vite".

I think there are ~3~5 things we should do:

*   Add sth like the :warning:  sign (can be just a unicode char) at the beginnig of those specific warnings. This should make them stand out a bit more.
*   Clean up the content below those warnings so there are fewer callouts. The more callouts, the fewer will be read.
*   Improve the messaging in these warnings giving **straight and quick** answers and then sending to reasonable places in the new docs.
*   Add a guide about supported bundlers and have as many covered with short and simple sections explaining that "All's good" and giving quick links to what to read next. This is to target basic SEO.
*   Consider listing (disallowing crawling) the legacy guides in `robots.txt`.

**Comment by Reinmar** [comment]
> *   Consider listing (disallowing crawling) the legacy guides in `robots.txt`.

We'll need to discuss this. I'm not sure about the consequences. These are new pages, but their content was copied 1-to-1 from the current documentation. Those pages that we want to delist are currently the highest performing guides.

**Comment by Witoso** [comment]
> Add a guide about supported bundlers and have as many covered with short and simple sections explaining that "All's good" and giving quick links to what to read next. This is to target basic SEO.

This should be some `Installation` guide that we have in the setup section that goes deep into this and ESM and other topics.

**Comment by godai78** [comment]
We redirected many of the old guides (like Quicks start) so that the old location of the legacy guides leads to the new ones instead and it will take some time before the legacy one list again in google. This will be our advantage.  
  
There's been really few guides that have just been copied (like toolbars), most have been rewritten or written from scratch even if the names were similar.  
  
The infobox would probably fare off much better with a link to migration guide (when we put those infboxes in 6 months go none of that ws ready and the QS was an empty placeholder). That's as close as we get to the "short answer" unless we put individual links in all individual infoboxes, which is also a solution.

**Comment by Witoso** [comment]
Let's start with:

*   Add sth like the :warning:  sign (can be just a unicode char) at the beginnig of those specific warnings. This should make them stand out a bit more.
*   Clean up the content below those warnings so there are fewer callouts. The more callouts, the fewer will be read.
*   Improve the messaging in these warnings giving **straight and quick** answers and then sending to reasonable places in the new docs (link to corresponding guide React > React).

**Comment by Witoso** [comment]
We changed info boxes, added them to a few more places, tweaked titles. The framework section may need a few more infoboxes but it's not a blocker.

**Comment by Reinmar** [comment]
LGTM
