### ISSUE TITLE
Autosave is not defined

### ISSUE THREAD

**Issue by mprythero** [ckeditor/ckeditor5#1653]
## Is this a bug report or feature request? (choose one)
🐞 Bug report

## 💻 Version of CKEditor
ckeditor 5
@ckeditor/ckeditor5-autosave

## 📋 Steps to reproduce

Go to instructions here (https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) 
1. go to project directory's public plugins folder
2. git clone -b stable https://github.com/ckeditor/ckeditor5-build-classic.git
3. cd ckeditor5-build-classic
4. npm install

5. npm install --save-dev @ckeditor/ckeditor5-autosave

6. Edit src/ckeditor.js and add the following:
`import Autosave from '@ckeditor/ckeditor5-autosave/src/autosave'; `
and add `Autosave ` to ClassicEditor.builtinPlugins

7. Run `yarn run build`

8. In my document I've got:
```

<script>
ClassicEditor
    .create( document.querySelector( '#notes' ), {
        plugins: [ Autosave ],
        toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'undo', 'redo' ],
        image: {
            toolbar: [ 'imageStyle:full', 'imageStyle:side', '|', 'imageTextAlternative' ],
        },
        autosave: {
            save( editor ) {
                // The saveData() function must return a promise
                // which should be resolved when the data is successfully saved.
                return saveData( editor.getData() );
            }
        }
    } );

  </script>
```

## ✅ Expected result

Should allow me to use the autosave feature with CKEditor5

## ❎ Actual result

Get "Uncaught ReferenceError: Autosave is not defined"

**Comment by ma2ciek** [comment]
Hi @mprythero.

Since the `Autosave` class is added to the `ClassicEditor.builtinPlugins` you shouldn't have to add it too in the `ClassicEditor.create()` method. It's also forbidden since you'd be merging source code and built code. So all should be working with:

```
ClassicEditor
    .create( document.querySelector( '#notes' ), {
        toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'undo', 'redo' ],
        image: {
            toolbar: [ 'imageStyle:full', 'imageStyle:side', '|', 'imageTextAlternative' ],
        },
        autosave: {
            save( editor ) {
                // The saveData() function must return a promise
                // which should be resolved when the data is successfully saved.
                return saveData( editor.getData() );
            }
        }
    } );
```

**Comment by pomek** [comment]
```diff
<script>
ClassicEditor
    .create( document.querySelector( '#notes' ), {
-        plugins: [ Autosave ],
        toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'undo', 'redo' ],
        image: {
            toolbar: [ 'imageStyle:full', 'imageStyle:side', '|', 'imageTextAlternative' ],
        },
        autosave: {
            save( editor ) {
                // The saveData() function must return a promise
                // which should be resolved when the data is successfully saved.
                return saveData( editor.getData() );
            }
        }
    } );

  </script>
```

The code above should resolve the issue. You tried to use `Autoformat` (from global - window - scope). In fact, `window.Autoformat` here is undefined.
