### ISSUE TITLE
Impossible to compile `ckeditor5-premium-features` using `angular-compiler`

### ISSUE THREAD

**Issue by Mati365** [ckeditor/ckeditor5#16534]
## 📝 Provide detailed reproduction steps (if any)

1. Open stack blitz: https://stackblitz.com/edit/o84wjw?file=package.json or install it from [zip](https://github.com/user-attachments/files/15765489/o84wjw-wchydu.zip). 

### ✔️ Expected result

Compiles without errors.

### ❌ Actual result

Lots of compilation errors from `ckeditor5-premium-features` package. `ckeditor5` compiles fine.

```bash
⠇ Building...
✘ [ERROR] TS2614: Module '"./multilevellist.js"' has no exported member 'MultiLevelListConfig'. Did you mean to use 'import MultiLevelListConfig from "./multilevellist.js"' instead? [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-list-multi-level/src/index.d.ts:8:41:
      8 │ ... MultiLevelList, type MultiLevelListConfig } from './multilevell...
        ╵                          ~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:19:8:
      19 │         [RevisionViewer.pluginName]: RevisionViewer;
         ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2339: Property 'pluginName' does not exist on type 'typeof import("/home/projects/o84wjw/node_modules/@ckeditor/ckeditor5-revision-history/src/revisionviewer")'. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:19:24:
      19 │         [RevisionViewer.pluginName]: RevisionViewer;
         ╵                         ~~~~~~~~~~


✘ [ERROR] TS2709: Cannot use namespace 'RevisionViewer' as a type. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:19:37:
      19 │         [RevisionViewer.pluginName]: RevisionViewer;
         ╵                                      ~~~~~~~~~~~~~~


✘ [ERROR] TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:20:8:
      20 │         [RevisionViewer.pluginName]: RevisionViewer;
         ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2339: Property 'pluginName' does not exist on type 'typeof import("/home/projects/o84wjw/node_modules/@ckeditor/ckeditor5-revision-history/src/revisionviewer")'. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:20:24:
      20 │         [RevisionViewer.pluginName]: RevisionViewer;
         ╵                         ~~~~~~~~~~


✘ [ERROR] TS2709: Cannot use namespace 'RevisionViewer' as a type. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/augmentation.d.ts:20:37:
      20 │         [RevisionViewer.pluginName]: RevisionViewer;
         ╵                                      ~~~~~~~~~~~~~~


✘ [ERROR] TS2305: Module '"./revisionviewer.js"' has no exported member 'RestoreRevisionCommand'. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/index.d.ts:10:41:
      10 │ ...RevisionViewer, type RestoreRevisionCommand, type ShowChangeCom...
         ╵                         ~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2305: Module '"./revisionviewer.js"' has no exported member 'ShowChangeCommand'. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-revision-history/src/index.d.ts:10:70:
      10 │ ...eRevisionCommand, type ShowChangeCommand } from './revisionview...
```

![obraz](https://github.com/ckeditor/ckeditor5/assets/3949262/c2b1ce48-6226-49bb-8648-d0348d595d3b)

## 📃 Other details

* Browser: Firefox 126
* `"@angular/compiler": "17.2.4"`
* ` "typescript": "~4.9.3"`

**Comment by Witoso** [comment]
> \[RevisionViewer.pluginName\]: RevisionViewer;

This error is caused by using TS in `4.9`, bumping to 5.0 removes those errors. We need to make it standing out in the docs that we require 5.0, cc @gorzelinski.

> ✘ \[ERROR\] TS2614: Module '"./multilevellist.js"' has no exported member 'MultiLevelListConfig'. Did you mean to use 'import MultiLevelListConfig from "./multilevellist.js"' instead? \[plugin angular-compiler\]

We do export them, but I noticed they have `@internal` flag on them as well. @filipsobol by any chance we use `skipInternal` flag?

**Comment by Witoso** [comment]
Some bundlers ship the default `tsconfig` with `"skipLibCheck": true`. That's why those errors are silenced in some cases.

**Comment by Witoso** [comment]
1. Revision history: @scofalik 
2. Multi level: experimental API, or tag properties as internal, or just remove this config. @mmotyczynska 
3. TypeScript 5.0: docs update, @Witoso 
4. Augmentation: does it make sense right now? Do we need to document it?? Create a follow up.

**Comment by Reinmar** [comment]
> Some bundlers ship the default `tsconfig` with `"skipLibCheck": true`. That's why those errors are silenced in some cases.

Isn't this something that we should also change in the E2E tests that we have? cc @dufipl @Mgsy

**Comment by filipsobol** [comment]
> > Some bundlers ship the default `tsconfig` with `"skipLibCheck": true`. That's why those errors are silenced in some cases.
> 
> Isn't this something that we should also change in the E2E tests that we have? cc @dufipl @Mgsy

I think we should. The `skipLibCheck: true` option is good for performance, but may suppress errors in declaration files of external dependencies.

Suppressing errors in E2E **tests** is counterproductive :)

**Comment by Witoso** [comment]
TS errors not reproducible in the latest `alpha` :+1: (make sure to delete package-lock / node\_modules) in your fork to test a fresh setup.
