### ISSUE TITLE
Docs isssue: Lack of comma and incorrect Editor type in DLL example of an integration

### ISSUE THREAD

**Issue by marcelmroz** [ckeditor/ckeditor5#16536]
## 📝 Provide a description of requested docs changes

In [CKEditor 5 DLL builds for CKEditor 5 Collaboration Features](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds-collaboration-features.html)

1. Missing comma [in plugins config, after `CKEditor5.table.TableToolbar`](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds-collaboration-features.html#:~:text=CKEditor5.table.TableToolbar)
![Screenshot 2024-06-10 at 09 59 16](https://github.com/ckeditor/ckeditor5/assets/103954333/74bc971a-2fa8-46b1-a039-c03f3a7a8a70)

2. Instead of `Editor` it should be `CKEditor5.editorClassic.ClassicEditor` in [watchdog setup](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds-collaboration-features.html#:~:text=const%20watchdog%20%3D%20new%20CKEditor5.watchdog.EditorWatchdog(%20Editor%20)%3B) 
![Screenshot 2024-06-10 at 09 58 54](https://github.com/ckeditor/ckeditor5/assets/103954333/cfc49937-2c96-444f-9c8a-ec4ef8c431ee)

**Comment by Witoso** [comment]
Resolved with [#16595](https://github.com/ckeditor/ckeditor5/pull/16595)
