### ISSUE TITLE
Warnings regarding table's CSS

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1654]
There are two warnings when running manual tests:

```
[ThemeImporter] Failed to find "/workspace/ckeditor5/packages/ckeditor5-theme-lark/theme/ckeditor5-table/table.css".

[ThemeImporter] Failed to find "/workspace/ckeditor5/packages/ckeditor5-theme-lark/theme/ckeditor5-table/inserttable.css".
```

**Comment by Reinmar** [comment]
Hm... actually, there are more warnings when running `--files=core` (previously I was testing `--files=mention`):

![image](https://user-images.githubusercontent.com/156149/55085622-4215db80-50a7-11e9-938a-043828171946.png)

What could have changed? Or were there always there? If they were... they are confusing and we should get rid of them.

cc @oleq

**Comment by oleq** [comment]
They were always there. They happen if a feature CSS file `ckeditor5-foo/theme/bar.css` has no counterpart in `ckeditor5-theme-lark/theme/ckeditor5-foo/bar.css`. 

At first, it helped to figure out obvious bugs (_I wrote my theme styles but they don't work..._ (a.k.a. _I made a typo..._)) but now I suppose with more and more packages, I agree this might actually be annoying.

I'm OK with removing them completely.

**Comment by jodator** [comment]
I was inspecting the dev environment and I can see two ways of dealing with this:

1. Remove `debug: true` from theme importer options for manual tests
2. Add `verbose` option there to include missing files warnings
3. Remove missing files warnings.

I'd go with 1:

![Selection_278](https://user-images.githubusercontent.com/247363/55388813-39545800-5534-11e9-8bf0-346ad0ed45b5.png)

I don't know why we need all the `Loading for "foo/bar.css"` logs are there anyway and I never read them.

Option 2: If you wish we might leave the `debug: true` there (so some noise will still be there) but no warning will be outputted.

Option 3: Similar to option 2 but no-one will ever know if some missing counterpart file type of warning.

**Comment by oleq** [comment]
> I don't know why we need all the `Loading for "foo/bar.css"` logs are there anyway and I never read them.

That's a good point I guess. Only errors should land here.
