### ISSUE TITLE
Broken Link: "Context and Collaboration Features" Page Results in 404 Error

### ISSUE THREAD

**Issue by w-beom** [ckeditor/ckeditor5#16555]
I encountered an issue with a link on your documentation site. When trying to access the "Context and Collaboration Features" page via the following URL:

https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/context-and-collaboration-features.html

I am met with a 404 error page. This issue prevents access to important documentation that I need for implementing collaboration features in CKEditor 5. Could you please investigate and resolve this broken link?

**Comment by Witoso** [comment]
Thanks for the report, there was some issue in the CDN infra. Should work right now.
