### ISSUE TITLE
Can I enable colorPicker in old CKEditor5?

### ISSUE THREAD

**Issue by kinju4374** [ckeditor/ckeditor5#16564]
How can I enable colorPicker in fontColor and fontBackgroundColor?

I have tried below and it doesn't work for me.

`
```
// added support for extra fontFamily
	options.editorOptions.fontFamily = {
		 supportAllValues: true
	};
```
	
	// added numeric support for fontsize
	options.editorOptions.fontSize = {
		options: [
                9,
                11,
                13,
                'default',
                17,
                19,
                21
            ],
		supportAllValues: true
	};

    // enable color picker
    options.editorOptions.fontColor = {
        colorPicker :true
    };
	
	// table features
	options.editorOptions.table = {
        contentToolbar: [
            'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties'
        ]`

except fontColor settings, other options for table, fontSize, fontFamily works fine.

Currently it displays as follows.

![image](https://github.com/ckeditor/ckeditor5/assets/17248153/60d33dd3-4915-4a95-a30e-14707b163188)

Could someone please suggest, whether it is possible to do it using js or need to upgrade it to latest version?

**Comment by Reinmar** [comment]
From what I can see, color picker is available since v38.0.0 so that's the earlier version you could turn it on.

It's not possible before. As a workaround, people came up with very rich color pallettes: https://github.com/ckeditor/ckeditor5/issues/1812#issuecomment-552471067
