### ISSUE TITLE
Questions about hiding the toolbar, toolbar icons size and about having two separate buttons for the Highlight feature

### ISSUE THREAD

**Issue by zackhalil** [ckeditor/ckeditor5#1656]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

version 12.0.0

1. In the InlineEditor is it possible to turn on the highlight feature 
2. In the DecoupleEditor is it possible to make the toolbar autohide and show like it does in the InlineEditor 
3. can the icons in tool bar be made smaller?
4. Is it possible to separate the highlight maker and pen as two separate toolbar options...

**Comment by Mgsy** [comment]
1. You can enable every feature in all kinds of editors. Here is the guide [how to install plugins.](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)
2. I'm not sure what do you mean by 'autohide'. Could you write more about it?
3. You can change the size of icons by modifying [default styles](https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/ckeditor5-ui/components/icon/icon.css#L7).
4. Yes, it's possible, check out the [highlight feature documentation](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html#inline-buttons).

**Comment by zackhalil** [comment]
for 2 I figure a way.... what i want is the toolbar to hide when not being used and only show when i click on the field plus I didn't want the field to shift down as well when the field toolbar is shown

          <div id="Description-document-editor" class="document-editor">   <div id="Description-content-container" class="content-container"> <div id="Description-toolbar" class="toolbar-container"></div> <div id="Description-html"> </div> </div> </div> 

           var toolbar = document.querySelector("Description-toolbar");
           var documentHTML = document.querySelector("Description-html");
           var documentEditor = document.querySelector("Description-document-editor");

            toolbar.style.display = "none";
            editor.ui.focusTracker.on( "change:isFocused", ( evt, name, isFocus ) => {
               if (element.includes("Table.")) {
                  documentHTML.style.minHeight="150px";
               }

               documentEditor.style.position="relative";
               if (isFocus && !editor.isReadOnly) {
                  toolbar.style.display = "";
                  documentEditor.style.top="-38px";
                  documentEditor.style.marginBottom="-38px";
               } else {
                  toolbar.style.display = "none";
                  documentEditor.style.top="0px";
                  documentEditor.style.marginBottom="0px";
               }
            });

**Comment by zackhalil** [comment]
for 4... I saw that but I wanted two different drop downs one for makers and one for pens.... also the icons for marker and pen look almost the same... can i change them?

Thanks for your answers

**Comment by Mgsy** [comment]
>for 4... I saw that but I wanted two different drop downs one for makers and one for pens.... also the icons for marker and pen look almost the same... can i change them?

@jodator, is there a quick way to achieve it?

**Comment by jodator** [comment]
This would require creating new ui component based on [original highlight dropdown](https://github.com/ckeditor/ckeditor5-highlight/blob/master/src/highlightui.js#L167-L242).

The code should be relatively the same but would required:
1. filter out options for only `pens` or `markers`
2. the logic for changing the split button icon should take into account that you can have only pen or marker in this dropdown - right now it changes to last used highlighter.

I've tried to create a sub component by:

```js
class SeparateHighlightDropdowns extends Plugin {
	init() {
		const editor = this.editor;
		const componentFactory = editor.ui.componentFactory;

		componentFactory.add( 'highlightPen', locale => {
			const origDp = componentFactory.create( 'highlight' );

			const toRemove = [];
			for ( const item of origDp.toolbarView.items ) {
				if ( item.label && item.label.includes( 'marker' ) ) {
					toRemove.push( item );
				}
			}

			for ( const item of toRemove ) {
				origDp.toolbarView.items.remove( item );
			}

			return origDp;
		} );

		componentFactory.add( 'highlightMarker', () => {
			const origDp = componentFactory.create( 'highlight' );

			const toRemove = [];
			for ( const item of origDp.toolbarView.items ) {
				if ( item.label && item.label.includes( 'pen' ) ) {
					toRemove.push( item );
				}
			}

			for ( const item of toRemove ) {
				origDp.toolbarView.items.remove( item );
			}

			return origDp;
		} );
	}
}
```
but it is not good enough:
![Peek 2019-03-29 10-10](https://user-images.githubusercontent.com/247363/55221935-f11ef800-520a-11e9-86c0-370a4680983d.gif)

**Comment by zackhalil** [comment]
What about changing the SVG icons of the marker and pen?

**Comment by Mgsy** [comment]
>What about changing the SVG icons of the marker and pen?

Just change it in the [highlight feature code.](https://github.com/ckeditor/ckeditor5-highlight/blob/master/src/highlightui.js#L14)

**Comment by zackhalil** [comment]
@Mgsy Hi im new to ckeditor 5... Im using the ckeditor5 decoupled document build? Can you point me in general direction on how do I customize that build? I only can seem to see how to modify the classic build?

**Comment by Mgsy** [comment]
>Can you point me in general direction on how do I customize that build? I only can seem to see how to modify the classic build?

You can create your own customized build based on an existing build. Here you can find [creating custom builds guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html). The example concerns the classic build, but the procedure is the same for every type of builds. 

If you want to create your own theme for CKEditor 5, take a look at our [theme customization guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html).
