### ISSUE TITLE
Implement attribute properties

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1659]
## Is this a bug report or feature request?

🆕 Feature request

## 💻 Version of CKEditor

CKEditor v5 @ 12.0.0

## 📋 Steps to reproduce

Based on discussion in https://github.com/ckeditor/ckeditor5/issues/908#issuecomment-462264116 emerged the idea to provide an API that will allow to mark attributes with metadata.

First we need to use it to describe whether or not attribute should be considered as visual formatting or not.

The default implementation will not restrict property names, so it could be used by plugin developers for better extensibility.

**Comment by oleq** [comment]
Just a reminder for myself: we should make this sort of metadata [inspectable](https://github.com/ckeditor/ckeditor5-inspector).
