### ISSUE TITLE
Serious performance drop after exporting engine utils in every test

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#166]
See #144.

It makes sad unfortunately. We require the whole engine to be loaded in every single test... Since these means more than 200 additional files, tests execution slowed down terribly (+0.5s to every non-engine tests!).

We've got two ways out:

1. Revert the change.
2. Implement bundler for tests.

We wanted to avoid the latter, because having modules in their raw format, while being much slower, is easier to work with. Implementing a bundler for tests will take a lot of time, because it must feature a smart module pool to be able to rebuild only these bundles (there will be a bundle for each test) which are affected by change in one of the source files. 

Hence, for now, I'd propose reverting the change that we've made. However, while I [haven't seen this before](https://gist.github.com/Reinmar/4e742e8005e0fb0a0bce868192a6d995) we may need to implement bundling for tests anyway, if HTTP2 won't help enough (I'd check if first).

**Comment by pjasiun** [comment]
I was unsure about this change at the first place. What it does is replacing:
```
import { stringify, parse, getData, setData } from '/tests/engine/_utils/model.js';
```
With:
```
const stringify = bender.model.stringify;
const parse = bender.model.parse;
const getData = bender.model.getData;
const setData = bender.model.setData;
```
Plus some additional issues.

It does not look like a progress for me.

**Comment by pjasiun** [comment]
Also. If you add `import { stringify, parse, getData, setData } from '/tests/engine/_utils/model.js';` very often, or you want to public these methods in the global namespace for debugging, you can create a snipped in your IDE for it.

**Comment by Reinmar** [comment]
Well, if all of you are ok, then let's unpublish these tools. You can also tell me how to create a snippet for Sublime :D.

**Comment by Reinmar** [comment]
BTW. I'm also reverting how these tools are used in tests, because they should never be used by `bender`. That was meant to be debugging util, not testing util.

**Comment by Reinmar** [comment]
I committed:

* https://github.com/ckeditor/ckeditor5-delete/commit/2dd07e2f1b812575488eef92c48d2c978a811d02
* https://github.com/ckeditor/ckeditor5-enter/commit/4b0af7b00b3b034e5d904111ab68c34f77227bcf
* https://github.com/ckeditor/ckeditor5-engine/commit/81813f9a198e50c492b6623470d4443dddfb56bb

**Comment by Reinmar** [comment]
More: https://github.com/ckeditor/ckeditor5/commit/78d789ea98b87c5db91bc2242c2a1d1dc02521e5

**Comment by Reinmar** [comment]
Seems that I've reverted all related changes. I'll report a new ticket for the performance issue... because I still see some regressions. Most likely, they are simply caused by the fact that the engine grew to a size where every test is heavy.

**Comment by Reinmar** [comment]
See #169 for perf issues.
