### ISSUE TITLE
Invalid Link to CKEditor 5 Installation Guide in README.md

### ISSUE THREAD

**Issue by fn-jakubkarp** [ckeditor/ckeditor5#16607]
## 📝 Provide a description of requested docs changes
| Scenario      | Expected result | Actual result |
|--------|--------|--------|
| Click on 'Installing CKEditor 5` in README.md hyperlink | Open CKEditor 5 docs website | Returns Error: 404 Page not found |

**Cause**: Incorrect hyperlink 
<details><summary>Actual result</summary>

![image](https://github.com/ckeditor/ckeditor5/assets/80711470/e88d6254-91ae-4b45-8e53-91fa819e5dc5)

</details> 

<details><summary>Expected result</summary>

![image](https://github.com/ckeditor/ckeditor5/assets/80711470/e7dff2cd-a918-4402-8590-96d5f8bf2c08)

</details> 

---

_What is the purpose and what should be changed?_

Issue source: [README.md](https://github.com/ckeditor/ckeditor5/blob/master/README.md)

**Solution**

```diff
+ [Installing CKEditor&nbsp;5](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start.html)

- [Installing CKEditor&nbsp;5](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/quick-start.html)

```

**Comment by Witoso** [comment]
Thanks for the report, we are preparing for a large release this week, and some links to resources were updated beforehand to land on `npm`. Stay tuned!

**Comment by Witoso** [comment]
Issue resolved, links work.
