### ISSUE TITLE
Accessibility: replace italic <i> tag with the accessible <em> tag

### ISSUE THREAD

**Issue by kellyannmcnamara01** [ckeditor/ckeditor5#16654]
## 📝 Provide a description of the improvement
Currently when using CKeditor, after selected some text to be italic the text gets wrapped and displayed in an `<i>` tag. This is not in alignment with accessibility practices. `<i>` tags are not read or recognized by screen readers and prevent non-sighted users from knowing the emphasis of the italicized text. 

_How the feature works now and what you'd like to change_?
Currently italic text is wrapped in an `<i>` tag; ideally it is wrapped in an `<em>` tag

## 📃 Other details
* CKEditor version: 3.8.3

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Dup: https://github.com/ckeditor/ckeditor5/issues/10393
