### ISSUE TITLE
Add option to select if a link opens in a new tab

### ISSUE THREAD

**Issue by kellyannmcnamara01** [ckeditor/ckeditor5#16653]
## 📝 Provide a description of the new feature
When editing or adding links in CKeditor can there be a checkbox to allow the link to open in a new tab or not? 

_What is the expected behavior of the proposed feature?_
Allowing a user to choose if the link opens in a new tab or not

---

### Screenshots
<img width="556" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/24300129/e2669b25-10b1-407d-9d70-0972c41e5e15">
<img width="484" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/24300129/b2a1637c-4672-4115-9e83-1365b3b4c566">

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Yes, it's possible, check [the documentation about the decorators](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links).
