### ISSUE TITLE
All CHANGELOG.md should lead to ckeditor5/CHANGELOG.md

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#16667]
Currently, the changelogs of all packages except `ckeditor5` are a bit confusing.

The look like we'd recently release v19.0.0. 

![](https://github.com/ckeditor/ckeditor5/assets/156149/b873d1c9-61f9-4eaf-bfd2-61b68075ff3c)

Let's have all changelogs (in this repo and the commercial one, except of course the main one) equal to:

```markdown
Changelog
=========

All changes in the package are documented in https://github.com/ckeditor/ckeditor5/blob/master/CHANGELOG.md.
```

No other content is necessary there anymore.

**Comment by Reinmar** [comment]
I can see we already used this in new packages:

```
Changelog
=========

All changes in the package are documented at https://github.com/ckeditor/ckeditor5/blob/master/CHANGELOG.md.
```

The longer wording of this note is fine.

But is "at" actually correct in it? Shouldn't it be "in"?

**Comment by Reinmar** [comment]
> But is "at" actually correct in it? Shouldn't it be "in"?

@godai78 confirmed that "in" is the correct form.

**Comment by pomek** [comment]
DoD:

* Update all `CHANGELOG.md` files in **both** repositories according to the template (see the first post).
