### ISSUE TITLE
Simple docx document not importing images 

### ISSUE THREAD

**Issue by maggie-chintaro** [ckeditor/ckeditor5#16668]
The docx document attached is a basic template from word. When import from word on your site the image does not import with it (https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html). I can copy and paste in later but it will not import. For my own documents I cannot even copy and paste. 

I need to decide on whether we are using this product asap. Appreciate any assistance

**Comment by FilipTokarski** [comment]
Hello @maggie-chintaro, please note that this issue tracker is dedicated to the open source part of CKEditor 5. If you are interested in any of our premium features or experience any problems, please [contact the support](https://ckeditor.com/contact/) and provide all necessary information.
