### ISSUE TITLE
not found ckeditor5/ckeditor5.css

### ISSUE THREAD

**Issue by Pilu12** [ckeditor/ckeditor5#16671]
### Reproduction steps

1. …
2. …
3. …

### Definition of Done

- _Please leave this field for us. We will fill it during the backlog refinement session._

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by Witoso** [comment]
Please share more information about the setup that you try to achieve and in what environment.

**Comment by filipsobol** [comment]
This is likely the same issue as https://github.com/ckeditor/ckeditor5/issues/16638.

**Comment by filipsobol** [comment]
This problem has been fixed in `42.0.2`.
