### ISSUE TITLE
Docs issue report from "getting-started/setup/optimizing-build-size.html"

### ISSUE THREAD

**Issue by hendeltom** [ckeditor/ckeditor5#16684]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/optimizing-build-size.html

### Project version

42.0.0

### Is the information outdated? How?

The mentioned import paths do not work with Typescript. See below.

### Is there something missing in the guide? What is it?

The example code
```js
- import { ClassicEditor, Bold, Italic and Table } from 'ckeditor5';

+ import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic/dist/index.js';
+ import { Bold, Italic } from '@ckeditor/ckeditor5-basic-styles/dist/index.js';
+ import { Table } from '@ckeditor/ckeditor5-table/dist/index.js';
```
does not work for Typescript builds because the `./dist` folders of all plugins do not contains the file `index.d.ts` as the `./src` folders do. So for the moment, then only import paths that would work are
```ts
import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic/src/index';
import { Bold, Italic } from '@ckeditor/ckeditor5-basic-styles/src/index';
import { Table } from '@ckeditor/ckeditor5-table/src/index';
```

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by Reinmar** [comment]
The types are there:

![](https://github.com/ckeditor/ckeditor5/assets/156149/d7725514-6c78-42bf-906e-854cee70cad7)

But TS indeed cannot find them:

![](https://github.com/ckeditor/ckeditor5/assets/156149/9823b940-19d2-48f3-a391-b813882504d3)

```
➜  my-app yarn build
yarn run v1.22.21
$ tsc && vite build
src/main.ts:3:31 - error TS7016: Could not find a declaration file for module '@ckeditor/ckeditor5-editor-classic/dist/index.js'. '/Users/p/Workspace/my-app/node_modules/@ckeditor/ckeditor5-editor-classic/dist/index.js' implicitly has an 'any' type.
  If the '@ckeditor/ckeditor5-editor-classic' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@ckeditor/ckeditor5-editor-classic/dist/index.js';`

3 import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic/dist/index.js';
```

**Comment by Reinmar** [comment]
cc @filipsobol

**Comment by filipsobol** [comment]
The problem is that these types are in a different folder than the code (`dist/*` vs `dist/types/*`). This could be fixed either by moving the types to the same folder as the code or by using the `exports` field in the `package.json`.

I'll look into both options to see which would be better, taking into account backwards compatibility with the old installation methods.

**Comment by Witoso** [comment]
To keep it KISS I would vote for option 1. Do we know how many files on average would appear?
