### ISSUE TITLE
TS2307: Cannot find module 'ckeditor5'.

### ISSUE THREAD

**Issue by contactabhi98** [ckeditor/ckeditor5#16686]
## 📝 Provide detailed reproduction steps (if any)

1. I'm using angular 8.2 and I don't why ckeditor5 is not working, while importing the common libraries like underline, SourceEditing, Strikethrough,

### ✔️ Expected result

It should work as expected

### ❌ Actual result

TS2307: Cannot find module 'ckeditor5'.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Could you describe steps to reproduce the issue?

PS. Maybe you didn't install the `ckeditor5` package? Are you sure you've run `npm install ckeditor5`?

**Comment by contactabhi98** [comment]
Hi Reinmar,

Thanks for reaching out me.
Please find the requested details below:
- I have installed the packages:
a . "@ckeditor/ckeditor5-angular": "^1.2.3",
b.  "ckeditor5": "^10.0.0",
as per compatibility with angular 8.2 but while using underline, strike though, text colour etc... by importing from ckedito5


import {
	ClassicEditor,
	AccessibilityHelp,
	Autosave,
	Bold,
	Essentials,
	FontBackgroundColor,
	FontColor,
	Heading,
	Indent,
	IndentBlock,
	Italic,
	List,
	ListProperties,
	Paragraph,
	SelectAll,
	SourceEditing,
	Strikethrough,
	Underline,
	Undo,
	type EditorConfig
} from 'ckeditor5';


import 'ckeditor5/ckeditor5.css'; 


Getting an error:
Cannot find module 'ckeditor5' or its corresponding type declarations.ts(2307).

![Screenshot from 2024-07-09 12-38-18](https://github.com/ckeditor/ckeditor5/assets/75126257/dbfc6e4e-cbfc-4de2-9613-3769d23d4d65)
![Screenshot from 2024-07-09 12-38-46](https://github.com/ckeditor/ckeditor5/assets/75126257/3e2145ce-00d1-4da1-beb5-f40978b90842)
![Screenshot from 2024-07-09 12-39-23](https://github.com/ckeditor/ckeditor5/assets/75126257/c1ce74f8-a9d7-41f8-8059-0d02104d5b1c)

please let me know, if you need more details from my end, also we can connect if possible

**Comment by Reinmar** [comment]
> *   b. "ckeditor5": "^10.0.0",

ouch :O

This is a 6 year old version of CKEditor 5 and a 4 year old version of Angular integration

None of our documentation actually documents how to use those. You must bump your dependencies first.

**Comment by contactabhi98** [comment]
So, we need to update the angular version first before using CkEditor5, right @Reinmar .
