### ISSUE TITLE
@ckeditor/ckeditor5-html-embed/dist/index.js 124:30 File was processed with these loaders

### ISSUE THREAD

**Issue by storageChu** [ckeditor/ckeditor5#16687]
## 📝 Provide detailed reproduction steps (if any)

1. install  ckeditor5 ckeditor5-premium-features  
2. install @ckeditor/ckeditor5-react
3. 
```
import { CKEditor } from '@ckeditor/ckeditor5-react';
import { ClassicEditor, Bold, Essentials, Italic, Mention, Paragraph, Undo } from 'ckeditor5';
import { SlashCommand } from 'ckeditor5-premium-features';

                    <CKEditor
                        editor={ClassicEditor}
                        config={{
                            toolbar: {
                                items: ['undo', 'redo', '|', 'bold', 'italic'],
                            },
                            plugins: [
                                Bold, Essentials, Italic, Mention, Paragraph, SlashCommand, Undo
                            ],
                            licenseKey: '<YOUR_LICENSE_KEY>',
                            mention: {
                                // Mention configuration
                            },
                            initialData: '<p>Hello from CKEditor 5 in React!</p>',
                        }}
                    />
```
### ✔️ Expected result

No errors.

### ❌ Actual result

```
Failed to compile.

./node_modules/@ckeditor/ckeditor5-html-embed/dist/index.js 124:30
Module parse failed: Unexpected token (124:30)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   * each widget so they can be destroyed if they are no longer in DOM after the editing view was re-rendered.
|   */
>   _widgetButtonViewReferences = new Set();
|   /**
|   * @inheritDoc
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* "react": "^16.13.1",
* "ckeditor5": "^42.0.0",
* "ckeditor5-premium-features": "^42.0.0",
* "@ckeditor/ckeditor5-react": "^8.0.0",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
From what I can see babel fails on a public class field. This is a JavaScript notation supported by all browsers for years now. Which would indicate that you're running a super old version of babel in your project. Could you check that? 

Unless, @filipsobol you have a different idea?

**Comment by phamquanganh31101998** [comment]
I've encountered this problem, too. 
I'm using babel-loader 8. Is this version too old?

**Comment by filipsobol** [comment]
Not necessarily, but being on the latest version always helps :)

If your environment allows for that, you can either try to update configuration of the `@babel/preset-env` plugin ([docs](https://babeljs.io/docs/babel-preset-env)) to support ES2022 or install the `@babel/plugin-transform-class-properties` plugin ([docs](https://babeljs.io/docs/babel-plugin-transform-class-properties)).

If this doesn't help, then please create a minimal reproducible example that we can use to reproduce this issue.

**Comment by phamquanganh31101998** [comment]
@filipsobol Many thanks! The first solution (update @babel/preset-env) didn't seem to work. But the second solution worked for me. 
However, I had to specify explicitly every packages containing class properties (@ckeditor/ckeditor5-html-embed, @ckeditor/ckeditor5-upload, like so ...).

**Comment by filipsobol** [comment]
@phamquanganh31101998 Could you please share a code snippet with the solution? It might help others to fix this problem.

**Comment by phamquanganh31101998** [comment]
Here's the example. Hope someone might find it useful.
In `webpack.config.js`

`module: {
    rules: [
      // specify all packages using class properties
      {
        test: /\.(js|jsx)?$/,
        include: [
          path.resolve(__dirname, '../node_modules/@ckeditor/ckeditor5-html-embed'),
          path.resolve(__dirname, '../node_modules/@ckeditor/ckeditor5-upload'),
          // ... 
        ],
        use: [
          {
            loader: 'babel-loader',
            options: {
              plugins: [
                '@babel/plugin-transform-class-properties',
                '@babel/plugin-transform-logical-assignment-operators',
              ],
            },
          },
        ],
      },`
