### ISSUE TITLE
addListToDropdown not showing label

### ISSUE THREAD

**Issue by shibon-lal** [ckeditor/ckeditor5#16712]
I am trying to add plugin using JavaScript like the bellow code 

 <script type="importmap">
			{
				"imports": {
					"ckeditor5": "https://cdn.ckeditor.com/ckeditor5/42.0.0/ckeditor5.js",
					"ckeditor5/": "https://cdn.ckeditor.com/ckeditor5/42.0.0/"
				}
			}
		</script>
		<script type="module">
			import {
				ClassicEditor,
				Essentials,
				Paragraph,
				Bold,
				Italic,
				Font,
                createDropdown,
                SplitButtonView,
                Collection,
                Model,
                addListToDropdown,
			} from 'ckeditor5';
			ClassicEditor
				.create( document.querySelector( '#description_1' ), {
					plugins: [ InsertDropDown, Essentials, Paragraph, Bold, Italic, Font ],
					toolbar: [
						'undo', 'redo', '|', 'bold', 'italic', '|',
						'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor',
                        'InsertDropDown'
					]
				} )
				.then( editor => {
					window.editor = editor;
				} )
				.catch( error => {
					console.error( error );
				} );

        function InsertDropDown(editor) {
        editor.ui.componentFactory.add("InsertDropDown", locale => {
        const dropdownView = createDropdown(locale, SplitButtonView);
            dropdownView.buttonView.actionView.set({
                label: 'Translate',
                withText: true,
            });

            const items = new Collection();
            items.add( {
                type: 'button',
                model: new Model( {
                    withText: true,
                    label: 'First item'
                } )
            } );

            items.add( {
                type: 'button',
                model: new Model( {
                    withText: true,
                    label: 'Second item'
                } )
            } );

            addListToDropdown(dropdownView, items);
        return dropdownView;
        });
 };
</script>

Expected to show dropdown value
Currently not showing value

![image](https://github.com/ckeditor/ckeditor5/assets/40288623/d2ea9c7e-0a35-49e7-a9b3-c08339b09371)

**Comment by blackcoder87** [comment]
I can confirm this issue with CKEditor 42.0.0 or newer (npm, webpack).

With CKEditor 41.4.2 the affected plugin worked fine when using "new ButtonView" instead of "new Model".

**Comment by Witoso** [comment]
This related to the [update to v41.0.0](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-41.html#exports-renamed), most likely in previous versions you didn't import from index but from the `src` path. `Model` was renamed to `ViewModel` in the export due to name collision. We will update the docs.

**Comment by blackcoder87** [comment]
Thank you. Works fine with "ViewModel".

**Comment by shibon-lal** [comment]
It is working Fine with **ViewModel**
