### ISSUE TITLE
setData with RestrictedEditingException produces incorrect blanks

### ISSUE THREAD

**Issue by Geri1590** [ckeditor/ckeditor5#16721]
## 📝 Provide detailed reproduction steps (if any)

The issue is detailed in #9646.
When calling editor.setData() on an editor with RestrictedEditingException plugin, produces incorrect text (blank blocks).

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html
2. Switch to restricted mode
3. Do editor.setData(editor.getData()) few times

### ✔️ Expected result

New data visualized correctly.

### ❌ Actual result

New data is visualized with extra `<span class="restricted-editing-exception"></span>`.

### ❓ Possible solution

Described in #9646.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by bramdebouvere** [comment]
Is there any workaround for this?

**Comment by Witoso** [comment]
Resolved #17367.
