### ISSUE TITLE
Can't add multiple attributes to rel (nofollow, referrer) in ckeditor5 with custom plugin

### ISSUE THREAD

**Issue by AroundtheGlobe** [ckeditor/ckeditor5#1673]
## Is this a bug report or feature request? (choose one)

🐞 Bug report (Possible)

## 📋 Steps to reproduce
```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import LinkAttributeCommand from './linkAttributeCommand';

const REL_NOFOLLOW = 'linkRelNoFollow';

export default class RelNoFollow extends Plugin {
    static get pluginName() {
        return 'LinkRelNoFollow';
    }
    init() {
        const editor = this.editor;
        editor.model.schema.extend('$text', {allowAttributes: REL_NOFOLLOW});
        editor.conversion.attributeToElement({
            model: REL_NOFOLLOW,
            view: {
                name: 'a',
                attributes: {
                    rel: ['nofollow', 'noreferrer']
                },
                // the priority has got to be the same as here so the elements would get merged:
                // https://github.com/ckeditor/ckeditor5-link/blob/20e96361014fd13bfb93620f5eb5f528e6b1fe6d/src/utils.js#L33
                priority: 5
            }
        });
        editor.commands.add(REL_NOFOLLOW, new LinkAttributeCommand(this.editor, REL_NOFOLLOW));
    }
}
```

1. I created a custom plugin to allow rel="nofollow" and rel="noferrer" When I have a link with the individual rel value it works so: `<a href="#" rel="noreferrer">Anchor</a>` works and `<a href="#" rel="nofollow">Anchor</a>` does too. 

But `<a href="#" rel="nofollow noreferrer">Anchor</a>` is being stripped from the editor resulting in: `<a href="#" >Anchor</a>`. 

Not sure it's a bug or something I need to change in my plugin to make it work.

**Comment by oleq** [comment]
This should do the trick:

```js
function LinkRel( editor ) {
	editor.model.schema.extend( '$text', { allowAttributes: 'linkRel' } );

	editor.conversion.for( 'downcast' ).attributeToElement( {
		model: 'linkRel',
		view: ( attributeValue, writer ) => {
			const linkElement = writer.createAttributeElement( 'a', { rel: attributeValue }, { priority: 5 } );
			writer.setCustomProperty( 'link', true, linkElement );

			return linkElement;
		},
		converterPriority: 'low'
	} );

	editor.conversion.for( 'upcast' ).attributeToAttribute( {
		view: {
			name: 'a',
			key: 'rel'
		},
		model: 'linkRel',
		converterPriority: 'low'
	} );
}

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ Link, LinkRel, ... ],
		// ...
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by AroundtheGlobe** [comment]
Thank you @oleq that was very helpful and sorry for my late reply. For others who want to create a plugin and build it into the editor itself see the code below. I do wonder how to add the checkbox options into the View to be able to select the "nofollow" and "noreferrer". Would you be able to help with that as well ?

`import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import LinkAttributeCommand from './linkAttributeCommand';

const LINKREL = 'linkRel';

export default class LinkRel extends Plugin {
    static get pluginName() {
        return LINKREL;
    }
    init() {
        const editor = this.editor;
        editor.model.schema.extend('$text', {allowAttributes: LINKREL});
        editor.conversion.for( 'downcast' ).attributeToElement( {
            model: LINKREL,
            view: ( attributeValue, writer ) => {
                const linkElement = writer.createAttributeElement( 'a', { rel: attributeValue }, { priority: 5 } );
                writer.setCustomProperty( 'link', true, linkElement );

                return linkElement;
            },
            converterPriority: 'low'
        } );

        editor.conversion.for( 'upcast' ).attributeToAttribute( {
            view: {
                name: 'a',
                key: 'rel',
                attributes: {
                    rel: ['noreferrer', 'nofollow']
                }
            },
            model: 'linkRel',
            converterPriority: 'low'
        } );

        editor.commands.add(LINKREL, new LinkAttributeCommand(this.editor, LINKREL));
    }
}
`
