### ISSUE TITLE
Image contextual toolbar does not disappear after clicking source editing.

### ISSUE THREAD

**Issue by blucayzer** [ckeditor/ckeditor5#16739]
## 📝 Provide detailed reproduction steps (if any)

1. Have a CKEditor 5 Classic Editor.
2. Insert an image via URL
3. Click SourceEditing.

This bug can be replicated if the first HTML tag is a figure. If the first HTML tag isn't a figure, the image contextual toolbar will disappear.

### ✔️ Expected result
![image](https://github.com/user-attachments/assets/d409a1bd-c54b-4d30-9392-d315523ba131)

The Image contextual toolbar should disappear after clicking the Source Editing.

### ❌ Actual result
![image](https://github.com/user-attachments/assets/2261401b-ff91-4371-b877-0af572e4f1f5)

The Image contextual toolbar does not disappear after clicking the Source Editing.

## 📃 Other details

* Browser: Edge
* CKEditor Version: v39
* This bug can be seen in the latest version of CKEditor.
* Can be replicated in the CKEditor Builder as seen in the screenshot above
* Installed CKEditor plugins: Source Editing and Image

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the report! Not reproducible in the docs, reproducible in the Builder and output (checked stackblitz).

**Comment by Witoso** [comment]
**@blucayzer** do I understand correctly you reproduce it in v39?

**Comment by blucayzer** [comment]
@Witoso, yes.

**Comment by Mati365** [comment]
Looks like it's not related to view-source functionality but rather blur handling in toolbar. I reproduced it with menubar.

![obraz](https://github.com/user-attachments/assets/2de5eb6a-bd1c-4a0f-bba3-d52e4bfc876f)

**Comment by Mati365** [comment]
I was able to reproduce this issue using the table toolbar, so it appears to be a global problem. It’s essential to ensure that the element with the toolbar is the first one in the document.

![obraz](https://github.com/user-attachments/assets/7eb3c0d3-e672-4c01-9490-b819e075861d)
