### ISSUE TITLE
CKEditor5 causes unexpected behaviour for text styles applied on links

### ISSUE THREAD

**Issue by peterwcm** [ckeditor/ckeditor5#16753]
## 📝 Provide detailed reproduction steps (if any)

With the HTML normalisation in CKEditor5, when applying a text style, `<span>` (and other inline elements) can no longer be a wrapper of `<a>`, even though it's valid HTML. The issue can be reproduced using the official demo page: https://ckeditor.com/docs/ckeditor5/latest/features/style.html

To reproduce:
1. Apply the `Spoiler` text style to some text that contains a link, e.g. the first sentence **_Nowadays, writing is often a team sport._**
2. The hover effect will break into 3 different parts because of the new HTML structure and that creates bad UX. Plus you have no control over the link style since the link tag itself has no class injected and CSS can't target an element based on the class of a child.

### ✔️ Expected result

In CKEditor4, the above HTML would be something like:
```
<p>
  <span class="spoiler">Nowadays, <a href="https://ckeditor.com">writing is often a team sport</a>.</span>
</p>
```
This would allow you to customise the inline link style however you want, and the selected text would appear as one single block, not three.

### ❌ Actual result

```
<p>
  <span class="spoiler">Nowadays, </span>
  <a href="https://ckeditor.com"><span class="spoiler">writing is often a team sport</span></a>
  <span class="spoiler">.</span>
</p>
```
The selected text is split into 3 blocks and the actual `spoiler` class in added to the `<span>` inside the link tag so you have no control over the link style at all, e.g. changing the hover underline color of the link in this case

### ❓ Possible solution

I know it would be difficult to just 'revert' back to how CKEditor4 works because of the massive restructure work. I would like to hear thoughts from you guys to see how we can work around this issue. Thanks!

## 📃 Other details

* Browser: Chrome Version 126.0.6478.127 (Official Build) (arm64)
* OS: macOS 14.4.1 (23E224)
* First affected CKEditor version: 5 (As shown on the demo page)
* Installed CKEditor plugins: As shown on the demo page

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This is how the internal engine of CKEditor 5 works, let's close is as a dup of #15408
