### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module (at main.js

### ISSUE THREAD

**Issue by faklolch** [ckeditor/ckeditor5#16757]
Видає помилку Uncaught SyntaxError: Cannot use import statement outside a module (at main.js

Як вирішити це питання

**Comment by filipsobol** [comment]
Hi @faklolch,

We need more information about your setup and a minimal reproducible example that we can use to reproduce this problem and help you fix it.

My guess is that you have a `<script>` tag that is missing a `type="module"` attribute.

```html
<!-- BEFORE -->
<script>
  // ...
</script>

<!-- AFTER -->
<script type="module">
  // ...
</script>
```

See the "[Installing CKEditor 5 from CDN](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/quick-start.html#installing-ckeditor-5-from-cdn)" section in out documentation for some usage examples.

**Comment by faklolch** [comment]
з цим розібрався, скрипт добавив не через файл main js, а просто вписав  в код сторінки  в 
<script type="module">
  // ...
</script>

Зробив встановив версію через builder. але мені треба кнопка submit. як добавити щоб отримувати дані з ckeditor.

**Comment by filipsobol** [comment]
Please refer to the "[Getting and setting data](https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/getting-and-setting-data.html)" document in our documentation.

**Comment by faklolch** [comment]
там не написано про кнопку submit

**Comment by faklolch** [comment]
і в цьому прикладі не працює editor.setData(value.content);

тільки в класичному варіанті при textarea

**Comment by faklolch** [comment]
ваша документація не зрозуміла.

**Comment by filipsobol** [comment]
To have the submit button, you can use the [editor inside the `<form>` element](https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/getting-and-setting-data.html#automatic-integration-with-html-forms).

If you need further help, please use English.

**Comment by faklolch** [comment]
this example only for Classic editor! it doesn't work in the built ckeditor

**Comment by filipsobol** [comment]
We need more information about your setup and a minimal reproducible example to be able to help you.
