### ISSUE TITLE
Crosslink feature guides

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1675]
* [x] Highlight to font color/bg color. 
* [x] Basic styles to remove format.
* [x] Font to remove format.

**Comment by msamsel** [comment]
I also include PR for `alignment` plugin, which is also supported by Remove Formatting.

**Comment by msamsel** [comment]
@Reinmar do you have an idea how to crosslink basic-styles and font with remove formatting?
You wrote:
> What you wrote is on the verge of being an implementation detail. We need a simple mention that text alignment can be removed with remove format. That said, I don't know where and how.

@mlewand asked me to take care of this issue. However, I don't have any better idea of where to put those references.

**Comment by mlewand** [comment]
@msamsel @AnnaTomanek will assist you in this. She has a good sense of what the docs should look like.

**Comment by AnnaTomanek** [comment]
Fixed with https://github.com/ckeditor/ckeditor5-basic-styles/commit/eba1cd2e5669ab85bed719b63927c0c3b5582bf6, https://github.com/ckeditor/ckeditor5-font/commit/1fcb78860b1e63a33c56a0961566d5051f294f67 and https://github.com/ckeditor/ckeditor5-indent/commit/ac4d0be9f965fed4baedfdfaa513a899f12bc39a.
