### ISSUE TITLE
Media embed not working

### ISSUE THREAD

**Issue by ever82** [ckeditor/ckeditor5#16769]
## 📝 Provide detailed reproduction steps (if any)

1. use chrome open https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#previewable-media
2. click the embeded videos 

### ✔️ Expected result

the videos will play 

### ❌ Actual result

the videos don't play

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
They are not meant to be playable within CKEditor. Otherwise, interacting with them would he harder (e.g. selecting).
