### ISSUE TITLE
Encoding issue with URL

### ISSUE THREAD

**Issue by kglickman** [ckeditor/ckeditor5#16768]
## 📝 Ask a question

We have a custom build of the Classic editor using build 42.  We are also using the React package.

If we try to create a link where the URL has encoded Asian characters in the query params, the URL gets corrupted.  If we create the same link in the official examples, it works fine.

Here is an example of a URL with this problem 
`https://xxx.yyy.com?param=%EF%BD%B6%EF%BD%BD%EF%BE%80%EF%BE%8F%EF%BD%B0%EF%BD%B4%EF%BD%B8%EF%BD%BD%EF%BE%8D%EF%BE%9F%EF%BE%98%EF%BD%B4%EF%BE%9D%EF%BD%BD%E9%83%A8`

Here is what it looks like after create the link in the editor
`https://xxx.yyy.com?param=ï½¶ï½½ï¾ï¾ï½°ï½´ï½¸ï½½ï¾ï¾ï¾ï½´ï¾ï½½é¨`

Is there some kind of encoding setting that needs to be added to our config?  I searched the docs but I didn't find anything.

**Comment by Reinmar** [comment]
We use UTF-8 everywhere. And it should be used all across the entire stack to ensure that things work correctly.

If you see any problems with encoding, that means that at some point you use a different one or a tool that does not work with UTF-8. This can be multiple things: both on the frontend and backend.

**Comment by kglickman** [comment]
Thank you.  It turns our that our code was unescaping the html before passing it into CKEditor.  I wasn't able to track down why the unescaping was added but it was a remnant from when we were using CKEditor4 so maybe it used to be needed.
