### ISSUE TITLE
Samsung keyboard autosuggest ignores the first character of second and later words

### ISSUE THREAD

**Issue by sofiyastrochyk** [ckeditor/ckeditor5#16761]
## 📝 Provide detailed reproduction steps (if any)

1. Open a CKEditor demo, e.g. https://ckeditor.com/ckeditor-5/demo/editor-types/ - Classic tab, or Mobile-friendly editor
2. Enable Predictive text in the keyboard settings
3. Place the cursor at a start of a new paragraph
4. Type more than 1 word

![Screenshot from 2024-07-18 16-10-22](https://github.com/user-attachments/assets/e7d20f68-3c8c-49f9-b27b-c65bd108d236)

[Screencast from 18.07.24 16:27:16.webm](https://github.com/user-attachments/assets/cd404fac-c6cb-4da5-942c-44f2cc76a731)

### ✔️ Expected result

One of the suggestions matches the most recent word typed (e.g. "test"), and the entire word is underlined

### ❌ Actual result

Only the part of the word after the first letter (e.g. "est") is underlined and matches suggested words 

## 📃 Other details

* Browser: Chrome
* OS: Android, v11.0
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This will be most likely fixed in the next version of the editor (rel: #14707, #14567).

You can test [the nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) if it resolved the problem.

**Comment by sofiyastrochyk** [comment]
This is great news, thanks, and the demo in the nightly version seems to work fine 👍
