### ISSUE TITLE
importmap

### ISSUE THREAD

**Issue by thien349k** [ckeditor/ckeditor5#16772]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
In case someone lands here in the future: CKEditor 5 has now a native support for importmaps. Read more in the docs: https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/quick-start.html
