### ISSUE TITLE
Source editing only available for super admins.

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [ckeditor/ckeditor5#16776]
## 📝 Ask a question

_What is your question? Please be as specific as possible to help us understand it._

Source Editing is only visible for super admins. We need to be visible to regular admins as well. Is there any setting/configuration option I can't find?

**Comment by Reinmar** [comment]
I guess you use CKEditor in a specific system, like a CMS or CRM. Please note that CKEditor is just the editor component used there, but how it's configured (which features are available to whom) is in the responsibilities of that system's authors.
