### ISSUE TITLE
An error occurred after deployment to the server

### ISSUE THREAD

**Issue by majintd** [ckeditor/ckeditor5#16789]
vue3+ckeditor5

Below is a screenshot of the error
![20240724163941](https://github.com/user-attachments/assets/b8f2319c-2f4a-4dde-931b-e71e16fbab6b)
![20240724163947](https://github.com/user-attachments/assets/fa200857-e213-40b2-b92a-540cb4b48c9f)

This is my code 
```
`<template>
  <div `id="app">`
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
  </div>
</template>

<script>
import { ClassicEditor, Bold, Essentials, Italic, Paragraph, Undo } from 'ckeditor5';
import CKEditor from '@ckeditor/ckeditor5-vue';

import 'ckeditor5/ckeditor5.css';
import 'ckeditor5-premium-features/ckeditor5-premium-features.css';

export default {
  name: 'app',
  components: {
    ckeditor: CKEditor.component
  },
  data() {
    return {
      editor: ClassicEditor,
      editorData: '<p>Hello from CKEditor 5 in Vue!</p>',
      editorConfig: {
        plugins: [ Bold, Essentials, Italic, Paragraph, Undo ],
        toolbar: [ 'undo', 'redo', '|', 'bold', 'italic' ],
        `licenseKey`: 'MyKey',
      }
    };
  }
};
</script>`
```

**Comment by filipsobol** [comment]
Could you please check if you have the same problem when using the alpha of the next major version of the integration?

You can install the `@ckeditor/ckeditor5-vue` package in version `7.0.0-alpha.2` and update the code like this:

```diff
<template>
  <div `id="app">`
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
  </div>
</template>

<script>
import { ClassicEditor, Bold, Essentials, Italic, Paragraph, Undo } from 'ckeditor5';
- import CKEditor from '@ckeditor/ckeditor5-vue';
+ import { Ckeditor } from '@ckeditor/ckeditor5-vue';

import 'ckeditor5/ckeditor5.css';
import 'ckeditor5-premium-features/ckeditor5-premium-features.css';

export default {
  name: 'app',
  components: {
-    ckeditor: CKEditor.component
+    ckeditor: Ckeditor
  },
  data() {
    return {
      editor: ClassicEditor,
      editorData: '<p>Hello from CKEditor 5 in Vue!</p>',
      editorConfig: {
        plugins: [ Bold, Essentials, Italic, Paragraph, Undo ],
        toolbar: [ 'undo', 'redo', '|', 'bold', 'italic' ],
        `licenseKey`: 'MyKey',
      }
    };
  }
};
</script>
```

**Comment by majintd** [comment]
@filipsobol I have tried according to the method you gave, and now the local code can not be used normally
````
import {  ClassicEditor, Bold, Essentials, Italic, Paragraph, Undo, PasteFromOffice, Underline } from 'ckeditor5';
import {Ckeditor} from "@ckeditor/ckeditor5-vue";
import 'ckeditor5/ckeditor5.css';
import 'ckeditor5-premium-features/ckeditor5-premium-features.css';
export default {
  name: 'app',
  components: {
    ckeditor: Ckeditor
  },
  data() {
    return {
      editor: ClassicEditor,
      editorData: '<p>Hello from CKEditor 5 in Vue!</p>',
      editorConfig: {
        plugins: [Bold, Essentials, Italic, Paragraph, Undo, PasteFromOffice, Underline ],
        toolbar: ['undo', 'redo', '|', 'bold', 'italic', 'Underline','insertImage','MathType','ChemType'],
        licenseKey: 'MyKey',
      }
    };
  },
};
</script>
````
![image](https://github.com/user-attachments/assets/595dbf6a-4dbc-4a10-a2f9-9bedcf4545c1)
![image](https://github.com/user-attachments/assets/208244e9-9dc9-40d9-ba75-9b9e17cf26ff)

**Comment by majintd** [comment]
> Could you please check if you have the same problem when using the alpha of the next major version of the integration?
> 
> You can install the `@ckeditor/ckeditor5-vue` package in version `7.0.0-alpha.2` and update the code like this:
> 
> ```diff
> <template>
>   <div `id="app">`
>     <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
>   </div>
> </template>
> 
> <script>
> import { ClassicEditor, Bold, Essentials, Italic, Paragraph, Undo } from 'ckeditor5';
> - import CKEditor from '@ckeditor/ckeditor5-vue';
> + import { Ckeditor } from '@ckeditor/ckeditor5-vue';
> 
> import 'ckeditor5/ckeditor5.css';
> import 'ckeditor5-premium-features/ckeditor5-premium-features.css';
> 
> export default {
>   name: 'app',
>   components: {
> -    ckeditor: CKEditor.component
> +    ckeditor: Ckeditor
>   },
>   data() {
>     return {
>       editor: ClassicEditor,
>       editorData: '<p>Hello from CKEditor 5 in Vue!</p>',
>       editorConfig: {
>         plugins: [ Bold, Essentials, Italic, Paragraph, Undo ],
>         toolbar: [ 'undo', 'redo', '|', 'bold', 'italic' ],
>         `licenseKey`: 'MyKey',
>       }
>     };
>   }
> };
> </script>
> ```

Thank you very much, I tried to update my vue version and now it seems that the problem has been solved

**Comment by filipsobol** [comment]
We will be releasing a stable `7.0.0` version in about two weeks. I highly recommend migrating to it when it's available, so that later you can get the bug fixes as they are released.
