### ISSUE TITLE
New global name for `ckeditor5` and `ckeditor5-premium-features`.

### ISSUE THREAD

**Issue by pszczesniak** [ckeditor/ckeditor5#16798]
### What has to be done

*   Change global name from `ckeditor5` into `CKEDITOR`,
*   Change global name from `ckeditor5-premium-features` into `CKEDITOR_PREMIUM_FEATURES`,
*   Extending our `@ckeditor/ckeditor5-dev-build-tools` build tools with the ability to pass the `globals` parameter.
* 	Update `ckeditor5-package-generator` with new mandatory flag `--global-name` to define a global name of the package to be used in UMD build.

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@ckeditor/qa-team this may cause some e2e tests fail if we have tests for UMD.
