### ISSUE TITLE
Multi-root editor: cannot focus root which has only block widget inside

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#16806]
## 📝 Provide detailed reproduction steps (if any)

1. Go to [multi-root editor demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/multi-root-editor.html)
2. Remove all content from one of the roots and add only a table
3. Focus other root and then try focusing the root with the table (but do not click on the table)

### ✔️ Expected result

Focus should stay in the root, similarly to a "standard" editor:

https://github.com/user-attachments/assets/e8a13c03-4516-4aab-b4a6-99bbb8c8324d

### ❌ Actual result

Focus jumps back to the other root, it's not possible to focus a root which has only block widget:

https://github.com/user-attachments/assets/45c1f190-1130-406b-a821-5f42f85c38a3

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pszczesniak** [comment]
It does not need to ba a table, it can be anything that selected got a toolbar/tooltip; for example an image:

https://github.com/user-attachments/assets/d59de37f-27ad-47ed-8a72-61c7643ab170

**Comment by Mati365** [comment]
@FilipTokarski / @pszczesniak I checked it on Firefox, on latest docs, and I'm not able to reproduce this issue. Can you still reproduce this?

**Comment by pszczesniak** [comment]
@Mati365 yes i can (Chrome).

**Comment by pszczesniak** [comment]
On Firefox it works as expected.

**Comment by Mati365** [comment]
Debug notes:

1. It's not recent regression. It's possible to reproduce it on 39 version. 
1. Increasing timeout in this function shows that clicking on editable does not focus nested block element:

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/observer/focusobserver.ts#L106-L110

![obraz](https://github.com/user-attachments/assets/b4cb0e71-7b7b-426e-b578-1d9fb3f12bb4)

so it's performing fallback to previously focused node

**Comment by f1ames** [comment]
I stumbled upon this same issue today. I prepared demo for rerepo and then found this issue... Anyway, I'll share it, maybe it could be helpful - https://stackblitz.com/edit/1haefu?file=main.js.

https://github.com/user-attachments/assets/575164a2-a75f-4135-bc86-d88175111a74

**What' interesting here** is the other part of this issue (however, I'm not 100% sure if it's the same cause) is how document selection updates when you focus and then deselect different roots.

AFAIU selecting the root (and then deselecting it) should result in document selection (`editor.editing.view.document.selection`) being placed inside this focused root. However, with block widget inside middle root something happens and selection gets back to middle root, as if it's gets stolen by it:

https://github.com/user-attachments/assets/48bdddea-00cf-498d-ade7-1ee12a9463d1

**Comment by Mati365** [comment]
@f1ames That's the same issue. I suspect that Chrome is not firing the selection change event after focusing editable containing block element. So we have focus but there is no selection, and the editor is trying to fall back to last known focus because editable does not contain any cursor. The funny thing is that forcing chrome to focus first block or contenteditable element works.

https://github.com/ckeditor/ckeditor5/pull/16892/files#diff-5dd5f41942a4096889e59688767ae58a1755591bf98f1e52c8c8e9baba0609d0R254-R282

I extracted the issue to bare minimum HTML here: https://stackblitz.com/edit/stackblitz-starters-lf3smh?file=index.html
