### ISSUE TITLE
Two sequential <blockquote> elements getting merged

### ISSUE THREAD

**Issue by vtulse** [ckeditor/ckeditor5#16812]
We have created a plugin **div wrapper**  wrap paragraphs into <div> tag using the same code which blockquote using
## 📝 Provide detailed reproduction steps (if any)

1. Add 2 the blockquote element sequentially
2. After saving the data while down casting it merge both elements into single

### ✔️ Expected result

![While-adding-element](https://github.com/user-attachments/assets/6b6fe9db-4ea0-4fbd-a907-56ee4a891972)

### ❌ Actual result

![Post save editing](https://github.com/user-attachments/assets/cf6c7291-60ba-488f-9974-45fb489eae7c)

## 📃 Other details
* Installed CKEditor plugins: CKEditor 5 blockquote

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi, please provide some code or reproducible sample. This cannot be yet classified as a bug, as your implementation changed the behavior. Merging block quotes is not reproducible in our demos. Thanks!

**Comment by vtulse** [comment]
Hello @Witoso 
This issue I'm facing with CKEditor using inside Drupal CMS
You can check how data casting makes issue here https://www.drupal.org/project/drupal/issues/3464368#comment-15703614

**Comment by Witoso** [comment]
If you created a custom plugin, we need to understand how you did it. The issue is not reproducible on our side.

**Comment by vtulse** [comment]
Yes, this is an issue with our preprocessor function where we are altering the html, closing this for working as expcted
