### ISSUE TITLE
Missing export for blockAutoformatEditing and inlineAutoFormatEditing in ckeditor5

### ISSUE THREAD

**Issue by slotterbackW** [ckeditor/ckeditor5#16815]
## 📝 Provide detailed reproduction steps (if any)

I'm not sure if I'm missing something obvious, but I'm working on upgrading to the latest CKEditor version, and when I try and import either the [blockAutoformatEditing](https://ckeditor.com/docs/ckeditor5/latest/api/module_autoformat_blockautoformatediting.html) or [inlineAutoFormatEditing](https://ckeditor.com/docs/ckeditor5/latest/api/module_autoformat_inlineautoformatediting.html) functions from `ckeditor5`

```
import { blockAutoformatEditing, inlineAutoformatEditing } from 'ckeditor5';
```

 I get an error saying `blockAutoformatEditing not found in 'ckeditor5'` and `inlineAutoformatEditing not found in 'ckeditor5'`.

For the record all the other plugins and functions I've imported from the new ckeditor5 package are working, which is why I'm wondering if this is a bug.

### ✔️ Expected result

I would expect the functions to be available to import via the `ckeditor5` package since the autoformat plugin is available via that package.

### ❌ Actual result

 I get an error saying `blockAutoformatEditing not found in 'ckeditor5'` and `inlineAutoformatEditing not found in 'ckeditor5'`.

## 📃 Other details

* OS: MacOS, Sonoma 14.5
* First affected CKEditor version: I'm on 42.0.2 for `ckeditor5`, but I'm guessing this is related to the `42.0.0` release.
* Installed CKEditor plugins: `[ckeditor5, ckeditor5-react, ckeditor5-dev-utils]`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the catch! Most likely, it was not caught during the Typescript migration that provided importing from `index`. v42.0.0, although a big release just re-exported indexes. We will fix this asap.

**Comment by slotterbackW** [comment]
Thanks so much for the quick action!
