### ISSUE TITLE
Quickstart guide problem Uncaught TypeError: Failed to resolve module specifier "ckeditor5". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by noa-no-h** [ckeditor/ckeditor5#16823]
## 📝 Provide detailed reproduction steps (if any)

I followed the quickstart guide here https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/quick-start.html#installing-ckeditor-5-using-npm
I created a new empty directory and within this directory, I completed the steps in "Installing CKEditor 5 using npm" without doing anything else. Then I launched a live server on a local port and loaded index.html. 

### ✔️ Expected result

I expected to see a minimal CKEditor.

### ❌ Actual result

I saw the words "Hello from CKEditor 5!" without any editor. I have the following 3 error messages in my console:

1. index.html:1 Denying load of chrome-extension://gomekmidlodglbbmalcneegieacbdmki/client/gpcWindowSetting.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
2. chrome-extension://invalid/:1 Failed to load resource: net::ERR_FAILED
3. index.html:1 Uncaught TypeError: Failed to resolve module specifier "ckeditor5". Relative references must start with either "/", "./", or "../".

## 📃 Other details

* Browser: Arc version 1.53.1
* OS: Mac M1 Sonoma 14.1.1
* First affected CKEditor version: 42.0.2 
* Installed CKEditor plugins: 42.0.2 

Thanks in advance for your help!

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi, using the editor from npm also needs a bundler that will correctly build JS files. CKEditor 5 is compatible with any modern JavaScript bundler. For a quick sample project setup, we recommend using [`Vite`](https://vitejs.dev/guide/).

We will update the docs, thanks for the issue.

If you want to download full working sample, the [builder](https://ckeditor.com/ckeditor-5/builder/https://ckeditor.com/ckeditor-5/builder/) provides such option.

**Comment by noa-no-h** [comment]
Thank you so much! I had missed the small text at the top of the builder that mentioned the bundler necessity. It's working now!

**Comment by Witoso** [comment]
Will be improved in the next release of the docs and new version.
