### ISSUE TITLE
toolbar print

### ISSUE THREAD

**Issue by zhangguangsen** [ckeditor/ckeditor5#1682]
## Is this a bug report or feature request? (choose one)
Other
🐞 Bug report  |  🆕 Feature request  |  Other

## 💻 Version of CKEditor
ckeditor5

## 📋 Steps to reproduce

1.
2.

## 📃 Other details that might be useful 
Why there is no print button in ckeditor5's toolbar?

**Comment by Mgsy** [comment]
>Why there is no print button in ckeditor5's toolbar?

There is no print button because this feature doesn't exist in CKEditor 5. Feel free to open a new feature request in this repository if you find this one important.
