### ISSUE TITLE
Placeholder does not disappear after inserting media

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1684]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master and the latest release.

## 📋 Steps to reproduce

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html or use local build documentation.
2. To the first editor (it must be empty), paste any URL to YT or add the media using the UI button.

## ✅ Expected result

`Type the content here!` should disappear.

## ❎ Actual result

But it does not:

![image](https://user-images.githubusercontent.com/2270764/55618849-ccd99300-5797-11e9-9617-2c6d941978a4.png)

## 📃 Other details that might be useful

I can reproduce it on Firefox, Chrome, and Safari.

**Comment by Mgsy** [comment]
Related [https://github.com/ckeditor/ckeditor5/issues/4114.](https://github.com/ckeditor/ckeditor5/issues/4114)
