### ISSUE TITLE
Improve spacings in UI list items

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#16844]
## 📝 Provide a description of the improvement

There is a logic that disables the space reserved for checkboxes in list items if no items have one leading to huge rendering differences between menus (see screenshots below). 

<img width="281" alt="Screenshot 2024-08-02 at 11 33 07" src="https://github.com/user-attachments/assets/44cff6fd-bda1-47a2-9cc6-6871171cd818">
<img width="424" alt="Screenshot 2024-08-02 at 11 33 01" src="https://github.com/user-attachments/assets/bc319700-af83-4b60-bbd3-07d849364b32">

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
Fixed on `release`.
