### ISSUE TITLE
ckeditor 5 Templates plugin, removes the style and class attributes added in the template data. 

### ISSUE THREAD

**Issue by ganeshudaya** [ckeditor/ckeditor5#16852]
## 📝 Ask a question

_What is your question? Please be as specific as possible to help us understand it._

I am using ckeditor 5's Template feature from productivity pack. 
In the ckeditor 5 website there is a demo for Templates and Slash Command, where I am able to see Templates created with style and class attributes. 
But when I try the same, the ckeditor 5 removes the class and style attributes. 
Not sure what I missing

**Sample template definition.** 

{
            title: 'Signature (multi-line)',
            data: `<p **style='margin-left:2em;'**><span'><strong>I hereby verify that the aforementioned report has undergone thorough factual verification and reflects the most current information.</strong></span></p>
              <p **style='margin-left:22em;'**><br>
              <span'>Signature: __________&nbsp;&nbsp;</span><br>
              <span'>Name:&nbsp;</span><br>
              <span'>Title:&nbsp;</span><br>
              <span'>Date:</span></p>
              <div id="100">ID DIV</div>`,
            description: 'Author signature with statement',
            icon: ``,
          }

**Image from ckeditor 5 demo**
![image](https://github.com/user-attachments/assets/739d32e1-d5ee-4b4d-9ca7-897b24ab8bf8)

**Comment by Witoso** [comment]
Hi! By default, if the editor is not configured, it won't accept the content, element or attributes, it doesn't know about. The quickest way would be to enable the [General HTML Support](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html) plugin, and configure it with the content you want to preserve.

**Comment by ganeshudaya** [comment]
Thank you @Witoso for reply. It helps.
