### ISSUE TITLE
Nested item gets focused in menu bar after clicking category button

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#16857]
## 📝 Provide detailed reproduction steps (if any)

https://github.com/user-attachments/assets/1f461809-3fbc-4fd6-bdab-5eade6a97a78

After clicking the "category" button like "Image", or "Text", the first item inside gets focused and stays focused. Earlier we decided to show focus only on keyboard interaction.

**Comment by Mati365** [comment]
@scofalik It's not entirely a bug. From what I remember, it handles case when user press arrow down after clicking menu. Without such selection, it's kinda hard for the user to distinguish which menu item should be highlighted - parent menu item or nested menu item.

**Comment by scofalik** [comment]
It might be the case, probably to be discussed then.

**Comment by Mati365** [comment]
@scofalik Yep, it's not super intuitive, though. Probably needs adjustments.

**Comment by oleq** [comment]
We discussed this topic and we figured out the best solution would be no action upon clicking a menu category button (unless it violates WCAG).

**Comment by Comandeer** [comment]
It shouldn't violate WCAG as a focus indicator is needed only for keyboard navigation.
