### ISSUE TITLE
how can i make a plugins that support callback function like autosave?

### ISSUE THREAD

**Issue by LouisMing** [ckeditor/ckeditor5#1687]
## Is this a bug report or feature request? (choose one)

Other

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
>how can i make a plugins that support callback function like autosave?

Could you be more specific in your question? What do you want to achieve?

**Comment by LouisMing** [comment]
> > how can i make a plugins that support callback function like autosave?
> 
> Could you be more specific in your question? What do you want to achieve?

I want develop a saving butoong like ms office word. my boss perfer oparating butoon to autosaving.
but I don't kown the way to make a callback function in config,

**Comment by Mgsy** [comment]
Take a look at our [getting and saving data guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html). You'll find there a code sample how to save data with a button.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
