### ISSUE TITLE
Table doesn't respect the pagination page break after exporting to PDF

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#16875]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/latest/features/pagination/pagination-integration.html#demo
2.  Remove the page break element
3.  Export the PDF document

### ✔️ Expected result

In the exported document, the table starts on the second page.

![](https://github.com/user-attachments/assets/cfc8d9df-869f-4d78-b755-6bc0905306fb)

### ❌ Actual result

In the exported document, the table is still on the first page.

![](https://github.com/user-attachments/assets/92af63b3-7e51-4057-abf6-3c5cdb21a903)

## 📃 Other details

*   The same behavior can be reproduced in the demo at ckeditor.com - [https://ckeditor.com/export-to-pdf-word/#pagination](https://ckeditor.com/export-to-pdf-word/#pagination)
*   It doesn't seem to be a regression

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mati365** [comment]
@Mgsy It looks like it works on nightly https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/pagination/pagination-integration.html#demo. Maybe related to:

https://github.com/cksource/ckeditor5-commercial/issues/6289
https://github.com/cksource/ckeditor5-commercial/issues/5708

**Comment by Witoso** [comment]
Yes, this should be solved in the release that just came out v43.0.0.
