### ISSUE TITLE
Duplicated Modules Error When Trying to Add Plugins in Next.js

### ISSUE THREAD

**Issue by 0x0wen** [ckeditor/ckeditor5#16891]
## 📝 Ask a question

I tried to add the TableColumnResize plugin to my editor, but even after following the documentation, its still resulting in an error.
Here is the source code:

1. index.js
`
const CustomCKEditor = dynamic(() => import("@/components/Elements/Input/ckEditor"), {
	ssr: false,
});
<CustomCKEditor
	value={content}
	onChange={handleContent}
	editorConfig={editorConfig}
        website={website}
	token={token}
/>`

2. editor.js
`"use client";
import { useState } from "react";
import { CKEditor } from "@ckeditor/ckeditor5-react";
import { ClassicEditor, TableColumnResize } from "ckeditor5";
import axios from "axios";
import ImageEditor from "../Editor/ImageEditor";
import "ckeditor5/ckeditor5.css";
import { useImageUpload } from "@/utils/hooks/useImageUpload";
`

I suggest the problem is in the module imports, hence i only show the importing parts of the code.

And here is a clip of the error
![image](https://github.com/user-attachments/assets/ff58b749-1761-49e3-8a9c-5791b957b212)

**Comment by Witoso** [comment]
Hi! Please share the versions of packages, and the whole code of the Editor setup.

```
{ ClassicEditor, TableColumnResize } from "ckeditor5";
```

This line suggests that you're using a predefined builds, those are in maintenance only mode, you need to provide all plugins to the editor if you're using v42+. See the [migration guide](https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/predefined-builds.html).

**Comment by 0x0wen** [comment]
It is solved now! I wasn't aware of the update and that part of the docs, apparently it is a version problem (I was using the 42.0.2 version).

All i did was following the guide you provide which is uninstalling old build package and installs the new one (also update the ckeditor for react package).

Thank you so much for the help, and much much respect for the fast response👍🔥
