### ISSUE TITLE
CKeditor 5 Custom Build

### ISSUE THREAD

**Issue by foryougautam** [ckeditor/ckeditor5#16904]
I am attempting to create a custom build of CKEditor from the stable branch. However, even after ensuring that all versions are consistent, I am still encountering duplicity errors.

Steps Taken:
Checkout Stable Branch: I started by checking out the stable branch of CKEditor for the custom build.
Align Versions: I ensured that all versions were set to 41.4.2 for consistency.
Install Dependencies: I ran npm install using the --legacy-peer-deps flag to handle peer dependencies.
Add Custom Plugin: I included a custom plugin, specifically [ckeditor5-math by isaul32](https://github.com/isaul32/ckeditor5-math).
Build Process: I initiated the build process using npm run build.
Run Sample: Finally, I ran a sample index.html to test the build.
Despite following these steps, I am still encountering issues related to duplicity. Any guidance on how to resolve this would be greatly appreciated.

﻿Error in console
version.js:149 Uncaught 
CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at version.js:149:11
    at ckeditor.js:6:1939691
    at universalModuleDefinition:11:1
    at universalModuleDefinition:9:27
    at universalModuleDefinition:1:1

index.html:31 Uncaught 
ReferenceError: ClassicEditor is not defined
    at index.html:31:2
    
Package.json
{
  "name": "@ckeditor/ckeditor5-build-classic",
  "version": "41.4.2",
  "description": "The classic editor build of CKEditor 5 – the best browser-based rich text editor.",
  "keywords": [
    "ckeditor5-build",
    "ckeditor",
    "ckeditor5",
    "ckeditor 5",
    "wysiwyg",
    "rich text",
    "editor",
    "html",
    "contentEditable",
    "editing",
    "operational transformation",
    "ot",
    "collaboration",
    "collaborative",
    "real-time",
    "framework"
  ],
  "main": "./build/ckeditor.js",
  "types": "./build/ckeditor.d.ts",
  "files": [
    "build",
    "ckeditor5-metadata.json",
    "CHANGELOG.md"
  ],
  "dependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "41.4.2",
    "@ckeditor/ckeditor5-autoformat": "41.4.2",
    "@ckeditor/ckeditor5-basic-styles": "41.4.2",
    "@ckeditor/ckeditor5-block-quote": "41.4.2",
    "@ckeditor/ckeditor5-ckbox": "41.4.2",
    "@ckeditor/ckeditor5-ckfinder": "41.4.2",
    "@ckeditor/ckeditor5-cloud-services": "41.4.2",
    "@ckeditor/ckeditor5-easy-image": "41.4.2",
    "@ckeditor/ckeditor5-editor-classic": "41.4.2",
    "@ckeditor/ckeditor5-essentials": "41.4.2",
    "@ckeditor/ckeditor5-heading": "41.4.2",
    "@ckeditor/ckeditor5-image": "41.4.2",
    "@ckeditor/ckeditor5-indent": "41.4.2",
    "@ckeditor/ckeditor5-link": "41.4.2",
    "@ckeditor/ckeditor5-list": "41.4.2",
    "@ckeditor/ckeditor5-media-embed": "41.4.2",
    "@ckeditor/ckeditor5-paragraph": "41.4.2",
    "@ckeditor/ckeditor5-paste-from-office": "41.4.2",
    "@ckeditor/ckeditor5-table": "41.4.2",
    "@ckeditor/ckeditor5-typing": "41.4.2",
    "@isaul32/ckeditor5-math": "^41.4.2"
  },
  "devDependencies": {
    "@ckeditor/ckeditor5-core": "41.4.2",
    "@ckeditor/ckeditor5-dev-translations": "^42.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^41.0.0",
    "@ckeditor/ckeditor5-theme-lark": "41.4.2",
    "terser-webpack-plugin": "^4.2.3",
    "typescript": "5.0.4",
    "webpack": "^5.58.1",
    "webpack-cli": "^4.9.0"
  },
  "author": "CKSource (http://cksource.com/)",
  "license": "GPL-2.0-or-later",
  "homepage": "https://ckeditor.com/ckeditor-5",
  "bugs": "https://github.com/ckeditor/ckeditor5/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/ckeditor/ckeditor5.git",
    "directory": "packages/ckeditor5-build-classic"
  },
  "scripts": {
    "build": "webpack --mode production",
    "postbuild": "tsc -p ./tsconfig.types.json"
  }
}

**Comment by Witoso** [comment]
Hi! The best way would be to investigate the lock file for different installed versions of CKEditor packages. It will show which package pulled what.

**Comment by foryougautam** [comment]
> Hi! The best way would be to investigate the lock file for different installed versions of CKEditor packages. It will show which package pulled what.

Thanks fixed now this is parent folder lock file

**Comment by foryougautam** [comment]
Closing as this is fixed now
