### ISSUE TITLE
Inconsistent behavior for URL fields

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#16902]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html
2. Select any text and press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>K</kbd> to open link balloon toolbar.
3. Type any URL (e.g. `https://ckeditor.com`) and press <kbd>Enter</kbd> while the URL input is still focused. The link should be added
4. Open the Image dropdown and select the "Insert via URL" option.
5. Type any URL (e.g. `https://placehold.co/200x300`) and press <kbd>Enter</kbd> while the URL input is still focused.

### ✔️ Expected result

The image should be inserted into the editor – just like it happened with the link.

### ❌ Actual result

Nothing happens, the <kbd>Enter</kbd> keypress is ignored.

### ❓ Possible solution

The <kbd>Enter</kbd> key behavior from the Link balloon is connected with the [implicit form submission behavior](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission): if the text `input` in the form is focused when the user presses <kbd>Enter</kbd>, the form is submitted.

The `input` in the Link balloon is encapsulated inside a `form` and thanks to that, pressing <kbd>Enter</kbd> inserts the link. However, the `input` in the Image dialog is not encapsulated inside a `form` leading to a worse user experience (the user needs to either click the "Insert" button or – if they use only the keyboard for navigation – tab to the "Insert" button and press <kbd>Enter</kbd>/<kbd>Space</kbd>). Adding the `form` element to the Image dialog should fix the issue.

## 📃 Other details

* Browser: N/A (de facto all browsers support the implicit form submission)
* OS: N/A
* First affected CKEditor version: 42.0.0
* Installed CKEditor plugins: `image`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Looks like we're missing `'form'` here 

https://github.com/ckeditor/ckeditor5/blob/ef327bb501e3e0b579c16ce7fd5b1713fd095cbe/packages/ckeditor5-image/src/imageinsert/ui/imageinserturlview.ts#L72

and a submit handler similar to this one

https://github.com/ckeditor/ckeditor5/blob/ef327bb501e3e0b579c16ce7fd5b1713fd095cbe/packages/ckeditor5-media-embed/src/ui/mediaformview.ts#L105-L107
