### ISSUE TITLE
Hide or Disable AI Assistant custom command text box and have custom label below it

### ISSUE THREAD

**Issue by cdhemant** [ckeditor/ckeditor5#16906]
We are trying to integrate AI Commands plugin. We want to restrict user from entering custom text and instead use only predefined set of AI Commands.
Is there configuration property to hide or disable AI Assistant custom command text box.
![image](https://github.com/user-attachments/assets/22dd349d-f360-4343-a079-d72da5663eee)

And to show custom label the AI popup

**Comment by Witoso** [comment]
Hey @cdhemant, for commercial plugins, please reach out to [support](https://ckeditor.com/contact/), as our tech teams tend to respond on this channel first. Thanks!
