### ISSUE TITLE
Link plugin not working as expected

### ISSUE THREAD

**Issue by flaviubln** [ckeditor/ckeditor5#16912]
Hello, guys

Im currently using ckeditor5 (licensed) and I need to customize the link functionality a bit.
What I want is that when I insert a link I want it to open in a new tab if it's an external link and add a little icon after the link and if the link contains a specific regex/domain (e.g. flv.com) then to open it in the same page (not a new tab).
I've been trying to achieve this with decorators, but it doesn't seem to work properly. And I dont know if I can add that icon tho.

Thank u lots.

**Comment by martynawierzbicka** [comment]
Hello,

Thank you for creating a ticket. If you are a licensed user please send your request via our support channel: support@cksource.com.

Many thanks!
