### ISSUE TITLE
Inline editor toolbar is lost on mobile and desktop

### ISSUE THREAD

**Issue by jjroelofs** [ckeditor/ckeditor5#16914]
Original issue: https://github.com/ckeditor/ckeditor5/issues/7695 by @jodator 

> ## 📝 Provide detailed reproduction steps (if any)
> 1. Open inline editor sample
> 2. Click in one of the lowest editing areas.
> 
> ### ✔️ Expected result
> The toolbar is fully visible.
> 
> ### ❌ Actual result
> It is not.
> 
> ![](https://user-images.githubusercontent.com/247363/88363115-3b70a480-cd7f-11ea-99f6-e406f61cb9a3.png)
> 
> ## 📃 Other details
> * Browser: Chrome
> * OS: Android
> * Related: [The Balloon block editor sample UI is off the screen on mobile #1544](https://github.com/ckeditor/ckeditor5/issues/1544).
> 
> If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jjroelofs** [comment]
This is still a bug and to me it is a critical bug because am not aware of any workaround. In our drag and drop page builder, it's possible for a user to create a 50/50 split column even on a small screen, and if the toolbar ends in the middle the screen, this is when this bug is more critical:

![image](https://github.com/user-attachments/assets/a261eb9a-1703-4d94-9246-6bd8cc76fb36)

**Comment by jjroelofs** [comment]
The problem is also reproducible on desktop resolutions:

![image](https://github.com/user-attachments/assets/3e84bfd6-b2f5-494d-81ce-833340e0ecc4)

**Comment by Witoso** [comment]
Thanks for the report, let's move this issue under this one: #9763
