### ISSUE TITLE
hgroup and summary do not accept heading elements

### ISSUE THREAD

**Issue by jwylarsen** [ckeditor/ckeditor5#16947]
## 📝 Provide detailed reproduction steps (if any)

1. Enter source editing mode
2. Create an hgroup element and add a heading element
3. Create a details element with a child summary element and add a heading element
4. Toggle back to design mode
5. Toggle back to source mode

### ✔️ Expected result

Code is preserved as written.

### ❌ Actual result

hgroup and summary elements are removed

### ❓ Possible solution

submitting PR to fix this in schema definitions

## 📃 Other details

* Browser: Chrome, Firefox
* OS: Windows 11, Ubuntu
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
The problem is in invalid configuration of the GHS `hgroup` element:

https://github.com/ckeditor/ckeditor5/blob/08270aafcc6e7e4fb4f4a4d2ebbc7451f031d303/packages/ckeditor5-html-support/src/schemadefinitions.ts#L340-L354

It should be:
```
{
	model: 'htmlHgroup',
	view: 'hgroup',
	modelSchema: {
		allowIn: '$root',  // <- this is missing
		allowChildren: [
			'paragraph',  // <- this is missing
			'htmlP',  // <- this is missing
			'htmlH1',
			'htmlH2',
			'htmlH3',
			'htmlH4',
			'htmlH5',
			'htmlH6'
		],
		isBlock: false
	}
},
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup#technical_summary) it's not a regular container so it does not allow other containers and also it allows only headings and paragraphs inside.

**Comment by jwylarsen** [comment]
@niegowski That's great. Do you know how to fix the summary element as well? It should accept EITHER $text OR exactly 1 heading element. A little bit trickier.

**Comment by Comandeer** [comment]
@jwylarsen, the [specification](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element) allows more than one heading in the `summary` element:
 
> [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2), optionally intermixed with [heading content](https://html.spec.whatwg.org/multipage/dom.html#heading-content-2).

It means that any number of heading elements is valid according to the specification, e.g. the following HTML is valid:

```html
<details>
  <summary>
    <em>Test</em>
    <h2>Test</h2>
    <strong>Test</strong>
    <h3>Test</h3>
  </summary>
  <p>Lipsum</p>
</details>
```

[Validator agrees](https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%3Bbase64%2CPCFET0NUWVBFIGh0bWw%2BDQo8aHRtbCBsYW5nPSIiPg0KICA8aGVhZD4NCiAgICA8dGl0bGU%2BVGVzdDwvdGl0bGU%2BDQogIDwvaGVhZD4NCiAgPGJvZHk%2BDQogICAgPGRldGFpbHM%2BDQogICAgICA8c3VtbWFyeT4NCiAgICAgICAgPGVtPlRlc3Q8L2VtPg0KICAgICAgICA8aDI%2BVGVzdDwvaDI%2BDQogICAgICAgIDxzdHJvbmc%2BVGVzdDwvc3Ryb25nPg0KICAgICAgICA8aDM%2BVGVzdDwvaDM%2BDQogICAgICA8L3N1bW1hcnk%2BDQogICAgICA8cD5MaXBzdW08L3A%2BDQogICAgPC9kZXRhaWxzPg0KICA8L2JvZHk%2BDQo8L2h0bWw%2B).

**Comment by jwylarsen** [comment]
@Comandeer Good to know! I was just going off of what MDN said. Either way, I've submitted a PR to address both hgroup and summary issue here: https://github.com/ckeditor/ckeditor5/pull/16951
