### ISSUE TITLE
Footnote feature 

### ISSUE THREAD

**Issue by AnasSawalha995** [ckeditor/ckeditor5#16955]
The proposed feature is a custom footnote plugin for CKEditor that enhances text editing by allowing users to easily insert and manage footnotes within their documents. The expected behavior of this feature includes:

1. Footnote Insertion: Users can insert footnotes anywhere within the text. Each footnote will be linked to a corresponding reference number within the document, displayed as a superscript number.

2.Footnote List Management: A footnote container will be available at the end of the document, displaying a numbered list of all footnotes. Each item in this list will include the footnote text and an asterisk linking back to the reference number in the main text.

3. Title and Structure: The footnote section will have a clear title, "Footnote," and will maintain a structured format with numbered items. This section will be visually distinct and automatically updated as footnotes are added or removed.

4. Content Protection: The feature will prevent accidental deletion or modification of the footnote section title and its content. This ensures that the integrity of the footnote list and its references is preserved throughout the editing process.

5. Dynamic Updates: When footnotes are added, removed, or edited, the corresponding references and footnote list will update dynamically to reflect these changes, maintaining consistency and accuracy in the document.

Overall, this feature aims to streamline the process of managing footnotes, making it easier for users to reference and organize additional information in their documents without compromising the layout and structure.

here is a link that will give and insight https://www.tiny.cloud/docs/tinymce/latest/footnotes/

**Comment by Witoso** [comment]
Thanks for the issue. This is a dup of #1965. Please move discussion there.
