### ISSUE TITLE
Contextual balloon does not work with non-empty selection

### ISSUE THREAD

**Issue by Tadaz** [ckeditor/ckeditor5#16958]
## 📝 Provide detailed reproduction steps (if any)

I have just migrated to v.43 and I noticed that a couple of my custom plugins are not working properly. Both of them have the same issue that can be replicated in [your docs page](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/abbreviation-plugin/abbreviation-plugin-level-2.html#demo).

As per the recording below you can see that trying to use your example "Abbreviation" is not possible.  When content is selected the contextual balloon does not appear and there is no error/warning about that.
![bug](https://github.com/user-attachments/assets/c9bd99f5-a4d8-419f-9953-71d76db8455b)

I have tried multiple browsers - the issue persists.

### ✔️ Expected result

The abbreviation contextual balloon should appear all the time.

### ❌ Actual result

The abbreviation contextual balloon appears only when the 0 coordinate is included in selection.

## 📃 Other details

* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
* OS: macOS Sonoma 14.4
* First affected CKEditor version: 43
* Installed CKEditor plugins: 
  * @ckeditor/ckeditor5-vue
  * ckeditor5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for the report, we will begin investigation asap. Potential cause: #16739
