### ISSUE TITLE
How to get content with html entities replaced?

### ISSUE THREAD

**Issue by kamitorl** [ckeditor/ckeditor5#1697]
Hi there.
CKeditor4 replaced any "<" written by the user into "& lt; "  (all together) and ">" into "& gt;"  (all together). But now that is not happening, so if someone writes, i.e. < select > (all together), and i put that content outside the ckeditor, this is going to be understood as HTML.
Is there any way to get that content replaced?
Thanks!!

**Comment by mlewand** [comment]
CKEditor 5 also converts the entities while outputting them. You can easily verify this by opening [Classic build example](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) clearing the content and typing "`foo < bar > baz`" as a text there. Then open up the console and call `editor.getData()`.

It return entities properly as expected. Either verify your use case, or provide us with step by step test case how to reproduce the problem.

**Comment by kamitorl** [comment]
Sorry!! You're right!!
