### ISSUE TITLE
shift + del do not cut text to the clipboard with <br/>

### ISSUE THREAD

**Issue by C1aus** [ckeditor/ckeditor5#1698]
🐞 Bug report 
## 💻 Version of CKEditor
4
## 📋 Steps to reproduce
1. Enter text with two lines, separated with [Enter]
2. Select all text and press shift + del 
## ✅ Expected result
I can insert related text from clipboard with shift + ins keys combination.
## ❎ Actual result
I can't insert text with shift + ins keys combination.

**Comment by Mgsy** [comment]
> Version of CKEditor
4

Hi, this is an issue tracker for CKEditor 5. If you have a problem related to CKEditor 5, please report it in the proper repository - https://github.com/ckeditor/ckeditor-dev/issues.
