### ISSUE TITLE
Gulp tasks refactoring

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#170]
We're slowly getting to the point where the existing tasks will need to be refactored, to accumulate the amounts of code and raising complexity. 

Example issues:

1. Splitting utils to multiple files. Currently we have some groups like build utils, but they are used by multiple tasks.
2. Postponing `require()` calls, to speed up gulp bootstrap. Currently the whole `gulpfile.js` has a huge dependency tree so it takes 1-3s just to load all the code.
3. Builder will need to be given some proper architecture, so its extensible.

**Comment by Reinmar** [comment]
Related issue: https://github.com/ckeditor/ckeditor5/issues/74

**Comment by maxbarnas** [comment]
> 2 Postponing require() calls, to speed up gulp bootstrap. Currently the whole gulpfile.js has a huge dependency tree so it takes 1-3s just to load all the code.

This suggestion became invalid after bunch of tests.

**Comment by szymonkups** [comment]
Gulp tasks were moved to separate repositories, some refactoring was done during this process.
