### ISSUE TITLE
Balloon Editor toolbar sticks out of the limiter element while scrolling

### ISSUE THREAD

**Issue by michalbilik** [ckeditor/ckeditor5#17002]
## 📝 Provide detailed reproduction steps (if any)
Also reproducible on the `release` branch, and in the `ckeditor5-ui/tests/manual/blocktoolbar/scrollable-blocktoolbar.html` manual test.

1. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/balloon-block-editor.html
2. Add `style="max-height: 300px; max-width: 400px; overflow: auto;"` style to the parent container of `ck-editor__editable`.
```html
<div class="live-snippet" style="max-height: 300px; max-width: 400px; overflow: auto;">
</div>
``` 
3. Select some content, and press the Balloon Block button (⠿).
4. Scroll up or down.

### ✔️ Expected result
The toolbar hides when scrolling.

### ❌ Actual result
The toolbar moves with the scroll and does not hide.

https://github.com/user-attachments/assets/6c495658-f549-4d24-9707-277886b28d4a

### ❓ Possible solution
Related to: https://github.com/ckeditor/ckeditor5/issues/5460

## 📃 Other details

* Browser: all
* OS: macOS
* First affected CKEditor version: 43.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mati365** [comment]
Follow-up of https://github.com/ckeditor/ckeditor5/pull/16685

**Comment by niegowski** [comment]
The case of a contextual balloon is not a regression. Only the block balloon toolbar is a regression.

**Comment by Mati365** [comment]
@michalbilik can you split this ticket into two separate issues? First one about Case 1, and the second one about Case 2?

**Comment by michalbilik** [comment]
The contextual balloon issue was moved to: https://github.com/ckeditor/ckeditor5/issues/17009.

**Comment by Mati365** [comment]
Thanks!
