### ISSUE TITLE
Focusing table after setting border: none makes table shrink and results in text content "jumping"

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#17000]
## 📝 Provide detailed reproduction steps (if any)

1. Open feature rich docs demo on latest `release`
2. Add a table
3. Add text to cells
4. Set table properties to `border: none`
5. Focus and blur cell with text a few times

### ✔️ Expected result

Table dimensions do not change.

### ❌ Actual result

When focusing the cell the table shrinks a bit, creating ugly effect of the content "jumping". It's more visible when ther is more content inside the table.

https://github.com/user-attachments/assets/1c1eac24-8bb5-4dc6-b0da-435ed21c746a

https://github.com/user-attachments/assets/e11c9af0-814f-41a2-ae8d-fae857851291

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mati365** [comment]
Maybe related to https://github.com/ckeditor/ckeditor5/issues/17000
