### ISSUE TITLE
Can I modify, the default toolbar icon with custom text or icon?

### ISSUE THREAD

**Issue by premsanth-rajamani** [ckeditor/ckeditor5#1702]
Im using classic editor in ckeditor 5,
Can i modify the default toolbar icons with custom icons/text.

Existing:

<img width="409" alt="Screenshot 2019-04-13 at 4 36 57 PM" src="https://user-images.githubusercontent.com/35285960/56079021-22ebad80-5e0c-11e9-850c-3d5f45587869.png">

Expected:

<img width="409" alt="Screenshot 2019-04-13 at 4 36 57 PM" src="https://user-images.githubusercontent.com/35285960/56078985-c7b9bb00-5e0b-11e9-8d88-edbd6e0cc43b.png">

**Comment by Mgsy** [comment]
Hi! It's possible to make such changes. Please, take a look at our [ButtonView documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_buttonview-ButtonView.html).

If you want to use a custom icon, pass to the `set()` method `icon` property with a path to the icon. For using text instead of an icon, user `withText: true` property.

Here is an example - to change the `Font size` icon, modify a path to it in the following line in the feature code - https://github.com/ckeditor/ckeditor5-font/blob/master/src/fontsize/fontsizeui.js#L18.

If you want to use a text, in the same file modify code as follows:
```js
dropdownView.buttonView.set( {
    label: t( 'Font Size' ),
    // icon: fontSizeIcon, --> remove icon
    tooltip: true,
    withText: true // --> use text instead of icon
} );
```

**Comment by premsanth-rajamani** [comment]
@Mgsy I could apply the solution above if i created a custom plugin, but what if i want to modify default toolbar styles. Here, I have used one of the default toolbar menu - fontSize.
Is there a way to override default toolbar styles?

`ClassicEditor.create(editor, {
  fontSize: { options: [9, 10, 11, 12, 14, 19, 21] },
  toolbar: [
    "fontSize",
    "bold",
    "italic",
    "underline",
    "bulletedList",
    "numberedList",
    "link"
  ]
});`

**Comment by atzork** [comment]
> `ClassicEditor.create(editor, { fontSize: { options: [9, 10, 11, 12, 14, 19, 21] }, toolbar: [ "fontSize", "bold", "italic", "underline", "bulletedList", "numberedList", "link" ] });`

I have same issue and nowhere can i find a solution.

**Comment by castroCrea** [comment]
I'm looking for a solution too +1 👍

**Comment by zeeskhan1990** [comment]
@Mgsy  Any updates on this problem? I have the same issue. I want to remove the fontSize Icon and just show font-sizes itself on the dropdown. But I can't seem to find a way to remove the icon without needing to create a completely separate custom plugin for the same.

**Comment by isetpro** [comment]
@Mgsy Do you help me? I cannot find a normal solution of my issue - disable text in default 'headers' button.

**Comment by shrutika-agrawal** [comment]
Found this on another question - https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-customize-the-ckeditor-5-icons
https://github.com/ckeditor/ckeditor5/issues/7810
Hope this is what you are looking for.

**Comment by Dlas1212** [comment]
@premsanth-rajamani @isetpro @castroCrea  @atzork @zeeskhan1990 

Found the solution: 

```
const specialCharactersButtonView = editor.ui.view.toolbar.items._items.find(item => item.label === 'Special characters')
if (specialCharactersButtonView) {
    specialCharactersButtonView.icon = '<svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="26.000000pt" height="25.000000pt" viewBox="0 0 26.000000 25.000000" preserveAspectRatio="xMidYMid meet"><g transform="translate(0.000000,25.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none"><path d="M68 234 c-60 -32 -78 -129 -33 -183 67 -79 186 -52 215 48 28 100 -88 187 -182 135z m120 -17 c30 -14 52 -56 52 -98 0 -43 -56 -99 -99 -99 -99 0 -156 115 -88 178 43 41 81 46 135 19z"/><path d="M80 150 c0 -11 5 -20 10 -20 6 0 10 9 10 20 0 11 -4 20 -10 20 -5 0 -10 -9 -10 -20z"/><path d="M166 163 c-12 -12 -6 -33 9 -33 8 0 15 6 15 14 0 17 -14 28 -24 19z"/><path d="M75 100 c-10 -16 14 -49 40 -56 32 -8 75 19 75 46 0 18 -7 20 -54 20 -30 0 -58 -4 -61 -10z m105 -10 c0 -5 -22 -10 -50 -10 -27 0 -50 5 -50 10 0 6 23 10 50 10 28 0 50 -4 50 -10z"/></g></svg>'
}
```
