### ISSUE TITLE
ckeditor-Duplicate-Modules

### ISSUE THREAD

**Issue by bulli1979** [ckeditor/ckeditor5#17027]
## 📝 Provide detailed reproduction steps (if any)

import Model from '@ckeditor/ckeditor5-ui/src/model';
import { Plugin, ListDropdownItemDefinition, SplitButtonView, createDropdown, Collection, addListToDropdown } from "ckeditor5";

export class PlaceholderPlugin extends Plugin {
  callFunction: any;

  init() {
    const editor = this.editor;
    const editorConfig = editor.config;
    console.log(editorConfig);
    const placeHolderItems = editor.config.get('placeHolderData.items') as [];
    console.log(placeHolderItems);

    const items = new Collection<ListDropdownItemDefinition>();

    for (const placeholder of placeHolderItems) {
      items.add(this.createDropDownButton(placeholder, editor));
    }

    // The button must be registered among the UI components of the editor
    // to be displayed in the toolbar.
    editor.ui.componentFactory.add('placeholder', (locale) => {
      // The button will be an instance of ButtonView.
      const dropDown = createDropdown(locale, SplitButtonView);
      dropDown.buttonView.set({
        withText: true,
        label: "Placeholder",
        icon: false,
        tooltip: true
      });
      addListToDropdown(dropDown, items);
      return dropDown;
    });

  }

  setCallFunc(callFunction: any) {
    this.callFunction = callFunction;
  }

  createDropDownButton(item, editor): ListDropdownItemDefinition {

    const dropDownItem: ListDropdownItemDefinition = {
      type: 'button',
      model: new Model({ label: item.label })

    }

    dropDownItem.model.on('execute', () => {
      // Change the model using the model writer.
      editor.model.change((writer) => {
        // Insert the text at the user's current position.
        editor.model.insertContent(writer.createText(item.value));
      });
    });

    return dropDownItem;
  }
}

using
 "ckeditor5": "^43.0.0",
   "ckeditor5-premium-features": "^43.0.0",
"@ckeditor/ckeditor5-angular": "^8.0.0",

### ✔️ Expected result

i want to show the dynamic dropdown in an angular application. 
I can import all espect Model from ckeditor5

import Model from '@ckeditor/ckeditor5-ui/src/model';
import { Plugin, ListDropdownItemDefinition, SplitButtonView, createDropdown, Collection, addListToDropdown } from "ckeditor5";

if i also import model there i got an error. 

### ❌ Actual result

_What is the actual result of the above steps?_
i got an error duplicate_module

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._
i think there is a problem with the model in this version
## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This was changed to prevent name collision, import `ViewModel` from `ckeditor5`. What is the context of the change on your side? Are you updating to a new version?

**Comment by bulli1979** [comment]
thanks a lot this was the solution.
