### ISSUE TITLE
Inserting elements before an image when image is first child 

### ISSUE THREAD

**Issue by Livijn** [ckeditor/ckeditor5#1703]
## Is this a bug report or feature request? (choose one)
🐞 Bug report

## 💻 Version of CKEditor
@ckeditor/ckeditor5-vue `^1.0.0-beta.1`

## 📋 Steps to reproduce
1. Launch the editor
2. Insert an image

## ✅ Expected result
Being able to insert text or any other element.

## ❎ Actual result
Nothing happens when clicking above the image. See this image for reference:
![image](https://user-images.githubusercontent.com/349311/56079183-27ef3380-5df1-11e9-9611-11cc787fc6d1.png)

## 📃 Other details that might be useful
I have extra padding-top 🤯

**Comment by scofalik** [comment]
Hi, thank you for your feedback. We are aware of this issue. We have a high priority on it but I cannot give you any ETA at this moment. Here is a related discussion: https://github.com/ckeditor/ckeditor5/issues/407

**Comment by scofalik** [comment]
I forgot the most important thing :). For now you can workaround it by pressing <kbd>Shift + Enter</kbd> when the image is selected. Also, <kbd>Enter</kbd> will insert a new paragraph after the image.

**Comment by Livijn** [comment]
> For now you can workaround it by pressing Shift + Enter when the image is selected. Also, Enter will insert a new paragraph after the image.

Good to know!

**Comment by EdifierCN** [comment]
通过 shift + enter 在图片前插入新的段落后，无法删除该空段落。
