### ISSUE TITLE
I use document-editor in Vue component. But it is shown like classic-editor.

### ISSUE THREAD

**Issue by HarrisonLee1998** [ckeditor/ckeditor5#1704]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 CKEditor5

CKEditor5+Vue2+Vue-cli3+element-UI
## 📋 Steps to reproduce

1.I install the dependencies about CKEditor5 by npm.
2.I have paste the code on your website into my vue-component.
3.Then I run my vue project. But is shown unexpectedly.

## ✅ Expected result
The style of document-editor like the demo on your website.

## ❎ Actual result
The style of  classic-editor.
## 📃 Other details that might be useful
The details in packages about CKEditor5:
    "@ckeditor/ckeditor5-basic-styles": "^11.1.0",
    "@ckeditor/ckeditor5-build-decoupled-document": "^12.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-essentials": "^11.0.1",
    "@ckeditor/ckeditor5-link": "^11.0.1",
    "@ckeditor/ckeditor5-paragraph": "^11.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^13.0.1",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.1",
The details in main.js about CKEditor5:
    import CKEditor from '@ckeditor/ckeditor5-vue'
    Vue.use(CKEditor)

The details in my component about CKEditor5:
    <template>
    <div id="app">
        <ckeditor :editor="editor" @ready="onReady"></ckeditor>
    </div>
   </template>

   <script>
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document'
export default {
    name: 'app',
    data() {
        return {
            editor: DecoupledEditor,
        };
    },
    methods: {
        onReady( editor )  {
            // Insert the toolbar before the editable area.
            editor.ui.getEditableElement().parentElement.insertBefore(
                editor.ui.view.toolbar.element,
                editor.ui.getEditableElement()
            );
        }
    },
}
</script>

<style lang="scss" scoped>
// .ck-reset{width: 600px!important;} /*可有可无，设置最外层div宽度即可*/
 .ck-editor__editable{min-height: 400px;}
</style>

###------
The above details are all my configuration about CKEditor5 in my projects. There is no other in any file.

**Comment by Mgsy** [comment]
Hello, you're using decoupled document build which doesn't include styles and you should create it on your own. [Here is our guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html) where you will find all the necessary information on how to make your editor look like the one on our website.

**Comment by QQchu** [comment]
So the VUE document mode cannot be displayed like  document example .must create it ,use  Here is our guide?

**Comment by QQchu** [comment]
> 可有可无，设置最外层div宽度即
兄弟，所以vue 的文档模式没办法做到和展示的例子一样吗？只能通过用div 这种模式？
