### ISSUE TITLE
In versions of vue 3, specifically 3.3.4, it presents conflicts with CkEditot 7.0.0

### ISSUE THREAD

**Issue by cristian807** [ckeditor/ckeditor5#17059]
## vue 3.3.4 and CkEditor 7.0.0

![image](https://github.com/user-attachments/assets/11c91534-10e1-414d-b93e-8d13c8506661)

### ✔️ Solution

To resolve this conflict I uploaded the version of vue to 3.5.3

![image](https://github.com/user-attachments/assets/c7f26d92-69f1-4824-90f5-7fc9f0b9d845)

**Comment by Witoso** [comment]
Our Vue package has a peer dependency for  `"vue": "^3.4.0"`. That's why you needed to upgrade, as this is the minimal required version.
