### ISSUE TITLE
Copy a List with styling is removing the styling of list elements

### ISSUE THREAD

**Issue by tsevillano** [ckeditor/ckeditor5#17065]
## 📝 Provide detailed reproduction steps (if any)

1. [Created this codepen with simple CKEditor](https://codepen.io/Tomas-Sevillano/pen/PorVyaJ)
2. [Copy the description of this job post](https://jobs.craftventures.com/companies/inspira-futures/jobs/40273803-lsat-tutor-juris#content)
3. Paste the description on the codePen

### ✔️ Expected result

All text and list item should have the same background and color. 

### ❌ Actual result

List item doesn't get the correct background and text color.

## 📃 Other details

* Browser: Google Chrome 127.0.6533.122
* OS: MacOs 14.05
* First affected CKEditor version: 37.0.0
* Installed CKEditor plugins: ClassicEditor,Essentials,Paragraph,Bold, Italic,List,Font

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lkszzajac** [comment]
The editor example in the linked Codepen does not include the General HTML Support plugin. After adding and configuring the plugin, the background and text color are uniform across the pasted text.

![image](https://github.com/user-attachments/assets/6ceb9917-3628-4354-948d-0e7ecc6d6858)

I am marking the issue as invalid, as it's an expected behavior of the editor without GHS.

**Comment by Witoso** [comment]
The editor just processes and inputs what's in the clipboard, and clipboard content from this website explicitly sets the style on `li`.

```html
<li style="color: rgb(63, 73, 90);>
```

If you would like to achieve some different behavior, you would need to overwrite/extend [the clipboard pipeline](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/clipboard.html#input-pipeline-events-overview) or write a [converter for this attribute](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/conversion/helpers/upcast.html#handling-attribute-values-via-a-callback) (for example, reapply the style to text inside `li`).


Full clipboard
```html
<meta charset='utf-8'><strong style="color: rgb(63, 73, 90); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, &quot;sans-serif&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Responsibilities<br><br></strong><ul style="color: rgb(63, 73, 90); margin: 0px auto 16px; font-size: 16px; line-height: 22.4px; padding: 0px 0px 0px 32px; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, &quot;sans-serif&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="color: rgb(63, 73, 90); margin: 0px auto 8px; font-size: 16px !important; line-height: 22.4px;">Tutor students one-on-one on all sections of the LSAT Exam</li><li style="color: rgb(63, 73, 90); margin: 0px auto 8px; font-size: 16px !important; line-height: 22.4px;">Tailor an LSAT curriculum to student's needs</li><li style="color: rgb(63, 73, 90); margin: 0px auto 8px; font-size: 16px !important; line-height: 22.4px;">Track and analyze student progress</li><li style="color: rgb(63, 73, 90); margin: 0px auto 8px; font-size: 16px !important; line-height: 22.4px;">Create and maintain project trackers to monitor student progress</li><li style="color: rgb(63, 73, 90); margin: 0px auto 8px; font-size: 16px !important; line-height: 22.4px;">Keep students' families up to date on progress</li><li style="color: rgb(63, 73, 90); margin: 0px auto 16px; font-size: 16px !important; line-height: 22.4px;">Tutor during after-school hours, including afternoons, evenings, and weekends<br></li></ul>
```
