### ISSUE TITLE
Scrolling Malfunction in Some Plugins When Left Block Button is Activated

### ISSUE THREAD

**Issue by w-beom** [ckeditor/ckeditor5#17067]
## 📝 Provide detailed reproduction steps (if any)
When the block button on the left is activated, scrolling does not work properly in some plugins.

### ❌ Actual result

_What is the actual result of the above steps?_

![Untitled video - Clipchamp로 제작](https://github.com/user-attachments/assets/2311e3e1-45f3-4d9d-8559-71b2abd99b83)

**Comment by Witoso** [comment]
Thanks for the report, could you provide the details regarding the browser and OS?

**Comment by w-beom** [comment]
browser : chrome
OS : windows11

**Comment by Mati365** [comment]
I managed to reproduce it on Chrome 129. I'll take a look.
