### ISSUE TITLE
Pasting a large table from Excel causes whole page to scroll away from editor

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor5#17079]
## 📝 Provide detailed reproduction steps (if any)

1. Copied a simple table with lots of rows (200) from Excel (Version 2406, Build 17726.20206)
2. Navigated to CKEditor, making sure to scroll down the page so that the top of the page isn't visible.  The editor is completely visible.
3. Pasted the content into CKEditor
4. My browser is scrolled to the top of the page.  CKEditor is no longer visible.

### ✔️ Expected result

Do not scroll to the top of the page when pasting in a table.

### ❌ Actual result

Browser scrolls to the top of the page.

### ❓ Possible solution

NA

## 📃 Other details

NOTE: This can be reproduced on the CKEditor 5 demo page here:
https://ckeditor.com/productivity-pack/paste-from-office-enhanced-demo/

* Browser: Edge 128, Chrome 128, Firefox 130
* OS: Windows 11
* First affected CKEditor version: Not sure, but occurs in 43.1.0
* Installed CKEditor plugins: See plugins used on demo page above.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mati365** [comment]
Reproducible on tables pasted from LibreOffice Calc.

**Comment by Mati365** [comment]
I proposed fix https://github.com/ckeditor/ckeditor5/pull/17314
