### ISSUE TITLE
CSP documentation is incomplete

### ISSUE THREAD

**Issue by jeandat** [ckeditor/ckeditor5#17074]
## 📝 Provide a description of requested docs changes

Regarding the CSP page: https://ckeditor.com/docs/ckeditor5/latest/getting-started/setup/csp.html

1. There is no paragraph for the "style-src" instruction
2. Also for "style-src", you say "The recommended CSP configuration" which is a bit funny since with it you cannot customise fonts or alignments according to your doc. If I understand correctly they are not part of standard out of the box features? Who uses a text editor without font or alignments buttons? Also in my tests, ckeditor is completely broken with a nonce and thus requires "unsafe-inline".

Am i missing something?

**Comment by Witoso** [comment]
> If I understand correctly they are not part of standard out of the box features? Who uses a text editor without font or alignments buttons?

Surprisingly, many users, those plugins are not enabled by default.

> There is no paragraph for the "style-src" instruction

Looks like we dropped it in a big v42.0.0 docs rewrite, I will readd it.

> Also in my tests, ckeditor is completely broken with a nonce and thus requires "unsafe-inline".

`nonce` is not supported yet, gathering +1s #16791.
