### ISSUE TITLE
How to set the editor height?

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1708]
No, it's not a DUP 😄

First of all, we have [a great self-answered question on SO]( https://stackoverflow.com/questions/46559354/how-to-set-the-height-of-ckeditor-5-classic-editor?noredirect=1&lq=1) which is plain wrong

```
.ck-editor__editable {
    min-height: 400px;
}
```

Why? Because image caption, comment editors and others have the `ck-editor__editable` class too and the styling breaks there, see https://github.com/ckeditor/ckeditor5-angular/issues/92.

The second issue here is that this answer supposes to solve only the Classic Editor case.

Note that it would be useful to have a simple selector that will work for all editor types.

I've talked to @dkonopka and he suggested the `.ck.ck-editor__editable[role='textbox']`. IMO the `.ck.ck-content` would be simpler but I don't know if it works in all cases. OTH we could have also the `.ck-editor__editable:not(.ck-editor__nested-editable)` but that approach is less verbose.

After we agree about the correct selector we should change some SO answers, GH answers and docs:

- https://stackoverflow.com/questions/52485000/how-to-set-ckeditor-5-height
- https://stackoverflow.com/questions/46559354/how-to-set-the-height-of-ckeditor-5-classic-editor
- https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html
- https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#styling

And possibly more.

cc @oleq @dkonopka @Reinmar

**Comment by oleq** [comment]
What about

```css
.ck-editor__editable:not(.ck-editor__nested-editable) { 
    min-height: 400px;
}
```
? 😁

**Comment by ma2ciek** [comment]
> What about
> .ck-editor__editable:not(.ck-editor__nested-editable) { 
    min-height: 400px;
}

I posted it also above :)

**Comment by dkonopka** [comment]
Your solution still will affect comment reply.

I don't know how, but I see in the our collaboration-samples there is no `__nested-editable` for comment reply:

![Screenshot 2019-04-16 at 11 43 08](https://user-images.githubusercontent.com/10219857/56199288-e3f06e80-603c-11e9-810e-f90c3b624a78.png)

**Comment by ma2ciek** [comment]
> (maybe it's a bug?)

It is not a nested editable so it seems fine.

**Comment by Reinmar** [comment]
Shouldn't we recommend using `ck-editor__editable_inline`? All editables created with `InlineEditableUIView` will have that class.

**Comment by oleq** [comment]
> Shouldn't we recommend using `ck-editor__editable_inline`? All editables created with `InlineEditableUIView` will have that class.

That makes sense. Or at least, as long as `InlineEditableUIView` is the only editable in our family.

**Comment by oleq** [comment]
I edited answers on SO and updated the guides.

**Comment by dkonopka** [comment]
Hmm.. are you sure that `.ck-editor__editable_inline` is a correct solution?

```css
.ck-editor__editable_inline {
  min-height: 200px;
}
```

Using this fix in any editor build with comments breaks reply container (which is editable):

![Screenshot 2019-04-18 at 12 25 32](https://user-images.githubusercontent.com/10219857/56354848-1634d400-61d5-11e9-81d2-c1198d21700c.png)

**Comment by oleq** [comment]
Letters is an integration, like any other. We will never come up with a solution that fixes The Editor (what is The Editor here BTW?) and does not affect Other Editors. People will need to narrow (prefix) the selector to target specific editors in their apps and this is quite natural. `.ck-editor__editable_inline` shows them the direction.

**Comment by dkonopka** [comment]
Just to let you know, it's not a Letters integration, just simple classic build with comments plugin - see https://ckeditor.com/collaboration/comments/demo/ :)

**Comment by oleq** [comment]
`.ck-editor .ck-editor__editable_inline` will not work with Inline and Balloon editors. There's no `.ck-editor` wrapper in their DOM structure.

**Comment by arif3258** [comment]
Setting the height through css works great. But how do I set the height if it is not known before hand? 

Meaning, consider a such scenario where the editor's height needs to adjusted according to the viewport lets say. So the desired height needs to be calculated in the script. Is there any way to set the height from the script?

afaik it was pretty simple with CKEditor 4. Cannot seem to work this out with CKEditor 5.

**Comment by Reinmar** [comment]
Depending on which element you want to style (may differ between elements). But, assuming that you want to change the height of the editable element it will look like this:

```js
editor.editing.view.change( writer => {
    writer.setStyle( 'height', '200px', editor.editing.view.document.getRoot() );
} );
```

So, the style needs to be changed via the view writer because the editable element's attributes are controlled by the editor's editing engine.

**Comment by arif3258** [comment]
> Depending on which element you want to style (may differ between elements). But, assuming that you want to change the height of the editable element it will look like this:
> 
> ```js
> editor.editing.view.change( writer => {
>     writer.setStyle( 'height', '200px', editor.editing.view.document.getRoot() );
> } );
> ```
> 
> This works with all types of editors.
> 
> So, the style needs to be changed via the view writer because the editable element's attributes are controlled by the editor's editing engine.

Thanks a lot. This works great!

**Comment by spirobel** [comment]
my editor is part of a resizeable floating box that also differs depending on screensize. it should fill out the remaining space in this box. Is there a way to do this in css, or do I need to calculate the height of the siblings in javascript everytime the box resizes and then use the remainder?  The editor i am replacing  was a textarea with height: 100% and overflow:hidden.

**Comment by oleq** [comment]
@spirobel It sounds like a use-case for [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex).

**Comment by spirobel** [comment]
> @spirobel It sounds like a use-case for [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex).

thanks for your answer! I did it with javascript now, because I am not really a CSS expert. Maybe I will try again later this is a really ugly solution at the moment. I will post a link to the repo when its done. Maybe someone can benefit as well.

**Comment by mohd-aidi** [comment]
look at all other simple editor where have height configurable. but why this amazing ckeditor dont have this easy cofnguration? lol

**Comment by pikulinpw** [comment]
For those who've been looking for a solution to dynamically adjust the height of CKEditor 5 and add resize capabilities, I'm excited to share a new plugin I've developed: https://github.com/pikulinpw/ckeditor5-resizableheight

**Key Features**:
- Dynamically adjust the height of the CKEditor instance.
- Option to resize the editor, providing a more flexible editing environment.
- Set specific height options or allow the plugin to determine the height based on content.
- Seamless integration with CKEditor 5.

It's now available on npm and easy to integrate with your existing CKEditor setup. Check out the README for installation and usage instructions.

Feedback, bug reports, and contributions are welcome. Let's make our CKEditor experience even better!

**Comment by Witoso** [comment]
Thank you @pikulinpw for sharing  your work! :blush:

**Comment by pikulinpw** [comment]
> Thank you @pikulinpw for sharing  your work! 😊

Thank you too, I hope my plugin will help and solve the problem, if there are any problems with the plugin or something in it will be missing, write and I will finalize it

**Comment by Saiuke** [comment]
> my editor is part of a resizeable floating box that also differs depending on screensize. it should fill out the remaining space in this box. Is there a way to do this in css, or do I need to calculate the height of the siblings in javascript everytime the box resizes and then use the remainder?

Here you go @spirobel, with this, you can make sure that the editor will grow to fill whatever vertical space is available.

```css
.ck.ck-reset.ck-editor.ck-rounded-corners {
    height: 100%;
    display: flex;
    flex-direction: column;

    .ck-editor__main {
      flex-grow: 1;
      display: flex;

      .ck-editor__editable_inline {
        flex-grow: 1;
      }
    }
  }
```

**Comment by pip-timer** [comment]
+1



Take stock of this explanation
