### ISSUE TITLE
Reverting back to flat dropdown menus (not nested)

### ISSUE THREAD

**Issue by mkerollos** [ckeditor/ckeditor5#17082]
The change introduced by https://github.com/ckeditor/ckeditor5/pull/16766 appears to have changed how the menus appear in the aiAssistant such that groups are all nested. How do I revert back to a flat list?

**Comment by FilipTokarski** [comment]
Hello @mkerollos , thanks for reaching out! This repository is used mainly for the open source part of the CKEditor 5 ecosystem. If you are a licensed customer and have any questions about the premium features, we highly encourage to [reach out to our support team](https://ckeditor.com/contact/). This way we will be able to provide you all required assistance quicker and  more effectively.
