### ISSUE TITLE
Building comment and change tracking adapters

### ISSUE THREAD

**Issue by tehkyle** [ckeditor/ckeditor5#17081]
## 📝 Ask a question

I am working on building comment and change tracking adapters with our DB as a backend and am a little stumped on how I am supposed to handle adding a comment to a suggestion and the documentation is very light on the subject.

I have the comments adapter configured and working per the [docs](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html) which follows the flow of creating a comment thread object containing a list of comment objects, adding removing comments to that list until the whole thread is unlinked, resolved, or deleted.

When implementing the change tracking adapter based on [this](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html) I noticed when adding a comment to a suggestion it fires both 'addComment' from CommentsIntegration as well as updateSuggestion with 'hasComments: true'. The CommentData object from addComment has a 'threadId' that appears to match the existing SuggestionData 'id'. Is SuggestionData supposed to also behave like a CommentThreadData? Or should addComment create a new CommentThread in the database with an id that matches the Suggestion? What is the intended integration flow here? 

If this information is available in the documentation I apologize and would love a link, but I was unable to find any clear details on the interaction between TrackChanges and Comments besides "It is also recommended to use the track changes plugin together with the comments plugin" and "Track changes use the comments plugin to allow discussion in suggestions" on the [Track Changes docs](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html). Additionally the sample integrations don't describe the intended behavior of a database integration, simply returning empty or mostly empty promises. Are CommentData objects supposed to store independant of CommentThreads? I don't see any comment collections on the SuggestionData model, nor is there a comment adapter event to get comments, only comment threads.

**Comment by FilipTokarski** [comment]
Hello @tehkyle, thanks for reaching out! This repository is used mainly for the open source part of the CKEditor 5 ecosystem. If you are a licensed customer and have any questions about the premium features, we highly encourage to [reach out to our support team](https://ckeditor.com/contact/). This way we will be able to provide you all required assistance quicker and  more effectively.
