### ISSUE TITLE
The tab key should leave the editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1709]
The <kbd>Tab</kbd> key should leave the editor.

Currently, the <kbd>Tab</kbd> key cycles through nested editables. This is native behaviour implemented by browsers and it doesn't make much sense. The user will not understand that when he/she is in some place in the text, the <kbd>Tab</kbd> key will move them to the next editable element, which may be far from their current context. Plus, to make editor integrate well with forms and other multi-input apps, the <kbd>Tab</kbd> key should allow leaving the editor and moving forward to the next input. 

However, as @mlewand pointed out (f2f :P), if the editor is a central place of the application, we need to allow the application to decide what to do when the user presses this key.

Related issues (some may need to be resolved together with this):

* https://github.com/ckeditor/ckeditor5-table/issues/183 (Implement a custom navigation through tables)
* https://github.com/ckeditor/ckeditor5-widget/issues/84 (Implement keyboard navigation in widgets (focusing nested editables and cycling))
* https://github.com/ckeditor/ckeditor5-widget/issues/83 (Keyboard navigation in content around widgets)
* https://github.com/ckeditor/ckeditor5/issues/1197 (Enabling tab to insert some characters/indent stuff/etc)

**Comment by panta82** [comment]
Is there some hack or plugin that can be implemented now, to help ease the accessibility pains?

Eg. a way to leave the editor focus on a key press?

**Comment by godai78** [comment]
Wasn't this covered with recent changes where the `Tab` navigates between focusable fields?

**Comment by Witoso** [comment]
Yep, done it [v41.3.0](https://github.com/ckeditor/ckeditor5/releases/tag/v41.3.0) via https://github.com/ckeditor/ckeditor5/issues/15506.
