### ISSUE TITLE
[Track changes] - How to show changes in the li element

### ISSUE THREAD

**Issue by felipe-issa-zebra** [ckeditor/ckeditor5#17091]
When track  changes feature is on, it is possible to mark the 'li' (list item) object as removed as well, so it also has the formatting?

Example, I have this simple object:

![image](https://github.com/user-attachments/assets/940fdd22-c855-4a67-b737-143236b513ba)

If I select the entire 'line 2' and press backspace, the changed behavior appears this way:

![image](https://github.com/user-attachments/assets/ff45bad0-d367-4694-83e1-3aa21f26f05c)

Checking the html, I can see the deleted class was added to the span, not to the li element:

`<li><span class="ck-list-bogus-paragraph"><span class="ck-suggestion-marker ck-suggestion-marker-deletion" data-suggestion="e3d413a8fe1e4401d9398ea66396d6d90" data-author-id="user-1">line 2</span></span></li>`

Is there any way I can customize to make the class to be added to the 'li' instead? I want to customize it using css to display it with removed colors if the entire line is removed, but as it doesn't have any added class I see no way of changing it.

**Comment by Witoso** [comment]
Hi, thanks for reaching out! This repository is used mainly for the open-source part of the CKEditor 5 ecosystem. If you are a licensed customer and have any questions about the premium features, we highly encourage to [reach out to our support team](https://ckeditor.com/contact/). This way we will be able to provide you all required assistance quicker and more effectively.

Thanks!
