### ISSUE TITLE
AttributeCommand is only as Type exported

### ISSUE THREAD

**Issue by ultraxf** [ckeditor/ckeditor5#17105]
## 📝 Ask a question

Hi, we are currently customizing in ckeditor5 and we want to use AttributeCommand in our own plugin. We noticed, there is not possible to use a AttributeCommand, because this is only exported as Type.

Is there any reason for that? Can you provide this as normal export? 
Or is there another way to do the trick?

Thx :)

**Comment by Witoso** [comment]
Hey! Yes, it was overlooked in the Typescript migration, we will export it in the next release.

**Comment by ultraxf** [comment]
Thx for the reply :)

**Comment by Witoso** [comment]
Let's keep it open, we will close when it's added.
