### ISSUE TITLE
Balloon _enableBalloonActivators not working in 43.0.0

### ISSUE THREAD

**Issue by weasteam** [ckeditor/ckeditor5#17107]
## 📝 Provide detailed reproduction steps (if any)

I've developed a custom plugin that displays a balloon when clicked. The functionality works as expected in versions 42.0.0 and earlier, but it has stopped working in version 43.0.0.

```
	init() {
		...
		// Enable the balloon activators.
		this._enableBalloonActivators();
		...
	}

	_enableBalloonActivators() {
		const editor = this.editor;
		const view = editor.editing.view;
		const viewDocument = editor.editing.view.document;

		view.addObserver( ClickObserver );
	
		this.listenTo(viewDocument, 'click', () => {
			this._showUI();
		});
	}
```

### ✔️ Expected result

The Balloon should display when clicked the element.

### ❌ Actual result

The Balloon only shows in the version 42.0.0 and earlier, not working in 43.0.0

**Comment by Mati365** [comment]
@weasteam Hi! :wave:  Can you prepare a small project on any REPL (like StackBlitz) that reproduces this issue? Before doing that - please make sure that balloon is being pinned to a visible element (without `display: none` style). It was modified in recent versions and might be causing issue. Previously, it was possible to pin the balloon to an invisible element.

**Comment by felixranesberger** [comment]
I'm facing a very similar issue. 
I found out that when I used the [abbreviation example](https://github.com/ckeditor/ckeditor5-tutorials-examples/tree/main/abbreviation-plugin/part-3) provide by CKEditor it also doesn't work. 

My plugins that worked AFAIK in v41 now don't open up balloons, if the selected text that is used for attaching the balloon is not a `<span>` tag.

**Comment by Mati365** [comment]
@felixranesberger I tested the example above, and it works fine (besides CSS that can be improved). I'm selecting text content in `p` and `h2` elements. 

https://github.com/user-attachments/assets/670ba391-a175-47c2-b594-21a2ef71d86d

I'm tested it on Chrome 129 and Firefox 130.  Which version of CKEditor are you using?

**Comment by Witoso** [comment]
This was fixed in https://github.com/ckeditor/ckeditor5/releases/tag/v43.1.0, please update, and let us know if it works.

**Comment by weasteam** [comment]
Thank you for fixing the bug.
