### ISSUE TITLE
ButtonView css

### ISSUE THREAD

**Issue by maxkarkowski** [ckeditor/ckeditor5#17111]
## 📝 Ask a question

Why has the ButtonView not the css cursor: pointer as a default? Or do i have to write a css class to give it the pointer cursor myself?

**Comment by Witoso** [comment]
[There's a long history of `pointer` on buttons](https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default), [W3C User Interface guidelines](https://www.w3.org/TR/CSS21/ui.html#propdef-cursor) says: “The cursor is a pointer that indicates a link”.

I assume we are not opinionated here, and user browser's defaults. If you want to add it, add a class or target `ck-button` (remember about `ck-disabled` class).
