### ISSUE TITLE
Review license headers at the end of it24

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1712]
We changed license headers in this iteration in all files. However, if someone created some file before that change in a branch and this branch was merged after that, there may be an outdated header used there.

**Comment by pomek** [comment]
Let's close this ticket one day before code freeze. I have a script that takes care of all those files.

**Comment by mlewand** [comment]
Two files were not adjusted:

* https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/249d7b2eaeacbbf9d4679ccf954382094aaabb94/src/lib/marked/renderer.js
* https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/249d7b2eaeacbbf9d4679ccf954382094aaabb94/src/lib/to-markdown/converters.js

In addition to that we should also update license section in the README.md 's.

Currently it looks like following: 

```md
## License

Licensed under the terms of [GNU General Public License Version 2 or later](http://www.gnu.org/licenses/gpl.html). For full details about the license, please check the `LICENSE.md` file.
```

While it should also include the link.

**Comment by pomek** [comment]
```diff
-[...] For full details about the license, please check the `LICENSE.md` file.
+[...] For full details about the license, please check the `LICENSE.md` file or [https://ckeditor.com/legal/ckeditor-oss-license](https://ckeditor.com/legal/ckeditor-oss-license).
```

Is it fine?

**Comment by pomek** [comment]
> Two files were not adjusted:
> 
> * https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/249d7b2eaeacbbf9d4679ccf954382094aaabb94/src/lib/marked/renderer.js
> * https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/249d7b2eaeacbbf9d4679ccf954382094aaabb94/src/lib/to-markdown/converters.js

Fixed in https://github.com/ckeditor/ckeditor5-markdown-gfm/commit/12e8d716112399ac89386a12cd8e883aa190d9b4.

**Comment by mlewand** [comment]
> Is it fine?

Yea, looks good to me.

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/58535483-69477100-81ee-11e9-8457-0b23c289674b.png)

:tada:

**Comment by pomek** [comment]
All READMEs have been changed.

**Comment by mlewand** [comment]
OK, looks like we're good to go.
