### ISSUE TITLE
[Edge, Safari] ckeditor5-editor-* CI jobs fail on 15th test

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1715]
https://travis-ci.org/ckeditor/ckeditor5-editor-inline/jobs/521399249

![image](https://user-images.githubusercontent.com/156149/56342190-96e4d780-61b7-11e9-98a0-21dbc682c332.png)

My guess will be the memory leak tests make that browser unresponsive. I'd switch them off on Edge because its engine is dead anyway.

**Comment by Reinmar** [comment]
Those tests should be skipped when `window.gc` is not present:

```js
function skipIfNoGarbageCollector() {
	before( function() {
		if ( !window.gc ) {
			this.skip();
		}
	} );
}

```

But maybe this object is available on Edge? :| Or I'm mistaken that this is about that test.

**Comment by Reinmar** [comment]
One more job: https://travis-ci.org/ckeditor/ckeditor5-editor-balloon/jobs/521399230

Here, both Safari and Edge failed:

![image](https://user-images.githubusercontent.com/156149/56342488-6fdad580-61b8-11e9-92dc-6c1d3bad06a2.png)

I've just checked that `this.skip()` is either not called or it doesn't make the test abort from being executed (and just skips the results). We need to make sure those tests are not executed at all.

**Comment by pomek** [comment]
It is not about the GC. This test is invalid and breaks everything:

```js
it( 'initializes with config.initialData', () => {
	return InlineEditor.create( editorElement, {
		initialData: '<p>Hello world!</p>',
		plugins: [ Paragraph ]
	} ).then( editor => {
		expect( editor.getData() ).to.equal( '<p>Hello world!</p>' );

		editor.destroy();
	} );
} );
```

**Comment by pomek** [comment]
It should be:

```js
it( 'initializes with config.initialData', () => {
	const editorElement = document.createElement( 'div' );
	document.body.appendChild( editorElement );

	return InlineEditor.create( editorElement, {
		initialData: '<p>Hello world!</p>',
		plugins: [ Paragraph ]
	} ).then( editor => {
		expect( editor.getData() ).to.equal( '<p>Hello world!</p>' );

		editor.destroy();
		editorElement.remove();
	} );
} );
```

**Comment by pomek** [comment]
I assume that the editor does not know what to do. We passed `initialData` and we have HTML code as initial data in `editorElement`.

https://github.com/ckeditor/ckeditor5-editor-inline/blob/1f47051035b38fe049719fa062c75523d1a466c5/tests/inlineeditor.js#L33-L34

**Comment by pomek** [comment]
Because we removed BrowserStack from our CI (https://github.com/ckeditor/ckeditor5/issues/1742#event-2410171871), could we agree that this ticket is no longer valid?

**Comment by pomek** [comment]
After removing BS, all tests pass. I am closing the ticket.
