### ISSUE TITLE
Using ckeditor in Dialog

### ISSUE THREAD

**Issue by thiagoreri** [ckeditor/ckeditor5#17165]
## 📝 Provide detailed reproduction steps (if any)

1. When I use ckeditor within a dialog, the link shortcut doesn't work very well

![image](https://github.com/user-attachments/assets/8be64c93-65a3-4146-8be2-8b5bfbef27f9)

The dialog box appears hidden

**Comment by OxManny-Dev** [comment]
Add a custom CSS and update the variable they created for the z-index.

something like this 

`
:root {
  --ck-z-default: 800; 
}
`

**Comment by thiagoreri** [comment]
OK, now it's at the front, but when I click to type the text, the focus goes to the textarea as if the input was unavailable.

![image](https://github.com/user-attachments/assets/2d48875b-2f09-4edf-9d98-2917d9b1c7ac)

**Comment by OxManny-Dev** [comment]
Which library are you using? If it's material-ui, add a prop called "disableEnforceFocus" and set it to true.

**Comment by OxManny-Dev** [comment]
Looks like there's a directive you can pass called "allow-focus-outside".
Docs says it here 
https://quasar.dev/vue-components/dialog

**Comment by thiagoreri** [comment]
Perfect, thanks

**Comment by thiagoreri** [comment]
Perfect, thanks
