### ISSUE TITLE
Unable to convert model elements from <ul>/<li>

### ISSUE THREAD

**Issue by jegeay** [ckeditor/ckeditor5#1716]
[Issue_Demo.zip](https://github.com/ckeditor/ckeditor5/files/3093247/Issue_Demo.zip)
🐞 Bug report

## 💻 Version of CKEditor
ckeditor5@12.1.0

## 📋 Steps to reproduce

Cf attached zip file :
 - Folder "Issue_demo_without" contains a plugin that works fine.
It converts model elements simpleBoxList and simpleBoxListItem from/to view elements `{name: 'div', classes: 'simple-box-list'}` and `{name: 'div', classes: 'simple-box-list-item'} `
- Folder "Issue_demo_with" contains a plugin that shows the issue.
The only difference, comparing to the previous folder, is to replace `<div>` view elements by `<ul>` and `<li>`. That is, converting model elements simpleBoxList and simpleBoxListItem from/to view elements `{name: 'ul', classes: 'simple-box-list'}` and `{name: 'li', classes: 'simple-box-list-item'} `

1. Open ./Issue_demo_without/index.html
Check that the `<div>` elements of the index.html are correctly converted into the model (as in the expected result).
2. Open ./Issue_demo_with/index.html
Check that the `<ul>` and `<li>` elements of the index.html are not converted into the model (as in the actual result).

## ✅ Expected result
```
<simpleBox>
  <simpleBoxTitle>
    "Box title"
  </simpleBoxTitle>
  <simpleBoxList>
    <simpleBoxListItem>
      "It should contain lists"
    </simpleBoxListItem>
    <simpleBoxListItem>
      "and list items."
    </simpleBoxListItem>
  </simpleBoxList>
</simpleBox>
```
## ❎ Actual result
```
<simpleBox>
  <simpleBoxTitle>
    "Box title"
  </simpleBoxTitle>
  <simpleBoxList>
  </simpleBoxList>
</simpleBox>
```
## 📃 Other details that might be useful
[Issue_Demo.zip](https://github.com/ckeditor/ckeditor5/files/3093247/Issue_Demo.zip)

**Comment by Mgsy** [comment]
@scofalik, could you take a look at this one?

**Comment by jegeay** [comment]
I found the cause of the problem. It is due to using the List plugin.
So, it is not really a bug but rather a misuse of the framework.

Maybe, the documentation could be improved in order to explain for each plugin, which view elements and wich model elements are handled. So interactions between plugins could be better managed.

What is your point of view about this ?

**Comment by Mgsy** [comment]
I'm sorry for the late response, somehow we missed it. I'm glad that you managed to solve your issue. Thank you for your suggestion about the documentation, we'd consider it.
