### ISSUE TITLE
Add multiple attends to run package test suite

### ISSUE THREAD

**Issue by Mati365** [ckeditor/ckeditor5#17169]
## 📝 Provide a description of the improvement

Our test suite tends to randomly crash on certain packages without any reason. Most of these crashes are random disconnections from Karma server which result in `Disconnected reconnect failed before timeout of 2000ms (ping timeout)` error. 

It's crashing, mostly in our commercial repo. There might be few reasons why it's crashing:

1. Maybe due to async nature of the commercial tests. They are using async stuff and maybe some of the socket connections are not properly destroyed, causing tests to timeout. It'd be explanation why merging this branch: https://github.com/cksource/ckeditor5-commercial/commit/29d1c94cf5afd3d40cd9676d0f7bf853aacde953 caused more instability than it was before. Debugging it may be time-consuming. 
2. Maybe some breaking changes were introduced in latest Chrome 129 upgrade that does not play well with Karma. There was at least one issue with our testing suite after upgrade: https://github.com/ckeditor/ckeditor5/commit/cf5533f4e54bdea484d213393f1e933e7da0a6c6 so some changes in protocol were made. 

### Proposal workaround

Let's add multiple attends to our `scripts/ci/check-unit-tests-for-package.js` calls in testing suite. In other words, let's rewrite these CI bash scripts:

```bash
#!/bin/bash -eo pipefail

node scripts/ci/check-unit-tests-for-package.js --package-name ckeditor5-ai --check-coverage
````

into something like that (I did not test it):

```bash
#!/bin/bash -eo pipefail

COMMAND="node scripts/ci/check-unit-tests-for-package.js --package-name ckeditor5-ai --check-coverage"

for attempt in {1..3}; do
    echo "Attempt $attempt..."
    $COMMAND && exit 0
done

echo "Command failed after 3 attempts."
exit 1
````

It's not a great solution, but good enough at this moment. 

---

:question: Maybe CircleCI supports it out of the box and might be done at job level?

**Comment by pomek** [comment]
> ❓ Maybe CircleCI supports it out of the box and might be done at job level?

> Note: CircleCI does not support automatic retries of failed steps, jobs & workflows. If you are looking for that feature, please vote for it [here](https://ideas.circleci.com/cloud-feature-requests/p/support-automatic-retry-of-failed-builds).

https://support.circleci.com/hc/en-us/articles/360043188514-How-to-Retry-a-Failed-Step-with-when-Attribute

**Comment by pomek** [comment]
A function to update: https://github.com/ckeditor/ckeditor5/blob/0b53cf1f85b85582922d58f221ecf5e1d1f653d5/scripts/ci/check-unit-tests-for-package.js#L47-L68
