### ISSUE TITLE
[Docs] Image used in the docs is too small

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1717]
The image we use is only 800px wide hence the white margins on its side.

![image](https://user-images.githubusercontent.com/156149/56349772-8c333e00-61c9-11e9-8915-dfed75ec3799.png)

We should:

* use a wider image there (1000px will do)
* ask ourselves why we don't use `display:table` for `figure.image`?

cc @oleq @dkonopka

**Comment by dkonopka** [comment]
Could you add links where we can find this issue (I've checked `/examples/` and there everything is ok)?

**Comment by oleq** [comment]
Let's use a bigger version of an image then.
