### ISSUE TITLE
Table scope attributes missing

### ISSUE THREAD

**Issue by proudnerds-typo3** [ckeditor/ckeditor5#17185]
## 📝 Provide detailed reproduction steps (if any)

1. Create a table with a couple of rows and columns
2. Define a Header row and/or column row with the pop-up tool
3. Save and view page or inspect the source in the RTE

This behaviour can also be reproduced with: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html

### ✔️ Expected result

The th's in the table row defined as Header row should have an attribute scope with 'row' or 'col' 

<table>
    <thead>
        <tr>
            <th scope="row">Test 1</th>
            <th scope="col">Test 2</th>
            <th scope="col">Test 3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Test 4</th>
            <td data-title="Test1">Test 6</td>
            <td data-title="Test2">Test 7</td>
        </tr>
        <tr>
            <th scope="row">Test5</th>
            <td data-title="Test3">Test 9</td>
            <td data-title="Test1">Test 10</td>
        </tr>
    </tbody>
</table>

### ❌ Actual result

The scope attributes are missing

### ❓ Possible solution

Reinstate the option that was still working in ckeditor4. See: https://ckeditor.com/docs/ckeditor4/latest/examples/table.html

## 📃 Other details

The scope attribute is a WCAG requirement for tables:
https://www.w3.org/WAI/WCAG22/Techniques/html/H63.html

* Browser: not relevant
* OS: not relevant
* First affected CKEditor version: ckeditor5
* Installed CKEditor plugins: Processing / Base / Plugins

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
DUP: #3175
