### ISSUE TITLE
The table in the migration guide is cropped

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1718]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html#configuration-options-compatibility-table

![image](https://user-images.githubusercontent.com/1099479/56352009-9f94d800-61ce-11e9-977f-760421b7db25.png)

cc @msamsel @Reinmar

**Comment by Reinmar** [comment]
I guess this needs to be fixed in the styles. So cc @dkonopka.

**Comment by dkonopka** [comment]
Code blocks inside table break it, we are missing here `white-space: normal`.

![Screenshot 2019-04-29 at 11 23 01](https://user-images.githubusercontent.com/10219857/56887199-3dab5c80-6a71-11e9-928e-68bb05c57966.png)

**Comment by mlewand** [comment]
@dkonopka the problem with changing white-space for code element is that it will change its formatting:

![code snippet with no indentation](https://user-images.githubusercontent.com/5353898/58082901-34b53300-7bb8-11e9-8324-616098577f42.png)

mby scroll overflow? 🤔 just like we do for other wider code listings?

![Overflow visible in the CKE5 Content Security Policy guide](https://user-images.githubusercontent.com/5353898/58083213-db013880-7bb8-11e9-90c3-c82df4589ff7.png)

**Comment by dkonopka** [comment]
@mlewand It's not so easy to set `overflow-x: scroll`, because then we need to set some `max-width` of this element which stretch `<table>`.

That's why I decided to go with `white-space: normal` even if it changes code formatting.

**Comment by mlewand** [comment]
Why does its width exceed the parent constraints in the first place? 🤔 I think this is the issue that contributes to the problem.

I'm afraid that `table-layout: fixed` is a no-go option. Just imagine it will apply fixed, equal widths to each single table in our docs. The default layout strategy seems to make more sense than that.

If we can't come up with a reasonable reusable solution, I'm ok with simply hand correcting the code listing in this particular doc as a workaround.

**Comment by dkonopka** [comment]
As I can see, [the table here is a plain html](https://raw.githubusercontent.com/ckeditor/ckeditor5/master/docs/builds/guides/migrate.md), so we can easily add extra CSS class (or inline style) and it will be working only for this table. I know it's not the best idea, but it could work. WDYT?

**Comment by mlewand** [comment]
Oh, in this case it's totally fine 👍 If it's for this table only, and just please fine-tune the first cell width, so that it has same width as now (with the default strategy).

The more width in second cell the less lines it will contain 🙂
