### ISSUE TITLE
How to validate data?

### ISSUE THREAD

**Issue by Agnostion** [ckeditor/ckeditor5#17188]
How can I check on the backend side whether the received content matches the editor settings?

For example, with indents. If I set a step of 40px, then how can I check on the backend side in the right way that the user received exactly 40px in indentation? Is there some way out of the box so that I can create an editor on the back side with specific settings, load content into it and check it for compliance with the settings?

If this is not the case, then I will be glad to receive any advice or examples from your experience, thank you.

Thank you for your editor and the time spent on it, it is very valuable!

**Comment by Witoso** [comment]
> How can I check on the backend side whether the received content matches the editor settings? For example, with indents. If I set a step of 40px, then how can I check on the backend side in the right way that the user received exactly 40px in indentation?

Could explain the why? It's cannot grasp the use case here. What do you mean by: _the user received exactly 40px in indentation?_

**Comment by Agnostion** [comment]
> > How can I check on the backend side whether the received content matches the editor settings? For example, with indents. If I set a step of 40px, then how can I check on the backend side in the right way that the user received exactly 40px in indentation?
> 
> Could explain the why? It's cannot grasp the use case here. What do you mean by: _the user received exactly 40px in indentation?_

So that one user cannot submit any styles, so that the content is within the appropriate frames, and so that other users cannot receive content outside of these frames.
After all, if I configured the editor to indent in increments of 40px, then the user can still manually send a POST request to the server and keep the indentation at, say, 100px

**Comment by Witoso** [comment]
That's an interesting case. Thanks for sharing. Currently, the editor, as you mentioned, clears unrecognized HTML elements as well as attributes it was not configured to handle. It's a bit trickier with specific values, but you could update the converters to only accept specific values in some cases, and fallback to others.

 If you want to run the editor on the server, some browser environment will be needed like Puppeteer. At the same time, editor will not report compliance in a true/false manner, and you would need to implement some sort of diffing mechanism.

**Comment by Agnostion** [comment]
Thanks for the advice. My project simply does not use any converters; all text with html markup is written into the database as data directly from the editor, so I asked myself the question of validation. I will think about how to solve this.

Thank you again for your time, it is greatly appreciated. And thanks for this editor, great work :)
