### ISSUE TITLE
The `checkVersionAvailability()` in `ckeditor5-dev-release-tools` does not work on Windows

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#17191]
The `checkVersionAvailability()` in `ckeditor5-dev-release-tools` does not work on Windows, because its arguments are wrapped inside `'` by `shellEscape()`. Example command that is generated by this util looks like:
```
npm show '@ckeditor/ckeditor5-upload'@'43.0.0' version
```
Then, it is passed down to `shelljs` as:
```
npm show "'@ckeditor/ckeditor5-upload'@'43.0.0'" version
```
which throws an error:
```
npm error code ENOENT
npm error syscall open
npm error path D:\Projekty\ckeditor5\ckeditor\ckeditor5-upload'@'43.0.0'\package.json
npm error errno -4058
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'D:\Projekty\ckeditor5\ckeditor\ckeditor5-upload'@'43.0.0'\package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
```

See https://github.com/ckeditor/ckeditor5-dev/blob/0e35f4972c7c8dfdef8055f9b0dbc0cca46003d1/packages/ckeditor5-dev-release-tools/lib/utils/checkversionavailability.js#L22

It works well on non-Windows environments.

#### Proposed solution

To make all npm-related commands cross-platform compatible, we could use either [`npm`](https://www.npmjs.com/package/npm) or [`pacote`](https://www.npmjs.com/package/pacote) packages to fetch the required data from npm registry instead of calling shell command.

**Comment by pomek** [comment]
> To make all npm-related commands
Could we modify only commands that use the registry directly? I mean, `npm whoami` could remain untouched.

**Comment by psmyrek** [comment]
Sure, it should work. Probably only commands with escaped arguments cause problems on Windows.
