### ISSUE TITLE
`npx webpack` with `ckeditor5-dev-utils` 44.0.0 fails to build CKEditor with `Error [ERR_REQUIRE_ESM]: require() of ES Module`

### ISSUE THREAD

**Issue by wyattoday** [ckeditor/ckeditor5#17203]
## 📝 Provide detailed reproduction steps (if any)

1. Run `npm update --dd`
2. Then run `npx webpack`
3. Watch it fail with...

```
[webpack-cli] Failed to load 'C:\location-to\ckeditor5-custom\webpack.config.js' config
[webpack-cli] Error [ERR_REQUIRE_ESM]: require() of ES Module C:\location-to\ckeditor5-custom\node_modules\@ckeditor\ckeditor5-dev-utils\lib\index.js from C:\location-to\ckeditor5-custom\webpack.config.js not supported.
Instead change the require of index.js in C:\location-to\ckeditor5-custom\webpack.config.js to a dynamic import() which is available in all CommonJS modules.
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at Object.<anonymous> (C:\location-to\ckeditor5-custom\webpack.config.js:12:29) {
  code: 'ERR_REQUIRE_ESM'
}
```

The line in question that it's angry about (in our webpack.config.js):

```
const { bundler, styles } = require( '@ckeditor/ckeditor5-dev-utils' );
```

### ✔️ Expected result

A successful build.

### ❌ Actual result

A failure (see above).

### ❓ Possible solution

Rolling back `ckeditor5-dev-utils` to 43.0.0 (`npm install @ckeditor/ckeditor5-dev-utils@43.0.0`) fixes the bug. So it was introduced in the last few weeks between 43.0.0 and 44.0.0.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
According to https://github.com/ckeditor/ckeditor5-dev/releases/tag/v44.0.0, all `ckeditor5-dev-*` packages are now ESM. Please update your configuration to use an `import` statement or an `import()` function.

**Comment by wyattoday** [comment]
I see. The documentation hasn't been updated: https://ckeditor.com/docs/ckeditor5/latest/getting-started/legacy/advanced/alternative-setups/integrating-from-source-webpack.html

**Comment by pomek** [comment]
The `@latest` npm tag for the `@ckeditor/ckeditor5-dev-utils` package (and others as well) now points to v43.

![Image](https://github.com/user-attachments/assets/72e5db63-13c3-4a8b-9a31-e0b5c025deea)

**Comment by pomek** [comment]
Docs are updated, too. I think, we did what we could to produce a working output after reading these guides.
