### ISSUE TITLE
Docs issue report from "features/collaboration/comments/comments-outside-editor.html"

### ISSUE THREAD

**Issue by ryanj-openquire** [ckeditor/ckeditor5#17204]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-outside-editor.html

### Project version

43.1.1

### Is there something missing in the guide? What is it?

When using comments outside of the Editor, how would one render archived comments? The CommentsArchiveUI plugin does not support Context mode. Are we supposed to grab the archived comments from the Annotations#collection and render them ourselves? Who handles reopening and removing - are we supposed to provide that ourselves or will the AnnotationsUIs handle that? 

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by Witoso** [comment]
Hi! As the question is about a premium feature, please use [our support channel](https://ckeditor.com/contact/). This way it will be looked at faster by our support them. Thanks!
