### ISSUE TITLE
Preserve font properties when applied to all the document

### ISSUE THREAD

**Issue by rvasseur31** [ckeditor/ckeditor5#17211]
## 📝 Provide detailed reproduction steps (if any)

1. Add text with one break line between each paragraph
2. Select all document and apply a font property like font size, font family or bold
3. Place the cursor on an empty line
4. Write text

### ✔️ Expected result

The text should have the font properties that we applied to the all document

### ❌ Actual result

The text have the defaults properties. It might be liked to https://github.com/ckeditor/ckeditor5/issues/17152

https://github.com/user-attachments/assets/211a99da-9d86-4068-a5d0-a276dd0351da

## 📃 Other details

* Browser: Brave or Chrome
* OS: MacOS Sonoma (Not tested on windows)
* First affected CKEditor version: 43.1.0 (Not tested on previous versions)
* Installed CKEditor plugins: Alignment, AutoLink, Autoformat, Bold, Essentials, FontBackgroundColor, FontColor, FontFamily, FontSize, GeneralHtmlSupport, Heading, Italic, Link, List, Paragraph, RemoveFormat, SelectAll, Strikethrough, Underline, Undo

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
I think there's a dup somewhere, but I couldn't find it. For the editor, the default is the stylesheets. Removal of the whole text is back to the defaults. We don't have a notion of changing dynamically the default font while interacting with fonts plugins (as it works in GDoc for example).

**Comment by Witoso** [comment]
Found it! DUP: https://github.com/ckeditor/ckeditor5/issues/10517
