### ISSUE TITLE
Enter, Shift+Enter, and Link toolbar do not work within Bootstrap Modal

### ISSUE THREAD

**Issue by nschroder26** [ckeditor/ckeditor5#17218]
## 📝 Provide detailed reproduction steps (if any)

1. Initialize CKEditor
2. Click button to show Bootstrap modal
3. Click in editor and press enter
4. Click "Link" toolbar button

### ✔️ Expected result

When pressing enter, expect cursor to move to next line
When clicking Link toolbar button, expect to see input for URL

### ❌ Actual result

Cursor does not move to next line
There is not an input for a link

### ❓ Possible solution

There seems to be some conflict with Bootstrap modals, this exact same setup works as expected for inline editors. I've modified to use the exact setup found [here](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/quick-start.html#installing-ckeditor-5-from-cdn), and added the Link plugin. I've also attempted solutions such as [this](https://stackoverflow.com/questions/41121577/ckeditor-link-input-not-working-in-modal) with no luck

## 📃 Other details

* Browser: FF/IE/Chrome
* OS: macOS
* First affected CKEditor version: 43.2.0
* Installed CKEditor plugins: Essentials, Bold, Italic, Font, Paragraph, Link

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey! There's a [Bootstrap entry](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/css.html#bootstrap-modals) in the docs, explaining the need to change the focus behavior.

**Comment by nschroder26** [comment]
Not sure how I missed that section of the docs, sorry and thank you!
