### ISSUE TITLE
Docs issue report from "features/images/images-inserting.html"

### ISSUE THREAD

**Issue by j2s** [ckeditor/ckeditor5#17227]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/images/images-inserting.html

### Project version

43.2.0

### Is there something missing in the guide? What is it?

Hi
I have seen a demo of someone pasting text & image from a .docx document into ckeditor5. This was under Drupal.
The image is captured and saved in Drupal's files directory under ./inline-images.
That functionality (which does not work for me!) is a very common use-case so if not supported it would be worth mentioning it.

### Is there anything else you would like to add?

.

### User agent

Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0

**Comment by Witoso** [comment]
Hi, I've just tested it, and it works correctly in our demos. Please reach out to the Drupal community to consult them regarding potential issues.
