### ISSUE TITLE
Tidak Dapat Mengimpor Terjemahan Bahasa Indonesia untuk CKEditor

### ISSUE THREAD

**Issue by FajarSant** [ckeditor/ckeditor5#17238]
### Reproduction steps

1. npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic
2. import translations from 'ckeditor5/translations/id.js';
3. npm error 404 Not Found - GET https://registry.npmjs.org/@ckeditor%2fckeditor5-translations - Not found

### Current behavior

Cannot find module '@ckeditor/ckeditor5-translations/id.js' or its corresponding type declarations.
Property 'language' does not exist on type 'ClassicEditor'.****

### Definition of Done

- _Please leave this field for us. We will fill it during the backlog refinement session._

### User agent

versi nodejs 20  versi npm 10

**Comment by filipsobol** [comment]
Hi @FajarSant. It looks like you are trying to install `@ckeditor/ckeditor5-translations/id.js`, but such a package doesn't exist.

The package you need to install is `ckeditor5`. Then, you can import translations from the `ckeditor5/translations/<LANGUAGE_CODE>.js`.
