### ISSUE TITLE
How to make a ckeditor.js build which includes all basic and essential plugins along with MathType and ChemType

### ISSUE THREAD

**Issue by GAWADERP** [ckeditor/ckeditor5#17233]
## 📝 Ask a question
I want to build and download the "ckeditor.js" file to use in my java maven project.  I am using jsp as front end technology and initializing the ckeditor from java script code. 
Please help me to make a build which includes all essential and basic plugins along with MathType and ChemType plugins. 
**Note**:- I found a build with MathType and ChemType, but in that build, **Underline** plugin is **missing**. So that build is no use for me.

I want below plugins in my build: -
Autoformat,
BlockQuote,
Bold,
CKFinder,
CKFinderUploadAdapter,
CloudServices,
CodeBlock,
Essentials,
Heading,
Image,
ImageCaption,
ImageStyle,
ImageToolbar,
ImageUpload,
Indent,
Italic,
Link,
List,
MathType,
ChemType,
MediaEmbed,
Paragraph,
PasteFromOffice,
Table,
TableToolbar,
TextTransformation,
Underline

**Comment by filipsobol** [comment]
Hey @GAWADERP 👋 

Do you prefer a build that is optimized (smaller size, but requires installing Node and npm) or ready-to-use (heavier, but doesn't require any tooling)?

**Comment by GAWADERP** [comment]
I am seeking a "ready-to-use" CKEditor.js file that includes all the plugins mentioned above, which I can directly reference as a native JavaScript file(not CDN) in my project.

**Comment by filipsobol** [comment]
If you would rather not use CDN, then save these files locally in your project. Their behavior won't change.
