### ISSUE TITLE
Error on remove image link / ready event is fired more than once

### ISSUE THREAD

**Issue by felipeissa** [ckeditor/ckeditor5#17252]
When removing a link from image, the following error is being displayed on console:

```
polyfills.js:1 Uncaught CKEditorError: Cannot read properties of undefined (reading '_removeAttribute')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of undefined (reading '_removeAttribute')
    at Aa.removeAttribute (main.js:1:711864)
    at cE.<anonymous> (main.js:1:1298952)
    at cE.fire (main.js:1:536129)
    at cE._testAndFire (main.js:1:795292)
    at cE._convertAttribute (main.js:1:793831)
    at cE.convertChanges (main.js:1:791864)
    at main.js:1:819706
    at qS.change (main.js:1:762482)
    at listenTo.priority (main.js:1:819671)
    at v0.fire (main.js:1:536129)
```

Reproduction steps:

1. Add image to ck editor
2. Click on image and add a link to it (any link will do, eg: 'https://google.com'
3. Click to 'unlink'

The error above will be displayed into console. Also, everytime you try to remove the link the event 'ready' is fired again (on angular app).

Issue can be seen on the feature reach editor:  https://ckeditor.com/ckeditor-5/demo/feature-rich/ (just can't validate it it calls 'ready' more than once also.

### ✔️ Expected result

Link should be removed and no error should be displayed on console. Ready event should be fired only once, not every link removal.

### ❌ Actual result

Error is displayed on console, ready event is fired for every link removal.

## 📃 Other details

* Browser: Google Chrome 129.0.6668.90 
* OS: Windows 11
* First affected CKEditor version: / Installed CKEditor plugins:

"@ckeditor/ckeditor5-editor-classic": "~43.2.0"
"@ckeditor/ckeditor5-image": "~43.2.0"
"@ckeditor/ckeditor5-link": "~43.2.0"

Editor config:

{
      link: {
        addTargetToExternalLinks: true
      }
};

**Comment by Witoso** [comment]
I cannot reproduce the error on our demo page, could you share a recording? I'm not sure if I understand `ready` event. Could you elaborate how you listen to it?

**Comment by Witoso** [comment]
Thank you, I confirmed it throws on the demo, I could replicate it [in the docs](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html). We will investigate.
