### ISSUE TITLE
Enter key press with out text don't set any paragraph <p> html tag

### ISSUE THREAD

**Issue by xidhramirez** [ckeditor/ckeditor5#17253]
Here is the evidence:
![Image](https://github.com/user-attachments/assets/df438083-6468-4e49-9363-35ce81139bef)
 and the console log
![Image](https://github.com/user-attachments/assets/37b4224c-757e-47a9-8234-4cb2ca5dc1a0)
print
![Image](https://github.com/user-attachments/assets/3d33a481-f406-4949-8894-6876f7fe2a2f)

**Comment by Witoso** [comment]
Hi! Please use the `{ trim: 'none' }` option in [`getData`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-getData).
