### ISSUE TITLE
How to Persist Style and Custom Attributes on Figure Tag?

### ISSUE THREAD

**Issue by YadBro** [ckeditor/ckeditor5#17259]
I have an HTML string like this:

```
<figure class="image" style="transform:rotate(-180deg);" data-angle="-180"....
```
If I put this string in CKEditor data, the style and custom attribute are removed.

**Comment by Reinmar** [comment]
Check out the GHS plugin: https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html
