### ISSUE TITLE
Failed to bundle using Rollup v2.79.1

### ISSUE THREAD

**Issue by aramhovsepyan** [ckeditor/ckeditor5#17257]
Many ckeditor plugins in JSDeliver contain the following instead of the plugin itself
`/**
 * Failed to bundle using Rollup v2.79.1: failed to resolve an internal import.
 * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
 */

 throw new Error('Failed to bundle using Rollup v2.79.1: failed to resolve an internal import. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');`

Thanks.

**Comment by filipsobol** [comment]
Hi @aramhovsepyan. Can you provide a link to some examples?

**Comment by aramhovsepyan** [comment]
Hi Filip,
Thanks for the prompt response. Sure, here is the link: https://cdn.jsdelivr.net/npm/@ckeditor/ckeditor5-page-break@43.2.0/+esm
Sorry if the bug is unrelated to CKEditor.
Regards,
Aram.

**Comment by filipsobol** [comment]
The file you are trying to access is for the **legacy** installation method, which requires a custom webpack setup. This installation method is still supported, but on the deprecation path.

In v42.0.0 we introduced a new installation methods (NIM), which work with any bundler and without any CKEditor-specific requirements. Please refer to the [NIM migration guide](https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/migration-to-new-installation-methods.html) for more information.

You can access the browser build, which includes the core and all open-source packages [here](https://cdn.jsdelivr.net/npm/ckeditor5@43.2.0/dist/browser/ckeditor5.js). If you prefer to use individual plugins, you can do so by adding the `dist/index.js` to the URL ([`page-break` example](https://cdn.jsdelivr.net/npm/@ckeditor/ckeditor5-page-break@43.2.0/dist/index.js)). However, using individual plugins from CDN is more tricky to setup and requires using an [importmap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap).
