### ISSUE TITLE
CKEditor 5 Builder page, i select Vanilla JS, it use module but this does not support mobile

### ISSUE THREAD

**Issue by jamesliao0814** [ckeditor/ckeditor5#17262]
## 📝 Ask a question

CKEditor 5 Builder page, i select Vanilla JS, it use module but this does not support mobile.
So
Can you provide mobile-friendly script?

**Comment by Witoso** [comment]
Could you elaborate what you mean by mobile-friendly? Which mobile does it not support?

**Comment by jamesliao0814** [comment]
I've found a solution.
script type=module
Need to be packaged with webpack
