### ISSUE TITLE
Pasted plain text with line breaks, can't add a list to each line

### ISSUE THREAD

**Issue by qqabcv520** [ckeditor/ckeditor5#1727]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

12.0.7

## 📋 Steps to reproduce

1. Copy multiple lines of text
2. Paste
3. List command

## ✅ Expected result
Add a list to each line
## ❎ Actual result
Only added to the first line
## 📃 Other details that might be useful
Inconsistent with Microsoft Word

**Comment by Reinmar** [comment]
CKEditor 4 also allows turning lines between soft breaks into list items. However, it comes at a cost. This content:

```html
<p>foo<br>bar<br>bom</p>
```

Will become this after applying the list to a selection placed in "bar":

```html
<p>foo</p>
<ul><li>bar</li></ul>
<p>bom</p>
```

And after you remove the list, you'll get:

```html
<p>foo</p>
<p>bar</p>
<p>bom</p>
```

So a different content than the one you started with. But, OTOH, it's the same if the middle line was a heading, so perhaps it's fine.

cc @oleq @scofalik WDYT?

**Comment by qqabcv520** [comment]
So how should I use `<p>foo</p>` replace `foo<br>` when I paste plain text wraps?

**Comment by Reinmar** [comment]
> So how should I use `<p>foo</p>` replace `foo<br>` when I paste plain text wraps?

I'm sorry but I don't understand your question.

---

I checked that Google Docs behaves like CKEditor 5 – the entire block is converted into list item.

And, MS Word behaves like CKEditor 5 as well. Which means that only CKEditor 4 behaves differently here.

cc @mlewand

**Comment by qqabcv520** [comment]
CKEditor: Only added to the first line.

![GIF2](https://user-images.githubusercontent.com/26498115/56951849-6ca5f900-6b6b-11e9-9942-652c1c391fd9.gif)

Google Docs: Add a list to each line.

![GIF3](https://user-images.githubusercontent.com/26498115/56952062-ef2eb880-6b6b-11e9-99c9-29137de13bac.gif)

So how should I Add a list to each line?

**Comment by qqabcv520** [comment]
@Reinmar

**Comment by scofalik** [comment]
Maybe when pasting from Notepad, `<br>`s are created instead of paragraphs for each line?

**Comment by Mgsy** [comment]
>Google Docs: Add a list to each line.

That's because in this case, Google Docs creates two separate paragraphs after paste. If you try to create a paragraph with a soft brake and apply a list, you'll notice it behaves like CKEditor 5.

![bug_cke5](https://user-images.githubusercontent.com/20988892/56953078-153c6480-6b3c-11e9-986b-22531393b01f.gif)

>Maybe when pasting from Notepad, `<br>`s are created instead of paragraphs for each line?

You're right, CKEditor 5 doesn't create a new paragraph for each line copied from Notepad.

**Comment by Reinmar** [comment]
So, it's a question whether single line breaks in plain text should create new paragraphs or `<br>`s. I think we had a discussion about that but I can't find it now. 

We should open a new ticket with a better description and close this one. How line breaks are pasted will affect more features (e.g. headings, text alignment, image insertion). I'd be fine with changing the current algorithm and I think it wasn't criticised for the first time

**Comment by qqabcv520** [comment]
I think the paste behavior should be the same as the main editor, whether a single line break in plain text should create a new paragraph when pasted, or configurable.

**Comment by Reinmar** [comment]
> I think the paste behavior should be the same as the main editor

What do you mean by "main editor"?

**Comment by qqabcv520** [comment]
Should be Mainstream editor, For example: MS Word, Google Doc.
