### ISSUE TITLE
CKEditor 12.1 Font Pluggin

### ISSUE THREAD

**Issue by zackhalil** [ckeditor/ckeditor5#1728]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

12.1.0

## 📋 Steps to reproduce

1.Download latest 12.1.0 from https://ckeditor.com/ckeditor-5/download/
2. Select Document build
3. select zip

## ✅ Expected result

tried latest build expecting it to have new font color feature as described in https://ckeditor.com/blog/CKEditor-5-v12.1.0-with-mentions-font-color-and-remove-formatting-released/

I added 'fontColor', 'fontBackgroundColor' to toolbar but it does show new plugin?

## ❎ Actual result

no new button appears

**Comment by Mgsy** [comment]
Font color and font background color plugins are not included in our builds. If you want to add those plugins, please take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build).

**Comment by zackhalil** [comment]
Thanks...

Excuse my ignorance... I'm using document build but under 
https://github.com/ckeditor/ I can only see classic editor..... do I use 
this the classic editor still to build the document build?

Cheers

**Comment by Mgsy** [comment]
[Here](https://github.com/ckeditor/ckeditor5-build-decoupled-document) you'll find the document build repository.

**Comment by zackhalil** [comment]
Thanks! got it working.... Wasnt as hard as it looked...

Cheers
