### ISSUE TITLE
Adding custom button on the toolbar

### ISSUE THREAD

**Issue by rexkenley** [ckeditor/ckeditor5#17307]
## 📝 Ask a question

I want to add a "save button" on the toolbar that will call a custom js function. Is that possible? I currently have a separate save button which is not ideal design.

![Image](https://github.com/user-attachments/assets/0eefea1a-c07e-4dc3-ae9f-954969d0735a)

**Comment by FilipTokarski** [comment]
You can add a plugin which will register custom button on the toolbar - https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/creating-simple-plugin-timestamp.html.

**Comment by rexkenley** [comment]
Thanks
