### ISSUE TITLE
Link and unlink icons are missing in the `icons` object

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#17304]
## 📝 Provide detailed reproduction steps (if any)

Our `icons` object is missing the `link` and `unlink` icons- https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-core/src/index.ts#L123.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by brianjhanson** [comment]
I'm seeing the same issue in `44.0.0`. It looks like the [exports were added in #17306 ](https://github.com/ckeditor/ckeditor5/pull/17306) but then [reverted in #17363](https://github.com/ckeditor/ckeditor5/pull/17363). 

I seem to be able to access the SVG via `import linkIcon from '@ckeditor/ckeditor5-link/theme/icons/link.svg';` but admittedly that seems like a bad idea. 

Is there some other workaround to be able to use `icons.link`?

**Comment by Witoso** [comment]
Copying the files to your project. The change causes issues in some setups. We will clean up the icons situation early next year probably.
