### ISSUE TITLE
Remove ckeditor5-integrations-common's package.json's resolution wrap-ansi@7.0.0

### ISSUE THREAD

**Issue by baurelien-la** [ckeditor/ckeditor5#17305]
## 📝 Provide detailed reproduction steps (if any)

1. Install a new ckeditor5 build on an Angular 18 project, with the new provided wrapper **@ckeditor/ckeditor5-angular@9.0.0**

### ❌ Actual result

_What is the actual result of the above steps?_

When building the project we get this error :

```
Unknown error: Error [ERR_REQUIRE_ESM]: require() of ES Module /{projectpath}/node_modules/wrap-ansi/index.js from /{projectpath}/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /{projectpath}/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
error Command failed with exit code 127.
```
This forces us to use the same workaround used in @ckeditor/ckeditor5-integrations-common :

In package.json : 
```
resolutions: {
  "wrap-ansi": "7.0.0",
}
```

### ✔️ Expected result

_What is the expected result of the above steps?_

We should be able to build our Angular application without dependencies errors caused by this workaround. 

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

A quick study showed us that this workaround is here since a while, so issue might be specific to new Angular 17-18 version. 

We did not have the issue before migrating from Angular 15 to 18 as our  ckeditor5@4.1.0.0 build and angular wrapper 8.0.0 were working fine. 

Error began with Angular 18 migration through a warning pushing us to update our ckeditor5 build and angular wrapper to at least 42.0. 

After updating to 43.2.0, the build error appeared.

The workaround works fine but we want to keep a clean project package. And we would prefer using the last wrap-ansi@9.0.0 recommended version.

## 📃 Other details

* Framework : Angular 18 - Node 20
* First affected CKEditor version: 4.3.2.0
* Specific dependency issue seems to begin on @ckeditor/ckeditor5-integrations-common

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mati365** [comment]
@baurelien-la Hi! Thanks for you reporting the issue. I checked it locally, using this `package.json` file:

```json
{
  "name": "ckeditor5-angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@ckeditor/ckeditor5-angular": "^9.0.0",
    "ckeditor5": "^43.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.2.3",
    "@angular/cli": "^18.2.3",
    "@angular/compiler-cli": "^18.2.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.5.2"
  }
}
```

It looks like it works without any further problems. Can you prepare a small reproducible demo (for example on stack blitz) that reproduces such a problem?

**Comment by baurelien-la** [comment]
It will be hard to provide a small reproducible demo as our project is kinda big. We will see what we can do. 

Worse case, we will issue a new bug if we gather more informations.
