### ISSUE TITLE
Long URL Exceeding boundaries of box

### ISSUE THREAD

**Issue by ProfessorGram** [ckeditor/ckeditor5#17310]
What ckeditor 5 setting is required (and where) to prevent a long url from exceeding the boundaries of the forum post display box?

Please see https://ibb.co/wLkWkyH 

Thank you

g.
----

**Comment by Reinmar** [comment]
This is an issue with the content styles applied by that forum. Probably requires `break-word`. Not a problem with CKEditor itself which wraps such links:

![Image](https://github.com/user-attachments/assets/655f0fe7-a16f-4b98-8f24-c4ddb40c5eaf)

**Comment by ProfessorGram** [comment]
Hello there!

I think you may have missed a step.

This is a two-step solution, right?

Could you please provide

1.  A screenshot of where in the Administrative GUI back-end the command
"break-word" goes to accomplish

2.  A successful demonstration of the User front-end result.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
