### ISSUE TITLE
DataController#init and #ready are not fired

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1732]
They are documented but never fired. AFAIR, the data controller was supposed to fire similar events to the UI controller.

**Comment by Reinmar** [comment]
cc @pjasiun

**Comment by Reinmar** [comment]
There's even an example in https://ckeditor.com/docs/ckeditor5/latest/api/module_core_plugin-PluginInterface.html.

**Comment by pjasiun** [comment]
I just tested it and it works fine for me:

![Screenshot 2019-04-29 at 11 59 54](https://user-images.githubusercontent.com/1166967/56889966-53705000-6a78-11e9-87df-c5dc35cb8d2e.png)

(for both initialization with and without collaboration).

The event was introduced here: https://github.com/ckeditor/ckeditor5-engine/commit/46d924364f3be9a4039dfde8ba9f44ff4e7372f1#diff-b9d22c15cdbf4113c48fb4ca592546c9R110 and is fired correctly (note that it is fired only during data initialization).

When it comes to `DataController#init`: there is decorable method with such name, which works as an event too: https://github.com/ckeditor/ckeditor5-engine/blob/master/src/controller/datacontroller.js#L110. It also works fine.

**Comment by Reinmar** [comment]
Confirmed. No idea why I haven't seen them. Sorry.
