### ISSUE TITLE
CodeView for toolbar?

### ISSUE THREAD

**Issue by standfv** [ckeditor/ckeditor5#1734]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1. 
2.

## 📃 Other details that might be useful

CodeView for toolbar?

**Comment by Mgsy** [comment]
Hello, could you describe what this ticket is about? Please, provide some meaningful information, so we'll be able to answer it.

**Comment by martonx** [comment]
I think @standfv means ckeditor 5 miss source code editor plugin?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
