### ISSUE TITLE
Include underline in built packages

### ISSUE THREAD

**Issue by lspohn** [ckeditor/ckeditor5#1735]
🆕 Feature request
Hi,

I'd like to use Ckeditor 5 (most recent packages) in our web project based on Vue + Vuex + Typescript.

The standard build (with Inline Editor) works really great. However, I miss the underline option.

I thus followed the guide to build Ckeditor from source for Vue. I used the vue.config.js 1:1 and did not include any further editor plugins. However, it doesn't work, getting this runtime error:

> Cannot read property 'getAttribute' of null
>     at IconView._updateXMLContent (iconview.js?b512:122)
>     at IconView.render (iconview.js?b512:95)

I think the underline formatting is quite a basic one. Was there an important reason to exclude it from the built package? It might save me - and possibly many other users - a lot of headache from dealing with the custom build if you added it.

Thank you anyway for this great project.

Lucas

**Comment by Mgsy** [comment]
Hello, our builds contain a basic amount of plugins and it's up to a developer which plugins will be included to the custom build. Please, take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

The error you've experienced is related to loading SVG's. Could you share your `vue.config.js` code?

**Comment by lspohn** [comment]
Hi! That's why I ask to reconsider the underline plugin as basic :-)

I created a new vue.config.js file (I use Vue CLI but didn't need the config yet) and just copied the suggestion from https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html into that.
Interestingly, the error is the same if I remove the SVG loader part from the vue.config.js.

Thanks!

**Comment by Mgsy** [comment]
Thanks. Indeed, the editor throws an error after using the config from our documentation. Could you try to uncomment this part `svgRule.uses.clear();`, rebuild the app and check whether it solves the problem?

**Comment by lspohn** [comment]
Hi!

Thanks a lot for the suggestion. So this works:
`svgRule.uses.clear()`
`svgRule.use('raw-loader').loader('raw-loader')`

It doesn't work with
`config.module
      .rule( 'cke-svg' )
      .test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
      .use( 'raw-loader' )
      .loader( 'raw-loader' )`

Because then the other SVGs are not loaded. Is there any drawback of using raw loader for all svgs instead of the Vue cli standard?

**Comment by lspohn** [comment]
Hi,

I notices that my own svgs acutally didn't load correctly. I had to use:

```
const svgRule = config.module.rule('svg')
svgRule.uses.clear()
    svgRule
      .oneOf('cke-svg')
      .test(/ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/)
      .use('raw-loader')
      .loader('raw-loader')
      .end()
      .end()
      .oneOf('svg')
      .use('file-loader')
      .loader('file-loader')
      .options({
        name: 'img/[name].[hash:8].[ext]'
      })
```

The file loader configuration was just copied from the original configuration without the Ckeditor Webpack Mod. I used "vue inspect" to get the original config.
