### ISSUE TITLE
Lists do not respect current indent level

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor5#17356]
## 📝 Provide detailed reproduction steps (if any)

1. Indent a couple of times.
2. Insert a bulleted list and add some items.

### ✔️ Expected result
The bullets should be close to the text of the bullet.

### ❌ Actual result
The bullets are separated from the text by the current indent level.
![Image](https://github.com/user-attachments/assets/40d6f6e9-789b-4a96-be14-2663cecb5a81)

Indented lists also have some strange margin added to the bottom of list element.
 
Note: this was not an issue with CK 4.

### ❓ Possible solution
Have lists with indenting work as expected like they did in CK 4.

It looks like the editor is adding the margin-left to LI elements instead of the UL/OL elements. Because it is also placing paragraph elements in the LI elements, the stylesheet is adding a bottom margin to the all the list items.

## 📃 Other details
This can reproduced on the CKEditor demo page here:
[https://ckeditor.com/ckeditor-5/demo/feature-rich/](https://ckeditor.com/ckeditor-5/demo/feature-rich/)
* Browser: Edge 130, Chrome 131
* OS: Windows 11 Pro

* First affected CKEditor version: 43.1.0
* Installed CKEditor plugins: See demo page.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Thanks for reporting, marking as a dup of https://github.com/ckeditor/ckeditor5/issues/16742
