### ISSUE TITLE
Cannot find module '../theme/icons/unlink.svg'

### ISSUE THREAD

**Issue by NesTeRDGIT** [ckeditor/ckeditor5#17358]
After updating to version 43.3.0, when building the project, we get an error:
node_modules/@ckeditor/ckeditor5-link/src/index.d.ts:21:37 - error TS2307: Cannot find module '../theme/icons/link.svg' or its corresponding type declarations.

Cause: #17304

I think need to add files *.d.ts for *.svg files or remove exporting svg as module.

**Comment by Mgsy** [comment]
Hi @NesTeRDGIT! Thanks for reaching out. Could you please share more details about your project configuration and, ideally, share an example project with steps to reproduce the issue? Are you able to reproduce it with a build created by [Online builder](https://ckeditor.com/ckeditor-5/online-builder/)?

**Comment by NesTeRDGIT** [comment]
@Mgsy What project details would you like to know? 
Angular-18.
Typescript
dependencies {
"ckeditor5": "43.3.0",
 "ckeditor5-premium-features": "43.3.0"
}

This commit [commit](https://github.com/ckeditor/ckeditor5/pull/17306/files#diff-2bc6954a7390b2b049d0b53ee1c586cfe5cd49361e53eaff072a67fdc46038be) added export SVG files as modules typescript - this is error. 
Files SVG is not module. 
I don't know why this was done. But you can add *.d.ts files for *.svg files, for fix TS2307 error.
Example
link.svg.d.ts
--------------------------------
declare const content: string;
export default content;

**Comment by Witoso** [comment]
This is not reproducible on our side in a vanilla TS project: https://stackblitz.com/edit/vitejs-vite-7gibwb?file=index.html,src/style.css,src/main.ts,tsconfig.json&terminal=dev

We already export SVG icons in other places, AFAIK, there's augmentation added on our side already: https://github.com/ckeditor/ckeditor5/blob/25416abbf4446396e7d0ace47c962fd10230245a/typings/types.d.ts#L6

Could you share minimal repro for us to take a look?

**Comment by NesTeRDGIT** [comment]
@Witoso 
https://stackblitz.com/edit/stackblitz-starters-fim6xt?file=src%2Fapp%2Fapp.component.ts

**Comment by vivdesign** [comment]
Got the same issue with angular 16

**Comment by Witoso** [comment]
Issue solved with `43.3.1` release.
