### ISSUE TITLE
Create a `EmojiMentionIntegration` plugin

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#17379]
## 📝 Provide a description of the new feature

The goal is to allow for inserting emoji after typing `:`.

![Image](https://github.com/user-attachments/assets/fd95d92e-f2ea-4dad-b67b-c507c289a0c6)

In other words, let's use the Mention plugin as a base.

We can initially use the `emoji-picker-element-data` package as input data. We may change it at some point.

### Definition of Done

* _The name is temporary, and it's subject to change._
	* Confirm the name with @Witoso.
* After typing a colon, we should display a dropdown that allows for inserting emoji.
	* I would require a single character before reviewing the database.
* We need a manual test that allows the feature to be tested.
* We need automated tests for the new code.
* Feature branch and a pull request should target the `#epic/ck/17361` branch.

**Comment by Witoso** [comment]
My thoughts:
* this plugin is a part of `Emoji` plugin, I don't see the reason to split it to two separate plugins. Internally it can be split of course.
* If there's `Mention` config with `:` this plugin should not be enabled and warn to the console about the conflict.
* Have some sensible max, GH has 5, GDoc 15? We 10?

**Comment by przemyslaw-zan** [comment]
Closed via https://github.com/ckeditor/ckeditor5/pull/17523
