### ISSUE TITLE
IE 11 - Not able to add content/text below the previously added content

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1737]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

Both ckeditor 4/ckeditor 5

## 📋 Steps to reproduce

1. Add the attached content in ckeditor. The content is some container having some already formatted text.
2. The user not able to add anything below this container. Whenever user tries to put cursor, it moves inside this container. The same thing works fine on google chrome browser and the user can add text below this container.

## ✅ Expected result
It should work the same way on IE11 as it is working in Chrome.

[notes.txt](https://github.com/ckeditor/ckeditor5/files/3141455/notes.txt)

**Comment by mlewand** [comment]
CKEditor 5 is currently not suported on IE11. You'll find the official list at [CKEditor 5 browser compatibility](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/browser-compatibility.html) page.

**Comment by chetan-rflx** [comment]
But the same issue is there on ckeditor 4 version which is used by some of users. At this moment we cannot ask them to get upgraded to ckeditor 5.
Is there any chance it the issue can be fixed on ckeditor 4?
