### ISSUE TITLE
Pasting lists from word does not match word document.

### ISSUE THREAD

**Issue by NTTData-Anthony** [ckeditor/ckeditor5#17389]
## 📝 Provide detailed reproduction steps (if any)

1.  copy text from [wordlistpasteissue.docx](https://github.com/user-attachments/files/17622528/wordlistpasteissue.docx)

2. paste into ckeditor5

### ✔️ Expected result

all lists should show as is in word document. ![Image](https://github.com/user-attachments/assets/8021d179-97e4-41ab-9cde-dc9edff1d40e)

### ❌ Actual result

lists display incorrectly
![Image](https://github.com/user-attachments/assets/b0d2b556-f8ac-4b24-b73f-bb57b2e95ba8)

## 📃 Other details

* Browser: Chrome
* OS: Windows
* First affected CKEditor version: 
* Installed CKEditor plugins: see main.js file for config. [main_js.txt](https://github.com/user-attachments/files/17622569/main_js.txt)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Works correctly in [Paste from Office Enhanced](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html).
![Image](https://github.com/user-attachments/assets/afe8da8a-6817-4f54-8efa-75416ffb780e)

Most likely the clipboard and requires more complex processing that our PFOE plugin delivers.

**Comment by NTTData-Anthony** [comment]
Is there a list of supported features covered by standard vs enhanced paste from word? @Witoso
