### ISSUE TITLE
Change suggestion containing a new table with header column and cell split is not applied correctly when using `getDataWithAcceptedSuggestions()`

### ISSUE THREAD

**Issue by lkszzajac** [ckeditor/ckeditor5#17404]
## 📝 Provide detailed reproduction steps (if any)

1. Open an editor with `Table`, `TrackChanges` and `TrackChangesData` plugins (e.g. `ckeditor5/external/ckeditor5-commercial/packages/ckeditor5-collaboration/tests/manual/all-features-rtc.html`)
2. Enable Track Changes and perform these actions:
    1. Add a 5x5 table.
    2. Add a header column
    3. Split one of the cells in the header column
3. Extract data from the document using `editor.plugins.get("TrackChangesData").getDataWithAcceptedSuggestions()`  

### ✔️ Expected result

- extracted table markup has the same structure as in editor

### ❌ Actual result

- extracted table includes 4 additional columns at the end
- header row is applied

![Image](https://github.com/user-attachments/assets/eca066b2-0ae8-42c7-9544-a0896bd71d5c)

## 📃 Other details

* Browser: n/a
* OS: n/a
* First affected CKEditor version: 
* Installed CKEditor plugins:

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mmotyczynska** [comment]
The bug can be reproduced without using Track Changes.
1. Open the documentation for tables: https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables.html
2. Insert a 5x5 table.
3. Convert the first column to a **header column**.
4. **Horizontally** split one of the cells in the header column.
5. Set the current data using the Inspector or in the console: `editor.setData( editor.getData() )`

This results in the table expanding to an unintended size (9x6). Additionally, it then becomes impossible to undo any changes.
https://github.com/user-attachments/assets/4fab1855-5fbb-409f-8807-8cbacdc47cfb

**Comment by Greatowen42** [comment]
Please I need a Google console to publish my app.
I have a budget please 

WhatsApp me
+63966 470 0031 please

**Comment by Mati365** [comment]
Checked works fine after fix in https://github.com/ckeditor/ckeditor5/pull/17640.
