### ISSUE TITLE
CK Editor 5 - React : Append Image node to current cursor position

### ISSUE THREAD

**Issue by Buwaneka1993** [ckeditor/ckeditor5#1741]
## Is this a bug report or feature request? (choose one)
 Other

## 💻 Version of CKEditor

5

## 📃 Other details that might be useful
I want to append <Image> into current cursor position of my CKEditor component.
current cursor position can get using following 
` const insertPosition = editor.model.document.selection.getFirstPosition();`

I referred following doc, but couldn't find good example code for this 
[https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_utils_insertcontent.html](url)

**Comment by Mgsy** [comment]
Hello, please take a look at our example in [creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html#step-4-inserting-a-new-image). Does it solve your problem?

**Comment by Buwaneka1993** [comment]
Thank you . Its helpful
