### ISSUE TITLE
Absolute `font-size` doesn't scale on text resizing

### ISSUE THREAD

**Issue by mfranzke** [ckeditor/ckeditor5#17416]
The "powered by" text gets defined with an absolute `font-size` or in other words by a pixel value. This should be a relative value like all others as it doesn't scale (upwards) nicely on users setting bigger font-sizes in their environments for accessibility reasons.

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-ui/theme/globals/_poweredby.css#L38

**Comment by Greatowen42** [comment]
Please I need a Google console to publish my app.
I have a budget please 

WhatsApp me
+63966 470 0031 please
