### ISSUE TITLE
Browserstack integration breaks our CI

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1742]
## Is this a bug report or feature request? (choose one)

Other

## 📋 Steps to reproduce

Recently browserstack integration doesn't work great and causes our CI tests to fail rendering it unreliable.

~One example is https://travis-ci.org/ckeditor/ckeditor5-utils/builds/529690643~ (build was restarted later on, and is no longer broken)

Even though tests passes, there are plenty of errors reported.

**Comment by pomek** [comment]
- Did BS change anything on its side? (cc: @wwalc)
- Can it be related to Travis itself?
- Restarting the build usually helps but it does not seem to be a solution.

**Comment by pomek** [comment]
I increased BrowserStack limits (https://github.com/ckeditor/ckeditor5-dev/compare/master...t/ckeditor5/1742) and executed 10 builds:

1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530193037
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530195877
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530198261
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530199802
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530201883
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530204677
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530208272
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530212249
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/530214758
1. https://travis-ci.org/ckeditor/ckeditor5-ui/builds/522126220

Everything is green.

The problem that the ticket describes is not too often and unfortunately, it's hard to debug. I guess we had no luck. We can stay with new limits but if the problem will occur again, (TBH) I have no idea what we can do more.

**Comment by pomek** [comment]
As specified here – https://github.com/ckeditor/ckeditor5/issues/1778#issuecomment-496461206 – let's close this topic.

**Comment by mlewand** [comment]
Reopening this issue as #1778 was a dup of this issue.

**Comment by pomek** [comment]
Due to problems last time, we decided to disable integration with BrowserStack.
