### ISSUE TITLE
[Widget] Mouseover events

### ISSUE THREAD

**Issue by guillome2k** [ckeditor/ckeditor5#1744]
🆕 Feature request 
Onmouseover / onmouseout events for custom plugin (inline) widgets

💻 Version of CKEditor
12.10

## 📋 Steps to reproduce

1. Searched the manuals
2. Tried stuff like:
```modelObj.document.listenTo(editor.editing.view.document, "click", function() { console.log("cliock wi"); });

plugin.listenTo(editor.editing.view.document, "over", function(event, data) { console.log("on mouseenter"); });
plugin.listenTo(editor.editing.view.document, "mousemove", function(event, data) { console.log("on mousemove"); });
plugin.listenTo(editor.editing.view.document, "mouseover", function(event, data) { console.log("on mouseover"); });
plugin.listenTo(editor.editing.view.document, "enter", function(event, data) { console.log("on enter"); });
plugin.listenTo(editor.editing.view.document, "hover", function(event, data) { console.log("on hover"); });```

## ✅ Expected result
I like to add an onmouseover action to my custom inline widget plugin.

This code for onclick does work
plugin.listenTo(editor.editing.view.document, "click", function(event, data) {
	const target = data.target;
	const modelObj = getWidgetDom(target);

	if (!modelObj) { return; }
.. code
});

**Comment by Mgsy** [comment]
cc @jodator

**Comment by jodator** [comment]
There are no such [observer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_observer_observer-Observer.html) defined. Currently we use only [click](https://github.com/ckeditor/ckeditor5-engine/blob/9a40550a7425670264974edc9252f3dcf888ce2f/src/view/observer/clickobserver.js#L26) & [mousedown](https://github.com/ckeditor/ckeditor5-engine/blob/9a40550a7425670264974edc9252f3dcf888ce2f/src/view/observer/mouseobserver.js#L24) events.

You can add your own observers by extending the [DomEventObserver](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_observer_domeventobserver-DomEventObserver.html) and [add it to the view](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_view-View.html#function-addObserver).

**Comment by guillome2k** [comment]
Worked! Thank you!

**Comment by juanpasolano** [comment]
@guillome2k Would you mind sharing how you implemented this.
I've tried creating a `DomEventObserver` but it only fires once on mouseentering the document, I need it to trigger when entering different elements in the document.

```
class MouseEnterObserver extends DomEventObserver {
  get domEventType() {
    return 'mouseenter';
  }
  onDomEvent( domEvent ) {
    this.fire( 'mouseenter', domEvent );
  }
}
```

Thank you

**Comment by guillome2k** [comment]
```js
class MouseEnterObserver extends DomEventObserver {
	constructor( view ) {
		super( view );

		this.domEventType = 'mousemove';
	}

	onDomEvent( domEvent ) {
		this.fire( domEvent.type, domEvent );
	}
}
class MouseOutObserver extends DomEventObserver {
	constructor( view ) {
		super( view );

		this.domEventType = 'mouseout';
	}

	onDomEvent( domEvent ) {
		this.fire( domEvent.type, domEvent );
	}

..


editor.editing.view.addObserver(MouseEnterObserver);
		plugin.listenTo(editor.editing.view.document, "mousemove", function(event, data) {
			const target = data.target;
			const modelObj = getWidgetDom(target);

			if (!!modelObj) {
				... your code ...
}```
