### ISSUE TITLE
[Link UI] Accept/Cancel button icons alignment

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#17442]
This is from our current docs:

![Image](https://github.com/user-attachments/assets/b7f2f6ec-fbf8-432f-b4a9-211a3072f34f)

This is from the [Feature-rich demo](https://ckeditor.com/ckeditor-5/demo/feature-rich/):

![Image](https://github.com/user-attachments/assets/39cba8ab-3393-4ea3-937f-a61e73b6482b)

The docs version is the correct one.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Rel: https://github.com/cksource/ckeditor5-commercial/issues/6785

**Comment by pszczesniak** [comment]
Proposed solution: https://github.com/ckeditor/ckeditor5/issues/17449

**Comment by pszczesniak** [comment]
Fix was released: [ckeditor/ckeditor5-dev@v43.0.1 (release)](https://github.com/ckeditor/ckeditor5-dev/releases/tag/v43.0.1), the CSS files were built successfully.

The issue should not be present anymore.
