### ISSUE TITLE
CK Editor5  - insertContent of <video> tag 

### ISSUE THREAD

**Issue by Buwaneka1993** [ckeditor/ckeditor5#1748]
## Is this a bug report or feature request? (choose one)
 Other

## 💻 Version of CKEditor

5

## 📋 Steps to reproduce
` const sourceElement = writer.createElement('source', {
                    src: url,
                    type: mediaObj.mediaType
                });
                const videoElement = writer.createElement('video', { controls: true, width: 400 }
                );
                videoElement._children._nodes.push(sourceElement);
                editor.model.insertContent(videoElement, editor.model.document.selection);`

## ✅ Expected result
`<video width="400" controls>
  <source src="mov_bbb.mp4" type="video/mp4">
</video>`
## ❎ Actual result
Nothing will display

**Comment by Mgsy** [comment]
Hello, CKEditor 5 has a custom data model and accepts only elements and attributes allowed by the schema. If you want to insert `<video>` element to your editor, you have to write a plugin which enables it in the schema and provides a proper conversion. 

Please, take a look at our [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) documentation.

**Comment by Buwaneka1993** [comment]
@Mgsy  Can`t we solve this problem without creating a plugin?

**Comment by mlewand** [comment]
The only way to create new functionality is by adding plugins. Otherwise CKEditor does not know how to handle given entity and skips it.

**Comment by Buwaneka1993** [comment]
I tried it in this way, but its not worked.

`editor.model.schema.register('video', {
                    isLimit: true
                });
                editor.model.schema.register('source', {
                    allowIn: 'video',
                    isBlock: true
                });


                let element = editor.conversion.elementToElement({
                    model: 'video',
                    view: {
                        name: 'source',
                    }
                });
                const sourceElement = writer.createElement('source', {
                    src: url,
                    type: mediaObj.mediaType
                });
                const videoElement = writer.createElement('video', { controls: true, width: 400, height: 400 }
                );
                videoElement._children._nodes.push(sourceElement);
                editor.model.insertContent(videoElement, editor.model.document.selection);`
