### ISSUE TITLE
Where to signup or get notified for Core updates?

### ISSUE THREAD

**Issue by matbk49751** [ckeditor/ckeditor5#17505]
Where would I go to signup or get notified for Core updates?

**Comment by Witoso** [comment]
Depends on what you mean by updates and Core :)
1. Subscribe to releases on GitHub, each release has a detailed changelog.
2.  [Subscribe to our newsletter](https://ckeditor.com/#newsletter-signup) for the high-level release updates.

**Comment by matbk49751** [comment]
Hi @Witoso ! Thank you. This is what I needed.
