### ISSUE TITLE
[Docs] Duplicated npm package in the snippet on Vue.js integration page

### ISSUE THREAD

**Issue by lisavansteijn** [ckeditor/ckeditor5#1751]
While I was installing one of the needed npm packages for my vue ckeditor, I noticed that in the docs it says to install the following:

`npm install --save \`
`    @ckeditor/ckeditor5-editor-classic \`
`    @ckeditor/ckeditor5-essentials \`
`    @ckeditor/ckeditor5-basic-styles \`
`    @ckeditor/ckeditor5-basic-styles \`
`    @ckeditor/ckeditor5-link \`
`    @ckeditor/ckeditor5-paragraph`

Note that '@ckeditor/ckeditor5-basic-styles \' is in this list twice. This is a pretty easy one to miss when you're casually checking out the docs, but I figured since the docs are linked to here, I'd let you guys know 😉

Link: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source

**Comment by Mgsy** [comment]
Hi, thanks for pointing this out! The additional package should be removed from the snippet.
