### ISSUE TITLE
Support TypeScript v5.7+ in `ckeditor5-dev-build-tools`

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#17526]
## Provide a description of the task

TypeScript v5.7 has been released a few days ago with additional restrictions in JSON imports: https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#validated-json-imports-in---module-nodenext.

The goal is to make the `ckeditor5-dev-build-tools` package compatible with this TypeScript version. Right now `yarn run test` fails in this package:

```
FAIL  tests/build/build.test.ts > TypeScript declarations
Error:
ERROR: Error occurred when processing the file undefined.
[plugin typescript] src/input.ts (7:22): @rollup/plugin-typescript TS1543: Importing a JSON file into an ECMAScript module requires a 'type: "json"' import attribute when 'module' is set to 'NodeNext'.
7 import settings from './settings.json';
                       ~~~~~~~~~~~~~~~~~

 ❯ Module.build src/build.ts:249:9
    247|   }
    248|
    249|   throw new Error( removeWhitespace( message ) );
       |         ^
    250|  }
    251| }
 ❯ tests/build/build.test.ts:107:21
```

**Comment by pomek** [comment]
Verify if this syntax:

```
import myConfig from "./myConfig.json" with { type: "json" };
```

Is compatible with TS < 5.7. If so, let's proceed. Otherwise, we need to discuss what to do with the breaking change.

**Comment by pomek** [comment]
I checked if asserting an import works in TS 5.6, and it looks good. This change affects tests only.
