### ISSUE TITLE
Preserve empty inline elements

### ISSUE THREAD

**Issue by dsdon** [ckeditor/ckeditor5#17524]
## 📝 Provide detailed reproduction steps (if any)

CKEditor4 uses an empty anchor element as the destination for a document/bookmark link. CKEditor5 removes the empty anchor element.
1. In Source view, type &lt;a id="footnotes" name="footnotes"&gt;&lt;/a&gt;
2. Switch back to WYSIWYG view, then switch back to Source view.

### ✔️ Expected result

Preserve the empty anchor element

### ❌ Actual result

The empty anchor element is removed.

## 📃 Other details

This appeared to be fixed in [Issue#: 9888](https://github.com/ckeditor/ckeditor5/issues/9888) but seems to be broken again.
I was able to duplicate this in the "Source code editing and HTML support" demo.
I also tried this using an empty span tag and had the same results so I assume this applies to all empty inline elements that have opening/closing tags.
 
* Browser: Chrome Version: 131.0.6778.71
* OS: Windows 11
* First affected CKEditor version: 43.2.0
* Installed CKEditor plugins: …
import {
	ClassicEditor,
	AccessibilityHelp,
	Alignment,
	Autoformat,
	AutoImage,
	AutoLink,
	Autosave,
	BlockQuote,
	Bold,
	CloudServices,
	Code,
	CodeBlock,
	Essentials,
	FindAndReplace,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	GeneralHtmlSupport,
	Heading,
	Highlight,
	HorizontalLine,
	HtmlComment,
	HtmlEmbed,
	ImageBlock,
	ImageCaption,
	ImageInline,
	ImageInsertViaUrl,
	ImageResize,
	ImageStyle,
	ImageTextAlternative,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	Italic,
	Link,
	LinkImage,
	List,
	ListProperties,
	MediaEmbed,
	PageBreak,
	Paragraph,
	PasteFromOffice,
	RemoveFormat,
	SelectAll,
	ShowBlocks,
	SourceEditing,
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersMathematical,
	SpecialCharactersText,
	Strikethrough,
	Style,
	Subscript,
	Superscript,
	Table,
	TableCaption,
	TableCellProperties,
	TableColumnResize,
	TableProperties,
	TableToolbar,
	TextPartLanguage,
	TextTransformation,
	// Title,
	Underline,
	Undo
} from 'ckeditor5';

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Bookmarks feature will be available in the next release (#1944). Meanwhile, to preserve empty elements, you need to configure `GeneralHtmlSupport` with the [`allowEmpty`](https://ckeditor.com/docs/ckeditor5/43.3.1/api/module_html-support_generalhtmlsupportconfig-GeneralHtmlSupportConfig.html#member-allowEmpty) property.
