### ISSUE TITLE
Intervals and timeouts are orphaned if editor crashes

### ISSUE THREAD

**Issue by lkszzajac** [ckeditor/ckeditor5#17531]
## 📝 Provide detailed reproduction steps (if any)

1. Set `tokenUrl` to a function call that throws an error:
```
cloudServices: {
		tokenUrl: async () => {
			const response = {status: 404}
		   
			if (response.status < 200 || response.status > 299) {
			throw new Error('Cannot download new token.');
			}
		   
			if (typeof response.data !== 'string') {
			throw new Error('Unable to parse token.');
			}
		   
			return response.data;
		   },
```

### ✔️ Expected result

- after editor crashes, the `getToken` interval call should be cleared

### ❌ Actual result

- `getToken` interval call is being executed indefinitely

## 📃 Other details

* Browser: n/a
* OS: n/a
* First affected CKEditor version: n/a
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by f1ames** [comment]
@lkszzajac could it be related or the same as #17462? 🤔

**Comment by Mati365** [comment]
@f1ames Apparently, it's. I added the detection for failing of the token initialization in the cloud services plugin.  Take a look at proposed solution: https://github.com/ckeditor/ckeditor5/pull/17686.
