### ISSUE TITLE
ClassicEditor doesn't translate plugins

### ISSUE THREAD

**Issue by gastonmunoz** [ckeditor/ckeditor5#1753]
🐞 Bug report

## 💻 Version of CKEditor

@ckeditor/ckeditor5-build-classic, version: 11.2.0
@ckeditor/ckeditor5-editor-classic, version 12.0.0
@ckeditor/ckeditor5-heading, version 11.0.0

## 📋 Steps to reproduce

1. Use the ckeditor Angular2+ Component
```
@Component({
    selector: "dynamic-report-designer",
    template: `
        <ng-container *ngIf="(control.visible$ | async)">
            <ckeditor [editor]="editor"></ckeditor>
        </ng-container>`,
    styles: [`
        .list-group-item-action {
            width: 100%;
            display: block;
        }
    `]
})
export class DynamicReportDesignerComponent {
    public editor = ClassicEditor;
}
```
2. Import a language:
```
import "@ckeditor/ckeditor5-build-classic/build/translations/es";
```

3. Use the ClassicEditor from source (not build) and configure the language:
```
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";

ClassicEditor.defaultConfig = {
    toolbar: {
        items: ["heading"]
    },
    language: "es",
    plugins: [Essentials,
        Heading]
};
```

## ✅ Expected result
The heading plugin words are translated to the language selected.

## ❎ Actual result
All plugin words stay in english.
![image](https://user-images.githubusercontent.com/38219335/57549325-9f08e080-7339-11e9-8729-826f74c78a96.png)

**Comment by ma2ciek** [comment]
Hi @gastonmunoz.

Could you tell me how you build the editor? I guess you have an error there.

> import "@ckeditor/ckeditor5-build-classic/build/translations/es";

These translations are invalid after the build as they are connected to the `@ckeditor/ckeditor5-build-classic` package only.

Have a look at the [Setting UI language guide](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#building-the-editor-using-a-specific-language).
