### ISSUE TITLE
AutoLink cannot be removed even with using `removePlugins`

### ISSUE THREAD

**Issue by minaTafreshi99** [ckeditor/ckeditor5#17540]
1. I want to get rid of autolink as it messes up my Iframe but as it is deeply integrated into the ClassicEditor build there is no way to get rid of it while using Link.

### ✔️ Expected result

removePlugins: ['AutoLink'] works for disabling it from editor, or another way to get rid of it in the chain.

### ❌ Actual result

removePlugins is not effective.

## 📃 Other details

* Browser: Different browsers
* OS: MacOS Sonoma 14.7
* First affected CKEditor version: ckeditor5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
I suggest [migrating to the new installation methods](https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/predefined-builds.html). Predefined builds will be deprecated soon, and the other setup methods allow more fine-grained plugins, and I suggest using the [Builder](https://ckeditor.com/ckeditor-5/builder/) and picking needed plugins from the Advanced features tab.
