### ISSUE TITLE
editor.getData() returns invalid table in specific case

### ISSUE THREAD

**Issue by kubaklatt** [ckeditor/ckeditor5#17556]
## 📝 Provide detailed reproduction steps (if any)

1. Open for example https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Create a 4x3 table
3. Merge cells from the second row and second column to the third row of the third column
4. Set the first column as the header
5. Use `editor.getData()` to extract HTML
6. Use `editor.setData()` to implement the table into the editor

### ✔️ Expected result

_`editor.getData()` returns a valid table without additional columns and rows_

### ❌ Actual result

_`editor.getData()` returns a table with additional columns and rows_

https://github.com/user-attachments/assets/d91a57a1-f78f-4127-8b14-3704fd17d2bc

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: 37.0.0-alpha.1
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Could you check if this is a recent regression?

**Comment by kubaklatt** [comment]
@Witoso I managed to locate that the problem started occurring from `37.0.0-alpha.1`
