### ISSUE TITLE
Improve Emoji focus behavior

### ISSUE THREAD

**Issue by przemyslaw-zan** [ckeditor/ckeditor5#17565]
DoD:

- When using the _Show all emoji..._ option in the mention menu, the search bar in the picker should be focused.
- It should not be possible to tab out of the picker menu. Instead, it should loop around from the last focusable element to the first, and vice versa.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
The new UI has covered the DoD points (#17596), so we can close this issue.
