### ISSUE TITLE
Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by dangrishh** [ckeditor/ckeditor5#17588]
### Reproduction steps

in the part of ckeditor builder

"https://ckeditor.com/ckeditor-5/builder/"

eyJtZXNzYWdlIjoiVHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0aWVzIG9mIHVuZGVmaW5lZCAocmVhZGluZyAndmFsdWUnKSJ9

### Definition of Done

- _Please leave this field for us. We will fill it during the backlog refinement session._

### Relevant debug data

```shell

```

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

**Comment by pomek** [comment]
Please explain the problem when creating an issue, how to reproduce it, and the expected and current behavior. Otherwise, we cannot help you.
