### ISSUE TITLE
Lost content when pasting from Outlook (MS Office syntax) -> CKE5

### ISSUE THREAD

**Issue by niallcurtis** [ckeditor/ckeditor5#17599]
## 📝 Provide detailed reproduction steps (if any)

I'm noticing some lost content and styling when pasting from Outlook `365 MSO (Version 2409 Build 16.0.18025.20214) 64 Bit` into CKEditor5 `43.3.1`. We are using the PasteFromOfficeEnhancedPlugin

Here is an example of the raw clipboard content of what I'm copying; an excerpt from larger EML file but I cannot share that here

```
<p class=MsoNormal>
  <b>
    <span lang=EN-GB style='font-size:10.0pt;font-family:"Arial",sans-serif;color:black;mso-themecolor:text1;mso-ansi-language:EN-GB'>
      EXAMPLE? 
    </span>
  </b>
  <b>
    <span lang=EN-GB style='font-size:10.0pt;font-family:"Arial",sans-serif;mso-ansi-language:EN-GB'>
      EXAMPLE
      <o:p></o:p>
    </span>
  </b>
</p>

<ul style='margin-top:0in' type=disc>
  <li class=MsoListParagraph style='margin-left:0in;mso-list:l2 level1 lfo2'>
    <span lang=EN-GB style='font-size:10.0pt;font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-GB'>
      Lorem ipsum
      <o:p></o:p>
    </span>
  </li>
  <li class=MsoListParagraph style='margin-left:0in;mso-list:l2 level1 lfo2'>
    <span lang=EN-GB style='font-size:10.0pt;font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-GB'>
      “Aliquam erat volutpat”
      <o:p></o:p>
    </span>
  </li>
  <li class=MsoListParagraph style='margin-left:0in;mso-list:l2 level1 lfo2'>
    <span lang=EN-GB style='font-size:10.0pt;font-family:"Arial",sans-serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-GB'>
      [Sed dictum nisi at lorem sollicitudin convallis]
    </span>
    <span lang=EN-GB style='font-size:10.0pt;font-family:"Arial",sans-serif;mso-ansi-language:EN-GB'>
      <o:p></o:p>
    </span>
  </li>
</ul>
```

However, once that content enters CKEditor, the content is lost; all the list items are missing their text content, or missing entirely. The text at the top that says EXAMPLE remains.

I'm assuming this relates to the styling/meta tags used by Office suite.

A custom approach where I use DOM parser, and remove the non-standard HTML works, but my bug here is why it doesn't work by default just what was in the clipboard.

### ✔️ Expected result

In CKE5 after pasting without any custom handling, I would see the title, then a list with list items.

### ❌ Actual result

Currently, without manually DOM parsing the clipboard contents then adding the parsed content at selection, I only see the title; the list items are gone.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Microsoft Edge 128.0.2739.107
* OS: Windows 11
* First affected CKEditor version: Currently recognised in `43.3.1`
* Installed CKEditor plugins: PasteFromOfficeEnhanced from `ckeditor5-premium-features` `43.3.1`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey, thanks for sharing the detailed issue. As it's related to the premium feature, and we may need a file to better test the clipboard pipeline, please report it via our [support channel](https://ckeditor.com/contact/) so that we can take a look at it with our devs as soon as possible.
