### ISSUE TITLE
Roots out of order in Document Outline when using a MultiRoot Editor

### ISSUE THREAD

**Issue by hannahwalsh7** [ckeditor/ckeditor5#17600]
## 📝 Provide detailed reproduction steps (if any)

1. Create a CKEditor instance with React using the MultiRoot editor
2. Add the DocumentOutline, Heading, and MultiRootEditor, MultiRootEditorReactIntegration plugins
3. Add a heading in both roots and notice that they appear in the document outline
4. Add a new root either above the first root or between the two existing roots
5. Add a heading into the new root

### ✔️ Expected result

The headings should appear in the same order in the document outline as they appear in the document.

### ❌ Actual result

The latest heading appears at the bottom of the document outline, regardless of where it appears in the document.
![Image](https://github.com/user-attachments/assets/e8f47c4c-90dc-4b0f-b564-43dc533d4dfb)

## 📃 Other details

* Browser: Chrome
* OS: Mac
* First affected CKEditor version: CKEditor 5 v44.0.0
* Installed CKEditor plugins: 
  * Heading
  * DocumentOutline
  * MultiRootEditor
  * MultiRootEditorReactIntegration
  * MultiRootEditorReactRevisionHistoryIntegration

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey, thanks for sharing the detailed issue. As it's related to the premium feature, please report it via our support channel so that we can take a look at it with our devs as soon as possible.
