### ISSUE TITLE
looking for a callback when user leave his session in real-time collaboration.  

### ISSUE THREAD

**Issue by acanshul** [ckeditor/ckeditor5#1760]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
Hello, currently we don't provide such API. If you have any question related to real-time collaboration, please contact us via the [form on our website](https://ckeditor.com/contact/).

**Comment by oskarwrobel** [comment]
Hi, you should be able to do that by observing `#connectedUsers` or `#sessions` collection of `Sessions` plugin.
https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/users-in-real-time-collaboration.html#sessions
