### ISSUE TITLE
Real-time collab:: Looking for user presence list callbacks.

### ISSUE THREAD

**Issue by acanshul** [ckeditor/ckeditor5#1761]
Can we customize or add more info in user presence list in real-time collab, basically want to perform some action by clicking on user in presence list.

**Comment by Mgsy** [comment]
Hello, while creating an issue, please provide some meaningful title and describe your case in a message. Putting a question in the title isn't readable.

cc @oskarwrobel

**Comment by acanshul** [comment]
Sure, Basically I have a scenario where i want to open chat bar with user from presence list.

**Comment by oskarwrobel** [comment]
Unfortunately, PresenceList does not provide any API to customize/extend it.

**Comment by Mgsy** [comment]
@acanshul, if you want to talk about real-time collaboration and its features, please contact us via the [form on our website](https://ckeditor.com/contact/).
