### ISSUE TITLE
How to close editor ...

### ISSUE THREAD

**Issue by grimace** [ckeditor/ckeditor5#1763]
## Is this a bug report or feature request? (choose one)

 **Other**

## 💻 Version of CKEditor
@ckeditor5/ckeditor5-angular 1.0.1
@ckeditor/ckeditor5-build-classic 12.1.0
## 📋 Steps to reproduce

1.  I'm starting ClassicEditor on click of an element on the page
2. Is there a way to close editor ( either programmatically or maybe add a close button to dialog )?

## ✅ Expected result
I have multiple elements on the page, but only want to allow to edit one thing at a time
## ❎ Actual result
dialog is up on page and I'm not sure what event to listen to or how to tell editor to go away.

**Comment by jodator** [comment]
Something like [`editor.destroy()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-destroy)? 

The Angular component implements the [OnDestroy interface](https://angular.io/api/core/OnDestroy) which handles [editor destroy](https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/ckeditor.component.ts#L166-L171).

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by o-alquimista** [comment]
@jodator Sorry for commenting on an old issue, but I can't find where to ask questions.

My question is: when you remove the editor from the DOM by deleting a parent element, do you still have to call its `destroy()` method?

Although the editor no longer exists on the DOM, I worry its javascript instance may still exist, and consume resources, and possibly lead to memory leaks.

**Comment by jodator** [comment]
> My question is: when you remove the editor from the DOM by deleting a parent element, do you still have to call its `destroy()` method?

Yes, you should. The editor creates listeners and most of them might be attached to the DOM so they will not be marked to memory release.

**Comment by Radon8472** [comment]
> Something like [`editor.destroy()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-destroy)?
> 
> The Angular component implements the [OnDestroy interface](https://angular.io/api/core/OnDestroy) which handles [editor destroy](https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/ckeditor.component.ts#L166-L171).

I hat a similar question, as I discovered this issue and your answer..
It took some time to find a way to access the editor object, unfortunally this seems very hidden in the documentation.


Finally I found this piece of code: (at https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/data-from-external-source.html#bootstrapping-the-project)

```javascript
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        plugins: [ Essentials, Paragraph, Heading, List, Bold, Italic, ExternalDataWidget ],
        toolbar: [ 'heading', 'bold', 'italic', 'numberedList', 'bulletedList', '|', 'undo', 'redo' ]
    } )
    .then( editor => {
        console.log( 'Editor was initialized', editor );

        CKEditorInspector.attach( 'editor', editor );

        // Expose for playing in the console.
        window.editor = editor;
    } )
    .catch( error => {
        console.error( error.stack );
    } );
```

The importand part is that `then()` can be used to make the editor object accessable in your scripts, what gives you the chance to call `destroy()` or anything else.

@grimace

I would not recomment to story your editor globally on the windows, but If you have multiple editors, you could create an array, where you add each of your editors, for later calls of destroy.
