### ISSUE TITLE
Table drag and drop box does not disapear when table loses focus

### ISSUE THREAD

**Issue by felipeissa** [ckeditor/ckeditor5#17630]
## 📝 Provide detailed reproduction steps (if any)

1 - Open ck [editor demo app](https://ckeditor.com/ckeditor-5/demo/feature-rich/)
2. - Click on the table, it will have yellow borders and the box to drag and drop it will be visible:

![Image](https://github.com/user-attachments/assets/b6a4e024-3e29-4338-8f60-8c26f9164372)

3 - Now click outside of the table, the yellow border and the drag drop box in the top left corner dissapear

![Image](https://github.com/user-attachments/assets/424bc254-1bfd-4c67-9a57-fa9f9c5dd1c6)

4 - Now click again on the table, inside the drag and drop box (borders will be blue):

![Image](https://github.com/user-attachments/assets/7e0dc4f0-8374-4758-80a1-e8e1b8e7f9d3)

5 - Click outside of the table (same way as step 3). The border is back to grey, but the drag and drop box still visible:

![Image](https://github.com/user-attachments/assets/2066c3ae-27bd-4eb6-b6eb-0d383ba00320)

### ✔️ Expected result

Drag and drop box should disapear once table loses focus.

### ❌ Actual result

Drag and drop box still visibible

## 📃 Other details

* Browser: Chrome (131.0.6778.109)
* OS: Windows 11
* First affected CKEditor version: Dont know
* Installed CKEditor plugins: Its demo page 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
This is a proper behavior. On step 5 most likely you clicked outside the editor, this is so-called blur state, indicated by the gray outline on the table. It lets users go back to the point where the selection was after they did something outside of the editor. If a gray boundary appears when you click in the editor, please share a recording.
