### ISSUE TITLE
Merge Tags or fields ?

### ISSUE THREAD

**Issue by Nothing-Works** [ckeditor/ckeditor5#1765]
## Is this a bug report or feature request? (choose one)

  🆕 Feature request  

Merge tags allow users to dynamically add content to their email,

like curly brackets  {{ ... }} or square brackets [ ... ] or any other.

Thanks

**Comment by Mgsy** [comment]
Hello, we've created a guide that shows how to implement the placeholder feature which could be used to insert content dynamically. You can find it [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html).

**Comment by Nothing-Works** [comment]
@Mgsy  thank you very much
