### ISSUE TITLE
CKEditor 5 Image ALT text getting removed on image replace

### ISSUE THREAD

**Issue by vtulse** [ckeditor/ckeditor5#17670]
## 📝 Provide detailed reproduction steps (if any)

1. Add the image and filled the alt text for the image
![Image](https://github.com/user-attachments/assets/f5cb1ae5-1738-4448-a382-e4b8694ab447)

3. Click on the image and replace currently added image with new will not retain the old alt text.
![Image](https://github.com/user-attachments/assets/fb601046-1bb5-4984-b1ba-d8877d8a3c89)

### ✔️ Expected result

Make sure to keep the alt tag that functions in previous versions of CKE 5.

### ❌ Actual result
ALT text got removed post image replace.
![Image](https://github.com/user-attachments/assets/39868235-5d2e-4954-8c72-addff59f7501)

### ❓ Possible solution

-

---
Note: Please ignore the advisory title which is our custom changes.
We have tried to add attributeToAttribute but it is not going into that.
 .attributeToAttribute({
        view: {
          name: 'img',
          key: 'alt',
        },
        model: {
          key: 'alt',
          value: (viewElement) => {
            return viewElement.getAttribute('alt');
          },
        },
      })

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hi! Could you name versions between which you observed the regression?

**Comment by Witoso** [comment]
Thanks for the info! Please reach first to the Drupal community. As far as I know, they maintain their own implementation of images.
