### ISSUE TITLE
Expose ClassicEditorUIView in the main ckeditor5 package

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#17681]
## 📝 Provide a description of the improvement

Some integrators would like to use `ClassicEditorUIView` class, however it is not exported from the main `ckeditor5` package in v42+ (NIM).

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Closed by #17682.
