### ISSUE TITLE
pastefromoffice

### ISSUE THREAD

**Issue by 516821202** [ckeditor/ckeditor5#1771]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1. Can't use Word replication function in WPS software
2. WPS is the most common editing software in China
3. WPS goes beyond Word usage

**Comment by Mgsy** [comment]
Hello, can you describe your problem more precisely? The information in 'steps to reproduce' is unclear. According to the issue title, I assume you want to paste the content from WPS Office to CKEditor 5?

**Comment by 516821202** [comment]
1、If I use WPS software to copy and paste, I will report an error：
        Not allowed to load local resource: 
        file:///C:/Users/MRZHOU~1/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png
2、But if I copy and paste with Microsoft Word, I will convert the picture into bese64 format, and there will be no error.
3、In China, WPS functions are the same as Microsoft Word, and 90% of people use wps.
4、I annotate the normalizeSpacerunSpans function of space. JS in ckeditor5-paste-from-office, and then change the regexPictureHeader regularity of the extractImageDataFromRtf function of image. JS to base64, but I don't know if it's correct or not.

**Comment by Mgsy** [comment]
Thanks. Currently, pasting from WPS is not supported. I saw that you opened an issue in [ckeditor5-paste-from-office](https://github.com/ckeditor/ckeditor5-paste-from-office/issues/58) repository, so I will move the discussion there and confirm it as a feature request.
