### ISSUE TITLE
How do you enumerate tooltip options when using the Vue integration?

### ISSUE THREAD

**Issue by KenLFG** [ckeditor/ckeditor5#1776]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

CKEditor 5 / Classic Build or Custom Build (tried both)

## 📋 Steps to reproduce

1. Follow the docs to set up the Vue js integration to where you get an editor as expected in the page.
2. Struggle to figure out how to enumerate the toolbar options based on the docs' recommendation: Array.from(editor.ui.componentFactory.names());

## ✅ Expected result

That there's a straight-forward and successful way to do this as the documentation for many plugins either don't mention the options available or do but having to go through each and every plugin to collect that information is tedious.

## ❎ Actual result

No way to enumerate the toolbar options. I've tried access the editor instance assigned to the Vue component. For example, using the local component example which is documented as follows:

`<template>
    <div id="app">
        <ckeditor :editor="editor" ... ></ckeditor>
    </div>
</template>

<script>
    export default {
        name: 'app',
        components: {
            // Use the <ckeditor> component in this view.
            ckeditor: CKEditor.component
        },
        data() {
            return {
                editor: ClassicEditor,

                // ...
            };
        }
    }
</script>`

If you use the Vue dev console to flag the component (so it's available in the browser JS console as $vm0), attempting to use the following doesn't work:

> Array.from ($vm0.editor.ui.componentFactory.names());

Because "ui" is undefined. I tried digging around the code and found the ComponentFactory class defined in the editorui module, trying to see if I could hack it into existence (i.e. new ComponentFactory($vm0.editor) but no dice. I'll get a CF instance but it doesn't have a names function.

I don't know if it's just that the docs are out of date or if something else is going on. Note that I'm using Webpack to package this all up.

## 📃 Other details that might be useful

Cutting an excerpt out of the package.json so you can see what components I'm using and what versions are installed:

`
    "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.1",
    "@ckeditor/ckeditor5-alignment": "^11.1.0",
    "@ckeditor/ckeditor5-autoformat": "^11.0.1",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.0",
    "@ckeditor/ckeditor5-block-quote": "^11.0.1",
    "@ckeditor/ckeditor5-build-classic": "^12.1.0",
    "@ckeditor/ckeditor5-build-inline": "^12.1.0",
    "@ckeditor/ckeditor5-ckfinder": "^11.0.1",
    "@ckeditor/ckeditor5-core": "^12.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.0",
    "@ckeditor/ckeditor5-easy-image": "^11.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.0",
    "@ckeditor/ckeditor5-essentials": "^11.0.1",
    "@ckeditor/ckeditor5-heading": "^11.0.1",
    "@ckeditor/ckeditor5-image": "^13.0.1",
    "@ckeditor/ckeditor5-link": "^11.0.1",
    "@ckeditor/ckeditor5-list": "^12.0.1",
    "@ckeditor/ckeditor5-media-embed": "^11.1.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.1",
    "@ckeditor/ckeditor5-paste-from-office": "^11.0.1",
    "@ckeditor/ckeditor5-table": "^12.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^13.0.1",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^2.0.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
`
Let me know if there are any other details you need.

Note that this isn't an isolated issue (with regard to my case at least) as I found this SO question where another person had the same issue:

https://stackoverflow.com/questions/55531854/how-to-customize-ckeditor-5-in-a-vuejs-app

**Comment by Mgsy** [comment]
Hello, you receive `undefined` because you don't have access to the editor instance. In Vue.js integration, the quickest way to use editor instance and its API is by the `@ready` event. You should put `@ready` listener in the template and create a proper method. 

The code might look like this:

```js
<template>
    <div id="app">
        <ckeditor :editor="editor" @ready="onEditorReady"></ckeditor>
    </div>
</template>

<script>
    import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

    export default {
        name: 'app',
        data() {
            return {
                editor: ClassicEditor,
                editorData: '<p>Content of the editor.</p>'
            };
        },
        methods: {
            onEditorReady( editor ) {
                // Display all toolbar items.
                console.log( Array.from( editor.ui.componentFactory.names()) );
            }
        }
    }
</script>
```
