### ISSUE TITLE
Toolbar in Multi root sample not usable on mobile

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1779]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Open multi root example
2. Select word in lower editing fields

## ✅ Expected result

Toolbar is shown so you can use buttons like bold

## ❎ Actual result
You have to scroll up
## 📃 Other details that might be useful
![Screenshot_20190528-135007_Chrome](https://user-images.githubusercontent.com/247363/58475967-b7596780-814f-11e9-9af6-96152566f8e1.jpg)

**Comment by Mgsy** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/1107?

**Comment by jodator** [comment]
@Mgsy: I think no - The problem is with sample itself IMO. The toolbar is not shown if you scroll down on mobile. The #1107 is about overlapping it by native toolbar.

Here I think the toolbar should follow the viewport.
