### ISSUE TITLE
Removing 1 image results in removing 2

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1782]
## Is this a bug report or feature request? (choose one)

🐞 Bug report
## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Found in balloon editor
2. Insert 3 images in the content
3. Selection one image (by touching it) - ie middle one
4. Delete it using android keyboard

## ✅ Expected result

The selected image is removed.

## ❎ Actual result

- Two images are removed.

## 📃 Other details that might be useful

:popcorn: : 
![Peek 2019-05-28 15-16](https://user-images.githubusercontent.com/247363/58480934-a7e01b80-815b-11e9-9cbd-47741c73f54f.gif)

**Comment by Mgsy** [comment]
This issue isn't reproducible anymore.
