### ISSUE TITLE
Include MathType plugin in the Features section

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1787]
## Is this a bug report or feature request? (choose one)

Docs

## 💻 Version of CKEditor

CKEditor v5 @ 12.1.0

## 📋 Steps to reproduce

Wiris have created an integration with CKEditor 5. It would be great to feature [mathtype-ckeditor5](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5) plugin in our Features section.

**Comment by rathiayush** [comment]
[mathtype-ckeditor5](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5) has some issues
please see below thread:-
https://github.com/ckeditor/ckeditor5/issues/1920

**Comment by mlewand** [comment]
Thanks for letting us know @rathiayush 👍

**Comment by mlewand** [comment]
Fixed with #1943.
