### ISSUE TITLE
Integration tests for Editor.setData/getData

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#179]
There was an issue that arguments passed to `DataController` from `Editor.setData` were in wrong order. No test catch that, so we should write some integration tests that check if data and other arguments are passed properly to `DataController` and then down to the model.

**Comment by Reinmar** [comment]
There are 3 things to do actually:

1. Add integrational tests.
2. Fix existing unit tests.
2. Fix creator mocks (including the temporary one in ckeditor5/ckeditor5-creator-classic).
