### ISSUE TITLE
Edge modifies HTML attributes order, what breaks unit tests

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor5#1790]
## Is this a bug report or feature request? (choose one)

Other

## 📋 Steps to reproduce

There appears situation, when CI breaks build, because MS Edge creates slightly different HTML output. Attributes, classes or styles might be sorted in different order, than in Chrome or Firefox. There should be some semi-automatic method which will fix that situations.
https://github.com/ckeditor/ckeditor5-font/pull/44#issuecomment-497334287

Sample to test in Edge and other browsers:
https://codepen.io/msamsel/pen/XwyVmm

Potential solutions:
1. CKE4 has created own function which sort the attributes:
   * https://github.com/ckeditor/ckeditor-dev/blob/597482b6d46c1f5c16ebc9a7d7072a8d6cd8aca8/tests/_benderjs/ckeditor/static/tools.js#L284
   * https://github.com/ckeditor/ckeditor-dev/blob/597482b6d46c1f5c16ebc9a7d7072a8d6cd8aca8/tests/_benderjs/ckeditor/static/tools.js#L119
2. https://www.chaijs.com/plugins/chai-dom/

**Comment by Reinmar** [comment]
Not interested in investing in fixing tests for Edge. But it's a general problem that we use the native HTML writer which can behave slightly differently on different browsers. 

I'm closing this ticket. If this issue ever pops up again, let's report a new, generic ticket for it (or find an existing ticket, cause I think we discussed this already).
