### ISSUE TITLE
Simple upload adapter

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1791]
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 📋 Steps to reproduce

We already have an [extensive documentation on how to create a custom upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html), but it would be even nicer to make a plugin that exposes very simple API for basic uploading.

**Comment by ma2ciek** [comment]
Maybe we can fork https://github.com/pourquoi/ckeditor5-simple-upload? :trollface:
