### ISSUE TITLE
What is the best way to upgrade a customized build?

### ISSUE THREAD

**Issue by moyuanhuang** [ckeditor/ckeditor5#1795]
## Is this a bug report or feature request? (choose one)
Other

🐞 Bug report  |  🆕 Feature request  |  Other

Hello! I'm trying to upgrade CKEditor 5 to 12.1.0, I ran a customized build of CKEditor on my application. I originaled installed it by
```
yarn add '@ckeditor/ckeditor5-editor-classic' \
'@ckeditor/ckeditor5-essentials' \
'@ckeditor/ckeditor5-basic-styles' \
'@ckeditor/ckeditor5-highlight' \
'@ckeditor/ckeditor5-link' \
'@ckeditor/ckeditor5-alignment'
```

I wonder if I have to manually modify the versions of all related packages in my `package.json` or is there a simpler way to do it? Thanks!

**Comment by Mgsy** [comment]
Hello, you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to automatically update your dependencies in package.json.

**Comment by moyuanhuang** [comment]
@Mgsy Thanks! I'll try it later and see how it works. Closing the issue for now.
