### ISSUE TITLE
Can't indent first list item in an unordered list

### ISSUE THREAD

**Issue by mikedanger** [ckeditor/ckeditor5#1796]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor 5 - I'm not sure of our exact configuration but this happens for me in the "stock" demo at https://ckeditor.com/ckeditor-5/demo/

## 📋 Steps to reproduce

1. Create an unordered list.
2. Press the tab key on the first list item

## ✅ Expected result

First list item is indented

## ❎ Actual result

Nothing happens/CKEditor loses focus

## 📃 Other details that might be useful

Sorry if this is documented somewhere as intended behavior, I tried Google and the official CK docs and didn't find anything that seemed relevant. I have a client that actually wants this behavior, and from what I can tell if I try to create it manually it passes a validator as good HTML. If there's some reason it's built this way I'm happy to take it back to them.

**Comment by Mgsy** [comment]
Hi, this is intended behaviour of the editor. We decided to keep lists with proper semantic and good-looking HTML, so indenting the first list item won't be possible.
