### ISSUE TITLE
ckEditor-Angular, viewportTopOffset: is not working

### ISSUE THREAD

**Issue by kapilthakkar2912** [ckeditor/ckeditor5#1797]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## ckEditor 5 - with Angular

ClassicEditor

add viewportTopOffset in config json as below
```
public ckEditorConfig = {
      viewportTopOffset: 300,
        toolbar: [
          'heading',.....
.........
```

**Comment by Mgsy** [comment]
Hello, `viewportTopOffset` property should be defined inside `toolbar` (look at the example on our [documentation page](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-toolbar)).

Your config should look like this:

```js
public ckEditorConfig = {
    toolbar: {
        items: [ 'heading' ],
        viewportTopOffset: 300
    }
    // ...
}

**Comment by kapilthakkar2912** [comment]
Sorry my bad :( 

But when image added then toolbar get overlap.

![ckEditor_toolbar](https://user-images.githubusercontent.com/19683659/58939086-355ad700-872b-11e9-97f8-9ff4dbeaf473.png)

**Comment by ma2ciek** [comment]
Hi @kapilthakkar2912,

Probably your CSS overrides the default CKEditor 5 CSS for the image. We can't do anything about it. You should create a page which CSS don't affect the CKEditor 5 editor.

These are the default styles for the image element:

```css
.ck-content .image>img {
    display: block;
    margin: 0 auto;
    max-width: 100%;
}
```

And note that if you have:

```css
img {
   // some prop: value;
}
```

Then it will affect all images, including images in the CKEditor 5 editor.

**Comment by kapilthakkar2912** [comment]
Hi @ma2ciek ,
Thank you for your replay.

I have added following css code in style.css and its work :).

```
.ck-content .image>img {
    display: block;
    margin: 0 auto;
    max-width: 100%;
}
```
