### ISSUE TITLE
Invalid link in CKFinder configuration

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#1798]
🐞 Bug report 

## 💻 Version of CKEditor

12.1

## 📋 Steps to reproduce

1. Go to https://ckeditor.com/docs/ckeditor5/latest/api/module_ckfinder_ckfinder-CKFinderConfig.html#member-options 
2. Click on a link in "Check the file manager documentation for the complete list of options."

## ✅ Expected result

Page with CKFinder options should be shown. Most likely this one: https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config

## ❎ Actual result

The 404 is being thrown because the link is https://ckeditor.com/docs/ckfinder/latest/ckfinder3/.html#!/api/CKFinder.Config

**Comment by Reinmar** [comment]
In all other links to CKFinder.Config we use absolute links like https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config-cfg-language. I remember there was some issue with relative links to CKFinder docs.
