### ISSUE TITLE
Button tooltip looks fuzzy on Chrome 75

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1802]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master & the one in the docs

## 📋 Steps to reproduce

1. Hover mouse over the button in the toolbar.

## ✅ Expected result

The tooltip is sharp as in Firefox:
![Selection_037](https://user-images.githubusercontent.com/247363/59092808-baecab80-8912-11e9-9f59-7d31276130b7.png)

## ❎ Actual result

Chrome 75:
![Selection_038](https://user-images.githubusercontent.com/247363/59092827-c2ac5000-8912-11e9-850b-7ebe90a86ce0.png)

Edit: There's also a visible line of the tooltip outline that separates the tip (triangle) of the tooltip.

## 📃 Other details that might be useful

Chrome: `75.0.3770.80 (Official Build) (64-bit)`
OS: `Linux Mint 19.1 Cinnamon`

**Comment by dkonopka** [comment]
I can confirm it, it looks fuzzy on macOS (non-retina). It is something related to the height with a number after the decimal point.

![chrome75-4k](https://user-images.githubusercontent.com/10219857/59093785-0e5ff900-8915-11e9-9749-b7ab861b1206.png)

See:

![glitch](https://user-images.githubusercontent.com/10219857/59094160-dd33f880-8915-11e9-85df-1f1b4b432143.gif)

**Comment by oleq** [comment]
Pixel rounding is the issue. Adding `top: 0` to `.ck.ck-tooltip` seems to be the right fix. Can you confirm @dkonopka?
