### ISSUE TITLE
Remove the "catch" statement from samples included in CKEditor 5 builds (?)

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1803]
I recently encountered an issue when trying to load one of 3rd party plugins into a CKEditor 5 build. Unfortunately the error logged in the console was completely useless:

![Screen Shot 2019-06-07 at 11 24 45 AM](https://user-images.githubusercontent.com/545175/59094644-e1ace100-8916-11e9-9677-bc890dd0ed04.png)

Only after I commented the catch block, it showed me something meaningful:

![Screen Shot 2019-06-07 at 11 26 01 AM](https://user-images.githubusercontent.com/545175/59094718-0bfe9e80-8917-11e9-97ad-677be0395ab6.png)

It took me a few seconds to understand that I can try getting rid of the catch statement that looked like something that should just show me the correct stack trace, to see if that changes anything:

<img width="338" alt="Screen Shot 2019-06-07 at 11 26 35 AM" src="https://user-images.githubusercontent.com/545175/59094781-318ba800-8917-11e9-8d6c-50bd9b666ef0.png">

In order to improve the developer experience, I'd get rid of that statement.

**Comment by Reinmar** [comment]
That's a good catch.

**Comment by jodator** [comment]
>     2\. it's a good practice to have the `.catch()` call at the end of a promise chain, so I'm not sure how lack of it will be seen by the developers

Well to be honest I don't what's worse dummy catch or no `.catch()` clause at all ;)

Maybe the better solution would be (ps.: remember about the full names, like in `error`?):
```js
.catch( error => {
    // Handle the editor initalisation errors - ... (or some better text :P )
    console.error( 'There was a problem with initializing the editor', error );
} );
```
with the above we have: full error logged, no uncaught error in promise logged and better practice with having he `catch()` clause.

But logging the full error will be better then logging only `err.stack`.

**Comment by Reinmar** [comment]
> But logging the full error will be better then logging only `err.stack`.

That's the point of:

> 2\. it's a good practice to have the `.catch()` call at the end of a promise chain, so I'm not sure how lack of it will be seen by the developers

It doesn't work now, but perhaps it can work. The flaws of the current body of the `catch()` callback are (perhaps) not a reason to completely negate the value of using that `catch()`. Let's just find out if there's a better way.

**Comment by jodator** [comment]
> Let's just find out if there's a better way.

Logging the full `error` object instead of `error.stack` as a start. Adding some message to this might be also helpful (to show that we caught that error).

**Comment by wwalc** [comment]
Getting rid of the catch statement was the first idea that came to my mind to solve the real problem that was introduced by "wrong" catch statement.  I do agree with both of you that if we can catch errors but at the same time show the full information about the issue (log the full error, whatever) + a custom error message as proposed in https://github.com/ckeditor/ckeditor5/issues/1803#issuecomment-505020018, then it would look more professional, then just getting rid of the catch statement.

**Comment by mlewand** [comment]
Fixed with a PR in each build:

* [decoupled-document](https://github.com/ckeditor/ckeditor5-build-decoupled-document/pull/30)
* [inline](https://github.com/ckeditor/ckeditor5-build-inline/pull/20)
* [balloon](https://github.com/ckeditor/ckeditor5-build-balloon/pull/36)
* [classic](https://github.com/ckeditor/ckeditor5-build-classic/pull/93) (main)
* [balloon-block](https://github.com/ckeditor/ckeditor5-build-balloon-block/pull/14)
