### ISSUE TITLE
Append elements to main widget on downcast?

### ISSUE THREAD

**Issue by theknet** [ckeditor/ckeditor5#1804]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

12.1.0

## 📋 Steps to reproduce

I've searched everywhere in the documentation but cannot find an answer. If I'm given a simple element such as `<my-element config="1,2,3"></my-element>`, is it possible to add "placeholder" elements inside? For example, the above code, becomes this:

```
<my-element config="1,2,3">
    <ul class="wrapper-element">
        <li>Element 1</li>
        <li>Element 1</li>
        <li>Element 1</li>
    </ul>
</my-element>
```

The outer element is a non-editable widget and setting the config attribute is handled through commands.

**Comment by Mgsy** [comment]
Hello, please take a look at our [implementing a block widget guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html), it describes how to implement a non-editable block widget with elements inside of it.

**Comment by theknet** [comment]
Hey @Mgsy, thank you for the response! There's a slight difference as to what we're trying to achieve and what the documentation describes.

From our backend we will receive the following code:
`<my-element config="1,2,3"></my-element>`

But when the editor loads our plugin, we'd like to convert this on the fly so in the editor it becomes:

```
<my-element config="1,2,3">
    <ul class="wrapper-element">
        <li>Element 1</li>
        <li>Element 1</li>
        <li>Element 1</li>
    </ul>
</my-element>
```

And on save, we only get the original content which would be `<my-element config="1,2,3"></my-element>`. However, the documentation describes loading content that is already there. We could do this before loading the editor and append the elements we need but we'd need to listen for commands and update the HTML before reloading the editor content with updated HTML.

Is it possible to do this using downcasting?

**Comment by Mgsy** [comment]
@jodator, can you take a look at this one?

**Comment by jodator** [comment]
Hi @theknet it's totally doable but requires some work.

First you need to upcast (convert view-to-model) the `<my-element>` to proper model elements:

```js
this.editor.conversion.for( 'upcast' ).add( dispatcher => dispatcher.on( 'element:my-element', ( evt, data, conversionApi ) => {
	const { modelCursor, modelRange, viewItem } = data;
	const { writer } = conversionApi;

	const config = viewItem.getAttribute( 'config' );
	const myElement = writer.createElement( 'myElement', { config } );

	const listItems = config.split( ',' );

	for ( const listItemId of listItems ) {
		const listItem = writer.createElement( 'listItem', { listType: 'bulleted', listIndent: 0 } );

		writer.insert( listItem, writer.createPositionAt( myElement, 'end' ) );
		const text = writer.createText( `Element ${ listItemId }` );

		writer.insert( text, writer.createPositionAt( listItem, 0 ) );
	}

	writer.insert( myElement, modelCursor );
} ) );
```

This way you'll have `myElement` in the model and created the list items inside it.

Now the downcast conversion (model-to-view) has two pipelines (editingDowncast and dataDowncast) - more on conversion is [in framework guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#conversion).

For editing downcast you wan't to leave default conversion:

```js
this.editor.conversion.for( 'editingDowncast' ).elementToElement( {
	model: 'myElement',
	view: 'my-element'
} );
```

but for data downcast you should write own conversion that will convert `myElement` to proper form of `my-element` ie will read list item text nodes and create config value.
