### ISSUE TITLE
Find coordint offset top and left for cursor

### ISSUE THREAD

**Issue by MuTaToR08** [ckeditor/ckeditor5#1807]
I want to display a context menu under the cursor. How can I find the offset coordinates in pixels?

**Comment by jodator** [comment]
To show an [ContextualBalloon](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_panel_balloon_contextualballoon-ContextualBalloon.html#function-add) you provide a set of data. One of them is a [target](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_dom_position-Options.html#member-target) to which attach the balloon. It accepts a [Rect class](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_dom_rect-Rect.html).

You can pass the DOM range to the `Rect.getDomRangeRects()`. This can be obtained from model's selection using model to view mapper and `domConverter`:

```js
const editing = editor.editing;
const domConverter = editing.view.domConverter;
const mapper = editing.mapper;

const viewRange = mapper.toViewRange( modelRange );
const rangeRects = Rect.getDomRangeRects( domConverter.viewRangeToDom( viewRange ) );

// Get first rect
return rangeRects.pop();
```

You can also check how mention feature [implements this](https://github.com/ckeditor/ckeditor5-mention/blob/b6a50cf48aa856ec600e827fe6f21ee5af06245d/src/mentionui.js#L453).

**Comment by MuTaToR08** [comment]
ContextualBalloon is displayed incorrectly if the edited block is inside an iframe

**Comment by MuTaToR08** [comment]
this code throw error
`ncaught TypeError: Cannot read property 'name' of undefined
    at Qs.getModelLength (ckeditor.js:5)
    at Qs._findPositionIn (ckeditor.js:5)
    at Qs.on.priority (ckeditor.js:5)
    at Qs.fire (ckeditor.js:5)
    at Qs.toViewPosition (ckeditor.js:5)
    at Qs.toViewRange (ckeditor.js:5)`
error in line: https://github.com/ckeditor/ckeditor5-engine/blob/e9d05fa9eaa70885bc32b60989d5bb9c5bb11807/src/conversion/mapper.js#L422
i use next code: 
` 
import Rect from '@ckeditor/ckeditor5-utils/src/dom/rect';
...
      const editing = this.editor.editing;
        const domConverter = editing.view.domConverter;
        const mapper = editing.mapper;

        const range =  this.editor.model.document.selection.getFirstRange();
        const viewRange = mapper.toViewRange(range);
        const rangeRects = Rect.getDomRangeRects( domConverter.viewRangeToDom( viewRange ) );`
