### ISSUE TITLE
I  want to see all toolbars config, but I can't find 

### ISSUE THREAD

**Issue by hhlingyoko** [ckeditor/ckeditor5#1809]
hello， I want to add some code in document , but i can't find the Configuration.  how can i find this ？ thanks

**Comment by Mgsy** [comment]
Hi, can you describe more precisely what do you want to achieve? What kind of code do you want to add to the document?

**Comment by hhlingyoko** [comment]
> Hi, can you describe more precisely what do you want to achieve? What kind of code do you want to add to the document?

such as javascript html c++ …

**Comment by hhlingyoko** [comment]
> Hi, can you describe more precisely what do you want to achieve? What kind of code do you want to add to the document?

I want to choose code type and insert  code to the page. 
or I want to know is there any other ways to insert code in the document

**Comment by Mgsy** [comment]
Currently, CKEditor 5 doesn't have such a feature, but we might implement it at some point. Please, take a look at the [discussion about this plugin](https://github.com/ckeditor/ckeditor5/issues/436) and feel free to comment - it will allow us to track the popularity of this request.

**Comment by hhlingyoko** [comment]
> Currently, CKEditor 5 doesn't have such a feature, but we might implement it at some point. Please, take a look at the [discussion about this plugin](https://github.com/ckeditor/ckeditor5/issues/436) and feel free to comment - it will allow us to track the popularity of this request.

![image](https://user-images.githubusercontent.com/16332083/59258666-f8329f80-8c6a-11e9-86df-2ceaa6f273d3.png)
I want to use this tool ，but I can't find this tool's name

**Comment by Mgsy** [comment]
This is a Code plugin for creating inline code. It's not enabled by default, so you need to create a custom build with this plugin attached. You should import it from the basic styles plugin:
```js
import Code from '@ckeditor/ckeditor5-basic-styles/src/code';
```

Please, take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html), it explains how to add plugins in a proper way.

**Comment by matteboy99** [comment]
@Mgsy I'm also keen to use this plugin - I'm utilising vue.js which seems to throw an error on a duplication issue when building the editor. Is the 'code' tool available by default with the vue.js build?

**Comment by Mgsy** [comment]
Hi @matteboy99, you should build the editor from source with Code plugin. You can find a guide [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source).

**Comment by matteboy99** [comment]
@Mgsy can I not extend the vue.js build?

**Comment by Mgsy** [comment]
If you don't want to mess around in Vue.js files, you can prepare a custom CKEditor 5 build ([here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) is a guide) and simply attach it to your component (instead of importing `@ckeditor/ckeditor5-build-classic`, import your custom build).

**Comment by matteboy99** [comment]
@Mgsy understood. Thanks for your help!
