### ISSUE TITLE
React: Custom build giving duplicate module error

### ISSUE THREAD

**Issue by Rc85** [ckeditor/ckeditor5#1817]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other
Other

## 💻 Version of CKEditor
```
"@ckeditor/ckeditor5-autoformat": "^11.0.2",
"@ckeditor/ckeditor5-basic-styles": "^11.1.1",
"@ckeditor/ckeditor5-block-quote": "^11.1.0",
"@ckeditor/ckeditor5-build-classic": "^12.2.0",
"@ckeditor/ckeditor5-editor-classic": "^12.1.1",
"@ckeditor/ckeditor5-essentials": "^11.0.2",
"@ckeditor/ckeditor5-heading": "^11.0.2",
"@ckeditor/ckeditor5-link": "^11.0.2",
"@ckeditor/ckeditor5-list": "^12.0.2",
"@ckeditor/ckeditor5-paragraph": "^11.0.2",
"@ckeditor/ckeditor5-react": "^1.1.3",
"@ckeditor/ckeditor5-table": "^13.0.0",
"@ckeditor/ckeditor5-theme-lark": "^14.0.0",
"@ckeditor/ckeditor5-undo": "^11.0.2",
"@ckeditor/ckeditor5-alignment": "^11.1.1",
"@ckeditor/ckeditor5-dev-utils": "^12.0.1",
"@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
```

## 📋 Steps to reproduce

Build with original source code from @ckeditor/ckeditor5-build-classic using the original webpack config.

Follow this tutorial https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html

## ✅ Expected result

Not get a duplicate module error.

## ❎ Actual result

`ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules`

## 📃 Other details that might be useful

I even build with no plugins.

```
/**
 * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

// The editor creator to use.
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
];

// Editor configuration.
ClassicEditor.defaultConfig = {
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};
```
And still getting the error. I even tried using @ckeditor/ckeditor5-build-classic as the editor and still getting error.

```
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import CKEditor from '@ckeditor/ckeditor5-react';
```

**Comment by Mgsy** [comment]
Hello, I've followed all the steps in [Custom builds guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and everything works as expected.

I can see that you try to integrate the editor with React, please follow our [guide about the integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) to make it properly.

**Comment by Rc85** [comment]
> Hello, I've followed all the steps in [Custom builds guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and everything works as expected.
> 
> I can see that you try to integrate the editor with React, please follow our [guide about the integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) to make it properly.

I'm trying to do a custom build so that I can add the Alignment plugin. Am I doing something wrong?

**Comment by Mgsy** [comment]
>Am I doing something wrong?

I don't know without knowing what did you do exactly 😄 Can you write steps which you perform to reproduce the issue (please, be precise as much as you can).

**Comment by Rc85** [comment]
> > Am I doing something wrong?
> 
> I don't know without knowing what did you do exactly 😄 Can you write steps which you perform to reproduce the issue (please, be precise as much as you can).

1. I cloned this repo: https://github.com/ckeditor/ckeditor5-build-classic
2. I installed all the dependencies by running npm install and even install them in my project.
3. I opened `ckeditor.js` inside the `src` folder
4. I copied and pasted the same code (without `CustomPlugin` and `OtherCustomPlugin`) from here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html#updating-build-configuration
5. I added the Alignment plugin
5. I cd into the cloned `ckeditor5-build-classic` directory and run `npm build`
6. In my React component, I import `ClassicEditor` from the cloned repo like so: `import ClassicEditor from '../dir/to/ckeditor5-build-classic';`
7. Save my project and webpack dev server reloads my project in the browser and I get the duplicate module warning. The editor loads perfectly fine though, but the error bothers me and I suspect will increase my build size.
8. I tried removing 1 plugin at a time and building (until there are no plugins left like the code provided in my original post), but still getting the duplicate error.
9. I don't have any imported ckeditor dependencies in my project, just the `ClassicEditor` from the build and `CKEditor` from `ckeditor-react`.

In my webpack.config.js, the only thing relevant to CKEditor is 

    const { styles } = require( '@ckeditor/ckeditor5-dev-utils' );

and

```
    {
        loader: 'postcss-loader',
            options: styles.getPostCssConfig({
                themeImporter: {
                    themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
                },
            minify: true
        })
    },
```

I only want to accomplish two things:

1. Be able to use the Alignment plugin
2. Have my components that use CKEditor pass the jest snapshot test. And the only way is to rebuild from src according to this issue https://github.com/ckeditor/ckeditor5-react/issues/66

**Comment by Mgsy** [comment]
@pomek, can you help in investigating the problem?

**Comment by pomek** [comment]
Without looking at `src/app.js` or a place where the component is used we can do nothing. If our builds (even without any modification) throws the dup error, it means that any of `ckeditor5-*` package is imported on the same level as `ckeditor5-build-*`. I don't see any other solution.

**Comment by Mgsy** [comment]
Closing it due to a lack of activity.

**Comment by euharbachou** [comment]
i think it still open should be, this error crash react app

**Comment by mikewudev** [comment]
I know this is old, but in case it's useful. I solved the duplicate plugin issue by making sure I was **only ever importing the custom build** in the entire app.

**Comment by uharbachou** [comment]
@mikewudev yes, it will fix the problem
more of that, if you make import only in one component also will work, but in two different component it will make error. No. I don't agree with that solution. Or warning or error in dev mode but in prod it will be surprise for all.

**Comment by uharbachou** [comment]
or not initialize one of the component
it broke minimum for one hour dev app.
200ppl * 10$(minimum) and this price only 200 ppl for ONE THIS ERROR checking
hope it fixed.

**Comment by mikewudev** [comment]
@uharbachou Do you mean that it should throw an error during build/dev instead of only in prod? If so, I totally agree.
