### ISSUE TITLE
Not uploading pasted image from some websources

### ISSUE THREAD

**Issue by albawan** [ckeditor/ckeditor5#1818]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

12.2.0 classic editor build 

## 📋 Steps to reproduce

When copying images from some webpages (not all) instead of the image being uploaded the HTML with links to the source images will be inserted. 

1. Copy an image from [The Guardian](https://www.theguardian.com/) (as an example).
2. Paste this image in the classic editor build, you can try [here](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) 

## ✅ Expected result
Image is uploaded to server
## ❎ Actual result
HTML with references to original file are inserted. 
## 📃 Other details that might be useful
This does not always happen. For example, if you copy an image from the results of Google Images, the image is uploaded.

**Comment by Mgsy** [comment]
Hello, we are aware of this issue. There are already tickets about it, you'll find them here - https://github.com/ckeditor/ckeditor5-easy-image/issues/14 https://github.com/ckeditor/ckeditor5-image/issues/211. Feel free to join the discussion.
