### ISSUE TITLE
continuous image Upload

### ISSUE THREAD

**Issue by littleone2018** [ckeditor/ckeditor5#1822]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor 5

after upload an image, the image button became disabled,  the costumer can not upload the next pic. this is really horrible

**Comment by Mgsy** [comment]
Hello, after an image is uploaded, the selection automatically jumps on it. It's not possible to upload another image while another one is selected. The solution is simple - after upload just put the caret in some other editable block (i.e. paragraph).  

However, if it's not a case, I'll ask you to provide more information about your environment, upload adapter, plugins you use. If it's possible, please write exact steps to reproduce the issue.
