### ISSUE TITLE
Cannot adjust the size of a table cell and align entire table to the left

### ISSUE THREAD

**Issue by GitKou** [ckeditor/ckeditor5#1824]
## Is this a bug report or feature request? (choose one)
Feature request  
1. Adjust a specific cell's width.
2. The entire table is always in center of the page. Is there a way to align the table to the left ?
## 💻 Version of CKEditor
CKEditor5
@ckeditor/ckeditor5-angular
@ckeditor/ckeditor5-build-decoupled-document

## ✅ Expected result
In CKEditor 4, the table cell's width can be adjusted by dragging and dropping, as shown below.

![image](https://user-images.githubusercontent.com/7437397/59667296-0c394c80-91e9-11e9-945a-e948a91ef5ae.png)

## ❎ Actual result
In CKEditor5
![image](https://user-images.githubusercontent.com/7437397/59669294-8919f580-91ec-11e9-81c8-8b15e4f7be21.png)

**Comment by Mgsy** [comment]
Hello, currently CKEditor 5 doesn't have such features, but there are already tickets about those functionalities. You can find them here and track the progress:
1. https://github.com/ckeditor/ckeditor5/issues/1466
1. https://github.com/ckeditor/ckeditor5-table/issues/105
