### ISSUE TITLE
Help to get data

### ISSUE THREAD

**Issue by Olegars** [ckeditor/ckeditor5#1827]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor 5

Hi
I need to get an image's name which I delete
I try to do it the following way:

```js
editor.model.document.on( 'change', () => {
            const changes = editor.model.document.differ.getChanges();

             for ( const entry of changes ) {

                       if ( entry.type === 'remove' && entry.name==='image') {

                                   // the event works rightly
                                   // how can I get an image's name which was deleted?

                        }

                }

        } );
```

**Comment by Mgsy** [comment]
Hi, what do you mean exactly by image name? It would be easier to answer if you describe what you try to achieve.

**Comment by Olegars** [comment]
Hi
> <img src="/assets/images/bg/umbrellas-e935d5c582.jpg"

I delete an image in the ckeditor   but image   remains on the server
I need to get "umbrellas-e935d5c582.jpg
to delete it from server

**Comment by jodator** [comment]
@Olegars Something like this:

```js
editor.editing.view.document.on( 'delete', ( evt, data ) => {
	const selection = editor.model.document.selection;
	const firstPosition = selection.getFirstPosition();
	const nodeAfter = firstPosition.nodeAfter;

	if( nodeAfter && nodeAfter.is( 'image' ) {
		console.log(nodeAfter.getAttribute('src') );
	}
}, { priority:'highest' } );
```

ps.: some other condition checking might be helpful to add, ie check if `selecion.isCollapsed` or get nodeBefore if direction of delete is backward: `data.direction == 'backward'`.

**Comment by Olegars** [comment]
Thanks a lot, Maciej, it works fine
