### ISSUE TITLE
Export to Word file (docx)

### ISSUE THREAD

**Issue by flg717** [ckeditor/ckeditor5#1828]
## Is this a bug report or feature request? (choose one)
🆕 Feature request  

Plugin or service for exporting the editor contents to a docx file.

Similar requirements to ["Export to PDF"](https://github.com/ckeditor/ckeditor5/issues/1161).

---

If you would like to see such an addon for CKEditor 5, please add 👍 to this issue. If you have any additional requirements, please add a comment.

**Comment by Reinmar** [comment]
I converted your ticket into a feature request.

For now, you'd need to use some external HTML to docx converter.

**Comment by gumatias** [comment]
@Reinmar that's very helpful info! Do you have any JS converter to recommend?

**Comment by AnnaTomanek** [comment]
The export to Word (`.docx`) feature has been officially released as stable.

Check the [Export to Word documentation](https://ckeditor.com/docs/ckeditor5/latest/features/export-word.html) to read more about the feature and try it out on the demo.

This is a premium feature. You can [purchase it online here](https://ckeditor.com/pricing/) or [contact us](https://ckeditor.com/contact/) for a tailored offer. Let us know if you have any feedback or questions!

You can also sign up for the [CKEditor Premium Features 30-day free trial](https://orders.ckeditor.com/trial/premium-features) that includes export to Word, export to PDF, real-time collaboration and more.
