### ISSUE TITLE
Cannot copy from word document

### ISSUE THREAD

**Issue by zhyit** [ckeditor/ckeditor5#1829]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

12.2.0

## 📋 Steps to reproduce

1.Download the document, copy it, and paste it in ckeditor

## ✅ Expected result
Copy the contents of the document into the editor
## ❎ Actual result
The replication failed and the console reported the following errors：
     Uncaught TypeError: Cannot read property 'length' of undefined
## 📃 Other details that might be useful
I have added text-related plug-ins, form plug-ins, alignment plug-ins, Title plug-ins to ckeditor.

**Comment by Mgsy** [comment]
Hello, can you share a document you're trying to paste to the editor? Without that, we won't be able to reproduce and investigate the issue.

>I have added text-related plug-ins, form plug-ins, alignment plug-ins, Title plug-ins to ckeditor.

Can you share also your editor configuration? It seems that you have some third-party plugins loaded.

**Comment by zhyit** [comment]
This is my configuration based on the CKEditor Ecosystem Documentation，
I chose to add the plug-in to the build
Reference address：https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html
The document to be copied is the sample document in the ecological document，
The document address is in：  https://ckeditor.com/docs/ckeditor5/latest/features/paste-from-word.html

This is my configuration：
toolbar: [
          "heading",
          "|",
          "alignment",
          "fontFamily",
          "fontSize",
          "fontColor",
          "fontBackgroundColor",
          "bold",
          "italic",
          "bulletedList",
          "numberedList",
          "imageUpload",
          "imageStyle:side",
          "imageStyle:full",
          "insertTable",
          'underline',
          'strikethrough',
          'subscript',
          'superscript'
        ],
        fontSize: {
          options: [
            'default',
            'tiny',
            'default',
            'big',
            'huge',
            8,
            9,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            21,
            24,
            36
          ]
        },
        alignment: {
          options: [ 'left', 'right','center','justify']
        }

**Comment by Mgsy** [comment]
I have checked it with plugins set from your config and everything works fine after pasting the sample document from the documentation. 

Please, make sure that you have all packages updated (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)) and you installed all plugins properly.

Can you tell us which MS Word do you use?

**Comment by zhyit** [comment]
Of course I can, but I've come home now to enjoy my family. Can I reply to you tomorrow? Have a good dream

**Comment by zhyit** [comment]
I used  npm-check-updates to update the version and found that the build was unsuccessful. I reported the following error：
TypeError: this.cliEngine is not a constructor
    at ESLintPlugin.invokeESLint (D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:97:25)
    at ESLintPlugin.getErrors (D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:76:21)
    at ESLintPlugin.onMessage (D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:42:29)
    at Interface.<anonymous> (D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2\plugins\JavaScriptLanguage\jsLanguageServicesImpl\js-language-service.js:105:39)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)

Can you give me some ideas to revise it?

**Comment by zhyit** [comment]
I tried to copy it with the edit box in Demo, but it didn't work.

**Comment by zhyit** [comment]
I tried to use CKEditor Ecosystem Documentation
Demo was copied, but failed. My browser is Google and I use WPS software.

**Comment by Mgsy** [comment]
>My browser is Google and I use WPS software.

Pasting from WPS is not supported. We have a feature request for it -https://github.com/ckeditor/ckeditor5-paste-from-office/issues/58.
