### ISSUE TITLE
Ck Editor initialize issue in angular while page initializing second time after saving

### ISSUE THREAD

**Issue by antonyvimal** [ckeditor/ckeditor5#1830]
I am using the CK Editor in my angular project, it is getting loaded properly for the first page initialized. For the second time control is not getting rendered properly also am getting the error message. Thanks in advance.

I have tried to re-initialized for the second time, but that is not working. I have mentioned the error message received from the screen for your reference.

Uncaught TypeError: Cannot read property 'getSelection' of undefined

**Comment by Mgsy** [comment]
Hello, it's hard to tell anything about your problem without a code sample. Can you share with us your project or code, so we'll be able to reproduce the issue?

**Comment by antonyvimal** [comment]
Thanks for your reply. Below is the code snippet used in the program.

fnCKEdtiorProperty() {
        CKEDITOR.config.toolbarGroups = [
            { name: 'styles', groups: ['styles'] },
            { name: 'basicstyles', groups: ['basicstyles', 'cleanup'] },
            { name: 'clipboard', groups: ['clipboard', 'undo'] },
            { name: 'colors', groups: ['colors'] },
            { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi', 'paragraph'] },
            { name: 'document', groups: ['mode', 'document', 'doctools'] },
            { name: 'insert', groups: ['insert'] },
            { name: 'editing', groups: ['selection', 'find', 'spellchecker', 'editing'] },
            { name: 'links', groups: ['links'] },
            { name: 'forms', groups: ['forms'] },
            { name: 'tools', groups: ['tools'] }
        ];
        CKEDITOR.config.uiColor = '#e5e5e5';
        CKEDITOR.config.image_previewText = ' ';
        CKEDITOR.config.removeDialogTabs = 'image:advanced;image:Link;link:advanced;link:upload';
        CKEDITOR.config.removeButtons = 'PasteText,Flash,Iframe,Source,Save,NewPage,Preview,Print,Templates,'
            + 'Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,Blockquote,CreateDiv,'
            + 'Language,About,ShowBlocks,Styles,Strike,PasteFromWord';
        CKEDITOR.config.removePlugins = 'resize';
        CKEDITOR.config.htmlEncodeOutput = true;
        CKEDITOR.config.fontSize_defaultLabel = '12px';
        CKEDITOR.config.font_defaultLabel = 'Arial';
        CKEDITOR.config.height = 209;
}

**Comment by Mgsy** [comment]
@antonyvimal, thanks for a code, but you use CKEditor 4 and this is CKEditor 5 repository. I saw that you opened an [issue in CKEditor 4 Angular](https://github.com/ckeditor/ckeditor4-angular/issues/38) repository, which is a good place, so the whole discussion should be moved there.
