### ISSUE TITLE
Broken code snippet

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1834]
Not sure if docs or Umberto issue.

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#listening-to-changes

![Screen Shot 2019-06-25 at 3 21 14 PM](https://user-images.githubusercontent.com/545175/60101906-e5d15f00-975c-11e9-8a0d-5c1bec0440f3.png)

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5/blob/c9ac85160893449b00946a3b4dbf4738e060211e/docs/builds/guides/integration/basic-api.md#listening-to-changes

**Comment by pomek** [comment]
(missing code block \`\`\`)
