### ISSUE TITLE
 如何支持tiff格式图片上传 How to support TIFF format picture upload

### ISSUE THREAD

**Issue by JForkYao** [ckeditor/ckeditor5#1836]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
Hello, currently it's not possible to upload `*.tiff` files. However, we created a feature request for this case. You can give it  👍 to boost its popularity and track progress [here](https://github.com/ckeditor/ckeditor5-image/issues/295).
