### ISSUE TITLE
Add support for setting table cell background color

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1841]
CKEditor 4 allowed the user to set the background color for table cells. Other applications like Google Docs offer it too:

<img width="239" alt="Screen Shot 2019-06-27 at 5 21 27 PM" src="https://user-images.githubusercontent.com/545175/60278669-20273180-9900-11e9-80cd-98b47ba25699.png">

This ticket is created to track the demand for this feature. If you need this in your project please add 👍to this issue.

**Comment by jswiderski** [comment]
I believe this issue can be treated as a part of #3287
