### ISSUE TITLE
Update option in plugin

### ISSUE THREAD

**Issue by MuTaToR08** [ckeditor/ckeditor5#1849]
## Is this a bug report or feature request? (choose one)
Other

## 💻 Version of CKEditor

12.2

## 📋 Steps to reproduce

It is required in the plugin to respond to a change in the editor config, is it possible to track the change?

**Comment by Mgsy** [comment]
Hi, can you describe your case more precisely? What do you want to achieve?

**Comment by MuTaToR08** [comment]
I create a plugin "Suggestions".
His input data is a list of variables and a list of types.
And I want to make it so that these lists are updated inside the plugin, if the editor has updated the config

**Comment by TheHunterDog** [comment]
> I create a plugin "Suggestions".
> His input data is a list of variables and a list of types.
> And I want to make it so that these lists are updated inside the plugin, if the editor has updated the config

So if i understand correctly. You want to edit var's in an js file with input from the user ?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by MuTaToR08** [comment]
@TheHunterDog, right. example create function refreshConfig, which was called when updating the config.

**Comment by jodator** [comment]
> It is required in the plugin to respond to a change in the editor config, is it possible to track the change?

I think that no one reported that to us. In short, we do not re-read the config in most of the features (if not all of them). The `Config` class is non-observable and, for most of the cases, it doesn't make sense to update the configuration of a plugin in the run-time. For instance configuration of a plugin defines its conversion - which must be the same when the editor is run.

If you want to react on changes in lists you can use [`Collection`](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_collection-Collection.html) class from ckeditor5-utils inside your plugin.

**Comment by MuTaToR08** [comment]
So I must to input the config, a [Collection](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_collection-Collection.html) and not a native object?

**Comment by jodator** [comment]
@MuTaToR08 no - you can create a collection inside your plugin and use it without a config. You don't have the information that the config was updated. 

You can always call a method of your plugin from the outside like this:
`editor.pugins.get( 'MyPlugin' ).doSomething()` if your plugin defines `static get pluginName()` getter.
