### ISSUE TITLE
Text transformation throws an error when undoing between block elements

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1850]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-typing/tests/manual/texttransformation.html
2. After `(tm` press enter.
3. Type `)`
4. Move the caret left (before the typed character).
5. Backspace.
6. Move the caret right (after the typed character).
7. Type space.
8. Backspace.
9. Undo all the changes.

## ✅ Expected result

```js
ckeditorerror.js:51 Uncaught CKEditorError: merge-operation-target-position-invalid: Merge target position is invalid.
```

## ❎ Actual result

No error should be thrown.

## 📃 Other details that might be useful

Reproducible on Firefox and Chrome.

**Comment by jodator** [comment]
WFM at the current master. Probably fixed by https://github.com/ckeditor/ckeditor5-typing/issues/214 or https://github.com/ckeditor/ckeditor5-typing/issues/208.
