### ISSUE TITLE
In FCKEditor the created HTML output will be in an iframe How can we get the same functionality with CKEditor5.

### ISSUE THREAD

**Issue by venkataramanagovindu** [ckeditor/ckeditor5#1858]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by venkataramanagovindu** [comment]
please help me out in this.

**Comment by Mgsy** [comment]
Hello, can you describe more precisely what do you want to achieve?

**Comment by venkataramanagovindu** [comment]
in the below image the code is generated by FCKeditor
![FCKEditor](https://user-images.githubusercontent.com/39056356/60660502-8ae2ea80-9e75-11e9-8778-6eff1bd169e4.PNG)
in this image, the code is generated by 
![CKEditor5](https://user-images.githubusercontent.com/39056356/60660520-933b2580-9e75-11e9-9c3f-41c24bb23709.PNG)


in FCKEditor the code is generated in an iframe so that there is no problem of ignoring tags like "<Html><Head><body> and <!Doctype>"

am getting HTML which includes html,head and body when I tried to insert that code in CK5 it's ignoring tags like html,body and head

**Comment by Reinmar** [comment]
There's no support for iframed-editables in CKEditor 5. See https://github.com/ckeditor/ckeditor5/issues/665. 

Due to that, there is no support for full HTML editing. If you have legacy content, you need to figure out the way to pre-process it in such a way to make it compatible with CKEditor 5.

**Comment by venkataramanagovindu** [comment]
![Doctype](https://user-images.githubusercontent.com/39056356/60676031-76b1e400-9e9b-11e9-8780-75341aba0d5c.PNG)
How to give HTML code to CKEditor4 having !Doctype,html,head,body and script tags

I used the below code but it working only with normal tag(div,p) and not with the script tags
![I_Used](https://user-images.githubusercontent.com/39056356/60676255-166f7200-9e9c-11e9-97b6-39a4b07d8469.PNG)
