### ISSUE TITLE
properties undefined, regular build on ClassicEditor

### ISSUE THREAD

**Issue by Romaxx** [ckeditor/ckeditor5#1859]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

@ckeditor/ckeditor5-editor-classic: 12.1.1
@ckeditor/ckeditor5-dev-webpack-plugin: 8.0.1
@ckeditor/ckeditor5-dev-utils: 12.0.1

## 📋 Steps to reproduce

1. Build with webpack (Encore)
2. Run with Chrome 75

## ✅ Expected result
Start editor
## ❎ Actual result
js throw:
```
Composer.js:289 TypeError: Cannot read property 'get' of undefined
    at ClassicEditor.set [as state] (observablemixin.js:77)
    at ClassicEditor.set (observablemixin.js:97)
    at new Editor (editor.js:123)
    at new ClassicEditor (classiceditor.js:63)
    at classiceditor.js:188
    at new Promise (<anonymous>)
    at Function.create (classiceditor.js:187)
    at Composer.render (Composer.js:284)

line 77 in observablemixin.js, properties is not defined
const oldValue = properties.get( name );

properties appear in line 47 in the same file
const properties = this[ observablePropertiesSymbol ];
```

**Comment by Reinmar** [comment]
I've just built an editor and it was working fine.

But we're right now during the release process, so perhaps you've been running `npm install` while we've been releasing packages and might've gotten some new and some old. I propose to refresh your installation.

**Comment by Reinmar** [comment]
I'll close this ticket for now. Let me know if the problem still exists.
