### ISSUE TITLE
Question: delay between releases and downloads

### ISSUE THREAD

**Issue by toxpal** [ckeditor/ckeditor5#1860]
Not really an issue or problem, but I'd like to know why there is such a delay between release of new version on Github and options to download new version at Downloads page? Usually, it takes at least a few days before new version is available at https://ckeditor.com/ckeditor-5/download/

**Comment by Reinmar** [comment]
It makes releasing things easier for us – there are more than a dozen people involved in each release process, testing, proof-reading, reviewing docs, writing blog posts, preparing graphics, etc. Additionally, some of us are involved in releases of more than one project. By separating the "code release" from "social release" we make sure that no one is blocked by people like me who are involved in too many of these activities :D

At the same time, it allows us shipping the code as soon as it's ready, meaning that the community can use it without waiting until we've got all the materials ready. 

The downside is, of course, some confusion created by this, so we try to have the social releases as soon as possible. Right now it may take us from 1-2 weeks. I hope we'll get better with time :)

**Comment by toxpal** [comment]
Thanks, makes sense.
