### ISSUE TITLE
VM357:2 Uncaught ReferenceError: ClassicEditor is not defined

### ISSUE THREAD

**Issue by Yongest** [ckeditor/ckeditor5#1861]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Yongest** [comment]
VM357:2 Uncaught ReferenceError: ClassicEditor is not defined

**Comment by Mgsy** [comment]
Hello, while creating a ticket, please always provide a meaningful title and detailed description (about your environment, steps to reproduce, actual/expected result). Without that information, we can't help you.
