### ISSUE TITLE
README - a wrong number of ready-to-use builds

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1862]
## Is this a bug report or feature request? (choose one)

Other

## 📃 Other details that might be useful

Shouldn't be five?

```diff
-CKEditor 5 is distributed as four ready-to-use rich text editor builds which you can install from npm.
+CKEditor 5 is distributed as five ready-to-use rich text editor builds which you can install from npm.
```

**Readme:**
![image](https://user-images.githubusercontent.com/2270764/60727399-12942c00-9f3e-11e9-816e-f34316fa61f6.png)

**Docs:**
![image](https://user-images.githubusercontent.com/2270764/60727367-04461000-9f3e-11e9-9b48-b6a3fd04e77e.png)

**Comment by Reinmar** [comment]
Waiting for a PR, @pomek ;)

**Comment by Reinmar** [comment]
@mlewand proposes that we should use "several" instead of "five" so we don't have to update it every now and then.
