### ISSUE TITLE
Simple copy-paste not working

### ISSUE THREAD

**Issue by Romaxx** [ckeditor/ckeditor5#1863]
🐞 Bug report 
## 💻 Version of CKEditor
Last Version of DecoupledEditor (12.2.0)
## 📋 Steps to reproduce
1. copy text in editor
2. paste text in editor
## ✅ Expected result
pasting the text
## ❎ Actual result
```
eventName.indexOf is not a function
at getCallbacksForEvent (emittermixin.js:588)
    at Document.fire (emittermixin.js:189)
    at Document.handleInput (clipboardobserver.js:51)
    at Document.fire (emittermixin.js:207)
    at ClipboardObserver.fire (domeventobserver.js:96)
    at ClipboardObserver.onDomEvent (clipboardobserver.js:74)
    at ProxyEmitter.listenTo.useCapture (domeventobserver.js:79)
    at ProxyEmitter.fire (emittermixin.js:207)
    at HTMLDivElement.domListener (emittermixin.js:235)

eventName is equal to EventInfo {source: Document, name: "clipboardInput", path: Array(0), stop: , off: } when bug occur
```

**Comment by Mgsy** [comment]
Hi, I've checked your case and copy-paste works fine in the last version of decoupled editor (in other builds as well). Please, make sure that you installed it properly and all the dependencies are updated (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

Some useful documentation links:
* [Installation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installation.html)
* [Basic API](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html)
* [Building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)

**Comment by Romaxx** [comment]
Hello,
all dependencies are updated, I build the editor with webpack 4,
editor load without problems nor warnings (appart duplicated error from module "undefined" reported issue #1821), debug at getCallbacksForEvent() function emittermixin.js:581 show that events works (change:isFocused, change:isRenderingInProgress, _keydown:1114179 etc..) but when I paste text, it continue to throw the error.

**Comment by Mgsy** [comment]
Thanks for the information. Can you create a repository with your project where the problem exists, so we'll be able to check the behaviour live?

**Comment by Romaxx** [comment]
Hi @Mgsy now it's works, 
I have upgraded to last packages (published 2 days ago).
I dont know if it was a core/ui/utils/essentials problem.

For info:
From versions (paste not working):
` "@ckeditor/ckeditor5-alignment": "^11.1.2",
        "@ckeditor/ckeditor5-autoformat": "^11.0.3",
        "@ckeditor/ckeditor5-autosave": "^11.0.3",
        "@ckeditor/ckeditor5-basic-styles": "^11.1.2",
        "@ckeditor/ckeditor5-block-quote": "^11.1.1",
        "@ckeditor/ckeditor5-core": "^12.2.0",
        "@ckeditor/ckeditor5-easy-image": "^11.0.3",
        "@ckeditor/ckeditor5-editor-balloon": "^12.2.0",
        "@ckeditor/ckeditor5-editor-classic": "^12.1.2",
        "@ckeditor/ckeditor5-editor-decoupled": "^12.2.0",
        "@ckeditor/ckeditor5-editor-inline": "^12.2.0",
        "@ckeditor/ckeditor5-essentials": "^11.0.3",
        "@ckeditor/ckeditor5-font": "^11.2.0",
        "@ckeditor/ckeditor5-heading": "^11.0.3",
        "@ckeditor/ckeditor5-image": "^13.1.1",
        "@ckeditor/ckeditor5-link": "^11.1.0",
        "@ckeditor/ckeditor5-list": "^12.0.3",
        "@ckeditor/ckeditor5-paragraph": "^11.0.3",
        "@ckeditor/ckeditor5-table": "^13.0.1",
        "@ckeditor/ckeditor5-theme-lark": "^14.1.0",
        "@ckeditor/ckeditor5-ui": "^13.0.1",
        "@ckeditor/ckeditor5-upload": "^11.1.0",
        "@ckeditor/ckeditor5-utils": "^13.0.0",`

to versions (working):
`"@ckeditor/ckeditor5-alignment": "^11.1.3",
        "@ckeditor/ckeditor5-autoformat": "^11.0.4",
        "@ckeditor/ckeditor5-autosave": "^11.0.4",
        "@ckeditor/ckeditor5-basic-styles": "^11.1.3",
        "@ckeditor/ckeditor5-block-quote": "^11.1.2",
        "@ckeditor/ckeditor5-core": "^12.2.1",
        "@ckeditor/ckeditor5-easy-image": "^11.0.4",
        "@ckeditor/ckeditor5-editor-balloon": "^12.2.1",
        "@ckeditor/ckeditor5-editor-classic": "^12.1.3",
        "@ckeditor/ckeditor5-editor-decoupled": "^12.2.1",
        "@ckeditor/ckeditor5-editor-inline": "^12.2.1",
        "@ckeditor/ckeditor5-essentials": "^11.0.4",
        "@ckeditor/ckeditor5-font": "^11.2.1",
        "@ckeditor/ckeditor5-heading": "^11.0.4",
        "@ckeditor/ckeditor5-image": "^13.1.2",
        "@ckeditor/ckeditor5-link": "^11.1.1",
        "@ckeditor/ckeditor5-list": "^12.0.4",
        "@ckeditor/ckeditor5-paragraph": "^11.0.4",
        "@ckeditor/ckeditor5-table": "^13.0.2",
        "@ckeditor/ckeditor5-theme-lark": "^14.1.1",
        "@ckeditor/ckeditor5-ui": "^13.0.2",
        "@ckeditor/ckeditor5-upload": "^11.1.1",
        "@ckeditor/ckeditor5-utils": "^13.0.1",`

Thanks for interest.
