### ISSUE TITLE
Config filebrowserImageBrowseUrl Ckfinder in [Ckeditor 5+Angular 7]

### ISSUE THREAD

**Issue by skipperhoa** [ckeditor/ckeditor5#1864]
I want config filebrowserImageBrowseUrl Ckinder in [Ckeditor 5+Angular 7]
I have upload image success in Ckeditor5+Angular 7.

https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html

**Comment by Reinmar** [comment]
`filebrowserImageBrowseUrl` is CKEditor 4's configuration option. Refer to https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html to learn more about image upload in CKEditor 5.
