### ISSUE TITLE
All list levels in CKEditor 5 demos use the same marker

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1866]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

iteration 25

## 📋 Steps to reproduce

1. Just open `/docs/ckeditor5/latest/features/indent.html`
2. Insert a list.
1. Use the indent plugin to nest part of a list.

## ✅ Expected result

The markers should be different for each nesting level.

![image](https://user-images.githubusercontent.com/5353898/60801706-c03e4f80-a177-11e9-8d77-06c25c2944b2.png)

## ❎ Actual result

All markers are the same.

![image](https://user-images.githubusercontent.com/5353898/60801647-a1d85400-a177-11e9-9e34-7c50ba1d0276.png)

**Comment by dkonopka** [comment]
This issue is related to our documentation stylesheet, it will be handled there - in the another repository.
