### ISSUE TITLE
Cant edit widget after seeing the source code

### ISSUE THREAD

**Issue by TheHunterDog** [ckeditor/ckeditor5#1867]
🐞 Bug report  

Version 4.11.4

## 📋 Steps to reproduce

1. Using a custom widget and using it 
2. Switching to the source code in the editor 

## ✅ Expected result

To still double click and edit the widget

## ❎ Actual result

The Editor sees it as text, not as an widget

## 📃 Other details that might be useful

I am using it on drupal 7

**Comment by Reinmar** [comment]
This is CKEditor 5's issue tracker. See https://github.com/ckeditor/ckeditor-dev/ for CKEditor 4's one.

**Comment by TheHunterDog** [comment]
Whooops

**Comment by Reinmar** [comment]
No problem :) Have a nice day!
