### ISSUE TITLE
Override default templates

### ISSUE THREAD

**Issue by jkaffrey** [ckeditor/ckeditor5#1868]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

CKEditor 5, custom build

## 📃 Other details that might be useful

Currently I am utilizing the comments plugin and would like to add some buttons / change the default appearance of the comments for the plugin (beyond just CSS changes). Additionally, I was hoping to add some extended functionality to the plugin. I'm not sure if this is possible, if it is, it eludes me. If it isn't, then I'll have to change this to a feature request.

**Comment by Reinmar** [comment]
Hi! Comments are a part of the commercial offering, while this issue tracker covers the open source part of the project. Please contact the team through the [support channel](https://ckeditor.com/contact). Thank you!
