### ISSUE TITLE
When the document content is empty, insert the image directly, the image is always in the focus state, continue to enter text, the image disappears

### ISSUE THREAD

**Issue by taurus888** [ckeditor/ckeditor5#1869]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other
    this is a bug report

## 💻 Version of CKEditor
   CKEditor5

## 📋 Steps to reproduce

1. When the document content is empty, insert the image directly.
2.Then I want to insert the image and continue editing the text.
3.But the image remains in focus, and if you continue typing, the image disappears.

## ✅ Expected result
    1. I want the image to be in focus when I click on it.
    2. I want to insert the image and then continue to edit the text just like I did in CKEditor4.
   
![TIM截图20190709161709](https://user-images.githubusercontent.com/42331368/60871835-286b5f00-a266-11e9-9e41-298dec32d47a.jpg)

## ❎ Actual result
![TIM截图20190709161533](https://user-images.githubusercontent.com/42331368/60871842-2d301300-a266-11e9-83bf-7644b2609d93.jpg)

**Comment by Mgsy** [comment]
Hello, you should create a new paragraph if you want to continue editing. You can achieve it by pressing <kbd>Enter</kbd> while an image is focused to insert a paragraph after the image or <kbd>Shift + Enter</kbd> to insert a paragraph before the image.
