### ISSUE TITLE
Infinite unordered list on enter

### ISSUE THREAD

**Issue by code-chris** [ckeditor/ckeditor5#1871]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor
Based on @ckeditor/ckeditor5-build-classic 12.3.0 (also reproducible in current demo (https://ckeditor.com/ckeditor-5/demo/)

## 📋 Steps to reproduce

1. Prepare the editor with this data:
```<div class="ck ck-content ck-editor__editable ck-rounded-corners ck-editor__editable_inline ck-blurred" role="textbox" aria-label="Rich Text Editor, main" contenteditable="true" style="min-height: 685px;"><p>Some text</p><ul><li>Topic 1</li><li>Topic 2</li><li><br data-cke-filler="true"></li><li><br data-cke-filler="true"></li><li><br data-cke-filler="true"></li></ul>```
2. When hitting enter after "Topic 1" or "Topic 2", a new list-item appears 👍. Hitting enter again on the new item, ends the unordered list formatting. 👍 (Double enter ends the list)
3. When hitting enter in one of the following lines with a list-symbol, the list is always extended by one item but never ended.

## ✅ Expected result
A unordered list always ends on hitting enter on a empty list-item line.

## ❎ Actual result
The unordered list is extended always by one new item. This can only be fixed, by manual removing the formatting through the toolbar.

## 📃 Other details that might be useful
From HTML-side this can be fixed, if the two `<br>` Tags inside the `li` are removed. Then the behavior is as expected.

---

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by Mgsy** [comment]
Hello, did you achieve your content state by using the editor or only by using `editor#setData`? I mean list items with `<br>`, because if you'll try to add `<br>` to an empty list item, it will be removed.

**Comment by Mgsy** [comment]
@Reinmar @mlewand, what do you think about this behaviour?

**Comment by mlewand** [comment]
The original report is not entirely clear to me. @code-chris My assumption is that in 3rd step you're placing your caret in a list item which has a break line, and your caret is before the break line. Thus pressing enter results with adding extra list items.

Depicted by following (where `^` denotes the caret):

```
<li>^<br></li>
```

In that case 

I see that this behavior is incompatible with MS Word as it does in fact

* MS Word - incompatible - it closes the list item and moves break line to the a newly created paragraph. Same thing goes for other invisible characters like non-breaking spaces and regular spaces.
* Gdocs - compatible - they treat it exactly the same way as us

It's a valid feature request, but I'd like to understand how many users really expect this kind of behavior.

**Comment by code-chris** [comment]
> My assumption is that in 3rd step you're placing your caret in a list item which has a break line, and your caret is before the break line

Correct!

I tried this behavior in MS Word 2016. It's the same behavior as here. Word creates new list items when hitting enter (caret placed before line break)

So if the behavior should be similar to Word or other tools, it looks correct to me...

The problem is, that it confuses the end-user if he don't know this line-break behavior (including me 😉)

I will discuss this topic today with my colleagues and close this issue if not needed anymore. Thanks for your time!

**Comment by code-chris** [comment]
I discussed this topic internally, and we are fine with the current behavior. So I'll close this.
Thanks for your time!
