### ISSUE TITLE
Language error webpack

### ISSUE THREAD

**Issue by maytinhdibo** [ckeditor/ckeditor5#1872]
🐞 Bug report  
![image](https://user-images.githubusercontent.com/6669725/60941478-8604b780-a309-11e9-8c0d-7858391f33fc.png)
Language display is wrong when I config webpack.
```
plugins: [
      new CKEditorWebpackPlugin( {
        // Main language that will be built into the main bundle.
        language: 'en',

        // Additional languages that will be emitted to the `outputDirectory`.
        // This option can be set to an array of language codes or `'all'` to build all found languages.
        // The bundle is optimized for one language when this option is omitted.
        additionalLanguages: 'all',
    } )

```

**Comment by Mgsy** [comment]
cc @ma2ciek

**Comment by ma2ciek** [comment]
Hi @maytinhdibo.

Are you sure that both (the `ckeditor.js` and translations) comes from the same build? The translations aren't deterministic so two builds will create two different translation maps. More information would be welcome.

**Comment by maytinhdibo** [comment]
> Hi @maytinhdibo.
> 
> Are you sure that both (the `ckeditor.js` and translations) comes from the same build? The translations aren't deterministic so two builds will create two different translation maps. More information would be welcome.

It's my package.json. I hope you can create example full code for CKeditor like some same project.
 ```
"@ckeditor/ckeditor5-alignment": "^11.1.2",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.2",
    "@ckeditor/ckeditor5-block-quote": "^11.1.1",
    "@ckeditor/ckeditor5-build-classic": "^12.3.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.2",
    "@ckeditor/ckeditor5-essentials": "^11.0.3",
    "@ckeditor/ckeditor5-font": "^11.2.0",
    "@ckeditor/ckeditor5-heading": "^11.0.3",
    "@ckeditor/ckeditor5-highlight": "^11.0.3",
    "@ckeditor/ckeditor5-image": "^13.1.1",
    "@ckeditor/ckeditor5-link": "^11.1.0",
    "@ckeditor/ckeditor5-list": "^12.0.3",
    "@ckeditor/ckeditor5-paragraph": "^11.0.3",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-ui": "^13.0.1",
    "@ckeditor/ckeditor5-upload": "^11.1.0",
```

**Comment by ma2ciek** [comment]
> It's my package.json. I hope you can create example full code for CKeditor like some same project.

This, actually, isn't needed. The question is how you rebuild the editor, do you add proper translation files to the editor, do your browser cache the old translation files (try `ctrl + shift + r`), etc.

**Comment by maytinhdibo** [comment]
> > It's my package.json. I hope you can create example full code for CKeditor like some same project.
> 
> This, actually, isn't needed. The question is how you rebuild the editor, do you add proper translation files to the editor, do your browser cache the old translation files (try `ctrl + shift + r`), etc.
![image](https://user-images.githubusercontent.com/6669725/60958524-b14ecd00-a330-11e9-9acb-affd0577e92a.png)

I'm hard reload my browser and change additionalLanguages: 'all' on/off, this map change to different language map.

**Comment by ma2ciek** [comment]
Could you show how you add translations to your HTML page?

**Comment by maytinhdibo** [comment]
> Could you show how you add translations to your HTML page? And whether you use only original (English) translations?
When I remove additionalLanguages it will display english 
I'm using ReactJS, and `import '@ckeditor/ckeditor5-build-classic/build/translations/vi';`. In my config, language is `language: 'vi'`, but it just translates link plugin.

**Comment by maytinhdibo** [comment]
> Could you show how you add translations to your HTML page? And whether you use only original (English) translations?


When I remove additionalLanguages it will display english
I'm using ReactJS, and import '@ckeditor/ckeditor5-build-classic/build/translations/vi';. In my config, language is language: 'vi', but it just translates link plugin.

**Comment by ma2ciek** [comment]
> import '@ckeditor/ckeditor5-build-classic/build/translations/vi'

That's why you're having the error. You should import translation from your custom build.

**Comment by maytinhdibo** [comment]
> > import '@ckeditor/ckeditor5-build-classic/build/translations/vi'
> 
> That's why you're having the error. You should import translation files from your custom build. Each build creates a different translation map.

Okay, thanks you. But I hope CKEditor have some examples for ReactJS, Angular or js in codepen, codesandbox,...etc. It's best way to understand your documents.

**Comment by ma2ciek** [comment]
We can't have examples on the Codepan or similar sites because we use webpack with a set of custom loaders and plugins that can't be used on these sites.
