### ISSUE TITLE
insert-operation-position-invalid

### ISSUE THREAD

**Issue by acanshul** [ckeditor/ckeditor5#1873]
Unable to connect on collab mode

Error:: realtimecollaborationclient-init: Connecting with the server resulted in error.", error: CKEditorError: insert-operation-position-invalid: Insertion position is invalid

**Comment by Mgsy** [comment]
Hello, collaboration features are our commercial plugins and this issue tracker covers the open-source part of the project. Please, use [the support channel](https://ckeditor.com/contact) to reach our team.
