### ISSUE TITLE
Cannot type after MathType's Math equation

### ISSUE THREAD

**Issue by venkateshwarans** [ckeditor/ckeditor5#1874]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

CKEditor5 V12.1.0
Custom Build Package - @project-sunbird/ckeditor-build-font

## 📋 Steps to reproduce
Video to reproduce the issue - https://imgur.com/NA9pz3Q
1. Open the editor 
2. Enter some text. (enter `space` after text)
3. Click on MathType Plugin
4. Enter any equation. Click Ok. 
5. Now try typing. 

## ✅ Expected result
1. Should be able to type.

## ❎ Actual result
2. Unable to type.

## 📃 Other details that might be useful
Related Issue - https://github.com/ckeditor/ckeditor5/issues/1049

---

If you'd like to see this fixed sooner, add 👍 to this post.

**Comment by Mgsy** [comment]
I can confirm this issue.

**Comment by mlewand** [comment]
A thing that i noted here is that the key for this issue to occur is adding a *regular space* before the MathType widget.

Exception occurs if you set the editor content like that: `editor.setData( '<p>Hello world! <math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;<msqrt><mn>2</mn>&nbsp;</msqrt></math></p><p>Sample text</p>' )`

But it doesn't occur if you explicitly use `&nbsp;`, like so: `editor.setData( '<p>Hello world!&nbsp;<math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;<msqrt><mn>2</mn>&nbsp;</msqrt></math></p><p>Sample text</p>' )`

**Comment by adityaism** [comment]
is this fixed?

**Comment by Mgsy** [comment]
>is this fixed?

Unfortunately, this is still the issue, however, Wiris (author of the MathType) works on improvements in the plugin and after the release, this one (and many others) should be fixed.

**Comment by akhilrkeyvalue** [comment]
Hi, can I please know when the next release is going to be and when the bug will be fixed?

**Comment by FilipTokarski** [comment]
This issue is fixed in the new MathType version 7.19.0
