### ISSUE TITLE
Img not closed

### ISSUE THREAD

**Issue by BenoitChery** [ckeditor/ckeditor5#1876]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

1.insert an image
2.the generated file contains <img> not closed, isn't that mandatory in xhtml ?

## ✅ Expected result
<img src="" />

## ❎ Actual result
<img src="">
## 📃 Other details that might be useful
Can we configure this ?

**Comment by Mgsy** [comment]
Hello, indeed, tags should be closed in XHTML, but CKEditor 5 is based on HTML and the output generated by the editor is a valid HTML.

**Comment by ma2ciek** [comment]
Is the https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_dataprocessor_xmldataprocessor-XmlDataProcessor.html what you're looking for?
