### ISSUE TITLE
Custom tag like a meta tag

### ISSUE THREAD

**Issue by kosaa** [ckeditor/ckeditor5#1877]
Hello
I want to create my own tag with behavior similar to <meta> tag. I mean that neighboring elements wont be merged into one.

Is there any example how can I get that result? Now I don't know what options I need to pass to register method.

**Comment by Mgsy** [comment]
Hello, can you be more specific in your description of expected behaviour? What kind of tag do you want to introduce?

Basically, all new elements should be registered in the schema and have proper model <--> view converters. Please, take a look at our documentation. After reading these materials, you'll be able to allow new elements in the editor:

* [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)
* [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html)
* [Conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html)

**Comment by kosaa** [comment]
when I add div tag, and two tags are inlined, ckeditor merge this two tags into one, I need to set behaviour identically to mark tag

in example:
when I got that html structure:
```
<mytag class="mytag-class-a">test</mytag>
<br>
<mytag class="mytag-class-b">test</mytag>
```

and I remove <br> (with backspace), I expect to that html structure

```
<mytag class="mytag-class-a">test</mytag><mytag class="mytag-class-b">test</mytag>
```

but now ckeditor merge this two tags into one

```
<mytag class="mytag-class-a">testtest</mytag>
```

**Comment by jodator** [comment]
this probably depends on the model configuration - schema & conversion. It looks like you store both tags the same way in the model - but we need to see how do you define those tags (I see that those should be different values in the model as those tags have different classes).

Note that if you'd wish to separate similar elements from merging in the view there's [id attribute](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_attributeelement-AttributeElement.html#member-id) which you can set in the conversion when [creating attribute element](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-createAttributeElement).

**Comment by kosaa** [comment]
here is the code I use

```
editor.model.schema.register('mytag', {
		inheritAllFrom: '$block',
		allowAttributes: ['id', 'customtag']
	}
);

editor.conversion.elementToElement({model: 'mytag', view: 'mytag'});
editor.conversion.attributeToAttribute({model: 'id', view: 'id'});
editor.conversion.attributeToAttribute({model: 'customtag', view: 'customtag'});

editor.data.set('<p><mytag id="idA">wordA</mytag> lotem ipsum <mytag id="idB">wordB</mytag></p>');
```

in this example tag mytag isnt linlined, when I set isInline to true content isnt shown

**Comment by jodator** [comment]
For inline elements, those attributes have to be defined on `$text`:

```js
editor.model.schema.extend( '$text', {
	allowAttributes: [ 'id', 'customtag' ]
} );
```

and the conversion should be defined as:
```js
editor.conversion.for( 'upcast' ).attributeToAttribute( {
	model: 'customtag',
	view: {
		key: 'data-customtag',
		value: /[\s\S]+/
	}
} );
editor.conversion.for( 'downcast' ).attributeToElement( {
	model: 'id',
	view: ( modelAttributeValue, viewWriter ) => {
		return viewWriter.createAttributeElement( 'mytag', {
			id: modelAttributeValue
		} );
	}
} );
```

**Comment by kosaa** [comment]
works, thank you!
