### ISSUE TITLE
 Why I cannot write

### ISSUE THREAD

**Issue by hhlingyoko** [ckeditor/ckeditor5#1878]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

CKEditor 5

## 📋 Steps to reproduce

I wrote a plug-in for inserting code，I can insert code in the editor but cannot write。
I want to know why I cannot write? Thanks.

This is my HTML code after clicking the insert code button。

![image](https://user-images.githubusercontent.com/16332083/61018232-a2b3f480-a3c8-11e9-9e96-63194b36a60f.png)

**Comment by Mgsy** [comment]
Hello, we can't tell you anything about your problem without looking into your code. Please, share your plugin code and CKEditor 5 config. 

And one question to clarify - you can't type in the editor or in your code element?
