### ISSUE TITLE
[Firefox] Inline Editor crashes after trying to fill empty bullet list elements after reload

### ISSUE THREAD

**Issue by daveish** [ckeditor/ckeditor5#1882]
🐞 Bug report
Version: 11.0.1

## 📋 Steps to reproduce

1. Add empty bullet list elements to the editor
2. Reload the page, the editor is on (with the persisted list elements)
3. Try to add text to the empty list elements

## ✅ Expected result

The editor works as expected and you can do other cool stuff.

## ❎ Actual result

The console returns the following error: 
`TypeError: n.viewItem.parent is null`

**Comment by Mgsy** [comment]
Hello, I'm not able to reproduce your issue. Can you give us more details or a live sample?

P.S. I can see that you're using CKEditor v.11.0.1 which is old and might contain some bugs. The latest released version is 12.3.1, please update your editor (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)) and check whether you can reproduce it.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
