### ISSUE TITLE
identify multiple ckeditor in a form

### ISSUE THREAD

**Issue by wings77** [ckeditor/ckeditor5#1883]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by wings77** [comment]
how to identify ckeditor when there are several in the form, something like:

        ```
editor1.setData( 'text1' );
        editor2.setData( 'text2' );
        editor1.setData( 'text3' );

```

**Comment by Mgsy** [comment]
I don't know your use case, but you can assign each editor instance to different variables. Please, see a code below:

```js
ClassicEditor
	.create( document.querySelector( '#editor1' )
	.then( editor => {
		window.editor1 = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );

ClassicEditor
	.create( document.querySelector( '#editor2' )
	.then( editor => {
		window.editor2 = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );
```

Above sample code will give you access to `editor1` and `editor2` in your browser console.
