### ISSUE TITLE
Upload images on submit

### ISSUE THREAD

**Issue by luaVolk** [ckeditor/ckeditor5#1884]
Is there a way to only upload the images to the server only when the form is submitted? I have tried looking for this but found nothing.

**Comment by Mgsy** [comment]
Hello, can you be more specific in your question and give some example of your use case?

**Comment by luaVolk** [comment]
Right now in all the examples ive seen the image gets uploaded immediately once you open/paste/drop it in the editor. I would like to wait until the form is submitted and send everything at once like a regular form.

I would prefer to not have to deal with files that werent used (when deleted in the editor or if the form itself is never submitted) in the backend.

**Comment by Mgsy** [comment]
@oleq, is it possible to achieve this behaviour right now?

**Comment by oleq** [comment]
We don't have this kind of feature ATM. 

Is this even technically possible? I mean, is there any other WYSIWYG editor allowing that? 

Seems like awfully risky business, waiting minutes (hours?) for the upload. What if all (let's say 10+ images) are rejected by the server at the same time (too big, too small, bad extension, whatever) on submit? Is the content saved then? If there's a full-page reload, the images are lost.

**Comment by KatuGT** [comment]
what about deleting the image from the database when you remove the image from you  WYSIWYG editor ?
