### ISSUE TITLE
How do we observe keydown events if the editor is disabled (i.e. editor.isReadOnly == true) ?

### ISSUE THREAD

**Issue by ysct** [ckeditor/ckeditor5#1885]
## Is this a bug report or feature request? (choose one)

Feature request

## 💻 Version of CKEditor

CKEditor 5, Decoupled Editor

## 📃 Details
```
editor.editing.view.document.on( 'keydown', event => {
    console.log('keydown fired');
});
```

It appears that `keydown` events will only fire if editor is not disabled.  How do we observe `keydown` events if `editor.isReadOnly == true`? 

This would be useful from a UX perspective, if we could prompt users as they attempt to type something into a disabled field.

Thanks.

https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html#event-event:keydown

**Comment by Mgsy** [comment]
cc @oleq

**Comment by oleq** [comment]
When you switch `editor.isReadOnly` to `false`, the editable loses focus (`editor.ui.focusTracker.isFocused` is `false`). The focus goes somewhere else, usually to the body (see `window.document.activeElement`). You can't simply listen to keyboard events in that case, like you mentioned. 

I suppose you should listen to events on `<body>` in that case. You can use the native DOM API (`addEventListener()`) to CKEditor API to do that 

```js
editor.ui.view.listenTo( document.body, 'keydown', ( evt ) => {
	if ( editor.isReadOnly ) {
		console.log( 'UI keydown', evt );
    }
} );
```

But keep in mind that you'll not be able to tell:
* if the focus moved to body from the editor as a result of switching `isReadOnly` to `true`,
* if the editor was, for instance, always read–only and the user just navigated the web page and did whatever they did there (like filling some other fields, etc.)

A better idea would be styling the editor in such way it leaves no doubt as to what happened. Check out `.ck.ck-editor__editable_inline[contenteditable="false"]`.

**Comment by ysct** [comment]
Alright, thanks for the suggestion!  👍
