### ISSUE TITLE
How to disable and enable CKEditor 5

### ISSUE THREAD

**Issue by conangithub** [ckeditor/ckeditor5#1886]
I am using CKEditor 5 version 12.2.0 which is installed using CDN.

I cannot disable or make my CKEditor read-only. I've read these documentation but still don't work.

https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html
https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#member-isReadOnly

This is my code

`ClassicEditor.create(document.querySelector('#description'))
        .then(editor => {
          console.log(editor);
        })
        .catch(error => {
          console.error(error);
        });`

To disable it, my code like this

`$('#description').isReadOnly = true;`

Please help me. @Reinmar @mlewand

**Comment by Mgsy** [comment]
Your code doesn't work, because you try to set `isReadOnly` property on a source element. This API is available via the editor instance, so you should use `editor.isReadOnly = true;` instead.

**Comment by conangithub** [comment]
How to apply editor instance to my code? I don't really understand when read that page you give to me. Any example? @Mgsy

**Comment by Mgsy** [comment]
>How to apply editor instance to my code? I don't really understand when read that page you give to me. Any example? @Mgsy

You can access the editor instance i.e. after creating the editor. Please, see the code below:

```js
ClassicEditor.create( document.querySelector('#description' ) )
     .then(editor => { 
          console.log( editor ); 
          editor.isReadOnly = true; // make the editor read-only right after initialization
     } ) .catch( error => { 
          console.error( error ); 
     } );
```

**Comment by conangithub** [comment]
Ok. I applied to my code and it works. Thank for helping me.

**Comment by conangithub** [comment]
Sorry, one more problem. I use `editor` as global variable so it can be accessed by other function.

```
var descriptionEditor;

ClassicEditor
        .create(document.querySelector('#description'))
        .then(editor => {
          console.log(editor);
          descriptionEditor = editor;
        })
        .catch(error => {
          console.error(error);
        });

descriptionEditor.isReadOnly = true;
```
I got this error.

```
TypeError: undefined is not an object (evaluating 'descriptionEditor.isReadOnly = true')
```

@Mgsy

**Comment by pomek** [comment]
When JS engine is executing `descriptionEditor.isReadOnly = true;`, the variable is equal to `undefined`. It will change its value when `ClassicEditor.create()` promise is being resolved.

**Comment by conangithub** [comment]
Ok. I got it. Better I put `isReadOnly` inside `ClassicEditor.create()` function as above to load.
The global variable works if we put inside any event.

Thank you. My problem is solved.

**Comment by Sumit-Shahu** [comment]
> Your code doesn't work, because you try to set `isReadOnly` property on a source element. This API is available via the [editor instance](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html), so you should use `editor.isReadOnly = true;` instead.

I need to know how to make isReadONly for particular element like<p>is read only Tag</p>

**Comment by anobjectn** [comment]
In my current project, I was looking for this ability - to disable programmatically but only after page has loaded based on the user via JS.  For me, simply disabling the textarea "_behind_" ckeditor did the trick as thos fields will not post. This was the behavior I wanted and its a common method across regular inputs, selects, textareas, and of course ckeditor enhanced textareas. 

with jQuery, that could be something like
`$myFieldsDefinedElsewhere.attr('disabled', false);`
or vanilla
`document.getElementById("myTextarea").disabled = true;`

**Comment by Chandrashreej** [comment]
> Your code doesn't work, because you try to set `isReadOnly` property on a source element. This API is available via the [editor instance](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html), so you should use `editor.isReadOnly = true;` instead.

> When JS engine is executing `descriptionEditor.isReadOnly = true;`, the variable is equal to `undefined`. It will change its value when `ClassicEditor.create()` promise is being resolved.

How can we pass isReadOnly through div or textarea or can we set it Seperately. As in my project I have many pages like view item there I need to disable editing.

**Comment by Chandrashreej** [comment]
> > Your code doesn't work, because you try to set `isReadOnly` property on a source element. This API is available via the [editor instance](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html), so you should use `editor.isReadOnly = true;` instead.
> 
> I need to know how to make isReadONly = true for particular element/ tag but not entire document

Did you get any solution for this?

**Comment by caamaann** [comment]
How to disable CKEditor 5 in react app? 
`export function CKRTE(field) {
  const {
    input: { onChange, value },
  } = field;
  return (
    <div className={css(styles.formContainer)}>
      <CKEditor
        {...field.input}
        editor={ClassicEditor}
        isReadOnly={field.isReadOnly}
        data={value}
        onChange={(event, editor) => onChange(editor.getData())}
        onBlur={(event, editor) => {}}
        config={{ extraPlugins: [MyCustomUploadAdapterPlugin] }}
      />
      <div className={css(styles.errorContainer)}>
        {field.meta.touched ? field.meta.error : ""}
      </div>
    </div>
  );
}`
my code is like this

**Comment by Mr-Lion** [comment]
> > Wie wende ich eine Editorinstanz auf meinen Code an? Ich verstehe nicht wirklich, wann ich diese Seite gelesen habe, die Sie mir geben. Irgendein Beispiel? @Mgsy
> 
> Sie können auf die Editorinstanz zugreifen, dh nachdem Sie den Editor erstellt haben. Bitte beachten Sie den folgenden Code:
> 
> ```js
> ClassicEditor . create (  document . querySelector ( '#description'  )  ) 
>      . then ( editor  =>  {  
>           console .log ( editor ) ; editor .isReadOnly = true ; // den Editor direkt nach der Initialisierung schreibgeschützt machen } ) . catch ( error => { Konsole . Fehler ( Fehler ) ; } ) ;   
>              
>            
>              
>       
> ```

Hi Guys,

I also have the same problem and what I quoted here definitely doesn't work.
The documentation is so sketchy. It doesn't say how to do it.

In the documentation there is a button how to disable / enable it, but nowhere is it described what the function of the button looks like.

`editor.isReadOnly = true;`
I immediately get an error saying that the property "isReadOnly" is protected. They can only be accessed within the class.

Really great, great !!!
And now?

I urgently ask for help !!!
![image](https://user-images.githubusercontent.com/6929357/162748981-804808cd-8b39-4b9f-8590-bba7a4593efc.png)

**Comment by BrianLeishman** [comment]
Same issue, I think it's just the DefinitelyTyped definitions that are saying it's protected when it's not supposed to. Might make sense to create a pr or an issue over there

**Comment by FilipTokarski** [comment]
Hi, for anyone having problems with `editor.isReadOnly = true;` - the read-only mechanism has been changed in version `34.0.0`. Please see the [changelog](https://ckeditor.com/docs/ckeditor5/latest/updating/changelog.html) for version 34, [migration docs](https://ckeditor.com/docs/ckeditor5/latest/updating/migration-to-34.html#changed-mechanism-for-setting-and-clearing-the-editor-read-only-mode), and [feature docs](https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html) for more details.

**Comment by BrianLeishman** [comment]
Copying here for visibility, from the docs:

```js
// ❌ Old usage:
function makeEditorReadOnly() {
    editor.isReadOnly = true;
}

function makeEditorEditable() {
    editor.isReadOnly = false;
}

// ✅ New usage:
const myFeatureLockId = Symbol( 'my-feature' );

function makeEditorReadOnly() {
    editor.enableReadOnlyMode( myFeatureLockId );
}

function makeEditorEditable() {
    editor.disableReadOnlyMode( myFeatureLockId );
}
```

Note that DefinitelyTyped's definitions aren't updated yet for this apparently, so trying to use the `enableReadOnlyMode` and `disableReadOnlyMode` will still throw errors, but you can work around this for now in Typescript with

```ts
const loadingLock = Symbol(); // symbol name param is optional, `Symbol` always returns a unique symbol regardless of input
(editor as any)['enableReadOnlyMode'](loadingLock);
// ... later ...
(editor as any)['disableReadOnlyMode'](loadingLock);
```

**Comment by Mr-Lion** [comment]
Isn't it sad to know that the DefinitelyTyped in TS hasn't been updated yet the patchy documentation presents it in a very sloppy way?

Then why isn't the DefinitelyTyped not updated immediately?

Unfortunately, I can't make sense of your code. Especially since it was totally pointless encapsulated in a function and set from true to false. What is that supposed to do?
This was about troubleshooting "`editor.isReadOnly`".

**Comment by BrianLeishman** [comment]
In the docs it mentions how the latest version of ckeditor5 made `editor.isReadOnly` a protected field, you can't update it. So the example with the functions (from the docs) is showing how they expect you to make a ckeditor readonly going forward.

You'll notice in my own example at the bottom I don't wrap things needlessly in the functions.

**Comment by Mr-Lion** [comment]
So somehow the documentation seems really crap. It doesn't want to work for me.

The documentation is totally incomplete. If it had been written properly, I wouldn't have had any trouble with it.

Well, I did what you suggested and the stupid documentation says the same thing.

I therefore ask for help!

![image](https://user-images.githubusercontent.com/6929357/170364770-e3dc965d-5165-4699-b1bf-a3673912f566.png)

**Comment by BrianLeishman** [comment]
The type definitions don't include the new methods, so you have to trick TypeScript into not caring (super gross, I know...)

```ts
(editor as any)['enableReadOnlyMode'](loadingLock);
```

**Comment by Mr-Lion** [comment]
Where do I add the code?
Why isn't this integrated into TS yet?

I don't understand your code. I ask for something more detailed.

**Comment by Mr-Lion** [comment]
Even though I commented out the isreadonly everywhere, I still get the error
![image](https://user-images.githubusercontent.com/6929357/170366866-6077cff8-331e-4a6d-92a1-e43374606838.png)

**Comment by Mr-Lion** [comment]
> The type definitions don't include the new methods, so you have to trick TypeScript into not caring (super gross, I know...)
> 
> ```ts
> (editor as any)['enableReadOnlyMode'](loadingLock);
> ```

I am asking for help here.
Can't get this solved and how to add it in TypeScript I don't know.

**Comment by Mr-Lion** [comment]
I built it like this:
```ts
watchdog.setCreator((element: HTMLElement, editorConfig: EditorConfig | undefined): Promise<Editor> => Editor.create(element, editorConfig)
    .then((editor: Editor) => {
        
        if (window.location.pathname.match(/admin\/cards\/delete\/(\d+)/g)) {
            (editor as any)['enableReadOnlyMode'](element);
            // editor.enableReadOnlyMode(element);
        };
        window.editor = editor;

        return editor;
    })
);
```

But in the browser (Chrome) i see this error here:
![image](https://user-images.githubusercontent.com/6929357/170825092-10e4d084-162c-4eda-a92e-860ab5eaa767.png)

What is here `lookID` or `loadingLock`?

Please help!
