### ISSUE TITLE
how to limit inline editor's max-height?

### ISSUE THREAD

**Issue by kanlidy** [ckeditor/ckeditor5#189]
Inline editor: 

`<div contenteditable="true" id="content">...</div>`

`CKEDITOR.inline( 'content' );`

<hr>

I try to add plugin "autoGrow" to my ckeditor4.5.

But config like this is not work:

`config.autoGrow_maxHeight = 200;`

<hr>

so, I google some solutions:

1. first try:

     `CKEDITOR.inline('test',{
        autoGrow_onStartup: true,
        autoGrow_maxHeight: 200
     });`

2. second try:

    `CKEDITOR.replace ('content', { autoGrow_maxHeight: 200 });`

All, fail.

Anyone, can help? Thanks.

**Comment by Reinmar** [comment]
Hi! This is CKEditor 5's bug tracker. You're asking about CKEditor 4, which has its bug tracker on http://dev.ckeditor.com. However, your question more falls into StackOverflow category, because you're not reporting any issue, so I recommend asking there.
