### ISSUE TITLE
upload local video not only online video

### ISSUE THREAD

**Issue by xiaosunJessica** [ckeditor/ckeditor5#1894]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
Hello, while creating a new ticket, please provide a meaningful subject and a detailed description of your case. I'd be grateful if you can edit a message and write more information. Thanks!
