### ISSUE TITLE
Image resize options not present in ckeditor 5

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1895]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

ckeditor 5

## 📋 Steps to reproduce

1. In earlier versions i.e. ckeditor 4 when user upload images, there were options to resize the image.
2. User can mention height and width of the image. Even resize control was available to change the image dimensions.
3. But in ckeditor 5, these options are not available. These options were used extensively by our users and all of sudden there is no way to resize the images.
4 . The image alignment options i.e. left, center and right are also not working when content is seen on web page. It works only inside ckeditor window.
5. Please see attached screenshots.

## ✅ Expected result
Need an option to resize images. 

![imageresize_cke5](https://user-images.githubusercontent.com/47845224/61350738-30d72180-a886-11e9-9e5c-6b113d8b83b3.jpg)
![imageresize_cke4](https://user-images.githubusercontent.com/47845224/61350740-316fb800-a886-11e9-8bd4-bf339e208d8f.jpg)

**Comment by Mgsy** [comment]
Image resize feature is on our roadmap and it will be available in the next release. You can read more about it [here](https://github.com/ckeditor/ckeditor5-image/issues/241).
