### ISSUE TITLE
IE11: Embedded videos are not working with IE 11 browser.

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1896]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

ckeditor 5

## 📋 Steps to reproduce

1. Embed a video link with ckeditor 5
2. When the content is seen on IE11 browser the video link does not work but the same link works when it is seen on chrome.

## ✅ Expected result
Embedded Videos should work on IE 11

**Comment by Mgsy** [comment]
Hello, Internet Explorer 11 isn't supported by CKEditor 5. We've made a research about it some time ago, you can read a discussion [here](https://github.com/ckeditor/ckeditor5/issues/330).
