### ISSUE TITLE
Bring compatibility with code coverage

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#190]
Apparently, Istanbul (even the latest one) doesn't support some ES6 constructs that we use.  This means that we're unable to run jobs, because they take ridiculous amount of time.

There are two things we need to do:

1. Fork benderjs-coverage to use a standard Istanbul (benderjs-coverage uses a hacked one, because, AFAIR, CKE4 requires that) and in its latest version.
2. Check what ES6 features break Istanbul and stop using them. My guess will be that deconstructuring in default params.

See https://github.com/benderjs/benderjs/issues/253 for more.

**Comment by pjasiun** [comment]
In fact bender jobs instability is very time consuming. For me everything starts when I updated Node from 4.4.4 to 5.9.1. It looks old Istanbul (the one we currently use) does not work fine to the new Node.

**Comment by pjasiun** [comment]
But, anyway, if it is only nested deconstructing what breaks new Istanbul I think we can live without it. It will be a little sad live, I used to like it, but, well, live is brutal.

**Comment by Reinmar** [comment]
I made a small "workaround" in #185 – configured Bender.js to fail after 5s, not 1 minute. This speeds up tests... but still we need a real solution.

**Comment by Reinmar** [comment]
I pushed branch t/190 with an upgrade benderjs-coverage. But now we need to downgrade our code so it does not use ES6 features which Istanbul can't handle.

**Comment by pjasiun** [comment]
Can't we use babel to compile them?

**Comment by Reinmar** [comment]
Hm... then there's a high chance that lack of Babel+Istanbul integration will yield uncovered lines of code. But it's worth checking.

**Comment by pjasiun** [comment]
In this case babel do nice job:
```js
function defaultParams( { foo = 1, bar = 2 } = {} ) {
  console.log( foo, bar );
}
```
=>
```js
"use strict";

function defaultParams() {
  var _ref = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

  var _ref$foo = _ref.foo;
  var foo = _ref$foo === undefined ? 1 : _ref$foo;
  var _ref$bar = _ref.bar;
  var bar = _ref$bar === undefined ? 2 : _ref$bar;

  console.log(foo, bar);
}
```

What, in fact, is a code we should cover in tests.

**Comment by oskarwrobel** [comment]
I've added two babel plugins for transformation destructing in default params
```
babel-plugin-transform-es2015-destructuring
babel-plugin-transform-es2015-parameters
```

looks there is no problem with coverage of transpiled code.

Still one error occurs (only on first run of job), but coverage for this file is generated.
![screenshot 2016-06-17 08 36 53](https://cloud.githubusercontent.com/assets/1057056/16144037/c6fe8eba-3470-11e6-87f1-6cb88b7ec8bc.png)

**Comment by Reinmar** [comment]
Thanks for the good news!

**Comment by Reinmar** [comment]
I mean – all good except the htmlDP error. Looks very weird in fact.

**Comment by oskarwrobel** [comment]
Here is a problem of htmldataprocessor error https://github.com/ckeditor/ckeditor5-engine/blob/master/tests/dataprocessor/htmldataprocessor.js#L11
