### ISSUE TITLE
How do I allow React to Portal into CKEditor?

### ISSUE THREAD

**Issue by ysct** [ckeditor/ckeditor5#1900]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

CKEditor 5, v12.2.0. Decoupled Editor

## 📋 Steps to reproduce

1. Use CKEditor to manage an empty DOM node.
2. Using React Portals, Portal a React Component into this DOM node.

## ✅ Expected result
Within the CKEditor editor, the React Component would be rendered.

## ❎ Actual result
It doesn't render, nor appear within the DOM tree.

## 📃 Other details that might be useful
Currently there's a CKEditor React Component, but that's for inserting CKEditor within React. 
However, if I were to insert React within CKEditor, how would I go about doing it using CKEditor framework and React Portal? 

Thanks!

**Comment by ysct** [comment]
By the way, even if I use vanilla JS, for example...

`document.querySelector(".editable-container").innerHTML = "<h1>something</h1>"`

...it wouldn't work if CKEditor instance is created. It would only work after the CKEditor is destroyed.

So I suspect that it could be CKEditor forbidding external Javascript to change any DOM nodes that it's currently managing.

**Comment by Mgsy** [comment]
@pomek, do we have any experience with CKEditor 5 and React Portals? Is it possible to use it within our editor?

**Comment by pomek** [comment]
@ysct, does the console show any error? If don't, could you describe steps in order to reproduce the issue? We don't expect that you share the entire application but a minimal sample that shows the error would be nice.

**Comment by ma2ciek** [comment]
> However, if I were to insert React within CKEditor, how would I go about doing it using CKEditor framework and React Portal?

Do you want to render something inside the CKEditor 5 component? I don't understand your use case and what you want to achieve.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
