### ISSUE TITLE
Copy formatting / format painter

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1901]
## Is this a bug report or feature request?

🆕 Feature request

## 💻 Version of CKEditor

CKEditor v5 @ 12.3.1

## 📋 Steps to reproduce

It would be nice to have a feature that allows you to easily apply formatting from one part of the document to the other.

We have already [copy formatting feature implemented in CKEditor 4](https://ckeditor.com/docs/ckeditor4/latest/features/copyformatting.html).

## 📃 Other details that might be useful

The implementation should use [AttributeProperties#isFormatting](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-AttributeProperties.html) property to identify formatting attributes.

---

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by Jch71** [comment]
Hello, and thanks for the good work on CKE5. 
I'd like to add a request to this one : 
On the Office suite, if you paste a text with formating, you get the formatting pop-in. 

![67773972_387392905296323_26985210801291264_n](https://user-images.githubusercontent.com/6115571/62449840-59f31f80-b76b-11e9-8895-f52bcb194d32.png)


I'm currently building a word-like editor for our customers, and we want them to feel the same as with the tools they currently know. 
If this feature could be built with the format painter, it would be a real plus !
Thanks !

**Comment by mlewand** [comment]
@Jch71 I see your point. But this is a separate feature request not related with Copy Formatting / Format Painter (unless I miss something 🙂). In that case please report a separate issue for this, so that community can find it easily and bump it.

**Comment by wquintanilhadasilva** [comment]
Please, what is the npm copyFormatting package for the 5x version of ckeditor?

npm i @ ckeditor5 - ????

**Comment by jensen-lin** [comment]
Our customers is asking for format painter.

**Comment by a-legotin** [comment]
Any update on this? Would like to see this feature in your product.

**Comment by Joeycz** [comment]
any update？

**Comment by christianztamayo** [comment]
Would love to have this feature on our app.

**Comment by kuku711** [comment]
I'm interested too in this plugin.

**Comment by ChristopherGeorgeson** [comment]
Following

**Comment by JS-mark** [comment]
any update?

**Comment by kuku711** [comment]
Important ability. We need it too.

**Comment by kwittward** [comment]
We also need this functionality. WHy was it taken out? It would be super helpful to know the reasons why you take things out between versions. Our customers count on this.

**Comment by Shrek132021** [comment]
Hi - when can we expect a format painter on CKEditor 5?

**Comment by JS-mark** [comment]
Can't wait! I realized it by myself, it's still very simple!

**Comment by huzedong2015** [comment]
> 等不及了！我自己实现了，还是很简单的！

Do you have NPM package？

**Comment by huzedong2015** [comment]
> Can't wait! I realized it by myself, it's still very simple!

Do you have NPM package？

**Comment by JS-mark** [comment]
> > Can't wait! I realized it by myself, it's still very simple!
> 
> Do you have NPM package？

No, only on the company project.

**Comment by zjw93615** [comment]
> I realized it by myself, it's still very simple!

Hi, could you give me some ideas? I really need this feature on my project.

**Comment by JS-mark** [comment]
> > I realized it by myself, it's still very simple!我自己意识到的，还是很简单的！
> 
> Hi, could you give me some ideas? I really need this feature on my project.
> 
> 你好，你能给我一些想法吗? 我真的需要在我的项目这个功能。

ok! No problem.

**Comment by JS-mark** [comment]
Wrote a blog to introduce the ideas of plug-in implementation.
Article: https://js-mark.com/JavaScript/%E5%9F%BA%E4%BA%8ECKEditor5%E7%9A%84%E6%A0%BC%E5%BC%8F%E5%8C%96%E6%8F%92%E4%BB%B6/#more

**Comment by Marcy1231** [comment]
Our customers would like to have a format-painter feature as well. Would be great, if you could implement this important feature!

**Comment by sam-farhan** [comment]
This feature is a hard requirement for a project I am currently working on. Would be nice to see it officially implemented.

**Comment by mlewand** [comment]
Thanks for noting, like mentioned, the feature has been [shipped in version 37.1.0](https://github.com/ckeditor/ckeditor5/blob/master/CHANGELOG.md#3710-2023-04-19) and is available as a part of productivity pack feature set 🎉
