### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by andrenovax** [ckeditor/ckeditor5#1903]
## 💻 Version of CKEditor

any

## 📋 Steps to reproduce

Hey guys,
Cant find any docs and examples with how to make a custom toolbar and how to set custom attributes
Is it possible to make something like this?

```jsx

const CKEditor = () => (
  <ckeditor5
    toolbar={WysiwygToolbar}
    showToolbarOn="select"
    ...
  />
);

type Props = {
  setAttribute: (attributeKey: string, value?: string, element: WysiwygElement) => any,
  setStyle: (cssKey: CSSKeyType, value?: string | number, element: WysiwygElement) => any,
  attributes: {
    [key: string]: string | number
  },
  styles: {
    [key: CSSKeyType]: string | number
  },
  selectedElement: WysiwygElement,
};

function WysiwygToolbar({ setAttribute, setStyle, attributes, styles, selectedElement }: Props) {
  return (
    <div>
      {styles.fontWeight !== 'bold' 
        ? <button onClick={() => setStyle('font-weight', 'bold', selectedElement)>Make it bold!</button>
        : <button onClick={() => setStyle('font-weight', null, selectedElement)>Remove bold formatting!</button>
      }
      <input 
        type="text" 
        onChange={event => setAttribute('myCustomAttr', event.target.value, selectedElement)} 
        value={attributes.myCustomAttr} 
      />
    </div>
  );
}

```

Need it to implement the next ui
![wyswyg_link_editor2](https://user-images.githubusercontent.com/6430439/61528136-9d058100-aa50-11e9-8ac5-48fcaf0e45a3.png)

Thanks

**Comment by oleq** [comment]
You don't have to UI offered by the editor. You can have your own on top of the editing layer. Check out [this guide ](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/external-ui.html) to learn more.

**Comment by Reinmar** [comment]
It can be a completely external UI (as proposed by @oleq) in which case you could use React all the way down. Or, you can use our UI and extend it with your additions. For instance, I can see that you want to extend the [link balloon](https://github.com/ckeditor/ckeditor5-link/blob/master/src/ui/linkformview.js). Those additions can be React-based, but then the outermost parts of the UI will be controlled by our code but that will create a less clear situation for you (parts of the code will be React-based and some will use our UI library). It basically depends on how much you want to change. Whether it's better to drop our entire UI or trying to extend it.

**Comment by andrenovax** [comment]
cool, thanks
