### ISSUE TITLE
Suggestion: include CKEditor version in JS file comments

### ISSUE THREAD

**Issue by toxpal** [ckeditor/ckeditor5#1904]
Now, after downloading CKeditor from https://ckeditor.com/ckeditor-5/download/ gives a bunch of files, and none of files has actual version number. As a result, it makes developers wondering what version of CKEditor they are using in their scripts.

P.S. I know there is a README file in package and it has version number, but it's absolutely incorrect and out-of-date. For example, downloaded 12.3.1 several minutes ago and README file says it's version 11. Right...

P.P.S. I also discovered there's a hardcoded version number inside ckeditor.js but you can only find it if you know what to look for. Since I downloaded 12.3.1, I typed 12.3.1 into text editor's search field and found this value hardcoded deep in the file. So, you can only find the version of CKeditor if you already know what version you have, which doesn't help, obviously...

If you could include version number at the top of ckeditor.js file (where comments are written) like many devs do in their JS scripts, that would be extremely useful.

Thank you for your consideration.

**Comment by Mgsy** [comment]
cc @Reinmar @mlewand

**Comment by Reinmar** [comment]
> P.S. I know there is a README file in package and it has version number, but it's absolutely incorrect and out-of-date. For example, downloaded 12.3.1 several minutes ago and README file says it's version 11. Right...

Thanks for pointing this out 😬 I forwarded it to my colleagues.

> P.P.S. I also discovered there's a hardcoded version number inside ckeditor.js but you can only find it if you know what to look for. Since I downloaded 12.3.1, I typed 12.3.1 into text editor's search field and found this value hardcoded deep in the file. So, you can only find the version of CKeditor if you already know what version you have, which doesn't help, obviously...

You can also check it on a page where CKEditor is loaded by checking the value of `CKEDITOR_VERSION` global.

![image](https://user-images.githubusercontent.com/156149/61619979-38c10800-ac70-11e9-87d5-2c6f1a5580e1.png)

---

Assuming that the README will be up to date (so you can check the version number by browsing the files) and that you can check the version in the browser (to verify which version you're really using – which sometimes isn't that obvious) – won't that be enough?

It shouldn't be too hard, of course, to add the version number in the footer of the file, but if we can avoid spending time on that, I'm always happy to do so :)

**Comment by toxpal** [comment]
If README contains accurate version number, I believe it will be fine. During development (especially updates of bundled JS library in my apps) it would require extra efforts to load each app in browser just to check version number of some bundled JS library, so I simply open JS file via text editor and overwrite it with a new version (if needed) right on the disk.

But like I said,accurate README will be OK :)

**Comment by Reinmar** [comment]
> If README contains accurate version number, I believe it will be fine.

That's fixed already and new packages should be available in a couple of minutes. Thanks again for reporting it!

**Comment by Reinmar** [comment]
> But like I said,accurate README will be OK :)

OK, so I'll close this ticket.

If anyone can spot other problems with the current solution, please let us know.
