### ISSUE TITLE
Update documentation builder and the #stable branch

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1907]
After https://github.com/ckeditor/ckeditor5/pull/1905 we can remove `#stable` suffixes from `mrgit.json` also on the `ckeditor5@stable` branch. That's because when mrgit will detect that `ckeditor5` is on the `stable` branch it will also use `stable` inside other repositories (see https://www.npmjs.com/package/mrgit#base-branches).

However, when we do that change in `ckeditor5@stable`, we need to verify that the documentation builder uses mrgit and that everything works fine.

cc @pomek @vokiel

**Comment by pomek** [comment]
Done with https://github.com/ckeditor/ckeditor5/commit/79c2cf1293757b0ad304a33f3495fef6291ee03a and https://github.com/ckeditor/ckeditor5/commit/2dd8256a14cf6bed03fccb60f79cd8fba7436778.
