### ISSUE TITLE
Doubled imports in dev/tasks/build/utils.js file

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#191]
https://github.com/ckeditor/ckeditor5/blob/7a29eee51e1f40e615aa320f3c19da9a4e5c4f2d/dev/tasks/build/utils.js#L14
and
https://github.com/ckeditor/ckeditor5/blob/7a29eee51e1f40e615aa320f3c19da9a4e5c4f2d/dev/tasks/build/utils.js#L24

https://github.com/ckeditor/ckeditor5/blob/7a29eee51e1f40e615aa320f3c19da9a4e5c4f2d/dev/tasks/build/utils.js#L15
and
https://github.com/ckeditor/ckeditor5/blob/7a29eee51e1f40e615aa320f3c19da9a4e5c4f2d/dev/tasks/build/utils.js#L23

There should be some imports naming convention to overcome similar issues. I propose to use small camel case of full import name so:

- ~~`pipe`~~ but `multipipe` for `require( 'multipipe' )`
- ~~`filter`~~ but `gulpFilter` for `require( 'gulp-filter' )`

**Comment by Reinmar** [comment]
That's more of an oversight than a real issue. But it maybe a good idea to introduce some std naming and I agree that camel case makes most sense.

**Comment by jodator** [comment]
@Reinmar there's no "New not really an issue" button so I've used "New issue" button :wink:.
