### ISSUE TITLE
Move blank characters out of the custom tag

### ISSUE THREAD

**Issue by kosaa** [ckeditor/ckeditor5#1911]
When caret is between tags (`</mytag>CARRET_POS<mytag`) and I put some blank characters my structure is like this
```
<mytag id="idA">wordA &nbsp;</mytag><mytag id="idB">wordB</mytag>
```

it is able to move this blank characters out of the tag <mytag> structure?

expected result
```
<mytag id="idA">wordA</mytag> &nbsp;<mytag id="idB">wordB</mytag>
```

current editor config:
```
editor.model.schema.extend('$text', {
	allowAttributes: ['id', 'customtag']
});

editor.conversion.for('upcast').attributeToAttribute({
	model: 'id',
	view: {
		key: 'id',
		value: /[\s\S]+/
	}
});
editor.conversion.for('downcast').attributeToElement({
	model: 'id',
	view: (modelAttributeValue, viewWriter) => {
		return viewWriter.createAttributeElement('mytag', {
			id: modelAttributeValue
		});
	}
});
```

**Comment by Mgsy** [comment]
cc @jodator

**Comment by jodator** [comment]
@kosaa If I get this correctly you don't wish to "write" with `id` attribute. This looks like the same case as in  `Mention` feature. You can check the code here: https://github.com/ckeditor/ckeditor5-mention/blob/164c858230ffa619387f1a89a3ec6bb8d10be898/src/mentionediting.js#L158-L167

It is added as a post-fxer:

```js
const doc = editor.model.document;
doc.registerPostFixer( writer => selectionMentionAttributePostFixer( writer, doc ) );
```

this will disallow to type any character with and `id` attribute.

If you whish to remove `id` attribute from newly inserted text then you can check the `removePartialMentionPostFixer` from that file for inspiration. If you detect typed space you can create range on typed character and remove that attribute using range (:

```js
const start = writer.createPositionAt( change.position );
const range = writer.createRange( start, start.getShiftedBy( 1 );
writer.removeAttribute( 'id', range );
```
