### ISSUE TITLE
CSS variable "--ck-image-upload-progress-line-width" is duplicated

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1915]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 📃 Other details that might be useful

While I was fixing #1805, I found duplicated definition of the `--ck-image-upload-progress-line-width` variable.

- https://github.com/ckeditor/ckeditor5-image/blob/8fa4acf7850e958526d0f049899f88cb91282a74/theme/imageuploadprogress.css#L8
- https://github.com/ckeditor/ckeditor5-theme-lark/blob/b87d6e719b62a65e6f06f19a4f504c4115a7fc70/theme/ckeditor5-image/imageuploadprogress.css#L8

**Comment by Mgsy** [comment]
cc @dkonopka
