### ISSUE TITLE
Unable to even get quick start example for classic editor5 working

### ISSUE THREAD

**Issue by migorski** [ckeditor/ckeditor5#1918]
## Is this a bug report or feature request? (choose one)
bug report

🐞 Bug report  |  🆕 Feature request  |  Other

## 💻 Version of CKEditor
ckeditor5/12.3.1/classic

## 📋 Steps to reproduce

1. code from servicenow ui page shown below

(html)
<?xml version="1.0" encoding="utf-8" ?>
<j:jelly trim="false" xmlns:j="jelly:core" xmlns:g="glide" xmlns:j2="null" xmlns:g2="null">

	
	<script src="https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js"></script>
	
	<g:ui_form>	
		<textarea name="editor2" id="editor2">
			blah
		</textarea>
	</g:ui_form>		
</j:jelly>

(script)
jQuery(window).load(function() {
	ClassicEditor.create( document.querySelector( '#editor2' ) );	
});

## ✅ Expected result
expect page to open with editor

## ❎ Actual result

VM11995 ckeditor.js:5 Uncaught (in promise) CKEditorError: observable-bind-to-properties-length: The number of properties must match. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-observable-bind-to-properties-length

    at https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:124173
    at Array.forEach (<anonymous>)
    at Object.Hi [as to] (https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:124107)
    at Ji.set _document [as _document] (https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:125961)
    at https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:256352
    at https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:143337
    at oo.n (https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:143626)
    at oo.fire (https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:108777)
    at oo.add (https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:141841)
    at Ec.createRoot (https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js:5:318131)

## 📃 Other details that might be useful
created quick start page using ckeditor v4 (<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>) and the page and editor opens successfully

**Comment by Mgsy** [comment]
Hello, unfortunately it looks like a library you use causes problems (or a way it's used) and there's not much we can do about it. You can try to debug it on your own.

As you can see in the following sample, this code works fine - https://codepen.io/mlewand/pen/xvqpqW.
