### ISSUE TITLE
[Docs] Unavailable video in the classic editor sample

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#1923]
## Is this a bug report or feature request?

🐞 Bug report 

## 📋 Steps to reproduce

1. https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

## ✅ Expected result

Valid youtube video.

<img width="1632" alt="Screenshot 2019-07-29 at 13 38 57" src="https://user-images.githubusercontent.com/10219857/62045707-59f09e00-b206-11e9-89a7-a1a8acdfea42.png">

**Comment by jodator** [comment]
We should upload something on our own and use it. We cannot rely on third-party content as it might be removed anytime from YouTube.

**Comment by mlewand** [comment]
> We should upload something on our own

I don't think we have any pro videos that would look good.

This case should be a lesson for us that we should use videos from a established/bigger publishers rather than picking just any youtube video.

**Comment by jodator** [comment]
> This case should be a lesson for us that we should use videos from a established/bigger publishers rather than picking just any youtube video.

Please bear in mind that an established/bigger publisher can block content in some countries. So again uploading own video is also a plus ;)

**Comment by mlewand** [comment]
@gok9ok @AnnaTomanek  any URL for suitable video? 🙂 I don't want this issue to be open for a long time.

**Comment by gok9ok** [comment]
https://www.youtube.com/watch?v=CB70skVw3nU
