### ISSUE TITLE
Missing redirect for track changes

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1929]
This page is outdated: https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes.html and contains misleading information:

![Screen Shot 2019-07-30 at 2 52 13 PM](https://user-images.githubusercontent.com/545175/62130581-a658de00-b2d9-11e9-8655-16a435ae7635.png)

There should be a redirect in umberto.json to 
https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html

**Comment by pjasiun** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/commit/8463e8768c00d5fcf82e088c56bef024ec1d05e8.
