### ISSUE TITLE
ckeditor5 translations use

### ISSUE THREAD

**Issue by rathiayush** [ckeditor/ckeditor5#1931]
Other
## 💻ckeditor-classic-build 12.3.1

As written in docs:-
To use different language than default one (English), we need to load the editor together with the preferred language:
```
<script src="https://cdn.ckeditor.com/ckeditor5/[version.number]/[distribution]/ckeditor.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/[version.number]/[distribution]/translations/[lang].js"></script>
```

I am loading editor and giving language value at runtime,this implies i need to include all language js files in my page. Loading all language js would not be a great idea as only one of them going to be used.
for eg:-

```
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        language: this.lang  //variable 
    } )
    .catch( error => {
        console.error( error );
    } );
```

Is there any better way to do it?

**Comment by mlewand** [comment]
That's a pretty easy task that you can achieve with some JS scripting.

You just want to defer script loading and create the editor once script has been loaded. You can see it here https://codepen.io/mlewand/pen/YmxeJo

**Comment by rathiayush** [comment]
Thanks @mlewand
