### ISSUE TITLE
Complete toolbar with all plugins

### ISSUE THREAD

**Issue by akvaliya** [ckeditor/ckeditor5#1935]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

` "@ckeditor/ckeditor5-build-classic": "^12.3.1"`

I am using above toolbar in `@ckeditor/ckeditor5-angular`

My requirement is a editor with allowing to select font & color picker with all other basic toolbar features.

I am using classic & it's provide only around 7 items in toolbar. Document editor has full toolbar.

How can i implement classic editor with document toolbar options?

I have looked into document & it's vary complicated

**Comment by mlewand** [comment]
Not sure what parts of documentation you used, but it's clearly shown how to use different editor builds in the [Rich text editor component for Angular](Rich text editor component for Angular) guide (there's even a dedicated "Note: Using the Document editor build" section).

Follow the described steps and you'll get the build you're looking for.
