### ISSUE TITLE
Adding ImageStyles to Custom Build VueJS + Laravel Mix

### ISSUE THREAD

**Issue by minasm** [ckeditor/ckeditor5#1938]
## Is this a bug report or feature request? (choose one)
Other
🐞 Bug report  |  🆕 Feature request  |  Other

## 💻 Version of CKEditor
5

## 📋 Steps to reproduce
I am trying to implement a custom build to be used with VueJs and Laravel Mix. Now looks like all working but I cannot manage to set up the required plugins as they either conflict or give not-loaded errors.
What I am trying to do is create a custom build to support image upload and then image align to left/right with a Baloon toolbar.
Here is my custom component;

```
<template>
	<ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
</template>

<script>
    import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

    import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
    import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
    import BalloonToolbar from '@ckeditor/ckeditor5-editor-balloon/src/ballooneditor'
    import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
    import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';
    import ImagePlugin from '@ckeditor/ckeditor5-image/src/image';
    import ImageCaptionPlugin from '@ckeditor/ckeditor5-image/src/imagecaption';
    import ImageStylePlugin from '@ckeditor/ckeditor5-image/src/imagestyle';
    import ImageToolbarPlugin from '@ckeditor/ckeditor5-image/src/imagetoolbar';
    import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';

    export default {
        name: 'ckeditor-custom',
        data() {
            return {
                editor: ClassicEditor,
                editorData: '<p>Hello World</p>',
                editorConfig: {
                    plugins: [
                        EssentialsPlugin,
                        BalloonToolbar,
                        BoldPlugin,
                        ItalicPlugin,
                        ParagraphPlugin,
                        ImagePlugin,
                        ImageCaptionPlugin,
                        ImageStylePlugin,
                        ImageToolbarPlugin,
                        ImageUpload,
                    ],

                    toolbar: {
                        items: [
                            'bold',
                            'italic',
			   '|',
                            'undo',
                            'redo',
                            'imageUpload',
                        ]
                    },
                    image: {
                        toolbar: [
                            'imageStyle:full',
                            'imageStyle:side',
                            'imageTextAlternative'
                        ]
                    },
                }
            };
        }
    };
</script>
```

## ✅ Expected result

Trying to have a basic toolbar but also have an image upload feature with a custom uploader. Once the image is added to the editor, I want to use the features here;
https://ckeditor.com/docs/ckeditor5/latest/features/image.html#configuring-image-styles

## ❎ Actual result

When I use the plugin, I get the following error:

![Screenshot 2019-08-02 at 16 44 36](https://user-images.githubusercontent.com/2103447/62382254-14eda400-b545-11e9-9619-1ce58dd3b0c0.png)

Obviously, I am missing something here. When I remove the Balloon plugin then I get another error. 
![Screenshot 2019-08-02 at 16 52 24](https://user-images.githubusercontent.com/2103447/62382661-ede3a200-b545-11e9-8a0b-def76d5a38e6.png)

**Comment by Mgsy** [comment]
Your problem occurs because you've imported and loaded two editors - classic editor and balloon editor. `BlockToolbar` import should be removed, also from the plugins array (after that your errors should disappear).

As I understand, you try to configure image styles. Please see a guide in our [documentation page](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image-ImageConfig.html#member-styles).

**Comment by minasm** [comment]
Thank you @Mgsy,

Missed that completely. Basically,

 I am trying to get the buttons when you upload and select an image so that you can align it to left or right; example link is here:

https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html
Which plugin do I need to do this exactly? 
![rsz_screenshot_from_2019-08-05_17-12-40](https://user-images.githubusercontent.com/2103447/62479014-6f387000-b7a4-11e9-987c-f39c549e0150.png)

**Comment by Mgsy** [comment]
If you want to achieve behaviour from the example you provided, you should import `ImageToolbar` plugin (`'@ckeditor/ckeditor5-image/src/imagetoolbar';`) and configure it in editor config:
```js
// ...
image: {
        toolbar: [
               'imageStyle:full',
               'imageStyle:side',
                'imageTextAlternative'
           ]
 }
// ...
```

If you want custom styles, you should create own styles. [Here](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-styles) is the guide.

**Comment by minasm** [comment]
@Mgsy thank you for your reply but that was how I was trying to use it.
I tried what you suggested and still getting 
`CKEditorError: plugincollection-plugin-not-loaded: The requested plugin is not loaded {"plugin":"BalloonToolbar"}`
Additionally, I am getting `Uncaught (in promise) CKEditorError: plugincollection-plugin-name-conflict: Two plugins with the same name were loaded`

Adding my custom VueJS component here;
```
<template>
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
</template>

<script>
    import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

    import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
    import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
    import BalloonToolbar from '@ckeditor/ckeditor5-editor-balloon/src/ballooneditor'
    import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
    import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';
    import ImagePlugin from '@ckeditor/ckeditor5-image/src/image';
    import ImageCaptionPlugin from '@ckeditor/ckeditor5-image/src/imagecaption';
    import ImageStylePlugin from '@ckeditor/ckeditor5-image/src/imagestyle';
    import ImageToolbarPlugin from '@ckeditor/ckeditor5-image/src/imagetoolbar';
    import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';

    export default {
        name: 'ckeditor-custom',
        data() {
            return {
                editor: ClassicEditor,
                editorData: '<p>Hello World</p>',
                editorConfig: {
                    plugins: [
                        EssentialsPlugin,
                        BalloonToolbar,
                        BoldPlugin,
                        ItalicPlugin,
                        ParagraphPlugin,
                        ImagePlugin,
                        ImageCaptionPlugin,
                        ImageStylePlugin,
                        ImageToolbarPlugin,
                        ImageUpload,
                    ],

                    toolbar: {
                        items: [
                            'bold',
                            'italic',
                            '|',
                            'undo',
                            'redo',
                            'imageUpload',
                        ]
                    },
                    image: {
                        toolbar: [
                            'imageStyle:full',
                            'imageStyle:side',
                            'imageTextAlternative'
                        ]
                    }
                }
            };
        }
    };
</script>
```

**Comment by Mgsy** [comment]
As I wrote before, you import two editors. This line
```
 import BalloonToolbar from '@ckeditor/ckeditor5-editor-balloon/src/ballooneditor'
```

causes troubles, because you don't import `BalloonToolbar` as a component, but the whole balloon editor base.

After removing this line, there should be no errors in the console.

**Comment by minasm** [comment]
Thank you very much @Mgsy for your guidence
Closing this issue as I switched to another solution.
