### ISSUE TITLE
Allow users to add new hashtags to the editor.

### ISSUE THREAD

**Issue by ajaykrshukla** [ckeditor/ckeditor5#1939]
I am using ckeditor 5 amd mention plugin to allow user to insert hashtag. What it does is that it allow users to select only predefined hashtag to be inserted in editor but what i want is that it should allow new hastag to be inserted in editor as well. Please let me know how this can be programmed. If anyone can share any idea that will be great. I have already used Javascript replace and insertcontent but it is taking cursor to last position after btween sentence hashtag. So this is issue

I

**Comment by Mgsy** [comment]
Hello, just to be sure - you want users to be able to create a completely new mention dynamically and add it to the mentions list?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by ajayshukla** [comment]
Hello Mgsy,

Sorry that I did not get your notification. Yes you have understood it correctly we need to allow users to add hashtags dynamically.

Can you please let me know how that can be done?

Thanks
