### ISSUE TITLE
Uncaught TypeError: Cannot read property 'anchorNode' of null

### ISSUE THREAD

**Issue by colegauthier** [ckeditor/ckeditor5#1940]
## Is this a bug report or feature request? (choose one)

**🐞 Bug report**  |  🆕 Feature request  |  Other

## 💻 Version of CKEditor

CKEditor 5
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "@ckeditor/ckeditor5-build-classic": "^12.3.1",
    "@ckeditor/ckeditor5-markdown-gfm": "^11.0.4",

**Using this with Angular**

## 📋 Steps to reproduce

1. Create two components, one for the editor and another as a home page.
2. Use the editor component in the home page component.
3. Add onChange event on the editor component.
4. That's pretty much it, followed the quick start guide here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#note-using-the-document-editor-build

## ✅ Expected result
No errors in console. 

## ❎ Actual result

Getting an Uncaught TypeError: Cannot read property 'anchorNode' of null

## 📃 Other details that might be useful

Any help would be great!

**Comment by Mgsy** [comment]
Hello, can you show us your integration code?

**Comment by colegauthier** [comment]
This is my other component (HTML):

`<app-editor></app-editor>`

This is my editor component (HTML):

`<ckeditor [editor]="Editor" (change)="onChange($event)" [(ngModel)]="model.editorData"></ckeditor>`

This is my editor component (TS):

`import { Component, OnInit } from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import { ChangeEvent } from '@ckeditor/ckeditor5-angular';

@Component({
  selector: 'app-editor',
  templateUrl: './editor.component.html',
  styleUrls: ['./editor.component.css']
})
export class EditorComponent implements OnInit {

  constructor() { }

  public Editor = ClassicEditor;

  public model = {
    title: "",
    editorData: "",
  };

  public onChange({ editor }: ChangeEvent) {
    const data = editor.getData();
    console.log(data);
  }

  sendData() {
    console.log(this.model);
  }

  ngOnInit() {
  }

}
`

**Comment by colegauthier** [comment]
@Mgsy I noticed that I was using an older version of Angular, version 5. I have since then upgraded and everything seems to be working as intended without any errors. Thank you for your help.

**Comment by rezonjov** [comment]
I have been getting the same error 

![image](https://user-images.githubusercontent.com/129856/66018096-d99d3080-e507-11e9-9c6a-265ac2ddeecb.png)

I'm using a new version of Angular 8z

**Comment by Stalinko** [comment]
I've caught the same error via Sentry as the commentor above ^
however we use ReactJS 16.5 so it's not related to Angular.
Our users trigger this error pretty regularly but I can't reproduce it with my Android right now.
