### ISSUE TITLE
🐞 Bug report "Use *ngIf for show hide div ckeditor back to normal textarea"

### ISSUE THREAD

**Issue by alfradias** [ckeditor/ckeditor5#1947]
🐞 Bug report

I Have Button Like Tabs for show hide div using ngIf. When first load ckeditor5 work well but after I'm change tabs and back to tabs with ckeditor5 the field return to normal textarea

💻 Version of CKEditor
"@ckeditor/ckeditor5-build-classic": "^11.2.0"
"Ionic: 4"
"Angular: 5"

 ✅ Expected result
When change tabs to div with ckeditor5, not back to normal textarea.

 ❎ Actual result
When change tabs to div with ckeditor5, back to normal textarea.

 📃 Other details that might be useful

`
ionViewDidLoad() {
    ClassicEditor
    .create( document.querySelector( '#editor' ), {
      toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
    } )
    .then( editor => {
        this.theEditor = editor;
    } )
    .catch( error => {
        console.error( error );
    } );
}
`

**Comment by ma2ciek** [comment]
Do you use the `ckeditor5-angular`? If so, then please report it in the https://github.com/ckeditor/ckeditor5-angular.

**Comment by Mgsy** [comment]
Hello, as I understand you create a mobile app with Ionic and the editor doesn't create after switching back to the tab? Do you destroy the editor after changing tab? Do you have any errors in the console? 

Also, the code sample of your integration will be much appreciated.

**Comment by alfradias** [comment]
Sorry for replying in a long time.
Hello, I'm using ionic + angular 5. Yeah in first reload editor work well but after switching tab and back to the first tab editor doesn't create. I didn't destroy the editor and there is no error in console

my code in picture 
![controller](https://user-images.githubusercontent.com/20962620/63071821-0347cb80-bf4b-11e9-8292-512fea4dfc26.jpeg)
![view](https://user-images.githubusercontent.com/20962620/63071822-0347cb80-bf4b-11e9-9a27-02e1ef84bdc9.jpeg)

**Comment by ma2ciek** [comment]
I'm glad that you've fixed the problem 😄
