### ISSUE TITLE
DowncastDisaptcher#selection api docs list nonexistent `consumable` parameter

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#1948]
## Is this a bug report or feature request?

📃 Docs

## 💻 Version of CKEditor

CKEditor v5 @ 12.3.1

## 📋 Steps to reproduce

[`@ckeditor/ckeditor5-engine/src/conversion/downcastdispatcher#selection`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastDispatcher.html#event-selection) API docs list a `consumable`, which is not passed directly.

**Comment by jodator** [comment]
Closed by 3a68560.
