### ISSUE TITLE
Ditch guppy-pre-commit dependency

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#195]
I've just fund that guppy-pre-commit is too aggressive.
It install hooks in top-level repo when ckedtior 5 is installed as dependency.

**Comment by jodator** [comment]
Ok, I've wrongly configured `package.json` on #t/145 branch.

**Comment by Reinmar** [comment]
Just guessing, but haven't you mistakenly copied this dependency to your own project? ;)
