### ISSUE TITLE
Image tags are broken "\ instead of "

### ISSUE THREAD

**Issue by klyc261** [ckeditor/ckeditor5#1951]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by klyc261** [comment]
🐞 This is a bug report 

💻 4.12.1 Standart CK Editor


📋 Inserting images through my own local file storage (ASP.NET Core) but image tags are broken
for example one of these :

`<img src=\"/ckuploads/201908110748323278402_o4426.png\">`

The " \ " character is unnecessary and i didn't get the debug..


✅ Expected result is without any \ character..

📃 I saw that ajax loader could do that but didn't find anything.

**Comment by Mgsy** [comment]
Hi, can you tell us more about your implementation? Did you built your own upload adapter? It looks like those quotes become escaped by `\`.
