### ISSUE TITLE
Allow document.querySelector eg #editor[body]

### ISSUE THREAD

**Issue by ophian** [ckeditor/ckeditor5#1952]
🐞 Bug report 

We have textareas build as #editor[body] IDs 
`<textarea id="editor[body]">` etc
called by 
```javascript
    ClassicEditor
        .create( document.querySelector( '#editor[body]' ) )
        .catch( error => {
            console.error( error );
        } );
```
give errors.

## 💻 Version of CKEditor

v12.3.1

**Comment by Mgsy** [comment]
Hi, you shouldn't use square brackets in ID's, it's not compatible with a specification, please see a [reference](https://www.w3.org/TR/html4/types.html#type-name). 

However, if you won't resign from having square brackets in your ID, you can use `document.getElementById`, so the following code will work:

```js
ClassicEditor
        .create( document.getElementById( 'editor[body]' ) )
        .catch( error => {
            console.error( error );
        } );
```

**Comment by ophian** [comment]
Ops, thanks!

**Comment by Afluex-developer07** [comment]
ghghjghjghj

**Comment by Afluex-developer07** [comment]
**ghjghjhgjhg******ghjhgjhgjhghghg
