### ISSUE TITLE
Base64UploadAdapter within Decoupled Document editor

### ISSUE THREAD

**Issue by psuplat** [ckeditor/ckeditor5#1958]
Hi,

I've been really strugling with this for half a day now, and I really cant get this to work, and the documentation does not seem to have what I need.

Using the vue.js CKeditor5 I need to enable the Base64UploadAdapter. I have found plenty examples to make it work with the classic editor, but nothing that will work with the "Decoupled document" version.

This is my setup:

main.js
```
import CKEditor from '@ckeditor/ckeditor5-vue';
Vue.use( CKEditor );
```

PageDraft.vue
```
<template>
   <div>
      <ckeditor :editor="editor" @ready="onReady" v-model="formDraftContent" :config="editorConfig" ></ckeditor>
   </div>
</template>

<script>
import DecoupledEditor from "@ckeditor/ckeditor5-build-decoupled-document";
import axios from "axios";

export default {
  name: "PageDraft",
  props: [
    "draftContent"
  ],
  components: {},
  data() {
    return {
      editor: DecoupledEditor,
      formDraftContent: this.draftContent,
      editorConfig: {
      }
    };
  },
  mounted() {},
  methods: {
    onReady(editor) {
      // Insert the toolbar before the editable area.
      editor.ui
        .getEditableElement()
        .parentElement.insertBefore(
          editor.ui.view.toolbar.element,
          editor.ui.getEditableElement()
        );
    },
  }
};
</script>
```

The above setup work perfectly, except I cannot upload images.

So, I tried to do this:
```
...
import DecoupledEditor from "@ckeditor/ckeditor5-build-decoupled-document";
import Base64UploadAdapter from '@ckeditor/ckeditor5-upload/src/base64uploadadapter';
...
editorConfig: {
        plugins: [
          Base64UploadAdapter
        ]
        // The configuration of the editor.
      }
...
```

but, then I get errors about duplicated modules.

So, how do I include the Base64UploadAdapter plugin with the decoupled editor document?

**Comment by Mgsy** [comment]
Hi, you can't add a plugin to the build the way you did in your code snippet (as you noticed, it will cause an error about duplicated modules). As [the documentation says](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html), `Base64UploadAdapter` plugin will work right after you enable it in a build, no additional configuration is required. 

As you use Vue.js, you have two ways:
1. [Build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source) with `Base64UploadAdapter` plugin.
1. [Add a plugin to an existing build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) (in your case it will be the decoupled document build), then import it to your Vue component.
