### ISSUE TITLE
Cannot add plugins when I use nuxt.js.

### ISSUE THREAD

**Issue by MaomaoFE** [ckeditor/ckeditor5#1964]
```
ckeditor.js

import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'
import FontPlugin from '@ckeditor/ckeditor5-font/src/font'
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold'

export default class ClassicEditor extends ClassicEditorBase {}

ClassicEditor.builtinPlugins = [Bold]

ClassicEditor.defaultConfig = {
  toolbar: {
    items: ['heading', '|', 'bold']
  }
}

```
```
editor.vue

let ClassicEditor;
if (process.browser) {
  ClassicEditor = require("~/assets/ckeditor/ckeditor.js");
}

export default {
  mounted() {
    this.init();
  },
  methods: {
    init() {
      ClassicEditor.create(document.querySelector("#editor"))
        .then(editor => {})
        .catch(err => {});
    }
  }
};
```
I use ckeditor5 in nuxt.js, but when i add a plugins i get a problem. `TypeError: ClassicEditor.create is not a function`.
if i require`@ckeditor/ckeditor5-build-classic` , it's work.

Is ckeditor not supporting Nuxt.js ssr?

**Comment by Mgsy** [comment]
Hello, please take a look at our [Vue.js documentation page](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source) and try to build the editor from source with plugins of your choice. After that, let us know if the problem still occurs.

**Comment by MaomaoFE** [comment]
@Mgsy  I am using nuxtjs, whether the methods in the documentation support

**Comment by robitwtms** [comment]
@Mgsy as @MaomaoFE mentions, I am also using nuxtjs and am wondering if the methods in the documentation support it...I am going to give it a try now, but it would be nice to know (assuming you have the answer of course) if it will work before doing so. Anyway, any input would be greatly appreciated. Otherwise, I hope you have a wonderful day!

**Comment by robitwtms** [comment]
@robitwtms building ckeditor from source with nuxt.js is tricky. I just tried it failed utterly. It would be nice if they had a specific "nuxt.js" installation guide, but I know that is asking a bit much. Oh well, gonna try and again...and again...and again

**Comment by liamcharmer** [comment]
@robitwtms did you get this working?

**Comment by edgarsn** [comment]
> @robitwtms building ckeditor from source with nuxt.js is tricky. I just tried it failed utterly. It would be nice if they had a specific "nuxt.js" installation guide, but I know that is asking a bit much. Oh well, gonna try and again...and again...and again

Yeah. I'm having trouble as well. I would like to get some instructions how to build editor from source on nuxt.js. There is no problem with `@ckeditor/ckeditor5-build-classic`. Probably we're doing something wrong way.

Is there any, who could show me his `nuxt.config.js`. I'm interested how the build extend method looks like.

Thanks.

**Comment by Mgsy** [comment]
Hello guys, we've decided to open a separate [feature request](https://github.com/ckeditor/ckeditor5/issues/6071) for Nuxt.js integration. Feel free to add 👍 to the first post to bump its popularity and join the discussion.

**Comment by egbleosong** [comment]
sdafasdfsadfsadf23412
123
12
312
3
123
123123
