### ISSUE TITLE
[Docs] The docs say that base64 upload adapter is available by default

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1967]
https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html

> The @ckeditor/ckeditor5-upload package is available by default in all builds. The installation instructions are for developers interested in building their own, custom WYSIWYG editor.

This is wrong on so many levels :D We cannot say that a package is available in a build – a package is just a container. A plugin can be available. 

And no, base64 is not enabled by default. If it was, all images would be base64 by default.

**Comment by jswiderski** [comment]
I had a question about that lately as well. 

We should make it clear that although `@ckeditor/ckeditor5-upload` package is available by default in all builds, you still need to create a custom build if you wish to use that plugin.
