### ISSUE TITLE
Tests log some errors (while, perhaps they should fail)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1970]
![image](https://user-images.githubusercontent.com/156149/63252203-afe9bc00-c26f-11e9-91bd-e71254c27206.png)

IDK when this started. It might've either be caused by some changes in the engine which made those things start to fail... but then the question remains – why errors do not make the tests fail?

Or, it might've started due to the changes in the error handling mechanism. But then, again, nothing should be logged both prior to those changes and after them.

**Comment by ma2ciek** [comment]
> Make sure we throw on console.log/error() in the tests. Not sure how, but I guess we can load some file which overrides them as the very first test (just add it in the karma's config). There may be a more "standard" way to do so too.

I've tried the following added to the entry file of the automated tests and it's been working well:

```js
beforeEach( () => {
	console.log = log => { originalWarn( 'Detected \`console.log()\`:' ); throw new Error( log ); };
	console.warn = warn => { originalWarn( 'Detected \`console.warn()\`:' ); throw new Error( warn ); };
	console.error = error => { originalWarn( 'Detected \`console.error()\`:' ); throw new Error( error ); };
} );
```

Although, shouldn't this behavior be configurable, e.g. `consoleAllowed` defaulted to `false`? I can imagine someone crying when debugging a broken test 😄

**Comment by Reinmar** [comment]
Let's continue the discussion in https://github.com/ckeditor/ckeditor5/issues/1996.
