### ISSUE TITLE
Print Plugin

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#1972]
## Is this a bug report or feature request? (choose one)

 🆕 Feature request

## 📃 Other details that might be useful
In CKEditor 4 there is a [Print Plugin](https://ckeditor.com/cke4/addon/print) which displays System Print Properties dialog after pressing the button on the toolbar.  

Perhaps a similar plugin could be implemented for CKEditor 5. 

**NOTE:** The plugin is only available for Classic Editor (with contents in iframe) however it is not available for inline editor (CKEditor 5 comes only in inline versions). Perhaps there is a way to put editor contents into dynamic iframe and call the `window.print()` method from there (or a better soluion)?

------

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by AnnaTomanek** [comment]
The two new features introduced recently, [export to PDF and export to Word](https://ckeditor.com/export-to-pdf-word/), provide similar functionality (and even more). They allow you to export your WYSIWYG editor content to a portable, easy-to-print format, that can then be printed using your OS tools.

**Comment by adrianfish** [comment]
Export to PDF is a commercial license feature whereas print was just included in ckeditor4.
