### ISSUE TITLE
Android Webview could not active the upload file select when use the customer upload image component

### ISSUE THREAD

**Issue by dreamcog** [ckeditor/ckeditor5#1973]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

Ckeditor 5

## 📋 Steps to reproduce

1.I created custom image upload plugin
2.it works fine in the pc chrome,but it cannot active the file selector when i click the upload image button.
3.I test the demo in ckeditor 5 homepage, it works fine in android webview.

## ✅ Expected result

can upload image from android web view

## ❎ Actual result

 it cannot active the file selector when i click the upload image button.

## 📃 Other details that might be useful

I think there is something wrong in the code ,
when I use the custom image upload plugin and it can not use in the android webview.

if you  need i think i could make a demo page.
thanks for watching this, and hope to get answer soon.

**Comment by dreamcog** [comment]
is there anyone could help?

**Comment by Mgsy** [comment]
Hi, we've tested CKEditor 5 with WebView and all the features works fine. 

As you mentioned, the problem might be in your code, as you write your own plugin. It would be great if you can provide a live sample and a code, so we'll be able to look into it. Also, information about your Android and WebView versions will be appreciated.

**Comment by dreamcog** [comment]
> Hi, we've tested CKEditor 5 with WebView and all the features works fine.
> 
> As you mentioned, the problem might be in your code, as you write your own plugin. It would be great if you can provide a live sample and a code, so we'll be able to look into it. Also, information about your Android and WebView versions will be appreciated.

I will provide a simple soon! thanks for your help

**Comment by dreamcog** [comment]
> Hi, we've tested CKEditor 5 with WebView and all the features works fine.
> 
> As you mentioned, the problem might be in your code, as you write your own plugin. It would be great if you can provide a live sample and a code, so we'll be able to look into it. Also, information about your Android and WebView versions will be appreciated.

I will provide a sample soon! thanks for your help

**Comment by dreamcog** [comment]
> Hi, we've tested CKEditor 5 with WebView and all the features works fine.
> 
> As you mentioned, the problem might be in your code, as you write your own plugin. It would be great if you can provide a live sample and a code, so we'll be able to look into it. Also, information about your Android and WebView versions will be appreciated.

I made a link :https://jsfiddle.net/dreamcog/8q7mLz6f/20/
i found it is works in this code, but it doesn't work in my project, thanks for your time and help.
I will check my code. and try to finger it out.

thanks again.

**Comment by dreamcog** [comment]
> Hi, we've tested CKEditor 5 with WebView and all the features works fine.
> 
> As you mentioned, the problem might be in your code, as you write your own plugin. It would be great if you can provide a live sample and a code, so we'll be able to look into it. Also, information about your Android and WebView versions will be appreciated.

I made a link :https://jsfiddle.net/dreamcog/8q7mLz6f/20/
i found it is works in this code, but it doesn't work in my project, thanks for your time and help.
I will check my code. and try to finger it out.

thanks again.
