### ISSUE TITLE
[Safari] Images uploads with incorrect size

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1975]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Upload some bigger image.
2. If the issue doesn't occur, repeat step 1 few times.

## ✅ Expected result
The image is uploaded with a correct size.

## ❎ Actual result
The image is uploaded with incorrect size.

## 📃 Other details that might be useful

**Screenshot**
![Screenshot 2019-08-20 at 08 17 06](https://user-images.githubusercontent.com/20988892/63322375-90ac6680-c323-11e9-99dc-8193209303ac.png)

Tested on Safari 12.1.

**Comment by Reinmar** [comment]
Is it a regression?

**Comment by Mgsy** [comment]
It is, can't reproduce it on our [demo page](https://ckeditor.com/ckeditor-5/demo/).

**Comment by Reinmar** [comment]
Weird things are happening there :O Looks completely as a Safari bug:

![image](https://user-images.githubusercontent.com/156149/63323940-3c0aea80-c327-11e9-8a52-194598e8bdd7.png)

That green thing at the bottom is part of the checkmark.

**Comment by Reinmar** [comment]
Definitely Safari's bug. Toggling any style or resizing the window makes it recalculate all the things and yields different results.

![Aug-20-2019 08-52-50](https://user-images.githubusercontent.com/156149/63324243-f39ffc80-c327-11e9-9512-b12e20534ffc.gif)

**Comment by Reinmar** [comment]
From what I can see that's due to `display: table` that we started using.

**Comment by Reinmar** [comment]
OK, the workaround that I found is really ugly, but I can't think of something better right now: https://github.com/ckeditor/ckeditor5-image/compare/t/ckeditor5/1975?expand=1

* If we go this way we should definitely hide it behind an env check to target Safari only.
* We should also make sure that this code is not executed in unit tests – let's just ignore it there completely because testing it will be a PITA.
* We can test perhaps some other styles than `display`. Something less intrusive for the visual appearance. Ideas welcomed :)

**Comment by Mgsy** [comment]
>OK, the workaround that I found is really ugly, but I can't think of something better right now: https://github.com/ckeditor/ckeditor5-image/compare/t/ckeditor5/1975?expand=1

I've tested your solution and it fixes this problem.

**Comment by pomek** [comment]
The same issue occurs on mobile Safari (iOS).

**Comment by oleq** [comment]
I propose a [more subtle solution](https://github.com/ckeditor/ckeditor5-image/compare/t/ckeditor5/1975b?expand=1) based on https://stackoverflow.com/a/29804327/1485219. @Mgsy can you check it out?

**Comment by Reinmar** [comment]
LGTM. Instead of a timeout you force style recalculation by accesing a property. BTW, do we need the last `offsetHeight` access? Or only the middle one is needed?

**Comment by oleq** [comment]
You're right. The second one is obsolete. Updated the branch.

**Comment by Mgsy** [comment]
>I propose a more subtle solution based on https://stackoverflow.com/a/29804327/1485219. @Mgsy can you check it out?

Works fine 👌

**Comment by Reinmar** [comment]
OMFG, I wanted to check how to make this hack pass our tests in Safari, but this turned out to be a pandora's box: https://github.com/ckeditor/ckeditor5-image/issues/312.
