### ISSUE TITLE
[Docs] Errors from ckeditor-cloud-services-core should be listed in the Error codes page

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1978]
Errors defined in https://github.com/ckeditor/ckeditor-cloud-services-core

are not listed in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-fileuploader-uploading-data-failed

Other errors, from CF's code, are already included.

**Comment by Reinmar** [comment]
I guess we first need to finally close https://github.com/ckeditor/ckeditor5/issues/924.

**Comment by pomek** [comment]
After resolving #924, error docs page includes error codes from the package:

![image](https://user-images.githubusercontent.com/2270764/64598327-d2c34800-d3b7-11e9-8169-99ce5d80ba44.png)
