### ISSUE TITLE
how change language in ckeditor5-vue?

### ISSUE THREAD

**Issue by egerr10** [ckeditor/ckeditor5#1981]
Hey, guys, I'm trying to change the language, but nothing's happening.

`data() {
      return {
        editor: ClassicEditor,
        editorConfig: {
          mediaEmbed: { previewsInData: true },
          language: "ru",
        },
      };
    },`

This option also does not work. To be more precise, there are changes, but not what we would like):

`import ru from '@ckeditor/ckeditor5-build-classic/build/translations/ru';
editorConfig: {
          language: ru,
        },`

![image](https://user-images.githubusercontent.com/23010257/63351400-984a2a80-c378-11e9-845b-1d0b69cc5d67.png)

Documentation for vue.js is very scarce, hopefully in the future you will have time to add more editor configuration examples for vue, react, angular.

**Comment by Sitronik** [comment]
Hi @egerr10 I have one solution, this is an example for DecoupledEditor:
```Javascript
if (document.querySelector('.document-editor__toolbar')) {
          this.editorConfig.language = 'lang_to_change'
          this.ckEditor.destroy();
          document.querySelector('.document-editor__toolbar').children[0].remove();

          this.editor.create(document.querySelector('.document-editor__editable'), this.editorConfig).then(editor => {
            this.ckEditor = editor;
            //console.log('editor', editor.data.set(this.editorData));
            const toolbarContainer = document.querySelector('.document-editor__toolbar');
            toolbarContainer.appendChild(editor.ui.view.toolbar.element);
          });
        }
```
After that the language will be changed

**Comment by 332lfgb6** [comment]
> 

good idea.

**Comment by 332lfgb6** [comment]
> Hi @egerr10 I have one solution, this is an example for DecoupledEditor:
> 
> In your component you must have this methods:
> 
> ```js
> data() {
>     return {
>       ckeditorComponent: true,
>       editorData: '',
>       editor: DecoupledEditor,
>       editorConfig: {}
>     };
> },
> methods: {
>  forceRerender() {
>       // Remove ckeditorComponent from the DOM
>       this.ckeditorComponent = false;
> 
>       // If you like promises better you can
>       // also use nextTick this way
>       this.$nextTick().then(() => {
>         // Add the ckeditorComponent back in
>         this.ckeditorComponent = true;
>       });
>     },
>  onReady(editor) {
>       if (document.querySelector('.document-editor__toolbar') && document.querySelector('.document-editor__toolbar').children[0]) {
>         document.querySelector('.document-editor__toolbar').children[0].remove();
>       }
> 
>       const toolbarContainer = document.querySelector('.document-editor__toolbar');
>       toolbarContainer.appendChild(editor.ui.view.toolbar.element);
>     }
> }
> ```
> 
> ```
> <ckeditor v-if="ckeditorComponent" v-model="editorData" :editor="editor" :config="editorConfig" @ready="onReady"></ckeditor>
> ```
> 
> After that the language will be changed.

good idea
