### ISSUE TITLE
Removing last column marks first column as non-header

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1986]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. Paste the table below somewhere in the editor

|   | A   | B   | C   |   |
|---|-----|-----|-----|---|
| A | X   | 0-0 | 0-0 |   |
| B | 0-0 | X   | 0-0 |   |
| C | 0-0 | 0-0 | X   |   |

2. Mark first row and first column as `Header Row/Column` 
3. Select first row, last column.
4. Remove the entire column.

## ✅ Expected result

The first column shouldn't be touched.

![image](https://user-images.githubusercontent.com/2270764/63507733-b29b1a00-c4d8-11e9-9bad-23aff3a4b5e2.png)

## ❎ Actual result

The first column isn't marked as Header column.

![image](https://user-images.githubusercontent.com/2270764/63507742-ba5abe80-c4d8-11e9-99be-a3fdf894a0a9.png)

**Comment by pomek** [comment]
If two columns are headers, the first one stays as a header, the second one loses the attribute when removing the last column.

**Comment by jodator** [comment]
Probably the same case as here: https://github.com/ckeditor/ckeditor5-table/issues/203. So those should be fixed together.

**Comment by scofalik** [comment]
DUP https://github.com/ckeditor/ckeditor5-table/issues/203
