### ISSUE TITLE
Placeholder is still shown if editor isReadOnly

### ISSUE THREAD

**Issue by MCMicS** [ckeditor/ckeditor5#1987]
🐞 Bug report

## 💻 Version of CKEditor
12.3.1

## 📋 Steps to reproduce

1. Create Editor with Placeholder set
2. set it as Read only

## ✅ Expected result
Placeholder will not shown in read only editor

## ❎ Actual result
Placeholder will display in read only editor

**Comment by Reinmar** [comment]
Thanks. It seems that a simple CSS selector change should fix it.

**Comment by MCMicS** [comment]
yes. my fix was a css selector too.
But it would be nicer if the placer holder css class ist not added if read only (my opinion)

**Comment by Reinmar** [comment]
That's possible as well... Humm... I wonder if that's more of a CSS or JS logic :D I'm fine with both. @dkonopka, feel free to go either way.
