### ISSUE TITLE
Toolbar btn to view/edit code/html of editor

### ISSUE THREAD

**Issue by akvaliya** [ckeditor/ckeditor5#1989]
## Is this a bug report or feature request? (choose one)

 🆕 Feature request

## 💻 Version of CKEditor
"version": "12.3.1"

## ✅ Expected result

Toolbar button to switch between html & editor text

![](https://content.screencast.com/users/Akvaliya/folders/Jing/media/4a6375c6-076d-473c-90ff-7fdd8b3e80dd/2019-08-23_1543.png)

Does this feature exist? Is there any plan for this?

**Comment by Mgsy** [comment]
Hello, CKEditor 5 doesn't have such feature. We have an open issue for it, feel free to join the discussion - https://github.com/ckeditor/ckeditor5/issues/592.
