### ISSUE TITLE
Add --no-pull option to `gulp update`

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#199]
Sometimes I only want to change branches, without pulling changes (which takes significant amount of time).

**Comment by pomek** [comment]
A few days ago we got new alias (`gulp pull`) for `gulp update`. 

During this issue, I feel a little confused when I typed: 

```
$ gulp pull --no-pull
```

Should we perhaps consider other way - make another command (`git checkout` known as `git co`) instead of `--no-pull` option for `update` task?

**Comment by Reinmar** [comment]
Hm... true. This makes things harder :D.

**Comment by Reinmar** [comment]
I realised that I wanted to add this option because pulling is slow, but pulling is slow because it's synchronous (see #213). If we speed up the task, there will be no sense for such an option.
