### ISSUE TITLE
Comment icons in "narrowSidebar" mode have invalid button type "comment"

### ISSUE THREAD

**Issue by Discordius** [ckeditor/ckeditor5#1992]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest version, with collaborative editing and commenting enabled

## 📋 Steps to reproduce

1. Render CKEditor with collaboration as a text field in a standard HTML form
2. Change the annotation mode of the comment sidebar to "narrowSidebar"
3. Click on the icon for an existing comment

## ✅ Expected result

This just opens up the existing comments

## ❎ Actual result

Clicking on the comment submits the form, due to the icon being wrapped in a `<button type="comment">` tag. 

## 📃 Other details that might be useful

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button:

> **type**
> The default behavior of the button. Possible values are:
> + submit: The button submits the form data to the server. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.
> + reset: The button resets all the controls to their initial values, like `<input type="reset">`.
> + button: The button has no default behavior and does nothing when pressed. It can have client-side scripts associated with the element's events, which are triggered when the events occur.

"comment" is not a valid button type, meaning that the button defaults back to "submit", which causes any form that it is part of to submit. This is obviously unintended behavior.

**Comment by pjasiun** [comment]
Thanks for reporting. We will try to fix it in the next iteration.

**Comment by pjasiun** [comment]
The bug was fixed in the comments plugin. The new version, which we plan to release this month, should use the proper type of the button. I also suggested some API improvements to avoid such bugs in the future: https://github.com/ckeditor/ckeditor5/issues/2091/
