### ISSUE TITLE
CKEditor inline with Vue

### ISSUE THREAD

**Issue by OctaneInteractive** [ckeditor/ckeditor5#1993]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

I'm using:

vue-cli ^2.9.6
ckeditor5-build-inline ^12.3.1
ckeditor5-vue ^1.0.0-beta.2

## 📋 Steps to reproduce

I've tried multiple combinations based on the instructions in [the documentation for Vue](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html) but none have worked.

## ✅ Expected result

The goal here is to use the inline editor.

## ❎ Actual result

When I attempted to use the [ES6 modules version](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-es6-modules), I got the error:

> TypeError: Class constructor Cb cannot be invoked without 'new'

So I abandoned that and at the moment, I have the following:

```
<template>
	<ckeditor
	 	 :editor="CKEditor.editor"
	  	v-model="CKEditor.editorData"
	  	:config="CKEditor.editorConfig"
	  	tag-name="textarea"></ckeditor>
</template>
```

```
  // CKEditor.
  import InlineEditor from '@ckeditor/ckeditor5-build-inline'
```

```
export default {
	data() {
		return {
			CKEditor: {
				editor: InlineEditor,
				editorData: ''
				editorConfig: {}
			}
		}
	}
}
```

... which gives me the error:

> [Vue warn]: Unknown custom element: `<ckeditor>` - did you register the component correctly? For recursive components, make sure to provide the "name" option.

... for each instance of the editor in the template.

I'm guessing this is how the inline editor is used with Vue, as I've so far not found the appropriate documentation to use it with Vue.

**Comment by Mgsy** [comment]
Hi @OctaneInteractive! I've just successfully run CKEditor 5 inline build with Vue.js using [ES6 modules](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-es6-modules) guide. 

Please, make sure that you follow all the steps from the guide and your packages are updated. You can also try to reinstall dependencies.
