### ISSUE TITLE
Wiris Math equations and chemical formulas is not working with ckeditor5

### ISSUE THREAD

**Issue by rathiayush** [ckeditor/ckeditor5#1997]
🐞 Bug report  
## v12.4.0 classic build

Add npm install --save @wiris/mathtype-ckeditor5

## 📋 Steps to reproduce

1. Add mathtype-ckeditor5 to your plugin list and the toolbar configuration
```
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        plugins: [ MathType, ... ],
        toolbar: [ 'MathType', 'ChemType', ... ]
    } )

```
2. Try to open Mathtype for ckeditor toolbar

## Wiris mathtype opens as blank popup with some console errors

![wirisIssue](https://user-images.githubusercontent.com/30827484/63744876-48aab800-c8be-11e9-8d47-304ddaff8e85.PNG)
![wirisIssueConsoleErrors](https://user-images.githubusercontent.com/30827484/63744884-4ba5a880-c8be-11e9-8434-cec97007e338.PNG)

**Comment by Mgsy** [comment]
Hi, I can't reproduce your problem. Please make sure that your dependencies are updated (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)) and check our [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

**Comment by rathiayush** [comment]
@Mgsy I am using updated packages.
Please find below config this may help you to reproduce this issue.
```

{
  "name": "@ckeditor/ckeditor5-build-classic",
  "version": "12.4.0",
  "description": "The classic editor build of CKEditor 5 – the best browser-based rich text editor.",
  "keywords": [
    "ckeditor5-build",
    "ckeditor",
    "ckeditor5",
    "ckeditor 5",
    "wysiwyg",
    "rich text",
    "editor",
    "html",
    "contentEditable",
    "editing",
    "operational transformation",
    "ot",
    "collaboration",
    "collaborative",
    "real-time",
    "framework"
  ],
  "main": "./build/ckeditor.js",
  "files": [
    "build"
  ],
  "devDependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.5",
    "@ckeditor/ckeditor5-autoformat": "^11.0.5",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.4",
    "@ckeditor/ckeditor5-block-quote": "^11.1.3",
    "@ckeditor/ckeditor5-ckfinder": "^11.0.5",
    "@ckeditor/ckeditor5-core": "^12.3.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.0",
    "@ckeditor/ckeditor5-easy-image": "^11.0.5",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.4",
    "@ckeditor/ckeditor5-essentials": "^11.0.5",
    "@ckeditor/ckeditor5-heading": "^11.0.5",
    "@ckeditor/ckeditor5-image": "^14.0.0",
    "@ckeditor/ckeditor5-link": "^11.1.2",
    "@ckeditor/ckeditor5-list": "^12.1.0",
    "@ckeditor/ckeditor5-media-embed": "^11.1.4",
    "@ckeditor/ckeditor5-paragraph": "^11.0.5",
    "@ckeditor/ckeditor5-paste-from-office": "^11.1.0",
    "@ckeditor/ckeditor5-table": "^14.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^14.2.0",
    "eslint": "^5.5.0",
    "eslint-config-ckeditor5": "^2.0.0",
    "husky": "^1.3.1",
    "lint-staged": "^7.0.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^3.1.0",
    "style-loader": "^1.0.0",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "webpack": "^4.39.1",
    "webpack-cli": "^3.3.6"
  },
  "engines": {
    "node": ">=8.0.0",
    "npm": ">=5.7.1"
  },
  "author": "CKSource (http://cksource.com/)",
  "license": "GPL-2.0-or-later",
  "homepage": "https://ckeditor.com/ckeditor-5",
  "bugs": "https://github.com/ckeditor/ckeditor5/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/ckeditor/ckeditor5-build-classic.git"
  },
  "scripts": {
    "build": "webpack --mode production",
    "lint": "eslint --quiet '**/*.js'",
    "preversion": "npm run build; if [ -n \"$(git status src/ckeditor.js build/ --porcelain)\" ]; then git add -u src/ckeditor.js build/ && git commit -m 'Internal: Build.'; fi"
  },
  "lint-staged": {
    "**/*.js": [
      "eslint --quiet"
    ]
  },
  "eslintIgnore": [
    "build/**",
    "packages/**"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@wiris/mathtype-ckeditor5": "^7.16.1"
  }
}
```

Ckeditor.js
```

/**
 * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

// The editor creator to use.
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import MathType from '@wiris/mathtype-ckeditor5';

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
	Essentials,
	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	BlockQuote,
	CKFinder,
	EasyImage,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	MathType
];

// Editor configuration.
ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'bulletedList',
			'numberedList',
			'imageUpload',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'undo',
			'redo',
			'MathType'
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};
```

**Comment by Mgsy** [comment]
Thanks @rathiayush for your code samples. I've used your setup and I'm still unable to reproduce the issue - MathType works as expected.

Can you try to reinstall all the packages, rebuild the editor and see if you can still reproduce it? If so, can you prepare some sample where the problem can be reproduced?

**Comment by rathiayush** [comment]
> Thanks @rathiayush for your code samples. I've used your setup and I'm still unable to reproduce the issue - MathType works as expected.
> 
> Can you try to reinstall all the packages, rebuild the editor and see if you can still reproduce it? If so, can you prepare some sample where the problem can be reproduced?

Hi @Mgsy i can still able to reproduce at my end. Even i took latest , updated all packages and then build editor. I am only opening mathtype after editor initialization and not doing anything special.
please have a look at console error which i had attached earlier, May be you could have idea about what is going wrong.
Thanks

**Comment by Mgsy** [comment]
As I wrote before - I used your setup and it seems to be working fine. Please, create some live sample (it can be a GitHub repository) with a minimal amount of code needed to reproduce the issue and we'll look at it.

**Comment by mstermaaten** [comment]
Same issue here, @rathiayush did you fix it?

**Comment by rathiayush** [comment]
> Same issue here, @rathiayush did you fix it?

No @mstermaaten

**Comment by Mgsy** [comment]
It's hard to help you without a possibility to reproduce the issue. So, as I mentioned above, please create some live sample (it can be a GitHub repository) where we'll be able to see the error and try to find the source of it.

**Comment by aleeammar88** [comment]
I have used MathType in ckeditor 5, it was working fine but now it's giving 404 error when loading MathType. Even though i have opened MathType on your demo site, it's not working there too!
Any solution?

![image](https://user-images.githubusercontent.com/42765755/66031584-29d2bd80-e51d-11e9-8a8d-b0ce8a9548f6.png)

**Comment by Mgsy** [comment]
>I have used MathType in ckeditor 5, it was working fine but now it's giving 404 error when loading MathType. Even though i have opened MathType on your demo site, it's not working there too!
Any solution?

It was a temporary issue which has been fixed. 

I'm closing this issue due to a lack of activity.

**Comment by jeyyuu** [comment]
Hi please help. This has been my problem for two days now....I followed the instruction but Math Type wont appear in my toolbar as expected. My ckeditor would only show this: 
[
![mattyy](https://user-images.githubusercontent.com/41854183/105147297-f82f9c80-5b3b-11eb-9a7a-29469e2aede9.JPG)
](url)

See, it won't show in the toolbar. Maybe I don't really know what file on where to add the configuration as stated. Please help.

**Comment by FilipTokarski** [comment]
If you [installed and added it to the toolbar](https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html#installation) it has to be there. Looking at your screenshot - isn't it hidden and and shows up together with other toolbar icons when you click the three-dot icon?
