### ISSUE TITLE
It takes too long to create when there are multiple editors

### ISSUE THREAD

**Issue by tonyChenHey** [ckeditor/ckeditor5#1999]
## Is this a bug report or feature request? (choose one)

 🆕 Feature request

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/24632391/63759267-c6d38280-c8ef-11e9-8425-61c0077f089d.png)

## ✅ Expected result
Quickly create
## ❎ Actual result
![image](https://user-images.githubusercontent.com/24632391/63759537-43666100-c8f0-11e9-9877-181b8ede7c83.png)
It takes too long to create when there are multiple editors

**Comment by Reinmar** [comment]
How many editors do you create?

**Comment by tonyChenHey** [comment]
> 你创造了多少编辑？

About 20 or more
Because the page is a customizable component

**Comment by Reinmar** [comment]
That's 126ms per editor. Not bad, taken that this is a full application. It certainly can be improved, but, frankly speaking, I don't see a significant issue here. 

What you can do is to initialize some of the editors on demand. I'm pretty sure that not all editors are visible at once, right? Some are below the fold so the user don't need to see them immediately. You can also change your UI a bit so the user has to e.g. click an "edit" button first to enable the editor. It can also happen on first click in the text. There are multiple options here and they are more future proof than just enabling all editors at once. What if some day you will need 100 of them? Even if we cut down the time by 50%, it will still take a couple of seconds.
