### ISSUE TITLE
One of the basePath tests fails on Firefox

### ISSUE THREAD

**Issue by gregpabian** [ckeditor/ckeditor5#20]
A test called "basePath should work with script tags - \ckeditor\ckeditor.js" fails on Firefox. Tested with FF version 37.0.1.

**Comment by fredck** [comment]
That's because change the script URL to: `http://localhost:1030/tests/ckeditor/%5Cckeditor%5Cckeditor.js`

...while in Chrome we have this:
`http://localhost:1030/ckeditor/ckeditor.js`

@Reinmar, you added this test... what's the sense of it?

**Comment by Reinmar** [comment]
You mean this test https://github.com/ckeditor/ckeditor5/blob/master/tests/ckeditor/basepath.js#L23?

It checks if we can find `ckeditor.js` path even if it's loaded from Windows file system.

**Comment by fredck** [comment]
> You mean this test https://github.com/ckeditor/ckeditor5/blob/master/tests/ckeditor/basepath.js#L23?

Yes.

I've been trying to change this test, while keeping the same scope, but I got no luck. The point is that that one is not a valid URL for file system stuff and I'm afraid that it will be impossible to run that test in Firefox... maybe on Windows systems only.

Can we remove that test? Or maybe make it a regression for Firefox (non Windows?) only?

**Comment by Reinmar** [comment]
The code would need to be changed to be testable, not the test. I'm ok with removing that test (or leaving it commented for the future, so it's clear what else must work).
