### ISSUE TITLE
Strikethrough toolbar option is not coming even if i add it in the editor config for inline editor

### ISSUE THREAD

**Issue by Suresh918** [ckeditor/ckeditor5#2001]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor
5

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
Hello, if you want to use the strikethrough plugin, you should add it to the build. Please, follow our [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and see [Basic text styles documentation](https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html#installation).
