### ISSUE TITLE
Compatibility with other browsers

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#201]
So far we're testing in Chrome only. We need to bring compatibility with at least latest versions of Safari, Firefox, Opera and Edge.

**Status update (16.12.2016)**: We've been testing and using CKEditor 5 in Chrome, Safari, Firefox (51+ with enabled selection change events) and Opera – the level of stability is satisfactory as for this stage. We're planning to work on Edge support during next months.

List of known issues:

* [ ] https://github.com/ckeditor/ckeditor5-engine/issues/407 (Firefox)
* [x] https://github.com/ckeditor/ckeditor5-ui/issues/55
* [x] https://github.com/ckeditor/ckeditor5-utils/issues/19
* [ ] https://github.com/ckeditor/ckeditor5/issues/323 (Edge)
* [ ] https://github.com/ckeditor/ckeditor5/issues/380 (Edge)

Low priority:

* [ ] https://github.com/ckeditor/ckeditor5-engine/issues/592

**Comment by Reinmar** [comment]
**There's a separate discussion about browser support in: https://github.com/ckeditor/ckeditor5/issues/236.**

In this ticket, which is assigned to iteration 3, I'd propose to work only on support for the modern browsers and only for desktop (though, we see that editor works on most mobile ones too):

1. Chrome and Opera.
2. Firefox.
3. Safari.
4. Edge.

In all cases, we should support only the latest version.

Support for IE11, which according to current ideas expressed in #236 is a must have, will be added later. I think, though, that we should make a review of how CKEditor works on it now to have a better understanding of what will need to be done in the future. This is part of this task ass well.

**Comment by Reinmar** [comment]
The first thing we need to do is checking what's the actual status. This should involve running automated and manual tests and a few minutes of normal editor usage on every browser.

**Comment by Reinmar** [comment]
First thing that needs to be done is adding `--es5` option to the compiler so it produces ES5 compatible code.

**Comment by maxbarnas** [comment]
After updating tests (https://github.com/ckeditor/ckeditor5-utils/issues/2) and turning on transpilation to ES5 Chrome has 1 error, Safari has 39 (down from 154) and Edge has 45 (down from being untestable).

**Comment by maxbarnas** [comment]
**Update**

Problem with `isSurrogateHalf()` function is present on all browsers. Babel's fault seems to be evident.

The need for helper to compare HTML output is real. Firefox and Edge breaks the most because of it. Another problems shared between Edge and Firefox is `dataprocessor/xmldataprocessor` and `view/observer/selectionobserver`; they seem to break on both browsers.

**Comment by Reinmar** [comment]
> Problem with isSurrogateHalf() function is present on all browsers. Babel's fault seems to be evident.

Could you elaborate on that? I don't think that you've mentioned this issue before.

**Comment by maxbarnas** [comment]
> Could you elaborate on that? I don't think that you've mentioned this issue before.

**Comment by maxbarnas** [comment]
The `isSurrogateHalf()` function is the place, where Babel translates unicode code points in regex expression to some mangled characters, that make no sense. 

It is explained better in https://github.com/ckeditor/ckeditor5-utils/issues/66#issuecomment-242045302

**Comment by Reinmar** [comment]
Let's close this ticket. The editor works really stable on Chrome, Opera, Firefox and Safari. There are a lot of issues with Edge (you can follow them there – https://github.com/ckeditor/ckeditor5/issues/423) though...
