### ISSUE TITLE
Third–party UI for ckeditor5

### ISSUE THREAD

**Issue by rathiayush** [ckeditor/ckeditor5#2012]
🆕 Feature request  |  Other

Where can i find exapmle for custom UI for ckeditor5 ? I have read documentation [Third–party UI for ckEditor5](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/external-ui.html#readying-the-editor-side) but i have some doubts. is there any full exapmle?

**Comment by Mgsy** [comment]
Hi, can you explain your problem? The guide you've mentioned contains detailed steps how to create a custom UI with a live example at the beginning.

**Comment by rathiayush** [comment]
```
<div class="ck-editor">
    <!-- The toolbar of the editor. -->
    <div class="btn-toolbar" role="toolbar" aria-label="Editor toolbar">
        <!-- The headings dropdown. -->
        <div class="btn-group mr-2" role="group" aria-label="Headings">
            <div class="dropdown" id="heading">
              <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Headings</span></button>
              <div class="dropdown-menu" aria-labelledby="heading-button"></div>
            </div>
        </div>

        <!-- Basic styles buttons. -->
        <div class="btn-group mr-2" role="group" aria-label="Basic styles">
            <button type="button" class="btn btn-primary btn-sm" id="bold">B</button>
            <button type="button" class="btn btn-primary btn-sm" id="italic">I</button>
            <button type="button" class="btn btn-primary btn-sm" id="underline">U</button>
        </div>

        <!-- Undo and redo buttons. -->
        <div class="btn-group mr-2" role="group" aria-label="Undo">
            <button type="button" class="btn btn-primary btn-sm" id="undo">&larr;</button>
            <button type="button" class="btn btn-primary btn-sm" id="redo">&rarr;</button>
        </div>
    </div>

    <!-- The container with the data of the editor. -->
    <div id="editor">
        <p>Hello world!</p>
    </div>
</div>
```
As mentioned "you can define the actual UI of the editor in HTML"
Would this need be in our HTML page?

**Comment by Mgsy** [comment]
>As mentioned "you can define the actual UI of the editor in HTML"
Would this need be in our HTML page?

Yes, because this external UI structure will be used by the editor. I'd advise you to analyze the code once again and in case of any problems, ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/ckeditor5) - it's a better place for asking questions about using CKEditor 5 than GitHub, because more people from the community can read it and get involved.
