### ISSUE TITLE
Class attribute with array value doesn't work in Downcast converters

### ISSUE THREAD

**Issue by MendesJ** [ckeditor/ckeditor5#2018]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Custom build with the dependencies below

```json
"dependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.5",
    "@ckeditor/ckeditor5-alignment": "^11.2.0",
    "@ckeditor/ckeditor5-autoformat": "^11.0.5",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.4",
    "@ckeditor/ckeditor5-block-quote": "^11.1.3",
    "@ckeditor/ckeditor5-ckfinder": "^11.0.5",
    "@ckeditor/ckeditor5-core": "^12.3.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.5",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.5",
    "@ckeditor/ckeditor5-easy-image": "^11.0.5",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.4",
    "@ckeditor/ckeditor5-engine": "latest",
    "@ckeditor/ckeditor5-essentials": "^11.0.5",
    "@ckeditor/ckeditor5-font": "^11.2.2",
    "@ckeditor/ckeditor5-heading": "^11.0.5",
    "@ckeditor/ckeditor5-highlight": "^11.0.5",
    "@ckeditor/ckeditor5-image": "^14.0.0",
    "@ckeditor/ckeditor5-inspector": "^1.3.0",
    "@ckeditor/ckeditor5-link": "^11.1.2",
    "@ckeditor/ckeditor5-list": "^12.1.0",
    "@ckeditor/ckeditor5-media-embed": "^11.1.4",
    "@ckeditor/ckeditor5-paragraph": "^11.0.5",
    "@ckeditor/ckeditor5-paste-from-office": "^11.1.0",
    "@ckeditor/ckeditor5-table": "^14.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^14.2.0",
    "@ckeditor/ckeditor5-ui": "^14.0.0",
    "@ckeditor/ckeditor5-upload": "^12.0.0",
    "@ckeditor/ckeditor5-utils": "^14.0.0",
    "@ckeditor/ckeditor5-widget": "^11.1.0",
    "eslint": "^6.2.2",
    "eslint-config-ckeditor5": "^2.0.0",
    "husky": "^3.0.4",
    "interactjs": "^1.5.4",
    "itiriri": "^2.0.1",
    "jsbarcode": "^3.11.0",
    "lint-staged": "^9.2.5",
    "lodash-es": "^4.17.15",
    "postcss-loader": "^3.0.0",
    "qrcode": "^1.4.1",
    "raw-loader": "^3.1.0",
    "save": "^2.4.0",
    "style-loader": "^0.23.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.39.3",
    "webpack-cli": "^3.3.7"
  },
```
## 📋 Steps to reproduce

Declare a downcast converter and use elementToElement. As value for the **class** attribute put an array of strings.

``` javascript
 conversion.for('downcast')
            .elementToElement({
                model: 'tagType',
                view: (modelItem, viewWriter) => {
                    const type = modelItem.getAttribute('type')
                    const view = viewWriter.createContainerElement('div', {
                        class: ['tag-type', 'tag-type-content']
                    })

                    viewWriter.insert(viewWriter.createPositionAt(view, 0), viewWriter.createText(type))

                    return view
                }
            })
            .elementToElement({
                model: 'tagArea',
                view: (modelItem, viewWriter) => viewWriter.createContainerElement('div', {
                    class: ['tag-area', 'tag-area-content']
                })
            })
            .attributeToAttribute({
                model: {
                    name: 'tagArea',
                    key: 'type'
                },
                view: (modelAttributeValue) => ({
                    key: 'class',
                    value: [getCssClass(modelAttributeValue)]
                })
            })
```

## ✅ Expected result

Html classes separated by a space.

```html
<div class="tag-area tag-area-content tag-area-content-red">
</div>
<div class="tag-type tag-type-content">
</div>
```

## ❎ Actual result

Html classes are separated by a comma instead of a space. And the extra css class that must be added by the **attributeToAttribute**  converter is missing.

```html
<div class="tag-area,tag-area-content">
</div>
<div class="tag-type,tag-type-content">
</div>
```

## 📃 Other details that might be useful

No errors showed in the console.

I use the **attributeToAttribute** to had an extra class to the element dynamically based on the value of the attribute and it does nothing. The function is called, the value returned is correct but nothing appends.

**Comment by Mgsy** [comment]
cc @jodator

**Comment by jodator** [comment]
Hi @MendesJ for the view writer, you must provided values similarly as you'd do in HTML:

```js
const view = viewWriter.createContainerElement( 'div', {
    class: 'tag-type tag-type-content'
} );
```

Or you can use helper methods for this:

```js
const view = viewWriter.createContainerElement( 'div' );
viewWriter.addClass( ['foo', 'bar'], view );
// or
viewWriter.addClas( 'foo', view );
viewWriter.addClas( 'bar', view );
```

**Comment by MendesJ** [comment]
Hi @jodator that's what I have done after I post the issue.

In the [attributeToAttribute documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-attributeToAttribute), it says that 
>  If key is 'class', value can be a String or an array of Strings

So I thought,  it can be use for the **elementToElement** too.

About **attributeToAttribute** that doesn't add the extra CSS class, I think there is something wrong because it worked in another plugin before but maybe I am doing something wrong.

Also I have tried to use multiple **attributeToAttribute** converters on the same model attribute but only the first one is applied it would be great to define multiple converters for the same model attribute.

For example, I would have a converter for a style and another for a data

```javascript
.attributeToAttribute({
    model: {
        name: 'tag',
        key: 'x'
    },
    view: (modelAttributeValue) => ({
        key: 'style', 
        value: {
            left: modelAttributeValue
        }
    })
 })           
 .attributeToAttribute({
     model: {
         name: 'tag',
         key: 'x'
     },
     view: 'data-x'
})
 ```

**Comment by jodator** [comment]
> Also I have tried to use multiple **attributeToAttribute** converters on the same model attribute but only the first one is applied

Yes - this is the logic behind converters. You convert a model value to a view. If multiple converters are defined only one is applied (the one with highest priority or first run if priority is equal). If you wish to convert single model with many attributes you must write all of them in one converter.

This happens because we mark which model attribute values were already converted to the view by using `consumables` so the first converter will mark this attribute as converted and other will not add additional changes to the view.

ps.: I didn't notice the attribute and element converters on `tagArea` in your example. Could you write how did you define schema? It might be a case that you want to create a model's attribute to view attribute converter for a model element.

**Comment by MendesJ** [comment]
Ok for the `attributeToAttribute` I already have started to do it with only one converter.

There is how the schema is defined for the `tagArea`

```javascript
        if (!schema.isRegistered('tag'))
            schema.register('tag', {
                allowAttributes: ['id', 'type'],
                allowWhere: '$block',
                isObject: true
            })

        if (!schema.isRegistered('tagArea'))
            schema.register('tagArea', {
                allowAttributes: ['height', 'type'],
                allowIn: 'tag',
                isLimit: true
            })
```

The `downcast` converter of the `tag` element 
```javascript
.elementToElement({
    model: 'tag',
    view: (modelItem, viewWriter) => toWidget(viewWriter.createContainerElement('div', {class:'tag'}), viewWriter)
})
```

I checked the other plugin i wrote, it is identical except the schema and attributes names.

**Comment by jodator** [comment]
OK So the `attributeToAttribute()` converter for `tag` will not work with your schema as you do not have `tag`

> In the [attributeToAttribute documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-attributeToAttribute), it says that
> 
> > If key is 'class', value can be a String or an array of Strings

Yes - but this relates to the configuration key `class` only not the `viewWriter.createElement()`.

> Ok for the `attributeToAttribute` I already have started to do it with only one converter.

You can get back if you will have some issues with that approach but please paste whole code (schema + converters) and HTML data since I'm a bit lost now after updates :).

**Comment by MendesJ** [comment]
Thank you @jodator for the help. I think all my problems came from the fact the I mixed the `attributeToAttribute` configuration with the `viewWriter.createElement()`. 

 I fixed all mistakes and everything seems to work as expected.
