### ISSUE TITLE
Configurable placeholder for Title section in title plugin

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#2020]
Follow-up: https://github.com/ckeditor/ckeditor5/issues/2003.

Proposed by @jodator https://github.com/ckeditor/ckeditor5-heading/pull/130#discussion_r320017837.

A placeholder of body section in the Title plugin is configurable through `EditorConfig#placeholder` property. Placeholder of title section is hard-coded.

The question is. Do we need/want such a config option? Wouldn't be weird when the body section will be configurable through general editor config option but the title section by a plugin config option? We need to think about it.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-heading/issues/137.
