### ISSUE TITLE
Blur event is triggered while type inside a table element

### ISSUE THREAD

**Issue by bdamay** [ckeditor/ckeditor5#2024]
I intend to use the blur event on ckeditor within vueJS and i run into a problem that i don't know how to deal with. I think it might be a bug. 
Here it is: 
If i insert a table in ckeditor and type in it, the blur event is triggered on ckeditor even if don't quit the ckeditor div. And more important, i lose focus on the table.
Any help would be great 

Thanks 

## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

ckeditor5 within VueJs and webpack
    "@ckeditor/ckeditor5-build-inline": "^12.4.0",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",

## 📋 Steps to reproduce
I have this code 
In the template 
` <ckeditor @blur="blurred" :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>`

Component method:
```
 methods: {
   blurred () { console.log('blurred'); }
}

1. Insert a table in ckeditor 
2. Type in the table triggers the blur event

## ✅ Expected result

No Blur event 

## ❎ Actual result

Blur is triggered

## 📃 Other details that might be useful

**Comment by Mgsy** [comment]
Hello, described behaviour is expected, because blur event is fired when one of the editables loses focus (in your case, you move the focus from the main editable to the nested editable - a table cell).

>And more important, i lose focus on the table.

Can you provide more information about it (steps to reproduce/screencast)? I've checked it and everything seems to be working fine.

**Comment by bdamay** [comment]
Hi, thanks for your quick reply, fair enough for the blur event fired while moving into the table cell. (even if at first i think it shouldn't as strickly speaking i don't leave the editor... ? )

For the other part 
The focus is lost while typing into the table cell. Table seems to refresh itself and you lose the focus on the cell (Might be a VueJS refreshing side effect ?)

See the screencast i made. to illustrate the behavior

Have a nice day

**Comment by Mgsy** [comment]
Thanks for the screencast. Unfortunately, I can't reproduce it. Can you try to make a basic integration based on our [integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-es6-modules) (without making any additional steps) and verify whether it's still reproducible for you?

**Comment by bdamay** [comment]
I tried without anything else (no vue-loader no webpack, ... nothing but ckeditor vuejs component) and i still have the problem. 
I even removed VueJS devtools extension  i'm using in chrome...

...Speaking of which...  tried the component in Firefox and it works fine.... (There is a slight hangup while typing but cursor comme back in the cell i'm typing in and no blur event is fired)

Seems to be a problem i encounter only in Chrome... you might be able to reproduce there ?

**Comment by Mgsy** [comment]
Unfortunately, still can't reproduce it. Can you provide some live example where we'd be able to check it?

**Comment by bdamay** [comment]
Sorry i didn't have time to give you a live example as requested. 
I'll eventually reopen the subject when i'm a bit less busy
