### ISSUE TITLE
Allow users to add new hashtags using mention plugin to the editor.

### ISSUE THREAD

**Issue by ajayshukla** [ckeditor/ckeditor5#2028]
I am using ckeditor 5 and mention plugin to allow user to insert hashtag. What it does is that it allow users to select only predefined hashtag to be inserted in editor but what i want is that it should allow new hashtag to be inserted in editor as well. Please let me know how this can be programmed. If anyone can share any idea that will be great. I have already used JavaScript replace and insert content but it is taking cursor to last position after between sentence hashtag. So this is issue. So, basically, I want user to type/add new hashtags when they add  edit content like Facebook editor.

Any help or idea share is deeply appreciated.

**Comment by Reinmar** [comment]
I'm sorry, but I'm not sure I understand the problem that you have. We don't define any set of hashtags. So it's all up to your implementation to handle it. If you want to allow creating a new hashtag, just provide it in the mention feed as the user type.

**Comment by ajayshukla** [comment]
Hello @Reinmar ,

Thanks for your reply. 

We are looking to implement hashtag functionality in ckeditor 5 like this https://www.jqueryscript.net/demo/Facebook-Like-Hashtag-Highlighting-Plugin-with-jQuery-hashtags-js/

When someone type # and put letters after that it creates hashtag, so we are looking to implement this in ckeditor 5
Thanks

**Comment by Reinmar** [comment]
I created a feature request for the scenario that you described: https://github.com/ckeditor/ckeditor5-mention/issues/87.
