### ISSUE TITLE
Error caused by mathtype

### ISSUE THREAD

**Issue by qdechochen** [ckeditor/ckeditor5#2030]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

ckeditor 5

## 📋 Steps to reproduce

1. install mathtype plugin and export a build
2. setData with any html which containes  "&-amp;" (no -, escape of &)

## ❎ Actual result
ckeditor can't transform the html, and an error will be thrown. nothing displayed in editor.

## 📃 Other details that might be useful
![image](https://user-images.githubusercontent.com/1181011/64518260-6c411a00-d324-11e9-95b0-6a97325acc2f.png)

**Comment by Mgsy** [comment]
Hi @qdechochen, thanks for the report. I can reproduce this issue.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/5732.
