### ISSUE TITLE
CKEditor5 - Duplicate modules 

### ISSUE THREAD

**Issue by NaveenPrasathSS** [ckeditor/ckeditor5#2033]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor - V5

CKEditor5

## 📋 Steps to reproduce

1. Create 2 different SPFx web part and use CKEditor5 in both web parts. Use Document mode editor as editor.
2. Once the app is deployed in SharePoint, add both the web parts in same classic page

**Comment by Mgsy** [comment]
Hello, we didn't test CKEditor 5 with SharePoint, so, unfortunately, there's not much we can do. However, you can try to read solutions from our documentation page for [ckeditor-duplicated-modules](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) error and see if any of those help you. 

If not, I'd recommend asking a question on [StackOverflow](https://stackoverflow.com/) - maybe someone has done such integration and will be able to help you.
