### ISSUE TITLE
Selection warnings during unit tests

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#2038]
## Is this a bug report or feature request?

👷‍ Task

## 💻 Version of CKEditor

CKEditor v5 @ 12.4.0

## 📋 Steps to reproduce

While running all unit tests there are plenty of `WARN: ‘Cannot determine a proper selection range after insertion.’` reported. We should get rid of these and have clean output 👌

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/1996
