### ISSUE TITLE
[iOS] Dictation commands do not work

### ISSUE THREAD

**Issue by mumat** [ckeditor/ckeditor5#2044]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKeditor5 12.4.0

## 📋 Steps to reproduce

1. Open the CKeditor5 demo page on iOS
2. Start dictation on the iOS keyboard
3. Say the "New Line" or "New Paragraph" dictation command

## ✅ Expected result

A new line or a new paragraph is entered and I can dictate further content.

## ❎ Actual result

The new line or new paragraph is not entered and I cannot dictate anything until I stop the session and start a new one.

**Comment by Mgsy** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/2045.
