### ISSUE TITLE
Cannot build from source on Rails & Webpacker

### ISSUE THREAD

**Issue by imk66** [ckeditor/ckeditor5#2050]
I don't know is this is the right repo.
However, I have an error following the Building from source instructions here.

[Advanced setup - CKEditor 5 Documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source)

I'm under Rails & Webpacker 4
This is my environment.js

```
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')
const ckeditorSVG = require('./loaders/ckeditor-svg')
const ckeditorCSS = require('./loaders/ckeditor-css')
const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' )

environment.plugins.prepend('CKEditor',new CKEditorWebpackPlugin({
  language: 'en'
  })
)

environment.loaders.append('ckeditorCSS', ckeditorCSS)
environment.loaders.append('ckeditorSVG', ckeditorSVG)

const cssLoader = environment.loaders.get('css');
cssLoader.exclude = /(\.module\.[a-z]+$)|(ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css)/

const fileLoader = environment.loaders.get('file');
fileLoader.exclude = /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)
module.exports = environment
```

I create two loader for svg and css

```
const { styles } = require( '@ckeditor/ckeditor5-dev-utils' );

 module.exports = {
  test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,
  use: [
      {
          loader: 'style-loader',
          options: {
              injectType: 'singletonStyleTag'
          }
      },
      {
          loader: 'postcss-loader',
          options: styles.getPostCssConfig( {
              themeImporter: {
                  themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
              },
              minify: true
          } )
      },
  ]
}
```

and

```
module.exports = {
  test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
  use: [ 'raw-loader' ]
}
```

I append the loader in my config

```
environment.loaders.append('ckeditorCSS', ckeditorCSS)
environment.loaders.append('ckeditorSVG', ckeditorSVG)
```

It doesn't compile

```
ERROR in ./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css& (./node_modules/style-loader/dist??ref--3-0!./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-2!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css&)
Module build failed (from ./node_modules/style-loader/dist/index.js):
ValidationError: Invalid options object. Style Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { injectType?, attributes?, insert?, base? }
    at validate (/Users/imk66/workspace/ckeditor5-sample/node_modules/style-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/imk66/workspace/ckeditor5-sample/node_modules/style-loader/dist/index.js:17:28)
｢wdm｣: Failed to compile.
```

Here is the perfect code to reproduce this.
https://github.com/imk66/ckeditor5-sample

**Comment by imk66** [comment]
Hi @robypez!

I'm trying to look at your environment.js but I get an error.
#1723

Did you get the same error?

Thank you, thank you in advance.

**Comment by Mgsy** [comment]
Hello @imk66, can you share the error you experience after using a solution proposed in https://github.com/ckeditor/ckeditor5/issues/1723#issuecomment-485820678?

**Comment by imk66** [comment]
Hello @Mgsy , Yes, I am getting a compile error after using the solution suggested in the https://github.com/ckeditor/ckeditor5/issues/1723#issuecomment-485820678.

This is the error.

```
ERROR in ./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css& (./node_modules/style-loader/dist??ref--3-0!./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-2!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css&)
Module build failed (from ./node_modules/style-loader/dist/index.js):
ValidationError: Invalid options object. Style Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { injectType?, attributes?, insert?, base? }
    at validate (/Users/imk66/workspace/ckeditor5-sample/node_modules/style-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/imk66/workspace/ckeditor5-sample/node_modules/style-loader/dist/index.js:17:28)
｢wdm｣: Failed to compile.
```

**Comment by Mgsy** [comment]
Thanks.

@ma2ciek, can you take a look at it?

**Comment by ma2ciek** [comment]
Hi!

For me, it looks like a collision of the `style-loader` package versions. Could you check which version the Rails & Webpacker 4 uses by default?

> ERROR in ./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css& (./node_modules/style-loader/dist??ref--3-0!./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-2!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css&)

We can easily see, that the error comes from the `app/javascript/app.vue` path and the default vue's pipeline of webpack loaders. I guess that you might have installed the `style-loader@1` which is later used during the webpack process for vue files that accepts another version of this package to be present.

**Comment by imk66** [comment]
Thank you @ma2ciek .

I don't know what version Rails & Webpacker 4 is using by default, but I'll check it.

I certainly installed style-loader@1 later.
When I deleted style-loader@1 and tried it, the compilation was successful.

However, I think that css does not work, so I think that some correction is necessary.

<img width="1440" alt="スクリーンショット 2019-09-17 23 56 55" src="https://user-images.githubusercontent.com/55286708/65053592-211faa80-d9a7-11e9-8b2d-2e62faf999c4.png">

**Comment by imk66** [comment]
@ma2ciek 
I don't know if this is a best practice, but I was able to solve the problem.
The cause was in the setting of style-loader.

This is my environment.js

```
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')
const ckeditorSVG = require('./loaders/ckeditor-svg')
const ckeditorCSS = require('./loaders/ckeditor-css')
const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' )

environment.plugins.prepend('CKEditor',new CKEditorWebpackPlugin({
  language: 'en'
  })
)

environment.loaders.append('ckeditorCSS', ckeditorCSS)
environment.loaders.append('ckeditorSVG', ckeditorSVG)

const cssLoader = environment.loaders.get('css');
cssLoader.exclude = /(\.module\.[a-z]+$)|(ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css)/

const fileLoader = environment.loaders.get('file');
fileLoader.exclude = /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)
module.exports = environment
```

I create two loader for svg and css

```
const { styles } = require( '@ckeditor/ckeditor5-dev-utils' );

 module.exports = {
  test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,
  use: [
    'style-loader',
    'css-loader',
    {
        loader: 'postcss-loader',
        options: styles.getPostCssConfig( {
            themeImporter: {
                themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
            },
            minify: true
        } )
    },
],
}
```

and

```
module.exports = {
  test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
  use: [ 'raw-loader' ]
}
```


I append the loader in my config

``
environment.loaders.append('ckeditorCSS', ckeditorCSS)
environment.loaders.append('ckeditorSVG', ckeditorSVG)
```

**Comment by ma2ciek** [comment]
The style-loader used by the webpacker is version [0.23.1](https://github.com/rails/webpacker/blob/d0fa1d1351bfc5bb53e76b94ce6f33cf2175a879/package.json#L47), maybe that was the root of the problem as we recommend to install the 1.0.0 version.

But I also see that you've added the `css-loader` before the `style-loader`. Maybe that fixed the issue instead? Because in most of the cases the `css-loader` isn't needed when the `postcss-loader` is present.

Anyway, good that you have fixed your issue!
