### ISSUE TITLE
Cannot add form input, save and cancel buttons to dropdown menu

### ISSUE THREAD

**Issue by Hamid-Niakan** [ckeditor/ckeditor5#2053]
## Is this a bug report or feature request? (choose one)

🆕 Feature request  |  Question

## 💻 Version of CKEditor

CKEditor 5

## ✅ Expected result
adding form inputs and buttons to my dropdown menu, like media embed dropdown
![1](https://user-images.githubusercontent.com/46133027/65015695-79b75f00-d937-11e9-97ec-c1a302ea861a.png)

## 📃 Other details that might be useful
I'm trying to create a plugin for CKEditor 5 which consists of a dropdown menu, inside of the dropdown I need to have form inputs and buttons and underneath the form elements, a list of items but I can't find how to add form elements to dropdown menu.
In framework documentation there is a section called UI library (https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/ui-library.html#dropdowns)
here you can learn how to add list or toolbar to dopdown but nothing about how to add form elements.

**Comment by Mgsy** [comment]
Hi, I'd recommend you to go through our [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) to get the basic concept of creating plugins in CKEditor 5. Then, you should get familiar with our UI Library, so the link you've mentioned will be a good starting point. Our library offers many ready-to-use components, you can browse them in our [API docs](https://ckeditor.com/docs/ckeditor5/latest/api/) (UI section).

It might be a good idea to analyze our plugins to see how we implemented things you want to achieve. For example, [here](https://github.com/ckeditor/ckeditor5-media-embed/blob/master/src/ui/mediaformview.js) is a code of media embed plugin responsible for creating a form which is included in the dropdown.
