### ISSUE TITLE
Allow adding manual tests in this repository

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#2054]
## Is this a bug report or feature request? (choose one)

Other

## 📃 Other details that might be useful

Right now, if we want to tests 3rd party plugins, we need to add manual tests inside our packages (see https://github.com/ckeditor/ckeditor5-core/pull/195). Would be good to have an option to put those tests in this repository.

**Comment by mlewand** [comment]
Feature has shipped 🎉 Now you can also use a `--files` filter query to serve tests only from the root repo, like so:

```
yarn run manual -f /
yarn run manual --files /,link,typing
```
