### ISSUE TITLE
how to resolve "Some CKEditor 5 modules are duplicated"

### ISSUE THREAD

**Issue by cathy0023** [ckeditor/ckeditor5#2056]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

CKEditor-5

## 📋 Steps to reproduce

1.I use Vue.
2.I first install @ckeditor/ckeditor5-vue    and  @ckeditor/ckeditor5-build-inline
3.I install @wiris/mathtype-ckeditor5
4.Tip need install these dependencies,then I install "@ckeditor/ckeditor5-core": "^12.3.0",
"@ckeditor/ckeditor5-engine": "^14.0.0",
"@ckeditor/ckeditor5-ui": "^14.0.0",
"@ckeditor/ckeditor5-utils": "^14.0.0",
5.in page show following picture error.
![image](https://user-images.githubusercontent.com/34565525/65105655-3678f100-da08-11e9-8d0e-cce00971dfcb.png)

[##](url) ✅ Expected result

**Comment by Reinmar** [comment]
You cannot add plugins to an existing build (ckeditor5-build-inline). You must use a source version of the editor (ckeditor5-editor-inline). Check this guide out: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source
