### ISSUE TITLE
Font family not upcasting

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#2058]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

12.4.0

## 📋 Steps to reproduce

1. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html
2. Open console
3. Call `editor.setData('<p><span style="font-family:\'Times New Roman\',Times,serif;">Times font</span></p>')`

## ✅ Expected result
The editor should have the text "Times font" with font-family Times New Roman.

## ❎ Actual result
The editor has the text "Times font" with no font-family defined.

## 📃 Other details that might be useful
Issue is with the fact it compares the exact string `'Times New Roman', Times, serif` with `'Times New Roman',Times,serif`, being the space between fallback fonts the only difference.

IMHO, the mapping should apply when the font name matches, in this case the `Times New Roman`.

**Comment by Mgsy** [comment]
cc @jodator

**Comment by jodator** [comment]
Hi, Unfortunately, we know about this limitation: https://github.com/ckeditor/ckeditor5-font/issues/6. At this time we can't do much about this but I'll see if we cannot fix this issue with styles normalization (required for other features.

**Comment by dkrahn** [comment]
Thanks!!!!

By the way, great work!!!

**Comment by Reinmar** [comment]
@jodator Can't we close this ticket as a DUP? Or are they a bit different?

**Comment by jodator** [comment]
I've forgot about that. Yes it is a dup of ckeditor/ckeditor5-font#6.
