### ISSUE TITLE
Does it make sense for todo list styles to be defined in list.css?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2063]
I don't know if we'll ever add styles for the base `List` plugin but `ToDoList` is a separate one, so I'm not sure if its styles should be located in `list.css`.

**Comment by Reinmar** [comment]
cc @dkonopka @oleq

**Comment by Reinmar** [comment]
BTW, it even looks odd how we import that:

```js
import todoListIcon from '../theme/icons/todolist.svg';
import '../theme/list.css';
```

**Comment by oleq** [comment]
I agree. A `todolist.css` would make more sense. 

Can we do this on https://github.com/ckeditor/ckeditor5-list/issues/147 since we're gonna touch it anyway?
