### ISSUE TITLE
Cannot insert anything to the beginning if there content begins with a table

### ISSUE THREAD

**Issue by qdechochen** [ckeditor/ckeditor5#2067]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

ckeditor 5, classic editor

## 📋 Steps to reproduce

1. insert a table at the beginning
2. then try insert a line before the table

## ✅ Expected result
new line inserted

## ❎ Actual result
You can't because the cursor cannot be put before the table

**Comment by Mgsy** [comment]
Hello, we are aware of this issue, please see https://github.com/ckeditor/ckeditor5/issues/407. For now, you can use <kbd>Shift</kbd> + <kbd>Enter</kbd> to insert a new paragraph before the selected widget and <kbd>Enter</kbd> to insert it after.

**Comment by gkzsolt** [comment]
Hi @Mgsy,

With `Enter` to insert after, there is a problem if the selected widget is an image with "side" alignment. The the inserted new paragraph will be floated next to the image. That would be a use case, but what I need and cannot do is to have a "clear: both", to be able to start a new paragraph below. So `Enter` does not work in this case.
