### ISSUE TITLE
Must following the  license of CKEditor 5

### ISSUE THREAD

**Issue by mengjoel** [ckeditor/ckeditor5#2068]
@tplaner @Reinmar Hi,our teams use the CKEditor 5 as a component  in  a commercial software, but we don’t  modify the source code of CKEditor 5. Must our software follow the GPL's license  of CKEditor 5 ?

**Comment by mlewand** [comment]
Hey @mengjoel please use https://cksource.com/contact/ to reach out our sales team who have all the knowledge about the licensing. We use GH for tracking bugs, feature requests, tasks etc.
