### ISSUE TITLE
How do I convert mathtype to img

### ISSUE THREAD

**Issue by erwin199** [ckeditor/ckeditor5#2073]
## Is this a bug report or feature request? (choose one)

 🆕 Feature request  

## 💻 Version of CKEditor
12.4.0

## 📋 Steps to reproduce

1. Installing mathtype  plugins.

## ✅ Expected result

![image](https://user-images.githubusercontent.com/31053595/65594330-1d9eab80-dfc5-11e9-9669-09d0be23034b.png)

## ❎ Actual result
MathML code
example
`<math xmlns="http://www.w3.org/1998/Math/MathML"><msqrt><mn>3</mn></msqrt></math>`

**Comment by Mgsy** [comment]
Hi, do you mean that math formula shows up in the code as an image?

**Comment by duzhihao-github** [comment]
Math appears as an image in the editor, and converting to HTML will be mathml, which I hope will not be converted

**Comment by Mgsy** [comment]
Wiris has opened a dedicated repository for MathType integrations, so all questions and features request should be reported there. Please, let's move the discussion to the proper issue - https://github.com/wiris/html-integrations/issues/4.
