### ISSUE TITLE
Remove gitter badge from framework integrations

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#2075]
## Is this a bug report or feature request?

👷‍ Task

## 💻 Version of CKEditor

CKEditor v5 @ 12.4.0

## 📋 Steps to reproduce

Back in #2037 we said farewell to our gitter channel 👋

While browsing integrations I noticed that there are still gitter badges in the readme. E.g. in [react integration](https://github.com/ckeditor/ckeditor5-react/blob/ec340417b710e0985fd48d3eeeedaced1644ac4d/README.md).

**Comment by pomek** [comment]
Looks like the task is done.
