### ISSUE TITLE
Is there any responsive ui documentation for the balloon block editor?

### ISSUE THREAD

**Issue by imk66** [ckeditor/ckeditor5#2076]
## Is this a bug report or feature request? (choose one)
Other.
I need support.

## 💻 Version of CKEditor

ckeditor-5 balloon-block

## 📃details
https://ckeditor.com/ckeditor-5/demo/#balloon-block
I want to make balloon block editor responsive ui like this demo.

I looked for a document but couldn't find a way.

How can I make it responsive ui?
Is there a document?

**Comment by Mgsy** [comment]
>I want to make balloon block editor responsive ui like this demo.

Hello, you can create a balloon block editor using our [ready-to-use build](https://github.com/ckeditor/ckeditor5-build-balloon-block).

**Comment by imk66** [comment]
Hi, @Mgsy .Thank you for the reply.

[Rich text editor component for Vue.js - CKEditor 5 Documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source)
I read here and used the editor from source.

Here is my perfect code now.
https://github.com/imk66/ckeditor5-sample

But I can't reproduce the responsive ui.
Do I need any special plug-ins to make responsive ui?

**Comment by imk66** [comment]
I understand.
The editor is switched between showing and hiding depending on the window size.

This issue has been resolved. Thank you very much.
This issue will close.
