### ISSUE TITLE
MathType not loading even in ckeditor 5 demo site

### ISSUE THREAD

**Issue by aleeammar88** [ckeditor/ckeditor5#2079]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 CkEditor 5

I have used MathType in ckeditor 5, it was working fine but now it's giving 404 error when loading MathType. Even though i have opened MathType on your demo site, it's not working there too!
Please find attached image!

Demo Site:
https://ckeditor.com/docs/ckeditor5/latest/features/mathtype.html

![image](https://user-images.githubusercontent.com/42765755/66031141-3c002c00-e51c-11e9-932d-424ebe6f0f54.png)

**Comment by Mgsy** [comment]
Hello, thank you for the report. We are aware of this issue and working on it. I'll let you know after we fix the problem.

**Comment by aleeammar88** [comment]
> Hello, thank you for the report. We are aware of this issue and working on it. I'll let you know after we fix the problem.

Thanks @Mgsy

**Comment by Mgsy** [comment]
@aleeammar88, the issue has been resolved, thanks once again for reporting it!

**Comment by aleeammar88** [comment]
Thank you @Mgsy  for prompt action!
