### ISSUE TITLE
after install ckeditor in vuejs project ipad and e browsers not working please help me.

### ISSUE THREAD

**Issue by vasan057** [ckeditor/ckeditor5#2087]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by Mgsy** [comment]
Hi, please provide some meaningful description with steps to reproduce, error message and other details which might help with diagnosing your problem. Did you see our [Vue integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)?
