### ISSUE TITLE
Title feature should be integrated with headings dropdown

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#2089]
While I am aware of some limitations mentioned in https://github.com/ckeditor/ckeditor5/issues/2005, the current solution is pretty confusing from the UX perspective.

Consider this one from Google Docs:
![Screenshot 2019-10-07 at 14 04 43](https://user-images.githubusercontent.com/538321/66310247-ff617580-e90b-11e9-897b-ce72891bd3e0.png)

And now CKEditor 5:
![Screenshot 2019-10-07 at 14 04 53](https://user-images.githubusercontent.com/538321/66310258-05efed00-e90c-11e9-8a1f-dc0b772720fe.png)

From the user's perspective, making an element a title and making it a heading level-whatever is the same process and should be done using the same tools. In our solution this is not possible and it is highly confusing what the title element is and why you cannot assign it just like you are assigning a heading.

**Comment by pjasiun** [comment]
I need to disagree with you.

What we do is not similar to what Google Docs has. It is similar to Sublime Post editor, Medium or Grammarly:

<img width="531" alt="Screenshot 2019-10-07 at 14 16 31" src="https://user-images.githubusercontent.com/1166967/66310729-38e6b080-e90d-11e9-9103-db379964ff4d.png">

![Screenshot 2019-10-07 at 14 19 39](https://user-images.githubusercontent.com/1166967/66310902-9549d000-e90d-11e9-9dfc-0820390f3acc.png)

Note that none of these tools let you create a title using the heading menu. The role of our title plugin is to make sure that there is a single header, at the beginning of the document. I have no idea how it supposes to work with possibility to change a paragraph into a header.

What Google docs has, as a "Title" option, is just a heading type. You may create as many titles as you want, put them wherever you want. This can be achieved in CKEditor 5 using heading plugin, you do not need a separate plugin for it.

**Comment by AnnaTomanek** [comment]
Thanks for adding more context to this. I can understand the feature more now.

A question is whether the connection with the 3 tools that you listed will be natural/clear for the users or devs who integrate such an editor. My first association when discussing ANY of CKEditor 5 features is Google Docs/Word though, and I guess I'm not alone in this.

In that case I propose to make it more clear in the docs, perhaps by adding some more context like @pjasiun added above. I'll try to handle this.

**Comment by Reinmar** [comment]
I'd wait for feedback from outside. I think that this feature will be clear when implemented correctly in a target system. Whether the docs are clear... IDK. Let's see.
