### ISSUE TITLE
Should we use @module instead of namespaces?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#209]
We've known from the beginning that JSDoc allows you to organise code in modules instead of namespaces. See e.g.: http://usejsdoc.org/howto-es2015-modules.html. However, we decided to go with namespaces because that's how we'd like to see the code in a release version.

This creates issues though. If a module exports more than a default, then we have a confusing scheme how to document these. Also, there are some issue with namespaces which aren't documented. And finally, since we started exporting not only the default value, in a release e.g. an AMD's `require()` function will be returning an object with one or more properties anyway.

So I think it'd be nice to research how JSDoc organises code which is documented using modules. E.g. I'm curios how module which export only the default value are represented. Whether this isn't less readable than it could be.

**Comment by Reinmar** [comment]
I've made a research on that and it's not all roses, but neither is namespacing.

You need to see how the code needs to be documented in https://github.com/ckeditor/ckeditor5-design/tree/jsdoc-module-test/ckeditor5

And this is the result:

![screen shot 2016-09-08 at 12 21 35](https://cloud.githubusercontent.com/assets/156149/18346085/d977a1d2-75be-11e6-8478-0856d04fd5b7.png)
![screen shot 2016-09-08 at 12 21 48](https://cloud.githubusercontent.com/assets/156149/18346086/d97b1556-75be-11e6-98ed-91c14fd7faba.png)

Turns out that there are couple of problems. I described the results in https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-245549805.

The biggest problem that I have are the default exports. It's unclear how to document them, because a default export of module `ckeditor5/a` is accessible as `ckeditor5/a~A`, so there's no word about it being the default. We'd need to automatically add a note that this is the default export and should be imported as:

```js
import A from 'ckeditor5/a';
```

Pros:

* More semantically correct.
* It's easy to understand how to document multiple weird exports.
* It may get better in the future once JSDoc has a better support for ES6 modules.
* We gain the ability to document every module (which is impossible with namespaces, because in those the module name is taken by the class). Actually, it won't be even that much work to simply point a in module's document to the default export.

Cons:

* Default exports are mixed with other ones. (Should be fairly easy to automatically add a custom `@defaultExport` tag to comment before a class/function/variable. We can then do whatever we want with this.
* Links are looong. `module:ckeditor5/core/editor~Editor` instead of the current `ckeditor5.core.Editor`.

The cons are significant, but I feel that with the modules notation we at least won't need to hack JSDoc once the version with full support for ES6 is released. Using namespaces we'll be hacking forever, because we simply don't use namespaces in our code. OTOH, it'll require a bit of work to port the current code to modules.

WDYT?

**Comment by oleq** [comment]
> Using namespaces we'll be hacking forever, because we simply don't use namespaces in our code.

This's what makes me think modules are better for us.

**Comment by jodator** [comment]
@Reinmar the cons are really not that bad. Maybe only the `@defaultExport` which looks like gonna be fixed eventually.
The long links is not an issue really - only  cosmetics.

**Comment by Reinmar** [comment]
OK, thanks guys. So we're going with modules. I'll create a separate ticket to make this change as it's not going to fit into iteration 3 anyway.

**Comment by Reinmar** [comment]
Turns out that we may not need the hacks any more: https://github.com/jsdoc3/jsdoc/issues/1137#issuecomment-246523760.
