### ISSUE TITLE
Is there possible get an editable inline widget?

### ISSUE THREAD

**Issue by avayayu** [ckeditor/ckeditor5#2093]
## Is this a bug report or feature request? (choose one)

  🆕 Feature request 

## 💻 Version of CKEditor

The default one installed by yarn add.

I have read the guide Implementing an inline widget.But when I use the code on the guide,I get a placeholder which when uses typing,the placeholder convert to a plain text.There is no changes on model.
So Is there possible to get an inline widget that what I edit in the editor,the model node can change as what I edit?

**Comment by Mgsy** [comment]
Hi, currently CKEditor 5 doesn't support editable inline widgets. However, we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1729) for it. If you'd like to see it in CKEditor 5, add a thumb up to the first post, so we'll be able to track the popularity of this request.
