### ISSUE TITLE
[PFO] Editor crashes after pasting a content with multiple spaces

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#2095]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

12.4.0

## 📋 Steps to reproduce

1. Open document editor demo
2. Remove all content
3. Paste the folloing content from Word
```
                                                                            Test
```
With the resulting HTML(from Word)
```
...

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:150%'><span style='font-size:13.0pt;line-height:150%;
font-family:"Times New Roman",serif'><span
style='mso-spacerun:yes'>                                                            
</span><span style='mso-spacerun:yes'>          </span><span
style='mso-spacerun:yes'>    </span><span style='mso-spacerun:yes'> </span>Test<o:p></o:p></span></p>

...
```

## ✅ Expected result
Have word content pasted in document

## ❎ Actual result
Nothing is pasted to CKEditor 5 and in the console the following error is thrown
```
space.js:42 Uncaught TypeError: Cannot read property 'data' of undefined
    at space.js:42
    at NodeList.forEach (<anonymous>)
    at normalizeSpacerunSpans (space.js:39)
    at parseHtml (parse.js:40)
    at MSWordNormalizer.execute (mswordnormalizer.js:34)
    at Clipboard.editor.plugins.get.on.priority (pastefromoffice.js:67)
    at Clipboard.fire (emittermixin.js:207)
    at Document.listenTo.priority (clipboard.js:78)
    at Document.fire (emittermixin.js:207)
    at Document.handleInput (clipboardobserver.js:51)
```

## 📃 Other details that might be useful
- Same results in Firefox, Chrome and Edge
- From what I could see it has something to do with the way the HTML string is formed, having the span tag in one line and its style in the next one.
```
font-family:"Times New Roman",serif'><span
style='mso-spacerun:yes'>
```

**Comment by Mgsy** [comment]
Hi, thanks for the report! I can reproduce this issue. It occurs also in `v11.2.0`, so it's not a regression.

**Comment by Reinmar** [comment]
Seems like a DUP of https://github.com/ckeditor/ckeditor5/issues/5645.

**Comment by Reinmar** [comment]
I was wrong (see https://github.com/ckeditor/ckeditor5/issues/5645#issuecomment-550432710).

**Comment by Reinmar** [comment]
OK, I did a combined PR for both tickets in https://github.com/ckeditor/ckeditor5-paste-from-office/pull/89.
