### ISSUE TITLE
it will be great if we get plain input text directly from ckeditor as .getData() function for html output.

### ISSUE THREAD

**Issue by sauravraj95** [ckeditor/ckeditor5#2096]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by sauravraj95** [comment]
`<ckeditor #editorInstance tagName="textarea" [ngClass]="{'ckActive': editorData }" [editor]="editor"
                [(ngModel)]="editorData"
                [config]="{ toolbar: [ 'bold', 'italic', '|' , 'BulletedList', 'NumberedList' ]}"
                (change)="onChangeCK($event)">
              </ckeditor>`

for angular integration.

**Comment by Mgsy** [comment]
Hi, if you'd like to retrieve a plain text, you can just strip all the HTML tags from the code returned by `editor.getData()`. For example, you can use regex - `editor.getData().replace( /(<([^>]+)>)/ig, '' );`

**Comment by Prince890840** [comment]
My Question is when i integrate ckeditor into our Project then there is a task about to show character count whatever'd content paste into ckeditor then i saw a difference between the Microsoft word and Ckeditor which has too much difference.

Here I posted the difference of both, can anyone give solution how can i overcome this problem ?
1.  ![image](https://github.com/ckeditor/ckeditor5/assets/77726300/13c69838-900d-44d8-9f3f-5533a16ce2c5)
2.  ![image](https://github.com/ckeditor/ckeditor5/assets/77726300/82355299-7f98-4110-9b01-e55b720ad4de)
3.  ![image](https://github.com/ckeditor/ckeditor5/assets/77726300/a55076ce-07e5-4ee9-942e-d349a43d0361)

In above I pasted same content in ckeditor, Google Docs and Microsoft word , every editor has different result.

below is my code for the reference.

`const ReviewerNotes = ({
  notes,
  errorMessage,
  plainText,
}) => {
  const onNotesChange = useCallback((updatedEditorState) => {
    setReviewInfo({
      reviewNotes: updatedEditorState,
      errorMessage: '',
      plainText: convertHTMLToPlainText(updatedEditorState),
    });
  }, []);
  const characterLength = plainText.length;
  const scrollAndFocusEditor = (editor) => {
    const element = document.body;
    editor.focus();

    if (element) {
      window.scroll({
        top: element.scrollHeight,
        behavior: 'smooth',
      });
    }
  };

  return (
    <>
      <div className="divider divider-top" />
      <PrimaryText className="project-detail-note">
        Reviewer notes &nbsp;
        <span>(Minimum 100 characters)</span>
      </PrimaryText>
      <div>
        <TextEditor
          editorState={notes}
          error={!!errorMessage}
          characterCount={{
            isShown: true,
            character: characterLength,
          }}
          stripPastedStyles
          onEditorStateChange={onNotesChange}
          onReady={scrollAndFocusEditor}
        />
        <div className="error-label">{errorMessage}</div>
      </div>
    </>
  );
};

import { forwardRef, useMemo } from 'react';
import PropTypes from 'prop-types';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import plainTextToHtml from '@ckeditor/ckeditor5-clipboard/src/utils/plaintexttohtml';

import './editor.scss';

const editorConfig = {
  language: 'en', // fa - for persian language ( rtl )
  toolbar: {
    items: [
      'undo',
      'redo',
      'heading',
      '|',
      'bold',
      'italic',
      'link',
      'bulletedList',
      'numberedList',
      '|',
      'outdent',
      'indent',
    ],
  },
};

const TextEditor = forwardRef((
  {
    editorState,
    onEditorStateChange,
    error,
    characterCount,
    onReady,
    placeholder,
    stripPastedStyles,
    ...rest
  },
  ref,
) => {
  const { isShown, character } = characterCount ?? {};

  const handleEditorContentChange = (_event, editor) => {
    const editorContent = editor.getData();
    const editingView = editor.editing.view;

    editingView.document.on('enter', (evt, data) => {
      editor.execute(data.isSoft ? 'enter' : 'shiftEnter');

      data.preventDefault();
      evt.stop();
      editor.editing.view.scrollToTheSelection();
    }, { priority: 'high' });

    onEditorStateChange(editorContent);
  };

  const appliedConfiguration = useMemo(() => ({
    ...editorConfig,
    ...(placeholder && { placeholder }),
  }), [placeholder]);

  const handleEditor = (editor) => {
    if (stripPastedStyles) {
      editor.plugins.get('ClipboardPipeline').on('inputTransformation', (_evt, data) => {
        const dataTransfer = data.dataTransfer;

        const content = plainTextToHtml(dataTransfer.getData('text/plain'));

        data.content = editor.data.processor.toView(content);
      }, { priority: 'high' });
    }

    onReady(editor);
  };

  return (
    <div className={`text-editor-wrapper ${error ? 'ckEditor-error' : ''}`}>
      <CKEditor
        config={appliedConfiguration}
        data={editorState}
        editor={ClassicEditor}
        ref={ref}
        onChange={handleEditorContentChange}
        onReady={handleEditor}
        // eslint-disable-next-line react/jsx-props-no-spreading
        {...rest}
      />
      {isShown ? (
        <p className="character-count-box">
          {character}
        </p>
      ) : null}
    </div>
  );
});`
