### ISSUE TITLE
Disable ckeditor with class

### ISSUE THREAD

**Issue by aleixfabra** [ckeditor/ckeditor5#21]
I don't know it is already answered but I can't find how to disable ckeditor with a class name given.

First, I replace all textareas using:

``` js
CKEDITOR.replaceAll();
```

Then, I what to disable all textareas that have `disable` class name:

``` html
<textarea class="disable" name="editor"></textarea>
````

How can I do that using class instead of its name?

Thanks!

**Comment by Reinmar** [comment]
This is an issue tracker for CKEditor 5. Neither it is related to CKEditor 4 nor it is a right place to ask questions :). I can see that you asked your question on StackOverflow and this is the right place.
