### ISSUE TITLE
Unable to use authenticated upload

### ISSUE THREAD

**Issue by felipegiotto** [ckeditor/ckeditor5#2110]
Hi! I would like to make an authenticated call to my backend (with a JWT token) so I can upload an image to the server, but the plugin always make a simple POST request, without the "Authorization: Bearer ..." header.

With a simple modification on the "UploadAdapter._initRequest()", I was able to do it, but I think this should be available natively in the component.

Thanks!

**Comment by Exlord** [comment]
So this is a no go!!! and I have to make a custom build uploader and editor just so I can add a simple JWT token to the request????
