### ISSUE TITLE
Speed up package installation by using shrinkwrap or caching?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#212]
Most of CKEditor 5 packages will require the same set of dependencies, but when you try to install the whole project in dev mode we run separate `npm i` in all packages. This takes awful lot of time and basically repeats the same steps dozens of times.

https://blog.nodeswat.com/what-i-learned-from-analysing-1-65m-versions-of-node-js-modules-in-npm-a0299a614318#.gdyn7p1k6 describes some interesting ways how we could improve the installation time.

**Comment by scofalik** [comment]
I have bad memories using shrinkwrap in previous company.

There were problems all the time, but TBH noone ever explained us how it exactly works and how to deal with common problems. We also used some weird things like private npm repos.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev-env/issues/20.
