### ISSUE TITLE
The requested toolbar item is unavailable.

### ISSUE THREAD

**Issue by MansoorJafari** [ckeditor/ckeditor5#2132]
I'm using this code for set alignment to toolbar (Angular 7)

 public Editor = ClassicEditor;
     public config = {
            toolbar: [ 'heading', '|', 'bold', 'italic','|','bulletedList', 'numberedList', 'undo', 'redo','alignment' ],
     }

but give me this warning and not working

ckeditor.js:5 toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable
 {name: "alignment"}

this is my ckeditor in html 

`  
     <ckeditor [config]="config"  [editor]="Editor" ></ckeditor>
`

**Comment by Eyegabry99** [comment]
I've followed this guide but nothing seems to work. Is there a workarond?

**Comment by Mgsy** [comment]
>I've followed this guide but nothing seems to work. Is there a workarond?

Hi, if you have a question related to this guide, please open a new issue with a detailed description.

**Comment by mohsen-mohebbi** [comment]
hello i am create new plugin in angular project and get same error 
this plugin that i am added in custom build folder in my project
https://github.com/leknoppix/ckeditor5-fullscreen
So What should I do to solve the problem?
