### ISSUE TITLE
Add alignment plugin to Balloon Editor

### ISSUE THREAD

**Issue by adrienpessu** [ckeditor/ckeditor5#2133]
Hello,

I'm trying to add the plugin alignment to my custom build with balloon editor (love this one).
I have followed the instructions in the documentation [https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html#installation](https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html#installation). When I use my custom build in my angular application, I get the "ckeditor-duplicated-modules" [error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules).

I think that's because the "ckeditor5-alignment" package have the classic editor as a dependency but I'm not sure.

Do you know how can I use the plugin in the balloon editor? 

Thank you very much in advance.

PS : my custom plugin is [here](https://github.com/adrienpessu/ckeditor5-build-balloon)

**Comment by brian-learningpool** [comment]
I was just wondering if there's a different answer to this in 2020?  I'm also trying to add alignment to ckeditor5-react with ckeditor5-editor-balloon and struggling with the documentation on this.
