### ISSUE TITLE
ERROR in ./ckeditor.js Module not found: Error: Can't resolve '@ckeditor/ckeditor5-editor-classic/src/classiceditor

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#2146]
1. Setup [development environment](https://github.com/ckeditor/ckeditor5/wiki/Development-Environment)
2. `cd packages/ckeditor5-build-classic`
3. `npm install`
4. `npm run build`

```
Building 'build/ckeditor.js'...

[11:33:39] PO file doesn't exist under the path: /Users/wiktor/www/ckeditor5/packages/ckeditor5-build-classic/lang/translations/en.po.
[11:33:39] Missing translation for: Bold.
(...)
[11:33:40] Missing translation for: Text alternative.
Hash: 07753511c7c798f0c340
Version: webpack 2.7.0
Time: 22325ms
          Asset     Size  Chunks                    Chunk Names
    ckeditor.js   297 kB       0  [emitted]  [big]  main
ckeditor.js.map  1.69 MB       0  [emitted]         main
  [54] ./~/@ckeditor/ckeditor5-paragraph/src/paragraph.js 10.8 kB {0} [built]
 [127] ./~/@ckeditor/ckeditor5-image/src/imagetoolbar.js 3.08 kB {0} [built]
 [248] ./~/@ckeditor/ckeditor5-autoformat/src/autoformat.js 3.59 kB {0} [built]
 [249] ./~/@ckeditor/ckeditor5-basic-styles/src/bold.js 1.68 kB {0} [built]
 [250] ./~/@ckeditor/ckeditor5-basic-styles/src/italic.js 1.71 kB {0} [built]
 [251] ./~/@ckeditor/ckeditor5-block-quote/src/blockquote.js 2.75 kB {0} [built]
 [252] ./~/@ckeditor/ckeditor5-heading/src/heading.js 5.03 kB {0} [built]
 [253] ./~/@ckeditor/ckeditor5-image/src/image.js 789 bytes {0} [built]
 [254] ./~/@ckeditor/ckeditor5-image/src/imagecaption.js 646 bytes {0} [built]
 [255] ./~/@ckeditor/ckeditor5-image/src/imagestyle.js 1.65 kB {0} [built]
 [256] ./~/@ckeditor/ckeditor5-link/src/link.js 12 kB {0} [built]
 [257] ./~/@ckeditor/ckeditor5-list/src/list.js 3.73 kB {0} [built]
 [258] ./~/@ckeditor/ckeditor5-presets/src/essentials.js 1.23 kB {0} [built]
 [259] ./ckeditor.js 1.76 kB {0} [built]
 [444] ./~/@ckeditor/ckeditor5-widget/src/widget.js 9.4 kB {0} [built]
    + 460 hidden modules

ERROR in ./ckeditor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-editor-classic/src/classiceditor' in '/Users/wiktor/www/ckeditor5/packages/ckeditor5-build-classic'
 @ ./ckeditor.js 6:0-85

(...)

ERROR in ./ckeditor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-editor-classic/src/classiceditor' in '/Users/wiktor/www/ckeditor5/packages/ckeditor5-build-classic'
 @ ./ckeditor.js 8:21-84
 @ multi ./~/regenerator-runtime/runtime.js ./ckeditor.js
```

**Comment by MorganFrimen** [comment]
Build
       Running build
       
       > strapi@0.1.0 build /tmp/build_61c7b1db_
       > strapi build
       
       Building your admin UI with production configuration ...
       ℹ Compiling Webpack
Error: Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic' in '/tmp/build_61c7b1db_/plugins/wysiwyg/admin/src/components/CKEditor'
    at /tmp/build_61c7b1db_/node_modules/strapi-admin/index.js:70:23
    at finalCallback (/tmp/build_61c7b1db_/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/tmp/build_61c7b1db_/node_modules/webpack/lib/Compiler.js:265:20)
    at /tmp/build_61c7b1db_/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/tmp/build_61c7b1db_/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /tmp/build_61c7b1db_/node_modules/webpack/lib/Compilation.js:1173:13
    at /tmp/build_61c7b1db_/node_modules/webpack/lib/Compilation.js:1096:25
    at /tmp/build_61c7b1db_/node_modules/webpack/lib/Compilation.js:1017:13
    at /tmp/build_61c7b1db_/node_modules/neo-async/async.js:2830:7
    at /tmp/build_61c7b1db_/node_modules/neo-async/async.js:2830:7
    at done (/tmp/build_61c7b1db_/node_modules/neo-async/async.js:2863:11)
    at /tmp/build_61c7b1db_/node_modules/neo-async/async.js:2818:7
    at /tmp/build_61c7b1db_/node_modules/webpack/lib/Compilation.js:1017:13
    at /tmp/build_61c7b1db_/node_modules/neo-async/async.js:2830:7
    at /tmp/build_61c7b1db_/node_modules/neo-async/async.js:2830:7
    at done (/tmp/build_61c7b1db_/node_modules/neo-async/async.js:2863:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.SRmry/_logs/2020-12-06T14_47_17_896Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

Unknown problem, locally collected without errors

**Comment by sirdavidoflee** [comment]
I just ran into this problem while adding CKEditor to a Strapi project and tried deploying to Heroku with the same issue above and wanted to comment in case anyone else searches for this issue in the future!

Heroku doesnt run builds on subfolders or submodules, so to get this working for deploying to Heroku you just need to add the dependencies you have in the ./packages folder or whatever subfolder CKEditor is installed from and copy those dependencies into the package.json file in the root of the project in the dependencies section.

In my case for Strapi I had ./plugins/wysiwyg/package.json with two dependencies that I just had to copy into ./package.json

**Comment by AkhilSharma90** [comment]
this is a common problem when using strapi - the dependencies for ckeditor reside in the package.json file insde the plugins folder, just copy the dependencies into the main package.json file, things should work

**Comment by apostle51** [comment]
> Bir Strapi projesine CKEditor eklerken bu sorunla karşılaştım ve yukarıdaki aynı sorunla Heroku'ya konuşlandırmayı denedim ve gelecekte başka birinin bu sorunu araması durumunda yorum yapmak istedim!
> 
> Heroku, alt klasörler veya alt modüller üzerinde derlemeler çalıştırmaz, bu nedenle, bunun Heroku'ya dağıtmak için çalışmasını sağlamak için, ./packages klasörüne veya CKEditor'un hangi alt klasöründen kurulu olduğuna sahip olduğunuz bağımlılıkları eklemeniz ve bu bağımlılıkları package.json dosyasına kopyalamanız yeterlidir. bağımlılıklar bölümünde projenin kökünde.
> 
> Benim durumumda Strapi için ./plugins/wysiwyg/package.json'a sahiptim ve sadece ./package.json'a kopyalamam gereken iki bağımlılık vardı.



> I just ran into this problem while adding CKEditor to a Strapi project and tried deploying to Heroku with the same issue above and wanted to comment in case anyone else searches for this issue in the future!
> 
> Heroku doesnt run builds on subfolders or submodules, so to get this working for deploying to Heroku you just need to add the dependencies you have in the ./packages folder or whatever subfolder CKEditor is installed from and copy those dependencies into the package.json file in the root of the project in the dependencies section.
> 
> In my case for Strapi I had ./plugins/wysiwyg/package.json with two dependencies that I just had to copy into ./package.json


Thanks. it's work.
