### ISSUE TITLE
Trying to import local build in React throws error

### ISSUE THREAD

**Issue by Robyrogers** [ckeditor/ckeditor5#2174]
I am trying to configure an existing build according to the documentation but importin the build to React throws an error in lodash-es depenedency

This the error:
./src/ckeditor5-build-classic/node_modules/lodash-es/_baseClone.js
Line 151: 'keysIn' is not defined no-undef

If I use the build from npm that one is working fine

**Comment by hffariel** [comment]
Caused by eslint and solved by adding `/* eslint-disable */ ` to the built ckeditor.js . @Robyrogers @pomek

**Comment by jayjaydluffy** [comment]
@hffariel doesn't seem to work: 
![image](https://user-images.githubusercontent.com/13216855/88453674-baf39600-ce9b-11ea-8b31-7f679a0a6bb2.png). Can you please help? Thanks in advance.

**Comment by aframson** [comment]
worked for me 

> Caused by eslint and solved by adding `/* eslint-disable */ ` to the built ckeditor.js . @Robyrogers @pomek

worked for me
