### ISSUE TITLE
Replace gulp init with gulp install --all

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#219]
There's `gulp init` task now which installs all `ckeditor5-*` packages which are listed in `devDependencies` in the dev mode. You can do the same calling `gulp install <pkg-name>` for all packages. So this is confusing because install and init sound like two separate steps, while they make pretty much the same.

The idea is to have:

* `gulp install <pkg-name>`
* `gulp install --all` to do what `gulp init` does now (it installs all `devDependencies` in the dev mode).

**Comment by szymonkups** [comment]
I agree. The `gulp init` task is just a proxy to `gulp install <pkg-name>`, so there is no need for a separate name of the task.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev-env/issues/18.
