### ISSUE TITLE
DecoupledEditor -Enable image resize plugin doesn't work.

### ISSUE THREAD

**Issue by omretterry** [ckeditor/ckeditor5#2190]
#### Operation Step:
1. Install the `ckeditor5-vue` and `ckeditor5-build-decoupled-document`
2. Install the `ckeditor5-image`
3. in vue file
`import ImageResize from '@ckeditor/ckeditor5-build-decoupled-document';`
and set editor config
`extraPlugins: [ImageResize],`

![image](https://user-images.githubusercontent.com/32243578/65828344-6fe51280-e2cc-11e9-997c-aec20b19909c.png)
The image resize seems not work.I don't know how to enable the image resizing in default build. 

#### Version
```
    "@ckeditor/ckeditor5-build-decoupled-document": "^12.4.0",
    "@ckeditor/ckeditor5-image": "^14.0.0",
    "@ckeditor/ckeditor5-vue": "^1.0.0",
```
Chrome Version: v77.0.3865.90

**Comment by Mgsy** [comment]
>I don't understand why i can not resize image by default (remove the imageResize import and extraPlugins) if ImageResize plugin already exist in the build.

The case is that ImageResize plugin isn't [enabled by default in the build](https://github.com/ckeditor/ckeditor5-build-decoupled-document/blob/master/src/ckeditor.js), so you have to do it on your own, then rebuild the editor as the documentation says.

**Comment by omretterry** [comment]
Rebuild and success.Thks for help.I will close the issue.
