### ISSUE TITLE
Add requireLineFeedAtFileEnd rule to jscs

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#222]
We should add this rule to .jscs file.

Rationale:
1. https://encrypted.google.com/#hl=en&q=newline+at+end+of+file+git
2.  ![selection_040](https://cloud.githubusercontent.com/assets/247363/16329488/3ee74576-39e3-11e6-9dc5-9e1c4b5cda6d.png)

``` json
"requireLineFeedAtFileEnd": true
```

ps. since this is mostly cosmetic change I can do this for you guys.

**Comment by oskarwrobel** [comment]
Related ticket: https://github.com/ckeditor/ckeditor5-design/issues/146#issuecomment-217370896

**Comment by Reinmar** [comment]
We now use ESLint. Do we have this rule enabled?

**Comment by jodator** [comment]
Yep:
https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/eslint-config-ckeditor5/.eslintrc.js#L129-L132
