### ISSUE TITLE
Support multiple editable roots

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#2247]
CKEditor 5 engine support multiple roots in the editor.

The user should be able in the constructor of the decoupled editor to use an object where keys are editable names and walues are (`HTMLElements` or string data). Also `getData( rootName )` and `setData( rootName )` should be provided there.

Then, in the documentation, we should add a sample in https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html (in the framework section?) with the editor with multiple (two?) editable areas.

Also, decoupled editor samples need to be updated.

**Comment by martijnpieters** [comment]
After separating some functionality in the multi root example, I was able to create and destroy roots dynamically. 

One problem over here (and when I have a lot of spare time I will create an actual bug report): the current selection / focus is lost as soon as a new root is added and `setData` has been executed. This `setData` is actively setting the selection to `null`, so I had to cherry-pick some lines of code from that method to be able to set the initial data for the dynamically added root.

Proposal: don't remove the selection during `setData` if we're not setting data for the selected root.

**Comment by bbottema** [comment]
I'm a little confused, this ticket is still open, but the documentation seems to [imply](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html) that this feature is fully supported already. What's the current status?

**Comment by elsa-polo** [comment]
> After separating some functionality in the multi root example, I was able to create and destroy roots dynamically.
> 
> One problem over here (and when I have a lot of spare time I will create an actual bug report): the current selection / focus is lost as soon as a new root is added and `setData` has been executed. This `setData` is actively setting the selection to `null`, so I had to cherry-pick some lines of code from that method to be able to set the initial data for the dynamically added root.
> 
> Proposal: don't remove the selection during `setData` if we're not setting data for the selected root.

I am also trying to create and destroy roots dynamically, could you please share what you had to change to do this? Thanks:)

**Comment by Mgsy** [comment]
> I'm a little confused, this ticket is still open, but the documentation seems to [imply](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html) that this feature is fully supported already. What's the current status?

Hi! The multi-root editor is officially supported in CKEditor 5, it seems that this issue has slipped our attention, that's why it's still open. Thanks for bringing it to our attention! For everyone interested in using the multi-root editor, see [the guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/custom-editor-creator.html).

> I am also trying to create and destroy roots dynamically, could you please share what you had to change to do this? Thanks:)

Adding and removing roots dynamically is not supported yet. You can find more information about it [here](https://github.com/ckeditor/ckeditor5/issues/6291).

**Comment by jblaisdiligent** [comment]
> After separating some functionality in the multi root example, I was able to create and destroy roots dynamically.
> 
> One problem over here (and when I have a lot of spare time I will create an actual bug report): the current selection / focus is lost as soon as a new root is added and `setData` has been executed. This `setData` is actively setting the selection to `null`, so I had to cherry-pick some lines of code from that method to be able to set the initial data for the dynamically added root.
> 
> Proposal: don't remove the selection during `setData` if we're not setting data for the selected root.

Hi, I know this is an old post but, I think this post here solved your setData issues (https://github.com/ckeditor/ckeditor5/issues/8915#issuecomment-771878390)
I'd be interested in seeing how you managed to dynamically add/destroy roots dynamically, as it is a behaviour we'd like in our project. We're just starting on that atm, but if you'd have pointers or a shareable repo, it would be awesome!
Thanks
