### ISSUE TITLE
Implement font size editing plugin

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#2275]
Implement a Font Size editing plugin as part of ckeditor5-font plugin.

This issue gathers mostly [requirements](https://github.com/ckeditor/ckeditor5/issues/638) for editing part of that feature:

1. it should be [highly configurable](https://github.com/ckeditor/ckeditor5/issues/638#issuecomment-347271402) in terms of markup that it outputs - either class either inline style.
1. It should come with [set of presets](https://github.com/ckeditor/ckeditor5/issues/638#issuecomment-347265397).
1. The feature should be developed in the [dependency injection–friendly](https://github.com/ckeditor/ckeditor5/issues/425) way ([see example](https://github.com/ckeditor/ckeditor5-alignment/issues/2)).
1. Schema: I think that `fontSize` attributes should be enabled in all contexts like paragraphs, headings, etc (so probaly inside Image caption also) (if not please comment /cc @Reinmar )

**Comment by vigosofts** [comment]
Please my ckeditor loads  the smallest font as the default, how do i change the default font to "big" or "huge"?
