### ISSUE TITLE
Handling variations of font-family notations and partial matches

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2278]
When working on the initial implementation of the font family feature @jodator implemented a regexp-based solution which made the editor accept content like:

```html
<span style="font-family: &quot;Ba ba&quot;, 'Bu bu'">
<span style='font-family: "Bo bo"'>
```

Such content cannot be produced by the editor but it may pasted from outside of the editor.

During the review we decided to ignore such cases for now. The reasoning is that the editor should only be able to handle data which it produced for now and the whole spectrum of mismatched font name values is much wider:

(source: https://github.com/ckeditor/ckeditor5-font/pull/5#issuecomment-357954222)

> We only need to care about correctly loading data created with the editor. There's much more than quotes than can go wrong here and it's not yet time to worry about these situations. Some examples:
>
> * `font` was used instead of `font-family`,
> * some characters were encoded in `font-family`'s value,
> * there's only a partial match for a font family name – e.g. only the first name was used.
>
> All these cases may happen with a pasted content and a complete solution for them would be extremely complex. We've seen that in CKEditor 4 already where a bit too aggressive normalisation was actually breaking stuff rather than helping.

We need to understand which cases we should handle. Also, the "how" and "where" questions need to be answered.

**Comment by Reinmar** [comment]
To sum up what we can do here now:

* No normalization on conversion/data processing. Whatever `font-family` value is e.g. pasted, it should be converted to exactly the same value in the model. This way, we'll ensure that we'll not break the content (which might happened and actually happened in CKE4)
* The only point at which we can normalize the font value is when deciding which option in the UI should be marked as active. Here, we can have some naive heuristic.

**Comment by NoAverageJoseph** [comment]
Is there any plan to at least handle the cases where CKEditor 4 produced CSS like "font-family:Times New Roman,Times,serif;", and when edited or pasted in a CKEditor 5 editor, it matches with the "Times New Roman" font, which has CSS "font-family:'Times New Roman', Times, serif;"? I'm surprised that this isn't handled in a way where spaces, 0/1/2 quotes, and case sensitivity is taken into account. Right now, "Times New Roman" and other fonts from CKEditor 4 get completely removed when editing in CKEditor 5. This is really bad behavior, and the only solution I have is to set config.fontFamily.supportAllValues to true, which keeps all fonts the same. Doing this also introduces the possibility that strange fonts will be introduced, but I don't have a better solution.
