### ISSUE TITLE
Bundler: Ensure that it works on Windows

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#228]
Backslash all the things!

**Comment by luzfcb** [comment]
I do not know if this is relevant to this issue, but probably the simplest way to test on Windows, is enable http://www.appveyor.com/ github integration and using it to run the tests suite on Windows machine.

AppVeyor is the only "Windows Based Continuous Integration Server" that I have found to date.

**Comment by Reinmar** [comment]
Thanks for the hint. We plan to work on CI at some point so this may be useful.

Anyway, this ticket is more about fixing the current code rather than checking it, cause we know that it doesn't work on Windows.

**Comment by szymonkups** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/issues/20.
