### ISSUE TITLE
Hi! Could Font Size Icon change to the real value?

### ISSUE THREAD

**Issue by wuguokai** [ckeditor/ckeditor5#2284]
Now Font Size Icon is a svg 
![image](https://user-images.githubusercontent.com/30334643/49208771-9e1b6c80-f3f3-11e8-8042-34fe81019108.png)
I want to change it to the real value.like this:
![image](https://user-images.githubusercontent.com/30334643/49208827-cb681a80-f3f3-11e8-9f6a-3aa145bdf326.png)
How should I do it?
Thank you!

**Comment by rickycai-2020** [comment]
> Sorry! I'm so stupid. I have added the component, but throw the error:
> ![image](https://user-images.githubusercontent.com/30334643/49213609-a24d8700-f3ff-11e8-859a-1296689140b9.png)
> 1.add the component:
> ![image](https://user-images.githubusercontent.com/30334643/49213679-c610cd00-f3ff-11e8-8e5e-a3688bd1d89b.png)
> 2.import it and add the toolbar:
> ![image](https://user-images.githubusercontent.com/30334643/49213711-da54ca00-f3ff-11e8-8242-1136231a75e6.png)
> ![image](https://user-images.githubusercontent.com/30334643/49213728-e0e34180-f3ff-11e8-89f2-5a0e03b2ccdb.png)
> 3.build and use it.

I use this code block in my build-from-source CKEditor but always get the error as below screenshot
![image](https://user-images.githubusercontent.com/60695529/84388973-fe65ae00-ac27-11ea-8884-a286425a3e65.png)
Have you ever meet this issue? Do you know how to resolve it?
