### ISSUE TITLE
Document colors section for font/background color dropdowns

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#2286]
## Is this a bug report or feature request?

🆕 Feature request

## 💻 Version of CKEditor

CKEditor v5 @ 12.1.0

## 📋 Steps to reproduce

The **document colors** section of a dropdown should pick up colors present in the editor contents at a time of opening the dialog.

This means that it will simply contain unique colors used throughout the document. The colors should appear in the same order as in the document (starting from top). Also the colors should be unique within the sections (they can duplicate colors present in the generic dropdown).

## Config

There should be a **config** property allowing to customize the number of items in document colors section or allowing to disable it by setting it's value to `0`. `FontColorConfig#documentColors` will do.

```js
ClassicEditor
	.create( {
		fontColor: {
			documentColors : 0 // Disable document colors section.
		}
	} )
```

## 📃 Other details that might be useful

We initially wanted to add this feature in 12.1.0 but ended up in extracting it to this dedicated issue and pushing it back for future release.

Edit: Down the discussion you might see references to "recent colors" features, which is a different features that we considered - but ultimately we proceeded with document colors feature.

**Comment by mahindragithub** [comment]
How to Change HSL to RGB font color
