### ISSUE TITLE
Stable release date

### ISSUE THREAD

**Issue by kmoe** [ckeditor/ckeditor5#23]
Apologies if this has been answered elsewhere: I had a look and couldn't find it anywhere else.

Do you have an estimated date when a stable version of ckeditor5 will be available?

**Comment by Reinmar** [comment]
No, there's no ETA defined yet. Also, the scope of version 1.0 isn't defined yet, so it could be absolutely misleading. However, we expect to have a solution useable in **some limited scenarios** in 1.5-2 years time.

**Comment by Reinmar** [comment]
Let's merge this ticket into #24.

**Comment by fredck** [comment]
As usual, I'm more optimist than @Reinmar when it comes to dates, so I would expect the first version still in 2016. No ETA for now though.

**Comment by Reinmar** [comment]
I was hesitating between 1-1.5y and 1.5-2y, so I can agree with you ;). The first version in 2016 is doable.
