### ISSUE TITLE
Rollup bundler: Allow configuring the output format

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#230]
Followup for: #193.

Currently it's hardcoded that rollup should produce an iife.

**Comment by pomek** [comment]
This issue has been resolved in https://github.com/ckeditor/ckeditor5/commit/0c288bd2fd00c04a59c6bb81f4e8ff928bc53c0a.

Unfortunately, Bundler will be extracted to a new package (#271), so I cannot create a PR at this moment.

**Comment by pomek** [comment]
Moved the ticket to proper repository - https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/issues/9
