### ISSUE TITLE
Create a task to update libraries used by GFM DataProcessor

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#2304]
Data processor uses [marked](https://github.com/chjj/marked) and [to-markdown](https://github.com/domchristie/to-markdown) libraries, they're located under `/src/lib` directory. We need a task that will easily update these libraries. We cannot just simply install them by `npm i` and then include in our project - CKEditor 5 compiler will not handle `node-modules` dependecy.
#### Marked

After cloning GitHub repository build version of the library is located under `lib/marked.js`
#### To-markdown

After cloning GitHub repository build verions of the library is located under `dist/to-markdown.js`;

**Comment by Reinmar** [comment]
Invalid after recent changes.
