### ISSUE TITLE
Escape special characters when converting from view to data

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#2309]
Special characters when converting from view do data should be escaped. For example:

``` html
<p>*test*</p>
```

should be converted to:

``` markdown
\*test\*
```

Now they are not escaped and during back conversion to view they are treated as normal markdown formatting. This is also reported in https://github.com/ckeditor/ckeditor5-markdown-gfm/issues/4#issuecomment-248530198. List of characters to escape can be found in https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/master/tests/gfmdataprocessor/escaping.js#L9-L24.

**Comment by jodator** [comment]
Tests added in 52aed7f. Fixed by recent changes in plugin.
