### ISSUE TITLE
Inconsistent list processing

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#2310]
I did some further testing with lists conversion on GitHub and it looks like they're inserting paragraphs inside list items in some situations (so are libraries we use). We must be sure that view which is displayed in RTE will produce correct markdown output that later on will be converted by GitHub to HTML. And that HTML needs to look similar to the view presented in RTE. This is tricky sometimes.
### Example 1

Let's take this view:

``` html
<ul><li>item</li></ul><ol><li>item</li></ol>
```

our data processor will convert this to:

``` markdown
*   item

1.  item
```

But when we will convert it back to markdown, the result is:

``` html
<ul><li><p>item</p></li><li><p>item</p></li></ul>
```

This should be definitely two lists instead of one. Question is: should we insert paragraphs inside those lists? Markdown from this example is converted by GitHub to:

``` html
<ul>
<li><p>item</p></li>
</ul>

<ol>
<li>item</li>
</ol>
```

Should our view look the same, or we could skip paragraphs from the first list item and be a little inconsistent with what GitHub is doing? I believe that current list feature implementation doesn't allow to put paragraph inside list item.
### Example 2

When there is an empty line between list items, they are wrapped in paragraphs (same behavior on GitHub and our data processor)

``` markdown
* one

* two
```

is processed to:

``` html
<ul><li><p>one</p></li><li><p>two</p></li></ul>
```

The same issue as in **Example 1** - should we convert such lists to have paragraphs in `<li>` or not?

**Comment by jodator** [comment]
AFAICS it works correctly (using setData -> getData -> setData). Related PR #7307.
