### ISSUE TITLE
Find a better markdown processor

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5#2314]
[marked](https://github.com/chjj/marked) with over 300 issues and 166 pull requests the library is not maintained anymore. The last release was 10 months ago :(

Ref: https://github.com/chjj/marked/issues/938
Ref: https://github.com/compodoc/compodoc/issues/349
Ref: https://github.com/showdownjs/showdown

**Comment by phanirithvij** [comment]
@vladikoff, @mlewand  I think this issue can be closed because marked is under active development again?

**Comment by jodator** [comment]
As per #7307 comments - It looks that not doing it was a good move as marked was brought back to life ;).

Let's close this as we decided to stay with marked.
