### ISSUE TITLE
Figure tags from Image plugin are not handled

### ISSUE THREAD

**Issue by panzer-planet** [ckeditor/ckeditor5#2316]
`src/lib/to-markdown/to-markdown.js` does not seem to handle the figure tag inserted by the image plugin resulting in visible <figure> tags in rendered markdown.
![screen shot 2018-02-26 at 16 02 42](https://user-images.githubusercontent.com/4153188/36716205-1eb91ffc-1ba2-11e8-831b-600cfabe6ded.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by sg-brady** [comment]
Hi @mlewand, just wondering if there is any progress on this issue?

**Comment by jodator** [comment]
AFAICS this works with current master, so probably marked/turndown upgrade did the trick.

OTOH I'd say that similar issues would not have a big priority as the markdown plugin should be compatible with itself. In other words markdown -> editor -> markdown should be reliable.
