### ISSUE TITLE
i have some ERROR module.js:442, Please hel me. im newbie on here and bad english.

### ISSUE THREAD

**Issue by bankingtotal** [ckeditor/ckeditor5#232]
"C:\Program Files (x86)\JetBrains\WebStorm 2016.1.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" server.js --env=test
Loading Initializers: 01_mongodb.js
module.js:442
    throw err;
    ^

Error: Cannot find module 'D:\LAO Online\Webstorm/Initializers01_mongodb.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at D:\LAO Online\Webstorm\server.js:13:5
    at Array.forEach (native)
    at Object.<anonymous> (D:\LAO Online\Webstorm\server.js:11:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

Process finished with exit code 1

how to fix it ?

**Comment by Reinmar** [comment]
Are you sure this error is related to CKEditor 5? There's nothing there about it and there's some Monogo stuff, whereas CKEditor doesn't use it anywhere.

**Comment by bankingtotal** [comment]
sorry, I use webstorm. and I've been googling, and found some similar problems. I am new in this regard.
whether this problem can be fixed?

**Comment by Reinmar** [comment]
In order for us to be able to help you in any way you need to describe what problems do you have and what are you trying to do. A stack trace doesn't tell anything about what have you actually tried to do.

We need to be able to reproduce the issue. So please tell us what you're trying to do precisely.

**Comment by bankingtotal** [comment]
I'm want to make a connection for a game, that will serve to localhost. but after the coding is completed, when I do a run, an error like the above. I've been trying to update the node. but the result is still the same.

I am also confused why can this

**Comment by Reinmar** [comment]
I'm sorry, but this has nothing to do with CKEditor 5. I'm afraid you need to seek for a help somewhere else.

**Comment by bankingtotal** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20354398/16685211/c82dabda-4533-11e6-9605-1b7da3bad7bf.png)
 
whether this relates to nodejs?
Thanks for respond reinmar, I'm sorry if you are confused by what I did, but I really need help

**Comment by Reinmar** [comment]
BTW. Please read http://www.catb.org/esr/faqs/smart-questions.html. It's full of good advices on how to ask questions.
