### ISSUE TITLE
Spelling mistake in docs

### ISSUE THREAD

**Issue by turigeza** [ckeditor/ckeditor5#2323]
Spelling mistake in docs (this might be the wrong place to mention in which case sorry :)
"Binds obvervable properties"
Here 
https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html

**Comment by AnnaTomanek** [comment]
Hi @turigeza, thank you for your report. It is fixed now; the fix will be visible in the [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/) in a few hours.
