### ISSUE TITLE
Text alignment does not enable the feature command

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#2329]
![image](https://user-images.githubusercontent.com/1099479/55231715-c0978800-5223-11e9-94de-3921773a0337.png)

------

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by mlewand** [comment]
Issue is no longer reproducible. [Checked in v30](https://ckeditor.com/docs/ckeditor5/30.0.0/features/remove-format.html).
