### ISSUE TITLE
Create a release task

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#234]
We should consider trying to fully automate releasing new version of packages.

For a full automation the task would need to do this:

1. Check if it should be a next major/minor/patch version (it can be different in all repos) based on something (I'm not sure what yet).
2. Do whatever we'll figure we need to do for a release (to be discussed here: https://github.com/ckeditor/ckeditor5-design/issues/145).
3. Run `npm version` with proper args to bump up the version in packages which need to be published.
4. Publish the new version of packages on npm.

This will be a pretty complex task or a series of tasks. It also seems that it'd be good to make it usable in a specific package and it also may be easier to make it less automated (e.g. that you specify the version manually).

**Comment by Comandeer** [comment]
There is at least one project that could help in automating the release – [semantic-release](https://github.com/semantic-release/semantic-release).

It automates the detection of version's type by comparing results of tests for current and last release (if someone is broken, then it's obviously a major etc.). It is also able to generate changelog based on commit messages (of course written using some kind of convention). The only big issue we could encounter is the support for multirepo architecture (AFAIK it's intended to work with single repo libraries).

**Comment by Reinmar** [comment]
There are some ideas what to do in the [npm version](https://docs.npmjs.com/cli/version) help:

```
"scripts": {
  "preversion": "npm test",
  "version": "npm run build && git add -A dist",
  "postversion": "git push && git push --tags && rm -rf build/temp"
}
```

But that's part of the job still. E.g. we need to write a release note on GH (https://github.com/ckeditor/ckeditor5/releases). There's a lot to research and understand AFAICS. Especially that we must automate this very well.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev-env/issues/16.
