### ISSUE TITLE
Adding general exec task for running terminal commands

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#235]
While working on `'use strict';` removal task I came across situation where possibility of running command once over every package would be very handy. I have something similar to this in mind: 
```
gulp exec --task command --cmd "sed 's/find/replace' .jshintrc"
```
Would you consider this useful considering your past work on packages?

**Comment by Reinmar** [comment]
I think that such a tool would be really useful. But I'd try to make the commands shorter:

```
gulp exec --task sh "sed 's/find/replace' .jshintrc"
```

I'm not sure whether `--cmd` can be removed though. Hopefully minimist can handle it and gulp won't break.

**Comment by maxbarnas** [comment]
Making command shorter would be actually the biggest challenge of this task, but worth the effort.

**Comment by maxbarnas** [comment]
The shortest command I can achieve is:
```bash
gulp exec --sh "npm install"
```
I know it breaks convention, but this task is pretty different from usual tasks, that are very restricted - therefore safer. Breaking convention seems semi-justified. 

If that is not acceptable then we are stuck with:
```bash
gulp exec --task sh --cmd "npm install"
```

**Comment by Reinmar** [comment]
Let's better not overcomplicate it then, because the profit is just a few characters. It can be:

```
gulp exec --task sh --cmd "npm install"
```
