### ISSUE TITLE
Block indentation should be recognized as a formatting attribute

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#2358]
## Is this a bug report or feature request?

🆕 Feature request

## 💻 Version of CKEditor

CKEditor v5 @ 12.3.1

## 📋 Steps to reproduce

1. Use a sample with block indentation and remove format plugins.
1. Indent a paragraph.
1. Select all.
1. Use remove format option.

## ✅ Expected result

Indentation should be gone.

## ❎ Actual result

Indentation is not removed.

## 📃 Other details that might be useful

It's enough to add 

It should mark the attribute as [isFormatting = true](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-AttributeProperties.html#member-isFormatting) using [schema#setAttributeProperties](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html#function-setAttributeProperties).

---

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by gauravjain028** [comment]
I am also having the same issue with my custom plugins. Remove format is not considering `$block` level attributes. Please help.
