### ISSUE TITLE
Which browsers should be supported?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#236]
In iteration 3 we'll be working on browser support, but we need to understand on what browsers we should focus. The obvious ones are:

* Latest Chrome, Safari, Firefox and Edge desktop versions.
* Latest Safari and Chrome mobile versions.

Optional:

* Edge on Windows Phone (is there such a browser actually? how is it different from Edge on desktop),
* IE11 on desktop (may be costly).

**Comment by fredck** [comment]
As for today, IE11 is still a must. It is the only IE version supported by Microsoft. It's the default browser in Windows 8.1. It's supported on Windows 7, Windows 8.1, Windows Server 2008 R2, Windows Server 2012 R2, Windows 10 and Windows Server 2016.

Edge is the default browser on Windows 10 though, although IE11 is available there as well.

(Source: Wikipedia)

**Comment by mwadams** [comment]
https://support.microsoft.com/en-us/lifecycle?wa=wsignin1.0#gp/Microsoft-Internet-Explorer

It's not quite the only supported version of IE11. Windows Vista SP2 is still supported, and that means IE9 is still supported.

Your existing corporate user base who are stuck on unsupported XP machines, or Vista SP2, can, of course, continue to use CK4, so, IE11 only would seem to be a reasonable strategy.

As to Edge mobile - it is basically the same browser, but I would test on that platform, as interactions can be different. It is a highly compliant browser, though, so unless you are doing something exceptionally quirky, it should be fine.

**Comment by Reinmar** [comment]
The problem with IEs is that for us every version differs significantly. While for a typical FE developers there were no huge changes between IE9, IE10, and IE11, for us every new IE version (and then Edge) was a big problem. For a normal FE tasks new IE releases meant some bug fixes and new features, so new versions were iterative *enhancements*. For editing, a lot of existing behaviour was changing which mean that every single IE/Edge version is a different browser for us. 

Supporting IE11 will mean a lot of work. Supporting IE9 will be a hardcore. I don't think that we'll ever attempt that, especially that with every new browser the quality of the code will drop. Accumulating quirks break many design choices made before, so that affects the whole development process, making it longer and harder. Effectively, everyone loses something.

Also, taken that CKEditor 4 supports IE9 and that IE9 is used in legacy software which doesn't often get new features (that would be unblocked by CKEditor 5) and in general is mainly maintained at the same level, without bigger changes, there's very little chance that many corporate clients will upgrade to CKEditor 5 anyway (why changing something that works). I'd even consider whether the same doesn't apply to IE11. Will CKEditor 5 really be used in software produced for IE11?

> As to Edge mobile - it is basically the same browser, but I would test on that platform, as interactions can be different. It is a highly compliant browser, though, so unless you are doing something exceptionally quirky, it should be fine.

Good to hear that. I guess we're not going to support Edge mobile officially from the beginning, but we'd love to support it at some point.

**Comment by Reinmar** [comment]
I should've reported this issue in https://github.com/ckeditor/ckeditor5-design/issues, so I'll better move it there now, as I feel it's not over :). Also, we'll like to have a place to share the status of things, because as I explained in https://github.com/ckeditor/ckeditor5/issues/201#issuecomment-236166094 we're not going to work on all browsers now.

**This issue was moved to: https://github.com/ckeditor/ckeditor5-design/issues/156.**
