### ISSUE TITLE
Failed to run bender server

### ISSUE THREAD

**Issue by seasonxuan** [ckeditor/ckeditor5#238]
When I prepare development environment step by step, I get in trouble to run test .

in `ckeditor5` project
```shell
$ gulp build
...
$ bender server run
(node:16522) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
info: [plugins] Loaded plugin: benderjs-chai
info: [plugins] Loaded plugin: benderjs-coverage
info: [plugins] Loaded plugin: benderjs-mocha
info: [plugins] Loaded plugin: benderjs-promise
info: [plugins] Loaded plugin: benderjs-sinon
info: [plugins] Loaded plugin: dev/bender/plugins/ckeditor5
(node:16522) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
info: Bender.js v0.4.1 Server started at http://localhost:1030
```
![bender dashboard - chromium_005](https://cloud.githubusercontent.com/assets/16759124/16771808/78426b52-4884-11e6-81db-ad5b5e2606ce.png)

in `benderjs-example-project` [offical project](https://github.com/benderjs/benderjs-example-project) from github
```shell
$ bender server run
(node:16703) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
info: [plugins] Loaded plugin: benderjs-jasmine
(node:16703) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
info: Bender.js v0.4.1 Server started at http://localhost:1030
```
![bender dashboard - chromium_006](https://cloud.githubusercontent.com/assets/16759124/16771928/d307b704-4884-11e6-9f80-8f1e693e38a3.png)

my system environment
```shell
$ cat /etc/issue && uname -a
Linux Mint 18 Sarah \n \l
Linux zixuan-notebook 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ nvm --version && node -v && npm -v 
0.31.0
v6.1.0
3.8.6
```

**Comment by scofalik** [comment]
Hello!

It seems that `bower install` post install hook has not been executed, for unknown reason. You may either go to `node_modules/benderjs` directory and execute `npm run-script postinstall` or simply remove `benderjs` directory from `node_modules` and run `npm install` in `ckeditor5` directory again (this will take more time, though).

Let us know if it worked for you.

**Comment by scofalik** [comment]
BTW. Warnings that you get after executing `bender server run` are fine, don't worry.

**Comment by seasonxuan** [comment]
@scofalik 
Thanks a lot! It worked for me after execute `npm run-script postinstall`
