### ISSUE TITLE
Create documentation for `gulp exec` task

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#239]
`gulp exec` task and functions that can be executed this way should be included in [Development Workflow documentation](https://github.com/ckeditor/ckeditor5/wiki/Development-Workflow).

**Comment by maxbarnas** [comment]
Documentation updated https://github.com/ckeditor/ckeditor5/wiki/Development-Workflow#gulp-exec---task-task---repository-repository-name---include-root.

@szymonkups or @Reinmar please check it.

**Comment by Reinmar** [comment]
It's great. It even contains things that I thought will be missing :D.

**Comment by Reinmar** [comment]
Perhaps one detail – you can clarify that bump-year has a year hardcoded for now.
