### ISSUE TITLE
Editor crashes after deleting all contents and typing.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#242]
Steps to reproduce:

1. Open https://ckeditor5.github.io/
2. `Ctrl+A`.
3. `Del`.
4. Type `foobar`.

Errors:

1. Editor creates a new paragraph after `f`.
2. After two clicks selection/caret cannot be changed.
3. Features does not work.
4. `Uncaught TypeError: Cannot read property 'label' of undefined` is thrown.

**Comment by pomek** [comment]
But all works correctly when:
1. Open https://ckeditor5.github.io/
2. `Ctrl+A`
3. Type `foobar`.

**Comment by scofalik** [comment]
It seems that the problem is solved with the new content. It seems that `<h1>` -- unrecognized HTML tag - created this problem.

**Comment by AnnaTomanek** [comment]
For reference, here is the "before" and "after" content: https://github.com/CKEditor5/ckeditor5.github.io/commit/448f2a01dade1aa650455006295e06008b13e3a0#diff-eacf331f0ffc35d4b482f1d15a887d3bL51

I confirm it had the issues described above yesterday :) Here is the gif that Wojtek recorded:

![cke5](https://cloud.githubusercontent.com/assets/538321/16869475/4a8cd09e-4a7d-11e6-9859-d3c99e8088ef.gif)

**Comment by Reinmar** [comment]
I think that this issue is caused by https://github.com/ckeditor/ckeditor5-engine/issues/520, but let's keep the original report open as well.

**Comment by Reinmar** [comment]
Curious, I can't reproduce the issue any more regardless of the content... Either something changed in Chrome recently (which is possible) or I don't know...

Anyway, I think that the bug is still there, just invisible. Even if they changed something in this case, I'm pretty sure you should be able to reproduce the issue in some other way. https://github.com/ckeditor/ckeditor5-engine/issues/520 describes a bit more details why.

**Comment by fredck** [comment]
Weird... I can't reproduce this any more as well. Maybe they saw this issue and fixed the browser? :D

Anyway, as you can see in the screencast, the text was not any more a heading after delete, which is not the case now.

@scofalik, @AnnaTomanek, @wojtekidd: are you guys still able to reproduce it?

**Comment by Reinmar** [comment]
I was still able to reproduce this on Safari: http://giphy.com/gifs/3oEjI9qZIWjFsRToEo – there's an empty paragraph below the heading in which the text appears.

**Comment by fredck** [comment]
From past experience, it feels like those "fixing paragraphs" automatically created by the browser when the selection ends up at the root element.

**Comment by Reinmar** [comment]
OK, I've spent now enough time to be able to tell that this is exactly https://github.com/ckeditor/ckeditor5-engine/issues/520.
