### ISSUE TITLE
No editor appear after bundle

### ISSUE THREAD

**Issue by seasonxuan** [ckeditor/ckeditor5#244]
I want to see the basic editor, So I execute tasks
```
$ gulp build
...
$ gulp bundle --config dev/tasks/bundle/build-config-standard.js
...
[22:13:37] Starting 'bundle:generate'...
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
[22:13:47] Finished 'bundle:generate' after 9.92 s
...
```
It's normal? But I can't see editor when I open `file:///home/zixuan/Project/ckeditor5-all/ckeditor5/index.html` in chromium as follow.
```html
<!-- index.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="bundle/ckeditor.css">
    </head>
    <body>
        <div id="editor">
            <h1>Hello!</h1>
            <p>I'm a CKEditor5 instance.</p>
        </div>

        <script src="bundle/ckeditor.js"></script>
        <script>
            const classicEditor = ClassicEditor.create( document.getElementById( 'editor' ), {
                toolbar: [ 'headings', 'bold', 'italic', 'undo', 'redo' ]
            } );
        </script>
    </body>
</html>
```
I can see the sample text, but I can't edit it. No error and warn appear in chromium console!

**Comment by oskarwrobel** [comment]
Hi!

Thanks for testing CKEditor5.

Lets try to figure out what might happened.

## # 1

```
[22:13:37] Starting 'bundle:generate'...
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
[22:13:47] Finished 'bundle:generate' after 9.92 s
```
There is no error or warning from rollup (we are using rollup.js to bundle js files) and task was executing for almost 10 seconds so we can assume that bundling process went well. But to be 100% sure please check if `ckeditor5/bundle/` directory contains these files:
- ckeditor.js (~1.38 MB)
- ckeditor.min.js (~245 kB)
- ckeditor.css (~33 kB)
- ckeditor.min.css (~7kb)

## # 2
```
file:///home/zixuan/Project/ckeditor5-all/ckeditor5/index.html
```

```html
<!-- index.html -->
...
<link rel="stylesheet" href="bundle/ckeditor.css">
...
<script src="bundle/ckeditor.js"></script>
...
```
Looks like `index.html` file is in the right place and paths to static files are correct. Does your directory structure look like that?
```
ckeditor5
|
|-bundle
|  |-ckeditor.js
|  |-ckeditor.css
|
|-index.html
```

## # 3
- what is your node.js version?
- what is your Chromium version?
- what Operation System you use?

This is very strange that there is no error on your browser console. Have you tried to run this example using some local web server like https://github.com/indexzero/http-server?

**Comment by oskarwrobel** [comment]
Sorry for closing this ticket. Wrong button :)

**Comment by seasonxuan** [comment]
#  1 & 2
`/home/zixuan/Project/ckeditor5-all/ckeditor5` is the root path of the repository, I just put `index.html` in ckeditor root path. the related directory structure look like that.
 ```
ckeditor5
|
|-bundle
|  |-ckeditor.css
|  |-ckeditor.js
|  |-ckeditor.min.css
|  |-ckeditor.min.js
|-index.html
```
```Bash
$ cd /home/zixuan/Project/ckeditor5-all/ckeditor5
$ gulp bundle --config dev/tasks/bundle/build-config-standard.js
...
[11:25:37] Starting 'bundle:generate'...
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
[11:25:46] Deleted file '/home/zixuan/Project/ckeditor5-all/ckeditor5/bundle/tmp'.
[11:25:46] Finished 'bundle:generate' after 9.88 s
[11:25:46] Starting 'bundle:minify:js'...
[11:25:46] Starting 'bundle:minify:css'...
[11:25:50] Finished 'bundle:minify:css' after 3.19 s
[11:25:50] Finished 'bundle:minify:js' after 3.19 s
[11:25:50] 
Bundle summary:
ckeditor.js: 1.38 MB (gzipped: 260.86 kB)
ckeditor.css: 35.27 kB (gzipped: 7.74 kB)
ckeditor.min.js: 274.41 kB (gzipped: 66.59 kB)
ckeditor.min.css: 7 kB (gzipped: 1.71 kB)
[11:25:50] Finished 'bundle' after 20 s
```
# 3
The environment  as follow. Git repository had been updated to yesterday(July 15).
```Bash
$ cat /etc/issue && uname -a && chromium-browser --version
Linux Mint 18 Sarah \n \l
Linux zixuan-notebook 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Using PPAPI flash.
Chromium 51.0.2704.79 Built on Ubuntu 16.04, running on LinuxMint 18
$ nvm --version && node -v && npm -v
0.31.0
v6.1.0
3.8.6
```
# 4
Visit `index.html` via chromium. But no error and warn!
```Bash
$ http-server
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://192.168.1.41:8080
  http://192.168.1.42:8080
Hit CTRL-C to stop the server
```
![localhost 8080 - chromium_007](https://cloud.githubusercontent.com/assets/16759124/16892608/f3aa1574-4b4a-11e6-8671-1448a770a4a4.png)

# 5
Test can work after `bender server run` !
![build-amd-tests-basic-styles-manual-basic-styles - chromium_008](https://cloud.githubusercontent.com/assets/16759124/16892664/2cfc3a1c-4b4d-11e6-8082-eb016d01dcaa.png)

**Comment by Reinmar** [comment]
That's super strange... but there must be something wrong somewhere, so let's check :D.

First of all, when dealing with promises always catch errors. So instead of:

```js
            const classicEditor = ClassicEditor.create( document.getElementById( 'editor' ), {
                toolbar: [ 'headings', 'bold', 'italic', 'undo', 'redo' ]
            } );
```

You should have something like:

```js
ClassicEditor.create( document.getElementById( 'editor' ), {
                toolbar: [ 'headings', 'bold', 'italic', 'undo', 'redo' ]
} )
.then( editor => {
	window.editor = editor;
} )
.catch( err => {
	console.error( err.stack );
} );
```

If this still gives no clues, then please upload the whole package (with the bundle and index file) somewhere so we can check it.

**Comment by Reinmar** [comment]
BTW. I updated the wiki: https://github.com/ckeditor/ckeditor5/wiki/Development-Workflow/_compare/171735372747b35aba72438b3d84e25b1ce1129a...8327343704007ae90bcc1b2e452111ff3eda6616

**Comment by seasonxuan** [comment]
The problem still remains. The attachment as follow contains the bundle and index file .
[ckeditor5.tar.gz](https://github.com/ckeditor/ckeditor5/files/373558/ckeditor5.tar.gz)

**Comment by Reinmar** [comment]
I got it finally. You can't have code in a `<script>` element that contains `src`. It should be:

```html
        <script src="bundle/ckeditor.js"></script>
        <script>
            ClassicEditor.create( document.getElementById( 'editor' ), {
                toolbar: [ 'headings', 'bold', 'italic', 'undo', 'redo' ]
            } )
            .then( function( editor ) {
                window.editor = editor;
            } )
            .catch( function( err ) {
                console.error( err.stack );
            } );
        </script>
```

The sample in the wiki is correct and after I changed the `index.html` in your package, everything worked fine.
