### ISSUE TITLE
Handle h1 even if editor is configured to support h2+

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2455]
I think we discussed it somewhere but I can't find it reported.

Basically, the idea is that, since the editor is by default configured to support h2+, when you paste a h1, it gets converted into a paragraph. A more useful behaviour would be if h1 was converted to h2 (and heading1 in the model, to be precise) at that point.

Also, when working on an answer to https://stackoverflow.com/questions/49052613/is-it-possible-to-attach-an-inline-editor-to-an-h1-in-ckeditor5 I realised that if we made this behaviour (h1 -> h2) available for `setData()` as well, there might be a new kind of confusion among developers. Suddenly, the h1 elements won't be dropped but they will become h2s.

**Comment by 2-fly-4-ai** [comment]
Why would it convert h1 to h2? Am I missing something? I get that I should not have an h1 in my article's body, but this caught me off guard. Good to know I'm not going crazy.
