### ISSUE TITLE
Dealing with cross-repo changes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#246]
CKEditor 5 uses [multi-repo architecture](https://medium.com/content-uneditable/why-we-chose-a-multirepo-architecture-for-ckeditor-5-54c7e50af1f5). One of the downsides of this solution is that some changes in one repo may require changes in other repos as well.

I think that there are two possible ways to organise such changes, in a way which will be... organised :D.

1. In the repository which triggers some change you create a ticket and a PR for that ticket (branch name `t/xxx`). In other repositories you create only PRs but clearly referencing the original PR (branch names `t/ckeditor5-trigger-repo/xxx`).

  Now, to mark that some changes were made in all those repositories, you add the original ticket **and** other PRs (so those which don't have their respective tickets) to the current milestone. This way in all repositories in which something's changed, there's some "issue" (PRs are kind of issues as well) in the milestone.

2. We create tickets for every single PR made to any repo. If one ticket triggers changes in 5 other repos, then you create 5 additional tickets.

The second solution looks better from the "history" perspective. It adds more overhead, but just by checking issues you can learn what has changed. This will be important when releasing suff and, most importantly, for the community when assessing releases. However, the first way may be acceptable as well, because changes are marked within milestones anyway, just not as normal issues:

(this screenshot shows that a PR and issue was added to a milestone, which isn't the point – I've just wanted to show that PRs are displayed in a milestone)

![screen shot 2016-07-19 at 11 52 23](https://cloud.githubusercontent.com/assets/156149/16945900/5bce501c-4da7-11e6-814a-52d5dd7ff148.png)

However, it may be confusing why we're milestoning some PRs and some we don't. I'm fine with that, but are you? Or have you got other ideas?

**Comment by oleq** [comment]
I'm for 2. More work but less confusion.

**Comment by scofalik** [comment]
I'm also for second solution. Seems to be more unified.

**Comment by pomek** [comment]
The same as guys above.

**Comment by maxbarnas** [comment]
I am for second solution. Referencing other issues, at least in _main_ issue, would be nice too.

**Comment by fredck** [comment]
"2", especially because in that way each ticket will be reported on the point of view of the specific repos, promoting better separation.

**Comment by Reinmar** [comment]
Thanks guys. I haven't expected that we'll all agree so fast :)

**Comment by Reinmar** [comment]
So if we go with (2), then the first question that appeared today was: should you put all related tickets on review or just the main one?

I'm for all.

**Comment by szymonkups** [comment]
Just a question regarding second option: when we create separate issues for each repository - should we put `status:onreview` tag to each issue or only to the issue that triggers all the changes (and reference other issues inside)? It's not that big deal but I think putting just main issue on a review will cause a little less mess on our task board, and will provide single starting point to review and close all related issues.
WDYT?

**Comment by scofalik** [comment]
If we won't have any problems with forgotten, not closed "related tickets" I am for putting only one issue on review. I agree with @szymonkups that having them all on review may be messy. But it would be more messy if we forget about closing some tickets. But AFAIK, they should get closed after PR is closed, right?

**Comment by Reinmar** [comment]
Hm, you may be right that it's enough to put just the main one. By merging other PRs you'll be automatically closing other tickets (because, ofc, we all use "Fixes #XXX." ;)). So +1, for just the main one.
