### ISSUE TITLE
Make title placeholder configurable

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#2472]
The title placeholder should be configurable. Also, the default value should be better. @AnnaTomanek: can you propose better values for the default placeholders?

**Comment by Reinmar** [comment]
> I introduced the default placeholder for both title and body if the title plugin is enabled. I believe that the plugin looks strange when they are not defined.

I was a bit surprised by this change, but I agree that it makes sense. If you load the `Title` plugin it just preconfigures your editor. That's reasonable and safe.
