### ISSUE TITLE
Cant use `gulp exec` on ckeditor5 only

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#249]
The `--repository ckeditor5` will not work because of the way how it's implemented.

You can't even do something like `--include-root --repository foo` to run on ckeditor5 only as it doesn't work either.

**Comment by maxbarnas** [comment]
It is fixed in https://github.com/ckeditor/ckeditor5/pull/237

**Comment by Reinmar** [comment]
Hm... it's overcomplicated, but we can live with it. I guess that a solution would be to change `--include-root` to `--exclude-root`. That would let you run the task on `ckeditor5` without any additional option and would, in general, be more understandable for the users.

**Comment by maxbarnas** [comment]
I agree it is overcomplicated but I considered couple of things before doing it this way:
- backward compatibility with existing tasks
- ckeditor5 package's loss of importance over time

**Comment by Reinmar** [comment]
Good point about ckeditor5 losing importance. I'll close the issue that I've just reported :d.
