### ISSUE TITLE
Support for pasting content from Excel

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#2513]
It would be nice to have support for pasting content from Excel (for features which are already available in the editor - tables, basic text styling, highlights, etc).

First it should be verified what already works out-of-the-box. Next step is to add support (proper content transformations on paste) for missing features.

Add 👍 if you'd like to see this feature.

**Comment by kevinclerc** [comment]
any news on this topic?
Past from excel wihtout loosing formatting would be really good.

**Comment by jensen-lin** [comment]
Our users would like to have this fixed

**Comment by mmoroppa** [comment]
Hi! Our team will have to move to CKEditor 4 just because this issue :(

**Comment by viz-eight7six** [comment]
Any idea if this is on the road map?

**Comment by BruTyler** [comment]
Vote for the feature, our users prefer offline excel to work with tables and they want to share their tables via ckeEditor

**Comment by kuku711** [comment]
any update for this?
if i paste from excel to word and from word to editor its save the style ^_^

**Comment by hajrice** [comment]
Any word? Looks like it's been in progress for 4 years now

**Comment by fpolli** [comment]
Just voting for this. I use Excel all the time and this would be cool to have.

**Comment by mikebpech** [comment]
Voting here

**Comment by paulbenjamin3409** [comment]
Voting here for this feature

**Comment by aaronschubert** [comment]
Voting for this. It is a nonstarter really - we shouldn't have to justify voting for this - why would you not support it?

**Comment by vijendrapatil** [comment]
CKEditor dev team is truely adamant and not considering this ticket. Complete ignorance at such important feature.

**Comment by vijendrapatil** [comment]
> CKEditor dev team is truely adamant and not considering this ticket. Complete ignorance at such important feature.

@jacekbogdanski , JakeAlmer I have created a new ticket for the same.

**Comment by Reinmar** [comment]
Resolved by [Paste from Office Enhanced](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-office-enhanced.html) :tada: 

With this feature, the experience with style retention will now be much better.

Since the scope of this ticket wasn't defined, in case of any remaining issues that we didn't cover, please open new tickets.
