### ISSUE TITLE
Handle saving errors

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#2546]
As @wwalc notice:

> >it should wait with the next "Saving..." until the previous save attempt was completed.
>
> Just a note that if we ever implement this, we should handle correctly a situation where the first save attempt failed (not sure what was the definition of "completed" above). We should try to continue saving the data again after getting an error/timeout or sth.

(https://github.com/ckeditor/ckeditor5-autosave/issues/9)

It should be possible to reject save integration. In such case autosave should try to save again, possibly with a small timeout.

However, it is the simplest implementation, there is far more can be done:
 - the timeout can get bigger and bigger (more times autosave failed in the row, longer is the timout editor waits before it try to save again),
 - some UX could be provided when it is not possible to save the data or at least observable property with the save status.

**Comment by ma2ciek** [comment]
Closed by https://github.com/ckeditor/ckeditor5-autosave/pull/27.
