### ISSUE TITLE
Why does an image change its size after being uploaded

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2552]
![sep-27-2017 20-21-34](https://user-images.githubusercontent.com/156149/30930281-8effbcf2-a3c1-11e7-8471-7b712518fecd.gif)

**Comment by dzpt** [comment]
@pjasiun how do i add more data on this json?
like data-id?

**Comment by ma2ciek** [comment]
Hi @dzpt,

Your request is a dup of #5204 which will be resolved soon.
