### ISSUE TITLE
Mark model attributes using @attribute instead of @property

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#26]
Currently we use one tag for all of them what requires reading the code to understand their meaning. Let's introduce an @attribute tag and we'll find a way to extend JSDoc to handle it.

**Comment by jodator** [comment]
What's the difference between `@attribute` and `@property`?

Also I don't recall any doc lib using `@attribute` ([jsdoc](http://usejsdoc.org/), [Google Closure compiler](https://developers.google.com/closure/compiler/docs/js-for-compiler) - [actually google extends this](https://code.google.com/p/jsdoc-toolkit/wiki/TagReference)) - so I guess that `@attribute` is a special `@property`, am I right?

**Comment by Reinmar** [comment]
The difference is that attribute is part of a model's state, while property isn't. At least, if I remember the intention correctly.

I also don't recall any library using attributes, but they definitely do extend JSDoc. Actually, just like you extended JSDuck :).

**Comment by jodator** [comment]
I don't get the difference but I didn't dig into Models definition either so I guess it is valid case.

**Comment by Reinmar** [comment]
I opened a new issue for this, because that doesn't make sense any more to make some big differentiation between attrs and props: https://github.com/ckeditor/ckeditor5/issues/107
