### ISSUE TITLE
Can't use highlight while typing

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2616]
1. Apply highlight to an empty selection.
2. Type something.
3. Press the highlight button again.

Expected: It works like bold – you stop writing with the highlight but the typed text remained highlighted.

Actual: It all disappears.

To me, this is super annoying and makes this feature far less useful.

![foo](https://user-images.githubusercontent.com/156149/63677001-627bca80-c7ec-11e9-86ab-4f07b379f353.gif)

## Additional notes

* Let's focus on the selection position at the end of a highlight. A similar issue, although more tricky to reproduce, exists on the start of a highlight but it's out of the scope of this ticket.
* The highlight feature uses its own command class (unlike Bold, Italic, etc.).
* Why does it work differently than in Bold, Italic, etc? It's most likely because we wanted to support the "place the caret (collapsed selection) in a highlighted text and press the highlight button to remove the entire highlight".
* The solution should probably land here: https://github.com/ckeditor/ckeditor5/blob/550b168/packages/ckeditor5-highlight/src/highlightcommand.js#L66-L91

**Comment by mlewand** [comment]
Reproducible in 11.1.0, didn't check earlier version (highlight was introduced in 1.0.0).

**Comment by Reinmar** [comment]
Two DUPs: #9021, #9174.
