### ISSUE TITLE
How can i get inline style with highlight color 

### ISSUE THREAD

**Issue by xwillmadeit** [ckeditor/ckeditor5#2618]
With the default highlight setting i get the editor data like this

`<p>Hello from <mark class="pen-red">CKEditor 5!</mark></p>`

How can i get the editor data like this

`<p>Hello from <mark style="color: red;">CKEditor 5!</mark></p>`

The editor data might be used in other project，but i don't have 'pen-red' style defined in that project, with inline color it will work.

**Comment by dstj** [comment]
@jodator, thanks a lot for the `InlineHighlighter` plugin. There's a small bug in your implementation for markers though: it has to set `background-color`, not `color` in inline style. So, you can't simply reuse the `option.color` property as `styles`.

I suggest to following modifcation:

```
...
converterDefinition.view[ option.model ] = {
	name: 'mark', // The same as in default converter.
	// Additional style attribute on <mark> element.
	styles: option.styles,  // <---- use a dedicated 'styles' object property
	classes: option.class // The same as in default converter.
};
```

and you define the `styles` property in the highlight options:

```
highlight: {
	options: [
		{
			model: 'yellowMarker',
			class: 'marker-yellow',
			title: 'Yellow marker',
			color: 'yellow',
			type: 'marker',
			styles: {
				'background-color': 'yellow'
			}
		},
		{
			model: 'redPen',
			class: 'pen-red',
			title: 'Red pen',
			color: 'red',
			type: 'pen',
			styles: {
				color: 'red'
			}
		}
	]
},
```

**Comment by meetajhu** [comment]
Hi @jodator i tried what you told and i keep getting 

`It was not possible to load the plugin`
and
`class constructors must be invoked with 'new'`

here's is what i did

`
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

export default class InlineHighlighters extends Plugin {
	init() {
		const editor = this.editor;

		// Base conversion definition.
		const converterDefinition = {
			model: {
				key: 'highlight',
				values: []
			},
			view: {},
			converterPriority: 'high'
		};

		// Get highlight configuration options:
		const options = editor.config.get( 'highlight.options' );

		// Build conversion definition for configured options.
		for ( const option of options ) {
			// Define which model values are recognized:
			converterDefinition.model.values.push( option.model );

			// Define how those values are converted:
			converterDefinition.view[ option.model ] = {
				name: 'mark', // The same as in default converter.
				// Additional style attribute on <mark> element.
				styles: {
					color: option.color
				},
				classes: option.class // The same as in default converter.
			};
		}

		// Override the downcast conversion only:
		editor.conversion.for( 'downcast' ).attributeToElement( converterDefinition );
	}
}
`

In my Editor Config

`
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Clipboard from "@ckeditor/ckeditor5-clipboard/src/clipboard";
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
import ListPlugin from '@ckeditor/ckeditor5-list/src/list';
import InlineHighlighters from './ckEditorTools/InlineHighlighters';

export const editorConfig = {
  fontFamily: {
    options: [
      "default",
      "Ubuntu, Arial, sans-serif",
      "Ubuntu Mono, Courier New, Courier, monospace"
    ]
  },
  toolbar:{ 
  items: [
    "heading",
    "|",
    "bold",
    "italic",
    "underline",
    "link",
    "bulletedList",
    "numberedList",
    "highlight"
    // "blockQuote",        
    // "undo",
    // "redo"
  ]},
  plugins: [ Essentials, Bold, Italic, Paragraph, Underline, Clipboard, LinkPlugin, ListPlugin, Highlight, InlineHighlighters ],
};
`

Thanks
