### ISSUE TITLE
Cannot read property 'modal' of undefined (again)

### ISSUE THREAD

**Issue by gkzsolt** [ckeditor/ckeditor5#2645]
Hi,
I am using a CKEditor build and trying to use - or add? - the CKFinder integration to it. I am struggling now for half a day but to no avail.
The editor builds - I am using InlineEditor, btw. - _do include_ the CKFinder plugin, as I see, it is listed in InlineEditor.builtinPlugins, and according to the docs it is also enabled: "This feature is enabled by default in all builds." So I don't have to add CKFinder to my plugin list.
In my app I instantiate an editor and try to access the CKFinder with its ui toolbar button:

`const CKEditor = require('@ckeditor/ckeditor5-build-inline');`
`  CKEditor
        .create( document.querySelector('#editor'), {`
`toolbar: [ 'ckfinder' ],`
`ckfinder: {
                uploadUrl: '...',
            }`
`})
        .then(...)`

I then build a bundle with webpack. But when I click the ckfinder button I got the infamous 

> Cannot read property 'modal' of undefined

All my internet searches revealed only the question "Have you added ckfinder.js to a webpage? 
Check the CKFinder for CKEditor5 integration feature guide."

Well, I checked the CKFinder for CKEditor5 integration feature guide. 

> The easiest way to load the CKFinder library is to include the <script> tag loading the ckfinder.js file first:

Yes, but I am not going to do this, because I am building a bundle with webpack - like the whole CKEditor docs suggest - and with webpack you don't load JS using script tags. Is CKFinder loaded by the InlineEditor build? I see it in the devDependencies, but don't know how to check it better (the code is minimised.)
If I add:
`import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';`
as the example in the integration guide, I get a _ckeditor-duplicated-modules_ error, which also seems to confirm that ckfinder is loaded. So where is the problem, what am I doing wrong?

Thank you for any help.

**Comment by xumoqiu** [comment]
@Mgsy I used ckeditor-angular 
add the tag in html page

`<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>
<ckeditor #ckeditor [editor]="Editor" (ready)="onReady($event)" [config]="ckConfig" ></ckeditor>`

`ckConfig = {
    //extraPlugins:'html5video',
    alignment: {
      options: [ 'left', 'right','center','justify']
    },
    fontSize: {
      options: [ 12, 'default', 14, 16, 18, 20, 22, 24, 26, 28, 36, 44, 48, 72],
  },
 // puligns:[CKFinder],
  ckfinder: {
    //openerMethod: 'popup',
    uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'

  },
   // plugins:[Font],
    toolbar:['bold','italic','fontSize','highlight', 'heading', '|', 'bulletedList', 'numberedList', '|', 'alignment', '|','imageTextAlternative','imageUpload','mediaEmbed','ckfinder', 'insertTable','link', 'blockQuote','undo', 'redo']
  }`

it still has the problem can you help me
![image](https://user-images.githubusercontent.com/24932876/87242022-82939700-c45b-11ea-8c36-1e91ac609a2d.png)

**Comment by xumoqiu** [comment]
![image](https://user-images.githubusercontent.com/24932876/87242029-9b9c4800-c45b-11ea-9f6a-e37fe136d175.png)

**Comment by Amangoel998** [comment]
@xumoqiu Instead of adding <script....> tag in HTML when using Angular, you should instead add the file under assets and attach the file name inside angular.json file like below 
`"scripts":{
      "src/assets/js/ckfinder.js",
}`
