### ISSUE TITLE
[Edge] No HTML is pasted/copied (only plain text available)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2660]
Edge still doesn't support Clipboard API: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6515107-clipboard-api (https://developer.microsoft.com/en-us/microsoft-edge/platform/status/clipboardapi/?filter=f3f0000bf&search=clipboard).

Without a proper support for Clipboard API you can only paste or copy a plain text from the editor. To workaround this we'd need copybin and pastebin which require quite a lot of work to be implemented and they will be used only for Edge...

**Comment by hotcpufox** [comment]
I realize this was closed, however, oddly 12/21/2019


Edge is still not pasting html properly, but only for SOME subset of pages I have been testing vs same site and paragraph with embedded html links vs Chrome. Primarily example for the paste, that  I require and tested is Evernote. Evernote allows two modes - one with html, RTF and native formatting, the other to match style of current font, but always "plain text".  And yes, I was consistent on all tests I have been performing.

Can anyone comment?  Ideally, someone who is following the API question, or capable of confirming this or who would like to try a variety of sites.
