### ISSUE TITLE
CWD issues in `gulp exec --task sh`

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#269]
I tried to run:

```
gulp exec --task sh --cmd 'npm i'
```

But I got npm warnings that are only printed when using `npm i` in ckeditor5. I saw the same problem when trying to execute `gulp lint` on all packages – again gulp was run on the main repo.

I think that the reason is because `shExec()` is async and `gulp exec --task sh` ignores that. It also ignores errors that a command may produce (it should rather stop further execution).

**Comment by maxbarnas** [comment]
After discussing this with @szymonkups I opened similar issue on `ckeditor5-dev-env: https://github.com/ckeditor/ckeditor5-dev-env/issues/2.
