### ISSUE TITLE
Implement the auto embed (sub)feature

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#2731]
Just [like in v4](https://sdk.ckeditor.com/samples/mediaembed.html) we probably want to implement the Auto Embed. Long story short, it's all about upcasting the pasted urls from the clipboard straight to embedded media. Check out the v4 demo to learn more.

**Comment by Im-Goutham** [comment]
How to disable this auto embed feature ?

**Comment by Mgsy** [comment]
> How to disable this auto embed feature ?

There's no configuration option for disabling this feature, however, you can just import media embed plugin's dependencies without the auto embed ([as you can see](https://github.com/ckeditor/ckeditor5-media-embed/blob/master/src/mediaembed.js#L11), it's a dependency of the media embed plugin):

```plaintext
import MediaEmbedEditing from '@ckeditor/ckeditor5-media-embed/src/mediaembedediting';
import MediaEmbedUI from '@ckeditor/ckeditor5-media-embed/src/mediaembedui';
import Widget from '@ckeditor/ckeditor5-widget/src/widget';
```
