### ISSUE TITLE
New bug in CKEditor component joomla!

### ISSUE THREAD

**Issue by sonqor** [ckeditor/ckeditor5#274]
Hello. As in issue [https://github.com/joomla/joomla-cms/issues/7631](https://github.com/joomla/joomla-cms/issues/7631) mentioned, core.js has a bug in joomla and we can't change the configs. Please fix it. Thanks.

**Comment by f1ames** [comment]
Hello @sonqor, this is CKEditor 5 repository. I assume the bug you would like to report is related to CKEditor 4. All bugs related to CKEditor 4 should be reported in http://dev.ckeditor.com/. Please report this bug there. If you could also provide more comprehensive description than in https://github.com/joomla/joomla-cms/issues/7631 or steps to reproduce this bug it would be much easier for us to validate the bug.

**Comment by sonqor** [comment]
@f1ames OK!

**Comment by sonqor** [comment]
It's here:
[http://dev.ckeditor.com/ticket/14788](http://dev.ckeditor.com/ticket/14788)
