### ISSUE TITLE
[Edge] Open media in new tab does not work

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#2771]
Clicking the semantic media's URL won't open a new tab in Edge. To do that, the user must right-click and select the native contextual menu option.

The cursor is also wrong when hovering the URL.

**Comment by FilipTokarski** [comment]
This bug still exists on old Edge, however it is fixed in the new upcoming version (79.0.309.56)

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
