### ISSUE TITLE
mediEmbed Question

### ISSUE THREAD

**Issue by mariomeraz** [ckeditor/ckeditor5#2778]
hello

noob question, add  CDN ckeditor.js and all work fine, only no show my videos in html view, read documetation and configure **previewsInData** true, but no work.

    ClassicEditor
        .create( document.querySelector( '#editor' ), {
            mediaEmbed: {
                previewsInData:true
            },
            image: {
                // You need to configure the image toolbar, too, so it uses the new style buttons.
                toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight' ],

                styles: [
                    // This option is equal to a situation where no style is applied.
                    'full',

                    // This represents an image aligned to the left.
                    'alignLeft',

                    // This represents an image aligned to the right.
                    'alignRight'
                ]
            },
            language: 'es',
            ckfinder: {
                uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
            }
        } )
        .catch( function( error ) {
            //console.error( error );
        } );

**Comment by dvlpr91** [comment]
How did you solve it?
