### ISSUE TITLE
Remove unused gulp tasks and rethink node.js testing tasks location

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#281]
After we moved all development utils to [ckeditor5-dev-env](https://github.com/ckeditor/ckeditor5-dev-env) repository there are unused gulp tasks inside: `dev/tasks/test`:
 - `gulp test:dev`
 - `gulp test:dev:coverage`

Those tasks should be removed from the main repository as there are no dev tasks to test.

There are also tasks that tests our code under node.js environment. Those tasks use bender configuration. We can leave them inside main repository or move them to the [ckeditor-dev-env](https://github.com/ckeditor/ckeditor5-dev-env). In the latter case bender configuration should be passed there as a parameter. 

I am not quite sure where is proper place for these tasks.

**Comment by szymonkups** [comment]
If we decide to move these tasks `ckeditor-dev-env`, we will be able to remove `gulp-` dependencies for main repository. Only `gulp` and `run-sequence` will be left I think.

**Comment by maxbarnas** [comment]
I am thinking about moving this in-node editor testing (along with its unit tests) to `ckeditor5-dev-builder`. Reasons? Testing in node is pretty much just modifying CKEditor build. Similarity is thin, but the best I could find.

**Comment by szymonkups** [comment]
I moved this task to iteration 3, we will decide if we want to keep this in main package or move it somewhere else.

**Comment by Reinmar** [comment]
For now, I'd remove this code as we don't use this task, unfortunately. We wanted to understand what piece of code will work under Node, but this proved to be too high cost to continue doing that in a long run. We can bring back the code once we have CI.

**Comment by szymonkups** [comment]
Reminder to update wiki and remove `gulp test:*` tasks description from wiki after closing this.
