### ISSUE TITLE
Get response from CKEditor Upload

### ISSUE THREAD

**Issue by WandersonAlves** [ckeditor/ckeditor5#2833]
Hi All!

I wanna know if is possible to get the response from my server after the upload is complete.

Currently, i have something like this:

```
editor.plugins.get('FileRepository').on('change:uploaded', (result, name, value, oldValue) => {
	console.log(result);		
})
```

But, all of the four parameters not correspond to the response data.

From a custom adapter, is possible to create a new event to listen, and on this event, return my data?
Thanks!

**Comment by robclancy** [comment]
This is the first big issue I've had with ckeditor5. Every time I have had to integrate an editor with uploads I need to listen to the uploaded event to do extra steps. This is the default in every editor I've used. But in this case I need to listen to events on the plugins to be able to get the file instance to listen to events on the loader... 
Either that or make a custom adapter that fires custom events.

**Comment by rosnaib11** [comment]
Got same issue using ckeditor 5. This one made me confused or maybe not really working on ckeditor 5

> ```js
> const fileRepo = editor.plugins.get( 'FileRepository' );
> const fileLoader = fileRepo.getLoader( yourNativeFileInstance );
> 
> fileLoader.on( 'change:uploadResponse', ( evt, name, value, oldValue ) => {
>     console.log( newValue ); // your data
> } );
> ```

instead, I figured out the fileLoader is already on the `createUploadAdapter` params. And that loader is the one you need to add the event listener

```
MyCustomUploadAdapterPlugin(editor) {
      editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
        loader.on('change:uploadResponse', (evt, name, val, oldval) => {
          if(val){
            console.log(val)  // object response {default: image_link }
          }
        })
        return new MyUploadAdapter(loader)
      }
}
```
