### ISSUE TITLE
Configuration of ckeditor5-dev-* packages

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#288]
As @pjasiun pointed out, providing global object to whole package isn't a good practice. There were also contradictory arguments for/against different solutions. This issue hopefully will clear things up.

Example:

``` js
const config = {
    ROOT_DIR: '.',
    IGNORED_FILES: [
        'src/lib/**'
    ]
};

const ckeditor5Lint = require( 'ckeditor5-dev-lint' )( config );
```

Even providing parameters separately to package is still too broad:

``` js
const ROOT_DIR = '.';
const IGNORED_FILES = [
    'src/lib/**'
];
const ckeditor5Lint = require( 'ckeditor5-dev-lint' )( ROOT_DIR, IGNORED_FILES);
```

I would like to discuss idea of tasks with explicit parameters:

``` js
const ROOT_DIR = '.';
const IGNORED_FILES = [
    'src/lib/**'
];
const ckeditor5Lint = require( 'ckeditor5-dev-lint' );

gulp.task( 'lint', ckeditor5Lint.lint(ROOT_DIR, IGNORED_FILES ); // Or `.bind()` etc.
```

Current solution is quite comfortable, but rigid. On the other hand complicating code without good reason isn't good idea. I am for something in the middle:
- Explicit parameters to tasks, where such flexibility is needed,
- Explicit parameters to package, where all the package's tasks are tied together logically,
- No global config object passed blindly to every package.

**Comment by pomek** [comment]
Your examples are fine when we have simple strings as a configuration.

`docs-builder` is using a [complicated configuration](https://github.com/ckeditor/ckeditor5/blob/t/243/gulpfile.js#L15-L39). Do you have any idea pass the configuration in a proper way?

[Sometimes](https://github.com/ckeditor/ckeditor5-dev-builder/blob/t/3/lib/builder/index.js#L135) I need to get a configuration based on a dynamic key. How do you want to resolve it? Perhaps a  current solution isn't good, but the solution is unified between all modules which `docs-builder` requires.

**Comment by pjasiun** [comment]
> docs-builder is using a complicated configuration. Do you have any idea how pass the configuration in a proper way?

I see nothing wrong in passing similar configuration to each tool, but separately. 

If `ckeditor5DevEnv.relink` need only `WORKSPACE_DIR`, passing the whole config to `ckeditor5DevEnv` seems to be wrong.

In my external project use only `ckeditor5DevEnv.relink` I should be able to use it, passing to it what it needs. I should not need to create a bigger configuration for the whole `ckeditor5DevEnv` which options I do not need if I only use `ckeditor5DevEnv.relink`. Of course, I can pass to `ckeditor5DevEnv` only options needed by `relink` and skip other options, but it seems to be hacky.

**Comment by szymonkups** [comment]
Another thing to consider: tasks like `compile` can use parameters passed from command line, for example:
```
gulp compile --formats esnext
```
These command-line parameters are parsed inside `ckeditor5-dev-compiler`. I think that this logic should be a part of a gulpfile, not compiler package itself. When some other project will define it's own tasks, it is forced to use the same command-line parameters defined there. In my opinion all parameters should be passed as method arguments. Decision how these parameters are passed to the gulp task ( or even if that should be possible ) is up to developer integrating our tools.

**Comment by Reinmar** [comment]
This issue got resolved somehow naturally.
