### ISSUE TITLE
Affect plugins loading order without creating strict requirements

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#2907]
We already touched this topic [here](https://github.com/ckeditor/ckeditor5-core/issues/148), but it was not implemented then.

Currently, when one plugin requires another plugin you can be sure about two things:
 - the required plugin will be loaded,
 - the required plugin will be loaded before your plugin.

However, sometimes we need only the second part. Another plugin is not necessary, but if it is loaded we want it to be initialized before our plugin. Currently `afterInit` needs to be used what is far from a perfect solution. My proposal is to introduce soft requirements:

```js
class A extends Plugin {
	static get softRequires() {
		return [ 'B' ];
	}

	static get pluginName() {
		return 'A';
	}

	init() {
		if( this.editor.plugins.has( 'B' ) {
			console.log( 'B is also loaded!' );
		}
	}
}

class B extends Plugin {
	static get pluginName() {
		return 'B';
	}
}
```

It means that if the plugin `B` is not loaded then plugin `A` shows no errors nor warnings. However, if plugin `B` is loaded, then it is initialized before plugin `A`, the same way, as it would be a requirement.

Note, that I am not sure about "Soft requirements" name nor about `softRequires` method name. Feel free to propose a better name.

**Comment by jodator** [comment]
Ha! Another plot twist. We will probably have to loosen some `requires()` calls due to work on CKEditor5 DLL (#8395). What we will need here:

*   Probably new method alongside `requries()` that will define `softRequires()` - I'm unsure about the naming but let leave it as is for now.
*   The `softRequires()` should be used to cross-package requirements definition.
*   The `requires()` should be left as now for "glue" packages as an automatic plugin loading mechanism for plugins from the same package. In most cases, it would be that `Feature` will require `FeatureEditing` and `FeatureUI`.

**Comment by jodator** [comment]
Again, the same finding as before IIRC:

*   The `Plugin.requires()` can have string. It will try to load a plugin from `builtinPlugins` (the `availablePlugins` in `PluginCollection`.
*   I've modified a bit plugin loading to also allow loading plugins from `plugins` object (so re-ordering them).
*   If a plugin is unavailable (either `builtinPlugins` or `plugins` array) we can reject editor loading (right now it doesn fail).

**Comment by jodator** [comment]
After a F2F talk, we agreed that there's no need to introduce new `softRequires` getter as we already allow a string to be specified there. The current behavior will be expanded to order plugins available either as `Editor.builtinPlugins` or `plugins` / `extraPlugins` configuration option. ATM, the string only loads a plugin if it is defined in `builtinPlugins`.

**Comment by pomek** [comment]
Closed with https://github.com/ckeditor/ckeditor5/commit/9c24fcae6f30c05ecc4ef796f6222486ae3a77f4.
