### ISSUE TITLE
Wrong paths to ckeditor.css after build structure has changed

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#292]
In various MTs like

* http://tests.ckeditor.dev:1030/build/modules/amd/tests/editor-classic/manual/classic
* http://tests.ckeditor.dev:1030/build/modules/amd/tests/theme-lark/manual/theme
* http://tests.ckeditor.dev:1030/build/modules/amd/tests/ui-default/dropdown/manual/dropdown

etc. there's a `<link>` declaration pointing to `ckeditor.css`:

```html
<link rel="stylesheet" href="%APPS_DIR%ckeditor/build/modules/amd/theme/ckeditor.css">
```

But instead of
`http://tests.ckeditor.dev:1030/apps/ckeditor/build/amd/theme/ckeditor.css `
it now should be 
`http://tests.ckeditor.dev:1030/apps/ckeditor/build/modules/amd/theme/ckeditor.css`
otherwise all MTs have no styling.

All MTs in the project should be reviewed and fixed.

**Comment by szymonkups** [comment]
PRs that will resolve this:

 - https://github.com/ckeditor/ckeditor5-basic-styles/pull/22
 - https://github.com/ckeditor/ckeditor5-editor-classic/pull/26
 - https://github.com/ckeditor/ckeditor5-engine/pull/564
 - https://github.com/ckeditor/ckeditor5-headings/pull/24
 - https://github.com/ckeditor/ckeditor5-theme-lark/pull/31
 - https://github.com/ckeditor/ckeditor5-ui-default/pull/51
 - https://github.com/ckeditor/ckeditor5-undo/pull/38
