### ISSUE TITLE
There should be a default bundle config

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#295]
When I call `gulp build` without any bundle config the default one should be used. Now I get an error instead.

**Comment by pomek** [comment]
Moved to proper repository: https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/issues/21

**Comment by pomek** [comment]
Reopen because https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/pull/22/files/2da1d8b0e1904876808685a3d48366291e5e721c#r74433409
