### ISSUE TITLE
Gulp exec: SIGINT doesn't stop all tasks.

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#296]
I wanted to run some command in all dependencies of `ckeditor5`. 

I was wrong and I called bad command. I would like to stop the execution of the previous command and execute the correct command one more time. 

I pressed `CTRL + C` in order to send `SIGINT` signal (which breaks the process). Unfortunately, it doesn't break process but it breaks single task in dependencies. 

Steps to reproduce:

1. Run the following command in main (`ckeditor5`) repository: `gulp exec --task sh --cmd 'echo "Test" && sleep 1'`
2. Press `CTRL + C`.
3. Expected: `gulp exec` stops execute. Currently, it breaks the only task in sub-repository.

I prepared some visualisation of this bug.

![Visualisation of reported bug.](https://media.giphy.com/media/3o7TKuKXWYv7lAL3Dq/giphy.gif)

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev-env/issues/15.
