### ISSUE TITLE
Implement advanced lists (document lists)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2973]
## Intro
The current implementation of lists assumes that a list item cannot contain any block content – that a list item is the lowest block element.

It means, that what the user sees as a "block" can either be a list item, paragraph or a heading. Never two at the same time.

It's a different model than what we had in CKEditor 4 where we allowed to have paragraphs and headings and other things in list items. The current CKEditor 5's implementation, which I call "article lists" (we can think of a better name), is definitely more limited. Let's clarify the whys and why nots.

## Justification

However, before I'll get to that I'd like to clarify that IMO the current implementation isn't temporal. Block elements support won't be ever added to it because, simply, the article and document lists are two separate features. If we'll ever work on the document lists (I guess we'll do), then the developer will have to enable that feature and we yet have to define whether both kinds of lists can coexist in one editor.

Why we decided to work on article lists first:

* Because the UX, mental model and implementation are simpler if you don't allow blocks inside list items. There's a wide range of issues in CKEditor 4 when it comes to blocks inside list items. E.g. initially, a list is created without `<p>`s inside, but you can insert `<hX>` inside an item using the format dropdown and when you'll remove that format you'll be left with a `<li><p>...</p></li>`. You can't remove that `<p>` then, you have inconsistent markup and inconsistent styling (paragraphs usually have margins). And this is only one out of many, many issues (pasting, enter, and stability).
* Lists are lists and (at least IMO) should rather not be used to format big chunks of multiline, multi-format content. At least not in articles. See also @wwalc's https://github.com/ckeditor/ckeditor5-heading/issues/68#issuecomment-288243769.
* We're not alone in taking this direction. Medium and Draft.js editors also enforce such limitation.

Why we'll need to work on document lists:

* Often, you want to have multiline content in a list. I'm doing this very frequently myself with Markdown. It lets you better present a complex content. It's just useful if you used to do that.
* Actually, that was the only argument which came to my mind, but it's an important one. The more complex the content, the more need for more complex lists :).

## Future

As I mentioned, I see document lists as a separate, opt-in feature. When implementing them we'll need to think on many UX and implementation aspects

* Whether both types of lists can exist in one editor – how to manage which are which, conversion between them, inconsistent markup (e.g. on paste), etc.
* What kind of formatting should be available in list items. E.g., we may say that headings should not be allowed, but multiple paragraphs, code blocks, block quotes, etc. are fine.
* The <kbd>Enter</kbd> behaviour. Should it create new list item or new paragraph (the latter could e.g. be done on <kbd>Shift</kbd>+<kbd>Enter</kbd>).
* How to represent them in the model and how to share current lists code with the new feature. E.g. I hope that we could use the same converters but with a different schema and <kbd>Enter</kbd>, <kbd>Backspace</kbd> modifiers and different commands. However, the dangerous part is that in this model, the `<listItem>` can be nested which will mean something different than subsequent items with different `indent` value.

Anyway, I wanted to start this topic and write down my concerns because I expect that we'll be asked about our current approach. However, I wouldn't like to think too much on this because I'm sure I just touched the tip of the iceberg. 

---

If you'd like this feature to be implemented, add 👍 to this post.

**Comment by treyspiva** [comment]
Another use case for the document list is procedures.  You need a number list for the step of the procedure.  Often pictures (but not limited to images) objects are needed to illustrate the procedure step.  Having the image as a sibling of step breaks the numbering.  It would be an awful solution to make the user have to set the start number in the next step.

**Comment by JacDek** [comment]
I have a use case were Latex markup is being translated into html for editing in the Ckeditor. I would prefer that the editor didn't just drop elements that it decides are invalid. At the moment we are trying to find a workaround in the translation so that it will spit out something that is safe to give to Ckeditor.

**Comment by alexishuxley** [comment]
CkEditor has made its way into many upstream products, e.g. wikis, ticketing systems. 

Frequently in these contexts its necessary to write instructions, for which step numbering is a must, and often these instructions include the need to include images. This is just the nature of quality documention. For example:

 1. Scroll down the page to the share icon, which looks like this: 
![image](https://user-images.githubusercontent.com/581514/84020644-6cd61200-a983-11ea-9989-181f8de8addd.png) 
  and click it.
 1. Select the recipient application.

The above two list items were both done in Github's editor with '1.' and '1.', where it is displayed correctly, but in CkEditor itself it is not displayed correctly, which leads to conversations like:

> I got as far as step 1 and then it went wrong.
> Err, which step 1? The first step 1 or the second step 1?

**Comment by drashti2277** [comment]
This will be a great feature. But meanwhile did anyone found any work around for this? 
I've just started exploring this side of ckeditor 5 so need someone's input if below mentioned is good approach to handle this temporarily.
- A custom plugin which detects the occurrence of block element in a list and resets the "value" attribute of <li> element in continuation. 
I would deeply appreciate any help.
Thanks.

**Comment by neongreen** [comment]
> Frequently in these contexts its necessary to write instructions, for which step numbering is an absolute must, and often these instructions need to include images or code samples.

Same here. I run [Brick.do](https://brick.do); I asked a customer what they would require to start using Brick for writing documentation, and "lists with multiple elements inside" was the first thing they mentioned.

**Comment by jhartacs** [comment]
Using CKEditor 5 to write numbered instructions is impossible with the current approach. Specifically the lack of ability to add images that highlight an instruction. Lists with multiple elements inside is absolutely needed.

**Comment by MPIIIMan** [comment]
Being able to includes elements in a list, but without showing a number in front of them.
In HTML this is easily done like so: `<li style="list-style-type:none;">No number</li>`
A way to exclude a list item from showing a number would be helpful.

**Comment by mmichaelis** [comment]
Unfortunately, this is currently a blocker for us, migrating from CKEditor 4 to CKEditor 5. If I got it correctly, it is about these structures, which won't work:

```xml
<ul>
  <li>Works</li>
  <li><p>Doesn't work</p></li>
<ul>
```

To reproduce, you can use this DevTool-code within CKEditor 5 demo:

```javascript
editors[0].setData("<ul><li>Yes</li><li><p>No</p></li></ul>");
```

Which will end up in view as:

```
<ul>
  <li>Yes</li>
</ul>
<p>No</p>
```

While I understand the UX-challenge here, as mentioned previously with reference to ckeditor/ckeditor5-design#11, it prohibits editing documents with CKEditor 5, which are not necessarily created with CKEditor 5 (but with CKEditor 4, for example) and even corrupts these contents while loading.

Are there any ideas for workarounds how to get around this limitation? For the first example, obviously, by adjusting data-processing to remove the obsolete `<p>` tag... but this won't solve many other issues. Or, for the possibly related issue #9005, to remove such obsolete `<p>` tags on paste-from-office.

**Comment by wimleers** [comment]
I know this is planned for the current iteration (#10795), and that it will span multiple iterations. But no PRs are linking to this issue. Is that maybe because experimentation is happening? 🤞

**Comment by kuku711** [comment]
it will resolve the issue of block elements like images/table inside a list? (right now its just reset the list numbers/remove)

**Comment by Reinmar** [comment]
> it will resolve the issue of block elements like images/table inside a list? (right now its just reset the list numbers/remove)

Yes, that's exactly what this feature is all about :) 

![](https://user-images.githubusercontent.com/156149/161848410-ff22cca3-4949-4854-8772-474503b3e702.png)

**Comment by Reinmar** [comment]
To conclude this ticket:

It's been a long ride – nearly a year-long project. Definitely one of the trickiest feature we ever worked on.

Finally, it's over :tada:

Congratulations to @niegowski @arkflpc @CatStrategist @oleq @magda-chrzescian @scofalik and many other that contributed. Big thanks to the @ckeditor/qa-team :hugs: 

This feature will be a part of the upcoming v33.0.0 release. However, due to its size and complexity, we'll keep it on an "experimental" level for 1-2 releases, meaning that we don't recommend using it in production without assessing the risk. For now, it isn't even covered in the documentation, although this should change sooner.

**Comment by blairjanis** [comment]
I'm very interested in testing out the document list feature but I must be doing something wrong in the implementation.  I'm importing DocumentList ```import DocumentList from '@ckeditor/ckeditor5-list/src/documentlist.js';``` and adding DocumentList to the ```Editor.buildinPlugins``` array.  But when I do that my toolbar disappears and the editor is not editable.  No error is showing up in the console.  Any help is appreciated.  Thanks.

**Comment by FilipTokarski** [comment]
Hi @blairjanis  as this ticket was a feature request and is already closed - could you open a new ticket with detailed reproduction steps, editor config, plugins installed, etc., so that we could be able to investigate it?
