### ISSUE TITLE
Outdent doesn't fix the list item type

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2998]
![jan-17-2018 11-53-00](https://user-images.githubusercontent.com/156149/35039067-0ca121ce-fb7d-11e7-94a7-c200625d4eec.gif)

In CKEditor 4 the type of the outdented list item is changed to numbered so you have one list, not 3.

However, it's not entirely clear to me what's the expected behaviour.

**Comment by jswiderski** [comment]
The CKEditor 4 behavior is consistent with the one of MS Word 

![](https://user-images.githubusercontent.com/5314687/93229677-21e44b80-f777-11ea-8f20-b81e1aa54f2a.gif)

**Comment by wwalc** [comment]
I agree, what I'd expect when outdenting the list item is to merge it to the list items one level above.

**Comment by Reinmar** [comment]
I think this was changed with the introduction of the DocumentList feature (which replaced the old List feature now).
