### ISSUE TITLE
Extend chai instance to allow checking for thrown `CKEditorError` errors.

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#300]
Related: https://github.com/ckeditor/ckeditor5-utils/issues/2.

**Comment by maxbarnas** [comment]
I pushed very early version of such extension to https://github.com/ckeditor/ckeditor5/tree/t/300.

**Comment by Reinmar** [comment]
The code looks nice :) Especially that it's validating itself (though, `describe()` and `it()` is missing, so I'm not sure what an assertion error would do).

**Comment by maxbarnas** [comment]
I added tests just to have quick feedback about the behaviour of extension. When those tests breaks, they break whole test suite. And it doesn't look nice at all. I'll check if I can put in in `describe` block to make it spot easier if in future those tests break.

**Comment by maxbarnas** [comment]
I set this as invalid and reverted the code because of problems with Chai extension in bundles. We'll use Babel plugin, that allows to extend builtin types - this will make `instanceof` usable again.
