### ISSUE TITLE
CKEditor API

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#302]
CKEditor is a framework, with plenty pluggable feature. It should be hackable. The information we miss is: how much you can hack the editor to still be able to use plugins? Or thinking from the other side: what API I should expect creating a plugin, if I do not know in what editor is will be used with?

I believe it should be something very clear for everybody who will write a plugin or an editor type. We could provide different levels of API for different usage, for instance:
 - any editor (including backend),
 - frontend editor,
 - single editable frontend editor.

For instance `frontend editor` may not need `setData` method, since there may be multiple editable or there may be an editor without a toolbar.

On the one hand `Editor` and `StandardEditor` classes define such interface, but since they have references to other classes (I am talking mostly about `EditorUI`) it seems to be not clear enough.

I believe that, if we want to let people create both plugins and editor types it should be very clear which plugin works with which editor, so clear API docs for each level might be very useful.

**Comment by Reinmar** [comment]
I reported a wider ticket for this issue: https://github.com/ckeditor/ckeditor5/issues/303.
