### ISSUE TITLE
gulp compile task fails silently.

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#305]
After updating `ckeditor5` repo and `node_modules` `gulp compile` task fails silently.

**Comment by Reinmar** [comment]
-> ckeditor5-dev-compiler?

**Comment by oskarwrobel** [comment]
I will move it to this repo, but first I want to investigate where exactly is the problem.

**Comment by oskarwrobel** [comment]
The problem is gone. Reinstalling node_modules fixes it. It probably was an Issue in some dependency of dependency and looks like someone fixed it. @Reinmar has defected instance of `ckeditor5` repo so I will wait for his confirmation and then close the issue.

**Comment by Reinmar** [comment]
I can confirm that it's no longer a problem :D.
