### ISSUE TITLE
Two undo steps on delete

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#307]
1. Go to the [online demo](https://ckeditor5.github.io/).
 2. Double-click on "CKEditor" in the title to select the work.
 3. `Backspace` to "Delete".
 4. `Cmd+Z` to "Undo". Issue: There is only a selection change.
 5. `Cmd+Z` again. The deletion is undone.

**Comment by fredck** [comment]
Something similar happens with different variations of selection, like selecting one whole paragraph.

**Comment by Reinmar** [comment]
I've encountered it myself as well and forgot to report. Most likely this issue will need to be moved to ckeditor5-delete, but there's a chance that it's an issue in ckeditor5-undo, so I'm leaving it here.

**Comment by Reinmar** [comment]
Already fixed. Most likely in https://github.com/ckeditor/ckeditor5-typing/pull/42.
