### ISSUE TITLE
[Edge][IME] Characters duplicate after selecting the word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#3108]
## Steps to reproduce
1. Create new empty line.
2. Change the keyboard language to Hiragana.
3. Type 'test'.
4. Click on some block element to dismiss the suggestion balloon.
5. Select the word from step 3.

## Current result
Word hasn't become selected and last two characters have been duplicated.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/34483154-00a21fb6-efbd-11e7-882d-ba73f3855368.gif)

## Other information
OS: Windows 10
Browser: Edge
Release: 1.0.0-alpha2

**Comment by FilipTokarski** [comment]
Since introduction of the new Edge based on chromium, this issue doesn't occur anymore. I'm closing this.
