### ISSUE TITLE
Remove WORKSPACE_DIR setting from all gulpfiles

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#311]
This setting isn't used anywhere AFAICS but is defined in every `gulpfile.js`.

**Comment by maxbarnas** [comment]
It is used in https://github.com/ckeditor/ckeditor5-dev-env/blob/fcf268bc8454ec2693d65387b27914fa6f7ee630/lib/index.js#L16

Without it sharing the same workspace directory for CKEditor 5 and other projects is impossible. AFAIK @pjasiun is using it now or soon will be.

**Comment by Reinmar** [comment]
Regardless of whether it's useful now or not, it only needs to be defined in the package which uses ckeditor5-dev-env, so only in ckeditor5. Now, it's everywhere.

**Comment by maxbarnas** [comment]
Sure, just wanted to point out that it is used in one place :)

**Comment by Reinmar** [comment]
I've got rid of it when refactoring ckeditor5-dev recently.
