### ISSUE TITLE
[IME] Can't type while the image is selected

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#3110]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Change the keyboard language to `Hiragana`.
3. Select the image.
4. Start the composition with <kbd>a</kbd>.

## Current result
- Suggestion balloon appears in the top-left corner of the browser
- Text doesn't replace the image

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/34486782-aa5ea452-efd1-11e7-9fa5-0b5f60d62cd7.gif)

## Other information
OS: Windows 10, MacOS X
Browser: All browsers
Release: 1.0.0-alpha2

**Comment by FilipTokarski** [comment]
I checked it on [demo page](https://ckeditor.com/ckeditor-5/demo/#classic) and `article manual test` on latest master. I cannot reproduce this anymore - replacing image and composition in Hiragana work as expected. I'm closing this.
