### ISSUE TITLE
Fix compatibility errors in tests

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#312]
Related: https://github.com/ckeditor/ckeditor5/issues/201.

Failed automatic tests:
- Edge - 41
- Safari 9 - 39
- Firefox - 23
- Chrome - 1
- Opera - 1

**Comment by maxbarnas** [comment]
Update
-------
Problem with `isSurrogateHalf()` function is present on all browsers. Babel's fault seems to be evident.

The need for helper to compare HTML output is real. Firefox and Edge breaks the most because of it. Another problems shared between Edge and Firefox is `dataprocessor/xmldataprocessor` and `view/observer/selectionobserver`; they seem to break on both browsers.

**Comment by maxbarnas** [comment]
## Results of tests
Series of fixes were made:
- https://github.com/ckeditor/ckeditor5-ui/pull/69
- https://github.com/ckeditor/ckeditor5-utils/pull/70
- https://github.com/ckeditor/ckeditor5-engine/pull/580
- https://github.com/ckeditor/ckeditor5-core/pull/17

Manual tests needed polyfill. Related PR will be published soon.

### Firefox
- Unit tests
 - Enabling `selectionchange` event (which is soon to be enabled by default) solves last batch of failing tests
- Manual tests
 - No problems found

### Safari
- Unit tests
 - Engine fixes are needed: https://github.com/ckeditor/ckeditor5/issues/325
 - Problems with BabelJS and Unicode: https://github.com/ckeditor/ckeditor5-engine/issues/576
- Manual tests
 - Found one general error and one problem specifically with Safari https://github.com/ckeditor/ckeditor5-engine/issues/592

### Edge
- Unit tests
 - Testing is postponed while Edge has regression errors https://github.com/ckeditor/ckeditor5/issues/323
- Manual tests
 - Editor runs, but there are plenty of unexpected behaviours, e.g. *bolding* selection that starts and the beginning of the line deletes that text

### IE 11
 - Failed and broken tests are almost in every package. I was unable to run the editor. Details: https://github.com/ckeditor/ckeditor5/issues/329.

**Comment by Reinmar** [comment]
Super, thanks for the detailed output.

**Comment by Reinmar** [comment]
Beside the mentioned tests I have these issues:

* http://tests.ckeditor.dev:1030/build/modules/amd/tests/enter/entercommand [FF and Safari]
* http://tests.ckeditor.dev:1030/build/modules/amd/tests/link/ui/linkballoonpanel [FF only]

**Comment by Reinmar** [comment]
The enter command mentioned above is a regression on master, so it doesn't count. So the only failing test is the one in the link package. Let's move it to a separate ticket.

And for now, it means that we have FF and Safari clean with the exception of:

* https://github.com/ckeditor/ckeditor5-engine/issues/598
* https://github.com/ckeditor/ckeditor5-link/issues/29

So I'm closing this ticket as done (for FF and Safari).
