### ISSUE TITLE
Moving selection over bold boundary causes selection end to move

### ISSUE THREAD

**Issue by stormdr1ve** [ckeditor/ckeditor5#314]
If you start a drag selection, and move it over a bold/non-bold boundary (such as between "the" and "second" in the first paragraph of the sample), the start of the selection will jump to the bold/non-bold boundary.

I have only tested this in Firefox 50 on Linux.

**Comment by Reinmar** [comment]
Thanks for reporting. This is a dup of https://github.com/ckeditor/ckeditor5-engine/issues/401. We haven't implemented support for selection direction in the view of the engine yet.

**Comment by Reinmar** [comment]
PS. Please not that support for Firefox will be added in iteration 3 (we're working on it now).
