### ISSUE TITLE
Confusing characters after transform emoji using text-transformation

### ISSUE THREAD

**Issue by elszczepano** [ckeditor/ckeditor5#3147]
Steps to reproduce:
1. Add custom text transformation e.g.:
```
typing: {
    transformations: {
        extra: [
	    { from: ':)', to: '🙂' },
	    { from: ':+1:', to: '👍' },
	    { from: ':tada:', to: '🎉' }
        ]
    }
}
```
2. Type e.g `:tada:` and then push space a few times. 

![2019-07-05 09 44 34](https://user-images.githubusercontent.com/23155008/60707359-d1832400-9f0b-11e9-89d2-4f9d90b294af.gif)

**Comment by elszczepano** [comment]
It may be somehow related. If you add a lot of emojis strange characters are shown (I've shown it in a comment for simplicity - it occurs in the main editor too). Also, the editor inserts content in the other place than a marker position.

![Oct-18-2019 09-11-53](https://user-images.githubusercontent.com/23155008/67073446-6510f580-f187-11e9-9a35-ba318c795314.gif)

**Comment by farthinker** [comment]
I found a working solution:
https://github.com/mycolorway/ckeditor5-typing/commit/90cfb1cdf3103336562cbb2bf1a31557bbb169ee
https://github.com/mycolorway/ckeditor5-utils/commit/835ac1f94e8d3cd0b3992b4618703c486e48af6c

These two commits make sure both `diff` and `fastDiff` correctly handle two-byte characters and the results are correctly normalized.
