### ISSUE TITLE
Extra space at end of paragraphs causes following paragraph to get styled.

### ISSUE THREAD

**Issue by SteveTheTechie** [ckeditor/ckeditor5#315]
1. Go to the [online demo](https://ckeditor5.github.io/).
2. Double-click on "Notes" to select.
3. Use keyboard (Shift+Right Arrow) to extend the selection to include the extra space at right.  _(Why is that space there?)_  I think you could also do this with the mouse, but have not tried that.
4. Select Heading 1 or other different paragraph style.
5. Paragraph after Notes also gets styled.

The extra space can be "found" in the same way at the end of every paragraph.

**Comment by scofalik** [comment]
Hello, thanks for your report.

This is not an extra space, just an indicator that the selection end's up down in the next block below (in contrary to ending at the end of block above).

This is a default behavior added by the browser. You can try it in simple `<textarea>`s like this Github editor (be sure to make at least two paragraphs and select the one above). This is also a common behavior in many editors, both desktop editors and web editors.

Still you are right that it's unexpected that block below is changed to heading or paragraph when there is no really visible clue that it is selected. For that we already have an issue: https://github.com/ckeditor/ckeditor5-headings/issues/9
