### ISSUE TITLE
Functional requirements

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3163]
*Originally posted by @fredck in https://github.com/ckeditor/ckeditor5/issues/610#issuecomment-337267343.*

---

This is a preliminary analysis of requirements.

When it comes to use cases, we want to support **data tables**. This comes in contrast with the use case we don't want to support at this stage, which is clearly described in the [HTML5 specs for tabular data](https://www.w3.org/TR/html5/tabular-data.html):

> Tables should not be used as layout aids. Historically, many Web authors have tables in HTML as a way to control their page layout making it difficult to extract tabular data from such documents.

We'll still see developers asking for the above though and we'll handle such requests in a separate issue.

## Macro elements

The macro elements of the table feature are:

 * Table: represents the whole table, including the following elements:
  * Row: a sequence of horizontal cells.
  * Column: a sequence of vertical cells.
  * Cell: the smallest unit of the table.
 * Caption: a caption description for the table.

Users would like to operate on all the above elements.

HTML-wise, we follow the [Editor Recommendations specs on tables](http://ckeditor.github.io/editor-recommendations/features/table.html).

## Features

These list of features may be incomplete and it focuses just on UX and high-level features. The order in the list matters as this is the proposed way to releasing enhancements to the feature as a whole.

### Milestone 1 – MVP (ready)

 * Insert / remove tables.
 * CSS controlled styling (kinda nothing to do here... it should just work).
 * Custom selection (table).
 * Type and insert content inside cells and the caption.
 * Caret navigation through the cells.
 * Insert row / column.
 * Remove row / column.
 * Merge cells (if UX is found for it, otherwise part of Milestone 2 will have to be anticipated).
 * Table copy / paste.
 * Set the table header rows.

### Milestone 2 (todo)

 * Support block content inside tables. See ckeditor/ckeditor5-table#56.
 * Custom selection (table + row + columns + cells). See ckeditor/ckeditor5-table#63.
 * Multi-cell styling.
 * Multi-cell copy/paste.
 * Styles, which set classes to tables, to define alignment (like image styles) and different design for different kinds o table. See ckeditor/ckeditor5#3160.
 * Set the table footer rows.
 * Column resizing.
 * Rearrange rows and columns (move them). This may be available as copy/cut + paste first and later as DnD.
 * Caption. See ckeditor/ckeditor5-table#66.
 
## Details

 * Captions should work exactly like in the image feature.
 * Cells selection can contain multiple cells in both horizontal and vertical directions in the middle of a table.
 * Coping cells sends a table to the clipboard based on the subset of cells selected.
 * Pasting behavior is to define, much probably based on CKEditor 4.

**Comment by troyberg** [comment]
Another one here looking for column resizing as well as some of these other features. Any plans for milestone 2 yet?

**Comment by Reinmar** [comment]
We're currently working on https://github.com/ckeditor/ckeditor5/issues/3287 which will,  among many other things, allow changing columns and table widths (but not by dragging - we don't plan that at the moment). 

I'm closing this ticket in favor of more granular tickets. 

**NOTE:** Please upvote specific features from this list: https://github.com/ckeditor/ckeditor5/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Atype%3Afeature++label%3Apackage%3Atable or report new tickets for features which weren't yet reported.

**Comment by firozkhan342** [comment]
I need resize the column in my project, Is there any way to resize the column @Reinmar

**Comment by djcurfew** [comment]
Any update on the resizing columns feature? Thanks!

**Comment by Xuan-Spider** [comment]
Any update on the resizing columns and rows? It is really helped in my project. Thanks @Reinmar

**Comment by dhirendra-singh81** [comment]
Awaiting update on the column and row resizing. Super important for table layouting. Thanks, @Reinmar
