### ISSUE TITLE
Better detection of heading rows

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#3172]
Right now when upcasting table row it is assumed that `headingRows` attribute is calculated only from number of rows of first `<thead>` section (following `<thead>` sections are treated as normal rows).

The other case might be when a `<table>` element does not have `<thead>` nor `<tbody>` sections or a `<tbody>` section with "pseudo table head".

The "pseudo table head" is a row which contains only `<th>` elements.

We might detect such rows as heading rows because right now they will be counted as heading columns which will result in wrong table:

For instance such table:
```html
<table>
	<tr>
		<th>a</th>
		<th>b</th>
	</tr>
	<tr>
		<th>c</th>
		<td>d</td>
	</tr>
</table>
```
 will be converted to a model representation:
```
<table headingColumns="2">
    <tableRow>...</tableRow>
    <tableRow>...</tableRow>
</table>
```
but should be:
```
<table headingColumns="1" headingRows="1">
    <tableRow>...</tableRow>
    <tableRow>...</tableRow>
</table>
```

**Comment by mlewand** [comment]
Also got it reported from one of our users today.

**Comment by Reinmar** [comment]
FYI: https://ckeditor.github.io/editor-recommendations/features/table.html
