### ISSUE TITLE
Editorconfig - rules for `package.json`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#318]
NPM always inserts 2 spaces as an indent. Our code style is a little bit different and manually changes in `package.json` can be troublesome. 

In order to simplify editing this file, I would like to add few lines to `.editorconfig` file:

``` ini
[package.json]
indent_style = space
tab_width = 2
```

Related ticket on npm repository - https://github.com/npm/npm/issues/5694

**Comment by Reinmar** [comment]
Interesting idea. I haven't thought about this... Unfortunately, this isn't the only JSON file out there, so we'd perhaps need a more general rule. OTOH, I've never had any problems with editing JSON files because my Sublime is configured to adjust its settings to a file I'm editing.

**Comment by Reinmar** [comment]
I've just stumbled upon this :D We had a quick internal poll and we agreed that treating `package.json` in a special way is fine.

**Comment by Reinmar** [comment]
I changed our CKE5 dev env. I'll fix remaining CKE5 repos soon.
