### ISSUE TITLE
Error thrown when navigating into the table insertion panel using the keyboard

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#3182]
1. Open http://localhost:8125/ckeditor5-table/tests/manual/table.html
2. Alt+F10 to focus the toolbar,
3. Right arrow until the table button is selected,
4. Arrow down/Space to open the drop-down,
5. Arrow down to move focus to the drop-down,

**Expected:**

The first button in the grid is focused. Or, actually, anything until we figure out the correct accessibility for the grid.

**Actual:**

Error is thrown because the child of the panel has no `focus()` interface.

<img width="1059" alt="screen shot 2018-06-05 at 09 35 27" src="https://user-images.githubusercontent.com/1099479/40961867-212374aa-68a4-11e8-8799-593f72324b8f.png">

**Comment by mlewand** [comment]
#3184 marked as a (partial) duplicate of this task.
