### ISSUE TITLE
Arrow keys should move selection to cell next/previous/above/below cell

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#3227]
## Generalised issue

Arrow keys work differently in all browsers and in all of them they don't do what the user would expect:

* Chrome moves the selection to the right cell if you press down arrow.
* In Firefox arrow keys don't do anything useful.

We need a custom handler for arrow keys. However, it's a non-trivial task due to issues described in https://github.com/ckeditor/ckeditor5-table/issues/108#issuecomment-465529187. We will need to, at least partially, use the browser native handling and try to do something with that.

## Original issues

I wanted to fill the table column and I was surprised that when I press down key selection moved to the cell on the right, not below. The same for arrow up - selection should be moved to the cell above, not on the left. The current behavior makes filling column very inconvenient.

**Comment by jodator** [comment]
Closing as already implemented and a dup of #3267.
