### ISSUE TITLE
Fix failed tests in Edge

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#323]
Related: https://github.com/ckeditor/ckeditor5/issues/312.

This task should be postponed because of recent problems with Edge, e.g. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8619646/

**Comment by Reinmar** [comment]
I think we could postpone Edge to it4. Let's wait for any feedback about https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8619646/.

**Comment by Reinmar** [comment]
Let's follow all the issues in https://github.com/ckeditor/ckeditor5/issues/423.
