### ISSUE TITLE
Support for nested tables

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3232]
Add support for nesting one table inside another.

This feature wasn't on our roadmap yet, but let's gather a feedback if this is a common requirement.

**NOTE**: It is possible to enable support for nested tables. See https://github.com/ckeditor/ckeditor5-table/issues/121#issuecomment-528251188 for how to do that.

--- 

If you'd like this to be officially supported add 👍 to this ticket.

**Comment by aaroncalderon** [comment]
@Reinmar I looked into this and based off the sample [Chat with mentions](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/chat-with-mentions.html) I was able to figure out what you ment by:

> You will need to wrap this code with function and pass it to `config.extraPlugins`...

JavaScript Snippet below:

```JavaScript
  ClassicEditor
    .create(document.querySelector('.editor'), {
      extraPlugins: [AllowNestedTables],
      toolbar: {
        items: [
          'heading',
          '|',
          'fontFamily',
          'fontBackgroundColor',
          'fontColor',
          'bold',
          'underline',
          'italic',
          'strikethrough',
          'link',
          'bulletedList',
          'numberedList',
          '|',
          'indent',
          'outdent',
          '|',
          'imageUpload',
          'blockQuote',
          'insertTable',
          'mediaEmbed',
          'undo',
          'redo',
          'code',
          'codeBlock',
          'superscript',
          'subscript',
          'highlight'
        ]
      },
      language: 'en',
      image: {
        toolbar: [
          'imageTextAlternative',
          'imageStyle:full',
          'imageStyle:side'
        ]
      },
      table: {
        contentToolbar: [
          'tableColumn',
          'tableRow',
          'mergeTableCells',
          'tableCellProperties',
          'tableProperties'
        ]
      },
      licenseKey: '',

    })
    .then(editor => {
      window.editor = editor;
    })
    .catch(error => {
      console.error('Oops, something gone wrong!');
      console.error(
        'Please, report the following error in the https://github.com/ckeditor/ckeditor5 with the build id and the error stack trace:'
      );
      console.warn('Build id: kwgdr5ln3fje-waex6uolg10x');
      console.error(error);
    });

  function AllowNestedTables ( editor ) {
    editor.model.schema.on('checkChild', (evt, args) => {
        const context = args[0];
        const childDefinition = args[1];

        if (context.endsWith('tableCell') && childDefinition && childDefinition.name == 'table') {
          // Prevent next listeners from being called.
          evt.stop();
          // Set the checkChild()'s return value.
          evt.return = true;
        }
      }, {
        priority: 'highest'
      });
  }
```

**Comment by athuldom** [comment]
i have seen the above code snippet. I am using this editor in my react project. Can any one show me how to solve the issues with the above mentioned code in a react class component. As i am new to this, a help will be great full.
Thank you

**Comment by aaroncalderon** [comment]
@athuldom so, I googled for `ckeditor react component` and the first link I got was [Rich text editor component for React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html). So, it has a __configuration__ property. All you have to do is add the configuration as shown above to include the `extraPlugins` and `allowNestedTables` bit.

**Comment by deepaksm1** [comment]
How to implement this in Angular, I tried below code but not working

ClassicEditor.extraPlugins = [ allowNestedTables ]

`
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
//	import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
//	import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
//	import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
//	import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';

import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';

export default class ClassicEditor extends ClassicEditorBase { }

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
	Essentials,
	//	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	BlockQuote,
	//	CKFinder,
	EasyImage,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	//	ImageToolbar,
	ImageResize,
	ImageUpload,
	Indent,
	List,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TextTransformation,
	TableProperties,
	TableCellProperties
];
ClassicEditor.extraPlugins = [ allowNestedTables ]
// Editor configuration.
ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic',
			'bulletedList',
			'numberedList',
			'|',
			'indent',
			'outdent',
			'|',
			'imageUpload',
			'blockQuote',
			'insertTable',
			'undo',
			'redo'
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells',
			'tableProperties', 'tableCellProperties'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};

function allowNestedTables ( editor ) {
    editor.model.schema.on('checkChild', (evt, args) => {
        const context = args[0];
        const childDefinition = args[1];

        if (context.endsWith('tableCell') && childDefinition && childDefinition.name == 'table') {
          // Prevent next listeners from being called.
          evt.stop();
          // Set the checkChild()'s return value.
          evt.return = true;
        }
      }, {
        priority: 'highest'
      });
  }
`

**Comment by deepaksm1** [comment]
> How to implement this in Angular, I tried below code but not working
> 
> ClassicEditor.extraPlugins = [ allowNestedTables ]
> 
> ```
> import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
> 
> import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
> //	import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
> import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
> import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
> import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
> import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
> //	import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
> import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
> import Heading from '@ckeditor/ckeditor5-heading/src/heading';
> import Image from '@ckeditor/ckeditor5-image/src/image';
> import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
> import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
> //	import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
> import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
> import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
> import Indent from '@ckeditor/ckeditor5-indent/src/indent';
> //	import Link from '@ckeditor/ckeditor5-link/src/link';
> import List from '@ckeditor/ckeditor5-list/src/list';
> import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
> import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
> import Table from '@ckeditor/ckeditor5-table/src/table';
> import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
> import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';
> 
> import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
> import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
> 
> export default class ClassicEditor extends ClassicEditorBase { }
> 
> // Plugins to include in the build.
> ClassicEditor.builtinPlugins = [
> 	Essentials,
> 	//	UploadAdapter,
> 	Autoformat,
> 	Bold,
> 	Italic,
> 	BlockQuote,
> 	//	CKFinder,
> 	EasyImage,
> 	Heading,
> 	Image,
> 	ImageCaption,
> 	ImageStyle,
> 	//	ImageToolbar,
> 	ImageResize,
> 	ImageUpload,
> 	Indent,
> 	List,
> 	Paragraph,
> 	PasteFromOffice,
> 	Table,
> 	TableToolbar,
> 	TextTransformation,
> 	TableProperties,
> 	TableCellProperties
> ];
> ClassicEditor.extraPlugins = [ allowNestedTables ]
> // Editor configuration.
> ClassicEditor.defaultConfig = {
> 	toolbar: {
> 		items: [
> 			'heading',
> 			'|',
> 			'bold',
> 			'italic',
> 			'bulletedList',
> 			'numberedList',
> 			'|',
> 			'indent',
> 			'outdent',
> 			'|',
> 			'imageUpload',
> 			'blockQuote',
> 			'insertTable',
> 			'undo',
> 			'redo'
> 		]
> 	},
> 	image: {
> 		toolbar: [
> 			'imageStyle:full',
> 			'imageStyle:side',
> 			'|',
> 			'imageTextAlternative'
> 		]
> 	},
> 	table: {
> 		contentToolbar: [
> 			'tableColumn',
> 			'tableRow',
> 			'mergeTableCells',
> 			'tableProperties', 'tableCellProperties'
> 		]
> 	},
> 	// This value must be kept in sync with the language defined in webpack.config.js.
> 	language: 'en'
> };
> 
> function allowNestedTables ( editor ) {
>     editor.model.schema.on('checkChild', (evt, args) => {
>         const context = args[0];
>         const childDefinition = args[1];
>         if (context.endsWith('tableCell') && childDefinition && childDefinition.name == 'table') {
>           // Prevent next listeners from being called.
>           evt.stop();
>           // Set the checkChild()'s return value.
>           evt.return = true;
>         }
>       }, {
>         priority: 'highest'
>       });
>   }
> ```

Solved this shifted extra plugins in 
```
ClassicEditor.defaultConfig = {
	extraPlugins: [allowNestedTables], ....
```
