### ISSUE TITLE
Implement TableUtils#getTable()

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3233]
We can simplify:

```js
const table = editor.model.document.selection.getFirstPosition().getAncestors().find( item => item.name == 'table' );
```

To:

```js
const table = tableUtils.getTable( editor.model.document.selection );
```

I was surprised to not find this function because I thought I saw it somewhere.

**Comment by jodator** [comment]
We already have similar methods for `View` position/element. The `findAncestor()` is used extensively in tables.

**Comment by Reinmar** [comment]
Conclusion: Add `findAncestor()` to a model position and remove all the `findAncestor()` helper function use from cke5-table.
