### ISSUE TITLE
[Safari] Fix failing engine tests

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#325]
Related: https://github.com/ckeditor/ckeditor5/issues/312.

**Browser:** Safari 9.

**Problematic test groups:**
- [http://localhost:1030/build/modules/amd/tests/engine/view/renderer](http://localhost:1030/build/modules/amd/tests/engine/view/renderer),
- [http://localhost:1030/build/modules/amd/tests/engine/view/document/jumpoverinlinefiller](http://localhost:1030/build/modules/amd/tests/engine/view/document/jumpoverinlinefiller).
- http://tests.ckeditor.dev:1030/build/modules/amd/tests/engine/model/composer/modifyselection

Because of the complexity, this task should be directed by @Reinmar or @pjasiun.

**Comment by Reinmar** [comment]
I added one test to the list – modifyselection is also failing on my machine. And pretty badly in fact. I haven't seen this reported anywhere as "to be fixed". This was only mentioned somewhere that there's problem with `normalize()` and I thought that this is solved.

**Comment by maxbarnas** [comment]
I've checked `modifyselection` on my machine. All 47 tests are passing. Strange, but thanks for pointing it out.

**Comment by Reinmar** [comment]
They fail due to the `normalize()` method missing in Safari. And you explained it here: https://github.com/ckeditor/ckeditor5-engine/issues/576#issuecomment-242037264. How can they pass now?

**Comment by Reinmar** [comment]
In fact, this ticket should be moved here: https://github.com/ckeditor/ckeditor5-engine/issues/598.
