### ISSUE TITLE
Keyboard navigation skips a cell if a widget is the only child

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#3260]
![2019-02-19 14-28-38 2019-02-19 14_29_51](https://user-images.githubusercontent.com/1099479/53019960-3c005f80-3456-11e9-99ca-b02770964b3d.gif)

**Comment by niegowski** [comment]
Is this issue still valid?

**Comment by oleq** [comment]
I couldn't reproduce it. Probably resolved along with #3267.
