### ISSUE TITLE
Implement a custom navigation through tables

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3267]
Currently, we allow the browser to do its thing. Some support <kbd>Tab</kbd>, most support arrow keys, but all that is inconsistent and buggy. We should design and implement our own solution.

**Comment by Reinmar** [comment]
Two stages:

*   Handling selection at the cell boundary. When the selection is at the start and you press up, then you go to the end of the cell above the current cell. When you press left, you go to the end of the cell on the left. Symmetrical for the end of cell positions. Note: an empty table creates an interesting case and should be handled correctly.
*   Handling selections not at the cell boundary by comparing rects.

**Comment by oleq** [comment]
Some tickets to review/close along with this one:
* https://github.com/ckeditor/ckeditor5/issues/3286
* https://github.com/ckeditor/ckeditor5/issues/3177
* https://github.com/ckeditor/ckeditor5/issues/1709
