### ISSUE TITLE
Editor crashes with a downcasting error when input contain an empty <tr></tr>

### ISSUE THREAD

**Issue by hponcet** [ckeditor/ckeditor5#3274]
This was fixed if i hard replace the source html by `replace(/<tr[^<]*><\/tr>/gm, '<tr><th></th></tr>')`

**Comment by mlewand** [comment]
The thing is that ideally we should not end up with model that has content like that - this is clearly pointless table markup.

We did put extra effort in iteration 30 to make sure no empty rows are created by _our core_ plugins (ckeditor/ckeditor5-table#277, ckeditor/ckeditor5-table#278). But in the end we decided that we need to fix the source of the issue, rather to make all our algorithms work with flawed table structure.

I mentioned that there will be But there are still more cases like this popping out:

*   #6439
*   This very issue, although there's unfortunately no repro-case the easiest one I can see is simply pasting content from external sources - we will never be able to guarantee that the content doesn't contain empty rows.

**Comment by jodator** [comment]
> I mentioned that there will be issues like this popping out with time, and we can see some examples:

The issues you mentioned comes from, unfortunately, wrong table handling in our commands. The fixes are on the way: #6545 & #6546. 

However we should make our conversion process resilient and anticipate wrong input data.
