### ISSUE TITLE
Table header removed if row/column just after it is deleted

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#3278]
### Steps to reproduce

1. Make a table with one or more header rows.
2. Put selection in a row after the last header row.
3. Remove the row.

In the result, the header is gone 😱. The same happens for columns.

![Aug-15-2019 12-51-30](https://user-images.githubusercontent.com/1502228/63090602-1adb8000-bf5c-11e9-84c0-a3a7e567208c.gif)

**Comment by jodator** [comment]
Looks like fixed on latest master. Not linking any specific issue or PR as it might be fixed somewhere when working on #6502 and related issues.

**Comment by jodator** [comment]
Current state:

![](https://user-images.githubusercontent.com/247363/82876916-c9740e80-9f39-11ea-8669-c8edb0e4a912.gif)
