### ISSUE TITLE
Tables need "remove empty row" post-fixer

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#3280]
There is at least one case when it is possible to create an empty table row, even without real-time collaboration. I suspect it is also possible through some simultaneous changes in RTC.

To reproduce it, you need a table where there is only one non-spanned cell in a row and then remove this row through removing a column. See the gif below for an example.

![Aug-15-2019 17-58-20](https://user-images.githubusercontent.com/1502228/63108399-0c568e00-bf87-11e9-99ae-3bad92959b8c.gif)

![image](https://user-images.githubusercontent.com/1502228/63108418-17a9b980-bf87-11e9-8b4b-aff0c670317d.png)

A similar thing happens when merging down but it is actually handled in the command:

```js
// Remove empty row after merging.
if ( !removedTableCellRow.childCount ) {
	removeEmptyRow( removedTableCellRow, writer );
}
```

However, things like this should be handled through post-fixers. A command should do what it is supposed to do and then post-fixer should clean whatever incorrect state happens. It is better to handle it in post-fixer because:

1. Multiple commands are handled at once.
2. RTC scenarios are handled as well.

**Comment by mlewand** [comment]
Issue in remove column described in the first post here caused #6422. I wonder whether we should really go for a post-fixer, or make sure that the commands properly handle the model. Another solution might be both.

**Comment by Reinmar** [comment]
> I wonder whether we should really go for a post-fixer, or make sure that the commands properly handle the model. Another solution might be both.

I'd go with commands leaving a clean editor first and see if we have any problems. If we'll see that we cannot really control it from the command perspective, we need a post-fixer indeed. A post-fixer should be a last resort.

**Comment by jodator** [comment]
So ultimately we went with the cleanup after yourself in commands and utils by introducing `TableUtils.removeRow()` and `TableUtils.removeColumn()` methods.

This is required to use that always as table modifications are not trivial and simple remove row element is not enough to create a proper table state. The reason of this is that after merging some cells you might create an empty row - which will yield table model error as defined in HTML specs. The solution for this is to remove this row and update overlapping cells `rowspan` attribute to not create an invalid table state.

Handled, among others, by: #6502.
