### ISSUE TITLE
Table and column resizing (by mouse)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3284]
We've just introduced [image resizing](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#resizing-images) and we can quite easily implement a similar solution for tables too.

Then, the second thing is columns resizing. For this we cannot reuse the logic from image resizing so it's a far bigger task.

For the first implementation we'll focus on horizontal axis only (column resize, table width resize). If you're interested in row height resize head on to #11637 issue.

**Note:** It will be possible to resize rows/columns/tables by using the [table styles](https://github.com/ckeditor/ckeditor5/issues/3287) feature.

---

If you'd like to see resizing in tables, please react with 👍 to this ticket **and** explain in the comment which part is crucial for you.

**Comment by farthinker** [comment]
The column width resize is very crucial for us. Table with `table-layout: auto` usually generates an unexpected result, and our user couldn't do anything about it.
But resizing the whole table is not necessary, as we always set the table width to 100%.

**Comment by wwalc** [comment]
A few questions, anyone interested in this feature please feel free to jump in.

*   What units should be used for resized columns (% or px)? If pixels then please explain why and what with ensuring that the content responsive?
*   Is it fine if only a column that the user decided to change will have the width set?

**Comment by mat-berg** [comment]
I would mimic google docs or word resizing mechanism with the mouse, the end user does not care about % or px, they adjust the size with their mouse as they like and that's it. So I guess pixel under the hood.

**Comment by kuku711** [comment]
> A few questions, anyone interested in this feature please feel free to jump in.
> 
> * What units should be used for resized columns (% or px)? If pixels then please explain why and what with ensuring that the content responsive?
> * Is it fine if only a column that the user decided to change will have the width set?

I will be happy to get this feature!
- Units should be in % only, when all columns will have fix width and column will be added it will destroy the layout (will get more width then the document have).
- While developing the feature you will see if set width is needed for all the table or just the touched columns.
Thank you!!

**Comment by NeilD321** [comment]
Completely disagree with kuku711. 
If a user resizes a table they are choosing to move from responsive to a set size and they are doing so for a reason. Table size when changed by the user using drag handles should be px. Otherwise the user does not know what will happen when viewed on other devices and that's the whole point. Our users are making documents, not responsive pages. 

In the dialog though, let me choose.

Columns can be either.

**Comment by rjschof** [comment]
@Reinmar Can we please get an update on where this feature might be on the roadmap?

**Comment by neongreen** [comment]
Re/ px versus % — how do other editors do it? E.g. I think prosemirror/tiptap has mouse-resizable columns.

**Comment by neongreen** [comment]
Note: perhaps px vs % should be configurable when integrating the editor.

For some products, "our users are making documents, not responsive pages" is absolutely true. For our product ([Brick](https://brick.do)), the opposite is true.

**Comment by mlewand** [comment]
We'll be starting with column resize (which will also allow to resize a table itself).

However, we won't tackle row resize yet, I've extracted it to a separate issue: #11637. **For anyone interested in row resize**, please upvote the linked issue too. This will allow us to better understand if there's a desire in community for this feature.

**Comment by neongreen** [comment]
Is this shipped already?

**Comment by richa0312** [comment]
I want column resize feature for one of my client, please do let us know when it will be ready with proper example.?

**Comment by Reinmar** [comment]
This feature was shipped a couple months ago: https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-column-resize
