### ISSUE TITLE
Manual tests require explicit polyfill insertion

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#332]
Related: https://github.com/ckeditor/ckeditor5/issues/312.

Bender can't inject polyfill in manual tests using `/* @bender-include: ... */` directive. We have to add the polyfill in the old-fashioned way.

**UPDATE:**
It can be done using bender's directive from MD files. Details below in the comments.

**Comment by Reinmar** [comment]
We should've told you that in case of manual tests you need to add this annotation to MD files, not JS. And it works :).

![screen shot 2016-09-16 at 09 08 47](https://cloud.githubusercontent.com/assets/156149/18577954/602ed194-7bed-11e6-9726-5aacc3b52f5a.png)

**Comment by maxbarnas** [comment]
In that case I will modify compiler utils to inject this method into manual test's MD files.

**Comment by Reinmar** [comment]
Fixed with https://github.com/ckeditor/ckeditor5-dev-compiler/issues/39.
