### ISSUE TITLE
Should we describe modules and namespaces in JSDoc?

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#334]
While working on https://github.com/ckeditor/ckeditor5-engine/issues/610 I tried to describe modules and namespaces (in corresponding `*.jsdoc` file). I noticed lack of any output after generating documentation.

This might be of course my lack of knowledge about JSDoc, but the question that came to me is - does separate description of module at the top of module's source file and description of namespace  in `*.jsdoc` file really needed?

**Comment by Reinmar** [comment]
After we switch to `@modules` this won't be an issue, because it will be natural to document every one of them.

See #328.
