### ISSUE TITLE
[Chrome] What should we do about occasional rendering issues?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#3399]
## The problem

We've discovered recently that Chrome has some issues with rendering certain elements which have `display: inline-block`. Check out the gap between the first alignment button and the toolbar separator. It changes as the window is resized.

The problem is that according to the dev tools the gap is the same (sic!). All the widths/margins/paddings etc. remain untouched. The problem is in the rendering layer of the web browser.

![kapture 2018-02-16 at 14 41 32](https://user-images.githubusercontent.com/1099479/36310203-99c66804-1327-11e8-88ec-c84794d29297.gif)

There are also other related issues. Like this one, when the web browser claims the elements to have the same height while clearly they are rendered differently:

![image](https://user-images.githubusercontent.com/1099479/36310281-cd5ac246-1327-11e8-8cb4-f05d821e73d2.png)

![image](https://user-images.githubusercontent.com/1099479/36310289-d1dd4938-1327-11e8-847a-3772549c97ef.png)

![image](https://user-images.githubusercontent.com/1099479/36310330-f5603d48-1327-11e8-8905-be9b0c177f1c.png)

Another case:

According to Chrome all the margins (orange) are **the same**:
![image](https://user-images.githubusercontent.com/1099479/36310357-02634da0-1328-11e8-8f76-c06a2de47339.png)

## Solutions

I checked some options here and there are 2 that fix the issue probably because they change the rendering strategy of the viewport:
* `display: block` for `.ck-toolbar > * `, which then requires float (doesn't it?). It's unacceptable since we're flex-oriented now.
* `display: inline-flex` for `.ck-toolbar > * `, which also fixes the issue and surprisingly doesn't break anything. This option is definitely worth investigating.

cc @Reinmar @dkonopka

**Comment by Reinmar** [comment]
This issue is dead and I didn't see any other reports so I assume that it got somehow fixed. Either by us or Chrome.
