### ISSUE TITLE
Content filtering – tests, fixes and stability

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#341]
Currently, it's possible to load e.g.:

``` html
<ul><li><h2>dfdd</h2></li></ul>
```

and you're even able to retrieve this data back :D.

The schema doesn't allow headings in list items:

``` js
schema.registerItem( 'listItem', '$block' );
schema.allow( {
    name: 'listItem',
    inside: '$root',
    attributes: [ 'type', 'indent' ]
} );
```

So the heading or list should be filtered out. There will be many cases like this. Elements that we don't support or which combinations we don't support should be somehow, gracefully, handled upon conversion to the model.

This requires a lot of tests and most likely many fixes. So far we haven't tested for that and haven't used schema extensively. There will be time when we'll need to do that and this will be we'll want to filter pasted content in a stable way.

**Comment by scofalik** [comment]
That's true, there is no check in list item view-to-model converter and this is mistake. However, default converters have schema checks. There is schema filtering on view-to-model conversion, in `buildViewConverter`.

So I agree this is more overall issue, that we don't care about schema, but this could be also reported as a bug in `List` feature.

**Comment by Reinmar** [comment]
Important use case: https://github.com/ckeditor/ckeditor5/issues/348. It's also needed for pasting.

**Comment by Reinmar** [comment]
Bug: https://github.com/ckeditor/ckeditor5-paragraph/issues/18

**Comment by Reinmar** [comment]
We closed something around 20 tickets in ckeditor5-paragraph, ckeditor5-image and ckeditor5-lists improving the stability of pasting and general conversion's UX (e.g. aligning disallowed structures to the editor's schema). I can still crash the editor from time to time but I think that we're on a level of stability where we can say that pasting is well covered.

**Comment by scofalik** [comment]
Could you point me to examples which crash editor (or is it just "copy a website that is big and rich enough")? Any idea what is crashing?

**Comment by Reinmar** [comment]
E.g. https://www.theatlantic.com/entertainment/archive/2017/04/the-why-of-cooking-samin-nosrat/523923/ (if you copy the entire content)

Previously I've some other website crashing but with the same error, I think.

**Comment by scofalik** [comment]
Ah, goddamn those bugs in Mapper :).

Anyway it's worth looking at somewhere in near future.
