### ISSUE TITLE
In-house compiler vs Webpack for the whole process

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#345]
Current state of things:
1. CKEditor code is kept in multiple packages which are kept in multiple repositories.
2. We use a custom compiler which gathers all the code from all those packages and outputs it into one directory. Optionally, it also transpiles the ES6 modules into AMD or CJS. We call this step "compilation".
3. The developers can use the compilation to:
   - either bundle the code using a bundler (Webpack, Rollup, etc.) of their choice,
   - or include the code into their projects by simply importing needed modules (e.g. a CJS compilation of CKEditor can be freely used in Node.js env).

Pros:
- CKEditor is bundler-independent. This is safe for the future and flexible.
- We have full control over the compilation process, so we can freely adjust some CKEditor specific things.
- No boilerplate overhead. Each file is either an ES6 module, CJS module or AMD module. Compare that with what [Webpack does](https://github.com/webpack/webpack/tree/master/examples/multi-part-library).
- The compilation is simply a source code gathered into one place. It's easy to reason about, play with, transform, etc.
- Not really a pro, but worth mentioning, that [Lodash has its compiler](https://lodash.com/custom-builds) too.

Cons:
- Performance issues when using a compilation (in AMD format) in the testing environment. There are so many modules now that it takes the browser 1-3s to load them locally. Running tests became unacceptably slow.
- Loading external resources. What if some package requires e.g. a module from lodash or some polyfill? Currently, you need to [commit this code to your repository](https://github.com/ckeditor/ckeditor5-utils/tree/master/src/lib/lodash).
## Options
1. Keep the current setup and find solution a solution to the problems (performance issues and loading external resources).
2. Keep the in-house compiler to satisfy the use cases where a compilation can be used (building CKEditor into other projects) and, simultaneously, use e.g. Webpack for the whole testing and bundling processes (without use of compiler).
   - Cons:
     - We'll have to maintain two versions of the same functionality, because some custom processing which we can now do in the compiler will need to be copied to the Webpack loader.
     - This doesn't solve the problem with loading external resources, because, while with Webpack we could use its features, we'd need to handle that in the compiler in some way (copy Webpack's functionality?).
3. Totally switch to some bundler and forget about being flexible, cause we're overengineering it, otherwise.
   - Cons:
     - less flexibility,
     - satisfies less cases,
     - makes us fully dependent on the specific bundler.
## Proposal

I'd gladly choose option 3, because it'd be simple. But it doesn't feel right.

Therefore, I'm afraid we need to find solutions for issues with the 1 option.
### Testing Environment

As for the performance issues, we plan to move to Karma and we can use Webpack with it. Our test runner will have to launch the compiler and upon it launch Webpack.

This sounds simple, but I'm bit afraid about the number of files to watch (cause you need a watcher). I wonder what are the OS real limits. And I also wonder if we could plug the Vinyl stream (which we normally save to the disk) straight to Webpack to save some time.
### External Resources

This topic is more tricky and makes my nights sleepless. I don't want to duplicate Webpack's features because that'd be ridiculous. So we need some simple, flexible solution, that one could use in the (rare) cases when external resource is required.

The idea that came to my mind is to expose a compiler hook which the packages could use to plug their resources. For example:
1. Compiler is processing ckeditor5-utils.
2. Function exposed by `ckeditor5-utils/dev/compiler-hook.js` is executed.
3. That function is able to register a package (by name - so e.g. `lodash`) and let compiler know where to look for that resource. The function can also produce this code (e.g. run `lodash-cli` on the fly).
4. The compiler will copy those files together with the package and replace `import x from '@lodash/foo/bar.js';` with `import x from 'path/to/lodash/foo/bar.js';`.

Moreover:
- If any other package tries to register the same resource, the existing one will be reused. This will allow reusing the same dependency.
- Compiler can also allow plugging resources through its configuration, allowing developers to specify can be located in their case.
## Help Needed

We've got far too little experience with Webpack or other options and we're thinking about this for too long, so there's a chance that we don't see some obvious or simply better option.

**Comment by Reinmar** [comment]
BTW, I've just stumbled upon https://github.com/chymz/ng2-ckeditor/issues/41 :D

**Comment by pjasiun** [comment]
> No boilerplate overhead. Each file is either an ES6 module, CJS module or AMD module. Compare that with what Webpack does.

I do not get your comparison. You compare building to ES6/CJS/AMD in the current CKE solution (that can WebPack do too https://webpack.github.io/docs/configuration.html#output-library) with building to UMD what the current CKE solution could do too un the future.

**Comment by Reinmar** [comment]
> I do not get your comparison. You compare building to ES6/CJS/AMD in the current CKE solution (what Webpack can do too: https://webpack.github.io/docs/configuration.html#output-library) with building to UMD what the current CKE solution could do in the future too.

We talked yesterday that Webpack's entry points look like this: https://github.com/webpack/webpack/tree/master/examples/multi-part-library Remember? ;) Unless there's an option to get clean source packages out of Webpack, this isn't acceptable.

**Comment by pjasiun** [comment]
I think that `ckeditor5-compiler` should be limited to what it do with the ES6 flag, so gathering all source code in one place. It should not use Bable, should not transpile the code nor include System.js. It should prepare the code with proper ES6 linking between modules. Because `ckeditor5-compiler` would not do any compilation we could consider renaming it (again).

Then you can include this code into your project and use it in any way you need, merging it with your building system, if you want to.

Then, we should provide the real compilation a.k.a. bundling. It should generate a single file in CJS/AMD/UMD format. We could use Webpack for it. Also, for simpler Webpack integration we could distribute CKEditor as a Webpack dll.

**Comment by Reinmar** [comment]
> I think that ckeditor5-compiler should be limited to what it do with the ES6 flag, so gathering all source code in one place.

If compiler will be able to produce only ES6 output, then you e.g. wouldn't be able to easily include CKEditor into your CJS project (say, Node.js env or project which uses Browserify unless it handles ES6 modules). I don't think there's anything wrong with being able to produce CJS and AMD – there's no magic there and it's convenient.

**Comment by Reinmar** [comment]
This issue was resolved by https://github.com/ckeditor/ckeditor5/issues/362. We dropped the compilation and implement our specific bundling needs in form of a plugins for bundlers (initially we focus on Webpack and Rollup).
