### ISSUE TITLE
Text content from unsupported HTML elements could be preserved

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#348]
Forgive me if I reported this in the wrong repository.

When CKEditor is launched to edit existing content with unsupported elements (e.g. an HTML table), then at least the text content inside could be preserved. Currently the whole element is completely removed.

Found when testing CKEditor 5 in Drupal, when trying to edit existing content previously created with CKEditor 4.

**Comment by Reinmar** [comment]
Part of https://github.com/ckeditor/ckeditor5/issues/341.
