### ISSUE TITLE
Use constructors instead of strings for features in bundler config

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#350]
https://github.com/ckeditor/ckeditor5-core/pull/33 will remove loading features by strings. It means the bundler config will not be able to build an editor.

Instead of strings, need to use the features constructors.

**Comment by Reinmar** [comment]
It now accepts an array of strings and that can be still true, because it has access to the file system. It may even work without any change needed – did you test it with ckeditor/ckeditor5-core#33?

**Comment by pomek** [comment]
Yep, it works. I forgot that bundler resolves the strings. So, this ticket is invalid.
