### ISSUE TITLE
Configure CI which allows testing setup of branches

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#356]
As a developer I would like to know whether my new feature won't break the whole editor.

I would like to run tests of all modules which I changed.

An example:

I'm creating a new big feature in `ckeditor5-engine`. It requires changes in other repositories - `ckeditor5-core` and `ckeditor5-undo`. When the feature is ready, I would like to check whether packages which depend on `ckeditor5-engine`, `ckeditor5-core` and `ckeditor5-undo` are still valid and work as well.

In order to do this, I will create a new branch `ci/ckeditor5-engine/ticket_id` and update the packages in `package.json`. I have to add branches for particular packages. After that I will push the branch and CI will execute all the tests automatically.

CI won't check code coverage because it should be checked by CIs for a particular packages.

What do we need to close this ticket?

- Configuration for CI which allows running all the tests without generating the CC report.
- Introduce Build badge in README.

**Comment by Reinmar** [comment]
Unfortunately, it does not seem to work :(

https://travis-ci.org/ckeditor/ckeditor5/builds/178348366

On this configuration of branches the tests pass for me locally, but they do not pass on CI. My guess is that wrong version of packages are sourced by the compiler.

**Comment by Reinmar** [comment]
I moved the issue to https://github.com/ckeditor/ckeditor5/issues/368.
