### ISSUE TITLE
Change to scoped packages

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#359]
I can't find where but we agreed to release our CKEditor 5 packages as scoped npm packages. This means that their current names will be preceded with `@ckeditor/`. This influences couple of things:

1. The compiler and other tools operating on packages names will  have to take this into consideration. Note: this is a pretty big change, because the packages are then installed in `node_modules/@<scope>/`
2. The `Plugin.name` property (added in https://github.com/ckeditor/ckeditor5-core/issues/27) should most likely also consider this.
3. All deps in all packages will need to be aligned.

**Comment by Reinmar** [comment]
I think that the big question is whether we allow two packages with the same name but in different scopes loaded to the same editor. I guess... why not. But if we agree that a single `ckeditor5-<name>` package can only exist once in a given installation, then we wouldn't have to consider scope names in the code of the editor (`Plugin.name`), because it would be a purely "installational" thing.

**Comment by fredck** [comment]
Agree... if we would ever suffer with name collision, we will be able to solve this problem later.

**Comment by Reinmar** [comment]
> Agree... if we would ever suffer with name collision, we will be able to solve this problem later.

I don't think there will be a clean way to solve such issues later. But name collisions in a single editor setup are very unlikely. After all, there can be many image features out there, but you'll have just one image feature in your editor. 

To be clear – my 2nd comment still proposes scoped packages, but it limits them to the npm+compiler level. Above that, in JS, there will be simpler names. In fact, on compilation to browser JS we lose also other aspect of npm's reality which is multiple versions of one package (if versions don't match).

**Comment by Reinmar** [comment]
We've just rolled out this change when working on #389.
