### ISSUE TITLE
Consider dropping lodash

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#361]
We use it now only in 26 places and half of this is `clone()`, `extend()`, and `is*` methods. 

It's hard to say how much space lodash build for CKE takes, cause we use the modular one, but it's definitely more than what we'd need to implement our simple replacements for these methods. Lodash is extremely modular (which may add quite a lot of noise in a build) and implements a support for chaining which I've never seen we used.

The reasons why we used lodash was to not reinvent the wheel and use a well tested solution. But lodash makes less sense in ES6 world than it did before (and when I last checked lodash lacked support for ES6), we're not used to use it heavily and as a result it's a bit odd situation.

OTOH, there's a few bytes to win, faster compilation times and that's it. Plus, we'll have to maintain more code ourselves. So perhaps it's still better if we use lodash. Maybe we should just spend more time getting familiar with it.

WDYT?

**Comment by fredck** [comment]
Considering that this is already implemented, I would not touch it. Especially because we add our API layer to it, so we can replace it at any moment.

For the future, we may first check if there are other useful things in lodash that we can benefit from.

**Comment by Reinmar** [comment]
I've been checking Webpack dlls and when browsing a source of CKEditor 5 build I searched for "lodash". This is the scrollbar:

![image](https://cloud.githubusercontent.com/assets/156149/20893344/bc175f54-bb11-11e6-81d3-478c9e8ab3b1.png)

The longer blocks of yellow are all lodash packages... So these couple of lodash functions which we use make for a ~20% of our code ;|

It's a very naive check, but I think that it can be quite precise. And it can be even worse if you consider that our code in this DLL has extensive API docs and lodash has little. So after stripping comments out lodash may take even more space.

**Comment by Reinmar** [comment]
I'm closing this ticket in favour of https://github.com/ckeditor/ckeditor5/issues/435 and https://github.com/ckeditor/ckeditor5-utils/issues/188.
