### ISSUE TITLE
Switch to ESLint

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#366]
JSCS was merged into ESLint and this makes ESLint the new standard.

We need to define our ESLint preset and publish it on npm.

Most importantly, it seems that moving to ESLint will render ckeditor5-dev-lint useless – it'll be better to use npm script for that. The problematic part may be replacing `guppy-pre-commit` with something else that would run this npm task. This should stay automated, so if there's no package which by default calls ESLint, then we'd need to keep ckeditor5-dev-lint.

Also, please mind that ckeditor5-dev-lint has the ability to lint only the changed files which are added to the git index. I wouldn't like to drop this optimisation, cause linting the engine takes quite a lot of time. But perhaps ESLint has similar optimisations by default. E.g. I heard about its cache mechanism.

**Comment by Comandeer** [comment]
Maybe [preset from BEMQuery](https://github.com/BEMQuery/bemquery-package-boilerplate/blob/master/config/eslint/default.json) could be used as a starting point for preset? It should be similar to the codestyle used in CKE5, with minor changes only (e.g. BEMQuery always requires curly braces for arrow functions and CKE5 AFAIK not).

**Comment by Reinmar** [comment]
Thanks, it'll speed up the setup. And we have to standardise our use of arrow functions as well. This will be a good moment.

**Comment by Reinmar** [comment]
We introduced our own config: https://www.npmjs.com/package/eslint-config-ckeditor5

I'm quite happy with ESLint because it throws on many issues which JSCS and JSHint missed. However, many of its rule are too pedantic and lack flexibility. I needed to disable a couple of interesting ones because they made us write worse code ;|.

**Comment by Reinmar** [comment]
ESLint up and running in all packages. Bye bye JSHint and JSCS.
