### ISSUE TITLE
CI uses wrong version of Chrome

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#369]
The current Travis configuration includes installation of the newest stable Chrome version. However due to this line:

```yaml
- export CHROME_BIN=chromium-browser
```

Travis uses the preinstalled Chromium browser, which is noticeably older than the current Chrome (51 vs 54). After removing this line, CI should use the right version of Chrome (karma searches for executable on its own).

**Comment by Reinmar** [comment]
Not sure if this changes anything but we have this:

```js
		if ( process.env.TRAVIS ) {
			karmaConfig.browsers = [ 'CHROME_TRAVIS_CI' ];
		}
```

cc @pomek

**Comment by pomek** [comment]
This ticket is about [removing](https://github.com/BEMQuery/bemquery/blob/master/.travis.yml#L15-L17) the 

```diff
- export CHROME_BIN=chromium-browser
```

from `.travis.yml`.

As @Comandeer said, CI will use the latest Chrome (not preinstalled Chromium). It is okay.

OTOH, it isn't a bug. We use older Chrome and everything works ok. We can upgrade Chrome and it most probably everything will still work, so it looks like "enhancement", not a "bug".

**Comment by Reinmar** [comment]
It's a bug, cause we thought we used the latest Chrome ;)

**Comment by pomek** [comment]
https://travis-ci.org/ckeditor/ckeditor5-autoformat/builds/179758006#L1340

Chrome 54 works fine. Can I upgrade the `.travis.yml` in all repositories?

**Comment by Reinmar** [comment]
I guess so.

**Comment by pomek** [comment]
Done.

**Comment by Reinmar** [comment]
I'm not sure if this is related, but this is a second stalled build that I've seen in 24h: https://travis-ci.org/ckeditor/ckeditor5-engine/builds/180348237. It looks like the browser is hanging there.

**Comment by pomek** [comment]
I had the same situation yesterday - https://github.com/ckeditor/ckeditor5-dev-tests/issues/17

It looks like Karma cannot close the Chrome (or Karma doesn't know when Chrome has done its work).

**Comment by Reinmar** [comment]
Since it worked better with Chromium the question is whether it was a good change. Let's monitor the situation for now.
