### ISSUE TITLE
Remove DOM dependencies.

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#3717]
We should remove DOM dependencies from `HtmlDataProcessor` class in order to run it's code under Node.js. It uses `DOMParser` in `toDom` method and `innerHTML` in `toData` method (by using `BasicHtmlWriter`). 
`HtmlDataProcessor` is also used in view test utilities (`parse` and `setData` methods), so more and more tests will be dependent on this class.

Research about feasible solution will be needed - for example [jsdom](https://github.com/tmpvar/jsdom).

**Comment by Reinmar** [comment]
This is very old and very outdated :)
