### ISSUE TITLE
CKEditor's AMD compilation doesn't work with the default Require.js

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#373]
Unfortunately, we weren't able to load an AMD compilation of the editor with `Require.js`. It breaks as:

The reason of this issue is that we have a couple of circular dependencies in the code:

```
(master d6c67cc) p@m /www/ckeditor5/ckeditor5> madge --format=es6 --circular ./build/modules/esnext/ckeditor5/
ui/template -> ui/view
ui/view -> ui/viewcollection
engine/model/operation/removeoperation -> engine/model/operation/reinsertoperation
engine/model/delta/mergedelta -> engine/model/delta/splitdelta
engine/model/delta/unwrapdelta -> engine/model/delta/wrapdelta
```

All of them are reasonable and we'd need to make the code more complicated in order to remove these things. Also, all of them work fine with e.g. Webpack or Rollup.

Unfortunately, when transpiling the code to AMD Babel cares more about interoperability with other module systems than about making circular dependencies work (and they are designed to work in ES6 modules). I reported the issue to Babel (https://github.com/babel/babel/issues/3917), but I don't think that a patch would be accepted because it was a design choice to favor interoperability (and the issue only occures with Require.js). 

Hence, in the past, I had to fork Require.js (https://github.com/Reinmar/requirejs) and worked around this issue: https://github.com/Reinmar/requirejs/commit/d05953735f9e93887b74f92b68d522301fef363e

So, if anyone wants to load CKEditor using Require.js, then it's only possible using https://github.com/Reinmar/requirejs/blob/master/require.js. Also, since I don't think we'll care to remove those circular dependencies, the AMD modular compilation (not talking about possible AMD bundles) will not be suitable for more advanced use, I'm afraid.

**Comment by fredck** [comment]
Auch! This may end up being an important issue.

Ofc, requiring a custom Require.js to make it work is not a solution.

Can we create, especially for AMD, a safe replacement for the involved classes so they load without the circular dependency. Let me try to bring an example:

```
ClassA -> ClassB
ClassB -> ClassA

// We know that this circular dependency exists and that loading
// them in the [ ClassA, ClassB ] order is fine. 
// For that purpose, we introduce "ClassB_AMD_Proxy":

ClassA -> ClassB_AMD_Proxy
ClassB_AMD_Proxy (no dependecies)
ClassB -> ClassA

ClassB_AMD_Proxy is a proxy/copy of ClassB but requires("ClassB") inside every method during "runtime", not on module loading.
```

I'm not sure if I'm clear, if this works or if this is doable... it's just a suggestion that may give you guys some ideas.

**Comment by Reinmar** [comment]
TBH, I'm not sure if this is a big problem. I think that in AMD world either you use a bundle... or nothing. The AMD platform doesn't support many building scenarios and, AFAICT, all libraries shipping AMD versions provide ready to use bundles, not source node.

For instance, remember that we haven't found a good solution to how load source AMD version of CKEditor using reasonable paths... because the platform doesn't support such situations. It only support simple name => path maps.

So, since ckeditor5-dev-bundler-rollup can produce an AMD bundle, then CKEditor can be used in an AMD-based project. It just won't be possible to use modular version of CKEditor, which shouldn't be a big surprise for the developers using AMD.

**Comment by Reinmar** [comment]
We should rather work on optimising Webpack/Browserify and general experience rather than hacking through AMD, which, as we've learnt very well in the past, was a total nightmare.

**Comment by fredck** [comment]
> So, since ckeditor5-dev-bundler-rollup can produce an AMD bundle, then CKEditor can be used in an AMD-based project. It just won't be possible to use modular version of CKEditor

Ok, now the issue is clearer. I thought we weren't able to produce an AMD bundle at all! So nothing to do here for now, really. We should be fine.

**Comment by Reinmar** [comment]
I presume that this issue will appear in Google in the future if developers will be looking for AMD version of CKEditor, so a small update.

We dropped the compilation step (https://github.com/ckeditor/ckeditor5/issues/362), so now the raw source code (ES6 modules) needs to be bundled before loading it into the browser. If you configure Webpack or Rollup to produce an AMD output everything will work fine.

The issue we had previously was only applying to loading non-bundled AMD-based source code of CKEditor which didn't work with a default Require.JS. Since this isn't a reasonable environment anyway (due to the number of files), we don't consider this a real issue.
