### ISSUE TITLE
CKEDITOR on iphone

### ISSUE THREAD

**Issue by fkroockmann** [ckeditor/ckeditor5#377]
Hi,

I have a problem with CKEDITOR with inline mode on Iphone 6 plus, when i begin to edit my content, the toolbar disappear cause of safari deactivate all fixed element.

Any suggest ?

**Comment by Reinmar** [comment]
Hi,

Sorry to hear that. Safari on iOS has a very flawed viewport model (see https://github.com/ckeditor/ckeditor5-design/issues/149) which causes a lot of issues. We're investigating how to deal with that in CKEditor 5.

However, I think that you asked about CKEditor 4 which has its own issue tracker on http://dev.ckeditor.com. I'm closing this ticket as invalid, but if you were asking about CKEditor 5, we can open it. If not, then please open a ticket on http://dev.ckeditor.com (although, I must say that fixing this issue would be super hard).
