### ISSUE TITLE
 In Microsoft Edge the system stops me from entering a new line. I start a new line and it instantly deletes it.

### ISSUE THREAD

**Issue by yubitib** [ckeditor/ckeditor5#380]
On the edit issue page I am seeing the following annoying behavior when using Microsoft Edge

I type text on the first line of the description and hit the Enter key. I can see the cursor jump to the next line and then instantly jump back. I can workaround the issue by typing a ":", but this is always put on a new line even when I do not want it to.

**Comment by Reinmar** [comment]
Hi, thanks for the report. We didn't work on Edge support yet. We're planning to deal with this in Q1 next year. This is the ticket to track: https://github.com/ckeditor/ckeditor5/issues/201.

**Comment by Reinmar** [comment]
Just for clarity – cause I see that you also reported https://github.com/ckeditor/ckeditor-docs/issues/80, did you mean to report an issue for CKEditor 4 or 5?

**Comment by Reinmar** [comment]
Let's follow all the Edge issues in https://github.com/ckeditor/ckeditor5/issues/423. Especially that it wasn't confirmed by @yubitib that this particular bug applies to CKE5.
