### ISSUE TITLE
There should be error when there is no converter to the model element

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#3818]
Each model element should have a converter. There should an error or warning when there is no converter to the model element. Now nothing happens, you do not get the element in the view, and get an error, at some point later when you add another element. Error or warning should appear immediately when you add that element to the model.

**Comment by Reinmar** [comment]
Related ticket: #6538.

**Comment by Reinmar** [comment]
This will be resolved in #10377.
