### ISSUE TITLE
Various algorithms should scroll the viewport to the selection

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3870]
1. Paste, press enter multiple time, etc.
2. The caret goes off screen and you stop seeing it.

The viewport should automatically be scrolled to show that position.

**Comment by APegram** [comment]
@Reinmar I know this issue has been closed; however, I was curious if there was a way to disable the scrollTo cursor method. I have users that are working with large documents and are referencing higher up in the text editor, but when they type it will auto-scroll to the caret. It appears to do this on more than what I see described; IE - typing anything does this.

Thanks!
