### ISSUE TITLE
CkEditor Cannot set property 'dir' of undefined

### ISSUE THREAD

**Issue by Hopp123** [ckeditor/ckeditor5#391]
favorite
I want to use CKEditor.

I have currently install ckeditor using npm

So it is installed in node_modules folder

My folder structure is like

app --> index.js

node_modules -->ckeditor -->...
and I have require it in index.js

also set veriable

 var CKEDITOR_BASEPATH = '../node_modules/ckeditor'
still getting the dir error

**Comment by Reinmar** [comment]
I'm sorry, but I think that you've mistaken CKEditor 4 and CKEditor 5. This repository is for CKEditor 5 and you're apparently experiencing a problem with CKEditor 4.

I'll close this ticket. You can look for help in:

* http://dev.ckeditor.com – CKEditor 4's issue tracker. However, I don't think that you have a problem with a bug, but rather with how to install CKEditor.
* https://stackoverflow.com – here you can look for help with integrating CKEditor.
