### ISSUE TITLE
Tool for checking out a history state

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#392]
In order to use e.g. `git bisect` command, we need to have a tool which allows checking out to particular history state.

We can use git hook (push). Each repository (including the ckeditor5) after pushing the changes (to `master` branch only), will use a hook. The hook will send a request to our server.

The server should do:

1. Update the main repo (`git pull # in ckeditor5`),
2. Update the packages (`mgit pull`). **Important thing:** Update process has to get changes from `master` branch in each package,
3. Run the tool which collect hashes from all packages,
4. Save collected hashes in `mgit.json`,
5. Commit changed `mgit.json` and push to remote. Do we want to skip CI for this commit?

Mgit is a CLI tool but it can be also used as a module in the code:

```js
const mgit = require( 'mgit2/lib/index' );

mgit( commands, options )
.then( () => {
  // Mgit finished.
} );
```

WDYT?

**Comment by pomek** [comment]
Script for collecting hashes is already done - https://github.com/ckeditor/ckeditor5-dev/pull/54

Now we need to turn on it. It requires an update `.travis.yml` in each package.

**Comment by pomek** [comment]
We changed a way to deliver this ticket. We will use CI for it.

I pasted below what @Reinmar posted a long time ago:

>On successful build in `ckeditor5-*#master`:
>
>1. Clone `ckeditor5`,
>2. Update `mgit.json`, do that by:
>    * switching to `master` (future – to the same branch on which `ckeditor5-*` is – e.g. `major`),
>    * `mgit bootstrap`,
>    * change `mgit.json`,
>    * commit all changes to `<branch>-revisions`.
>
>    Such a workflow will ensure that `<branch>-revisions` branch will always contain the same files >as `master` or `major`, but with a modified `mgit.json`.
>
>3. Push (we need to do that using HTTPS (password), to do that via SSH we might need a paid Travis accounts - TODO),

**Comment by Reinmar** [comment]
I need to answer some auth questions and we are ready to go. Thanks, @pomek!

**Comment by Reinmar** [comment]
It's up and running. See https://github.com/ckeditor/ckeditor5/tree/master-revisions
