### ISSUE TITLE
Operational Transform Server-Side Example?

### ISSUE THREAD

**Issue by benjismith** [ckeditor/ckeditor5#3942]
When ckeditor5 is released, I'll be integrating it in a realtime collaborative writing environment, so I'm very interested in the mechanics of the operational transform implementation.

Do you have any design docs, or a simple prototype, showing how to implement the server-side of the OT system?

**Comment by YaoKaiLun** [comment]
If I have to implement collaboration by myself，I will be very pressed for implementing the operational transformation. I will be really appreciate if there have any docuements or examples for it [Worship].
