### ISSUE TITLE
Define presets

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#399]
In CKEditor 4 presets were defining the entire editor setup, together with its default config (https://github.com/ckeditor/ckeditor-presets).

In CKEditor 5 this job will be done by specific builds.

In CKEditor 5 I see presets differently. They will be sets of features. This means that you'll be able to compose your editor builds out of smaller sets of features, without the need to first install (via npm) and then import (in JS) all of them.

In terms of the code, a preset will simply be a plugin which requires other plugins. Presets will be kept in `ckeditor5-presets` repository (just one! :D):

```
ckeditor5-presets/
  src/
    textbox.js
    standard-article.js
    editing-improvements.js
    ...
```

The textbox preset may e.g. require: `Typing`, `Undo`, `Enter`, `Clipboard`. It will give you a textarea-like experience.

The standard-article may require e.g. the textbox preset plus `Paragraph`, `Heading`, `List`, `Image`,  `Bold`, `Italic`, `Link` etc.

The editing-improvements may require e.g. `Auforomat` and `TextTransformations` plugins.

**Comment by Reinmar** [comment]
Usage (before):

```
npm i --save @ckeditor/ckeditor5-editor-classic
npm i --save @ckeditor/ckeditor5-typing @ckeditor/ckeditor5-undo ...
npm i --save @ckeditor/ckeditor5-paragraph @ckeditor/ckeditor5-heading ...
npm i --save @ckeditor/ckeditor5-autoformat ...
```

```js
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Typing from '@ckeditor/ckeditor5-typing/src/typing';
import Undo from '@ckeditor/ckeditor5-undo/src/undo';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';

ClassicEditor.create( { 
  plugins: [
    Typing, Undo, Paragraph, Autoformat, ...
  ]
} );
```

Usage (with presets):

```
npm i --save @ckeditor/ckeditor5-editor-classic
npm i --save @ckeditor/ckeditor5-presets
```

```js
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import StandardArticlePreset from '@ckeditor/ckeditor5-presets/src/standard-article';
import EditingImprovementsPreset from '@ckeditor/ckeditor5-presets/src/editing-improvements';

ClassicEditor.create( { 
  plugins: [
    StandardArticlePreset, EditingImprovementsPreset
  ]
} );
```

**Comment by Reinmar** [comment]
Hm... the only problem with a single repo for all presets is that it will be always release, whenever any other package is released. But so will ckeditor5 itself, so perhaps that's ok.

**Comment by scofalik** [comment]
Is there any point in having presets come with some kind of default configuration? Maybe some plugins will have some configuration options that will change look or behaviour of a plugin.

**Comment by Reinmar** [comment]
> Is there any point in having presets come with some kind of default configuration? Maybe some plugins will have some configuration options that will change look or behaviour of a plugin.
> 
> The configuration maybe could be exported in additional variable and might be modified before being used in editor constructor.

I've been thinking about this. Generally, we want as few config options as possible, but we won't avoid some. E.g., the one with which we're currently dealing is the toolbar configuration.

Now, we have 3 options (in this particular case):

1. Do nothing. The developer will have to configure the toolbar and presets are not going to help with that. This is fine (at least at the current stage) and makes things easy.
2. We can let the presets define some configurations – e.g. at least push buttons to the default toolbar config. Since a preset is a plugin, that will be trivial, no magic needed. 

  Actually, we do a similar thing in the image feature already. In order to not require configuring its toolbar every time, there are two config properties. `config.image.defaultToolbar` and `config.image.toolbar`. If the latter is defined, it's used. If not, then the first is used. And this allows the features to push their buttons to that option. Unfortunately, it also proves that our `Config` object is far from perfect, because we can define default options... but they can't be arrays and multiple features can't play with them. Though, this is solvable.
3. We can implement a similar mechanism like in CKE4 where features would define in which toolbar group it should be displayed and with what priority. This was able to do magic, but it's complicated and fails miserably when number of buttons vary heavily. E.g. the default config is to have 3 rows of buttons, so if you strip half of the features, you're left with just a few buttons in each row. OTOH, CKE5's toolbars will be much simpler, so perhaps this could work better here.

Anyway, the whole topic of presetting some options boils down to 3 things – let's have as few options as possible, let's have sensible defaults, let's not overcomplicate it prematurely.

**Comment by scofalik** [comment]
My point is... if this is just plugins loading plugins... I mean it helps and it makes it easier and quicker to start using CKE5, cause user don't have to think "Oh, which plugins do I need to have usable editor? Have I missed something important?". But OTOH, it is very small improvement over what we have now.

That's why I asked. If there is anything more that user have to configure, maybe go harded in that direction and help user in that regard too.

**Comment by Reinmar** [comment]
> But OTOH, it is very small improvement over what we have now.

I think that this is a quite significant improvement. Forgetting about some plugins even in CKE4 was a pretty big issue because it's usually very hard to understand why the editor isn't working. Plus, if we'll simplify installation of the base 10 plugins, then it'll be very useful for us (in e.g. manual tests), will look good in the docs, etc. All those things matter.

But I certainly agree that if we could do more, we should. That's why I mentioned the toolbar configuration which is another thing which can be done better. Fortunately, we can progressively enhance this situation and presets proposed in this way (as plugins) will definitely not block such progress.

**Comment by Reinmar** [comment]
If you're interested in how all this will look – I introduced first two presets in https://github.com/ckeditor/ckeditor5-presets and I used them in https://github.com/ckeditor/ckeditor5-labs/tree/master/integrations/webpack-integration.

**Comment by Reinmar** [comment]
Handled in https://github.com/ckeditor/ckeditor5-presets/issues/2.
