### ISSUE TITLE
Define rules for documenting editor config options

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#403]
ATM we have just a couple config options (lang, toolbar, some concerning image, typing) but more and more are arriving. I haven't found any standardized documentation for these existing, except some mentions here in there in class/method docs.

If there's really no such thing, we must establish some standards, use them to clean–up existing configs and follow them when creating new ones. TBH, it's the most important knowledge for devs using our software, an entry–point to working with CKE.

**Comment by fredck** [comment]
There is a starting point, defined in the good days, long time ago:
https://github.com/ckeditor/ckeditor5-design/wiki/Configuration

Some of it may still apply. Some things may be missing.

**Comment by oleq** [comment]
These rules define how config properties should like etc. not how to document them in JSDoc. And that's what I'm missing now.

**Comment by Reinmar** [comment]
Totally agree – it's high time to think about that.

WDYT about defining a `module:core/editor/editor~EditorConfig` class to which other features will add properties? Just like in CKE4, iirc.

One thing which I'm unsure is how to document the deeper structure that we have now. There's e.g. `config.image.toolbar`. We'd need to check what JSDoc could handle. Perhaps this would be fine:

```
@member module:core/editor/editor~EditorConfig#image.toolbar
```

**Comment by oleq** [comment]
I'm fine with any pattern as long as it keeps all the things together somehow.

**Comment by Reinmar** [comment]
I defined the interface of the editor config in https://github.com/ckeditor/ckeditor5-core/commit/9974503 and started adding other packages' options. This turned out to be tricky due to nested config options like `heading.options` and `image.*`. I'm using more interfaces for that which even works fine because then we have starting points for all heading's and image's options.

**Comment by Reinmar** [comment]
![image](https://user-images.githubusercontent.com/156149/29207273-d6896688-7e85-11e7-9daa-9aa4bcbc845c.png)
