### ISSUE TITLE
CLA section of CONTRIBUTING file points to a non–existent URL

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#405]
See https://github.com/ckeditor/ckeditor5/blame/master/CONTRIBUTING.md#L69 –  http://ckeditor.com/cla is 404. 

As an OSS project, I think we should be very clear on this subject and provide any necessary information that developers might want to know. ATM, 404 does not build trust and doesn't look very professional either. The only public information we provide and I was able to find is https://dev.ckeditor.com/wiki/cla, which isn't up–to–date and not at all in the context of CKEditor 5.

**Comment by Reinmar** [comment]
The CLA signing system is under construction. The link is there since the very beginning (I noticed it only recently when updating the file). Let's not touch it and just make sure that it'll work once CLAs are on.
