### ISSUE TITLE
[Chrome] Impossible to create a new line

### ISSUE THREAD

**Issue by ssougnez** [ckeditor/ckeditor5#406]
I'm creating a test app for webpack. Here is my main JavaScript file:

```
import 'regenerator-runtime/runtime';

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classic';

import Enter from '@ckeditor/ckeditor5-enter/src/enter';
import Typing from '@ckeditor/ckeditor5-typing/src/typing';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Undo from '@ckeditor/ckeditor5-undo/src/undo';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Image from '@ckeditor/ckeditor5-image/src/image';

ClassicEditor.create(document.getElementById("editor"), {
    plugins: [ Enter, Typing, Paragraph, Undo, Bold, Italic, Image ],
    toolbar: [ 'bold', 'italic', 'undo', 'redo' ]
});
```

I guess that the "Enter" plugin is supposed to handle new lines when the user presses "Enter" ? Although, when I press "Enter", nothing happens.

For the webpack configuration, I'm using a file very similar to this one: https://github.com/CKEditor5/ckeditor5.github.io/blob/master/webpack.config.js.

Sorry if I'm doing anything wrong, just started to play with this :-)

**Comment by Reinmar** [comment]
> I guess that the "Enter" plugin is supposed to handle new lines when the user presses "Enter" ? Although, when I press "Enter", nothing happens.

Do you load any data to the editor? I mean – right now there's no "autoparagraphing" yet, so if you loaded an empty content, there may be no paragraph AFAIR and enter will not work.

If not that, then another question – are you sure there are no errors thrown when you press enter?

**Comment by Reinmar** [comment]
That's the issue with autoparagraphing: https://github.com/ckeditor/ckeditor5/issues/331.

**Comment by ssougnez** [comment]
Hi,

I don't know if my answer is needed (as I think that #331 is the reason of my issue) but still... I confirm that I'm not loading any data in the editor, I just have an empty div and I do the "ClassicEditor.create". 

Thanks for your answer

**Comment by Reinmar** [comment]
OK, cool. So the workaround for you will be to always have some `<p></p>` in that `<div>` for now. But it's temporary, because we'll close #331 soon definitely.

**Comment by ssougnez** [comment]
Just tried that, worked very well, thanks a lot ;-)

**Comment by Reinmar** [comment]
This issue was fixed by https://github.com/ckeditor/ckeditor5/issues/331. Now, you can load empty data into the editor and paragraph will automatically be created if needed.
