### ISSUE TITLE
[Safari] Refreshing caret position is noticeable when playing with the placeholder

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#4078]
![jun-12-2017 13-48-43](https://user-images.githubusercontent.com/1057056/27033083-00260326-4f78-11e7-9ffa-e3da0dee9de2.gif)

But when start typing immediately after placing the selection then content appears in the right place.

---

If you'd like to see this fixed sooner, add a :+1: reaction to this post.

**Comment by oleq** [comment]
This should be resolved by #8689.

**Comment by oleq** [comment]
Closed in #8689.
