### ISSUE TITLE
Running task on all subrepositories

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#41]
In #36 we are discussing how to run some common task on all subrepositories. For example, we need to  change the years in the copyright header. We could run a task directly from the `ckeditor5` repo on each of its subrepositories, but this means that this task would need to know everything about its subrepositories (e.g. which files are ignored). This knowledge of course is discoverable, but it would make more sense if subrepositories were running the task themselves.

The idea that we have is that subrepositories will have a grunt task (or some other API) which will accept a path to a file with a task source and name of that task. This way the main repo will be able to run one of its tasks in all subrepos. The task's code will be kept in the main repo, but the task will be run directly in subrepos, so the logic on which files it should be run will be local.

**Comment by Reinmar** [comment]
The idea is to implement a gulp task called e.g. `exec`.

```
dev/tasks/exec/
  tasks.js
  functions/
    package.json // Dependencies of existing functions.
    bump-year.js
```

Usage (with param):

```
gulp exec bump-year 2017
```

Contents of `bump-year.js`:

```js
'use strict';

/** 
 * {String} packagePath
 * {Minimatch} params
 */
module.exports = ( packagePath, params ) => {
};
```

**Comment by Reinmar** [comment]
First use case that we have for this task is https://github.com/ckeditor/ckeditor5/issues/149. But there are obvious other ones like bumping year, dependencies in package.json, updating JSCS rules, etc.

**Comment by Reinmar** [comment]
I've just thought that we could make `gulp status` and `gulp update` aliases for `gulp exec status` and `gulp exec update`, but that would mean that all their deps need to be kept in the main `package.json` so it would create a bit confusing situation. Hence, it's better to not move them and keep `exec` for special occasions only.

**Comment by maxbarnas** [comment]
What has been determined so far:
- tasks inside `ckeditor5` repository will have all the knowledge about files that have to be processed
- script should obey rules in `.gitignore` files in each repository (and possibly other configuration files of this kind)
