### ISSUE TITLE
Introduce the "Essentials" plugin

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#411]
While it is easy for developers to decide whether the "Heading" or "Link" features need to be included or not on their editor setup, there is a set of features which are expected to be in every editor. Currently, we're talking about Clipboard, Enter, Typing and Undo. Actually, the editor may not even work reliably without them.

When a developer will be designing their editor, it will be easy to miss one of these essential features and have a hard time to understand why things are not working.

Additionally, we may introduce in the future a few more essential features, for example, to handle backspace or whatever. It would be hard for developers to stay informed and keep their setups always updated.

I would like to propose two possible options for solving this problem:

 1. Introduce the "Essentials" plugin, which basically includes all such features.
 2. or... having such features automatically added to all builds by the builder.

With "2" we can be sure that one will never miss the essentials, while "1" makes it more explicitly.

This is a follow-up of https://github.com/ckeditor/ckeditor5-presets/issues/1.

**Comment by szymonkups** [comment]
I like idea of "Essentials" plugins, it gives us the flexibility to extend the list of essential features, and does not involve any builder logic to add features not specified by the user.
On the other hand maybe the builder could just inform about missing plugins in specified configuration, so that the user will be forced to create a valid config.

**Comment by Reinmar** [comment]
This is duplicating presets' functionality. There's already `presets/textbox` (which can be called `presets/essentials` if we find this name more adequate).

Please remember that such a feature will depend on the "essential" packages, so it's best if it's in a separate package... like `ckeditor5-presets`.

**Comment by fredck** [comment]
You want to solve other problems with presets and its purpose is still very unclear, IMHO. Anyway, this could have been discussed in ckeditor/ckeditor5-presets#1, not here. In any case, the Essentials plugin doesn't block nor duplicates the presets idea and it could be used inside the presets.

Here, I'm bringing a clear problem and proposing a clear solution. And yes, it should be a separate package called `ckedtor5-essentials` with the `Essentials` plugin inside.

**Comment by fredck** [comment]
> I like idea of "Essentials" plugin

I like this idea the most, as well.

**Comment by Reinmar** [comment]
This is done already: ckeditor/ckeditor5-essentials.
