### ISSUE TITLE
Should this package be published as ckeditor5 or @ckeditor/ckeditor5?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#412]
All the deps are scoped, but it somehow seems natural for the main package to not be scoped (for better visibility). WDYT?

**Comment by fredck** [comment]
Very good question... no easy answer though :/

This package will be always used together with other scoped packages. Maybe to avoid WTFs or confusion it's better to have it scoped as well?

**Comment by fredck** [comment]
Having `ckedito5` as an "alias" (copy) to `@ckeditor/ckeditor5` is bad, right? Or good?

**Comment by pomek** [comment]
+1 for scoped packages, because I guess I'm not be able to remove `ckeditor5` from npm :/

**Comment by Reinmar** [comment]
> +1 for scoped packages, because I guess I'm not be able to remove ckeditor5 from npm :/

That's a wrong way of thinking. We need to remove it anyway and it must not affect the answer to this question.

**Comment by Reinmar** [comment]
BTW, let me note one thing here – what's inside this repo will be used very rarely. In fact... I'm not sure whether we need this package at all. It may be useful if it can be installed through npm (instead of being cloned), but still, the audience is rather small – it's us, the developers (and other developers interested in the whole env – mainly those making PRs). 

In other words, the ckeditor5 package and repository has no value for people who want to integrate CKEditor 5 with their apps. Perpahs this will make the answer simple.

**Comment by Reinmar** [comment]
> Having ckedito5 as an "alias" (copy) to @ckeditor/ckeditor5 is bad, right? Or good?

Dunno... But for me it would be a bit strange. Perhaps we can simply push some proper README under "ckeditor5" which will direct people to "@ckeditor/ckeditor5" if necessary. Actually, this may be really useful because at this point we can already channel the developers to two targets – integrations (so e.g. builds) and framework (so e.g. ckeditor5 repo).

**Comment by fredck** [comment]
For sure we cannot remove any of these packages later on, so better to have a definitive solution right now.

What if we start with `ckeditor5` only and then see if it really causes confusion. Going with less in the beginning is possible and we can introduce `@ckeditor/ckeditor5` at any moment later on.

**Comment by Reinmar** [comment]
I generally agree – I'm actually less worried now about the confusion that this specific package is not scoped.

What worries me now, when I think more about this, is that the content of ckeditor5 is not what people would expect. 99% of people out there will want to use CKEditor by installing this package. And since ckeditor5's README will need to be cluttered with the dev stuff it will be hard to point people to the correct place.

Therefore, it may be useful to actually release something totally focused on documentation as "ckeditor5". And, in fact, I'd wait with publishing the real content of the ckeditor5 repository somewhere until we see that this would be useful for someone.

**Comment by Reinmar** [comment]
We went with [`ckeditor5`](https://www.npmjs.com/package/ckeditor5). Someone had to use it anyway.
