### ISSUE TITLE
Test Lerna with concurrency=1

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#431]
We've got some issues with Lerna's `bootstrap` command: https://github.com/ckeditor/ckeditor5/pull/428#issuecomment-297495570

They seem to be caused by concurrent `npm i`. Since we've been running to some random but similar problems since we started using Lerna, I think that most of them might be caused by concurrency.

So, let's see what concurrency=1 changes and whether it can be configured in `lerna.json`.

**Comment by Reinmar** [comment]
OK, it's impossible to set concurrency in `lerna.json` so we can't turn it off globally. But we can test if it slows down installation on Travis.

**Comment by Reinmar** [comment]
Let's see the stats: https://travis-ci.org/ckeditor/ckeditor5/builds/226295529.

The previous `lerna bootrap` with concurrency=4 (on master) took 144s: https://travis-ci.org/ckeditor/ckeditor5/builds/225186414#L1372

**Comment by Reinmar** [comment]
I have a bad luck...

First, Travis didn't capture any logs... and now, suddenly, a new version of Lerna was released :D

**Comment by Reinmar** [comment]
With concurrency=1: 174s (https://travis-ci.org/ckeditor/ckeditor5/builds/226295529#L1372)

**Comment by Reinmar** [comment]
With concurrency=4: 143s (https://travis-ci.org/ckeditor/ckeditor5/builds/225186414#L1372)

**Comment by Reinmar** [comment]
Builds fail very often recently due to Lerna's concurrency issues, so I disabled it in `.travis.yml` (e2b0b38).

**Comment by ma2ciek** [comment]
Lerna is also used here: https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-tests/bin/install-dependencies.sh#L16.

**Comment by Reinmar** [comment]
I know, but I haven't seen package builds failing yet. Or at least I don't remember.

**Comment by Reinmar** [comment]
We started using concurrency=1 all around to avoid issues and it really helps, so since https://github.com/lerna/lerna/pull/844 enables configuring all options in `lerna.json` I'll add it to the two we have (here and in ckeditor5-dev).  I'll also have to change the script which creates `learna.json` on CI (located in ckeditor5-dev-tests) and I'll be able to remove the param from `.travis.yml` in this repo.
