### ISSUE TITLE
[Edge] Selection does not move to the next block when in a paragraph inside a block quote

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#4342]
1. http://localhost/cke5/_/build/docs/ckeditor5/1.0.0-beta.2/examples/builds/classic-editor.html
2. Set data and selection `<blockquote><p>[]foo</p></blockquote><p>bar</p>`.
3. Press arrow right a couple of times to move to the next paragraph.

**Expected**:

It works! I'm down there!

**Actual**:

Stuck at the end of the block quote.

![kapture 2018-04-19 at 10 38 26](https://user-images.githubusercontent.com/1099479/38980744-eeb34d7a-43bd-11e8-8080-ca190d02b458.gif)

Edge 16.16299 

cc @Mgsy

**Comment by FilipTokarski** [comment]
Checked it once again and the bug seems to be gone now, shoud be closed.
