### ISSUE TITLE
How to remove <p> and </p> in Ckeditor5?

### ISSUE THREAD

**Issue by sunfeng90** [ckeditor/ckeditor5#4381]
When I use `window.editor.getData()` to get the data I have insert, but I commit got the content with `<p>`. How to remove the `<p>` and `<image>`.

**Comment by leooangeloo** [comment]
> I fixed this problem in following way: `export function ckEditorRemoveTags (data) { return data .replace('<p>', '') .replace('</p>', '') .replace('<figure class="image">', ',') .replace('<img src="', '') .replace('"></figure>', '') }`.But when I edit the content, I cannot show the image.I only show the url.For example `2332323232323223,https://upload.jdcf88.com/test/2018/7/25/15325318644189.png`

Could you provide more detail as to how you solved this issue of getting rid of the HTML tags?
