### ISSUE TITLE
Switch headings using dropdown causing unexpected behaviour in Chrome

### ISSUE THREAD

**Issue by fe-artisan** [ckeditor/ckeditor5#440]
I am using windows 10 with chrome 58.0.3029.110 (64-bit). When clicked on the dropdown item to switch headings, the caret was affected by the click event, causing the target selected block changed unexpected, then the heading command was applying to the wrong text block.

I searched a lot on the web, it seems to be a bug of chrome, as this [link](http://stackoverflow.com/questions/34354085/clicking-outside-a-contenteditable-div-stills-give-focus-to-it) reveals:

they're doing this:

```
on click:
  find nearest text node;
  if text node is editable:
    add insertion point;
```

...when they should be doing this:

```
on click:
  if clicked element is editable:
    find nearest text node;
    add insertion point;
```

**Comment by Reinmar** [comment]
Thanks for the ticket! We're aware of this issue and plan to implement some workaround soon.

I'm closing this ticket as a DUP of https://github.com/ckeditor/ckeditor5-ui/issues/228.
