### ISSUE TITLE
Removing empty paragraph is merging and is bad UX

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#4434]
![oct-01-2018 10-57-22](https://user-images.githubusercontent.com/1502228/46279218-cceaa300-c568-11e8-94c7-b23dfcba0e9f.gif)

As you can see, there is an empty paragraph, and then there is a heading below it. Then, a user removes the empty paragraph. But under the hood, this is realized as a merge. So the heading is merged into an empty paragraph and the header becomes a paragraph.

AFAIR, I requested this "action" to be a merge because of collaboration :D. So when one user types in an empty paragraph and the other clicks <kbd>Backspace</kbd> in it, the text that was written by the first user is not deleted.

However, outside of a collaboration, it looks really bad. We should do something about it. It looks like a bug.

**Comment by niegowski** [comment]
Issue #6680 is addressing this (and is aware of OT and "right merge").
