### ISSUE TITLE
Verify API docs on CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#444]
We have API docs validation thanks to our `@ckeditor/jsdoc-plugins` package. Now, it'd be a time to enable this on CI. Realistically, we can only do this in this repo, as a post-integration check.

**Comment by pomek** [comment]
I prepared some prototype how it could work. You need to check out following branches:

- [`ckeditor5#t/444`](https://github.com/ckeditor/ckeditor5/tree/t/444),
- [`ckeditor5-dev#t/ckeditor5/444`](https://github.com/ckeditor/ckeditor5-dev/tree/t/ckeditor5/444).

Command `gulp docs:api-json` works as it worked. If validation does not pass, nothing will happen. Documentation will build.

Command `gulp docs:api-json --validate` does not build the documentation. It validates whether the JSDoc is correct. If so, nothing will happen. Other case errors will be displayed and JSDoc will finish with `error code = 1` (for Gulp).

I didn't add the last task to `.travis.yml`.

**Comment by Reinmar** [comment]
I'm not sure what does this line do: https://github.com/ckeditor/ckeditor5-dev/compare/t/ckeditor5/444#diff-d9ba2abf4483c7964be2611fb7a2fb73R54

But the rest looks fine (I didn't test it though). Please make PRs so we can finalize this.

**Comment by Reinmar** [comment]
BTW, good idea to configure this through env variables :D Best option in this nightmare.

**Comment by pomek** [comment]
> I'm not sure what does this line do:

It breaks the JSDoc and set the proper error code.

**Comment by Reinmar** [comment]
Ahh... Sorry, I didn't see that it's indented. I thought it's straight in the module definition.
