### ISSUE TITLE
List nesting is disabled after undoing block quote transformation

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#445]
## Steps to reproduce
1. Make an ordered list with 2 items.
2. Place a cursor on second item and press "TAB" to create a nested list.
3. Place a cursor on first item and transform it into quote block.
4. Undo changes with CTRL + Z.
5. Try to repeat step 2.

## Current result
There is no possibility to make a nested list.

## Expected result
List should transform into nested list after pressing "TAB" key.

## Notes
Bug is reproducable only if you use "undo". When you remove quote block by clicking a button, list nesting isn't blocked.

## Other informations
OS: Windows 10, Ubuntu 16.04
Browsers: Chrome, Chromium, Firefox, Edge, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
I can confirm this. I also noticed that the result of step 4 is incorrect – undoing applying a blockquote should leave us with a nested list item, not a flat list.

![jun-21-2017 22-06-26](https://user-images.githubusercontent.com/156149/27404382-151aa644-56ce-11e7-8e5c-754aa9039d38.gif)

**Comment by Reinmar** [comment]
This may be something between change conversion, undo and list's postfixer.

**Comment by Reinmar** [comment]
This is a problem with conversion again because `editor.getData()` returns a nested list item after undoing applying block quote. So the model is OK, just the view is bad. See https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-315124980 and the following comment. This is not a problem which we'll be able to fix now.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore. The result of step 4 is correct - the nested list is restored and we are able to outdent/indent the item.

![bug_cke5](https://user-images.githubusercontent.com/20988892/36199401-cb884a24-1179-11e8-9c14-cfbec3a6e0c2.gif)
