### ISSUE TITLE
Editor crashes after undoing changes related to block quotes in nested list

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#446]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/ and don't delete editor's content.
2. Create an ordered list and type some text.
3. Press enter, type some text and press TAB to create a nested list.
4. Repeat step 3 10 times without pressing TAB (you should have 10 nested items).
5. Transform nested items number 10 (last one), 1 (first one) and 5 (middle one) into quote block.
6. Press CTRL + Z 3 times to undo changes.
7. Put a cursor on nested item 6.
8. Click on a block quote button twice (to transform it into quote block and undo changes. **Important**: Don't use CTRL + Z).
9. Press CTRL + Z.

## Current result
- After doing step 8, list item is removed.
- After doing step 9, editor crashes.

## Logs
Logs from console - https://gist.github.com/Mgsy/82513d50078417e601146d0813ffc430

## Notes
This bug could be pretty hard to reproduce, so feel free to comment if you have problem with it.

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

**Comment by Reinmar** [comment]
May be related to https://github.com/ckeditor/ckeditor5/issues/445.

**Comment by Reinmar** [comment]
There are different issues now. E.g., the previously nested list items are not nested anymore after undo.

![jul-13-2017 18-04-06](https://user-images.githubusercontent.com/156149/28175857-bb66c630-67f5-11e7-8c7f-e289f5d069ee.gif)

So, we can't work on this bug anyway for now.

**Comment by Reinmar** [comment]
I'm not sure why I actually added this issue to any iteration. It's very hard to reproduce. Perhaps there weren't more important issues back then :D Let's reprioritise now.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore. https://github.com/ckeditor/ckeditor5/issues/446#issuecomment-315124528 was fixed as well.
