### ISSUE TITLE
Introduce RawElement (aka ShadowElement)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4469]
See this comment: https://github.com/ckeditor/ckeditor5-engine/issues/1643#issuecomment-456814970

~~The name `UIElement` is misleading because this element can also be used to e.g. output raw content to the data.~~

~~We also need to rename `createUIElement()` and perhaps some other helpers.~~

**Comment by jodator** [comment]
A simple use-case for `RawElement` - passing non-editable regions of the content: https://github.com/ckeditor/ckeditor5/issues/5566#issuecomment-542156007.

**Comment by Reinmar** [comment]
I stumbled upon this again. Similar case to what @jodator posted above.

**Comment by jodator** [comment]
Let's not forget about this fix: #1684.
