### ISSUE TITLE
Editor crashes after styling image as a paragraph

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#448]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/
2. Click on an image to make a selection.
3. Press ALT + F10 to focus a toolbar.
4. Press move down arrow to open styling tab.
5. Again press move down arrow to select paragraph styling.
6. Press Enter.

## Current result
Editor crashes.

## Expected result
There should not be any possibility to open styling menu while selecting an image.

## Log
Log - https://gist.github.com/Mgsy/f7ea8f1e3fa2eb3849ed813058a6a07e

## Other informations
OS: Windows 10
Release: 0.10.0

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Thanks, @Mgsy. The actual issue is in the ckeditor5-ui and I [migrated](https://github.com/ckeditor/ckeditor5-ui/issues/238) your report there so you can follow it if you wish to be notified about the status. It doesn't look like a very complex issue so hopefully, we're gonna address it soon.
