### ISSUE TITLE
Focus with ALT + F10 doesn't work on Ubuntu browsers

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#449]
## Steps to reproduce
1. Open your Ubuntu environment and go to https://ckeditor5.github.io/
2. Focus editor.
3. Press ALT + F10.

## Current result
There is a focus on a browser's "file" tab.

## Expected result
It should focus editor's toolbar.

## Other informations
OS: Ubuntu 16.04
Browsers: Chromium, Firefox
Release: 0.10.0

**Comment by Reinmar** [comment]
We use the same keystroke which CKE4 does. It's known to not work in Ubuntu because it opens the app menu there.

Since it's really hard to find a reliable keystroke, we simply allow the developers to bind different one to this action.
