### ISSUE TITLE
Improve performance of attribute removal

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#4504]
While working on remove formatting (ckeditor/ckeditor5-remove-format#7) we found that removing attributes from relatively simply code takes too much time.

![image](https://user-images.githubusercontent.com/5353898/55471333-c74e4280-5609-11e9-8958-33a27784b5f0.png)

For repro case see ckeditor/ckeditor5-remove-format#7.

**Comment by Reinmar** [comment]
Unfortunately, XXX does not resolve this issue completely. The performance is still fundamentally wrong.

I did some profiling and out of 8s that the whole thing takes, 3.3s are spent in `parseAttributes()` in the view element constructor. That'd be the first thing to check because we can gain the most here. But it'd still not be all.

Here are stats of view element constructor calls, split per element name. In the arrays I stored the `attributes` param of the constructor:

![image](https://user-images.githubusercontent.com/156149/69235889-b7807000-0b92-11ea-9de7-860a63e63994.png)

As you can see, in summary, the constructor is called 70k times 🤯 

👉  70.000 times 👈 

Most of the time, in this case, with `undefined` as `attributes`. Hence... perhaps we can add a condition for it.

**Comment by Reinmar** [comment]
> Most of the time, in this case, with `undefined` as `attributes`. Hence... perhaps we can add a condition for it.

Nope. The number of times we call this with `undefined` is actually around 500 compared to 70k with some empty map/object. We could still find ways to optimize this locally but I think that we should figure out why that many elements are created and whether we can prevent that.

**Comment by Reinmar** [comment]
I closed https://github.com/ckeditor/ckeditor5-image/pull/335 but I think we should keep this issue opened. I think that a reasonable time for this content is around 1s. So there's still 80% to go.

**Comment by Reinmar** [comment]
I extracted the image load observer to https://github.com/ckeditor/ckeditor5/issues/5766 and I'd remove this ticket from the iteration as there's more to do here.

**Comment by Reinmar** [comment]
I was testing loading a quite long content (50 pages) into the editor and I can also see the getRawTag there:

![image](https://user-images.githubusercontent.com/156149/69731137-9fc46100-1129-11ea-8738-277954f9ad9f.png)

Interesting if it would be possible to optimise that bit 🤔

**Comment by Reinmar** [comment]
In this case, there are 30k model nodes created, even though the final document has 3k nodes. Again, we're executing `toMap()` just too many times.

**Comment by Reinmar** [comment]
Okeydokey – I was able to take `toMap()`'s execution time from something around 20-30% of the total task's time to close to 0%. Details in https://github.com/ckeditor/ckeditor5/issues/5854.

However, we should still check if we can save some time here. Unfortunately, in both cases (remove format and data loading) this will not be a micro-optimization any more (unless someone knows how to shove some time off the `Position#parent` getter). This time we have to figure out:

* how to do fewer things (e.g. create fewer elements),
* how to not do some things at all.

**Comment by Reinmar** [comment]
Actually, I'm wrong, there's still more to do in here:

![image](https://user-images.githubusercontent.com/156149/69788711-61798100-11bf-11ea-98eb-3ce9c973d86f.png)

This is `parseAttributes()` from view element and it also does the `isPlainObject()` thing. We can change the condition there too.

**Comment by jodator** [comment]
@Reinmar would you mind creating a manual sample similar to the ones I've created for the memory leak tests?

- It might be just one editor build with some complex content to parse.
- to make tests easier it could initialize the editor on a button (to setup performance test in dev tools)
- it should have as many features (in the editor and in loaded content) to test in some full setup
- it could also load the same content to different setups (like current Classic and some with many features enabled) so one button will tests subset of features from the content the other would test all of them.

**Comment by Reinmar** [comment]
As I commented in https://github.com/ckeditor/ckeditor5/issues/2336#issuecomment-623907622. We reduced the time over 10x. NICE :)
