### ISSUE TITLE
Style attribute conversion does not work with attributeToAttribute()

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4517]
```js
		editor.model.schema.extend( 'tableCell', {
			allowAttributes: 'style'
		} );

		editor.conversion.attributeToAttribute( {
			model: {
				name: 'tableCell',
				key: 'style'
			},
			view: 'style'
		} );
```

![image](https://user-images.githubusercontent.com/156149/58405112-fd86cc00-8066-11e9-8099-c038ebb174f9.png)

------

If you'd like to see this bug fixed sooner, add 👍 to this post.

**Comment by usama-ayub** [comment]
i saw all above comments they all are help me but can i apply style attribute in 

- image tag
- link tag
- li tag

and secondly how can i apply nested elements like "<div><span>click</span></div>

**Comment by Mgsy** [comment]
A small note about this issue. I tried to add the conversion for `style` attribute in list items. I've used the solution from this ticket and finished with something like this:
```js
editor.model.schema.extend( 'listItem', {
        allowAttributes: 'listStyle'
} );

editor.conversion.for( 'upcast' ).attributeToAttribute( {
  model: {
       name: 'listItem',
       key: 'listStyle'
   },
   view: 'style'
 } );
editor.conversion.for( 'downcast' ).add( dispatcher => {
	dispatcher.on('attribute:listStyle:listItem', ( evt, data, conversionApi ) => {
		const viewElement = conversionApi.mapper.toViewElement( data.item );
		conversionApi.writer.setAttribute( 'style', data.attributeNewValue, viewElement );
	} );
}, { priority: 'highest' } );
```
However, it turned out that it doesn't work for `<li>` elements, while the same code works fine for paragraphs. So, I've modified the upcast conversion and added `value` property. After this change, `style` attribute on list items converts properly:
```js
editor.conversion.for( 'upcast' ).attributeToAttribute( {
    model: {
          name: 'listItem',
          key: 'listStyle'
     },
     view: {
         name: 'li',
         key: 'style',
         value: /[\s\S]+/
    }
} );
```

**Comment by dustinormond** [comment]
@josueexhume

Which file were you editing in your big block of code above? Is this before building the editor or do you do this in your page that creates the editor? I really want to implement this but am struggling where to put this.

**Comment by viz-eight7six** [comment]
Hello! any idea if this will get fixed? 

For some context, I am trying to apply inline styles for images and the workarounds listed in the comments have not been working.

Thanks!

**Comment by harleenarora** [comment]
Hello!

For some context, I am trying to apply inline styles for table and the workarounds listed in the comments have not been working.

Thanks!
