### ISSUE TITLE
Upcast converter for element:* gets data.modelRange == null 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4529]
When talking about upcasting, if you try to convert an element's attribute you need to listen to `element:*` event (there's no dedicated event for attribute conversion). Unfortunately, if you'd try this way:

```js
editor.conversion.for( 'upcast' ).add( dispatcher => {
	dispatcher.on( 'element:p', ( evt, data, conversionApi ) => {
		console.log( data.modelRange );
		console.log( Array.from( data.modelCursor.root.getChildren() ) );
	} );
} );
```

You can get `data.modelRange == null` and the model tree to which you convert (second `console.log()`) may not have the element that's being converted yet. In this specific case above this will happen if you add this converter before the `Paragraph` and `Heading` plugins are loaded. That's because in this scenario your listener will be executed before the `Paragraph`'s element converter.

The solution is simple and is actually what all our converters added e.g. with `attributeToAttribute()` do – they use `priority: 'low'`:

```js
editor.conversion.for( 'upcast' ).add( dispatcher => {
	dispatcher.on( 'element:p', ( evt, data, conversionApi ) => {
		console.log( data.modelRange );
		console.log( Array.from( data.modelCursor.root.getChildren() ) );
	}, { priority: 'low' } );
} );
```

This way, no matter how early you'll add your callback, it will always be executed after the default priority element converter from e.g. `Paragraph` feature.

The above needs to be documented.

**Comment by rshipp** [comment]
fyi, I tried to use `low` priority on an element->attribute dispatcher inside a listElement, and ran into the same exception - but using `lowest` worked. not sure if something changed here that caused that, or if it's specific to lists, or what.
