### ISSUE TITLE
Applying bold on nested list with empty item breaks a selection

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#453]
## Steps to reproduce
1. Load a sample with content.
2. In the middle of editor create an ordered list and type "test".
3. Press "Enter" to create second item, type "test" and press "TAB" to nest it.
4. Remove a text from the first item.
5. Start a selection from the first item (empty one) and drag it down a little bit below second item (it should select whole list and create a small blank space selection at the end of the second item).
6. Press CTRL + B couple times.

## Current result
Selection breaks.

## Expected result
Selection should remain unchanged.

## Screenshot
Here is a proper selection from step 5.
![screen](https://cloud.githubusercontent.com/assets/20988892/26554028/942ccba8-448e-11e7-8222-a3696553c553.png)

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

**Comment by Reinmar** [comment]
I think it's a DUP of https://github.com/ckeditor/ckeditor5-engine/issues/922.
