### ISSUE TITLE
Add support for shift+enter (soft line breaks)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4542]
We're not going to implement this in ckeditor/ckeditor5#4541 as it's not needed currently and we don't have line break support planned.

**Comment by indralekha** [comment]
how can i make the enter button behave in same way as Shift+enter (soft Break). I dont want line breaks, (on how enter key is working) but want it a soft break.
 Using ShiftEnter Plugin, could solve the prob but it is impacting Bulletlist, numbered list on enter, as it is taking shift+enter and not adding a bullet point after pressing enter.
