### ISSUE TITLE
Use a more standard 'directory/' notation in .gitignore

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#456]
Moved from https://github.com/ckeditor/ckeditor5-engine/issues/960.

**Comment by jodator** [comment]
As a comment to: https://github.com/ckeditor/ckeditor5-engine/issues/960#issuecomment-305739824.

I know that this might be tricky but anyway gulp task should add those `/**` if needed as `.gitignore` should be written using git standards.
