### ISSUE TITLE
Cannot select all content when widget is first/last element

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#4584]
When widget (for example image) is placed as first or last element in the editor we cannot select all contents.

Quoting @Reinmar

> This happens because the editor's content ends with a cE=false element. Blink's and Webkit's selection implementations are limited and don't allow placing one of the boundaries in such a place. So CTRL+A does nothing in such a case.  
> The most reasonable solution I can think of is handling CTRL+A manually and patching renderer so it creates space at the beginning/end of the editable so the boundary can be rooted there.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by melanke** [comment]
+1

**Comment by Reinmar** [comment]
Resolved in the upcoming release.
