### ISSUE TITLE
Implement keyboard navigation in widgets (focusing nested editables and cycling)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4603]
Currently, by coincidence, it's possible to get into nested editables using the tab key because browsers try to focus the next editable host.

In fact, the tab key should nearly always leave the editor (the only exception is list indentation). Therefore, we need a totally different keystroke for accessing and cycling through nested editables.

**Comment by mlewand** [comment]
Also there's an inconsistency in the default browser handling in that tha tab the selection in content _before_ the currently focused text, which is something unexpected.

As an example:

1.  Open https://ckeditor.com/docs/ckeditor5/20.0.0/features/image.html#image-captions
2.  In the "Image captions" section demo put the selection (caret) in the middle of `Image without caption:` paragraph.
3.  Press the <kbd>tab</kbd> key.

### Expected

Focus is either moved to the next focusable element after the editor or to the second widget.

### Actual

The focus is moved to the widget _before_ the caret.

**Comment by Reinmar** [comment]
Let's close this as a DUP of #6741.
