### ISSUE TITLE
Inserting widgets inside soft breaks makes the insertion in the wrong place

### ISSUE THREAD

**Issue by felipepar** [ckeditor/ckeditor5#4605]
When I insert a widget after some line breaks, (Shift + Enter), the widget is inserted at the correct position.

However, when I add the line breaks, then click on a previous line, and then insert the widget, it is inserted at the start of the paragraph.

I recorded a small video to try to show the behavior in the Demo page:

https://www.loom.com/share/71c3b9f0afcf4f5b9e66241b565fb93e

The problem apparently happens with any widget (I tested with tables and images).

**Comment by Reinmar** [comment]
Closed due to lack of activity.
