### ISSUE TITLE
EventInfo should be automatically added as event's first param

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#461]
When documenting events we only document the params which we pass to `fire()` which renders in our API docs like this:

![image](https://user-images.githubusercontent.com/156149/26879403-3d2657c0-4b91-11e7-9184-b509eb16682d.png)

However, if one would like to use that event, its first param would be `EventInfo` object.

In CKEditor 4 API docs we implemented a mechanism which automatically adds info about this object to all events. We need a similar thing for CKEditor 5.

**Comment by ma2ciek** [comment]
Docs after changes:
<img width="887" alt="screen shot 2017-08-16 at 12 45 52" src="https://user-images.githubusercontent.com/2768047/29360106-a6214f9c-8281-11e7-8392-1a545beb16a8.png">

**Comment by Reinmar** [comment]
Closed by https://github.com/ckeditor/ckeditor5-dev/issues/257.
