### ISSUE TITLE
Drag & drop removes styling from a word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#466]
## Steps to reproduce
1. Type some text, i.e. "Test".
2. Select it and apply bold with <kbd>CTRL</kbd> + <kbd>B</kbd>.
3. Create a new line.
4. Select the word from step 2.
5. Try to drag the word to the new line.

## Current result
Styling was removed from the word. 

## GIF
![bug](https://user-images.githubusercontent.com/20988892/26932838-08c24a1e-4c65-11e7-954d-f51fe8e2d591.gif)

## Other information
OS: Windows 10, MacOS X
Browsers: Chrome, Safari, Firefox, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
Merged into https://github.com/ckeditor/ckeditor5-clipboard/issues/23.
