### ISSUE TITLE
Customize keys to accept mention

### ISSUE THREAD

**Issue by felipegiotto** [ckeditor/ckeditor5#4665]
Currently, the plugin always select the current item when the user hit Enter, Tab or Space keys. My suggestion is to allow the user to customize these keys. For instance, I may want to disable the "Space key" shortcut, so if the user has the mention box opened and hit Space, the box closes and the editor keeps only the plain text, without mentions.

**Comment by zadam** [comment]
From my perspective the "space" issue is severely limiting usefulness of this plugin to only simple use cases - even the standard use case of mentioning somebody by name does not fully work since names contain space between first name and last name.

If having this configurable would take too much time then a quickfix could be considered of just allowing space (resp. not treating it as a "commit key") as a more sensible default.

**Comment by cnickless** [comment]
Not allowing a space to be written after the marker makes for a broken typing experience. It restricts users from being able to simply type marker characters (e.g. #, @) with a space following it.  Right now if I wanted to just type "#[space]" the first option will be selected.  If I delete those characters to go back to just the #, the feed is shown again.

To get past this, the user would have to either:

1. Type text after the tag, then use their mouse to select the cursor to the tag, delete the characters and then move the cursor back to the end of the string.
2. Type in sequence:  #[esc][space]

That's quite the unnatural behavior placed on the user.

I'd recommend just updating the default keys to select being ENTER and TAB, as those feel like the more specialized keys for this.

To test the ideal scenario -- type a comment on GitHub here down below ... type "#[Space]" and notice how the mention feed appears and then disappears.

**Comment by jaigupta10** [comment]
Any update on this one? Is it working and if so then how.

**Comment by zadam** [comment]
@jaigupta10 There's PR ckeditor/ckeditor5-mention#92 which fixes the space behavior but unfortunately it wasn't merged yet and has not activity :-(

**Comment by mlewand** [comment]
Note that this issue focuses on being able to customize the keys used for committing the mention.

@zadam @cnickless @neongreen your feature request is valid (ability for mentions to have a space) but that's [a separate issue dedicated to handling space in mention value](https://github.com/ckeditor/ckeditor5/issues/9741). Please add 👍 reaction there to show your support.

Unfortunately mentioned PR ckeditor/ckeditor5-mention#92 (which became #7306 after our repo migration) merely removed space from list of keys that accept a mention. While logic of mention (which were broken by spaces) remained unchanged.
