### ISSUE TITLE
[Chrome, Safari] Editor crashes after droping a whitespace on a paragraph

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#467]
## Steps to reproduce
1. Create two empty paragraphs.
2. Write some text in the second paragraph, i.e. "Test".
3. Click twice on the first paragraph to make a selection.
4. Drag selected whitespace to the second paragraph.

## Current result
Editor crashes.

## Logs
Error from the console - https://gist.github.com/Mgsy/3fef68d35ade6014c29e911bf859e54e

## GIF
![bug](https://user-images.githubusercontent.com/20988892/26966912-5cc3cf7e-4cfc-11e7-92a1-ad157c6bfef3.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
Merged into https://github.com/ckeditor/ckeditor5-clipboard/issues/23.
