### ISSUE TITLE
Refresh feed items and update editor content

### ISSUE THREAD

**Issue by baptooo** [ckeditor/ckeditor5#4671]
Hello and thank you for this very nice plugin ! 👌 

I am reporting this issue as I didn't found any matching existing one.

## Describe the issue
When updating the feed values, the editor content is not updated with the new values.
I am looking for a way to update all the existing mentions in the model with the new values.

I tried to create a custom editor command called `mention:refresh` that will find every element that has the attribute `mention` and replace the `text` value with the incoming one but I didn't manage to do this...

Is it possible in the actual version of the plugin please ? Is there a simpler way to achieve this ?

Thank you very much !

## Screenshot
![2019-10-01 16 29 20](https://user-images.githubusercontent.com/1875595/65971629-bbccbe80-e468-11e9-94ca-19dc849f34b3.gif)

**Comment by saiyam-gambhir** [comment]
Hello, @jodator I am also struck with this.
Is there any example that explains the whole process.
I am getting the mentions data as getters from vuex and then storing in the feeds but it is not updating it.
Thanks.

**Comment by jodator** [comment]
@saiyam-gambhir You mean to replace all mentions with the updated ones? You can invoke [the above example](https://github.com/ckeditor/ckeditor5/issues/4671#issuecomment-537466838) with your own additions. If you store the updated feed you need to manually update the editor content from your Vue app. If you'd wrap the above sample in some method then you would only need to execute it passing `editor` and updated `feed` but the data customization is up to you.
