### ISSUE TITLE
Text dragged out of a balloon shouldn't replace original element

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#468]
### Scenario 1
1. Open a sample with an image.
2. Select the image and open a text alternative balloon.
3. Drag it's content and drop on a paragraph.

### Scenario 2
1. Select some text.
2. Press <kbd>CTRL</kbd> + <kbd>K</kbd> and type some text.
3. Select text from step 2.
4. Drag it and drop on a paragraph.

## Current result
Text from a balloon replaces the element which had balloon sticked to it.

## GIF
![bug](https://user-images.githubusercontent.com/20988892/26968204-70b71356-4d01-11e7-8042-0fb55379a12d.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Opera, Edge
Release: 0.10.0

**Comment by Reinmar** [comment]
Merged to https://github.com/ckeditor/ckeditor5-clipboard/issues/23.
