### ISSUE TITLE
[Firefox] Placeholder doesn't disappear after clicking on it

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#469]
## Steps to reproduce
1. Open a sample with placeholders.
2. Click few times on a placeholder.

## Current result
Placeholder doesn't disappear.

## Expected result
Placeholder should disappear when you click it.

## Notes
Placeholder disappears only if you place a caret after text.

## GIF
![bug](https://user-images.githubusercontent.com/20988892/27025898-587fbcae-4f5c-11e7-8dd8-64f0982c48f1.gif)

## Other information
OS: Windows 10
Browser: Firefox
Release: 0.10.0

**Comment by Reinmar** [comment]
![jun-21-2017 20-55-32](https://user-images.githubusercontent.com/156149/27401583-02ca8356-56c4-11e7-9f81-095afa84fe09.gif)

It's really bad with the caret appearing outside the `<h2>` because typing there will crash the editor.

**Comment by Reinmar** [comment]
I fixed the second part of the issue by https://github.com/ckeditor/ckeditor5-engine/commit/34498a83778a2efe0fd036e480e54b0fbf6b255a.

But I can't find why Firefox would ignore some clicks. It's also hard to find some rule when they are ignored.

**Comment by Reinmar** [comment]
Or... actually, it works nearly seamlessly now:

![jul-07-2017 17-05-58](https://user-images.githubusercontent.com/156149/27963879-9b827940-6336-11e7-8f37-b87db0409117.gif)

**Comment by Reinmar** [comment]
@Mgsy, could you confirm whether it's better now?

**Comment by Mgsy** [comment]
> @Mgsy, could you confirm whether it's better now?

Yes, now it works as it should.
