### ISSUE TITLE
Documentation for grunt/gulp tasks

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#47]
Followup for #43 and #36.

I'm not sure yet where we want to keep it (in the README or in ckeditor5-design and later copy somewhere... dunno). But we definitely need to have a list of them with short descriptions what they are needed for.

Second part is a documentation of a typical workflow (based on #43).

**Comment by Reinmar** [comment]
One thing that would definitely need to be clarified in ckeditor5-design is what we encountered while working on #43. Like a more high-level description of the situation. Without it the behaviour of our tools may seem to be weird.

**Comment by szymonkups** [comment]
For now, I will put tasks description here. Later on we can move them to more suitable place.

## dev-install \< path|GitHub URL|name \>

###### Task description
Installs selected dependency in development mode. Dependency will be cloned into `workspace` directory (if it is not already), linked ( using symlink ) to `node_modules` and added to `package.json` inside CKEditor5 main repository. Dependency can be recognized by:
* path - local path to repository on disk
```
grunt dev-install /home/user/workspace/ckeditor5-core
```
* GitHub URL - it can be either short or full URL, also with branch information
```
grunt dev-install ckeditor/ckeditor5-core
grunt dev-install https://github.com/ckeditor/ckeditor5-core.git
grunt dev-install git@github.com:ckeditor/ckeditor5-core.git
grunt dev-install ckeditor/ckeditor5-core#branch-name
```

* name - module name used in NPM. In this situation task will try to reach NPM to obtain GitHub URL from package information and clone it to `workspace` directory
```
grunt dev-install ckeditor5-core
```
###### Task steps
1. Use either local path, GitHub URL or NPM name to recognize dependency.
1. If dependency directory does not exists - clone dependency repository into `workspace`.
1. If branch information is provided - checkout repository to desired branch.
1. Run `npm install` inside newly created repository to install all dependencies there.
1. Link repository to `node_modules` inside CKEditor5 repository.
1. Add dependency to `package.json` file inside CKEditor5 repository.
1. Install Git hooks inside dependency directory.

**Comment by Reinmar** [comment]
Important note: you use the term "Plugin development mode" and later use the word "plugin" many times.  The thing you're referring to is a "package" (aka "node module").

The important of a correct naming is well visible e.g. when you work on `ckeditor5-core` which is not a plugin – it's simply a package with some modules inside.

Relevant discussion is here: https://github.com/ckeditor/ckeditor5-design/issues/92

**Comment by Reinmar** [comment]
PS. https://github.com/ckeditor/ckeditor5/issues/66

**Comment by szymonkups** [comment]
Updated [my comment](https://github.com/ckeditor/ckeditor5/issues/47#issuecomment-165065990) to use gulp tasks, also replaced "plugin" with "package".

**Comment by Reinmar** [comment]
Published on https://github.com/ckeditor/ckeditor5/wiki/Development-Workflow. Great job.
