### ISSUE TITLE
[Firefox] Typing a long string without spaces stretches content width

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#470]
## Steps to reproduce
1. Create an empty paragraph.
2. Press a single key, i.e. <kbd>S</kbd> and hold it until letters touch editor's border.

## Current result
Text stretches content width without making a new line.

## GIF
![bug](https://user-images.githubusercontent.com/20988892/27033577-485ecc34-4f7a-11e7-8eb0-37d87ccd57c4.gif)

## Other information
OS: Windows 10
Browser: Firefox
Release: 0.10.0

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/462.

**Comment by oskarwrobel** [comment]
`word-break: normal` - looks like the solution, but I'm sure it can't be so easy :)
