### ISSUE TITLE
Implement autolinking feature

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#4715]
Create autolinking mechanism as separate feature. After new content is inserted to the editor, editor should detect matched UTL and automatically transforms it to link.

In addition to URLs it might also support email addresses.

**Comment by robclancy** [comment]
This is incredible. How is this not a thing? We have auto embed links, which can be super intrusive and if you want to disable it you need a custom build, but links don't link?  

When you use the medit provider
```js
{
    name: 'allow-all',
    url: /^.+/
}
```
Then you actually get all links converted to media, which with auto embed ruins things now. But the point is that the functionality is right there.

This is so surprising. This is something I would want to PR right away, basically copying the functionality from auto embed. But there is no indication on if a PR will even be accepted on here anymore.

Also this is tagged backlog... a core feature of any editor on a website is that links link when you paste or type them out.

**Comment by jodator** [comment]
After some fiddling with it - I'm not sure if the paste scenario is OK - or should be the only one.

### Behavior

I've checked GDocs & Word online and both works the same - the link is pasted as plain text. The autolinking happens on space & (shift-) enter. So it might be that this is what user would expect from this.

It should undo link on <kbd>ctrl</kbd>+<kbd>z</kbd>.

### Enabling

I guess the `AutoLink` plugin would be enough to have this as opt-in (opt-out) - similarly to `AutoMediaEmbed`. At this point I don't see a need for configuration (to not bloat our config). I'd start with autolinking links & emails.

---

The other thing is to implement the <kbd>CTRL</kbd>+<kbd>K</kbd> handling when selection (collpased?) is inside link - but that's different story (#4722).
