### ISSUE TITLE
Consider implementing fake visual selection in editable

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#4721]
Related issue https://github.com/ckeditor/ckeditor5-link/issues/2.

---

At this moment, if some content is selected in editable 

![image](https://cloud.githubusercontent.com/assets/1099479/17928997/e118fa16-69fd-11e6-9118-96bfe157accf.png)

and the user clicks "Link", which opens the panel and focuses an input inside, the original selection is **visually** lost in editable

![image](https://cloud.githubusercontent.com/assets/1099479/17928989/d5219c40-69fd-11e6-976b-f2be181b7100.png)

which can be considered an UX problem.
- Is is possible to implement something similar to what Find dialog does in v4? (fake selection using `<span>`)
- Would that be safe an easy to maintain? It would reside in editing view layer only, not in the document tree model, I guess.
- Can we react fast enough to changes in DOM like selection change using mouse or keyboard, command execution, etc. to get rid of fake selection and replace it with a real one so the features never get confused because of it?
- Most importantly, is it worth our effort? None of the editors in the market seems to bother. Well, maybe except Google Docs, but they always render selection using `<span>` in their custom editing environment, which is something completely different.

---

Just FYI, it works in classic editor in v4, because editable is enclosed in an iframe, which is technically a separate window and a separate focus context.

**Comment by jodator** [comment]
The first implementation seems to do the trick:

<table><tbody><tr><td>eSelection on text:</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/247363/84635711-e033d280-aef3-11ea-9601-7e6981fcfa07.gif"></figure></td></tr><tr><td>Collapsed selection</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/247363/84635718-e32ec300-aef3-11ea-9449-c6b3d18e391f.gif"></figure></td></tr></tbody></table>

I've used a marker for that (the colors are to be tuned later) and while doing it I've came to a conclusion that adding a visual representation for a collapsed selection might be also nice.

cc @oleq , @panr WDYT?

**Comment by panr** [comment]
Looks good 👌  Just wonder whether we should add an info about the collapsed selection - that the entered URL will extend selected text with its value (example.com) 🤔 (probably not a scope of the ticket).

**Comment by jodator** [comment]
From sync:

- use the CSS value for selection color

**Comment by oleq** [comment]
For the collapsed caret you can use a pulsing animation like in the type around feature https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgettypearound.css#L132.
