### ISSUE TITLE
Clean up the .svg icon files in the project

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#474]
The icons contain [tons of garbage code](https://raw.githubusercontent.com/ckeditor/ckeditor5-basic-styles/master/theme/icons/bold.svg) like comments, unnecessary `<title>`, other tags, attributes etc..

![image](https://user-images.githubusercontent.com/1099479/27277883-0f9ed55e-54e0-11e7-8c54-cfdefd0a32a9.png)

We got to get rid of this code and possibly use some external utility to optimize the files. 4KB for a bold icon feels like an excess. Some icons like [`object-center.svg`](https://raw.githubusercontent.com/ckeditor/ckeditor5-core/master/theme/icons/object-center.svg) are just ~300 bytes and that feels more like the right size.

A follow–up of https://github.com/ckeditor/ckeditor5-ui/issues/245.

**Comment by oleq** [comment]
https://github.com/svg/svgo feels like the right tool to use. Perhaps we should use it during the build phase?

**Comment by Reinmar** [comment]
Yeah... I wanted to comment on that. It'd be perfect if we could do the cleanup as late as on the build phase. But it means changing dozen Webpack configs. This is awful. We are yet to understand how much can our single Webpack plugin configure. It'd be perfect if it was able to set all those things so developers wouldn't have to repeat that.

@ma2ciek, be prepared :D

**Comment by oleq** [comment]
I checked the svgo. It saves 20KB in the `ckeditor5-core/theme/icons` alone 😮

**Comment by ma2ciek** [comment]
But adding svg minifying process (which is needed only once per svg) to each build would extend the build time. Or maybe I misunderstand something.

I'm not sure about running shell commands from Webpack. The JS lib that could process the file content would be the best, as it could be just a simple Webpack loader.

**Comment by oleq** [comment]
> But adding svg minifying process (which is needed only once per svg) to each build would extend the build time. Or maybe I misunderstand something.

Yes, I got your point. We may repeat it every time an editor is built or we can make people remember about it during the review. I wonder which approach is easier/safer 🤔 

BTW: https://github.com/tcoopman/image-webpack-loader supports svgo (found it in https://github.com/svg/svgo/blob/master/README.md).

**Comment by Reinmar** [comment]
> But adding svg minifying process (which is needed only once per svg) to each build would extend the build time. Or maybe I misunderstand something.

I wouldn't worry about it too much. After all, that's what build process is for – to optimise stuff.

The other option, which is optimising this on commit will require some code in all our repos and will slow down the dev env boostrap time.

**Comment by oleq** [comment]
> The other option, which is optimising this on commit will require some code in all our repos and will slow down the dev env boostrap time.

In my mind, the other option was more like "make sure you check it when reviewing any new icon" ;-)

**Comment by ma2ciek** [comment]
> BTW: https://github.com/tcoopman/image-webpack-loader supports svgo (found it in https://github.com/svg/svgo/blob/master/README.md).

This package looks really promising, so probably we can add the loader with our custom plugin if we don't want to force people to insert the loader manually into their `weback.config.js` file.

> I wouldn't worry about it too much. After all, that's what build process is for – to optimise stuff.

Probably you're right, as it doesn't take so much time.

**Comment by Reinmar** [comment]
But "check" and what? Someone needs to optimise it anyway. Unless this is easy to run manually by anyone in the team, that would be an inconvenient option. But if it is easy to run (e.g. `svgo --file=icon.svg`), then it may be the best option for now. We'll just need to notify the entire team.

**Comment by oskarwrobel** [comment]
Interesting fact is that Safari displays svg title

![image](https://user-images.githubusercontent.com/1057056/27284004-3477d77e-54f7-11e7-85fa-485687841779.png)

**Comment by oleq** [comment]
That's all you need to do:
```
npm install -g svgo
svgo -i icon.svg
```
I suppose we're not gonna introduce many new icons so there's no point in making it an automated process.

**Comment by oleq** [comment]
@oskarwrobel https://github.com/ckeditor/ckeditor5-ui/issues/245 ;-)

**Comment by oleq** [comment]
This is funny because it will be a PR-less issue. Changes awaiting the R are in t/ckeditor5/474 branches in the following repos:

* https://github.com/ckeditor/ckeditor5-basic-styles/tree/t/ckeditor5/474
* https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5/474
* https://github.com/ckeditor/ckeditor5-link/tree/t/ckeditor5/474
* https://github.com/ckeditor/ckeditor5-list/tree/t/ckeditor5/474
* https://github.com/ckeditor/ckeditor5-undo/tree/t/ckeditor5/474
* https://github.com/ckeditor/ckeditor5-upload/tree/t/ckeditor5/474

The uncompressed (no gzip, raw XML) icons weighted 41.5kB before the optimization. Now it's 15.5kB, which is quite impressive TBH (~37% of the original size).

When reviewing, make sure no distortion appeared visually and the icon properly responds to the parent color change (e.g. apply `color: red` to the `.ck-button` CSS class).

**Comment by oleq** [comment]
This issue will close https://github.com/ckeditor/ckeditor5-ui/issues/245.

**Comment by Reinmar** [comment]
I think that what this ticket misses is explaining somewhere how to deal with the new icons. Since we don't have any other place right now it can be somewhere in https://github.com/ckeditor/ckeditor5/wiki/Development-environment as "Additional stuff to remember when contributing". We'll later extract it to "Contributing" guide or something.

**Comment by szymonkups** [comment]
It looks like the tool is leaving `<title>` in icon files: https://github.com/ckeditor/ckeditor5-basic-styles/commit/b8580a129228d3e817d9e09b64ae6821654ef829#diff-4e876a53975446929ce59efb641136e5R1 so Safari still is displaying tooltips.

**Comment by oleq** [comment]
I just noticed that `removeTitle` is [disabled by default in SVGO](https://github.com/svg/svgo). I'll enable it and update branches soon.

**Comment by oleq** [comment]
Updated. Let's see how does it work now.

**Comment by szymonkups** [comment]
Now everything looks fine. I've merged all the branches and removed them. Please update Wiki and we will be able to close this issue.

**Comment by oleq** [comment]
[Updated the wiki](https://github.com/ckeditor/ckeditor5/wiki/Development-environment#svg-icons). The issue can be closed safely now.
