### ISSUE TITLE
Upgrade all Webpack usage to Webpack 3

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#475]
Release notes: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

Interesting to check:

* Module concatenation – we should check it in ckeditor5-build-classic. Hopefully, it will improve the bundle size. As for Webpack use in other places... I think that we could also introduce this plugin, but I'd check if it doesn't affect the performance. The performance will count the most in automated tests, so in manual tests we can lose more. Ideally, we should have the same configuration everywhere so we test with the production setup.
* "Better Build Caching" and "Faster initial and incremental builds" sounds like there might be some changes in the memory consumption – I hope that not for worse.

**Comment by pomek** [comment]
Bundle size with and without module concatenation:

- with: 381307B (**372K**),
- without: 420550 (**411K**).

So we could use it.

**Comment by Reinmar** [comment]
Nice! And gzipped size (which is the one which matters)?

**Comment by pomek** [comment]
Gzipped size:

- with: 101216 (**99K**),
- without: 112131 (**110K**).

**Comment by pomek** [comment]
PRs:

- https://github.com/ckeditor/ckeditor5-build-classic/pull/28,
- https://github.com/ckeditor/ckeditor5-build-inline/pull/2,
- https://github.com/ckeditor/ckeditor5-build-balloon/pull/2.
