### ISSUE TITLE
Typing over the link (replacing link text)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4762]
This was mentioned in ckeditor/ckeditor5#4720 but requires a separate ticket. Because of UX we need to allow replacing link text.

See https://github.com/w3c/editing/issues/156#issuecomment-263858380.

See also – typing after a link: https://github.com/ckeditor/ckeditor5-link/issues/72.

**Comment by pomek** [comment]
I've checked a few solutions that we have available on the market.

## Typing over the entire link

_The link is selected from left to right._

* CKEditor 5: replaces the text without the link, ignores 2SCM
* CKEditor 4: replaces the text without the link (except the first letter that is being linked)
* Tiny: uses 2SCM and produces different results based on starting selection:
  - when starts before the link - the same as CKEditor 5
  - when starts at the beginning of the link - the same as CKEditor 4
* Quil: the same as CKEditor 4
* Google Docs: the same as CKEditor 5

## Typing in the non collapsed selection in the link

All editors listed above do the same action: replaces the text and keeps the link.

## Typing when the selection starts at the beginning of the link (ends in)

* CKEditor 5: replaces the text without the link
* CKEditor 4: replaces the text and keeps the link
* Tiny: the same as CKEditor 4
* Quil: the same as CKEditor 4
* Google Docs: the same as CKEditor 4

## Typing when the selection ends at the end of the link (starts somewhere in)

* CKEditor 5: replaces the text and keeps the link
* CKEditor 4: replaces the text without the link (except the first letter that is being linked)
* Tiny: the same as CKEditor 5
* Quil: the same as CKEditor 4
* Google Docs: replaces the text without the link

### My 5 cents

* **Typing over the entire link**
  The link should be removed. The same happens with basic styles and we should be consistent across all features (we do it now)
* **Typing in the non collapsed selection in the link** 
  The inserted text should be linked. We edit a part of the link (we do it now)
* **Typing when the selection starts at the beginning of the link (ends in)**
  Most probably a user wants to update the beginning of the link, we should insert the text as the link (we don't do it now)
* **Typing when the selection ends at the end of the link (starts somewhere in)**
  The same as above (we do it now)

**Comment by Reinmar** [comment]
> ## **Typing when the selection starts at the beginning of the link (ends in)**
> 
> *   CKEditor 5: replaces the text and keeps the link
> *   Google Docs: the same as CKEditor 4

From what I can see, GDocs behave like CKE5 – you write without the link.

> ### **My 5 cents**

So, AFAICS, there's just one behavior that perhaps we should change – the one with typing at the beginning on a non-collapsed selection. We could indeed align our behavior to that of CKE4, Tiny, Quill here. 

However, my question would be – why? How's this different from typing over the entire link? Why can I edit the beginning of a link or the end of the link but not the entire link text at once?

**Comment by jodator** [comment]
> **Typing over the entire link**  
> The link should be removed. The same happens with basic styles and we should be consistent across all features (we do it now)

For the above behavior I'm not sure TBH, so another voice needed.

*   :+1: to keep consistency (remove link)
*   :-1: for PITA whe I'd like to replace link text but keep a link and probably we never get 100% agreement here what is a desired action. Selecting a text with link and typing over it is a bit different than selecting a link and using <kbd>del</kbd>/<kbd>backspace</kbd>.

 The below are :+1: for me:

> **Typing in the non collapsed selection in the link**  
> The inserted text should be linked. We edit a part of the link (we do it now)
> 
> **Typing when the selection starts at the beginning of the link (ends in)**  
> Most probably a user wants to update the beginning of the link, we should insert the text as the link (we don't do it now)
> 
> **Typing when the selection ends at the end of the link (starts somewhere in)**  
> The same as above (we do it now)

**Comment by Reinmar** [comment]
> *   👎 for PITA whe I'd like to replace link text but keep a link and probably we never get 100% agreement here what is a desired action. Selecting a text with link and typing over it is a bit different than selecting a link and using del/backspace. In other words having replace mechanism for typing wouldn't be a big PITA compared to not having it.

Same thoughts here. I'm also considering being inconsistent with other editors here. And I also see a differernce between typing over a link and pressing backspace/delete. In the latter case, I think that it's more natural to remove the link. In the former, I think we could risk keeping the link.

Let's maybe discuss this tomorrow on the sync too.

**Comment by neongreen** [comment]
For me, not being able to replace the link text by selecting it and typing over is indeed a PITA. I resort to tricks like "select everything but the first and the last character, type what I want, remove the first and the last character".

I'd much prefer "keep the link but replace the link text when typing over; delete the link entirely on backspace".

**Comment by jodator** [comment]
Notes from internal meeting:

*   we agree we should have replace link text when whole link is selected and keep the link 👍
*   link only for safety
*   how to implement?
    *   pasting - no
    *   insertContent - check constrains and then override 👍
    *   command (input) - override behavior (first letter only probably) :-1: 
    *   selection attributes - non empty selection with link - set selection attributes for link - check why selection attributes is not inherited on type :-1: 
*   only one link (not two links selected)
