### ISSUE TITLE
You shouldn't be able to link an image (just yet)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4771]
The link feature should be disabled when an image is selected. Most likely some state check is missing.

In the future, we'll add the possibility to link images, but so far we don't have converters for that.

Alternatively, instead of fixing the state check now, we can add a converter allowing linking images. But the state check needs to be fixed at some point anyway.

**Comment by VikramP-RSW** [comment]
<script src="https://cdn.ckeditor.com/ckeditor5/34.2.0/classic/ckeditor.js"></script>

i m using this version and not able to use linkingImage facility I mean i cant able to add link over Image
