### ISSUE TITLE
Task dev-install clones repositories using wrong Git URLs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#48]
I should end up with this in `.git/config`:

```
[remote "origin"]
	url = git@github.com:ckeditor/ckeditor5-core.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

But I had this:

```
[remote "origin"]
	url = https://github.com/ckeditor/ckeditor5-core
	fetch = +refs/heads/*:refs/remotes/origin/*
```

But... we get those URLs from package.json so we need to figure out when to change them to those SHH ones.

**Comment by szymonkups** [comment]
Added PR that fixes this issue - when short GitHub URL is provided in `package.json` we will use SSH for cloning.
