### ISSUE TITLE
The caret disappears after styling a word and applying a marker

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#480]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-engine/tests/manual/markers.html
2. Select a word.
3. Press <kbd>CTRL</kbd> + <kbd>B</kbd>.
4. Apply marker to the word.
5. Try to place the caret at the marker.

## Current result
The caret is invisible, but you're still able to type inside the marker.

## Notes
- Bug isn't reproducable on MS Edge.
- Might be related - https://github.com/ckeditor/ckeditor5/issues/478

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27475293-e9462e0c-5804-11e7-8530-2bb24c3cf269.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
I think it's just a problem with the manual test. It may be that the button steals focus from the editable.

**Comment by oskarwrobel** [comment]
Caret is invisible after focusing editable.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore.
