### ISSUE TITLE
How to add multiple attributes to 'a' tag ?

### ISSUE THREAD

**Issue by gauravjain028** [ckeditor/ckeditor5#4827]
I want to add multiple attributes to the **a** tag. In the engine where we do like

```
buildModelConverter().for( data.modelToView, editing.modelToView )
	.fromAttribute( 'linkHref' )
	.toElement( linkHref => {
		const linkElement = new LinkElement( 'a', { href: linkHref } );

		// https://github.com/ckeditor/ckeditor5-link/issues/121
		linkElement.priority = 5;

		return linkElement;
	} );
```

What should I do to set more attributes, like target, rel attributes. If I do same as above it adds one more **a** tag.

**Comment by Reinmar** [comment]
The things discussed in this thread were documented in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html.
