### ISSUE TITLE
Allow setting link's target attribute (allow opening links in new tabs)

### ISSUE THREAD

**Issue by itelmenko** [ckeditor/ckeditor5#4829]
## Original ticket description

> Hello!
>
> There are not ability to select target of link in ckeditor5 . 
>
> Please, add it

## Feedback needed

Please read this discussion starting from [this comment](https://github.com/ckeditor/ckeditor5-link/issues/186#issuecomment-452392660) and leave your feedback (by adding a reaction) in [this comment](https://github.com/ckeditor/ckeditor5-link/issues/186#issuecomment-452608537).

**Comment by zehawki** [comment]
I felt compelled to come here and add a note that this feature is the cat's whiskers :-) What a fricking lifesaver to be able to put an auto rule that sends external links to a new window without having to worry about writers screwing the UX for readers. Thank you! CK editor is lovely, and thank you for listening to the community.

**Comment by liuxiaojiu** [comment]
[www.baidu.com](url)

**Comment by sdavid501** [comment]
link: {
      defaultProtocol: 'http://',
      addTargetToExternalLinks: true
    }

**Comment by mlewand** [comment]
@Madejczyk I haven't set up any particular branch containing this configuration. All that is required is just some simple config adjustment.

I made a demo so you can play with it: https://codepen.io/pen?editors=1010

**Comment by MrBeeUser** [comment]
link: {
            decorators: {
                openInNewTab: {
                    mode: 'manual',
                    label: 'Open in a new tab',
                    attributes: {
                        target: '_blank',
                        rel: 'noopener noreferrer'
                    }
                }
            }
        }

See here https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-attributes-to-links-using-the-ui-manual-decorators

**Comment by Jones-S** [comment]
It seems that the setting is reset:
I have this code: 
```
  link : {
    decorators: [
      {
        mode: 'manual',
        label: 'External Link',
        attributes: {
          rel: "noopener noreferrer",
          target: '_blank',
        }
      }
    ]
  }
```
(like indicated above)

And I get this

https://github.com/user-attachments/assets/6d55938d-cb5d-4a23-a526-8d1d3a905307

Is this normal? How would one fix this?

**Comment by sebastianbayer** [comment]
Seems to work again with the latest Version of Craft CMS (5.5.7) & CKEditor Plugin (4.4.0). 👍
