### ISSUE TITLE
[Edge] Placeholder appears after opening the link balloon multiple times 

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#483]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html
2. Click on the link to open the link ballon.
3. Click somewhere else to close the link balloon.
4. Repeat steps 2 and 3 multiple times.

## Current result
Placeholder appears next to the url inside the balloon.

## Notes
Placeholder should appear after few clicks, but sometimes it could take a while to reproduce this issue.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27580692-c25f6eaa-5b2b-11e7-9b18-497641d1c286.gif)

## Other information
OS: Windows 10
Browser: Edge 15
Release: 0.10.0

**Comment by Reinmar** [comment]
LOL... The placeholder is rendered by Edge. We just use the `placeholder` attribute.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore.
