### ISSUE TITLE
Focusing Link actions view by Tab works only for the first time

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#4831]
It occurs on FF, Safari and Edge.
Works fine on Chrome.

## Steps to reproduce
1. Click on link element in editable, link actions view should appear attached to the link element
2. Press Tab to move focus to the actions view
3. Click Once again to the same link element to move focus again to editable
4. Press Tab to move focus to the actions view

## Expected result
Link actions view is focused

## Current result
Focus went somewhere

## Preview
![apr-24-2018 09-12-57](https://user-images.githubusercontent.com/1057056/39171785-1ec0eee2-47a0-11e8-9862-194142323355.gif)

## The reason
This is because `Link.actionsView.focusTracker` stays focused after the `actionsView` is removed from `ContextualBalloon`. DOM `blur` event is not fired at all.

So this condition works only for the first time becuase `this.actionsView.focusTracker.isFocused` stays as true.
https://github.com/ckeditor/ckeditor5-link/blob/82dc81e92c0e5c940c7d879453297271bd944b6e/src/linkui.js#L220

This is a browser issue because focused element that is removed from DOM should dispatch blur event:
- https://bugzilla.mozilla.org/show_bug.cgi?id=559561 (reported 8 years ago :D)
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6274504/ (2 years)

So we need to find a workaround for this. It might be resetting `FT` after removing `actionsView` from `CB` (here:)
https://github.com/ckeditor/ckeditor5-link/blob/82dc81e92c0e5c940c7d879453297271bd944b6e/src/linkui.js#L362-L363

**Comment by FilipTokarski** [comment]
Those bugs are now entirely fixed in the new upcoming Edge v.79.0.309.56

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
