### ISSUE TITLE
Link balloon should be visible even if command is disabled

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#4834]
As the title says. Currently, the function that handles opening the balloon toolbar returns quickly if the command is disabled.

I think this is incorrect for some reasons:

1. Buttons in the balloon will be disabled anyway so no editing will be possible.
2. At the moment, in read-only mode, the links are clickable anyway, so nothing opens anyway.
3. But there might be other editor's state where link command is temporarily disabled but you would like to be able to open the balloon to check out the link's URL.

**Comment by pomek** [comment]
> Buttons in the balloon will be disabled anyway so no editing will be possible.

The unlink button seems to be active even if the link command will be disabled.

![image](https://user-images.githubusercontent.com/2270764/72875529-bdaade00-3cf4-11ea-97c6-96d08f019fe5.png)

Is it ok? You can't create new links but existing ones can be destroyed.

**Comment by scofalik** [comment]
> The unlink button seems to be active even if the link command will be disabled.

I think this is fine. These are two separate commands. If a feature "blocks" editor (like read-only or comments-only mode) then it should block both of these commands. Of course, I hope that the button is linked with the command.
