### ISSUE TITLE
[Edge] Selection from the end of blured block element isn't possible

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#484]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html
2. Click at the end of the block element and hold the mouse button.
3. Without releasing the mouse button, try to drag a selection to the beginning of this block element.

## Current result
It's impossible to make a selection.

## Notes
Issue isn't reproducable if you put the caret at the end of the block element and then try to make a selection. 

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27583505-ec1d14b4-5b34-11e7-8717-08e7c22dd436.gif)

## Other information
OS: Windows 10
Browser: Edge 15
Release: 0.10.0

**Comment by Reinmar** [comment]
Does it work in CKEditor 4?

**Comment by Mgsy** [comment]
> Does it work in CKEditor 4?

Yes, in CKE4 everything works fine. I also checked it on some content on jsfiddle and it also worked. It seems it's not browser's issue.

**Comment by Reinmar** [comment]
OK. Thanks.

Let's merge it into https://github.com/ckeditor/ckeditor5-engine/issues/928 because all those issues seem to be related.
