### ISSUE TITLE
[Edge] Link disappears on enter after link text 

### ISSUE THREAD

**Issue by charithgunaratna** [ckeditor/ckeditor5#4844]
This bug only repros in Edge. Chrome works fine. 
1) Add a link using the balloon. 
2) Click on the green checkmark after done typing.
3) Click on the text box outside the link text and press enter

![ckeditor5-link](https://user-images.githubusercontent.com/14225179/55991443-25f56b00-5c5f-11e9-922d-bf3ef59b6c9f.gif)

Expected: 
Cursor should goto a new line.

Actual:
Link is removed

**Comment by FilipTokarski** [comment]
This bug still exists on old Edge, however it is fixed in the new upcoming version (79.0.309.56)

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
