### ISSUE TITLE
Marker is lost after dividing the word at the end of a paragraph

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#485]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-engine/tests/manual/markers.html
2. Apply the marker to some word at the end of the paragraph (there shouldn't be any characters without the marker).
3. Put the caret inside this marker.
4. Press <kbd>Enter</kbd>.

## Current result
Part of the marker, which was moved downwards, became a plain text.

## Notes
Issue doesn't occur if there is some text without the marker at the end of the paragraph.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27590373-c8815082-5b4e-11e7-8ce9-0b7700f08aad.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera, Firefox, Edge
Release: 0.10.0

**Comment by scofalik** [comment]
When debugging this check whether the marker (in `document.markers`) is wrong or correct. This issue may be caused by two problems:

1. `Marker` range was incorrectly transformed.
2. `Marker` was incorrectly converted to view.

**Comment by Mgsy** [comment]
I noticed that if you try to "reverse" the scenario, it will give you the same effect. Take a look at this case:

## Steps to reproduce
1. Select the first word of the paragraph.
2. Apply the marker.
3. Put the caret before the marker (at the beginning of the paragraph).
4. Press <kbd>Enter</kbd>.

![bug_cke5](https://user-images.githubusercontent.com/20988892/27635885-3646b566-5c09-11e7-8005-1c51ff6fd073.gif)

**Comment by scofalik** [comment]
For the first reported issue, I created a ticket in proper repo: https://github.com/ckeditor/ckeditor5-engine/issues/1006

The second reported issue can't be reproduced anymore.

**Comment by Reinmar** [comment]
Closed by https://github.com/ckeditor/ckeditor5-engine/issues/1006.
