### ISSUE TITLE
List feature and focus cycler collision

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#486]
If I use `FocusCycler` to handle focus outside the editor and I want to indent list then both actions are executed: the list is indented and focus is moved.

![list-focuscycler](https://user-images.githubusercontent.com/1166967/27634447-8eb91014-5c03-11e7-8ca0-05901c6a5a6a.gif)

To reproduce it add this code to the Classic Editor sample.
```js
function initializeFocusCycling( editor ) {
	const focusTracker = new FocusTracker();
	const keystrokes = new KeystrokeHandler();
	const focusables = new ViewCollection();

	const buttonView = new ButtonView( editor.locale );
	buttonView.label = 'Save';
	buttonView.withText = true;
	document.body.appendChild( buttonView.element );

	keystrokes.listenTo( document );

	[ editor.ui.view, buttonView ].forEach( view => {
		focusables.add( view );
		focusTracker.add( view.element );
	} );

	const focusCycler = new FocusCycler( { focusables, focusTracker } );

	keystrokes.set( 'tab', ( evt, cancel ) => {
		focusCycler.focusNext();
		cancel();
	} );
}
```

**Comment by oskarwrobel** [comment]
This is a matter of keystroke priorities. `KeystrokeHandler` supports it https://github.com/ckeditor/ckeditor5-utils/issues/180. I think we can close this ticket.

**Comment by Reinmar** [comment]
If this is closed either pick the right milestone or "fixed" label.
