### ISSUE TITLE
[Chrome, Firefox, Opera] Text is pasted with the whitespace at the beginning

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#487]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-clipboard/tests/manual/pasting.html
2. Select some part of the text.
3. Press <kbd>Ctrl</kbd> + <kbd>C</kbd>.
4. Put the caret at some word.
5. Press <kbd>Ctrl</kbd> + <kbd>V</kbd>.

## Current result
Text is pasted with the whitespace at the beginning.

## Notes
Issue doesn't occur on Safari and Edge.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27637474-260bda12-5c10-11e7-9e70-22fcb0b6b7c0.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Firefox, Chrome, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
I can't reproduce it. Is there something special you do? Can you still reproduce it?

**Comment by Mgsy** [comment]
I checked it again and I can't reproduce it anymore.

**Comment by Reinmar** [comment]
Good news :) thanks.
