### ISSUE TITLE
[Chrome, Opera] Dragging the selection over the image with caption moves the image and the caret

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#489]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html
2. Be sure that the image has caption and is transformed into "side image".
3. Put the caret at the end of the quote block and drag the selection over the image.

## Current result
- The image is moving upwards and downwards
- The caret blinks at the beginning of the document

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27737900-20e44722-5daa-11e7-891a-210873d12eda.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
This is another case for https://github.com/ckeditor/ckeditor5-image/issues/19.
