### ISSUE TITLE
[Chrome, Safari] Typing is disabled after pasting the link from the external page

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#491]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html
2. Go to some external website, i.e. https://en.wikipedia.org/wiki/Jimi_Hendrix
3. Copy some text with the link. 
4. Paste it to the editor.
5. Put the caret at the end of the link.
6. Try to type something.

## Current result
Typing is disabled.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27795445-751a475c-6006-11e7-95a2-31fa9096d0f6.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
The minimal TC is to:

1. Write some text.
2. Select a part of it.
3. Apply a link and apply italic.
4. Typing at the end of it is disabled.

**Comment by Reinmar** [comment]
There's more, unfortunately:

![jul-03-2017 16-15-36](https://user-images.githubusercontent.com/156149/27796604-e362774e-600a-11e7-9e51-719c073c4f01.gif)

Also reproducible if you apply the italic to e.g. the last letter of a linked word.

**Comment by Reinmar** [comment]
Surprisingly, this is not due to the recent changes in ckeditor/ckeditor5-engine#922.

**Comment by Mgsy** [comment]
> There's more, unfortunately:

Here is another case related with markers:
![bug_cke5](https://user-images.githubusercontent.com/20988892/27796953-1df1a35c-600c-11e7-93f1-82cdab61e1d2.gif)

**Comment by Reinmar** [comment]
The first revision which fails is 4f6bb68 which contains https://github.com/ckeditor/ckeditor5-link/issues/121 and https://github.com/ckeditor/ckeditor5-engine/issues/963 which is unlikely to have any effect on this.

So, my guess is that this issue existed for a long time but it was invisible due to incorrectly rendered links.

**Comment by Reinmar** [comment]
**Important**: In the case originally reported by @Mgsy, typing is disabled but no error is thrown. In the case I found later the editor crashes, so these may be two separate issues unfortunately.
