### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#492]
While refactoring commands API (https://github.com/ckeditor/ckeditor5-core/issues/88) we talked about the read-only mode.

Recently, we also talked about it more, F2F with @Reinmar and @oskarwrobel.

We decided that:

 - there should be an observable property in the editor: `editor.readonly`, so all features can observe it,
 - the command base class should have a default listener which disable all commands if the editor is in the read-only mode,
 - UI should be disabled manually: for instance, the contextual toolbar should not be displayed if all buttons there are disabled, on the other hand, it should be possible to open link balloon on a link to copy that link URL (however in can be implemented later),
 - the engine will not block anything in the read-only mode, in case somebody wants to implement a feature which applies some changes anyway,
 - selection should be enabled in the read-only mode, it should be possible to select and copy text.

**Comment by Reinmar** [comment]
> there should be an observable property in the editor: editor.readonly, so all features can observe it,

`readOnly` or `readonly`? The word is "read-only" so these are two separate words, hence `readOnly`. [CKE4 uses `readOnly`](http://docs.ckeditor.com/#!/api/CKEDITOR.commandDefinition-property-readOnly) as well.

Besides, we wanted to resign from having a negated "readOnly" and instead have "isEditable". I think we already have it somewhere in the code. So, we should make the final decision and clean this up.

> the command base class should have a default listener which disable all commands if the editor is in the read-only mode,

See https://github.com/ckeditor/ckeditor5-core/blob/77e52176e0885d37d8c05e8d2f7851b58c033fe6/tests/command.js#L115-L134



> selection should be enabled in the read-only mode, it should be possible to select and copy text.

This we need to see live. Our first step is to disable features, so disable ability to change the content. But then we need to figure out what to do with the selection. Do we want to turn of `contentEditable` or do we want to leave ability to put a caret in the content or do we want something in between. Let's make the decision later as we'll be able to better understand the needs.

**Comment by oskarwrobel** [comment]
`readolny` is consistent with HTML `input#readolny` attribute.

**Comment by Reinmar** [comment]
> readolny

I love the typo :D Makes this word so cool :D

**Comment by oskarwrobel** [comment]
Fixed :D

**Comment by Reinmar** [comment]
> readolny is consistent with HTML input#readolny attribute.

Aren't attributes case-insensitive?

![image](https://user-images.githubusercontent.com/156149/27800005-d633066c-6017-11e7-9e44-0e24b378cd15.png)

But:

![image](https://user-images.githubusercontent.com/156149/27800034-f3b86c54-6017-11e7-978e-c2a81294ea44.png)

**Comment by pjasiun** [comment]
I would keep `readonly`/`readOnly`. `Editable` as already overused (`isEditable` could be also a method to check if the type of the element is "Editable", also `editable.isEditable = false` looks very strange for me). I'm fine with both `readonly` and `readOnly`, but to keep backward compatibility and because its 2 words I prefer `readOnly`.

**Comment by scofalik** [comment]
In this case I am also for `readOnly`. I know we had discussion about parameter names but this one I think is fine and natural. We are all used to think about editor as "read only" and "not read only". As @pjasiun stated, `isEditable` has connotation with other parts of code.

**Comment by Reinmar** [comment]
Back to the naming... shouldn't it be `isReadOnly`?

> Boolean properties and variables are always prefixed by an auxiliary verb:

https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines

**Comment by pjasiun** [comment]
`isReadOnly` is great.

**Comment by oskarwrobel** [comment]
One of the requirements is:
> UI should be disabled manually: for instance, the contextual toolbar should not be displayed if all buttons there are disabled, on the other hand, it should be possible to open link balloon on a link to copy that link URL (however in can be implemented later),

From @fredck.
> I'm for not showing contextual toolbars at all, if the editor is readonly.

https://github.com/ckeditor/ckeditor5-image/issues/123#issuecomment-313639614
