### ISSUE TITLE
[Edge] Pressing "Backspace" at the end of a list item in the nested list moves the caret downwards

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#493]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html
2. Put the caret at the second list item.
3. Press <kbd>Tab</kbd>.
4. Put the caret at the end of the first list item.
6. Press <kbd>Backspace</kbd>.

## Current result
The caret moves to the beginning of the second item, but user is still able to type at the first item.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27857869-85b57140-6173-11e7-990f-bd204b68ac0e.gif)

## Other information
OS: Windows 10
Browser: Edge
Release: 0.10.0

**Comment by FilipTokarski** [comment]
This bug is fixed in the new upcoming Edge v.79.0.309.56.

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
