### ISSUE TITLE
Rise the specificity of CSS reset rules (and all other rules as well)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#494]
I added CKEditor samples to CKEditor documentation and guess what? The CKEditor's reset gets overridden by the page styling.

![image](https://user-images.githubusercontent.com/156149/27859875-7d3f7310-617a-11e7-9f0d-5533b685213c.png)

The documentation website styles are not very specific. They are actually really common:

![image](https://user-images.githubusercontent.com/156149/27859925-b845eae8-617a-11e7-80b2-d65791249897.png)

The `.formatted ...` styles come from Umberto.

So, the problem that we have is that `.ck_reset` has very low specificity. It's enough to have `.mycontent ul` to break that.

I can see that we've been adding rules like `.ck_reset_all *` which would've the same specificity as `.mycontent ul` but I'm thinking that perhaps we could do something else.

What if we had a rule that we're always using at least two classes? Like, what if everything had `.ck` class, so we can always use `.ck.ck_reset` and then `.ck.ck-list__item`. That would always give us minimum specificity of 20 which would always override styles like `.mycontent ul` (which are 11).

**Comment by oleq** [comment]
> What if we had a rule that we're always using at least two classes? Like, what if everything had .ckclass, so we can always use .ck.ck_reset and then .ck.ck-list__item. That would always give us minimum specificity of 20 which would always override styles like .mycontent ul (which are 11).

👍 

I'll check this out.

**Comment by jodator** [comment]
Also: 
![selection_056](https://user-images.githubusercontent.com/247363/36216792-10b102ae-11b0-11e8-8b45-3eb84dd32752.png)
