### ISSUE TITLE
[Edge] "Arrow up" and "arrow down" are disabled inside the marker

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#496]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-engine/tests/manual/markers.html
2. Put the caret inside the marker.
3. Press <kbd>Arrow up</kbd> or <kbd>Arrow down</kbd>.

## Current result
Nothing happens. 

## Other information
OS: Windows 10
Browser: Edge
Release: 0.10.0

**Comment by mlewand** [comment]
Looks like an upstream. Hopefully Edge engine should be changed soon and this will resolve this issue. Let's keep an eye on it.

**Comment by FilipTokarski** [comment]
I checked it and It seems to be fixed in the new upcoming Edge v.79.0.309.56

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
