### ISSUE TITLE
Deleting the placeholder shouldn't be possible

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#497]
### Scenario for Chrome, Safari, Opera
1. Go to http://localhost:8125/ckeditor5-engine/tests/manual/placeholder.html
2. Type something in the title.
3. Press <kbd>Ctrl</kbd> + <kbd>A</kbd>.
4. Press <kbd>Delete</kbd>.

### Scenario for Edge, Firefox
1. Focus the editor.
2. Repeat steps 3 and 4 from scenario 1.

## Current result
**Scenario 1:**
- Paragraph placeholder disappears

**Scenario 2:**
- Placeholders disappears

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27957458-ed992aca-631e-11e7-8e00-060d9adedd70.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Firefox, Safari, Opera, Edge
Release: 0.10.0

**Comment by Reinmar** [comment]
This manual test doesn't limit you from removing the paragraph. It's beyond the scope of that manual test.
