### ISSUE TITLE
Ctrl + A in the balloon doesn't select whole content

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#498]
## Steps to reproduce
1. Open the balloon (it could be the link balloon or the text alternative balloon).
2. Focus the input.
3. Press <kbd>Ctrl</kbd> + <kbd>A</kbd>.

## Current result
Nothing happens.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27961804-4a49ebf4-6330-11e7-862a-9275e7aaea7d.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Edge, Opera

**Comment by oleq** [comment]
The problem is [this line](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/panel/balloon/balloonpanelview.js#L140). It's been introduced to fix https://github.com/ckeditor/ckeditor5-link/issues/126 but when removed, I cannot reproduce the original issue anyway which is odd.

**Comment by Reinmar** [comment]
So how do you know that it's this line?

**Comment by Reinmar** [comment]
Oh, by "original issue" you mean ckeditor/ckeditor5-link#126. Nvmnd
