### ISSUE TITLE
Space missing when pasting

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#499]
1. Copy the phrase "Please read our Privacy Statement." from the "Privacy" section of this page: https://cksource.com/terms.
 2. Paste it inside CKEditor.

Note that the space before the linked words is missing.

(A side note, the link is also not maintained)

**Comment by Reinmar** [comment]
Fixed on master already by https://github.com/ckeditor/ckeditor5-clipboard/issues/24 and https://github.com/ckeditor/ckeditor5/issues/477.

**Comment by Reinmar** [comment]
Proof :P

![image](https://user-images.githubusercontent.com/156149/28010764-3ec50a16-6560-11e7-883d-5eafb0812304.png)
