### ISSUE TITLE
Option+Backspace doesn't delete words

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#501]
This is something that I do very often. When I have a typo in a word, instead of moving the caret to the mistake position and fix it, I simply delete the whole word and write it again. It's just faster.

To achieve that, I do `Option+Backspace` (Mac). Don't know the Windows way for it.

Unfortunately, this doesn't work and a single character is deleted only :(

By-Word navigation with `Option+Arrows` works fine though.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-typing/issues/92.
