### ISSUE TITLE
The alt attribute should always be output

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5033]
It's required in the data output. Perhaps it should also be required in the model, even when empty.

**Comment by jodator** [comment]
@Comandeer is adding always an empty `alt=""` OK(-ish) if no alt specified? It looks like empty alt solves some errors.

**Comment by jodator** [comment]
It looks like the `src` attribute cannot be ommited also. As both `src` and `alt` use the same converter I think that the best way is to keep both in the data. However, an empty `src` (or omitted) is invalid in terms of [HTML spec](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-src). Rest of [comments in the PR](https://github.com/ckeditor/ckeditor5/pull/7405#discussion_r437947119).
