### ISSUE TITLE
Right-click over image has a weird effect

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#5049]
With Chrome, when right-clicking an image ([like the one in the demo](https://ckeditor5.github.io/)), the native selection seems to briefly take place and the fake selection disappears. It gives a "flashing" effect. Then the native context menu appears, which is ok.

Ideally, the fake selection would stay on the image and no fancy flashing should happen.

**Comment by FilipTokarski** [comment]
I checked it and can't reproduce any 'flashing' effect, I guess we can close this one.
