### ISSUE TITLE
What should toolbar config look like when there's more than just items to set?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#505]
A follow-up of https://github.com/ckeditor/ckeditor5/issues/495.

ATM, our toolbar config is pretty straightforward:
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ]
}  );
```
However, because of #495, sometimes users will have to specify an additional offset for the toolbar. There are basically 3 ways to do it:
## Logical
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: {
		items: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ],
		verticalOffset: 150
	}
}  );
```
It totally makes sense. However in 95% of integrations there will be no `verticalOffset`, so we always force developers to define their configs like this:
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: {
		items: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ]
	}
}  );
```
which looks totally anti–KISS.

## Sentimental
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ],
	toolbarVerticalOffset: 150
}  );
```
It keeps the essential toolbar config simple but then why we allowed configuration nesting in the first place?

## Agile
Both 
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ]
}  );
```
and 
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: {
		items: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ],
		verticalOffset: 150
	}
}  );
```

are valid. The logic under the hood discovers and normalizes the configuration. Feels like an overkill but OTOH it solves both problems: an elegant `verticalOffset` setting and simple `toolbar: [ ... ]` in most of the cases.

---

cc @Reinmar, @fredck

**Comment by Reinmar** [comment]
Big -1 for sentimental. We should use the possibility that we have in CKE5 and group the config options.

So, of course, I'm for Logical and Agile. I'd say KISS and go with Logical only, but we're using the simplified notation already in so many places that it will be actually simpler to go with Agile :D

**Comment by oleq** [comment]
We have "83 matches across 70 files" for `toolbar: [` (which includes image toolbar) but it's a lot of work in multiple repos to fix that. Agile would solve that issue.

Which part of the editor should "normalize" the config if we went with Agile?

**Comment by Reinmar** [comment]
The config is immutable, so nothing should do it "in place". We can have a util like `ui/toolbar/gettoolbarconfig.js`

**Comment by oleq** [comment]
`gettoolbarconfig.js` has become a static method of `ToolbarView`. And actually, it's a config->factory converter and knows nothing about `editor.config` – it accepts the config value. It's not relevant in the context of this discussion.

What we need is an util that translates 
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ]
}  );
```
into 
```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePreset ],
	toolbar: {
		items: [ 'headings', 'bold', 'italic', 'link', 'unlink', ... ],
	}
}  );
```
and we have to use it across `ckeditor5-editor-*` packages, not `ckeditor5-ui`. Different editor iplementations use different toolbars (classic has `StickyT` and inline uses `BalloonPanelView`) so the information must be parsed and propagated down from the creator level.

**Comment by Reinmar** [comment]
TBH... I don't understand. 

> gettoolbarconfig.js has become a static method of ToolbarView.

?

**Comment by oleq** [comment]
See https://github.com/ckeditor/ckeditor5-ui/blob/master/src/toolbar/toolbarview.js#L116-L133.

**Comment by Reinmar** [comment]
That's "fillFromConfig" which is something completely different than normalizing the config.

**Comment by oleq** [comment]
Just FYI: I included the utility in https://github.com/ckeditor/ckeditor5-ui/issues/277.

**Comment by Reinmar** [comment]
Introduced in ckeditor/ckeditor5-ui#277.
