### ISSUE TITLE
Should commands enqueue their changes?

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#506]
I have a feeling that we had this discussion before. However, I have some doubts.

At the moment, all commands execute their changes in `enqueueChanges` block. This means that the developer has to only fire `editor.execute( '...' )` without remembering to use `document.enqueueChanges( () => { ... } )`. There might be also other advantages (please write if you remember any).

Most commands that we have now are pretty simple and are executed on user actions. Take `BoldCommand` for example. It is fired when user clicks an icon or presses <kbd>Ctrl + B</kbd>. If the command is enabled no additional checks need to be made. In `enqueueChanges` the command simply looks where bold can be applied and does it.

Now, there may be more complex command, for example, a command that adds or removes a specific marker. If the command enqueues changes on execute, it may happen, that when those changes are applied, the marker has been already removed and command fails:
```javascript
class RemoveMarkerCommand extends Command {
  ...
  execute( markerName ) {
    if ( this.editor.document.markers.has( markerName ) ) {
      this.editor.document.enqueueChanges( () => {
        this.editor.document.batch().removeMarker( markerName ); // *
      } );
    }
  }
  ...
}
```
```javascript
document.enqueueChanges( () => {
  editor.execute( 'removeCommand', 'myMarker' );
  editor.document.batch().removeMarker( 'myMarker' );
} );
```
In this case, line commented with `*` will throw, because at the moment of execution that line, the marker will be already gone.

Of course the example is simplified, but consider situation, when `RemoveCommand` is used in a callback to `model.Document#event:change` to fix some stuff. In this case the above scenario is very real.

What we can do?

We can secure the command in `enqueueChanges` block. It is easy in the `RemoveMarker` example - just move the `if` into `enqueueChanges` block. In other scenarios it might be more messy, because most commands operate on current selection. Selection at the moment of `execute()` and at the moment of `enqueueChanges` execution may differ. Of course, you can check the selection in `enqueueChanges` but this may mean that something is applied not as expected. Acutally, `AttributeCommand` and `ListCommand` check the selection ranges in `enqueueChanges` block.

We can remove `enqueueChanges` from commands. This way each time a command is used, developer would need to use `model.Document#enqueueChanges()` but we would have more control over how and when the command is executed.

WDYT?

**Comment by scofalik** [comment]
I haven't been aware that there is related issue: https://github.com/ckeditor/ckeditor5-engine/issues/654

**Comment by pjasiun** [comment]
I believe that the solution described there (https://github.com/ckeditor/ckeditor5-engine/issues/654#issuecomment-309746925) will solve this problem.

**Comment by Reinmar** [comment]
I agree with @pjasiun. We need to stop enqueuing the way we do. We'll still need to discuss the API (I'd try finding something easier than PJ's proposal) but in general, we can't have all these situations in our codebase – you must see how the code will get executed.

**Comment by pjasiun** [comment]
> We can remove enqueueChanges from commands. This way each time a command is used, developer would need to use model.Document#enqueueChanges() but we would have more control over how and when the command is executed.

This is not an option. `enqueueChanges` is the framework level function. `execute` is for people who take a build and want to use it without a deep architecture understanding. API for the should be as simple as possible.

**Comment by Reinmar** [comment]
I'd close this ticket (because https://github.com/ckeditor/ckeditor5/issues/506#issuecomment-316927091 explains what's not an option so it also explains what we need to do) and continue in ckeditor/ckeditor5-engine#654.

**Comment by scofalik** [comment]
Okay I am fine with closing this issue. I'll continue in the related issue.
