### ISSUE TITLE
Fix branches coverage summary

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#51]
Because of the building we have one branch not covered in every file. Because of it, it is hard to check if all other branches are covered (each file has 75% - 98%, depending on the number of tests). Even if we will not be able to remove that line, it would be useful to ignore it in the coverage or fix the summary.

**Comment by Reinmar** [comment]
This will not be a problem any more once Istanbul 1.0 is released (https://github.com/gotwarlost/istanbul/issues/212).

Before that... we would need to fork Babel modules and put a special comments in the helper templates. We'll need to fork them anyway, so perhaps we could also do this.

**Comment by Reinmar** [comment]
In fact, we have this hotfixed by adding an ignore comment: https://github.com/ckeditor/ckeditor5/blob/78d789ea98b87c5db91bc2242c2a1d1dc02521e5/dev/tasks/build/utils.js#L153

It's fine for now, so I'm closing this ticket.
