### ISSUE TITLE
[Docs] Missing screenshots

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#510]
https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/overview.html

- [x] Classic editor
- [x] Inline editor
- [ ] Balloon editor

https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/whats-new.html
- [x] Animated GIF of pasting images
- [x] Animated GIF of DnD of images
- [x] <del>Animated GIF of using image styles</del> - we'll use a screenshot for now
- [x] Screenshot of a link with the edit balloon on it
- [x] Animated GIF with auto formatting in action
- [x] Animated GIF with the behavior of classic editor toolbar when scrolling
- [x] Animated GIF of classic editor growing when typing
- [x] Screenshot of the toolbar of classic (article) editor with toolbar with less features - perhaps add CKEditor 4 full screenshot for comparison?

**Comment by AnnaTomanek** [comment]
Note: do we want to consider adding a border around the images like "Screenshot of a link with the edit balloon on it"? With the same font being used as in the docs this is confusing as it does not look like an image with an example at first.

**Comment by Reinmar** [comment]
Yeah, this is true. @oleq, could you try to style images in Umberto in some "free time"? :D

**Comment by oleq** [comment]
> in some "free time"

I don't recognize this idiom 💤

**Comment by Reinmar** [comment]
Don't forget to replace:

```
[ TODO Animated GIF of Letters and collaboration ]
```

With a screenshot of Letters.

PS. To make it simpler for you – I think that all gifs are here: /builds/guides/whats-new.html

**Comment by AnnaTomanek** [comment]
Image styles - for now we decided to use a screenshot, to be replaced with a screencast after we create the Image styles feature guide from #584.

**Comment by oleq** [comment]
> Yeah, this is true. @oleq, could you try to style images in Umberto in some "free time"? :D

@Reinmar Done along with iframe styles for embeds. Wait for new umberto in npm.

**Comment by fredck** [comment]
There is still one TODO in the page. It's not critical, so we can remove the line from there at least:

[ TODO Animated GIF of image being inserted and how it looks like in a smartphone and desktop ]
