### ISSUE TITLE
[Docs] Missing content

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#511]
- [x] [PK] A list of CKEditor 5 configuration options. (done: fb338685)
- [x] [PK] Browser Compatibility (reference: http://docs.ckeditor.com/#!/guide/dev_browsers). Dedicated page, must have. (done: 5d3747a)
- [x] [AT] Starting page for Builds.
- [x] [AT] Starting page for Framework.
- [x] [PK] Starting page for API documentation (list most useful entry points, like links to 
ClassicEditor class, some Guides about the API; take inspiration from [Popular API Pages](http://docs.ckeditor.com/)).
- [x] [PK] [Builds: Guides -> Overview] Describe editor implementation with a balloon toolbar (done: 062ab66).
- [x] [PK] [Builds: Guides -> Overview] Mention that builds, including the toolbar configuration, can be adjusted through configuration (linking to related doc). Right now one can have a feeling that the only way to do so is through Custom builds (done: 062ab66).
- [ ] [PK] Guides about events in CKEditor 5. For users with CKEditor experience it will be confusing that there are no events listed e.g. in the ClassicEditor class. See e.g. https://github.com/ckeditor/ckeditor5/issues/710. We need more examples too.
- [x] [PK] Improved API docs for the existing creators and links between creators and other resources about them (builds overview).
- [x] ~"*When NOT to use CKEditor 5 Builds*" page, referenced in "Guides -> Migration"~ (last section in overview)
- [ ] [PK] Accessibility Support (reference: http://docs.ckeditor.com/#!/guide/dev_a11y). Nice to have, explain current and desired state.
- [x] [PK,WW] Add CKE5 to CDN Website (TODO link in Installation guide).
- [x] [PK] Quick Start presenting on how to run classic build from CDN with a full working example, as there is nothing more encouraging than being able to run a new application within minutes. Add reasonable [next steps](http://docs.ckeditor.com/#!/guide/dev_installation-section-next-steps) at the bottom.
- [x] [PK] Explain how one can easily check what is the toolbar definition of currently used build and mention it in builds/guides/integration/configuration.html#Toolbar-setup. As there is no "removeToolbarButon" option, one is forced to redefine the toolbar if a feature is removed.
- [x] [PK] [Builds: Guides -> ?] Explain how to integrate deeper by importing `@ckeditor/ckeditor5-build-classic/ckeditor`.

**Comment by Reinmar** [comment]
Doubts:

* where to put guides such as browser compatibility and events list because they make sense in builds and in the framework,
* it's hard to document config options because it's a sum of creator + features,
* it doesn't make sense to document the status of a11y because we only touched keyboard support and nothing else,
* I'd like to prioritise these items.

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5/issues/710 proved that we need the guide about events.

**Comment by oleq** [comment]
Not sure if the right issue, but [this](https://github.com/ckeditor/ckeditor5-ui/issues/348) should be done sooner or later too.

**Comment by AnnaTomanek** [comment]
From an issue reported by @pjasiun in our internal website tracker:

> Also, I think we could put more in the "Features" list in the documentation:
>* react and angular integrations,
>* multiple languages support,
>* paste from Word and other "Working on!" features.

>I think the "Features" page in the documentation should be a place when a visitor can see how powerful and flexible our solution is and we should gather there everything what he can consider as "feature" there.

**Comment by godai78** [comment]
I think we could at least mention 508 in the Keyboard support guide, it would show we strive toward this goal and it would come up in search.
