### ISSUE TITLE
Image should re-render view on load

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5118]
[edited]
Sometimes the source of the image element is loaded async and this causes layout change. We need to reposition UI attached to the content then.

E.g. Image element is rendered in the DOM after pressing `Start external changes` but image is heavy and we need to wait a couple of seconds to see the source of the image. The image is loaded but UI is in the old position because its its update was not triggered:
![sep-25-2017 11-40-19](https://user-images.githubusercontent.com/1057056/30802340-79546a74-a1e6-11e7-9868-ef99882a7d18.gif)

**Comment by Isaacn123** [comment]
am getting this empty Tags 
<figure class="image"><img></figure>
