### ISSUE TITLE
[Docs] Build examples

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#512]
Right now our plan is to have six examples for builds: three presenting builds in exactly the same form as users will get them, and three that we will demo on our website, with some slight modifications. 

Let's see how different the example setups will be from "plain" examples to understand how to structure/name precisely the examples.

### Plain examples
- [ ] Classic (description missing, content missing)
- [ ] Inline (description missing, content missing)
- [ ] Balloon toolbar (missing)

### Customized setups
- [ ] Classic (missing)
- [ ] Inline (missing)
- [ ] Balloon toolbar (missing)

As a complementary documentation we also may need to create a dedicated entry in CKEditor Guides (see [Example CKEditor 4 Setups](http://docs.ckeditor.com/#!/guide/dev_example_setups) as a reference), depending on how heavy the modifications in demos will be. In short, the examples may/should include a bit of introduction, so that users could easily use similar setups in their web applications. However examples should not start with a wall of text, because it makes browsing samples much harder. If we end up with walls of text, we will need to create an entry in Guides for that.

**Comment by Reinmar** [comment]
I need a help with writing some descriptions of these examples. E.g. a list of things that I should mention.

**Comment by wwalc** [comment]
Yeah, let's wait for the demos to be really finished. Then let's get back to this. In fact I may try to handle this.

**Comment by Reinmar** [comment]
What's the status of this? We have 3 examples but to which category they fall into? What's still missing?

**Comment by wwalc** [comment]
Current status:
 * Demos are okay but the content in CKEditor needs to be still updated.
 * We will have just three samples as we have now because we did not make any drastic modifications to builds apart form changing the configuration in one example.
 * The description above editors needs to be enhanced (addding one paragraph of text, or two in case of inline editor as we used custom image styles there). Me or @AnnaTomanek will do this.

**Comment by Reinmar** [comment]
> Demos are okay but the content in CKEditor needs to be still updated.

This was done in f577f97.

**Comment by Reinmar** [comment]
I'll move this ticket to the next iteration so we can decide what we want to do with these examples.

**Comment by Reinmar** [comment]
I also mentioned that the config was modified: d3e5a7e.

So, in fact, I'll split this ticket in two parts - simple examples (done) and customised examples (todo).

**Comment by Reinmar** [comment]
Followup https://github.com/ckeditor/ckeditor5/issues/583.
