### ISSUE TITLE
[FF] Image toolbar's position is incorrect after pasting the image at the beginning of the document

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#5135]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-easy-image/tests/manual/easyimage.html.
2. Upload the image.
3. Cut/copy it.
4. Paste it at the beginning of the document.

## Expected result
The image toolbar shows up below the image.

## Current result
The image toolbar shows up on the image.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/35678346-41b40e62-0753-11e8-8051-0ed04b8ebff9.gif)

## Other information
OS: All platforms
Browser: Firefox
Release: Latest master

**Comment by FilipTokarski** [comment]
I'm not able to reproduce the original issue - everytime after pasting the toolbar shows correctly below the image. I guess we can close this one.
