### ISSUE TITLE
Setting image height and width

### ISSUE THREAD

**Issue by olup** [ckeditor/ckeditor5#5154]
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 📃 Other details that might be useful

Hi ! Thanks for the very well designed ckeditor 5 and its image plugin. I have two / three questions that can be interpreted as feature requests.

Many front end, including mine, actually uses images parameters sizes to build progressive loading, placeholders, etc... We love our non-jumping image process, and for that it is critical that height and width are hardcoded in the img tag (indeed, only to compute an aspect ratio). From what I can understand in the image plugin code only url and alt and styles are setable on the image bloc object. Would it be possible to consider adding those parameters, or is it something i should extend myself (I am not talking PR but adding a plugin on top of this one) ? 

Finally, something that don't really belong here, but i cannot find any equivalent plugin to manage embed (like a youtube video) in the editor.
Is there work allready in this direction or is it uncharted territory ?

Cheers.

**Comment by tuannd255** [comment]
@Reinmar So sorry. I have a error for ckeditor5-image (lib in ckeditor5-react) in resize function (bellow video). Step:
1. Upload image 
2. Resize Image
Issues: 
- Image alway scale to 100% width
Expect:
- Image can resize
Please help me this error. Thank you!
Link video issues:
https://drive.google.com/file/d/1sqq3j7O2AAlCN_C2LaFxB2ysfjtBYScn/view?usp=sharing

**Comment by rhysstubbs** [comment]
I also need this feature.

Was it implemented? Some of the comments above are talking about image resizing etc. but I don't think that was what the OP was asking about.

Happy to write my own plugin... but it'd be amazing if someone has already done this ;)!?

**Comment by neongreen** [comment]
> We love our non-jumping image process, and for that it is critical that height and width are hardcoded in the img tag

Agreed. Otherwise we see jumps like this, which are very jarring if the image loads slowly:

<img src="https://user-images.githubusercontent.com/1523306/100135557-7bad7400-2e92-11eb-977c-3827ca29c751.gif" width=50%>

**Comment by Reinmar** [comment]
Related issue: #8663.

**Comment by wimleers** [comment]
I do not understand how this is related to #8663. Could you elaborate? 😊 🙏

**Comment by Reinmar** [comment]
Currently, CKE5 does support `width` but AFAICS only if it's paired with `sizes` or something similar. E.g. the `width` attribute will be output when an image was pasted into the editor (from file). Additionally, with `ImageResize` present, the `width` inline style present on `figure` is also handled.

#8663 is about backward compat with CKE4 and we'll need to work in it on different notations of similar things. So if CKE4 could've output something, it will need to be handled in CKE5 as well.

**Comment by tomitrescak** [comment]
Hello, will the height setting be possible since that functionality has been implemented? This is important for SVG source of images. Currently, when you insert image and set SVG as its source, the height is capped at 150px, beyond which it is not possible to resize the image, making the scalability an issue. I spent already a week on this but cannot find a way out beyond manually setting the height and width of the image.

**Comment by SazanYa** [comment]
This feature is needed by many people, especially for creating emails. Outlook and Windows 10 Mail rendering engine doesn’t understand the style attribute on <img> elements. So we need to define a width attribute for correct displaying. And it would be nice if ImageResize plugin allowed us to set image sizes using this attributes.

**Comment by suracekumar632** [comment]
![pexels-cottonbro-4761788](https://user-images.githubusercontent.com/100569625/178406974-59f75af9-9fb6-4f0a-b5e1-221f0224a513.jpg)

**Comment by suracekumar632** [comment]
![pexels-cottonbro-4761788](https://user-images.githubusercontent.com/100569625/178407363-36e41971-ece2-47ae-b110-68ae6045bae3.jpg)

**Comment by jc-harbour** [comment]
Bump on this, `img` tags are getting `width` and `height` stripped from the rendered `img` tag. Any update on this?

**Comment by wimleers** [comment]
This has been reported as a bug against Drupal too now: https://www.drupal.org/project/drupal/issues/3336446#comment-14888366.

This bug has been known for a while now — is it really so complicated to fix? 😅

**Comment by KlemenDEV** [comment]
It would be really nice to have this fixed, agree. We and our users love CKE5 on our websites, but the CLS score has been hit quite severely on some of our pages due to the arguments missing.

**Comment by leevigraham** [comment]
I'm working on an image-dimensions plugin. Just have to hook up the observable properties. 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/25124/218305867-172cdfd6-1c49-421e-92f6-28e5bac24311.png">

**Comment by wimleers** [comment]
@leevigraham Could you share the code? 😊 🙏

**Comment by leevigraham** [comment]
@wimleers I didn't get much further than the screenshot above.

**Comment by Witoso** [comment]
We are taking a look at this, if anyone wants to check the status, observe the https://github.com/ckeditor/ckeditor5/issues/14146 and its subtasks.

**Comment by Witoso** [comment]
The implementation is close to completion, but we would love to hear some feedback. [The details are gathered in the comment.](https://github.com/ckeditor/ckeditor5/issues/14146#issuecomment-1632607316)

**Comment by Witoso** [comment]
:tada: This feature was merged to the `master` and is available on the [nightly releases](https://github.com/ckeditor/ckeditor5/issues/14724) and [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) to test.

[In a comment in another issue](This feature was merged to the master and is available on nightly releases and nightly docs to test.  More details of what was implemented can be found in the comment in another issue.), you can find more details about the changes.
