### ISSUE TITLE
"Enter image caption" placeholder shows up when clicking the caption–less image in read–only mode

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5168]
1. Go to http://localhost:8125/ckeditor5-image/tests/manual/caption.html
2. `editor.isReadOnly = true`
3. Click an image without a caption.

**Expected**: Nothing happens

**Actual**: The placeholder shows up and you can't use it.

![image](https://user-images.githubusercontent.com/1099479/48058616-27ee6600-e1b7-11e8-9524-f511cff3a36e.png)

**Comment by anuradhawick** [comment]
What is the current status of this bug? I am having the same problem and it looks a bit confusing on the read-only plane.
