### ISSUE TITLE
Image srcset on custom media insert

### ISSUE THREAD

**Issue by dannybarinshtein** [ckeditor/ckeditor5#5179]
Hello,

I am using the editor API to insert images from a custom built media library.

I have the following snippet:

```
editor.model.change(writer => {
	const imageElement = writer.createElement("image", {
		src: imageUrl,
		alt: alt
	});

	editor.model.insertContent(
		imageElement,
		editor.model.document.selection
	);
});
```

The only thing I can't figure out is how to add srcset to it.. I read a few closed issues where it says srcset requires sizes as well, or that the srcset attribute has been changed to responsive with the srcset and sizes being attributes inside of it.

Is there a better approach to image insertion here? Or am I missing something else?

Any assistance would be greatly appreciated.

**Comment by ZakaGn** [comment]
Hi, i have the same problem, i have tried :

```
let Att=[];
Att["src"] = 'https://placehold.it/350x150';
Att["srcset"] = {"data" : "https://placehold.it/350x150 350w, https://placehold.it/950x150 950w", "width" : 950};
editor.model.change(writer => {insertImage(writer, editor.model, Att);});
```

but i cant get is working, is that format correct ?

i only get:

`<figure class="image ck-widget" contenteditable="false"><img></figure>`

**Comment by ZakaGn** [comment]
Well that was my error again, fixed by changing:
`Att = {}`
