### ISSUE TITLE
Image feature guide should be simplified

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5192]
## Is this a bug report or feature request?

📃 Docs

## 💻 Version of CKEditor

CKEditor v5 @ 12.4.0

## 📋 Steps to reproduce

With addition of image resizer in 12.4.0 I feel like the image sample has way too much content in it.

There's a good chance that no one will get to "Responsive images" section.

As a quick and cheap solution we could turn image into a category, similarly like we have "Paste from office" and "Image upload".

I'd love to hear some opinions on that.

**Comment by godai78** [comment]
I'll take this on, but will surely need some assistance on the way.

**Comment by godai78** [comment]
![](https://user-images.githubusercontent.com/68123541/100729034-8f903300-33c8-11eb-98b4-8ddb8372318c.png)

This is the suggested cut for a new structure. Linking images went to basic image support, but I won't fight moving it into it's own separate guide.

**Comment by AnnaTomanek** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/5117

**Comment by godai78** [comment]
Let's thaw this after the release.

**Comment by AnnaTomanek** [comment]
Closing this issue in favor of https://github.com/ckeditor/ckeditor5/issues/8591 as we are pushing all changes to the PR linked there. The effort done so far is accounted for in this issue.
