### ISSUE TITLE
Image changes size after clicking on resize handler 

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#5195]
After clicking on a image resize handler, the image changes its size.

![resize](https://user-images.githubusercontent.com/20988892/63408486-763fbf00-c3ef-11e9-9220-b7b206a32bb8.gif)

---

If you'd like to see this fixed sooner, add 👍 to this post.

**Comment by oleq** [comment]
Bumped again into this one. It's pretty annoying I must admit. Is it hard to fix?

**Comment by mlewand** [comment]
Shouldn't be. There's a slight chance that it's related to #5189 so hopefully we could fix both at once.
