### ISSUE TITLE
contrary Tooltip for Full Size for Image with Resizing Plugin

### ISSUE THREAD

**Issue by MCMicS** [ckeditor/ckeditor5#5203]
The tooltip for full Size style for images with ImageResize Plugin is contrary.
The tooltip says "Full Size image" even if the image was resized.

**Possibilities**

- Restore the original size if this setting is used (see https://github.com/ckeditor/ckeditor5-image/issues/318)
- map it to alignCenter style
- change tooltip to e.g.: Disable Text warp
This is something like disable floating within HTML or prevent text wraps around objects.

![grafik](https://user-images.githubusercontent.com/4604206/64198065-d6bb0b80-ce87-11e9-8971-7b4d84c0c93f.png)

**Comment by Reinmar** [comment]
I decided to make a step back and look at the options to see the big picture. I wrote down my thoughts in #7560. It seems that we need a bit bigger changes.
