### ISSUE TITLE
Edit in WYSIWYG mode but output Markdown format

### ISSUE THREAD

**Issue by amkgo** [ckeditor/ckeditor5#522]
I want to create a webpage that users can write technical documents using CKEditor 5 in WYSIWYG mode. They don't understand markdown syntax.
Is it possible to use  https://github.com/ckeditor/ckeditor5-markdown-gfm plug-in in CKEditor 5 to edit the contents in WYSIWYG mode but get the result data in Markdown format?

Thanks,
Andrew

**Comment by Reinmar** [comment]
Hey,

I've just created a simple guide on how to enable this Markdown data processor. It's not yet available on the [docs nightly build](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/index.html), but you can see its source here:

https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/master/docs/features/markdown.md

And the source file used for the demo: 

https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/master/docs/_snippets/features/markdown.js

The demo looks for me like this:

![image](https://user-images.githubusercontent.com/156149/29710136-61c41388-898f-11e7-873e-e5340459bad5.png)

The guide will be available online on the [Features page](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/index.html) in ~3h.

**Comment by Reinmar** [comment]
I'll close this ticket as the documentation now answers your question. But if anything is unclear, please let us know (you can comment in this thread).

**Comment by amkgo** [comment]
This is great. Thanks.

**Comment by Reinmar** [comment]
The guide is already available here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/markdown.html
