### ISSUE TITLE
[Chrome] The image duplicates after pressing Enter

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#531]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html.
2. Drag the selection over the image starting from the block quote.
3. Press <kbd>Enter</kbd>.

## Current
New image appears below the original one.

## Notes
- It's reproducible when the image is set to the `side image`.
- It's reproducible only if the selection starts in the block element which is below the image.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/32177316-4e4ff388-bd8a-11e7-8197-d0cb8690d2e7.gif)

## Other information
OS: Windows 10
Browser: Chrome, Opera
Release: 1.0.0-Alpha1

**Comment by Mgsy** [comment]
I checked this issue once again and it's reproducible also on Chrome and Opera (probably because of https://github.com/ckeditor/ckeditor5-image/issues/19). Follow the scenario from https://github.com/ckeditor/ckeditor5/issues/489 to insert a filler, then press <kbd>Enter</kbd>. New image will appear.

![bug_cke5](https://user-images.githubusercontent.com/20988892/31765863-24860e88-b4c6-11e7-8e63-5c84baf941cd.gif)

**Comment by pjasiun** [comment]
We met this problem multiple times, but we were not able to reproduce it. That's great you find a scenario.

**Comment by Mgsy** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/pull/1173.

**Comment by Mgsy** [comment]
Unfortunately, I have to re-open this issue. I managed to reproduce it again, but only on Chrome and Opera. After dragging the selection over the image, the selection disappears, user isn't able to type, but after pressing <kbd>Enter</kbd>, the image duplicates. I'm updating the scenario.

**Comment by Mgsy** [comment]
It's fixed.
