### ISSUE TITLE
New block quote appears after pressing Enter inside the empty block quote

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#532]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html.
2. Select the content inside the block quote.
3. Press <kbd>Backspace</kbd> twice.
4. Put the caret at the empty block quote.
5. Press <kbd>Enter</kbd>.

## Current result
New block quote appeared. 

## Notes
This bug is reproducible only if the image was inserted above the block quote.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/29766617-ad678854-8bdf-11e7-9e31-81f129833b40.gif)

## Other information
OS: Windows 10, MacOS X
Browser: All browsers
Release: 0.10.0

**Comment by Reinmar** [comment]
We're left with a blockquote without a paragraph inside. This may be a bug in the `deleteContent()`' "delete all content handling".

**Comment by scofalik** [comment]
This is probably a regression right? I am pretty sure we have tested that scenario.

**Comment by Reinmar** [comment]
This is a new code in `deleteContent()` and the typing feature, so it seems to introduce a regression.

**Comment by pomek** [comment]
> This is a new code in deleteContent() and the typing feature, so it seems to introduce a regression.

And this bug still occurs. Even if the introduced code will be disabled:

![image](https://user-images.githubusercontent.com/2270764/29921718-f50c27d0-8e52-11e7-8814-20b6e4b1acaf.png)

**Comment by Reinmar** [comment]
Hm... Surprise. I can confirm that it's old – reproducible on ckeditor5.github.io. So no pressure on fixing it – it requires pressing backspace twice and in a specific condition (when image precedes a blockquote).

It might be a bug in ckeditor5-widget's backspace handler or somewhere deep in `deleteContent()`.

**Comment by pomek** [comment]
When I replace this block – https://github.com/ckeditor/ckeditor5-widget/blob/master/src/widget.js#L171-L174

with

```js
if ( previousNode.isEmpty ) {
	const dataController = this.editor.data;
	const batch = modelDocument.batch();

	dataController.deleteContent( modelSelection, batch );
}
```

I am not able to reproduce this issue. Unfortunately, two tests fail. Here is my question – could we fix the tests or isn't my proposition valid?

**Comment by Reinmar** [comment]
And how are we supposed to answer if you haven't shown us these tests?

Besides, try understanding the cause. You're talking about the code all the time, replacing one code with another. But to propose a correct solution you need to understand what should be the correct solution. Code comes next.

**Comment by pomek** [comment]
@Mgsy, we resolved an issue which can fix the reported bug.

Could you check it once again?

**Comment by Mgsy** [comment]
@pomek: I checked it and everything works fine, thanks. I'm closing this issue.
