### ISSUE TITLE
Unnecessary information in "Browser compatibility"

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#533]
The [Browser compatibility](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/browser-compatibility.html) guide groups browsers in "Close to full support" just because of missing features of the editor. This is misleading because there may be always missing features but those are not the ones that tell if there is compatibility with a browser more than with another.

The browsers in that group are instead our "full support" browsers. Those are the browsers that we'll be focused on when developing and testing.

Associating missing features to browser compatibility seems to be wrong and misleading.

**Comment by Reinmar** [comment]
But it'd be good to mention the missing features anyway. For us they are missing features, for some people will be complete blockers (inability to type).

So, would it be fine to just remove the "close to" part? And leave the notes as they are now?

**Comment by fredck** [comment]
Shouldn't they look at the open issues instead? Hard to say which features are important for users and listing them in the "compatibility" page doesn't sound right.

**Comment by Reinmar** [comment]
> Shouldn't they look at the open issues instead? Hard to say which features are important for users and listing them in the "compatibility" page doesn't sound right.

IME is not a typical feature. It's a basic way of inputting text. Lack of full support for IME is something else than lack of support for tables.

This way, we could write that we support everything, just look for tickets about missing features ;) Custom mobile UI and better support for touch are kind of features themselves. So do we have a full mobile support with just a missing features that the users should find by themselves? I thought that this guide is supposed to bring information about the status of things so I wrote the important things down.

**Comment by Reinmar** [comment]
OK, I changed the wording a bit. If you feel that it's still bad feel free to change it.
