### ISSUE TITLE
[Docs] Do something with build samples

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#535]
Every build has its `sample/index.html`. We need to decide whether we want to keep those and if so, improve them (e.g. use some generic, future-proof content).

**Comment by Reinmar** [comment]
cc @wwalc

**Comment by Reinmar** [comment]
For now, these samples are not published on npm, so they are available only in the repository.

**Comment by wwalc** [comment]
I believe we might want to bundle such sample when distributing builds as zip packages. We haven't decided yet what the structure of a zip file should be, but for the end users such included sample should be useful. It would make discovering on how to run the editor a no-brainer and would let users get a taste of it, without even having to look at the documentation. 

So: 👍  for making the content of a sample future proof and generic.

**Comment by Reinmar** [comment]
> The sample should not load any image - I was wondering if not to load something from CDN instead of "../tests/manual/sample.jpg, but not loading any resource would make it fully working without the internet connection.

I think that when you're offline you will accept and understand the fact that an image doesn't load. So using CDN makes sense for me.

**Comment by Reinmar** [comment]
> If we include the sample in the zip package, we should possibly fix the path to the build file:

?

It's exactly this now:

```
<script src="../build/ckeditor.js"></script>
```

**Comment by wwalc** [comment]
> ?
> 
> It's exactly this now:
> 
> <script src="../build/ckeditor.js"></script>

Ignore this, nvm. What I meant there that **depending on the structure of the zip package** (https://github.com/ckeditor/ckeditor5/issues/541) it may or **may not** be okay.

**Comment by pomek** [comment]
Guys, could you provide some URL which we can use in the sample?

**Comment by wwalc** [comment]
I think this issue can be closed as we decided not to include any sample in distributed zip packages. The included README file will serve as a starting point for anyone starting his journey with CKEditor.

**Comment by Reinmar** [comment]
The file is useful when rebuilding an editor (it lets you quickly validate the result). So it makes perfect sense to keep it in the repos. Of course, it won't be published on npm or in zip packages, but as we know this is a completely different set of files anyway.

So, I'll make some cleanup in this files and leave it there on GH.

**Comment by Reinmar** [comment]
I improved the files and mentioned that they can be used in 1506584.
