### ISSUE TITLE
ContextualToolbar should be not displayed when all components inside are disabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5388]
This will automatically turn off CT when the editor will be in read-only mode (see read-only requirements https://github.com/ckeditor/ckeditor5/issues/492). And this might be a nice way to disable toolbar for specific elements.

**Comment by AlexBlack772** [comment]
this code `if ( Array.from( this.toolbarView.items ).every( item => item.isEnabled !== undefined && !item.isEnabled ) ) {
			return;
		}`

doesn't work as expected if we add separator in toolbar menu

`	toolbar: {
		items: [
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'|',   <----------- Problem is here
			'link'
		]
	},`
