### ISSUE TITLE
[Docs] Create meaningful README.md in CKEditor 5 "editor" repositories

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#539]
When going through CKEditor 5 repositories one may get lost or at least spend too much time on discovering something that should be well-explained, what's the purpose of each repository and if its "useful" or not. Right now the first impression that one may get is that the whole ecosystem is quite confusing.

Take for example the inline editor. One can easily be redirected from google to https://github.com/ckeditor/ckeditor5-editor-inline

What's I'm missing there is:
 - A cross link to a place that explains what is an inline editor from the end user perspective (e.g. https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/overview.html#Inline-editor, hopefully it will be extended with time)
 - An information & example on how this repo can be used and what precisely it contains, one can be surprised that something called "an editor" is in fact a low-level thing, which is quite useless unless features are added to it
 - An information that if one is looking for a ready to use inline editor, he should rather look into CKEditor 5 inline editor build.

Instead of putting the whole information in README.md I believe that this info could be added here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_editor-inline_inlineeditor-InlineEditor.html and could be just linked in README.md.

**Comment by Reinmar** [comment]
Hm... I haven't actually read what you wrote before doing changes, but it seems that I had very similar ideas :D.

See: 

* ckeditor/ckeditor5-editor-classic@f0dc8d5
* ckeditor/ckeditor5-editor-inline@560dee3
* ckeditor/ckeditor5-editor-balloon@4f19a24
