### ISSUE TITLE
[Docs] Move docs about setting up the development environment to the documentation website

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#540]
The following article: [Development environment](https://github.com/ckeditor/ckeditor5/wiki/Development-Environment) should be ported to the documentation website. The reasoning is that the documentation should not be fragmented in multiple locations and that such article should appear in search results on the documentation website.

**Comment by Reinmar** [comment]
Done:

* https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/contributing/development-environment.html
* https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/contributing/testing-environment.html
* https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support.html
