### ISSUE TITLE
ContextualToolbar doesn't respect viewportTopOffset

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#5412]
Just like the StickyToolbarView, ContextualToolbar should use `viewportTopOffset` to calculate the position of the toolbar and avoid displaying it above (or bellow) page elements that define top boundaries.

This happens in the documentation, for example:

![image](https://user-images.githubusercontent.com/630060/30975847-8ec1d45c-a473-11e7-86c4-7f0a043309e7.png)

**Comment by dawidurbanski** [comment]
It's a duplicate of https://github.com/ckeditor/ckeditor5/issues/9892
