### ISSUE TITLE
A bit confusing syntax required for RequireJS

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#545]
While playing with RequireJS and CKEditor 5 to validate the [API docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/basic-api.html) I found that using CKEditor is quite counterintuitive:

https://github.com/wwalc/ckeditor5-test-requirejs/blob/master/scripts/app/main.js#L4

In short, the following code works:
```
	const ClassicEditor = require( 'ckeditor' );

	ClassicEditor.ClassicEditor
		.create( document.querySelector( '#text-editor' ) )
```

I was expecting something like
```
	const ClassicEditor = require( 'ckeditor' );

	ClassicEditor
		.create( document.querySelector( '#text-editor' ) )
```

**Comment by Reinmar** [comment]
The least confusing way to import would be this:

```js
	const ClassicEditor = require( 'ckeditor' ).ClassicEditor;
```

I thought that it's not possible, but it turns out that it is, to turn just one export of a module into a library. Right now, we're wrapping the entire module, so `require( 'ckeditor' )` gives you the module object. I pushed an example how we can change Webpack configuration to [`proper-export`](https://github.com/ckeditor/ckeditor5-build-classic/compare/proper-export). It seems to  work and will make this correct:

```js
// In CommonJS environment.
const ClassicEditor = require( '@ckeditor/ckeditor5-build-classic/build/ckeditor.js' );
ClassicEditor.create; // [Function]

// If AMD is present, you can do this.
require( '/(ckeditor path)/build/ckeditor.js', ClassicEditor => {
    ClassicEditor.create; // [Function]
} );

// As a global.
ClassicEditor.create; // [Function]

// As an ES6 module (if using webpack or Rollup).
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';
ClassicEditor.create; // [Function]
```

**Comment by Reinmar** [comment]
Nope, one correction:

```js
// In CommonJS environment.
const ClassicEditor = require( '@ckeditor/ckeditor5-build-classic/build/ckeditor.js' ).default;
ClassicEditor.create; // [Function]
```

**Comment by Reinmar** [comment]
And you'd need to validate Requirejs, @wwalc.

**Comment by Reinmar** [comment]
If the AMD case will be fine, then I'd only check how we can get rid of that `default` in case of CJS ;\

**Comment by wwalc** [comment]
@Reinmar `proper-export@ce22096` gave me the following results with RequireJS:

`build/ckeditor.js` taken as is from `proper-export` requires this syntax (with `.default` added):
```
define(function (require) {
	const ClassicEditor = require( 'ckeditor' ).default;

	ClassicEditor
		.create( document.querySelector( '#text-editor' ) );
...
```

However, when I rebuilt editor by myself from the `proper-export` branch with `npm run build-ckeditor` I got the right (?) result (note: I checked just RequireJS):
```
define(function (require) {
	const ClassicEditor = require( 'ckeditor' );

	ClassicEditor
		.create( document.querySelector( '#text-editor' ) );
...
```

The funniest thing happened when I run `npm run build` to rebuild CKEditor, it stopped working completely with RequireJS:
```
define(function (require) {
	const ClassicEditor = require( 'ckeditor' );
	console.log(ClassicEditor); // undefined
...
```

**Comment by Reinmar** [comment]
> The funniest thing happened when I run npm run build to rebuild CKEditor, it stopped working completely with RequireJS:

`npm run build` resets the `ckeditor.js` to its initial state so it reverts part of the changes.

**Comment by Reinmar** [comment]
Changed in:

* https://github.com/ckeditor/ckeditor5-build-balloon-toolbar/commit/599ab22d8e87b0726272e3b6ba018fcd0b8d65e4
* https://github.com/ckeditor/ckeditor5-build-inline/commit/5f64e7d3ccac992ea8877e8203d6f52527fa58cd
* https://github.com/ckeditor/ckeditor5-build-classic/commit/e5c7511f1f583ec3a394f336f075a3e875e00f12
