### ISSUE TITLE
React wrapper fails because of IconView._updateXMLContent()

### ISSUE THREAD

**Issue by lucasriondel** [ckeditor/ckeditor5#5457]
I'm trying to build a simple React (and Typescript) component wrapper for CKEditor and I'm facing the following issue: 

```
TypeError: Cannot read property 'getAttribute' of null
    at IconView._updateXMLContent (iconview.js:102)
    at IconView.render (iconview.js:76)
    at IconView.on (observablemixin.js:241)
    at IconView.fire (emittermixin.js:196)
    at IconView.(:8080/anonymous function) [as render] (http://localhost:8080/bundle.js:63966:16)
    at ViewCollection.on (viewcollection.js:68)
    at ViewCollection.fire (emittermixin.js:196)
    at ViewCollection.add (collection.js:182)
    at ButtonView.render (buttonview.js:160)
    at ButtonView.on (observablemixin.js:241)
```

There is the method's code : 

```
_updateXMLContent() {
		if ( this.content ) {
			const parsed = new DOMParser().parseFromString( this.content.trim(), 'image/svg+xml' );
			const svg = parsed.querySelector( 'svg' );
			const viewBox = svg.getAttribute( 'viewBox' );

			if ( viewBox ) {
				this.viewBox = viewBox;
			}

			this.element.innerHTML = '';

			while ( svg.childNodes.length > 0 ) {
				this.element.appendChild( svg.childNodes[ 0 ] );
			}
		}
	}
```
Here's my component (I am following the official [QuickStart guide](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html) and my webpack is correctly configured)

```
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials'
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph'
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold'
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic'

class CKEditor extends React.Component<{}, {}> {
  constructor(props) {
    super(props)
    }

  public componentDidMount() {
    ClassicEditor.create(ReactDOM.findDOMNode(this), {
      plugins: [Essentials, Paragraph, Bold, Italic],
      toolbar: ['bold', 'italic']
    })
      .then(editor => console.log(editor))
      .catch(e => console.error(e))
  }

  public render() {
    return (
      <div />
    )
  }
}

export default CKEditor
```

`this.content.trim()` value is `/6482730187d98b5f6ceab33ce6e275fe.svg`, which is really weird because I've tried to load CKEditor directly from the official CDN using [load-script](https://www.npmjs.com/package/load-script) ([like this implementation](https://github.com/codeslayer1/react-ckeditor/blob/master/src/ckeditor.js), unless i'm using CKEditor 5 which is why i'm not using this package), and it worked (if I don't specify `plugins` or `toolbar` properties), giving me a Classic Editor, and there `this.content.trim()` was giving HTML nodes instead of paths looking like strings.

Any idea ?

**Comment by BossBele** [comment]
I had this issue on NextJS, I can confirm the best way to work with CKEditor is using a custom build:

1. Use the [CKEditor online builder](https://ckeditor.com/ckeditor-5/online-builder/) to select the plugins that you want with your editor
2. Download the customized editor in the final step of the builder
3. Uncompressed the zip file
4. Place it in you repo the docs recommend to put it at the same level as you node_modules
5. Run yarn add file:./ckeditor5 (ckeditor5 is the default name of the uncompressed zip build)
6. Import the ck custom editor on your react app

Reference:
https://github.com/ckeditor/ckeditor5/issues/7376#issuecomment-802460193
