### ISSUE TITLE
[mostly FF] Painfully low balloon positioning performance in the document editor sample

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5468]
1. Go to https://docs.ckeditor.com/ckeditor5/latest/examples/builds/document-editor.html
2. Scroll the inner container.

![kapture 2018-06-19 at 12 28 44](https://user-images.githubusercontent.com/1099479/41592388-b1ccf10c-73bc-11e8-8b82-d334cc53ef5e.gif)

In FF it's quite obvious that the balloon does not catch up. Also visible in Chrome but not to that extent.

(likely) helpful article https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

**Comment by FilipTokarski** [comment]
Doesn't happen anymore. I think we can close this.
