### ISSUE TITLE
Define package keywords

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#551]
There are a couple of groups of packages:

* builds
* editor creators
* framework
* utils / API

It'd be good to mark each package with one or more keywords.

Right now we only marked builds, but with the `ckeditor5-build` keyword, which I think should be differently formatted, so we don't have `ckeditor5-creator`, `ckeditor5-framework` keywords (which might look like package names).

We need to check what kind of word separator we could use – maybe simply a space?

**Comment by Reinmar** [comment]
@pomek, could you make a quick research what kind of characters work in keywords and how similar (multi-package) projects use keywords? Like webpack, Babel, gulp, d3, etc.

**Comment by pomek** [comment]
#### Webpack

No `keywords` in `package.json`.

* [Webpack](https://github.com/webpack/webpack/blob/6b5ffa4d70b3d0e47c836196f217d8826604b723/package.json),
* [Webpack Style-Loader](https://github.com/webpack-contrib/style-loader/blob/378e90637f1c2c30bff026d7f92bdc82d9d4ecb8/package.json),
* [Webpack CSS-Loader](https://github.com/webpack-contrib/css-loader/blob/05c36db29bfcdbb1a3da50a8f7b9a20dbd929721/package.json).

#### Babel

The same like Webpack – no `keywords`:

* [Babel](https://github.com/babel/babel/blob/4c517a8912234b0b56d95fe8e294a2b45c8cae8f/package.json),
* [Babel-preset-es2017](https://github.com/babel/babel/blob/4c517a8912234b0b56d95fe8e294a2b45c8cae8f/packages/babel-preset-es2017/package.json),
* [Babel-preset-es2016](https://github.com/babel/babel/blob/4c517a8912234b0b56d95fe8e294a2b45c8cae8f/packages/babel-preset-es2016/package.json),
* [Babel-preset-es2015](https://github.com/babel/babel/blob/4c517a8912234b0b56d95fe8e294a2b45c8cae8f/packages/babel-preset-es2015/package.json).

#### Gulp

All plugins use a few words. The common one is `gulpplugin`:

* [Gulp](https://github.com/gulpjs/gulp/blob/c4d219e1a2318b9b4a3f921257818113cdd026dc/package.json),
* [Gulp-pug](https://github.com/pugjs/gulp-pug/blob/dd7dba14becb72618f865f8243ba9727f533d4db/package.json),
* [Gulp-if](https://github.com/robrich/gulp-if/blob/06c0b186a459f3e9f66c96b717c714cd12f56a29/package.json),
* [Gulp-rename](https://github.com/hparra/gulp-rename/blob/3b4fdf8a923934c762eac92cdde536d9b0acf173/package.json),
* [Gulp-eslint](https://github.com/adametry/gulp-eslint/blob/a3988386f0159516e7b56f38442d5f59ff57bf2c/package.json).


#### d3

The common keyword is `d3-module`:

* [d3](https://github.com/d3/d3/blob/41dad6467234c0decf68608a760e46a882d5b80e/package.json),
* [d3-queue](https://github.com/d3/d3-queue/blob/1d1353f628e7e5a1b20d8aec917eb44f0bd86fdc/package.json),
* [d3-shape](https://github.com/d3/d3-shape/blob/acb6053eae36fe6dcdb0b62fe2691bee2acc511b/package.json),
* [d3-hexbin](https://github.com/d3/d3-hexbin/blob/6d5c3e295f81975049e48a56866b87eb316c60d5/package.json).

#### Angular.js

No common keyword:

* [Angular.js](https://github.com/angular/angular.js/blob/6eb15cb1143cfbc291810708d6727c398878de17/package.json),
* [Angular new router](https://github.com/angular/router/blob/f642b4caad6501609182487ce5e7107d9876d912/package.json),
* [Angular-translate](https://github.com/angular-translate/angular-translate/blob/c7e743bb54b18f404e7ab5b91b88f842f144bbae/package.json).

Situation of `Angular` is similar to `Angular.js`

#### ESLint

Common keyword for plugins is `eslint`:

* [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser/blob/9c71a627da36e97da52ed2731d58509c952b67ae/package.json),
* [eslint-transforms](https://github.com/eslint/eslint-transforms/blob/1dc288b355e23f8c57ca724d88f810849d34dcf1/package.json),
* [eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown/blob/47ad3f9d1a5e96945b0544b254b2f7793bf91d1f/package.json).

**Comment by Reinmar** [comment]
Thanks!

**Comment by Reinmar** [comment]
OK, so I'd propose doing this

1. All packages should have "ckeditor5" keyword.
2. Additionally, specific groups can be marked:
* [core libs](https://github.com/ckeditor/ckeditor5#core-libraries) don't need to be marked because this set is closed,
* [editors](https://github.com/ckeditor/ckeditor5#editors) should be marked with "ckeditor5-editor",
* [features](https://github.com/ckeditor/ckeditor5#features) should be marked with "ckeditor5-feature",
* [themes](https://github.com/ckeditor/ckeditor5#themes) with "ckeditor5-theme",
* and [builds](https://github.com/ckeditor/ckeditor5#builds) are already marked with "ckeditor5-build".

WDYT?

**Comment by Reinmar** [comment]
OK, so with 2 👍 I'm going to introduce these keywords. However, in the meantime I thought that core libs could be marked with "ckeditor5-lib" anyway.

**Comment by Reinmar** [comment]
Done.
