### ISSUE TITLE
build-classic 0.4.0 and build-inline 0.2.0 undefined

### ISSUE THREAD

**Issue by CanRau** [ckeditor/ckeditor5#552]
hey guys..i already love your work a lot so far! congrats for this great program! 👍 

just wanted to use config.image.styles and wanted to move to inline build anyway so installed it..

i'm using it in a vue project with webpack 3.4.1

```
import { InlineEditor } from '@ckeditor/ckeditor5-build-inline/build/ckeditor'
InlineEditor.create(..)
```
throws, `Cannot read property 'create' of undefined`
and the same is true for classic build 0.4.0
0.2.0 and 0.3.0 work fine, even though without config.images.styles..which is not too big of an issue for now..

what else can i provide to help?

**Comment by Reinmar** [comment]
Hey, we've changed the build API a bit so I silently published new build releases... yesterday evening :D That's the changelog for the inline build: https://github.com/ckeditor/ckeditor5-build-inline/releases/tag/v0.2.0

Basically, you now need to import the default export:

```
import InlineEditor from '@ckeditor/ckeditor5-build-inline/build/ckeditor'
```

**Comment by Reinmar** [comment]
We also updated the documentation to match these changes (e.g. [here](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/basic-api.html#UMD-support) and [here](https://www.npmjs.com/package/@ckeditor/ckeditor5-build-inline)).

**Comment by Reinmar** [comment]
PS. I made this look kinda weird, so I need to explain myself – the new releases were published independently from the main project iteration because we knew that we'll also have to change the docs and since we only maintain nightly build of the docs now, people would be confused by that (new docs, old releases). So I decided to quickly release the new versions.

Sorry for the trouble!

**Comment by CanRau** [comment]
what that was really fast..could've figured it out myself by checking ckeditor.js a little more in detail..next time ;-)
now digging more into customizing builds as i realized it's not just throwing the config.image.styles object in place..but adding plugins and stuff..
love it! :D

m'kay...now i'm off playing on my own muchas gracis

just realized your 3rd answer..no sorry needed i'm totally good with such changes especially in alpha, beta, nightly stuff ;)

i've been a little tired, unpatient, lazy and trying to be the hero saving your lifes :p
