### ISSUE TITLE
Underline not working!

### ISSUE THREAD

**Issue by Espumisan** [ckeditor/ckeditor5#5561]
Hey, I'm using 
```
"@ckeditor/ckeditor5-basic-styles": "^11.0.0",
"@ckeditor/ckeditor5-build-classic": "^11.2.0",
"@ckeditor/ckeditor5-ckfinder": "^10.0.0",
"@ckeditor/ckeditor5-vue": "^1.0.0-beta.1",
```

And when I try to implement underline, it's just not adding up and I see warning:
```
toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable
 {name: "underline"}
```
Code: 
```
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold'
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline'

plugins: [Underline, Bold],

editorConfig: {
        toolbar: [ 'bold', 'underline' ]
      },
```
I see bold, but I don't see underline

p.s. icons are missing aswell

**Comment by gauravasrivastava** [comment]
I noticed the same issue with the React component of ckeditor5. "underline" option is not working. here is my snippet,
`<CKEditor
                    onInit={ editor => console.log( Array.from( editor.ui.componentFactory.names() ) ) }
                    onChange={ ( event, editor ) => console.log( { event, editor } ) }
                    config={ {
                        removePlugins: [ 'Heading' ],
                        toolbar: [ 'link', 'bold', 'italic', 'underline', 'bulletedList', 'numberedList' ]
                    } }
                    editor={ ClassicEditor }
                    data={response.get('text')}
                />`

**Comment by Mgsy** [comment]
@gauravasrivastava, did you add Underline plugin to your build? Keep in mind that it's not available by default, so it has to be installed manually. Also, can you see any errors in the console?

**Comment by Sawan1994** [comment]
@Mgsy New plugins are not getting added in react build provided by ckeditor 5. Can you share a working code via codepen etc for adding new plugins like font family, underline etc to react build of ckeditor5?

**Comment by Mgsy** [comment]
> [**@Mgsy**](https://github.com/Mgsy) New plugins are not getting added in react build provided by ckeditor 5. Can you share a working code via codepen etc for adding new plugins like font family, underline etc to react build of ckeditor5?

If you don't [build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source), you have to [prepare a custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds), then integrate it with React.

**Comment by farrvince** [comment]
Same error here: toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable - {name: "underline"

And I have the same error with multiple items:

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize:50"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize:75"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize:original"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "linkImage"}

[Warning] widget-toolbar-no-items: Trying to register a toolbar without items. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items (ckeditor.js, line 5)
 – {toolbarId: "mediaEmbed"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "AutoLink"}

**Comment by farrvince** [comment]
> > [**@Mgsy**](https://github.com/Mgsy) New plugins are not getting added in react build provided by ckeditor 5. Can you share a working code via codepen etc for adding new plugins like font family, underline etc to react build of ckeditor5?
> 
> If you don't [build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source), you have to [prepare a custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds), then integrate it with React.

Same error here: toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable - {name: "underline"

And I have the same error with multiple items:

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize:50"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize:75"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "imageResize:original"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "linkImage"}

[Warning] widget-toolbar-no-items: Trying to register a toolbar without items. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items (ckeditor.js, line 5)
 – {toolbarId: "mediaEmbed"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
 – {name: "AutoLink"}

**Comment by AtaullahkhanMweb** [comment]
not working  underline button in ckeditor

**Comment by AtaullahkhanMweb** [comment]
underline button in ckeditor5 not working in online bulid

**Comment by jayshri-cms** [comment]
why underline plugin is not working in ckeditor? I am trying to use ckeditor5 classic build. but underline plugin is not working.

**Comment by Witoso** [comment]
@jayshri-cms, please create a separate issue detailing your problem, we don't observe this on any demo or sample.

**Comment by biladina** [comment]
of course its not working, because in predefined build classic, underline is not included.. more on [included plugins in predefined build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#list-of-plugins-included-in-the-ckeditor-5-predefined-builds)
