### ISSUE TITLE
code

### ISSUE THREAD

**Issue by hosamalzagh** [ckeditor/ckeditor5#5568]
## 📝 Provide detailed reproduction steps (if any)

```
<p><code>{ "results": [ { "text": "Group 1", "children" : [ { "id": 1, "text": "Option 1.1" },</code></p>
<p><code>&nbsp;{ "id": 2, "text": "Option 1.2" } ] },</code></p>
<p><code>&nbsp;{ "text": "Group 2", "children" : [ { "id": 3, "text": "Option 2.1" },</code></p>
```

code  add <P> in new line after paste

or if  i press code key and past dispaly as

`<p>.<strong>article_content &nbsp;blockquote</strong>{<br>&nbsp; &nbsp;&nbsp;<strong>background</strong>: <strong>#e2f2f7</strong>;<br>&nbsp; &nbsp;&nbsp;<strong>padding</strong>: 2<strong>em </strong>2.5<strong>em</strong>;<br>&nbsp; &nbsp;&nbsp;<strong>font-weight</strong>: <strong>bold</strong>;<br><br>&nbsp; &nbsp;&nbsp;<strong>overflow</strong>: <strong>hidden</strong>;<br>&nbsp; &nbsp;&nbsp;<strong>margin-left</strong>: 0;<br>&nbsp; &nbsp;&nbsp;<strong>margin-right</strong>: -1.3<strong>em</strong>;<br>&nbsp; &nbsp;&nbsp;<strong>font-style</strong>: <strong>italic</strong>;<br>&nbsp; &nbsp;&nbsp;<strong>border-left</strong>: 0;<br>&nbsp; &nbsp;&nbsp;<strong>border-right</strong>: <strong>solid </strong>5<strong>px hsl</strong>(0, 0%, 80%);<br>}</p> `

### ✔️ Expected result

*What is the expected result of the above steps?*

### ❌ Actual result

*What is the actual result of the above steps?*

## 📃 Other details

* Browser: …all
* OS: …centos7
* CKEditor version: …5
* Installed CKEditor plugins: …code

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Your request is pretty vague, bug I suppose you're asking for code blocks feature, in which case we're working on it here: #436
