### ISSUE TITLE
[Safari] The caret is stuck inside the caption 

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#557]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html.
2. Focus the image caption.
3. Try to focus some paragraph.

## Current result
There's no possibility to move the caret outside the caption.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/30330224-c035c9cc-97d4-11e7-917d-f71652d657db.gif)

## Other information
OS: MacOS X
Browser: Safari 11.0
Release: 0.11.0

**Comment by Reinmar** [comment]
I can indeed reproduce this but it's a bit random. Perhaps some timing issues. My guess – we try to rerender the content after blur before we get selectionchange event (and update the view->model selection based on the DOM's one).

**Comment by Mgsy** [comment]
Moved to the proper repository - https://github.com/ckeditor/ckeditor5-engine/issues/1157.

**Comment by Reinmar** [comment]
Actually, I don't know if the engine is the correct repository, but let's check it there.
