### ISSUE TITLE
install @ckeditor/ckeditor5-image Missing imageresize

### ISSUE THREAD

**Issue by AnyGong** [ckeditor/ckeditor5#5572]
## 📝 Provide detailed reproduction steps (if any)

1. npm install --save @ckeditor/ckeditor5-image

### ✔️ Expected result

Will install the full dependency plugin package

### ❌ Actual result

node_modules Missing imageresize plugin function, this dependency exists in the actual github package！
![image](https://user-images.githubusercontent.com/9441196/66630345-9a24c180-ec36-11e9-872f-189cf90f138b.png)

## 📃 Other details

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0.1
    Safari: 13.0.2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, I've just installed `Image` plugin via `npm install @ckeditor/ckeditor5-image` and the package contains `ImageResize` plugin. Please, make sure that you installed the plugin in version `14.0.0`.

**Comment by AnyGong** [comment]
@Mgsy I tried to install `npm install --save @ckeditor/ckeditor5-image@14.0.0 ` like this and suddenly found it. But with `npm install --save @ckeditor/ckeditor5-image`, the version information displayed is always `v13.1.2`, my `npm` installation source address is `https://registry.npmjs.org `maybe no Post the latest on npm?
