### ISSUE TITLE
Custom plugin + Custom inline element is not recognized by Track Changes

### ISSUE THREAD

**Issue by fdkdervis** [ckeditor/ckeditor5#5573]
## 📝 Provide detailed reproduction steps (if any)

1. Created a custom plugin (ui, editing, commands)
2. Commands insert custom element : conversion to span
3. Run editor with track changes enable by default

### ✔️ Expected result

*Be able to insert my element and see changes in track changes*

### ❌ Actual result

*Cannot insert my element when track changes is enable*
*If track changes is disabled, custom element can be added* #

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by pjasiun** [comment]
The current version of the track changes plugin does not support interactions with custom plugins. We plan to introduce it in the future. Please [contact our support channel](https://ckeditor.com/contact/) if you want to talk about it.
