### ISSUE TITLE
Content Changing Tracking 

### ISSUE THREAD

**Issue by luizhmcarvalho** [ckeditor/ckeditor5#5574]
Hi.

We need to enable the changing tracking plugin on my ckeditor 5 instance. Is necessary any special license key?

**Comment by pjasiun** [comment]
Yes. Track changes is a commercial-only plugin. Please check our [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html) and [contact our support channel](https://ckeditor.com/contact/).

**Comment by scofalik** [comment]
I'd like to add that we offer free trials: https://orders.ckeditor.com/trial/collaboration.
