### ISSUE TITLE
Hide merging cells options in the table UI.

### ISSUE THREAD

**Issue by nikkimk** [ckeditor/ckeditor5#5578]
## 📝 Provide a description of the new feature
A11y feature: Complex data tables aren't always accessible to screen readers, so UI should make it harder to do things that are less accessible. Often tables with merged cells can be made into smaller, easier-to-understand, mobile-friendly tables. (See note at https://webaim.org/techniques/tables/data#complextables)

*What is the expected behavior of the proposed feature?*
Merging and splitting would be in some kind of advanced menu instead as one of the main options in the floating menu.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Thanks for reporting this feature. Luckily you can already do solve this problem today with the [`config.table.tableToolbar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-tableToolbar) option. Just exclude cell merge button and you're good to go.

As for removing the feature from the default toolbar, we'd like to keep it as this is a vital functionality for many use cases. Thus we'd like to keep it as an opt-out.
