### ISSUE TITLE
[Docs] Provide nicer customized theme example

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#558]
Just for the reference, the current one looks as follows:

![screen shot 2017-09-13 at 12 50 13](https://user-images.githubusercontent.com/545175/30373591-21adc4b8-9882-11e7-8b6d-a129bfe812ed.png)

IIRC @RyszardB had quite an interesting proposal, not sure if doable though.

**Comment by wwalc** [comment]
One of the alternatives that looked reasonable. 

Note: I'm mainly referring to colours used and the subtle underline below buttons.
Maybe it's just because I like the blue colour ;)

![screen shot 2017-09-13 at 13 03 15](https://user-images.githubusercontent.com/545175/30374085-f39280e4-9883-11e7-8d9a-1201db1cad3b.png)

**Comment by oleq** [comment]
Is this issue still valid?

![image](https://user-images.githubusercontent.com/1099479/37526283-3617b470-292f-11e8-93da-ba896a8c68ad.png)

**Comment by Reinmar** [comment]
When looking at:

![image](https://user-images.githubusercontent.com/156149/37529166-b5bcb336-2936-11e8-90d3-3e21fa8a36d8.png)

The only thing which doesn't work for me is the blue border of the editable. But IDK if making it darker would help. It's not a big problem anyway.

**Comment by oleq** [comment]
@wwalc WDYT?
