### ISSUE TITLE
A toolbar with grouped items should have some sane max-width

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5586]
## 📝 Provide detailed reproduction steps (if any)

1. Open classic editor.
2. Make the window very narrow.
3. Open the toolbar with the items that didn't fit in the single row.

### ✔️ Expected result

It should never get out of the viewport. It should have some sane `max-width` and wrap items to the next line.

### ❌ Actual result

Sometimes it's getting too long and it sticks out.

![Peek 2019-10-14 19-05](https://user-images.githubusercontent.com/247363/66769544-ab2f3600-eeb5-11e9-8dd8-a99a438659a7.gif)

## 📃 Other details

Follow-up of https://github.com/ckeditor/ckeditor5-ui/pull/523.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ahmedosama5200** [comment]
any updates ?

**Comment by nusagates** [comment]
Fix this please

**Comment by nusagates** [comment]
Still waiting for an update on this issue. 🙏

**Comment by snorkellingcactus** [comment]
Same here

**Comment by Reinmar** [comment]
It would also be good to resolve #6146.
