### ISSUE TITLE
Editor is not showing and giving an error in production(Angular8).

### ISSUE THREAD

**Issue by muhazzib** [ckeditor/ckeditor5#5593]
Ckeditor5 is working fine in development mode but giving an error in production.
**Production Mode Error**
![Screenshot_33](https://user-images.githubusercontent.com/25737000/66900976-36740d00-f017-11e9-84c0-d1daefeb4499.png)
![Screenshot_34](https://user-images.githubusercontent.com/25737000/66901058-67ecd880-f017-11e9-8a79-70f8bc1aa766.png)
**Code**
**TypeScript File**
```
import { Component, OnInit, DoCheck } from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import { ConfigService } from '../../services/config.service';
import { ChallengesService } from '../services/challenges.service';
import { Challenge } from '../interfaces/challenge';
import { Condition } from '../interfaces/condition';
import { Router, ActivatedRoute } from '@angular/router';
@Component({
  selector: 'app-create-challenge',
  templateUrl: './create-challenge.component.html',
  styleUrls: ['./create-challenge.component.scss']
})
export class CreateChallengeComponent implements OnInit, DoCheck {
  public Editor = ClassicEditor;
  showEditor = false;
  editorConfig = {
    placeholder: 'Type the content here!',
    toolbar: ['bold', 'italic']
  }
}
```
**HTML**
```
<ckeditor
   class="editor"
   [config]="editorConfig" [editor]="Editor"
   name="description"
   [(ngModel)]="translation.description"></ckeditor>
```
**Configuration**
```
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';
@NgModule({
declarations: [...],
imports: [CKEditorModule],
 providers: [...]
})
```
Versions:
"@ckeditor/ckeditor5-angular": "^1.1.0"
"@ckeditor/ckeditor5-build-classic": "^12.4.0"

**Comment by Mgsy** [comment]
Hello, did you follow our [Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html)?

**Comment by ma2ciek** [comment]
Could you also show your `tsconfig.json` configuration? I can bet that targeting the `es5` might be a problem.

**Comment by muhazzib** [comment]
I was able to fix this issue by upgrading angular version to latest.
