### ISSUE TITLE
"CKEditor Unexpected error" wrapper makes errors unreadable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5595]
Good luck analysing where this issue occurred: 

![image](https://user-images.githubusercontent.com/156149/66908688-cdd36300-f00b-11e9-8ee6-19ae7f5dc544.png)

We need to improve this as this will be a big PITA.

**Comment by Reinmar** [comment]
Those links to sources don't work. Clicking them opens a new tab:

![image](https://user-images.githubusercontent.com/156149/66908859-1723b280-f00c-11e9-89de-59c7112945fc.png)

**Comment by ma2ciek** [comment]
Hm. The core of the problem seems to be displaying the `\n` character as the `CKEditorError` `JSON.stringify( data )` creates `\\n` from `\n`. Maybe we can add use something like `JSON.stringify( data ).replace( /\\n/g, '\n' ) )`? I can also make the beginning more readable.

**Comment by ma2ciek** [comment]
>  Because, do we actually need to have data == { originalError: foo }? Can't we have data == foo?

We can't have an error instance passed directly, because the `JSON.stringify( error )` returns `{}`, thus I enumerated there the error properties:

```js
{
	originalError: {
		message: err.message,
		stack: err.stack,
		name: err.name
	}
}
```

Of course, this data could be kept also as such structure:
```js
{
	message: err.message,
	stack: err.stack,
	name: err.name
}
```

But it won't change anything in case of displaying the error stack properly.

**Comment by ma2ciek** [comment]
The other thing that comes to my mind is that we can overwrite the stack trace of the `CKEditorError` with the original error's stack trace as these errors start from the same place.

E.g.:

```js
static rethrowUnexpectedError( err, context ) {
	if ( err.is && err.is( 'CKEditorError' ) ) {
		throw err;
	}

	const ckeditorError = new CKEditorError( 'unexpected-error', context, {
		message: err.message,
		name: err.name
	} );

	ckeditorError.stack = err.stack;

	throw ckeditorError;
}
``` 

Although this construction introduces some magic so I'm not sure about it.

**Comment by ma2ciek** [comment]
cc @mlewand, what do you think about the proposed solutions?

**Comment by ma2ciek** [comment]
ping @Reinmar @mlewand, could you check my proposals in the above comments?

**Comment by pjasiun** [comment]
I believe that we should forward errors when the editor is built with `--debug` flag, instead of wrapping them in `CKEditorError`. I hope it should be enough to have both easy debugging in the debug mode and working watchdog in the productive mode.

**Comment by ma2ciek** [comment]
I've checked and on Chrome replacing only the `error.stack` property results in displaying only the error stack to the console when an error occurs:

![Screen Shot 2019-11-06 at 09 46 26](https://user-images.githubusercontent.com/2768047/68282939-e1a63e00-007a-11ea-8037-45dbf68c8264.png)

**Comment by Reinmar** [comment]
If it works well in all browsers, then I think it's a good idea. If not, I'd do a custom error message getter for cases where error's additional data is an instance of an error.

**Comment by ma2ciek** [comment]
This replacement, unfortunately, doesn't print the stack trace well on Safari. It works well on Chrome and FF though. On Safari the stack trace is created once the error is thrown, not when the error is created, thus replacing it doesn't change anything.

Comparison of the original errors and the rethrown errors:

Chrome:
<img width="580" alt="Screen Shot 2019-11-18 at 11 21 09" src="https://user-images.githubusercontent.com/2768047/69045157-96831800-09f6-11ea-904b-1635fc778911.png">

Firefox:
<img width="542" alt="Screen Shot 2019-11-18 at 11 21 28" src="https://user-images.githubusercontent.com/2768047/69045135-8cf9b000-09f6-11ea-9e57-04fb3b77c9bf.png">

Safari:
<img width="507" alt="Screen Shot 2019-11-18 at 11 21 48" src="https://user-images.githubusercontent.com/2768047/69045204-b1ee2300-09f6-11ea-88a3-0194d4908260.png">

The original error could be logged, however it doesn't sound like a good solution.

**Comment by jodator** [comment]
At least it's something better for majority of users :)

**Comment by Reinmar** [comment]
I guess we can change this multiple times – i.e. try with this and then improve if we'll see that it wasn't enough. 

Optionally, if you think that the above result is still bad, we can add do it our `// if CK_DEBUG` comment, as @pjasiun proposed, to disable the rethrow completely in our entire dev env. This way, we'll have no problems during development at all (due to the flag) and the community and us in some specific cases (like debugging something in docs) will have pretty good errors thanks to the first step.

**Comment by ma2ciek** [comment]
> I guess we can change this multiple times – i.e. try with this and then improve if we'll see that it wasn't enough.

Great 👍 

> Optionally, if you think that the above result is still bad, we can add do it our // if CK_DEBUG comment, as @pjasiun proposed, to disable the rethrow completely in our entire dev env. This way, we'll have no problems during development at all (due to the flag) and the community and us in some specific cases (like debugging something in docs) will have pretty good errors thanks to the first step.

Can we add the `// @if CK_DEBUG // throw err;` (where `err` is the original error) at the beginning of the `CKEditorError.rethrowUnexpectedError`? This way we should handle all possible debugging obstacles connected with rethrowing errors.

**Comment by Reinmar** [comment]
AFAIU rethrowing will still change the stack trace on Safari? That'd be a bummer, but I guess the only alternative would be something like:

```js
		try {
			if ( this._pendingChanges.length === 0 ) {
				// If this is the outermost block, create a new batch and start `_runPendingChanges` execution flow.
				this._pendingChanges.push( { batch: new Batch(), callback } );

				return this._runPendingChanges()[ 0 ];
			} else {
				// If this is not the outermost block, just execute the callback.
				return callback( this._currentWriter );
			}
		} catch ( err ) {
                        // @if CK_DEBUG // throw err;
			CKEditorError.rethrowUnexpectedError( err, this );
		}
``` 

But I don't know how the above will differ from what you proposed. Could you show some stack traces that both solutions will produce?

**Comment by ma2ciek** [comment]
Oh. Now I reread this and this approach doesn't make any sense on Safari. The only way to preserve the original stack trace there would be commenting the `try {`, and `} catch ( err ) { ... }` parts. So actually the `// @if CK_DEBUG // throw err;` doesn't make sense to me.

The result of adding the `// @if CK_DEBUG // throw err;` part in the `catch()` is following:
<img width="458" alt="Screen Shot 2019-11-20 at 11 41 26" src="https://user-images.githubusercontent.com/2768047/69232203-de3aa880-0b8a-11ea-832b-db1629b65b21.png">

**Comment by Reinmar** [comment]
Dunno. Let's see it live and decide. We're not debugging things on Safari too often anyway, so we could most likely live without this anyway. 

Do changes that you think will be fine, let's merge them and if we'll be still complaining then we can think further.
