### ISSUE TITLE
Consider enabling toolbar items grouping in inline and balloon builds

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5597]
## 📝 Provide a description of the new feature

ATM [automatic items grouping](https://github.com/ckeditor/ckeditor5/issues/416) (a.k.a. responsive toolbar) works only in **classic** and **decoupled** editors. I wasn't enabled in **inline** and **balloon** because there's no way to have it out–of–the–box. Simply, there's no obvious size restriction for the toolbars in these editors because the toolbar element is floating and physically attached down bellow in the so-called "body" collection. There's no parent that could squeeze it or force to resize.

But there are some tricks we could use to make it happen in inline/balloon:

* For instance, we can use an **arbitrary** CSS `max–width` on the toolbar element. It will automatically group items that do not fit. It will be static from that moment on because still there's nothing that impacts its size, but it does improve the UX

   ![image](https://user-images.githubusercontent.com/1099479/66909257-b9439a80-f00c-11e9-9b74-310ec08affb5.png)

* In **inline** we could synchronize the `max-width` of the toolbar with the width of the editable it is attached to avoid this situation:
   
   ![image](https://user-images.githubusercontent.com/1099479/66909614-5acaec00-f00d-11e9-8dca-af2faadd2750.png)

   This should be fairly easy because we have a tool that can observe changes in the geometry of the editable. All we need is to read it and apply to the toolbar:
   
   ![image](https://user-images.githubusercontent.com/1099479/66909777-a382a500-f00d-11e9-84a5-e7444600bf7c.png)

* In **balloon** we could do the same (`max-width`) maybe except that 
  * we don't have control over where the toolbar is positioned,
  * and even if we had, a balloon toolbar as wide as editable still looks weird

  So in this case, we could also observe the geometry of the editable but use some sane scale factor like `toolbar#max-width = 50% of editable.width`.

We can start implementing those features straight away or we can first document them like

> wanna save some space in balloon/inline, set `max-width` here and there

and see if people start using it.

---

@Reinmar @dkonopka @mlewand 

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by pshurygin** [comment]
This feature would be great to have!
Also, i would argue that there is one obvious size restriction for any kind of editor toolbar, which is viewport width. I think there are pretty much no cases when you expect to see an editor toolbar outside of viewport and be forced to scroll to see it. This behavior actually looks like a bug to me.
