### ISSUE TITLE
MathType plugin doesn't work

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#5613]
## 📝 Provide a description of requested docs changes

MathType demo doesn't work in the latest docs. The editor loads without a formula and it's not possible to insert new formulas.

**Comment by oleq** [comment]
Things land in the model/view but they don't render

![image](https://user-images.githubusercontent.com/1099479/67008947-dd75a900-f0ea-11e9-9bc1-7d5dfdbaaeed.png)

![image](https://user-images.githubusercontent.com/1099479/67008959-e49cb700-f0ea-11e9-8251-7f1d0a90893f.png)

**Comment by jodator** [comment]
Same on Android - something is in the editing area but I don't see anything.

**Comment by Reinmar** [comment]
It works fine on https://ckeditor.com/docs/ckeditor5/latest/features/mathtype.html so this may be something on our side. Could you bisect when it stopped working? It's perhaps worth to build the docs from `stable` and see if it works there too.

**Comment by Reinmar** [comment]
OK, got it. It's due to the `xmlns` attribute used on `<img>`. MathType should not add it there because it's completely invalid in this context.

**Comment by mlewand** [comment]
The issue has been fixed by MathType team in their upcoming release. We checked https://github.com/wiris/mathtype-ckeditor5/tree/4594e7fae89a1b0c0a15cf756774feadbdbb81fa and it indeed no longer have this issue.

We got information that the release will be published today. So we should update the version in deps as soon as it's published and we're good to go.

**Comment by mlewand** [comment]
Version 7.17.1 has been released a moment ago.

On a side note, I don't know how is that possible that we already had [a dependency on non-existent (back then) 7.17.1 version](https://github.com/ckeditor/ckeditor5/blob/81c153a0938cd14684e5f0ffa7d5f21140d585d4/package.json#L85) already 😂

Anyway this means that it should work out of the box as long as `yarn.lock` will get updated too.
