### ISSUE TITLE
Editor crashes when pasting across document title and body

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5614]
## 📝 Provide detailed reproduction steps (if any)

0. Copy some paragraph from the guide.
1. Open title feature guide
2. Type "foo" in the title and "bar" in the body
3. Select [foo bar].
4. Paste

![image](https://user-images.githubusercontent.com/1099479/67008126-275d8f80-f0e9-11e9-9c86-4afebfce188e.png)

### ✔️ Expected result

Content is pasted.

### ❌ Actual result

Error is thrown and the editor stops working

```
CKEditorError: model-position-path-incorrect: The position's path is incorrect. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-position-path-incorrect
 {"position":{"root":"main","path":[0,0,0],"stickiness":"toNext"}}
```

## 📃 Other details

* master, 
* cross-browser

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Source of the issue: https://github.com/ckeditor/ckeditor5/issues/1921

**Comment by oleq** [comment]
A good catch. Closing as a dup of https://github.com/ckeditor/ckeditor5/issues/1921.
