### ISSUE TITLE
[FF] The caret appears at the top of the editor after right-click on the not focused editable

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#562]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html.
2. Don't focus the editor.
3. `Right-click` on the editor.

## Current result
The caret has appeared at the top of the editor.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/30543796-a748dd1e-9c84-11e7-8987-cfda9a4a6fdf.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Firefox
Release: 0.11.0

**Comment by scofalik** [comment]
The same will also happen if you focus toolbar and then click <kbd>Tab</kbd>. For some reason selection is incorrectly set before the first focus in editor.

**Comment by ma2ciek** [comment]
I've checked, that FF puts the selection (both `focusNode` and `anchorNode`) at the contentEditable, instead of the first paragraph or something else. Should we move the selection to the first element inside the editor if the editor is selected? I see, that there's no trouble with this in the CKE4.

**Comment by Reinmar** [comment]
There's a great chance that https://github.com/ckeditor/ckeditor5-engine/pull/1151 will fix it.

**Comment by ma2ciek** [comment]
Oh, I didn't notice the PR.

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5/issues/1010 also mention issues with an editor which contains only a `<video>`. It would be good to see where the editor places the selection in such a case. The only valid place will be around that video (if it's marked in the schema as an object).
