### ISSUE TITLE
Part of the Title plugin docs is written in the snippet and it produces errors

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5625]
## 📝 Provide a description of requested docs changes

I was searching the "You can check the content of the title and body elements below." text in the `title.md` document and I couldn't find it. I don't think we should put part of the documentation in snippets since it is hard to find.

Also, the code highlight plugin outputs warnings about this (I was checking why this was logged):

> Language "title-console" in codeblock section is not supported. Autohighlight was used instead!
onmessage @ highlight.worker.js:14

**Comment by AnnaTomanek** [comment]
The second part was also reported here: https://github.com/cksource/umberto/issues/830.

**Comment by godai78** [comment]
PR: https://github.com/ckeditor/ckeditor5/pull/8366

This was targeted at master, as this is that time.
