### ISSUE TITLE
Publish only the important files for ckeditor5-* packages during releasing packages

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#563]
ATM we publish everything from the packages during the release.

We could publish the important files only:

* Directories: 
  - `src/`,
  - `theme/`,
  - `lang/`,
* Files: 
  - `CHANGELOG.md`,
  - `LICENSE.md`.

[Single files should be published by NPM out-of-the box](https://docs.npmjs.com/files/package.json#files) so we need to add a `files` key to `package.json` with specified directories above.

**Comment by pomek** [comment]
We did the same task in `mgit2` repository – https://github.com/cksource/mgit2/blob/56a31ce3107ba4df8501d95ea3b75da68a7c8a87/package.json#L54-L57.

**Comment by Reinmar** [comment]
+ README.md?

**Comment by pomek** [comment]
`README.md` and `package.json` are done by npm.

**Comment by pomek** [comment]
Done in all repositories except the `*build*`:

* https://github.com/ckeditor/ckeditor5-autoformat/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-adapter-ckfinder/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-basic-styles/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-block-quote/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-core/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-clipboard/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-editor-balloon/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-editor-classic/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-engine/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-enter/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-editor-inline/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-essentials/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-image/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-heading/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-link/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-list/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-markdown-gfm/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-paragraph/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-typing/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-theme-lark/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-undo/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-ui/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-upload/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-utils/compare/t/ckeditor5/563
* https://github.com/ckeditor/ckeditor5-widget/compare/t/ckeditor5/563

**Comment by pomek** [comment]
I forgot to add the `Internal` prefix to the commit message and I messed up a little with the commit references. Sorry.

**Comment by Reinmar** [comment]
Feel free to force push corrected branches.

**Comment by pomek** [comment]
I did it and now we have two references :D

**Comment by Reinmar** [comment]
I merged these branches on Friday. Thanks!
