### ISSUE TITLE
Pasting list from Microsoft Word loses indentation

### ISSUE THREAD

**Issue by adamerose** [ckeditor/ckeditor5#5631]
## 📝 Provide detailed reproduction steps (if any)

MS Word:
![image](https://user-images.githubusercontent.com/10884874/67124095-ca80d880-f1bf-11e9-9414-599125c019c3.png)

1. Make a list in Microsoft Word with indented bullets
2. Paste the whole list into CKEditor 5

The bug also occurs on this demo page:
https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo

## ✔️ Expected result

The indentation should be preserved.

## ❌ Actual result

The indentation is lost.
![image](https://user-images.githubusercontent.com/10884874/67123794-462e5580-f1bf-11e9-8355-068c394a2369.png)

## 📃 Other details

Pasting from Google Docs does work correctly (indentation is preserved).
https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html#demo

* Browser: Chrome & Edge
* OS: Windows 10
* CKEditor version: ckeditor5-build-classic 12.4.0
* MS Word version: 2016

---

**Comment by Mgsy** [comment]
Hi! We're aware of this issue, actually, PR waits for a review - https://github.com/ckeditor/ckeditor5-paste-from-office/pull/53.

I'm closing it as a DUP of https://github.com/ckeditor/ckeditor5/issues/2518.
