### ISSUE TITLE
"Show more items" tooltip placement improvement

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#5636]
## 📝 Provide detailed reproduction steps (if any)

Thanks to the toolbar grouping feature the editor looks much better on the smaller devices.

But, there is one thing we could improve - tooltip position. In the situation where an editor has small padding or margin there is a possibility of trimmed tooltip content. We know that by default "show more" button will be always the last one, so we could think about this "improvement".

It all boils down to [introduce a new class of tooltip component](https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/ckeditor5-ui/components/tooltip/tooltip.css) - `_sw`. 

cc @oleq 

### ✔️ Expected result
![Screen Shot 2019-10-21 at 10 17 56](https://user-images.githubusercontent.com/10219857/67188367-74dd4380-f3ec-11e9-8fc8-cbaebd6059be.png)

*What is the expected result of the above steps?*

### ❌ Actual result

![Screen Shot 2019-10-21 at 10 19 21](https://user-images.githubusercontent.com/10219857/67188357-6ee76280-f3ec-11e9-8525-143f99f81c8a.png)

---
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
What we need is another position in https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_tooltip_tooltipview-TooltipView.html#member-position.

**Comment by oleq** [comment]
cc @mlewand

**Comment by Acrophost** [comment]
Looks like the issue is not reproducible on `master` anymore.
