### ISSUE TITLE
Consider adding info about allowed image types to the image upload guide

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5637]
The info about changes made in https://github.com/ckeditor/ckeditor5-image/pull/323 is missing.

**Comment by AnnaTomanek** [comment]
As discussed, I proposed some additions in the CKFinder adapter guide: https://github.com/ckeditor/ckeditor5-ckfinder/pull/53

We may want to add a piece of code example to show how to implement it.

If this version looks OK, I'll add similar entries to the guides for other upload adapters.

**Comment by AnnaTomanek** [comment]
A similar block was added to all guides:

* [CKFinder](https://github.com/ckeditor/ckeditor5-ckfinder/blob/stable/docs/features/ckfinder.md#configuring-allowed-file-types)
* [Easy Image](https://github.com/ckeditor/ckeditor5-easy-image/blob/stable/docs/features/easy-image.md#configuring-allowed-file-types)
* [Base64](https://github.com/ckeditor/ckeditor5-upload/blob/stable/docs/features/base64-upload-adapter.md#configuring-allowed-file-types)
* [Simple upload adapter](https://github.com/ckeditor/ckeditor5-upload/blob/stable/docs/features/simple-upload-adapter.md#configuring-allowed-file-types)

We could refine it later (add some code example, rework the simple adapter guide as the new part does not really perfectly match the existing Configuration section), but this should do for now.
