### ISSUE TITLE
[Docs] Documentation needs a favicon

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#564]
Project's documentation needs a favicon for better bookmarking and overall UX. This one would be OK to start with:

![image](https://user-images.githubusercontent.com/1099479/30812074-2a95f44c-a20a-11e7-9056-00990fa4d040.png)

cc @Reinmar @m-turek.

**Comment by Reinmar** [comment]
@m-turek, will you check how Umberto could load it?

@oleq, what size and ext it should be? Could you prepare a target file?

**Comment by wojtekidd** [comment]
Contact Rysiek - we do have a favicon of the Ecosystem and that would be preferable to use with the docs too.

**Comment by RyszardB** [comment]
My proposal..

![screen shot 2017-10-04 at 14 48 30](https://user-images.githubusercontent.com/17498197/31176717-16f20a00-a914-11e7-84da-5edb660509f1.png)

Please let me know what you think.

**Comment by Reinmar** [comment]
I'm slightly worried that it's not related to CKEditor. You will see it in a browser tab and you will not have an idea that it's the tab you look for (unless you get used to it). The color and the shape are new.

Question – could we have different favicons for different parts of CKEditor Ecosystem documentation?

**Comment by fredck** [comment]
> Question – could we have different favicons for different parts of CKEditor Ecosystem documentation?

I'm for having different ones, per project.

**Comment by oleq** [comment]
It looks like this issue has been fixed at some point.
