### ISSUE TITLE
Track changes broken on Android

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5640]
## Provide a description of the task

Turns out that https://github.com/ckeditor/ckeditor5-engine/pull/1783 has broken Track Changes plugin. We don't have the time to fix it now, and as such we have to revert this change and reopen the original issue.

## 📃 Other details

* CKEditor version: Latest `master` branch.

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5/issues/4533#issuecomment-544500122

**Comment by mlewand** [comment]
Actually, this issue is a duplicate of https://github.com/ckeditor/ckeditor5/issues/5638 that was created a moment ago.
