### ISSUE TITLE
Сan't start a video inside a table

### ISSUE THREAD

**Issue by lasfin** [ckeditor/ckeditor5#5642]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/ckeditor-5/demo/
2. Create a table
3. Insert any video from youtube/Vimeo to any table cell

### ✔️ Expected result

I could press play and see the video.

### ❌ Actual result

I can't press a button inside an iframe. I could only see a preview.

**Comment by ma2ciek** [comment]
Hi!

It's by design. However there's an open ticket about it - https://github.com/ckeditor/ckeditor5/issues/2743, you can give there a 👍 and a description of your use case.
