### ISSUE TITLE
A few links miss the `:Error message` part

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#5643]
The `attachLinkToDocumentation()` function expects the above part to be present. If it's missing, the link isn't added. It was also described in the [`attachLinkToDocumentation` requirements](https://github.com/ckeditor/ckeditor5-utils/pull/186).

https://github.com/ckeditor/ckeditor5-utils/blob/875d5a44ea24994f8dc8aafd5910ed1166a72fb9/src/ckeditorerror.js#L128-L153

<img width="569" alt="Screen Shot 2019-10-21 at 16 51 40" src="https://user-images.githubusercontent.com/2768047/67216371-62cac780-f423-11e9-9c52-1ad029fd98b1.png">

The problem I see is that this part can be easily missed when introducing a new error. I was also confused as I didn't know the second part is mandatory since I thought that the whole error will be displayed in the error codes page anyway.

As I don't see any easy way to prevent this kind of error, maybe the `attachLinkToDocumentation()` function could also support strings that miss the `:Error message` part?

**Comment by ma2ciek** [comment]
cc @pomek, @mlewand, @Reinmar.

**Comment by pomek** [comment]
When throwing an error, we always should think about a person who will read it. 

If a part of the code that I used would throw an error: "collection-add-invalid-id", I would like to know why my id is "invalid". Was it too short? Not a string, not a number, or whatever. I know, I can find more details about the error in the documentation but if an author of the code could give me a more detailed error when it occurred, I would be happy.

So I would like to ask – why can't we describe what happened? E.g.: 

```js
throw new CKEditorError( 'collection-add-invalid-id: Collection ID must be a 32-length string.' );
```

When the error occurs, I have some details and also I have a url to full documentation.

**Comment by ma2ciek** [comment]
> When throwing an error, we always should think about a person who will read it.

> If a part of the code that I used would throw an error: "collection-add-invalid-id", I would like to know why my id is "invalid". Was it too short? Not a string, not a number, or whatever. I know, I can find more details about the error in the documentation but if an author of the code could give me a more detailed message when it occurred, I would be happy.

That wasn't my point. By doing a quick search I've found that ~10 errors lack this part, so the URL won't be generated correctly for them now. So this is something everybody creating an error should be aware of. And my idea (optional) was to attach the link to every error message, even if the second part is missing.

**Comment by pomek** [comment]
I understood your idea and my post was about it. Even if an error has a specified code (that is described more precisely in the documentation), the error's message should tell you what happened.

I am for describing errors as `error-code: Something went wrong.` which means that we should fix an invalid part of our code.

**Comment by ma2ciek** [comment]
To add more context, we have an old issue to remove the second part during the editor building process - https://github.com/ckeditor/ckeditor5-dev/issues/287.

**Comment by Reinmar** [comment]
IMO, all errors should have a human readable message. Just to be consistent.

**Comment by ma2ciek** [comment]
> IMO, all errors should have a human readable message. Just to be consistent.

So, should we close the ckeditor/ckeditor5-dev#287 and #30 since both of them are invalid?

**Comment by Reinmar** [comment]
Minification is one thing. Once we'll have it working, we will need to make sure that errors are still logged nicely. But this is future. Right now, we support only `id: Error msg` format and our code should also support that.

**Comment by Reinmar** [comment]
In other words – there's no point in supporting errors without messages if today all errors should have messages.

**Comment by ma2ciek** [comment]
Ok, so I'll just fix these few errors.

**Comment by Reinmar** [comment]
I pushed the first batch of changes to https://github.com/ckeditor/ckeditor5/pull/new/i/5643.
