### ISSUE TITLE
Automatic text transformation replaces texts in inappropriate way

### ISSUE THREAD

**Issue by kubagit** [ckeditor/ckeditor5#5644]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/text-transformation.html#demo
2. Place cursor at the end of text "Type here..."
3. Press Shift+Enter
4. Start typing strings to be transformed, e.g. "", (tm), ..., 1/2, etc.

### ✔️ Expected result

The text should be transformed only in actual cursor position

### ❌ Actual result

Parts of original text "Type here..." is also being replaced.

## 📃 Other details

* Browser: Mozilla Firefox 69.0.2
* OS: Ubuntu 19.04

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Hi, thanks for reporting. This has been already fixed on master (https://github.com/ckeditor/ckeditor5/issues/1955) and is awaiting a release.
