### ISSUE TITLE
Empty 'spacerun' span tag prevents pasting from word

### ISSUE THREAD

**Issue by amrita-syn** [ckeditor/ckeditor5#5645]
## 📝 Provide detailed reproduction steps (if any)
https://github.com/ckeditor/ckeditor5/issues/2536
The fix for the above issue does not handle empty 'spacerun' span tags.
### ✔️ Expected result

Pasting from word with empty `span[style*=spacerun]` should succeed.

### ❌ Actual result

Pasting does not happen.

## 📃 Other details

* Browser: Chrome, Firefox
* OS: Windows
* CKEditor version: latest
* Installed CKEditor plugins: Standard ClassicEditor

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by amrita-syn** [comment]
Raised PR - https://github.com/ckeditor/ckeditor5-paste-from-office/pull/88

**Comment by mlewand** [comment]
@amrita-syn can I ask you to provide a simple .docx that we can use as a fixture to test this case?

**Comment by Reinmar** [comment]
I closed https://github.com/ckeditor/ckeditor5/issues/2095 as a DUP of this issue. There's an example HTML, but no docx still. Maybe @dkrahn can share some example file.

**Comment by amrita-syn** [comment]
[spacerun.docx](https://github.com/ckeditor/ckeditor5/files/3807341/spacerun.docx)
@mlewand Example file added.

**Comment by dkrahn** [comment]
Yep. The given document by @amrita-syn gives the same problem.
I think that what I commented on issue #2095 about the span tag breaking in 2 lines is a good starting point. From what I analysed the the regex that catches this condition doesn't consider line breaking.

**Comment by Reinmar** [comment]
Hm, so the case that you reported in https://github.com/ckeditor/ckeditor5/issues/2095 is actually a bit different problem. I'll reopen your ticket then.

**Comment by Reinmar** [comment]
I made a combined PR for both tickets in https://github.com/ckeditor/ckeditor5-paste-from-office/pull/89.
