### ISSUE TITLE
Changing image url to save

### ISSUE THREAD

**Issue by JMA12** [ckeditor/ckeditor5#5647]
## Provide a description of the task
Change the url attribute of an img element before saving

*What steps should be taken to fulfil the task?*

## 📃 Other details
First is I converted img element url attributes to contain a additional path, but how to remove that added path before saving?

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
You need to better explain what you're trying to achieve.
