### ISSUE TITLE
Release description invalid links

### ISSUE THREAD

**Issue by petko** [ckeditor/ckeditor5#5648]
For the last few releases here on GitHub, links to new features in the release description are not working and leading to 404 error pages.

For example: https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html, https://ckeditor.com/docs/ckeditor5/latest/features/page-break.html, etc..

**Comment by Mgsy** [comment]
Hi! We're in the middle of a release, the documentation will be updated after we finish. I'll let you know when it will be available.

**Comment by petko** [comment]
Thank you, Mgsy!
