### ISSUE TITLE
[Docs] Reporting issues and support sections for CKE5

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/ckeditor5#565]
When going through the nightly docs build I realised that CKE5 Builds has a section called _Reporting issues_ and CKE5 Framework has a _Support_ section. Could we make sure that both Builds and Framework have these two sections in the left-hand side menu?

**Comment by AnnaTomanek** [comment]
True, and also they somehow duplicate the same thing. Reporting issues is copied from CKEditor 4 docs and Support is copied from our messaging when setting up Gitter :)

We could either merge both into one article (available in both Builds and Framework) or have two separate ones, with Support linking to Reporting issues.

**Comment by Reinmar** [comment]
Yeah, they've been copied all over the place n times :P As for merging – that might be hard. These are two separate navigation trees and need to be two separate guides. Both, technically and IMO also in terms of the content.

Feel free to propose changes ;)

**Comment by AnnaTomanek** [comment]
As I understood it, @wojtekidd wanted to have both guides in both navigation trees (Builds and Framework). If so, we either merge both articles into one (content-wise) and duplicate it in both trees, or edit the content and keep 2 separate articles in 2 trees (so 4 altogether).

**Comment by wojtekidd** [comment]
While we're at it - the _License and legal_ section should be also present in the Framework docs.

**Comment by wwalc** [comment]
> As I understood it, @wojtekidd wanted to have both guides in both navigation trees (Builds and Framework). 

I'm for it as well.

To avoid issues with maintaining two copies with the same content, we may for now have one real "Reporting issues" article in CKEditor 5 Build section and another one in "CKEditor 5 Framework" that contains just text like "For an information on how to report issues, please visit ...".
Same with Support & License and legal.

Later on we'll add an issue in Umberto to support some kind of symlinks or sth.

**Comment by AnnaTomanek** [comment]
This is temporarily fixed by duplicating content and creating Support sections with relevant docs in both Builds and Framework (see 27c3fae22bc2e1bba28bc4680aa17bdce6de5a8e). When [#324](https://github.com/cksource/umberto/issues/324) is fixed, we will be able to get rid off the duplication. 

For now I've decided that it's more user-friendly to duplicate the entire content of these guides instead of leaving an almost empty file with a link to yet another article.

**Comment by Reinmar** [comment]
A small warning to all of us – the URLs became public already so when we're reorganising docs we need to consider breaking changes.

In this case, I [needed to update the URL to error codes docs](https://github.com/ckeditor/ckeditor5-utils/commit/1f3800be3edfa25c687eb80934485483490996ea) which is logged to the console together with errors.
