### ISSUE TITLE
Formatted text is deleted when typing new text directly behind it

### ISSUE THREAD

**Issue by mumat** [ckeditor/ckeditor5#5650]
## 📝 Provide detailed reproduction steps (if any)

1. Type in some unformatted text
2. Highlight this text and apply some formatting (e.g. make it bold)
3. Set the cursor to the end of the formatted text (selection is removed)
4. Type in some new text

### ✔ Expected result

You can continue typing after the previously selected text without it being deleted

### ❌ Actual result

The text typed in before is deleted.

![CKEditorDeletedText](https://user-images.githubusercontent.com/18577751/67386921-24a1e500-f596-11e9-8379-d07b54252675.gif)

## 📃 Other details

The bug is reproducible on the CKEditor5 demo page.

* Browser: Microsoft Edge 42.17134.1038.0 / Microsoft EdgeHTML 17.17134
* OS: Windows 10
* CKEditor version: 12.4.0 classic
* Installed CKEditor plugins: None

**Comment by Mgsy** [comment]
Hi, thanks for the report. I can confirm this behaviour, however, it doesn't occur in Chromium-based Edge, so we should wait for the next Edge release which will fix a lot of Edge-related bugs.

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
