### ISSUE TITLE
Bring some colours to the code block

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5663]
Follow-up: https://github.com/ckeditor/ckeditor5/issues/436

It would be nice to see some nice syntax highlighting for the code block feature:

![image](https://user-images.githubusercontent.com/1057056/67581966-2bbd2480-f749-11e9-8bcd-d98476aeb0a0.png)

**Comment by oleq** [comment]
As per https://github.com/ckeditor/ckeditor5/issues/436#issuecomment-548399675, this will not be implemented in code blocks. It's gonna be a separate code snippets feature.
