### ISSUE TITLE
How to move the selection under the code block when it is the last element in the document

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5666]
Follow-up: https://github.com/ckeditor/ckeditor5/issues/436.

AFAIR It's a known problem of widgets.

![Oct-25-2019 17-20-29](https://user-images.githubusercontent.com/1057056/67583523-0f6eb700-f74c-11e9-8809-0d6aa6d82b5a.gif)

**Comment by pjasiun** [comment]
Yea, that's tricky. First I wanted to write that it should be done the same way it is done in the blockquote, so double enter should leave the block, but then I realized that it would be very annoying whenever you want to create an empty line in your code.

**Comment by oskarwrobel** [comment]
> First I wanted to write that it should be done the same way it is done in the blockquote, so double enter should leave the block, but then I realized that it would be very annoying whenever you want to create an empty line in your code.

I had the same thoughts.
