### ISSUE TITLE
addChildCheck does not work for inline elements, causing an infinite loop

### ISSUE THREAD

**Issue by Thomas-Negrault** [ckeditor/ckeditor5#5667]
## 📝 Provide detailed reproduction steps (if any)
I have 2 custom plugins. The first one contains a text field and I want to control what elements are allowed inside it so I used `schema.addChildCheck` like this:

```
if ( Array.from( context.getNames() ).includes( 'myPlugin' ) && [ 'myPlugin', 'image', 'media'].includes(childDefinition.name ) ) 
{
    return false;
}
```
myPlugin, image and media are blocks and have `allowWhere:"$block" in `schema.register` If I try to paste into myPlugin somethink like:
```
<p>text</p>
<image/>
<p>text</p>
```
It does work as expected and remove the image because of the addChildCheck.

The issue is with myPlugin2 wich is declared using `allowWhere: '$text'` instead of $block because it's an inline element. I added it into the array of forbidden elements. When I paste into myPlugin something like this:
```
<p>text <myplugin2/> text</p>
```
I end up with an infinite loop and the following error:

> schema.js:1173 Uncaught RangeError: Maximum call stack size exceeded

I track down the error:
In insertcontent.js :
- `_handleNode` calls `_handleDisallowedNode` because it is not allowed
-  `_handleDisallowedNode` calls `handleNodes` because my element is.. an element
- `handleNodes` iterate through the nodes and calls `_handleNode` wich go back to step one and cause an infinite loop

If I change the `allowWhere: '$text'` by `allowWhere: '$block'` it does "work" as myPlugin2 is stripped from the paste into myPlugin but myPlugin2 is no longer inline so I cannot do this.

I tried to update to ckeditor5 v15.0.0 (all the plugins) but I had the same error.

### ✔️ Expected result

myPlugin2 should be removed from my pasted content

### ❌ Actual result

infinite loop and the following error: Uncaught RangeError: Maximum call stack size exceeded

## 📃 Other details

* Browser: Chrome

* CKEditor version: 
* Installed CKEditor plugins: 
- "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.0",
- "@ckeditor/ckeditor5-autoformat": "^11.0.0",
- "@ckeditor/ckeditor5-autosave": "^11.0.0",
- "@ckeditor/ckeditor5-basic-styles": "^11.0.0",
- "@ckeditor/ckeditor5-block-quote": "^11.0.0",
- "@ckeditor/ckeditor5-core": "^12.0.0",
- "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
- "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
- "@ckeditor/ckeditor5-easy-image": "^11.0.0",
- "@ckeditor/ckeditor5-editor-balloon": "^12.0.0",
- "@ckeditor/ckeditor5-engine": "^13.0.0",
- "@ckeditor/ckeditor5-enter": "^11.0.4",
- "@ckeditor/ckeditor5-essentials": "^11.0.0",
- "@ckeditor/ckeditor5-heading": "^11.0.0",
- "@ckeditor/ckeditor5-link": "^11.0.0",
- "@ckeditor/ckeditor5-list": "^12.0.0",
- "@ckeditor/ckeditor5-media-embed": "^11.0.0",
- "@ckeditor/ckeditor5-paragraph": "^11.0.0",
- "@ckeditor/ckeditor5-table": "^12.0.0",
- "@ckeditor/ckeditor5-theme-lark": "^13.0.0",
- "@ckeditor/ckeditor5-ui": "^12.0.0",
- "@ckeditor/ckeditor5-upload": "^11.0.0",
- "@ckeditor/ckeditor5-utils": "^12.0.0",
- "@ckeditor/ckeditor5-widget": "^11.0.0",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! Thanks for a detailed bug report. I tried to understand what actually happens and it's a bit too hard. Could you prepare a simplified plugin (with schema rules and some base converters if needed) and information how we can reproduce the issue there?

**Comment by Reinmar** [comment]
@Thomas-Negrault, if you'll have time to prepare such a plugin, we can always reopen the ticket.
