### ISSUE TITLE
Configure CI for the code block repository

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5669]
Follow-up: https://github.com/ckeditor/ckeditor5/issues/436.

**Comment by pomek** [comment]
One thing is still missing – we need to publish an empty package on NPM as 0.0.1. @mlewand or @Reinmar, could you?

**Comment by mlewand** [comment]
@pomek @oskarwrobel please, make the package version 0.0.1 https://github.com/ckeditor/ckeditor5/blob/e15bf8dfbcd54cd5e47fc6b36e23be1adbeba8e0/package.json#L3 before we do that.

**Comment by pomek** [comment]
@mlewand, done in https://github.com/ckeditor/ckeditor5-code-block/commit/dc3c0a9381bae6eb4507e044e859993fa3a1850c.
