### ISSUE TITLE
Starting a line with an asterisk and space after a SHIFT+ENTER

### ISSUE THREAD

**Issue by wielinde** [ckeditor/ckeditor5#5671]
![ckeditor-shift-enter](https://user-images.githubusercontent.com/327272/67661063-88465c80-f960-11e9-9d39-0b46914e9a2f.gif)

##  Detailed reproduction steps

1. Go to the official demo page of CKEditor 5 
2. Type a line
3. Finish that line by pressing SHIFT+ENTER
4. Start the next line with the an asterisk (*) followed by a space

### ✔️ Expected result

The asterisk and space should not be transformed. No bullet list should get generated. 

### ❌ Actual result

1. A bullet list is created, starting at the preceding line.
2. The first Letter of the preceding line gets lost.

* Browser: All browsers
* OS: All OSes
* CKEditor version: Latest stable

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Hi, thanks for the report. It looks like I forgot about block autoformat while fixing https://github.com/ckeditor/ckeditor5/issues/1955.
