### ISSUE TITLE
Translations in the wrong places

### ISSUE THREAD

**Issue by ramonribeiro96** [ckeditor/ckeditor5#5676]
Translations exchanged in pt-br (balloon and balloon-block), none of the translations are in the correct place. only the classic are correct.
I'm using reactjs.

## 📃 Other details

* Browser: Chrome 78
* OS: Ubuntu 19.10
* CKEditor version: 5
* Installed CKEditor plugins: Classic, Balloon and Balloon Block

**Comment by Reinmar** [comment]
Hi! 

All fine in my case:

![image](https://user-images.githubusercontent.com/156149/67746837-990dd580-fa27-11e9-99ed-c277e8da3948.png)

Are you sure you loaded translations from the correct build and cleaned the cache?

**Comment by ramonribeiro96** [comment]
hi @Reinmar, i just cleaned the caches, but it's still the same.
`yarn cache clean`

![asd](https://user-images.githubusercontent.com/29488690/67770792-d5e0c900-fa35-11e9-9989-fd8257ee32d9.png)

**Comment by ramonribeiro96** [comment]
wow, it was really my inattention, I imported the classic translation to use the balloon.
sorry, now everything is alright!
congratulations for the excellent application!
