### ISSUE TITLE
Error "Cannot read property 'is' of null" thrown in Real-time Collaboration demo

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5678]
## 📝 Provide a description of requested docs changes

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration.html (or [permalink](https://ckeditor.com/docs/ckeditor5/15.0.0/features/collaboration/real-time-collaboration/real-time-collaboration.html?docId=e0d0cca1552401d1c9848cdfa76fcc787))
1. Wait till editor is initialized.
1. Inspect javascript console.

### ✔️ Expected result

No exceptions are logged.

### ❌ Actual result

```
watchdog.js:383 Uncaught TypeError: Cannot read property 'is' of null
    at h._shouldReactToError (watchdog.js:383)
    at h._handleError (watchdog.js:352)
    at _boundErrorHandler (watchdog.js:99)
```

is thrown

## 📃 Other details

Error occurs randomly. Since it does, I'll put some details below:

<details>
<summary>Exception details available here</summary>

```
Uncaught TypeError: Cannot read property 'is' of null
    at h._shouldReactToError (watchdog.js:383)
    at h._handleError (watchdog.js:352)
    at _boundErrorHandler (watchdog.js:99)
_shouldReactToError @ watchdog.js:383
_handleError @ watchdog.js:352
_boundErrorHandler @ watchdog.js:99
error (async)
(anonymous) @ watchdog.js:250
Promise.then (async)
create @ watchdog.js:247
(anonymous) @ collaboration.js:122
XMLHttpRequest.send (async)
(anonymous) @ xhr.js:160
t.exports @ xhr.js:11
t.exports @ dispatchRequest.js:57
Promise.then (async)
a.request @ Axios.js:51
a.<computed> @ Axios.js:61
(anonymous) @ bind.js:9
o @ randomuser.js:5
(anonymous) @ collaboration.js:118

```

</details>

* Browser: Any
* CKEditor version: 15.0.0

**Comment by ma2ciek** [comment]
It's caused by the emoji sdk:

```
ErrorEvent {isTrusted: true, message: "Script error.", filename: "", lineno: 0, colno: 0, …}bubbles: falsecancelBubble: falsecancelable: truecolno: 0composed: falsecurrentTarget: Window {parent: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}defaultPrevented: falseerror: nulleventPhase: 0filename: ""isTrusted: truelineno: 0message: "Script error."path: [Window]returnValue: truesrcElement: Window {parent: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}target: Window {parent: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}timeStamp: 31120.74499996379type: "error"__proto__: ErrorEvent

sdk.js:1 Uncaught TypeError: Cannot read property 'contentWindow' of null
    at D (sdk.js:1)
    at f (sdk.js:1)
D @ sdk.js:1
f @ sdk.js:1
```

<img width="665" alt="Screen Shot 2019-10-29 at 13 49 58" src="https://user-images.githubusercontent.com/2768047/67768545-0edb6680-fa53-11e9-93e2-dc79a1859eaf.png">

The most important part is that the error event has the `error:null` part, which causes the latter issue.

**Comment by mlewand** [comment]
Looks like you have already a good understanding of that, why does it throw randomly? 🤔
