### ISSUE TITLE
Rails 6: ckeditor is not work after updating to rails 6

### ISSUE THREAD

**Issue by ayza-hamid** [ckeditor/ckeditor5#5688]
### ✔️ Expected result

*Ckeditor should work properly, I updated to the latest version of ckeditor and configured accordingly.*

### ❌ Actual result

*Uncaught ReferenceError: CKEDITOR is not defined. I am getting this error on the console.*

## 📃 Other details

* **Browser**: Chrome
* **OS**: Ubuntu 16.04 LTS
* **CKEditor** version: 5.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Any more details than that? 😄 We're unable to reproduce the issue based on the title alone. Please include step by step instruction how to reproduce the problem.

However given that CKEDITOR is undefined my bet is that you're not including the build to your site.

**Comment by ayza-hamid** [comment]
It was working fine with rails 5.2 I just updated the rails version and starts giving me `Uncaught ReferenceError: CKEDITOR is not defined` this error.

The Gem's version is 5.0.0 and rails version is 6.0.0

```  
CKEDITOR.on 'instanceReady', (event) ->
    editor = event.editor

    editor.on 'mode', (e) ->
```
Application.js 
```
//= require ckeditor/application
```

Gemfile
```
gem 'ckeditor', '5.0.0'
```

config.js
```
CKEDITOR.editorConfig = function (config) {
  config.toolbar_mini = [
    ["Bold",  "Italic",  "Underline",  "Strike"]
  ];
}
```

**Comment by jodator** [comment]
Hi if you're using https://rubygems.org/gems/ckeditor - it is a GEM provided by the community so you should [contact them](https://github.com/galetahub/ckeditor).

Also as I briefly scanned the Gem's docs it looks likes it is provided for CKEditor 4 and this is a repository for CKEditor 5 which probably brought some misunderstanding as the Gem's version is `5.0.0` :)
