### ISSUE TITLE
Math type Formula Created not displayed properly when parsed

### ISSUE THREAD

**Issue by JMA12** [ckeditor/ckeditor5#5689]
## 📝 Provide detailed reproduction steps (if any)

1. … Added a content on editor using mathtype
2. … Then using a html parser, tried to parse the equation then display it as a common component

### ✔️ Expected result

*What is the expected result of the above steps?*
Displaying the content like how it was displayed in the editor

### ❌ Actual result

*What is the actual result of the above steps?*
The styles applied to the content in the editor is not carried when parsing the data to display as a common html elements

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, MathType is rendered as `MathML` element outside of the editor and currently only [Firefox and Safari](https://caniuse.com/#feat=mathml) support it. If you'd like to render formulas properly in other browsers, you should use some third-party libraries which will handle `MathML`, i.e. [MathJax](https://www.mathjax.org).

**Comment by JMA12** [comment]
But mathjax is not supported in ckeditor 5

**Comment by Mgsy** [comment]
>But mathjax is not supported in ckeditor 5

Yes, but you should load it on your page, not in CKEditor 5. Please, see the discussion on [StackOverflow](https://stackoverflow.com/questions/29682207/unable-to-render-mathml-content-in-google-chrome).

**Comment by JMA12** [comment]
Okay thanks, might needed to find a way to display mathml elements in chrome.

Closing this issue.
