### ISSUE TITLE
Add possibility to toggle toolbar items grouping in a build

### ISSUE THREAD

**Issue by changus** [ckeditor/ckeditor5#5692]
Is there an easy way to implement a multi-row toolbar like in previous ckeditor versions?  I like the dynamic grouping, but I am also in need of a multi-row toolbar.  

I did not find anything describing this by looking at the documentation or searching the issues, thanks!

**Comment by Mgsy** [comment]
Hi! There's [`shouldGroupWhenFull`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_toolbar_toolbarview-ToolbarOptions.html#member-shouldGroupWhenFull) property which toggles grouping, however this toolbar option is passed to the toolbar constructor, so there's no way to change it in the build. 

We've decided to add a possibility for toggling grouping in the current iteration.
