### ISSUE TITLE
Image resize does not work

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#5695]
## 📝 Provide detailed reproduction steps (if any)

1. With the latest ckeditor 5, the image is inserted in notes editor using image plugin
2. Resize the image. Save the content.
3. When the notes content is viewed on web page. Image is seen in actual size.

### ✔️ Expected result

The image should be seen in resized format.
Image resize options like in old ckeditor should be available.

### ❌ Actual result

Actual image is displayed on webpage.

## 📃 Other details

* Browser: Chrome/Mozilla
* CKEditor version: 5
* Installed CKEditor plugins:

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, I believe that your content doesn't display properly because you didn't attach CKEditor 5 styles on your page. Please, take a look at our [content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) guide to learn how to use them.
