### ISSUE TITLE
Question: Build CKEditor 5 React Component from source, met Duplicate Plugin Error

### ISSUE THREAD

**Issue by Jeff-Tian** [ckeditor/ckeditor5#5697]
I am following the instructions of  https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html.

## Issue I met:
```
×
Unhandled Rejection (CKEditorError): ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
```

It cause by using the Bold plugin.

## Symptons:
I can only run the CKEditor when I deleted the Bold and Italic plugins from the doc: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html.

If I use the Bold or Italic plugin, then the build is success, however the running page will error.

## Help wanted:
Who can help investigate the root cause? 

I checked the `@ckeditor/ckeditor5-react`'s `package.json` found it references the packaged `classic-editor`, is it expected?

**Comment by Mgsy** [comment]
Hi, there are few cases which might cause this issue. Do you use a build or you build the editor from the source? Please, see our [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) to learn how to do it properly.

Also, please check if your dependencies are updated (i.e. using [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)).
