### ISSUE TITLE
TypeError: Cannot read property 'push' - Balloon-Editor - React

### ISSUE THREAD

**Issue by ramonribeiro96** [ckeditor/ckeditor5#5698]
I am trying to use balloon-editor to customize a part of my application.

you can't edit anything and the balloon doesn't appear when you select something.
on the console is giving the following error:

> TypeError: Cannot read property 'push' of undefined
    at new BalloonEditor (ballooneditor.js:73)
    at ballooneditor.js:201
    at new Promise (<anonymous>)
    at Function.create (ballooneditor.js:193)
    at t.value (ckeditor.js:150)
    at t.value (ckeditor.js:129)
    at commitLifeCycles (react-dom.development.js:21142)
    at commitLayoutEffects (react-dom.development.js:24138)
    at HTMLUnknownElement.callCallback (react-dom.development.js:363)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:412)
    at invokeGuardedCallback (react-dom.development.js:466)
    at commitRootImpl (react-dom.development.js:23903)
    at unstable_runWithPriority (scheduler.development.js:674)
    at runWithPriority$2 (react-dom.development.js:11834)
    at commitRoot (react-dom.development.js:23723)
    at runRootCallback (react-dom.development.js:22809)
    at react-dom.development.js:11886
    at unstable_runWithPriority (scheduler.development.js:674)
    at runWithPriority$2 (react-dom.development.js:11834)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11881)
    at flushSyncCallbackQueue (react-dom.development.js:11869)
    at unbatchedUpdates (react-dom.development.js:22958)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26369)
    at Object.render (react-dom.development.js:26460)
    at Module../src/index.js (index.js:7)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.0 (api.js:6)
    at __webpack_require__ (bootstrap:785)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1

![balloon-editr](https://user-images.githubusercontent.com/29488690/68025082-b2fb2280-fc8a-11e9-9446-65099f6a0d31.png)

## 📃 Other details

* Browser: Chrome v.78
* OS: Ubuntu 19.10
* CKEditor version: @ckeditor/ckeditor5-react; @ckeditor/ckeditor5-editor-balloon;

**Comment by Mgsy** [comment]
Hi, I can see that you're integrating CKEditor 5 with React. Did you follow our [CKEditor 5 React integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) guide?

**Comment by ramonribeiro96** [comment]
I am following this logic [Using CKEditor 5 source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-ckeditor-5-source), but with BalloonEditor instead of ClassicEditor.

**Comment by ramonribeiro96** [comment]
My code: 
```
import React, { Component } from 'react';
import CKEditor from '@ckeditor/ckeditor5-react';
import BalloonEditor from '@ckeditor/ckeditor5-editor-balloon/src/ballooneditor';
import '@ckeditor/ckeditor5-build-balloon/build/translations/pt-br';

import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';

const editorConfiguration = {
    plugins: [Bold, Italic],
    toolbar: ['bold', 'italic'],
    language: 'pt-br'
};

class App extends Component {
    render() {
        return (
            <div className="App">
                <CKEditor
                    editor={BalloonEditor}
                    data={'<p><span style="font-family:Tahoma;font-size:11px;">Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos.</span></p>'}
                    config={editorConfiguration}
                />
            </div>
        );
    }
}


export default App;
```

**Comment by Mgsy** [comment]
As you build the editor from the source, you have to take care of adding all the plugins required for using CKEditor 5, such as Typing, Paragraph etc. Your config is missing such plugins. We have a package which includes all the necessary packages. You can install it from npm - `npm install --save @ckeditor/ckeditor5-essentials/src/essentials`. 

Add it to your editor and it should work fine.

**Comment by ramonribeiro96** [comment]
I had this package already, but I was giving that I had duplicate builds. I just removed everything and reinstalled, and no longer gave this error.
but still the same.
![coiso](https://user-images.githubusercontent.com/29488690/68136060-65d5b580-ff03-11e9-99ec-227f1a8767cb.png)

**Comment by Mgsy** [comment]
Can you share your `package.json`?

**Comment by ramonribeiro96** [comment]
```
{
  "name": "react-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ckeditor/ckeditor5-alignment": "^15.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^15.0.0",
    "@ckeditor/ckeditor5-build-balloon": "^15.0.0",
    "@ckeditor/ckeditor5-build-classic": "^15.0.0",
    "@ckeditor/ckeditor5-editor-balloon": "^15.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^15.0.0",
    "@ckeditor/ckeditor5-essentials": "^15.0.0",
    "@ckeditor/ckeditor5-font": "^15.0.0",
    "@ckeditor/ckeditor5-paragraph": "^15.0.0",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@date-io/date-fns": "^1.3.11",
    "@material-ui/core": "^4.3.3",
    "@material-ui/icons": "^4.4.3",
    "@material-ui/pickers": "^3.2.6",
    "@material-ui/styles": "^4.3.3",
    "axios": "^0.19.0",
    "connected-react-router": "^6.5.2",
    "date-fns": "~2.3.0",
    "html-to-rtf": "^1.3.2",
    "node-sass": "^4.12.0",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.7.2",
    "ra-data-json-server": "~3.0.0-alpha.4",
    "react": "~16.9.0",
    "react-admin": "~3.0.0-alpha.4",
    "react-dom": "~16.9.0",
    "react-final-form": "^6.3.0",
    "react-scripts": "^3.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by ramonribeiro96** [comment]
any news @Mgsy ?
I'm trying to do with build-balloon, but when I add another plugin, it gives me a duplicate error.

**Comment by Mgsy** [comment]
Unfortunately, I'm still not able to reproduce your issue. 

>I'm trying to do with build-balloon, but when I add another plugin, it gives me a duplicate error.

Probably you try to add a plugin directly to the build which is incorrect. Please, see our [Installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) guide.

**Comment by ramonribeiro96** [comment]
I will check, thanks for your time and help
