### ISSUE TITLE
How to add a custom plugin to a CKEditor 5 build?

### ISSUE THREAD

**Issue by loagit** [ckeditor/ckeditor5#5699]
Hello. I am trying to install a custom plugin by following [this tutorial](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) as a reference. I am trying for days to make it work properly as described but I have not had any success yet. 

I posted [my question in stackoverflow](https://stackoverflow.com/questions/58659814/how-to-add-a-custom-plugin-to-a-ckeditor-5-build) not long ago, and I left all the details there. If it's not too much, could you guys have a look please? Thank you in advance for your attention.

**Comment by Mgsy** [comment]
Hi, thanks for a detailed report! I've followed described steps and I wasn't able to reproduce the issue. 

![image](https://user-images.githubusercontent.com/20988892/68107623-b2aa9380-fee5-11e9-9556-b5764602a1c5.png)

Here are my steps:
1. Download ZIP file from the GitHub repository.
1. Create `myplugin.js`, `myplugin_ui.js` and `myplugin_editing.js` files.
1. Run `npm install`.
1. Import `MyPlugin` in `ckeditor.js` and add it to the plugins array.
1. Run `npm run build`.

I'd suggest checking if your dependencies are updated. You can verify it with [npm-check-updates](https://www.npmjs.com/package/npm-check-updates). If not, update them, run `rm -rf node_modules`, `npm install`, then `npm run build`.

**Comment by loagit** [comment]
Hi Mgsy. Thanks for answering

> Here are my steps:
> 
> 1. Download ZIP file from the GitHub repository.
> 2. Create src/myplugin.js, src/myplugin_ui.js and src/myplugin_editing.js files.
> 3. Run npm install.
> 4. Import MyPlugin from src/myplugin.js in src/ckeditor.js and add it to the plugins array.
> 5. Run npm run build.

By the way you explained it makes me understand there are **no** two distinct Node JS projects, one for the plugin, and one for the ckeditor5-build-classic. In this case, the way you said it, it looks like I should put the plugin files in the same project as the [downloaded CKEditor build](https://github.com/ckeditor/ckeditor5-build-classic). I've tried this before, as follows:

1. I downloaded the CKEditor 5 build.
2. I installed the dependencies with `npm install`.
3. Inside the src folder, I created a new myplugin folder.
4. Inside the created folder I put the three plugins files (myplugin.js, myplugin_ui.js and myplugin_editing.js).
5. In CKEditor source code (ckeditor.js) I imported the plugin, and added it to the plugin list.
6. I ran `npm run build`
7. I opened the sample/index.html file with the browser.

Following this approach, the build works perfectly, as you have shown. 

It turns out that what I would like to do is to create a separate Node JS project for my own CKEditor 5 plugin, without having to build it inside any CKEditor 5 build src folder. I wish I could create a different module/package for any plugin that was developed, and that I could install it through NPM (i.e. `npm install myplugin`). An important detail is that I would like to do this **locally**, without having to put the plugin project in a repository on the internet. The installation would be done locally, from a folder on my computer.

The problem is that when I do this, I end up getting [this error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules):

`ckeditor-duplucated-modules`

I believe I don't know how to:

1. Create a Node JS project for the plugin.
2. Install created project (the plugin) into CKEditor 5 build project (the one downloaded).

> If your plugin requires some modules from packages which are not available in this npm project, just feel free to run npm install --save-dev @ckeditor/ckeditor5-whateveryouneed.

I am following the beginning of [this tutorial](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#plugin-structure). For now, the only dependency my plugin needs is the [Plugin class](https://github.com/ckeditor/ckeditor5-core/blob/master/src/plugin.js).

**Comment by loagit** [comment]
[Test Me.zip](https://github.com/ckeditor/ckeditor5/files/3804130/Test.Me.zip)

I uploaded both projects, the plugin and the ckeditor build. To reproduce the problem, do the following:

1. Open the myplugin project, and use `npm install`. That done close it.
2. Open the ckeditor build project (ckeditor5-build-classic-master), and do `npm install`. Wait for it to finish. Note that in its dependencies there is a reference to the plugin project (myplugin, with file).
3. Delete existing files inside the build folder (sorry, I forgot to delete them).
4. After the installation has completed, run `npm run build`.
5. When the distribution is done, open the index.html file inside the project's sample folder.

Note that CKEditor 5 does not load, and the error mentioned will appear in the browser console.

**Comment by Mgsy** [comment]
@loagit, I've downloaded your package, followed your steps and everything works fine for me.

**Comment by loagit** [comment]
@Mgsy, this is weird... Whenever I start the browser I find the following message:

![error1](https://user-images.githubusercontent.com/25250493/68130310-e4c5f080-fef9-11e9-8fef-906b7dc978f1.jpg)

I just opened windows cmd, and these are all the steps I'm going through:

```
C:\Users\RDS\Desktop\Test Me>cd myplugin

C:\Users\RDS\Desktop\Test Me\MyPlugin>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN myplugin@1.0.0 No repository field.

added 6 packages from 3 contributors and audited 25 packages in 3.9s
found 0 vulnerabilities

C:\Users\RDS\Desktop\Test Me\MyPlugin>cd ..

C:\Users\RDS\Desktop\Test Me>cd ckeditor5-build-classic-master

C:\Users\RDS\Desktop\Test Me\ckeditor5-build-classic-master>npm install

> husky@1.3.1 install C:\Users\RDS\Desktop\Test Me\ckeditor5-build-classic-maste
r\node_modules\husky
> node husky install

husky > setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an e
mpty Git repository and reinstall husky.
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

added 890 packages from 416 contributors and audited 11942 packages in 118.28s
found 0 vulnerabilities


C:\Users\RDS\Desktop\Test Me\ckeditor5-build-classic-master>npm run build

> @ckeditor/ckeditor5-build-classic@15.0.0 build C:\Users\RDS\Desktop\Test Me\ck
editor5-build-classic-master
> webpack --mode production

Hash: ee6cf3d113288acb7347
Version: webpack 4.41.2
Time: 18794ms
Built at: 04/11/2019 13:03:26
                  Asset      Size  Chunks                          Chunk Names
            ckeditor.js   612 KiB       0  [emitted]        [big]  main
        ckeditor.js.map  3.98 MiB       0  [emitted] [dev]         main
     translations\af.js  2.18 KiB          [emitted]
     translations\ar.js  2.64 KiB          [emitted]
    translations\ast.js  2.23 KiB          [emitted]
     translations\az.js  2.56 KiB          [emitted]
     translations\bg.js  2.18 KiB          [emitted]
     translations\ca.js  2.19 KiB          [emitted]
     translations\cs.js   2.6 KiB          [emitted]
     translations\da.js   2.3 KiB          [emitted]
  translations\de-ch.js  2.24 KiB          [emitted]
     translations\de.js  2.57 KiB          [emitted]
     translations\el.js  2.56 KiB          [emitted]
  translations\en-au.js  2.15 KiB          [emitted]
  translations\en-gb.js  2.15 KiB          [emitted]
     translations\eo.js  2.21 KiB          [emitted]
     translations\es.js  2.55 KiB          [emitted]
     translations\et.js  2.46 KiB          [emitted]
     translations\eu.js  2.26 KiB          [emitted]
     translations\fa.js  3.44 KiB          [emitted]
     translations\fi.js  2.38 KiB          [emitted]
     translations\fr.js   2.7 KiB          [emitted]
     translations\gl.js  2.66 KiB          [emitted]
     translations\gu.js  2.25 KiB          [emitted]
     translations\he.js  2.37 KiB          [emitted]
     translations\hr.js  2.39 KiB          [emitted]
     translations\hu.js  2.58 KiB          [emitted]
     translations\id.js  2.29 KiB          [emitted]
     translations\it.js  2.81 KiB          [emitted]
     translations\ja.js  2.48 KiB          [emitted]
     translations\km.js  2.92 KiB          [emitted]
     translations\kn.js  2.83 KiB          [emitted]
     translations\ko.js  2.19 KiB          [emitted]
     translations\ku.js  3.92 KiB          [emitted]
     translations\lt.js  2.62 KiB          [emitted]
     translations\lv.js  2.61 KiB          [emitted]
     translations\ms.js  2.14 KiB          [emitted]
     translations\nb.js  2.29 KiB          [emitted]
     translations\ne.js   5.4 KiB          [emitted]
     translations\nl.js  2.46 KiB          [emitted]
     translations\no.js   2.4 KiB          [emitted]
     translations\oc.js  2.15 KiB          [emitted]
     translations\pl.js  2.66 KiB          [emitted]
  translations\pt-br.js  2.53 KiB          [emitted]
     translations\pt.js  2.27 KiB          [emitted]
     translations\ro.js  2.53 KiB          [emitted]
     translations\ru.js  4.01 KiB          [emitted]
     translations\si.js  2.42 KiB          [emitted]
     translations\sk.js  2.57 KiB          [emitted]
     translations\sq.js  2.39 KiB          [emitted]
translations\sr-latn.js  2.43 KiB          [emitted]
     translations\sr.js  3.71 KiB          [emitted]
     translations\sv.js  2.19 KiB          [emitted]
     translations\tr.js  2.54 KiB          [emitted]
     translations\tt.js  2.16 KiB          [emitted]
     translations\ug.js  2.58 KiB          [emitted]
     translations\uk.js  4.12 KiB          [emitted]
     translations\vi.js  2.25 KiB          [emitted]
  translations\zh-cn.js   2.2 KiB          [emitted]
     translations\zh.js  2.11 KiB          [emitted]
Entrypoint main [big] = ckeditor.js ckeditor.js.map
  [8] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
 [10] (webpack)/buildin/global.js 472 bytes {0} [built]
[105] ./src/ckeditor.js + 619 modules 2.95 MiB {0} [built]
      | ./src/ckeditor.js 3.42 KiB [built]
      | ../MyPlugin/src/myplugin.js 296 bytes [built]
      | ../MyPlugin/src/myplugin_ui.js 201 bytes [built]
      | ../MyPlugin/src/myplugin_editing.js 211 bytes [built]
      |     + 616 hidden modules
    + 1176 hidden modules

C:\Users\RDS\Desktop\Test Me\ckeditor5-build-classic-master>
```
I'm still getting the same error. I do not understand what is happening. What am I doing wrong? Is there something I am not seeing anywhere? :(

**Comment by loagit** [comment]
[error.zip](https://github.com/ckeditor/ckeditor5/files/3804826/error.zip)

@Mgsy, I just recorded on video. Can you take a look, please?

**Comment by ma2ciek** [comment]
Hi @loagit.

The problem is that installing this way you install separately the `ckeditor5-build-classic` and your plugin. The `my-plugin` installs its own deps because it can't reach the `ckeditor5-build-classic`' modules. To cross-link dependencies and to work easier on the project I recommend you to use our [Development environment](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html) where `yarn` can link everything together. It should be also possible if you create the `package.json` in the root of your two directories with the following content:

```json
{
  "workspaces": {
    "packages": [
       "ckeditor5-build-classic-master",
       "my-plugin"
    ]
  }
}
```

And call `yarn install`.

PS. I recommend you to use `peerDependencies` instead of `dependencies` with the `>= 15.0.0` range instead of the `^15.0.0` range to create the plugin that can be installed easily in the future.

**Comment by loagit** [comment]
Hi, @ma2ciek.

Thank you for the reply. I haven't tried your approach yet because I don't use Yarn. I was reading here over the internet, and from what I could see today both tools are equally good. I believe that if I follow your advice, I can achieve the result I desire. Before I start studying more about Yarn, I would like to ask you: Is there no way I can do this just by using only npm? 

I ask this, as I find it strange that it is possible to install other plugins so easily with npm, such as the [alignment](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) plugin itself. Was it developed with yarn too? I'm asking for curiosity, and because I don't know about this information.

**Comment by ma2ciek** [comment]
> I ask this, as I find it strange that it is possible to install other plugins so easily with npm, such as the alignment plugin itself. Was it developed with yarn too? I'm asking for curiosity, and because I don't know about this information.

If your custom plugin would be on the NPM, as the alignment plugin is, the problem wouldn't exist and you could install all together using just `npm install`.

I'm not sure if the NPM supports workspaces now, AFAIK only yarn and Lerna do at this moment. 

Also, this problem might happen in some NPM versions only as it depends on how the module resolution works with symlinks pointing outside of the main directory. For me, it looks a little bit buggy that modules shared between projects are installed twice, the plugin with its dependencies is symlinked inside the main project's `node_modules`, thus the plugin shouldn't have problem with importing CKEditor 5 deps from the main project.

The CKEditor 5 depends on singletons, thus when it encounters module duplication it throws an error.

>  Was it developed with yarn too

It was developed in the `npm & lerna` manner first and now is developed using `yarn` after we migrated to it.

**Comment by loagit** [comment]
@ma2ciek, It seems that following your approach made everything work correctly, **thank you very much**. The only thing, though, is that now I need to incorporate the use of yarn in my development, which doesn't make me very comfortable at first, but I'm happy because I can better organize my projects anyway.

So that my question also brings clarification to other CKEditor 5 users, I will put here what I did in more detail:

1. I created a folder named `ckeditor-and-plugins` that serves as the root for CKEditor 5 build, and my plugin.
2. With Yarn, I used `yarn init` inside this folder. As a result, a package.json file is generated.
3. I downloaded [CKEditor 5 classic build from it's Git repository](https://github.com/ckeditor/ckeditor5-build-classic), and its root folder (ckeditor5-build-classic-master) was put into the ckeditor-and-plugins folder.
4. The plugin folder was also put inside ckeditor-and-plugins with the name `my-plugin`. Only 2 items are here: package.json and the src folder with the plugin source code (the 3 js files).
5. The plugin package.json file has been changed and has the following content:
```
{
  "name": "my-plugin",
  "version": "1.0.0",
  "description": "My first CKEditor 5 plugin project.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "RDS",
  "license": "ISC",
  "peerDependencies": {
    "@ckeditor/ckeditor5-core": ">=15.0.0",
    "@ckeditor/ckeditor5-ui": ">=15.0.0"
  }
}
```
6. The CKEditor 5 build package.json file has also been changed so that it could include my dependency:
```
...
"devDependencies": {
    ...
    "my-plugin": "1.0.0"
},
...
```
7. The plugin was installed in src/ckeditor.js in the same way as explained on [the site tutorial](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build).
8. In the container root folder (ckeditor-and-plugins) of both projects, the package.json file had the following content (In workspace, we see here the folders's names):
```
{
  "name": "ckeditor5-myplugins",
  "version": "1.0.0",
  "description": "CKEditor 5 project with custom plugins.",
  "main": "index.js",
  "author": "RDS",
  "license": "MIT",
  "private": true,

  "workspaces": 
  {
    "packages": [
      "ckeditor5-build-classic-master",
      "my-plugin"]
  }
}
```
9. Still within this root folder of both projects, the `yarn install` command was executed.
10. Once the dependencies have been installed, inside the ckeditor5-build-classic-master folder, the `npm run build` command has been run for distribution to be done.
11. With the distribution done, it was only necessary to open samples/index.html (inside the same folder) to test.

I want to congratulate everyone here for their willingness and help. I'm glad to be able to use a tool that I have some support from its developers. Hope you keep up the good work. :)

Ah, one more thing. This is the first time I'm using git here ... And ... Do I have to close this issue? There is a `Close and comment` button here.

**Comment by ma2ciek** [comment]
Hi,

Good to know it works for you. Just for the clarification:

> 7. The plugin was installed in src/ckeditor.js in the same way as explained on the site tutorial.

If you install everything using `yarn` later, then there's no need to install projects partially with `npm` earlier (but it shouldn't break anything anyway). I'm not sure what did you mean about the `installation` here.

> Ah, one more thing. This is the first time I'm using git here ... And ... Do I have to close this issue? There is a Close and comment button here.

You mean GitHub I guess. Don't worry, I'm closing the issue and marking it as solved.

**Comment by alexkess101** [comment]
@loagit Really appreciate the time you took to explain your solution. I've been working on this exact problem for about a week and finally found this github thread and it worked great! Much appreciated!

**Comment by motoroller1983** [comment]
> @ma2ciek, It seems that following your approach made everything work correctly, **thank you very much**. The only thing, though, is that now I need to incorporate the use of yarn in my development, which doesn't make me very comfortable at first, but I'm happy because I can better organize my projects anyway.
> 
> So that my question also brings clarification to other CKEditor 5 users, I will put here what I did in more detail:
> 
>     1. I created a folder named `ckeditor-and-plugins` that serves as the root for CKEditor 5 build, and my plugin.
> 
>     2. With Yarn, I used `yarn init` inside this folder. As a result, a package.json file is generated.
> 
>     3. I downloaded [CKEditor 5 classic build from it's Git repository](https://github.com/ckeditor/ckeditor5-build-classic), and its root folder (ckeditor5-build-classic-master) was put into the ckeditor-and-plugins folder.
> 
>     4. The plugin folder was also put inside ckeditor-and-plugins with the name `my-plugin`. Only 2 items are here: package.json and the src folder with the plugin source code (the 3 js files).
> 
>     5. The plugin package.json file has been changed and has the following content:
> 
> 
> ```
> {
>   "name": "my-plugin",
>   "version": "1.0.0",
>   "description": "My first CKEditor 5 plugin project.",
>   "main": "index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "RDS",
>   "license": "ISC",
>   "peerDependencies": {
>     "@ckeditor/ckeditor5-core": ">=15.0.0",
>     "@ckeditor/ckeditor5-ui": ">=15.0.0"
>   }
> }
> ```
> 
>     6. The CKEditor 5 build package.json file has also been changed so that it could include my dependency:
> 
> 
> ```
> ...
> "devDependencies": {
>     ...
>     "my-plugin": "1.0.0"
> },
> ...
> ```
> 
>     7. The plugin was installed in src/ckeditor.js in the same way as explained on [the site tutorial](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build).
> 
>     8. In the container root folder (ckeditor-and-plugins) of both projects, the package.json file had the following content (In workspace, we see here the folders's names):
> 
> 
> ```
> {
>   "name": "ckeditor5-myplugins",
>   "version": "1.0.0",
>   "description": "CKEditor 5 project with custom plugins.",
>   "main": "index.js",
>   "author": "RDS",
>   "license": "MIT",
>   "private": true,
> 
>   "workspaces": 
>   {
>     "packages": [
>       "ckeditor5-build-classic-master",
>       "my-plugin"]
>   }
> }
> ```
> 
>     9. Still within this root folder of both projects, the `yarn install` command was executed.
> 
>     10. Once the dependencies have been installed, inside the ckeditor5-build-classic-master folder, the `npm run build` command has been run for distribution to be done.
> 
>     11. With the distribution done, it was only necessary to open samples/index.html (inside the same folder) to test.
> 
> 
> I want to congratulate everyone here for their willingness and help. I'm glad to be able to use a tool that I have some support from its developers. Hope you keep up the good work. :)
> 
> Ah, one more thing. This is the first time I'm using git here ... And ... Do I have to close this issue? There is a `Close and comment` button here.

Could u update working project? i cannot compile with plugin(

**Comment by Witoso** [comment]
@motoroller1983 this is an old issue, feel free to open a new one detailing your problems :)
