### ISSUE TITLE
Should ImageButton be included in the builds?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#570]
Extracted from https://github.com/ckeditor/ckeditor5/issues/567.

me:

> Should the "Insert image" button be available in those builds too? I know that it should not appear automatically in the toolbar, but should the plugin be enabled?

@wwalc:

> Shouldn't we track it in a separate ticket as it's a completely separate issue?
The original issue was about two particular plugins which were already included, hence this issue could be closed.

> The new issue could be about the Image Button and our strategy towards it. For example I have some concerns regarding mobiles. On mobiles the only reasonable way to insert an image is a toolbar button. If it's not available in Builds by default then there is a "?" regarding basic support for mobiles by CKEditor 5 Builds

**Comment by fredck** [comment]
So we must also check how this button behaves on mobiles, first of all. I'm curious to see it.

**Comment by fredck** [comment]
As a first feeling, I would be for including the plugin in the build but not in the toolbar configuration, leaving the implementor one config away from having it.

**Comment by Reinmar** [comment]
The button was added to all builds.
