### ISSUE TITLE
Some CKEditor keyboard shortcuts conflict with Mac OS shortcuts

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#5705]
## 📝 Provide detailed reproduction steps (if any)

CKEditor uses key shortcuts which conflict with Mac OS shortcuts.  For example for Bold and for Link both shortcuts work: `CMD+B` and `Ctrl+B` for Bold, `CMD+K` and `Ctrl+K` for Link. The problem is that on Mac `Control-K` means "Delete the text between the insertion point and the end of the line or paragraph" and `Control-B` means "Move one character backward" - https://support.apple.com/en-us/HT201236.

The reason is because when meta (Cmd) key is pressed, it is treated as `Ctrl` key by the editor.

### ✔️ Expected result

When `Ctrl+K` or `Ctrl+B` is pressed, Mac OS commands should be executed.
CKEditor commands should only be executed when `Cmd+K` or `Cmd+B` is pressed. 

### ❌ Actual result

When `Ctrl+K`, `Cmd+K` or `Ctrl+B`, `Cmd+B` is pressed, CKEditor commands are executed.
Mac OS commands are not executed at all.

## 📃 Other details

* Browser: Any
* OS: Mac OS
* CKEditor version: 15
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jswiderski** [comment]
From what I have checked these two Mac OS shortcuts can be replaced: `Control-B` with `Left Arrow` and `Control-K` with `Shift+Command+Right Arrow` and `Delete`.

**Comment by Reinmar** [comment]
Hm... I copied this behaviour from CKEditor 4. It also treats Ctrl and Cmd as the same key and I don't think that there were complains about this.

But we could, most likely, fix it. Although, I'd be most worried about the safety of this change – how well we can recognize that we're on macOS.

**Comment by oleq** [comment]
> But we could, most likely, fix it. Although, I'd be most worried about the safety of this change – how well we can recognize that we're on macOS.

We have [`env.isMac`](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_env-env.html#static-member-isMac) already that is based on the UA string. I checked how it works and in Chrome, Firefox, and Safari, [it does contain the `'macintosh'` substring](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/env.js#L87) so I think we're safe.

TBH we're the only editor that acts this way so this actually could be an issue for some people.

**Comment by oleq** [comment]
[Seems like this is the right place to change this](https://github.com/ckeditor/ckeditor5/blob/e0fcb17d404352133609aa6875d62e056261677f/packages/ckeditor5-utils/src/keyboard.js#L208).
