### ISSUE TITLE
dropdown menu is crunched - see picture

### ISSUE THREAD

**Issue by addsimm** [ckeditor/ckeditor5#5706]
## 📝 Provide detailed reproduction steps (if any)

```
 <script src="https://cdn.ckeditor.com/ckeditor5/15.0.0/decoupled-document/ckeditor.js"></script>
    <script>

        $(document).ready(function () {
            options = {
                fontFamily: {
                    options: [
                        "Abril Fatface",    // Display
                        "Cookie",           // Cursive
                        "Cousine",          // Fixed
                        "Lato",             // Sans
                        "Tinos"             // Serif
                    ]
                },
                fontSize: {
                    options: [
                        10,
                        'default',
                        18,
                        24,
                        30
                    ]
                },
                toolbar: ['|', 'fontFamily', '|','|','fontSize', '|', '|', "alignment:left", 'alignment:center',
                    'alignment:right', '|', '|', 'bold', 'italic',
                    'underline', 'strikethrough', '|', '|', 'highlight:greenPen', 'highlight:redPen',
                    'highlight:yellowMarker', 'removeHighlight', '|', '|', 'blockQuote'],
                language: 'en',
                removePlugins: ['Autoformat']
            };

            DecoupledEditor
                .create(document.querySelector('#editor'), options)
                .then(editor => {
                    const toolbarContainer = document.querySelector('#toolbar-container');
                    toolbarContainer.appendChild(editor.ui.view.toolbar.element);
                    editor.model.document.on('change:data', function () {
                        countWords();
                    });
                    window.myeditor = editor;
                    window.myeditor.setData(original_story_content);
                    starting_words = countWords();

                    // console.log(Array.from(editor.ui.componentFactory.names()));

                })
                .catch(error => {
                    console.error(error);
                });
        });
```
### ✔️ Expected result

The drop downs (font family and font size)in the toolbar used to be flat

### ❌ Actual result

now they look like this, with the caret pointing down below the icon:

![Screen Shot 2019-11-04 at 5 17 27 PM](https://user-images.githubusercontent.com/2389450/68171039-02f61580-ff27-11e9-8a2f-5813b7f89e07.png)

**Comment by jodator** [comment]
It looks like you've made some CSS modifications. Any chance that this might force this behavior? Those buttons look OK when using default CSS.

**Comment by addsimm** [comment]
I have only made changes to colors; here is the entire file:

/*
 * Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */

:root {
    --ck-color-base-foreground: #525259;
    --ck-color-base-background: white;
    --ck-color-base-border: hsl(0, 0%, 77%);
    --ck-color-base-action: #52c3bd;
    --ck-color-base-focus: hsl(209, 92%, 70%);
    --ck-color-base-text: #525259;
    --ck-color-base-active: hsl(208, 88%, 52%);
    --ck-color-base-active-focus: hsl(208, 88%, 47%);
    --ck-color-base-error: hsl(15, 100%, 43%);

    /* -- Generic colors ------------------------------------------------------------------------ */

    --ck-color-focus-border: hsl(208, 90%, 62%);
    --ck-color-focus-shadow: hsla(209, 90%, 72%, .5);
    --ck-color-focus-disabled-shadow: hsla(209, 90%, 72%, .3);
    --ck-color-focus-error-shadow: hsla(9, 100%, 56%, .3);
    --ck-color-text: #525259;
    --ck-color-shadow-drop: hsla(0, 0%, 0%, 0.2);
    --ck-color-shadow-inner: hsla(0, 0%, 0%, 0.1);

    /* -- Buttons ------------------------------------------------------------------------------- */


    --ck-color-button-action-active-background: var(--ck-color-base-action);
    --ck-color-button-action-active-shadow: transparent;
    --ck-color-button-action-background: var(--ck-color-base-action);
    --ck-color-button-action-disabled-background: var(--ck-color-base-action);
    --ck-color-button-action-hover-background: var(--ck-color-base-action);
    --ck-color-button-action-text: white;

    --ck-color-button-cancel: #f06831;

    --ck-color-button-default-active-background: white;
    --ck-color-button-default-active-shadow: transparent;
    --ck-color-button-default-background: white;
    --ck-color-button-default-disabled-background: white;
    --ck-color-button-default-hover-background: white;

    --ck-color-button-save: #9bcd69;

    --ck-color-switch-button-inner-background: var(--ck-color-base-background);
    --ck-color-switch-button-off-background: hsl(0, 0%, 69%);
    --ck-color-switch-button-on-background: var(--ck-color-button-action-background);

    /* -- Dropdown ------------------------------------------------------------------------------ */

    --ck-color-dropdown-panel-background: var(--ck-color-base-background);
    --ck-color-dropdown-panel-border: var(--ck-color-base-border);

    /* -- Input --------------------------------------------------------------------------------- */

    --ck-color-input-background: var(--ck-color-base-background);
    --ck-color-input-border: hsl(0, 0%, 78%);
    --ck-color-input-error-border: var(--ck-color-base-error);
    --ck-color-input-text: var(--ck-color-base-text);
    --ck-color-input-disabled-background: hsl(0, 0%, 95%);
    --ck-color-input-disabled-border: hsl(0, 0%, 78%);
    --ck-color-input-disabled-text: hsl(0, 0%, 36%);

    /* -- List ---------------------------------------------------------------------------------- */

    --ck-color-list-background: var(--ck-color-base-background);
    --ck-color-list-button-hover-background: white;
    --ck-color-list-button-on-background: var(--ck-color-base-active);
    --ck-color-list-button-on-background-focus: var(--ck-color-base-active-focus);
    --ck-color-list-button-on-text: var(--ck-color-base-background);

    /* -- Panel --------------------------------------------------------------------------------- */

    --ck-color-panel-background: var(--ck-color-base-background);
    --ck-color-panel-border: var(--ck-color-base-border);

    /* -- Toolbar ------------------------------------------------------------------------------- */

    --ck-color-toolbar-background: #525259;
    --ck-color-toolbar-border: #525259;

    /* -- Tooltip ------------------------------------------------------------------------------- */

    --ck-color-tooltip-background: lightyellow;
    --ck-color-tooltip-text: #525259;

    /* -- Engine -------------------------------------------------------------------------------- */

    --ck-color-engine-placeholder-text: hsl(0, 0%, 76%);

    /* -- Upload -------------------------------------------------------------------------------- */

    --ck-color-upload-bar-background: hsl(209, 92%, 70%);
    --ck-color-upload-infinite-background: hsla(0, 0%, 0%, 0.1);

    /* -- Link -------------------------------------------------------------------------------- */

    --ck-color-link-default: hsl(240, 100%, 47%);
    --ck-color-link-selected-background: hsla(201, 100%, 56%, 0.1);

    /* Overrides the border radius setting in the theme. */
    --ck-border-radius: 2px;

    /* Overrides the default font size in the theme. */
    --ck-font-size-base: 14px;

    /* Helper variables to avoid duplication in the colors. */
    --ck-custom-background: hsl(270, 1%, 29%);
    --ck-custom-foreground: hsl(255, 3%, 18%);
    --ck-custom-border: hsl(300, 1%, 22%);
    --ck-custom-white: hsl(0, 0%, 100%);

    /* -- Overrides the default colors used by the ckeditor5-widget package. -------------------- */

    --ck-color-widget-blurred-border: hsl(0, 0%, 87%);
    --ck-color-widget-hover-border: hsl(43, 100%, 68%);
    --ck-color-widget-editable-focus-background: var(--ck-custom-white);

}

**Comment by Reinmar** [comment]
Did you check whether some of your styles are not overriding editor styles?

**Comment by addsimm** [comment]
Yes. I looked through my css thoroughly and do not see anything that would affect the dropdown widths and the width of the items in the toolbar is unconstrained.

**Comment by Reinmar** [comment]
OK, so if those are not your styles, then what did you change that broke the layout of these dropdowns? There must be something because they just work for everyone else. So, there's something specific in your case. I'd recommend just removing pieces of your page's styles/JS/whateverelseisthere and checking when dropdowns will start to work again.

**Comment by addsimm** [comment]
Thanks I did that already.  I guess I will try again. Keep in mind that the drop downs work, they are just squeezed in the default position, but not the menus themselves.

**Comment by Reinmar** [comment]
I know. That's why I'm saying it's most likely your stylesheet. Probably affecting the flex styling of the `<button>` element.

**Comment by addsimm** [comment]
I stripped everything out and placed the above code in its own html page (without my custom CSS) and the result
![Screen Shot 2019-11-20 at 8 55 40 AM](https://user-images.githubusercontent.com/2389450/69260216-66618380-0b74-11ea-8b66-ea6c60d9a470.png)
 is the same, without the color - see screenshot.

**Comment by Reinmar** [comment]
Could you create a simple repo with all the code and instructions how to build it, so we could take a look?

**Comment by addsimm** [comment]
can you look at the html page? I can take out any other dependencies.

**Comment by Reinmar** [comment]
Which HTML page?

**Comment by addsimm** [comment]
the one i will send you

**Comment by Reinmar** [comment]
Yes, of course. As long as it's minimal – this is – it contains only the things needed to reproduce the issue.

**Comment by addsimm** [comment]
of course - I commented out all the extraneous code, which I also did in my last test

**Comment by Reinmar** [comment]
I'm sorry, but this is not a valid HTML page so I cannot test it. It's part of some template and it doesn't show an editor.

**Comment by addsimm** [comment]
Can you please leave this open; I will try to create the html file within a week

**Comment by Mgsy** [comment]
Thanks for the information. So, please post your file here and after that, I'll reopen the issue.
