### ISSUE TITLE
i want to img src using getData method

### ISSUE THREAD

**Issue by KIM-DONGWON** [ckeditor/ckeditor5#5708]
I would like to implement upload via UploadAdapter and get the content written in the editor via getData.
But the attributes of img src disappear and the image tag comes out as
`<p>12331</p><figure class="image"><img></figure>`

`<img src ="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAQAAAD8x0bcAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATBJREFUKM+FkssrRHEUx8f7kbGSraRoNmKPCWXDgqWiLJS/4JOdxmMhappkYyMrZmGDhQxKyU7URJZkIws2s/Ee33vvuGfujOi7ON9zzvee87vnnBCh/2G0l6ZAqplooWiKd7YCom3emDRRGQmy7NLCAle88kKaOXn7isYp9UQ9fLHEEM98cMCikBJ7YpAVZbp/2rXTp+LntPnNIlyoZpROe1MV91wTdnmH4Nh6bril0kRj6t6fq3EieGxA0VETbfDgNzJRCY+sm+iIU9dm8+D4ZxyaaI9L18aEO8Gxjp9mx0TzGmVDUbtGDSJmoojmsZxLJQSPxfmkNX8tawqMB9YyoQ9Xg7ur5liP3aSLGmo15aS8lOZXcAUVzJLx/y3DDOXFp+IgzAjTwjB1v9/TH/gG+LTpjGw2qEQAAAAASUVORK5CYII="><figcaption class="ck-placeholder ck-editor__editable ck-editor__nested-editable" data-placeholder="Enter image caption" contenteditable="true"><br data-cke-filler="true"> </figcaption>`

If i do getData() again after setData() text as above, img src will come out normally.

`<figure class="image"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAQAAAD8x0bcAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATBJREFUKM+FkssrRHEUx8f7kbGSraRoNmKPCWXDgqWiLJS/4JOdxmMhappkYyMrZmGDhQxKyU7URJZkIws2s/Ee33vvuGfujOi7ON9zzvee87vnnBCh/2G0l6ZAqplooWiKd7YCom3emDRRGQmy7NLCAle88kKaOXn7isYp9UQ9fLHEEM98cMCikBJ7YpAVZbp/2rXTp+LntPnNIlyoZpROe1MV91wTdnmH4Nh6bril0kRj6t6fq3EieGxA0VETbfDgNzJRCY+sm+iIU9dm8+D4ZxyaaI9L18aEO8Gxjp9mx0TzGmVDUbtGDSJmoojmsZxLJQSPxfmkNX8tawqMB9YyoQ9Xg7ur5liP3aSLGmo15aS8lOZXcAUVzJLx/y3DDOXFp+IgzAjTwjB1v9/TH/gG+LTpjGw2qEQAAAAASUVORK5CYII="></figure>`

How can I get the src of the base64 path of the image uploaded through the editor using getData()?

**Comment by ayelet-hb** [comment]
Hi, we need this ability in our system? can you link to the task? any timeline on that?
Thanks :)

**Comment by mlewand** [comment]
@ayelet-hb this feature has been implemented for some time already. There's a dedicated plugin for base64 image uploading and it's documented in the [Base64 image upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html) guide.

**Comment by ayaniv** [comment]
Hi @mlewand, After using a custom upload adapter, the image is passed to the ckeditor using blob like this: `editor.execute( 'imageUpload', {file: blob});`
But, `editor.getData()` returns blank image tag like @KIM-DONGWON got: `<p>12331</p><figure class="image"><img></figure>`

Question is, why getData() is not returning the image blob?
How to overcome this situation?
I tried to use the plugin that you mentioned, but it didn't help.
What am i missing?

**Comment by Isaacn123** [comment]
@ayaniv  did you get the Answer to that. am facing the same situation here....
