### ISSUE TITLE
i want to img src using getData method

### ISSUE THREAD

**Issue by KIM-DONGWON** [ckeditor/ckeditor5#5709]
I would like to implement upload via UploadAdapter and get the content written in the editor via getData.
But the attributes of img src disappear and the image tag comes out as
`<p>12331</p><figure class="image"><img></figure>`

`<img src ="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAQAAAD8x0bcAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATBJREFUKM+FkssrRHEUx8f7kbGSraRoNmKPCWXDgqWiLJS/4JOdxmMhappkYyMrZmGDhQxKyU7URJZkIws2s/Ee33vvuGfujOi7ON9zzvee87vnnBCh/2G0l6ZAqplooWiKd7YCom3emDRRGQmy7NLCAle88kKaOXn7isYp9UQ9fLHEEM98cMCikBJ7YpAVZbp/2rXTp+LntPnNIlyoZpROe1MV91wTdnmH4Nh6bril0kRj6t6fq3EieGxA0VETbfDgNzJRCY+sm+iIU9dm8+D4ZxyaaI9L18aEO8Gxjp9mx0TzGmVDUbtGDSJmoojmsZxLJQSPxfmkNX8tawqMB9YyoQ9Xg7ur5liP3aSLGmo15aS8lOZXcAUVzJLx/y3DDOXFp+IgzAjTwjB1v9/TH/gG+LTpjGw2qEQAAAAASUVORK5CYII="><figcaption class="ck-placeholder ck-editor__editable ck-editor__nested-editable" data-placeholder="Enter image caption" contenteditable="true"><br data-cke-filler="true"> </figcaption>`

If i do `getData() `again after `setData()` text as above, img src will come out normally.

`<figure class="image"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAQAAAD8x0bcAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATBJREFUKM+FkssrRHEUx8f7kbGSraRoNmKPCWXDgqWiLJS/4JOdxmMhappkYyMrZmGDhQxKyU7URJZkIws2s/Ee33vvuGfujOi7ON9zzvee87vnnBCh/2G0l6ZAqplooWiKd7YCom3emDRRGQmy7NLCAle88kKaOXn7isYp9UQ9fLHEEM98cMCikBJ7YpAVZbp/2rXTp+LntPnNIlyoZpROe1MV91wTdnmH4Nh6bril0kRj6t6fq3EieGxA0VETbfDgNzJRCY+sm+iIU9dm8+D4ZxyaaI9L18aEO8Gxjp9mx0TzGmVDUbtGDSJmoojmsZxLJQSPxfmkNX8tawqMB9YyoQ9Xg7ur5liP3aSLGmo15aS8lOZXcAUVzJLx/y3DDOXFp+IgzAjTwjB1v9/TH/gG+LTpjGw2qEQAAAAASUVORK5CYII="></figure>
`

How can I get the src of the base64 path of the image uploaded through the editor using `getData()`?

**Comment by Mgsy** [comment]
Hi! I'm not able to reproduce your issue. After enabling [Base64UploadAdapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html) in my build, uploading an image and executing `editor.getData()` I've successfully received HTML with `base64` string in `src` attribute. 

Can you describe exact steps to reproduce?

**Comment by KIM-DONGWON** [comment]
Thank you for your answer.

Thank you for your answer.

```
            class MyUploadAdapter {
                
                constructor( loader ) {
                    // The file loader instance to use during the upload.
                    this.loader = loader;
                }

                // Starts the upload process.
                upload() {
                    return this.loader.file
                        .then(file => new Promise((resolve, reject) => {
                            
                        }) 
                    );
                }

                // Aborts the upload process.
                abort() {
                    if ( this.xhr ) {
                        this.xhr.abort();
                    }
                }

            }

            function MyCustomUploadAdapterPlugin( editor ) {
                editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
                    // Configure the URL to the upload script in your back-end here!
                    return new MyUploadAdapter( loader );
                };
            }

            ClassicEditor
                .create( document.querySelector( '#editor' ), {
                    extraPlugins: [ MyCustomUploadAdapterPlugin ],
                })
                .then(function (editor) {
                    editorData  = editor;         
                })
                .catch( error => {
                    console.log( error );
                });
```

After button click 
console.log(editorData.getData());
`<figure class="image"><img></figure><p>here is text</p><p>test</p><p>this is test</p>`

**Comment by KIM-DONGWON** [comment]
Thank you!
I changed the upload as below by referring to Base64UploadAdapter.js in github.
It's working normally.
Thank you!!

```
                upload() {
                    var reader  = new FileReader();

                    return new Promise( ( resolve, reject ) => {
                        reader.addEventListener( 'load', () => {
                            resolve( { default: reader.result } );
                        });

                        reader.addEventListener( 'error', err => {
                            reject( err );
                        });

                        reader.addEventListener( 'abort', () => {
                            reject();
                        });                    

                        this.loader.file.then( file => {
				            reader.readAsDataURL( file );
            			});                        
                    })
                }
```

**Comment by Mgsy** [comment]
Great to hear that you managed to solve your issue :)
