### ISSUE TITLE
SimpleUploadAdapter - misleading documentation

### ISSUE THREAD

**Issue by zehawki** [ckeditor/ckeditor5#5710]
Re this page: https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html

Having spent hours on this, and reading a gadzillion SO and medium posts and trying many things myself, I can confidently say that the documentation on this bit is quite misleading. 

This line in particular is the source of endless confusion and run around - _The @ckeditor/ckeditor5-upload package is available by default in all official editor builds. You do not have to install it, if you are extending one._

Why not add/replace it with the [accurate info as mentioned here by](https://github.com/ckeditor/ckeditor5/issues/2176) @Mgsy on the excellent issue submission by @metalelf0

> If you'd like to enable SimpleUploadAdapter, you have to create a custom build which will include this plugin. Please, see our Installing plugins guide. After enabling it in your build, you should configure it.

**Comment by Reinmar** [comment]
Thanks for reporting this! I thought we fixed this description but apparently we forgot to do that 🤦‍♂️ Going to do that in the current iteration.
