### ISSUE TITLE
How to disable filler in CKEditor 5?

### ISSUE THREAD

**Issue by TatianaAU** [ckeditor/ckeditor5#5713]
If the text opened in ckeditor 5 contains empty paragraph `<p><br></p>`
the existing `<br>` is ignored and another one is added:
`<p><br><br data-cke-filler="true"></p>`

This behaviour is not expected as it increases the spaces between the paragraphs in the letter. How to disable the filler?

Browser: iOS WKWebKit, Android WebView, Web Chrome
OS: iOS, Android, Windows
CKEditor version: ckeditor 5, inline, v15.0.0
Installed CKEditor plugins: Essentials,
	Autoformat,
	Bold,
	Italic,
	Underline,
	BlockQuote,
	EasyImage,
	Heading,
	Image,
	ImageStyle,
	Link,
	List,
	Paragraph,
	Table,
	TableToolbar,
	Autosave,
	Alignment,
	Subscript,
	Superscript,
	Strikethrough,
	Font

**Comment by Reinmar** [comment]
It seems to be a DUP of https://github.com/ckeditor/ckeditor5/issues/5564. AFAICT, there's a bug. We'll be looking into this shortly.
