### ISSUE TITLE
Using Plugins when loading from CDN

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ckeditor/ckeditor5#5718]
## 📝 Provide a description of the new feature
It would be nice if the plugins are available from CDN, especially the Base64UploadAdapter.

When having an old  classic Asp-application the introduction of npm seems to be an uneeded overhead

*What is the expected behavior of the proposed feature?*
Remove need for making custom builds
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, thanks for the feedback. We're aware that the current way of adding plugins isn't convenient and we'd like to improve it. 

However, solving this issue isn't trivial and requires many changes. Please, see the discussion in the proper ticket - https://github.com/ckeditor/ckeditor5/issues/667.

**Comment by Mgsy** [comment]
Hi, sorry for closing the ticket - I've made it by mistake :) 

@mlewand can you take a look at it?

**Comment by Reinmar** [comment]
Currently, it's not possible to add plugins without making a new build of the editor, unless the editor is integrated from source. So, loading them from CDN would not work. 

There's a ticket for allowing extending builds without rebuilding them (https://github.com/ckeditor/ckeditor5/issues/667) and I think that we can close this ticket as a DUP of that one.

**Comment by ThorvaldAagaard** [comment]
OK, but the I think the Base64UploadAdapter should be included in the default package

**Comment by Reinmar** [comment]
I agree. We've been thinking about this too. I reported a ticket for this: https://github.com/ckeditor/ckeditor5/issues/5751.
