### ISSUE TITLE
"View source" functionality

### ISSUE THREAD

**Issue by Maxhou00** [ckeditor/ckeditor5#5719]
I think this functionality is important and it's better to keep discussing about it instead of acting like an ostriche and locking the topic.

You can see there on the issue #592 you locked that the view source functionality is more important than what you thought
So please consider more about it or do what you said

> We will support CKEditor 4 until 2023

We cannot use CKEDITOR 4 only for this because there are still many bugs on it for example we cannot copy/paste on android.

**Comment by wwalc** [comment]
We are fully aware that view source is important for many users, but at the same time please note that plenty of comments in the closed thread are not bringing anything new to this topic and their quality is getting worse. 

Believe me, if this was something that can be done in a month or two, we'd already done that. Unfortunately, it's a huge topic. So for now, to avoid spending more and more time to explain the same thing over and over again we prefer to lock this topic and any further clones like this. The time we will save this way would be spent on: writing documentation, answering other GitHub where our reply can indeed help someone and on doing slowly things that bring us closer to the "view source" solution (like internal planning, recruitment) and so on.
