### ISSUE TITLE
Autoformat --- for horizontal rule

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#5720]
## 📝 Provide a description of the new feature

Typing `---` should insert horizontal rule just like in Markdown (btw this is used below in this issue template). This was mentioned in the #1365 but marked as "not a part of MVP".

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
Looks like this is pretty easy to add:

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-autoformat/src/autoformat.js#L165-L167

**Comment by Reinmar** [comment]
The tricky thing is that autoformat is about formatting and here we want to insert something. We'd need to check whether it'll actually work. Unless, you checked it already?

**Comment by neongreen** [comment]
Haven't checked, unfortunately. It didn't occur to me there could be a difference between formatting and insertion.

**Comment by maxbarnas** [comment]
A few interesting cases regarding this autoformatting feature:

*   `---^foobar` creates new paragraph with `foobar` below the newly created horizontal line.
*   Blockquote allows the horizontal line to be created inside itself.
*   `---` inside empty headings leaves the heading, then creates the horizontal line, then a new paragraph.
*   `---^heading` leaves one heading, creates a horizontal line, and creates a new heading with the original content, `heading`.

**Comment by maxbarnas** [comment]
Typical behavior in other editors:

*   CKE5
    *   \-- => – (en-dash)
    *   \--- => — (em-dash)
*   CKE4
    *   none? 
*   Notion:
    *   \-- => — (em-dash)
    *   \--- => horizontal line
*   LibreOffice Writer
    *   \-- => — (em-dash)

To be contd.
