### ISSUE TITLE
Market CKEditor as Markdown WYSIWYG editor

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#5721]
## 📝 Provide a description of requested docs changes

Just an idea - in certain communities Markdown is very popular and essentially gold standard for  text editing, documentation, publishing etc. Many apps use split view approach to editing where you enter markdown in one pane and it is rendered in another pane - I consider this pretty bad UX, but there's also a new breed of WYSIWYG markdown text editors which try to combine the best of both worlds - simplicity and "just text" writing and realtime feedback and rendering all in one.

And I think that CKEditor is actually such an editor - it supports [Markdown output](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html) but also a bit hidden [Markdown input](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html).

The problem is that it's not well known that CKEditor can work like a complete Markdown WYSIWYG since it is not marketed as such. Those two critical features mentioned above are isolated, not put into larger context. Autoformat documentation does not even mention it uses Markdown syntax.

Of course CKEditor does not support Markdown perfectly and in some aspects probably never will, but there is a big range of what people actually need/want from Markdown - e.g. for some it's mostly about having mostly keyboard oriented writing using familiar syntax without toolbar clicking. What CKEditor loses on imperfect Markdown support gains on the feature richness and maturity compared to those other markdown WYSIWYGs.

What I had originally in mind was that you could start by putting up a documentation page and/or blog post "How to configure CKEditor as a Markdown WYSIWYG" to spread the awareness and get some hits from google.

**Comment by polarathene** [comment]
The markdown support should be improved with [a recent PR updating it](https://github.com/ckeditor/ckeditor5-markdown-gfm/pull/29)? No idea how that impacts the autoformatting feature.

One of the devs I work with evaluated CKEditor but stated it didn't support Markdown input(as a source, although I guess one could convert markdown to html each time?) or a editing mode. They didn't seem to be aware of this inline editing support for Markdown, probably because as this issue cites, it's not easily discoverable, I only found out after finding this issue and trying it out.

Reddit provides a toggle to switch between richtext and raw markdown editors, while Github does raw markdown with GUI toolbar support. Probably should be a separate issue but would be nice to see CKEditor have that sort of flexibility if possible. Another variant uses raw markdown but applies styles to the font style and size based on markdown features while still retaining the raw markdown syntax.

**Comment by fredck** [comment]
> One of the devs I work with evaluated CKEditor but stated it didn't support Markdown input(as a source, although I guess one could convert markdown to html each time?) or a editing mode.

Have you checked the following at the CKEditor 5 documentation?  
[https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html)

A properly configured editor definitely accepts markdown on input and output.

**Comment by fredck** [comment]
> Reddit provides a toggle to switch between richtext and raw markdown editors, while Github does raw markdown with GUI toolbar support. Probably should be a separate issue but would be nice to see CKEditor have that sort of flexibility if possible.

CKEditor will cover the richtext editor part. Then, it's up to the implementation to decide what kind of editing workflows are necessary, eventually making it possible to switch between CKEditor and any other kind of editor (markdown or not).

**Comment by godai78** [comment]
This issue https://github.com/ckeditor/ckeditor5/issues/7924 nicely fit into this aim, too.

**Comment by godai78** [comment]
"How to configure CKEditor as a Markdown WYSIWYG" - well, that would be seemingly a simple taskt. Just use autoformatting and Markdown output ;)

**Comment by zadam** [comment]
Yes. I know that, you know that. 

But people evaluating CKEditor as a component for their new application don't know that. 

These features are not well advertised. [Autoformatting](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) page doesn't even mention that the syntax is actually Markdown. If you don't closely read this documentation (which you typically do once you already made your decision to use CKEditor), you won't realize CKEditor has these capabilities.

**Comment by godai78** [comment]
Well, it DOES mention now, it's just waiting for a review.

**Comment by godai78** [comment]
@zadam, I guess you may like this blog post: https://ckeditor.com/blog/CKEditor-5-the-best-open-source-Markdown-editor/ ;)

**Comment by zadam** [comment]
@godai78 Awesome!
