### ISSUE TITLE
Whats the new way for styleset dropdown?

### ISSUE THREAD

**Issue by alexander-schranz** [ckeditor/ckeditor5#5723]
## 📝 Provide a description of the new feature

*What is the expected behavior of the proposed feature?*

Its maybe more a question. What is in ckeditor 5 the best way to add a styleset. I was wondering why there is a heading configuration but no styleset configuration.

What I need is to define a tag e.g. `span` which will have a class `text-class` so example configuration:

So something like this: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_stylesSet.html

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! CKEditor 5 has its own data model and each new element/attribute should be introduced in [Schema](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html) and have a proper [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html). In [`conversion#elementToElement`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-elementToElement) example, you can see how to define custom styles to the element.

**Comment by alexander-schranz** [comment]
@Mgsy thx for the fast reponsive! Do you have any tutorial to create a Toolbar Dropdown with different elements?

**Comment by Mgsy** [comment]
Unfortunately, we don't have such a tutorial. However, you can see how we do it in our features. You can take the [Heading ](https://github.com/ckeditor/ckeditor5-heading/blob/master/src/headingui.js) and [Alignment ](https://github.com/ckeditor/ckeditor5-alignment/blob/master/src/alignmentui.js) plugins as a reference.
