### ISSUE TITLE
Is it possible that on click of an image inside the editor, a plugin should do something like show an alert with the image details?

### ISSUE THREAD

**Issue by ajaybushel** [ckeditor/ckeditor5#5729]
More of a question.

I have created an image plugin which has a dropdown menu with fields like height, width, url  which allows us to insert an image into the editor.

Now I would like to extend.

Once an image is in the editor, and the user clicks on it, the same dialog which was used to insert the image (aforementioned image plugin) with its details. 

So for example, 

Step 1. I insert an image from "unsplash.com/myimage" with dimensions w120 and h120
Step 2. On click of the inserted image, the image plugin dialog should open again with its values prefilled (in this case, URL: "unsplash.com/myimage" with dimensions w120 and h120)

Anything like this is possible? I guess I am talking about communication between components/plugins

**Comment by mlewand** [comment]
Well, yes, it is possible to do that.

First you need to detect the case when the image gets selected. The best way for that would be to listen to model selection change. Based on this information you need to invoke your UI.
