### ISSUE TITLE
addTargetToLinks

### ISSUE THREAD

**Issue by KyooMario** [ckeditor/ckeditor5#5731]
I tried config setting below but checked or not the target is _blank.
Please advise:

`link: {
        // Automatically add target="_blank" and rel="noopener noreferrer" to all external links.
        //addTargetToExternalLinks: true,

        // Let the users control the "download" attribute of each link.
        decorators: {
            addTargetToLinks: {
                mode: 'manual',
                label: 'Open in a new tab',
                attributes: {
                    target: '_blank',
                    rel: 'noopener noreferrer'
                }
            }
        }
    }`

**Comment by Mgsy** [comment]
Hi! Can you describe your issue more precisely? If you ask about links in a link balloon (inside the editor) it will always be `target=_blank` and it's expected behaviour. 

If you call `editor.getData()`, you'll see that those attributes have been added properly.

**Comment by KyooMario** [comment]
Thanks for the reply. We found out that in Edit mode the target is always _blank but in read mode it follows the expected behavior _self when disabled and _blank when enabled.
