### ISSUE TITLE
MathType plugin doesn't accept &amp; entity.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#5732]
## 📝 Provide detailed reproduction steps (if any)

Open editor with MathType plugin and execute `editor.setData('&amp;');`. 

### ✔️ Expected result

Character `& ` should be displayed just like in editor without MathType plugin. 

### ❌ Actual result

Error gets thrown: `Parse error - Error parsing XML`

## 📃 Other details

* Browser: Any
* OS: Any
* CKEditor version: 15.0
* Installed CKEditor plugins: Mathtype

---

**NOTE:** You can workaround this error by using `editor.setData('&amp;amp;');` instead of `editor.setData('&amp;');` .

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Closed a DUP in https://github.com/ckeditor/ckeditor5/issues/5675.

**Comment by Reinmar** [comment]
Another DUP: https://github.com/ckeditor/ckeditor5/issues/2030.

**Comment by thiagolobao** [comment]
Any update?

**Comment by FilipTokarski** [comment]
I checked it with the new version of MathType and it works now. Character `&` displays with no errors.

**Comment by FilipTokarski** [comment]
This issue is fixed in the new MathType version 7.19.0

**Comment by JMA12** [comment]
Still getting this error
