### ISSUE TITLE
Multiple images on the same block

### ISSUE THREAD

**Issue by castroCrea** [ckeditor/ckeditor5#5733]
## 📝 Provide a description of the new feature

*What is the expected behavior of the proposed feature?*
I would like to have multiple image on the same line features like the screen shots
It's good to compare screen shot or do story telling
<img width="768" alt="Capture d’écran 2019-11-14 à 00 52 49" src="https://user-images.githubusercontent.com/20707343/68814438-23d20f80-0679-11ea-9543-5372b77b8c41.png">

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Currently, images in CKEditor 5 are block elements, so there's no possibility to add two images in a single block. To allow that, we have to introduce inline images. Please, see the following ticket - https://github.com/ckeditor/ckeditor5/issues/2052.
