### ISSUE TITLE
contentsLangDirection configuration doesn't work in React component

### ISSUE THREAD

**Issue by goratt12** [ckeditor/ckeditor5#5735]
## 📝 Provide detailed reproduction steps (if any)

1. my configuration code:
<CKEditor
  className={classes.editor}
  editor={ ClassicEditor }
  data={article.content} 
  onChange={handleChange}
  config={ {
    **contentsLangDirection : 'rtl'**
   } }
 />
2. …
3. …

### ✔️ Expected result

I expect that the default text direction will be right to left but the config doesn't seem to change anything

### ❌ Actual result

no change in text direction

## 📃 Other details

* Browser: chrome
* OS: windows
* CKEditor version: 5
* Installed CKEditor plugins: none
![Capture](https://user-images.githubusercontent.com/23094928/68831740-e2ad2000-06b7-11ea-92f5-a67f9078788a.PNG)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! In CKEditor 5, `contentsLangDirection` isn't a valid config property for setting a text direction. Please, see our [Setting the UI language](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#righttoleft-rtl-languages-support) guide to learn how to set it properly.
