### ISSUE TITLE
When I change style in the middle of word, editor breaks down.

### ISSUE THREAD

**Issue by nikitasakov** [ckeditor/ckeditor5#5736]
## 📝 Provide detailed reproduction steps (if any)

1. Type word
2. Change style on toolbar
3. Continue typing

### ✔️ Expected result

Style changed and I am able to continue typing.

### ❌ Actual result

My word is duplicated with a new style and I got error. Editor breaks down. 

**DEMO:** https://youtu.be/EeHYM_0wx5c

## 📃 Other details

* Device: Pixel 1/2/3 (Got this bug on Pixels, OnePlus 6T/7)
* Browser: Mobile Google Chrome 78.0.3904.62
* OS: Android 8.0.0 / 9.0.0
* CKEditor version: 15.0.0
* Installed CKEditor plugins:

**By ckeditor:** ```@ckeditor/ckeditor5-essentials, @ckeditor/ckeditor5-adapter-ckfinder, @ckeditor/ckeditor5-autoformat, @ckeditor/ckeditor5-basic-styles, @ckeditor/ckeditor5-block-quote, @ckeditor/ckeditor5-ckfinder, @ckeditor/ckeditor5-easy-image, @ckeditor/ckeditor5-heading, @ckeditor/ckeditor5-image, @ckeditor/ckeditor5-indent, @ckeditor/ckeditor5-link, @ckeditor/ckeditor5-list, @ckeditor/ckeditor5-media-embed, @ckeditor/ckeditor5-paragraph, @ckeditor/ckeditor5-paste-from-office, @ckeditor/ckeditor5-table```

**Other**: ```@wwalc/ckeditor5-emoji```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. CKEditor 5 doesn't work well with GBoard and we're aware of this specific issue. It has been reported here - https://github.com/ckeditor/ckeditor5/issues/1786. 

Feel free to add 👍 to the first post in the mentioned ticket to bump its popularity and join the discussion.
