### ISSUE TITLE
[Edge] Applying the inline style to the text scrolls the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#574]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html.
2. Make the editor scrollable. 
3. Select some part of the text from the top of the editor.
4. Scroll down.
5. Press <kbd>Ctrl</kbd> + <kbd>B</kbd>.

## Current result
The editor has been scrolled up.

## Expected result
The scrollbar shouldn't change its position.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31070630-52f171d0-a761-11e7-825e-74349f88d89d.gif)

## Other information
OS: Windows 10
Browser: Edge 16
Release: 0.11.0

**Comment by oleq** [comment]
Are you sure it does not happen in Chrome or Firefox too, @Mgsy?

**Comment by Reinmar** [comment]
I saw it happening in Edge only. It's some weeeird Edge bug so I didn't pay much attention to it in the past.

**Comment by Mgsy** [comment]
>Are you sure it does not happen in Chrome or Firefox too, @Mgsy?

Yes, I've checked other browsers and this one occurs only in Edge.

**Comment by FilipTokarski** [comment]
This bug is fixed in the new upcoming Edge v.79.0.309.56

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
