### ISSUE TITLE
Is there a Code-block/snippet plugin coming?

### ISSUE THREAD

**Issue by mstermaaten** [ckeditor/ckeditor5#5741]
## 📝 Provide a description of the new feature

In the CKeditor 4 there was a code-snippet plugin https://ckeditor.com/docs/ckeditor4/latest/features/codesnippet.html

I would love to see this in CKeditor 5 as well!

*What is the expected behavior of the proposed feature?

![Schermafdruk 2019-11-15 11 21 51](https://user-images.githubusercontent.com/49290062/68936132-2d06cd80-079a-11ea-9480-05e79b8e1649.png)

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mstermaaten** [comment]
Now we only have the basic text styling code option which becomes ugly when writing multiple lines of code syntax.

**Comment by Mgsy** [comment]
Hi, the code blocks plugin will be available in the next release and currently is under review. Please, see our [roadmap for the current iteration](https://github.com/ckeditor/ckeditor5/issues/5653) to see all upcoming changes.
