### ISSUE TITLE
[Docs] Applying the link to the header changes its font-weight in the editor examples

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#575]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/inline-editor.html.
2. Select the second header from the first editable.
3. Apply the link.

## Current result
Header's `font-weight` has changed.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31071077-fbee1ad0-a762-11e7-94ad-5354f322101a.gif)

**Comment by oleq** [comment]
It's an issue in docs, not in the editor. There's a `.formatted a { font-weight: 400; }` rule that causes this. We need to figure out why it's there first and then address the issue.

**Comment by Reinmar** [comment]
I guess you're not working on this, so I'll fix it.

**Comment by Reinmar** [comment]
Fixed in Umberto. I couldn't find out why this style existed.
