### ISSUE TITLE
Creating a Modal window for Image plugin in ckeditor5-ui

### ISSUE THREAD

**Issue by cksachdev** [ckeditor/ckeditor5#5756]
## Provide a description of the task
I am trying to create a Modal window to open image catalog and then insert to ckeditor5. Is there a Modal window with boilerplate events and methods in ckeditor5-ui? Please point me to the right links to implement a modal window. 

If there is a Slack or Discord channel for developers, please share a link to join the same.

**Comment by Mgsy** [comment]
Hello, we don't provide this kind of ready-to-use UI components, however, CKEditor 5 UI library is flexible and allows to create your own elements which could be used in the editor. Please, [see the guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/ui-library.html#views) about it. I'd also recommend you looking at our plugins code to see how our team implements custom views.

**Comment by cksachdev** [comment]
@Mgsy I have looked at existing plugin code and ckeditor5-ui repo. Please share the specific repo link where I could see a Modal window. I am looking for a Modal popup window like wiris or Easy Image(from ckeditor4). As of now I am able to achieve it by firing an event on window object and adding a listener inside ckeditor5 plugin. Although that makes my popup/modal work but doesn't seem like a right way to achieve it. 
Kindly guide on how to achieve the same inside Plugin files.
cc: @vaibhavbhuva @vrayulu @nik720

**Comment by Mgsy** [comment]
@cksachdev, I'm afraid that we don't have such an example. In my previous message, I left a link to the guide which shows how to create custom elements. You should create your own template and add proper CSS styling. 

You can also use some CSS framework, like Bootstrap, which has modals included and attach them to the editor. Please, see [Third-party UI](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/external-ui.html) and [Compatibility with Bootstrap](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html#compatibility-with-bootstrap) guides.
