### ISSUE TITLE
LaTeX inserted using MathType $$ syntax cannot be loaded

### ISSUE THREAD

**Issue by smmbetterstudents** [ckeditor/ckeditor5#5757]
A little background knowledge, as the feature doesn't seem to be very well documented, but explained by Wiris:
With the MathType plugin installed in a CKEditor 5 instance, it is possible to write LaTeX directly in the editor by wrapping it between `$$`, ie. `$$\frac{x}{3}$$`, and then edit it using the MathType-editor by double clicking on it or placing the cursor on it and click the MathType-button in the toolbar.

## 📝 Provide detailed reproduction steps (if any)
1. Insert LaTeX wrapped in `$$`, ie. `$$\frac{x}{3}$$`
2. Get data from the editor instance using `getData`
3. Load content again, either using `setData` or setting it as `initialData` and reload the page

### ✔️ Expected result
When I load data again, I should see the $$ wrapped LaTex and should be able to edit it as LaTeX in the MathType UI by double clicking on it or placing the cursor on it and click the MathType-button in the toolbar.

### ❌ Actual result
When I load data again, I get an empty preview image.

## 📃 Other details
The difference in markup from "normal" equations inserted using the MathType UI and using $$ latex syntax is that the ones inserted using $$ gets wrapped in a <semantics> tag and gets a <annotation> tag containing the inserted LaTex.

To me it looks like the editor doesn't understand the difference between equations inserted this way, and "normal" equations inserted using the MathType UI, and then tries to preview them which it should not.

* Browser: Chrome 78.0.3904.97
* OS: Windows 10 build 1903
* CKEditor version: CKEditor 5 15.0.0
* Installed CKEditor plugins: Default classic build + MathType

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, sorry for the late response. This issue is related to MathType and currently, Wiris is working on some architectural changes to improve the integration with CKEditor 5. After that, most issues should be solved (hopefully this one too).

**Comment by thiagolobao** [comment]
Any update?

**Comment by FilipTokarski** [comment]
This issue was fixed by the latest MathType for CKEditor5, version 7.24.0.
