### ISSUE TITLE
Can I show twitter/instagram posts in Ckeditor5 without using Embedly and Iframely

### ISSUE THREAD

**Issue by SerzhanHelena** [ckeditor/ckeditor5#5758]
In my project I use ckeditor5 to create articles. I want to add twitter, instagram posts in articles, but can not. When I create article and insert , for example, [](https://twitter.com/ckeditor/status/1027571541989572612) this post, in creating mode it looks :
![2019-11-18_18h13_43](https://user-images.githubusercontent.com/32465547/69145763-7418f980-0adf-11ea-9e25-13bd4ef33c88.png)
But after saving my article and clicking on it to view it, post is not showing. In inspector I see the following code:
`<figure class="media"><oembed url="https://twitter.com/ckeditor/status/1027571541989572612"></oembed></figure>`

In documentation I read that I shoul use Embedly or Iframely services to displaying posts. Can I do this without using these services? I want that after clicking on the article twitter post was shown. I try to use Embedly, everything is okay, but were there other way to showing twitter/instagram posts?
P.S. Inserting youtube video I could only after setting in config this field :

```
mediaEmbed: {
        previewsInData: true,
    }
```

**Comment by Mgsy** [comment]
Hi! Currently, this functionality isn't available, because the media embed plugin doesn't support asynchronous media preview generation. Please, take a look at https://github.com/ckeditor/ckeditor5/issues/2740 to learn more.

**Comment by SerzhanHelena** [comment]
Maybe can I create a custom plugin for it?
