### ISSUE TITLE
[Edge] The list displays incorrectly near the left aligned image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#576]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/inline-editor.html.
2. Select the image from the second editable.
3. Transform it into the `left aligned image`.
4. Transform the paragraph next to the image into some `list`.

## Current result
The list's bullet/number displays behind the image.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31071853-e7ef5334-a765-11e7-8563-38387382f763.gif)

## Other information
OS: Windows 10
Browser: Edge 16
Release: 0.11.0

**Comment by Reinmar** [comment]
This is a result in Chrome:

![image](https://user-images.githubusercontent.com/156149/31072369-e1d67624-a767-11e7-8f93-97c9e24c0008.png)

And this is a native problem anyway. We discussed this in https://github.com/ckeditor/ckeditor5-image/pull/140 and there's not much we can do. We can only break if further  by adding `overflow:hidden`.

Besides, it's like that for years and I don't remember people complaining (which is strange actually).
