### ISSUE TITLE
Error on insertContent

### ISSUE THREAD

**Issue by devaptas** [ckeditor/ckeditor5#5760]
I made a function to insertHTML in editor and scroll to selection after insert, but I'm having a trouble with it. Can be a bug?

```
DecoupledEditor.prototype.insertHtml = function (html) {
	const editor = this;
	const editing = editor.editing;
	const viewFragment = editor.data.processor.toView(html);
	const modelFragment = editor.data.toModel(viewFragment);
	editor.model.change(writer => {
		const modelRange = editor.model.insertContent(modelFragment);
		writer.setSelectionFocus(modelRange.end, 'end');
		scrollViewportToShowTarget({
			target: editing.view.domConverter.viewRangeToDom(editing.mapper.toViewRange(modelRange)),
			viewportOffset: 20
		});
	});
};
```

Example to insert:
```html
<p style="text-align:center;"><strong>ANGIORRESSONÂNCIA DOS VASOS CERVICAIS</strong></p><p><br>Técnica:<br>Exame realizado em aparelho de ressonância magnética de 1,5 Tesla, com aquisição de imagens em seqüências<br>multiplanares com bobinas específicas, ponderadas em T1 pós-contraste e sequências de angiorressonância com<br>contraste dos vasos cervicais.<br>Relatório:<br>Tronco braquiocefálico arterial D e artérias subclávias D e E de contornos regulares e calibres normais.<br>Artérias carótidas comuns, internas e externas de contornos irregulares, porém, sem áreas de afilamento significativo.<br>Artérias vertebrais com forma, contornos e calibre preservados.<br>Impressão diagnóstica: Angiorressonância magnética cervical dentro da normalidade.</p>
```

Error on console:

> VM1573:83085 Uncaught CKEditorError: unexpected-error {"originalError":{"message":"Cannot read property 'is' of undefined","stack":"TypeError: Cannot read property 'is' of undefined\n    at Mapper._findPositionIn (<anonymous>:13363:19)\n    at Mapper.on.priority (<anonymous>:12929:29)\n    at Mapper.fire (<anonymous>:86937:30)\n    at Mapper.toViewPosition (<anonymous>:13156:8)\n    at Mapper.toViewRange (<anonymous>:13118:113)\n    at Object.callback (<anonymous>:126912:68)\n    at Model._runPendingChanges (<anonymous>:21728:58)\n    at Model.change (<anonymous>:21143:17)\n    at DecoupledEditor../src/ckeditor.js.DecoupledEditor.insertHtml (<anonymous>:126908:15)\n    at Object.success (<anonymous>:129:44)","name":"TypeError"}}
>     at Function.rethrowUnexpectedError (<anonymous>:83137:9)
>     at Mapper.fire (<anonymous>:86970:59)
>     at Mapper.toViewPosition (<anonymous>:13156:8)
>     at Mapper.toViewRange (<anonymous>:13118:113)
>     at Object.callback (<anonymous>:126912:68)
>     at Model._runPendingChanges (<anonymous>:21728:58)
>     at Model.change (<anonymous>:21143:17)
>     at DecoupledEditor../src/ckeditor.js.DecoupledEditor.insertHtml (<anonymous>:126908:15)
>     at Object.success (<anonymous>:129:44)

**Comment by Mgsy** [comment]
Hello, I don't know how your `scrollViewportToShowTarget` function looks like, but it might be a cause of your problem. I've just run your code without using `scrollViewportToShowTarget` and it properly inserts provided HTML.

**Comment by tmendesilva** [comment]
It's a native function scrollViewportToShowTarget:
`import {scrollViewportToShowTarget} from '@ckeditor/ckeditor5-utils/src/dom/scroll';`

**Comment by Mgsy** [comment]
@tmendesilva, true, thanks 😄 

Anyway, I've checked it with `scrollViewportToShowTarget` and everything works as expected.
