### ISSUE TITLE
Simple upload adapter not working

### ISSUE THREAD

**Issue by yashspr** [ckeditor/ckeditor5#5767]
When I try to upload an image using the ckeditor5, I get an alertbox error saying **"Couldn't upload file: {filename}"**

My ckeditor config:

```
ClassicEditor
    .create(document.querySelector('#story-body'), {
        simpleUpload: {
            uploadUrl: 'http://localhost:7000'
        }
    })
    .then(editor => {
        console.log(editor);
    })
    .catch(error => {
        console.error(error);
    });
```

## 📝 Provide detailed reproduction steps (if any)

1. Cloned the ckeditor classic repo (`git clone https://github.com/ckeditor/ckeditor5-build-classic.git`)
2. Installed ckeditor5-upload (`yarn add @ckeditor/ckeditor5-upload`)
3. Imported it in src/ckeditor.js (`import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';`)
4. Added it to builtin plugins
5. rebuilt ckeditor (`yarn run build`)
6. Copied the contents in the `build` directory to my project directory.
### ✔️ Expected result

The image should be uploaded and a URL should be returned from the local server

### ❌ Actual result

I get an alert box error in the browser saying "Couldn't upload file: {filename}"

## 📃 Other details

* Browser: Firefox 70
* OS: Windows
* CKEditor version: 15.0
* Installed CKEditor plugins: ckeditor5-upload

A local server is running on my machine to handle the image upload but no request is even sent to the server. I just get the above error in the browser.

On further inspection in the browser, I saw XHR requests made to the server. I see that only an OPTIONS requests is made to the server and no POST request is sent.

---

Any kind of help would be appreciated. 
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by robclancy** [comment]
There could be many issues here. Unfortunately the real errors don't get shown. This has made it difficult when trying to test uploads ourselves.

**Comment by yashspr** [comment]
Is there anyway to debug the error? 
Or is there any other plugin with minimal setup to handle image uploads?

Any other solution to handle image uploads in ckeditor?

If it's of any help, my webserver is built with nodejs.

**Comment by Mgsy** [comment]
@yashspr, I've just checked it and the editor sends POST request after OPTIONS request. Maybe there's something that blocks your requests, i.e. CORS rules?

**Comment by yashspr** [comment]
@Mgsy You are right. It was CORS that was preventing the POST request. The cors error was mixed up among the other errors generated by js files, so I couldnt spot it. 

Thanks for the help!

**Comment by Mgsy** [comment]
I'm glad that you solved it :)

**Comment by mrborek** [comment]
it also happens when you've got together

`import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';`

and 

`import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';
`

Just remove UploadAdapter

**Comment by sakina1403** [comment]
Can we get the sample body of the POST request anywhere?

**Comment by GabrielCasasJs** [comment]
@yashspr podrias explicarme como pudiste solucionarlo? estoy con el mismo problema hace dias y no puedo resolverlo, me tira el mismo error que te tiraba a ti en su momento

**Comment by ntnull** [comment]
> I'm glad that you solved it :)

Hello, how did you solve the problem with CORS?

**Comment by yashspr** [comment]
> > 
> 
> how did you solve the problem with CORS?

My backend was written in Javascript (Node.js). I used the `cors` npm package to fix it.
