### ISSUE TITLE
[Chrome] Selection disappears from the link after few bold & unbold commands 

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#577]
## Steps to reproduce

1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/headings.html.
2. Click 3 times Bold icon. (Or Italic)

## Current result
Link at the end is not selected

## Expected result
Whole content should be selected

Browser: Chrome

**Comment by Reinmar** [comment]
This is Chrome's native issue with selection rendering. The selection is correct, but not fully visible. See https://github.com/ckeditor/ckeditor5-engine/issues/992
