### ISSUE TITLE
To-do list item styling in the output is lost after adding inline style to the item

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#5775]
## 📝 Provide detailed reproduction steps (if any)

1. Open the [to-do list manual test](http://localhost:8125/ckeditor5-list/tests/manual/todo-list.html).
2. Select a whole list item.
3. Add some styling.

### ✔️ Expected result

The proper styling in the output is preserved.

### ❌ Actual result

The styling in the output is lost.

## 📃 Other details

![bug_cke5](https://user-images.githubusercontent.com/20988892/69346130-90996b00-0c72-11ea-8caa-15fbba0fce34.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Let's make it a DUP of https://github.com/ckeditor/ckeditor5/issues/5779.
