### ISSUE TITLE
Chat with mentions - 

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5#5777]
## 📝 Provide detailed reproduction steps (if any)

1. following the doc for [Chat with mentions](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/chat-with-mentions.html#source-code)

### ✔️ Expected result
Working Chat with mentions

### ❌ Actual result

<details><summary>Console error</summary>
<p>
[WDS] Disconnected! client:172
[WDS] Hot Module Replacement enabled. client:48
[WDS] Live Reloading enabled. client:52
[HMR] Waiting for update signal from WDS... log.js:24
plugincollection-load: It was not possible to load the plugin. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-load
 
Object { plugin: ContextualBalloon() }
plugincollection.js:235
    loadPlugin plugincollection.js:235
CKEditorError: "plugincollection-plugin-not-loaded: The requested plugin is not loaded. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-plugin-not-loaded
 {"plugin":"ContextualBalloon"}"
    CKEditorError ckeditorerror.js:66
    get plugincollection.js:123
    init mentionui.js:78
 CKEditorError@http://localhost:8181/build/vendors~app.js:61339:3
get@http://localhost:8181/build/vendors~app.js:3383:10
init@http://localhost:8181/build/vendors~app.js:48638:34
_editor.js:90:12
Erreur d’analyse XML : mal formé
Emplacement : http://web.tcket.bellvision.local:8080/ticket/new
Numéro de ligne 1, Colonne 6 : new:1:6
Error: unexpected-error {"originalError":{"message":"svg is null","stack":"_updateXMLContent@http://localhost:8181/build/vendors~app.js:54130:20\nrender@http://localhost:8181/build/vendors~app.js:54106:8\ndecorate/<@http://localhost:8181/build/vendors~app.js:67326:32\nfire@http://localhost:8181/build/vendors~app.js:65197:30\ndecorate/this[methodName]@http://localhost:8181/build/vendors~app.js:67330:16\nViewCollection/<@http://localhost:8181/build/vendors~app.js:60162:10\nfire@http://localhost:8181/build/vendors~app.js:65197:30\nadd@http://localhost:8181/build/vendors~app.js:61626:8\nrender@http://localhost:8181/build/vendors~app.js:51921:18\ndecorate/<@http://localhost:8181/build/vendors~app.js:67326:32\nfire@http://localhost:8181/build/vendors~app.js:65197:30\ndecorate/this[methodName]@http://localhost:8181/build/vendors~app.js:67330:16\n_renderElementChildren@http://localhost:8181/build/vendors~app.js:57399:13\n_renderElement@http://localhost:8181/build/vendors~app.js:57132:8\n_renderNode@http://localhost:8181/build/vendors~app.js:57114:16\nrender@http://localhost:8181/build/vendors~app.js:56826:21\n_renderElementChildren@http://localhost:8181/build/vendors~app.js:57419:35\n_renderElement@http://localhost:8181/build/vendors~app.js:57132:8\n_renderNode@http://localhost:8181/build/vendors~app.js:57114:16\nrender@http://localhost:8181/build/vendors~app.js:56826:21\nrender@http://localhost:8181/build/vendors~app.js:60041:33\nrender@http://localhost:8181/build/vendors~app.js:56225:15\ndecorate/<@http://localhost:8181/build/vendors~app.js:67326:32\nfire@http://localhost:8181/build/vendors~app.js:65197:30\ndecorate/this[methodName]@http://localhost:8181/build/vendors~app.js:67330:16\nViewCollection/<@http://localhost:8181/build/vendors~app.js:60162:10\nfire@http://localhost:8181/build/vendors~app.js:65197:30\nadd@http://localhost:8181/build/vendors~app.js:61626:8\n_createRotatorView@http://localhost:8181/build/vendors~app.js:56051:27\nContextualBalloon@http://localhost:8181/build/vendors~app.js:55847:34\ninstantiatePlugin/<@http://localhost:8181/build/vendors~app.js:3541:20\ninstantiatePlugin@http://localhost:8181/build/vendors~app.js:3514:11\nloadPlugin@http://localhost:8181/build/vendors~app.js:3473:11\ninstantiatePlugin/</<@http://localhost:8181/build/vendors~app.js:3537:17\ninstantiatePlugin/<@http://localhost:8181/build/vendors~app.js:3518:33\ninstantiatePlugin@http://localhost:8181/build/vendors~app.js:3514:11\nloadPlugin@http://localhost:8181/build/vendors~app.js:3473:11\ninstantiatePlugin/</<@http://localhost:8181/build/vendors~app.js:3537:17\ninstantiatePlugin/<@http://localhost:8181/build/vendors~app.js:3518:33\ninstantiatePlugin@http://localhost:8181/build/vendors~app.js:3514:11\nloadPlugin@http://localhost:8181/build/vendors~app.js:3473:11\ninit@http://localhost:8181/build/vendors~app.js:3458:42\ninitPlugins@http://localhost:8181/build/vendors~app.js:2386:23\ncreate/<@http://localhost:8181/build/vendors~app.js:3910:12\ncreate@http://localhost:8181/build/vendors~app.js:3906:10\n./assets/js/libs/_editor.js@http://localhost:8181/build/app.js:59:94\n__webpack_require__@http://localhost:8181/build/runtime.js:786:30\nfn@http://localhost:8181/build/runtime.js:151:20\n./assets/js/app.js@http://localhost:8181/build/app.js:17:92\n__webpack_require__@http://localhost:8181/build/runtime.js:786:30\nfn@http://localhost:8181/build/runtime.js:151:20\n1@http://localhost:8181/build/app.js:491:18\n__webpack_require__@http://localhost:8181/build/runtime.js:786:30\ncheckDeferredModules@http://localhost:8181/build/runtime.js:46:23\nwebpackJsonpCallback@http://localhost:8181/build/runtime.js:33:19\n@http://localhost:8181/build/app.js:1:57\n","name":"TypeError"}} ckeditorerror.js:66
[WDS] Hot Module Replacement enabled. client:48
[WDS] Live Reloading enabled. client:52
</p>
</details>

## 📃 Other details
Using WebpackEncore and following [This repository](https://github.com/Kocal/webpack-encore-vue-ckeditor5) for configuraiton

* Browser: Firefox
* OS: W10
* CKEditor version: 15
* Installed CKEditor plugins:
    "dependencies": {
        "@ckeditor/ckeditor5-basic-styles": "^15.0.0",
        "@ckeditor/ckeditor5-build-classic": "^15.0.0",
        "@ckeditor/ckeditor5-editor-classic": "^15.0.0",
        "@ckeditor/ckeditor5-essentials": "^15.0.0",
        "@ckeditor/ckeditor5-link": "^15.0.0",
        "@ckeditor/ckeditor5-mention": "^15.0.0",
        "@ckeditor/ckeditor5-paragraph": "^15.0.0",
        "@ckeditor/ckeditor5-theme-lark": "^15.0.0",
    },
    "devDependencies": {
        "@ckeditor/ckeditor5-dev-utils": "^12.0.5",
        "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.5",
    }
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! If you use React, did you see https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source?

**Comment by kl3sk** [comment]
Hi!
No I didn't I use vanilla Javascript.

**Comment by Reinmar** [comment]
Hm... I think that the guide is a bit incorrect as it points you to "Installing plugins" as a prerequisite while it should really point you to https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source where you could learn how to configure webpack to understand CKEditor 5's SVGs and CSS (you need to configure webpack loaders correctly). Could you check if this information helps?

If not – could you post a simplified repo in which we could see this bug?

**Comment by kl3sk** [comment]
I will, but because I encountered a lot of issues with webpack and Ckeditor5 I search befaore asking.
I think I was in a good way when using this repo.
https://github.com/Kocal/webpack-encore-vue-ckeditor5

(Except no VueJS in my case). Could you confirm there is no issue in it ?

**Comment by kl3sk** [comment]
@Reinmar Thank enrething seems to work.
This repo is not up to date I think, and I see a `Encore` configuration that work perfectly for me.

Thanks i'll close
