### ISSUE TITLE
Adding a link to a to-do list item produces incorrect HTML

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#5779]
## 📝 Provide detailed reproduction steps (if any)

1. Open the to-do list manual test.
2. Create a new to-do list with 1 list item and a few words.
3. Select the first word.
4. Add a link.

### ✔️ Expected result

In the preview, the link is added only to the first word.

### ❌ Actual result

In the preview, the link is added to the whole list item.

## 📃 Other details

![bug_cke5](https://user-images.githubusercontent.com/20988892/69429820-c141d900-0d34-11ea-8c6b-7f9c4a9686d6.gif)

Related - https://github.com/ckeditor/ckeditor5/issues/5775

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @jodator @oskarwrobel – didn't we already talk about this? I think we even had it reported but I couldn't find a ticket.

**Comment by jodator** [comment]
Looks a bit similar to this: https://github.com/ckeditor/ckeditor5-list/pull/154.

**Comment by Reinmar** [comment]
Looks exactly like the last comment in this thread :D That's why it sounded familiar.

**Comment by Reinmar** [comment]
The data downcast is, unfortunately, really broken. Soft breaks also causes some interesting results:

```html
<ul class="todo-list">
  <li>
    <label class="todo-list__label">
      <input type="checkbox" disabled="disabled">
      <span class="todo-list__label__description">dsf</span>
    </label>
    <br>
    <label class="todo-list__label">
      <span class="todo-list__label__description">dsf</span>
    </label>
  </li>
</ul>"
```
