### ISSUE TITLE
[Chrome] Error throws in the image description after random typing

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#578]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/image.html or https://ckeditor5.github.io/
2. Type randomly in the image description

Error:
![screen shot 2017-10-02 at 12 44 24](https://user-images.githubusercontent.com/2768047/31074172-a01a8baa-a76f-11e7-9e8e-942e6b5fcc57.png)

**Comment by Reinmar** [comment]
Hm... confirmed. When I type blabla quick enough the error is thrown.

**Comment by Reinmar** [comment]
I can't reproduce this issue on http://localhost:8125/ckeditor5-image/tests/manual/caption.html though. And I can do this on http://localhost/ckeditor5/build/docs/ckeditor5/0.11.0/examples/builds/classic-editor.html. Interesting. It seems that page styling affects it.

**Comment by Reinmar** [comment]
Yeah, that's definitely due to styling because when I loaded the docs before Umberto generated their CSS, I could not reproduce this issue.

**Comment by ma2ciek** [comment]
It's interesting that styling might easily destroy the editor.

**Comment by Reinmar** [comment]
OK, for some reason, a common ancestor of these mutations is a text node. Such situation should not be handled by `_handleContainerChildrenMutations()`. I wonder what's inside the mutations array.

**Comment by Reinmar** [comment]
OK, it turns out that this is Grammarly:

![image](https://user-images.githubusercontent.com/156149/31076957-f56d6fe8-a77c-11e7-9862-a7d009c38dae.png)

It seems that in https://github.com/ckeditor/ckeditor5/issues/267 we missed that Grammarly kicks in in nested editables.

Before we'll ping Grammarly's team, we need to figure out whether we can't just add `.ck-editor__editable` to nested editables.

cc @oleq

**Comment by oleq** [comment]
We could add this class but it will require some refactoring of the styles across the project. There are many usages of the `.ck-editor__editable` in various stylesheets and we must understand their purpose, then rewrite the styles to consider the more generic role of the class.

**Comment by Reinmar** [comment]
@oleq, could you estimate how hard would this change be? And if it makes sense in general? I see that right now, nested editable has only the `.ck-editable` class... which is odd. Unification sound like a thing we should do.

**Comment by oleq** [comment]
The change is not hard but it is spread across multiple repositories and, most certainly, Letters too. I think the right moment to do this will be after https://github.com/ckeditor/ckeditor5/issues/420, though.

**Comment by oleq** [comment]
I cannot reproduce this issue. Can anyone confirm?

**Comment by Reinmar** [comment]
Not this one, but e.g. this:

![image](https://user-images.githubusercontent.com/156149/37666071-ef337a16-2c5e-11e8-8299-6f04a8770d04.png)

Grammarly inserts bazillion text nodes with spaces into the editor when you type some random letters quickly. It doesn't do that when it's completely disabled.

**Comment by oleq** [comment]
OK. I check that and the `.ck-editor__editable` class fixes the problem. I'll prepare a multi-repo PR.
