### ISSUE TITLE
ClassicEditor disable editing html attribute

### ISSUE THREAD

**Issue by medozeus** [ckeditor/ckeditor5#5784]
I have this simple Html

`<li id="thisisID"></li>`

after editing it in CKEditor it's removing the id by itself tried to disable it by 
` editor.config.allowedContent = true;`

but no effect didn't work

```
              ClassicEditor .create( document.querySelector( '#editor' ), {
								language: 'en'
								} )
                                .then( editor => {
				  editor.config.allowedContent = true;
                                        console.log( editor );
                                } )
                                .catch( error => {
                                        console.error( error );
                                } );
```

**Comment by Mgsy** [comment]
Hi! CKEditor 5 has own data model and accepts only elements/attributes which are allowed in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html). `allowedContent` is a CKEditor 4 property which isn't included to CKEditor 5.

 In your case, you should extend paragraph schema to accept your attributes and create a proper model <--> view [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html). Please, see our guide about [preserving custom content](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html).
