### ISSUE TITLE
The initial label and attribute styles are missing

### ISSUE THREAD

**Issue by bszhct** [ckeditor/ckeditor5#5785]
## Provide a description of the task

I want to keep my html text from changing. For example, the rich text I got from the server is 
```html
<p style="text-indent: 2em;"></p><span id="var_9926108136793732" contenteditable= "false" class="spanVarBtn" ref="common_feeAmount">variables</span>
```

, which is also the case when rendering to the editor, but these properties and styles are now lost.

A very urgent need, I very much hope to get a reply, thank you very much!

*What steps should be taken to fulfill the task?*

## 📃 Other details

* Browser:Chrome
* OS:Mac
* CKEditor version: @ckeditor/ckeditor5-build-decoupled-document@15.0.0
* Installed CKEditor plugins: …

**Comment by Mgsy** [comment]
Hi! CKEditor 5 has own data model and accepts only elements/attributes which are allowed in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html). In your case, you should extend paragraph schema to accept your attributes and create a proper model <--> view [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html). Please, see our guide about [preserving custom content](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html).
