### ISSUE TITLE
big data rerender error

### ISSUE THREAD

**Issue by xinglong717** [ckeditor/ckeditor5#5786]
## 📝 Provide detailed reproduction steps (if any)

1. …when display lots of times with big data,it's happening error
2. …Error Message:"The above error occurred in the <t> component:
    in t (created by CKEditorWrapper)""React will try to recreate this component tree from scratch using the error boundary you provided,"
3. …Error Message:"Uncaught TypeError: Cannot read property 'parentNode' of undefined"

### ✔️ Expected result
![error](https://user-images.githubusercontent.com/32957829/69483849-2520ea80-0e78-11ea-8207-450de551561f.jpg)

*What is the expected result of the above steps?*

### ❌ Actual result

*What is the actual result of the above steps?*

## 📃 Other details

* Browser: …Chrome
* OS: …windows10
* CKEditor version: …CKeditor5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, can you write exact steps to reproduce the issue (including data you're loading to the editor)? Does it occur only in React integration or also in the native CKEditor 5?
