### ISSUE TITLE
Inline editor toolbar does not wrap. (Also, can we add a "show more items" button to it?)

### ISSUE THREAD

**Issue by garyapps** [ckeditor/ckeditor5#5787]
## 📝 Provide detailed reproduction steps (if any)

1. Build a CKEditor instance with Inline editor 
OR
Just go to the Inline Editor documentation page, the bug is present in the editor on that page:
https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html

2. Shrink your browser window so it is narrower than the toolbar

### ✔️ Expected result
The expectation is that the toolbar should wrap when it is wider than the window

### ❌ Actual result
The actual result is that the toolbar does not wrap; it goes off screen.

See the screenshot below:

![ckeditor_toolbar_wrap_bug](https://user-images.githubusercontent.com/39851125/69490021-f2560280-0e35-11ea-99a6-af7132bb6bb5.png)

## 📃 Other details
This problem was not previously present in older versions of CKEditor 5. Or maybe I did not notice it before... I only noticed it after updating to version 15.0 recently.

### Solution to bug

Add the following style to the page 

`<style>
        .ck.ck-toolbar.ck-toolbar_floating>.ck-toolbar__items { 
            flex-wrap: wrap;
        }
    </style>`

(That CSS rule is actually already present, but the flex-wrap is mistakenly set to "nowrap" instead of "wrap".) 

### Related question
Not sure where to post this question, so I'll ask it here - 
**Is it possible to add a "Show more items" button in the inline editor toolbar?**
It appears to be present by default on the classic editor.
You can see it when you use the editor on the classic editor documentation page, if you shrink the browser window until it is narrower than the toolbar: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html 

![ckeditor_toolbar_wrap_bug2](https://user-images.githubusercontent.com/39851125/69489912-6b545a80-0e34-11ea-8756-2af28b85f44e.png)

If it is not possible to add the "show more items" button in the inline editor toolbar, please consider it a feature request.

* Browser: All (Tested on Chrome and Firefox)
* OS: Tested on Windows
* CKEditor version: 15.0
* Installed CKEditor plugins: None

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thank you for the report. Currently, the grouping is enabled in classic and decoupled editors. We consider allowing it in inline and balloon editors, however, there are a few problems which should be discussed. Please, see the following ticket to learn more - https://github.com/ckeditor/ckeditor5/issues/5597.
