### ISSUE TITLE
[Docs] Pasted image is not selectable in the inline editor example

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#579]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/inline-editor.html.
2. Select the image from the second editable.
3. Press <kbd>Ctrl</kbd> + <kbd>C</kbd>.
4. Focus the first editable.
5. Press <kbd>Ctrl</kbd> + <kbd>V</kbd>.
6. Try to select the image.

## Current result
There is no possibility to select the image.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31076089-f7542058-a778-11e7-9558-64062591f0e3.gif)

## Other information
OS: Windows 10, MacOS X
Browser: All browsers
Release: 0.11.0

**Comment by Reinmar** [comment]
It should not be possible to paste the image there. There's something wrong with the configuration.

**Comment by Reinmar** [comment]
I'm pretty sure that the `ImageEngine` plugin is loaded there despite this config:

```js
config.removePlugins = [ 'Blockquote', 'Image', 'ImageToolbar', 'List', 'EasyImage', 'ImageUpload', 'CKFinderUploadAdapter' ];
```
