### ISSUE TITLE
ListEditing Plugin loads dispatchers from unexpected location

### ISSUE THREAD

**Issue by LinkiPinki** [ckeditor/ckeditor5#5792]
Currently, the `ListEditing` Plugin fetches the dispatchers to register its conversion directly from the `EditingController` and `DataController`; Presumably this is a leftover from an older Editor API which came in my way when I tried to implement a custom dispatcher.

I created a Pull request with what I think it should look like [here](https://github.com/ckeditor/ckeditor5-list/pull/162).

**Comment by Mgsy** [comment]
@jodator, can you take a look at it?

**Comment by jodator** [comment]
Hi @LinkiPinki it looks like you're right. I'm going to check you PR that today.
