### ISSUE TITLE
Check collaboration in standard and restricted modes

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5803]
## Provide a description of the task

Check how the restricted editing feature works with collaboration features.

**Comment by Reinmar** [comment]
At this point we are  interested in comments (in both modes) and in track changes (in both modes too).

**Comment by jodator** [comment]
## Integration

### Standard mode

Track changes
  - requires integration with track changes

Comments
  - works

Real-time
  - works

### Restricted mode
Restricted mode
  - track changes commands are disabled - requires configuration/API for enabling commands of track changes modes - currently requires a manual update of `RestrictedEditingModeEditing#_alwaysEnabled` to enable them.
  - navigation commands do not work

Comments
  - comments commands are disabled (the same case for `_alwaysEnabled`)

Real-time
  - works

## Styles preview:

### Standard mode:

![Selection_069](https://user-images.githubusercontent.com/247363/69720156-4997f380-1112-11ea-9ff0-1441c21dd3be.png)

### Restricted mode

comments

![Selection_070](https://user-images.githubusercontent.com/247363/69720077-24a38080-1112-11ea-96dd-ed9f1e8d35af.png)

![Selection_071](https://user-images.githubusercontent.com/247363/69720082-266d4400-1112-11ea-87e7-dbdde2de172a.png)

track changes (requires some positioning fixing AFAICS)

![Peek 2019-11-27 12-16](https://user-images.githubusercontent.com/247363/69719060-02106800-1110-11ea-81e0-5aa11c4521dd.gif)

**Comment by jodator** [comment]
I'm thinking about how the track changes should integrate with restricted editing in terms of always enabling Track Changes and Comments commands in RE mode:

1. Configuration (user would have to manually input 10-ish commands)
2. Track Changes will update `RestrictedEditingModeEditing#_alwaysEnabled` field
3. RE will expose API to change the `_alwaysEnabled` and TC/Com will use that.

cc @scofalik, @Reinmar
