### ISSUE TITLE
toolbar option tooltip gets cut off in case we have larger text for different languages (e.g. russian)

### ISSUE THREAD

**Issue by pankaarya** [ckeditor/ckeditor5#5805]
## 📝 Provide detailed reproduction steps (if any)

![CKEditor5 tooltip text cutoff](https://user-images.githubusercontent.com/47715189/69612999-cfeeff80-1056-11ea-97c6-64a560531c94.PNG)

### ✔️ Expected result
tooltip should accomodate either left or right as per available space, but not cut off

*What is the expected result of the above steps?*

### ❌ Actual result

*What is the actual result of the above steps?*
tooltip text gets cut off

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report, we are aware that our tooltips don't work perfectly. Please, see the following ticket to learn more - https://github.com/ckeditor/ckeditor5/issues/5478.
