### ISSUE TITLE
Can I use(merge) balloon editor in classic editor so that both can work in single editor

### ISSUE THREAD

**Issue by abhijitkc** [ckeditor/ckeditor5#5808]
## I want to use(merge) balloon editor in classic editor so that both can work in single editor. For simplicity I want both toolbar to show in the editor.  

*What steps should be taken to fulfill the task?*

## I want to use(merge) balloon editor in classic editor so that both can work in single editor. For simplicity I want both toolbar to show in the editor.  

* Browser: All
* OS: All
* CKEditor version: 5
* Installed CKEditor plugins: basic plugins

**Comment by Mgsy** [comment]
Hi! The balloon editor uses the [`BalloonToolbar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_toolbar_balloon_balloontoolbar-BalloonToolbar.html) plugin, so it could be applied to any type of the editor. 

Just import the plugin to your build:
```js
import BalloonToolbar from '@ckeditor/ckeditor5-ui/src/toolbar/balloon/balloontoolbar';
```
and [configure it](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-balloonToolbar) in your editor:
```
balloonToolbar: [ 'bold', 'italic', '|', 'undo', 'redo' ]
```

If you're not familiar with installing plugins in CKEditor 5, please see [our guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

**Comment by abhijitkc** [comment]
Thanks @Mgsy . This works for me. But I am getting one issue, the balloon toolbar is showing at the bottom of the editor and not near selected word. Do you have any idea? I have attached the screenshot below.
![ckeditor](https://user-images.githubusercontent.com/36158867/69632145-b361c000-1074-11ea-9b08-31b7ddd41bf9.png)

**Comment by Mgsy** [comment]
Do you have any errors in the console?

**Comment by abhijitkc** [comment]
No. Nothing in the console.

**Comment by Mgsy** [comment]
Can I ask you for your editor configuration code and `package.json`?

**Comment by abhijitkc** [comment]
I am just using the @ckeditor/ckeditor5-editor-classic build. I am pasting the code for editor config and package.json below.

ckeditor.js

`
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import BalloonToolbar from '@ckeditor/ckeditor5-ui/src/toolbar/balloon/balloontoolbar';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
// import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
// import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
// import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
// import Table from '@ckeditor/ckeditor5-table/src/table';
// import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';
import PageBreak from '@ckeditor/ckeditor5-page-break/src/pagebreak';
import Font from '@ckeditor/ckeditor5-font/src/font';
import LineHeight from 'ckeditor5-line-height';

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
	Font,
	LineHeight,
	Bold,
	Italic,
	Underline,
	Strikethrough,
	RemoveFormat,
	Alignment,
	Essentials,
	UploadAdapter,
	Autoformat,
	CKFinder,
	EasyImage,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	PageBreak,
	BalloonToolbar
];

// Editor configuration.
ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'fontFamily',
			'fontSize',
			'lineheight',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'removeFormat',
			'alignment',
			'numberedList',
			'bulletedList',
			'indent',
			'outdent',
			'undo',
			'redo',
			'fontColor',
			'fontBackgroundColor',
			'imageUpload',
			'pageBreak',
		]
	},
	balloonToolbar: {
		items: [
			'bold',
			'italic',
			'|',
			'undo',
			'redo',
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	fontSize: {
		options: [
			10,
			11,
			12,
			13,
			14,
			15,
			16,
			17,
			18,
			20,
			22,
			24
		]
	},
	fontFamily: {
		options: [
			'Arial',
			'sans-serif',
			'Comic Sans MS',
			'Courier New',
			'Georgia',
			'Lucida Sans Unicode',
			'Tahoma',
			'Geneva',
			'Times New Roman',
			'Trebuchet MS',
			'Verdana',
			'Muli'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};
`
package.json

`{
  "name": "",
  "version": "15.0.0",
  "description": "",
  "keywords": [
    "ckeditor5-build",
    "ckeditor",
    "ckeditor5",
    "ckeditor 5",
    "wysiwyg",
    "rich text",
    "editor",
    "html",
    "contentEditable",
    "editing",
    "operational transformation",
    "ot",
    "collaboration",
    "collaborative",
    "real-time",
    "framework"
  ],
  "main": "./build/ckeditor.js",
  "files": [
    "build"
  ],
  "devDependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^15.0.0",
    "@ckeditor/ckeditor5-alignment": "^15.0.0",
    "@ckeditor/ckeditor5-autoformat": "^15.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^15.0.0",
    "@ckeditor/ckeditor5-block-quote": "^15.0.0",
    "@ckeditor/ckeditor5-ckfinder": "^15.0.0",
    "@ckeditor/ckeditor5-core": "^15.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.0",
    "@ckeditor/ckeditor5-easy-image": "^15.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^15.0.0",
    "@ckeditor/ckeditor5-essentials": "^15.0.0",
    "@ckeditor/ckeditor5-heading": "^15.0.0",
    "@ckeditor/ckeditor5-image": "^15.0.0",
    "@ckeditor/ckeditor5-indent": "^15.0.0",
    "@ckeditor/ckeditor5-link": "^15.0.0",
    "@ckeditor/ckeditor5-list": "^15.0.0",
    "@ckeditor/ckeditor5-media-embed": "^15.0.0",
    "@ckeditor/ckeditor5-paragraph": "^15.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^15.0.0",
    "@ckeditor/ckeditor5-table": "^15.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^15.0.0",
    "eslint": "^5.5.0",
    "eslint-config-ckeditor5": "^2.0.0",
    "husky": "^1.3.1",
    "lint-staged": "^7.0.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^3.1.0",
    "style-loader": "^1.0.0",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "webpack": "^4.39.1",
    "webpack-cli": "^3.3.6"
  },
  "engines": {
    "node": ">=8.0.0",
    "npm": ">=5.7.1"
  },
  "author": "CKSource (http://cksource.com/)",
  "license": "GPL-2.0-or-later",
  "homepage": "https://ckeditor.com/ckeditor-5",
  "bugs": "https://github.com/ckeditor/ckeditor5/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/ckeditor/ckeditor5-build-classic.git"
  },
  "scripts": {
    "build": "webpack --mode production",
    "lint": "eslint --quiet '**/*.js'",
    "preversion": "npm run build; if [ -n \"$(git status src/ckeditor.js build/ --porcelain)\" ]; then git add -u src/ckeditor.js build/ && git commit -m 'Internal: Build.'; fi"
  },
  "lint-staged": {
    "**/*.js": [
      "eslint --quiet"
    ]
  },
  "eslintIgnore": [
    "build/**",
    "packages/**"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@ckeditor/ckeditor5-font": "^15.0.0",
    "@ckeditor/ckeditor5-page-break": "^15.0.0",
    "@ckeditor/ckeditor5-remove-format": "^15.0.0",
    "@ckeditor/ckeditor5-ui": "^15.0.0",
    "@ckeditor/ckeditor5-word-count": "^15.0.0",
    "ckeditor5-line-height": "^0.3.1"
  }
}
`
Also to create editor I am using 

`ClassicEditor.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );`

**Comment by Mgsy** [comment]
I see that you use `ckeditor5-line-height` which is a third-party plugin. Can you check if the problem occurs after disabling this plugin? It's possible that it uses some old dependencies what causes conflicts with the editor.

**Comment by abhijitkc** [comment]
After disabling 'ckeditor5-line-height' plugin the problem resolved. Thanks again @Mgsy . But do you know any solution to use line height functionality in ckeditor 5?

**Comment by Mgsy** [comment]
There's no official line-height plugin, however we have a feature request for it - https://github.com/ckeditor/ckeditor5/issues/1429. Feel free to add 👍 to the first post to bump its popularity. 

Anyway, you can create this feature on your own. The following guides might be useful:
- [Creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)
- [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html)
- [Conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html) and [Conversion API](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html)
