### ISSUE TITLE
Remove R+ and R- labels

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5811]
They duplicate the PR statuses and pipelines.

**Comment by Reinmar** [comment]
They need to be removed from all repos, so I assigned it to you @mlewand since you did that recently.

**Comment by mlewand** [comment]
![Aaaand it's gone image](https://s3.amazonaws.com/blogs.comedycentral.com-production/wp-content/uploads/sites/58/2014/04/1303-and-itsgone.jpg)
