### ISSUE TITLE
Review building an editor guide after upgrading to Webpack 5

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#5815]
## 📝 Provide a description of requested docs changes

Terser is a default minified in Webpack 5. In our docs, we mentioned about optimizing the bundle using something similar to `uglify-js`.

After switching to Webpack 5, we can clean up our guides and recommend using Terser which is available by default.

**Comment by ma2ciek** [comment]
Actually, a small note should be there for some time, as many users will still be using the old webpack@4.

**Comment by mlewand** [comment]
@pomek I'll assign this issue to you for the time being, so that we won't forget it once stable Webpack 5 is out.

**Comment by Reinmar** [comment]
The RC is out.

**Comment by Reinmar** [comment]
TODO:

*   Update webpack 4 to webpack 5 everywhere in our project (package.jsons, documentation where we mention `webpack@4`, etc.)
*   Check whether everything works. Docs build. Manual and automated tests run. Translations work.
*   Wait until official release to merge that PR (with the 4->5 update).

**Comment by pomek** [comment]
[> Webpack 5: release planned for 2020-10-10.](https://github.com/webpack/webpack/issues/11406)

**Comment by pomek** [comment]
I updated our scripts and guides. Automated and manual tests, building builds, snippets, and docs were working. I wanted to go through our guides in order to check whether the guides are correct. 

Unfortunately, some of them don't work. Webpack throws an error:

```
(node:17801) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17801) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:17801) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
[webpack-cli] HookWebpackError: item.node is not a function
    at makeWebpackError (/Users/pomek/Projects/tmp/advanced-setup/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /Users/pomek/Projects/tmp/advanced-setup/node_modules/webpack/lib/Compilation.js:1987:11
    at eval (eval at create (/Users/pomek/Projects/tmp/advanced-setup/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:49:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: item.node is not a function
    at /Users/pomek/Projects/tmp/advanced-setup/node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (/Users/pomek/Projects/tmp/advanced-setup/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (/Users/pomek/Projects/tmp/advanced-setup/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
    at /Users/pomek/Projects/tmp/advanced-setup/node_modules/terser-webpack-plugin/dist/index.js:226:27
    at /Users/pomek/Projects/tmp/advanced-setup/node_modules/p-try/index.js:4:10
    at new Promise (<anonymous>)
    at pTry (/Users/pomek/Projects/tmp/advanced-setup/node_modules/p-try/index.js:3:37)
    at run (/Users/pomek/Projects/tmp/advanced-setup/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:24:18)
    at /Users/pomek/Projects/tmp/advanced-setup/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:46:18
```

I don't know why. I didn't find anything helpful in webpack docs or repository. Maybe it is related to the hot releases period. I would wait for the official release and then, check the code once again.

**Comment by pomek** [comment]
The error occurred because I didn't link our webpack plugin that was also modified… (facepalm)

**Comment by pomek** [comment]
As I wrote here – https://github.com/ckeditor/ckeditor5/pull/8213#issuecomment-704768606 – we're waiting for the official release now.

**Comment by pomek** [comment]
Webpack 5 is out – https://webpack.js.org/blog/2020-10-10-webpack-5-release/.

**Comment by Reinmar** [comment]
I extracted the spike to #8342 and consider it done already. What's left now is cleaning up what you came up with and possibly merge with the other changes that I've been working on.

**Comment by niemyjski** [comment]
We need this as well

**Comment by kceron** [comment]
Does anyone know how to fix this warning?

**Comment by pomek** [comment]
I will close this ticket. I am trying to understand why it's still open. CKEditor 5 can be built using both webpack versions. Webpack 5 in the project has been used for three years, and I do not recall any issues.
