### ISSUE TITLE
Enable stylelint in code-block and restricted-editing packages

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5816]
## Provide a description of the task

A follow-up of https://github.com/ckeditor/ckeditor5/issues/5696.

**Comment by mlewand** [comment]
I have checked stylelint against current master and it passes fine 👍

**Comment by oleq** [comment]
We need to enable stylelint in all packages (like ESLint) to have linter working when e.g. developing branches. Stylelint in ckeditor5 also covers all packages but that would only work for master-revisions and stable (master) code from code-block and restricted-editing.

**Comment by mlewand** [comment]
Reopening as running:

```
user@domain /ckeditor5/ckeditor5 (master)
$ stylelint --quiet --allow-empty-input 'packages/**/*.css' 'docs/**/*.css'
```

might not test against all subpacakages.
