### ISSUE TITLE
Enable cycling across restricted editing regions

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5819]
## 📝 Provide a description of the new feature

ATM you can use Tab/Shift+Tab to move between the regions. But, for instance, when you are in the last one, your selection will not be moved to the first one on Tab (and I think it should).

This could improve the UX and allow faster form–like filling of the content.

cc @dkonopka @jodator 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by dkonopka** [comment]
☝️ It's sounds good in terms of editor UX, but this means it won't be possible to "exit" editor through clicking `Tab` key?

**Comment by oleq** [comment]
Kinda the same problem we have with lists and now code blocks.
