### ISSUE TITLE
The floating toolbar design

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#582]
I was checking the ballon panel in a demo page:

![image](https://user-images.githubusercontent.com/630060/31121814-fafd58f2-a839-11e7-8bef-3110b9ce42dd.png)

Unfortunately, the lack of contrast of it, and also its design, probably, make it merge into the content, making it hard to see and use it. When playing of selecting text randomly, I was even confused on finding where the toolbar is, sometimes

I have the impression that the current design has been created on top of the classic editor and it works better there. But it seems to not be a good "universal" solution.

What do you think?

**Comment by wwalc** [comment]
Note: the background of the page may be different. Whatever color we choose it will not fit all scenarios. I'd review the whole UI TBH.

**Comment by Reinmar** [comment]
Hm... when you wrote this I realised that I had this feeling too, just not clear enough.

Would stronger shadow help?

**Comment by oleq** [comment]
Maybe some shadow and maybe simply inverted colors. It's unlikely the editor will be integrated into a web page with a black bg and white text. It would work in like 90% of cases.

**Comment by fredck** [comment]
It's almost like I've seen something like this out there already :D

![image](https://user-images.githubusercontent.com/630060/31123033-90897d8e-a83e-11e7-9cbc-940e414fd651.png)

**Comment by oleq** [comment]
LGTM in CKEditor too

![image](https://user-images.githubusercontent.com/1099479/31123143-f6c608ec-a83e-11e7-9117-e95ddce52c1e.png)

**Comment by Reinmar** [comment]
You went with a bit too dark colors, but it sounds like a good option. Although, I wonder how many people will prefer the bright version cause, aesthetically speaking, I like it more.

Also, I think we should wait for some feedback cause, after having second thoughts, I think that we may be overthinking this.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/issues/645.
