### ISSUE TITLE
Add image editor to CKEditor 5

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#5825]
I'm opening this ticket to see if there is a demand for an image editing feature that is closely integrated with CKEditor 5 (e.g. can be opened using a contextual toolbar when the image is focused).

![Screen Shot 2019-11-26 at 3 39 23 PM](https://user-images.githubusercontent.com/545175/69643020-f3b84280-1062-11ea-87db-b6ac254ddbbd.png)

Some selected image manipulation features that the built-in image editor could support:

 - crop,  
 - rotation, flip 

and maybe even more:

 - image filters (e.g. grayscale, brightness, invert, sepia, blur, sharpen, emboss, noise)
 - adding text
 - drawing (free drawing, line drawing), shapes

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
CKBox comes with image editing now: [https://ckeditor.com/blog/ckbox-1-6-0/](https://ckeditor.com/blog/ckbox-1-6-0/)

And there's integration with CKEditor: https://ckeditor.com/file-management/

**Comment by Witoso** [comment]
Image editing inside the editor was introduced via the integration with [CKBox](https://ckeditor.com/ckbox/) in version `v40.2` 🎉  🎉  🎉 

https://github.com/ckeditor/ckeditor5/assets/9881379/aec8b88f-0da7-4661-b85b-e10d7d1d891a
