### ISSUE TITLE
The CKFinder docs miss correct links in the lib installation

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#5830]
## 📝 Provide a description of requested docs changes

I tried to integrate the CKFinder like in the https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html#full-integration and I almost failed. I was stacked exactly at this point: https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html#configuring-the-full-integration - and the magic URL to the CKFinder - "https://example.com/ckfinder/ckfinder.js" (:trollface:).

I tried to get the correct one and I had to browse the internet. 

After some browsing, I came to the https://ckeditor.com/ckfinder/download page. However, nor of these packages seems to provide the "https://example.com/ckfinder/ckfinder.js". There were some `ckfinder.js` files in the provided framework integration zips, though I didn't know if they were env specific or not, maybe these files would work too.

Finally, in one of the CKEditor 5 docs snippet, I've found the magic line - 

```html
<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>
```

And was able to see the same as in the demo.

These things shouldn't be hidden as it makes integrating this library very hard for people not familiar with the project.

**Comment by mlewand** [comment]
Fixed in ckeditor/ckeditor5-ckfinder#54.
