### ISSUE TITLE
Side image makes the table go above it

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#5833]
## 📝 Provide detailed reproduction steps (if any)

1. Open an editor with image and table features, for example: https://ckeditor.com/collaboration/real-time-collaborative-editing/demo/?active-demo=collaboration
2. Create a table and insert an image before it.
3. Change image style to side image.

### ❌ Actual result

![image](https://user-images.githubusercontent.com/1502228/69662515-cb414000-1084-11ea-98ad-4948647bf021.png)

As you can see that's quite a glitch. Something is probably incompatible with CSSes.

**Comment by Reinmar** [comment]
> Something is probably incompatible with CSSes.

It's CSS.

**Comment by Mgsy** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/2049?
