### ISSUE TITLE
The hue of the focus outline's stronger color could be improved

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5837]
![image](https://user-images.githubusercontent.com/156149/69679001-58958c00-10a7-11ea-8440-523784947c6c.png)

To me this blue border looks a bit out of place. Maybe it's the hue or maybe it should be less saturated. IDK.

cc @dkonopka @oleq

**Comment by oleq** [comment]
LGTM (but I created it). Maybe let's have more feedback from other developers (P.S. don't forget that hue also contributes to a11y and contrast).

**Comment by mlewand** [comment]
Personally I also find it nice looking.
