### ISSUE TITLE
Can't insert at the begin or the end of inline element on Safari and Chrome

### ISSUE THREAD

**Issue by minhtranite** [ckeditor/ckeditor5#5839]
## 📝 Provide detailed reproduction steps (if any)

1. Setup CKEditor with root element is a inline element
2. Try insert at the begin or the end.

![Screen Shot 2019-11-27 at 09 47 53](https://user-images.githubusercontent.com/5418628/69689463-9e7c3f80-10fb-11ea-9d25-58d21cd83ba7.png)

### ✔️ Expected result
It insert new charactors

### ❌ Actual result

It not insert and sometime it remove all content.

### Workaround
Add style `display: block` to root element and it work.

## 📃 Other details

* Browser: Safari
* OS: osx
* CKEditor version: 14.x
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by minhtranite** [comment]
I setup a simple codesandbox to reproduce this issue here: https://codesandbox.io/s/react-ckeditor-64l5x

And here is error log on Sentry:

![Screen Shot 2019-11-27 at 12 00 17](https://user-images.githubusercontent.com/5418628/69695062-8ad9d480-110d-11ea-9a08-0f6f414263ee.png)

**Comment by mlewand** [comment]
@minhtranite the thing is that we didn't implement creating editors on inline elements at all so far, so it only "somehow" works coincidentally :slightly\_smiling\_face: So this is a matter of adding a feature like to the editor.

I added a feature request for this #6070 so I'll close this as a duplicate. Feel free to subscribe mentioned feature issue and add a 👍 reaction to it.
