### ISSUE TITLE
Restricted editing boundary can be crossed with a command which operates on more than the current selection

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5840]
There are two commands that come to my mind:

* unlinking
* delete word

Content that will break:

![image](https://user-images.githubusercontent.com/156149/69702484-9e764280-10ef-11ea-8d52-3473a58b91fd.png)

**Comment by jodator** [comment]
Reported by @oleq:

1. Go to restricted mode
2. Put the caret at the beginning of an editable (exception) area
3. Click “Link”
4. The link is inserted before the exception (the exception should be included)

 type some link and save.

**Comment by jodator** [comment]
Another case (Firefox, native spell check):

![Peek 2019-11-28 08-51](https://user-images.githubusercontent.com/247363/69787247-5ec95c80-11bc-11ea-8f16-606ba3cc10b8.gif)

The native spell check did not fix "computter" when the action was performed on the part outside the exception. When performed on part in exception we get word changed outside the marker.

Words on Chrome are treted separately if divided by `<span>` (marker).

**Comment by jodator** [comment]
And also Safari does weird things with fixed words:

1. put selection at the end of an exception marker
2. write " cooool"
3. press space
4. the word get fixed to cool but "l" is out of the exception marker
