### ISSUE TITLE
Is it a problem that ckeditor5 is no longer a dependency of ckeditor5-utils?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5842]
We introduced it as a dep of ckeditor5-utils so we could implement version.js.

But with https://github.com/ckeditor/ckeditor5/issues/5660, we had to drop this idea. We hardcoded the version and update it before a release. This means that ckeditor5 is no longer a dep of ckeditor5-utils.

Is it a problem? Does it change something? Let's think about it for a while.

**Comment by Reinmar** [comment]
cc @pomek @ma2ciek

**Comment by pomek** [comment]
Sorry for the late response.

I don't think it changes anything.

**Comment by Reinmar** [comment]
I didn't see any problems either so let's just close this. Thanks.
