### ISSUE TITLE
Update the release steps scripts

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5845]
## Provide a description of the task

I've checked when the CKEditor 5 version is bumped. The version update script should be run after `release:bump-version` if I get the flow correctly since the version is take from `package.json`.

As for now, one has to call `postchangelog` task manually after the version is bumped.

I think that the flow should be updated but I don't have a clear view how.

**Comment by pomek** [comment]
The script cannot be executed after `release:bump-version` triggers `npm run build` in `ckeditor5-build-*` repositories. But you're right. The version should be taken from `CHANGELOG.md` instead of `package.json`.

I guess, https://github.com/ckeditor/ckeditor5/pull/5847 fixes the issue.

**Comment by jodator** [comment]
Yes, I've forgot to close this. Closed by:  #5847.
