### ISSUE TITLE
Fix CC in 3 packages

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5848]
Code coverage dropped there: https://coveralls.io/builds/27275642/source?filename=packages%2Fckeditor5-utils%2Fsrc%2Fversion.js

## Packages

- [x] utils
- [x] watchdog
- [ ] upload

**Comment by pomek** [comment]
CC is below 100% also in other packages:
- https://github.com/ckeditor/ckeditor5-upload
- https://github.com/ckeditor/ckeditor5-watchdog

**Comment by Reinmar** [comment]
Thanks, I updated the title to cover all 3 places.

**Comment by oleq** [comment]
2 branches + 1 follow-up and it's ready for review.

**Comment by mlewand** [comment]
@oleq since we won't be tackling #5875 soon, can you add a PR with instanbul ignore directive for the `upload` package?

**Comment by oleq** [comment]
Are you sure this is the right thing to do? This is a real case where we don't have coverage because we don't understand how the code works. This is a good reminder that we need to address this issue.

**Comment by mlewand** [comment]
I hear you, that being said I don't think we have the time to investigate it properly now. So marking it with an ignore and giving a reference to #5875 sounds like a sane idea. I'm not sure whether #5875 is severe enough to put it in the next iteration or should it stay in our todo list. @Reinmar what's your take on this?

**Comment by oleq** [comment]
I created a follow-up in #5892 so we can close this issue and get back to the problem later on.
