### ISSUE TITLE
Full size image button do not resize image

### ISSUE THREAD

**Issue by projct1** [ckeditor/ckeditor5#5849]
## 📝 Provide detailed reproduction steps (if any)

1. [Go here](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#resizing-images)
2. Try to resize second (small) image
3. Click "Full size image" button

### ✔️ Expected result

The image will resize on 100%.

### ❌ Actual result

Nothing to happen.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Actually, we have this case reported [here](https://github.com/ckeditor/ckeditor5/issues/5203), so I'm closing it as a duplicate.
