### ISSUE TITLE
There's browser outlilne instead of CKEditor one in Using a React component in a block widget

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5851]
## 📝 Provide a description of requested docs changes

Go to "Using a React component in a block widget" guide and see the outline:

(todo: image from safari)

on FF:

![Selection_072](https://user-images.githubusercontent.com/247363/69734602-89210880-112f-11ea-85e9-534af6f64a9e.png)

Other samples do not have this outline. Might be related to: #5850

**Comment by oleq** [comment]
I couldn't reproduce it. Something OS-specific?

**Comment by mlewand** [comment]
I also couldn't repro this issue on Chrome/FF. So it indeed was most likely due to #5850.
