### ISSUE TITLE
Request: How do I use wordcount plugin in non-npm environment = CDN

### ISSUE THREAD

**Issue by vinicius1209** [ckeditor/ckeditor5#5852]
Hi all!
I'm using Ckeditor 5 with CDN import method. And i now i'm trying to implement a word, caracter and lines counter for my editor. But, how can i do that withou using node??

Best regards

**Comment by Mgsy** [comment]
Hello! It's not possible to add plugins to the existing build. It means that, unfortunately, you have to create a custom build with a plugin of your choice. We're aware that it's not the best solution, we'll be working on it, but improving the current solution won't be easy. 

Please, see the ticket about allowing adding plugins to the build - https://github.com/ckeditor/ckeditor5/issues/667.
