### ISSUE TITLE
CI fails due to collaboration links in React / Angular guide

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5853]
## 📝 Provide detailed reproduction steps (if any)

See the recent CI builds for the `master` branch: https://travis-ci.org/ckeditor/ckeditor5/jobs/617865377

### ✔️ Expected result

Build should pass with no errors.

### ❌ Actual result

Following errors are reported:

```
Error: Failed while convert {@link features/collaboration collaboration plugins} tag in ckeditor5/15.0.0/builds/guides/frameworks/angular.md.
Error: Failed while convert {@link features/collaboration collaboration plugins} tag in ckeditor5/15.0.0/builds/guides/frameworks/react.md.
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I guess we already have some links to the collab features somewhere, so it's just a matter of finding them and figuring out how they are written.

**Comment by ma2ciek** [comment]
Links were correct, but not in the CKEditor 5 repository as they required the `ckeditor5-extra/collaborative-features/` extension. I changed them to simple markdown links.
