### ISSUE TITLE
[Docs] Code auto formatting not working in the guide 

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#586]
Code auto format does not work in in the https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/autoformat.html because the editor has no `Code` plugin loaded. 

Maybe https://github.com/ckeditor/ckeditor5-build-classic should provide it by default? 

cc @Reinmar

**Comment by Reinmar** [comment]
This is dup. It was reported already.

The build should not contain this plugin. But it should be enabled in the autoformat example. I just didn't manage to do so.

**Comment by Reinmar** [comment]
It was reported as a comment here: https://github.com/ckeditor/ckeditor5/issues/573#issuecomment-333472946.

So let's keep this ticket.

**Comment by Reinmar** [comment]
Haha... It turns out that the Code feature doesn't work at all in this sample. 

![image](https://user-images.githubusercontent.com/156149/31203781-dfd21ab0-a968-11e7-905c-ecf3f8e16ecd.png)

I wonder if that's because of the styling.

**Comment by Reinmar** [comment]
OK, nvmnd. I'm stupid.
