### ISSUE TITLE
Disable text transformations inside code blocks

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#5862]
## 📝 Provide detailed reproduction steps (if any)

1. Open code block manual test and replace `ClassicEditor.create()` with:
```js
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ Code, CodeBlock, Autoformat, Indent, ArticlePluginSet, TextTransformation ],
```
2. `yarn run manual -f code-block`
3. In code block, type `1/2`

### ✔️ Expected result

`1/2` should stay as `1/2`.

### ❌ Actual result

`1/2` is replaced with `½`

## 📃 Other details

* Browser: FF
* OS: Mojave 10.14.6 
* CKEditor version: master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
TODO: Does it apply to inline code too?

TODO: How was it fixed in inline code + autoformat case?

**Comment by Reinmar** [comment]
TODO: Does it apply to inline code too?

TODO: How was it fixed in inline code + autoformat case?

**Comment by Reinmar** [comment]
I've checked the TextTransformation's code and I think that we need to be able to either disable some sort of command (which doesn't exist at the moment) or the whole plugin (which isn't "disableable" yet). 

I'd go with the command, if it's possible to introduce here a reasonable command. By "reasonable" I mean a command which API will make sense.

If that's impossible, we should allow disabling the whole plugin. And this can be made the same way as in [https://github.com/ckeditor/ckeditor5-widget/pull/113](https://github.com/ckeditor/ckeditor5-widget/pull/113) – by introducing `isEnabled` to the plugin itself. But then we'll have 3 repetitions of the same code, so the first step would be to extract that to a mixin that we'd mix into the `Command`, `WidgetToolbarRepository` and `TextTransformations` plugins.

**Comment by oleq** [comment]
I'm against a command in this case. 

ATM the plugin's `init()` [registers a watcher](https://github.com/ckeditor/ckeditor5-typing/blob/139989cbc128a1cea123e92838c36eb71c0ecd8c/src/texttransformation.js#L111) that interacts with the model. The command would need to enable this watcher when executed (?) and disable it when... yeah, that's a good question.

Besides, execution of any command is, in terms of a state machine, a transition between state A and state B. This text transformation command (that brings a watcher) would impact all editor states form some point until it gets disabled. IMO it violates the "paradigm of commands" as we know it.

I'm for another solution with disabling the plugin. It can have methods `TextTransformation#enable` and `TextTransformation#disable` or an observable property `TextTransformation#isEnabled`.

**Comment by Reinmar** [comment]
I'm fine with no command. As I said – I'd only go this way if we'd consider it clean.

We recently introduced plugin disabling in one of the plugins: [https://github.com/ckeditor/ckeditor5-widget/pull/113](https://github.com/ckeditor/ckeditor5-widget/pull/113). It's a copy-paste from the command API because we didn't know how soon we'll need this in another plugin. I think I'm fine with moving this to core now so the API is available for all plugins.

**Comment by panr** [comment]
OK, I'll do it that way.

**Comment by panr** [comment]
I raised few PRs for the text transformation typing issue, but there will be another ticket for handling  conversion to code block from for example paragraph with transformed text inside, like:

```
CKEditor © 2020
```

`©` should transform to `(c)`, right?

**Comment by aspirin01** [comment]
After a lot of struggle and search,
this is the only solution I came up with
`
  config={{
                  typing: {
                    transformations: {
                      remove: ['symbols', 'quotes', 'arrowLeft', 'arrowRight','mathematical','typography'],
                      
                    },
                  },}
}
`
Add this to your config in ckeditor component
