### ISSUE TITLE
Typing selects entire content in restricted mode on Edge

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5863]
## 📝 Provide detailed reproduction steps (if any)

1. Open restricted editing feature guide.
2. Switch to restricted mode.
3. Click in the first editable region, e.g. `it is ed^itable`.
1. Press `ctrl+a`.
1. Put the (collapsed) selection back to the same position in editable.
1. Start typing.

### ✔️ Expected result

Typed letters get inserted into the selected position.

### ❌ Actual result

Entire content gets selected.

## 📃 Other details

* Browser: Edge 44.18362.449.0 (18.18362)
* OS: Win10
* CKEditor version: latest `master` branch

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
I've just checked it on new Edge in beta version (79.0.309.56) and the bug is gone ( still exists on old Edge though ).

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
