### ISSUE TITLE
Ctrl+backspace/delete deletes restricted content in very specific cases

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5864]
## 📝 Provide detailed reproduction steps (if any)

1. Open restricted editing feature guide.
1. Make sure youre using "standard" mode.
1. Edit first paragraph in a way that there's a text before the first editable area (**but there's no space**).
2. Switch to restricted mode.
3. Make following selection in the first editable region: `it^ is editable`.
1. Press `ctrl+backspace`.

### ✔️ Expected result

Only characters in the editable area should be removed.

### ❌ Actual result

Characters from outside editable area are also removed. There's a respective case for the `ctrl+delete` key.

![1896522b-c455-4728-b798-ee3443ff5164](https://user-images.githubusercontent.com/5353898/69807212-0490c180-11e5-11ea-804b-bfb629f94a73.gif)

## 📃 Other details

* Browser: Chrome, FF, Edge
* OS: Win10
* CKEditor version: latest `master` branch

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Dup of: https://github.com/ckeditor/ckeditor5/issues/5840
