### ISSUE TITLE
Pressing enter in the todolist created from code block crashes the editor

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#5866]
## 📝 Provide detailed reproduction steps (if any)

1. Create a code block that contains a few lines
1. Change it to todo-list 
1. Press enter after the first line

### ✔️ Expected result

No crash

### ❌ Actual result

Crash

## 📃 Other details

* Browser: All 
* OS: macOS
* CKEditor version: latest 15.0.0 (before the release)
* Installed CKEditor plugins: CodeBlock, TodoList

![todolist](https://user-images.githubusercontent.com/2768047/69808088-1b381800-11e7-11ea-8a45-e14616cb2d30.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It's not a DUP of https://github.com/ckeditor/ckeditor5/issues/5779 per se, but it's the same problem – converters are not expecting any inline elements or any other markup.

**Comment by Reinmar** [comment]
In this case, it crashes because you have `<br>`s in that newly created list item.

**Comment by Reinmar** [comment]
Another case: #6585.
