### ISSUE TITLE
Extra spacing in empty code block on Edge

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5867]
## 📝 Provide detailed reproduction steps (if any)

Two cases:

1. Open code snippet guide.
1. Insert an empty code block.

Case 2:

1. Open code snippet guide.
1. Put the cursor at the end of code snippet.
1. Press enter.

### ✔️ Expected result

Code block has more-or-less even padding. Empty line does not cause an extra padding at the end.

### ❌ Actual result

A single line is inserted, but there's a weird spacing at the bottom which disappears as soon as you type first character.

Case 1:
![image](https://user-images.githubusercontent.com/5353898/69808266-6d793900-11e7-11ea-9681-d3a44ec3d3c9.png)

Case 2:
![image](https://user-images.githubusercontent.com/5353898/69808098-1e330880-11e7-11ea-8e27-cb3266bb8b9e.png)

## 📃 Other details

* Browser: Edge
* OS: Win10
* CKEditor version: latest `master` branch

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
This bug still exists on old Edge, however it is fixed in the new upcoming version (79.0.309.56)

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
