### ISSUE TITLE
Page break sample print preview doesn't work

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5868]
## 📝 Provide a description of requested docs changes

Page break sample print preview doesn't work on Edge.

1. https://ckeditor.com/docs/ckeditor5/latest/features/page-break.html
1. Scroll to the "Open print preview" button.
1. Click it.

### ✔️ Expected result

Print preview should be opened.

### ❌ Actual result

Nothing happens.

**Comment by godai78** [comment]
It opens now, by the way. Newest chrome on a mac.

**Comment by godai78** [comment]
It does work with the newest Edge (I simply downloaded the current version and installed it) on a mac. 

![Screenshot 2020-11-20 at 13.54.15.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/36eb8d8c-c48f-4cb6-bb2b-2568852c6df8)

**Comment by SergiiMarkin** [comment]
The print preview is feature from Page break plugin or can I implement print preview without installing this page break plugin?

**Comment by Mgsy** [comment]
> The print preview is feature from Page break plugin or can I implement print preview without installing this page break plugin?

Hi @SergiiMarkin, the preview on our documentation page is not a part of the page break plugin - it has been implemented with the native API. 

As this issue doesn't occur in the new Edge, I'll close the ticket.
