### ISSUE TITLE
Content styles are outdated

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#5873]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#the-full-list-of-content-styles

```
CKEditor 5 (v12.4.0) content styles.
 * Generated on Mon, 21 Oct 2019 11:34:56 GMT.
```

CKEditor 5 is in version 15.0.0 at this moment.

**Comment by mlewand** [comment]
The file was heavily outdated, but we did update it during preps for the testing phase https://github.com/ckeditor/ckeditor5/blame/114588bc18b132b7413a7c8c04386e9cab7a83c1/docs/builds/guides/integration/content-styles.md#L51-L52.
