### ISSUE TITLE
Figure out what to do with ckeditor5.github.io

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#588]
Right now we're linking to this page from all over GH. And when I tried to find a good place to link to in the new websites, I couldn't. I think that perhaps CKEditor 5 needs its development center anyway. A place where the last releases can be listed and links to important (for developers) places in our documentation.

However, it definitely needs to be rethought.

**Comment by Reinmar** [comment]
E.g. another thing for which we could use this website is keeping nightly stuff:

* nightly builds of the editor,
* nightly builds of the docs,
* nightly whatever.

**Comment by wojtekidd** [comment]
Everything is under control and we'll get back to it when CKE5 stable is out 😽

**Comment by Reinmar** [comment]
We're slowly killing it by changing links so they point to https://ckeditor.com and https://docs.ckeditor.com. ckeditor5.gh.io may be turned into a developer's center in the future, but right now the readme in ckeditor5's repo takes over this role.
