### ISSUE TITLE
Adding column next to down+left merged cell works incorrectly

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#5882]
## 📝 Provide detailed reproduction steps (if any)

1. Create a cell that is merged down and merged left (see GIF).
2. Insert column directly on the left of that cell.

![Dec-02-2019 15-25-18](https://user-images.githubusercontent.com/1502228/69967272-581e4a80-1518-11ea-8908-49f48015bdf2.gif)

### ❌ Actual result

The table layout goes crazy.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Merged #6376 into this issue.

**Comment by Reinmar** [comment]
Let's give this max 1 day and see if we can fix it.
