### ISSUE TITLE
decoupled-document build doesn't work properly on React CKEditor component

### ISSUE THREAD

**Issue by goratt12** [ckeditor/ckeditor5#5884]
When setting the the `editor` prop on the CKEditor component to DecoupledEditor, the toolbar does show at all.
I installed the DecoupledEditor using the command `npm install --save @ckeditor/ckeditor5-build-decoupled-document`

the `data` prop works just fine, but the toolbar of the DecoupledEditor doesn't show (screenshot attached)

my code:

`import CKEditor from '@ckeditor/ckeditor5-react';`
`import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';`
.
.
.
 `    <CKEditor`
 `        editor={ DecoupledEditor }`
 `        data="<p>Hello from CKEditor 5!</p>"`
`     />`
![Untitled](https://user-images.githubusercontent.com/23094928/69984176-371e1f80-1541-11ea-9fc7-0cd7966f3849.png)

**Comment by Mgsy** [comment]
Hi! Did you spawn the toolbar to the container? In the decoupled editor you should take care of it on your own because the editable and the toolbar are separated. Please, see the [documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#example-decoupled-editor).

**Comment by goratt12** [comment]
Thank you for the quick response.
But how do I do that on the React component?

‫בתאריך יום ג׳, 3 בדצמ׳ 2019 ב-11:45 מאת ‪Kacper Tomporowski‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Mgsy** [comment]
>But how do I do that on the React component?

Just add the container for the toolbar in your component and put the toolbar inside. See the example below:

```js
<div id="toolbar-container"></div>
<CKEditor
      editor={ DecoupledEditor }
      config={ editorConfiguration }
      data="<p>Content</p>"
      onInit={ editor => {
            // Add the toolbar to the container
	    const toolbarContainer = document.querySelector( '#toolbar-container' );
            toolbarContainer.appendChild( editor.ui.view.toolbar.element );

	    window.editor = editor;
            // You can store the "editor" and use when it is needed.
            console.log( 'Editor is ready to use!', editor );
       } }
      onChange={ ( event, editor ) => {
             const data = editor.getData();
             console.log( { event, editor, data } );
      } }
      onBlur={ ( event, editor ) => {
             console.log( 'Blur.', editor );
      } }
      onFocus={ ( event, editor ) => {
             console.log( 'Focus.', editor );
      } }
/>
```

**Comment by Munsterberg** [comment]
For anyone reading this in the future, you should use a ref instead of manipulating the DOM directly like in the example above.

**Comment by WilixLead** [comment]
This is example with ref (working to me)
```tsx
export default function Editor({ value, onChange, ...rest }: EditorProps) {
  const toolBarRef = createRef<HTMLDivElement>();
  return <div>
    <div ref={toolBarRef} />
    <CKEditor
    {...rest}
    editor={DecoupledEditor}
    data={value}
    onReady={editor => {
      if (toolBarRef.current) {
        toolBarRef.current.appendChild(editor.ui.view.toolbar.element);
      }
    }}
    onChange={(event:any, editor:any) => {
      onChange && onChange({
        target: { value: editor.getData() }
      } as ChangeEvent<HTMLInputElement>)
    }}
  />
  </div>
}
```

**Comment by AmitUpadhyay878** [comment]
import CKEditor from '@ckeditor/ckeditor5-react';
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';


and my code is 

 <CKEditor
                                data={
                                    ckeditordata?.description
                                        ? ckeditordata?.description
                                        : ckeditordata
                                }
                                // editor={ClassicEditor}
                                editor={DecoupledEditor}
                                config={{
                                    removePlugins: [
                                        'EasyImage',
                                        'ImageUpload',
                                        'MediaEmbed'
                                    ],
                                    allowedContent: true,
                                    extraAllowedContent: true,
                                   
                                    toolbar: [
                                        'heading',
                                        '|',
                                        'bold',
                                        'italic',
                                        '|',
                                        'link',
                                        'bulletedList',
                                        'numberedList',
                                        // "blockQuote",
                                        // 'ckfinder',
                                        '|',
                                        // 'imageTextAlternative',
                                        // 'imageUpload',
                                        // 'imageStyle:full',
                                        // 'imageStyle:side',
                                        // '|',
                                        // 'mediaEmbed',
                                        'insertTable',
                                        // "tableColumn",
                                        // "tableRow",
                                        // "mergeTableCells",
                                        '|',
                                        'undo',
                                        'redo'
                                    ]
                                }}
                                onReady={(editor) =>
                                    // ckeditordata.description
                                    console.log(editor, 'hello')
                                }
                                onChange={handleCKEditor}
                            />


and i got below Error: 

ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
CKEditorError: ckeditor-duplicated-modules

**Comment by Witoso** [comment]
@AmitUpadhyay878 please create a new issue, most likely it's related to a build step of the editor. Please share there the details:

*   Which version of CKEditor 5 you're using,
*   Some key details about your setup (plugins, etc.) and which installation path you followed (predefined builds, online builder, DLLs).
*   The steps we should follow to reproduce the issue.
*   Any relevant code snippets or a link to a repository that illustrates the issue.
