### ISSUE TITLE
[Docs][Framework] Quick Start - Step 4 is confusing

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#589]
It took me quite a while to understand what is going on in "Step 4" on Quick Start guide. The snippet alone is confusing and I can only imagine how long it will take a new user to realise that this snippet is an extension of the snippet from "Step 3". Especially since 

I'd add some introductory description, something like:

------
Let's expand our plugin so it will actually do something. First, import `ModelElement` class:
```javascript
import ModelElement from '@ckeditor/ckeditor5-engine/src/model/element';
```
Then, add code that will be executed after prompt dialog is accepted:
```javascript
// ... The rest of snippet
```
------

Then it will be clear what is the snippet in Step 4 referring too.

**Comment by Reinmar** [comment]
Thanks. I fixed some time ago. Although, I've just noticed that the snippet in step 4 may require some more description (688ceb9).
