### ISSUE TITLE
Custom Plugin - Is there a way to create a "fixed" link (keyword)?

### ISSUE THREAD

**Issue by loagit** [ckeditor/ckeditor5#5894]
Hi.

After following [this tutorial](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html), I am trying to create a new plugin that looks like a link, but it's (it acts as) a keyword (similar to [stackoverflow keywords/tags)](https://stackoverflow.com/tags). Some of its behaviors:

1. It cannot be edited, but only removed as a whole.
2. It is not intended that when the editor is in edit mode, clicking on the link will redirect to the desired page. This behavior can only exist in read-only mode. This allows you to select the link element and move or remove it without leaving the page.
3. Since this component is added in the middle of a text, it should not be possible to apply any styling to it, such as bold, italic, text or background color, etc.
4. A button must be added to toolbar for the link address to be set.

The practice using the editor is very similar to the link button. You select a text, click the button, set the URL, and the snippet changes to the desired result.

So far I am having some difficulties. For example, of the items mentioned, I was able to complete number 1, and I think 3 as well. Numbers 2 and 4 are giving me a headache. I don't know how to make it non-clickable in edit mode so the user doesn't end up leaving the page (The representation in Editing View is being done using the `<a>` element with the `href` attribute).

Regarding item 4, I have no idea how I could add a button in the editor that has a link-like dropdown. I don't know how to create, mix, and use UI components because I don't find much documentation on the subject. I have been trying to look at [source code from other plugins](https://github.com/ckeditor/ckeditor5-link/blob/688dd63b34c9795ef239e3f6df221e54e5aa35bf/src/linkui.js) but find it hard to understand, especially as a beginner.

Here's my `keywordediting.js`:

```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import { toWidget , viewToModelPositionOutsideModelElement } from '@ckeditor/ckeditor5-widget/src/utils';
import Widget from '@ckeditor/ckeditor5-widget/src/widget';
import KeywordCommand from './keywordcommand';

export default class KeywordEditing extends Plugin
{
    static get requires()
    {
        return [Widget];
    }

    init()
    {
        this._setSchema();
        this._setConverters();

        this.editor.commands.add('keyword', new KeywordCommand(this.editor));

        this.editor.editing.mapper.on(
            'viewToModelPosition',
            viewToModelPositionOutsideModelElement( this.editor.model, viewElement => viewElement.hasClass( 'rs-kw' ) )
        );
    }

    _setSchema()
    {
        const schema = this.editor.model.schema;

        schema.register('keyword', {
            allowWhere: '$text',
            isInline: true,
            isObject: true,
            allowAttributes: ['href' , 'data-name']
        });
    }

    _setConverters(){
        const conversion = this.editor.conversion;

        // UPCAST
        conversion.for( 'upcast' ).elementToElement( {
			view: {
				name: 'a',
                classes: ['rs-kw']
			},
			model: (viewElement , modelWriter) =>
            {
                let href = viewElement.getAttribute('href');
                const name = viewElement.getChild(0).data;
    
                return modelWriter.createElement('keyword', [
                    ['href' , href] , 
                    ['data-name' , name]
                ]);
            }
         });

        // EDITING DOWNCAST
        conversion.for('editingDowncast').elementToElement({
            model: 'keyword',
            view: (modelItem, viewWriter) => {
                const widgetElement = createKeywordView(modelItem, viewWriter);

                return toWidget(widgetElement , viewWriter);
            }
        });

        // DATA DOWNCAST
        conversion.for('dataDowncast').elementToElement({
            model: 'keyword',
            view: createKeywordView
        });

        // Helper method for both downcast converters.
        function createKeywordView(modelItem, viewWriter) {
            let href = modelItem.getAttribute('href');
            
            const kwView = viewWriter.createContainerElement(
                'a', { 'href' : href , class : 'rs-kw'}
            );

            const name = viewWriter.createText(modelItem.getAttribute('data-name'));
            viewWriter.insert(viewWriter.createPositionAt(kwView, 0), name);

            return kwView;
        }
    }
}
```
And my `keywordui.js`:
```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';

export default class KeywordUI extends Plugin 
{
    init()
    {
        this._initToolbarButton();
    }

    _initToolbarButton()
    {
		const editor = this.editor;
		const kwCommand = editor.commands.get( 'keyword' );
		// const t = editor.t;

        editor.ui.componentFactory.add( 'keyword', locale => {
			const button = new ButtonView( locale );
			button.set({
				label: 'Keyword',
                tooltip: true,
                withText: true
			});

			// This doesn't work, but I've seen it before.
			// button.isEnabled = true;
			// button.label = 'Keyword';
			// button.icon = icone;
			// button.keystroke = linkKeystroke;
			// button.tooltip = true;
			// button.isToggleable = true;

			// Bind button to the command.
			button.bind( 'isEnabled' ).to( kwCommand, 'isEnabled' );
			button.bind( 'isOn' ).to( kwCommand, 'value', value => !!value );

			// Show the panel on button click.
			this.listenTo( button, 'execute', () => {
                console.log('Button pressed!');
            });

			return button;
		} );
    }
}
```

**Comment by Mgsy** [comment]
@jodator, can you take a look at it?

**Comment by Reinmar** [comment]
It sounds exactly like [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html). Did you see it? There's a demo at the end.

**Comment by Reinmar** [comment]
Oh, sorry. I focused on the 4 points that you listed instead of the surrounding text. My colleague notified me that you actually write about this guide :D 

I think I replied regarding 2nd point in https://github.com/ckeditor/ckeditor5/issues/5921. As for 4th point, unfortunately I'm not able help you beyond pointing to the link feature implementation. That's where the entire code is you should be able to recreate the same behaviour with copy-paste approach.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
