### ISSUE TITLE
Can we get a CKEditor.isBrowserSupported()

### ISSUE THREAD

**Issue by winzig** [ckeditor/ckeditor5#5896]
The docs on browser compatibility are fairly vague, with most popular browsers listed as being fully supported on latest releases. It would be helpful to know how far back support goes, so that we can gate the use of CKEditor5 to browsers that work well. Even better if this gating test could be implemented within CKEditor itself, e.g. CKEditor.isBrowserSupported(). 🙏 

Most of our users are on modern browsers, but some are limited due to their operating system circumstances. A complaint came in today from someone not seeing a cursor when editing, and the balloon editing features don't even display. I later found out they are using Firefox 45 on macOS 10.6, a very old combination to be sure.

I did some quick testing with Browserstack, and it appears Firefox < 52 is totally borked on CKEditor5 (at least when trying to use the CKEditor5 demo page editors). So I will probably manually add a test for Firefox < 52 to try and workaround that. 

A standardized way to test for CKEditor support would be very welcome.

**Comment by winzig** [comment]
FWIW, [Firefox 49 removed support for macOS 10.6, 10.7, and 10.8](https://blog.mozilla.org/futurereleases/2016/04/29/update-on-firefox-support-for-os-x/), which means that CKEditor5 won't work on Firefox on those platforms at the moment.

**Comment by Mgsy** [comment]
cc @Reinmar

**Comment by Reinmar** [comment]
CKEditor 5 does not implement any browser versions detection and checks. CKEditor 4 did it so it wasn't hard to implement such a method. Here, we'd need some additional code which is IMO hard to justify. 

In addition to that, we don't check the minimal version. As the documentation states, we officially support only the latest stable version of each browser. Those versions change too quickly now for us to maintain a more precise list.

So, while I'd love to help here, I can't justify this effort right now and IDK if ever.
