### ISSUE TITLE
ckeditor.js:Uncaught (in promise) TypeError: Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by diasraphael** [ckeditor/ckeditor5#5897]
## 📝 Provide detailed reproduction steps (if any)

1. I am trying to setup watchdog with comments and trackchanges feature for ckeditor5
2. I am following this doc for reference.
https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html#controlling-editor-creation-and-destruction
**3.After setting up the creator and destructor I am getting the above error
"TypeError: Cannot read property 'model' of undefined"
4.And please let me know how to trigger this destructor(i want to make sure not to keep outdated comments in database so should do a clean-up when the editor is destroyed or closed.)**

### ✔️ Expected result
To overcome the below error

TypeError: Cannot read property 'model' of undefined

### ❌ Actual result
TypeError: Cannot read property 'model' of undefined
getting this error when we setup the creator method of watchdog.
Before this watchdog  setup there were no errors.

## 📃 Other details

* Browser:Chrome
* OS:Windows
* CKEditor version:15.0.0
* Installed CKEditor plugins:WatchDog,Trackchanges,comments,autosave

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Please, take a look at our [Track Changes integration sample](https://github.com/cksource/ckeditor5-collaboration-samples/tree/master/track-changes-integration) and see how we implemented Watchdog. It should be useful to compare our code with yours.

**Comment by diasraphael** [comment]
Thanks for the response. The link is broken plz check. And plz provide some suggestions on how to trigger the destructor method also.
https://stackoverflow.com/questions/59171723/how-to-trigger-the-destructor-method-of-ckeditor5-watchdog

**Comment by Mgsy** [comment]
I'm sorry, indeed, I've attached the incorrect link. Now it should work fine. 

However, as Comments and Track Changes are our commercial plugins, in case of further issues, please contact us through our [support channel](https://ckeditor.com/contact/), so our team could analyze your query and find a proper solution.

**Comment by Discordius** [comment]
I am running into the same problem, help would be appreciated. Any way of calling the `watchdog.destroy()` function seems to result in a `cannot read property 'model' of undefined` error

**Comment by Mgsy** [comment]
@Discordius, can you provide exact steps to reproduce the issue? Also, please make sure that you destroy the watchdog while the editor's state is `ready`. You can check it by calling `watchdog.state;`.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by d3p4n5hu** [comment]
I'm facing this same issue. Here's the code.

`this.watchdog = new EditorWatchdog;

this.watchdog.setCreator((elem, editorConfig) => ClassicEditor
    .create(elem, editorConfig)
    .then(editor => {
        console.log('ready')
        console.log(editor)
    })
);

this.watchdog.setDestructor(editor => editor
    .destroy()
    .then(() => {
        // Do something after the editor is destroyed.
        console.log('destroyed')
    })
);

this.watchdog.create(<MY_DIV_ELEM>, <MY_CONFIG>);`

![image](https://user-images.githubusercontent.com/16369510/81908307-b3378b80-95e6-11ea-99c8-b3c2baef5caf.png)

As you can see, the editor instance is logged in console. But when i try to get the instance from watchdog, it's `undefined`.

![image](https://user-images.githubusercontent.com/16369510/81908520-f4c83680-95e6-11ea-824a-34ac28ece4e1.png)

**Comment by d3p4n5hu** [comment]
Okay i got the solution. We have to return the `editor` instance from the `.then` method after the `ClassicEditor.create` method.

This is the new code:
`this.watchdog.setCreator((elem, editorConfig) => ClassicEditor
                    .create(elem, editorConfig)
                    .then(editor => {
                        console.log('ready')
                        console.log(editor)
                        return editor;
                    })
                );`

We should update the docs as well for this as it isn't mentioned there.

**Comment by Mr-Lion** [comment]
Hello folks,

I have the same problem and the solution here definitely doesn't work!

> Ok ich habe die Lösung. Wir müssen die `editor`Instanz von der `.then`Methode nach der `ClassicEditor.create`Methode zurückgeben.
> 
> Das ist der neue Code: `this.watchdog.setCreator((elem, editorConfig) => ClassicEditor .create(elem, editorConfig) .then(editor => { console.log('ready') console.log(editor) return editor; }) );`
> 
> Wir sollten auch die Dokumentation dafür aktualisieren, da es dort nicht erwähnt wird.

That's what I tried too. Still the same error comes up.

I ask for help and bug fix
