### ISSUE TITLE
table cells merge, table plugin UI & UX

### ISSUE THREAD

**Issue by nemiro** [ckeditor/ckeditor5#5898]
First or all, Table plugin of ckeditor 5 lacks of possibilities and convenience from ckeditor 4.

Cannot select multiple cells; cannot select rows, cols; cannot modify cell styles (cell background for example).
Cannot merge multiple cells (because of no multiple selection), cannot unmerge cells from left/top.

It is really cool how it's been made at [moqups.com](url) or at [paper.dropbox.com](url)

![image](https://user-images.githubusercontent.com/4909921/70143021-99932f00-16ab-11ea-88e1-576068608abd.png)
![image](https://user-images.githubusercontent.com/4909921/70143298-41a8f800-16ac-11ea-96f8-27643b76c861.png)
![image](https://user-images.githubusercontent.com/4909921/70143327-56858b80-16ac-11ea-8ccc-3cb52dacd619.png)

ability to select rows, cols, cells (multiple or all), always visible panel , ability to resize cols\rows, understandable cols\rows insert

Is it in plans or something similar? May be I can do some help somehow?

**Comment by Mgsy** [comment]
Hi! Sorry for the late response. We're aware that CKEditor 5 table plugin is missing some important features, however, we're still developing it and functionalities mentioned in your report are on our roadmap. Please, see the ticket about styling cells (it includes also multi-cell selection) - [https://github.com/ckeditor/ckeditor5/issues/3287](https://github.com/ckeditor/ckeditor5/issues/3287). As you can see, we started working on it and there's a PR with initial implementation which will be available in the upcoming release.
