### ISSUE TITLE
Allow to disable auto embed

### ISSUE THREAD

**Issue by robclancy** [ckeditor/ckeditor5#5903]
I have been having 1 common issue with ckeditor. I can't configure a lot of stuff. This one seems like a no-brainer. I tried `removePlugins: [ 'AutoMediaEmbed' ],` but it never worked. You include this plugin as a dependency for another one which doesn't make sense either. Embedding doesn't require auto embeding to work (it didn't even exist at first). It shouldn't be forced in like that as a dependency. If anything the `MediaEmbed` is a dependency of `AutoMediaEmbed`.

But the simple solution without getting into if it should be a dependency or not is to just be able to do `autoMediaEmbed: false`?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
That's correct, `AutoMediaEmbed` plugin is required by default by the media embed plugin - https://github.com/ckeditor/ckeditor5-media-embed/blob/b8b4b929d2a6d8eaa9efaa568fa0bdbec7d76872/src/mediaembed.js#L36

However, as `MediaEmbed` plugin is a glue which connects all the required parts of the plugin, you can simply import those dependencies instead of `MediaEmbed` (or create a new plugin which will require dependencies without `AutoMediaEmbed`. So, use:

```
import MediaEmbedEditing from '@ckeditor/ckeditor5-media-embed/src/mediaembedediting';
import MediaEmbedUI from '@ckeditor/ckeditor5-media-embed/src/mediaembedui';
import Widget from '@ckeditor/ckeditor5-widget/src/widget';
```

instead of:

```
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed'
```

**Comment by robclancy** [comment]
Really? This is your response? ...

Starting to get concerned about our choice of editor.

**Comment by nasa8x** [comment]
I added this config fixed this problem:

```
  autoMediaEmbed: {
      isEnabled: false,
  },
```

**Comment by gravelfox** [comment]
@robclancy you ever figure out a way to disable this?

**Comment by neongreen** [comment]
@gravelfox see my workaround at https://github.com/ckeditor/ckeditor5/issues/9816#issuecomment-1793427291

**Comment by robclancy** [comment]
I don't even know if I disabled this. I have so many stupid hacks and workarounds for this editor I've lost track.

**Comment by HaNdTriX** [comment]
Just if anyone is looking for a solution. Here is a drop in replacement without `AutoMediaEmbed`.

```ts
import { Plugin } from '@ckeditor/ckeditor5-core'
import { Widget } from '@ckeditor/ckeditor5-widget'
import MediaEmbedEditing from '@ckeditor/ckeditor5-media-embed/src/mediaembedediting'
import MediaEmbedUI from '@ckeditor/ckeditor5-media-embed/src/mediaembedui'

import '@ckeditor/ckeditor5-media-embed/theme/mediaembed.css'

/**
 * Fork of the media embed plugin.
 * With AutoMediaEmbed disabled.
 *
 * more info: https://github.com/ckeditor/ckeditor5/issues/5903#issuecomment-563180441
 */
export class MediaEmbed extends Plugin {
  /**
   * @inheritDoc
   */
  public static get requires() {
    return [MediaEmbedEditing, MediaEmbedUI, Widget] as const
  }

  /**
   * @inheritDoc
   */
  public static get pluginName() {
    return 'MediaEmbed' as const
  }
}

export type { MediaEmbedConfig } from '@ckeditor/ckeditor5-media-embed'
```

**Comment by macs1756** [comment]
***If you work with strapi***
I disabled it in node_modules, file -
 "/node_modules/@ckeditor/strapi-plugin-ckeditor/admin/src/components/CKEditorinput/Configurator.js"
add 'removePlugins: ['MediaEmbed']' in config object
