### ISSUE TITLE
Support removing the toolbar on the classic editor, it half works already

### ISSUE THREAD

**Issue by robclancy** [ckeditor/ckeditor5#5904]
We want to use ckeditor for comments so we can use autoformat and have comments act like slack messages (before their terrible editor). At first I just set `toolbar: false` and then used some CSS hacks to hide the remains. But then I extended the editor and made the template empty. https://github.com/postedin/ember-ckeditor/blob/master/addon/comment-editor.js#L8

`toolbar: false` works, I don't know if this is something that was meant to work. But it leaves some UI behind which is pretty ugly.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Hi!

Removing a toolbar has never been a feature we considered in this kind of an editor. So what you did, actually, is a hack. If you want to have full control over the shape of the editor, you can either:
* use the [`DecoupledEditor`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html#static-function-create) and not inject the toolbar anywhere,
* or [create your own](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html).

BTW: If you still feel like hacking, you can remove the toolbar of the editor in the runtime by calling `editor.ui.view.top.remove( 0 )`. It looks simpler.

**Comment by robclancy** [comment]
Alright I've done it the nicer way but still hacky. https://github.com/postedin/ember-ckeditor/blob/6e2d7d90e41ec0ac911d2e8704883a804adf938b/addon/comment-editor.js#L9

I do plan to update this to have more custom builds for this kind of thing anyway and to split out the different builds into their own addons for ember.
