### ISSUE TITLE
 setData: unexpected result with latex expression

### ISSUE THREAD

**Issue by centaur54dev** [ckeditor/ckeditor5#5906]
## 📝 Reproduction steps
Using setData with an argument containing a latex expression produces unexpected result. For example:
```
let editor = ClassicEditor
	        .create(  editorDiv )
	        .then( (editor) => {
                    editor.setData("<p>\\[x=0\\]</p>");
	        } )
```

### ✔️ Expected result
\\[x=0\\]

### ❌ Actual result
x=0x=0

## 📃 Other details
It is remarkable that the issue occurs only during editor initialization. Running the setData command with the same argument, through the console (after the editor is loaded) works normally.

* Browser: chrome
* OS: linux mint
* CKEditor version: 16
* Installed CKEditor plugins: default ClassicEditor

**Comment by Mgsy** [comment]
Hello, I'm not able to reproduce your issue. It works fine if I use `editor#setData` after the initialization as well as in the console. Do you use any third-party plugins/libraries?

**Comment by ETHwsch** [comment]
I can confirm that a plain Ckeditor 5 version works correctly: https://jsfiddle.net/Lvywge37/4/

The error seems to be related to the ckeditor5-math-preview plugin: https://github.com/centaur54dev/ckeditor5-math-preview#readme
An example which envisions the wrong behavior can be seen here: https://jsfiddle.net/ub472vq6/

**Comment by centaur54dev** [comment]
Indeed i have accidentally loaded the math-preview plugin when i was looking at this bug. Accept my apologies.
