### ISSUE TITLE
Copy&pasting code snippets from our docs to the code blocks demo gives ugly results

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5907]
Just copy&paste one of the snippets (from outside of the editor) that's available on https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html into the editor.

You need to select the code snippet with some surrounding text (start the selection before a code snippet). Selecting just the content of a code snippet and copying it works fine.

![image](https://user-images.githubusercontent.com/156149/70214110-1b7e6900-173b-11ea-847b-fb29151fdb24.png)

**Comment by AvanthikaMeenakshi** [comment]
Does anyone know why this is happening? When I paste without formatting(cmd+shift+v) it is working fine.

**Comment by Reinmar** [comment]
I *think* it should be resolved by now.

**Comment by Reinmar** [comment]
Yup, fixed in the nightly.
