### ISSUE TITLE
Undo / Redo events handling

### ISSUE THREAD

**Issue by vadimud** [ckeditor/ckeditor5#5912]
Please create an example of Undo / Redo events handling (callback) from another custom plug-in.

Currently I try to use following approach: 
`editor.model.document.on( 'change:data', (eventInfo, batch) => {`
`...<custom code>...`
`		} );`

But this code fired for any changes, not for changes according Undo / Redo events.

Thanks for help.

[CKEditor 5, plugin example]

**Comment by Mgsy** [comment]
Hello, you can listen on undo/redo command `execute` event. Please, see the example below:

```js
const undoCommand = editor.commands.get( 'undo' );
const redoCommand = editor.commands.get( 'redo' );

undoCommand.on( 'execute', eventInfo => {
    console.log( 'Undo has been fired.' );
} );

redoCommand.on( 'execute', eventInfo => {
    console.log( 'Redo has been fired.' );
} );
```

**Comment by vadimud** [comment]
Thanks.
