### ISSUE TITLE
CKEditor5 Resize

### ISSUE THREAD

**Issue by PavanSrivatsav** [ckeditor/ckeditor5#5913]
## 📝 Provide a description of the new feature
Can we have a feature to resize the CKEditor like CKEditor 4 resizer?

*What is the expected behavior of the proposed feature?*
https://ckeditor.com/docs/ckeditor4/latest/assets/img/resize_01.png
The user should be able to drag and set his/her required size.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! We decided to not introduce the editor resize feature. Please, see the discussion in https://github.com/ckeditor/ckeditor5/issues/636 where you'll find an explanation for this decision.

**Comment by pikulinpw** [comment]
For those who've been looking for a solution to dynamically adjust the height of CKEditor 5 and add resize capabilities, I'm excited to share a new plugin I've developed: https://github.com/pikulinpw/ckeditor5-resizableheight

**Key Features**:
- Dynamically adjust the height of the CKEditor instance.
- Option to resize the editor, providing a more flexible editing environment.
- Set specific height options or allow the plugin to determine the height based on content.
- Seamless integration with CKEditor 5.

It's now available on npm and easy to integrate with your existing CKEditor setup. Check out the README for installation and usage instructions.

Feedback, bug reports, and contributions are welcome. Let's make our CKEditor experience even better!

**Comment by kyrofa** [comment]
@pikulinpw thank you for this, your plugin works wonderfully for my purposes.

**Comment by kuige** [comment]
add the following css to enable the resize behavior

```css
.ck-editor__main {
  resize: vertical;
  overflow: auto;
}
.ck-editor__editable {
  height: 100%;
  scrollbar-width: thin;
}
```
