### ISSUE TITLE
Allow placeholder text on editable widgets

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#5916]
## 📝 Allow placeholder text on editable widgets

*What is the expected behavior of the proposed feature?*

For editable elements, I'd like to be able to define some placeholder text that will be shown in the editing view when the element is empty. Generally you'd be able to do this with a CSS `:empty` selector, but since CKE5 adds "data-cke-filler" elements inside empty elements when they're rendered, that no longer works.

### Possible implementation

For example, if I had an editingDowncast like this: 

```
        conversion.for( 'editingDowncast' ).elementToElement( {
            model: 'questionTitle',
            view: ( modelElement, viewWriter ) => {
                const h5 = viewWriter.createEditableElement( 'h5', {
                    'data-placeholder': 'Question Title',
                } );

                return toWidgetEditable( h5, viewWriter );
            }
        } );
```

I'd like it to automatically add the `ck-placeholder` class to the `h5` element in the view when the `h5` is empty, and remove the class when the `h5` contains text.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
@jodator, can you take a look at it?

**Comment by Reinmar** [comment]
Hi @rshipp! If I understand your ticket correctly, this should already be possible. Check out this piece of code from ckeditor5-image:

```js
import { enablePlaceholder } from '@ckeditor/ckeditor5-engine/src/view/placeholder';
import { toWidgetEditable } from '@ckeditor/ckeditor5-widget/src/utils';

/**
 * Returns a function that creates a caption editable element for the given {@link module:engine/view/document~Document}.
 *
 * @param {module:engine/view/view~View} view
 * @param {String} placeholderText The text to be displayed when the caption is empty.
 * @returns {Function}
 */
export function captionElementCreator( view, placeholderText ) {
	return writer => {
		const editable = writer.createEditableElement( 'figcaption' );
		writer.setCustomProperty( 'imageCaption', true, editable );

		enablePlaceholder( {
			view,
			element: editable,
			text: placeholderText
		} );

		return toWidgetEditable( editable, writer );
	};
}
```

Does it solve your use case?

**Comment by rshipp** [comment]
@Reinmar thanks for the reply! It looks like that method is called by a custom listener on 'insert:caption' events - what I was hoping for was for ckeditor to automatically define a listener like this and call enablePlaceholder/disablePlaceholder as appropriate, so I didn't have to manage that myself. Do you think that would be in scope for an engine feature?

**Comment by Reinmar** [comment]
The [`enablePlaceholder()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_placeholder.html#static-function-enablePlaceholder) function does exactly that. It takes care of showing/hiding the placeholder text. The `disablePlaceholder()` method is for disabling this functionality completely.

**Comment by rshipp** [comment]
oh! I misunderstood, this probably does solve my usecase then. I'll try it out asap.

**Comment by Reinmar** [comment]
Cool! And if you feel that the docs could be improved, a PR would be awesome :)

**Comment by rshipp** [comment]
Works great, thanks for the pointer! Reading the [docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_placeholder.html#static-function-enablePlaceholder) again now I don't know how I'd change them to make it clearer. I'd love to see more working examples like you have in the Tutorials section, but I understand CKE can just do too many things that its not feasible to have tutorials for everything.

**Comment by rshipp** [comment]
Is there a suggested workaround for handling the edge case where an element is empty except for a `paragraph` element? The #1464 workaround means some of my nested editables are never completely empty. Would I have to attach a placeholder to the `p` inside the `editable` somehow?
