### ISSUE TITLE
How do I create a link in Editing View without allowing it to be clicked in edit mode?

### ISSUE THREAD

**Issue by loagit** [ckeditor/ckeditor5#5921]
### DESCRIPTION

I am creating a keyword plugin, and it's purpose is to allow certain words in the editor to be highlighted in a special way. When the content is published, and the reader begins reading, he or she may click on these highlighted words to be directed to a link specified by the word itself.

### THE PROBLEM

During the editing process, you can click on the highlighted word to select it, but this makes you to leave the editor page. I wish the editor user could click on the word to select it, but without been redirected. Word selection is important as it can be removed if necessary.

In summary, the component is defined as follows in Editing View:

`<a href="https://somewebsite.com" class="rs-kw">text</a>`

In the Model:

`<keyword href="https://somewebsite.com" data-name="text"></keyword>`

This new element behaves like a widget and is stated in the schema as follows:

```
schema.register('keyword' , {
   allowWhere: '$text',
   isInline: true,
   isObject: true,
   allowAttributes: ['href', 'data-name']
});
```

CSS style:

```
.rs-kw {
   color: #0099cc;
   background: none;
   padding: 0px 2px;
   font-family: Candara;
   font-weight: bold;
   text-decoration: none;
   border-style: solid;
   border-width: 1px;
   border-color: #0099cc;
   box-shadow: 2px 2px #0099cc;
}
```
Is it possible to do this kind of procedure?

**Comment by Reinmar** [comment]
AFAIR, browsers don't allow clicking `<a>` elements in editable elements, so I don't think that any additional action should be needed from your side. But just in case I forgot something, you can scan  the code of [https://github.com/ckeditor/ckeditor5-link/blob/master/src/linkediting.js](https://github.com/ckeditor/ckeditor5-link/blob/master/src/linkediting.js) which implements support for `<a>` elements too and they are not clickable at all.

PS. You can also consider having different elements in the view than `<a>`.

**Comment by Reinmar** [comment]
I saw [https://github.com/ckeditor/ckeditor5/issues/5894](https://github.com/ckeditor/ckeditor5/issues/5894) from you and I can see that you use widgets, so you actually make fragments of text non-editable again, hence the native link handling is opening links.

To prevent that, just `preventDefault()` on `mousedown` on those links.
