### ISSUE TITLE
How can we export full HTML with styles?

### ISSUE THREAD

**Issue by TuguldurJ** [ckeditor/ckeditor5#5925]
Hello guys,

How can we export full HTML with styles?

This is crucial thing for WYSIWYG document editors.

editor.getData returns elements with only class names.

But how can we get those class styles?
ie. `<figure class="image image-style-align-center image_resized">`

Is there any other HTML extraction with exact styles???

Otherwise, it would useless for content editors and email writers.

Your competitors like froala, stripo.email, beefree.io can easily export HTML with styles and Responsive Images. 

Another thing that setting width for figure element is useless for email templates. ESP's do not support that element.

For big picture, your main feature should be deliverable content! not only in-box content.

Any suggestion?

**Comment by TuguldurJ** [comment]
#5923

**Comment by Mgsy** [comment]
Hello, the list of all available styles can be found in our [Content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) guide.

**Comment by TuguldurJ** [comment]
Hello

I read it.
Email clients do not support class.
We need extract html elements with its styles without class declaration in
css.

ie. <img style=“width: 132px;”></img>

**Comment by Mgsy** [comment]
Unfortunately, it's not possible to receive HTML with inline styles. We have an open feature request for it - https://github.com/ckeditor/ckeditor5/issues/1627. Feel free to add 👍 to the first post to bump its popularity and join the discussion.

**Comment by peterfargo2** [comment]
If not available in ckeditor5, Is this feature a part of ckeditor4? Also looking to export for email purposes.

**Comment by tienanh2907** [comment]
let's do it, please
