### ISSUE TITLE
balise wrapper.

### ISSUE THREAD

**Issue by xorgxx** [ckeditor/ckeditor5#594]
Hi i use ver.5 of Ckeditor. all work well.
But i have he small problem, when i try to put fullscreen (clic bar menu ckeditor) i cant see anythink. i discover that ckeditor change my balise existing wrapper balise on my main html and this is why i have this problem.

How i can change this problem on ckeditor to not do this?

Thank

**Comment by Reinmar** [comment]
I'm sorry, but I don't understand what you're asking. However, it seems that it's about integration with some external application. If so, https://stackoverflow.com/questions/tagged/ckeditor5 would be a better place to ask for help but you'll need to be far more specific.

Let us know if you'll open a question on StackOverflow or provide more information here if you think that you stumbled upon a bug in CKEditor 5 or if you think that it's a feature request.

**Comment by Reinmar** [comment]
I see that you asked your question in https://stackoverflow.com/questions/46649823/ckeditor-5-fullscreen-wrapper-balise-conflict.
