### ISSUE TITLE
[Docs] Add methods which should appear higher in search results

### ISSUE THREAD

**Issue by m-turek** [ckeditor/ckeditor5#595]
I plan to add `importants` array to `docsearch` config in `umberto.json`
The purpose of this is to make several API methods more important when performing a search

Example:

```
"docsearch": {
		"apiKey": "fc463c26455365ad403d5ec51796cd73",
		"indexName": "ckeditor_nightly",
	  	"importants": [
		  "module:editor-balloon/ballooneditor~BalloonEditor.create",
		  "module:editor-classic/classiceditor~ClassicEditor.create",
		  "module:editor-inline/inlineeditor~InlineEditor.create",
		  "module:core/editor/editor~Editor.create"
		]
	}
```

Currently these methods don't appear in search results when a "create" search query is performed

**Comment by oleq** [comment]
Can you specify what is the point of this issue?

**Comment by m-turek** [comment]
Sorry, updated the firt comment

**Comment by ma2ciek** [comment]
Maybe it could be done with a special tag instead of hardcoding if it's a more common problem?

**Comment by m-turek** [comment]
We could use a special tag, but I'm not 100% sure that boosting search results will work as expected, so I'd rather test it by hardcoding first (before putting effort into creating tag plugins and updating source code comments)

**Comment by Reinmar** [comment]
Yep, this is fastest we can do and easiest to maintain actually.
