### ISSUE TITLE
There's no doc page showcasing how to add a button to a toolbar

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5950]
## 📝 Provide a description of requested docs changes

I was searching the docs for a place that showcase how to create a UI component and add it to a toolbar. We have a [UI library page](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/ui-library.html) but it is so generic that it doesn't explain how to define a component and then use it in the CKEditor toolbar configuration. At least I couldn't find one.

Such a page should IMO:

1. Describe how to define ui component:

    ```js
    editor.ui.componentFactory.add( 'myButton', locale => {
        const button = new ButonView( locale );
        // .. some relevant customization
       return button;
    } );
    ```
2. Probably showcasing some wiring with a command or custom logic.
3. Add this button to various toolbars (at least main and image or table).

    ```js
    ClassicEditor.create( el, {
        plugins: [ ..., MyButtonUI ],
        toolbar: [
            'bold', 'italic', '|',
            'myButton'
        ],
        image: {
            toolbar: [ 'myButton' ]
        }
    } );
    ```

**Comment by Mgsy** [comment]
Actually, adding custom buttons to the toolbar is described in [Creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html#step-3-registering-a-button) and [Implementing a block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#creating-a-button) guides. Do you think we should extract it to some other page (i.e. UI library)?

**Comment by jodator** [comment]
Yeah, I've forgot about this. But anyway we should add such section to the UI library page to show how to wire things together.

**Comment by godai78** [comment]
Extracting no, referencing it more - for sure. I, for one, needed that but learnt the thing myself ;)

**Comment by godai78** [comment]
I'm positive this guide would be very much the answer for these needs, too: https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/toolbar.html
