### ISSUE TITLE
Wiris MathType and ChemType are missing code where disabling commands disables toolbar buttons

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#5957]
## 📝 Provide detailed reproduction steps (if any)

1. Run CKEditor with the following code :
```
const commands = [ 'MathType', 'ChemType', 'link' ];
for ( const command of commands ) {
	  const commandToBlock = editor.commands.get( command );
	  commandToBlock.on( 'change:isEnabled', evt => {
		  commandToBlock.isEnabled = false;
		  evt.stop();
	  }, { priority: 'lowest' } );

	  commandToBlock.isEnabled = false;
};
```

### ✔️ Expected result

MathType and ChemType plugins toolbar buttons should be disabled and commands should not work.

### ❌ Actual result

Commands for MathType and ChemType plugins don't work however buttons are enabled which gives the false impression that plugins are working.

## 📃 Other details

* Browser: Any
* OS: Any
* CKEditor version: Any
* Installed CKEditor plugins: MathType, ChemType

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
This issue is fixed in the new MathType version 7.19.0
