### ISSUE TITLE
Mention plugin is missing code where disabling command disables the key listener

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#5958]
## 📝 Provide detailed reproduction steps (if any)

1. Use below configration for Mention plugin:
```
	mention: {
            feeds: [
                {
                    marker: '@',
                    feed: [ '@Barney', '@Lily', '@Marshall', '@Robin', '@Ted' ],
                    minimumCharacters: 1
                }
            ]
        },
```

2. Use the following code at editor start (inside `.then()`):
```
const commands = [ 'mention' ];
for ( const command of commands ) {
	  const commandToBlock = editor.commands.get( command );
	  commandToBlock.on( 'change:isEnabled', evt => {
		  commandToBlock.isEnabled = false;
		  evt.stop();
	  }, { priority: 'lowest' } );

	  commandToBlock.isEnabled = false;
};
```
3. Type inside the editor `@T`

### ✔️ Expected result

Nothing happens.

### ❌ Actual result

Mention panel pops out. The command does not work because selecting anything from the panel has no result however plugin gives the false impression that it is working.
![issue](https://user-images.githubusercontent.com/5314687/70611269-34888d80-1c05-11ea-872c-8bfe2b472304.gif)

## 📃 Other details

* Browser: Any
* OS: Any
* CKEditor version: Any
* Installed CKEditor plugins: mention

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
cc @jodator

**Comment by jodator** [comment]
@Mgsy yes this one is confirmed. Basically we would need to change the mention plugin to check the command state before trying tho show the UI. Now you can trigger mention where it is not allowed.

**Comment by mlewand** [comment]
Also AFAIR listeners can be conditionally disabled all along, so we could disable [keydown listener](https://github.com/ckeditor/ckeditor5-mention/blob/9a514ccb0dc8b595100fd4459a82fa67cc329d1d/src/mentionui.js#L111) along with the command.
