### ISSUE TITLE
HTML Source plugin

### ISSUE THREAD

**Issue by saiky** [ckeditor/ckeditor5#5965]
## 📝 There is an extensive requirement of source code to check the back-end HTML  of the editor content.

*This extension will show the HTML source we can edit over there or put a new class or create a new HTML component*

**Comment by saiky** [comment]
The source option is not available with Angular Plugin of CK editor

**Comment by jodator** [comment]
Hello @saiky. We already have this reported: https://github.com/ckeditor/ckeditor5/issues/592.
