### ISSUE TITLE
How can i switch between standard mode and restricted mode ?

### ISSUE THREAD

**Issue by bittu1028** [ckeditor/ckeditor5#5968]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

*What is the expected result of the above steps?*

### ❌ Actual result

*What is the actual result of the above steps?*

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Standard and restricted modes are based on plugins, so if you'd like to switch between those, you can reload the editor with the proper plugin. You'll find more information on the [plugin documentation page](https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html#running-the-standard-editing-mode).

Please, see the example in [restricted editing manual test](https://github.com/ckeditor/ckeditor5-restricted-editing/blob/master/tests/manual/restrictedediting.js).

**Comment by pragyaaaaa** [comment]
@Mgsy I want to switch between standard and restricted modes exactly as shown in the features demo here[feature demo on this page](https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html) 
How can it be achieved? I've followed the documentations on installing plugins and modifying js but I'm kinda stuck with this.
