### ISSUE TITLE
wrong path when render data image

### ISSUE THREAD

**Issue by quyetDK** [ckeditor/ckeditor5#5973]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

http://api.localhost/1576292047597-pexels-photo-414612.jpeg

### ❌ Actual result

http://api.localhost/1576292047597-pexels-photo-414612.jpeg 0w
( redundant "0w" )
## 📃 Other details

* Browser: All
* OS: …
* CKEditor version: "@ckeditor/ckeditor5-vue": "^1.0.0",

* Installed CKEditor plugins:
- "@ckeditor/ckeditor5-image": "^15.0.0",
- "@ckeditor/ckeditor5-upload": "^15.0.0",
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, can you describe your issue more precisely and provide steps to reproduce your problem?
