### ISSUE TITLE
How to allow classes to figure tag

### ISSUE THREAD

**Issue by bum-hyun** [ckeditor/ckeditor5#5974]
I want to insert a custom element that contains custom class to figure tag.

like
`<p>`
    `<figure class='custom-class'>`
         `<img class="" src="${src}">`
       ` <figcaption></figcaption>`
    `</figure>`
`</p>`

so, I add below code in onReady method 

    editor.model.schema.register('figure', {
      inheritAllFrom: '$block', or 'figure'
      allowAttributes: ['class', 'style'],
      isBlock: true
    });

but, Editor still didn't allow custom class.
How can I solve it?

**Comment by Mgsy** [comment]
Hi! There's no `figure` element in the model, so your schema record won't work. As the model image has a `figure` container in the view, you can allow `class` attribute on the model image and add it to the `figure` element in the view. 

See the example below:
```js
editor.conversion.attributeToAttribute( {
	model: {
		name: 'image',
		key: 'class',
		value: 'custom-class'
	},
	view: {
		name: 'figure',
		key: 'class',
		value: 'custom-class'
	}
} );
```

Additionally, if you'd like to have a custom figure class on every image inserted to the document, you can extend the conversion:

```js
editor.conversion.for( 'downcast' )
	.add( dispatcher => dispatcher.on(
		'insert:image',
		( evt, data, conversionApi ) => {
			// Obtain already converted item
			const viewElement = conversionApi.mapper.toViewElement( data.item );
			if ( viewElement ) {
				// Add a custom class to it
				conversionApi.writer.addClass( 'custom-class', viewElement );
			}
		},
		// Use the lowest priority to make sure that this will be run
		// after default converters.
		{ priority: 'lowest' }
	) );
```
