### ISSUE TITLE
modules are duplicated when building editor

### ISSUE THREAD

**Issue by felek000** [ckeditor/ckeditor5#5975]
## 📝 Provide detailed reproduction steps (if any)
When i was adding Alignment  or table plugin i get this error. As soon i remove them the build is going smoothly

```
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Link from '@ckeditor/ckeditor5-link/src/link'
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';

class ClassicEditor extends ClassicEditorBase {
}

ClassicEditor.builtinPlugins = [
    Alignment,
    Essentials, Paragraph, Bold, Italic, Link, Image, ImageStyle, ImageToolbar, ImageUpload,ImageResize,
];
ClassicEditor.defaultConfig = {
    toolbar: {
        items: ['bold', 'italic', 'link','alignment']
    },
    image: {
        toolbar: ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],
        styles: [
            'full',
            'alignLeft',
            'alignRight'
        ]
    },
    language: 'pl'
};
ClassicEditor.create(document.querySelector('#editor'))
    .then(editor => {
        console.log(editor);
    });

```

### ✔️ Expected result

editor show up no error

### ❌ Actual result

*What is the actual result of the above steps?*

## 📃 Other details

* Browser: chrome
* OS: Windows
* CKEditor version: 5

**Comment by Mgsy** [comment]
Hello, can you check if your dependencies are updated? You can use \[npm-check-updates\]([https://www.npmjs.com/package/npm-check-updates](https://www.npmjs.com/package/npm-check-updates)) to verify it. There's a chance that it causes the problem.

**Comment by robclancy** [comment]
This thing has caused me so much pain. Whenever I run into it I open `node_modules/@ckeditor/` then go through every package. Any package that has a `node_modules` folder inside it is most likely duplicating a module. So I work that out and then add a resolution in `package.json`. 

For example, for the patch I need if there is a ckeditor update it will duplicate, so I have this:
```json
  "resolutions": {
    "@ckeditor/ckeditor5-upload": "https://github.com/robclancy/ckeditor5-upload.git#patch-2"
  },
```

It would be nice if the error gave more information though so I don't need to go searching.

**Comment by felek000** [comment]
I did like so delete all node_modules and lock file. Then install one more time and build runs. For now :)
