### ISSUE TITLE
Code block: doesn't work with the markdown data processor

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#5977]
## 📝 Provide detailed reproduction steps (if any)

1.  Create an editor that uses the markdown data processor.
2.  That editor will not properly load code blocks existing in markdown data and an error is thrown.

**Comment by fredck** [comment]
The fix is pretty simple. Tests included.

I'm also proposing a small chance to the the test utils available in core, to make it possible to test editors with different DPs.

**Comment by fredck** [comment]
Updated the ticket description because, in fact, an error is thrown, not only data loss.

**Comment by Reinmar** [comment]
It's similar to the `Clipboard` plugin which also has to instantiate its own HTMLDP.

**Comment by fredck** [comment]
This seems to be fine now with v20.0.0.
