### ISSUE TITLE
Code block: disable spell checking inside code.

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#5978]
Spell checking shouldn't be enabled inside code blocks, because of the nature of such blocks. Otherwise, lots of spell checking issues are pointlessly found in the code inside the blocks.

Example:

![](https://user-images.githubusercontent.com/630060/70923711-93e10600-2028-11ea-8fa7-c3b994585cf1.png)

**Comment by Reinmar** [comment]
I guess this makes sense. It'd be ideal to have a smarter spellchecking there, like in VSCode but that's for WSC guys to consider. The native spellcheck has to be disabled.
