### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#598]
Having an issue template will help the community in reporting valid and complete tickets.

It'd also be good to have templates for typical answers like – what if someone ignored the issue template.

**Comment by oleq** [comment]
I think [this one](https://github.com/ckeditor/ckeditor-dev/issues/new) would do the trick for now.

**Comment by Reinmar** [comment]
I find it slightly too complicated. I had problems figuring out where to write what myself. cc @mlewand

**Comment by fredck** [comment]
I'm quite unsure a template is really valuable. If it'll really-really make a difference on the quality of the issues. It can just make it more difficult, in fact.

Are other popular projects using it?

But ofc, it *may* reduce the amount of "support request" issues, but I still don't see it as a big problem for now.

**Comment by Reinmar** [comment]
Yep, a lot of projects use issue templates. First 3 I checked:

* https://github.com/babel/minify/blob/master/.github/ISSUE_TEMPLATE.md (and the whole Babel ecosystem)
* https://github.com/webpack/webpack/blob/master/.github/ISSUE_TEMPLATE.md
* https://github.com/angular/angular-cli/blob/master/.github/ISSUE_TEMPLATE.md

And when I checked a couple of recent issues in https://github.com/ckeditor/ckeditor-dev/issues?utf8=%E2%9C%93&q=is%3Aissue they were nicer than how I remembered them from the past, so perhaps that's thanks to the template as well. @mlewand, did you notice some improvement after you introduced the template?

**Comment by fredck** [comment]
I like the readability of the Angular one. It makes a better use of empty lines.

**Comment by Roshanjossey** [comment]
This is the issue template I use in my project
https://github.com/Roshanjossey/first-contributions/blob/master/ISSUE_TEMPLATE.md

Here's a sample issue
Roshanjossey/first-contributions#802

🐞 Problem

🎯 Goal

💡 Possible solutions

📋 Steps to solve the problem

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - Addresses #<put issue number here>
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

This is working extremely well for me. I've written a blog post about it
https://medium.com/@roshanjossey/how-better-issues-improve-collaboration-5a4e6ff95e90

Do reply if you like it. I'll submit a pull request to include this

**Comment by Reinmar** [comment]
I like the idea to use Unicode emojis. It's an easy and visually simple way to divide the text into fragments – they are more visible than `##` (heading characters in MD). But we'd need a bit different sections. Right now I can think of:

* Bug report or feature request?
* Version
* Steps to reproduce
* Expected result
* Actual result
* Other details that might be useful

I also think we could provide a link to our docs where we'd show an example of how issue can be reported with some additional information like where to get the version from.

WDYT?

**Comment by oleq** [comment]
The emoji approach LGTM. I'd like to use headers, though:
```
## 🐞 Problem
```

**Comment by Reinmar** [comment]
Thanks @Roshanjossey for the PR!

I improved the formatting of the template a bit and now it looks like this:

![image](https://user-images.githubusercontent.com/156149/31842465-8e18e036-b5ee-11e7-8e50-6ad37c90acce.png)

Let's see how it works in this repo and we'll add it to other repos too or do necessary adjustments.

**Comment by oleq** [comment]
I just found out that this template brings some confusion to references because it uses checkboxes that GH recognizes as checklists:

![image](https://user-images.githubusercontent.com/1099479/31995510-f00e828e-b984-11e7-934a-59fd81e5225f.png)

There's no to–do list in the issue, it's all about `- [x] Bug report`. It may cause some confusion in the tracker, WDYT?

**Comment by pjasiun** [comment]
I also find these checkboxes strange (its the multiple chose what is strange for me). I would replace it with something like:

"Bug report/Feature request (delete unnecessary)"

**Comment by oleq** [comment]
I'm glad I'm not the only one freaking out 😛 

I think something like this would do the trick:

```
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report
- Feature request
```

**Comment by oleq** [comment]
I've just noticed that recently users submitted lots of issues which are basically requests for help which usually resolve when the right link to the documentation is provided. 

I think to reduce the noise around here, the template should point to Gitter and/or SO in such situations because this GH is not the right kind of place for this kind of discussion.

**Comment by mlewand** [comment]
You might want to use `SUPPORT.md` file for that, see:

* https://github.com/blog/2400-support-file-support
* https://help.github.com/articles/adding-support-resources-to-your-project/

**Comment by vokiel** [comment]
As this issue is still open...

What about replacing the green :negative_squared_cross_mark: with the red one: :x: which better (IMHO) shows, that something is wrong with the current result.

Another thing is the beetle emoji in the *Is this a bug report or feature request?* header, always starting with a :beetle: emoji, which is wrong for features. So I would go with :beetle: / :new: or add them to the list and remove from header, like:

---

## Is this a bug report or feature request? (choose one)

- :beetle: Bug report
- :new: Feature request

## 💻 Version of CKEditor



## 📋 Steps to reproduce

1.
2.

## ✅ Expected result

## :x: Actual result

## 📃 Other details that might be useful

**Comment by jodator** [comment]
@vokiel it probably dependends on used fonts for emojis:

![selection_003](https://user-images.githubusercontent.com/247363/35271388-3d7c959e-0032-11e8-947f-87e67bf4c729.png)

ps.: that cross is a bit more distinguishable though..

**Comment by vokiel** [comment]
Interesting, looks like it's more browser specific, than OS:

**Chrome / Opera / Vivaldi**
![screenshot_20180123_115259](https://user-images.githubusercontent.com/422571/35272002-118b4a0a-0034-11e8-8027-acfd355bb43c.png)

**Firefox**:
![screenshot_20180123_115309](https://user-images.githubusercontent.com/422571/35272006-199a004c-0034-11e8-827b-f1291508c3d1.png)

**Comment by jodator** [comment]
Yeah: this cross is very inconsistent across different styles: https://emojipedia.org/negative-squared-cross-mark/. The https://emojipedia.org/cross-mark/ has consistent colors though.

**Comment by Reinmar** [comment]
One thing which I don't like in the current template is that the bug report and feature request are two list items. If you delete one of them you'll be left with a list of one list item which is neither semantically correct nor looks nice.

Also, I kinda miss the third option "Other" or "I'm not sure" for all kinds of issues which you're not sure about. Also, we often report issues of type "task" or "docs" so "Other" would be best for them.

So, what do you think about? 

```
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  | Other

## 💻 Version of CKEditor

<!-- Please specify CKEditor version, build type and all customizations. -->

## 📋 Steps to reproduce

1.
2.

## ✅ Expected result

## ❎ Actual result

## 📃 Other details that might be useful
```

**Comment by Reinmar** [comment]
We recommend reporting issues and feature requests in this repository and since the issue template is mostly for the community, I think that it's completely enough that it's only defined in this repository.

Thanks!
