### ISSUE TITLE
Should SpecialCharactersXXX require SpecialCharacters?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5981]
Right now each of `SpecialCharactersXXX` (such as `SpecialCharactersEssentials` or `SpecialCharactersArrows`) require (has as a dependency) `SpecialCharacters`. 

However, the documentation of all those plugins state that you need to use them like this:

```js
		ClassicEditor
			.create( {
				plugins: [ ..., SpecialCharacters, SpecialCharactersEssentials ],
			} )
			.then( ... )
			.catch( ... );
```

Which doesn't make much sense because `SpecialCharactersEssentials` will load `SpecialCharacters`. Also, `SpecialCharactersEssentials` access the base plugin vis `editor.plugins.get( 'SpecialCharacters' )` so it does not link to the base plugin anywhere except its `requires()` getter.

So, should we untangle them or fix the docs?

**Comment by Reinmar** [comment]
cc @jodator

**Comment by jodator** [comment]
Looking at what we have now we probably should untangle them.

1. `TableToolbar` plugin does not require `Table` but alone the plugin makes no sense - but does not use `Table` inside.
2. The `TextTransformation` plugin uses `Input` without `requires()` definition (same package).
3. Most other plugins do require plugins from other packages if they use them.

Also, looking at how this feature could be configured (using all pages or only subset) it makes sense to make this two+ plugin requirement:
- `plugins: [ ..., SC, SCEssentials ]`
- `plugins: [ ..., SC, SCLatin, SCText ]`
