### ISSUE TITLE
ckeditor-duplicated-modules when installing SimpleUploadAdapter

### ISSUE THREAD

**Issue by dthibau** [ckeditor/ckeditor5#5990]
I am following [instructions](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)
to install the SimpleUploadAdapter

In my working directory
1. npm install --save @ckeditor/ckeditor5-upload
2. Edit ckeditor.js (as provided) 
`import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';

import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import Font from '@ckeditor/ckeditor5-font/src/font';
import Autosave from '@ckeditor/ckeditor5-autosave/src/autosave';
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
	Essentials,
	Autoformat,
	Bold,
	Italic,
	Underline,
	BlockQuote,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	Alignment,
	RemoveFormat,
	Indent,
	IndentBlock,
	Font,
	Autosave,
	SimpleUploadAdapter
];

// Editor configuration.
ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'alignment',
			'bold',
			'italic',
			'link',
			'bulletedList',
			'numberedList',
			'imageUpload',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'undo',
			'redo'
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};`
3. rm -rf node_modules && npm i
4. yarn run build

Then I open sample/index.html :  CKEditor is not loaded and I got the following msg in the console : 
`Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.`

**Comment by robclancy** [comment]
You would have installed latest version of it but using old versions of other parts of ckeditor. yarn/npm will then duplicate to support both versions but ckeditor doesn't like that. You need to make sure all versions are the same for everything to do with the `@ckeditor` org.

**Comment by dthibau** [comment]
You should be right 
I cloned the repo https://github.com/ckeditor/ckeditor5-build-classic.git, perharps 2 weeks ago
Then I rebuilt ckeditor several times to add each plugin I need
When I add the `SimpleUploadAdapter` today, I ran into problems.

What do you suggest me to do ? Edit manually the `package.json` ? Clone the repo again ? Indicate the version when I install a plugin

Here is my package.json 

`{
  "name": "@ckeditor/ckeditor5-build-classic",
  "version": "12.4.0",
  "description": "The classic editor build of CKEditor 5 – the best browser-based rich text editor.",
  "keywords": [
    "ckeditor5-build",
    "ckeditor",
    "ckeditor5",
    "ckeditor 5",
    "wysiwyg",
    "rich text",
    "editor",
    "html",
    "contentEditable",
    "editing",
    "operational transformation",
    "ot",
    "collaboration",
    "collaborative",
    "real-time",
    "framework"
  ],
  "main": "./build/ckeditor.js",
  "files": [
    "build"
  ],
  "devDependencies": {
    "@ckeditor/ckeditor5-alignment": "^11.2.0",
    "@ckeditor/ckeditor5-autoformat": "^11.0.5",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.4",
    "@ckeditor/ckeditor5-block-quote": "^11.1.3",
    "@ckeditor/ckeditor5-core": "^12.3.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.4",
    "@ckeditor/ckeditor5-essentials": "^11.0.5",
    "@ckeditor/ckeditor5-heading": "^11.0.5",
    "@ckeditor/ckeditor5-image": "^14.0.0",
    "@ckeditor/ckeditor5-link": "^11.1.2",
    "@ckeditor/ckeditor5-list": "^12.1.0",
    "@ckeditor/ckeditor5-media-embed": "^11.1.4",
    "@ckeditor/ckeditor5-paragraph": "^11.0.5",
    "@ckeditor/ckeditor5-paste-from-office": "^11.1.0",
    "@ckeditor/ckeditor5-table": "^14.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^14.2.0",
    "eslint": "^5.5.0",
    "eslint-config-ckeditor5": "^2.0.0",
    "husky": "^1.3.1",
    "lint-staged": "^7.0.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^3.1.0",
    "style-loader": "^1.0.0",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "webpack": "^4.39.1",
    "webpack-cli": "^3.3.6"
  },
  "engines": {
    "node": ">=8.0.0",
    "npm": ">=5.7.1"
  },
  "author": "CKSource (http://cksource.com/)",
  "license": "GPL-2.0-or-later",
  "homepage": "https://ckeditor.com/ckeditor-5",
  "bugs": "https://github.com/ckeditor/ckeditor5/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/ckeditor/ckeditor5-build-classic.git"
  },
  "scripts": {
    "build": "webpack --mode production",
    "lint": "eslint --quiet '**/*.js'",
    "preversion": "npm run build; if [ -n \"$(git status src/ckeditor.js build/ --porcelain)\" ]; then git add -u src/ckeditor.js build/ && git commit -m 'Internal: Build.'; fi"
  },
  "lint-staged": {
    "**/*.js": [
      "eslint --quiet"
    ]
  },
  "eslintIgnore": [
    "build/**",
    "packages/**"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@ckeditor/ckeditor5-autosave": "^11.0.5",
    "@ckeditor/ckeditor5-font": "^11.2.2",
    "@ckeditor/ckeditor5-highlight": "^11.0.5",
    "@ckeditor/ckeditor5-indent": "^10.1.0",
    "@ckeditor/ckeditor5-remove-format": "^10.0.4",
    "@ckeditor/ckeditor5-upload": "^16.0.0"
  }
}`

**Comment by dthibau** [comment]
I tried to downgrade @ckeditor/ckeditor5-upload to 12.0.0
The CKEditor appears in the sample page but with another erros msg in the console ;
`CKEditorError: plugincollection-plugin-name-conflict: Two plugins with the same name were loaded.`

Not easy to get compatible versions of all these plugins !

**Comment by ma2ciek** [comment]
Hi!

Try to upgrade all of the \`@ckeditor\` plugins to the latest version.

**Comment by Mgsy** [comment]
[npm-check-updates](https://www.npmjs.com/package/npm-check-updates) is a nice tool for bumping dependencies versions.

**Comment by dthibau** [comment]
I finally managed to do it.
First, I tried with `npm-check-updates`, it updated my `package.json` but when I ran `yarn run build `
I got : 
```
ERROR in ckeditor.js from UglifyJs
Unexpected token: keyword «const» [./node_modules/@ckeditor/ckeditor5-utils/src/ckeditorerror.js:13,7][ckeditor.js:122,0]
```

Then I redid everything from the beginning, clone the repo, make each installation of the needed plugins ... and it works.

Thank u everybody for your good comments.
