### ISSUE TITLE
Restricted Editing Improvements

### ISSUE THREAD

**Issue by panr** [ckeditor/ckeditor5#5992]
In **Restricted** mode:
- ~root shouldn’t be editable (contenteditable = false), you don't want to see a caret in places that you can't edit.~
- content with **cursor: default**
- exceptions with **cursor: text** (contenteidtable = true)
- ✅ `cmd/ctrl + a` inside current exception should select only text inside that exception (not all content inside editor) (done in https://github.com/ckeditor/ckeditor5-restricted-editing/pull/16)

--
How to do this? Through CSS class? Any other ideas?

**Comment by jodator** [comment]
>     * `cmd/ctrl + a` inside current exception should select only text inside that exception (not all content inside editor)

Dup of: https://github.com/ckeditor/ckeditor5/issues/5826.

**Comment by jodator** [comment]
> * root shouldn’t be editable (contenteditable = false), you don't want to see a caret in places that you can't edit.

That's one of the requirements - navigate through the docs using caret. So this might be either configurable or invalid. But I don't have a strong (any) opinion on that.

**Comment by panr** [comment]
> Dup of: https://github.com/ckeditor/ckeditor5/issues/5826.

Cool 😎

**Comment by panr** [comment]
✅ cmd/ctrl + a inside current exception should select only text inside that exception (not all content inside editor)

**Comment by panr** [comment]
OK, I pushed the last PR related to the restricted editing improvements listed above.
