### ISSUE TITLE
Make horizontal-line work with track-changes

### ISSUE THREAD

**Issue by phaux** [ckeditor/ckeditor5#5994]
Use `model.insertContent` instead of `writer.insert` so that the changes regarding the `<horizontalLine>` are automatically picked up by the `track-changes` plugin.

**Comment by pomek** [comment]
In page-break, after inserting an element, we try to put a selection in the first editable after the inserted element. If the element does not exist, we create and insert it. The same fix could be applied here – https://github.com/ckeditor/ckeditor5-page-break/blob/9b0f43fd498b2dac483283e39bb7d80f61b0102a/src/pagebreakcommand.js#L54.
