### ISSUE TITLE
Markdown-GFM: not escaping HTML in text

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#5997]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the [markdown demo](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html).
2.  Type some text which contains HTML in it, like "\<h1>Test\</h1>".

### ✔️ Expected result

The output should be `\<h1>Test\</h1>`, according to the [GFM specs](https://github.github.com/gfm/#backslash-escapes).

### ❌ Actual result

Current output: `<h1>Test</h1>`.

**Comment by jodator** [comment]
It looks like fixed by the #7307 .
