### ISSUE TITLE
Improve Context docs

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#6001]
We are [introducing](https://github.com/ckeditor/ckeditor5/issues/5891) `Context` class and new type of plugin, a `ContextPlugin`.

It brings some important functionalities to CKEditor Ecosystsem so we need a good API and feature docs to explain in details how to use it.

Besides as @scofalik [noticed](https://github.com/ckeditor/ckeditor5-core/pull/204#pullrequestreview-332593603) `Editor` and `Context` may share an interface in API docs.

**Comment by Reinmar** [comment]
DUP of [https://github.com/ckeditor/ckeditor5/issues/6008.](https://github.com/ckeditor/ckeditor5/issues/6008)
