### ISSUE TITLE
Markdown-GFM: make it a plugin

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#6007]
Currently, including the GFM data processor in an editor is a bit cumbersome, requiring creating a custom editor for that purpose. 

According to [https://github.com/ckeditor/ckeditor5/issues/2848](https://github.com/ckeditor/ckeditor5/issues/2848), the markdown-gfm package should provide a plugin that enables its data processor.

**Comment by ma2ciek** [comment]
It'd be a perfect solution for the CKEditor 5 Online builder. Currently there's no easy way to add this plugin to the sample because it has a custom initialization. 

Since it's rather an easy task with quick benefits, maybe we could raise the priority of this issue?
