### ISSUE TITLE
Warnings on the CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6013]
Not sure why, but I've seen two warnings on CI. They should crash their respective tests, but they didn't. 

This a screenshot from ckeditor5's https://travis-ci.org/ckeditor/ckeditor5/builds/627100105:

![image](https://user-images.githubusercontent.com/156149/71186968-71482a80-227e-11ea-95a5-3d2d55bd1723.png)

**Comment by Reinmar** [comment]
Another one is here [https://travis-ci.org/ckeditor/ckeditor5/builds/627217770?utm\_source=github\_status&utm\_medium=notification](https://travis-ci.org/ckeditor/ckeditor5/builds/627217770?utm_source=github_status&utm_medium=notification).

**Comment by ma2ciek** [comment]
There's a high chance both warnings are displayed just after the test passes. And mocha can't make the just passed test fail, because it lacks knowledge which of the previous tests actually threw. The same problem happens in the CF codebase.

**Comment by pomek** [comment]
Mention warning is already fixed – https://github.com/ckeditor/ckeditor5-mention/commit/3c207d0c6ed963cec5c44f90d96fe678793ac4e1.

The error alert will be fixed after merging this PR – https://github.com/ckeditor/ckeditor5-upload/pull/108.

**Comment by pomek** [comment]
After fixing https://github.com/ckeditor/ckeditor5/issues/5892 the issue will be fixed as well so I am closing this one as a DUP.
