### ISSUE TITLE
onDelete Image method

### ISSUE THREAD

**Issue by ztjustin** [ckeditor/ckeditor5#6017]
## 📝 Provide a description of the new feature

*What is the expected behavior of the proposed feature?*

Exists something that I can get the element removed, this is for example when i try to delete a image and  i want  to delete it from the server side
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! There's no any `onDelete` event for elements, however, CKEditor 5 has a [differ](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_differ-Differ.html) which allows you to get changes in the document. 

I've made a code sample which listens on changes in the document, saves the selected image element (or elements) and returns removed images. Does it solve your case?

```js
const elements = [];

editor.model.document.on( 'change', () => {
	const selectedBlocks = editor.model.document.selection.getSelectedBlocks();

	if ( selectedBlocks ) {
		for ( const block of selectedBlocks ) {
			if ( block.name == 'image' && !elements.includes( block ) ) {
				elements.push( block );
			};
		};
	}
} );

editor.model.on( 'deleteContent', () => {
	const changes = editor.model.document.differ.getChanges();

	for ( const change of changes ) {
		if ( change.type == 'remove' && change.name == 'image' ) {
			console.log( 'The image has been removed.' );
			console.log( elements.shift() );
		}
	};
} );
```
