### ISSUE TITLE
TextTransformation creates 30+ instances of TextWatcher

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6020]
`TextTransformation` creates a new `TextWatcher` instance for every configured transformation. This is completely non-optimal. We should have one `TextWatcher` and check all transformations in it. And then react to `matchetd:data` and check whcih transformation we matched.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @jodator

**Comment by Reinmar** [comment]
I'm thinking about something like this:

```plaintext
		const watcher = new TextWatcher( editor.model, text => {
			for ( const transformation of configuredTransformations ) {
				const from = normalizeFrom( transformation.from );
				const to = normalizeTo( transformation.to );
			
				const match = from.test( text );

				if ( match ) {
					// Return match meta data so we can access that in the `matched:data` event.
					return { match, transformation };
				}
			}
		} );

		watcher.on( 'matched:data', ( evt, data ) => {
			const transformation = data.transformation;

			// Apply the transformation...
		} );

```

Which means that the return value of `TextWatcher` callback must allow returning some metadata (in this case – the `transformation` object that we need later on in `matched:data` listener.

**Comment by jodator** [comment]
Yeah, I was worried about that and probably left for next step which supposed to be openeing the API.

~The problem with that might be different and might be deeper.~ Nah we can fix that as you proposed. I would only advise to not take this example as-is. Ie, the `from/to` might be stored somewhere to not create them every time user type. The `for` loop should be AFAP® (as-fast-as-possible) IMO.

The other things is that we could rething this watcher API and how the test callbacks are registered but passing stuff in the data is OK.
