### ISSUE TITLE
Mismatched plugin versions causes "CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated."

### ISSUE THREAD

**Issue by adamerose** [ckeditor/ckeditor5#6027]
## 📝 Provide detailed reproduction steps (if any)
1. Start with a working version of a simple project using ClassicEditor in React building from source at version 15.0.0
2. Add plugins for Image and Base64UploadAdapter and run `npm install @ckeditor/ckeditor5-upload @ckeditor/ckeditor5-image`, which automatically installed versions 16.0.0
3. Run the app with `npm start`

### 👀 Example Repo
Here's an example...
https://github.com/adamerose/cke-craco-tutorial/tree/base64upload

`master` branch is the working version before adding plugins. The 1st commit on `base64upload` branch reproduces the bug, and 2nd commit downgrades the plugin versions and works again.

### ✔️ Expected result
App should run with the automatically installed plugin versions

### ❌ Actual result
I get the following error
`CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules`

### 📃 Workaround
Downgrade `@ckeditor/ckeditor5-upload` and `@ckeditor/ckeditor5-image` to 15.0.0 and it works again.

## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 15
* Installed CKEditor plugins: 
    "@ckeditor/ckeditor5-basic-styles": "^15.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.5",
    "@ckeditor/ckeditor5-editor-classic": "^15.0.0",
    "@ckeditor/ckeditor5-essentials": "^15.0.0",
    "@ckeditor/ckeditor5-image": "^16.0.0",
    "@ckeditor/ckeditor5-paragraph": "^15.0.0",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-theme-lark": "^15.0.0",
    "@ckeditor/ckeditor5-upload": "^16.0.0",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! You use dependencies from different versions. All dependencies except those from `ckeditor5-dev-*` and integrations (e.g. `ckeditor5-react`) should be in the save version. Here, you have some in `v15.0.0` and some in `v16.0.0` which is why it doesn't work.

**Comment by adamerose** [comment]
@Reinmar May I suggest adding a check for this and a separate error message? The error in my post seems unrelated and the page it links to does not mention versioning at all. It's not obvious that plugins have to be the same version, I didn't see that in the docs.
