### ISSUE TITLE
CKEditor5 iOS

### ISSUE THREAD

**Issue by wernerbouwer** [ckeditor/ckeditor5#603]
Hi. I use to be able to browse the CKEditor5 examples on my IPhone 6, iOS (10) from CKEditor.com without a problem. Now, there is no Toolbar visible and the Editors seem to allow no interaction? Am I the only one experiencing this? Thank you.

**Comment by Reinmar** [comment]
Hey,

I'm afraid that you'll need to upgrade to iOS 11, first. It contains a critical fix for Safari's bug in ES6 support. That's why you don't see anything.

I think I made a mistake removing a workaround for this issue that quickly ;| I can see that quite a lot of people use iOS10 still.

**Comment by Reinmar** [comment]
According to our analytics only 65% of ckeditor.com's visitors has iOS11 installed already so we may need to consider bringing back the workaround ;/

cc @fredck

**Comment by wernerbouwer** [comment]
Thank you for the feedback. Will do the update asap. Thanks for a great product.

**Comment by Reinmar** [comment]
PS. I covered the "nothing works" part, but I haven't mentioned what you'll see after you'll upgrade :D

Basically, there are issues with the UI that we're aware of. The status of things are described in https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/browser-compatibility.html#Mobile-environment and the tl;dr is that, according to our research, for small-res devices we'll need a completely separate UI. This is still a TODO for us.
