### ISSUE TITLE
It was not possible to load the plugin

### ISSUE THREAD

**Issue by Olegars** [ckeditor/ckeditor5#6030]
## 📝 Provide detailed reproduction steps (if any)
Hi
1.  I followed the "Using CKEditor from source" section at the below link, also creating the project using 'vue create'.

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source2. …
2.When running 'yarn  serve' everything works ok. 
3.When  opening resulted build in a browser ckeditor does not open. Browser displaying mistake 
`plugincollection-load: It was not possible to load the plugin. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-load
` 
### ✔️ Expected result
How can i solve it?
## 📃 Other details

* Browser: firefox, chrome
* OS: ubuntu 18
* vue: 2.6.11
* CKEditor version: 5
* Installed CKEditor plugins: …
"@ckeditor/ckeditor5-alignment": "^15.0.0",
    "@ckeditor/ckeditor5-autoformat": "^15.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^15.0.0",
    "@ckeditor/ckeditor5-block-quote": "^15.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.5",
    "@ckeditor/ckeditor5-editor-classic": "^15.0.0",
    "@ckeditor/ckeditor5-essentials": "^15.0.0",
    "@ckeditor/ckeditor5-font": "^15.0.0",
    "@ckeditor/ckeditor5-highlight": "^15.0.0",
    "@ckeditor/ckeditor5-image": "^15.0.0",
    "@ckeditor/ckeditor5-link": "^15.0.0",
    "@ckeditor/ckeditor5-list": "^15.0.0",
    "@ckeditor/ckeditor5-media-embed": "^15.0.0",
    "@ckeditor/ckeditor5-paragraph": "^15.0.0",
    "@ckeditor/ckeditor5-table": "^15.0.0",
    "@ckeditor/ckeditor5-theme-lark": "ckeditor/ckeditor5-theme-lark",
    "@ckeditor/ckeditor5-vue": "^1.0.0"
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Olegars** [comment]
I beg pardon, figured out

**Comment by Elawphant** [comment]
How did you resolve this?
