### ISSUE TITLE
Allow to default a manual link decorators value

### ISSUE THREAD

**Issue by robclancy** [ckeditor/ckeditor5#6031]
https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links

We are using the open in new tab option here but want it to default to true.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thanks. That's a good idea.

**Comment by rodrigofarcas** [comment]
Hi, is this going to make at some point? Many of our users are very interested on this feature.

**Comment by robclancy** [comment]
@Reinmar @niegowski I have tested this multiple times now and I still can't see it working.

```js
decorators: {
              addTargetToLinks: {
                mode: 'manual',
                label: 'Open in a new tab',
                defaultValue: true,
                attributes: {
                  target: '_blank',
                  rel: 'noopener noreferrer',
                },
              },
```

**Comment by robclancy** [comment]
Okay so it works when you use the toolbar and click link, which was never really an issue because the user can see to make it a new tab or not easily. The issue is when you paste a link it auto links to be internal. This still happens.
