### ISSUE TITLE
tempalte support jsx-style syntax

### ISSUE THREAD

**Issue by solorhyme0109** [ckeditor/ckeditor5#6032]
## 📝 Provide a description of the new feature

*What is the expected behavior of the proposed feature?*
It would be very excited if template support jsx style or vue-template style syntax.
```
// current
this.setTemplate({
  tag: 'input',
  attributes: {
    class: [ 'foo',  bind.if( 'isEnabled', 'ck-enabled' )],
    placeholder: bind.to('placeholder' )
   },
  on: {
    keydown: bind.to( 'input' )
  }
})

// expect
this.template = 
<input
  :class="{ foo: true, 'ck-enabled'': bind.if('isEnabled') }"
  @keydown="bind.to('input')"
/>
```
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thanks for the idea. In general, we considered JSX but we wanted to avoid introducing unnecessary dev dependencies. Whatever we use become other people dependency and therefore we strive to stay as tool-agnostic as possible.
