### ISSUE TITLE
How to create a widget with dynamic/unmanaged content

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#6036]
Hello, I'm trying to create a simple widget which displays some dynamic (read only) content. As a base I was following [this guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html).

Widget displays dynamic content which means that generating content (rendering) will be handled externally by another script. As an example you can imagine that as a content of the widget I want to render a table with data loaded asynchronously.

My plan was to create `editingDowncast` like this:

```javascript
<section class="dynamic-widget">
   <script type="text/javascript">
        // this should replace content of <section> element with custom rendered content
        window.doCustomRendering(document.currentScript.parentNode);
   </script>
</section>
```
(`dataDowncast` will omit the script tag or any other rendered content)

The plugin works correctly in the sense that the model is correctly downcasted to what I want - section and script tag are rendered into the editor and script is executed when the DOM is rendered.

But now I was surprised that my `doCustomRendering()` function is not able to replace the content of `<section>` element. Emptying, appending elements simply does nothing. Even if I open a chrome developer console and try to manually delete the contents of the `<section>`, the content seems to be immediately restored.

So it seems like CKEditor prevents external editing of the DOM which kind of makes sense to me as it tries to keep model, view and rendered DOM in sync. 

My question is - how can I create a widget which will have an "unmanaged" content - i.e. content which can be freely manipulated by application script without inteference from CKEditor? I'd like to avoid iframe if possible ...

Thanks.

**Comment by jodator** [comment]
Hello - you should use [`UIElement`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-createUIElement) - it basically allows us to render any DOM content inside the editing view that is not translated to the model (although the wrapper must be in the model). An example of such a mix is described in the [React component inside CKeditor 5 widget guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/using-react-in-a-widget.html).

**Comment by zadam** [comment]
Yes, that's exactly what I was looking for, thanks!
