### ISSUE TITLE
Bump year in copyright headers

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6040]
## Provide a description of the task

It's _time_ to reflect year change in copyright headers of our source files.

**Comment by pomek** [comment]
Done in CKE 5 and all its packages (https://github.com/ckeditor/ckeditor5/commit/0b3b33bef8b75e90e0af221f889394178c57b9b7).

**Comment by pomek** [comment]
Done in ckeditor5-dev (https://github.com/ckeditor/ckeditor5-dev/commit/cf765584e771e2f4eb15ee7ded1bb495ed7cdbf6).

**Comment by pomek** [comment]
Done in integrations:

- React (https://github.com/ckeditor/ckeditor5-react/commit/b8dd780f8aaec62b1dae000fab0637d3ee2187b5)
- Vue (https://github.com/ckeditor/ckeditor5-vue/commit/f947ac39755a28dd9bc7a74d6c96dc734953ffd6, `dist/` was not changed)
- Angular (https://github.com/ckeditor/ckeditor5-angular/commit/fbb596fe5caa834ca41ba0078ff03aefa7df3886)
- Inspector (https://github.com/ckeditor/ckeditor5-inspector/commit/a5a8749dfb7bb5b4edee65ddf59cda293db0f005)

**Comment by pomek** [comment]
Did I miss anything? Please, reopen if so.
