### ISSUE TITLE
Watchdog.create() call test case silently failing

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6042]
## 📝 Provide detailed reproduction steps (if any)

While working on #6002 I noticed that the ["should not throw an error when the destructor is not defined" unit case](https://github.com/ckeditor/ckeditor5-watchdog/blob/c89a99aaa53fb1fcdd847b48d780e25508a9419f/tests/watchdog.js#L61-L66) is causing DOM leaks.

Upon closer look it turned out that the promise returned by [`watchdog.create()`](https://github.com/ckeditor/ckeditor5-watchdog/blob/c89a99aaa53fb1fcdd847b48d780e25508a9419f/tests/watchdog.js#L65) is silently rejected (rejection caused by unhandled exception).

Two things here:

1. First this means that this test doesn't pass, as this call per unit test should not throw exception. [If you adjust the test in a way that it waits for the promise resolution](https://github.com/ckeditor/ckeditor5-watchdog/commit/2ef7452b50ced84ef5d03ae7b74b1d5140917d9d) then it fails.
1. Why isn't this reported by Karma in a first place? I can see it reported when running Karma in debugging mode, but it is not reported to the console and it went unnoticed for a longer time.

## 📃 Other details

This issue might be related to #5897.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
In this case we should temporarily remove the test until this is resolved, so there's no leak affecting other tests. The main problem now is that it triggers a promise, and doesn't wait for it, so the leak kicks in 1 / 2 tests later (as mocha is not aware that something is till happening so it starts next test cases).

**Comment by ma2ciek** [comment]
Yep, I can confirm it, that test wait for the `editor.create()` to finish.

**Comment by ma2ciek** [comment]
> Why isn't this reported by Karma in a first place? I can see it reported when running Karma in debugging mode, but it is not reported to the console and it went unnoticed for a longer time.

Karma (or rather mocha) mutes all promise rejections between tests unfortunately.

**Comment by oleq** [comment]
Bonus: If you add a test after this last one https://github.com/ckeditor/ckeditor5-watchdog/blob/9b6ace1ab5050355f49f264c0231b68351d495c4/tests/watchdog.js#L1033, it will never be executed. I tried adding one with just debugger call to see the state of DOM and it never ran.

```diff
diff --git a/tests/watchdog.js b/tests/watchdog.js
index c69f21b..620df4a 100644
--- a/tests/watchdog.js
+++ b/tests/watchdog.js
@@ -1087,6 +1087,14 @@ describe( 'Watchdog', () => {
                                     } );
                   } );
          } );
+
+         describe( 'cleanup category', () => {
+                  it( 'cleanup test ', () => {
+                           expect( true ).to.be.true;
+
+                           debugger;
+                  } );
+         } );
 } );

 function throwCKEditorError( name, context ) {
```

**Comment by ma2ciek** [comment]
Maybe it's somehow connected with the `window.onerror` replacements I've made in those tests. I'll investigate it more once I've a little bit more time. Maybe there's a better solution to test error handling mechanisms.
