### ISSUE TITLE
Image uploading i not working with vue plugin

### ISSUE THREAD

**Issue by nehadhiman6** [ckeditor/ckeditor5#6045]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

*What is the expected result of the above steps?*

### ❌ Actual result

*What is the actual result of the above steps?*

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hello,
I just checked image upload integration in Vue and it works fine. Could you please provide more detailed steps of your integration process? Are you using Easy Image, CKFinder or custom image adapter? It would be also easier to investigate this issue if you could provide some error messages and your CKEditor configuration.
