### ISSUE TITLE
No proper documentation for vue 

### ISSUE THREAD

**Issue by nehadhiman6** [ckeditor/ckeditor5#6046]
## 📝 Provide a description of requested docs changes

*What is the purpose and what should be changed?*

**Comment by FilipTokarski** [comment]
Hello,

As it comes to integrating CKEditor and Vue, we have a documentation page here:
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html

Is there any specific issue or case, that you want to know and that is not mentioned in the docs? We would be grateful for some more detailed information.
