### ISSUE TITLE
Is there a plug-in for tables in v5?

### ISSUE THREAD

**Issue by 7iomka** [ckeditor/ckeditor5#605]
Is there a plug-in for tables in v5?

**Comment by scofalik** [comment]
Hi,

the tables plugin has not been yet developed for CKEditor 5. We will be working on it in short future, but we are not giving any date right now.

If you are interested, you can take a look at [our roadmap](https://github.com/ckeditor/ckeditor5-design/issues/172).

**Comment by scofalik** [comment]
BTW. Such simple to answer questions can be asked on our Gitter channel: gitter.im/ckeditor/ckeditor5

**Comment by Reinmar** [comment]
Yep, as @scofalik wrote, we're going to start working on it very soon. I created a ticket for it in https://github.com/ckeditor/ckeditor5/issues/610.
