### ISSUE TITLE
[upload] One of test gives invalid results

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#6055]
```
ALERT: TypeError: Cannot read property 'upload' of undefined
TypeError: Cannot read property 'upload' of undefined
    at eval (webpack:///./packages/ckeditor5-upload/src/filerepository.js?:499:31)
```

It seems like an error. The test should fail and the entire build as well. But it doesn't.

**Comment by ma2ciek** [comment]
It's quite common when a promise is rejected after the test passes.

**Comment by pomek** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/5892.
