### ISSUE TITLE
Console usage no longer causes CI to fail

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6056]
## Provide a description of the task

For at least few weeks now (unstubbed) `console.*` usage no longer causes the CI to fail, while it did a while ago. This was introduced with #1996.

An example is https://travis-ci.org/ckeditor/ckeditor5/builds/634643857?utm_medium=notification&utm_source=github_status

Despite running the tests with `--production` flag (formerly `----disallow-console-us`), which should break the builds.

Time to figure out why it is no longer working and fix it.

**Comment by ma2ciek** [comment]
That's because the error / log is done after the test passes. And because the `mocha` can't figure out which test caused the error.

**Comment by mlewand** [comment]
Sounds reasonable @ma2ciek. But it would be great if cases like this would still fail CI tests.

**Comment by mlewand** [comment]
Getting into the root cause of this problem will actually take some time for us, which we don't have in this iteration. So we'll just fix this praticular case for now with #6057.
