### ISSUE TITLE
Support for pasting content from Google Sheets

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6059]
## 📝 Provide a description of the new feature

It'd be nice if CKEditor 5 could handle content created in Google Sheets. 

Currently, there's one annoying issue which occurs only on Windows:

1. Type "test" inside a cell in Google Sheets.
1. Select the cell.
1. Copy it.
1. Paste it to the editor.

This is what appears in the editor:
```html
<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->test
```
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@ckeditor/qa-team could we check if it's still valid on Windows? There were a few improvements in pasting from GSheets recently.

**Comment by Witoso** [comment]
Ha, interesting! Thanks! This demo has full GHS turned on, so the style is preserved in the data downcast. Closing, not sure though which iteration fixed this.
