### ISSUE TITLE
help: how to getData from the model range

### ISSUE THREAD

**Issue by yuyinjun** [ckeditor/ckeditor5#6061]
I want to getData from a model Range
<pre name="code" class="javascript">
for (const marker of editor.model.markers) {
      const markerRange = marker.getRange();
      for (const child of markerRange) {
        if(child.is('node')){
          const viewNode=editor.editing.mapper.toViewElement(child);
          console.log(editor.data.processor.toData(viewNode));
         }
        if(child.is('textProxy')){`
         // i dont want to get child.data, i want to get html ,how can i do
        }
    } 
 } 
</pre>

**Comment by Mgsy** [comment]
Hi! I assume that you'd like to get a marker element as HTML. You can use [`mapper#markerNameToElements`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_mapper-Mapper.html#function-markerNameToElements) and  [`view#domConverter`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_domconverter-DomConverter.html#function-mapViewToDom).

```js
const domConverter = editor.editing.view.domConverter;
const mapper = editor.editing.mapper;
const markers = editor.model.markers;

for ( const marker of markers ) {
      const viewElements = mapper.markerNameToElements( marker.name );
      
      viewElements.forEach( element => {
        console.log( domConverter.mapViewToDom( element ) );
      } )
 } 
```

The sample output of the above code will be:
```html
<span class="ck-comment-marker" data-comment="ef849d1027d51a34caf92d39ccac1e18b">goal of CKEditor&nbsp;5</span>
```
