### ISSUE TITLE
Editor crashes when trying to apply browsers spellcheck suggestion in table cell in chrome/safari

### ISSUE THREAD

**Issue by cutteroid** [ckeditor/ckeditor5#6062]
Editor crashes when trying to apply browsers spellcheck suggestion inside table cell in chrome/safari

![Screen Recording 2020-01-10 at 16 41 08](https://user-images.githubusercontent.com/20125880/72161948-b79a3080-33c9-11ea-86ef-057bfbee18da.gif)

Stacktrace:
```
Uncaught CKEditorError: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
 {"offset":9,"nodeList":[{"name":"paragraph","children":[{"data":"this "}]},{"name":"paragraph","children":[{"data":"computer"}]}]}
    at Ws.offsetToIndex (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:226045)
    at Ys.offsetToIndex (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:227117)
    at Ks.get index [as index] (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:231967)
    at Ks.get textNode [as textNode] (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:232043)
    at zc (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:342883)
    at jc._validateSelectionRange (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:342719)
    at fa.<anonymous> (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:262468)
    at fa.fire (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:128711)
    at fa._setRanges (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:255934)
    at fa.setTo (https://ckeditor.com/assets/libs/ckeditor5/16.0.0/ckeditor.js:5:255010)
```

## 📃 Other details

* Browser: Chrome/Safari
* OS: OS X 10.15.2
* CKEditor version: 16.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi! 
Thank you for reporting this. I checked it and unfortunately can confirm - this bug happens on Chrome, Safari and new chromium-based Edge, both Win10 and macOS.
Seems like regression, I was not able to reproduce this on older versions of CKEditor ( v12.0.0 ).
Firefox seems to be working fine.

**Comment by Mgsy** [comment]
It occurs also in v15.0.0.

**Comment by Mgsy** [comment]
I've investigated this issue and it looks like this change has introduced the bug - https://github.com/ckeditor/ckeditor5-typing/commit/0aeb3848d48200fde311bf8e393f522acb4f2a45.

**Comment by Reinmar** [comment]
OK, first finding:

![image](https://user-images.githubusercontent.com/156149/73360284-e0b03180-42a2-11ea-8932-e40073f618b6.png)

There are two mutations that are being handled. Unfortunately, something incorrect happens between them so when the 2nd one is being handled, the selection is in an incorrect place (after a paragraph).

**Comment by Reinmar** [comment]
The first mutation:

```
{type: "text", oldText: "see comter", newText: "see ", node: Text}
```

So, it easily deletes the old text.

The 2nd mutation:

```
{
    type: "children"
    oldChildren: Array(1)
         0: ContainerElement {parent: EditableElement, name: "span", _attrs: Map(0), _children: Array(1), _classes: Set(0), …}
    newChildren: Array(2)
         0: ContainerElement {parent: EditableElement, name: "span", _attrs: Map(0), _children: Array(1), _classes: Set(0), …}
         1: Text {parent: null, _textData: "commuter"}
    node: EditableElement {parent: ContainerElement, name: "td", _attrs: Map(1), _children: Array(1), _classes: Set(2), …}
}
```

So, the "commuter" text is being inserted by the browser outside of the `<span>` which wraps a lonely text node (it maps to a `<paragraph>` in the model). Unfortunately, since we map the view `<span>` to model `<paragraph>` in this case, it gives us an insertion position outside of that paragraph and this happily breaks.

I wonder how did it work before the changes that @Mgsy found.

**Comment by Reinmar** [comment]
OK, previously it didn't work either: 

![image](https://user-images.githubusercontent.com/156149/73361290-f4f52e00-42a4-11ea-8fba-37a7176735b4.png)

It didn't crash because of some nice postfixers that we have, but the input command tried to do something incorrect.

**Comment by Reinmar** [comment]
The solution to this is forcing Chrome/Safari to insert this text inside that span. It turned out that changing the `display` to `inline-block` or `block` is enough. I think that none of them should affect how tables are rendered so I'll go with `inline-block` as it should be the safest option.

**Comment by Reinmar** [comment]
From what I can see the above hack fixes https://github.com/ckeditor/ckeditor5/issues/3243 too. It may probably fix some other bugs as well but I couldn't find any matching tickets.
