### ISSUE TITLE
Error in the ckeditor5-image\theme\textalternativeform.css file

### ISSUE THREAD

**Issue by bastien70** [ckeditor/ckeditor5#6063]
Hello, just to show an error in the **textalternativeform.css** file in **ckeditor5-image\theme**

![ckeditor](https://user-images.githubusercontent.com/53140475/72208378-38c4f680-34a2-11ea-8624-b022a153fedc.PNG)
So, impossible to use the file

**Comment by Reinmar** [comment]
Hi! I think you tried to parse this as CSS, but it's PostCSS actually. You need to have a PostCSS loader + our plugins for it defined in your webpack configuration. See [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html).
