### ISSUE TITLE
Nuxt.js custom build throws error (Cannot read property 'getAttribute' of null)

### ISSUE THREAD

**Issue by edgarsn** [ckeditor/ckeditor5#6069]
I'm having problem implementing custom build into nuxt.js. It throws error (see below) in dev tools console and I can't figure out what is wrong with my `nuxt.config.js`. Possibly i'm missing something in `extend` part or I've done it wrong way.

### What I've done so far?

Checked out this solution, but it doesn't work as well: https://github.com/ckeditor/ckeditor5-vue/issues/24#issuecomment-467485099

Read issue #1964 where others have problems with nuxt.js implementation as well.

### Shortcuts to my source code

[nuxt.config.js](https://github.com/edgarsn/nuxt-ckeditor-setup/blob/master/nuxt.config.js)
[build-classic.js](https://github.com/edgarsn/nuxt-ckeditor-setup/blob/master/libraries/ckeditor/build-classic.js)
[index.vue (outputing editor)](https://github.com/edgarsn/nuxt-ckeditor-setup/blob/master/pages/index.vue)

<details><summary>My nuxt.config.js compact/inline version</summary>
<p>

```js
const CKEditorWebpackPlugin = require('@ckeditor/ckeditor5-dev-webpack-plugin');
const {styles} = require('@ckeditor/ckeditor5-dev-utils');

export default {
   /*
    ** Build configuration
    */
    build: {
        /*
        ** You can extend webpack config here
        */
        extend(config, ctx) {
            // exclude ckeditor 5 css from global css rule
            config.module.rules.filter(r => r.test.toString().includes('css')).forEach(rule => {
                rule.exclude = /ckeditor5-[^/\\]+[/\\].+\.css$/;
            });
            // exclude svg files
            config.module.rules.filter(r => r.test.toString().includes('svg')).forEach(rule => {
                rule.test = /\.(png|jpe?g|gif|webp)$/;
            });

            // add new rule for svg files, excluding ckeditor
            config.module.rules.push({
                test: /\.svg$/,
                exclude: function (modulePath) {
                    return /node_modules\/@ckeditor/.test(modulePath);
                },
                use: [
                    {
                        loader: "url-loader",
                        options: {
                            limit: 1000,
                            name: '[path][name].[ext]'
                        }
                    }
                ],
            });

            // add ckeditor 5 loader rules
            config.module.rules.unshift(
                {
                    // Or /ckeditor5-[^/]+\/theme\/icons\/[^/]+\.svg$/ if you want to limit this loader
                    // to CKEditor 5 icons only.
                    test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
                    use: ['raw-loader']
                },
                {
                    // Or /ckeditor5-[^/]+\/theme\/[\w-/]+\.css$/ if you want to limit this loader
                    // to CKEditor 5 theme only.
                    test: /ckeditor5-[^/\\]+[/\\].+\.css$/,
                    use: [
                        {
                            loader: 'style-loader',
                            options: {
                                injectType: 'singletonStyleTag',
                            }
                        },
                        {
                            loader: 'postcss-loader',
                            options: styles.getPostCssConfig({
                                themeImporter: {
                                    themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
                                },
                                minify: true
                            })
                        },
                    ]
                }
            );

            // add ckeditor webpack plugin
            config.plugins.unshift(
                new CKEditorWebpackPlugin({
                    // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
                    language: 'en'
                })
            );
        },
    }
}
```

</p>
</details>

## 📝 Provide detailed reproduction steps (if any)

1. Clone my test repo https://github.com/edgarsn/nuxt-ckeditor-setup
2. `npm install`
3. `npm run dev`

### ✔️ Expected result

It should load ckeditor successfully, without errors.

### ❌ Actual result

It throws theese errors and editor is not loaded.

"plugincollection-load: It was not possible to load the plugin. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-load" (plugin - ContextualBalloon)

"ckeditor.js?3730:5 TypeError: Cannot read property 'getAttribute' of null
    at IconView._updateXMLContent (iconview.js?c77c:122)"

## 📃 Other details

* Browser: Chrome 79
* OS: Windows 10 x64
* CKEditor version: 16.0.0
* Installed CKEditor plugins: See [package.json](https://github.com/edgarsn/nuxt-ckeditor-setup/blob/master/package.json). In few words - default plugins for classic build.

**Comment by Mgsy** [comment]
Hi! We're aware that CKEditor 5 doesn't work well with Nuxt.js. I've created a new [feature request](https://github.com/ckeditor/ckeditor5/issues/6071) for it, so feel free to add 👍 to the first post to bump its popularity. 

Also, you can try to check already reported issues about Nuxt (some of them are in [ckeditor5-vue](https://github.com/ckeditor/ckeditor5-vue) repository), maybe there you'll find something that will help you.

**Comment by umi-soft** [comment]
I am useing vue 2.6.11。
I also have this problem。

**Comment by bunsl** [comment]
I am useing angular 11.0.5
I also have this problem。

**Comment by victororlyk** [comment]
have the same problem with custom build and nuxt
