### ISSUE TITLE
Pass viewElementName to downcastCustomClasses function in the conversion guide

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6077]
## 📝 Provide a description of requested docs changes
In [Adding extra attributes to elements contained in a figure](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html#adding-extra-attributes-to-elements-contained-in-a-figure) section, there is a `downcastCustomClasses()` function which decides if an attribute should be set on `<figure>` element or its child.

```js
function downcastCustomClasses( modelElementName ) {
    return dispatcher => dispatcher.on( `insert:${ modelElementName }`, ( evt, data, conversionApi ) => {
        const modelElement = data.item;

        const viewFigure = conversionApi.mapper.toViewElement( modelElement );

        if ( !viewFigure ) {
            return;
        }

        // The code below assumes that classes are set on the <figure> element...
        conversionApi.writer.addClass( modelElement.getAttribute( 'customClass' ), viewFigure );

        // ... but if you prefer the classes to be passed to the <img> element, find the view element inside the <figure>:
        //
        // const viewElement = findViewChild( viewFigure, viewElementName, conversionApi );
        //
        // conversionApi.writer.addClass( modelElement.getAttribute( 'customClass' ), viewElement );
    } );
}
```

If a user decides to add an attribute to the child element and uncomment the code, it will throw because `viewElementName` is undefined.

I think we should pass `viewElementName` to `downcastCustomClasses()` along with `modelElementName` to avoid this problem.

**Comment by Reinmar** [comment]
I'm not the author of this guide, but I think I understand the their intention. The commented code shows an alternative and executing it requires more changes than just uncommenting it. You also need to comment the line above and add this parameter to this function. IMO, it's hard to make it much clearer without adding one more section. Also, I don't actually like this `findViewElement()`. We should be passing a callback to `downcastCustomClasses()` for reasonable flexibility.

Did you get feedback about this guide which made you report this ticket? That's what I'm actually afraid that someone got confused here. But, frankly speaking, the code here is quite straightforward...

**Comment by Reinmar** [comment]
A viable option would be to have `downcastCustomClasses()` defined twice (under different names, to avoid collision). One implementation would do the basic thing. The other, the "downcast to a specific child element" thing. Then, we would also duplicate:

```plaintext
editor.conversion.for( 'downcast' ).add( downcastAttribute( modelElementName, viewElementName, viewAttribute, modelAttribute ) );
```

And we could comment one of those calls out. Switching between options would be easier then.

**Comment by Reinmar** [comment]
I realised when reviewing this that we have big issues with that guide and it needs a lot more attention :( See https://github.com/ckeditor/ckeditor5/issues/6325.
