### ISSUE TITLE
Toolbar button placement

### ISSUE THREAD

**Issue by Harut101** [ckeditor/ckeditor5#6081]
## 📝 It is not possible to change the position of the toolbar button.

*Right now the toolbar button appears on the left side of the ckeditor, can you please discuss and implement a way to change the position of the button*?

## 📃 Other details

* Browser: any
* OS: any
* CKEditor version: 5
* Installed CKEditor plugins: any

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, can you tell us more about your use case and describe the expected behaviour/configuration?

**Comment by Harut101** [comment]
![paragraph](https://user-images.githubusercontent.com/36543683/72598569-79e95a80-3929-11ea-855a-a98eec4116ea.PNG)

**Comment by Harut101** [comment]
![Screenshot 2019-10-18 at 12 04 28](https://user-images.githubusercontent.com/36543683/72598801-fda34700-3929-11ea-9c99-167fe86f6710.png)
The use case is that it appears under/above an element and so I need a way to configure it to change where it should appear.

**Comment by Mgsy** [comment]
You can configure the position of the block toolbar with CSS. Please, see the [configuration guide](https://ckeditor.com/docs/ckeditor5/latest/features/blocktoolbar.html#configuration).
