### ISSUE TITLE
List item is changed to the paragraph on paste if the selection is on the whole item

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#6085]
![Jan-17-2020 17-03-44](https://user-images.githubusercontent.com/2768047/72626702-6a7b0900-394b-11ea-8210-c01ed7468caa.gif)

**Comment by Mgsy** [comment]
I can't reproduce it. Do I miss something in the scenario?

![bug_cke5](https://user-images.githubusercontent.com/20988892/72726753-75bb7800-3b89-11ea-8c59-e8ba0ae031bd.gif)

**Comment by ma2ciek** [comment]
Hm. I can't reproduce it now. I guess that I was pasting something that the editor couldn't parse and some auto-paragraphing behavior occurred
