### ISSUE TITLE
how to hightlight lateated new text Synchronous with ckeditor 5

### ISSUE THREAD

**Issue by malone081021** [ckeditor/ckeditor5#6086]
I want to hightlight new text Synchronously when user type text. I add plugin, but i do not know , how to select new text , and excute ```execute( 'highlight', { value: 'yellowMarker' })```

**Comment by Mgsy** [comment]
Hi, your description sounds like a case for our [track changes plugin](https://ckeditor.com/collaboration/track-changes/demo/). If it solves your use case, feel free to sign up to the [free trial](https://orders.ckeditor.com/trial/track-changes/). If you'll have any questions, please reach us via our [contact form](https://ckeditor.com/contact/).

**Comment by andybond006** [comment]
We have a custom plugin that doesn't highlight, but rather underlines new text inserted by the user.

We accomplish this by listening for the `input` and setting the selection attribute before the input character is added. As we do not use the highlight plugin, this is untested, but you could look into accomplishing what you are looking for by doing something like the following.

Assuming the editor already has the highlight plugin loaded, the following event handler should apply the highlight attribute to new text that is input by the user:
```
this.listenTo(editor.commands.get('input'), 'execute', () => {
      editor.model.enqueueChange('transparent', writer => writer.setSelectionAttribute('highlight', { value: 'yellowMarker' }));
    }, { priority: 'high' });
```

Alternatively, you may be able to use the highlight command directly and forego the `editor.model.enqueueChange`.

Again, this is untested, and will not handle pasted content. But pasted content can be handled through a similar event handler.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of response of the author.

**Comment by malone081021** [comment]
``` JavaScript 
 editor.listenTo(
        editor.commands.get('input'), 
        'execute', 
      () => {
        this.myEditor.execute( 'highlight', { value: 'yellowMarker' } ); // 1
       // editor.model.change(writer => writer.setSelectionAttribute('highlight', { value: 'yellowMarker' }));
      }, 
      { priority: 'high' }
      );
```
execute `this.myEditor.execute( 'highlight', { value: 'yellowMarker' } ); ` ,lead to typing error

![image](https://user-images.githubusercontent.com/43690259/74096284-d9f1ac00-4b37-11ea-8fde-2fe6ef361986.png)

 but `editor.model.change(writer => writer.setSelectionAttribute('highlight', { value: 'yellowMarker' }));` 
lead to flowing error @andybond006 
![image](https://user-images.githubusercontent.com/43690259/74096228-330d1000-4b37-11ea-8374-50ccf16bf245.png)

**Comment by crest-daksh** [comment]
I want to use the highlight feature of ckEditor5 but without using the plugin , but I can not find any good example to do so . Can please help me how can I do that for particular text . I just want to highlight the particular text . How can I do that ? 

below is the code for ckEditor that I am working on  : 
    
<CKEditor
                editor={ClassicEditor as keyof unknown}
                data={formatToHtml(text)}
                onReady={(editor) => {
                
                  editor.model.document.on("change:data", () => {
                    const text = editor.getData().replace(/<[^>]*>?/gm, ""); // Strip HTML tags
                    const words = text
                      .trim()
                      .split(/\s+/) // Correct regex for splitting on whitespace
                      .filter(Boolean).length;
                    const characters = text.trim().length;
                    setWordCount(words);
                    setCharacterCount(characters);

                    const content = editor.getData();

                    const parser = new DOMParser();
                    const doc = parser.parseFromString(formatToHtml(text), 'text/html');

                    const sections = doc.querySelectorAll('h3');
                    const changes: Record<string, string> = {};

                    sections.forEach((section) => {
                      const sectionTitle = section.textContent?.trim();
                      const nextSibling = section.nextElementSibling;

                      // Capture section's content (e.g., lists under the heading)
                      let sectionContent = "";
                      if (nextSibling) {
                        sectionContent = nextSibling.outerHTML; // Get HTML of sibling element
                      }

                      // Check if the content of this section has changed
                      if (
                        sectionTitle &&
                        previousContent.current[sectionTitle] !== sectionContent
                      ) {
                        changes[sectionTitle] = sectionContent;
                        previousContent.current[sectionTitle] = sectionContent;// Update cached content
                      }
                    });
                 
                  });

                config={{
                  licenseKey: 'GPL',
                  toolbar: [
                    "heading",
                    "bold",
                    "italic",
                    "link",
                    "blockquote",
                    "numberedList",
                    "bulletedList",
                    "indent",
                    "outdent",
                    "undo",
                    "redo",
                    "alignment",
                  ],
                  // plugins: [Timestamp],
                  placeholder: "",
                }}

              />
