### ISSUE TITLE
Can i integrate ckeditor4 's plugin in ckeditor5?

### ISSUE THREAD

**Issue by shavidze** [ckeditor/ckeditor5#6097]
##Integrate ckeditor4's plugin into the ckeditor5.
I was trying to integrate a ckeditor4's slider slideshow in the ckeditor5 but got an error like 'CKEDITOR is not define' in plugin.js file. Can someone help me? Any idea?
_What steps should be taken to fulfill the task?_

* CKEditor version: 5
* Installed CKEditor plugins: slideshow

**Comment by FilipTokarski** [comment]
Hi! 
Thanks for the comment. Unfortunately, it is not possible to use CKEditor4 plugins in CKEditor5. 
CKE4 and CKE5 are different apps, which have different architecture and serve different purposes, therefore [those ecosystems are not fully compatible](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html).
In this case, the solution would probably be [creating your own plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) for CKE5.
