### ISSUE TITLE
Initialize editor with bold/italic ect selected

### ISSUE THREAD

**Issue by olitomas** [ckeditor/ckeditor5#6102]
I searched all over and cant find the answer to this anywhere in the docs or issues. Is there a way to initialize the editor with bold enabled (or any toolbar button for that matter). Or better yet, is there a way to programmatically do it afther the editor has been created ?

**Comment by olitomas** [comment]
I found a way to achieve this by experimenting, but its dirty and I would love if someone could point out a better way 😅

How I am doing this now (I do realize this is NOT a good solution):

`
    ClassicEditor.create(el, {}).then( (editor) => {
        editor.ui.view.toolbar.items._items.forEach((item) => {    
            if(item.label && item.label.toLowerCase() === 'bold') {
                item.isOn = true;
            }
        });
    })
`

**Comment by olitomas** [comment]
Update: This doesn't work. The bold button lights up, but you have to press the button for it to actually activate (i.e when you write)

**Comment by olitomas** [comment]
Update 2: This actually works if I run run .click() on the DOM element. I.e:

```javascript
   ClassicEditor.create(el, {}
        }).then( (editor) => {
            editor.ui.view.toolbar.items._items.forEach((item) => {    
                if(item.label && item.label.toLowerCase() === 'bold'){
                    item.element.click();
                }
            });
        });
```

**Comment by FilipTokarski** [comment]
Hi! 
In CKEditor 5 there is something called [commands](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html) and every command can be invoked with `execute()` method. So the simplest way to activate bold on editor init would be:

```js
const boldCommand = editor.commands.get( 'bold' );

if ( !boldCommand.value ) {
    boldCommand.execute();
}
```
But you have to keep in mind that commands are being 'refreshed' every time you change selection in the editor. So in this case, if you initialize editor with some content, the `bold` will disappear as soon as you click somewhere in the editor. Therefore it makes more sense to initialize it empty.
Hope that helps!
