### ISSUE TITLE
[ckeditor5-inspector] Add history/operations/batch tab

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#6104]
## 📝 Provide a description of the new feature

Display the history stack, and some way to look at batches/operations and have a basic understanding of what they're doing (e.g. `InsertOperation on path [1, 0, 0, 1]`). I know undo/redo is an optional plugin, so I'm not sure if this'd be in-scope for the inspector, but it'd be super helpful for me.

My use cases: 

1. I have a bunch of custom components, and I've noticed some of them seem to be breaking undo/redo functionality. When I insert them via a Command, then try to undo, they aren't removed from the editor. I'm going to have to debug why, and it'd be convenient to have an easier way to explore the history / undo batches than clicking through things in the console. 

2. I'm building some persistent undo/redo functionality, where undo batches and operations are stored to a server and manually loaded back into the editor on pageload. This also has me debugging a bunch of batch/operation stuff manually from the console.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
cc @oleq

**Comment by oleq** [comment]
Hi, @rshipp! 

Thank for your suggestions. That would definitely help a lot of people figure out some operation mess in their projects. I can't give you an ETA because there is plenty of other improvements already on our TODO list but I promise I'll keep it in the back of my head 😀

**Comment by oleq** [comment]
Oh, BTW, since you're here, can I ask you to [skim through existing issues](https://github.com/ckeditor/ckeditor5-inspector/issues) and give 👍where it makes sense for you?

**Comment by oleq** [comment]
Issue moved to [ckeditor/ckeditor5-inspector #70](https://github.com/ckeditor/ckeditor5-inspector/issues/70) via [**ZenHub**](https://www.zenhub.com/)
