### ISSUE TITLE
[Table properties UI] RTL support

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6107]
## 📝 Provide a description of the improvement

A follow-up of ckeditor/ckeditor5#6049.

ATM there's no RTL support in the table (cell) properties UI but there should be (e.g. different order of alignment buttons).

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This is what it looks like:

![image](https://user-images.githubusercontent.com/1099479/74955753-68521180-5405-11ea-92a1-b8f89ff638a0.png)

![image](https://user-images.githubusercontent.com/1099479/74956220-1362cb00-5406-11ea-82da-f05daae54aa3.png)

* Margins and paddings are broken.
* Color picker dropdown displays on the wrong side.
* Color picker border radiuses are broken because the palette button is on the other side.
* Alignment icons are in the wrong order,
* Are the save and cancel icons on the right side of the text?

**Comment by panr** [comment]
I think I fixed all issues except for this:

> Are the save and cancel icons on the right side of the text?
