### ISSUE TITLE
Problems with backwards selection around images

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#611]
I'm not sure if it's an engine or image issue, so posting it here. Browser is Google Chrome 61.

## Case 1

1. In a sample with an image in the content https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html move the caret after the image (`before<image>after[]`).
2. <kbd>Shift</kbd>+<kbd>Arrow up</kbd> to select the content after the image, the image and content before it.

![kapture 2017-10-17 at 12 40 05](https://user-images.githubusercontent.com/1099479/31660988-7e8af92c-b339-11e7-81b3-a34e78153c6d.gif)

**Expected**:

```
[before<image>after]
```

**Actual**: 

The selection collapses to the beginning of editable

```
[]before<image>after
```

**Note**: Forward selection works fine.

## Case 2

1. In a sample with an image in the content https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html move the caret after the image (`before<image>after[]`)
2. Using the mouse (MacBook touchpad in the screencast) select the content after the image, the image and content before it.

![kapture 2017-10-17 at 12 42 02](https://user-images.githubusercontent.com/1099479/31661000-842fd4a6-b339-11e7-95b5-9381fcecfac0.gif)

**Expected**:

```
[before<image>after]
```

**Actual**: 

The image and the content flicker like possessed by a demon.

**Comment by Reinmar** [comment]
@szymonkups is already working on it.

**Comment by oleq** [comment]
That's a great news actually!

**Comment by scofalik** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/1156 ? Further comments concern not only FF.

**Comment by oleq** [comment]
@szymonkups Can you refer to the issue which is supposed to close this one?

**Comment by szymonkups** [comment]
Flickering from **Case 2** should be now fixed by https://github.com/ckeditor/ckeditor5-image/issues/19. But still you'll not able to select the whole content because selection lands in the nested editable, it is reported here: https://github.com/ckeditor/ckeditor5-image/issues/108.

Looks like **Case 1** needs more investigation as it might be a separate issue. I will report it in `ckeditor5-image` repository.
