### ISSUE TITLE
Use the LabeledView instead of LabeledInputView across the project

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6110]
## Provide a description of the task

A follow-up of ckeditor/ckeditor5#6049.

When we first created the latter there were limited use cases and it worked fine. As the new table form arrived I discovered we need to label other (non-input) components like drop–downs as well.

I created the `LabeledView` with some helpers to cover all possible cases (and used in in table (cell) props forms) but I'm not 100% sure about it's interface. Also if we decide to deprecate `LabeledInputView` there will be lots of (simple) changes across the repos (image, link, media).

Things to decide:
* Is the component OK? (API/interface)
* Do we need anything more?
* Should we deprecate `LabeledInputView` now?
  * For how long should it exist in our codebase before we remove it?

**Comment by panr** [comment]
There are two major PRs for the issue:
- **For changing component name** from `LabeledView` to `LabeledFieldView` — https://github.com/ckeditor/ckeditor5-ui/pull/547
  - This one also set `LabeledInputView` as deprecated.
- **For replacing** `LabeledInputView` with `LabeledFieldView` — https://github.com/ckeditor/ckeditor5-theme-lark/pull/274
