### ISSUE TITLE
Implement the table properties UI

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6112]
## 📝 Provide a description of the new feature

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6049.

The table cell properties UI will soon be delivered in https://github.com/ckeditor/ckeditor5-table/pull/227. We need a twin view for table properties with minor changes

![image](https://user-images.githubusercontent.com/1099479/72885550-6f073f00-3d08-11ea-83fb-fd849e7cfff4.png)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by lagnadi** [comment]
How to add an option as a table title ?

**Comment by Witoso** [comment]
@lagnadi if you mean caption, there's [a guide for it in the documentation](https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables-caption.html) but it's not a part of table properties.
