### ISSUE TITLE
Table selection with keyboard

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6115]
## 📝 Provide a description of the new feature

It depends on custom navigation in tables: #3267 and #6113.

Adding keyboard navigation would enable us to use <kbd>shift</kbd> with arrows to extend selection over multiple cells.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This will probably fix #3203 too.
