### ISSUE TITLE
Review behavior of existing features on multi-range selections in tables

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6116]
## 📝 Provide a description of the improvement

Most of the CKEditor 5 features are already implemented with multi-range selection in mind or they operate on multiple nodes by default. However, as we introduce a multi-range selection as a supported solution in the model, we must check how features integrate with such a selection.

Add integration tests for the existing features that will validate that existing CKEditor 5 features works with a selected table fragment (multi-range selection).

Requires #6113.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
May be blocked by https://github.com/ckeditor/ckeditor5/issues/6328.

**Comment by oleq** [comment]
Features broken so far when executed on a multi-cell selection:
* horizontal line
* page break
* special characters
