### ISSUE TITLE
Cut / delete on selected table fragment

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6119]
## 📝 Provide a description of the new feature

Similarly to #6118, table selection should handle:

- the cut shortcut (<kbd>CTRL</kbd>+<kbd>X</kbd>)
- <kbd>Delete</kbd> or <kbd>Backspace</kbd>

as clearing the content of selected table cells.

Additionally, the cut shortcut should copy the contents to the clipboard. Requires only #6113 as either task (this or #6118) can handle this part (this requirement might be moved to a follow-up issue if #6118 is still open).

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Currrent behviour:


![2020-02-20 17 09 07](https://user-images.githubusercontent.com/1099479/74954685-c8e04f00-5403-11ea-8008-56bd13534cfd.gif)
