### ISSUE TITLE
Maximum connection requests 

### ISSUE THREAD

**Issue by Prasad-YS** [ckeditor/ckeditor5#6134]
What are maximum concurrent connection request IE11 supports,
Somewhere I read it as 8 and some blogs says 13, I'm unable to get any  docs on this.

**Comment by mlewand** [comment]
IE11 is not officially supported for CKEditor 5.

Also I don't know what kind of concurrent connections are you asking for. Editor can be displayed in as many concurrent as your HTTP server can handle. Maybe you wanted to ask for max [Collaboration](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration.html) users count? In that case we don't have any particular limit of concurrent users.
