### ISSUE TITLE
Change attribute on editingDowncast

### ISSUE THREAD

**Issue by shavidze** [ckeditor/ckeditor5#6135]
How could i change img attribute on editinigDowncast ? here is my code

    conversion.for("editingDowncast").elementToElement({
      model: "sliderItemImage",
      view: (modelElement, viewWriter) => {
        console.log("model element", modelElement._attrs.get("src"));
        console.log("viewwriter", viewWriter);
        const img = viewWriter.createAttributeElement("img", {
          attributes: {
            src: modelElement._attrs.get("src")
          }
        });
        return toWidget(img, viewWriter);
      }
    });

**Comment by shavidze** [comment]
I added attributeToAttribute conversation and that's all.

  // Then the conversion might be a two way attribute-to-attribute:
    conversion.attributeToAttribute({
      model: "src",
      view: "src"
    });

    conversion.for("editingDowncast").elementToElement({
      model: "sliderItemImage",
      view: (modelElement, viewWriter) => {
        const img = viewWriter.createAttributeElement("img", {
          attributes: {
            src: modelElement._attrs.get("src") // here updated src value
          }
        });
        return toWidget(img, viewWriter);
      }
    });
  }

**Comment by Reinmar** [comment]
Yup, that's the correct solution. I'd recommend using a more unique attribute name, though. Or a more precise `model` pattern (something like `model: { name: 'sliderItemImage', key: 'src' }` if I remember correctly) which will ensure that your feature will not conflict with other features which use the `src` attribute.

**Comment by shavidze** [comment]
> Yup, that's the correct solution. I'd recommend using a more unique attribute name, though. Or a more precise `model` pattern (something like `model: { name: 'sliderItemImage', key: 'src' }` if I remember correctly) which will ensure that your feature will not conflict with other features which use the `src` attribute.

I tried but it seems that it doesn't work.
