### ISSUE TITLE
Useless tests in ckeditor5-core

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6138]
## 📝 Provide detailed reproduction steps (if any)

This test: https://github.com/ckeditor/ckeditor5-core/blob/8a88cb52c122fd2952f88f8773a03808f32d6037/tests/editor/editor.js#L353-L366

```js
it( 'should wait for the full init before destroying', done => {
	const spy = sinon.spy();
	const editor = new TestEditor();

	editor.on( 'destroy', () => {
		done();
	} );

	editor.destroy();

	sinon.assert.notCalled( spy );

	editor.fire( 'ready' );
} );
```
does not test anything

### ✔️ Expected result

The test shold test something.

### ❌ Actual result

:thinking: 

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Yeah, the intention was probably that the spy is called in the listener.
