### ISSUE TITLE
Toolbar wrapping - No documentation with information found?

### ISSUE THREAD

**Issue by thorleifjaocbsen** [ckeditor/ckeditor5#6143]
I've asked on StackOverflow but seems like nobody is doing this.

https://stackoverflow.com/questions/59842067/ckeditor-5-vuejs-toolbar-not-wrapped-when-text-field-is-smaller-than-width-o

I could not find any documentation on how to enable wrapping of the toolbar or atleast just have it hide the buttons that overflow instead of all? 

My question is:

1. How to make so it only hides the buttons that is overflowing, still show the most left ones.
2. How to make it multiline, so it just wraps down instead?

**Comment by thorleifjaocbsen** [comment]
Answering my own second question:

shouldNotGroupWhenFull: true in the "toolbar" config will not group them all. But wrap around. Now for my first question! This was btw documentet correctly, just my bad not looking too good at the properties docs for "toolbar": https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html

**Comment by Reinmar** [comment]
As I commented under your SO post – the thing that you're showing on the screenshot is a bug. Not sure on what side (CKE5's or yours). It shouldn't look like this – only buttons which don't fit in the toolbar width should be wrapped. If you can prepare a simplified demo on which this happens, please open a new bug report.

**Comment by Reinmar** [comment]
> 1.  How to make so it only hides the buttons that is overflowing, still show the most left ones.

That's what should happen. It does not, so see my previous comment.

> 2\. How to make it multiline, so it just wraps down instead?

That's not possible yet (no JS option for that). It can certainly be achieved with changing the styling of the toolbar but I'm not sure we're much interested in this as we do all we can to avoid having such toolbars again.

**Comment by Reinmar** [comment]
> 1.  How to make so it only hides the buttons that is overflowing, still show the most left ones.

That's what should happen. It does not, so see my previous comment.

> 2\. How to make it multiline, so it just wraps down instead?

That's not possible yet (no JS option for that). It can certainly be achieved with changing the styling of the toolbar but I'm not sure we're much interested in this as we do all we can to avoid having such toolbars again.

**Comment by thorleifjaocbsen** [comment]
Hi Reinmar, 2. as I answered my self it is possible. I just added "shouldNotGroupWhenFull" as i explained above and it wrapped instead of grouping. 

I unfortunally dont have much time to explore more, so I just maed it so it did not group and are happy.  I'm using the ckeditor5 vue plugin so might be something in that who "f*" it up :)

**Comment by tungpt9x2** [comment]
just add this config for toolbar
toolbar: {
        shouldNotGroupWhenFull: true
    }
