### ISSUE TITLE
Make the getResizeObserver re-use a single observer instance for performance reasons

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6145]
## Provide a description of the task

We used to have just one observer use–case for toolbar grouping. Now there's a [new one for balloon toolbars]( https://github.com/ckeditor/ckeditor5-ui/pull/536/files) and another one [for the inline toolbar](https://github.com/ckeditor/ckeditor5-editor-inline/pull/65). 

I figured this should be a performance issue, [and it is](https://github.com/WICG/ResizeObserver/issues/59#issuecomment-408098151). There should be a single instance used on a web page because otherwise the [performance loss is huge](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/z6ienONUb5A/F5-VcUZtBAAJ).

**Comment by Reinmar** [comment]
WUT, this is weird. How can we ensure that there's a single instance on the entire page? We don't control the whole page obviously. What if someone added more observers?

**Comment by oleq** [comment]
At least we can make sure there's only one observer added by CKEditor features and this is what my PR does.
