### ISSUE TITLE
Ckeditor 5 is not rendered the view 

### ISSUE THREAD

**Issue by lingamwin** [ckeditor/ckeditor5#6156]
I just tried with adding sample svg content like '<svg width='100' height='100'><circle cx='50' cy='50' r='40' stroke='black' stroke-width='3' fill='red' /></svg>'

the elements are append after register in schema,  

When i look the ckeditor inspector view tab, the svg elements are add, but not visible in page

![render issue](https://user-images.githubusercontent.com/34454721/73332916-3c23f480-428e-11ea-991a-1440e113b4de.PNG)

Please provide any solution on this

**Comment by Reinmar** [comment]
I replied to your more generic ticket about how to approach this in https://github.com/ckeditor/ckeditor5/issues/6155.

In case of this bug, I think what you miss is a `xmlns` attribute on this `<svg>` element. We actually had a bug in the past that we ignored it but I can see this test right now in our test suite:

```js
		it( 'should create namespaced elements', () => {
			const namespace = 'http://www.w3.org/2000/svg';
			const viewSvg = new ViewElement( 'svg', { xmlns: namespace } );

			const domSvg = converter.viewToDom( viewSvg, document );

			expect( domSvg.createSVGRect ).to.be.a( 'function' );
		} );
```

Which means that everything works fine. Please add `{ xmlns: http://www.w3.org/2000/svg }` to the `createContainerElement()` that's creating this `<svg>` element and it should appear.

If it still won't display correctly, please show us a screenshot of the editor's DOM (you can inspect it via the browser's dev tools).

**Comment by lingamwin** [comment]
@Reinmar Got it. Thank you so much.
