### ISSUE TITLE
Emoji category in special characters is not discoverable

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6162]
## 📝 Provide detailed reproduction steps (if any)

Now that all category went to a first place (#6157) the emoji category is no longer visible in the sample's dropdown without scrolling - that hits the discoverability. This is even a bigger problem on Apple OSes, where the scrollbar is not visible by default.

### ✔️ Expected result

The Emoji category should be visible without scrolling.

IMO we should change the default max-height to allow it containing one item more by default. I see a benefit in this solution that if someone adds an extra category she or he will not face this problem.

### ❌ Actual result

The Emoji category is not visible at first.

![](https://user-images.githubusercontent.com/5353898/73431215-2e2eac00-4340-11ea-8706-fef1e7b4b4ff.png)

![](https://user-images.githubusercontent.com/5353898/73431219-30910600-4340-11ea-954b-c0c061ade136.png)

## 📃 Other details

*   CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
For me, on i/5985 it renders at the very beginning.

![image](https://user-images.githubusercontent.com/156149/73438587-91273f80-434e-11ea-889b-2caa5067daaa.png)

Could you recheck this?

**Comment by mlewand** [comment]
I can confirm that on mentioned branch, the Emoji category goes to the first position - in which case this issue will no longer be an issue after merging ckeditor5-special-characters#12.
