### ISSUE TITLE
Rename text value of font sizes

### ISSUE THREAD

**Issue by ayaniv** [ckeditor/ckeditor5#6163]
The text that can be shown in font size drop down list is rather a string value or numeric value.
Strings are: ['tiny', 'small', 'default', 'big', 'huge']

My feature request is to allow me rephrasing the text value of each option, so i can call it whatever i want, but in the background it will still use the same values.
So basically, I would like you to make the array accepts key-value objects.
Example:
```
[
{key: 'default', value: 'normal'},
{key: 'big', value: 'large'}
]
```

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi! It looks like those ideas have already been discussed here: https://github.com/ckeditor/ckeditor5/issues/2295
