### ISSUE TITLE
CKEditor Supressing MouseDown Action Performed Inside React Component Block Widget

### ISSUE THREAD

**Issue by abhisheksirari** [ckeditor/ckeditor5#6164]
## 📝 Provide detailed reproduction steps (if any)

I implemented a React Component inside a block widget in the editor. I used the following demo example as reference : 

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/using-react-in-a-widget.html#demo

I had bind a mousedown event to an element inside the React Component. However, the event didn't get executed on performing the mousedown action. 

I debugged the CKEditor code a bit and found that __onMousedown_ method inside _widget.js_ had a line - [_domEventData.preventDefault();_](https://github.com/ckeditor/ckeditor5-widget/blob/81bb636040afab8dea0a06655e1028f239d5790c/src/widget.js#L145), which was causing this behavior.

### ✔️ Expected result

CKEditor should not ideally be supressing with the events fired from inside the React Component Block Widget.

## 📃 Other details

* Browser: Firefox
* OS: Windows 10
* CKEditor version: Latest Master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This issue has the same root cause as https://github.com/ckeditor/ckeditor5/issues/4465 and it's also related to https://github.com/ckeditor/ckeditor5/issues/2743. Please subscribe to #4465 for further notifications.
