### ISSUE TITLE
Toolbar icons showing very small after replacing with NormalModuleReplacementPlugin in react

### ISSUE THREAD

**Issue by abhijitkc** [ckeditor/ckeditor5#6166]
I have replaced the toolbar icon for bold with NormalModuleReplacementPlugin in react js in webpack.config.js file but icon looking very small and not similar to existing.

 I have replaced icons with 
`new webpack.NormalModuleReplacementPlugin( /bold\.svg/, path.resolve( __dirname, './assets/bold.svg' ) )`
in the webpack.config.js file. Also I am attaching the images for the help

See the bold image 

![toolbar](https://user-images.githubusercontent.com/36158867/73463255-f573ee80-43a2-11ea-9498-7631503415b3.png)

svg image screenshot for bold icon

![svg image](https://user-images.githubusercontent.com/36158867/73463466-4b489680-43a3-11ea-9789-17d96be4f7ec.png)

Also the code for svg is 

`<svg class="ck ck-icon ck-button__icon" viewBox="0 0 30 30">
    
    <title>B</title>
    <desc>Created with Sketch.</desc>
    <g id="13" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="3_8-1280x720" transform="translate(-281.000000, -210.000000)">
            <g id="Format" transform="translate(35.000000, 210.000000)">
                <g id="letters" transform="translate(212.000000, 0.000000)">
                    <g id="B" transform="translate(34.000000, 0.000000)">
                        <rect id="Rectangle-Copy-6" stroke="#D9DCEF" fill="#E5E7F3" x="0.5" y="0.5" width="29" height="29" rx="5"></rect>
                        <path d="M19.9997756,12.6562319 C19.9974794,10.6378789 18.3199292,9.00223889 16.2498598,9 L10.8333146,9 C10.3730877,9 10,9.36376684 10,9.81249598 L10,21.1874397 C10,21.6361688 10.3730877,21.999968 10.8333146,21.999968 L16.2498598,21.999968 C17.843442,22.0064566 19.2656706,21.0262368 19.7910266,19.559314 C20.3163827,18.0923912 19.8290875,16.4620477 18.5777242,15.4999678 C19.4720297,14.8133458 19.9957321,13.766076 19.9997756,12.6562319 L19.9997756,12.6562319 Z M18.3331464,18.3437037 C18.3320897,19.4650996 17.3999892,20.3739134 16.2498598,20.3749437 L11.6666293,20.3749437 L11.6666293,16.3124638 L16.2498598,16.3124638 C17.3999892,16.3134941 18.3320897,17.2223079 18.3331464,18.3437037 Z M11.6666293,14.6874718 L11.6666293,10.624992 L16.2498598,10.624992 C17.4004272,10.624992 18.3331464,11.5344091 18.3331464,12.6562319 C18.3331464,13.7780547 17.4004272,14.6874718 16.2498598,14.6874718 L11.6666293,14.6874718 Z" id="Shape" fill="#A8ADCB" fill-rule="nonzero"></path>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>`

**Comment by Reinmar** [comment]
Sorry to hear that. But it doesn't seem to be related to CKEditor 5. CKEditor 5 doesn't do anything special with those icons – we just use them. If your icon renders incorrectly, then it means that probably something's wrong with it.

You may try to start with one of the default CKE5 icons and try to modify it to see when it breaks.
