### ISSUE TITLE
Why not having all arrows in the special chars arrows section

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6167]
So, we do have an example in the docs how to add additional arrows:

https://github.com/ckeditor/ckeditor5-special-characters/blob/master/docs/features/special-characters.md#adding-characters-to-an-existing-category

But why don't we actually add those pretty default arrows to the default arrows preset?

Also, when we do that, we need to figure out some new example.

cc @pomek @oleq 

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Yeah, what we have in "Arrows" category at this moment is a very limited set and it doesn't even have the most common arrows.

![image](https://user-images.githubusercontent.com/1099479/73647447-c5b33800-467b-11ea-9a46-6fbeb3baeb33.png)

So this is how I see this:
1. Let's make sure all common arrows are in the category (compare with popular word processors so users feel familiar with our choices).
2. Let's use something else in the guide. I think adding greek letters (α, β, Δ) to the mathematical category would be fine.
3. Let's review other categories for similar mistakes.

**Comment by DawidKossowski** [comment]
Generally, there are a lot of categories in special characters which are not included by default (comparing with most popular editors). However, most of them are very specific, like Braille or Musical, and shouldn't be as default in the CKEditor. But, in my opinion, there is at least one category which could be very useful:  **Emoji** and could be added as a separate plugin.  
  
During this issue I will add all common arrows to the category and update the user guide.
