### ISSUE TITLE
The image and media embed icons are not aligned identically

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6168]
Not sure how's this possible but ME is 0.5px higher which renders on my non-retina screen as a blur:

![image](https://user-images.githubusercontent.com/156149/73470317-fcd9ce80-4387-11ea-9657-d81b2bb90ce1.png)

cc @oleq @panr 

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by panr** [comment]
I fixed these icons in related PRs ☝🏻

**Comment by panr** [comment]
@Reinmar @oleq new plan... I'll fix only `image` and `media embed` alignment and close other PRs. I'll leave the rest for future sync with @dkonopka and @oleq to discuss the icons requirements. 

WDYT?

**Comment by panr** [comment]
I only fixed vertical alignment for `media-embed` icon https://github.com/ckeditor/ckeditor5-media-embed/pull/95#issuecomment-589080227
