### ISSUE TITLE
Improve the special chars icon

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6169]
## 📝 Provide a description of the improvement

![image](https://user-images.githubusercontent.com/156149/73470086-a66c9000-4387-11ea-9192-5f1309bf7e3f.png)

I think that this icon is a bit too big and slightly misaligned (although, I'm not actually sure in which direction :D).

BTW, I also found out that the media embed and image icons are not aligned to each other: https://github.com/ckeditor/ckeditor5/issues/6168.

cc @oleq @panr

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Yes, it was the "development icon" and it somehow stayed and I forgot to create a followup. I totally agree it should be improved.

**Comment by panr** [comment]
I made few PRs fixing sizes and optical alignment of some icons.
