### ISSUE TITLE
Block autoformat could work in all kind of blocks

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6170]
## 📝 Provide a description of the improvement

So, right now when you're in at the beginning of a heading 2 and type `###` it is not going to change it to a heading 3. It's only possible to turn a paragraph into other types of blocks.

This means that you can't easily toggle between block types. Also, if you made a mistake, you need to get back to a paragraph (e.g. by undoing) and only then you can use autoformatting.

One example of an application where you can always switch between block types is Notion and I use this quite a lot. Especially when I'm changing heading levels (cause I'm reorganizing a document).

Another aspect is that currently you can only apply autoformatting to an **empty block**. We'd also like to apply formatting for blocks that have some content in it, as long as your cursor is at the beginning of the line.

Related issue:

*   [It should be possible to convert a heading into a list item and vice versa](https://github.com/ckeditor/ckeditor5/issues/2368)

cc @jodator @panr @oleq

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
> One example of an application where you can always switch between block types is Notion and I use this quite a lot. Especially when I'm changing heading levels (cause I'm reorganizing a document).

After using this app for some time I feel that this is the expected way of doing things. IIRC I just used this app this way (might be a hint from a tutorial). It feels natural. Even so, then when testing our implementation of block autoformat it felt weird in that regard.

ps.: This change shouldn't be a time consuming one.

**Comment by ma2ciek** [comment]
Note also that Notion allows you to remove the current formatting by typing backspace at the beginning of the line, which I also find intuitive. In the CKEditor 5 you're deleting the whole heading / blockquote. Though, this might be releated to how our features are implemented.

Also, all block auto formatting should work with some text present in the line already - I can't find the proper ticket about this issue.

**Comment by Reinmar** [comment]
> Note also that Notion allows you to remove the current formatting by typing backspace at the beginning of the line, which I also find intuitive. In the CKEditor 5 you're deleting the whole line in case of heading / blockquote. Though, this might be releated to how our features are implemented.

I like this behaviour of Notion but it works there because each block is a separate entity. In our cases it would be less intuitive.

But the thing that I miss and we could definitely have is that pressing backspace in the first line of the editor should reset the format to paragraph.

**Comment by Reinmar** [comment]
We did a quick review of the block autoformat code and there are a couple of things that might be worth at least considering when working on this:

* Reading model element names from the schema.
* Naming.
* isTyping.
* Not limitting this to paragraph with just one child (e.g. inline widgets, soft breaks, etc.).

**Comment by Reinmar** [comment]
One thing I noticed in Notion is that \`1. \` will work in a paragraph but not in a heading. While \`# \` will work everywhere. That even makes some sense, so we should be careful to not "overdo" here.

**Comment by mlewand** [comment]
We need more elaboration on that:

> *   Reading model element names from the schema.
> *   Naming.
> *   isTyping.

Related issue:

*   [It should be possible to convert a heading into a list item and vice versa](https://github.com/ckeditor/ckeditor5/issues/2368)

**Comment by Reinmar** [comment]
> *   Reading model element names from the schema.

It's about https://github.com/ckeditor/ckeditor5/blob/b80c677/packages/ckeditor5-autoformat/src/autoformat.js#L120-L139. It'd be cleaner if we read the `heading*` element names from the schema. But it's a completely minor issue.

> Naming

It's most likely about https://github.com/ckeditor/ckeditor5/blob/b80c677/packages/ckeditor5-autoformat/src/autoformat.js#L126. It's not a command value. Since we planned to review this code, it might be a good moment to clean up such issues. But it's again a minor issue.

> isTyping

It's about using the `isInput` property (it was renamed from isTyping -> isInput) to check whether a current change should be treated as typing. That property was added quite recently so the autoformat feature which was implemented very early is using some other heuristic (probably, worse).

**Comment by mlewand** [comment]
We had a quick discussion regarding these changes today, and we made several minor adjustments.

> One thing I noticed in Notion is that \`1. \` will work in a paragraph but not in a heading. While \`# \` will work everywhere. That even makes some sense, so we should be careful to not "overdo" here.

Wile mentioned Notion doesn't allow turning a list to a header, we decided to simplify things and not impose such limitations for now. Which means there is not going to be any map telling what block can be turned into what.

While doing this issue we could also do some refactoring here and there (e.g. #7366, there are also some misused variable names in the code).

However for now the refactoring should be limited, so we're not going to utilize text watcher / perform a full rewrite.

**Comment by Reinmar** [comment]
I noticed that you can't turn a heading into a list by typing \`1. \`. You can, however, by typung \`\* \`. That makes a lot of sense. I was just trying to number the headings (as steps) and I was positively surprised that Notion devs predicted this case. It makes a lot of sense to me.
