### ISSUE TITLE
Question on how to simplify the View Structure

### ISSUE THREAD

**Issue by appreciated** [ckeditor/ckeditor5#6171]
I am currently working on a custom build similar to the classic but with some adjustments for my project. This is an awesome project by the way.

I am currently struggling with the somehow built in Downcast order, This caues the view structure to be sometimes very clean, and sometimes unnecessary complicated. 

Assuming I have the following model:
![grafik](https://user-images.githubusercontent.com/1729845/73484927-7979a680-43a2-11ea-8021-ed742fb54c3c.png)

And the following View:
![grafik](https://user-images.githubusercontent.com/1729845/73484882-6666d680-43a2-11ea-8d8f-8e0b48dd29b6.png)

I am using for both "attributes" (type1 and type2) the same following code for up and downcasting. 
```
editor.model.schema.extend('$text', {allowAttributes: "type1"});
editor.conversion.for('downcast').attributeToElement({
	model: annotationConfig.name,
	view: (attributeValue, writer) => {
		return writer.createAttributeElement("type1");
	},
	converterPriority: 'low',
});
editor.conversion.for('upcast').attributeToAttribute({
	view: {
		name: "type1"
	},
	model: "type1",
	converterPriority: 'low'
});
editor.commands.add(annotationConfig.name, new AttributeCommand(editor, "type1"));
```

When swapping the attributes, the view is much cleaner, like this:
![grafik](https://user-images.githubusercontent.com/1729845/73485064-bfcf0580-43a2-11ea-83d6-de5400baff76.png)

Is there a way to manipulate the view while or after the downcasting to archive the same results as above with both models at the same time? 

I would be glad for any help 🙂.

**Comment by jodator** [comment]
This is controlled by a [priority attribute of the `AttributeElement`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_attributeelement-AttributeElement.html#member-priority). This can be passed as the third parameter of the [`attributeToElement()` downcast helper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-attributeToAttribute). The lower the `priority` the outer-most the view element will be.

The `converterPriority` controls when this particular callback will be called (after - 'low' or before - 'high' other converters). This is useful for overriding or enhancing other features converters (like the one provided by the editor).

Example in our code for restricted editing standard mode feature: https://github.com/ckeditor/ckeditor5-restricted-editing/blob/5f9514eb9daeacab82ca43d29249c9d760c504f9/src/standardeditingmodeediting.js#L46-L54

**Comment by jodator** [comment]
ps.: I'm closing this issue just to keep open issues low.

If you have any additional questions you can ask them here.

**Comment by appreciated** [comment]
@jodator First of all thank you very much for your answer!

> The converterPriority controls when this particular callback will be called (after - 'low' or before - 'high' other converters). This is useful for overriding or enhancing other features converters (like the one provided by the editor).
>Example in our code for restricted editing standard mode feature: https://github.com/ckeditor/ckeditor5-restricted-editing/blob/5f9514eb9daeacab82ca43d29249c9d760c504f9/src/standardeditingmodeediting.js#L46-L54

This worked beautifully!

There is still one missing piece on how to make this truly dynamic. 
> to archive the same results as above with both models at the same time

I'm missing information during the downcast:
* What is the position of the attribute in the model (that is currently downcasted to the view) 

The "only" information I currently have is `(attributeValue, DowncastWriter). 
I tried checking the `DowncastWriter` but nothing seemed promising to my requirements. 

Have you got some more hints for me 🙂?

**Comment by jodator** [comment]
> What is the position of the attribute in the model (that is currently downcasted to the view)

Unfortunately, I don't recall any easy way to do this. The 'dynamic' part of your requirement might be dropped as the users should not perceive this (in most cases) and probably one of the attributes might be required to be always the outer-most.

However, as I don't know your case and I might be wrong ;) You _could_ try to implement the very low-level converter for the attribute. But this task would require you to dive into the downcast converter helpers and basically copy the code to your own listener:

```js
conversion.for( 'downcast' ).add( dispatcher.on( 'attribute:type2', ( evt, data, conversionApi ) => {
    // Here you would have more information available, like:
    // data.item - the model item on which the attribute is set

} );
```

You can read more about this:
- [conversion deep dive guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html)
- [example of enhancing existing attribute conveter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html#adding-a-css-class-to-inline-elements) (usage of `attribute` dispatcher event)
- [source code of the attributeToElement](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/conversion/downcasthelpers.js#L1096-L1119) downcast conversion helpers
- [downcast conversion API](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastConversionApi.html)

**Comment by appreciated** [comment]
I think I managed to do it, still got some issues left, but I guess nothing I cannot solve on my own.

For those having similar issues / requirements you can use the following as a starting point. 
```
editor.conversion.for('downcast').add(dispatcher => {
	dispatcher.on('attribute:' + annotationConfig.name, (evt, data, conversionApi) => {
		const viewWriter = conversionApi.writer;
		const viewSelection = viewWriter.document.selection;
		var oldViewElement = viewWriter.createAttributeElement(annotationConfig.name);
		if (!conversionApi.consumable.consume(data.item, evt.name)) {
			return;
		}
		if (data.item instanceof ModelSelection || data.item instanceof DocumentSelection) {
			viewWriter.wrap(viewSelection.getFirstRange(), oldViewElement);
		} else {
			// Node attribute conversion.
			let viewRange = conversionApi.mapper.toViewRange(data.range);
			// First, unwrap the range from current wrapper.
			if (data.attributeOldValue !== null && oldViewElement) {
				viewRange = viewWriter.unwrap(viewRange, oldViewElement);
			}
			if (data.attributeNewValue !== null && oldViewElement) {
				viewWriter.wrap(viewRange, oldViewElement);
			}
		}
	});
});
```

**Comment by appreciated** [comment]
@jodator Sorry to bother you again, I replaced the thing with the dispatcher above, but now I have a really weird behaviour. When I put the cursor at a specific position in the text.
`<type1>test<type2>te[ ]st</type2>test</type1>`

The view will split the whole into two pieces.
`<type1>test<type2>te</type2></type1>[ ]<type1><type2>st</type2>test</type1>`

Why does putting the cursor into that postion, changes the view anyways? 
I can assure that this did not happen before.

**Comment by jodator** [comment]
> Why does putting the cursor into that postion, changes the view anyways?

Probably it is due to the `selection` attributes. If you set selection attributes it will be rendered as an empty view element. Below is a similar situation for bold attribute:

![Peek 2020-01-31 15-53](https://user-images.githubusercontent.com/247363/73548884-d9735a00-4441-11ea-9ae0-cb913ef56cac.gif)

This happens only when editing to allow typing with selection attributes. If you use `editor.getData()` the returned editor content will be as you expect without an empty element. Why this happens in your case I cannot tell without a whole code _but_ if the `editor.getData()` is correct and this situation happens only when typing I wouldn't worry much.

**Comment by jodator** [comment]
ps.: check also solution with different priorities:

```js
editor.conversion.for('downcast').attributeToElement({
	model: annotationConfig.name,
	view: (attributeValue, writer) => {
		return writer.createAttributeElement("type1", {}, { priority: 20 } );
	},
	converterPriority: 'low',
});

editor.conversion.for('downcast').attributeToElement({
	model: annotationConfig.name,
	view: (attributeValue, writer) => {
		return writer.createAttributeElement("type2", {}, { priority: 10 } ); 
	},
	converterPriority: 'low',
});
```

ps.: For priorities IIRC the 'normal' is 10 or 20 (default) if you'd like to have the most outer-most element use `1` or something below `0` (like `-10`) but don't use `0` as it might be interpreted as "unset" value (kinda bug - should be reported somewhere).

**Comment by appreciated** [comment]
> ps.: For priorities IIRC the 'normal' is 10 or 20 (default) if you'd like to have the most outer-most element use 1 or something below 0 (like -10) but don't use 0 as it might be interpreted as "unset" value (kinda bug - should be reported somewhere).

The problem is, that this solution is constant. I need to be able to decide depending on the current state model whether an attribute should be wrapped or inserted. So what I need are kinda dynamic converterPriorities. Or some kind of view normalization, after downcasting.

**Comment by appreciated** [comment]
@jodator I now also tried to rearrange some attributes using the Postfixer with no success, changes are for some reason reverted right away.

```
editor.editing.view.document.registerPostFixer(writer => {
	if (writer.document.getRoot().getChild(0).getChild(0)) {
		console.log(writer.document.getRoot().getChild(0).getChild(0));
		if (!writer.document.getRoot().getChild(0).getChild(0).name) {
			writer.wrap(writer.createRangeIn(writer.document.getRoot().getChild(0).getChild(0)), writer.createAttributeElement("type1"));
			writer.wrap(writer.createRangeIn(writer.document.getRoot().getChild(0).getChild(0)), writer.createAttributeElement("type2"));
		}
		return false;
	}
	return false;
});
```

**Comment by appreciated** [comment]
I was also thinking about overriding the DomConverter or the Renderer. Can it actually be done in a supported way?
