### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by arvindmittal** [ckeditor/ckeditor5#6173]
![image](https://user-images.githubusercontent.com/60504052/73528582-27d12a80-443b-11ea-869e-7bb0c4840c3f.png)

**Comment by FilipTokarski** [comment]
Hi! Thanks for the report. In order to reproduce this error and find solution I need more information. Could you explain what are you trying to achieve and provide detailed steps for this?

**Comment by arvindmittal** [comment]
Hi, this is as mentioned here:
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html

stuck here:
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html#rebuilding-the-bundle

**Comment by FilipTokarski** [comment]
Did you try `npm run build` instead of `yarn run build`?

**Comment by arvindmittal** [comment]
great!
both i tried now and all done!
thanks!
