### ISSUE TITLE
Table alignment property is not working properly

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6179]
## 📝 Provide detailed reproduction steps (if any)

Try to align the table on the latest master using table properties view.

### ✔️ Expected result

- the table is visually set either to right or left or centered

### ❌ Actual result

- table cells contents are aligned left/right

## 📃 Other details

There are a few problems:

1. The `alignment` attribute on `Table` is picked up by `Alignment` plugin converters (:bug:)
2. The downcast conversion of the alignment to style does not work with the editing styles (💅):
    - it could be set on the `<figure>` not on `<table>` (as now)
    - the `<table>` styles in the editing area could have less enforcing rules and could allow proposed inline styles.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Also @oleq's insights on this in the PR: https://github.com/ckeditor/ckeditor5-table/pull/232#discussion_r373444290.

**Comment by Reinmar** [comment]
There are cases like lists, where we use `listIndent`, `listType` because a list item can be semantically renamed into a paragraph or a heading.

However, there are also cases like images, medias, tables, where such an item cannot be renamed. Those features are objects and their attributes will never end up on a different element.

Therefore, IMO, here we have a bug in the alignment package.

**Comment by jodator** [comment]
> Therefore, IMO, here we have a bug in the alignment package

Nope :) I've didn't test this feature manually because of no UI (which is fine). Also, this tickets prooves that we're able to iterate fast and find the bugs earlier and that this doesn't hurt us so much :)

The problem here was with priorities - if both converters have the same priority then the one added to the build earlier will win (or should win). Here, increasing the table's `alignment` priority helps - the other solution would be to change the attribute name.

What was caught here also is a lack of `consuming` in low-level attribute converter (using `conversion.for().add()`).

**Comment by jodator** [comment]
The "where to" convert is extracted to: #6197 as it needs some decisions.

**Comment by zero-8** [comment]
same problem , i am using it in nuxt the image can only be in center and right, cannot align it to the left.

ive used this for nuxt integration using 

https://blowstack.com/blog/frameworks/create-ckeditor-5-custom-build

for developers who are experiencing the same problem

**Comment by DeltekDavid** [comment]
Hello from 2024 :) Experienced this today using the nightly build. I can align the table center or right. Left-align does nothing. Tried both in code with defaultProperties and using the contextual Table Properties button.
