### ISSUE TITLE
Clicking "Cancel" in a table props form of a newly created table deletes it

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6180]
## 📝 Provide detailed reproduction steps (if any)

1. Insert a table
2. Open table properties
3. Click the cancel button

### ✔️ Expected result

The form is closed.

### ❌ Actual result

The table disappears.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
What we need [here](https://github.com/ckeditor/ckeditor5-table/blob/ec22240d8a04d7dfe386773ef6fca58d940b2d67/src/tableproperties/tablepropertiesui.js#L126) is `if ( this._undoStepBatch.operations.length )`.

**Comment by oleq** [comment]
TBH it's quite confusing

> [A batch that should be undone. If not set, the last added batch will be undone.](https://ckeditor.com/docs/ckeditor5/latest/api/module_undo_undocommand-UndoCommand.html#function-execute)

I thought that if a batch is passed, the command works exclusively on that batch.
