### ISSUE TITLE
Specify / add info about units in table properties

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6184]
## 📝 Provide a description of the improvement

Currently if you go to the [test](http://localhost:8125/ckeditor5-table/tests/manual/tableproperties.html) and open table properties/cell properties balloon there are many input fields in which you can type some values - but it is not specified what units to use. From UX point of view, it might be helpful for some less experienced users to add an information, that they can use different types of units ( px, vh, vw, rgb, rgba, hex, etc ) and in fact they have to specify them. Typical example for that would be - someone wants to change width of the table, types `600`, saves and nothing happens ( and in fact that was my first intuitive attempt to change the width ). 
So my proposition is - maybe adding a short info or a unit picker would be useful for the users?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This will be resolved by #6131.

**Comment by Reinmar** [comment]
Let's treat this as a DUP.
