### ISSUE TITLE
Auto formatting not working with Balloon Editor

### ISSUE THREAD

**Issue by justmarkup** [ckeditor/ckeditor5#6191]
## 📝 Reproduction

I am using ckeditor vue and the ballooneditor, via

```
import CKEditor from '@ckeditor/ckeditor5-vue';
import BalloonEditor from '@ckeditor/ckeditor5-editor-balloon/src/ballooneditor';
```
I also set up bold for toolbar and block toolbar, but if I type ```**bold**``` there is no autoformatting happening, but the documentation said it should work for all builds?

Here are all the plugins I use

```
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough'
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
import ListPlugin from '@ckeditor/ckeditor5-list/src/list';
import BlockToolbar from '@ckeditor/ckeditor5-ui/src/toolbar/block/blocktoolbar';
import Autosave from '@ckeditor/ckeditor5-autosave/src/autosave';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import WordCount from '@ckeditor/ckeditor5-word-count/src/wordcount';
```

### ✔️ Expected result

Autoformatting works as expected for balloon editor

### Question

- I tried to manually add the autoformat plugin, but then I get the error that it is already there
- Is there anything else which could prevent auto formatting from working? Any Plugin, any known issues?

**Comment by FilipTokarski** [comment]
Hi, I just checked Vue with BalloonEditor + Autoformat and it works fine.
To make it available, you have to import Autoformat just like other plugins, se be sure to add:

`import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';`

and be sure to add it to your editor configuration:

```js
data() {
    return {
	editor : BalloonEditor,
	editorConfig : {
		plugins : [
		    Autoformat,
                     // ...other plugins
		],
                 // ..toolbar and other configuration
	}
    }
}
```

Hope that helps!

**Comment by justmarkup** [comment]
Hi @FilipTokarski 

Thanks for your quick reply, I tried that but than I get the following error and I can't see where the duplicate comes from?

```
Reason: CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.
```
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

**Comment by FilipTokarski** [comment]
Could you show us your `package.json` file?

**Comment by justmarkup** [comment]
This are my dependencies from ckeditor:

```
"@ckeditor/ckeditor5-alignment": "^15.0.0",
"@ckeditor/ckeditor5-autoformat": "^16.0.0",
"@ckeditor/ckeditor5-autosave": "^15.0.0",
"@ckeditor/ckeditor5-basic-styles": "^15.0.0",
"@ckeditor/ckeditor5-block-quote": "^15.0.0",
"@ckeditor/ckeditor5-build-balloon": "^15.0.0",
"@ckeditor/ckeditor5-build-balloon-block": "^15.0.0",
"@ckeditor/ckeditor5-core": "^15.0.0",
"@ckeditor/ckeditor5-dev-utils": "^12.0.5",
"@ckeditor/ckeditor5-editor-balloon": "^15.0.0",
"@ckeditor/ckeditor5-essentials": "^15.0.0",
"@ckeditor/ckeditor5-font": "^15.0.0",
"@ckeditor/ckeditor5-heading": "^15.0.0",
"@ckeditor/ckeditor5-image": "^15.0.0",
"@ckeditor/ckeditor5-link": "^15.0.0",
"@ckeditor/ckeditor5-list": "^15.0.0",
"@ckeditor/ckeditor5-markdown-gfm": "^15.0.0",
"@ckeditor/ckeditor5-paragraph": "^15.0.0",
"@ckeditor/ckeditor5-paste-from-office": "^16.0.0",
"@ckeditor/ckeditor5-table": "^15.0.0",
"@ckeditor/ckeditor5-theme-lark": "^15.0.0",
"@ckeditor/ckeditor5-ui": "^15.0.0",
"@ckeditor/ckeditor5-undo": "^15.0.0",
"@ckeditor/ckeditor5-vue": "^1.0.0",
"@ckeditor/ckeditor5-word-count": "^15.0.0",
```

I also tried ```rm -rf node_modules && npm install``` but got the same error after.

**Comment by FilipTokarski** [comment]
Thanks, it seems like some of your plugins have different versions and that's what's causing the problem. You can either upgrade plugins to v.16 ( with exception of `ckeditor5-dev-utils` and `ckeditor5-vue`) or downgrade Autoformat and PasteFromOffice to v.15. For upgrading to the latest version you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

**Comment by justmarkup** [comment]
@FilipTokarski 

Thanks a lot, downgrading to v.15 worked.
