### ISSUE TITLE
Table's InsertTableView takes a long time to render

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6193]
## 📝 Provide detailed reproduction steps (if any)

We should improve rendering time of this component.

For instance in case of loading a simple editor with small data sample, it took 60ms, which in turns add up to slow `_initToolbar` execution. For comparison the entire editor renders in 1.23s so this view alone accounts for almost 5% of the entire initialization time.

![Profiler flame chart](https://i.imgur.com/YNRcnFQ.png)

### ✔️ Expected result

Quicker editor UI render 🏃‍♀️

### ❌ Actual result

`InsertTableView` takes a lot of time during the initial editor render 🐢 🐢 🐢 🐢 🐢 🐢 🐢 🐢 🐢

## 📃 Other details

This is a follow-up of #5880.

*   Browser: Chrome
*   OS: Windows (should be cross system)
*   CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
> Les recalculations 🏃‍♀️

The performance problem here isn't due to recalculations AFAICT, but simply initializing and rendering a lot of UI when not needed.

**Comment by mlewand** [comment]
> The performance problem here isn't due to recalculations

Yea, I copied the expected / actual from #6194. In case of tables, in fact a lot of items are created - something that we could defer.
