### ISSUE TITLE
How the table `alignment` attribute should be downcasted

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6197]
## 📝 Provide detailed reproduction steps (if any)

Right now it is downcasted as described [on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table):

> This enumerated attribute indicates how the table must be aligned inside the containing document. It may have the following values:
>
> - left: the table is displayed on the left side of the document;
> - center: the table is displayed in the center of the document;
> - right: the table is displayed on the right side of the document.
>
> Set margin-left and margin-right to auto or margin to 0 auto to achieve an effect that is similar to the align attribute.

In this regard in behaves differently than [image styles](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-styles). Current behavior does not change the rendered table visually so something must be changed:

a) If `<table>` is the outcome **and** we'd like the MDN approach (no text surrounding a table) then we need to change styles on `<figure>`/`<table>` to make the `margin` trick visible.
b) If we decide to go for Image styles way then we should convert this attribute to `<figure>` and what should be the outcome

To check:
- [x] conversion target (`<table>`/`<figure>`)
- [x] icons (should be updated if we do not want the text to surround table)

### ✔️ Expected result

To be honest I'm not 100% convinced that the current way or image style is better (for table).

However the table should be visually aligned to left/right when using alignment feature.

### ❌ Actual result

The table visually stays the same.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Let's use float for now, as in images and CKEditor 4.

We can add an option to switch off text flow. See https://github.com/ckeditor/ckeditor5/issues/6174.
