### ISSUE TITLE
Some tests started to fail on Chrome 80

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6198]
## 📝 Provide detailed reproduction steps (if any)

1. Update Chrome to the latest version (80)
2. Run tests on `master` branch

### ✔️ Expected result

:green_heart: tests are green

### ❌ Actual result

:red_circle: tests are red:

Tests fail in:

- table (one test) running single repo locally / CI ([PR](https://travis-ci.org/ckeditor/ckeditor5-table/builds/646322690))
- autoformat - bulleted list (multiple tests) running whole ckeditor5 tests locally
- ImageResize (multiple tests) running whole ckeditor5 or single repo locally

Those are only repositories I've found failing but I didn't check them all (ie table fails locally/Ci when running single repo but not when shole ckeditor5 package tests).

## 📃 Other details

* Browser: Chrome 80
* OS: Linux
* CKEditor version: latest master

CKEditor 5 builds on Travis CI (ooks OK though):

- latest for Chrome 79: https://travis-ci.org/ckeditor/ckeditor5/builds/646078449#L949
- manually triggered for Chrome 80: https://travis-ci.org/ckeditor/ckeditor5/builds/646475112

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Another one perhaps: https://travis-ci.org/ckeditor/ckeditor5-build-decoupled-document/jobs/646773142#L2322

**Comment by Reinmar** [comment]
For me, only the image resize tests fail locally on Chrome 80.0.3987 (Mac OS X 10.15.2). cc @mlewand

Also, on CI all are green now: https://travis-ci.org/ckeditor/ckeditor5/builds/646814309. Which is weird.

Can you check on your side?

**Comment by Reinmar** [comment]
OK, I can also reproduce the single table test that fails when running table tests locally. I'll handle that.

I can't reproduce any problem with autoformat when running all tests. I'll ignore this.

**Comment by mlewand** [comment]
@Reinmar interestingly tests ran on `master` for `image` and `widget` packages (`yarn run test -f image,widget`) are green on Windows. I can see that CI also reports no issue.

Tested with `Chrome 80.0.3987 (Windows 10.0.0)`. 🤔 I'll make a couple more runs.

**Comment by jodator** [comment]
@mlewand - it might be that for me only some configuration failed (ie running all tests or running single repo)

**Comment by Reinmar** [comment]
For this specific setup (image + widget) I get the below:

```
SUMMARY:
✔ 604 tests completed
✖ 2 tests failed

FAILED TESTS:
  Widget - integration
    ✖ should do nothing if clicked inside a nested editable
      Chrome 80.0.3987 (Mac OS X 10.15.2)
    AssertionError: expected '[<div class="ck-widget ck-widget_selected" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>]' to equal '[]<div class="ck-widget" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>'

      + expected - actual

      -[<div class="ck-widget ck-widget_selected" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>]
      +[]<div class="ck-widget" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>

    at Context.eval (webpack:///./packages/ckeditor5-widget/tests/widget-integration.js?:128:118)


    ✖ should does nothing for non-Safari browser
      Chrome 80.0.3987 (Mac OS X 10.15.2)
    AssertionError: expected '[<div class="ck-widget ck-widget_selected" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>]' to equal '[]<div class="ck-widget" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>'

      + expected - actual

      -[<div class="ck-widget ck-widget_selected" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>]
      +[]<div class="ck-widget" contenteditable="false"><figcaption contenteditable="true">foo bar</figcaption></div>

    at Context.eval (webpack:///./packages/ckeditor5-widget/tests/widget-integration.js?:247:118)


Error: Karma finished with "1" code.
error Command failed with exit code 1.
```

OMFG...

**Comment by Reinmar** [comment]
@mlewand, could you check `yarn run test -f core,engine,image,widget`

**Comment by mlewand** [comment]
I even went ahead and ran the entire test suite, still, no issue:
![image](https://user-images.githubusercontent.com/5353898/73936635-8d159780-48e3-11ea-8ef6-ab458da1898e.png)

**Comment by Reinmar** [comment]
Just perfect. So, I guess, we're waiting for a new Chrome version to patch that.

**Comment by Reinmar** [comment]
Let's merge this into https://github.com/ckeditor/ckeditor5/issues/6222.
