### ISSUE TITLE
Mobile examples not working for me

### ISSUE THREAD

**Issue by gbcgit** [ckeditor/ckeditor5#621]
Hi,

Congrats on the big achievement with version 5.  

Wish I had good news.  I tried to load these two pages with examples on an iPhone SE with stock Safari

1.  https://ckeditor.com/ckeditor-5-builds/
2.  https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html

In the first case the editor does NOT appear
In the second case, if I drag scroll around a bunch, I get a glimpses of the editor.

Should these work?   Or should I use version 4 for mobile website that needs editing?

Thanks

**Comment by AnnaTomanek** [comment]
Please see here for information about support for mobile environments: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/support/browser-compatibility.html#Mobile-environment (in short: it hasn't been our priority at this stage, we are aware it's buggy and we definitely will be fixing it).

As for docs, we are now working on a ticket to provide better UX on mobile devices, things should hopefully improve in a few days.

Thanks for your feedback!

**Comment by scofalik** [comment]
Might be related: https://github.com/ckeditor/ckeditor5/issues/603

**Comment by oleq** [comment]
And https://github.com/ckeditor/ckeditor5/issues/542 too.

**Comment by Reinmar** [comment]
Closing due to lack of feedback.
