### ISSUE TITLE
X-Content-Type-Options: nosniff ERROR

### ISSUE THREAD

**Issue by SrStick** [ckeditor/ckeditor5#6213]
when trying to load the ckeditor script on the front end it is blocked.
this is the error:

The resource `http://localhost:3003/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js` has been blocked due to the MIME type (“text/html”) not matching (X-Content-Type-Options: nosniff)

here's my script

`<script src="/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js">
        ClassicEditor.create(document.querySelector('#editor'))
        .catch(error => console.error(error));
</script>`

**CKeditor version: 5**
**Browser: Firefox 72.0.2**

**Comment by jeremywhittington** [comment]
Why was this closed?
