### ISSUE TITLE
Table Resize,Style sheet

### ISSUE THREAD

**Issue by plbeast** [ckeditor/ckeditor5#6216]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

A resize, style  function should be provided as which was should in ck4.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the comment. As it comes to styling and resizing tables this will be available in the next CKEditor 5 release, probably within ~one/two weeks time. You can read more about it [here](https://github.com/ckeditor/ckeditor5/issues/3287).
