### ISSUE TITLE
Inline Editor: the first heading or paragraph can not be modified

### ISSUE THREAD

**Issue by plbeast** [ckeditor/ckeditor5#6217]
## 📝 Provide detailed reproduction steps (if any)

1.build a package (Inline Editor) from offical website: https://ckeditor.com/ckeditor-5/online-builder/
2. Open the ./samples/index.html, it is showed the problem.

### ✔️ Expected result

Which select the first paragraph "This is some sample content." , The tool bar should be active.

### ❌ Actual result

Which select the first paragraph "This is some sample content." , The tool bar should be inactive.

## 📃 Other details

* Browser:  Chrome 79.0.3945.130
* OS: Win10
* CKEditor version: V5
* Installed CKEditor plugins:  any plusins are okay.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I just built an Inline Editor from the Online Builder page and selecting a paragraph makes toolbar active, as expected.
Did you change anything in the editor settings after downloading? I think in order to try to reproduce this issue, I need more information or some more detailed steps.

**Comment by plbeast** [comment]
Dear Filip,


I have try serval times. It may be caused by the plusin "Title" is included.&nbsp;


But it is still strange. That the first line can not be modified. And what's more. When I enter "Enter" then, the style of the first line destroyed.


best regards
Sam
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Filip Tokarski"; 
Date: 2020年2月11日(星期二) 晚上11:32
To: "ckeditor/ckeditor5"; 
Cc: "Sam Wang"; "Author"; 
Subject: Re: [ckeditor/ckeditor5] Inline Editor: the first heading or paragraph can not be modified (#6217)

&nbsp;

Hi, thanks for the report. I just built an Inline Editor from the Online Builder page and selecting a paragraph makes toolbar active, as expected.
 Did you change anything in the editor settings after downloading? I think in order to try to reproduce this issue, I need more information or some more detailed steps.

**Comment by FilipTokarski** [comment]
If you use `Title` plugin it works in such a way, that the first element you have in your editor content will be turned into document title. This is why the toolbar is disabled when you try to edit the first line of text - it was converted into document title. Similarly, when you press `enter` inside document title, the content gets separated and the second part of it is put into a `<p>` tag, which has its own, different styling. You can read more about this plugin [here](https://ckeditor.com/docs/ckeditor5/latest/features/title.html).
Hope that helps!

**Comment by plbeast** [comment]
Seems something reasonable.
