### ISSUE TITLE
Selection can no longer be placed before widget if it's the only item in model

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6221]
## 📝 Provide detailed reproduction steps (if any)

You can no longer set a selection before a widget (using `writer.setSelection( widgetModel, 'before' )`) if it's the only item in model.

This is best depicted by the following code:

```js
it( 'allows setting the selection before a widget', () => {
	setModelData( editor.model, '[<widget></widget>]' );

	const widgetModel = editor.model.document.getRoot().getChild( 0 );

	editor.model.change( writer => {
		writer.setSelection( widgetModel, 'before' );
	} );

	expect( getModelData( editor.model ) ).to.be.equal( '[]<widget></widget>' );
} );
```

This is a regression from https://github.com/ckeditor/ckeditor5-engine/commit/0dec72d4d80aa61927d922938a1f338e74f6c200

First bad commit in `master-revisions` branch: https://github.com/ckeditor/ckeditor5/commit/beade810a465ba3b130f2071af9a6dc950e13b97

### ✔️ Expected result

The selection should be placed before the widget.

### ❌ Actual result

An entire widget gets selected.

## 📃 Other details

Interestingly I checked whether setting selection  **after** the widget is possible, however it doesn't work even in 16.0.0 so this surprised me, and looks like a different case.

* Browser: Any
* OS: Any
* CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Added an example unit test here https://github.com/ckeditor/ckeditor5-widget/tree/i/6221

Although `widget-integration.js` coinciden`t`ally t`est this case too`.

**Comment by Reinmar** [comment]
That's not a correct selection position. Selection is only allowed on object elements or in containers which allow $text inside (you can type there).
