### ISSUE TITLE
how add some attribute to new text when user type some text

### ISSUE THREAD

**Issue by malone081021** [ckeditor/ckeditor5#6224]
Add some attribute, eg: "highlight"、"blod"，when user type new text.

like `writer.setAttribute('highlight', { value: 'yellowMarker' })` ,

have any event or time , I can run `writer.setAttribute('highlight', { value: 'yellowMarker' })`  or 

any Other methods

**Comment by Mgsy** [comment]
If you'd like to add a highlight to the text inserted by a user, you can use the following code:

```js
const inputCommand = editor.commands.get( 'input' );
const highlightCommand = editor.commands.get( 'highlight' );

inputCommand.on( 'execute', () => {
    if ( !highlightCommand.value ) {
	editor.execute( 'highlight', { value: 'yellowMarker' } );
    }
}, { priority: 'high' } );
```
