### ISSUE TITLE
Setting table/cell style to "none" should reset other fields

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6227]
## 📝 Provide detailed reproduction steps (if any)

1. Set table border style to solid.
2. Set the color.
3. Change the style back to none.

### ✔️ Expected result

There's no color set any more.

### ❌ Actual result

The color is not reset. You can't change it now.

![image](https://user-images.githubusercontent.com/156149/74251669-c50a4980-4cec-11ea-9132-91bc9441043c.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Additionally, `table-style:none` should not be left in the data when you set this value.

**Comment by jodator** [comment]
> Additionally, `table-style:none` should not be left in the data when you set this value. Covered also in #6232.

I handle this case in #6232 because it is other issue than reported here.
