### ISSUE TITLE
Table properties: default value == no value

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6232]
## 📝 Provide detailed reproduction steps (if any)

Let's fix the scenarios listed in https://github.com/ckeditor/ckeditor5/issues/6231.

**Comment by Reinmar** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/6227.

**Comment by jodator** [comment]
The issue itself isn't hard to fix but linked issues (#6227, #6179) required to be closed first as those have code needed by this.

#6227 - clears other fields and will have conflicting changes
#6179 - has common code needed to implement this change.

ATM I've created a draft PR with obvious changes: https://github.com/ckeditor/ckeditor5-table/pull/245.

**Comment by jodator** [comment]
@Reinmar one last thing - what should land in the model for default values - I assume that nothing.

So if we upcast data we should filter out default values, ie for `borderStyle` we should upcast known values and ditch the `'none'` and other unknown?

**Comment by Reinmar** [comment]
> @Reinmar one last thing - what should land in the model for default values - I assume that nothing.

Yep, no attribute.

> So if we upcast data we should filter out default values, ie for `borderStyle` we should upcast known values and ditch the `'none'` and other unknown?

IDK, TBH. I'd do the thing which requires least work now.
