### ISSUE TITLE
Cannot copy image + text if the image is the last tag of the content

### ISSUE THREAD

**Issue by FlBaumann** [ckeditor/ckeditor5#6234]
## 📝 Provide detailed reproduction steps (if any)

1. Write some text in the Editor 
2. Upload a Image
3. Click with your mouse on the written text again
4. Ctrl + A
5. Ctrl + X/C 

### ✔️ Expected result
It will copy/cut text +image

### ❌ Actual result
Nothing happens

## 📃 Other details

* Browser: Chrome
* OS: Win 10
* CKEditor version: ckeditor5 16.0.0
* Installed CKEditor plugins: 

ClassicEditor.builtinPlugins = [
	Essentials,
	SimpleUploadImagePlugin,
	Alignment,
	Autoformat,
	Bold,
	Italic,
	Underline,
	Strikethrough,
	Image,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Link,
	List,
	Table,
	TableToolbar,
	RemoveFormat,
	Highlight,
	SimpleButton
];

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Unfortunately it's a known and more general case, which concerns copying widgets that are at the beginning / end of the document. It's already been reported [here](https://github.com/ckeditor/ckeditor5/issues/2066).
