### ISSUE TITLE
How to add Custom plugin on ckeditor5 inline editor

### ISSUE THREAD

**Issue by meharoof** [ckeditor/ckeditor5#6236]
How can we add Custom plugin on ckeditor5 inline editor. I need to add a plugin on toolbar and open a custom pop up while click on it. pop up view  contains OK button and it generate a html tag on the selected place when clicking on OK button. Can you please help anyone.

We are tying to migrate ckeditor 4 version to 5. Following is the code that we had implemented on ckeditor 4 version. Actually we need to implement this code on ckeditor version 5.

var _importedSavedSearchKey = null;
var _importSavedSearchInstance = null;
CKEDITOR.plugins.add('agoraImportDemand',
{
    init: function (editor) {
        var pluginName = 'agoraImportDemand';
        editor.ui.addButton('agoraImportDemand',
            {
                label: 'Import Saved Searches',
                command: 'agoraImportDemandOpen',
                icon: CKEDITOR.plugins.getPath('agoraImportDemand') + 'icons/agorawidgets.png',
            });
        var cmd = editor.addCommand('agoraImportDemandOpen', { exec: ImportSavedSearch });
    }
});

function ImportSavedSearch(e) {
    _importSavedSearchInstance = e;
    $("#IwbPopUpArea").AgoraDialogModal({ ServiceUrl: '/webbuilder/GetAgentSavedSearchList.aspx', ParentCss: 'webbuilder', EnableAjaxHtmlLoad: true });
}

function InsertSavedSearchTemplate(dmandKey, demandName, demandQueryUrl, layoutImage, layout) {
    $("#IwbPopUpArea").AgoraDialogModal({ CloseModal: true });
    layoutImage = (typeof (layoutImage) != 'undefined' ? layoutImage : "/Images/SaveSearchLayoutThumb/demandtemplate-1.jpg");
    _importSavedSearchInstance.insertHtml('<agora_import_demand><img style="width: 100%;" alt="' + demandName + '" src="' + layoutImage + '" data-layout="' + layout + '" data-demand-key="' + dmandKey + '" data-demand-url="' + demandQueryUrl + '" /></agora_import_demand>');
}

Thanks in Advance!

**Comment by Reinmar** [comment]
Please refer to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/overview.html and the following guides to learn how to build plugins for CKEditor 5.

**Comment by meharoof** [comment]
Thanks. I would like to call a function while click on Ok Button in custom pop up. The function will return a HTML element and it need to place that HTML element on selected place inside CkEditor. Funtion is given below and can anyone convert this code from CKEditor 4 to 5

function InsertSavedSearchTemplate(dmandKey, demandName, demandQueryUrl, layoutImage, layout) {
    layoutImage = (typeof (layoutImage) != 'undefined' ? layoutImage : "/Images/SaveSearchLayoutThumb/demandtemplate-1.jpg");
    _importSavedSearchInstance.insertHtml('<agora_import_demand><img style="width: 100%;" alt="' + demandName + '" src="' + layoutImage + '" data-layout="' + layout + '" data-demand-key="' + dmandKey + '" data-demand-url="' + demandQueryUrl + '" /></agora_import_demand>');
}
