### ISSUE TITLE
Table properties is sometimes displayed below the toolbar

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6242]
## 📝 Provide detailed reproduction steps (if any)

It seems that it only happens in the north position:

![Feb-12-2020 21-07-14](https://user-images.githubusercontent.com/156149/74372879-bc447100-4ddb-11ea-8b08-556daea1ae8e.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
It could be an aftermath of changes made in https://github.com/ckeditor/ckeditor5/issues/6220. When the toolbar is not sticky it is positioned in a different way than when it's sticky. It can work differently with `z-index`.

**Comment by Reinmar** [comment]
OK, we reverted the patch for the above mentioned issue, and this problem is now gone.
