### ISSUE TITLE
When I use DecoupledEditor in React，running with ‘TypeError: Cannot set property 'ckeFiller' of undefined’

### ISSUE THREAD

**Issue by mamaledoboi** [ckeditor/ckeditor5#6245]
## 📝 Provide detailed reproduction steps (if any)

1. import
```
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
```

2. render()

```
 <TabPane >
      <h1>Document editor</h1>
      <div id="toolbar-container" />
      <div id='editor'>
          <p>This is the initial editor content.</p>
      </div>
  </TabPane>
```

3. create a editor
```
componentDidMount() {
    DecoupledEditor
        .create( document.querySelector( '#editor' ) )
        .then( editor => {
          const toolbarContainer = document.querySelector( '#toolbar-container' );

          toolbarContainer.appendChild( editor.ui.view.toolbar.element );
        } )
        .catch( error => {
          console.error( error );
        } );
}
```
4. running

### ✔️ Expected result

show the editor on page

### ❌ Actual result
```
 error2: TypeError: Cannot set property 'ckeFiller' of undefined
```

## 📃 Other details

* Browser: chrome
* OS: MacOS
* CKEditor version: 5
* Installed CKEditor plugins: only ckeditor5-build-decoupled-document

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I created a react app with the settings you provided and the editor works just fine, I have no errors. 
Please make sure you follow the steps from our [react integration documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#quick-start) and you should be able to run your app without problems.

**Comment by bhayward93** [comment]
Are you by chance using SSR? https://github.com/ckeditor/ckeditor5/issues/1511

**Comment by Mgsy** [comment]
Closing it due to a lack of response from the author.

**Comment by Dolov** [comment]
why not use "import CKEditor from '@ckeditor/ckeditor5-react'"
