### ISSUE TITLE
Setting table height does not prevent cell height from expanding the table

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6249]
## 📝 Provide detailed reproduction steps (if any)

1. Open [test](http://localhost:8125/ckeditor5-table/tests/manual/tableproperties.html) and add a new table
2. Set table with to 500px and height to 300px
3. Select a cell and set height to 600px

### ✔️ Expected result

Table height should prevent cell height from expanding the table

### ❌ Actual result

Table height expands, balloon gets hidden under the toolbar

![table_height](https://user-images.githubusercontent.com/34380544/74428235-e6884400-4e58-11ea-86c9-c1d6b0ca575d.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It's a behaviour of the browser and we don't have much to say here. We could workaround it, but I don't know what I'd expect myself as a user if I set the width in two places. I'll close this issue as invalid. I think that it may get better when we introduce resizing by mouse too.
