### ISSUE TITLE
Add code of examples

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#625]
We knew how important this is for the developers but we didn't manage to add code examples to live examples.

I've just checked how many visits we had from various sources to this repo and the first referer is docs.ckeditor.com. From which pages precisely?

![image](https://user-images.githubusercontent.com/156149/31837070-b32ce60e-b5d7-11e7-9229-fbfbc68fd1c0.png)

Yep, from examples. I wondered why and it gets clear when you see the website:

![image](https://user-images.githubusercontent.com/156149/31837093-c3489dd0-b5d7-11e7-9fd7-fca770c54b2f.png)

Basically, people hoped to see the code of these examples.

Let's fix this. We can do this in two steps:

1. Let's add a short paragraph of text above/below each example with a link to the Quick Start guide saying that the user can find the source there.
2. Let's work on wrapping examples with tabbed widget presenting "output", "HTML", "JS" and "CSS" if needed. A link to JSFiddle would actually be doable now too (in most of the examples), but to reduce the scope this can be done later.

@AnnaTomanek, could you handle the first part? Please also ping @m-turek so we publish the changes once they are done.

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5/issues/1608#issuecomment-474338643

> If we want to add the inspector to all demos of the editor in our docs, we should/could try to do that together with displaying the source code of these samples (reported in #625). Therefore, let's for now focus on mentioning the inspector in a couple of places, rather than on enabling it.

**Comment by Reinmar** [comment]
FYI: again request for source code 😄 
<img width="855" alt="Screenshot 2019-04-05 at 09 24 29" src="https://user-images.githubusercontent.com/10219857/55611098-d1e11700-5784-11e9-9815-748e815e9b54.png">

**Comment by godai78** [comment]
My suggestion is to follow suit and add the code of examples as we did for full-featured and bottom-toolbar examples.  
  
Using the real code listing from the examples would make the editor (almost) immediately deployable hence of hight usability for integrators.  
  
The said examples:

*   full-featured: [https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)
*   bottom toolbar: https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/bottom-toolbar-editor.html
