### ISSUE TITLE
Custom UploadAdapter + downcast of result is not applied immediately

### ISSUE THREAD

**Issue by kroeberk** [ckeditor/ckeditor5#6261]
## 📝 Provide detailed reproduction steps (if any)

1. Create a custom upload adapter that returns {default: SOME-ID}
2. Create a elementToElement Downcaster for image elements that replaces SOME-ID with an actual URL

### ✔️ Expected result

The image should upload and then be immediately downcast and displayed correctly.

### ❌ Actual result

The image model is not downcast, the HTML stays like 
`<img src=SOME-ID/>`
, instead of 
`<img src=URL>`
, therefore the image appears broken. When reloading the editor, downcast works as expected.

## 📃 Other details

* Browser: Chrome 
* OS: MacOS
* CKEditor version: 
 "@ckeditor/ckeditor5-core": "^12.2.1",
    "@ckeditor/ckeditor5-engine": "^13.2.1",
    "@ckeditor/ckeditor5-react": "^1.1.3",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Since it's an attribute change here, you need an attributeToAttribute converter, not elementToElement. The latter would only handle data loaded at once, or a pasted image.

I'll close the ticket. Let me know if I didn't guess it correctly.
