### ISSUE TITLE
document editor plugin  image upload

### ISSUE THREAD

**Issue by updatepromise2020** [ckeditor/ckeditor5#6262]
@Reinmar i need your help please , i updated to cke 5 editor in my angular app, i used document editor plugin and use onready function to render it but i'm not able to upload any image file from my gallery , My question is how can i catch the image upload file and display it in the email body?

i tried to configure the simple upload file adapter plugin but my application complains about the duplicate plugin , i'm not sure how can i use together

this is my onready fun

public onReady( editor ) {

    editor.ui.getEditableElement().parentElement.insertBefore(
        editor.ui.view.toolbar.element,
        editor.ui.getEditableElement()
    );
}

Any help will be appreciated!
thanks

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. To be able to look into this issue, I need to see the error message you are getting and your editor configuration. Meanwhile, you can also refer to our docs on [Angular integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html), [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and [Simple Upload Adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html). 
Please also make sure that the plugins you installed are all of the same version.

**Comment by updatepromise2020** [comment]
@FilipTokarski I have upgraded to cke editor version 5 and I want to remove the default <p></p> tag insertion on every line . I have tried multiple way in angular 8 but nothing works. Please help me how can i use configuration of cke5 editor in my angular 8 project . Thank you !

Below is my config code
 public Editor = DecoupledEditor;
 cke5Config: any;
this.cke5Config = { //config for cke editor 5
    autoParagraph: false,
    enterMode: 'br',
    ShiftEnterMode: 'br',
  
} 

              <ckeditor #editorEmail [config]="cke5Config" [editor]="Editor"  debounce="500"  (ready)="onReady($event)"></ckeditor>

**Comment by FilipTokarski** [comment]
I'm not sure I understood correctly. Could you please clarify what is your goal here and provide step by step path to reproduce your issue?
