### ISSUE TITLE
try to add nested paragraph to new model element: Cannot read property 'is' of undefined

### ISSUE THREAD

**Issue by dmarini** [ckeditor/ckeditor5#6263]
Creating a new plugin, starting off very simple, want to simply create a <caption><paragraph></paragraph></caption> structure in the $root. I have looked at the table plugin code as reference and see how the insertTableRowsCommand seems to do exactly the same thing:

schema is as follows:

```
schema.register('caption', {
     allowIn: ['$root'],
     allowContentOf: ['$block', '$text'],
     isLimit: true
});

schema.extend('paragraph', { allowIn: 'caption' });
```
In the execute of the command (modelSelection is just document.selection in this snippet):
```
 model.change(writer => {
            const e = writer.createElement('caption'); //create the caption element
            writer.insert(e, modelSelection.getFirstPosition()); //insert into the model
            writer.insertElement('paragraph', e); //put the paragraph inside
        }); 
```
### ✔️ Expected result
expect that the inspector will show me a model looking like: 
```<$root><caption><paragraph></paragraph></caption></$root>``` 
with no thrown errors

### ❌ Actual result
model looks like ```<$root><caption><paragraph></paragraph></caption></$root>``` but the following error is thrown, after which the editor is broken:

```
ckeditorerror.js:66 Uncaught CKEditorError: unexpected-error {"originalError":{"message":"Cannot read property 'is' of undefined","stack":"TypeError: Cannot read property 'is' of undefined\n    at Mapper._findPositionIn (http://localhost:8080/ckeditor.js:11860:19)\n    at Mapper.on.priority (http://localhost:8080/ckeditor.js:11426:29)\n    at Mapper.fire (http://localhost:8080/ckeditor.js:83622:30)\n    at Mapper.toViewPosition (http://localhost:8080/ckeditor.js:11653:8)\n    at DowncastDispatcher.modelViewSplitOnInsert (http://localhost:8080/ckeditor.js:58371:43)\n    at DowncastDispatcher.fire (http://localhost:8080/ckeditor.js:83622:30)\n    at DowncastDispatcher._testAndFire (http://localhost:8080/ckeditor.js:9729:8)\n    at DowncastDispatcher.convertInsert (http://localhost:8080/ckeditor.js:9440:9)\n    at DowncastDispatcher.convertChanges (http://localhost:8080/ckeditor.js:9392:10)\n    at http://localhost:8080/ckeditor.js:8473:29","name":"TypeError"}}
    at Function.rethrowUnexpectedError (http://localhost:8080/ckeditor.js:79887:9)
    at Mapper.fire (http://localhost:8080/ckeditor.js:83655:59)
    at Mapper.toViewPosition (http://localhost:8080/ckeditor.js:11653:8)
    at DowncastDispatcher.modelViewSplitOnInsert (http://localhost:8080/ckeditor.js:58371:43)
    at DowncastDispatcher.fire (http://localhost:8080/ckeditor.js:83622:30)
    at DowncastDispatcher._testAndFire (http://localhost:8080/ckeditor.js:9729:8)
    at DowncastDispatcher.convertInsert (http://localhost:8080/ckeditor.js:9440:9)
    at DowncastDispatcher.convertChanges (http://localhost:8080/ckeditor.js:9392:10)
    at http://localhost:8080/ckeditor.js:8473:29
    at View.change (http://localhost:8080/ckeditor.js:48818:27)
```

## 📃 Other details

If I insert just the caption, no error. It's only when I try to nest an element inside the caption that I get this error. I don't understand why the view layer would even care when right now I'm simply modifying the model, not the view. There are no up/downcasters registered yet, I was simply starting by manipulating the model, and again the table plugin (which I looked at for reference) does exactly this. I am confused and nothing in the documentation seems to indicate why this would be needed or fail.

Finally, how do you guys determine where failures are sourced? the event model in CKEditor makes debugging a true horror story, with disconnected stacks that lead you nowhere near where the error was originally thrown, making it close to impossible to determine on my own how the engine operates and possibly learn/fix it on my own. Am I missing some easy way to track the bugs to the plugin that registered whatever listener uses this mapper call?

* Browser: Chrome 79
* OS: Windows 10
* CKEditor version: Custom build with all @ckeditor5 packages at 15.0.0

* Installed CKEditor plugins: Less than the standard set. Table plugin excluded to verify it wasn't a random downcaster error registered by the table (which again, does the same thing but it works):
[
	Essentials,
	Alignment,
	FontSize,
	FontFamily,
	Highlight,
	UploadAdapter,
	Bold,
	Italic,
	Strikethrough,
	Underline,
	Superscript,
	Subscript,
	BlockQuote,
	CKFinder,
	EasyImage,
	Image,
	Indent,
	IndentBlock,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	TableCaption,  <--- my plugin, eventually will add caption to table elements
]

Given the above, I feel like this must be a bug. Sorry if i'm incorrect but could use whatever help is available.

**Comment by Reinmar** [comment]
Hi! I'm not able to dive deeper into this right now but perhaps I'll be right – do you have a converter for that new element?

As for the problems with debugging, we're aware of them. That's not that big problem for us because of the experience that we have, but we're completely aware that it's sometimes a black box for other developers. E.g. if I'm right that it's a missing converter, then it's something that should be far more verbose. The event system should also have better debugging tools.

**Comment by Mgsy** [comment]
Closing it due to a lack of activity.
