### ISSUE TITLE
Demo editors in guides should always come with a meaningful content

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6268]
## 📝 Provide a description of requested docs changes

Take a look at https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/image.html#image-styles

![image](https://user-images.githubusercontent.com/1099479/74525605-beb0e300-4f21-11ea-8437-9b70f4db9f11.png)

I think we can do better than

```
Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here. Lots of text here.
```

because ATM it looks like a developer code somehow made it to the production. It's not a manual test but a feature guide for end–users. It should present more or less a read use–case and that means some meaningful content.

@AnnaTomanek @Reinmar

**Comment by AnnaTomanek** [comment]
You're totally right. We've been trying to avoid such Lorem ipum style content in the demos for a little while, but there are still some older demos that need some work. I'll try to handle it in the nearest future :+1: .

**Comment by godai78** [comment]
I rewrote it into a more humane version doing some other task, there were two occurrences of those.

**Comment by godai78** [comment]
I keep doing this, should all rewritten demos be referenced here, too?

**Comment by oleq** [comment]
You can ping this issue in commit messages ("see #6268"). References will pop up here for the record automatically and when you find out you ran out of lorem ipsums we can close this issue. 

Also, make sure the issue has a time estimate despite being resolved by commits related to other issues.

**Comment by godai78** [comment]
I believe - with the exception of the image guide - all other demos have been rewritten to have sensible contents.

**Comment by godai78** [comment]
Plenty of stuff has since been rewritten and / or created from scratch. We may consider listing what else needs to be changed.

**Comment by AnnaTomanek** [comment]
When you have a moment to spare, @godai78, could you kindly go through the demos again and see if there is anything left to do? It would be great if we could close this issue and #9995 finally after making sure all demos have meaningful content indeed.

**Comment by godai78** [comment]
No sooner than the next release ships, I believe. Unless in meantime. But I will. Some of #9995 are unattainable, tho.

**Comment by godai78** [comment]
No more demos with nonsensible / placeholder content (except ones where it is no attainable). #9995 stays as a leftover follow-up.
