### ISSUE TITLE
Text with attribute in an exception marker is missing cursor: text

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6272]
## 📝 Provide detailed reproduction steps (if any)
1. Put the caret in an exception marker.
1. Insert some styled text, i.e. with bold.
1. Hover it.

### ✔️ Expected result

The cursor displays as `text`.

### ❌ Actual result

The cursor displays as `default`.

## 📃 Other details

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/74527560-544e7180-4f26-11ea-891c-89d408ed8155.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @panr

**Comment by panr** [comment]
Probably `bold` has some other styles that override our latest changes... I will take a look at this 👍

**Comment by panr** [comment]
PR is ready to check. I refactored code for styling as well.
