### ISSUE TITLE
New line with Shift + Enter

### ISSUE THREAD

**Issue by CHItA** [ckeditor/ckeditor5#628]
Hey there,

It would be nice to be able to enter plain break lines by using Shift + Enter or something similar. I am not entirely sure whether this should be a core feature or would it better be off as a feature in CKEditor 5.

Just a suggestion, keep up the good work.

**Comment by szymonkups** [comment]
Hello,
Could you please take a look at this issue: https://github.com/ckeditor/ckeditor5/issues/617? You can find there detailed information that should answer your questions.

**Comment by CHItA** [comment]
Thanks, it seems I haven't done a thorough enough search. For anyone who might find this later there is an [open ticket about this here](https://github.com/ckeditor/ckeditor5-enter/issues/2).
