### ISSUE TITLE
Div with display table is not recognized by ckeditor

### ISSUE THREAD

**Issue by leandrogallina** [ckeditor/ckeditor5#6281]
## 📝 Reproduction steps

The problem happens when I open the editor with the following HTML:

<div class="container" style="display: table">
  <div class="row" style="display: table-row">
    <div class="cell" style="display: table-cell border-style: solid; border-width: thin">
      ONE CELL
    </div>
    <div class="cell" style="display: table-cell border-style: solid; border-width: thin">
      ANOTHER CELL
    </div>
  </div>
</div>

### ✔️ Expected result

The editor should display the content in two cells in a single row, as if created from an HTML table:

ONE CELL | ANOTHER CELL

### ❌ Actual result

The editor ignores all divs, displaying the content of what should be cells one in top of the other:

ONE CELL

ANOTHER CELL

## 📃 Other details

* Browser: Firefox 72.0.2
* OS: Linux Ubuntu 
* CKEditor version: "15.0.0"
* Installed CKEditor plugins: ckeditor5-adapter-ckfinder, ckeditor5-alignment, ckeditor5-autoformat, ckeditor5-basic-styles, ckeditor5-block-quote, ckeditor5-ckfinder, ckeditor5-core, ckeditor5-dev-utils, ckeditor5-dev-webpack-plugin, ckeditor5-easy-image, ckeditor5-editor-decoupled, ckeditor5-essentials, ckeditor5-font, ckeditor5-heading, ckeditor5-highlight, ckeditor5-image, ckeditor5-indent, ckeditor5-link, ckeditor5-list, ckeditor5-media-embed, ckeditor5-paragraph, ckeditor5-paste-from-office, ckeditor5-table, ckeditor5-theme-lark, ckeditor5-mention, ckeditor5-typing

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, can you show the exact HTML you're loading into the editor?

**Comment by leandrogallina** [comment]
Of course! Sorry, it looks like the HTML disappeared from the Github editor.

```
<div class="container" style="display: table">
<div class="row" style="display: table-row">
<div class="cell" style="display: table-cell">
ONE CELL
</div>
<div class="cell" style="display: table-cell">
ANOTHER CELL
</div>
</div>
</div>

```

**Comment by jodator** [comment]
Hi @leandrogallina we only support standard HTML elements in our features. It would be impossible for us to handle all possible markup that imitates proper HTML elements. I don't know your business case that is behind your markup but HTML has already table elements.

Besides that, if you wish to support such HTML content you have to write all the converters by yourself. If you have a structure like that without `colspan` or `rowspan` attributes and you don't use table sections as `thead` or `tbody` I would try to use [`conversion.elementToElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-elementToElement) for this.

Here is a sample like a two-way converter for table cell might look:
```js
editor.conversion.elementToElement( {
	model: 'tableCell',
	view: {
		name: 'div',
		classes: [ 'cell' ],
		styles: {
			display: 'table-cell'
		}
	}
} );
```
You will also need a converters for `table` and `tableRow` model elements.
