### ISSUE TITLE
Line deleted but formatting remains even on official demo

### ISSUE THREAD

**Issue by zehawki** [ckeditor/ckeditor5#6282]
## 📝 Provide detailed reproduction steps (if any)

Delete a line of heading text. Now press delete to bring the next line of paragraph up.

### ✔️ Expected result

The para text should just move up without any changes to its formatting.

### ❌ Actual result

The para text takes the formatting of the previous line even though it was deleted.

Here's a gif showing whats going on:

![captured](https://user-images.githubusercontent.com/8095144/74720544-fd190b80-525b-11ea-85fe-e3b6be628fbb.gif)

I looked into the HTML as its being generated and see the issue:

After the line is deleted, the formatting tags are not removed along with the line, so the HTML contains:
`<h2>&nbsp;</h2><p>Like all the great things on earth traveling teaches us by example. Here are some of the most precious lessons I’ve learned over the years of traveling.</p>`
And then when delete is pressed, the next para text takes the h2 tag.

This is a very unintuitive behavior and something I've not seen in any other editor. To cross check I performed exactly the same in Word, Google docs, Quill and clearly they handle this as expected.

Froala does the same thing as CK, BUT it has a saving grace - when the heading line is deleted and another backspace is pressed, the line formatting disappears.

I strongly feel this behavior should be changed since its quite unexpected & puzzling for the end users (who reported this issue to me) and I find it equally puzzling :-)

**Comment by Mgsy** [comment]
Hi, thanks for the report. We're aware that the current behaviour might be unintuitive and we're discussing it [here](https://github.com/ckeditor/ckeditor5/issues/3115). Feel free do join the discussion and add 👍 to the first post to raise its popularity.
