### ISSUE TITLE
Inline widget disappearing (everything between the widgets) on typing

### ISSUE THREAD

**Issue by abhikhatri** [ckeditor/ckeditor5#6283]
I developed a plugin to insert image as inline widget but whenever I type after the inserted widget it deletes everything in between the widgets

Here's a video
https://streamable.com/oeu0k

The code is almost same as placeholder widget but not sure why's it happening with my custom plugin!

Only happening if I insert the image tag, when I changed the widget to a span with some random data, it's working like it's supposed to be.

## 📃 Other details

* Browser: Chrome 80
* OS: Mac OS High Sierra
* CKEditor version: 16.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, it's hard to tell why your solution doesn't work without seeing your code. Could you share a snippet, so we'll be able to take a quick look what's going on?

**Comment by abhikhatri** [comment]
@Mgsy Here's the repo ->  https://github.com/abhikhatri/mathInput
Build using `npm run build` and then just start a static server inside directory

You can add maths via small text editor below

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
