### ISSUE TITLE
Table selection does not cooporate with typing

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6284]
## 📝 Provide detailed reproduction steps (if any)

1. Make mouse selection in table for 2+ table cells
2. Type something

### ✔️ Expected result

You should be able to type in last table cell.

### ❌ Actual result

Something breaks

## 📃 Other details

I've tried to fix this issue with 

```js
this.listenTo( viewDocument, 'keydown', () => {
	if ( !this.hasMultiCellSelection ) {
		return;
	}

	editor.model.change( writer => {
		const end = this._endElement;
		this.clearSelection();
		writer.setSelection( end.getChild( 0 ), 0 );
	} );
}, { priority: 'highest' } );
```

In the `TableSelection` class and it works well but it needs some behavior polishing. For isntance arrows do not work as expected (you end up in different cell then `end` one.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This should be handled in the ckeditor5-typing package. There's a listener for keydown which should make sure that the selection is collapsed. Let's move the selection to the first cell. We don't even need to select its content.

**Comment by Reinmar** [comment]
May be blocked by https://github.com/ckeditor/ckeditor5/issues/6328.
