### ISSUE TITLE
Table cell/row/column selection – stage II

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6285]
This is a followup for the table selection MVP ticket (#3202).

In this iteration following improvements will be implemented:

*   [Improved keyboard handling (up and down arrows, tab handling)](https://github.com/ckeditor/ckeditor5/issues/3267)
*   [Introduced select entire row and select entire column features](https://github.com/ckeditor/ckeditor5/issues/6500)
*   [Improved merge and split command handling](https://github.com/ckeditor/ckeditor5/issues/6123)
*   [Improved removing rows/columng from tables with colspan/rowspan multi-cell selections](https://github.com/ckeditor/ckeditor5/issues/6406)
*   [Table properties balloon should be positioned in relation to the selection rather than the entire table](https://github.com/ckeditor/ckeditor5/issues/6357)
*   [Fixed a case where it was possible to merge regular cell with a header cell](https://github.com/ckeditor/ckeditor5/issues/6521)
*   [Fixed a crash when undoing row insertion with cell properties applied](https://github.com/ckeditor/ckeditor5/issues/6382)
*   [Fixed a crash when removing a row after horizontal split](https://github.com/ckeditor/ckeditor5/issues/6401)

**Comment by QuentinLeGoff** [comment]
Hi, does it include cell/row/column selection in collaboration ?

**Comment by Reinmar** [comment]
No, not yet. Still in the pipeline for Q2.
