### ISSUE TITLE
What about bringing some life to the table feature demo with some emojis?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6287]
## 📝 Provide a description of requested docs changes

Before:

![Screenshot 2020-02-19 at 09 50 46](https://user-images.githubusercontent.com/1099479/74817575-6866ea00-52fd-11ea-9440-7d90d3afc328.png)

After:

![Screenshot 2020-02-19 at 09 50 36](https://user-images.githubusercontent.com/1099479/74817569-6735bd00-52fd-11ea-8dd8-bf86badf1407.png)

cc @AnnaTomanek @Reinmar

**Comment by AnnaTomanek** [comment]
Go go go! :racing\_car:

**Comment by Reinmar** [comment]
Go go go! 🏎
