### ISSUE TITLE
Should copied part of a table include table properties?

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6288]
## 📝 Provide a description of the improvement

When copying part of a table should we copy table attributes also?

I can see that some attributes don't make sense like:

- `width`
- `height`
- border color, width, style
- `alignment`

But some might make sens:

- `backgroundColor`

ps.: The headings are calculated so you can copy part of the table with headings.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I'd say no. Most styles, as you mentioned make no sense. 

A bit similar situation happens when copying text. We also don't copy the block styles with that.

So, I'm closing this as I assume there's no work needed.
