### ISSUE TITLE
Source View

### ISSUE THREAD

**Issue by agluck3** [ckeditor/ckeditor5#629]
- [X ] Feature request

## 💻 Version of CKEditor
V5

I would love to see the View Source option become available. When I write my posts I like to be able to add custom html into it.

**Comment by pjasiun** [comment]
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/592.

**Comment by bhojkamal** [comment]
Yes, I also want to see the source code like in CKEditor 4.

**Comment by robozb** [comment]
+1

**Comment by webivan1** [comment]
+1
