### ISSUE TITLE
[BUG] cannot get selected items

### ISSUE THREAD

**Issue by MuTaToR08** [ckeditor/ckeditor5#6290]
### 📝 Provide detailed reproduction steps (if any)

i have this model:
```
<ul>
  <li>text 1 for test</li>
  <li>text 2[ for test</li>
</ul>
<p>text last] for test</p>
```
the characters "[" and "]" indicate the selection of text.

### ✔️ Expected result

I tried to get the elements " for test" and "text last" using code
```
const selection = editor.model.document.selection;
const range = selection.getFirstRange();

for (const item of range.getItems()) {
    console.log(item.data)
}  
```

### ❌ Actual result

But I get all the elements completely

### 📃 Other details
* Browser: chrome 
* OS: win 10
* CKEditor version: 12.3.0

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I checked this using code you provided ( on v.12.3.0 ) and I'm getting three elements: `" for test"`, `undefined`, `"text last"` - so everything seems to be fine here. It would be easier to understand this issue if you explained what do you mean by _"I get all the elements completely"_ and maybe you could show the results you are getting.

**Comment by MuTaToR08** [comment]
sorry, i testing on breakpoin in plugin. 
I noticed, after your comment, that it selects all the text to my breakpoint.
