### ISSUE TITLE
Do not use a table in the special chars demo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6292]
## 📝 Provide a description of requested docs changes

So, we've got an ugly bug https://github.com/ckeditor/ckeditor5/issues/6220 and it's so painfully visible in our demo, that I'd like to change it. Let's replace that table with something else.

**Comment by AnnaTomanek** [comment]
Fixed with ckeditor/ckeditor5-special-characters@22d6609.
