### ISSUE TITLE
CKEditor 5 source code not working properly

### ISSUE THREAD

**Issue by meharoof** [ckeditor/ckeditor5#6293]
Is there any way to add html elements on CKEditor 5 like CKEditor 4 version through Source code. Currently Source code is not working properly when I receive edited data from Database  on CKEditor 5 version. Please let me know.

**Comment by Mgsy** [comment]
Hi! First of all, please note that CKEditor 4 and CKEditor 5 have different architecture. CKEditor 5 doesn't have View Source feature, however, we're discussing it [here](https://github.com/ckeditor/ckeditor5/issues/592). 

The most important aspect of CKEditor 5 is a custom data model which accepts only elements allowed in the editor. It means that unrecognized elements (i.e. `<span>`, `<div>`) will be stripped out and converted to a form which is understandable for the editor. 

If you'd like to preserve your content, you have to introduce elements in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and provide a proper [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html). Please, see our [Preserving custom content](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html) guide to learn more.

**Comment by meharoof** [comment]
Thank you so much for your feedback.
