### ISSUE TITLE
Image plugin extensible

### ISSUE THREAD

**Issue by kaluginserg** [ckeditor/ckeditor5#6294]
Image plugin - sometimes can be not fit for custom purpose.
For example: adding custom tags inside figuge tag, or custom attibutes to img tag.
It is often tasks. 
And best approach for that case - extend logic with micro custom plugins. And CKE5 architecture provides api for extending Image with other custom plugins...

But currently Image-plugin in some places in source code - blocking that.
Downcast logic in source code in several places:
```js
const imgView = figureView.getChild( 0 )
```
It found here: `src/image/utils.js` and `src/imageupload/imageuploadediting.js`and here `src/imageupload/imageuploadprogress.js`.
But if we want to extend Image... this code will cause for strange behaviour (for example if we are inserting some tags before the img tag).

In next place there is better approach, that provide ability to extending:
``` js
// Find an image element inside the figure element.
const viewImage = Array.from( data.viewItem.getChildren() ).find( viewChild => viewChild.is( 'img' ) );
```
Found here: https://github.com/ckeditor/ckeditor5-image/blob/0a6902af1d58c192aaccd432ffbb05a5ef1b5675/src/image/converters.js#L38 

I offer update Image plugin in several places with last approach. It can solve many problems (in our cases) with extending Image.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Hi @kaluginserg you get this right and your PR looks also OK - it only needs tests for that change (we can talk about this in the PR).

However, as we just started the release process it will not be included in upcoming release.

**Comment by kaluginserg** [comment]
@jodator - ok, i understood.
About release, maybe you can add this changes into.. let's say minor release: cke5-image@17.0.1 ... ? It would be nice)
