### ISSUE TITLE
Multiple cell selection is (sometimes) lost when it ends beyond the table

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6299]
## 📝 Provide detailed reproduction steps (if any)

![Kapture 2020-02-20 at 16 58 40](https://user-images.githubusercontent.com/1099479/74953721-515df000-5402-11ea-8779-37b1c45f6734.gif)

### ✔️ Expected result

It should lock at the table boundary and remain the same (b<->r).

### ❌ Actual result

Sometimes the selection is lost and collapses to a single cell.

## 📃 Other details

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6113.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
There's a chance that #6114 will fix this issue.

**Comment by Reinmar** [comment]
Fixed along #6114.
