### ISSUE TITLE
Multiple cell selection renders after the editor if there is some content

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6300]
## 📝 Provide detailed reproduction steps (if any)

![Kapture 2020-02-20 at 17 03 35](https://user-images.githubusercontent.com/1099479/74954151-f678c880-5402-11ea-914f-dab9f5982928.gif)

### ✔️ Expected result

It should stay contained in the table.

### ❌ Actual result

Because native DOM selection is not cancelled is expands across other nodes.

## 📃 Other details

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6113.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Let's merge it into #6114.
