### ISSUE TITLE
Multiple cell selection does not get along with enter

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6301]
## 📝 Provide detailed reproduction steps (if any)

![2020-02-20 17 07 06](https://user-images.githubusercontent.com/1099479/74954526-89b1fe00-5403-11ea-8483-fe79508464d1.gif)

### ✔️ Expected result

To be researched (e.g. in popular desktop editors).

### ❌ Actual result

The result is unpredictable.

## 📃 Other details

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6113.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Solution: select the last cell's content and let the current enter algorithm work.

**Comment by Reinmar** [comment]
May be blocked by https://github.com/ckeditor/ckeditor5/issues/6328.
