### ISSUE TITLE
Selected table cells need a solid background

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6302]
This is (I think) a common pattern across text editors (and spreadsheet editors)

### v4

![image](https://user-images.githubusercontent.com/1099479/74955102-6cc9fa80-5404-11ea-8195-9ea7275e0f50.png)

### GDocs

![image](https://user-images.githubusercontent.com/1099479/74955182-8b2ff600-5404-11ea-95f8-34dd5c458525.png)

### LibreOffice

![image](https://user-images.githubusercontent.com/1099479/74955451-f7125e80-5404-11ea-93fd-f53f641549dd.png)

## ATM

![image](https://user-images.githubusercontent.com/1099479/74954871-1492f880-5404-11ea-8081-e8968b084932.png)

## Should be (more or less)

![image](https://user-images.githubusercontent.com/1099479/74954919-28d6f580-5404-11ea-8497-d3ce4876c9dc.png)

## 📃 Other details

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6113.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
From my POV it is a part of: https://github.com/ckeditor/ckeditor5/issues/6114.

**Comment by Reinmar** [comment]
Agree with @jodator
