### ISSUE TITLE
Failing asset build on CodeBlock

### ISSUE THREAD

**Issue by nezaboravi** [ckeditor/ckeditor5#6303]
## 📝 Provide detailed reproduction steps (if any)

yarn add @ckeditor/ckeditor5-code-block
Add in vue component:
import CodeBlock from '@ckeditor/ckeditor5-code-block';

### ✔️ Expected result

Expecting the build to pass and code block visible in cke editor on page

### ❌ Actual result

Build fails with error:
```
ERROR in ./resources/js/components/Forms/Editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/Forms/Editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-code-block' in '/Users/vladimir/Projects/coding-wisely/resources/js/components/Forms'
 @ ./resources/js/components/Forms/Editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/Forms/Editor.vue?vue&type=script&lang=js&) 6:0-55
 @ ./resources/js/components/Forms/Editor.vue?vue&type=script&lang=js&
 @ ./resources/js/components/Forms/Editor.vue
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/main.scss
```
However, it is on the path and exists:
https://www.dropbox.com/s/4dp43sbx34z3qt8/Screenshot%202020-02-21%2012.16.39.png?dl=0

## 📃 Other details
* CKEditor version: 5
Code:
```<script>
    import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
    import CodeBlock from '@ckeditor/ckeditor5-code-block';
    export default {
        name: 'Editor',
        data() {
            return {
                editor: ClassicEditor,
                editorData: '<p>Content of the editor.</p>',
                editorConfig: {
                    toolbar: [ 'bold', 'italic', '|', 'link', '|' ]
                }
            };
        },
    }
</script>`
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. You are trying to add a plugin to an already built editor, which is not possible. To create a customised editor you have to [build it from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source).

P.S.
The error itself comes from wrong import statement, in the future remember to use:
`import CodeBlock from "@ckeditor/ckeditor5-code-block/src/codeblock";`

and then add it to your editor config:
```js
editorConfig: {
        plugins: [ CodeBlock ],
        toolbar: [ "bold", "italic", "|", "link", "|", "codeBlock" ]
      }
```

**Comment by nezaboravi** [comment]
I have done as you suggested. When i add it as /src/codeblock it fials on webpack building on css in some of code-block files, not at computer right now. 
I encourage you to try it by your self, following  code-block documentation (it shall be fixed)
Simple setup, will take you 3 minutes to reproduce.
Install laravel, vue and run yarn install. Add ckeditor as per docuemntation. 
It just takes a lot of efforts since docs on vue i was following is prety confusing.
If you have time. 
:) Thanks for reply tho Filip

**Comment by FilipTokarski** [comment]
I didn't have any problems when adding plugins to [editor built from source in Vue](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source), so probably there might be something wrong with your configuration. It would be helpful to see the error message and your editor configuration. Besides that, [make sure your Webpack configuration is correct](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#configuring-vueconfigjs) and all the plugins you add have the same version.
