### ISSUE TITLE
Table styles do not convey to .ck-content?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6314]
## 📝 Provide detailed reproduction steps (if any)

![image](https://user-images.githubusercontent.com/156149/75145080-95017400-56f8-11ea-8eb2-1898d4ea74ab.png)

### ✔️ Expected result

I'd expect to see a similarly styled table on the right.

### ❌ Actual result

Styles are significantly different.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
AFAICS, it's only about the border in td/th and alignment in th.

**Comment by panr** [comment]
Fix is ready.
