### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Tim-arts** [ckeditor/ckeditor5#6315]
Hi, I have this error and I don't know from where it comes from. I'm using Browserify/Babelify with the preset-env. When the server starts and tries to compile the impacted file, it fails because of the "font" module.
There is a little snippet of code:

```
import Ckeditor from "@ckeditor/ckeditor5-build-classic";
import CkeditorFrLanguage from "@ckeditor/ckeditor5-build-classic/build/translations/fr";
import CkeditorFont from "@ckeditor/ckeditor5-font/src/font"; <-- Fails here

let CkeditorEnConstructor = Ckeditor.create(document.getElementById("news-en"), {
        toolbar: [
            "heading", "|", "fontFamily", "bold", "italic", "link", "bulletedList", "numberedList", "|", "indent", "outdent", "|",
            "imageUpload", "mediaEmbed", "blockQuote", "ckfinder", "|", "imageStyle:full", "imageStyle:side", "|",
            "insertTable", "tableColumn", "tableRow", "mergeTableCells", "|", "undo", "redo"
        ],
        language: {
                ui: "en"
            }
        })
        .then(editor => {
            return editor;
        });
```

And in my package.json:
`"browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "@babel/preset-env"
          ]
        }
      ]
    ]
  },`

### ✔️ Expected result

Babel compilation success.

### ❌ Actual result

Babel compilation fails with **SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'**

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 5 latest
* Installed CKEditor plugins: none

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Please first be sure to follow our docs on [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and [building editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html).
If you then still encounter any problems, it would be helpful to know exact steps to reproduce the issue, editor configuration, error messages, etc.
