### ISSUE TITLE
CKEditor 5 stop converting custom data model

### ISSUE THREAD

**Issue by meharoof** [ckeditor/ckeditor5#6318]
Is there any way to stop converting custom data model on CKEditor 5 without using [Preserving custom content](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html). Actually, we need to add custom attributes and tags on  CKEditor 5. Currently it's converting into CKEditor 5 custom data model while saving into DB. Thanks in advance.

**Comment by Mgsy** [comment]
Hi! As you mentioned, CKEditor 5 operates on a custom data model and it is a part of its architecture. There's no way to change it. The editor understands and converts only recognized elements, so if you'd like to keep your custom attributes and tags, you have to register them in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and provide a proper [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html). The guide you've mentioned is a good example showing the whole process.

**Comment by meharoof** [comment]
Thanks you so much for replying.
