### ISSUE TITLE
"View Source" functionality / plugin #592

### ISSUE THREAD

**Issue by isaacSolano** [ckeditor/ckeditor5#6321]
## 📝 Provide a description of the new feature
View source html code option
_What is the expected behavior of the proposed feature?_
To open like a textarea element with the html tags of the data written on the editor
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report, we're aware that this feature is highly requested by our community and there's already a discussion about it in a proper ticket - https://github.com/ckeditor/ckeditor5/issues/592.
