### ISSUE TITLE
list items is replaced with heading tag and  <li> tag is replaced when ever try to use heading inside the <li> tag

### ISSUE THREAD

**Issue by irshadalijan** [ckeditor/ckeditor5#6322]
## 📝 Provide detailed reproduction steps (if any)

1. Created list item
2. Selected heading to make `<li>` tag with proper heading tag
3. It changes to heading tag and replaces `<li>` tag
Checkout the attached gif.

### ✔️ Expected result

`<li>` tags should be preserved and not replaced with heading tags. In fact heading tags should be inside `<li>` tag like it worked in ckeditor 4 but in ckeditor 5 its not working.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10339478/75220713-a1f29600-57d2-11ea-8d10-4870a5572d37.gif)

**Comment by Reinmar** [comment]
This is by design and how many modern editors (focused on semantic content) work.

A feature that would allow having blocks inside list items is #2973.
