### ISSUE TITLE
Add a warning to all demos that pasting from Word/GDocs should be tested in a particular demo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6324]
## 📝 Provide a description of requested docs changes

The issue: most people expect for the formatting to be maximally preserved when testing pasting from Word.

In most of our demos we enable a minimal number of features (usually none formatting ones). Hence, styling is lost.

We should automatically detect that one is pasting from Word/GDocs and show a nice warning that pasting in this demo may not work as expected and give a link to the Word/GDocs guides (where we have many features enabled and configured).

---

From the technical perspective, the easiest way to plug this behaviour automatically to all editors on a page would be to do something like:

```js
setTimeout( () => {
     const editables = document.queryElementAll( '.ck-content' );
     
    editables.forEach( editable => {
        if ( !editable.ckeditorInstance ) return;

        editable.ckeditorInstance.plugins.get( 'Clipboard' ).on( 'clipboardInput', ... );
     } );
}, 3000 );
```

This code should be included in one of the assets that loaded on **all** our test pages. I presume that Umberto support such things.

**Comment by Reinmar** [comment]
@pomek, where do you think we could place this bit of logic?

**Comment by pomek** [comment]
I guess we can use [/docs/asset/snippet.js](https://github.com/ckeditor/ckeditor5/blob/4fbc3ae0abd9c7ce6babef8352a3534ddc99facb/docs/assets/snippet.js) file.

**Comment by Reinmar** [comment]
@panr, you can find PFW, PFGDocs regexps in `mswordnormalizer.js` and `googledocsnormalizer.js`.

**Comment by panr** [comment]
PR is ready for a review.

**Comment by panr** [comment]
Just added requested changes and created another PR for the `window.preventPasteFromOfficeNotification` variable.
