### ISSUE TITLE
Font Size Increase in Bold plugin

### ISSUE THREAD

**Issue by shakthifuture** [ckeditor/ckeditor5#6327]
Hi Team,

How to increase font size in the "Bold" plugin? I am customizing the [https://github.com/ckeditor/ckeditor5-basic-styles] bold plugin library, is there any way to change the font size?

Thank you.

**Comment by FilipTokarski** [comment]
Hi, if you want to change font size, please refer to [Font plugin docs](https://ckeditor.com/docs/ckeditor5/latest/features/font.html).
