### ISSUE TITLE
There's no way to edit SVG files in the project because they are "overcompressed"

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6334]
## Provide a description of the task

Check out what `link.svg` looks like when opened in Sketch:

![image](https://user-images.githubusercontent.com/1099479/75354326-1437a900-58ad-11ea-91fa-38d33c499e94.png)

(similar results in other graphic editors). 

This is because of our aggressive `clean-up-svg-icons` task squeezes every byte of the SVG files using every technique available and SVG editors don't handle this well on the input (FYI it looks ok in the browser).

Unless we have these icons stored somewhere locally (or retrieved from the git history) there's no way to edit and improve them. Or copy and use as a base for future icons.

We need to either:
* find some way to decompress the icons (unlikely to happen),
* store and maintain a sketch file with icons for everyone to use,
* store raw (uncompressed) SVG icons somewhere else (in parallel to compressed ones).

cc @panr @dkonopka @Reinmar

**Comment by panr** [comment]
Well done! We should call our compressor `Picasso` ;-D

**Comment by oleq** [comment]
Related https://github.com/svg/svgo/issues/1164 and https://github.com/svg/svgo/issues/1137.

**Comment by oleq** [comment]
Looks like the following helps:
```diff
diff --git a/scripts/svgo.config.json b/scripts/svgo.config.json
index a5ba4161..dd238555 100644
--- a/scripts/svgo.config.json
+++ b/scripts/svgo.config.json
@@ -3,8 +3,9 @@
                   "collapseGroups",
                   "removeDimensions",
                   { "removeAttrs": { "attrs": "(fill|stroke|fill-rule)" } },
+                  { "convertPathData": { "noSpaceAfterFlags": false } },
                   "removeTitle",
                   "removeComments",
                   "removeMetadata"
          ]
-}
\ No newline at end of file
+}
```

**Comment by panr** [comment]
I can confirm. Fix works fine! 🎉

**Comment by oleq** [comment]
I created a [PR](https://github.com/ckeditor/ckeditor5/pull/6336). It solves the technical aspect and brings mangled icons back to life but we may not be that lucky next time. Let's discuss the way we store, share and develop editor resources like Sketch files.

**Comment by oleq** [comment]
Re-opening because of

> Let's discuss the way we store, share and develop editor resources like Sketch files.

**Comment by panr** [comment]
Are you sure? This is a good followup to the issue. I would close it and open a new one.

**Comment by oleq** [comment]
Alright, please a new one and put some reference to this one.
