### ISSUE TITLE
The selection moves outside a table after selecting multiple cells

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6340]
## 📝 Provide detailed reproduction steps (if any)

1. Go to http://localhost:8125/ckeditor5-table/tests/manual/tableselection.html.
2. In the first editor select a few cells.

### ✔️ Expected result

Only table cells are selected.

### ❌ Actual result

The text below the table is also selected.

## 📃 Other details

* The model selection is correct

![bug_cke5](https://user-images.githubusercontent.com/20988892/75426977-f407f880-5945-11ea-8834-ec7c208e04c9.gif)

* Browser: Chrome, Edge
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
We wanted to keep it as a part of https://github.com/ckeditor/ckeditor5/issues/6114.
