### ISSUE TITLE
Search and Replace text with big document

### ISSUE THREAD

**Issue by lingamwin** [ckeditor/ckeditor5#6342]
Provide the best way to implement 'Find and Replace' feature
We tried with existing highlight plugin, but it getting slowness while searching 
What is best way to parse the document more than 500 pages?

**Comment by Mgsy** [comment]
Hi! Thanks for the report. CKEditor 5 isn't a tool which should handle such a big amount of content. Our team is constantly improving the editor performance, however, it will never be able to handle 500+ pages. 

We advise loading smaller chunks of the text instead of working on the whole 500+ pages document. Using the editor this way is more effective and allows to avoid such performance issues. This is how our customers use the editor and we recommend you the same.

**Comment by lingamwin** [comment]
@Mgsy Thanks for your response. What is the best way to implement 'Find and Replace' feature ?

**Comment by Mgsy** [comment]
Probably the best way to implement it will be using [Markers](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_markercollection-Marker.html) and [`TreeWalker`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html#function-getWalker). 

However, currently, it might be difficult without API allowing [marking keywords](https://github.com/ckeditor/ckeditor5/issues/1257).

**Comment by ejwill04** [comment]
@Mgsy - I'm attempting to implement find and replace using your suggestions regarding using Markers and TreeWalker.  I'm adding a mark using `writer.addMarker`.  I then have a `downcast` for the `addMarker` that wraps each marker in a `mark` with a class.  However, this ultimately modifies the HTML coming from `editor.getData()`.  Is there an approach that wouldn't modify `editor.getData()`?  I don't want to store the class or pollute the HTML. Thanks in advance!

**Comment by Mgsy** [comment]
Hi @ejwill04. You can control the data produced by `editor.getData()` by defining `dataDowncast` conversion.

```js
// Add a converter to the data pipepline only:
editor.conversion.for( 'dataDowncast' ).elementToElement( dataConversionConfig ) );
```

**Comment by ejwill04** [comment]
> Hi @ejwill04. You can define the conversion only for the editing area, so all `mark` elements will be visible only in the editing view.
> 
> ```js
> // Add a converter to the editing only:
> editor.conversion.for( 'editingDowncast' ).elementToElement( editingConversionConfig ) );
> ```
> 
> Also, if you'd like to define how the element should be represented in HTML returned by the editor (i.e. using `editor.getData()`), you can use `dataDowncast` conversion:
> 
> ```js
> // Add a converter to the data pipeline only:
> editor.conversion.for( 'dataDowncast' ).elementToElement( dataConversionConfig ) );
> ```

Thanks for this feedback @Mgsy.  It was helpful!

**Comment by antoniolucasnobar** [comment]
Dear @ejwill04 ,
have you ever been able to implement such plugin. Could you please share the code? I need something like the [Find/Replace](https://ckeditor.com/cke4/addon/find) plugin in CKEditor 4 and any help is welcome.

thanks in advance.
A. Lucas

**Comment by ejwill04** [comment]
> Dear @ejwill04 or @lingamwin ,
> have you ever been able to implement such plugin. Could you please share the code? I need something like the [Find/Replace](https://ckeditor.com/cke4/addon/find) plugin in CKEditor 4 and any help is welcome.
> 
> thanks in advance.
> A. Lucas

Hi @antoniolucasnobar 

The approach I ended up taking was to wrap the incoming HTML with spans and a classname based on the search.  These spans and classnames were added before the content gets to CKEditor.  I then created a simple plugin in CKEditor that could persist the classname.

**Comment by antoniolucasnobar** [comment]
thank you @ejwill04 for so quick response. Sadly, I thinkl my needs are different from yours. I am still a little confused about ckeditor5.

I was able to check all chunks that have the search word, but I was not able to change the text  (replace for the new). I was not able even to highlight the text I found. 
```js
editor.model.change( writer => {
    const range = editor.model.createRangeIn( editor.model.document.getRoot() );
    // Iterate over all items in this range:
    for (const value of range.getWalker()) {
        const item = value.item;
        //how to check if it is a node with text?
        if (item.data && item.data.includes(searchString)) {
            console.log(value.item);
            // is there a way to highlight the current range? 
            // The command below highlight the current selecion on text.
            editor.execute( 'highlight', { value: 'yellowMarker' } );
            // I do not know where I put the current range to highlight
            editor.conversion.for( 'downcast' ).markerToHighlight( 
                      { model: 'comment', view: { classes: 'comment' } } );
            // I tried this, but it has no effect
            item.data = item.data.replaceAll(searchString, "foobar");
            // this gives me a error    
            // writer.addMarker( 'search:' + searchString, { range, usingOperation: false } );
        }
    }
```

Nevertheless, I was able to make a plugin to replace text, getting the text using `editor.getData()`,  using replace (or replaceAll) in the string and finally, using `editor.setData()` to set the text back to the view. 
It works, but I think this is not the right way to do it.
Below is the code I used to replace text. I had to use the SweetAlert because I do not know where to put HTML to render the modal. It is inconvinent, because it closes after the first substitution:

```js
class ReplaceText extends Plugin {
    init() {
        const editor = this.editor;
        editor.ui.componentFactory.add( 'replaceText', locale => {
            const view = new ButtonView( locale );
            view.set( {
                label: 'Substituir Texto',
                icon: replaceTextIcon,
                tooltip: true
            } );
            // Callback executed once the button is clicked.
            view.on( 'execute', () => {
               Swal.fire({
                    title: 'Substituir texto',
                    confirmButtonText: 'Substituir',
                    html:
                      '<label for="swal-input1">Localizar</label>' +
                      '<input id="swal-input1" class="swal2-input">' +
                      '<label for="swal-input2">Substituir por</label>' +
                      '<input id="swal-input2" class="swal2-input">' + 
                      '<label for="swal-input2">Substituir tudo?</label>' +
                      '<input type="checkbox" id="swal-input3">' 
                      ,
                    focusConfirm: false,
                    preConfirm: () => {
                      return [
                        document.getElementById('swal-input1').value,
                        document.getElementById('swal-input2').value,
                        document.getElementById('swal-input3').checked
                      ]
                    }
               }).then((formValues) => {
                   if (formValues && formValues.isConfirmed) {
                       editor.model.change(writer => {
                           console.log(formValues);
                           console.log(formValues.value[0]);
                           console.log(formValues.value[1]);
                           if (formValues.value[2]) {
                               editor.setData(editor.getData().replaceAll
                                (formValues.value[0], formValues.value[1]));
                           } else {
                               editor.setData(editor.getData().replace
                                 (formValues.value[0], formValues.value[1]));
                           }
                        });
                   }
               });
            } );
            return view;
        } );
    }
}
```

**Comment by parthiban1781** [comment]
Hi!, I'm trying to do the find and replace(custom code, not going to use the existing plugin) functionality in ckeditor5, Please suggest the approach to do the same or share the sample source if anything.

**Comment by nawein** [comment]
I hope this message finds you well. I wanted to bring to your attention a performance issue we've encountered while using the find and replace function in our application's multi-root editor.

The problem arises from the fact that we are currently comparing all the root data when executing the find and replace function. This process becomes inefficient, especially when dealing with larger datasets, as it leads to a noticeable lag in performance.

Our current approach involves comparing all root data, and upon detecting a change, we save the modified data back to the backend. However, we recognize the need to optimize this process by identifying the specific rootname where the data has been altered during the replace operation.

Could you please provide guidance or suggestions on how we can enhance our implementation to pinpoint the specific rootname where the data change occurs during the replace operation? This optimization would greatly improve the efficiency and responsiveness of our application.
