### ISSUE TITLE
node modules not found and failed to compile

### ISSUE THREAD

**Issue by kailaskadam** [ckeditor/ckeditor5#6344]
## 📝 Provide detailed reproduction steps (if any)

1. …npm install @ckeditor/ckeditor5-track-changes
2. …import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import TrackChanges from '@ckeditor/ckeditor5-track-changes/src/trackchanges';
3. …// Plugins to include in the build.
ClassicEditor.builtinPlugins = [ TrackChanges ];

// The editor configuration.
ClassicEditor.defaultConfig = {
    language: 'en'
};

### ✔️ Expected result
it should show the CKeditor with track changes.
_What is the expected result of the above steps?_

### ❌ Actual result
./node_modules/@ckeditor/ckeditor5-collaboration-core/theme/users.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@ckeditor/ckeditor5-collaboration-core/theme/users.css)
Module not found: Can't resolve './@ckeditor/ckeditor5-ui/theme/mixins/_unselectable.css' in 'D:\unicef-impact\uac\node_modules\@ckeditor\ckeditor5-collaboration-core\theme'

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …chome
* OS: …win10
* CKEditor version: …5
* Installed CKEditor plugins: …track changes

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. First of all, you're trying to add a plugin directly to the build which is not correct. Please, see our [Installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) guide to learn more. 

Also, as Track Changes is our commercial plugin and this issue tracker concerns open-source side of the project, in case of any problems, please contact us directly through [our support channel](https://ckeditor.com/contact/), so we'll be able to analyse and solve your issue more efficiently.

**Comment by kailaskadam** [comment]
Hi Mgsy, Thanks for the reply

now i have followed the installing plugins guide but getting new issue.
![Ckeditor](https://user-images.githubusercontent.com/1982795/75457812-f187bc00-59a2-11ea-9b7a-ce4faf1f46e5.PNG)

Below are steps:-
1.npm install --save @ckeditor/ckeditor5-react
2.git clone -b stable https://github.com/ckeditor/ckeditor5-build-classic.git ckeditor5-with-track-changes
3.cd ckeditor5-with-track-changes
4.npm install
5.npm install --save-dev @ckeditor/ckeditor5-track-changes
6.Then updated the src/ckeditor.js file
7. Added the below lines in src/ckeditor.js
import TrackChanges from '@ckeditor/ckeditor5-track-changes/src/trackchanges';
also added the track changes inside editor configuration toolbar section.
8.npm run build
9.Importing build in my component 
example
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from "../../../vendor/ckeditor5-build-classic/build/ckeditor";

export default function FormComponent() {
    return (
 <CKEditor
                            onInit={ editor => {
                                editor.execute( 'trackChanges' );

                              //  this.setState( { editor } );

                                console.log( 'Editor is ready to use!', editor );

                               // this.refreshDisplayMode();
                            } }
                            onChange={ ( event, editor ) => console.log( { event, editor } ) }
                            editor={ ClassicEditor }
                            config={ {
                                licenseKey: ""
                            } }
                            data={<p>Ckeditor 5 with track changes</p> }
                        />
)
}

When i am running my app it throwing me the error
index.js:1 ./src/vendor/ckeditor5-build-classic/build/ckeditor.js
  Line 5:1:       Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 5:2089:    'define' is not defined                                                no-undef
  Line 5:2100:    'define' is not defined                                                no-undef
  Line 5:2481:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 5:3160:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 5:3269:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 5:3804:    Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by Mgsy** [comment]
If you're using React, please see [our guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) to learn how to integrate CKEditor 5 in React. Also, you can take a look at our [Track Changes for React](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/track-changes-for-react) example to see the whole implementation with Track Changes.

**Comment by kailaskadam** [comment]
As per my understanding i followed the steps to integrate the editor into React.

Also following the same structure when i make build inside the vendor folder and run my application 
then it throws the error.

**Comment by Mgsy** [comment]
As I can see, you've placed your custom build inside `src` directory:
```
index.js:1 ./src/vendor/ckeditor5-build-classic/build/ckeditor.js
```
React scripts compiles everything inside `src`, so it also tries to compile your CKEditor 5 build and it throws.

To solve this issue, you should move `vendor` directory outside of `src`. However, React scripts might complain about importing a package which isn't in `src` directory, so I'll suggest doing the following:

1. In `vendor/ckeditor5-with-track-changes/package.json` change a name to `ckeditor5-with-track-changes`
2. In your main `package.json` add the following dependency:
```json
"dependencies": {
    "ckeditor5-with-track-changes": "file:./vendor/ckeditor5-with-track-changes",
}
```
3. Run `npm install`.
4. Import the build in your app:
```js
import ClassicEditor from 'ckeditor5-with-track-changes';
```

It will install your local build in `node_modules`, so you'll be able to import it. After that, there should be no problem with running your project.
