### ISSUE TITLE
Selecting a table cell (or cells) through a model does not render a nice table selection

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6346]
## 📝 Provide a description of the improvement

So. we not only have to handle selection done by the mouse, but also programmatically through the model. This will e.g. fix the undo which is not able to select cells right now.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
One thing is this check: https://github.com/ckeditor/ckeditor5-table/blob/3a2e025b7d3132a603d3bd5d814f76f8a5e1bf54/src/tableselection/converters.js#L24 and the `TableSelection.hasMultipleCellSelection` is used in various places.

The `TableSelection` does not restore or handle selection set elsewhere (ie by the model modification elsewhere).

This might require:
1. change for this check
2. how the `TableSelection` returns `getSelectedTableCells`

**Comment by Reinmar** [comment]
It may be worth resolving https://github.com/ckeditor/ckeditor5/issues/6347 when working on this issue.

**Comment by jodator** [comment]
Check also: https://github.com/ckeditor/ckeditor5/issues/6353.
