### ISSUE TITLE
Expected an assignment or function call and instead saw an expression no-unused-expressions

### ISSUE THREAD

**Issue by kailaskadam** [ckeditor/ckeditor5#6349]
## 📝 Provide detailed reproduction steps (if any)

1.npm install --save @ckeditor/ckeditor5-react
2.git clone -b stable https://github.com/ckeditor/ckeditor5-build-classic.git ckeditor5-with-track-changes
3.cd ckeditor5-with-track-changes
4.npm install
5.npm install --save-dev @ckeditor/ckeditor5-track-changes
6.Then updated the src/ckeditor.js file
7. Added the below lines in src/ckeditor.js
import TrackChanges from '@ckeditor/ckeditor5-track-changes/src/trackchanges';
also added the track changes inside editor configuration toolbar section.
8.npm run build
9.Importing build in my component
example
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from "../../../vendor/ckeditor5-build-classic/build/ckeditor";

export default function FormComponent() {
return (
<CKEditor
onInit={ editor => {
editor.execute( 'trackChanges' );

                          //  this.setState( { editor } );

                            console.log( 'Editor is ready to use!', editor );

                           // this.refreshDisplayMode();
                        } }
                        onChange={ ( event, editor ) => console.log( { event, editor } ) }
                        editor={ ClassicEditor }
                        config={ {
                            licenseKey: ""
                        } }
                        data={<p>Ckeditor 5 with track changes</p> }
                    />
)
}

### ✔️ Expected result
Ckeditor should be displayed with track changes feature.
_What is the expected result of the above steps?_

### ❌ Actual result
ndex.js:1 ./src/vendor/ckeditor5-build-classic/build/ckeditor.js
Line 5:1: Expected an assignment or function call and instead saw an expression no-unused-expressions
Line 5:2089: 'define' is not defined no-undef
Line 5:2100: 'define' is not defined no-undef
Line 5:2481: Expected an assignment or function call and instead saw an expression no-unused-expressions
_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …Chrome
* OS: …windows10
* CKEditor version: …5
* Installed CKEditor plugins: …
Track Changes
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Please, don't open new issues for problems discussed in another ticket. I've answered you in the original one - https://github.com/ckeditor/ckeditor5/issues/6344. I'll close it as a duplicate.
