### ISSUE TITLE
Adding Bookmark Plugin 

### ISSUE THREAD

**Issue by BoopathySrinivasan** [ckeditor/ckeditor5#6350]
I'm trying to add bookmark plugin in the toolbar with the reference of the below URL
https://www.npmjs.com/package/ckeditor5-bookmark.

But It throws below error 
ERROR Error: Uncaught (in promise): CKEditorError: CKEditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

In the node modules, there is a separate folder for the ckeditor5-bookmark with version 1.0.3.

**Comment by Mgsy** [comment]
Hi! The mentioned plugin is not an official plugin created by our team, so in case of any problems, you should contact the plugin maintainer.

**Comment by BoopathySrinivasan** [comment]
Thanks for the response @Mgsy!!  Is there any other way to add bookmark as a plugin in the CK editor. Because our objective is to create a bookmark for an image/chart or any words present in the document and refer those bookmarks in some other area on the same document.

**Comment by Mgsy** [comment]
Currently, we don't have any plans to introduce such a plugin, however, you can create it on your own. Please, see our [Creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) guide, then read about [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and [Conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html).
