### ISSUE TITLE
Table MouseSelectionHandler should reset its #isSelecting flag on mouseup

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6353]
## 📝 Provide detailed reproduction steps (if any)

It [sets the flag `true`](https://github.com/ckeditor/ckeditor5-table/blob/d498df44a424147a04147bc08ff8503baa421b60/src/tableselection/mouseselectionhandler.js#L85) but never `false` during its lifecycle.

This could potentially affect the selection logic.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Closed with ckeditor/ckeditor5-table@516ba8c.
