### ISSUE TITLE
Introduce a common "get selected cells" util in src/utils.js

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6358]
## 📝 Provide a description of the improvement

Right now we have:

*   `getSelectedTableCells` in `tablecellpropertycommand.js`,
*   `getSelectedTableCells` in `tableselection.js` (which is invalid as it's only reasonable to be used while the selection is being made – hence, it should be a private util).

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
> *   `getSelectedTableCells` in `tablecellpropertycommand.js`,

The implementation of this function is naive, and the function to be introduced should not work like this. The aformentioned implementation returns the same cell multiple times. The table cell props form works only because the value is deduped later on (in `getSingleValue()`).

**Comment by Reinmar** [comment]
Related ticket: #6364.

**Comment by oleq** [comment]
What about https://github.com/ckeditor/ckeditor5-table/blob/7749fc82e0e3670d6817aff151ef45b8202682e7/src/tableselection/utils.js#L39-L52?

**Comment by Reinmar** [comment]
ckeditor/ckeditor5-table#263 introduced a new function (plugin method) for getting selected cells (from the model document selection).
