### ISSUE TITLE
Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated

### ISSUE THREAD

**Issue by ighmouraceneb** [ckeditor/ckeditor5#6359]
Hi, 

I want to add font-size to the toolbar of ckeditor5-build-balloon but it shows me this error 
Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

### ❌ Actual result

_ckeditorerror.js:66 Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules_

## 📃 Other details

I import in component : 
import * as BalloonEditor from '@ckeditor/ckeditor5-build-balloon';
import { CloudinaryImageUploadAdapter } from 'ckeditor-cloudinary-uploader-adapter';
import Font from '@ckeditor/ckeditor5-font/src/font';

 Editor = BalloonEditor;
editorConfig = {
    
     plugins: [ Font],
       fontSize: {
      options: [
          9,
          11,
          13,
          'default',
          17,
          19,
          21
      ]
    },
     toolbar: [ 'fontSize', ]
  };

* Angular : 8.3.25
* Browser: chome
* OS: W10
* CKEditor version:5
* Installed CKEditor plugins: @ckeditor/ckeditor5-font/src/font

---

**Comment by ighmouraceneb** [comment]
it's ok from me => https://github.com/ckeditor/ckeditor5/issues/6296#issuecomment-589549023

**Comment by arucastillo** [comment]
Hey, can you help me, I have the same problem, but I don't understand really well the documentation?

**Comment by ighmouraceneb** [comment]
in order to add plugins to an editor it must be installed otherwise:
1) go to the cd node_modules / @ ckeditor folder
2) clone the editor from git
git clone -b stable https://github.com/ckeditor/ckeditor5-build-classic.git
cd ckeditor5-build-classic
npm install
3) Now install the plugin
4) Edit the src / ckeditor.js file by importing the plugin and adding it to the list of plugins and in the config toolbar
5) import the editor into your component and voila and don't forget to uninstall all the editors that are already installed
You can see on this link for more details: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html

**Comment by ronit-mukherjee** [comment]
Best way I would suggest is to use - [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/ )

**Comment by Thanhky30** [comment]
1
