### ISSUE TITLE
Introduce Range#getContainedElement()

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6364]
### 📝 Provide a description of the new feature

PRs like https://github.com/ckeditor/ckeditor5-table/pull/258/files and lots of other code that I've seen recently shows that we need such a method.

We need it in the model and in the view.

The second part of this issue is to clean up existing code, especially in ckeditor5-table. I think that it may be hard to scan our entire code base for those things, but looking got phrases like "get\\w+element" may help. But this is not a priority to change all that now.

Strongly connected with: #6358.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
I reviewed the codebase and I saw no use cases for such a method View Range. This kind of check is used only in `(View)Selection#getSelectedElement()`.
