### ISSUE TITLE
EasyImage or upload image with ckEditor and vuetify

### ISSUE THREAD

**Issue by YoussefAlmardini** [ckeditor/ckeditor5#6365]
## 📝 Provide detailed reproduction steps (if any)

1.i would like simply to upload image in my classic editor
2.i tried to install plugin but it not works.
3. either i have duplicated package   in case of (upload adapter) or can not resolve the package EasyImage in case of( easy image) 

### ✔️ Expected result

Image is uploaded successfully

### ❌ Actual result

ERRORS!!!

## 📃 Other details
My simple code: ckeditor.js

`<template>
  <v-container>
       <ckeditor 
        :editor="editor" 
        v-model="editorData" 
        :config="editorConfig"
       ></ckeditor>
  </v-container>
</template>

<script>

  import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
  import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';

  export default {

    name: 'ckEditor',

    data: () => ({

        editor: ClassicEditor,
        editorData: '<p>Content of the editor.</p>',
        editorConfig: {
            plugins:[EasyImage],
        }    
    }),

    mounted(){

    },

    methods:{
        clear(){
            this.editorData = '';
        }
    }
  }
</script>
`

main.js

`import Vue from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify';
import CKEditor from '@ckeditor/ckeditor5-vue';

Vue.config.productionTip = false
Vue.use( CKEditor );

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')
`

npm v  6.11.3
ckeditor v 5
@vue/cli 4.1.2

help :(

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. First of all, you are trying to add a plugin to an already existing build, which won't work. Please refer to our [Vue.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source) on how to add a custom editor to your Vue app. You can also read more about [how to install plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).
  
Secondly, if you are sure that your integration is correct and you are still getting `duplicated modules` error, please make sure that all the plugins you installed have the same version ( currently it is 17 ).   
  
If you are using Simple Upload Adapter, please refer to the docs, on [how to set up both client and server side](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html). This plugin needs both configurations to work properly.
  
Last but not least, if you are using Easy Image, please refer to the docs on [how to set it up properly](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/easy-image.html). It's a commercial plugin, therefore you need to use our [Cloud Services](https://ckeditor.com/ckeditor-cloud-services/) solution. Here you can find [Cloud Services docs](https://ckeditor.com/docs/cs/latest/guides/overview.html). If you are already a registered user, you can always [contact our support](https://ckeditor.com/contact/).
  
Hope that helps!

P.S.
If you are sure all the above information, steps you followed and all configurations are correct, and you are still getting errors, it would be helpful to see your editor configuration and error messages.

**Comment by YoussefAlmardini** [comment]
Thanks @FilipTokarski 

Now after taking another look at documentation i can finally upload a photo in my vue-cli project! with those steps:

1-installing configuring packages:

`npm install --save \
    @ckeditor/ckeditor5-vue \
    @ckeditor/ckeditor5-dev-webpack-plugin \
    @ckeditor/ckeditor5-dev-utils \
    postcss-loader@3 \
    raw-loader@0.5.1
`

2-edit my vue.config.js file:

`const path = require( 'path' );
const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' );
const { styles } = require( '@ckeditor/ckeditor5-dev-utils' );

module.exports = {
    // The source of CKEditor is encapsulated in ES6 modules. By default, the code
    // from the node_modules directory is not transpiled, so you must explicitly tell
    // the CLI tools to transpile JavaScript files in all ckeditor5-* modules.
    transpileDependencies: [
        /ckeditor5-[^/\\]+[/\\]src[/\\].+\.js$/,
        "vuetify"
    ],

    configureWebpack: {
        plugins: [
            // CKEditor needs its own plugin to be built using webpack.
            new CKEditorWebpackPlugin( {
                // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
                language: 'en'
            } )
        ]
    },

    // Vue CLI would normally use its own loader to load .svg and .css files, however:
    //	1. The icons used by CKEditor must be loaded using raw-loader,
    //	2. The CSS used by CKEditor must be transpiled using PostCSS to load properly.
    chainWebpack: config => {
        // (1.) To handle editor icons, get the default rule for *.svg files first:
        const svgRule = config.module.rule( 'svg' );

        // Then you can either:
        //
        // * clear all loaders for existing 'svg' rule:
        //
        //		svgRule.uses.clear();
        //
        // * or exclude ckeditor directory from node_modules:
        svgRule.exclude.add( path.join( __dirname, 'node_modules', '@ckeditor' ) );

        // Add an entry for *.svg files belonging to CKEditor. You can either:
        //
        // * modify the existing 'svg' rule:
        //
        //		svgRule.use( 'raw-loader' ).loader( 'raw-loader' );
        //
        // * or add a new one:
        config.module
            .rule( 'cke-svg' )
            .test( /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
            .use( 'raw-loader' )
            .loader( 'raw-loader' );

        // (2.) Transpile the .css files imported by the editor using PostCSS.
        // Make sure only the CSS belonging to ckeditor5-* packages is processed this way.
        config.module
            .rule( 'cke-css' )
            .test( /ckeditor5-[^/\\]+[/\\].+\.css$/ )
            .use( 'postcss-loader' )
            .loader( 'postcss-loader' )
            .tap( () => {
                return styles.getPostCssConfig( {
                    themeImporter: {
                        themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' ),
                    },
                    minify: true
                } );
            } );
    }
};`

3- create acount via [](https://ckeditor.com/ckeditor-cloud-services/)
to get upload URL and tokenURL ( those are needed in case of using easyImage ).


4- install my plugins and import them in my Vue component:

`import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

  import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
  import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
  import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
  import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
  import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
  import Image from '@ckeditor/ckeditor5-image/src/image';
  import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
  import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
  import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
  import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
  import Link from '@ckeditor/ckeditor5-link/src/link';
  import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
  import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';


  export default {
    
    name: 'HelloWorld',

    data: () => ({
     
   
    }),

    mounted(){
      ClassicEditorBase
      .create( this.$refs['editor'], {
          plugins: [
             Bold,
             Italic,
             Essentials,
             Image,
             EasyImage,
             ImageUpload,
             ImageToolbar,
             ImageStyle,
             ImageResize,
             Autoformat,
             Paragraph,
             Link,
             TextTransformation
          ],

          cloudServices: {
            uploadUrl: 'https://69582.cke-cs.com/easyimage/upload/',
            tokenUrl: 'https://69582.cke-cs.com/token/dev/n5YcB30VclqPBnWpENRHGrWg8ruD4cnkRf1wZPj1ozOU9dRr2wkbriW8zd9o'
          },
            
          toolbar: [ 'bold', 'italic', 'alignment','imageUpload','link'],
          image: {
              toolbar: [ 'imageTextAlternative', '|', 'imageStyle:full', 'imageStyle:side' ]
          }

      } )
      .then( editor => {
          console.log( 'Editor was initialized', editor );
      } )
      .catch( error => {
          console.error( error.stack );
      } );
    }
  }`

And it works ! 
![image](https://user-images.githubusercontent.com/32193161/76524949-43344a00-646b-11ea-8239-c2aaeb717454.png)

I only want to ask one question, i cannot position an image next to text so they have a kind of display:block, and am looking to display image and text as felx next to eachothers. how?

**Comment by FilipTokarski** [comment]
You can refer to our [docs on image styles](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-styles) and [responsive images](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#responsive-images).
