### ISSUE TITLE
Renderer#_updateChildren fails when DOM element is "moved back"

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#6367]
## 📝 Provide detailed reproduction steps (if any)

Sorry for an ambigous title but it is hard to explain it properly. Following case throws error in track changes feature:

1.  Connect two clients to an empty document. Client A should have track changes off, client B should have track changes on.
2.  At the same time write a letter on both clients. Write a little sooner on a client with track changes on.
3.  Editor crashes in `Renderer#_updateChildren()`

Following happens:

```js
const diff = this._diffNodeLists( actualDomChildren, expectedDomChildren );

let i = 0;
const nodesToUnbind = new Set();

for ( const action of diff ) {
    if ( action === 'insert' ) {
        insertAt( domElement, i, expectedDomChildren[ i ] );
        i++;
    } else if ( action === 'delete' ) {
        nodesToUnbind.add( actualDomChildren[ i ] );
        remove( actualDomChildren[ i ] );
    } else { // 'equal'
        // Force updating text nodes inside elements which did not change and do not need to be re-rendered (#1125).
        this._markDescendantTextToSync( this.domConverter.domToView( expectedDomChildren[ i ] ) );
        i++;
    }
}
```

This is a part of `_updateChildren()`.

`actualDomChildren` is `#text` , `<span*>`  
`expectedDomChidren` is `<span*>`, `#text`, `<span>`  
`diff` is `insert`, `equal`, `insert`, `delete`

So far so good.

The problem is that the spans with `*` are literally the same DOM element, while `actualDomChildren` is a reference to the node list, so it gets updated by `insertAt()`.

Now, what happens when the first `insert` from `diff` is handled?

`actualDomChildren` becomes `<span*>`, `#text` instead of `<span*>`, `#text`, `<span*>`. This later causes a throw because last `delete` action is on non-existing index (because `<span*>` was moved, not copied).

**Comment by Reinmar** [comment]
DUP of #6092.
