### ISSUE TITLE
Merge cell left/right options are never enabled

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6368]
## 📝 Provide detailed reproduction steps (if any)

![](https://user-images.githubusercontent.com/156149/75720113-32027500-5cd6-11ea-8427-4e2cddcdb958.png)

On: https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-and-cell-styling-tools

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team is it a regression? If so, could you bisect this?

**Comment by Mgsy** [comment]
This bug has been introduced in v16. It occurs only if a table contains a header. I'll bisect it.

**Comment by Mgsy** [comment]
It occurs since this change - https://github.com/ckeditor/ckeditor5-table/commit/c9c69541d80559db4c510039b5e4c51f5f9dd2a2.

**Comment by scofalik** [comment]
If you will change something in merging behavior, please add a ticket to test those changes in CF.

**Comment by jswiderski** [comment]
From what I have checked problem only occurs when Header Column is applied (Header Row looks fine).
