### ISSUE TITLE
Implement font family feature

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#637]
I'd like to bootstrap works on another feature: the font (family) feature.

The simplistic approach is to create a dropdown with set of configurable list of font-names to apply. But maybe we could do something better here?

**Comment by jodator** [comment]
I've also bootstraped a feature talks on Editor Recommendations repo: https://github.com/ckeditor/editor-recommendations/issues/60.

**Comment by Reinmar** [comment]
Let's merge this ticket into https://github.com/ckeditor/ckeditor5/issues/638.
