### ISSUE TITLE
Typescript error TS2370: A rest parameter must be of an array type.

### ISSUE THREAD

**Issue by blesardi** [ckeditor/ckeditor5#6373]
##  ERROR in node_modules/@ckeditor/ckeditor5-angular/ckeditor.d.ts(92,38): error TS2370: A rest parameter must be of an array type.

 This error is about callback arguments in Watchdog interface.

  interface Watchdog<T> {
        setCreator(creator: (...args: any[]) => Promise<T>): void;
        setDestructor(destructor: (item: T) => Promise<void>): void;
        on(event: string, callback: (...args: any) => any): void;
        destroy(): Promise<void>;
        create(...args: any[]): Promise<void>;
    }

**Comment by leoz2007** [comment]
Same here!
Do you find a solution?

**Comment by Mgsy** [comment]
Hi! We've just released a new version of `ckeditor5-angular` package (v1.2.2). Could you please check if it solves your problem?

**Comment by Mgsy** [comment]
Great! So, I'm closing the issue.
