### ISSUE TITLE
Multi line toolbar items

### ISSUE THREAD

**Issue by memic84** [ckeditor/ckeditor5#6375]
### 📃 Description
We are working on a migration to **ckeditor5**, and are struggling with the **toolbar items** on multiple lines.

The problem is that we have a lot of functionalities from CKEditor and also some community or custom plugins in our toolbar. We have a lot of content that is on fixed width between 400px and 500px.

### ✔️ Expected result

**Current situation in CKEDITOR 4**
![image](https://user-images.githubusercontent.com/3043840/75856033-c7475b80-5df3-11ea-856f-4ae0a924b8db.png)

### ❌ Actual result

**New situation in CKEDITOR 5**
![image](https://user-images.githubusercontent.com/3043840/75856063-db8b5880-5df3-11ea-9140-ef2da4fea9e5.png)

## 📃 Other details
As i understood in other tickets, is that multi-line toolbar items are seen as an anti-pattern in CKEditor5, however single line for a lot of items where the content is smaller has some UI problems.

1) Is there a way to force multi-lines in CK5?
2) If not, can we force the responsive menu on desktop to a fixed width for the toolbar?
3) Any other solutions are also welcome.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. As it comes to responsive toolbar, it is already available in Classic and Decoupled editor builds. We are now working on [enabling it in other builds](https://github.com/ckeditor/ckeditor5/issues/5597) too. Actually, those changes have already been done and will be available in the next release ( in about two weeks time ).

**Comment by memic84** [comment]
@FilipTokarski Thanks for the quick reply! This will work :)
