### ISSUE TITLE
[Table] Adding column/row next to multi-merged cell breaks geometry and content

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6376]
## 📝 Provide detailed reproduction steps (if any)

1. Go to all features test
2. Add a table
3. Create one big cell merged from several others
4. Select some cell next to this big merged cell and add a column

### ✔️ Expected result

Empty column is inserted

### ❌ Actual result

Insertion breaks table geometry, content jumps from cell to cell

![table_create_column1](https://user-images.githubusercontent.com/34380544/75856975-b7307b80-5df5-11ea-968c-f625eea11612.gif)

When you then type something in the big cell and add a row above or below, you get this:

![table_create_row1](https://user-images.githubusercontent.com/34380544/75857352-62d9cb80-5df6-11ea-98c5-79be6a48b9e5.gif)

## 📃 Other details

You can play with this in different cell configurations. Also happens with multicell selection.
Similar issue: https://github.com/ckeditor/ckeditor5/issues/5882

* Browser: any
* OS: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
DUP of #5882.
