### ISSUE TITLE
Pasting into selection made of multiple table cells crashes the editor

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6377]
## 📝 Provide detailed reproduction steps (if any)

1. Copy some text.
2. Create a multi-cell selection using your mouse.
3. Ctrl+V

### ✔️ Expected result

The text should be pasted, probably into the last cell in the seleciton.

### ❌ Actual result

Editor crashes.

![2020-03-04 12 11 49](https://user-images.githubusercontent.com/1099479/75874329-c45b6380-5e11-11ea-8a03-d3351331df05.gif)

## 📃 Other details

master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Fixed with ckeditor/ckeditor5-engine#1830.
