### ISSUE TITLE
Image and table not rendering as shown in text editor

### ISSUE THREAD

**Issue by amit2maha1** [ckeditor/ckeditor5#6379]
1. I made this build to upload and resize image:
https://www.npmjs.com/package/ckeditor5-build-decoupled-document-base64-imageresize
2. I integrated it as shown here : https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-document-editor-build
3. But the css doesnt apply to image and table, when displaying after retrieving from database

### ✔️ Expected result
this:
![image](https://user-images.githubusercontent.com/46278096/75900141-92bfb800-5e64-11ea-982d-db9204cfe426.png)

### ❌ Actual result

shows up likes this:
![image](https://user-images.githubusercontent.com/46278096/75900205-ab2fd280-5e64-11ea-8590-56152ab0d73e.png)

## 📃 Other details

* Browser:  chrome
* OS: win 10
* CKEditor version: ckeditor 5
* Installed CKEditor plugins: image resize, image upload ( I am using base64)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by martijnpieters** [comment]
@amit2maha1 What does the resulting HTML look like? Does the figure have a class attribute with value `image-style-align-right`? In that case you just have to display it properly by implementing some CSS rules.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. CKEditor 5 uses its own css classes, so when you generate HTML, it also contains those classes. If you then try to put this HTML somewhere on your website, you need exactly those same css classes, in order for the content to look like in the editor.
So what you need to do here, is to [add a stylesheet with a complete list of CKEditor 5 content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#sharing-content-styles-between-frontend-and-backend). This should fix your problem.

**Comment by amit2maha1** [comment]
> Hi, thanks for the report. CKEditor 5 uses its own CSS classes, so when you generate HTML, it also contains those classes. If you then try to put this HTML somewhere on your website, you need exactly those same CSS classes, in order for the content to look like in the editor.
> So what you need to do here, is to [add a stylesheet with a complete list of CKEditor 5 content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html). This should fix your problem.

nice thanks this is exactly what I wanted

**Comment by falcon9r** [comment]
> Привет, спасибо за отчет. CKEditor 5 использует свои собственные классы CSS, поэтому при создании HTML он также содержит эти классы. Если вы затем попытаетесь разместить этот HTML-код где-нибудь на своем веб-сайте, вам понадобятся точно такие же классы CSS, чтобы контент выглядел как в редакторе. Итак, что вам нужно сделать здесь, это [добавить таблицу стилей с полным списком стилей содержимого CKEditor 5](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) . Это должно решить вашу проблему.

мне не описать словами как вы помогли мне :)
