### ISSUE TITLE
Question, How to get the dom or the element html top value at the cursor?

### ISSUE THREAD

**Issue by yu0307** [ckeditor/ckeditor5#6383]
I'm trying to get the html location top value when update event is triggered. So far I have no clue how to get that. Can anyone help please?

**Comment by Mgsy** [comment]
Hi, could you describe your use case more precisely?

**Comment by yu0307** [comment]
sure, 
I was trying to get the cursor location when anything was changed within the editor. 
assuming a case which an enter key was pressed somewhere within the editor's contents. 
I tried to use the event change:data like below 
```
model.document.on("change:data", (eventInfo, batch) => {
                var node = document.getSelection().anchorNode;
            });
```

but it seems the event was fired before the cursor was moved after the enter key. document.getSelection().anchorNode gets the node before the caret was moved. 

Other than the approach above, is there something CKEditor provides that shows the cursors's location whenever called upon?

Thank you

**Comment by yu0307** [comment]
@Mgsy hi, just in case you missed it.

**Comment by Mgsy** [comment]
Basically, you are on the right track. To get the current caret position, you can call `editor.model.document.selection.getFirstPosition()`.

So, the changed code can look like this:
```js
editor.model.document.on( 'change:data', ( eventInfo, batch ) => {
	console.log( editor.model.document.selection.getFirstPosition() );
} );
```

**Comment by yu0307** [comment]
@Mgsy Thank you for your help. How do we select a dom element from this selection's firstPosition()?

**Comment by Reinmar** [comment]
@yu0307, I saw your other ticket (#6396) and frankly speaking – you should read the documentation: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/overview.html.

You're trying to do things like the editor was a thin wrapper on DOM layer. It's not. CKEditor 5 introduces an MVC architecture and all the features are based on it. Usually, you should not touch the DOM – it's CKEditor 5's role. Just like in most modern apps/frameworks.
