### ISSUE TITLE
doubling of heading, conflict with reveal.js 

### ISSUE THREAD

**Issue by TimFFischer** [ckeditor/ckeditor5#6386]
CKG Editor has conflicts with reveal.js. 

## 📝 detailed reproduction steps 

1. install the dokuwiki-plugins ckgeditor5 and reveal.js (version 2018-09-02; most present one)
2. generate a page with multiple headings in DW editor
3. open ckgeditor ("Edit") and press button "DW editor" (without doing changes to the sourcecode)
3. open DW editor ("Edit") again

### ✔️ Expected result

no changes expected

### ❌ Actual result

each heading got doubled 

## 📃 Other details

* Browser: Chrome
* OS: CentOS Server
* CKEditor version: 2020-02-13
* Installed CKEditor plugins: none 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, I'm not sure what exactly you try to achieve, however, it looks like you use some external libraries. We can't make CKEditor 5 to work with every integration, especially with some less popular technologies, so I'm afraid you have to debug it on your own. 

If you feel that we should provide support for one of the technologies you use, feel free to open a new feature request.
