### ISSUE TITLE
Font / font background color features

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#639]
Those two features have many similarities both in implementation and UI/UX so as for start I think that it make sense to talk about them in one issue.

Let's start  talks on those features as it might be lengthy and both requires good research on UI and UX.

Those features were also discussed in: https://github.com/ckeditor/ckeditor5/issues/481, https://github.com/ckeditor/ckeditor5/issues/631, https://github.com/ckeditor/ckeditor5/issues/616.

**Comment by jodator** [comment]
And related talk in Editor Recommendations: https://github.com/ckeditor/editor-recommendations/issues/62.

**Comment by Reinmar** [comment]
Further works are conducted in the https://github.com/ckeditor/ckeditor5-highlight repository.
