### ISSUE TITLE
Question: Why is BalloonEditor has no getSelection method?

### ISSUE THREAD

**Issue by yu0307** [ckeditor/ckeditor5#6390]
Hi all, 
I was using the vue component for CKeditor, and why is my editor instance having no method getSelected() ?
```
<ckeditor
                ref="ckEditor"
                :editor="editor"
                v-model="editorData"
                :config="editorConfig"
            ></ckeditor>
...
data(){
    return {
        editor: ballooneditor,
        editorConfig: {some configs..},
        editorData: 'some data',
    }
}
... somewhere in the js...
this.$refs.ckEditor.instance.getSelection(); **<------------------has no such method** 

```

thank you

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. There is no `getSelection()` method in CKEditor 5 ( although you might have seen it in CKEditor 4 ). If you want to get [selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_selection-Selection.html) you should use: `editor.model.document.selection`
You can [use it in conjunction with `getSelectedContent`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-getSelectedContent):
```
const selection = editor.model.document.selection;

editor.editing.model.getSelectedContent( selection );
```
