### ISSUE TITLE
For Title Plugin, Is there a way to limit the title max char length?

### ISSUE THREAD

**Issue by yu0307** [ckeditor/ckeditor5#6396]
I tired using some vanilla js within the Editor ready even method, but it seems the view is rendered after this event is called. I can't also seem to find a ready event for this plugin. 
Can anyone help please. 
```
@ckeditor/ckeditor5-heading/src/title           <------this plugin
.....
editor_instance.plugins
                .get("Title")
                ._getTitleElement()
                .document.on("keydown", e => {
                    console.log(e);
                });                         <-------------this will not work.
```

**Comment by Reinmar** [comment]
There's no existing feature to limit the length of the title. You'd need to implement it by yourself. And for that, it will be enough to operate on the model. You don't need access to the DOM.

PS. See my other comment in https://github.com/ckeditor/ckeditor5/issues/6383#issuecomment-596953639.

**Comment by Reinmar** [comment]
You can open a feature request for the title length limit. I'm closing this issue as it's too specific.
