### ISSUE TITLE
Mentions plugin autocomplete formatting

### ISSUE THREAD

**Issue by psweeney101** [ckeditor/ckeditor5#6397]
## 📝 Provide detailed reproduction steps (if any)

1. Autocomplete a word or group of words using the Mentions plugin
2. Attempt to apply formatting (bold, italicize, etc.) to only a part of that autocompleted segment. 
3. The entire word or phrase that was inserted from autocomplete receives that formatting, not just what was highlighted.

Example: Autocomplete "@username", try to bold only "user" and not "name", and the entire "@username" is highlighted.

Can be seen in [the demo](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#demo) if you try to apply formatting to just a letter or group of letters.

I understand this is a very minor use case, however if you extend this plugin to work for phrases or multiple words it becomes a more common issue.

### ✔️ Expected result

_What is the expected result of the above steps?_
Only what is highlighted is formatted

### ❌ Actual result

_What is the actual result of the above steps?_
The entire word is highlighted, which is inconsistent with the rest of the document.

## 📃 Other details

* Browser: Chrome 80
* OS: Windows 10
* CKEditor version: CKEditor 5 v17.0.0
* Installed CKEditor plugins: Mentions

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is intentional. This feature treats the entire inserted fragment as a token. It must be left untouched, otherwise it's "unmarked" (the mention is lost). For a different behaviour you'd need #1686.
