### ISSUE TITLE
Introduce nested dropdowns

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6399]
## 📝 Provide a description of the new feature

Introduce some guide/API for creating nested dropdowns.

![image](https://user-images.githubusercontent.com/20988892/76304051-fb72be80-62c2-11ea-86a6-5ba2f52139e3.png)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by regischen** [comment]
I am wondering can developer can implement this by themselves?

**Comment by gumatias** [comment]
@Mgsy mind being more specific on what kind of guidance or API we are looking for? I might take a stab at it if I can.

**Comment by rutvay-dv** [comment]
Hi @Mgsy is this introduced ?

**Comment by Witoso** [comment]
We are investigating this in #16766.
