### ISSUE TITLE
Implement Highlight feature

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#640]
A feature for highlight a text by defined set of "highlighters". At first it looks very similar to [font background](https://github.com/ckeditor/ckeditor5/issues/639) but this feature would most probably have different UI/UX then a font background.

The main difference here is that Highlight feature is mostly inspired by highlighting a text on paper with a marker pen.

There's also a described use-case by @elglingo: https://github.com/ckeditor/ckeditor5/issues/631#issuecomment-339380798 and some insights on this from @scofalik: https://github.com/ckeditor/ckeditor5/issues/631#issuecomment-339631589.

**Comment by jodator** [comment]
And also related talk in Editor Recommendations repo: https://github.com/ckeditor/editor-recommendations/issues/63.

**Comment by jodator** [comment]
As pointed out by @Commander in editor recommendations. The element used to mark stuff in content is called `mark`.

**Comment by jodator** [comment]
@oleq & @fredck I've created an issue in https://github.com/ckeditor/ckeditor5-highlight/issues/1 that gathers all talks about this feature. Please add your comments if needed.

**Comment by Reinmar** [comment]
Further works are  conducted in the https://github.com/ckeditor/ckeditor5-highlight repo.
