### ISSUE TITLE
[Table] Crash when removing row after horizontal split

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6401]
## 📝 Provide detailed reproduction steps (if any)

1. Open some test with table
2. Select some cell and split horizontally two times
3. Select the middle cell and click `delete row`

### ✔️ Expected result

Row gets deleted

### ❌ Actual result

Editor crashes:
![table_split1](https://user-images.githubusercontent.com/34380544/76303014-4ab7ef80-62c1-11ea-9c31-96ac84169534.gif)

```js
Uncaught TypeError: Cannot read property 'is' of undefined
    at Function._createAt (position.js:914)
    at Model.createPositionAt (model.js:606)
    at Writer.createPositionAt (writer.js:597)
    at Object.callback (removerowcommand.js:103)
    at Model._runPendingChanges (model.js:801)
    at Model.change (model.js:170)
    at RemoveRowCommand.execute (removerowcommand.js:61)
    at RemoveRowCommand.<anonymous> (observablemixin.js:255)
    at RemoveRowCommand.fire (emittermixin.js:209)
    at RemoveRowCommand.<computed> [as execute] (observablemixin.js:259)
```

## 📃 Other details

I cannot reproduce it on latest docs, as well as v16 & v15. After bisecting, it seems that this bug was introduced by this commit: https://github.com/ckeditor/ckeditor5-table/commit/281dba525da57d9d28529c1bf43ef997dd93681b

* Browser: any
* OS: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
@FilipTokarski Could you verify this? WFM here.

I would like also to verify what I see on the GIF: I can see that all the cells are grey besides the middle one - how this happens? I've tested it by:

1. insert 3x3 table
2. select last table cell and set heading columns (all table cells are grey)
3. split middle table cell
4. split the same table cell again
5. move the selection to the new middle cell (as in your GIF)
6. invoke delete row

It works for me now.

**Comment by FilipTokarski** [comment]
The cells are grey because they have styling applied, they are not header rows/columns. Sorry for that, indeed it might have been misleading.
  
Anyway, I checked it once again and now it works for me too. I guess it has been fixed together with other changes in table, in latest release. I'm closing this.
