### ISSUE TITLE
Removing complex colspan/rowspan multi-cell selections column/rows should be improved

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6406]
## 📝 Provide detailed reproduction steps (if any)

After ckeditor/ckeditor5-table#261 is merged, there are some edge cases not handled well. Example screencasts:

![](https://user-images.githubusercontent.com/5353898/76330700-769d9a00-62ee-11ea-86e8-9c08e80c8600.gif)

![](https://user-images.githubusercontent.com/5353898/76330709-7b624e00-62ee-11ea-9fa6-c5e62ac0469a.gif)

### ✔️ Expected result

The table structure should be better.

### ❌ Actual result

Weird artifact cells added to the right side of the table.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
After checking this problem we've seen that a proper fix will require a lot of effort from us to get this right.

Because of that we'd like to understand whether it's an important issue for our users, before committing to it, so be sure to add :+1

**Comment by jodator** [comment]
Look at my comments here: https://github.com/ckeditor/ckeditor5/issues/6487.

**Comment by jodator** [comment]
> After checking this problem we've seen that a proper fix will require a lot of effort from us to get this right.

Nah, it was small oversight - the table map obtained from `TableWalker` must be recalculated on each row/column removal. Fix on the way.
