### ISSUE TITLE
Table balloon rendered in wrong place after unlinking text in table

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6408]
## 📝 Provide detailed reproduction steps (if any)

1. Open some editor with `table` and `link` features
( for example it's easy to reproduce on [classic-editor-with-real-time-collaboration](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/classic-editor-with-real-time-collaboration) sample )
2. Add a link in some cell
3. Unlink

### ✔️ Expected result

Text is unlinked, table balloon appears at the top of the table

### ❌ Actual result

Text is unlinked, table balloon jumps to top-left corner of the window:  
  
![table_link_render](https://user-images.githubusercontent.com/34380544/76395454-a0e76a00-6377-11ea-9d6d-ce9b50b07047.gif)

## 📃 Other details
* It is hard to spot, because most of the times some elements on the page are covering the balloon when it jumps to top-left corner ( this is exactly the case in most of the tests and docs, so sometimes you need to remove html to see it clearly )
* Browser: any
* OS: any
* CKEditor version: **Introduced in version 12.2.0**
* Installed CKEditor plugins: Table, Link

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Seems like the original issue if fixed now. However I'm not sure if the current behaviour is 100% correct, as after unlinking the table balloon shows up on the unlinked text, instead on the table:


https://user-images.githubusercontent.com/34380544/135272796-bda39026-c0c3-4a55-9967-5b29b1ac73fa.mp4

**Comment by mateuszzagorski** [comment]
@FilipTokarski it seems that it has been already found by @LukaszGudel here:  
[https://github.com/ckeditor/ckeditor5/pull/10373#issuecomment-908298028](https://github.com/ckeditor/ckeditor5/pull/10373#issuecomment-908298028)  
  
And as per Dawid's [comment](https://github.com/ckeditor/ckeditor5/pull/10373#issuecomment-914140857) regarding resolving this problem:

> In this [issue](https://github.com/ckeditor/ckeditor5/pull/10373#issuecomment-908298028) it's caused by a mechanism that prevents balloons from jumping around if the context has been changed (for example if you are on a link, but now you jumped out of the link and you see text attributes balloon. It should stay more or less in the same place). Because of this the balloon stays inside the cell, and cell related balloons (for example table cell properties) do not get sticky when scrolling (because it makes no sense for the UI). So we decided it's good enough as is.

it seems that this issue should be closed as the behavior is known and expected.
