### ISSUE TITLE
How I can listen keystroke in JS?

### ISSUE THREAD

**Issue by cagataycali** [ckeditor/ckeditor5#641]
## 💻 Version of CKEditor
5

I need to bind data with vuejs in ckeditor5 but I couldn't handle keystroke with these,

```javascript
 editor.on('change', function () {
    alert(1);
  });
```

Any ideas?

**Comment by cagataycali** [comment]
Ah I extract one usage from example but It's hard to find. 
```javascript
editor.document.on('changesDone', () => {
   alert(1);
});
```

**Comment by scofalik** [comment]
If you want to perform an action after each editor content change, I confirm that it is correct to use [`changesDone` event](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_document-Document.html#event:changesDone).

Maybe we should introduce some kind of "FAQ" in the documentation / guides if this not clear enough, as this is another question of this kind.

**Comment by Reinmar** [comment]
I'd also consider changing the naming of these events a bit. It'll be one of the most popular issues that people try to use the `change` event when they don't care about atomic changes and should not be notified about atomic changes (because you can't touch many things before `changesDone`).
