### ISSUE TITLE
no ImageResize plugin

### ISSUE THREAD

**Issue by hjm100** [ckeditor/ckeditor5#6410]
The @ckeditor/ckeditor5-build-classic package has no ImageResize plugin

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. ImageResize in not enabled by default in any of editor builds. Please refer to our docs on [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and [enabling ImageResize plugin](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#enabling-image-resizing).

**Comment by hjm100** [comment]
Every time you load a package, you need to update the build again because @ckeditor/ckeditor5-image is already in the project

**Comment by hjm100** [comment]
Is there a better way to open it without having to change the package every time

**Comment by FilipTokarski** [comment]
You can [create your own, custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) with all the plugins and configuration you need.

**Comment by hjm100** [comment]
ok
