### ISSUE TITLE
Autoformat should support strikethrough

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6412]
## 📝 Provide detailed reproduction steps (if any)

Currently autoformat does not support strikethrough. It should be possible to strikethrough text with `~~`.

## 📃 Other details

*   Browser: Any
*   OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
There are a bunch of basic style commands added in https://github.com/ckeditor/ckeditor5-autoformat/blob/871ad12b85fe59ade193b45b0c9fbc081515ac07/src/autoformat.js#L77-L107 but there's no binding for the `strikethrough` comand.

So we need to do a similar thing as for other (bold, italic, code) commands but for `strikethrough` and with different wrapper (`~~`).

Ofc this change needs to be covered with unit tests.

**Comment by niegowski** [comment]
https://github.com/ckeditor/ckeditor5-autoformat/pull/79
