### ISSUE TITLE
How to bind click event to anchor tag(<a>) ? I am using converter to place the anchor tag in the document. I tried binding onclick with the anchor tag, but it throws method is undefined. So Please let me know how to make the text clickable after conversion?

### ISSUE THREAD

**Issue by Shankar26G** [ckeditor/ckeditor5#6418]
## Provide a description of the task

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Shankar26G** [comment]
// Helper method for both downcast converters.
  function createPlaceholderView( modelItem:any, viewWriter:any ):any {
    const name = modelItem.getAttribute( 'name' );

    const placeholderView = viewWriter.createContainerElement( 'a', {
        class: 'highlight',
        onclick:'test()'
    } );

    // Insert the placeholder name (as a text).
    const innerText = viewWriter.createText( '{' + name.value + '}' );
    viewWriter.insert( viewWriter.createPositionAt( placeholderView, 0 ), innerText );
    
   // innerText.on( 'click' ).bind.to( 'referenceLinkCommand1');
    return placeholderView;

**Comment by Shankar26G** [comment]
Where can i place the test() method so that the editor recognizes it? Or atleast how do i make the innextText as clickable?

const innerText = viewWriter.createText( '{' + name.value + '}' );

**Comment by Mgsy** [comment]
Hi! You can listen to [`click`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html#event-event:click) event on the view document and verify if the target is the `a` element. See the example below:

```js
editor.editing.view.document.on( 'click', ( evt, data ) => {
    if ( data.target.name == 'a' ) {
        console.log( '<a> element clicked.' );
    }
} );
```

**Comment by Shankar26G** [comment]
Hi Mgsy. Thank you
