### ISSUE TITLE
Research CSS flex box layout in the UI

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#642]
ATM we use the float–based element positioning, which isn't the most convenient way of building the interfaces. Flex would speed up the development, shorten the code and solve [some issues](https://github.com/ckeditor/ckeditor5/issues/636#issuecomment-339697266) that required JS solutions.

The only problem here is IE11 which has some [issues with Flex](https://caniuse.com/#search=flex) but I'm not certain if they will be a problem to us. This must be checked.

The sooner we go with Flex, the better because ATM we're facing a [major CSS refactoring](https://github.com/ckeditor/ckeditor5-ui/issues/144#issuecomment-336849249) (migration to PostCSS) in a couple of days anyway and the number of UI components isn't that big (yet).

**Comment by mwadams** [comment]
Having spent a lot of time on FlexBox with IE11 support, the bugs are not challenging to work around (largely, just have a good "reset" to normalize flexbox defaults, and then remember to always use `flex: a b c;`)

**Comment by Reinmar** [comment]
What's the status of this? Didn't we move to flex?

**Comment by oleq** [comment]
We use flex across the UI ATM. I consider the topic closed.
