### ISSUE TITLE
Sprockets::FileNotFound in Admin::Blogs#new

### ISSUE THREAD

**Issue by aditya2727** [ckeditor/ckeditor5#6420]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Sorry, but it seems like a accidental issue report. Closing.
