### ISSUE TITLE
[Table] Crash after splitting cell horizontally and removing column

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6422]
## 📝 Provide detailed reproduction steps (if any)

1. Open some table test
2. Select a cell
3. Click `split cell horizontally`
4. Click `delete column`

![12_table4](https://user-images.githubusercontent.com/34380544/76514005-8389cd00-6457-11ea-9e53-8a62cd882156.gif)

### ✔️ Expected result

Column is removed, no crash

### ❌ Actual result

Editor crashes:
```js
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at tableutils.js:564
    at Array.reduce (<anonymous>)
    at TableUtils.getRows (tableutils.js:563)
    at RemoveRowCommand.refresh (removerowcommand.js:37)
    at Document.<anonymous> (command.js:111)
    at Document.fire (emittermixin.js:209)
    at Document._handleChangeBlock (document.js:317)
    at Model._runPendingChanges (model.js:804)
    at Model.change (model.js:170)
    at RemoveColumnCommand.execute (removecolumncommand.js:68)
```

## 📃 Other details

Bisection shows this commit: https://github.com/ckeditor/ckeditor5-table/commit/700fbb12e8226bba6055eb7c83354d024b7a589d

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
The source of this problem is that **after removing the column**, there's a minor mess in the model - there's an empty table row leftover in the model.

As a result, a subsequent [removerowcommand's refresh method](https://github.com/ckeditor/ckeditor5-table/blob/abe9d05110025616a1a80cd940bf89282ed89cb0/src/commands/removerowcommand.js#L37) fails, because [`tableutils.getRows()`](https://github.com/ckeditor/ckeditor5-table/blob/abe9d05110025616a1a80cd940bf89282ed89cb0/src/tableutils.js#L564) command expects always a cell.

**Comment by mlewand** [comment]
Unfortunately the root cause of the issue (the fact that column remove can put an empty table row in model) is not a regression, as I'm able to reproduce it on v17.0.0 docs.

**Comment by Reinmar** [comment]
> Unfortunately the root cause of the issue (the fact that column remove can put an empty table row in model) is not a regression, as I'm able to reproduce it on v17.0.0 docs.

I can't see that empty row. At what stage is it created? And is it cleaned up later on?

It's weird to have an empty row and something that should never happen. So, perhaps, the fix should be somewhere else (so empty row is never created)?

**Comment by mlewand** [comment]
@Reinmar The empty row is created (or rather not removed) during the remove column command. See the gif below, you can note a weird ~1px artifact on the bottom-right edge of the last cell after column has been removed:

![](https://user-images.githubusercontent.com/5353898/76532804-6cf36e00-6477-11ea-8883-6aae6a9bc462.gif)

If you inspect the view markup it will confirm this, there's a third (empty) row:

![](https://user-images.githubusercontent.com/5353898/76532849-7d0b4d80-6477-11ea-9f2a-2b1233303a58.png)

Definitely the command should not leave mess in the model, but having a case like that it's highly possible that other commands might produce a markup like this in certain scenario, so it's better to take a slightly more _defensive_ approach with the `getRow()` function.
