### ISSUE TITLE
Can't insert content before widget in editor

### ISSUE THREAD

**Issue by CaelanStewart** [ckeditor/ckeditor5#6424]
## 📝 Provide detailed reproduction steps (if any)

1. Go to this page: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html
2. Insert a table at the very beginning of the content
3. Try to add content before the table without cutting the table, inserting the content, and then pasting the table after the newly inserted content.

This fundamentally falls down to an inability to place the caret position BEFORE the table widget.

The converse of this issue is also true, you can't remove a blank line before a table widget.

I've not tested, but it probably affects any widget that behaves in a similar manner to the table.

### ✔️ Expected result

If I have the caret position directly AFTER the table, I should be able to press left to select it, and then press left AGAIN to place the caret BEFORE the table. Or just keep pressing the up key.

### ❌ Actual result

With the caret position directly after the table, if I press left, it selects the table, but I am unable to then press left a second time to place the caret BEFORE the table.

## 📃 Other details

Slack have recently adopted a simply WYSIWYG. If you add a code block, place the caret within it, or after it, and you can just keep pressing 'up' until the caret is placed BEFORE the code block.

Basically, Slack's WYSIWYG allows all of what I explain is missing in CKEditor above.

I love CKEditor, it is so well made. But there's just these issues that are concerning, because I can guarantee, from numerous previous support requests, that users of our software will be creating support tickets asking for help on how to delete the space before, and how to add stuff before it.

The mechanism for selecting the table with the select handle etc. felt a little odd and unintuitive. My manager came over to have a little play with the integration into our software, and he was confused about what the little selection handle was - and he's a technically literate guy (developer). It looks like you should be able to drag and drop the table by clicking and dragging the selection handle.

I was confused when I first played with it, too. I think sometimes for creators of software, you built it, so it couldn't be more obvious to you how to use the tools.

You'd be amazed at the lack of an ability for most people to figure out they need to select the table, cut it, and then paste it to be able to move it, or to place content before it.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by CaelanStewart** [comment]
I've updated the extra details a bit after realising I was a bit silly and that it is actually fairly obvious how to delete the table - place the caret after it and then delete it with backspace.

However, there are some other points that I've added in, and left the other points which still stand.

**Comment by Mgsy** [comment]
Hi! We're aware of this UX issue and we've implemented a workaround for it - while selecting a widget press <kbd>Enter</kbd> to add a new paragraph after the widget and <kbd>Shift</kbd> + <kbd>Enter</kbd> to add a new line before the widget.

This is a workaround for a general issue which is described [here](https://github.com/ckeditor/ckeditor5/issues/407).

**Comment by CaelanStewart** [comment]
@Mgsy - that's very unusable and unintuitive. From plentiful experience, I guarantee that we'll receive support tickets from confused users about this. You should not have to refer to a shortcut that isn't obvious in order to do basic things like add a line before a table.

Plus, should not the fact that you've received an issue report be evidence enough that a more user-friendly and intuitive solution is necessary? I actually played around for a few minutes trying to figure out if you'd added some kind of shortcut for it, and I could not find one. That alone is indication of poor UX.

Also, you've not responded to the second part of my issue report. You can't remove the space before the widget without cutting and pasting the widget.

Could it not be possible to have a "virtual" caret position, before a widget? Or, perhaps, a "virtual" line, which can be selected WITHOUT selecting the table? In almost ANY text editor, you can select newline characters. But CKEditor goes against the grain, there.

It would be so much more intuitive if you hooked onto the "Left" or "Right" arrow keys and, if the caret is on the table, add a new line before it.

This is was Slack do, now that they support WYSIWYG.

Microsoft Word handles this a bit differently, though, it is still somewhat intuitive. They have a little drag handle, which looks similar to CKEditor's Table selection handle. You can just drag the table down, even if there are no lines after the table. It will create enough lines for you to place the table where the user dropped it. If they did what Slack did, AND had the drag handle, then that would be even better.

Either way, the current solution is poor. You cannot expect users of CKEditor to pass on a list of instructions on how to use a simple WYSIWYG on any software CKEditor is integrated in.

CKEditor is such a well-made piece of software, but there's these rough edges which are concerning, and may even necessitate a switch to a different piece of software by vendors if they are not addressed.

**Comment by CaelanStewart** [comment]
@Mgsy - I stopped being lazy for a moment and read the thread you posted. Basically, ignore me...
