### ISSUE TITLE
Certain file pasted from word crashes in title feature sample (possibly in others)

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6427]
## 📝 Provide detailed reproduction steps (if any)

1. Open [nightly docs title feature sample](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/title.html).
2. Open word file:  [Blue Hotel.docx](https://github.com/ckeditor/ckeditor5/files/4328817/Blue.Hotel.docx)
3. Select entire word file content.
1. Copy.
1. Paste into the editor.

### ✔️ Expected result

Content should be pasted. Just like it did for the v17.0.0 release, see [docs@17.0.0 permalink](https://ckeditor.com/docs/ckeditor5/17.0.0/features/title.html).

### ❌ Actual result

Exception is being thrown:

```
ckeditorerror.js:66 Uncaught TypeError: Cannot read property 'getNormalized' of undefined
    at StylesMap.getNormalized (stylesmap.js:245)
    at AttributeElement._clone (element.js:572)
    at AttributeElement._clone (attributeelement.js:208)
    at DowncastWriter._wrapChildren (downcastwriter.js:1129)
    at DowncastWriter._wrapRange (downcastwriter.js:1301)
    at DowncastWriter.wrap (downcastwriter.js:841)
    at DowncastDispatcher.<anonymous> (downcasthelpers.js:620)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:474)
    at DowncastDispatcher.convertInsert (downcastdispatcher.js:195)
```

## 📃 Other details

I feel like more samples could be affected by this. I assume it's table properties plugin.

* Browser: Chrome (didn't test more)
* OS: Win10 (didn't check other)
* CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@ckeditor/qa-team can you check if you reproduce that (and can't reproduce on 17.0.0)?

**Comment by FilipTokarski** [comment]
I can reproduce this on nightly.  
 
On _v17_, _v16_, _v15_ and _paste-from-office_ test the text content gets pasted ok, but I get error about loading the image:
```
Not allowed to load local resource: 
file:///C:/Users/path_to/clip_image002.jpg
```

However, if you just click only on the image and copy it ( in word file ), it gets pasted without problems everywhere.

**Comment by mlewand** [comment]
Can you verify if any other samples are affected by this problem?

**Comment by FilipTokarski** [comment]
All samples in v17 are ok, I can reproduce the original error only on nightly _Document title_

**Comment by pomek** [comment]
The error can be related to https://github.com/ckeditor/ckeditor5-engine/pull/1826. I'll debug it.

**Comment by Adaer** [comment]
> 我可以每晚复制一次。
> 
> 在_V17_，_V16_，_V15_和_粘贴，从办公_测试的文本内容被粘贴好了，但我得到的错误有关加载图像：
> 
> ```
> Not allowed to load local resource: 
> file:///C:/Users/path_to/clip_image002.jpg
> ```
> 
> 但是，如果仅单击图像并将其复制（在word文件中），则将其粘贴到各处都不会出现问题。

We have the same problem
