### ISSUE TITLE
Quick start webpack scss build failed

### ISSUE THREAD

**Issue by cagataycali** [ckeditor/ckeditor5#643]
## 🐞 Webpack SCSS build failiture

- [x] Bug report

## 💻 Version of CKEditor
> v5

## 📋 Steps to reproduce

1. [Quick start](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html)
2. Add this in webpack, 
```javascript
            { 
                // Or /ckeditor5-[^/]+\/theme\/[^/]+\.scss$/ if you want to limit this loader
                // to CKEditor 5's theme only.
                test: /\.scss$/,

                use: [
                    'style-loader',
                    'css-loader',
                    'sass-loader'
                ]
            },
```

## ✅ Expected result

`DONE  Compiled successfully in X sec.`

## ❎ Actual result

```
 error  in ./~/@ckeditor/ckeditor5-editor-classic/theme/theme.scss

Module build failed: 
// Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in /Users/cagatay/x/frontend2/node_modules/@ckeditor/ckeditor5-editor-classic/theme/theme.scss (line 1, column 1)

 @ ./~/@ckeditor/ckeditor5-editor-classic/theme/theme.scss 4:14-202 18:2-22:4 19:20-208
 @ ./~/@ckeditor/ckeditor5-editor-classic/src/classiceditor.js
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/notes/Editor.vue
 @ ./src/components/notes/Editor.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/notes/Note.vue
 @ ./src/components/notes/Note.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/notes/Notepad.vue
 @ ./src/components/notes/Notepad.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

**Comment by oleq** [comment]
I followed quick start guide from scratch and ended up with a successful build in `dist/`. 

1. Have you changed anything in `webpack.config.js`? Because your second step
    > 2. Add this in webpack,

    looks exactly like the content of `webpack.config.js` in the quick start guide.
2. Which version of node.js you used? What's your OS?

**Comment by cagataycali** [comment]
I'm using,
> node 8.4.0
> npm 5.3.0

I added into webpack config but I've scss files already. I have to use this one `/ckeditor5-[^/]+\/theme\/[^/]+\.scss$/`

**Comment by oleq** [comment]
I'm afraid I won't be able to help you out without more information about the environment. The build fails at the very first line of the scss file (the comment). It could be that the file is not recognized correctly by the sass loader or some other loader wants to compile it as a js file because it is [direclty imported](https://github.com/ckeditor/ckeditor5-editor-classic/blob/master/src/classiceditor.js#L16).
