### ISSUE TITLE
Disabling table selection should collapse selection

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#6430]
## 📝 Provide a description of the improvement

At this moment, when you disable table selection plugin, the selection stays as it was, that is, it can be done on multiple cells. This is in my opinion wrong - if I disable the multi-cell selection I don't want it to be existing in the editor anymore.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
Unfortunately, when I do this:

```plaintext
tableSelectionPlugin.forceDisabled( 'trackChanges' );

editor.model.change( writer => {
	const range = editor.model.schema.getNearestSelectionRange( editor.model.document.selection.getFirstPosition() );

	writer.setSelection( range );
} );
```

The `range` is still collapsed on a cell, instead of inside :|.

**Comment by mlewand** [comment]
Yea, I guess you need to do some extra magic to shrink to inside of a first/last table cell, as the selection is always outside of a cell.

**Comment by scofalik** [comment]
I've used this and it seems to work:

```plaintext
editor.model.change( writer => {
	let position = editor.model.document.selection.getFirstPosition();

	if ( position.nodeAfter && position.nodeAfter.is( 'tableCell' ) ) {
		position = writer.createPositionAt( position.nodeAfter, 0 );
	}

	const range = editor.model.schema.getNearestSelectionRange( position );

	writer.setSelection( range );
} );
```

But I treat it as a hack and looking foward to having it inside the plugin.

**Comment by scofalik** [comment]
It seems to work even for more difficult cases like this:

![](https://user-images.githubusercontent.com/1502228/76613507-93201900-651e-11ea-8a02-2eab007687f8.png)

(selection ends up on an image) or an empty cell.

**Comment by mlewand** [comment]
We were able to make a temp workaorund in CF, since we need to start testing iteration 30 ASAP I'm moving this to it. 31st
