### ISSUE TITLE
Should tableCell be defined as object in schema?

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#6432]
## 📝 Provide a description

I am not sure if `tableCell` element should be "an object" (`isObject: true` in schema). Looking at description: https://ckeditor.com/docs/ckeditor5/latest/api/module\_engine\_model\_schema-SchemaItemDefinition.html an object is:

> "self-contained" and should be treated as a whole. Examples of object elements: `image`, `table`, `video`, etc. **Note:** An object is also a limit, so [`isLimit()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html#function-isLimit) returns `true` for object elements automatically.

So I am not sure if it applies. I'd add to that, that for me, "an object" is something that carries an information on it's own. For example a video, or image. It can be empty, with no other content/data and it still is meaningful.

Current situation messes up some algorithms.

First, `getNearestSelectionRange()` selects a cell, while I think that even in this situation:

```plaintext
<table>
    <tableRow>
        <tableCell><paragraph></paragraph></tableCell>[]
    </tableRow>
</table>
```

The selection range should be

```plaintext
<table>
    <tableRow>
        <tableCell><paragraph>[]</paragraph></tableCell>
    </tableRow>
</table>
```

Not

```plaintext
<table>
    <tableRow>
        [<tableCell><paragraph></paragraph></tableCell>]
    </tableRow>
</table>
```

(even with table selection turned on).

Second, `Model#hasContent()` will return `true` when an empty cell is selected (like in the example above).

I think it should be a `isLimit` + `isBlock`.

**Comment by scofalik** [comment]
For example, this is what I have to do if I want to be sure that the range will be created in something that is "visible" in editor. A real piece of content, if you will.

```plaintext
_hasContent( range ) {
	for ( const item of range.getItems() ) {
		if ( _itemIsContent( item ) ) {
			return true;
		}
	}

	return false;
}

_itemIsContent( item ) {
	return item.is( 'textProxy' ) || this.editor.model.schema.isObject( item ) && !item.is( 'tableCell' );
}
```

**Comment by Reinmar** [comment]
IMO, the current definition is correct. Let me go through it:

*   `isObject` this is needed to make the cell selectable from outside. It also makes a table cell "count" as a content which is an unfortunate side effect. If anything, I'd look for a different property to mark selectable things, but a new one would need to be introduced. `isSelectable`? All objects would be selectable by default too.
*   `isLimit` is fine of course. All objects are limits too.
*   `isBlock` that would be incorrect. Blocks are paragraphs, headings, etc. They have block formatting enabled (text transformation) and can be converted one to another (toggling between block styles). Also, containers such as `blockQuote` are not marked as blocks and `tableCell` is a container in fact (it contains paragraphs and other block-level elements).

So, if the problems boil down to two things:

*   make cells not seen as content
*   make cells not be selected automatically by `getNearestSelectionRange()`

Then we need to differentiate cells from other selectable objects. In other words – cell is selectable like other objects, but it's not an object. Hence, we need a new property in the schema.

**Comment by scofalik** [comment]
:+1: 

You are right. Plus, table cell cannot be divided by enter key.

**Comment by Reinmar** [comment]
> Plus, table cell cannot be divided by enter key.

That's ensured by `isLimit`.

**Comment by Reinmar** [comment]
Let's wait for more ideas in #7631. If we won't have ground breaking proposals there _regarding `isObject`_, then the only decision that we'll have to make in this ticket will be whether we are also taking the occasion to implement `isContent` or not. Both options will be fine, so it's a matter of your intuition @oleq.
