### ISSUE TITLE
Multi-cell selection is stuck when deleting columns in certain scenarios

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6434]
## 📝 Provide detailed reproduction steps (if any)

In http://localhost:8125/ckeditor5-table/tests/manual/table.html:

![2020-03-13 12 24 22](https://user-images.githubusercontent.com/1099479/76623234-61fe1380-6533-11ea-9067-353293398448.gif)

### ✔️ Expected result

There should be no multi-selection leftover ("Terrestrial planets"), only a regular selection collapsed inside the cell.

### ❌ Actual result

There's a regular selection in the table next to the muli-cell (spaning a 1 cell) selection.

## 📃 Other details

master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This issue seems to be no longer happening.

**Comment by jodator** [comment]
Yep. It looks like it was due to some table column removal bug. Either #6789 or #6546.
