### ISSUE TITLE
Indent feature is broken on simple vanilla CDN install ...

### ISSUE THREAD

**Issue by peppies** [ckeditor/ckeditor5#6435]
I am using the Quick Start guide, using the CDN URL and copy/paste example of the Classic editor: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html#classic-editor

The indent feature appears broken/disabled. Seems to work in your demo, but not in the actual product. I was wasting time reading about plugins, npm, etc... but then I realized, this is a feature that should be working on a simple, basic install.

Apparently, it only works on LISTS? No, that's not how it works. Needs to work on paragraphs, as the tab key doesn't work for this.

What does this mean? You guys have some work to do.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. By default, Indent feature in Classic Build is enabled only for lists. To use it with other elements like paragraphs, you need BlockIndent plugin. 
To achieve this, you can [create a custom build with additional plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) or use our [online builder](https://ckeditor.com/ckeditor-5/online-builder/).
