### ISSUE TITLE
The table breaks after removing a last header row

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6437]
## 📝 Provide detailed reproduction steps (if any)

1. Insert a table
2. Put the caret in the last row
3. Create a header row
4. Delete header

### ✔️ Expected result

The row disappears properly.

### ❌ Actual result

The table breaks and the selection moves out of the table.
![Screenshot 2020-03-16 at 08 34 41](https://user-images.githubusercontent.com/20988892/76733688-9b1bcb00-6761-11ea-893d-9aa1bbbee16b.png)

## 📃 Other details

**Note**: It seems to be an old issue, it also occurs in v12.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Might be fixed by #6439 - to check.
