### ISSUE TITLE
Firefox: Invalid behavior when moving the keyboard focus to an editor using Tab

### ISSUE THREAD

**Issue by davidpolberger** [ckeditor/ckeditor5#644]
## 📋 Steps to reproduce

1. Go to https://ckeditor5.github.io/ using Firefox 55.
2. Press <kbd>Tab</kbd> six times, until the editor is focused.
3. Start typing a sentence with spaces.
4. Try to delete what you just wrote using <kbd>Backspace</kbd>.

## ✅ Expected result

The caret should appear just before the first heading. Space characters should be correctly inserted. Deleting characters using the <kbd>Backspace</kbd> key should work, without affecting other parts of the document. This is what happens when Chrome is used.

## ❎ Actual result

A new line is created before the first heading (outside of a paragraph block). Typing correctly inserts text, but spaces cannot be inserted. When an attempt is made to delete characters using <kbd>Backspace</kbd>, empty paragraph blocks are inserted.

## 📃 Other details that might be useful

![Screencast](https://user-images.githubusercontent.com/6777396/32128154-d57b1bd2-bb7b-11e7-91fd-4dfe6c7ac903.gif)

**Comment by Mgsy** [comment]
Hi, thanks for your detailed bug report. Actually, we are aware of this bug and it occurs when the editor is focused differently than by mouse left button click (see https://github.com/ckeditor/ckeditor5/issues/562). 

We have open PR which fixes this issue, so you can track it here - https://github.com/ckeditor/ckeditor5-engine/pull/1151.

**Comment by davidpolberger** [comment]
Great, thanks!
