### ISSUE TITLE
Keyboard support - mention about "Shift+Enter" and "Enter" when selection is on a widget

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#6442]
## 📝 Provide a description of requested docs changes

https://ckeditor.com/docs/ckeditor5/latest/features/keyboard-support.html

**Comment by pomek** [comment]
Enter - adds a paragraph "below" (after) the widget and put selection inside.
Shift+Enter - adds a paragraph "above" (before) the widget and put selection inside.

**Comment by niegowski** [comment]
This seems outdated.

**Comment by godai78** [comment]
Yes, this is done basically. How about closing the issue?

![Screenshot 2020-11-20 at 14.01.58.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/d9bd566d-01d9-4fdc-b6cb-d705695b2366)

**Comment by godai78** [comment]
This is done this way now:

![Screenshot 2020-11-20 at 14.01.58.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/52590543-262e-430e-a4ed-f6747df95665)

I guess there were some changes (like the soft break behaviour) in meantime. Is this still a thing? If so, I can add it to the guide like, on the go.

**Comment by niegowski** [comment]
It depends on the context (the current selection), see below in the same table:

![](https://user-images.githubusercontent.com/1232187/99803368-9f428880-2b39-11eb-989b-a72549db0088.png)

**Comment by godai78** [comment]
So this is covered, generally, I guess?

**Comment by niegowski** [comment]
> So this is covered, generally, I guess?

That's what I meant here:

> This seems outdated.

😉

**Comment by godai78** [comment]
Yeah. Let's close it then? ;)
