### ISSUE TITLE
Table properties balloon not displaying on cell multiselect in Balloon and Balloon Block editors

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6443]
## 📝 Provide detailed reproduction steps (if any)

Occurs on latest master

1. Open Ballon or Balloon Block editor
2. Select multiple cells ( with some text content )

**In Balloon editor you don't event need to add any text**

### ✔️ Expected result

Table properties balloon shows up, you are able to edit a table

### ❌ Actual result

Editor balloon toolbar shows up, you can edit only content

Sample from Balloon Block editor:
![16_table1](https://user-images.githubusercontent.com/34380544/76755842-e4c9dd00-6784-11ea-9afa-d32d8efb611a.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
So, the tl;dr is that on a multi-cell selection we should still see the table toolbar.

**Comment by Reinmar** [comment]
But what I described above would make bold, italic and other inline options inaccessible in case of table cell selection, so you won't be avle to boild multiple cells at once. In other words, it's trade off and it's not a good one. We need to find a better solution from the UX perspective.

**Comment by wwalc** [comment]
Just to not forget: we already have one solution for conflicting items (balloon rotator). Maybe using it (if does not require a lot of effort) wouldn't be as bad as leaving users with a feature that just cannot be used.

**Comment by oleq** [comment]
I stumbled upon this today again and I think we could raise the priority of this issue. This is pretty annoying.

**Comment by Reinmar** [comment]
Solution: If there is more than one range in the selection, the contextual toolbar should not be displayed. I guess we don't check that currently and that makes the contextual toolbar displayed for multi-range table cell selections.
