### ISSUE TITLE
[Safari] Balloon editor toolbar should always expand when there's enough space

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6444]
## 📝 Provide detailed reproduction steps (if any)

0. Open the balloon editor and make a selection.
1. Scale down the browser.
2. Hide the toolbar.
3. Expand the window.
4. Make a selection again.

![2020-03-16 13 11 39](https://user-images.githubusercontent.com/1099479/76757707-65d6a380-6788-11ea-983d-dfb48ab6ab68.gif)

### ✔️ Expected result

The toolbar should look like before 1.

### ❌ Actual result

The toolbar looks like after 1.

## 📃 Other details

It works correctly in other browsers because unlike Safari, they don't use polyfilled `ResizeObserver`. I think something's wrong with the polyfill, maybe it should be improved.

cc @panr 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by panr** [comment]
Oh boy... Safari 🙄

**Comment by panr** [comment]
Fun fact. Just tested it in Safari 13.1.1 which supports ResizeObserver and... it's still broken BUT... even "funnier" fact — it's also broken in other browsers... It looks like the bug lies somewhere else...

**Comment by oleq** [comment]
[It looks like we can finally get rid of the polyfill. 🎉](https://github.com/ckeditor/ckeditor5/issues/7375)

**Comment by oleq** [comment]
It looks like the resize observer does not kick in when the toolbar re-appears. It works when the editable starts to re-scale again, though. Have fun! :P
