### ISSUE TITLE
Add more buttons to Table snippets

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#6445]
## Provide a description of the task

Currently we have a very limited set of toolbar buttons in the table demos: https://ckeditor.com/docs/ckeditor5/latest/features/table.html

This no longer makes sense as we now have table selection and table styles features that, together, allow you to select an arbitrary set of cells and apply e.g. formatting such as alignment or font color/size/family to them. This is definitely cool and something that lots of our customers will do.

Besides some formatting features, **lists** should also be in the table demos as placing lists in tables is a relatively frequent use case.

**Comment by AnnaTomanek** [comment]
Let's maybe set it up like this:

*   Table |
*   Font family, Font size |
*   Bold, Italic |
*   Text alignment |
*   Numbered list, Bulleted list |
*   Indent, Outdent |
*   Link, Block quote

**Comment by panr** [comment]
@AnnaTomanek the PR is ready for review ;-) 
https://github.com/ckeditor/ckeditor5-table/pull/285
