### ISSUE TITLE
Table selection docs

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6447]
## Provide a description of the task

We need to have a place in docs where we can point to from the new release blog post regarding table selection.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: latest `master`

**Comment by AnnaTomanek** [comment]
Fixed with:

*   [x] Guide: [ckeditor/ckeditor5-table@154e582](https://github.com/ckeditor/ckeditor5-table/commit/154e582)
*   [x] API docs: [ckeditor/ckeditor5-table@2f55c6a](https://github.com/ckeditor/ckeditor5-table/commit/2f55c6a)
