### ISSUE TITLE
Shared UI and UX between CKEditor 5 and Letters

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#645]
At some point in the past Letters and CKEditor 5 diverged in terms of the UI and UX. Each project developed own solutions and at this moment this inconsistency generates lots of issues and very few benefits.

![image](https://user-images.githubusercontent.com/1099479/32221125-a1026156-be34-11e7-8596-8fd122419b51.png)

![image](https://user-images.githubusercontent.com/1099479/32221137-a881a84c-be34-11e7-8262-521a703e6875.png)

![image](https://user-images.githubusercontent.com/1099479/32221156-bdc75ee0-be34-11e7-85c6-a76e05910373.png)

![image](https://user-images.githubusercontent.com/1099479/32221149-b26ee8c4-be34-11e7-825e-b0aaf739ac9f.png)

## The problem

1. Two different UIs for very similar application imply there's no clear vision of what the whole thing should look and work like. 
1. Two UIs mean double effort when it comes to maintenance, bug fixing etc.
1. Bringing new features means again a double design/implementation effort.

## The solution

1. A single UI should be shared between the applications.
1. The UI should be simple yet beautiful. It's a good occasion to revise certain decisions, consider feedback we got and bring an even better UI.
1. The UI should be extensible.

## Mockups

**Note**:
* The icons are under development.
* The colors are under development.
* Click to enlarge.

## Icons and toolbar

The icons will be refreshed and unified. The toolbar could become totally flat.

### v1

![image](https://user-images.githubusercontent.com/1099479/32222585-25f3d174-be3a-11e7-862b-a313246e33fb.png)

### v2

![image](https://user-images.githubusercontent.com/1099479/32222618-4cdde2a2-be3a-11e7-8d9d-8c9b8d0e99e1.png)

### First step

![image](https://user-images.githubusercontent.com/1099479/32222690-8a61b48c-be3a-11e7-9978-4bf0e0995362.png)

### Second step

![image](https://user-images.githubusercontent.com/1099479/32222706-a23fbcb6-be3a-11e7-8a36-4217ff893d58.png)

### Second step (focused), alternative back navigation

![image](https://user-images.githubusercontent.com/1099479/32223363-5143bb70-be3d-11e7-8326-a73d5f4d91a7.png)

### The same UI in Letters with different colors

![image](https://user-images.githubusercontent.com/1099479/32223373-5b962216-be3d-11e7-89fa-4e1ef306f11e.png)

### CKEditor 5

![image](https://user-images.githubusercontent.com/1099479/32223394-6f79bdec-be3d-11e7-82e0-17a19f6d7756.png)

### Letters

![image](https://user-images.githubusercontent.com/1099479/32223403-7857e114-be3d-11e7-877e-e0e3c018c254.png)

## Balloon toolbar

![image](https://user-images.githubusercontent.com/1099479/32222820-10eedec6-be3b-11e7-814e-cfd246fb75ed.png)

**Comment by oleq** [comment]
Related issues:
* https://github.com/ckeditor/ckeditor5/issues/642
* https://github.com/ckeditor/ckeditor5-ui/issues/144

**Comment by pjasiun** [comment]
I have to say that I love the flat UI, you proposed. All elements look modern and cool. I also believe that we should make it clear, that the color palette (background, icons, focus, etc.) should be configurable, but the rest should be unified. Great job!

**Comment by pjasiun** [comment]
Ach, one thing I need to add is that I believe that we should avoid having drop-downs in balloon panels. Of course, it is up to the developer how he will integrate CKE5 framework, but we should not have them in our demos. For sure there should not be a drop-down in Letters block toolbar:

![screen shot 2017-10-31 at 13 36 58](https://user-images.githubusercontent.com/1166967/32224129-74db2660-be40-11e7-99f0-b73e515202e3.png)

I think that together with drop-down for styles, we should provide buttons for basic styles (P, H1-H*) and leave it up to the developer which UI he wants to use.

**Comment by oleq** [comment]
I agree that in Letters, the toolbar should be as simple as possible. The shorter path to reach the feature is the best and we can reduce the number of clicks here. 

However, in CKE5 [we need such dropdowns](https://github.com/ckeditor/ckeditor5-ui/issues/333) because the editor has more features and almost never goes fullscreen, so space is scarce and we must use it efficiently.

**Comment by RyszardB** [comment]
This is my UI proposal that I did in January of this year. Have been rejected..

![screen shot 2017-10-31 at 13 40 57](https://user-images.githubusercontent.com/17498197/32224382-7aa2180a-be41-11e7-8081-708f1ad33df8.png)

![screen shot 2017-10-31 at 13 39 51](https://user-images.githubusercontent.com/17498197/32224383-7ac655ee-be41-11e7-98a8-cd03da74027c.png)

**Comment by dkonopka** [comment]
I think it could be a good idea to give developers opportunity to get rid of dropdowns and change it to inline buttons (with their custom icons).

**Comment by oleq** [comment]
> This is my UI proposal that I did in January of this year. Have been rejected..

@RyszardB: Requirements change as the time goes by. What didn't make sense at that time (for whatever the reason) can make sense now because we understand the projects better. It's a living thing.

**Comment by wwalc** [comment]
> Ach, one thing I need to add is that I believe that we should avoid having drop-downs in balloon panels. Of course, it is up to the developer how he will integrate CKE5 framework, but we should not have them in our demos. For sure there should not be a drop-down in Letters block toolbar:

Remember that we have separate issues for heading buttons (e.g. https://github.com/ckeditor/ckeditor5/issues/455) so to some extent this problem will be solved.

**Comment by pjasiun** [comment]
> However, in CKE5 we (..) almost never goes fullscreen, so space is scarce and we must use it efficiently.

Note, that in many cases when only P, H1, H2 and H3 buttons are needed they takes **less** space than then dropdown. Especially with this flat UI.

**Comment by fredck** [comment]
Very good stuff here... well done everyone!

@oleq, I remember we also took into consideration adding the url as part of the "Open link" button. I still like that idea.

**Comment by oleq** [comment]
@fredck Yes, it's still on my TODO list. It could be useful for people reviewing their document and checking the targets of the links.

**Comment by dkonopka** [comment]
Some proposal below. 
We should decide how many characters will be optimal (and calculate it to `max-width`).

![link-preview](https://user-images.githubusercontent.com/10219857/32228692-41bce804-be4f-11e7-8c64-261d98c63709.png)

**Comment by wwalc** [comment]
I'd like to underline one problem with the width of input element and paste a screenshot from Google Docs:

<img width="650" alt="screen shot 2017-11-02 at 06 21 06" src="https://user-images.githubusercontent.com/545175/32310918-143fa75c-bf96-11e7-8b66-e8eab58a5629.png">

Basically, I'm afraid that looking nice should come in pair with usability. Having to fight with the cursor to view the URL (which is a key information for this feature) looks like a UX problem to me. And if we plan to make the input much wider, then the design should already include it, because it would simply look different.

**Comment by oleq** [comment]
@wwalc You posted the image of the intermediate "go to link" balloon and you write about the input so I'm a little bit confused here.

But if you're worried that the href input in the "edit link" balloon is not wide enough, [we already had this discussion](https://github.com/ckeditor/ckeditor5-link/issues/56#issuecomment-265418009).

If you're worried that the link href in the "go to link" will be truncated (...), the answer is basically the same. No matter how wide the balloon, there would still be some cases where the href gets truncated. Our job is to satisfy the most common ones and keep the UI clean.

**Comment by fredck** [comment]
As long as the button is a real link, so the browser will show the full URL in the "status bar", it should be fine.

**Comment by wwalc** [comment]
@oleq Thanks for the explanation. It just looked like an input element for me, thus my confusion and confusing comment (I did not read previous comments). In any case it looks like I have same thoughts as @Reinmar when it comes to the size of the input and the amount of information shown, but it's a dup of #56.

@fredck IMO we should not expect regular end users to treat the status bar as a part of the CKEditor interface.

**Comment by dkonopka** [comment]
So here are two ideas. I think the first one is a good alternative for people who don't know about existing of the status bar in the web browser. About 2nd proposal: input should be 100% width only on mouseover event. It can work with a nice smooth transition.

WDYT?


![screen shot 2017-11-02 at 15 21 55](https://user-images.githubusercontent.com/10219857/32330807-8767dcd6-bfe1-11e7-8711-eda41f422fd5.png)

**Comment by fredck** [comment]
IMHO, I don't think we should worry about it until it is a problem. KISS on the first milestone.

**Comment by wwalc** [comment]
Just to comment on @dkonopka proposal: 2nd option seems better to me as it will be usable also for people on tablets.

**Comment by oleq** [comment]
>  it will be usable also for people on tablets.

Touch devices most certainly will (eventually) get a completely different UI so I wouldn't use that as a point.

**Comment by Reinmar** [comment]
BTW, are the new designs posted somewhere? Olek showed me them but I don't see them posted anywhere. What Olek posted here in the first message are just pieces of the design, not the whole thing together. It makes it harder to analyse it.

E.g., when I saw it all for the first time there was the editor's light toolbar and the floating dark balloon next to it. I immediately got the impression that the balloon is detached from a completely new UI. It doesn't match the rest of the UI which is light and, I think, had a different sizing.

The second problem that I had is with the icons in the toolbar. They are super bold. I don't like the current serif icons because they just don't fit our use case (serif icons may work in some specific, "classical" apps, though). But those new bold icons look heavy to me and I can see that they forced you to make "Paragraph" bold too which I'm not convinced about.

Finally, it'd be good to verify how editor would look in some contexts. In most cases it's a just a piece of existing systems and websites. Its design cannot make it hard to integrate it and I have doubts about the dark colors and heavy fonts.

**Comment by scofalik** [comment]
I don't like this blue tint in the dark UI.

**Comment by Reinmar** [comment]
> I don't like this blue tint in the dark UI.

It may also cause trouble in many integrations. We always tried to use grey for the UI's body. I don't say that we must do that, but we must be careful. That's why I proposed to see integrations. It may happen that this theme doesn't even look good on ckeditor.com ;)

**Comment by oleq** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/642.

**Comment by oleq** [comment]
Branch constellation with the refreshed theme is configured in the [t/645 branch](https://github.com/ckeditor/ckeditor5/tree/t/645).

## Critical changes

* Redesigned the theme ckeditor/ckeditor5-theme-lark#123
* Updated UI components to bring the support for the refreshed Lark ckeditor/ckeditor5-ui#362
* Implemented a 2-step editing, refreshed link UI ckeditor/ckeditor5-link#165
* Simplified the text alternative UI ckeditor/ckeditor5-image#172

## Changes with new icons

* Updated icons for the refreshed Lark theme ckeditor/ckeditor5-alignment#19
* Updated icons for refreshed Lark theme ckeditor/ckeditor5-basic-styles#63
* Updated icons for the refreshed Lark theme ckeditor/ckeditor5-core#118
* Updated icons for the refreshed Lark theme ckeditor/ckeditor5-list#92
* Updated icons for the refreshed Lark theme ckeditor/ckeditor5-undo#77

## Minor changes

* Updated documentation and samples to consider the updates in the Lark ckeditor/ckeditor5#800
* Minor adjustments in toolbar configurations ckeditor/ckeditor5-autoformat#47
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-adapter-ckfinder#7
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-block-quote#16
* Minor adjustments in toolbar configurations ckeditor/ckeditor5-clipboard#43
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-easy-image#12
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-cloudservices#10
* Minor adjustments in toolbar configurations ckeditor/ckeditor5-editor-classic#68
* Minor adjustments in toolbar configurations ckeditor/ckeditor5-editor-inline#30
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-editor-balloon#13
* Minor adjustments in toolbar configurations ckeditor/ckeditor5-engine#1264
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-heading#94
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-enter#52
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-markdown-gfm#18
* Minor adjustments in toolbar configurations ckeditor/ckeditor5-typing#135
* Minor adjustment in toolbar configuration ckeditor/ckeditor5-upload#82

**Comment by Reinmar** [comment]
🎉 
🎉 🎉 
🎉 🎉 🎉 
🎉 🎉 
🎉 

Bravo guys! Waiting for the summary.

**Comment by oleq** [comment]
Hurray!  🎉

Here's the quick summary of the research we did over the past two months hopefully explaining decisions we made and answering the most obvious questions about the new UI of the editor.

**Note**: The screen-shots below may not correspond with the current stage of development. They are slightly outdated and I used them only to present some concepts/problems that we stumbled upon. For the latest UI, go straight to master in ckeditor5 or [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/index.html) tomorrow.

## Icon thickness

We started with 1px icons just like before refactoring. They looked great on Retina but soon we found out there are lots of rendering issues with complex shapes and curves on LoDPI screens (jagged edges etc.).

We then decided to switch to 2px icons, which solved the issue (worked well on LoDPI and Retina) but they looked very heavy as compared to other pieces of UI, e.g. fonts in dropdowns and CMSs that may use CKEditor 5.

Finally, we decided to trade-off some crispness and the feel of a lightweight UI and we stopped at 1.5px for straight lines. It's readable on LoDPI screens but still not overwhelming as 2px. Yes, we worked on the icons thrice…

[There's a follow–up discussion about the icons and possible LoDPI issues.](https://github.com/ckeditor/ckeditor5/issues/808)

## Paddings in the UI

The very first idea was a padding-less UI e.g. with buttons using 100% height of the toolbar. But then we found out there are two main problems with that approach:

1. Such buttons collide with the arrow attaching the floating toolbar to the selection. There's no way to style the arrow to provide a smooth transition. It will always stand out in some arrangements. <img src="https://user-images.githubusercontent.com/1099479/35738696-e107ad52-082f-11e8-921c-7afa0a04919e.png" width="370" />
1. A padding less toolbar looks weird when it wraps to the next line (narrow UI). There's no spacing between toolbar buttons and there's no way in CSS to tell which items have been wrapped and give them some spacing.
3. If we go with padding-less UI, we must stick to that approach wherever possible. And that includes forms, like the link/image form and any (possibly more complex) that come in the future. Mostly because the transition from a padding-less UI to a padded one feels just horrible (e.g. clicking link button and switching to the link form).
   <img width="785" alt="screen shot 2018-02-02 at 13 28 11" src="https://user-images.githubusercontent.com/1099479/35738821-44ace854-0830-11e8-8408-47b06db176f9.png">

   And this is where actual hell begins:
   * A padding-less forms mean there's no way we can use labels when they are necessary (and they will be). There's no space for them.
   * Label-less inputs look strange when they have a value but no clue what the value is (the example with width/height). What is 220? An age, size or year? If we added the labels it would mean that in some languages (e.g. German), the labels will expand the UI horizontally to enormous sizes. <img width="778" alt="screen shot 2018-02-02 at 13 29 50" src="https://user-images.githubusercontent.com/1099479/35738898-6118d6c4-0830-11e8-9592-fdd843013bad.png">
   * Padding-less UI means we must figure out how to tell the user that inputs are focusable (they have no boundaries, they look just like a text) and then somehow announce the focus, but there's no way to do that. 
   * Padding-less UI means that if we want to advertise the focus of inputs (and there's no other way than material design approach), we'll hit the arrow (triangle) problem like in the toolbar. The input "cuts" the arrow off if it gets any side border of a different color (the "http://example.com" case).
   * In a padding-less UI we can only build the UI sideways. In truth, everything is a toolbar. If there's a form with 2+ inputs, we're doomed because it will consume most of the horizontal space available in the viewport. There's no way to switch to multi–line forms etc.
   * A padding-less UI means action buttons (save, cancel, etc.) must span 100% height of the UI. When they got background colors, we lose the contrast and a perception where the floating UI starts and what is beyond (below) it. The color (e.g. green) does not go well with the border of the balloon.

So (a very) long story short, because:

1. We want to use balloon arrows because they are great when the precision matters (e.g. they're awesome when indicating forward and backward selection in the balloon editor).
2. We want to have a freedom to use labels in complex forms that may arrive.
3. We want to be able to build mutli–row forms in the future in the balloons.

we decided to go with paddings in the UI — it's safer and gives us more possibilities.

## Bright UI vs. inverted colors

The very first idea was adopting Letters–style UI which is dark (inverted) by default. Then we realized that even if it looks great it has some issues.

Most of the apps around the web use a bright UI. CKEditor 5 is a component which should work out–of–the–box for most use cases, which means it should not stand out and should not require additional work for developers.

We also considered a hybrid: white toolbar and dark balloons. The problem was the both UIs looked like pieces of a different application. They contradicted each other and the overall feeling was that the UI lacks consistency, as if the team doesn't know what is best for the project.

That's why we went with a bright UI but used a slightly gray background for the toolbar by default ([a follow–up about the gradient](https://github.com/ckeditor/ckeditor5/issues/805)). It's the safest decision here.

Still, in our documentation, we'll maintain [an example](https://docs.ckeditor.com/ckeditor5/latest/examples/framework/theme-customization.html) (guide) with a dark theme created just by overriding CSS variables (which is pretty easy). We can call it now "an official customization". An inverted theme also became one of the manual tests in ckeditor5-theme-lark.

## Full-height separators

We decided that at the current stage of development, we can ignore toolbars wrapping to the next line. We also decided that we will advise (in examples and default configs) the usage of toolbar separators after dropdowns (e.g. heading) and as a grouping mechanism, which especially looks awesome in the inverted theme.

<img width="418" alt="screen shot 2018-02-02 at 13 48 09" src="https://user-images.githubusercontent.com/1099479/35738938-760fa9cc-0830-11e8-88f7-f1f58bb51e1a.png">

## 2-step editing link and simplified text-alternative

We decided to refresh the way of creating links in this refactoring. Mostly because in the old UI there was no possibility to open the link in new tab/window and we already [knew about that](https://github.com/ckeditor/ckeditor5-link/issues/31). 

The refreshed UI comes with a keyboard support. What is also important, there is no difference between the toolbar height between editing steps, which would not be possible if we went with the padding-less UI. Also, the new link form saves a lot of space (143px of height vs 53px!).

<img width="440" alt="screen shot 2018-02-02 at 15 49 10" src="https://user-images.githubusercontent.com/1099479/35739015-aeb3bb2e-0830-11e8-9269-7fd422ee28b1.png">

<img width="421" alt="screen shot 2018-02-02 at 15 49 20" src="https://user-images.githubusercontent.com/1099479/35739023-b22c5842-0830-11e8-8483-c33d90ca2f2b.png">

## What's next?

We're importing the new theme to Letters and designing some icons unique for the application. Soon we'll make a public demo. Stay tuned!

**Note: Please start new discussions in the [follow-ups](https://github.com/ckeditor/ckeditor5/labels/module%3Atheme-%2A) instead of bloating this issue even further.** Please mark them with the `module:theme-*` label, if possible.

## Bonus (click to open)

![new-theme-transition](https://user-images.githubusercontent.com/1099479/35739226-3d784046-0831-11e8-9528-ed16a9df86f3.gif)
