### ISSUE TITLE
Add link to creating plugin tutorial in plugin overview section

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6463]
## 📝 Provide a description of requested docs changes

Currently if you go to [plugins overview](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/plugins.html), there is a short paragraph about [creating plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/plugins.html#creating-plugins), but it links only to _quickstart_ and _custom builds_ sections. However, there is a whole [tutorial on creating custom plugins](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) in _framework_ subpage.  

My proposition is to add this link, because most often this is exactly what someone is looking for when entering this page and it will redirect people straight to what they need.

**Comment by Mgsy** [comment]
@FilipTokarski, can you create a PR for it?
