### ISSUE TITLE
Decoupled Editor does not render properly with React

### ISSUE THREAD

**Issue by barreeeiroo** [ckeditor/ckeditor5#6467]
When I try to load CKEditor using DecoupledDocument build, it does not render "the document". Instead, it just takes the background and places above the textbox.

![image](https://user-images.githubusercontent.com/19251112/77166481-9eda8500-6ab4-11ea-86d5-bea35c73def3.png)

---

**View.tsx**

```
//@ts-ignore
import CKEditor from '@ckeditor/ckeditor5-react';
//@ts-ignore
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
import '@ckeditor/ckeditor5-build-decoupled-document/build/translations/es';

<CKEditor
    editor={DecoupledEditor}
    config={{
        language: 'es',
    }}
    onChange={(event: any, editor: any) => console.log({event, editor})}
    onInit={(editor: any) => {
        console.log('Editor is ready to use!', editor);
        editor.ui.getEditableElement().parentElement.insertBefore(
            editor.ui.view.toolbar.element,
            editor.ui.getEditableElement()
        );
    }}
    data="<p>Hello from CKEditor 5 f!</p>"
/>
```

**package.json**

```
"@ckeditor/ckeditor5-build-classic": "^18.0.0"
"@ckeditor/ckeditor5-build-decoupled-document": "^18.0.0"
"@ckeditor/ckeditor5-react": "^2.1.0"
```

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. To style decoupled document editor like in the sample,  first use this markup in your React component:

```js
render() {
        return (
          <div className="App">
          <h2>CKEditor 5 using a custom build - DecoupledEditor</h2>

          <div className="document-editor">
            <div className="document-editor__toolbar"></div>
            <div className="document-editor__editable-container">
            <CKEditor
              onInit={ editor => {
                  console.log( 'Editor is ready to use!', editor );
                  window.editor = editor;

                  // Add these two lines to properly position the toolbar
                  const toolbarContainer = document.querySelector( '.document-editor__toolbar' );
                  toolbarContainer.appendChild( editor.ui.view.toolbar.element );
              } }
              onChange={ ( event, editor ) => console.log( { event, editor } ) }
              editor={ DecoupledEditor }
              data="<p>Hello from CKEditor 5's DecoupledEditor!</p>"
            />
            </div>
          </div>
        </div>
        );
    }
```
And then in your css file add all [styles for decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html#styles).
Here, you can read more about [structuring html for decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html) and basic [decoupled document api](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#example-decoupled-editor).

Hope that helps!

**Comment by barreeeiroo** [comment]
Hi @FilipTokarski,

Yeah, it was that I have not added the missing divs and styles, thank you. However, I would understand that it should be done automatically. Else, it is like installing Classic Editor and just applying a bunch of CSS properties.

And just another question: the demo Editor (https://ckeditor.com/ckeditor-5/demo/#document) does not seem to be the same as the one in documentation (https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html).
See that when you focus the last one, a blue "focused" outline appears. Is it possible to get the styles that have been used in the demo one?

**Comment by FilipTokarski** [comment]
To get focus styles like in demo page, you can add these to your html:
```
.ck.ck-editor__editable:not(.ck-editor__nested-editable).ck-rounded-corners.ck-focused{
    border: 1px solid transparent;
    box-shadow: 0 0 5px rgba(0,0,0,.1);
}
```

**Comment by barreeeiroo** [comment]
Yup, it works! Thanks @FilipTokarski 

However, I've used this one:

```
.ck.ck-editor__editable:not(.ck-editor__nested-editable).ck-rounded-corners{
    border: 1px solid transparent;
    box-shadow: 0 0 5px rgba(0,0,0,.1);
}
```

So it would remain the same for both focused and not focused.
