### ISSUE TITLE
Trigger 'Height:Change' not working

### ISSUE THREAD

**Issue by Pavel177** [ckeditor/ckeditor5#6468]
Hallo,

in the documentation i found 'Height:Change' event to trigger Size changes. Unfortunately it doesnt work.

You can see my code below: 

```
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .then( editor => {
        editor.model.document.on( 'change:height', (eventInfo, name, value, oldValue) => {
                console.log('height');
            } );
         } )
        .catch( error => {
            console.error( error );
        } );
</script>
```
Could you please tell me, what am i doing wrong? 

thanks Pavel

**Comment by Reinmar** [comment]
The `change:height` event is fired by only one thing and this is table cell properties panel. It's a completely different thing. It has nothing to do with editor size.

As for editor size – there's no event for that. You would need to use DOM events (possibly a resize event on the main editable element) to learn about editor size changes.
