### ISSUE TITLE
ViewRoot should be created together with the editor structure

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#647]
After https://github.com/ckeditor/ckeditor5-ui/issues/262 creating of `viewRoot` is moved to UI initialization it means that `viewRoot` is not available before the UI init. View root is more an engine not UI so would be good to have it created together with the editor structure.

**Comment by oleq** [comment]
@oskarwrobel Can you prepare a PR for this?

**Comment by oskarwrobel** [comment]
Sure. I'm on it.

**Comment by oskarwrobel** [comment]
@oleq ready to review.
