### ISSUE TITLE
Allow overriding existing commands

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#6470]
Perhaps I'll start with my motivation. I'm using Mention feature to insert internal links. Internal link can be inserted also in other ways from the UI.

I have defined my model element `InternalLink` which defines upcasts, downcasts etc. and I'd like Mention plugin to insert such model element into the document upon the selection of the appropriate item from the mention list. However, looking at the `MentionCommand` plugin implementation it's clear that the command inserts `mention` model element and this is not configurable.

So the next idea I had was to replace the "command handler" class - `mention` command will be handled by my `CustomMentionCommand` instead of the default one. 

So what I came up with is the following:

```javascript
export default function MentionCustomization(editor) {
        // setTimeout will make sure this will not be replaced by the standard MentionCommand implementation
	setTimeout(() => {
		editor.commands.add('mention', new CustomMentionCommand(editor));
	}, 1000);
}

class CustomMentionCommand extends Command {
	execute(options) {
		// ... insert the InternalLink object
	}
}
```

This works but is of course super ugly. Unfortunately there does not seem to be support to override an existing command object. Currently, it seems like "whoever sets the command last wins". 

Possible way to handle this would be to assign a priority to the command which would change the game to "whoever has the highest priority wins" with the possibility for the higher priority command to fall through and delegate to the lower priority command if it decides it does not want to handle the command after all.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In order to modify _mention_ command and use your own implementation, you can try creating a custom plugin like this:
```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import Command from '@ckeditor/ckeditor5-core/src/command';

export default class myPlugin extends Plugin {
    afterInit(){
        const editor = this.editor;
        editor.commands.add( 'mention', new myCommand( editor ) );
    }
}

class myCommand extends Command {
    execute() {
        console.log( 'My custom mention command executed' )
        // Do anything you want..
    }
}
```

By adding a custom command in the `afterInit` method here, you will be able to override the  _mention_ command that is already registered in the editor. `afterInit` also makes sure that all other commands are already loaded and you can safely override them without running into priority issues.
You can then simply import and use this plugin, just as you would use any other.

Hope that helps!

**Comment by zadam** [comment]
Thank you Filip, this is much better!
