### ISSUE TITLE
PendingActions in online builder.

### ISSUE THREAD

**Issue by tustc79** [ckeditor/ckeditor5#6471]
The PendingActions plugin is not available in the online builder (https://ckeditor.com/ckeditor-5/online-builder), while AutoSave is. 

This plugin add some very useful functionality as seen on https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html

**Comment by ma2ciek** [comment]
Hi @tustc79,

The pending actions is required by the `Autosave` feature, thus, it's bundled into the generated build when the `Autosave` plugin is selected. So AFAIS there's no need to add this plugin to the online builder plugin list. Am I right?

**Comment by tustc79** [comment]
Hi ma2ciek,

It appears you are right and it seems to be included. The following line in the tutorial threw me off...

"The PendingActions plugin is unavailable in any of the builds by default so you need to install it."

So when I tried to do that I could not find it.

But thanks for resolving this for me!

Erwin

**Comment by ma2ciek** [comment]
Thanks for pointing this out, maybe we could add a note that the builds created by the online builder may have it installed. cc @mlewand

**Comment by mlewand** [comment]
Thanks for pointing this out @tustc79 - @ma2ciek yea, it's good idea to update the docs there. I'll prepare the PR shortly.

**Comment by mlewand** [comment]
Actually after attempting to document I realized using autosave to load pending actions is just a workaround.

I think that `PendingActions` plugin falls into the bag of API-oriented plugins, like `TextWatcher`. So I'd think we should consider adding api-oriented plugin to the online builder.

**Comment by mlewand** [comment]
I opened issue in the online builder project to address this problem.
