### ISSUE TITLE
Adjust docs for monorepo

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6479]
## Provide a description of the task

*   [x] scripts for building the docs (p3) - @pomek verified that both `yarn run docs` and integration build script for the entire CKEditor ecosystem will work out-of-the-box with no further changes required.
*   [x] [dev articles in the docs (p4)](https://github.com/ckeditor/ckeditor5/issues/6523)
*   [x] markdown files in subpackages, like main `README.md` or `api/docs/*.md` like [here](https://github.com/mlewand/ckeditor5-monorepo-test/blob/880aaabffa8a5f5affe85553b27ab01f6140530d/packages/ckeditor5-link/docs/api/link.md#L23-L30) (lines 23-30)
*   [ ] [knowledge base (p4)](https://github.com/ckeditor/ckeditor5/issues/6525)

## 📃 Other details

This is a subtask of [#6466](https://github.com/ckeditor/ckeditor5/issues/6466).

**Comment by pomek** [comment]
> scripts for building the docs

In CKEditor 5 repository works without any changes.

I needed to upgrade our documentation builder because now it does not need to bootstrap anything. Just a clone monorepo and link dependencies. And it's working.

**Comment by mlewand** [comment]
All right our public docs are done, except #6770 which has been extracted.
