### ISSUE TITLE
Table properties balloon is inaccessible when editor is near the top of the page

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6482]
## 📝 Provide detailed reproduction steps (if any)

1. Open editor with table + table properties
2. Make sure there is no content above the editor
3. Create a table and open table/cell properties balloon

### ✔️ Expected result

Balloon opens at the bottom of the table, you can reach every option

### ❌ Actual result

Balloon opens on the top of the table. It's hidden under browser toolbar and it's inaccessible:

![24_table1](https://user-images.githubusercontent.com/34380544/77402623-3a1e7380-6daf-11ea-95d0-9a7491fa9c06.gif)

## 📃 Other details
* to reproduce this, there should be no/very little content above the editor
* happens since introduction of table properties
* Browser: any
* OS: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
I'm pretty sure it's a dup but I cannot find the original issue.

**Comment by Mgsy** [comment]
>I'm pretty sure it's a dup but I cannot find the original issue.

I had the same feeling and couldn't found the proper issue 😄 But finally, I got it - https://github.com/ckeditor/ckeditor5/issues/6181
