### ISSUE TITLE
Parent Element becomes null after using Model writer methods

### ISSUE THREAD

**Issue by Shankar26G** [ckeditor/ckeditor5#6483]
const sourceRange = writer.createRange(writer.createPositionAt(parentElement, index));
          sourceRange.start.offset = 24;
          sourceRange.end.offset = 30;
          writer.setAttribute('highlight', 'yellow', sourceRange);

  After writer.setAttribute is executed , the parent element becomes null.

It is same when i use writer.insertText() method.	

Please let me know if i am using the API wrongly or it is the actual behaviour?

IMAGE BEFORE USING WRITER METHOD:

<img width="576" alt="TextProxy With Parent Element" src="https://user-images.githubusercontent.com/23693720/77407841-cd21d280-6ddc-11ea-9136-fba7c24a53e2.png">

IMAGE AFTER USING WRITER METHOD:
<img width="576" alt="Parent Element as null" src="https://user-images.githubusercontent.com/23693720/77407952-00646180-6ddd-11ea-92e2-c93b260dd998.png">

**Comment by Reinmar** [comment]
You're relying on a text proxy here. Text proxy is a temporary view of a text node fragment. It's valid only until you make any changes to the document. Once you change the model, the proxy becomes invalid. 

Besides, you should not modify offsets of positions inside ranges. Those are all readonly properties.

**Comment by Shankar26G** [comment]
Thanks ReinMar for the response.
Please let me know how do i find the range of specific text in the document? 
And how do i replace the text? I dont find replace method in the writer.
Thanks.
