### ISSUE TITLE
Dynamic config attribute for CKEditor5

### ISSUE THREAD

**Issue by ijh5005** [ckeditor/ckeditor5#6488]
## Provide a description of the task
Hi, I'm trying to dynamically update the toolbar programmatically.

_What steps should be taken to fulfill the task?_

If I start with this code...

...
...
// initial config
const config = {
  plugins: [ Bold, Italic],
  toolbar: [ 'bold', 'italic' ]
};
...
...
<CKEditor
          editor={ ClassicEditor }
          config={ config }
          data='<p>Hello from CKEditor 5! </p> '
  />
...

How would I change the config to have the UI update.
// final config
// note the config changed from the initial value
const config = {
  plugins: [ Bold ],
  toolbar: [ 'bold' ]
};

## 📃 Other details

* Browser: …
Chrome
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Mgsy** [comment]
Hi! There's no possibility to manage the config dynamically. If you'd like to update the editor with your new config, you have to [destroy](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-destroy) the editor and [create](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#static-function-create) it again with a new config.

**Comment by danwellman** [comment]
Can you provide some more information on how to do this please @Mgsy ?

I have tried to do this following the API docs, but I have found that the new editor gets created _outside_ of the original `<ckeditor>` element, and as such loses it's form bindings.

I am recreating the editor (to pick up config changes) like this:

    setTimeout(() => {
      this.instance.editorInstance.destroy().then(() => {
        const editorBase = document.querySelector('#ckEditor');
        this.Editor.create(editorBase, this.rteConfig);
      });
    });
