### ISSUE TITLE
Editor doesn't work when using Symbol polyfil

### ISSUE THREAD

**Issue by dovydaskukalis** [ckeditor/ckeditor5#6489]
## 📝 Provide detailed reproduction steps (if any)

Due to this issue https://github.com/babel/babel/issues/6010, the editor fails to initiate because [this](https://github.com/ckeditor/ckeditor5-utils/blob/8846e660d5e7e9c766d84c1e181456d1f308d00b/src/observablemixin.js#L274) always returns true even when it shouldn't. Another piece of code with the same issue is [here](https://github.com/ckeditor/ckeditor5-utils/blob/8846e660d5e7e9c766d84c1e181456d1f308d00b/src/observablemixin.js#L175). Changing `observablePropertiesSymbol in this` to `this[observablePropertiesSymbol]` and `observablePropertiesSymbol in observable` to `observable[observablePropertiesSymbol]` makes the editor work fine.

I am aware it only supports modern browsers however without these changes it does not work on mobile apps built with Meteor or any other tool that adds this polyfil. As it's a simple fix, please consider making these changes 🙂

### ✔️ Expected result

Editor works with Symbol polyfil.

### ❌ Actual result

Editor doesn't load at all.

**Comment by Reinmar** [comment]
Hi! Thanks for a detailed issue report. If the mentioned change solves the issue, then I think we'll be fine with it. Could you make a PR perhaps?

**Comment by dovydaskukalis** [comment]
Sure, will do.
