### ISSUE TITLE
Unable to type in the editor

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#6495]
Alright, this is a very weird issue that it seems I'm able to constantly reproduce, but only with given text. Paste the following in CKEditor:

Therefore I think it could make sense to enlarge the CKEditor 4 toolbar even more 😱 by adding the Find button, e.g. next to Maximize.

Then **start writing exactly this sentence, in the same paragraph:** In order to use the Replace feature

Expected result:

"In order to use the Replace feature" is typed in the editor.

Current result:

![](https://user-images.githubusercontent.com/545175/77525711-bab1a280-6e89-11ea-8254-221db91ae169.png)

Confirmed on https://ckeditor.com/ckeditor-5/demo/

The emoji was inserted using mac native emoji dialog (Ctrl+Cmd+space), if that makes any difference.

**Comment by Reinmar** [comment]
@niegowski is it resolved by the PR that you're working on?

**Comment by niegowski** [comment]
Seems that this is related to #3147 (fix for that issue fixes this one).

**Comment by mlewand** [comment]
Great to hear this, I've been hitting this issue too :+1:
