### ISSUE TITLE
Tooltips are missing in table properties

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6497]
## 📝 Provide detailed reproduction steps (if any)

Labels and tooltips are missing in table and table cell props dialogs. None of the buttons, such as alignment or color picker have them.

![](https://user-images.githubusercontent.com/156149/77556861-4ee72e00-6eb9-11ea-9dbb-d65ebccda78b.png)

It seems that they are not populated somewhere.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I can see they were included in `contexts.json` so they were supposed to be defined.

![](https://user-images.githubusercontent.com/156149/77557341-f1071600-6eb9-11ea-8d3e-d0bf805d894d.png)

**Comment by panr** [comment]
PR is ready.
