### ISSUE TITLE
Angular 9.1.0 npm install error.

### ISSUE THREAD

**Issue by blueiceprj** [ckeditor/ckeditor5#6499]
## 📝 Provide detailed reproduction steps (if any)

After angular 9.1.0 upgrade "npm install" -> postinstall: "ngcc" getting error.

### ❌ Actual result

Error: Error on worker #7: Error: Expected UMD module file (/Volumes/HDD2/blueice/repos/framework/cloud/FWBuilder/ui/ams-ui/node_modules/@ckeditor/ckeditor5-angular/node_modules/@ckeditor/ckeditor5-watchdog/src/utils/getsubnodes.js) to contain exactly one statement, but found 2.
    at UmdReflectionHost.computeUmdModule (/Volumes/HDD2/blueice/repos/framework/cloud/FWBuilder/ui/ams-ui/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:73:23)
    at FactoryMap.factory (/Volumes/HDD2/blueice/repos/framework/cloud/FWBuilder/ui/ams-ui/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:30:84)

## 📃 Other details

* Browser: 
* OS:Mac OS
* CKEditor version: 18.0.0
* Installed CKEditor plugins:
"@ckeditor/ckeditor5-angular": "^1.2.2",
"@ckeditor/ckeditor5-build-classic": "^180.0",
"@ckeditor/ckeditor5-build-decoupled-document": "^18.0.0",
"@ckeditor/ckeditor5-watchdog": "^18.0.0",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Could you check if the [following solution](https://github.com/ckeditor/ckeditor5-angular/issues/178#issuecomment-602232373) solves your problem?

**Comment by blueiceprj** [comment]
Hi! Thank you so much. I have resolved. 
- removed node_modules, packege-lock.json
- ng update
- npm update
- npm install
