### ISSUE TITLE
The FormHeaderView comoponent needs some refactoring and clean-up

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6507]
## Provide a description of the task

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6109.

* [x] [There's an orphan stylesheet left in ckeditor5-table.](https://github.com/ckeditor/ckeditor5-table/blob/master/theme/formheader.css#L1-L11)
* [x] [Code style](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/components/formheader/formheader.css#L11) 😛
* [x] [These are not component wireframe](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/components/formheader/formheader.css#L16-L23) styles. They should definitely land in ckeditor5-theme-lark.
* [x] [Docs say ](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/formheader/formheaderview.js#L18):
   > the component contains a bolded label view that has to be set

  but then the [`options.label` is optional](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/formheader/formheaderview.js#L35). Why?

cc @jodator

**Comment by jodator** [comment]
Ugh :( sorry for that. I'll read those changes to know those CSS better.

**Comment by panr** [comment]
OK, made the changes.
