### ISSUE TITLE
Online Builder does not include the new tableselection function

### ISSUE THREAD

**Issue by fkuhrt** [ckeditor/ckeditor5#6508]
I wanted to use the latest table selection feature but the Online Builder (https://ckeditor.com/ckeditor-5/online-builder/) as custom build seems that it is not yet included . Here my build zip (https://cke5-online-builder.cke-cs.com/download/71tz3lkrhro4-jpjln4dtwi2i/ckeditor5.zip) and my online sample: https://yogawerkstatt.io/ck5/sample/

It only works when downloading the CKEditor Classic https://ckeditor.com/ckeditor-5/download/

When will it be available in the Custom Online Builder?

**Comment by mlewand** [comment]
TableSelection plugin is not listed there, because it's a dependency of a standard Table plugin. So by adding table you have table selection out of the box.

Your sample has no table selection because it has a previous release, `v17.0.0` you can check this by logging `window.CKEDITOR_VERSION` variable.

**Comment by fkuhrt** [comment]
Okay, so how can I build with the latest version (v18.0.0) on https://ckeditor.com/ckeditor-5/online-builder/ 
Thanks.

**Comment by mlewand** [comment]
@fkuhrt you made us realize that online builder is generating an outdated version. I'm investigating it and pass it on. This should be addressed today, I'll let you know once that's fixed.

Sorry for inconvenience.

**Comment by ma2ciek** [comment]
We updated the online-builder so the issue should not occur anymore.

Please, try again, and sorry for the inconvenience.

**Comment by fkuhrt** [comment]
### Yeah! 
Works like a charm. Thanks for the quick fix. 
/ Fred
