### ISSUE TITLE
How to make the marker to be displayed in the document with color?

### ISSUE THREAD

**Issue by Shankar26G** [ckeditor/ckeditor5#6509]
writer.addMarker( "search:blue", {range: range, usingOperation: false} );

Above code does not generate span in the view . Hence the markerline and marker dot is not visible.

<span class="ck-user__marker ck-user__marker--0" data-name="test" data-session-id="xVBS_ns32YyvLg33AAHD">
 
 ​<span class="ck-user__marker-line">
 <span class="ck-user__marker-dot"></span>
 </span></span>

Please let me know how to add marker and view it in the document.  Any sample code will be very useful for my implementation of find functionality.

Thanks.

**Comment by Shankar26G** [comment]
<img width="576" alt="Marker" src="https://user-images.githubusercontent.com/23693720/77750001-05c5e400-7049-11ea-953e-fb741b58d383.png">

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Adding a marker to your model only, will not make it look highlighted in the view. To achieve this, you also need to add a [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) using [marker-to-highlight downcast helper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcasthelpers-DowncastHelpers.html#function-markerToHighlight). You can do it like this:
```js
// conversion between model and view
// don't forget to add a CSS class for 'my_marker_css_class' in your html file
editor.conversion.for( 'downcast' ).markerToHighlight( { model: 'my_marker', view: { classes: 'my_marker_css_class' } } );

// create a marker
editor.model.change( writer => {
    writer.addMarker( "my_marker", {range: range, usingOperation: false})
} );
```

You can start with this snippet and then further modify it to fit your particular needs.
Hope that helps!

**Comment by Shankar26G** [comment]
Thanks Filip Tokarski. Let me try and get back to you.

**Comment by Shankar26G** [comment]
Filip Tokarski, It is working like charm.
Thanks a lot for the help. Really appreciate it
