### ISSUE TITLE
how to use the ckeditor5‘s image upload in thymeleaf，the document makes me consufed

### ISSUE THREAD

**Issue by dsfdsfdsf123** [ckeditor/ckeditor5#6513]
what is the the column upload ？
how to get the column upload？Object Promise

**Comment by Mgsy** [comment]
Hi, I'm sorry, but I don't understand your issue. Please, describe it more precisely - what you'd like to achieve, which plugins do you use, which technologies you use etc.

**Comment by dsfdsfdsf123** [comment]
ckeditor5，how to change language in it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kacper Tomporowski"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午2:40
收件人:&nbsp;"ckeditor/ckeditor5"<ckeditor5@noreply.github.com&gt;;
抄送:&nbsp;"刘刚"<860721890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ckeditor/ckeditor5] how to use the ckeditor5‘s image upload in thymeleaf，the document makes me consufed (#6513)





 
Hi, I'm sorry, but I don't understand your issue. Please, describe it more precisely - what you'd like to achieve, which plugins do you use, which technologies you use etc.

**Comment by Mgsy** [comment]
>ckeditor5，how to change language in it?

Please, see the guide about [setting UI language](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html).
