### ISSUE TITLE
Can you please add feature to render MathML to target div. mathtype working in CKeditor but there is no documentation how we can show MathML to target div 

### ISSUE THREAD

**Issue by phpdev1995** [ckeditor/ckeditor5#6515]
Can you please add feature to render MathML to target div. mathtype working in CKeditor but there is no documentation how we can show MathML to target div

**Comment by FilipTokarski** [comment]
Hi, thanks for this insight. To render MathML formulas on some other website, you can use [MathJax library](https://www.mathjax.org/). You can just load their scripts via CDN and everything should work fine.
Also please note, that if you will have any problems/questions regarding the use of MathtType itself, that are not strictly connected to CKEditor, you can ask them on [Wiris MathType repository](https://github.com/wiris/html-integrations)
