### ISSUE TITLE
Stylesheet of the page clash into ckeditor

### ISSUE THREAD

**Issue by maxcuttins** [ckeditor/ckeditor5#6516]
## 📝 Provide detailed reproduction steps (if any)

1. load the editor in a page with the reset of all CSS styles (ie: bold and italic included).
2. open the ckeditor and write some text
3. you'll not see any bold or italic style.

### ✔️ Expected result
To see ckeditor formatting

_What is the expected result of the above steps?_

### ❌ Actual result
No bold or italic in pages with full reset.

_What is the actual result of the above steps?_

## 📃 Other details

* CKEditor version: 5.18
* Installed CKEditor plugins: none

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. From what you say, I assume that your css reset is overriding editor styles, so the behaviour here is correct. Please make sure to preserve and not to override your default editor styles with other css.

**Comment by maxcuttins** [comment]
I'm not overriding editor styles.
My reset is casted at the beginning.
Editor CSS are not touched in any way.
But there are not rules in your CSS about B/Strong and I/italic
So, i'm not overridding any editor style, instead the editor is expecting to use browser default CSS which has been resetted by my reset.

Take a look: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#the-full-list-of-content-styles

Do you see any rules about Bold or Italic?

**Comment by robclancy** [comment]
You need to provide your own base content styles for somehting like that. The way ckeditor works is to use minimal styles needed to work, so you have control over how things look. For us that works well but we also wanted to share a class to apply these styles that we put on the editor and the resulting content which I wish was better supported.  

But if your site doesn't style `<strong>` as bold then neither will ckeditor.

**Comment by maxcuttins** [comment]
I didn't support in the backend.
I active a browser's like CSS support per case by using specific class ".text".
I don't want bold or italic to be spanned over all the project.
Of course CKeditor is used to edit where the .text class is active but the editor fail to see basic style.

**Comment by robclancy** [comment]
That's why you can wrap the editor and where you display the content in a
class. I did this but in a different way to add a content class to the
editors text section.
I'll link tommorow when on the computer if you're interested.
