### ISSUE TITLE
Can't click to work on anything before or after a table when there is only a table

### ISSUE THREAD

**Issue by robclancy** [ckeditor/ckeditor5#6518]
## 📝 Provide detailed reproduction steps (if any)

To make sure this wasn't something we did I went to the docs demo, deleted all content, then inserted a table. Now no matter where I click in the editor it will focus the table cell.

### ✔️ Expected result

Click away from the table and just get focus before or after it to continue writing.

### ❌ Actual result

Clicking away from the table when there is no other content before or after it will just refocus the table cell.

## 📃 Other details

* Browser: Chrome and Firefox tested
* CKEditor version: 18 I assume the demo is on.
* Installed CKEditor plugins: Whatever is on the demo.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. It's a known issue which affects all widgets. Right now, there's no "easy" way to move the selection before/after a widget if it's the only element in the document. 

However, we've implemented a simple workaround - you can press <kbd>Shift</kbd> + <kbd>Enter</kbd> to insert a new paragraph before the widget and <kbd>Enter</kbd> to insert it after the widget.

For more information, please see the following issue - https://github.com/ckeditor/ckeditor5/issues/407.

**Comment by robclancy** [comment]
When? Because I tried that. When you select the whole widget?

**Comment by Mgsy** [comment]
>When? Because I tried that. When you select the whole widget?

Yes, you have to select the whole widget, then you'll be able to insert new paragraphs using keystrokes I've mentioned above.
