### ISSUE TITLE
How to stop adding newline with Ctrl + Enter?

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#6519]
I have the following code:

```
this.editor.keystrokes.set('Ctrl+Enter', (ev, cancel) => {
            ev.preventDefault();
            ev.stopPropagation();

            cancel();

            // this.trigger('onCtrlEnter', ev.domEvent);
        });
```

I just don't want the newline after Ctrl + Enter is executed...

**Comment by Mgsy** [comment]
Hi! Typing-oriented keystrokes can't be handled by the keystroke handler. As the [documentation says](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#member-keystrokes):

>Note: Certain typing-oriented keystrokes (like Backspace or Enter) are handled by a low-level mechanism and trying to listen to them via the keystroke handler will not work reliably. To handle these specific keystrokes, see the events fired by the [editing view document](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html) (`editor.editing.view.document`).
