### ISSUE TITLE
Blocking error when inserting OS emoji

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#6520]
## 📝 Provide detailed reproduction steps (if any)

1.  Have an empty editor (like the docs [demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)).
2.  Paste the following (including space at the end):

```plaintext
I was missing this feature on multiple occasions and had to fallback to ancient WYSIWYG knowledge of "go to n-1 character and start typing from there and press delete to remove last character". 
```

1.  Insert an emoji using the OS (`ctrl+cmd+space` on mac, `win+.` on windows).

### ✔️ Expected result

The emoji is inserted and no error is thrown.

### ❌ Actual result

The emoji is inserted and **an error is thrown**.

Following that, **the editor is broken**. For example "select all -> backspace" will not work.

## 📃 Other details

*   OS: confirmed on mac and windows.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It works on `master` already. Fixed by @niegowski in ckeditor/ckeditor5-utils#327.
