### ISSUE TITLE
Move the cursor without selection？

### ISSUE THREAD

**Issue by liuyi520123** [ckeditor/ckeditor5#6527]
A document has many paragraphs. 

I want to move the cursor down or up one by one paragraph. I try some ways to  implement it.

1. I find a paragraph, `writer.createSelection`  then `writer.setSelection()` then `editor.editing.view.focus()` and scrollTo the position.
2. I find a paragraph, `writer.createPositionAt` then `writer.setSelectionFocus` then `editor.editing.view.focus()` and scrollTo the position.

I only want the cursor move to other paragraph and don't select any thing.But it failed. 

Can you give me an idea ?

**Comment by Mgsy** [comment]
Hi! You can iterate through all elements in the root, find the one from the current selection, get its index and use it to get an index of next/previous element. Finally, you can create a new range inside the next/previous element and move the selection.

I've prepared a basic implementation which could be a good starting point for your use case:

```js
editor.model.change( writer => {
    const root = editor.model.document.getRoot();

    for ( const element of root.getChildren() ) {
        const range = editor.model.document.selection.getFirstRange();
        const currentElement = range.getCommonAncestor();

        if ( element == currentElement ) {
            const currentElementIndex = root.getChildIndex( currentElement );
            const nextElementIndex = currentElementIndex + 1;

            const nextElement = root.getChild( nextElementIndex );
					
            const newPosition = writer.createPositionAt( nextElement, 'after' );
            const newRange = writer.createRange( newPosition );

            writer.setSelection( newRange );
        }
    }
} )
```

You might find the following documentation links useful:
- [Range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html)
- [Writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html)
- [Selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_selection-Selection.html)
- [Root](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_rootelement-RootElement.html)

**Comment by liuyi520123** [comment]
> Hi! You can find the index of the current element and use it to get an index of next/previous element. Finally, you can create a new range inside the next/previous element and move the selection.
> 
> I've prepared a basic implementation moving the selection to a next block, which could be a good starting point for your use case:
> 
> ```js
> editor.model.change( writer => {
>     const root = editor.model.document.getRoot();
> 
>     const range = editor.model.document.selection.getFirstRange();
>     const currentElement = range.getCommonAncestor();
> 
>     const currentElementIndex = root.getChildIndex( currentElement );
>     const nextElementIndex = currentElementIndex + 1;
> 
>     const nextElement = root.getChild( nextElementIndex );
> 
>     const newPosition = writer.createPositionAt( nextElement, 'after' );
>     const newRange = writer.createRange( newPosition );
> 
>     writer.setSelection( newRange );
> } )
> ```
> 
> You might find the following documentation links useful:
> 
> * [Range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html)
> * [Writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html)
> * [Selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_selection-Selection.html)
> * [Root](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_rootelement-RootElement.html)

Thank you very much.I use editor.model.document.selection to do this, so the editor can remember last selection when lost focus.
But I can't put the selection to view If the selection the area below the scroll bar. I find that when the table inserted, it will scroll to the position of the selection.
How is this achieved? This is cool But I can't find this part of the code.

**Comment by liuyi520123** [comment]
> Hi! You can find the index of the current element and use it to get an index of next/previous element. Finally, you can create a new range inside the next/previous element and move the selection.
> 
> I've prepared a basic implementation moving the selection to a next block, which could be a good starting point for your use case:
> 
> ```js
> editor.model.change( writer => {
>     const root = editor.model.document.getRoot();
> 
>     const range = editor.model.document.selection.getFirstRange();
>     const currentElement = range.getCommonAncestor();
> 
>     const currentElementIndex = root.getChildIndex( currentElement );
>     const nextElementIndex = currentElementIndex + 1;
> 
>     const nextElement = root.getChild( nextElementIndex );
> 
>     const newPosition = writer.createPositionAt( nextElement, 'after' );
>     const newRange = writer.createRange( newPosition );
> 
>     writer.setSelection( newRange );
> } )
> ```
> 
> You might find the following documentation links useful:
> 
> * [Range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html)
> * [Writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html)
> * [Selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_selection-Selection.html)
> * [Root](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_rootelement-RootElement.html)

Thank you.I got it.
