### ISSUE TITLE
Review most used code in terms of performance

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6528]
## 📝 Provide a description of the improvement

Doing the MergeCells command PR [review @oleq found out](https://github.com/ckeditor/ckeditor5-table/pull/290#discussion_r401459561) that undoing merge of large selection is pretty slow.

It looks like some significant time is spent in code that is not suspicious at a first glance. Some examples are ([from initial report](https://github.com/ckeditor/ckeditor5-table/pull/290#discussion_r401521283)):

1.  Element's `is()` comparison is doing `string.replace()` for `model:` prefix checking. Adding many checks up this is significant time.
2.  Position's constructor is doing `Array.concat()` that has some [performance issues](https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki). Changing it to spread operator (as a wild guess - it hasn't that performance boost in synthetic tests) also cut some time.

---

I see a potential quick win (spending additional 1-2 hour) in reviewing some repeatable code and checking if it has some potential fixes (ie those that will not change logic or API).

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Repeatable result:

1.  Testing done on "Performance: pasting data" manual test using "full websites" setting.
2.  Test: invoke "full website" -> click to focus -> CTRL-Z (undo).

Result: 466ms to 87.4ms for the line of concatenating parent path (same time reduction in undo execution).

![](https://user-images.githubusercontent.com/247363/78136913-abe86400-7424-11ea-9ca5-f82f4964959e.png)

after:

![](https://user-images.githubusercontent.com/247363/78136924-b145ae80-7424-11ea-9935-d4e3b2769a7d.png)

**Comment by jodator** [comment]
And another gain by using `for` loops instead of spread operator: from 56.6ms self time to 3.5ms self time (I had to extract those to methods to compare this part of code).

![](https://user-images.githubusercontent.com/247363/78138291-f965d080-7426-11ea-8b5a-0216eb34469a.png)

after:

![](https://user-images.githubusercontent.com/247363/78138381-18646280-7427-11ea-844a-ec72557fafe7.png)

Side note: because of the time fluctuation I'd only consider an order of magnitude change (as above) to be significant enough.

**Comment by Reinmar** [comment]
Waiting for the PRs... 🛎

**Comment by jodator** [comment]
Another finding - the `is()` method is painfully slow because:

1.  It does [string operations](https://github.com/ckeditor/ckeditor5/issues/6529) 
2.  Calls super...

Below is a result `RootElement.is()` times:

Before:

![](https://user-images.githubusercontent.com/247363/78144015-549bc100-742f-11ea-90db-ed0f49d1aea7.png)

After (removing string concatenation **and** do not call `super.is()`:

![](https://user-images.githubusercontent.com/247363/78143990-4cdc1c80-742f-11ea-8776-1126fd0b07c4.png)

![](https://user-images.githubusercontent.com/247363/78144142-844ac900-742f-11ea-97b3-551b4b566af5.png)

**Comment by jodator** [comment]
I've double checked the latter finding and this is bonkers:

Current code:

![](https://user-images.githubusercontent.com/247363/78145394-1dc6aa80-7431-11ea-900f-2506cd5c67ca.png)

After changes only in RootElment:

![](https://user-images.githubusercontent.com/247363/78145432-2ae39980-7431-11ea-8e9b-3d48352b0bad.png)

The changes:

```js
is( type, name ) {
	if ( !name ) {
		return type == 'rootElement' || type == 'element' || type == this.name || type == 'node';
	} else {
		return ( type == 'rootElement' && name == this.name ) || ( type === 'element' && name == this.name );
	}
}
```

**Comment by jodator** [comment]
I've inlined most of the `is()` checks and I've removed that `mode:` and `view:` checks. Gain `10s` in the above scenario.

Before (undo callback took 25.1s ):

![](https://user-images.githubusercontent.com/247363/78151412-dd6b2a80-7438-11ea-826f-26c2c2561efd.png)

After (undo callback took 14.89s):

![](https://user-images.githubusercontent.com/247363/78151533-fc69bc80-7438-11ea-83fb-498e3388892d.png)
