### ISSUE TITLE
Remove model / view check from `is()` checks.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6529]
## 📝 Provide a description of the improvement

This was introduced by #4479. Right now I can see this cause performance lags as `RootElement.is()` is called quite often. This method uses `string.replace` which done hundred thousend times isn't good.

Another case is that I don't see any usage of this so :man\_shrugging: why we have this. We can have another way of checking this (ie is it model position, element or whatever) - I'd suggest some flag or a helper on `model`. But I didn't research that.

## 📃 Other details

Below is a comparison of a "Performance: pasting data" test using "long (semantic)" input. Test consist invoking paste and doing undo.

Before (self times):

![](https://user-images.githubusercontent.com/247363/78142650-77c57100-742d-11ea-9e32-c9a03c896a36.png)

After  (self times):

![](https://user-images.githubusercontent.com/247363/78142663-7b58f800-742d-11ea-8476-2d871197dcb7.png)

And impact on whole code:

Before `RootElement.is()`: total time 9463 ms (includes `super.is()` calls)

![](https://user-images.githubusercontent.com/247363/78142717-94fa3f80-742d-11ea-99e7-2ecdf98cd37e.png)

After `RootElement.is()`: Total time: 3163ms (down by 3)

![](https://user-images.githubusercontent.com/247363/78142778-a8a5a600-742d-11ea-839b-1ffde84c4988.png)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
@Reinmar I've changed some code to verify the approach and the speed up is visible. Now the question is do we want to keep `model:` & `view:` checks?

Changes are here: https://github.com/ckeditor/ckeditor5-engine/compare/i/6529?expand=1. Ps it is not PR ready code so minor work is needed.

**Comment by jodator** [comment]
And the speedup comparison is here: https://github.com/ckeditor/ckeditor5/issues/6528#issuecomment-607295726.

**Comment by Reinmar** [comment]
> @Reinmar I've changed some code to verify the approach and the speed up is visible. Now the question is do we want to keep `model:` & `view:` checks?

IMO, yes. It was introduced later, that's why it's not used. But it should be. I had many cases myself when I had (for some reason) a view element passed in place of a model element or vice versa. If existing checks (especially in writers) were more precise, that would be caught ealier.

**Comment by Reinmar** [comment]
I reported #6538 and bumped #3818 higher as both would be a great improvement in our API.
