### ISSUE TITLE
Paste from Word is badly broken

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#653]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

CKEditor 5, online demo.

## 📋 Steps to reproduce

1. Copy text from Word (Mac).
2. Paste inside the editor.

## ✅ Expected result

Text is pasted.

## ❎ Actual result

Image is pasted.

Screencast:

![nov-07-2017 16-29-33](https://user-images.githubusercontent.com/630060/32501788-3ef150da-c3d9-11e7-9048-5d534bb24813.gif)

**Comment by Mgsy** [comment]
I can confirm this bug. It occurs when the image upload is enabled.

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-upload/issues/68.
