### ISSUE TITLE
How do you install a plugins？

### ISSUE THREAD

**Issue by dsfdsfdsf123** [ckeditor/ckeditor5#6531]
How do you install a plug-in and then reference it to a html like jquery，
I downloaded version is 1.8.0
but i don't know how to install plugins in it ,like code,codeBlock,alignment
![1585777151(1)](https://user-images.githubusercontent.com/27897226/78189277-518ee800-74a4-11ea-9324-620364b2f56a.jpg)
![1585777191(1)](https://user-images.githubusercontent.com/27897226/78189337-68cdd580-74a4-11ea-931f-5a7e970dc9c6.jpg)
but page is error
![1585777248(1)](https://user-images.githubusercontent.com/27897226/78189400-8ac75800-74a4-11ea-9586-f92430807873.jpg)
![1585777306(1)](https://user-images.githubusercontent.com/27897226/78189476-adf20780-74a4-11ea-88d6-7d02dc5b51a5.jpg)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. You should install plugins using NPM, import and then add them to your [editor configuration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html). Please refer to our [docs on installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and [creating custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html).
If you however don't want to do it yourself, you can use our [online builder](https://ckeditor.com/ckeditor-5/online-builder/) - there you can simply choose the plugins you need and download a ready-to-use editor build.
Hope that helps!

**Comment by dsfdsfdsf123** [comment]
3q3q3q，you are a goodman




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Filip Tokarski"<notifications@github.com&gt;; 
发送时间: 2020年4月2日(星期四) 下午3:25
收件人: "ckeditor/ckeditor5"<ckeditor5@noreply.github.com&gt;; 
抄送: "刘刚"<860721890@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ckeditor/ckeditor5] How do you install a plugins？ (#6531)





 
Hi, thanks for the report. You should install plugins using NPM, import and then add them to your editor configuration. Please refer to our docs on installing plugins and creating custom builds.
 If you however don't want to do it yourself, you can use our online builder - there you can simply choose the plugins you need and download a ready-to-use editor build.
 Hope that helps!
