### ISSUE TITLE
Deploy monorepo changes

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6534]
## Provide a description of the task

This will be a final step in our migration.

We can't just partially deploy the work to ckeditor5 repo (a lot of things will break). Instead we're verifying our work on a different, sandbox _clone_ of ckeditor5 repository and we're creating an instruction that should be followed during the deploy.

**Comment by mlewand** [comment]
### Steps

*   [ ] Merge all subpackages to the main `ckeditor5` repository ([instruction](https://github.com/ckeditor/ckeditor5/issues/6476#issuecomment-604347762))

**Comment by pomek** [comment]
Remove lint task from `package.json`, delete `.gitignore` and other files in a directory that isn't an alone repository anymore. Review `package.json` – dev/dependencies, repository URL, bugs URL etc.
I do not recommend doing it manually. A script for doing this could be helpful.

**Comment by pomek** [comment]
Before starting migration, consider merging `stable` to `master` in ckeditor-* repos.

**Comment by pomek** [comment]
In build repositories – [remove committing part from the `preversion` hook](https://github.com/ckeditor/ckeditor5-dev/issues/606#issuecomment-608353069).

**Comment by pomek** [comment]
> Merge all subpackages to the main ckeditor5 repository

Before this task and after merging `stable` => `master`, we need to merge the `i/6537` branch to `master` in all packages. Those branches contain corrected links to repositories in monorepo architecture (see: https://github.com/ckeditor/ckeditor5/issues/6537#issuecomment-607865342).

**Comment by mlewand** [comment]
All right, all the necessary steps were performed. Docs deployment and repo archive will be handled later.
