### ISSUE TITLE
To-do list is a focus trap

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6535]
## 📝 Provide detailed reproduction steps (if any)

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/todo-lists.html
2.  Focus the editor by placing the selection anywhere in its content
3.  Press the `tab` key

### ✔️ Expected result

The focus should go outside of the editor

### ❌ Actual result

Focus for a brief moment goes to the first input checkbox (you can see it because _focus ring_ blinks for a moment) and goes back to your selection position.

## 📃 Other details

This is a rather major accessibility issue.

*   Browser: Any
*   OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mmotyczynska** [comment]
How about setting `tabindex` to `-1` to prevent focusing the checkbox element with `tab` key? :thinking:

**Comment by mlewand** [comment]
Given that this tab doesn't do anything valuable now it makes perfect sense to drop it from focus list 👍
