### ISSUE TITLE
Update repository links in subpackages documentation

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6537]
There are multiple instances in each package where repository-related links are placed. These will naturally change after the migration so we need to be sure that they're correct.

Examples are:

*   Badges in the main `README.md`'s, like here: https://github.com/mlewand/ckeditor5-monorepo-test/blob/880aaabffa8a5f5affe85553b27ab01f6140530d/packages/ckeditor5-link/README.md#L5-L9
*   links in `docs/api/*.md` files, like here: https://github.com/mlewand/ckeditor5-monorepo-test/blob/880aaabffa8a5f5affe85553b27ab01f6140530d/packages/ckeditor5-link/docs/api/link.md#L23-L30

Also it make sense to run a proper search/regexp over all files, including js files - maybe there are some links that should be replaced too.

Subtask of #6479.

**Comment by mlewand** [comment]
As for the change I think it make sense just to make `i/6537` branches in each package with the changes and make one, sort-of, master pull request? This should make PR status maintenance easier.

**Comment by pomek** [comment]
Changes are done in all repositories:
- https://github.com/ckeditor/ckeditor5-core/compare/master...i/6537
- https://github.com/ckeditor/ckeditor-cloud-services-core/compare/master...i/6537

**Comment by mlewand** [comment]
Fixed in ckeditor/ckeditor5-core#220 and with merging `i/6537` branch to each other package.
