### ISSUE TITLE
Header id attribute in ckeditor 5 heading plugin

### ISSUE THREAD

**Issue by shakthifuture** [ckeditor/ckeditor5#6539]
Hi Team,

How to add id attribute in header element using CKEditor heading plugin?

✔️ Expected result

"<h1 id='5' class='h1''>Testing</h1>"

 ❌ Actual result

"<h1 class='h1''> Testing</h1>"

Thanks for your help.

**Comment by rshipp** [comment]
I'd also like to see this specific feature! It's currently possible with some [custom converters](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html#loading-content-with-a-custom-attribute) (see also my convoluted solution [here](https://github.com/bebraven/platform/blob/staging/app/javascript/ckeditor/customelementattributepreservation.js#L171)), but heading IDs seems like it would be used often enough in the kind of content design work CKE5 is meant for that it'd be a good builtin.

**Comment by shakthifuture** [comment]
In my work, compulsory I should use id attribute in heading element. There's any option available without custom converted.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In your [heading configuration options](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-heading-levels) you can add something like:
```js
{
	model: 'my_heading',
	view: {
		name: 'h2',
		attributes: {
			class: 'my_heading_class',
			id: 'my_heading_ID',
		}
	},
	title: 'My Heading',
	class: 'ck-heading_heading2',
	// It needs to be converted before the standard 'heading2'.
	converterPriority: 'high'
}
```
This example will create a custom _h2_ header element with custom _class_ and _id_.
Hope that helps!

**Comment by shakthifuture** [comment]
It worked, thank you @FilipTokarski...

**Comment by shakthifuture** [comment]
Hi @FilipTokarski ,

How to update/change the id value when I apply the header value in the text?

Thank you.

**Comment by FilipTokarski** [comment]
You can use this code:
```js
let id = 1;

editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on( 'insert:my_heading', ( evt, data, conversionApi ) => {

    const viewWriter = conversionApi.writer;

    viewWriter.setAttribute( 'id', `my_heading_id_${id}`, conversionApi.mapper.toViewElement(data.item ) )

    id += 1;
    } );
} );
```
For every time the heading is inserted, it will increment id by 1 and add to the heading as an attribute.

**Comment by shakthifuture** [comment]
Working.. thank you
