### ISSUE TITLE
CKEditor 5 classic demo not working on safari on MacOS

### ISSUE THREAD

**Issue by jmfederico** [ckeditor/ckeditor5#654]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Classic Editor Demo for version 5

## 📋 Steps to reproduce

1. Visit https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html with Safari 11.0.1
2. Editor will not load

## ✅ Expected result
Editor should be loaded

## ❎ Actual result
Editor is not loaded

**Comment by szymonkups** [comment]
@Mgsy could you check it too? It is working for me:
![image](https://user-images.githubusercontent.com/2396463/32536145-544510aa-c45d-11e7-8fd4-ad24cad1ffa4.png)

**Comment by fredck** [comment]
Yes, please let us know your Safari version. There is a [known issue with Safari 10](https://github.com/ckeditor/ckeditor5/issues/542).

**Comment by pomek** [comment]
Works for me as well:

![image](https://user-images.githubusercontent.com/2270764/32537391-bd343096-c462-11e7-926c-8a2510f9d233.png)

**Comment by Mgsy** [comment]
Hi, @jmfederico. I can't reproduce your issue, the editor loads correctly on Safari 11.0.1. Please, let us know if there is some error in the console, so we can look at it.

**Comment by jmfederico** [comment]
Well, tried again and it worked. Yesterday it just wordnd't load on Safari (but did in Chrome and Firefox). Anyway, all good now.

<img width="1168" alt="screen shot 2017-11-08 at 06 52 18" src="https://user-images.githubusercontent.com/237977/32547720-6b35bea6-c451-11e7-92c2-26435f1e1fed.png">
