### ISSUE TITLE
How to upload image without the CKFinder or EasyImage?

### ISSUE THREAD

**Issue by szpnygo** [ckeditor/ckeditor5#655]
I want to build my api without CKFinder

What's the format of the api result?

**Comment by szymonkups** [comment]
Hey @szpnygo.
To achieve that you'll need to implement your own adapter. See docs [here](https://docs.ckeditor.com/ckeditor5/latest/api/module_upload_filerepository-Adapter.html), especially `upload()` method description.

Hope this helps, also I encourage you to ask your future questions on StackOverflow under [ckeditor5 tag](https://stackoverflow.com/questions/tagged/ckeditor5).
