### ISSUE TITLE
Issue there is no documentation how to configure mathtype mathml format to latex format

### ISSUE THREAD

**Issue by gitalexhope** [ckeditor/ckeditor5#6552]
## 📝 Please provide the document for change MathType plugin configuration

Hello team

I'm unable to find document how to change the configuration for MathType plugin MathML to Latex.

**Comment by Mgsy** [comment]
Hi, thanks for the report. Please, read about [LaTeX support](https://docs.wiris.com/en/mathtype/mathtype_web/latex-support) in MathType plugin.

Also, note that MathType is not developed by CKEditor team, but Wiris, so all questions and feature request should be reported in [this repository](https://github.com/wiris/html-integrations/issues).
