### ISSUE TITLE
Binds events to the inserted element, such as a click

### ISSUE THREAD

**Issue by oldpubcat** [ckeditor/ckeditor5#6555]
First of all, thank you for the open source.

I have a requirement that I don't know how to implement

I want to bind events to the inserted element, such as inserting a block and then clicking on the element to pop up an form field.

I haven't seen an example of this.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If I understood you correctly, in this case you can use [clickObserver](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_observer_clickobserver-ClickObserver.html) to check if the desired element was clicked, and then fire some event. Very basic implementation will look like this:
```js
editor.editing.view.listenTo( editor.editing.view.document, 'click', ( evt, data ) => {
    const element = editor.editing.mapper.toModelElement( data.target );
    const name = element.name;

    if ( name === 'paragraph' ) {
        console.log( 'You clicked on pargraph' )
        // do something...
    }
} );
```
This code will [map view element](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_mapper-Mapper.html), which has been clicked, to model element. Then based on, for example, the element's name you can fire some action. This snippet will not work for [AttributeElements](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_attributeelement-AttributeElement.html) - for this you would need some extra logic to check if text has attributes. So, you can start with this code and further adjust it to you particular needs.
Hope that helps!

**Comment by oldpubcat** [comment]
thanks.
