### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Anbarasan-321** [ckeditor/ckeditor5#6556]
![image](https://user-images.githubusercontent.com/30228735/78471281-c3d62580-774d-11ea-99a4-b43ffa1b5ac6.png)
Getting error message  "Uncaught SyntaxError: Cannot use import statement outside a module"  while integrating the code block on HTML website. Kindly check and let me know how to fix this?

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Could you please provide a step by step path to reproduce this issue and your editor configuration?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
