### ISSUE TITLE
Preserving element attribute does not work (code from documentation)

### ISSUE THREAD

**Issue by kfirba** [ckeditor/ckeditor5#6560]
## 📝 Provide detailed reproduction steps (if any)

1. Create an editor instance and add the following configuration option: `extraPlugins: [AllowLinkClass]`. The plugin code:

```js
function allowLinkClass(editor) {
  editor.model.schema.extend('$text', {allowAttributes: 'linkClass'});

  editor.conversion.for('downcast').attributeToElement({
    model: 'linkClass',
    view: (attributeValue, writer) => {
      const linkElement = writer.createAttributeElement('a', {class: attributeValue}, {priority: 5});
      writer.setCustomProperty('link', true, linkelement);

      return linkElement;
    },
    converterPriority: 'low',
  });

  editor.conversion.for('upcast').attributeToAttribute({
    view: {
      name: 'a',
      key: 'class',
    },
    model: 'linkClass',
    converterPriority: 'low',
  });
}
```

2. Instantiate the editor where the editor's content has the following `a`:

```html
<div id="editor">
  <a class="articles_hotels_search_box" href="https://example.com" target="_blank">Gerloczy Rooms de Lux</a>
</div>
```
3. View the rendered model element in CKEditor Inspector and confirm it is missing the `linkClass` attribute.

### ✔️ Expected result

```html
<paragraph>
 "[linkHref][linkClass] Gerloczy Rooms de Lux"
</paragraph>
```
where `linkClass` contains the class `articles_hotels_search_box`

### ❌ Actual result

```html
<paragraph>
 "[linkHref] Gerloczy Rooms de Lux"
</paragraph>
```

## 📃 Other details

* Browser: Chrome@latest
* OS: Centos7
* CKEditor version: 18
* Installed CKEditor plugins: alignment, autoformat, basic-styles, block-quote, core, dev-utils, editor-balloon, essentials, font, heading, horizontal-line, image, indent, inspector, link, list, media-embed, paragraph, paste-from-office, remove-format, table, theme-lark, ui, widget

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! I can see a typo in your variable name - in `writer.setCustomProperty('link', true, linkelement);` you reference to `linkelement` instead of `linkElement`. 

However, after fixing it, your code works as expected:

![Screenshot 2020-04-06 at 14 24 20](https://user-images.githubusercontent.com/20988892/78558269-969f7b00-7812-11ea-9b3a-58ab9ee4e3dc.png)

Are you sure that you've loaded the plugin properly and rebuilt the editor?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
