### ISSUE TITLE
Application is not working in share point webpart

### ISSUE THREAD

**Issue by ankurihg** [ckeditor/ckeditor5#6564]
## 📝 Error in share point web part when using with react v15

1. make an sharepoint webpart
2. launch it using gulp serve
3. web part is not launching and gives the following error.

### ✔️ Expected result

Webpart should launch.

### ❌ Actual result

Following error on debug console of browser.

react-dom-15-bundle_51ab2d4f79c129b30d46e17f916e1cc1.js:1 Uncaught (in promise) Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60HubLinks%60.

## 📃 Other details

* Browser: Chrome
* OS:Windows
* CKEditor version: 5
* Installed CKEditor plugins: N/A

---

**package.json**

`{
  "name": "ihg-content-card",
  "version": "1.1.2",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^18.0.0",
    "@ckeditor/ckeditor5-react": "^2.1.0",
    "@microsoft/sp-core-library": "1.6.0",
    "@microsoft/sp-loader": "^1.10.0",
    "@microsoft/sp-lodash-subset": "1.6.0",
    "@microsoft/sp-office-ui-fabric-core": "1.6.0",
    "@microsoft/sp-webpart-base": "1.6.0",
    "@pnp/spfx-controls-react": "1.17.0",
    "@types/camljs": "0.0.30",
    "@types/js-beautify": "0.0.31",
    "@types/prop-types": "^15.7.3",
    "@types/react": "15.6.6",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "camljs": "^2.8.2",
    "deep-diff": "^1.0.1",
    "handlebars": "^4.0.10",
    "js-beautify": "^1.6.14",
    "linqts": "^1.11.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-html-parser": "^2.0.2",
    "sp-client-custom-fields": "^1.3.7",
    "sp-pnp-js": "^3.0.6"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.2": "^0.6.5",
    "@microsoft/sp-build-web": "^1.10.0",
    "@microsoft/sp-module-interfaces": "1.6.0",
    "@microsoft/sp-webpart-workbench": "^1.10.0",
    "@types/chai": ">=3.4.34 <4.2.0",
    "@types/chrome": "0.0.69",
    "@types/mocha": ">=2.2.33 <=5.2.2",
    "@typescript-eslint/eslint-plugin": "^2.24.0",
    "@typescript-eslint/parser": "^2.24.0",
    "ajv": "~6.5.2",
    "eslint": "^6.8.0",
    "file-saver": "^1.3.3",
    "gulp": "^3.9.1",
    "moment": "^2.18.1",
    "tslint-microsoft-contrib": "5.0.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  }
}
`
**tsx file**
`public render(): React.ReactElement<MyProps> {
    return(
      <CKEditor
          editor={ ClassicEditor }
          data="<p>Hello from CKEditor 5!</p>"
          onInit={ editor => {
              // You can store the "editor" and use when it is needed.
              console.log( 'Editor is ready to use!', editor );
          } }
          onChange={ ( event, editor ) => {
              const data = editor.getData();
              console.log( { event, editor, data } );
          } }
          onBlur={ ( event, editor ) => {
              console.log( 'Blur.', editor );
          } }
          onFocus={ ( event, editor ) => {
              console.log( 'Focus.', editor );
          } }
      />
    );
  }`

**Comment by Mgsy** [comment]
Hi, thanks for the report. Unfortunately, we didn't test CKEditor 5 in SharePoint, so we won't be able to help you. I'm afraid you have to debug it on your own. 

However, you can open a feature request for SharePoint integration. If it will be highly requested by the community, we'll definitely take a look at it.
