### ISSUE TITLE
i need help，how can i insert some html with style such div into editor

### ISSUE THREAD

**Issue by huanghaoming** [ckeditor/ckeditor5#6576]
<div class="jumbotron">
                    <h1>uploading</h1>
                    <hr>
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                             aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                    </div>
                </div>

i want to custom a view ..but when i use javascript to append to editor,is no work。。。how can i do

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not sure I understand what you mean. Could you describe in more detail what you want to achieve? What kind of custom _styling_ and _view_ you have in mind?

**Comment by huanghaoming** [comment]
`<div class="jumbotron">
                    <h1>custom title</h1>
                    <hr>
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                             aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                    </div>
                </div>`

This is my html content,   I want to insert it into editor,but  no work...

**Comment by FilipTokarski** [comment]
It's not possible to preserve all content inserted into editor from outside. Editor preserves only elements registered in [schema](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html). It is done by [converting](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) elements between [view and model](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html).
We have [feature request ticket](https://github.com/ckeditor/ckeditor5/issues/6462) for supporting custom divs with classes, so if you want to add anything, fell free to write there.

**Comment by huanghaoming** [comment]
do you give some demo for use "registered in schema"

**Comment by FilipTokarski** [comment]
You can find explanation in [schema guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html).

**Comment by huanghaoming** [comment]
i do not mean inserted into editor from outside.....I want to insert html by javascript

**Comment by huanghaoming** [comment]
sorry.....i need some more detail code。。。。can you provide？

**Comment by FilipTokarski** [comment]
To register a `div` element in [schema](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html) and add [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) you can use this code:
```js
editor.model.schema.register( 'div', {
    inheritAllFrom: '$block'
} );
editor.conversion.elementToElement( {
    model: 'div',
    view: 'div'
} );
```
You can refer to docs and further adjust it to your particular needs. [Here you can read more about conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html).

**Comment by huanghaoming** [comment]
oh, i find out can not modify editor html dom by jquery，how can i do for it

**Comment by FilipTokarski** [comment]
Sorry, but I'm afraid I don't understand what is the case here. I won't be able to help you, until you provide a detailed, step by step description of what you want to achieve and what problems you want to solve.

**Comment by huanghaoming** [comment]
First of all，this is an editor；

![图片1](https://user-images.githubusercontent.com/11265013/78882880-4ed75880-7a8b-11ea-8e33-72bfb7ba1c06.png)
When i upload a image，
![image](https://user-images.githubusercontent.com/11265013/78882938-66164600-7a8b-11ea-9862-222f5bfdb228.png)

However，image upload is slow by network，so i want to give a mask div，like this：

![image](https://user-images.githubusercontent.com/11265013/78882967-73333500-7a8b-11ea-91d8-ec31c9265145.png)


But when i append html to it（use jquery），is no work
