### ISSUE TITLE
I want to set the default word

### ISSUE THREAD

**Issue by oldpubcat** [ckeditor/ckeditor5#6577]
for example：https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#demo

your code
```
writer.appendElement('paragraph', simpleBoxDescription);
```
HTML results
```
  <div class="simple-box-description"><p><br data-cke-filler="true"></p></div>
```

my code
```
writer.appendText('default word',  simpleBoxDescription);
// or
writer.appendElement('paragraph', {text: 'default word'}, simpleBoxDescription);
```
I want the result， He is able to edit or press enter
```
  <div class="simple-box-description"><p>default word</p></div>
```
Or another way to implement my idea.

**Comment by Mgsy** [comment]
Hi, if you want to insert a default text, I'd suggest creating a new paragraph element, appending a text inside and inserting this paragraph to the simple box description. See the code below:

```js
const paragraph = writer.createElement( 'paragraph' );
writer.appendText( 'default word', paragraph );
	
writer.insert( paragraph, simpleBoxDescription, 0 );
```

**Comment by oldpubcat** [comment]
This is an amazing.   Thank you very very very much!!!!!
