### ISSUE TITLE
Mention not being built via online builder or custom build

### ISSUE THREAD

**Issue by kelso6969** [ckeditor/ckeditor5#6578]
## 📝 Provide detailed reproduction steps (if any)

1. Use Online Builder, allow mentions, build and test
2. I also used the custom build, git, npm, yarn,  

### ✔️ Expected result

Plugin to load

### ❌ Actual result

jquery.min.js:2 jQuery.Deferred exception: Mention is not defined ReferenceError: Mention is not defined
    at HTMLDocument.<anonymous> (http://172.27.218.59/khamlin/ops_issue_detail.php?id=140:824:16)
    at HTMLDocument.dispatch (http://172.27.218.59/khamlin/assets/vendor/jquery/jquery.min.js:2:42571)
    at HTMLDocument.v.handle (http://172.27.218.59/khamlin/assets/vendor/jquery/jquery.min.js:2:40572)
    at Object.trigger (http://172.27.218.59/khamlin/assets/vendor/jquery/jquery.min.js:2:70627)
    at s.fn.init.triggerHandler (http://172.27.218.59/khamlin/assets/vendor/jquery/jquery.min.js:2:71306)
    at HTMLDocument.<anonymous> (http://172.27.218.59/khamlin/assets/vendor/jquery-migrate/jquery-migrate.min.js:2:6808)
    at e (http://172.27.218.59/khamlin/assets/vendor/jquery/jquery.min.js:2:29453)
    at t (http://172.27.218.59/khamlin/assets/vendor/jquery/jquery.min.js:2:29755) undefined
k.Deferred.exceptionHook @ jquery.min.js:2

**jquery.min.js:2 Uncaught ReferenceError: Mention is not defined**
    at HTMLDocument.<anonymous> (ops_issue_detail.php?id=140:824)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.v.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at s.fn.init.triggerHandler (jquery.min.js:2)
    at HTMLDocument.<anonymous> (jquery-migrate.min.js:2)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version 5
* Installed CKEditor plugins: Tried just the basic editor package and adding mention, as well as online builder
---
`ClassicEditor
			.create( document.querySelector( '#issue_updates' ), {
	
				toolbar: {
					items: [
						'heading',
						'|',
						'fontColor',
						'fontBackgroundColor',
						'fontSize',
						'bold',
						'italic',
						'link',
						'bulletedList',
						'numberedList',
						'|',
						'horizontalLine',
						'indent',
						'outdent',
						'|',
						'blockQuote',
						'insertTable',
						'undo',
						'redo',
						'codeBlock',
						'code'
					]
				},
				language: 'en',
				table: {
					contentToolbar: [
						'tableColumn',
						'tableRow',
						'mergeTableCells'
					]
				},
				licenseKey: '',
                mention: {
                    feeds: [
                        {
                            marker: '@',
                            feed: [ '@Barney', '@Lily', '@Marshall', '@Robin', '@Ted' ],
                            minimumCharacters: 1
                        }
                    ]
                }

			} )
			.then( editor => {
				window.editor = editor;
		
				
				
				
			} )
			.catch( error => {
				console.error( 'Oops, something gone wrong!' );
				console.error( 'Please, report the following error in the https://github.com/ckeditor/ckeditor5 with the build id and the error stack trace:' );
				console.warn( 'Build id: 9z97qr36z00-7wbqrubadt3l' );
				console.error( error );
			} );`
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, could you share more details about your issue? I've just downloaded a build with the mention plugin via our online builder, it works fine and the plugin is included to the build:

```js
/**
 * @license Copyright (c) 2014-2020, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat.js';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote.js';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold.js';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder.js';
import CKFinderUploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter.js';
import Heading from '@ckeditor/ckeditor5-heading/src/heading.js';
import Image from '@ckeditor/ckeditor5-image/src/image.js';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption.js';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle.js';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar.js';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload.js';
import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic.js';
import Link from '@ckeditor/ckeditor5-link/src/link.js';
import List from '@ckeditor/ckeditor5-list/src/list.js';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed.js';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table.js';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar.js';
import Mention from '@ckeditor/ckeditor5-mention/src/mention.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';

export default class Editor extends ClassicEditor {}

// Plugins to include in the build.
Editor.builtinPlugins = [
	Autoformat,
	BlockQuote,
	Bold,
	CKFinder,
	CKFinderUploadAdapter,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	Italic,
	Link,
	List,
	MediaEmbed,
	PasteFromOffice,
	Table,
	TableToolbar,
	Mention,
	Essentials,
	Paragraph
];
```

**Comment by kelso6969** [comment]
I can confirm that those are in the src/ckeditor.js file as well, but when I load the plugin, I get this.

jquery.min.js:2 Uncaught ReferenceError: Mention is not defined

my <script> for init is below
ClassicEditor
			.create( document.querySelector( '#issue_updates' ), {
				plugins: [ Mention ],
				toolbar: {
					items: [
						'heading',
						'|',
						'fontColor',
						'fontBackgroundColor',
						'fontSize',
						'bold',
						'italic',
						'link',
						'bulletedList',
						'numberedList',
						'|',
						'horizontalLine',
						'indent',
						'outdent',
						'|',
						'blockQuote',
						'insertTable',
						'undo',
						'redo',
						'codeBlock',
						'code'
					]
				},
				language: 'en',
				table: {
					contentToolbar: [
						'tableColumn',
						'tableRow',
						'mergeTableCells'
					]
				},
				licenseKey: '',
                mention: {
                    feeds: [
                        {
                            marker: '@',
                            feed: [ '@Barney', '@Lily', '@Marshall', '@Robin', '@Ted' ],
                            minimumCharacters: 1
                        }
                    ]
                }

			} )
			.then( editor => {
				window.editor = editor;
		
				
				
				
			} )
			.catch( error => {
				console.error( 'Oops, something gone wrong!' );
				console.error( 'Please, report the following error in the https://github.com/ckeditor/ckeditor5 with the build id and the error stack trace:' );
				console.warn( 'Build id: 9z97qr36z00-7wbqrubadt3l' );
				console.error( error );
			} );

**Comment by kelso6969** [comment]
Tested using the sample index.html as well

After adding support for Mention
				plugins: [ Mention ],

I reload it and get this

index.html:107 Uncaught ReferenceError: Mention is not defined
    at file:///C:/Users/P2781093/Downloads/ckeditor5%20(1)/sample/index.html:107:16

**Comment by Mgsy** [comment]
Why do you add `Mention` plugin inside your `editor#create` method? It's already loaded in the build configuration in `ckeditor.js`, there's no need to load it again. 

Just remove `plugins: [ Mention ]` and it should work fine.

**Comment by kelso6969** [comment]
I did read it wasn't necessary and had tried without using that line, but @mentions still wouldn't come up, no other errors in console.

**Comment by BillyNZL** [comment]
Hi,

Similar problem. I have tried to follow the simplest steps. Please help, I have been trying for many many hours to get this going :)

Result: Editor Loads but mentions does **not** trigger on @ or any character. There are no console errors.

1. Configured Build with mentions at https://ckeditor.com/ckeditor-5/online-builder/

2.  Edited the index.html with the following script to initialize ckeditor and mentions
`ClassicEditor
    .create(document.querySelector('.editor'), {
        toolbar: {
            items: [
                'heading',
                '|',
                'fontColor',
                'fontBackgroundColor',
                'fontSize',
                'bold',
                'italic',
                'link',
                'bulletedList',
                'numberedList',
                '|',
                'horizontalLine',
                'indent',
                'outdent',
                '|',
                'blockQuote',
                'insertTable',
                'undo',
                'redo',
                'codeBlock',
                'code'
            ]
        },
        language: 'en',
        table: {
            contentToolbar: [
                'tableColumn',
                'tableRow',
                'mergeTableCells'
            ]
        },
        licenseKey: '',
        mention: {
            feeds: [{
                marker: '@',
                feed: ['@Barney', '@lily', '@marshall', '@robin', '@ted'],
                minimumCharacters: 1
            }]
        }
    })
    .then(editor => {
        window.editor = editor;
    })
    .catch(error => {
        console.error('Oops, something gone wrong!');
        console.error('Please, report the following error in the https://github.com/ckeditor/ckeditor5 with the build id and the error stack trace:');
        console.warn('Build id: 9z97qr36z00-7wbqrubadt3l');
        console.error(error);
    });`

**Comment by BillyNZL** [comment]
Update. I have found that a double @@ is required to trigger the auto complete. CAn you provide guidance on why or how to configure for a single @ ?

Cheers

**Comment by Ruman-Al** [comment]
Hello,
I have also similar problem like above both.
I removed **plugins: [ Mention ]** from editor-create method.
and used both single @ and double @@.
and add the plugin to build you can seee in image in line 27.
![image](https://user-images.githubusercontent.com/131847160/234786750-0f20a4f9-53dc-42a9-b466-bd9cd87fe136.png)
![image](https://user-images.githubusercontent.com/131847160/234786972-9b103562-9105-4fce-8e2f-b970819d5bac.png)

don't know why it doesn't work for me ?

**Comment by Ruman-Al** [comment]
@Mgsy please have a look into my problem

**Comment by Ruman-Al** [comment]
you can see my script as well
![image](https://user-images.githubusercontent.com/131847160/234787519-5948bacc-3e2f-4d3b-82f9-3242ef72ad7e.png)
