### ISSUE TITLE
Update the CKEditor5 build-in plugin attribute

### ISSUE THREAD

**Issue by shakthifuture** [ckeditor/ckeditor5#6583]
Hi,

Using the below code I have created id attribute in the header plugin

```
{
	model: 'my_heading',
	view: {
		name: 'h2',
		attributes: {
			class: 'my_heading_class',
			id: 'my_heading_ID',
		}
	},
	title: 'My Heading',
	class: 'ck-heading_heading2',
	// It needs to be converted before the standard 'heading2'.
	converterPriority: 'high'
}
```
Here the problem, how to update the id value dynamically when i apply the header into text?

**Comment by FilipTokarski** [comment]
Hi, I answered your question in [the original ticket here](https://github.com/ckeditor/ckeditor5/issues/6539#issuecomment-611356214).
