### ISSUE TITLE
Cannot extend an item which was not registered yet

### ISSUE THREAD

**Issue by torontochen** [ckeditor/ckeditor5#6584]
Hi there,
I am working on a  Vue project  to upload image by base64 ,so I import Base64UploadAdapter ,here are codes,

**// main.js**
import CKEditor from '@ckeditor/ckeditor5-vue'
Vue.use(CKEditor)

**//component**
`<template>
 <div style="height: 280px;">
                  
                    <ckeditor
                      :editor="editor"
                      v-model="vueEditor"
                      :config="editorConfig"
                    ></ckeditor>
    </div>
</template>`

`<script>
   import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
   import Base64UploadAdapter from "@ckeditor/ckeditor5- 
   upload/src/adapters/base64uploadadapter";
  import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
  import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
  import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
  import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
 import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";
 import Image from "@ckeditor/ckeditor5-image/src/image";
 import ImageToolbar from "@ckeditor/ckeditor5-image/src/imagetoolbar";
 import ImageCaption from "@ckeditor/ckeditor5-image/src/imagecaption";
 import ImageStyle from "@ckeditor/ckeditor5-image/src/imagestyle";
 import ImageResize from "@ckeditor/ckeditor5-image/src/imageresize";
 import ImageUpload from "@ckeditor/ckeditor5-image/src/imageupload";
 import Font from "@ckeditor/ckeditor5-font/src/font";

export default {
   data() {
    return {
        vueEditor: null
        editor: ClassicEditor,
      editorConfig: {
          plugins: [
          EssentialsPlugin,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin,
          ImageUpload,
          Font,
          Image,
          ImageToolbar,
          ImageCaption,
          ImageStyle,
          ImageResize,
          Base64UploadAdapter
        ],
        toolbar: {
          items: [
            "bold",
            "italic",
            "link",
            "undo",
            "redo",
            "imageUpload",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "imageTextAlternative",
            "|",
            "imageStyle:full",
            "imageStyle:side"
          ]
        }
      },
      }
  }
}
</script>`

**//package.json**
    "@ckeditor/ckeditor5-basic-styles": "^18.0.0",
    "@ckeditor/ckeditor5-build-classic": "^18.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.9",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.9",
    "@ckeditor/ckeditor5-editor-classic": "^18.0.0",
    "@ckeditor/ckeditor5-essentials": "^18.0.0",
    "@ckeditor/ckeditor5-link": "^18.0.0",
    "@ckeditor/ckeditor5-paragraph": "^18.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^18.0.0",
    "@ckeditor/ckeditor5-upload": "^18.0.0",
    "@ckeditor/ckeditor5-heading": "^18.0.0",
    "@ckeditor/ckeditor5-image": "^18.0.0",
    "@ckeditor/ckeditor5-indent": "^18.0.0",
    "@ckeditor/ckeditor5-list": "^18.0.0",
    "@ckeditor/ckeditor5-font": "^18.0.0",
    "@ckeditor/ckeditor5-media-embed": "^18.0.0",
    "@ckeditor/ckeditor5-vue": "^1.0.1",

### **problems** :

1. the image upload icon doesn't show on toolbar, either do the other icons

2.I got error on browser
**_ckeditor.js?3730:5 CKEditorError: schema-cannot-extend-missing-item: Cannot extend an item which was not registered yet. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-schema-cannot-extend-missing-item
 {"itemName":"image"}
    at Schema.extend (webpack-internal:///./node_modules/@ckeditor/ckeditor5-engine/src/model/schema.js:241:15)
    at ImageUploadEditing.init (webpack-internal:///./node_modules/@ckeditor/ckeditor5-image/src/imageupload/imageuploadediting.js:135:24)_**

I tried many times, just isn't work,please help me out

**Comment by jodator** [comment]
I can see that:

```plaintext
ImageUpload,
Font,
Image,
ImageToolbar,
ImageCaption,
ImageStyle,
ImageResize,
```

could be out of order (it shouldn't matter but I don't recall we have tests for this).

Could you try:

```plaintext
Font,
Image,
ImageToolbar,
ImageCaption,
ImageStyle,
ImageResize,
ImageUpload,
```

**Comment by torontochen** [comment]
you are right ,Image must be before all the other image plugins in order,thank you
