### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by Yomi337** [ckeditor/ckeditor5#659]
Hello! I am using CKEditor 5 for my project, but i cant complete it because alpha version dont have a couple of very important components like colorpicker and custom css selectpicker (kind of headings plugin but apllying custom styles from my own CSS). So I am wondering how soon developers team can finish this 2 important plugins? I need to know that stuff because i cant calculate average time for completeing my project without this info.

Also I found strange behaviour with including plugins when using CDN source. If you include all available (at the moment) plugins, you still missing "Undo", but if u delete "plugins" string in config you can use undo and redo functions.

I look forward for answer, it will really help me. Thanks!

**Comment by Reinmar** [comment]
Hey! Thanks for the feedback :)



> custom css selectpicker (kind of headings plugin but apllying custom styles from my own CSS

We're discussing about this feature in https://github.com/ckeditor/ckeditor5/issues/648. You can give 👍 which will help us priorities this feature. Also, it'd be really helpful if you described the use cases that you have for such a feature.

> colorpicker

What do you mean by colorpicker? The font color feature? It's currently in the making. You can see first designs in https://github.com/ckeditor/ckeditor5-highlight/issues/3.

> So I am wondering how soon developers team can finish this 2 important plugins?

We can't guarantee any dates. The features are ready when they are ready. But the highlight feature is already in our pipeline.



> Also I found strange behaviour with including plugins when using CDN source. If you include all available (at the moment) plugins, you still missing "Undo", but if u delete "plugins" string in config you can use undo and redo functions.

I don't understand what you did and what happened. Could you create a sample? E.g. on https://jsfiddle.net?

**Comment by Yomi337** [comment]
> What do you mean by colorpicker? The font color feature? It's currently in the making. You can see first designs in ckeditor/ckeditor5-highlight#3.
I mean not just some presets (like 8-10 basic color) but full range of colors with possibility to insert hex, rgba etc.

> I don't understand what you did and what happened. Could you create a sample? E.g. on https://jsfiddle.net?
Unfortunately i can't do it on jsfiddle, coz it will be not obvious to see what is happening. I ll try to explain... When you init ckeditor you can go without any config (use defaults), if you do so, you get full stack of available features, but if you try to use any custom config you loose "undo" and "redo", you just don't have such possibility to write it in config, so i can't create custom config without loosing these features. Hope it will help.

**Comment by Reinmar** [comment]
> I mean not just some presets (like 8-10 basic colors) but full range of colors with possibility to insert hex, rgba etc.

There's a ticket now regarding this feature: https://github.com/ckeditor/ckeditor5/issues/1457

> but if you try to use any custom config you loose "undo" and "redo", you just don't have such possibility to write it in config, so i can't create custom config without loosing these features

There's `config.extraPlugins` now: https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-extraPlugins
