### ISSUE TITLE
How to traverse the document using ckeditor view?

### ISSUE THREAD

**Issue by Shankar26G** [ckeditor/ckeditor5#6591]
const range = this.editor.model.createRangeIn(this.editor.model.document.getRoot());
    for (const value of range.getWalker()) {
}

The above code we are traversing through model elements.
Is there any API to traverse through the view elements?

**Comment by Reinmar** [comment]
It's the exact same code but on the view :)

```plaintext
const range = this.editor.editing.view.createRangeIn(this.editor.editing.view.document.getRoot());
for (const value of range.getWalker()) {
	console.log( value );
}
```
