### ISSUE TITLE
UI customization of media embed dropdown panel

### ISSUE THREAD

**Issue by parinda96** [ckeditor/ckeditor5#6595]
Current media embed dropdown panel contains one textbox for URL and two buttons(icons) for save and cancel
There should be a way to change these buttons, styling of the textbox and the dropdown panel.

I am using a custom build of CKEditor5.

* CKEditor version: 5
* Plugin: MediaEmbed

**Comment by Mgsy** [comment]
Hi, please provide some meaningful description of your issue. Without knowing the case, we won't be able to answer.

**Comment by Mgsy** [comment]
Thanks for editing the original post. 

Basically, it's possible to customize the appearance of the media embed UI via CSS. Just get the proper selectors and create your own styling rules.

**Comment by parinda96** [comment]
Not just CSS.

How can I replace the icon buttons with text buttons?

**Comment by Reinmar** [comment]
You need to modify the source code of this feature. You can fork the repo and change https://github.com/ckeditor/ckeditor5-media-embed/blob/master/src/ui/mediaformview.js and use your patched version of this package.
