### ISSUE TITLE
Downcast Dispatcher fires multiple times

### ISSUE THREAD

**Issue by shakthifuture** [ckeditor/ckeditor5#6596]
```
downcastDispatcher.on('insert:heading', (evt: any, data: any, conversionApi: any) => {
      if ( conversionApi.consumable.consume( data.item, evt.name ) ) {
            return;
      }
      const viewWriter = conversionApi.writer;
      viewWriter.setAttribute('id', uuid, conversionApi.mapper.toViewElement(data.item));
      evt.stop();
});
```
the above code fires multiple times(minimum 3 times) for every insert, so my id value changing frequently. But it should fire only once when I apply the heading tag. Even I refresh the page, it gets fired. How to restrict that?

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. That's strange, because the same code works fine for me. If you are using some framework, please make sure that this code is not invoked multiple times by, for example, some other component.

**Comment by shakthifuture** [comment]
Hi,
Thank for your response, I didn't use any extra framework. please add just "console.log" inside in dispatcher you can able to notice the multiple times execution.

**Comment by FilipTokarski** [comment]
I already did and it executed only once every time I used it, that's why I said it works fine for me. There must be something different in your implementation. Maybe you could provide more information about this code/how it is used in your app in broader context?
