### ISSUE TITLE
When editing the LINK head or tail, there is an exception in Chinese input

### ISSUE THREAD

**Issue by cai123nb** [ckeditor/ckeditor5#6597]
## 📝 Provide detailed reproduction steps (if any)

1. go to https://ckeditor.com/ckeditor-5/demo/#balloon
2. scroll to LINK section
3. edit link tail in Chinese

### ✔️ Expected result

It should generate Chinese word instead of English alphabets. Just like edit in the middle(It's quite right).

### ❌ Actual result

It record many useless English alphabets.(It should work like edit in the Link middle).

## 📃 Other details

I record some gif files to demonstrate this bug, hope it can help.

edit in middle(right):

![Jietu20200411-155738-HD](https://user-images.githubusercontent.com/26185374/79038627-5e7eaa80-7c0d-11ea-8ee4-7fa3de0c874b.gif)

edit in tail(wrong):

![Jietu20200411-155527-HD](https://user-images.githubusercontent.com/26185374/79038640-76562e80-7c0d-11ea-854e-38ce884f035f.gif)

* Browser: Chrome
* OS: Mac OS
* CKEditor version: See demo.
* Installed CKEditor plugins: See dmo.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. We're aware that composition breaks in many cases. This one is also known - you can read more about it here - https://github.com/ckeditor/ckeditor5/issues/3118.
