### ISSUE TITLE
Drag & drop widgets

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#6598]
This feature would allow user to drag existing widget (image, table, custom block widget) from one place in a document to another.

Table widget has already a handle which intuitively looks like a good control for that:

![image](https://user-images.githubusercontent.com/617641/79043997-fdea7000-7c02-11ea-8c69-481e8b3c89e6.png)

Currently the workaround is to CTRL-X it from one place and then CTRL-V it to another one.

I found references/requests for this in comments - https://github.com/ckeditor/ckeditor5/issues/2060#issuecomment-574958799 https://github.com/ckeditor/ckeditor5/issues/5481#issuecomment-406961043 but have not found a separate issue.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. Drag and drop feature isn't supported in CKEditor 5, however, your case is in the scope of the main D&D issue - https://github.com/ckeditor/ckeditor5/issues/2664. Please, see it to learn more.
