### ISSUE TITLE
Dynamic add and remove plugins on one editor

### ISSUE THREAD

**Issue by liuyi520123** [ckeditor/ckeditor5#6599]
I try to develop a function that can dynamically add or move the tools on the toolbar.  Because of different document types, some don't need to upload pictures, some don't need to be bold, and some don't need font size. Therefore, sometimes I need to delete some toolbar icons, and sometimes you need to add some icons on the same editor.

I try to destroy the editor, empty the element contents, and then create it again, but two times later an error will be reported.

Is there any idea or API that can help me, thank you?

```
// create one editor
 DecoupledEditor
		.create(...)
                .then( editor => {...})
// destory editor
editor.destory();
// clear div conent
div.innerHTML = ''
// create editor again
 DecoupledEditor
		.create(...)
                .then( editor => {...})
```

![image](https://user-images.githubusercontent.com/24844047/79100630-869b1480-7d99-11ea-9c3d-760189e87141.png)

![image](https://user-images.githubusercontent.com/24844047/79100691-a0d4f280-7d99-11ea-8ed8-06afd4a72096.png)

**Comment by Reinmar** [comment]
Hi! Could you create a sample on which this issue is reproducible? This will make it easier for us to analyze it.

**Comment by Reinmar** [comment]
Just to clarify – I asked about that because you should be able to destroy one editor and initialize another one. We do that thousand of times in the tests.

**Comment by netstreet** [comment]
i have same issue to destroy(), below example my test code.
![Shot_20200414_141937](https://user-images.githubusercontent.com/32259223/79219545-28366a80-7e5b-11ea-86ac-c26ebd1cf19d.png)

element i try to destroy when i close collapse i got same error @liuyi520123 got too. i try to destroy element same way editor.destroy();

**Comment by liuyi520123** [comment]
@Reinmar I deploy a website, the address is http://issuse.icecode.cc/, click button 'Create New' on the page, will see the error.
The source can see in Developer Tools，and I took a screenshot too.
Because DecoupledEditor?

![image](https://user-images.githubusercontent.com/24844047/79291110-5f128c00-7f00-11ea-93de-02cda7b1496e.png)

**Comment by mzrybbd** [comment]
How is this problem solved now
