### ISSUE TITLE
[Docs] Document how to send data from CKEditor to the server

### ISSUE THREAD

**Issue by xssec** [ckeditor/ckeditor5#660]
HI,

Is there any sample how to integrate CKE5 to store data into mysql with PDO and retrieve it?

**Comment by Reinmar** [comment]
Hi!

Thanks for the suggestion. However, storing data is something so backend-specific that we don't think that it makes sense to document it. There are hundreds of frameworks and thousands of methods.

What we could have is some documentation how to make CKEditor send data to the server (without mentioning how the server should handle that data). I believe there are no such docs now.

**Comment by Reinmar** [comment]
To give a quick answer to those who will be looking for it:

1. The classic editor can be initialized on a `<textarea>` just like CKEditor 4 can be and if this this textarea is used in a form, then CKEditor's data will be sent to the server together with the whole form's content on submit.
2. Other editors cannot be initialised on a `<textarea>` so submitting their data must be handled by JS. One example how to do that can be found in https://stackoverflow.com/questions/46910377/can-i-use-ckeditor-5-inline-or-balloon-editor-on-a-form-submission.

**Comment by xssec** [comment]
Hi Reinmar,

Thank you for your info. Hope this will provide soon 😄

**Comment by ak868308** [comment]
I have the same issue
I implemented the ckeditor5 in Yii2 but when trying to submit a form textarea posts blank data
I am using ActiveForm.

**Comment by Reinmar** [comment]
Documented in https://github.com/ckeditor/ckeditor5/blob/master/docs/builds/guides/integration/saving-data.md. It will be published soon.
