### ISSUE TITLE
I want to use a button on the outside and then delete an internal widget

### ISSUE THREAD

**Issue by oldpubcat** [ckeditor/ckeditor5#6600]
Thanks for your open source.

I want to use a button on the outside and then delete an internal widget.

HTML
```html
  <div id="editor">
    <p>Editor content goes here.</p>
  </div>
  <input type="button" value="Delete" id="deleteBtn">
```

Suppose that now have multiple widgets inside the editor, I hit delete to select a widget by a class or ID and then delete it

js
```js
const selection = editor.model.document.selection;
editor.model.document.model.deleteContent(selection)
```

For example, his class is called 'title'.  how do I select the element I want by `selection` ?

**Comment by Mgsy** [comment]
Hi, I think the easiest way will be iterating through all the elements, checking their attributes and removing the item which matches your condition.

For the example purpose, let's assume that we operate on the editor's model and you'd like to remove all images with id 'foo' (remember that it's a model attribute, not a view attribute).

To get all the elements from the document, you can use a [TreeWalker](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html#function-getWalker). Everything happens in [`Model#change`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-change) block, so we'll be able to modify the model. Then, we check if an element is an image and verifying if its ID matches the one we want to remove. Finally, we call [`Writer#remove`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-remove) to delete the element.

See the example code below:

```js
editor.model.change( writer => {
	const root = editor.model.document.getRoot();
	const range = writer.createRangeIn( root );

	for ( const value of range.getWalker() ) {
		if ( value.item.is( 'image' ) ) {
			const itemId = value.item.getAttribute( 'id' );

			if ( itemId == 'foo' ) {
				writer.remove( value.item );
			}
		}
	}
} );
```

**Comment by oldpubcat** [comment]
Hi, guy. Thank you for answer!  

Maybe the above problem is not clearly described.

This is the example I just created.

For example：https://github.com/oldpubcat/CKEditorDemo

Clicking the black close icon when the widget is not selected will invalidate deleting the widget.

Can you help me?

**Comment by Mgsy** [comment]
I'm sorry, but I'm quite confused now. Do you want to remove the widget after clicking on your close icon or delete the widget after clicking `delete` button? Please, describe your use case more precisely.

**Comment by oldpubcat** [comment]
I'm sorry for the confusion,  clicking buttons and icon is the same thing,

button
```js
document.getElementById('deleteBtn').addEventListener('click', function(e) {
      const selection = editor.model.document.selection;
      editor.model.document.model.deleteContent(selection);
})
```

icon
```js
 document.getElementById('testClose').addEventListener('click', (evt, data) => {
      const selection = editor.model.document.selection;
      editor.model.document.model.deleteContent(selection)
})
```

I want in the case where the widget is not selected, like clicking on a button and then the widget is selected by some action, then it can be selected by `selection`, and then it can be deleted by `deleteContent`

I feel like the heart of the problem is how can a widget be selected externally in such a way that it has a selected state

maybe it's a little convoluted, I can record a video if I need to.

Thank you for patient reply!

**Comment by iKorso** [comment]
@Mgsy Hey, i am sorry for asking this after 3 years, but i cant find any solution for my case...
Your example code removing only first found element. Is there any methods which i can use to remove all matched elements? I added custom plugin which creates inline element with data-id attribute (and other not important in that case attributes). I am doing it by using some method outside editor via editor.execute(...) (like, clicking not related to editor button). My case is - there can be multiple elements with same data-id, and i need to remove all of them at once by other method outside of editor (again, clicking another not related to editor button once). Am i missing something in your example above or there is some tricks to do so?

**Comment by Witoso** [comment]
@iKorso the provided method iterates over all elements (items) of the editor's content and it's the easiest way to achieve what you also need. I don't think it's possible it only deletes the first element. It's a loop that matches all images and checks their id.

> there can be multiple elements

Make sure you have proper `if` matchers for those elements.

**Comment by AliaksandrBortnik** [comment]
@iKorso I believe it is possible that @Mgsy 's snippet doesn't work for your case if you need to remove multiple items. I would suggest to wrap as 
```javascript
editor.model.enqueueChange(writer => { 
    writer.remove(value.item);
};
```
 In this way, all changes will be a single batch.
 ```javascript
 editor.model.change( writer => {
    const root = editor.model.document.getRoot();
    const range = writer.createRangeIn( root );

    for ( const value of range.getWalker() ) {
        if ( value.item.is( 'image' ) ) {
            const itemId = value.item.getAttribute( 'id' );

            if ( itemId == 'foo' ) {
                editor.model.enqueueChange(writer => { 
                    writer.remove(value.item);
                };
            }
        }
    }
} );
 ```

**Comment by Witoso** [comment]
Thanks for commenting @AliaksandrBortnik. Actually after taking a deeper look, this example needs a small rewrite after 3 years. Below is a working example:

```javascript
editor.model.change( writer => {
	const root = editor.model.document.getRoot();
	const range = writer.createRangeIn( root );
	const itemsToRemove = [];

	for ( const value of range.getWalker() ) {
		if ( value.item.is( 'element', 'imageBlock' ) ) { // a different `is` usage.
			// writer.remove( value.item ); <- removal here won't work. We are in an iterator.
			itemsToRemove.push( value.item );
		}
	}
	for ( const item of itemsToRemove ) {
		writer.remove( item ); // remove all of the items.
	}
} );
```

The logic is one batch of changes, so there's one undo step for all. If you want to have them as separate batches, use  
them for each removal.

@iKorso apologies for the overlook.

**Comment by AliaksandrBortnik** [comment]
If he needs an undo for all removed, it is also possible to pass a Batch instance as the first param of `enqueueChange()`. Moreover, he can prevent from undo by passing `isUndoable: false` to the batch. It depends on requirements, for sure.

**Comment by Witoso** [comment]
> If he needs an undo for all removed.

Not needed actually, changes `editor.model.change` are combined into one undo step by default.
