### ISSUE TITLE
Two editors for same element

### ISSUE THREAD

**Issue by NagaraniG** [ckeditor/ckeditor5#6606]
I wanted to classic editor and balloon editor for same element

**Comment by Mgsy** [comment]
Hi, it's not possible to create multiple editors on a single element. Also, please take a look at our documentation explaining how to handle [two different editors](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors) on a single page.
