### ISSUE TITLE
Editor crashes when pressing tab in a table cell with selection on an image 

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6607]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/table.html.
2. Upload an image in a table cell (as the last child).
3. Select the image.
4. Tab.

### ✔️ Expected result

Probably the new table row should be created (or some sort of navigation).

### ❌ Actual result

The editor crashes.

![2020-04-15 12 54 41](https://user-images.githubusercontent.com/1099479/79329630-6f366580-7f18-11ea-847f-f94b530fe0f3.gif)

```
downcast.js:491 Uncaught TypeError: Cannot read property 'getChildren' of undefined
    at getExistingTableSectionElement (downcast.js:491)
    at getOrCreateTableSection (downcast.js:480)
    at DowncastDispatcher.<anonymous> (downcast.js:114)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:474)
    at DowncastDispatcher.convertInsert (downcastdispatcher.js:185)
    at DowncastDispatcher.convertChanges (downcastdispatcher.js:137)
    at editingcontroller.js:93
    at View.change (view.js:479)
    at Document.EditingController.listenTo.priority (editingcontroller.js:92)
```

## 📃 Other details

It exists prior to it31.

Have you seen this before @jodator, @ckeditor/qa-team?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Never seen it before. Unfortunately, it seems that it exists since version 18 (15, 16, 17 are ok).

**Comment by jodator** [comment]
This is highly weird. But I'd like to look at it after conversion in table fix PR: ckeditor/ckeditor5-table#301. Might be also related to the ckeditor/ckeditor5-table#304.

**Comment by FilipTokarski** [comment]
Bisection gives this output:
```
ae2f366204e38e630342fc7153cde2db09b30f89 is the first bad commit
commit ae2f366204e38e630342fc7153cde2db09b30f89
Author: Travis CI User <travis@example.org>
Date:   Tue Mar 3 21:24:21 2020 +0000

    Revision: https://github.com/ckeditor/ckeditor5-table/commit/f3d1dee9973f1c23d2c5fb4035b747e871bf18e2

:100644 100644 075fe59ce7d9e9457d517e1a301aa44cee137d91 22e8b112f8734b1bdd85eb44a4d998ffd42eda56 M	mrgit.json
```

**Comment by jodator** [comment]
Let's see this after ckeditor/ckeditor5-table#304.

**Comment by jodator** [comment]
Unfortunately it doesn't :/
