### ISSUE TITLE
Ctrl + A and Backspace does not delete the content

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#6608]
## 📝 Provide detailed reproduction steps (if any)

1. Set data with text and image at the end.
2. Mark all with Ctrl + A.
3. Press Backspace.

### ✔️ Expected result

To be able to delete the content.

### ❌ Actual result

Not able to delete the content.

## 📃 Other details

* Browser: Chrome (latest)
* OS: Windows 10
* CKEditor version: latest
* Installed CKEditor plugins:    
    Autoformat,
    BlockQuote,
    Bold,
    Heading,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Italic,
    Link,
    List,
    PasteFromOffice,
    Table,
    TableToolbar,
    SimpleUploadAdapter,
    FontSize,
    FontColor,
    FontBackgroundColor,
    FontFamily,
    Code,
    CodeBlock,
    ImageResize,
    Mention,
    RemoveFormat,
    Strikethrough,
    Underline,
    Essentials,
    Paragraph,
    InsertCardField,
    Fullscreen

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. This is a well-known issue which occurs in Chrome and Safari. Unfortunately, there's no solution yet. See https://github.com/ckeditor/ckeditor5/issues/4584 to learn more.
