### ISSUE TITLE
[Safari] Can't paste any file

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#661]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha.1

## 📋 Steps to reproduce

1. Open https://ckeditor5.github.io
2. Try pasting any image

## ✅ Expected result

Image is pasted and uploaded.

## ❎ Actual result

![image](https://user-images.githubusercontent.com/156149/32732871-1e663682-c88e-11e7-8c3e-e4047f4f722b.png)

Fails with "[object FileError]" message.

And:

> Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 4.)

Logged on the console.

## 📃 Other details that might be useful

The same with the latest dev version.

**Comment by Reinmar** [comment]
Turns out that it's more complicated than we thought. It doesn't work only on first load of this file. If you drop it to the editor before pasting it then pasting will work correctly.

**Comment by Reinmar** [comment]
The strange fact is that it works with drop, but not with paste. Which is odd because we handle both input methods in the same way.

**Comment by szymonkups** [comment]
It looks like Safari issue, medium editor and other has the same exact issue with copy/paste on Safari.

**Comment by f1ames** [comment]
I think @msamsel did some research recently. @msamsel could you share some insight about this?

**Comment by msamsel** [comment]
I've investigate it only in perspective for pasting images from word. What meant that I only analyse images in `text/html` and `text/rtf` clipboards. Currently Safari Technology Preview provides `blob:` url instead of `file:` which are displayed in the browser. This works for new Word (15.xx) and native TextEdit app. Some more info here: https://bugs.webkit.org/show_bug.cgi?id=124391#c105
I don't have any knowledge for image type clipboards.

**Comment by Reinmar** [comment]
That's sad :| Not the kind of news I hoped for... But thanks anyway! :D

**Comment by ccorcos** [comment]
I'm seeing this same issue. Weird that drag and drop works but paste doesnt...

**Comment by Reinmar** [comment]
I'm not sure what was causing this issue, but there's a chance that it got fixed by ckeditor/ckeditor5-image#248. @Mgsy, could you recheck this?

**Comment by Mgsy** [comment]
>I'm not sure what was causing this issue, but there's a chance that it got fixed by ckeditor/ckeditor5-image#248. @Mgsy, could you recheck this?

It has been fixed by https://bugs.webkit.org/show_bug.cgi?id=182536.
