### ISSUE TITLE
Pasting image from Google, with "Base64UploadAdapter", doesn't convert the image to base64.

### ISSUE THREAD

**Issue by felipegiotto** [ckeditor/ckeditor5#6610]
## 📝 Provide detailed reproduction steps (if any)

1. Open an editor with the "Base64UploadAdapter" plugin, which converts images to "data:image/png;base64" to make self-contained HTMLs (no uploads or external files needed).
2. Open google, search any image, right click on the image, "Copy image"
3. Paste the content into the editor

### ✔️ Expected result

The editor should convert the pasted image to base64.

### ❌ Actual result

The editor creates an "img" tag with the actual URL of the image.

## 📃 Other details

* Browser: Firefox 75.0 64bits
* OS: Ubuntu 16.04 LTS
* CKEditor version: 18.0.0
* Installed CKEditor plugins: Essentials, Alignment, Highlight, Autoformat, Bold, Italic, Strikethrough, Underline, BlockQuote, Heading, Image, ImageCaption, ImageToolbar, Indent, IndentBlock, List, Paragraph, PasteFromOffice, Table, TableToolbar, Base64UploadAdapter, Mention, TextTransformation, TableProperties, TableCellProperties.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

I found other related issues, but they seem to be about the real uploader plugin, not the base64 "fake" uploader.

**Comment by Mgsy** [comment]
Hi! Currently, the upload isn't triggered after pasting an image from external websites and it pastes as HTML. Please see the following issues to learn more - https://github.com/ckeditor/ckeditor5/issues/5152 https://github.com/ckeditor/ckeditor5/issues/2557.
