### ISSUE TITLE
All inputs become the same after emoji and 126 characters

### ISSUE THREAD

**Issue by jpaddison3** [ckeditor/ckeditor5#6612]
## 📝 Provide detailed reproduction steps (if any)

1. Go to: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
2. Make a new paragraph, and add an emoji to the paragraph
3. Type 140 or so characters (mash your keyboard)

### ✔️ Expected result

You can type characters

### ❌ Actual result

All characters after ~126 are the same character, despite pressing different keys

## 📃 Other details

* Browser: Chrome 80.0.3987.163
* OS: Mac OS 10.15.4
* CKEditor version: Example build of latest
* Installed CKEditor plugins:

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jimrandomh** [comment]
Replicates for me (Chrome 81.0.4044.92, Windows 10). Requires that the emoji be from outside the basic multilingual plane, for example U+1F9D0 🧐.

**Comment by Mgsy** [comment]
Hi, thanks for the report. This is a known issue and [has been fixed](https://github.com/ckeditor/ckeditor5-utils/pull/327) in the current iteration. It will be available in the next release which is scheduled to 29th April.
