### ISSUE TITLE
Disable site wide styles

### ISSUE THREAD

**Issue by Thhorster** [ckeditor/ckeditor5#6614]
Hello since ckeditor 5 doesn't use iframe how can you disable default website styles? Since most css frameworks adds styling to tag names and we plan to use editor for pdf it's big issue. As far as I'm aware there's only two options iframe or manually overriding every element which is obviously isn't good.

So basically can we use iframes or is there any other way to disable site styles?

**Comment by Mgsy** [comment]
@oleq, can you take a look at it?

**Comment by Reinmar** [comment]
It's impossible to use iframes within CKEditor 5. It was a conscious decision as using an iframe increases complexity of the entire frameworks, heavily affects performance and creates countless other issues.

The only way to disable site wide styles in the editor is therefore to write a stylesheet for `.ck-content` that will reset all these styles. I hope that one day HTML features such as web components will resolve this issue, but for now there's no easier solution than resetting all these styles manually.
