### ISSUE TITLE
Can't leave table if it's the only content inside the editor

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#6618]
## 📝 Provide detailed reproduction steps (if any)

1.  Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
2.  Delete everything inside the editor
3.  Insert table.

### ✔️ Expected result

The cursor can be moved outside the table using mouse or keyboard.

### ❌ Actual result

The cursor is trapped inside the table, without any way to move selection outside of it.

## 📃 Other details

*   Browser: Chrome 80.0.3987.163
*   OS: macOS 10.15.3
*   CKEditor version: 18.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
IMO, the solution to #407 should also resolve this issue, so I'm closing this as a DUP.
