### ISSUE TITLE
npm run test creates npm-debug.log

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#662]
I don't think that it did this in the past. Since we're using this command to run tests now all the time, this is really annoying.

**Comment by Reinmar** [comment]
To be more precise, that's how this command ends now:

![image](https://user-images.githubusercontent.com/156149/32733641-1fb13814-c890-11e7-839e-f3ee2479caba.png)

For some reason, it wasn't that verbose in the past.

**Comment by Reinmar** [comment]
PS. At the same time we need this command to crash our CI so we need proper error codes :D

**Comment by jodator** [comment]
I can see that you have very old NPM `v4`. I've got `v4.6.1` and logs are saved in `~/.npm/_logs` (or maybe this is configurable - dunno).

Apart of that I can see that NPM does output log for `run-script` and does not for `test`:

```sh
# This will not produce .log file:
npm t -- --files=engine
npm test -- --files=engine
# or silent
npm run --silent test -- --files=engine

# This will produce .log file (if test fails):
npm run test -- --files=engine
```

Are you sure that you didn't switch from `npm test` to `npm run test` after removing gulp?

I've found [Similar question](https://stackoverflow.com/questions/28489663/how-to-avoid-npm-debug-log-creation) on SO.

**Comment by jodator** [comment]
Also can be set in `.npmrc` as in [this SO answer](https://stackoverflow.com/questions/34426332/how-to-suppress-output-when-running-npm-scripts).

**Comment by Reinmar** [comment]
OK, thanks. I'll check what happens after an upgrade :)

**Comment by Reinmar** [comment]
Seems fine after I upgraded npm. Thanks.
