### ISSUE TITLE
TreeWalker returns same element twice

### ISSUE THREAD

**Issue by electerious** [ckeditor/ckeditor5#6622]
## 📝 Provide detailed reproduction steps (if any)

I'm trying to find elements using the TreeWalker / getWalker. My implementation looks like the following:

```js
findNodes(type, inElement) {
	const nodes = [];

	this.editor.model.change( writer => {
		const range = writer.createRangeIn( inElement );

		for ( const value of range.getWalker() ) {
			const node = value.item;

			if ( node.is( type ) ) {
				console.log('push'); // Executes two times
				nodes.push(node);
			}
		}
	} );

	return nodes;
}
```

```js
const nodes = this.findNodes('autocomplete', this.editor.model.document.getRoot());
console.log(nodes);
```

And this is how the DOM looks like. It's untouched and no changes have been made:

![DOM](https://user-images.githubusercontent.com/499088/79469933-1393d700-8001-11ea-8130-7243b73df60a.png)

The editor only contains one element of the type `autocomplete`, but `nodes` is an array with two items. Both referencing the same element.

### ✔️ Expected result

An array with one element.

### ❌ Actual result

An array with two elements.

![Output](https://user-images.githubusercontent.com/499088/79469764-e2b3a200-8000-11ea-8036-c39a8b981cc1.png)
## 📃 Other details

* Browser: Chrome, Safari, Firefox
* OS: macOS 10.15.4
* CKEditor version: 18.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
By default, the walker returns the beginning and also the element end of an element. There's an option to skip the "closing tags": https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html#function-getWalker
