### ISSUE TITLE
if inputting 2 character "_", then characters between the 2 "_" will transform to be Italics automatically. How can I cancel it?

### ISSUE THREAD

**Issue by iamwinter** [ckeditor/ckeditor5#6624]
if inputting 2 character "\_", then characters between the 2 "\_" will transform to be Italics automatically. How can I cancel it?
For example, I edit following word into ckeditor5
```
I have_some problems_, Could you help me?
```
Then "some problems" will be Italics automatically.
Could you help me to solve this issue?
Thank you!

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this issue and [it is already tracked here](https://github.com/ckeditor/ckeditor5/issues/2388), so feel free if you want to add anything to that topic.
As for now, the only solution would be disabling [Autoformat plugin](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html). You can do it by removing plugin from your editor configuration and rebuilding it.
