### ISSUE TITLE
Change the config on runtime

### ISSUE THREAD

**Issue by castroCrea** [ckeditor/ckeditor5#6625]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

When we use mention and we for exemple add a user after ckeditor5 is already up, we don't see it in the autocompletion mention list. 
I set the user on configuration and i can't update configuration after ckeditor is up

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Basically, there's no way to change the editor's config after the initialization. If your config has changed and you'd like to use it in the editor, the only solution will be [destroying](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-destroy) the current instance and [creating](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#static-function-create) a new one with the updated config.

However, it looks like your case doesn't require updating the whole editor. Mentions plugin supports a [callback for providing feed items](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#providing-the-feed), so it's possible to make an asynchronous call to your data storage which should return updated list.

**Comment by castroCrea** [comment]
@Mgsy 
After digging ⛏
I couldn't make it work because I don't use an external Api, but redux with react js. And the function is memorize, so it doesn't mute if parameters mutate.

For a hack I relaod the components if a mention parameters change, it's far from good but I only found this solution.

**Comment by Mgsy** [comment]
I'm glad that you found the solution :)
