### ISSUE TITLE
I have found some errors during writing through CK Editor-based text editor.

### ISSUE THREAD

**Issue by ami-dev-ko1** [ckeditor/ckeditor5#6626]
## 📝 Provide detailed reproduction steps

I have found some errors during writing through CK Editor-based text editor.

1. If you enter the space more than twice and then write something, the consonant of the first letter automatically repeats. (This error occurs when you write on a line with letters, words or sentences in the body text, not on the empty space)
![Error_1](https://user-images.githubusercontent.com/52805360/79552307-d3eaef00-80d5-11ea-866f-89b9848b9c52.gif)

2. Many characters with separated consonants & vowels are generating, when you enter the space more than twice and then move your mouse cursor to the left side more than two columns with the “left arrow key”. (Different from the first error, this error occurs even in the empty space without any letters, words or sentences)
![Error_2](https://user-images.githubusercontent.com/52805360/79552333-d8afa300-80d5-11ea-94a7-84eeaa33b04f.gif)

3. If you write something next to the link-inserted section, many characters with separated consonants & vowels generates. 

![Error_3](https://user-images.githubusercontent.com/52805360/79552371-e5cc9200-80d5-11ea-9838-c9d921ca86d2.gif)

* Browser: Chrome
* OS: Windows10
* CKEditor version: 18

**Comment by FilipTokarski** [comment]
Hi, thanks for the report and detailed info. Unfortunately, these issues are known and are confirmed. If you want to add anything to the topic, feel free to do so - we are tracking them here:
- [bug with multiple spaces](https://github.com/ckeditor/ckeditor5/issues/5895)
- [bug with link](https://github.com/ckeditor/ckeditor5/issues/3118)

I'll close this one as a duplicate.
