### ISSUE TITLE
Event only runs when there's more than one character

### ISSUE THREAD

**Issue by electerious** [ckeditor/ckeditor5#6628]
## 📝 Provide detailed reproduction steps (if any)

I'm want to listen for text changes inside an element. I'm currently adding the listener in the `editingDowncast` conversion as this seems to be the best way to create an event listener for all new and existing elements (let me know if there's a better way).

```js
conversion.for( 'editingDowncast' ).elementToElement( {
	model: 'autocomplete',
	view: ( modelElement, viewWriter ) => {
		const span = viewWriter.createEditableElement( 'span', {
			class: 'autocomplete'
		} );

		span.on('change:text', (e, node) => {
			console.log('change')
		});

		return toWidgetEditable( span, viewWriter );
	}
} );
```

### ✔️ Expected result

The callback should execute for all text changes.

### ❌ Actual result

The callback only executes when there's more than one character in the element.

`Hello`
`Hell` => Callback executes
`Hel` => Callback executes
`He` => Callback executes
`H` => Callback executes
`` => No callback
`H` => No callback
`Ha` => Callback executes
`Hal` => Callback executes

Here's a video: https://gofile.io/?c=6vuB8X

The element itself still exists, even when there's nothing inside.
## 📃 Other details

* Browser: Safari / Chrome / Firefox
* OS: macOS 10.15.4
* CKEditor version: 18
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Could you please prepare a simplified demo with a minimal amount of the code, so we'll be able to run it locally and investigate it?

**Comment by electerious** [comment]
I can't provide a working demo, sorry. I've worked around the issue by manually tracking changes of DOM nodes which was more reliable.
