### ISSUE TITLE
[Docs] CKEditor directory name @ckeditor left out on docs

### ISSUE THREAD

**Issue by nickmanning214** [ckeditor/ckeditor5#663]
https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/installation.html

Here in the npm section, I downloaded CKEDITOR using npm and it installed as `node_modules/@ckeditor/ckeditor5-build-inline/build/ckeditor.js`, but the docs leave out the `@ckeditor` directory when it says CKEditor will then be available at `node_modules/ckeditor5-build-[name]/build/ckeditor.js`. Not sure if this is an error or if there's something I'm missing.

**Comment by Reinmar** [comment]
This is our error. [Scoped packages](https://docs.npmjs.com/misc/scope) are installed in `node_modules/@SCOPE/*`. Thanks for reporting!
