### ISSUE TITLE
The arrow next to the "merge cells" button seems to be disabled

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6631]
## 📝 Provide a description of the improvement

When the button is disabled (because it's not applicable to single cell selections), the dropdown with options such as "split" or "merge cell left" should be available. It can be opened by click the arrow. However, to me, that arrow seems to be invisible. When the button is disabled, the arrow may be missed. I think that discoverability of that dropdown will be really hard.

I honestly don't know how we can improve this... Maybe the button shouldn't be off? Maybe it should have no action or display something when a single cell is selected?

![](https://user-images.githubusercontent.com/156149/79587054-3e019500-80d2-11ea-8365-4d8dc7881dd6.png)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @oleq @panr

**Comment by oleq** [comment]
I agree that it looks a little bit odd. Here are some options that popped into my head:

1. Make the merge cells a standalone button. Then make the merge/split tools a regular drop-down (always enabled). **Problems**: 
   * We need two different icons for the same functionality, 
   * We're bloating the toolbar.
2. We ignore the problem then implement the [unmerge functionality](https://github.com/ckeditor/ckeditor5/issues/6567) bound to the main button. The button will always be enabled and the vast majority of users will never need to open the drop-down in the first place. **Problems**:
   * We need another feature.
3. Somehow re-design of the split button to address the issue (???). **Problems**:
   * This will probably result in the re-design of the rest of the components.
   * That's pretty time-consuming.

**Comment by Reinmar** [comment]
I wonder if this could work:

*   When multiple cells are selected, the button merges them.
*   When only one, clicking the button opens the dropdown (button and arrow work in the same way).

At first I thought that it may be confusing. But then I realised that nothing bad will happen if you have just one cell selected – you'll simply see the dropdown panel with available options. When you have multiple cells selected, you will have a high chance of figuring out that there's a button and arrow and both are clickable. And if you click the button hoping for it to open the dropdown, you can always undo that.

**Comment by mlewand** [comment]
> *   When only one, clicking the button opens the dropdown (button and arrow work in the same way).

But you mean that the button would still have an icon of merge command? That would be misleading. How about changing the split button's "face" action in case the default one is disabled?

Agree that currently anybody looking at it first will always think it's disabled. Personally never seen something like that before.

**Comment by oleq** [comment]
> * When multiple cells are selected, the button merges them.
> * When only one, clicking the button opens the dropdown (button and arrow work in the same way).

Not sure if this is possible with the current architecture. That could mean a brand new component for that purpose.

Also... I agree with @mlewand that if you click something that looks like a drop-down it should act like one. It should open the panel, not execute some editing action.

----

> But you mean that the button would still have an icon of merge command? That would be misleading. How about changing the split button's "face" action in case the default one is disabled?

So like making the button disabled but announcing it by changing the icon only? This what the "disabled" state of the button is for. Also, users won't be able to tell why the thing is not working (the button is enabled, right?). And they will have to learn what each of the icons means, which could be a steep learning curve.

---

> Agree that currently anybody looking at it first will always think it's disabled. Personally never seen something like that before.

There's a similar case somewhere in CF. I remember explaining how to do that to someone in their team.

**Comment by Reinmar** [comment]
> Make the merge cells a standalone button. Then make the merge/split tools a regular drop-down (always enabled). **Problems**:
> 
> *   We need two different icons for the same functionality,
> *   We're bloating the toolbar.

Not really an option to due to the problems that you describe. I can't imagine how the icons could look.

> We ignore the problem then implement the [unmerge functionality](https://github.com/ckeditor/ckeditor5/issues/6567) bound to the main button. The button will always be enabled and the vast majority of users will never need to open the drop-down in the first place. **Problems**:
> 
> *   We need another feature.

Unmerge will also sometimes need to be off (when that cell wasn't merged previously). Also, I feel that it would be even more confusing than my proposal as you may be surprised by the result.

> Somehow re-design of the split button to address the issue (???). **Problems**:
> 
> *   This will probably result in the re-design of the rest of the components.
> *   That's pretty time-consuming.

I can't imagine simple and local changes that could be done here. Redesigning the entire toolbar for that is a no go too. So if you're consider it time-consuming, I don't think it's an option.

:( 

I'm afraid that this is a quite critical issue (the current styles) and that the only option is to make this a dropdown button and move the "Merge cells" to the dropdown.

**Comment by niegowski** [comment]
What if we split that dropdown in two separate buttons (merge and split) and get rid of "Merge cell up/left/right/bottom" (I think that this is legacy and very confusing). So we would have button for merging (without dropdown), and dropdown for split vertically/horizontally.

**Comment by jodator** [comment]
Unfortunately, the current behaviour look  broken to me. For some time I thought that something is broken.

![](https://user-images.githubusercontent.com/247363/79947295-0304b600-8472-11ea-812b-0ead64d2ddc0.gif)
