### ISSUE TITLE
TextTransformation is not enabled by default, but the docs say it is

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#6632]
To actually get TextTransformation to work in a custom build, I had to re-build it with

```
// src/ckeditor.js

import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation.js';

...

Editor.builtinPlugins = [
	Autoformat,
	Bold,
	Italic,
        ...
	TextTransformation
];
```

This was not mentioned in the documentation.

**Comment by Mgsy** [comment]
Hi, `TextTransformation` is enabled in all our builds, just like the documentation says. You can verify it [here](https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js#L31). Please, make sure that you use the latest released version (v18.0.0).

**Comment by neongreen** [comment]
I used a build created by the online builder, not one of the five pre-published builds.

My build ID was `mdr3d3gosspb-5n2uy9bk3s0`.

**Comment by neongreen** [comment]
The build was generated two days ago, so it's pretty recent.

**Comment by Mgsy** [comment]
Indeed, the online builder is missing `TextTransformation` plugin picked by default. However, you can easily add it manually by clicking `Add` button. 

Thanks for bringing it to our attention, the plugin will be added to the default plugins set in the next release which is scheduled to the end of this month. We'll track this issue in our private repository, so let's keep this one closed.
