### ISSUE TITLE
hello，When assigning a value to the editor, this code can't keep the class in the P tag, or it has been cleaned up

### ISSUE THREAD

**Issue by gongzhiq** [ckeditor/ckeditor5#6640]
```
class myAttachmentWidget extends Plugin {
	 init() {
        const editor = this.editor;
        const model = editor.model;
		
        model.schema.register( 'myAttachmentWidget', {
            inheritAllFrom: '$block',
            isObject: true
        } );
		
        editor.conversion.for( 'downcast' ).elementToElement( {
                model: 'myAttachmentWidget',
                view: ( modelElement, viewWriter ) => {
                    return viewWriter.createContainerElement( 'p', { class: "att_empty_paragraph"});
                }
            } );
			
        editor.conversion.for( 'upcast' ).elementToElement( {
                view: {
	 				name: 'p',
	 				classes: 'att_empty_paragraph'
	  			},
                model: 'myAttachmentWidget'
            } ) ;
    }
}

```

**What I want**

```
<p class='att_empty_paragraph'>
   <br/>
</p>
```

It's actually like this
```
<p>
    <br data-cke-filler="true">
</p>
```

When assigning a value to the editor, this code can't keep the class in the P tag, or it has been cleaned up

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not sure if I understood correctly, but if you just want a class to be added to every paragraph you create, you can use code like this:
```js
editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on( 'insert:paragraph', ( evt, data, conversionApi ) => {
  
        const viewWriter = conversionApi.writer;

        viewWriter.addClass( 'att_empty_paragraph', conversionApi.mapper.toViewElement(  data.item ) )
    }  );
}  );
```

First, it uses [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) to get access to [downcast dispatcher](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastDispatcher.html). It is then able to intercept every paragraph insertion. Then, thanks to [downcast conversion api](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastConversionApi.html), it uses [downcast writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html) and [mapper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_mapper-Mapper.html) to add a class to the paragraph.
Hope that helps!

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Could you please provide more detailed information about the plugin you are trying to create and what it should precisely do?

**Comment by gongzhiq** [comment]
@FilipTokarski Thank you for your answer!

I want to enter this format into the editor, 

```
<p class='att_empty_paragraph'>
   <br/>
</p>
```
but the editor will remove the "class" attribute

```
<p>
    <br data-cke-filler="true">
</p>
```

How can I keep the "class" attribute

**Comment by FilipTokarski** [comment]
To convert your custom model element to view element with class, you can use code like this:
```js
editor.model.schema.register('myAttachment', {
    inheritAllFrom: '$block'
});

editor.conversion.elementToElement( {
    model: 'myAttachment',
    view: {
        name: 'p',
        classes: 'my_class'
    },
    converterPriority: 'high'
} );
```
  
It will then automatically convert element between model and view, preserving the class:

![22_model1](https://user-images.githubusercontent.com/34380544/79959414-6861a280-8484-11ea-956e-8d52f6dcb610.gif)

This is a minimal implementation and you can further modify it to fit your specific needs.
Hope that helps!

**Comment by gongzhiq** [comment]
@FilipTokarski 
Thank you very much for your help to solve the problem!
Excuse me, what debugging tool do you use above? I can download a debugging code

**Comment by FilipTokarski** [comment]
It's our [CKEditor 5 Inspector](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/development-tools.html), a very useful tool if you want to see what happens inside the editor.

**Comment by gongzhiq** [comment]
@FilipTokarski Thank you very much
