### ISSUE TITLE
ClassicEditor.create is not a function

### ISSUE THREAD

**Issue by shrirangjoshi94** [ckeditor/ckeditor5#6644]
Hi,
I am facing this issue

ClassicEditor.create is not a function
I am using Jquery.

This is my code in JS

**let ClassicEditor = require('@ckeditor/ckeditor5-editor-classic/src/classiceditor');**

ClassicEditor.create(document.querySelector('#editor'), {
            toolbar: [
                'heading',
                'bold',
                'italic',
                'link',
                'bulletedList',
                'numberedList',
                'blockQuote',
                'undo',
                'redo'
            ],
        });

I was facing an issue while adding the plugin so I followed the below URL.
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

In my package.json this was the dependency listed

"dependencies": {
        "@ckeditor/ckeditor5-editor-classic": "^17.0.0",
        "@ckeditor/ckeditor5-font": "^17.0.0",
    }

I tried by updating the version to 18 as well by looking at your either comments.
Please provide a solution to this issue.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. To use the editor you need to build it first, only importing it like this is not enough. You can [build it by yourself](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html), or use our [online builder](https://ckeditor.com/ckeditor-5/online-builder/) to download a ready to use build with the plugins you choose.

**Comment by shrirangjoshi94** [comment]
Heyy Filip,
Thank you for the response.

As mentioned by you I have used the online builder(https://ckeditor.com/ckeditor-5/online-builder/) approach to build it according to my requirement.
I have uploaded the package on my personal GitHub account (**https://github.com/shrirangjoshi94/ckeditor5-custom-build**).
But when I try to install it in my project using the below command

**npm install https://github.com/shrirangjoshi94/ckeditor5-custom-build.git --save**

I get the premature close error.
Can you suggest to me what I am doing wrong?
I am new to NPM and in the documentation, I was unable to get how to integrate it with my current application using npm.

**Comment by FilipTokarski** [comment]
If you use online builder, you get an already built, working editor app ( `ckeditor.js` file ) and you don't need to install anything additionally. You can just use this file in your `html` file - see the CDN file example in the [quick start docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html) . You can also refer to docs on [installation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installation.html).
Apart from that, when using `npm`, you can install only packages that are in the `npm` repository. Please refer to this tutorial on [how to use npm](https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/).

**Comment by shrirangjoshi94** [comment]
Heyy Filip,
Thank you help. Actually I found a package on npm(https://www.npmjs.com/package/ckeditor5-build-classic-plus-font) which matched my exact requirement.
Still, I tried the method which you had suggested and learned a lot from this approach.
