### ISSUE TITLE
Allow hasSelectionHandle on EmptyElements

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#6650]
## 📝 Allow hasSelectionHandle on EmptyElements

_How the feature works now and what you'd like to change_?

Currently, the `toWidget` function's `hasSelectionHandle` option does not work on elements created with `createEmptyElement`. This is because [addSelectionHandle](https://github.com/ckeditor/ckeditor5-widget/blob/bfa6a620de8494d8e69239f278640448bca210ca/src/utils.js#L362) inserts a new element inside the element, which is only valid with non-empty elements. The selection handle is a super helpful way to make elements easy to select, but because of the way it's implemented, it's fundamentally incompatible with empty elements. Is there some way to redesign it to append the selection handle as a sibling, instead of a child?

_My usecase_

I have an `<iframe>` element that must be empty, and is also hard to select (because clicking inside an iframe sends the focus to the `src` document). Because the selection handle doesn't support empty elements, I'll have to create a custom workaround for these elements.

-----

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Unfortunately this would be hard. When this element is a child of the widgetized element it just stays together with it no matter what. If it was a sibling, then this would require some additional work to get it stick there (a view post-fixer would perhaps be sufficient). Plus, it's hard to predict some other issues that may arose. For instance, I have no idea how positioning could be done if they are siblings.

The workaround is quite simple too – use a `<div>` wrapper in the view. Wouldn't that work for you?

**Comment by rshipp** [comment]
Alright, thanks for the answer. Adding a surrounding element seems reasonable, I just can't do it right now since it would break backwards compatibility for all our content - have to wait for an editing freeze and migrate everything.

**Comment by Reinmar** [comment]
If by backwards compat you mean not changing the data (output), you can have this wrapper only in the editing view, while outputting a bare iframe in the data view.

**Comment by rshipp** [comment]
Oh, like a UIElement wrapping the EmptyElement? I didn't know that was possible, but I can look into it.

**Comment by Reinmar** [comment]
I meant ContainerElement wrapping the EmptyElement. Container element can be turned into a widget and your iframe will render inside it.

A bit similar to the media embed implementation although there we have ContainerElement wrapping a UIElement.
