### ISSUE TITLE
Setting language on the build-from-source

### ISSUE THREAD

**Issue by XPLing** [ckeditor/ckeditor5#6651]
I'm  using the CKEditor  build from source according to the official [document](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#building-the-editor-using-a-specific-language)

I have some trouble with the setting language that where should I put the translation files.

According to the official guide, we should use @ckeditor/ckeditor5-dev-webpack-plugin on the webpack.confi.json if build-from-source below.
```
const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' );

// Define webpack plugins...
    plugins: [
        new CKEditorWebpackPlugin( {
            // The main language that will be built into the main bundle.
            language: 'en',

            // Additional languages that will be emitted to the `outputDirectory`.
            // This option can be set to an array of language codes or `'all'` to build all found languages.
            // The bundle is optimized for one language when this option is omitted.
            additionalLanguages: 'all',

            // An optional directory for emitted translations. Relative to the webpack's output.
            // Defaults to `'translations'`.
            // outputDirectory: 'ckeditor5-translations',

            // Whether the build process should fail if an error occurs.
            // Defaults to `false`.
            // strict: true,

            // Whether to log all warnings to the console.
            // Defaults to `false`.
            // verbose: true
        } ),

        // Other webpack plugins...
    ]
// ...
```
The default value is 'translation' of the  **outputDirectory** option,  and the position is relative to the webpack's output.  we should create translation folder If the **additionalLanguages** option is  set, but I can't sure where should create the folder

## 📃 Other details

* Browser: Chorme
* OS: window
* CKEditor version: 18.0.0
* Installed CKEditor plugins: Essentials, Bold, Italic, Link, Paragraph, Image, ImageCaption,ImageStyle,   ImageToolbar,ImageUpload, EasyImage,CKFinder, List, Table,TableToolbar, Indent, Heading,   MediaEmbed

**Comment by FilipTokarski** [comment]
Hi @XPLing ! You do not need to create `translations` folder, it will be automatically created for you, when you [build the editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html). You can then change the language, just like in the [docs you linked to](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#building-the-editor-using-a-specific-language).
