### ISSUE TITLE
Selecting a whole paragraph by multiple clicks, also select an adjacent table

### ISSUE THREAD

**Issue by cedric-legallo** [ckeditor/ckeditor5#6652]
## 📝 Provide detailed reproduction steps (if any)

1. Having an editor with a table after a paragraph
2. Click multiple times on the paragraph to select its whole content
![Screencast 2020-04-23 11_06_25](https://user-images.githubusercontent.com/1001106/80081486-4b47d500-8553-11ea-824e-589fe2aede70.gif)

### ✔️ Expected result

The paragraph is selected, the table is not

### ❌ Actual result

The paragraph and the table are selected

## 📃 Other details

* Browser: Chrome
* OS: Linux and Windows, probably all
* CKEditor version: 5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this issue and [we are tracking it here](https://github.com/ckeditor/ckeditor5/issues/1839). If you wan to add anything to this thread, please feel free to do so. I'll close this one as a duplicate

**Comment by cedric-legallo** [comment]
Sorry for the duplication, i searched for it but was focused on the table keyword so did not find it. I thumbsed up there
