### ISSUE TITLE
Dev experience. The consistency of dependencies of tests of plugins.

### ISSUE THREAD

**Issue by kaluginserg** [ckeditor/ckeditor5#6657]
I try to clone the 'ckeditor5-table' project and run `npm install`, and then open the project in my IDE - and try to explore code.
But I have confusion with `ckeditor5-table/tests/tableediting.js`:

`import VirtualTestEditor from '@ckeditor/ckeditor5-core/tests/_utils/virtualtesteditor';`

I can't find this file in my `node_modules`. In package `@ckeditor/ckeditor5-core` there is no `tests` folder. It is not expected.

I know that exists instruction for the test environment, but I do not want to test, I just want to see the source code, and I expect that it be available when I clone the project and run `npm install`.

It probably will be better if will exist a separate npm package for `tests/_utils`(let's say smth like '@ckeditor/ckeditor5-core-test-utils') and place it to the 'devDependencies' of the `ckeditor5-table`, `ckeditor5-image` and etc.?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
A similar issue was reported in #6313. We're discussing how to resolve it. Let's keep this issue as the main one.

**Comment by Reinmar** [comment]
Doh :D We started discussing it in #6313, so let's close this one.
