### ISSUE TITLE
Docs: MathType formulas styling is broken

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6660]
## 📝 Provide a description of requested docs changes

1. Go to http://localhost:8080/build/docs/ckeditor5/latest/features/math-equations.html.
1. Try to select the default formula.
1. Add a new formula.

## Current result
There's no visual selection on the default formula and the new formula is styled incorrectly.

## GIF
![mathtype](https://user-images.githubusercontent.com/20988892/80188376-5cefb200-8611-11ea-9cdf-824fd000f6fa.gif)

## Notes
It works fine in manual tests, so it seems to be a docs issue.

**Comment by mlewand** [comment]
Unfortunately, after downgrading Mathtype lib to `7.19.0` version I'm still reproducing the issue so it is likely that our styles caused the issue.

**Comment by mlewand** [comment]
It's a duplicate of #2080.
