### ISSUE TITLE
Add table navigation to docs.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6663]
## 📝 Provide a description of requested docs changes

We do not have documentation for table navigation so at least it should be mentioned in "Features > Keyboard support" table.

**Comment by niegowski** [comment]
[There](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/keyboard-support.html) is some info about <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd>. I'm not sure if adding information about arrow keys would add any value, it seems intuitive how to use them. 

I noticed that there is no documentation about keyboard handling for widgets. Those are not there:
* <kbd>Enter</kbd> and <kbd>Shift</kbd>+<kbd>Enter</kbd> while widget is selected,
* Handling arrow keys when caret is next to widget or widget is selected.

Maybe we could split [Keyboard Support](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/keyboard-support.html) table to multiple sections to show Widget and Table custom keyboard handling?

**Comment by niegowski** [comment]
Also there is no info about <kbd>Tab</kbd> handling when table widget is selected.
