### ISSUE TITLE
conversion.attributeToAttribute - generates id for all the model elements. How do i restrict to a single element?

### ISSUE THREAD

**Issue by Shankar26G** [ckeditor/ckeditor5#6671]
conversion.attributeToAttribute( { model: 'id', view: 'id' } );

Especially when i copy paste a content i do get the below error

CKEditorError: conversion-attribute-to-attribute-on-text: Trying to convert text node's attribute with attribute-to-attribute converter

**Comment by Mgsy** [comment]
Hi, please [see my answer](https://github.com/ckeditor/ckeditor5/issues/6627#issuecomment-617659205) on a similar case, where `id` is added only for headings.
