### ISSUE TITLE
Page Styling not like in demo of Document Editor

### ISSUE THREAD

**Issue by Goyam** [ckeditor/ckeditor5#6673]
## 📝 Provide detailed reproduction steps (if any)

1. …Reproduced when installing via npm
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! If you'd like to get styles of our demo document editor, please [follow our guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html).

Also, while opening a new issue, please remember to provide a meaningful description of your issue. In most of the cases it's difficult to figure out what the author wants to achieve if he attached only a title.
