### ISSUE TITLE
The BlockToolbar button does not move during scrolling if the editor's height is limited

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#6675]
## 📝 Provide detailed reproduction steps (if any)

I used a sample provided with an online build of BalloonBlockEditor, and fixed editor height to 400px:

```diff
/* Inline & Balloon build. */
.ck.editor[role='textbox'] {
	width: 100%;
	background: #fff;
	font-size: 1em;
	line-height: 1.6em;
	min-height: var(--ck-sample-editor-min-height);
+	height: 400px;
	padding: 1.5em 2em;
}
```

The result is shown in the GIF below:

<img src="https://user-images.githubusercontent.com/1523306/80312731-7b130900-87ef-11ea-8b1c-1a4aa653ab5a.gif" width=500px>

## 📃 Other details

* Browser: Chrome, Safari
* OS: macOS
* CKEditor version: CKEditor 5 v18.0.0
* Installed CKEditor plugins: custom build `mdr3d3gosspb-5n2uy9bk3s0`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oskarwrobel** [comment]
DUP https://github.com/ckeditor/ckeditor5/issues/5460.
