### ISSUE TITLE
Tab behavior in the first and last cell of the table

### ISSUE THREAD

**Issue by panr** [ckeditor/ckeditor5#6676]
## Issue preview for both scenarios:

⚠️ It might take a while to load the whole GIF. Please be patient...

![ezgif com-resize](https://user-images.githubusercontent.com/1303365/80355479-721a4a00-8878-11ea-9792-29991ca499dc.gif)

## 1️⃣ First cell

1. Select the very first cell in the table
2. Press <kbd>Shift + Tab</kbd>.

### ✔️ Expected result

The focus should leave the table and should be moved to the previous focusable sibling, like it does in, for example - `Restricted Editing`.

### ❌ Actual result

The focus still stays in the first cell.

## 2️⃣ Last cell

1. Select the very last cell in the table
2. Press <kbd>Tab</kbd>.

### ✔️ Expected result

The focus should leave the table and should be moved to the next focusable sibling, like it does in, for example - `Restricted Editing`.

### ❌ Actual result

The new empty row has been added to the table.

## 📃 Other details

* Browser: Edge (Chromium)
* OS: macOS Mojave

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
<kbd>Tab</kbd> when in the last cell of a table - Insert a new table row - this is expected and documented here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/keyboard-support.html

**Comment by panr** [comment]
Huh, right. Didn't see it 😬. Also, I see that GDocs does the same, so it's how it should be, right?  I'm closing the issue then.
