### ISSUE TITLE
Disable text transforms inside <code>

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#6678]
When I'm editing inside inline \<code\>, text transformations should be disabled. Normal quotes should not be replaced with curly quotes, etc. This is already the case for code blocks.

Also — ideally, when I have typed `` `"foo" `` and then closed the `` ` ``, existing transformations inside `` ` ` `` should be undone. Slack's message editor does that. Alternatively, we can detect that we're inside what is soon to become a piece of code, and not apply transformations there. Perhaps this can be moved into a separate issue.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, thanks for the report. We're aware of this issue and it is reported already - https://github.com/ckeditor/ckeditor5/issues/1239. Feel free to add 👍 to the first post to bump its popularity.
