### ISSUE TITLE
Icons looks fuzzy on Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#668]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open editor on Firefox 57.
2. Lookup toolbar icons.

## ✅ Expected result
Chrome:
![selection_020](https://user-images.githubusercontent.com/247363/32879463-5ff0ed7c-caaa-11e7-9577-27b44cfdb613.png)

## ❎ Actual result
Firefox 57 (Quantum) / Linux Mint 18.2 (Sonya):
![selection_019](https://user-images.githubusercontent.com/247363/32879504-8d61cc22-caaa-11e7-89c6-9b9f8333c0f5.png)
## 📃 Other details that might be useful

I don't remember how that looked on previous Firefox.

**Comment by dkonopka** [comment]
As I see this fix is working:

```css
svg.ck-icon { 
     transform: translate3d( 0, 0, 0 ); 
}
```

**Comment by jodator** [comment]
I can confirm that it works for main toolbar icons but not with icons in dropdown:
![selection_021](https://user-images.githubusercontent.com/247363/32880285-6ab95b4c-caad-11e7-81ed-8ee60e2ce21e.png)

When disabled `translate3d( 0, 0, 0 )` in dev tools:
![selection_024](https://user-images.githubusercontent.com/247363/32880370-af4ef9f6-caad-11e7-98bc-83725bd300a8.png)
(the align right icon looks OK)...

**Comment by dkonopka** [comment]
We can also try a new fix for blurred elements:

```css
will-change: transform;
```

but currently, [it's not supported for IE/Edge](https://caniuse.com/#search=will-change) .

**Comment by Reinmar** [comment]
Icons were always fuzzy in Firefox. It's not something new (not a regression caused by Quantum).

**Comment by dkonopka** [comment]
@jodator  `.ck-dropdown__panel` needs fix too then. 

```css
will-change: transform
```

Anyway every `translate` property in CSS should be changed to `translate3d` property (or will-change). 

![screen shot 2017-11-16 at 11 04 40](https://user-images.githubusercontent.com/10219857/32885569-2813d928-cabe-11e7-8d38-c9bc4c647c4f.png)

**Comment by oleq** [comment]
PR please ❤️
