### ISSUE TITLE
The second enter in the code block feature should not escape it

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#6682]
## 📝 Provide a description of the improvement

It's pretty common to separate code using empty lines and every editor supporting code blocks should allow such a feature.

However, currently, after pressing enter two times the caret escapes the code block area :cry: This lowers the editing experience quite heavily while working with a large number of code snippets. The only workaround which is known to me is writing code first and pressing enters as the second step of creating a snippet.

IMO only the third enter should create a paragraph and remove the last (empty) line of the code block which was created by the second enter.

## 📃 Other details

*   CKEditor version: 18

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
> The only workaround which is known to me is writing code first and pressing enters as the second step of creating a snippet.

<kbd>Shift</kbd>+<kbd>Enter</kbd>

It does not mean I disagree with you. This is a potential UX issue.

**Comment by mlewand** [comment]
@ma2ciek you can put multiple subsequent line breaks using shift + enter

**Comment by Reinmar** [comment]
> IMO only the third enter should create a paragraph and remove the last (empty) line of the code block which was created by the second paragraph.

:+1: The same as in Slack, I believe. Makes sense to me. I was consider reporting this too.

**Comment by mlewand** [comment]
I also use shift+enter in such cases.

If we think about three enters it is a must that it removes tailing enter, because for me subsequent enter press is the only way I know how to leave the code block in a first place - which is something that I use much more often than multiple empty lines.

**Comment by oleq** [comment]
If anyone's interested in researching the feel of a triple enter, [this is where things should be changed](https://github.com/ckeditor/ckeditor5-code-block/blob/5300e22a9ceeb3ba321b1aacd74f9e5435405d1a/src/codeblockediting.js#L332-L410). 

I'm also putting an intro label here because the implementation part of this issue should be quite simple.

**Comment by ma2ciek** [comment]
\><kbd>Shift</kbd>+<kbd>Enter</kbd>

Oh, thanks, IDK why I didn't discover that combo. 

However it seems to be a discoverability issue as you guys mentioned it already.

**Comment by ma2ciek** [comment]
I missed that tip in the https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#tips-and-tweaks section - this should be fixed too.

**Comment by Reinmar** [comment]
Let's wait for some more feedback before doing anything here. The "triple Enter to escape" would be harder to discover than the current double Enter, so this isn't an easy change and might need some sort of configuration.

**Comment by marcellofuschi** [comment]
Just created a [PR](https://github.com/ckeditor/ckeditor5/pull/10316) to make the feature behave as described above in this issue.

I agree that this could be made configurable. The new behaviour might be a sensible default, though.
