### ISSUE TITLE
CkEditor5 doesn't work on firebase hosting

### ISSUE THREAD

**Issue by weilies** [ckeditor/ckeditor5#6683]
I have imported CKeditor5 into my project which run on StackBlitz, i can see the editor without error. But once i deployed into Firebase 
https://firestore-e23cb.firebaseapp.com/

It only reflect as 'loading...'
It's running on Chrome and i have no knowledge to fix it 

Here the console error. You may check out my app link above for the error detail.

> Unhandled Promise rejection: Unexpected end of input ; Zone: <root> ; Task: null ; Value: SyntaxError: Unexpected end of input
>     at eval (<anonymous>)...

**Comment by Reinmar** [comment]
HI! I'm afraid that we won't be able to help you. The error is not related to CKEditor 5 and I don't know how you built your app. But even knowing that, it does not seem like something related to CKEditor 5 itself. There are probably some other libraries involved.

Personally, I'd try e.g. removing CKEditor 5 and checking whether the error occurs as well. I think there's a big chance that it will.

**Comment by Reinmar** [comment]
PS. If you'll manage to debug it and find out that this is indeed some problem with CKEditor 5 (maybe some compatibility issue), then feel free to open a new ticket.
