### ISSUE TITLE
Costume build changing language when building from source

### ISSUE THREAD

**Issue by MAGGUNT** [ckeditor/ckeditor5#6684]
## 📝 Provide detailed reproduction steps (if any)

So I fork the classic-editor-build stable branch and changed the language in both the src/ckeditor.js and the wepack.config.js and language won't change. Then proceeded to download version 15.0.0 and 17.0.0 and it does work.

### ✔️ Expected result

Language change

### ❌ Actual result

Language is always english. 

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 18.0.0
* Installed CKEditor plugins: All plugins from classic build.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, did you add a translation file to your page? [As the documentation says](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#loading-additional-languages-from-cdn-npm-and-zip-file), it's required to add additional `<script>` element with a language file you'd like to use. 

If you use the classic build, you can find all translations in `build/translations` directory. For example, to load German, you'll need to add the following line:
```html
<script src="build/translations/de.js"></script>
```

**Comment by MAGGUNT** [comment]
Hi I was working on costume build by forking the classic-editor repo here https://github.com/ckeditor/ckeditor5-build-classic, from my understanding if you build from source you should just modify webpack.config.js and src/ckeditor.js  files. When I did that on version 17.0.0 of this same build it did work, as you said I also tried to add the translation file directly into  the html sample but nothing happen. Also I can see the right translation being added in the build/ckeditor.js but they don't change on version 18.0.0.

**Comment by MAGGUNT** [comment]
It's working for me fine in version 19.0.0
