### ISSUE TITLE
Is there any convention/rationale regarding passing locale?

### ISSUE THREAD

**Issue by tomalec** [ckeditor/ckeditor5#6687]
## Provide a description of the task

`locale` is used a lot in our components.
I noticed that in some places we are using `this.locale` in other we pass it through methods like `this._createColorGrid( locale )`. Is there any convention or rationale behind any of those? I think it would be good to sick to one, otherwise we end up passing an argument https://github.com/ckeditor/ckeditor5-table/blob/8c311ed46c50f00904ca35f5e6c80b82643b3307/src/ui/colorinputview.js#L95 to a function that uses the instance property https://github.com/ckeditor/ckeditor5-table/blob/8c311ed46c50f00904ca35f5e6c80b82643b3307/src/ui/colorinputview.js#L136 what is asking for troubles in my opinion.

## 📃 Other details

* Browser: n/a
* OS: n/a
* CKEditor version: master
* Installed CKEditor plugins: n/a

**Comment by jodator** [comment]
It looks like nobody noticed that before.

I'd go with not passing `locale` (or anything from `this` to speak more broadly) to internal methods. In this case passing `this.locale` looks weird.

OTOH if the `this.locale` is an only "external" variable then passing it to a function outside a class would be more common. So it would require to move the method from class to a function and pass `locale` as a parameter. But I reckon that this issue is not about that.

**Comment by Reinmar** [comment]
I thought that you're asking about why in some places we use the `editor.locale` object (taken e.g. from plugin's `this.editor.locale`) and sometimes we use the `locale` taken from [`ComponentFactory`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_componentfactory-ComponentFactory.html)'s callback.

It actually doesn't make much sense for `ComponentFactory` to pass `locale` to its callbacks but it's convenient and perhaps it's there also for some historical reasons. But it's true that in most (if not all) cases using `editor.locale` is possible as well.

We could prioritise one of these ways, but I don't know if thinking too much about this is worth the effort. While slightly confusing, this doesn't seem to be a big deal.

**Comment by tomalec** [comment]
Thanks for the answers. My main concern was, that I encounter a mixed usage of both when there was `locale` attribute present, but not used at all. Now, given all the above, I'd remove the unused attribute and stick to `this.locale`.

Closing as answered.
