### ISSUE TITLE
[Docs] Create a custom build example

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#669]
I'm thinking about creating "Examples => Builds => Custom build". This custom build will be a simplified editor with a subset of features (and maybe some new ones once we'll have them). It will also contain a link to a tutorial called "Creating a custom build". This tutorial will be a simple step-by-step guide to modifying an existing build and it will contain a "read more" link to https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html

OTOH, the existing "Custom builds" article is pretty simple for now (it may grow with time) so maybe it doesn't make sense to create a new tutorial. OTTH, in this quick tutorial I could show a quicker way than what we have so far (without forking, etc – just minimal steps).

The problem we want to solve is people now finding easily enough that they can create custom builds.

**Comment by wwalc** [comment]
Actually I found one candidate: enable the Underline button in a custom build.

**Comment by oleq** [comment]
I decided to KISS. I created an example linking to the existing "Creating custom builds" guide – as yet another way to reach that place.
