### ISSUE TITLE
Arrow keys should activate the magic block

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6692]
The block should then become ready (**"activated"**) for inserting content, but not be in the model yet to not break features like track changes or collaboration.

This can be implemented by adding an attribute to the model selection so the model structure is untouched. It comes down to the following scenario:

1. A widget is selected (e.g. the last child).
2. Arrow down in pressed.
3. Selection gets an attribute.
4. Conversion for the selection kicks in.
5. A late listener removes `.ck-selected` from a widget and adds a class (?) to the block (block becomes active).

**Comment by Reinmar** [comment]
DUP of #6693.
