### ISSUE TITLE
Pasting when the magic block is active should work as a regular paste

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6696]
The scenario is that a user activates the block, for instance, using the keyboard and then pastes some content.

This comes down to the integration with `insertContent`/`clipboardInput`. Needs research.

---

A piece of https://github.com/ckeditor/ckeditor5/issues/407.

**Comment by Reinmar** [comment]
I'd start with overriding insertContent because that will handle also some other features that use this method.

**Comment by oleq** [comment]
Some rough implementation ideas:

- we need to support when the selection is `DocumentSelection` only
- `evt.stop()`
- create a standalone selection where the insertion will happen (after/before a widget),
- calling `insertContent` for that selection,
- we use the result of `insertContent` for the standalone selection to modify the `DocumentSelection`,
- and return the right ranges.
