### ISSUE TITLE
Custom inline element disappear after setData() if it is the only or first element in tableCell

### ISSUE THREAD

**Issue by marcofanch** [ckeditor/ckeditor5#6698]
I target to create a plugin to insert FontAwesome icon to the editor.

_(I understand this is not a bug, but my lack of knowledge on the editor, anyhow when creating the ticket "bug" was the closest option from the list.)_

## Code

```js
// fontsymbolediting.js
// init()
    //.....

    schema.register('fontSymbol', {
      allowWhere: '$text',
      isInline: true,
      isBlock: true,
      isObject: true,
      allowAttributes: ['name'],
    });

    conversion.for('dataDowncast').elementToElement({
      model: 'fontSymbol',
      view: (modelItem, viewWriter) => {
        console.log('dataDowncast fontSymbol')
        const symbolName = modelItem.getAttribute('name');
        const symbolColor = modelItem.getAttribute(FONT_COLOR);

        const symbolElement = viewWriter.createUIElement(
          'i',
          {
            class: `m-font-symbol fas fa-${symbolName}`,
            style: `color: ${symbolColor}`,
          },
        );

        return symbolElement;
      },
    });

    conversion.for('downcast').elementToElement({
      model: 'fontSymbol',
      view: (modelElement, viewWriter) => {
        console.log('editingDowncast fontSymbol')
        const symbolName = modelElement.getAttribute('name');
        const symbolColor = modelElement.getAttribute(FONT_COLOR);

        const symbolElement = viewWriter.createUIElement(
          'i',
          {
            class: `m-font-symbol fas fa-${symbolName}`,
            style: `color: ${symbolColor}`,
          },
        );

        const viewWrapper = viewWriter.createContainerElement('span', {
          class: 'm-font-symbol-container',
          name: symbolName,
        });
        viewWriter.insert(viewWriter.createPositionAt(viewWrapper, 0), symbolElement);

        return toWidget(viewWrapper, viewWriter);
      },
    });

    conversion.for('upcast').elementToElement({
      view: {
        name: 'i',
        classes: ['m-font-symbol'],
      },
      model: (viewElement, modelWriter) => {
        const cssClasses = viewElement.getAttribute('class') || '';
        const name = (cssClasses.match(/fa-([\w-]+)/) || [])[1];

        if (!name) {
          return null;
        }

        const fontSymbolModel = modelWriter.createElement('fontSymbol', { name });

        return fontSymbolModel;
      },
    });
```

I took reference from the horizontal rule plugin, everything worked fine until I saved the data and reloaded it into the editor.

The icon was not showing up.

upcast() was called, model element returned, but the element did not appear.

I looked into table cell, and realized that table cell accept only block element.

I cannot find any example of putting inline element inside table cell.

However, if I pad an empty space before the icon, it can display properly, with the padded space of course.

### ✔️ Expected result

The inline icon appears in the table cell after setData()

### ❌ Actual result

Nothing shows up in the table cell

## 📃 Other details

* Browser: Chrome
* CKEditor version: 18
* Installed CKEditor plugins: font, table

**Comment by Reinmar** [comment]
Hi!

There are a couple of things that I spotted that can cause issues:

*   In the schema, you marked this element to be a block and inline one at the same time. It can't be both. In this case, inline would be the way to go.
*   You're downcasting this element to a UIElement (I mean `dataDowncast` here). That's unsafe and may not work. Every model element must be mapped to something in the view. While, a UI element is treated as "nothing". It's an element that's considered to be zero-length content. Its purpose is to display UI, not content itself. It could only be used inside a container element (check out the media embed feature for an example or https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/using-react-in-a-widget.html). Your `downcast` definition is hence correct – it uses a UIElement inside a container element. The model element maps to that container element and alls fine.
*   You have data downcast and then you have the general downcast. That's at least confusing. You should either have editingDowncast + dataDowncast or just downcast if the format is identical in both pipelines.

IDK if any of these is the reason of your problems, but you could try resolving them and see.

**Comment by stu43005** [comment]
I also encountered a similar problem.

I made a placeholder example on the documentation:
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

Insert a placeholder in the table: 
![image](https://user-images.githubusercontent.com/1288549/83835211-c1c71d80-a722-11ea-82f9-63e82d73b6b7.png)
getData(): `<figure class="table"><table><tbody><tr><td><span class="placeholder">{date}</span></td></tr></tbody></table></figure>`

Then I saved the data and reload it into the editor:
![image](https://user-images.githubusercontent.com/1288549/83835324-1074b780-a723-11ea-83bf-ef8915311549.png)
getData(): `<figure class="table"><table><tbody><tr><td>{date}</td></tr></tbody></table></figure>`

If insert a space before the placeholder, everything will be OK:
![image](https://user-images.githubusercontent.com/1288549/83835455-634e6f00-a723-11ea-8470-96abc3c4d23c.png)
getData(): `<figure class="table"><table><tbody><tr><td>&nbsp;<span class="placeholder">{date}</span></td></tr></tbody></table></figure>`

**Comment by Reinmar** [comment]
We fixed the problem and the patch will be included in the next release (planned around the end of August).

Thanks!

**Comment by MrMitch** [comment]
@Reinmar great news, thank you for the work put into this ! Looking forward to this.
