### ISSUE TITLE
Placeholder remains in editor if embedded media link is added in blank editor

### ISSUE THREAD

**Issue by parinda96** [ckeditor/ckeditor5#6699]
Embed media using the link in blank editor having placeholder

![placeholder-bug](https://user-images.githubusercontent.com/55236758/80561390-f2b88200-8a01-11ea-9380-86472575579b.png)

Note: The above screenshot is from the documentation page itself.

### ✔️ Expected result

The placeholder should be removed after adding any content (media/image).

### ❌ Actual result

Placeholder remains there even after I add some text content after the embedded video.

* Browser: Chrome
* OS: Windows
* CKEditor version: 5

**Comment by Mgsy** [comment]
Hi, thanks for the report, however, this is a known issue. You can find more information here - https://github.com/ckeditor/ckeditor5/issues/1684.
