### ISSUE TITLE
Support lang attribute

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#670]
## 🐞 Is this a bug report or feature request? (choose one)

- Feature request

## 💻 Version of CKEditor

1.0.0-alpha.2

## 📋 Steps to reproduce

It's impossible to use Classic Editor in systems where the input language in the editor is different than the language used by the CMS (e.g. in any systems where the content is translatable).

## ✅ Expected result

There should be a simple way to instruct Classic Editor to add `lang` attribute that will apply to the entered content. This is especially important, because otherwise the browser spellchecker is using the wrong language.

## ❎ Actual result

In case of Inline/Balloon editor this is plain simple as I can set the attributes on the editable element, in case of Classic Editor this is a bit more cumbersome:

```
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .then( editor => {
            editor.ui.view.editable.element.setAttribute('lang', 'de');
        } )
        .catch( error => {
            console.error( error );
        } );
```

## 📃 Other details that might be useful

Note: the inner content of the editor may have nothing to do with the interface language of the editor.

**Comment by oleq** [comment]
Since https://github.com/ckeditor/ckeditor5/issues/1151, you can set `config.language.content` that will change the `lang` attribute of the content (all editors).
