### ISSUE TITLE
Error checking image insertion

### ISSUE THREAD

**Issue by i-terezie** [ckeditor/ckeditor5#6707]
## 📝 Provide detailed reproduction steps (if any)

The error occurs when using a root editor of a type other than $root, which I defined as 
```
schema.register( 'DocumentTitle', {
            isLimit: true,
            allowContentOf: '$block'
        } );`
```
this.model.document.createRoot( sourceElements[rootName].root, rootName );
`
At sourceElements[rootName].root =  'DocumentTitle' 

### ✔️ Expected result

Normal work.

### ❌ Actual result

```
`TypeError: Cannot read property 'getAncestors' of null
    at new SchemaContext (schema.js:1176)
    at Schema.on.priority (schema.js:58)
    at Schema.fire (emittermixin.js:209)
    at Schema.<computed> [as checkChild] (observablemixin.js:259)
    at isImageAllowedInParent (utils.js:129)
    at isImageAllowed (utils.js:105)
    at ImageInsertCommand.refresh (imageinsertcommand.js:40)
    at Document.<anonymous> (command.js:111)
    at Document.fire (emittermixin.js:209)
    at Document._handleChangeBlock (document.js:317)`
```
## 📃 Other details

* Browser: Chrome 
* OS: Linux
* CKEditor version:  ^18.0.0
* Installed CKEditor plugins: 
CKEditorDocument.builtinPlugins = [
    Essentials,
    UploadAdapter,
    Autoformat,
    Bold,
    Italic,
    BlockQuote,
    EasyImage,
    Heading,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Indent,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    Table,
    TableToolbar,
    TextTransformation,
    testPlugin, //My plugin
    DocumentBox,//My plugin
    Placeholder //My plugin
];

---
I fixed this error by adding parrent check to null.

```
// Checks if image is allowed by schema in optimal insertion parent.
//
// @returns {Boolean}
function isImageAllowedInParent( selection, schema, model ) {
	const parent = getInsertImageParent( selection, model );
	if(parent===null)return(false);// My FIX
	return schema.checkChild( parent, 'image' );
}`

```

@ckeditor/ckeditor5-image/src/image/utils.js: 128.

I don’t know how correct this is, but after this edit everything began to work fine.

**Comment by Mgsy** [comment]
Hi, unfortunately, creating the editor on paragraph-like roots is not supported yet. Please, see the proper issue to learn more - #762.

However, feel free to open a pull request with proposed fix. We'll be happy to review and merge it :)
