### ISSUE TITLE
Support dir attribute

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#671]
Similar to #670, but may be more complex due to expected RTL support in the editor.

## 🐞 Is this a bug report or feature request? (choose one)

- Feature request

## 💻 Version of CKEditor

1.0.0-alpha.2

## 📋 Steps to reproduce

It's impossible to use Classic Editor in systems where the input language direction in the editor is different than by the language used by the CMS (e.g. in any systems where the content is translatable).

## ✅ Expected result

There should be a simple way to instruct Classic Editor to add `dir` attribute that will apply to the entered content. 

## ❎ Actual result

In case of Inline/Balloon editor this is plain simple as I can set the attributes on the editable element, in case of Classic Editor this is a bit more cumbersome:

```
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .then( editor => {
            editor.ui.view.editable.element.setAttribute('dir', 'rtl');
        } )
        .catch( error => {
            console.error( error );
        } );
```

## 📃 Other details that might be useful

Note: the inner content of the editor may have nothing to do with the interface language of the editor.

**Comment by oleq** [comment]
Since https://github.com/ckeditor/ckeditor5/issues/1151, you can set `config.language.content` that will change the `dir` attribute of the content (all editors).

**Comment by ashishforgrz** [comment]
This if for full editor but `<div dir="rtl">right</div>` does not work in ckeditor5 but was working for ckeditor4. Is there any way to support dir="rtl" for some only the tags where it is present.

**Comment by Witoso** [comment]
@ashishforgrz consider that the implementation of this feature may be different in the CKE5. Take a look at the [RTL support](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#righttoleft-rtl-languages-support) and [Text part language](https://ckeditor.com/docs/ckeditor5/latest/features/language.html). If you still want to support `rtl` via div, you need to enable this attribute in the [General HTML support.](https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html)
