### ISSUE TITLE
Update repository field in each sub-package's package.json file

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6712]
## Provide a description of the task

Currently the [`repository` field `package.json` files](https://github.com/ckeditor/ckeditor5/blob/a41a05a3c3e666eef06665f88d07d4109a2d4041/packages/ckeditor5-link/package.json#L45) point to old repository.

This has to be updated to point to proper monorepo location.

AFAIR you can point precisely subdirectory.

**Comment by pomek** [comment]
It will be fixed with https://github.com/ckeditor/ckeditor5/pull/6726.
Mentioned in https://github.com/ckeditor/ckeditor5/issues/6723. 

I am closing it as DUP.
