### ISSUE TITLE
URI with an authority must start with a slash "/" or be empty

### ISSUE THREAD

**Issue by Edgame2** [ckeditor/ckeditor5#6717]
I get this error and upload fails.
Using ckEditor with React.

PHP Fatal error:  Uncaught ErrorException: The path of a URI with an authority must start with a slash "/" or be empty. Automagically fixing the URI by adding a leading slash to the path is deprecated since version 1.4 and will throw an exception instead. in C:\\xampp\\htdocs\\ckfinder\\core\\connector\\php\\vendor\\guzzlehttp\\psr7\\src\\Uri.php:754\nStack trace:\n#0 [internal function]: CKSource\\CKFinder\\ExceptionHandler->errorHandler(16384, 'The path of a U...', 'C:\\\\xampp\\\\htdocs...', 754, Array)\n#1 C:\\xampp\\htdocs\\ckfinder\\core\\connector\\php\\vendor\\guzzlehttp\\psr7\\src\\Uri.php(754): trigger_error('The path of a U...', 16384)\n#2 C:\\xampp\\htdocs\\ckfinder\\core\\connector\\php\\vendor\\guzzlehttp\\psr7\\src\\Uri.php(497): GuzzleHttp\\Psr7\\Uri->validateState()\n#3 C:\\xampp\\htdocs\\ckfinder\\core\\connector\\php\\vendor\\microsoft\\azure-storage\\src\\Common\\Internal\\ServiceRestProxy.php(124): GuzzleHttp\\Psr7\\Uri->withPath('ckfinder/root-d...')\n#4 C:\\xampp\\htdocs\\ckfinder\\core\\connector\\php\\vendor\\microsoft\\azure-storage\\src\\Blob\\BlobRestProxy.php(1328): Micr in C:\\xampp\\htdocs\\ckfinder\\core\\connector\\php\\vendor\\guzzlehttp\\psr7\\src\\Uri.php on line 754,

Ant idea how to solve that ? Thank you for your help.

**Comment by Reinmar** [comment]
It seems that it has nothing to do with CKEditor 5 itself. You either misconfigured the upload URL (IDK which adapter you use) or the backend.
