### ISSUE TITLE
How to wrap a list item's text node

### ISSUE THREAD

**Issue by padevone** [ckeditor/ckeditor5#6719]
## Provide a description of the task

Hello. It's only a question.
I want to wrap a text node for every list item (li tag) in a span tag for applying styles, but after reading engine's documentation I don't know how to do it in the right way
Can you help me with it? I belive, that I can do it without rebuilding the editor

## 📃 Other details

I'm using this: https://github.com/ckeditor/ckeditor5-build-classic

**Comment by Mgsy** [comment]
Hi! I don't know what is your exact use case, however, you can [iterate through the elements](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html#function-getWalker) and [set the specified model attribute](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-setAttribute) for list items:

```javascript
const range = editor.model.createRangeIn( editor.model.document.getRoot() );

for ( const value of range.getWalker( { ignoreElementEnd: true } ) ) {
	if ( value.item.is( 'element' ) && value.item.name == 'listItem' ) {
		for ( const child of value.item.getChildren() ) {
			if ( child.is( 'text' ) ) {
				editor.model.change( writer => {
					writer.setAttribute( 'bold', true, child );
				} );
			}
		}
	}
}
```

**Comment by padevone** [comment]
Thanks, @Mgsy, for your feedback. I'll try it in my case
P.S. Sorry for my no answer, I've forgot about my question after several days
