### ISSUE TITLE
Emoji inserted via macOS emoji picker can be garbled in certain cases

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#6721]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-5/demo/
2. Replace the contents with `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx xxxxxxx xxxxxxx xxxxxxxxxxx xxxxxxxxxx xxxxxxxxx xxxxx xxx xxxxxxx xxxx xxxx xxxxxx xxxx xxxxx xxxx xx xxxxxxxxx xxx`
3. Put cursor before the first character
4. Insert 🎉using the macOS emoji picker (Ctrl+Cmd+Space). I can't reproduce this issue with Cmd+V.

### ✔️ Expected result

Emoji!

### ❌ Actual result

![image](https://user-images.githubusercontent.com/1523306/80914988-e1e87300-8d57-11ea-8132-79d799e7f9e0.png)

## 📃 Other details

* Browser: Vivaldi (Chromium)
* OS: macOS Mojave
* CKEditor version: ?
* Installed CKEditor plugins: ?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
Might be caused by the same bug as https://github.com/ckeditor/ckeditor5/issues/6612, if the version at ckeditor.com has not been updated yet.

**Comment by Reinmar** [comment]
Yup, this is fixed already and released as v19 already. The demo is not yet updated, so this issue is indeed still reproducible there.
