### ISSUE TITLE
Allow distinguishing between "cursor inside/outside inline code" (same as for links)

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#6722]
## 📝 Provide a description of the improvement

Currently, if you are at the end of a link, you can press <kbd>Right Arrow</kbd> once to "escape" it and type outside of the link. The link is highlighted when I'm inside it, but not when I'm outside. This is very convenient.

It would be great to have the same behavior for inline code. The only other editor I know that does this is the one used by Bitbucket. In this demo, note how I can escape the `<code>` merely by pressing <kbd>Right Arrow</kbd>.

![2020-05-03 16 25 46](https://user-images.githubusercontent.com/1523306/80915410-d3e82180-8d5a-11ea-92af-3fc351f14fb0.gif)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
Also note how in Bitbucket the cursor position doesn't change when I escape `<code>` — it is still visually inside the code. I wonder if it's possible to fix that, too.

**Comment by Reinmar** [comment]
:+1: We've been discussing enabling two-step caret movement for `<code>`s. That's the solution used for links and we can have the same for `<code>` elements. Would that be fine?

BTW, I think you can enable it already by using https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_utils_bindtwostepcarettoattribute.html#static-function-bindTwoStepCaretToAttribute.

**Comment by neongreen** [comment]
Sounds awesome

**Comment by oleq** [comment]
I stumbled upon this issue a few times while using the https://github.com/ckeditor/github-writer. I think this is pretty annoying and we should finally address the problem.

**Comment by Reinmar** [comment]
I don't think that we'll manage this in the current iteration because we have a full backlog already. But it's on our short priority list so it'd end up in June's iteration.

Unless, of course, you wanna help us ;)

**Comment by tomalec** [comment]
There are two new PRs for this change:
 - [ ] Attribute highlight code extracted from `link` to `typing` https://github.com/ckeditor/ckeditor5/pull/7546
 - [ ] 2SCM made to work with **two** steps and for multiple attributes https://github.com/ckeditor/ckeditor5/pull/7577 - this is still a draft, as I need to update Docs and Guides.

I believe the first PR can be reviewed now. In the meantime, I'll update the missing parts of the second one.
