### ISSUE TITLE
Wrong text format

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#6724]
## 📝 Provide detailed reproduction steps (if any)

1. Write this in Nodepad++:
```
test
	test 2
	test 3
		test4
			test5
				test6
					test7
```
2. Copy the text from the Notepad++.
3. Paste the text into the editor.

### ✔️ Expected result

The text to be formatted as it is in the notepad++

### ❌ Actual result

```
test
 test 2
 test 3
  test4
   test5
    test6
     test7
```

## 📃 Other details

* Browser: …
* OS: Every
* CKEditor version: Latest
* Installed CKEditor plugins: Doesn't matter

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! This is a sub-case of #1197. So, I'll close your ticket as a DUP.
