### ISSUE TITLE
Restore additional checks on CI

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#6742]
Before merging to the monorepo, for `ckeditor5-*` packages we had a few checks/tasks:

- JS linter
- CSS linter
- Dependency check
- Save revision

ATM, the repository executes only tests and checks the coverage.

We could consider restoring the scripts listed above:

- Linter – they are obvious,
- Dependency check – when to execute the script? For PR? For push to the master branch? For every commit? I guess we need to check all packages.
- Save revision script is no longer needed.

**Comment by mlewand** [comment]
I recall the dependency check being very useful. I think that doing it for PR + periodically on master (in case someone made a commit straight to the `master`) is good enough.

JS / CSS linter should go asap.
