### ISSUE TITLE
How can I integrate a custom ckeditor5 build to react project?

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor5#6747]
## Provide a description of the task
I build a custom ckeditor5 using the [online builder](https://ckeditor.com/ckeditor-5/online-builder/),  how can I integrate with my react project?
_What steps should be taken to fulfill the task?_
Create a custom build ckeditor5 project
## 📃 Other details

* Browser: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
* OS: OSX Mojave
* CKEditor version: 5
* Installed CKEditor plugins:

**Comment by Mgsy** [comment]
Hi! Please, see our [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html). Basically, you'll find there all the necessary information and step-by-step instructions.
