### ISSUE TITLE
TableSelection plugin should not contain mouse handlers

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#6757]
## 📝 Provide a description of the improvement

`TableSelection` plugin contains mouse handlers but they should be in separate plugin since `TableNavigation` is also using this plugin to make selections with keyboard.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
@niegowski Could you propose new classes after the split?

**Comment by niegowski** [comment]
### What we have

#### TableSelection Plugin

Contains mix of selection utils and converters with the mouse handlers.

*   `getSelectedTableCells()`
*   `getSelectionAsFragment()`
*   `setCellSelection( anchorCell, targetCell )`
*   `getFocusCell()`
*   `getAnchorCell()`
*   `_defineSelectionConverter()`
*   ~`_enableShiftClickSelection()`~
*   ~`_enableMouseDragSelection()`~
*   `_enablePluginDisabling()`
*   `_handleDeleteContent()`
*   ~`_getModelTableCellFromDomEvent()`~
*   `_getCellsToSelect( anchorCell, targetCell )`

Mouse handlers should be extracted to separate plugin.

#### TableNavigation Plugin

Contains only keyboard event handlers for moving caret inside table cell and also if expanding of selection is expected then it is using `TableSelection` to change selection (`setCellSelection`, `getFocusCell`, `getAnchorCell`).

### Proposed change

I would keep current `TableSelection` name but remove mouse handlers from there.

New name for `TableNavigation`:

*   `TableCaret`
*   `TableCaretHandling`
*   `TableCaretSelection`
*   `TableSelectionCaret`
*   `TableKeyboardHandling`

New name for mouse handlers extracted from `TableSelection`:

*   `TableCursor`
*   `TableCursorHandling`
*   `TableCursorSelection`
*   `TableSelectionCursor`
*   `TableKeyboardHandling`

I'm not sure which names are best matching the purpose and other plugins' names. What do you thing @jodator @Reinmar.

**Comment by jodator** [comment]
On F2F

1. The `TableNavigation` could be `TableKeyboard`.
2. The mouse thingy - `TableMouse` as we have no defenitive plans for touch handling ATM.

Just to have it "discoverable" by search.
