### ISSUE TITLE
[FF] Error after moving focus to the image caption using Tab

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#676]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret at `Heading 1`.
3. Press <kbd>Tab</kbd>

## ✅ Expected result
Focus should move to the caption without error.

## ❎ Actual result
Focus moves to the caption and there is the error in the console.

## 📃 Other details that might be useful
**Error**
```
NS_ERROR_FAILURE: renderer.js:623
_updateDomSelection renderer.js:623
_updateSelection renderer.js:558
render renderer.js:235
render document.js:277
decorate/< observablemixin.js:327
fire emittermixin.js:273
decorate/this[methodName] observablemixin.js:331
FocusObserver/</this._renderTimeoutId<
```

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/33010976-c1d50872-cddc-11e7-89d5-48b2c58525d3.gif)

**Browser:** Firefox 57 (Quantum).

**Note:** I'm able to reproduce this issue also in Firefox 56.

**Comment by ma2ciek** [comment]
I've checked it on Chome and Firefox@59 and listed below some results.

`NS ERROR FAILURE` it's a very generic Firefox error, it's hard to tell what actually goes wrong under the hood.

I see, that in the `_domSelectionNeedsUpdate` on FF, `oldViewSelection` is updated to the `figcaption`, but `this.selection` is not, so the Renderer tries later to move the selection to the place where the selection was before.

In Chrome, both `this.selection` and `oldViewSelection` were the same and pointing the `Caption`, so the Renderer didn't have to change it.

The 

https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/renderer.js#L634-L654

**Comment by ma2ciek** [comment]
Differences between Chrome and FF.

Note: the first rendering is because of the manually placed cursor at the beginning.

Chrome ViewSelection changes and rendering:

<img width="256" alt="screen shot 2017-12-04 at 16 18 02" src="https://user-images.githubusercontent.com/2768047/33559982-c8a3f004-d90e-11e7-8299-d82622e538c7.png">

FF ViewSelection changes and rendering:

<img width="645" alt="screen shot 2017-12-04 at 16 17 40" src="https://user-images.githubusercontent.com/2768047/33560015-de39765a-d90e-11e7-8900-1fc091011d62.png">

**Comment by ma2ciek** [comment]
I see that shift + tab from the caption doesn't work at all in the latest FF.

**Comment by ma2ciek** [comment]
It looks like the `selection:change` event is fired several milliseconds after the `focus:change` event on the FF and that implies wrong command execution order.

FF:
<img width="389" alt="screen shot 2017-12-05 at 14 37 12" src="https://user-images.githubusercontent.com/2768047/33609948-472ea9da-d9ca-11e7-8433-2555ad0e3f91.png">

Chrome:
<img width="385" alt="screen shot 2017-12-05 at 14 37 30" src="https://user-images.githubusercontent.com/2768047/33609950-49b32dac-d9ca-11e7-92ea-b6cfeef6b619.png">

It looks like we can increase the timeout in the https://github.com/ckeditor/ckeditor5-engine/blob/7755349c190f08e3806ae562f094823c5db57088/src/view/observer/focusobserver.js to solve that issue as we can't ensure correct order in a different way.

**Comment by ma2ciek** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/795

**Comment by Reinmar** [comment]
Can't we make the code more bulletproof? Selection changes should not depend on focus changes and vice versa.

We could, of course, increase the timeout but it's hard to tell to what value. At some point the delay in which the editor reacts will be noticable but the editor might be still unstable in some specific cases on overloaded and slow devices.

**Comment by ma2ciek** [comment]
> Can't we make the code more bulletproof? Selection changes should not depend on focus changes and vice versa.

Sure, I'll talk with @szymonkups about other possibilities. But I guess, it's not gonna be easy.

**Comment by ma2ciek** [comment]
After a F2F talks, we agreed that using longer `setTimeout` is ok for now as a quick bugfix, this will solve https://github.com/ckeditor/ckeditor5-engine/issues/1157 too. And then we should start working on the https://github.com/ckeditor/ckeditor5-engine/issues/796.
