### ISSUE TITLE
Tables creation with keyboard accessibility

### ISSUE THREAD

**Issue by dpavez14** [ckeditor/ckeditor5#6765]
# 📝 Provide a description of the improvement
Currently, it's not possible to create a table using only the keyboard.
When you open the table dropdown, there isn't any keystroke associated to change the number of rows and columns, so it's not possible to make a table using just the keyboard.

## ✔️ Expected  behavior
Open the dropdown and be able to:

- [ ] Increase the number of rows with the "arrow down" key.
- [ ] Decrease the number of rows with the "arrow up" key.
- [ ] Increase the number of columns with the "arrow right" key.
    - [ ] (on RTL it should decrease).
- [ ] Decrease the number of columns with the "arrow left" key.
    - [ ] (on RTL it should increase).
- [ ] Press "enter" to add the table.
    - [ ] Move the focus inside the table.
- [ ] Press "escape" to discard the creation of the table 
    - [ ] Keep on the toolbar.
- [ ] This functionality and each change (eg. "2 rows, 3 rows, 5 columns") should be announced with ARIA.

Another option could be to use some spinner (for rows and columns) to specify the numbers on the input box (similar to [AlloyEditor](https://alloyeditor.com/))

![imagen](https://user-images.githubusercontent.com/11673191/81387828-5b2fef00-90e5-11ea-87ed-40874bab2adc.png)

## 📃 Other details

- **Browser:** Any
- **OS:** Any
- **CKEditor version:** 19.0.0
- **Related issues:** #3184 #3161

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
This is a DUP of #3176.
