### ISSUE TITLE
Allow others to create table with headings

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6768]
## 📝 Provide a description of the improvement

We have two ways of inserting tables:

1.  `insertTable` command
2.  `TableUtils.createTable()` (used by the command)

Both allows to create table of given dimensions. I think that we could add `headingRows` and `headingColumns` to allow creating tables with headings.

Related: #6734.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by fredck** [comment]
FYI, I've worked-this-issue-around in GitHub Writer with [this commit](https://github.com/ckeditor/github-writer/commit/654532fe3f54d0ac21eea355c8df17ad9caed539#diff-be3d8fe7926338f9bfca3524465905e2R23-R34).

Basically, I'm executing "setTableRowHeader" right after "insertTable".

The drawback is that this creates a double undo step for the table insertion. Additionally, if the user undoes just the last step, the table will lose the header, which may be unexpected.
