### ISSUE TITLE
Insert id on each new line

### ISSUE THREAD

**Issue by castroCrea** [ckeditor/ckeditor5#6778]
## 📝 Description of the new feature

When with hit enter or past element each new line as a unique identifier
Each node as an identifier and we can get the identifier of the selection

I will need that to add context to associated data to each line

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. To insert an `id` every time you insert a newline ( i.e. a paragraph ) you can use code like this:
```js
editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on( 'insert:paragraph', ( evt, data, conversionApi ) => {
				
    const viewWriter = conversionApi.writer;
				
    viewWriter.setAttribute( 'id', 'my_unique_id', conversionApi.mapper.toViewElement(data.item ) )

    } );
} );
```
This is a basic implementation and you can further adjust it to your needs and, of course, to work with elements other than paragraph. Here you can read more about the [editing engine architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html), [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html), [writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html), [mapper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_mapper-Mapper.html).
Hope that helps!

**Comment by castroCrea** [comment]
Thanks a lot it helps to understand better the architecture.

**Comment by enzolry** [comment]
> Hi, thanks for the report. To insert an `id` every time you insert a newline ( i.e. a paragraph ) you can use code like this:
> 
> ```js
> editor.conversion.for( 'downcast' ).add( dispatcher => {
>     dispatcher.on( 'insert:paragraph', ( evt, data, conversionApi ) => {
> 				
>     const viewWriter = conversionApi.writer;
> 				
>     viewWriter.setAttribute( 'id', 'my_unique_id', conversionApi.mapper.toViewElement(data.item ) )
> 
>     } );
> } );
> ```
> 
> This is a basic implementation and you can further adjust it to your needs and, of course, to work with elements other than paragraph. Here you can read more about the [editing engine architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html), [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html), [writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html), [mapper](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_mapper-Mapper.html).
> Hope that helps!

Hi,
I managed to insert my custom attribute 'data-id' to 'insert:image' and 'insert:table' elements. But then, when I edit the content again, the editor inserts a new value to 'data-id' attribute even though the elements already have one. How can I do to make sure the editor take existing 'data-id' attribute into account and does not replace them every time ?
Thanks
