### ISSUE TITLE
[FF] Editor crashes after deleting block elements with the image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#678]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-Alpha2

## 📋 Steps to reproduce

1. Go to http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.html.
2. Start the selection in the block quote and move it to the `OL List item 2`.
3. Press <kbd>Delete</kbd>.

## ✅ Expected result
Selected block elements should disappear.

## ❎ Actual result
Editor crashes.

## 📃 Other details that might be useful
**Error**
```
TypeError: element is null schema.js:405
getLimitElement schema.js:405
_shouldEntireContentBeReplacedWithParagraph deletecommand.js:140
execute/< deletecommand.js:86
enqueueChanges document.js:237
execute deletecommand.js:68
decorate/< observablemixin.js:327
fire emittermixin.js:273
decorate/this[methodName] observablemixin.js:331
execute commandcollection.js:67
execute editor.js:193
init/< delete.js:37
fire emittermixin.js:273
DeleteObserver/< deleteobserver.js:47
fire emittermixin.js:273
fire domeventobserver.js:96
onDomEvent keyobserver.js:28
observe/</< domeventobserver.js:79
fire emittermixin.js:273
domListener emittermixin.js:248
```

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/33012828-593e9598-cde2-11e7-858b-9db1db43302f.gif)

**Related** - https://github.com/ckeditor/ckeditor5/issues/675

**Browser:** Firefox 57 (Quantum)

**Notes:** 
- It occurs also if in step 3 you paste some content or use `cut`.
- I'm also able to reproduce it in Firefox 56.

**Comment by Reinmar** [comment]
OK, turns out that FF creates two ranges in this case.

Add this in `Schema#getLimitElement()`:

```
console.log( stringify( selection.getFirstPosition().root, selection ) );
```

And you'll get:

```html
<heading1>Heading 1</heading1>
<paragraph>Paragraph</paragraph>
<paragraph><$text bold="true">Bold</$text> <$text italic="true">Italic</$text> <$text linkHref="foo">Link</$text></paragraph>
<listItem indent="0" type="bulleted">UL List item 1</listItem>
<listItem indent="0" type="bulleted">UL List item 2</listItem>
<listItem indent="0" type="numbered">OL List i[tem 1</listItem>
<listItem indent="0" type="numbered">OL List item 2</listItem>]
<image alt="bar" imageStyle="imageStyleSide" src="sample.jpg"><caption>[Caption</caption></image>
<blockQuote>
    <paragraph>Quote</paragraph>
    <listItem indent="0" type="bulleted">Quoted UL List item 1</listItem>
    <listItem indent="0" type="bulleted">Quote]d UL List item 2</listItem>
    <paragraph>Quote</paragraph>
</blockQuote>
```

Apparently, `getLimitElement()` fails to return the limit element for that selection `null` is returned.

**Comment by Reinmar** [comment]
Naturally, `$root` should be returned for this selection.

**Comment by Reinmar** [comment]
It's probable that similar issue occurs in https://github.com/ckeditor/ckeditor5/issues/675, so let's check it after fixing this issue.

**Comment by pomek** [comment]
I replaced a callback used inside the `Schema#getLimitElement()`:

https://github.com/ckeditor/ckeditor5-engine/blob/2d9f8fa33404e4723cde6240c3157ceb24713a55/src/model/schema.js#L584-L590

with this:

```js
( node, range ) => {
	if ( !node ) {
		return range.getCommonAncestor();
	}

	const rangeCommonAncestor = range.getCommonAncestor();

	// If the node is also the common ancestor for the range, let's use it.
	if ( node === rangeCommonAncestor ) {
		return node;
	}

	return node.getCommonAncestor( rangeCommonAncestor );
}
```

The editor does not crash but the content is not removing:

![image](https://user-images.githubusercontent.com/2270764/35734666-38d700fe-0822-11e8-952d-64c123490fea.png)

Selection contained `OL List item 2` (from the second list) and `Quote` (from the blockquote). After pressing `Backspace`, the text from the list was removed. On Chrome it works fine.

I guess it's something broken with the image because, without the image, it works fine.

**Comment by pomek** [comment]
A @Reinmar answer to the question – does why is content being removed partially in FF?

> The content is not being removed because deleteContent() cares about the first range only. There's a separate ticket for this: ckeditor/ckeditor5-engine#366.

**Comment by pomek** [comment]
Note for me:

https://github.com/ckeditor/ckeditor5-typing/commit/6df1ab19d226f6f63b059b500b2269cbb3b81448 waits until https://github.com/ckeditor/ckeditor5-engine/issues/1281 will be fixed.
