### ISSUE TITLE
I hope to support the copy and paste of WPS

### ISSUE THREAD

**Issue by 1baoxiaobowfj** [ckeditor/ckeditor5#6783]
The function of paste word is very good. I hope can paste WPS

**Comment by Mgsy** [comment]
Hi, thanks for the report. Unfortunately, pasting a content from WPS is not supported. However, we have [open feature request](https://github.com/ckeditor/ckeditor5/issues/2488) for it, feel free to add :+1: to the first post and join the discussion to bump its popularity.
