### ISSUE TITLE
Japanese language patch

### ISSUE THREAD

**Issue by higty** [ckeditor/ckeditor5#6792]
## 📝 Provide a description of the improvement
I created new Japanese translation file for version 19.0.0 based on this.
<script src="https://cdn.ckeditor.com/ckeditor5/19.0.0/classic/translations/ja.js"></script>

`(function (d) { const l = d['ja'] = d['ja'] || {}; l.dictionary = Object.assign(l.dictionary || {}, { "%0 of %1": "", "Upload file": "ファイルのアップロード", "Highlight": "ハイライト", "Insert code block": "コードの挿入", "Text alignment": "テキストの位置", "Insert media": "動画の挿入", "Align left": "左", "Align right": "右", "Align center": "真ん中", "Justify": "均等配置", "Increase indent": "インデントの挿入", "Decrease indent": "インデントの削除", "Block quote": "ブロッククオート(引用)", Bold: "ボールド", "Bulleted List": "箇条書きリスト", Cancel: "キャンセル", "Cannot upload file:": "ファイルをアップロードできません:", "Centered image": "中央寄せ画像", "Change image text alternative": "画像の代替テキストを変更", "Choose heading": "見出しを選択", Column: "列", "Could not insert image at the current position.": "", "Could not obtain resized image URL.": "", "Delete column": "列を削除", "Delete row": "行を削除", Downloadable: "", "Dropdown toolbar": "", "Edit link": "リンクを編集", "Editor toolbar": "", "Enter image caption": "画像の注釈を入力", "Full size image": "フルサイズ画像", "Header column": "見出し列", "Header row": "見出し行", Heading: "見出し", "Heading 1": "見出し1", "Heading 2": "見出し2", "Heading 3": "見出し3 ", "Heading 4": "", "Heading 5": "", "Heading 6": "", "Image toolbar": "", "image widget": "画像ウィジェット", "Insert column left": "", "Insert column right": "", "Insert image": "画像挿入", "Insert image or file": "画像やファイルの挿入", "Insert row above": "上に行を挿入", "Insert row below": "下に行を挿入", "Insert table": "表の挿入", "Inserting image failed": "", Italic: "イタリック", "Left aligned image": "左寄せ画像", Link: "リンク", "Link URL": "リンクURL", "Merge cell down": "下のセルと結合", "Merge cell left": "左のセルと結合", "Merge cell right": "右のセルと結合", "Merge cell up": "上のセルと結合", "Merge cells": "セルを結合", Next: "", "Numbered List": "番号付きリスト", "Open in a new tab": "", "Open link in new tab": "新しいタブでリンクを開く", Paragraph: "パラグラフ", Previous: "", Redo: "やり直し", "Rich Text Editor": "リッチテキストエディター", "Rich Text Editor, %0": "リッチテキストエディター, %0", "Right aligned image": "右寄せ画像", Row: "行", Save: "保存", "Select column": "", "Select row": "", "Selecting resized image failed": "", "Show more items": "", "Side image": "サイドイメージ", "Split cell horizontally": "縦にセルを分離", "Split cell vertically": "横にセルを分離", "Table toolbar": "", "Text alternative": "代替テキスト", "This link has no URL": "リンクにURLが設定されていません", Undo: "元に戻す", Unlink: "リンク解除", "Upload failed": "アップロード失敗", "Upload in progress": "アップロード中" }); l.getPluralForm = function (n) { return 0;; }; })(window.CKEDITOR_TRANSLATIONS || (window.CKEDITOR_TRANSLATIONS = {}));`

**Comment by ma2ciek** [comment]
Hi,

Thanks for the translations!!

However, note, that these translations might be lost in the big number of issues. If you want to help translate CKEditor 5 into the Japanese language, join the [CKEditor 5 project on Transifex](https://www.transifex.com/ckeditor/ckeditor5/) and add these translations there. Your help will be much appreciated!

**Comment by higty** [comment]
I see.
I registered Transifex and send request to paticipate.

**Comment by Mgsy** [comment]
> I see.  
> I registered Transifex and send request to paticipate.

Great to hear :) Thank you for your contribution! I'm closing this ticket, however, if you'll have any questions - feel free to ask.

**Comment by higty** [comment]
@Mgsy 
I added translation at Transifex. Please review if you would have a time.

**Comment by ma2ciek** [comment]
We won't review these translations as we don't know Japanese. But other Japanese members of  Transifex will review :)

**Comment by higty** [comment]
Okey. I got it.
Keep going CKEditor!
