### ISSUE TITLE
Attachment button like in mail client. In case user wants to build mail client in react app with ckeditor.

### ISSUE THREAD

**Issue by kumarProspera** [ckeditor/ckeditor5#6797]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. CKEditor 5 should be treated as a component in your mail application for creating a content (messages). It means that other "mail client" functionalities, like adding an attachment to the message, should exist in your application's scope, not in the editor.
