### ISSUE TITLE
Error on insertContent

### ISSUE THREAD

**Issue by nirav-rb** [ckeditor/ckeditor5#6798]
I am trying to use insertContent method but getting some error.

Here is my implementation

```
<div id="editor">
    <p>This is the editor content.</p>
</div>
<button onclick="update()">update</button>

<script src="./node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js"></script>
<script>
    var editorInstance;
    ClassicEditor
        .create(document.querySelector('#editor'))
        .then(editor => {
            editorInstance = editor;
        })
        .catch(error => {
            console.error(error);
        });

    function update() {
        editorInstance.model.insertContent("<p><b>Test</b> Content</p>")
    }
</script>

```
update method should update the editor source with given content, but I am getting an error

Error on the console:

> Uncaught TypeError: e.is is not a function
>     at xc.Nm (converters.js:777)
>     at xc.fire (emittermixin.js:209)
>     at xc.<computed> [as insertContent] (observablemixin.js:259)
>     at update (ck5.html:19)
>     at HTMLButtonElement.onclick (ck5.html:4)

 Can anyone please help in sorting out this issue?

**Comment by Mgsy** [comment]
Hi! `Model#insertContent` doesn't support inserting content directly from HTML string. If you'd like to do it, you'll have to process the HTML. Please, see the updated code for `update()` function:

```javascript
    function update() {
		const htmlString = '<p><b>Test</b> Content</p>';
		const htmlDP = editorInstance.data.processor;
		const viewFragment = htmlDP.toView( htmlString );

		const modelFragment = editorInstance.data.toModel( viewFragment );

		editorInstance.model.insertContent( modelFragment );
    }
```

Also, see [`Model#insertContent`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent) documentation to learn more about it.

**Comment by nirav-rb** [comment]
Thank you so much for the speedy reply @Mgsy
