### ISSUE TITLE
[FF] Incorrect selection after applying inline style to the content with image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#680]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-Alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Start the selection in the block quote and move it to the `Heading 1`.
3. Press `Bold`.

## ✅ Expected result

Content should receive bold and the selection should remain unchanged.

## ❎ Actual result

Bold has been applied to selected content, but the selection has moved below the image.

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/33017060-3a451c16-cdf1-11e7-8d2c-be99a5d92b8c.gif)

**Browser:** Firefox 57 (Quantum)

**Note:** I'm also able to reproduce it in Firefox 56.

**Comment by Reinmar** [comment]
WFM now.
