### ISSUE TITLE
Error when when loading the base package from NPM & locally

### ISSUE THREAD

**Issue by AndrewCloss** [ckeditor/ckeditor5#6803]
Hi folks, I'm trying to load CKEditor5 in my view however my Laravel Mix is not loading the package properly.
### Approach 1
package.json
`"dependencies": { "@ckeditor/ckeditor5-build-classic": "^19.0.0" }`
editor.js
`require('@ckeditor/ckeditor5-build-classic');`
webpack.mix.js
`mix.js('resources/js/editor.js', 'public/js');`
edit.blade.php
`<script src="{!! mix('js/editor.js') !!}"></script>`
I get:
>Uncaught ReferenceError: ClassicEditor is not defined

However the 'editor.js' is loaded in my browser's Network tab. Here is the pastebin (minus the minified code, too big for pastebin): https://pastebin.com/iAh2Y95c

### Approach 2
I used the online builder and moved it into my project.

webpack.mix.js
`mix.copyDirectory('resources/js/ckeditor5', 'public/js/ckeditor5');`
edit.blade.php
`<script src="/js/ckeditor5/src/ckeditor.js"></script>`

I get `Uncaught SyntaxError: Unexpected identifier` error on line 5 of `ckeditor.js`:
> import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';

**Comment by Mgsy** [comment]
Hi! As I can see, you use the following import:

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
```

It's the editor class which should be used for creating a build. As well this one:

```html
<script src="/js/ckeditor5/src/ckeditor.js"></script>
```

It's the editor configuration, not the build. The file you should import is a build which could be found in `build` directory. So, if you use our online builder, updated script tag should look like this:

```html
<script src="/js/ckeditor5/build/ckeditor.js"></script>
```

**Comment by AndrewCloss** [comment]
That works, I appreciate it Kacper!

**Comment by Mgsy** [comment]
Great to hear that it works :) Have fun with CKEditor 5!
