### ISSUE TITLE
Downcast elementToElement() can't create "attribute elements"

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#6807]
During downcasting, it should be possible to do the following (e.g.):

```javascript
editor.conversion.for( 'dataDowncast' ).elementToElement( {
	model: 'emoji',
	view: ( modelElement, viewWriter ) => {
		// Create an attribute element.
		const emoji = viewWriter.createAttributeElement( 'span' );

		// Create text to insert into the element.
		const viewText = viewWriter.createText( `:${ modelElement.getAttribute( 'name' ) }:` );

		// ... but the following will throw an error :(
		viewWriter.insert( viewWriter.createPositionAt( emoji, 0 ), viewText );

		return emoji;
	}
} );
```

The above throws because `DowncastWriter.insert` enforces the insertion position to be inside a "container element", not an "attribute element" : https://github.com/ckeditor/ckeditor5/blob/fb5fe8b8950cf11700d691bd4369b8bb8aa12cf2/packages/ckeditor5-engine/src/view/downcastwriter.js#L639

### Workaround (hack) causes other issues

The only hack/workaround for the above is replacing `createAttributeElement( 'span' )` with `createContainerElement( 'span' )`. That's, in fact, [the wait it is implemented right now](https://github.com/ckeditor/github-writer/blob/94cabb026a574984df0c4ab2bc2216089dc8eee0/src/app/plugins/emoji.js#L101-L113).

The problem with `createContainerElement` is that it enforces a series of rules that don't apply for an inline element (`span`). For example, [it forces a space character present before itself to be replaced with a non-breaking-space](https://github.com/ckeditor/ckeditor5/blob/fb5fe8b8950cf11700d691bd4369b8bb8aa12cf2/packages/ckeditor5-engine/src/view/domconverter.js#L978-L984). **This behavior is causing a serious issue: ckeditor/github-writer#181**.

Note that converting the above `emoji` model element to an inline `span` makes total sense, because `emoji` is marked with `isInline`.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I don't think that this is a correct scenario. An attribute element doesn't have an identity. It can be merged at any moment with surrounding attribute elements. Model element must be mapped to something in the view, so it must not be an attribute element. 

I confirmed my thoughts with @scofalik 

You're completely correct here:

> The problem with `createContainerElement` is that it enforces a series of rules that don't apply for an inline element (`span`)

But that doesn't mean that we should be using attribute elements instead. What we miss is a better support for inline view elements. We probably miss some type of element or configuration for container elements, but the solution is unlikely to be in attribute elements.

**Comment by Reinmar** [comment]
Could you report a new ticket describing what you're trying to achieve, so we can understand your needs?

**Comment by scofalik** [comment]
Also you incorrectly used the conversion helper. In `view` you aren't supposed to do the modifications, you only should return the view element that will be later further managed by the default converters.

**Comment by fredck** [comment]
> Could you report a new ticket describing what you're trying to achieve, so we can understand your needs?

Ofc ;) -> #6809

**Comment by fredck** [comment]
> I don't think that this is a correct scenario. An attribute element doesn't have an identity. It can be merged at any moment with surrounding attribute elements. Model element must be mapped to something in the view, so it must not be an attribute element.

Your explanation makes sense.

I was mislead with my assumptions based on the documentation:

*   The limited scope of AttributeElement is not clear in [its documentation page](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_attributeelement-AttributeElement.html).
*   The allowed positions are not described in [the DowncastWriter.insert() documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-insert).
*   The [createContainerElement() documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-createContainerElement) just shows block elements.

**Comment by Reinmar** [comment]
I opened #7447 for these docs issues :+1:
