### ISSUE TITLE
Reduce CI build count

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6811]
## Provide a description of the task

This is more of a discussion at this point rather than a real call to action.

Something that I observed a long time ago, and never had an answer what's the reason for this is that we run **two CI builds** for each Pull Request.

![](https://user-images.githubusercontent.com/5353898/81817246-ba01c800-952c-11ea-97ab-8f4d0c77b275.png)

I think we're good with just making a CI for each PR\*. Doing that would increase our building capacity by 100%.

 \* Making a CI run for each PR means running CI on creating PR or updating branch that is related with an existing PR.

**Comment by mlewand** [comment]
Also we should enable a setting that _aborts a running build_ if new changes were pushed to a given branch, and starts building for the latest hash in a given branch right of the bat.

**Comment by Reinmar** [comment]
> Also we should enable a setting that _aborts a running build_ if new changes were pushed to a given branch, and starts building for the latest hash in a given branch right of the bat.

:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Reinmar** [comment]
As for PR and push builds – I could never understand which is which. But I can see value in running both. One tells you whether your change will work when it's on master (which is super important) and the other verifies your change itself. I'd say that the former is more important, if we really need to optimize this.

**Comment by mlewand** [comment]
## Cancelling pending builds

I have enabled this optimization for our CIs.

I will note, however, that I remembered [one aspect of cancellation slightly incorrect](https://docs.travis-ci.com/user/customizing-the-build#building-only-the-latest-commit):

> If you are only interested in building the most recent commit on each branch you can use this new feature to automatically cancel older builds in the queue that are _**not yet running**_. Existing builds will be allowed to finish.

This means that the builds that were _already started_ will not be cancelled, but the pending will so it's still beneficial.

## CI runs for branches

> But I can see value in running both. One tells you whether your change will work when it's on master (which is super important) and the other verifies your change itself.

Agree that running on `master` is beneficial and mission critical.

That being said we [could whitelist `master` (and `stable`) branches](https://docs.travis-ci.com/user/customizing-the-build#building-specific-branches) to be the only branches that automatically trigger the build.

> I could never understand which is which

There are few indicators, for instance on GH you can see it in status section:

![](https://user-images.githubusercontent.com/5353898/81912121-75c70400-95ce-11ea-9bcf-25b76a1fe781.png)

On Travis itself there is different summary text:

![](https://user-images.githubusercontent.com/5353898/81912239-9abb7700-95ce-11ea-8c78-87f36573d1f4.png)

![](https://user-images.githubusercontent.com/5353898/81912391-ccccd900-95ce-11ea-939e-370d4fb171a3.png)

**Comment by jodator** [comment]
> Also we should enable a setting that _aborts a running build_ if new changes were pushed to a given branch, and starts building for the latest hash in a given branch right off the bat.

I thought that we have that already. I saw some builds to be :x: because other started.

**Comment by Reinmar** [comment]
> Cancelling pending builds

Done. 

However, we'll start building docs on CI which may bring back long queues. If that'll happen, let's kill "push" builds.

**Comment by mlewand** [comment]
For now we don't have too much problem with the CI (timings) so we're closing it. If it's going to be an problem this issue should be reopened in the future.
