### ISSUE TITLE
Introduce method to easily "clone" element with children to model writer.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6819]
## 📝 Provide a description of the new feature

In some copy/paste scenarios there's a need to copy elements along with its attributes and with children.

I'd propose a new method:

```javascript
writer.copyElement( element ); // Copies this element with its attributes.
writer.copyElement( element, { deep: true } ); // As above but with children.
```

That will create a shallow or deep copy of given element. The rationale behind object is that this might be later on enhanced and also simple true/false is hard to remember in code.

ps.: ATM we have private `Element._clone()` but this is not a good way of doing this.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
I think that cloneElement will be a better name - I'd guess people are more used to "cloning".

**Comment by Reinmar** [comment]
Agree – `cloneElement()` sounds more "common".

**Comment by jodator** [comment]
AFAIR it should also land on `model` isntance.
