### ISSUE TITLE
Toolbar items lack vertical spacing when wrapped to the next line

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5#682]
## 🐞 Is this a bug report or feature request?
- Bug report (CSS/design)

## 💻 Version of CKEditor

dev.alpha-2

## 📋 Steps to reproduce

1. Change the width of the editor to `240px` on https://ckeditor5.github.io/
2. Hover over the icon rows

## ✅ Expected result

Either a smaller dropdown height or more padding for the icons

## ❎ Actual result

the dropdown is super close to the icon focus / hover background

## 📃 Other details that might be useful

![icons](https://user-images.githubusercontent.com/128755/33047654-df47f57a-ce24-11e7-8a8b-0d1ec41b384d.gif)

**Comment by Reinmar** [comment]
We're in the middle of refactoring the theme to PostCSS, so let's better not touch this now. But I'm adding this to the milestone to not forget it.

**Comment by vladikoff** [comment]
Awesome thanks!  🎨
