### ISSUE TITLE
Image upload in ckeditor not working in edge broswer

### ISSUE THREAD

**Issue by ktechtest** [ckeditor/ckeditor5#6820]
Image upload in ckeditor not working in edge broswer, the choose file option missing in ckeditor

**Comment by Mgsy** [comment]
Hi, can you tell us more about your issue? Do you have properly configured an [upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html)? Does the browser console contain any error?

**Comment by ktechtest** [comment]
Hi , yes the upload image from ckeditor working well in chrome/firefox, i have issue with edge browser only. Edge version :  44.18362.449.0 and console error SCRIPT5007: Unable to get property 'specified' of undefined or null reference

**Comment by Mgsy** [comment]
Thanks for sharing details. Unfortunately, the Edge version you're using is the old one - at the beginning of this year Microsoft has released new Edge with an engine based on Chromium. Formerly, the "old" Edge was causing many problems in CKEditor 5 (you can check our closed issues with label `browser:edge`) and the latest version has brought the stability, so we won't work on issues related to the old one. All I can recommend is updating your browser or using Chrome/Firefox.
