### ISSUE TITLE
CI output shows wrong hint in case of bad code coverage

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6824]
## Provide a description of the task

There was a build recently that did not meet CC for the engine package: https://travis-ci.org/github/ckeditor/ckeditor5/builds/687052304

However the CI output has a hint at the end:

> The following packages did not pass unit tests: engine

Where it should say that CC is incorrect.

<details>
<summary>See the CI output dump in case someone restarts it</summary>
<pre><code>Worker information
0.13s0.00s0.01s0.00s0.00s
system_info
Build system information
0.01s0.00s0.68s0.17s0.05s0.00s0.04s0.00s0.01s0.01s0.01s0.01s0.01s0.00s0.00s0.02s0.00s0.01s0.22s0.00s0.00s0.00s0.01s0.00s0.09s0.00s0.73s0.00s0.07s6.03s0.00s2.40s0.00s2.17s
docker_mtu
resolvconf
services
3.02s$ sudo systemctl start xvfb
install_chrome
$ export CHROME_SOURCE_URL=https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
git.checkout
7.05s$ git clone --depth=50 --branch=master https://github.com/ckeditor/ckeditor5.git ckeditor/ckeditor5
0.01s
Setting environment variables from repository settings
$ export GITHUB_TOKEN=[secure]
Setting environment variables from .travis.yml
$ export SLACK_WEBHOOK_URL=[secure]
nvm.install
2.78s$ nvm install 10
cache.1
Setting up build cache
cache.npm
$ node --version
v10.20.1
$ npm --version
6.14.4
$ nvm --version
0.35.3
$ yarn --version
1.15.2
before_install.1
0.01s$ export START_TIME=$( date +%s )
before_install.2
1.90s$ npm i -g yarn
install
37.02s$ yarn install
626.66s$ node ./scripts/continuous-integration-script.js
pkg-adapter-ckfinder
Testing ckeditor5-adapter-ckfinder
pkg-alignment
Testing ckeditor5-alignment
pkg-autoformat
Testing ckeditor5-autoformat
pkg-autosave
Testing ckeditor5-autosave
pkg-basic-styles
Testing ckeditor5-basic-styles
pkg-block-quote
Testing ckeditor5-block-quote
pkg-build-balloon
Testing ckeditor5-build-balloon
pkg-build-balloon-block
Testing ckeditor5-build-balloon-block
pkg-build-classic
Testing ckeditor5-build-classic
pkg-build-decoupled-document
Testing ckeditor5-build-decoupled-document
pkg-build-inline
Testing ckeditor5-build-inline
pkg-ckfinder
Testing ckeditor5-ckfinder
pkg-clipboard
Testing ckeditor5-clipboard
pkg-cloud-services
Testing ckeditor5-cloud-services
pkg-code-block
Testing ckeditor5-code-block
pkg-core
Testing ckeditor5-core
pkg-easy-image
Testing ckeditor5-easy-image
pkg-editor-balloon
Testing ckeditor5-editor-balloon
pkg-editor-classic
Testing ckeditor5-editor-classic
pkg-editor-decoupled
Testing ckeditor5-editor-decoupled
pkg-editor-inline
Testing ckeditor5-editor-inline
pkg-engine
Testing ckeditor5-engine
52.51sChecking dependencies...
All dependencies are defined correctly.
yarn run v1.22.4
$ node --max_old_space_size=4096 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test.js -f engine --reporter=dots --production --coverage
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣:    1048 modules
ℹ ｢wdm｣: Compiled successfully.
14 05 2020 14:52:44.115:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
14 05 2020 14:52:44.117:INFO [launcher]: Launching browsers CHROME_TRAVIS_CI with concurrency unlimited
14 05 2020 14:52:44.121:INFO [launcher]: Starting browser Chrome
14 05 2020 14:52:44.814:INFO [Chrome 81.0.4044 (Linux 0.0.0)]: Connected on socket Q5kBvx7SgPC1gpRjAAAA with id 64897464
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
........................................................................
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
WARN: 'Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.'
Chrome 81.0.4044 (Linux 0.0.0): Executed 5352 of 5415 (skipped 6) SUCCESS (32.199 secs / 17.298 secs)
=============================== Coverage summary ===============================
Statements   : 99.67% ( 8262/8289 )
Branches     : 99.81% ( 5176/5186 )
Functions    : 99.33% ( 1633/1644 )
Lines        : 99.7% ( 8185/8210 )
================================================================================
Coverage report saved in '/home/travis/build/ckeditor/ckeditor5/coverage'.
Done in 46.02s.
(node:10693) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ERROR: Coverage for lines (99.7%) does not meet global threshold (100%)
ERROR: Coverage for functions (99.33%) does not meet global threshold (100%)
ERROR: Coverage for branches (99.81%) does not meet global threshold (100%)
ERROR: Coverage for statements (99.67%) does not meet global threshold (100%)
💥 engine doesn't have required code coverage 💥
pkg-enter
Testing ckeditor5-enter
pkg-essentials
Testing ckeditor5-essentials
pkg-font
Testing ckeditor5-font
pkg-heading
Testing ckeditor5-heading
pkg-highlight
Testing ckeditor5-highlight
pkg-horizontal-line
Testing ckeditor5-horizontal-line
pkg-image
Testing ckeditor5-image
pkg-indent
Testing ckeditor5-indent
pkg-link
Testing ckeditor5-link
pkg-list
Testing ckeditor5-list
pkg-markdown-gfm
Testing ckeditor5-markdown-gfm
pkg-media-embed
Testing ckeditor5-media-embed
pkg-mention
Testing ckeditor5-mention
pkg-page-break
Testing ckeditor5-page-break
pkg-paragraph
Testing ckeditor5-paragraph
pkg-paste-from-office
Testing ckeditor5-paste-from-office
pkg-remove-format
Testing ckeditor5-remove-format
pkg-restricted-editing
Testing ckeditor5-restricted-editing
pkg-select-all
Testing ckeditor5-select-all
pkg-special-characters
Testing ckeditor5-special-characters
pkg-table
Testing ckeditor5-table
pkg-theme-lark
Testing ckeditor5-theme-lark
pkg-typing
Testing ckeditor5-typing
pkg-ui
Testing ckeditor5-ui
pkg-undo
Testing ckeditor5-undo
pkg-upload
Testing ckeditor5-upload
pkg-utils
Testing ckeditor5-utils
pkg-watchdog
Testing ckeditor5-watchdog
pkg-widget
Testing ckeditor5-widget
pkg-word-count
Testing ckeditor5-word-count
pkg-cloud-services-core
Testing ckeditor-cloud-services-core
Uploading combined code coverage report…
Done
---
The following packages did not pass unit tests: engine
The command "node ./scripts/continuous-integration-script.js" exited with 1.
45.03s$ yarn run lint
yarn run v1.22.4
$ eslint --quiet '**/*.js'
Done in 44.85s.
The command "yarn run lint" exited with 0.
1.78s$ yarn run stylelint
yarn run v1.22.4
$ stylelint --quiet --allow-empty-input 'packages/**/*.css' 'external/*/packages/**/*.css' 'docs/**/*.css'
Done in 1.60s.
The command "yarn run stylelint" exited with 0.
30.41s$ yarn run docs:api --validate-only
yarn run v1.22.4
$ node ./scripts/docs/build-api-docs.js --validate-only
JSDoc started...
No errors found during the validation.
Documented 568 files!
Done in 30.23s.
The command "yarn run docs:api --validate-only" exited with 0.
0.00s$ if [ $TRAVIS_TEST_RESULT -eq 0 ]; then travis_wait 30 yarn run docs:build-and-publish-nightly; fi
The command "if [ $TRAVIS_TEST_RESULT -eq 0 ]; then travis_wait 30 yarn run docs:build-and-publish-nightly; fi" exited with 0.
cache.2
store build cache
after_script.1
0.00s$ export END_TIME=$( date +%s )
after_script.2
0.39s$ ckeditor5-dev-tests-notify-travis-status
Done. Your build exited with 1.</code></pre>
</details>

**Comment by Reinmar** [comment]
The error is correct. The tests didn't pass because there's a WARN on the console and we made warnings throw errors.
