### ISSUE TITLE
Table, Link, Image plugins overwrite/strip off existing style attribute

### ISSUE THREAD

**Issue by scazzy** [ckeditor/ckeditor5#6827]
## 📝 Provide detailed reproduction steps (if any)
Purpose is to retain all styles that exists in the html being sent to the editor.
Having Table, Link, Image etc plugins seem to be stripping off the style and over writing it's own. For example, Table having thick borders, Link being blue, etc.

Wrote a converter to retain the existing style on top of the plugin's style attributes but nothing seems to work.
```
// editor.model.schema[extend/register](...)
editor.conversion.attributeToAttribute( { model: 'style', view: 'style' } );
editor.conversion.for('upcast').attributeToAttribute({
  model: {
    key: '__style',
    name: 'style'
  },
  view: 'style'
});

editor.conversion.for('downcast').add(dispatcher => {
  dispatcher.on(`attribute:__style:style`, (evt, data, conversionApi) => {
    conversionApi.consumable.consume(data.item, evt.name);

    const viewElement = conversionApi.mapper.toViewElement(data.item);

    conversionApi.writer.setAttribute('style', data.attributeNewValue, viewElement);
  });
});
```
### ✔️ Expected result

[] Existing styles to be retained

### ❌ Actual result

[] Existing/custom styles are being stripped off
[] Plugin's are overwriting their styles if they have any

## 📃 Other details

* Browser: All
* OS: MacOS
* CKEditor version: 19.0.0
* Installed CKEditor plugins: Essentials, Autoformat, Bold, Italic, BlockQuote, CKFinder, EasyImage, Heading, Image, ImageCaption, ImageStyle, ImageToolbar, ImageUpload, Indent, Link, List, MediaEmbed, Paragraph, PasteFromOffice, Table, TableToolbar, TextTransformation,

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, did you see our [Preserving custom content guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html)?

**Comment by dufipl** [comment]
Closing due to lack of feedback.
