### ISSUE TITLE
Accents on letters for track changes sometimes fails

### ISSUE THREAD

**Issue by ericksod** [ckeditor/ckeditor5#6833]
## 📝 Provide detailed reproduction steps (if any)
This seems a bit similar to https://github.com/ckeditor/ckeditor5/issues/3124, but not sure if it is related. 
1. Type individual letters with accents within the boundaries of non-tracked existing text  (eg. é, ô, ã, ü)
2. Type words with accents or individual letters outside the boundaries of existing text (eg. fiancé, sótão, tênis)

### ✔️ Expected result
Any time accents are typed, they should display on top of the letter.

### ❌ Actual result

Done using [track changes example](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html)
<img width="333" alt="Screen Shot 2020-05-15 at 12 12 52 PM" src="https://user-images.githubusercontent.com/8618241/82073763-b0509f80-96a7-11ea-87ad-98626cb05ca9.png">

## 📃 Other details

* Browser: Chrome Version 81.0.4044.138
* OS: Mac OS Sierra 10.12.6
* CKEditor version: Done in example for ckeditor 5 for track changes
* Installed CKEditor plugins:

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report, I can reproduce this bug. I've transfered this report to our private issue tracker, as Track Changes is a commercial plugin and this repository is for an open-source part of the project. We'll investigate and triage it soon.

Also, for your further reports and questions about Track Changes, please use our [support channel](https://ckeditor.com/contact/), so our team will be able to answer more efficiently.
