### ISSUE TITLE
Get the mouse-selected text in the CKeditor5 editor and replace it

### ISSUE THREAD

**Issue by luoxianqin** [ckeditor/ckeditor5#6835]
## 📝 Provide a description of the new feature

In CKeditor4, there is the function of obtaining text selection and replacing the selected text. I can realize the simple and complex conversion of Chinese through this function, but it is not available in CKeditor5. I think it is very good

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! If you'd like to replace the selected text, you'll need to simply [get a range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html#function-getFirstRange) and [insert the text](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent) at the given position. Please, see the example below:

```javascript
editor.model.change( writer => {
    const range = editor.model.document.selection.getFirstRange();

    editor.model.insertContent( writer.createText( 'Text to insert' ), range )
} );
```

**Comment by luoxianqin** [comment]
Thank you very much.This helped me a lot, but I found that replacing the text in this way clears out the original style, which I didn't clearly describe in the problem description




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kacper Tomporowski"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 下午5:06
收件人:&nbsp;"ckeditor/ckeditor5"<ckeditor5@noreply.github.com&gt;;
抄送:&nbsp;"sailoo"<728332278@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ckeditor/ckeditor5] Get the mouse-selected text in the CKeditor5 editor and replace it (#6835)





 
Hi! If you'd like to replace the selected text, you'll need to simply get a range and insert the text at the given position. Please, see the example below:
 editor.model.change( writer =&gt; {     const range = editor.model.document.selection.getFirstRange();     editor.model.insertContent( writer.createText( 'Text to insert' ), range ) } );

**Comment by Mgsy** [comment]
You can pass attributes while creating a text node, see:

```javascript
writer.createText( 'Text to insert', { bold: true, italic: true } );
```

**Comment by devraj112** [comment]
For not replacing the selected text, what method we can use?

**Comment by Witoso** [comment]
@devraj112 please describe your scenario in more details.

**Comment by devraj112** [comment]
> Hi! If you'd like to replace the selected text, you'll need to simply [get a range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html#function-getFirstRange) and [insert the text](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent) at the given position. Please, see the example below:
> 
> ```js
> editor.model.change( writer => {
>     const range = editor.model.document.selection.getFirstRange();
> 
>     editor.model.insertContent( writer.createText( 'Text to insert' ), range )
> } );
> ```

This insertContent() method will remove the selected content. I want to know, is there a way with which we can keep the selected content also and be able to insert our structure. Like for example, in case of Abbreviation plugin example 
` _createFormView() {
        const editor = this.editor;
        const formView = new FormView( editor.locale );

        this.listenTo( formView, 'submit', () => {
            const title = formView.titleInputView.fieldView.element.value;
            const abbr = formView.abbrInputView.fieldView.element.value;

            editor.model.change( writer => {
                editor.model.insertContent(
                    writer.createText( abbr, { abbreviation: title } )
                );
            } );

        } );

        return formView;
    }`

Here, for not selected content means wherever our cursor is it will work fine, but, if we have a selection it will remove that selected content and insert the input text of abbreviation and title. I want to know, is there a way around to keep that selected content and insert the desired structure beside the selected content?

**Comment by crest-daksh** [comment]
@Mgsy I want to get the selected text , how can  I get that . I want to get the selected text on right click on mouse , how can I get that ? please help me if you have any idea ?
