### ISSUE TITLE
Update GIF in the "Git commit message convention" guide

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6837]
## 📝 Provide a description of requested docs changes

Since we changed the message convention recently, the following gif should also be updated:

![Screencast how to copy a source version of the suggested commit message when closing a PR.](https://ckeditor.com/docs/ckeditor5/latest/assets/img/closing-a-pr.gif)

(it should contain a `Feature(**<module>**):` prefix.

The guide is here: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html

**Comment by AnnaTomanek** [comment]
Note: When recording the GIF, remember to disable the ZenHub addon so that only GitHub actions were visible.
