### ISSUE TITLE
i have a confuse，when i want to development a plugin

### ISSUE THREAD

**Issue by Dolov** [ckeditor/ckeditor5#6840]
hello , i have a confuse about use plugin in react

I have a demand have to development a plugin, but i found it must clone the ckeditor5 depository and build it, i want to know is it necessary，thanks for you

**Comment by Mgsy** [comment]
Hi! Adding plugins to the editor requires creating custom builds. However, if you're using React, I suggest you [building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source), so you can write your plugin code in a single file (`src/App.js` from the example).

Here you can find some materials which might be useful for you:

*   [Adding plugins to a build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build)
*   [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)

**Comment by Dolov** [comment]
Is "creating custom builds"  means that i need clone source code and build it ?
is "building the editor from source"  means "@ckeditor/ckeditor5-editor-*"
thanks

**Comment by Mgsy** [comment]
> Is "creating custom builds" means that i need clone source code and build it ?

You can customize an existing build (e.g. `ckeditor5-build-classic`) and cloning the repository will be required. 

> is "building the editor from source" means "@ckeditor/ckeditor5-editor-\*"

Yes, if you build the editor from the source, you use the editor class, not a build (e.g. `ckeditor5-editor-classic`).

Please, take a look at links I've posted in my previous message - you'll find there answers for all your questions with step-by-step guides.

**Comment by Dolov** [comment]
Thank you for your patience，ckeditor is great , I'll check the documents again @Mgsy

**Comment by Mgsy** [comment]
Great to hear that you like CKEditor 5 :) I'll close this issue as solved, however, if you'll have some further questions, feel free to ask.

**Comment by Dolov** [comment]
hello, i have another question trouble you, i want to custom file upload url, but  i not find the api, ckeditor4 has "onFileUploadRequest" and "onFileUploadResponse", i not find in ckeditor5  @Mgsy

**Comment by Mgsy** [comment]
> hello, i have another question trouble you, i want to custom file upload url, but i not find the api

It sounds like a use case for our [Simple upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html). However, if it doesn't fit your needs, you can try to create your own [custom upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html).

**Comment by Dolov** [comment]
haha i find it !!!  tks @Mgsy

**Comment by Dolov** [comment]
another one...
i use simpleUpload and set uploadUrl, but i not find the way to set request params

**Comment by Mgsy** [comment]
While using `SimpleUploadAdapter`, you can use [`headers`](https://ckeditor.com/docs/ckeditor5/latest/api/module_upload_adapters_simpleuploadadapter-SimpleUploadConfig.html#member-headers) configuration option for defining request headers.
