### ISSUE TITLE
Can not keep type after insert an image.

### ISSUE THREAD

**Issue by FPG-Alan** [ckeditor/ckeditor5#685]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

ckeditor5-build-classic  1.0.0-alpha.2

## 📋 Steps to reproduce

1.Open [CKeditor5 Classic editor](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html)
2.Drag an image and insert it to the end of CKeditor.

## ✅ Expected result
Should can keep type below this image.

## ❎ Actual result
Can not keep type below this image.

## 📃 Other details that might be useful
<img width="724" alt="screen shot 2017-11-22 at 4 00 22 pm" src="https://user-images.githubusercontent.com/5809641/33116237-00bd972a-cf9f-11e7-8b0a-5cfd5e11a4ae.png">

**Comment by Reinmar** [comment]
Thanks for the report. It's a dup of https://github.com/ckeditor/ckeditor5/issues/407.
