### ISSUE TITLE
Add 'Commercial support' section in the CKEditor 5 docs

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/ckeditor5#695]
I just spotted that we're only mentioning the community support on https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/getting-support.html

What about licenses and paid support?

**Comment by wwalc** [comment]
Pull requests are more than welcome ;)

**Comment by wojtekidd** [comment]
☝️ 
![](https://media2.giphy.com/media/d2Z0bXYnj4Ma5VxC/giphy.gif)
