### ISSUE TITLE
HtmlEncodeOutput Doesn't Seems to Work

### ISSUE THREAD

**Issue by azazlhr** [ckeditor/ckeditor5#698]
- Bug report

## 💻 Version of CKEditor

ckeditor5 v1.0.0-alpha.2

## 📋 Steps to reproduce

1. Set htmlEncodeOutput to True in create method
2. Call getData() method

## ✅ Expected result
getData() method should return encoded string.
## ❎ Actual result
getData() method does not return encoded string.

SO post:
https://stackoverflow.com/questions/47555667/ckeditor-5-htmlencodeoutput-doesnt-work

**Comment by jodator** [comment]
Hi, I've posted an answer on SO: https://stackoverflow.com/questions/47555667/ckeditor-5-htmlencodeoutput-doesnt-work.

Basically we do not have such option in CKEditor 5 as it was in CKEditor 4.

**Comment by Reinmar** [comment]
I'd like to ask why would you like to use this option? What kind of use case does it solve? Maybe we'd be able to find some solution.

**Comment by azazlhr** [comment]
Here is the [post](http://r2d2.cc/2011/05/26/ckeditor-a-potentially-dangerous-request-form-value-was-detected-from-the-client/) that explains the problem and its solution in ASP.NET application but using CKEditor4.

**Comment by Reinmar** [comment]
This seems to be a problem with ASP.NET itself. Isn't there a reliable way to configure ASP.NET to allow HTML for this specific POST field? Workarounding this by obfuscating the input is not the cleanest solution. So, unless we'll see that this is commonly requested by the community and that there are no other good solutions, we are not going to implement such an option.

PS. If you want to go with obfuscation, then you can still do it yourself. Just pass the return value of `editor.getData()` through a function like [this one](https://github.com/ckeditor/ckeditor-dev/blob/45cf8e0e8a60ec547f8850d1a91594e6cf9bf98a/core/tools.js#L371-L379). This is what CKEditor 4 does.

**Comment by yuskie** [comment]
I see this being useful for handling special characters. I'm not sure if there's a better way. Currently I'm using he to encode the text and keep the tags before sending the JSON to the server. The issue with my approach is that I'll need to decode it twice to get a presentable HTML with the special characters.

**Comment by yuskie** [comment]
Spring's @requestbody can't seem to convert the check mark from the word example to a proper value. The quotes also cause an issue with the JSON parsing.
