### ISSUE TITLE
[Docs] Add section about CKFinder to the Upload image guide

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#699]
It's missing here completely: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/image-upload.html

And we may also need to improve https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_adapter-ckfinder_uploadadapter-CKFinderUploadAdapter.html and https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/adapter-ckfinder.html.

**Comment by Reinmar** [comment]
Let's make it a DUP of https://github.com/ckeditor/ckeditor5/issues/618.

**Comment by kaisanjay** [comment]
Image upload guide is not as descriptive as it should be.
as a beginner its a very hectic work for figure out what's going on.

**Comment by ma2ciek** [comment]
Hi, @kaisanjay.

This issue is marked as duplicate.

Please vote in https://github.com/ckeditor/ckeditor5/issues/618.

**Comment by hsbakhtiari** [comment]
> 
> 
> Image upload guide is not as descriptive as it should be.
> as a beginner its a very hectic work for figure out what's going on.

it's not about being beginner, it's not document at all. I think it's because of easy Image feature.
seems ckeditor team want we use easy image instead!!

**Comment by ma2ciek** [comment]
Sorry to hear that @hsbakhtiari.

We'll improve these guides it in the near future.
