### ISSUE TITLE
package.json should be indented with tabs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7]

**Comment by fredck** [comment]
The current formatting is on purpose.

The point is that `npm install whatever --save-dev` reformats package.json. It will be a pain in the *** to have to always reformat the code to our standards.

So, IMHO, for package.json, we should keep the `npm install` standards.

**Comment by Reinmar** [comment]
://////////////////////

Heh... ok.

**Comment by Reinmar** [comment]
Actually, I'd prefer avoiding using `npm install --save-dev`, but I guess that no one will support me ;).

**Comment by fredck** [comment]
> Actually, I'd prefer avoiding using npm install --save-dev, but I guess that no one will support me ;).

-1 straight :) especially because of version numbers but also because we must be ok with such so common practices.
