### ISSUE TITLE
Should we set eslint root: true for ckeditor5 repos?

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#7019]
`"root": true`
> By default, ESLint will look for configuration files in all parent folders up to the root directory. This can be useful if you want all of your projects to follow a certain convention, but can sometimes lead to unexpected results. To limit ESLint to a specific project, place "root": true inside the eslintConfig field of the package.json file or in the .eslintrc.* file at your project’s root level. ESLint will stop looking in parent folders once it finds a configuration with "root": true.

**Comment by pomek** [comment]
After switching to the monorepo, we have only one file `.eslintrc.js` for the entire repository.
