### ISSUE TITLE
[FF] Shift + tab doesn't work in nested editable

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#703]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
Put the caret inside the image caption.
Press <kbd>Shift</kbd>+<kbd>Tab</kbd>

## ✅ Expected result

Caret should go to the first line of the editor.

## ❎ Actual result

Nothing happens.

## 📃 Other details that might be useful

Browser: Firefox 57 (Quantum).
Related: https://github.com/ckeditor/ckeditor5/issues/676

**Comment by Reinmar** [comment]
It's not defined that tab/shift+tab should cycle through contentEditable elements. Whatever happens now is "ok" since it's native behaviour for now.

**Comment by ma2ciek** [comment]
Now, the focus is locked in the caption. It's not a native behavior, focus should go somewhere else after <kbd>Shift</kbd>+<kbd>Tab</kbd>

**Comment by f1ames** [comment]
I have noticed that <kbd>Shift</kbd>+<kbd>Tab</kbd> is locked only in the first image caption. If you have two images you can switch between captions with <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd>. However, using <kbd>Shift</kbd>+<kbd>Tab</kbd> in the first image caption in the editor has no effect.

**Comment by Reinmar** [comment]
Invalid. See https://github.com/ckeditor/ckeditor5/issues/1709.
