### ISSUE TITLE
Changelog tool suggest a wrong version for a package in v0.0.2

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7088]
![image](https://user-images.githubusercontent.com/156149/37458540-9a243294-2845-11e8-9d3c-b01c2ec0aaa9.png)

It suggested `v0.0.2-0`. I'd expect `v0.0.3` or `v0.1.0`.

**Comment by pomek** [comment]
The issue will not occur anymore because all of our packages are in the stable version (a major is not equal to 0). 

Also, according to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/versioning-policy.html, the major version of our packages will be always the same.
