### ISSUE TITLE
gulp lint-staged does not exclude src/lib/**

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#71]
I tried to rebuild lodash and I cannot commit it.

**Comment by szymonkups** [comment]
I did some quick research and it looks like it could be an issue connected with `git-guppy` package. I've reported issue here: https://github.com/therealklanni/git-guppy/issues/45 and will wait for the response.

**Comment by szymonkups** [comment]
I've created PR fixing this issue for `git-guppy` project. It was incorporated and published today in `1.1.0` version. 
Created two pull requests one to resolve this issue, second to update `ckeditor5-core` repository.

**Comment by Reinmar** [comment]
Fixed by #73.
