### ISSUE TITLE
Add `--use-mgit` switch fot `ckeditor5-dev-tests`.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7138]
Dunno if small addition but looks handy: Run tests for packages that are other then `master` in `mgit.json`, ie by integrating with `mgit st`.

It could be handy for reviews and own development.

Usage:

```sh
yarn test --cws --use-mgit
```
instead of:
```sh
yarn test -cws --files=editor-*,ui,core,engine,image,link,ui,utils,widget
```

Note that I've used `editor-*` shortcut here as I also wanted to test all `editor-*` packages and I was writing them by hand previously.

Edit: This is my `mgit st` output:
![selection_156](https://user-images.githubusercontent.com/247363/51256422-aa5c8880-19a5-11e9-9ae9-ede9851b221d.png)

**Comment by pomek** [comment]
After merging to the monorepo, we removed Mr.Git from the project. The issue is no longer valid.
