### ISSUE TITLE
The changelog generator should parse multiple type comments from merge commit.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7171]
The general rule of a thumb is that a merge should only introduce one change (atomic, precise, other blah, blah) but there are times that this would be useful.

Allow us to create merge commits like this:

```md
Feature: Introduce a Foo.foo feature. Closes #11123.
Fix: Fixes Bar braking baz. Closes #11111.
```

ATM only multiple `BREAKING CHANGE:` are parsed (if I get this correctly).

**Comment by pomek** [comment]
After merging https://github.com/ckeditor/ckeditor5-dev/pull/640, multi-messages in a single commit will be supported.

**Comment by pomek** [comment]
Introduced in https://github.com/ckeditor/ckeditor5-dev/pull/640.
