### ISSUE TITLE
[Chrome, Edge] Exception after pressing CTRL + U while content is selected

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#718]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

**Scenario 1**
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Select the image caption.
3. Press <kbd>Ctrl</kbd> + <kbd>U</kbd> (it's still <kbd>Ctrl</kbd> in MacOS).

**Scenario 2**
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Select two list items.
3. Press <kbd>Ctrl</kbd> + <kbd>U</kbd> (it's still <kbd>Ctrl</kbd> in MacOS).

## ✅ Expected result

Nothing happens.

## ❎ Actual result

There is the error in the console and in Chrome the selection has moved to the beginning of the document.

## 📃 Other details that might be useful

**Error**
```
input.js:205 Uncaught TypeError: modelFromCurrentDom.getChildren is not a function
    at MutationHandler._handleContainerChildrenMutations (input.js:205)
    at MutationHandler.handle (input.js:147)
    at Input._handleMutations (input.js:105)
    at Document.listenTo (input.js:50)
    at Document.fire (emittermixin.js:269)
    at MutationObserver._onMutations (mutationobserver.js:248)
```

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/33943967-f401a986-e01a-11e7-81e9-5bcd712216a3.gif)

**Notes**

It doesn't occur if the `underline` plugin is loaded.

**Other information**

OS: Windows 10, MacOS X
Browser: Chrome, Edge

**Comment by Reinmar** [comment]
This is a good one. I guess that a native underline comes into action and breaks our mutation observer.

**Comment by scofalik** [comment]
I wonder what's up, cause I can't reproduce it, while @Mgsy says that it is fixed for caption but still crashes for list items.

**Comment by scofalik** [comment]
Although, when I click <kbd>Cmd + U</kbd>, I don't get an underline, instead I get this sign: ¨ and composition starts (I guess) and this crashes when there is a multielement selection.

**Comment by Reinmar** [comment]
BTW, on my MacOS at least, with Polish Pro keyboard the keystroke which is worth testing is Alt+U.

Pressing Alt+U enters umlaut composition. So Alt+U,U inserts "ü". This works fine on Firefox and Chrome in some cases now, but crashes on the two-lists-item-selection. After #140 it simply stops crashing in e.g. two-lists-item-selection case, but it will do nothing. Which is fine for now. Let's see if anyone will ever report it.

**Comment by scofalik** [comment]
Did you check if other keystrokes (Cmd+U, Ctrl+U) crash the editor?

**Comment by Reinmar** [comment]
I tried all combinations with U.
