### ISSUE TITLE
Can't remove the inline style when the selection starts at the image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#719]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Start the selection at the end of the `OL List item 2`.
3. Drag it through the image and to other block elements.
4. Add some inline style.
5. Try to remove this style.

## ✅ Expected result

Style has been removed properly.

## ❎ Actual result

After step 4, style icon hasn't become active and there is no possibility to remove the style with current selection.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/33987211-65984fdc-e0c0-11e7-8de1-163612a9c47c.gif)

**Other information**
OS: Windows 10, MacOS X
Browsers: All browsers

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-basic-styles/issues/56.
