### ISSUE TITLE
Special initial changelog entry for each new package

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7191]
When we publish a new package it always gets a changelog in this format:

```
## [10.0.0](https://github.com/ckeditor/ckeditor5-mention/tree/v10.0.0) (2019-04-10)

The initial release.
```
Currently the initial package is treated as anything else, so it gets regular changelog lines and needs to be corrected manually.

Nothing critical, but would be lovely to have this.

**Comment by pomek** [comment]
After merging https://github.com/ckeditor/ckeditor5-dev/pull/640, we will have a single changelog for all packages in the main repository. There will be a dedicated section for "New packages".
