### ISSUE TITLE
Check whether we cannot adopt new yarn's release workflow

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7197]
See [https://next.yarnpkg.com/features/release-workflow](https://next.yarnpkg.com/features/release-workflow)

Sounds like something we're doing now. We've got different strategies for ckeditor5-dev and ckeditor5 itself, but at least in ckeditor5-dev there should be something we could improve.

**Comment by pomek** [comment]
After merging https://github.com/ckeditor/ckeditor5-dev/pull/640, we do not use Lerna and we switched to yarn workspaces as `ckeditor5` repository.
