### ISSUE TITLE
Make builder to work in sub-repos

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#72]
As discussed it would be beneficial to run builder in each repo to build it as in ckeditor5 repository.
This is useful for CI servers integration.

**Comment by Reinmar** [comment]
Related discussion ckeditor/ckeditor5-design#112 and #74.

**Comment by Reinmar** [comment]
@jodator has researched how we could setup CI server and turns out that we'll want to avoid such complications. Relevant discussion in: https://github.com/ckeditor/ckeditor5-design/issues/45#issuecomment-176834943
