### ISSUE TITLE
Updating blog post links in GitHub releases

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7200]
I just noticed we never updated blog post links in our [GH releases](https://github.com/ckeditor/ckeditor5/releases) 🙈

Currently we'd need to have a tool for this, but once we switch to monorepo, it won't be that much of a work so we could just agree on doing this manually. In which case we should close this and open a follow-up in the knowledge base repo to update release instructions.

**Comment by Reinmar** [comment]
Let's do this manually ;)
