### ISSUE TITLE
Tests: istanbul-instrumenter-loader not found

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#7201]
The tests app [injects the istanbul-instrumenter-loader package as a loader in the webpack config](https://github.com/ckeditor/ckeditor5-dev/blob/712ef150b1220e78866c77ee84e4d132ad13b685/packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js#L78). Because of this, an error is thrown when running tests in an application that depends on `@ckeditor/ckeditor5-dev-tests` only and uses `yarn`.

To illustrate this, let me show a theoretical directory structure of the app after a yarn install:

```plaintext
/node_modules
	/...   <-- here we have the packages available to the application
	/@ckeditor
		/ckeditor5-dev-tests
			/node_modules
				istanbul-instrumenter-loader   <-- here we have the loader
```

As we can see, yarn install `istanbul-instrumenter-loader` at the `ckeditor5-ev-tests` scope, because it looks like being the only package that depends on it. But in reality, the test runner runs at the application scope and, because webpack tries to load `istanbul-instrumenter-loader`, it can't be found.

To solve the problem, it is necessary to add `istanbul-instrumenter-loader` as a direct dependency of the application itself:

```plaintext
yarn add --dev istanbul-instrumenter-loader
```

Although this is not optimal, it is acceptable. **The problem is that this is not documented anywhere** and required a lot of research to figure it out, so I believe that the `ckeditor5-dev-tests` readme should point out that `istanbul-instrumenter-loader` must be added as a dev dependency as well.

**Comment by Reinmar** [comment]
I still don't get this. yarn always installs deps in a flat way. So if you have a nested `node_modules` either you encountered a bug in yarn or you're doing something in a non-standard, non-safe way.

That's now it's installed for me:

![](https://user-images.githubusercontent.com/156149/85987022-5f91cd80-b9ed-11ea-96ea-408a3479991a.png)

And I assume it's the same for everyone else in the team as no one raised this problem to my knowledge.

Anyway, you mentioned what's the workaround for you and this ticket is googleable, so if anyone else will have this problem, they should be able to land here.

**Comment by fredck** [comment]
I've just stumbled in this problem again, this time with a plugin for Karma: "karma-webpack".

I've upgraded ckeditor5-dev-tests from v22.0.0 to v23.1.1. After running `yarn`, test running stopped working with the following error: `ERROR [preprocess]: Can not load "webpack", it is not registered!`. 

It took me some time to figure what was going on, but the previous experience with the instanbul plugins made me intuitively find the problem. Here again, we have a tool expecting to find a plugin as a project dependency, while we're counting on yarn bringing all ckeditor5-dev-tests dependencies to the project root... but it doesn't.

> I still don't get this. yarn always installs deps in a flat way.

This seems to be a wrong assumption. It's more like "flatty" than "flat", really.

Here is what I have:

![](https://user-images.githubusercontent.com/630060/89901825-f4d7d280-dbe5-11ea-9577-f30edb3b26ae.png)

I use yarn packages.

As we can see, yarn is leaving a lot of stuff inside the package node\_modules instead of putting them in the root. It's hard to say how it decides where to put what, though, because many other dependencies are in the project root instead.

So, the only thing we can assume is that "we don't know", so we can't make assumptions.

I was wondering if it is not the "really right" way for it if plugins for third-party software that assume things are available in the project root would be set as "peerDependencies". It would be a bit of a PITA though for integrators because they would have to add all such dependencies in their project, but anyway it would be guaranteed to work.

Or maybe there is a way for ckeditor5-dev-tests to ensure that its dependencies (or selected ones at least) must be always installed in the project root.

I think it is worth at least trying to figure something out because, as we can see, this is a recurring issue.

**Comment by fredck** [comment]
So... yarn has its own issues, ofc.

It was enough to delete yarn.lock and re-run yarn and things got in place.

This is so damn unreliable, though :/

**Comment by Dumluregn** [comment]
I have encountered this issue as well while reviewing https://github.com/ckeditor/github-writer/pull/274. We decided to add the `istanbul-instrumenter-loader` to the `package.json`. Removing `yarn.lock` and reinstalling didn't help me. I don't reopen the issue as adding the devDependency means it should not bother anyone in the future.
