### ISSUE TITLE
Review and upgrade dependencies

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7202]
*   Review packages that we use (especially in dev-tests which seems to have many legacy things).
*   Remove things that we don't need.
*   Upgrade all other packages to their newest versions.

Note: Since we will be reworking dev-env soon, I guess we can skip it for now.

**Comment by pomek** [comment]
I've just reviewed all packages and their packages.json.

The updated packages have been pushed to the branch [i/7202-upgrade-deps](https://github.com/ckeditor/ckeditor5-dev/compare/i/7202-upgrade-deps) in `ckeditor5-dev` repository.

Unfortunately, the upgrade requires bumping the Node's version. https://github.com/ckeditor/ckeditor5/issues/7258

**Comment by Reinmar** [comment]
When upgrading dependencies let's also upgrade Node version (#7258).

Packages/repos to review:

* ckeditor5,
* ckeditor5-dev

**Comment by pomek** [comment]
Both ([v5](https://github.com/ckeditor/ckeditor5/commit/91cffa8e9cbcee6e7ad57e829e5de6275f06aaa8), [dev](https://github.com/ckeditor/ckeditor5-dev/commit/f771fb0221db07f802bbdf0da1450fe5d79314c9)) PRs are merged so I'm closing as resolved.
