### ISSUE TITLE
Lerna publish doesn't allow you to skip packages

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7216]
I just had a release, where the only difference compared to last release was in `ckeditor5-dev-utils`. I skipped all other packages during the `yarn run changelog` step, yet when running `lerna publish` it listed all the packages that were skipped + there was no option to skip them.

So I had to patch bump each package.

**Comment by pomek** [comment]
After merging https://github.com/ckeditor/ckeditor5-dev/pull/640, we do not use Lerna anymore.
