### ISSUE TITLE
How to get CKeditor content html with inline css??

### ISSUE THREAD

**Issue by SaraMob** [ckeditor/ckeditor5#7232]
In ckeditor5-react , i'm using the html content form ckeditor component ,
but i get html with external css class  Ex: " <span class="text-huge">" and i need it to be Ex: " <span style=" font-size: 1.8em">" 
how can i do that with ckeditor5-react, or how to get the css of content to use it later?

**Comment by Mgsy** [comment]
Hi, thanks for the report. Getting data with inline styles is not supported. However, we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1627) for it, so feel free to add :+1: to the first post and join the discussion to bump its popularity.

**Comment by SaraMob** [comment]
OK , is there a way to extract the css of the ckeditor written content ?

**Comment by Mgsy** [comment]
[Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#the-full-list-of-content-styles) you can find the full list of styles used by CKEditor 5.

**Comment by SaraMob** [comment]
The full list of styles used by CKEditor 5 , isn't full , it doesn't have all the css styles , 
ex : <span class="text-huge">huge</span> ,  and in the full css styles there's no css for "class="text-huge""

**Comment by Mgsy** [comment]
If you'd like to get every styled produced by CKEditor 5 features, you can generate all the styles using `yarn docs:content-styles` in the development environment. See the guide [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html#generating-content-styles).

**Comment by SaraMob** [comment]
Ok , thanks :D

**Comment by OWS-thinhpv** [comment]
i need inline style css because im working with Gmail not suport style class , please update version with inline css
