### ISSUE TITLE
Making the inline placeholder widget editable

### ISSUE THREAD

**Issue by nfplee** [ckeditor/ckeditor5#7233]
Hi, Would anyone be able to help with the following issue https://stackoverflow.com/questions/61715050/making-the-ckeditor-5-inline-placeholder-widget-editable?

I opened a bounty (which expires tomorrow) but I still have not received any interest. I'm sure it's a trivual answer to someone who understands the API.

**Comment by Mgsy** [comment]
Hi, thanks for the report. Unfortunately, editable inline widgets are not supported in CKEditor 5. We have an [opened feature request](https://github.com/ckeditor/ckeditor5/issues/1729) for it, so check it out for more details and feel free to add :+1: to the first post to bump its popularity.

**Comment by nfplee** [comment]
Thanks for the quick response. I completely missed that issue..
