### ISSUE TITLE
Want ckeditor5 contents same as WYSIWYG editor used for Mailing content

### ISSUE THREAD

**Issue by ArunPandianB** [ckeditor/ckeditor5#7238]
Hi All,

In ckeditor5 document editor styles are included as style sheet file, its get included and rendered in angular8 component. When we send that html to a mail (Gmail or Outlook), those style are not included in the html contents. So we don’t get any styles in the received mail.
             
In mail, they are removing the class names from the html elements, but retains the some styles because the contents of ckeditor is not a normal tags.

I am unable to get the exact view in mail. Kindly help me out how I can **include all the html elements** and styles or **convert those structured tags** from ckeditor5.

For Reference attached the images:
**In CKeditor5:**
![email](https://user-images.githubusercontent.com/27341694/82352898-4a07ac00-9a1c-11ea-8c8b-1079f63d6ef1.jpg)

**In Gmail:**
![ema](https://user-images.githubusercontent.com/27341694/82352963-61df3000-9a1c-11ea-9935-bc23a397ae0b.jpg)

Thanks in Advance!

**Comment by Mgsy** [comment]
Hi! Converting class styles to inline styles isn't supported in CKEditor 5. We have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1627) for it, so feel free to add :+1: to the first post and join the discussion to bump its popularity.
