### ISSUE TITLE
Cancelling comments freezes Safari users

### ISSUE THREAD

**Issue by forevergareth** [ckeditor/ckeditor5#7239]
## 📝 Provide detailed reproduction steps (if any)

1. Clicks to make a comment
2. Cancel the entry => app freezes with no log output

This does not happen on Chrome.

### ✔️ Expected result

Close comment popup and return app to normal state

### ❌ Actual result

The application freezes unable to interact with other parts of the application

This does not happen on Chrome.

## 📃 Other details

Framework Angularjs 1.6.4

* Browser: Safari 13
* OS: OSX Catalina
* CKEditor version: 5
* Installed CKEditor plugins: Comments, Track Changes

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. As Comments are our commercial plugin and this issue tracker is dedicated to an open-source part of the project, could you please send the report via our [support channel](https://ckeditor.com/contact/)? Our team will be able to analyze your query and investigate it. Also, please provide a step-by-step instruction how to reproduce the problem, your CKEditor 5 dependencies versions and other information you find useful.
