### ISSUE TITLE
Upgrade Node to the next LTS version

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7258]
## Provide a description of the task

According to https://github.com/nodejs/Release, Node 10 will change its status from "Active" to "Maintenance".

In the nearby future, the upgrade will be a thing to do.

![image](https://user-images.githubusercontent.com/2270764/82539683-1fb60b80-9b4e-11ea-9ca2-d6610cf40b71.png)

**Comment by pomek** [comment]
Yeah. We still use 8.

https://github.com/ckeditor/ckeditor5/blob/e3e952148690e9bc6439a99c168b2abab0e9f046/package.json#L115-L118

**Comment by pomek** [comment]
One more confusing place:
https://github.com/ckeditor/ckeditor5/blob/5aebb0fe0db77f51095df26c03fccf4e57d8da15/docs/builds/guides/development/custom-builds.md#L32

**Comment by Reinmar** [comment]
Let's always upgrade to the "Active" version, so that would be v12 at the moment.

Also, in this ticket's scope I'd see only:

* ckeditor5
* ckeditor5-dev

Other repositories/packages should be pinged with a recommendation to follow this change.

**Comment by Reinmar** [comment]
Let's merge this effort into #7202.
