### ISSUE TITLE
dragging text does not re-arrange it and trims whitespace

### ISSUE THREAD

**Issue by thedavidmeister** [ckeditor/ckeditor5#726]
## 🐞 Is this a bug report or feature request? (choose one)

Not sure?

- Bug report
- Feature request

## 💻 Version of CKEditor

alpha2

## 📋 Steps to reproduce

1. select some text including whitespace either side (can use https://ckeditor.com/ckeditor-5-builds/#classic)
2. drag it somewhere else in the wysiwyg

## ✅ Expected result

text moves to where it is dragged (e.g. google docs) or does nothing (kind of lame but better than losing whitespace)

## ❎ Actual result

text remains in place but loses whitespace

## 📃 Other details that might be useful

ckeditor:

![tewxw1rcyb](https://user-images.githubusercontent.com/629710/34077064-1f739ea0-e34d-11e7-881a-5dbbea47ae66.gif)

google drive:

![loqumyhgsk](https://user-images.githubusercontent.com/629710/34077072-80e84b18-e34d-11e7-81e6-55163ebce4c6.gif)

**Comment by Reinmar** [comment]
Hi! The current behaviour is completely coincidental – we haven't yet worked on D&D and this is support for typing kicking in. There's an issue for adding D&D support: https://github.com/ckeditor/ckeditor5-clipboard/issues/23.

**Comment by thedavidmeister** [comment]
@Reinmar what is the best way to disable dnd in the meantime?

**Comment by thedavidmeister** [comment]
@Reinmar i am running into issues where this coincidental dnd behaviour is regurgitating everything in `event.dataTransfer` from the drag and drop API straight into the editor (which is all serialised machine data) - is there a way to disable this editor behaviour until proper support is added?

**Comment by thedavidmeister** [comment]
moved my q to https://github.com/ckeditor/ckeditor5-clipboard/issues/23
