### ISSUE TITLE
Broken documentation links to source code after monorepo migration

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#7265]
I noticed this "See source" link in the table docs is broken; not sure how many others there might be: https://ckeditor.com/docs/ckeditor5/latest/api/module_table_tableediting-TableEditing.html

**Comment by Reinmar** [comment]
Thanks! We're on it.

**Comment by mlewand** [comment]
@pomek isn't it a duplicate of #6763?

**Comment by pomek** [comment]
No, it's a different URL. The issue describes URLs in API Docs while #6763 is about "Contribute to the guide".

**Comment by Reinmar** [comment]
Fixed staging, should be fixed on prod tomorrow.
