### ISSUE TITLE
Inline placholder Widget for angular

### ISSUE THREAD

**Issue by KishanRavindran** [ckeditor/ckeditor5#7266]
Hello All,
     I am looking on the way to add functionality in my angular 8 project. https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html
I searched and looked for any docx related to doing the same steps in angular but I couldn't find any. So anyone can point in on the links on doing the same in angular 8 project it will helpful.

Thanks in Advance.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If you want to use a custom editor in Angular, you first need to build it on it's own and then add it in your Angular component. So in your case: 
- first create and build a standalone editor with [inline widget plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html)
- in your Angular app [import previously built `ckeditor.js` file into your editor component](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build)

I checked it and it works for me, so you shouldn't have problems either. In case anything goes wrong, I will need more information and detailed steps, to look into the issue.
Hope that helps!

**Comment by KishanRavindran** [comment]
Hi @FilipTokarski I have build the custom plugins following this link https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html
Also looked in this issue also
https://github.com/ckeditor/ckeditor5/issues/6413
https://github.com/ckeditor/ckeditor5-angular/issues/176

I have build the custom plugin and added them in my angular assets folder
![Screenshot 2020-05-22 at 2 36 29 PM](https://user-images.githubusercontent.com/22557988/82652698-aac0ff80-9c3b-11ea-9193-2c8fc05eefc7.png)
![Screenshot 2020-05-22 at 2 41 36 PM](https://user-images.githubusercontent.com/22557988/82652720-b44a6780-9c3b-11ea-82e6-2ff04b5a35f1.png)
And imported them in my component but the editor is not coming. And there is no error in console log.

I am not sure what I missed.

Thanks in advance.

**Comment by FilipTokarski** [comment]
That's strange 🤔  Please also make sure you installed our Angular integration, modified module file and added ckeditor tag in your component `html` file - you can find it all in [quick start guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#quick-start) ( but in this case there is no need to `npm install @ckeditor/ckeditor5-build-classic` because you import your own build ).

**Comment by KishanRavindran** [comment]
Hi @FilipTokarski I found what issue and fixed it. 

Thank you.

**Comment by FilipTokarski** [comment]
Ok, I'm glad that it works now 👍

**Comment by narenderkonka** [comment]
Inline placholder Widget for angular for this looking source code

**Comment by abhim089** [comment]
How can we initialize this inline widget inside custom build. 
I have already installed and editor is working properly but i am not able to initialize the placeholder inline widget plugin inside this custom build.
