### ISSUE TITLE
Editor.getData() cant get inline-style html

### ISSUE THREAD

**Issue by Dolov** [ckeditor/ckeditor5#7268]
hello 
I recently developing a feature rely ckeditor5, Her powerful function and outstanding appearance really attracted me, but i found editor.getData() cant get inline-style html string. Due to the editor content data needs to be used by unknown third-party companies，Could you add this function please.
If not，Can I know why ？ and Is there any other way to do this
Thank you for your reply anyway

**Comment by Mgsy** [comment]
Hi! Currently it's not possible to get HTML with inline styles, however, we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1627) for it. Feel free to add :+1: to the first post to bump its popularity.
