### ISSUE TITLE
Call external function from toolbar button

### ISSUE THREAD

**Issue by nirav-rb** [ckeditor/ckeditor5#7269]
We are using ckEditor5 with an angular application.

We need to add one button on CKEditor toolbar by clicking this button we need to execute function which is defined our angular application's component.ts file
Cuurently we added one button "MarvinJS" out side of Ckeditor as you can see in screen shot
![image](https://user-images.githubusercontent.com/55694457/82640407-25801f80-9c28-11ea-8342-ffe09168f830.png)

When you click on "MarvinJS" button, it will execute one function defined in our angular component.ts file and open an external editor(marvinjs editor) in pop up as you can see in this screenshot
![image](https://user-images.githubusercontent.com/55694457/82640597-80197b80-9c28-11ea-9a6f-9f4417748eab.png)

Now we need to add "MarvinJS" button inside CKEditor toolbar and by clicking it, it should execute the same function which is called by External "Marvin JS" button defined in component.ts and open external editor(marvinjs editor) in a popup.

So Can anyone please help me to achieve this?

**Comment by FilipTokarski** [comment]
Hi @nirav-rb , I think this issue has already been discussed and [here you can find a working solution](https://github.com/ckeditor/ckeditor5-angular/issues/197#issuecomment-623907020). I checked it and it works for me, so I'll close this issue now as a duplicate.

**Comment by everett86** [comment]
My answer search is complete https://angulardev.space/questions/running-a-function-using-a-component-in-angular-5
