### ISSUE TITLE
Question: is there ever a reason to use EditableElements in the data view?

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#7274]
## 📝 Is there ever a reason to use EditableElements in the data view?

I've switched between using EditableElement for things in my dataDowncasts that use EditablElement in the editingDowncast, and replacing them all with ContainerElement in the dataDowncast. It doesn't seem to make a difference, but I don't know how to tell for certain. 

I'm happy to do a docs PR mentioning "you don't need to use EditableElement in data downcast converters" on the EditableElement page or writer.createEditableElement section, but I don't want to say it if it's not true.

**Comment by Mgsy** [comment]
cc @Reinmar

**Comment by Reinmar** [comment]
There's no reason to use EditableElement in the data pipeline. EditableElement is an extension of ContainerElement that adds `isReadOnly` and `isFocused` properties that make no sense in the data. Actually, they won't even end up in the data as they are state of that element and (at least currently) the data pipeline is stateless.
