### ISSUE TITLE
Copy Word table and pasting into CKE5 loses table cell background color

### ISSUE THREAD

**Issue by luig0** [ckeditor/ckeditor5#7275]
## 📝 Provide detailed reproduction steps (if any)

1. Visit demo page [Pasting content from Microsoft Word](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo)
2. Download [sample Word document](https://ckeditor.com/docs/ckeditor5/latest/assets/CKEditor5.PFO.Sample.Recognition_of_Achievement.docx)
3. Copy table from sample Word document and paste it into the demo editor

<img width="506" alt="Screen Shot 2020-05-22 at 12 18 09 PM" src="https://user-images.githubusercontent.com/28884578/82697553-5e1ef980-9c26-11ea-8003-0c67993dda3a.png">

<img width="824" alt="Screen Shot 2020-05-22 at 12 18 49 PM" src="https://user-images.githubusercontent.com/28884578/82697578-6d05ac00-9c26-11ea-8205-3b5924ff6057.png">

### ✔️ Expected result

Copied table cell background colors from Word document are properly transferred to Ckeditor5 as described at [Table styles compatibility with CKEditor 4 and office suites (Word, Excel, Google Docs) #5652](https://github.com/ckeditor/ckeditor5/issues/5652). 

### ❌ Actual result

Table loses cell background color data after it is pasted into CKE. This appears to be happening in upcasting (?); some table cell inline styles are transferred to attributes, while others are not.

## 📃 Other details

* Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
* OS: macOS Catalina Version 10.15.4 (19E287)
* CKEditor version: @ckeditor/ckeditor5-editor-classic@18.0.0
* Installed CKEditor plugins: A bunch, but this issue exists in the demo editor at [Pasting content from Microsoft Word](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo)
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Looks like a regression was working in v17: https://ckeditor.com/docs/ckeditor5/17.0.0/features/pasting/paste-from-word.html#demo

**Comment by Reinmar** [comment]
Since this will require bisecting changes before our migration to monorepo, this will be useful: https://ckeditor.com/docs/ckeditor5/17.0.0/framework/guides/contributing/development-environment.html#bisecting-through-a-multi-repository

**Comment by Reinmar** [comment]
BTW, from some reports that I saw, I gather that  font colors and other font styles may be lost now too. We need to check all the formatting here. 

To whoever will work on this:

*   Make sure to enable PasteFromOffice plugin,
*   Make sure to use the `supportAllValues` config options of the font plugins,
*   Use table properties and font plugins.

In other words – use the same setup as in the Paste from Word demo in the docs.

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5/issues/7295#issuecomment-634484526 contains some really interesting findings about setups that don't work. The issue is much wider than just about tables (or we have two different regressions at the same time, which is unlikely).

**Comment by luig0** [comment]
@Reinmar @mlewand @niegowski Thank you for the quick turn!
