### ISSUE TITLE
Error caused by paste

### ISSUE THREAD

**Issue by huangxok** [ckeditor/ckeditor5#7276]
## 📝 Provide detailed reproduction steps (if any)

1. select text
2. ctrl+c
3. ctrl+v

### ✔️ Expected result
_What is the expected result of the above steps?_
paste work normally

### ❌ Actual result
![image](https://user-images.githubusercontent.com/7628834/82714027-99213b80-9cbf-11ea-88d4-66776dc1e61c.png)

## 📃 Other details

* Browser: chrome 81
* OS: Mac catalna 10.15.4
* CKEditor version: ck5@19.0.0
* Installed CKEditor plugins: 
![image](https://user-images.githubusercontent.com/7628834/82714144-fd43ff80-9cbf-11ea-9ef6-513e4f788523.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by huangxok** [comment]
I found the reason which is I using ImageUpload Plugin!
when using the ImageUpload , paste is not working and take a error.
I look for some Issues that looks like this.

**Comment by huangxok** [comment]
I read the docmention about how to create a custom plugin upload.
[](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html#implementing-a-custom-upload-adapter)

**Comment by huangxok** [comment]
[Custom image upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html#implementing-a-custom-upload-adapter)

**Comment by huangxok** [comment]
![image](https://user-images.githubusercontent.com/7628834/82727174-69a01c80-9d1b-11ea-8d45-a60d2b6aaa5a.png)
when pasting text, it will callback the imageuploadediting paste event.
I debug the code , found where cause error, **editor.editing.view.createRangeIn(data.content)** is a Range Object 
![image](https://user-images.githubusercontent.com/7628834/82727273-137fa900-9d1c-11ea-9c82-cebc0b5c50f1.png)
Array.form can‘t handle the Range Object.

**Comment by huangxok** [comment]
if there is a dataconte(image) on clipboard, I can paste image in editor(drop image,paste image),but I can‘t paste pure text

**Comment by Mgsy** [comment]
Hi! We've checked copy/paste with `ImageUpload` plugin active and we can't reproduce your issue. I can see that you try to create a custom image upload adapter, I believe there's some mistake in your implementation which crashes the editor, so I advice verifying it. 

Also, I can see that you use `Base64UploadAdapter` - note that using multiple upload adapters is not allowed and may break the editor. If you'd like to use only the custom adapter, remove other adapters from the editor.

**Comment by huangxok** [comment]
@Mgsy thank you!
I don't know what happened it when I use the demo [Custom image upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html#implementing-a-custom-upload-adapter).
when I build a new project and rewrite the editor, it works well.
maybe I used it wrong.
