### ISSUE TITLE
CKFinder issue.

### ISSUE THREAD

**Issue by RuchitaCrawl** [ckeditor/ckeditor5#7277]
Hey!! Thanks for this awesome package. :)

## 📝 detailed operation steps

```
 import CKEditor from '@ckeditor/ckeditor5-vue';
 import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';

 data() {
            return {
                editor: DecoupledEditor,
                editorData: '',
                editorConfig: {
                    ckfinder: {
                        uploadUrl: 'https://cksource.com/weuy2g4ryt278ywiue/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
                    },
                  
                },
            }
        },

```

Image is uploaded successfully. and it's work fine. but on next day when i open my editor it lookes like [this image](https://prnt.sc/sm6jua).

and when i open this image from it's url in browser it give me [this result.](https://prnt.sc/sm6ko8)

you can check this using this url:: https://cksource.com/weuy2g4ryt278ywiue/core/connector/php/connector.php?command=Proxy&type=Files&currentFolder=%2F&fileName=las-sillas-the-chairs-game-pico-pao.jpg

* Browser: Google Chrome 80.0.3987.149 
* OS: Ubuntu
* CKEditor version:  5
* Plugin version: 19.0

---

**Comment by Mgsy** [comment]
Hi, thanks for the report. CKFinder is our commercial plugin and you use our upload endpoint created for a demo purpose. Please, [contact us](https://ckeditor.com/contact/) to discuss a possibility for integrating CKFinder in your application.
