### ISSUE TITLE
Update Config on runtime in angular

### ISSUE THREAD

**Issue by KishanRavindran** [ckeditor/ckeditor5#7278]
Hi All,
    I have added a placeholder config using the inline widget following this link
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html
And I was able successfully to add it to my angular component. Now I need to update that config with dynamic values. 
And also did some research on it and found that we can't update the editor config once it is initialized so we need to destroy the editor and create it again. 

I have tried to destroy and create it but once destroy the editor I am not able to reinitialize it.  So can anyone guide me on how to destroy and create an editor or update my config details.

Thanks in Advance

**Comment by Mgsy** [comment]
@ma2ciek, can you take a look at it?

**Comment by ma2ciek** [comment]
The `ckeditor5-angular` component supports only updating the data right now.

Could you describe your use case more deeply?

**Comment by KishanRavindran** [comment]
Hi @ma2ciek sorry for late reply
The below is the code in there I need to update the value types in the placholderconfig. As the values to it will come dynamically from a table. I have added this in the `Oninit` of the angular component.
`Editor.create(document.querySelector('#editor'), {
      placeholderConfig: {
        types: this.test
      }
    }).then(editor => {
    }).catch(error => {
      console.log(error);
    })`

And I also tried to destroy and create it but once it destroyed the CKEditor is not showing. 
I did it like the below then I came to know that I should not add editor.destory in promise.
`Editor.create(document.querySelector('#editor'), {
      placeholderConfig: {
        types: this.test
      }
    }).then(editor => {
             editor.destroy()
    }).catch(error => {
      console.log(error);
    })`

So Please tell me how to update this dynamically without the need to re-create the CKeditor.
`placeholderConfig: {
        types: this.test
      }`

Or please tell me how to delete and create it without refreshing the view in angular UI.

**Comment by jpduckwo** [comment]
I've got the same issue, our placeholder is updated after the editor is loaded but I can't figure out a way to get the ckeditor to refresh with a new configuration (which has the placeholder text setting)...

**Comment by Reinmar** [comment]
Request for a dynamic option: `config.toolbar.viewportTopOffset`.

**Comment by ma2ciek** [comment]
This issue is cross-framework (it touches also implementations of React and Vue integrations). With such issues, I'm not sure if we should track them in CKEditor 5 or in these repositories.

cc @Reinmar

**Comment by Reinmar** [comment]
Let's merge this into #7383.
