### ISSUE TITLE
Upload success, but no url insert via editor.getData()

### ISSUE THREAD

**Issue by 26903651** [ckeditor/ckeditor5#728]
Sorry for my poor English.
I implements my Adaper with this [doc](https://docs.ckeditor.com/ckeditor5/latest/api/module_upload_filerepository-Adapter.html)
The file upload to my server successfully, and I return a url with json data : 

```
resolve({default : imageUrl});
```

, but when I try to get the html data via editor.getData(), it return something like this:

```
<figure class="image"><img></figure>
```

**Comment by Reinmar** [comment]
Did you check whether `imageUrl` really holds some value? And whether there are no errors? And that this line is really called?

If all these things are true then we'd need to see a full code.

**Comment by 26903651** [comment]
Yes, I checked all you said, there is my full code.
`var xlsys = require("xlsys");

export default class UploadAdapter
{
	constructor(loader)
	{
		// Save Loader instance to update upload progress.
		this.loader = loader;
		this.xhr = undefined;
	}

	onProgress = (e) => {
		this.loader.uploadTotal = e.total;
		this.loader.uploaded = e.loaded;
	}

	_promiseUpload = (resolve, reject) => {
		this.xhr = new XMLHttpRequest();
		this.xhr.upload.addEventListener("progress", this.onProgress, false);
		this.xhr.upload.addEventListener("load", resolve, false);
		let env = xlsys.core.env.Environment.getInstance();
		let serverIp = env.getString(xlsys.client.base.ClientBase.ENV_TRANSFER_SERVERIP);
		let serverPort = env.getString(xlsys.client.base.ClientBase.ENV_TRANSFER_SERVERPORT);
		let uploadUrl = env.getString(xlsys.client.base.ClientBase.ENV_TRANSFER_UPLOAD_PATH);
		let timeout = xlsys.core.util.ObjectUtil.objectToInt(env.getString(xlsys.base.Base.ENV_REQUEST_TIME_OUT));
		uploadUrl = "http://" + serverIp + ":" + serverPort + uploadUrl+"?type=ckeditor5";
		this.xhr.open("POST", uploadUrl);
		let formData = new FormData();
		this.attachment = new xlsys.core.io.Attachment(this.loader.file.name, 0, xlsys.core.io.Attachment.STYLE_FILE_SYSTEM, null);
		this.attachment.setAttachmentName(this.loader.file.name);
		this.attachment.setSize(this.loader.file.size);
		this.attachment.setPath(xlsys.base.Base.RESOURCE_PRELOAD_DIR+"/ckeditor");
		this.attachment.type = this.loader.file.type;
		formData.append(xlsys.base.Base.UPLOAD_PARAM_ATTACHMENT, xlsys.core.util.IOUtil.getCommonJSONFromObj(this.attachment));
		formData.append(xlsys.base.Base.UPLOAD_PARAM_ATTACHMENT_DATA, this.loader.file, this.loader.file.name);
		let isTimeout = false;
		if(timeout>0)
		{
			setTimeout(()=>{
				isTimeout = true;
				this.xhr.abort();
				reject(new Error("Request Timeout"));
			}, timeout);
		}
		this.xhr.onreadystatechange = ()=>{
			if(!isTimeout && this.xhr.readyState===4 && this.xhr.status===200)
			{
				let ret = JSON.parse(this.xhr.responseText);
				if(ret.success)
				{
					let imageUrl = "http://" + serverIp + ":" + serverPort + ret.url;
					resolve({default : imageUrl});
				}
				else reject();
			}
		};
		this.xhr.send(formData);
	}

	upload()
	{
		return new Promise(this._promiseUpload);
	}

	abort()
	{
		if(this.xhr) this.xhr.abort();
	}
}`

**Comment by 26903651** [comment]
`import React, { Component } from "react";
import PropTypes from "prop-types";
import ClassicEditor from "ckeditor5-build-classic-xlsys";
import "./xlr-client-htmleditor.css";
import UploadAdapter from "./UploadAdapter";

export default class HtmlEditor extends Component
{
	static propTypes = {
		
	};

	static defaultProps = {
		
	};

	constructor(props)
	{
		super(props);
		this.textarea = undefined;
		this.editor = undefined;
	}

	componentDidMount()
	{
		this._initCKEditor();
	}

	componentWillUnmount()
	{
		this.editor.destroy();
	}

	_initCKEditor = async () => {
		this.editor = await ClassicEditor.create(this.textarea);
		this.editor.plugins.get("FileRepository").createAdapter = (loader)=>(new UploadAdapter(loader));
	}

	render()
	{
		return (
			<div
				{...this.props}
			>
				<textarea
					ref={(ref)=>{this.textarea=ref;}}
				/>
			</div>
		);
	}
}`

**Comment by 26903651** [comment]
I use a custom build with only change the language to 'zh'

**Comment by Reinmar** [comment]
Hm... The code looks fine really. So you can check two things:

* Whether `resolve()` is really called and that you don't call `reject()` as well (that would through if I remember correctly, but it's best to check).
* What's the value of the `src` param in the DOM. If it's updated there once the promise is resolved.

**Comment by 26903651** [comment]
I find the problem, there is no bug, I add an listener to onload event, and with callback 'resolve', first, so when the load finish, it callback with null.
Thanks for your response, @Reinmar

**Comment by Reinmar** [comment]
Great!
