### ISSUE TITLE
Can't copy paste html snippets to the editor

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor5#7281]
## Provide a description of the task
The company I'm working want to migrate from Durpal to DatoCMS, and now I'm importing existing datas from Durpal to DatoCMS, and they were used ckeditor4 for the rich text editor, for the new CMS I used ckeditor5 and done adding many custom plugins, but finally I can't copy past/import the existing datas to the new ckeditor5.

<img width="724" alt="Screen Shot 2020-05-25 at 11 09 02 AM" src="https://user-images.githubusercontent.com/51118408/82792514-345d1100-9e78-11ea-9091-67d7c507f89a.png">

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser: …
* OS: OSX
* CKEditor version: 5
* Installed CKEditor plugins: …

**Comment by Mgsy** [comment]
Hi. Basically, CKEditor 4 content is not compatible with CKEditor 5. You can read more about it [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html#existing-data). However, CKEditor 4 [code snippet plugin](https://ckeditor.com/cke4/addon/codesnippet) produces HTML which should be recognizable for CKEditor 5 code block feature. Also, I can't see [code blocks](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html) icon in your toolbar. Are you sure you have installed this plugin in your editor?

**Comment by henok-tesfaye** [comment]
Hi, sorry If I make you confused. I don't want the code blocks icon. I want the `sources` icon from ckeditor4. So that copy paste of the above content in sources(html mode) will display the actual HTML result when toggling it.

**Comment by Mgsy** [comment]
Thanks for the clarification. Source view is not available in CKEditor 5. There's a [feature request](https://github.com/ckeditor/ckeditor5/issues/592) for it with a long discussion, so you can read it to learn why we didn't decide to implement it yet.
