### ISSUE TITLE
Touch outside table clears selected content inside table

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7288]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a two+ block content in a table cell. I've used `<p><hr><p>` but `<p><p>` also shows this.
2.  Select a content inside this cell.
3.  Touch outside the table.

Found in the horizontal line feature guide.

### ✔️ Expected result

The selection changes or stays the same. The content douesn't change.

### ❌ Actual result

The content is cleared.

![](https://user-images.githubusercontent.com/247363/82819220-5074a880-9ea0-11ea-91e8-23231ccffb1e.gif)

## 📃 Other details

*   Browser: Chrome@Android ~`80.0.4147.105` (I've might used previous one as this is what I have now)~ the one that was available on [May 25th](https://www.apkmirror.com/apk/google-inc/chrome/)
*   OS: Android 9
*   phone: Galaxy S8+ (SM-G955F)
*   keyboard: GBoard
*   CKEditor version: latest stable

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Unfortunately, it can't be reproduced on iOS Chrome and also on Mobile view in Chrome Dev tools.

**Comment by pomek** [comment]
Same using Android Studio and Virtual Devices:

![image](https://user-images.githubusercontent.com/2270764/88894673-88092380-d248-11ea-82df-cc2101826d98.png)

![image](https://user-images.githubusercontent.com/2270764/88894682-8c354100-d248-11ea-9375-1543ca57d700.png)

**Comment by jodator** [comment]
Update: I cannot reproduce it on my current setup (latest mobile chrome and Gboard).

I'd go with :+1: for the fix w did or did not in the meantime.
