### ISSUE TITLE
BlockAutoformatEditing and InlineAutoformatEditing  does not have docs for pluginName property

### ISSUE THREAD

**Issue by tomalec** [ckeditor/ckeditor5#7290]
## 📝 Provide a description of requested docs changes

As you can see below `pluginName` property does not have any docs for `BlockAutoformatEditing` and `InlineAutoformatEditing`
- https://ckeditor.com/docs/ckeditor5/latest/api/module_autoformat_inlineautoformatediting-InlineAutoformatEditing.html#static-member-pluginName 
- https://ckeditor.com/docs/ckeditor5/latest/api/module_autoformat_blockautoformatediting-BlockAutoformatEditing.html#static-member-pluginName 

These properties were added at https://github.com/ckeditor/ckeditor5/commit/3879b034c2f354b134191c5107ef941aa4501ca7 with `@inheritDoc`, but the thing is both classes do not inherit from anything.
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-autoformat/src/blockautoformatediting.js#L23

Personally, I don't get the design pattern there. They only have a `constructor()` defined, which does a lot, and the instances returned from `constructors` are not used anywhere.

Given the instances are not stored anywhere, I'm not sure why `pluginName` is even needed?

**Comment by Reinmar** [comment]
Those properties can be removed as these are not plugins.

**Comment by jodator** [comment]
My 2 cents: Yep it looks like those can be simple functions - we use that pattern everywhere else.

Personally I don't like creating objects that are not referenced anywhere so it would be nice to refactor that (if we have time, etc).

**Comment by tomalec** [comment]
If we're about to do small refactoring, I'd add simplifying arguments handling to the list.

Currently, there is [a logic](https://github.com/ckeditor/ckeditor5/blob/de677bbc2dadfc7ba7833a70134cbc40403e4391/packages/ckeditor5-autoformat/src/inlineautoformatediting.js#L90-L100) to support, various types of arguments like: `testRegexpOrCallback`, `attributeOrCallback`, even though, the only case we actually use is: `testRegexp`, `callback`

**Comment by Reinmar** [comment]
Let's cover that in #1239.
