### ISSUE TITLE
How to integrate a external font family with my Ckeditor5 build. 

### ISSUE THREAD

**Issue by shrirangjoshi94** [ckeditor/ckeditor5#7293]
## I had a font family to integrate with my existing build. I had the zip file of this font family(https://fonts.google.com/specimen/Poppins).

Can someone please guide me on the steps to include it with my build. I tried to find out in the documentation but was not able to get the details regarding the functionality which I wanted to achieve.

## 📃 Other details

I was using Ckeditor5 along with Jquery and Laravel.

**Comment by FilipTokarski** [comment]
Hi, you can include the font on your website, like you would do it normally ( for example using `@font-face` or in `link` tag ) and then [add it in fontFamily configuration](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-family-feature). That should do the trick.

**Comment by shrirangjoshi94** [comment]
Hey Filip,
Thank you for resolving my query.
