### ISSUE TITLE
What should be proposed by the changelog generator if a package has only "Fix" commits but introduced MINOR BREAKING CHANGE?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7299]
Sorry for the long title.

But… 

During the current release, we spotted that `media-embed` has `MAJOR BREAKING CHANGE` in the `Fix` type of the commit (https://github.com/ckeditor/ckeditor5/commit/3011e37768225dfe928f3e3321753fc04ca58ff2).

The tool proposed the `patch` version bump and we went this way. But it does not make any sense when you will see in the "Releases packages" section:

```
Minor releases (contain minor breaking changes):

@ckeditor/ckeditor5-media-embed: v19.0.0 => v19.0.1
```

We decided to switch manually to the minor bump.

**Comment by pomek** [comment]
And also sorry for the mess with labels. I don't know which one should be used.

**Comment by Reinmar** [comment]
All repos follow the same version number now, so usually there'd be another package with a feature/other change that'd need to bump the minor version (y in x.y.z) and then all packages would follow.

However, assuming a theoretically release with just a fix + minor bc, I'd still say that it should be a minor release (y in x.y.z).

**Comment by Reinmar** [comment]
> However, assuming a theoretically release with just a fix + minor bc, I'd still say that it should be a minor release (y in x.y.z).

We agreed that this should be the rule.
