### ISSUE TITLE
Should "Release" commit contain [skip ci]?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7302]
We added it in the past because of CI. After publishing a package and pushing it on GH, CI can require packages in which the release process is still in progress. CI couldn't install the proper version and it ended with an error.

As for now, when we have a single repo, I guess we can remove that and verify the release on CI.

The example release commit: https://github.com/ckeditor/ckeditor5/commit/1ddafcc7ec8e0ee184c5e16bc784170b3a1bcfa8

cc: @Reinmar, @mlewand

**Comment by Reinmar** [comment]
:+1:
