### ISSUE TITLE
ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated

### ISSUE THREAD

**Issue by zhangtaoBqteam** [ckeditor/ckeditor5#7304]
## 📝 Provide detailed reproduction steps (if any)

1. i want to use both document editor and classic editor, so i add two components through Vue.
2. CkeditorClassic
```javascript
import { Component, Vue, Prop, Watch } from 'vue-property-decorator';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import "@ckeditor/ckeditor5-build-decoupled-document/build/translations/zh-cn";
@Component({
  name: 'CkeditorClassic'
})
export default class extends Vue {
   @Prop({ required: true }) editorData!: string;

   private editorDataCopy = "";
   private editorConfig = {
     language: "zh-cn" // 中文
   };
   private editor: any = null

   @Watch("editorDataCopy")
   watchEditorDataCopy() {
     this.$emit("update:editorData", this.editorDataCopy);
   }

   /**
   * 初始化容器
   */
    public initEditor() {
      ClassicEditor.create(document.getElementById('editor-classic'), this.editorConfig)
        .then((editor: any) => {
          this.editor = editor
          editor.setData(this.editorDataCopy)
        })
        .catch((error: any) => {
          console.error("There was a problem initializing the editor.", error);
        });
    }
  }
```
3. CkeditorDocument
```javascript
import { Component, Vue, Prop, Watch } from 'vue-property-decorator';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import "@ckeditor/ckeditor5-build-decoupled-document/build/translations/zh-cn";
@Component({
  name: "CkeditorDocument"
})
export default class extends Vue {
  @Prop({ required: true }) editorData!: string;
  private editorDataCopy = "";
  private editorConfig = {
    language: "zh-cn", // 中文
    extraPlugins: [ ImgUploadAdapterPlugin ]
  };

  @Watch("editorDataCopy")
  watchEditorDataCopy() {
    this.$emit("update:editorData", this.editorDataCopy);
  }
  
  public initEditor() {
    this.editorDataCopy = this.editorData;
    DecoupledEditor.create(this.editorDataCopy, this.editorConfig)
      .then((editor: any) => {
        this.editor = editor
        const toolbarContainer = document.getElementById("toolbar-container");
        const editableContainer = document.getElementById("editable-container");
        if (toolbarContainer && editableContainer) {
          toolbarContainer.appendChild(editor.ui.view.toolbar.element);
          editableContainer.appendChild(editor.ui.view.editable.element);
        }
      })
      .catch((error: any) => {
        console.error("There was a problem initializing the editor.", error);
      });
  }
}
```
4. but when i switch CkeditorClassic editor to CkeditorDocument editor (from one page to another), the error ```ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated``` happened

### ✔️ Expected result

no error

### ❌ Actual result

![image](https://user-images.githubusercontent.com/43007011/83008558-ea2a8a00-a047-11ea-8cc5-d3e913815c0d.png)

## 📃 Other details

* Browser: Google
* OS: MacOs
* CKEditor version:  @ckeditor/ckeditor5-build-classic(19.0.0), @ckeditor/ckeditor5-build-decoupled-document(19.0.0)
* Installed CKEditor plugins: none

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Basically, you can't use two builds on the same page - it will lead to code duplication which is a cause of the error you experience. To solve that, you can create a "super build". Please, see our guide about [using two different editors on the same page](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors).

**Comment by zhangtaoBqteam** [comment]
> Hi! Basically, you can't use two builds on the same page - it will lead to code duplication which is a cause of the error you experience. To solve that, you can create a "super build". Please, see our guide about [using two different editors on the same page](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors).

Thank you so much. I just updated the build and it works
