### ISSUE TITLE
List toolbar item working?

### ISSUE THREAD

**Issue by 26903651** [ckeditor/ckeditor5#731]
I want to listing all available item with code
`console.log(Array.from( editor.ui.componentFactory.names ));`
but the array length is 0, did I missed something?

**Comment by Reinmar** [comment]
So maybe you haven't loaded any plugins like Bold or Italic?

**Comment by 26903651** [comment]
I used ckeditor-build-classic, and there is some item in toolbar, like Bold and Italic, and they are functionaly , I want to show more item, but I get nothing

**Comment by 26903651** [comment]
there is my code
`import React, { Component } from "react";
import PropTypes from "prop-types";
import ClassicEditor from "ckeditor5-build-classic-xlsys";
import "./xlr-client-htmleditor.css";
import UploadAdapter from "./UploadAdapter";

export default class HtmlEditor extends Component
{
	static propTypes = {
		
	};

	static defaultProps = {
		
	};

	constructor(props)
	{
		super(props);
		this.textarea = undefined;
		this.editor = undefined;
	}

	componentDidMount()
	{
		this._initCKEditor();
	}

	componentWillUnmount()
	{
		this.editor.destroy();
	}

	_initCKEditor = async () => {
		this.editor = await ClassicEditor.create(this.textarea);
		this.editor.plugins.get("FileRepository").createAdapter = (loader)=>(new UploadAdapter(loader));
		console.log(Array.from( this.editor.ui.componentFactory.names )); // I got an empty array
	}

	render()
	{
		return (
			<div
				{...this.props}
			>
				<textarea
					ref={(ref)=>{this.textarea=ref;}}
				/>
			</div>
		);
	}
}`

**Comment by Reinmar** [comment]
It all depends what's in `ckeditor5-build-classic-xlsys`. Whether that editor has some plugins built in or not.

E.g. this editor class will have plugins built in: https://github.com/ckeditor/ckeditor5-build-classic/blob/master/src/ckeditor.js#L26-L44 (hence, we call it a build... after passing it through webpack)

This editor doesn't have plugins built in: https://github.com/ckeditor/ckeditor5-editor-classic/blob/master/src/classiceditor.js#L40 so you need to pass those plugins into the `create()` method of it (as a `config.plugins`). Just like here: https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html#Let-39-s-start

**Comment by 26903651** [comment]
I think my situation is very simple, I cloned `ckeditor5-build-classic`, and change it's language to `zh`, and build it, then I publish it to npm with name `ckeditor5-build-classic-xlsys`, i didn't change anything else, so i think this build has full plugins. 
The build-config.js full code ：
`
'use strict';

module.exports = {
	// The editor creator to use.
	editor: '@ckeditor/ckeditor5-editor-classic/src/classiceditor',

	// The name under which the editor will be exported.
	moduleName: 'ClassicEditor',

	// Plugins to include in the build.
	plugins: [
		'@ckeditor/ckeditor5-essentials/src/essentials',

		'@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter',
		'@ckeditor/ckeditor5-autoformat/src/autoformat',
		'@ckeditor/ckeditor5-basic-styles/src/bold',
		'@ckeditor/ckeditor5-basic-styles/src/italic',
		'@ckeditor/ckeditor5-block-quote/src/blockquote',
		'@ckeditor/ckeditor5-easy-image/src/easyimage',
		'@ckeditor/ckeditor5-heading/src/heading',
		'@ckeditor/ckeditor5-image/src/image',
		'@ckeditor/ckeditor5-image/src/imagecaption',
		'@ckeditor/ckeditor5-image/src/imagestyle',
		'@ckeditor/ckeditor5-image/src/imagetoolbar',
		'@ckeditor/ckeditor5-link/src/link',
		'@ckeditor/ckeditor5-list/src/list',
		'@ckeditor/ckeditor5-paragraph/src/paragraph',
		'@ckeditor/ckeditor5-upload/src/imageupload',
	],

	// UI language. Language codes follow the https://en.wikipedia.org/wiki/ISO_639-1 format.
	language: 'zh',

	// Editor config.
	config: {
		toolbar: {
			items: [
				'headings',
				'bold',
				'italic',
				'link',
				'bulletedList',
				'numberedList',
				'blockQuote',
				'undo',
				'redo'
			]
		},

		image: {
			toolbar: [ 'imageStyleFull', 'imageStyleSide', '|', 'imageTextAlternative' ]
		}
	}
};
`

**Comment by 26903651** [comment]
@Reinmar I test it with original ckeditor-build-classic, still, I got an empty array.
there are my steps:
1. npm install --save @ckeditor/ckeditor5-build-classic
2. import it in my class with code `import ClassicEditor from "@ckeditor/ckeditor5-build-classic";`
3. Get the item list : `console.log(Array.from( this.editor.ui.componentFactory.names ));`
there is my code : 
`
import React, { Component } from "react";
import PropTypes from "prop-types";
// import ClassicEditor from "ckeditor5-build-classic-xlsys";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import "./xlr-client-htmleditor.css";
import UploadAdapter from "./UploadAdapter";

export default class HtmlEditor extends Component
{
	static propTypes = {
		
	};

	static defaultProps = {
		
	};

	constructor(props)
	{
		super(props);
		this.textarea = undefined;
		this.editor = undefined;
	}

	componentDidMount()
	{
		this._initCKEditor();
	}

	componentWillUnmount()
	{
		this.editor.destroy();
	}

	_initCKEditor = async () => {
		this.editor = await ClassicEditor.create(this.textarea);
		this.editor.plugins.get("FileRepository").createAdapter = (loader)=>(new UploadAdapter(loader));
		console.log(Array.from( this.editor.ui.componentFactory.names )); // Still I got an empty array
	}

	render()
	{
		return (
			<div
				{...this.props}
			>
				<textarea
					ref={(ref)=>{this.textarea=ref;}}
				/>
			</div>
		);
	}
}
`

**Comment by Reinmar** [comment]
Ooopsie. My bad. We've got a bug in the docs. It should be:

```js
Array.from( this.editor.ui.componentFactory.names() )
```

I'm going to fix it in the docs. Thanks for pointing this out.

**Comment by Reinmar** [comment]
Fixed in ckeditor5, ckeditor5-core and ckeditor5-ui.

**Comment by 26903651** [comment]
Should I update my ckeditor build?

**Comment by Reinmar** [comment]
No no, it's just the docs. You've tried to call this so far:

```js
Array.from( this.editor.ui.componentFactory.names )
```

While the right code is:

```js
Array.from( this.editor.ui.componentFactory.names() )
```

The latter will work with the current builds.
