### ISSUE TITLE
Vertical align of table cells in the content is wrong and causes content jumps

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7310]
## 📝 Provide a description of requested docs changes

In this example an empty paragraph is created before a widget and then removed.

![](https://user-images.githubusercontent.com/1099479/83034360-72089800-a038-11ea-8ea5-81a04f975fb4.gif)

This is caused by [reset styles](https://ckeditor.com/docs/assets/1.3.2/css/styles.css) we use in the docs that enforce `vertical-align: baseline` on almost everything. Using `vertical-align: middle` fixes the problem.

**Comment by Reinmar** [comment]
Could you fix this in the docs?

**Comment by oleq** [comment]
Yes, this should be addressed in our docs styles. This is not a general editor issue.
