### ISSUE TITLE
How to Implement Inline Widget ?

### ISSUE THREAD

**Issue by beingArkReal** [ckeditor/ckeditor5#7312]
`

import React, { Component } from "react";
import CKEditor from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import { Grid } from "@material-ui/core";
class WYSIWYG extends Component {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }

  render() {
    console.log(ClassicEditor.builtinPlugins.map((plugin) => plugin.pluginName));
    return (
      <Grid container alignItems="stretch">
        <Grid item xs={12}>
          <CKEditor
            ref={this.myRef}
            config={{
              toolbar: ["heading", "|", "bold", "italic", "blockQuote", "link", "numberedList", "bulletedList", "imageUpload", "insertTable", "tableColumn", "tableRow", "mergeTableCells", "mediaEmbed", "|", "undo", "redo", ],
            }}
            editor={ClassicEditor}
            data={this.props.value}
            onInit={(editor) => {
              editor.ui.componentFactory.add("MyPlugin");
              let D = Array.from(editor.ui.componentFactory.names());

              // You can store the "editor" and use when it is needed.
            }}
            onChange={(event, editor) => {
              const data = editor.getData();
              this.props.onChange(data);
            }}
            onBlur={(event, editor) => {}}
            onFocus={(event, editor) => {}}
          />
        </Grid>
      </Grid>
    );
  }
}

export default WYSIWYG;
`

**Comment by Mgsy** [comment]
Hi, could you please provide some description to your issue? The code itself doesn't explain your problem. Also, did you see our [Implementing an inline widget guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html)?
