### ISSUE TITLE
Insert image icon appears with white background

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#732]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Load the editor with image upload or go to http://localhost:8125/ckeditor5-easy-image/tests/manual/easyimage.html

## ✅ Expected result

All icons have no background.

## ❎ Actual result

`Insert image` icon has white background.

## 📃 Other details that might be useful

**Screenshot**
![screen1](https://user-images.githubusercontent.com/20988892/34147538-550e193a-e49e-11e7-9c26-86c9a9111527.png)

**Other information**
OS: Windows 10, MacOS X
Browser: All browsers

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Reported an [issue](https://github.com/ckeditor/ckeditor5-theme-lark/issues/120) in Lark.

**Comment by oleq** [comment]
This issue is already addressed in https://github.com/ckeditor/ckeditor5/issues/645.
