### ISSUE TITLE
Non Editable Element

### ISSUE THREAD

**Issue by ThenmozhiD** [ckeditor/ckeditor5#7322]
I have insert a dynamic content into my editor using the below code
```
const appendData = arg.code;
    const selection = this.editor.editorInstance.model.document.selection;
    const range = selection.getFirstRange();
    this.editor.editorInstance.model.change(writer => {
      writer.insert(appendData, range.start);
    });
```
My screen looks like this:
![image](https://user-images.githubusercontent.com/16700578/83132098-8020ec00-a0fe-11ea-9493-cec95f5cdf32.png)

How to make the content (only the inserted text) as non editable and also I want to clear the whole text with single backspace.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If you are trying to create an inline widget, please [refer to docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html). If something else, then please provide more detailed and step-by-step information about what you are trying to achieve.

**Comment by ThenmozhiD** [comment]
I am expecting the same behavior. But, the placeholders will not be in dropdown.
In that case how to achieve this?

**Comment by FilipTokarski** [comment]
The same behavior as what? As I asked in comment above, please explain in details your use case and what goal you're trying to achieve, so then we will be able to look into this issue.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
