### ISSUE TITLE
🐛 write.move() duplicate the range at the new position

### ISSUE THREAD

**Issue by castroCrea** [ckeditor/ckeditor5#7324]
## 📝 Provide detailed reproduction steps (if any)

I'm trying to do a drag n drop plugin content

But when I use `write.move()` it work but there is a duplication, because the remaining context is still here.

This is my plugin 
```
import Plugin from "@ckeditor/ckeditor5-core/src/plugin";
import { isWidget } from "@ckeditor/ckeditor5-widget/src/utils";

export default class DragNDropContent extends Plugin {
	static get requires() {
		return [DragNDropContentEditing];
	}
}

class DragNDropContentEditing extends Plugin {
	init() {
		const editor = this.editor;

		// Prevents from the browser redirecting to the dropped image.
		this.listenTo(
			editor.editing.view.document,
			"clipboardInput",
			(evt, data, dropRange) => {
				const ranges = data.targetRanges.map((viewRange) =>
					editor.editing.mapper.toModelRange(viewRange)
				);

				const blocks = editor.model.document.selection.getSelectedBlocks();
				let numberOfBlock = 0;
				let start;
				let end;
				// crawl all the block to get the previous block and the start position and end position
				for (const block of blocks) {
						if (numberOfBlock === 0) {
							editor.model.change((writer) => {
								start = writer.createPositionAt(
									block,
									"before"
								);
							});
						}
						editor.model.change((writer) => {
							end = writer.createPositionAt(block, "after");
						});
						numberOfBlock++;
				}

				// Move the block
				if (numberOfBlock && start && end) {
					editor.model.change((writer) => {
						try {
							const rangeSource = writer.createRange(start, end);
							//bug there is a duplication of the block so we need to remove the other one after
							writer.move(
								rangeSource,
								ranges[0].getCommonAncestor(),
								"before"
							);
						} catch (e) {
							console.log(e);
						}
					});
				}
			}
		);
	}
}

```

So I can put a hack that delete the block at the place where the caret remain but it's not really ideal

Do you have any idea, why it move and let the old block ? 

My guess writer.remove() doesn't work on range

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
cc @Reinmar

**Comment by castroCrea** [comment]
Hello just for more context:

* first I select the text with natural computer selection
* Then I move the text with natural drag n drop
* and I watch the drop with the event ** clipboardInput** (unfortunatly the drop event doesn't return the **data.targetRanges**)
* Then I get the range that wrap all the block where my selected text is.
* And I apply move in the model change

Thanks for the help

**Comment by Reinmar** [comment]
Hi @castroCrea! I replied to you in https://github.com/ckeditor/ckeditor5/issues/2664#issuecomment-635793428. I covered briefly how I'd approach implementing this. I don't know if that's in line with what you tried to achieve as from what I can see, you're trying to work on a block-level.

Assuming that you'd go in the direction that drag&drop works similar to copy&paste, then insertion of the content that's been put into the data transfer is already done – the clipboard pipeline also handles `drop`.

However, what's not done:

*   on `dragstart` the content should be stringified to HTML and put into the data transfer – just like we do for `copy` now,
*   on `drop` we need to delete the content that was previously selected in the editor (if that's the content that's dropped – IDK how to check that in the easiest way) and also ensure that the focus is in the editor by calling `editor.editing.view.focus()`.

**Comment by Reinmar** [comment]
BTW, you don't have to use `model.change()` to create positions – the same methods are available on `model` itself.

**Comment by castroCrea** [comment]
Thank @Reinmar I will dig on this side, it is totally the D proposition on https://github.com/ckeditor/ckeditor5/issues/2664#issuecomment-635793428

**Comment by Reinmar** [comment]
I suppose I can close this ticket. Let us know in case I'm wrong.
