### ISSUE TITLE
Link's save button not working in React build for inline editor

### ISSUE THREAD

**Issue by Sawan1994** [ckeditor/ckeditor5#7325]
## 📝 Provide detailed reproduction steps (if any)

1. Install react build using https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html
2. Pass below config in CKeditor:
{
  toolbar: ["heading", "|", "italic", "link"],
  heading: {
    options: [
      { model: "heading1", view: "h1", title: "Heading 1", class: "" },
      { model: "heading2", view: "h2", title: "Heading 2", class: "" },
      { model: "heading3", view: "h3", title: "Heading 3", class: "" },
      { model: "heading4", view: "h4", title: "Heading 4", class: "" },
      { model: "heading5", view: "h5", title: "Heading 5", class: "" },
      { model: "heading6", view: "h6", title: "Heading 6", class: "" },
    ],
  },
}
3. In Ckeditor UI, try to save link on some text.
4. The Save icon does nothing.

### ✔️ Expected result

On clicking on save ✔️ icon in Link editor, Link panel should close and link should be created on the text.

_What is the expected result of the above steps?_

### ❌ Actual result
On clicking on save ✔️ icon in Link editor, Link panel does not close. No error on console. It seems nothing is happening on clicking the ✔️icon

_What is the actual result of the above steps?_

Nothing

## 📃 Other details

* Browser : Chrome
* OS: Windows 10
* CKEditor version:@ckeditor/ckeditor5-react, version "^2.1.0"
* Installed CKEditor plugins: using the already available Link plugin in the build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I check it with your configuration and it works for me. I can save the link. In order to look into this I will need more information about what plugins you use, how exactly you created the app and a step-by-step instruction to reproduce this.

**Comment by Sawan1994** [comment]
@FilipTokarski 

I have created my project using create-react-app and the installed the react build of CKEditor as below:

npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-inline

Then I created a component in react and used 
<CKEditor
   editor={ InlineEditor}
....
/>

and then passed data from parent to this component using props.

That's it.

**Comment by FilipTokarski** [comment]
Hi, unfortunately there must be some problem on your side and not with the editor. I tried using normal React integration and also building from source and I wasn't able to reproduce this issue in any way. Maybe you could just try creating your app from scratch once again.
