### ISSUE TITLE
Table toolbar overlaps main toolbar dropdowns

### ISSUE THREAD

**Issue by otherblandart** [ckeditor/ckeditor5#7329]
## 📝 Provide detailed reproduction steps (if any)

1. Include a plugin that supplies toolbar UI that includes a dropdown (Ex: FontFamily, FontSize)
2. Include Table and TableToolbar plugins
3. Add Table toolbar definition in editor config
4. Initialize an Editor (I'm using Classic)
5. Insert a Table and float it left so it's the first piece of content
6. Select a cell in the table so that Table's balloon toolbar appears
7. Click Font Family dropdown

### ✔️ Expected result

Table balloon toolbar should probably hide itself while main toolbar has focus, or there should be some collision logic or lower z-index than main toolbar content displayed.

### ❌ Actual result

Table balloon toolbar appears over main toolbar content.
![image](https://user-images.githubusercontent.com/22718637/83217131-85972a00-a130-11ea-9a44-32dc57235cd4.png)

And here's another example from: [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html](url)
![image](https://user-images.githubusercontent.com/22718637/83217565-b1ff7600-a131-11ea-8afd-54f1980a8fd0.png)

## 📃 Other details

* Browser: Chrome 83
* OS: Windows
* CKEditor version: 5
* Installed CKEditor plugins: FontFamily, Table, TableToolbar

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by otherblandart** [comment]
I believe other balloon toolbars (Image, for example) behave similarly.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this issue and we are [tracking it here](https://github.com/ckeditor/ckeditor5/issues/6220). If you want to add anything there, please feel free to do so. I'll close this one as a duplicate.
