### ISSUE TITLE
Allow linking images - update guides

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7332]
## 📝 Provide a description of requested docs changes

Showcase new feature in the docs somehow :)

*   Where to include the "main" guide (link, image or both)?
    * it should rather land in image guide as a new section (this guide is done in an "incremental" docs).
    * minimal in link guide: common API section
*   Link those guides together.
*   How to best showcase this feature (good example - real use-case).

**Comment by Reinmar** [comment]
Closed with 0ce93e8030. The styling is bad, but it's ok for now.

**Comment by Reinmar** [comment]
![](https://user-images.githubusercontent.com/156149/85532067-ab203200-b60f-11ea-98e6-29701a0d3fd1.png)

**Comment by Reinmar** [comment]
![](https://user-images.githubusercontent.com/156149/85532446-ff2b1680-b60f-11ea-932b-3c15b185d7e7.png)
