### ISSUE TITLE
handle of content style

### ISSUE THREAD

**Issue by zhangtaoBqteam** [ckeditor/ckeditor5#7333]
## Provide a description of the task
there are some style descriptions, such as image, text and editor builds. Is there any elegant way to handle all of these styles, which can prettify the editor, just like the demo at https://ckeditor.com/ckeditor-5/demo/#document
## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If you want your editor to look like in the demo, please check _html_ and _styles_ sections in [ document editor docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html#the-editor). There you can find CSS used to style it this way.

**Comment by zhangtaoBqteam** [comment]
thank you so much
