### ISSUE TITLE
Coping and pasting table rows doesn't work in CKEditor5

### ISSUE THREAD

**Issue by szamanm** [ckeditor/ckeditor5#7335]
## 📝 Provide detailed reproduction steps (if any)

Inside CKEditor 5 (i.e. here: https://ckeditor.com/ckeditor-5/demo/ )
1. Create any table, at least 2x2, fill it with some random data
2. Select first, entire row and copy to clipboard
3. select another row (or just first cell) and paste it

### ✔️ Expected result

The row should be pasted, or created below selection. The same scenario works fine with CKEditor4 ( from here: https://ckeditor.com/ckeditor-4/demo/ )

### ❌ Actual result

It seems that nothing happens, just like the clipboard is empty

## 📃 Other details

* Browser: Checked Chrome (81), Safari (13.1) and Firefox (76)
* OS: Mac
* CKEditor version: 5
* Installed CKEditor plugins: none

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Pasting table rows has been introduced in the latest release, however, our demo still uses v19.0.0. We will update it soon.

The latest version of the editor can be found in our documentation examples, so in the meantime, you can play with a feature [here](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#demos).

**Comment by szamanm** [comment]
Ah, great, that explains why I couldn't find any open report about that ;). Thank you for your explanation!
