### ISSUE TITLE
Page design issue in 'utils' document page.

### ISSUE THREAD

**Issue by ankitcodefarm** [ckeditor/ckeditor5#7337]
## 📝 Provide a description of requested docs changes
Looking for any help for adding the alphabet in the number list and found this little design issue in documentation.
so I have added here. Below are the link and screenshot.

if this the wrong place to add this kind of issue, please pardon me for this.

Browser: crome

The below link has some design issues.
[https://ckeditor.com/docs/ckeditor5/latest/api/module_list_utils.html](url)

_What is the purpose and what should be changed?_
![image](https://user-images.githubusercontent.com/37925504/83259068-07d92a00-a1d5-11ea-92e6-f2bff89b19c0.png)

**Comment by Mgsy** [comment]
cc @pomek

**Comment by Reinmar** [comment]
Thanks @ankitcodefarm. I'm moving this under the devops team.

**Comment by pomek** [comment]
`<li>` should be escaped.

https://github.com/ckeditor/ckeditor5/blob/987265215d21f80277881173ac76ef7688135d15/packages/ckeditor5-list/src/utils.js#L29-L30

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/88807409-f949c780-d1b1-11ea-825c-71dfe69e92dd.png)
