### ISSUE TITLE
ckeditor 5 online builder, editor produces error when using math type plugin

### ISSUE THREAD

**Issue by ahmedosama5200** [ckeditor/ckeditor5#7338]
## 📝 Provide detailed reproduction steps (if any)

1.use ckeditor 5 online builder and include math type plugin
2.run the sample/index.html file provided
3. you will see an error in the console and the editor doesn't show up at all

### ✔️ Expected result

the editor is supposed to show

### ❌ Actual result

a placeholder image appear along with an error
![Capture](https://user-images.githubusercontent.com/31630951/83260460-1c5bf900-a1ba-11ea-9fb2-670ae531a1d5.PNG)

## 📃 Other details

* Browser: chrome
* OS: windows
* CKEditor version: 5
* Installed CKEditor plugins: default selected plugins by online editor in addition to math type plugin

**Comment by Mgsy** [comment]
Hi, it seems that you open `index.html` directly from your browser. MathType is making requests to an external service and your browser doesn't allow it while using `file://` protocol. Try to create a simple HTTP server (e.g. using node `http-server`) and open the sample using HTTP protocol.

**Comment by ahmedosama5200** [comment]
I intent to use the editor for my android app using a webview component, so, I am loading it locally not from a server. Other plugins work fine, only math type is not working ? How can I make it work ? I am not an expert with node js, so can you, please, explain what I need to do ?

**Comment by ahmedosama5200** [comment]
I was able to run the app on android using an https server, but I am unable to run it on desktop. Can you help me with that ?

**Comment by Mgsy** [comment]
\>I was able to run the app on android using an https server, but I am unable to run it on desktop. Can you help me with that ?

You should do it the same way. You can use [http-server](https://www.npmjs.com/package/http-server) module to create a simple HTTP server in your project directory.
