### ISSUE TITLE
CKEditorError is printed without a link to the docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7339]
## 📝 Provide detailed reproduction steps (if any)

![](https://user-images.githubusercontent.com/156149/83260471-241b9d80-a1ba-11ea-8fbb-951795d17778.png)

I don't know if that's happening in all scenarios, so here goes a code that causes this:

```
		editor.conversion.for( 'dataDowncast' ).elementToElement( {
			model: 'paragraph',
			view: ( modelElement, viewWriter ) => {
				const viewContainer = viewWriter.createContainerElement( 'p' );

				viewWriter.insert( viewWriter.createPositionAt( viewContainer, 0 ), null );

				return viewContainer;
			}
		} );
```

This is a deal that the link isn't printed out.

My guess is that the error is swallowed somewhere by our code that was supposed to intercept errors.

When I throw the error into the global scope it gets printed nicely:

![](https://user-images.githubusercontent.com/156149/83260802-b02dc500-a1ba-11ea-8557-464d327d9ed1.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @ma2ciek

**Comment by ma2ciek** [comment]
That happens probably because of [this issue](https://github.com/ckeditor/ckeditor5/issues/5643).
