### ISSUE TITLE
Built-from-source React implementation doesn't work with Next.js

### ISSUE THREAD

**Issue by sethcwhiting** [ckeditor/ckeditor5#7343]
Hi! First of all, thank you so much for all of your hard work on this project. I think your service could to save my team a lot of work!

Right now, we're trying to assess whether or not to use CKEdit for our project, which we're building on top of Next.js. We need to make use of the Comments and Tracked Changes add-ons you offer. I found [this sample application](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/track-changes-for-react) you provide, and I'm currently trying to include it in our project, but I'm running into over 100 errors in my console, all relating to the same issue:

```
./node_modules/@ckeditor/ckeditor5-block-quote/theme/blockquote.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@ckeditor/ckeditor5-block-quote/src/blockquoteui.js
```

Following the link that Next provides in that error, the solution they propose is as follows:

> **Possible Ways to Fix It**
>Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
>
>Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations.
>
>The dependency should also provide instructions about what CSS needs to be imported by you, in your application.
>
>Importing CSS files within node_modules cannot be supported because we cannot know the correct behavior:
>
> - Should the file be consumed as Global CSS or CSS Modules?
> - If Global, in what order does the file need to be injected?
> - If Modules, what are the emitted class names? As-is, camel-case, snake case?
> - Etc...

As I said, we're at the point where trying to decide right now whether to spend several hundreds of dollars a month on your premium plugins or to spend several dozens of man hours trying to build something custom ourselves. If you could resolve this issue for us, it would make our decision - and the decision of any other teams trying to use your service with Next.js in the future - much easier.

Thanks again!

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thank you for the report. I've opened a [feature request for Next.js integration](https://github.com/ckeditor/ckeditor5/issues/7376), so let's move the discussion there.
