### ISSUE TITLE
ckeditor 5 some toolbar items are off screen on android webview

### ISSUE THREAD

**Issue by ahmedosama5200** [ckeditor/ckeditor5#7344]
## 📝 Provide detailed reproduction steps (if any)

1. use ckeditor 5 online builder and load the file using webview component in android
2. run the app on your android phone
3. open the ckeditor overflow menu

### ✔️ Expected result

I expect to see all toolbar items, at lease be able to scroll to see them all

### ❌ Actual result

Some items are off screen as seen in this image(more specifically the items on left) :
![Screenshot_20200530-133047_College Connect](https://user-images.githubusercontent.com/31630951/83327337-1f6aee00-a27b-11ea-91a7-96252c1d1839.jpg)

## 📃 Other details

* Browser: android webview
* OS: android
* CKEditor version: 5
* Installed CKEditor plugins: most of them except for real time collborative editing plugins

---

**Comment by Mgsy** [comment]
Hi, thanks for the report. We're aware of this issue, you can find more information [here](https://github.com/ckeditor/ckeditor5/issues/5586). Feel free to add :+1: to the first post to bump its popularity.

**Comment by ahmedosama5200** [comment]
When is this gonna be fixed, it's been open [here](https://github.com/ckeditor/ckeditor5/issues/5586) since Oct 15, 2019 and It seems like a high priority bug to me since users with small screen sizes won't be able to use some of the toolbar items
