### ISSUE TITLE
Toolbar button callback

### ISSUE THREAD

**Issue by ahmedosama5200** [ckeditor/ckeditor5#7345]
## 📝 Provide a description of requested docs changes

I searched the docs for a way to get notified(callback function) when a toolbar button is clicked but I couldn't find a way to do it ? I really need that in my app. is there a way to do that ?

**Comment by Mgsy** [comment]
Hi, if you're working on your custom plugin, you should listen to [`execute`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_buttonview-ButtonView.html#event-execute) event on your [`ButtonView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_buttonview-ButtonView.html) element. However, if you'd like to do it on an existing item, the easiest way will be listening on a command execution. Here is the example:

```
const command = editor.commands.get( 'Bold' );

command.on( 'execute', () => {
	console.log( 'Bold has been executed' );
};
```

Commands are executed after clicking on a toolbar item, so it should cover your case.

**Comment by ahmedosama5200** [comment]
Thanks. That should be included in the docs, though
