### ISSUE TITLE
[Edge] Editor crashes after using keyboard navigation

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#735]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Select two block elements.
3. Press <kbd>Alt</kbd> + <kbd>F10</kbd>.
4. Press <kbd>Enter</kbd>.

## ✅ Expected result

Dropdown should reveal.

## ❎ Actual result

Selected elements disappear and the editor crashes.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/34160225-62943570-e4cc-11e7-95a3-4563b77a0013.gif)

**Error**
```
 SCRIPT5007: SCRIPT5007: Unable to get property 'parent' of undefined or null reference
```

**Notes**

There is no possibility to use the toolbar with keyboard. Sometimes editor crashes and sometimes it reloads the page. I noticed also this error:
```
SCRIPT5022: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-nodelist-offset-out-of-bounds
```

It's reproducible in http://ckeditor5.github.io.

**Other information**
OS: Windows 10
Browser: Edge

**Comment by Reinmar** [comment]
Is it reproducible with the console closed? Edge's console makes it super unstable.

**Comment by Mgsy** [comment]
> Is it reproducible with the console closed? Edge's console makes it super unstable.

Yep, I'm aware of this fact. Unfortunately, this one occurs with closed console as well.

**Comment by Mgsy** [comment]
It turned out that this behaviour occurs because of the `Caret Browsing` mode. I will move it to the umbrella ticket - https://github.com/ckeditor/ckeditor5/issues/738.
