### ISSUE TITLE
Karma web-server logs 404 warning

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7350]
## 📝 Provide detailed reproduction steps (if any)

1. `yarn run test --reporter=dots`

### ✔️ Expected result

Clean output.

### ❌ Actual result

Some 404 warnings are visible in the console.

![image](https://user-images.githubusercontent.com/2270764/83387569-37627f00-a3ed-11ea-9d2d-1a19e583fea2.png)

### A solution:

Use `*.png` instead of `*.jpg`.

![image](https://user-images.githubusercontent.com/2270764/83387620-4e08d600-a3ed-11ea-9b4d-8ef8f4598f1e.png)

**Comment by Reinmar** [comment]
Let's check these tests that use jpg files whether they couldn't use these png assets that we provide. If not, we can add more assets.

If the problem is elsewhere and not trivial to fix (e.g. it's expected in the test to use a nonexistent file), let's forget about this ticket.
