### ISSUE TITLE
[Chrome/Safari] Icons in toolbar remain pressed after using spacebar in specific way

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#736]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Focus the editor.
3. Press <kbd>Alt</kbd> + <kbd>F10</kbd>.
4. Move focus to bold icon.
5. Press and hold <kbd>Spacebar</kbd>.
6. At the same time press <kbd>Arrow right</kbd>.

## ✅ Expected result

The icon should return to the default state.

## ❎ Actual result

The icon remains pressed.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/34162497-3c61e8b8-e4d4-11e7-9e9f-c7d8470a3aac.gif)

**Other information**
OS: Windows 10, MacOS X
Browser: Chrome, Safari

**Comment by Reinmar** [comment]
Can it be that new icons styling? We might've woken a devil with it...

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
> Press and hold Spacebar.
> **At the same time** press Arrow right.

Checked that out. This is a complete edge case. Why would anyone keep pressing spacebar and press an arrow key at the same time? It's Blink/Webkit only, besides.

**Comment by oleq** [comment]
Check out the [fiddle](https://jsfiddle.net/oleq/4zwt2n18/). 

1. Press Tab to focus the first button. 
2. Press and hold the spacebar. 
3. Press Tab to move to the second button. 

The first one remains in the pressed state.
