### ISSUE TITLE
editor.model.change return TypeError: editor.model.change is not a function

### ISSUE THREAD

**Issue by ZakaGn** [ckeditor/ckeditor5#7361]
Hi, i get TypeError: editor.model.change is not a function
when i try to use editor.model.change(writer => {insertImage(writer,editor.model,'src:"sdfgsdf/sdfsdf.jpg"');});

am I doing it wrong? how to access editor.model.change in this case?
this is my Code:

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import Heading from "@ckeditor/ckeditor5-heading/src/heading";
import {insertImage} from "@ckeditor/ckeditor5-image/src/image/utils";
export default function(Id){
	if(Id.length){
		ClassicEditor
			.create( document.querySelector( '#'+Id), {
				plugins: [Essentials, Heading, CKFinder],
				toolbar: ['heading', 'ckfinder',],
				ckfinder: {options: {onInit: MyFunc, resourceType: 'Images'}}
			})
			.then(editor => {/**/})
			.catch(error => {console.error(error);})
		;

		function MyFunc(finder){
			finder.on( 'toolbar:reset:Main:file', function(evt){
				if(evt.data.file.isImage()){
					evt.data.toolbar.push({
						name: 'ImageInfo',
						type: 'button',
						priority: 150,
						icon: 'ckf-details',
						label: 'Image Info',
						action: displayImageInfo
					});
				}
			});

			function displayImageInfo(editor){
				editor.model.change(
					writer => {
						insertImage(
							writer,
							editor.model,
							'src:"sdfgsdf/sdfsdf.jpg"'
						);
					}
				);
			}
		}

	}
}

**Comment by ZakaGn** [comment]
Thank you @Mgsy ,  

well in the editor is loaded perfectly, but not in ckfinder, 
i guess this is not a place to ask about ckfinder right?

 MyFunc is loaded in ckfinder,
ckfinder: {options: {onInit: MyFunc, resourceType: 'Images'}}

and is there where "editor.model.change" is not working,

while in the editor directly is working 100%

**Comment by FilipTokarski** [comment]
Hi, it seems like the problem here is, that `MyFunc` has no access to the editor instance. So when you are calling `editor.model.change` inside it, it doesn't know what `editor` is.
One way of resolving this, is to attach editor instance to window object:
```js
ClassicEditor.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
```
This way you will be able to retrieve editor instance inside `MyFunc` and `displayImageInfo`.
Hope that helps.

**Comment by ZakaGn** [comment]
@FilipTokarski yes that what should happen, but i cant get it, here is the code used, and here is some outputs that may be helps:

![code2](https://user-images.githubusercontent.com/57212541/83624402-d96f9c00-a592-11ea-8e65-2b3cfed48156.jpg)

![Editor2](https://user-images.githubusercontent.com/57212541/83624462-f2784d00-a592-11ea-82a9-5c7dd01940be.jpg)

**Comment by ZakaGn** [comment]
ok Sorry that was my error, now i get it, but i get a new error about iterator, here is the code again and the result

![code3](https://user-images.githubusercontent.com/57212541/83625376-1daf6c00-a594-11ea-97d4-5db1a890dd9d.jpg)

![editor3](https://user-images.githubusercontent.com/57212541/83625392-24d67a00-a594-11ea-8bca-471945f01753.jpg)

**Comment by FilipTokarski** [comment]
This iteration error most likely comes from wrong usage of `insertImage` utils function. You can see [in the docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils.html#static-function-insertImage) that the third argument should be an object with options, whereas in your code, you just pass a string. So please try like this:
```js
insertImage(
    writer,
    editor.model,
    { src: "media/image.jpg" }
);
```
That should do the trick.

P.S.
In the future please don't paste here images of your code, but rather the code itself. It will be easier for us when copying and debugging things.

**Comment by ZakaGn** [comment]
Wow it working 100%, what a stupid error i have made, thank you very much for your help, i m sorry for the images, this is the first time ever i have posted a question in github hhh so i had no idea about that, thank you again :)

**Comment by FilipTokarski** [comment]
No problem, I'm happy to hear that it works now 🙂  I'll close this ticket as solved.
