### ISSUE TITLE
editor.getData() returns html content without styles

### ISSUE THREAD

**Issue by ahmedosama5200** [ckeditor/ckeditor5#7363]
## 📝 Provide a description of requested docs changes

I am using the method mentioned [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#manually-retrieving-the-data) to manually retrieve data from the editor in javascript . I noticed that they don't have the same style as they were when editing. For example, image caption is to the left not in the middle. Also, Code blocks don't have that dark background or the tag showing the language used. It's just a `code tag` inside a `pre tag`. so, What am I missing ?

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not sure what is the use case here, so I'll give you two explanations:
1. If you want editor to return html with inline styles, this is unfortunately unavailable currently. We have a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/1627), so feel free to add anything you want to discussion there and add a 👍 .
2. `getData()` returns html with appropriate ckeditor css classes. So to style this content the same as in editor, you can make use of [content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html).

I hope this helps!

**Comment by ahmedosama5200** [comment]
I copied the contents [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#the-full-list-of-content-styles) into a separate file and linked it to my html. still the styles are not the same as the editor.

**Comment by ahmedosama5200** [comment]
Thanks, it worked.
I don't think this should be a feature because separating the style from the html will make the string saved to the back-end much smaller, since all of them will have the same style.
However, that should be well-noted in the documentation of getting the editor data
