### ISSUE TITLE
Next.js integration

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#7376]
## 📝 Provide a description of the new feature

Provide a guide for integrating CKEditor 5 with [Next.js](https://nextjs.org/).

**[Update 2 from @Witoso]**

New installation methods shipped in [v42.0.0](https://github.com/ckeditor/ckeditor5/releases/tag/v42.0.0) work seamlessly with Next.js. Check [Next.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/next-js.html).

**\[Update\]**

Hello everyone 👋!

We published an article in our docs, about the [Next.js integration](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/next-js.html). I want to thank community members that shared the examples below.

That said, there's still work in front of us to make this integration smoother. And we aim to fix it in its roots. I invite everyone to check our new installation methods RFC: [#15502](https://github.com/ckeditor/ckeditor5/issues/15502).

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Currently, it's [not possible](https://github.com/ckeditor/ckeditor5/issues/7343) to build the editor from the source using Next.js. I think it's related to a webpack configuration and Next.js webpack config requires some adjustments to make it compatible with CKEditor 5.

However, it's possible to run CKEditor 5 **build** inside Next.js application. To everyone struggling with the integration, please check the below workaround based on [StackOverflow](https://stackoverflow.com/a/58576912/7280974) answer:

*   Create a new Next.js application using `create-next-app`.
*   In your Next.js project run:

```shell
npm install --save @ckeditor/ckeditor5-build-classic @ckeditor/ckeditor5-react
```

*   Paste the following code to your `pages/index.js` file:

```javascript
import React, { useState, useEffect, useRef } from 'react'

export default function MyEditor () {
  const editorRef = useRef()
  const [ editorLoaded, setEditorLoaded ] = useState( false )
  const { CKEditor, ClassicEditor } = editorRef.current || {}

  useEffect( () => {
    editorRef.current = {
      CKEditor: require( '@ckeditor/ckeditor5-react' ),
      ClassicEditor: require( '@ckeditor/ckeditor5-build-classic' )
    }
    setEditorLoaded( true )
  }, [] )

  return editorLoaded ? (
    <CKEditor
      editor={ ClassicEditor }
      data='<p>Hello from CKEditor 5!</p>'
      onInit={ editor => {
        // You can store the "editor" and use when it is needed.
        console.log('Editor is ready to use!', editor)
      } }
      onChange={ (event, editor ) => {
        const data = editor.getData()
        console.log( { event, editor, data } )
      } }
    />
  ) : (
    <div>Editor loading</div>
  )
}
```

*   Run `yarn dev` and open the application.

The above solution uses our official classic editor build, however, you can [customize a build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) "outside of the Next.js integration" and load it the same way. Also, you can use [CKEditor 5 online builder](https://ckeditor.com/ckeditor-5/online-builder/) to get a ready-to-use build with a set of desired plugins.

**Comment by seta-hainguyen** [comment]
@Mgsy your solution works fine with basic use but got errors when I integrated with CKEditor Plugins like Easy Image or Alignment. Seems regarding to webpack configurtion:


_error - ./node_modules/@ckeditor/ckeditor5-ui/theme/icons/dropdown-arrow.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
`
> <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg"><path d="M.941 4.523a.75.75 0 1 1 1.06-1.06l3.006 3.005 3.005-3.005a.75.75 0 1 1 1.06 1.06l-3.549 3.55a.75.75 0 0 1-1.168-.136L.941 4.523z"/></svg>
Could not find files for /dashboard in .next/build-manifest.json
ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

**Comment by FilipaBarroso** [comment]
I was trying to follow the tutorial to [create a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) but I'm having the issue in #7343, because of the @ckeditor/ckeditor5-ui and @ckeditor/ckeditor5-core packages.

Could you please provide compiled packages or a workaround for this?

Thanks for your attention.

**Comment by sethcwhiting** [comment]
@Mgsy Just for context, Filipa is on my team (I'm the guy who originally raised the issue). We were doing great with the online build tool for a while, but we're now at the point where we need to add our own plug-in and the online build has become insufficient for our needs. If there's any way you could push offering compiled versions of your individual packages up your priority list, that would help us out tremendously. Until then, we'll probably need to handle this in some hacky way, which we really don't want to do. Thanks so much!

**Comment by adrianmaycon** [comment]
How do I enable the upload image option?

**Comment by wwalc** [comment]
Might be useful: https://medium.com/@aisynurul99/custom-ckeditor-5-next-js-d6ef5cc7dd93 (did not review it)

**Comment by perezjoyce** [comment]
> @Mgsy your solution works fine with basic use but got errors when I integrated with CKEditor Plugins like Easy Image or Alignment. Seems regarding to webpack configurtion:
> 
> _error - ./node_modules/@ckeditor/ckeditor5-ui/theme/icons/dropdown-arrow.svg 1:0
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
> > Could not find files for /dashboard in .next/build-manifest.json
> > ModuleParseError: Module parse failed: Unexpected token (1:0)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See [https://webpack.js.org/concepts#loaders`](https://webpack.js.org/concepts#loaders%60)

Did you find a workaround for this?

> @Mgsy your solution works fine with basic use but got errors when I integrated with CKEditor Plugins like Easy Image or Alignment. Seems regarding to webpack configurtion:
> 
> _error - ./node_modules/@ckeditor/ckeditor5-ui/theme/icons/dropdown-arrow.svg 1:0
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
> > Could not find files for /dashboard in .next/build-manifest.json
> > ModuleParseError: Module parse failed: Unexpected token (1:0)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See [https://webpack.js.org/concepts#loaders`](https://webpack.js.org/concepts#loaders%60)

I have the same issue. Were you able to resolve this?

**Comment by hscstudio** [comment]
Solve with this simple step

1. Install ckeditor `yarn install @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic`
2. Wrap ckeditor as a component, create new file `src/components/Editor.js`

```js
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import CKEditor from '@ckeditor/ckeditor5-react';

const Editor = (props) => {
  return (
    <CKEditor
      editor={ ClassicEditor }
      data={props.value}
      onChange={ (event, editor ) => {
        const data = editor.getData()
        props.onChange(data)
      } }
    />
  )
}

export default Editor;
```

3. On `src/pages`, use component Editor like this

```js
import dynamic from 'next/dynamic'

const Editor = dynamic(() => import('../components/editor'), { ssr: false })

const Home = () => {
  return (
    <Editor value="" onChange={(v)=> console.log(v)} />
  )
}
export default Home;
```

**Comment by jorissparla** [comment]
@hscstudio @Mgsy both solutions result in an **unhandled Runtime Error**
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `MyEditor`.

Call Stack
createFiberFromTypeAndProps
node_modules\react-dom\cjs\react-dom.development.js (25058:0)
`  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^24.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.0",
    "next": "10.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }`

**Comment by hscstudio** [comment]
> @hscstudio @Mgsy both solutions result in an **unhandled Runtime Error**
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of `MyEditor`.
> 
> Call Stack
> createFiberFromTypeAndProps
> node_modules\react-dom\cjs\react-dom.development.js (25058:0)
> ` "dependencies": { "@ckeditor/ckeditor5-build-classic": "^24.0.0", "@ckeditor/ckeditor5-react": "^3.0.0", "next": "10.0.3", "react": "17.0.1", "react-dom": "17.0.1" }`
> 
> **AND**
> 
> **Unhandled Runtime Error**
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `Editor`.

Show your code?

**Comment by jorissparla** [comment]
Here it is https://github.com/jorissparla/x. Very basic.

**Comment by hscstudio** [comment]
> Here it is https://github.com/jorissparla/x. Very basic.
Maybe error from code in pages/index.js, remove pages/index.js and rename pages/home.js to be pages/index.js

**Comment by jorissparla** [comment]
> > Here it is https://github.com/jorissparla/x. Very basic.
> > Maybe error from code in pages/index.js, remove pages/index.js and rename pages/home.js to be pages/index.js

![runtime](https://user-images.githubusercontent.com/16277487/102333703-11b65500-3f8e-11eb-96bb-be04d6474cd3.png)

**Comment by hscstudio** [comment]
@jorissparla 

change in Your packages to this version `"@ckeditor/ckeditor5-react": "^1.1.0",` and then npm install

**Comment by jorissparla** [comment]
that worked, Also the second link worked. Need to play around to see what is causing the issues in my basic example.
Thank you!!!

**Comment by jorissparla** [comment]
moving from   "@ckeditor/ckeditor5-react": "^2.1.0", to  "@ckeditor/ckeditor5-react": "^3.0.0", breaks the example. Will file a bug report

**Comment by afk-mario** [comment]
Customized editor (with plugins) was really easy following the [following docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds) and using the online builder.

**Comment by OrionLayton** [comment]
@afk-mario Would you mind sharing how you got CKEditor plugins working with Next? I keep running into the "Global CSS cannot be imported from within node_modules" error when trying to set up ExportPdf.

**Comment by afk-mario** [comment]
@OrionLayton

- Use the [CKEditor online builder](https://ckeditor.com/ckeditor-5/online-builder/) to select the plugins that you want with your editor
- Download the customized editor in the final step of the builder
- Uncompressed the zip file
- Place it in you repo the docs recommend to put it at the same level as you `node_modules`
- Run `yarn add file:./ckeditor5` (ckeditor5 is the default name of the uncompressed zip build)
- Import the ck custom editor on your react app

```jsx
import React, { Component } from 'react';
// When you add the ckeditor5 folder you can import it this way
import Editor from 'ckeditor5-custom-build/build/ckeditor';
import { CKEditor } from '@ckeditor/ckeditor5-react'

const editorConfiguration = {
    toolbar: [ 'bold', 'italic' ]
};

function Editor  ()  {
        return (
          <CKEditor
              editor={ Editor }
              config={ editorConfiguration }
              data="<p>Hello from CKEditor 5!</p>"
              onChange={ ( event, editor ) => {
                  const data = editor.getData();
                  console.log( { event, editor, data } );
              }
          />
    );
}

export default Editor;
```

Finally when you import this component make sure you are skipping server side rendering.

```jsx

import React from 'react';
import dynamic from 'next/dynamic';

const Editor = dynamic(() => import('./components/editor'), {
  ssr: false,
});

function App = () => {
  return (
    <div>
      <Editor />
    </div>
  );
};

export default App;
```

If you need plugins outside of the ones that the online builder has support for I think you can create a custom build by yourself but didn't tried that, the process after getting the custom build should be similar.

**Comment by Emyboy** [comment]
@Mgsy I'm getting `window is not defined` when I build


and get this during development.
![image](https://user-images.githubusercontent.com/34845973/111865728-f716c200-8968-11eb-9a50-09567e84902c.png)

**Comment by dtakeshta** [comment]
@hscstudio solution works, but for 3.0.0 you need to modify the import of ckeditor-react to:

`import { CKEditor } from "@ckeditor/ckeditor5-react";`

**Comment by jeffryang24** [comment]
From my experiment, I got `ReferenceError: window is not defined` when running `next build` if I implemented custom `_app.js` file with some server-side data fetching method, such as `getInitialProps`. The build didn't fail when I remove my custom `_app.js` implementation. Ya... This is actually so annoying... :disappointed: 

```js
// // pages/_app.js (got from nextjs documentation: https://nextjs.org/docs/advanced-features/custom-app)
// Only uncomment this method if you have blocking data requirements for
// every single page in your application. This disables the ability to
// perform automatic static optimization, causing every page in your app to
// be server-side rendered.
//
// MyApp.getInitialProps = async (appContext) => {
//   // calls page's `getInitialProps` and fills `appProps.pageProps`
//   const appProps = await App.getInitialProps(appContext);
//
//   return { ...appProps }
// }
```

**Comment by jeffryang24** [comment]
Finally, I used cancellablePromise, React Mutable Ref, and dynamic import to solve that. But, currently I'm facing a performance issue when rendering more than 10 CKEditor with dynamic import, this will make the browser unresponsive. Still find a way to minimize this performance issue.

- [cancellablePromise](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html), to cancel the async operation before the component unmount.
- React mutable ref, to store the CKEditor5-react and CKEditor-Inline-Editor import.
- Dynamic import, to import the module in demand.

**Comment by sunkid1995** [comment]
> I was trying to follow the tutorial to [create a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) but I'm having the issue mentioned in #7343, because I'm importing the @ckeditor/ckeditor5-ui and @ckeditor/ckeditor5-core packages. I assume the same issue will arise in other packages as well, for anyone working with Next.js.
> 
> Could you please provide compiled packages or a workaround for this?
> 
> Thanks for your attention.

same issue!

**Comment by mtkFreexe** [comment]
Is there any answers for ck editor plugin(Font) integration in Nextjs

**Comment by jsbimra** [comment]
> Just wanted to throw my two cents in this thread. I integrated CKEditor into Next using the `next/dynamic` component with `{ssr:false}` in the options. However, I was still getting weird errors. I was using it in a page, on `src/pages/ckeditor.js` just to test. Turns out that utilizing that route breaks CKEditor. Once I renamed that route, everything worked fine.

Worked for me too! Have you able to get all the options? can we see like (git editor) when we are replying on Git Thread here? I am just seeing Bold and Italic option only. 
I tried implementing:  plugins: [ Essentials, Bold, Italic, Paragraph ], but I get error: 

`./node_modules/@ckeditor/ckeditor5-clipboard/theme/clipboard.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@ckeditor\ckeditor5-clipboard\src\dragdrop.js`

**Comment by jsbimra** [comment]
> > Just wanted to throw my two cents in this thread. I integrated CKEditor into Next using the `next/dynamic` component with `{ssr:false}` in the options. However, I was still getting weird errors. I was using it in a page, on `src/pages/ckeditor.js` just to test. Turns out that utilizing that route breaks CKEditor. Once I renamed that route, everything worked fine.
> 
> Worked for me too! Have you able to get all the options? can we see like (git editor) when we are replying on Git Thread here? I am just seeing Bold and Italic option only. I tried implementing: plugins: [ Essentials, Bold, Italic, Paragraph ], but I get error:
> 
> `./node_modules/@ckeditor/ckeditor5-clipboard/theme/clipboard.css Global CSS cannot be imported from within node_modules. Read more: https://nextjs.org/docs/messages/css-npm Location: node_modules\@ckeditor\ckeditor5-clipboard\src\dragdrop.js`

Found it with toolbar options here: https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/toolbar.html#automatic-toolbar-wrapping
not sure why those error for plugins! 👍

**Comment by lazarok09** [comment]
## The 'media embed' plugin works with the React component and Next.js ?

I have a builded editor, i created following [ckeditor 5create online builder](https://ckeditor.com/ckeditor-5/online-builder/) But, the embed video only shows on the editor, the source code that is generated when i get it on `getData()` is different

### The React component
![image](https://user-images.githubusercontent.com/45147892/154482751-1fac41ab-3878-49d7-8d96-f13b1eff60a8.png)

###  The problem

When the editor convert the embed to a html code, is failing, getting me just this code when i use  `getData()`.

`<figure class="media"><oembed url="https://www.youtube.com/watch?v=4zAThXFOy2c&amp;feature=emb_title"></oembed></figure>` 

**This is not right at all. It should be like a figure tag, some divs.. a <iframe/> etc.** 

Take a look how it is  when we inspect the html code with the editor opened

![image](https://user-images.githubusercontent.com/45147892/154487441-09db83be-19a4-4ced-989d-7e0b9bb56469.png)

### getData
This function should return the html source of our editor, but the part of convert embed to an html, is a complet failure
* Here the code generated with `getData()` function is just this:
![image](https://user-images.githubusercontent.com/45147892/154487603-bad35ea2-6c7d-471e-b04b-b5be9e85cf4e.png)



Someone can help with it?

**Comment by laurencefass** [comment]
https://github.com/ckeditor/ckeditor5/issues/7376#issuecomment-743113027 fixed it for me. Thanks.

**Comment by tetaplaun** [comment]
> > Just wanted to throw my two cents in this thread. I integrated CKEditor into Next using the `next/dynamic` component with `{ssr:false}` in the options. However, I was still getting weird errors. I was using it in a page, on `src/pages/ckeditor.js` just to test. Turns out that utilizing that route breaks CKEditor. Once I renamed that route, everything worked fine.
> 
> Worked for me too! Have you able to get all the options? can we see like (git editor) when we are replying on Git Thread here? I am just seeing Bold and Italic option only. I tried implementing: plugins: [ Essentials, Bold, Italic, Paragraph ], but I get error:
> 
> `./node_modules/@ckeditor/ckeditor5-clipboard/theme/clipboard.css Global CSS cannot be imported from within node_modules. Read more: https://nextjs.org/docs/messages/css-npm Location: node_modules\@ckeditor\ckeditor5-clipboard\src\dragdrop.js`

Any news on this issue? Any workaround?

**Comment by lazarok09** [comment]
@tetaplaun you're using a build ? if not, try make yours here on https://ckeditor.com/ckeditor-5/online-builder/
after that, you can just add the editor with npm 
1 - extract the builder
2 - rename the path to ckeditor5
3 - add with `npm add file:./ckeditor5` or `npm add @file:./ckeditor5`

**Comment by tetaplaun** [comment]
> 

Yes, I'm using one of the prebuild configuations. The problem is, that once I integrate the "WProofreader" plugin, the mentioned error message ("Global CSS cannot be imported from within node_modules") appears.

**Comment by lazarok09** [comment]
@tetaplaun Are you using a build ? if not, try make yours here on https://ckeditor.com/ckeditor-5/online-builder/
after that, you can just add the editor with npm 
1 - extract the builder
2 - rename the path to ckeditor5
3 - add with `npm add file:./ckeditor5` or `npm add @file:./ckeditor5`

Once you already have your editor, can import him in your component 
```
 
// When you add the ckeditor5 folder you can import it this way
import Editor from 'ckeditor5-custom-build/build/ckeditor';
import { CKEditor } from '@ckeditor/ckeditor5-react';
export default function CEditor({ htmlData, setData }: any) {
  return (
    <CKEditor
      editor={Editor}
      data={htmlData}
      onChange={(_event, editor) => {
        const data = editor.getData();
        console.log(data);
        setData(data);
      }}
    />
  );
}
```

Remember to import dynamic on your component page

```
const CEditor = dynamic(() => import('../../components/Editor'), {
ssr: false,
});
```

const Page() {
const [data, setData] = useState();

return (
<div>
 <CEditor
          htmlData={'<h1>Hello World</h1>'}
          setData={setData}
        />
</div>
)
}

**Comment by lazarok09** [comment]
> Global CSS cannot be imported from within node_modules

may it help you https://github.com/vercel/next.js/discussions/27953

**Comment by tetaplaun** [comment]
> > Global CSS cannot be imported from within node_modules
> 
> may it help you [vercel/next.js#27953](https://github.com/vercel/next.js/discussions/27953)

Unfortunately, the problem is not solved yet, but thanks for the link!

**Comment by digitriss** [comment]
The issue's still occured, when I want to use plugins like "Alignment, Image". This only work for "italic and bold" unfortunatly.  Anybody fix it or has some worked code?

**Comment by viperfx** [comment]
Also looking for a official support from CKEditor team on supporting nextjs and CKEditor source builds without webpack hacks and tons of workarounds.

**Comment by amirshnll** [comment]
in my case i used

**Comment by amirshnll** [comment]
in my case i used custom build ckeditor version. my reference:

`https://github.com/tranvanhuyhoang/nextjs-custom-ckeditor5/tree/master/`

**Comment by deokchanjeong** [comment]
Uploaded an [example project](https://github.com/deokchanjeong/nextjs-ckeditor5-example) to my repository.
I hope it helps those who are struggling with the same problem.

**Comment by michvic** [comment]
I don't want to use the [Online builder path](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#creating-custom-builds-with-online-builder) (custom build) but [Building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source) (directly inside my project), but I can't configure the webpack in my next.config.js, to solve the css import issue.

and I get the following error:

![image](https://github.com/ckeditor/ckeditor5/assets/39414786/9dca8bd0-b5a5-4f06-b720-b982a3cbe529)

reasons to use ckeditor5 like this, is because I'm using typescript and that way I don't need to be creating d.ts files for the custom build, because the [Custom builds produced by the online builder and DLL versions of packages provided by CKEditor 5 do not provide built-in typings yet. ](https://ckeditor.com/docs/ckeditor5/latest/installation/working-with-typescript.html)another advantage is to create custom Plugins and Commands. becauese when I import and extend the Commands class in my project (@ckeditor/ckeditor5-core) I keep throwing the css error

**Comment by lazarok09** [comment]
> I don't want to use the [Online builder path](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#creating-custom-builds-with-online-builder) (custom build) but [Building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source) (directly inside my project), but I can't configure the webpack in my next.config.js, to solve the css import issue.
> 
> and I get the following error:
> 
> ![image](https://user-images.githubusercontent.com/39414786/238678382-9dca8bd0-b5a5-4f06-b720-b982a3cbe529.png)
> 
> reasons to use ckeditor5 like this, is because I'm using typescript and that way I don't need to be creating d.ts files for the custom build, because the [Custom builds produced by the online builder and DLL versions of packages provided by CKEditor 5 do not provide built-in typings yet. ](https://ckeditor.com/docs/ckeditor5/latest/installation/working-with-typescript.html)another advantage is to create custom Plugins and Commands. becauese when I import and extend the Commands class in my project (@ckeditor/ckeditor5-core) I keep throwing the css error

The global CSS issue is old but you have look, try to download this library and config your webpack https://www.npmjs.com/package/@zeit/next-sass

See more about because this is a issue ina Next.js project https://github.com/vercel/next.js/discussions/27953

**Comment by Witoso** [comment]
Hey @40fathoms, unfortunately, I couldn't reproduce the issue on this setup. Both the dev and prod build work fine. The only difference I have is the path, not sure why you use `@source`. I just have a straight path to the components folder.

```js
import dynamic from 'next/dynamic'
const CKEditorComponent = dynamic(() => import('@source/components/CKEditorComponent'), {
  ssr: false                                 // ^^^^^^^
})
```

Another, very dummy idea, but make sure that the `components` folder is copied to your container. Maybe it was dropped and not taken into it.

**Comment by Witoso** [comment]
Hello everyone 👋!

We published an article in our docs, about the [Next.js integration](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/next-js.html). I want to thank community members that shared examples before.

That said, there's still work in front of us to make this integration smoother. And we aim to fix it in its roots. I invite everyone to check our new installation methods RFC: #15502.

**Comment by yogithesymbian** [comment]
> I don't want to use the [Online builder path](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#creating-custom-builds-with-online-builder) (custom build) but [Building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source) (directly inside my project), but I can't configure the webpack in my next.config.js, to solve the css import issue.
> 
> and I get the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/39414786/238678382-9dca8bd0-b5a5-4f06-b720-b982a3cbe529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDg1NTgsIm5iZiI6MTcwNTY0ODI1OCwicGF0aCI6Ii8zOTQxNDc4Ni8yMzg2NzgzODItOWRjYThiZDAtYjVhNS00ZjA2LWI3MjAtYjk4MmEzY2JlNTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA3MTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDc5YmU2N2ZlZDliYjUwMmY2NmQ5NDEwZjc3NmU3ODRlN2JjNDE0NjZhYzQzMjk1NzBlZDg5MzA1Y2MzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8iouVOiuSYlUwP7N14JmBrno_5b9-zgqMkw2oht9j0)
> 
> reasons to use ckeditor5 like this, is because I'm using typescript and that way I don't need to be creating d.ts files for the custom build, because the [Custom builds produced by the online builder and DLL versions of packages provided by CKEditor 5 do not provide built-in typings yet. ](https://ckeditor.com/docs/ckeditor5/latest/installation/working-with-typescript.html)another advantage is to create custom Plugins and Commands. becauese when I import and extend the Commands class in my project (@ckeditor/ckeditor5-core) I keep throwing the css error

i have same issue

**Comment by yogithesymbian** [comment]
> Solve with this simple step
> 
> 1. Install ckeditor `yarn install @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic`
> 2. Wrap ckeditor as a component, create new file `src/components/Editor.js`
> 
> ```js
> import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
> import CKEditor from '@ckeditor/ckeditor5-react';
> 
> const Editor = (props) => {
>   return (
>     <CKEditor
>       editor={ ClassicEditor }
>       data={props.value}
>       onChange={ (event, editor ) => {
>         const data = editor.getData()
>         props.onChange(data)
>       } }
>     />
>   )
> }
> 
> export default Editor;
> ```
> 
> 3. On `src/pages/Home`, use component Editor like this
> 
> ```js
> import dynamic from 'next/dynamic'
> 
> const Editor = dynamic(() => import('../components/Editor'), { ssr: false })
> 
> const Home = () => {
>   return (
>     <Editor value="" onChange={(v)=> console.log(v)} />
>   )
> }
> export default Home;
> ```

**why paragraph heading is not working** ? i use typescript instead for my nextjs.
the changelog is already set H1 or any , but on editor is still small like other words without h1


```
// components/Editor.tsx
import { FC/* , ChangeEvent  */, useEffect} from 'react';
// import dynamic from 'next/dynamic';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
// import { EventInfo } from '@ckeditor/ckeditor5-utils';

interface EditorProps {
  value: string;
  onChange: (data: string) => void;
}

const Editor: FC<EditorProps> = ({ value, onChange }) => {
  /* ChangeEvent or  ClassicEditor error params */
  // const handleChange = (event: ChangeEvent, editor: ClassicEditor) => {
  //   const data = editor.getData();
  //   onChange(data);
  // };

  return (
    <CKEditor
      editor={ClassicEditor}
      data={value}
      onChange={(event: any, editor: any) => {
        const data = editor.getData();
        onChange(data);
      }}
    />
  );
};

export default Editor;
```
index.tsx
```
....
function YogiHome(props: {
  profile: any;
}) {
return (
<Editor value="" onChange={(v: any)=> console.log(v)} />
....

```

**Comment by Witoso** [comment]
@yogithesymbian could you provide a reproducible sample, e.g., on StackBlitz?

**Comment by chiragOctet** [comment]
I am getting a flickering issue when i have added this line & also when I enter any data into other fields it makes an flickering effect.
const ReactQuill = dynamic(() => import('react-quill'), {
    ssr: false
  });

**Comment by Witoso** [comment]
Hello everyone, happy to report that we finished the looong work in #15502, and the new installation methods shipped in v42.0.0 make the Next.js integration much, much easier 🥳

Test the new setup with the [Next.js integration guide](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/next-js.html), and let us know what you think!

**Comment by laurencefass** [comment]
Brilliant work thank you!

**Comment by Witoso** [comment]
> CKEditor 5 does not support server-side rendering (yet)

Yep, we plan to investigate this as well, we need access to the browser's APIs so fully-server-rendered mode might be tricky, but we'll see.
