### ISSUE TITLE
Table cells with set width/height can exceed these limits

### ISSUE THREAD

**Issue by oliverguenther** [ckeditor/ckeditor5#7377]
## 📝 Provide detailed reproduction steps (if any)

1. Create a table with at least one cell
2. Set width and height to that cell
3. Write a long word or a long paragraph that exceeds set width or height

### ✔️ Expected result

Users can restrict the size to be forced. This would mean that content is being ellipsed to avoid breaking the available dimensions.

I did not open this ticket to raise this issue for the core of CKEditor, since ideally, the user of CKEditor could provide some custom CSS to enforce the dimensions.

We can already do that for the width by using something like `word-break: break-all` on the `td` and `th` elements. 

But for height, users of CKEditor that really want to enforce these limits are stuck as the browser will automatically resize. If cells with a limited dimension would introduce a child element, this again would allow users to set something like `overflow: hidden` on that inner container and force the height.

### ❌ Actual result

Both width and height exceed freely depending on the input

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
@jodator is the current behaviour expected or a bug?

**Comment by jodator** [comment]
Hi @oliverguenther  - we're constrained by what [CSS 2.x specification](https://www.w3.org/TR/CSS22/tables.html#height-layout) offers here. The `height` on table cell is:

> In CSS 2.2, the height of a cell box is the minimum height required by the content.

So in other words if the content is bigger than cell it will resize the table cell to show that content. We can't do other tricks (like setting height on inner `<div>` element) as it would complicate the already complex table editing part. So, unfortunately, we can't do anything about that.

**Comment by oliverguenther** [comment]
Hi @jodator , thanks for the evaluation :+1:
