### ISSUE TITLE
Nested color of text replaced by top level color

### ISSUE THREAD

**Issue by deniszavadskiy** [ckeditor/ckeditor5#7380]
1. Set editor data: `<p><span style='color: rgb(0, 255, 0);'>My <span style='color: rgb(255, 0, 0);'>Text</span></span></p>`
2. Get editor data.
3. See result.

### ✔️ Expected result
Color of nested text was not removed.

### ❌ Actual result
nested span with color was removed.
result of getData: `<p><span style="color: rgb(0, 255, 0);">My Text</span></p>`

## 📃 Other details

* Browser: Chrome 83.0.4103.61
* OS: OS X 10.15.4
* CKEditor version: 19.0.1
* Installed CKEditor plugins: 
    "@ckeditor/ckeditor5-alignment": "^19.0.1",
    "@ckeditor/ckeditor5-basic-styles": "^19.0.1",
    "@ckeditor/ckeditor5-core": "^19.0.1",
    "@ckeditor/ckeditor5-dev-utils": "^20.0.0",
    "@ckeditor/ckeditor5-editor-decoupled": "^19.0.1",
    "@ckeditor/ckeditor5-engine": "^19.0.1",
    "@ckeditor/ckeditor5-essentials": "^19.0.1",
    "@ckeditor/ckeditor5-font": "^19.0.1",
    "@ckeditor/ckeditor5-heading": "^19.0.1",
    "@ckeditor/ckeditor5-inspector": "^2.1.0",
    "@ckeditor/ckeditor5-link": "^19.0.1",
    "@ckeditor/ckeditor5-list": "^19.0.1",
    "@ckeditor/ckeditor5-paragraph": "^19.1.0",
    "@ckeditor/ckeditor5-remove-format": "^19.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^19.1.0",
    "@ckeditor/ckeditor5-ui": "^19.0.1",
    "@ckeditor/ckeditor5-utils": "^19.0.2",
    "@ckeditor/ckeditor5-vue": "^1.0.1",
    "@ckeditor/ckeditor5-widget": "^19.1.0",

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Actually this is not a bug, but the way conversion in editor works. Nesting styles in such a way is not possible, so this behavior is correct. You can see that if you set colors manually and `getData()`, you will get separate, adjacent `span` elements. Each one with its own styles, for example:
```html
<p>
    <span style="color:hsl(0,75%,60%);">My</span> 
    <span style="color:hsl(150,75%,60%);">Text</span>
</p>
```
So if you want to `setData` with your own content, please remember to wrap every text element in its own span with styles.
