### ISSUE TITLE
Mention does not work with some languages(Arabic or Persian)

### ISSUE THREAD

**Issue by webasoo** [ckeditor/ckeditor5#7385]
## 
Set a feed with some Hebrew text:

    feed: [ 'علی', 'امین', 'Barney', 'Lily', 'Marshall', 'Robin', 'Ted' ]

Switch the keyboard to persian,
Try to autocomplete them (they correspond to "hldk" and "ugd" in an English keyboard).

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I just checked `Mention` plugin with various languages, including Hebrew, Persian, Chinese, etc. and everything works fine for me. 
Apart from that:
- first you write about Hebrew and then have Arabic in the code snippet. So I'm not sure which one you want me to check
- you don't have a marker set in your feed examples, so please refer to the [configuration docs](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#configuration)

If that doesn't help, I'll need to see your editor configuration, error messages and also a step-by-step guide to reproduce this issue will also be helpful.

**Comment by webasoo** [comment]
thanks @FilipTokarski 
please see:
-------------------------------------------------
![ckeditor-bug](https://user-images.githubusercontent.com/28995799/83935745-9ea77700-a7d1-11ea-922f-c75fe54a1b8b.gif)
--------------------------------------------------
my config:

`
CKEDITOR.replace( 'editor', {
			extraPlugins: 'mentions',
			mentions: [
				{
					feed:  ['amin', 'امین','علی', 'John'],
					marker: '@',
					minChars: 0
				}]
		} );
`

version: "4.14.0"

**Comment by FilipTokarski** [comment]
> version: "4.14.0"

CKEditor4 and CKEditor5 are completely separate applications and this repository/issue tracker is for CKEditor5. Please report your issue in [CKEditor4 issue tracker](https://github.com/ckeditor/ckeditor4/issues)
