### ISSUE TITLE
Uncaught TypeError: ClassicEditor.create(...).then(...).getData is not a function

### ISSUE THREAD

**Issue by Fer2323** [ckeditor/ckeditor5#7390]
const ClassicEditor = require ("@ckeditor/ckeditor5-build-classic");
let editor;

ClassicEditor
    .create( document.querySelector( '#content' ) )
    .then( newEditor => {
      editor = newEditor;
    } )
    .getData()
    .catch( error => {
      console.error( error );
    } );

CKEditor works but shows this error in console:

Uncaught TypeError: ClassicEditor.create(...).then(...).getData is not a function

If I remove .getData () it doesn't work

**Comment by Fer2323** [comment]
const ClassicEditor = require ("@ckeditor/ckeditor5-build-classic");
ClassicEditor
    .create( document.querySelector( '#content' ) )
    .then( editor => {
      console.log( 'Editor was initialized', editor );
    } )
    .catch( err => {
      console.error( err.stack );
    } );

If I put it like this CKEditor doesn't work and it shows this error in console:


app.js:53668 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ba.init (app.js:100)
    at ba.<anonymous> (app.js:100)
    at ba.fire (app.js:100)
    at ba.<computed> [as init] (app.js:100)
    at app.js:100

**Comment by Fer2323** [comment]
var myEditor;

ClassicEditor
    .create( document.querySelector( '#content' ) )
    .then( editor => {
      console.log( 'Editor was initialized', myEditor=editor );
    } )
    .catch( err => {
      console.error( err.stack );
    } );
myEditor.getContent();

it works but it gives error in console:

Uncaught TypeError: can't access property "getContent", myEditor is undefined

**Comment by FilipTokarski** [comment]
Hi, if you want to get editor content you need to use `getData()` method. Please refer to [docs on basic API interaction](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html). Apart from this, if you want us to look into the problem, please provide us information about your editor configuration and a step-by-step description to reproduce your issue.
