### ISSUE TITLE
mobile bottom toolbar

### ISSUE THREAD

**Issue by ahmedosama5200** [ckeditor/ckeditor5#7395]
## 📝 Provide a description of the new feature

I need to be able place the toolbar in the bottom of the editor on mobile, like microsoft word
![Screenshot_20200606-163747_Office](https://user-images.githubusercontent.com/31630951/83947032-d8e63800-a814-11ea-83aa-80aedcf9e257.jpg)

I couldn't find a way to do that in the documentation. is that supported ? Even if I had to do more work to get it implemented, guide me where to start ?

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not sure what is the precise use case here and whether you want to use classic/inline/balloon editor, but generally you can position toolbar freely just by using CSS - you need to overwrite editor rules by your own. You can read more about this in [theme customization docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html).

**Comment by FilipTokarski** [comment]
I guess the easiest would be here to use a decoupled document editor and create a container for toolbar, which you can position below.

**Comment by ahmedosama5200** [comment]
but I am using the classic editor not document editor

**Comment by FilipTokarski** [comment]
Well, you can still target it with CSS, but in Classic build, toolbar is a part of editor as a whole, so the styling will be somewhat constrained and might produce a bit unexpected results. So again, in your use case, I would advise to use decoupled document editor.

**Comment by ahmedosama5200** [comment]
I am using the editor so users can enter questions and answers. In docs, it says that document editor is like ms word, for writing several pages which is not the case in my website. Why is the toolbar part of classic editor ? Why not making it decoupled ?

**Comment by Mgsy** [comment]
> In docs, it says that document editor is like ms word, for writing several pages which is not the case in my website.

This is just a sample use case, there are no limitations for each type of builds and you can use it the way you want.

> Why is the toolbar part of classic editor ? Why not making it decoupled ?

For most users, there's no need to separate the toolbar and the editable, so the most common way of displaying it is above the editable. This is also the most intuitive. For people who would like to have a better control, we created the decoupled editor which separates the toolbar and the editable. 

So, if your case is displaying the toolbar in a different position, [use the decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#example-decoupled-editor). You can style it to look the same as the classic editor.
