### ISSUE TITLE
Images in numbered lists trigger number reset

### ISSUE THREAD

**Issue by HDinger** [ckeditor/ckeditor5#7397]
## 📝 Provide detailed reproduction steps (if any)

1. Create a numbered list 
2. Add an image inside the list

![image_in_list](https://user-images.githubusercontent.com/7457313/84010484-01854380-a975-11ea-9765-da40c0daa4b1.gif)

### ✔️ Expected result

The numbering should be kept when an image is inserted. I expect something like this:
![how-it-should-look](https://user-images.githubusercontent.com/7457313/84010600-30031e80-a975-11ea-928e-c93a1593aeb8.png)

### ❌ Actual result

The numbering is broken by the image. The number below it, starts again from "1" instead of continuing the previous numbering.

## 📃 Other details

* Browser: Tested in Chrome and Firefox
* OS: Mac OS 10.14.5
* Tested on the demo page https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by alexishuxley** [comment]
It would be great to get this fixed; including images in numbered lists is an essential in writing good documentation with "addressable" steps. E.g.:

 1. Scroll down the page to the share icon, which looks like this: 
![image](https://user-images.githubusercontent.com/581514/84020644-6cd61200-a983-11ea-9989-181f8de8addd.png) 
  and click it.
 1. Select the recipient application.

The above two list items were both done *in Github*'s editor with '1.' and '1.', where it is displayed correctly, but in ckeditor itself it is *not* displayed correctly, which leads to conversations like:

> I got as far as step 1 and then it went wrong.
> Which step 1, the first step 1 or the second step 1?

**Comment by alexishuxley** [comment]
It looks like the same applies to putting code blocks in numbered lists.

**Comment by Mgsy** [comment]
Hi, thanks for the report. CKEditor 5 doesn't support block elements inside lists, so every time you try to insert a block element to a list item, it will create a new paragraph. 

We have an open feature request for inserting more advanced lists (allowing inserting block elements to an item), you can read about it [here](https://github.com/ckeditor/ckeditor5/issues/2973). Feel free to add :+1: to the first post and join the discussion to bump its popularity.
