### ISSUE TITLE
How to get all img elements?

### ISSUE THREAD

**Issue by wenmingtang** [ckeditor/ckeditor5#7398]
## 📝 Provide a description of the new feature

I want to get all the IMG elements, and  their attributes. src, width, height,uploadStatus….
thx.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, if you want to get all image elements you can start with code like this:
```js
const range = editor.model.createRangeIn( editor.model.document.getRoot() );

for ( const value of range.getWalker( { ignoreElementEnd: true } ) ) {
    if( value.item.is( 'element' ) && value.item.name === 'image' ){
        console.log( value.item );
    }
}
```
This creates a [range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html) containing all editor content, goes through it and logs only [elements](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_element-Element.html), that are images. You can then access the elements and its attributes.
