### ISSUE TITLE
TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by IgnacioHR** [ckeditor/ckeditor5#740]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

@ckeditor/ckeditor5-build-classic

## 📋 Steps to reproduce

1. Create angular 5.1.0 project
2. add "@ckeditor/ckeditor5-build-classic": "^1.0.0-alpha.2"
3. on scripts section of file .angular-cli.json I added "../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js" to call the scripts
4. in the form-component.ts I added declare const ClassicEditor;
5. in the ngOnInit I added ClassicEditor.create( ... ) stuff referring to the id of a textarea in the html template.
6. when the form is displayed, an error is raised in the console

form.component.ts:70 TypeError: Cannot read property 'style' of null
    at Og.replace (scripts.bundle.js:22699)
    at o.initPlugins.then.then (scripts.bundle.js:22699)
    at ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.js:4756)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:142)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4747)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)
    at HTMLLIElement.globalZoneAwareCallback (zone.js:1566)

## ✅ Expected result

textarea editor replaced by ckeditor5

## ❎ Actual result

console error and simple textarea is used instead

## 📃 Other details that might be useful

The form is an angular reactive form

When I move the textarea outside the form ckeditor initializes OK

**Comment by Reinmar** [comment]
You need to pass an actual element to `create()`. ID or a selector won't do.

Check e.g. https://github.com/ckeditor/ckeditor5/issues/599#issuecomment-342582265 to see how to do that in Angular 2+.

**Comment by Reinmar** [comment]
Feel free to comment further if I missed something.

**Comment by IgnacioHR** [comment]
This is how I'm passing the node to the create method. I'll debug what is sent to create and will reply back later

ClassicEditor.create( document.querySelector( '#emailBodyContent' ) )

**Comment by Reinmar** [comment]
Did you check whether `document.querySelector()` returns anything? Maybe this element doesn't exist in the document at that point yet?

**Comment by IgnacioHR** [comment]
Ok, tested. document.querySelection('#emailBodyContent') returns null and this is the source of the problem. I'll move further from this point.

Thanks!

**Comment by ma2ciek** [comment]
Shouldn't we throw some more meaningful error for such obvious mistake?

**Comment by Reinmar** [comment]
I think there's a ticket somewhere about validating that a proper first param is passed to `create()`. I can't find it, though. Maybe @pjasiun remembers.

If not, we should create it and finally add this check. There were also discussions about checking that an editor isn't initialised on this editor yet. That's important as well.

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor5-engine/issues/1270 ? :)

**Comment by pjasiun** [comment]
And we plan to work on error handling soon, I will keep this case in mind.

**Comment by Reinmar** [comment]
> And we plan to work on error handling soon, I will keep this case in mind.

This specific issue is not related to error handling. And it's not related to ckeditor/ckeditor5-engine#1270 too :P
