### ISSUE TITLE
I can't use a restricted edition with mention

### ISSUE THREAD

**Issue by guimaraesSalgado** [ckeditor/ckeditor5#7404]
I would like to create a restricted model and leave some parts for the user to change, but using the mention. But I noticed this is not possible, is there a way to do this?

**Comment by Mgsy** [comment]
Hi, you can define which commands should be enabled in restricted editing mode. See [the documentation](https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html#configuration).

**Comment by guimaraesSalgado** [comment]
@Mgsy, I read the commands and documentation, however when trying to use portrait editing with mention, the mention plugin did not work ... I saw the question if it is possible, because when implementing following the documentation, it did not work

**Comment by Mgsy** [comment]
I was able to successfully insert a mention to the exception marker in the restricted editing mode:

![](https://user-images.githubusercontent.com/20988892/84116897-f98ad980-aa30-11ea-9cf1-d02850e452b1.gif)

Make sure that you've configured your plugins properly.

**Comment by guimaraesSalgado** [comment]
can you help me find an error in the configuration? because I'm trying and I can't find it, I'm working with angular
