### ISSUE TITLE
Image Tooltip ck-widget

### ISSUE THREAD

**Issue by mjapadilla** [ckeditor/ckeditor5#7406]
![image](https://user-images.githubusercontent.com/56869280/84129016-f36a1c80-aa73-11ea-8b1f-ee7c1afe78ec.png)

I cant click the image alignment tooltip,

**Comment by Mgsy** [comment]
Hi, could you please explain why you'd like to click on the tooltip? Tooltips appear on elements only if the cursor hovers a button. After moving the cursor to the tooltip, it leaves the button, so the tooltip disappears.

**Comment by mjapadilla** [comment]
Sorry, i mean i cant click the popup buttons when i select image
but good news i figure it out why. its seems i have parent container with z-index that block the popup buttons
