### ISSUE TITLE
[Chrome/Safari] Block shouldn't be nested inside another block after paste

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#741]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Create empty block quote.
3. Double-click inside this block quote.
4. Press <kbd>Ctrl</kbd> + <kbd>X</kbd>.
5. Put the selection at the end of `Heading 1`.
6. Press <kbd>Ctrl</kbd> + <kbd>V</kbd>.

## ✅ Expected result

Element should be pasted outside of the block.

## ❎ Actual result

Element is nested inside the `<h1>` block.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/34289258-f22155d4-e6f1-11e7-80ad-7b7070400365.gif)

**Other information**

Related - https://github.com/ckeditor/ckeditor5/issues/730
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera

**Comment by Reinmar** [comment]
Not a regression, but quite serious.

**Comment by Mgsy** [comment]
It's fixed.
