### ISSUE TITLE
Error: No PostCSS Config found in: \node_modules\@ckeditor\ckeditor5-

### ISSUE THREAD

**Issue by aysiscore** [ckeditor/ckeditor5#7412]
I am trying to build the CKEditor5 from source and have setup Webpack as mentioned in the docs. When I build the project, I get an error saying there is no PostCSS config file found, but in the Github repository for the Classic Editor builds etc there is no postcss.config.js file.

Why am I getting that error?

**Comment by Mgsy** [comment]
Hi, did you follow our guide about [creating the editor from the source](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)?

**Comment by aysiscore** [comment]
Mgsy I have found the problem. Most websites have their own css files which need to be loaded using css-loader and MiniCssExtractPlugin.loader or whatever. The problem is that those loads must not touch any of CKEditor's css. 

But simply doing this in Webpack is not enough:
```
test: /\.css$
exclude:  path.join( __dirname, 'node_modules', '@ckeditor' ),
```

I had to rewrite the Regex so it avoids matching anything that contains "ckeditor" like this:
`test: /^(?!.*ckeditor).*\.css$/`

I am not sure if that is the "proper" way of doing it, but it works for me. I think the docs need some updates on how to setup CKEditor within an existing site that already has css files and is built using Webpack.

**Comment by thedanbob** [comment]
I ran into the same sort of problem. I solved it by switching my postcss.config.js based on the file being processed:

```js
const { styles } = require('@ckeditor/ckeditor5-dev-utils')

const ckeditorConfig = styles.getPostCssConfig({
  themeImporter: {
    themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
  },
  minify: true
})

const normalConfig = {
  plugins: [
    // Config used by the rest of my site
  ]
}

module.exports = ({ file }) => /@ckeditor/.test(file.dirname) ? ckeditorConfig : normalConfig
```
