### ISSUE TITLE
style tags inside <em> makes the Italics button not toggle the italics

### ISSUE THREAD

**Issue by charliekunkel** [ckeditor/ckeditor5#7415]
## 📝 Provide detailed reproduction steps (if any)

Discovered with a document that was originally pasted from word I think probably, but I figured out what was causing it and duplicated it in a new document.

1. Add a style attribute to an <em> element:  `<em style="font-size:18pt;">This is emphasized</em>`
2. Highlight any of the text (not in source mode)
3. Click the "I" button in the toolbar to toggle Italics.  

### ✔️ Expected result

Italics should be removed/toggled for the highlighted text

### ❌ Actual result

Italics is not removed/toggled

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.14.0
* Installed CKEditor plugins: CKFinder

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, CKEditor 5 and CKEditor 4 are completely separate applications and this repository is for CKEditor 5. Please report any problems you have with CKE4 in [CKEditor 4 issue tracker](https://github.com/ckeditor/ckeditor4/issues).
