### ISSUE TITLE
Add translation for Mongolian.

### ISSUE THREAD

**Issue by hurelhuyag** [ckeditor/ckeditor5#7416]
## 📝 It needs mongolian translation

I wanted to use ckeditor5. But I need mongolian translation.

---

**Comment by Mgsy** [comment]
Hi! CKEditor 5 translations are managed via Transifex: [https://transifex.com/ckeditor/ckeditor5](https://transifex.com/ckeditor/ckeditor5)

You can join the Mongolian team and submit them. Thank you!
