### ISSUE TITLE
Close the toolbar in dialog mode

### ISSUE THREAD

**Issue by nonomaxxis** [ckeditor/ckeditor5#7422]
hi,
i use ckeditor5 vue.js in dialog, toolbar has bug.
![image](https://user-images.githubusercontent.com/6130447/84505008-36c1c680-acd2-11ea-996f-4bfffaeabd73.png)
 when i change widow size its ok. 
![image](https://user-images.githubusercontent.com/6130447/84505089-607aed80-acd2-11ea-908e-35527d4e6e63.png)

Help me.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In order to look into this, we'll need a step-by-step guide to reproduce the issue. Also please provide your editor configuration and check if there are any errors in the console.

**Comment by otherblandart** [comment]
I've also encountered this issue, using a third-party framework's dialog widget. Editor is given width of 100% inside dialog. I think the issue relates to editor instance being initialized before dialog DOM is fully rendered, so it doesn't know what _100%_ is yet. My fix was to reduce dialog container width by a small amount when it is rendered, then set a small timeout to reset the width of the dialog after.

**Comment by FilipTokarski** [comment]
@nonomaxxis do you still encounter this issue or were you able to fix it like in the comment above ☝️  ?

**Comment by nonomaxxis** [comment]
> Hi, thanks for the report. In order to look into this, we'll need a step-by-step guide to reproduce the issue. Also please provide your editor configuration and check if there are any errors in the console.

editor: ClassicEditor,
        editorConfig: {
          toolbar: [
            'undo',
            'redo',
            'fontColor',
            'fontBackgroundColor',
            'fontSize',
            '|',
            'bold',
            'italic',
            'underline',
            'removeFormat',
            'alignment',
            'bulletedList',
            'numberedList',
            'horizontalLine',
            '|',
            'link',
            'imageUpload',
            'insertTable',
            'mediaEmbed',
          ],
          image: {
            toolbar: [
              'imageTextAlternative',
              'imageStyle:full',
              'imageStyle:side',
            ],
          },
          table: {
            contentToolbar: [
              'tableColumn',
              'tableRow',
              'mergeTableCells',
            ],
          },
        },

**Comment by FilipTokarski** [comment]
I checked the toolbar in few setups and it works fine for me, so I guess there might be something wrong with your implementation and not with the editor itself. It's really hard to tell without more information about your app. If you are using  third party libraries or some custom styles on the editor, please make sure they are not the cause of this issue.
