### ISSUE TITLE
Consider dropping the JSDoc API extractor

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#7425]
Around 3 years ago we did a small research about JS API docs extractors. That time we choose the [JSDoc](https://github.com/jsdoc/jsdoc) lib as with its cons it was the most popular and maintained library. However, as time passed, our needs grew to the point where we need to maintain a bunch of plugins extending or fixing the JSDoc default behavior. We have plugins for fixing class constructor docs, supporting new tags (like `@error`), supporting mixins, fixing various inheritance issues, allowing shorter syntax than `module:...` in some places and so on. As maintaining it takes a lot of time (recently we forked it to add support for Node@12 without breaking our doc builder) we should consider replacing it with other tools, hence I made a small summary of the current situation and available options.

### Current issues with JSDoc

*   no Node.js API (CLI usage only)
*   poor API reference (nothing has changes since the last research 😅)
*   recent BC in the plugin API after changing the underlying parser
*   no clear API for plugin API, no available typings for internal structures, it's hard to determine what's internal and what's public and what can be changed at given step
*   missing built-in features that could solve our issues
    *   support for mixins
    *   support for inheriting events
    *   support for inheriting docs for class static properties
    *   shorter syntax
*   many duplicated tags leading to inconsistent docs
*   old codebase that was design to work with ES3 and ES5 features
*   \[ckeditor5-dev\] all our tests for jsdoc plugins are unit tests - having them written as integration tests would allow us for better testing for regressions and changing the documentation extractor more easily. However, due to no API for JSDoc, it's not possible to write them as easily as we write unit tests, there is also no chance to test coverage of our JSDoc plugins this way.

### Other JS API docs extractor

After googling around I came to the conclusion that during the last years nothing new has been introduced to the market.

<table><tbody><tr><td>Name</td><td>Status</td></tr><tr><td><a href="https://github.com/documentationjs/documentation">documentation.js</a></td><td>author only merges some PRs, see <a href="https://github.com/documentationjs/documentation/wiki/Current-maintenance-status">the maintenance status</a></td></tr><tr><td><a href="https://github.com/esdoc/esdoc">ESDoc</a>&nbsp;</td><td>&nbsp;Last commit 3 years ago</td></tr><tr><td><a href="https://github.com/jsdoc/jsdoc">JSDoc</a>&nbsp;</td><td>&nbsp;Maintained, mainly by one author</td></tr><tr><td><a href="https://github.com/yui/yuidoc">YuiDoc</a>&nbsp;</td><td>&nbsp;Last commit 3 years ago</td></tr></tbody></table>

### TS API doc extractors

The situation is pretty different in the TS world. There's a couple of API docs extractor available and actively maintained. However, the problem here is that writing documentation requires TS codebase or codebase parseable by the TS parser (#504). I feel this won't happen anytime soon.

*   [https://github.com/microsoft/tsdoc](https://github.com/microsoft/tsdoc) - An open-source doc spec + a parser, the type is often inferred from the TS system, so there's no need to write it twice.
*   [https://github.com/TypeStrong/typedoc](https://github.com/TypeStrong/typedoc)
*   [https://github.com/microsoft/rushstack/tree/master/apps/api-extractor](https://github.com/microsoft/rushstack/tree/master/apps/api-extractor) written on top of the mentioned `tsdoc` spec and parser.

### Creating new API docs extractor

This is another option - writing an API docs extractor from scratch on top of an open-source parser. While it should not be a super hard task it hard for me to determine time needed to implement it. Such an extractor would be a perfect fit if we would like to make the [Umberto](https://github.com/cksource/umberto) project public at some point.

Requirements:

*   creating a JSDoc tag parser (there's ~10-15 different tags that we use),
*   transforming md-like comment fragments to HTML markup,
*   creating a type parser for `@param`, `@type`, etc.,
*   creating a reference validator (not confuse with type checking),
*   choosing a parser (acorn, babel parser, etc.) and using it to walk through documented entities (aka doclets)
*   producing an array of JSDoc's doclet-like objects that can be easily parse by [Umberto](https://github.com/cksource/umberto) for documented symbols
*   \[bonus\] support types parsable by the TS complier

### Bonus

*   [https://github.com/microsoft/rushstack/tree/master/apps/api-extractor](https://github.com/microsoft/rushstack/tree/master/apps/api-extractor) comes from [https://github.com/microsoft/rushstack](https://github.com/microsoft/rushstack) - a bunch of Microsoft's tools for TS monorepo projects developed by the Rush Stack community. I feel that it can be valuable for us to check this repository for some valuable tools that can be applied for the JS world too. And they could be an option if we'd like to move to TS at some point.

**Comment by ma2ciek** [comment]
RFC @scofalik @Reinmar @mlewand @pomek.

**Comment by ma2ciek** [comment]
As there's no quick win in the options above I'm changing our JSDoc plugins so they work with the new JSDoc version and write some integration tests to them so we can switch the extractor more easily in the future.

**Comment by Reinmar** [comment]
Could you write down your thoughts @ma2ciek? I know you ported our old JSDoc plugins to the new version. Was it worth it?

**Comment by ma2ciek** [comment]
Here's a short list of pros that I've seen when I've decided to keep the JSDoc:

*   Much less code to maintain - writing new JSDoc extractor would need to cover the following topics:
    *   source code with a well-thought architecture (good research would be needed)
    *   unit tests
    *   e2e tests (they would be necessary to check if the documentation still builds fine after the migration)
    *   docs clear to everyone - even if we'd go with the JSDoc way of writing API docs we'd still need to decide what exactly we want to support and what we do not since the number of supported tags in JSDoc is huge and it's not clear how they behave in various situations
    *   review that takes other person's time
*   We can wait until a new more satisfying solution comes up without investigating too much into this topic.
*   New API extractor would need to be a project customized strictly for our needs, thus we wouldn't achieve any support from the community and the project could become another 1-person project (Especially since Umberto is still a closed-source project and only a combination of both of them publicly available would be valuable for people).
*   Parsers have some bugs as well that are mostly hidden by the JSDoc's (or other API docs extractor's) abstraction. When we'd depend on parsers directly we'd have to deal with lower-level bugs that could be harder to fix without the proper knowledge and maintain its updates as well (like adding support for new JS documentable symbols).

For sure, porting plugins to the latest version of Umberto took me much longer than I was anticipating and it wasn't an enjoyable task (mainly because some random things were broken and it was hard to debug due to nesting shell process executions and huge output data that needed to be compared). Was it worth it? Hm. I imagine myself deep in the new API extractor at this moment fighting with other bugs and complications I wasn't aware of :smile:

**Comment by Reinmar** [comment]
Thanks, @ma2ciek. So I'll close this ticket.
