### ISSUE TITLE
ListItems that contain block level elements have their ListItem nature discarded

### ISSUE THREAD

**Issue by foxseanpatrick** [ckeditor/ckeditor5#7426]
1. …Open existing html content in ckeditor5 with this markup:
`<ul><li><p>content</p></li></ul>`
2. Save resulting html content as parsed by ckeditor5
3. The resulting saved html is `<p>content</p>`

While ideally the html would be preserved exactly as entered (it's perfectly valid) I understand from https://github.com/ckeditor/ckeditor5/issues/2973 that block level elements are not supported in lists (which is extremely problematic for us but is an issue for another day).  Given that that is not an option it seems like the output html *ought* to just discard the paragraph tag and keep the `<ul><li>` markup:
`<ul><li>content</li></ul>`

I can imagine many scenarios when folks with existing content are transitioning to ckeditor 5 and would have existing content like this case. And I can't imagine any of those scenarios in which discarding the list tags would be the desired outcome.

In our case we have at least 1,000 pages of content (from hundreds of authors generated over a decade) that happen to have this particular issue, making it extremely problematic to convert to ckeditor5.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the feedback. As you noticed, there's an [open feature request](https://github.com/ckeditor/ckeditor5/issues/2973) for document lists which covers your use case. I understand that you find this feature important, so I encourage you to leave :+1: for the first post in the request and add your feedback to the discussion. It will allow us to track a popularity of requests. Thanks!
