### ISSUE TITLE
change toobark and other icon sizes for sake of accesibilty

### ISSUE THREAD

**Issue by addsimm** [ckeditor/ckeditor5#743]
- Feature request

Our users come from an older population and have challenges that larger icons, among other changes, would help overcome.  I spent a great deal of time hacking version 4 to increase the toolbar icon size, replacing the icon graphics (and other adjustments) to increase the size to 40px square. It still does not look great. 

Right now, in version 5 the icons are 20px square - way too small for many people to use easily.   These people would greatly benefit from making larger sizes easily available.

Thanks

**Comment by oskarwrobel** [comment]
In CKE5 all icons are vectors so you can easily scale them. This should be not a problem to adjust size of toolbar (or any other) buttons.

![dec-23-2017 21-59-09](https://user-images.githubusercontent.com/1057056/34322621-8b3a8da4-e82c-11e7-9678-728f1c3aa881.gif)
