### ISSUE TITLE
Introduce support for PDF export and Multiroot Editor.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#7430]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

Introduce generic support for PDF Export tool and Multiroot Editor.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by tomalec** [comment]
Today with @Reinmar we discussed the scope of this issue.

- The idea is to slightly change `-export-pdf` behavior. It should use a callback provided in the config to collect data, so in case of multi-root, the user could provide different functions to collect data for PDF and to `getData` for other means. By default, it should work as today, so the default value of the callback would be `config.exportPdf.dataCallback= ( editor ) => editor.getData()`.

  Then multi-root editor-author, could either define `getData` for this and other applications or provide a callback specifically for pdf export.
- The above callback needs to be documented, with an example snippet with a multi-root editor.
- The manual test is not strictly required for this issue but could be done as nice-to-have

**Comment by tomalec** [comment]
PR is waiting at https://github.com/cksource/ckeditor5-internal/pull/184
