### ISSUE TITLE
Chrome focus bug

### ISSUE THREAD

**Issue by stasyabezruk** [ckeditor/ckeditor5#7442]
## 📝 Provide detailed reproduction steps (if any)

1. I used code=plugin from official tutorial for inline widget - https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html
2. I added this plugin to react component classic ckeditor
3. when some placeholder=span was inserted, the focus in the end doesn't work
BUT it works well in Firefox

### ✔️ Expected result

the focus cursor after custom span should work

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: chrome (new version is 83.0.4103.106)
* OS:  windows

* CKEditor version: 
"@ckeditor/ckeditor5-build-classic": "^19.0.2",
  "@ckeditor/ckeditor5-react": "^2.1.0"

* Installed CKEditor plugins: …

![image](https://user-images.githubusercontent.com/10813820/84781583-ae079b00-afef-11ea-940d-6c1f150ac1e3.png)

**I can't set focus after custom span. The code for plugin was the copy from the official tutorial**

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, do I understand correctly that you can't place the selection after an inline widget? Can you reproduce your issue in our [placeholder plugin demo](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#demo)?

**Comment by stasyabezruk** [comment]
yes, exactly. But in your placeholder plugin demo it works ok. May it be the case that code is different from that demo uses ?

**Comment by stasyabezruk** [comment]
> Hi, do I understand correctly that you can't place the selection after an inline widget? Can you reproduce your issue in our [placeholder plugin demo](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#demo)?

**Comment by stasyabezruk** [comment]
the difference is that I use CKEditor from '@ckeditor/ckeditor5-react'; for these needs

**Comment by Mgsy** [comment]
I've just checked the code from our [Implementing an inline widget guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#full-source-code) with React integration and it works fine in Chrome. Please make sure that you follow our [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) and your placeholder plugin code is the same as in documentation.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
