### ISSUE TITLE
Image toolbar does not appear 

### ISSUE THREAD

**Issue by andres314** [ckeditor/ckeditor5#7446]
## 📝 Provide detailed reproduction steps (if any)

I have created a VUE.JS component with the CKEditor, I was able to add a custom upload adapter, but the image toolbar doesn't appear. I can't find a simple documentation about how to adding using the vue implementation

```
<template>
  <ckeditor
    :editor="editor"
    v-model="val"
    v-on:input="onInput"
    :config="editorConfig"
  ></ckeditor>
</template>

<script>
import CKEditor from "@ckeditor/ckeditor5-vue"
import ClassicEditor from "@ckeditor/ckeditor5-build-classic"

import CKEditorUploadAdapter from "./CKEditorCustomUploadAdapter"

// Plugin for image upload
function CustomUploadAdapterPlugin(editor) {
  editor.plugins.get("FileRepository").createUploadAdapter = loader => {
    return new CKEditorUploadAdapter(loader)
  }
}

export default {
  name: "RichTextEditor",
  components: {
    ckeditor: CKEditor.component
  },
  props: {
    value: { type: String, default: "" },
    name: { type: String, default: "" },
    onInput: { type: Function, default: () => {} }
  },
  data() {
    return {
      editor: ClassicEditor,
      editorConfig: {
        image: {
          toolbar: ["imageTextAlternative"]
        },
        toolbar: [
          "bold",
          "italic",
          "|",
          "ImageUpload",
          "MediaEmbed",
          "|",
          "undo",
          "redo"
        ],
        extraPlugins: [CustomUploadAdapterPlugin]
      }
    }
  },
  computed: {
    val: {
      get: function() {
        return this.value + ""
      },
      set: function(val) {
        this.$emit("input", val)
      }
    }
  }
}
</script>

```

### ✔️ Expected result

To see the image toolbar

### ❌ Actual result

The image does not has the toolbar

## 📃 Other details

* CKEditor version: 5
* Installed CKEditor plugins:
"@ckeditor/ckeditor5-build-classic": "^19.0.2"
 "@ckeditor/ckeditor5-vue": "^1.0.1"

**Comment by Mgsy** [comment]
Hi, I can see that you try to load a plugin and a build at the same time. This is not allowed - if you'd like to use your custom adapter, you should [add it to your build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build), then import this customized build. The other solution will be [building the editor from the source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source).

**Comment by andres314** [comment]
@Mgsy The custom adapter works without any issue, in not the problem. The problem is the image toolbar, which does not appear, even if I remove my custom  adapter.

**Comment by andres314** [comment]
Also, it might be not allowed, but I don't see where says that on the docs that I need a customn build for the custom adapter. https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html

**Comment by Mike20403** [comment]
same problem with angular framework, I integrate a online custom build to my angular project, everything works ok but the image toolbar is missing, Image resized works

**Comment by wayneYo** [comment]
> I have the same problem you have

**Comment by wayneYo** [comment]
> 角度框架存在同样的问题，我将在线自定​​义构建集成到我的角度项目中，一切正常，但图像工具栏丢失，图像调整大小有效

I have the same problem you have

**Comment by wayneYo** [comment]
> same problem with angular framework, I integrate a online custom build to my angular project, everything works ok but the image toolbar is missing, Image resized works

I have the same problem you have

**Comment by Witoso** [comment]
If the image toolbar isn't appearing, but image resizing one is working, there may be several reasons for this:

**Configuration Issue:** It could be due to a missing or incorrect configuration in your CKEditor setup. Check the configuration and make sure the image toolbar is included in the toolbar configuration.

**CSS Issue:** Sometimes, the image toolbar might not be visible due to CSS issues (like z-index problems, hidden overflow, etc.). Make sure there are no conflicting styles that hide the toolbar. Does the toolbar appear in the HTML source?

**Comment by Mike20403** [comment]
> If the image toolbar isn't appearing, but image resizing one is working, there may be several reasons for this:
> 
> **Configuration Issue:** It could be due to a missing or incorrect configuration in your CKEditor setup. Check the configuration and make sure the image toolbar is included in the toolbar configuration.
> 
> **CSS Issue:** Sometimes, the image toolbar might not be visible due to CSS issues (like z-index problems, hidden overflow, etc.). Make sure there are no conflicting styles that hide the toolbar. Does the toolbar appear in the HTML source?

you're right, after considering all possibilities, i've found out that the problem comes from the 'z-index', it was overlapped by some of my layouts, I've fixed the issue by modifying z-index, thanks you !

**Comment by nandhinigandhi95** [comment]
where you add z-index or please tell me add z-index in which class

**Comment by Mike20403** [comment]
> where you add z-index or please tell me add z-index in which class

![image](https://github.com/ckeditor/ckeditor5/assets/57946382/88df6003-fc13-4ec5-87f6-4ddbbd68bca8)
may be apply to one of the 2  classes, id remember for sure :'D, I left it for too long

**Comment by zhzgao** [comment]
Add this css to you <style> (not <style scoped>) will work fine:
``` css
.ck-balloon-panel {
  z-index: 9999 !important;
}
```
