### ISSUE TITLE
Translation download fetches also Collaboration Features translation

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7461]
## 📝 Provide detailed reproduction steps (if any)

1.  Execute `npm run translations:download`

### ✔️ Expected result

Only CKEditor 5 package localization is downloaded.

### ❌ Actual result

Collaboration Features translation are downloaded too.

## 📃 Other details

AFAIR it was introduced with plural forms. I was pretty sure that I reported an issue for this back in a day but I couldn't find it today.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
The PR fixing it was merged - ckeditor/ckeditor5-dev#641. Maybe ckeditor5-dev-env wasn't released since then?

**Comment by mlewand** [comment]
Might be the case, I'll check that.

**Comment by mlewand** [comment]
I didn't experience it last time so I think the issue went away :relieved: Thanks!
