### ISSUE TITLE
Allow mouse interactions with block widget content

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#7468]
## 📝 Provide a description of the improvement

Scenario: I have a block widget with UI element inside - the UI element is mostly text:

![](https://user-images.githubusercontent.com/617641/85130352-185d4d00-b235-11ea-80a7-bf0d2c170744.png)

I'd like to interact with it - e.g. to be able to select the text within the widget. But currently this seems to be blocked by CKEditor - mouse events are not getting to the widget content and I'm not able to select the text.

From the issues (e.g. #2773) I've read this seems to be some design decision and not a bug, but I was not able to find some more detailed explanation why this is the case. Also, what is not clear to me is if this is a temporary limitation and perhaps might be fixed in the future?

Thanks.

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I think that we could merge this into #4600 and #4465. The latter is about stopping CKE5 handling some events and once this is done selection _should_ start to work. I achieved that with native `<input>`s. Could you check a workaround from #4465? If it works for your case too, I'd close this ticket.

**Comment by zadam** [comment]
Thanks, those issues provide more info and I actually remember reading them before but today I could not find them ...

The workaround/hack mentioned in the #4465 helped, thanks!

**Comment by Reinmar** [comment]
FYI: I proposed a better workaround in https://github.com/ckeditor/ckeditor5/issues/4600#issuecomment-648814894. It's also in line with the direction that we'll take on our side.
