### ISSUE TITLE
CKFinder : cors issue & A parser-blocking, cross site (i.e. different eTLD+1) script

### ISSUE THREAD

**Issue by tarzanking** [ckeditor/ckeditor5#7473]
## 📝 Provide detailed reproduction steps (if any)

1. I am trying to using vue.js connect to CKFinder which I was built in Laravel ( work fine when in Laravel ) but it faces the problem when use vue.js call the CKFinder 
2. I was trying to use the script 
`<script src="http://127.0.0.2:8000/js/ckfinder/ckfinder.js"></script>`
to make the integration but it still facing the problem below
3. I have tested to call API from Laravel it works fine and doesn't have any issue of CORS, but when connecting to CKFinder it fails...

Issue Image
![image](https://user-images.githubusercontent.com/12784182/85209818-7f7e1d00-b36d-11ea-996f-ca158313a011.png)

Follow was my Configuration CKFinder Vue.JS Code
The added script in index.html page
`
    <script src="http://127.0.0.2:8000/js/ckfinder/ckfinder.js"></script>
`

Follow code is the configuration in my editor page

```
          ckfinder: {
              // Upload the images to the server using the CKFinder QuickUpload command.
              uploadUrl:'ckfinder/connector?command=QuickUpload&type=Files&responseType=json',
              filebrowserBrowseUrl: '/ckfinder/browser',
              filebrowserImageBrowseUrl: '/ckfinder/browser?type=Images',
              filebrowserUploadUrl:'/ckfinder/connector?command=QuickUpload&type=Files',
              filebrowserImageUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Images',

              // Define the CKFinder configuration (if necessary).
              options: {
                  resourceType: 'Images'
              },

              openerMethod: 'popup'
          },
```

### ✔️ Expected result

Somebody help...

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: window
* CKEditor version: 5
* Installed CKEditor plugins: …
```
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'

  import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials'
  import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold'
  import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic'
  import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
  import Code from '@ckeditor/ckeditor5-basic-styles/src/code';
  import LinkPlugin from '@ckeditor/ckeditor5-link/src/link'
  import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph'
  import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment'
  import Heading from '@ckeditor/ckeditor5-heading/src/heading';


  import Indent from '@ckeditor/ckeditor5-indent/src/indent';
  import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
  import Font from '@ckeditor/ckeditor5-font/src/font';

  import Base64UploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/base64uploadadapter'

  import Image from '@ckeditor/ckeditor5-image/src/image'
  import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar'
  import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption'
  import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle'
  import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize'

  import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder'
  import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage'

  import Table from '@ckeditor/ckeditor5-table/src/table';
  import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
```
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, sorry for the late reply. The error seems to be related to your server configuration, you can try adding `Access-Control-Allow-Origin: *` header to your responses and see if it helps.

**Comment by tarzanking** [comment]
Hi, thanks for your reply.
For now, I am able to drag and drop and upload the file to the server which not face any issue CORS issue by using CKFinder upload Url method. **( Also I added the `Access-Control-Allow-Origin: * ` in my server site )**

But when I try to open CKFinder it shows the error as mentioned above

**Comment by lyp82n** [comment]
Hi，Tarzanking.
Is this problem solved?
We have the same problem

**Comment by tarzanking** [comment]
Not yet ... I am waiting for @Mgsy to give the solution ...

**Comment by Mgsy** [comment]
@tarzanking, unfortunately, I can't reproduce your issue. I'd suggest checking your CKFinder script loading. As I can see in the picture in the first post, there's a warning about inserting a `<script>` tag with your resource using `document.write`. Please, make sure that CKFinder is loading properly on your page and is not blocked by the browser.

Just out of curiosity - can you check if the script hosted on our end works fine for you?

```html
<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>
```

**Comment by tarzanking** [comment]
@Mgsy Follow script work fine for me 
`<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>`
![image](https://user-images.githubusercontent.com/12784182/89188168-da439f00-d5d0-11ea-8b84-48f2dbff951e.png)
I also having the same warning but it work well with ckeditor.com

I am using the following way to create my ckfinder
`https://github.com/ckfinder/ckfinder-laravel-package`

Does the way I insert the ckfinder.js is the right way?

**Comment by Mgsy** [comment]
So, as it works fine with a script hosted on our end, I assume that your application hasn't been able to load the CKFinder script hosted on your server - that's why the error occurred. It's hard to tell what is the source of the problem, however, it's related to your application/server configuration, not CKFinder.

I'll close this issue, as it's not CKEditor 5 and CKFinder integration problem.

**Comment by tarzanking** [comment]
@Mgsy but I follow the 
`https://github.com/ckfinder/ckfinder-laravel-package` method
the error also happened in localhost not in server

**Comment by cast3** [comment]
I had the same issue, I solve it putting:
// http://docs.cksource.com/ckfinder3-php/configuration.html#configuration_options_headers
//config/ckfinder.php

```
$config['headers'] = array(
    'Access-Control-Allow-Origin' => '*',
    'Access-Control-Allow-Headers' => 'Origin, X-Requested-With, Content-Type, Accept'
);
```
