### ISSUE TITLE
Remove "Creating custom builds" guide

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#7475]
With the change to monorepo this guide is largely outdated plus we weren't happy with it anyway.

TODO:

1.  Create a redirect in Umberto from this guide to https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html
2.  Check all references to this guide in our docs (both guides and API docs) and change them to "Installing plugins".

**Comment by Reinmar** [comment]
It's a DUP of #6770. Unless we want to separate these steps.

**Comment by AnnaTomanek** [comment]
This one is easier and requires far less effort (it's more of a technical task than rewriting task). So I'd be +1 for splittling them. Sorry for the DUP :)

**Comment by Reinmar** [comment]
The custom builds guide was aligned to match the current "situation". The rest of the work is happening in #6770 so I'm closing this ticket.
