### ISSUE TITLE
When an image is resizing it affect ImageCaption

### ISSUE THREAD

**Issue by kaluginserg** [ckeditor/ckeditor5#7477]
## 📝 Reproduction steps

- Using ImageResize and ImageCaption together.

### ✔️ Expected result

There should be the ability to change only image size, but not the Caption size. Probably the ability to set Caption size to 100% of the text container. Or smth like that.

### ❌ Actual result

When an image is resized to small size - it affects ImageCaption size, so Image caption looks really very bad... 

<img width="819" alt="Screenshot 2020-06-22 at 14 25 12" src="https://user-images.githubusercontent.com/6398891/85282533-94a19b80-b494-11ea-9da0-6245c12d03b8.png">
<img width="820" alt="Screenshot 2020-06-22 at 14 24 55" src="https://user-images.githubusercontent.com/6398891/85282549-98cdb900-b494-11ea-99f6-97994c8c586e.png">

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this resizing issue and [it is tracked here](https://github.com/ckeditor/ckeditor5/issues/6329). Please feel free to add there any information that are important to you. I'll close this ticket as a duplicate.

**Comment by kaluginserg** [comment]
@FilipTokarski As I see it is different issues. In the https://github.com/ckeditor/ckeditor5/issues/6329 - the caption container is **narrower than the image width**. But here I've noticed that the caption container should have custom settings for better usability - that is probably not a Bug but a very needed feature.
