### ISSUE TITLE
Restricted and word necklace editing

### ISSUE THREAD

**Issue by guimaraesSalgado** [ckeditor/ckeditor5#7480]
I am using the restricted edition plugin and would like to paste a word content, however I was unable to do this and from what I saw the plugin does not support the "enter" key. Is this correct?

**Comment by FilipTokarski** [comment]
Hi, restricted editing does not allow to paste content from word the same way you would do it normally. This means the text will be pasted, but in this case styling will be lost. As it comes to commands, please see our [restricted editing documentation](https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html#configuration) - you can enable existing or custom commands by modifying the configuration.
