### ISSUE TITLE
Pasting multiple cells leaves the selection while TableSelection is disabled

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#7486]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a table.
2.  Select two cells and copy them.
3.  Disable `TableSelection` - `editor.plugins.get( 'TableSelection' ).forceDisabled()`.
4.  Put the caret in a cell.
5.  Paste.

### ✔️ Expected result

The selection is collapsed.

### ❌ Actual result

Multiple cells are selected.

## 📃 Other details

![](https://user-images.githubusercontent.com/20988892/85391018-ee17d200-b549-11ea-8642-9f9b23f08887.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Handle this in `setCellSelection()` to not set multi-cell selection.
