### ISSUE TITLE
Pasting table into table adds spaces in empty cells

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7487]
## 📝 Provide detailed reproduction steps (if any)

1. Go to [demo](https://ckeditor.com/ckeditor-5/demo/#document)
2. Paste some table into another one, both empty
To see the result more clearly, create a big selection and add a background color.

### ✔️ Expected result

Pasted cells are empty, there are no spaces added

### ❌ Actual result

Single spaces are added in pasted cells:  
  
![23_table_1](https://user-images.githubusercontent.com/34380544/85394746-5321f680-b54f-11ea-9221-d18291befa8b.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Let's take a quick look at it - it might be wrong handling of `&nbsp;` handling. `DomConverter` of something might have there wrong block filler mode set.
