### ISSUE TITLE
Merge->release merges should be ignored by changelog generator

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7489]
## Provide a description of the task

Currently the changelog generator is picking some extra noise:

![](https://user-images.githubusercontent.com/5353898/85420553-a73ed200-b573-11ea-81ef-a3f87ea93d92.png)

It would be nice if in case commit message is exactly "Merge branch 'master' into release" then the commit gets ignored.

**Comment by pomek** [comment]
There are more "internal" merge commits that could be skipped:

- Merge master into...
- Merge stable into...
- Merge branch master into...
- Merge branch 'master' into...

Also, `release` merges could be skipped too.

**Comment by mlewand** [comment]
That's right, as this is what I git when more commits were considered:

![](https://user-images.githubusercontent.com/5353898/85527847-8924b080-b60b-11ea-9a0a-937c511314e9.png)

It's way too noise

**Comment by pomek** [comment]
After some improvements:

![image](https://user-images.githubusercontent.com/2270764/85705682-bf346400-b6e1-11ea-9bf9-05acfa829e51.png)
