### ISSUE TITLE
Please provide an example code insert some text at the current cursor position of ckeditor

### ISSUE THREAD

**Issue by projjwalmaiti** [ckeditor/ckeditor5#749]
## 🐞 Is this a bug report or feature request? (choose one)
- Feature request

## 💻 Version of CKEditor
5

Just need an example code or a working code to insert say "Apple" at the current cursor position.

**Comment by Reinmar** [comment]
After the refactoring that we currently do it will be:

```js
editor.model.change( writer => {
    writer.insertText( 'foo', editor.model.document.selection.getFirstPosition() );
} );
```

You'll be able to do this once we release the next version (beta.1).

Right now it's more complicated and it requires importing the `Text()` constructor:

```js
import Text from '@ckeditor/ckeditor5-engine/src/model/text';

...

editor.document.enqueuChanges( () => {
    editor.document.batch().weakInsert( 
        editor.document.selection.getFirstPosition(),
        new Text( 'foo' )
    );
} );
```

So if you're using alpha.2 you'll need to build your editor from source like in https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html. Once beta is out, you won't need to do that – you'll be able to use a build.

**Comment by devmws** [comment]
@Reinmar 
I'm using vueJs v2.6 along side:
"@ckeditor/ckeditor5-build-classic": "^11.2.0",
"@ckeditor/ckeditor5-vue": "^1.0.0-beta.1",

I tried your very first solution, but I'm getting this error:
`Cannot read property 'change' of undefined`

My scenario is that I have a button when the user clicks on it should insert couple of words it the editor.
here is a snippet:
`<button
											:disabled="!addEditObj.tags"
											id="addTag"
											@click="addTag()"
											type="button"
											class="btn btn-icon btn-primary border-0"
										>
											<i class="btn-icon-wrapper pe-7s-plus m-0"></i>
										</button>`

and I'm importing these:
`import CKEditor from "@ckeditor/ckeditor5-vue";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";`

**Comment by yxlolxy** [comment]
I hava the same problem!

**Comment by yxlolxy** [comment]
I found the editor is a class component instead of a instance when i'm debugging, so i guess editor shound come from editor ref，get it like this `(this.$refs.editorRef as any).$_instance;`, then everything is ok!
