### ISSUE TITLE
To Add multiple attribute on inline element

### ISSUE THREAD

**Issue by pheeno** [ckeditor/ckeditor5#7494]
In our case, there had some required to trans multiple attrs from `Model` To `View` and it just keep in object, not for DOM,I tried to add `upcastDispatcher` on that but it can not locate the right position, I console on it and found which in `conversionApi` the `data.modelCursor` isn't correct  it throw this `[Exception: CKEditorError: model-position-path-incorrect: The position's path is incorrect.` 

versions

    "@ckeditor/ckeditor5-basic-styles": "^19.0.1",
    "@ckeditor/ckeditor5-core": "^19.0.1",
    "@ckeditor/ckeditor5-dev-utils": "^20.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^19.0.1",
    "@ckeditor/ckeditor5-essentials": "^19.0.1",
    "@ckeditor/ckeditor5-highlight": "^19.0.1",
    "@ckeditor/ckeditor5-paragraph": "^19.1.0",
    "@ckeditor/ckeditor5-restricted-editing": "^19.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^19.1.0",
    "@ckeditor/ckeditor5-widget": "^19.1.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^3.1.0",
    "style-loader": "^1.2.1",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"

original HTML

    <div id="editor">
      <p>
        before
        <span class="inlineSignificantData" data-significantParaDataType="pd02">test on multiple attrs</span>
        after
      </p>
    </div>
now i want to add another attrs on `Model` until it convert to `View` to extract, i confirm that it will pass the schema, but it finally shows wrong 
code is here

       data.upcastDispatcher.on('element:span', (evt, data, conversionApi) => {
       const { consumable, schema, writer } = conversionApi
       const { viewItem } = data
       if (consumable.test(viewItem, {classes:'inlineSignificantData',attributes: ['significantParaDataType' ,'extraCustomAttr','name'] })) {
        const { modelRange } = conversionApi.convertChildren(data.viewItem, data.modelCursor)
        writer.setAttributes(
           {
             name: 'inlineSignificantData',
             significantParaDataType:'psd02',
             extraCustomAttr:'test1',
           },
           modelRange
         )

       }
     },{priority:'high'})
in finally `HTML`  this span show in wrong place
![image](https://user-images.githubusercontent.com/32829824/85533009-bccefd00-b642-11ea-8291-e31213bbb394.png)

**Comment by Mgsy** [comment]
Hi, the main issue I see is that you've registered inline element (span) as an element. In CKEditor 5, the best way to handle inline elements is representing them as model attributes which convert to inline elements in the view, e.g. span. 

Here is a simple example of handling span element with a class attribute:

```javascript
class AllowSpanElement extends Plugin {
	init() {
	   this.editor.model.schema.extend( '$text', { allowAttributes: [ 'spanClasses' ] } );

	   // Add an upacast (view-to-model) converter for class attribute of a span.
	   this.editor.conversion.for( 'upcast' ).elementToAttribute( {
		    view: {
		     	name: 'span',
		     	attributes: { class: true }
		    },
	    	model: {
	     		key: 'spanClasses',
	     		value: viewElement => viewElement.getAttribute( 'class' )
	    	}
	   	} );

	   // Add an downcast (model-to-view) converter for class attribute of a span.
	   this.editor.conversion.for( 'downcast' ).attributeToElement( {
	    	model: 'spanClasses',
	    	view: ( modelAttributeValue, viewWriter ) => {
	     		return viewWriter.createAttributeElement( 'span', {
	      			class: `${ modelAttributeValue }`
	     		} );
	    	}
	   } );
	}
}
```

It should give you an idea, how to handle such elements.

**Comment by Mgsy** [comment]
> excellent it's very helpful thank you !

No problem, have fun with CKEditor 5 :)

**Comment by chille1987** [comment]
> Hi, the main issue I see is that you've registered inline element (span) as an element. In CKEditor 5, the best way to handle inline elements is representing them as model attributes which convert to inline elements in the view, e.g. span.
> 
> Here is a simple example of handling span element with a class attribute:
> 
> ```js
> class AllowSpanElement extends Plugin {
>     init() {
>        this.editor.model.schema.extend( '$text', { allowAttributes: [ 'spanClasses' ] } );
> 
>        // Add an upacast (view-to-model) converter for class attribute of a span.
>        this.editor.conversion.for( 'upcast' ).elementToAttribute( {
>             view: {
>                  name: 'span',
>                  attributes: { class: true }
>             },
>             model: {
>                  key: 'spanClasses',
>                  value: viewElement => viewElement.getAttribute( 'class' )
>             }
>        } );
> 
>        // Add an downcast (model-to-view) converter for class attribute of a span.
>        this.editor.conversion.for( 'downcast' ).attributeToElement( {
>             model: 'spanClasses',
>             view: ( modelAttributeValue, viewWriter ) => {
>                  return viewWriter.createAttributeElement( 'span', {
>                       class: modelAttributeValue
>                  } );
>             }
>        } );
>     }
> }
> ```
> 
> It should give you an idea, how to handle such elements.

Hey @Mgsy is there a way to pass multiple attributes? For example I want to add all the classes from example above and data-id and data-name attributes

**Comment by paqu83** [comment]
I have the same question as [chille1987](https://github.com/chille1987) . Anyone know hot to work with two attributes?

**Comment by chille1987** [comment]
I believe something like this should work:

```
export default class GlossaryEditing extends Plugin {
    init() {
        this._defineSchema();
        this._defineConverters();

        this.editor.commands.add('insertGlossary', new InsertGlossaryCommand(this.editor))
        this.editor.commands.add('removeGlossary', new RemoveGlossaryCommand(this.editor))
    }

    _defineSchema() {
        const schema = this.editor.model.schema;
        schema.extend('$text', { allowAttributes: ['glossary'] })
    }

    _defineConverters() {
        const conversion = this.editor.conversion

		conversion.for('upcast').elementToAttribute( {
			view: {
				name: 'span',
				classes: 'hj-glossary-item',
				attributes: {
					'data-id': true,
					'data-definition': true,
					'data-upvotes': true,
					'data-downvotes': true,
					'data-user-name': true,
					'data-user-id': true
				}
			},
			model: {
				key: 'glossary',
				value: viewItem => {
					const glossaryAttribute = editor.plugins.get('Glossary').toGlossaryAttribute(viewItem, {
						id: viewItem.getAttribute('data-id'),
						definition: viewItem.getAttribute('data-definition'),
						upvotes: viewItem.getAttribute('data-upvotes'),
						downvotes: viewItem.getAttribute('data-downvotes'),
						userid: viewItem.getAttribute('data-user-id'),
						username: viewItem.getAttribute('data-user-name')
					});

					return glossaryAttribute;
				}
			},
			converterPriority: 'high'
		});

		conversion.for('downcast').attributeToElement( {
			model: 'glossary',
			view: (modelAttributeValue, { writer }) => {
				// Do not convert empty attributes (lack of value means no mention).
				if (!modelAttributeValue) {
					return;
				}

				return writer.createAttributeElement('span', {
					class: 'hj-glossary-item',
					'data-id': modelAttributeValue.id,
					'data-definition': modelAttributeValue.definition,
					'data-upvotes': modelAttributeValue.upvotes,
					'data-downvotes': modelAttributeValue.downvotes,
					'data-user-id': modelAttributeValue.userid,
					'data-user-name': modelAttributeValue.username
				});
			},
			converterPriority: 'high'
		});
    }
}
```

**Comment by paqu83** [comment]
thank you @chille1987  that saved my day! My use-case is working fine now.

**Comment by stparis10** [comment]
Please @chille1987, what is done in toGlossaryAttribute() methode?

**Comment by chille1987** [comment]
> Please @chille1987, what is done in toGlossaryAttribute() method?

glossary.js
```
import GlossaryEditing, { _toGlossaryAttribute } from './glossaryediting';
import GlossaryUI from './glossaryui';
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import './styles.css'

export default class Glossary extends Plugin {
	toGlossaryAttribute( viewElement, data ) {
		return _toGlossaryAttribute( viewElement, data );
	}

	static get requires() {
		return [GlossaryEditing, GlossaryUI];
	}

	static get pluginName() {
		return 'Glossary';
	}
}
```


glossaryediting.js
```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import InsertGlossaryCommand from './insertglossarycommand';
import RemoveGlossaryCommand from './removeglossarycommand';
import { uid } from 'ckeditor5/src/utils';

export default class GlossaryEditing extends Plugin {
    init() {
        this._defineSchema();
        this._defineConverters();

        this.editor.commands.add('insertGlossary', new InsertGlossaryCommand(this.editor))
        this.editor.commands.add('removeGlossary', new RemoveGlossaryCommand(this.editor))
    }

    _defineSchema() {
        const schema = this.editor.model.schema;
        schema.extend('$text', { allowAttributes: ['glossary'] })
    }

    _defineConverters() {
        const conversion = this.editor.conversion

		conversion.for('upcast').elementToAttribute( {
			view: {
				name: 'span',
				classes: 'hj-glossary-item',
				attributes: {
					'data-id': true,
					'data-definition': true,
					'data-upvotes': true,
					'data-downvotes': true,
					'data-user-name': true,
					'data-user-id': true
				}
			},
			model: {
				key: 'glossary',
				value: viewItem => {
					const glossaryAttribute = editor.plugins.get('Glossary').toGlossaryAttribute(viewItem, {
						id: viewItem.getAttribute('data-id'),
						definition: viewItem.getAttribute('data-definition'),
						upvotes: viewItem.getAttribute('data-upvotes'),
						downvotes: viewItem.getAttribute('data-downvotes'),
						userid: viewItem.getAttribute('data-user-id'),
						username: viewItem.getAttribute('data-user-name')
					});

					return glossaryAttribute;
				}
			},
			converterPriority: 'high'
		});

		conversion.for('downcast').attributeToElement( {
			model: 'glossary',
			view: (modelAttributeValue, { writer }) => {
				// Do not convert empty attributes (lack of value means no mention).
				if (!modelAttributeValue) {
					return;
				}

				return writer.createAttributeElement('span', {
					class: 'hj-glossary-item',
					'data-id': modelAttributeValue.id,
					'data-definition': modelAttributeValue.definition,
					'data-upvotes': modelAttributeValue.upvotes,
					'data-downvotes': modelAttributeValue.downvotes,
					'data-user-id': modelAttributeValue.userid,
					'data-user-name': modelAttributeValue.username
				});
			},
			converterPriority: 'high'
		});
    }
}

export function _addGlossaryAttributes( baseGlossaryData, data ) {
	return Object.assign( { uid: uid() }, baseGlossaryData, data || {} );
}

export function _toGlossaryAttribute( viewElementOrGlossary, data ) {
	const dataGlossary = viewElementOrGlossary.getAttribute('data-id');
	const textNode = viewElementOrGlossary.getChild( 0 );

	// Do not convert empty mentions.
	if ( !textNode ) {
		return;
	}

	const baseGlossaryData = {
		id: dataGlossary,
	};

	return _addGlossaryAttributes( baseGlossaryData, data );
}
```

**Comment by devraj112** [comment]
I am new to ckeditor 5. How can I crack the custom plugin creation I am struggling to work out with the schema and conversion. I have went through the documentation. Can you guys help?

**Comment by Witoso** [comment]
@devraj112 please create a new issue, and let us know what's not clear :)

**Comment by ItsFrankieD** [comment]
Figured I'd toss in my two cents. Although assigning custom properties to the `AttributeElement` works in theory, I don't believe it properly represents the `AttributeElement` during conversion. Not to mention that we have `writer.setCustomProperty()` and `AttributeElement.getCustomProperty()` for that.

The string returned during the upcast conversion is intended to be the sole value representing what eventually gets downcast to the view. Anything else represents the data model of the `AttributeElement`, e.g. non-rendered properties, methods, etc. The cleanest solution I could come up with was to `JSON.stringify()` the view element's attribute before pushing them to the `AttributeElement`.

With that being said, am I wrong in my assumption? Is the `Object.assign()` option a CKEditor standard that I've missed? I'd love to hear any other solutions to this conundrum!

```js
export default class SomePlugin extends Plugin {
  init() {
    this.editor.model.schema.extend('$text', {
      allowAttributes: [
        'somePlugin',
      ]
    });

    this.editor.conversion.for('upcast').elementToAttribute({
      view: {
        name: 'span',
        attributes: [
          'data-custom-1',
          'data-custom-2',
        ],
      },
      model: {
        key: 'somePlugin',
        value: (viewElement) => {
          // Stringify the attributes for storage in the model attribute.
          return JSON.stringify({
            'data-custom-1': viewElement.getAttribute('data-custom-1'),
            'data-custom-2': viewElement.getAttribute('data-custom-2'),
          });
        },
      },
    });

    this.editor.conversion.for('downcast').attributeToElement({
      model: 'somePlugin',
      view: (modelAttributeValue, conversionApi) => {
        // Parse the model attribute value back into an object.
        return conversionApi.writer.createAttributeElement(
          'span',
          JSON.parse(modelAttributeValue)
        );
      },
    });
  }
}
```
