### ISSUE TITLE
Scoped breaking changes are getting duplicated by changelog generator

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7495]
## 📝 Provide detailed reproduction steps (if any)

While preparing changelog for 20.0.0 I had this case where the "MINOR BREAKING CHANGE (table): The \`TableNavigation\` plugin renamed to \`TableKeyboard\`." would be duplicated (one occurrence in BC section, and second in "other changes" section, see e7a2353).

### ✔️ Expected result

"MINOR BREAKING CHANGE (table): The \`TableNavigation\` plugin renamed to \`TableKeyboard\`." should be noted only in BC section.

### ❌ Actual result

Entry is not stripped in the "Other changes" seciton.

**Comment by pomek** [comment]
The commit described in the issue - https://github.com/ckeditor/ckeditor5/commit/4d2f5f9b9f298601b332f304da66333c52673cb8.

Breakpoint (if we'll need to back to the issue in the future).
