### ISSUE TITLE
PHP code in editor

### ISSUE THREAD

**Issue by fahimaga** [ckeditor/ckeditor5#750]
Hi,
Can you please help me in adding php code in ckeditor

**Comment by Reinmar** [comment]
Hi!

What do you mean by adding PHP code in CKEditor? Embedding it like a code snippet:

```php
      <?php
      for ($number = 1; $number <= 10; $number++) {
        // ...
      }; ?>
```

Or do you mean something like CKEditor 4's [protected source](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-protectedSource)?

**Comment by fahimaga** [comment]
I want to execute the php code in browser via CK editor
eg. If I write <?php echo "good" ; ?>
It should give out put in browser as good 
not <?php echo "good" ; ?>

**Comment by jodator** [comment]
The short answer is you cannot execute server side inside browser. Actually you cannot execute any language that is not supported by the browser itself - and as AFAIK the [only one supported](https://stackoverflow.com/questions/22947558/why-dont-browsers-interpret-more-programming-languages) is JavaScript.

Probably most of the thing you'd like to execute with PHP is in some way  doable in JavaScript. 

Also while saving the editor contents on the server you could process it by any language your web server process so you could parse PHP tags before serving it to users' browsers but... this would be a huge security hole. I would not recommend it doing it on production server unless running this code in good isolation from your infrastructure. 

Even online PHP interpreters ([link](http://www.runphponline.com/), [link](http://www.writephponline.com/)) post PHP code to server and returns it to the browsers and I suspect that they run user code in some safe way.

As such I'm closing this as invalid - if you have additional questions you can also use stackoverflow to ask [questions about CKEditor 5](https://stackoverflow.com/questions/tagged/ckeditor5).
