### ISSUE TITLE
CKEditor 4 HTML interpreted wrong by CKEditor 5

### ISSUE THREAD

**Issue by aflipphi19** [ckeditor/ckeditor5#7500]
In our system we are use the CKEditor 4 as well as the Vue CKEditor 5 component.
The big issue now is that the content saved by the CKEditor 4 is interpreted completely different by CKEditor 5

For instance:
`<p><strong>Bestratingsweb.nl</strong><br />
<span style="font-family:calibri,helvetica,sans-serif">Stationsweg&nbsp;Oost&nbsp;194c</span><br />
<span style="font-family:calibri,helvetica,sans-serif">3931&nbsp;EX Woudenberg</span><br />
<img src="https://www.bestratingsweb.nl/bestanden/text-editor/image-20191230153534-1.png" style="height:12px; width:12px" /><span style="font-family:calibri,helvetica,sans-serif"> 0318 - 745&nbsp;743</span><br />
<img src="https://www.bestratingsweb.nl/bestanden/text-editor/image-20191230153534-2.png" style="height:12px; width:12px" /><span style="font-family:calibri,helvetica,sans-serif">&nbsp;</span><a href="mailto:info@bestratingsweb.nl" target="_blank"><span style="font-family:calibri,helvetica,sans-serif"><strong>info@bestratingsweb.nl</strong></span></a><br />
<img src="https://www.bestratingsweb.nl/bestanden/text-editor/image-20191230153534-3.png" style="height:12px; width:12px" /><span style="font-family:calibri,helvetica,sans-serif"><strong> </strong></span><a href="https://www.bestratingsweb.nl/" target="_blank"><span style="font-family:calibri,helvetica,sans-serif"><strong>www.bestratingsweb.nl</strong></span></a><br />
<br />
<a href="https://www.feedbackcompany.com/nl-nl/reviews/bestratingsweb-nl"><img src="https://www.bestratingsweb.nl/bestanden/email/E-mailhandtekening_Bestratingsweb.nl.jpg" style="height:225px; width:420px" /></a></p>`

is tranformed by CKEditor 5 to:
`<figure class=\"image\"><img src=\"https://www.bestratingsweb.nl/bestanden/text-editor/image-20191230153534-1.png\"></figure><p>0318 - 745&nbsp;743<br>&nbsp;</p><figure class=\"image\"><img src=\"https://www.bestratingsweb.nl/bestanden/text-editor/image-20191230153534-2.png\"></figure><p>&nbsp;<a href=\"mailto:info@bestratingsweb.nl\"><strong>info@bestratingsweb.nl</strong></a><br>&nbsp;</p><figure class=\"image\"><img src=\"https://www.bestratingsweb.nl/bestanden/text-editor/image-20191230153534-3.png\"></figure><p><a href=\"https://www.bestratingsweb.nl/\"><strong>www.bestratingsweb.nl</strong></a><br><br>&nbsp;</p><figure class=\"image\"><img src=\"https://www.bestratingsweb.nl/bestanden/email/E-mailhandtekening_Bestratingsweb.nl.jpg\"></figure>`

notice all the unwanted `<figure>` tags and in CKEditor 4 the images and text line up correctly.
In CKeditor 5 the image is shown above the line which is unwanted.

How can we fix this.
Upgrading all texteditors to CKEditor 5 is not an options (for the coming few years)

**Comment by Mgsy** [comment]
Hi, thanks for the report. At first, you'll need to know that CKEditor 4 and CKEditor 5 have different architecture and basically, content created in CKEditor 4 might not be compatible with CKEditor 5. Please, see our [Migration from CKEditor 4 guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html) to learn more.

You might also find useful our [CKEditor 5 architecture guides](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/intro.html).
