### ISSUE TITLE
`ckeditor-duplicated-modules` error when using `CKEditor` react component. Compatability issue v19 vs v20?

### ISSUE THREAD

**Issue by asimkt** [ckeditor/ckeditor5#7501]
## Question 1

1. Navigate to https://codesandbox.io/s/ckeditor-5-zf94v?file=/src/index.js
2. The build is throwing error `CKEditorError
ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules`

### ❌ Actual result
Throwing error

### Question 2
1. Remove the Alignment import from the same code. (https://codesandbox.io/s/ckeditor-5-z5p0q) Or change the version to `20.0.0`
2. The build is fine

I know it's a major version bump. Is this expected behavior?

We should show a more descriptive error message about a version mismatch.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, `ckeditor-duplicated-modules` error occurs often when plugins have different version. So in this case, try upgrading _Alignment_ to _20.0.0_. 
Apart from that, please make sure you are familliar with [react integration docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html). In your case, if you want to add some plugins, especially the part about [customising editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds) and [building from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).

**Comment by asimkt** [comment]
Thanks @FilipTokarski  Closing this issue for now.
