### ISSUE TITLE
Remove inline styles when paste to editor

### ISSUE THREAD

**Issue by ppazuchowski** [ckeditor/ckeditor5#7505]
Hi,

I would like to paste to editor table from Word, but I want to strip all inline styles.
How to configure this? Is it possible in CKEditor5?

Thanks

**Comment by QuentinLeGoff** [comment]
On my side, I've created a plugin that listens paste event and clear all styles from nodes that will be inserted.

**Comment by Mgsy** [comment]
Hi, currently, there's no possibility to strip those styles, however, as @QuentinLeGoff said, you can create your custom plugin which will listen on paste and process HTML. See our [Clipboard guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/clipboard.html#handling-clipboard-input-differently).

**Comment by Reinmar** [comment]
The content processed for paste is converted in the context of `$clipboardHolder` root element, so it may be possible to write something like this:

```javascript
editor.model.schema.addAttributeCheck( ( ctx, attributeName ) => {
    if ( ctx.startsWith( '$clipboardHolder' ) ) {
         return false;
    }
} );
```

However, this will also affect content copied and pasted within the editor. Limiting this to content coming from "outside" is trickier.

If you want to better target the filter, then listening to the `#paste` event would be the only option.

**Comment by mitulsimform** [comment]
I want to do the same any luck with this?

**Comment by galago** [comment]
> 

Can you share with plugin with us?

**Comment by NomisGnos** [comment]
I thought I'd share a snippet of the code I created to remove inline styles.  Note: This may be overkill but it seems like [General HTML Support](https://ckeditor.com/docs/ckeditor5/latest/api/html-support.html) would be a better way to solve this question but the API is not ready for production and subject to change.

This works on PASTING as elements are created it will execute:
```
import { Command } from 'ckeditor5/src/core';

export default class RemoveInlineStylesCommand extends Command {
  execute() {
    const { model } = this.editor;

    model.change((writer) => {
    });
  }

  refresh() {
    const editor = this.editor;

    editor.data.upcastDispatcher.on("element", (evt, data, conversionApi) => {
      if ( data.viewItem.hasAttribute('style') ) {
        if ( data.viewItem.isEmpty ) {
          return;
        }
        var dataItems = data.modelRange.getItems();
        for ( let item of dataItems ) {
          for ( let attribute of item.getAttributeKeys()) {
            var attrObj = item.getAttribute(attribute);
            if ( attrObj.hasOwnProperty('styles') ) {
              delete attrObj.styles;
              conversionApi.writer.setAttribute(attribute, attrObj, item);
            }
          }
        }
      }
    },
    {
      priority: "low",
    });
  }
}
```

and

this is good when a user tries to hit the "SOURCE" button to add their own inline styles.

```
import { Plugin } from "ckeditor5/src/core";
import RemoveInlineStylesCommand from "./removeinlinestylesCommand";

/**
 * The Remove inline styles plugin
 *
 * @internal
 */
export default class RemoveInlineStylesEditing extends Plugin {
  init() {
    this.editor.commands.add("removeinlinestyles", new RemoveInlineStylesCommand(this.editor));

    this.editor.data.downcastDispatcher.on("insert", (evt, data, conversionApi) => {
      if ( data.item.hasOwnProperty('name') ) {
        for ( const attribute of data.item.getAttributeKeys() ) {
          var attrObj = data.item.getAttribute(attribute);
          if ( attrObj.hasOwnProperty('styles') ) {
            delete attrObj.styles;
            conversionApi.writer.setAttribute(attribute, attrObj, data.item);
          }
        }
        removeChildStyles(data.item, conversionApi);
      }
    },
    {
      priority: "low",
    });
  }
}

function removeChildStyles(item, conversionApi) {
  for ( var i=0; i<item.childCount; i++ ) {
    var child = item.getChild(i);
    for ( const attribute of child.getAttributeKeys() ) {
      var attrObj = child.getAttribute(attribute);
      if ( attrObj.hasOwnProperty('styles') ) {
        delete attrObj.styles;
        conversionApi.writer.setAttribute(attribute, attrObj, child);
      }
    }
  }
}
```
