### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by pulciux** [ckeditor/ckeditor5#751]
- Bug report

## 📋 Steps to reproduce

1. It happens in Chrome  63.0.3239.108 (64 bit) - desktop and mobile tested. No further browsers tested. 
2. Leaving a DIV element bound to an inline editor for another element which gets focus, it ends up in a never ending while loop when it calls getParentUIElement from domconverter.js

domNode is undefined and ancestors.length too but it will never be false.
```javascript
	/**
	 * Returns parent {@link module:engine/view/uielement~UIElement} for provided DOM node. Returns `null` if there is no
	 * parent UIElement.
	 *
	 * @param {Node} domNode
	 * @return {module:engine/view/uielement~UIElement|null}
	 */
	getParentUIElement( domNode ) {
		const ancestors = getAncestors( domNode );

		// Remove domNode from the list.
		ancestors.pop();

		while ( ancestors.length ) {
			const domNode = ancestors.pop();
			const viewNode = this._domToViewMapping.get( domNode );

			if ( viewNode && viewNode.is( 'uiElement' ) ) {
				return viewNode;
			}
		}

		return null;
	}

```

**Comment by Reinmar** [comment]
Hi! Thanks for the report.

I tried to understand what happens, but it seems I don't. There's the `ancestors` array from which we pop an item on each iteration. So no matter what happens `ancestors.length` should become `0` at some point. Are you sure it never is? How could that happen?

Also, could you explain what do you do exactly? Even when fixing such low-level issues. we'd like to have a higher-level scenario to make sure that such a problem will never occur again.

**Comment by pulciux** [comment]
Hi Reinmar,
it took a while but I've figured out what it triggers the infinite loop.
I was integrating ckeditor5 into my framework and I've noticed that after a certain event was fired by a different element it was ending in an infinite loop.
The event was triggering a complex cascade of events but eventually, I've found it was also trying to reinitiate the editor on the same div.
So I've reproduced it in a simpler code and it is actually what it causes the infinite loop.

If for some reason you have initiated an inline editor and then you try to reinitiate it, it will end in an infinite loop.

```html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <script type="text/javascript" src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/inline/ckeditor.js"></script>
      <script type="text/javascript">
      	function initEditor(sel) {
		    try {
		        var elm = document.querySelector(sel);
		        InlineEditor
		                .create(elm)
		                .then(editor => {
		                    console.log(editor);
		                })
		                .catch(error => {
		                    console.error(error);
		                });

		    } catch (err) {
		        console.error(err.message);
		    }
      	}
      </script>      
   </head>
   <body>
   		<div id="mfield-test" contenteditable="true" style="border: 1px solid gray; margin-bottom: 200px;">
   			<p>This is a test text</p>
   		</div>
   	  	<div onclick="initEditor('#mfield-test');;" style="border: 1px solid red; width: 200px;">init editor again</span>
        <script type="text/javascript">
        	initEditor('#mfield-test');
        </script>
   </body>
</html>
```
to reproduce it, run the example and then click on 'init editor again'

**Comment by Reinmar** [comment]
Yep, it's a known problem. You can't initialise two editors on one element because they start to override each others' changes in that element.

DUP of https://github.com/ckeditor/ckeditor5/issues/746.
