### ISSUE TITLE
The mention does not appear as expected

### ISSUE THREAD

**Issue by dazedsanjin** [ckeditor/ckeditor5#7511]
## 📝 Provide detailed reproduction steps (if any)

When I finish typing some content and press @, the mention box does not appear as expected, it must appear after typing a space 

### ✔️ Expected result
it can appear after typing  content and press @

### ❌ Actual result
![](https://s1.ax1x.com/2020/06/28/N2gTLd.jpg)

## 📃 Other details

* Browser:  Chrome 83.0.4103.106
* OS:  Windows 10
* CKEditor version: ckeditor5-build-classic: ^20.0.0
* Installed CKEditor plugins: mention

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, can you tell us more about your use case? Why you'd expect a mention will appear while inserting a marker as a part of the word? The current behaviour makes sense for me, as the mention won't be included in some word, e.g. "This is#tomato" vs. "This is #tomato".
