### ISSUE TITLE
Uncaught ReferenceError: ClassicEditor is not defined

### ISSUE THREAD

**Issue by CriticaIError** [ckeditor/ckeditor5#7512]
## 📝 Provide detailed reproduction steps (if any)

1. Download ckeditor and create a custom build, after downloading files, upload them to your host, in my case, localhost.
2. Folder is located at: /static/ckeditor/ckeditor.js
3. Include the script in your code and create a div with class editor.
4. After creating the div and including the script, you will see a normal box instead of the desired one and if you check console it will say: 
- Uncaught ReferenceError: ClassicEditor is not defined ( If i add this one )
- Uncaught ReferenceError: InlineEditor is not defined ( Or this one, depending the case )

### ✔️ Expected result

- Having the CKEditor customized working on my website.

### ❌ Actual result
![image](https://user-images.githubusercontent.com/58123351/85977164-081e3e00-b9aa-11ea-9051-a74dff3e7df8.png)

Not even loading.

## 📃 Other details

OS: Windows 10
CKEditor Version: 5

NOTE: If i change my local path to the cdn path it works without that error, but if i try to use the path which is the one i want to use, it doesn't work.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I didn't have any problems creating a custom build and running it, so please make sure you follow our giude on [creating custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and that the path to the build is correct. I'm afraid the problem might be somewhere on your side. In any case, if you'll not be able to debug it yourself, we'll need more information ( i.e. editor configuration ) and precise steps ( with code ), to look into this.

**Comment by CriticaIError** [comment]
Well im retarded, as you commente that i made another download with new stuff and it works like a charm, not sure what i did wrong the first time, output:

![image](https://user-images.githubusercontent.com/58123351/85993429-56403b00-b9c4-11ea-8ae4-244c93d7c247.png)

**Comment by mohamed-aiman** [comment]
having same issue

**Comment by rmaxx** [comment]
Same issue, the editor works when initiated from inside the /sample/ckeditor.js , but i can't start 'ClassicEditor.create' from outside the script, so lets say on a onload for all editors with class ''x'.  What am i missing? Should i export it , and where?

**Comment by Chanticrow** [comment]
> Same issue, the editor works when initiated from inside the /sample/ckeditor.js , but i can't start 'ClassicEditor.create' from outside the script, so lets say on a onload for all editors with class ''x'. What am i missing? Should i export it , and where?

I have the same issue.  Just upgraded to v32 from v31.1.  The build of v31.1 I created last week exports "ClassicEditor" whereas the v32 I just built exports "CKSource".  Switching from "ClassicEditor.create" to "CKSource.Editor.create" fixed the problem, but I should not have to make this change.

**Comment by rmaxx** [comment]
i added window.ClassicEditor = ClassicEditor to the source, which seems like a workaround, but it works. Ill try the CKSource.Editor.create later, see how that works.. Tnx.

**Comment by skipperhoa** [comment]
You npm install --save @ckeditor/ckeditor5-build-classic , after then you change url script: 
<script src="./node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js"></script>
you can see : https://github.com/ckeditor/ckeditor5-build-classic

**Comment by Daydreamer-ia** [comment]
It's so interesting. I meet the same issue. **I cannot get ClassicEditor like sample do**. But it works when i try **windows.ClassicEditor**

**Comment by Russellmd** [comment]
The same issue with custom build. I added in my custom build all non-premium plugins. It works fine with CDN urls, but not with my custom build. To make it working I'm using now

`CKSource.Editor.create(...)`

However, I don't see in documentation such case
