### ISSUE TITLE
'start' attribute on ordered list seems to be ignored

### ISSUE THREAD

**Issue by npolauer** [ckeditor/ckeditor5#7514]
## 📝 Provide detailed reproduction steps (if any)

```
<div>
    <ol start='1'>
        <li>first list</li>
    </ol>

    <p>separator</p>

    <ol start='2'>
        <li>second list</li>
    </ol>

    <p>separator</p>

    <ol start='3'>
        <li>third list</li>
    </ol>
</div>
```
**Note: separators exists to prevent the editor to combine the lists to one**

1. set the provided HTML as content of the editor `setData()`

### ✔️ Expected result
- the first list starts with number 1
- the second list starts with number 2
- the third list starts with number 3

> ![image](https://user-images.githubusercontent.com/56922874/86014573-cc728b00-ba20-11ea-8bc7-03fbc3b9b3c2.png)

### ❌ Actual result
- all lists start with number 1
- 'start' attributes seem to be ignored

Tested with the Demo Editor (https://ckeditor.com/ckeditor-5/demo/)
![image](https://user-images.githubusercontent.com/56922874/86014697-f4fa8500-ba20-11ea-95d6-b12b8dc904b1.png)

**Comment by Mgsy** [comment]
Hi, thanks for the report. The current behaviour occurs because CKEditor 5 doesn't support `start` attribute on lists. There's an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1032) for it, feel free to add :+1: to the first post and join the discussion to bump its popularity.
