### ISSUE TITLE
Integrate to-do list with autoformat

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7518]
## 📝 Provide a description of the new feature

Autoformat could also support inserting to-do lists with `[ ] ` - which would symbolize a checbox.

GitHub, for instance, uses a `- [ ] ` marker for todo checkbox. This will work out of the box (given #6170 is done) as dash (`-`) will transform line to a unordered list and subsequent `[ ] ` will turn it into a to-do item as expected.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Adding to a discussion, should there be more combinations that trigger the to-do list rather than `- [ ]` alone, for example.

I personally typically try to use `[ ] - ` and then be surprised that GH doesn't get it :smile: So in addition to `- [ ]` I suggest handling `[ ] ` too.

Another thing: should the space between the bracket be mandatory?

**Comment by Reinmar** [comment]
I always try `[ ] text` and I'm then pissed that it doesn't work :D

**Comment by jodator** [comment]
For me PITA is lack of `[]` support in GH.

In Notion you'd type `[]` only (OTOH in Notion `[ ]` doesn't work...).

What should trigger - I think `[]` or `[ ]` is enough as \`- \` would trigger list (just checked Notion):

1.  type `-`
2.  type ` ` (space)
3.  paragraph gets turned into list item
4.  type `[]`
5.  list item gets turned into todo list item

**Comment by mlewand** [comment]
> *   type `-`
> *   paragraph gets turned into list item
> *   type `[]`
> *   list item gets turned into todo list item

Yes, this might also work :+1:

So based on our comments I can see that the best option is to look at beginning that would match following regexp: `\s\[\s\]\s`:

*    `[ ]` 
*   `[ ]` 
*    `[]` 
*   `[]`
