### ISSUE TITLE
LinkImage is not saved if switched to target=_blank

### ISSUE THREAD

**Issue by airstarh** [ckeditor/ckeditor5#7519]
## 📝 Steps

1  Insert image from other site through copy-paste.
2. Add link on it and set switcher to open link in new tab (target=_blank)
3. Save link

### ✔️ Expected result

After content is saved - the clicked image should be opened in new window (tab)

### ❌ Actual result

Target=_blank is not set. Image-link is opened in the same window (tab).

## 📃 Other details

* Browser: Chrome latest
* OS: Windows 10 latest
* CKEditor version: 20.0.0
* Installed CKEditor plugins: LinkImage latest

**Comment by Reinmar** [comment]
Thank you! We will try to squeeze it into the current iteration.
