### ISSUE TITLE
setSelection doesnt work on multiple ranges

### ISSUE THREAD

**Issue by BurakKartal1** [ckeditor/ckeditor5#7520]
Im trying to add find/replace and this is what i have so far.
```

      const documentRange = this.editor.model.createRangeIn(this.editor.model.document.getRoot());
      let selectionRanges = [];
      for (const node of documentRange.getWalker(undefined, false)) {
        if (node.item.data !== undefined && node.item.data.includes(searchString)) {
          let occurences = getIndicesOf(searchString, node.item.data)
          if (occurences.length !== undefined) {
            for (let i = 0; i < occurences.length; i++) {
              selectionRanges.push(
                this.editor.model.createRange(
                  this.editor.model.createPositionAt(node.item.textNode.parent, occurences[i]),
                  this.editor.model.createPositionAt(node.item.textNode.parent, (occurences[i] + searchString.length))
                )
              )
            }
          }
        }
      }
      writer.setSelection( selectionRanges );
```

[as documentary says](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-setSelection)
```
// Sets selection to given ranges.
const ranges = [ writer.createRange( start1, end2 ), writer.createRange( start2, end2 ) ];
writer.setSelection( range );
```

this should work but when i run. it only selects the last match.

**Comment by Mgsy** [comment]
Hi, I don't know how your plugin works and how exactly you change the selection, however, I was able to create the selection for multiple ranges using [Writer API](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html). See the example below:

```javascript
editor.model.change( writer => {
	const root = editor.model.document.getRoot();
	
	const start1 = writer.createPositionFromPath( root, [ 0, 0 ] );
	const end1 = writer.createPositionFromPath( root, [ 0, 2 ] );

	const start2 = writer.createPositionFromPath( root, [ 1, 0 ] );
	const end2 = writer.createPositionFromPath( root, [ 1, 2 ] );

	writer.setSelection( [ writer.createRange( start1, end1 ), writer.createRange( start2, end2 ) ] );
} );
```

I recommend reviewing your code and verifying if your selection contains multiple ranges before going further.

**Comment by Reinmar** [comment]
BTW, multi-range selection works only in Firefox. We also support it in tables on all browsers by a completely custom implementation. In all other cases, it's not going to render.

As for find&replace it should rather be approached with something like [model markers.](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#markers)
