### ISSUE TITLE
After backspacing into a link, the caret should still stay outside

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7521]
## 📝 Provide a description of the improvement

So we changed recently (#1016) the behavior when clicking after the link. You will now be placed "outside" the link.

However, the same isn't true when you backspace to that place.

![](https://user-images.githubusercontent.com/156149/86126032-ee7e1300-badd-11ea-9ba4-e533d12cbc71.gif)

I think we should be consistent here.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I'm not sure, though, what should happen if you delete one more letter (one of the link's letters).

**Comment by kherona** [comment]
I am having worse problem now https://github.com/ckeditor/ckeditor5/issues/7646 I cannot publish or use this component if this doesn't get fixed (I tried using other builds but ran into bunch of other bugs when integrating plugins). Probably I'll need to get too many likes to get a response..

**Comment by jodator** [comment]
> I'm not sure, though, what should happen if you delete one more letter (one of the link's letters).

It should stay as today if you leave the link: you delete link but selection does not have a link attribute.

**Comment by jodator** [comment]
I've tested the PR solution and I have the same feeling as @oleq - it works nice. However I've found something on master that troubles me.

1.  The solution addresses <kbd>backspace</kbd> but maybe the same should happen on <kbd>del</kbd>? Kinda weird that selecting some text after a link and deleting it behaves differently on those keys (but maybe I'm lacking something in terms of deletion directionality?)
2.  Select + type:

![](https://user-images.githubusercontent.com/247363/88175402-1b799d80-cc26-11ea-90bb-50b4187eda9e.gif)

So on the above GIF you can see that depending on the selection direction behaves differently - it looks like the link attribute "glues" itself to the selection. It was a surprise for me as my intention was (beside testing the PR :stuck\_out\_tongue: ) to write something in place of the selection. Ps.: when `Clipboard` plugin is present paste works in the "intended" way.

The PR is OK and depending on question 1 - I'm for merging it as it brings value. The "2" can be a follow up.

**Comment by oleq** [comment]
@jodator Both concerns are valid in my opinion. They don't block the PR, though, especially that the iteration is about to finish. I think they should become followups and we can address them in the next iteration.
