### ISSUE TITLE
Placeholder wigit inverts text for RTL languages

### ISSUE THREAD

**Issue by allen138** [ckeditor/ckeditor5#7526]
## 📝 Provide detailed reproduction steps (if any)

1. Compose text with placeholders in MS Word using a RTL language such as Hebrew
2. Copy/Paste the text into a CKEditor with the placeholder plugin enabled
3. Notice the placeholders are displayed in the opposite direction. 

### ✔️ Expected result
1. The text show follow the same direction as it was composed in MS Word

### ❌ Actual result
1. The placeholders are rendered in the opposite direction as they were composed in word. For example, [[First Name]] [[Middle Name]] [[Last Name]] will be rendered [[Last Name]] [[Middle Name]] [[First Name]]

## 📃 Other details

* Browser: All, but tested on Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* OS: Windows 10
* CKEditor version: 4.12.1
* Installed CKEditor plugins: placeholder

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by allen138** [comment]
Related to: https://github.com/ckeditor/ckeditor4/issues/4131

**Comment by FilipTokarski** [comment]
Hi, CKEditor4 and CKEditor5 are completely separate applications and this repository/issue tracker is for CKEditor5. Please report your issue in [CKEditor4 issue tracker](https://github.com/ckeditor/ckeditor4/issues).
