### ISSUE TITLE
What does --snippets option filter?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7527]
## 📝 Provide a description of requested docs changes

I was trying to build only the following guide with its snippet: http://127.0.0.1:8080/ckeditor5/20.0.0/examples/builds/classic-editor.html

So, I tried (using the guide name):

```
yarn docs --skip-api --snippets=classic-editor
```

But it throws errors.

I also tried (using the snippet name):

```
yarn docs --skip-api --snippets=build-classic-source
```

But it also didn't work (the snippet was not built).

The documentation for this option does not help: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html#generating-documentation. But I also think that the option itself is not functioning too well since I could not make it work.

**Comment by pomek** [comment]
[Classic editor](https://github.com/ckeditor/ckeditor5/blob/5deccac26d6dd240d025c6d5904b4f11397d8796/docs/examples/builds/classic-editor.md) requires two snippets to work. In both attempts, you specified only first or second snippet both but never both at the same time.

A working solution could look like:

```
yarn docs --skip-api --snippets=classic-editor,build-classic-source
```

Why? The snippet adapter does not know where those snippets are used. If your documentation page requires more than a single snippet, you need to specify all of them manually.
