### ISSUE TITLE
Is there have anyway to add custom attribute to Paragraph

### ISSUE THREAD

**Issue by pheeno** [ckeditor/ckeditor5#7529]
Version: CKeditor5 lastest
description: I try many times to add custom attribute to all Paragraph, it looks like 
`<paragraph name='johnny' age='18'>
       I'm a text, have fun
</paragraph>` 
is there anyway to make this come true? please give me some hints. Thanks !

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. You can start with code like this:
```js
editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on( 'insert:paragraph', ( evt, data, conversionApi ) => {
				
    const viewWriter = conversionApi.writer;
				
    viewWriter.setAttribute( 'name', 'johnny', conversionApi.mapper.toViewElement(data.item ) )
    } );
} );
```
This way, every time you insert a paragraph, it will get the attributes you set. You can do the same for `age`.
In the API docs, you can read more about [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html), [downcast dispatcher](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastDispatcher.html), [writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html).

**Comment by pheeno** [comment]
Thanks a lot it's very helpful!!
