### ISSUE TITLE
Custom builds and advanced setup refer to deprecated repositories

### ISSUE THREAD

**Issue by mat128** [ckeditor/ckeditor5#7533]
The [Custom builds documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) refers to cloning the ckeditor5-build-classic (and variants) repositories.

These repositories have been deprecated and replaced by [subdirectories in the main ckeditor5 repository](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-build-classic).

The [superbuilds section](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds) has the same issue and directly links to the deprecated repository as an example.

Documentation should clearly indicate which repository to clone and repositories mentioned should not be deprecated.

**Comment by mlewand** [comment]
You're absolutely right, actually we have this issue already reported in #6770 - thanks for pinging, we're looking to fix it in this iteration.
