### ISSUE TITLE
Shift+tab in the first table cell does nothing

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7535]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the table sample https://ckeditor.com/docs/ckeditor5/19.0.0/features/table.html
2.  Place the caret in the first cell.
3.  Press <kbd>shift</kbd>+<kbd>tab</kbd>.

### ✔️ Expected result

I'd like to discuss expected behavior, currently I'm keen to think that it should move cursor before the table.

This will be consistent with other widgets, e.g. image:

![](https://user-images.githubusercontent.com/5353898/86373052-40ac6900-bc83-11ea-9230-24bbd15149d6.gif)

### ❌ Actual result

Nothing happens.

## 📃 Other details

Reproducible _at least_ since 16.0.0.

*   Browser: Chrome, Firefox (didn't check others)

---

As a workaround one could use <kbd>up</kbd> / <kbd>left</kbd> arrows to get outside of the table.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Our long-term plans for navigating in/out of nested editables is to use other keys (there's a separate ticket for that). But we can resolve this issue (Shift+Tab) in the meantime as the long-term solution will not be implemented anytime soon.

**Comment by niegowski** [comment]
> I'd like to discuss expected behavior, currently I'm keen to think that it should move cursor before the table.
> 
> This will be consistent with other widgets, e.g. image:

How this works with image captions is a default browser behavior - <kbd>Tab</kbd> navigates to next editable (and this is different in Chrome and in Firefox). I would adjust it with arrow keys handling so <kbd>Shift</kbd>+<kbd>Tab</kbd> in the first table cell would select the whole table widget.
