### ISSUE TITLE
Iframe being stripped (BalloonEditor fork)

### ISSUE THREAD

**Issue by bhayward93** [ckeditor/ckeditor5#7537]
## 📝 Provide detailed reproduction steps (if any)

1. …Insert  youtube link via media embed
2. …Save the editor - this saves to our database - the iframe is present in the saved content.
3. …Load the content - iframe is present in the XHR body, but iframe is stripped out by ckeditor.

### ✔️ Expected result

Iframe should display

### ❌ Actual result

Iframe is stripped.

## 📃 Other details

* Browser: Firefox and Chrome
* OS: Ubuntu 20.04
* CKEditor version: CKEditor5 20.0.0
* Installed CKEditor plugins:
```
Essentials,
UploadAdapter,
Autoformat,
Bold,
Italic,
// BlockQuote,
CKFinder,
EasyImage,
Heading,
Image,
ImageCaption,
ImageStyle,
ImageToolbar,
ImageUpload,
Indent,
Link,
List,
MediaEmbed,
Paragraph,
PasteFromOffice,
Table,
TableToolbar,
Alignment,
BlockToolbar,
HeadingButtonsUI,
ParagraphButtonUI,
Underline,
Strikethrough,
RemoveFormat,
CodeBlock
UploadAdapterPlugin // custom
ThemeSwitcherPlugin //custom 
```

Code for editor can be found here:
https://gitlab.com/minds/minds-ckeditor-bundle/-/blob/master/src/ckeditor.js

Our Angular wrapper:
https://gitlab.com/minds/front/-/merge_requests/1047/diffs#505396313e0a60320f1d925fd6d427a10e55b48b

I have tried
Adding in config values that I now believe are ckeditor4 only?
 
```
extraAllowedContent: '*(*)',
allowedContent: true,
```

I tried to use the on instance ready hook, but I think that also only exists in CKEditor4
`CKEDITOR.on('instanceReady', function () {`
https://stackoverflow.com/a/52975371/7396007

I tried to expand this as a Plugin to see if I could get hold of an object containing on instanceReady.

When there is an error in the build, it shows the iframe as present.

Any help would be greatly appreciated.

**Comment by Mgsy** [comment]
Hi, thanks for the report. I've just checked your issue and setting the data with HTML produced by Media Embed plugin works properly. Do you process your HTML while saving it in the database? Could you also share a sample media embed which doesn't load properly in your editor?

**Comment by bhayward93** [comment]
Hey @Mgsy, really appreciate the quick response.

You are 100% correct; thank you kindly for testing on your end. I dug around in our sanitizer to see if I'd missed anything when setting the exceptions, and it seems we were stripping the `data-oembed-url` attribute from the parent div. :facepalm:. Posting this here should anyone else run into similar symptoms. It appears this was an issue in CKEditor4, so I led myself down the wrong rabbit-hole.
