### ISSUE TITLE
Get image file data before it been pasted on the document

### ISSUE THREAD

**Issue by brunoinds** [ckeditor/ckeditor5#7539]
## 📝 Provide a description of requested docs changes

_What is the purpose and what should be changed?_
When a picture is pasted on the document, you cannot have access to the file before it. And I couldn't find it out on the documentation.

**Comment by FilipTokarski** [comment]
Hi, [answer for this ticket is here](https://github.com/ckeditor/ckeditor5/issues/7540#issuecomment-654705834). In the future please do not open tickets regarding the same issue twice. I'm closing this as a duplicate.
