### ISSUE TITLE
How to change image file data on CKEditor 5 before it been pasted

### ISSUE THREAD

**Issue by brunoinds** [ckeditor/ckeditor5#7540]
## 📝 Provide a description of requested docs changes

_What is the purpose and what should be changed?_
I wanna compress the pasted image file before it been pasted on the on CKEditor 5 document. The documentation didn't explain how to do that and is very complicated.

I already tried the code below, but it's not working on pasted images from the clipboard.

`editor.editing.view.document.on('clipboardInput', (evt, data)=>{
            const images = Array.from( data.dataTransfer.files);
            
            //MAKE CHANGES ON IMAGE FILE (COMPRESS WITH MY LIBRARY) AND UPLOAD IT AFTER

            // Upload the first image:
            editor.execute( 'imageUpload', { file: images[ 0 ] } );
  })`

**Comment by FilipTokarski** [comment]
Hi, if you want to process the image file, I guess the most suitable way would be to do it on back-end. You can check our docs on [simple upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html) or [custom adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html).  
  
Apart from that, answering your question on how to access pasted image data, you can start with code like this:
```js
editor.conversion.for( 'downcast' ).add( dispatcher => {
	dispatcher.on( 'attribute:src:image', ( evt, data, conversionApi ) => {
		console.log(data );
	}, { priority: 'low' } );
} );
```
