### ISSUE TITLE
Triple-click inside image caption causes error in Firefox

### ISSUE THREAD

**Issue by garyapps** [ckeditor/ckeditor5#7542]
## 📝 Provide detailed reproduction steps (if any)

1. Launch Firefox browser. (Do not use Chrome browser).
2. Go to [CKEditor Images documentation page](https://ckeditor.com/docs/ckeditor5/latest/features/image.html) 
3. Scroll down to the Image Captions section ( [direct link](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-captions) )
4. Look at the image with a caption "_Autumn fields by Aleksander Nowodziński_". 
5. Triple-click inside the caption anywhere on the caption text (click 3 times very fast). Normally doing a triple-click should select all the text. 
6. Instead you will see an error in the console. Also you will now be unable to select that image (meaning you can hover over it and see a yellow outline, but if you click it you will not get a blue outline). In fact you will not be able to select the other image in the editor either (the one without a caption), so it appears that the selection tool stops working after the error happens. 
7. Try again, this time using Chrome browser. No error in Chrome; caption text gets selected correctly.

### ✔️ Expected result

Clicking 3 times in a row should select all the caption text.
If you use Chrome that is what will happen. 
But if you use Firefox you will get an error in the console.

### ❌ Actual result

You get an error in the console:
```
CKEditorError: model-selection-range-intersects: Trying to add a range that intersects with another range in the selection. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…port/error-codes.html#error-model-selection-range-intersects
 {"addedRange":{"start":{"root":"main","path":[1],"stickiness":"toNext"},"end":{"root":"main","path":[2],"stickiness":"toPrevious"}},"intersectingRange":{"start":{"root":"main","path":[1,0,0],"stickiness":"toNone"},"end":{"root":"main","path":[1,0,0],"stickiness":"toNone"}}}
```
Also, after this error happens it is not possible to select the image. It is also not possible to select the image that is after it (the one without a caption). In other words the selection tool stops working.

## 📃 Other details

* Browser: Firefox
* OS: Win 10
* CKEditor version: 20
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for this report. I confirm this bug. It happens generally in image captions, event in empty ones. Only in Firefox. It's a regression introduced in the lates iteration, in v19 it works ok.

**Comment by Reinmar** [comment]
@FilipTokarski, could you bisect this issue?

**Comment by FilipTokarski** [comment]
https://github.com/ckeditor/ckeditor5/commit/824d7317de8461773fab4f55cdfd6c585498131d

**Comment by Reinmar** [comment]
Thanks. But the result didn't make it any simpler unfortunately :D In fact, it's a big WTH.

**Comment by garyapps** [comment]
I wonder if this is somehow connected to the other bug report I filed - [Video element breaks widget functionality in Firefox #7525](https://github.com/ckeditor/ckeditor5/issues/7525)

At first glance they seem like very different issues - this one is related to triple clicking in a caption, whereas that one is related to clicking a video - but both bugs happen only in Firefox, they are both related to figure elements, and also both bugs result in the selection tool breaking after which all other widgets becoming un-selectable.
