### ISSUE TITLE
[API docs] Clean up Iterable/Iterator usage

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#755]
I've just found this in the model Node's docs:

```js
	/**
	 * Returns iterator that iterates over this node's attributes.
	 *
	 * Attributes are returned as arrays containing two items. First one is attribute key and second is attribute value.
	 * This format is accepted by native `Map` object and also can be passed in `Node` constructor.
	 *
	 * @returns {Iterable.<*>}
	 */
	getAttributes() {
		return this._attrs.entries();
	}

	/**
	 * Returns iterator that iterates over this node's attribute keys.
	 *
	 * @returns {Iterator.<String>}
	 */
	getAttributeKeys() {
		return this._attrs.keys();
	}
```

`Iterator` or `Iterable`?

`Map#entiries()`, `Map#keys()` return an iterator because:

> The iterator protocol defines a standard way to produce a sequence of values (either finite or infinite).
>
> An object is an iterator when it implements a next() method with the following semantics:

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterator_protocol

Then, we have iterables – objects which have `Symbol.iterator` properties. So, I think that this is the right way to document them:

```js
/** 
 * @implements Iterable
 */
class MyClass {
	// No docs
	[ Symbol.iterator ]() {
		return this._items[ Symbol.iterator ]();
	}
}
```

The only problem here will that we can't document what you'll get when iterating over `MyClass`'s instance, so perhaps this is better:

```js
/** 
 * @implements Iterable
 */
class MyClass {
	/**
	 * Some desc.
	 *
	 * @returns {Iterator.<STH>}
	 */
	[ Symbol.iterator ]() {
		return this._items[ Symbol.iterator ]();
	}
}
```

**Comment by Reinmar** [comment]
cc @pjasiun

**Comment by Reinmar** [comment]
One more `Iterator` type:

```js
	/**
	 * Returns the names of items.
	 *
	 * @returns {Iterator.<String>}
	 */
	* getNames() {
		yield* this._items.map( item => item.name );
	}
```

**Comment by pjasiun** [comment]
You are right. All of these methods should return `Iterator`.

Classes with `Symbol.iterator` method could have also `@implements Iterable` and this method should be documented. It would be perfect if clicking on `Iterable` on the list of interfaces in Umberto link to the `Symbol.iterator` method.

**Comment by Reinmar** [comment]
OK, I'll go with `@returns Iterator.<...>` and documentation for `Symbol.iterator` properties. I'll also test whether we can use `@implements Iterable` but if that won't help, I'll only create a low-prior ticket for Umberto since this a "nice to have" thing, nothing critical.

**Comment by ma2ciek** [comment]
> Iterator or Iterable?
> Map#entiries(), Map#keys() return an iterator because:
> 
> The iterator protocol defines a standard way to produce a sequence of values (either finite or infinite).
> 
> An object is an iterator when it implements a next() method with the following semantics:
> 
> Source: developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterator_protocol

Some iterators are in turn iterables:
```js
var someArray = [1, 5, 7];
var someArrayEntries = someArray.entries();

someArrayEntries.toString();           // "[object Array Iterator]"
someArrayEntries === someArrayEntries[Symbol.iterator]();    // true
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterator_protocol

In fact, that's important that the object is iterable, beacuse use can use on it `Array.from( iterable )`, `...iterable` and so on.

```ts
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
    return?(value?: any): IteratorResult<T>;
    throw?(e?: any): IteratorResult<T>;
}

interface Iterable<T> {
    [Symbol.iterator](): Iterator<T>;
}

interface IterableIterator<T> extends Iterator<T> {
    [Symbol.iterator](): IterableIterator<T>;
}
```
In TS there's Iterator, Iterable and a subtype IterableIterator: https://github.com/Microsoft/TypeScript/blob/964565e06968259fc4e6de6f1e88ab5e0663a94a/lib/lib.es2015.iterable.d.ts#L36

**Comment by Reinmar** [comment]
Ha, actually, we're wrong here. To be precise, generator functions return `Generator` type. `Generator` type implements both `Iterable` and `Iterator` protocols. This came to my mind when looking at a code like this:

```js
/**
 * @param {Iterable} attrs
 */
function doSth( attrs ) {
    for ( const a of attrs ) ...
}
```

The for-of loops require `Iterables`s (the `Symbol.iterator` property), but we've just agreed that `* getAttributes()` returns an... `Iterator` (so `next()/done` props).

So, to sum this up:

* If your function accepts a param on which you then iterate over using `for-of`, then document that your function requires an `Iterable` type (because it's all about `Symbol.iterator`).
* If your function accepts a param on which you do `Array.from( param )`, then document that your function requires an `Iterable` type (because it's all about `Symbol.iterator`).
* If your function is a generator function document that it returns a `Generator`.
* If your function returns an object with only the `next()/done` props (e.g. manually created), then document that it returns an `Iterator`.
* If your function returns an object which has only the `Symbol.iterator` property, then document that it returns an `Iterable`.

**Comment by Reinmar** [comment]
Wow, that's not all still. E.g. this:

```
	[ Symbol.iterator ]() {
		return this._someMap[ Symbol.iterator ]();
	}
```

Returns an iterator? Nope, it returns a generator:

```
> x = new Map()
Map {}
> x[ Symbol.iterator ]()[ Symbol.iterator ]
[Function: [Symbol.iterator]]
> x[ Symbol.iterator ]().next
[Function: next]
```

**Comment by Reinmar** [comment]
Info from @ma2ciek:

> OK, @maciek_bukowski explained it to me that IteratorPrototype defines its Symbol.iterator property. Which means that all native iterators are also iterables. TS's IterableIterator makes more sense now.

And a confirmation:

> %MapIteratorPrototype% inherits from %IteratorPrototype% which implements [@@iterator] (and that just returns `this`) -> http://www.ecma-international.org/ecma-262/#sec-%iteratorprototype%-@@iterator …
>
> It's necessary for iterators to also be iterable with `for of` (or be consumable by any other iterator takers)

So, we need to define the `IterableIterator` type to document native return values... I'll see where it leads me.

**Comment by Reinmar** [comment]
When fixing this I realised that there are no methods which require `Iterator`. All of them require `Iterable` so that's the piece of information (and the actual interface) which matters.

At the same time, it's hard to document whether some of our methods return `IterableIterator` or something else because you need to scan the code of methods quite thoroughly and most of the time go deeper into nested methods. 

Since all this is so complicated even for us, I don't think that there's any value in using `IterableIterator`, `Iterator` and `Generator` precisely. Let's use the most frequent and most generic interface that there is – `Iterable`. Only in special cases where a value is not an `Iterable`  use the `Iterator` interface.

---

## FINAL RULE

1. Use `Iterable` everywhere.
2. Unless you're *sure* that a value *doesn't have* the `Symbol.iterator` property *because* it's a handcrafted iterator.

**Comment by Reinmar** [comment]
OK, you can see all API changes in the links above. 

I also reported a feature request for Umberto to support `@implements Iterable`: https://github.com/cksource/umberto/issues/448.
