### ISSUE TITLE
Edit or change plugin features from angular component for custom build

### ISSUE THREAD

**Issue by logesh1311** [ckeditor/ckeditor5#7551]
## Provide a description of the task
Is there a way to change a plugin configurations for a custom build for a cutsom plugin  in angular component.
eg: Changing icon of a plugin 

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …5
* Installed CKEditor plugins: …

**Comment by Mgsy** [comment]
Hi, you can pass the configuration while creating the editor, see more information [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html). As it comes to Angular integration, use [`config` property](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#config).

You can also modify plugins icons using webpack configuration, see the guide [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-customize-the-ckeditor-5-icons).
