### ISSUE TITLE
Repeated Characters occured at head of a line.

### ISSUE THREAD

**Issue by ziji-wu** [ckeditor/ckeditor5#7553]
* Browser : Chrome(Version 83.0.4103.116/64 bit)
* OS : Windows Version 1909
* Input Method : (Default)  Microsoft Input Method

* Description : Everytime I input at the head of a new line , Repeated Characters always occures, what I need is only a character I input but not the same two.
* Addition : I have recorded the scene when the bug occured, you can get the vedio [here](https://github.com/MarkWu45/LearnerHub-Bug-Report) .
It is clear what happened unexceptedly by the Vedio, hoping to solve the question as soon as possible, thanks a lot.

**Comment by Mgsy** [comment]
Hi, thanks for the report. We're aware of problems related to IME, unfortunately, solving those issues is not trivial and requires a lot of effort. [We're discussing](https://github.com/ckeditor/ckeditor5/issues/7462) migration to `beforeInput`, so we hope it will solve our IME problems. 

However, I'm not able to reproduce the issue you've mentioned. Could you please tell us which language you use and step-by-step instruction?

**Comment by MarkWu45** [comment]
I tried in English and Chinese, both have the question, unfortunately, It is not always occure though I do the same thing. What's more, I found that typing 'a' & 'z' using Chinese is more likely to trigger this bug. You can watch the vedio [here](https://github.com/MarkWu45/LearnerHub-Bug-Report)

**Comment by gd2016** [comment]
Under windows system, use Chinese input method to input numbers or characters like "!@" at the beginning of each line will be repeated. The English input method is normal.

**Comment by a111223** [comment]
I also encountered this problem, Google browser win10 system, using Microsoft input method, adjust to Chinese mode, and will appear when a new line of characters are input

**Comment by gd2016** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
