### ISSUE TITLE
I am using classic ckeditor.js version 5 in my project in angular.js version 1.3.20 and i am unable to add a custom button in the editor toolbar?

### ISSUE THREAD

**Issue by MrManojSingh** [ckeditor/ckeditor5#7554]
Hey Guys,
I am using classic ckeditor.js version 5 in my project in angular.js version 1.3.20 and i am unable to add a custom button in the editor toolbar.
I need to add a custom button in the toolbar and on its click i need to open my custom bootstrap modal and bind some url in iframe to the editor.
Please suggest some way to do it in this version and build of the editor.

**Comment by Mgsy** [comment]
Hi, please see our [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html), where you'll find a step-by-step instruction on how to create plugins in CKEditor 5 and create new buttons with a specific action.

**Comment by ManojEzimax** [comment]
> Hi, please see our [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html), where you'll find a step-by-step instruction on how to create plugins in CKEditor 5 and create new buttons with a specific action.


@Mgsy  - i see the link you shared but how will i import these packages in my project as i mentioned that i am only using ckeditor.js file in my project 

@ckeditor/ckeditor5-image \
    @ckeditor/ckeditor5-core \
    @ckeditor/ckeditor5-ui \
@ckeditor/ckeditor5-core/src/plugin \
@ckeditor/ckeditor5-ui/src/button/buttonview

**Comment by stefandobre** [comment]
@ManojEzimax have you found a solution in the meantime?
