### ISSUE TITLE
How to get full url return in extraPlugins implemention

### ISSUE THREAD

**Issue by ManojEzimax** [ckeditor/ckeditor5#7557]
How to get the exact entered url back in this return html 

mediaEmbed: {
                    extraProviders: [
                        {
                            name: 'thinglink',
                            // A URL regexp or an array of URL regexps:
                            url: /^thinglink\.com\/card\/(\w+)/,
                            // To be defined only if the media are previewable:                        
                            html: match =>{
                               return (
                                    '<div style="position: relative; padding-bottom: 100%; height: 0; ">' +
                                        `<iframe src="${ **url** }" ` +
                                            'style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" ' +
                                            'frameborder="0" width="480" height="270" allowfullscreen allow="autoplay">' +
                                        '</iframe>' +
                                    '</div>'
                                );
                            }
                        },
]}

**Comment by Mgsy** [comment]
Hi, I'm not sure what is your exact problem, however, `match` might contain ID which could be used for creating a proper URL in your iframe. Please, see the example of our default providers config - https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-media-embed/src/mediaembedediting.js#L38.

**Comment by ManojEzimax** [comment]
Hi @Mgsy,
Thanks for answering well my problem is that i want the exact user entered url back in the html after url match not just the id so that i can pass it in the iframe src. 
Is this possible or i will just get the id from the url match instead of the whole path.

**Comment by Mgsy** [comment]
`match` in your provider configuration returns the full address and the id as an array. Let's see the example of Dailymotion configuration:

```javascript
{
	name: 'dailymotion',
	url: /^dailymotion\.com\/video\/(\w+)/,
	html: match => {
		const id = match[ 1 ]; // returns the id.
		const url = match[ 0 ]; // return the full url.

		return (
			'<div style="position: relative; padding-bottom: 100%; height: 0; ">' +
				`<iframe src="https://www.dailymotion.com/embed/video/${ id }" ` +
					'style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" ' +
					'frameborder="0" width="480" height="270" allowfullscreen allow="autoplay">' +
				'</iframe>' +
			'</div>'
		);
	}
}
```

As you can see, `match[ 0 ]` will return the full URL and `match[ 1 ]` only the id.

**Comment by ManojEzimax** [comment]
okay @Mgsy thanks for the hint, so basically the regex we are passing in URL plays an important role here as it will return exactly whats matched. 
FYI i used this regex builder - https://www.regextester.com/97812
