### ISSUE TITLE
cant append text using view writer 

### ISSUE THREAD

**Issue by KapSSe** [ckeditor/ckeditor5#7558]
Hello! I want to change contents of a tag for editor outputed data.As I understood, i have an issue with understanding how @ckeditor/ckeditor5-engine/src/view/writer works.

```
    this.editor.conversion.for( 'dataDowncast' ).elementToElement(
    	( {
    		model: 'mergetag',
    		view: ( modelElement, viewWriter ) => {
    		   return viewWriter.insert( viewWriter.createText( 'foo' ), this.editor.model.document.selection.getFirstPosition() );
    			}
    		} )
    	);
```

But it throws an error *view-writer-insert-invalid-node*. 

```
    this.editor.conversion.for( 'dataDowncast' ).elementToElement(
    	( {
    		model: 'mergetag',
    		view: ( modelElement, viewWriter ) => {
    		   return viewWriter.createContainerElement('foo')
    			}
    		} )
    	);
```
And this one works fine but i need to change a container contents not a container name.

**Comment by KapSSe** [comment]
Oh i solved this myself i used

**Comment by gumatias** [comment]
@KapSSe almost what I needed, do you know of a way to properly insert plain text back in the dataDowncast conversion? from your example, it'd be without the span around it and just text next to the rest of the document text.
