### ISSUE TITLE
How we can we resize media embeds videos just like images in the editor?

### ISSUE THREAD

**Issue by ManojEzimax** [ckeditor/ckeditor5#7563]
Is their a way to resize media embeds just like images? If yes please let me know how it will be implemented in the embedded providers.

**Comment by Mgsy** [comment]
Hi, currently resizing media embeds is not supported. We have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/6593) for it, so feel free to add :+1: to the first post to bump its popularity.
