### ISSUE TITLE
Export to Word and PDF commands should be enabled in read-only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#7567]
## 📝 Provide a description of the improvement

I believe Export to Word and Export to PDF commands should be enabled in read-only mode, as those don't affect the data. I can imagine cases when a user would like to only display content and allow exporting it. Currently, it's impossible, as commands are blocked.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by wwalc** [comment]
+1
