### ISSUE TITLE
How to prevent "change:isFocused" event when development new inline widget

### ISSUE THREAD

**Issue by bahung1221** [ckeditor/ckeditor5#7570]
Hi there,

I'm so sorry for my stupid question, but currently, I trying to create an `extend image resize` plugin which placed on image toolbar (see image below).

But I facing a problem that is I can't inspect styles of the plugin inside toolbar because each time I switch focus to devtool (f12) the toolbar was disappeared. I know this behavior was described in CKEditor 5 document [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/focus-tracking.html#focus-in-the-editor-engine), but I can't find out how to prevent `change:isFocused` event, I tried below code but it doesn't working at all 😢 :

```
export default class ExtendedImageResizeCommand extends Command {
  constructor(editor) {
    super(editor)

    editor.editing.view.document.on('change:isFocused', (evt, data, isFocused) => {
      if (!isFocused) {
        
        // Not working
        evt.stop()

        // Re-focus, not working too
        editor.editing.view.focus()
      }
      console.log(`View document is focused: ${isFocused}.`)
    })
  }
  ...
}
```

So please give me some advice about how to achieve it, I really appreciate any help.
Thank you so much for your great editor ever! 😄 

Image:
![image](https://i.imgur.com/lbkvYn3.png)

**Comment by Reinmar** [comment]
This is always causing problems to me too :D @oleq do you have some trick to prevent that?

**Comment by oleq** [comment]
```javascript
setTimeout( () => {
    debugger;
}, 5000 );
```

is your friend, I use it all the time. Make a snippet out of it in Chrome dev tools (Sources > Snippets).
