### ISSUE TITLE
Insert Media issue with CKEditor5 decoupled version

### ISSUE THREAD

**Issue by julie0842** [ckeditor/ckeditor5#7573]
## 📝 Provide detailed reproduction steps (if any)

We're using a decoupled toolbar with CKEditor5 and seeing a problem where the insert media button in the toolbar isn't opening the input dropdown as expected to be able to enter the URL. 

1. Open CKEditor5 version 19.0.1 using ckeditor5-editor-decoupled
2. Select the Insert Media button in the toolbar

### ✔️ Expected result

The input drop down should appear as it does in the CKEditor5 demo documentation

![image](https://user-images.githubusercontent.com/57689261/86811071-c12fe880-c03a-11ea-9ba4-d55c85924b82.png)

### ❌ Actual result

Nothing appears when clicking the Insert Media button. 

## 📃 Other details

* Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* OS: macOS Mojave Version 10.14.6
* CKEditor version: "@ckeditor/ckeditor5-editor-decoupled": "19.0.1"
* Installed CKEditor plugins:
"@ckeditor/ckeditor5-alignment": "^19.0.1"
    "@ckeditor/ckeditor5-autoformat": "19.0.1"
    "@ckeditor/ckeditor5-autosave": "^19.0.1"
    "@ckeditor/ckeditor5-basic-styles": "^19.0.1"
    "@ckeditor/ckeditor5-block-quote": "^19.0.1"
    "@ckeditor/ckeditor5-clipboard": "^19.0.1"
    "@ckeditor/ckeditor5-code-block": "^19.0.1"
    "@ckeditor/ckeditor5-core": "^19.0.1"
    "@ckeditor/ckeditor5-dev-utils": "^20.0.0"
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^20.0.0"
    "@ckeditor/ckeditor5-editor-decoupled": "19.0.1"
    "@ckeditor/ckeditor5-engine": "^19.0.1"
    "@ckeditor/ckeditor5-essentials": "^19.0.1"
    "@ckeditor/ckeditor5-font": "^19.0.1"
    "@ckeditor/ckeditor5-heading": "^19.0.1"
    "@ckeditor/ckeditor5-highlight": "^19.0.1"
    "@ckeditor/ckeditor5-image": "^19.0.1"
    "@ckeditor/ckeditor5-indent": "^19.0.1"
    "@ckeditor/ckeditor5-inspector": "^2.1.0"
    "@ckeditor/ckeditor5-link": "^19.0.1"
    "@ckeditor/ckeditor5-list": "^19.0.1"
    "@ckeditor/ckeditor5-media-embed": "^19.1.0"
    "@ckeditor/ckeditor5-page-break": "^19.0.1"
    "@ckeditor/ckeditor5-paragraph": "^19.1.0"
    "@ckeditor/ckeditor5-paste-from-office": "19.0.2"
    "@ckeditor/ckeditor5-react": "^2.1.0"
    "@ckeditor/ckeditor5-remove-format": "^19.0.1"
    "@ckeditor/ckeditor5-special-characters": "^19.0.1"
    "@ckeditor/ckeditor5-table": "^19.1.0"
    "@ckeditor/ckeditor5-theme-lark": "^19.1.0"
    "@ckeditor/ckeditor5-typing": "^19.0.1"
    "@ckeditor/ckeditor5-ui": "^19.0.1"
    "@ckeditor/ckeditor5-upload": "^19.0.1"
    "@ckeditor/ckeditor5-utils": "^19.0.2"
    "@ckeditor/ckeditor5-widget": "^19.1.0"

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, can you share more information about your issue? Do you use one of our build or you build the editor from the source? Do you have any errors in the console? 

Also, one case comes to my mind - could you verify if link balloon opens properly?

**Comment by julie0842** [comment]
Hi, thanks for the quick response. We're building the editor from source and I can verify the link balloon does open properly. I'll check for errors in the console and will report back on that.

**Comment by Mgsy** [comment]
> I can verify the link balloon does open properly

So, I believe there's some styling conflict. Do you display the editor in a modal? If so, try to use [this fix](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html#bootstrap-modals) to configure `z-index` of the floating editor UI.

**Comment by Mgsy** [comment]
Hey @julie0842, did you manage to solve your issue?

**Comment by julie0842** [comment]
@Mgsy Apologies for my delay - We were able to figure it out and was on our end. Thank you for the help!

**Comment by Mgsy** [comment]
> [**@Mgsy**](https://github.com/Mgsy) Apologies for my delay - We were able to figure it out and was on our end. Thank you for the help!

That's great to hear :) So, I'm closing this issue.
