### ISSUE TITLE
Allow disabling resize handles when using resize buttons

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7579]
## Provide a description of the task

The `ImageResize` plugin was refactored to common glue plugin that requires:

*   `ImageResizeEditing` - for command **and** image resize handles
*    `ImageResizeUI` - for dropdown and buttons

However, we've identified that not everybody would like to have buttons and resize handles and it would be nice to configure `ImageResizeEditing` feature so that handles are optional (as opt-out to have backward compatibility if possible).

I can see two options:

1.  Split the `ImageResizeEditing` to two - but the question remains how to name the resulting plugins (and how to keep backward compatibility for previous `ImageResize` plugin - or introduce breaking change.
2.  Use configuration option, ie: `config.imageResizeHandles: false` (or similar).

**Comment by Reinmar** [comment]
What about this:

```
ImageResize: requires = [ ImageResizeEditing, ImageResizeHandles, ImageResizeButtons ]
```

Right now, you enable `ImageResize` and that will still work.

If you'll want buttons only – you'll load `ImageResizeEditing` + `ImageResizeButtons`

If you'll want handles only – you'll load `ImageResizeEditing` + `ImageResizeHandles`

Do I miss something?

**Comment by jodator** [comment]
> Do I miss something?

No, this is also a way to go. I like the naming, so probably it is a way to go :)

**Comment by panr** [comment]
@Reinmar your granular approach is OK, but IMHO it'd be nice to have the opt-out option (`config.imageResizeHandles: false`) for handles if someone already uses `ImageResize` plugin. I think it's convenient. Or is it too much?

**Comment by jodator** [comment]
> Or is it too much?

We tend to have [less config options](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html) if possible so configuring (opting-out) by plugins configuration in build would be OK.

**Comment by Reinmar** [comment]
> We tend to have [less config options](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html) if possible so configuring (opting-out) by plugins configuration in build would be OK.

Exactly.
