### ISSUE TITLE
Table downcast in one step

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7580]
## Provide a description of the task

Table conversion is made from multiple atomic converters. This place nice with the current state of view rendering and DOM renderer. We optimize for small changes inside tables, like adding / removing a table cell or table row. However introducing reconversion ( #8099 ) enables handling table changes using single converter. A table can reconvert itself after every change but we limit those changes to only a critical part when a `headingRows` changes require handling table sections (`<tbody>` and `<thead>`).

Linked issues:

*   #8138 - so the reconversion happens on selected (or all) table children events.
*   Espcially (https://github.com/ckeditor/ckeditor5/issues/8138#issuecomment-700702745) - what should table render (maybe creating only table rows structures is enough.

Points to research:

*   How to re-render big model structure in an efficient way.
*   How to re-use existing DOM nodes if re-rendering them is not necessary.
*   How to not stress the DOM too much.
*   DOM nodes re-use strategies. Check if DOM Renderer disallows re-using actively mapped DOM nodes on structural changes.

**Comment by niegowski** [comment]
Will be handled in #10294
