### ISSUE TITLE
How to listen for 'mention added' event?

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#7581]
It is not a bug, but there is no Question Issue. 

The question is: How can I listen for an event 'mention added' or something like that? I need to know when a mention is added. How can I achieve that?

**Comment by FilipTokarski** [comment]
Hi @hpivanov , you can start with code like this:
```js
editor.conversion.for( 'downcast' ).add( dispatcher => {
    dispatcher.on( 'attribute:mention', ( evt, data, conversionApi ) => {
        console.log( 'Mention has been inserted' );
        console.log( data );
    }, { priority: 'low' } );
} );
```
This will be fired every time you insert a mention, or some other content which has `mention` attribute in the model. If you need some more info, please refer to docs on:
- [editing engine architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html)
- [conversion api](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html)
- [downcast dispatcher api](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastDispatcher.html)
  
Hope that helps!

**Comment by hpivanov** [comment]
This works, but it fires even when I get the data from the editor using getData(). I just need to know that I have clicked on an item from the dropdown menu, that's it.

**Comment by Mgsy** [comment]
@hpivanov, in this case, you can simply add a dispatcher for `editingDowncast`, instead of `downcast` (which is for editing and data pipelines).

**Comment by hpivanov** [comment]
@Mgsy Thanky you. That is what I was looking for :)
