### ISSUE TITLE
How can I disable merging attribute elements during conversion?

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#7593]
How can I disable this https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html#merging-attribute-elements-during-conversion.

I have the following code (which is a mention in our app):

```
<strong>@<strong class="k-mention">testuser</strong></strong>
```

CKEditor converts the code above to this (which in our case is unexpected):

```
<strong>@testuser</strong>
```

**Comment by Reinmar** [comment]
Use different priority for each of them. E.g. the link feature uses priority:5 (https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-link/src/utils.js#L38). The priority changes the order in which elements are nested (lower priorities get "inside"). However, it also prevents attribute elements from merging.

The other option is to set the `id` property as it's also used in `isSimilar()` to differentiate attribute elements: https://github.com/ckeditor/ckeditor5/blob/ef4b1f92dbd5a816a6be49f997726df1fd7d6eae/packages/ckeditor5-engine/src/view/attributeelement.js#L196
