### ISSUE TITLE
ContextualBalloon in LinkUI: Is there a way to keep the balloon open?

### ISSUE THREAD

**Issue by Mistralys** [ckeditor/ckeditor5#7594]
## Prevent Link balloon from closing on losing focus

I have created a plugin that adds an additional button to the Link balloon. In my application, users can choose links from an internal registry, and clicking that button displays an application-specific (modal) dialog to choose the target URL. The problem is, as soon as you click anywhere, the link balloon closes. It is then impossible to insert the selected URL into the Link text input field, since it has already been closed.

As far as I can see, the code responsible is this: 
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-link/src/linkui.js#L288

I see no way to influence that in any way.

## Trying to find a solution

My first idea was to keep the ballon from closing, but maybe that's the wrong approach.

Does anyone have any alternative ideas/pointers on how I could implement such a dialog in my application, while keeping the stable featureset of the official Link plugin?

## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 20.0.0
* Installed CKEditor plugins: Essentials, Paragraph, Bold, Link

**Comment by Mistralys** [comment]
I spent some time thinking, and changed my approach. Here's what I did:

- Added a dropdown menu in the link balloon to select an existing link, without needing the separate dialog.
- Added an "Add link" button in the toolbar, which opens the full dialog.

This way, there is no need to change the behavior of the link plugin. For the users, this is also pretty straightforward.

**Comment by antoniolucasnobar** [comment]
@Mistralys , would you mind to share the code to show a dialog? I am facing the same problem as you did, but I do not know how to show up a dialog in ckeditor5. 

thanks in advance.

**Comment by Mistralys** [comment]
> @Mistralys , would you mind to share the code to show a dialog? I am facing the same problem as you did, but I do not know how to show up a dialog in ckeditor5.
> 
> thanks in advance.

Hi Antonio,

I am actually using a dialog from my own application, not a CKEditor-specific dialog. I added a command to the toolbar, which simply does this:

```javascript
import Command from '@ckeditor/ckeditor5-core/src/command';

/**
 * Handles executing the command when the toolbar button
 * is clicked.
 */
export default class AddMailLinkCommand extends Command 
{
    refresh() 
    {
        // Disable the command if the editor is in read-only mode.
        this.isEnabled = !this.editor.isReadOnly;
    }

    execute() 
    {
            Mails_Mail.DialogAddLink();
    }
};
```

The other part was modifying the existing link popout to replace the link input field with a select element.

Sorry I can't be of more help!

**Comment by antoniolucasnobar** [comment]
Thank you very much for your attention @Mistralys
