### ISSUE TITLE
Is their another way to validate bad html data on setData() ?

### ISSUE THREAD

**Issue by ManojEzimax** [ckeditor/ckeditor5#7600]
Hi,
There is catch event of course to catch invalid html while setting data inside the editor but is there another way so that we can validate this bad data and still display data inside the editor like this case of missing p tag.

Error thrown:  Parse error - This page contains the following errors:error on line 1 at column 209: Opening and ending tag mismatch: p line 0 and div

My Invalid missing p tag html : 
![image](https://user-images.githubusercontent.com/36915403/87089882-b6e93680-c254-11ea-8264-a6c153dc452c.png)

**Comment by Mgsy** [comment]
Hi, could you please provide more details about your issue? I've used `editor.setData()` with your HTML and it didn't crash. 

P.S. Please, paste the code directly to your message, because it's difficult to copy the code from the image.
