### ISSUE TITLE
Issue When tried to add plugin with online custom build ckeditor5

### ISSUE THREAD

**Issue by surat-bit** [ckeditor/ckeditor5#7605]
I have downloaded ckeditor 5 from online custom build and tried to add a plugin as per document given ckeditor website..
npm install  successfully done but yarn run build causes issue....any advice...
Thanks in advance.

**Comment by Mgsy** [comment]
Hi, could you provide more information about your issue (e.g. error messages) and describe steps to reproduce?

**Comment by surat-bit** [comment]
Thanks for reverting back...I have upgraded to latest nodejs stable version(12.18) and taken the build then the issue has been solved
