### ISSUE TITLE
How to reset the editor's content after some invalid html error

### ISSUE THREAD

**Issue by ManojEzimax** [ckeditor/ckeditor5#7606]
I am getting following error for some invalid html i guess, but when i try to setData for the right one's then its not updating the editor's text area and feels like its stuck .

Error: Parse error - This page contains the following errors:error on line 1 at column 26: Opening and ending tag mismatch: a line 0 and xml

**Comment by Mgsy** [comment]
Hi, could you provide exact steps to reproduce the issue?

**Comment by ManojEzimax** [comment]
@Mgsy , please refer to this below issue i have used that invalid html on setData() function then the editor just freezes and i have to hard refresh the page.

https://github.com/ckeditor/ckeditor5/issues/7600

**Comment by Mgsy** [comment]
Thanks, I'll take a look at it. As it comes to resetting the editor, please check our [Watchdog feature](https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html) - it automatically resets the editor if some error occurs.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
