### ISSUE TITLE
Modal undefinde

### ISSUE THREAD

**Issue by xumoqiu** [ckeditor/ckeditor5#7609]
@Mgsy I used ckeditor-angular 
add the tag in html page

`<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>
<ckeditor #ckeditor [editor]="Editor" (ready)="onReady($event)" [config]="ckConfig" ></ckeditor>`

`ckConfig = {
    //extraPlugins:'html5video',
    alignment: {
      options: [ 'left', 'right','center','justify']
    },
    fontSize: {
      options: [ 12, 'default', 14, 16, 18, 20, 22, 24, 26, 28, 36, 44, 48, 72],
  },
 // puligns:[CKFinder],
  ckfinder: {
    //openerMethod: 'popup',
    uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'

  },
   // plugins:[Font],
    toolbar:['bold','italic','fontSize','highlight', 'heading', '|', 'bulletedList', 'numberedList', '|', 'alignment', '|','imageTextAlternative','imageUpload','mediaEmbed','ckfinder', 'insertTable','link', 'blockQuote','undo', 'redo']
  }`

it still has the problem can you help me
![image](https://user-images.githubusercontent.com/24932876/87242022-82939700-c45b-11ea-8c36-1e91ac609a2d.png)

_Originally posted by @xumoqiu in https://github.com/ckeditor/ckeditor5/issues/2645#issuecomment-657190322_

**Comment by Mgsy** [comment]
Hi, thanks for the report. Basically, this error message occurs when a user doesn't attach CKFinder to the application. Could you please verify that `<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>` is attached to your page (you can check it in DOM).

**Comment by xumoqiu** [comment]
- thank you
