### ISSUE TITLE
UX: Unable to use the resizing images feature on mobile phones browser

### ISSUE THREAD

**Issue by ThingsOfBeam** [ckeditor/ckeditor5#7610]
Currently, the resizing images feature is not usable on the mobile browser as if it could not sense the touch event to resize image on mobile browser.

* Browser: Chrome
* OS:  IOS
* CKEditor version: 19.0.1
* Installed CKEditor plugins: ImageResize

**Comment by Mgsy** [comment]
Hi, thanks for the report. Currently, we don't support image resizing on mobile devices, however, we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/5624) for it, so feel free to add 👍 to the first post and join the discussion to bump its popularity.
