### ISSUE TITLE
Show blockToolbar

### ISSUE THREAD

**Issue by xavzelada** [ckeditor/ckeditor5#7611]
## 📝 Provide a description of requested docs changes

I would like to ask you, if I could be a way to show the blockToolbar automatically when the ckeditor gets the focus? I've been trying to find a way to do it, but I couldn't do it yet

so, I will really appreciate your help with this question.

**Comment by Mgsy** [comment]
Hi, I'm not sure if I understand your case properly, because the block toolbar shows up after focusing a block. You can check this behaviour in [our demo](https://ckeditor.com/docs/ckeditor5/latest/features/blocktoolbar.html):

**Comment by xavzelada** [comment]
yes, I would like to show the toolbar item after focusing the editor

![xk](https://user-images.githubusercontent.com/2313940/87285923-d0aea600-c500-11ea-9090-807dac273c5e.png)

**Comment by Mgsy** [comment]
@xavzelada, I'm sorry for the late response. Basically, you can listen to focus change and open the balloon after focusing the editable. Please, see the following code example as a starting point for your use case:

```javascript
const blockToolbar = editor.plugins.get( 'BlockToolbar' );
		
editor.editing.view.document.on( 'change:isFocused', ( evt, value, newValue, oldValue ) => {
	if ( newValue ) {
		setTimeout( () => {
			blockToolbar.panelView.show();
			blockToolbar.panelView.pin( {
				target: blockToolbar.buttonView.element,
				limiter: editor.ui.getEditableElement()
			} );
		}, 200 );
	}
} );
```

Some stuff to read:

*   [Block toolbar API](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_toolbar_block_blocktoolbar-BlockToolbar.html)
*   [`change:isFocused`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html#event-change:isFocused) event
