### ISSUE TITLE
Link plugin with internal links

### ISSUE THREAD

**Issue by marcellofuschi** [ckeditor/ckeditor5#7618]
**Internal link**: link pointing to another spot in the same document instead of an external URL.

I noticed that the official link plugin doesn't properly handle internal links by default. For example, when you click on an existing internal link it tries to open it in a new tab (`target=_blank` behavior).

**Comment by Reinmar** [comment]
Hi! Do you mean anchor links `#some-anchor`? You'd expect that when clicking such a link you get scrolled to this point in the document?

**Comment by marcellofuschi** [comment]
Hi! Yes, that's what I would expect.

**Comment by jswiderski** [comment]
Duplicate of #1944.
