### ISSUE TITLE
Onclick Execution

### ISSUE THREAD

**Issue by nlahiry** [ckeditor/ckeditor5#7619]
Hi there, 
I am currently trying to implement a plugin where i create a drop-down list from provided json, The Json structure is given below 

` CustomActionButtons: {
                items: [
                    { value: "1", label: "Save", action: "saveData", tooltip: 'Tooltip1' },
                    { value: "2", label: "Preview", action: "previewData", tooltip: 'Tooltip2' }
                ],
                masterData: { title: "Actions", tooltip: 'Save/Preview' }
            }
`
What i want to do is execute the action provided in JSON, 
the action will be defined in the html page where i link my cutom build ckeditor, as a function like 

`
function saveData(){
      //do something
}
`
it seems i can't figure out how to do that.
can anyone help? or is it not possible?

Just To be Sure i do not want to use eval

**Comment by FilipTokarski** [comment]
Hi, I created a sample plugin with dropdown options, which can execute a function when you click on a specific option. I hope this is close to what your use case assumes. So, here's the minimal implementation:
```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import Collection from '@ckeditor/ckeditor5-utils/src/collection';
import Model from '@ckeditor/ckeditor5-ui/src/model';
import { createDropdown, addListToDropdown } from '@ckeditor/ckeditor5-ui/src/dropdown/utils';

class dropdownSamplePlugin extends Plugin{
	init(){
		const editor = this.editor;

		editor.ui.componentFactory.add( 'dropdownSamplePlugin', locale => {
			// Create collection of dropdown items
			const items = new Collection();

			items.add( {
				type: 'button',
				model: new Model( {
					withText: true,
					label: 'Save'
				} )
			} );

			items.add( {
				type: 'button',
				model: new Model( {
					withText: true,
					label: 'Preview'
				} )
			} );

			const dropdownView = createDropdown( locale );
			addListToDropdown( dropdownView, items );
	
			dropdownView.buttonView.set( {
				label: 'dropdownSamplePlugin',
				withText: true,
				tooltip: true
			} );

			// Execute command when an item from the dropdown is selected
			this.listenTo( dropdownView, 'execute', evt => {
				if( evt.source.label === 'Save' ) {
					// Do whatever you need here
					console.log( 'Fire "saveData()" function here' );
				}
			} );

			return dropdownView;
		} );
	}
}
```
You can further adjust this code to your specific needs, for example creating dropdown collection items based on your JSON data. If you need some more information, please see the links:
- [creating simple plugin tutorial](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)
- [Collection](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_collection-Collection.html) 
- [UI Model](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_model-Model.html)
- [DropdownView](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_dropdownview-DropdownView.html)
- [createDropdown](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_utils.html#static-function-createDropdown)
- [addListToDropdown](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_utils.html#static-function-addListToDropdown)  
  
Hope that helps!

**Comment by nlahiry** [comment]
@FilipTokarski I did the same plugin , before , my requirement is quite different i guess  i need to provide a sample for it to be understandable 

`
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import Model from '@ckeditor/ckeditor5-ui/src/model';

import { createDropdown, addListToDropdown } from '@ckeditor/ckeditor5-ui/src/dropdown/utils';
import Collection from '@ckeditor/ckeditor5-utils/src/collection';


export default class CustomActionButtons extends Plugin {

    static get pluginName() {
        return 'customActionButtons';
    }

    init() {
        const editor = this.editor;
        const t = editor.t;
        const defaultTitle = t('Dynamic Tags');
        const dropdownTooltip = t('List of tags to use for dynamically filling up data');
        const DROPDOWN_ITEMS = editor.config.get('CustomActionButtons.items');
        const Dropdown_details = editor.config.get('CustomActionButtons.masterData');

        // Register UI component
        editor.ui.componentFactory.add('customActionButtons', locale => {

            const dropdownView = createDropdown(locale);

            dropdownView.set({
                label: 'Custom Actions',
                tooltip: true
            });
            dropdownView.buttonView.set({
                isOn: false,
                withText: true,
                label: Dropdown_details.title,
                tooltip: Dropdown_details.tooltip
            });
            dropdownView.extendTemplate({
                attributes: {
                    class: [
                        'ck-image-dropdown'
                    ]
                }
            });

            this.listenTo(dropdownView, 'execute', evt => {
               eval(evt.source.onClick)
            });

            // The collection of the list items.
            const DropdownCollection = new Collection();

            DROPDOWN_ITEMS.forEach(item => {
                return DropdownCollection.add({
                    type: "button",
                    model: new Model({
                        withText: true,
                        label: item.label,
                        tooltip:item.tooltip,
                        onClick: item.action,
                    })
                });
            });

            // Create a dropdown with a list inside the panel.
            addListToDropdown(dropdownView, DropdownCollection);

            return dropdownView;
        });
    }
}
`
You see i am passing the function though as a parameter, and i do not want to use eval as it is a security risk, as for some reason 
`
window[functionname]() 
`
not working , i want to know is there any way to avoid using eval and still be able to achieve the same functionality ?

my ck editor initialization is as follows:

`
ClassicEditor
        .create(document.querySelector('#editor'), {
            toolbar: ['customActionButtons',
                '|',
                'heading',
                '|',
                'undo',
                'redo',
                '|',
                'selectAll',
                'fontSize',
                'fontFamily',
                'fontColor',
                'fontBackgroundColor',
                'alignment',
                'numberedlist',
                "bulletedList",
                'specialCharacters',
                'todoList',
                '|',
                'removeFormat',
                'bold',
                'italic',
                'underline',
                '|',
                'subscript',
                'superscript',
                'strikethrough',
                'blockQuote',
                'horizontalLine',
                '|',
                'pageBreak',
                "imageUpload",
                'insertTable',
                'customDropDown',
                "link",
                '|',
                'exportPdf',
                'exportWord'
            ],
            DynamicDropdown: {
                items: [
                    { value: "1", label: "Appliant Name", tagValue: "<#appName#>", tooltip: 'Tooltip1' },
                    { value: "2", label: "Application Number", tagValue: "<#appNumber#>", tooltip: 'Tooltip2' }
                ],
                masterData: { title: "Dynamic Tags", tooltip: 'Dynamic Tag Description' }
            },
            CustomActionButtons: {
                items: [
                    { value: "1", label: "Save", action: "saveData()", tooltip: 'Tooltip1', icon: 'https://cdn4.iconfinder.com/data/icons/fevzicons-1/91/noun_170933-512.png' },
                    { value: "2", label: "Preview", action: "saveData()", tooltip: 'Tooltip2' }
                ],
                masterData: { title: "Actions", tooltip: 'Save/Preview' }
            },
            table: {
                contentToolbar: [
                    'tableColumn', 'tableRow', 'mergeTableCells',
                    'tableProperties', 'tableCellProperties'
                ],

                // Set the palettes for tables.
                tableProperties: {
                    borderColors: customColorPalette,
                    backgroundColors: customColorPalette
                },

                // Set the palettes for table cells.
                tableCellProperties: {
                    borderColors: customColorPalette,
                    backgroundColors: customColorPalette
                }
            },
            image: {
                toolbar: ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],
                upload: {
                    types: ['png', 'jpeg']
                },
                styles: [
                    // This option is equal to a situation where no style is applied.
                    'full',

                    // This represents an image aligned to the left.
                    'alignLeft',

                    // This represents an image aligned to the right.
                    'alignRight'
                ]
            },
            exportPdf: {
                stylesheets: [
                    'EDITOR_STYLES',
                ],
                fileName: 'my-file.pdf',
                converterOptions: {
                    format: 'A4',
                    margin_top: '20mm',
                    margin_bottom: '20mm',
                    margin_right: '12mm',
                    margin_left: '12mm',
                    page_orientation: 'portrait'
                }
            },
            fontSize: {
                options: [
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22
                ]
            },
            fontColor: {
                colors: fontcolors,
                columns: 10
            },
            fontBackgroundColor: {
                colors: fontcolors,
                columns: 10
            },

        })
        .then(editor => {
            Editor = editor;
        })
        .catch(error => {
            console.error(error.stack);
        });
`

**Comment by Mgsy** [comment]
> You see i am passing the function though as a parameter, and i do not want to use eval as it is a security risk, as for some reason
> 
> window\[functionname\]() 
> 
> not working , i want to know is there any way to avoid using eval and still be able to achieve the same functionality ?

Are you sure that your function is available in the Window object? If you'd like to keep your plugin's logic, I'd recommend making some changes:

1.   In `item.action`, don't pass the function call, but a function name. So, instead of setting `action` to `saveData()`, use `saveData`.
2.  In the dropdown view `execute` listener, you can execute your function by simply calling `window[ evt.source.onClick ]();`.
3.  Make sure that your functions are available in the Window object:

```javascript
function saveData() {
	console.log( 'Saved.' );
}

function previewData() {
	console.log( 'Preview.' );
}

window.saveData = saveData;
window.previewData = previewData;
```

After those changes, I was able to successfully execute a function:

![](https://user-images.githubusercontent.com/20988892/89182779-903dc780-d596-11ea-8490-e426927893b3.gif)
