### ISSUE TITLE
Why on npm @ckeditor/ckeditor5-link i am not getting 3 linkImages js file downloaded into node module.

### ISSUE THREAD

**Issue by ManojEzimax** [ckeditor/ckeditor5#7622]
Hi,  on npm @ckeditor/ckeditor5-link i am not getting 3 linkImages js file downloaded into node module.

This is for my custom online editor builder linkImage feature addition for version 19.0.1 for both image and link npm.
If it does  not support these versions then please share the latest version to support link image plugin

**Comment by FilipTokarski** [comment]
Hi, I just checked it and when I install `@ckeditor/ckeditor5-link` from `npm` I have all the needed files. Please check whether you have the newest version of `link` plugin and maybe just try reinstalling all packages.

**Comment by ManojEzimax** [comment]
hi, 
i just did that and still did not got those missing files - linkImage, linkimageediting and linkimageui

![image](https://user-images.githubusercontent.com/36915403/87447752-946e6900-c618-11ea-968c-b33475deefa7.png)

**Comment by Mgsy** [comment]
I can see that your package has been installed at version 19.0.1. The link image feature was released in 20.0.0, so you should install the latest version.
