### ISSUE TITLE
Blue border glitch when undoing image resize

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7633]
## 📝 Provide detailed reproduction steps (if any)

1. Resize some image
2. To see it clearly keep pressing `undo` and `redo`

### ❌ Actual result

The blue border stays as its place for a split second and then jumps to fit the size of the image.  
![16_image_4](https://user-images.githubusercontent.com/34380544/87668098-ccd28c00-c76b-11ea-98e0-bf589fd1ceaa.gif)

## 📃 Other details

* Browser: any
* CKEditor version: since 17

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Seem to be related to #7548.
