### ISSUE TITLE
Markers disappeared after cutting and pasting text

### ISSUE THREAD

**Issue by MarineLohezic** [ckeditor/ckeditor5#7637]
## 📝 Provide detailed reproduction steps (if any)

1. Add a comment to a text
2. Cut this text commented
3. Paste it in the document

### ✔️ Expected result

_ The comment follow the text

### ❌ Actual result

_ The comment disappeared. 

## 📃 Other details

* Browser: Firefox
* OS: Windows 10
* CKEditor version: 20.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Comments is a commercial plugin and this GitHub issue tracker is for the open-source part of CKEditor ecosystem. If you have a license for our products and encounter any problems, please [contact our support](https://support.ckeditor.com/hc/en-us/requests/new) and we'll get back to you as soon as possible.
