### ISSUE TITLE
Form Elements in Ckeditor5

### ISSUE THREAD

**Issue by ArunPandianB** [ckeditor/ckeditor5#7638]
In ckeditor4, there is a form elements plugin for input elements like textarea, inputbox, etc.,
Ref: [https://ckeditor.com/cke4/addon/forms](https://ckeditor.com/cke4/addon/forms)

Is there any way doing this in ckeditor5 or any references/documentations available for this.

Thanks in Advance!

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. There is no out-of-the-box way of doing such things, but you can try creating your own widget for this. Please see the docs on [inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html) and [block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html). Also the docs on [creating simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html) might be of interest to you.

**Comment by djabif** [comment]
Hi @ArunPandianB I am looking for the same thing. Did you find or implement something for this?

**Comment by kevinquillen** [comment]
> There is no out-of-the-box way of doing such things, but you can try creating your own widget for this.

This seems like a huge miss. Plugins often will want to capture user input in some way, having an abstract/central API to doing this is crucial. Neither the inline, block, or simpleBox demo get close to explaining how to have UI interactions or inputs like whats on the full demo page here: https://ckeditor.com/ckeditor-5/demo/feature-rich/

In order for CKEditor 5 to have a thriving plugin ecosystem like 4.x did this is going to be required. The barrier of entry right now to doing something like a select list or radio/checkbox inputs are very, very high.

**Comment by abdussalam02** [comment]
I am running a marketing agency and post a load of blogs and having form in editor gives us an edge. So, I request you to add this plugin or feature in ckeditor.
