### ISSUE TITLE
Add the TAB keydown in the editor

### ISSUE THREAD

**Issue by guimaraesSalgado** [ckeditor/ckeditor5#7639]
## Provide a description of the task

I set up a function so that the user can indent the text inside the editor, without the need to click on the "Indent" in the toolbar, but I saw that the feature did not work, just took the method, follow my code

## 📃 Other details
onTab(event) {
    console.log(event);
    if (event.key === 'Tab') {
      event.preventDefault();
    }
  }

Is there a way to make this work within my editor?

**Comment by mlewand** [comment]
Just [register your keystroke](https://ckeditor.com/docs/ckeditor5/20.0.0/api/module_core_editingkeystrokehandler-EditingKeystrokeHandler.html#function-set) in the editor, like so:

```javascript
editor.keystrokes.set( 'tab', ( data, stop ) => {
	editor.execute( 'indent' )
	stop();
} );
```

**Comment by mlewand** [comment]
Actually this is a duplicate of #7541
