### ISSUE TITLE
[Chrome] Vertical scrollbar appears after focusing the content in editor which has been resized

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#764]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Open the console.
3. Drag it up to cover part of the image.
4. Drag it down slowly until horizontal scrollbar appears.
5. Click on the image twice.

## ✅ Expected result

Nothing happens.

## ❎ Actual result

Vertical scrollbar appears, content "jumps".

## 📃 Other details that might be useful

**Notes**

This is very strange bug and I was able to reproduce it only with following setup:
- Windows 10
- Large screen
- Chrome
- Unmodified `article test` content

You don't have to use console in this issue, you can just change height of the browser window (for me it's 699px).

I didn't manage to reproduce it on OS X or in other browsers.

It's not reproducible in https://ckeditor5.github.io/, editor's size could matter in this case.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/34677298-f77b4552-f48f-11e7-982d-56803f2c8052.gif)

**Other information**

OS: Windows 10
Browser: Chrome

**Comment by Mgsy** [comment]
It can lead to some strange selection issues, i.e like this one, where image under the `OL List item 2` has been selected:

![bug_cke5](https://user-images.githubusercontent.com/20988892/34677864-bce5fe3a-f491-11e7-9aea-eca5930fdc2f.gif)

**Comment by oleq** [comment]
I confirm that. I decided to give the issue a couple of minutes because I thought it's gonna be something related to `.ck-body` container or similar. But to my surprise, the issue occurs during a very simple selection change between a list and a blockquote, which does not involve any floating UI. Still, no idea why.
![kapture 2018-01-19 at 10 56 28](https://user-images.githubusercontent.com/1099479/35145282-8b164f08-fd07-11e7-8309-ba835b15bc25.gif)

**Comment by Reinmar** [comment]
Can this be related? https://bugs.chromium.org/p/chromium/issues/detail?id=803045 We don't have an iframe but it seems very similar.

**Comment by oleq** [comment]
Looks almost the same. I think it could be the culprit. We can track the progress in chromium and get back to it if there's a patch for the original issue.

**Comment by Reinmar** [comment]
Please comment on Chromium's issue tracker that it's not just about iframes.

**Comment by mlewand** [comment]
@Mgsy I just gave it a try and no luck, might be due to a different resolution. Can you give another try on the latest master to ensure that it still occurs?

**Comment by Mgsy** [comment]
It looks like it's fixed 🎉
