### ISSUE TITLE
Add intext text formating capability via command shortcuts

### ISSUE THREAD

**Issue by usqr** [ckeditor/ckeditor5#7643]
## 📝 Add intext formating options

Ability to edit formating of text from the input field via command shortcuts - something similar to notion:

![](https://user-images.githubusercontent.com/21010044/87785850-3a002300-c839-11ea-9474-a0ff2d8cf4b1.png)

![](https://user-images.githubusercontent.com/21010044/87798214-01b61000-c84c-11ea-8eea-56b4fc8891f1.gif)

Example in action: https://imgur.com/a/tigQbxi

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
This one is already reported :) - #5714.
