### ISSUE TITLE
procedure for 'super builds' in monorepo structure

### ISSUE THREAD

**Issue by meecect** [ckeditor/ckeditor5#7645]
I know lots of docs are being re-written right now after the monorepo move, especially related to custom builds, but is it possible to get just a very brief instruction on how to approach this if the primary goal is to produce what you used to call a 'super-build'?  

I used to use a forked repo of the classic build and added the code for the balloon editor to it so that I could use both, as well as adding a few plugins that I wanted available in both editors.

I'm using ckeditor with meteor, which has support for importing npm packages and has its own build process. 

Do I use npm to install the base ckeditor package and then write my own ckeditor.js, based on the builds I want and then just include that in my project?

thanks,
Cliff

**Comment by Reinmar** [comment]
Hi! The custom build guide is unfortunately undergoing a rewrite. 

I'm working on it in #6770 and the content is mostly ready. Basically, we're getting rid of the recommendation to maintain custom builds in separate repositories (forks of official builds). Instead, we just recommend including a build's source into your project's structure.

You can see the current text in: 

You can see the current text here:

*   Installing plugins: https://raw.githubusercontent.com/ckeditor/ckeditor5/72a64b941da2933d2e90ec3b1fab04d06500d3c7/docs/builds/guides/integration/installing-plugins.md ([preview](https://github.com/ckeditor/ckeditor5/blob/72a64b941da2933d2e90ec3b1fab04d06500d3c7/docs/builds/guides/integration/installing-plugins.md))
*   Advanced setup: https://raw.githubusercontent.com/ckeditor/ckeditor5/72a64b941da2933d2e90ec3b1fab04d06500d3c7/docs/builds/guides/integration/advanced-setup.md ([preview](https://github.com/ckeditor/ckeditor5/blob/72a64b941da2933d2e90ec3b1fab04d06500d3c7/docs/builds/guides/integration/advanced-setup.md)).

I hope that helps in the meantime.
