### ISSUE TITLE
FOUC when building new inline editors

### ISSUE THREAD

**Issue by thedavidmeister** [ckeditor/ckeditor5#765]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

alpha2

## 📋 Steps to reproduce

1. create a new editor
2.

## ✅ Expected result

editor appears in the correct place with no FOUC

## ❎ Actual result

sometimes editor will flash in the wrong place (top of the screen) before moving into place

## 📃 Other details that might be useful

this only happens on initial creation of the editor and only "sometimes"

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
I managed to reproduce that. It happens upon the first focus of the editable when the (floating) toolbar is supposed to show up.

The reason why it happens is that we must first make the toolbar visible before we can obtain its geometry (bounding rects won't work when `display` is `none`) and use that geometry to position it relative to the editable.

I see two solutions to the problem:
1. Check if bounding rects work when `visibility: hidden`. If so, it's enough to make sure the toolbar is invisible until it is positioned.
2. Move the toolbar off the screen (`top/left: -9999px` etc.) before it's positioned.

**Comment by Reinmar** [comment]
Can we use `opacity:0` for a moment?

**Comment by scofalik** [comment]
As far as I remember, `visibility: hidden;` should work. But moving out of screen also should be fine and for me, it even feels safer.

**Comment by oleq** [comment]
I think the issue is gone with this simple patch:
```diff
diff --git a/src/panel/balloon/balloonpanelview.js b/src/panel/balloon/balloonpanelview.js
index 075780c..4491f9d 100644
--- a/src/panel/balloon/balloonpanelview.js
+++ b/src/panel/balloon/balloonpanelview.js
@@ -74,7 +74,7 @@ export default class BalloonPanelView extends View {
 		 * @default 0
 		 * @member {Number} #top
 		 */
-		this.set( 'top', 0 );
+		this.set( 'top', -9999 );
 
 		/**
 		 * The absolute left position of the balloon panel in pixels.
@@ -83,7 +83,7 @@ export default class BalloonPanelView extends View {
 		 * @default 0
 		 * @member {Number} #left
 		 */
-		this.set( 'left', 0 );
+		this.set( 'left', -9999 );
 
 		/**
 		 * Balloon panel's current position. The position name is reflected in the CSS class set
```

**Comment by mlewand** [comment]
@thedavidmeister I have used [Inline editor demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html) to reproduce the issue, but I don't see the issue there.

It is likely that the issue got fixed down the road. Can you check whether you're able to still reproduce the problem with the latest version of CKEditor?
