### ISSUE TITLE
CI fails because of invalid links

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7653]
## 📝 Provide a description of requested docs changes

On my local machine:

```
Error: Invalid internal links in /ckeditor5/20.0.0/framework/guides/architecture/core-editor-architecture.html:
  * '../../../api/module_core_command-Command.html#event-set:%7Bproperty%7D' -
  * '../../../api/module_core_command-Command.html#event-change:%7Bproperty%7D' -
```

On the latest master (https://github.com/ckeditor/ckeditor5/commit/8f3c81bd98b979ce36521a8eda42ca2d18588752) / https://travis-ci.org/github/ckeditor/ckeditor5/jobs/709989289:

```
Error: Invalid internal links in /ckeditor5/20.0.0/framework/guides/architecture/core-editor-architecture.html:
  * '../../../api/module_core_command-Command.html#event-set:%7Bproperty%7D' - 
  * '../../../api/module_core_command-Command.html#event-change:%7Bproperty%7D' - 
```

**Comment by tomalec** [comment]
I made a small investigation plus a quick. I'm not sure whether it's the way we would like to go, or should we rather, make the content contain also escaped `{}` in `a href`s and `id`s.

**Comment by pomek** [comment]
I found this one - https://secure.n-able.com/webhelp/NC_9-1-0_SO_en/Content/SA_docs/API_Level_Integration/API_Integration_URLEncoding.html.

And from what I can understand, Umberto should escape `{` and `}` (and other characters). It does when generating URLs but it doesn't when saving API docs.

HTML of the page where the error occurs:

```html
 (e.g. <a href="../../../api/module_core_command-Command.html#event-set:%7Bproperty%7D"><code>#set:value</code></a>
```

HTML of the page where the URL indicates:

```
<a class="member-name" href="#event-set:{property}">set:{property}</a>
```

So, instead of fixing a validator, we must fix how the URLs are generated/saved.

**Comment by tomalec** [comment]
> instead of fixing a validator, we must fix how the URLs are generated/saved.

:+1: from me :)

I just didn't know where to and needed something that unlocks my local.
