### ISSUE TITLE
Verify that styles in 2SCM are OK

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7667]
## Provide a description of the task

The #7577 PR introduces a 2SCM highlight class for `code`. 

My worry is that the background color change might be hard to notice. However, I think that we have a similar issue with a link 2SCM highlight.

**Comment by jodator** [comment]
And do not forget about: #7671.

**Comment by Reinmar** [comment]
After the testing phase, we concluded that the bg color is fine. There's the other problem with the caret being displayed always inside the `<code>` (visually), but it deserves its own ticket.
