### ISSUE TITLE
doc: Changing the view template: bad import 

### ISSUE THREAD

**Issue by asimkt** [ckeditor/ckeditor5#7670]
at https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/annotation-customization/annotations-custom-template.html#changing-the-view-template
the import
```
import CommentView from '@ckeditor/ckeditor5-comments/src/ui/view/commentview';
```
should have been
```
import CommentView from '@ckeditor/ckeditor5-comments/src/comments/ui/view/commentview';
```

If I know where to change I will be happy to create a PR

**Comment by asimkt** [comment]
Found one more. I was banging my head around this for a while: 

same document section have:
```
// mycommentview.js

import CommentView from '@ckeditor/ckeditor5-comments/src/ui/view/commentview';

// Create a new comment view class basing on the default view.
class MyCommentView extends CommentView {
    // Overwrite the method to provide a custom template.
    _getTempate() {
        return {
            // Provide the template definition here.
        };
    }
}
```
should have been:
```
// mycommentview.js

import CommentView from '@ckeditor/ckeditor5-comments/src/comments/ui/view/commentview';

// Create a new comment view class basing on the default view.
class MyCommentView extends CommentView {
    // Overwrite the method to provide a custom template.
    _getTemplate() {
        return {
            // Provide the template definition here.
        };
    }
}
```
Two changes happened:
1. change in import
2. fix typo: `_getTempate` to `_getTemplate`.

**Comment by Mgsy** [comment]
cc @scofalik

**Comment by scofalik** [comment]
Hello,

> If I know where to change I will be happy to create a PR

Unfortunately, docs are a closed repo. Thank you for pointing out those errors - we will fix them ASAP.

**Comment by asimkt** [comment]
Saw some doc being open, so asked. Thought I couldn't find the correct file. Happy to help.

**Comment by scofalik** [comment]
I fixed those typos, the changes will be visible soon.
