### ISSUE TITLE
Active <code> element styles do not work in docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7671]
## 📝 Provide detailed reproduction steps (if any)

![](https://user-images.githubusercontent.com/156149/88227953-b39b7500-cc6e-11ea-8fa6-bf6381be6d24.gif)

### ✔️ Expected result

The code element should be highlighted.

### ❌ Actual result

Nothing happens.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
AFAICS the cdoe styles  are overriden by: `.formatted :not(pre) > code:not(.hljs)`. The feature works in the terms of adding proper classes.

**Comment by oleq** [comment]
Closed in #7678 (release branch).
