### ISSUE TITLE
CkEditor5 text takes format of header 1

### ISSUE THREAD

**Issue by sandywilkins** [ckeditor/ckeditor5#7672]
## 📝 Provide detailed reproduction steps (if any)

1. … Write a complete sentence on one line.
2. …Enter an Enter in the middle of the sentence
3. …Select the top sentence and apply header 1 styling
4. ...Submit the form

### ✔️ Expected result
When displaying the saved HTML, the top line should have a header formatting, and the second line should have normal formatting.

### ❌ Actual result
Both lines have header formatting
The actual output is `<h2>this is the title<p>this is the body</p></h2>`

## 📃 Other details

Video here: https://youtu.be/g6CF_R1WBdg

* Browser: Chrome
* OS: Mac
* CKEditor version: 5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. Could you please tell us how do you save and display the data produced by the editor? I've followed your steps and `editor.getData()` returns proper HTML with `h1` and `p` elements.

**Comment by sandywilkins** [comment]
Hi @Mgsy ! Yes you're correct. Part of my backend code extracts base64 images and when looking further into this it appears that that method is altering the HTML that returns. Thanks for your time.
