### ISSUE TITLE
Length limit

### ISSUE THREAD

**Issue by Pr0methean** [ckeditor/ckeditor5#7673]
## Type of report

Feature request

## Provide description of the new feature

I'm concerned that users may enter more text into a ckeditor instance than the associated database column can store. In Angular, it'll be difficult to attach a keypress handler for that purpose without clobbering the one built into ckeditor. It would be handy if I could configure ckeditor with a maximum number of characters to allow, including markup.

**Comment by mlewand** [comment]
There's already the API to do that.

Just add a listener like

```
editor.model.document.on( 'change:data', ( evt, batch ) => {
	const data = editor.getData();
	console.log( data.length );
} );
```

You may want to throttle the listener for improved performance.

On the other hand if you wouldn't want to include markup, there's a [word count](https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html) plugin.
