### ISSUE TITLE
Single-paragraph mode

### ISSUE THREAD

**Issue by Pr0methean** [ckeditor/ckeditor5#7674]
## Type of report

Feature request

## Provide description of the new feature

I have a text field which, because of page-layout considerations, should not be much more than 3em tall. May we please have an option to configure ckeditor so that it ignores the enter key and doesn't produce any block elements in the output, effectively constraining it to be a single paragraph? (I'm using Angular, in case it makes a difference.)

**Comment by Reinmar** [comment]
This is somewhere on our roadmap: #762. I don't know yet where. Although, AFAIR we checked and we were quite close to supporting this. You may find some inspiration in https://github.com/ckeditor/ckeditor5/issues/2253#issuecomment-495128530.

In fact, I'll ask the team to look into that as it may be a rather quick win now.
