### ISSUE TITLE
use https://ckeditor.com/ckeditor-5/online-builder/ Add pastefromoffice, but it doesn't work in the project

### ISSUE THREAD

**Issue by Mingscript** [ckeditor/ckeditor5#7675]
## 📝 Provide detailed reproduction steps (if any)

1.use https://ckeditor.com/ckeditor-5/online-builder/ Self purchase build, also add pastefromoffice

### ✔️ Expected result

I hoped that the content format of word can be completely copied to ckeditor

### ❌ Actual result

As a result, the background color of the font and the middle of the paragraph were not copied

## 📃 Other details
Here are some pictures

![1](https://user-images.githubusercontent.com/21995558/88263617-e5f3b380-ccfc-11ea-8b67-41555b86f4c1.png)
![2](https://user-images.githubusercontent.com/21995558/88263640-f3a93900-ccfc-11ea-86e6-0038e4a3ff31.png)
![3](https://user-images.githubusercontent.com/21995558/88263644-f572fc80-ccfc-11ea-9088-2688aeaca4b5.png)
![4](https://user-images.githubusercontent.com/21995558/88263647-f572fc80-ccfc-11ea-90b3-f2d01146d4ce.png)

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi thanks for the report. I checked it and indeed we have a bug with background color here. This occurs when there are no `tableProperties` or `tableCellProperties` plugins in the editor, and I [reported it in a separate issue](https://github.com/ckeditor/ckeditor5/issues/7684). So the workaround here is, when using Online Builder, to add `tableProperties` or `tableCellProperties` plugins ( or both of them ).
As it comes to the alignment issue, you also need to add `Alignment` plugin, so that editor can use it on pasted content.
Hope that helps!

**Comment by Mgsy** [comment]
Hi @Mingscript, just to let you know - we've fixed the issue with pasting text containing background colour. Packages with the fix will be available after the release, i.e. next week.

**Comment by Mingscript** [comment]
> 您好，感谢您的举报。我检查了一下，确实这里有一个背景色错误。当编辑器中没有`tableProperties`或`tableCellProperties`插件时，就会发生这种情况，而我[在另一期中对此进行了报道](https://github.com/ckeditor/ckeditor5/issues/7684)。因此，这里的解决方法是，使用Online Builder时，添加`tableProperties`或`tableCellProperties`插件（或两者）。
> 对于对齐问题，您还需要添加`Alignment`插件，以便编辑器可以在粘贴的内容上使用它。
> 希望有帮助！



> Hi thanks for the report. I checked it and indeed we have a bug with background color here. This occurs when there are no `tableProperties` or `tableCellProperties` plugins in the editor, and I [reported it in a separate issue](https://github.com/ckeditor/ckeditor5/issues/7684). So the workaround here is, when using Online Builder, to add `tableProperties` or `tableCellProperties` plugins ( or both of them ).
> As it comes to the alignment issue, you also need to add `Alignment` plugin, so that editor can use it on pasted content.
> Hope that helps!

Thank you. Another point is that in addition to the above mentioned alignment, the text size will not be pasted into ckedtior. This also needs to be added separately？

**Comment by Mingscript** [comment]
> Hi @Mingscript, just to let you know - we've fixed the issue with pasting text containing background colour. Packages with the fix will be available after the release, i.e. next week.

thanks,One question is whether all the styles pasted from Word will be retained as long as I add pasteFromOffice, because now the background color, font size and paragraph center will not be retained.

**Comment by Mingscript** [comment]
> Hi thanks for the report. I checked it and indeed we have a bug with background color here. This occurs when there are no `tableProperties` or `tableCellProperties` plugins in the editor, and I [reported it in a separate issue](https://github.com/ckeditor/ckeditor5/issues/7684). So the workaround here is, when using Online Builder, to add `tableProperties` or `tableCellProperties` plugins ( or both of them ).
> As it comes to the alignment issue, you also need to add `Alignment` plugin, so that editor can use it on pasted content.
> Hope that helps!

 add tableProperties or tableCellProperties plugins (  both of them ).
But the font size and font family are not copied correctly. I have added both plugins
<img width="921" alt="WeChat6ce0ee4d5416db7c3d64796ff7bae582" src="https://user-images.githubusercontent.com/21995558/88414345-48d56f80-ce0f-11ea-90d3-bf0a967224a2.png">

**Comment by Mgsy** [comment]
@Mingscript, can you reproduce mentioned issues after upgrading to the latest version (v21)?

As it comes to the font-family issue, it might be required to set `supportAllValues` property, you can learn more about it [here](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#accepting-all-font-names).

**Comment by cg-durgeshsingh** [comment]
![image](https://user-images.githubusercontent.com/46962067/94425880-84f3bc00-0141-11eb-871c-bef25f403965.png)
 
Paste from office is not working in windows
