### ISSUE TITLE
emitter.on is not a function when using advanced google closure compilation

### ISSUE THREAD

**Issue by thedavidmeister** [ckeditor/ckeditor5#768]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

basic custom build as per https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#Scenario-2-Building-from-source

## 📋 Steps to reproduce

1.
2.

## 📃 Other details that might be useful

currently investigating/debugging further...

**Comment by thedavidmeister** [comment]
reading https://github.com/ckeditor/ckeditor5/issues/413

put this debug code in:

```javascript
function isDomNode(obj) {
  console.log(obj.addEventListener, 'idn', !!(obj && (0, _isNative2.default)(obj.addEventListener)));
  return !!(obj && (0, _isNative2.default)(obj.addEventListener));
}
```

and get this output:

`ƒ addEventListener() { [native code] } "idn" false`

for a DOM element - seems NQR as the fn is reported as native code

**Comment by thedavidmeister** [comment]
note that i'm not using google closure compilation on ckeditor code directly, just including it as an extern

**Comment by thedavidmeister** [comment]
without advanced optimisations:

`ƒ addEventListener() { [native code] } "function addEventListener() { [native code] }" "idn" true`

with advanced:

`ƒ addEventListener() { [native code] } "function addEventListener() { [native code] }" "idn" false`

looks the same to me :/

**Comment by thedavidmeister** [comment]
```javascript
function isNative(value) {
  if (!(0, _isObject2.default)(value)) {
    return false;
  }
  var pattern = (0, _isFunction2.default)(value) || (0, _isHostObject2.default)(value) ? reIsNative : reIsHostCtor;
	console.log(pattern, (0, _toSource2.default)(value));
  return pattern.test((0, _toSource2.default)(value));
}
```

with optimisations:

`/^function.*?\(\) \{ \[native code\] \}$/ "function (d,f,g,h){try{f&&f.handleEvent&&(f.handleEvent=c.wrap(f.handleEvent))}catch(i){}var j,k,l;return e&&e.dom&&("EventTarget"===a||"Node"===a)&&(k=c.U("click"),l=c.W(),j=function(a){if(a){var b;try{b=a.type}catch(c){return}return"click"===b?k(a):"keypress"===b?l(a):void 0}}),b.call(this,d,c.wrap(f,void 0,j),g,h)}"`

**Comment by thedavidmeister** [comment]
```javascript
function toSource(func) {
	console.log(funcToString.call(func), func + '', func.toString());
  if (func != null) {
    try {
      return funcToString.call(func);
    } catch (e) {}
    try {
      return func + '';
    } catch (e) {}
  }
  return '';
}
```

with optimisations:

```javascript
function (d,f,g,h){try{f&&f.handleEvent&&(f.handleEvent=c.wrap(f.handleEvent))}catch(i){}var j,k,l;return e&&e.dom&&("EventTarget"===a||"Node"===a)&&(k=c.U("click"),l=c.W(),j=function(a){if(a){var b;try{b=a.type}catch(c){return}return"click"===b?k(a):"keypress"===b?l(a):void 0}}),b.call(this,d,c.wrap(f,void 0,j),g,h)} function addEventListener() { [native code] } function addEventListener() { [native code] }
```

**Comment by thedavidmeister** [comment]
`console.log(funcToString.toString(), func.toString.toString());`

`function toString() { [native code] } function (){return"function"==typeof this&&this.K?a.Y.apply(this.M,arguments):a.Y.apply(this,arguments)}`

**Comment by Reinmar** [comment]
We changed the `isDomNode()` util recently to this: 

https://github.com/ckeditor/ckeditor5-utils/blob/bd1f2ca9fdbbcb20222a4915034f8d16d66f567f/src/dom/isdomnode.js#L16-L26

There were too many issues with the old, lodash-based solution. Could you check if it works with GCC?

**Comment by thedavidmeister** [comment]
@Reinmar oh wow, that looks totally different

i can test it out, do you know what i should put in package.json of my build to get the right version?

**Comment by Reinmar** [comment]
That's not published yet and you won't be able to install just this single package from a Git repo (npm allows that) because other packages will break.

So, you can either setup the [development environment](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/contributing/development-environment.html) or patch that function manually in your `node_modules/`.

**Comment by thedavidmeister** [comment]
@Reinmar hmmm, any idea when it might be published? i've currently disabled sentry and can get away without it for a while longer... i don't feel comfortable maintaining ad-hoc patches unless its really needed

**Comment by Reinmar** [comment]
It will be published in February, together with all the big changes that we're working on now.

**Comment by thedavidmeister** [comment]
OK awesome, i think i can hold out that long :)

**Comment by mkubilayk** [comment]
what is the timeline for the fix? is it already released?

**Comment by Reinmar** [comment]
Did you use v1.0.0-beta.1 which we released 2 weeks ago? It uses the new method to differentiate between DOM nodes and other objects and, hopefully, the issue is gone.

**Comment by Mgsy** [comment]
Closing due to a lack of activity.
