### ISSUE TITLE
Consider enabling AutoLink in all builds

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7682]
## Provide a description of the task

Demo is here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/link.html#autolink-feature

Do we want this feature in all builds? I'm :+1:

**Comment by mlewand** [comment]
Also it will still be possible to use link without the AutoLink feature - in this case one should reimplement the Link plugin but without including AutoLink plugin. So it should pretty much [look like in v22.0.0](https://github.com/ckeditor/ckeditor5/blob/a5a4b933e8ecef2b25ddbf03d371b89f26490025/packages/ckeditor5-link/src/link.js).
