### ISSUE TITLE
The demo of AutoLink does not work (and the guide is unclear)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7683]
## 📝 Provide a description of requested docs changes

Open: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/link.html#autolink-feature

And follow the instructions in the editor. Nothing happens. That's because it's missing "http(s)://".

Besides that, this section misses the information that this plugin is not enabled by default and being mentioned in https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/link.html#common-api and https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/link.html#installation sections too.

**Comment by Reinmar** [comment]
And no, it does not work with emails:

![](https://user-images.githubusercontent.com/156149/88279097-ce5c0100-cce3-11ea-87b8-ad34320e1e01.png)

**Comment by jodator** [comment]
> And follow the instructions in the editor. Nothing happens. That's because it's missing "http(s)://".

Either `http://` or `www.` - but yes this slipped.

**Comment by Reinmar** [comment]
As for the `mailto:` – do we want to remove this example (and support for it) or fix it?

**Comment by jodator** [comment]
> As for the `mailto:` – do we want to remove this example (and support for it) or fix it?

The whole fix was under 5min so let's fix it. #7685

**Comment by oleq** [comment]
TBH this guide is still unclear to me. I pasted several links in the content and nothing happened. It took me a while to realize I need to press space for the feature to work. I almost created an issue for this.

> The [`AutoLink`](http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/api/module_link_autolink-AutoLink.html) feature will automatically add turn URLs or e-mail addresses into real links.

This only tells half of the story. The rest is in the editor content and it's easy to miss that (usually we use some random content).

WDYT?
