### ISSUE TITLE
When using PasteFromOffice, if you remove tableProperties and tableCellProperties, pasted text loses background color

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7684]
## 📝 Provide detailed reproduction steps (if any)

1. Open editor with `PasteFromOffice` plugin.
2. Make sure there are no `tableProperties` **and** `tableCellProperties` plugins imported ( using either one of them will give expected result ).
3. From Word, paste some text with background color.

### ✔️ Expected result

Text is pasted with background color.

### ❌ Actual result

Text loses background color. If you add those plugins ( or one of them ), everything is ok.

## 📃 Other details

This happens since 19.1.1 release, which was addressing some PFO issues and indeed fixed most of them, but we somehow missed this combination.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I can confirm this. BG color is not pasted. FG color works fine.
