### ISSUE TITLE
imageInsert is hidden with custom config

### ISSUE THREAD

**Issue by iksent** [ckeditor/ckeditor5#7691]
## 📝 Provide detailed reproduction steps (if any)

1. @ckeditor/ckeditor5-react
2. ClassicEditor
3. imageInsert works just OK
4. Then provide any custom "toolbar" config, that includes "imageInsert"
5. ...and image select button dissappears.

My config:

```
{
  simpleUpload: {
    uploadUrl: `/api/v1/resources`,
      headers: {
      Authorization: `Bearer ${COOKIES.apiKey.get()}`,
    },
  },
  toolbar: ["...", "imageInsert", "..."] <---- Adding "toolbar" to config, then imageInsert is hidden
}
```

* Browser: Chrome
* CKEditor version: 18.0.0
* Some of CKEditor imports:
```
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
```

**Comment by Mgsy** [comment]
Hi, thanks for the report. There's no `imageInsert` button in CKEditor 5, in order to add the image upload button to the editor, you should use `imageUpload` toolbar item.

**Comment by iksent** [comment]
Oh, it works, thanks! Sorry for the issue of the wrong usage.
