### ISSUE TITLE
CKEditor5 with Meteor

### ISSUE THREAD

**Issue by formspoint** [ckeditor/ckeditor5#770]
I just want to help others that may have issues integrating CKEditor5 with Meteor.

1) Installed using npm: 

```bash
meteor npm install --save @ckeditor/ckeditor5-build-classic
```

2) Used CSS to change height on the editor:

```css
.ck-editor__editable {
    min-height: 350px;
}
```

3) Used the onRendered funtion to create the editor:

Here, assigning the editor to the variable theEditor will not work, it will always be undefined for some reason.  Also, assigning the editor to the Template instance (a ReactiveDict) will not work, again it will be undfined.  THE only thing that worked for me is to assigne the editor to the window object like below.

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';

Template.templateName.onRendered(() => {
	let theEditor;

	ClassicEditor
	  .create( document.querySelector( '#noteContent' ) )
	  .then( editor => {
	     console.log('editor: ', editor); // undefined
	     theEditor = editor; // doesn't work, undefined
             Template.instance().state.set('editor', editor); // undefined
	     window.myEditor = editor; // works
           })
	   .catch( error => {
	      console.error( error.stack );
 	    });
        ...
});
```

4) In order to get the data back from the window object, I did this:

```javascript
Template.templateName.events({
  'click #update-note': (event, instance) => {
    
    ...
    const note = window.myEditor.getData(); // works.
    ...
  },
```

I hope this helps.

UPDATE:

[This post](https://github.com/ckeditor/ckeditor5/issues/770#issuecomment-357821279) by me at the bottom has corrections/modifications after the feedback from the maintainers.

**Comment by Reinmar** [comment]
Hi! Thanks for sharing.

The `theEditor` variable must work within the scope of `onRender()`'s callback. It will not be available outside this callback but inside it will definitely be accessible.

I don't know Meteor and I don't know what you want to achieve, but assigning the editor instance to `window.myEditor` is not safe. E.g. you may want to have two editors on one page and this solution won't work.

In general, it seems to be a good idea to connect the new editor instance with a state of your template, but the following line looks wrong:

```js
Template.instance().state.set('editor', editor);
```

Again, I don't know Meteor, but `instance()` call can't possibly know which template is now being rendered **because editor initialization is asynchronous**. So perhaps that's why it doesn't work.

I'm afraid that you need to dig a bit deeper into Meteor to find the proper way of managing template states.

I'll leave this issue open. Perhaps someone else will stumble upon it and share some ideas.

**Comment by Reinmar** [comment]
PS. There's a separate topic about CKEditor 5 integration with other frameworks (Angular, React, etc.): https://github.com/ckeditor/ckeditor5/issues/599.

**Comment by formspoint** [comment]
Thanks.

If I change the code to this, from another location, I can see that the state is set for TEST, but the 'editor' state is never set (not just undefined, the variable is not added to the hash table).  Even when I move let template = this; inside the .then promise, it never sets the variable in state.  So what's different inside that promise?  Is there a barrier between the promise code and my template code?

```
Template.templateName.onRendered(() => {
	let template = this;
        template.state.set('TEST', 'WORKS'); // undefined

	ClassicEditor
	  .create( document.querySelector( '#noteContent' ) )
	  .then( editor => {
             template.state.set('editor', editor); // undefined
	     window.myEditor = editor; // works
           })
	   .catch( error => {
	      console.error( error.stack );
 	    });
        ...
});
```

**Comment by ma2ciek** [comment]
Hi, @formspoint.

**Comment by formspoint** [comment]
Hi @ma2ciek

**Comment by ma2ciek** [comment]
I closed issue by mistake while typing. Please, read my updated previous comment.

**Comment by formspoint** [comment]
This code now seems to work, including the template session state.  Thanks for the help.

Creating the editor:

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';


Template.templateName.onRendered(function() {
ClassicEditor
  .create( document.querySelector( '#noteContent' ) )
  .then( editor => {
    if (editor) {
      let template = this;
      template.state.set('editor', editor.getData());			
     }
  })
  .catch( error => {
    console.error( error.stack );
   });
});
```

Helper for the template:

```javascript
note () {
  let note = note.findOne({_id: Meteor.userId()}, {note: 1});
  return note;
}
```

Template:

```html
<textarea id="noteContent" name="content">{{note}}</textarea>
```

Event to get the data from the instance:

```javascript
Template.theTemplate.events({
  'click #update-note': (event, instance) => {
    event.preventDefault();

    const note = instance.state.get('editor');

});
```

**Comment by formspoint** [comment]
Okay, I found another problem.

Starting out with a blank Editor when I type in the word 'TEST', when press the update note button and trigger the #update-note event, since I do not have the editor in a session, and only added editor.getData(), I have no way of getting the data out of the editor here:

```javascript
Template.theTemplate.events({
  'click #update-note': (event, instance) => {
    event.preventDefault();
    const note = instance.state.get('editor'); // this instance is set, but it doesn't have new 'TEST'
});
```

the instance.state.get('editor') doesn't actually have the editor, just getData(), which is nothing because we started out as nothing.

How do I get the data out of the editor when I do not have a handle on the editor?  I couldn't put the editor inside the session -- AND -- I cannot get the value out of the text area like this -- it doesn't contain 'TEST' only the editor does:

```javascript
let note = $('textarea#noteContent').text() // this will contain nothing
```

**Comment by ma2ciek** [comment]
Oh, my mistake. I meant `editor.document.on( 'changesDone', cb )`, not `editor.on( 'changesDone', cb ). I'm sorry for the confusion. 

>Above, the only time I have editor is inside the .then promise.

IMO, that's the right place as you have access to the editor.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
