### ISSUE TITLE
Special characters dropdown is cut on mobile

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7700]
## 📝 Provide detailed reproduction steps (if any)

1.  Open special characters dropdown on mobile

### ✔️ Expected result

I'm able to interact with the special characters feature.

### ❌ Actual result

![](https://user-images.githubusercontent.com/247363/88374739-8d72f380-cd9a-11ea-8886-565b0a8288a3.png)

## 📃 Other details

*   Browser: Chrome
*   OS: Android

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@oleq wasn't there already a more generic issue reported for that? #5514 _looks_ similar but the body doesn't have hidden overflow.
