### ISSUE TITLE
Link ballon should re-position on window scroll (regression)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7705]
## 📝 Provide detailed reproduction steps (if any)

1.  Select some text
2.  Open the link balloon
3.  Scroll the page

### ✔️ Expected result

The balloon sticks to the selection (like in v19.0.0).

![](https://user-images.githubusercontent.com/1099479/88395992-308b3380-cdc2-11ea-8b84-360b76795b65.gif)

### ❌ Actual result

![](https://user-images.githubusercontent.com/1099479/88396020-3b45c880-cdc2-11ea-8cbb-b4b038490d5c.gif)

The balloon position gets lost.

## 📃 Other details

*   Browser: cross-browser
*   CKEditor version: master

**It's a regression introduced in v20.0.0.**

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This looks nasty on mobile (check out the location of the balloon and the selection)

![](https://user-images.githubusercontent.com/1099479/88396375-beffb500-cdc2-11ea-995d-36db0c8ec1b2.jpeg)

**Comment by Reinmar** [comment]
We should start from bisecting this.

**Comment by mlewand** [comment]
The regression has been introduced in v20.0.0. The first bad commit is 52e53e6 part of #7436 PR (#4721 issue).
