### ISSUE TITLE
The special characters drop-down is rendered off-screen on mobile devices

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7709]
## 📝 Provide detailed reproduction steps (if any)

1.  In Safari/iOS open the special characters guide (vertical mode)

### ✔️ Expected result

The entire dropdown should be visible and accessible to the user. All glyphs should be visible.

### ❌ Actual result

![](https://user-images.githubusercontent.com/1099479/88405098-13109680-cdcf-11ea-9795-250e3023d6d5.jpeg)

## 📃 Other details

*   Browser: Safari
*   OS: iOS
*   CKEditor version: master

---

Quick idea: we may need more [default dropdown panel positions](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_dropdownview-DropdownView.html#static-member-defaultPanelPositions) as we [did with the balloon panel view in the past](https://github.com/ckeditor/ckeditor5/commit/9c442c4ab7a2d457563a4afd848389d2024a395b).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Dup of: #7700? :wink:

**Comment by oleq** [comment]
Haha, yes, of course.
