### ISSUE TITLE
Link plugin is not working in bootstrap modal

### ISSUE THREAD

**Issue by hirenbhut93** [ckeditor/ckeditor5#7712]
Link options is not work in bootstrap modal

**Comment by Mgsy** [comment]
Hi, it's a known issue, please check [our guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html#bootstrap-modals) about it.

**Comment by Ahmed-Aboud** [comment]
this might help if you are using bootstrap-vue
[](https://github.com/bootstrap-vue/bootstrap-vue/issues/2269#issuecomment-446331930)

**Comment by maneeshtiwari-ve** [comment]
Just Remove: tabindex="-1"

And Add: data-bs-focus="false"

I hope your Problem Solved :)

**Comment by maneeshtiwari-ve** [comment]
Just Remove: tabindex="-1"

And Add: data-bs-focus="false"

I hope your Problem Solved :)

**Comment by Yuvraj8823** [comment]
[](url)> Just Remove: tabindex="-1" on Bootstrap Modal
> 
> And Add: data-bs-focus="false"
> 
> I hope your Problem Solved :)

Tried as you suggested. link/hyperlink plugin is still not showing any popup box to update the link whereas things like video embeding or image upload buttons are working fine

I'm using ckeditor 5 36.0.1 classiceditor default through cdn and bootstrap 5.2

**Comment by amanc0des** [comment]
I found that it was quite troublesome to make this work with the Bootstrap modal. To solve the issue, I removed the default Bootstrap modal initialization and switched to a custom modal implementation. After doing this, everything worked perfectly fine.
