### ISSUE TITLE
Style combo box scroll not showing when it clicked on second time

### ISSUE THREAD

**Issue by cvak48** [ckeditor/ckeditor5#772]
## 📋 Steps to reproduce

1. Click on Style combo drop down menu and look for scroll bars
2. Select any item and repeat Step:1 and look for scroll bars

## ✅ Expected result
Should be same as Step:1
## ❎ Actual result
Scroll disappearing when second time clicks
## 📃 Other details that might be useful
following images may useful
https://drive.google.com/drive/folders/10whbOh4YJQBk2WXKJSXs1s04SAmwALr5?usp=sharing

**Comment by scofalik** [comment]
Hello @cvak48!

You reported an issue concerning CKEditor 4 version. This repository is for CKEditor 5, which is a different project.

Please report your issue here: https://github.com/ckeditor/ckeditor-dev

Thank you.
