### ISSUE TITLE
Remove incoherent paragraphs

### ISSUE THREAD

**Issue by elalekey** [ckeditor/ckeditor5#7722]
Currently when I copy/paste a text it generates multiple paragraphs that make no sense to be there, even causing the text to merge and not be readable.

![image](https://user-images.githubusercontent.com/41456459/88572142-b4386080-d00c-11ea-9280-d579b47f1920.png)

![image](https://user-images.githubusercontent.com/41456459/88572209-c87c5d80-d00c-11ea-90e6-05ec347d8e5a.png)

However when I paste it into a "demo" of CKEditor this does not happen, I am using vue to be able to use CKEditor

UPDATE: I solved with this function but i want to make a new "paragraph" when the user press "ENTER"

![image](https://user-images.githubusercontent.com/41456459/88572900-f1512280-d00d-11ea-932b-9992b34d2f38.png)

**Comment by FilipTokarski** [comment]
Hi, could you describe once again what is the problem now and provide a step-by-step description how to reproduce it? Also your editor configuration could be helpful here. Without this information, it will be hard for us to look into this issue.
