### ISSUE TITLE
Multi-cell selection with arrows+shift breaks when trying to go in opposite direction on single row/column

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7727]
## 📝 Provide detailed reproduction steps (if any)

1. Select a cell
2. Hold `shift` + click `arrow right` to create a multicell selection
3. Still holding `shift` start clicking `arrow left`, to go in opposite direction

### ✔️ Expected result

You can create multi-cell selection going in both directions

### ❌ Actual result

Once you go in one direction, if you then go in opposite direction and reach the single original cell, multi-cell selection breaks.
Screencasts:  
  
![28_table1](https://user-images.githubusercontent.com/34380544/88647860-bc54d680-d0c6-11ea-8455-615720f238b5.gif)
  
  
![28_table2](https://user-images.githubusercontent.com/34380544/88647903-c7a80200-d0c6-11ea-9bda-4f618961ff7a.gif)

## 📃 Other details
However, it works ok if you already have some multiple cells selected. Then you can go in any direction:  
  
![28_table3](https://user-images.githubusercontent.com/34380544/88648608-73e9e880-d0c7-11ea-8556-a162b18adb76.gif)

* Browser: Chrome, Firefox, Edge
* No errors in the console
* CKEditor version: introduced in 20.0.0, works fine in 19.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This seems that some other handler is taking over if one table cell is selected from outside

**Comment by niegowski** [comment]
Widget keydown handler is taking over if only one cell is selected from outside:

https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-widget/src/widget.js#L216-L227

Recently we simplified keydown handlers, and apparently missed this case

**Comment by niegowski** [comment]
I think that https://github.com/ckeditor/ckeditor5/blob/987265215d21f80277881173ac76ef7688135d15/packages/ckeditor5-table/src/tablekeyboard.js#L192 should be split into separate handlers for cells selected from outside (with the priority higher than widget handler) and for the selection inside the table cell (with current priority)

**Comment by jodator** [comment]
As @niegowski pointed out. This issue was fixed by #7770 and the #7739 PR added proper tests for this case.
