### ISSUE TITLE
Support for drag&drop of blocks

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7731]
## 📝 Provide a description of the new feature

Extracted from #2664. Scenario C and possibly D.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
We're hesitant between going with C (widgets only) only or C and D (all blocks).

We'd probably add some "handle" next to each block. Maybe, Notion-style. 

On click, that handle would select that block.

On drag, it would start reorganizing blocks.

**Comment by Witoso** [comment]
We are excited to announce that we have released an experimental feature of blocks drag and drop in CKEditor 5. Please note that this feature is not yet fully developed or tested, and it may not be ready for production use.

Live demos are available in our docs:
https://ckeditor.com/docs/ckeditor5/latest/features/pasting/drag-drop.html#drag-and-drop-of-content-blocks

### What works


https://github.com/ckeditor/ckeditor5/assets/9881379/081f6ebb-d467-4d21-9d26-bc0141c70256


- Selection of the whole text block and moving it inline **and** between blocks.
- Placement of blocks inside other blocks: tables, blockquote, etc.
- The pilcrow icon in the Ballon block editor behaves as a drag handle.

### What needs improvement

- Scroll the content while dragging.
- Drag and drop inside the lists.
- The drag handle is only available for the Ballon block editor.
- The drag handle is only visible on select, and not on hover.

### Setup

⚠️  This is an **experimental feature,** it is available for users, developers, and enthusiasts, who want to test out new functionality and provide feedback to the product team.  ⚠️

1. Update the editor’s packages or build to the `38.0.1+` version.
2. Add the `DragDropExperimental` plugin from the clipboard package (available for all builds).
3. If you use the Ballon block editor, add the `DragDropBlockToolbar` to drag and drop with the icon.
4. Rebuild the editor if needed and reload the page.

### Feedback

Let us know in comments, and in the reactions to this comment, what you think, and what enhancements would you like us to include in the stable release.

👍 - This looks great, keep it going!

👎 - I don’t like it, do something else.

🎉 - I want a drag handle for every editor type (something like: ⠿)

❤️ - The drag handle should be visible on hovering over blocks, next to them (let us know in comments how would you render that in your editor setups, what editor types you use, etc.?)

🚀 - Make it lists aware (placing inside lists, sublists creation).

**Comment by wimleers** [comment]
Looks _awesome_!

> I want a drag handle for every editor type (something like: ⠿)
Where you say "editor type" I think you mean widget/block type? Or maybe internally you call each of those an "editor"?

(To me, the entire CKEditor 5 UI _is_ "the editor".)

> The drag handle should be visible on hovering over blocks, next to them […]
Definitely not IMHO. That'd be visually very distracting. Also, that'd make the experience very different on touch devices?

**Comment by Witoso** [comment]
@wimleers thanks for the feedback 🌞 As for the editor type we mean different builds/UIs (inline, classic, balloon, document, [etc.](https://ckeditor.com/docs/ckeditor5/latest/examples/index.html)). Added this context to the main comment.

> Definitely not IMHO. That'd be visually very distracting. Also, that'd make the experience very different on touch devices?

Extremely popularized by Notion, and other block editors. On mobile usually the handle is hidden.

> this UX works well for vertically stacked content. How will it work for horizontally adjacent content?

As we don't have an official way of inserting grid layout into the editor (except tables), I think we will skip this in the stable 🤔 Placement before/after vertically would need some detection of columns.

> how does this work for nested stacked content, such as table rows, list items within lists (+ nested in that case), captions on images, et cetera? (For example: the demo video shows dragging into a table caption, but can you also drag out of there?)

Yes, you can drag the text out of table rows. List items probably require more UI polishing, and captions don't work as far as I see. Something we need to take a look at.

> keyboard support?

Haven't seen that in the wild, any examples? Usually, it's handled by standard copy-paste I guess.

**Comment by wotnak** [comment]
> > keyboard support?
>
> Haven't seen that in the wild, any examples?

Notion supports navigating between blocks and moving them using keyboard https://www.youtube.com/watch?v=_VXg62RyGuU&t=545s.
Wordpress Gutenberg editor also supports moving blocks by keyboard https://youtu.be/iRnaBwlIDco?t=143.

**Comment by Witoso** [comment]
Exciting update! 🎉 We've improved drag-and-drop of blocks in [v40.0.0](https://github.com/ckeditor/ckeditor5/releases/tag/v40.0.0), which has just been released. Now you can place blocks between other blocks more intuitively. For those using an editor with a balloon block toolbar, you can even initiate a drag from there. [Play with it out in our docs](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)!

Got more thoughts or feedback? There are still improvements we would like to make, follow and 👍 the #15110, if you're interested.
