### ISSUE TITLE
Document `--snippets` usage.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7737]
## 📝 Provide a description of requested docs changes

I've tried to use `--snippets` option to build some snippets from all. Some examples on how to construct this would be helpful.

Places I've searched for that information:

1.  https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html#generating-documentation
2.  https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/ckeditor5-dev-docs

**Comment by jodator** [comment]
It should be name of a file of a snippet.

**Comment by AnnaTomanek** [comment]
Why-o-why did it go to `master`? The rules are clear and even explained in the knowledge base :smiling\_imp:
