### ISSUE TITLE
Add a FAQ section in the docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#774]
Questions:

* [ ] Why the editor filters out my content (styles, classes, attributes, elements)? And why there's no `allowContent: true`?
* [ ] *This place is waiting for you*

**Comment by scofalik** [comment]
- How to turn on source mode / How to write a source mode plugin

**Comment by oleq** [comment]
* What happened to contents.css? How do I style the content of the editor?
* The build (editor) I use is missing \<feature\>. How to add it?
* Where's `editor.insertHtml()` and `editor.insertText()`?
* What happened to `window.CKEDITOR`?
* I want users to be able to drag&drop/upload images. Where should I start?

**Comment by Reinmar** [comment]
Great ideas, thanks! What else? :)

**Comment by Reinmar** [comment]
* Is there a Classic editor full package build with a full toolbar? (source https://github.com/ckeditor/ckeditor5/issues/860)

**Comment by Reinmar** [comment]
How to replace CKEditor 5 icons? (Answer: by using `NormalModuleReplacementPlugin`)

**Comment by scottmessinger** [comment]
I've been looking through the docs and I'm a bit confused as to the format the data is exported in. In the docs, `getData` is referenced, but it's unclear what format the string is -- is it using the XML  processor or the HTML one? Also, if we wanted to go all-in on ckeditor and save text in our database in the most optimal, highest fidelity, fastest-for-ckeditor-to-parse format, how would I do that? Is there a JSON export that would work best or is the XML data format the best?

**Comment by Reinmar** [comment]
PS. In the meantime, you can also check https://github.com/ckeditor/ckeditor5/issues/620.

**Comment by jeffryang24** [comment]
Hmm... How to add closing tag to the element from `editor.getData()` method, such as `<br>` become `<br />`? I found this FAQ in CKEditor4 but not in CKEditor5... :bow:
