### ISSUE TITLE
Advanced setup guide results in plugincollection-plugin-not-loaded error

### ISSUE THREAD

**Issue by Moteke** [ckeditor/ckeditor5#7746]
## 📝 Provide detailed reproduction steps (if any)

I followed [this installation guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html) step by step and ended up with an error. I tried to build the editor from source using webpack configuration with dependencies from the classic build's package.json.

My configuration files:
[_webpack.common.js_ ](https://pastebin.com/c2xz8uAM) - this one is merged with [_webpack.dev.js_](https://pastebin.com/tTfFfnf2)
[_package.json_](https://pastebin.com/9KpG1mRy)
[_ckeditor.js_
](https://pastebin.com/GQNjgSAu) and the final one [_index.js_](https://pastebin.com/wsK3hb3T)
__

### ✔️ Expected result

Loaded editor built from source.

### ❌ Actual result

**First, I get 2 terminal errors:**
`[CKEditorWebpackPlugin] Error: No JS asset has been found during the compilation. You should add translation assets directly to the application from the translations directory. If that was 
intentional use the buildAllTranslationsToSeparateFiles option to get rif of the error.`

`[CKEditorWebpackPlugin] Error: Too many JS assets has been found during the compilation. You should add translation assets directly to the application from the translations directory or use the addMainLanguageTranslationsToAllAssets option to add translations for the main language to all assets or use the buildAllTranslationsToSeparateFiles if you want to add translation files on your own.`

**Next, there are these fatal errors in the browser console:**
![chrome_J6pbg3MXhR](https://user-images.githubusercontent.com/30510104/88853591-3d5bbd00-d1f0-11ea-83f8-64f1cf0e6f1d.png)

While importing all plugins in ckeditor.js file, I get this message with each of them:
![ss-npm-err](https://user-images.githubusercontent.com/30510104/88854205-3b462e00-d1f1-11ea-98b3-94ea33556e4a.png)

I think I'm probably missing something, but I couldn't find a proper solution. I've seen solved issues with the same error for Vue.js guide, but it isn't relevant to this one.

**Comment by FilipTokarski** [comment]
Hi, I checked the guide and I was able to build the working editor. This guide assumes some previous knowledge of how CKEditor works and how to use it with custom Webpack configurations - so some sentences might not sound as precise as expected. 
So, to sum up:
- first you need to install all dependencies, which can be based on this: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/package.json
- create `webpack.config.js` file which  specifies _at least_ entry, output, plugins and rules for loaders, better example here:
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/webpack.config.js
- in your entry directory add `ckeditor.js` file which specifies editor type and its configuration, like here:
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/src/ckeditor.js
- build editor using `webpack --mode production`
- in your `html` file add container for the editor and create editor instance using the build file:
```html
<script src="../build/ckeditor.js"></script>
<script>
	ClassicEditor.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( error => {
			console.error( 'There was a problem initializing the editor.', error );
		} );
</script>
```
like here: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/sample/index.html .   
  
And this should be enough to run the editor. I would advise to double check your implementation if everything is correct. You can also see [quick start](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html) guide and docs on [custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html), which might be helpful here.

**Comment by Moteke** [comment]
It must have been a problem with other packages or something related to that - I built it separately and it works.
