### ISSUE TITLE
Tab key does not insert 'indentation' inside text

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#7751]
## 📝 Provide detailed reproduction steps (if any)

When I press the 'Tab' key to insert an indent between text.

### ✔️ Expected result

Example: START TAB:    :END TAB

### ❌ Actual result

Example: START TAB: :END TAB

## 📃 Other details

Tab works as a focus manager between different widgets.

* Browser: Any
* OS: Any
* CKEditor version: Any
* Installed CKEditor plugins: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. Actually, we have this feature request already reported - #7541. Feel free to add :+1: to the first post and join the discussion to bump its popularity.
