### ISSUE TITLE
Image Styles don't work in vue.js

### ISSUE THREAD

**Issue by liuxin2046** [ckeditor/ckeditor5#7757]
## 📝 Provide detailed reproduction steps (if any)
1. I had import imagetoolbar imageStyles module

![A88DA26A-4651-4578-8708-2F062BC0DE20](https://user-images.githubusercontent.com/33651766/89023491-39e24600-d356-11ea-99fa-e50c2f9e80e0.png)

2.  Here is editorConfig

![C377E8DE-E2C3-4da5-ACEA-15548F232026](https://user-images.githubusercontent.com/33651766/89023524-4bc3e900-d356-11ea-8de3-2d8c6fb54755.png)

![DE2B4357-E9EF-4b97-A486-AE0798A0B565](https://user-images.githubusercontent.com/33651766/89023559-59796e80-d356-11ea-9808-2126212c5d0f.png)

![58B1D6AB-1BF2-48a9-8533-B4339325C84B](https://user-images.githubusercontent.com/33651766/89023571-5f6f4f80-d356-11ea-9b04-61192169caf7.png)

`

### ✔️ Expected result
![9AF933C0-2943-48ba-86BF-41FE8BA34A22](https://user-images.githubusercontent.com/33651766/89023729-9b0a1980-d356-11ea-9815-f4ef901452fa.png)

### ❌ Actual result
I can't set image styles, It does not take effect

![F8F42E53-504F-4a6e-9E4E-146912CB9CEE](https://user-images.githubusercontent.com/33651766/89023869-d3a9f300-d356-11ea-8851-3eba5301ef8f.png)

## 📃 Other details

* Browser: chrome 84.0.4147.105
* OS: window
* CKEditor version: CkEditor5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, I just checked Vue integration with Image plugin and I had no problem with the toolbar and [image styles](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-styles), so this is not a bug in the editor itself or with Vue integration. I'm afraid there might be something wrong in your implementation, so please double check if your configuration is ok.

**Comment by liuxin2046** [comment]
Thanks Reply，I refer to the documentation and I use the editor built from source, also i refer to the configuration of the document. Heading, Font is normal except for image style, I did not find the error. @FilipTokarski

**Comment by liuxin2046** [comment]
Do I need to add relevant css？ Can someone help me？

**Comment by Mgsy** [comment]
@liuxin2046, do you have any errors/warnings in the console?

**Comment by liuxin2046** [comment]
I have found the problem, other components I use affected it, thank you @Mgsy
