### ISSUE TITLE
Content styles docs page is broken

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#7766]
## 📝 Provide a description of requested docs changes

See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html

![](https://user-images.githubusercontent.com/617641/89226032-87231980-d5db-11ea-892f-96f8037ba766.png)

It's not just broken formatting, there are unfinished comment blocks etc. so copy & paste will result in incorrect / largely commented out CSS.

**Comment by pomek** [comment]
Thanks for the report. 

The stylesheet is generated properly (see [the page raw file](https://raw.githubusercontent.com/ckeditor/ckeditor5/master/docs/builds/guides/integration/content-styles.md)) but we're missing code block markup.

**Comment by pomek** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/2270764/89255660-92e5fe80-d622-11ea-948c-1ee2c59ad865.png)
