### ISSUE TITLE
pastring from word is not work 

### ISSUE THREAD

**Issue by iyuchang** [ckeditor/ckeditor5#7767]
![image](https://user-images.githubusercontent.com/14918254/89246192-23c9d380-d63d-11ea-815e-031d9dff5e66.png)

![image](https://user-images.githubusercontent.com/14918254/89246232-3e9c4800-d63d-11ea-830f-dea22abb5675.png)

**Comment by Mgsy** [comment]
Hi, thanks for the report. Just to be sure - do you copy the content from MS Word or other software?
