### ISSUE TITLE
Docs: Change required Node.js version to 12.0.0+

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#7771]
## 📝 Provide a description of requested docs changes

Our docs are outdated and mention incorrect Node.js requirements. Examples:

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#requirements 6.9+

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html#requirements 8.0+

**Comment by AnnaTomanek** [comment]
Also:

According to https://github.com/ckeditor/ckeditor5/blob/master/package.json#L118, the minimum required npm version is 5.7.1.

We should fix it in places like https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#requirements

**Comment by godai78** [comment]
Addressed in this PR: #7772
