### ISSUE TITLE
Providing additional options to the DowncastHelpers config.view callback

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#7774]
Follow-up: https://github.com/ckeditor/ckeditor5/issues/7628

We are going to introduce additional options passed to the downcast conversion through `getData` / `DataController#get`.
Those options will be available through `ConversionApi`. Since `DowncastHelpers` does not have access to `ConversionApi` only custom converters will be able to use them. However, it would be very useful to use those options in DowncastHelpers in `config.view` callback.

The easiest way seems to be providing the entire `ConversionApi` to `config.view` callback.

How this change will correspond to the [changes in UpcastConversion](https://github.com/ckeditor/ckeditor5/pull/7652)?

**Comment by Reinmar** [comment]
cc @jodator 

Recently, @jodator proposed to add `conversionApi` to the `config.view` callbacks in #7334.

**Comment by jodator** [comment]
> How this change will correspond to the [changes in UpcastConversion](https://github.com/ckeditor/ckeditor5/pull/7652)?

So this shouldn't be blocking. As in the above comment, #7334 should be closed first.

**Comment by oskarwrobel** [comment]
Closed by https://github.com/ckeditor/ckeditor5/issues/7334.
