### ISSUE TITLE
Balloon Editor toolbar does not get hide when move focus from Editor in Safari Mac

### ISSUE THREAD

**Issue by gauravjain028** [ckeditor/ckeditor5#778]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

"@ckeditor/ckeditor5-build-balloon": "^1.0.0-alpha.2"

## 📋 Steps to reproduce

1. Select any text in [Balloon Editor Example](https://docs.ckeditor.com/ckeditor5/latest/examples/builds/balloon-editor.html)
2. Now click on Link Toolbar Icon.
3. Click outside of Editor.

## ✅ Expected result
It should close the Link dialog box and Editor Toolbar as well.

## ❎ Actual result
It is closing the Link dialog box only and Editor toolbar will not get hide, even we click outside of editor multiple times.

## 📃 Other details that might be useful
I am getting this error on Safari Browser [Version 11.0.1 (13604.3.5)]. It is working file on Chrome.
<img width="613" alt="screen shot 2018-01-22 at 3 31 22 pm" src="https://user-images.githubusercontent.com/2246860/35215284-c1d50cd0-ff89-11e7-95db-dcb2870333e4.png">
<img width="536" alt="screen shot 2018-01-22 at 3 31 13 pm" src="https://user-images.githubusercontent.com/2246860/35215287-c21b159a-ff89-11e7-90e0-142a7c28d5b1.png">

**Comment by Mgsy** [comment]
Hi, @gauravjain028, thanks for the report. I can confirm this issue. After opening the link balloon/text alternative balloon, there is no possibility to blur the editor. It looks like the editor is still focused, but selection has disappeared. The same behaviour we can observe while using inline editor.

![bug_cke5](https://user-images.githubusercontent.com/20988892/35265969-0d4095e8-0022-11e8-8724-e004656f70fe.gif)

I can reproduce it in Firefox and Safari. 

In Edge, we have different case. It's really strange. After opening the link balloon and blurring the editor, whole screen becomes covered by autocomplete items from the input. It's reproducible in classic, balloon and inline editors.

![bug_cke5](https://user-images.githubusercontent.com/20988892/35266667-3a7591e2-0024-11e8-9f6d-2cc3c95e5784.gif)

cc @Reinmar

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
I confirm the issue in Safari. There's a problem with the balloon editor toolbar + link/image text alternative.

**Comment by oleq** [comment]
@Mgsy Can you still confirm this issue? I was unable to reproduce it.

**Comment by Mgsy** [comment]
>@Mgsy Can you still confirm this issue? I was unable to reproduce it.

I can't reproduce it either.

**Comment by oleq** [comment]
Safari Version 11.1 (13605.1.33.1.2)

![kapture 2018-04-04 at 15 56 24](https://user-images.githubusercontent.com/1099479/38312013-e28e3e68-3820-11e8-8aee-cbb40175665e.gif)

Anyone?

**Comment by Reinmar** [comment]
I can't reproduce it either.

**Comment by fsbraun** [comment]
I seem to have the issue with the current version 45.

![Image](https://github.com/user-attachments/assets/fb6a6644-803a-407f-8490-8f6c87512fbb)

**Comment by fsbraun** [comment]
Same with inline editor:

* In the [demo](https://ckeditor.com/ckeditor-5/demo/editor-types/#inline), second editor I open the images ALT attribute
* Click save
* Click into the first editor

On Safari 18.5, the toolbar of the second stays.
