### ISSUE TITLE
Can't access property "appendChild", toolbarContainer is null

### ISSUE THREAD

**Issue by santonini82** [ckeditor/ckeditor5#7782]
Following [this](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html#document-editor) guide I get the error:

**Can't access property "appendChild", toolbarContainer is null**

### ✔️ Expected result

Text Editor is rendered correctly

### ❌ Actual result

The text editor does not have a toolbar

## 📃 Other details

* Browser: Mozilla Firefox
* OS: Ubuntu
* CKEditor version: 21

**Comment by Mgsy** [comment]
Hi! I've just checked the code from the snippet and the editor initializes properly. Do you have a proper HTML markup? The error message indicates that a container with `toolbarContainer` ID might not exist.

**Comment by santonini82** [comment]
OK
I had not noticed that the element `<div id = "toolbar-container"> </div> `must already be present in the HTML
I thought the element `<div id = "editor"> </div>` was enough
Thank you
