### ISSUE TITLE
MathType / ChemType not works when editor is used inside Bootstrap Modals

### ISSUE THREAD

**Issue by rohitcoder** [ckeditor/ckeditor5#7784]
## 📝  Reproduction Steps

1. Setup bootstrap simple page
2. Build your own Ckeditor5 with MathType plugin
3. Now, add a button to launch bootstrap modal and inside that modal add ``<div class='modal'></div>``
4. Now, initialize your ClassicEditor
5. Now, Click on MathType icon and try to type any text it wouldn't work.

### ✔️ Expected result

MathType / ChemType should work inside modals

### ❌ Actual result

MathType / ChemType not working inside modals

## 📃 Other details

* Browser: Chrome
* OS: MacOS
* CKEditor version: 21.0.0 

---

**Comment by Mgsy** [comment]
Hi, can you check if [this fix](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html#bootstrap-modals) works for you?

**Comment by rohitcoder** [comment]
Hi @Mgsy ,

Yes i confirm this works!

**Comment by mskashef** [comment]
I have got the same issue from Material UI Modals.
I simply set the `disableEnforceFocus` property of the dialog to `true`

```JSX
<Dialog fullScreen open={open} onClose={handleClose} TransitionComponent={Transition} disableEnforceFocus={true}>
     {/* dialog content... */}
</Dialog>
```

And solved my problem.

**Comment by pooja-create** [comment]
thank you sooooo  much
