### ISSUE TITLE
how to insert span tag after select the p tag text. actually i was using writer.createElement()

### ISSUE THREAD

**Issue by Gayudhaya** [ckeditor/ckeditor5#7786]
## 📝 Provide detailed reproduction steps (if any)

editor.model.change( writer=>{
                writer.createElement( 'span' );
            
                
            })

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor5/tree/master/.github/ISSUE_TEMPLATE). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/reporting-issues.html) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by Stamped-cadby** [comment]
> We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor5/tree/master/.github/ISSUE_TEMPLATE). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
> 
> Please refer to [our guide on how to report issues](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/reporting-issues.html) on the tracker, and open a new issue using the template as this one is being closed now.





https://conservationist-round.github.io/2lW99Yy1ezpAFKfU2QD1dC9NT75IaEQSth2LQtKnGLwwEgzgFl3PBI1VAJTl7WBs1gnBzg/
