### ISSUE TITLE
How to add id anchor to the editor and scroll to the position after opening the doc?

### ISSUE THREAD

**Issue by geohuz** [ckeditor/ckeditor5#7788]
## 📝 Insert id anchor for element and scroll to the anchor upon opening

_What is the expected behavior of the proposed feature?_

--- In a long document with date line split for every day, I would like to insert a heading with id=new Date(), and the editor can scroll to specific date anchor programmatically upon next opening.

I would appreciate any suggestion with programming this feature using the framework. I'm totally newbie and can't figure out the steps to do this.  

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
You can do a simple trick to put a selection in the place where you'd like to scroll to and then call [`scrollToTheSelection()`](https://ckeditor.com/docs/ckeditor5/20.0.0/api/module_engine_view_view-View.html#function-scrollToTheSelection).

```javascript
// Find the element where you'd like scroll to in editor model document.
// Set the selection in there, like
//	editor.model.change( ( writer ) => {
//		writer.setSelection( elementToBeFocused, 0 );
//	} );

const editingView = editor.editing.view;

editingView.scrollToTheSelection();
editingView.focus();
```
