### ISSUE TITLE
[FF] Styling is lost after using markdown formatting in list item

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#779]
Originally reported here - https://github.com/mozilla/notes/issues/584

## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Delete whole content.
3. Put the caret at empty paragraph and type `Sample paragraph. ` (remember about whitespace at the end).
4. Select the sentence from the right to the left using mouse.
5. Copy it.
6. Paste text to two new paragraphs.
7. Select all three paragraphs, starting from the last one.
8. Convert them into the ordered list.
9. Put the caret at the end of the first list item.
10. Type `**test**` and press <kbd>Spacebar</kbd>.
11. Repeat step 10 for the second item.

## ✅ Expected result

Styling of formatted word doesn't disappear.

## ❎ Actual result

Styling of formatted word disappears.

## 📃 Other details that might be useful

**Notes**

- Styling of the first and last word doesn't disappear.
- Sometimes this bug isn't reproducible, so if you can't reproduce it, try to repeat scenario few times.
- I was able to reproduce it also with 3 list items.

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/35276829-00dbba26-0045-11e8-88b7-38eb16a1606a.gif)

**Other information**
OS: Windows 10
Browser: Firefox

**Comment by Reinmar** [comment]
Can you reproduce it on the latest master? I couldn't.

**Comment by Mgsy** [comment]
> Can you reproduce it on the latest master? I couldn't.

Yes, I was testing it on the latest master. As you can see in https://github.com/mozilla/notes/issues/584, I also had problems with reproducing this issue, but finally I made it. 

It looks like this one is pretty random. Inside the issue from Mozilla Notes you can find a screencast showing this bug on https://ckeditor5.github.io.

**Comment by Mgsy** [comment]
I think that I've found some dependency. It looks like all actions related to selecting content must be done with mouse, not keyboard, i.e. <kbd>Ctrl</kbd> + <kbd>A</kbd>.

I've updated scenario for exact steps and changed the screencast.

**Comment by Mgsy** [comment]
This issue isn't reproducible anymore.
