### ISSUE TITLE
about vue use it

### ISSUE THREAD

**Issue by QQchu** [ckeditor/ckeditor5#7790]
## Provide a description of the task

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

I want to use its schema like the document example by vue https://ckeditor.com/ckeditor-5/demo/#document, but  <ckeditor></ckeditor> it doesn't work the way I want it to, so I use it <div class="document-editor">
          <div class="document-editor__toolbar"></div>
          <div class="document-editor__editable-container">
            <div class="document-editor__editable">
              <p>The initial editor data.</p>
            </div>
          </div>
        </div>  in vue.
But I have a problem,When I custom class MyUploadAdapter,I need useing vue instanced method in upload method, but this object is  MyUploadAdapter;

**Comment by abtafa** [comment]
Hi @QQchu 
 Even I also got the same problem. Anyway, I can help you now. In that Vue, file Create Uploader.js and paste given code and which page u want to add that uploader just add this config

step 1: install that upload adopter

step 2: create uploadAdopter.js like app.vue file place and paste this code.

export default class UploadAdapter {
  constructor (loader) {
    // The file loader instance to use during the upload.
    this.loader = loader
  }

  // Starts the upload process.
  upload () {
    return new Promise((resolve, reject) => {
      const reader = new window.FileReader()

      reader.addEventListener('load', () => {
        resolve({ default: reader.result })
      })

      reader.addEventListener('error', err => {
        reject(err)
      })

      reader.addEventListener('abort', () => {
        reject()
      })

      this.loader.file.then(file => {
        reader.readAsDataURL(file)
      })
    })
  }

  // Aborts the upload process.
  abort () {
    //
  }
}

step 3: import ur uploader file and check path and your path is correct it will work like this
        import UploadAdapter from '../UploadAdapter'  -- in your vue file and add the editor config pages like this

 editorConfig: {
        extraPlugins: [this.uploader],

}

step 4:  In method object function paste this code 
 uploader (editor) {
      editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
        return new UploadAdapter(loader)
      }
    },


that's its ur upload adopter now will work

**Comment by QQchu** [comment]
> Hi @QQchu
> Even I also got the same problem. Anyway, I can help you now. In that Vue, file Create Uploader.js and paste given code and which page u want to add that uploader just add this config
> 
> step 1: install that upload adopter
> 
> step 2: create uploadAdopter.js like app.vue file place and paste this code.
> 
> export default class UploadAdapter {
> constructor (loader) {
> // The file loader instance to use during the upload.
> this.loader = loader
> }
> 
> // Starts the upload process.
> upload () {
> return new Promise((resolve, reject) => {
> const reader = new window.FileReader()
> 
> ```
>   reader.addEventListener('load', () => {
>     resolve({ default: reader.result })
>   })
> 
>   reader.addEventListener('error', err => {
>     reject(err)
>   })
> 
>   reader.addEventListener('abort', () => {
>     reject()
>   })
> 
>   this.loader.file.then(file => {
>     reader.readAsDataURL(file)
>   })
> })
> ```
> 
> }
> 
> // Aborts the upload process.
> abort () {
> //
> }
> }
> 
> step 3: import ur uploader file and check path and your path is correct it will work like this
> import UploadAdapter from '../UploadAdapter' -- in your vue file and add the editor config pages like this
> 
> editorConfig: {
> extraPlugins: [this.uploader],
> 
> }
> 
> step 4: In method object function paste this code
> uploader (editor) {
> editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
> return new UploadAdapter(loader)
> }
> },
> 
> that's its ur upload adopter now will work

 my problem is that how show document's style by using vue like Official documents, if I use vue ckeditor component,it looking diferent with Official documents,
if  l use div mode, I need useing vue instanced method in upload method, but this object is MyUploadAdapter;
but Thank you very much for your answer

**Comment by Mgsy** [comment]
> my problem is that how show document's style by using vue like Official documents

The document editor styling could be changed by CSS. [Here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html) you can find a guide explaining how to achieve the result presented in our official demo. Keep in mind that you have to provide a proper HTML markup in your Vue app to make it work.
