### ISSUE TITLE
 Table and cell styling tools - Vue Js 

### ISSUE THREAD

**Issue by abtafa** [ckeditor/ckeditor5#7798]
Hi, I am using the document editor default plugins. its help full for my vue Js small project and very flexible. And I want to add some more features in that document plugin. I have to add  Table and cell styling tools in that document Editor. But whatever instruction in that CKEditor Document followed. But not able to fix that issue. so any can suggest to what I have to do next step and I leave my code below. I'm using vue js framework

Require my Project: I have to add color table border and background color for that I installed package CKeditor table

**editorConfig**: {
        placeholder: 'Type the content here!',

        table: {
          contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableCellProperties',
            'tableProperties'
          ],
        }
      }

I added that editor config and Installed the npm package. but I'm getting this error

Error :: - toolbarview-item-unavailable: The requested toolbar item is unavailable - {name: "tableCellProperties"}.

I don't know what next go do. can you pls guide me in that

Thanks
Abtaf A

**Comment by Mgsy** [comment]
Hi, please don't open multiple issues for a single problem. I've answered you in your second ticket - #7811.

**Comment by Mohsen-graphyy** [comment]
Hi, I fixed this problem by adding this config :
 `{ 
     removePlugins: ['MediaEmbedToolbar'] 
}` 
It works for me and I no longer get this warning.
