### ISSUE TITLE
[Edge] Selection moves to the beginning of the document after using autoformat

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#780]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret at the end of the `Paragraph`.
3. Type `*test*`.

## ✅ Expected result

Selection doesn't change.

## ❎ Actual result

Selection has moved to the beginning of the document.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/35269408-3032ca26-002c-11e8-8bd4-72f5725dfe23.gif)

**Other information**
OS: Windows 10
Browser: Edge

**Comment by oleq** [comment]
I confirm the issue. It's quite severe, unfortunately :(

**Comment by Mgsy** [comment]
It's not reproducible anymore.
