### ISSUE TITLE
paste-from-office: Losing indent level for nested lists of different type (numbered, bullet)

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor5#7805]
## 📝 Reproduction Steps

1. Created a nested list in MS Word (Office 365) as follows:

    > * Lorem
    > * Ipsum
    >     1. Dolor
    >     2. Sit
    > * Amet

    See [Copy-Paste-Mixed-List-Issue-CKEditor.docx](https://github.com/ckeditor/ckeditor5/files/5040544/Copy-Paste-Mixed-List-Issue-CKEditor.docx) (first list shows error; second list works).

2. Copy the entire list
3. Paste it for example to [CKEditor 5 demo](https://ckeditor.com/ckeditor-5/demo/)

### ✔️ Expected result

Just as all other nested lists (even for mixed outer numbered, inner bullet) the nested indentation levels should be kept as is.

### ❌ Actual result

Indentation level of nested list is set to 0:

> * Lorem
> * Ipsum
> 1. Dolor
> 2. Sit
> * Amet

## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* Office: MS Word; Office 365
* CKEditor version: Most recent (CKEditor 5 demo) as well as custom using `"@ckeditor/ckeditor5-paste-from-office": "^20.0.0"`
* Installed CKEditor plugins: `"@ckeditor/ckeditor5-paste-from-office": "^20.0.0"`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I confirm this bug. However it seems to occur only if you have numbered items inside bulleted list, otherwise the indentation works fine:  
  
![word3](https://user-images.githubusercontent.com/34380544/89761529-dba02a80-daee-11ea-8839-d0ed076b7441.png)
  
-  occurs also on older versions
- browser: any

**Comment by pomek** [comment]
Lists in Word use the `id` property for marking the whole list as a structure. It means that nested lists have the same value of the property as their parents.

All list items have the same `id`:

![image](https://user-images.githubusercontent.com/2270764/97548592-9b569700-19cf-11eb-96f0-79a9b16d3c78.png)

However, for some, unknown reason, the first list in the attached document has mixed `id` values (a parent and a nested list are not the same).

I would say: I can reproduce the issue and I can't reproduce the issue at the same time. It depends on which list I use.

The list used for testing:

```
• Lorem
    1. Dolor
    2. Sit
• Ipsum
```

If I use the attached document as a source for testing, I am able to reproduce the issue. However, if I create a new list with the same structure, the issue does not occur.

I guess, something wrong happened with the existing list in the Word. I can't reproduce the issue when I create a fresh list.

**Comment by Reinmar** [comment]
Could you check this in CKEditor 4? If that works there, then perhaps we need to change the way how we process nested lists in PFO in CKE5.

**Comment by mmichaelis** [comment]
Comparing

* [CKEditor 4 Demo - The battle-tested WYSIWYG HTML editor](https://ckeditor.com/ckeditor-4/demo/)
* [CKEditor 5 demo - A set of ready to use rich text editors created with a powerful framework](https://ckeditor.com/ckeditor-5/demo/)

CKEditor 4 works without problems regarding the given example document (created with MS Office 365, if it matters). CKEditor 5 demo still shows the described problem.

**Comment by jodator** [comment]
Findings from the other PR: https://github.com/ckeditor/ckeditor5/pull/8390#issuecomment-721079455 & the rest of the conversation.
