### ISSUE TITLE
How to get delete element or range

### ISSUE THREAD

**Issue by pheeno** [ckeditor/ckeditor5#7807]
Hi there:
   Now i have a task to get element which is delete, is there any event or methods to get the delete one when typing backspace. please give me some help thanks.

**Comment by Mgsy** [comment]
Hi, I don't know your exact use case, however, CKEditor 5 implements a diffing mechanism, which is available under the [Differ instance](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_differ-Differ.html). So, you can use it to get the recent changes in the document by using `Differ#getChanges()`. 

The below code example will return information about the removed content and its position:

```javascript
editor.model.document.on( 'change:data', () => {
    for ( const change of editor.model.document.differ.getChanges() ) {
        if ( change.type === 'remove' ) {
            console.log( change );
        }
    }
} ); 
```

**Comment by pheeno** [comment]
i got it !! thanks!
