### ISSUE TITLE
How do I change the icon on the left of the form in CKEditor 5 Balloon Block?

### ISSUE THREAD

**Issue by SequelONE** [ckeditor/ckeditor5#7810]
Can you tell me how to change the icon on the left near the form? I need to replace it with a plus sign. Perhaps CKEditor 5 Balloon Block already has its own set of icons, where there may be a plus button. Is it possible to display this button when rendering the form?

![](https://habrastorage.org/webt/5f/2d/4b/5f2d4ba678aac585236860.png)

```
<script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/balloon-block/ckeditor.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/balloon-block/translations/ru.js"></script>
<script>
const textarea = document.getElementById('tickets-editor');
  BalloonEditor.create( document.querySelector( '#editor' ) , {
  language: 'ru',
  removePlugins: [ 'Table' ],
  toolbar: [ 'bold', 'italic', 'bulletedList', 'numberedList', 'blockQuote' ]
  })
  .then( editor => {
   window.editor = editor;
   } )
  .catch( error => {
  console.error( 'There was a problem initializing the editor.', error );
  } );
  editor.model.document.on( 'change:data', () => textarea.value = editor.getData());
</script>
```

* CKEditor version: 20.0.13
* Installed CKEditor plugins: Balloon Block

**Comment by Mgsy** [comment]
Hi, CKEditor 5 icons could be easily customized with webpack. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-customize-the-ckeditor-5-icons) you can find a guide explaining how to achieve it. The block toolbar uses a [pilcrow icon](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-core/theme/icons/pilcrow.svg), so this is the one you should change.
