### ISSUE TITLE
Table and cell styling tools - Vue Js

### ISSUE THREAD

**Issue by abtafa** [ckeditor/ckeditor5#7811]
Hi, I am using the document editor default plugins. its help full for my vue Js small project and very flexible. And I want to add some more features in that document plugin. I have to add Table and cell styling tools in that document Editor. But whatever instruction in that CKEditor Document followed. But not able to fix that issue. so any can suggest to what I have to do next step and I leave my code below. I'm using vue js framework

Require my Project: I have to add color table border and background color for that I installed package CKeditor table

editorConfig: {
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableCellProperties',
        'tableProperties'
      ],
    }
  }
I added that editor config and Installed the npm package. but I'm getting this error

Error :: - toolbarview-item-unavailable: The requested toolbar item is unavailable - {name: "tableCellProperties"}.

I don't know what next go do. can you pls guide me in that

Thanks
Abtaf A

**Comment by Mgsy** [comment]
Hi! The table properties plugin is not enabled by default, so you'll need to add it to your build. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) you can learn how to add a plugin to a build. Also, you can use our [CKEditor 5 online builder](https://ckeditor.com/ckeditor-5/online-builder/) to create a build with the desired plugins, then integrate it with your Vue project. 

To learn how to install the Table properties plugin, visit the [plugin documentation page](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-and-cell-styling-tools-2).

**Comment by abtafa** [comment]
Hi, @Mgsy thanks for immediate response. Now I using CKEditor 5 online builder and I added required plugins. then I checked not able to integrate with my vue project. can u pls look into that.
After download my online package I got build ckeditor.js. I copied that file and already using node modules CKEditor file there I replaced. but nothing showing now. I don't know how to integrate into my vue project

**Comment by Mgsy** [comment]
CKEditor 5 provides official integration with Vue. To learn how to integrate it into your project, please see our [integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html).

**Comment by abtafa** [comment]
Hi, @Mgsy thanks for your response. I understand integration with vue. but I got CKeditor 5 online builder file downloaded. then where I have to replace that file I'm asking. because after that I don't know what I have to do. the download builds to replace to old nodemodules/@ckeditor/CKEditor-build-decoupled-document file.

**Comment by Mgsy** [comment]
You have to specify a path to your build downloaded from CKEditor 5 online builder. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-es6-modules) is a code snippet which you should use. Instead of importing the classic build from `node_modules`, add a path to your custom build.

**Comment by abtafa** [comment]
Hi @Mgsy thank you for your response. finally done. what we did we created our build and replaced file to that nodemodules/ckeditor.js and in our vue component. then we added toolbar items. now it's working perfectly.
thanks, nice editor

**Comment by young-altair** [comment]
Dear @abtafa, would you like to give me a little guidance? I'm running into the exact same problem as yours, but haven't found a solution. I'm still a beginner at VueJS.
Thank you very much.
