### ISSUE TITLE
Google spreadsheet prepends HTML comment

### ISSUE THREAD

**Issue by robclancy** [ckeditor/ckeditor5#7812]
## 📝 Provide detailed reproduction steps (if any)

1. Copy from a google spreadsheet (test here https://docs.google.com/spreadsheets/d/1gaZVvQas-a5NSnSKqXC5n_mhh4ujLwGeTJkoDIR7KiI/edit#gid=0)
2. Paste in the demo (https://ckeditor.com/ckeditor-5/demo/)

### ✔️ Expected result

Paste as a table.

### ❌ Actual result

The table works fine, but it has a HTML prepended to it. 
`<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->`

![image](https://user-images.githubusercontent.com/857111/89744399-7e6a9180-da7a-11ea-8c52-ede564c44978.png)

## 📃 Other details

We have worked around this for now by stripping this stuff on our editor input. https://github.com/postedin/ember-ckeditor/blob/develop/addon/components/ckeditor/component.js#L89

* Browser: Chrome based
* OS: Linux, Mac, Windows
* CKEditor version: Tested on earlier versions with the same issue but now on latest (version 21) and whatever the demo version is

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, thank you for the report. We're aware of this issue and it's already reported [here](https://github.com/ckeditor/ckeditor5/issues/6059), so I'll close it as a duplicate.

**Comment by robclancy** [comment]
This is a bug not a feature request. And probably why I couldn't find the original issue... which has been open for 7 months. Google spreadsheets already work, even before all the table updates, except this one bug.

**Comment by robclancy** [comment]
So I guess this is yet another thing I have to go through your support for to show we spend money and get this fixed.
