### ISSUE TITLE
insert span element for selected text. inckeditor5

### ISSUE THREAD

**Issue by Gayudhaya** [ckeditor/ckeditor5#7818]
editor.model.change(writer =>{
                       const spanele = writer.createElement('paragraph');
                    //   const selection1 = writer.createSelection( spanele, 'in' );
                    //   editor.model.insertContent( writer.createText( 'x' ), selection1 );
                    //    writer.setSelection( selection );
                       editor.model.insertContent( spanele,writer.createPositionAt( editor.model.document.getRoot(), 0));
                       writer.setSelection( spanele, 'in' );

                    //  const docFrag = writer.createDocumentFragment();
                    //  writer.append(spanele,docFrag);
                    //    writer.insertText( 'context', spanele );
                    //    return docFrag;
                    // //     editor.model.insertContent( docFrag );
                            })
                    //         editor.model.insertContent( docFrag );  
                    //         console.log(editor,'--44')
                      }
                    }nt();

**Comment by Mgsy** [comment]
Hi, can you provide some description for your issue?
