### ISSUE TITLE
Exception when typing at the end of a link + basic style

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#782]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

For the following model:
```html
<paragraph>
    Foo <$text linkHref="url">bar</$text><$text bold=true linkHref="url">biz[]</$text>
</paragraph>
```
start typing

## ✅ Expected result

Bolded link should be inserted.

## ❎ Actual result

Explosion 💥 💥 💥 

## 📃 Other details that might be useful

Works fine for the following model:
```html
<paragraph>
    foo<$text bold=true linkHref="url">barbiz[]</$text>
</paragraph>
```
or
```html
<paragraph>
    f<$text bold=true>oo</$text><$text bold=true linkHref="url">barbiz[]</$text>
</paragraph>
```

## Gif

![jan-24-2018 01-16-50](https://user-images.githubusercontent.com/1057056/35308020-f4736a70-00a5-11e8-8eee-708ce879c976.gif)

**Comment by Mgsy** [comment]
DUP https://github.com/ckeditor/ckeditor5-typing/issues/120
