### ISSUE TITLE
How to put opened ballon block somewhere ?

### ISSUE THREAD

**Issue by arcaweb** [ckeditor/ckeditor5#7821]
Hi,

I would like to use the balloon editor on my element, but I have to move the balloon block in an always open left side fixed panel used to edit all element style only (not partially).

I do not find anything in API to customize ballon block container & position (= relative), is it possible with JS or the only solution is to manipulate many CSS ?

Or maybe an alternative, will be to have a ballon editor, and an decoupled editor in my left side panel ? But the plugin does not allow to use multiple instance on same element, and decoupled apply to words, not only to all element.

I am working on a jquery website, so without module building.

Any idea ?

Thanks :)

**Comment by arcaweb** [comment]
No idea ? :(

**Comment by Reinmar** [comment]
Hi! Sorry for late reply.

I tried to analyze your question, but I'm not sure I understand. AFAIU you want to reposition the block toolbar (the pilcrow icon) but I don't know where.

CSS-based solution should be the option here. But it will all depend on where do you want to move that button. If you could perhaps show that visually with some mockup, that might help.

**Comment by arcaweb** [comment]
Hi @Reinmar ,

It is for creating a live web page builder with settings panel (left or right), like you can find in wordpress and others. 

I'm looking for the best solution to have :  
- the paragraph editor (ie block toolbar) always opened in a settings panel (outside of the text)
- the text editor (ie ballon toolbar) inside my text

I have no complications with ballon block in my text, this is standard. 
But for the block toolbar, I do not found all events / settings to keep it open and in another place. Maybe it's not possible without rewriting some core code :/
Or maybe with version 4 ?

Is it more clear for you ?

Thanks for your help.

**Comment by arcaweb** [comment]
Hi @Reinmar , I come back to you to know if I you have any suggestions for my questions :)

**Comment by Reinmar** [comment]
Hi @arcaweb! It's much clearer now. I think that such customization is indeed a new feature. You can get a lot of inspiration from the existing implementation: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.js. Unfortunately, this plugin does not register anything to `editor.ui.componentFactory` so you cannot just do `editor.ui.componentFactory.create()`. You will need to copy a lot of the existing logic.

**Comment by Reinmar** [comment]
I reported a ticket to have the balloon block button in the component factory: #8068.
