### ISSUE TITLE
Class in `allowAttributes`?

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#7827]
I want to create bootstrap `card` widget. There are classes in `card-header` element like `card-header bg-success text-white`.
Event if I add `allowAttributes: ['class', 'id'],` to schema `class` attribute is handled somehow different that `id` for example. I cannot add classes during creation of card header:
```
const cardHeader = writer.createElement('cardHeader', {
        id: 'sdasd',
        classes: ['bg-success', 'text-white']
    });
```
`id` attribute is not ignored but `class` is. Why?

**Comment by jodator** [comment]
I think that you have something mixed up as the model (schema definition) doesn't need to have view attributes, it might be something like `isSuccess` (or `type`) and setting it in the model to `true` / `false` would render the view element differently.

Also if you define in schema attribute `class` the model attribute should be `class` not `classes` but again, this is not how the model should be defined. For instance, if your `cardHeader` in the view is:

```html
<div id="foo" class="card-header bg-success text-white">...</div>
```

and the class "bg-succes" is either set or not but "text-white" is always the same, the model can be:

```html
<cardHeader id="foo" isSuccess="true">...</cardHeader>
```

Now the conversion must also reflect this:

```javascript
// view-to-model
editor.conversion.for( 'upcast' ).elementToElement( {
	view: {
		name: 'div'
		classes: 'card-header'
	},
	model: ( viewElement, writer ) => {
		return writer.createElement( 'cardHeader', {
			id: viewElement.getAttribute( 'id' ),
			isSuccess: viewElement.hasClass( 'bg-success' )
		}
	}
} );

// model-to-view
editor.conversion.for( 'downcast' ).elementToElement( {
	model: 'cardHeader',
	view: ( modelElement, writer ) => {
		const isSuccess = modelElement.getAttribute( 'isSuccess' );
		return writer.createContainerElement( 'div', {
			id: modelElement.getAttribute( 'id' ),
			class: `card-header text-white${ isSuccess ? ' bg-success' : '' }`
		} );
	}
} );
```

**Comment by piernik** [comment]
Thanks for details. I get Your point problem is that there are many variations (success, primary, dange, warning, info...).

I have one suggestion. In schema I should be able to define which (or maybe all) classnames are allowed. Like `allowClassnames: ['bg-success', 'text-white]`
If this is defined Your engine should allow those classes to be picked. Or even (if it is widget) there should be button in tools that allows to pick class from defined in schema. I think working with classes is very needed in every project, so why not making it super simple.
If `allowClassnames: '*'` then all classnames are valid - in widget tool You can simple write classnames that has to be applied.

I think it would be great addition and super user friendly.

**Comment by jodator** [comment]
But the engine is not aware of CSS classes - the main idea here is to have a virtual model that is easier to operate on in collaboration or other processing. It operates on abstract attributes not related to DOM attributes and their meaning (like `id` or `class`). Now when converting to view you have a virtual representation of DOM (or HTML content) which is then translated to actual DOM in the browser.

Taking this into consideration, we would not see DOM-related specific attributes handling in the model. So, unfortunately, we cannot implement CSS class handling in the model. This requires a bit of overhead but OTOH manipulating this in model is way easier.

Consider mapping multiple set of class that goes together to a `type` attribute:

```
bg-success text-white			->	success
bg-warning text-black size-bg	-> 	warning
bg-error text-white size-huge	->	error
...
```

Manipulating this on model level would require to change only type:

```javascript
model.change( writer => writer.setAttribute( 'type', 'error', cardHeader );
```

But, this would require an `attributeToAttribute()` converter that would map `type` attribute to proper set of CSS class names. The `elementToElement` converter would be a bit simpler though.

ps.: You can have attribute `cssClassName` and put there anything what you'd like if you don't plan to change `cardHeader` type by the editor:

```javascript
// view-to-model
editor.conversion.for( 'upcast' ).elementToElement( {
    view: {
        name: 'div'
        classes: 'card-header'
    },
    model: ( viewElement, writer ) => {
        return writer.createElement( 'cardHeader', {
            id: viewElement.getAttribute( 'id' ),
            cssClassName: [ ...viewElement.getClassNames() ].join( ' ' )	// <-- read all CSS class names
        }
    }
} );

// model-to-view
editor.conversion.for( 'downcast' ).elementToElement( {
    model: 'cardHeader',
    view: ( modelElement, writer ) => {
        return writer.createContainerElement( 'div', {
            id: modelElement.getAttribute( 'id' ),
            class: modelElmeent.getAttribue( 'cssClassName' )				// <-- output it to the view
        } );
    }
} );
```

Also, I'm closing this issue. If you have any question, you can always post them on [StackOverflow with CKEditor5 tag](https://stackoverflow.com/questions/ask?tags=ckeditor5).
