### ISSUE TITLE
DomEmitterMixin should pass "passive" option for listener

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#7828]
## 📝 Provide a description of the improvement

The current implementation of `DomEmitterMixin` only supports `useCapture` option but no `usePassive` option.

This is needed for non-blocking `scroll` listeners - [https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
> The current implementation of `DomEmitterMixin` only supports `useCapture` option but no `usePassive` option.

@niegowski could you expand your ticket with why? When `usePassive` is needed, a use case.

**Comment by niegowski** [comment]
> @niegowski could you expand your ticket with why? When `usePassive` is needed, a use case.

This is needed for non-blocking `scroll` listeners - https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners
