### ISSUE TITLE
Link balloon doesn't open on the link selected with double-click

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#783]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Open sample with contextual toolbar (i.e. http://localhost:8125/ckeditor5-ui/tests/manual/contextualtoolbar/contextualtoolbar.html).
2. Delete whole content.
3. Type a word.
4. Apply link to it.
5. Double-click on this word.
6. Click on the link icon in contextual toolbar.

## ✅ Expected result

Link balloon opens properly.

## ❎ Actual result

Link balloon doesn't open.

## 📃 Other details that might be useful

**Notes**
In step 6, pressing <kbd>Ctrl</kbd> + <kbd>K</kbd> will give the same result.

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/35324862-53c14118-00f2-11e8-9e17-8d01e1b9a6b9.gif)

**Other information**
OS: All platforms
Browser: All browsers

**Comment by oleq** [comment]
DUP of https://github.com/ckeditor/ckeditor5-link/issues/152?

**Comment by oleq** [comment]
Also related to https://github.com/ckeditor/ckeditor5-ui/issues/354.

**Comment by Reinmar** [comment]
Let's merge it into https://github.com/ckeditor/ckeditor5/issues/852
