### ISSUE TITLE
DomEmitterMixin doesn't attach separate listeners for different options set (capture, passive)

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#7830]
## 📝 Provide detailed reproduction steps (if any)

If some plugin needs to attach a listener to some DOM node with different listener options, for example:

```javascript
editor.ui.view.listenTo( domElement, 'scroll', () => {
   // ...
}, { useCapture: true } );
```

Then new listener options are ignored if there were previously registered listeners with different options. So in the example above, if there was a listener for `scroll` on given `domElement` that wasn't using `useCapture` then all the following listeners will share options from the first one.

This is because of this check (it doesn't allow attaching a new listener with different options, it's reusing previously attached listener): 

https://github.com/ckeditor/ckeditor5/blob/2283aa4f743717eb09c527780c6ba3c21f57398d/packages/ckeditor5-utils/src/dom/emittermixin.js#L184-L188

### ✔️ Expected result

You should be able to attach DOM listeners with different options (some with `capture` and some without it).

### ❌ Actual result

All listeners to tame DOM node (and same event) are using the same listener options.

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
We'd also need to change how we memorize listeners here: [https://github.com/ckeditor/ckeditor5/blob/2283aa4f743717eb09c527780c6ba3c21f57398d/packages/ckeditor5-utils/src/dom/emittermixin.js#L201](https://github.com/ckeditor/ckeditor5/blob/2283aa4f743717eb09c527780c6ba3c21f57398d/packages/ckeditor5-utils/src/dom/emittermixin.js#L201)

E.g. we'd have to use `eventName:mode` format.

**Comment by Reinmar** [comment]
> E.g. we'd have to use `eventName:mode` format.

Note: It'd be better to avoid using `:` as a separator because we often use it already (e.g. event namespacing).

Format: `click([usePassive],[useCapture])`

**Comment by arkflpc** [comment]
Separate proxy is needed for each combination of modes (capture & passive). If only memorization was changed, non-capture callback would be called if another callback (capturing one) is added later. I.e:

```javascript
domEmitter.listenTo( parentNode, 'test', () => { console.log( 'I\'m not supposed to be called' ); } );
domEmitter.listenTo( parentNode, 'test', () => { console.log( 'I\'m ok to be called' ); }, { useCapture: true } );

childNode.dispatchEvent( new Event( 'test', { bubbles: false } ) );
```

This is because second `listenTo` adds the capturing handler to node, but the event is fired on the same proxy. And this proxy dispatches it to all attached callbacks, whether capturing or not.
