### ISSUE TITLE
Please teach me how to add custom event after execute a command

### ISSUE THREAD

**Issue by pheeno** [ckeditor/ckeditor5#7833]
Hi there 
  Please teach me how to add a custom event after execute a command , for example ,  could i add a custom code to notice the outer frame which contain CKEditor5  when 'undo' or 'redo' command execute ?  please give me some hint , thanks a lot .

**Comment by Mgsy** [comment]
Hi, you can listen to specific command execution and provide your custom code in a callback. See the example below:

```javascript
const command = editor.commands.get( 'Undo' );

command.on( 'execute', () => {
	console.log( 'Undo has been executed!' );
} );
```

The above code will fire the console log after executing undo. You can read more about commands in our documentation:

*   [event-execute](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html#event-execute)
*   [Commands](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/core-editor-architecture.html#commands)

**Comment by pheeno** [comment]
excellent! thanks!
