### ISSUE TITLE
How to add plugin to the build and use it in Angular application?

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#7837]
I created framework project (`my-ckeditor-custom-project`) according to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html.
I needed to create my custom plugins which I did...

But now I wanted to use them in my real project (outside `my-ckeditor-custom-project`).

How to export it so I can use ckeditor in `typescript`? 
If I create bundle with `webpack --mode production` there is one bundle file, but I cannot import anything from it:
```
import * as ClassicEditor from '../ckeditor/bundle.js';
import {ClassicEditor} from '../ckeditor/bundle.js';
import ClassicEditor from '../ckeditor/bundle.js';
const ClassicEditor = require( '../ckeditor/bundle.js' );
```
None of this works.
Even if I use `<script src="/assets/ckeditor/bundle.js"></script>` in html `ClassicEditor is not defined`.

I need ckeditor for `angular` application.

**Comment by ma2ciek** [comment]
The webpack configuration in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html doesn't seem to provide any library output - it creates just an executable JS script. If you want to add your plugin and create a custom build from it refer to the https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor.
