### ISSUE TITLE
Failed to send Slack message when GH action was unable to merge stable into master

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7839]
There are multiple commits on `stable` that are not available on `master`: https://github.com/ckeditor/ckeditor5/compare/stable?expand=1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
OK, that's probably because of a conflict:

![](https://user-images.githubusercontent.com/156149/90146681-9f382d00-dd81-11ea-9c89-1108b5e3cb9a.png)

But then – shouldn't we be notified somewhere?

**Comment by mlewand** [comment]
It should be posted to our #cke5-ci in case of conflict:  https://github.com/ckeditor/ckeditor5/blob/c15c8be92c6af2644e32bf9d23d4157835e8cfbf/.github/workflows/merge-stable.yml#L27-L31

I checked logs on GH and indeed there were some conflicted merges that were not notified on the channel. So it needs to be further investigated _why._
