### ISSUE TITLE
Re-enable no-unused-expressions ESLint rule

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7843]
## Provide a description of the task

I've stumbled upon that [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions) is commented out due to incompatibility with [chai expressions in tests suite](// We can't use it because of https://github.com/eslint/eslint/issues/2102).

After some digging I think that we could use ESLint configuration to disable some rules based on location. The thing is to disable that for tests.

**Comment by jodator** [comment]
So the `no-unused-expressions` is used mainly to detect:

```javascript
// No:
foo && doFoo( foo.bar );

// Also no:
escaped && ( escaped += escaped[ 0 ] );
```

I've used [`"chai-friendly/no-unused-expressions"`](https://github.com/ihordiachenko/eslint-plugin-chai-friendly) rule and found out that we have 18 errors in code for that.

Those can be grouped as:

1\. "smart code"

Hidden `if-else` :

```javascript
leaveBlockStartOnEnter( editor, data.isSoft ) ||
leaveBlockEndOnEnter( editor, data.isSoft ) ||
breakLineOnEnter( editor );
```

A getter that renders?

```javascript
// Render view#template along with collection of children.
view.element;
```

Implicit default value:

```javascript
this.colorTableView;
```

This can be just rewritten.

2\. Getters testing

This one is curious as we test if getters can throw something... but [getters should not throw](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/code-style.html#getters).

Some seems like testing shortcuts but most of the `Marker` getters could throw:

```javascript
expectToThrowCKEditorError( () => {
	marker.affectsData;
}, /^marker-destroyed/ );
```

---

One rule and some many things caught - I'm for restoring it and:

1.  Report the markers issues.
2.  Update "smart code"
3.  Disable this error on line in tests or rewrite tests if it would be quick.

**Comment by Reinmar** [comment]
Do we have examples in the code (\`src/\*\*\`) that would be caught with this rule?

I suppose you first saw a mistake/smelly code and then started looking for why this rule is off.

**Comment by jodator** [comment]
In `scr` are examples from 1 from my previous comment:

*   hidden `if-else` using \`||\` 
*   left-over `view.element` 
*   couple un-defined `this.fooView` which could be `this.fooView = undefined`

The base issue was from "external" PR with a construct: `escaped && ( escaped += escaped[ 0 ] );`.

**Comment by jodator** [comment]
After digging up this I've used `"overrides"` to override rule for tests instead of using external plugin. Although the above plugin works nice and allows for this check for test code except chai assertions I've felt that relaying on external plugin is less desirable.
