### ISSUE TITLE
Update marked dependency

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7850]
## Provide a description of the task

Follow-up for the #7307. The currently used version in `0.7.0` and the latest one is [`1.1.1`](https://github.com/markedjs/marked/releases/tag/v1.1.1). I've changed the version to `0.8.2` and the tests passed but it would be nice to test the upgrade in a real-world scenario.

@fredck could you check and/or confirm that upgrade to `1.1.1` would be safe?

**Comment by fredck** [comment]
> @fredck could you check and/or confirm that upgrade to `1.1.1` would be safe?

The PR that introduced Marked v1.0.0 contains the following:

> The only users that will need to change their code are users who are extending the lexer or parser currently. 

[We're indeed doing so](https://github.com/ckeditor/ckeditor5/blob/7cd5fc198e1977ecefbf0e455f4b514b467e7775/packages/ckeditor5-markdown-gfm/src/markdown2html/markdown2html.js#L31-L32), therefore we need to adapt the code to their newly introduced API.

Apart from that, once our tests pass, we should be good to go with it.

**Comment by fredck** [comment]
I've pushed a PR that starts he upgrade to v1.1.1.

I've added some questions to the PR though, so it's not ready to go still.
