### ISSUE TITLE
The tests start failing 

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7851]
## 📝 Provide detailed reproduction steps (if any)

It looks like [sinon.calledWithMatch](https://sinonjs.org/releases/v9.0.3/assertions/#sinonassertcalledwithmatchspyorspycall-arg1-arg2-) assertions for toolbar started to fail on master.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
May be related to https://github.com/ckeditor/ckeditor5/blame/2c10447fb8a6ccee9eea958ffa8c38642769aca1/yarn.lock#L10434-L10438.
