### ISSUE TITLE
insert table bug ( error:cannot-change-view-tree)

### ISSUE THREAD

**Issue by farshad-abb** [ckeditor/ckeditor5#7860]
1. using CKEditor5 in React
2. using a built file by online builder including all plugins related to table
3. @ckeditor/ckeditor5-table and other plugins are using version 21.0.0

when I try to insert a table by clicking table button in toolbar, I get the following error and the editor crashes.

**CKEditorError: cannot-change-view-tree: Attempting to make changes to the view when it is in an incorrect state: rendering or post-fixers are in progress. This may cause some unexpected behavior and inconsistency between the DOM and the view. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree**

when I use the watchdog feature with the current config, the problem gets solved. but I want to prevent the error without using watchdog

**Comment by FilipTokarski** [comment]
Hi thanks for the report. I just followed the steps you provided with React + editor from online builder and everything works fine. I don't get any errors when clicking table buttons and table works ok. I'd advise to double check whether you have everything set up properly on your side and whether you follow [docs on react integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html).
