### ISSUE TITLE
Review the markdown feature guide

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7862]
## 📝 Provide a description of requested docs changes

The markdown feature guide has big "**This feature is experimental!**" disclaimer - we might update it. For now I'd leave that this is still experimental but it's transitioning to a more stable form.

The other thing is that we could update the sample to add more supported features there. I've created a manual tests for this feature in 0bd756c - so this configuration could be re-used there.

**Comment by godai78** [comment]
There were some changes made to the guide/demo but more may come as needed: https://github.com/ckeditor/ckeditor5/pull/8336

**Comment by godai78** [comment]
I'd risk the statement that the purpose of this issue has been fully completed as of now, therefore this issue, too, may be deemed done.

**Comment by jodator** [comment]
~Sorry for the late reply. The disclaimer is still there. My concern was to remove the phrase.~

Doh, I feel safer with "experimental" being there after all :D.
