### ISSUE TITLE
Possible bug in handling newline element in blockqoute

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#7863]
## 📝 Provide detailed reproduction steps (if any)

Found here: #7859

Use `HtmlDataProcessor.toView()`  with (notice the `\n` after `</pre>`:

```
"<blockquote>\n<p>Example 1:</p>\n<pre><code>code 1</code></pre>\n<p>Example 2:</p>\n<pre><code>code 2</code></pre>\n</blockquote>\n"
```

This is converted to the view as (notice the `</pre> </blockquote>`)

```
"<blockquote><p>Example 1:</p><pre><code>code 1</code></pre><p>Example 2:</p><pre><code>code 2</code></pre> </blockquote>"
```

It is represented in the view as `Text` element with `" "` (space):

![](https://user-images.githubusercontent.com/247363/90520664-f109fa00-e169-11ea-86d9-6abc354474c8.png)

### ✔️ Expected result

The `" "` should not be inserted here.

## 📃 Other details

I'd suspect recent changes in handling paragraphable elements. But that's a wild guess.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
> I'd suspect recent changes in handling paragraphable elements. But that's a wild guess.

This issue is with us for many iterations, example [https://ckeditor.com/docs/ckeditor5/16.0.0/features/code-blocks.html](https://ckeditor.com/docs/ckeditor5/16.0.0/features/code-blocks.html) is also behaving the same way.
