### ISSUE TITLE
Update markdown-gfm's LICENSE.md after changing dependencies

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7865]
We need to list those deps and their licenses. Look for how "Lodash" is mentioned in some packages.

**Comment by jodator** [comment]
@Reinmar ~could you point me to some example. I couldn't find anything while searching for "lodash" in `*.md` or `*.json` files. Looking at all files also doesn't return anything in particular.~

I've found it under "lo-dash" - which IMHO is wrong name as this library goes by "Lodash" :upside\_down\_face: ([official site](https://lodash.com/), [releases](https://github.com/lodash/lodash/releases/tag/4.0.0)).
