### ISSUE TITLE
Fix the dependency to jsdoc

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7870]
```
warning "@ckeditor/ckeditor5-dev-docs > @ckeditor/jsdoc-plugins@23.1.1" has unmet peer dependency "jsdoc@^3.6.0".
```

That's probably after we moved to JSDoc 4?

**Comment by pomek** [comment]
Most probably we need to remove those lines:

https://github.com/ckeditor/ckeditor5-dev/blob/998c7a933972cb85287024580e63d788ad17d77b/packages/jsdoc-plugins/package.json#L25-L27
