### ISSUE TITLE
Should the label for the "Insert image via URL" form change

### ISSUE THREAD

**Issue by panr** [ckeditor/ckeditor5#7878]
## 📝 Provide a description of the improvement

We can consider if the label for the form should change to `Update image via URL`, when the user selects the image in the content and then opens the dropdown (the form input is filled). 

ATM, in that scenario, only the `submit` button will change, from `Insert` to `Update`. The label for the **Insert image via URL** is static (doesn't change).

![image](https://user-images.githubusercontent.com/1303365/90617162-a3939880-e20e-11ea-8005-3e36952a0902.png)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Sounds like a good idea. But maybe "Update image URL" instead of "Update image via URL"?
