### ISSUE TITLE
Image naming for keydown enter supporting

### ISSUE THREAD

**Issue by libterty** [ckeditor/ckeditor5#7880]
## Provide a description of the task

ATM we have an image upload plugin working fine however user cannot able to escape after they using keyboard enter event. They have to click the image again and only image itself after they have input something to save their input the the image.
I didn't find a way in the document to solve this. Is there a way for this workaround.

![Screen Shot 2020-08-19 at 7 21 40 PM (2)](https://user-images.githubusercontent.com/38395851/90629208-8df39280-e251-11ea-803b-d7f96851412a.png)

**Comment by Mgsy** [comment]
Hi, I'm not sure if I understand your use case. Could you please explain it precisely?
