### ISSUE TITLE
Pasting with shift pressed produces extra line breaks

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7884]
## 📝 Provide detailed reproduction steps (if any)

1.  Open [https://ckeditor.com/docs/ckeditor5/21.0.0/examples/builds/classic-editor.html](https://ckeditor.com/docs/ckeditor5/21.0.0/examples/builds/classic-editor.html)
2.  Copy two subsequent paragraphs of text
3.  Put the selection inside of the editor
4.  Paste with <kbd>ctrl/cmd</kbd> + <kbd>shift</kbd> + <kbd>v</kbd>

### ✔️ Expected result

The same behavior as with <kbd>ctrl/cmd</kbd> + <kbd>v</kbd> alone

### ❌ Actual result

![](https://user-images.githubusercontent.com/5353898/90727216-32fa8380-e2c3-11ea-9a6b-42607bcaeec7.png)

## 📃 Other details

[During the course it turned out](https://github.com/ckeditor/ckeditor5/issues/7884#issuecomment-689410602) that this should actually be a feature rather a bug, as this behavior comes from the browser putting extra EOL chars in the clipboard.

*   CKEditor version: v21

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
1. We put a double EOL character after each paragraph.
1. [We are losing soft line breaks](https://github.com/ckeditor/ckeditor5/issues/8045).

I was surprised to learn that the first problem might be actually inherited from contenteditable itself.

A comparison on how other editors handle this:

<table>
<thead>
<tr>
<th>CKEditor 5</th>
<th>Microsoft Word</th>
<th>Google Docs</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<pre><code>Paragraph

new paragraph

new paragraph

new paragraph

new paragraph

softBreak follows:softBreak follows:softBreak follows:

new paragraph</code></pre>
</td>
<td>
<pre><code>Paragraph
new paragraph
new paragraph
new paragraph
new paragraph
softBreak follows:
softBreak follows:
softBreak follows:
new paragraph
</code></pre>
</td>
<td>
<pre><code>Paragraph
new paragraph
new paragraph
new paragraph
new paragraph
softBreak follows:
softBreak follows:
softBreak follows:
new paragraph
</code></pre>
</td>
</tr>

<tr>
<th>CKEditor 4</th>
<th>Plain content editable (Chrome)</th>
<th>Plain content editable (Firefox)</th>
</tr>

<tr>
<td>
<pre><code>Paragraph

new paragraph

new paragraph

new paragraph

new paragraph

softBreak follows:
softBreak follows:
softBreak follows:

new paragraph</code></pre>
</td>
<td>
<pre><code>Paragraph

new paragraph

new paragraph

new paragraph

new paragraph

softBreak follows:
softBreak follows:
softBreak follows:

new paragraph</code></pre>
</td>
<td>
<pre><code>Paragraph

new paragraph

new paragraph

new paragraph

new paragraph

softBreak follows:
softBreak follows:
softBreak follows:

new paragraph</code></pre>
</td>
</tr>

<tr>
<th>TinyMCE</th>
<th>Microsoft Word 365 online</th>
<th></th>
</tr>

<tr>
<td>
<pre><code>Paragraph

new paragraph

new paragraph

new paragraph

new paragraph

softBreak follows:
softBreak follows:
softBreak follows:

new paragraph</code></pre>
</td>
<td>
<pre><code>Paragraph 

new paragraph 

new paragraph 

new paragraph 

new paragraph 

softBreak follows: 
softBreak follows: 
softBreak follows: 

new paragraph </code></pre>
</td>
<td>
</td>
</tr>
</tbody>
</table>

As mentioned, the fact that paragraph is converted into a double EOL character is inherited from `contenteditable` handling and all online editors except Google Docs keep this implementation.

TinyMCE however implements a feature which will convert such pasted content so that it doesn't have extra lines between.

Given that the behavior of separating paragraphs with two line breaks is common in web editors I think it make sense to keep it. However it make sense to implement a feature that will detect formatting like that and retain line breaks/soft breaks.

**Comment by Reinmar** [comment]
Double line breaks are also what I'd expect. They make the document look reasonably good when copied from the editor to a plain text editor. 

But the question here would be – can we solve the original issue assuming that we don't change the format? And if so – how would the fix look?

**Comment by mlewand** [comment]
The fix in this case is to _teach_ our plaintext to HTML conversion function that rule. This is actually what I have already have proposed in #8047.

**Comment by jodator** [comment]
> The fix in this case is to _teach_ our plaintext to HTML conversion function that rule.

My initial thought on this would be the same. Side note - WDYT about describing the plain-text \<-> editor (HTML) conversion. Would it be needed?

**Comment by mlewand** [comment]
@jodator where would you like to see this kind of description?

**Comment by jodator** [comment]
> @jodator where would you like to see this kind of description?

I'm thinking about a guide somewhere (maybe a section in Clipboard guide). But that's something for the future if we see that there's need for one. I was just thinking aloud here :)
