### ISSUE TITLE
Add support for the `yarn test -f [externalPackage]` command

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#7889]
A follow-up to the environment unification. I feel we should add support for `yarn test -f [externalPackage]` when the `externalPackage` is cloned to the `external` directory.

cc @pomek

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Yhm.

```
yarn run test -f comments

    comments
      ✔ should allow for adding comment thread
ERROR: 'Elements leaked (1):
<div class="ck ck-reset ck-editor ck-rounded-corners" role="application" dir=...
Be a good citizen and clean your DOM once you're done with it.'
      ✔ should not block comments editing
ERROR: 'Elements leaked (1):
<div class="ck ck-reset ck-editor ck-rounded-corners" role="application" dir=...
Be a good citizen and clean your DOM once you're done with it.'
    selection changes
      ✔ should allow for selecting all content
ERROR: 'Elements leaked (1):
<div class="ck ck-reset ck-editor ck-rounded-corners" role="application" dir=...
Be a good citizen and clean your DOM once you're done with it.'
    other safe commands
      ✔ should allow exporting to PDF
ERROR: 'Elements leaked (1):
<div class="ck ck-reset ck-editor ck-rounded-corners" role="application" dir=...
Be a good citizen and clean your DOM once you're done with it.'
  comments restricted editing mode integration (restricted editing)
    ✔ addCommentThread command should be enabled in restricted editing mode
  getDateTimeFormatter()

SUMMARY:
✔ 600 tests completed
✨  Done in 21.05s.
```

**Comment by ma2ciek** [comment]
This is a part I certainly don’t want to overcomplicate by introducing new resolution semantics etc. I like your proposal, on the other hand, the implementation becomes pretty ugly with our strategy of stripping the `ckeditor5-`  part whenever possible :smile: 

Maybe we could use `-e` instead of `-r` as a shortcut from `--external`? On the other hand, we could enhance the `-r` option to support `yarn test -r ckeditor5` as well (IDK if this makes sense).

**Comment by pomek** [comment]
> we could enhance the -r option to support yarn test -r ckeditor5 as well (IDK if this makes sense).

I was thinking about it as well and it makes sense to have an option to tests all packages from the root directory without removing external stuff.

**Comment by mlewand** [comment]
An option to run tests per repository seems to be fine :+1:
