### ISSUE TITLE
The "Creating a simple plugin" tutorial makes much less sense once we released that feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7891]
## 📝 Provide a description of requested docs changes

Inserting images via URL is now an official feature. This guide https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html cover the same kind of functionality.

We may need to find a better example now. Probably, a multi-step, richer feature that'd cover more engine and core and UI.

**Comment by Reinmar** [comment]
cc @AnnaTomanek

**Comment by godai78** [comment]
The tutorial has been fully replaced with two, new, shiny, and much more in-detail tutorials coming v.35.0.0.

I hereby deem this issue no longer valid.
