### ISSUE TITLE
Selecting an Image from bottom to top throws exceptions

### ISSUE THREAD

**Issue by ac-newcomp** [ckeditor/ckeditor5#7892]
## 📝 Provide detailed reproduction steps (if any)

1. Navigate to https://ckeditor.com/docs/ckeditor5/latest/features/image.html
2. Go to the sample with an image and add a newline below it
3. Select the image, starting from bottom to top
4. See GIF below for demonstration

![bug](https://user-images.githubusercontent.com/65816808/90837662-af6f7f80-e320-11ea-93af-cf0cb85674cb.gif)

### ✔️ Expected result

No errors thrown

### ❌ Actual result

The following error is thrown: `Uncaught CKEditorError: model-selection-range-intersects: Trying to add a range that intersects with another range in the selection. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…port/error-codes.html#error-model-selection-range-intersects
 {"addedRange":{"start":{"root":"main","path":[4],"stickiness":"toNext"},"end":{"root":"main","path":[5,73],"stickiness":"toPrevious"}},"intersectingRange":{"start":{"root":"main","path":[4,0,0],"stickiness":"toNone"},"end":{"root":"main","path":[4,0,0],"stickiness":"toNone"}}}`

## 📃 Other details

* Browser: FF79.0
* OS: Windows 10
* CKEditor version: all version that I've tested, including whatever version is on the CKEditor document page
* Installed CKEditor plugins: Image

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I confirm this bug.
Apparently it was introduced in 20.0.0, bisection shows this commit https://github.com/ckeditor/ckeditor5/commit/824d7317de8461773fab4f55cdfd6c585498131d

**Comment by Reinmar** [comment]
My guess:

1.  FF creates a multi-range selection in this case. At least, it did that in the past.
2.  Our post-fixer fixes one of these selections by e.g. extending it so it overlaps now with the other range.
3.  Error.

If I'm right, we could consider merging overlapping selections.

**Comment by psmyrek** [comment]
Firefox creates a multi-range selection containing three ranges, two of which are identical. The selection post-fixer tries to merge all of them together, but the `rangeA.isIntersecting( rangeB )` returns `false` for identical ranges. As a result, the selection returned from post-fixer contains not properly merged, intersected ranges.

**Comment by LangQian** [comment]
In FF (Win & Mac), with similar steps, this issue also happens to Horizontal Line

**Comment by psmyrek** [comment]
Yes, the Horizontal Line is also affected. My PR https://github.com/ckeditor/ckeditor5/pull/8466 is a general fix for all such cases.
