### ISSUE TITLE
CodeBlock don't support syntax highlight.

### ISSUE THREAD

**Issue by weijiang1994** [ckeditor/ckeditor5#7895]
CodeBlock don't support syntax highlight.

**Comment by mlewand** [comment]
This request is already tracked in #5769. Code blocks are meant to be a simpler code representation, while the full featured plugin you're asking got working name code snippets.

Please add :+1: there to show your support.

**Comment by weijiang1994** [comment]
> This request is already tracked in #5769. Code blocks are meant to be a simpler code representation, while the full featured plugin you're asking got working name code snippets.
> 
> Please add  there to show your support.

OK, Thanks~
