### ISSUE TITLE
Initialization of the ckeditor with deferred data loading

### ISSUE THREAD

**Issue by ZapevalovAnton** [ckeditor/ckeditor5#790]
Bug report. ckeditor version "@ckeditor/ckeditor5-build-balloon": "^1.0.0-alpha.2".

I want create simple ckeditor component for Vue.js. The contenteditable element is initially initialized with an empty value. After extracting data from the store, they are transferred to the editor via v-model attr. But ckeditor thinks that initially there should be an empty value and inserts the following into the element:

```html
<p>
  <br data-cke-filler="true">
</p>
```

- If commented ckeditor initialization, then the data is inserted normally.
- With other editors (eg quill.js), the data is inserted normally.

Code my Vue.js component:

```html
<template>
  <div contenteditable="true" v-html="value"></div>
</template>

<script>
	
  import BalloonEditor from '@ckeditor/ckeditor5-build-balloon'

  export default {
    name:  'Editor',

    props: [
      'value'
    ],

    mounted () {

      BalloonEditor
        .create(this.$el)
        .then((editor) => {
          editor.document.on('change', (e, data) => {
            this.updateContent(editor.getData())
          })
        })
      },

    methods: {

      updateContent (content) {
        this.$emit('input', content);
      },
    }
}

</script>

<style lang="scss">

  ol { margin-left: 15px; }
  ul { margin-left: 20px; }

</style>
```

**Comment by oleq** [comment]
What is the expected behavior then?

I'm not really acquainted with Vue, but if your data contains `<br data-cke-filler>`, then you're obtaining the contents of the [view instead of the model](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/architecture/intro.html#editing-engine). The view layer contains all sorts of quirks (like the filler) to make the editing possible in numerous cases in different browsers. The only right way to obtain the actual data of the editor is thorough `editor.getData()`.

Or am I missing something? If so, please extend your case with additional info.

**Comment by ZapevalovAnton** [comment]
In order:

1. Vue create element ```<div contenteditable="true" v-html="value"></div>``` with empty ```value```
2. ```v-html``` directive set ```value``` to contenteditable content
3. After create element in ```mounted``` method initialized ckeditor
4. Vue make ajax requests and change ```value``` via two-way data binding
5. But with enabled ckeditor, content of contenteditable element not changed

My English is not good, sorry. I understandably explained?

**Comment by ZapevalovAnton** [comment]
With disabled ckeditor or another editors (eg Quill.js) two-way data binding changed ```value```

**Comment by ZapevalovAnton** [comment]
Sorry, i am stupid. I watched like it's done in components for Quill.Js. They manually update this data in the ```watch``` method.

https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue
https://surmon-china.github.io/vue-quill-editor/

 I am use ```setData``` method of ckeditor for it, but my cursor always comes to the beginning.

**Comment by ZapevalovAnton** [comment]
Ha ha... I am fixed problem from previous comment. Thank you!)
