### ISSUE TITLE
Markdown docs crash on latest release branch

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7906]
## 📝 Provide detailed reproduction steps (if any)

1. On latest release branch go to docs `/features/markdown.html`

### ✔️ Expected result

Console is clear

### ❌ Actual result

Error:
```js
Uncaught TypeError: u.a.use is not a function
    at Module.<anonymous> (snippet.js:4)
    at n (snippet.js:4)
    at snippet.js:4
    at snippet.js:4
```

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
It looks like docs builder uses marked library in version `0.8` and does not load it from Markdown plugin dependencies.

```
λ jodator-GL75-9SE ckeditor5 → λ git release → cat node_modules/marked/package.json | grep \"version\"                    
  "version": "0.8.2",
λ jodator-GL75-9SE ckeditor5 → λ git release → cat packages/ckeditor5-markdown-gfm/node_modules/marked/package.json | grep \"version\"
  "version": "1.1.1",
```

**Comment by jodator** [comment]
Yep. I've force install Marked in version `1.1.1` in CKEditor5 main repo and the docs were built OK.

**Comment by jodator** [comment]
Docs are built correctly so...

1.  Add marked to ckeditor5's `package.json` in version `1.1.1` temporarily to unblock release process.
2.  Upgrade dependencies in dev packages.

**Comment by jodator** [comment]
I've pushed a fix to the `release` branch. It hinders the dependency management but this would require a proper fix.
