### ISSUE TITLE
Error thrown when creating a link on a non-collapsed selection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7907]
## 📝 Provide detailed reproduction steps (if any)

1.  Build docs for production.
2.  Visit http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/examples/builds/balloon-block-editor.html.
3.  Create a selection like in the screencast.
4.  Attempt to create a link.

![](https://user-images.githubusercontent.com/1099479/90891394-e6df3a00-e3bb-11ea-8a4a-13f1787e87f9.gif)

```
Uncaught TypeError: t.getCustomProperty(...) is not a function
    at ut.e.on.priority (snippet.js:4)
    at ut.fire (snippet.js:4)
    at ut.convertMarkerRemove (snippet.js:4)
    at ut.convertChanges (snippet.js:4)
    at snippet.js:4
    at nt.change (snippet.js:4)
    at Le.Bt.listenTo.priority (snippet.js:4)
    at Le.fire (snippet.js:4)
    at Le._handleChangeBlock (snippet.js:4)
    at cn._runPendingChanges (snippet.js:4)
i @ snippet.js:4
rethrowUnexpectedError @ snippet.js:4
fire @ snippet.js:4
convertMarkerRemove @ snippet.js:4
convertChanges @ snippet.js:4
(anonymous) @ snippet.js:4
change @ snippet.js:4
Bt.listenTo.priority @ snippet.js:4
fire @ snippet.js:4
_handleChangeBlock @ snippet.js:4
_runPendingChanges @ snippet.js:4
change @ snippet.js:4
_hideFakeVisualSelection @ snippet.js:4
_removeFormView @ snippet.js:4
_closeFormView @ snippet.js:4
(anonymous) @ snippet.js:4
fire @ snippet.js:4
t.listenTo.useCapture @ snippet.js:4
fire @ snippet.js:4
n @ snippet.js:4
```

## 📃 Other details

It's a regression introduced in v20.0.0.

*   Browser: Any
*   Any
*   CKEditor version: release (3928dab)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
It could be reproduced with any type of block elements. Simply start the selection at the end of a block.

![](https://user-images.githubusercontent.com/20988892/91040924-5d27aa80-e60f-11ea-86ad-9ccb7d9abccb.gif)
