### ISSUE TITLE
Production build with Laravel Mix error

### ISSUE THREAD

**Issue by ZapevalovAnton** [ckeditor/ckeditor5#791]
Bug report. ckeditor version "@ckeditor/ckeditor5-build-balloon": "^1.0.0-alpha.2".

After production build with laravel mix i am get error:

```javascript
app.js:1 Uncaught (in promise) ReferenceError: n is not defined
    at Eu.attachDomRoot (app.js:1)
    at Eu.createRoot (app.js:1)
    at Su.createRoot (app.js:1)
    at Xu.init (app.js:1)
    at r.initPlugins.then (app.js:1)
    at <anonymous>
```

With ```npm run watch``` all ok.

Code:

```javascript
<template>
  <div contenteditable="true" v-html="value"></div>
</template>

<script>
	
  import BalloonEditor from '@ckeditor/ckeditor5-build-balloon'

  export default {
    name:  'Editor',

    props: [
      'value'
    ],

    data () {

      return {
        editor: null
      }
    },

    mounted () {

      BalloonEditor
        .create(this.$el)
        .then((editor) => {

          this.editor = editor

          editor.document.on('change', (e, data) => {
            this.updateContent(editor.getData())
          })
        })
      },

    methods: {

      updateContent (content) {
        this.$emit('input', content);
      },
    },

  watch: {

    value (val) {

      if ((this.editor != null) && (val != this.editor.getData())) {
        this.editor.setData(val)
      }
    }
  }
}

</script>

<style lang="scss">

  ol { margin-left: 15px; }
  ul { margin-left: 20px; }

</style>
```

**Comment by Reinmar** [comment]
Hi! Are you sure that `this.$el` is defined when you pass it to `create()`?

**Comment by ZapevalovAnton** [comment]
I'm having trouble debugging. In the development mode, this problem does not occur. And after the code is minified, I can not understand anything.

**Comment by ZapevalovAnton** [comment]
Any ideas?

**Comment by jodator** [comment]
I'd try to enable sourcemap for `app.js` file it should help to debug it. You could also post you Laravel Mix configuration maybe that could help since it looks like some problem with JS minification.

**Comment by ZapevalovAnton** [comment]
Sourcemap with minified file?

Laravel Mix config file: 

```javascript
let mix     = require('laravel-mix');
let webpack = require('webpack');

mix
  /***** Settings *****/

  /* Applicaton Settings */

  .webpackConfig({

    plugins: [

      new webpack.ProvidePlugin({
        'jQuery': 'jquery',
        '$': 	  'jquery',
        'Prism':  'prismjs',
        'Popper': ['popper.js', 'default'],
        'Util':     'exports-loader?Util!bootstrap/js/dist/util',
        'Collapse': 'exports-loader?Util!bootstrap/js/dist/collapse',
        'Dropdown': 'exports-loader?Util!bootstrap/js/dist/dropdown'
      })
    ]
  })

  /* Monitor Settings */

  /* ---------------- */

  /* All Settings */

  .options({
      processCssUrls: false
  })

  .browserSync('tuhub.dev')

  /***** Application *****/

  .js('resources/assets/app/js/index.js', 'public/app/js/app.js')

  .sass('resources/assets/app/sass/_index.scss', 'public/app/css/app.css')

  /***** Monitor *****/

  .react('resources/assets/monitor/index.js', 'public/monitor/app.js');
```

**Comment by jodator** [comment]
@ZapevalovAnton yes - use that: https://laravel.com/docs/5.5/mix#css-source-maps. It will map minified code to source.

**Comment by ZapevalovAnton** [comment]
Element is defined BalloonEditor is not defined!)

![image](https://user-images.githubusercontent.com/6674242/35484921-67fdf966-0479-11e8-9a88-034770f25cd4.png)

**Comment by Reinmar** [comment]
You try to import the editor from `@ckeditor/ckeditor5-build-baloon`. The build there is in UMD format. So it works with CJS, AMD and globals, but the problem is with importing that by using the ES6 syntax. For that to work, something needs to unify all these formats. When you use webpack directly to build your app, this is webpack. But maybe in a Vue component it doesn't work for some reason?

**Comment by ZapevalovAnton** [comment]
I am clone ckeditor from https://github.com/ckeditor/ckeditor5-editor-balloon to my node_modules folder and change import path to ```import BalloonEditor from '@ckeditor/ckeditor5-build-balloon/src/ckeditor.js'```. It worked for me.

**Comment by Reinmar** [comment]
If this worked, then why's `BalloonEditor` undefined on the screenshot you posted above? Do you mean that all this worked after you cloned this repo instead of installing it through npm?

**Comment by ZapevalovAnton** [comment]
Yes!!!

**Comment by ZapevalovAnton** [comment]
I just now deleted the ```node_modules``` and reinstall all the packages. Now everything works as expected. WTF?!?!

**Comment by Reinmar** [comment]
Uh, I've just noticed that you imported this now:

```
import BalloonEditor from '@ckeditor/ckeditor5-build-balloon/src/ckeditor.js'
```

Yeah, that's the base for the balloon editor's build. And it's a ES6 module. Unlike the `build/ckeditor.js` file published on npm.

But anyway, I can see that it worked for you after reinstalling `node_modules`. `rm -rf node_modules` FTW :>!

**Comment by ZapevalovAnton** [comment]
Yes, everything works even with ```import BalloonEditor from '@ckeditor/ckeditor5-build-balloon``` after reinstall. Thanks.
