### ISSUE TITLE
CKEditor5: align left for table does not work

### ISSUE THREAD

**Issue by farshad-abb** [ckeditor/ckeditor5#7914]
align right and center  works properly for a selected table. but align left does not work !

**Comment by Mgsy** [comment]
Hi, thanks for the report. I'm not able to reproduce the issue, a table alignment seems to work fine:

![](https://user-images.githubusercontent.com/20988892/91015310-3bb4c780-e5eb-11ea-982b-7c981693e47d.png)

You can verify it in [our demo](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-and-cell-styling-tools). Can you share detailed steps to reproduce?

**Comment by FilipTokarski** [comment]
Closing due to lack of feedback.
