### ISSUE TITLE
Some images pasted from Word aren't correctly inserted when using Chrome

### ISSUE THREAD

**Issue by marcellofuschi** [ckeditor/ckeditor5#7915]
I tried to upload some images from a .doc file using Paste from Word. On Safari, it works ok. When using Chrome, though, the images don't get inserted correctly, but instead the following result is obtained:

<img width="437" alt="Screenshot" src="https://user-images.githubusercontent.com/20324786/90978336-70724180-e54d-11ea-9a7e-cf60054b282e.png">

The error message appearing in the console is: 
> Not allowed to load local resource: file:///(etc.)

The `src` attribute value of the inserted images is their local file path. On Safari, instead, they get uploaded correctly and the upload response URL is added as `src`.

Here is the sample .doc file I used for testing:
[Images.doc.zip](https://github.com/ckeditor/ckeditor5/files/5113934/Images.doc.zip)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I wasn't able to reproduce the issue with the file you provided, but I guess you are having a problem, that has already been reported and we're [tracking it here](https://github.com/ckeditor/ckeditor5/issues/2493). It would be very helpful for us if you could add there a comment with your Word version, CKEditor version and configuration, steps to reproduce and any other information that you find important. Meanwhile, I'll close this ticket as a duplicate.
