### ISSUE TITLE
[Edge] Editor reloads after inserting the list with autoformat (opened console issue)

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#792]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Open the console.
3. Create new paragraph.
4. Press <kbd>*</kbd>, then <kbd>Spacebar</kbd>.

## ✅ Expected result

Unordered list has been inserted.

## ❎ Actual result

Editor hangs and reloads.

## 📃 Other details that might be useful

**Notes**

- This bug is reproducible only with opened console.
- It's reproducible for ordered list, but editor hangs after inserting the ordered list for the second time.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/35441651-9b06c8a0-02a4-11e8-9162-bc0a99348157.gif)

**Other information**
OS: Windows 10
Browser: Edge

**Comment by Reinmar** [comment]
> This bug is reproducible only with an opened console.

OMG... Not again ;|

**Comment by Mgsy** [comment]
This issue isn't reproducible anymore.
