### ISSUE TITLE
Other feature guides should advertise the autoformatting feature.

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7924]
## 📝 Provide a description of requested docs changes

Despite being enabled in all editor builds, [this feature](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) may be hard to discover for the users. At the same time, we spent a lot of time implementing it and it is awesome (from the UX standpoint).

I suppose if we simply put `<info-boxes>` in other features' guides like ["Headings"](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html), ["Basic styles"](https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html), lists (essentially all features supported by the `Autoformat` plugin), this could help people learn about this nifty feature and make the editor feel smarter and more modern (at virtually no cost). The `<info-box>` could suggest using the token related to the feature (e.g. `#`, `*`, etc.) and link to "learn more" in the "Autoformatting" guide.

cc @AnnaTomanek @godai78

**Comment by godai78** [comment]
Working on it gradually within this scope: https://github.com/cksource/content-documentation-proofread/issues/332

**Comment by godai78** [comment]
Added so far to:

* Heading - https://github.com/ckeditor/ckeditor5/pull/8281
* Markdown output - https://github.com/ckeditor/ckeditor5/pull/8336

**Comment by godai78** [comment]
Looks like it's all ready.
