### ISSUE TITLE
Link balloon displayed in wrong place

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#7926]
## 📝 Provide detailed reproduction steps (if any)

1.  Create a link like this: `<$text linkHref="aaa">foo</$text><$text linkHref="aaa" bold="true">bar</$text>[]`
2.  Click the link toolbar button

### ✔️ Expected result

The link Baloon should appear close to the caret.

### ❌ Actual result

The link balloon appears in an incorrect place.

![](https://user-images.githubusercontent.com/1232187/91051503-83097b00-e620-11ea-9fab-5904caa513ac.png)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
What version was it introduced in? if this release it should be related to #7838 if v20 it's going to be #4721

**Comment by niegowski** [comment]
v20 was not affected

**Comment by niegowski** [comment]
I stumbled upon this issue in Safari@iOS but can also reproduce in Chrome@Mac

**Comment by niegowski** [comment]
I used this page http://localhost:8081/build/docs/ckeditor5/latest/features/link.html

**Comment by niegowski** [comment]
seems that there must be a bold at the end of the link and the caret just after the link.

**Comment by mlewand** [comment]
Still I'm unable to repro it on Win (which simply might be not affected). @ckeditor/qa-team can you check it on your end both win/mac?

Meanwhile here's the screencast from my attempt:

![](https://user-images.githubusercontent.com/5353898/91056273-0f6a6c80-e626-11ea-8d21-ad3db70473d7.gif)

**Comment by FilipTokarski** [comment]
I can reproduce this, can be either bold or italics at the end of the link. And it needs to be active when you place the cursor:  
  
![0_link1](https://user-images.githubusercontent.com/34380544/91056594-7851e480-e626-11ea-8a4b-1911a438fa6b.gif)
