### ISSUE TITLE
Creating a numbered list above an unordered list results with a unordered

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7932]
## 📝 Provide detailed reproduction steps (if any)

1.  Open [lists feature demo](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) for the upcoming v21 release (not not published yet, so production link won't work).
2.  Focus the editor under the "List styles" section.
3.  Put the selection in the "Ingredients required for making a coffee:" paragraph.
4.  Press "Numbered list" button.

### ✔️ Expected result

Should create a numbered list.

### ❌ Actual result

It makes unordered list instead.

![](https://user-images.githubusercontent.com/5353898/91058913-573ec300-e629-11ea-8354-c682aaeb6fff.png)

## 📃 Other details

It doesn't happen if there's no list styles demo.

*   Browser: Chrome (didn't check others, but my assumption is that it's a cross-browser thing)
*   OS: Windows
*   CKEditor version: v21.0.0
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
The bug is in the conversion:

![image.png](https://images.zenhubusercontent.com/5762b11cbf93871ccd9cb8a8/79556fc3-d8fb-4d13-8af9-25c957c09e42)
