### ISSUE TITLE
Docs should add RawElement as a valid element to insert

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#7933]
## 📝 Provide a description of requested docs changes
The documentation doesn't say it allows `RawElement` to be inserted using the `DowncastWriter`.

_What is the purpose and what should be changed?_
The following lines os JSDoc should include `RawElement` as a valid value, since it is the list of [valid nodes](https://github.com/ckeditor/ckeditor5/blob/3a4f65efa7898456d3100d370a649ec966b6b479/packages/ckeditor5-engine/src/view/downcastwriter.js#L1923).

https://github.com/ckeditor/ckeditor5/blob/3a4f65efa7898456d3100d370a649ec966b6b479/packages/ckeditor5-engine/src/view/downcastwriter.js#L655-L673

https://github.com/ckeditor/ckeditor5/blob/3a4f65efa7898456d3100d370a649ec966b6b479/packages/ckeditor5-engine/src/view/downcastwriter.js#L1887-L1898

https://github.com/ckeditor/ckeditor5/blob/3a4f65efa7898456d3100d370a649ec966b6b479/packages/ckeditor5-engine/src/view/downcastwriter.js#L1907-L1910

**Comment by jodator** [comment]
Thanks! Fixed by fb69520. Some things were already fixed but I've also removed the internal docs to have fewer docs to maintain.
