### ISSUE TITLE
Why is the toWidget only for container elements

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#7934]
## Provide a description of the task
Why has the toWidget functionality been limited to container elements? It used to work for AttributeElements also, which allowed the use os inline widgets with some styling.

_What steps should be taken to fulfill the task?_
Try to add an `AttributeElement` or a `RawElement` to the toWidget function. Before version 21.0.0 It would work. As of this version it doesn't work anymore.

## 📃 Other details

* Browser: Any
* OS: Any
* CKEditor version: Since version 21.0.0
* Installed CKEditor plugins: Any

**Comment by dkrahn** [comment]
Is there any reason for this behavior?

**Comment by jodator** [comment]
The main problem for this might be that different view elements have different purpose. The widget system, as for now, is prepared to handle blocks of content. Those usually resides directly in root (or in other block, but let's simplify that) alongside other content. This is true for images, tables, etc. Those elements have different requirements for handling than mentioned in your issue.

For instance, `AttributeElement` is treated as an inline, most likely a text attribute, which is not distinguishable from any other `AttributeElement` (in majority of cases). Attribute elements of the same/similar type might be merged together. Most notably is that `<strong>foo</strong><strong>bar</strong>` should be one: `<strong>foobar</strong>` and using `AttributeElement` allows to achieve that. Even though you'd create two instances of `AttributeElement` it will be merged in the data (in the default behavior, but it [can be changed](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-createAttributeElement)). You can think of this as "uncountable" entities (water, sand, wood) in opposite to concrete objects which are "countable" (chair, sand grain, tree).

In this terms `AttributeElement` is not suited for widgets in my opinion. We do have explored inline widgets but we do not have official plugin that use that. In other words it is not 100% supported and we have only [one approved pattern for this](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#defining-converters). In other words, we can't guarantee that other use-cases will work as we do not test them. If that worked it might be just a coincidence.

The other thing is with `RawElement` - it might be suitable for a widget. I didn't analyse how it is handled in the renderer so it might be either bug or a feature request to make `RawElement` widgetable.

**Comment by jodator** [comment]
The main problem for this might be that different view elements have different purpose. The widget system, as for now, is prepared to handle blocks of content. Those usually resides directly in root (or in other block, but let's simplify that) alongside other content. This is true for images, tables, etc. Those elements have different requirements for handling than mentioned in your issue.

For instance, `AttributeElement` is treated as an inline, most likely a text attribute, which is not distinguishable from any other `AttributeElement` (in majority of cases). Attribute elements of the same/similar type might be merged together. Most notably is that `<strong>foo</strong><strong>bar</strong>` should be one: `<strong>foobar</strong>` and using `AttributeElement` allows to achieve that. Even though you'd create two instances of `AttributeElement` it will be merged in the data (in the default behavior, but it [can be changed](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-createAttributeElement)). You can think of this as "uncountable" entities (water, sand, wood) in opposite to concrete objects which are "countable" (chair, sand grain, tree).

In this terms `AttributeElement` is not suited for widgets in my opinion. We do have explored inline widgets but we do not have official plugin that use that. In other words it is not 100% supported and we have only [one approved pattern for this](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#defining-converters). In other words, we can't guarantee that other use-cases will work as we do not test them. If that worked it might be just a coincidence.

The other thing is with `RawElement` - it might be suitable for a widget. I didn't analyse how it is handled in the renderer so it might be either bug or a feature request to make `RawElement` widgetable.

**Comment by dkrahn** [comment]
Thank you @jodator for the detailed explanation.

The CKEditor Team has done wonders with CKEditor5! What you all have achieved is really amazing!

If I may, I would suggest some tests with of `RawElement` with the `toWidget` function, as it seams to be a possible way the solve the issue #1633.
I will close this issue as you have answered my question.
Thanks again for your effort!
