### ISSUE TITLE
Incomplete link selection when link is at the end of line

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7936]
## 📝 Provide detailed reproduction steps (if any)

1. Create a link at the end of line
2. Using mouse, try to select link from end to start

### ✔️ Expected result

Link is fully selected

### ❌ Actual result

![0_link2](https://user-images.githubusercontent.com/34380544/91129001-8563e780-e6a9-11ea-8863-0f55281a946e.gif)  
  
![0_link3](https://user-images.githubusercontent.com/34380544/91129557-821d2b80-e6aa-11ea-9d06-052a2343480e.gif)

## 📃 Other details

* Browser: Chrome
* CKEditor version: since 20.0.0
* First bad commit: https://github.com/ckeditor/ckeditor5/commit/37c744a7faa0929c5633d4fa7bb5d7342d273076
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
I tried to reproduce this together with @Reinmar on chrome on mac / win and we're unable to. @Mgsy can you reproduce it?

**Comment by Mgsy** [comment]
I was able to reproduce it. However, it doesn't occur every time I try. I think this is an old issue and I was struggling with it before.

**Comment by Reinmar** [comment]
OK, I'm able to reproduce it as well. I think that the caret needs to be inside the link before you start making the selection. Also, it seemed to help to move the mouse cursor slowly.

**Comment by Reinmar** [comment]
This does not seem a high-priority issue as it's not leading to a crash and it's easy for the user to fix this manually. Plus, it does not happen too often.

**Comment by slotterbackW** [comment]
We have some users also reporting this issue. I took a look at it at it seems related to the presence of &NoBreak; characters in the DOM after the link. I took this screenrecording on the demo page which I hope will help. Thanks!

https://user-images.githubusercontent.com/14916556/124159078-f3123a00-da57-11eb-830f-3448366f7105.mp4

**Comment by Mgsy** [comment]
I can confirm that this issue still exists and is really easy to reproduce:

https://user-images.githubusercontent.com/20988892/124551908-1c094500-de33-11eb-8f83-c20ca8478b96.mp4

**Comment by Reinmar** [comment]
Probably a DUP of #8814.

**Comment by Reinmar** [comment]
Let's close this as a DUP of #8814.
