### ISSUE TITLE
tableProperties is different on Windows and MAC

### ISSUE THREAD

**Issue by jiangyanghe** [ckeditor/ckeditor5#7937]
## 📝 Provide detailed reproduction steps (if any)

1. … I can copy the backgroup-color of table on Mac, but can not copy on Window; My application is WPS;
2. … I can copy the propertype of height and width both of Mac and Windows in WPS
3. …

### ✔️ Expected result
 I can copy  any propertype on Mac of window'WPS

## 📃 Other details

* Browser: chrome
* OS: …
* CKEditor version: V5
* Installed CKEditor plugins: @ckeditor/ckeditor5-table

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Hi @jiangyanghe thanks for the report. We already have a request for supporting WPS. You can upvote it here: #2488.

For now, we do not have support for WPS office.
