### ISSUE TITLE
dropdown font-size can not choose when selection is a inline widget

### ISSUE THREAD

**Issue by minhlp** [ckeditor/ckeditor5#7942]
## 📝 Provide detailed reproduction steps 

1. I have a custom plugin like inline widget (see [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#the-model-and-the-view-layers))
2. I am using conversion like here
`  schema.extend('placeholder', {
        allowAttributes: ['fontSize']
    });
    conversion
        .attributeToAttribute({
            model: {
                name: 'placeholder',
                key: 'fontSize',
                values: ['tiny', 'small', 'big', 'huge']
            },
            view: {
                'tiny': {
                    key: 'class',
                    value: 'text-tiny'
                },
                'small': {
                    key: 'class',
                    value: 'text-small'
                },
                'big': {
                    key: 'class',
                    value: 'text-big'
                },
                'huge': {
                    key: 'class',
                    value: 'text-huge'
                }
            },
            converterPriority: 'high'
        });

    conversion.for('upcast')
        .attributeToAttribute({
            view: {
                key: 'class',
                value: /text-[\s\S]+/
            },
            model: {
                key: 'fontSize',
                value: viewElement => {
                    const regexp = /text-([\s\S]+)/;
                    const match = viewElement.getAttribute('class').match(regexp);
                    if (!match) {
                        return null;
                    }
                    return match[1];
                }
            }
        });`
3. I select a placeholder, click dropdown to choose font-size 

### ✔️ Expected result

the placeholder's font-size is selected 

### ❌ Actual result

the placeholder's font-size isn't selected 

## 📃 Other details

* Browser:Chrome Version 84.0.4147.135 
* OS: MacOS
* CKEditor version:21.0.0
* Installed CKEditor plugins:"@ckeditor/ckeditor5-font": "^21.0.0",

---

**Comment by Mgsy** [comment]
Hi! Currently, we don't support styling inline widgets. We track this feature request [here](https://github.com/ckeditor/ckeditor5/issues/1633), so feel free to add :+1:  to the first post and join the discussion to bump its popularity.
