### ISSUE TITLE
'ck-balloon-panel' is showing outside of 'editable-container' when scrolling

### ISSUE THREAD

**Issue by kaluginserg** [ckeditor/ckeditor5#7943]
## 📝 Provide detailed reproduction steps (if any)

1. Open editor with img or table (it needs just for showing balloon toolbar).
2. Click to any object that provide balloon toolbar.
3. Scroll down
![2020-08-26_11-52-55 (1)](https://user-images.githubusercontent.com/6398891/91283742-a86ac600-e793-11ea-8881-c0a8f8e1453c.gif)

### ✔️ Expected result

Balloon toolbar must disappear outside of editable-container OR must stick inside of editable-container close to border.

### ❌ Actual result

Balloon toolbar is showing outside of editable-container.

## 📃 Other details

* Browser: Chrome 84
* OS: MacOs
* CKEditor version: 18-21

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, thanks for the report. We're aware of this issue and tracking it here - #5328. I'm closing it as a duplicate.

**Comment by twoshlove** [comment]
Temporarily fixed this problem so that it doesn't look like a bug.

this.elements.editorWrapper = document.querySelector('.ck-content');
this.elements.editorWrapper.addEventListener('wheel', (e) => {
     e.target.blur();
});
