### ISSUE TITLE
removeFromToolbar in config

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#7945]
I have custom build with all tools and buttons that I need. But In some cases I don't want `link` button to be shown. I need option `removeFromToolbar` for that. Otherwise I have to rewrite my whole `toolbar` config, which can change in time.

BTW. I think that option `removePlugins` is not working. I'm adding 
```
removePlugins: [
   'Bold'
],
```
and `bold` is working as always. But still (as in docs) `removePlugins` does not remove corresponding buttons.

**Comment by Reinmar** [comment]
Interesting proposal. I stumbled upon this problem many times too.

**Comment by Reinmar** [comment]
Expected usage:

```js
ClassicEditor.create( {
	toolbar: {
		removeItems: [ 'bold' ]
	}
} )
```

**Comment by Reinmar** [comment]
Edge case: there were `|` used like this:

```js
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'bulletedList',
			'numberedList',
			'|',
			'indent',
			'outdent',
			'|',
			'imageUpload',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'undo',
			'redo'
		]
	},
```

And you defined `removeItems: [ 'indent', 'outdent' ]` so after that you'd end up with two separators next to each other.

Perhaps we can relatively easily normalize this.

It seems that all this code can be put in `ToolbarView.fillFromConfig`.

**Comment by maxbarnas** [comment]
Since `ToolbarView.fillFromConfig` accepts `items` directly, and not the entire `toolbar` config, I have to change both the `fillFromConfig` signature and calls in the following packages:

*   `ui`,
*   `widget`,
*   `internal`,
*   and editor bundles.

**Comment by maxbarnas** [comment]
We decided to move forward with the change. `ToolbarView.fillFromConfig` will handle both an array and object passed as parameters. In the first case, it will behave the same way as now, in the latter, it will treat the object as the entire toolbar config instead of just `items`.

CC @oleq
