### ISSUE TITLE
AutoComplete does not detect characters entered via ALT+ char code

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor5#7946]
When invoking the AutoComplete component, if a user enters a character using the ALT + character code key combination, the AutoComplete component does not detect that the text has changed.  For example, if we are using the Mentions component which utilizes the AutoComplete component and search for the name @Sébastian, then we cannot find the name searching for @S + ALT + 0233.

**Comment by Mgsy** [comment]
@FilipTokarski, could you verify this behaviour?

**Comment by FilipTokarski** [comment]
I was able to properly add a mention ( tried in Chrome, Edge and Firefox ):  
  
![0_mentions1](https://user-images.githubusercontent.com/34380544/91703405-69b18300-eb7a-11ea-96de-74c3eeb32d18.gif)

**Comment by Mgsy** [comment]
Thanks, @FilipTokarski. 

@jbalinski, can you provide the detailed steps to reproduce the problem and tell us more about your setup?

**Comment by FilipTokarski** [comment]
Closing due to lack of feedback.
