### ISSUE TITLE
Every new line will show the extra first letter of Chinese character

### ISSUE THREAD

**Issue by mooory** [ckeditor/ckeditor5#795]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. use ckeditor5 in in react
2. setting language for 'zh-cn'
3. type Chinese character in every new line
4. ckeditor5 showed the extra first letter of character

## ✅ Expected result
not show this letter
## 📃 Other details that might be useful
This situation only  hanppened when i type the first character in a new line.
And it happened in Chrome and not happened in Firefox Browser.

![image](https://user-images.githubusercontent.com/26402598/35545235-1374f74c-05a9-11e8-8c30-a574a37d8342.png)
![image](https://user-images.githubusercontent.com/26402598/35545258-31d565aa-05a9-11e8-9bd8-9eee9f271a35.png)

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/777. IME is not yet well supported in CKEditor 5, unfortunately.

**Comment by Reinmar** [comment]
Oops, sorry. This is a DUP of https://github.com/ckeditor/ckeditor5/issues/748, not https://github.com/ckeditor/ckeditor5/issues/777. I updated my previous comment.
