### ISSUE TITLE
"Implementing an inline widget" tutorial using outdated writer API

### ISSUE THREAD

**Issue by markanye** [ckeditor/ckeditor5#7961]
Related to #7910, the documentation for [Implementing an inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html) needs to be updated.

**Comment by Mgsy** [comment]
Hi! Thanks for the report, the documentation has been updated, however, it's not published yet. We'll update the live docs soon. I'll let you know when it will be done.

**Comment by markanye** [comment]
Thanks @Mgsy !

**Comment by mlewand** [comment]
And the docs are out 🎉 Thanks for noting this @markanye!
