### ISSUE TITLE
Font family and size with supportAllValues does not load 

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#7965]
## 📝 Provide detailed reproduction steps (if any)

1. Go to online document demo;
2. From console paste
```
editors[0].setData('<figure class="table"><table><tbody><tr><td><span style="font-family:Arial, Helvetica, sans-serif;font-size:11px;">Font Arial 11</span></td></tr></tbody></table></figure>')
```
3. Check the applied font.

### ✔️ Expected result

Should show a table with content Font Arial 11 in Arial font and size 11px

### ❌ Actual result

Shows a table with content Font Arial 11 with no font styles applied

## 📃 Other details

Apparently changing the `upcast` conversion to `elementToAttribute` instead of `attributeToAttribute` in the `_prepareAnyValueConverters` resolves the problem.
But I am not sure if this is the correct way to solve it.

* Browser: Chrome
* OS: Windows
* CKEditor version: 21.0.0
* Installed CKEditor plugins: Default

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I can confirm this.
When I remove `supportAllValues: true` everything seems to be fine.

**Comment by dkrahn** [comment]
Any plans to fix this?
