### ISSUE TITLE
 Is there a way to change the button layout to pie menu ?

### ISSUE THREAD

**Issue by steveyang331** [ckeditor/ckeditor5#7968]
## 📃 Other details

* Browser: … Chrome 
* OS: …Win
* CKEditor version: … latest
* Installed CKEditor plugins: …latest

---
 Is there a way to change the button layout to pie menu ?

![image](https://user-images.githubusercontent.com/16850883/91626927-cfb8d180-e9e5-11ea-94b4-51d3ba00f8c1.png)

Thanks.

**Comment by Mgsy** [comment]
Hi, CKEditor 5 doesn't offer different button layouts, however, it's possible to create a custom UI, which might be a solution for your use case. Please, see our [Third-party UI guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/external-ui.html) which should be a good starting point for further customization.
