### ISSUE TITLE
Incorrect selection when the image is inside the block quote

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#797]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the sample with Easy Image and block quote plugins.
2. Upload the image at the beginning of the document.
3. Apply the block quote.
4. Transform the image into the `side image`.
5. Start the selection inside this block quote and move outside of it.

## ✅ Expected result

Content below the block quote is selected.

## ❎ Actual result

Selection blinks, content isn't selected properly.

## 📃 Other details that might be useful

**Notes**

Result may be slightly different on each browser, but still the selection is incorrect.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/35557635-fc853414-05a5-11e8-857c-793ccedb788c.gif)

**Other information**
OS: All platforms
Browser: All browsers

**Comment by Reinmar** [comment]
It works better now.
