### ISSUE TITLE
Custom build from online builder doesn't have insertImageViaUrl

### ISSUE THREAD

**Issue by dzpt** [ckeditor/ckeditor5#7971]
## 📝 Provide detailed reproduction steps (if any)

1. Go to custom build
2. Select all image plugins
3. Build and use

### ✔️ Expected result

Have `insertImageViaUrl`

### ❌ Actual result

Doesn't have `insertImageViaUrl`

## 📃 Other details

* Browser: Version 84.0.4147.135 (Official Build) (64-bit)
* OS: macOS Catalina 10.15.2
* CKEditor version: …
* Installed CKEditor plugins: all

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, to make `insertImageViaUrl` work, you need to add it in the editor configuration, please [see the docs](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#inserting-images-via-source-url). Also, please keep in mind that it is available since version 22 ( latest ).

**Comment by dzpt** [comment]
@FilipTokarski I know, i mean the online builder page https://ckeditor.com/ckeditor-5/online-builder/ is still using v21.
Atleast we should clarify to user to know what version is using to build.

**Comment by Mgsy** [comment]
Hi! The online builder isn't updated yet, however, we'll be releasing it soon. It should be live today, I'll let you know!

**Comment by Mgsy** [comment]
@dzpt, good news! The online builder with updated dependencies is live. Have fun with CKEditor 5!
