### ISSUE TITLE
Link decorators are lost after initialization if LinkImage plugin is enabled

### ISSUE THREAD

**Issue by AnnaSoledat** [ckeditor/ckeditor5#7975]
## 📝 Provide detailed reproduction steps (if any)
I have link decorators in config
```
link: {
    decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Открыть в новом окне',
            defaultValue: true,
            attributes: {
                target: '_blank'
            }
        },
        likeAButton: {
            mode: 'manual',
            label: 'Кнопка',
            defaultValue: false,
            attributes: {
                class: 'likeAButton',
            }
        }
    }
}
```
I add links with decorators on and save data. Then I open this data again, and the decorators seem off. And if I output data it hasn't decorators.

### ✔️ Expected result

Decorators should be turn on.

### ❌ Actual result

Decorators turned off.

UPD: I add `converterPriority: 'high'` to upcast conversion for manual decorators in linkediting.js and now it seems to work fine.

**Comment by Mgsy** [comment]
Hi, thanks for the report! Could you please provide exact steps to reproduce the issue, including information about HTML which is saved and the one which is loaded to your editor?

**Comment by AnnaSoledat** [comment]
Hi! I tried to reproduce it on the clear classic build, and as soon as I add the LinkImage plugin I can see that bug. I add to the config manual decorators and use to check HTML like `<p>This is an instance of the <a target="_blank" href="https://ckeditor.com/docs/ckeditor5/latest/builds/guides/overview.html#classic-editor">classic editor build</a>.</p>`.

**Comment by FilipTokarski** [comment]
I added the link decorator configuration ☝️  and here are my results:
- just adding a link with decorators seems to work fine  
  
![link1](https://user-images.githubusercontent.com/34380544/91861985-b45ff780-ec6d-11ea-9a21-79f538647995.png)
  
- having the link already in html file, after initialisation decorators are off ( but adding them by hand works ok )
  
![link2](https://user-images.githubusercontent.com/34380544/91862155-e2ddd280-ec6d-11ea-8070-33435180e881.png)

- if I remove `linkImage` plugin, it initialises with decorators on

**Comment by blaisefonseca** [comment]
I have similar issue but in my case, I get below error when LinkImage plugin is enabled.
```
CKEditorError: view-writer-invalid-range-container: The container of the given range is invalid. 
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-writer-invalid-range-container

    at Fo (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:93766)
    at So.wrap (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:86672)
    at Vr.n.on.priority (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:183129)
    at Vr.fire (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:26402)
    at Vr._testAndFire (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:167283)
    at Vr.convertInsert (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:164591)
    at Ea.toView (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:214320)
    at Ea.stringify (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:214050)
    at Ea.get (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:214004)
    at Z_.getData (http://localhost:2012/app/libs/ckeditor-22/build/ckeditor.js?v=UNKNOWN:5:281197)
```
LinkDecorators:
```
link: {
	decorators: {
		toggleDownloadable: {
			mode: 'manual',
			label: 'Downloadable',
			attributes: {
				download: 'file'
			}
		},
		openInNewTab: {
			mode: 'manual',
			label: 'Open in a new tab',
			attributes: {
				target: '_blank',
				rel: 'noopener noreferrer '
			}
		}
	}
},
```
HTML
```
<p style="margin-left:0cm;text-align:justify;">test para:</p>
<ul>
    <li style="text-align:justify;">
        <a href="https://test.com/fdsf" target="_blank" rel="noopener noreferrer">link1</a>
    </li>
    <li style="text-align:justify;">
        <a href="https://test.com/fdsf" target="_blank" rel="noopener noreferrer">link 2</a>
    </li>
    <li style="text-align:justify;">
        <a href="https://test.com/fdsf" target="_blank" rel="noopener noreferrer">link 3</a>
    </li>
</ul>
```

**Comment by pomek** [comment]
I reproduced the issue.

The problem occurs because the converter for linked images is also parsing links without images.

See:
https://github.com/ckeditor/ckeditor5/blob/2f2de9d4ad89c81807018606c29ad1b5b10f3c6c/packages/ckeditor5-link/src/linkimageediting.js#L250-L251

After adding a check, whether an image is inside a link, everything works fine.
