### ISSUE TITLE
The indentation bug

### ISSUE THREAD

**Issue by huangxok** [ckeditor/ckeditor5#7982]
## 📝 Provide detailed reproduction steps (if any)
I am sorry to paste so many code （including comment ）
I use ckeditor5 by react  
error is here
“import Indent from '@ckeditor/ckeditor5-indent/src/indent'; // here is question“

1. code as follow： 
import React from 'react';
import CKEditor from '@ckeditor/ckeditor5-react';
// import InlineEditor from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';
import InlineEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
// import './translate/zh-cn.js';
// import CKEditorInspector from '@ckeditor/ckeditor5-inspector';
// official plugins
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import UnderLine from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Undo from '@ckeditor/ckeditor5-undo/src/undo';
import Font from '@ckeditor/ckeditor5-font/src/font';
import Indent from '@ckeditor/ckeditor5-indent/src/indent'; // here is question

// import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
// import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';

// import Table from '@ckeditor/ckeditor5-table/src/table';
// import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
// import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
// import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';

// import FileRepository from '@ckeditor/ckeditor5-upload/src/filerepository';
// import Image from '@ckeditor/ckeditor5-image/src/image';
// import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
// import Base64UploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/base64uploadadapter';
// import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
// import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
// import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
// import ImageSize from '@ckeditor/ckeditor5-image/src/imageresize';
// import UploadFile from './ckuploadfile/uploadfile';

// custom plugins
// import Emphasis from './ckeditor/emphasis';
// import Wavy from './ckeditor/wavy';
// import TextMathbf from './ckeditor/textmathbf';
// import TextMathrm from './ckeditor/textmathrm';
// import TextBrackets from './ckeditor/textbrackets';
// import TextInlineEquation from './ckeditor/textinlineequation';
// import TextBlockEquation from './ckeditor/textblockequation';
// import TextSplit from './ckeditor/textsplit';
// import TextCases from './ckeditor/textcases';
// import TextBecause from './ckeditor/textbecause';
// import TextTherefore from './ckeditor/texttherefore';
// import Vowel from './ckeditor/vowel';
// import CircleNumber from './ckeditor/circlenumber';
// import Circlenumberlimit from './ckeditor/circlenumberlimit';

const customColorPalette = [
    {
        color: 'hsl(4, 90%, 58%)',
        label: 'Red',
    },
    {
        color: 'hsl(340, 82%, 52%)',
        label: 'Pink',
    },
    {
        color: 'hsl(291, 64%, 42%)',
        label: 'Purple',
    },
    {
        color: 'hsl(262, 52%, 47%)',
        label: 'Deep Purple',
    },
    {
        color: 'hsl(231, 48%, 48%)',
        label: 'Indigo',
    },
    {
        color: 'hsl(207, 90%, 54%)',
        label: 'Blue',
    },
];

const fontColor = [
    {
        color: '#000000',
        label: 'Black',
    },
    {
        color: '#333333',
        label: 'Dim grey',
    },
    {
        color: '#666666',
        label: 'Grey',
    },
    {
        color: '#999999',
        label: 'Light grey',
    },
    {
        color: '#cccccc',
        label: 'little grey',
    },
    {
        color: '#ffffff',
        label: 'White',
        hasBorder: true,
    },
    {
        color: '#61a951',
        label: 'Light green',
    },
    {
        color: '#16a085',
        label: 'Dim green',
    },
    {
        color: '#07a9fe',
        label: 'Light blue',
    },
    {
        color: '#003ba5',
        label: 'Dim blue',
    },
    {
        color: '#8e44ad',
        label: 'Purpse',
    },
    {
        color: '#f32784',
        label: 'Pink',
    },
    {
        color: '#c0392b',
        label: 'Brown',
    },
    {
        color: '#d35400',
        label: 'Light Brown',
    },
    {
        color: '#f39c12',
        label: 'Dim yellow',
    },
    {
        color: '#fdda00',
        label: 'Yellow',
    },
];

const editoConfig = {
    language: 'zh-cn',
    plugins: [
        Paragraph,
        Essentials,
        Bold,
        Italic,
        UnderLine,
        Strikethrough,
        Undo,
        Font,
        // Image,
        // ImageUpload,
        // ImageToolbar,
        // ImageCaption,
        // ImageStyle,
        // ImageSize,
        // FileRepository, //需要服务器
        // Base64UploadAdapter, // 图片适配器
        // Table,
        // TableToolbar,
        // TableProperties,
        // TableCellProperties,
        // Highlight,

        // RemoveFormat,
        // Emphasis,
        // Wavy,
        // TextMathbf,
        // TextMathrm,
        // TextBrackets,
        // TextInlineEquation,
        // TextBlockEquation,
        // TextSplit,
        // TextCases,
        // TextBecause,
        // TextTherefore,
        // Vowel,
        // CircleNumber,
        // Circlenumberlimit,
    ],
    // extraPlugins: [UploadFile],
    // table: {
    //     contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'],
    // },
    // tableProperties: {
    //     borderColors: customColorPalette,
    //     backgroundColors: customColorPalette,
    // },
    // image: {
    //     toolbar: ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight', 'imageStyle:side'],
    //     styles: [
    //         // This option is equal to a situation where no style is applied.
    //         'full',
    //         'side',

    //         // This represents an image aligned to the left.
    //         'alignLeft',

    //         // This represents an image aligned to the right.
    //         'alignRight',
    //     ],
    //     resizeUnit: 'px',
    // },
    // fontFamily: {
    //     options: ['default', 'Ubuntu, Arial, sans-serif', 'Ubuntu Mono, Courier New, Courier, monospace'],
    //     supportAllValues: true,
    // },
    // fontColor: {
    //     colors: fontColor,
    //     columns: 4,
    //     // documentColors: 12,
    // },
    // fontBackgroundColor: {
    //     colors: fontColor,
    //     columns: 4,
    //     // documentColors: 12,
    // },
    // fontSize: {
    //     options: [9, 12, 14, 16, 18, 20, 24, 36, 48],
    //     supportAllValues: true,
    // },
    // toolbar: {
    //     items: [
    //         'undo',
    //         'redo',
    //         '|',
    //         'imageupload',
    //         'bold',
    //         'fontColor',
    //         'fontBackgroundColor',
    //         'fontSize',
    //         // 'emphasis',
    //         // 'wavy',
    //         // 'underline',
    //         // 'insertTable',
    //         // 'MathbfText',
    //         // 'MathrmText',
    //         // 'BracketsText',
    //         // 'InlineEquationText',
    //         // 'BlockEquationText',
    //         // 'SplitText',
    //         // 'CasesText',
    //         // 'BecauseText',
    //         // 'ThereforeText',
    //         // 'Vowel',
    //         // 'CircleNumber',
    //         // 'Circlenumberlimit',
    //     ],
    //     shouldGroupWhenFull: true,
    // },
    // highlight: {
    //     options: [
    //         {
    //             model: 'greenMarker',
    //             class: 'marker-green',
    //             title: 'Green marker',
    //             color: 'rgb(25, 156, 25)',
    //             type: 'marker',
    //         },
    //         {
    //             model: 'yellowMarker',
    //             class: 'marker-yellow',
    //             title: 'Yellow marker',
    //             color: '#cac407',
    //             type: 'marker',
    //         },
    //         {
    //             model: 'redPen',
    //             class: 'pen-red',
    //             title: 'Red pen',
    //             color: 'hsl(343, 82%, 58%)',
    //             type: 'pen',
    //         },
    //     ],
    // },
    // vowel: {
    //     options: [
    //         'a',
    //         'ā',
    //         'á',
    //         'ǎ',
    //         'à',
    //         'u',
    //         'ū',
    //         'ú',
    //         'ǔ',
    //         'ù',
    //         'ü',
    //         'ǖ',
    //         'ǘ',
    //         'ǚ',
    //         'ǜ',
    //         'e',
    //         'ē',
    //         'é',
    //         'ě',
    //         'è',
    //         'i',
    //         'ī',
    //         'í',
    //         'ǐ',
    //         'ì',
    //         'o',
    //         'ō',
    //         'ó',
    //         'ǒ',
    //         'ò',
    //     ],
    // },
};

class App extends React.Component {
    state = {
        editorValue: 'd',
        count: 1,
    };
    render() {
        const { editorValue, count } = this.state;
        let list = [];
        for (var i = 0; i < count; i++) {
            list.push(i);
        }
        return (
            <-div className='App'>
                {list.map((item,index) => {
                    return (
                        <CKEditor
                            key={index}
                            editor={InlineEditor}
                            config={editoConfig}
                            data={editorValue}
                            onInit={editor => {
                                // You can store the "editor" and use when it is needed.
                                console.log('Editor is ready to use!', editor);
                                console.log(editor.editing.view.document.isFocused);
                                // CKEditorInspector.attach(editor);
                            }}
                            onChange={(event, editor) => {
                                const data = editor.getData();
                                this.setState({ value: data });
                                console.log({ event, editor, data });
                            }}
                            onBlur={(event, editor) => {
                                console.log('Blur.', editor);
                            }}
                            onFocus={(event, editor) => {
                                console.log('Focus.', editor);
                            }}
                        />
                    );
                })}
            <-/div>
        );
    }
}

export default App;

this is a react project， I wanna a demo to learn about the ckeditor5‘s feature，and there is a bug。

### ✔️ Expected result

it works normally

### ❌ Actual result

An error has occurred！
CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

## 📃 Other details

* Browser: chrome 85
* OS: MAC OS catalina 10.15.6
* CKEditor version: @ckeditor/ckeditor5-editor-classic  ^19.0.0
* Installed CKEditor plugins: 
all plugins
    "@ckeditor/ckeditor5-basic-styles": "^19.0.0",
    "@ckeditor/ckeditor5-build-inline": "^19.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^13.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^19.0.0",
    "@ckeditor/ckeditor5-editor-inline": "^19.0.0",
    "@ckeditor/ckeditor5-engine": "^19.0.0",
    "@ckeditor/ckeditor5-essentials": "^19.0.0",
    "@ckeditor/ckeditor5-font": "^19.0.0",
    "@ckeditor/ckeditor5-heading": "^19.0.0",
    "@ckeditor/ckeditor5-highlight": "^19.0.0",
    "@ckeditor/ckeditor5-image": "^19.0.0",
    "@ckeditor/ckeditor5-indent": "^22.0.0",
    "@ckeditor/ckeditor5-link": "^19.0.0",
    "@ckeditor/ckeditor5-paragraph": "^19.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^19.0.0",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-table": "^19.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^19.0.0",
    "@ckeditor/ckeditor5-ui": "^19.0.0",
    "@ckeditor/ckeditor5-undo": "^19.0.0",
    "@ckeditor/ckeditor5-upload": "^19.0.0",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, I see that most of your CKEditor plugins are version 19 but `indent` is 22. 
As you can see in [error message docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules), one of the reasons for this error is `conflicting version of dependencies`, which most probably is the case here. Please make sure that all of your CKEditor plugins have the same version. In this case you can just change `indent` to 19, or update everything to the newest version ( which is recommended ). To easily update your dependencies, you can use tool like [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

**Comment by huangxok** [comment]
thanks a lot!
