### ISSUE TITLE
Extract linting packages to a separate repositories

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7985]
Originally reported here: https://github.com/ckeditor/ckeditor5/issues/7224

Basically three linter packages should be moved to separate repositories:

- eslint-config-ckeditor5
- eslint-plugin-ckeditor5-rules
- stylelint-config-ckeditor5

After unifying the versioning policy for released packages, each time when you generate a changelog, it contains a few entries that must be removed manually.

If somebody does not know about that, those packages will be bumped from version 1.0.0 to 23.0.0.

**Comment by mlewand** [comment]
We decided that we're going to make a separate repo for each package (and extract them from ckeditor5-dev repo).

**Comment by pomek** [comment]
Don't forget about disabling the "Issues" tab in new repositories.

**Comment by mlewand** [comment]
Repositories created:

*   https://github.com/ckeditor/eslint-config-ckeditor5
*   https://github.com/ckeditor/eslint-plugin-ckeditor5-rules
*   https://github.com/ckeditor/stylelint-config-ckeditor5

I also disabled the "Projects" tab :stuck\_out\_tongue\_winking\_eye:

**Comment by pomek** [comment]
Since https://github.com/ckeditor/eslint-config-ckeditor5 contains some tests, we can introduce Travis for that repository.

**Comment by pomek** [comment]
CI: https://travis-ci.org/ckeditor/eslint-plugin-ckeditor5-rules

I guess everything is done.
