### ISSUE TITLE
[Chrome/Safari] Selection blinks after pressing Ctrl + Shift + Arrow up when the caret is in the caption

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#799]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret in the caption.
3. Press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>Arrow up</kbd>/<kbd>Home</kbd>.

## ✅ Expected result

Selection doesn't blink.

## ❎ Actual result

Selection blinks and moves to the beginning of the caption.

## 📃 Other details that might be useful

**Notes**

It doesn't occur in Firefox and Edge. In these browsers, only caption gets selected.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/35568002-728a3bd4-05c7-11e8-80de-c5ba82e05fea.gif)

**Other information**

OS: All platforms
Browser: Chrome/Safari

**Comment by Reinmar** [comment]
In general, it shouldn't be possible to make a selection which starts in a nested editable and reaches out of it. Engine needs to fix such cases and also potentially prevent them.

**Comment by Reinmar** [comment]
Works fine now.
