### ISSUE TITLE
Unresponsive editor after adding a link with target="_blank" in a specific way

### ISSUE THREAD

**Issue by bananablues** [ckeditor/ckeditor5#7991]
## 📝 Provide detailed reproduction steps (if any)

1. add in ckeditor config file:
```
link: {
    decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Open in a new tab',
            attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
             }
         }
     }
},
```
2. insert in editor a list with two list-items (ul or ol)
3. add in first list-item a normal link (without target="_blank")
4. add in second list-item a link with target="_blank"
5. save

### ✔️ Expected result

Open Editor again and edit.

### ❌ Actual result

Editor is empty and not editable.

## 📃 Other details

* Browser: Firefox, Chrome
* OS: mac OS Mojave
* CKEditor version: build-classic 21.0.0 and 22.0.0
* Installed CKEditor plugins: CodeBlock and Highlight

**Comment by Mgsy** [comment]
Hi, thanks for the report. I can't reproduce your issue. Could you please share HTML which is returned by `editor.getData()` before saving the data and after loading it to the editor? Do you have any error in the console?

Also, it would be great if you could record a short screencast showing the problem.

**Comment by bananablues** [comment]
editor.getData(), before saving:
```
<ul><li><a href="/support.html">normal link</a></li><li><a href="https://www.gogle.ch" target="_blank" rel="noopener noreferrer">link with target:blank</a></li></ul>
```

editor.getData(), after loading to the editor:
```
Uncaught ReferenceError: editor is not defined
    at <anonymous>:1:1
```
Error message in console:
```
ckeditor5-config.js?v=1:132 CKEditorError: view-writer-invalid-range-container
    at Vn (../ckeditor5-build-classic/build/ckeditor.js:5:201714)
    at En.wrap (../ckeditor5-build-classic/build/ckeditor.js:5:194756)
    at Ns.i.on.priority (../ckeditor5-build-classic/build/ckeditor.js:5:290547)
    at Ns.fire (../ckeditor5-build-classic/build/ckeditor.js:5:134790)
    at Ns._testAndFire (../ckeditor5-build-classic/build/ckeditor.js:5:274712)
    at Ns.convertInsert (../ckeditor5-build-classic/build/ckeditor.js:5:272020)
    at Ns.convertChanges (../ckeditor5-build-classic/build/ckeditor.js:5:271195)
    at ../ckeditor5-build-classic/build/ckeditor.js:5:302476
    at ps.change (../ckeditor5-build-classic/build/ckeditor.js:5:241242)
    at lc.listenTo.priority (../ckeditor5-build-classic/build/ckeditor.js:5:302441)
```
My solution so far:
```
link: {
    addTargetToExternalLinks: true
},
```
...without above mentioned problem.

**Comment by Mgsy** [comment]
I've checked your HTML and I'm still unable to reproduce the problem. I've used your HTML

```
<ul><li><a href="/support.html">normal link</a></li><li><a href="https://www.gogle.ch" target="_blank" rel="noopener noreferrer">link with target:blank</a></li></ul>
```

and tried to load it to the editor on initialization and also simply using (`editor.setData( editor.setData ) )`). Both cases result in proper content loading.

Maybe there is some additional steps/configuration required?

**Comment by itarcontact** [comment]
Hello. I am reporting the same problem.
When links are included in the list `<ul>` or `<ol>` and given an attribute, e.g. `target="_ blank"` the ckeditor crashes.

![image](https://user-images.githubusercontent.com/55651445/163154505-341364d6-4b03-4004-b406-39daf4d77f7e.png)

![image](https://user-images.githubusercontent.com/55651445/163153863-1140a1b2-7b9a-4ddc-b88a-e02fc0cf340e.png)

![image](https://user-images.githubusercontent.com/55651445/163154219-24041e87-a501-41a8-a842-8aa20feb092e.png)


Links in a list with no attributes works fine.

![image](https://user-images.githubusercontent.com/55651445/163153565-31c5cc5b-a095-4eb8-9f21-2bb185f7736b.png)
