### ISSUE TITLE
Implement the beforeInput support detection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7995]
## 📝 Provide a description of the new feature

The event is supported in all major web browsers [except Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=970802) ([still an experimental feature behind a flag](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features)). This means for the time being both `beforeInput` and mutation typing will need to exist next to each other. And even after Firefox enables the feature, it will take some time for people to update their browsers (which is slow in corporate environments).

This is why `isBeforeInputSupported = !env.isGecko` does not make sense. We need a feature discovery similar to [the one described on the React issue tracker](https://github.com/facebook/react/issues/11211#issuecomment-355866473) instead.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
facebook/react#11211 and confirmation in https://stackoverflow.com/questions/49927038/how-to-feature-detect-input-events-level-1-or-2-support

**Comment by oleq** [comment]
Closed in #8021.
