### ISSUE TITLE
Updating chai with benderjs-chai

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#80]
We've noticed that we are using an old version of [Chai](http://chaijs.com/) when testing with Bender.js: `~1.10.0`. There is a new [benderjs-chai](https://github.com/benderjs/benderjs-chai) version available on [npm](https://www.npmjs.com/package/benderjs-chai) that uses Chai in version `~3.2.0`. We should update `benderjs-chai`. This will also require some changes in our tests since function-style assertions are [no longer supported](https://github.com/chaijs/chai/issues/371).

**Comment by Reinmar** [comment]
This issue is blocked by https://github.com/benderjs/benderjs-chai/issues/2.

**Comment by Reinmar** [comment]
Not applicable after we dropped Bender.
