### ISSUE TITLE
Is it possible to convert image alignment class styles to inline styles?

### ISSUE THREAD

**Issue by justlester** [ckeditor/ckeditor5#8004]
Hi! I am using the CKEditor 5 for creating email content. 
When I get output data from the editor, the image output in HTML have class styles of "image-style-right":
```
<figure class="image image_resized image-style-align-right" style="width:484px;">
<img src="https://c.cksource.com/a/1/img/docs/sample-image-bilingual-personality-disorder.jpg">
<figcaption>One language, one person.</figcaption>
</figure>
```
What I need is:
```
<figure style="width:484px; float:right;margin: 16px 0 16px 24px;">
<img style="width:100%" src="https://c.cksource.com/a/1/img/docs/sample-image-bilingual-personality-disorder.jpg">
<figcaption style="text-align:center; padding: .6em;font-size: .75em;">One language, one person.</figcaption>
</figure>
```

Without the styles, I can't display the image properly. I read the documentation but I'm not sure what APIs I will be using. 

A little help would be appreciated. Thanks!

**Comment by Mgsy** [comment]
Hi! Currently, CKEditor 5 doesn't allow converting class-based styles to inline styles. We have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1627) for it, so feel free to add :+1:  to the first post and join the discussion to bump its popularity.
