### ISSUE TITLE
Test and stabilize composition (IME) using beforeInput on desktop browsers (Mac)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8008]
## Provide a description of the task

On a F2F call with @niegowski we discovered that Safari on Mac uses `deleteByComposition` to recompose the typed content. It was a surprise because it seems Chrome does not do that so there are some differences within the same operating system when it comes to IME.

All Mac-compatible browsers must be tested thoroughly to make sure composition is stable and all use-cases (like recomposition) are covered.

Some extra things to verify:

*   does the spell check work (accepting changes)?
*   does the autocorrection work (spell checker changing words as you type)?
*   do accented letters work (they are not a composition on Mac)?

**Comment by Reinmar** [comment]
Closed together with #7462. We're reorganizing the work in #11438.
