### ISSUE TITLE
Test and stabilize composition (IME) using beforeInput on desktop browsers (Linux)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8010]
## Provide a description of the task

A twin to [#8008](https://github.com/ckeditor/ckeditor5/issues/8008) except that Linux-compatible browsers must be tested. As there are multiple desktop environments in the Linux ecosystem and IME is tightly connected to the OS, I'd stick to the most popular distributions like Ubuntu or Mint just for starters (maybe something with KDE? Is KDE still a thing?).

**Comment by Reinmar** [comment]
Closed together with #7462. We're reorganizing the work in #11438.
