### ISSUE TITLE
Test and stabilize composition (IME) using beforeInput on Android

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8011]
## Provide a description of the task

A twin to #8008 except that it's Android that must be tested. For starters, I'd go with the default Android web browser (that is Chrome most of the time, I guess) and few popular keyboards (because it's the keyboard that matters when it comes to IME).

**Comment by oleq** [comment]
I briefly checked out the status of things on Android 10 and it turned out it uses composition a lot, also for basic typing. While normal `insertText` works, `insertCompositionText` is used whenever the word is underlined (suggesting), which is like 80% of the time, also using English keyboard (it's not IME-related).

**Comment by oleq** [comment]
TODO: https://github.com/ckeditor/ckeditor5/pull/8176#discussion_r500229072

**Comment by Reinmar** [comment]
Closed together with #7462. We're reorganizing the work in #11438.
