### ISSUE TITLE
Test and stabilize beforeInput in Collaboration Features

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8013]
## Provide a description of the task

There are a few things that must be tested and stabilized, for instance:

*   what happens if during a composition a collaborator did some formatting in the same paragraph?
*   what happens if during a composition a collaborator split the paragraph?
*   what happens if during a composition an auto embedding finishes (paste a link, start composition, link was embedded)?
*   does `beforeInput` go well with track changes?
    *   does a composition on top of `beforeInput` work as well?
*   what happens when the autocorrection kicks in (spell checker changes words as you type) and the Track Changes is on?
*   does spell check work correctly with Track Changes?
*   ...
*   ...
*   ...
*   (probably lots of cases)

**Comment by Reinmar** [comment]
Closed together with #7462. We're reorganizing the work in #11438.
