### ISSUE TITLE
Customizing Mention Output. Writer is undefined

### ISSUE THREAD

**Issue by BillyNZL** [ckeditor/ckeditor5#8024]
## 📝 Provide detailed reproduction steps (if any)

1. …Follow instructions from https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#customizing-the-output

![Capture](https://user-images.githubusercontent.com/14131711/92182577-228c0080-eea0-11ea-8e99-e9a8380358de.PNG)

### ✔️ Expected result

Mention link will be customized to <a class="mention" data-mention="@Ted" data-user-id="5" href="https://www.imdb.com/title/tt0460649/characters/nm1102140">@tdog</a>

### ❌ Actual result
undefined error thrown on writer object

## 📃 Other details

* Browser: ANY
* OS: ANY
* CKEditor version: 5
* Installed CKEditor plugins: Mentions

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
@BillyNZL - could you verify installed CKEditor 4 plugins versions? I'd suspect that you might have `v21.x` or lower. We've just released [`v22`](https://github.com/ckeditor/ckeditor5/releases/tag/v22.0.0) which brought breaking changes:

`v21`: only writer was passed to conversion API callbacks

```javascript
view: ( modelAttributeValue, writer ) => {
```

in `v22` it becomes full [`conversionAPI`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_downcastdispatcher-DowncastConversionApi.html):

```javascript
view: ( modelAttributeValue, conversionAPI ) => {
```

**Comment by BillyNZL** [comment]
FYI

I used a custom build from the https://ckeditor.com/ckeditor-5/online-builder/ (with Mention Plugin). Then followed the guide above.

**Comment by BillyNZL** [comment]
I used CKEditor 5 (not 4)

**Comment by BillyNZL** [comment]
This was the code used (exactly as from the guide)

`    editor.conversion.for( 'downcast' ).attributeToElement( {
        model: 'mention',
        view: ( modelAttributeValue, { writer } ) => {
            // Do not convert empty attributes (lack of value means no mention).
            if ( !modelAttributeValue ) {
                return;
            }`

**Comment by BillyNZL** [comment]
I used the Custom Online Builder. How do I tell what version mention Plugin it comes with?

**Comment by jodator** [comment]
> I used CKEditor 5 (not 4)

I fixed a typo (sorry for the confusion). OK, for next few days, please use the `v21` ( `view: ( modelAttributeValue, writer ) => {` ) API from the example above. I've just checked, and the builder is not yet updated to the `v22` as we're in the middle of a release process. The docs, have been updated, but AFAIK, new features are still being added to the to the online builder.

The online builder should be updated when there'll be a blog post releases, which should happen in the next few days.

**Comment by BillyNZL** [comment]
Thanks, I can confirm that if I use v21 (view: ( modelAttributeValue, writer ) => {) it works
