### ISSUE TITLE
Using ckeditor from source can not build in vuejs

### ISSUE THREAD

**Issue by leeboo** [ckeditor/ckeditor5#8027]
install fresh vuejs project and followed this guide https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source

everything is ok when npm run serve, but npm run build, it's failed:

` error  in ./node_modules/@ckeditor/ckeditor5-paragraph/src/paragraph.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
this.query.translateSource is not a function
    at PoolWorker.fromErrorObj (/Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at /Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/thread-loader/dist/WorkerPool.js:152:14
    at Object.translateSourceLoader (/Users/ydhlleeboo/workspace/epiboly/design/webfront/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js:16:20)
`

... all ckeditor5 modules build failed

what does i missing?

**Comment by saroj990** [comment]
How do you include all the dependencies in the component ? and it would be nice if you can share the content package.json.

**Comment by leeboo** [comment]
package.json：
`{
  "name": "webfront",
  "version": "0.1.37",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --port 8080",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-alignment": "^22.0.0",
    "@ckeditor/ckeditor5-autoformat": "^22.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^22.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^23.2.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^23.2.0",
    "@ckeditor/ckeditor5-editor-balloon": "^22.0.0",
    "@ckeditor/ckeditor5-essentials": "^22.0.0",
    "@ckeditor/ckeditor5-font": "^22.0.0",
    "@ckeditor/ckeditor5-heading": "^22.0.0",
    "@ckeditor/ckeditor5-indent": "^22.0.0",
    "@ckeditor/ckeditor5-inspector": "^2.1.0",
    "@ckeditor/ckeditor5-link": "^22.0.0",
    "@ckeditor/ckeditor5-list": "^22.0.0",
    "@ckeditor/ckeditor5-paragraph": "^22.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^22.0.0",
    "@ckeditor/ckeditor5-remove-format": "^22.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^22.0.0",
    "@daybrush/drag": "^0.16.1",
    "@daybrush/utils": "^0.10.5",
    "@popperjs/core": "^2.4.0",
    "@scena/guides": "^0.8.0",
    "animate.css": "^3.7.2",
    "awesome-bootstrap-checkbox": "^1.0.1",
    "bootstrap": "^4.5.0",
    "core-js": "^3.6.5",
    "cssgram": "^0.1.3",
    "dom-to-image": "^2.6.0",
    "echarts": "^4.8.0",
    "gradient-parser": "^0.1.5",
    "html2canvas": "^1.0.0-rc.5",
    "imagesloaded": "^4.1.4",
    "infinite-viewer": "^0.4.3",
    "ion-rangeslider": "^2.3.1",
    "jquery": "^3.5.1",
    "jquery-bridget": "^2.0.1",
    "keycon": "^0.8.0",
    "lodash": "^4.17.15",
    "masonry-layout": "^4.2.2",
    "moveable": "^0.17.10",
    "popper.js": "^1.16.1",
    "postcss-loader": "^3.0.0",
    "puppeteer": "^3.3.0",
    "raw-loader": "^0.5.1",
    "react-compat-css-styled": "^0.1.3",
    "react-simple-compat": "^0.1.7",
    "register-service-worker": "^1.7.1",
    "scenejs": "^1.1.7",
    "scss": "^0.2.4",
    "select2": "^4.0.13",
    "selecto": "^1.1.2",
    "sortablejs": "^1.10.2",
    "tinycolor2": "^1.4.1",
    "unit-to-px": "^1.0.5",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.2",
    "vue-color": "^2.7.1",
    "vue-property-decorator": "^8.4.2",
    "vue-router": "^3.2.0",
    "vue-upload-component": "^2.8.20",
    "vuex": "^3.4.0",
    "vxe-table": "^2.9.9",
    "xe-utils": "^2.4.5",
    "xmlserializer": "^0.6.1"
  },
  "devDependencies": {
    "@types/bootstrap": "^4.5.0",
    "@types/dom-to-image": "^2.6.0",
    "@types/echarts": "^4.6.0",
    "@types/imagesloaded": "^4.1.2",
    "@types/jest": "^24.0.19",
    "@types/jquery": "^3.3.38",
    "@types/masonry-layout": "^4.2.1",
    "@types/sortablejs": "^1.10.4",
    "@types/tinycolor2": "^1.4.2",
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.34.0",
    "@vue/cli-plugin-babel": "^4.2.3",
    "@vue/cli-plugin-eslint": "^4.2.3",
    "@vue/cli-plugin-pwa": "^4.2.3",
    "@vue/cli-plugin-router": "^4.2.3",
    "@vue/cli-plugin-typescript": "^4.2.3",
    "@vue/cli-plugin-unit-jest": "^4.2.3",
    "@vue/cli-plugin-vuex": "^4.2.3",
    "@vue/cli-service": "^4.2.3",
    "@vue/eslint-config-standard": "^5.1.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "@vue/test-utils": "1.0.0-beta.31",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~3.7.5",
    "vue-template-compiler": "^2.6.11",
    "w3c-xmlserializer": "^2.0.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/strongly-recommended",
      "@vue/standard",
      "@vue/typescript/recommended"
    ],
    "parserOptions": {
      "ecmaVersion": 2020
    },
    "overrides": [
      {
        "files": [
          "**/__tests__/*.{j,t}s?(x)",
          "**/tests/unit/**/*.spec.{j,t}s?(x)"
        ],
        "env": {
          "jest": true
        }
      }
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "jest": {
    "preset": "@vue/cli-plugin-unit-jest/presets/typescript-and-babel"
  }
}
`


vue.config.js:
`
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path')
// eslint-disable-next-line @typescript-eslint/no-var-requires
const CKEditorWebpackPlugin = require('@ckeditor/ckeditor5-dev-webpack-plugin')
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { styles } = require('@ckeditor/ckeditor5-dev-utils')

module.exports = {
  lintOnSave: false,
  // The source of CKEditor is encapsulated in ES6 modules. By default, the code
  // from the node_modules directory is not transpiled, so you must explicitly tell
  // the CLI tools to transpile JavaScript files in all ckeditor5-* modules.
  transpileDependencies: [
    /ckeditor5-[^/\\]+[/\\]src[/\\].+\.js$/
  ],
  configureWebpack: {
    plugins: [
      // CKEditor needs its own plugin to be built using webpack.
      new CKEditorWebpackPlugin({
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'zh-cn',

        // Append translations to the file matching the `app` name.
        translationsOutputFile: /app/
      })
    ]
  },
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        args[0].title = 'Layouts'
        return args
      })
    // Vue CLI would normally use its own loader to load .svg and .css files, however:
    // 1. The icons used by CKEditor must be loaded using raw-loader,
    // 2. The CSS used by CKEditor must be transpiled using PostCSS to load properly.

    // (1.) To handle editor icons, get the default rule for *.svg files first:
    const svgRule = config.module.rule('svg')

    // Then you can either:
    //
    // * clear all loaders for existing 'svg' rule:
    //
    // svgRule.uses.clear();
    //
    // * or exclude ckeditor directory from node_modules:
    svgRule.exclude.add(path.join(__dirname, 'node_modules', '@ckeditor'))

    // Add an entry for *.svg files belonging to CKEditor. You can either:
    //
    // * modify the existing 'svg' rule:
    //
    // svgRule.use( 'raw-loader' ).loader( 'raw-loader' );
    //
    // * or add a new one:
    config.module
      .rule('cke-svg')
      .test(/ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/)
      .use('raw-loader')
      .loader('raw-loader')

    // (2.) Transpile the .css files imported by the editor using PostCSS.
    // Make sure only the CSS belonging to ckeditor5-* packages is processed this way.
    config.module
      .rule('cke-css')
      .test(/ckeditor5-[^/\\]+[/\\].+\.css$/)
      .use('postcss-loader')
      .loader('postcss-loader')
      .tap(() => {
        return styles.getPostCssConfig({
          themeImporter: {
            themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
          },
          minify: true
        })
      })
  }
}
`

**Comment by leeboo** [comment]
i found remove this code, build success:
![image](https://user-images.githubusercontent.com/1256745/92295968-4fa0e780-ef62-11ea-9612-1a3ca2c3bcdb.png)
What was the effect if i remove CKEditorWebpackPlugin

**Comment by saroj990** [comment]
Everything looks okay to me. This one https://github.com/ckeditor/ckeditor5-vue/issues/136 might be helpful.

**Comment by FilipTokarski** [comment]
Hi @leeboo, I understand that you have already solved your problem and we can close this ticket?
