### ISSUE TITLE
Browser freezes after dropping the image to the editor from the files browsing window

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#803]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-easy-image/tests/manual/easyimage.html.
2. Click on the insert image icon.
3. Drag the image to the editor.
4. Close the window.

## ✅ Expected result

The image has been inserted and editor works fine.

## ❎ Actual result

The image has been inserted, but the browser freezes.

## 📃 Other details that might be useful

**Notes**

This bug is pretty random, I wasn't able to find any dependency while it occurred. Basically, I am able to reproduce this issue only in Chrome and on Windows. Sometimes it occurs after first d&d, sometimes after 10th and sometimes just doesn't occur. 

Drag and drop upload from the desktop works fine, so it looks like problem occurs only when image is dragged from the files browsing window.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/35668634-85230c64-0732-11e8-9837-d2716c058be2.gif)

**Other information**

OS: Windows 10
Browser: Chrome

**Comment by oleq** [comment]
That's a nasty one. It means that users might lose their content. 

cc @Reinmar

**Comment by Reinmar** [comment]
@Mgsy is it a regression? If not, is it possible to bisect it?

**Comment by Mgsy** [comment]
This is not a regression and I believe it occurs since the upload plugin has been introduced. After small investigation I can point some old commits:

- Here is the first bad revision, which introduces the upload plugin to the editor - https://github.com/ckeditor/ckeditor5/commit/22abf5172f158f4030ebe9665d406f043a8e8422.

- And here is the first bad commit in the upload repository - https://github.com/ckeditor/ckeditor5-upload/commit/9276e1de7f035713328cbedf1845c83da2a1eb1d. This is the oldest one which allows to test this bug manually. Older ones don't have the insert image button, so testing this scenario is impossible.

This bug is easier to reproduce when you test it in the [upload image manual test](http://192.168.20.71:8125/ckeditor5-upload/tests/manual/imageupload.html). My browser freezes every time after second d&d from the dialog. Still, I'm able to reproduce it only in Chrome on Windows.

**Comment by FilipTokarski** [comment]
Checked it once again and it seems like Chrome is working fine now, no freezing.
However I'm not able to drag&drop the image in Firefox at all.
