### ISSUE TITLE
Unlinking fails for middle block when more than 2 blocks are selected

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8030]
## 📝 Provide detailed reproduction steps (if any)

1.  Create 3 blocks, e.g. used 3 list items.
2.  Select all of them and create a link.
3.  Click "Unlink" in the link actions balloon.

![](https://user-images.githubusercontent.com/1099479/92243142-46137300-eec1-11ea-87d5-74a5a4e93754.gif)

### ✔️ Expected result

All items should be free of the link.

### ❌ Actual result

The middle item is still linked.

I briefly checked this and the 3 ranges `Writer#removeAttribute()` works on internally are looking fine. It feels like the bug is in the `setAttributeOnRange()` helper. When I logged the following

```
console.log( val.item, valueBefore, valueAfter );
```

in the walker inside it was

```
TextProxy {textNode: Text, data: "tem", offsetInText: 0} undefined "foo"
Element {parent: RootElement, _attrs: Map(2), name: "listItem", _children: NodeList} undefined undefined
TextProxy {textNode: Text, data: "third", offsetInText: 0} undefined "foo"
```

because the walker created with `shallow: true`. When I got rid of this option, the bug is gone and more items are logged

```
TextProxy {textNode: Text, data: "tem", offsetInText: 0} undefined "foo"
Element {parent: RootElement, _attrs: Map(2), name: "listItem", _children: NodeList} undefined undefined
TextProxy {textNode: Text, data: "second item", offsetInText: 0} undefined "foo"
Element {parent: RootElement, _attrs: Map(2), name: "listItem", _children: NodeList} "foo" undefined
TextProxy {textNode: Text, data: "thir", offsetInText: 0} undefined "foo"
```

P.S. The bug could also be in `getMinimalFlatRanges()`.

## 📃 Other details

*   Browser: Chrome
*   OS: Mac
*   CKEditor version: v22.0.0

It's not a regression, I checked in v16.0.0 and it's all the same.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by panr** [comment]
This bug appeared after the changes from this commit: https://github.com/ckeditor/ckeditor5/commit/0ed523ef12dc6b0849bbec19049405850b270857#diff-a3ae70b600cbe7a13e75771a6a5519acR81

**Comment by oleq** [comment]
Are you sure this is the right commit? Because I'm experiencing the same bug in releases [as old as v16.0.0.](https://ckeditor5.github.io/docs/nightly/ckeditor5/16.0.0/examples/builds/classic-editor.html)

**Comment by panr** [comment]
`git bisect` told me that this is the one ;-P Reverting that commit fixes this issue for my case (regarding multi-block link marker issue).
