### ISSUE TITLE
Korean characters are broken when typing between blocks

### ISSUE THREAD

**Issue by KENNYSOFT** [ckeditor/ckeditor5#8031]
## 📝 Provide detailed reproduction steps (if any)

1. Type a block with any type like `code1` or _itallic1_, or **bold1**
2. Type two spaces, and then type a block like `code2` or _itallic2_, or **bold2**
3. Back the cursor to between spaces, and then try typing Korean characters

### ✔️ Expected result

Korean characters should be inputted correctly, like below:

> `code1` 안녕하세요 `code2`

### ❌ Actual result

Korean characters are broken, like below:

> `code1` ㅇ아안ㄴ녀녕ㅎ하핫세셍요 `code2`

More details in ckeditor/github-writer#224

## 📃 Other details

* Browser: Chrome 84 and Chrome 85
* OS: Windows 10 20H1
* CKEditor version: IDK, provided ckeditor/github-writer
* Installed CKEditor plugins: IDK

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by fredck** [comment]
This issue is a follow up to ckeditor/github-writer#224. It seems that IME doesn't inherit styles when typing inside inline-styled text.

**Comment by jongjunpark** [comment]
Also, same issue occur when space bar is pressed twice then typing Korean text.
In addition, when mathtype code is inserted then press one space bar, there is founded same issue.

**Comment by dancinlife** [comment]
I have same issue.

https://user-images.githubusercontent.com/44921882/158103288-9b6ba6e3-25b2-41cb-9b8c-3ab45e34a581.MP4

**Comment by dancinlife** [comment]
korean characters change ploblem.

https://user-images.githubusercontent.com/44921882/158103695-5f82f080-4209-45be-8859-cb2d0a7dee8d.MP4

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team  Could you retest this with the latest CKE version?

**Comment by bysxx** [comment]
This issue occurred in version 31.0.0, but seems to have been resolved by updating to version 35.3.2. 
Previously, the logic of creating '<p>&nbsp</p>' seems to have caused a problem

**Comment by mabryl** [comment]
Can confirm that the issue no longer appears in the newest version of the editor, hence closing the ticket.
