### ISSUE TITLE
Allow ID in paragraph creates a nested para.

### ISSUE THREAD

**Issue by sameerpallav** [ckeditor/ckeditor5#8032]
## 📝 Provide detailed reproduction steps (if any)
I want to allow id attribute in paragraphs in ckeditor5. So I followed the code mentioned in ckedtor5 docs.

```
ConvertDivAttributes(editor) {
    editor = editor || this.Editor;
    // Allow <div> elements in the model.
    editor.model.schema.register('p', {
      allowWhere: '$block',
      allowContentOf: '$root',
      allowAttributes: ['id']
    });
    // // // Allow <div> elements in the model to have all attributes.
    editor.model.schema.addAttributeCheck(context => {
      if (context.endsWith('p')) {
        return true;
      }
    });

    // // // // The view-to-model converter converting a view <div> with all its attributes to the model.
    editor.conversion.for('upcast').elementToElement({
      view: 'p',
      model: (viewElement, { writer: modelWriter }) => {
        console.log(viewElement);
        // return modelWriter.setAttribute( viewElement.getAttributes());
        return modelWriter.createElement('p', viewElement.getAttributes());
      }
    });

    // // // // // The model-to-view converter for the <div> element (attributes are converted separately).
    editor.conversion.for('downcast').elementToElement({
      model: 'p',
      view: 'p'
    });

    // // // // The model-to-view converter for <div> attributes.
    // // // // Note that a lower-level, event-based API is used here.
    editor.conversion.for('downcast').add(dispatcher => {
      dispatcher.on('attribute', (evt, data, conversionApi) => {
        // Convert <div> attributes only.
        if (data.item.name !== 'p') {
          return;
        }

        const viewWriter = conversionApi.writer;
        const viewDiv = conversionApi.mapper.toViewElement(data.item);

        // In the model-to-view conversion we convert changes.
        // An attribute can be added or removed or changed.
        // The below code handles all 3 cases.
        if (data.attributeNewValue) {
          viewWriter.setAttribute(data.attributeKey, data.attributeNewValue, viewDiv);
        } else {
          viewWriter.removeAttribute(data.attributeKey, viewDiv);
        }
      });
    });
  }
```

This results in a HTML structure
```
<p id="5f437ab1469b7cf994912ef1">
     <p class="">BIC (SWIFT Code) XXX</p>
</p>
```
### ✔️What I want is 
`<p id="5f437ab1469b7cf994912ef1" class="">BIC (SWIFT Code) XXX</p>`

Can anyone help out on how to do it?

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
You've registered a `p` element in the schema while CKEditor uses [`paragraph`](https://ckeditor.com/docs/ckeditor5/latest/api/module_paragraph_paragraph-Paragraph.html) to convert `<p>` HTML elements. If you'd like to extend existing `paragraph` you need to use only attribute conversion part of your code.

I'd remove:

*   `editor.model.schema.register` 
*   instead of `schema.addAttributeCheck` you could [extend](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html#function-extend) existing `paragraph` schema definition, but for now it is OK.
*   probably [a two-way attribute converter](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-attributeToAttribute) should do the trick of retaining `id` attribute on paragraph:

```javascript
editor.conversion.attributeToAttribute( {
    view: 'id',
    model: 'id'
} );
```

**Comment by sameerpallav** [comment]
I managed to preserve id and classes via the following code without creating nested elements.
`class AllowAttributes {
  editor;
  /**
   * Plugin's constructor - receives an editor instance on creation.
   */
  constructor( editor ) {
      // Save reference to the editor.
      this.editor = editor;
  }

  /**
   * Sets the conversion up and extends the table & image features schema.
   *
   * Schema extending must be done in the "afterInit()" call because plugins define their schema in "init()".
   */
  afterInit() {
      const editor = this.editor;

      // Define custom attributes that should be preserved.
      setupCustomAttributeConversion( 'p', 'paragraph', 'id', editor );
      setupCustomAttributeConversion( 'h2', 'heading1', 'id', editor );
      setupCustomAttributeConversion( 'h3', 'heading2', 'id', editor );
      setupCustomAttributeConversion( 'h4', 'heading3', 'id', editor );
      // setupCustomAttributeConversion( 'table', 'table', 'id', editor );
      // setupCustomAttributeConversion( 'img', 'image', 'id', editor );

      // Define custom class that should be preserved.
      setupCustomAttributeConversion( 'p', 'paragraph', 'class', editor );
      setupCustomAttributeConversion( 'h2', 'heading1', 'class', editor );
      setupCustomAttributeConversion( 'h3', 'heading2', 'class', editor );
      setupCustomAttributeConversion( 'h4', 'heading3', 'class', editor );
  }
}

function setupCustomAttributeConversion( viewElementName, modelElementName, viewAttribute, editor ) {
  // Extends the schema to store an attribute in the model.
  const modelAttribute = `${ viewAttribute }`;

  editor.model.schema.extend( modelElementName, { allowAttributes: [ modelAttribute ], isBlock: true } );

  editor.conversion.for( 'upcast' ).add( upcastAttribute( viewElementName, viewAttribute, modelAttribute ) );
  editor.conversion.for( 'downcast' ).add( downcastAttribute( modelElementName, viewElementName, viewAttribute, modelAttribute ) );
}

/**
 * Returns the custom attribute upcast converter.
 */
function upcastAttribute( viewElementName, viewAttribute, modelAttribute ) {
  return dispatcher => dispatcher.on( `element:${ viewElementName }`, ( evt, data, conversionApi ) => {
      const viewItem = data.viewItem;
      const modelRange = data.modelRange;

      const modelElement = modelRange && modelRange.start.nodeAfter;

      if ( !modelElement ) {
          return;
      }

      conversionApi.writer.setAttribute( modelAttribute, viewItem.getAttribute( viewAttribute ), modelElement );
  } );
}

/**
 * Returns the custom attribute downcast converter.
 */
function downcastAttribute( modelElementName, viewElementName, viewAttribute, modelAttribute ) {
  return dispatcher => dispatcher.on( `insert:${ modelElementName }`, ( evt, data, conversionApi ) => {
      const modelElement = data.item;

      const viewFigure = conversionApi.mapper.toViewElement( modelElement );
      // const viewElement = findViewChild( viewFigure, viewElementName, conversionApi );

      // if ( !viewElement ) {
      //     return;
      // }
      if (modelElement.getAttribute( modelAttribute )) {
        conversionApi.writer.setAttribute( viewAttribute, modelElement.getAttribute( modelAttribute ), viewFigure );
      }
  } );
}`

**Comment by sameerpallav** [comment]
The above class works as expected

**Comment by saisk73** [comment]
Hi I'm getting the same error in reactjs how could I fix this can in the function itself.


OS: Windows
CKEditor version 5
Framework: React 16.6.0
