### ISSUE TITLE
Change Media Embed URL input field placeholder

### ISSUE THREAD

**Issue by NemanjaSoldo** [ckeditor/ckeditor5#8042]
Is it possible to change placeholder of the URL input box for media embedding? So to write custom URL instead of https://example.com ?
![image](https://user-images.githubusercontent.com/11049488/92468872-25eef700-f1d4-11ea-99bd-9b45b526c94a.png)

**Comment by FilipTokarski** [comment]
Hi, unfortunately there is currently no obvious way to do it.
One workaround could be just simply target this input by a css selector, and change its placeholder on initialization:  
`document.querySelector( '.ck-input' ).placeholder = 'www.mywebsite.com';`  
But this doesn't make much sense when there are more plugins with inputs like this.  
  
Other workaround would be to change the plugin's code here:  
https://github.com/ckeditor/ckeditor5/blob/3679012f75a22249e0dd3bd54c2a5d0eea869d75/packages/ckeditor5-media-embed/src/ui/mediaformview.js#L274  
But that's also not a flexible and stable solution, as you would need to do it every time you update the packages.
