### ISSUE TITLE
Should toolbar have a gradient?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#805]
![image](https://user-images.githubusercontent.com/156149/35679276-b444bf1e-0756-11e8-88d4-522eddfae886.png)

My feeling is that a gradient is a bit out of fashion. WDYT?

**Comment by oleq** [comment]
A follow-up of https://github.com/ckeditor/ckeditor5/issues/645.

**Comment by oleq** [comment]
If we go with the gradient, this one must be fixed:

![image](https://user-images.githubusercontent.com/1099479/35809731-d5cd9f1c-0a89-11e8-86f0-77e76449f782.png)

**Comment by scofalik** [comment]
I don't like gradient. It looks a bit weird when you hover over icon - the contrast near top of the icon is different than on the below.

**Comment by Reinmar** [comment]
I was curious how it's going to look without the gradient and I'm not satisfied with this eiter :P

A little darker:

![image](https://user-images.githubusercontent.com/156149/35810597-80669986-0a8c-11e8-8276-e2b84e1c5c4d.png)

A little ligther:

![image](https://user-images.githubusercontent.com/156149/35810655-bcc9de38-0a8c-11e8-86df-6a3cac1aa446.png)

Current:

![image](https://user-images.githubusercontent.com/156149/35810607-884eeacc-0a8c-11e8-840b-784a339546ce.png)

**Comment by dkonopka** [comment]
For me, that gradient in toolbar looks like something not rendered properly. On the other hand gradient is not working good with states of buttons + arrows in balloons.

IMHO we should decide to color, like `#f8f8f8` or `#dadada`. 

![screen shot 2018-02-05 at 15 56 26](https://user-images.githubusercontent.com/10219857/35810839-4394673a-0a8d-11e8-96f2-c4eaa6168526.png)

**Comment by Reinmar** [comment]
#dadada is a bit too dark IMO... OTOH, https://www.youtube.com/watch?v=lNYcviXK4rg

**Comment by Reinmar** [comment]
BTW, if we'd remove the gradient and go with a light background then the borders stand out too much.

Is the contrast between borders and the toolbar background important for a11y?

**Comment by oleq** [comment]
> Is the contrast between borders and the toolbar background important for a11y?

Not that much. It's more about the design.

**Comment by oleq** [comment]
BTW: Please make sure you visualize the editor as a part of an environment. Otherwise, it does not make much sense. CKEditor is almost never a standalone application in the web page. It makes a difference.

## Gradient

![ckeditor5-in-drupal-gradient](https://user-images.githubusercontent.com/1099479/35850306-a0562156-0b24-11e8-8047-63fde9cec70d.png)

## Flat

![ckeditor5-in-drupal-flat](https://user-images.githubusercontent.com/1099479/35850311-a3aed79e-0b24-11e8-9dea-f0ed2d337517.png)

**Comment by Reinmar** [comment]
This is a good point. There are, however, many kind of apps to which CKEditor will be injected. I guess you can't look ideal in all of them.

From the two screenshot of CKEditor 5 in Drupal 8 I'm totally ok with both. I guess that the same will be for Wordpress, Neos or whatever else you'd try. Moreover, developers who will be integrating CKEditor 5 into these apps will be able to easily adjust the colors and gradients and everything. Which means that we fully satisfy this requirement (for CKE to be easy to integrate).

What matters now, the most, is the initial look of CKEditor 5 on our websites (docs and ckeditor.com). I'd actually focus on these, if we're talking about putting things into perspective.

**Comment by Reinmar** [comment]
Interestingly, this gradient is far less visible on my MB Pro than on my Dell external LCD. On my MB Pro it looks good :D

**Comment by Reinmar** [comment]
Result of our discussion with @dkonopka and @oleq. With and without gradient:

![ckeditor5 github io_docs_nightly_ckeditor5_latest_examples_builds_classic-editor html 2](https://user-images.githubusercontent.com/156149/36209953-7b611dcc-119d-11e8-9137-39c7ad1d83fd.png)

![ckeditor5 github io_docs_nightly_ckeditor5_latest_examples_builds_classic-editor html 3](https://user-images.githubusercontent.com/156149/36209954-7b80c1b8-119d-11e8-8c91-9c4ef725d267.png)
