### ISSUE TITLE
Make editor placeholder behave like the native input placeholder

### ISSUE THREAD

**Issue by uriklar** [ckeditor/ckeditor5#8058]
In a native input the placeholder text disappears only once starting to type, not of focus. ([See example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder))

In CKEditor the placeholder text disappears on focus. ([See example](https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html))

I'd expect it to behave the same way as the native one does.  
If someone can point me in the right direction I could try taking a crack at it. Thanks!

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, this difference arises from the fact, that in CKEditor the editing area is not a standard input and there is a custom implementation of a placeholder.

Possible workaround would be to remove `!doc.isFocused` from this check - https://github.com/ckeditor/ckeditor5/blob/3679012f75a22249e0dd3bd54c2a5d0eea869d75/packages/ckeditor5-engine/src/view/placeholder.js#L158
  
but it still doesn't look 100% like in the native input and also you would need to do it everytime you update the packages.

I'll leave this issue open and change it to a feature request.

**Comment by FilipTokarski** [comment]
I changed the name of the issue to better match the purpose of a feature request.

**Comment by winzig** [comment]
Would it be possible to put the placeholder "behind" the CKEditor editing div, leaving the editor semi-translucent so the placeholder bleeds through, and then hiding it completely once the div is non-empty? I opened another bug related to the current placeholder in #8385.

**Comment by oleq** [comment]
Fixed in #8689.
