### ISSUE TITLE
Opened dropdown's button has an odd background

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#806]
![image](https://user-images.githubusercontent.com/156149/35679487-82403222-0757-11e8-837d-8e8a2b0b40bd.png)

Was this on purpose?

**Comment by oleq** [comment]
That's actually a bug. It should have active button's background.
![image](https://user-images.githubusercontent.com/1099479/35684020-e959eb70-0765-11e8-98bb-8e689b84bba0.png)
