### ISSUE TITLE
移除默认占位字符

### ISSUE THREAD

**Issue by mdddj** [ckeditor/ckeditor5#8066]
## 📝 Provide a description of requested docs changes

_What is the purpose and what should be changed?_
![image](https://user-images.githubusercontent.com/29020213/92991745-88b7f980-f518-11ea-93ad-abd4fd4a1288.png)
how delete it

**Comment by Mgsy** [comment]
Hi, I'm sorry, but I can't understand your case. Please, provide some meaningful detailed description in English.

**Comment by mdddj** [comment]
This is a plugin problem that has been fixed
