### ISSUE TITLE
Pasting text in the middle of a linked/hyperlink text breaks into 2 hyperlink texts.  

### ISSUE THREAD

**Issue by justlester** [ckeditor/ckeditor5#8067]
## 📝 Provide detailed reproduction steps (if any)

1. Add a linked/hyperlink text. 
2. Copy any text and paste in the middle of the linked/hyperlink text. 

### ✔️ Expected result

![image](https://user-images.githubusercontent.com/47380149/93047910-2d107c00-f690-11ea-9edc-1348f3570350.png)

### ❌ Actual result

![image](https://user-images.githubusercontent.com/47380149/93047850-005c6480-f690-11ea-8138-2ba7fcf54722.png)

## 📃 Other details

* Browser: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
* OS: Windows 10
* Dependencies: 
``
    "@ckeditor/ckeditor5-autoformat": "^21.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^21.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^23.5.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^23.5.1",
    "@ckeditor/ckeditor5-editor-classic": "^21.0.0",
    "@ckeditor/ckeditor5-essentials": "^21.0.0",
    "@ckeditor/ckeditor5-heading": "^21.0.0",
    "@ckeditor/ckeditor5-image": "^21.0.0",
    "@ckeditor/ckeditor5-link": "^21.0.0",
    "@ckeditor/ckeditor5-list": "^21.0.0",
    "@ckeditor/ckeditor5-media-embed": "^21.0.0",
    "@ckeditor/ckeditor5-paragraph": "^21.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^21.0.0",
    "@ckeditor/ckeditor5-remove-format": "^21.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^21.0.0",
    "@ckeditor/ckeditor5-typing": "^21.0.0",
    "@ckeditor/ckeditor5-upload": "^21.0.0",
    "@ckeditor/ckeditor5-watchdog": "^22.0.0",
    "@ckeditor/ckeditor5-word-count": "^21.0.0",
``

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. This behaviour has been changed in the latest release (v22.0.0). After updating your packages, it should work as expected. You can verify it in our [online demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html).

**Comment by justlester** [comment]
> Hi, thanks for the report. This behaviour has been changed in the latest release (v22.0.0). After updating your packages, it should work as expected. You can verify it in our [online demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html).

Great! Thanks :D
