### ISSUE TITLE
Implementation of adapter for image upload on an existing basis

### ISSUE THREAD

**Issue by guimaraesSalgado** [ckeditor/ckeditor5#8076]
I clone an existing base (classic) and when inserting the adapter it returns an error, an error that I am not able to correct

![image](https://user-images.githubusercontent.com/49767698/93123305-40c2df00-f69e-11ea-9b69-41d2aff68036.png)
![image](https://user-images.githubusercontent.com/49767698/93123320-47e9ed00-f69e-11ea-8c3a-e09d39ce60a8.png)

how to get around this? since it is not in the base?

**Comment by Mgsy** [comment]
Hi! You've probably cloned [ckeditor5-build-classic](https://github.com/ckeditor/ckeditor5-build-classic) repository, which is no longer maintained. It has outdated packages at version 19.0.0, as the latest version is 22.0.0. You can't install the latest package (in your base `Base64UploadAdapter`) and run it along with the outdated ones. 

Please, see our updated guide about [installing plugins.](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) You can also simply update packages manually and it should fix your issue.
