### ISSUE TITLE
Can't execute imageInsert command inside other plugin

### ISSUE THREAD

**Issue by dbojarski** [ckeditor/ckeditor5#8083]
Image plugin has ``imageInsert``command responsible for inserting the image inside the editor. I have my own plugin and dependently on the situation I'd like not to use the plugin but instead insert an image (different plugin, default one from CKEditor - Image)

```
    // TOKEN PLUGIN
    function createPlaceholderView(item, writer, placeholderFormat) {
      const name = item.getAttribute('name');
      const label = item.getAttribute('label');
      const value = item.getAttribute('value');
      const tokenIsImage = tokenIsImage(name);

      if(tokenIsImage) {
        // HERE I'D LIKE TO PLUG OUT FROM TOKEN PLUGIN AND USE THE Image plugin FROM CKEDITOR
      	editor.execute('imageInsert', {src: value});

        return;
	  }

      const placeholderView = writer.createContainerElement(...getCreateElementSettings(
        name,
        label,
        value
      ));
      let innerText;

      if(valueMode && value) {
        innerText = writer.createText(tokenIsCompanyLogo ? '' : value);
      } else {
        innerText = writer.createText(placeholderFormat.replace(TOKEN_FORMAT_PLACEHOLDER, label));
      }

      writer.insert(writer.createPositionAt(placeholderView, 0), innerText);

      return placeholderView;
    }

```

Unfortunately I get an error. I thought that maybe the error appeared because of empty return but even without the return the error still appears.

```
CKEditorError: unexpected-error {"originalError":{"message":"Cannot read property 'name' of undefined","stack":"TypeError: Cannot read property 'name' of undefined\n at Gr.getModelLength (http://elzoy-demo21072020.localhost:4200/main.js:113952:227295)\n at Gr._findPositionIn (http://elzoy-demo21072020.localhost:4200/main.js:113952:227654)\n at Gr.on.priority (http://elzoy-demo21072020.localhost:4200/main.js:113952:224462)\n at Gr.fire (http://elzoy-demo21072020.localhost:4200/main.js:113952:108684)\n at Gr.toViewPosition (http://elzoy-demo21072020.localhost:4200/main.js:113952:226594)\n at Gr.toViewRange (http://elzoy-demo21072020.localhost:4200/main.js:113952:226350)\n at Jr.Aa.downcastDispatcher.on.priority (http://elzoy-demo21072020.localhost:4200/main.js:113952:258265)\n at Jr.fire (http://elzoy-demo21072020.localhost:4200/main.js:113952:108684)\n at Jr.convertSelection (http://elzoy-demo21072020.localhost:4200/main.js:113952:230938)\n at http://elzoy-demo21072020.localhost:4200/main.js:113952:256937","name":"TypeError"}}

```

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! It looks like you're modifying the model during conversion from model to the view. I assume that `createPlaceholderView` is used in some converter, and so it _must_ return something. You cannot just abort with an empty `return` and at this stage decide to do something else. A converter is supposed to convert things (mode to view or view to model). It should return an element representing the model element that's being converted. And if you need additional logic that needs to change the model, it needs to be executed earlier or later. Perhaps a [post-fixer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#function-registerPostFixer) might help you but I don't know your case and it's generally good to avoid post-fixers if possible.
