### ISSUE TITLE
How to use Mathematical Formulas in Angular 9 Project(Editor)

### ISSUE THREAD

**Issue by hasmukh-smartSense** [ckeditor/ckeditor5#8094]
#### I have used the below command for angular 

npm install ckeditor4-angular --save

##### Html code
```
<ckeditor [config]="options" id="editor1" [(ngModel)]="model.editorData"></ckeditor>
```

##### TypeScript Code
```
public model = {
    editorData: '<p>Hello, world!</p>',
 };
```
Angular 9 Editor show but I want to add Mathematical Formulas 
![1](https://user-images.githubusercontent.com/67405620/93420105-eb6c1500-f8cb-11ea-9a6a-fde37cfbbd12.png)

This is Mathematical Formulas Example in doc
![2](https://user-images.githubusercontent.com/67405620/93420194-1b1b1d00-f8cc-11ea-812d-59eb7a17f22e.png)

**Comment by FilipTokarski** [comment]
Hi thanks for the report. I see that you are using CKEditor 4 which is a completely different application than CKEditor 5. Please report this issue in [CKEditor 4 issue tracker](https://github.com/ckeditor/ckeditor4/issues). I'll close this as invalid.
