### ISSUE TITLE
Unsupported element causes JS error instead of being filtered out

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#8098]
## 📝 Provide detailed reproduction steps (if any)

1.  First you need to open ZD support ticket no. 64940 where you will find `SampleEmail_SendToCKEditor.html` and `unnamed_attachment_1.eml`.
2.  Please download these files and open `.eml` in email client and the `.htm` in MS Word as well as browser e.g. new Edge.
3.  Copy the contents (Ctrl+A/Ctrl+C) and paste them into CKEditor

### ✔️ Expected result

Content gets pasted

### ❌ Actual result

Content doesn't get pasted and JS error is being thrown.

```
emittermixin.js:242 Uncaught TypeError: Cannot read property 'childCount' of null
at UpcastDispatcher.dispatcher.on.priority (upcasttable.js:103)
at UpcastDispatcher.fire (emittermixin.js:209)
at UpcastDispatcher._convertItem (upcastdispatcher.js:249)
at UpcastDispatcher._convertChildren (upcastdispatcher.js:282)
at UpcastDispatcher.<anonymous> (upcasthelpers.js:454)
at UpcastDispatcher.fire (emittermixin.js:209)
at UpcastDispatcher._convertItem (upcastdispatcher.js:249)
at UpcastDispatcher._convertChildren (upcastdispatcher.js:282)
at UpcastDispatcher.<anonymous> (upcasthelpers.js:454)
at UpcastDispatcher.fire (emittermixin.js:209)
```

The problem is that template contains `div` elements which wrap the `table` and are inside the `table` element. Instead of being filtered out they cause JS error (once you add `div` plugin the error is gone).

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: 22.0.0
*   Installed CKEditor plugins: All Features

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jswiderski** [comment]
In order to work around this problem one needs to implement div plugin e.g. https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html#loading-content-with-all-attributes.

Once plugins supporting divs is added to the build template no longer produces errors.

**Comment by Reinmar** [comment]
It'd be good to first bisect this as it may give us some pointers.

**Comment by pomek** [comment]
It's a regression. Bisect: https://github.com/ckeditor/ckeditor5/commit/aa6f0baf21ea9d0593d42c57e7aac7e12e94cee2.

**Comment by pomek** [comment]
Minimal HTML snippet that triggers the error:

```html
<table>
   <tbody>
      <tr>
         <td>
            <div align="center">
               <table>
                  <tbody>
                     <tr>
                        <td style="border: 2px solid rgb(242, 242, 242);">
                           <p>Test</p>
                        </td>
                     </tr>
                  </tbody>
               </table>
            </div>
         </td>
      </tr>
   </tbody>
</table>
```

After removing the `div` element or the `td[style]` attribute, everything works.
