### ISSUE TITLE
Research different looks of balloon navigation buttons

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#810]
ATM we use a green background for "save" and no background for cancel:

![image](https://user-images.githubusercontent.com/1099479/35739637-8279685e-0832-11e8-9b72-9e8870332f4e.png)

but we could use a different approach to make it even more lightweight (possibly making the icons thicker):

![image](https://user-images.githubusercontent.com/1099479/35739673-a7ad3ee8-0832-11e8-834c-3707cbc4a91b.png)

![image](https://user-images.githubusercontent.com/1099479/35739710-c923bdea-0832-11e8-9f3b-5f61c138ff64.png)

A follow-up of https://github.com/ckeditor/ckeditor5/issues/645.

**Comment by oleq** [comment]
Slightly thicker icons
![image](https://user-images.githubusercontent.com/1099479/36264091-22d2f818-126c-11e8-80a4-5182545b6cc2.png)

**Comment by dkonopka** [comment]
Like we were talking, the current green button with save icon looks like focused state and some users can be confused. So I'm for removing the background of it.

Coloured thicker icons look really well also in inverted theme (but we need to change a bit hue of green) and this is my favorite version.

![screen shot 2018-02-19 at 15 24 34](https://user-images.githubusercontent.com/10219857/36382397-09c92c82-1589-11e8-920e-3915662e0aef.png)

**Comment by jodator** [comment]
I like the [fat version](https://github.com/ckeditor/ckeditor5/issues/810#issuecomment-365959033) of two color variant.

**Comment by scofalik** [comment]
+1 two colors, thick.
