### ISSUE TITLE
Create react app 1 guide is outdated

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#8105]
## 📝 Provide a description of requested docs changes

Currently if you go to [create-react-app@1 integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-create-react-app1) and try to follow the steps, you don't get the described results. 
`package.json` does not include any scripts, so you cannot `npm run eject`. Even if you try to run it with `node_modules/.bin/react-scripts eject` it ends with an error and the project does not contain the files that are described in the guide.

**Comment by Reinmar** [comment]
Perhaps we could replace the info about ejecting with something like:

> If you already have your configuration ejected, you can do this... If not, you will need to upgrade CRA as apparently the eject command was removed.

**Comment by pomek** [comment]
I am for removing the whole section about CRA@1 and UglifyJs (provided by the CRA@1). As for now, we have 4 different versions of the same script, and keeping all docs up-to-date becomes a time-consuming task.

I'd keep documentation for the latest and the previous major versions. 

If somebody uses older versions (that most probably aren't supported by CRA anymore), we could recommend an upgrade to (at least) supported/maintained version.

**Comment by Reinmar** [comment]
The last release of version 1.x is 3 years ago, and 2.x was released over 2 years ago.

Dropping 1.x seems reasonable. In the worst case, we can forward people to https://ckeditor.com/docs/ckeditor5/15.0.0/

**Comment by pomek** [comment]
The same problem occurs with CRA@2. As for now, you cannot create a new app using this version:

```
A template was not provided. This is likely because you're using an outdated version of create-react-app.
```

![image](https://user-images.githubusercontent.com/2270764/98345451-fa8e5a00-2014-11eb-992c-c7fc1516adfc.png)

![image](https://user-images.githubusercontent.com/2270764/98345487-067a1c00-2015-11eb-8c42-b21a97ffcc5e.png)

Works fine for CRA@3.

![image](https://user-images.githubusercontent.com/2270764/98345526-11cd4780-2015-11eb-845b-61e5d0687ec5.png)
