### ISSUE TITLE
Typos in FileDialogButtonView API docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#8110]
## 📝 Provide a description of requested docs changes

1. Go to [FileDialogButtonView#set api docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_upload_ui_filedialogbuttonview-FileDialogButtonView.html#function-set)
  
The text:  
 `Such an property becomes a part of the state and is be observable.`
I guess it should be more like:
`Such a property becomes a part of the state and is observable.` ?

**Comment by godai78** [comment]
Sorry it took so long, here's the PR: #8118. Took some time to correct a few other similar minor errors.
