### ISSUE TITLE
Improve the visibility of the "The following packages did not pass unit tests"

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8111]
## 📝 Provide a description of the improvement

The most important line here is the "The following packages did not pass unit tests", but it's quite hard to spot.

It'd be good to use some emojis and/or better styling and/or more spacing around to help with that. Perhaps even Travis has some special formatting option (similar to the tokens we used to fold sections above).

![](https://user-images.githubusercontent.com/156149/93571766-356cfd80-f995-11ea-87e1-8a44bfee5ef7.png)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Also, the wording isn't particularly correct as we also check e.g. dependencies there. Possibly, linter is also executed, etc. Something like this would be more correct:

> 🔥 The following packages have errors: 

cc @AnnaTomanek for better wording :)

**Comment by Reinmar** [comment]
> :fire: Errors were found in the following packages:

**Comment by mlewand** [comment]
> Also, the wording isn't particularly correct as we also check e.g. dependencies there

@Reinmar I just realized that the script is smart enough to tell the difference and it gives a correct sentence depending on what went wrong.

https://github.com/ckeditor/ckeditor5/blob/master/scripts/continuous-integration-script.js#L104-L112

So I guess that adding a proper emoji at the beginning of each log should do the job.

Maybe an extra line spacing after the error and `---` will also improve the visibility.

**Comment by Reinmar** [comment]
The ideas are in line with what I was thinking about, but I'd need to see this to say whether it works for me in the end.
