### ISSUE TITLE
Invalid options object (postcss)

### ISSUE THREAD

**Issue by bilalmalkoc** [ckeditor/ckeditor5#8112]
{
        devtool: 'source-map',
        performance: { hints: false },
        entry: path.resolve(__dirname, 'src/js', 'ckEditor.js'),
        output: {
            // The name under which the editor will be exported.
            library: 'ClassicEditor',

            path: path.resolve(__dirname, 'dist/ckeditor'),
            filename: 'ckeditor.js',
            libraryTarget: 'umd',
            libraryExport: 'default',
        },
        optimization: {
            minimizer: [
                new TerserJSPlugin({
                    sourceMap: true,
                    terserOptions: {
                        output: {
                            // Preserve CKEditor 5 license comments.
                            comments: /^!/,
                        },
                    },
                    extractComments: false,
                }),
            ],
        },
        plugins: [
            new CKEditorWebpackPlugin({
                // UI language. Language codes follow the https://en.wikipedia.org/wiki/ISO_639-1 format.
                // When changing the built-in language, remember to also change it in the editor's configuration (src/ckeditor.js).
                language: 'tr',
                additionalLanguages: 'all',
            }),
            new webpack.BannerPlugin({
                banner: bundler.getLicenseBanner(),
                raw: true,
            }),
        ],

        module: {
            rules: [
                {
                    test: /\.svg$/,
                    use: ['raw-loader'],
                },
                {
                    test: /\.css$/,
                    use: [
                        {
                            loader: 'style-loader',
                            options: {
                                injectType: 'singletonStyleTag',
                                attributes: {
                                    'data-cke': true,
                                },
                            },
                        },
                        {
                            loader: 'postcss-loader',
                            options: styles.getPostCssConfig({
                                themeImporter: {
                                    themePath: require.resolve(
                                        '@ckeditor/ckeditor5-theme-lark'
                                    ),
                                },
                                minify: true,
                            }),
                        },
                    ],
                },
            ],
        },
    },

Tried this: (not working)

    {
        loader: 'postcss-loader',
        options: {
            postcssOptions: styles.getPostCssConfig({
                themeImporter: {
                    themePath: require.resolve(
                        '@ckeditor/ckeditor5-theme-lark'
                    ),
                },
                minify: true,
            }),
        },
    },

**Comment by Reinmar** [comment]
Hi! You didn't mention what you see (an error, or the app does not build correctly) so it's hard for us to analyze your ticket.

However, one thing came to my mind – you may have an old version of style-loader installed (especially if you use CRA). See the info box in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#installing-missing-dependencies.

**Comment by kenianbei** [comment]
I'm getting same error, it's after updating to postcss-loader ^4.0.0:

> Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
    ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
     - options has an unknown property 'plugins'. These properties are valid:
       object { postcssOptions?, execute?, sourceMap? }
        at validate (/home/moz/Developer/anvill/ckeditor/node_modules/schema-utils/dist/validate.js:98:11)
        at Object.loader (/home/moz/Developer/anvill/ckeditor/node_modules/postcss-loader/dist/index.js:43:28)

Downgrading to 3.0.0 branch fixes it.

**Comment by danrot** [comment]
@kenianbei I've got the same error, it seems to me that `postcss-loader` changed the confguration. You can't pass the return value of `styles.getPostCssConfig` anymore directly to the options, but to the `postcssOptions` property of the `options` object:

```javascript
{
    loader: 'postcss-loader',
    options: {
        postcssOptions: styles.getPostCssConfig({
            themeImporter: {
                themePath: require.resolve(
                    '@ckeditor/ckeditor5-theme-lark'
                ),
            },
            minify: true,
        }),
    },
},
```

However, I am also using `ckeditor` in combination with [react-styleguidist](https://github.com/styleguidist/react-styleguidist), where I get the following error if I do that adjustment:

```
./node_modules/@ckeditor/ckeditor5-widget/theme/widget.css (./node_modules/postcss-loader/dist/cjs.js??ref--6-1!./node_modules/@ckeditor/ckeditor5-widget/theme/widget.css) 8:0                            
Module parse failed: Unexpected token (8:0)                                                                                                                                                                
File was processed with these loaders:                                                                                                                                                                     
 * ./node_modules/postcss-loader/dist/cjs.js                                                                                                                                                               
You may need an additional loader to handle the result of these loaders.                                                                                                                                   
|  */                                                                                                                                                                                                      
|                                                                                                                                                                                                          
> :root {                                                                                                                                                                                                  
|       --ck-color-resizer: var(--ck-color-focus-border);                                                                                                                                                  
|       --ck-resizer-size: 10px;                                                                                                                                                                           
 @ ./node_modules/@ckeditor/ckeditor5-widget/theme/widget.css 2:12-95 9:17-24 13:15-22                                                                                                                     
 @ ./node_modules/@ckeditor/ckeditor5-widget/src/widget.js                                                                                                                                                 
 @ ./node_modules/@ckeditor/ckeditor5-table/src/table.js                                                                                                                                                   
 @ ./src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js                                                                                                                            
 @ ./node_modules/react-styleguidist/lib/loaders/styleguide-loader.js!./node_modules/react-styleguidist/lib/client/index.js                                                                                
 @ ./node_modules/react-styleguidist/lib/client/index.js                                                                                                                                                   
 @ multi regenerator-runtime/runtime ./src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss ./src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/styleguidist.scss ./node_modules/react-styleguidist/lib/client/index
```

At first I thought it seems to be related to the `:root` pseudo selector, but I start thinking that it might be because of the comment (`/* ... */`) right before that... Does anybody experience similar issues?

**Comment by kenianbei** [comment]
@danrot Thanks! Updating my config to match yours allowed for a successful build with postcss 4.0. Seems like the docs should be updated to match this new requirement: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html#lets-start

**Comment by danrot** [comment]
@kenianbei You are welcome :slightly_smiling_face:

But I still get the same error as described above :sweat_smile: What is bothering me as well, I have upgraded to Postcss 8, but when I tried to output the return value of `getPostcssConfig` I still get Postcss 7 as version:

```
{
  plugins: [
    [Function (anonymous)] {
      postcssPlugin: 'postcss-import',
      postcssVersion: '7.0.35'
    },
    [Function (anonymous)] {
      postcssPlugin: 'postcss-ckeditor5-theme-importer',
      postcssVersion: '7.0.35'
    },
    [Function (anonymous)] {
      postcssPlugin: 'postcss-mixins',
      postcssVersion: '7.0.35'
    },
    [Function: walk] {
      postcssPlugin: 'postcss-nesting',
      postcssVersion: '7.0.35'
    },
    [Function (anonymous)] {
      postcssPlugin: 'postcss-ckeditor5-theme-logger',
      postcssVersion: '7.0.35'
    }
  ]
}
```

Maybe that is related? :thinking:

**Comment by air-hand** [comment]
@danrot I have faced the same error with newest packages (webpack v5, loaders, etc).

```
  "devDependencies": {
    "@ckeditor/ckeditor5-dev-utils": "^24.4.2",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^24.4.2",
    "css-loader": "^5.2.1",
    "postcss": "^8.2.10",
    "postcss-loader": "^5.2.0",
    "raw-loader": "^4.0.2",
    "style-loader": "^2.0.0",
    "webpack": "^5.32.0",
    "webpack-cli": "^4.6.0"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-basic-styles": "^27.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^27.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^27.0.0"
  },
```

```
ckeditor-test    | ERROR in ./node_modules/@ckeditor/ckeditor5-editor-classic/theme/classiceditor.css (./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/@ckeditor/ckeditor5-editor-classic/theme/classiceditor.css) 1:0 
ckeditor-test    | Module parse failed: Unexpected token (1:0)
ckeditor-test    | File was processed with these loaders:
ckeditor-test    |  * ./node_modules/postcss-loader/dist/cjs.js
ckeditor-test    | You may need an additional loader to handle the result of these loaders.
ckeditor-test    | > .ck.ck-editor{position:relative}.ck.ck-editor .ck-editor__top .ck-sticky-panel .ck-toolbar{z-index:var(--ck-z-modal)}.ck.ck-editor__top .ck-sticky-panel .ck-toolbar{border-radius:0}.ck-rounded-corners .ck.ck-editor__top .ck-sticky-panel .ck-toolbar,.ck.ck-editor__top .ck-sticky-panel .ck-toolbar.ck-rounded-corners{border-radius:
```

after added css-loader like below, it seems to be solved.
```
                    test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
                    use: [
                        {
                            loader: 'style-loader',
                            options: {
                                injectType: 'singletonStyleTag',
                                attributes: {
                                    'data-cke': true
                                }
                            }
                        },
                        'css-loader', // added this line
                        {
                            loader: 'postcss-loader',
                            options: {
                                postcssOptions: CKEditorStyles.getPostCssConfig( {
                                    themeImporter: {
                                        themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
                                    },
                                    minify: true
                                })
                            }
                        },
                    ]
```

I also tried packages specified versions by [the document](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source), there is no error if without css-loader.

**Comment by dabernathy89** [comment]
@air-hand you totally just saved my butt. I'm using Laravel Mix v6, which requires PostCSS 8. Could not figure out what I was doing wrong, but adding `css-loader` as an intermediary between `style-loader` and `postcss-loader` seems to have worked.

**Comment by piyushk96** [comment]
Thanks, @air-hand I was stuck with this issue for a very long time. Adding `css-loader` just worked for me 👍🏻

**Comment by alexrafael10** [comment]
@air-hand thank you so muchhhh <3

**Comment by rayalois22** [comment]
@air-hand Thank you very much

**Comment by Moki-19** [comment]
The solution which consists in encapsulating all the return value of `getPostCssConfig` in `postcssOptions` may not work as expected if you were passing `sourceMap` option to `getPostCssConfig` (as it will be set inside `postcssOptions` that is not a valid option schema for `post-css-loader`: https://webpack.js.org/loaders/postcss-loader/#options).

This patch takes this case in account :
```
const patchPostCssConfig = (config) => {
  const { plugins, ...rest } = config;
  return { postcssOptions: { plugins }, ...rest };
};
```

```
{
   loader: 'postcss-loader',
   options: patchPostCssConfig(styles.getPostCssConfig({/* options (including or not sourceMap) */})),
}
```
