### ISSUE TITLE
The block quote icon stands out (is too heavy)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#812]
Take a look at this zoomed out screenshot: 

![image](https://user-images.githubusercontent.com/156149/35798113-1a86a6b2-0a62-11e8-8ffd-a7055fc35bc5.png)

It's heavier than any other icon in the toolbar.

I'd also add that IMO it's kinda edgy (not rounded enough). That also stands out a bit.

**Comment by dkonopka** [comment]
What do you think about a little bit different shape?

![screen shot 2018-02-13 at 15 31 22](https://user-images.githubusercontent.com/10219857/36154848-fb51d876-10d2-11e8-9eaa-e79b3354993f.png)

**Comment by Reinmar** [comment]
Interesting direction. I think it's too small (comparing to other icons), but after you'd make it bigger it would be heavy again. Can we use a thinner style for it?

**Comment by dkonopka** [comment]
It's tricky to show the quote (as you said if I'm making it bigger it's getting bold), but this is something that looks much better than the current icon. Or we are trying with another shape of a quote?

### current blockquote icon 
<img width="635" alt="blockquote-current" src="https://user-images.githubusercontent.com/10219857/36196958-a470c90e-1172-11e8-9dce-0b1fff6fadd8.png">

### bold version
<img width="635" alt="blockquote-bold" src="https://user-images.githubusercontent.com/10219857/36197390-e1fc795c-1173-11e8-942d-581691dec096.png">


### bold bigger version
<img width="635" alt="blockquote-bold-bigger" src="https://user-images.githubusercontent.com/10219857/36197383-df1d3938-1173-11e8-8346-88913447360a.png">


### thin version
<img width="635" alt="blockquote-thin" src="https://user-images.githubusercontent.com/10219857/36197374-dc33668e-1173-11e8-9edb-71cb4509884b.png">

**Comment by pjasiun** [comment]
I prefered the first proposal.

**Comment by scofalik** [comment]
I like the "bold bigger version" proposal :) Although think version is okay too. I don't like current icon either. It is quite heavy.

**Comment by dkonopka** [comment]
Next proposals after call. It's worth noting that here we have a small disproportion between list icon because number "2" is outside grid.
 
### 1.
<img width="790" alt="blockquote-1" src="https://user-images.githubusercontent.com/10219857/36530995-d92b53ee-17bc-11e8-8880-c5dac0b90f88.png">

### 2.
<img width="790" alt="blockquote-2" src="https://user-images.githubusercontent.com/10219857/36530996-d945e6aa-17bc-11e8-89a1-d921b2dcc733.png">

### 3.
<img width="790" alt="blockquote-3" src="https://user-images.githubusercontent.com/10219857/36530997-d96019c6-17bc-11e8-82bd-8610d99138b2.png">

I would go with 3rd option.

**Comment by oleq** [comment]
Some more ideas (the original is the first one):

<img src="https://user-images.githubusercontent.com/1099479/36549923-4491ade0-17f4-11e8-8620-1d6ab28e2139.png" width="799" />

**Comment by oleq** [comment]
Two more:
<img width="798" alt="screen shot 2018-02-22 at 17 22 05" src="https://user-images.githubusercontent.com/1099479/36550169-efcb38ca-17f4-11e8-8fb4-5c0d2325f868.png">

**Comment by oleq** [comment]
Slightly more refined:
<img width="796" alt="screen shot 2018-02-22 at 17 27 46" src="https://user-images.githubusercontent.com/1099479/36550500-bd732ca6-17f5-11e8-8e77-17003b9d7132.png">

**Comment by scofalik** [comment]
I liked the idea of "hollow icon" at first sight, but it looks a bit like like two six numbers: 66. Someone might think this is something connected with inserting numbers or something. I think that idea fits the theme most and is best-looking, but a bit confusing :(.

**Comment by oleq** [comment]
I do my best to lose this "6" feel. We can either go with a solid icon (first approach) and make it lighter by reducing the size or try to play with hollow ones. Two more:

<img width="800" alt="screen shot 2018-02-22 at 17 40 29" src="https://user-images.githubusercontent.com/1099479/36551342-aee22320-17f7-11e8-9ebc-314e094a7102.png">

I think the first one looks more like a quote than "6".

**Comment by scofalik** [comment]
Shorter "tail" helps for sure.

**Comment by Reinmar** [comment]
TBH, none of the proposals convince me :D Damian's went into too "droplet" shapes. Olek's 6-ish into "66". So far, I'm starting to like the current icon more and more with time and the only one I also liked was the smaller version of the original one:

![image](https://user-images.githubusercontent.com/156149/36564163-a9ff1898-181c-11e8-9e0f-731fddcc9301.png)

Olek – is it possible to stretch this one a bit? I think that something with little radius, filled "head" and slightly longer tail might work. This will differentiate it well from "66" while keeping the right size. And to prevent it from being too heavy, the head should stay proportionally small which means that the tail must become a little longer so the overall size isn't too small... I wish I could into SVG.

**Comment by Reinmar** [comment]
After 3 more mins of looking at this we both (I and Maja) came to the same conclusion that from all the proposed icons we like the smaller version of the original icon the most. However, there may be still options to improve it:

* make the tail slightly longer (to enlarge the icon),
* make the head slightly more narrow (to reduce the weight of the icon).

**Comment by dkonopka** [comment]
### Narrow head
![blockquote-narrow-head](https://user-images.githubusercontent.com/10219857/36584694-1dc5c39a-187b-11e8-819b-c3542987080d.png)

### Narrow head & thin tail
![blockquote-narrow-head-thin-tail](https://user-images.githubusercontent.com/10219857/36584695-1de05340-187b-11e8-89cc-d3a499a965a1.png)

### Narrow head & long, thin tail
![blockquote-narrow-head-long-thin-tail](https://user-images.githubusercontent.com/10219857/36584693-1daa4a20-187b-11e8-975c-0537b19b2dee.png)

**Comment by oleq** [comment]
I think there's too much tail in Damian's mockups. So I re-adjusted my first mockup
<img width="542" alt="screen shot 2018-02-23 at 10 11 03" src="https://user-images.githubusercontent.com/1099479/36586387-e0d3d65a-1881-11e8-91d4-e8049716e7e9.png">

**Comment by oleq** [comment]
Some more adjustments.

Before:

![localhost_8125_ckeditor5-theme-lark_tests_manual_iconset html 22](https://user-images.githubusercontent.com/1099479/36586954-d7d7346e-1883-11e8-8c57-2243f1241a66.png)

<img width="494" alt="screen shot 2018-02-23 at 10 26 06" src="https://user-images.githubusercontent.com/1099479/36587007-09620b62-1884-11e8-80c5-b5421b08026b.png">


After:

![localhost_8125_ckeditor5-theme-lark_tests_manual_iconset html 21](https://user-images.githubusercontent.com/1099479/36586946-d4ea33b4-1883-11e8-89c7-7a0b96474dcc.png)
<img width="542" alt="screen shot 2018-02-23 at 10 11 03" src="https://user-images.githubusercontent.com/1099479/36587002-05cbaec2-1884-11e8-8084-f8717cecc93b.png">

**Comment by oleq** [comment]
TBH, I can't get anything better than this
<img width="532" alt="screen shot 2018-02-23 at 10 38 54" src="https://user-images.githubusercontent.com/1099479/36587536-c34a1604-1885-11e8-947c-26b23daffd49.png">
in this concept. We can either merge it or try another approach.

**Comment by scofalik** [comment]
For sure it looks better than the old version. Since a lot of variations has been proposed here I think that we can settle on something final. The last one and the one where I added a thumbs-up are looking good.
