### ISSUE TITLE
HTML to Plain text conversion

### ISSUE THREAD

**Issue by sudhird81** [ckeditor/ckeditor5#8121]
Is there any way to get Ckeditor 5 content and convert it  from HTML to plain text? 

I have tried the plugin https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html but it requires selection of content. 

**Requirement** is having ckeditor without any toolbar or controls and sending data as plain text to api call. 

**Why need ckeditor5?**
Using ckeditor as in future need to use Mention feature of it.

**Comment by Mgsy** [comment]
Hi, I'm not sure what exactly you'd like to achieve. As you refer to Remove format feature, do you want to get the data without any formatting or get the data in a plain text?

To retrieve the data as a plain text, you can use [viewToPlainText](https://ckeditor.com/docs/ckeditor5/latest/api/module_clipboard_utils_viewtoplaintext.html#viewToPlainText) helper method:

```javascript
import viewToPlainText from '@ckeditor/ckeditor5-clipboard/src/utils/viewtoplaintext';
import ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic/src/ckeditor';

ClassicEditorBuild
    .create( element )
    .then( editor => {
        // Will get the stringified content.
        console.log( viewToPlainText( editor.editing.view.document.getRoot() ) );
    } )
    .catch( error => {
        console.error( error.stack );
    } )
```

> **Requirement** is having ckeditor without any toolbar or controls

So, the best choice would be the [decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html) which separates the editing area and the toolbar. You can simply not appending the toolbar during the initialization.

> Using ckeditor as in future need to use Mention feature of it.

CKEditor 5 supports the Mentions plugin, you can read more about it in the [feature guide](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html).
