### ISSUE TITLE
Dropdown panel is clipped when at the edge of the viewport

### ISSUE THREAD

**Issue by pumpuroom** [ckeditor/ckeditor5#8126]
When the editing area is small and is at the edge of the viewport, the dropdown panel extends beyond its borders and is clipped

![Снимок экрана 2020-09-22 133124](https://user-images.githubusercontent.com/27552039/93874313-daf8d780-fcdb-11ea-828b-965f9c06f26f.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. We are aware of this issue and we are [tracking it here](https://github.com/ckeditor/ckeditor5/issues/5586). Please add there 👍  if you'd like to see it fixed sooner and also fell free to add anything you consider important. I'll close this ticket as a duplicate.
