### ISSUE TITLE
Create a block quote feature guide

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#8129]
## 📝 Provide a description of requested docs changes

We'd love to change the links to plugins in the online builder to docs (they now link to npm packages) and it looks like the block quote feature is the only one missing to accomplish this.

**Comment by godai78** [comment]
All my love has been invested in writing  
this missing sibling of the evergrowing family of CKSource docs  
for a better part of the Wednesday morning.

**Comment by godai78** [comment]
Working branch here: https://github.com/ckeditor/ckeditor5/tree/i/8129

**Comment by AnnaTomanek** [comment]
Closed in 4de0e05 :tada:
