### ISSUE TITLE
Document [skip ci] usage and its implications

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#8130]
## Provide a description of the task

We don't have the documentation on how the `[skip ci]` part should be used in our git commit message.

Now, in the past we were more keen to use `[skip ci]` whenever possible to increase our CI throughput. However, this changed recently as the CI started to test more things, like docs links etc. So lately we're more keen to use `[skip ci]` only when it's really, really safe.

### Implication

There's one serious implication: if you provide `[skip ci]` to a message commit of the last commit in your branch and create a PR for this branch **there will be no GitHub status check for CI**. This needs to be emphasized in our docs as we had cases when we didn't know why status checks are missing.

**Comment by mlewand** [comment]
On a side note we should document when we should use `[skip ci]`.

**Comment by mlewand** [comment]
On a side note we should document when we should use `[skip ci]`.

**Comment by godai78** [comment]
https://docs.google.com/document/d/1AnpTKxiAc-st9OkRKmVzMBQtszjxKV_W-UA_wtc1y-M/edit

**Comment by AnnaTomanek** [comment]
Added to the internal GitHubology article.
