### ISSUE TITLE
Migrating to CKEditor 5

### ISSUE THREAD

**Issue by GawadNikita** [ckeditor/ckeditor5#8131]
I'm working on a task where I need to migrate from CK Editor 4 to CK Editor 5.
There is a problem that I'm facing:

1. The data I want to set in the editor is a specific form of HTML. Say eg:
```
<section class="section-header">
<header>
<h1> Main Header for page </h1>
</header>
</section>
<section class="section-body-wrapper">
<div> Lorem ipsum. Some random text</div>
</section>
```

But after using the setData() what I get is 
```
<h1> Main Header for page</h1>
<div> Lorem ipsum. Some random text</div>

```
All the tags and attributes assigned to tags are lost.
Need to understand how I can handle this in CK Editor 5.
PS: The markup that I want to set is returned by API. So in my case I can not keep it static. Its as per the response returned by API.

**Comment by FilipTokarski** [comment]
Hi, CKEditor 5 has it's own data model and doesn't allow to use all the tags by default, hence it converts all unknown tags into the ones registered in [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#schema).
Here you can read more about [editor architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/core-editor-architecture.html), [editing engine ](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html) and [conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html).

**Comment by GawadNikita** [comment]
Thank you for your reply Filip. I have already checked the editor architecture and editing engine part. But the documentation did not help while implementation. I need more clarity and understanding on this.

**Comment by Mgsy** [comment]
The links that @FilipTokarski has provided are a good starting point for learning CKEditor 5 basics, so I highly recommend going through those materials. Additionally, here are a few tutorials which show how you can use those concepts in practice: 

*   [Creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)
*   [Implementing a block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html)
*   [Implementing an inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html)
*   [Preserving custom content](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html)

Additionally, you can read more about the migration from CKEditor 4 to CKEditor 5 [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html).
