### ISSUE TITLE
Migrating to CK Editor 5

### ISSUE THREAD

**Issue by GawadNikita** [ckeditor/ckeditor5#8132]
I'm working on a task where I need to migrate from CK Editor 4 to CK Editor 5.
There is a problem that I'm facing:

So CKEditor 4 has an instance object and when I went through the old code I saw at several place the developer had used the properties from that object , eg:
CKEDITOR.instances.editor1, CKEDITOR.doc.element.createFromHtml and few others.

I'm unable to find the substitute for this in your documentation. Need to understand how can implement this with CK Editor 5. Kindly help me with the same.
Thank you.

**Comment by Mgsy** [comment]
Hello, please don't create multiple tickets for one problem. Let's keep the discussion in the original issue - #8131.
