### ISSUE TITLE
Pressing backspace at the beginning of the first block should reset it to a paragraph

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8137]
## 📝 Provide detailed reproduction steps (if any)

Pressing backspace here should turn the first line into a paragraph.

![](https://user-images.githubusercontent.com/156149/94105220-1c52c980-fe39-11ea-9369-5d4ac906583d.png)

### ✔️ Expected result

The first line is turned into a paragraph.

### ❌ Actual result

The first line remains a heading.

## 📃 Other details

We already support pressing Backspace in this case (when the editor is empty):

```html
<root>
	<heading1>[]</heading1>
</root>
```

But to me, it does not really matter what's in the next line. When I press backspace here I'd expect to see a paragraph. 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
> Pressing backspace here should turn the first line into a paragraph.

Annoying as hell :smile:

**Comment by Reinmar** [comment]
Why? If it happens only in the first block of the editor. I don't mean implementing Notion's behavior when it happens in every block.

**Comment by jodator** [comment]
> Why? If it happens only in the first block of the editor. I don't mean implementing Notion's behavior when it happens in every block.

I meant that the current behavior is annoying. I'm all-in for the change.

**Comment by Reinmar** [comment]
Strongly related scenario: #7636.
