### ISSUE TITLE
Active button's style is a bit boring

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#814]
![image](https://user-images.githubusercontent.com/156149/35798699-e1c6cbb6-0a63-11e8-8304-b4dfeb8ef6a1.png)

The simple, rounded grey square looks somehow dull in comparison to these icons. Also, the gradient (which I actually don't like https://github.com/ckeditor/ckeditor5/issues/805) strengthen this, IMO.

Previously it was the same:

![image](https://user-images.githubusercontent.com/156149/35798797-2c7a63a2-0a64-11e8-8979-66584cf45642.png)

But due to a darker and plain toolbar color it matched better.

Some ideas for this style:

* remove the gradient :P
* add some gradient/box-shadow to an active button
* use slightly lighter color

---

PS. The current style looks the worst when used in a dropdown:

![image](https://user-images.githubusercontent.com/156149/35798909-72dac42c-0a64-11e8-9167-18ad0c436722.png)

**Comment by Reinmar** [comment]
One thing could be to use opacity + color so the button blends better with the gradient. Although... difference is minimal :D

![image](https://user-images.githubusercontent.com/156149/35811195-26e75ea2-0a8e-11e8-9171-7a929544972c.png)

![image](https://user-images.githubusercontent.com/156149/35811265-58a9599a-0a8e-11e8-8529-8be99aa737bd.png)

**Comment by Reinmar** [comment]
We need to remember here that there must a contrast between hover and active style of a button.

**Comment by Reinmar** [comment]
I got used to these buttons. And they are less of a problem for me once we dropped the gradient. I'd be fine with ignoring this.

**Comment by oleq** [comment]
Moved to the next iteration. We'll have more time to gather the feedback.

**Comment by Reinmar** [comment]
I got used to it. And it looks better now, when there's no gradient. So, from my POV it's ok.
