### ISSUE TITLE
Better formatting of custom errors

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8140]
## 📝 Provide a description of the improvement

Right now an error prints like this:

![](https://user-images.githubusercontent.com/156149/94132888-3784ff80-fe60-11ea-830b-1f276c6a61b6.png)

It was formatted slightly better in the past because there was a period after the message

![](https://user-images.githubusercontent.com/156149/94132979-55eafb00-fe60-11ea-9a5f-a687edc3f8a6.png)

We don't have the message now but we have to separete "Read more" from the error code somehow. Some ideas:

*   `CKEditorError: error-code | Read more: URL`
*   `CKEditorError: [error-code] Read more: URL`
*   `CKEditorError: error-code -> Read more: URL`
*   Or something without "Read more" at all

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @jodator

**Comment by jodator** [comment]
Another thing to improve - error with params.

**Comment by jodator** [comment]
And check the test for proper format: https://github.com/ckeditor/ckeditor5/pull/8124#discussion_r494218003.

**Comment by Reinmar** [comment]
> Another thing to improve - error with params.

I wonder if we could learn something from other projects here. Maybe there are some tricks that could improve the readability even further.

BTW, one of these things would be if we were able to shorten the URL as it obscures the view... But I guess this is not easily doable.

**Comment by jodator** [comment]
Custom URL shortener :wink: https://www.youtube.com/watch?v=Z57566JBaZQ. 

But we could check how to improve in other repos for sure.

**Comment by jodator** [comment]
I've played a bit with this - I'd go with a two-line message:

```
error-short-id { param: 'value" } 
Read more: https://ckeditor.com/docs/ckeditor5/latest/.../#error-error-short-id 
```

`console.log`:

![Selection_046](https://user-images.githubusercontent.com/247363/94544506-9de89400-024b-11eb-9fba-431c73571cf1.png)

`CKEditorError`:

![Selection_048](https://user-images.githubusercontent.com/247363/94544954-2ff09c80-024c-11eb-879e-0ae86cb4d417.png)

:+1:  Pros:

*   Link to documentation is always in the same position, so the "Read more" call to action stands out.
*   Optional params are close to the error id.

:-1: Cons:

*   requires a new method for console logging errors to have consistent error log formatting

**Comment by jodator** [comment]
It seems that 3 :+1: is enough :) Thanks!

**Comment by Reinmar** [comment]
Did you create a PR for this? I can see it's on review but I can't find any linked PR.

**Comment by jodator** [comment]
> Did you create a PR for this? I can see it's on review but I can't find any linked PR.

OMG Sorry - I was 100% sure that the PR was created because I've updated the PR in `eslint-plugin-ckeditor5-rules` repository (ckeditor/eslint-plugin-ckeditor5-rules#1). PR is ready here: #8218.
