### ISSUE TITLE
Code should not be copied to a new line on Enter

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8144]
## 📝 Provide a description of the improvement

Unlike bold or italic, which people seem to expect to be copied to a new line when you press Enter, `<code>` makes no sense at all. I find it very annoying when using GH Writer and writing content like this:

![](https://user-images.githubusercontent.com/156149/94144684-c2bac100-fe71-11ea-88a5-c307ea4bd2c1.png)

I was absolutely not expecting "The" to be wrapped in `<code>`.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Having `<code>` act the same way as `<link>` seems OK to me.
