### ISSUE TITLE
Backspace does not remove all blocks in particular cases

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8145]
## 📝 Provide detailed reproduction steps (if any)

1.  `<p>A</p><p>[]B</p><p>C</p><p>D</p>`
2.  Press Shift+right 3 times to select "B" and "C"
3.  Press Shift+right _one more_ time to move the end of the selection to `<p>]D</p>`
4.  Press backspace.

### ✔️ Expected result

`<p>A</p><p>[]</p><p>D</p>`

### ❌ Actual result

`<p>A</p><p>[]C</p><p>D</p>`

## Additional details

*   First affected version: 20.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
I already checked it and its a thing about replacing [https://github.com/ckeditor/ckeditor5/blob/ea4e36a0d45bd8e8451f8fb6b6c8637324028862/packages/ckeditor5-engine/src/model/utils/deletecontent.js#L87-L89](https://github.com/ckeditor/ckeditor5/blob/ea4e36a0d45bd8e8451f8fb6b6c8637324028862/packages/ckeditor5-engine/src/model/utils/deletecontent.js#L87-L89) 

with:

```
if ( !startPosition.isTouching( endPosition ) ) {
   writer.remove( writer.createRange( startPosition, endPosition ) );
}
```

**Comment by Reinmar** [comment]
BTW, typing over that selection is affected too.

**Comment by niegowski** [comment]
> BTW, typing over that selection is affected too.

Because `model.deleteContent()` is used there also.

**Comment by jodator** [comment]
Reported right after release: #8219.
