### ISSUE TITLE
Multiple new line changed to one new line in CKeditor 5 Markdown

### ISSUE THREAD

**Issue by Mekala-palaniyappan** [ckeditor/ckeditor5#8149]
I have entered multiple new lines, but what I get in window.editor.getData() is a single newline.

![Screenshot 2020-09-24 at 7 50 50 PM](https://user-images.githubusercontent.com/42611462/94157854-4f2fa880-fe9f-11ea-9ef2-ef06b2581bad.png)

**Comment by FilipTokarski** [comment]
Hi, please do not open multiple tickets for the same issue. I answered your question in https://github.com/ckeditor/ckeditor5/issues/8165 and I'm closing this as a duplicate.
