### ISSUE TITLE
Input's focus is too strong

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#815]
Now:

![image](https://user-images.githubusercontent.com/156149/35799209-50a0d3be-0a65-11e8-932e-267d7c2b387e.png)

---

After some slight reduction:

![image](https://user-images.githubusercontent.com/156149/35799553-65227116-0a66-11e8-96b3-b1b04c39dff4.png)

---

My problem with what we have now is that it's strong so it "pollutes" the space in the balloon. It starts to conflict with the border of the balloon itself. Perhaps, we could even try something lighter than what I showed in the second screenshot.

**Comment by dkonopka** [comment]
I agree it can be reduced in light theme, but we need to remember about dark theme this how it looks in Letters (open in new tab):

![screen shot 2018-02-09 at 11 19 44](https://user-images.githubusercontent.com/10219857/36023012-4ca40014-0d8b-11e8-937c-73cee5aef1d7.png)


Changed 
```css
/* +10% light */
--ck-color-focus-border: hsla(208, 90%, 72%, 1);

/* +15% light */
--ck-color-focus-shadow: hsl(209, 90%, 87%);

/* -2px blur-radius (3rd value) */
--ck-focus-outer-shadow: 0 0 1px 1px var(--ck-color-focus-shadow)
```

![screen shot 2018-02-09 at 11 23 07 copy](https://user-images.githubusercontent.com/10219857/36023164-d42d7eb6-0d8b-11e8-9359-f60f1144b7ec.png)
