### ISSUE TITLE
[Safari] UI Icons are not scalling on page zoom.

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#8152]
## 📝 Provide detailed reproduction steps (if any)

1.  Zoom in/out any editor (<kbd>Cmd</kbd>+<kbd>+</kbd>)

### ✔️ Expected result

![](https://user-images.githubusercontent.com/1232187/94162551-200d3d00-fe87-11ea-8118-a0400cf9a4b8.png)

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/94162583-27cce180-fe87-11ea-84c6-e0eedd14d923.png)

## 📃 Other details

*   Browser: Safari 14
*   OS: macOS 10.14.6
*   CKEditor version: very old, even on v15

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @oleq Didn't it work in the past? :O

**Comment by oleq** [comment]
[Known issue](https://bugs.webkit.org/show_bug.cgi?id=199236).

**Comment by niegowski** [comment]
There is a workaround - it scales properly if you set `font-size: initial` on the SVG

**Comment by oleq** [comment]
> There is a workaround - it scales properly if you set `font-size: initial` on the SVG

Which we can't because we use an arbitrary font size for icons: https://github.com/ckeditor/ckeditor5/blob/b5e8ca02b2d6d7ff8f710bd9a9472b46296ef161/packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/icon/icon.css#L15

**Comment by Reinmar** [comment]
Decision: We need to choose between resolving this issue on Safari@macOS and scaling icons automatically with the font size. We choose the latter.

**Comment by oleq** [comment]
FYI: SVG icons follow the `--ck-font-size-base` custom property.
