### ISSUE TITLE
Drop-down looks misaligned

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#816]
When there is a separator after (and before) the dropdown it looks like a border around the paragraph menu:

![screen shot 2018-02-05 at 11 36 49](https://user-images.githubusercontent.com/1166967/35801280-f76fa52a-0a6b-11e8-94fb-c651bce2e387.png)

Then, when I click on the drop-down, I expect that the panel will be aligned to that menu. The panel looks misaligned:

![screen shot 2018-02-05 at 11 36 31](https://user-images.githubusercontent.com/1166967/35801282-0270ac8a-0a6c-11e8-80d2-b6559d46104e.png)

There is no such effect when I disable separator after the headings menu because then there is no "border effect":

![screen shot 2018-02-05 at 12 07 26](https://user-images.githubusercontent.com/1166967/35801619-48b3142a-0a6d-11e8-9c7b-927f873d5307.png)

But then the arrow is more connected to the "B" icon than "paragraph". 
![screen shot 2018-02-05 at 12 07 34](https://user-images.githubusercontent.com/1166967/35801637-5f514260-0a6d-11e8-8848-217e39787800.png)

My proposals are:

1. align it to the padding, and always add the separator after and before drop-down menus to have the border effect:
![screen shot 2018-02-05 at 12 15 39](https://user-images.githubusercontent.com/1166967/35801913-5f133d7a-0a6e-11e8-957d-c77503ee625e.png)

2. Put the arrow on the left and don't use a separator to avoid "border effect":
![screen shot 2018-02-05 at 12 22 19](https://user-images.githubusercontent.com/1166967/35802155-47fa84b2-0a6f-11e8-969b-4a8e7f57b297.png)

3. Create the border the way we had it before, do the drop-down is align to it:
![screen shot 2018-02-05 at 12 06 46](https://user-images.githubusercontent.com/1166967/35802211-7957c5ec-0a6f-11e8-98d4-1b0df37417b8.png)

4. Disconnect separator form the top and bottom, so there is no border around the menu (see https://github.com/ckeditor/ckeditor5/issues/817):
![screen shot 2018-02-05 at 12 26 57](https://user-images.githubusercontent.com/1166967/35802323-f7243514-0a6f-11e8-9c54-80310c35e713.png)

I'm for option 1 or 4.

**Comment by Reinmar** [comment]
I didn't have this feeling about the dropdown. The separator's placement is indeed a bit funky, but I'm cool with that.

What I didn't like so far, though, is the style of the active button when the dropdown is opened. It's in different style than the dropdown's panel (dark bg vs light panel). The old styling (light button and light button) worked better, but back then the dropdown's button always had a border so it was a bit different situation.

**Comment by scofalik** [comment]
I have a feeling that dropdown options are floating above the dropdown button. It always looked so weird to me (didn't native Safari dropdowns looked a bit like this?). Anyway, it would be more natural if both dropdown options and button were on the same level: either add shadow to the button or "flatten" options (I am for this one).

BTW. It seems that the dropdown options box is too high (it seems like it overlays on a button a bit).

**Comment by dkonopka** [comment]
I agree that dropdown panel looks higher than dropdown button.

### Current dropdown (border-radius and position bottom: 1px)

![screen shot 2018-02-13 at 11 04 08](https://user-images.githubusercontent.com/10219857/36144308-f4f509fa-10ad-11e8-8ef0-a3e80e77a4ee.png)

### Proposal 
If we will try to change position of dropdown panel to `bottom: 0px`, and disable `border-bottom-left-radius` of button and `border-top-left-radius` of panel it looks flat and like real "panel" instead of "popup". Additionally, we can change a little bit visibility of shadow from `hsla(0, 0%, 0%, 0.2)` to `hsla(0, 0%, 0%, 0.1)`.

![screen shot 2018-02-13 at 11 27 03](https://user-images.githubusercontent.com/10219857/36145193-e5ee4266-10b0-11e8-9942-066541f8c170.png)
