### ISSUE TITLE
Pasting list inside other list results in two list types on the same level

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8160]
## 📝 Provide detailed reproduction steps (if any)

1.  Create a two-level list.
2.  Set level two style to bulleted list style (ie circles).
3.  Create a second list with numbered list styles (ie roman).
4.  Select & copy the second list.
5.  Put caret inside the first list item on level two of the first list.
6.  Paste.

### ✔️ Expected result

The styles are set to the same list style & type on every list item from level two.

### ❌ Actual result

The items pasted after the selected list item have their styles retained.

![](https://user-images.githubusercontent.com/247363/94234196-8044c300-ff09-11ea-907e-e6ff575d818a.gif)

You cannot have this effect using UI and changin list styles as we change all items on the same level when changing list style of one item (second part of the above GIF).

## 📃 Other details

*   CKEditor version: master @ iteration 36
*   Installed CKEditor plugins: ListStyles

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Uh, good that you spotted this :) Let's fix it in it37.

**Comment by pomek** [comment]
What are the expected results?
