### ISSUE TITLE
Pagination demo page separation line goes outside of the editable

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#8163]
## 📝 Provide a description of requested docs changes

Use a device with vertical display orientation.

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html
2.  Scroll so that some page break is visible.

### Expected

Line separation stays within the editable.

### Actual

Page break overflows on the right hand side.

![](https://user-images.githubusercontent.com/5353898/94250748-eb01f880-ff21-11ea-8758-68fa4f5c3e60.png)

It will mostly occur on mobile, but on desktop if you have a vertical screen you can also experience this.

**Comment by Reinmar** [comment]
WFM and no one reported such issues.
