### ISSUE TITLE
New line issue in Ckeditor 5 Markdown

### ISSUE THREAD

**Issue by Mekala-palaniyappan** [ckeditor/ckeditor5#8165]
**Expected** :

When we give the editor output as an input for the editor, it should act as the same.

**Result** :

I gave multiple lines between two lines, created the data. And then give the same output as an input for the editor, it removes multiple lines, considering as one new line.
**Note**: Considering **Shift+Enter** is the new line creation,  when we give multiple new lines using **enter** it considering one new line.

![Screenshot 2020-09-25 at 3 32 53 PM](https://user-images.githubusercontent.com/42611462/94255440-e18a8780-ff45-11ea-8c81-8f41c7f37b1c.png)

**What I need**:

1. We can generate multiple new lines using the **enter** key
2. Need to accept editor output as an input for the editor, it should work.

Waiting for the reply!

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not able to reproduce this issue. Every time I set the data that was taken from the editor, I get the expected results ( which contain new lines ). I suspect this might be some problem with your implementation, maybe you use some additional, custom plugins? Anyway, to look into this issue further, we'll need more information ( editor config, plugins used, step by step description, etc. ).
