### ISSUE TITLE
Reduce the amount of commits visible during generating the changelog

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#8166]
Right now the tool prints all commits with their messages since an old commit in the past. This way the number of commits visible is huge. It would be perfect if the tool can filter out all "internal" commits there were part of a PR and print only those that were made directly on `master` or are merge commits.

I'm not sure though if that's doable.

**Comment by mlewand** [comment]
@ma2ciek please verify if that's the case, if not then please close the issue. Otherwise provide us with some output.

**Comment by mlewand** [comment]
It's been few days since last activity, I'll close this issue for now assuming that it is no longer bothering us. In case it still is, feel free to reopen it.
