### ISSUE TITLE
Provide an option to skip links in the changelog generator for monorepo packages

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#8167]
Links to private packages don't make sense, hence we could have an option to skip attaching links and paste the plain text instead.

**Comment by pomek** [comment]
The feature works well for [generating the changelog for a single package](https://github.com/ckeditor/ckeditor5-dev/blob/67567dcb6da6ff1d69d1e2ec06c507c35c392f88/packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js#L42).

The option is called [`options.skipLinks`](https://github.com/ckeditor/ckeditor5-dev/blob/67567dcb6da6ff1d69d1e2ec06c507c35c392f88/packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js#L32). It hides commit links (`(commit)` part in the changelog entry) and compare links (the header, the version number is a link).

What we need to do in such a case:

1. [Add the new option in the docs (`options.skipLinks`)](https://github.com/ckeditor/ckeditor5-dev/blob/67567dcb6da6ff1d69d1e2ec06c507c35c392f88/packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js#L31-L58)
2. [Add new options in the `writerContext` object](https://github.com/ckeditor/ckeditor5-dev/blob/67567dcb6da6ff1d69d1e2ec06c507c35c392f88/packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogformonorepository.js#L274-L283):
    ```js
	{
		skipCommitsLink: Boolean( options.skipLinks ),
		skipCompareLink: Boolean( options.skipLinks )
	}
	```
3. Test the solution:
    * Update the changelog script for v5 (add the `skipLinks: true`): https://github.com/ckeditor/ckeditor5/blob/b5e8ca02b2d6d7ff8f710bd9a9472b46296ef161/scripts/release/changelog.js#L15-L36
    * Execute `yarn run changelog`
    * Check whether the generated changelog for the latest version does not include `(commit)` at the end of each entry.
    * Rollback all changes.

**Comment by psmyrek** [comment]
To simplify testing of this solution, the `releaseBranch` option can be changed to `master`, which may already have many more commits than `release` branch.
