### ISSUE TITLE
can't set ckeditor toolbar location at bottom

### ISSUE THREAD

**Issue by nikhil-ponduri** [ckeditor/ckeditor5#8168]
I am trying to put the toolbar in bottom of my editor. As per the docs I have passed toolbarPosition:bottom property to config but seems like it didn't work. Here is the code
```
import React from 'react';
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

function App() {
  return (
    <div className="App">
      <CKEditor
        editor={ClassicEditor}
        data="<p>Hello from CKEditor 5!</p>"
        onInit={editor => {
          // You can store the "editor" and use when it is needed.
          console.log('Editor is ready to use!', editor);
        }}
        onChange={(event, editor) => {
          const data = editor.getData();
          console.log({ event, editor, data });
        }}
        config={{
          toolbarLocation: 'bottom'
        }}
      />
    </div>
  );
}

export default App;

```
but still the toolbar was placed on top

![](https://i.stack.imgur.com/0fuG8.png)
Any help would be really thankfull

**Comment by Mgsy** [comment]
Hi, in your case I'd recommend using the decoupled editor, as it has a separated toolbar and the editable, so you could style it the way you want. Please, read more about it in [our documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html#document-editor).

**Comment by kyle-ssg** [comment]
This can also just be done via CSS, building on 

```
.ck.ck-editor {
    display: flex;
    flex-direction: column-reverse;
}
```

**Comment by AliAbbasTX** [comment]
> This can also just be done via CSS, building on
> 
> ```
> .ck.ck-editor {
>     display: flex;
>     flex-direction: column-reverse;
> }
> ```

But in mobile view, the dropdown at the end of the toolbar (if there are more options), it shows on the bottom of the toolbar. The expect behavior: the dropdown menu should appear above the three-dots menu.
![image](https://github.com/ckeditor/ckeditor5/assets/139323346/2c4aaafe-dc4c-40d5-89a6-8929c03f0a6e)
