### ISSUE TITLE
How can i trigger ImageUpload event out of the editor?

### ISSUE THREAD

**Issue by Jungle2036** [ckeditor/ckeditor5#8169]
## Provide a description of the task

![image](https://user-images.githubusercontent.com/59079450/94353598-7c4da800-00a5-11eb-9054-64e4c7944b23.png)
![image](https://user-images.githubusercontent.com/59079450/94353622-c33b9d80-00a5-11eb-9c6b-622ad3efa01d.png)

**Comment by utsabc** [comment]
Hello @Jungle2036  I'm not sure what is the exact question is but  I am assuming that you want to add the base64image 
(/other) upload adapter to ck-editor build you are trying to integrate.

For this you need to add it as plugin and create a custom build and then import it into your project.

Exact guide can be found here
[Plugin docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)

**Comment by Mgsy** [comment]
Hi @Jungle2036, it would be great if you could tell us more about your issue and provide some meaningful description. From what I can see on your screenshots and the code, I assume that you'd like to have an external button which triggers upload in the editor. If so, you can use [imageUpload command](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageupload_imageuploadcommand-ImageUploadCommand.html) and execute it after clicking on your external button. Here's a sample code:

```javascript
editor.execute( 'imageUpload', {
	file: [
		file1,
		file2
	]
} );
```
