### ISSUE TITLE
Unable to update Collection after Adding it to Editor Config

### ISSUE THREAD

**Issue by harsh201** [ckeditor/ckeditor5#8172]
## Unable to update Collection after Inserting it to Editor Config
I am trying to create a new plugin where the plugin is a dropdown and the item definitions are fetched dynamically from backend service. And I want to use the item definitions, fetched from backend, to be used while inserting the new section in editor.

My Plugin Structure is:
- widget
  - widget.js
  - widgetediting.js
  - widgetcommand.js
  - widgetui.js

_What steps should be taken to fulfill the task?_
- Create a property in widgetediting of type collection
- Add it to editor.config
- Fetch asynchronously the values from server, in widgetui, and add it to collection retrieved from editor.config and pass same collection to addListToDropdown
- The list here is always empty.

_What works_
- Create a property in widgetui of type collection
- Add it to editor.config
- Fetch asynchronously the values from server, in widgetui, and add it to collection retrieved from editor.config and pass same collection to addListToDropdown
- This one works perfectly for rendering using the collection but when I try to retrieve it from editor.config, it it comes as undefined.

## 📃 Other details
I have tried all other combinations of initializing collection in widgetediting and trying to use it in widgteui but nothing works and to my dismay even fetching from same class after setting the value returns empty collection.

Method used for setting:
``` javascript
this.editor.config.define('documentComponent', {
        components: this.components,
        itemDefinitions: this.itemDefinitions,
      });
```
Method used for retrieval:
``` javascript
editor.config.get('documentComponent.itemDefinitions')
```

**Comment by jodator** [comment]
Hi @harsh201! At this moment we do not support dynamic nor asynchronous configurations. you can track this issue here: #7383.

For your problem:

1.  You could fetch your data asynchronously and then feed it to the editor config when using the create method.
2.  Store the asynchronous data outside the editor config.
3.  Update the config using `editor.config.set()`.

The `editor.config.define` is used to define default data. It is not meant to store references as we clone the values on return. This is done to prevent accidental config value override outside `get()` and `set()` methods.

Alternatively, you could try using callback (AFAIR we do not clone functions):

```javascript
this.editor.config.define('documentComponent', {
	components: () => this.components,
	itemDefinitions: () => this.itemDefinitions,
});
editor.config.get('documentComponent.itemDefinitions')()
```

**Comment by harsh201** [comment]
Thanks! That worked. 
Slightly digressing from the issue, I want to add the HTML elements based on the id selected above and I am trying to do that in widgetcommand. I looked at the [FAQ page](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#where-are-the-editorinserthtml-and-editorinserttext-methods-how-to-insert-some-content) but since command creates ands appends new element, I am a little confused on how to write the Model Fragment here. Also is this the right place to do it or I should be handling it in widgetui?

**Comment by harsh201** [comment]
Thanks for the help. I will open another ticket for my question.
