### ISSUE TITLE
Not possible to use Block Indent Feature with custom headings

### ISSUE THREAD

**Issue by antoniolucasnobar** [ckeditor/ckeditor5#8177]
## 📝 Provide detailed reproduction steps (if any)
1. Create custom header as defined in [Headings](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html) page.
2. install block indentation plugin, as stated in [its page](https://ckeditor.com/docs/ckeditor5/latest/features/indent.html)
3. Select the custom the created custom header 
4. Try to use the indent feature

### ✔️ Expected result

I exptect to be able to use the block indent feature with Custom Headers

### ❌ Actual result

Both buttons are never enabled, so I can not use this feature

## 📃 Other details

Looking into the [source](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-indent/src/indentblock.js#L82-L83), I saw the indent block feature only enable itself to knownElements:
```js
// Enable block indentation by default in paragraph and default headings.
const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
```

This way, we can not use this feature with any custom Headers.

A simple change can allow that. Changing the above line to:
```js
// Enable block indentation by default in paragraph and default headings.
const options = editor.config.get( 'heading.options' );
const headings = options.map(option => option.model);
const knownElements = headings || [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
```
and voilá, block indent works for all defined headers. Another option would be to have a config option, but I think it would only to double the config between headers and blockindent. 

Maybe we do not need the last line, once the [headings plugin](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-heading/src/headingediting.js#L39-L47) always set the heading options. But if the user remove the heading plugin, I do not know the results of that.

Please, let me know if this is the way to fix this. I can make a PR, if you folks approve it. If not, please tell me what should be the solution

   * Browser: Firefox 80.0
   * OS: Linux mint 19.3
   * CKEditor version: 22.0
   * Installed CKEditor plugins: Essentials, Alignment, Paragraph, Heading, List, Bold, Italic, Indent, Outdent

As a final note, the link to see the code at the end of the [contribute section of block indent feature](https://ckeditor.com/docs/ckeditor5/latest/features/indent.html#contribute) is pointing to the font plugin, not the indent plugin.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, indeed, custom headings are not supported by the indent block feature, as heading elements are hardcoded. Your solution seems to be a good direction, so it would be great if you could prepare a PR with fix and tests, our team will be happy to review it. Thank you for your contribution!

**Comment by antoniolucasnobar** [comment]
Hello @Mgsy 
the PR is ready for someone to look at it. 

I do not know to whom should I send the signed CLA. Could you help me with this?

And if you need anything to change in the PR, please let me know.

Best Regards.

**Comment by antoniolucasnobar** [comment]
CLA e-signed.

**Comment by Mgsy** [comment]
> CLA e-signed.

Great, thanks! We will review your PR soon :)
