### ISSUE TITLE
Import from word document

### ISSUE THREAD

**Issue by jenniferhan90** [ckeditor/ckeditor5#8180]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

There is a importFromWord button, click the button will open file browser to let the user select a word doc, after selected, the doc content will be inserted into the editor.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by edoversb** [comment]
👍

**Comment by jainkn202** [comment]
@edoversb , How we can implement this , import of document? any referance ?

**Comment by Reinmar** [comment]
It has been released as a premium feature: https://ckeditor.com/import-from-word/
