### ISSUE TITLE
The Paste from Word demo could have more features

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#8181]
I was trying to check how well our list styles handle Paste from Word and was redirected to a different sample:

<img width="857" alt="Screen Shot 2020-09-29 at 11 01 47 AM" src="https://user-images.githubusercontent.com/545175/94537001-362e4b00-0243-11eb-88b8-b1932bcec859.png">

In the recommended "Paste from Word" sample, list styles are not available:

<img width="123" alt="Screen Shot 2020-09-29 at 11 01 54 AM" src="https://user-images.githubusercontent.com/545175/94537057-39c1d200-0243-11eb-971e-6c6b1aab217c.png">

**Comment by godai78** [comment]
Like this?
![Screenshot 2020-10-27 at 07.09.28.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/dfa31307-cee3-4d6d-bf86-0233800c6d44)

I think we could use some text already inside the demo, I dunno how it happened I overlooked this being so sad and ugly, I'll come up with some pasting story or a Word paragraph and will commit it today.

**Comment by godai78** [comment]
Working branch: https://github.com/ckeditor/ckeditor5/tree/docs-pastefromoffice-demo

**Comment by godai78** [comment]
I decided to add two different demos to both paste from... guides. They are the same demo from the technical point of view, but the contents are adapted to the guides. This will nicely add to the paste plaintext guide once it is merged.

**Comment by godai78** [comment]
PR: #8349

**Comment by AnnaTomanek** [comment]
This issue is (was) blocked by #8080 - this bug caused the list style to not be preserved when pasted from Word. You should actually see this if you tested the new list style feature in the paste from Office guide, @godai78 and @Mgsy :wink: 

The fix has just been merged to `master` and so, this will start working in the next editor version. This means that the documentation change should also land in `master`, not `stable`, as it will be valid for the next editor version that we will release.

**Comment by godai78** [comment]
I rebased it just now.

**Comment by AnnaTomanek** [comment]
Did you merge `master` into your branch and test if the list styles work in your branch?

**Comment by godai78** [comment]
Can I please ask @ckeditor/qa-team to check this? Have no access to Word, can't test myself...

**Comment by FilipTokarski** [comment]
After merging `master` into `docs-pastefromoffice-style` and building docs, it looks like it works ok. Custom list styles are preserved when pasting into `Paste from Word` demo 👍
