### ISSUE TITLE
CKEditor - Changing the text to bold or deleting the text takes around 50 seconds and a warning message appears

### ISSUE THREAD

**Issue by JamesTester09** [ckeditor/ckeditor5#8185]
## 📝 Provide detailed reproduction steps (if any)

1. insert a text with around 35.000 charakters or more into the CKEditor
2. mark the whole text
3. change the text style to bold/ delete the whole text at once

### ✔️ Expected result

text ist changed to bold immediately/ text is deleted immediately

### ❌ Actual result

Changing the text to bold or deleting the text takes around 50 seconds and a warning message ("a website slows down your browser") appears in Firefox.

## 📃 Other details

* Browser: Mozilla Firefox 81.0
* OS: Windows 10
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this issue and [we'll track it here](https://github.com/ckeditor/ckeditor5/issues/8188). Please feel free to add there anything you consider important. I'll close this one as a duplicate.
