### ISSUE TITLE
Formatting large content freezes the editor

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#8188]
## 📝 Provide detailed reproduction steps (if any)

1. Add some large content to editor ( I'm using the one from [pagination demo](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html#demo) )
2. Select all
3. Change font size/ apply bold / apply some other formatting

### ✔️ Expected result

Formatting happens immediately.

### ❌ Actual result

Editor freezes, sometimes for more than ~30 seconds:  
  
![0_freeze1](https://user-images.githubusercontent.com/34380544/94653422-d778d800-02fb-11eb-95e1-20cda022bb6d.gif)

## 📃 Other details

* Browser: Chrome, Firefox
* On Safari the freeze is almost unnoticeable
* CKEditor version: old issue, happens even on v15

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Can you reproduce it also in the [pagination demo](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html#demo)? I've checked changing font size and it works as expected.

![](https://user-images.githubusercontent.com/20988892/95055061-0a9fda80-06f3-11eb-8b5c-5d36448b6b67.gif)

**Comment by FilipTokarski** [comment]
For me, it still freezes on `export-pdf`, `export-word` and `pagination` demos

**Comment by mlewand** [comment]
Same for me I can reproduce it on the default content of pagination demo https://ckeditor.com/docs/ckeditor5/23.1.0/features/pagination.html#demo

**Comment by Reinmar** [comment]
![image.png](https://images.zenhubusercontent.com/5762b11cbf93871ccd9cb8a8/67357358-7e99-49d3-9b96-8c36a5dc210a)

It seems that the post fixers are causing this again. It'd be good to check if this is related to our dear DocumentSelection#markers collection or something else. And if it's something else, whether there's some low-hanging fruit.

**Comment by Reinmar** [comment]
TODO:

*   Check whether this is triggered by enabling pagination.
*   Check this on latest master as we resolved the markers issue already.
*   Check what's the origin of that `(anonymous)` that takes 90% of the time. Look for low hanging fruits.
