### ISSUE TITLE
How to add custom attributes using custom upload adapter?

### ISSUE THREAD

**Issue by dzpt** [ckeditor/ckeditor5#8192]
I want to put few extra attributes to the img tag while using custom upload adapter like this

    <img data-id='123' src='....' />

Since the [upload API][1] only accepts Promise object with uploaded urls, i don't know how do i do it.

    {
    	default: 'http://server/default-size.image.png',
    	'160': 'http://server/size-160.image.png',
    	'500': 'http://server/size-500.image.png',
    	'1000': 'http://server/size-1000.image.png',
    	'1052': 'http://server/default-size.image.png'
    }

  [1]: https://ckeditor.com/docs/ckeditor5/latest/api/module_upload_filerepository-UploadAdapter.html#function-upload

**Comment by Mgsy** [comment]
Hi, thanks for the report. Actually, we have a [feature request](https://github.com/ckeditor/ckeditor5/issues/5204) for custom attributes in upload adapters (with a proposed solution which might interest you), so I'm closing it as a duplicate.
