### ISSUE TITLE
Spacing in the toolbar and buttons

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#820]
I have a feeling, that spacing between icons is too small. Toolbar feels crowded, compressed, narrowed. I feel that in the old theme there was just enough "air" between icons.

You can see how those changed here: https://user-images.githubusercontent.com/1099479/35739226-3d784046-0831-11e8-9528-ed16a9df86f3.gif

I also feel like it wouldn't be bad if the toolbar was a tad higher (like it was). Although that might look bad with new dropdown design.

**Comment by dkonopka** [comment]
I had the same feelings working on Letters. Spacing is important especially in the balloon toolbar where for example we have only four buttons (bold, italic, link, comment). 

I think we can easily enlarge padding of buttons (without changing icon size) from:
 `--ck-spacing-tiny (0.15em)` to `0.25em`

### Current padding 0.15em for buttons
![padding-015](https://user-images.githubusercontent.com/10219857/35911954-8b8629ce-0bfb-11e8-98a8-8654f5a5fb5c.png)

### Proposal padding 0.25em
![padding-025](https://user-images.githubusercontent.com/10219857/35911966-939b1dcc-0bfb-11e8-892f-42133fce8b62.png)

**Comment by Reinmar** [comment]
After a discussion with @oleq and @dkonopka  I changed the title of this ticket to also cover spacing inside buttons and all types of spacing around buttons (and not only spacing between buttons).

One of the ideas (which @pjasiun brought) was to limit the spacing between toolbar and icons to have more "padding-less" effect:

![image 7](https://user-images.githubusercontent.com/156149/36209691-bbb66f4a-119c-11e8-8216-29e5cc2db040.png)

We can also add spacing inside buttons (around icons):

![image](https://user-images.githubusercontent.com/156149/36209876-42754b1e-119d-11e8-8d67-4830ca5166d7.png)


To compare, this is the current state:

![image](https://user-images.githubusercontent.com/156149/36209847-2bf93850-119d-11e8-8875-00e61cb8172c.png)

**Comment by oleq** [comment]
Unfortunately making the spacing around the buttons is not an option because it starts looking weird in balloons which have arrows. Check out my previous [comment](https://github.com/ckeditor/ckeditor5/issues/645#issuecomment-362608165) (section "Paddings in the UI").
![image](https://user-images.githubusercontent.com/1099479/36212435-41821460-11a4-11e8-9dff-48b33d652b76.png)
