### ISSUE TITLE
Should table-cell post-fixer should be a model post-fixer?

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8200]
## Provide a description of the task

The table cell (paragraph) post fixer:

*   ensures proper **view** structure in the editing view
    *   single `<paragraph>` without any attributes must be rendered as `<span>` because we need to have 1:1 model-view-mapping as this makes editing easier. This is because we support "data" tables where single paragraph content is converted directly into a table cell in data
    *   in other cases, it should be `<p>`
*   is executed for **model** changes

The introduction of `Differ.refresh()` introduced infinite post-fixer loop when it returned `true`. Returning `true` is needed to indicate that **model** changed so other model post-fixer should be re-run to check if the **model** state still needs a post-fixing (#1936).

However, this post-fixer does not change the **model**. It only changes the **view**. Today, I do not remember exactly why we needed to go this path. It might be due to access to the differ (rather not) or checking this rule on the **model** level.

**Comment by niegowski** [comment]
If some handler does not modify the model then it should listen to `editor.model.document.on( 'change:data' )` because it's still before the downcast starts.
