### ISSUE TITLE
Support triggerBy of deeply nested elements

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8201]
## 📝 Provide a description of the improvement

The first implementation of the `triggerBy` (#7956) assumes that `"insert"` and `"remove"` changes happen directly inside the parent object.

This simplification can be overcome by allowing any `parent > child` change to trigger a `parent` reconversion.

For instance in tables a model tree is: `table > tableRow > tableCell`. So this issue should allow reconversion of a table on `tableCell` insert to / remove from a `tableRow`.

To consider:

*   For sure only the first parent of type should be refreshed.
*   Do we need this?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
DUP #10294 and #10360
