### ISSUE TITLE
Text node with attribute is duplicated in slot conversion demo

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8203]
## 📝 Provide detailed reproduction steps (if any)

1.  Select the whole paragraph inside "slot"
2.  Set attribute (ie bold)
3.  Trigger reconversion (ie by changing attribute on box) 

### ✔️ Expected result

bolded text is not reconverted.

### ❌ Actual result

The bold is re-converted.

![](https://user-images.githubusercontent.com/247363/94906246-6aea0e80-049e-11eb-91c5-bf88960be533.gif)

Note: Happens only when text is fully covered, below it works OK:

![](https://user-images.githubusercontent.com/247363/94906357-a1278e00-049e-11eb-9777-e240eacb0992.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Fixed by rewriting the PR [#8099](https://github.com/ckeditor/ckeditor5/pull/8099).

**Comment by jazzonaut** [comment]
This is still an issue as of version 29.1.0
