### ISSUE TITLE
Raw HTML embedding

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8204]
## 📝 Provide a description of the new feature

An idea of the feature is the ability to paste any HTML markup to the editor that will be displayed as a widget in the editing area and the raw HTML in the output data.

View:

```html
<p>Paragraph</p>
<div class="ck-widget">
<!-- HTML Markup -->
</div>
```

`editor.getData()`

```html
<p>Paragraph</p>
<!-- HTML Markup -->
```

Most probably, in the view, we will generate a preview that the user will not be able to interact with.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
I think gathering usage ideas would be awesome. The first thing that came to my mind are:

*   Some HTML snippets taken from other sites. Sometiemes, you can embed a piece of code - similar to `MediaEmbedd` but you could paste any content. I can think only of YouTube's "embed" in the share menu as an example (much better would be media embed for this) but a similar "embed on your webpage" is also available from other sites.
*   Google AdWords snippets (ad boxes). It _might_ be useful to allow users to insert an ad box inside an article.

This rise a question - should we allow JS in there? If yes - document it as a potential security risk.

**Comment by pomek** [comment]
> This rise a question - should we allow JS in there? If yes - document it as a potential security risk.

The same could happen with `iframe`. However, the `script` tag is more dangerous I guess. So the question is, should we filter (somehow) the pasted HTML?

**Comment by Comandeer** [comment]
Much sites should be able to be embedded using OEmbed or services like iframely → https://iframely.com/embed/https%3A%2F%2Fblog.comandeer.pl%2F

Additionally nearly every kind of embed uses JS in some form (see the example above), so stripping JS out of the pasted content could make the whole thing pretty useless. At the same time keeping JS can be dangerous…

**Comment by Reinmar** [comment]
Notes from my sync with @pomek: 

*   Now: Handling `<div class="raw-html-embed">`.
    *   Figure out a good class name.
    *   Do we need a `<figure>`?
        *   If someone wants to embed an iframe with a video, then perhaps we could.
        *   If a script tag, then definitely not...
        *   So, in case of a so low-level feature as this one, it's probably best to leave this to the user (which, in many cases, will be some developer). Let's keep in mind that this is a feature targetted at slightly more advanced users.
*   Future: Handling any element without a wrapper in the data.
*   XSS:
    *   Consider using an HTML sanitizer.
        *   [https://www.npmjs.com/package/sanitize-html](https://www.npmjs.com/package/sanitize-html) (MIT)
        *   [https://github.com/cure53/DOMPurify](https://github.com/cure53/DOMPurify) (MPL or Apache – are these ok?)
    *   If we won't be able to use an HTML sanitizer for any reason, then:
        *   Strip `on*` attributes.
        *   Strip `<script>` tags.
        *   Secure `javascript:` links, iframe src, image src, etc.
    *   Recommend CSP settings in the feature guide. Explain that this feature allows embedding any HTML and it's not possible to fully ensure that the user didn't paste something unsafe. Therefore, this feature should be used with caution. OTOH, if we'll use a sanitizer and recommend CSP, then maybe we don't need to warn anyone further.
    *   Add a config option `noPreviews` that'd solve this issue fully.
    *   Consider adding a note in the embed dialog saying that you should not paste HTML from untrusted sources.
*   Should we use a widget mask to block user interaction?
*   TODO:
    *   UI 💎

**Comment by pomek** [comment]
How do we want to call the new package? 

- `ckeditor5-html-embed` (similar to `ckeditor5-media-embed`)
- `ckeditor5-raw-html`
- `ckeditor5-html-snippet`

I don't know.

**Comment by Reinmar** [comment]
> ckeditor5-html-embed (similar to ckeditor5-media-embed)

:+1:

**Comment by Reinmar** [comment]
Docs: We must mention clearly and visibly that this is a special feature.

**Comment by pkwasnik** [comment]
Proposition of the UI: after clicking the button, put textarea in the editor right away. There will be two tabs: "Raw HTML" and "Preview" (ofc icons will looks better), so user could edit HTML inside an editor and quickly see preview.

![](https://user-images.githubusercontent.com/16957311/95749365-bf11a180-0c9b-11eb-8937-c1a91bf291e9.png)

**Comment by pomek** [comment]
First results of the conversion. It works.

![image](https://user-images.githubusercontent.com/2270764/95830363-d4d4a480-0d37-11eb-89ee-bb2ef93c2186.png)

However, there are my 3 cents:

- When upcasting an element, there is no DOM reference to the upcasted element (I wanted to use `element.innerHTML`). Instead, I used [`view.stringify()`](https://github.com/ckeditor/ckeditor5/blob/0e6b3edd69039f78ca38fa45649824b2e789ca3b/packages/ckeditor5-engine/src/dev-utils/view.js#L246) on element's children.

- While the conversion process, the results of [`view.stringify()`](https://github.com/ckeditor/ckeditor5/blob/0e6b3edd69039f78ca38fa45649824b2e789ca3b/packages/ckeditor5-engine/src/dev-utils/view.js#L246) and [`view.parse()`](https://github.com/ckeditor/ckeditor5/blob/0e6b3edd69039f78ca38fa45649824b2e789ca3b/packages/ckeditor5-engine/src/dev-utils/view.js#L338) cannot be used in the [`DowncastWriter.insert()`](https://github.com/ckeditor/ckeditor5/blob/829b200ed01448586fc60ab835d727fa0e6c663b/packages/ckeditor5-engine/src/view/downcastwriter.js#L671) function because the document fragment (returned by the `parse()` function) contains `view.Element`s that [cannot be inserted to other elements](https://github.com/ckeditor/ckeditor5/blob/829b200ed01448586fc60ab835d727fa0e6c663b/packages/ckeditor5-engine/src/view/downcastwriter.js#L1914).

- `RawElement` cannot be passed as an argument to [`toWidget()`](https://github.com/ckeditor/ckeditor5/blob/f729c2f7fdd07e6d9f039c5b5f40823eec4364b2/packages/ckeditor5-widget/src/utils.js#L94) function so I needed to wrap it in additional container.

- Since the above, I used the container element for marking the editing data as a widget, and the raw element for embedding the HTML. https://github.com/ckeditor/ckeditor5/blob/eebe876cb59d00738cd6293cc7293afaca0414e2/packages/ckeditor5-html-embed/src/htmlembedediting.js#L72-L87

I guess the concept of the UI is required in order to continue work on the feature.

**Comment by pomek** [comment]
A question. [`sanitize-html`](https://www.npmjs.com/package/sanitize-html) allows customizing its behavior by specifying the options object as the second argument.

We can provide a default configuration that the end-users could modify in order to match their needs.

The question is – should we?

**Comment by Reinmar** [comment]
> The question is – should we?

That depends on whether you see a use case for that. And it's easier to start with no option, that's for sure.

**Comment by Reinmar** [comment]
> *   Since the above, I used the container element for marking the editing data as a widget, and the raw element for embedding the HTML.

:+1: 

> *   When upcasting an element, there is no DOM reference to the upcasted element (I wanted to use `element.innerHTML`). Instead, I used [`view.stringify()`](https://github.com/ckeditor/ckeditor5/blob/0e6b3edd69039f78ca38fa45649824b2e789ca3b/packages/ckeditor5-engine/src/dev-utils/view.js#L246) on element's children.

You can use an instance of HtmlDataProcessor to turn a view structure into a string.

**Comment by Reinmar** [comment]
> A question. [`sanitize-html`](https://www.npmjs.com/package/sanitize-html) allows customizing its behavior by specifying the options object as the second argument.

We discussed this f2f and the problem is that the default options of sanitize-html strip, among others, iframes and inline styles.

It is highly configurable, though. Same for DOMPurify – it also strips iframes by default, although keeps inline styles.

In our case, stripping inline styles, iframes, video elements, etc. would make the preview feature quite useless. Therefore, we'd need to loosen the default settings. However, if we change anything we risk allowing for a bit too much. So, we need to be very careful with that and test the final solution ourselves.

Things that should be previewable to make the preview useful:

*   iframe, video, audio elements
*   most HTML elements (via a whitelist)
    *   including: spans, divs, section, article, aside, tables, images, etc. – everything that's a reasonable content
    *   excluding: script, style, link, etc.
*   SVG elements?
*   inline styles
*   what else?

Things that should not be allowed (other than obvious things):

*   the style tag, all things that would normally be used in `<head>`,
*   what else?

Let's try to configure sanitize-html and DOMPurify to these requirements and test both with payloads from some XSS database.

**Comment by pomek** [comment]
Should we accept the `controls` attribute for `video`/`audio` tags?

![image](https://user-images.githubusercontent.com/2270764/96103181-abeb1580-0ed7-11eb-99e1-a7c428ed3eae.png)

**Comment by pomek** [comment]
What should we do with `form` and input elements?

```html
<form action="/my-handling-form-page" method="post">
 <ul>
  <li>
    <label for="name">Name:</label>
    <input type="text" id="name" name="user_name">
  </li>
  <li>
    <label for="mail">E-mail:</label>
    <input type="email" id="mail" name="user_email">
  </li>
  <li>
    <label for="msg">Message:</label>
    <textarea id="msg" name="user_message"></textarea>
  </li>
 </ul>
</form>
```

ATM, I would prefer to do the same that the sanitizer does (remove):

![image](https://user-images.githubusercontent.com/2270764/96105408-48161c00-0eda-11eb-83a6-9151a66f3ebe.png)

**Comment by oleq** [comment]
## UI/UX proposal

I'm for the inline editing strategy, as [suggested](https://github.com/ckeditor/ckeditor5/issues/8204#issuecomment-707106317) by @pkwasnik. It sounds simple and if we pull it off this will lay the groundwork and pave the way for the [code snippet feature](https://github.com/ckeditor/ckeditor5/issues/5769) (editing in a black-box inside editor content but beyond engine's reach).

But first, let's see if there are some serious blockers in this approach.

## Views

### Adding and editing the embed

![](https://user-images.githubusercontent.com/1099479/96117359-45232780-0eea-11eb-8a90-ed6d2df1f3c0.png)

### Previewing the raw content

![](https://user-images.githubusercontent.com/1099479/96117378-4e13f900-0eea-11eb-9d1b-862dea144216.png)

### UX enhancements related to sanitization

![](https://user-images.githubusercontent.com/1099479/96117406-5704ca80-0eea-11eb-8b86-adba3ce96401.png)

## Risks

*   The toolbar icon may be a challenge. We already used both designs that would make sense so we need to come up with some new idea

![](https://user-images.githubusercontent.com/1099479/96118752-3ccbec00-0eec-11eb-82cc-751d3a43a71a.png)

*   I guess we need to have [this issue about excluding DOM events in widgets resolved](https://github.com/ckeditor/ckeditor5/issues/4600) to avoid surprises in the `<textarea>`.
    *   Does it address issues like using <kbd>Ctrl</kbd>+<kbd>A</kbd> in `<textarea>`?

**Comment by Reinmar** [comment]
> I guess we need to have [this issue about excluding DOM events in widgets resolved](https://github.com/ckeditor/ckeditor5/issues/4600) to avoid surprises in the `<textarea>`.
> 
> *   Does it address issues like using Ctrl+A in `<textarea>`?

@psmyrek, did you test how a textarea works within the editor when working on #4600?

**Comment by Reinmar** [comment]
> *   The toolbar icon may be a challenge. We already used both designs that would make sense so we need to come up with some new idea

This feature is targetted at more advanced users, so using the word "HTML" would be fine. Would it somehow fit in the icon?

**Comment by oleq** [comment]
> so using the word "HTML" would be fine

I'm not so sure about this. They could use PHP there. Or virtually anything for that matter (e.g. markdown?). So using "HTML" is not the best decision IMO (not very future-proof).

> Would it somehow fit in the icon?

Yes, but this is going to be ugly.

**Comment by pomek** [comment]
In order to have a textarea and the toggle button inside the widget, we must use changes from this o from this PR – https://github.com/ckeditor/ckeditor5/pull/8243.

**Comment by oleq** [comment]
I prepared final designs for the UI of the feature. Please let me know if anythings is not clear.

## Textarea blurred

![](https://user-images.githubusercontent.com/1099479/96450260-415b1200-1216-11eb-8de5-1cc38981eff7.png)

## Textarea focused

![](https://user-images.githubusercontent.com/1099479/96450301-4ddf6a80-1216-11eb-9935-0b60318eead9.png)

## Content preview

![](https://user-images.githubusercontent.com/1099479/96450322-5768d280-1216-11eb-882c-048d44499c0e.png)

## Spacings

![](https://user-images.githubusercontent.com/1099479/96450349-5f287700-1216-11eb-9692-6be1c73f1dc6.png)

**Comment by finex** [comment]
Hi, is it necessary to print the `<div class="raw-html-embed">` element? How may I get rid of it and only print the content?

**Comment by smileBeda** [comment]
> Hi, is it necessary to print the <div class="raw-html-embed"> element? How may I get rid of it and only print the content?

Exact same problem here.

1. First of all, the feature "source code" is _misleading_ because hey, _editing source code_ means to edit source code, and not to get stripped HTML saved. 
2. However, being the feature "Insert HTML" there, one uses that as it does not strip HTML code, yet, outputs it wrapped in a `raw-html-embed` div which literally will destroy everything if you for example echo that later in a `div class="row"` that assumes certain structures inside it.

Fazit, with CKEditor you can currently _not_ build your own HTML. It is either wrapped in unnecessary HTML div, _or stripped_, which as said, is extremely confusing, since _editing source code_ really means that: editing source code.

If anything, the insert HTML feature should be used to _insert HTML_ like "insert code snippet" and the editing source code, should be what we use if we want to build our own HTML.

Is there any solution at least to either allow more HTML when editing source code, or to strip that `raw-html-embed`?
