### ISSUE TITLE
User uploaded images are visible on server to other users

### ISSUE THREAD

**Issue by mikeromanov** [ckeditor/ckeditor5#8206]
Hello, dear folks! I'm using django ckeditor with ckuploader to insert images and upload documents. Everything is working great, except one feature. When one presses the button "Browse on server" during image upload, any user can see all images previously uploaded by anyone.
![image](https://user-images.githubusercontent.com/33122675/95007668-e07ae980-061a-11eb-8553-dedb46bb44eb.png)
Since my website (dedicated to birds) is intended to be a multi-user platform, it is not desirable behaviour. I'd prefer one of the following:

1. User can see only his uploaded files. 

2. User can see only files in the current derectory (which belongs to the currently edited page).

Are there any settings to do this?

If not, please tell me how CKEditor remembers all uploaded files? It should store them in some database, but I didn't find one.

**Comment by Mgsy** [comment]
Hi! This issue tracker is dedicated to CKEditor 5, while your issue is about CKEditor 4. The latter has its own tracker, so please report your problem in a [proper repository](https://github.com/ckeditor/ckeditor4/issues).
