### ISSUE TITLE
Hide "packages" from code page

### ISSUE THREAD

**Issue by Aaron-Junker** [ckeditor/ckeditor5#8207]
Hide the "packages" section from the code page. This can be done by edit the description on the cope page.

**Comment by Mgsy** [comment]
Hi, I'm not sure what do you mean, can you tell us more about your issue?

**Comment by Aaron-Junker** [comment]
@Mgsy I also described it in microsoft/powertoys#6117

**Comment by AnnaTomanek** [comment]
It looks like this issue was reported to us by mistake. I'm closing it as invalid - @Aaron-Junker do let us know if you think otherwise.

**Comment by Aaron-Junker** [comment]
No that isnt a mistake.

**Comment by AnnaTomanek** [comment]
Hi @Aaron-Junker, thanks for chiming in. Can you please let us know what you mean exactly? How is this issue connected with CKEditor 5? Can you paste a screenshot or screencast showing this?

**Comment by Aaron-Junker** [comment]
![ck1](https://user-images.githubusercontent.com/58633848/96604665-a6396980-12f5-11eb-9b02-af5d6d50dc3b.PNG)
![ck2](https://user-images.githubusercontent.com/58633848/96604664-a5a0d300-12f5-11eb-940e-f9303245ca2c.PNG)
![ck3](https://user-images.githubusercontent.com/58633848/96604663-a5a0d300-12f5-11eb-8e6f-a7ff911716ca.PNG)
![ck4](https://user-images.githubusercontent.com/58633848/96604660-a5083c80-12f5-11eb-8a1c-9e019741bf2a.PNG)

I hope that help. If not i don't know what else I should do

**Comment by mlewand** [comment]
Ok so the request here is to disable packages section on our GitHub repository. It sounds fair since we're not using it anyway. I disabled it.

**Comment by Aaron-Junker** [comment]
👍
