### ISSUE TITLE
List new plugins during the release

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#8217]
## 📝 Provide a description of the new feature

AFAIR we have already a logic that detects new plugins for the `npm run docs:content-styles` command.

It would be great to list the new plugins during the release so that we can pass on new plugin list to be added to the added to the online builder.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
A list of plugins is available here: https://github.com/ckeditor/ckeditor5/blob/608baa9be5a1c8ae5600e8df9627c4f5b2cecef7/scripts/docs/build-content-styles.js#L249-L252

We need to save an array of those objects and compare them with the existing database file. After displaying the list, we should update the database and commit it.

**Comment by mlewand** [comment]
Fixed in #8338
