### ISSUE TITLE
beforeDestroy` has been renamed to `beforeUnmount getting this issue with vue 3

### ISSUE THREAD

**Issue by yedidisatya** [ckeditor/ckeditor5#8224]
![image](https://user-images.githubusercontent.com/31219029/95309666-159c6b80-08a9-11eb-8459-9ff56ef36d31.png)

script.ts
import { computed, defineComponent, reactive } from 'vue';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

export default defineComponent({
    name: 'add-notes',
    components: {
       // ckeditor: CKEditor.component
    },
    setup() {
        const state = reactive({
            editor: ClassicEditor,
            editorData: '<p>test</p>',
            editorConfig: {
                // The configuration of the editor.
            }
        })
        return {
            state: computed( () =>  state)
        }
    }
})

templte.html

<template>
    <div>
          <ckeditor ></ckeditor>
    </div>
</template>

<script src="./Notes.ts" />

main.ts
import { createApp } from 'vue';
import App from './App.vue';
import './index.css';
import router from './router/router';
import CKEditor from '@ckeditor/ckeditor5-vue';

const OrderSatus = createApp(App);

OrderSatus.use(router);
OrderSatus.use(CKEditor);

router.isReady().then(() => {
    OrderSatus.mount('#app');
});

**Comment by yedidisatya** [comment]
![image](https://user-images.githubusercontent.com/31219029/95309639-09181300-08a9-11eb-94a1-22b5662c6086.png)

**Comment by Mgsy** [comment]
Hi, we're aware of this change and we'll be working on it in the current iteration. Please refer to #8135 to learn more.
