### ISSUE TITLE
Two <a> tags, one inside another, when adding manual link decorator with target attribute

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#8230]
## 📝 Provide detailed reproduction steps (if any)

1. Set the following link options:
```js
link: {
    addTargetToExternalLinks: true,
    decorators: {
        isExternal: {
            mode: 'manual',
            label: 'is top',
            attributes: {
                target: '_top'
            }
        }
    }
}
```
2. Add link with manual decorator to some text

### ✔️ Expected result

There is only one `<a>` tag.  

### ❌ Actual result

There are two `<a>` tags, one inside another, with different target attributes:  
```html
<p>Some <a target="_blank" rel="noopener noreferrer" href="https://www.google.com"><a target="_top">sample</a></a> text</p>
```
- https://github.com/ckeditor/ckeditor5/issues/6436 similar?
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Yeah, it's the same story as in #6436. A limitation that may not be easy to remove.

I'll close this as a DUP of #6436.
