### ISSUE TITLE
The supportAllValues doesn't work with nested elements

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#8233]
## 📝 Provide detailed reproduction steps (if any)

1.  Use the following configuration for FontSize plugin:

```
fontSize:  {   
options: [ 8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72 ],   
supportAllValues: true   
}
```

1.  Open editor with the following content:

```javascript
<p style="text-align:center"><span style="font-size:28px">APPROVED</span></p>
<p style="text-align:center"><span style="color:#27ae60"><em style="font-style: italic;"><strong><span style="font-size:28px">APPROVED</span></strong></em></span></p>
```

### ✔️ Expected result

Since `supportAllValues` is used, nested `span` with `font-size:28px` should be retained in both cases.

### ❌ Actual result

The nested `span` with `font-size:28px` is getting removed from the second paragraph.

![](https://user-images.githubusercontent.com/5314687/95558471-9167f680-0a16-11eb-87c7-e1d4bb71c34d.png)

Even after creating a custom plugin (I can attach it if necessary) which retains elements (ok, I have changed the `i` into styled `span` ), their order and overwrites the font-size plugin default converter, there result is still the same:

![](https://user-images.githubusercontent.com/5314687/95559429-08ea5580-0a18-11eb-868f-6040399d06d2.png)

The only solution is removing `supportAllValues: true` .

NOTE: This could be a duplicate of #7965

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: 23.0.0
*   Installed CKEditor plugins: FontSize

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is the minimal markup to reproduce this issue:

```html
OK:
<p><span style="font-size:28px">APPROVED</span></p>
NOK:
<p><span style="color:#27ae60"><span style="font-size:28px">APPROVED</span></span></p>
```

And it indeed does not work only if `supportAllValues` is set to `true` :thinking: .

**Comment by psmyrek** [comment]
Even simpler minimal failing markup:
```html
<p><span><span style="font-size:28px">This text should have 28px font size...</span></span></p>
```

**Comment by dkrahn** [comment]
Still does not work with nested elements, for example, inside a table cell.
```
OK:
<p><span style="font-size:28px">APPROVED</span></p>
NOK:
<figure class="table"><table><tbody><tr><td><span style="font-family:'Courier New', Courier, monospace;">APPROVED</span></td></tr></tbody></table></figure>
```

The test I did was today(2021-01-26 10:30) accessing https://ckeditor.com/ckeditor-5/demo/#document
1. In the editor, I cleared it and added a table with one cell and the text applying the Courier font.
2. In the console, I executed the following:
```
editors[0].setData(editors[0].getData())
```
Result: The font family is lost. As is the font-size.
