### ISSUE TITLE
Dynamically change dropdown panel position

### ISSUE THREAD

**Issue by denisr-w** [ckeditor/ckeditor5#8235]
## Description of the task

Im using CKEditor5 Custom Inline editor in Angular framework. In some cases the width of the component that is using `<ckeditor>` is so small that the toolbar gets a dropdown button for showing other items in toolbar. When this button is clicked I would like that the position of the panel is in some cases south east and in other cases south west. Can this be achieved through `set()` method for `panelPosition` property dynamically somehow? Also how can I access my DropdownView class?

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: …
* Installed CKEditor plugins: 	Alignment, Bold, Essentials, FontColor, FontSize, Heading, Indent, IndentBlock, Italic, List, ListStyle, Paragraph, PasteFromOffice, RemoveFormat, Table, TableCellProperties, TableProperties, TableToolbar, Underline

**Comment by Reinmar** [comment]
cc @oleq is it possible today?

**Comment by oleq** [comment]
> cc @oleq is it possible today?

Yes, but via protected property chain only:

```
editor.ui.view.toolbar._behavior.groupedItemsDropdown.panelPosition = 'sw'; 
```

You can use one of https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_dropdownview-DropdownView.html#member-panelPosition then.

**Comment by denisr-w** [comment]
Thank you @oleq. You sir are a gentleman and a scholar.
