### ISSUE TITLE
Editor with the Pagination plugin enabled does not start if the config is not set

### ISSUE THREAD

**Issue by arnoldoscar101** [ckeditor/ckeditor5#8238]
After downloading custom build with pagination and after running the given sample html file, the ckeditor 5 does not load. It gives the below error: 

Build id: 1d7yaythf0db-bhg4k9yx2klk
index.html:182 TypeError: Cannot destructure property 'pageWidth' of 't[_0x734c(...)][_0x734c(...)](...)' as it is undefined.
    at s.m (ckeditor.js:5)
    at kl.<anonymous> (ckeditor.js:5)
    at kl.i (ckeditor.js:5)
    at kl.fire (ckeditor.js:5)
    at kl.init (ckeditor.js:5)
    at ckeditor.js:5

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I can confirm this issue. It looks like the editor from [online builder](https://ckeditor.com/ckeditor-5/online-builder/) is missing [pagination configuration options](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html#configuration). If you add them manually ( and not forget license key ), then everything works fine.  
  
cc @ma2ciek Could you take a look at this?

**Comment by Reinmar** [comment]
That's a bug in the pagination feature. It should use some sane defaults to be able to start without the config being set.

**Comment by oleq** [comment]
cc @niegowski

**Comment by arnoldoscar101** [comment]
Hi Guys,

Thanks for your help. I have found the solution for the pagination
configuration issue. But, now after loading sample page, I am getting the
below error:
Uncaught (in promise) TypeError: Cannot read property 'parent' of undefined
    at s.p (ckeditor.js:5)
    at s._mapPageStarterInfoToPageBreakInfo (ckeditor.js:5)
    at ckeditor.js:5
    at Array.map (<anonymous>)
    at s.u (ckeditor.js:5)
    at ckeditor.js:5

Please help.

Thanks & Regards,

Arnold

**Comment by ma2ciek** [comment]
@FilipTokarski, could you reproduce the issue?

**Comment by FilipTokarski** [comment]
No, after adding license key and [pagination config](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html#installation) everything works fine.  
  
@arnoldoscar101 I suppose this might be something in your editor config. But, if you are sure that there's a bug on our side, could you please create a separate ticket for this ( we should keep this one for tracking the original issue ) ? Providing step-by-step description and your full editor config, editor type, plugins etc. would be very helpful too.

**Comment by ma2ciek** [comment]
> ```
> Uncaught (in promise) TypeError: Cannot read property 'parent' of undefined
>     at s.p (ckeditor.js:5)
>     at s._mapPageStarterInfoToPageBreakInfo (ckeditor.js:5)
>     at ckeditor.js:5
>     at Array.map (<anonymous>)
>     at s.u (ckeditor.js:5)
>     at ckeditor.js:5
> ```

Hm. I just faced this issue as well, so indeed, it should be reported somewhere. 

> That's a bug in the pagination feature. It should use some sane defaults to be able to start without the config being set.

I think so, at least an error when the configuration is missing. Right now it's hard to tell for which feature the configuration is mandatory and for which feature is not while browsing https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html.

**Comment by ma2ciek** [comment]
Hi @arnoldoscar101, 

I guess that you've created the build using the online builder and you've added the `Title` plugin to this build as well? It seems that this plugin is currently incompatible with the `Pagination` plugin - I'm sorry for the inconvenience.

**Comment by Reinmar** [comment]
There are two issues here that we should resolve:

*   The editor should start without errors when the plugin is added to the editor.
*   However, we can also log a warning that the pagination feature needs to be configured. Also, for simplicity, the pagination feature may be disabled when there's no configuration.

There's also a followup – sharing the config between pagination and export plugins.
