### ISSUE TITLE
image-style-side in <figure> is not preserved when setting data

### ISSUE THREAD

**Issue by Ashot72** [ckeditor/ckeditor5#824]
When I getData() then it outputs &lt;figure class="image image-style-side"&gt;&lt;img src="sharepoint.jpg" /&gt;&lt;figcaption&gt;SharePoint&gt;/figcaption&gt;&gt;/figure&gt;
When I set data above then class "image-style" is not preserved and output is  &ltfigure class="image"&gt;
Also, the value inside &lt;figcaption&gt; (in this case SharePoint) is moved inside &lt;p&gt; tag &lt;p&gt;SharePoint&lt;/p&gt; tag and &lt;figcaption&gt; is empty.

**Comment by Reinmar** [comment]
Hi! Can you reproduce this on any of the online demos?

**Comment by ma2ciek** [comment]
I couldn't reproduce it. On the https://ckeditor5.github.io/ it works correctly. If you'll find out that it still doesn't work in some build, please, let us know.
