### ISSUE TITLE
What do we need to do when creating a new package?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8244]
## 📝 Provide a description of requested docs changes

Would be good to have an instruction with steps that must be done when creating the new package.

E.g. we need to publish an empty package with version 0.0.1 on npm in order to have a working `yarn install` command.

Also, the new package should be added to README in the root package.

**Comment by mlewand** [comment]
There is already an instruction on how to create a new package: https://www.notion.so/Creating-a-new-package-f3528d73f2324413a8222ac4e8ec1334

It has the step with publishing 0.0.1

There was no step to add the newly created package to [`main CKE5 repository's package list`](https://github.com/ckeditor/ckeditor5#packages) though, so I added it. @pomek are you missing something else or is this issue good to close?

**Comment by pomek** [comment]
Everything is fine. Closing.
