### ISSUE TITLE
Creating a custom element not working

### ISSUE THREAD

**Issue by MihaiZhaoDev** [ckeditor/ckeditor5#8253]
## Provide a description of the task
Creating a custom element not working

* CKEditor version: 5

I am trying to create a custom html element and add into the editor but it seems that is not working.

`class InsertImage extends Plugin {
	init() {
		const editor = this.editor;

		editor.ui.componentFactory.add("insertImage", (locale) => {
			const view = new ButtonView(locale);

			view.set({
				label: "Insert image",
				icon: imageIcon,
				tooltip: true,
			});

			// Callback executed once the image is clicked.
			view.on("execute", () => {
				const imageUrl = prompt("Image URL");
				const imageText = prompt("Image Text");
				const imageAlt = prompt("Image Alt");

				editor.model.change((writer) => {

					const imageElement = writer.createElement(`
						<p>&nbsp;</p>
						<a
						href="${imageUrl}"
						data-fancybox="group"
						>
							<img
								class="img-responsive large-img"
								src="${imageUrl}"
								alt="${imageAlt}"
							/>
						</a>
						<h3 class="text-center">${imageText}</h3>
						<p>&nbsp;</p>
					`);

					editor.model.insertContent(
						imageElement,
						editor.model.document.selection
					);

				});
			});

			return view;
		});
	}
}`

**Comment by FilipTokarski** [comment]
Hi, I replied in your [other ticket](https://github.com/ckeditor/ckeditor5/issues/8254). Please do not add multiple tickets for the same issue. I'm closing this as a duplicate.
