### ISSUE TITLE
Creating a custom element using Plugins not working

### ISSUE THREAD

**Issue by MihaiZhaoDev** [ckeditor/ckeditor5#8254]
Creating a custom element not working

CKEditor version: 5
I am trying to create a custom html element and add into the editor but it seems that is not working.

`class InsertImage extends Plugin {
  init() {
    const editor = this.editor;

    editor.ui.componentFactory.add("insertImage", (locale) => {
      const view = new ButtonView(locale);

      view.set({
        label: "Insert image",
        icon: imageIcon,
        tooltip: true,
      });

      // Callback executed once the image is clicked.
      view.on("execute", () => {
        const imageUrl = prompt("Image URL");
        const imageText = prompt("Image Text");
        const imageAlt = prompt("Image Alt");

        editor.model.change((writer) => {
          const imageElement = writer.createElement(`
                    <p>&nbsp;</p>
                    <a
                    href="${imageUrl}"
                    data-fancybox="group"
                    >
                        <img
                            class="img-responsive large-img"
                            src="${imageUrl}"
                            alt="${imageAlt}"
                        />
                    </a>
                    <h3 class="text-center">${imageText}</h3>
                    <p>&nbsp;</p>
                `);

          editor.model.insertContent(
            imageElement,
            editor.model.document.selection
          );
        });
      });

      return view;
    });
  }
}`

**Comment by MihaiZhaoDev** [comment]
If I do the following code it works but is not what I want:
					var imageElement = writer.createElement("image", {
						class: "img-responsive large-img",
						src: imageUrl,
						alt: imageAlt,
					});

**Comment by FilipTokarski** [comment]
Hi, editor has it's own data [model](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#model) and if you want to add some new elements you need to first register them as allowed - please see docs on [schema ](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and [conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html).  I'm not sure about your use case here, but maybe also [tutorial on block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html) might be helpful.
  
Also, just out of curiosity, aren't [Image](https://ckeditor.com/docs/ckeditor5/latest/features/image.html) and [LinkImage](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#linking-images) plugins enough for your use case?
