### ISSUE TITLE
"Error: Module not found" creating an NPM package from react ckeditor source

### ISSUE THREAD

**Issue by aidanalexander** [ckeditor/ckeditor5#8256]
## 📝 Provide detailed reproduction steps (if any)

1. Followed [this guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-create-react-app2) to create a customised react build of ckeditor. It works without issue after running `yarn start`.
2. I modified the build script to be `"NODE_ENV=production && rm -rf dist && mkdir dist && babel src/CKEditor --out-dir dist --copy-files"`, run `yarn build` and then `npm publish` which creates and publishes the Ckeditor build as an NPM package
5. Trying to use the npm package results in an error 
 
### ✔️ Expected result

A working NPM package that I can import and utilise in other projects

### ❌ Actual result

`../node_modules/@ckeditor/ckeditor5-image/theme/textalternativeform.css (../node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!../node_modules/postcss-loader/src??postcss!../node_modules/@ckeditor/ckeditor5-image/theme/textalternativeform.css)
Module not found: Can't resolve './@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css' in '/home/aidan/electedtech-ui/node_modules/@ckeditor/ckeditor5-image/theme'`

## 📃 Other details

From what I can tell the issue is caused by the other projects that import my Ckeditor NPM package not having the same webpack config to handle the CSS imports as setup in the guild I followed. The problem is that the other projects don't have configurable webpacks and the idea of the NPM package is to just to import it and use it straight away. Is there anyway to pre-compile / pre-import these css files in the NPM package?    

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
cc @pomek Could you take a look at this?

**Comment by pomek** [comment]
I'd suggest using webpack for building the package. Except for resolving js files, we also import CSS and SVG that (I assume) babel does not understand.

Please, take a look at the guide that helps you configure webpack – https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-configuration. In case of troubles, let us know.

**Comment by aidanalexander** [comment]
Thank you for your feedback so far! After setting up a new webpack config it now renders something in my other projects but unfortunately all it shows is the input div without a toolbar and I can't type. 

![Screenshot from 2020-10-16 16-36-19](https://user-images.githubusercontent.com/23035229/96279031-1aaa9a80-0fce-11eb-8f9c-e15c8ba8fa88.png)

Typing is triggering some kind of update to the DOM nodes within so there is some accompanying JS but it doesn't show anything. There are no console error or warnings throughout.


Here is the webpack.config.js I'm using:
```
const path = require("path");
const { styles } = require("@ckeditor/ckeditor5-dev-utils");

module.exports = {
  mode: "production",
  entry: path.resolve(__dirname, "src/index.js"),
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
    libraryTarget: "umd",
    library: "@electedtech/electedtech-ckeditor",
  },
  plugins: [],
  module: {
    rules: [
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        use: ["raw-loader"],
      },
      {
        test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
        use: [
          {
            loader: "style-loader",
            options: {
              injectType: "singletonStyleTag",
              attributes: {
                "data-cke": true,
              },
            },
          },
          {
            loader: "postcss-loader",
            options: styles.getPostCssConfig({
              themeImporter: {
                themePath: require.resolve("@ckeditor/ckeditor5-theme-lark"),
              },
              minify: true,
            }),
          },
        ],
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
        },
      },
    ],
  },
};
```

src/index.js 
```
import CKEditor from "./CKEditor.jsx";

export default CKEditor;
```

src/CKEditor.jsx
```
import Alignment from "@ckeditor/ckeditor5-alignment/src/alignment"
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
import CKEditor from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
import Essentials from "@ckeditor/ckeditor5-essentials/src/essentials";
import Font from "@ckeditor/ckeditor5-font/src/font"
import FontSize from "@ckeditor/ckeditor5-font/src/fontsize"
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageInsert from '@ckeditor/ckeditor5-image/src/imageinsert';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import Italic from "@ckeditor/ckeditor5-basic-styles/src/italic";
import Link from '@ckeditor/ckeditor5-link/src/link';
import ListStyle from "@ckeditor/ckeditor5-list/src/liststyle"
import Paragraph from "@ckeditor/ckeditor5-paragraph/src/paragraph";
import React from "react";
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import Underline from "@ckeditor/ckeditor5-basic-styles/src/underline";

const editorConfiguration = {
  plugins: [Essentials, Bold, Italic, Underline, Paragraph, Font, FontSize, ListStyle, Indent,Alignment, Link, Image, ImageInsert, Table, TableToolbar, TableProperties, TableCellProperties ],
  fontFamily: {
    options: [
      "Arial",
      "Times New Roman"
    ],
  },
  fontSize: {
    options: [
      8,
      9,
      10,
      11,
      12,
      14,
      16,
      18,
      20,
      22,
      24,
      28,
      36,
      48,
      72
    ]
  },
  table: {
    contentToolbar: [
      'tableColumn', 'tableRow', 'mergeTableCells',
      'tableProperties', 'tableCellProperties'
    ]
  },
  toolbar: [
    "fontFamily",
    "fontSize",
    "bold",
    "italic",
    "underline",
    "bulletedList",
    "numberedList",
    "outdent",
    "indent",
    'alignment:left', 'alignment:right', 'alignment:center', 'alignment:justify',
    'fontColor', 'fontBackgroundColor',
    "link",
    "imageInsert",
    "insertTable",
    "undo",
    "redo"
  ]
}

const ElectedTechCKEditor = ({ ...props }) => (
  <CKEditor editor={ClassicEditor} config={editorConfiguration} {...props} />
);

export default ElectedTechCKEditor;
```

**Comment by aidanalexander** [comment]
@pomek Hope you had a good weekend and sorry to chase if you've already seen this - not sure how notifications work on Github threads/comments! I've continued to play around with this but I'm still facing the same issue I described above, do you have any ideas?

**Comment by msglab** [comment]
I believe I am having the same issue.....
CKEditor works fine in localhost but when pushing them to heroku I get a fail because:
Error: Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic' in '.../plugins/wysiwyg/admin/src/components/CKEditor'

**Comment by aidanalexander** [comment]
> I believe I am having the same issue.....
> CKEditor works fine in localhost but when pushing them to heroku I get a fail because:
> Error: Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic' in '.../plugins/wysiwyg/admin/src/components/CKEditor'

The issue I was having related to using Babel for compiling rather than a correctly configured webpack. 

pomek gave me this link to read to correctly configure webpack although I'm having another issue that I described above... https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#webpack-configuration

**Comment by msglab** [comment]
Thanks! I actually noticed that a second package.json got generated in the plugins folder, and it had the 2 lines for the ckeditor.. I manually copied them to the root-layer package json and then all was fine... no idea if that is best practice though

**Comment by aidanalexander** [comment]
Would you mind sharing your package.json with me? Still struggling to get a functioning build through webpack on my end...

**Comment by msglab** [comment]
package.json is a list of packages you are using, so you shouldn't copy-paste a random one, it is veeeery unlikely that there is a match with the needed packages.

BUT the 2 lines I added to the file are:

```
.....
 "devDependencies": {},
  "dependencies": {
....

    **"@ckeditor/ckeditor5-build-classic": "^23.0.0",
    "@ckeditor/ckeditor5-react": "^2.1.0"**
....
  },
```

In my case I have 2 folders, "backend" with strapi and then "frontend" with next. The 2 lines above go to the one in the backend folder, since the ckeditor in my case is for the strapi backend.

good luck and I hope this is somewhat helpful!

**Comment by aidanalexander** [comment]
@FilipTokarski  @pomek Hi there, the need for this has come up again but unfortunately i'm still facing the same issue. Any chance of some input from yourselves? Thank you!

**Comment by pomek** [comment]
Hi @aidanalexander. Sorry for the late reply. I missed the issue. I'll try to reproduce the issue and let you know if I'll be able to fix that.

**Comment by pomek** [comment]
I tried to reproduce your issue. Unfortunately, with no luck :D 

I started with a new project based on your data. I aligned the configuration a little bit and… everything works.

## The project structure

```bash
├── dist
│   ├── index.html
│   └── main.js           # Created by Webpack.
├── node_modules          # Created by npm.
├── src
│   ├── CKEditor.jsx
│   └── index.js
├── webpack.config.js
└── package.json
```

### `package.json`

Nothing special. Just import everything that is needed.

```json
{
  "name": "Test-App",
  "description": "React in 'dependencies' is just for running the development sample.",
  "repository": "https://example.com",
  "license": "MIT",
  "dependencies": {
    "react": "^16.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-react": "^7.12.5",
    "@ckeditor/ckeditor5-alignment": "^23.1.0",
    "@ckeditor/ckeditor5-basic-styles": "^23.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^23.6.1",
    "@ckeditor/ckeditor5-editor-classic": "^23.1.0",
    "@ckeditor/ckeditor5-essentials": "^23.1.0",
    "@ckeditor/ckeditor5-font": "^23.1.0",
    "@ckeditor/ckeditor5-image": "^23.1.0",
    "@ckeditor/ckeditor5-indent": "^23.1.0",
    "@ckeditor/ckeditor5-link": "^23.1.0",
    "@ckeditor/ckeditor5-list": "^23.1.0",
    "@ckeditor/ckeditor5-paragraph": "^23.1.0",
    "@ckeditor/ckeditor5-react": "^2.1.0",
    "@ckeditor/ckeditor5-table": "^23.1.0",
    "@ckeditor/ckeditor5-theme-lark": "^23.1.0",
    "babel-loader": "^8.2.1",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^4.0.2",
    "react-dom": "^17.0.1",
    "style-loader": "^1.3.0",
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12"
  },
  "peerDependencies": {
    "react": "^16.14.0"
  }
}
```

### `webpack.config.js`

Your configuration looked good. However, it misses a few things:

- Missing React preset for Babel (assuming, you have defined it in `.babelrc`). I added it directly to the webpack configuration
- The library assumes that React exists. We don't want to build React inside our component because an end-user (of our component) may use a different version. Also, the end-user does not want to attach React twice (for the first by itself, the second one by us)

```js
const path = require( "path" );
const { styles } = require( "@ckeditor/ckeditor5-dev-utils" );

module.exports = {
	mode: "production",
	entry: path.resolve( __dirname, "src/index.js" ),

	output: {
		filename: "main.js",
		path: path.resolve( __dirname, "dist" ),
		libraryTarget: "umd",
		library: "@electedtech/electedtech-ckeditor",
	},

	// The component should not import any React definition to its internals.
	// See: https://github.com/ckeditor/ckeditor5-react/blob/f0a2e57bc507425ee9d038c55cda9db370425de1/webpack.config.js#L20-L27
	// We assume that the end-user of the component will provide the framework.
	// The component is not responsible for that. React is peer dependency of the component.
	externals: {
		react: {
			root: 'React',
			commonjs2: 'react',
			commonjs: 'react',
			amd: 'react'
		}
	},

	module: {
		rules: [
			{
				test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
				use: [ "raw-loader" ],
			},
			{
				test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
				use: [
					{
						loader: 'style-loader',
						options: {
							injectType: 'singletonStyleTag',
							attributes: {
								'data-cke': true
							}
						}
					},
					{
						loader: 'postcss-loader',
						options: styles.getPostCssConfig( {
							themeImporter: {
								themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
							},
							minify: true
						} )
					}
				],
			},
			{
				test: /\.jsx$/,
				loader: 'babel-loader',
				exclude: /node_modules/,
				query: {
					compact: false,
					presets: [ '@babel/preset-react' ]
				}
			}
		],
	},
};
```

### `src/index.js`

```js
import CKEditor from "./CKEditor.jsx";

export default CKEditor;
```

### `src/CKEditor.jsx`

Take a look at the file. I added some comments that could help you.

```jsx
// Why do you want to attach the library inside a component?
// See: ../webpack.config.js:15
// import React from "react";

import Alignment from "@ckeditor/ckeditor5-alignment/src/alignment"
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
import Essentials from "@ckeditor/ckeditor5-essentials/src/essentials";
import Font from "@ckeditor/ckeditor5-font/src/font"
import FontSize from "@ckeditor/ckeditor5-font/src/fontsize"
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageInsert from '@ckeditor/ckeditor5-image/src/imageinsert';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import Italic from "@ckeditor/ckeditor5-basic-styles/src/italic";
import Link from '@ckeditor/ckeditor5-link/src/link';
import ListStyle from "@ckeditor/ckeditor5-list/src/liststyle"
import Paragraph from "@ckeditor/ckeditor5-paragraph/src/paragraph";
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import Underline from "@ckeditor/ckeditor5-basic-styles/src/underline";

// If you're using @ckeditor/ckeditor5-react@^3.0.0, use:
// import { CKEditor } from "@ckeditor/ckeditor5-react";
// If not (@ckeditor/ckeditor5-react@^1.0.0 or @ckeditor/ckeditor5-react@^2.0.0), the import below is enough:
import CKEditor from "@ckeditor/ckeditor5-react";

const editorConfiguration = {
	plugins: [
		Essentials,
		Bold,
		Italic,
		Underline,
		Paragraph,
		Font,
		FontSize,
		ListStyle,
		Indent,
		Alignment,
		Link,
		Image,
		ImageInsert,
		Table,
		TableToolbar,
		TableProperties,
		TableCellProperties
	],
	fontFamily: {
		options: [
			"Arial",
			"Times New Roman"
		],
	},
	fontSize: {
		options: [
			8,
			9,
			10,
			11,
			12,
			14,
			16,
			18,
			20,
			22,
			24,
			28,
			36,
			48,
			72
		]
	},
	table: {
		contentToolbar: [
			'tableColumn', 'tableRow', 'mergeTableCells',
			'tableProperties', 'tableCellProperties'
		]
	},
	toolbar: [
		"fontFamily",
		"fontSize",
		"bold",
		"italic",
		"underline",
		"bulletedList",
		"numberedList",
		"outdent",
		"indent",
		'alignment:left', 'alignment:right', 'alignment:center', 'alignment:justify',
		'fontColor', 'fontBackgroundColor',
		"link",
		"imageInsert",
		"insertTable",
		"undo",
		"redo"
	]
};

const ElectedTechCKEditor = ( { ...props } ) => (
	<CKEditor editor={ ClassicEditor } config={ editorConfiguration } { ...props } />
);

export default ElectedTechCKEditor;
```

### `dist/index.html`

This is a file that shows that everything works.

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>CKEditor 5 – React Component – development sample</title>
    <style>
        body {
            max-width: 800px;
            margin: 20px auto;
        }

        .button_read-only {
            margin: 10px 0;
        }

    </style>
</head>

<body>
<h1>CKEditor 5 – React Component – development sample</h1>
<p style="text-align: center;">Component's events are logged to the console.</p>
<button id="readOnly" class="button_read-only" disabled>Toggle the read-only mode</button>

<div id="root"></div>

<script src="../node_modules/react/umd/react.production.min.js"></script>
<script src="../node_modules/react-dom/umd/react-dom.production.min.js"></script>
<script src="./main.js"></script>
<script>
	const editorContent = `
<h2>Sample</h2>
<p>This is an instance of the <a href="https://ckeditor.com/docs/ckeditor5/latest/builds/guides/overview.html#classic-editor">classic editor build</a>.</p>
<p>You can use this sample to validate whether your <a href="https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html">custom build</a> works fine.</p>
`;

	const readOnlyButton = document.getElementById( 'readOnly' );

	class App extends React.Component {
		constructor( props ) {
			super( props );
		}

		render() {
			return React.createElement( window[ '@electedtech/electedtech-ckeditor' ].default, {
				data: editorContent,
                // If you're using @ckeditor/ckeditor5-react@^3.0.0, use: `onReady()`.
				onInit: editor => {
					window.editor = editor;

					readOnlyButton.disabled = false;

					console.log( 'event: onReady' );
					console.log( 'Editor is ready to use! You can use "editor" variable to play with it.' );

					editor.ui.view.listenTo( readOnlyButton, 'click', () => {
						editor.isReadOnly = !editor.isReadOnly;
					} );
				},
				onChange: ( event, editor ) => {
					console.log( 'event: onChange', { event, editor } );
				},

				onBlur: ( event, editor ) => {
					console.log( 'event: onBlur', { event, editor } );
				},
				onFocus: ( event, editor ) => {
					console.log( 'event: onFocus', { event, editor } );
				}
			} )
		}
	}

	document.addEventListener( 'DOMContentLoaded', () => {
		ReactDOM.render(
			React.createElement( App ),
			document.getElementById( 'root' )
		);
	} );
</script>
</body>

</html>
```

## Steps

1. Copy the files above to the proper places.
2. `npm i`
3. `./node_modules/.bin/webpack`
4. Open `dist/index.html`. It can be done even without the HTTP server.

Let me know whether everything is understandable for you. And of course, if something does not work, let me know as well.

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/99536830-2c0b0c00-29ab-11eb-8f9f-8e729f5ac04c.png)

**Comment by aidanalexander** [comment]
Thank you so much for this @pomek, and the comments are very helpful. 

I've followed your instructions and dist/main.js works in index.html as you described. However if I publish to NPM and import the package in another project I get the same empty box that I described in this thread on the 16th of October. 

If I copy your index.html to this other project and update the import path to "./node_modules/@electedtech/electedtech-ckeditor/dist/main.js" then it works, so it's not NPM mangling the JS, it's the same JS as before. What is the difference between doing <script src="./path/to/dist/main.js"></script> and importing the package as a React component 

```
import CKEditor from '@electedtech/electedtech-ckeditor'
import React from 'react'

const FormCkeditor = ({ ...props }) => {
  return (
    <CKEditor
      config={{
        removePlugins: ['Heading', 'ImageUpload', 'MediaEmbed']
      }}
      {...props}
    />
  )
}

export default FormCkeditor

```

**Comment by pomek** [comment]
Insert `console.log( CKEditor )` right before the `FormCkeditor` definition. It will help us to understand what the variable really means (keeps as its value).

**Comment by aidanalexander** [comment]
```
import CKEditor from '@electedtech/electedtech-ckeditor'
console.log(CKEditor)
```
results in:
```
(_ref12) => {
      var t = Object.assign({}, _ref12);
      return ep.a.createElement(Oi.a, ck({
        editor: Sd,
        config: dk
      }, t));
    }
```

**Comment by aidanalexander** [comment]
Another project uses lazy loading, doing:
```
const Ckeditor = React.lazy(() => import("../components/FormCkeditor.jsx"));
console.log(Ckeditor); // eslint-disable-line
```

results in:
```
$$typeof: Symbol(react.lazy)
_ctor: () => {…}
arguments: (...)
caller: (...)
length: 0
name: ""
__proto__: ƒ ()
[[FunctionLocation]]: ckeditor.js:5
[[Scopes]]: Scopes[2]
_result: (_ref) => {…}
propTypes: {customClassNames: ƒ, growVertically: ƒ, name: ƒ, onChange: ƒ, updateForm: ƒ}
arguments: (...)
caller: (...)
length: 1
name: "FormCkeditor"
__proto__: ƒ ()
[[FunctionLocation]]: FormCkeditor.jsx:60
[[Scopes]]: Scopes[2]
_status: 1
defaultProps: (...)
propTypes: (...)
get defaultProps: ƒ ()
set defaultProps: ƒ (newDefaultProps)
get propTypes: ƒ ()
set propTypes: ƒ (newPropTypes)
__proto__: Object

```

**Comment by aidanalexander** [comment]
Both have the same problem

**Comment by pomek** [comment]
Since as you could see, the code that I posted above works fine, I'm not able to do more on this topic.

If you want me to take look at the last issue you reported, I'd need at least a minimal repo where I will be able to reproduce the issue.

**Comment by aidanalexander** [comment]
Thank you for your help. It does work when imported into a fresh create-react-app so clearly there is something going wrong with these particular project's configs. I suspect it's being compiled with some compatibility flags enabled but we haven't been able to work it out as of yet. 

Thanks again!
