### ISSUE TITLE
Get data without ignoring empty elements

### ISSUE THREAD

**Issue by denisr-w** [ckeditor/ckeditor5#8259]
## Provide a description of the task

I'm using CKEditor5 Custom Inline editor in Angular framework. On `blur` output I would like to get data from editor and store it somewhere. Like many discussions I found on github I would also like to get empty HTML elements even if there is no content in them. The method `getData()` returns the trimmed version of editor content. In documentation under **_Migration from CKEditor 4_** under **_Configuration options compatibility table_** it says that `ignoreEmptyParagraph` is not applicable in version 5.
Can this be achieved some other way?

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 5
* Installed CKEditor plugins: Alignment, Bold, Essentials, FontColor, Heading, Indent, IndentBlock, Italic, List, ListStyle, Paragraph, PasteFromOffice, RemoveFormat, Table, TableCellProperties, TableProperties, TableToolbar, Underline

**Comment by Mgsy** [comment]
Hi! You can pass `{ trim: 'none' }` option to `editor#getData()` to preserve empty elements in the output HTML. See more in the [documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_utils_dataapimixin-DataApi.html#function-getData).
