### ISSUE TITLE
[Docs] Wrong links in Available builds section on Overview page

### ISSUE THREAD

**Issue by vokiel** [ckeditor/ckeditor5#826]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

N/A

## 📋 Steps to reproduce

1. Open https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/overview.html#available-builds
2. Click on any of three builds

## ✅ Expected result

Move to right build.
 
## ❎ Actual result

Nothing happens

## 📃 Other details that might be useful

Those links are upper-case when IDs are lower-case, e.g. `#Classic-editor` vs `#classic-editor`, see: https://github.com/ckeditor/ckeditor5/blame/master/docs/builds/guides/overview.md#L20

**Comment by dkonopka** [comment]
It should be also fixed also in the [README.md](https://github.com/ckeditor/ckeditor5/blob/master/README.md).

**Comment by Reinmar** [comment]
This is strange. I'm quite sure it worked. @m-turek, is it possible that it changed when we changed MD parser? That it started generating lower-cased ids for headings?

**Comment by m-turek** [comment]
Yeah, that's cause of the md parser.
