### ISSUE TITLE
Mention with Decoupled editor error

### ISSUE THREAD

**Issue by bakhiem** [ckeditor/ckeditor5#8264]
## 📝 Provide detailed reproduction steps (if any)
I custom builds Decoupled editor with mention, I follow this link to do that : https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html
But when run, I have an error 
![image](https://user-images.githubusercontent.com/29191068/96112019-3483a900-0f0c-11eb-8fb9-6cd5a9132209.png)
This is my code : 
![image](https://user-images.githubusercontent.com/29191068/96112125-5b41df80-0f0c-11eb-9295-490288165603.png)
But I do the same with classic editor, it run. I don't know why Decoupled editor cause this error.
Can this be achieved some other way?

**Comment by Mgsy** [comment]
@FilipTokarski, can you take a look at it and see if you can observe any problem with the decoupled editor and Mentions plugin (including [the customization](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#customizing-the-output))?

**Comment by FilipTokarski** [comment]
For me, Mention plugin works fine with document editor, also the customization ( from docs ) doesn't cause any errors. It seems that the bug is not in the editor itself but rather in the implementation. @bakhiem could you double check that you didn't change the Mentions customization between the document and classic editors?

p.s. in the future please do not paste here the screenshots of your code, but rather the code itself. It will be easier for us to try to reproduce the issue.

**Comment by bakhiem** [comment]
@FilipTokarski Yes, this is my code, and I just copy & paste from the document, remove option property(link and href), and It work in classic editors but not work in decoupled editors
`/**
 * @license Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

// The editor creator to use.
import DecoupledEditorBase from '@ckeditor/ckeditor5-editor-decoupled/src/decouplededitor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import Mention from '@ckeditor/ckeditor5-mention/src/mention';  
export default class DecoupledEditor extends DecoupledEditorBase {}

// Plugins to include in the build.
DecoupledEditor.builtinPlugins = [
	Essentials,
	Alignment,
	FontSize,
	FontFamily,
	FontColor,
	FontBackgroundColor,
	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	Strikethrough,
	Underline,
	BlockQuote,
	CKFinder,
	EasyImage,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TextTransformation,
	TableProperties,
	TableCellProperties,
  Mention,
  MentionCustomization
];

// Editor configuration.
DecoupledEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'fontfamily',
			'fontsize',
			'fontColor',
			'fontBackgroundColor',
			'|',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'|',
			'alignment',
			'|',
			'numberedList',
			'bulletedList',
			'|',
			'indent',
			'outdent',
			'|',
			'link',
			'blockquote',
			'imageUpload',
			'insertTable',
			'mediaEmbed',
			'|',
			'undo',
			'redo'
		]
	},
	image: {
		styles: [
			'full',
			'alignLeft',
			'alignRight'
		],
		toolbar: [
			'imageStyle:alignLeft',
			'imageStyle:full',
			'imageStyle:alignRight',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells',
			'tableProperties',
			'tableCellProperties'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};
function MentionCustomization( editor ) {
  // The upcast converter will convert <a class="mention" href="" data-user-id="">
  // elements to the model 'mention' attribute.
  editor.conversion.for( 'upcast' ).elementToAttribute( {
      view: {
          name: 'a',
          key: 'data-mention',
          classes: 'mention',
          attributes: {
              href: true,
              'data-user-id': true
          }
      },
      model: {
          key: 'mention',
          value: viewItem => {
              // The mention feature expects that the mention attribute value
              // in the model is a plain object with a set of additional attributes.
              // In order to create a proper object, use the toMentionAttribute helper method:
              const mentionAttribute = editor.plugins.get( 'Mention' ).toMentionAttribute( viewItem, {
                  // Add any other properties that you need.
                  userId: viewItem.getAttribute( 'data-user-id' )
              } );

              return mentionAttribute;
          }
      },
      converterPriority: 'high'
  } );

  // Downcast the model 'mention' text attribute to a view <a> element.
  editor.conversion.for( 'downcast' ).attributeToElement( {
      model: 'mention',
      view: ( modelAttributeValue, { writer } ) => {
          // Do not convert empty attributes (lack of value means no mention).
          if ( !modelAttributeValue ) {
              return;
          }
          return writer.createAttributeElement( 'a', {
            class: 'mention',
            'data-mention': modelAttributeValue.id,
            'data-user-id': modelAttributeValue.userId
          }, {
              // Make mention attribute to be wrapped by other attribute elements.
              priority: 20,
              // Prevent merging mentions together.
              id: modelAttributeValue.uid
          } )
      },
      converterPriority: 'high'
  } );
}`

**Comment by FilipTokarski** [comment]
I copied your code and it works ok for me. Are you sure your document editor works fine without Mention plugin? Maybe the problem is somewhere else than this customization?  
It doesn't seem like the bug is in the editor/plugin.

**Comment by bakhiem** [comment]
My code is run ok without Mention plugin
This is how I implement that: 
1. Follow this link to build: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html
2. Then I copy build folder to node_modules
3. Import and config mention(but I don't think it cause error)
`import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document'`
```
      editor: DecoupledEditor,
      editorConfig: {
        language: 'vi',
        toolbar: ['heading', '|', 'bold', 'italic', 'NumberedList', 'BulletedList'],
        mediaEmbed: {
          removeProviders: ['dailymotion', 'spotify', 'vimeo', 'flickr', 'facebook', 'youtube']
        },
        mention: {
          feeds: [
            {
              marker: '@',
              feed: this.getFeedItems,
              minimumCharacters: 1,
              itemRenderer: this.customItemRenderer
            }
          ]
        },
      items : [
        { id: '@swarley', userId: '1', name: 'Barney Stinson', link: 'https://www.imdb.com/title/tt0460649/characters/nm0000439' },
        { id: '@lilypad', userId: '2', name: 'Lily Aldrin', link: 'https://www.imdb.com/title/tt0460649/characters/nm0004989' },
        { id: '@marshmallow', userId: '3', name: 'Marshall Eriksen', link: 'https://www.imdb.com/title/tt0460649/characters/nm0781981' },
        { id: '@rsparkles', userId: '4', name: 'Robin Scherbatsky', link: 'https://www.imdb.com/title/tt0460649/characters/nm1130627' },
        { id: '@tdog', userId: '5', name: 'Ted Mosby', link: 'https://www.imdb.com/title/tt0460649/characters/nm1102140' }
      ],
      }
    onEditorReady (editor) {
      editor.ui.getEditableElement().parentElement.insertBefore(editor.ui.view.toolbar.element, editor.ui.getEditableElement())
    },
```
  ```
  getFeedItems( queryText ) {
    return new Promise( resolve => {
        setTimeout( () => {
            const itemsToDisplay = this.items
                .filter( isItemMatching )
                .slice( 0, 10 );

            resolve( itemsToDisplay );
        }, 100 );
    } );
    function isItemMatching( item ) {
        const searchString = queryText.toLowerCase();
        return (
            item.name.toLowerCase().includes( searchString ) ||
            item.id.toLowerCase().includes( searchString )
        );
    }
},
    customItemRenderer( item ) {
    const itemElement = document.createElement( 'span' );

    itemElement.classList.add( 'custom-item' );
    itemElement.id = `mention-list-item-id-${ item.userId }`;
    itemElement.textContent = `${ item.name } `;

    const usernameElement = document.createElement( 'span' );

    usernameElement.classList.add( 'custom-item-username' );
    usernameElement.textContent = item.id;

    itemElement.appendChild( usernameElement );

    return itemElement;
}
```
When I type @, it show ok but when I click in one item, It cause that error

**Comment by Mgsy** [comment]
Just a quick note - which CKEditor 5 version do you use? Your problem sounds like a thing related to our API breaking change introduced in v22. Can you call `CKEDITOR_VERSION` in your browser console and share the version?

**Comment by bakhiem** [comment]
Thank you, I'd fix my problem by update version from 19 to 23. Thanks for your support :D
