### ISSUE TITLE
I Can't write with custom document editor

### ISSUE THREAD

**Issue by RPJOF** [ckeditor/ckeditor5#8276]
Hello,
 I create an online document editor or when I create it myself I can't write text, while when it's one already done, I can write about it. Is it a bug? Have a nice day.

E.g :
https://schoolmore.cf/doc/sample/
![image](https://user-images.githubusercontent.com/60546959/96282946-b0005b80-0fdb-11eb-8fbb-9232256139e1.png)

**Comment by RPJOF** [comment]
Hey ... ?

**Comment by Mgsy** [comment]
Hi, thanks for the report. Could you please share your build configuration, package.json and verify if you have any error in the console? 

> https://schoolmore.cf/doc/sample/

Unfortunately, there's no working example under this link.

**Comment by RPJOF** [comment]
Hello, I no longer have this error now because I recreate a publisher and now it works, but it happens to me a few times when I create my online editor. Have a good day and thank you!

**Comment by Mgsy** [comment]
> Hello, I no longer have this error now because I recreate a publisher and now it works, but it happens to me a few times when I create my online editor. Have a good day and thank you!

Make sure that you don't include Restricted editing plugin, as it allows editing only specific fields. You can read more about this feature [here](https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html).
