### ISSUE TITLE
App Crashed due to conversionApi is undefined

### ISSUE THREAD

**Issue by thanglv2** [ckeditor/ckeditor5#8279]
Hello, we're getting the below error while trying to paste rich text content into the text editor, it only happens after building in production mode whereas it works fine on dev mode. We followed strictly the Webpack configuration at this link  https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source

## 📝 Provide detailed reproduction steps (if any)

Paste a richtext content into the text editor

### ✔️ Expected result

Show up the correct content

### ❌ Actual result

Make the application crash and show this log in the console ("conversionApi" is undefined in the function createViewElementFromDefinition)

> Uncaught TypeError: Cannot read property 'writer' of undefined
>     at downcasthelpers.js:1527
>     at downcasthelpers.js:1520
>     at i (matcher.js:188)
>     at r.match (matcher.js:116)
>     at Ge.<anonymous> (upcasthelpers.js:755)
>     at Ge.fire (emittermixin.js:209)
>     at Ge._convertItem (upcastdispatcher.js:249)
>     at Ge._convertChildren (upcastdispatcher.js:282)
>     at Ge.upcastDispatcher.on.priority (upcasthelpers.js:448)
>     at Ge.fire (emittermixin.js:209)
>     at Ge._convertItem (upcastdispatcher.js:253)
>     at Ge.convert (upcastdispatcher.js:207)
>     at Object.callback (datacontroller.js:414)
>     at $n._runPendingChanges (model.js:830)
>     at $n.change (model.js:175)
>     at $e.toModel (datacontroller.js:413)

## 📃 Other details

* Browser: Chrome 86
* OS: MacOS 10.14.6
* CKEditor version: 23.0.0
* Installed CKEditor plugins: EssentialsPlugin, BoldPlugin, ItalicPlugin, HeadingPlugin

**Comment by Mgsy** [comment]
Hi, thanks for the report. Could you please share exact steps to reproduce (including the content which crashes the editor), so we'll be able to reproduce it locally?

**Comment by thanglv2** [comment]
Hi @Mgsy thanks for your reply, we found out that a plugin which we use in Webpack configuration (LodashModuleReplacementPlugin) led to that error, after updating/removing that plugin everything works fine now.
So it's not a problem from Ckeditor and I will close this issue.
