### ISSUE TITLE
[Edge] Selection jumps to the beginning of the word with code styling

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#828]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Open the sample with the code plugin.
2. Select some text.
3. Apply the code styling.
4. Put the caret at the end of the word.
5. Click on the word's right border.

## ✅ Expected result

Nothing happens.

## ❎ Actual result

Selection jumps to the beginning of the word.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/35917888-10bafc00-0c10-11e8-9f3c-4a2f86bf3e40.gif)

**Other information**
OS: Windows 10
Browser: Edge 16

**Comment by FilipTokarski** [comment]
I'm not able to reproduce it anywhere, seems to be fixed.
