### ISSUE TITLE
Add LinkImage to CKEditor Online Builder

### ISSUE THREAD

**Issue by jannejava** [ckeditor/ckeditor5#8282]
I am trying to configure the[ CKEditor Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) to allow linking of images. However, I cannot find the plugin LinkImage to make this possible.

_How the feature works now and what you'd like to change_?

Possible to select LinkImage as a plug-in in the list

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

Thanks in advance!

**Comment by Mgsy** [comment]
cc @ma2ciek

**Comment by ma2ciek** [comment]
Hi @jannejava!

It looks like we overlooked this plugin. We'll add it to the online builder soon, stay tuned :)

**Comment by ma2ciek** [comment]
@AnnaTomanek, @godai78, could you create a description for this plugin?

**Comment by godai78** [comment]
Something like this?  
  
The `LinkImage` plugin adds support for linking images. The feature may be used for numerous purposes, like linking to a high-resolution version of an image. Thumbnails may be used to link to another page or article. Same as banners linking to external pages. The image link can be added or edited via the image toolbar.

**Comment by ma2ciek** [comment]
Thanks!

**Comment by AnnaTomanek** [comment]
Give us a sec, @ma2ciek. @godai78 will go visit the online builder and research other plugin descriptions. And then come back with a sentence long one :wink:

**Comment by ma2ciek** [comment]
Sure, such a long description may not fit into the limited space.

**Comment by godai78** [comment]
You have no sense of party.  
  
Allows for adding clickable links to images, for creating banners od referrers.

**Comment by arezooalipanah** [comment]
> You have no sense of party.
> 
> Allows adding clickable links to images for creating banners or referrers.

what do i ?
