### ISSUE TITLE
Default font color turns to white

### ISSUE THREAD

**Issue by ZHICHENGH** [ckeditor/ckeditor5#8284]
Hi!
I made a ckeditor5 in a page success. However, When I inlay it into a pop-up window, The default font color becomes white. I do not understand why it happens :( Could you please give me some ideas about how to fix it?
Thanks!

**Comment by Oscarsgc** [comment]
@ZHICHENGH were you able to change the default color? I see the same behavior, text and cursor are white by default and they are missing since the editor background is white too
