### ISSUE TITLE
CkEditor5 Nuxt.js Integration with Custom Plugins

### ISSUE THREAD

**Issue by mohitsehgal** [ckeditor/ckeditor5#8285]
## 📝 Provide detailed reproduction steps (if any)
Hi, 
I wanted to integrate ckeditor5 with MathType plugin for adding support for mathematical equations.
I have done the following.

1. Import CkEditor-vue and ClassicEditor
```
let ClassicEditor
let CkEditor
if(process.browser){
    ClassicEditor = require( '@ckeditor/ckeditor5-editor-classic/src/classiceditor');
     CkEditor = require( "@ckeditor/ckeditor5-vue")
     console.log('ClassicEditor ', typeof( ClassicEditor.default().create))
}else{
     CkEditor = { component : {template:'<div></div>'}}
     ClassicEditor = {default(){
         
     }}
}
```
2.editor and editorConfig in `data`
```
 editor: ()=>{return ClassicEditor.default()},
             editorConfig:{},
```
3. Initiate the component
```
components: {
        ckeditor: CkEditor.component
    },
```

4. Integrated in the Template of my vue component.
```
<ckeditor
                        :editor="editor"
                        v-model="question.title"
                        :config="editorConfig"
                    ></ckeditor>
```

### ✔️ Expected result
CKEditor should be shown in my Nuxt App

### ❌ Actual result
Giving error
```
Class constructor ClassicEditor cannot be invoked without 'new'
```
I have spent a lot of time reading other posts on similar issues. I have not found anything in other issues, official documentation, or anywhere on the web.
Please help. I have invested a lot of time in `CKEditor` without any good return.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, thanks for the report. Currently, CKEditor 5 doesn't support Nuxt.js integration, so I'm afraid it would be difficult to tell you something more about the issue. We have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/6071) for the integration, so feel free to add :+1: to the first post and join the discussion to bump its popularity. Additionally, you can find some solutions posted in the issue which might be helpful.
