### ISSUE TITLE
unexpected internal errors for simple html input

### ISSUE THREAD

**Issue by voborl00** [ckeditor/ckeditor5#8299]
I am facing weird internal ckeditor errors while using pretty simple html fragment. Replicable by pasting following code samples to online classic editor example (https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) or using default classic editor offline.

snippet.js:4 Uncaught TypeError: Cannot read property 'childCount' of null
    at se.e.on.priority (snippet.js:4)

and

Uncaught CKEditorError: model-position-parent-incorrect

with "foo" replaced by <p>foo</p> (foo enclosed in paragraph tag)

original code

<table>
    <tbody>
        <tr>  
            <td>
                <table>
                    <tbody>
                        <tr>
                            <td>
                                <table>
                                    <tbody>
                                        <tr>
                                            <td style="font-weight: bold;">foo</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>

**Comment by voborl00** [comment]
html code in attached txt file

[template.txt](https://github.com/ckeditor/ckeditor5/files/5408685/template.txt)

**Comment by voborl00** [comment]
altered foo in paragraph attached

[template2.txt](https://github.com/ckeditor/ckeditor5/files/5408721/template2.txt)

**Comment by Mgsy** [comment]
Hi! Thanks for the report, we're aware of this issue and actually, it has been fixed - #8098. It will be released with the next CKEditor 5 version which is planned to be published on October the 28th, so stay tuned!
