### ISSUE TITLE
ckeditor hangs when typing

### ISSUE THREAD

**Issue by zackhalil** [ckeditor/ckeditor5#8303]
## 📝 Provide detailed reproduction steps (if any)

when typing users have found intermittent issues causing the ckeditor to hang. I found one way to reporduce it not sure if it others.

When I press ctrl-z i get the below error in JS console

17:34:23.245 Error: s.flat is not a function Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-s.flat is not a function
 1 ckeditor.js:5:7396
	o https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:7396
	rethrowUnexpectedError https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:7572
	enqueueChange https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:587108
	execute https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:723730
	decorate/< https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:375027
	fire https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:345553
	decorate/this[t] https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:375076
	execute https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:512299
	execute https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:592529
	e https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:590781
	set/< https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:590478
	fire https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:345553
	listenTo/< https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:590331
	fire https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:345553
	fire https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:437967
	onDomEvent https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:438108
	observe/</< https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:437885
	fire https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:345553
	n https://tomcat.boss-portal.com:8443/bOnline.SCC/ckeditor/ckeditor.js:5:431642

### ✔️ Expected result

the ckeditor to continue to work

### ❌ Actual result

ckeditor hangs when typing, that is no response. Sometimes i can type but backspace fails to work

## 📃 Other details

[ckeditor.zip](https://github.com/ckeditor/ckeditor5/files/5413400/ckeditor.zip)
[ckeditor5-build.zip](https://github.com/ckeditor/ckeditor5/files/5413408/ckeditor5-build.zip)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. Can you share the detailed steps to reproduce the issue?

**Comment by zackhalil** [comment]
I found issue... Im using app based on old version of firefox (56.0.2). Where array.flat is not avaliable.... I fixed by adding 

Object.defineProperty(Array.prototype, 'flat', {
    value: function(depth = 1) {
      return this.reduce(function (flat, toFlatten) {
        return flat.concat((Array.isArray(toFlatten) && (depth>1)) ? toFlatten.flat(depth-1) : toFlatten);
      }, []);
    }
});

to my JS
