### ISSUE TITLE
Getting Error while Creating Editable Inline Widget

### ISSUE THREAD

**Issue by harsh201** [ckeditor/ckeditor5#8304]
## Error while trying to insert text in editable inline widget
We want to create a editable inline widget, similar to what is [described here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html).
_What steps should be taken to fulfill the task?_
I created a similar widget to what is described in the link above.
My directory structure is:
widget
 - placeholder.js
 - placeholdercommand.js
 - placeholderediting.js
 - placeholderui.js

My editing file:
```javascript
export default class ConditionalPlaceholderEditing extends Plugin {
  static get requires() {
    return [Widget];
  }

  init() {
    console.log('ConditionalPlaceholderEditing#init() got called');
    this._defineSchema();
    this._defineConverters();
    this.editor.commands.add(
      'insertConditionalPlaceholder',
      new ConditionalPlaceholderCommand(this.editor)
    );

    this.editor.editing.mapper.on(
      'viewToModelPosition',
      viewToModelPositionOutsideModelElement(this.editor.model, (viewElement) =>
        viewElement.hasClass('conditionalPlaceholder')
      )
    );
  }

  _defineSchema() {
    const schema = this.editor.model.schema;

    schema.register('conditionalPlaceholder', {
      // Allow wherever text is allowed:
      allowWhere: '$text',

      // The placeholder will act as an inline node:
      isInline: true,

      isObject: true,

      // The placeholder can have many types, like date, name, surname, etc:
      allowAttributes: ['name'],
    });
  }

  _defineConverters() {
    const conversion = this.editor.conversion;

    conversion.for('upcast').elementToElement({
      view: {
        name: 'span',
        classes: ['conditionalPlaceholder'],
      },
      model: 'conditionalPlaceholder',
    });

    conversion.for('editingDowncast').elementToElement({
      model: 'conditionalPlaceholder',
      view: (modelItem, { writer: viewWriter }) => {
        const widgetElement = createPlaceholderView(modelItem, viewWriter);

        // Enable widget handling on a placeholder element inside the editing view.
        return toWidgetEditable(widgetElement, viewWriter);
      },
    });

    conversion.for('dataDowncast').elementToElement({
      model: 'conditionalPlaceholder',
      view: (modelItem, { writer: viewWriter }) => createPlaceholderView(modelItem, viewWriter),
    });

    // Helper method for both downcast converters.
    function createPlaceholderView(modelItem, viewWriter) {
      const placeholderView = viewWriter.createEditableElement('span', {
        class: 'conditionalPlaceholder',
      });

      const innerText = viewWriter.createText('{}');
      viewWriter.insert(viewWriter.createPositionAt(placeholderView, 0), innerText);

      return placeholderView;
    }
  }
}

```
The empty braces gets inserted normally, but when I try to edit it(add new text between braces), I get following error:
```
Uncaught TypeError: Cannot read property 'substr' of undefined
    at hl.<anonymous> (blockautoformatediting.js:113)
    at hl.fire (emittermixin.js:209)
    at hl._handleChangeBlock (document.js:317)
    at Rl._runPendingChanges (model.js:833)
    at Rl.enqueueChange (model.js:236)
    at Cd.execute (inputcommand.js:89)
    at Cd.<anonymous> (observablemixin.js:255)
    at Cd.fire (emittermixin.js:209)
    at Cd.<computed> [as execute] (observablemixin.js:259)
    at ua.execute (commandcollection.js:69)
```

Can you please help me with understanding what I am missing here?

**Comment by Mgsy** [comment]
Hi, thanks for the report. Unfortunately, editable inline widgets are not supported in CKEditor 5. We have an open feature request for this case, you can track it [here](https://github.com/ckeditor/ckeditor5/issues/1729). Feel free to add :+1: to the first post to bump its popularity and join the discussion.

**Comment by ndanvers** [comment]
> Hi, thanks for the report. Unfortunately, editable inline widgets are not supported in CKEditor 5. We have an open feature request for this case, you can track it [here](https://github.com/ckeditor/ckeditor5/issues/1729). Feel free to add  to the first post to bump its popularity and join the discussion.

I'm sorry I must be misunderstanding - 

The [link ](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html) is quite literally from the CKeditor version 5 documentation with a guide on how to achieve the solution, there is even a working demo.

How could it be the case, that this is not supported in Ckeditor5 as of now, if there are guides and documentation on the website?
