### ISSUE TITLE
Angular does not find the exported classes from super build

### ISSUE THREAD

**Issue by denisr-w** [ckeditor/ckeditor5#8307]
## 📝 Details
I'm using CKEditor5 super build with two classes: InlineEditor and BalloonEditor. I followed the instructions for super builds in [documentation ](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds). Everything works fine if I use compiled script in simple `index.html`. The problem that I'm faceing is when trying to use this script in Angular framework.

I did the following steps in my component:
1. `import * as CKSource from '../libs/ckeditor5-super-build/build/ckeditor.js';`
2. `public editor = CKSource.CKEDITOR.InlineEditor;`
3. `<ckeditor [editor]="editor" data="<p>Hello, world!</p>"></ckeditor>`

### ✔️ Expected result
I expect everything to work fine when serving the app.

### ❌ Actual result
I get an error `TypeError: Cannot read property 'InlineEditor' of undefined`

## 📃 Other details
Browser: Chrome
OS: Windows
CKEditor version: 5

**Comment by FilipTokarski** [comment]
Hi, I checked adding superbuild to Angular and it worked for me. Please note that when creating a superbuild your are already exporting and object with two editors, and then you are importing this object as `CKSource`. So when importing, this should be enough:
`public editor = CKSource.InlineEditor;`

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
