### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by monika1111** [ckeditor/ckeditor5#8310]
HI, I want to use ckEditor, after importing Table I get this issue https://prnt.sc/v3r7da..
I went trough this https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
 step by step  witch could be the reasons of this error, but as I see there is no reason to be this error, Can you please take a look? 

This is my Repository https://github.com/monika1111/ckEditor. Thanks

**Comment by mlewand** [comment]
@monika1111 can you double check if:

1.  removing `yarn.lock` and `package-lock.json` 
2.  `rm -rf node_modules && npm install`

solve the issue?

**Comment by monika1111** [comment]
Thank you for your quick response.
I have done as you said, but now I got another issue https://prnt.sc/v3st3g, That seems to be because of style-loader version.
When I wanted to change it **`npm install style-loader@1.0.0`**  got an error about ckeditor-duplicated-modules.

**Comment by Mgsy** [comment]
Hi @monika1111, as I can see you use Craco in your project. Currently, building the editor from the source can be done after [ejecting the project and modifying the Webpack config](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source). Unfortunately, we didn't test it with Craco, so it might behave unpredictably. However, there's some community solution for Craco project, which might be helpful in your case, see it [here](https://github.com/ckeditor/ckeditor5-react/issues/160#issuecomment-668558623).

We're aware that requiring ejecting a project might not be the best experience and this problem will be covered in [this issue](https://github.com/ckeditor/ckeditor5-react/issues/170).

**Comment by monika1111** [comment]
Now I don't get any error, I have used this article to use craco.
https://medium.com/@adamerose/using-ckeditor-5-in-create-react-app-without-ejecting-cc24ffb3fd9c
Thanks for your support👍

>
