### ISSUE TITLE
Add missing features to the `all-features` manual test

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8317]
http://localhost:8125/ckeditor5/tests/manual/all-features.html

Missing features:

- HTML Embed
- List styles
- Paste from Office

Would be good for having those all here.

**Comment by pomek** [comment]
Also, the list style plugin could be added.

**Comment by pomek** [comment]
I updated the ticket title and body. 
More features could be added and I mention some of them in the first post. I could miss something, so feel free to add it if missing.

**Comment by psmyrek** [comment]
There is probably a bug in `ImageResize` plugin used together with `HtmlEmbed` plugin which has `showPreviews` option set to `true` - see https://github.com/ckeditor/ckeditor5/issues/8433.
