### ISSUE TITLE
The editing root should remain focused when saving changes in the embed

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8318]
## 📝 Provide detailed reproduction steps (if any)

1.  Run an editor with a dynamic toolbar (inline, balloon) in http://fake.ckeditor.com:8125/ckeditor5-html-embed/tests/manual/htmlembed.html.
2.  Edit an embed.
3.  Save it.

### ✔️ Expected result

Widget is focused. The editor is focused. The toolbar remains visible.

### ❌ Actual result

The editor loses focus. The global toolbar disappears.

![](https://user-images.githubusercontent.com/1099479/96861787-e0754900-1464-11eb-884b-049760fed36d.gif)

## 📃 Other details

*   follow-up of #8301.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pkwasnik** [comment]
@oleq If the editor stays focused after save, how the user could close it to see the preview?

**Comment by oleq** [comment]
"Save" accepts the changes. "Cancel" discards them. Regardless of which one is clicked in the end, the editor (view root) should remain focused and the widget should also be selected (if selected before clicking "Edit").
