### ISSUE TITLE
[Safari@iOS] The previewless raw html text has too low contrast

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8320]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/features/html-embed.html.
2.  Disable previews.

### ✔️ Expected result

In Chrome on Mac:

![](https://user-images.githubusercontent.com/1099479/96869757-356a8c80-1470-11eb-86a7-0e20d18d5a53.png)

### ❌ Actual result

Safari in iOS:

![](https://user-images.githubusercontent.com/1099479/96869809-461b0280-1470-11eb-8abf-0f3fea67c01b.png)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Actually, is the contrast on desktop high enough? It's quite low too.
