### ISSUE TITLE
Inserting image above html embed and changing its align will result in increasing html embed height

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8324]
## 📝 Provide detailed reproduction steps (if any)

1.  insert html embed
2.  insert image above html embed
3.  change image align to left or right

### ✔️ Expected result

Image change align, but html embed will stay unchanged.

### ❌ Actual result

HTML embed increase its height covering image.

![](https://user-images.githubusercontent.com/16957311/96917102-bd6c8880-14a8-11eb-98a5-6a310ac0b112.gif)

## 📃 Other details

*   Browser: Chrome, Firefox
*   OS: Windows
*   CKEditor version: 23.0.0
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/pull/8330.
