### ISSUE TITLE
Allows rendering the `<script>` tag in HTML preview

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8326]
## 📝 Provide a description of the improvement

Right now, the scripts are being removed because we use the `Element#innerHTML` property for updating the preview container element.

https://github.com/ckeditor/ckeditor5/blob/64c87e53bbb589125a88f8ce772b9f4c57fedc5c/packages/ckeditor5-html-embed/src/htmlembedediting.js#L310-L319

We could parse the HTML string and append a proper structure to the element.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by wwalc** [comment]
I'd consider my case as irrelevant, but I just stumbled upon this problem when I tried to quickly embed a 3rd party library in CKEditor to showcase the potential of widgets.
