### ISSUE TITLE
Can't save an HTML embed after pasting a text from the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#8328]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a new HTML embed/edit the existing one.
2.  Select some text in the editor.
3.  Copy it.
4.  Paste it to the HTML embed.
5.  Save changes.

### ✔️ Expected result

Changes are saved.

### ❌ Actual result

Nothing happens.

## 📃 Other details

![](https://user-images.githubusercontent.com/20988892/96963900-c6417680-1509-11eb-80f2-a35a988629df.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
The same kind of error (missing selection on the widget element).

1. **Insert** an empty widget.
2. Enter.
3. **Insert** a second widget.
4. Click the first `textarea`.
5. Type whatever.
6. After saving changes, the second container will be modified.

![image](https://user-images.githubusercontent.com/2270764/96964870-824f7100-150b-11eb-87e7-455b06372e08.png)

**Comment by pkwasnik** [comment]
Another similar bug:

1.  Insert or edit widget (do not save)
2.  Click anywhere outside the widget
3.  Try to save
4.  Nothing happen

**Comment by psmyrek** [comment]
I've created a follow-up #8509 to provide a generic solution for selecting a widget, which has the `data-cke-ignore-events` attribute.
