### ISSUE TITLE
Better documentation for how to use lark?

### ISSUE THREAD

**Issue by burtonator** [ckeditor/ckeditor5#8339]
## 📝 Provide a description of the improvement

I've gone through the documentation and I'm very confused at how to get lark working.  Note that I consider myself pretty advanced in React / CSS etc but I think maybe I'm missing something entirely with the docs.

I've made the change to webpack to add the loaders, not receiving any build errors but the lark theme just isn't being used.

I assume I have to 

import '@ckeditor/ckeditor5-theme-lark'

... but that's just a blank CSS file.

Importing this doesn't work either.

import '@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-editor-classic/classiceditor.css';

... doesn't work either.  

## 📃 Other details

* Browser: 
* OS: MacOS Catalina
* CKEditor version
* Installed CKEditor plugins:

    "@ckeditor/ckeditor5-build-classic": "=23.0.0",
    "@ckeditor/ckeditor5-build-balloon": "=23.0.0",
    "@ckeditor/ckeditor5-react": "=2.1.0",
    "@ckeditor/ckeditor5-theme-lark": "=23.0.0",
    "@ckeditor/ckeditor5-dev-utils": "=23.6.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "=23.6.0"

---

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Have you followed https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source @burtonator?

**Comment by burtonator** [comment]
@oleq I did but still having problems.  We have our own webpack config but pretty sure all the changes were merged

**Comment by burtonator** [comment]
@oleq looks like the style-loader works but the postcss for lark isn't being used.

**Comment by Mgsy** [comment]
Hi @burtonator, I'm sorry for a late reply. Could you please provide some steps to reproduce the problem, so we'll be able to see it locally?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity. If you'll have further questions regarding this issue, feel free to ask, I will re-open the ticket.
