### ISSUE TITLE
Autoformat creates additional undo steps

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#834]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Type something using autoformatting, i.e. `*test*`.
3. Undo few times.

## ✅ Expected result

After first undo, styling is lost.

## ❎ Actual result

Nothing happens, there are empty undo steps.

## 📃 Other details that might be useful

**Notes**

It's a regression. Here is the first bad revision - https://github.com/ckeditor/ckeditor5/commit/b279e7e9523a21f47d3d1cca9461b9a4bf96b052.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36092152-a43ae966-0fe6-11e8-824d-12edd8ecb85f.gif)

**Other information**

OS: Windows 10, MacOS X
Browser: All browsers

**Comment by Reinmar** [comment]
This was already reported. Could you search for it?

**Comment by Mgsy** [comment]
>This was already reported. Could you search for it?

Are you sure? I can't find it. Similar one was reported here https://github.com/ckeditor/ckeditor5/issues/781.

**Comment by Reinmar** [comment]
Ah, right. I meant that one. But they seem to be heavily related.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore.
