### ISSUE TITLE
Editable gets a weird extra scroll when it ends with a small HTML embed 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8340]
## 📝 Provide detailed reproduction steps (if any)

1.  Create content that and with an HTML embed that has only e.g. one character.
2.  Put the selection in a content preceding that embed.

### ✔️ Expected result

The editable should have no scroll as it's not styled with any overflow and height limitations.

### ❌ Actual result

![](https://user-images.githubusercontent.com/156149/97144769-562f2c80-1765-11eb-9232-b228153b536c.png)

Bonus point. In our docs the scroll appears only when the widget is not selected. In manual tests I can see that the scroll changes its height but it's shown in both cases.

![](https://user-images.githubusercontent.com/156149/97144801-634c1b80-1765-11eb-8df5-78337bb7424c.gif)

## 📃 Other details

This happens on every browser. 

I tried to figure out what's leaking out of the embed but I couldn't. My wild guess is that it may be something with using flex, but I can be very wrong.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Is this issue still valid? I wasn't able to reproduce it.

**Comment by niegowski** [comment]
Ok, a tooltip for the edit button is causing this.

**Comment by Reinmar** [comment]
Can we add a padding at the bottom of the editable in this particular demo? :D

**Comment by Reinmar** [comment]
Or display the tooltip on the left of the button. For all embeds ;)
