### ISSUE TITLE
Assign errors found in CI build to proper categories

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#8344]
## 📝 Provide a description of the improvement

Currently the `scripts/continuous-integration-script.js` assigns all errors found during CI build as unit tests errors, because [the `add` method is always called on the `unitTests` set](https://github.com/ckeditor/ckeditor5/blob/32efc5f68f82c24b0e5070b0aa5a960262d591e8/scripts/continuous-integration-script.js#L134). It should be changed to something like `failedChecks[ checkName ].add( packageName );`

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Fixed in the past, https://github.com/ckeditor/ckeditor5/blob/768466c6e0e18b0f4c2230b1f66a2defb2496c50/scripts/continuous-integration-script.js#L138.
