### ISSUE TITLE
[Edge] Selection moves to the beginning of the document after 'select all' from the contextual menu

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#835]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Right-click on the image.
3. Click on `select all`.

## ✅ Expected result

Whole content is selected.

## ❎ Actual result

Selection moves to the beginning of the document.

## 📃 Other details that might be useful

**Notes**

Selecting all with <kbd>Ctrl</kbd> + <kbd>A</kbd> works properly.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36103711-6d1194a6-1010-11e8-8034-15e1f4e07198.gif)

**Other information**

OS: Windows 10
Browser: Edge

**Comment by ma2ciek** [comment]
Does `select all` work well in other cases? I mean outside of the nested editables?

**Comment by Mgsy** [comment]
>Does select all work well in other cases? I mean outside of the nested editables?

Yes, it works properly in other cases. It also works good inside the caption. Problem occurs when you open the contextual menu on the image.

**Comment by FilipTokarski** [comment]
This issue does not exist in the new upcoming Edge v.79.0.309.56.

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
