### ISSUE TITLE
Source Editing Area

### ISSUE THREAD

**Issue by monika1111** [ckeditor/ckeditor5#8351]
I see that ckEditor4 has a feature Source Editing Area
![image](https://user-images.githubusercontent.com/16905883/97271581-2e65c480-184a-11eb-8b27-02d7e9127b74.png)

But I can't find this module for ckEditor5.

Can you please tell me how can I use this feature for ckEditor5?

Thanks

**Comment by Mgsy** [comment]
Hi, the view source feature is not available in CKEditor 5. There's a dedicated issue related to this feature, you can read the discussion [here](https://github.com/ckeditor/ckeditor5/issues/592).
