### ISSUE TITLE
Difference conversion vs mapper

### ISSUE THREAD

**Issue by B4rtes** [ckeditor/ckeditor5#8356]
Hi Team,

Could you please explain the difference between conversion (downcast, upcast) and mapper?

As far as I uderstand, mapper is used for complex conversion, but I haven't found good example to sort it out.

Thanks

**Comment by jodator** [comment]
In short `mapper` is used to map `model` element with a corresponding `view` element during [downcast conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#conversion).

When using [conversion helpers](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html), like [`elementToElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-elementToElement) you don't need to worry about it. It is used in [custom element conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/custom-element-conversion.html).

The best way to start is to read followng guides:

*   [creating a simple plugin](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)
*   [implementing a block widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html)
*   [conversion introduction](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html) and linked guides
