### ISSUE TITLE
Raw HTML widget buttons don't reflect commands state

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#8357]
## 📝 Provide detailed reproduction steps (if any)

Raw HTML widget buttons don't reflect commands state. When the editing command is disabled, the edit and save buttons should be disabled as well. This happens for example when track changes is turned off (the feature is not yet integrated with TC).

**Comment by pkwasnik** [comment]
We agreed with @scofalik that only the save button should be disabled when editing command is disabled. Edit button can't be linked to updateHtmlEmbed. It is disabled when the focus is outside of the widged, so each time user will want to edit, will need first to select the widged. Anyway for edit button it is not a problem to stay enabled.
