### ISSUE TITLE
Old view element should be unbound after reconversion is done

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#8358]
## 📝 Provide detailed reproduction steps (if any)

When reconversion happens, the old view element is removed but it is not unbound, because we want to use it to get its children (without reconverting those children).

However, this element is never unbound which is incorrect. This causes an error, because markers that were created on that view element will still be bound to the old view element.

**Comment by jodator** [comment]
Closed by: [`cc7851a`](https://github.com/ckeditor/ckeditor5/commit/cc7851aded211bffe999e8257c713749e5ff43ab).

**Comment by jodator** [comment]
> However, this element is never unbound which is incorrect. This causes an error, because markers that were created on that view element will still be bound to the old view element.

Good catch - I didn't think that markers could retain elements as well. I was focus on the view-to-model bindings only. Since the binding was removed it seemed OK to not unbind it explicitly.
