### ISSUE TITLE
How to load the Placeholder from server response

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5#8360]
## Provide a description of the task

Hi Team

i have completed the placeholder by following link
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

i have an requirement to load the placeholder from the server response

instead of below code i would to like to load the from server response.

![image](https://user-images.githubusercontent.com/67726510/97318324-1ee27d80-1842-11eb-918d-df861e7c2546.png)

dynamic server response
[ 'date', 'first name', 'surname' , etc...]

And also i want to load the data from the server whenever placeholder expanding

![image](https://user-images.githubusercontent.com/67726510/97318365-2c980300-1842-11eb-85cf-7ad575d38255.png)

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Mgsy** [comment]
Hi, how about fetching the data from the server before the editor initialization and passing them to the editor config?
