### ISSUE TITLE
How to block the file dialog open based on condition

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5#8361]
## Provide a description of the task

Dear Team

I have created the custom plugin for upload files.
![image](https://user-images.githubusercontent.com/67726510/97318724-8bf61300-1842-11eb-803f-6e6521da25dd.png)

**when i click on the upload attachment icon below dialog view getting open**

![image](https://user-images.githubusercontent.com/67726510/97318792-9dd7b600-1842-11eb-921b-46e15e20076f.png)

In this case i would like to block the File dialog window based on condition
Example
If i uploaded the three attachments already. i need to show an alert otherwise the FileDialog should open.

Just give me an example with like below condition, will do that as per condition
let a = 3;
if(a == 3)
alert()
else
file dialog should open

Custom Plugin Code

class UploadAttachment extends Plugin {
init() {

        const editor = this.editor;

        editor.ui.componentFactory.add('uploadAttachment', locale => {

            const view = new FileDialogButtonView(locale);

            view.set({
                acceptedType: '*',
            });

            view.buttonView.set({
                label: 'Upload Attachment',
                icon: UploadAttachmentIcon,
                tooltip: true
            });

            view.on('done', (evt, file) => {

               //This block will trigger when we select the file 
            });

            return view;
        });
    }
}

Added to the toolbar
toolbar:['uploadAttachment']
Added to extraPlugin
extraPlugins: [
UploadAttachment
],

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Mgsy** [comment]
Hi, thanks for the report. [`FileDialogButtonView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_upload_ui_filedialogbuttonview-FileDialogButtonView.html) is responsible for opening the native file selection dialog, so if you'd like to implement a custom dialog, you should create a custom solution.

However, if you'd like to use it and just block the native dialog, you can listen to the [`ButtonView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_buttonview-ButtonView.html) execute event and stop it with a higher priority. See the code below:

```javascript
const view = new FileDialogButtonView(locale);
const buttonView = view.buttonView;

// ...

buttonView.on( 'execute', evt => {
	evt.stop();
}, { priority: 'high' } );
```
