### ISSUE TITLE
Get rid of conversion API references from the mention attribute value

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8370]
## Provide a description of the task

1.  The attribute converter sets the attribute value using `_toMentionAttribute()` helper https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-mention/src/mentionediting.js#L52
2.  The helper gets the conversion API object during the conversion.
3.  The helper merges the conversion API object (`data`) with the attribute value https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-mention/src/mentionediting.js#L86-L102
4.  ...using `Object.assign()` in https://github.com/ckeditor/ckeditor5/blob/8dbcf217887f5c2c621d03325f9853ccfde4f60d/packages/ckeditor5-mention/src/mentionediting.js#L71.

And the result looks like this:

![](https://user-images.githubusercontent.com/1099479/97442168-d43c3080-1929-11eb-98c3-b14ad82fc1ad.png)

The attribute value is full of crazy references that have nothing to do with the content. This caused the [ckeditor5-inspector to throw](https://github.com/ckeditor/ckeditor5-inspector/pull/102) because of circular references (e.g. in `writer`) when inspecting a mention. Although the inspector is OK now (we'd hit this issue sooner or later, so the fix makes sense), the value of the mention attributes should be revisited because this asks for trouble.

**Comment by oleq** [comment]
A hotfix https://github.com/ckeditor/ckeditor5/tree/hotfix/mention-conversion-api-update waiting for tests.

**Comment by jodator** [comment]
I'm not sure about the tests though - on one hand, we didn't catch that but on the other hand we probably could detect that extra attributes were set on the mention. :/

**Comment by oleq** [comment]
The missing assertion IMO is `expect( Object.keys( attributeValue ) ).to.have.members( [ 'id', other props that make sense… ] )`
