### ISSUE TITLE
Custom Plugin - Formatting + "Implementing an inline widget" tutorial

### ISSUE THREAD

**Issue by IgorWolbers** [ckeditor/ckeditor5#8371]
I am using the documentation to create a plugin to do something very similar to the tutorial [Implementing an inline widget][1]. My only issue with the documentation, and where I am currently stuck, is that it does not mention or have any code to be able to apply additional formatting to the view although it does appear that the model is changed. Can you help me better understand how standard formatting could be applied to the corresponding view in this tutorial?

Here is a gif of what I am referring to. The plugin code that is running is the code copied from the [inline widget tutorial][1].

![inline-widgit - formatting](https://user-images.githubusercontent.com/6107962/97445433-a217d800-1903-11eb-9796-86c3138451d1.gif)

Thank you in advance.

[1]:https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

**Comment by Mgsy** [comment]
Hi, thanks for the report! Styling inline widgets in CKEditor 5 is [not supported](https://github.com/ckeditor/ckeditor5/issues/1633). You can find more information in the linked issue, feel free to add :+1: to the first post and join the discussion to bump its popularity.
