### ISSUE TITLE
Changelog corrections for iteration 37

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#8373]
## Provide a description of the task

Changelog for the new release is up https://github.com/ckeditor/ckeditor5/blob/release/CHANGELOG.md. Feel free to fine-tune it directly on the `release` branch.

**Comment by pomek** [comment]
> Please note that there are some **major** breaking changes. Be sure to review them before upgrading.

Shouldn't be **minor**?

**Comment by mlewand** [comment]
@pomek good call, corrected.

**Comment by godai78** [comment]
Committed to release.

**Comment by AnnaTomanek** [comment]
Some post-fixes done in 429a620. Ready to :rocket: !
