### ISSUE TITLE
How to restrict image upload by size when using Base64 image upload adapter

### ISSUE THREAD

**Issue by ankitkumarsuthar** [ckeditor/ckeditor5#8376]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

--- I need to know the uploaded image size and based on that I want to decline that upload or allow it. 

I am using the "Base64 image upload adapter" for image upload and want to know the size of the uploaded images and also want to restrict image upload if image size is higher than a particular size like (1mb).

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. This feature request has been [already reported](https://github.com/ckeditor/ckeditor5/issues/5657), so I'm closing it as a duplicate. Feel free to add :+1: to the first post and join the discussion to bump its popularity.
