### ISSUE TITLE
"Page brack" & "Pagination" not working when added in build at once. 

### ISSUE THREAD

**Issue by ankitkumarsuthar** [ckeditor/ckeditor5#8382]
## 📝 Provide detailed reproduction steps (if any)

1. I have created a custom build from the official site (I will add an image of my build)
2. Download it and it's not working and showing errors in the console. 

My customer build a plugin image which has added.
https://ibb.co/0QkMPJ4

Also this error in the console:
`Cannot destructure property 'pageWidth' of 't[_0x734c(...)][_0x734c(...)](...)' as it is undefined`

### ✔️ Expected result

_What is the expected result of the above steps?_

Need to run the "Page brack" & "Pagination" plugins. 

### ❌ Actual result

_What is the actual result of the above steps?_

The editor is not working.

## 📃 Other details

* Browser: crome
* OS: windows
* CKEditor version: CKEditor 5 document edition 
* Installed CKEditor plugins: … 

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, this issue occurs because you have to add a configuration for Pagination plugin. We are aware of this issue, you can find more information [here](https://github.com/ckeditor/ckeditor5/issues/8238).
