### ISSUE TITLE
Placeholder doesn't immediately disappear completely in Safari

### ISSUE THREAD

**Issue by winzig** [ckeditor/ckeditor5#8385]
## 📝 Provide detailed reproduction steps (if any)

1. In Safari 14 (and possibly earlier?) go to https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html
2. Click into the editing area and notice that ~1 second passes before the placeholder space disappears and the cursor resets itself to the beginning of the line:

![screenshot 2020-10-30 at 15 25 19](https://user-images.githubusercontent.com/127062/97762163-eb635580-1ac4-11eb-9667-254b8a036e3e.gif)

### ✔️ Expected result

Placeholder should completely disappear instead of leaving the cursor floating out to the right.

(I also agree with #8058 that the placeholder shouldn't actually disappear until the user starts typing, but I'm guessing that would require more of an overhaul to fix.)

### ❌ Actual result

In Safari 14, the text of the placeholder disappears, but the space it took up takes another second or so to disappear, creating a weird effect (see gif above).

## 📃 Other details

* Browser: Safari 14.0
* OS: macOS 10.15.7
* CKEditor version: Latest on ckeditor.com website (currently v23)
* Installed CKEditor plugins: Whatever is installed on the ckeditor website (don't think it matters)

**Comment by Mgsy** [comment]
Hi, thanks for the report. We're aware of this issue and it's already reported, you can find it [here](https://github.com/ckeditor/ckeditor5/issues/4078). Feel free to add :+1: to the first post and join the discussion to bump its popularity.

**Comment by winzig** [comment]
It's 3 years old and hasn't been commented on in 2 years, but ok.

**Comment by oleq** [comment]
For anyone interested, #8689 resolved this issue.
