### ISSUE TITLE
Super build results in ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by KoalaBear84** [ckeditor/ckeditor5#8386]
## 📝 Provide detailed reproduction steps (if any)

I'm following [Creating “super builds”](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds) and run into [ckeditor-duplicated-modules](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules)

1. git clone -b stable https://github.com/ckeditor/ckeditor5-build-classic.git
2. cd ckeditor5-build-classic
3. npm install
4. Steps from [Creating “super builds”](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds)
5. npm run build

### ✔️ Expected result

Working build with Classic and Inline.

### ❌ Actual result

```
ckeditor.js:formatted:222 Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
    at Object.<anonymous> (ckeditor5-build-classic/build/ckeditor.js:5:9399)
    at Object.<anonymous> (ckeditor5-build-classic/build/ckeditor.js:5:9473)
    at n (ckeditor5-build-classic/build/ckeditor.js:5:3571)
    at Module.<anonymous> (ckeditor5-build-classic/build/ckeditor.js:5:442325)
    at n (ckeditor5-build-classic/build/ckeditor.js:5:3571)
    at ckeditor5-build-classic/build/ckeditor.js:5:4370
    at ckeditor5-build-classic/build/ckeditor.js:5:4381
    at ckeditor5-build-classic/build/ckeditor.js:5:3432
    at ckeditor5-build-classic/build/ckeditor.js:5:3436
```

## 📃 Other details

* Browser: Edgium 88 dev
* OS: Windows 10 2004 Pro
* CKEditor version: Latest from https://github.com/ckeditor/ckeditor5-build-classic.git
* Installed CKEditor plugins: Default from https://github.com/ckeditor/ckeditor5-build-classic.git

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
Hi @KoalaBear84!

I'm aware that you were using outdated docs for some reason. Could you hard refresh the page to clear the cache and try again? You should see the following:

![](https://user-images.githubusercontent.com/2768047/97810877-52c10700-1c77-11eb-98ed-34844a7e39b9.png)

**Comment by KoalaBear84** [comment]
The docs are still the same, what should be changed?

**Comment by ma2ciek** [comment]
> Or because I use [https://github.com/ckeditor/ckeditor5-build-classic.git](https://github.com/ckeditor/ckeditor5-build-classic.git) ?

The https://github.com/ckeditor/ckeditor5-build-classic.git is an outdated repository and everything was merged into the `ckeditor5` repository. 

> The docs are still the same, what should be changed?

Have you tried to go to https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds and run CTRL/CMD + SHIFT + R?

**Comment by KoalaBear84** [comment]
Thanks for your quick help. I didn't knew that the original repository was archived / obsolete. Started this a little over a year ago, so the scripts didn't work anymore.

The only thing that was wrong is the repository url. Changed it to the new main ckeditor one, and changed the paths which fixed it. 😃

New steps (for me):

1. git clone -b stable https://github.com/ckeditor/ckeditor5.git
2. cd ckeditor5/packages/ckeditor5-build-classic
3. npm install
4. Steps from Creating “super builds”
5. npm run build

**Comment by DaveOrDead** [comment]
Hey team, I've had this same issue on the latest version (31) of ckeditor5 trying to create a super build of classic and inline editors.

I followed the steps above:

    1.  `git clone -b stable https://github.com/ckeditor/ckeditor5.git`
    2.  `cd ckeditor5/packages/ckeditor5-build-classic`
    3. `npm install`
    4. Steps from [Creating “super builds”](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds)
    5. `npm run build`

At runtime I am getting `plugincollection-plugin-name-conflict {"pluginName":"Delete"}` 

This was working fine actually on version 27 so it could be something that has changed in the interim. Should I open a new issue for this?

Thanks :)

**Comment by ma2ciek** [comment]
:point\_up: I guess that you might have a `yarn.lock` or `package-lock.json` file. Could you remove it, reinstall the environment and test it again?

**Comment by DaveOrDead** [comment]
Hey @ma2ciek thanks for coming back to me.

I should have said, I have tried removing both the `package-lock.json` file and deleting `node_modules` and reinstalling the environment cleanly but still getting the same results

**Comment by ma2ciek** [comment]
Thanks.

Could you, @DaveOrDead, open a new issue if you think it's a valid one? And provide your `package.json` file?

**Comment by kumawat30rahul** [comment]
but how do i use this editor another react project?

**Comment by Witoso** [comment]
@kumawat30rahul please don't comment on non-related closed issues. [The usage of the editor in React is documente](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html#quick-start)d.
