### ISSUE TITLE
How to display content with MathType formulas?

### ISSUE THREAD

**Issue by danisetg** [ckeditor/ckeditor5#8387]
Hi,

I am trying to use the mathType plugin on my custom cdkeditor build. In the editor, everything works great, but if I try to display its output data using div innerHtml, the math formulas don't look correct.

Also the inline latex "$$\mylatex code$$" doesn't change in the output.

I don't know if using innerHtml is the correct way to display the output data to the final user who can only view the content, so, any ideas in how to correctly achive this will be really appreciate.

**Comment by ma2ciek** [comment]
I transferred this issue to the CKEditor 5 repository as it is not Angular-specific. 

cc @Mgsy - do you recognize such problems? Was there a problem with styling data after `editor.getData()`?

**Comment by Mgsy** [comment]
> I am trying to use the mathType plugin on my custom cdkeditor build. In the editor, everything works great, but if I try to display its output data using div innerHtml, the math formulas don't look correct.

Hi, by default MathType returns HTML containing [MathM](https://developer.mozilla.org/en-US/docs/Web/MathML)L, which is [not supported in all browsers yet](https://caniuse.com/mathml). It should render properly in Firefox. I'm not sure what is your exact problem, however, could you try to open your content in Firefox and see whether it works?

**Comment by danisetg** [comment]
> Hi, by default MathType returns string containing [MathM](https://developer.mozilla.org/en-US/docs/Web/MathML)L, which is [not supported in all browsers yet](https://caniuse.com/mathml). It should render properly in Firefox. I'm not sure what is your exact problem, however, could you try to open your content in Firefox and see whether it works?

Hi, thanks for the reply. My problem is exactly that. It seems that MathType is not supported in Chrome yet. It looks fine in firefox, but only the formulas created using the MathType editor, if I write latex inline code, it does not render.

I haven't found a real solution but I managed to achive what I want by not using MathType but just writing the formulas with latex code between '$' symbols, and then rendering the output using a module named ng-katex, instead of the div innerHtml.

**Comment by Mgsy** [comment]
Unfortunately, there's not much you can do in terms of MathML support in the browsers, however, you can use some math rendering engine which will handle MathML on your page, e.g. [MathJax](https://www.mathjax.org/).
