### ISSUE TITLE
ImageResize plugin translation wrong

### ISSUE THREAD

**Issue by zhangyu1818** [ckeditor/ckeditor5#8388]
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

zh-cn

![image](https://user-images.githubusercontent.com/11534968/97823466-0e278100-1cf4-11eb-99b4-7918f37afae9.png)

en

![image](https://user-images.githubusercontent.com/11534968/97823507-2bf4e600-1cf4-11eb-99f4-222a8cdd75c9.png)

* Browser: …
* OS: …
* CKEditor version: 23.1.0
* Installed CKEditor plugins: 23.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. CKEditor 5 translations are created with a help of the community on [Transifex](https://www.transifex.com/ckeditor/ckeditor5/) and were reviewed by contributors who know Chinese. If you believe that some translations are not correct, please report it on Transifex. Thank you for your contribution!
