### ISSUE TITLE
Focusing the link in read-only mode activates the contextual toolbar

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#839]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the article sample with the contextual toolbar plugin.
2. Turn on the read-only mode.
3. Put the selection in `Paragraph`.
4. Press <kbd>Tab</kbd> to focus the link.
5. Select some text.

## ✅ Expected result

The contextual toolbar is hidden.

## ❎ Actual result

The contextual toolbar appears.

## 📃 Other details that might be useful

**Notes**

I'm not able to reproduce it in the [ContextualToolbar sample](http://localhost:8125/ckeditor5-ui/tests/manual/contextualtoolbar/contextualtoolbar.html).

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36143057-4da4510e-10aa-11e8-934d-e461d5acf21a.gif)

**Other information**

OS: Windows 10, MacOS X
Browser: All browsers

**Comment by oleq** [comment]
I tried to reproduce it in http://localhost:8125/ckeditor5-core/tests/manual/readonly.html but to no avail. Can you still reproduce this issue?

**Comment by Mgsy** [comment]
Nope, it's not reproducible anymore 🎉
