### ISSUE TITLE
Research exposing CKEditor 5 API as a global object

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8399]
## Provide a description of the task

Exposing CKEditor5 global object (available on `window`) and dot access to classes (base editor API). 

*   it might require better naming for some classes/methods
*   it might require to make CKE5 as main entry package, see also: #1061.

Requirements to met:

*   [ ] Adding a plugin to a build (might be a new build type).
*   [ ] Using imports from base editor plugins (`core`, `engine`, `utils` \<`EmitterMixin`\>, `ui`).
*   [ ] Using imports from "common" plugins (`widget`, `clipboard`, ... ).
*   [ ] Potential to solve CSS double import issue [#8400](https://github.com/ckeditor/ckeditor5/issues/8400).

**Comment by jodator** [comment]
TIL: you can load anything from the exported DLL:

![](https://user-images.githubusercontent.com/247363/99969319-90a6dc00-2d9a-11eb-9286-68229e07c266.png)

So you _could_ tinker with the exposed DLL. Not the best API though.

**Comment by jodator** [comment]
> So you _could_ tinker with the exposed DLL. Not the best API though.

This could be improved somehow, though.

1.  Real global object exposed on `window`.
2.  Use own module ID plugin for webpack ([docs](https://webpack.js.org/configuration/optimization/#optimizationmoduleids), [source](https://github.com/webpack/webpack/blob/b9c50fdb090cac8def50e576676463c739bd3046/lib/ids/NamedModuleIdsPlugin.js#L20)).

Side note as for 1: I've tried to use `libraryEntryPoint` but it fails with DLL.

**Comment by pomek** [comment]
I would see: `CKEditor('module:engine/model/position~Position')`. But, it may be just a wish.

**Comment by jodator** [comment]
So this task can be also closed as the research proved that we're going with DLL + custom webpack plugin to expose global: #8521.
