### ISSUE TITLE
[Chrome/Edge/Firefox] Incorrect selection after turning off the read-only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#840]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Turn on the read-only mode.
3. Select some text.
4. Turn off the read-only mode without losing the focus on the editor.
5. Try to type something.

## ✅ Expected result

User is able to type.

## ❎ Actual result

Text is selected, but user isn't able to delete it/type.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36148041-dd0d5e5c-10ba-11e8-8f57-676dc9d30c62.gif)

**Other information**

OS: Windows 10, MacOS X
Browser: Chrome, Edge, Firefox

**Comment by Reinmar** [comment]
That was actually a problem with the test. After clicking the button the test editable was blurred. The same if you change the read only mode via the console. So I fixed this by focusing the editable.
