### ISSUE TITLE
some features of ckEditor4 are not visible

### ISSUE THREAD

**Issue by monika1111** [ckeditor/ckeditor5#8403]
I have set toolbar like this 
![image](https://user-images.githubusercontent.com/16905883/97879670-b14eb980-1d39-11eb-8c0c-f04198f253be.png)
but I cant see any features, e.g. Font Size..

![image](https://user-images.githubusercontent.com/16905883/97879827-dba07700-1d39-11eb-8e14-0674f6daded7.png)

Can you please tell me the reason?

**Comment by FilipTokarski** [comment]
Hi, CKEditor4 and CKEditor5 are completely separate apps and this repository is for CKEditor5. Please report your issue in [CKEditor4 issue tracker](https://github.com/ckeditor/ckeditor4/issues).  
I'm closing ticket this as invalid.
