### ISSUE TITLE
Table widgets can be floating outside of the editor when the editor size is limited

### ISSUE THREAD

**Issue by LangQian** [ckeditor/ckeditor5#8410]
## 📝 Provide detailed reproduction steps (if any)

1. Limit the size of the editor (height/width)
2. Enter enough content and a table so that the table can be hidden by scrolling it up/down.
3. Bring up the table toolbar, or bring up the table/table cell property widget, then scroll the table away until it's not visible in the editor.

### ✔️ Expected result

The toolbar/widgets should be closed when the corresponding table/cell is not visible in the editor.

### ❌ Actual result

The toolbar/widgets are floating outside of the editor. See the following screenshots:
1. Table toolbar:
![Screen Shot 2020-11-03 at 12 06 57 PM](https://user-images.githubusercontent.com/16005923/98018947-2ae4b700-1dcf-11eb-90b8-ca406227f031.png)

2. Table cell properties:
![Screen Shot 2020-11-03 at 12 05 24 PM](https://user-images.githubusercontent.com/16005923/98018948-2b7d4d80-1dcf-11eb-99f6-20cb939b4349.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this issue and we're tracking it here https://github.com/ckeditor/ckeditor5/issues/5328. I'll close this ticket as a duplicate.
