### ISSUE TITLE
Table Cell/Table Properties Configuration Pop-up Could be Cut Off

### ISSUE THREAD

**Issue by LangQian** [ckeditor/ckeditor5#8420]
## 📝 Provide detailed reproduction steps (if any)

1. Limit the size of CK Editor (width, height)
2. Place CK Editor at somewhere near the edge of the browser
3. Bring up the table/table cell properties configuration pop-up

### ✔️ Expected result

The pop-up widget should be fully visible by:
1. Scroll within CK Editor.
OR
2. Scroll the parent widget of CK Editor

### ❌ Actual result

The direct parent of this pop-up is "body" element, since in our product, "body" shouldn't be scrollable, there is no way for us to see the full widget.

![Screen Shot 2020-11-05 at 3 25 11 PM](https://user-images.githubusercontent.com/16005923/98293884-09293280-1f7d-11eb-891b-3cfce4f3ffe3.png)
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
There's a chance it will be resolved by a fix for #5328.

**Comment by Witoso** [comment]
Looks like solved in the `v40.0.0`, I couldn't get an effect of cut off popup at the end of the page.

![](https://github.com/ckeditor/ckeditor5/assets/9881379/f2853b00-2cd2-4240-99c4-1bca49f08ee0)
