### ISSUE TITLE
Custom attributes not respecting copyOnEnter: false

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#8428]
## 📝 Provide detailed reproduction steps (if any)

1. Define a custom attribute on headings (see below)
2. Set the attribute property `copyOnEnter: false`
3. Add a heading to the document
4. Set the custom attribute on the heading
5. Hit enter

### ✔️ Expected result

When you hit enter, the custom attribute should not be copied to the paragraph.

### ❌ Actual result

When you hit enter, the custom attribute is copied to the paragraph.

## Code

Relevant piece of the custom plugin:

```js
        const schema = this.editor.model.schema;
        const conversion = this.editor.conversion;

        // Support for setting/preserving heading IDs.
        const headings = [
            { model: 'heading1', view: 'h2' },
            { model: 'heading2', view: 'h3' },
            { model: 'heading3', view: 'h4' },
            { model: 'heading4', view: 'h5' },
            { model: 'heading5', view: 'h6' },
        ];

        headings.forEach( h => {
            schema.extend( h.model, {
                allowAttributes: [ 'id' ],
            } );
            conversion.attributeToAttribute( {
                model: { name: h.model, key: 'id' },
                view: { name: h.view, key: 'id' },
            } );
        } );
        schema.setAttributeProperties( 'id', {
               copyOnEnter: false
        } );
```

Heading plugin config:

```js
    heading: {
        options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h2', title: 'Heading 1', class: 'ck-heading_h2' },
            { model: 'heading2', view: 'h3', title: 'Heading 2', class: 'ck-heading_h3' },
            { model: 'heading3', view: 'h4', title: 'Heading 3', class: 'ck-heading_h4' },
            { model: 'heading4', view: 'h5', title: 'Heading 4', class: 'ck-heading_h5' },
            { model: 'heading5', view: 'h6', title: 'Heading 5', class: 'ck-heading_h6' },
        ]
    },
```

Screenshots of the document/model, before and after pressing Enter:

<img width="672" alt="Screen Shot 2020-11-06 at 3 38 55 PM" src="https://user-images.githubusercontent.com/1382374/98417283-46a5c280-2046-11eb-9514-8d566c6ae5e7.png">
<img width="672" alt="Screen Shot 2020-11-06 at 3 38 59 PM" src="https://user-images.githubusercontent.com/1382374/98417293-4c9ba380-2046-11eb-94df-9963b9d1ef03.png">

## Relevant CKE Code

I'm not sure if this is a bug or me doing something wrong, because when I look through the path I *think* this is following, it looks pretty straightforward. I assumed when I hit enter, it calls EnterCommand, which then checks getCopyOnEnterAttributes for what attributes to set on the paragraph.

EnterCommand: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-enter/src/entercommand.js
getCopyOnEnterAttributes: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-enter/src/utils.js

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: 23.1.0
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, sorry for the late reply! Basically, this is an old issue related to the schema which can't control such behaviour. You can read more about it [here](https://github.com/ckeditor/ckeditor5/issues/4543) and [here](https://github.com/ckeditor/ckeditor5/issues/4235). Feel free to jump into the discussion to bump the popularity of mentioned issues!
