### ISSUE TITLE
Show something when embedding something non-previewable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8435]
## 📝 Provide a description of the improvement

It currently looks like this:

![](https://user-images.githubusercontent.com/156149/98526997-be5c3300-227a-11eb-9b40-ba3b3eb166b7.png)

The problem is not that it's not clear that this is an HTML snippet, but rather – what snippet this is. If you have a couple of them in the content, you may not understand which is which or if they are filled already or not.

Therefore, some way to identify what's inside would be good.

### Option 1. Show non-editable source

We could simply show a disabled textarea with the source of the embed, just like in the case of when previews are completely disabled.

**However, how can we detect that a preview is not available?**

One option is, of course, that when the sanitizer stripped everything, we know that the thing is non-previewable. But what if just one part of the input was removed and it makes the preview non-existent?

The other option is to make this check after rendering the preview. If it is `0px` high, we can tell that the preview didn't render. However, this will be slow and may cause layout trashing so if we go this way we must be smart.

Related ticket (in this option): #8326.

### Option 2. Add a "title" field

The other option would be to add a field for a snippet's title and display it e.g. in the "HTML snippet: \<title>" place.

The title could be stored in `data-title` and we wouldn't have to do anything more – if the preview doesn't render, the user still sees something. We don't have to even detect these situations.

My biggest concern is that the title will leak to data, but I'd be fine with that as it's kind of a "label/caption" like thing.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Option 3. Always show the banner from #8434.

Pros: Just like that.

Cons: Will be displayed for every embed and pollute the screen.

**Comment by magda-chrzescian** [comment]
I introduced a solution in the [PR](https://app.zenhub.com/workspaces/ckeditor-5-5d9c8a4eac250d0001664feb/issues/ckeditor/ckeditor5/8799).

I added a placeholder in the preview container. If any preview is visible, the placeholder is simply getting covered by it.

**Comment by magda-chrzescian** [comment]
One more follow-up: #8836
