### ISSUE TITLE
First class support for file uploads beyond images

### ISSUE THREAD

**Issue by gavrichards** [ckeditor/ckeditor5#8443]
## 📝 Provide a description of the improvement

It would be great to see the image upload functionality broadened to support other file types too.

At a basic level, I could envisage other files appearing as a box with generic icon such as paperclip, and a link to download the file.

I would particularly like to see audio file uploads enhanced beyond this though, with an inline <audio> player (and link to download).

I would appreciate any advice anyone might have for building this myself using existing plugins and APIs.
Thanks!

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report! Currently, it's not possible to upload files which are not images, as it will require implementing a [file upload adapter](https://github.com/ckeditor/ckeditor5/issues/5999). There's also a more generic [feature request](https://github.com/ckeditor/ckeditor5/issues/7342) about files upload, feel free to add :+1: to the first post and join the discussion to bump its popularity!
