### ISSUE TITLE
Video can't be played in disabled table

### ISSUE THREAD

**Issue by JanTamis** [ckeditor/ckeditor5#8455]
## 📝 Provide detailed reproduction steps (if any)

After adding a youtube video to a table (using media embed) and setting the editor to readonly, the video can't be played.

### ✔️ Expected result
The video in the table can be played.

### ❌ Actual result
The video can't be played

## 📃 Other details

* Browser: chrome 86.0.4240.193
* OS: Windows 10 20H2
* CKEditor version: v11.2.0
* Installed CKEditor plugins: 
        Autoformat,
	BlockQuote,
	Bold,
	CKFinder,
	CKFinderUploadAdapter,
	Essentials,
	FontBackgroundColor,
	FontColor,
	Heading,
	Image,
	ImageCaption,
	ImageResize,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	Italic,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableCellProperties,
	TableProperties,
	TableToolbar,
	TextTransformation,
	TrackChanges,
	MediaBrowser,
	MediaStyle,
	MediaCaption,
	MediaToolbar

**Comment by Mgsy** [comment]
Hi, could you tell us more about your issue? What kind of video do you mean? Does this issue refer to the media embed?

**Comment by JanTamis** [comment]
> Hi, could you tell us more about your issue? What kind of video do you mean? Does this issue refer to the media embed?

I've updated the issue, please let me know if you need more information.

**Comment by Mgsy** [comment]
> After adding a youtube video to a table (using media embed) and setting the editor to readonly, the video can't be played.

Actually, there's also no way to preview a video without the read-only mode. Currently, CKEditor 5 doesn't allow previewing videos, however, there's an [open feature request](https://github.com/ckeditor/ckeditor5/issues/2743) for it, so feel free to add :+1: to the first post and join the discussion to bump its popularity.
