### ISSUE TITLE
Text alignment (toolbar) shouldn't be available for Table

### ISSUE THREAD

**Issue by LangQian** [ckeditor/ckeditor5#8456]
## 📝 Provide detailed reproduction steps (if any)

1. Use classic editor with table and text alignment enabled (text alignment options collapsed into one button).
2. Insert a table, select the whole table
3. Try to apply text alignment (the ones in toolbar, not the ones in table properties configuration)

### ✔️ Expected result

1. The table can be aligned to left/right/center.
OR
2. Text alignment options (toolbar) disabled when a table is selected.

### ❌ Actual result

Although all the text alignment options are available to table, the table can only be aligned to right and center, but not left, so the behaviour is not consistent.
![Screen Shot 2020-11-13 at 10 19 42 AM](https://user-images.githubusercontent.com/16005923/99090057-20c77300-259c-11eb-9371-25d4775fe0f0.png)

## 📃 Other details

Also reproducible [here](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#configuring-styling-tools).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LangQian** [comment]
I guess the issue happened because the "Align left" in the toolbar doesn't apply any alignment to the elements and just let elements use their default alignment, which is left for paragraphs but center for tables. Since alignment options are already available in the "Table properties", I think it's reasonable to disable the ones in toolbar when a table is selected.

**Comment by LangQian** [comment]
If this issue can be easily addressed, could you provide me some instructions or codes on how I can address it by myself (where in the source code I should disable the command)? I need to address this ASAP and don't want to wait for the next release. Thanks!

**Comment by Mgsy** [comment]
Hi, thanks for the report.

> Although all the text alignment options are available to table, the table can only be aligned to right and center, but not left, so the behaviour is not consistent.

This is an issue we are aware, however, it's not trivial. You can read more about it and the problems here - #6231.

As it comes to disabling the alignment on the table element, you can simply create a new schema check, which disallows the alignment attribute. See the code example below:

```javascript
editor.model.schema.addAttributeCheck( ( context, attributeName ) => {
    if ( context.endsWith( 'table' ) && attributeName == 'alignment' ) {
        return false;
    }
} );
```
