### ISSUE TITLE
成功块 警告块

### ISSUE THREAD

**Issue by liwuming** [ckeditor/ckeditor5#8460]
感觉markdown-it有一个很好用的插件，markdown-it-container，可以实现
:::success
内容区域
:::
这样的语法，渲染后的结果是
```html
<div class="success">内容区域</div>
```
也就是说可以自定义块的class，不知道后续可以实现这样的功能吗

其实和BlockQuote功能有些相似，是选择类名而不是语言而已

**Comment by Mgsy** [comment]
Hi, I'm sorry, but we don't understand your language. Please, translate your message to English and open a new issue, so everyone will be able to understand it. Thanks!
