### ISSUE TITLE
webpack-internal:///./resources/js/app.js:20 TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by alamamir** [ckeditor/ckeditor5#8461]
## Provide a description of the task

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser:chrome
* OS: wivdows 10
* CKEditor version: 5
* Installed CKEditor plugins:
        "@ckeditor/ckeditor5-alignment": "^23.1.0",
        "@ckeditor/ckeditor5-basic-styles": "^23.1.0",
        "@ckeditor/ckeditor5-dev-utils": "^23.6.1",
        "@ckeditor/ckeditor5-dev-webpack-plugin": "^23.6.1",
        "@ckeditor/ckeditor5-editor-classic": "^23.1.0",
        "@ckeditor/ckeditor5-editor-decoupled": "^23.1.0",
        "@ckeditor/ckeditor5-essentials": "^23.1.0",
        "@ckeditor/ckeditor5-paragraph": "^23.1.0",
        "@ckeditor/ckeditor5-theme-lark": "^23.1.0",

console error
`webpack-internal:///./resources/js/app.js:20 TypeError: Cannot read property 'getAttribute' of null
    at IconView._updateXMLContent (webpack-internal:///./node_modules/@ckeditor/ckeditor5-ui/src/icon/iconview.js:105)
    at IconView.render (webpack-internal:///./node_modules/@ckeditor/ckeditor5-ui/src/icon/iconview.js:81)
    at IconView.eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js:259)
    at IconView.fire (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js:218)
    at IconView.<computed> [as render] (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js:263)
    at ViewCollection._renderViewIntoCollectionParent (webpack-internal:///./node_modules/@ckeditor/ckeditor5-ui/src/viewcollection.js:208)
    at ViewCollection.eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-ui/src/viewcollection.js:69)
    at ViewCollection.fire (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js:218)
    at ViewCollection.addMany (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/collection.js:227)
    at ViewCollection.add (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/collection.js:192)
`

webpack mix
`const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
const CKEditorWebpackPlugin = require('@ckeditor/ckeditor5-dev-webpack-plugin');
const { styles } = require('@ckeditor/ckeditor5-dev-utils');

module.exports = {
    plugins: [
        // ...

        new CKEditorWebpackPlugin({
            // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
            language: 'pl'
        })
    ],

    module: {
        rules: [
            {
                test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
                use: ['raw-loader']
            },
            {
                test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
                use: [
                    {
                        loader: 'style-loader',
                        options: {
                            injectType: 'singletonStyleTag',
                            attributes: {
                                'data-cke': true
                            }
                        }
                    },
                    {
                        loader: 'postcss-loader',
                        options: styles.getPostCssConfig({
                            themeImporter: {
                                themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
                            },
                            minify: true
                        })
                    },
                ]
            }
        ]
    }
};
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .sourceMaps();
`

main.js
`require('./bootstrap');
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';

ClassicEditor
    .create(document.querySelector('#editor_en'), {
        plugins: [Essentials, Paragraph, Bold, Italic],
        toolbar: ['bold', 'italic']
    })
    .then(editor => {
        console.log('Editor was initialized', editor);
    })
    .catch(error => {
        console.error(error.stack);
    });

`

**Comment by Mgsy** [comment]
Hi, could you please provide a meaningful description of your issue? I assume that you receive some error related to Webpack, however, we can't tell anything about the problem without knowing more about your project, environment and steps to reproduce the problem.

**Comment by alamamir** [comment]
i want to add alignment plugin to editor by webpack an npm according to documention !
please build editor with alignment plugin and release for users
 thank u :)

**Comment by Mgsy** [comment]
As I can see, you build the editor from the source. Did you follow [our guide about it](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)? It's required to provide a specific webpack configuration, so make sure that you've included the config from the guide in your project.
