### ISSUE TITLE
target=_blank duplicates after clicking on it in the documentation example

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8462]
## 📝 Provide detailed reproduction steps (if any)

use chrome visit "https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html#loading-content-with-a-custom-attribute" the live demo on mac.

click the demo links with target on right top .

![gs](https://user-images.githubusercontent.com/1290017/99177913-054d9b00-2749-11eb-81dc-bdfb0ac105e9.gif)

### ✔️ Expected result

show links popup and only one "target"
### ❌ Actual result

when click zone in "target" , editor duplicate "target" show

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report! I can confirm this issue, it has been introduced in v20.0.0.

**Comment by pomek** [comment]
Looks like the selection inherits some attributes from the URL after clicking at the end. It should not inherit anything (see: https://github.com/ckeditor/ckeditor5/issues/1016).

Attributes of the text (URL) node:

![image](https://user-images.githubusercontent.com/2270764/99252456-490ad800-280f-11eb-8177-724e0e55068e.png)

Selection's attributes:

![image](https://user-images.githubusercontent.com/2270764/99252507-5d4ed500-280f-11eb-8e8e-c6400b8b7147.png)

The code below should also remove attributes that can be added by automatic decorators:

https://github.com/ckeditor/ckeditor5/blob/745d28b8f68e6af64a874d8ff31ba9f04161a08e/packages/ckeditor5-link/src/linkediting.js#L519-L525
