### ISSUE TITLE
unselect whole link text when backward to forward use mouse at the end of link text

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8464]
## 📝 Provide detailed reproduction steps (if any)

1. insert a link use command or toolbar to ckeditor5 editor.
2. when caret blink at the end of link text 
3. press mouse and drag from backward to forward ,can not select the last latter of link text.

![gs](https://user-images.githubusercontent.com/1290017/99204561-076b3480-27f1-11eb-8e3d-e716df845d17.gif)

### ✔️ Expected result
select all the text mouse passed

### ❌ Actual result

can not select the last latter

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report! We are aware of this issue and it's reported here - #7936, so I'm closing it as a duplicate.
