### ISSUE TITLE
Resize youtube video without table

### ISSUE THREAD

**Issue by JanTamis** [ckeditor/ckeditor5#8468]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

it would be nice to resize a video (in this case a youtube video) without the use of a table.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! This feature request is tracked [here](https://github.com/ckeditor/ckeditor5/issues/6593), so I encourage you to add :+1: to the first post and join the discussion to bump its popularity.
