### ISSUE TITLE
Clipboard deep dive instantiates UpcastWriter incorrectly

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#8470]
## 📝 Provide a description of requested docs changes

_What is the purpose and what should be changed?_

In the code block here https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/clipboard.html#processing-input-content, the `UpcastWriter` constructor is called without passing a `viewDocument` argument. If you try to write this plugin according to the docs, you end up with an exception like 

```
Uncaught TypeError: Cannot read property 'stylesProcessor' of undefined at new Element
```

when you try to call `writer.createElement`.

It took me a while to figure this out, but the [UpcastWriter](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_upcastwriter-UpcastWriter.html) docs show the correct way to instantiate the object is by passing in a view document. In the case of the clipboard plugin, it would specifically be the editing view document.

**Comment by Mgsy** [comment]
Hi! Thanks for the report and PR :tada: We will take a look at it soon.
