### ISSUE TITLE
Option to output in-line CSS styles only (no classes)

### ISSUE THREAD

**Issue by dmboucher** [ckeditor/ckeditor5#8473]
My company is upgrading from CKEditor v.4.6.2.  We would like to upgrade to v.5, but we're having some difficulty with in-line CSS styles vs. classes.  In our tests of CKEditor 5, we've been using a build of the ClassicEditor created with the online builder: 
[https://ckeditor.com/ckeditor-5/online-builder/](https://ckeditor.com/ckeditor-5/online-builder/).

**Use Case:**
We are using the output of the CKEditor to send as the body of an email.  As such, we must have all in-line CSS styles (no classes).  Most email editors ignore CSS classes when parsing HTML email messages.

**Feature Request:**
We would love to have a setting similar to:
```
ClassicEditor
	.create( document.querySelector( "#id" ), {
		inlineStyles: true
	});
```

**Expected Behavior:**
If this setting were `true`, the entire `.getData()` output of the CKEditor would contain **_only_** in-line CSS styles.  No classes.

For example, if I change the font family, both v4 and v5 CKEditors produce something like this:
`<span style="font-family:'Courier New', Courier, monospace;">Content</span>`

However, for font size, the v5 CKEditor gives me a class-based style:
`<span class="text-small">Content</span>`

When sending this as an email, that class is ignored _(of course)_ and so I am not able to offer font sizing in the CKEditor for this use case.

**Another use case:**
A search on the web uncovered another person who asked for this feature back in September of 2019:  [https://stackoverflow.com/questions/58014387/how-do-i-tell-ckeditor-5-to-use-inline-styling-on-the-elements-which-it-creates](https://stackoverflow.com/questions/58014387/how-do-i-tell-ckeditor-5-to-use-inline-styling-on-the-elements-which-it-creates)   Their use-case was to use the output of the Editor as the source to programmatically create a `.pdf` file output.

If this is currently available in CKEditor v5, then I apologize for unnecessarily requesting this feature.  I would be thrilled to know how to accomplish this.  I searched through the documentation, but was unable to find any way to do this.

**_Thank you!_**

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Inlining styles feature is not available in CKEditor 5, so I'm afraid that you'll need to use some tool for processing HTML and converting to inline styles (e.g. [Juice](https://github.com/Automattic/juice)). This feature request is tracked [here](https://github.com/ckeditor/ckeditor5/issues/1627), so I encourage you to give :+1: to the first post and join the discussion to bump its popularity.
