### ISSUE TITLE
how to control caret position at the end of engine.view.downcastwriter createContainerElement or createEditableElement elements 

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8475]
## 📝 Provide detailed reproduction steps (if any)
follow the plugin guider of ckeditor5.com,i build a inline suggest plugin
the main code as follow:

```js
//regist inlineSuggest schema 
schema.register('inlineSuggest', {
    allowContentOf: '$block',
    isObject: true,
    isInline: true,
    allowWhere: '$text',
})

//upcastt 
conversion.for('upcast').elementToElement({
    view: {
        name: 'span',
        classes: 'inline-suggest'
    },
    model: 'inlineSuggest'
})

// downcast 
conversion.for('downcast').elementToElement({
    model: 'inlineSuggest',
    view(modelElement, { writer: viewWriter }) {
        const inlineSuggest = viewWriter.createContainerElement('span', {
            class: 'inline-suggest',
        });
        viewWriter.setCustomProperty('suggest', true, inlineSuggest);
        return inlineSuggest;
    }
})

// main execute of insertInlineSuggest command 
execute() {
     this.editor.model.change(writer => {
        let inlineSuggest = writer.createElement('inlineSuggest');
        const innerText = writer.createText('2020-11-17');
        writer.append(innerText, inlineSuggest);
        this.editor.model.insertContent(inlineSuggest);
    });
}
```
and now the code works well
but i have a problem while typing ,the gif:
![gs](https://user-images.githubusercontent.com/1290017/99505884-59ac8100-29bc-11eb-867a-6385ec1b24fe.gif)

when i insert the inlineSuggest ,i can put caret by clicking at the end. and type words not in the inlineSuggest area . 
clicking the space between inlineSuggest and words, caret out of inlineSuggest and at the begin of words , this is my expect .
when i type something to inlineSuggest , change default date string.
then clicking the space between inline suggest and words , the ckeditor5-inspector tell me caret is out  of inlineSuggest and at the start of words as gif show . 
but when i start typing , the caret going to the end of inlineSuggest . 

so why caret at the start of words but going to the end of inlineSuggest when typing?

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by xinglie** [comment]
if the inlineSuggest is first element of the editor content , i can not put caret before inlineSuggest , whatever clicking or use arrow keys .
so can someone tell me how to solve this case?

**Comment by Reinmar** [comment]
Hi! Sorry for the late reply. We don't support inline elements the way you used them. You can check how the mention feature was implemented by us - it uses model attributes. Same for all other inline features such as bold, italic, fonts, etc.

We use elements in an inline context in two cases only: empty elements (img, br) or widgets (https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html). Also, in the widget case, we don't support nested editables inside such inline widgets yet: https://github.com/ckeditor/ckeditor5/issues/1729.
