### ISSUE TITLE
inline widget with popup

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8476]
## 📝 Provide a description of the new feature

like https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

the placeholder only allow user focus and replace it when typing . 

how about allow user change some of the text inside placeholder  or show balloon popup to provide some options to quickly use?

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the feedback. Changing text inside a widget requires implementing editable inline widgets, but a current architecture doesn't allow creating such elements. We have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1729) for it, so I encourage you to add :+1: to the first post and join the discussion to bump its popularity.

Additionally, the placeholder feature is not the official plugin, the code shown in the guide is for educational purpose only to learn users how to create inline widgets. The code provides a basic implementation and could be used for further development, depending on the user's use case.
