### ISSUE TITLE
Docs: Incorrect snippet in the editing engine guide

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8477]
## 📝 Provide a description of requested docs changes

follow the link : https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#changing-the-view

the example code:

![image](https://user-images.githubusercontent.com/1290017/99536668-a062a100-29e5-11eb-853d-130367e0f626.png)

"data" should use "editing" instead?

**Comment by Mgsy** [comment]
Hi! Indeed, this snippet is incorrect, thanks for letting us know!
