### ISSUE TITLE
[Edge] Two clicks are required to close the balloon UI

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#848]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the selection in the link.
3. Click on the `edit link` icon.
4. Put the selection in `Heading 1`.

## ✅ Expected result

The link balloon closes after the first click.

## ❎ Actual result

The link balloon closes after two clicks.

## 📃 Other details that might be useful

**Notes**

Related - https://github.com/ckeditor/ckeditor5/issues/716

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36251918-3506252e-1243-11e8-9783-d1156a879621.gif)

**Other information**

OS: Windows 10
Browser: Edge

---

If you'd like to see this fixed sooner, add 👍 to this post.

**Comment by oleq** [comment]
Can you check if this [fix](https://github.com/ckeditor/ckeditor5/issues/716#issuecomment-358928266) solves this issue too?

**Comment by Mgsy** [comment]
>@Mgsy Can you check if this fix solves this issue too?

Och, forgot to mention that I've checked it before and unfortunately it doesn't fix this problem.

**Comment by FilipTokarski** [comment]
This bug is fixed in the new upcoming Edge v.79.0.309.56.

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
