### ISSUE TITLE
Wrong position of HTML embed button in the toolbar

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#8481]
On narrow screens it is hidden in the "more items" menu.

<img width="688" alt="Screen Shot 2020-11-19 at 9 10 16 AM" src="https://user-images.githubusercontent.com/545175/99638806-15b28e00-2a47-11eb-9496-23a847dd59df.png">

**Comment by godai78** [comment]
I rearranged the buttons:

![Screenshot 2020-11-20 at 14.14.32.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/16b1dac3-aec8-4788-81ca-0eb8bc448617)

Changes in this PR: https://github.com/ckeditor/ckeditor5/pull/8492
