### ISSUE TITLE
How to convert view element/position to model element/position

### ISSUE THREAD

**Issue by B4rtes** [ckeditor/ckeditor5#8482]
Hi guys,

Using mouse over event I was able to receive target view element.
I have view element and view position. I set view selection to necessary position.

How can I set model selection to this position? I have only view attribute element, not any model one.

Thanks

**Comment by Mgsy** [comment]
Hi, can you tell us more about your use case and what you would like to achieve? Also, some code examples would be also appreciated.

**Comment by B4rtes** [comment]
> Hi, can you tell us more about your use case and what you would like to achieve? Also, some code examples would be also appreciated.

Hi @Mgsy ,
Looks like I was able to cope with the task.

I've just created view range over target node and then convert to model range using editor.editing.mapper.toModelRange(viewRange). I think I can close the issue
Thanks :)
