### ISSUE TITLE
addMarker event is not called in data pipeline when range is at start of the root element

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#8485]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://codepen.io/jacekbogdanski/pen/XWKwRjB?editors=1010
2. Open developer tools console.
3. Refresh the page.

### ✔️ Expected result

Debugger statement for `addMarker` event should stop script execution.

### ❌ Actual result

Nothing happens.

The issue seems to be caused by the https://github.com/ckeditor/ckeditor5/blob/eee94cef569a159ba1e59482d571e2413dde575c/packages/ckeditor5-engine/src/controller/datacontroller.js#L491-L510 function executed in https://github.com/ckeditor/ckeditor5/blob/eee94cef569a159ba1e59482d571e2413dde575c/packages/ckeditor5-engine/src/controller/datacontroller.js#L240-L248

It looks like when the marker range is at the start or end of the root it won't be contained in the root element range and the following code will fail to process markers.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
I've added it to the iteration 44 as this is needed for HTML comments.
