### ISSUE TITLE
Create a redirect from the old Vue guide to somewhere (vue-v3?)

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8489]
## 📝 Provide a description of requested docs changes

We renamed one of the guide:

![image](https://user-images.githubusercontent.com/2270764/99780997-90e37500-2b17-11eb-8272-947510320b6b.png)

On the current docs (https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html), the URL works. However, the content is not updated:

How it looks now:

![image](https://user-images.githubusercontent.com/2270764/99781286-f3d50c00-2b17-11eb-98fc-3f7eb2e5b803.png)

How it should be:

![image](https://user-images.githubusercontent.com/2270764/99781358-0f401700-2b18-11eb-880e-fe29c5155727.png)

**Comment by oleq** [comment]
I think the redirect in https://github.com/ckeditor/ckeditor5/blob/master/docs/umberto.json#L9 for the old URL should point to the Vue 3+ docs.
