### ISSUE TITLE
Review toolbars in the demos in the documentation to improve feature discoverability

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#8493]
After [multiline toolbar](https://github.com/ckeditor/ckeditor5/issues/6146) and [marking UI buttons in the docs](https://github.com/ckeditor/ckeditor5/issues/6267) are done, we should review all demos and see:

*   If the toolbar buttons selected for each sample are optimal both in terms in the number of features available in the demo and the button placement.
*   Which buttons should be marked as important and what tooltip should be added there.
*   Where using the multiline toolbar would make sense. Do we have any samples where we needed to disable the TOC to accommodate a larger number of buttons that we can now modify to use the multiline toolbar instead?

Toolbars checked / adjusted:

*   [x] Examples section
*   [x] autoformatting
*   [x] automatic text transformations
*   [x] basic text styles
*   [x] block indentation
*   [x] block quote
*   [x] block toolbar
*   [x] code blocks
*   [x] comments
*   [x] track changes
*   [x] real-time collaboration
*   [x] users
*   [x] document title
*   [x] document placeholder
*   [x] export to PDF
*   [x] export to Word
*   [x] font
*   [x] headings
*   [x] highlight
*   [x] horizontal line
*   [x] image upload
*   [x] Image Ready
*   [x] CKFinder
*   [x] Base64
*   [x] Simple upload
*   [ ] images
*   [x] keyboard support
*   [x] link
*   [x] lists
*   [x] markdown output
*   [x] math/chemical formulas
*   [x] media embed
*   [x] mentions
*   [x] page break
*   [x] pagination
*   [x] pasting from Word
*   [x] pasting from GD
*   [x] pasting plain text
*   [x] raw HTML embedding
*   [x] read-only support
*   [x] remove formatting
*   [x] restricted editing
*   [x] select all
*   [x] special characters
*   [x] spelling/grammar checking
*   [x] tables
*   [x] text alignment
*   [x] to-do lists
*   [x] UI language
*   [x] watchdog
*   [x] word/character count

Toolbar tooltips added (including demos that do not need the tooltips):

*   [x] autoformatting
*   [x] automatic text transformations
*   [x] basic text styles
*   [x] block indentation
*   [x] block quote
*   [x] editor toolbar
*   [x] block toolbar
*   [x] code blocks
*   [x] comments
*   [x] track changes
*   [x] real-time collaboration
*   [x] users
*   [x] document title
*   [x] document placeholder
*   [x] export to PDF
*   [x] export to Word
*   [x] font
*   [x] headings
*   [x] highlight
*   [x] horizontal line
*   [x] HTML embed
*   [x] image upload
*   [x] images
*   [x] keyboard support
*   [x] link
*   [x] lists
*   [x] markdown output
*   [x] math/chemical formulas
*   [x] media embed
*   [x] mentions
*   [x] page break
*   [x] pagination
*   [x] pasting from Word
*   [x] pasting from GD
*   [x] pasting plaintext
*   [x] read-only support
*   [x] remove formatting
*   [x] restricted editing
*   [x] select all
*   [x] special characters
*   [x] spelling/grammar checking
*   [x] tables
*   [x] text alignment
*   [x] to-do lists
*   [x] UI language
*   [x] watchdog
*   [x] word/character count

**Comment by godai78** [comment]
Checked and eliminated all the ones that do not have a toolbar or the toolbar is prober length and there is no need for the indicator.

**Comment by godai78** [comment]
Toolbar guide has been extracted from the configuration guide and added as a standalone guide to aid discoverability and overcome the search engine standard issue.

**Comment by godai78** [comment]
A few screenshots for split toolbars:

![](https://user-images.githubusercontent.com/68123541/100997382-79b27780-355a-11eb-83a2-f04d0f10589c.png)

![](https://user-images.githubusercontent.com/68123541/100997419-8636d000-355a-11eb-815e-9287d6d777fb.png)

![](https://user-images.githubusercontent.com/68123541/100997438-8cc54780-355a-11eb-8900-51719e8bd6a7.png)

And a toolbar that will wrap if anybody insists on using CKEditor 5 on their phone:

![](https://user-images.githubusercontent.com/68123541/100997536-a797bc00-355a-11eb-9d8f-54086f99bd09.png)

**Comment by godai78** [comment]
There is a larger discussion coming, we already took up this topic with @pkwasnik and @Mgsy.
The Classis Editor comes up with a toolbar about 2/3 the widescreen display demo width, as they have only the predefined set and no other items. 

Now:
- do wee keep hiding buttons in these,
- or do we wrap buttons automatically into another line?

If the latter, we could introduce the wrapping switch straight into the editor base, because putting it in every one of those demos would require a substantial amount of code, as they do not have toolbar items listed and would need to.

---

Also future feature request on my part: allow automatic wrapping but set a predefined breakpoint. This is a combo approach between "wrap only as needed" and "wrap here so it looks good" that would produce the ultimate visual results for the editor.

**Comment by godai78** [comment]
Tooltip indicators for buttons were added where applicable.  
  
Sometimes more than one tooltip was added if there was more than one demo and it made sense.  
  
Other changes: all lists have been grouped into one submenu, as it make sense to keep them together both functionally and logically.  
  
Images guide shall be anyway rewritten largely, so it was not tended to too carefully (just one indicator added, this may change once the guide is slashed into pieces).

**Comment by AnnaTomanek** [comment]
Moved the toolbar indicator task to a separate issue: https://github.com/cksource/ckeditor5-internal/issues/588

**Comment by AnnaTomanek** [comment]
There are still some unchecked guides in the list - @godai78 can you review them, propose changes if any are needed or check them and let's close this issue finally?

**Comment by godai78** [comment]
Sure.

**Comment by godai78** [comment]
*   CKFinder needs the tooltip moved right not to stick out the editor window. Will have to make a PR for that.
*   The same applies to the remove formatting feature and same solution.
*   Didn't even touch the images guide, it will sooner or later be scrapped and rewritten anyway, so there is no point in doing it now.
*   Markdown output is a borderline case - it is fine on a normal screen, but will wrap fast on mobile. I see no point in forcewrapping it, tho.
*   All other toolbars have been assessed using the same methodology we employed previously and I deem those worthy being left alone as they are.  
      
    I suggest closing this with a PR for CKFinder and Remove Formatting that I will prepare today.

**Comment by oleq** [comment]
I just stumbled upon this: the balloon in this guide should be positioned in the same way as in the export to PDF guide.

![](https://user-images.githubusercontent.com/1099479/109033242-b9ef4500-76c6-11eb-8973-5dc6ada14e4f.jpeg)

**Comment by godai78** [comment]
@pkwasnik - do we have power over it?  
  
The PDF exporter indeed looks like this:

![](https://user-images.githubusercontent.com/68123541/109109899-6e747f80-7736-11eb-8496-27a398cc0ef5.png)

**Comment by oleq** [comment]
Yes, it's configurable. When I first created one for the PDF export guide I consciously made it look like this.

**Comment by godai78** [comment]
Share the knowledge, please :)

**Comment by godai78** [comment]
Never mind, I guess I found it.

**Comment by oleq** [comment]
You can use any of [https://atomiks.github.io/tippyjs/v6/all-props/](https://atomiks.github.io/tippyjs/v6/all-props/) options there.

**Comment by godai78** [comment]
Had I known of its existence before, that would have had been much splendid indeed. I'm taking the link to the documentation tech-tips database, thank you..

**Comment by AnnaTomanek** [comment]
Closed in 37dac1d. Hell of a ride it was! Thanks! :clap:

**Comment by oleq** [comment]
That would be great if we could measure the impact of these changes. For instance, changes to the average visit duration from Google Analytics would be very helpful.
