### ISSUE TITLE
link edit popup sometimes not display when use mouse click

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8499]
## 📝 Provide detailed reproduction steps (if any)

1. follow create widget guide : https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#demo i implement the feature to my custom editor 
2. when i use the block widget with links , i found link popup sometimes not display when i move caret from block widget inside to the link , as gif:

![gs](https://user-images.githubusercontent.com/1290017/99901695-7b2aa700-2cf3-11eb-9673-eba12296613b.gif)

## 📃 Other details

i deep into the link plugin code , 
`@ckeditor/ckeditor5-link/linkui.js`
add a `console.log` to `click` listener like bellow

```js
this.listenTo(viewDocument, 'click', () => {
    const parentLink = this._getSelectedLinkElement();
    console.log(parentLink);
    if (parentLink) {
        // Then show panel but keep focus inside editor editable.
        this._showUI();
    }
});
```

i found when clicking inside link, sometimes `parentLink` is null ,but the caret blink inside the link text.

so continue to `_getSelectedLinkElement` method

add `console.log` like bellow
```js
_getSelectedLinkElement() {
    const view = this.editor.editing.view;
    const selection = view.document.selection;
    console.log(selection.focus.getAncestors());
    //...other codes
```
i found when popup not display, the `selection.focus` point to old position.
![image](https://user-images.githubusercontent.com/1290017/99901842-9813aa00-2cf4-11eb-99d9-6368d3f2431d.png)

not point to the link. 

so when i change the `click` listener use `setTimeout` like bellow

```js
this.listenTo(viewDocument, 'click', () => {
    setTimeout(() => {
        const parentLink = this._getSelectedLinkElement();
        console.log(parentLink);
        if (parentLink) {
            // Then show panel but keep focus inside editor editable.
            this._showUI();
        }
    }, 0);
});
```
every thing is ok.

i have no idea why  ui caret position is changed , `selection.focus` is not immediately changed sometimes.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. We are aware of this issue, you can read more about it [in the proper ticket](https://github.com/ckeditor/ckeditor5/issues/6559).

**Comment by skdusgh** [comment]
https://earscoming.tistory.com/entry/ckeditor5-ckeditor-not-working-ckeditor-%EC%9D%BC%EB%B6%80-%EA%B8%B0%EB%8A%A5-%EC%95%88%EB%90%98%EB%8A%94-%EA%B2%BD%EC%9A%B0
