### ISSUE TITLE
Dropdown see more plugins is not responsive

### ISSUE THREAD

**Issue by thepriefy** [ckeditor/ckeditor5#8504]
## 📝 Provide detailed reproduction steps (if any)

1. open CKEditor5 demo page (https://ckeditor.com/ckeditor-5/demo/)
2. resize your screen until the width is equal 320px 
3. click on 3 dots (top-right) of the editor

### ✔️ Expected result

menus are displayed in 2 lines

### ❌ Actual result

some menus is overflow

320px

![CKEditor5-320px](https://user-images.githubusercontent.com/10849586/99937933-60127280-2d99-11eb-968e-c9de871aa907.png)

425px (works fine)

![CKEditor5-425px](https://user-images.githubusercontent.com/10849586/99937944-66085380-2d99-11eb-9bf0-413727b130eb.png)

## 📃 Other details

* Browser: Google Chrome
* OS: Windows 10
* CKEditor version: 5
* Installed CKEditor plugins: -

---

Thank you in advance.

**Comment by Mgsy** [comment]
Hi, thanks for the report. We are [aware of this issue](https://github.com/ckeditor/ckeditor5/issues/5586) and we are working on it in the current iteration.
