### ISSUE TITLE
Select-All is part of ckeditor5-essentials since 23.1.0 

### ISSUE THREAD

**Issue by joachimdoerr** [ckeditor/ckeditor5#8508]
The Documentation told us that we have to import the select-all plugin: 

https://ckeditor.com/docs/ckeditor5/latest/features/select-all.html#installation

`npm install --save @ckeditor/ckeditor5-select-all`

and import and provide the plugin to the builtinPlugins.

`import SelectAll from '@ckeditor/ckeditor5-select-all/src/selectall';`

But since 23.1.0 the select all plugin is a part of the ckeditor5-essentials

```
├─┬ @ckeditor/ckeditor5-essentials@23.1.0
│ ├─┬ @ckeditor/ckeditor5-clipboard@23.1.0
│ │ ├── @ckeditor/ckeditor5-core@23.1.0 deduped
│ │ ├── @ckeditor/ckeditor5-engine@23.1.0 deduped
│ │ └── @ckeditor/ckeditor5-utils@23.1.0 deduped
│ ├── @ckeditor/ckeditor5-core@23.1.0 deduped
│ ├── @ckeditor/ckeditor5-enter@23.1.0 deduped
│ ├─┬ @ckeditor/ckeditor5-select-all@23.1.0
│ │ ├── @ckeditor/ckeditor5-core@23.1.0 deduped
│ │ ├── @ckeditor/ckeditor5-ui@23.1.0 deduped
│ │ └── @ckeditor/ckeditor5-utils@23.1.0 deduped
│ ├── @ckeditor/ckeditor5-typing@23.1.0 deduped
│ └─┬ @ckeditor/ckeditor5-undo@23.1.0
│   ├── @ckeditor/ckeditor5-core@23.1.0 deduped
│   ├── @ckeditor/ckeditor5-engine@23.1.0 deduped
│   └── @ckeditor/ckeditor5-ui@23.1.0 deduped
```

In case of add the plugin to builtinPlugins the editor throw some exceptions: 

`CKEditorError: plugincollection-plugin-name-conflict {"pluginName":"SelectAll"}`

_What is the purpose and what should be changed?_

Please add a note that select all is not to add for builds anymore.

**Comment by Mgsy** [comment]
Hi! Actually, the Select all plugin was always a part of the Essentials plugin :) As the documentation says:

> This feature is enabled by default in all builds (loaded by the [`Essentials`](https://ckeditor.com/docs/ckeditor5/latest/api/module_essentials_essentials-Essentials.html) plugin). The installation instructions are for developers interested in building their own, custom rich text editor.

It means that the mentioned instructions are for people not using our ready-to-use builds, which might not load the Essentials plugin.
