### ISSUE TITLE
editor builder defaultConfig.language not apply to editor.locale

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8510]
## 📝 Provide detailed reproduction steps (if any)

1. use `ckeditor5/packages/ckeditor5-build-decoupled-document` to build custom editor
2. change `ckeditor5/packages/ckeditor5-build-decoupled-document/src/ckeditor.js` the `defaultConfig.language` to `zh-cn` 

### ✔️ Expected result

ui is `zh-cn` and editor.locale also too

### ❌ Actual result

only ui display language in `zh-cn` .  editor.locale language still is `en`,both uiLanguage and cotentLanguage

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Indeed after changing the language the `editor.locale` still shows `en`.  
cc @ma2ciek could you take a look at this?

**Comment by Reinmar** [comment]
I confirm that it doesn't work. And it's odd.

![](https://user-images.githubusercontent.com/156149/136001592-1dd3a1cf-fc27-4576-ba10-531540141c07.png)

Only setting it in create() works.

![](https://user-images.githubusercontent.com/156149/136001679-9e11c09a-37ec-4215-8edc-b4aa025cd047.png)

**Comment by pomek** [comment]
### 📝 Steps

* Use the `ckeditor5-build-classic`, but it happens with other builds too.
* Start the HTTP server in the `packages/ckeditor5-build-classic` directory (`hs .`)
* In the `sample/index.html` file, modify script tags:

	  <script src="../build/ckeditor.js"></script>
	  <script src="../build/translations/pl.js"></script>
	  <script>
		  ClassicEditor.defaultConfig.language = 'pl';
		  ClassicEditor.create( document.querySelector( '#editor' ) )
			  .then( editor => {
				  window.editor = editor;
			  } )
			  .catch( error => {
				  console.error( 'There was a problem initializing the editor.', error );
			  } );
	  </script>

* Type `editor.locale` in the console.

### ✔️ Expected result

	  editor.locale
	  Locale {uiLanguage: 'pl', contentLanguage: 'pl', uiLanguageDirection: 'ltr', contentLanguageDirection: 'ltr', t: ƒ}

### ❌ Actual result


	  editor.locale
	  Locale {uiLanguage: 'en', contentLanguage: 'en', uiLanguageDirection: 'ltr', contentLanguageDirection: 'ltr', t: ƒ}

### ❓ Possible solution

* Find a place where the `editor.locale` object is created.
* Notice that `Editor#defaultConfig` is used too late, and the `Context` class is already initialized.
* The goal is to use the language specified in the configuration object passed in the constructor **or** built in the editor (`Editor#defaultConfig`).


<details>
<summary>Solution (SPOILER)</summary>

```diff
diff --git a/packages/ckeditor5-core/src/editor/editor.js b/packages/ckeditor5-core/src/editor/editor.js
index 141a7076f2..c4677263c4 100644
--- a/packages/ckeditor5-core/src/editor/editor.js
+++ b/packages/ckeditor5-core/src/editor/editor.js
@@ -52,6 +52,8 @@ export default class Editor {
 	 * @param {Object} [config={}] The editor configuration.
 	 */
 	constructor( config = {} ) {
+		const language = config.language || this.constructor.defaultConfig.language;
+
 		/**
 		 * The editor context.
 		 * When it is not provided through the configuration, the editor creates it.
@@ -59,7 +61,7 @@ export default class Editor {
 		 * @protected
 		 * @type {module:core/context~Context}
 		 */
-		this._context = config.context || new Context( { language: config.language } );
+		this._context = config.context || new Context( { language } );
 		this._context._addEditor( this, !config.context );
 
 		// Clone the plugins to make sure that the plugin array will not be shared

```
</details>

Make sure to cover this change with tests:

* passing the language in the constructor
* specifying the language as `#defaultConfig`
* specifying the language by passing an instance of the `Context` class in the constructor as `config.context`

**Comment by pomek** [comment]
☝️ remember that the build is not refreshed when applying changes in its sources. Please call the `yarn run build --mode development --watch` command in the build directory to automatically rebuild the build when changing the code.

**Comment by wimleers** [comment]
This _might_ solve https://www.drupal.org/project/drupal/issues/3250191 🤞
