### ISSUE TITLE
Create the "Toolbar configuration" guide

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8513]
## 📝 Provide a description of requested docs changes

Follow up of #6146

_Create a guide with different kinds of toolbars and different configs (multi-line, grouping, etc.)._

**Comment by oleq** [comment]
Just for the record, if this was a separate task, it needs an estimate and a milestone.

**Comment by pkwasnik** [comment]
> Just for the record, if this was a separate task, it needs an estimate and a milestone.

I've closed it as I've included all docs in [#6146](https://github.com/ckeditor/ckeditor5/issues/6146), sorry for not explaining it here.
