### ISSUE TITLE
Add support for classes in the alignment plugin

### ISSUE THREAD

**Issue by georgringer** [ckeditor/ckeditor5#8516]
Currently I am checking out the migration of CMS TYPO3 from ckeditor4 to 5. One thing which I am missing is to use classes instead of inline styles for the alignment plugin.

If e.g. right alignment is selected, the text should get `<p class="alignment-right">` instead of `<p style="texta-align:right"`.

What do you think about that?

**Comment by Mgsy** [comment]
Hi, thanks for the feedback. Could you please tell us more why you would expect to see classes in this case, instead of inline styles?

**Comment by georgringer** [comment]
There are a couple of reasions:
* The content security policy `style-src-attr` can be configured to ignore inline styles
* In TYPO3 it is possible to filter attributes which are not allowed by editors and one of those is `style`. Coming from ckeditor4 and src-view button and other way, you don't want editors to style it through that. The attribute `class` is allowed
* E.g. the highlight plugin (https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html) does it with classes as well
* In the frontend, someone might use the class to add some additional styling via this class

Hope those are enough reasons?

I don't know if any other plugins are using inline styles but all of those should be really avoided.
