### ISSUE TITLE
Document unsupported features for Markdown editor

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#8520]
It seems using CKEditor 5 as Markdown editor attracts many users who, after seeing our explanation that this feature is experimental as HTML remains [the best standard for rich-text data](https://medium.com/content-uneditable/a-standard-for-rich-text-data-4b3a507af552), are wondering which features are supported/unsupported in our Markdown implementation.

As such, we could check it and add a "Known issues" section to the documentation just like we do it for [export to PDF](https://ckeditor.com/docs/ckeditor5/latest/features/export-pdf.html#known-issues) or [export to Word](https://ckeditor.com/docs/ckeditor5/latest/features/export-word.html#known-issues).

**Comment by godai78** [comment]
The Markdown output demo seems to have no autoformatting feature on. We should reconsider turning it on.
