### ISSUE TITLE
Implement the CKEditor5 global object based off the CKEditor5 DLLs

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8521]
## 📝 Provide a description of the new feature

It would be nice to have all (DLLs and plugins) exposed as UMD global (or just global).

*   Every package has its `index.js` (probably also defined in `package.json` if needed - other plugins _might_ use it to import it).
*   Webpack plugin to extends `index.js` so the exports are exposed as `window.CKEditor5[ packageName ]`.
    *   Additionally, we should move other globals (version, translations) there. (🎉 breaking change).
    *   We can also do runtime checks for:
        *   versions
        *   required DLLs (core, widget, ui, etc) based on dependencies listed in package.jsons of these packages
    *   In the end, we have:
        *   `window.CKEditor5.htmlEmbed.HtmlEmbed`
        *   `window.CKEditor5.htmlEmbed.HtmlEmbedCommand`
        *   `window.CKEditor5.htmlEmbed.HtmlEmbedUI`
        *   `window.CKEditor5.htmlEmbed.HtmlEmbedEditing`

To check: `CKEditor5` or `CKE5`? Definitely not `CKEDITOR` to avoid conflicts with CKEditor 4's global.

If changes in other packages (version, translations) might be done separately then it would be even better. I think that we might forget about something. Additionally, other improvements might also be done in a follow-up.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
I guess the screen attached below says more than anything else:

![image](https://user-images.githubusercontent.com/2270764/100320001-dcd36580-2fc0-11eb-8595-bba756627eff.png)

**Comment by jodator** [comment]
The plugins are automatically available on `CKEditor5` global object. However, we miss the plugins bundled in DLL. For instance Plugin from core in main \`ckeditor5:

```
/**
 *  @module dll/core
 */

import { Plugin } from '@ckeditor/ckeditor5-core/core';

export * from '@ckeditor/ckeditor5-core/core';

window.CKEditor5.core = {};

window.CKEditor5.core.plugin = Plugin;
```

**Comment by jodator** [comment]
Closed with [`a51150`](https://github.com/ckeditor/ckeditor5/commit/a51150e333d3ff10b72908fc2340c2983039dd95).
