### ISSUE TITLE
Ckeditor5 Toolbar item view m=not working properly 

### ISSUE THREAD

**Issue by vishwakarmanikhil** [ckeditor/ckeditor5#8523]
I am trying to implement ckeditor5 on my website. But I am facing one issue is that when screening size decreases then toolbar item hide and we can hide and unhide by using the three-dot button. it's working fine in desktop and tablet view but it is not working properly. I have added a screenshot of the error and we can't scroll icons also. Is there is any way to handle this error? Or better is than don't hide toolbar items instead display one below other.
![ckeditor 5 error](https://user-images.githubusercontent.com/63867254/100127079-bddfb100-2ea4-11eb-87c6-4354d9934443.png)

**Comment by FilipTokarski** [comment]
Hi, I guess your issue has already been adressed [here](https://github.com/ckeditor/ckeditor5/issues/6146). If everything goes fine, this feature will be merged in this iteration, so stay tuned!
