### ISSUE TITLE
[Edge] Tooltip doesn't hide after right-click on the icon

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#853]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Right-click on the icon from the toolbar.
3. Put the selection in the editor.

## ✅ Expected result

The tooltip hides.

## ❎ Actual result

The tooltip is still visible.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36260787-b21d86be-1262-11e8-97f3-0f1aab655c42.gif)

**Other information**

OS: Windows 10
Browser: Edge

**Comment by oleq** [comment]
It looks more like a bug in Edge since tooltips are controlled by `.ck-button:hover` and in the screencast, the buttons are clearly no longer hovered.
