### ISSUE TITLE
How to add .po files localization for a custom plugin

### ISSUE THREAD

**Issue by B4rtes** [ckeditor/ckeditor5#8532]

**Comment by xinglie** [comment]
could you snapshot a picture of your `ckeditor5-customPlugin` with official plugins? 
i also write a plugin with localization, it works for me ,so let me try help you.

**Comment by B4rtes** [comment]
Hi @xinglie ,

I'm not sure I understood you correctly. But plugin structure looks like this
ckeditor5-customPlugin/
--lang/translations/en.po
--plugin.js
--pluginUI.js
--pluginEditing.js
--pluginCommand.js
node_modules/
index.js

In the pluginUI I use t(<translation_key>)  function to get the right translation

**Comment by xinglie** [comment]
you missed `src` folder, add `src` like 
```bash
ckeditor5-customPlugin/
--src
----lang/translations/en.po
----plugin.js
----pluginUI.js
----pluginEditing.js
----pluginCommand.js
node_modules/
index.js
```
or change your `webpack.config.js` `CKEditorWebpackPlugin` config
```js
new CKEditorWebpackPlugin( {
    //...
    packageNamesPattern:/[/\\](?:ckeditor5-)[^/\\]+[/\\]/,
    sourceFileRegexp:/[/\\](?:ckeditor5-)[^/\\]+[/\\].+\.js$/,
    sourceFilesPattern:/[/\\](?:ckeditor5-)[^/\\]+[/\\].+\.js$/
} ),

```

**Comment by B4rtes** [comment]
@xinglie thanks for the provided options!

I tried to use both options, but it still doesn't work.

In the second option I also have issue with building. Was able to fix just removing the _sourceFileRegexp_ property.

Should I import somewhere the translation file or folder?
 _en.po_ file contains
======
msgid ""
msgstr ""
"Language: en\n"
"Plural-Forms: \n"

msgid "text"
msgstr "Simple text"
=======
In the pluginUI.js I call t("text").

**Comment by xinglie** [comment]
@B4rtes 
I read `CKEditorWebpackPlugin` source code ,I think change your `webpack.config.js` `CKEditorWebpackPlugin` config like below
```js
new CKEditorWebpackPlugin( {
    packageNamesPattern:/ckeditor5-[^/\\]+[/\\].+\.js$/,
    sourceFilesPattern:/ckeditor5-[^/\\]+[/\\].+\.js$/
} ),

```

**Comment by ihavecoke** [comment]
@B4rtes Maybe you can try create custom plugins and import it. the plugin file init method like this:
``` javascript
init() {
    const t = this.editor.t;

    // Create two buttons and link them with numberedList and bulletedList commands.
    createUIComponent( this.editor, 'numberedList', "Any Text", numberedListIcon )
  }
```

**Comment by yoyo837** [comment]
How to add .po file localization for custom plugin from folder, not from npm?

**Comment by Reinmar** [comment]
Probably worth mentioning that our package generator supports translations: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/plugins/package-generator/using-package-generator.html
