### ISSUE TITLE
SpecialCharacters plugin first-time load is too slow

### ISSUE THREAD

**Issue by bahung1221** [ckeditor/ckeditor5#8545]
Hi there,

## 📝 Provide a description of the improvement
Currently, I adding some emoji to `SpecialCharacters` plugin. 

It worked but still have a little UX problem, the plugin was load too slow for the first time I open it, maybe cause by lazy load or something like this, I don't know. 
I confirmed that the default items of `SpecialCharacters` still occur that issue, you can try directly in the sample editor on [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html#adding-characters-to-an-existing-category).

So, can we have an option to allow load the plugin popup without waiting for the user open it?

![Screen-Recording-2020-11-30-at-2](https://user-images.githubusercontent.com/27690861/100620615-30dba280-3351-11eb-9680-fa5ee7d52248.gif)

Best regards 😄 

## 📃 Other details

* Browser: Chrome
* OS: MacOS
* CKEditor version: 23.1.0
* Installed CKEditor plugins: SpecialCharacters
---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. We are aware of this issue and you can read more about it here - #6161. Also, feel free to add :+1: to the first post and join the discussion to bump its popularity!
