### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [ckeditor/ckeditor5#8546]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by vokiel** [comment]
Hi Alvaro,

thank you for contacting us. We've just created the Security Advisory, you're welcome to contribute with your findings. In case you don't have enough access please let us know.

**Comment by pwntester** [comment]
Thanks! closing the public issue then

**Comment by mlewand** [comment]
Moving the discussion to security advisory.
