### ISSUE TITLE
[Edge] ContextualToolbar moves to the beginning of the list item after applying inline styling

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#855]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-editor-balloon/tests/manual/ballooneditor.html.
2. Convert some block to the list.
3. Start the selection at the beginning of the list item and move it to the right.
4. Click on the bold icon from the contextual toolbar.

## ✅ Expected result

The contextual toolbar doesn't change its position.

## ❎ Actual result

The contextual toolbar moves to the beginning of the list item.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36302603-4e0dd1b8-1309-11e8-864e-4d102dcb808b.gif)

**Other information**

OS: Windows 10
Browser: Edge

**Comment by FilipTokarski** [comment]
Doesn't happen anymore, can be closed.
