### ISSUE TITLE
How to add addListToDropdown and  createDropdown in custom build

### ISSUE THREAD

**Issue by shankar5147** [ckeditor/ckeditor5#8556]
I am Install ckeditor5-ui and adding
import {
  addListToDropdown,
  createDropdown
} from '@ckeditor/ckeditor5-ui/src/dropdown/utils';

result: 
I am getting this error CKEditorError: ckeditor-duplicated-modules

![ck-issue](https://user-images.githubusercontent.com/43570538/100710237-6f1aa580-33d5-11eb-843a-4bf8b8f08a3a.png)

**Comment by FilipTokarski** [comment]
Hi, could you describe the steps you are taking and what precisely you are trying to achieve? The [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) may indicate that you are for example using packages with different versions or adding plugins to the build, so please check if that's not the case here.

**Comment by gellweiler** [comment]
I had the same issue. However it turned out that the issue wasn't directly caused by addListToDropdown but by:

`import Model from '@ckeditor/ckeditor5-ui/src/model';`

This is needed for new Module() when creating the ListDropdownDefinition.

Couldn't find the source of the issue however my workaround is:

```
const dropdown = createDropdown( undefined );

const button: ListDropdownButtonDefinition = {
  type: 'button',
  model:{
    id: "example",
    withText: true,
    label: "example"
  }
} as unknown as ListDropdownButtonDefinition;
  
const items: Collection<ListDropdownItemDefinition> = new Collection();
items.add(button);

addListToDropdown(dropdown, items);
```
