### ISSUE TITLE
Creating multiline toolbars in online builder

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8567]
## 📝 Provide a description of the improvement

In online builder (https://ckeditor.com/ckeditor-5/online-builder/) it should be possible to take advantage of #6146 and allow toolbar line break using `-`. The challenge here – if a line break was added, we need to set `shouldGroupWhenFull` to `false` automatically in the generated build's config.

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by AnnaTomanek** [comment]
This will be done as part of the CKEditor 5 online builder project that has a separate issue tracker.
