### ISSUE TITLE
npm fails to install on ckeditor5 and classic version

### ISSUE THREAD

**Issue by jwandrews99** [ckeditor/ckeditor5#8570]
## 📝 Provide detailed reproduction steps (if any)

npm i @ckeditor/ckeditor5-react

### ✔️ Expected result

installed module

### ❌ Actual result

$ npm i @ckeditor/ckeditor5-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from @ckeditor/ckeditor5-react@3.0.0
npm ERR! node_modules/@ckeditor/ckeditor5-react
npm ERR!   @ckeditor/ckeditor5-react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\japot\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\japot\AppData\Local\npm-cache\_logs\2020-12-02T18_10_43_167Z-debug.log

## 📃 Other details

* Browser: …
* OS: windows 10
* CKEditor version: latest
* Installed CKEditor plugins: none

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, I couldn't reproduce this error, the packages install without any problems. Please make sure that you follow our [docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and that there are no npm issues on your side.

**Comment by jwandrews99** [comment]
Hi, I get the same error, is it my version of react causing the issue? Being used inline with create-react-app
