### ISSUE TITLE
Markdown plugin doesn't recognize a basic table

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#8572]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html.
2.  Call

```html
editor.setData(`
	<p>test</p>
    <table>
        <tbody>
            <tr>
                <td>test</td>
                <td>test;</td>
                <td>nbsp;</td>
            </tr>
            <tr>
                <td>nbsp;</td>
                <td>nbsp;</td>
                <td>nbsp;</td>
            </tr>
            <tr>
                <td>nbsp;</td>
                <td>nbsp;</td>
                <td>nbsp;</td>
            </tr>
        </tbody>
    </table>
`)
```

### ✔️ Expected result

The table outputs as markdown.

### ❌ Actual result

The table outputs as HTML.

## 📃 Other details

This is interesting, as adding `<thead>` to the markup results in proper markdown output. 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It works fine. But you must not have indentation at the beginning of that HTML because it makes the MD parser to recognize this a as code snippet.

This worked:

![](https://user-images.githubusercontent.com/156149/101328512-63fdc480-3870-11eb-9945-9243c6fc508c.png)

This indeed didn't:

![](https://user-images.githubusercontent.com/156149/101328610-8263c000-3870-11eb-8ae4-a3157a35186b.png)

**Comment by mobilisedonline** [comment]
If you create a table using the table button but don't specify a header row then the table is left as HTML and isn't converted to markdown.

Markdown tables require a header so I can understand why it slips through but it would be better if all tables were automatically given a header row when the markdown plugin is installed.

**Comment by Thibibi** [comment]
Same problem here. Just add a simple table with the toolbar button, it is output as html instead of markdown. Workaround is to force a header row to have the markdown output.
