### ISSUE TITLE
Reusable icons from DLL build

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8574]
## 📝 Provide a description of the improvement

A follow-up to the #8517. In the mentioned ticket we've decided that some amount of duplication is OK to not block the whole issue. In the DLL approach, general icons are duplicated by every feature that uses it.

It would be nice to come with an idea to have those icons loaded from CKEditor 5 DLL.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
DUPs #8623.
