### ISSUE TITLE
Validate a need for ckeditor5-essentials to be exposed as DLL-consumer plugin

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8576]
## 📝 Provide a description of the improvement

During the work on #8517 we've identified that we can't have a DLL that consumes other DLL. For this reason, the editor DLL builds imports plugins required by the `Essentials` plugin directly.

This is a follow-up to the #8395, but does not block it in any way IMO.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
DUP of #8605. We plan to have essentials and other plugins that are included in the existing builds, bundled into the DLL-compatible editor bundles.
