### ISSUE TITLE
Check if DLL can be exposed in ckeditor5 main repository

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8578]
## Provide a description of the task

At this point, I think that we need to validate the last problem, which is - where to expose those paths (questions 2 & 3 in https://github.com/ckeditor/ckeditor5/issues/8517#issuecomment-737719336). The idea is to add a bigger reason for the `ckeditor5` package. It would also make imports a bit more sane, in that term that it would provide imports as:

```javascript
import { Plugin } from 'ckeditor5/core';
```

At the time of writing this issue, the #8517 issue branch uses `ckeditor5-dll` to provide DLL build. The imports paths look like below:

```javascript
import { Plugin } from '@ckeditor/ckeditor5-core/core`
```

This is because we would like to keep the ability to have imports to work the same way as in today's build using direct imports.

This of course requires an entry file in each package that exports public-public API:

```javascript
// file `core.js` in the `ckeditor5-core` package direclyt (not in /src).
export { default as Plugin } from './src/plugin';
export { default as Command } from './src/command';
export { default as Editor } from './src/editor/editor';
```

This is also duplicated by the `core.js` file inside `ckeditor5-dll` package:

```javascript
export * from '@ckeditor/ckeditor5-core/core';
```

---

Things to validate when moving those files from `ckeditor5-dll` to `ckeditor5`:

*   Does the DLL is built the same way?
*   I think that we need to change from where we're importing stuff. So every import form `@ckeditor/ckeditor5-feature` should be changed to `ckeditor5/feature`.
*   Do the yarn/npm workspace handle cyclic import?
    *    We put every package to the `ckeditor5/packages` but every package might also require one `ckeditor5` instead of the current mix of packages (mostly `uitls`, `ui` & `core`).
*   Do the test, manual tests, and docs works?

I do not consider this as a blocker to the main task, rather as an improvement.

**Comment by pomek** [comment]
Closed with https://github.com/ckeditor/ckeditor5/commit/80790e62c5450da612749b34afd9ac403d2ba594.
