### ISSUE TITLE
[Edge] Strange behaviour after pasting the icon from the toolbar to the dropdown item

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#858]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the article sample with the ContextualToolbar plugin.
2. Select some text in the editor.
3. Right-click on some icon from the contextual toolbar.
4. Click on `copy`.
5. Reveal the dropdown list.
6. Right-click on its item.
7. Click on `paste`.

## ✅ Expected result

The image is focused.

## ❎ Actual result

The image is blurred.

## 📃 Other details that might be useful

**Notes**

This is an edge case but might lead to crashes. After step 7, try to press <kbd>Delete</kbd> - the editor will crash.

Copying and pasting items from the toolbar is interesting, but I guess it's just Edge...

- Copy/paste of toolbar items is possible only if we have the selection in the editor.
- Editor won't crash if we repeat steps for the main toolbar.

```
SCRIPT5007: Unable to get property 'getChildren' of undefined or null reference
input.js (205,1)
```

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36313762-f30aa8f2-1332-11e8-8834-9a901a215a3f.gif)

**Other information**

OS: Windows 10
Browser: Edge

**Comment by oleq** [comment]
It doesn't look to me like something a regular user could do. More an edge case, actually.

**Comment by FilipTokarski** [comment]
Does not happen in the new Edge v.79.0.309.56

**Comment by Mgsy** [comment]
Fixed in the new Edge release.
