### ISSUE TITLE
Add ELSint rule to check inter-packages imports

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8581]
## 📝 Provide a description of the new feature

Follow-up for the #8395. We're going to change how we import things from other packages.

This ESLint rule should check if the imports from other packages are pointing to the package entry file instead of direct import.

In other words, depending on how the #8578 is resolved the imports should point to entry file:

```javascript
import { Plugin } from '@ckeditor/ckeditor5-core/core';
// or (see #8578)
import { Plugin } from 'ckeditor/core';
```

The wrong import would be:

```javascript
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
```

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
> Verify that the only thing that a package has in dependencies is ckeditor5 (from the set of pkgs maintained by us). Second rule – only import from the current package or ckeditor5 (also, only applies to the set of our packages). Let's have ESLint rules for that (#8581). Exception: the ckeditor5 package.

**Comment by Reinmar** [comment]
TODO: Update remaining incorrect imports (also in CF and internal).

**Comment by pomek** [comment]
In the `Title` plugin we need to refactor the code a bit:

```diff
-import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
-import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
+import { Plugin } from 'ckeditor5/src/core';
 
-import ViewDocumentFragment from '@ckeditor/ckeditor5-engine/src/view/documentfragment';
-import ViewDowncastWriter from '@ckeditor/ckeditor5-engine/src/view/downcastwriter';
-import first from '@ckeditor/ckeditor5-utils/src/first';
+import { first } from 'ckeditor5/src/utils';
 import {
+	UpcastWriter,
 	needsPlaceholder,
 	showPlaceholder,
 	hidePlaceholder,
 	enablePlaceholder
-} from '@ckeditor/ckeditor5-engine/src/view/placeholder';
+} from 'ckeditor5/src/engine';
```

```diff
@@ -44,7 +42,7 @@ export default class Title extends Plugin {
 	 * @inheritDoc
 	 */
 	static get requires() {
-		return [ Paragraph ];
+		return [ 'Paragraph' ];
 	}
```

```diff
 	/**
@@ -149,10 +147,11 @@ export default class Title extends Plugin {
 		const data = editor.data;
 		const model = editor.model;
 		const root = editor.model.document.getRoot();
-		const viewWriter = new ViewDowncastWriter( editor.editing.view.document );
+		const view = editor.editing.view;
+		const viewWriter = view.change( viewWriter => viewWriter );
 
 		const rootRange = model.createRangeIn( root );
-		const viewDocumentFragment = new ViewDocumentFragment( editor.editing.view.document );
+		const viewDocumentFragment = new UpcastWriter( view.document ).createDocumentFragment();
 
 		data.downcastDispatcher.conversionApi.options = options;
```

Are we fine with the changes above?

**Comment by Reinmar** [comment]
As for the `viewWriter`... This is a hacky code in that plugin, so there will be no prefect solution. I'd go with adding `ViewDowncastWriter` as additional export in `ckeditor5-engine`. Let's make this class accessible because I remember that I also had to use it once somewhere.

**Comment by Reinmar** [comment]
@pomek pointed out that this will mean using two different writers in one piece of code. I thought at first that these are two different methods. 

This piece of code is copied directly from `DataController#get()`. We could think about exposing somehow a piece of that logic and make it reusable, but this is for the future. For now, I think it's reasonable to add `createDocumentFragment()` to `DowncastWriter`. It's apparently needed when working in both directions (up and down).
