### ISSUE TITLE
Using a '-' divider in toolbar items config without the shouldNotGroupWhenFull option enabled causes displaying an unwanted separator.

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8582]
## 📝 Provide detailed reproduction steps (if any)

1.  In the editor configuration inside items list set `-` divider on any position
2.  `shouldNotGroupWhenFull` should be set to false (it is the default option) 
3.  Open editor

### ✔️ Expected result

There should not be any separator inserted in the place of `-`. Using `-` without `shouldNotGroupWhenFull` should not affect the toolbar.

### ❌ Actual result

There is an unwanted separator inserted in the place of `-`.

![](https://user-images.githubusercontent.com/16957311/101031372-e0935900-3579-11eb-954d-bbca6da1d02c.png)

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Haha, is this a feature or a bug? :D

We talked about logging a warning that `shouldNotGroupWhenFull` is enabled and a separator is used. This may be the simplest solution.

**Comment by oleq** [comment]
> We talked about logging a warning that shouldNotGroupWhenFull is enabled and a separator is used. This may be the simplest solution.

[There is one](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-ui/src/toolbar/toolbarview.js#L303). But maybe we should not render the view at all in this case.

**Comment by Reinmar** [comment]
> But maybe we should not render the view at all in this case

Which view? I don't understand what's the expected behavior in this case.

**Comment by oleq** [comment]
1.  `-` should create a new toolbar line, as in the documentation.
2.  If, due to other configuration (`shouldNotGroupWhenFull === false`) this is not possible, `-` should do nothing.
3.  According to the bug report, it spreads toolbar items, which is against 1.
4.  This means the behavior described in the bug report is a bug.
5.  The UI View corresponding to `-` in the toolbar configuration should not be rendered at all to address this bug.

**Comment by Reinmar** [comment]
Thanks. That clarifies it.
