### ISSUE TITLE
PasteFromOffice does not work in Custom Build

### ISSUE THREAD

**Issue by CarlosValencia78** [ckeditor/ckeditor5#8583]
1. Create Custom Build as mentioned in https://ckeditor.com/ckeditor-5/online-builder/
2. Choose PasteFromOffice, among other plugins
3. Upon unzipping file and opening sample > index.html, OR when using it in my code all plugins work EXCEPT PasteFromOffice

I am saying that PasteFromOffice does not work because I am using the same 'sample Word Document' provided by https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html

Upon copying and pasting the contents of this document onto the Editor that appears in the link above, the editor does indeed format everything pasted correctly as expected. 

However, when running locally on my computer or upon opening sample > index.html, the Editor does NOT format the same as shown on the sample editor in the link above. 

Here is my config:

`public Editor = Editor;

  editorConfig = {
    // plugins: [
    //   PasteFromOffice
    // ],
    toolbar: {
      items: [
        'bold',
        'italic',
        'underline',
        'link',
        'bulletedList',
        'numberedList',
        '|',
        'indent',
        'outdent',
        '|',
        'imageUpload',
        'blockQuote',
        'insertTable',
        'undo',
        'redo'
      ]
    }
  };`

Here is the import I used after bringing the Custom Build into my project:

import * as Editor from './ckeditor5/build/ckeditor';

I have also read in some articles that I must place PasteFromOffice in the config.plugins like so:

plugins: [
      PasteFromOffice
    ],

But I get the error:

Uncaught CKEditorError: ckeditor-duplicated-modules

Which I completely understand because there are certain duplicated modules in my imports. 

My question is, how do I properly set PasteFromOffice so that it works? The custom build sample > index.html does not work out the box, so I am a bit stumped. I would really appreciate some clarity, thanks in advance.

**Comment by FilipTokarski** [comment]
Hi, [as the documentation states](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html):
  

> The Paste from Office plugin only preserves content formatting and structures that are included in your CKEditor 5 build. 
> This means that you may need to add missing features such as font color or text alignment to your build.
  
You are missing plugins that actually format the content, like `fontColor`, `fontSize`, etc. You need to add them as well, when building editor from Online Builder.

**Comment by CarlosValencia78** [comment]
So besides fontColor, fontSize, text alignment, which ones are needed SPECIFICALLY in order to make PasteFromOffice to work?

**Comment by CarlosValencia78** [comment]
So I attempted it again using the advice you offered @FilipTokarski and it did the trick.

I truly and DEEPLY appreciate your help with this, thank you!!!!!!!!!!!!!!!!!

**Comment by CarlosValencia78** [comment]
![image](https://user-images.githubusercontent.com/33466298/101261064-53c7d700-3702-11eb-9713-b12d9a3dd9dd.png)

**Comment by CarlosValencia78** [comment]
What plugin is necessary for this arrow to show? When I copy and paste this, we see:

Next expected data refresh is December 4th.  

Ø  Any work that has not been attested by 12/4 will be overwritten during this refresh.

Which is exactly how it shows up in the custom build but NOT on the Paste From Word editor page (https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html)

You are correct (thanks by the way) in advising me to add other plugins such as fontColor, fontSize, text alignment, etc, but what about to show these characters? I have literally selected all special character plugins and upon pasting I am getting this O with a line through it.

I even selected all plugins which renders the editor completely uneditable, I just get an enormous image that covers the screen and some text behind it. 

What is the exact plugin for these symbols to appear?

What are the exact plugins included in the sample Editor on this page:
https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html

**Comment by FilipTokarski** [comment]
> What are the exact plugins included in the sample Editor on this page:
> https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html

Here you can see [plugins](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-paste-from-office/docs/_snippets/features/build-paste-from-office-source.js) and [config](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-paste-from-office/docs/_snippets/features/paste-from-office.js).  
  
Now, as it comes to the arrow character - I can reproduce it only if I use `SpecialCharactersArrows` and at the same time don't use `PasteFromOffice`.  
So, if you enable `PasteFromOffice` plugin, this arrow item will be converted to standard CKEditor list item and everything will work ok. Also, please keep in mind that CKEditor has a limited amount of [list item styles](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html#list-styles) and not everything copied from MS Word will look 100% the same.
