### ISSUE TITLE
Extract common part from the webpack.config.js file to factory function

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8586]
See: https://github.com/ckeditor/ckeditor5/pull/8564#issuecomment-738632056

**Comment by pomek** [comment]
Which convention should be used for naming exported packages to the global scope?

`CKEditor5.basicStyles` (camelCase) vs `CKeditor5.BasicStyles` (PascalCase)

IMO, the later one suggests that `BasicStyles` is a constructor.

**Comment by jodator** [comment]
Closed with [`c5c78d2`](https://github.com/ckeditor/ckeditor5/commit/c5c78d25797a86a57c9cc0976585cd18e2cec045).
