### ISSUE TITLE
Inline images - Feature guide

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8591]
Create a feature guide for inline images.
Add a mention in the image guide.

**Comment by pkwasnik** [comment]
[] Feature guide
[] Mention in image guide

**Comment by magda-chrzescian** [comment]
Might be worth mentioning in the guide, that the image style class will be applied to different elements in the editor view and the HTML output. More in this comment: https://github.com/ckeditor/ckeditor5/issues/8775#issuecomment-789015814

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5/issues/9339 is one of the pieces.

**Comment by magda-chrzescian** [comment]
> When you use EasyImage and load either ImageBlock or ImageInline (but not Image) there is a soft requirement error in the console because Image is missing.
> 
> The code of the EasyImage plugin does not use anything from @ckeditor/ckeditor5-image so this is a virtual requirement. Most likely we made Image the requirement of EasyImage to improve DX so developers don't have to include both if they want to use our service. The intention was good but it backfired when the API has changed.
> 
> The solution is getting rid of the requirement (breaking change) and mentioning in the migration guide that EasyImage must be used together with Image.

**Comment by oleq** [comment]
This task will be continued in #8591.

**Comment by oleq** [comment]
Closed in #9656.
