### ISSUE TITLE
Verify if Widget can be removed from the DLL build.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8597]
## Provide a description of the task

Verify that a `Widget` package can be optional and removed from the DLL build.

**Comment by jodator** [comment]
OMG, most of the widget utils will be cumbersome to change, especially as we import them in very low level utility methods.

The HTML embed package was quite easy (+/- 15 min of work): 151c21b

However, after initial changes in the image plugin it looks like the work can be very cumbersome as we would push `editor` / or `Widget` instance around and it will not look nice: 2fd3616.

For now I've stopped refactoring this package.

**Comment by Reinmar** [comment]
The decision for now - we'll not chase this. Let's have the widget package in the base dll.
