### ISSUE TITLE
Set the default language of WProofreader to EN_AI on our demos

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#8598]
Page: https://ckeditor.com/docs/ckeditor5/latest/features/spelling-and-grammar-checking.html
Language code: `EN_AI` https://docs.webspellchecker.net/display/WebSpellCheckerServer55x/Default+languages+list
Option name: `lang` https://webspellchecker.com/docs/api/wscbundle/Options.html

![Screen Shot 2020-12-07 at 2 55 23 PM](https://user-images.githubusercontent.com/545175/101359545-b7860780-389c-11eb-8f49-e496b7f55f7a.png)

**Comment by godai78** [comment]
I made the changes, but can't seem to get it to work and test it on my local server (didn't work before changes either). @ckeditor/qa-team can you have a look? Working branch is /docs-spelling-ai.

**Comment by godai78** [comment]
Thanks @Mgsy for workaround. Pushed.
