### ISSUE TITLE
Do we need `dll-*` packages?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8605]
## Provide a description of the task

Would be good to explain somewhere why they are needed.

**Comment by jodator** [comment]
I think that we could remove all the `ckeditor5-dll-*` packages and move the DLL build code and webpack configuration to `ckeditor5-build-*` packages. Thus, having less packages.

The con of this is that it might bring confusion to others and a clear separation of standard vs dll buld might help that.

**Comment by pomek** [comment]
Closed with https://github.com/ckeditor/ckeditor5/pull/8810.
