### ISSUE TITLE
There is no way to toggle widget's class (ui only) without touch the data model?

### ISSUE THREAD

**Issue by ulion** [ckeditor/ckeditor5#8606]
## 📝 Provide detailed reproduction steps (if any)
Well, I am trying to implement a collapsible widget, and it looks good,  except when refocus anywhere in the editor, the collapsed widget (only display title) get expanded again, just like it's not collapsed (since the class I added to the widget dom element is reset by the editor engine probably).

### ✔️ Expected result

Some UI only operations can be done via operate the widget's dom element's class (or anything else, then css can do its work according to the class change).

### ❌ Actual result

The dom element's class is resetted by editor engine when re-focus anywhere of the editor.

I know it's a little related to https://github.com/ckeditor/ckeditor5/issues/798 though here the requirement is more clear:

We need a method to do some UI adjustment, without change the data model/value, since we do not want this change be stored in data model, neither sync this change to other collaborative users. it is a local browser UI only toggle thing.

So, is there some official/unofficial way to do this? Any help is appreciated! Thank you.

My code sample:

```
        this.editor.editing.view.addObserver(ClickObserver);
        this.editor.editing.view.document.on('click', (evt, data) => {
            // collapsable-section-handle is an UIElement added under the widget container. the arrow to switch collapsed state.
            if (data.domTarget && data.domTarget.classList && data.domTarget.classList.contains('collapsable-section-handle')) {
                data.domTarget.parentElement.classList.toggle('collapsed');
            }
        });
```

agenda is the widget main container element.
```
section.agenda > .collapsable-section-handle {
	position: absolute;
    left: -23px;
    top: 2px;
    cursor: pointer;
}
section.agenda > .collapsable-section-handle:before {
	content: "\25bc";
}
section.agenda.collapsed > .collapsable-section-handle:before {
	content: "\25ba";
}
section.agenda > .collapsable-section-handle:hover {
	color: blue;
}
section.agenda.collapsed > * {
	display: none;
}
section.agenda.collapsed > .collapsable-section-handle, section.agenda.collapsed > .agenda-title {
	display: block;
}
```

**Comment by Reinmar** [comment]
You can always change the view by `editor.editing.view.change()` block (similar to the change block in the model, but for the editing view). You need to change the view of the editor by the view layer, not directly via the DOM.

All changes done directly to the DOM of the editor will be reverted so the DOM always matches the view of the editor. The only exception is inside `UIElement`s and `RawElement`s as they were designed specifically to allow rendering custom structures and make it completely transparent for the editor.

Hope this helps. If not, we can reopen the ticket.

**Comment by ulion** [comment]
Cool, it does work. So the only problem is that how to make developers like me figure out how to do such task without post issue here :D
