### ISSUE TITLE
Cannot Declare a Variable Twice iOS Simulator

### ISSUE THREAD

**Issue by mark-bragg** [ckeditor/ckeditor5#861]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

CKEditor 5 second alpha

## 📋 Steps to reproduce

1. I have CKEditor5 zip downloaded, and the js and js.map files included in the build
2. An HTML doc is opened within a web view and the basic setup is performed to create the classic editors in all the text areas
3. When the app is run on the simulator I get an error in the debugger of the developer portal of Safari

## ✅ Expected result
No errors in the debugger

## ❎ Actual result
Errors in the debugger

## 📃 Other details that might be useful
The errors are occurring in the CKEditor build file
![debugger1](https://user-images.githubusercontent.com/15349627/36396902-1f7470be-1575-11e8-8b6a-8906322e4438.png)
![debugger2](https://user-images.githubusercontent.com/15349627/36396905-226346b0-1575-11e8-946a-9a6268f565b3.png)

**Comment by Reinmar** [comment]
This is due to a bug in Safari 10. See https://github.com/ckeditor/ckeditor5/issues/542.

It works fine since Safari 11.

**Comment by mark-bragg** [comment]
I see the npm package workaround, but are you aware of any cocoapod for it?

**Comment by mark-bragg** [comment]
Also, the github for babel-plugin-transform-es2015-block-scoping
<https://babeljs.io/docs/plugins/transform-es2015-block-scoping/> is gone.
I'm currently looking for it, do you know if it was deleted or the name was
changed?

**Comment by mark-bragg** [comment]
found it
