### ISSUE TITLE
HTML wrapping blocks for editable WYSIWYG content

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#8611]
## 📝 Provide a description of the new feature

Most of the time an inline HTML block is an overkill, and I rather want to wrap existing content in a div with a class/id (for styling), or something along those lines.

If user-submitted JS is allowed (e.g. if CKEditor is used in a site builder, which is my usecase), then it also makes sense to add arbitrary HTML elements like `<canvas>` or `<input>` that the user can use for small JS demos.

I made a sketch of how this could look.

<img src="https://user-images.githubusercontent.com/1523306/101551513-6451a900-39b1-11eb-998b-5ad129e39010.png" width="500px">

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
Oh, looks like it might be a duplicate of https://github.com/ckeditor/ckeditor5/issues/6462. Happy to close and move if this is actually so.

**Comment by Reinmar** [comment]
Yeah, that could be a DUP of #6462. I was indeed thinking about making it more generic than just for div elements. Also, it should be relatively simple if this is implemented as a widget. Maybe only for stuff like `<canvas>` that need to be rendered differently. In this case, the HTML embed feature would actually handle that: https://ckeditor.com/docs/ckeditor5/latest/features/html-embed.html.
