### ISSUE TITLE
Adjust releasing scripts to handle changes related to DLL

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8616]
## Provide a description of the task

As for now, the `ckeditor5` package is empty on npm.

After closing https://github.com/ckeditor/ckeditor5/issues/8395, we will have some source code in the package that should be released on npm.

We need to figure out what we would like to release and how much work it requires from us.

**Comment by pomek** [comment]
The [`releaseSubRepositories()`](https://github.com/ckeditor/ckeditor5-dev/blob/88cd33d5de08916379671e8da29fab8f75134892/packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js#L51-L67) function that we use for releasing packages allows defining empty releases. It means the published package will not contain any source code. See: [https://unpkg.com/browse/ckeditor5@23.1.0/](https://unpkg.com/browse/ckeditor5@23.1.0/).

How it looks now in the code:
https://github.com/ckeditor/ckeditor5/blob/b963b0cda36ab9f0485aef8cca727c7b63846f2b/scripts/release/publish.js#L31-L38

In fact, the `description` property in the source code is other than the published on npm:

<table>
	<tr>
		<td>GitHub</td>
		<td>npm</td>
	</tr>
	<tr>
		<td>
<a href="https://github.com/ckeditor/ckeditor5/blob/b963b0cda36ab9f0485aef8cca727c7b63846f2b/package.json#L4">ckeditor5/package.json#L4</a>
		</td>
		<td>
<a href="https://unpkg.com/browse/ckeditor5@23.1.0/package.json">ckeditor5@23.1.0/package.json</a>
		</td>
	</tr>
</table>


We could improve the function by renaming the `*empty*` options to `*custom*`. Also, by adding a new option (`customReleasesFiles`), we could define which files and directories should be copied from the source packages.

One more thing. As for now, the published `ckeditor5` package does not define any dependencies. 

After introducing DLLs, the "core" packages should be added as `dependencies`.

```js
const ckeditor5Dependencies = {};

// Some operations on FS that will extract required packages and add those into `ckeditor5Dependencies` object.

require( '@ckeditor/ckeditor5-dev-env' )
	.releaseSubRepositories( {
		cwd: process.cwd(),
		packages: 'packages',
		customReleases: [ // Renamed from `emptyReleases`. It is an array of packages that should be modified before publishing.
			'ckeditor5'
		],
		packageJsonForCustomReleases: { // An object that modifies the `package.json` for each package. 
			ckeditor5: {
				dependencies: ckeditor5Dependencies
			}
		},
		customReleasesFiles: {
			ckeditor5: [ // An array of glob patterns. Files that match to those patterns will be released.
				'src/*.js', // All JS files from the `src/` directory.
				'dist/' // Everything from the `dist/` directory.
			]
		},
		dryRun: process.argv.includes( '--dry-run' )
	} );
```

**Comment by jodator** [comment]
Related (build process): #8593.
