### ISSUE TITLE
Failing tests of the image resizer after DLL changes

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8617]
## 📝 Provide detailed reproduction steps (if any)

I don't know why those fail. It looks totally random and sometimes it do not fail if running step-by-step in debug mode.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
All changes have:

```
See: https://github.com/ckeditor/ckeditor5/issues/8617.
```

annotation.

**Comment by jodator** [comment]
I've removed it from #8395 as I got all tests passing with 100% so it should not block the release of DLLs.

**Comment by Reinmar** [comment]
All works fine atm. Let's open a new ticket once we see that something starts failing.
