### ISSUE TITLE
Paste From Word [PFW] doesn't read styles from document header.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#8618]
## 📝 Provide detailed reproduction steps (if any)

1.  Open CKEditor good amount of plugins installed (basic styles, font colors, font styles, lists)
2.  Open attached MS Word file
3.  Paste file contents into CKEditor  
    Attachment: [Sample CK Paste Document.zip](https://github.com/ckeditor/ckeditor5/files/5666387/Sample.CK.Paste.Document.zip)

### ✔️ Expected result

Pasted content looks like in MS Word document.

### ❌ Actual result

Pasted content is missing: bold and some font styles: color navy, sizes, family.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: 23.1.0
*   Installed CKEditor plugins: pastefromoffice

From what I have checked, these styles are kept in document header and are only applied through classes, not inline styles e.g

```
<style>
...
p.RTabletextboldstyle9pts, li.RTabletextboldstyle9pts, div.RTabletextboldstyle9pts
    {mso-style-name:"R Table text bold style 9pts";
    mso-style-priority:99;
    mso-style-unhide:no;
    margin-top:3.0pt;
    margin-right:2.25pt;
    margin-bottom:0cm;
    margin-left:0cm;
    margin-bottom:.0001pt;
    line-height:10.0pt;
    mso-line-height-rule:exactly;
    mso-pagination:widow-orphan;
    font-size:9.0pt;
    mso-bidi-font-size:10.0pt;
    font-family:"Arial","sans-serif";
    mso-fareast-font-family:PMingLiU;
    mso-bidi-font-family:"Times New Roman";
    color:navy;
    letter-spacing:-.4pt;
    mso-ansi-language:EN-GB;
    mso-fareast-language:EN-GB;
    font-weight:bold;
    mso-bidi-font-weight:normal;
    mso-no-proof:yes;}
....
<p class=RTabletextboldstyle9pts style='margin-bottom:3.0pt;text-align:justify;
line-height:115%;background:white;mso-shading:navy;mso-pattern:solid white'><span
lang=EN-GB style='font-size:14.0pt;mso-bidi-font-size:10.0pt;line-height:115%;
mso-no-proof:no'>Valuation</span><span lang=EN-GB style='font-size:10.0pt;
line-height:115%;font-weight:normal;mso-no-proof:no'>: </span><span lang=EN-GB
style='font-weight:normal'>Lorem Ipsum&nbsp;is simply dummy text of the
printing and typesetting industry. <o:p></o:p></span></p>
...
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
DUP of #10577
