### ISSUE TITLE
CSS class and IDs on the default content is omitted by CKEditor.

### ISSUE THREAD

**Issue by sarvap-praharanayuthan** [ckeditor/ckeditor5#862]
Feature request: Do not omit the CSS classes and or ID in the default content in CKEditor.

## 💻 Version of CKEditor
Ckeditor 5 1.0.0-alpha.2

## 📋 Steps to reproduce

1. Default content with CSS classes are displayed in the CKEditor without CSS classes
2. `<textarea><p class='small'>Sample Para</p></textarea>`

## ✅ Expected result

```
<div class="ck-blurred ck-editor__editable ck-rounded-corners ck-editor__editable_inline" contenteditable="true" role="textbox" aria-label="Rich Text Editor, main">
   <p class='small'>Sample Para</p>
</div>
```

## ❎ Actual result

```
<div class="ck-blurred ck-editor__editable ck-rounded-corners ck-editor__editable_inline" contenteditable="true" role="textbox" aria-label="Rich Text Editor, main">
   <p>Sample Para</p>
</div>
```

## 📃 Other details that might be useful

Adding the content via `.then(e => {e.setData(html)})` where var html contains the actual HTML too omits the CSS class.

**Comment by Reinmar** [comment]
Please see my answer on https://stackoverflow.com/questions/47734328/ckeditor-5-allow-span-elements-and-attributes. It explains why it's happening and how to deal with it.
