### ISSUE TITLE
Ckeditor5 stop inserting span

### ISSUE THREAD

**Issue by ofelipelima** [ckeditor/ckeditor5#8622]
Hi Team
I'm in a 2 days headache trying to found why ckeditor5 inserts a <span> tag in my custom tags and decided to give I try with you; maybe you can help me to understand and solve.

We have custom tags for CMS functions. Example:
{related::1234}
So system parse this {related} tag and get the number inside it to do something.

When I save the text and ckeditor5 reload content, my tag is now like:
`{related::<span style="background-color:rgb(255,255,255);color:rgb(63,66,84);">1234</span>}`

So with this <span> tag our system parser is not working as expected.

Why? How can I disable this?

We are migrating from ckeditor4 and having some dificulties - we're almost rolling back to v4 :(

- I don't know if this is the right place but we also miss the following function:
  -> Always paste all from clipboard as plain text to editor (most of our editors/journalists do not like to paste with another site's styles because sometimes our site layout becomes buggy because of copied styles when pasting to ckeditor - we try to facilitate and minorize human errors by lazyness or leak of attention or automated work) - pointing docs for this would be really apreciated

Thank you guys be safe

**Comment by Mgsy** [comment]
Hi, thanks for the report. Could you please provide steps to reproduce the problem?

**Comment by ofelipelima** [comment]
Very sorry about late response.

The step is to paste tags like:
{related::1234}

or use ckeditor 5 insert text to insert same tag, guess was like:

editor.model.change( writer => {
    const insertPosition = editor.model.document.selection.getFirstPosition();
    writer.insertText( '{related::1234}', insertPosition );
} );

Both methods cause ckeditor 5 to insert a span tag between number inside tag.

Unfortunately we rollback to ckeditor 4 because of this problem only :(
