### ISSUE TITLE
[React] ParseError: 'import' and 'export' may appear only with 'sourceType: module' when adding plugin

### ISSUE THREAD

**Issue by MartialSeron** [ckeditor/ckeditor5#8626]
## 📝 Provide detailed reproduction steps (if any)

Here's my code

```
import React, { useState } from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
```

babelify config 

```
{
...
       transform: [
          [
            'babelify',
            {
              presets: [['@babel/preset-env', { targets: { esmodules: true } }], '@babel/preset-react'],
            },
          ],
          'uglifyify',
        ],
...
}

```
### ✔️ Expected result

No errors

> Running "browserify:dist" (browserify) task
> \>\> Bundle .tmp/public/react/test/index.js created.

### ❌ Actual result

I'm getting this error when I add any plugin (I didn't tested all of them though) :
Without plugin, it bundles perfectly.

> Running "browserify:dist" (browserify) task
>\>\> /mnt/c/Users/mseron/projects/test/node_modules/@ckeditor/ckeditor5-essentials/src/essentials.js:10
>\>\> import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
>\>\> ^
>\>\> ParseError: 'import' and 'export' may appear only with 'sourceType: module'

I don't know if it's a config issue or not. Need help.

**Comment by Mgsy** [comment]
Hi, thanks for the report. The main issue I can see in your code is that you try to import a build and a plugin at the same time.:

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
```

CKEditor 5 doesn't allow such imports, if you'd like to add a plugin to the build, you have to do it in the build configuration file. Additionally, the Essentials plugin is [already enabled in the classic build](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/src/ckeditor.js#L9), so there's no need for loading it once again. 

Also, please make sure that you follow our [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html).

**Comment by MartialSeron** [comment]
Thanks @Mgsy 

Let's say I want the classic build with Markdown support.
I have to fork the classic build, customize it with `@ckeditor/ckeditor5-markdown-gfm` and then import my fork in my project's dependencies.
Am I correct ?

**Comment by Mgsy** [comment]
That's correct. You can read more about installing plugins [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build).
