### ISSUE TITLE
Multiline toolbar in the documentation

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#8636]
With the introduction of #6146 multiline toolbar we should reflect this option in the docs:

*   [x] Introduce multiline setup to selected guides (especially those with more buttons, document-like editors).
*   [x] Create a separate toolbar guide that would show various toolbar configuration possibilities.

**Comment by godai78** [comment]
Multiline toolbars have been introduced into the Export to and Pagination guides: cksource/ckeditor5-internal#516.  
  
The separate toolbar configuration guide with demos is being worked on here: #8585 (due today, most probably).

**Comment by godai78** [comment]
Please look over the guide structure and opinionate the demos.
