### ISSUE TITLE
[desktop Safari] Can not select a link in a table cell

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#8638]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-5/demo/
2. Create a table with a single cell
3. In the cell, create a link followed by some text
4. Try to select from the end to the beginning

### ✔️ Expected result

Can select everything.

### ❌ Actual result

Can not select the link.

![2020-12-10 16 17 47](https://user-images.githubusercontent.com/1523306/101791228-95da8980-3b03-11eb-90e5-524a4d7776e0.gif)

## 📃 Other details

* Browser: Safari 14.0.1
* OS: macOS Catalina
* CKEditor version: ?
* Installed CKEditor plugins: ?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Hello. I followed the steps but I can not reproduce this bug.  My Safari version is 13.1.3. 

![](https://user-images.githubusercontent.com/58658048/101891721-b6a5ec00-3ba2-11eb-8633-6fb2cad702a9.gif)

Are there any additional steps that have to be done to get this bug? What was your order of adding link and text inside this cell?

**Comment by neongreen** [comment]
Here is a full demonstration:

![2020-12-11 11 32 55](https://user-images.githubusercontent.com/1523306/101893314-a21f1f00-3bb5-11eb-947f-fd21da8050ca.gif)

**Comment by neongreen** [comment]
Turns out the [Liner](https://getliner.com/) extension is at fault.
