### ISSUE TITLE
Check whether all public plugins are available via index files

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8639]
## Provide a description of the task

Follow up to: #8608.

Plugins to check:

*   The `Title` plugin was not exported.
*   The `Clipbord` requires might be not needed

**Comment by Reinmar** [comment]
Kinda DUPs #8635.

**Comment by Reinmar** [comment]
> The Clipbord requires might be not needed

Let's handle this in #8635. Not a priority for now.

> The Title plugin was not exported.

Let's export it.

**Comment by Reinmar** [comment]
Base64UploadAdapter
SimpleUploadAdapter
