### ISSUE TITLE
How to add custom class when using writer.insertText

### ISSUE THREAD

**Issue by crying2812** [ckeditor/ckeditor5#8643]
## Provide a description of the task
I using insertText() to create new paragraph, how can i add custom class for new element?

_What steps should be taken to fulfill the task?_
Here is my code: 
`js
const docFrag = editor.model.change(writer => {

                const p1 = writer.createElement('paragraph', {class: 'flashback'});

                const docFrag = writer.createDocumentFragment();

                writer.append(p1, docFrag);

                writer.insertText('※   ※   ※', p1);

                return docFrag;
            });
`

* Browser: Chrome
* OS: Window
* CKEditor version: 5

**Comment by Mgsy** [comment]
Hi, thanks for the report. Did you allow `class` attribute on the `paragraph` element in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and provide proper [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-attributeToAttribute) for this attribute? The simplified implementation could look like this:

```javascript
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

export default class AllowClassAttribute extends Plugin {
    init() {
        const editor = this.editor;

        editor.model.schema.extend( 'paragraph', { allowAttributes: [ 'class' ] } );

        editor.conversion.attributeToAttribute( { model: 'class', view: 'class' } );
    }
}
```

**Comment by crying2812** [comment]
> Hi, thanks for the report. Did you allow `class` attribute on the `paragraph` element in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and provide proper [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-attributeToAttribute) for this attribute? The simplified implementation could look like this:
> 
> ```js
> import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
> 
> export default class AllowClassAttribute extends Plugin {
>     init() {
>         const editor = this.editor;
> 
>         editor.model.schema.extend( 'paragraph', { allowAttributes: [ 'class' ] } );
> 
>         editor.conversion.attributeToAttribute( { model: 'class', view: 'class' } );
>     }
> }
> ```

Thanks @Mgsy, it worked.

**Comment by dustinormond** [comment]
I am running into this same issue. I have added this:

        ckeditor.model.schema.extend( 'paragraph', { allowAttributes: [ 'class', 'contenteditable' ] } );
        ckeditor.conversion.attributeToAttribute( { model: 'class', view: 'class' } );
        ckeditor.conversion.attributeToAttribute( { model: 'contenteditable', view: 'contenteditable' } );

However, this only works for changes after the model has been loaded. I don't really understand which file I need to edit to include the import and export as mentioned above. Is this done before build? If so, which files do I need to edit before build?
