### ISSUE TITLE
insertText feature

### ISSUE THREAD

**Issue by ibogdan94** [ckeditor/ckeditor5#865]
## 🐞 feature request

- Feature

## 💻 Version of CKEditor

CKEditor 5 Classic 

## 📋 Steps to reproduce

1. Want to insert text in the cursor possition
2. Text insert to the bottom of the editor
3. In previous version, I can do like this:

```js
  $('#{{ id }}').closest('.form-group').on('click', '.possible-template-fields a', () => {
        CKEDITOR.instances.{{ id }}.insertText($(this).attr('data-value'));
      });
```

## ✅ Expected result
Need insertText feature for version 5
## ❎ Actual result
Can't do this with version 5

**Comment by zadam** [comment]
See https://stackoverflow.com/questions/47611200/how-to-programatically-insert-link-at-current-position-in-ckeditor-5 which works for me on 1.0.0.alpha.2

This is for link, but you should be able to adapt it for text easily.

**Comment by Reinmar** [comment]
I asked @scofalik to update my answer on SO with examples how this will be done after 1.0.0-beta. Let's have there examples how to insert plain text and how to insert text with attributes, ok?

**Comment by ibogdan94** [comment]
@zadam, @Reinmar but how I can use existing build (CKEditor 5 classic editor build v1.0.0-alpha.2), my project don't use any js frameworks yet, only jquery. Have any suggestions?

**Comment by Reinmar** [comment]
> @zadam, @Reinmar but how I can use existing build (CKEditor 5 classic editor build v1.0.0-alpha.2), my project don't use any js frameworks yet, only jquery. Have any suggestions?

You can't do this without rebuilding the editor. I described how you can insert text in 1.0.0-alpha.2 on https://stackoverflow.com/questions/47611200/how-to-programatically-insert-link-at-current-position-in-ckeditor-5.

**Comment by scofalik** [comment]
@Reinmar I've updated your answer. Please review it and accept.

**Comment by Reinmar** [comment]
Some users rejected your edit (as a reason they stated that your edits promote the project... WTH ;/) Fortunately, I was able to override them.

**Comment by cedricium** [comment]
Great SO writeup, very useful! I was able to adapt that answer to insert text - I wonder if / how would you insert an element with a predefined class?

Given a custom keystroke, I'd like to insert `<span>&#9;</span>` with a `class="tab-char"`, where
```css
.tab-char { white-space: pre; }
```
effectively inserting a tab character into the editor. Any thoughts - I'm using a `after 1.0.0-beta (March 2018)` build.

**Comment by oleq** [comment]
First things first, [you need a feature to handle `<span class="tab-char">`](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/faq.html#why-the-editor-filters-out-my-content-styles-classes-elements-where-is-configallowedcontent-true). You need to define it in the model and provide converters for it.
 
Then, once the editor understands this kind of data, you can [insert it whenever you want](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/faq.html#where-are-the-editorinserthtml-and-editorinserttext-methods-how-to-insert-some-content).

**Comment by Reinmar** [comment]
The [SO answer](https://stackoverflow.com/questions/47611200/how-to-programatically-insert-link-at-current-position-in-ckeditor-5) is up to date and the [API docs are in place too](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-insertText) so, I'm closing this.
