### ISSUE TITLE
Keyboard Shortcuts are not working 

### ISSUE THREAD

**Issue by gok9ok** [ckeditor/ckeditor5#8653]
## 📝 Provide detailed reproduction steps (if any)

When using some shortcuts on Mac, Control key acts like Command. So for example if I hit Control B instead of moving one character backward, it bolds, or if I hit Control K instead of clearing the text right to the cursor, it opens link dialogue.   
  
However, for example Control P, behaves as expected. 

## 📃 Other details

*   Browser: Chrome, although same issue is also mentioned in Firefox 
*   OS: MacOS 10.14.5
*   CKEditor version: Tried in on demos on [docs](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) as well as the [website](https://ckeditor.com/ckeditor-5/demo/). 

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by AnnaTomanek** [comment]
Originally reported here: https://news.ycombinator.com/item?id=25394609

**Comment by AnnaTomanek** [comment]
Looks like this could be related/duplicate: #5705

**Comment by oleq** [comment]
Fixed in #5705.
