### ISSUE TITLE
Inline images - Support for clipboard

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8659]
1. Implement pasting an inline image from several sources:
    1. external websites
    2. PFO (Word, Docs)
    3. CKEditor itself
2. Implement the insertion heuristic for a single image and mixed content (under consideration)

**Comment by pkwasnik** [comment]
- [ ] clipboard + PFO
- [ ] compat with CKE4's `image `and `image2`

**Comment by pkwasnik** [comment]
How insertion heuristic should work? 

Proposition:
- For a single image use the same logic as for base image insert/upload. Use the config option. If smart conversion selected, use the block in a new paragraph, inline for the rest.
- For mixed content detect the image type from the source

**Comment by oleq** [comment]
TODO: Let's make sure `AutoImage` upcasts to `image` instead of `imageInline` when pasting a link into an empty block. In other words, this feature should be in pair with the image upload.

**Comment by oleq** [comment]
Closed in #9351.

**Comment by uaza** [comment]
> TODO: Let's make sure `AutoImage` upcasts to `image` instead of `imageInline` when pasting a link into an empty block. In other words, this feature should be in pair with the image upload.

This todo would be important for us and great if implemented. Has this already been implemented or is this still on the roadmap?
