### ISSUE TITLE
Mark nightly docs in a distinctive way

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#866]
Developers find things in the nightly docs which are not yet published and things break. This is a serious issue now, when we're after the refactoring, but before the release, but it will be important every time we add something.

cc @oleq

**Comment by Reinmar** [comment]
BTW, we should also remove all links to nightly docs except intentional links.

**Comment by oleq** [comment]
Something like this (or very similar) should do the trick. A quick mockup:

![screen shot 2018-02-26 at 16 10 37](https://user-images.githubusercontent.com/1099479/36677894-a4a43fa4-1b0f-11e8-8d25-8dc277144141.png)

**Comment by Reinmar** [comment]
cc @m-turek @msamsel can we easily parametrise this in Umberto? That it's shown when building the nightly, and removed when building the official version?

If not, I'd add it using JS when hostname equals `ckeditor.github.io`. But here the question would be  whether I can add some JS by using umberto.json or something.

**Comment by oleq** [comment]
FYI, the background is `repeating-linear-gradient(   45deg,   #ffe447,   #ffe447 10px,   #efd63a 10px,   #efd63a 20px )`

**Comment by m-turek** [comment]
> cc @m-turek @msamsel can we easily parametrise this in Umberto? That it's shown when building the nightly, and removed when building the official version?

We can add an option to Umberto, let's say `nightly: true` and it should be easy

**Comment by oleq** [comment]
FYI: This will be handled in the documentation generator.
