### ISSUE TITLE
Inline images - Base image insert and upload support

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8660]
1. Automatically choose the right image type when inserting a new image from sources:
    1. upload from computer
    2. insert by URL
2. Three new config options for inserting new images:
    1. always inline (default)
    2. always block
    3. be smart
3. Smart insertion uses block images in an empty paragraph and inline for the rest.

**Comment by pkwasnik** [comment]
This is still under consideration, but there are mainly two options:
- inline images by default
- simply heuristic, e.g. block images in an empty paragraph, inline for the rest

**Comment by oleq** [comment]
Closed in #8966.
