### ISSUE TITLE
Images - Research compatibility with CKE4's image, image2 and easyimage plugins

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8663]
Support displaying images generated by CKEditor 4's `image`, `image2`, and `easyimage` plugins. We shouldn't change the image type when loading content.

**Comment by oleq** [comment]
[**Results**](https://www.notion.so/v4-images-migration-breakdown-c304665a3cc84e9a8f82222c8b3ec591).

**Comment by suracekumar632** [comment]
![pexels-cottonbro-4761788](https://user-images.githubusercontent.com/100569625/178406698-11cb95d6-2284-4dc5-aa4b-173ff0b182db.jpg)
