### ISSUE TITLE
Inline images - Editing part

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8664]
Plugin architecture, schema, conversion, and commands, that allow changing of an image type from inline to block and back by the user.

Assumptions:
    1. Let's not duplicate plugins
    2. KISS for now and we may refactor it later in the process

- [x] Transforming a block image to an inline image.
- [x] Transforming an inline image to a block image.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/8726.
