### ISSUE TITLE
Inline images - MVP step 2

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8666]
- [ ] Linking images (we're fine with this: `<p><a><img>foo</a></p>`-> `<p><a><img></a><a>foo</a></p>`)
- [ ] Image resizing
- [ ] Support for loading only the inline image feature

**Comment by pomek** [comment]
Remember about link decorators.

**Comment by oleq** [comment]
I'm not sure why this issue is still open (it's not an epic). The first sub-feature is tracked in #8871. The rest is already done.
