### ISSUE TITLE
Special characters grid exceeds drop-down size on small screen.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#8669]
## 📝 Provide detailed reproduction steps (if any)

1.  Visit https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html with mobile.
2.  Open special character dropdown.

### ✔️ Expected result

The whole content of the drop-down should be visible inside the panel.

### ❌ Actual result

The content renders outside of the drop-down panel.

![](https://user-images.githubusercontent.com/14334820/102210321-51b80200-3ed2-11eb-873e-6f14d18eb3d9.png)

## 📃 Other details

*   Browser: Chrome
*   OS: Android/Windows

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Related #7700.
