### ISSUE TITLE
Rethink dll-sample samples

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8675]
## Provide a description of the task

During the work on #8395 we've created a bunch of `dll-sample` directories to test if the DLL build actually work. However, a better approach might be needed. Those samples were created off the most representative (or random) manual test from the package.

*   A one, mega sample that allows reconfiguring the editor plugins (cc @pomek )
*   Move all `dll-sample` samples somewhere.
*   What to do with other cases from manual samples?
*   Don't forget about the main `dll-sample` sample in `ckeditor5` repository.

**Comment by Reinmar** [comment]
Some notes:

- [ ]  All packages should be available here (all script tags added). We'll have to maintain this file the same way we maintain all-features manual test.
- [ ]  Like online builder. We need a list of checkboxes for all plugins. We also need a list of toolbar buttons that they introduce.
    - [ ]  Idea: we need these metadata anyway. Let's move them from the online builder to each package's `package.json`.
    - [ ]  Idea2: The UI part of the online builder was supposed to be made reusable anyway. Let's see if that's doable.
- [ ]  When will we need this manual test? During the testing phase and when we'll be working on the DLL support. For the former it's enough to add `yarn build:dll`  to the testing phase steps. For the latter, just mention it in the test description that you need to run this command.

**Comment by Reinmar** [comment]
In this iteration: Move the current sample to manual tests. We don't want to have this additional directory in the project's root dir.

Let's leave the adhoc plugin (the one that's not being compiled). Consider removing the plugin that needs to be compiled separately. Reasoning: we forget about rebuilding it anyway, plus, it dups what other packages test.

**Comment by Reinmar** [comment]
The automation and nice UI for the manual test (plugin and toolbar config via clicking) should be exposed to a separate ticket.
