### ISSUE TITLE
Impossible to use custom protocol in ckeditor link

### ISSUE THREAD

**Issue by TanyaGashtold** [ckeditor/ckeditor5#8686]
We are using links with custom protocol, like "ourProtocol://some-address". When this link is inserted in Ckeditor link it does not work and we see  <a href = "#">  instead of  <a href = "ourProtocol://some-address">  in the markup. Links like "https://some-address" work fine.  Is there any way to use links with custom protocol in link plagin?

**Comment by LukaszGudel** [comment]
Hi, thanks for the report. We are aware of this issue and you can read more about it here - #8248. Also, feel free to add 👍 to the first post and join the discussion to bump its popularity!

Currently "unknown" protocol in a link is replaced by '#'. But only inside the editor view. If you use `editor.getData()` then in returned string you will find \<a> tag with unchanged href attribute.
