### ISSUE TITLE
Custom dropdown list renders empty

### ISSUE THREAD

**Issue by ko4a** [ckeditor/ckeditor5#8688]
## 📝 Provide detailed reproduction steps (if any)
I want to make a simple plugin which has some keys in dropdown and on change it fetches data by key from my api and inserts it in my ckeditor

I followed this guide from documentation: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/ui-library.html#adding-a-list-to-a-dropdown

and my code looks like
```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import {createDropdown, addListToDropdown} from "@ckeditor/ckeditor5-ui/src/dropdown/utils";
import Collection from "@ckeditor/ckeditor5-utils/src/collection";
import Model from "@ckeditor/ckeditor5-engine/src/model/model";
import SplitButtonView from "@ckeditor/ckeditor5-ui/src/dropdown/button/splitbuttonview";

export default class Preset extends Plugin {

	static get pluginName() {
		return 'Preset';
	}

	init() {
		const editor = this.editor;

		editor.ui.componentFactory.add('Preset', locale => {
			
			const dropdownView = createDropdown(locale, SplitButtonView);
			dropdownView.buttonView.actionView.set({
				withText: true,
				label: "choose variable",
				tooltip: true
			});
			const items = new Collection();

			items.add({
				type: "button",
				model: new Model({
					withText: true,
					label: "Foo"
				})
			});

			items.add({
				type: "button",
				model: new Model({
					withText: true,
					label: "Bar"
				})
			});
			addListToDropdown(dropdownView, items);

			return dropdownView;

		});
	}
}

```
I expect that this code will generate dropdown with 2 elements - Foo and Bar, but list is empty

see screenshot there: https://prnt.sc/w3rswv

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Hello, it looks like your Model import path is incorrect. Replace line 4 with: `import Model from '@ckeditor/ckeditor5-ui/src/model';`. Using your code snippet I was also getting empty lists, but after changing Model import path list loaded properly with 'Foo' and 'Bar' items. Please, let me know if this fixes your issue.

**Comment by mfsi-suryar** [comment]
After 32 hrs of brainstorming, I just foundout that it's a bug in their framework and all of their documentations.

Instead of this:
```
items.add({
    type: 'button',
    model: new Model({
        id: 'en',
        withText: true,
        label: 'English',
    })
});
```
write as this:
```
items.add({
    type: 'button',
    model: {
        id: 'en',
        withText: true,
        label: 'English',
    }
});
```
Sh*t! I just wasted 3 days of my precious time.

**Comment by johnflux** [comment]
> Hello, it looks like your Model import path is incorrect. Replace line 4 with: `import Model from '@ckeditor/ckeditor5-ui/src/model';`. Using your code snippet I was also getting empty lists, but after changing Model import path list loaded properly with 'Foo' and 'Bar' items. Please, let me know if this fixes your issue.

Note this is no longer the correct way to import, and I don't know what to replace it with.

In the end I followed mfsi-suryar and forced it in typescript:

items.add({
    type: 'button',
    model: {
        id: 'en',
        withText: true,
        label: 'English',
    } as any
});

**Comment by Witoso** [comment]
> all of their documentations.

Could you link the docs?

In some past release we renamed `Model` import to `ViewModel` from the `ckeditor5`  package due to name collision. IF you're importing from `ckeditor5` `ViewModel` should be used.

**Comment by codeonprod** [comment]
> Could you link the docs?

The documentation is definitely updated within last month. Most probably late July or early August. I was browsing the docs on July 19th and the ```ViewModel``` implementation was not there.

I was following this: https://ckeditor.com/docs/ckeditor5/latest/framework/architecture/ui-library.html#adding-a-list-to-a-dropdown

**Comment by johnflux** [comment]
Can we update the docs here:
Expand: [addListToDropdown](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_dropdown_utils.html#function-addListToDropdown)

**Comment by mialdi98** [comment]
Faced the same issue. version 44.0.0

comment saved me: https://github.com/ckeditor/ckeditor5/issues/8688#issuecomment-2239331192
