### ISSUE TITLE
unable to add content dynamically

### ISSUE THREAD

**Issue by dubeyteja** [ckeditor/ckeditor5#8692]
## 📝 Provide detailed reproduction steps (if any)

1. I have created small editable content 
2. I want to append it to the editor but using setData doesn't help me.
3. small editable content is html content with restricted editing . it appends to the editor but it creates new placeholders continuously 

### ✔️ Expected result

_What is the expected result of the above steps?_

content should be appended to the editor without any placeholders.

### ❌ Actual result

_What is the actual result of the above steps?_

its causing placeholders to attach at the start continuously with the content I append

## 📃 Other details

* Browser: chrome
* OS: MacOS
* CKEditor version: 5
* Installed CKEditor plugins: restricted-editing

**Comment by Mgsy** [comment]
Hi, I'm sorry, but I'm not sure if I understand your issue properly. Could you please provide more details and describe steps to reproduce, actual result and expected result? Also, screenshots or gifs will be much appreciated.
