### ISSUE TITLE
Many manual samples have warnings

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#8695]
## Provide a description of the task

Many manual samples have warnings. The most common one is misconfigured image toolbar:

```
widget-toolbar-no-items {toolbarId: "image"} 
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items
```

**Comment by jodator** [comment]
And errors:

*   http://localhost:8125/ckeditor5-engine/tests/manual/placeholder.html

**Comment by psmyrek** [comment]
Separate issues have been created for these 2 errors:
* for placeholder test: https://github.com/ckeditor/ckeditor5/issues/8771
* for CSP violation in UI test: https://github.com/ckeditor/ckeditor5/issues/8772

**Comment by pomek** [comment]
Before starting – the manual test server must be run (`yarn run manual -r ckeditor5`). Note: `-r ckeditor5` means that we want to compile all manual tests in the repository `ckeditor/ckeditor5`.

The number of these tests is enormous, so checking them one by one can be time-consuming.

In the past, we created a tool for verifying whether pages render correctly. The crawler is located in the `ckeditor5-dev` repository. ([link.](https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/ckeditor5-dev-docs/lib/web-crawler)).

CKEditor 5 uses the tool for verifying manual tests. For example, type `yarn run manual:verify` in the console and wait a while. 

However, the tool searches only for errors. So temporary, we can disable the "error check" and pass all messages through the tool: https://github.com/ckeditor/ckeditor5-dev/blob/edd946f6ed61aab82b0d9573332fe6b566c89a5a/packages/ckeditor5-dev-docs/lib/web-crawler/index.js#L516-L518.

If it catches the mentioned `widget-toolbar-no-items` warning, we will know where to fix it.

The warning itself means that the image toolbar has no items.  Adjusting the editor's configuration should fix the problem:

```js
image: {
	toolbar: [
		'toggleImageCaption',
		'imageTextAlternative'
	]
}
```

It may require adding the `ImageCaption` and `ImageTextAlternative` plugins to the editor.

One more thing worth mentioning. Updating the crawler sources in `ckeditor5-dev` does not impact files installed in the `ckeditor5` repository. It would help if you connected these packages somehow, e.g., using the [`yarn link`](https://classic.yarnpkg.com/en/docs/cli/link/) command.
