### ISSUE TITLE
Stable branch auto merge doesn't properly show error in case of fail

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#8697]
## Provide a description of the task

When a commit is pushed to the `stable` branch it automatically triggers a merge from `stable` to `master`. Sometimes changes can't be merged (e.g. due to conflict).

We're getting a Slack notification when this happens but the message is saying what went wrong:

> 
> **Ref**
> 
> refs/heads/stable
> 
> **Event**
> 
> push
> 
> **Actions URL**
> 
> [https://github.com/ckeditor/ckeditor5/commit/4aae1c5a593a9258f71c41fb4dd97d3717d8b25e/checks](https://github.com/ckeditor/ckeditor5/commit/4aae1c5a593a9258f71c41fb4dd97d3717d8b25e/checks)
> 
> **Message**
> 
> Error, merge call returned code , see [https://developer.github.com/v3/repos/merging/#perform-a-merge](https://developer.github.com/v3/repos/merging/#perform-a-merge) for a list of codes with explanation.

It should include the information about the problem.

**Comment by mlewand** [comment]
In this case the problem was that stable (e85eec1) couldn't be merged to master (e56051e) due to:

```

Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by mlewand** [comment]
On the other hand we actually had only fails due to conflicts so far, so instead of making a fancy message based on _what really caused_ the fail we can just add information "(most likely caused by merge conflict)" - and that will be enough.

**Comment by pomek** [comment]
After removing the Github action, the issue will not occur anymore. We replaced the action with custom code.
