### ISSUE TITLE
Feed templates of new package with information

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#87]
In #42 I created the tempaltes but they need two values - app name and GitHub repo path.

**Comment by Reinmar** [comment]
There's one more value - project description. This should be a short sentence like "The core framework of CKEditor 5 project."

**Comment by Reinmar** [comment]
I also see that this description can be used in the package.json.

**Comment by szymonkups** [comment]
Created PR that tries to solve this issue. I'm using there the package name to fill `{{AppName}}` template variable. Now I am wondering if this is a good assumption that package name = app name, or this should be a separate thing. For example `ckeditor-core` uses `CKEditor 5 Core Framework` in readme files. Maybe we should treat {{AppName}} as something like "display" name?

**Comment by Reinmar** [comment]
I've just noticed your comment here :D. I think we clarified that in the PR.

Fixed by #92.
