### ISSUE TITLE
insertImage should be enabled by default in all builds

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#870]
I think it will be confusing for end users that there is no image button in the toolbar. The discoverability of image support is close to zero in an editor that does not have any content with images inside already. Which, unlike on our demo pages, is the reality. After all when you create content you most of the time start with an empty editor.

Even GitHub, being a developer-oriented environment provides a hint for end users on how to upload images:
![screen shot 2018-03-02 at 12 14 30](https://user-images.githubusercontent.com/545175/36896525-56d35768-1e13-11e8-998f-783c4d9d5390.png)

Having no UI that suggests that images can be uploaded is confusing, IMO.

WDYT?

**Comment by Reinmar** [comment]
Adding this button to the toolbar by default sounds like a good idea. We've seen enough confusion already.

Where would you place this button (I mean the buttons order)?

**Comment by Reinmar** [comment]
cc @oleq

**Comment by wwalc** [comment]
> Where would you place this button (I mean the buttons order)?

I don't have any strong preferences here, apart from wishing to have the link and insertImage buttons close to each other (they both are frequently used and "insert" something).

## Current

	items: [
		'headings',
		'|',
		'bold',
		'italic',
		'link',
		'bulletedList',
		'numberedList',
		'blockQuote',
		'undo',
		'redo'
	]

## Proposal

	items: [
		'headings',
		'|',
		'bold',
		'italic',
		'bulletedList',
		'numberedList',
		'link',
		'insertImage',
		'blockQuote',
		'undo',
		'redo'
	]

My reasoning: from basic features and frequently used to less frequently used (I have not stats, just intuition and own experience)

**Comment by Reinmar** [comment]
cc @oleq WDYT?

**Comment by oleq** [comment]
LGTM. I'll check it live and give you the feedback ASAP.

**Comment by oleq** [comment]
It looks as follows

<img width="835" alt="screen shot 2018-03-05 at 15 10 06" src="https://user-images.githubusercontent.com/1099479/36979305-53c048d0-2087-11e8-8fda-e67ac0f34c25.png">

We could also go ocdish

<img width="826" alt="screen shot 2018-03-05 at 15 11 43" src="https://user-images.githubusercontent.com/1099479/36979386-a0063290-2087-11e8-8ea9-ecfc0d6f11e9.png">

but the first one LGTM.

@wwalc s/insertImage/uploadImage/?

**Comment by Reinmar** [comment]
> @wwalc s/insertImage/uploadImage/?

The name of the button was changed in this iteration. It was `insertImage` previously, but it's actually completely upload-oriented, so we decided to keep it consistent with that so we can propose `insertImage` with a wider range of options in the future.

**Comment by Reinmar** [comment]
Closed with:

* https://github.com/ckeditor/ckeditor5-build-classic/commit/f6cab12a612787ed36c267c9b35b7df4cde5f405
* https://github.com/ckeditor/ckeditor5-build-inline/commit/67e0779bdce18f379307ec35d2b4c77d77369f2c
* https://github.com/ckeditor/ckeditor5-build-balloon/commit/a1f94512801a6cd459115b31da4a0fea5738da3b
