### ISSUE TITLE
How can configure custom toolbar in decoupled ckeditor

### ISSUE THREAD

**Issue by s4sebin** [ckeditor/ckeditor5#8702]
I am trying to integrate @ckeditor/ckeditor5-vue2 in my NUXT project. But I couldn't make it because of the NUXT server-side rendering. So I have installed decoupled-CKEditor and I followed the steps mentioned in https://motorscript.com/using-ckeditor5-with-nuxtjs . Finally, the CKEditor is working but the toolbar is basic and I want to add some more configurations to the toolbar. I am not able to find any doc which helps to integrate it.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, if you want to add more plugins to your build, you need to  rebuild it or you can create editor from source. Please refer to [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) or [creating custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) docs. You can also use [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) for this purpose. You can then use your build in the Nuxt app.  
Also, I guess some solutions from [ticket about the Nuxt integration](https://github.com/ckeditor/ckeditor5/issues/6071) might be useful for you.
