### ISSUE TITLE
Ckeditor is not updating textarea value

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#8705]
## 📝 Provide detailed reproduction steps (if any)

http://plnkr.co/edit/2FCee5EGkqmARPhH?preview

1. Type something in ckeditor
2. Press 'get form value'
3. In console is result which is not updated

### ✔️ Expected result

According to https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#automatic-integration-with-html-forms it should be updated

### ❌ Actual result

Textarea value is not updated

**Comment by piernik** [comment]
@AnnaTomanek Can You take a look at it? Or maybe I'm doing something wrong?

**Comment by Mgsy** [comment]
Hi, as the documentation says, the textarea updates automatically after form submission. It means that the "submit" event should be called. After modifying your code and submitting the form, "Get form value" returns updated content.

```html
<form action="#" method="POST" onsubmit="event.preventDefault();">
    <textarea name="desc" id="editor">
      <p>This is some sample content.</p>
    </textarea>
    <p><input type="submit" value="Submit"></p>
</form>
<button id="btn">Get form value</button>
```

**Comment by piernik** [comment]
Oh... that's not good. I have my own form validation and I don't have value when I need it :/

**Comment by Mgsy** [comment]
How about using [`editor.updateSourceElement()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-updateSourceElement) after clicking on the button?

**Comment by piernik** [comment]
Sure I'll figure it out. 
Maybe You can pass an config option? 
```
'updateFormValue': 'onSend|onBlur|onUpdate',
'updateFormValueDebounce': 400, // only if updateFormValue = 'onUpdate'
```
Just a suggestion

**Comment by Mgsy** [comment]
Thanks for the suggestion! Could you please open a new feature request and describe how you would expect it to work? 

I will close this issue for now, as the original question seems to be answered. If you'll have some further questions, feel free to post them here!

**Comment by AdelN1368** [comment]
dsdsdsdsddsdsssccs

**Comment by justin-oh** [comment]
Posting for future people.

I had a problem with a form that was being submitted via Javascript. Something like:

```js
button.addEventListener('click', () => {
  fetch(form.action, {
    method: 'POST',
    body: new FormData(form),
  });
});
```

The solution was to manually trigger a submit event on the form prior to sending the data to the backend:

```diff
  button.addEventListener('click', () => {
+   form.dispatchEvent(new Event('submit'));
+                                           
    fetch(form.action, {
      method: 'POST',
      body: new FormData(form),
    });
  });
```

This successfully triggers the CKEditor instances to update their corresponding `textarea` values.
