### ISSUE TITLE
Can't delete a list after widget element using backspace

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#8706]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-5/demo/
2. Paste an image
3. Below the image, create a checkbox with any text
4. Go to the beginning of the checkbox text and press Backspace

![2020-12-17 14 06 30](https://user-images.githubusercontent.com/1523306/102491958-418a5900-4071-11eb-8020-00237fc6c8d4.gif)

### ✔️ Expected result

The checkbox becomes a normal paragraph.

### ❌ Actual result

Nothing is deleted, and the image is selected.

Note that everything works as expected without an image.

## 📃 Other details

* Browser: Chrome
* OS: macOS Catalina

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Hi, thank you for the report. I can confirm this issue. 

This issue can be found when any type of a list is added after widget element (image, embeded media, table).
