### ISSUE TITLE
How can i choose the suitable options for custom build

### ISSUE THREAD

**Issue by tranhanam19999** [ckeditor/ckeditor5#8713]
## 📝 Provide detailed reproduction steps (if any)

1. So im making a custom build, with a custom button as a plugin added to a build
2. The button will generate a <div> into the content of CKEditor
3. And then i will do sth like
```
document.getElementsByClassName("my-custom-box")[length - 1].style.backgroundImage = `url(${someUrlImage})`
```

### ✔️ Expected result

The image will be inside the content of CKEditor

### ❌ Actual result

Nothing happen, only the div appear

## 📃 Other details
One thing that i have noticed inside the div is that the ``` contenteditable = false ``` 
I cant query like appending document.getElementByClassName('my-custom-box')[0].style.backgroundImage = myImage
Which led me to config in the editingfile.js
```
schema.register('simpleBtn', {
      isObject: true,
      allowWhere: '$block',
      allowAtrributes: [ 'style' ],
      allowContentOf: '$block',
      allowAttributesOf: '$block'
})
```
But it doesnt work too
* Browser: Opera
* OS: Windows 10
* CKEditor version: 5 
* Installed CKEditor plugins: Classic Build and my custom plugin

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! I'm not sure if I understand your use case, so could you please tell more about the problem and what exactly you'd like to achieve? Some screenshots and the detailed description will be much appreciated.

**Comment by tranhanam19999** [comment]
Hi, i have achieved what i want, can i close this?

**Comment by Mgsy** [comment]
Great to hear you managed to solve your issue!
