### ISSUE TITLE
An indicator for new or updated docs.

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#8714]
We would benefit largely from having two indicators in the docs - **new** for a new guide, set automatically/manually and **updated** set manually (see linked issue below for explanations on why like this). Both would automatically expire after a set time.

The indicators would be displayed beside the title in the left-hand menu.

As described in details in this Umberto issue: cksource/umberto#882

**Comment by AnnaTomanek** [comment]
There is no need to open a separate issue for this for CKEditor 5 - it is tracked in the correct repository (Umberto) and it is marked with the correct squad (devops) as well as estimated. If you want to raise the priority of this, pin this issue on the squad channel.
