### ISSUE TITLE
Unable to select HTML embed when no other widget plugins are installed

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#8720]
## 📝 Provide detailed reproduction steps (if any)

1.  Configure online build with plugins: Bold, Italic, List, Link, HTML Embed
2.  Open sample.html
3.  Add html embed and try to select it

![](https://user-images.githubusercontent.com/58658048/102988053-a6cbc780-4513-11eb-92d6-8e0646708af5.gif)

### ✔️ Expected result

HTML snippet is selected and there are icons to add a paragraph before and after the element.

### ❌ Actual result

Unable to select HTML snippet.

## 📃 Other details

*   Browser: any
*   OS: macOS BigSur 11.1
*   CKEditor version: 24.0.0
*   Installed CKEditor plugins: Bold, Essentials, Italic, Link, HtmlEmbed, Paragraph
*   If I add Table or Image or Media Embed plugin to my build then HTMLEmbed is selected correctly

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
It's missing the Widget plugin in its deps. Compare to e.g. MediaEmbed.
