### ISSUE TITLE
Remember the language when creating a new code block

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#8722]
## 📝 Provide a description of the new feature

If I am using CKEditor to write an article, most of the time, when creating a new code block, I want to use the same code block language that I used the previous time. Otherwise I have to correct every single code block from "Plain text" to whatever programming language I am writing about.

It would be great to have this as a (perhaps opt-out?) feature.

Notion does this and it's been pretty intuitive.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Implementation wise, it could be implemented inside the command. However, I think that the option to reuse the previous choice should be explicit – by default the command should not do so. It means that the command would have to accept a param like `usePreviousLanguageChoice`.

**Comment by przemyslaw-zan** [comment]
Should this be the new default behavior, or off by default and only enabled by configuration?

**Comment by Reinmar** [comment]
It doesn't seem to have any negative effect on the UX so I'd go with this being on by default.
