### ISSUE TITLE
Implement the do–it–yourself type of an editor

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#873]
This kind of editor is required for us to showcase the [document editor](https://ckeditor.com/ckeditor-4/#document) (build) like we used to in v4.

## UI

This kind of editor (creator) will not render per se but instead provide the crucial building blocks for the developers to use in their application, e.g.:
* toolbar view
* editable view

They will be available as `editor.ui.view.toolbar` and `editor.ui.view.editable`, where the `editor.ui.view` is a direct, element–less extension of the `EditorUIView` class.

## Data

The editor will not replace an existing DOM element but it will [obtain the initial data as an argument](https://github.com/ckeditor/ckeditor5-core/issues/64).

## Config

The editor will support a configuration allowing a quicker configuration (positioning) of the UI elements in DOM, e.g. (config names WIP):

```
config = {
    ...
    ui: {
        toolbarContainer: document.querySelector( 'div.some-div' ),
        editableContainer: document.querySelector( 'main' )
    },
    ...
}
```

The above will basically do the following:

```js
document.querySelector( 'div.some-div' ).appendChild( editor.ui.view.toolbar.element );
document.querySelector( 'main' ).appendChild( editor.ui.view.editable.element );
```

once they are ready.

## Naming

That's the biggest problem so far. The name should express the nature of the editor — it provides the building blocks bound together as a whole (which is easy for developers) but does not force any DOM structure.

Ideas so far:
* `DIYEditor`,
* `AssembledEditor`,
* `ComposedEditor`,
* `DetachedEditor`,
* `BricksEditor`

**Comment by Reinmar** [comment]
Assembled and Composed 👎 – semantically, nothing's composed or assembled there.

DIY 👍 – it best describes what it is, but I'm not sure whether the `DIY` is well known.

Detached 👎 – this is not the right word – "detached" is about https://github.com/ckeditor/ckeditor5-core/issues/64.

Bricks – quite fine; but DIY works better for me.

**Comment by Reinmar** [comment]
More proposals (not saying that any good, but let's see):

* `ComponentsEditor` (as: editor exposing UI components)
* `CustomEditor` (problem: "custom editor" ~= "custom build")

**Comment by Reinmar** [comment]
cc @wojtekidd @AnnaTomanek @wwalc

**Comment by oleq** [comment]
https://www.collinsdictionary.com/dictionary/english/flat-pack?

**Comment by Reinmar** [comment]
That's not a very common idiom and I wouldn't know myself what it means. It wouldn't also ring any (correct) bells in my head.

**Comment by pjasiun** [comment]
👍 for `BricksEditor`, `DIYEditor`

**Comment by wojtekidd** [comment]
`ComponentsEditor` seems cool.

`DIYEditor` sounds a bit shabby IMO. DIY has sometimes these connotations like _handmade_ and also the [DIY ethic](https://en.wikipedia.org/wiki/DIY_ethic)

Other options:
`CustomizedEditor`
`PersonalizedEditor`
`BespokeEditor` as in _bespoke solution_

**Comment by pjasiun** [comment]
`BespokeEditor` is also cool :)

**Comment by jodator** [comment]
I'm for `DIYEditor` - the `BricksEditor` is not revealing enough. Also no for `BespokeEditor` (I had to google it :P )

Also this editor looks like a `FinishMeEditor` (`AlmostReadyEditor` ?) also a `WireframeEditor`.

**Comment by jodator** [comment]
After googling might be: https://en.wikipedia.org/wiki/Custom_software.

`TailorMadeEditor` (from wiki page linked above).

**Comment by scofalik** [comment]
Please, do not go with `DIYEditor`. Just, please. Trust @wojtekidd if you do not trust me. This does not sound good, really.

**Comment by Reinmar** [comment]
`TailorMade` and `Bespoke` have those connotations that this is ready to use and made precisely for you. While this creator is not about this. It's the fabric, the material you can use.

**Comment by pjasiun** [comment]
> TailorMade and Bespoke have those connotations that this is ready to use and made precisely for you. While this creator is not about this. It's the fabric, the material you can use.

No one expects, that the editor you downloaded from the CDN/website/npm is already tailored. This should be clear to everybody that we do not read your mind and if you need something tailored you need to do some final steps.

I really like `Bespoke` because it had no bad connotation. That is true that `BricksEditor` sounds like  `BlockEditor` and one may imagine something similar to the classic editor.

**Comment by Reinmar** [comment]
Yeah, I changed my mind. In this specific context people should not be confused. 

So, I'd personally choose from these two:

* `BespokeEditor`
* `ComponentsEditor`

**Comment by wwalc** [comment]
+0.5 `BespokeEditor`

**Comment by scofalik** [comment]
My suggestions:

`DecoupledEditor` - because UI/DOM elements are decoupled and you provide container,
`Attachable(Classic)Editor` - because UI/DOM are attached to provided containers,

Or make it a flag in `ClassicEditor` (`replaceElement: true/false`).

**Comment by jodator** [comment]
After thinking of `WireframeEditor`:

`BlueprintEditor`

**Comment by wojtekidd** [comment]
`DecoupledEditor` seems also OK to me, but I might not understand the context fully ;)

**Comment by oleq** [comment]
> Or make it a flag in ClassicEditor (replaceElement: true/false).

It does not make sense because `CE` imports certain UI classes that render the UI + behaviors like the sticky toolbar. It's a totally different kind of editor.

**Comment by Reinmar** [comment]
Additionally, https://github.com/ckeditor/ckeditor5-core/issues/64 is just a completely different scenario. You can have no replacing and still have the classic UI.

**Comment by oleq** [comment]
Maybe we could refer to the state of the UI here? E.g. `RenderlessEditor`, `BoxlessEditor`, `LooseEditor`.

**Comment by oleq** [comment]
Maybe `PartialEditor`? Devs are used to the concept of partials.

**Comment by jodator** [comment]
Huh... `IKEAEditor` - you have all the parts but you have to properly arrange & build them...

**Comment by wojtekidd** [comment]
`LooseEditor` is nice - also building on this `UnboundEditor` `ApartEditor` `UnattachedEditor` `UnleashedEditor` `UnrestrainedEditor`

**Comment by scofalik** [comment]
I once again propose `DecoupledEditor`. Look. In every other editor the UI is linked (coupled) with editable:

* classic - it is above the editing area,
* inline - it sticks to the editing area,
* balloon - it shows when you select something in the editing area.

In `DecoupledEditor` (or `DecoupledUIEditor`) the UI is completely decoupled from editing. It makes sense, really. Let's go for it.

**Comment by wwalc** [comment]
I'd be careful with proposing too complicated/long names (e.g. `UnrestrainedEditor`) to not end up with  Taumatawhakatangi­hangakoauauotamatea­turipukakapikimaunga­horonukupokaiwhen­uakitanatahuEditor.

**Comment by Reinmar** [comment]
One more idea – `GenericEditor`.

**Comment by Reinmar** [comment]
Or `UniversalEditor`.

**Comment by oleq** [comment]
Generic/Universal suggests some general/universal feature set instead of focusing on the flexibility of the UI.

**Comment by Reinmar** [comment]
I think that if we'll be that pedantic, then we won't find any name ;) Sure this word can be understood this way. But pretty much any word here can be misleading. Every word suggests something. But you need to stay at least a bit open when you learn about these things.

For now, the only other name I liked was `BespokeEditor` and `DIYEditor`. The latter is very precise. The former is quite good too, but its biggest strength is that it has very little connotations. It keeps your mind open until you learn what that thing really is. It even has this kind of proper name feeling.

**Comment by Reinmar** [comment]
In other words, let's try to find a "good enough" name. Something easy, not overengineered, not overthought, not confusing, and not too popular (so it doesn't appear too often in other contexts in our docs)

**Comment by Reinmar** [comment]
OK, so, let's sum this up.

We've got two proposals:

* `DecoupledEditor` – because its UI is decoupled into parts.
* `GenericEditor` – because it allows you to create (pretty much) every kind of editor.

Let's have a final vote:

👍 if you want `DecoupledEditor`
👎 if you want `GenericEditor`

**Comment by oleq** [comment]
It's `DecoupledEditor` then. Thanks for your votes!

---

Question about the configuration. ATM I resurrected the `ui` namespace in the config:

```js
DecoupledEditor
	.create( '<p>foo</p>', {
		plugins: [
			...
		],
		image: {
			toolbar: [ 'imageStyleFull', 'imageStyleSide' ]
		},
		ui: {
			toolbarContainer: '.doc-editor__top',
			editableContainer: '.doc-editor__editable'
		},
		toolbar: [
			'headings', '|', 'fontsize', 'fontfamily', '|',
			...
		]
	} )
```

we could go deeper

```js
DecoupledEditor
	.create( '<p>foo</p>', {
		plugins: [
			...
		],
		image: {
			toolbar: [ 'imageStyleFull', 'imageStyleSide' ]
		},
		ui: {
			decoupled: {
				toolbarContainer: '.doc-editor__top',
				editableContainer: '.doc-editor__editable'
			}
		},
		toolbar: [
			'headings', '|', 'fontsize', 'fontfamily', '|',
			...
		]
	} )
```

or quite the opposite

```js
DecoupledEditor
	.create( '<p>foo</p>', {
		plugins: [
			...
		],
		image: {
			toolbar: [ 'imageStyleFull', 'imageStyleSide' ]
		},
		decoupled: { // ?
			toolbarContainer: '.doc-editor__top',
			editableContainer: '.doc-editor__editable'
		},
		toolbar: [
			'headings', '|', 'fontsize', 'fontfamily', '|',
			...
		]
	} )
```

or even

```js
DecoupledEditor
	.create( '<p>foo</p>', {
		plugins: [
			...
		],
		image: {
			toolbar: [ 'imageStyleFull', 'imageStyleSide' ]
		},
		toolbarContainer: '.doc-editor__top',
		editableContainer: '.doc-editor__editable',
		toolbar: [
			'headings', '|', 'fontsize', 'fontfamily', '|',
			...
		]
	} )
```

Which one is best?

**Comment by scofalik** [comment]
> It's `DecoupledEditor` then. Thanks for your votes!
🎉 

As far as config is concerned, I am for `toolbarContainer` and `editableContainer` straight in the top-level of config (so last option).

**Comment by pjasiun** [comment]
I would not put `decoupled` in the config so 1 and 4 are fine for me.
