### ISSUE TITLE
Where is the event for deleting of image?

### ISSUE THREAD

**Issue by rosnaib11** [ckeditor/ckeditor5#8738]
I already searched the whole internet, couldn't find to add an event in docs, etc for deleting image something like `onImageRemoved` `onImageBeforeRemove`. Only this one but not stated in docs https://www.npmjs.com/package/ckeditor5-image-remove-event-callback-plugin is this one correct?!

Update:
Oh yea this one is working https://www.npmjs.com/package/ckeditor5-image-remove-event-callback-plugin 

please add events on docs

**Comment by Reinmar** [comment]
There's no specific event for image removal. Similar information may be obtained from [https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change:data](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change:data) and the differ, but with some additional work to "understand" the changes.

**Comment by Reinmar** [comment]
At the moment, I don't think that we'll be interested in adding an image-specific event. I'm happy to see, though, that there's a contrib plugin.

**Comment by papiscript** [comment]
The method used in the plugin has it's drawbacks:
1. it won't work for ckeditor >= 29
2. it fires callback also for ctrl+z

Regarding #1. Could anyone confirm that starting from ckeditor@29 the `change:data` event fires only for top lvl nodes, and all the children are not accessible from the callback (ie. ctrl+a the document -> delete selection -> if `<img/>` is wrapped with `<p>` then only `<p>` is accessible in the event data)? I think I've seen it somewhere in docs/thread and it was explained as performance gain change. Unfortunately i can't find it now.
