### ISSUE TITLE
Create a document editor example (and a build)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#874]
Created on top of the [do-it-yourself editor](https://github.com/ckeditor/ckeditor5/issues/873), the document editor example will correspond to [what we have in v4](https://ckeditor.com/ckeditor-4/#document).

## Docs

* The example will land in  https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/index.html.
* Mention in: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/overview.html#available-builds
* Tutorial: how to create the Document Editor example. 

## WIP

<img width="2032" alt="screen shot 2018-03-06 at 17 45 36" src="https://user-images.githubusercontent.com/1099479/37045427-349a2612-2166-11e8-81ad-f36c771e40e4.png">

![screen shot 2018-03-06 at 17 45 03](https://user-images.githubusercontent.com/1099479/37045389-200cab0c-2166-11e8-83de-9a9d4405a329.png)

**Comment by Reinmar** [comment]
That's already done!

**Comment by updatepromise2020** [comment]
@Reinmar i need your help please , i'm updated to cke 5 editor in my angular app, i used document editor plugin and use onready function to render it but i'm not able to upload any image file from my gallery , My question is how can i catch the image upload file and display it in the email body? 

i tried to configure the simple upload file adapter plugin but my application complains about the duplicate plugin , i'm not sure how can i use together 


this is my onready fun

 public onReady( editor ) {
  
        editor.ui.getEditableElement().parentElement.insertBefore(
            editor.ui.view.toolbar.element,
            editor.ui.getEditableElement()
        );
}

Any help will be appreciated!
thanks

**Comment by PaciekM** [comment]
@oleq hello, I see that you have implemented 'Fullscreen editor' mode, any advices how to implement it in react tsx?

**Comment by oleq** [comment]
@PaciekM Check out #1235. There are some ideas there and even a working community solution to the problem.
