### ISSUE TITLE
A code block suddenly switches from multiline to single-line when editing

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#8741]
## 📝 Provide detailed reproduction steps (if any)

Go to https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html. Type ```` ``` ```` to create a code block. Paste the following, with the initial empty line and the final empty line:

<pre><code>
((haskell-mode . 
 ((haskell-process-type . ghci)
  (haskell-process-path-ghci . "nix-shell")
  (haskell-process-args-ghci . ("--command" "ghci"))
  (eval . (add-hook 'before-save-hook #'ormolu-format-buffer nil t)))))

</code></pre>

Go to the first line and type `.`

![2021-01-01 23 29 57](https://user-images.githubusercontent.com/1523306/103447292-1c652f80-4c9a-11eb-96b5-679041a06292.gif)

### ✔️ Expected result

The `.` stays on the first line.

### ❌ Actual result

The whole block becomes single-line.

## 📃 Other details

* Browser: Chrome
* OS: macOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I can't reproduce this. I asked my colleagues to check it too. But in the meantime – do you perhaps have some browser extensions installed? I can see some additional copy marker and then some clock in the editable area.

**Comment by neongreen** [comment]
Oh alright, turns out it's [Liner](http://getliner.com/)'s fault.
