### ISSUE TITLE
Find a crawler to check whether all pages of our documentation and manual tests are green

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#8744]
Find a crawler that we could use to check whether all pages of our documentation and manual tests are green (no errors thrown):
* Ideally, it should use a real browser engine, such as headless Chrome.
* Ideally, it should be configurable in terms of which URLs to include (so e.g. API docs can be excluded).

**Comment by Reinmar** [comment]
Merged into `dll-integration`.
