### ISSUE TITLE
How can I disable a custom toolbar button in CKEditor 5 for individual

### ISSUE THREAD

**Issue by shankar5147** [ckeditor/ckeditor5#8748]
How can I disable custom toolbar for individual Items  In angular project

**Comment by LukaszGudel** [comment]
Hello. Every item in the toolbar is an object, which has `isEnabled` property. Setting it to false will disable this item. Setting it back to true will enable it. You can find those objects inside the `editor` object. 

Items in the toolbar have indexes, starting from 0. Separators '|' also counts.

To disable the first item in your toolbar, all you need to do is: 

```
editor.ui.view.toolbar.items.get(0).isEnabled = false; 
```

To get access to the `editor` object in your Angular project please follow [this section](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#accessing-the-editor-instance) in our Angular integration guide.

**Comment by shankar5147** [comment]
Thank You Replaying @LukaszGudel. Insert Image Button only not Working Remaining All  Working Good

**Comment by datasoysa** [comment]
This solution is not working for custom buttons, do you have any idea?

**Comment by RM6SS62** [comment]
> editor.ui.view.toolbar.items.get(0).isEnabled = false;

I have a problem with this, the button I want to disable is the uploadImage one, I pass the index 15 and the button disabled is the dropdown at the right (insertImage which I want to keep), then I set the index 14, and it disables the separator at the left.
Basically the uploadImage button is being ignored.

Any idea?
