### ISSUE TITLE
Image resizer doesn't work with LinkImage

### ISSUE THREAD

**Issue by Absolutely17** [ckeditor/ckeditor5#8749]
## 📝 Provide detailed reproduction steps (if any)

1. Insert image
2. Add link to image using LinkImage plugin
3. Close windows with editor and open again

### ✔️ Expected result

Resize buttons appeared on the image

### ❌ Actual result

Resize buttons did not appear on the image

This is due to a condition in imageresizehandler.js:

`if ( !domEvent.target.matches( 'figure.image.ck-widget > img' ) ) {
				return;
			}`
But with link on image the selector should be as follows: figure.image.ck-widget > a > img.

Tell me how can I fix this on my own? If I change imageresizehandler.js, then how can I load it correctly into my custom build

**Comment by LukaszGudel** [comment]
Hello. Thank you for the report. I can confirm this issue.

---

It can be reproduced by this data:

```
editor.setData(`<figure class="image"><a href="https://google.com"><img src="sample.jpg" alt="bar"></a></figure>`)
```

This behaviour is a regression. Git bisect points to [this commit.](https://github.com/ckeditor/ckeditor5/commit/c5dd33d8be5715bd4b68621eaefeee36a52e0915)

```
commit c5dd33d
Author: Paweł Smyrek <p.smyrek@cksource.com>
Date:   Fri Nov 20 08:48:28 2020 +0100
   Added stricter rule for attaching image resizer to an image
packages/ckeditor5-image/src/imageresize/imageresizehandles.js | 4 ++--
1 file changed, 2 insertions(+), 2 deletions(-) 
```
