### ISSUE TITLE
Paste from Office plugin not working in custom build of ckeditor.js.

### ISSUE THREAD

**Issue by santoshk10** [ckeditor/ckeditor5#8753]
We have created a custom build of ckeditor having various plugins including following:- 
Font Size
Font Family
Font Color
Paste from office
Is there any other configuration required in the ckeditor.create function as i am using following code for the configuration setup of ckeditor.

`	ClassicEditor
		.create(document.querySelector('#editor'), {
			fontSize: {
				options: [12, 14, 15, 16, 18, 20, 22],
				supportAllValues: true
			},
			image: {
				// Configure the available styles.
				styles: [
					'alignLeft', 'alignCenter', 'alignRight'
				],
				resizeOptions: [
					{
						name: 'imageResize:original',
						label: 'Original',
						value: null
					},
					{
						name: 'imageResize:50',
						label: '50%',
						value: '50'
					},
					{
						name: 'imageResize:75',
						label: '75%',
						value: '75'
					}
				],
                                toolbar: [
					'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
					'|',
					'imageResize',
					'|',
					'imageTextAlternative'
				]
			},
			toolbar: [
				'heading',
				'|',
				'alignment',                                                 // <--- ADDED
				'bold',
				'italic',
				'link',
				'bulletedList',
				'numberedList',
				'blockQuote',
				'undo',
				'redo',
				'fontBackgroundColor',
				'fontColor',
				'fontFamily',
				'fontSize',
				'subscript',
				'superscript',
				'underline',
				'highlight',
				'insertTable',
				'mergeTableCells',
				'imageStyle:full',
				'imageStyle:side',
			]
		})
		.then(editor => {
			window.editor = editor;
		})
		.catch(err => {
			console.error(err.stack);
		});` 

after pasting following content from word into ckeditor it converts the formatting of arrow and other symbols as below
Original Content:
![image](https://user-images.githubusercontent.com/29335501/103737176-ad7c3380-5017-11eb-83c3-f285f2e8a6f1.png)

ckeditor content and rich text box:
![image](https://user-images.githubusercontent.com/29335501/103737278-e4524980-5017-11eb-93a8-239ae24f590b.png)

any help is much appreciated.

**Comment by LukaszGudel** [comment]
Hello. Currently CKEditor5 is not supporting custom symbols for list-items markers. You can use [ListStyles](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html#list-styles) plugin that adds 3 types of markers for unordered lists and those are kept when pasting from Word. 

About the second issue, it looks like there could be some problems with text encoding. You can check encoding set in the Word document and in the html file. Also check if the font that you are using is supporting pasted symbols.
