### ISSUE TITLE
convert formula tag from <math> to <img> or <svg>

### ISSUE THREAD

**Issue by greatshieh** [ckeditor/ckeditor5#8763]
I am using Ckeditor5 with plugin [mathtype-ckeditor5](https://github.com/wiris/mathtype-ckeditor5).
The formula is OK in the editor. When I want to preview the content using editor.getData(), the formula tag is \<math\>. It can not be show in the page. MathJax can render the page but don't want to use this script. 
How can I get the formula with <img> when call editor.getData()?

**Comment by Mgsy** [comment]
Hi! MathType plugin is not maintained by CKEditor 5 team, but Wiris. All questions and feature requests related to MathType should be reported in their repository. 

Actually, this question was already asked, so please check this ticket - wiris/mathtype-ckeditor5#6.
