### ISSUE TITLE
VUE version

### ISSUE THREAD

**Issue by abelardolg** [ckeditor/ckeditor5#8766]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

---
By using your editor in Vue ecosystem

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Hello. Vue implementation for CKEditor5 is already available. See our documentation:

*   [Vue 2.x](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)
*   [Vue 3.x](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html)
