### ISSUE TITLE
[FF/Edge] Incorrect selection after pressing "CTRL + A" in the empty editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#877]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Delete whole content.
3. Press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>A</kbd>.

## ✅ Expected result
Nothing happens.

## ❎ Actual result
The caret disappears and inline styling buttons are disabled.

## 📃 Other details that might be useful
**GIF**

![bug_letters](https://user-images.githubusercontent.com/20988892/37081238-10968b56-21e9-11e8-8f3a-d755d1b3a062.gif)

OS: All platforms
Browser: Firefox, Edge

**Comment by Reinmar** [comment]
It's the same issue as https://github.com/ckeditor/ckeditor5/issues/562. And has a PR in https://github.com/ckeditor/ckeditor5-engine/pull/1151, but which still requires significant work.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore.
