### ISSUE TITLE
Manual test for placeholder throws an error

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#8771]
## 📝 Provide detailed reproduction steps (if any)

1. Run `yarn manual --files=engine`.
2. Open http://localhost:8125/ckeditor5-engine/tests/manual/placeholder.html.

### ✔️ Expected result

There is no error in the console.

### ❌ Actual result

There is an error in console:
```
TypeError: view.render is not a function
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Consider removing the test if fixing it takes too many hours.
