### ISSUE TITLE
Invalid link to image.png in the Link docs

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#8778]
## 📝 Provide a description of requested docs changes

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/link.html#demo-2.
2. Click the `downloadable resource` link in the editor and then the `image.png` link in the baloon.

Error: the 404 page is opened.

**Comment by pomek** [comment]
Fixed with https://github.com/ckeditor/ckeditor5/pull/9122.
