### ISSUE TITLE
Cannot update ckeditor5-editor-balloon to v24

### ISSUE THREAD

**Issue by lucaguindani** [ckeditor/ckeditor5#8780]
## 📝 Provide detailed reproduction steps (if any)

Update @ckeditor/ckeditor5-editor-balloon from v23 to v24 (https://www.npmjs.com/package/@ckeditor/ckeditor5-editor-balloon)

### ✔️ Expected result

Successful update

### ❌ Actual result

`fetchPackageMetaData error for @ckeditor/ckeditor5-editor-balloon@^24.0.0 504 Gateway Time-out`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ckeditor/ckeditor5-editor-balloon@^24.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Mgsy** [comment]
It looks like some connection or npm-related issue. Could you please try again after a few minutes and verify whether the same issue occurs for other packages (not related to CKEditor 5)?

**Comment by lucaguindani** [comment]
I'll try later, but other packages were successfully updated.

I did the same for other @ckeditor/xx packages.

**Comment by Mgsy** [comment]
I've just checked the package and it has installed properly:

```shell
npm install @ckeditor/ckeditor5-editor-balloon@^24.0.0
+ @ckeditor/ckeditor5-editor-balloon@24.0.0
added 5 packages from 1 contributor, removed 1 package and audited 1510 packages in 9.709s
```

**Comment by lucaguindani** [comment]
Strange, some kind caching of issue with an npm repository maybe...

```
17 http fetch GET 200 https://registry.npm.taobao.org/@ckeditor%2fckeditor5-editor-balloon 809ms
18 silly fetchPackageMetaData error for @ckeditor/ckeditor5-editor-balloon@^24.0.0 No matching version found for @ckeditor/ckeditor5-editor-balloon@^24.0.0.
19 silly fetchPackageMetaData error for @ckeditor/ckeditor5-editor-balloon@^24.0.0 No matching version found for @ckeditor/ckeditor5-editor-balloon@^24.0.0.
```

**Comment by lucaguindani** [comment]
Ok I switched the npm registry to "https://registry.npmjs.org/" and it works. Looks like "https://registry.npm.taobao.org/" is not updated with the v24 version.
