### ISSUE TITLE
DLL: Decide what to do with imports in ckeditor5-essentials

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8782]
## Provide a description of the task

After introducing the ESlint rule for our imports (https://github.com/ckeditor/ckeditor5/issues/8581), the content of the `packages/ckeditor5-essentials/src/essentials.js` file does not pass:

https://github.com/ckeditor/ckeditor5/blob/ae65599e1e76acdd108d38eeaf2f1a61b1d7aaa5/packages/ckeditor5-essentials/src/essentials.js#L10-L17

⬇️ Should it be?

```js
import { Plugin } from 'ckeditor5/src/core';

import { Clipboard } from 'ckeditor5/src/clipboard';
import { Enter, ShiftEnter } from 'ckeditor5/src/enter';
import { SelectAll } from 'ckeditor5/src/select-all';
import { Typing } from 'ckeditor5/src/typing';
import { Undo } from 'ckeditor5/src/undo';
```

As for now, I'll disable the new rule for the essential package.

**Comment by Reinmar** [comment]
> ⬇️ Should it be?

Yup. Already done.
