### ISSUE TITLE
getData() output plain text instead of HTML (question)

### ISSUE THREAD

**Issue by pdanno** [ckeditor/ckeditor5#8787]
Hello, 
I'm creating an integration of CKEditor5 in a nocode tool.
The editor is working great with the decoupled editor build, but I needed more plugins. 
I created a custom build, and everything works fine except the getData(). Now it output plain text instead of html.

I can't find the issue so far. In the CKinspector, everything looks fine, but the data outputed is not the one I want. 

Here is my editor & CKinspector :
![Screenshot 2021-01-08 at 16 24 00](https://user-images.githubusercontent.com/35064558/104032969-312c5080-51cf-11eb-971d-04e3f44119ed.png)

I'm currently on the trial of the pagination plugin with this in my console : "You are using the trial version of CKEditor 5 pagination plugin with limited usage. Make sure you will not use it in the production environment.", and no further explanation on the  "limited usage"

**Could it be linked to this ? Do you have an idea where to look to find my bug ? or what to test ?**

thanks a lot ! :)

## 📝 Provide detailed reproduction steps (if any)
Difficult to answer, mostly managed on the nocode tool ...

### ✔️ Expected result

`<p>This is a test line 1<br><br>This is a test line 2</p>`

### ❌ Actual result
plain text as : 
"This is a test line 1  
  
This is a test line 2"

my console when logging  `console.log(editor.getData());` in the DecoupledEditorDocument promise: 
![Screenshot 2021-01-08 at 16 25 21](https://user-images.githubusercontent.com/35064558/104033597-08f12180-51d0-11eb-9a88-335eb739da46.png)

## 📃 Other details

* Browser: Chrome
* OS: macOS
* First affected CKEditor version: 5
* Installed CKEditor plugins: 
* *

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! The pagination trial shouldn't change the data returned by `editor#getData()` from HTML to plain text. Could you please push your build to your GitHub repository, so I could clone and run it locally to see what's going on (of course remove your pagination trial license key from the config)?

**Comment by pdanno** [comment]
@Mgsy here we go : https://github.com/pdanno/CKE5forreview 
My integration code in my nocode tool is nearly the same as the html sample page, and the bug seems to be the same in the sample page anyway.

NB : When I add a table to my "document"/editor, the html of the table appears with the getData() (li, ul, table tags), but the content inside the table is still plain text

**Comment by Mgsy** [comment]
@pdanno I believe this issue is caused by the Markdown plugin, see - #7864. It occurs, because the initial content is intended, so Markdown processor interprets it as a code block and wraps this HTML into one. That's why it's returned by the plain text.

To fix this issue, you can simply remove indentation of your elements in the initial HTML content.
