### ISSUE TITLE
Pasting HTML embed widget does not paste it's content

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#8789]
## 📝 Provide detailed reproduction steps (if any)

1.  https://ckeditor.com/docs/ckeditor5/latest/features/html-embed.html
2.  Copy HTML widget
3.  Paste HTML widget

### ✔️ Expected result

Widget is pasted with its content.

### ❌ Actual result

Content of HTML widget is empty.

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This is because HTML embed feature is registering `rawContentMatcher` on the `editor.data.processor` [https://github.com/ckeditor/ckeditor5/blob/ca58a3bc8bd2981c69b934f5e500eac2bd9b501e/packages/ckeditor5-html-embed/src/htmlembedediting.js#L98](https://github.com/ckeditor/ckeditor5/blob/ca58a3bc8bd2981c69b934f5e500eac2bd9b501e/packages/ckeditor5-html-embed/src/htmlembedediting.js#L98) but Clipboard plugin is using a separate instance of `HTMLProcessor` https://github.com/ckeditor/ckeditor5/blob/ca58a3bc8bd2981c69b934f5e500eac2bd9b501e/packages/ckeditor5-clipboard/src/clipboard.js#L61

**Comment by maxbarnas** [comment]
I see that in both cases \`HTMLDataProcessor\` is initialized with the same Document view. Seems reasonable to use `HTMLDataProcessor` from the editor instance. Am I missing something? Surely, this fixes the problem when tested locally.

**Comment by niegowski** [comment]
Unfortunately, the `editor.data.processor` could be sth different than HTMLProcessor - i.e. it could be a markdown processor but for clipboard we need HTML processor. I was thinking about integrating it in a way that clipboard feature would be able to automatically use same matchers as those registered in data pipeline processor.

**Comment by maxbarnas** [comment]
Gotcha! To be clear, `editor.data.processor` can be something different, depending on the contents the editor wants to handle, but the clipboard, in its current form, always expects HTML or plain text. That's why we need those two processors decoupled?

**Comment by niegowski** [comment]
> Gotcha! To be clear, `editor.data.processor` can be something different, depending on the contents the editor wants to handle, but the clipboard, in its current form, always expects HTML or plain text, right? That's why we need those two processors decoupled?

That's correct
