### ISSUE TITLE
404 errors caused by tippy and popperjs in nightly docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8793]
Visit: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/mentions.html

```
GET https://ckeditor5.github.io/node_modules/tippy.js/dist/tippy.css net::ERR_ABORTED 404
mentions.html:32 GET https://ckeditor5.github.io/node_modules/tippy.js/themes/light-border.css net::ERR_ABORTED 404
mentions.html:808 GET https://ckeditor5.github.io/node_modules/@popperjs/core/dist/umd/popper.min.js net::ERR_ABORTED 404
mentions.html:809 GET https://ckeditor5.github.io/node_modules/tippy.js/dist/tippy-bundle.umd.min.js net::ERR_ABORTED 404
mentions.html:808 GET https://ckeditor5.github.io/node_modules/@popperjs/core/dist/umd/popper.min.js net::ERR_ABORTED 404
mentions.html:809 GET https://ckeditor5.github.io/node_modules/tippy.js/dist/tippy-bundle.umd.min.js net::ERR_ABORTED 404
```

![image](https://user-images.githubusercontent.com/156149/104161262-d83d0200-53f2-11eb-96b2-1cbbe400c38b.png)

I don't like two things here:

* That we read from node_modules directly. As you can see – it's not published on nightly docs.
* That we need to load 4 more files just for the toolbar hints.

We should try fixing at least the first issue, but if we can also reduce the second issue (e.g. by somehow merging these files into existing assests), then it'd be great. But the latter seems like a bigger deal, so if we won't see the light in the tunnel quickly, it may not be worth digging deeper.

**Comment by Reinmar** [comment]
It seems that the same issue will occur on official documentation because I don't think that we're publishing the entire node_modules directory there.

**Comment by oleq** [comment]
Looks like the docs builder should copy these assets instead of referencing them from `node_modules`.
