### ISSUE TITLE
Update docs about configuring EasyImage

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#880]
We need to update a couple of places:

* `module:cloudservices/cloudservices~CloudServicesConfig#uploadUrl`
* `module:cloudservices/cloudservices~CloudServicesConfig#tokenUrl`
* https://github.com/ckeditor/ckeditor5/blob/stable/docs/features/image-upload.md

**Comment by wwalc** [comment]
Updated docs are in the stable branch.

**Comment by Reinmar** [comment]
Merged to master too.
