### ISSUE TITLE
Disabled toolbar buttons still show active/focus styling when disabled

### ISSUE THREAD

**Issue by austingreendev** [ckeditor/ckeditor5#8806]
## 📝 Provide detailed reproduction steps (if any)

1. Use an editor where a toolbar button is in a disabled state. Decrease indent is the one I'm currently testing.
2. While the button is disabled, press the button, and the focus ring will be visible.

### ✔️ Expected result

I would expect disabled buttons to not show any interactive styling, including focus and active states.

### ❌ Actual result

Disabled buttons include focus/active styling as if they were not disabled.

![Screen Shot 2021-01-11 at 9 25 38 AM](https://user-images.githubusercontent.com/4030377/104217044-b8580f00-53ef-11eb-9cf4-067c0a7fe79c.png)

## 📃 Other details

* Browser: Chrome
* OS: Mac OSX
* First affected CKEditor version: Current version on [classic demo](https://ckeditor.com/ckeditor-5/demo/#classic)
* Installed CKEditor plugins: Current version on [classic demo](https://ckeditor.com/ckeditor-5/demo/#classic)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! AFAIR, this is intentional and critical for a11y reasons. If I remember correctly, the reasoning was that disabled buttons should not "disappear". We discussed this in the past in one of the issues, but I cannot find it now. Maybe @oleq will know.

cc @magda-chrzescian

**Comment by mlewand** [comment]
Yes it was an intentional choice. There are two reasons one is to make it possible to understand the state of commands (though UI buttons) for visually impaired users and to make the UI predictable (so that you navigate the UI same way each time instead of having it dependent on the context).

**Comment by magda-chrzescian** [comment]
IMO the issue concerns more the appearance of the button than its functionality.

As far as I can see, we actually do have different styling for the focus state of the disabled buttons. But it is hard to recognize if the direct comparison with enabled buttons can't be made (e.g. in read-only mode).
![image](https://user-images.githubusercontent.com/14334820/105022350-f38abb80-5a49-11eb-81f6-904c0a8c9d36.png)

So if what we want to achieve is to not confuse the user with VISUALLY focused buttons, we could just slightly change the styling for something like that:
![image](https://user-images.githubusercontent.com/14334820/105023264-06ea5680-5a4b-11eb-8856-5106bf36bc11.png)
or even not apply any border/outline on foucus.

**Comment by austingreendev** [comment]
Thanks for the quick responses!

> understand the state of commands for visually impaired users and to make the UI predictable

With the toolbar items having `tabIndex="-1"` aren't these values not navigable by standard keyboard? A screen-reader user would experience a "dimmed button" regardless of visual state. 

<img width="1293" alt="Screen Shot 2021-01-19 at 10 41 11 AM" src="https://user-images.githubusercontent.com/4030377/105079107-cf2be080-5a43-11eb-89ef-4bfdb6ee7f23.png">

But, we're mostly concerned with the visual focus state as @magda-chrzescian brought up. [Specifically these styles](https://github.com/ckeditor/ckeditor5/blob/f00933d7daa8a611f876d46b18bdb7d1854a6a1e/packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/button/button.css#L96-L99). There is a mention of https://github.com/ckeditor/ckeditor5-theme-lark/issues/70, but I think it may be unrelated.

Not applying a border/outline on disabled active/focus would be our preferred path forward, but if it's not possible we can override these values locally. Thanks again for the help!

**Comment by mlewand** [comment]
> With the toolbar items having `tabIndex="-1"` aren't these values not navigable by standard keyboard?

They will. We have custom keyboard handling where you can get into a toolbar with `alt+f10`. Also one can use screen reader's navigation tools to get straight into buttons.

But since you're concerned only about the visual aspect, let's focus on that.

> Not applying a border/outline on disabled active/focus would be our preferred path forward

By hiding this information we'd cause a confusion for people that focused a disabled button, moved their attention away and got back to the editor. Now without information where the focus is they're lost. Imagine you press tab to figure out where you are, but there are 2 more disabled options.

This is most relevant for keyboard-focused users. As users oriented on pointer device (mouse, touch screen) will not be that affected as these will probably intuitively force the focus into a known place by clicking/pressing desired part.

**Comment by austingreendev** [comment]
Oh, I had no idea the `alt+f10` functionality existed! This all makes more sense then.

If we need to modify the disabled active/hover styling we can handle that within our theme and CSS customizations. Going to close for now. Thanks for the help!
