### ISSUE TITLE
Turn cloud-services-core into a soft requirement

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8811]
## Provide a description of the task

Right now it's part of the DLL. However, it's a bit problematic because it's not a commonly used package.

Some of my thoughts:

> - We need to turn this into a soft requirement.
> - We considered having two DLLs (the base one and a richer, collab-ready one with more packages included), but the fact that packages from DLL must be imported via `ckeditor5` is a deal breaker because that'd mean that in the source files we would need to change imports from `cloud-services-core` to `ckeditor5`-based. This would in turn means that such packages need to be added to `ckeditor5`. While this is more or less fine for `cloud-services-core` which is part of the OSS part, this strategy with having two DLLs would work best if we could use this for commercial packages.
> - Also, if we'd want to use this collab-ready DLL for solving the problem with comments editor using e.g. basic styles, we'd need to also add basic-styles to the DLL (and hence `ckeditor5`. Same for the editor class. That would make it even more messy.
> - Anyway, this would be confusing too. It gets more complex the longer we think about this.
> - It seems that soft requirements, and perhaps some tricks to make them nice to use, is our only options. Soft requirement means a "dynamic requirement" and it's a bit like in the old RPM days when you knew you need to load some lib but the system would not install it automatically for you.

In order to turn it into a soft requirement of other packages:

* We need to check which things from this packages are imported in other packages.
* These things need to be somehow moved to the plugin(s) to make them available to other plugins.
* Code that was directly importing these things previously needs to be updated to use these things via the plugins. These plugins need to be added as soft requirements of code that consumes them.

**Comment by Reinmar** [comment]
Fortunately, there are just a few imports:

![image](https://user-images.githubusercontent.com/156149/104290641-e0607480-54ba-11eb-8c0d-b8045eedb4be.png)

![image](https://user-images.githubusercontent.com/156149/104290686-eeae9080-54ba-11eb-9eb5-3d9d693ac518.png)

However, a package that is much more complex to handle:

![image](https://user-images.githubusercontent.com/156149/104290823-1998e480-54bb-11eb-8b4c-8addf5a0bb1a.png)

But this package is only used in CF so we can tackle it later.

**Comment by Reinmar** [comment]
Oops. I confused cloud-services-core and cloud-services. We'll need to review once again how both packages are used.

**Comment by pomek** [comment]
While working on the issue, I've noticed that we have an editor that adds to its built-in plugin `CloudServices` plugins (which now requires `CloudServicesCore` as a soft requirement). 

It meant that I had to add the new plugin (`CloudServicesCore` exposed by the `@ckeditor/ckeditor-cloud-services-core` package) to the editor as well.

After that, some tests of the editor stopped passing. I wasn't able to mock the services.

I was thinking about how to resolve the issue and together with @ma2ciek, we figured out an idea for introducing an option for replacing built-in plugins.

Thanks to that, we can replace a built-in plugin with a custom mock. There are some limitations that could be improved in the future but do not interfere with the current ticket:

1. A plugin for replacing must be a class and must have a name (`#pluginName` must return a string).
2. Both plugins ("mock" and the original) cannot have dependencies.
3. Plugin that should be replaced must be loaded to the editor. You cannot replace a plugin that will not be loaded.

**Comment by ma2ciek** [comment]
:point\_up: It would be quite cool if we would be able to replace plugins with dependencies as well, as it should allow making some major customizations deep in the architecture.

**Comment by pomek** [comment]
While working on the issue, we figured out that we don't need the package at all. It can be merged into the `@ckeditor/ckeditor5-cloud-services` package.

Notes from our internal meeting:

- ckeditor-cloud-services-core
    - We can remove this package from GH.
    - We need to release a new empty major version of this package and use `npm deprecate` to make sure people are warned when they try to upgrade to this package.
    - The use case is that if a project is using 25.0.0 and use `ncu` to upgrade all packages, they should be warned when they try to upgrade to `ckeditor-cloud-services-core` in version 26.0.0. If we wouldn't release 26.0.0, they would have all packages updated (by ncu) except `cloud-services-core` and wouldn't learn that it got deprecated.
- `CloudServicesCore` should be moved to `ckeditor5-cloud-services` and become a dependency (hard, not soft) of the `CloudServices` plugin.
- The `Token`, `UploadGateway` should be moved too and should be available if someone needs to import them directly.
- Let's keep working on the current branch so we can easily diff with `master` to see if we didn't leave some unnecessary changes (e.g. `CloudServicesCore` in some places).
