### ISSUE TITLE
Can not set bullets to right side if text alignment is right

### ISSUE THREAD

**Issue by MuhammadAsadUllah821** [ckeditor/ckeditor5#8813]
I am unable to set bullets or numbered list on right side when text alignment is right 
![image](https://user-images.githubusercontent.com/77320078/104316726-5504d480-54f6-11eb-954a-484cf086f96c.png)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Did you check the documentation on [setting the UI language](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html)?
