### ISSUE TITLE
Can't use custom build

### ISSUE THREAD

**Issue by LittleToni** [ckeditor/ckeditor5#8815]
## 📝 Provide detailed reproduction steps (if any)

1. Generate Custom Editor Build based on Decoupled Document Build.
2. For simplicity use online Builder: https://ckeditor.com/ckeditor-5/online-builder/ (choose List + Indent Plugin)
3. Run `npm install`
4. Run `npm run build`
5. Open /sample/index.html in Browser

### ✔️ Expected result

Editor is rendered successfull

### ❌ Actual result

No Editor and no Toolbar is rendered.
Console: ckeditorerror.js:64 Uncaught CKEditorError: ckeditor-duplicated-modules

## 📃 Other details

* Browser: Chrome
* OS: Linux

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I just checked it with the steps you provided and could not reproduce the error. Are you sure you didn't change anything else in the config?

**Comment by LittleToni** [comment]
I didn't change anything.

If I change this script loaded in the example is works:

`<script src="../build/ckeditor.js"></script>`

to

`<script src="https://cdn.ckeditor.com/ckeditor5/24.0.0/decoupled-document/ckeditor.js"></script>`

**Comment by FilipTokarski** [comment]
Could you share your editor configuration and the contents `package.json`?

**Comment by LittleToni** [comment]
**package.json**

```
{
  "name": "ckeditor5-custom-build",
  "author": "CKSource",
  "description": "A custom CKEditor 5 build made by the CKEditor 5 online builder.",
  "version": "0.0.1",
  "license": "SEE LICENSE IN LICENSE.md",
  "private": true,
  "devDependencies": {
    "@ckeditor/ckeditor5-dev-utils": "^23.6.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^23.6.1",
    "@ckeditor/ckeditor5-editor-decoupled": "^24.0.0",
    "@ckeditor/ckeditor5-essentials": "^24.0.0",
    "@ckeditor/ckeditor5-indent": "^24.0.0",
    "@ckeditor/ckeditor5-list": "^24.0.0",
    "@ckeditor/ckeditor5-paragraph": "^24.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^24.0.0",
    "css-loader": "^5.0.1",
    "postcss": "^8.2.1",
    "postcss-loader": "^4.1.0",
    "raw-loader": "^4.0.2",
    "style-loader": "^2.0.0",
    "terser-webpack-plugin": "^4.2.3",
    "webpack": "^4.44.2",
    "webpack-cli": "^4.2.0"
  },
  "scripts": {
    "build": "webpack --mode production"
  }
}
```

**ckeditor.js**

```
/**
 * @license Copyright (c) 2014-2021, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */
import DecoupledDocumentEditor from '@ckeditor/ckeditor5-editor-decoupled/src/decouplededitor.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
import List from '@ckeditor/ckeditor5-list/src/list.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';

class Editor extends DecoupledDocumentEditor {}

// Plugins to include in the build.
Editor.builtinPlugins = [
	Essentials,
	Indent,
	List,
	Paragraph
];

export default Editor;
```

**Comment by FilipTokarski** [comment]
Even with literally the same config I still cannot reproduce this. Maybe it's some cache issue on your side?  
You could try removing `node_modules` and `package-lock.json` and then reinstall and rebuild everything + hard reloading the website.

**Comment by LittleToni** [comment]
It seems to be a problem with PhpStorm. If i run the npm command in linux bash everthing is fine. If i run it in PhpStorm the error occurs.

**Comment by rajesh-smartwebtech** [comment]
@LittleToni 
Can we create runtime in react this code ? 
`class Editor extends DecoupledDocumentEditor {}
`

becuase of i unable to load other plugins in react with following code 
`
import { CKEditor } from '@ckeditor/ckeditor5-react';
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';

import Code from '@ckeditor/ckeditor5-basic-styles/src/code'; //after this line getting error 
` 


all times getting folowing error
`
version.js:144 Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at ./node_modules/@ckeditor/ckeditor5-utils/src/version.js (version.js:144:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js (elementreplacer.js:12:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js (objecttomap.js:25:1)
    at options.factory (react refresh:6:1)
`

Thank you
