### ISSUE TITLE
Add GoogleFont

### ISSUE THREAD

**Issue by antoine5600** [ckeditor/ckeditor5#8816]
Hello,

I want to add some Google Font to the CkEditor5 in my nodeJS project. I read the documentation from [https://ckeditor.com/docs/ckeditor5/latest/features/font.html#accepting-all-font-names](url) but I don't understand everything. I don't know where did I need to add the font link like "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,900&display=swap".

I already look at the issue #6674, but I don't understand the answer,  sorry.

If someone can help me :)

Thanks,

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. First you need to have Font/FontFamily plugin [installed, imported and added to the toolbar](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#installation).
  
Then, in the `html` file where you use the editor, you need to include `<link>` tag with the font styles, [like in this example](https://developers.google.com/fonts/docs/getting_started):  
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,900&display=swap">
```   
Now following [font configuration docs](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-family-feature), add your chosen font in editor configuration:
```js
...
fontFamily: {
    options: [
            ...
            'Roboto, sans-serif'
            ...
        ]
},
...
```
You will then be able to choose the font in the font family dropdown:  
![0_font1](https://user-images.githubusercontent.com/34380544/104338343-b2008a80-54f6-11eb-9856-bfe69b4d76a5.gif)

**Comment by antoine5600** [comment]
I had this in my code :
`<style type="text/css">@import url(https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap);</style>`
 And this is what I have in fontfamily.js : 
 ```
const fontFamilyConfig = {
 			options: [
 				'default',
 			'Courier New, Courier, monospace',
 				'Georgia, serif',
 				'Lucida Sans Unicode, Lucida Grande, sans-serif',
 				'Tahoma, Geneva, sans-serif',
 				'Times New Roman, Times, serif',
 				'Trebuchet MS, Helvetica, sans-serif',
				 'Verdana, Geneva, sans-serif',
				 'Roboto, sans-serif'
 			],
			supportAllValues: true
 		};
```

But with this, I don't have the line 'Roboto' in the drop down list.
