### ISSUE TITLE
What's the purpose of #editableElement in *UIView classes?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#882]
So far, all `*UIView` classes provide the `editableElement` getter, e.g. the `ClassicEditorUIView` https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_editor-classic_classiceditoruiview-ClassicEditorUIView.html#member-editableElement.

It is then used in the main editor class to attach the DOM root https://github.com/ckeditor/ckeditor5-editor-classic/blob/d46af9fe4627da3f2f0b29349b1cbdabdf550637/src/classiceditor.js#L147

All `*UIView` classes define the `editableElement` in the same way

```js
/**
 * @inheritDoc
 */
get editableElement() {
	return this.editable.element;
}
```

but the truth is, the documentation points nowhere (it's empty) because it's not a part of `EditorUIView` or any interface that any `*UIView` could possibly use (there's no such interface).

The only reason I see to keep this getter is the separation of the editor class and the view internals (which are public anyway, so what's the point?). If so, we need to document this thing as an interface.

I'm for removing this thing or making it a part of a (really tiny) interface. 

Or am I totally missing the point of it?

cc @Reinmar @oskarwrobel

**Comment by Reinmar** [comment]
Why isn't it documented in `EditorUIView`?

And the point of this property is to not rely on `editor.ui.editable.element` which may be an element which somehow wraps the editable. That was first introduced when we still considered using `iframe`s one day. Right now, I have no idea whether we'll do that, but it may happen.

However, I'm not saying that it can't be developed differently. A specific editor class (which now uses the `editableElement` interface, theoretically knows what kind of editable it uses so perhaps it could access it directly. Can plugins know that too? Those which are editing-oriented will access this element through the engine view, so the question is what about UI-oriented plugins?

**Comment by oleq** [comment]
> And the point of this property is to not rely on editor.ui.editable.element which may be an element which somehow wraps the editable. That was first introduced when we still considered using iframes one day. Right now, I have no idea whether we'll do that, but it may happen.

That's a good point!

> A specific editor class (which now uses the editableElement interface, theoretically knows what kind of editable it uses so perhaps it could access it directly.

Since it is clear that we need it, let's just use it everywhere to avoid confusion.

> Can plugins know that too? Those which are editing-oriented will access this element through the engine view, so the question is what about UI-oriented plugins?

They should use `editor.ui.view#editableElement` for the iframe-case reason.

Long story short, let's document it ;-)

**Comment by Reinmar** [comment]
When discussing https://github.com/ckeditor/ckeditor5/issues/1445 I realised that `EditorUIView#editableElement` is, in fact, a mistake. I didn't notice previously that you mention the `EditorUIView` classes. I was thinking about `EditableUIView` where this property belongs. So, I'm closing this ticket (cause it has some confusing content) and let's remove it once we'll agree what to do in #1445.
