### ISSUE TITLE
Not able to use the paste from office even on the example page

### ISSUE THREAD

**Issue by debubiswas051171** [ckeditor/ckeditor5#8820]
I created a build with all options including the "paste from office". But after browsing to the example page "https://[myhost]/ckeditor5/sample/index.html":
1- I notice the paste from office is not maintaining the formatting as in the word document (in the attached word document).
2- I see a console error "widget-toolbar-no-items" and not sure if this is the culprit.
![error](https://user-images.githubusercontent.com/12814721/104349341-cf4e4c80-5528-11eb-9369-0b6b2c2a0b43.jpg)
[CKEditor5.PFO.Sample.Recognition_of_Achievement (1).docx](https://github.com/ckeditor/ckeditor5/files/5803749/CKEditor5.PFO.Sample.Recognition_of_Achievement.1.docx)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It looks like you are pasting plain text. I cannot reproduce this when pasting normally, so `paste from office` plugin works fine here. Only when I use `shift + ctrl + v` the content gets stripped of styling. So please make sure you are pasting correctly and that you didn't modify the configuration before using the editor.  
If that does not help, I'll need some more information on how to reproduce this problem ( precise steps, editor configuration, package.json, etc. )

**Comment by debubiswas051171** [comment]
You are right. It was a mistake on my part. All good now. Thanks.

Debabrata Biswas

[XC_Logo_Dark_XXS]

+91-9923822753 | xcentium.com<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M2r0vW2BV--K7fKkxvW2BgSpx56dFx5f6zpbDb02?te=W3R5hFj4cm2zwW3ZWVWB45TRgWW3K2B1R3FdZ9VW4cR5CP3Fbt5SW4hLywD3yTyZzW4fM4GS1LGpD_W1JJdSh41YyJmW3_qTry3_r9yNW2dW6lf1DBND1W32kS8Z3bzNHvW47GnQM4p8vdtW3F0p3-4phdjbW41D0ws3_L21WW34mmqd34yLs0W2CxfJc47lkxKW2CLvZp3P25XRW1_9Qx_34qG5BW3H0fNW1XnFSTW2TxrWp3XGL3rW2YgmC32KyGx5W3_B-YH3N-LcvW3vlNP54csz-XW3VLk062Rv8bMW4hqVpS4pD3gHW1D62qf45SvrL0&si=5669727013175296&pi=e13ca66a-6127-4e14-8815-fef8357a3050>
debabrata.biswas@xcentium.com<mailto:debabrata.biswas@xcentium.com>
2 Venture, Suite #340
Irvine, CA 92618

XCentium awarded 10 Sitecore MVPs for 2020<https://xcentium.com/partners/sitecore/xcentium-awarded-10-sitecore-mvps-for-2020>

[LN]<https://www.linkedin.com/company/xcentium>   [Twitter] <https://twitter.com/XCentium>    [Facebook] <https://www.facebook.com/XCentium>
NOTICE:  The information contained in this electronic mail transmission is intended for the use of the named individual or entity to which it is addressed and may contain information that is privileged or otherwise confidential. It is not intended for transmission to, or receipt by, any individual or entity other than the named addressee. If you have received this electronic transmission in error, please delete it without copying or forwarding it, and notify the sender of the error.
