### ISSUE TITLE
Fix HTTP#404 warnings in image tests

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8823]
## Provide a description of the task

https://travis-ci.org/github/ckeditor/ckeditor5/builds/754206122

```
$ node --max_old_space_size=8192 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test.js -f image --reporter=dots --production --coverage
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣:    1159 modules
ℹ ｢wdm｣: Compiled successfully.
13 01 2021 00:25:52.538:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
13 01 2021 00:25:52.539:INFO [launcher]: Launching browsers CHROME_TRAVIS_CI with concurrency unlimited
13 01 2021 00:25:52.578:INFO [launcher]: Starting browser Chrome
13 01 2021 00:25:53.473:INFO [Chrome 87.0.4280.141 (Linux x86_64)]: Connected on socket jPbVlWj95PPGcJgMAAAA with id 44540376
...................13 01 2021 00:25:55.743:WARN [web-server]: 404: /example.com/image.png
.13 01 2021 00:25:55.812:WARN [web-server]: 404: /www.example.com/image.png
............................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
.....................................
Chrome 87.0.4280.141 (Linux x86_64): Executed 517 of 517 SUCCESS (14.725 secs / 3.912 secs)
```

**Comment by pomek** [comment]
Most probably, it will be enough to replace URLs to `example.com` with something that exists, e.g., https://via.placeholder.com/350x150.png.

**Comment by przemyslaw-zan** [comment]
The first two cases for `supportedURLs` are the culprits here. Either they would have to be removed from the test and no longer deemed acceptable, or `autoimage.js` would have to guess whether or not they are local path or a URL, as they could be either, without the `https://`.

![](https://user-images.githubusercontent.com/69513154/121485483-8237af00-c9d0-11eb-8b97-a875a7812f94.png)

**Comment by pomek** [comment]
I agree that pasted URLs without the specified protocol should be _somehow_ adjusted/modified.

We have two options:
- do not accept URLs if the protocol is missing (requires RegExp corrections),
- add the protocol (`window.location.protocol`),
- leave the current implementation as it is and focus on hiding warnings.

As this issue was reported about a half year ago, I'd say that the first and the second points aren't a problem as nobody reported even a single issue.

So, let's focus on the dev-ops side of this task.

In the Karma's configuration, we can create ["an alias" (proxy)](http://karma-runner.github.io/6.3/config/configuration-file.html#proxies) for the invalid URLs.

`example.com/image.png` and `www.example.com/image.png` could load an image from the `@ckeditor/ckeditor5-utils` package. We already support it for `/assets/*` URLs. See: https://github.com/ckeditor/ckeditor5-dev/blob/66299f603b3c69450678306c5963b618ff20493a/packages/ckeditor5-dev-tests/lib/utils/automated-tests/getkarmaconfig.js#L44-L47.
