### ISSUE TITLE
Unable to select horizontal line and page break when no other widget plugins are installed

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#8825]
### Horizontal line

https://user-images.githubusercontent.com/1112966/104444480-263f3a80-5598-11eb-8a5a-470d75e48bd9.mov

1. Configure online build with horizontal line plugin.
2. Open `sample.html`.
3. Add a horizontal line and try to select it

### Page break

https://user-images.githubusercontent.com/1112966/104451924-8935cf00-55a2-11eb-8912-851b28caa3ff.mov

1. Configure online build with page break plugin.
2. Open `sample.html`.
3. Add a page break and try to select it

### ✔️ Expected result

Horizontal line/page break is selected.

### ❌ Actual result

Unable to select horizontal line/page break.

## 📃 Other details

* Installed CKEditor plugins: HorizontalLine/PageBreak.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
What about Page break? Looks like it has the same problem.

**Comment by maxbarnas** [comment]
> What about Page break? Looks like it has the same problem. Let's handle both of them here.

Somehow I did't register the Page break at first. Thanks for pointing it out. Both examples of the issue, as well as fixes are provided now.
