### ISSUE TITLE
Unable to click the link when inserting it through the hyperlink toolbar or copy and paste through Angular CkEditor

### ISSUE THREAD

**Issue by xinwanc** [ckeditor/ckeditor5#8826]
## 📝 Provide detailed reproduction steps (if any)

1. Click link toolbar, insert the link
2. Click the link to navigate
3. Another way is copy and paste the link and click

### ✔️ Expected result
Able to navigate to the link

### ❌ Actual result
No response

## 📃 Other details

* Browser: Google Chrome
* OS: Windows
* First affected CKEditor version: CkEditor5
* Installed CKEditor plugins: 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by xinwanc** [comment]
![image](https://user-images.githubusercontent.com/38121289/104446500-843e4300-55d5-11eb-88ef-96b257f4f7ac.png)
these are the configuration settings for ckeditor

**Comment by xinwanc** [comment]
![image](https://user-images.githubusercontent.com/38121289/104446665-bf407680-55d5-11eb-9526-b8f64c52d499.png)
when i click the hyperlink toolbar and insert the url after providing first url, it will display duplicated toolbar

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. Could you provide more details about your app ( ckeditor component code, configuration, steps to reproduce, etc. )? It seems like there might be something wrong in your implementation ( especially duplicated toolbar ), as the link feature is working fine elsewhere.
