### ISSUE TITLE
[Safari] Second bold inside paragraph moves selection to the beginning of it

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#883]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`v1.0.0-alpha.2`

## 📋 Steps to reproduce

1. Go to https://ckeditor5.github.io.
2. Replace existing content with simple `<p>Paragraph</p>`.
3. Place selection like `<p>Par^agraph</p>`.
4. Apply bold (button or `Ctrl/Cmd + b`).
5. Type one character.
3. Change selection to e.g. `<p>Paragra^ph</p>`.
4. Apply bold (button or `Ctrl/Cmd + b`).
5. Type one character.

## ✅ Expected result
Bold character is inserted.

## ❎ Actual result
Instead of character being inserted, caret moves to paragraph beginning.

![mar-08-2018 16-30-04](https://user-images.githubusercontent.com/1061942/37159796-feb31182-22ee-11e8-9db7-88a5380c198a.gif)

## 📃 Other details that might be useful

`Safari Version 11.0.3 (11604.5.6.1.1)`

**Comment by f1ames** [comment]
And the console error:
![image](https://user-images.githubusercontent.com/1061942/37160321-39b27aba-22f0-11e8-908a-b75dc20d2b36.png)

**Comment by Mgsy** [comment]
@f1ames, I'm not able to reproduce it. I've checked it on https://ckeditor5.github.io and the latest master and it works fine for me.

![bug_cke5](https://user-images.githubusercontent.com/20988892/37195387-e91ec724-2372-11e8-8be2-db7dbe28f745.gif)

My Safari version - `Version 11.0.3 (13604.5.6)`.

**Comment by f1ames** [comment]
Maybe it's the Safari version difference... I noticed it is not reproducible always but in most cases it happens. Below is a gif showing how I reproduce it from very beginning (from opening/refreshing the https://ckeditor5.github.io/) and navigating only via keyboard (apart from focusing editor - so applying bold via `Cmd + b`). Could you recheck if exact same steps give you different result?

![mar-09-2018 16-28-22](https://user-images.githubusercontent.com/1061942/37214972-f8c6db50-23b6-11e8-876c-6a6989ad7974.gif)

**Comment by Mgsy** [comment]
Interesting, I'm still not able to reproduce it. I've checked it in Safari 11.0.2, so the browser version probably doesn't matter in this case.

![bug_cke5](https://user-images.githubusercontent.com/20988892/37272379-b76a67ae-25d6-11e8-9927-85436a011673.gif)

**Comment by f1ames** [comment]
@Mgsy maybe we could ask another person to try reproduce it on their system. And if it will not be reproducible just close it as `invalid`. I'm really not sure why it behaves as shown above on my machine 🤔

**Comment by Mgsy** [comment]
>@Mgsy maybe we could ask another person to try reproduce it on their system.

Yeah, I guess it would be the best way to verify it :D 

@oleq, @Reinmar, could you take a look at it?

**Comment by Reinmar** [comment]
WFM

Version 11.0.3 (13604.5.6)

**Comment by f1ames** [comment]
Closing the issue then.

**Comment by f1ames** [comment]
Just a note, I have updated my OS (from El Capitan to High Sierra) so my Safari version is now

_11.0.3 (**13**604.5.6)_

instead of

_11.0.3 (**11**604.5.6.1.1)_

and can't reproduce it any longer. It seems even though both Safaris were `11.0.3` versions, it worked slightly different on both OSes.
