### ISSUE TITLE
Uploading .png images with transparent background

### ISSUE THREAD

**Issue by rturtu** [ckeditor/ckeditor5#8830]
## 📝 Provide detailed reproduction steps (if any)

1. Drag and drop a .png image with transparent background
2. The image appears in the editor with black background instead of transparent

### ✔️ Expected result

The image should be displayed with transparent background
![280px-PNG_transparency_demonstration_1](https://user-images.githubusercontent.com/20361045/104474935-2e629e80-55c7-11eb-86e2-055760bb5ce9.png)
(sample image from wikipedia)

### ❌ Actual result

The image is changed, all the transparent pixels are now black.
![image](https://user-images.githubusercontent.com/20361045/104474972-3a4e6080-55c7-11eb-8333-5896fc2370fa.png)

## 📃 Other details

* Browser: firefox 83.0
* OS: ubuntu 20.0
* First affected CKEditor version: ckeditor5 2.1.0
* Installed CKEditor plugins: 'Essentials', 'Bold', 'Italic', 'Link', 'List', 'Image',  'EasyImage', 'MediaEmbed', 'Table', 'TableToolbar', 'PasteFromOffice',

Is there a way to fix this or at least change the default color from black to white?

**Comment by Mgsy** [comment]
Hi, thanks for the report. I'm not able to reproduce this issue - your image displays with a transparent background.

![](https://user-images.githubusercontent.com/20988892/104895015-a806dd80-5975-11eb-81ba-b61efd90a1b9.png)

Can you reproduce it [in our demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)?

**Comment by rturtu** [comment]
It does not reproduce in your demo. It means that the problem is on our side, thanks for help
