### ISSUE TITLE
Create a state machine graph (type and alignment of the images).

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#8831]
The graph should cover the changes of image types (inline/block) and alignment caused by:
* interactions with the editor interface, 
* loading the data saved in CKE4,
* pasting/dragging the data inside the editor,

if we decide to follow the proposal below:
- 3 display modes as in the [comment](https://github.com/ckeditor/ckeditor5/issues/8657#issuecomment-757737677)
    - in paragraph
    - in line
    - between paragraphs
    - **Important:** modes do not reflect DOM/Model/View, only the way the content is rendered by the browser (visually).
- available alignments available only when "in paragraph" or "between paragraphs"
    - left
    - right
    - center
    - full-width
- changing the alignment from left to right or vice-versa does NOT change the type of a widget
    - we cannot change the type of the widget inline widget would be in a paragraph and block before/after and this will break CSS (`+, :first-child`, etc.)

**Comment by magda-chrzescian** [comment]
The tables below don't cover:
* creating a new image,
* pasting an external content,
* any of the behavior if only an inline or block option is allowed.

I think this is enough at this point to decide if the proposal defined in the https://github.com/ckeditor/ckeditor5/issues/8657#issuecomment-757737677 can properly handle the v4 compatibility and inline <-> block conversions issues.

![image](https://user-images.githubusercontent.com/14334820/104597763-054d1700-5676-11eb-9fd7-53b30e0500d8.png)

![image](https://user-images.githubusercontent.com/14334820/104597820-19911400-5676-11eb-9ade-3d0b984ef9a9.png)

![image](https://user-images.githubusercontent.com/14334820/104597896-32012e80-5676-11eb-84b1-e5e5f7a3325d.png)

**Comment by pkwasnik** [comment]
To order everything in my head about "interacting with the menu", I've created a table from another perspective. I've divided inline/block image into all possible arrangements: left/center/right/none and float or not to float. Then I've added the buttons that need to be clicked to achieve that arrangement (if I've understood it right ;) ).

![](https://user-images.githubusercontent.com/16957311/104643672-08172e80-56ad-11eb-8367-b1b8ae7549e1.png)

It could be good to start by analyzing if we need to cover any of those "**X**". Also, I see that currently there is no way to decide by the user if left/right should use inline or block. Previously I was for the only block left/right solution. But after playing a bit with it, I see that the difference in behavior is big enough that it will be useful if left/right alignment could be done both by inline or block.

**Comment by magda-chrzescian** [comment]
The updated diagrams below cover the behavior of the images in the context of the UI presented in [this comment](https://github.com/ckeditor/ckeditor5/issues/8657#issuecomment-762136899).
* It assumes the configuration that enables both, inline and block images.
* The option for inserting images is set to "smart" (the decision about the image type is made based on the current caret position).
* It doesn't cover the following cases:
  * inline/block option for inserting images - which is probably similar to the case where inline/block images are disabled,
  * inserting images into the blocks other than paragraph (</h1/li/td/blockquote>),
  * inserting the images next to another block images.

### To consider:
* Do we want to be smart or consistent regarding the alignment of the images? Should it be configurable? What happens if the user inserts a new image at the beginning of the line inside the paragraph? The options are:
  * The image is inline with no alignment (in the line)
  * The image is inline with left alignment (wrapped with text), because the user inserted this at the beginning of the line. This may be problematic if someone inserts a lot of emojis or uses the images as a bullet list.
* What happens when the user drops the block image aligned to the center at the beginning of the line in the paragraph?
  * The image is aligned to the left.
  * The image gets no alignment and is rendered in the line of text.
* What happens when the user converts the inline image aligned to the left into the block image? (This one should be taken into consideration while designing the UI for the alignment and resolved after it's done.) 
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/eed448ec-ea7c-47ca-8659-e9c0054340cd)
  * The image is still aligned to the left but is block type (a little inconsistency with the icon, which shows the image not wrapped with text. If the user wanted to keep the alignment and convert to block to add the caption, he should have clicked the caption icon).
  * The image is converted to block and aligned to the center as it is shown on the icon (this stands in the opposition to the rule of making as few changes as possible).

![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/0f7119c0-d361-458f-8bfe-ac797de111c3)
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/b9697cd0-c72f-492d-9780-66c226175a3d)
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/abb99664-048e-4a66-954c-4915034ed099)

### Interacting with the menu:
#### The image displayed the line of text:
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/7acccc6f-b901-405d-960f-66b6ec7de7f8)
#### The inline image wrapped with text:
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/230383a5-19a9-474a-a874-487845faba73)
#### The block image aligned to the center/full width:
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/0db2ec79-59b3-4420-84ec-0bf362bb7197)
#### The block image aligned to the left/right:
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/2629ff15-78a5-4516-a2f8-58590c70d585)

**Comment by magda-chrzescian** [comment]
@pkwasnik I agree that maybe we should talk about the full-width button. I'm also not sure if we need it and if it is even an alignment button.

> The solution that we've been talking on the beginning with only two state buttons seems for me simpler, still covering the same arrangements and giving users the possibility to choose between inline/block alignment:

It surely does cover all of the arrangements we need but in my opinion, it doesn't show a clear path for the user to achieve certain layouts. I probably would be confused if I wanted to have an image with wrapped text, but there was no button showing this layout.

**Comment by oleq** [comment]
I went through the tables and here's my feedback. I think it will simplify things a bit in MVP1 and we'll have a bunch of follow-ups with UX enhancements for MVP2:

## Loading data from CKE4

![](https://user-images.githubusercontent.com/1099479/105040081-b500fb00-5a61-11eb-8d33-3e058cd96a71.png)

Just wanted to make it clear that "full width" alignment is simply: "the first configured alignment" in this case. We expect developers to configure their default alignment and this is the one. In the default configuration, it is "full width" but it could be something else.

## Dragging/pasting

![](https://user-images.githubusercontent.com/1099479/105040096-b9c5af00-5a61-11eb-8099-6d86b0d49d51.png)

*   Section 1. (Alignment): Although I think these could make sense, this is beyond the scope of MVP1. These are clear UX enhancements we can apply iteratively on top of MVP1.
    *   (Position) Another thing worth mentioning here is that discovery of the line (not block) boundaries is tricky (etc. "at the end of the line"). Although we use the similar thing in the table feature for moving the caret around the cells using the keyboard, this is not widespread across the project and, again, beyond MVP1.
*   Section 2. (Type) I'm OK with changing the type of image from block to inline if there was **no** caption in the first place.
    *   (Type) If there was a caption, I think we should respect that and treat the image as a block, which may break the paragraph but this is OK.
*   Section 4.: (Type) We're OK to go inline if there was no caption (see Section 2.).
*   Section 3 and 5. (Alignment): Here again the same concern as Section 1.: discovering user intention in cases such as beginning/end of the line/block is beyond MVP1. A clear follow-up.

## Inserting new image

![](https://user-images.githubusercontent.com/1099479/105040104-bd593600-5a61-11eb-8652-4ddb8c24cc73.png)

Same as with loading from CKE4, "full width" means "the first configured alignment.

**Comment by oleq** [comment]
There's another concern regarding discovering the alignment of the image based on its position at the beginning/end of the line/block: there could be editor configurations that don't have styles that represent left/right alignments (despite our defaults working like this) and that could be a real blocker. On top of that, we'd need another flag similar to `isDefault` in style definitions to mark certain styles as associated with left/right positions.

**Comment by magda-chrzescian** [comment]
Based on @oleq's feedback and our earlier conversation I updated the tables and diagrams taking into account the following changes:
* Aligning based on the image position is beyond MVP1, so we stick with the default position while the image type conversion and the source image position while /pasting/dropping. We can also use the 'none' position for the inline images since it is actually the lack of any alignment, so it is always available.
* We decided that the caption shouldn't decide on the behavior of the image while pasting/dropping and we have to handle the disappearing caption anyway, so section 2 of @oleq's comment stays as it was.
* I added the information that while converting to inline, the image should be wrapped with <p> (allows us to avoid potential typing issues)

---
> there could be editor configurations that don't have styles that represent left/right alignments

In order to load the images from CKE4 properly, we have to make an assumption that the client will be aware of this limitation.

----
![image](https://user-images.githubusercontent.com/14334820/105064808-7a0cc080-5a7d-11eb-82d5-f5433fee5a1e.png)
![image](https://user-images.githubusercontent.com/14334820/105064873-8b55cd00-5a7d-11eb-89b8-a19fb54c766e.png)
![image](https://user-images.githubusercontent.com/14334820/105064898-94469e80-5a7d-11eb-8295-65b729223624.png)

## Interacting with the menu:
![Inline images - Page 1](https://user-images.githubusercontent.com/14334820/105065330-08814200-5a7e-11eb-81ea-0bce344acd9e.png)
![Inline images - Page 1 (1)](https://user-images.githubusercontent.com/14334820/105065339-0ae39c00-5a7e-11eb-9777-cf2954bd9785.png)
![Inline images - Page 1 (2)](https://user-images.githubusercontent.com/14334820/105065345-0cad5f80-5a7e-11eb-8777-1b4a6eb825d7.png)
![Inline images - Page 1 (3)](https://user-images.githubusercontent.com/14334820/105065348-0e772300-5a7e-11eb-99eb-746cf0a76030.png)

**Comment by oleq** [comment]
Thanks @magda-chrzescian for an excellent work! I think this concludes the research and should anything new come up, we can track it in the next iteration.

**Comment by magda-chrzescian** [comment]
## This is the alternative diagram to cover the solution described in [this comment](https://github.com/ckeditor/ckeditor5/issues/8657#issuecomment-765210045).

All of the differences and problematic areas are marked with red rectangles.  
  
 

![](https://user-images.githubusercontent.com/14334820/105488598-28994700-5cb2-11eb-937f-a37c9a97c135.png)

![](https://user-images.githubusercontent.com/14334820/105488619-3222af00-5cb2-11eb-9c0f-54773b3c3750.png)

![](https://user-images.githubusercontent.com/14334820/105488643-3b138080-5cb2-11eb-93f5-04dbe07b98e2.png)

![](https://user-images.githubusercontent.com/14334820/105488671-4666ac00-5cb2-11eb-990d-3267d4a1b291.png)
