### ISSUE TITLE
Rendering editor content in another element

### ISSUE THREAD

**Issue by opeyemidy** [ckeditor/ckeditor5#8832]
i'm trying to render the editor contents saved to database in another element retaining the editor styles, i was able to do it successfully for editor contents with this [link](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) but not mathtype plugin contents.

**what i'm expecting**
![Screenshot_2021-01-13 Screenshot from 2021-01-13 20-46-17 png (PNG Image, 1366 × 768 pixels) — Scaled (83%)](https://user-images.githubusercontent.com/47211870/104503179-0a13bb80-55e1-11eb-8c4e-2f92a06bee9e.png)

**what i got**
![Screenshot_2021-01-13 Screenshot from 2021-01-13 20-47-51 png (PNG Image, 1366 × 768 pixels) — Scaled (83%)](https://user-images.githubusercontent.com/47211870/104503565-873f3080-55e1-11eb-954e-86f718192645.png)

how can I fix this please?

**Comment by Mgsy** [comment]
Hi! By default MathType outputs MathML, which currently is [supported in Firefox and Safari](https://caniuse.com/mathml). It should render properly if you'll open your editor e.g. in Firefox. 

However, there are some libraries which allow handling MathML in all browsers, e.g. [MathJax](https://www.mathjax.org/), so you might want to try it and see if it works for you.
