### ISSUE TITLE
Angular 9 ck editor 5 remove html tag from html data and style and allowedContent =true is not working 

### ISSUE THREAD

**Issue by raoshahid799** [ckeditor/ckeditor5#8848]
i am using CK Editor 5 with online custom build,
passing the data with NgModel
Ck edtior 5 remove html tag from data and plus style and other attribute

i am using the following setting in config

```
CkEditorConfig = {
toolbar: {
  items: [...]
  , shouldNotGroupWhenFull: true,
  viewportTopOffset: 60
},

placeholder: 'Type some text',
allowedContent: true,
removeFormatAttributes : '',
}
```
i searched on internet but allowedContent =true is not working

**Comment by raoshahid799** [comment]
when i removed the markdown plugin its fixed

**Comment by AshimKK** [comment]
aaaaaaaa
name
<p> first </>
<div> test div</>

**Comment by meghal** [comment]
htmlSupport:  { allow: [
        {
            name: 'iframe',
			attributes: true,
            classes: true,
            styles: true
        }
	]},
