### ISSUE TITLE
Indented list created by CK Editor loses indentation when get loaded back to CK Editor

### ISSUE THREAD

**Issue by LangQian** [ckeditor/ckeditor5#8850]
## 📝 Provide detailed reproduction steps (if any)

In example editor [here](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html), do the following:

1. Clear the existing text
2. Click "Increase indent" button in the toolbar several times to create some indentation
3. With the current position, create an indented list with the "Bulleted List" button in the toolbar, like the following one:
![image](https://user-images.githubusercontent.com/16005923/104768283-612da380-573b-11eb-9637-79e7d49b6108.png)
4. In the console, type the following to fetch the current data:
`var ckContent = editor.getData();`
5. In the console, type the following to load the above data back into CK Editor:
`editor.setData(ckContent);`

### ✔️ Expected result

The list indentation should be kept.

### ❌ Actual result

The list indentation was lost.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report! We are aware of this issue and it's already reported. You can track it here - #6761.
