### ISSUE TITLE
model.TextProxy#is( '$text' ) should return true

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#8851]
## 📝 Provide a description of the improvement

Title says it all. I think that `TextProxy#is()` should return `true` for `$text` cause sometimes you might not be sure which one you will get and you would need to check both. Note that `TextProxy` tries to mimic `Text` as much as it can.

**Comment by scofalik** [comment]
For example, method from `Schema`:

```
	getDefinition( item ) {
		let itemName;

		if ( typeof item == 'string' ) {
			itemName = item;
		} else if ( item.is && ( item.is( '$text' ) || item.is( '$textProxy' ) ) ) {
			itemName = '$text';
		}
		// Element or module:engine/model/schema~SchemaContextItem.
		else {
			itemName = item.name;
		}

		return this.getDefinitions()[ itemName ];
	}
```

**Comment by Reinmar** [comment]
I don't think this is a good idea. These are not the same things. And have quite different APIs.
