### ISSUE TITLE
When table have cell with long text, the cell styling tool have weird overflow behaviour

### ISSUE THREAD

**Issue by asimkt** [ckeditor/ckeditor5#8853]
## 📝 Provide detailed reproduction steps (if any)

1. Goto https://ckeditor.com/docs/ckeditor5/latest/features/table.html
2. Keep adding a very long text like JSON object. (Added sample at end)
3. See the cell styling popover

### ✔️ Expected result

The popover should have a better UX. Welcoming suggestions

### ❌ Actual result

![image](https://user-images.githubusercontent.com/10784527/104882507-32a50800-5989-11eb-8121-5d657c6841b0.png)

Sample cell data:
```
{"changedByUser":"dev","changeType":"REMOVED","taskName":"Romania","taskId":1,"changedByUser":"dev","changeType":"REMOVED","taskName":"Romania","taskId":1,"changedByUser":"dev","changeType":"REMOVED","taskName":"Romania","taskId":1}
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thanks for the report. It seems that this issue boils down to #5328, so I'm closing it as a duplicate.
