### ISSUE TITLE
Can't select cell when it has only image

### ISSUE THREAD

**Issue by Absolutely17** [ckeditor/ckeditor5#8857]
## 📝 Provide detailed reproduction steps (if any)

1. Create table (2x2, for example)
2. Insert image in first cell
3. Select second cell
4. Try to select first cell

### ✔️ Expected result

The first cell is selected, the toolbar is open

### ❌ Actual result

First cell not selected

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Absolutely17** [comment]
Please tell me how I can fix this on my fork. Or help fix this in the official :)

**Comment by FilipTokarski** [comment]
Hi, it seems like it's the same case as the one already tracked here https://github.com/ckeditor/ckeditor5/issues/8511, so please add any comments there ( and if you already did, please do not open another ticket with the same issue ).
I'm closing this as a duplicate.
