### ISSUE TITLE
Pagination produce duplicate modules error installing with yarn

### ISSUE THREAD

**Issue by chringseng** [ckeditor/ckeditor5#8860]
Installing and including pagination plugin by yarn produce an duplicate modules error with white page.
We found the problem internal in node_modules folder. The pagination is installing @ckeditor/ckeditor5-core, @ckeditor/ckeditor5-ui and @ckeditor/ckeditor5-utils. After removing these modules from the plugin it worked.

It sounds for me, that it only happen if we install with yarn and not with npm, but I'm not sure. For now we duplicated the pagination plugin in our repo and removed the node_modules, but for sure this is no solution for the future.
Sounds for me in general like a not updated repo on yarn's page.

Version informations:
License: Paid production or dev license
Node: 14.15.1
npm: 6.14.8
yarn: 1.22.5
CKEditor: 23.1.0

**Comment by Mgsy** [comment]
Hi! Thanks for the report. The duplicated modules error can occur if CKEditor 5 packages are at different versions. As I can see, you use CKEditor 5 at version 23.1.0, while the latest one is 24.0.0 (and 25.0.0 will be released ~next week). It means when you install an additional plugin, e.g. pagination, it will be installed at the latest version.

There are two ways for fixing it:

*   Update all packages to the latest version (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)).
*   Install the pagination plugin at version 23.1.0.

However, I would recommend updating all packages to make sure that all bug fixes and new feature are available in your editor.

> License: Paid production or dev license

If you're a commercial user, feel free to reach us through our [support channel](https://ckeditor.com/contact/). Our dedicated support team will assist you in solving your problems :)

**Comment by chringseng** [comment]
Hi, I think it was really a version problem. We updated know from 23.1.0 to 24.0.0 and the error is away.
Thank you.

**Comment by chringseng** [comment]
I have to reopen this issue again, because of a other module. We have now the same problem, but not with pagination like before. Now is it the @ckeditor/ckeditor5-real-time-collaboration plugin.

The difference is that the versions are all the newest:

"@ckeditor/ckeditor5-alignment": "^25.0.0",
"@ckeditor/ckeditor5-autosave": "^25.0.0",
"@ckeditor/ckeditor5-basic-styles": "^25.0.0",
"@ckeditor/ckeditor5-block-quote": "^25.0.0",
"@ckeditor/ckeditor5-build-decoupled-document": "^25.0.0",
"@ckeditor/ckeditor5-clipboard": "^25.0.0",
"@ckeditor/ckeditor5-core": "^25.0.0",
"@ckeditor/ckeditor5-dev-utils": "^24.0.2",
"@ckeditor/ckeditor5-dev-webpack-plugin": "^24.0.2",
"@ckeditor/ckeditor5-editor-classic": "^25.0.0",
"@ckeditor/ckeditor5-editor-decoupled": "^25.0.0",
"@ckeditor/ckeditor5-essentials": "^25.0.0",
"@ckeditor/ckeditor5-font": "^25.0.0",
"@ckeditor/ckeditor5-heading": "^25.0.0",
"@ckeditor/ckeditor5-horizontal-line": "^25.0.0",
"@ckeditor/ckeditor5-html-embed": "^25.0.0",
"@ckeditor/ckeditor5-image": "^25.0.0",
"@ckeditor/ckeditor5-indent": "^25.0.0",
"@ckeditor/ckeditor5-link": "^25.0.0",
"@ckeditor/ckeditor5-list": "^25.0.0",
"@ckeditor/ckeditor5-media-embed": "^25.0.0",
"@ckeditor/ckeditor5-mention": "^25.0.0",
"@ckeditor/ckeditor5-page-break": "^25.0.0",
"@ckeditor/ckeditor5-pagination": "^25.0.0",
"@ckeditor/ckeditor5-paragraph": "^25.0.0",
"@ckeditor/ckeditor5-paste-from-office": "^25.0.0",
"@ckeditor/ckeditor5-react": "^3.0.0",
"@ckeditor/ckeditor5-real-time-collaboration": "^24.0.0",
"@ckeditor/ckeditor5-remove-format": "^25.0.0",
"@ckeditor/ckeditor5-special-characters": "^25.0.0",
"@ckeditor/ckeditor5-table": "^25.0.0",
"@ckeditor/ckeditor5-theme-lark": "^25.0.0",
"@ckeditor/ckeditor5-ui": "^25.0.0",
"@ckeditor/ckeditor5-upload": "^25.0.0",
"@ckeditor/ckeditor5-utils": "^25.0.0",
"@ckeditor/ckeditor5-watchdog": "^25.0.0",
"@ckeditor/ckeditor5-widget": "^25.0.0",
"@ckeditor/ckeditor5-word-count": "25.0.0",

I was wondering, because there is no 25.0.0 version for the realtime plugin?!

**Comment by Mgsy** [comment]
@chringseng, the issue occurs because you use `ckeditor5-real-time-collaboration` package at version 24.0.0. Please, update to version [25.0.0](https://www.npmjs.com/package/@ckeditor/ckeditor5-real-time-collaboration) and the issue should be fixed.

**Comment by chringseng** [comment]
Thank you, I saw it

**Comment by smajl** [comment]
@Mgsy Hi, question please, we recently started using `@ckeditor/ckeditor5-pagination` which works on 24.0.0 but then tried to update to 25.0.0 and got the `ckeditor-duplicated-modules` error as well. I am positive that all the plugins are set to 25.0.0 with only exception of `@ckeditor/ckeditor5-dev-utils` which doesn't have the 25.0.0 yet. Could that be the problem? If I remove import of the pagination plugin it all works even with 25.0.0.

**Comment by chringseng** [comment]
@smajl What worked for us:

1. Update all CK-Modules to 25.0.0 in package.json (it's fine if the dev-utils have the version 24.0.2)
2. Remove all npm modules and lock files
3. Install everything from new

This worked for us with yarn and the decoupled editor

**Comment by smajl** [comment]
@chringseng Nuking node_modules and lock file did the trick, thanks.
