### ISSUE TITLE
Improve the dependency checker if packages are not specified in arguments (CLI)

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8861]
After executing the command without additional arguments, it ends without any message:

```
yarn run check-dependencies
yarn run v1.22.10
$ node node_modules/@ckeditor/ckeditor5-dev-tests/bin/check-dependencies.js
✨  Done in 0.81s.
```

But it can be improved in the future, as a follow-up. We have two ways to solve the issue:

1. Exit with an error if packages aren't specified (easy to fix).
2. Check all packages found in the `package/` directory.

I'd go with the latter one.

_Originally posted by @pomek in https://github.com/ckeditor/ckeditor5/pull/8854#discussion_r560053686_

**Comment by psmyrek** [comment]
I'm closing this one, as there is already other task with more improvement ideas: https://github.com/ckeditor/ckeditor5/issues/8862
