### ISSUE TITLE
Decoupled Editor does not render properly with Angular 10

### ISSUE THREAD

**Issue by wilfoderek** [ckeditor/ckeditor5#8868]
# When I try to load CKEditor using DecoupledDocument build, it does not render "the document A4 paper". Instead, it just takes the background and places above the textbox.

### ✔️ Expected result
![expected_editor](https://user-images.githubusercontent.com/1625647/105057780-90962600-5a43-11eb-8bc8-8c1a575f83ab.jpg)

### ❌ Actual result
![actual_mistake](https://user-images.githubusercontent.com/1625647/105058198-f2569000-5a43-11eb-8f6c-a257b27d61bb.jpg)

Steps to reproduce the bug.
**Step 1.  Installation**
 npm install --save @ckeditor/ckeditor5-angular
  npm install --save @ckeditor/ckeditor5-build-decoupled-document

**Step 2. Adding CKEditorModule**
` import { CKEditorModule } from '@ckeditor/ckeditor5-angular';

@NgModule( {
    imports: [
        CKEditorModule,
    ],
} )
`
**Step 3. MyComponente.component.ts**

`
import * as DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
@Component( {
    // .......
} )
export class MyComponent {
    public Editor = DecoupledEditor;

    public onReady( editor ) {
        editor.ui.getEditableElement().parentElement.insertBefore(
            editor.ui.view.toolbar.element,
            editor.ui.getEditableElement()
        );
    }
}

`

**Step 4. MyComponente.component.html**

`
<ckeditor [editor]="Editor" data="<p>Hello, world!</p>" (ready)="onReady($event)"></ckeditor>
`

---
I would appreciate your help with this problem. 👍
Have a great day!
Any examples is welcome. :)

**Comment by FilipTokarski** [comment]
Hi, did you use [styles for Decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html#styles)?

**Comment by wilfoderek** [comment]
> Hi, did you use [styles for Decoupled editor](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html#styles)?

Dear @FilipTokarski  I have tried the style but I don´t know how it connects with ckedtior. this is the way how I call in my angular component:
<ckeditor [editor]="Editor" data="<p>Hello, world!</p>" (ready)="onReady($event)"></ckeditor>

I would be glad if you give me some instructions to get the goal.

**Comment by 3208722208** [comment]
The same is true when I use **' ckeditor 5-build-decomposed-document'** in my **vue2** application. I don't know how to use **styles** on vue components when reading official documents.The following is my related code.

**package.json :**

 "@ckeditor/ckeditor5-build-decoupled-document": "^24.0.0",
 "@ckeditor/ckeditor5-vue2": "^1.0.5",

**Vue Component :**

 <ckeditor
      v-model="editorData"
      :editor="editor"
      :config="editorConfig"
      :disabled="editorDisabled"
      @ready="onEditorReady"
    >
    </ckeditor>

import CKEditor from '@ckeditor/ckeditor5-vue2'
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document'
import '@ckeditor/ckeditor5-build-decoupled-document/build/translations/zh-cn'

 components: {
    ckeditor: CKEditor.component
  },

 data() {
    return {
      editor: DecoupledEditor,
      editorConfig: {
        // The configuration of the editor.
        language: 'zh-cn',
        ...
      }
   }
},
methods: {
    onEditorReady(editor) {
      console.log(editor)
      // Insert the toolbar before the editable area.
      editor.ui.getEditableElement().parentElement.insertBefore(
        editor.ui.view.toolbar.element,
        editor.ui.getEditableElement()
      )
    }
  }

**Comment by wilfoderek** [comment]
I have finally solved the problem with document editor style. I will put the code here to avoid spare time to people with the same problem. @3208722208  this can help you to solve your bug.
In MyComponent.component.ts

```
import { Component, OnInit } from '@angular/core';
import * as DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
export class MyComponentimplements OnInit {
  editor = DecoupledEditor;
  toolbar: any = ['heading', '|', 'bold',
    'italic', 'fontSize', 'fontFamily', 'underline', 'strikethrough', 'alignment',
    'highlight', 'numberedList', 'insertTable',
    'bulletedList', '|', 'indent',
    'outdent', 'undo', 'redo', 'exportPdf', 'exportWord', 'fontBackgroundColor',
    'fontColor'];

heading = {
    options: [
      { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
      { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
      { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
      { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
      { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
      { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
      { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' }
    ]
  };



ngOnInit() {
    DecoupledEditor.create(document.querySelector('.document-editor__editable'), {
      fontSize: { options: [9, 11, 12, 13, 'default', 17, 19, 21] },
      toolbar: this.opciones,
      heading: this.heading,
    }).then(editor => {
      const toolbarContainer = document.querySelector('.document-editor__toolbar');
      toolbarContainer.appendChild(editor.ui.view.toolbar.element);

      this.Editor = editor;
    }).catch(err => {
      console.error(err);
    });
  }

getData() {
    console.log("ckeditor html: ", this.editor.getData());
  }

 setData() {
    let data: any = `<p>Hi everyone!</p>`;
    this.editor.setData(data);
  }
 }
```


### Now in MyComponent.component.html

```
<div class="document-editor">
  <div class="document-editor__toolbar"></div>
  <div class="document-editor__editable-container">
    <div class="document-editor__editable">
    </div>
  </div>
</div>
```

### Style can be found here
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html#styles

**Comment by jesben** [comment]
using ngAfterViewInit instead

```TypeScript
ngAfterViewInit() {
    this.editor.create(document.querySelector('.document-editor__editable'), this.config).then(editor => {
      const toolbarContainer = document.querySelector('.document-editor__toolbar');
      toolbarContainer.appendChild(editor.ui.view.toolbar.element);

      if (this.formControl) {
        editor.setData(this.formControl.value);
      }
      else if (typeof this.data != 'undefined') {
        editor.setData(this.data);
      }

      editor.model.document.on('change', () => {
        const data = editor.getData();

        if (this.formControl) {
          this.formControl.patchValue(data);
        }
        else if (typeof this.data != 'undefined') {
          this.dataChange.emit(data);
        }
      });
    }).catch(err => {
      console.error(err);
    });
  }
```
