### ISSUE TITLE
Remove <figure> tag 

### ISSUE THREAD

**Issue by isuruhera** [ckeditor/ckeditor5#8869]
Is there any way to remove/ disable   `<figure>`  tag which wraps around images /tables ?

**Comment by Reinmar** [comment]
No, there's no simple way to do that. In fact, taken that an image may have a caption, the figure element is quite important there. I'd recommend doing some post-processing on the content – stripping a single element should be easy.

**Comment by rawthriver** [comment]
+1. Bad idea to hardcode figure table wrapper.

**Comment by josephj** [comment]
I am looking into this since the Outlook web mail will replace the `figure` with `p` :( It will be nice if there are customisable settings.

![CleanShot 2023-09-26 at 16 25 12@2x](https://github.com/ckeditor/ckeditor5/assets/136648/dbc3159c-9839-4345-b5fb-1b3f7e847a9e)

**Comment by qipengwei** [comment]
> 我正在研究这个问题，因为 Outlook 网络邮件将`figure`用`p`:( 替换，如果有可自定义的设置就好了。
> 
> ![CleanShot 2023-09-26 16 25 12@2x](https://private-user-images.githubusercontent.com/136648/270556362-dbc3159c-9839-4345-b5fb-1b3f7e847a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTQ4OTEsIm5iZiI6MTcxODY5NDU5MSwicGF0aCI6Ii8xMzY2NDgvMjcwNTU2MzYyLWRiYzMxNTljLTk4MzktNDM0NS1iNWZiLTFiM2Y3ZTg0N2E5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNzA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGZlYTFlNGNhYWY3NTgwMmYwMTBiMWU2MDI2MDkzNDc5ZTEyMjY5NzYyNjYxODhlZWM3ODZiNGJlNWZlNWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1VgCSgFBJPdXT6foKiRpdyrQIm7uQ9MVQp7IqYLXh-s)

How do you handle it
