### ISSUE TITLE
How to set Cursor to set outside dropdown select value binding in editor

### ISSUE THREAD

**Issue by shankar5147** [ckeditor/ckeditor5#8878]
Dropdown selecting data we passing in editor using  **editor.model.document.selection.getFirstPosition()** but cursor was not showing in after text in editor

* CKEditor version: 5
![ckeditor](https://user-images.githubusercontent.com/43570538/105356862-f89e6500-5c19-11eb-9ef7-adb969ae0462.png)

**Comment by shankar5147** [comment]
Are there any updates regarding this issue?

**Comment by FilipTokarski** [comment]
Hi, in order to look into this, we'll need a precise description of what you want to achieve and also see the code you used for this. Could you possibly prepare working demo or repository and also explain exactly what is the problem?

**Comment by sudheeramzur** [comment]
@FilipTokarski The issue is persisting when we are trying to bind the values from external select dropdown to the editor and post that the cursor is not available after the value that is binded.
