### ISSUE TITLE
Updating the docs about autoformatting.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#8879]
We added the to-do list support in the autoformat plugin.

There should be information about that on [autoformat](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) and [to-do list](https://ckeditor.com/docs/ckeditor5/latest/features/todo-lists.html) pages.

I'm pretty sure that we also support some --- -- combinations, so maybe it is worth checking what may be missing in the autoformat docs.

**Comment by godai78** [comment]
Created a PR branch based on /master.  
  
The feature works in the To-do list guide, fails to work in the Autoformatting guide.   
  
@ckeditor/qa-team - guys, can you please have a look at it?  
  
Also some kinda bug: typing \<kbd>Space\</kbd> twice quickly inside / after `[ ]` produces a dot (`.`). ALso in the autoformatting guide, where `[ ]` does not produce a list marker...  
  
PR: #8893
