### ISSUE TITLE
Editor placeholder renders inside page break widget

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#8880]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8125/ckeditor5/tests/manual/all-features.html
2.  remove all content
3.  insert page break

### ✔️ Expected result

Placeholder is not visible

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/105379277-f71a7000-5c0c-11eb-84d1-b0fa1a2e0a5d.png)

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: current master branch
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Since which version this is a regression?

**Comment by niegowski** [comment]
> *   First affected CKEditor version: current master branch

It's caused by the recent changes

**Comment by oleq** [comment]
Perhaps we should've used `RawElement` instead of `UIElement` in #8858.

**Comment by pkwasnik** [comment]
@niegowski I can't reproduce it, maybe other changes fixed this. Could you recheck and confirm?

**Comment by niegowski** [comment]
It's still there: (note that the page break must be the only content in the editor)

![](https://user-images.githubusercontent.com/1232187/108478710-22888d00-7295-11eb-86fc-fb3f81b27ea5.png)
