### ISSUE TITLE
Autolink does not detect non-domain URLs

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8881]
## 📝 Provide detailed reproduction steps (if any)

1. Open the Link demo – http://127.0.0.1:8080/ckeditor5/latest/features/link.html#autolink-feature
2. Find the "Autolink feature" section
3. Paste: `http://127.0.0.1:8080/ckeditor5/latest/features/link.html#autolink-feature` then <kbd>Space</kbd>
4. Paste: `http://127.0.0.1.com:8080/ckeditor5/latest/features/link.html#autolink-feature` then <kbd>Space</kbd>

### ✔️ Expected result

3. Pasted URL will be replaced with `$text[linkHref]` element
4. Same as 3.

![image](https://user-images.githubusercontent.com/2270764/105459859-3b4c5580-5c8b-11eb-897a-466d6d9c6e5c.png)

### ❌ Actual result

3. URL without a domain won't be replaced with a link.

![image](https://user-images.githubusercontent.com/2270764/105459838-338cb100-5c8b-11eb-9d56-30cb70bdb6dd.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by magda-chrzescian** [comment]
I created a PR that covers the described problem, but I limited the non-domain URLs to IP addresses. I assumed that we don't want to convert e.g. http://justsometext to the link.
