### ISSUE TITLE
Missing `language-css` error in Markdown demo

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8882]
## 📝 Provide detailed reproduction steps (if any)

Open the Markdown demo (http://127.0.0.1:8080/ckeditor5/latest/features/markdown.html) and see the dev console.

### ✔️ Expected result

Clean console (without errors).

### ❌ Actual result

```
highlight.pack.js:212 Could not find the language 'language-css', did you forget to load/include a language module?
p @ highlight.pack.js:212
f @ highlight.pack.js:168
onmessage @ highlight.worker.js:12
highlight.worker.js:14 Language "language-css" in codeblock section is not supported. Autohighlight was used instead!
```

![image](https://user-images.githubusercontent.com/2270764/105460820-9e8ab780-5c8c-11eb-9961-9b363c53f947.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
It seems that this issue is not reproducible anymore.
