### ISSUE TITLE
Avoid silent validation in command#execute()

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#890]
See https://github.com/ckeditor/ckeditor5-heading/pull/99#discussion_r173658956

Such checks can cause very nasty issues.

https://github.com/ckeditor/ckeditor5/pull/881 brings more of these and there may be some already, so let's fix them at once.

For me, the expected behaviour would be to throw an error. Alternatively, sometimes it's also ok to let the code pass and try to run with incorrect param if we can be quite sure that it will automatically crash short after. E.g. if the heading command would use `modelElement` to access some `headingElements[ modelElement ].whatever` just right after that `if()`, then that `if()` would be rather unnecessary. 

PS. remember that errors are documented with `@error`.

**Comment by jodator** [comment]
Handled in:
- https://github.com/ckeditor/ckeditor5-heading/pull/102
- https://github.com/ckeditor/ckeditor5-image/pull/190

**Comment by Reinmar** [comment]
Merged.
