### ISSUE TITLE
Update the documentation with info about DLLs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8905]
## 📝 Provide a description of requested docs changes

We have a new guide already, but it needs to be reviewed and updated.

Also, we need to think on what DLL-related things should be mentioned and where. Do we change imports? If yes, we need to review tones of docs (especially the framework guides). If not, we need to review whether we didn't change something already and revert that.

**Comment by Reinmar** [comment]
Decision for now: let's not use new paths in the guides. The reasoning is that we don't have the new import method documented in the API docs and explained. There are many decisions to be taken - such as, what's the difference between what's reexported and what's available directly.

**Comment by pomek** [comment]
Resolved with https://github.com/ckeditor/ckeditor5/pull/9147.
