### ISSUE TITLE
Get rid of the block image caption that currently shows up on image focus

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8907]
We agreed we're going with a "toggle caption" button in the image toolbar instead because it radically simplifies the UX in terms of switching between image types.

By doing this, we're also avoiding "jumping content" when navigating across the document and the overall confusion of the users as to why things change despite them doing no editing (also: will this "empty" caption remain or not? is it actually empty?).

The implementation of `ImageCaption` should also simplify.

Note: This is a major change for the CF team. Let's keep them informed.

**Comment by oleq** [comment]
Breaking change to note: after this you will need the image toolbar to add captions to images. Previously you could add captions without it by only focusing the image.

**Comment by oleq** [comment]
Should displaying the caption focus the nested editable?

## Yes

![2021-01-28 15.03.50.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/0fb11cdd-095c-4c32-878d-862909c275e7)

👍 just click and write quickly
👎 the image toolbar disappears and this may be confusing,
👎 if clicked by accident, the user must re-select the entire image,

## No

![2021-01-28 15.04.27.gif](https://images.zenhubusercontent.com/5db82ed39f933c0:0013cf856/48e6bd30-77c5-4f50-bf70-32e475aee366)

👍 it's clear what happened; the toolbar stays in place,
👎 another click to start typing (although you can <kbd>tab</kbd> to move the caret to the caption)

**Comment by magda-chrzescian** [comment]
Do we consider an option to keep the selection on the image active when editing the caption? I'm not sure if it's the right way, but the caption is actually a part of the image - even the widget border suggests that.  
  
I'm not sure which solution is better. The disappearing toolbar can be super annoying, but so is clicking in the caption to edit it. Sice the second scenario is probably the common one (add the caption -> enter the caption), maybe we should go with focusing the caption right away?

**Comment by oleq** [comment]
Closed in #9090.
