### ISSUE TITLE
Design image style, alignment, and caption icons

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8908]
The new UX means a new set of icons. Let's keep in mind that alignment icons should be re-usable across features such as table alignment (current), media (future), html-embed (future).

**Comment by jensen-lin** [comment]
**Feedback from our pilotusers:**
- When pasting images, the images should be automatically left-aligned.
- When we choose to set images to the left, the text below the image is moved to the right side of the image. We must then move this text down again. Possible to correct this? Have an option to right align and text is over or underneath the image.
- When pasting several pictures one after the other (below each other), there will be a lot of space in between. It is desirable that the pictures can be placed right after each other without any space between to save space. Able to remove the picture-text space when we do not use the picture-text.

**Comment by magda-chrzescian** [comment]
@jensen-lin thank you for your feedback.  
\* It is possible to change the text wrapping behavior simply by adjusting the CSS class behavior. You can address the `.ck-content .image-style-align-left` selector and give it the following properties:  
`float: none;`  
`margin-right: auto;`  
`margin-left: 0;`  
We are also working on putting this in the default image styles.  
\* Reducing the space between the images can be done a similar way, by resetting the margins for the `.ck-content .image` selector.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/8991.
