### ISSUE TITLE
Dropdown or drop-down?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#891]
I use "dropdown", but I can see "drop-down" being used in many places.

I'm not sure we can believe Google here, but "dropdown" seems to be far more popular:

![image](https://user-images.githubusercontent.com/156149/37282840-27ef45d4-25f6-11e8-9ac9-485d9dd844d7.png)

And it's the version used by most libs:

![image](https://user-images.githubusercontent.com/156149/37282858-35992c9a-25f6-11e8-862e-dc37c707fa7b.png)

cc @AnnaTomanek

**Comment by scofalik** [comment]
Of course dropdown.

**Comment by jodator** [comment]
I'm for "dropdown" - I've noticed that someone changed "dropdown" to "drop-down" in one of a features that I was working on and I've used "drop-down" since. But I feel that "dropdown" is OK also.

**Comment by AnnaTomanek** [comment]
Happy to use "dropdown" as a noun, let's just be consistent.

"Drop-down" was something we used in CKEditor 4, as a part of "drop-down menu" to replace incorrectly used "combo box". So it may have been me changing it somewhere, sorry about the confusion.

Welcome our new **dropdown** overlords!
