### ISSUE TITLE
iOS The caret is visible over dropdowns

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8913]
## 📝 Provide detailed reproduction steps (if any)

1. Put the selection in any editor in our docs
2. Open a dropdown (heading, special characters, table)

### ✔️ Expected result

The caret should not be visible.

### ❌ Actual result

![image](https://user-images.githubusercontent.com/2270764/105715753-466ae400-5f1e-11eb-886c-05fde310e7d7.png)

## 📃 Other details

* Browser: Safari (mobile)
* OS: iOS 14.3
* Installed CKEditor plugins: `#master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
I wouldn't be surprised if it was impossible to overlay iOS'es caret (high chance @oleq knows this) in which case there's not much we can do with it except to fill a bug report for upstream browser vendor.

**Comment by oleq** [comment]
DUP of #8913.
