### ISSUE TITLE
Tooltip "Click here…" is attached to invalid element

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8914]
## 📝 Provide detailed reproduction steps (if any)

1. Open the HTML embed guide

### ✔️ Expected result

The tooltip "Click here to insert new HTML snippet" should be attached to the proper icon in the editor's toolbar.

### ❌ Actual result

See the rectangle above the page title and navigation bar.

![image](https://user-images.githubusercontent.com/2270764/105716375-022c1380-5f1f-11eb-9a5c-bbb0de74ca6b.png)

## 📃 Other details

Browser: Safari (mobile)
OS: iOS 14.3
Installed CKEditor plugins: `#master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Works fine in the `Export to PDF` guide:

![image](https://user-images.githubusercontent.com/2270764/105717070-f5f48600-5f1f-11eb-91fe-62c32921fdfa.png)

**Comment by oleq** [comment]
The question is: is our implementation wrong or the library that we used is bugy? @pkwasnik any chance you give it a quick check?

**Comment by pomek** [comment]
@oleq, it works on other pages, e.g. Export to PDF.

**Comment by pomek** [comment]
But it also does not work in the Block-quote guide.

**Comment by pomek** [comment]
There is a small difference (the `tippyOptions` object) between working and non-working samples:

![image](https://user-images.githubusercontent.com/2270764/105720293-90a29400-5f23-11eb-90bb-3f239658130e.png)

![image](https://user-images.githubusercontent.com/2270764/105720314-95674800-5f23-11eb-9f89-68d5ec5b449a.png)

![image](https://user-images.githubusercontent.com/2270764/105720375-a912ae80-5f23-11eb-9edf-5fd4ab70f126.png)

**Comment by pkwasnik** [comment]
I don't have any iOS device, but I will try to analyze code and google about it

**Comment by oleq** [comment]
Looks like the balloon is attached to the void because the toolbar button got grouped 

![](https://user-images.githubusercontent.com/1099479/105823320-4bcb3b80-5fbd-11eb-81b4-e2a265c082aa.png)

**Comment by oleq** [comment]
If you open the toolbar dropdown with more items and do some scrolling, the balloon re-attaches to the button.

**Comment by oleq** [comment]
If you open the toolbar dropdown with more items and do some scrolling, the balloon re-attaches to the button.

**Comment by oleq** [comment]
Looks like the following resolves the issue:

```diff
diff --git a/docs/_snippets/assets.js b/docs/_snippets/assets.js
index ddf5db1473..798fd9f3e5 100644
--- a/docs/_snippets/assets.js
+++ b/docs/_snippets/assets.js
@@ -52,6 +52,12 @@ window.attachTourBalloon = function( { target, text, tippyOptions } ) {
                   return;
          }

+         if ( !target.offsetParent ) {
+                  console.warn( '[attachTourBalloon] The target DOM node is invisible and the balloon could not be attached.', { target, text } );
+
+                  return;
+         }
+
          const content = `
                   <div class="tippy-content__message">${ text }</div>
                   <button class="ck ck-button tippy-content__close-button ck-off" title="Close"></button>
```

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/commit/38314c9f453548632c0eb65645feb27e60ec2fe8.
