### ISSUE TITLE
Multi Root Editor - dynamically adding editable objects

### ISSUE THREAD

**Issue by vakuras** [ckeditor/ckeditor5#8915]
I've implemented a multi root editor with support for dynamically adding editable blocks.
The only issue I have encountered is that the newly added editable block is not rendered until it or any of the other editable blocks are touched.

Any way to force the object to be rendered?

**Comment by FilipTokarski** [comment]
Hi, without knowing the exact use case and seeing the code, there's not much we can help. 
Could you explain step by step what you want to achieve and possibly prepare some working demo of your custom code, or a repository, so we could look into this?

**Comment by vakuras** [comment]
Hi,

I actually managed already to make it work by setting the selection to the new editable element - 
`this.editor.model.change((writer: any) => writer.setSelection(this.editor.model.document.getRoot(rootName), 'end'));`

**Comment by huzedong2015** [comment]
how dynamically adding or remove editable element ?
