### ISSUE TITLE
MultiRoot editor - EditorUI.update fails somewhere in table widget code

### ISSUE THREAD

**Issue by vakuras** [ckeditor/ckeditor5#8916]
## 📝 Provide detailed reproduction steps (if any)

1. Add table width to Multi Editor code sample
2. Call EditorUI.update() somewhen
3. See error

### ✔️ Expected result

No error

### ❌ Actual result

×
CKEditorError: Cannot read property 'parent' of null
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Cannot read property 'parent' of null
▼ 6 stack frames were expanded.
findAncestor
.../node_modules/@ckeditor/ckeditor5-table/src/utils/ui/widget.js:53
getTableWidgetAncestor [as getRelatedElement]
.../node_modules/@ckeditor/ckeditor5-table/src/utils/ui/widget.js:35
WidgetToolbarRepository._updateToolbarsVisibility
.../node_modules/@ckeditor/ckeditor5-widget/src/widgettoolbarrepository.js:176
MultiRootEditorUI.<anonymous>
.../node_modules/@ckeditor/ckeditor5-widget/src/widgettoolbarrepository.js:94
MultiRootEditorUI.fire
.../node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js:221
MultiRootEditorUI.update
.../node_modules/@ckeditor/ckeditor5-core/src/editor/editorui.js:94

## 📃 Other details

* Browser: Microsoft Edge Latest
* OS: Windows 10
* First affected CKEditor version: 24
* Installed CKEditor plugins: Alignment,
    Bold,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    HeadingButtonsUI,
    ParagraphButtonUI,
    HorizontalLine,
    Indent,
    IndentBlock,
    Italic,
    Link,
    List,
    Paragraph,
    PasteFromOffice,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    TextTransformation,
    Underline,
    Image,
    ImageToolbar,
    ImageInsert,
    ImageResize,
    ImageStyle,
    LinkImage,
    Base64UploadAdapter,

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I cannot reproduce this. Could you share some more detailed steps together with your editor configuration? Besides, are you sure you're not using some custom code when experiencing this error?

**Comment by vakuras** [comment]
The reason for issue is, that I created the editables on the fly, didn't set the selection, and called update().
The table plugin code was trying to get the selection parent, and failed, as there was no selection in that editable yet.

The fix was the same as in #8915

**Comment by FilipTokarski** [comment]
I'm glad it works now. I'll close both tickets then.
