### ISSUE TITLE
Crash when copying nested table which was pasted into the editor

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#8917]
## 📝 Provide detailed reproduction steps (if any)

1. Enable nested tables with the code:
```js
editor.model.schema.on( 'checkChild', ( evt, args ) => {
	const context = args[ 0 ];
	const childDefinition = args[ 1 ];

	if ( context.endsWith( 'tableCell' ) && childDefinition && childDefinition.name == 'table' ) {
		// Prevent next listeners from being called.
		evt.stop();
		// Set the checkChild()'s return value.
		evt.return = true;
	}
}, { priority: 'highest' } );
```
2. Create a table with 1 table inside
3. Copy and paste thes table somewhere in the editor
4. Select the pasted table and press `ctrl / cmd + c`

### ✔️ Expected result

The second table is copied, no errors.

### ❌ Actual result

Error in the console:
```js
Uncaught TypeError: Cannot read property 'getAttributeKeys' of null
    at hasAnyAttribute (downcast.js:523)
    at createViewTableCellElement (downcast.js:382)
    at DowncastDispatcher.<anonymous> (downcast.js:69)
    at DowncastDispatcher.fire (emittermixin.js:221)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:560)
    at DowncastDispatcher._convertInsertWithAttributes (downcastdispatcher.js:582)
    at DowncastDispatcher.convertInsert (downcastdispatcher.js:197)
    at DataController.toView (datacontroller.js:248)
    at Document.onCopyCut (clipboard.js:151)
    at Document.fire (emittermixin.js:221)
```

https://user-images.githubusercontent.com/34380544/105724525-3e17a680-5f28-11eb-8cbb-8e45a1594be5.mp4

## 📃 Other details

Related - https://github.com/ckeditor/ckeditor5/issues/3232.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mat128** [comment]
I was able to reproduce the problem with the official demo editor as of today:

1. Navigate to https://ckeditor.com/ckeditor-5/demo/
2. Open console and attach checkChild handler to editor to allow nested tables
```javascript
editors[0].model.schema.on( 'checkChild', ( evt, args ) => {
	const context = args[ 0 ];
	const childDefinition = args[ 1 ];

	if ( context.endsWith( 'tableCell' ) && childDefinition && childDefinition.name == 'table' ) {
		// Prevent next listeners from being called.
		evt.stop();
		// Set the checkChild()'s return value.
		evt.return = true;
	}
}, { priority: 'highest' } );
```
3. Add 3x3 table
4. Add 3x4 table in the middle cell
5. Copy table
6. Paste table
7. Re-copy pasted table
