### ISSUE TITLE
Text styles not kept when being converted

### ISSUE THREAD

**Issue by LangQian** [ckeditor/ckeditor5#8921]
## 📝 Provide detailed reproduction steps (if any)

1. Load the following HTML into CK Editor
`<span style="font-family:'helvetica';">
    <span style="color:#0000ff;">
        <span style="font-size:16px;font-family:'arial';color:#000000;">
            aaa
        </span>
    </span>
</span>`

2. After CK Editor's processing, the above one was converted to the following one:
`<span style="color:#0000ff">aaa&nbsp;</span>`

### ✔️ Expected result

Styles should be kept after conversion.

### ❌ Actual result

Most styles were lost in the above scenario.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LangQian** [comment]
This is an issue our customers are facing, so it is very urgent for us but we couldn't solve it on our end. If any workaround can be provided, we would really appreciate it!

**Comment by Mgsy** [comment]
Hi! Could you please tell us what is your expected result? Do you expect to keep styles define in this span:

```
<span style="font-size:16px;font-family:'arial';color:#000000;">
```

... and convert it to a single span or keep the structure of nested spans?

**Comment by LangQian** [comment]
@Mgsy Both would work for us, as long as the styles can be kept. In the above example, our customers were seeing black text, but it now becomes blue, which makes them vey confused (since they don't know the underlying HTML looks like).

**Comment by LangQian** [comment]
Hi @Mgsy , do you need more information on this one? I see the 'pending: feedback' label is still there.

**Comment by Mgsy** [comment]
Hi @LangQian, I'm sorry for the late response, we had a busy period. I'll look at your case soon and get back to you.

**Comment by Mgsy** [comment]
@LangQian, thanks for bringing it to our attention. There's an issue with our converters - in the case of nested elements, styles from the deepest one should be applied, while now, those are ignored.

Note: CKEditor 4 handles such case properly and applies styles from the deepest nested element.

**Comment by jacekbogdanski** [comment]
A related issue in text part language feature - https://github.com/ckeditor/ckeditor5/pull/9074#issuecomment-799512201
