### ISSUE TITLE
with custom adapter is it able to place pdf and other docs in the Editor(not needed to upload in server)

### ISSUE THREAD

**Issue by GowthamAsohan** [ckeditor/ckeditor5#8922]
In our project we plan to use CKEDITOR 5 as chat editor in angular application. So we just need to attach (pdf or other docs) to each message sent. I have gone through the doc it is clear how to create custom adapter and it worked for image. So will it work for pdf and other doc as well. And no need to upload the files in server , will converted to base64  and  saved in database along with each message. Any reference (for implementing in angular)would be helpful.. Thanks

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Currently, it's not possible to upload files different from images and insert them to the editor. We have open feature requests for this use case, so feel free to add :+1:  and join the discussion to bump its popularity - #5999, #7342.
