### ISSUE TITLE
Problem editing the iframe tag

### ISSUE THREAD

**Issue by AliRJS** [ckeditor/ckeditor5#8923]
I stored this content in the database using ckeditor5:

`<figure class="media"><style>.h_iframe-aparat_embed_frame{position:relative;}.h_iframe-aparat_embed_frame .ratio{display:block;width:100%;height:auto;}.h_iframe-aparat_embed_frame iframe{position:absolute;top:0;left:0;width:100%;height:100%;}</style><div class="h_iframe-aparat_embed_frame"><span style="display: block;padding-top: 57%"></span><iframe src="https://www.aparat.com/video/video/embed/videohash/J80mR/vt/frame" title="مصاحبه با ایلان ماسک" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"></iframe></div></figure>`

The problem is that when I try to edit this content again with ckeditor, it converts the content as shown below.

`<p>.h_iframe-aparat_embed_frame{position:relative;}.h_iframe-aparat_embed_frame .ratio{display:block;width:100%;height:auto;}.h_iframe-aparat_embed_frame iframe{position:absolute;top:0;left:0;width:100%;height:100%;}</p>`

![Screenshot 2021-01-26 091935](https://user-images.githubusercontent.com/68047553/105805638-ab264d00-5fb7-11eb-9ea8-eed176f6bcf8.png)

CKEditor  version: CKEditor 5 - DecoupledDocumentEditor

**Comment by Mgsy** [comment]
Hi, do you use some kind of custom plugin for handling such iframe?
