### ISSUE TITLE
Pressing backspace / delete on a list item crashes the editor.

### ISSUE THREAD

**Issue by sultugamer7** [ckeditor/ckeditor5#8927]
## 📝 Provide detailed reproduction steps (if any)

1. Click on the Bulleted List or Numbered List.
2. Type '1234'.
3. Press the left arrow key twice to make the cursor reach between 2 and 3.
4. Press the backspace or the delete key.

### ✔️ Expected result

The editor should delete 2 if the backspace key was pressed or 3 if the delete key was pressed.

### ❌ Actual result

Editor crashes.

## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* First affected CKEditor version: Not sure
* Installed CKEditor plugins:
        Alignment,
	Base64UploadAdapter,
	Bold,
	CKFinder,
	Essentials,
	FontColor,
	FontSize,
	Heading,
	Highlight,
	Image,
	ImageCaption,
	ImageResize,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	Italic,
	List,
	ListStyle,
	Paragraph,
	PasteFromOffice,
	Table,
	TableCellProperties,
	TableProperties,
	TableToolbar,
	TextTransformation,
	Underline

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, sorry but I'm not able to reproduce this in any way ( could you try on [our demo](https://ckeditor.com/ckeditor-5/demo/)? ). Could you share some more information about the problem ( error message, step-by-step description, editor config, package.json, etc. )? And also, are you sure you're not using some custom code that changes how the `list` plugin behaves?

**Comment by sultugamer7** [comment]
Really sorry about this late comment.
It led to an error because we were using 2 different versions of the CKEditor (4 and 5).
After I removed the 4th version, everything worked fine.

Thank you.
