### ISSUE TITLE
Dynamically adding and removing editors using React component fails randomly

### ISSUE THREAD

**Issue by vakuras** [ckeditor/ckeditor5#8930]
## 📝 Provide detailed reproduction steps (if any)

1. Add and remove a CKEditor react component dynamically
2. When the CKEditor component is created, in the onReady callback, access editor.plugins
3. One of the component will crash on editor.plugins being undefined

### ✔️ Expected result

No crash

### ❌ Actual result

TypeError: Cannot read property 'plugins' of null
onReady
C:/Dev/CRM.Services.eSign/packages/client/src/common/components/ckEditor/CKEditorWrapper.tsx:191
  188 | onReady={(editor: any) => {
  189 |     typeof ref === 'function' ? ref(editor) : ref && (ref.current = editor);
  190 | 
> 191 |     variableDropDownUIRef.current = editor.plugins.get(VariableDropDownUI);
      | ^  192 |     variableDropDownUIRef.current!.setForceRender(forceRender);
  193 | 
  194 |     variableInputUIRef.current = editor.plugins.get(VariableInputUI);

## 📃 Other details

* Browser: MS Edge latest
* OS: Win 10
* First affected CKEditor version: 24
* Installed CKEditor plugins: Alignment,
    BlockToolbar,
    Bold,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    HeadingButtonsUI,
    ParagraphButtonUI,
    HorizontalLine,
    Indent,
    IndentBlock,
    Italic,
    Link,
    List,
    Paragraph,
    PasteFromOffice,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    TextTransformation,
    Underline,
    Image,
    ImageToolbar,
    ImageInsert,
    ImageResize,
    ImageStyle,
    LinkImage,
    Base64UploadAdapter,

---

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It's hard to guess what's wrong without seeing the actual code. Would you be able to prepare a repo or some minimal working demo of the failing app, so we could look into this?
