### ISSUE TITLE
Adjust Space between the line tool

### ISSUE THREAD

**Issue by arunjoshtech** [ckeditor/ckeditor5#8936]
## 📝 Increasing and decreasing  of spacs between the lines options needed. 
_What is the expected behavior of the proposed feature?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, setting line-height is not supported, however, we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1429) for it. Feel free to add :+1:  to the first post to bump its popularity.
