### ISSUE TITLE
Remove or replace deps and devDeps badges

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8938]
I suppose david reads package.json from the old repo. IDK, maybe there's a way to make it read from https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/package.json. If not, we can consider a different badge system or remove it at all.

Side quest: we can consider adding a CI badge to all packages. We removed these once we merged the project into one repo. I think it's fine to have the same travis badge in all packages. To me, it looks "nice" if the project has badges. The next one to consider would be something for the CC.

![image](https://user-images.githubusercontent.com/156149/106005442-8794fc80-60b4-11eb-9218-e9af41eb10de.png)

![image](https://user-images.githubusercontent.com/156149/106005502-967baf00-60b4-11eb-96a8-97ff58ed6c18.png)

**Comment by pomek** [comment]
Since we won't merge any PR that lowers the coverage below 100%, we can add the entire project coverage (as we want to keep it 100%).

[![Coverage Status](https://coveralls.io/repos/github/ckeditor/ckeditor5/badge.svg?branch=master)](https://coveralls.io/github/ckeditor/ckeditor5?branch=master)

So the ticket is about two things:

1. Replace the dep/devDep badges,
2. Add the coverage badge (the code below).

```md
[![Coverage Status](https://coveralls.io/repos/github/ckeditor/ckeditor5/badge.svg?branch=master)](https://coveralls.io/github/ckeditor/ckeditor5?branch=master)
```

**Comment by pomek** [comment]
Remember about updating the README of packages located in the internal repository.

**Comment by pomek** [comment]
As mentioned in the ticket, we can also add the Travis badge:

[![Build Status](https://travis-ci.com/ckeditor/ckeditor5.svg?branch=master)](https://travis-ci.com/ckeditor/ckeditor5)

```md
[![Build Status](https://travis-ci.com/ckeditor/ckeditor5.svg?branch=master)](https://travis-ci.com/ckeditor/ckeditor5)
```

Let's keep the order of these as following: npm, coverage, travis.

**Comment by pomek** [comment]
As mentioned in the ticket, we can also add the Travis badge:

[![Build Status](https://travis-ci.com/ckeditor/ckeditor5.svg?branch=master)](https://travis-ci.com/ckeditor/ckeditor5)

```md
[![Build Status](https://travis-ci.com/ckeditor/ckeditor5.svg?branch=master)](https://travis-ci.com/ckeditor/ckeditor5)
```

Let's keep the order of these as following: npm, coverage, travis.
