### ISSUE TITLE
Copy paste from windows space between line

### ISSUE THREAD

**Issue by arunjoshtech** [ckeditor/ckeditor5#8939]
1. … Tried to add editor with angular and found issues when copy paste from words introduce double space and when it convert to word introduce more space looks can't able to use this editor.
We used CKEditor 5 version 
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, could you add a detailed step-by-step description to reproduce this issue?
