### ISSUE TITLE
Toolbar starts to wrap

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#894]
![image](https://user-images.githubusercontent.com/156149/37375023-1813a230-271e-11e8-983c-2429c4f89118.png)

Well... we said that we ignore this scenario for now because it's the implementor's role to take care of this (by not using too many features or using wide enough toolbar. And here we are ;)

**Comment by oleq** [comment]
We need a dynamic grouping mechanism I described before https://github.com/ckeditor/ckeditor5/issues/817#issuecomment-363066559

![image](https://user-images.githubusercontent.com/1099479/35803786-581b2d50-0a75-11e8-8a64-3ad13a9ff3f7.png) 
![image](https://user-images.githubusercontent.com/1099479/35803793-645f89e4-0a75-11e8-9825-bfd1c740e66c.png)

**Comment by Reinmar** [comment]
BTW, in examples, there's no ToC on the right, so we might make the content a bit wider.

**Comment by oleq** [comment]
I created a quick fix for the limited horizontal space issue by adjusting the Umberto container width in the examples/builds/document-editor.html (see the [commit](https://github.com/ckeditor/ckeditor5/commit/9768a8f89f803c41d736e8a6429735b8d8121be6)). Unfortunately, we cannot use this fix in the guide (framework/guides/ui/document-editor.html) because it has the TOC on the right side, which limits the space.

We might need some option in Umberto to use a wider layout when necessary for examples/guides like this one.

**Comment by Reinmar** [comment]
In https://github.com/ckeditor/ckeditor5/issues/1472 @dashingswags proposed a bit different approach to the UI (the 3 dots and the menu look). I quite liked it. We don't have such a component your so we'd need to think how to propose it (to avoid weird duplication) **if** we want to make it reusable. If not, we could just implement similar look&feel.

One issue that I see with #dashingswags's solution is that dropdowns or split buttons won't work in such a panel. Would this be a deal breaker?

**Comment by dashingswags** [comment]
Tested with dropdowns before initiating a pull request which works well too. 
samples with screenshots wwould be uploaded on the issue page just to show variations

**Comment by dashingswags** [comment]
![screenshot 187](https://user-images.githubusercontent.com/15422269/51495427-82fa2700-1dbc-11e9-8cfe-ee1ba5192b38.png)
![screenshot 188](https://user-images.githubusercontent.com/15422269/51495428-8392bd80-1dbc-11e9-8266-5e903c3bda09.png)

**Comment by jodator** [comment]
Also on mobile: 
![2019-02-19 14 46 34](https://user-images.githubusercontent.com/247363/53019854-fcd20e80-3455-11e9-8fe7-8746285795b5.jpg)

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/issues/416.
