### ISSUE TITLE
React Iframe with CreatePortal - Wrong inlinne toolbar position

### ISSUE THREAD

**Issue by Morphexe** [ckeditor/ckeditor5#8945]
## 📝 Provide detailed reproduction steps (if any)

1. Create a React Iframe
2. Render Ballon/Inline CKEditor inside the iframe with React.createPortal
3. The inline toolbar is attached to the main document body, which messes up the position on the dom

### ✔️ Expected result

The Inline toolbar is correctly aligned to the element

### ❌ Actual result

The Inline toolbar gets the incorrect position on the document.

## 📃 Other details
From my quick debugging it seems ck-body-wrapper is being attached to the document.body, instead of the Iframe, so the position logic does not take in account the Iframe position on the page.
This seems to be specific to how the createPortal behaves with React.

I would look into this myself, but I have no idea where the logic for the position currently lives for the toolbar sadly, if you can point me in the right direction I can take a look at it myself.

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Can you create some live demo (e.g. in GitHub repository), so we'll be able to see the issue live?

**Comment by carlesgomalb** [comment]
I have been able to reproduce this as @Morphexe says. The only work around found is to override toolbar styles and make it fixed. Can this issue be opened again?
