### ISSUE TITLE
Ckeditor5 stop inserting span

### ISSUE THREAD

**Issue by ofelipelima** [ckeditor/ckeditor5#8946]
Hi Team
I'm posting this again because I did not seen your message at [#8622](https://github.com/ckeditor/ckeditor5/issues/8622) very sorry about that - and I guess if it's closed you will not look there.

We have custom tags for CMS functions. Example:
{related::1234}
So system parse this {related} tag and get the number inside it to do something.

When I save the text and ckeditor5 reload content, my tag is now like:
{related::<span style="background-color:rgb(255,255,255);color:rgb(63,66,84);">1234</span>}

So with this tag our system parser is not working as expected.

Why? How can I disable this?

We are migrating from ckeditor4 and having some dificulties - we're almost rolling back to v4 :(

**Steps to reproduce:**

The step is to paste tags like:
{related::1234}

or use ckeditor 5 insert text to insert same tag, guess was like:

editor.model.change( writer => {
const insertPosition = editor.model.document.selection.getFirstPosition();
writer.insertText( '{related::1234}', insertPosition );
} );

Both methods cause ckeditor 5 to insert a span tag between number inside tag.

Unfortunately we rollback to ckeditor 4 because of this problem only :(

Thank you guys be safe

**Comment by Mgsy** [comment]
Hi! The issue seems to be connected with some custom implementation, which wraps your text in `<span>`. 

```
editor.model.change( writer => {
	const insertPosition = editor.model.document.selection.getFirstPosition();
	writer.insertText( '{related::1234}', insertPosition );
} );
```

This code simply inserts text `{related::1234}` and by default, it won't wrap any text in `<span>` (you can verify it [in our demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)). I'd recommend reviewing your custom plugins and see whether any of them could insert unwanted `<span>`.

**Comment by ofelipelima** [comment]
You're right. Just tested in a clean ckEditor 5 build alone as you suggested.
I'll try to debug and find what is causing this and if successfull I post here.
Thank you very much.

**Comment by rsnyd46** [comment]
Ever figure out what happened here?

**Comment by ofelipelima** [comment]
> Ever figure out what happened here?

To be honest, I don't remember what I did to resolve.
I just remember generating the cleanest build of ckEditor possible, with the minimum number of plugins needed to run on the custom PHP CMS.
Following the Mgsy's tip and testing in a clean build was the suggestion that helped me the most, so I knew it was in my system and not in the ckeditor.

**Comment by rsnyd46** [comment]
@ofelipelima Thank you so much for the reply.  Be well.
