### ISSUE TITLE
Parse error on init with <a href="...&amp;..."

### ISSUE THREAD

**Issue by Schwammerl11** [ckeditor/ckeditor5#8949]
When editor is initialized on this element it crashes with the following error message. I found the &amps; to be the problem, but I can't prevent this as it's normal HTML. I am using the ClassicEditor.

`<div class="inputRichText ck-content" style="display: none;"><h2 dir="ltr">&nbsp;Zoetis</h2>

<h3 dir="ltr" style="">&nbsp;</h3>

<h3 dir="ltr" style="">FÜR TIERE - FÜR DIE GESUNDHEIT - FÜR SIE</h3>

<p dir="ltr" style=""><span style="color:rgb(0,0,0);font-family:Arial, Helvetica, sans-serif;">Zoetis ist ein weltweit tätiges Unternehmen im Bereich Tiergesundheit, das sich der immer besseren Unterstützung seiner Kunden und deren Aufgaben widmet. Aufbauend auf unsere 60-jährige Erfahrung liefern wir Arzneimittel und Impfstoffe sowie Unterstützung und Fortbildung in hoher Qualität. Wir arbeiten Tag für Tag an einem besseren Verständnis der realen Herausforderungen der Menschen, die Tiere aufziehen und versorgen, um sie auf die beste Art und Weise unterstützen zu können.</span></p>

<p dir="ltr" style="">&nbsp;</p>

<h3 dir="ltr" style=""><span style="color:rgb(0,0,0);font-family:Arial, Helvetica, sans-serif;font-size:14px;">KONTAKT</span></h3>

<p dir="ltr" style="">Zoetis Österreich GmbH</p>

<p dir="ltr" style="">Floridsdorfer Hauptstraße 1<br>
1210 Wien</p>

<p dir="ltr" style=""><a href="https://testserver.richter-pharma.at/rp/d/app.nsf/hub.xsp/elord/zoetis?cms&amp;konda=10#">+43(0)1 270 11 00 100</a></p>

<p dir="ltr" style=""><a class="ck-link_selected" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=vetoffice@zoetis.com">vetoffice@zoetis.com</a></p></div>`

![image](https://user-images.githubusercontent.com/15922280/106164089-ea0bfc80-6189-11eb-879c-d19b18432b52.png)

**Comment by Schwammerl11** [comment]
On further investigation, I found that it doesn't matter if I substitute & with &amp; or not. The error occurs every time the url contains more than one parameter and thus an ampersand.

This works:
<p dir="ltr" style=""><a class="ck-link_selected" href="https://mail.google.com/mail/?view=cm">vetoffice@zoetis.com</a></p>

These don't:
<p dir="ltr" style=""><a class="ck-link_selected" href="https://mail.google.com/mail/?view=cm**&**fs=1">vetoffice@zoetis.com</a></p>

<p dir="ltr" style=""><a class="ck-link_selected" href="https://mail.google.com/mail/?view=cm**&amp;**fs=1">vetoffice@zoetis.com</a></p>

**Comment by Schwammerl11** [comment]
Editing my link to look like this worked, although i don't understand any of this black magic ...
https://mail.google.com/mail/?view=cm&amp;amp;fs=1

**Comment by Mgsy** [comment]
Hi, thanks for the report. Unfortunately, I'm not able to reproduce your issue, the link with `&` renders properly:

![](https://user-images.githubusercontent.com/20988892/106431898-3a2add80-646e-11eb-894d-b862c0b22599.png)

Can you provide steps to reproduce the error?
