### ISSUE TITLE
There's no way to remove an empty paragraph at the beginning of content without changing the heading

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#895]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

master

## 📋 Steps to reproduce

1. Open any editor with the headings.
2. `editor.setData( '<p></p><h2>Header</h2>' )`
3. Try removing the empty paragraph without changing the heading level `h2->p`.

## ✅ Expected result

```
<p></p>
[]<h2>Header</h2>
```
and backspace could preserve the heading

```
[]<h2>Header</h2>
```

## ❎ Actual result

Backspace in such situation flattens the heading back to the paragraph. Is it by design?

**Comment by psiservices-rcocks** [comment]
We have a similar issue with delete and the following content:

`<h2></h2><p>paragraph</p>`

If you put the cursor on the `h2` line and press delete, it merges the paragraph into the heading rather than preserving the paragraph. This should only happen when the heading has content.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-typing/issues/146.
