### ISSUE TITLE
set default  image-caption-content after inserting an image

### ISSUE THREAD

**Issue by yxlolxy** [ckeditor/ckeditor5#8951]
Is there anyway to set default  image-caption-content after inserting an image,such as 
![image](https://user-images.githubusercontent.com/9352577/106228016-6869ac80-6225-11eb-9b6b-0315c1e83725.png)

**Comment by yxlolxy** [comment]
I think I found the way, append caption element to image element, then append the text  you want to caption element. I found it in stackoverflow

**Comment by laszlo-karpati** [comment]
Hi @yxlolxy !

We are in the same shoes.
Could you share your solution with us, please?

Thanks!

**Comment by yxlolxy** [comment]
just like this,
```
 const ele = writer.createElement("image", options);
 writer.appendElement("caption", ele);
 writer.appendText("sunny gay", ele.getChild(0));
```

**Comment by yxlolxy** [comment]
> Hi @yxlolxy !
> 
> We are in the same shoes.
> Could you share your solution with us, please?
> 
> Thanks!

Just like this,
```
const ele = writer.createElement("image", options);
writer.appendElement("caption", ele);
writer.appendText("我是大帅哥", ele.getChild(0));
```
