### ISSUE TITLE
Realtime Collaboration: Where can I see the details of user who saved the content last

### ISSUE THREAD

**Issue by asimkt** [ckeditor/ckeditor5#8952]
## 📝 Provide a description of requested docs changes

Google docs show who saved the content at last even when collaborating. Where can I see the detail of this data in Ck documentation?

![image](https://user-images.githubusercontent.com/10784527/106262291-d6739b00-6248-11eb-9213-1e67a5da4d59.png)

**Comment by Mgsy** [comment]
Hi! I'm sorry for the late reply. Currently, CKEditor 5 doesn't expose such UI for tracking last edits in the document. However, our team would love to know more about your use case, so could you please contact us through the [support channel](https://ckeditor.com/contact/) to discuss your needs?

P.S. The real-time collaboration is our premium feature and this repository is dedicated to an open-source part of the project, so we prefer keeping all communication about commercial features through the support channel. I'll close this issue and let's move the discussion to the support channel. Thanks!

**Comment by asimkt** [comment]
thanks
