### ISSUE TITLE
Single paragraph with different text formatting breaks it into multiple paragraphs while pasting on image

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#8953]
## 📝 Provide detailed reproduction steps (if any)

1.  Set different text formatting on parts of a paragraph
2.  Copy content of the paragraph
3.  Paste over the image

### ✔️ Expected result

An image is replaced with a single paragraph that looks exactly like the original one.

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/106264316-cac2ad00-6225-11eb-81d4-8c1dd133aa1a.gif)

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: very old bug
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
I guess it's because of the auto paragraphing. While pasting the `model.insertContent()` is triggered and it internally calls `model.deleteContent( selection, { doNotAutoparagraph: true } );` before inserting new content, new content (text) is not allowed in the root element so auto paragraphing kicks in.

**Comment by oleq** [comment]
This is ugly but it does not look like something users would come across in real-life applications. Like how often you paste text on a selected image (or an object? does it reproduce with tables?)? 

Is there any other use-case where this issue would re-appear?

**Comment by niegowski** [comment]
> does it reproduce with tables?

Yes, if a table is selected (not the selection inside)

**Comment by niegowski** [comment]
> Is there any other use-case where this issue could re-appear?

The same happens if you have some widget selected in the editor and drop some text with formatting from outside the editor

**Comment by oleq** [comment]
> I guess it's because of the auto paragraphing. While pasting the `model.insertContent()` is triggered and it internally calls `model.deleteContent( selection, { doNotAutoparagraph: true } );` before inserting new content, new content (text) is not allowed in the root element so auto paragraphing kicks in.

I still don't get why the result is chopped so crazy but it's likely because of some internals. Anyway, can you (roughly) estimate how much time would it take to address this?

**Comment by oleq** [comment]
> I guess it's because of the auto paragraphing. While pasting the `model.insertContent()` is triggered and it internally calls `model.deleteContent( selection, { doNotAutoparagraph: true } );` before inserting new content, new content (text) is not allowed in the root element so auto paragraphing kicks in.

I still don't get why the result is chopped so crazy but it's likely because of some internals. Anyway, can you (roughly) estimate how much time would it take to address this?

**Comment by oleq** [comment]
> I guess it's because of the auto paragraphing. While pasting the `model.insertContent()` is triggered and it internally calls `model.deleteContent( selection, { doNotAutoparagraph: true } );` before inserting new content, new content (text) is not allowed in the root element so auto paragraphing kicks in.

I still don't get why the result is chopped so crazy but it's likely because of some internals. Anyway, can you (roughly) estimate how much time would it take to address this?
