### ISSUE TITLE
Headings disallow to focus an image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#896]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of docs

Latest

## 📋 Steps to reproduce

1. Go to Classic Editor build example.
2. Focus the image and transform it into the side image.
3. Hover the upper part of the image and try to focus it.

## ✅ Expected result
You can focus the image.

## ❎ Actual result
You can't focus the image.

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/37392536-b0afd590-276e-11e8-96b7-adea1196dec8.gif)

**Notes**
It occurs only in docs.

OS: All plaftorms
Browser: All browsers

**Comment by Reinmar** [comment]
That's something about their styling. Let's fix this before the release.
