### ISSUE TITLE
Is the CKEditor file size supposed to be ~650 KiB?

### ISSUE THREAD

**Issue by Destaq** [ckeditor/ckeditor5#8962]
I'm creating a custom CKEditor build, and minifying it with Vue. 

However, I've noticed that when the `dist` folder is built with CKEditor, the file size is about 880 KiB (230 gzipped). On the other hand, without CKEditor, it's down to about 130 (40 gzipped).

Is this minified js file size normal or something to be worried about?

**Comment by stefandobre** [comment]
With almost all plugins enabled, my minified build of just the CKEditor5 library goes over 1MB, so I'd guess your size is normal, even pretty good.

**Comment by Destaq** [comment]
I guess it's average then; just surprised at the relatively large size.
