### ISSUE TITLE
Widget selection handler styles should not apply to child widgets

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8964]
## 📝 Provide detailed reproduction steps (if any)

1.  Put an HTML embed inside a table,
2.  Select the table

### ✔️ Expected result

The table should be selected, the HTML embed unselected.

### ❌ Actual result

Both handlers are selected.

![](https://user-images.githubusercontent.com/1099479/106445640-934f3d00-647f-11eb-97b7-8eaf97c85aed.png)

## 📃 Other details

*   Browser: \*
*   OS: \*
*   First affected CKEditor version: since the first implementation of the handle

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@oleq it looks to me like it has been fixed in the upcoming release.

**Comment by mlewand** [comment]
Fixed by #9457
