### ISSUE TITLE
Indent disable on Image , Indent work on CKEditor 4 and other editors 

### ISSUE THREAD

**Issue by raoshahid799** [ckeditor/ckeditor5#8965]
In CKEditor 5 we cannot increase or decrease the indent of image , disable on on image , 

![image](https://user-images.githubusercontent.com/13733062/106454264-4cc40780-64ac-11eb-8cb3-2f40827d7f2e.png)

**Comment by FilipTokarski** [comment]
Hi, indenting images CKEditor 5 it's not enabled by default, but you could do it with this code:
```js
if ( editor.model.schema.isRegistered( 'image' ) ) {
   editor.model.schema.extend( 'image', { allowAttributes: 'blockIndent' } );
}
```
This will allow `blockIndent` attribute on `image` model element.  
However, the images are by default wrapped in `<figure>` tag which has some styles on it, causing it in this case to _jump_ when adding indent. So you would also need to override the default margin styles for `figure`.  
  
Hope this helps!

**Comment by raoshahid799** [comment]
Thank you very much :)
