### ISSUE TITLE
Unable to get data after setting data with empty table inside a blockquote

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#8979]
## 📝 Provide detailed reproduction steps (if any)

1. Using [document editor](https://ckeditor.com/ckeditor-5/demo/#document)
2. Call `setData('<blockquote><figure class="table"><table><tbody><tr><td>&nbsp;</td></tr></tbody></table></figure></blockquote>')` (It's the same as adding blockquote, single cell table and getting it's data)
3. Call `getData()`

### ✔️ Expected result

Should return `<blockquote><figure class="table"><table><tbody><tr><td>&nbsp;</td></tr></tbody></table></figure></blockquote>`

### ❌ Actual result

Following exception is thrown:
`Uncaught TypeError: Cannot read property 'getAttributeKeys' of null`

![image](https://user-images.githubusercontent.com/1211686/106650406-a17d8600-6571-11eb-82f9-bc8bf0a941f1.png)

## 📃 Other details

* Browser: Chrome 88.0.4324.104
* OS: Windows 10
* First affected CKEditor version: 25.0.0
* Installed CKEditor plugins: Document build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I can confirm this.  
Seems like a regression introduced in version 23.0.0, bisection shows this commit - https://github.com/ckeditor/ckeditor5/commit/dc85a1e6495d3721c80128b546f6c0789b80d8ba  
  
Full stack trace:
```js
Uncaught TypeError: Cannot read property 'getAttributeKeys' of null
    at hasAnyAttribute (downcast.js:522)
    at createViewTableCellElement (downcast.js:381)
    at DowncastDispatcher.<anonymous> (downcast.js:68)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:554)
    at DowncastDispatcher._convertInsertWithAttributes (downcastdispatcher.js:576)
    at DowncastDispatcher.convertInsert (downcastdispatcher.js:216)
    at DataController.toView (datacontroller.js:238)
    at DataController.stringify (datacontroller.js:203)
    at DataController.get (datacontroller.js:188)
```

**Comment by niegowski** [comment]
This seems to be a DUP of #8941.

**Comment by dkrahn** [comment]
Could also be related to #8942.
From what I could tell, The fix suggested by @mat128 in the pull request above, should fix this problem.
What I don't know is if not calling the table postfixer is correct.
