### ISSUE TITLE
Additional step is required to move outside of the link

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#898]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce
1. Select some text.
1. Add a link.
1. Put the caret at the end of the link.
1. Press <kbd>Arrow right</kbd>.
1. Press <kbd>Arrow left</kbd> twice.
1. Press <kbd>Arrow right</kbd> twice.

## ✅ Expected result
The selection moves outside of the link.

## ❎ Actual result
The selection stays in the link.

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/37394062-2d17051e-2773-11e8-84e0-246afe410241.gif)

OS: All platforms
Browser: All browsers

**Comment by oleq** [comment]
DUP of https://github.com/ckeditor/ckeditor5-engine/issues/1346.
