### ISSUE TITLE
Failed to execute ‘collapse’ on ‘Selection’: The offset 7 is larger than the node’s length (2).

### ISSUE THREAD

**Issue by bittu1028** [ckeditor/ckeditor5#8983]
`“Failed to execute ‘collapse’ on ‘Selection’: The offset 7 is larger than the node’s length (2)”` 

I am getting this error on android webview whenever I am pressing the backspace button of the keyboard.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. We were testing CKEditor 5 in web view on Android/iOS and it was working properly. Can you prepare some demo/exact steps to reproduce, so we'll be able to see the issue locally?
