### ISSUE TITLE
Update the CF integration with the image feature after introducing inline images

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8985]
* `ImageStyleCommand#defaultStyle`?
* lots of tests to be updated
* Updating the default samples configurations as in #9144

**Comment by magda-chrzescian** [comment]
*   Updating the default samples configurations as in #9144

**Comment by oleq** [comment]
Use-case to fix: Because the caption of the image is stored in the model attribute when the caption is hidden, this may cause issues with the data compression in collaboration and desynchronization between collaborators.

**Comment by AnnaTomanek** [comment]
While reviewing the backlog, we realized that this is a leftover/duplicate issue with no PR connected to it as we covered the collaboration features integration in other issues (that are now merged to the respective feature branches). Leaving the estimate as is though as the scope of work that we've actually done covered both this estimate and the ones from other issues.
