### ISSUE TITLE
"Rich Text Editor" automatically appears at the top in ckeditor

### ISSUE THREAD

**Issue by ferykhan1362** [ckeditor/ckeditor5#8987]
When I use the ckeditor5 text editor similar to the example code below, a text with the title "Rich Text Editor" automatically appears at the top! My search to find and delete the relevant settings did not return any results. please guide me

     <script src="https://cdn.ckeditor.com/ckeditor5/25.0.0/classic/ckeditor.js"> 
     </script>
     <div id="editor">
     </div>
       <script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
    </script>

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/TdMzO.png

**Comment by Mgsy** [comment]
Hi, thanks for the report. This label shouldn't be visible by default. Maybe there are some styles in your application that make labels visible?

**Comment by ferykhan1362** [comment]
It is possible, but how can I solve it?

**Comment by Mgsy** [comment]
> It is possible, but how can I solve it?

I'm afraid I can't help you as I don't know your application, you should review your styles or force-hide this element with CSS.

**Comment by daoanhdungit** [comment]
@farshid-azizi I also had the same problem as you. The reason "Rich Text Editor" is showing is because the css property is overridden
![image](https://user-images.githubusercontent.com/41876188/231832559-b75d6b40-1731-4578-8e6b-f814e110ad69.png)
