### ISSUE TITLE
In the Angular component, defaultProtocol in the LinkConfig is not working as expected

### ISSUE THREAD

**Issue by alec-trievel** [ckeditor/ckeditor5#8988]
## 📝 Provide detailed reproduction steps (if any)

1. Inside a component, create a config object as follows: 
`    public editorConfig = {
        toolbar: {items: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', '|', 'indent', 'outdent', '|', 'blockQuote', 'insertTable', 'mediaEmbed', 'undo', 'redo']},
        image: {toolbar: ['imageStyle:full', 'imageStyle:side', '|', 'imageTextAlternative']},
        table: {contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells']},
        language: 'en',
        link: {
            defaultProtocol: 'https://',
        }
    };`
2. Inside the same compoent, setup the editor refgence as follows: `public editor = ClassicEditor;`
3. Create template for the same component as follows:
`<ckeditor [editor]="editor" [config]="editorConfig" [(ngModel)]="instructions"></ckeditor>`
4. Select the link tool in the toolbar and enter in a site such as `ckeditor.com`

### ✔️ Expected result

[Per the documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_link_link-LinkConfig.html#member-defaultProtocol): "For example, when the user is creating a link and types ckeditor.com in the link form input, during link submission the editor will automatically add the http:// protocol, so the link will look as follows: http://ckeditor.com.
The feature also provides email address auto-detection. When you submit hello@example.com, the plugin will automatically change it to mailto:hello@example.com"

### ❌ Actual result

Inputting ckeditor.com as a link does not automatically add the defaultProtocol to the the href attribute for sites nor emails. 

- Inputting ckeditor.com always generates `<p><a href="cdkeditor.com">cdkeditor.com</a></p>`
- Inputting hello@example.com always generates `<p><a href="hello@example.com">hello@example.com</a></p>`

## 📃 Other details

I've been able to add the other two features mentioned in the documentation - `addTargetToExternalLinks` and `decorators` - without issue using this method. These two features can be added together or separately and consistently work, but `defaultProtocol` never works.

* Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
* OS: Windows 10 Version 10.0.19041 Build 19041
* Angular version: 11.0.2
* First affected CKEditor version: "@ckeditor/ckeditor5-angular": "^1.2.3"
* Installed CKEditor plugins:"@ckeditor/ckeditor5-build-classic": "^18.0.0"

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. I've just checked your scenarios and everything works fine with the Angular integration. I can see that you use CKEditor 5 at version 18.0.0, which is old, as the latest version is 25.0.0. There's a chance that the mentioned feature is unavailable in the version you use. Try to upgrade to the latest version and see whether you can reproduce the problem.
