### ISSUE TITLE
Add support for setting text part language

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#8989]
## 📝 Provide a description of the new feature

Add support for setting text part language, similar to CKEditor 4 [language feature](https://ckeditor.com/cke4/addon/language).

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/2008

**Comment by Reinmar** [comment]
Inspiration: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-language_list

**Comment by niegowski** [comment]
We could simplify configuration by automatically detecting `dir` like we do it for `uiLanguageDirection` and `contentLanguageDirection`: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-utils/src/locale.js#L183-L185

**Comment by neongreen** [comment]
@niegowski

> We could simplify configuration by automatically detecting dir

Do you mean that if the user types some text in Hebrew or Arabic, it will automatically be laid out right-to-left even if the rest of the editor content is left-to-right?

Or that the whole editor content will be either right-to-left or left-to-right based whether the majority of the text is in one of the RTL langs or not?

**Comment by niegowski** [comment]
> Do you mean that if the user types some text in Hebrew or Arabic, it will automatically be laid out right-to-left even if the rest of the editor content is left-to-right?

I just meant the language code to "dir" mapping.

**Comment by hadifarnoud** [comment]
I should be able to change a paragraph's direction as needed. it can detect paragraphs direction based on first percentage of text in LTR or RTL language.

or simply, a LTR/RTL button that allow me to change text direction as needed.

**Comment by Reinmar** [comment]
There's a question that appeared while working on #9074 whether the default tittle of the default configuration of this dropdown have to be translated automatically.

IMO, no. It makes no sense as the entire config is there just for showcase purposes. It makes this feature work before someone configures this plugin. But the plugin needs to be configured anyway as the list of 4 options is just completely arbitrary and will not make any sense in 99% of cases.

**Comment by Reinmar** [comment]
The other question that appeared is the name of this feature:  [https://github.com/ckeditor/ckeditor5/pull/9074/files#r580836210.](https://github.com/ckeditor/ckeditor5/pull/9074/files#r580836210.) I find the current name "language" too vague and thus confusing. `config.language` will add to that as it may be understood as the language of the editor.

Therefore, I'm for something more concrete as "text language". cc @wwalc @AnnaTomanek

**Comment by Reinmar** [comment]
*   We should consider the name of the plugin. Should it be changed from `Language` to avoid collision with `language` property. `Language` → `Text language`?
*   There's `config.language` already. It's used to set UI and content languages.
*   The new feature is a new package and config of packages land in `config.<packageName>` hence we have a clash here.
*   If we'd rename this package name to avoid the clash, we'd have `config.textLanguage` which would still make a clash between `config.language.content` and `config.textLanguage` (content ≠ text wtf???).
*   Also, we expect to have more features related to language support (e.g. bidi blocks, some automatic recognition, unicode language marks, mirroring icons depending on the text dir under caret). Ideally, they should all be developed in one package (separate plugins, in one package). Thus, the more general name of this package, the better.
*   Hence, let's go with `ckeditor5-language` and `TextFragmentLanguage` plugin in it, and add this plugin's options to `config.language` object.

**Comment by wimleers** [comment]
Where can we screenshots/screencasts of this in action? https://ckeditor.com/blog/ckeditor-5-v26.0.0-with-extensible-builds-inline-widget-styling-and-annotations-guides/ made me curious to see how the CKEditor 5 implementation compares with the CKEditor 4 one 🤓

**Comment by AnnaTomanek** [comment]
Hi @wimleers, thanks for your interest :wave: 

The guide is [work in progress](https://github.com/ckeditor/ckeditor5/pull/9301), it should be merged tomorrow at the latest. The release blog post is due next Wednesday.
