### ISSUE TITLE
Blank space in the heading dropdown

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#899]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest docs

## 📋 Steps to reproduce

1. Open the heading dropdown.

## ✅ Expected result
No blank space at the beginning or at the end of the dropdown.

## ❎ Actual result
There is some blank space at the beginning and at the end of the dropdown.

## 📃 Other details that might be useful
**Screenshot**
Docs:
![image](https://user-images.githubusercontent.com/20988892/37394884-2dab4a2e-2775-11e8-89a3-1f989e3a0d42.png)

CKE5 sample:
![image](https://user-images.githubusercontent.com/20988892/37394906-3e098c00-2775-11e8-9cdd-fb551c26c912.png)

OS: All platforms
Browser: All browsers

**Comment by Reinmar** [comment]
That's again something about docs styling. Let's also fix this.

**Comment by oleq** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/494#issuecomment-365671757.

**Comment by Reinmar** [comment]
Can we have a hotfix for that in https://github.com/ckeditor/ckeditor5/blob/master/docs/assets/snippet-styles.css? I know that all these are problems with specificity, but we need to make the docs look good.

**Comment by oleq** [comment]
Yes, I can handle it.
