### ISSUE TITLE
How do I change the toolbar icon when I use an online builder?

### ISSUE THREAD

**Issue by jongjunpark** [ckeditor/ckeditor5#8994]
my editor was built by using an online builder.
But there is no function to change the toolbar icon, so I want to know how to change the icon.

<img width="382" alt="스크린샷 2021-02-05 오후 5 25 52" src="https://user-images.githubusercontent.com/60080679/107008995-c8d58c80-67d7-11eb-99f3-2740b3e2d3bf.png">

**Comment by Mgsy** [comment]
Hi! It's possible to change an icon via Webpack config. Please, [see the guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-customize-the-ckeditor-5-icons) to learn more.
