### ISSUE TITLE
Mentions issue

### ISSUE THREAD

**Issue by mturetchi** [ckeditor/ckeditor5#9000]
1. Access CKEditor (custom build)
2. Try to add a mention
3. Dropdown isn't displayed (a warning appears in the browser console)

mention-feed-callback-error: Could not obtain mention autocomplete feed. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-mention-feed-callback-error

I note that in the past this problem didn't exist, it appeared a few days ago, both in production and in dev environment

* Browser: Microsoft Chromium Edge, Google Chrome
* OS: Windows 10
* Installed CKEditor plugins: @ckeditor/ckeditor5-mention": "^22.0.0

**Comment by FilipTokarski** [comment]
Hi, are you sure you have [properly configured](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#configuration) mention feature? It's hard to say what caused this without seeing the code. So if  you're sure this is not something on your side, please share your editor configuration and steps to reproduce the issue.

**Comment by mturetchi** [comment]
Hi, here is an example for you to understand how CKEditor is initialized and configured
I mention that this feature was integrated in our project about 3 months ago, and no changes were made...

https://stackblitz.com/edit/typescript-k8xmfa?file=index.ts

**Comment by FilipTokarski** [comment]
The snippets you linked are missing your custom code, which most probably triggers the error. So again, please make sure that your methods for getting and rendering feed work properly ( do you still get the error if you remove them? ).

**Comment by mturetchi** [comment]
Fixed, I created a new ng build.... I can't explain the cause...
