### ISSUE TITLE
Misleading Code in Docs

### ISSUE THREAD

**Issue by klaustinw** [ckeditor/ckeditor5#9008]
## 📝 Describe requested docs changes
Link: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#context-feature

`import { CKEditor, CKEditorContext } from '@ckeditor/ckeditor5-react';`

_What is the purpose and what should be changed?_
I had troubles going through the documentation as it instructs the reader to import the CKEditorContext and Context from CKEditor whilst there is no need for that.

`import Context from '@ckeditor/ckeditor5-core/src/context';`
Importing "Context" and everything below the line in the code from docs (excluding ClassicEditor) will error out

> CKEditorError: ckeditor-duplicated-modules

and will be given a link to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules which then telling the reader that there have been duplicated imports.

**Comment by AnnaTomanek** [comment]
Thanks for the report!

@ma2ciek Would you kindly have a look at this?

**Comment by ma2ciek** [comment]
Hi @klaustinw,

> _What is the purpose and what should be changed?_  
> I had troubles going through the documentation as it instructs the reader to import the CKEditorContext and Context from CKEditor whilst there is no need for that.

For me, this section was clear as it starts with:

> The [`@ckeditor/ckeditor5-react`](https://www.npmjs.com/package/@ckeditor/ckeditor5-react) package provides a ready-to-use component for the [context feature](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/context-and-collaboration-features.html) that is useful when used together with some [CKEditor 5 collaboration features](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/collaboration.html).

So if you're not using the `Context` feature you should not be interested in this chapter.

And later the code snippet should be also correct. (It assumes that you build everything from source). 

> `import Context from '@ckeditor/ckeditor5-core/src/context';`  
> Importing "Context" and everything below the line in the code from docs (excluding ClassicEditor) will error out
> 
> | CKEditorError: ckeditor-duplicated-modules

Are you sure that you aren't importing any of the CKEditor 5 builds as well?

**Comment by klaustinw** [comment]
> 
> 
> Hi @klaustinw,
> 
> > _What is the purpose and what should be changed?_
> > I had troubles going through the documentation as it instructs the reader to import the CKEditorContext and Context from CKEditor whilst there is no need for that.
> 
> For me, this section was clear as it starts with:
> 
> > The [`@ckeditor/ckeditor5-react`](https://www.npmjs.com/package/@ckeditor/ckeditor5-react) package provides a ready-to-use component for the [context feature](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/context-and-collaboration-features.html) that is useful when used together with some [CKEditor 5 collaboration features](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/collaboration.html).
> 
> So if you're not using the `Context` feature you should not be interested in this chapter.
> 
> And later the code snippet should be also correct. (It assumes that you build everything from source). 
> 
> > `import Context from '@ckeditor/ckeditor5-core/src/context';`
> > Importing "Context" and everything below the line in the code from docs (excluding ClassicEditor) will error out
> > | CKEditorError: ckeditor-duplicated-modules
> 
> Are you sure that you aren't importing any of the CKEditor 5 builds as well?

I realized that I didn't need the Context feature as I tried without putting it inside my project. I thought it was an essential part of the CKEditor to work.

I built everything according to the docs told me to from installing the npm packages to using it inside React, but alas the problem still persists. This, I think it's of my own fault. I have looked specifically into the error code today and found out the specific solution for my errors. I apologize for the lack of information and misunderstanding of the error code, thank you for putting the time to reply to my open issue..

This is my first time putting an issue in GitHub. I assumed with me already figuring out the problem I should close this issue with comment.

 Thank you for your time
