### ISSUE TITLE
Upload images don't work in docs/features

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#901]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest `master` in all packages.

## 📋 Steps to reproduce

1. Pull the changes in all repositories (`mgit update`).
2. Be sure that everything is linked correctly (`lerna bootstrap`).
3. Build the documentation: `npm run docs -- --production`.
4. Go to built docs => features and play with it.

## ✅ Expected result

Upload images should work.

## ❎ Actual result

```
log.js:58 filerepository-no-upload-adapter: Upload adapter is not defined. [...]
```

## 📃 Other details that might be useful

Upload does not work for the editors listed below:

- Font: the 2nd editor on the page,
- Headings: both editors,
- Highlight: the 1st editor (on the top),
- Text alignment: the 1st editor (on the top).

If the upload image button in the editor's toolbar is being missed, you need to drag&drop the image.

**Comment by pomek** [comment]
When all related PRs will be merged, this ticket can be closed.

**Comment by Reinmar** [comment]
Thanks!
