### ISSUE TITLE
Output the source code in HTML instead of the model

### ISSUE THREAD

**Issue by asimkt** [ckeditor/ckeditor5#9010]
## 📝 Provide a description of the new feature

> Related to https://github.com/ckeditor/ckeditor5/issues/592 and https://github.com/ckeditor/ckeditor5/issues/1627

I want to get the HTML as it is for post-processing it for making it email friendly. So I've two questions:

- How can I get the actual source code (editing view HTML) instead of the model? As I've some custom elements in the editor which render react component inside it.
- How can I get the styles for our classes? I know I can copy it myself from content styles, but is there a better way to export it as "what I see".

I checked the docs and couldn't find an answer. I think it's because CK can output not just HTML and this is not implemented yet. But how can I get the actual HTML, not the HTML-like output as we get with `editor.getData()`?

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
Are you sure you want editing view HTML (which includes things like small buttons around images, other editing capabilities, etc)?

`getData` does not return the model, it returns a data view. For example, paragraphs are represented as `<paragraph>` in the model and `<p>` in the data view. `getData` returns the latter. Its output should be suitable for inserting into an email.

When you implement custom elements, you provide both a `model -> editing view` cast and a `model -> data view` cast. So custom elements should also be fine.

**Comment by asimkt** [comment]
> Are you sure you want to edit view HTML (which includes things like small buttons around images, other editing capabilities, etc)?

I want to see the source HTML, yes. but, I don't want to directly change it though. This is for my backend to store the content as HTML for other purposes.

> getData does not return the model, it returns a data view.

Sorry for the confusion. Mine was a [react](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/using-react-in-a-widget.html) component and I don't want to keep sending the whole HTML to the backend when autosaving. but on a specific event, I need this HTML. Now, are you saying that sending full HTML is the way to go in this case? There's no `getSource()` function? If there's a CK utility function that helps me do this, that would also work for me. 


And any input on the question below:
>How can I get the styles for our classes? I know I can copy it myself from content styles, but is there a better way to export it as "what I see".

**Comment by neongreen** [comment]
Your backend should not store _edit view_ HTML, it should store _data view_ HTML.

I want to make sure that we're on the same page. There are three entities:

* model — HTML-like tree that CKEditor works with internally
* data view — HTML output that is suitable for inserting into a web page, email, etc
* editing view — HTML that is present inside the editor during editing, with buttons and such

`getData` returns the data view. This is what you should be sending to your backend during autosave. (Counterintuitively, not the model! I thought saving the model made more sense, but the support told me that I should store the data view.)

**Comment by neongreen** [comment]
> How can I get the styles for our classes? I know I can copy it myself from content styles, but is there a better way to export it as "what I see".

I'm not a CKEditor dev, so I don't have any input here other than "yeah, sounds exactly like #1627".

**Comment by asimkt** [comment]
Thanks again for the quick replies. 

> Your backend should not store edit view HTML, it should store data view HTML.

As I said, I'm not sending the editing view or raw HTML to the backend on autosaving. copying from my older comment:

> but on a specific event, I need this HTML.

My specific event is after a confirmation from the user, I need to send the editor content as an email. as you may already know, CK can create the full HTML out of a data view, but I can't. But to send it as email content, I need either the editing view or a simple HTML which will render as the editor content with styles. so that I can send it as email content. I actually need inline style also, but I have a workaround for that.

**Comment by neongreen** [comment]
I admit that I still don't get why you need to send the editing view as email content. The reason I am very suspicious about the desire to include the editing HTML anywhere is that the editing HTML includes things like this (red ovals):

![image](https://user-images.githubusercontent.com/1523306/108106454-429a2f80-708e-11eb-9b98-c59b67bab0b1.png)

It would be rather weird to see these editor bits and pieces in an email where I can't actually edit the content.

If you have a custom React component, you should provide both an editing view representation and a data view representation for it — and the data view representation should be the one that you want to see outside of the editor (e.g. in emails).

However: if you really want to, I guess you can simply grab and serialize the DOM from inside the editor widget. You don't need CKEditor's support for that.

There might also be a specific method CKEditor provides to convert the data view into the editing view, but off the top of my head I don't know what it is. That would be a question for the CKEditor developers.

I think I'm not going to be particularly useful here so I will unsubscribe from this convo now.

**Comment by neongreen** [comment]
> However: if you really want to, I guess you can simply grab and serialize the DOM from inside the editor widget.

By finding an element with a `.ck-content` class and taking its [`.innerHTML`](https://www.w3schools.com/jsref/prop_html_innerhtml.asp) property.

**Comment by asimkt** [comment]
Thanks, @neongreen, and apologies for the late replies. Yes. I used DOM APIs to get the HTML.
