### ISSUE TITLE
CKEditor Custom build in React and is used as redux field causing focus issue

### ISSUE THREAD

**Issue by ga987** [ckeditor/ckeditor5#9014]
## 📝 Provide detailed reproduction steps (if any)

1. I have created custom build with necessary plugins from Online Builder.
2. I wanted Placeholder feature as well so followed CKEditor 5 Inline widget docs.
3. It is working fine in Html file
![image](https://user-images.githubusercontent.com/16472151/106285337-5bbb7780-626a-11eb-8c0f-f41c930c52ef.png)
4. When the custom build is imported and used as redux form field, It is causing focus issue. for better understanding please watch below video
https://user-images.githubusercontent.com/16472151/107607952-9e188780-6c60-11eb-9623-effc5e300f43.mp4

```
import React, { useState } from 'react';
import CKEditor from '@ckeditor/ckeditor5-react';
import Editor from 'ckeditor5-custom-build/build/ckeditor';
const editorConfiguration = {
  toolbar: {
    items: [
      'heading',
      '|',
      'fontSize',
      'fontFamily',
      '|',
      'bold',
      'italic',
      '|',
      'alignment',
      '|',
      'numberedList',
      'bulletedList',
      '|',
      'indent',
      'outdent',
      '|',
      'link',
      'blockQuote',
      'imageUpload',
      'insertTable',
      'mediaEmbed',
      '|',
      'undo',
      'redo',
      'placeholder',
    ],
  },
  image: {
    toolbar: ['imageTextAlternative', 'imageStyle:full', 'imageStyle:side'],
  },
  table: {
    contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells'],
  },
  placeholderConfig: {
    types: ['Name', 'DOB'],
  },
};
const CKEditor = (props: CKEditorProps) => {
   const [content, setContent] = useState(props.value || '');
  return (
      <CKEditor
        editor={Editor}
        config={editorConfiguration}
        data={content}
        onChange={(event, editor) => {
          setContent(editor.getData());
          props.updateFormData(content);
        }}
        onInit={editor => {
          window.editor = editor;
        }}
      />
  );
};
export default CKEditor;
```

* Installed CKEditor plugins: 
Below are the plugins in custom-build
     "@ckeditor/ckeditor5-alignment": "^25.0.0",
    "@ckeditor/ckeditor5-autoformat": "^25.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^25.0.0",
    "@ckeditor/ckeditor5-block-quote": "^25.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^24.0.2",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^24.0.2",
    "@ckeditor/ckeditor5-editor-classic": "^25.0.0",
    "@ckeditor/ckeditor5-essentials": "^25.0.0",
    "@ckeditor/ckeditor5-font": "^25.0.0",
    "@ckeditor/ckeditor5-heading": "^25.0.0",
    "@ckeditor/ckeditor5-highlight": "^25.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^25.0.0",
    "@ckeditor/ckeditor5-image": "^25.0.0",
    "@ckeditor/ckeditor5-indent": "^25.0.0",
    "@ckeditor/ckeditor5-link": "^25.0.0",
    "@ckeditor/ckeditor5-list": "^25.0.0",
    "@ckeditor/ckeditor5-media-embed": "^25.0.0",
    "@ckeditor/ckeditor5-paragraph": "^25.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^25.0.0",
    "@ckeditor/ckeditor5-remove-format": "^25.0.0",
    "@ckeditor/ckeditor5-table": "^25.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^25.0.0",
    "@ckeditor/ckeditor5-typing": "^25.0.0",
    "@ckeditor/ckeditor5-core": "^25.0.0",
    "@ckeditor/ckeditor5-ui": "^25.0.0",
    "@ckeditor/ckeditor5-utils": "^25.0.0",
    "@ckeditor/ckeditor5-widget": "^25.0.0"
And, below are used in main application
   "@ckeditor/ckeditor5-react": "^3.0.0",
   "ckeditor5-custom-build": "file:./ckeditor5",
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ga987** [comment]
@Mgsy can you please go through the above and help me out

**Comment by Mgsy** [comment]
Hi, could you please describe your problem and the current behaviour, as I'm not sure if I understand your case properly?
