### ISSUE TITLE
Can't insert a nested table with paste

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9016]
## 📝 Provide detailed reproduction steps (if any)

1.  [Enable nested tables](https://github.com/ckeditor/ckeditor5/issues/3232#issuecomment-528251188).
2.  Insert a table.
3.  Copy it.
4.  Paste it to a cell.

### ✔️ Expected result

The table is pasted to the cell.

### ❌ Actual result

Only cells are pasted.

## 📃 Other details

I believe it happens because of our current implementation of pasting tables.

Related - #3232.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
We're currently implementing the same behavior that Word has. It's a bit unintuitive to me, but it makes a lot of sense.

**Comment by joannazinsli** [comment]
What does the resolution:invalid label mean? Should this item be open and not closed? I tested copy and pasting nested tables in MS Word, and they paste the copied nested table inside the cell. On the CKEditor demo https://ckeditor.com/ckeditor-5/demo/feature-rich/, the copied nested table pastes in any adjacent cells, losing the nested behavior. 
A workaround is to create an empty nested table and paste there, but that isn't expected.

**Comment by cbushmak** [comment]
> What does the resolution:invalid label mean? Should this item be open and not closed? I tested copy and pasting nested tables in MS Word, and they paste the copied nested table inside the cell. On the CKEditor demo https://ckeditor.com/ckeditor-5/demo/feature-rich/, the copied nested table pastes in any adjacent cells, losing the nested behavior. 

Agreed, I don't think this is resolved. Word only pastes the table inline when you have cells highlighted, otherwise it nests the table. And the workaround to create an empty nested table and paste there doesn't preserve any attributes that were on the table you pasted, like the class.
