### ISSUE TITLE
How to get clear html-free text of ClassicEditor?

### ISSUE THREAD

**Issue by gomanuke** [ckeditor/ckeditor5#9018]
ClassicEditor.getData() returns text with html code. It's useful (for e-mail sending) to get clear html-free text as it's visible in editor window.

Appreciate for project efforts.

**Comment by Mgsy** [comment]
Hi, you can use our [`viewToPlainText()`](https://stackoverflow.com/a/47569852/7280974) helper to get the content as plain text.

**Comment by gomanuke** [comment]
Appreciate for help. Factually my choice is var plainText = $(editorObj.getData()).text();
