### ISSUE TITLE
Highlight is removed after turning off the feature

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#9021]
## 📝 Provide detailed reproduction steps (if any)

1. Open the Highlight feature demo (https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html)
2. Focus the editor (or even clear the editable)
3. Click the `Highlight` toolbar icon (turn on)
4. Type `foo`.
5. Press `[Space]`
6. Click the `Highlight` icon once again (turn off)

### ✔️ Expected result

"foo" will be highlighted.

### ❌ Actual result

"foo" is not highlighted.

## 📃 Other details

The same scenario works fine with basic-styles or font features.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
It's by design although I'm not a huge fan of this either. There are other UX issues related to this (search for the label), maybe we can handle them all.

**Comment by Reinmar** [comment]
I definitely reported this in the past once.

For me, there's a use case for removing the highlight when you're inside it. Not when you're at its boundary.

**Comment by Reinmar** [comment]
DUP of #2616.
