### ISSUE TITLE
[Docs] Too much padding in Bootstrap example

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#903]
The top padding (inside the editable) looks like something was misplaced.

![image](https://user-images.githubusercontent.com/156149/37403309-a9ced404-278e-11e8-8d0b-9aa96f31a887.png)

**Comment by jodator** [comment]
AFAICS all headins in docs have a big padding:

![selection_005](https://user-images.githubusercontent.com/247363/37408170-d40e8644-279b-11e8-815b-848b31e184fe.png)

But here we have combo of heading margin:

![selection_006](https://user-images.githubusercontent.com/247363/37408212-e362b5a2-279b-11e8-8de0-d5f768cfac56.png)

and editable div paddings:
![selection_008](https://user-images.githubusercontent.com/247363/37408227-ea9a968c-279b-11e8-8537-ec01095fe508.png)
