### ISSUE TITLE
Special Characters plugin is not keyboard accessible

### ISSUE THREAD

**Issue by oatymart** [ckeditor/ckeditor5#9037]
## 📝 Provide detailed reproduction steps (if any)

1. Load a ClassicEditor with SpecialCharacters plugin
2. Move focus to the toolbar by keyboard
3. Move focus to the Special Characters toolbar button by keyboard
4. Activate button -> focus doesn't move inside the dropdown, so it's unusable by keyboard

### ✔️ Expected result

I can choose and insert a special character from the toolbar by keyboard only

### ❌ Actual result

Focus returns to the editable content and the dropdown is stuck open

## 📃 Other details

* Browser: Chrome 87
* OS: MacOS 10.15.7
* First affected CKEditor version: 22.0.0
* Installed CKEditor plugins: BlockQuote, Bold, Essentials, Font, Heading, Indent, IndentBlock, Italic, ListStyle, **SpecialCharacters**, **SpecialCharactersEssentials**, Strikethrough, Subscript, Superscript, Table, TableCellProperties, TableProperties, TableToolbar, Underline, WordCount,

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pradip1987** [comment]
Hi Team,
When can we expect the fix for this bug?

**Comment by pradip1987** [comment]
:+1:
