### ISSUE TITLE
Default font style is not written into the element style

### ISSUE THREAD

**Issue by 4lch3m1st** [ckeditor/ckeditor5#905]
🐞 Bug report

CKEditor 4.7

## 📋 Steps to reproduce

1. Do not select the any font style before writing into the ckeditor
2. Write something into the CKEditor -> Font style has been set to default -> OK
3. Check the element style with the dev tools ->Font style is empty

## ✅ Expected result
Font style should be added as style to the element
## ❎ Actual result
Font style is empty
## 📃 Other details that might be useful
Added screenshot from the issue
![element style is empty](https://user-images.githubusercontent.com/15000997/37407243-7e091d2e-2799-11e8-8240-6d07bb7740f0.png)

**Comment by Reinmar** [comment]
Hi! This is CKEditor 5's issue tracker. CKEditor 4's is here: https://github.com/ckeditor/ckeditor-dev/issues.
