### ISSUE TITLE
Building commands mentioned in build manual tests doesn't work

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9054]
## 📝 Provide detailed reproduction steps (if any)

Open http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.html manual test. There's following information:

![](https://user-images.githubusercontent.com/5353898/108478049-4b5c5280-7294-11eb-86b3-6cf1cbc074f5.png)

Both of given build approaches doesn't work.

### ✔️ Expected result

Documented commands should work.

### ❌ Actual result

Running `npm run build` returns `npm ERR! missing script: build` - because there's no such task in devops.

Running `./node_modules/.bin/webpack -w` ends with error `ERROR in Entry module not found: Error: Can't resolve './src' in 'C:\Development\htdocs\ckSource\ckeditor5\ckeditor5'`.

```
$ ./node_modules/.bin/webpack -w

webpack is watching the files…


Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 2bdd93db9fa7eb1245d7
Version: webpack 4.46.0
Time: 61ms
Built at: 02/19/2021 9:17:41 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve './src' in 'C:\Development\htdocs\ckSource\ckeditor5\ckeditor5'
```

## 📃 Other details

*   Browser: Any
*   OS: Win10 (not sure about others)
*   First affected CKEditor version: `master` branch @ 44e90bd

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
> Running npm run build returns npm ERR! missing script: build - because there's no such task in devops.

https://github.com/ckeditor/ckeditor5/blob/44e90bdaefcd1f3495bfd889dfcac949023dded2/packages/ckeditor5-build-classic/package.json#L74

👀

**Comment by mlewand** [comment]
Ok it doesn't mention that the commands should be executed in a given package rather than cke5 root :facepalm: I'll add this information the manual test description.
