### ISSUE TITLE
Paste from word / List - List not pasting

### ISSUE THREAD

**Issue by pdanno** [ckeditor/ckeditor5#9055]
Hey,

## 📝 Provide detailed reproduction steps (if any)

Here is a very basic list in a word document. Pasting it in the editor is impossible. 
The file : [List issue.docx](https://github.com/ckeditor/ckeditor5/files/6012340/List.issue.docx)

Screenshot of its content : 
<img width="400" alt="Screenshot 2021-02-19 at 19 53 47" src="https://user-images.githubusercontent.com/35064558/108549370-5db6aa80-72ed-11eb-8607-6b66bc6c38d7.png">

### ❌ Actual result

It's not pasting in my app, but it looks like it's not pasting in the demo editor in the "Paste from Word" documentation either. Same error I believe.

Screenshot from the Paste from word documention : 
![Screenshot 2021-02-19 at 20 02 51](https://user-images.githubusercontent.com/35064558/108549680-c6058c00-72ed-11eb-95a9-7f660021c0c9.png)

Screenshot from my app : 
![Screenshot 2021-02-19 at 20 07 02](https://user-images.githubusercontent.com/35064558/108550005-39a79900-72ee-11eb-9ea6-c6bf52064394.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It's very strange because I can reproduce this only with the file you linked. If I create my own list there is no way to trigger the error.

**Comment by pdanno** [comment]
I found an other occurence of the same bug. 
[List bug.docx](https://github.com/ckeditor/ckeditor5/files/6152030/List.bug.docx)


Different document, from a different client of mine. I changed the content (confidential) and deleted all the part that are pasting correctly. 

It looks like the bug comme from the first item of the list or the list itself.

**Comment by pomek** [comment]
Internal note: I removed the estimate in favor of #9954.
