### ISSUE TITLE
Question: how to transform image's url post edit?

### ISSUE THREAD

**Issue by lanyusan** [ckeditor/ckeditor5#9056]
I am testing ckeditor5 for a project. I have a use case where an article is first internal only, with image urls being internal url. When the article is published to public site, the images will be copied to public server and the url will be changed.

I need to have a way to iterate all img tag to convert the url. Text based replace is problematic.

Does CKEdtior have some API that is detached from editing ui but can be used to transform the model?

Thanks in advance.

**Comment by Mgsy** [comment]
Hi! You can use [`TreeWalker`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_treewalker-TreeWalker.html) on the root to iterate over all elements in the document, filter `<image>` element and use [Writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html) to change its model `src` attribute.

**Comment by lanyusan** [comment]
Thanks for the advice.

**Comment by topskishan** [comment]
> Hi! You can use [`TreeWalker`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_treewalker-TreeWalker.html) on the root to iterate over all elements in the document, filter `<image>` element and use [Writer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html) to change its model `src` attribute.

can you please add more explaination or snippet.
