### ISSUE TITLE
Online buider generates invalid html on index.html sample file

### ISSUE THREAD

**Issue by sophisma** [ckeditor/ckeditor5#9059]
I generated a build using the online builder and the file index.html on the sample folder contains invalid html.

A valid html document must have the following structure:

```
<html>
<head></head>
<body></body>
</html>
```

But the generated page has the following structure:

```
<html></html>
<head></head>
<body></body>

```

**Comment by pomek** [comment]
The source file (`sample.pug`) misses proper indentations for everything inside the `<HTML>` tag.

**Comment by ma2ciek** [comment]
Thanks for reporting it. The issue will be fixed along with the upcoming CKEditor 5 release.
