### ISSUE TITLE
[Firefox] Link highlight when selection has removed italic attribute have visible gap

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#906]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Go to Classic Editor example.
2. Add link to `things` make it bold and italic.
3. Unset italic.

## ✅ Expected result

Link highlight is OK.

## ❎ Actual result

Link highlight has a visible gap.

## 📃 Other details that might be useful

Works on Chrome.

Step 2:
![selection_010](https://user-images.githubusercontent.com/247363/37408680-dee47398-279c-11e8-87bf-057e0a761113.png)

Step 3:
![selection_009](https://user-images.githubusercontent.com/247363/37408694-e6d437aa-279c-11e8-9cfc-0efe94533ed0.png)

**Comment by dkonopka** [comment]
Can't reproduce it  🤔 `Firefox version 59.0`

### Retina
<img width="263" alt="screen shot 2018-03-15 at 14 06 24" src="https://user-images.githubusercontent.com/10219857/37464948-24f3b6f6-285a-11e8-8d49-62801c8879d8.png">

### Full HD
![screen shot 2018-03-15 at 14 08 52](https://user-images.githubusercontent.com/10219857/37465113-9c68779e-285a-11e8-981a-576b11633565.png)

**Comment by jodator** [comment]
@dkonopka did you check that on docs or in the manual tests?

**Comment by jodator** [comment]
![screencast 2018-03-15 14_28_41](https://user-images.githubusercontent.com/247363/37466106-3df5620a-285d-11e8-8af8-9659529eb590.gif)

**Comment by dkonopka** [comment]
I was checking manual tests :) Anyway, it's still OK on [docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html): 
### Retina:
![link-gap-ff](https://user-images.githubusercontent.com/10219857/37467076-9b623b8c-285f-11e8-96bf-75cf087c3511.gif)

### Non-retina:
![link-gap-hd](https://user-images.githubusercontent.com/10219857/37467141-c60b43a6-285f-11e8-9673-5554834bc27d.gif)

As I can see you are on Windows, right?

**Comment by jodator** [comment]
@dkonopka never! ;) I'm on Linux Mint (Ubuntu) - FF: 58.0.2 (64-bit). I'll check on 59 then when it comes live.

**Comment by oleq** [comment]
Do you think this has anything to do with the phenomenon I mentioned in this comment https://github.com/ckeditor/ckeditor5-theme-lark/issues/159#issuecomment-373337909?

**Comment by jodator** [comment]
Hard to say but it is probably different case. The comment one looks like the outline overlaps selection background. Here I see that when the selection splits the text node it gets different dimensions then outline.

**Comment by jodator** [comment]
@dkonopka: The same on FF 59 unfortunately.

![selection_038](https://user-images.githubusercontent.com/247363/37672964-5d044d3a-2c6f-11e8-9e83-5cf94a453043.png)

**Comment by oleq** [comment]
I couldn't reproduce it on Mac/Windows. 

Because 
1. the popularity of Linux+Firefox environment is negligible,
2. this issue is but a minor annoyance, 
3. there's no quick fix,

I'd rather not spend time on it now.

**Comment by jodator** [comment]
Does not occur on current master & Firefox 59.0.2 (64-bit).

It was probably fixed by changes in how link highlight was rendered.
