### ISSUE TITLE
Missing Autosave Plugin needs to error

### ISSUE THREAD

**Issue by archonic** [ckeditor/ckeditor5#9072]
## 📝 Provide detailed reproduction steps (if any)

1. Have a super build with Classic and Decoupled
2. Omit the Autosave plugin from Classic
3. Attempt to use autosave with the Classic editor keeping everything else the same

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ There should be at least a console error saying that the autosave plugin is missing.

_What is the actual result of the above steps?_

There is no error at all. In fact, the status indicator will turn yellow and green still, as if saving is occurring. When combined with collaboration, it behaves exactly as if everything is working. You would have to notice the lack of network traffic while typing or come back many hours later to see that the data has vanished after collaborative services is no longer storing that document. The root issue (omitting the Autosave plugin) was my fault, but the lack of error and other behaviour here led to loss of data for clients.

## 📃 Other details

* Browser: All
* OS: All
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Everything in Classic + Decoupled default + Autosave

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, thank you for the report. I'm sorry to hear about the content loss. However, please note that the Autosave plugin is not required by the editor, as it's only an [option for saving the content](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html). Some users implement a custom saving mechanism and they won't be using Autosave, so we can't require this plugin by default. 

You can try to implement a custom validation mechanism on your page, for example:

```javascript
const autosaveConfig = editor.config.get( 'autosave' );

if ( !autosaveConfig ) {
	alert( 'Missing the Autosave configuration.' );
}
```

Apart from that, as you're using our commercial solutions (real-time collaboration), I'd recommend reaching us through the [support channel](https://ckeditor.com/contact/), our dedicated support team will do their best to help you in solving your issues.

**Comment by archonic** [comment]
I'm certainly not asking that the plugin be included by default. I think your solution there to manually check for the plugin will work. That might make sense to add to the docs. Thanks.
