### ISSUE TITLE
Unable to paste image from Word

### ISSUE THREAD

**Issue by Absolutely17** [ckeditor/ckeditor5#9077]
## 📝 Provide detailed reproduction steps (if any)

1. Copy text with image from Word document [Example.docx](https://github.com/ckeditor/ckeditor5/files/6028901/Example.docx)
2. Paste in CKEditor5

### ✔️ Expected result

The image was uploaded to the server and displayed on the page.

### ❌ Actual result

Error in console:
`Not allowed to load local resource: file:///C:/Temp/msohtmlclip1/01/clip_image002.png`
and no picture
## 📃 Other details

* Browser: Chrome 88
* OS: Windows 10
* First affected CKEditor version: CKEditor5 25.0
* Installed CKEditor plugins: Build-classic + Alignment

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It looks like [issue that is already being tracked here](https://github.com/ckeditor/ckeditor5/issues/2493). Feel free to add there any information you find important and meanwhile I'll close this ticket as a duplicate.
