### ISSUE TITLE
Catastrophic failure when deleting pasted image

### ISSUE THREAD

**Issue by luisvaldez** [ckeditor/ckeditor5#9079]
## 📝 Provide detailed reproduction steps (if any)

1. Copy an image from Photoshop
2. Paste onto editor
3. Try to delete it

I'm using the simpleUpload plugin to upload the results to an endpoing on my website that saves the image and returns a URL, which it does without a problem.
In fact, the website displays the image correctly without any issues.
The only problem is trying to delete them.
If I use a URL or a local file to upload the very same image, there is no issues with it at all.

### ✔️ Expected result

It should just delete the image.

### ❌ Actual result

TypeError: Cannot read property 'is' of undefined
    at nm.findPositionIn (ckeditor.js:5)
    at nm.on.priority (ckeditor.js:5)
    at nm.fire (ckeditor.js:5)
    at nm.toViewPosition (ckeditor.js:5)
    at rm.uN (ckeditor.js:5)
    at rm.fire (ckeditor.js:5)
    at rm._testAndFire (ckeditor.js:5)
    at rm._convertInsertWithAttributes (ckeditor.js:5)
    at rm.convertInsert (ckeditor.js:5)
    at ig.toView (ckeditor.js:5) "An error happened during restoring editor data. Editor will be restored from the previously saved data."

## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* First affected CKEditor version: 25.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by luisvaldez** [comment]
Found out that it happens whenever the images aren't inside a P tag.
<p><figure class=\"image image-style-align-right\"><img src=\"https://www.luisvaldez.co.uk/Blog/Articles/9/Images/03bcf647fc85449a84d1bda60e131ae5.png\"></figure></p>
is deletable
<figure class=\"image image-style-align-right\"><img src=\"https://www.luisvaldez.co.uk/Blog/Articles/9/Images/03bcf647fc85449a84d1bda60e131ae5.png\"></figure> not so much...

**Comment by LukaszGudel** [comment]
Hello, thank you for the report. Unfortunately I can not reproduce this issue. 

Could you check if you are able to get this bug in [our documentation page](https://ckeditor.com/docs/ckeditor5/latest/features/image.html)? 

Also, are you using any custom code that is modifying  `<p>` and `<figure>` tags behaviour?
