### ISSUE TITLE
Korean can't properly typing after using twice keydown space bar(&nbsp;)

### ISSUE THREAD

**Issue by jongjunpark** [ckeditor/ckeditor5#9081]
## 📝 Provide detailed reproduction steps (if any)

1. Create Classic CKEditor 5 at REACT
2. twice Space-bar (maybe insert "\&nbsp;" in editor)
3. typing Korean
### ✔️ Expected result

<img width="350" alt="스크린샷 2021-02-24 오후 1 24 26" src="https://user-images.githubusercontent.com/60080679/108947336-a088d180-76a3-11eb-9373-773e5f0680b8.png">

### ❌ Actual result

<img width="350" alt="스크린샷 2021-02-24 오후 1 24 57" src="https://user-images.githubusercontent.com/60080679/108947383-b26a7480-76a3-11eb-97d7-4c47bfc1c8cd.png">

## 📃 Other details

* Browser: Chrome, Edge
* OS: Any
* First affected CKEditor version: 25.0.0
* Installed CKEditor plugins: editor-classic

---

I checked the CKEditor4.
it works very well in same condition.
so I checked html tag by inspection

in CKEditor4
![화면-기록-2021-02-24-오후-2 49 20](https://user-images.githubusercontent.com/60080679/108954468-34f93100-76b0-11eb-9f65-819f6922560f.gif)

in CKEditor5
![화면-기록-2021-02-24-오후-2 51 43](https://user-images.githubusercontent.com/60080679/108954631-738eeb80-76b0-11eb-9d66-55956eca7b7b.gif)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Isn't it the same issue as here: https://github.com/ckeditor/ckeditor5/issues/8031 ?

**Comment by jongjunpark** [comment]
Thanks, I didn't found that. now, I checked.

**Comment by FilipTokarski** [comment]
Ok, I'll close this one as a duplicante then.
