### ISSUE TITLE
CKEditor5 Plugins are not installing as expected

### ISSUE THREAD

**Issue by JasonDunbar** [ckeditor/ckeditor5#9082]
## 📝 Provide detailed reproduction steps (if any)

1. Fork the CKEditor5 repo.
2. Clone the repo to my desktop using `git clone -b stable https://github.com/<MyGithubUsername>/ckeditor5.git`
3. Navigate to the build directory `cd D:\_source\ckeditor5\packages\ckeditor5-build-classic`
4. Run `npm install`
5. I install the Font plug in to use it in this build: `npm install --save-dev @ckeditor5/ckeditor5-font`
6. I then update the build configuration by adding to `src/ckeditor.js`:
  - `import Font from '@ckeditor/ckeditor5-font/src/font';`
  - `ClassicEditor.builtinPlugins = [ ..., Font]`
  - `ClassicEditor.defaultConfig = { toolbar: { items: [' ..., fontColor, fontBackgroundColor'] } }`

7. At this point, the guide says you should run yarn run build, but i can't get Yarn to work in this dev environment for love nor money, so instead I use `npm run build`
8. I test the build by opening `sample/index.html` in the browser and it looks fine; the Font plugin is loaded and the toolbar items appear.
9. I then use Git to stage the changes, then I Commit and Push to my cloned repository.
10. In the Nodejs project where I want to use ckeditor, I install the custom build using `npm install <MyGithubUsername>/ckeditor5#stable` 
11. To the project I add `import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';`

### ✔️ Expected result

The CKEditor instance appears with the Font toolbar elements visible and usable.

### ❌ Actual result

The editor appears as you would expect it to, but without the Font plug in. 

Back over in the CKEditor local repo, when I take a look at the `D:\_source\ckeditor5\packages\ckeditor5-build-classic\build\ckeditor.js.map` and search for **ckeditor5-font** I find many instances of it, indicating that it has indeed included it into the build. When I look at the same file in my Nodejs project `D:\_source\NodeJsProject\node_modules\@ckeditor\ckeditor5-build-classic\build\ckeditor.js.map` there's no sign of `ckeditor5-font;`. The sample.html in the NodeJS project works, but does not show the Font additions, nor do they show in the implementation in my project.

## 📃 Other details

* Browser: MS Edge Version 88.0.705.74 (Official build) (64-bit)
* OS: Win10 20H2
* Language: Typescript
* NodeJS version used to build CKEditor: 14.6.0
* NodeJS version used in project: 10.22.0 (latest supported version of SPFx tooling/scaffolding)
* First affected CKEditor version: CKEditor 5
* Installed CKEditor plugins: Font

**Comment by LukaszGudel** [comment]
Hello, thank you for adding an issue and providing very detailed reproduction steps. Looks like it's not a bug but an incorrect import path in step 11. When you installing your repo as npm package then it has a little different path in node_modules folder. 

You should import it as: `import ClassicEditor from 'ckeditor5/packages/ckeditor5-build-classic/build/ckeditor';`

During the installation process it also installs `@ckeditor/ckeditor5-build-classic` package in your node.js project as one of the subdependencies and thus you are able to import editor build from this package but it will not have any custom plugins that you have added.

You can easily verify the above by creating an empty npm project and installing your forked repo only (step 10). Then navigate to node_modules folder and you should find both `@ckeditor` folder with official packages and `ckeditor5` folder will all the files from your forked repo.

Additionally, I can recommend you to use our [online builder tool](https://ckeditor.com/ckeditor-5/online-builder/). You will be able to download ready-to-use editor with needed plugins and there is also a similar file structure like in `/ckeditor5-build-classic` folder where you can fine-tune your editor build and it should reduce install times and weight of your project.

Please, let me know if this fixes your issue.
