### ISSUE TITLE
[Table Caption] Handle all caption conversions

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9084]

**Comment by maxbarnas** [comment]
I came across an interesting case:

```html
<figure class="table">
	<figcaption>Caption A</figcaption>
	<table>
		<caption>Caption B</figcaption>
		...
	</table>
</figure>
```

Browsers treat both captions in an expected way: as separate paragraphs.

What would be our approach to this? 
1. Merge them into a single `caption` model data (possibly as two paragraphs inside caption element),
2. Ignore the `table > caption` when `figure > figcaption + table` is present,
3. Something else?

CKE4 seems to not handle `figure > figcaption` at all, transforming it to a regular paragraph while showing properly `table > caption`.

CC: @Mgsy @Reinmar @niegowski

**Comment by Reinmar** [comment]
IMO, a case with two captions could be extracted to a followup. For now, we should be fine if we support one caption: `table > caption` (for compat reasons) and `figure > figcaption + table` (because it's the desired output anyway).
