### ISSUE TITLE
All builds include the ImageUpload plugin twice

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#909]
It's duplicated in the `build-config.js`.

Fortunately, everything seems to work fine :)

**Comment by pomek** [comment]
- https://github.com/ckeditor/ckeditor5-build-classic/pull/43
- https://github.com/ckeditor/ckeditor5-build-inline/pull/9
- https://github.com/ckeditor/ckeditor5-build-balloon/pull/17

If the PRs listed above will be merged, this ticket can be closed.

**Comment by Reinmar** [comment]
Thanks!
