### ISSUE TITLE
Styling artifact in placeholder sample

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9096]
## 📝 Provide a description of requested docs changes

1.  Open `/features/editor-placeholder.html` (on master)
2.  Clear the editor.
3.  Place a heading 2.

## Actual

The placeholder text goes to the left side of the caret.

![](https://i.imgur.com/wxI9HqN.gif)

**Comment by Reinmar** [comment]
DUP of #9091.
