### ISSUE TITLE
The feature tour balloon does not disappear upon clicking the toolbar button in Safari/iOS

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9098]
## 📝 Provide detailed reproduction steps (if any)

https://user-images.githubusercontent.com/1099479/109032295-cb841d00-76c5-11eb-86d1-c739cedf73bb.mov

### ✔️ Expected result

The balloon should be gone forever after the first tap.

### ❌ Actual result

It keeps reapearing.

## 📃 Other details

*   Browser: Safari
*   OS: iOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Also, because of this, you need to tap multiple times to execute the command via the button.

**Comment by Reinmar** [comment]
Related issue: #9100..

**Comment by AnnaTomanek** [comment]
The fix should be merged to the `stable` branch.

**Comment by AnnaTomanek** [comment]
@ckeditor/qa-team Can you check this on iOS, please?

**Comment by LukaszGudel** [comment]
I've added a comment to the PR. It seems to work correctly now.
