### ISSUE TITLE
The strikethrough icon is intriguing

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#910]
Bold, Italic, Underline, Strikethrough = B, I, U, S

![screen shot 2018-03-15 at 15 37 37](https://user-images.githubusercontent.com/545175/37470007-db702bf6-2866-11e8-87bf-ee7d6beba75f.png)

T?

Now let's check CKEditor 4...

![screen shot 2018-03-15 at 15 39 16](https://user-images.githubusercontent.com/545175/37470098-0c9baa70-2867-11e8-8e63-b2d4c44f2cfe.png)

T is already used for removing formatting.

Even if T is used in some applications for striked text (though I find S to be more common, see. e.g. Google Docs), I believe that having an older editor where T was used for a completely different purpose is quite an important factor we should consider when offering UI to the end users.

**Comment by wwalc** [comment]
Related: #908

**Comment by oleq** [comment]
The problem with the letter "S" is that when crossed, it starts looking complex. It's hard to tell what it represents unless the actual shape of the letter is much thicker than the line used to cross it (v4). This, however, is impossible with our current icon styles because a thick line is reserved exclusively for bold.

So in the process of refactoring the theme, we decided to go with "T" which is:
* much simpler as a shape,
* orthogonal to the "crossing line",
* also used in some applications.

**Comment by scofalik** [comment]
Maybe it is more complex, but on the other hand, it is something that everyone is used to and everyone seeks it.

> It's hard to tell what it represents

I don't get it. Everyone knows a crossed letter when they see it. Unless the whole shape starts to look like something else and makes you wonder, like with crossed "T" we have now.

> unless the actual shape of the letter is much thicker than the line used to cross it

Maybe, probably yes. Maybe we could add some little spacing between the crossing line and the letter? So the line does not touch the letter.

> ("T" is) much simpler as a shape

T is not much simpler as a shape. Everything, when crossed, will get "complex".  "I" crossed would be quite a simple shape, and still you would have no clue what the heck this "plus symbol" is doing there. It can be complex, as long as it conveys the message. The current solution is less complex but gives you no clue.

Please, let's have a discussion about it, cause I find current button disturbing and it appeared that it's not only me.

**Comment by jodator** [comment]
I've just checked the LibreOffice:

![selection_027](https://user-images.githubusercontent.com/247363/37516356-1b78d26e-290e-11e8-933c-30fb5ed01e7e.png)

it looks there's not ideal solution :) But I think that as we go with feature -> icon the expected would be `S` for strikethrough not the `T`.

But OTOH I can get that striked `S` might be uglier then `T` (but I heaven't seen them).

**Comment by scofalik** [comment]
I like LibreOffice solution because for every option there's the same letter, so you can deduce the effects by comparing buttons when they are next to each other. I hope you know what I mean. You can easily see there's bold, italic and underline (these are easy) and you can see that there's "a" on the next button and you can see it is stroked.

**Comment by scofalik** [comment]
BTW. Google Docs does something in a vein of what I suggested:

![image](https://user-images.githubusercontent.com/1502228/37517352-6f12461e-2911-11e8-872a-0b3a8478b4d4.png)

But they did spacing above and below the line. I was thinking about spacing on the edges of S letter.

**Comment by wwalc** [comment]
In case anyone was curious how remove formatting looks like in Google Docs:

![screen shot 2018-03-20 at 14 07 57](https://user-images.githubusercontent.com/545175/37656400-3c225200-2c48-11e8-8b81-c529162ea2e8.png)

**Comment by oleq** [comment]
@wwalc Just in case: https://github.com/ckeditor/ckeditor5/issues/908

**Comment by wwalc** [comment]
> @wwalc Just in case: #908

Yeah, I know, I linked to that ticket already: https://github.com/ckeditor/ckeditor5/issues/910#issuecomment-373406783
My intention was to show that Google Docs uses a very similar button for a completely different purpose.

**Comment by Reinmar** [comment]
We need a decision here and I have to say that the problems with a crossed "T" letter are pretty big. @oleq and @dkonopka, could we see how an "S" would do?

**Comment by dkonopka** [comment]
It was "S" (not polished at all) before "T": https://github.com/ckeditor/ckeditor5-basic-styles/blob/39cbe97a326ff3157770747a33048d664c4fdec1/theme/icons/strikethrough.svg.

<img width="988" alt="screen shot 2018-03-27 at 15 48 24" src="https://user-images.githubusercontent.com/10219857/37971518-68e2be18-31d6-11e8-86f6-e93e388975e9.png">

But Szymon good mentioned Google Docs sample, we can try to get rid of the bottom spacing in crossing line, I'll try that and propose something.

**Comment by dkonopka** [comment]
Rounded style, 1,5px of thickness (like all icon set) + 1,5px height of crossing line (same as in underline):

### ~S~ "single spaced"
![single-space](https://user-images.githubusercontent.com/10219857/38019346-9f0dd27e-3277-11e8-9d6e-0954f2b36189.png)

### ~S~ with spacing below crossing line
![both-spaces](https://user-images.githubusercontent.com/10219857/38019367-a6532dd6-3277-11e8-8ec9-19dc93d6bf4d.png)

I would keep it simple and go with "single-spaced" icon.

**Comment by wwalc** [comment]
Love it already, any of the options above.

**Comment by scofalik** [comment]
Could we try an option that has vertical spacing, not a horizontal one? So the "S" shape is kept together? Though it could look like the strike is "behind" a letter, but maybe it would be more readable?

Also, we could try with less "curvy" S (so together with strikethrough it does not look like 8 or link icon).

**Comment by dkonopka** [comment]
@scofalik Idea of the strike "behind" a letter is good, but the icon is too small to show details and keep spacings. About less curvy S letter - [take a look at the proposal](https://github.com/ckeditor/ckeditor5/issues/910#issuecomment-376542959), it's not fitting to the current icon set in v5.
<img width="857" alt="screen shot 2018-03-28 at 14 27 52" src="https://user-images.githubusercontent.com/10219857/38028803-4b706fce-3294-11e8-96a2-fc66d4b4255b.png">

Anyway, let's wait for more feedback.

**Comment by scofalik** [comment]
It seems a bit out of place this way. I imagined it differently. And the spacing would have to be, you know, in a shape of S letter. Now, these are just two dashes. But I don't know if it would be better.

**Comment by Reinmar** [comment]
> Love it already, any of the options above.

Agree. Although, IMO the line is a bit too low. In the last proposal (https://github.com/ckeditor/ckeditor5/issues/910#issuecomment-376877029) it seems to be higher.

**Comment by dkonopka** [comment]
Yep, there was a difference with strike line, so here is 1px higher:
![strike-1px-higher](https://user-images.githubusercontent.com/10219857/38073760-aca114ae-332c-11e8-8aa4-ac059ba033c0.png)

**Comment by oleq** [comment]
How about something like this:

<img width="420" alt="screen shot 2018-03-29 at 12 36 48" src="https://user-images.githubusercontent.com/1099479/38084628-ec47ae8a-334d-11e8-973a-4a718904eed9.png">
<img width="552" alt="screen shot 2018-03-29 at 12 36 58" src="https://user-images.githubusercontent.com/1099479/38084629-ec7b66d0-334d-11e8-9198-9fdbb6272a86.png">

**Comment by Reinmar** [comment]
Even better. It's not only clear (although... I think that it's slightly less clear than @dkonopka's proposal above) and well shaped now, but additionally – it looks fresh.

**Comment by pjasiun** [comment]
> How about something like this:

In this icon "S" is above "–". I believe this is not how strikethrough works.

**Comment by Reinmar** [comment]
In the same way as chain's link doesn't look like a pill with a dash inside from any angle. This is a pictogram and the question is whether S over a line is clear to potential users. I certainly agree that it's further from reality than when a line is "over" the S, though. But, for me, the advantage of Olek's proposal is its lightness and freshness. The question is whether the icon still remains clear enough.

**Comment by wwalc** [comment]
Actually with `text-decoration-skip` striked text may look exactly this way.

**Comment by scofalik** [comment]
> But, for me, the advantage of Olek's proposal is its ( ... ) freshness.

Maybe a vertical line then? $

Just :trollface:. TBH, this is how I've seen it, Olek. I am not sure if it conveys the message, though :(.

**Comment by dkonopka** [comment]
So to sum up we have two proposals: the modern way and default strikethrough icon. 
Please give some 👍what do you prefer. 

### Default strikethrought icon
![default-s-icon](https://user-images.githubusercontent.com/10219857/38864867-55608570-423c-11e8-95fc-7f2c996808ea.png)

**Comment by dkonopka** [comment]
### Modern strikethrough icon

![modern-s-icon](https://user-images.githubusercontent.com/10219857/38864876-60d79a42-423c-11e8-8f8f-591c1f0181e3.png)

**Comment by scofalik** [comment]
I proposed the "modern" on and voted for "default", so I guess it tells a lot :)

**Comment by wwalc** [comment]
![image](https://user-images.githubusercontent.com/545175/38865024-e4fbf25a-423c-11e8-9755-0103f3b45640.png)

**Comment by Reinmar** [comment]
I guess we have a winner :D @dkonopka, could you create a PR so we can still close it in this iteration?
