### ISSUE TITLE
Feature tour balloon briefly visible when using a button on touch device

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9100]
## 📝 Provide detailed reproduction steps (if any)

1.  Open font styles demo.
2.  Focus the editor (so that the balloon disapears).
3.  Long press font size toolbar button.

### ✔️ Expected result

Tour balloon is not shown.

### ❌ Actual result

https://user-images.githubusercontent.com/5353898/109044689-fde84700-76d2-11eb-9b78-1621fa715acf.mp4

Balloon does show up. It occurred to me during a regular use, because even "normal" button presses show the balloon very briefly (as you can see later).

## 📃 Other details

*   Browser: Chrome
*   OS: Android

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Related issue: #9098.

**Comment by oleq** [comment]
Looks like a DUP of #9098 to me.
