### ISSUE TITLE
Rename isImage() helper to avoid confusion

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9103]
For backwards compatibility we decided to preserve the `image` element in the model for block images. This is OK (see my last comment) But we also left the `isImage()` helper untouched, which is now confusing as there are two helpers next to each other `isImage()` and `isImageInline()`.

The former suggests it checks both types of images, which is not true. We should at least rename `isImage()` to `isImageBlock()`, or even better: `isBlockImage()` (also `isImageInline()` -> `isInlineImage()`).

The next step would be renaming the `image` in the model to `imageBlock` so it corresponds to `imageInline` but this should be further discussed because this will increase an already vast scope of breaking changes in this feature.

**Comment by magda-chrzescian** [comment]
@oleq WDYT about keeping the `insertImage` helper and returning the `true` for both inline and block images and adding the new `isBlockImage` function for only the block images?
ATM we are mostly using the `isImage( element ) || isImageInline( element )` construction, so it would be nice to cover that with only one helper.

**Comment by oleq** [comment]
It comes down to figuring out how many times the helpers will be used:

*   How many times `isImage()` (returning `true` for both) will be used when implemented like this?
*   How many times `isBlockImage()` will be used when implemented?

**Comment by magda-chrzescian** [comment]
> How many times isImage() (returning true for both) will be used when implemented like this?

8 times

> How many times isBlockImage() will be used when implemented?

4 times

IMO we need both.

**Comment by oleq** [comment]
Let's have both then! :)

**Comment by magda-chrzescian** [comment]
I updated the estimate because we decided to move part of the task here: #9246

**Comment by oleq** [comment]
Closed in #9247.
