### ISSUE TITLE
[Table Caption] Update table-related algorithms

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9105]
1. Handle double captions in cases such as:
	1. Both `figure > table + figcaption` and `table > caption` are present - a followup to https://github.com/ckeditor/ckeditor5/issues/9084#issuecomment-788011456.
	2. Due to a live collaboration two captions might be added to the model.
1. Column insertion throws error. 
1. The <kbd>Tab</kbd>-ing from table cell to caption throws an error.

**Comment by niegowski** [comment]
Closed in #9209
