### ISSUE TITLE
Inline images overlap when inserted next to each other (styles)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9108]
![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/02c2be8c-a488-4951-8a6a-5b094d289b77)

**Comment by magda-chrzescian** [comment]
We can fix the problem by adding `z-index: 1` property to the `image-inline ck-widget_selected` selector.
Then inserting images right next to each other could be allowed. Especially that the distance between them can be easily set with the space button.
![Mar-05-2021 17-01-21.gif](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/76fe3bd1-d3ee-48b5-83c9-f35b815a98cc)

**Comment by magda-chrzescian** [comment]
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/e199a6a2-e24c-4cbe-bc81-a9e1ad7ab6d3) 

A similar problem occurs if an inline image is placed at the bottom of the editor.

**Comment by oleq** [comment]
> A similar problem occurs if an inline image is placed at the bottom of the editor.

But this one needs some margin to be addressed?

**Comment by magda-chrzescian** [comment]
@oleq Actually, it is addressed in #8991, so no need to explore this in this task.

**Comment by oleq** [comment]
Closed in #9186.
