### ISSUE TITLE
Error is occurred between mathtype and codeblock.

### ISSUE THREAD

**Issue by jongjunpark** [ckeditor/ckeditor5#9115]
## 📝 Provide detailed reproduction steps (if any)

1. Create Classic CKEditor 5 at REACT
2. Add plugin (Mathtype, Codeblock)
3. add mathtype code then switch codeblock next to the mathtype code
    or add codeblock then add mathtype code in codeblock

### ✔️ Expected result

mathtype code is correctly embedded in codeblock

### ❌ Actual result

1. add mathtype code then switch codeblock next to the mathtype code.
![화면-기록-2021-02-26-오전-11 54 26](https://user-images.githubusercontent.com/60080679/109248890-0737f780-782a-11eb-9103-c8b2c4ec87ec.gif)
error is occurred then can't use browser (below image is error massage)
<img width="673" alt="스크린샷 2021-02-26 오전 11 52 50" src="https://user-images.githubusercontent.com/60080679/109248442-2aae7280-7829-11eb-8c54-ea43eb7c5561.png">

2. add codeblock then add mathtype code in codeblock
![화면-기록-2021-02-26-오전-11 56 08](https://user-images.githubusercontent.com/60080679/109248997-364e6900-782a-11eb-8a51-865ccb561d97.gif)
it can't insert mathtype code in codeblock and create some blue border.

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: 25.0.0
* Installed CKEditor plugins: editor-classic, mathtype, codeblock

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Thanks for the report. This is a known issue, however, please note that MathType integration is not handled by our team, but Wiris. It's already reported in the integration repository, so you can track the progress there - wiris/html-integrations#13.
