### ISSUE TITLE
Can't disabled plugin using "addChildCheck"

### ISSUE THREAD

**Issue by jongjunpark** [ckeditor/ckeditor5#9118]
## 📝 Provide detailed reproduction steps (if any)

1. Create Classic CKEditor 5 at REACT
2. Add plugin (Blockquote, Codeblock, Mathtype)
3. create addChildCheck Function with plugin
```
// Blockquote plugin
schema.addChildCheck( ( ctx, childDef ) => {
	if ( ctx.endsWith( 'blockQuote' ) && childDef.name == 'image' ) {
		return false;
	}
        if ( ctx.endsWith( 'blockQuote' ) && childDef.name == 'mathml' ) {
		return false;
	}
}

// Codeblock plugin
schema.addChildCheck( ( ctx, childDef ) => {
	if ( ctx.endsWith( 'codeBlock' ) && childDef.name == 'image' ) {
		return false;
	}
        if ( ctx.endsWith( 'codeBlock' ) && childDef.name == 'mathml' ) {
		return false;
	}
}
```

### ✔️ Expected result

disabled plugin like this
<img width="45" alt="스크린샷 2021-02-26 오후 5 06 21" src="https://user-images.githubusercontent.com/60080679/109272997-f5b81500-7854-11eb-99c9-68f38ca042b1.png">

### ❌ Actual result

blockQuote can be changed image plugin to "disabled".
However, codeBlock, heading1, heading2 can't be changed image, table plugin to "disabled".
Also, All Plugin can't be changed mathtype plugin. how can be change this?

## 📃 Other details

* Browser: Ant
* OS: Any
* First affected CKEditor version: 25.0.0
* Installed CKEditor plugins: editor-classic, mathtype, codeblock, 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. If I understood correctly - if you just want to disable specific commands based on where the actual selection is, you can use code like this:
```js
const selection = editor.model.document.selection;
const document = editor.model.document;

// add here any commands that you need
const imageUploadCommand = editor.commands.get( 'imageUpload' );
const mathTypeCommand = editor.commands.get( 'MathType' );
const chemTypeCommand = editor.commands.get( 'ChemType' );

document.on( 'change', event => {
    for( const block of selection.getSelectedBlocks() ) {
                
        if( block.parent.name === 'blockQuote' || block.name === 'codeBlock' ) {
             imageUploadCommand.forceDisabled();
             mathTypeCommand.forceDisabled();
             chemTypeCommand.forceDisabled();
        } else {
            imageUploadCommand.clearForceDisabled();
            mathTypeCommand.clearForceDisabled();
            chemTypeCommand.clearForceDisabled();
        }
    }
} );
```
This way if anything inside the editor changes, the code checks if the current selection is inside `blockQuote` or `codeBlock`. If this is true, it disables the commands that you specified.
  
Here you can read more about:
- [document selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html)
- [document](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html)
- [command](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html)
- [command collection](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_commandcollection-CommandCollection.html)
  
Let me know if this will be enough for you use case.

**Comment by jongjunpark** [comment]
thanks, i can solve this problem by this way.
