### ISSUE TITLE
Buttons are not rounded in the document editor example

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#912]
![image](https://user-images.githubusercontent.com/156149/37490048-d316fcc2-2899-11e8-89d3-89d2c8bd5f8c.png)

They are fine elsewhere:

![image](https://user-images.githubusercontent.com/156149/37490058-e0fec018-2899-11e8-8dcb-b629d4f94b61.png)

**Comment by Reinmar** [comment]
BTW, it's the same about the tooltip.

**Comment by oleq** [comment]
All we need is `ck-rounded-corners` class added to `<div class="document-editor">...</div>`.

**Comment by Reinmar** [comment]
That's: ;/

Why doesn't toolbar work out of the box there?

**Comment by oleq** [comment]
Because I forgot to add this class when implementing this editor? :P

**Comment by Reinmar** [comment]
OK, from your reply I thought that this is how it's expected to be.
