### ISSUE TITLE
Rethink the (image) caption icon

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9121]
## Provide a description of the task

The icon I proposed in #9090

*   feels "heavy",
*   will not work for other features (such as tables).

We must come up with something better.

Related to #3204.

![](https://user-images.githubusercontent.com/1099479/109291745-a1e40680-7829-11eb-8a65-4bf1bd72a813.png)

**Comment by magda-chrzescian** [comment]
I tried to make it compatible with both the image style buttons and the table buttons which are significantly different (maybe we could improve these a bit?).

@oleq @niegowski would you share your opinion?

![](https://user-images.githubusercontent.com/14334820/110096012-c85fef80-7d9d-11eb-9e87-6cb687d94ee1.png)

![](https://user-images.githubusercontent.com/14334820/110096169-f1808000-7d9d-11eb-8cb9-05f6bd26a1e6.png)

**Comment by niegowski** [comment]
This icon is about the caption so I think that the caption part should be black (as the main focus) and the block above it should be gray and empty (as a context), also to distinguish caption from text maybe it could be shorter (not the full width of the box above) and one line to indicate that it's sth just below some block (maybe even a short line, not dashed)

**Comment by magda-chrzescian** [comment]
@niegowski Thanks for the comment. I explored some more options based on it. I was afraid that a one-line caption won't look like a text line, but now I think that it's quite understandable.
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/e108e471-797d-48b3-8e3e-ed8ec38eb546)
![image.png](https://images.zenhubusercontent.com/5fc63519d774781c638d81af/3d5922fc-aecd-45c6-be0b-3ce2e95acfa8)

I actually like the second version more since it focuses on the caption part itself (a filled shape is less a distraction than a border), but it is not very consistent with our icon set. So I think that the first one is a better option.

**Comment by magda-chrzescian** [comment]
Some reflections from the design process:

*   IMO we need to focus on the universal visual representation of the icon, it should be understandable even without the context of the editor - It doesn't have to look like "our" caption.
*   I assumed that the 1,5px line is the standard we want to keep. But maybe there is a decision to make - do we go with 1px for "irrelevant" things and 2px for the core content of the icon or we keep 1,5px lines everywhere. But it's probably the consideration for another issue.  
     

<table><tbody><tr><td>1.</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/110454389-75e94080-80c7-11eb-8ff0-98fd38e1d01f.png"></figure></td><td>One from the previous comment.</td></tr><tr><td>2.</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/110453722-c01df200-80c6-11eb-90df-75c6f24f50c6.png"></figure></td><td>&nbsp;</td></tr><tr><td>3.</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/110453860-ed6aa000-80c6-11eb-94f1-0f088d9523e7.png"></figure></td><td>&nbsp;</td></tr><tr><td>4.</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/110456530-f872ff80-80c9-11eb-8b9e-d09d1abea1e0.png"></figure></td><td>&nbsp;</td></tr><tr><td>5.</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/110453915-fd827f80-80c6-11eb-898d-cef2a763d36e.png"></figure></td><td>Some other direction. IMO looks too much like a tablet,<br>but maybe it's worth exploring</td></tr><tr><td>6.</td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/110454172-36baef80-80c7-11eb-9a89-5dcdf674d0a6.png"></figure></td><td>Some other direction. IMO looks too much like a tablet,<br>but maybe it's worth exploring</td></tr></tbody></table>

**Comment by niegowski** [comment]
I like this one the most

> ![](https://user-images.githubusercontent.com/14334820/110453860-ed6aa000-80c6-11eb-94f1-0f088d9523e7.png)

**Comment by AnnaTomanek** [comment]
Same as @niegowski although I do see the point of making the meaning of gray/leaner lines for "irrelevant" parts consistent for image and table features. Maybe this is a good moment to do it in all these icons?

**Comment by Reinmar** [comment]
Same as @niegowski. Although I also like the 4th option as that kind of line is often use to represent a text. Maybe we could merge both? Have it centered, but split? I don't like that it's left aligned in 4th.

Crazy idea: did you consider "CC" (closed caption) kind of symbolism? No idea whether it's the right symbol for this kind of captions, but just wanted to drop it here.

**Comment by magda-chrzescian** [comment]
@Reinmar I actually explored the CC idea, but it seemed to be strictly related to the video content and, as an icon, not very understandable to the editor users.

**Comment by magda-chrzescian** [comment]
With @oleq we finally made a decision to go with the option with the left alignment.  
Despite that I agree that the centered option looks better, this one seems to be more universal as a caption symbol.

![](https://user-images.githubusercontent.com/14334820/110454389-75e94080-80c7-11eb-8ff0-98fd38e1d01f.png)

**Comment by oleq** [comment]
Closed in 86e89ca.
