### ISSUE TITLE
Drag and drop of textual content and widgets

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#9128]
## 📝 Provide a description of the new feature

Extracted from [#2664](https://github.com/ckeditor/ckeditor5/issues/2664). Scenario A, B, and C with the assumption that dropping is allowed only in text positions or on the widgets.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
![](https://user-images.githubusercontent.com/1232187/109486255-ea4a3100-7a82-11eb-8202-f070b82acf40.gif)

**Comment by castroCrea** [comment]
@niegowski Game changing Thx alot

**Comment by castroCrea** [comment]
What do you think of adding the a drag indicator possibility (it can select automatically the block). I think it is nice fir the UX
![image](https://user-images.githubusercontent.com/20707343/109486871-bd4a4e00-7a83-11eb-8418-d7592d6e45bb.png)

**Comment by Reinmar** [comment]
@castroCrea If I understand correctly, these are scenarios C and D from #2664 and outside the scope of the current work. There's dedicated #7731 for the block-level dnd.

**Comment by Reinmar** [comment]
The cool thing is that @niegowski managed to make block widgets draggable in an inline-manner, but with what I think is a reasonably good UX. So it's not yet a proper block-level drag&drop, but it's a major improvement over what's currently completely impossible.

**Comment by seancowan-dev** [comment]
Awesome stuff, I've been working on my own solution based on using text ranging, but it doesn't seem to be viable.  I may end up going with block level only.
