### ISSUE TITLE
[Docs] The document editor deserves a better sample

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#913]
Related:  #894

The current sample for the document editor looks a bit silly and definitely does not show the potential of this editor. The header where 4 words cannot fit a single line. The squeezed content, which when printed on a paper would look silly. The styling of that sample should be reasonable for a document which is intended to be printed on a A4 paper, where most of the documents are later printed on.

![screen shot 2018-03-16 at 08 46 20](https://user-images.githubusercontent.com/545175/37509167-8b85b5a8-28f6-11e8-9030-e43da3f3fc92.png)

**Comment by oleq** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/894.

**Comment by Reinmar** [comment]
This issue starts from the same comment ;D

**Comment by Reinmar** [comment]
This page has 19cm:

![image](https://user-images.githubusercontent.com/156149/37530256-7295984a-2939-11e8-8366-3cbbd56e1808.png)

And fits Umberto's layout. 21cm starts overlapping with the license footer.

**Comment by Reinmar** [comment]
I tried to make other examples wider too, but it looked bad in their case.

**Comment by Reinmar** [comment]
We did all we could for now. Closing, unless someone have some ideas.
