### ISSUE TITLE
Re-think the UX for image caption toggling

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9136]
# ATM

https://github.com/ckeditor/ckeditor5/pull/9090 implements the following UX:

* 👍 click&type, which is likely the common use-case,
* 👎 the toolbar disappears so to revert adding the caption, you need to re-select the image,
* 👎 there's a lot happening at the same time (toolbar disappears, the caption appears and gets highlighted, the selection moves)

## Creating a new empty caption 

![2021-03-01 16.07.00.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/ed6531fa-2001-4289-8435-e0c3c1f468df)

## Reverting an existing caption 

![2021-03-01 16.06.39.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/24d0dd79-bfa8-4413-8533-836bcc2d6cf0)

# Other UXs

## Don't move the selection to the caption

* 👍 the toolbar stays in place, click again without moving the mouse to get rid of the caption,
* 👍 the selection does not change and the toolbar stays in place, less distractions,
* 👎 typing in a caption requires another click,

### Creating a new empty caption 

![2021-03-01 16.16.46.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/67d72bdf-60c1-4a1f-a690-ff2f68f58921)

### Reverting an existing caption 

![2021-03-01 16.16.27.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/fd9c65a7-3184-480c-b972-49c2afda0bde)

## Move the selection to the caption but keep the toolbar

* 👍 click&type, which is likely the common use-case,
* 👍 the toolbar stays in place, click again without moving the mouse to get rid of the caption,
* 👍 the toolbar stays in place, less distractions,
* 👎 possible collision with the balloon toolbar, although we already do that for the table toolbar
* 👎 requires changes in other features (note the grayed out buttons in the toolbar when the selection is in the caption)

### Creating a new empty caption 

![2021-03-01 16.31.51.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/f7f1d0c5-a751-4b4b-8e91-f8f3be9276ff)

### Reverting an existing caption 

![2021-03-01 16.32.07.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/daa67f49-c565-4e1a-838d-cfaefea533d1)

**Comment by niegowski** [comment]
> Move the selection to the caption but keep the toolbar

I'm voting for this option.

**Comment by magda-chrzescian** [comment]
> *   :-1: possible collision with the balloon toolbar, although we already do that for the table toolbar

@oleq By the collision, you mean that the toolbar is attached to the bottom of the image and it has to move when adding a caption? What do we do about that regarding the table?

**Comment by oleq** [comment]
> @oleq By the collision, you mean that the toolbar is attached to the bottom of the image and it has to move when adding a caption? What do we do about that regarding the table?

I mean there will be two toolbars in the same editable area next to each other and if the image is small (e.g. less than the height of the toolbar) they might overlap and we don't have the tools (or capacity to create them) necessary to resolve this conflict (e.g. to make sure they are at least positioned on the opposite sides of the image).

![](https://user-images.githubusercontent.com/1099479/110308762-ccd81280-8000-11eb-8339-7c2af8e92b11.png)

As for the table toolbar, we have the following UX to resolve this issue. We could replicate this UX in the images but this will mean that in some cases the toolbar will still disappear, for instance, when toggling an existing (non-empty) caption of an image (see the last screencast of https://github.com/ckeditor/ckeditor5/issues/9136#issue-818982226)

![](https://user-images.githubusercontent.com/1099479/110309091-33f5c700-8001-11eb-8b80-40fedf8e7943.gif)

**Comment by magda-chrzescian** [comment]
I fixed the toolbar visibility and extracted a follow-up to enable the buttons inside #9213.

**Comment by oleq** [comment]
Closed in #9212.
