### ISSUE TITLE
Extend 26.0.0's migration guide

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9138]
## 📝 Provide a description of requested docs changes

The migration guide was introduced in #9133.

It misses:

*   Ctrl/Cmd work by @niegowski. It's important to mention that if someone wants the Ctrl to be modifier regardless of the OS, they should use `Ctrl!`.
*   Rename of the commands, buttons and plugins from @psmyrek.

**Comment by niegowski** [comment]
> *   Ctrl/Cmd work by @niegowski. It's important to mention that if someone wants the Ctrl to be modifier regardless of the OS, they should use `Ctrl!`.

I pushed this part to the original PR.

**Comment by AnnaTomanek** [comment]
Merged long time ago to the `stable` branch.
