### ISSUE TITLE
Update default build configs/snippets with the new image styles configuration

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9144]
ATM we mostly use "semantical" styles across the code base. After #8909 there will be different styles available and we need to figure out which should be available by default.

**Comment by magda-chrzescian** [comment]
I temporarily added the 'full' and 'side' styles to the default set loaded with the `ImageInlineEditing` and `ImageBlockEditing` plugins to prevent some errors in tests. It should be reviewed while resolving this issue.

**Comment by magda-chrzescian** [comment]
The examples of the default editor builds (`ClassicEditor`, `BalloonEditor`, `BalloonBlockEditor`) contains some pictures that are styled by the 'side' image style. Except for the alignment, it also applies the `max-width: 50%` property to the image. This style is not covered by our new default set of image styles.

We need to support the content of these examples or change it. I really think that we should not limit the functionality of our default builds.

#### One option is to keep the `side` style available, but remove it from the toolbar.

*   Existing content will be successfully displayed in the editor.
*   None of the styles in the toolbar will be highlighted for the existing content.
*   It won't be possible by default to set the `max-width: 50%` property to the image for newly created content.

#### We can also add the `ImageResize` plugin to the particular builds.

*   Existing content won't be supported, it will require setting the image width again.
*   It will be possible to style the image properly, but the process will be more complicated (setting the alignment + setting the size separately).
*   The result of setting the image width will be slightly different than applying the `side` style (`max-width` vs `width`).

#### We can create a new set of semantic styles containing the inline images.

**Comment by magda-chrzescian** [comment]
The examples of the default editor builds (\`ClassicEditor\`, \`BalloonEditor\`, \`BalloonBlockEditor\`) contains some pictures that are styled by the 'side' image style. Except for the alignment, it also applies the \`max-width: 50%\` property to the image. This style is not covered by our new default set of image styles.

![](https://user-images.githubusercontent.com/14334820/110841195-e483f500-82a5-11eb-8622-a00bbdc9f76a.png)

We need to support the content of these examples or change it. I really think that we should not limit the functionality of our default builds.

#### One option is to keep the \`side\` style available, but remove it from the toolbar.

\*   Existing content will be successfully displayed in the editor.  
\*   None of the styles in the toolbar will be highlighted for the existing content.  
\*   It won't be possible by default to set the \`max-width: 50%\` property to the image for newly created content.

#### We can also add the \`ImageResize\` plugin to the particular builds.

\*   Existing content won't be supported, it will require setting the image width again.  
\*   It will be possible to style the image properly, but the process will be more complicated (setting the alignment + setting the size separately).  
\*   The result of setting the image width will be slightly different than applying the \`side\` style (\`max-width\` vs \`width\`).

#### We can create a new set of semantic styles containing the inline images.

*   The existing content will be supported.
*   The new content will be formatted easily.
*   We won't show our "full functionality" in all builds, but we can still use it in the builds which use the presentational styles.

**Comment by magda-chrzescian** [comment]
I just realised that we use the toolbar `defaultConfig` for the builds, so all issues related to the content compatibility will affect not only the demos but also the builds themselves.

> 👎 DEMO: None of the styles in the toolbar will be highlighted for the existing content.
👎 DEMO: While playing with the image styles it won't be possible to apply the max-width again.
(...)

**Comment by oleq** [comment]
Yes, we were aware of this. This is a breaking change for us (demos, guides, manual tests) and for integrators who will upgrade their editor installations. The key factor here is the upgrade path for the integrators, we need to document what to do (and where) in the migration guide.

Let's make sure we're on the same page, just correct me if I'm wrong: the problem in guides comes down to the fact that `.image-style-block-align-right` does not come with any size limitation so if the image used in the guide is huge, it will span the entire width of the editing root and look weird (and unresponsive)? (as opposed to `.image-style-side` which has `max-width: 50%`).

**Comment by oleq** [comment]
Do you remember @magda-chrzescian why `.image-style-block-align-right` and `.image-style-block-align-left` were implemented without `max-width` in the first place? 😅 Because if they had it, `.image-style-side` would be obsolete, and the upgrade path would be obvious.

**Comment by Reinmar** [comment]
I didn't think about the `max-width` thing ;/ 

There must be a reasonable upgrade path for people that used these styles (side, full) previously. Our demos are just one of the "consumers" so tricks used in the demos do not solve the problem. Adding ImageResize is not an option as well as it would also be a very breaking change - previously you were setting one thing, now you need to set the alignment + size.

Let's maybe have a call to discuss this.

**Comment by Reinmar** [comment]
Oops, Olek's comments appeared after I posted my reply :D

**Comment by magda-chrzescian** [comment]
* The content of the editor builds examples should be improved to show the use of the inline images.
* The sizes of the images in our docs should be probably less than the width of the editing area, so that the application of the inline/full styles is visible to the user (related to https://github.com/ckeditor/ckeditor5/issues/9507).

**Comment by magda-chrzescian** [comment]
I marked this issue as blocked by the CF integration. The documentation should be updated as soon as it is possible to verify that it is actually displayed correctly.

**Comment by magda-chrzescian** [comment]
There is an issue in the internal repo related to the word-export plugin (https://github.com/ckeditor/ckeditor5/issues/9542), if it's resolved, we can turn on the inline images in the export-word feature guide.

**Comment by magda-chrzescian** [comment]
I guess we can close this one since all PRs are already merged.
FYI @oleq.
