### ISSUE TITLE
Ship CKEditor 5 DLLs 🚀 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9145]
## 📝 Provide a description of the new feature

~Currently, CKEditor 5 does not come with a ready-to-use DLL builds and DLL-compatible plugin builds.~

~We made the editor DLL-ready and there's a~ [~guide how to generate such builds~](http://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/dll-builds.html)~, but more work needs to be put into DLLs becoming the major integration method.~

Update: DLL-compatible builds of `ckeditor5` and `ckeditor5-*` packages are available on npm. The aforementioned guide ["CKEditor 5 DLL builds"](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds.html) was updated and shows the quick path to start using DLL-based editor. In the meantime we also made the [collaboration features DLL-compatible](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/dll-builds-collaboration-features.html) meaning that **this integration method is supported all across our platform**.

### What's next?

As explained in the previous section, DLLs are support across our entire platform. However, there's an idea to make them the main integration method. This would be a large-scale effort as we'd need to rethink the installation paths, how OB works, what do we ship, how API docs look, etc. This is future.

Challenges:

*   Turning current builds into DLL builds.
*   Rewriting most of the "Builds" section in the guides.
*   Turning API docs upside down to expose the index files and the globals.
*   Understanding the limitations of this method (and reverting some of the above changes :D).
*   Explaining how to write DLL-compatible plugins.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
We are taking a different approach to delivering packages with built code. Check out a detailed RFC on the new installation methods: #15502 :tada:
