### ISSUE TITLE
Obtain page-wise data representation when pagination is enabled

### ISSUE THREAD

**Issue by priyath** [ckeditor/ckeditor5#9148]
## Provide a description of the task
I am currently evaluating ckeditor5 for a particular task, and one of the requirements is the concept of a page in the editor. This will be used later on to do things like re-ordering, deleting and duplicating pages. Ideally, the data model should have the notion of a page in its representation.

Even though pagination is supported, based on the documentation and some of the source code, it doesn't look like ckeditor5 has the concept of a page built into the data model. So I believe I would need to parse the entire document HTML/markdown obtained via getData() and do the required manipulations to obtain a page-wise content representation at an application level.  

What I am trying to do right now is to parse the getData() html content based on the `data-pagination-page` attribute and obtain content per page. Then I will perform the required manipulations (delete, duplicate, re-order) on this data, and do a setData() to update the document.

Is there a better way to go about this?

## 📃 Other details

* Browser: Chrome
* OS: UBuntu 18.04
* CKEditor version: 5
* Installed CKEditor plugins: Pagination

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Actually, the pagination data is stored in the model, but as [markers](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_markercollection-Marker.html) with a  `pagination` prefix, not elements. Markers contain information about their [range](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html), so you can read the position where the page break will happen. See the example below about receiving all markers related to the pagination and their ranges:

```javascript
const markers = editor.model.markers.getMarkersGroup( 'pagination' );

for ( const marker of markers ) {
    const range = marker.getRange();
    const name = marker.name;

    console.log( name, range )
}
```

**Comment by priyath** [comment]
Thank you for your response. This definitely seems like the better approach. To get the actual HTML content for each page do I need to get a `TreeWalker` object for each range and loop through the items?

**Comment by Mgsy** [comment]
> To get the actual HTML content for each page do I need to get a `TreeWalker` object for each range and loop through the items? Or is there a more convenient way to get the content within a given range?

I think the `TreeWalker` will be the best choice, as it returns all elements within a given range.
