### ISSUE TITLE
emojis being stripped off in the editor via paste or setData() after Vue 3 production build on WINDOWS

### ISSUE THREAD

**Issue by j3ang** [ckeditor/ckeditor5#9149]
## 📝 Provide detailed reproduction steps (if any)
1. Followed the steps to build classic editor from src for Vue 3
2. Uploaded dist code on staging server 

### ✔️ Expected result
Mac and Windows should work the same.

### ❌ Actual result
1. Emojis can be displayed correctly on mac systems on supported browsers, but it will be stripped off the editorData on **windows system on supported browsers**. 
2. **On Windows browsers**, It can't be rendered in the editor via paste or setData() methods. The emojis can only be inserted via the emoji panel ( without pressing space after or it will be stripped off again). 

## 📃 Screenshots
![ckeditor-5-emoji-bug-screenshorts](https://i.ibb.co/1698z4K/ckeditor-5-emoji-bug.jpg)

* First affected CKEditor version: 
```
    "@ckeditor/ckeditor5-basic-styles": "^25.0.0",
    "@ckeditor/ckeditor5-build-classic": "^25.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^24.2.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^24.2.0",
    "@ckeditor/ckeditor5-editor-classic": "^25.0.0",
    "@ckeditor/ckeditor5-essentials": "^25.0.0",
    "@ckeditor/ckeditor5-font": "^25.0.0",
    "@ckeditor/ckeditor5-link": "^25.0.0",
    "@ckeditor/ckeditor5-paragraph": "^25.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^25.0.0",
    "@ckeditor/ckeditor5-vue": "^2.0.1",
```
* Installed CKEditor plugins: 
```
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
import SpecialCharacters from "@ckeditor/ckeditor5-special-characters/src/specialcharacters";
import SpecialCharactersEssentials from "@ckeditor/ckeditor5-special-characters/src/specialcharactersessentials";
import Clipboard from "@ckeditor/ckeditor5-clipboard/src/clipboard";
import Essentials from "@ckeditor/ckeditor5-essentials/src/essentials";
import Font from "@ckeditor/ckeditor5-font/src/font";
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
import Italic from "@ckeditor/ckeditor5-basic-styles/src/italic";
import BlockQuote from "@ckeditor/ckeditor5-block-quote/src/blockquote";
import Heading from "@ckeditor/ckeditor5-heading/src/heading";
import Link from "@ckeditor/ckeditor5-link/src/link";
import List from "@ckeditor/ckeditor5-list/src/list";
import Paragraph from "@ckeditor/ckeditor5-paragraph/src/paragraph";
```

---

### Things I've tried: 
1. adding emoji plugins (special characters and 2 other similar [NPM packages](https://www.npmjs.com/package/ckeditor5-emojis) ).
2. encoding and decoding the editor data

- It all comes down to the editor not being able to make the unicode emoji stay rendered. The emojis can flash for a second on load when retrieving from database and then it will be stripped off the editor or not showing at all. 
- Emojis can be typed, set and retrieved in the editor on both **mac and windows** on supported browsers after `npm run serve`.
- Emojis can be typed, set and retrieved in the editor  **only on mac** on supported browsers after `npm run build`.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I just checked Vue integration built from source [with additional emojis](https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html#adding-a-new-category) and it works fine.  
 Maybe there's some additional information you can share on how exactly to reproduce this ( precise steps, some custom code you use, etc. )? 
 Apart from this, please keep in mind that if you use some third party plugins, which are not created nor maintaned by CKEditor team, we cannot guarantee that they will work properly.
