### ISSUE TITLE
dblClick in Chrome/Safari selects also the next element

### ISSUE THREAD

**Issue by xpressionlabspeter** [ckeditor/ckeditor5#916]
🐞 Bug report  

## 📋 Steps to reproduce

1. enter some text on several lines
2. select with the mouse the first line, by mousedown on first character, drag to last and mousup
3. select an h1-style: result the first line is now a h1
4. undo
5. select the first line by dblclick (three-click) on a word in the first line.
6. Choose h1-style.
7. The firstline AND the next paragraph is now h1

## ✅ Expected result
only the first line as h1

## ❎ Actual result
first and second paragraph h1

## 📃 Other details that might be useful
Only in Chrome and Safari
see attached gif

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37589335/37666707-7fe5ad3a-2c60-11e8-9c57-679637f97f70.gif)

**Comment by Reinmar** [comment]
This is CKEditor 5's bug tracker. CKEditor 4's bug tracker is here: https://github.com/ckeditor-dev

BTW, this is fixed in CKEditor 5:

![mar-20-2018 17-24-15](https://user-images.githubusercontent.com/156149/37667959-93f823ea-2c63-11e8-9808-7155007c11d3.gif)
