### ISSUE TITLE
Using ckeditor5, how to highlight code

### ISSUE THREAD

**Issue by mzrybbd** [ckeditor/ckeditor5#9160]
## 📝  codeblock

---Using ckeditor5, how to highlight code

**Comment by Mgsy** [comment]
Hi! Could you please tell more about your requirements and what exactly you'd like to achieve?

**Comment by mzrybbd** [comment]
like this
![image](https://user-images.githubusercontent.com/33386828/110458276-8b318f80-8106-11eb-860a-c9cc533d924b.png)

**Comment by mzrybbd** [comment]
![image](https://user-images.githubusercontent.com/33386828/110458527-d481df00-8106-11eb-85f7-02d5557721ee.png)

**Comment by Mgsy** [comment]
Thanks for the clarification. CKEditor 5 doesn't support syntax highlight, however, we have a [feature request for the code snippet feature](https://github.com/ckeditor/ckeditor5/issues/5769) which will include such functionality. Feel free to add :+1:  to the first post and join the discussion to bump its popularity.

However, it's possible to integrate the code block plugin with a third-party highlighter, but it won't work inside the editor and will apply only to the content displayed on the page. You can read more about it [here](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#integration-with-code-highlighters).

**Comment by someqq** [comment]
Why CKEditor 5 doesn't support syntax highlight? Do you have any plans to support in the future?
