### ISSUE TITLE
New element id attribute is duplicated by previous element's id

### ISSUE THREAD

**Issue by saisk73** [ckeditor/ckeditor5#9163]
## 📝 Provide detailed reproduction steps (if any)

When ever a new element is added the id of previous element is copied by new element instead of being empty.
I am using plugin to retain ids to elements by plugin [https://github.com/ckeditor/ckeditor5/issues/8032](https://github.com/ckeditor/ckeditor5/issues/8032)
How can I prevent new element to have previous ID.

### ✔️ Expected result

```
<h2 id="h2-123">Some Content</h2>
<p>&nbsp;</p>
```
### ❌ Actual result

```
<h2 id="h2-123">Some Content</h2>
<p id="h2-123">&nbsp;</p>
```

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: Chrome
* OS:Windows
* First affected CKEditor version:5
* Installed CKEditor plugins:
* Framework: React 16.6.0

**Comment by Mgsy** [comment]
Hi, thanks for the report. Basically, this is an old issue related to the schema which can't control such behaviour. You can read more about it [here](https://github.com/ckeditor/ckeditor5/issues/4543) and [here](https://github.com/ckeditor/ckeditor5/issues/4235). Feel free to jump into the discussion to bump the popularity of mentioned issues.
