### ISSUE TITLE
The image upload success indicator does not fit small images

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9165]
Instead of being displayed over an image (upper-right corner), it is displayed in the lower-right corner.

![Screenshot 2021-03-05 at 09.17.04.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/d8f07f1d-8ef1-4027-949b-2981da50e14b)

This problem also occurred with block images but they were less likely to be uploaded so small because that would not make sense between the paragraphs. With inline images used as pseudo-bullets for lists etc. this will happen more often.

**Comment by magda-chrzescian** [comment]
As we agreed, I implemented the simplest solution for now, so the indicator will be hidden if an image is smaller than 50x50px.

**Comment by oleq** [comment]
Closed in https://app.zenhub.com/workspace/o/ckeditor/ckeditor5/issues/9194.
