### ISSUE TITLE
The UX of resizing small images looks broken

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9166]
It already looks bad for block images (which have 50px `min-height` for `<img/>` BTW)
![2021-03-05 09.22.28.gif](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/6e6db5ee-0b07-479e-b5d0-7f1d4a712f70)

and I can imagine it will look even worse for small inline images (e.g. 16x16px) that will also get resizing after #8777. The resize UI might cover the entire inline image and we should do something about it. For instance, we could display only a single resize handle for very small images. This will require some additional research.

Related to #9165.

**Comment by magda-chrzescian** [comment]
Looking at what we have and based on the research, I'm not sure if we need to do anything with the resize UI covering the image. I don't find it annoying - if I want to see how the image looks like I can always unselect it.

**TinyMCE:**

![](https://user-images.githubusercontent.com/14334820/110109626-0238f200-7dae-11eb-8483-2276426c8139.png)

**Word:**

![](https://user-images.githubusercontent.com/14334820/110109804-3ad8cb80-7dae-11eb-838d-cfc86371859b.png)

**Google docs:** They limit the minimal size of inline images.

![](https://user-images.githubusercontent.com/14334820/110109927-60fe6b80-7dae-11eb-8261-19ec941c925e.png)

**Froala:**

![](https://user-images.githubusercontent.com/14334820/110110576-5395b100-7daf-11eb-8292-0ddacc0489a9.png)

**Comment by magda-chrzescian** [comment]
I also addressed here the issue with the placeholder overflowing the caption area:

![](https://user-images.githubusercontent.com/14334820/110137533-41c50580-7dd1-11eb-89b2-0740e55e4c8c.png)

**Comment by oleq** [comment]
> I also addressed here the issue with the placeholder overflowing the caption area:

Do you have any PR?

**Comment by oleq** [comment]
> I'm not sure if we need to do anything with the resize UI covering the image.

What about the dynamic size preview label "53x32"? Where does it go when the image is smaller than 50px?

**Comment by magda-chrzescian** [comment]
> Do you have any PR?

#9173 

> What about the dynamic size preview label "53x32"? Where does it go when the image is smaller than 50px?

Fixed it, it's displayed above the image - it seems to be the safest place to keep it visible and inside the editor.

**Comment by oleq** [comment]
Closed in #9173.
