### ISSUE TITLE
The linked image indicator does not work well with small (inline) images

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9167]
ATM we use the anchor icon as the only indicator for linked image. This works OK (also debatable) for large images but there's simply not enough space to do the same for a 32x32px inline image, which will be common in certain cases.

![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/aa099df7-2201-4233-8f46-1cb12f531da9)

**Comment by oleq** [comment]
Related to #9165 and #9166.

**Comment by magda-chrzescian** [comment]
It should wait for the #8871 to be finished since the anchor icon doesn't seem to be fully working even with large images ATM.

![](https://user-images.githubusercontent.com/14334820/110462609-33c4fc80-80d1-11eb-9878-0c04ae3902a2.png)

**Comment by niegowski** [comment]
Closed in #9438
