### ISSUE TITLE
Text is shown above table

### ISSUE THREAD

**Issue by jensen-lin** [ckeditor/ckeditor5#9169]
## 📝 Provide detailed reproduction steps (if any)

1. Create a list
2. Above the list put in a table
3. Align the table to be left aligned

### ✔️ Expected result

Table to be left aligned and text still be underneath

### ❌ Actual result

Text is above the table

## 📃 Other details
![image](https://user-images.githubusercontent.com/73527808/110089956-09a0d100-7d97-11eb-99af-c9c43659234b.png)

* Browser: Chrome
* OS: …
* First affected CKEditor version: Ck5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hello, thank you for the report. We are aware of this behaviour and it has been already reported. You can find more details about this issue here - #8412.
