### ISSUE TITLE
Automatic text transformation : create dates fraction

### ISSUE THREAD

**Issue by konchak007** [ckeditor/ckeditor5#9170]
**## Steps:**

1. When I write 11/22/2021 it fix into 1½0/2021 .
2. In the same way I want to make it possible for numbers like: 1/2=> ½
3. It works for : 1/2, 1/3, 1/4, 2/3, 3/4

* Browser: all
* OS: macOs
* First affected CKEditor version: 5 , react version
* Installed CKEditor plugins: …texttrasnformation

**Comment by Mgsy** [comment]
Research results could be found [here](https://docs.google.com/spreadsheets/d/12x2WZdxEj8t_EzoYj0RcYqUq6AE0wnzaqqEiAxbN1-k/edit#gid=0).

**Comment by Reinmar** [comment]
Convert to a fraction only if:

*   It's preceded by line start or a character that does not match `/\/a-z0-9/i`
*   And it's succeeded by line end or a character that does not match `/\/a-z0-9/i`

**Comment by arkflpc** [comment]
Removed handling line-end after transformed text from the scope of this ticket.

**Comment by arkflpc** [comment]
Handling of line-ends extracted to issue #10551
