### ISSUE TITLE
“Remove highlight” button is not following the highlight command disabled state

### ISSUE THREAD

**Issue by serhiiyanhol** [ckeditor/ckeditor5#9174]
## 📝 Provide detailed reproduction steps (if any)

1. Open [highlight feature guide](https://ckeditor.com/docs/ckeditor5/26.0.0/features/highlight.html#inline-buttons) and scroll to "Inline buttons" sample.
2. Disable the highlight command. You can do this by executing the following code `document.querySelectorAll( '.ck-editor__editable' )[ 2 ].ckeditorInstance.commands.get( 'highlight' ).forceDisabled( 'someId' )`.

### ✔️ Expected result

On disable Highlight plugin buttons in toolbar should become inactive.

### ❌ Actual result
“Remove highlight” button is still active.

![image](https://user-images.githubusercontent.com/5353898/111320941-c3395500-8667-11eb-8250-d491583de295.png)

## 📃 Other details

* First affected CKEditor version: 24 
* Installed CKEditor plugins: default highlight

Possible solution:

>  _addRemoveHighlightButton() {
     const t = this.editor.t;
     const command = this.editor.commands.get( 'highlight' );
     function decorateHighlightButton( button ) {
       button.bind( 'isEnabled' ).to( command, 'isEnabled' );
     }
     this._addButton( 'removeHighlight', t( 'Remove highlight' ), eraserIcon, null, decorateHighlightButton );
  }

**Comment by Mgsy** [comment]
Hi, thanks for the report. Could you please provide steps to reproduce the problem, as I'm not sure if I understand your case properly?

**Comment by Reinmar** [comment]
Isn't it a dup of #9021? Which is a dup of some other ticket :D I suppose everyone's annoyed by the same beavior.

**Comment by yanholserhii** [comment]
It isn't a dup. Please see the screenshot. In _addHighlighterButton the possibility to disable is provided. But there isn't such possibility for _addRemoveHighlightButton.

![image](https://user-images.githubusercontent.com/76559917/110298098-d8c1d580-7ffc-11eb-9a61-d478187da211.png)

**Comment by yanholserhii** [comment]
I already create PR. Soon I will provide needed test coverage.

**Comment by Reinmar** [comment]
Sorry for the previous comment. These are indeed separate issues.

Excuse me the ignorance once again (I'm not checking the code), but just to be sure – the issue you reported is that the button is not disabled when the command is disabled. In other words – disabling the command should also disable the button?

**Comment by yanholserhii** [comment]
Do not worry.
Yes, you are right, disabling the command should also disable the button. 
We use `highlight` and `removeHighlight` separately. So that's why the problem occurred.
