### ISSUE TITLE
ios rickeditor use todoList has an error

### ISSUE THREAD

**Issue by zhoujintang** [ckeditor/ckeditor5#9178]
CKEditorError: null is not an object (evaluating 'o.getStyle')
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-null is not an object (evaluating 'o.getStyle')

html:
<!DOCTYPE html>

<html lang="en" dir="ltr"></html>
<head>
	<title>CKEditor 5 ClassicEditor build</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="https://c.cksource.com/a/1/logos/ckeditor5.png">
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body data-editor="ClassicEditor" data-collaboration="false">
	<main >
		
		<div class="centered">
			<div class="row row-editor">
				<div class="editor">
					<h2>Bilingual Personality Disorder</h2>
					<figure class="image image-style-side"><img src="https://c.cksource.com/a/1/img/docs/sample-image-bilingual-personality-disorder.jpg">
						<figcaption>One language, one person.</figcaption>
					</figure>
					<p>
						a century show that
						<strong>the language you speak has more effects on you than you realise</strong>.
					</p>
				
				</div>
			</div></div>
		</div>
	</main>
	
	<script src="../build/ckeditor.js"></script>
	
	<script>ClassicEditor
			.create( document.querySelector( '.editor' ), {
				
				toolbar: {
					items: [
						'heading',
						'|',
						'bold',
						'italic',
						'link',
						'bulletedList',
						'numberedList',
						'|',
						'outdent',
						'indent',
						'|',
						'imageUpload',
						'blockQuote',
						'insertTable',
						'mediaEmbed',
						'undo',
						'redo',
						'todoList',
						'underline',
						'CKFinder',
						'alignment',
						'code',
						'codeBlock',
						'fontBackgroundColor',
						'fontColor',
						'fontFamily',
						'highlight',
						'horizontalLine',
						'imageInsert',
						'removeFormat',
						'specialCharacters',
						'subscript',
						'superscript',
						'fontSize'
					]
				},
			
				image: {
					toolbar: [
						'imageTextAlternative',
						'imageStyle:full',
						'imageStyle:side',
						'linkImage'
					]
				},
				table: {
					contentToolbar: [
						'tableColumn',
						'tableRow',
						'mergeTableCells',
						'tableCellProperties',
						'tableProperties'
					]
				},
				licenseKey: '',
				
				
			} )
			.then( editor => {
				window.editor = editor;
		
				
				
				
		
				
				
				
			} )
			.catch( error => {
				console.error( 'Oops, something went wrong!' );
				console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
				console.warn( 'Build id: 9ioipzrm307v-ej51o07rf63h' );
				console.error( error );
			} );
	</script>
</body>

**Comment by Mgsy** [comment]
Hi! Could you please describe your issue more precisely and provide steps to reproduce the problem?
