### ISSUE TITLE
Cannot set property 'dir' of undefined

### ISSUE THREAD

**Issue by ibrahimcseku** [ckeditor/ckeditor5#9179]
I am using ckeditor5 and It is working fine in one page of my project but the problem is when I point/redirect the page from another application then it through an uncatch exception.

Please suggest me how can I resolve this problem.

Here is the exception: 

Failed to load resource: the server responded with a status of 404 ():8080/demo/ckeditor5/config.js?t=G2VC:1 
Failed to load resource: the server responded with a status of 404 ():8080/demo/ckeditor5/lang/en.js?t=G2VC:1 
ckeditor.js:228 Uncaught TypeError: Cannot set property 'dir' of undefined
    at Object.d (ckeditor.js:228)
    at f (ckeditor.js:229)
    at Array.x (ckeditor.js:229)
    at A (ckeditor.js:229)
    at HTMLScriptElement.CKEDITOR.env.ie.CKEDITOR.env.version.g.$.onerror (ckeditor.js:230)

and when I type someting in the textarea then it through another error like below image:

![issue](https://user-images.githubusercontent.com/64660477/110209513-38ae6400-7eb7-11eb-975b-07ae80989d6b.PNG)

**Comment by Mgsy** [comment]
Hi, can you provide more details about your issue and share steps to reproduce the problem?
