### ISSUE TITLE
Hitting enter key disables current text style

### ISSUE THREAD

**Issue by mark-bragg** [ckeditor/ckeditor5#919]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor5 classic build 1.0.0-alpha.2

## 📋 Steps to reproduce

1. choose a style like italic
2. type text
3. hit enter key
4. type more text

## ✅ Expected result
I expect the text style to remain from one line to the next

## ❎ Actual result
Text style is disabled

**Comment by Reinmar** [comment]
This is a DUP of https://github.com/ckeditor/ckeditor5-enter/issues/40. We have some doubts there regarding which styles should be copied to the new line on enter, so feedback will be greatly welcomed :)
