### ISSUE TITLE
Ability to view and edit source code

### ISSUE THREAD

**Issue by blue-dreamer** [ckeditor/ckeditor5#9191]
## 📝 Provide a description of the new feature

The ability to view source as in earlier versions of CKeditor. 

Reasons:

1. Allows flexible editing options for authors, they can choose WYSIWYG or code view
2. Some HTML has to be manually added, e.g. DEL, INS, SMALL, CITE
3. Quite often I end up having to manually edit HTML because a client has been over zealous with WYSIWYG formatting
4. Source view can be helpful for quickly debugging output

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. There's already a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/592), so you can track the discussion and progress there.  
I'll close this ticket as a duplicate.
