### ISSUE TITLE
Toolbar issues on iPad

### ISSUE THREAD

**Issue by mark-bragg** [ckeditor/ckeditor5#920]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor5 Classic Build v-1.0.0.alpha2

## 📋 Steps to reproduce

1. open CKEditor in html doc on iPad
2. tap text style
3. tooltip is visible
4. type text
5. text is not styled
6. tap style again
7. type text
8. text is now styled
9. the tooltip has been visible throughout the entire process, so tap toolbar where no buttons are located
10. tooltip disappears

## ✅ Expected result
Text styles should be applied when a single tap is applied to the toolbar style button, and the tooltip should disappear.

## ❎ Actual result
Text styles require two taps, and the tooltips do not disappear until the toolbar is tapped.

The video isn't too clear, but it's the best I could do.
[toolbar_ipad_issues.m3u.zip](https://github.com/ckeditor/ckeditor5/files/1839706/toolbar_ipad_issues.m3u.zip)

**Comment by Mgsy** [comment]
I can confirm that on iPad two taps are required to apply an inline style. I've checked this behaviour on Android device and the button goes active after one tap.

**Comment by Reinmar** [comment]
That's one of the whole range of issues on mobiles, but perhaps we can prioritise this higher. Especially that it doesn't sound hard. 

cc @oleq

**Comment by Reinmar** [comment]
cc @Comandeer

**Comment by oleq** [comment]
It boiled down to the tooltips. When the button has some `:hover` styles then the first click activates them and the second one is a regular click. It looks like a backward compatibility feature in iOS to allow users browse and enjoy not–quite–mobile–friendly websites too.

Resolved the issue in PRs by simply 
* detecting iOS,
* disabling tooltips.

**Comment by Reinmar** [comment]
But perhaps listening to touch events blocks this behaviour? I can imagine a hybrid machine where you might still want to have tooltips (because it has a real mouse) but you'd need to support touch too.

I'd just like to confirm that there's no more straightforward solution using touch events?

**Comment by oleq** [comment]
I can check this out.

**Comment by oleq** [comment]
I checked it and it turned out that whether tooltips are on or off the command is actually executed. 

But with tooltips on, the selection does not get the attribute upon the first click. There's much more to the issue than I thought. It's probably something about tooltips "stealing" focus and changing the way engine works in this situation.

**Comment by oleq** [comment]
OK, the whole issue boils down to https://css-tricks.com/annoying-mobile-double-tap-link-issue/ (read it first) and there are 2 media query solutions

```css
@media (pointer: fine) {
   /* enable tooltips */
}
```

```css
@media (hover) {
   /* enable tooltips */
}
```

which work in Chrome, Safari, and Edge but not in... FF, disabling the tooltip functionality in that browser. Knowing that, I see 3 possible roads:

* [Disable tooltips in iOS](https://github.com/ckeditor/ckeditor5-ui/pull/381) (as suggested before),
* Ignore Firefox and implement the CSS-side media query fix, which is not a very good idea IMO,
* Implement a JS detection of the touch UA (as I researched, the topic is quirky) and disable tooltips on the JS side,
* Get rid of `:hover` and implement the tooltip logic using JS (`mouseover`, etc.), which feels like the safest road. Google did that in GDocs.

**Comment by oleq** [comment]
OK, I created [another PR](https://github.com/ckeditor/ckeditor5-ui/pull/388) which uses the media query solution in an inverted sort of way: it disables the tooltips when there's no `:hover` support (instead of enabling them, when `:hover` is supported) to use the safest fix and keep FF intact.
