### ISSUE TITLE
Support for pasting content from WPS

### ISSUE THREAD

**Issue by Y2zz** [ckeditor/ckeditor5#9208]
Paste should be normal, can only retain the picture, the text will be replaced by spaces

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. There is already a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/2488), so you can track it there. Also feel free to add any information you find important and don't forget to add 👍  to bump its popularity.  
I'll close this one as a duplicate.
