### ISSUE TITLE
Disabled buttons in the image toolbar.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9213]
After resolving the #9136, the image toolbar remains visible when the selection is placed inside the image caption. Still, all the buttons (except the caption button) in the toolbar are disabled.

It makes sense to enable the commands bound to these buttons to make the toolbar fully functional.

![](https://user-images.githubusercontent.com/14334820/110791655-be912d00-8272-11eb-81ab-ea7236e51f80.png)

**Comment by oleq** [comment]
This is a must-have. I already found myself trying to change style after toggling the caption so many times but I couldn't because of this.

**Comment by oleq** [comment]
Closed in #9459.
