### ISSUE TITLE
Default table properties via configuration

### ISSUE THREAD

**Issue by tony** [ckeditor/ckeditor5#9219]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

e.g. How do we configure the default table styles? I want a 1px border with certain colors to be pre-filled.

Example:

```js
{
  table: {
    tableProperties: {
      defaults: {
        borderColor: 'red',
        borderWidth: '1',
        borderStyle: 'solid'
      }
   }
}
```

Upon the user inserting a table, they should see:

![image](https://user-images.githubusercontent.com/26336/110826885-2471ba80-825b-11eb-86d6-b5b5d50ccf4a.png)

History: To avoid confusion, this remakes #6363's [original post](https://github.com/ckeditor/ckeditor5/issues/6363#issue-573975234) as its topic changed and it was closed. The new topic at #6841 is speaking about something different than setting default (clearing the value vs setting `none` to negate?)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Related #8502.

**Comment by Reinmar** [comment]
We'll be checking whether we cannot cover all properties at once when working on #8502. However, alignment is a higher priority so if covering all props would increase the scope too much, we'll focus on alignment only.

**Comment by pomek** [comment]
The proposed solution is being developed/tracked in the other issue – https://github.com/ckeditor/ckeditor5/issues/8502#issuecomment-808120931.

**Comment by tony** [comment]
@pomek Looking good!

**Comment by tony** [comment]
@pomek Thank you! The team is delighted about this!
