### ISSUE TITLE
Styling is lost after typing outside of the link

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#922]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the article sample.
1. Put the caret at the end of the link.
1. Press <kbd>Arrow right</kbd> to exit the link.
1. Activate the bold.
1. Type two characters.

## ✅ Expected result
The styling is preserved.

## ❎ Actual result
The styling is lost on the second character.

## 📃 Other details that might be useful
**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/37897071-8f05ed1e-30e5-11e8-9138-a0a6fd5d78b0.gif)

OS: All platforms
Browser: All browsers

**Comment by Reinmar** [comment]
Apparently, the gravity isn't reset on selection attrs being changed. So, the selection gets the bold attr, but since the gravity is set to right, it loses it after a character is inserted.

**Comment by oleq** [comment]
A cross-reference https://github.com/ckeditor/ckeditor5-engine/issues/1301.
