### ISSUE TITLE
CKEditorError: Cannot read property 'toNormalizedForm' of undefined

### ISSUE THREAD

**Issue by mayraGL** [ckeditor/ckeditor5#9222]
Hello. This, integrating CKEditor 5 in my angular application and wanting to edit a text that I previously created with the editor with a color option, I find the following message.

![image](https://user-images.githubusercontent.com/29493115/110869123-716f8400-828f-11eb-803d-f2218870026c.png)

My version of angular is 8. I generated my own build of your repository with version 25.0.0 and integrated MathType to be able to use it. This is the editor settings

![image](https://user-images.githubusercontent.com/29493115/110869290-c14e4b00-828f-11eb-91e8-11f54e2632b2.png)

![image](https://user-images.githubusercontent.com/29493115/110869315-cca17680-828f-11eb-9707-1c7535665a41.png)

I hope you can help me

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Could you please provide a step-by-step scenario that allows reproducing the issue?

**Comment by mayraGL** [comment]
Do you need the code or could you enter a test platform? 

> Hi! Thanks for the report. Could you please provide a step-by-step scenario that allows reproducing the issue?

**Comment by Mgsy** [comment]
> Do you need the code or could you log into a test platform?

It would be great if you could provide a scenario with a minimal amount of code necessary to reproduce the issue, so we'll be able to investigate it locally.

**Comment by mayraGL** [comment]
Hello 

This is the repository link. This is the link to the repository, there are instructions for installation.

https://github.com/mayraGL/test-ckeditor.git

I included 3 examples. The first two happen to us with the options of the font color and the background color. 

![image](https://user-images.githubusercontent.com/29493115/111337983-2c0ad800-863c-11eb-9b35-0f2a70f2cd5d.png)

![image](https://user-images.githubusercontent.com/29493115/111338067-3dec7b00-863c-11eb-8c1a-777a73ae2bfe.png)

The third example is a recently reported issue. When saving a mathematical formula, then when you want to edit and put this content in the editor, some special characters are not displayed and a '?' Symbol appears instead. I could not reproduce it in the example but I leave you some images sent by our test team.

![image](https://user-images.githubusercontent.com/29493115/111338928-f5818d00-863c-11eb-97b4-6e72064ce8ef.png)

![image](https://user-images.githubusercontent.com/29493115/111339012-0500d600-863d-11eb-9fa1-4a55e5dec249.png)

![image](https://user-images.githubusercontent.com/29493115/111339025-08945d00-863d-11eb-9c72-e55b18281fc5.png)

**Comment by mayraGL** [comment]
Hello!

Do you have any status of this?

**Comment by mayraGL** [comment]
Hello!

Do you have any status of this?

**Comment by Mgsy** [comment]
Hi @mayraGL, I'm sorry for the late response. We had a busy period because of the release. I'll look at your issue soon.

**Comment by Mgsy** [comment]
@mayraGL, I've looked at your project and it seems that error is triggered by specific content, i.e. `<span>` with the `style` attribute. 

I'm not sure what is the root of the problem, as I haven't seen this error before, however, I can see that you use a slightly old CKEditor 5 version. I've just checked that build with MathType created with our [Online builder](https://ckeditor.com/ckeditor-5/online-builder/) (that contains the latest packages) works properly in your project. So, I'd recommend preparing a new build with the most recent packages.

**Comment by mayraGL** [comment]
Hi

I was trying to generate the build as you indicated but when selecting the options and replacing the files, the bar is not displayed 

![image](https://user-images.githubusercontent.com/29493115/113328226-3930f380-92d9-11eb-95d8-d3c4fb4df5cb.png)

![image](https://user-images.githubusercontent.com/29493115/113327349-15b97900-92d8-11eb-8075-b2f5cdd4de9c.png)

And these are the files that I replace

![image](https://user-images.githubusercontent.com/29493115/113327566-5c0ed800-92d8-11eb-870b-0963529e7405.png)

Do you know what it could be? Or could you help me with a build of a version that I can use with those options?

I already need to close this because the client is upset :(

I also tried to generate it through its repository but with version 27.0.0 and the same error message appears.

![image](https://user-images.githubusercontent.com/29493115/113329007-40a4cc80-92da-11eb-93ad-9130ff5b8600.png)

**Comment by Mgsy** [comment]
> I was trying to generate the build as you indicated but when selecting the options and replacing the files and the error is not showing, but the bar is not showing.

Did you pick the decoupled editor (it requires inserting the toolbar separately)? Or are you sure that your toolbar configuration contains items?

**Comment by mayraGL** [comment]
I chose the Classic option. Then choose the plugins. And then drag the icons from Available toolbar items to Picked toolbar items.

**Comment by mayraGL** [comment]
Do you know what could be happening? Or could you help me to generate a build correctly?

**Comment by Mgsy** [comment]
It's difficult to say why it doesn't work for you. However, I can see that you directly replace files in `node_modules`, which is not a good idea (e.g. your custom build will disappear after updating packages). I'd suggest going through our [custom builds in the Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build) to learn how to do it in a proper way (it might be required to install your local build as a dependency, you can do it by calling `yarn add file:/<your-build-directory>`).

**Comment by mayraGL** [comment]
He estado intentando integrarlo de la manera que me dices

yo deberia de integrar todo el repositorio?

![image](https://user-images.githubusercontent.com/29493115/115250501-40d10480-a0ef-11eb-8f05-1ceec48551ac.png)

**Comment by mayraGL** [comment]
I also tried with the latest version of your repository (master)

**Comment by mayraGL** [comment]
Also I check the result of the Online Builder and it seems not to have ClassicEditor.defaultConfig, I added it to the file but it does not seem to work either. The bar is not shown yet and I added it in the same way that you indicated it to me

![image](https://user-images.githubusercontent.com/29493115/115264668-20f40d80-a0fc-11eb-9ab2-8f884b4189d8.png)

![image](https://user-images.githubusercontent.com/29493115/115264727-2d786600-a0fc-11eb-9183-a0bf39502623.png)

![image](https://user-images.githubusercontent.com/29493115/115264849-4a149e00-a0fc-11eb-9122-f38e6b22c27f.png)

**Comment by Mgsy** [comment]
I'm sorry but I can't reproduce your problem with the error, everything works as expected:

1.  Create a build containing MathType and Font plugins in our online builder.
2.  Unpack the zip.
3.  Clone [https://github.com/mayraGL/test-ckeditor.](https://github.com/mayraGL/test-ckeditor.)
4.  Move unpacked zip to the main `test-ckeditor` directory.
5.  Run `npm install --save file:./ckeditor5`.
6.  In `src/app/my-shared/my-ckeditor/my-ckeditor.component.js` change the import to `import ClassicEditor from 'ckeditor5-custom-build';`
7.  Run the project.

As it comes to the toolbar issue, it seems there's a problem with the editor configuration and the toolbar doesn't contain any items. You can try to configure your toolbar manually using the [`config`](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#config) property, e.g.:

```
<ckeditor id="editor" [editor]="editor" [data]="data" [(ngModel)]="data" (change)="change($event)" [config]="{ toolbar: [ 'heading', '|', 'bold', 'italic' ] }">
</ckeditor>
```

![](https://user-images.githubusercontent.com/20988892/115354368-d769f800-a1b9-11eb-8dfc-a4e7e269e004.png)

**Comment by mayraGL** [comment]
Thank you. She managed to integrate it the way you indicated. And the problem with the font color has been solved.

The bad news is that the problem with special characters with the MathType integration still persists in this version. I have finally managed to replicate the error.

I wrote the following in the editor.

![image](https://user-images.githubusercontent.com/29493115/115473215-ed4edb80-a200-11eb-8ece-d4d783303689.png)

![image](https://user-images.githubusercontent.com/29493115/115473249-0192d880-a201-11eb-95fb-2c16cc4d9b4d.png)

But once I save it in the database and then show it, it is displayed as follows

![image](https://user-images.githubusercontent.com/29493115/115479808-dadb9e80-a20e-11eb-9584-f0cc3f1fef40.png)

Update the repository so you can replicate it.

I will be waiting for your feedback

**Comment by Mgsy** [comment]
MathType is developed and maintained by the Wiris team, not CKEditor 5 team. All issues related to MathType should be reported in the MathType issue tracker - [https://github.com/wiris/html-integrations/issues.](https://github.com/wiris/html-integrations/issues.) While creating the issue, remember to include exact steps to reproduce the problem, actual and expected result to help the team investigating the issue.
