### ISSUE TITLE
Bug that occurs when entering Korean characters

### ISSUE THREAD

**Issue by amada75** [ckeditor/ckeditor5#9225]
## 📝 Provide detailed reproduction steps (if any)

First of all, thank you very much for making a great editor.
We are developing various programs using your attractive editor.

However, I want to check if a bug has been found and can be fixed.

This is a bug that occurs when entering Korean characters.

1) Press the space key twice in the editor.
2) Use the left arrow or mouse to move to the first part of the sentence.
3) Enter text with the keyboard.
4) Characters other than the entered characters are added and entered into the editor.

We ask for your interest and support so that this problem can be resolved.

Thank you.

### ✔️ Expected result

Text entered on the keyboard is displayed as it is

### ❌ Actual result

Wrong characters added
  
## 📃 Other details

* Browser: Chrome
* OS: Win 10 Pro
* First affected CKEditor version: CK Editor 5 (on your demo page : https://ckeditor.com/ckeditor-5/demo/)
* Installed CKEditor plugins: CK Editor 5 (on your demo page : https://ckeditor.com/ckeditor-5/demo/)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Isn't it the same scenario as in this issue - https://github.com/ckeditor/ckeditor5/issues/8031?

**Comment by amada75** [comment]
> Hi, thanks for the report. Isn't it the same scenario as in this issue - #8031?

Hi, You are right. 
My case is exactly same with the issue you mentioned. 
I am wondering how long does it take to fix?

**Comment by FilipTokarski** [comment]
Fixing issues related to IME is not easy and it will require some bigger changes in the editor. We are aware of them, and hopefully when [migration to beforeInput](https://github.com/ckeditor/ckeditor5/issues/7462) is done, most of them will be fixed. However, due to lots of other things we're working on, we cannot guarantee any ETA for this.  
  
I'll close this ticket as a duplicate.

**Comment by sunny-pandora** [comment]
I'm using Mac, and have the same issue.
Does IME problem will solve on Windows? or would it be working on IOS as well?
