### ISSUE TITLE
[Docs/Feature] Merging editor builds ("superbuilds")

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#923]
ATM we provide separate editor builds: build-classic, build-inline, etc. They are OK but it's not very hard to come up with an application which needs two of them at the same time, e.g. one to edit blog posts (classic) and another to do some quick editing in the front–ent (balloon), etc..

In fact, we came across this issue implementing our website which demos all kinds of editors. Because we ship all the builds separately, once loaded into a webpage they:
* load all the same CSS twice,
* load all the features twice,
* **weigh twice as much**.

To address this issue I came up with a successful solution: a super-build exporting two editor builds (no duplication, weight of a single build + a couple of bytes for another creator). The entry point looks as follows:

```js
/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */

import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import InlineEditorBase from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';
import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadadapterPlugin from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import AutoformatPlugin from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockquotePlugin from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import EasyimagePlugin from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import HeadingPlugin from '@ckeditor/ckeditor5-heading/src/heading';
import ImagePlugin from '@ckeditor/ckeditor5-image/src/image';
import ImagecaptionPlugin from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImagestylePlugin from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImagetoolbarPlugin from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageuploadPlugin from '@ckeditor/ckeditor5-image/src/imageupload';
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
import ListPlugin from '@ckeditor/ckeditor5-list/src/list';
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Imageupload1Plugin from '@ckeditor/ckeditor5-image/src/imageupload';

class ClassicEditor extends ClassicEditorBase {};
class InlineEditor extends InlineEditorBase {};

ClassicEditor.build = InlineEditor.build = {
	plugins: [
		EssentialsPlugin,
		UploadadapterPlugin,
		AutoformatPlugin,
		BoldPlugin,
		ItalicPlugin,
		BlockquotePlugin,
		EasyimagePlugin,
		HeadingPlugin,
		ImagePlugin,
		ImagecaptionPlugin,
		ImagestylePlugin,
		ImagetoolbarPlugin,
		ImageuploadPlugin,
		LinkPlugin,
		ListPlugin,
		ParagraphPlugin,
		Imageupload1Plugin
	],
	config: {
		toolbar: {
			items: [
				'heading',
				'|',
				'bold',
				'italic',
				'link',
				'bulletedList',
				'numberedList',
				'imageUpload',
				'blockQuote',
				'undo',
				'redo'
			]
		},
		image: {
			toolbar: [
				'imageStyle:full',
				'imageStyle:side',
				'|',
				'imageTextAlternative'
			]
		},
		language: 'en'
	}
};


export default {
	ClassicEditor, InlineEditor
}
```

but 
* it's not very straightforward,
* there's no documentation how to do that,
* it does not re-use `build-config.js` from the builds, which means there's no easy way to create a future–proof (upgrade–proof) superbuild out of `ckeditor5-build-classic` and `ckeditor5-build-inline`

I think we should address the above with some good docs and maybe some smart solution using our building processes and configurations.

cc @Reinmar, @m-kr

**Comment by Reinmar** [comment]
> it's not very straightforward,

I may be biased but it is straightforward to me. Also, it may be improved by refactoring the code to avoid constructions like `Foo.x = Bar.x = {}` which reduce readability.

> there's no documentation how to do that,

That's what we may want to improve.

> it does not re-use build-config.js from the builds, which means there's no easy way to create a future–proof (upgrade–proof) superbuild out of ckeditor5-build-classic and ckeditor5-build-inline

It's possible to have such a superbuild described by `build-config.js` if we'd change its format, but would require a lot of effort. And won't be that flexible as creating your own `ckeditor.js` file as you presented above. E.g. both builds may have different feature set.

So, for me it's more about writing documentation.

Also, please keep in mind that a develope who wants to use two editors don't have to create a build with it. There are other ways to integrate CKEditor 5, like importing editors and plugins directly into your app's code. The documentation should clarify that such a construct only makes sense if you want to create build-like thing.

**Comment by m-kr** [comment]
I ❤️ this. It will reduce the weight of loaded scripts, improve performance. I'll try to create a build with every builds using in the demo.

> it does not re-use build-config.js from the builds, which means there's no easy way to create a future–proof (upgrade–proof) superbuild out of ckeditor5-build-classic and ckeditor5-build-inline

This is something about what I'm afraid, cause there is no guarantee whether my superbuild config will not be outdated in the future release.

**Comment by Reinmar** [comment]
I've just thought about one more thing – since in every build repository theres `src/ckeditor.js` you could actually clone 2+ such repos and import those files into your code. It'd still result in an optimised build.

However, since we're talking about cloning here (and not about installing from npm) this isn't that convenient really because you'd need to maintain multiple forks. So I'd rather recommend what Olek showed above or the "advanced integration" scenario. In other words – importing everything you need. 

Besides, let's not be that worried about this:

> my superbuild config will not be outdated in the future release.

It won't happen that often and in all scenarios, it requires some manual actions from you.

**Comment by wwalc** [comment]
> my superbuild config will not be outdated in the future release.
> 
> It won't happen that often and in all scenarios, it requires some manual actions from you.

I had exactly same thoughts as @m-kr. Unless you personally remember to verify build configs every release there is a good chance it will go out of sync.

**Comment by Reinmar** [comment]
OK, if we'd allow passing an array of creators here: https://github.com/ckeditor/ckeditor5-build-classic/blob/cd42fd78ed6943cbc180d116bf97e24c53751ed4/build-config.js#L10

Then, what would be here: https://github.com/ckeditor/ckeditor5-build-classic/blob/cd42fd78ed6943cbc180d116bf97e24c53751ed4/build-config.js#L13

And here: https://github.com/ckeditor/ckeditor5-build-classic/blob/cd42fd78ed6943cbc180d116bf97e24c53751ed4/src/ckeditor.js#L25

The `moduleName` can become an array too. But what about the export? What to export so webpack will create more globals?

Just to make it clear:

```js
	output: {
		path: path.resolve( __dirname, 'build' ),
		filename: 'ckeditor.js',
		libraryTarget: 'umd',
		libraryExport: 'default',
		library: buildConfig.moduleName
	},
```

Right now it takes the global variable name from the build config. Not sure if this is going to work if we provide an array there.

Anyway, this requires some research.

**Comment by Reinmar** [comment]
We need to document this, cause people ask about this from time to time and the above examples are outdated.

**Comment by abhijitkc** [comment]
How to Create the editor after exporting this 2 editors? For more clarification 

`ClassicEditor.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );`

How we write this?
