### ISSUE TITLE
Headings output wrong h tags

### ISSUE THREAD

**Issue by rayrfan** [ckeditor/ckeditor5#9232]
## 📝 Provide detailed reproduction steps (if any)

Go to [classic editor example page](https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html), inspect element on the `h1` element, it actually outputs `h2`.  And for `h2` element `h3` tag is used etc. 

<img width="927" alt="wrong heading" src="https://user-images.githubusercontent.com/633119/43168837-87f7bc60-8f53-11e8-890e-26147f1e1796.png">

### ✔️ Expected result

I don't know if this mismatch of headings is intentional? I'd think when **Heading 1** is chosen on the toolbar, people would expect `<h1>` instead of `<h2>` as the output. The only rationale I can think of is that say in a blog normally the post's heading takes `<h1>` so naturally the content's **Heading 1** would take `<h2>`.

### ❌ Actual result

The actual result is `<h2>` is generated for **Heading 1**, `<h3>` for **Heading 2** etc.

## 📃 Other details

* Browser: any browser
* OS: any OS
* First affected CKEditor version: all

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Yes, this is intentional but you can ajdust it to your needs in the plugin configuration. Read more in [headings documentation](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#heading-levels).

**Comment by FilipTokarski** [comment]
If you're not using Title plugin and need headings to be h1-h6, you can [configure them to be so](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-heading-levels).
