### ISSUE TITLE
Rethink image upload flow and image model & data while it is uploading

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#9238]
## 📝 Provide a description of the improvement

We have a problem with how uploading image is represented and handled in model and how it is handled in conversion. The problem is that an image which is uploading does not have `src` attribute. If such image is then downcasted, there is an image with no `src` attribute in the HTML. Then, when that's upcasted, the image is gone. It is not converted, because there is no `src` attribute.

This causes problems in some features that rely heavily on the editor state. One example is data compression, which may fail, because the model before and the model after compression may differ if the image was uploading when the compression got triggered.

I have two ideas:

1. Simpler. If the image is uploading, it should be downcasted in a way that upcasting it is possible, it would still be an image but displaying some kind of "the image is broken because upload was cancelled" message.
2. Complex. The image should be downcasted in such a way, that the upload would be continued after the image is upcasted. There are two problems here:
    * the image would have to be saved ad base64 in the data content (unless we save it in local storage but this has obvious limitations when it comes to re-uploading),
    * do not send images coded in base64 to other clients in RTC as the operation would be huge.

Not sure if the second idea is viable.

After we have some idea how we want to handle uploading and upload-resuming (if we do) we should consider this also for other asynchronously loaded features (not sure if auto-embed is any problematic in this regard, maybe some future features?). It would be good to have one system for all such cases.

Also related: https://github.com/ckeditor/ckeditor5/issues/5159

**Comment by Reinmar** [comment]
Image upload uses pending actions, so we can block other features while image upload is in progress. Hence, it's a low priority for now.

**Comment by Reinmar** [comment]
Scope for now:

*   Go with the simplest solution for now (upcast empty src)
    *   Tests in ckeditor5-image
    *   Tests for this case in RH (closes: cksource/collaboration-features#3859)
*   Try to figure out why this check was there in the first place
    *   Needs going down the git blame far past the work on image block/inline
    *   Also: verify whether in HTML it's correct to have only e.g. srcset+sizes, but no src
        *   In that case, pasting content from ext websites might more often result in broken images
        *   NOTE: According to MDN, src is required, so this should not be an issue
*   Open a followup to figure out whether we can provide a better UX
    *   Research how other editor handle such a case (e.g. Google Docs)

**Comment by Reinmar** [comment]
> *   Needs going down the git blame far past the work on image block/inline

Done already: Nothing found. Changes from 2017.
