### ISSUE TITLE
Add @ckeditor/ckeditor-cloud-services-core to this repo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#924]
`@ckeditor/ckeditor-cloud-services-core` depends on `@ckeditor/ckeditor5-utils` and e.g. `@ckeditor/ckeditor5-easy-image` depends on `@ckeditor/ckeditor-cloud-services-core`. So, it'd be good to release `@ckeditor/ckeditor-cloud-services-core` together with the rest of our repos. Which means that this package should be added to our development env.

Unfortunately, it does not contain the `ckeditor5-*` prefix so there are issues like https://github.com/cksource/mgit2/issues/72 or issues with `npm run test` if the directory name doesn't start with `packages/ckeditor5-*`.

**Comment by Reinmar** [comment]
I pushed https://github.com/ckeditor/ckeditor-cloud-services-core/tree/t/ckeditor5/924 with how this repository will need to look like.

**Comment by pomek** [comment]
After fixing [CHANGELOG.md](https://github.com/ckeditor/ckeditor-cloud-services-core/blob/bb9aa5b14ce35ca0478b81d6b9819d57415b364e/CHANGELOG.md), our release tools handle this package.
