### ISSUE TITLE
Renaming the image model element to imageBlock.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9246]
This is a follow-up of the #9103

For backwards compatibility we decided to preserve the `image` element in the model for block images.

To correspond with the `imageInline`, maybe it should be renamed to `imageBlock`. This should be further discussed because this will increase an already vast scope of breaking changes in this feature.

**Comment by oleq** [comment]
Let's do this at the very end to avoid conflicts.

**Comment by niegowski** [comment]
Closed in #9707
