### ISSUE TITLE
The test passes, but config has unsupported font option

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#9253]
## Provide a description of the task

It looks like the test for `fontsizeediting.js` https://github.com/ckeditor/ckeditor5/blob/bdb49c58c9e985346dd55ff239cbf0cd6079ddb1/packages/ckeditor5-font/tests/fontsize/fontsizeediting.js#L78-L81 contains unsupported font option, but the test passes. In this example, the `model` can't be a number, but it should be a valid "length" or "percentage" value (i.e. `'14px'`).

It would be great to review the whole test suite and verify if other cases are valid.

**Comment by pomek** [comment]
We have also some errors in docs:

- https://github.com/ckeditor/ckeditor5/blob/31aabfd1886b857e0b69f7db744dea34ee2d4a44/packages/ckeditor5-font/src/fontsize.js#L114
- https://github.com/ckeditor/ckeditor5/blob/31aabfd1886b857e0b69f7db744dea34ee2d4a44/packages/ckeditor5-font/src/fontsize.js#L119

Missing `'`.

In the linked code, https://github.com/ckeditor/ckeditor5/blob/bdb49c58c9e985346dd55ff239cbf0cd6079ddb1/packages/ckeditor5-font/tests/fontsize/fontsizeediting.js#L78-L81

we should go with:

```js
{
	model: '14px',
	title: '14'
}
```

**Comment by CatStrategist** [comment]
I went through a normalizer for font-size values and number value as a model is correctly supported so user may define it as such without any issues. Browsers convert number units to pixels. Also added missing paragraphs :)
