### ISSUE TITLE
[Table Caption] Default caption position: below or above table?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9254]
## Provide a description of the task

Extracted from [https://github.com/ckeditor/ckeditor5/issues/9223#issuecomment-800373167:](https://github.com/ckeditor/ckeditor5/issues/9223#issuecomment-800373167:)

> When you google "table caption" and check the images you'll find out that the caption usually precedes the table (AFAIR this is LaTeX standard). 
> 
> \> Figure captions are generally placed below the figures, while table captions must be placed above the tables. This is because we generally read tables from the top down, and therefore want to see the caption at the top. Figures are not always read top down.
> 
> via [https://pressbooks.bccampus.ca/technicalwriting/chapter/figurestables/](https://pressbooks.bccampus.ca/technicalwriting/chapter/figurestables/)
> 
> Also, check the [comprehensive Wikipedia guide to tables](https://en.wikipedia.org/wiki/Help:Table) to see this is a preferred order.

**Comment by oleq** [comment]
cc @magda-chrzescian

**Comment by Reinmar** [comment]
We need a decision where to place this caption by default.

We should use CSS to control the place. In the model/data this should be const.

**Comment by magda-chrzescian** [comment]
The inconsistency between the table and image captions seems to be less of a problem than the content readability, so I'd rather see captions above tables.

**Comment by maxbarnas** [comment]
Should I fix this with CSS? (look at the table helper)

![image](https://user-images.githubusercontent.com/1112966/112165911-75849580-8bef-11eb-90af-127b72dd4b43.png)

**Comment by oleq** [comment]
> Should I fix this with CSS? (look at the table helper)

You didn't share DOM so I'm just guessing but it looks like the selection handle is located somewhere deeper in the structure instead of the top-most widget wrapper (figure?) and that's why it is positioned relative to the wrong element.

**Comment by maxbarnas** [comment]
Sorry for missing it. The DOM looks like this: 
![image](https://user-images.githubusercontent.com/1112966/112280414-49b3ef00-8c85-11eb-80fb-e9188674a3ab.png)

Helper is placed above table using `transform: translateY (100%)`. I wonder if I rather should try to bend CSS to my will ;) or try to change the placement of the helper. But that would affect a lot of other components in the editor, am I right?
