### ISSUE TITLE
Is there an easy way to group toolbar icons into dropdowns?

### ISSUE THREAD

**Issue by rayrfan** [ckeditor/ckeditor5#9255]
There are many features represented by icons on the toolbar (specifically I'm using the classic build) and they are getting crowded, so I'm just wondering if there is an easy way to configure the toolbar icons into dropdowns? For example, say group 'bold', 'italic', 'underline', 'strikethrough' into a dropdown and let 'bold' to show up on top with an downward arrow next to it and clicking on the arrow shows the other icons 'italic' etc.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. There is currently no handy way to do it unfortunately. However we have an open [feature request](https://github.com/ckeditor/ckeditor5/issues/1472) for this and a [pull request](https://github.com/ckeditor/ckeditor5/pull/1473) that actually introduced such feature, but at that time it didn't make it into official release. Please [check the code proposed there](https://github.com/ckeditor/ckeditor5/pull/1473/commits/af32896846a63bb255a083b2826c30217e1b0bf0) as it should fit your use case ( with some minor tweaks ).  
I'll close this ticket as a duplicate.
