### ISSUE TITLE
Adding Image inline between text, maintaining the flow of the sentence.

### ISSUE THREAD

**Issue by SaketSinha** [ckeditor/ckeditor5#9256]
Context: I am using CKEditor to allow teachers to add questions, in the process to create question papers. We have encountered some questions that need images to be inserted in the same line as the text (currently the image goes into the next line.

Sample questions:
1. A small image is part of the question: 
![1](https://user-images.githubusercontent.com/25716415/111400925-5026f180-86ee-11eb-8250-66544f07f05c.jpeg)
![2](https://user-images.githubusercontent.com/25716415/111400968-66cd4880-86ee-11eb-855a-4a2750b98efe.jpeg)

2. A group of images + text makes up the complete question sentence
![3](https://user-images.githubusercontent.com/25716415/111401047-88c6cb00-86ee-11eb-86d6-53573b652671.jpeg)

## 📝 Improvement
Currently, whenever I add a new image, it gets added as part of the new line, which I can then choose to position as 
![image](https://user-images.githubusercontent.com/25716415/111401655-b3655380-86ef-11eb-8c56-d28e8be80719.png) however, this does not result in achieving what the example image shows above.

If this can be achieved currently, please let me know the steps to achieve it.
If any more inputs are required please let me know.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In fact, we are currently working on implementing inline images and there's already a feature request ticket [here](https://github.com/ckeditor/ckeditor5/issues/2052). Unfortunately there is still lots of work to do so we cannot guarantee any ETA for this, but you can always check what's [currently on our roadmap](https://github.com/ckeditor/ckeditor5/issues/9199) and track it there.  
  
I'll close this ticket as a duplicate.
