### ISSUE TITLE
When insert new table, the table properties is not display

### ISSUE THREAD

**Issue by lihaiou32** [ckeditor/ckeditor5#9257]
I clone the code at 2021-3-16 , install the "ckeditor5-build-decoupled-document" and run the sample, insert new table ,the page like this:

![image](https://user-images.githubusercontent.com/13082463/111433430-3e1e7080-8739-11eb-8064-dd41c6f1a221.png)

but on the site : https://ckeditor.com/ckeditor-5/demo/#document
![image](https://user-images.githubusercontent.com/13082463/111433621-7de55800-8739-11eb-871f-6fec66ed8460.png)

what should I do can show the 'table properties' dropdown? (My English is poor.)

**Comment by FilipTokarski** [comment]
Hi, you need to import `TableProperties` and  `TableCellProperties` plugins and add them in table's toolbar configuration configuration, please [see the docs](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-and-cell-styling-tools-2).

**Comment by lihaiou32** [comment]
OK tsk
