### ISSUE TITLE
editor.setData(<content>) Filtered the style attribute of the li element in the ordered unordered list

### ISSUE THREAD

**Issue by jstf9673** [ckeditor/ckeditor5#9258]
1、open link [https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html](url)
2、open chrome console，The code entered is as follows：
`editor.setData('<p style="margin-left:6em;">啊实打实的</p><ul style="list-style-type:circle;"><li style="margin-left:6em;">&nbsp;啊实打实的</li><li style="margin-left:6em;">&nbsp;洒大地</li><li style="margin-left:6em;">&nbsp; 啊实打实的</li><li style="margin-left:6em;">&nbsp;洒大地上</li><li style="margin-left:6em;">&nbsp;啊时间大时代</li></ul>')`

The result is as follows:
![image](https://user-images.githubusercontent.com/10250573/111444727-a410f500-8745-11eb-9e26-fece2d4dc104.png)
![image](https://user-images.githubusercontent.com/10250573/111446008-e850c500-8746-11eb-9495-a8dc71285204.png)
the style attribute of the li element Disappeared

browser version： 89.0.4389.82（正式版本） (x86_64)

**Comment by LukaszGudel** [comment]
Hello, thank you for the report. Issue that you are describing here is not a bug but rather default editor behaviour. Most of attributes (including style attribute) are stripped off by the editor. To preserve styles on `<li>` tags you need to add a little bit of custom code during editor creation:

```js
ClassicEditor
   .create( ... )
   .then( editor => {
        editor.model.schema.extend( 'listItem', {
            allowAttributes: '__style'
        } );
        editor.conversion.for( 'upcast' ).attributeToAttribute( {
            model: {
                name: 'listItem',
                key: '__style'
            },
            view: {
                name: 'li',
                key: 'style',
                value: /[\s\S]+/
            }
        } );
        editor.conversion.for( 'downcast' ).add( dispatcher => {
            dispatcher.on('attribute:__style:listItem', ( evt, data, conversionApi ) => {
                const viewElement = conversionApi.mapper.toViewElement( data.item );
                conversionApi.writer.setAttribute( 'style', data.attributeNewValue, viewElement );
          } );
        }, { priority: 'highest' } );
     } )
```
You can find more useful information about this topic on #4517 and in [Framework section](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/overview.html) in our docs. Please, let me know if this code snippet is fixing your issue.
