### ISSUE TITLE
Could not load existing sourcemap of "../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js"

### ISSUE THREAD

**Issue by Niemad78** [ckeditor/ckeditor5#9259]
Hi, I try to use CKEditor in my react app, I import 2 packages with npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic and import them in my component like that : 

import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

Then I edit in my code : 

`            <CKEditor
              editor={ClassicEditor}
              data={text}
              value={conceptRecup.description_concept}
              onChange={
                (event, editor) => {
                  const data = editor.getData()
                  setConceptRecup({
                    ...conceptRecup,
                    description_concept: data,
                  })
                }
              }
            />`

When I want to launch my app, I had the below error message in my terminal : 

Could not load existing sourcemap of "../node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js"

Then print in my terminal a long code and my app doesn't work. 

* Browser: Mozilla
* OS: Ubuntu
* First affected CKEditor version: 
*     "@ckeditor/ckeditor5-build-classic": "^26.0.0",
      "@ckeditor/ckeditor5-react": "^3.0.2",

**Comment by pomek** [comment]
> Then print in my terminal a long code and my app doesn't work.

Could you share the error?

**Comment by Niemad78** [comment]
![Capture d’écran du 2021-03-17 12-35-45](https://user-images.githubusercontent.com/70136274/111463564-01924b00-8720-11eb-8767-2be8ab8fc059.png)

**Comment by pomek** [comment]
Unfortunately, this error is not helpful and does not say too much.

Could you provide steps that allow us to reproduce the issue? It includes configurations for babel, webpack, and/or other tools you use in the project.

**Comment by Niemad78** [comment]
I just install CKEditor package in command line with npm and import them in my component : 

1.
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

2.
            <CKEditor
              editor={ClassicEditor}
              data={text}
              value={conceptRecup.description_concept}
              onChange={
                (event, editor) => {
                  const data = editor.getData()
                  setConceptRecup({
                    ...conceptRecup,
                    description_concept: data,
                  })
                }
              }
            />

Even if I don't wrote second part, just import modules, makes my app down.

Below dependencies that I use :

  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.1.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "eslint": "^7.12.1",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^4.3.0",
    "lint-staged": "^10.5.0",
    "nodemon": "^2.0.7",
    "parcel-bundler": "^1.12.3",
    "prettier": "^2.1.2",
    "proptypes": "^1.1.0",
    "sass": "^1.32.6"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^26.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "axios": "^0.21.1",
    "date-fns": "^2.17.0",
    "mysql": "^2.18.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-calendar": "^3.3.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5"
  },

Babel config : 

{
    "plugins": [
        ["@babel/plugin-transform-runtime", { "regenerator": true }]
    ]
}

The other config that I had, was prettier and eslint

**Comment by Reinmar** [comment]
This does not seem to be a CKEditor issue. Those sourcemaps work for (pretty much) everyone else. So, the problem is most likely somewhere in the server / build process configuration. Maybe @pomek  will have some idea, but in general – this is beyond our reach.
