### ISSUE TITLE
Dragging content in the comments only mode removes the dragged content 

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#9268]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/collaboration/comments/comments-only-mode.html
2.  Drag some content from one place in the editor to some other place in the editor

### ✔️ Expected result

No content change

### ❌ Actual result

Dragged content is removed

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
How does cut (ctrl+x) work?

**Comment by niegowski** [comment]
> How does cut (ctrl+x) work?

cut does nothing as expected

**Comment by niegowski** [comment]
This could be fixed by adding 

```javascript
		// Prevent removing dragged fragment on drop.
		this.listenTo( this.editor.model, 'deleteContent', evt => evt.stop(), { priority: 'highest' } );
```

here:

https://github.com/cksource/collaboration-features/blob/33942442eea08b1ffe34e4be8833aa62cb5bc16b/packages/ckeditor5-comments/src/commentsonly.js#L97-L116

**Comment by niegowski** [comment]
This could be fixed by adding 

```javascript
        // Prevent removing dragged fragment on drop.
        this.listenTo( this.editor.model, 'deleteContent', evt => evt.stop(), { priority: 'highest' } );
```

In CommentsOnly plugin

and to disable drop target marker:

```javascript
        this.listenTo( viewDocument, 'dragging', ( evt, data ) => {
            data.dataTransfer.dropEffect = 'none';
            evt.stop();
        }, { priority: 'highest' } );
```

**Comment by scofalik** [comment]
This makes me thinking whether we should an easier way to just disable this feature. Like we have with table selection feature and `isEnabled` (which may not be used anymore as we enabled table selection for track changes ;)).

**Comment by niegowski** [comment]
With `isEnabled` we would also disable copying content from the editor by dragging it to other editors

**Comment by Mgsy** [comment]
The content is removed only in Safari. Chrome and Firefox don't remove the content but leave the drag&drop marker visible.

**Comment by niegowski** [comment]
> The content is removed only in Safari. Chrome and Firefox don't remove the content but leave the drag&drop marker visible.

It's because of other chrome/firefox chrome with modyfing text nodes. Try dragging content out of editor to for example dev tools console, or dragging some widget

**Comment by mlewand** [comment]
We can try check if it's quickly solvable. If it requires more time, we're fine to fix it later.
