### ISSUE TITLE
Drag and drop is not working on text in Safari

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9271]
## 📝 Provide detailed reproduction steps (if any)

1. Go to http://127.0.0.1:8080/ckeditor5/latest/features/pasting/drag-drop.html
2. Select text and try to drag it.
3. 
### ✔️ Expected result

Text is dragged and the drag marker is visible in the editor.

### ❌ Actual result

Selection is lost.

## 📃 Other details

* Browser: Safari 14.0.3
* OS: MacOSX Big Sur

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by magda-chrzescian** [comment]
The same happens on Android 6.0.1 and Chrome 89.

**Comment by maxbarnas** [comment]
Actually, it works. Need to wait longer for the selection to be draggable.
