### ISSUE TITLE
CI jobs are pending for a long time

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9273]
## Provide a description of the task

Yesterday I had a case where after a PR my job was pending for an hour or so.

Despite the fact that we just moved to a paid plan for TravisCI it still sometimes take a long time to run (that's especially true during our working hours).

I think it's just due to the fact that we don't have enough parallel jobs. When CKE4 and CKE5 are triggering Travis (both probably takes around 20-30 mins to complete) there's no room for new jobs. Especially given that we run 2 jobs per a PR.

Maybe it's time to say a final farewell to Travis?

**Comment by pomek** [comment]
After splitting the single thread into parallel jobs, the CI speeded up. I guess it's ok for now, and we can close the ticket.
