### ISSUE TITLE
Drag & drop: it's possible to drag content outside restricted editing area

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9279]
## 📝 Provide detailed reproduction steps (if any)

1. Go to http://localhost:8080/ckeditor5/latest/features/restricted-editing.html
2. Switch to restricted mode
3. Select some content in restricted area and drag it outside

### ✔️ Expected result

Content should not be dragged outside restricted area

### ❌ Actual result

Content is dragged outside restricted area:  
  
![0_tp3](https://user-images.githubusercontent.com/34380544/111593807-a5383580-87ca-11eb-81f9-97584d6acdc9.gif)

## 📃 Other details

* Browser: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
might be related to #9286

**Comment by mlewand** [comment]
might be related to #9286
