### ISSUE TITLE
The Italic feature icon is serif while other icons are sans-serif

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#928]
While reading #910 I've have one more thing to add (sorry for that but @wwalc told me to report this).

So the Italic feature icon is a serif one while other icons are sans-serif

![selection_005](https://user-images.githubusercontent.com/247363/38087281-d764e816-3357-11e8-8aba-669ab119c8af.png)

I don't see a better solution though.

**Comment by scofalik** [comment]
Well, "slash" icon might be not the best idea.

**Comment by jodator** [comment]
> Well, "slash" icon might be not the best idea.

Yeah I know that's probably a reason but since we're looking at icons... :wink:

**Comment by Reinmar** [comment]
Italicised lowercased "i" looks like an "info point" ;) We've been there.

**Comment by mlewand** [comment]
Since this issue issue is inactive for a quite some time, and we were unable to come up with a constructive proposal I'll close it for now.
