### ISSUE TITLE
Feature tour balloon is in the wrong place after switching to restricted mode

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9280]
## Steps to reproduce
1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/restricted-editing.html
2. Switch demo to restricted editing mode

## Actual behavior:
Balloon stays in wrong place, there's a warning in the console:
```
assets.js:4 [attachTourBalloon] The target DOM node for the feature tour balloon does not exist. 
{text: "Click to switch restricted editing mode."}
```

**Comment by godai78** [comment]
This will be difficult to apply, but we may use a simple hack - move the restricted editing toolbar item to the leftmost position, this way it will not change position on switch. I'll test it in a moment.

**Comment by godai78** [comment]
![](https://user-images.githubusercontent.com/68123541/113666515-abc21a80-96af-11eb-9501-3c9c19398f62.gif)

**Comment by godai78** [comment]
Merged quickfix, keeping this for further work.

**Comment by godai78** [comment]
Fixed, closing issue.
