### ISSUE TITLE
Drag and drop doesn't work on Android 6.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9282]
## 📝 Provide detailed reproduction steps (if any)

1. Select a text or widget in the sample http://127.0.0.1:8080/ckeditor5/latest/features/pasting/drag-drop.html and try to drag it.

### ✔️ Expected result

It should be dragged.

### ❌ Actual result

Nothing happens.

## 📃 Other details

* Browser: Chrome 89
* OS: Android 6.0.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Version 6 is a little bit outdated, so we'll not provide features that advanced as dnd to it.
