### ISSUE TITLE
Update Markdown guide known issues

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#9283]
> *   The horizontal rule is not yet supported by the [autoformatting](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) feature but it gets output to Markdown nevertheless if inserted using the toolbar button. GitHub issue: [#5720](https://github.com/ckeditor/ckeditor5/issues/5720).

This issue was resolved a while ago. Check the PR for details: #8646

**Comment by godai78** [comment]
Looks like this was covered before, it's not mentioned in the docs, neither here: [https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html](https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html) nor here: [https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html](https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html)  
  
It's even mentioned as a feature in the latter.

**Comment by AnnaTomanek** [comment]
Fixed on the `release` branch.
