### ISSUE TITLE
Drag & drop: dragging restricted region into another creates a duplicate

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9286]
## 📝 Provide detailed reproduction steps (if any)

1. Go to http://localhost:8080/ckeditor5/latest/features/restricted-editing.html
2. Switch to restricted editing mode
3. Fully select some restricted editing area
4. Drag it into another restricted area

### ✔️ Expected result

Only text is dropped, like when doing cut/paste

### ❌ Actual result

A duplicated restricted area is created inside:  
  
![0_tp4](https://user-images.githubusercontent.com/34380544/111598771-d8c98e80-87cf-11eb-880a-9680453d8603.gif)

## 📃 Other details

* Browser: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
There is also a related issue (not a regression):

![](https://user-images.githubusercontent.com/1232187/111627207-1f7ab100-87ef-11eb-8c67-9491fd1f9c7c.gif)
