### ISSUE TITLE
[Android] Editor remains focused on the selected link/comment/change.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9287]
## 📝 Provide detailed reproduction steps (if any)

1. Run Chrome and enter the responsive mode, select a device, for example, Galaxy S5
2. or open the Chrome browser on the Android device.
2. Open any editor's latest sample and select a part of the text with the link/comment/change
4. Try to set a caret in any other place of the editor.

It seems that it's related to the balloon toolbar - if some selection triggers the balloon, it can't be deselected.

### ✔️ Expected result

The caret should appear in the selected place.

### ❌ Actual result

Nothing happens, if the editor is focused, it always focuses the previously selected content.
![error1](https://user-images.githubusercontent.com/14334820/111486304-aa987000-8737-11eb-8706-bad3c7145b9d.gif)

## 📃 Other details

* Browser: Chrome 89
* OS: Android 9
* First affected CKEditor version: **27.0.0**

**Comment by FilipTokarski** [comment]
There's also a more basic scenario for this - create a selection by holding down some word. You cannot deselect it, unless you blur the whole editor:  

https://user-images.githubusercontent.com/34380544/111609077-3662d880-87da-11eb-9bed-8d71ac91aef6.mp4

**Comment by LukaszGudel** [comment]
One more thing to add - this only occurs on Chrome browser. On Firefox and some default Xiaomi browser it works correctly for me.

**Comment by oleq** [comment]
"Fixed" in #9298.
