### ISSUE TITLE
Maximize  in CKEDITOR

### ISSUE THREAD

**Issue by kumarsai4u** [ckeditor/ckeditor5#9290]
How to enable Maximize button in CKEDITOR 5

**Comment by FilipTokarski** [comment]
Hi, if you mean maximize plugin, like in CKEditor 4, then currently there is no such thing in CKEditor 5. We have however a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/1235) - so you can track it there. Also feel free to add there a 👍   and any other information that you find important.  
  
I'll close this ticket as a duplicate.

**Comment by pikulinpw** [comment]
Following the discussion about the feature to maximize the editor to full screen, I developed a plugin that solves this problem. I would appreciate it if you tried it and share your experience using it. Any additions, suggestions or questions are welcome. Your feedback will help make the plugin even better!

https://github.com/pikulinpw/ckeditor5-fullscreen

**Comment by Witoso** [comment]
Thank you @pikulinpw for sharing  your work! :blush:

**Comment by pikulinpw** [comment]
> Thank you @pikulinpw for sharing  your work! 😊

Thank you too, I hope my plugin will help and solve the problem, if there are any problems with the plugin or something in it will be missing, write and I will finalize it
