### ISSUE TITLE
DataController#toView() should have default value for options parameter

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#9293]
## 📝 Provide a description of the improvement

Some time ago we started to pass `options` parameter (available in `DataController#get()` and `#toView()` methods. While in `get()` it received default value (`{}`), it does not have a default value in `toView()`. Sometimes we use `toView()` directly and when doing this we have conversion errors in converters that check `conversionApi.options` object. One such place is clipboard handling.

Same goes for `stringify()`.

**Comment by pomek** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/commit/f77a3d57bddb96ae3280736f974cfd0b148611cb.
