### ISSUE TITLE
Errors in the console when using on JSFiddle

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#930]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

1.0.0-beta.1

## 📋 Steps to reproduce

1. Open https://jsfiddle.net/szymonkups/pr7e2oLb/, make sure console is open.
2. Press enter inside editor contents.

## ✅ Expected result
No errors shown.

## ❎ Actual result
Error displayed:
```
Uncaught TypeError: Cannot read property 'parentNode' of null
    at it (scroll.js:265)
    at Je (scroll.js:49)
    at Vm.scrollToTheSelection (view.js:265)
    at yc.listenTo (enter.js:41)
    at yc.fire (emittermixin.js:195)
    at yc.Uf.t.on (enterobserver.js:31)
    at yc.fire (emittermixin.js:195)
    at hm.fire (domeventobserver.js:96)
    at hm.onDomEvent (keyobserver.js:28)
    at Kc.listenTo (domeventobserver.js:81)
```

## 📃 Other details that might be useful
JSFiddle is inserting contents inside iframe - this might be connected.

**Comment by oleq** [comment]
> JSFiddle is inserting contents inside iframe - this might be connected.

It's definitely about the iframes.

**Comment by Reinmar** [comment]
There's a chance that https://github.com/ckeditor/ckeditor5-utils/pull/240 fixes this issue. It also describes it more precisely.

**Comment by Reinmar** [comment]
Encountered it on https://jsfiddle.net/adsvfnn0/.

We should fix this ASAP because it looks very bad and makes it impossible to create valuable JSFiddles.

**Comment by oleq** [comment]
I found the root of the issue and proposed the fix in https://github.com/ckeditor/ckeditor5-utils/pull/242 based on the initial contributor's [PR](https://github.com/ckeditor/ckeditor5-utils/pull/240/files).
