### ISSUE TITLE
Block images smaller than 50px render incorrectly in table cells

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9300]
![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/5c14cfed-76d5-4483-9b58-1f5b49c5ed4e)

A regression after https://github.com/ckeditor/ckeditor5/pull/9173.

**Comment by magda-chrzescian** [comment]
It is not a table-specific problem, the same happens in the entire editor content.

**Comment by oleq** [comment]
Closed in #9616.
