### ISSUE TITLE
Ck-Editor-5 for vue-2 :// CKEditorError: ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by BarathAspi** [ckeditor/ckeditor5#9302]
## 📝###  **CKEditorError: ckeditor-duplicated-modules**

1. I followed the steps listed down here [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html](url) by importing the components locally , globally **(one by one)**.

2. When I try to install and import the extension modules for the classic editor of the Ck-Editor-5 I get the following error.

3. For further reference I've attached the code of the App.vue and Main.js files below...

```
/**Main.js */

import Vue from 'vue'
import App from './App.vue'
import CKEditor from '@ckeditor/ckeditor5-vue2';
import VueCompositionApi from "@vue/composition-api";

Vue.config.productionTip = false
Vue.use( CKEditor );

Vue.use(VueCompositionApi); 

new Vue({
  render: h => h(App),
}).$mount('#app')

```

```
<!-- App.vue -->

<template>
  <div>
    <div v-html="editorData" class="mt-5 text-center" />

    <div class="mx-3 mt-15">
      <ckeditor
        :editor="editor"
        v-model="editorData"
        style=""
        :config="editorConfig"
      />
    </div>
    <div class="mt-5 ">{{ editorData }}</div>
  </div>
</template>

<script>
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import CKEditor from "@ckeditor/ckeditor5-vue2";
import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";

export default {
  setup() {
    const editor = ClassicEditor;
    const editorData = "<p>Content of the chapter.</p>";
    const editorConfig = {
      plugins: [EssentialsPlugin],
    };
    return {
      editor,
      editorData,
      editorConfig,
    };
  },
  components: { ckeditor: CKEditor.component, },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
                                                                                                

### ✔️ Expected result

The Editor with applied modules

### ❌ Actual result

![BrowserScreenShot](https://user-images.githubusercontent.com/74296707/111777824-d2bfd480-88d9-11eb-9171-0c813c755f0c.png)

## 📃 Other details

* Browser:Google  Chrome Version 87.0.4280.88 (Official Build) (64-bit)
* OS: Ubuntu 18.04.3 LTS
* First affected CKEditor version: 5
* Installed CKEditor plugins: Every plugin

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, [duplicated-modules](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) error happens because you are trying to add plugins to editor build, which is not allowed. So if you want to use for example Classic Build, you [don't need to add any other plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html#using-es6-modules). On the other hand, if you want to customize the build with some plugins of your choice, you need to [build it from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html#using-ckeditor-from-source).

**Comment by BarathAspi** [comment]
I did'nt configure the config.js and now after configuring as shown in the documentation everything works fine..
