### ISSUE TITLE
Word Headings turned into HTML list

### ISSUE THREAD

**Issue by LangQian** [ckeditor/ckeditor5#9308]
## 📝 Provide detailed reproduction steps (if any)

1. Use the sample editor [here](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/pasting/paste-from-word.html)
2. Copy the whole documentation from the attached [Sample.docx](https://github.com/ckeditor/ckeditor5/files/6173784/Sample.docx)
3. Paste it into the editor

### ✔️ Expected result

Headings, font size and corresponding numbers should be preserved.

### ❌ Actual result

Headings were converted into a list, all the numbers became 1, and the font size was also changed.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
@LukaszGudel, can you take a look at this issue?

**Comment by LukaszGudel** [comment]
Hello, thank you for the report. I can confirm this issue or in fact there are two separated issues when pasting this content from Word to the editor:

1. Block elements inside list items - currently, CKEditor5 is not supporting block elements like headings or multiple paragraphs inside a list item. You can read more about this in #2973. This issue has high priority and should be targeted soon but I can't promise any ETA just yet.
2. Unsupported list style - currently, CKEditor5 supports only 6 predefined styles for ordered lists and 3 predefined styles for unordered lists (details [here](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#list-styles)). There is already a feature request for custom list styles in #8687 so you can track it there. 

I'm closing this ticket as a duplicate.
