### ISSUE TITLE
The placeholder is invisible

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#931]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-engine/tests/manual/placeholder.html.

## ✅ Expected result
There should be visible placeholder.

## ❎ Actual result
The placeholder is invisible.

## 📃 Other details that might be useful

**Screenshot**

<img width="1175" alt="screen shot 2018-03-30 at 13 20 56" src="https://user-images.githubusercontent.com/10219857/38136252-90464c4c-341d-11e8-8233-690230c910df.png">

OS: All platforms
Browser: All browsers

**Comment by oleq** [comment]
It is `class="ck-placeholder"`, it should be `class="ck ck-placeholder"`.
