### ISSUE TITLE
CKEDTOR5 not working with Angular 9.1

### ISSUE THREAD

**Issue by afeef1915** [ckeditor/ckeditor5#9312]
>Problem 

     dependencies  issue after installing in angular 9.1 version.

>Errors

 					npm install --save @ckeditor/ckeditor5-angular
					npm WARN @angular-devkit/build-angular@0.1102.5 requires a peer of @angular/compiler-cli@^11.0.0 || ^11.2.0-next but none is installed. You must install peer dependencies yourself.
					npm WARN @angular-devkit/build-angular@0.1102.5 requires a peer of typescript@~4.0.0 || ~4.1.0 but none is installed. You must install peer dependencies yourself.
					npm WARN @ng-select/ng-option-highlight@0.0.2 requires a peer of @angular/common@^8.0.3 but none is installed. You must install peer dependencies yourself.
					npm WARN @ng-select/ng-option-highlight@0.0.2 requires a peer of @angular/core@^8.0.3 but none is installed. You must install peer dependencies yourself.
					npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
					npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/core@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
					npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/forms@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
					npm WARN @ngtools/webpack@11.2.5 requires a peer of @angular/compiler-cli@^11.0.0 || ^11.2.0-next but none is installed. You must install 
					peer dependencies yourself.
					npm WARN @ngtools/webpack@11.2.5 requires a peer of typescript@~4.0.0 || ~4.1.0 but none is installed. You must install peer dependencies 
					yourself.
					npm WARN angular2-ladda@2.0.2 requires a peer of @angular/common@^8.1.0 but none is installed. You must install peer dependencies yourself.
					npm WARN angular2-ladda@2.0.2 requires a peer of @angular/core@^8.1.0 but none is installed. You must install peer dependencies yourself. 
					npm WARN karma-jasmine-html-reporter@1.5.3 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.
					npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\@angular\compiler-cli\node_modules\fsevents):
					npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
					npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\karma\node_modules\fsevents):
					npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
					npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\rollup\node_modules\fsevents):
					npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
					npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
					npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
					npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
					npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
					npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

					+ @ckeditor/ckeditor5-angular@2.0.1
					updated 1 package and audited 1839 packages in 76.847s

					93 packages are looking for funding
					  run `npm fund` for details

					found 8 vulnerabilities (7 low, 1 moderate)
					  run `npm audit fix` to fix them, or `npm audit` for details

Ng version

 
					
						Angular CLI: 9.1.0
						Node: 12.16.1
						OS: win32 x64

						Angular: 9.1.0
						... animations, cli, common, compiler, compiler-cli, core, forms
						... language-service, platform-browser, platform-browser-dynamic
						... router
						Ivy Workspace: Yes

						Package                           Version
						-----------------------------------------------------------
						@angular-devkit/architect         0.901.0
						@angular-devkit/build-angular     0.901.0
						@angular-devkit/build-optimizer   0.901.0
						@angular-devkit/build-webpack     0.901.0
						@angular-devkit/core              9.1.0
						@angular-devkit/schematics        9.1.0
						@angular/cdk                      9.1.3
						@ngtools/webpack                  9.1.0
						@schematics/angular               9.1.0
						@schematics/update                0.901.0
						rxjs                              6.5.4
						typescript                        3.8.3
						webpack                           4.42.0

* After Npm  Audit

>  Run  npm install --save-dev karma@6.2.0  to resolve 2 vulnerabilities
>  Run  npm install --save-dev protractor@7.0.0  to resolve 1 vulnerability
>  Run  npm install angular-datatables@11.1.1  to resolve 2 vulnerabilities
>  Run  npm install @angular/cli@11.2.5  to resolve 2 vulnerabilities
>  Run  npm update ini --depth 3  to resolve 1 vulnerability
 
Note i did not want to update angular version from 9 to 11.

* please advice how can i resolve issue without upgrading to angular 11.

**Comment by Mgsy** [comment]
@LukaszGudel, can you take a look at this issue?

**Comment by LukaszGudel** [comment]
Hello @afeef1915. It looks like those vulnerabilities come from angular itself and its dependencies and not from our ckeditor5-angular package. I can see that you are using Angular CLI version 9.1.0, while there is a 9.1.15 version available. I tried to recreate your issue, and with Angular CLI 9.1.15 creating new project and installing `@ckeditor/ckeditor5-angular` is resulting in 0 vulnerabilities. When using 9.1.0 `npm audit` reported 7 vulnerabilities in my case. 

You can try to update your packages to the highest possible versions without introducing breaking changes to your project. Let me know if this fixes your issue.

**Comment by afeef1915** [comment]
> n

Thanks for the help dev.

I will try this solution .

Thanks very much.
