### ISSUE TITLE
Watchdog should not import CKEditor 5 utils as this leads to package duplication problem in integrations

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#9315]
In other words, we should get rid of this line: [https://github.com/ckeditor/ckeditor5/blob/a127c971ba23e4e6ed58d83327db617d85063b24/packages/ckeditor5-watchdog/src/contextwatchdog.js#L12](https://github.com/ckeditor/ckeditor5/blob/a127c971ba23e4e6ed58d83327db617d85063b24/packages/ckeditor5-watchdog/src/contextwatchdog.js#L12)

And write the \`toArray()\` utility for this package independently.

The current situation leads to the package duplication problem because the watchdog is bundled in the integration library independently from the CKEditor 5 bundle.

**Comment by Reinmar** [comment]
It worked so far because we imported that function directly from its file, hence we didn't import `index.js` hence we didn't import `EmitterMixin` (imported by `index.js`) hence we didn't trigger the error.

**Comment by Reinmar** [comment]
toArray is a one line, let's inline it and remove this dep completely.
