### ISSUE TITLE
Toggle Italic in blockquote changes selected amount of text

### ISSUE THREAD

**Issue by vokiel** [ckeditor/ckeditor5#932]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

1.0.0-beta.1

## 📋 Steps to reproduce

1. Open balloon or document demo https://ckeditor.com/ckeditor-5-builds/#balloon
2. Select whole paragraph
3. Add blockquote
4. Click couple of time on italic icon

## ✅ Expected result

The whole selected paragraph should be still selected.

## ❎ Actual result

Selection changes from full paragraph to couple of first words.

## 📃 Other details that might be useful

![italic_blockquote_1](https://user-images.githubusercontent.com/422571/38137046-a470168a-3422-11e8-9a3a-5ace5945b15c.gif)

---

![italic_blockquote_2](https://user-images.githubusercontent.com/422571/38137047-a671bcf4-3422-11e8-8bdb-26ba32a60251.gif)

---

The same happens also on https://ckeditor5.github.io/

**Comment by Reinmar** [comment]
That's Chrome rendering issue, IIRC. @szymonkups, I think you reported that to Blink's team?

**Comment by szymonkups** [comment]
@Reinmar: It looks like I created some samples but you created [the issue](https://bugs.chromium.org/p/chromium/issues/detail?id=740085&q=reporter%3Ap.koszulinski%40cksource.com&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) :) 

It looks like it was marked with lowest priority :(

**Comment by Reinmar** [comment]
Ok, so this is a dup of https://github.com/ckeditor/ckeditor5-engine/issues/992.
