### ISSUE TITLE
Undo doesn't work properly for the `imageStyle` command.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9322]
## 📝 Provide detailed reproduction steps (if any)

1. Open a manual test of the `imageStyle` plugin on the `2052-inline-images` branch.
2. Set the first image style to `inlineImage` (first button in the toolbar).
3. Press `Ctrl+Z`.

### ✔️ Expected result

The whole action executed by the `imageStyle` command should be undone. The image should be the `image` element in model and have the `imageStyle` property equal to `alignCenter`.

### ❌ Actual result

Only the last executed action is getting undone, so the image has proper `alignCenter` style but remains an `imageInline` instead of the `image` in the model.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
🍰 Cake recipe:

1.  [this](https://github.com/ckeditor/ckeditor5/blob/i/2052-inline-images/packages/ckeditor5-image/src/imagestyle/imagestylecommand.js#L104-L107)
2.  should go [there](https://github.com/ckeditor/ckeditor5/blob/551b3694b9ad08f65ada996e09004211c556b17d/packages/ckeditor5-image/src/imagestyle/imagestylecommand.js#L111)

**Comment by oleq** [comment]
Closed in #9387.
