### ISSUE TITLE
Upcast inline image styles to classes using a configurable mapping

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9332]
Developers should be able to configure upcast style matchers that will allow loading images styles with `float: left/right` (and others) to any supported class, e.g. `.image-style-align-left`. 

This is essential for:
* compatibility with CKE4 that has images styled like this in the output data (#8663),
* sensible paste support (#8659).

**Comment by Mgsy** [comment]
It will be covered by #10310.
