### ISSUE TITLE
"Is inline" gets enabled even when caption is visible

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9333]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert an image
2.  Enable caption and type there
3.  "Is inline" is disabled
4.  Click somewhere in the editor
5.  Select the image again
6.  "Is inline" is enabled

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Probably DUP of #9213.
