### ISSUE TITLE
Upload Image using own UI + Backend

### ISSUE THREAD

**Issue by paulm17** [ckeditor/ckeditor5#934]
Using the latest version 5 and a custom build.

Hi guys, really impressed with version 5 so far.  But I have a question regarding image uploads.

Looking at the image-upload.md, it mentions:

    In a properly configured editor, there are several ways for the end user to insert images:

    - Selecting it from a media management tool in your application.

How best do I go about that?  Really, all I need is a callback which will execute a function of mine to display the modal.

I've looked through a lot of issues which mention SO and DUPs and getting a bit lost.  Thanks!

**Comment by Reinmar** [comment]
To upload a file you can use the [`imageUpload`](https://docs.ckeditor.com/ckeditor5/latest/api/module_image_imageupload_imageuploadcommand-ImageUploadCommand.html) command. See [Image feature's common APIs](https://docs.ckeditor.com/ckeditor5/latest/features/image.html#common-api).

Additionally, you need to enable image upload. Read more about this here: https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5

And if you want to show your own UI, you need to implement a toolbar button which shows it. You'll find information how to do that in https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html and https://docs.ckeditor.com/ckeditor5/latest/framework/guides/architecture/ui-library.html

**Comment by Reinmar** [comment]
PS. In case of more specific questions, please use StackOverflow.
