### ISSUE TITLE
Online builder is generating a broken editor

### ISSUE THREAD

**Issue by alexmachina** [ckeditor/ckeditor5#9348]
## 📝 Provide detailed reproduction steps (if any)

1. Head to https://ckeditor.com/ckeditor-5/online-builder/
2. Generate a default editor (just hiting "next" on the wizard)
3. Extract and Open sample/index.html

### ✔️ Expected result

A working editor, etc

### ❌ Actual result
Hiting enter doesn't work as expected.
The editor doesn't create a newline, rendering the editor unusable.

## 📃 Other details
The version from '@ckeditor/ckeditor5-build-classic": "^26.0.0",' works perfectly, but trying to generate a custom build doesn't.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dronpes** [comment]
Seeing this as well. The sample page from the build export currently throws these browser console warnings for me:
```
toolbarview-item-unavailable {name: "undo"}
toolbarview-item-unavailable {name: "redo"} 
```
(But I'm afraid I don't have time to dig deeper.)

**Comment by ma2ciek** [comment]
Thanks for letting us know about the problem! It should be fixed soon (~1h)

**Comment by dronpes** [comment]
Working on this end again. Thanks for the speedy fix! 👏
