### ISSUE TITLE
Inserting image into empty editor prevents adding other content

### ISSUE THREAD

**Issue by eahrold** [ckeditor/ckeditor5#935]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Current version on ckeditor5 docs page (most likely beta-1)

## 📋 Steps to reproduce

1. go to https://docs.ckeditor.com/ckeditor5/latest/features/image.html
1. Choose the first CKEditor instance
1. Remove all content from editor
1. Add an image
1. Try to add text content to the editor

## ✅ Expected result
Either pressing arrow keys, or clicking off image, will deselect image and allow adding content before / after.

## ❎ Actual result
Image consumes entire width of editor, and will not release focus. If the image is the only element in the editor, cannot click off to add text before/after

![ezgif-4-7f08868362](https://user-images.githubusercontent.com/3740088/38316015-5b136caa-37ef-11e8-9601-4a93686889f9.gif)

**Comment by Reinmar** [comment]
That's a DUP of https://github.com/ckeditor/ckeditor5/issues/407.
