### ISSUE TITLE
Creating custom builds section doesn't indicated how to generate content styles . 

### ISSUE THREAD

**Issue by karocksjoelee** [ckeditor/ckeditor5#9354]
## 📝 Provide a description of requested docs changes

As titled, I am using Angular for both the editor and content display ( Different projects ) 
I cannot find a document that builds content styles out of the Custom build. ( I used online build tool ) 
Nor on the content style section: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html

**Comment by pomek** [comment]
@karocksjoelee, if the content stylesheet would be added into the zip archive created by Online Builder, would it resolve your use case?

**Comment by karocksjoelee** [comment]
> @karocksjoelee, if the content stylesheet would be added into the zip archive created by Online Builder, would it resolve your use case?

Definitely ，that would be awesome to have 😊

**Comment by pomek** [comment]
@karocksjoelee, I'd like to ask about your use-case. Why do you need the content style file? As you pointed out, we already have the content style definitions in our documentation. Are you missing anything in the CSS or copying and saving the code is not comfortable enough?

**Comment by karocksjoelee** [comment]
@pomek Some extra plugins style is not included in the document, for example, the split image and media insertion. 

My use-case : 
I have 2 Angular Project, 
- One for a writer to write their blog ( using CKEditor ) and then store it in the database. 
- Another is the display of pure blog contents ( Retrieve HTML string from the database ) , this project doesn't need editor .

**Comment by Reinmar** [comment]
> @pomek Some extra plugins style is not included in the document, for example, the split image and media insertion.

They are included:

![](https://user-images.githubusercontent.com/156149/112953975-3ea60680-913e-11eb-868e-25f468201fce.png)

Please read this guide [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html) because it covers the thing you mention.
