### ISSUE TITLE
Two-step caret movement activates on an inline element inside a link

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#937]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Open the article sample.
1. Set the following data: `editor.setData( '<p><a href="test">te<strong>s</strong>t</a></p>' )`.
1. Put the caret at the beginning of the link.
1. Keep pressing <kbd>Arrow right</kbd> until you reach the end of the link.

## ✅ Expected result
Two-step caret movement doesn't activate on inline elements inside the link.

## ❎ Actual result
Two-step caret movement activates on inline elements inside the link.

## 📃 Other details that might be useful
OS: All platforms
Browser: All browsers

**Comment by oleq** [comment]
A piece of https://github.com/ckeditor/ckeditor5-engine/issues/1301.

**Comment by oleq** [comment]
This issue is no longer reproducible.

**Comment by oleq** [comment]
You're right. My bad.
