### ISSUE TITLE
[Chrome/Safari] Link balloon doesn't activate after focusing an editor for the first time

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#938]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the article sample (don't focus the editor).
1. Open the console and set following data: `editor.setData( '<p><a href="test">te<strong>s</strong>t</a></p>' )`
1. Put the caret inside the link.

## ✅ Expected result
The link balloon shows up.

## ❎ Actual result
The link balloon doesn't show up.

## 📃 Other details that might be useful

It occurs every time when a link has some inline styling. It could be reproduced with simple `<a href="test">test</a>`, but it would be much harder.

It could be also reproduced in docs, just go to `Examples -> Inline editor` and put the caret in a link.

OS: All platforms
Browser: Chrome, Safari

**Comment by Reinmar** [comment]
I can't reproduce it on https://docs.ckeditor.com/ckeditor5/1.0.0-alpha.2/examples/builds/inline-editor.html. So it's a regression since beta.1.

**Comment by FilipTokarski** [comment]
Doesn't happen anymore, can be closed.
