### ISSUE TITLE
EasyImage should not depend on Image (after introducing ImageBlock and ImageInline)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9399]
## 📝 Provide detailed reproduction steps (if any)

When you use `EasyImage` and load either `ImageBlock` or `ImageInline` (but not `Image`) there is a soft requirement error in the console because `Image` is missing.

The code of the `EasyImage` plugin does not use anything from `@ckeditor/ckeditor5-image` so this is a virtual requirement. Most likely we made `Image` the requirement of `EasyImage` to improve DX so developers don't have to include both if they want to use our service. The intention was good but it backfired when the API has changed.

The solution is getting rid of the requirement (breaking change) and mentioning in the migration guide that `EasyImage` must be used together with `Image`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Closed in #9494
