### ISSUE TITLE
Unable to build docs on Windows

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#941]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest `master` in all packages (includes this repository).

## 📋 Steps to reproduce

0. Clone the repository.
1. `mgit update`
2. `npm i`
3. `lerna bootstrap`
4. `npm run docs -- --production`

## ✅ Expected result

Docs will be built successfully.

## ❎ Actual result

![image](https://user-images.githubusercontent.com/2270764/38411636-cd69ed3a-3987-11e8-8325-5b48a23c3c01.png)

![image](https://user-images.githubusercontent.com/2270764/38411907-6d9805b2-3988-11e8-80a5-a21b09410601.png)

Inside the `1.0.0-beta.1/` directory I found snippets built by Webpack. I cannot run it but it looks ok.

## 📃 Other details that might be useful

OS: Windows 10
CLI: Git Bash

**Comment by oleq** [comment]
@pomek Can you still reproduce it?

**Comment by pomek** [comment]
On Windows, I am using Linux Bash Shell and every command worked fine (because it works as Unix system). However, I guess on pure Windows this issue can be still a thing. But I don't know whether we should care about it.

**Comment by pomek** [comment]
This issue is no longer valid. We fixed the builder on Windows environments in the past. Unfortunately, I cannot recall an exact moment when.
