### ISSUE TITLE
Implement a generator for "Features output" documentation page

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#9414]
Extracted from #6642.

This generator should scan the metadata and try to print them out in a human-readable form in the docs.

We should not forget about 3rd paty plugins currently covered in our docs.

As for the integration with Umberto - see how error codes (also generated automatically) are embedded.

To be decided:

*   A la content styles (once every release) - more performant
*   or a la error pages (dynamically on every build) - slower

**Comment by psmyrek** [comment]
I will start this task in a simple way. The feature output generator will be a script a'la content styles. The "visualization" of the plugin metadata will re-use the collapsible list, just like it is done for error codes or in the API. Below is an excerpt from the sample output that could be generated:

<img src="https://user-images.githubusercontent.com/56868128/115713467-53a93a80-a376-11eb-8dfc-ee07cfbc9091.png" width="700px">

I'm not sure if the HTML output should be also presented here, as it may take up a lot of space 🙄 

Another question is where this output should be stored.

**Comment by ma2ciek** [comment]
TBH this task can be implemented in various ways. Maybe we should discuss it a bit or ask more people to tell their feelings about this topic so we can choose the best approach.

**Comment by ma2ciek** [comment]
cc @niegowski @pomek - maybe you can help with this topic.

**Comment by ma2ciek** [comment]
Closed by #9629.
