### ISSUE TITLE
The "x" icon in the tour balloon should have the correct cursor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9419]
## 📝 Provide a description of the improvement

![](https://user-images.githubusercontent.com/156149/113489130-a5bb1680-94c2-11eb-9a4c-30d46b9055db.png)

It shows the default cursor, but it should be the pointer.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by godai78** [comment]
Thanks for finding an unaligned tooltip. I'll correct it on `stable`.
