### ISSUE TITLE
Font family lost when paste from office

### ISSUE THREAD

**Issue by arminyahya** [ckeditor/ckeditor5#9421]
## 📝 Provide detailed reproduction steps (if any)
Hi 
I'm using a custom ckeditor5 build:
```js
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment.js';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat.js';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote.js';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor.js';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor.js';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily.js';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize.js';
import Heading from '@ckeditor/ckeditor5-heading/src/heading.js';
import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic.js';
import Link from '@ckeditor/ckeditor5-link/src/link.js';
import List from '@ckeditor/ckeditor5-list/src/list.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation.js';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
  
class Editor extends ClassicEditor {}
 
// Plugins to include in the build.
Editor.builtinPlugins = [
	Alignment,
	Autoformat,
	BlockQuote,
	Bold,
	Essentials,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	Heading,
	Indent,
	Italic,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	TextTransformation
];

export default Editor;
```
All features work, but when i paste from [sample word document](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html) font family is lost (text-align works).

I wanted to ask how this [demo ](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html) is working correctly

### ✔️ Expected result

font-family of word document should work on editor.
### ❌ Actual result
font-family is not coming from the word document.

## 📃 Other details

* Browser: latest version of chrome and mozila firefox
* My OS: windows 10
* First affected CKEditor version: 21
* Installed CKEditor plugins:
Alignment,
	Autoformat,
	BlockQuote,
	Bold,
	Essentials,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	Heading,
	Indent,
	Italic,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	TextTransformation
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by sshadmehr** [comment]
+1

**Comment by stavackoli** [comment]
we also have same issue in out CMS

**Comment by bemaxima** [comment]
+1

**Comment by FilipTokarski** [comment]
Hi, did you read [docs on configuring font family plugin](https://ckeditor.com/docs/ckeditor5/latest/features/font.html#accepting-all-font-names)?

**Comment by arminyahya** [comment]
Hi @FilipTokarski 

font-family is working correctly after adding  **supportAllValues**:
```js
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        fontFamily: {
            options: [
                // ...
            ],
            supportAllValues: true
        },
    } )
```

also, [docs ](https://ckeditor.com/docs/ckeditor5/latest/features/font.html)explain how to configure font size.

Thank you.
