### ISSUE TITLE
Disabling enter is no longer possible after upgrade to v27

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#9422]
After upgrading CKEditor from v25 to v27 I'm having an issue that it's no longer possible to disable enter (i.e. user shouldn't be able to insert new line and has to type everything in a single line).

In older versions (v25 and older) I disabled Enter by removing the corresponding plugins:

```javascript
const editorConfig = {
    removePlugins: [
        'Enter',
        'ShiftEnter'
    ]
}
```

In v27 this no longer works, I get this error:

> Uncaught (in promise) CKEditorError: plugincollection-required {"plugin":"Enter","requiredBy":"WidgetTypeAround"}

I can follow the dependency chain and keep removing plugins until I get to a working configuration with:

```javascript
const editorConfig = {
    removePlugins: [
        'Enter',
        'ShiftEnter',
        'WidgetTypeAround',
        'Widget',
        'DragDrop',
        'Clipboard',
        'ListEditing',
        'ListStyleEditing',
        'ListStyle',
        'HorizontalLine',
        'xy',
        ''
     ]
};
```

But this then removes too much other functionality which I actually need.

**Comment by FilipTokarski** [comment]
Hi, this happens because `Enter` is a dependency of other plugins, in this case [`WidgetTypeAround`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-widget/src/widgettypearound/widgettypearound.js#L70). There's however an easy workaround - you can use this code:
```js
editor.editing.view.document.on( 'enter', ( event, data ) => {
    data.preventDefault();
    event.stop();
    return;
}, { priority: 'high' } );
```
This will listen on `enter` event and prevent it from firing.

**Comment by zadam** [comment]
@FilipTokarski many thanks, that does the trick!
