### ISSUE TITLE
input <div style="text-align: justify;"><p style="text-align: center;">JavaScript</p></div>

### ISSUE THREAD

**Issue by Joeycz** [ckeditor/ckeditor5#9425]
As title said, I setData
`<div style="text-align: justify;"><p style="text-align: center;">JavaScript</p></div>`
but getData
`<p style="text-align: justify;">JavaScript</p>`

but I expect 
`<p style="text-align: center;">JavaScript</p>`

How can I do it?

![image](https://user-images.githubusercontent.com/7298176/113702275-e3f74680-970b-11eb-8861-9cde7f0405b2.png)

![image](https://user-images.githubusercontent.com/7298176/113702318-f1143580-970b-11eb-81aa-3b50907f9bfb.png)

**Comment by Reinmar** [comment]
This will most likely be addressed by #9249.

**Comment by jacekbogdanski** [comment]
As @Reinmar already wrote this issue will be addressed by #9249. Since it's basically the same bug as https://github.com/ckeditor/ckeditor5/issues/8921 I'm closing it as duplicate.
