### ISSUE TITLE
Can't get CKEditor (with Mention plugin) to work with React

### ISSUE THREAD

**Issue by k2xl** [ckeditor/ckeditor5#9427]
## 📝 Provide detailed reproduction steps (if any)

1. Followed instructions here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html
I see my app, 
![image](https://user-images.githubusercontent.com/965260/113777718-7cd09680-96f9-11eb-986b-e32bac3da1bb.png)

So far so good

2. I try to include Mention, read through this: https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#demo
So I ran what the page says, which is `npm install --save @ckeditor/ckeditor5-mention`

Then I add `import Mention from '@ckeditor/ckeditor5-mention/src/mention';`

And then I get `ckeditor-duplicated-modules` issue. Okay, no problem. I click on the link in the error and it tells me to try a custom build. So I visit https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html and try to follow instructions there.

3. I export a custom build on the website custom build tool with Mention plugin selected. It exports the Zip file.

This is where the documentation breaks down for me. I'm super confused at this point what I'm supposed to do with the zip file. In it, I see the ckeditor.js in the build directory, so I assumed that I just need to `import X from 'ckeditor.js'` in my code. Yet, I start getting `define` errors show up.

I've read this section too: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder

And tried to follow the instructions, but after the `yarn add file:./ckeditor5`, what is the proper way to import?
```
import React, { Component } from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from 'ckeditor5-custom-build/build/ckeditor';
import Mention from 'ckeditor5-custom-build/build/ckeditor';
const editorConfiguration = {
    toolbar: [ 'bold', 'italic' ],
    plugins: [Mention]
};
class App extends Component {
    render() {
        return (
            <div className="App">
                <h2>Using CKEditor 5 build in React</h2>
                <CKEditor
                    config={editorConfiguration}
                    editor={ ClassicEditor }
                    data="<p>Hello from CKEditor 5!</p>"
                    onReady={ editor => {
                        // You can store the "editor" and use when it is needed.
                        console.log( 'Editor is ready to use!', editor );
                    } }
                    onChange={ ( event, editor ) => {
                        const data = editor.getData();
                        console.log( { event, editor, data } );
                    } }
                    onBlur={ ( event, editor ) => {
                        console.log( 'Blur.', editor );
                    } }
                    onFocus={ ( event, editor ) => {
                        console.log( 'Focus.', editor );
                    } }
                />
            </div>
        );
    }
}

export default App;
```
But I see this: 
![image](https://user-images.githubusercontent.com/965260/113782517-5104df00-9700-11eb-827c-2cda84777d52.png)

The text is not editable. And I get errors around toolbar not loading.

**Comment by FilipTokarski** [comment]
Hi, it looks like you are importing two editor builds here:

> import ClassicEditor from 'ckeditor5-custom-build/build/ckeditor';
> import Mention from 'ckeditor5-custom-build/build/ckeditor';
  
As it comes to:

> The text is not editable. And I get errors around toolbar not loading.


This time you are probably using document editor? In this case, the [toolbar needs to be added manually](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-document-editor-build).
    
Generally, the easiest option to extend the editor build in React, with all the plugins you need, is to [build it from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source). So I would advise to follow this tutorial.

**Comment by jechazelle** [comment]
@k2xl did you found a solution ?
