### ISSUE TITLE
Highlight icon reacts to hover in read only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#943]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open a sample with the highlight plugin.
1. Turn on the read only mode.
1. Hover the highlight icon.

## ✅ Expected result
The icon doesn't highlight on hover.

## ❎ Actual result
The icon is highlighted.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/38414732-a0bca018-398f-11e8-9120-b27eaa2b00a7.gif)

**Comment by dkonopka** [comment]
We should disable `:focus`, `:active` action for buttons in read-only mode.

![screen shot 2018-04-09 at 12 45 30](https://user-images.githubusercontent.com/10219857/38493898-1e47d82a-3bf4-11e8-887f-2d4cfc5b627e.png)
