### ISSUE TITLE
when zip download and add ckeditor file to my project ,found syntax error in ckeditor.js

### ISSUE THREAD

**Issue by rivery811** [ckeditor/ckeditor5#9431]
Multiple markers at this line
	- primary expression expected
	- Semi-colon expected
	- '}' expected
	- ',' expected
	- ']' expected
	- ')' expected
	- Invalid trailing comma in arguments list
	- Invalid escape sequence
	- primary expression expected
	- Character '×' (U+00D7) is not a valid identifier 
	 start char

================> error message

use cdn is ok but i need base64 pulgin 
whats problems?

here my plugin list
Editor.builtinPlugins = [
	Autoformat,
	Base64UploadAdapter,
	BlockQuote,
	Bold,
	CloudServices,
	Essentials,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	Italic,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TextTransformation
];

**Comment by FilipTokarski** [comment]
Hi, I just checked downloading editors from [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) and from [download page](https://ckeditor.com/ckeditor-5/download/) and both work fine. Please make sure that this is not some error on your side. If this problem still exists, we'll need more precise step-by-step description to reproduce it.  
  
Apart from that, you can always [build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html) or [install additional plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) that you need.
