### ISSUE TITLE
About Title plugin

### ISSUE THREAD

**Issue by iveryo** [ckeditor/ckeditor5#9439]
If there are characters that need to be escaped in the title content
Such as "A & B"
The getTitle() method of Title plugin
The result obtained is "A & amp; B"
My expectation is "A & B"
Is this a bug?

Currently my solution is to pass
title._getTitleElement().getChild(0).getChild(0).data
To get A & B

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. This is not a bug. As you mentioned some characters need to be escaped and there's currently no handy method that would return this content unescaped. So the solution here might be to create a custom method that processes the returned html the way you want it.
