### ISSUE TITLE
Cursor placed on wrong side of table cell in Apple Safari

### ISSUE THREAD

**Issue by marcaspers** [ckeditor/ckeditor5#9442]
## 📝 Provide detailed reproduction steps (if any)

1. Open Safari on MacOS (problem only seems to occur with Safari, not other browsers)
2. Create a table in the editor
2. Type text in a table cell
3. Focus on another cell
4. Put your mouse pointer on the right of the cell with content, but leave margin between the text and your cursor while staying in the cell, and click

### ✔️ Expected result

Cursor appears at the end of the table content

### ❌ Actual result

Cursor appears at the beginning of the table content

## 📃 Other details

* Browser: Safari
* OS: macOS Big Sur
* First affected CKEditor version: At least since 21
* Installed CKEditor plugins: Many, but this one is also reproducable on your own [demo](https://ckeditor.com/ckeditor-5/demo/), as long as you use Safari.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
Duplicate of https://github.com/ckeditor/ckeditor5/issues/8637?

**Comment by marcaspers** [comment]
Yes, looks like the same issue!
