### ISSUE TITLE
[package - table]Option for default initial style (Solution provided)

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#9449]
## 📝 Provide a description of the new feature

In order to make table more responsive for initial structure it will be useful to control the default style of the table.
In this moment (version 27.0.0) there is no option to control any of the table properties from the config.
I think it is useful to define what is my default.

**_What is the expected behavior of the proposed feature?_**
I expect it to be at config like this:
```
 table: {
            contentToolbar: [ 'tableColumn', 'tableRow', 'mergeTableCells' ],
            defaultStyle: { alignment: 'left' }
        }
```
`table.defaultStyle` can get any object that represent the possible table style.

* Side note- the fix can be done here 
https://github.com/ckeditor/ckeditor5/blob/55248f45a8ce74fdd0276b03c2cd8e339dd1f4a7/packages/ckeditor5-table/src/tableutils.js#L100
```
 const defaultStyle = this.editor.config.get('table.defaultStyle');
 const table = writer.createElement( 'table',  defaultStyle );
 ```

* If the solution can also be for default cell style, it will be great 😄!
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by kuku711** [comment]
Suggested PR for this issue https://github.com/ckeditor/ckeditor5/pull/9393
If it is this, consider this issue as closed.

**Comment by Mgsy** [comment]
> Suggested PR for this issue [#9393](https://github.com/ckeditor/ckeditor5/pull/9393)  
> If it is this, consider this issue as closed.

The linked PR covers handling default styles for tables and table cells. It should be merged soon and will be available in the next release. I'm closing it as a duplicate.
