### ISSUE TITLE
Code blocks remove HTML TAG

### ISSUE THREAD

**Issue by Sabe67** [ckeditor/ckeditor5#9456]
Hello,

I have a problem with Code blocks. This feature remove my html tag on the editor :

Code displaying on the page :
![image](https://user-images.githubusercontent.com/13998579/114508540-c60e7200-9c34-11eb-8af4-4627f8da031b.png)

In the editor :
![image](https://user-images.githubusercontent.com/13998579/114508618-de7e8c80-9c34-11eb-95b7-6c25fc99a7cc.png)

So when I want to update my content, I always need to write again the HTML. It's a little boring ..
Ty for your help.

**Comment by FilipTokarski** [comment]
Hi, I'm not sure what you mean here because for me it returns correct markup. Could you provide precise steps to reproduce this?

**Comment by Sabe67** [comment]
I have contents stored in a database for some pages. 
For exemple I have something like this :
<h2>Popup</h2><pre><code class="language-html">&lt;a href=""&gt;test&lt;/a&gt;</code></pre>

And when I show this content in the editor in a Code block, it's just showing **test** and not all the code.

**Comment by FilipTokarski** [comment]
I did:
```js
editor.setData('<h2>Popup</h2><pre><code class="language-html">&lt;a href=""&gt;test&lt;/a&gt;</code></pre>')
```
On [this demo](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html) ( scroll down to second demo editor ) and it works fine.  
  
I would then suggest double checking your application code. Maybe you have some custom plugins that change editor's behavior?

**Comment by Sabe67** [comment]
Ok I will check, ty for your help.

**Comment by Sabe67** [comment]
Ok my error was to display my content in my editor without **htmlspecialchars** in php.
Now it's work :)

Ty
