### ISSUE TITLE
The two-step caret movement requires 3 steps on the left side of a link

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#946]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master (f31e6e1)

## 📋 Steps to reproduce

1. I've encountered it in build classic sample.
2. Navigate through text by cursor towards link (from it's left side so using right arrow).
3. Place a caret before last character of a word preceding a link.
4. press right arrow twice (you are "before" link)
5. press right arrow once (you are still "before" link)
6. press right arrow again (you are inside a link)

## ✅ Expected result
you should only need one right arrow press to enter link

## ❎ Actual result

you need press right arrow twice

## 📃 Other details that might be useful

![screencast 2018-04-06 13_30_52](https://user-images.githubusercontent.com/247363/38419049-2558f97a-399f-11e8-9fb5-0d2ba730ad9a.gif)

**Comment by jodator** [comment]
That's weird but the first try (freshly instantiated editor) does not show this error. Only the second and next movements will show this.

**Comment by scofalik** [comment]
We know about problems with 2-step-caret-movement. It will be refactored, maybe rewritten. There are more bugs.

**Comment by oleq** [comment]
I'm almost sure this is a DUP of https://github.com/ckeditor/ckeditor5-engine/issues/1301. But let's wait for the research first.

**Comment by Reinmar** [comment]
We've got so many tickets for two-step caret movement that it'd be good to create an epic for them.
