### ISSUE TITLE
[Firefox] New line is inserted when clicking just below image

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#947]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Checked on Classic build `1.0.0-alpha.2`

## 📋 Steps to reproduce

1. Go to https://docs.ckeditor.com/ckeditor5/1.0.0-alpha.2/examples/builds/classic-editor.html.
2. Focus image.
3. Click just right below image (see attached gif).

## ✅ Expected result

Caret is placed on the beginning of the header below.

## ❎ Actual result

Caret is placed in the new line which is inserted.

![image1](https://user-images.githubusercontent.com/1061942/38424087-3a81a19c-39b0-11e8-820e-35080f0f0024.gif)

## 📃 Other details that might be useful

Firefox 59.0.2 (64-bit). I was not able to reproduce it on Chrome.

**Comment by Mgsy** [comment]
It's a DUP of https://github.com/ckeditor/ckeditor5-image/issues/20.
