### ISSUE TITLE
Word can't open a file with nested tables exported from CKEditor 5

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9474]
## 📝 Provide detailed reproduction steps (if any)

1. Create a document with nested tables in the editor.
2. Export it to the Word format.
3. Try to open it in Word.

### ✔️ Expected result

It should be opened

### ❌ Actual result

![image](https://user-images.githubusercontent.com/14334820/114738458-4671c780-9d48-11eb-8906-3bb76632305b.png)

## 📃 Other details

* OS: MacOS Catalina

@ckeditor/ckeditor-5-triage 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
We decided on the standup that we'll adjust the export to docx command in a way that it will check model for nested tables. If it happens then it should show an alert that nested tables are currently not supported + link to issue + what shoudl be done (nested tbales should be removed).

**Comment by mlewand** [comment]
We got a word that it has already been fixed in our docx converter service. Once it's been deployed all we need to do is to remove workaround introduced as a part of #9501

**Comment by AnnaTomanek** [comment]
Support for nested tables was released in the OpenXML converter, so we may now remove the workaround.
