### ISSUE TITLE
[Firefox] Cannot delete content when selection includes side image

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#948]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Tested on `1.0.0-alpha.2`

## 📋 Steps to reproduce

1. Go to https://docs.ckeditor.com/ckeditor5/1.0.0-alpha.2/examples/builds/classic-editor.html.
1. Remove first and second headers (so image is surrounded by two paragraphs).
1. Remove image caption.
1. Switch image to **Side Image**.
1. Select both paragraphs.
1. Try to delete selected content.

![ff4](https://user-images.githubusercontent.com/1061942/38425051-1fc35910-39b3-11e8-90ad-b8dffab5096b.gif)

## ✅ Expected result

Selected content is removed.

## ❎ Actual result

Selected content is not removed. `TypeError: t is null` error is thrown.
![image](https://user-images.githubusercontent.com/1061942/38424901-c27fd3aa-39b2-11e8-9a64-5229a5964cf4.png)

## 📃 Other details that might be useful

Reproducible only on Firefox (`59.0.2 (64-bit)`).

In Chrome the same selection looks like (the image is also selected):
![image](https://user-images.githubusercontent.com/1061942/38425115-47fc0328-39b3-11e8-86e4-ca6748420e7a.png)

**Comment by Mgsy** [comment]
This bug has been fixed (https://github.com/ckeditor/ckeditor5/issues/678) and doesn't occur on the latest master.

**Comment by f1ames** [comment]
Thanks @Mgsy. I got confused as on latest master only first part of the text is removed (but I see there is already issue for that ckeditor/ckeditor5-engine#366).
