### ISSUE TITLE
Table-related commands are enabled in the restricted editing mode.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9480]
## 📝 Provide detailed reproduction steps (if any)

1. Open the restricted editing manual test and insert a table.
2. Switch to the restricted-editing mode.
3. Select the table and click on the insert column/row or merge cells button.

### ✔️ Expected result

The buttons should be disabled if the selected rage doesn't contain the editable areas only.

### ❌ Actual result

Buttons are enabled and fully functional - it is possible to insert the columns/rows or merge table cells.

![image](https://user-images.githubusercontent.com/14334820/114846112-a619b280-9ddc-11eb-9c97-89ece448edff.png)

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
These few table-related commands are enabled because they're a part of the restricted-editing manual test:

![](https://user-images.githubusercontent.com/11699569/118660743-c16a4a00-b7ee-11eb-8ff0-deaaed774d2f.png)
