### ISSUE TITLE
How can I control the maximum length of content?

### ISSUE THREAD

**Issue by jongjunpark** [ckeditor/ckeditor5#9489]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

I want to control of the content's maximum length.
As you can see below,First I tried change CSS.
```
.ck-editor__editable_inline { 
    max-height:400px; 
}
```

However It can be just controlled editor's length
I want to limit the input if the length is more than specified length.

for example, 
if .ck-content's offsetHeight > 1000, I want to be not able to typing text in editor.
How can I setting this feature?

**Comment by wimleers** [comment]
Drupal issue: https://www.drupal.org/project/drupal/issues/3273755

**Comment by Reinmar** [comment]
I'd approach it as in #2573. It's not feasible to just block (cut off) excess text without degrading the UX. The Twitter-like behavior is the best option, IMO.
