### ISSUE TITLE
Temporary disable exporting DOCX (Word documents) for content with nested tables

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9501]
## Provide a description of the task

Since generated DOCX documents that contains nested tables will now crash (and we don't want this to happen) we will temporarily disable exporting if the exported document has nested tables.

This is a temporary workaround to #9474.

> We decided on the standup that we'll adjust the export to docx command in a way that it will check model for nested tables. If it happens then it should show an alert that nested tables are currently not supported + link to an issue + what should be done (nested tables should be removed).

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: Latest `master`

**Comment by AnnaTomanek** [comment]
Closed in https://github.com/cksource/ckeditor5-internal/commit/f487fadcbe77116d74635cb55d6e319be75525fd
