### ISSUE TITLE
Builds' demos and configurations have inconsistent `ImageResize` plugin configurations.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9507]
## 📝 Provide detailed reproduction steps (if any)

1. The `inline` editor has the `ImageResize` plugin in the demo, but not in the default Online Builder configuration or the build itself. Besides that, the image styles configuration in the demo is the `document` type and `semantic` in the build.
2. The `document` editor has the `ImageResize` plugin in the demo and the Online Builder, but not in the build itself.

IMO it makes it difficult for the user to pick his desirable build. He looks at the demo and expects to get the same output from the build/Online Builder.

Besides, we have made some decisions about the builds' configurations, why change them in the demos? The above cases concern the display of the images in various styles (https://github.com/ckeditor/ckeditor5/issues/7715) - the fact that the style has changed is invisible because the image is so big that it always takes the whole width of the editor. 
**It can be easily fixed by setting the original size of the example images to something less than the usual width of the editable area.**

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Closed in #9618.
