### ISSUE TITLE
What are the limitations of the demo version?

### ISSUE THREAD

**Issue by it19862** [ckeditor/ckeditor5#951]
## Is this a bug report or feature request? (choose one)
Other
What are the limitations of the demo version?
I can not understand "ckeditor" paid or free?

## 💻 Version of CKEditor
CKEditor 5 Builds 
or
CKEditor 5 Framework

**Comment by Reinmar** [comment]
Both paid and Open Source editor versions are functionally identical. What differs is the way you are obliged to present the code and the fact that with a commercial license you receive at least one year of technical support and upgrades.

CKEditor is distributed under three copy-left Open Source license options: GPL, LGPL and MPL. You can modify, integrate and use it in your commercial websites and products for free as long, as our source code and modifications remain open and accessible to others under the same Open Source license terms [https://opensource.org/].

If you agree with the Open Source restrictions, and you don’t require any support services from us, then you are welcome to use CKEditor in your project as an Open Source software.

On the other hand, if you either disagree with the Open Source rules, or require our technical support for your project, then you would need to purchase a commercial license.

**Comment by Reinmar** [comment]
In case of further questions ragarding commercial offer you can contact us at https://ckeditor.com/contact/
