### ISSUE TITLE
Quick start guide miss `body` tag and `lang` attribute

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#953]
HTML snippet in this sample: https://github.com/ckeditor/ckeditor5/blob/6291d28077f0a4cac742fb756fe0361474ae9884/docs/framework/guides/quick-start.md

Do not have `<body>` tag. Even if it is correct HTML, it does not make it simple, especially since it is a quick start sample.

It also miss `lang` attribute, what causes validation errors.

**Comment by Reinmar** [comment]
Fixed in https://github.com/ckeditor/ckeditor5/pull/1138/commits/75c97420d8ef30386c80b398e07a2308c994242b.
