### ISSUE TITLE
Create the Updating CKEditor 5 guide

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#9530]
Proposal by @maxbarnas:

*   Create a short guide on updating CKEditor 5 (similar to the [Install guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installation.html)).
*   Crosslink with the Migration guides where necessary.

**Comment by AnnaTomanek** [comment]
By the way, we have a similar thing (entire section as it also includes things similar to our migration guides) in CKE4 docs: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_upgrade.html

**Comment by AnnaTomanek** [comment]
Looks like it's covered in https://github.com/cksource/ckeditor5-internal/issues/1265 and https://github.com/cksource/ckeditor5-internal/issues/1266. Should be delivered within the next few weeks.

**Comment by godai78** [comment]
Kazał pan, musiał sam ;)
