### ISSUE TITLE
Rename the image style "full" to "block".

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9545]
## Provide a description of the task

The name "full" doesn't reflect, how the image will be actually displayed. If the image's original size is less than the editor's width, it is displayed in the middle of the editing area in its original size. Since we are making so many breaking changes implementing the inline images, it seems to be a good moment to fix this name.

The image style name should be changed in the builds, manual and automatic tests, internal and CF projects.
This change should be mentioned in #9339.

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by magda-chrzescian** [comment]
There will be some missing translations due to these changes.

**Comment by oleq** [comment]
Closed in #9896.
