### ISSUE TITLE
Migration guides should be sorted by latest version first

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9550]
## 📝 Provide a description of requested docs changes

[Currently the sidebar in our builds docs](https://ckeditor.com/docs/ckeditor5/27.1.0/builds/index.html) shows:

![](https://user-images.githubusercontent.com/5353898/115735629-ebb11f00-a38a-11eb-8eb6-ccff0fe5d07b.png)

Typically you care only about x last releases and versions from year ago bother proportionally smaller audience.

Also having the latest version first is the most natural to me (and I believe to most users). E.g. that's the way [GH orders our releases](https://github.com/ckeditor/ckeditor5/releases) same thing goes for our changelog, etc.

**Comment by godai78** [comment]
On it today.
