### ISSUE TITLE
We should not list all the migration guides in the sidebar

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9551]
## 📝 Provide a description of requested docs changes

It sounds reasonable to limit it, e.g. 3 latest release + "older" link where older (or all?) migration docs would be listed. Otherwise we'll have a very crowded sidebar in 6 months, dominated by migration guides.

Also it simply looks weird even now:

![](https://user-images.githubusercontent.com/5353898/115736505-a17c6d80-a38b-11eb-97ce-b38a7808d3c5.png)

**Comment by godai78** [comment]
This issue will be addressed here: https://github.com/cksource/ckeditor5-internal/issues/1069

I believe we can hence close this one.

**Comment by godai78** [comment]
Considering the issue had been addressed during the great docs revamp, I consider my own proposal for closure as still valid.

And then I proceed to close the issue as no longer relevant.
