### ISSUE TITLE
Unexpected token 'export' in custom build

### ISSUE THREAD

**Issue by alexander-schranz** [ckeditor/ckeditor5#9554]
## 📝 Provide detailed reproduction steps (if any)

Have build with custom JS:

1. https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source
2. Run tests with jest (https://github.com/sulu/sulu/blob/c0e3b0b4d64d82111618a48de374e10265f3fb89/package.json#L124)

It will fail with:

https://github.com/sulu/sulu/pull/5950/checks?check_run_id=2413276236

### ✔️ Expected result

No errors:

### ❌ Actual result

```
    /Users/alex/Documents/Sulu-CMS/sulu-develop.localhost/vendor/sulu/sulu/node_modules/ckeditor5/src/core.js:10
    export * from '@ckeditor/ckeditor5-core';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@ckeditor/ckeditor5-alignment/src/alignment.js:10:1)
```

The problems seem's that now all plugins require a new package called `ckeditor` like here: https://github.com/ckeditor/ckeditor5/blob/41bf7a3aeb23c6f56a2ffa4ac53859d4411e6188/packages/ckeditor5-alignment/package.json#L14

But this package is in the documentation not set to be loaded over `babel` I think the documentation need to be added that `@ckeditor|ckeditor` are loaded over babel.

The currently provided regex in the docs is `/ckeditor5-[^\/\\]+[\/\\].+\.js$/` I think this is maybe wrong as it also should include /ckeditor5/ packages.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: 23 did work was updated to 27
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
@alexander-schranz thanks for the report. Your idea about tweaking the regexp might work. Can you try to change it in your local filesystem and see if it fixes the issue? And let us know the results.

**Comment by alexander-schranz** [comment]
@mlewand we did change it in our [webpack build](https://github.com/sulu/sulu/pull/5950/files) and it did work for us then.

**Comment by alexander-schranz** [comment]
@miewand I did look at the published packages and it seems like something like `@ckeditor/alignment` is published correctly with a build version which does not `contain` the `import` and `export` keywords. Only the [`ckeditor5`](https://www.npmjs.com/package/ckeditor5) package seems to be the only one not containing a build version? I also find it a little bit strange that this is the only package not in the `@ckeditor` namespace.

**Comment by pomek** [comment]
So if I understood correctly, we should update all RegExps to match the main (`ckeditor5`) package.

**Comment by alexander-schranz** [comment]
@pomek yes I'm not sure why it is accessed by jest but the package with the name [`ckeditor5`](https://www.npmjs.com/package/ckeditor5)  is in some case loaded in our tests and as this is not transpiled using babel it did fail. Before our regex was something like transpile our code and `@ckeditor` packages but as `ckeditor5` does not match we needed to update the transpiling to transpile `@ckeditor` and the `ckeditor5` packages.

**Comment by pomek** [comment]
The `ckeditor5` package is required for preparing DLLs. You can read more about it in the documentation – https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/dll-builds.html.

As I understand what needs to be changed, I'll update our docs. Thanks for reporting the issue.

**Comment by alexander-schranz** [comment]
Aslong as the `ckeditor5` package is published without transpiling it seems like the docs should be updated that you transpile `ckeditor5` package yourself by adding it to the regex. Thx for the dll link I hope we can soon migrate to something like dll in our case.

**Comment by pomek** [comment]
The updated guide will be published soon.

**Comment by alexander-schranz** [comment]
Thank you!

**Comment by pomek** [comment]
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target

![image](https://user-images.githubusercontent.com/2270764/117293717-09de4b00-ae72-11eb-883b-87b39fb1fbbf.png)

Once again, thank you for reporting the error.

**Comment by alexander-schranz** [comment]
Want to mention that this is maybe also the case in not ES5 targets as the `export` and `import` keywords also work in normal node target not, but as we currently use the ES5 target build and not the dlls I did not test that case and it did only appear in our `jest` tests not in the build.
