### ISSUE TITLE
Image toolbar overlapping drop cursor

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9566]
Image toolbar being visible all the time can become a bit problematic with inline images, especially when you for example want to drag an image into the line above the current one. Screencast contains dragging a table as a comparison:

https://user-images.githubusercontent.com/34380544/115722931-c0750280-a37f-11eb-8c1a-20deaf43aa4f.mp4

**Comment by niegowski** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/9604.
