### ISSUE TITLE
It's possible to create a code block with an image inside

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9567]
## Steps to reproduce:
1. Add some text with inline image inside
2. Select everything
3. Click `Insert code block`

## Result:
A code block with image inside is created

## Expected:
Code block cannot contain images

## Screencast:

https://user-images.githubusercontent.com/34380544/115726501-113a2a80-a383-11eb-9e85-c56ec4ca5354.mp4

**Comment by niegowski** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/9594.
