### ISSUE TITLE
Linking image results in resize value NaN%

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9568]
## Steps to reproduce:
1. Upload an image as inline
2. Add a link on the image
3. Try to resize it

## Result:
You cannot resize it, size value is `NaN%`, you also cannot drag it anywhere in Firefox. Sometimes it's hard to reproduce it, but with those steps I got it every time.

## Screencast:

https://user-images.githubusercontent.com/34380544/115735574-e0f68a00-a38a-11eb-9272-0695056f6956.mp4

**Comment by oleq** [comment]
Probably the same case https://github.com/ckeditor/ckeditor5/pull/9236#issuecomment-825441500.

**Comment by oleq** [comment]
Closed in #9598.
