### ISSUE TITLE
ClassicEditor is not Defined

### ISSUE THREAD

**Issue by ahmad6242** [ckeditor/ckeditor5#9574]
## 📝 Provide detailed reproduction steps (if any)

1. … I created a custom build 
2. … Downloaded it. 
3. … IN the sample folder when i tried to run index i get this
4. and when i tried to use it in my project i get this: ClassicEditor is not Defined
![image](https://user-images.githubusercontent.com/12858657/116206469-e3246400-a74f-11eb-8abf-044390b7e532.png)

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: … Chrome and firefox
* OS: … Win 10
* First affected CKEditor version: …
* Installed CKEditor plugins: … 
* 
![image](https://user-images.githubusercontent.com/12858657/116206611-0c44f480-a750-11eb-9cff-a806e7afe21c.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, this error is most probably caused by MathType plugin trying to do some requests. Please try opening the sample using some server, for example [this one](https://www.npmjs.com/package/http-server).
