### ISSUE TITLE
Make websocket requests for collaboration-enabled editors parallel/async

### ISSUE THREAD

**Issue by JarvisH** [ckeditor/ckeditor5#9576]
## 📝 Provide a description of the improvement

_How the feature works now and what you'd like to change_?

When adding groups of collaborative editors like this:

```js
// Create context instance
const contextWatchDog = new ContextWatchdog(Context)
await contextWatchDog.create(contextConfig)

let configs = [{}]

await contextWatchDog.add(configs)
```

... each editor instance makes a websocket query to the CKeditor cloud. These requests are fired synchronously, causing excessive loading times until all editors are ready. A screenshot of the requests for 5 editors on one page looks like this:

![image (2)](https://user-images.githubusercontent.com/1301804/116212838-8ae86480-a745-11eb-9ed1-6f1bdfae2b90.png)

It would be much better if all requests could be made simultanously.

## 📃 Other details

* CKeditor is built from source
* Browser: All
* OS: all
* CKEditor version: 27.1.0
* Installed CKEditor plugins: RealTimeCollaborativeEditing, ContextWatchdog, ContextBase, BalloonEditor, CloudServices, Essentials, Heading, Link, Paragraph

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by JarvisH** [comment]
Additional note: 5 editors with collaboration feature enabled, need about 2.5 seconds to load... without collaboration enabled, the all load in about 200ms

**Comment by Mgsy** [comment]
Hi! Thank you for the report. Please, note that real-time collaboration is our commercial feature and this issue tracker is dedicated to the open-source part of the project. I can see that you've already reached our support channel, so let's continue the conversation there.
