### ISSUE TITLE
Refresh the "What's new guide" for the stable release

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#958]
We should refresh the "What's new" guide for the stable release and put some real effort into it as this will be the main focus point for people who are totally new to CKEditor 5, and most of all, are still using CKEditor 4.

Some things to think about:
* Feature completeness (make sure we cover the latest features, too)
* Update screenshots and movies (new theme, new UIs)
* Restructure content to make it really shine - this will be the main entry point for some prospects!

//cc @wojtekidd @wwalc

**Comment by oleq** [comment]
FYI: added the "two-step caret movement around links" section today.

**Comment by godai78** [comment]
The "What's new" section has been removed altogether as obsolete.
