### ISSUE TITLE
Cannot clear image caption by deleting its contents

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9592]
## 📝 Provide detailed reproduction steps

1. Toggle **on** the image caption and type something in, e.g. `foo`.
1. Toggle **off and on** the caption.
1. **Delete** the caption.
1. Toggle **off and on** the caption. 

### ✔️ Expected result

An empty caption is shown.

### ❌ Actual result

The previous caption is shown. In the example above it will be `foo`.

**Comment by maxbarnas** [comment]
It should be fixed by removing this condition (as was done in the table caption): https://github.com/ckeditor/ckeditor5/pull/9503/files#diff-41de187645189be92dd09c145ad9a232fb75fe6832c7449ef76f50e759e175a6R160

**Comment by pomek** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/issues/9592.
