### ISSUE TITLE
Implement the deleting feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#96]
To be implemented in ckeditor5-delete.

**Comment by Reinmar** [comment]
The feature will expose `delete` and `forwardDelete` commands (just like the native ones). They will have one param "step" (looking for a better name) which can be set to "character" (default), "word" or "line". The param will only work if the selection is collapsed (just like it does natively).

**Comment by fredck** [comment]
> param "step" (looking for a better name)

I would go with "range", but I hope it'll not get confused with other range things we have in the API. So maybe "dimension" or "scope".

**Comment by Reinmar** [comment]
"range" sounds good

**Comment by Reinmar** [comment]
I don't know why I said "range", because I agree that it will be confusing :D I'll go with "unit" as in the old MS API (https://msdn.microsoft.com/en-us/library/ms536421(v=vs.85).aspx).

**Comment by Reinmar** [comment]
OK, there's a repo and https://github.com/ckeditor/ckeditor5-delete/issues/1 there, so we can close this one.
