### ISSUE TITLE
How can I configure keystrokes on React.js CKEditor component ?

### ISSUE THREAD

**Issue by Clipsyblitz** [ckeditor/ckeditor5#9608]
I would like to create a basic editor in React.js with only undo and redo button in order to limit the possible action in it.

After building my custom editor, I made some tests and I found that the shortcuts are always active. In fact, when I press Ctrl+B, bold transformation is toggle and I don't want this feature.

Of course, it also works with other basic shortcuts like Ctrl+U and Ctrl+I.

So, how could I configure keystrokes on React in order to disable these shortcuts ?

I have this config object :

```js
const basicEditorConfiguration = {
	toolbar: ["undo", "redo"]
}
```

And I tried to use the **keystrokes** key but it doesn't work actually : 

```js
const basicEditorConfiguration = {
	toolbar: ["undo", "redo"],
        keystrokes: ....
}
```

Thank you !

**Comment by FilipTokarski** [comment]
Hi, if this suits your use case, you can block execution of a command on a given keystroke by configuring it like this:
```js
editor.keystrokes.set( 'Ctrl+B', ( evt, cancel )=> {
    evt.preventDefault();
    evt.stopPropagation();
    cancel();
}, { priority: 'high' } );
```
In your React integration, you can use this [inside `onReady` component property](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#component-properties).
