### ISSUE TITLE
[ Bug report ] Ckeditor removes line-breaks on copy-paste from notepad

### ISSUE THREAD

**Issue by gwebkiev** [ckeditor/ckeditor5#961]
I use classic default ckeditor 5 build.

The problem is if I copy from notepad text like:
```
1
2
3
```
In editor I give result:
`1 2 3`

If I copy next text:
```
1

2

3
```
In editor I give:
```
1
2
3
```

Why ckeditor removing one line-break per line ?

**Comment by Reinmar** [comment]
cc @Mgsy Do you remember the ticket from Mozilla Notes guys about this?

**Comment by Mgsy** [comment]
>cc @Mgsy Do you remember the ticket from Mozilla Notes guys about this?

Yes, they had the same problem - https://github.com/mozilla/notes/issues/534.

@gwebkiev, we decided to open a ticket for a discussion, where you can find some explanation of this behaviour. Feel free to join the discussion and describe your use case, it would be very helpful for us - https://github.com/ckeditor/ckeditor5/issues/766.

**Comment by gwebkiev** [comment]
Thanks guys. I will research 766 issue
