### ISSUE TITLE
Testing environment: Automated tests with third party plugins?

### ISSUE THREAD

**Issue by tony** [ckeditor/ckeditor5#9612]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

Are there a template / example / docs for testing third party libraries that include a Testing workflows for Local environment and CI (travis/gh actions)?

Related links:
- Testing environment: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/testing-environment.html
  At the moment, this only seems to include instructions for testing official plugins, not third party ones in separate repositories

Examples of third party plugins:
- ckeditor5-math: https://github.com/isaul32/ckeditor5-math
   - Related issue, "How to test?": https://github.com/isaul32/ckeditor5-math/issues/36
- wiris formula editor: https://github.com/wiris/html-integrations/tree/stable/packages/mathtype-ckeditor5/src

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
The script that we use for executing automated tests assumes it works in the mono-repository. However, we have an open PR that changes it – https://github.com/ckeditor/ckeditor5-dev/pull/594.

I'll try to review it soon, and if everything works, merge and release. However, it will also require an update in our documentation, so I don't want to promise anything.

**Comment by tony** [comment]
Thank you for letting me know about https://github.com/ckeditor/ckeditor5-dev/pull/594!  No hurries as I'm aware the next release is around the corner. Look forward to seeing it in!

**Comment by pomek** [comment]
Closing in favor of https://github.com/ckeditor/ckeditor5/issues/9613#issuecomment-933384380.
