### ISSUE TITLE
Custom / third party plugins: Development workflow

### ISSUE THREAD

**Issue by tony** [ckeditor/ckeditor5#9613]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

I made this separately from #9611 since the reality of plugins outside the monorepo may make this a separate effort.

This would be instructions / utilities for a development loop, e.g. `yarn` + `yarn start` + launch browser w/ file watching and livereload, for third party / external plugins for ckeditor 5:
- [wiris formula editor](https://github.com/wiris/html-integrations/tree/stable/packages/mathtype-ckeditor5/src)
- [ckeditor5-math](https://github.com/isaul32/ckeditor5-math)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
I guess I answered your question in the comment – https://github.com/ckeditor/ckeditor5/issues/9611. However, we could create a guide in the documentation about how we create a new package. It would help integrators as well.

**Comment by tony** [comment]
@pomek That would be valuable for open source / third party packages!

**Comment by pomek** [comment]
I'd like to present the tool called [`ckeditor5-create-package`](https://www.npmjs.com/package/ckeditor5-package-generator), which creates a working package with a ready-to-use development environment.

A package created by this tool contains a few scripts that simplify writing new plugins for CKEditor 5, e.g.:

* Testing environments – execute tests, and verify the code coverage,
* Development environments – create an HTTP server with the live-reload mechanism, which speeds up the development,
* Tools for static analysis of the code.

Also, the new package contains an example plugin called `MyPlugin` that shows how to create a new icon in the editor's toolbar and inserts text directly into the editor.

On the package page, on npm, you can find a detailed guide on using the tool with available modifiers.

However, if you find any issue concerning the tool or suggest some improvement, please [report it in the dedicated GitHub repository](https://github.com/ckeditor/ckeditor5-package-generator/issues/new/choose).

I'll close the issue. If my response is not satisfactory, please, create a new issue in the `ckeditor5-package-generator` repository, as it will be a much better place to discuss such topics.

**Comment by tony** [comment]
@pomek Excited about this. Thank you!
