### ISSUE TITLE
ckeditor5 version 27.1 doesnt get the ngmodel with angular

### ISSUE THREAD

**Issue by ldoreillepro** [ckeditor/ckeditor5#9620]
From the version 27.1, with angular, we can use the @input data correctly but not the @input ngModel which cannot download the content into the ckeditor.

So we start with an empty editor.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/55096130/117007048-7548e100-ace9-11eb-9081-8e82235d367f.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/55096130/117007141-91e51900-ace9-11eb-9e4b-76af47b8a71f.png">

This is a basic code to reproduce the problem

https://github.com/ldoreillepro/ldoreillepro-test-angular-ckeditor5-27-1

I only added a basic ckeditor in thefolder src/app

**Comment by pulkitpatel95** [comment]
same issue. can we create a previous version build using online builder ?

**Comment by ldoreillepro** [comment]
@pulkitpatel95  you must compile it using the version 26 by yourself

**Comment by ldoreillepro** [comment]
@ma2ciek 

in the following file of the package ckeditor5-angular

https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/ckeditor.component.ts

It seems that the the method "writeValue" doesn't make it job correctly (line 240 to 245)

We can correct that by adding a line in the method "setUpEditorEvents"

If we add the following line:
editor.setData(this.data);
after the line 371, it works

So From that:
        const viewDocument = editor.editing.view.document;

We move to that:

        const viewDocument = editor.editing.view.document;
        editor.setData(this.data);


It's clearly a problem to know when the CKEditor is initialized .... 

I hope it will help your developers

**Comment by ldoreillepro** [comment]
Much better 
We must initialize the value of the editor when we create it 

It must be done in the method "attachToWatchdog" (line 285)

so the line:
  editor.setData(this.data);
must be placed line 301 before we return the object editor

**Comment by ma2ciek** [comment]
Hi @ldoreillepro, 

Thanks for reporting the issue and the PR, I confirm the issue.

> so the line:  
> editor.setData(this.data);  
> must be placed line 301 before we return the object editor

Unfortunately, this is not a good fix as we need to have real-time editing in mind and support it as well.

But, perhaps, we can extend the configuration with the initial data. I'll check it.

**Comment by pulkitpatel95** [comment]
Hi @ma2ciek , 

Any update on above issue or when we can expect a fix for this ?

**Comment by ma2ciek** [comment]
The fix landed on the master branch. We plan to release it at the beginning of the next week.
