### ISSUE TITLE
Paste from Excel

### ISSUE THREAD

**Issue by hichemamb** [ckeditor/ckeditor5#9621]
## 📝 Provide detailed reproduction steps (if any)

1. Copy tables from an Excel with style (font/color/background color/ font size)
2. Paste it into the editor

### ✔️ Expected result

Get the same result as it is display on the Excel with the good colors, size, border...

### ❌ Actual result

Actually paste from Excel work but we loose sometimes the style.

## 📃 Other details

* Browser: Google Chrome
* OS: Windows 10
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Currently there's no full support for pasting from Excel. There is a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/2513), so please feel free to add there anything you find important and don't forget to add 👍  to increase its popularity.  
I'll close this one as a duplicate.
