### ISSUE TITLE
Replicate the Paste From Google Docs ckeditor 

### ISSUE THREAD

**Issue by dacastro4** [ckeditor/ckeditor5#9633]
I tried to replicate the same ckeditor 5 instance that is in [this page](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html) but when I copy the same plugins it just don't get the same results when I copy and paste the content from a Google Docs

Here is my code

```
ClassicEditor.builtinPlugins = [
    //Plugins Listed Above
]

ClassicEditor.defaultConfig = {
    language: 'en',
    table: {
        contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableCellProperties',
            'tableProperties'
        ]
    },
    fontFamily: {
        options: [
            'default',
            'Lato, Helvetica, Arial, sans-serif',
            'omnes, sans-serif'
        ],
        supportAllValues: true
    },
    heading: {
        options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
            { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
            { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
            { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
            { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' }
        ]
    },
    fontColor: {
        colors: [
            {
                color: '#FFC700',
                label: 'Primary'
            },
            {
                color: '#B33CC8',
                label: 'Secondary'
            },
            {
                color: '#262626',
                label: 'Black'
            },
        ]
    },
    alignment: {
        options: [ 'left', 'center', 'right' ]
    },
    height: 300,
    toolbar: {
        items: ["heading", "|", "fontSize", "fontFamily", "fontColor", "fontBackgroundColor", "|", "bold", "italic", "underline", "strikethrough", "-", "alignment", "|", "numberedList", "bulletedList", "|", "outdent", "indent", "|", "link", "uploadImage", "insertTable", "horizontalLine", "|", "undo", "redo"],
        shouldNotGroupWhenFull: !0,
    },
    image: {
        styles: ["full", "alignLeft", "alignRight"],
        toolbar: ["imageStyle:alignLeft", "imageStyle:full", "imageStyle:alignRight", "|", "imageTextAlternative"]
    },
    fontSize: {
        options: [10, 12, 14, "default", 18, 20, 22],
        supportAllValues: !0
    },
}

window.onload = () => {
    ClassicEditor
        .create(document.querySelector('#intro'))
        .then(editor => {
            console.log(editor);
        })
        .catch(error => {
            console.error(error);
        });

    ClassicEditor
        .create(document.querySelector('#content'))
        .then(editor => {
            console.log(editor);
        })
        .catch(error => {
            console.error(error);
        });
}

```

###### Google Docs File
![Google Docs File](https://user-images.githubusercontent.com/7808930/117219339-11024c00-add3-11eb-83f2-6826ecdedec8.png)
###### CKeditor 5 Demo
![CKeditor 5 Demo](https://user-images.githubusercontent.com/7808930/117219336-0f388880-add3-11eb-94ec-dba828191d58.png)
###### My Instance of CKeditor
![My Instance of CKeditor](https://user-images.githubusercontent.com/7808930/117219342-119ae280-add3-11eb-93ba-4973f4f9932c.png)

* Browser: Google Chrome 90.0.4430.93 (Official Build) (x86_64)
* OS: MacOS 10.14.6 (18G2022)
* CKEditor version: 5 (NPM 27.1.0)
* Installed CKEditor plugins:
  * @ckeditor/ckeditor5-editor-classic
@ckeditor/ckeditor5-alignment
@ckeditor/ckeditor5-autoformat
@ckeditor/ckeditor5-link
@ckeditor/ckeditor5-block-quote
@ckeditor/ckeditor5-basic-styles
@ckeditor/ckeditor5-essentials
@ckeditor/ckeditor5-font
@ckeditor/ckeditor5-font
@ckeditor/ckeditor5-font
@ckeditor/ckeditor5-font
@ckeditor/ckeditor5-heading
@ckeditor/ckeditor5-horizontal-line
@ckeditor/ckeditor5-image
@ckeditor/ckeditor5-image
@ckeditor/ckeditor5-image
@ckeditor/ckeditor5-image
@ckeditor/ckeditor5-image
@ckeditor/ckeditor5-image
@ckeditor/ckeditor5-indent
@ckeditor/ckeditor5-indent
@ckeditor/ckeditor5-basic-styles
@ckeditor/ckeditor5-link
@ckeditor/ckeditor5-list
@ckeditor/ckeditor5-list
@ckeditor/ckeditor5-media-embed
@ckeditor/ckeditor5-paragraph
@ckeditor/ckeditor5-remove-format
@ckeditor/ckeditor5-basic-styles
@ckeditor/ckeditor5-basic-styles
@ckeditor/ckeditor5-basic-styles
@ckeditor/ckeditor5-table
@ckeditor/ckeditor5-table
@ckeditor/ckeditor5-table
@ckeditor/ckeditor5-table
@ckeditor/ckeditor5-typing
@ckeditor/ckeditor5-basic-styles
@ckeditor/ckeditor5-enter
@ckeditor/ckeditor5-paste-from-office

**Comment by FilipTokarski** [comment]
Hi, in this case the styles that format editor's content visually are taken from the page itself - you can see that for example headings and paragraphs outside the editor area look the same. So to imitate those in your app, you would basically need to add those few styles ( like editor width, paddings, margins, borders, etc. ) that are on the docs web page.

**Comment by dacastro4** [comment]
@FilipTokarski but what about the spaces between paragraphs and titles?

**Comment by FilipTokarski** [comment]
Here they're also controlled by the page styles:

https://user-images.githubusercontent.com/34380544/117308113-7f054c80-ae81-11eb-8692-13eb8f811190.mp4

So if you want to style your editor you can just use `p` selector, but if that collides with other styles that you want to use on your page, you can always narrow down the selector with `.ck-editor__editable` or `.ck-content`.

**Comment by dacastro4** [comment]
Thank you very much @FilipTokarski
