### ISSUE TITLE
Add support for Watchdog configuration in integrations

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9638]
## 📝 Provide a description of the new feature

Currently, it's not possible to configure Watchdog (e.g. number of restarts) while using React/Angular integration. It would be nice to allow users to pass the Watchdog configuration.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
This should be easy to implement via another property in the `<ckeditor>` component.

**Comment by jaspreetScrut** [comment]
Any updates for react application??

**Comment by pomek** [comment]
I am glad to announce we added the requested feature to both integrations:

* React: https://github.com/ckeditor/ckeditor5-react/releases/tag/v5.1.0
* Angular: https://github.com/ckeditor/ckeditor5-angular/issues/351

As the React integration is already published, the Angular release will happen this week.
