### ISSUE TITLE
Parse error in iPad console

### ISSUE THREAD

**Issue by jokohews** [ckeditor/ckeditor5#964]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor
https://cdn.ckeditor.com/ckeditor5/1.0.0-beta.2/balloon/ckeditor.js

None

## 📋 Steps to reproduce

1. Add CDN link to page
2. Load page on iPad (using 1st gen ipad)

**Comment by Reinmar** [comment]
What's your iOS version? Safari had a problem until recently with a bug in their JS parser.
