### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules was thrown when I use highlight

### ISSUE THREAD

**Issue by HugeMountain** [ckeditor/ckeditor5#9643]
## 📝 configuration

`

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import AutoFormat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Subscript from '@ckeditor/ckeditor5-basic-styles/src/subscript';
import Superscript from '@ckeditor/ckeditor5-basic-styles/src/superscript';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize';
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
import TodoList from '@ckeditor/ckeditor5-list/src/todolist';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
export default class Editor extends ClassicEditor {
}

// Plugins to include in the build.
Editor.builtinPlugins = [
	AutoFormat,
	Strikethrough,
	Subscript,
	Superscript,
	Underline,
	Code,
	FontBackgroundColor,
	FontColor,
	FontSize,
	Highlight,
	TodoList,
	PasteFromOffice,
	TableProperties,
	TableCellProperties,
	ImageUpload,
	ImageResize,
	IndentBlock
];

// Editor configuration.
Editor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic',
			'strikethrough',
			'subscript',
			'superscript',
			'underline',
			'code',
			'alignment',
			'link',
			'removeFormat',
			'|',
			'fontBackgroundColor',
			'fontColor',
			'fontFamily',
			'fontSize',
			'highlight',
			'|',
			'bulletedList',
			'numberedList',
			'todoList',
			'outdent',
			'indent',
			'|',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'codeBlock',
			'horizontalLine',
			'pageBreak',
			'specialCharacters',
			'restrictedEditingException',
			'undo',
			'redo'
		]
	},
	image: {
		toolbar: [
			'imageStyle:full',
			'imageStyle:side',
			'|',
			'imageTextAlternative'
		]
	},
	table: {
		contentToolbar: [ 'tableColumn', 'tableRow', 'mergeTableCells', 'tableCellProperties' ]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'zh-cn'
};

`

### ✔️ Expected result

To use highlight correctly

### ❌ Actual result

CKEditorError: ckeditor-duplicated-modules was thrown

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, please make sure that Highlight plugin has the same version as other CKEditor packages ( current one is `27.1.0` ). [Duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) happens ( among few other reasons ) mostly when plugin versions do not match.
  
However if that's not the case, we'll need precise steps to reproduce this and more information about your environment.

**Comment by hareluya86** [comment]
Hi @FilipTokarski, since @HugeMountain hasn't replied, let me share my configuration as I'm facing the same issue as well, but with the inline-editor, angular and basic-styles module. 

My dependencies:
`
"@ckeditor/ckeditor5-angular": "^2.0.1",
"@ckeditor/ckeditor5-basic-styles": "^27.1.0",
"@ckeditor/ckeditor5-editor-inline": "^27.1.0",
`
In ckeditor.js:
`
import InlineEditorBase from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';

export default class InlineEditor extends InlineEditorBase {}

InlineEditor.builtinPlugins = [
    Bold
]
`

And got the same error:
> Uncaught CKEditorError: ckeditor-duplicated-modules
> Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

**Comment by FilipTokarski** [comment]
Hi, please note that currently in Angular integration, there is no way to build the editor from source like in Vue or React. You need to first create a custom build and then use it inside your Angular app - [it's described in the documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build).
