### ISSUE TITLE
Json format data

### ISSUE THREAD

**Issue by sochan-tenten** [ckeditor/ckeditor5#9644]
## 📝 Provide a description of the new feature

I'm searching for Json format data to store and output the HTML data safely from user to protect XSS threat, but could not find such a method.
For example, another library "[quill.js](https://quilljs.com/docs/api/#content)" has getContent() and setContent() method, which converts HTML data to specific json-data to reorganize user input HTML data  easily and wonder if ckeditor has such method or not.... I also wonder how the developer removing XSS risk from using ckeditor, using a certain library for sanitizing on server-side? 
I could not find related document, so its helpful for me to get some advise. 
Thank you!
 
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by hxgdzyuyi** [comment]
https://github.com/ckeditor/ckeditor5/issues/620

**Comment by Reinmar** [comment]
Indeed a DUP of #620.
