### ISSUE TITLE
ckeditor-5-markdown-output

### ISSUE THREAD

**Issue by Mohamed-HassanNX** [ckeditor/ckeditor5#9645]
Hello , 

I would like to have a detail about bug with a problem encountered with the markdown plugin which returns markdown to us.
For the media video plugin, we have no markdown returned for it.
I wonder if it comes from my side or this is not yet present

Thank you so much .

* Browser: chrome
* OS: Mac
* First affected CKEditor version: 5
* Installed CKEditor plugins: Markdown , media

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report, however it's more of a feature, not a bug. Please keep in mind that markdown syntax is very simple in itself, hence the [markdown processor plugin does not output every content](https://ckeditor.com/docs/ckeditor5/24.0.0/features/markdown.html#known-issues) that you create inside editor. You can read more in [this comment](https://github.com/ckeditor/ckeditor5/issues/1281#issuecomment-483604395).
