### ISSUE TITLE
Implement the view source feature for the classic editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9647]
## 📝 Provide a description of the new feature

Extracted from #592.

This feature request is about introducing a feature for the classic editor that will allow switching to the source editing mode.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by adamerose** [comment]
Excited to see this! Source editing is important for my use case (and many others judging by [this thread](https://github.com/ckeditor/ckeditor5/issues/592#issuecomment-470424532))

Can you give any comment on whether this will work with the Markdown plugin to toggle between WYSIWYG and raw text markdown?

**Comment by psmyrek** [comment]
Hi @adamerose, the goal is to be able to edit the source of the document, no matter if HTML or Markdown.

**Comment by harleenarora** [comment]
@psmyrek How to get the this plugin all files.
