### ISSUE TITLE
HTML comments: Core

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9660]
## Provide a description of the task

Introduce a new `HtmlComment` plugin.

**Comment by psmyrek** [comment]
Feature branch is ready for development: `ck/8822-html-comment` (created from GHS feature branch: `ci/656-html-support`). Changes: https://github.com/ckeditor/ckeditor5/compare/ci/656-html-support...ck/8822-html-comment

I'm closing this issue as the initial version of the `HtmlComment` plugin has been created in the `ckeditor5-html-support` package.
