### ISSUE TITLE
HTML comments: Model

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9661]
## Provide a description of the task

Handle creating HTML comments in the model.

*   API to create and remove a comment.
*   It'd create a marker and set the root attribute.
*   Note: not a command as it will be used by upcast converters. Let's expose these methods on the plugin.

**Comment by ma2ciek** [comment]
I created the following API:

```
createHtmlComment( position, content, id=uid() ) => Comment ID (it's used later as a part of the marker name) 
removeHtmlComment( id );
```

But I think that this API misses a few things.

With this API the user won't be able to remove a comment in a specific position. Perhaps we could store all IDs of created HTML comments and be able to provide users a way to get all IDs for HTML comments that were created at a given position?

**Comment by ma2ciek** [comment]
I also encountered one with creating a marker before or after the root element. I'll create an issue for it.

**Comment by ma2ciek** [comment]
Perhaps we could also implement one or two methods like:

*   `getHtmlCommentsAtPosition()` -> `Array.<{ content: String, id: String, position: String }>`
*   `getAllHtmlComments()` -> `Array.<{ content: String, id: String, position: String }>`
*   `setContent( id: String, newContent: String )`

But TBH I'm not sure what are the use cases we should be aware of.

**Comment by psmyrek** [comment]
I like this proposal.
I would slightly change it to:

- `createHtmlComment( position: Position, content: String )` → returns full marker name, i.e. `"$comment:1234567890"`.
I don't see any case if anyone would like to set own unique comment id, as this is our internal way of storing the comment's content.
- `removeHtmlComment( markerName: String | range: Range )`
- `getHtmlCommentsInRange( range )` → returns `Iterable.<Marker>` to be consistent with similar `MarkerCollection#getMarkers...()` methods.

I think that `getHtmlCommentsAtPosition()` is not needed, because provided range in `getHtmlCommentsInRange()` can be collapsed.

Also `getAllHtmlComments()` is IMHO not needed, because we can provide a range to `getHtmlCommentsInRange()` that is set on the whole `$root`.

**Comment by ma2ciek** [comment]
> returns full marker name, i.e. `"$comment:1234567890"`.

TBH I wanted to avoid using any marker-oriented things in the API to not depend on the markers in the implementation

> I don't see any case if anyone would like to set own unique comment id, as this is our internal way of storing the comment's content.

That's true.

`getHtmlComment( markerName: String )` - it certainly makes sense and I was also considering it.

> getHtmlCommentsInRange( range ) → returns Iterable.\<Marker> to be consistent with similar MarkerCollection#getMarkers...() methods.

We've had a hard time with iterables. If they don't improve performance I'd avoid using them as it doesn't provide any value. 

But yep, as I was talking on priv, the `getHtmlCommentsInRange` can solve various problems.

**Comment by ma2ciek** [comment]
I'd stick to 3-4 methods to not overcomplicate the API. 99% of the usages of this feature will be `setData()` & `getData()` and the API can always be extended in the future.

**Comment by psmyrek** [comment]
> > returns full marker name, i.e. `"$comment:1234567890"`.
> 
> TBH I wanted to avoid using any marker-oriented things in the API to not depend on the markers in the implementation

So let's start considering that `"$comment:1234567890"` is the full unique comment id.

**Comment by ma2ciek** [comment]
During f2f talks we agreed to implement only the `getHtmlCommentsInRange` method. It should take care of markers at the range borders.

**Comment by psmyrek** [comment]
Merged to `ck/8822-html-comment` in https://github.com/ckeditor/ckeditor5/commit/4b8ee83eccb9971d9b5aca0e26566c8d24254d38.

**Comment by ma2ciek** [comment]
We implemented the following methods in the initial API:

```
createHtmlComment( position, content ) => commentID (a string that is later used as a marker name) 
removeHtmlComment( commentID ) => Bolean
getHtmlCommentsInRange( range ) => Array<commentID>
getHtmlCommentData( commentID ) => { position, content }
```
