### ISSUE TITLE
HTML comments: Conversion upcast

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9662]
## Provide a description of the task

Handle HTML comments upcast (`<$comment>` with a custom property `$rawContent` to a marker).

**Comment by ma2ciek** [comment]
Currently blocked by #10128.

**Comment by psmyrek** [comment]
Merged to feature branch `ck/8822-html-comment` in https://github.com/ckeditor/ckeditor5/commit/3e8e8fb985a67e62ea5a409191fc8810f08e96f7.
