### ISSUE TITLE
[Edge] Editor crashes after correcting a word in a link

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#968]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Create new word with a typo, i.e. `teszt`.
1. Select it and add a link.
1. Right click on it and correct it to `test`.
1. Open the console.

## ✅ Expected result
No errors in the console.

## ❎ Actual result
There are errors in the console.

## 📃 Other details that might be useful
It's interesting because I can't reproduce it while the console is opened from the beginning.

**Errors**

```
SCRIPT5022: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds

SCRIPT5022: cannot-change-view-tree: Attempting to make changes to the view when it is in incorrect state: rendering or post fixers are in progress. This may cause some unexpected behaviour and inconsistency between the DOM and the view. Read more: https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree
```

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/38854879-2d11f03c-4222-11e8-9cde-8a8a63884820.gif)

OS: Windows 10
Browser: Edge 16

**Comment by FilipTokarski** [comment]
Tested once again, the bug is gone now, should be closed.
