### ISSUE TITLE
How to upgrade to new versions with collaboration enabled without getting version mismatch

### ISSUE THREAD

**Issue by coolbaluk** [ckeditor/ckeditor5#9690]
## 📝 Provide a description of the improvement

Hi all, I've been running into this issue every time there is a new version release. Bumping the version and deploying will crash any open collaboration sessions, because some users would be on the previous version and some users will be on the new one, so we get the infamous version mismatch error.

Is there an approach on how to bump the ckeditor version without this happening that we are not aware of ?

**Comment by Mgsy** [comment]
Hi! Indeed, there's no possibility to join the document that has been created with CKEditor 5 version different than the one used by the connecting user. The solution for this case will be [flushing existing documents](https://help.cke-cs-staging.com/api/v4/docs#tag/Collaboration/paths/~1collaborations~1{document_id}/delete) using our REST API. After that, users with the updated CKEditor 5 version will be able to join the document.

Also, please note that real-time collaboration is our premium feature and this repository is dedicated to an open-source part of the project, so it would be appreciated if in case of further problems you could contact us through [our support channel](http://support.ckeditor.com/), where the dedicated support team will assist you in solving your issues. Thanks!

**Comment by coolbaluk** [comment]
I see, will give that a shot.

Thanks, will close this issue :)
