### ISSUE TITLE
Add building the features html output page to the default docs building process.

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#9695]
Currently, to run this script it's needed to run `yarn docs:features-html-output` before running `yarn docs` 

A follow-up to #9685.

**Comment by ma2ciek** [comment]
There are at least two solutions to this problem:

1.  Change the umberto generator so it will generate the additional page for the HTML output - it would require adding some configuration to the `umberto.json` file where you could specify the output path.
2.  Ignore `docs/builds/guides/integration/features-html-output-overview.md` by Git and add the `docs:features-html-output` script to the default CKEditor 5 docs build process before running umberto.

The 2nd solution is much uglier but much faster :sweat\_smile: 

cc @pomek @AnnaTomanek.

**Comment by ma2ciek** [comment]
Note that this task runs for around a second. So it won't increase the built time much.

**Comment by pomek** [comment]
Covered in https://github.com/ckeditor/ckeditor5/pull/10236. I'll merge the PR after the release.

**Comment by pomek** [comment]
After merging the PR, let's review our guides about preparing the release. We don't need to call it manually anymore, so we can drop points mentioning the step.
