### ISSUE TITLE
Better separate plugins in the "Features' HTML output" guide

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9699]
## 📝 Provide a description of the improvement

![](https://user-images.githubusercontent.com/156149/118232163-7966c280-b490-11eb-843c-c53091746f6b.png)

I find it a bit hard to connect the output (right column) to specific feature names on the left. E.g. which rows apply to the "Image" feature.

One, simplest (but potentially ugly idea) would be to have stronger border after each plugin. We could also colorize odd and even plugins differently. Or review the format completely.

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by godai78** [comment]
It's done: https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/features-html-output-overview.html
