### ISSUE TITLE
Improve the styling in "Features' HTML output" left column

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9700]
## 📝 Provide a description of the improvement

![](https://user-images.githubusercontent.com/156149/118232479-ea0ddf00-b490-11eb-8b1d-01ef2fa9bc86.png)

There are two links for each plugin, but it wasn't clear even for me after a while which links where. Just to make it clear now – the first link leads to the docs, the second to the plugin API docs.

Let's rethink what we need there and how it could be presented.

## 📃 Other details

*   Browser: …
*   OS: …
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by godai78** [comment]
How about describing it with "documentation" and "API" respectively. It's very simple and yet efficient.

**Comment by Reinmar** [comment]
Worth checking. I'm a bit afraid regarding long plugin names - whether they'll fit. But we'd need to check that.

**Comment by godai78** [comment]
Might go for icons as well, if text descriptions are too long.

**Comment by magda-chrzescian** [comment]
> Might go for icons as well, if text descriptions are too long.

Sometimes I have a hard time trying to distinguish which links lead to the API docs. I would see some "API link" icon used across the entire documentation.

About the reported issue, IMO there is no point in repeating the plugin name in this table, there is also a missing plugin name displayed as a title.

![image](https://user-images.githubusercontent.com/14334820/125625816-ad5124c4-bc9d-4c10-9325-a37158a8e5c5.png)

We could preceded the first link with the icon from the table of contents and the second one with some new icon for the API links.
![image](https://user-images.githubusercontent.com/14334820/125624348-0a004e1f-1ac8-4712-8b18-52c27506f797.png)

**Comment by godai78** [comment]
CCX conclusions:  
  
\* redraw the output as per Magda's image  
\* add alt text to the links with feature's name for SEO

**Comment by godai78** [comment]
Current state of works:

![](https://user-images.githubusercontent.com/68123541/132677808-8aa36b6e-92a1-4f16-b6c8-1d4e1b207287.png)

**Comment by godai78** [comment]
LGTM. Merging today.

![](https://user-images.githubusercontent.com/68123541/133438139-3ba23ef2-77c1-4ff2-893b-3c31756e7862.png)

**Comment by godai78** [comment]
Merged: #10492
