### ISSUE TITLE
The "source file" in "Features' HTML output" should probably link to the stable branch

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9701]
## 📝 Provide a description of the improvement

We don't have these files on the stable branch yet, but I think that's where we should point people from documentation most of the time.

So, once we ship the next release, let's update these links.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
TBH I was also thinking about removing them at all as we can't link to 3rd-party package metadata and to our internal package metadata files.

**Comment by godai78** [comment]
Guys?

**Comment by godai78** [comment]
Merged in June.
