### ISSUE TITLE
Mockups for find & replace UI

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9719]
Based on the outcome of #9716 we should prepare mockups for the UI.

**Comment by magda-chrzescian** [comment]
### The initial scope that we decided to cover:

- Search input + search button
- Replace
    - Replace single occurrence
    - Replace all occurrences
- Match case option
- Match whole words only option
- _Match cyclic option (from CKE4)?_
- Find next
    - Usually executed with `Enter` or `F3`
        - if we talk about `Enter` it should be a little more picky (than f3) to where it triggers
    - Do we want to have a separate button for that action (">") or execute it with the main "find" button? → Let's have 2 mockup versions and decide.
- Find previous
    - Usually executed with the `Shift+Enter` or `Shift+F3`
    - Do we want to have a separate button for that or execute it with the keyboard only?
- Highlighting search results and the currently selected result
    - Browser screen/viewport should also be scrolled to the highlighted result
- Remembering the state (previous search conditions)
- Displaying the number of results and the currently highlighted result
- Fully keyboard-navigable UI
- Keyboard shortcut
    - Where to display the UI if there is no button in the toolbar?
    - Do we want to override the browser search shortcut?
        - Definitely should only happen if the editor is focused.
    - **This is the topic that requires broader discussion.**

**Comment by magda-chrzescian** [comment]
### The remaining questions:
* Do we have to implement a pop-up to introduce the feature in the balloon editor?
* How to prevent covering search results by the find&replace UI?
* How costly would it be to auto-trigger the search event on the input change instead of using a `search` button?
  * No `search` button at all - only `prev` and `next`.
  * It would be a nice solution for touchscreens.
  * The smaller the UI is, the less likely it is to cover the results.

**Comment by magda-chrzescian** [comment]
> Do we have to implement a pop-up to introduce the feature in the balloon editor?
Here is a simple demo of the drop-down UI in the balloon editor: https://framer.com/share/9oFxhKDEUbeEOCc0DDuB/GnPu_hqj2#ru7XfkqmQ

**Comment by wwalc** [comment]
As an end user, I'm not sure if I would like that I have to chase with my mouse the panel with the next/prev buttons to cycle through found items. I'd rather expect the content to scroll, while the dialog to stay at the exact position so that I did not have to move my mouse all the time and that I could quickly just click 10 times to see all 10 items that were found.
<img width="101" alt="Screen Shot 2021-05-28 at 10 39 22 AM" src="https://user-images.githubusercontent.com/545175/119956093-ffaafa80-bfa0-11eb-907b-2974816ba36a.png">

**Comment by magda-chrzescian** [comment]
> As an end user, I'm not sure if I would like that I have to chase with my mouse the panel with the next/prev buttons to cycle through found items. I'd rather expect the content to scroll, while the dialog to stay at the exact position so that I did not have to move my mouse all the time and that I could quickly just click 10 times to see all 10 items that were found.

You're definitely right, but I'm not sure about the implementation.
* Are we always able to keep the position of the drop-down? Vertically, in most cases, yes, but still, it's going to be problematic (sometimes impossible) for the results located close to the top and bottom edges of the editor.
* I'm not sure how to handle this horizontally, as
  * we have a limited amount of the drop-down positions (it is relative to the drop-down button, moved by 0/25/50/75/100% from its center) and
  * we don't want to end up with something like this, where the drop-down got completely visually detached from the toolbar to maintain its position:

![image](https://user-images.githubusercontent.com/14334820/119986047-b029f600-bfc3-11eb-9d9a-34d3e861b5db.png)

We should also remember, that we probably won't be able to provide seamless navigation between the results, as the toolbar and drop-down will always disappear for a while when scrolling the content (or it will move with the currently highlighted result).

A way to go would be to completely detach the drop-down from the toolbar, so we are getting back to a pop-up-like solution again.

On the positive note is the problem only occurs in the balloon and balloon-block editors.
We should also label the buttons with the available shortcuts, so it would be possible to navigate with `enter`/`shift+enter` on devices with the keyboard.

**Comment by magda-chrzescian** [comment]
If we decided to go with this approach, the behavior of the `ENTER` button will differ between the balloon and other kinds of the editor, as we will have to move the focus from the find&replace input to the editable. So the keyboard navigation will be even harder and possible to execute with the `F3` button only.

**Comment by magda-chrzescian** [comment]
Summing up some recent decisions:

We decided to go with the drop-down UI. Initially, it won't be super friendly in the balloon and and balloon-block editors, but it is going to be fully functional and ready for potential future improvements.

I came out with a solution to avoid covering the content with a opened drop-down - it should be possible to hide the drop-down and still have the search results highlighted. Demo available here: https://framer.com/share/Find-Replace-UI--7fziRKKvGp4ItrumCHv1/mVivoNmGq#DWAL0tik3.

As the drop-down can be hidden at any time, we also decided to go with a more spacious design for the UI, with buttons instead of the icons and some more space for the options labels, as they can be much more extensive in languages other than English.

**Comment by magda-chrzescian** [comment]
Below you can see a proposition of a more spacious drop-down UI:
![image](https://user-images.githubusercontent.com/14334820/120491410-80ab2d00-c3b9-11eb-8f62-6f30c4a60b23.png)

**Comment by magda-chrzescian** [comment]
What's left to be done:

* Designing highlighting search results (so it won't mess up with tracked changes)
* Designing an icon for the main toolbar button
* Describing keyboard interaction in various types of editors

**Comment by magda-chrzescian** [comment]
> Designing highlighting search results (so it won't mess up with tracked changes)

Here is an icon design. IMO it should cover both, find and replace purposes:
![image](https://user-images.githubusercontent.com/14334820/121002197-604dea80-c78c-11eb-98e1-e621dffd52f7.png)

**Comment by magda-chrzescian** [comment]
> Designing highlighting search results

Here is a demo of highlighting the search results (the animation is visible a second after clicking the `Run` button.
https://jsfiddle.net/uh6joz17

![image](https://user-images.githubusercontent.com/14334820/121019672-f17a8c80-c79f-11eb-90f5-94e45c16ae3e.png)

Let's try to implement the suggested colours and animation and then check again if it suits our needs.

**Comment by magda-chrzescian** [comment]
Some more detailed information about interacting with the UI: https://miro.com/app/board/o9J_lB72Fbs=/ (it contains outdated design, but I think that described mechanisms should still be pretty clear).

**Comment by mlewand** [comment]
Cool stuff, thanks @magda-chrzescian! One question, have you used any of existing buttons in [https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-853042066](https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-853042066) mockup (I mean blue and gray buttons)? I don't recall them in any existing CKE5 feature so we'll have to create new ones.

**Comment by magda-chrzescian** [comment]
> Cool stuff, thanks @magda-chrzescian! One question, have you used any of existing buttons in #9719 (comment) mockup (I mean blue and gray buttons)? I don't recall them in any existing CKE5 feature so we'll have to create new ones.

I didn't use any existing component, but maybe we could just style an existing icon button differently?

**Comment by mlewand** [comment]
Yes, I expect we'll reuse button view and only adjust the styling based on CSS class. I just wanted to check whether there's something that we can reuse before we start to write new code.

I'm sure that we'll have to create some other new components for:

*   checkbox
*   input with the counter inside

**Comment by mlewand** [comment]
Ok, great work @magda-chrzescian I believe we have everything we need at this point.

**Comment by mateuszzagorski** [comment]
@magda-chrzescian if you could clarify the colors for the design - [https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-853042066](https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-853042066)  
  
Should we use a standard font color for text input, checkbox labels ( --ck-color-text: hsl(0, 0%, 20%) ) or go with something more grey-ish?  
  
And regarding buttons - should I use a standard bg color ( --ck-color-base-active: hsl(208, 88%, 52%) ) and use the predefined one for hover/focus ( --ck-color-base-active-focus: hsl(208, 88%, 47%) ), same thing for disabled buttons ( --ck-color-switch-button-off-background: hsl(0, 0%, 69%) ) or pick colors from screenshots/framer demo?

**Comment by magda-chrzescian** [comment]
@mateuszzagorski let's go with the defaults. I used the default colours, but I didn't pay much attention to it while sharing the screens, so there might be some inconsistencies.
Let me know when your'e done with some basic UI, I will take a look and make sure it looks ok. :)

**Comment by cmak9149** [comment]
Regarding "Match cyclic option (from CKE4)?", it will not be implemented at all?
