### ISSUE TITLE
Update npm engine version in `packange.json` in all repositories

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#972]
What we have now in all repositories is:
```json
  "engines": {
    "node": ">=6.0.0",
    "npm": ">=3.0.0"
  }
```

What we should have is:
```json
  "engines": {
    "node": ">=6.0.0",
    "npm": "^4.0.0"
  }
```

**Comment by Reinmar** [comment]
Not necessarily. We know that npm 5 sometimes causes issues. But we don't know for how many guys it works just fine. I don't think that we should be doing this change unless it's proven that npm 5 causes issues in normal scenarios.
