### ISSUE TITLE
Adding title attribute to mediaEmbed

### ISSUE THREAD

**Issue by Nora10** [ckeditor/ckeditor5#9732]
## 📝 Provide detailed reproduction steps (if any)

1. … How to add a title attribute to iframes/media/videos. Right now i have been able to add <div oembed-url=" url" oembed-title="dynamic title> but i cant go further.

### ✔️ Expected result

_What is the expected result of the above steps?_
<figure media>
  <iframe src="url" title="dynamic title">
 </figure>

### ❌ Actual result

_What is the actual result of the above steps?_

the title is been stripped out of the iframe

## 📃 Other details
I would like to be able to add a dynamic title for each media i embed. I have tried to create plugins and mock the mediaRegistry and utils file. I ahve gone through the docs for https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html#adding-an-html-attribute-to-certain-inline-elements
* Browser: … chrome
* OS: … ubuntu
* First affected CKEditor version: … ckeditor5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
@Nora10, I wrote a plugin that allows converting the `oembed-title` attribute.

- view -> model: the view attribute `oembed-title` will be set on the `media` element as the `title` attribute
- model -> view: the model `title` attribute will be set on the view figure as the `oembed-title` attribute.

The plugin does not allow modifying the attribute via the interface. You must do this. I prepare a solution that shows the idea of the entire conversion process. I hope it helps enough.

```js
class MediaEmbedTitleAttribute extends Plugin {
	/*
	 * @inheritDoc
	 */
	static get requires() {
		return [ MediaEmbedEditing ];
	}

	init() {
		const editor = this.editor;
		const conversion = editor.conversion;
		const elementName = editor.config.get( 'mediaEmbed.elementName' );

		// Extend the model element to allows the `title` attribute.
		editor.model.schema.extend( 'media', { allowAttributes: [ 'title' ] } );

		// View -> Model (data-oembed-url -> url)
		conversion.for( 'upcast' ).add( dispatcher => {
			// Upcast semantic media.
			dispatcher.on( `element:${ elementName }`, ( evt, data, conversionApi ) => {
				upcastTitleAttribute( data.viewItem, data, conversionApi );
			} );

			// Upcast non-semantic media.
			dispatcher.on( 'element:div', ( evt, data, conversionApi ) => {
				const viewItem = data.viewItem;
				const isOembedUrl = viewItem.getAttribute( 'data-oembed-url' );

				// Converting a non-oembed element.
				if ( !isOembedUrl ) {
					return;
				}

				upcastTitleAttribute( viewItem, data, conversionApi );
			} );
		} );

		// Model -> View.
		conversion.for( 'downcast' ).add( dispatcher => {
			// How to convert the `title` attribute on model element in view.
			dispatcher.on( 'attribute:title:media', ( evt, data, conversionApi ) => {
				// The media will be already converted - so it will be present in the view.
				const viewFigure = conversionApi.mapper.toViewElement( data.item );
				const writer = conversionApi.writer;

				// Set the attribute if exists.
				if ( data.attributeNewValue ) {
					writer.setAttribute( 'oembed-title', data.attributeNewValue, viewFigure );
				}
			} );
		} );

		// Tries to convert the `oembed-title` attribute from view to the `title` attribute in model.
		//
		// @param {module:engine/view/element~Element} viewElement
		// @param {module:engine/conversion/upcastdispatcher~UpcastConversionData} data
		// @param {module:engine/conversion/upcastdispatcher~UpcastConversionApi} conversionApi
		function upcastTitleAttribute( viewElement, data, conversionApi ) {
			const oEmbedTitle = viewElement.getAttribute( 'oembed-title' );

			// The element does not contain the `oembed-title` attribute.
			if ( !oEmbedTitle ) {
				return;
			}

			const consumableAttributes = { attributes: [ 'oembed-title' ] };

			// Check whether it can be consumed.
			// Might be consumed by something else - i.e. other converter with priority=highest - a standard check.
			if ( !conversionApi.consumable.consume( viewElement, consumableAttributes ) ) {
				return;
			}

			const mediaElement = data.modelCursor.nodeBefore;

			conversionApi.writer.setAttribute( 'title', oEmbedTitle, mediaElement );
		}
	}
}
```

**Comment by Nora10** [comment]
@pomek , trying it out now. thank you so much :) . I'll be back in a jiffy.

**Comment by Nora10** [comment]
@pomek  Thanks for your help. 
I was stuck at this stage  below **before** your implementation above : 

![MediaTitle - current](https://user-images.githubusercontent.com/38266274/120428830-5d916680-c342-11eb-9122-2233df6017e8.png)

But with your awesome help, i was able to get to this stage now ...**so much progress**.... :100: 
![MediaTitle - version2](https://user-images.githubusercontent.com/38266274/120428964-98939a00-c342-11eb-9006-117df84836ac.png)

**Question:** 
Please how can i achieve adding a "title" attribute to the nested iframe?  From the last image above, we now have access to "o-embed-title", and "data-oembed-title" in the inner div, but the iframe tag remains without a title attribute. 

**Steps i've tried:** 
On the mediaEmbedEditing.js, we have the providers array that has a "name", "url" , and "html". I have tried adding another key-value of "title": "dynamic-title" but it doesnt work. I can also see that in the mediaregistry.js, we have a providerDefinitions array that is looped. i manipulated there too, but no luck. I even tried using the extraProviders config to override providers - no luck there too. To summarize, can i add to the providerDefinitions pls? If yes, pls how do i go about it? 
Here's a sample of the providerDefinition object i was talking about - showing what i'm hoping to achieve.
```{
	name: 'youtube',
	url: [
		/^(?:m\.)?youtube\.com\/watch\?v=([\w-]+)/,
		/^(?:m\.)?youtube\.com\/v\/([\w-]+)/,
		/^youtube\.com\/embed\/([\w-]+)/,
		/^youtu\.be\/([\w-]+)/
	],
        title: 'dynamic-title'
	html: match => {
		const id = match[ 1 ];
		  return (
			  '<div style="position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;">' +
				  `<iframe src="https://www.youtube.com/embed/${ id }"  title=${dynamic-title}"` +
					  'style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" ' +
					  'frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>' +
				  '</iframe>' +
			  '</div>'
		  );
	  }
},```

The html array doesnt have access to extra key-value pairs. Eg. match[2] 
Thanks in advance. Suggestions are welcome too.  :)

**Comment by pomek** [comment]
@Nora10, the code you shared will not work this way. The `match` argument is an object representing a result of match inserted media (into the editor) against regexp URLs (in your code, the `url` array).

It translated the URL (from the model) to the view. You have no access to other data than the regexp results.

I'd update the downcast function that I showed you last time:

```js
// Model -> View.
conversion.for( 'downcast' ).add( dispatcher => {
	  // How to convert the `title` attribute on model element in view.
	  dispatcher.on( 'attribute:title:media', ( evt, data, conversionApi ) => {
		  // The media will be already converted - so it will be present in the view.
		  const viewFigure = conversionApi.mapper.toViewElement( data.item );
		  const writer = conversionApi.writer;
	  
		  // Set the attribute if exists.
		  if ( data.attributeNewValue ) {
			  writer.setAttribute( 'oembed-title', data.attributeNewValue, viewFigure );
		  }
	  } );
} );
```

The `viewFigure` variable is the container you showed on screenshots:

![image](https://user-images.githubusercontent.com/2270764/120435245-c5b16e00-c37d-11eb-9c0b-9def1ef4bcee.png)

To get the `<iframe>` element, it should be enough to get first children three times:

```js
const iframe = viewFigure
	.getChild( 0 ) // div.ck-media__wrapper
	.getChild( 0 ) // div (iframe wrapper)
	.getChild( 0 ) // iframe
```

However:

1. If the order of these elements will change, the code will not work, so you need a little smarter solution. See the example. 
	```js
	// The `linkInImage` element is something like this: <a href="">...</a>.
	// It can contain many children. We would like to find the `<img>` element.
	// It can be a first child in the link element but it is not a rule.
	// So we iterate over all link's children and looking for the `<img>`.
	const viewImage = Array.from( linkInImage.getChildren() ).find( child => child.name === 'img' );
	```
2. Make sure that different providers (YouTube, DailyMotion, etc.) can return the view structure that does not match your assumptions. You should keep it in mind.

I hope this helps.

**Comment by Nora10** [comment]
@pomek , thanks for the above message. 
From the downcast conversion you re-pasted above, my viewFigure doesnt have access to the iframe in the codebase directly. I can access the figure and the next child ( div.ck-media__wrapper), but i cant access the wrapping div and the iframe.
Here's a snapshot : 

![MediaTitle - viewFigure](https://user-images.githubusercontent.com/38266274/120616186-031e0600-c427-11eb-9472-6dc860a60f38.png)

Its pretty weird, cause i can manually just access it in the console via JS.

Also, the wording of "point 2" is not really clear -  _can return the view structure that does not match your assumptions_ . Pls could you expatiate more? 

I'm assuming the required action to acheive the "<iframe src="youtube.ca/..." title="dynamic-title">/<iframe>" would be: 

```
const iframeElement = viewFigure.getChild(0).getChild(0).getChild(0); //not working 


// Model -> View. - Adding a setAttribute for the writer for iframe 
conversion.for( 'downcast' ).add( dispatcher => {
	  // How to convert the `title` attribute on model element in view.
	  dispatcher.on( 'attribute:title:media', ( evt, data, conversionApi ) => {
		  // The media will be already converted - so it will be present in the view.
		  const viewFigure = conversionApi.mapper.toViewElement( data.item );
		  const writer = conversionApi.writer;
	  
		  // Set the attribute if exists.
		  if ( data.attributeNewValue ) {
			  writer.setAttribute( 'oembed-title', data.attributeNewValue, viewFigure );
			  writer.setAttribute( 'title', data.attributeNewValue, iframeElement ); //should set <iframe title="dynamic-title"></iframe>
		  }
	  } );
} );```

Did i get something wrong pls?

**Comment by Nora10** [comment]
@pomek

**Comment by pomek** [comment]
Apologies, @Nora10, but I’m afraid I’m unable to dig into it further.

I showed you the initial/starting point for custom development. Unfortunately, debugging the issue requires more research than I expected, and I cannot help you out here on GitHub.

I hope you will be able to resolve it by yourself or with community help. Good luck!

PS: For complex cases that require custom development, you can reach out to our support/sales team via https://ckeditor.com/contact/ as part of the commercial offering.

**Comment by Nora10** [comment]
@pomek Thank you so much for  your help starting this up, and responding. I was able to achieve my goal. 
With some manipulation and interception of the title attribute. Here's a screenshot below. Such a happy ending!

![Fixed Iframe media title](https://user-images.githubusercontent.com/38266274/121369330-bf853980-c909-11eb-9afa-77b9ae188b70.png)

We can go ahead and close the ticket
