### ISSUE TITLE
CKEditor causes overflow past edge of page when container width is 100%

### ISSUE THREAD

**Issue by adamerose** [ckeditor/ckeditor5#9739]
## 📝 Provide detailed reproduction steps (if any)

1. Codepen: https://codepen.io/adrotog/pen/WNpRdry
2. Resize window so that toolbar items collapse
3. Horizontal scrollbar appears allowing scrolling beyond the boundary of `<body>` and `<html>`

Video demo:  https://www.screencast.com/t/H6vzU5ZkYorR

![image](https://user-images.githubusercontent.com/10884874/119048911-e2b56c80-b98d-11eb-8df2-e580acc9fab9.png)

## 📃 Other details

Build Version: **ckeditor5/27.1.0/classic**

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Issue no longer exists in the newest releases. Hence, cloisng this thread.
