### ISSUE TITLE
Pressing spacebar 2 times adds dot after some of the characters.

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#9740]
## 📝 Provide detailed reproduction steps (if any)

1.  Visit any page in the documentation with the editor, like [https://ckeditor.com/docs/ckeditor5/latest/features/font.html](https://ckeditor.com/docs/ckeditor5/latest/features/font.html)  
    Or run any manual test, for example, `mention`
2.  Click in-between any word, or at the end of it.
3.  Press the spacebar 2 times.

It seems like if you try it after   `,  .  :  ;  "  '` characters for example, it won't add the  `.`   
But it will after   `/  |  \  &  $  (  @  ~`  and more.

### ✔️ Expected result

The text should be separated, or at the end of the word/line 2 spaces should be added.

### ❌ Actual result

After pressing the spacebar 2 times, a dot appears, replacing the first space.

## 📃 Other details

*   Browser: Tested on Safari 14.1, and Chrome 90.0.4430.212
*   OS: macOS Big Sur 11.3

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
It looks like it's a newish iOS feature and not an editor bug itself. It's possible to recreate this behavior almost anywhere (default Github editor, chrome URL bar, random input field, or even TextEdit app). Also, it can be turned off in System Preferences -> Keyboard -> Text -> "Add full-stop with double-space" checkbox.

**Comment by Mgsy** [comment]
As @LukaszGudel said, this is macOS default behaviour, not related to the editor, which could be turned off in the settings.
