### ISSUE TITLE
How to add custom plugin to a build created using online builder tool

### ISSUE THREAD

**Issue by pulkitpatel95** [ckeditor/ckeditor5#9749]
I've created a custom build using [online builder tool](https://ckeditor.com/ckeditor-5/online-builder/) and everyting is working fine.

Now, I want to add a custom button to toolbar. For that, I have created a custom plugin as below:

`import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';

export default class CustomHelpPlugin extends Plugin {
    
  init() {
    console.log(`Plugin init`);
    const editor = this.editor;

    editor.ui.componentFactory.add('helpButton', locale => {
      const view = new ButtonView(locale);

      view.set({
        label: 'Help',
        //icon: uploadIcon,
        tooltip: true
      });

      // Callback executed once the icon is clicked
      view.on('execute', () => {
         // fire a JS event
         window.dispatchEvent(new Event('ckEditor_help_event'));
		 console.log(`Event dispatched`);
      });

      return view;
    });
  }
}`

and adding this plugin to ckeditor.js as below :

`
import CustomHelpPlugin from './help-plugin.js'

class Editor extends ClassicEditor {}

// Plugins to include in the build.
Editor.builtinPlugins = [
	...,
	CustomHelpPlugin
];
`

But when I run the sample/index.html, it gives below error: 

TypeError: Illegal constructor
    at new uv (help-plugin.js:4)
    at plugincollection.js:421
    at Array.map (<anonymous>)
    at plugincollection.js:420
    at lo.init (plugincollection.js:206)
    at hv.initPlugins (editor.js:242)
    at classiceditor.js:192
    at new Promise (<anonymous>)
    at Function.create (classiceditor.js:188)
    at index.html:106

Can you help me where I am wrong ?

**Comment by Mgsy** [comment]
Hi, did you import `Plugin` class which is extended by your custom plugin?

```javascript
import Plugin from '@ckeditor/ckeditor5-core/src/plugin
```

**Comment by pulkitpatel95** [comment]
Oh yeah, that was missing, I thought I read somewhere you don't need to import Plugin class so didn't check that.
Thanks for the quick help 😃.
