### ISSUE TITLE
Only Last Item in Toolbar is shown

### ISSUE THREAD

**Issue by GarOracle** [ckeditor/ckeditor5#9753]
👍 

I have entered this as a question at: https://stackoverflow.com/questions/67627152/how-can-i-figure-out-why-my-toolbar-only-has-one-item

1) Custom build.  27.1.0.
2) From StackOverflow: I've been building up my CKE5 implementation a step at a time. It is to replace CKE4. It is inside of a JQuery UI dialog. The create method is pretty standard, but has some extra code for tracking multiple instances and "onEditorisCreated" logic that was in CKEDITOR.on('instanceReady', function (ev). I have multiple configurations and they worked outside of my application in a stand-alone application I wrote. Now the toolbar only shows the last item, regardless of the configuration I use. The editor object returned from the create method has the config, looking just fine. There are no errors on the console - I've found CKE5 to be pretty good about logging issue. The markup only has the one toolbar item, they are not simply hidden. Any thoughts on how to debug this?
3) When I have a breakpoint in my wrapper code I see that  as soon as the cke create method is called, before my wrapper code (except populating config) only the one button exists.  

### ✔️ Expected result

I see all of my toolbar buttons

### ❌ Actual result

Only the last toolbar button is shown.

## 📃 Other details

* Browser: … Chrolme
* OS: … Windows
* First affected CKEditor version: … 27.1.0
* Installed CKEditor plugins: … 
* 	Alignment,
	AutoImage,
	Autoformat,
	Base64UploadAdapter,
	BlockQuote,
	Bold,
	CKFinder,
	Clipboard,
	CloudServices,
	EasyImage,
	Essentials,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	Heading,
	HorizontalLine,
	Image,
	ImageCaption,
	ImageResize,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	InsertImage,
	Italic,
	Link,
	List,
	ListStyle,
	MediaEmbed,
	MediaEmbedToolbar,
	PageBreak,
	Paragraph,
	PasteFromOffice,
	Placeholder,
	RemoveFormat,
	SpecialCharacters,
	SpecialCharactersArrows,
	SpecialCharactersCurrency,
	SpecialCharactersEssentials,
	SpecialCharactersLatin,
	SpecialCharactersText,
	Strikethrough,
	Subscript,
	Superscript,
	Table,
	TableCellProperties,
	TableProperties,
	TableToolbar,
	TextTransformation,
	UploadAdapter,
	Underline

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jswiderski** [comment]
Please do not report implementation problems on CKEditor issue tracker. Licensed users should always use support channel for such cases.

**Comment by GarOracle** [comment]
How do I use the support channel?
________________________________
From: j.swiderski ***@***.***>
Sent: Monday, June 7, 2021 6:17 AM
To: ckeditor/ckeditor5 ***@***.***>
Cc: Garry Stumpf ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [ckeditor/ckeditor5] Only Last Item in Toolbar is shown (#9753)


Please do not report implementation problems on CKEditor issue tracker. Licensed users should always use support channel for such cases.

**Comment by lslowikowska** [comment]
Hi @GarOracle, the main support channel for our customers is emails and this is what you have already used so I have responded to you there 👍 You can send your support requests to us either by using the support@cksource.com email address or the support service platform at https://support.ckeditor.com/hc/en-us. Let me know if you have any questions regarding that - I will be happy to provide more information. For the issue itself, let's stick to the conversation in the emails.
