### ISSUE TITLE
[IME][Windows][Chrome] Turning bold on/off during composition breaks it

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#976]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Tested on `v1.0.0-beta.2`.

## 📋 Steps to reproduce

Extracted from https://github.com/ckeditor/ckeditor5-engine/pull/1355#issuecomment-381516509.

1. Open the article sample.
1. Put the caret at the end of the `Paragraph`.
1. Press <kbd>Ctrl</kbd> + <kbd>B</kbd>.
1. Start the composition (**Hiragana**) and type something.
1. Press <kbd>Ctrl</kbd> + <kbd>B</kbd>.

## ✅ Expected result

Well, not sure what should exactly happen. On native `contenteditable` the composition is just continued (as one part), however if you start switching composed characters (<kbd>Arrow up</kbd> or <kbd>Arrow down</kbd>) the whole composition becomes bolded. It might be hard to mimic such behaviour.

Maybe we should just disallow turning bold off during composition? Not sure how it will affect usability for the users which create content mainly by composing.

## ❎ Actual result

Composition is broken, continuing typing after second <kbd>Ctrl</kbd> + <kbd>B</kbd> press reinsert whole composed part (so it is duplicated) - the good news is composition still works so you can end it and delete duplicated part.

## 📃 Other details that might be useful

Only on Chrome on Windows it is possible to turn off styling (e.g. `Bold`) during composition.

**Comment by Mgsy** [comment]
I can't reproduce it anymore.
