### ISSUE TITLE
Option to add source code on toolbar like a ckeditor4.

### ISSUE THREAD

**Issue by harleenarora** [ckeditor/ckeditor5#9766]
There is no source code option in ckeditor5.

For exapmple ckeditor4:: 
https://nimb.ws/gW1hGx
https://nimb.ws/o1gDIq

Feature Request for new plugin::
`sourceCode`

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
See https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html
