### ISSUE TITLE
Invalid links in the docs

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#9767]
## 📝 Provide detailed reproduction steps (if any)

Build docs locally and open http://127.0.0.1:8080/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration-integration.html.

### ✔️ Expected result

All links are correctly generated.

### ❌ Actual result

Some links are not created. It looks like the `{@link @ckeditor4 ...}`, `{@link @ckeditor5 ...}` and `{@link @cs ...}` are not properly handled by the docs builder:

<img src="https://user-images.githubusercontent.com/56868128/119793989-619f2d80-bed7-11eb-971e-4d7117662c40.png" width="700">

This error **does not occur** in latest stable build: https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration-integration.html

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
It happens because, from the local environments, we do not have access to "external" projects, which is CS in such a case.

**Comment by psmyrek** [comment]
Thanks for the explanation, I didn't know. So I'm closing this issue.
