### ISSUE TITLE
TrackChanges with Chinese input leads to incorrect behavior (BUG)

### ISSUE THREAD

**Issue by chenyang9725** [ckeditor/ckeditor5#9770]
I'm Chinese and I use chinese input to input text into the editor.  but in the trackChanges mode, the editor will not only record the chinese word but also the letter of chinese word. see below.

https://user-images.githubusercontent.com/79300514/119815653-5d4a3300-bf1e-11eb-9320-1f70f3dc96a2.mov

And I found that the editor can produce correct behavior in some conditions. For example, I paste some chinese word into the editor, then move the cursor into the words, then I start to text. It looks good . see below.

https://user-images.githubusercontent.com/79300514/119816044-cf227c80-bf1e-11eb-93fc-aa81b74e9e82.mov

Strangely, if I only paste the chinese word on the editor, not moving the cursor, then start to text, it still has problem. See below.

https://user-images.githubusercontent.com/79300514/119816282-1b6dbc80-bf1f-11eb-8f81-82ddcd8c790e.mov

### ✔️ Expected result

We can use chinese input to text  correctly.( without the letter of chinese word)

### ❌ Actual result

The editor inserts the letter of chinese word with chinese word together . 

## 📃 Other details

* Browser:Chrome
* OS: MacOSX
* First affected CKEditor version: I produced these steps on your official [website](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes.html). 
--
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by chenyang9725** [comment]
Looking forward to a reply

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply, this ticket somehow slipped our attention. We are aware of this bug, as it's a part of a bigger issue with IME in general. This one and similar bugs will most probably be resolved when we get back to work on [migration to `beforeInput`](https://github.com/ckeditor/ckeditor5/issues/7462). Unfortunately right now we cannot guarantee any ETA for this, as we have lots of other obligations and ongoing work.
  
Apart from that, Track Changes is a commercial plugin and this issue tracker is mainly for the purpose of open source community. If you are a licensed user and have any problems when using the editor, feel free to [contact us through the support channel](https://ckeditor.com/contact/). Our dedicated support team will investigate the problem and get back to you as soon as possible.  
  
For now, I'll close this issue as a duplicate.
