### ISSUE TITLE
removePlugins errors

### ISSUE THREAD

**Issue by teobatman00** [ckeditor/ckeditor5#9775]
I would like to test removePlugins and it won't work as my expectation. So that I need you to fix it. Here is the issue

![image](https://user-images.githubusercontent.com/65856769/119922177-7fcd6200-bf99-11eb-8d35-cc4fc4ef4514.png)
![image](https://user-images.githubusercontent.com/65856769/119922295-c02ce000-bf99-11eb-8f3d-40d34545958b.png)

Your Documentation
![image](https://user-images.githubusercontent.com/65856769/119922465-0b46f300-bf9a-11eb-998d-4f1e06ae31d1.png)

The Fact 
![image](https://user-images.githubusercontent.com/65856769/119922223-9673b900-bf99-11eb-9917-aa23f28b28d4.png)

**Comment by AnnaTomanek** [comment]
@ckeditor/qa-team Potentially something to check after we merge the installation guides restructuring.

**Comment by dufipl** [comment]
Hello @teobatman00 👋 
Thank you for reporting the issue!
Could you please share the full configuration of the CKEditor 5 that you are using so we can try to reproduce this issue on our side?
