### ISSUE TITLE
Design and create an icon for the view source feature 

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9778]
Related to https://github.com/ckeditor/ckeditor5/issues/9647

**Comment by magda-chrzescian** [comment]
Here are some ideas (these are the sketches only) for the source editing mode icons:

![image](https://user-images.githubusercontent.com/14334820/120003991-8c23e000-bfd6-11eb-803f-960c51a24548.png)

On the left, I pasted our current icons for the inline code, code block, and HTML embed, as we don't want to go with something too similar.

WDYT? Do you have any favorites? Are some icons more understandable than others? Is it ok to use `<>` for both HTML and Markdown sources?

If you need some more context (icons in the toolbar/whole editor) please let me know.

**Comment by ma2ciek** [comment]
For me, the 2 and 3 are the most intuitive as there's a pencil icon there suggesting the editing and the `<>` representing the source of the document. 

4\. for me is a bit similar to the code block feature.

**Comment by pomek** [comment]
(3) looks good to me.

**Comment by niegowski** [comment]
For me also 3rd option looks the most intuitive. Do we consider using a labeled button there like in CKE4?

**Comment by Reinmar** [comment]
> For me also 3rd option looks the most intuitive. Do we consider using a labeled button there like in CKE4?
> 
> :thumbs up: 1

It's a quite specific button as it toggles the editor mode instead of performing an editing action. I think it makes sense that it stands out, the same way it did in CKE5.

What's more – in many scenarios people may want to move it outside the editor (like tabs in GH where you have "Markdown" and "Preview"). Thus, I think it's worth documenting how to trigger the source mode from the code.

**Comment by Reinmar** [comment]
As for the proposed icons, frankly speaking, if there's also "code" and "HTML snippet" feature in the editor, then IMO none of the options will be clear by the icon itself :D That's why the label may be necessary.

But I also like 3 the most. It combines the "document" and "source" and "editing".

**Comment by magda-chrzescian** [comment]
> It's a quite specific button as it toggles the editor mode instead of performing an editing action. I think it makes sense that it stands out, the same way it did in CKE5.

Well, we also have export buttons, which don't stand out (maybe they should?). I get the idea and don't reject it, but since we're always short in the toolbar space, I would consider carefully whether it's necessary.

> As for the proposed icons, frankly speaking, if there are also "code" and "HTML snippet" features available in the toolbar, then IMO none of the options will be clear by the icon itself :D That's why the label may be necessary.

We could try to make the icon stand out by its position in the toolbar - possibly should be the first/last one, such as the export icons. There is also a problem with the existing icons, they really look like presenting the whole document, not just a block to insert. I like the 'code block' icon from CKE4 better.
![image](https://user-images.githubusercontent.com/14334820/120278249-55d7b080-c2b5-11eb-9de5-277239e85af2.png)
Still, changing the existing icons can be confusing for the end user.

**Comment by godai78** [comment]
I'd say 2, tho I'd gladly see the HTML embed icon instead for this (I mean, stating HTML in open looks powerful) but yes, this would puzzle people.  
  
Also opting for putting this first in its own section in the toolbar.

**Comment by oleq** [comment]
4\. makes the most sense to me.

Key decision factors:

*   Consistency with "export to \*" icons as all these features work on the document level (as opposed to 1. and 2. that look like blocks/dialogs/windows).

![](https://user-images.githubusercontent.com/1099479/120303215-e8d11480-c2ce-11eb-914a-e23af79362a4.png)

![](https://user-images.githubusercontent.com/1099479/120303247-f25a7c80-c2ce-11eb-8bc0-0706af05fb9f.png)

*   Simplicity. Less noise is better. We can live without the pencil in the icon (as opposed to 3.).

Additionally:

*   The labeled button like in v4 feels OK to me. This button switches the entire editor between two very distinct modes and this should be clear. 
    *   If we ever have a button that switches between the normal and restricted editing, it should look the same (ATM it's implemented as an API and outside the editor).
        *   Also, let's make sure this button has a unique CSS class. This is related to #5551, which hasn't been solved yet but using this class developers will be able to get rid of the label easily (delivered by `.ck-button_with-text`) either via CSS or by iterating over `toolbar.items`, identifying it by `item.class` and setting `item.withText = false`.
*   In all default toolbar configurations, this button should be followed/preceded by a separator.
*   In the feature demo, this button should be the first in the toolbar and followed by a separator (like in v4).

**Comment by magda-chrzescian** [comment]
Considering your feedback (thank you a lot, it was really helpful), I'd like to suggest the following icon:
![image](https://user-images.githubusercontent.com/14334820/120320777-d5c83f80-c2e2-11eb-9353-3370578580e5.png)
and using it with the 'Source' label.

I changed it a bit to be more consistent with export buttons, but I didn't want to give up the pencil, as an indicator that we are going to edit something seemed pretty important (especially when being so similar to the export buttons)
