### ISSUE TITLE
Image gallery plugin

### ISSUE THREAD

**Issue by mabar** [ckeditor/ckeditor5#978]
Is there an image gallery plugin or is it planned at least? Thanks.

**Comment by Reinmar** [comment]
No, there's no such plugin yet and it's not planned.

Could you describe how would you see it work? And why does it need to be a feature of the editor and not of the system in which the editor is included?

**Comment by biomancer** [comment]
@Reinmar Hi! What do you think would be the best way to implement image gallery that may appear in any part of editor content, just like a single image? Gallery should be build separately and then we should add some placeholders and replace them with gallery html before rendering content? 
It seems that gallery is just some images grouped together in terms of semantic html, why is it any different from single images?
