### ISSUE TITLE
List the find and replace plugin in main repository

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9786]
## Provide a description of the task

Following should be done:

1.  Add the newly created package to:
    *   [CKEditor 5 repository's package list](https://github.com/ckeditor/ckeditor5#packages)
    *   [`ckeditor5#package.json`](https://github.com/ckeditor/ckeditor5/blob/master/package.json)

**Comment by mateuszzagorski** [comment]
I’ve added the new package to CKEditor 5 package list: 041812a.

Package.json was updated in a previous commit while working on documentation: 409d73e.

**Comment by mlewand** [comment]
LGTM :+1:
