### ISSUE TITLE
Implement the enter feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#98]
To be implemented in ckeditor5-enter.

**Comment by Reinmar** [comment]
We've been discussing with @pjasiun how could features affect the behaviour of the enter key. The ckeditor5-package cannot implement all possible scenarios working for all possible features (e.g. it should be a list plugin who defines how enter key works within lists). The default implementation should be minimal or even only provide the basic architecture.

So a central bus where other features could listen is needed. That bus must be available even when the enter feature wasn't loaded. Also, there should be a way for other features to trigger the enter feature for the current selection (so the enter command).

We thought about the following:

1. The enter feature will use the keystroke handler to fire an `enter` event on the tree view. The tree view becomes the central bus for editing events, which makes a perfect sense as it's the editing view.
2. The enter feature exposes an enter command which will fire the event on the tree view. So the command mimics the native behaviour.
3. The features will be able to listen to tree view's `enter` event and handle it when they want.
4. The enter feature may implement some basic logic for the enter, like handling paragraphs. However, there will be a paragraph feature, so perhaps that's unnecessary.
5. Other features can import modules from the enter package (or even the enter feature itself, but without saying that it's required, what will prevent its initialisation ;>) to use those tools in order to implement their behaviour. The only problem is that if someone  won't enable the enter feature its utils code will still be included... but that's unavoidable. However, the feature implementer may implement the enter support for his/her feature in a separate feature if that's a lot of code (but of course that would be an overkill :D).

**Comment by fredck** [comment]
I'm just worried about the "heading > ENTER > paragraph" case. The heading feature knows nothing about the paragraph feature and vice versa, so the feature itself should not make a reference to the other feature.

It may happen that some kinds of node classification need to taken in consideration. For instance, the enter feature may **by default** break "block nodes". The heading feature instead may say that ENTER should start a "default block" after it. So such kinds of generic notations may have to be defined.

**Comment by Reinmar** [comment]
I've been thinking about this case as well. The schema should define how the enter at the end of a heading should work. So far it defines block elements, but it does not define the main one. We can do two things:

1. Add `$baseBlock` to schema. The enter key listener defined in the heading feature would know that this block needs to be used.
2. Say that if any blocks are allowed inside the current editable, then `p` is the base/default one. Then all features will default to it.

The first option is more flexible, but I think that the second is fully justifiable. If anyone wants to implement the paragraph feature differently than we, then it's of course possible. But that feature must use the `p` element.

**Comment by Reinmar** [comment]
Actually, the second option is what we did in CKEditor 4. I don't recall problems with that specific decision.

**Comment by fredck** [comment]
Why you say "'p' element", not "'paragraph' node"? Enter works on the Data Model, so we don't care how converters represents it in the view.

I was just wondering what happens if the paragraph feature is not available. In such case `$defaultBlock` (my preferred name for it as it doesn't involve "inheritance") may be null and then, for example, the heading feature may decide to start a new heading on ENTER (or actually just leave the default implementation to run).

**Comment by Reinmar** [comment]
> Why you say "'p' element", not "'paragraph' node"? Enter works on the Data Model, so we don't care how converters represents it in the view.

Because we haven't decided yet whether we'll call it `p` or `paragraph` :D. Most likely it will be `paragraph`, to not make too close relations to how the DOM will look. It won't help much in this case, but should make a difference in other cases. Anyway, `p` was just faster to type now. And, to be precise, it's not a `paragraph` node, but element.

> I was just wondering what happens if the paragraph feature is not available. In such case $defaultBlock (my preferred name for it as it doesn't involve "inheritance") may be null and then, for example, the heading feature may decide to start a new heading on ENTER (or actually just leave the default implementation to run).

If the paragraph feature won't be defined then `paragraph` element won't be allowed by the schema. So that's why we don't need `$defaultBlock` to know whether enter can create a block. It's just a question whether we want to hardcode the name and whether (perhaps) it should be in anyway dynamic.

**Comment by fredck** [comment]
> If the paragraph feature won't be defined then paragraph element won't be allowed by the schema. So that's why we don't need $defaultBlock to know whether enter can create a block. It's just a question whether we want to hardcode the name and whether (perhaps) it should be in anyway dynamic.

Fair enough for me. KISS for now as it is possible to make it a feature in the future.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-enter/issues/1
