### ISSUE TITLE
Refine the image guides

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9804]
## Provide a description of the task

A follow-up of #8591.

---

TODOs as of a0f4e00:

*   [x] Replace demo content in the snippets - @magda-chrzescian to propose beautiful images, @godai78 to propose text
*   [x] The resizing images guide is block image-centric. Both contents in demos and code snippets should include inline images `features/images/images-resizing.html`
*   [x] Magda knows what to do with the image style guide `features/images/images-styles.html`
*   [x] ~~An entry in `builds/guides/whats-new.html` :P (just kidding)~~ let's just nuke this page, please
*   [x] Obvious TODOs in the content and broken links :P
*   [x] Links to builds in docs in the table `features/images/images-overview.html#image-features` are missing. Maybe the plugins should also be linked?
    *   [x] This sort of comes down to changes in the list that precedes the table: plugin names should not be used here at all but natural language links to sub-feature guides.
*   [x] Better images in the demo `features/images/images-text-alternative.html`
*   [x] The linking images guide is block image-centric. Missing inline images in demo content and in code snippets `features/images/images-linking.html`
*   [x] A cross-link to the migration guide is necessary in the "inline vs. block" section `/features/images/images-installation.html#inline-and-block-images`
*   [x] Image upload overview should backlink to images overview somewhere at the beginning `features/images/image-upload/image-upload.html`

**Comment by oleq** [comment]
Just for starters, the [custom styles](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-styles.html#custom-styles) demo is really great but not without issues. So here are some of them that I spotted:

* Snippet styles using `.ck.ck-content ...` (or, in reality, anything generic) apply not only to the custom styles demo but to all editors on the web page. CSS does not come with sandboxing and this must be addressed https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-image/docs/_snippets/features/image-semantical-style-custom.html#L160. In this situation we usually go with something like `#snippet-image-semantical-style-custom + .ck .ck-content`.

* Are these media queries even working https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-image/docs/_snippets/features/image-semantical-style-custom.html#L169-L186? Because there's not a single `.image.side` in the content.

* I'm slightly confused by the image style icons ![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/43c96018-8fb1-43c2-bc0a-0a08765fcb34) shouldn't the globe icon be used for this kind of image style? ATM the globe is used for the margin-right image that does not even exist in the content. My guess is something got mixed up here.

* The editor needs more vertical space. It took me a while to understand there's more (awesome) content in this demo but you need to scroll. People don't like to scroll if they don't have to so if we want to put the spotlight on it, this must be easier.

![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/fb7f5998-cfed-4082-b735-c4a592f86d95)

**Comment by godai78** [comment]
> let's just nuke this page, please

My sentiment exactly. How about we redirect it to overview without letting anyone know explicitly and without starting a bike shed discussion over it? ;)  
  
As for the image side, these were there I myself provided the icons. Would need to yarn the docs again, can't find these on `master` as of now...

**Comment by godai78** [comment]
Here they go, side images. Unless this is not what we're talking about?

![](https://user-images.githubusercontent.com/68123541/120998856-c20c5580-c788-11eb-84a1-9af2c439c9f3.png)

**Comment by magda-chrzescian** [comment]
@oleq thank you for your insight, this demo was never fully finished, especially if it comes to icons and media queries. I hope to be able to come back to that in some time.

In the demo content, there also was a right-margin image. I believe that these margin images shouldn't have icons with any specific pictures as they will look like a picture provided by the editor, I wanted to create some generic "margin" icons for them.

**Comment by magda-chrzescian** [comment]
@oleq Why do we need to show both options here? Seems a bit like information for the `installation` section.

![image](https://user-images.githubusercontent.com/14334820/122157898-f8726080-ce6b-11eb-80bd-fc69aa3d39c3.png)

**Comment by oleq** [comment]
> @oleq Why do we need to show both options here? Seems a bit like information for the `installation` section.

You're right 👍
