### ISSUE TITLE
Missing metadata and html output for the `TableCaption` feature

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#9806]
## 📝 Provide a description of requested docs changes

As in the title, the `TableCaption` plugin is not described in the [`table/ckeditor5-metadata.json`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-table/ckeditor5-metadata.json) file.

```bash
npm run docs:content-styles

> ckeditor5@27.1.0 docs:content-styles /Users/pomek/Projects/ckeditor/ckeditor5
> node ./scripts/docs/build-content-styles.js

...

📍 Looking for new plugins...
Found new plugins.
┌─────────────────────┬──────────────────────────────────────────────────────────────────┐
│ Plugin name         │ Module path                                                      │
├─────────────────────┼──────────────────────────────────────────────────────────────────┤
│ Tablecaption        │ packages/ckeditor5-table/src/tablecaption.js                     │
│ Tablecaptionediting │ packages/ckeditor5-table/src/tablecaption/tablecaptionediting.js │
│ Tablecaptionui      │ packages/ckeditor5-table/src/tablecaption/tablecaptionui.js      │
└─────────────────────┴──────────────────────────────────────────────────────────────────┘
```

Do not forget about executing `yarn run docs:features-html-output --commit` on the branch with the changes.

**Comment by pomek** [comment]
Marking as the `release:blocker`, because Online Builder loads packages from npm.

**Comment by ma2ciek** [comment]
@godai78, could you prepare a description for this plugin?

**Comment by ma2ciek** [comment]
IMO the shorter descriptions are a bit better as we are a bit out of space in the Online builder and most of the other descriptions are shorter.

**Comment by pomek** [comment]
See: https://github.com/ckeditor/ckeditor5/pull/9823#issuecomment-854883752.
