### ISSUE TITLE
[Docs] Document heading buttons

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#982]
I couldn't find any documentation about it so I'm not sure if anyone will notice it. And it's a pity as at least for me it's much more intuitive and easy to use. And the UI looks more consistent with it without a dropdown, it fits much better the ballon toolbar and so on.

By documenting it I mean for example having a note about it and a working demo here: https://docs.ckeditor.com/ckeditor5/latest/features/headings.html

**Comment by Reinmar** [comment]
We added this feature very recently and it's not even properly reviewed yet. We'll document it once it's stabilised.

**Comment by godai78** [comment]
Sooo, what do we need to add here? The guide is just being reviewed, but I can plow it tomorrow if it needs additions.

**Comment by godai78** [comment]
Working branch: https://github.com/ckeditor/ckeditor5/tree/docs-heading-buttons

**Comment by godai78** [comment]
OK, so there is now information about the feature option, there is a working demo with buttons and basic install-info. Hope that does the trick.

**Comment by AnnaTomanek** [comment]
PR open here: #8281
