### ISSUE TITLE
Cannot find what MediaEmbedToolbar does and what toolbar items are available

### ISSUE THREAD

**Issue by felinepc** [ckeditor/ckeditor5#9824]
## 📝 Provide a description of requested docs changes

I'm having a hard time finding out exactly what `MediaEmbedToolbar` does and what toolbar items are available for enabling via the `toolbar` array. The documentation has no mentioning or examples, unlike the image toolbar.

`Array.from( editor.ui.componentFactory.names() )` shows no items related it to it either other than the parent mediaEmbed button.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. `MediaEmbedToolbar` will most probably be used and properly documented when we introduce [styles for media embed](https://github.com/ckeditor/ckeditor5/issues/2781) (keep in mind that we do not provide any ETA for this). There are also no default items/configs that can be used with it.
So currently it can serve as a base for custom development, if you for example would like to create a plugin with your own custom items.
