### ISSUE TITLE
The demo content in the documentation has fixed margin bottom for the last-of-type elements.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9825]
## Provide a description of the task

The following rule: https://github.com/ckeditor/ckeditor5/blob/e58ff6a8d4741a81d9a879770788c14f16f1849d/docs/assets/snippet-styles.css#L32-L34
forces the sie of the bottom margin of every last-of-type element in the editor content. It breaks the behavior of content with custom styling (has to be overwritten with `!important` at this point.

It was introduced in https://github.com/ckeditor/ckeditor5/pull/8550.

This is an example of such behavior: there is no margin between the image and the next paragraph, despite it is directly set with the CSS (as it is the `last-of-type` element in the editor content):

![image](https://user-images.githubusercontent.com/14334820/121816958-f0090280-cc7e-11eb-9f26-0414789d2844.png)

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by niegowski** [comment]
The intention was to exclude the fake selection container from the `:last-child` css rule but this is not supported yet by browsers and the effect is still as it was before introducing this change (the last widget inside the editor):

![](https://user-images.githubusercontent.com/1232187/121019196-7f09ac80-c79f-11eb-8381-7c5de9168a46.gif)

**Comment by magda-chrzescian** [comment]
I actually think that we don't really need any of the `margin: 0` rules:
* current for the `.ck.ck-content > :not(.ck-fake-selection-container):last-of-type` selector,
* previous for the `.ck.ck-content > :last-child` selector.

The extra bottom margin of the last element in the editor doesn't really break the layout, at least it generates some extra space at the end of the content, but I don't think that it looks bad.
