### ISSUE TITLE
Improved errors and better documentation for saving/fetching suggestions in Track Changes

### ISSUE THREAD

**Issue by pocketcolin** [ckeditor/ckeditor5#9827]
I would like to request more robust documentation and errors for the saving/fetching functionality in Track Changes (specifically as it relates to Suggestions). Today, I ran into an issue where CKEditor was throwing the error, `CKEditorError: track-changes-suggestion-data-mismatch`, which stops any typing in the editor field. The issue turned out to be that the `type` param being passed in the payload to CKEditor for a suggestion was missing the `subType`. In other words, I was passing `formatInline` when CKEditor was expecting `formatInline:f3f32fj39` (where the string of characters after the colon is the `subType`). The only way I was able figure this out was by comparing my payload to the example in [this article](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html). I was unable to find any reference to a `subType` or recommendations on how to build the `type` since the `type` returned from the `getSuggestions()` method only includes `formatInline`. 

My suggestion/request here is just more thorough saving/fetching suggestions documentation for Track Changes and better errors because `CKEditorError: track-changes-suggestion-data-mismatch` wasn't specific enough to help diagnose the issue. I would love to see best practices for saving suggestions to an async database (as opposed to pulling them directly from an inline object as is shown in the docs currently).

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply, this ticket somehow slipped our attention. Track Changes is a commercial plugin and this issue tracker is dedicated mostly to the open source part of the CKEditor ecosystem. So if you are a licensed user and encounter any problems with the editor, we encourage to contact us via the [support channel](https://ckeditor.com/contact/) or directly to support@cksource.com. Our team will be happy to look into the issue and respond as soon as possible.  

Now as it comes to the documentation and ways to save suggestions to a database - we'd recommend checking [adapter integration](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/track-changes/track-changes-integration.html#adapter-integration) as it allows for asynchronous communication with back end and it's the recommended way to use this feature.

If you have any further suggestion as it comes to the documentation or believe that it's somehow faulty or misleading, please let us know. I'll close this ticket for now.
