### ISSUE TITLE
Images in editor docs should use absolute links

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9828]
## 📝 Provide a description of requested docs changes

1.  Open [image feature guide](https://ckeditor.com/docs/ckeditor5/28.0.0/features/image.html).
2.  Focus the first editor.
3.  Select all the content.
4.  Copy content.
5.  Open [document editor example](https://ckeditor.com/docs/ckeditor5/28.0.0/examples/builds/document-editor.html).
6.  Paste previously copied content.

### Expected

Image should be pasted.

### Actual

The image is broken and doesn't render.

![](https://user-images.githubusercontent.com/5353898/121149619-1bd15600-c843-11eb-9fa1-dafa40909468.png)

This poses also a broader interoperability problem. If you copy content from editor in our docs and paste it to third party app (e.g. MS Word, Google Docs) it doesn't work. Something that might be perceived as CKEditor issue by non-tech person testing CKE5.

**Comment by Reinmar** [comment]
This was hacked recently by the devops squad: Those URLs are now automatically "absolutized" on page load.
