### ISSUE TITLE
[GHS] Feature guide for General HTML support

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9854]
I think a feature guide would be a good starting point. It needs to be well thought how and where we link to it, but I'll skip this for now.

Important: GHS will be in a "beta" for now, so it actually makes sense to avoid linking to it from too many places. We want people to be able to play with it, but not to focus too broad audience on it.

**Comment by Reinmar** [comment]
I'm still hesitant between "Generic" and "General" for the feature name. 

IDK how well I understand the difference between these words, but for me, both seem related to this feature.

*   Generic because this feature treats all HTML features in the same way.
*   General because it tries to cover all HTML features.

We need to finally make a decision. I'll stick to "General" for now.

cc @AnnaTomanek @wwalc @godai78

**Comment by Reinmar** [comment]
We'll also have to rethink the guide for "Source editing" as it may not make much sense when not combined together with GHS.

**Comment by godai78** [comment]
Well, "general" is more like common, overall or widespread which is basically a positive denotation.

While "generic" means basically the same, but there is - especially in the IT field - the running notion of "generic" being "default", kind "random", "basic" so I would stay with general as it sounds better.

**Comment by oleq** [comment]
General sounds good to me. Universal HTML Support would also be nice IMO.

**Comment by godai78** [comment]
Universal sounds nice but appears much broader like everything is covered everywhere.

**Comment by AnnaTomanek** [comment]
Funny to be late to the party :rofl:  because I was about to recommend "generic" and kinda, thinking about the same as @godai78 but drawing opposite conclusions...

> Well, "general" is more like common, overall or widespread which is basically a positive denotation.
> 
> While "generic" means basically the same, but there is - especially in the IT field - the running notion of "generic" being "default", kind of "random", "basic" so I would stay with general as it sounds better.

"General" - yes, common, but I'd also say in the negative sense, like "not totally complete", "kinda working". So "we support HTML in general but as far as details go, you will need to add custom/more advanced stuff by yourself".

Whereas "generic", for me it's closer to "universal", as in "any HTML", more all-encompassing.

Since we have two different feelings about the same thing, I think I'll go ask what our native speakers think about that.

**Comment by godai78** [comment]
Good.

**Comment by AnnaTomanek** [comment]
OK, so here is the feedback - though it's more _general_ than in the IT context :wink: . Both are fine, still, for lay people "generic" may have the negative connotatations of "cheap", "average", "undistinguished", and "general" looks like it conveys the message well - plus we don't need to change anything to introduce it. So - I think **General HTML support** it is! :loudspeaker: 

PS: By the way, "arbitrary" just came to my mind now, too :speak\_no\_evil:

**Comment by Mgsy** [comment]
Closed by #9864.
