### ISSUE TITLE
[GHS] Clean up the draft PR

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9855]
## Provide a description of the task

*   The manual test throws: http://localhost:8125/ckeditor5/external/ckeditor5-internal/packages/ckeditor5-content-compatibility/tests/manual/generalhtmlsupport.html
*   The automated tests fail on the CI.

**Comment by Reinmar** [comment]
Actually, it's not only about the manual test. The entire feature doesn't work now. I tried this config in the docs:

```javascript
		generalHtmlSupport: {
			allowed: [
				// Enables <div>, <details>, and <summary> elements with all kind of attributes.
				{
					name: /^(div|details|summary)$/,
					styles: true,
					classes: true,
					attributes: true
				},

				// Extends the existing Paragraph and Heading features
				// with classes and data-* attributes.
				{
					name: /^(p|h2-4)$/,
					classes: true,
					attributes: /^data-/
				},

				// Enables <span>s with any inline styles.
				{
					name: 'span',
					styles: true
				},

				// Enables <abbr>s with the title attribute.
				{
					name: 'abbr',
					attributes: [ 'title' ]
				}
			]
```

**Comment by maxbarnas** [comment]
Please make sure you also have the new `Matcher` implementation in CKE5 repo. It's not yet merged and lives on `internal/718` branch. Thankfully, we'll move the entire GHS implementation to CKE5 and those problems will be gone.

**Comment by jacekbogdanski** [comment]
Already done in https://github.com/ckeditor/ckeditor5/tree/ci/656-html-support
