### ISSUE TITLE
config.generalHtmlSupport.allowed -> allow

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9858]
## 📝 Provide a description of the improvement

I find it more intuitive to write `allow` than `allowed`. That's what I wrote when creating a snippet from my memory. Same for `disallowed` -> `disallow`.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jacekbogdanski** [comment]
I've already renamed it on https://github.com/ckeditor/ckeditor5/tree/ci/656-html-support

Also, renamed `config.generalHtmlSupport` -> `config.htmlSupport` as we discussed it on Slack at some point, so we have `config.htmlSupport.allow`/`config.htmlSupport.disallow`.

**Comment by ashishforgrz** [comment]
I have used npm build for ckeditor 5 but when i try to load custom class in ckeditor 5, it is removing the class. Can you help with ckeditor 5 react example for allowing custom classes
