### ISSUE TITLE
Implement basic docs structure

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9862]
* Implement a working doc sample in features section (don't worry about the text content, polished text contet will be added as part of #9721).
* Make sure that API docs have proper structure (like other features).

**Comment by mateuszzagorski** [comment]
Basic documentation has been prepared and committed here: 409d73e on i/9802 branch

**Comment by mlewand** [comment]
Here are review notes:

## Guide review

* https://github.com/ckeditor/ckeditor5/blob/409d73e2279048d07888719e3c5ee04d3276ac7d/packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md#L27 - we have no information whether it will be enabled in all builds yet. I assume it won't. So let's remove it until it's there.
* https://github.com/ckeditor/ckeditor5/blob/409d73e2279048d07888719e3c5ee04d3276ac7d/packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md#L17 - we surely will change this behavior so I'm removing this note for now.
* https://github.com/ckeditor/ckeditor5/blob/409d73e2279048d07888719e3c5ee04d3276ac7d/packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md#L44 - try to avoid obvious comments.

I fixed the above in 482b8f09ac commit. The list below remains to be fixed:

## API docs

* FindAndReplaceFormView
	* `findInputView` - "The Find input view." find should not be uppercased (this appears in few other places).
	* `findView` - unspecified type, I don't really know what is this based on "Find view config" especially that this is not a config. Missing dot.
	* `findNextButtonView` - wrong casing in "FindNext" in description (the same for next property).
	* `_createFindView`, `_createReplaceView` - "configuration" in the description, again it has nothing to do with configuration.
	* Important: This class fires several events. There is no description for that.
* FindAndReplace
	* class introduction/banner: "The find and replace UI feature and" there's unfinished sentence.
* FindAndReplaceEditing
	* `stop()` - "Stops active results from updating." AFAIR it also clears out the results. Please confirm it and update description if needed.
* FindAndReplaceUI
	* `Example Find & Replace UI that uses FindAndReplace plugin API.`
		* Class banner: "Find & Replace" uppercased while we use lower case for feature name.	Also in outside communication we refer to it "find and replace" rather than "find & replace".
		* Class banner: `FindAndReplace` should be linked.
		* Class banner: This is not an example UI but it's the default UI plugin. I wouldn't say that the main purpose is to demonstrate something. So the second sentence could be dropped. But you can add information that the plugin registers dropdown buttons and also emits events regarding user search/replace intents.
		* Important: we have no information about fired events, while it does fire few delegated events. This must be documented.

On a side note: we're missing proper docs for `FindCommand#execute()`, `ReplaceCommand#execute()` and `ReplaceAllCommand#execute()` methods - however these will change soon so let's skip it for now.

**Comment by mateuszzagorski** [comment]
I've applied all changes based on your comment here: 2151200.

*   FindAndReplaceFormView
    *   Important: This class fires several events. There is no description for that.
*   FindAndReplaceUI  
    *   Important: we have no information about fired events, while it does fire few delegated events. This must be documented.

I've added some description regarding the fired events for `FindAndReplaceFormView` and `FindAndReplaceUI` but will review this further and update this comment tomorrow.

**Comment by mateuszzagorski** [comment]
Since `i/9802` was merged to `i/9880`, current progress of docs implementation is available here: 41dee64 on `i/9880`.

Reviewed and updated descriptions for fired events for ( FindAndReplaceFormView and FindAndReplaceUI ), applied some tweaks to the descriptions/@params.

**Comment by mlewand** [comment]
LGTM checked c061fff
