### ISSUE TITLE
Find and replace results are not styled

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9885]
## 📝 Provide detailed reproduction steps (if any)

1.  Open find and replace doc sample.
2.  Search for some text that is in the text, e.g. "sit".
3.  Press next match arrow button to perform the search.

### ✔️ Expected result

1.  Search results should be highlighted with some background color. We could also force some text color (to avoid situation that the text will be invisible if matched text has font color of our highlight).
2.  Also marked results have `find-result` class. In CKE5 we pay attention to prefix the class name with the `ck-` prefix. Instead it should be `ck-find-result`. The same should apply for highlight class (`find-result_selected`).

### ❌ Actual result

![](https://user-images.githubusercontent.com/5353898/122035771-18a21100-cdd3-11eb-82c3-73bb6daab19c.png)

Search results have no styling.

Search matches have no `ck-` prefix.

### ❓ Possible solution

Currently styles are kept in tests:  [https://github.com/ckeditor/ckeditor5/blob/409d73e2279048d07888719e3c5ee04d3276ac7d/packages/ckeditor5-find-and-replace/tests/manual/findandreplace.html#L11-L12](https://github.com/ckeditor/ckeditor5/blob/409d73e2279048d07888719e3c5ee04d3276ac7d/packages/ckeditor5-find-and-replace/tests/manual/findandreplace.html#L11-L12)

Instead it should be in plugin like we do for other plugins.

## 📃 Other details

*   Browser: Any
*   OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
I’ve made changes as per the description, you can see them here: 98fece2.  
  
Search results will now have a correct `ck-` prefix.  
Changed colors as per Magda’s comment: [https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-855899255](https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-855899255)

**Comment by mlewand** [comment]
There was one thing missed, see 98fece2#r52277180

Fixed in 039b1c0
