### ISSUE TITLE
Add an option to make image related stylings use "legacy mode" that are compatible with HTML email clients

### ISSUE THREAD

**Issue by felinepc** [ckeditor/ckeditor5#9887]
## 📝 Provide a description of the new feature

I'm using CKEditor5 to compose HTML emails (templates, signatures etc). Most of the stylings can be tweaked to work with the mainstream email services/clients, but images have been proven to be very tricky.

For example, Microsoft Outlook which is widely used especially for business users, ignore most the CSS styles added by CKEditor. This includes sizes, float, etc.

It would be great if CKEditor can add an option for "legacy" image styling, which includes using `width`/`height` attribute for size, and `align` instead of `float` etc, that makes the generated HTML compatible with most modern email clients.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by zomby22** [comment]
Also text color formatting and table borders not displaying in the email. Need to find a way for ckeditor to work with email forms sent to Outlook.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. There's a similar feature request [here](https://github.com/ckeditor/ckeditor5/issues/1627). Could you confirm that [this comment](https://github.com/ckeditor/ckeditor5/issues/1627#issuecomment-703199391) is helpful and solves your use case?
