### ISSUE TITLE
[GHS] Preserve empty inline elements

### ISSUE THREAD

**Issue by Joeycz** [ckeditor/ckeditor5#9888]
## Edited

Additional scenario:

1.  Create an empty paragraph.
2.  Activate bold.
3.  Type something.
4.  Use Backspace to remove the whole word.

Expected result: The bold stays active.  
Current result: The bold is lost.

## Original post

As title said:

Is there any config can prevent removal of empty span tags automaticlly?

![image](https://user-images.githubusercontent.com/7298176/122178765-76108d80-ceb9-11eb-9732-eae98ad09ad5.png)

![image](https://user-images.githubusercontent.com/7298176/122178882-92acc580-ceb9-11eb-8b9f-e13fb6061174.png)

---

If you'd like to see this improvement implemented, add a :+1: reaction to this post.

**Comment by resonantring** [comment]
I am also having this issue with CKEditor 5 and am unsure what to change in its configuration to allow empty span tags specifically. (If we could narrow it down to only allow empty span tags with specific classes, that would be even better.)

It feels like something that would be specified as per the documentation at
 https://ckeditor.com/docs/ckeditor5/latest/api/module_html-support_generalhtmlsupport-GeneralHtmlSupportConfig.html#member-allow 

but it does not look like MatcherPattern has any way to check against the text value inside of the element, or if the element is empty. 
https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_matcher-MatcherPattern.html

**Comment by ukalpa** [comment]
Hi,
May I ask if there is any update or progress on this feature?

**Comment by michaelchadwick** [comment]
I built a CKEditor 5 plugin for adding anchor links (i.e. <a name="foo"></a>), and it needs to be able to insert empty tags, too, so if anyone figures this out, I'm all ears :)

**Comment by wimleers** [comment]
This is also affecting Drupal: https://www.drupal.org/project/drupal/issues/3337298.

This seems like a clear GHS bug? Because this is **data loss**, this is marked critical on the Drupal side 😅

**Comment by Adstokoe19** [comment]
Do you have an ETA for this fix? As @wimleers mentioned, this bug results in data loss (when migrating from v4 to v5) in Drupal, which is blocker 😢

**Comment by winddies** [comment]
@Reinmar hei, when will this problem be solved ？ i meet the same issue

**Comment by dk-massive** [comment]
Is there any progress on this issue? 

I want to plus 1 on the importance of this issue.
This is a blocker in upgrading from version 4 to 5, and it is preventing us from upgrading our Drupal platform to 10.

Thank you!

**Comment by Witoso** [comment]
@dk-massive it's in our plans but we don't have an exact ETA yet.

**Comment by Witoso** [comment]
Possible solution and research:
1. When an element is empty then convert it to the model's element. (e.g. `softBreak`)
2. Similar to SelectionAttributes downcast.
3. Generic empty element without representation but with an attribute set.
4. Inserting text node with a special behavior (something like nbsp) that is kept in the model.

**Comment by Witoso** [comment]
Several decisions have been made in terms of the scope:

- Keeping empty elements will be the default behavior of GHS (still depending on configuration if an element is allowed of course)
- Representation:
    - Model: A generic empty element with inline attributes set.
    - View: Empty element.
-  UI interactions with the empty element won’t be developed for now (although some of them may work out of the box). Support for typing in empty elements or other actions may be tricky but there's a fallback to the source code view. This will reduce our scope, as well as will give us time to gather interest.

**Comment by Witoso** [comment]
As CKEditor 4 had an API configuration of `$removeEmpty`, we must preserve empty elements without attributes.
