### ISSUE TITLE
We need a plug-in to change the color of the text

### ISSUE THREAD

**Issue by liruidong1** [ckeditor/ckeditor5#989]
## Is this a bug report or feature request? (choose one)

Feature request 

## 💻 Version of CKEditor

CKEditor 5

## ✅ Expected result
We need a plug-in to change the color of the text

**Comment by scofalik** [comment]
We already have [the highlight feature](https://docs.ckeditor.com/ckeditor5/latest/features/highlight.html). It supports both font color and background highlighting. You can also check [the GH repository](https://github.com/ckeditor/ckeditor5-highlight).

If this is what you were looking for, please close the issue. If not, please elaborate what exactly you are looking for.

**Comment by liruidong1** [comment]
Yes, you are right. Thank you
