### ISSUE TITLE
[simple-upload-adapter] Directory traversal not working on "simpleUpload.uploadUrl"

### ISSUE THREAD

**Issue by o-alquimista** [ckeditor/ckeditor5#9894]
## 📝 Provide detailed reproduction steps (if any)

Current page: `example.domain/admin/test.php`.
Target upload URL: `example.domain/api/ckeditor/upload.php`.

Configuration example:
```js
ClassicEditor.create('.example', {
  simpleUpload: {
    uploadUrl: '../api/ckeditor/upload.php'
  },
  image: {
    upload: {
      types: ['jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'svg+xml']
    }
  }
})
.catch(error => {
  console.error(error);
});
```

Path relative to document root (`/api/ckeditor/upload.php`) resolves as expected.
Path relative to current script (`api/ckeditor/upload.php`) resolves as expected.

The only thing that is not working is directory traversal (`../api/ckeditor/upload.php`). Adding multiple levels of traversal (`../../../`) doesn't change the resolved path at all.

## 📃 Other details

* Browser: Firefox 89.0.1
* OS: Arch Linux
* First affected CKEditor version: 28.0.0
* Installed CKEditor plugins: [ckeditor5-upload](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-upload) + default plugins from Classic build (CKFinder support removed)
* Built using the [online builder](https://ckeditor.com/ckeditor-5/online-builder/).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, in `uploadUrl` you need to [provide a full url that points to your backend](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html#communication-protocol), this option will not work with relative urls.

**Comment by o-alquimista** [comment]
Thanks. This is not a bug then.

**Comment by o-alquimista** [comment]
Thanks. This is not a bug then.

> Hi, in `uploadUrl` you need to [provide a full url that points to your backend](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html#communication-protocol), this option will not work with relative urls.

Oh, I should mention that it does resolve relative URLs.

If you're currently on `/admin/main.php` and you set uploadUrl to `api/upload.php`, it will resolve to `/admin/api/upload.php`.
