### ISSUE TITLE
Updating the image plugin metadata.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9895]
## Provide a description of the task

We should update the image plugin metadata. It requires changes in the `UIComponents` and possibly some other sections.

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by psmyrek** [comment]
Changes are needed not only in `UIComponents`. Currently, this file in the Image package does not have info about `ImageBlock` and `ImageInline` plugins, and also the HTML output for the `Image` plugin seems to be outdated (i.e. lack of `<span class="image-inline">`).

Because of the recent major update in the Image package, it would good to re-check all plugins there and their metadata.

**Comment by magda-chrzescian** [comment]
@psmyrek I have a problem with updating the metadata of the `ImageStyle` plugin. The logic behind registering the UI components is [conditional](https://github.com/ckeditor/ckeditor5/blob/6dbdba8cebd2c91cafc3755fb8bfedc57f0b158e/packages/ckeditor5-image/src/imagestyle/utils.js#L202-L222) - it depends on the loaded `ImageBlock`/`ImageInline` plugins. Do we have any mechanism to show this kind of dependency in the OB?

**Comment by psmyrek** [comment]
It seems that Online Builder does no show UI components from the `ImageStyle` in the main toolbar, so it should be safe to define `UIComponents` array in the metadata file without any conditions - this array in the metadata format does not support conditionals anyway.

**Comment by magda-chrzescian** [comment]
There is another issue with the Online Builder and the `ImageStyle` plugin. The default image toolbar varies depending on the build type (classic vs document). This kind of customization is currently impossible to achieve in OB, so we end up with the same image toolbar (defined in the plugin metadata) in every generated build.

Since this is not new behavior, I wouldn't consider this a blocker, but we should address this problem as soon as possible.
