### ISSUE TITLE
Implement the basicstyles

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#99]
For now bold and italic. To be implemented in ckeditor5-basicstyle(s).

**Comment by fredck** [comment]
Do we really want to have a single "basic styles" package? Wouldn't we just have headache on having to figure out what's in and what's out this bundle-package instead of simply moving forward as separate repos?

**Comment by Reinmar** [comment]
Separate repos for each button? I don't want to maintain that :D.

**Comment by fredck** [comment]
Well, right now we should be talking about 4 features... otherwise, maybe better to start rethinking this proposal and maybe call it "inlines" or something because there are dozens of features that fit here: inline HTML elements that are boolean attributes in the data model.

**Comment by fredck** [comment]
Btw... "maintain" is a big word... once "bold" is done, it's done :)

**Comment by Reinmar** [comment]
Once bold is done we'll be changing the API dozen times. I really don't want to spread those changes across all those repos.

**Comment by fredck** [comment]
> Once bold is done we'll be changing the API dozen times.

That's a bad justification for it (don't say it loud:)) but the fact that several similar features may share common modules makes this a useful approach.

**Comment by Reinmar** [comment]
Moved to ckeditor/ckeditor5-basic-style#1.
