### ISSUE TITLE
Moving `ImageResize` plugin installation snippets to the end of the guide.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9904]
We should move the information about installing the `ImageResize` plugin to the `installation` section of the feature guide.

> @oleq Why do we need to show both options here? Seems a bit like information for the `installation` section.
> 
> ![image](https://user-images.githubusercontent.com/14334820/122157898-f8726080-ce6b-11eb-80bd-fc69aa3d39c3.png)
> 
> _Originally posted by @magda-chrzescian in https://github.com/ckeditor/ckeditor5/issues/9804#issuecomment-862030116_

**Comment by godai78** [comment]
Here is a working branch: [https://github.com/ckeditor/ckeditor5/tree/ck/9904-image-install-docs](https://github.com/ckeditor/ckeditor5/tree/ck/9904-image-install-docs)

We talked it over with @magda-chrzescian a bit and I would like to suggest not moving this one sub-plugin into the general installation guide, but instead reorganize the section of the image resizing guide as follows:

![](https://user-images.githubusercontent.com/68123541/122762536-b4cd8b80-d29d-11eb-806c-1d2b0f7648cd.png)

WDYT?

**Comment by godai78** [comment]
There is also one thing we need to explain, because:

> The image resize feature is not enabled by default in any of the editor builds.

and

> The image resize feature is enabled by default in the document editor build only.

cannot both be true.

**Comment by godai78** [comment]
Also the migration guide says:

> From the 29.0.0 version, the existing [`Image`](http://fake.ckeditor.com:8888/cke5-workspace/ckeditor5/build/docs/ckeditor5/28.0.0/api/module_image_image-Image.html) plugin loads two independent plugins - [`ImageInline`](http://fake.ckeditor.com:8888/cke5-workspace/ckeditor5/build/docs/ckeditor5/28.0.0/api/module_image_imageinline-ImageInline.html) and [`ImageBlock`](http://fake.ckeditor.com:8888/cke5-workspace/ckeditor5/build/docs/ckeditor5/28.0.0/api/module_image_imageblock-ImageBlock.html), therefore both of them are included in all of the [predefined editor builds](http://fake.ckeditor.com:8888/cke5-workspace/ckeditor5/build/docs/ckeditor5/28.0.0/builds/guides/overview.html#available-builds) by default.

So now we have three contradictory pieces of information in the guides. Can we set this?

**Comment by godai78** [comment]
OK, package verification shows it's in Document Editor (decoupled editor), so I'll correct it today, too.
