### ISSUE TITLE
SassError when creating ClassicEditor via webpack

### ISSUE THREAD

**Issue by msarris** [ckeditor/ckeditor5#9905]
This is (probably) not a bug in CKEditor, but other issue types didn't really apply so I chose this.

I'm trying to add a plugin to the ClassicEditor. For this I have the following code:

```js
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';

// ...

let config = { /* ... */ };
config.plugins = [ Underline ];
let editor = ClassicEditor.create(element, config);
```

I build the code with webpack and the following loader for CSS and SCSS:

```js
  {
    test: /\.(sa|sc|c)ss$/,
    loader: [
      {
        loader: MiniCssExtractPlugin.loader,
      },
      {
        loader: 'css-loader',
        options: {
          importLoaders: 2,
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          plugins: (loader) => [
            require('postcss-import')({root: loader.resourcePath}),
            require('postcss-preset-env')({
              browsers: ['> 1%', 'last 2 versions']
            })
          ],
        }
      },
      {
        loader: 'sass-loader',
      },
    ]
  },
```

When I import the Underline plugin like this, the webpack output contains quite a few errors like the following:

```
ERROR in ./node_modules/@ckeditor/ckeditor5-ui/theme/components/button/button.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...ck-unselectable": expected "{", was ";"
        on line 11 of C:\Users\micha\Documents\app\node_modules\@ckeditor\ckeditor5-ui\theme\components\button\button.css
>>      @mixin ck-unselectable;

   --------^
```

Apparently ckeditor-ui contains .css files that contain SCSS code (which was a bit surprising to me), and it seems like the build is struggling with this.

I've been trying all day to modify my webpack file to check if something there is causing this, but without a result so far.

I also tried to integrate the CKEditorWebpackPlugin with the rules described here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html. But that doesn't seem to fix the issue.

I'm hoping someone can nudge me in the right way because I'm kind of stuck and not sure how to fix the problem.

**Comment by AlejandroBryan** [comment]
Hi guys, does anyone solve the problem out this error message?

**Comment by msarris** [comment]
> 
> 
> Hi guys, does anyone solve the problem out this error message?

Hey Alejandro,

You need to have very specific webpack rules to be able to get this working, what I have now is the following:

```
  {
    test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
    use: [
      'style-loader',
      {
        loader: 'postcss-loader',
        options: styles.getPostCssConfig({
          themeImporter: {
            themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
          },
          minify: true
        })
      },
    ]
  },
  {
    test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
    loader: 'raw-loader',
  },
```

The `styles` is imported via `let {styles} = require('@ckeditor/ckeditor5-dev-utils');`

**Comment by AlejandroBryan** [comment]
> > Hi guys, does anyone solve the problem out this error message?
> 
> Hey Alejandro,
> 
> You need to have very specific webpack rules to be able to get this working, what I have now is the following:
> 
> ```
>   {
>     test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
>     use: [
>       'style-loader',
>       {
>         loader: 'postcss-loader',
>         options: styles.getPostCssConfig({
>           themeImporter: {
>             themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
>           },
>           minify: true
>         })
>       },
>     ]
>   },
>   {
>     test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
>     loader: 'raw-loader',
>   },
> ```
> 
> The `styles` is imported via `let {styles} = require('@ckeditor/ckeditor5-dev-utils');`

thanks you a lot. i got it.

**Comment by wobo-aqib** [comment]
> > Hi guys, does anyone solve the problem out this error message?
> 
> Hey Alejandro,
> 
> You need to have very specific webpack rules to be able to get this working, what I have now is the following:
> 
> ```
>   {
>     test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
>     use: [
>       'style-loader',
>       {
>         loader: 'postcss-loader',
>         options: styles.getPostCssConfig({
>           themeImporter: {
>             themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
>           },
>           minify: true
>         })
>       },
>     ]
>   },
>   {
>     test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
>     loader: 'raw-loader',
>   },
> ```
> 
> The `styles` is imported via `let {styles} = require('@ckeditor/ckeditor5-dev-utils');`

I have done that but now i am getting this issue.

import api from "!../../../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
