### ISSUE TITLE
Code snippet not rendering properly on nightly images docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9907]
## 📝 Provide a description of requested docs changes

Go to nightly docs and scroll down a bit - https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-resizing.html#using-pixels-instead-of-percentage-width

Code snippet is not rendered correctly:
![0_nightly1](https://user-images.githubusercontent.com/34380544/122543525-2900f880-d02c-11eb-9672-48996719dcfb.png)

**Comment by godai78** [comment]
Fixed, will push everything together into `master`.
