### ISSUE TITLE
Text missing closing parenthesis on images nightly docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9908]
## 📝 Provide a description of requested docs changes

Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-styles.html#ui

Text is missing closing parenthesis:
![0_nightly2](https://user-images.githubusercontent.com/34380544/122545294-f9eb8680-d02d-11eb-98c8-d1bd86e94486.png)

**Comment by godai78** [comment]
Fixed, will push everything together into `master`.
