### ISSUE TITLE
Missing code sample in nightly image docs?

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9911]
## 📝 Provide a description of requested docs changes

Go to - https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-styles.html#presentational-styles.
After the infobox it says _"The code sample above uses predefined...."_, but there is no code sample ( the last code sample is at the end of semantical styles section ). Is it a bug or am I missing something?

**Comment by godai78** [comment]
@magda-chrzescian, can you check?

**Comment by magda-chrzescian** [comment]
I guess it's just about the editor example, which is not above, but below right now.
