### ISSUE TITLE
Missing resize options in nigthly image docs demo

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9912]
## 📝 Provide a description of requested docs changes

Go to docs and scroll down a bit - https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-styles.html#presentational-styles.
It says that the demo is configured to have three resize options with percentages. But in reality this option is missing from the toolbar - it has only resize handles:
  

https://user-images.githubusercontent.com/34380544/122551541-67e77c00-d035-11eb-90e0-f323c7aa3248.mp4

**Comment by godai78** [comment]
I can't get the toolbar to have both styles and resize options, @magda-chrzescian, can you please take this one over?
