### ISSUE TITLE
Missing whitespace in installation section on nightly image docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9913]
## 📝 Provide a description of requested docs changes

Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-installation.html.
First line:
![0_nightly4](https://user-images.githubusercontent.com/34380544/122553966-a16db680-d038-11eb-90a6-933305b5a251.png)

**Comment by FilipTokarski** [comment]
There is also a typo in the infobox at the bottom:
_If your `integrations` depends_ => _If your `integration` depends_

**Comment by godai78** [comment]
Fixed, will push everything together into `master`.
