### ISSUE TITLE
[GHS] Applying attributes to existing features - table

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#9914]
## 📝 Provide detailed reproduction steps (if any)

Due to the complex model structure of the [Table](https://ckeditor.com/docs/ckeditor5/latest/features/table.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Let's make a research to find out what should be covered.
