### ISSUE TITLE
Missing links in migration guide on nightly docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9915]
## 📝 Provide a description of requested docs changes

Go to - https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/migration/migration-to-29.html

Missing links:
![0_nightly5](https://user-images.githubusercontent.com/34380544/122554864-ca427b80-d039-11eb-94af-d18c7ddf3693.png)

**Comment by FilipTokarski** [comment]
Also below in https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/migration/migration-to-29.html#inserting-images

**Comment by godai78** [comment]
@magda-chrzescian - can you take this one over?
