### ISSUE TITLE
[GHS] Applying attributes to existing features - media embed

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#9918]
## 📝 Provide detailed reproduction steps (if any)

Due to the complex model structure of the [Media Embed](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
It seems that media embed allows defining different outputs (e.g. coming from external providers like iframely). Basically, we have two output types - semantic and non-semantic. 

TODO: Check how the model looks like.

Let's start with small research.

**Comment by Reinmar** [comment]
Scope after the research:

* Support the configurable oembed element name.
* Tests.
* API docs.
