### ISSUE TITLE
Delete a table that was recently added but both versions overlaps

### ISSUE THREAD

**Issue by JoaovitorFerreira** [ckeditor/ckeditor5#9921]
## 📝 Provide detailed reproduction steps (if any)
Hello,
Im facing an issue using track change that, when I add an object, like a table, then deletes him without accept the change it is not overlaping the "addition" ,as shown in the following video:

https://drive.google.com/file/d/1msCSj6a-YSe5ONZKct6PohILQtue4k6b/view

### ✔️ Expected result

I was hoping that, when I delete an object, the red color appears.

### ❌ Actual result

The actual result is, when I delete a new object, the color overlaps the actual one, for example, if I delete an object, the green color stays .

## 📃 Other details

* Browser: microsoft edge, google chrome
* OS: windows 10
* First affected CKEditor version: 5
* Installed CKEditor plugins: 	Essentials, UploadAdapter,Autoformat, Bold,Italic, Underline,BlockQuote, CKFinder, EasyImage, Heading,Image, mageCaption, ImageStyle, ImageToolbar, ImageUpload, Indent,Link, List, MediaEmbed, Paragraph, PasteFromOffice, Table, TableToolbar, Base64UploadAdapter, ImageResize, Alignment, TextTransformation, Comments,	TrackChanges

Thank you all for the attention.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
I'm closing this issue, as the conversation has moved to our support channel.
