### ISSUE TITLE
Update Placeholder after initialization

### ISSUE THREAD

**Issue by mugnap** [ckeditor/ckeditor5#9925]
Hello,

I'd like to have the ability, for an Inline editor, to update the placeholder at runtime (i.e. after the editor has been created). Is there any way to do that? Currently the placeholder is set in the configuration options, so I can't change it later. I found this thread https://github.com/ckeditor/ckeditor5/issues/7383 but I think nothing has changed yet.
Thanks!

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by urbanspr1nter** [comment]
I'd really like to know if there's any ability to do this yet.. Is there an easy way in v37+?

@Witoso something probably worth thinking about. CKE5 can be used for a variety of scenarios such as chat apps. For example, in Slack, the placeholder will change depending on which channel or chat you are in. 

<img width="225" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1388415/e80509fb-f8a4-45fd-a56b-1b9324d9da2d">

<img width="281" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1388415/2c68732b-e7ea-4869-8865-8702c78a47d9">

Having a convenient way to update the root editable placeholder would be really nice..

**Comment by Witoso** [comment]
@urbanspr1nter thanks for bringing this to my attention! I haven't found an easy way to do that, unfortunately :/ I will keep it in my mind in our future API discussion.
