### ISSUE TITLE
Implement more reliable API docs search

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9926]
## 📝 Provide a description of the improvement

From time to time we're not getting correct results from our search provider (Algolia). It just stops working randomly, then we reach out to them it works for some time and again the same thing.

I thought that I have reported this issue in the past but I couldn't find anything but I was mentioning that it's broken multiple times in the past.

Honestly, if we would only have a dumb match fallback that would be useful in case when Algolia is down. Better yet we could check for alternatives that are stable and will work with no issues.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Today I'm having an issue after doing following steps:

1.  Open [https://ckeditor.com/docs/ckeditor5/28.0.0/api/index.html](https://ckeditor.com/docs/ckeditor5/28.0.0/api/index.html)
2.  Focus search bar.
3.  Type "Command".

### Expected

Getting relevant results.

### Actual

Search fails to show the dropdown. Following exceptions are thrown:

```
docsearch.min.js:2 Uncaught (in promise) AlgoliaSearchError {name: "AlgoliaSearchError", message: "Index ckeditor_docs_site does not exist", debugData: Array(1), statusCode: 404, stack: "AlgoliaSearchError: Index ckeditor_docs_site does …livr.net/docsearch.js/2/docsearch.min.js:2:81909)"}
```

![](https://user-images.githubusercontent.com/5353898/122689233-6da1b500-d221-11eb-9f0c-9c4e4fe95e4e.png)

**Comment by godai78** [comment]
The current configuration of Algolia introduced a great improvement of the search results and overall search experience globally, including API docs as well.

The type of error mentioned seems to have been eradicated from the site.

Hence the issue appears no longer valid.

![Screenshot 2022-07-28 at 15.07.35.png](https://images.zenhubusercontent.com/5f8fed35103c51288064a970/68bee584-ce16-4cba-95f4-3c61c8227c64)
