### ISSUE TITLE
Stylelint verification issues

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#9928]
Currently, there are some issues in the `findandreplaceform.css` file being highlighted by stylelint, for example:

```
51:2 ✖ Expected selector ".ck .ck-find-and-replace-form .ck-replace-form__wrapper .ck-button"
to come before selector ".ck .ck-find-and-replace-form .ck-find-form__wrapper .ck-button:hover"
no-descending-specificity
```

This needs to be reviewed and cleaned up.

**Comment by mlewand** [comment]
I temporarily disabled this rule for the file in d903bc5 to make CI pass.

**Comment by mateuszzagorski** [comment]
I've applied changes to the code, (PR here: #9988) and stylelint is not returning any issues anymore.

**Comment by oleq** [comment]
FYI: The mentioned PR will no longer be relevant after the UI/UX epic #10241 is solved because the structure of the UI will be different (and all CSS). So this will need to wait.
