### ISSUE TITLE
Link can not select

### ISSUE THREAD

**Issue by Joeycz** [ckeditor/ckeditor5#9929]
There is a link，if I select from edge of it，just caret move，but can not make a selection.

![屏幕录制2021-06-21-14 45 32](https://user-images.githubusercontent.com/7298176/122719430-bf3d5480-d2a0-11eb-841b-4dceddf37325.gif)

os: mac os 11.2.1
chrome: 91.0.4472.106 (x86_64)
demo: https://ckeditor.com/docs/ckeditor5/latest/features/link.html

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this issue and [it's already tracked here](https://github.com/ckeditor/ckeditor5/issues/7936).
I'll close this ticket as a duplicate.

**Comment by pomek** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/8814.
