### ISSUE TITLE
Action when there are no more search results available.

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#9934]
## 📝 Provide a description of the new feature

What should happen if there are no more search results (e.g. you replaced the last occurrence or your search query does not match)?

**Comment by magda-chrzescian** [comment]
Do we need something more than that?
![image](https://user-images.githubusercontent.com/14334820/122757899-71bce980-d298-11eb-9ae8-bfb5193001f5.png)

**Comment by mlewand** [comment]
Blocked by our ux followups call that is scheduled to 13th of July.

**Comment by mlewand** [comment]
Resolved by #10047.
