### ISSUE TITLE
Should we allow user to replace/replaceAll before actually searching?

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#9935]
## 📝 Provide a description of the new feature

Currently, if you type into the find and replace input before actually clicking the 'find' button to search for the typed query you can replace everything/first occurrence of the given query automatically.

![](https://user-images.githubusercontent.com/11699569/122753218-36b7b780-d292-11eb-840e-18d1fbdced45.png)

I'd think we should find a way to force users to at least see all of the results (including the first one selected) before allowing anyone to blindly replace chunks of text without even knowing what and where.

One idea is to:  
Force the user to click 2 times on replace/replaceAll button respectively, before allowing to take any action (adding highlight to the results after the first click).

**Comment by mlewand** [comment]
For now we'll change the form to be disabled by default (replace buttons) as long as there are no find results. We'll revisit this issue later in the iteration.

**Comment by mlewand** [comment]
Blocked by our ux followups call that is scheduled to 13th of July.

**Comment by mlewand** [comment]
There are some UI/UX works focused on overall find and replace experience. I'm closing this issue as it should be resolved there.
