### ISSUE TITLE
not render react component with decoupled-document

### ISSUE THREAD

**Issue by foadabdollahi** [ckeditor/ckeditor5#9937]
## i wanna use ckeditor decoupled-document in react 

```
 
import React from 'react' 
import {CKEditor } from "@ckeditor/ckeditor5-react";
import  DecoupledEditor  from "@ckeditor/ckeditor5-build-decoupled-document";
```
 and 

```
  <CKEditor
            required
            editor={DecoupledEditor}
            
            data={value ?? ""}
            onChange={(event, editor) => {
                const data = editor.getData()
                onChange(data)
            }}
            {...props}
        />
```
npm package:
  
    "@ckeditor/ckeditor5-build-classic": "^28.0.0",
    "@ckeditor/ckeditor5-build-decoupled-document": "^28.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",

* Browser: chrome & Firefox
* OS: windows
* First affected CKEditor version: 5
* Installed CKEditor plugins: 28.0.0
 
 
 Result:
![image](https://user-images.githubusercontent.com/13816403/122762009-1e579500-d2b2-11eb-9210-5ef9df2ebae5.png)

**Comment by FilipTokarski** [comment]
Hi, I assume that you followed [documentation on React integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)? When using decoupled editor, you also need to [adjust the markup for the toolbar](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-document-editor-build).
