### ISSUE TITLE
Docs: broken demo consoles on 'getting and saving data' page

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9938]
## 📝 Provide a description of requested docs changes

1. Go to - https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html
2. Scroll down to the demos
3. The fake consoles are broken and don't display the data

It's caused by the recent change in code highlighter. The fix should be easy and quick.

**Comment by Mgsy** [comment]
Closed by #9939.
