### ISSUE TITLE
Format loss after copy/paste

### ISSUE THREAD

**Issue by mark-bragg** [ckeditor/ckeditor5#994]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor5 classic 1.0.0-beta.3

## 📋 Steps to reproduce

1. type characters into some text editor (I used Notes on my Mac) with some indentations, bolded and underlined text, and regular text
2. copy paste the text into CKEditor
3. underline is lost and indentations are lost

## ✅ Expected result
formatting should stay the same after pasting from another editor

## ❎ Actual result
some formatting is lost

## 📃 Other details that might be useful
![text in notes](https://user-images.githubusercontent.com/15349627/39160958-2397a4ba-4723-11e8-917d-ce8301673d21.png)
![text pasted from notes into ckeditor](https://user-images.githubusercontent.com/15349627/39160959-23e14444-4723-11e8-914c-86b452618de9.png)

**Comment by Reinmar** [comment]
I created https://github.com/ckeditor/ckeditor5/issues/1008 for the issue with underline.

The lack of indent plugin would need to be tracked separately but so far no one reported it.
