### ISSUE TITLE
Missing plugins and outdated HTML output in `ckeditor5-metadata.json` in the Image package

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#9943]
## Provide a description of the task

The `ckeditor5-metadata.json`, that is available inside every package, should contain all plugins exported from a package with an up-to-date plugins data, i.e. their HTML output.

Currently, this file in the Image package does not have info about `ImageBlock` and `ImageInline` plugins, and also the HTML output for the `Image` plugin seems to be outdated (i.e. lack of `<span class="image-inline">`).

Because of the recent major update in the Image package, it would good to re-check all plugins there and their metadata.

**Comment by ma2ciek** [comment]
Isn't it a duplicate of #9895?

**Comment by psmyrek** [comment]
Yes, this is a duplicate, I have not found it earlier.
