### ISSUE TITLE
Trouble with CK5Editor Plugins

### ISSUE THREAD

**Issue by jacksonkr** [ckeditor/ckeditor5#9949]
I'm using react ck5editor via a wysiwyg plugin for strapi cms and I'm trying to get new toolbar item to appear with the help of plugins. [Here is the strapi wysiwyg article I used](https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi) to install cke5 into strapi.

package.json
```
...
    "@ckeditor/ckeditor5-build-classic": "^28.0.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "@ckeditor/ckeditor5-basic-styles": "^28.0.0",
...
```

/plugins/wysiwyg/admin/src/components/CKEditor/index.js
```
...
import React from 'react';
import PropTypes from 'prop-types';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import styled from 'styled-components';
import HtmlEmbed from '@ckeditor/ckeditor5-html-embed/src/htmlembed.js';
...
const configuration = {
  toolbar: [
    'heading',
    '|',
    'bold',
    'italic',
    'underline',
    'strikethrough',
    'embedHtml'
]}
...
const Editor = ({ onChange, name, value }) => {
  return (
    <Wrapper>
      <CKEditor
        editor={ClassicEditor}
        config={configuration}
        data={value}
        onReady={editor => editor.setData(value)}
        onChange={(event, editor) => {
          const data = editor.getData();
          onChange({ target: { name, value: data } });
        }}
      />
    </Wrapper>
  );
};
```

### ✔️ Expected result
I expected plugins to become available on the editor, per this issue I expected to see the html embed one.

### ❌ Actual result

Through all my experimentation the page either loads with a default toolbar layout, loads with no toolbar, or is blank with a warning about duplicate plugins.

### ❓ Possible solution

I must be adding the plugins wrong, is my best guess.

## 📃 Other details

* Browser: Brave 1.26.67 / Chrome
* OS: Windows 10
* First affected CKEditor version: 28.0.0 (the only version I've ever installed)
* Installed CKEditor plugins: none I guess (because they don't work)

**Comment by FilipTokarski** [comment]
Hi, as it comes to adding plugins - you're confusing a ready-made editor build with editor source class. Builds ( in this case `ckeditor5-build-classic` ) already have a specified set of plugins and you cannot extend it by just importing another ones ( which is described in the [duplicated modules error message](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) ). You can also read more about it in [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) section.  
So in this case, to customise the editor, you would need to [build it from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source) or just use [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) to generate your own custom editor build.

**Comment by jacksonkr** [comment]
@FilipTokarski I realized this morning that I was using the `@ckeditor/ckeditor5-build-classic` so today I switched up my project to use the src/classicEditor and now I'm getting a new issue

```
react_devtools_backend.js:2560 TypeError: Cannot read property 'getAttribute' of null
    at o._updateXMLContent (main.165ff31e.chunk.js:1)
    at o.render (main.165ff31e.chunk.js:1)
    at o.<anonymous> (main.165ff31e.chunk.js:1)
    at o.fire (main.165ff31e.chunk.js:1)
    at o.<computed> [as render] (main.165ff31e.chunk.js:1)
    at a._renderViewIntoCollectionParent (main.165ff31e.chunk.js:1)
    at a.<anonymous> (main.165ff31e.chunk.js:1)
    at a.fire (main.165ff31e.chunk.js:1)
    at addMany (main.165ff31e.chunk.js:1)
    at add (main.165ff31e.chunk.js:1) {phase: "initialization", willEditorRestart: false}
```

This error only shows up once I add plugins via `CustomEditor.builtinPlugins`


Full code:

```
import React from 'react';
import PropTypes from 'prop-types';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import styled from 'styled-components';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';

class CustomEditor extends ClassicEditorBase { }

CustomEditor.builtinPlugins = [
  Essentials,
  Bold,
];

CustomEditor.defaultConfig = {
  toolbar: {
      items: [
          'heading',
          '|',
          'alignment',                                                 // <--- ADDED
          'bold',
          'italic',
          'link',
          'bulletedList',
          'numberedList',
          'uploadImage',
          'blockQuote',
          'undo',
          'redo'
      ]
  },
  image: {
      toolbar: [
          'imageStyle:full',
          'imageStyle:side',
          '|',
          'imageTextAlternative'
      ]
  },
  language: 'en'
};

const Wrapper = styled.div`
  .ck-editor__main {
    min-height: 200px;
    > div {
      min-height: 200px;
    }
  }
`;

const configuration = {
  toolbar: [
    'heading', '|',
    'alignment', '|',
    'bold', 'italic', 'strikethrough', 'underline', 'subscript', 'superscript', '|',
    'link', '|',
    'bulletedList', 'numberedList', 'todoList',
    'fontfamily', 'fontsize', 'fontColor', 'fontBackgroundColor', '|',
    'code', 'codeBlock', '|',
    'insertTable', '|',
    'outdent', 'indent', '|',
    'uploadImage', 'blockQuote', '|',
    'undo', 'redo'
  ]
};

const Editor = ({ onChange, name, value }) => {
  return (
    <Wrapper>
      <CKEditor
        editor={CustomEditor}
        data={value}
        onReady={editor => editor.setData(value)}
        onChange={(event, editor) => {
          const data = editor.getData();
          onChange({ target: { name, value: data } });
        }}
      />
    </Wrapper>
  );
};

Editor.propTypes = {
  onChange: PropTypes.func.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
};

export default Editor;
```

**Comment by jacksonkr** [comment]
While this wasn't exactly a nightmare, it was still a pretty bad dream.

After a grueling amount research, too much really, [here's the answer](https://stackoverflow.com/a/68187615/332578)
