### ISSUE TITLE
[GHS] Review the documentation for GHS

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9951]
## 📝 Provide a description of requested docs changes

Recently, we've introduced the documentation for General HTML Support, which has been merged to the feature branch (`ci/656-html-support`). The main goal was to show the feature, mention current limitations and explain what it is, how to configure and use it. 

It would be great if we could have a guide review from a person who was not involved in the project to see whether everything is explained properly.

@magda-chrzescian @FilipTokarski could I ask you to take a look at this guide and share your thoughts?

**Comment by FilipTokarski** [comment]
**extend** => **extent**
  
![ghs1](https://user-images.githubusercontent.com/34380544/123405491-2cefc600-d5aa-11eb-8b86-71c3cf3de3cb.png)

**Comment by FilipTokarski** [comment]
The guide lacks a snippet with npm install, something like in other feature pages:

> To add this feature to your editor install the @ckeditor/ckeditor5-html-support package:
> `npm install --save @ckeditor/ckeditor5-html-support`

**Comment by FilipTokarski** [comment]
![ghs2](https://user-images.githubusercontent.com/34380544/123415893-2c5d2c80-d5b6-11eb-8b30-20a5b6565c56.png)
   
This statement feels weird when you read it for the first time. Can we remove it or rephrase it somehow?

**Comment by Mgsy** [comment]
Additionally, we should add information that we encourage to report issues and point to the main repository.

**Comment by Mgsy** [comment]
Closed by #9963.
