### ISSUE TITLE
Move vertical scrollbar at the top

### ISSUE THREAD

**Issue by mugnap** [ckeditor/ckeditor5#9953]
Hello,

When I use SetData() and the editor contains a lot of text, the vertical scrollbar moves to the bottom. This is by default.
Is there a way to move it back at the top, so that the user can start reading text in the editor without first scrolling to the top?
Thanks.

**Comment by Mgsy** [comment]
Hi, thanks for the report. I'm not able to reproduce your issue, however, you can try to listen to the [set event](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_controller_datacontroller-DataController.html#event-set), [change the selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-setSelection) to the beginning of the document and [scroll to the selection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_view-View.html#function-scrollToTheSelection).
