### ISSUE TITLE
UI/UX improvements of the find and replace feature.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9959]
Since I won't be able to review the functionality on Monday, I'll check it now, so just ignore my comments in case it points at some already known issue.

1. The visual appearance of the split button. It has probably unnecessary class `ck-button_with-text`.
How it looks like:
![image](https://user-images.githubusercontent.com/14334820/123451655-0186ce80-d5de-11eb-8343-b13b52070809.png)

How it should look like:
![image](https://user-images.githubusercontent.com/14334820/123449079-a0f69200-d5db-11eb-9867-2570dea8c680.png)

2. The text in buttons is misplaced vertically (too high). It probably would be better to set the fixed height for the button and align the text vertically with the `line height` = button height or with the flex `align-items` property.
![image](https://user-images.githubusercontent.com/14334820/123449885-60e3df00-d5dc-11eb-9f61-3dcdda1ea622.png)

3. Checkbox labels should be prepared for longer texts. It should have the `max-size`, `overflow` and `text-overflow` properties, or optionally should wrap the text if the max-width is exceeded.
![image](https://user-images.githubusercontent.com/14334820/123450495-16af2d80-d5dd-11eb-94af-d1231658ae47.png)

4. If we wanted to stay with the arrows and skip the `find` button in the MVP, the second arrow should point to the right, as it's a symbol for something like "run"/"play", an arrow pointing down is a bit unclear about the purpose. The first arrow should be rotated accordingly.

5. The tooltip should not be capitalized. It can be set on the buttons only using the `text-transform: uppercase` CSS rule.

6. The arrows are a bit too big (scale set 0.9 looks fine IMO, but @oleq may have some concerns about the sharpness of the icons(?)). They are also misplaced vertically, but it's hard to define the exact values they should be moved, as I'm not sure if we are going to change their rotation (as mentioned in 4). Again, please consult it with @oleq if needed.

7. Let's keep the input and checkbox border colors consistent (the lighter gray).
![image](https://user-images.githubusercontent.com/14334820/123453320-b1107080-d5df-11eb-9852-23cedf928f38.png)

8. Clicking the label should result in checking/unchecking. Moreover, the cursor should be set to the pointer when hovering over the checkbox/label.

9. Let's make the margin top of this pretty selector `.ck .ck-find-and-replace-form .ck-find-form__wrapper.ck-responsive-form .ck-find-checkboxes .ck-find-checkboxes__box:first-child` equal to `ck-spacing-large` instead of the `ck-spacing-unit`. (BTW, to set the size to `ck-spacing-unit`, the `ck-spacing-standard` variable should be used).

**Comment by mateuszzagorski** [comment]
I've had a short conversation with @oleq today regarding UI/UX for the find-and-replace feature.  
  
We agreed that for now, checkbox styling is something that we will omit and focus on it later on as a follow-up.
