### ISSUE TITLE
[GHS] Support for empty elements

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#9960]
## 📝 Provide a description of the improvement

Some HTML elements can be empty and the editor is not able to easily preserve them. GHS should allow preserving empty elements including their original location.

Examples of empty elements:
* img (currently represented as object)
* hr
* area
* br
* command
* map
* wbr
* colgroup -> col
* basefont (deprecated in modern browsers)
* keygen (deprecated in modern browsers)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Closing in favor of #9888 (has the exact same number of upvotes).
