### ISSUE TITLE
ckeditor 5 heading TitlePlugin 

### ISSUE THREAD

**Issue by super-cj** [ckeditor/ckeditor5#9961]
## 📝 Provide detailed reproduction steps (if any)

The first time I used ckeditor5, now I encountered a problem. The cursor is in the title, but the toolbar button is isEnabled = false
![20210626203620](https://user-images.githubusercontent.com/20263914/123513210-6c0f3b80-d6be-11eb-815d-a9a04b7fe446.png)

How to solve this problem      thank you

                                      

### ✔️ Expected result

I hope the functions in toolbar can also be used in the title

**Comment by Mgsy** [comment]
Hi! Thanks for the report. The toolbar buttons are disabled because your selection is inside the title, which allows only plain text. Changing the selection to the body will enable buttons. If you'd like to style your title, please use CSS.

**Comment by super-cj** [comment]
thank you
