### ISSUE TITLE
Implementing an inline widget document - code build returns error

### ISSUE THREAD

**Issue by esezer** [ckeditor/ckeditor5#9962]
## "Implementing an inline widget document" full code returns error

Trying to build with the exactly same code returns following error. I think it is related to webpack config for style loaders. It could be out of date and needs to be fixed.

      `ERROR in ./placeholder/theme/placeholder.css 1:0
      Module parse failed: Unexpected token (1:0)
      You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
      > .placeholder {
      |   background: #ffff00;
      |   padding: 4px 2px;
       @ ./placeholder/placeholderediting.js 12:0-33
       @ ./placeholder/placeholder.js
       @ ./app.js
      error Command failed with exit code 2.`

**Comment by Mgsy** [comment]
Hi! Thanks for the report. We're aware of this issue and, unfortunately, this is a part of some bigger task. It's described here with a possible solution - #8651. I'm closing it as a duplicate.
