### ISSUE TITLE
Direct edits in the Features’ HTML output docs page will be lost

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#9965]
## 📝 Provide a description of requested docs changes

There are multiple changes in the "Features’ HTML output" docs page (`docs/builds/guides/integration/features-html-output-overview.md`) that were made directly in this Markdown file. All direct edits below the `<!-- features-html-output-marker -->` line will be lost, because the content here is generated by a script `yarn docs:features-html-output`, which takes all `ckeditor5-metadata.json` files from all packages and compiles the HTML output.

To fix this issue, all changes that were made directly below the `<!-- features-html-output-marker -->` line, should be moved to the appropriate `ckeditor5-metadata.json` files and then the  `yarn docs:features-html-output` script should be called to re-create the expected content.

**Comment by godai78** [comment]
Can you link the commit to list the changes? I'll try covering it today.

**Comment by psmyrek** [comment]
I found a few commits that introduced some changes, which are not reflected in the `ckeditor5-metadata.json` files:

- https://github.com/ckeditor/ckeditor5/commit/0a1d68cb4381ebedc7e80b74313d7060652e1ec5
- https://github.com/ckeditor/ckeditor5/commit/e648176beff5e044556ab4c1cc19f5e23b102334
- https://github.com/ckeditor/ckeditor5/commit/4a3b936afced4cf42fae26b7a26fd35713047a06
