### ISSUE TITLE
Find and replace collaboration integration

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9969]
Feature was not tested with collaboration. Although I'm pretty sure it works with comments it won't integrate properly with Track Changes.

I expect it will attempt to replace text in removed suggestion which I believe it should not.

**Comment by LukaszGudel** [comment]
### Steps:
1. Add Find&Replace plugin to the editor with Track Changes plugin.
2. Turn on Track Changes.
3. Try to find anything.

### Result:
Find and Replace is not working when Track Changes is turned on.

https://user-images.githubusercontent.com/58658048/123625426-0763f600-d810-11eb-9283-e657197da087.mp4

**Comment by LukaszGudel** [comment]
1. Add replace or remove text suggestion.
2. Find some text that was suggested to be removed.
3. Replace it with some other text.

### Result:
Text in remove suggestion can be found and it also can be replaced. Remove suggestion is lost on text replace.

https://user-images.githubusercontent.com/58658048/123630595-0209aa00-d816-11eb-8738-f6dfdb1e3546.mp4

**Comment by LukaszGudel** [comment]
### Steps:
1. Add replace or remove text suggestion.
2. Find some text that was suggested to be removed.
3. Replace it with some other text.
4. Undo.

### Result:
The yellow highlight stays on the remove text suggestion, even when searching other words.

https://user-images.githubusercontent.com/58658048/123630873-59a81580-d816-11eb-9d26-aa1dff77befa.mp4

**Comment by LukaszGudel** [comment]
### Steps:
1. Find few words in a paragraph as user A.
2. Remove this paragraph as user B.
3. Replace All as user A.
4. Undo as user B.

### Result:
Paragraphs are split. Both words are visible.

https://user-images.githubusercontent.com/58658048/123637895-d0e1a780-d81e-11eb-98c8-fe23bb3ea72f.mp4

**Comment by mlewand** [comment]
Referring to https://github.com/ckeditor/ckeditor5/issues/9969#issuecomment-869611881

I'm wondering what's the optimal solution in terms of UX for find and replace.

I think it's out of discussion that inserted suggestions should be findable and replacable. When replaced, the text should remain a insert suggestion.

The question is how to act on a removed text suggestion.

## Disallowing to find text in removal suggestion

* Cons
	* You can't find the text you're looking for in _particular cases_.
* Pros
	* Simpler code implementation.
	* Gdocs seems to be doing this way.

## Allowing to find text in removal suggestion

* Cons
	* Replace button - what to do if you navigate to a text match that is in a removed suggestion? Replace doesn't make sense because you can't do it. So it should be disabled.
		* Replace all still kind-of makes sense, though you'll end up with matches after performing replace all which might be confusing.
	* Slightly more complicated code.
* Pros
	* End user can truly find all occurrences of a given string in the document.

## Opinions?

I'd like to hear from others what way we should go. Given the points above I'd prefer going the first one, so disallowing to find text in removal suggestion.

From the end user perspective I'd prefer second option **only if** it didn't have the confusion with replace buttons when you're matching text in removal suggestion.

**Comment by mlewand** [comment]
Blocked by our ux followups call that is scheduled to 13th of July.

**Comment by mlewand** [comment]
Blocked by our ux followups call that is scheduled to 13th of July.

**Comment by godai78** [comment]
I believe - even though the logic behind this would be probably more work to implement - the find should cover finding it, but no replace for such a case.

**Comment by niegowski** [comment]
I would go with the iterative approach and first implement the simpler solution and go with the more complex one only if there are community requests for that.

**Comment by LukaszGudel** [comment]
All issues mentioned in this ticket has been extracted to as new issues
