### ISSUE TITLE
Get editor content as plain text

### ISSUE THREAD

**Issue by balszab** [ckeditor/ckeditor5#997]
## Is this a bug report or feature request? (choose one)

🆕 Feature request 

## 💻 Version of CKEditor

ckeditor5-build-classic-1.0.0-beta.3

## Request

As a developer I would like to have the possibility to get the editor content as plain text (without formatting) like in CKEditor4.

CKEditor4 API documentation:
https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editable.html#method-getText

**Comment by szymonkups** [comment]
Hello @balszab,
You try using [viewToPlainText](https://github.com/ckeditor/ckeditor5-clipboard/blob/master/src/utils/viewtoplaintext.js) utility method.

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import ArticlePluginSet from '../_utils/articlepluginset';
import viewToPlainText from '@ckeditor/ckeditor5-clipboard/src/utils/viewtoplaintext';

ClassicEditor
	.create( ... )
	.then( editor => {
		console.log( viewToPlainText( editor.editing.view.document.getRoot() ) );
	} );
```
