### ISSUE TITLE
[GHS] General HTML Support feature

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#9970]
## 📝 Provide a description of the new feature

The General HTML Support ("GHS") feature will allow developers to easily enable HTML features that are not explicitly supported by any other dedicated CKEditor 5 plugins.

Some examples of HTML features that should be easily enabled using General HTML Support include:

* The `<section>`, `<article>`, and `<div>` elements.
* The `<audio>`, `<video>`, and `<iframe>` elements.
* The `<span>` and `<cite>` elements.
* Some of the attributes on existing dedicated CKEditor 5 features:
	* `data-*` and `id` attributes on e.g. `<p>` and `<h1-h6>`,
	* `style` and `classes` on e.g. `<strong>` and `<a>`.

The enabled HTML features could be loaded (e.g. via `editor.setData()`), pasted, output (e.g. via `editor.getData()`), and will be visible in the editing area. Such content could also be edited in the editor, although, to a limited extend.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by ashishforgrz** [comment]
Can anyone give me an example of how can i use custom classes in html tags while using ckeditor 5 with react npm build. I don't know where i am stuck. Simple code example of allowing General HTML Support with react npm build would be helpfull.
