### ISSUE TITLE
Add metadata info for find and replace package

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9971]
We need to add missing `ckeditor5-metadata.json` file.

**Comment by mlewand** [comment]
Good example would be word count plugin.

**Comment by mlewand** [comment]
After it's ready please pass it to review to @ma2ciek.

**Comment by godai78** [comment]
Pushed to i/9802, @ma2ciek - proceed at will.

**Comment by ma2ciek** [comment]
I pushed a fix for the typo. But as I see the `uiComponents` was not added. And I'm pretty sure that this component exposes some toolbar buttons. The schema is described in [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/package-metadata.html#data-format-for-plugin-metadata](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/package-metadata.html#data-format-for-plugin-metadata) but you can also ask me for help.

**Comment by godai78** [comment]
Made a push, please check.

**Comment by ma2ciek** [comment]
It looks fine to me now :ok\_hand:

**Comment by ma2ciek** [comment]
I changed the type from `Dropdown` to `SplitButton` as it looks more like the second one:

![](https://user-images.githubusercontent.com/2768047/123782498-433ba180-d88a-11eb-8481-db18af26cb76.png)

**Comment by mlewand** [comment]
Ok so we're good with plugin metadata.

**Comment by ma2ciek** [comment]
Remember to run `yarn run docs:features-html-output` before the release.
