### ISSUE TITLE
custom popup box select image insert ckeditor5 problem 

### ISSUE THREAD

**Issue by super-cj** [ckeditor/ckeditor5#9973]
There is no image settings widget, view generated HTML no problem, but did not appear  ，
I don't know where there is no setting 

![QQ截图20210629165940](https://user-images.githubusercontent.com/20263914/123770947-42902300-d8fd-11eb-9e0d-953e42c13622.png)

![QQ截图20210629170017](https://user-images.githubusercontent.com/20263914/123770960-43c15000-d8fd-11eb-84f0-cdff7a620362.png)

![QQ截图20210629170046](https://user-images.githubusercontent.com/20263914/123771732-e11c8400-d8fd-11eb-9ae2-aa6dc02e0480.png)

Hope to get help,  thankyou

**Comment by FilipTokarski** [comment]
Hi, if I understood the problem correctly, the image toolbar is missing when you use [CKFinder](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html)? I checked it and it worked for me, so we'll need precise step-by-step description on how to reproduce the issue.
