### ISSUE TITLE
Find and replace feature followup regarding checkboxview and used icons.

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#9980]
## 📝 Provide a description of the improvement

Followup from #9959.  
  
Right now there is no easy way for users to style checkboxes. For example, changing checkbox behavior on `:checked` pseudo-class or altering colors for it would require a lot of additional effort. Checkboxview class should be updated in a way that will allow changes like that without the need to alter the code too much.

Additionally, icons used in the find-and-replace feature are not compatible with icons used for pagination. This should be reviewed and updated to keep everything consistent. 

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
This will no longer be a problem because of #10229.
