### ISSUE TITLE
Invalid dependencies in ckeditor5-theme-lark - all deps should be dev deps

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9998]
## Provide a description of the task

In theme lark:

[https://github.com/ckeditor/ckeditor5/blob/d903bc52c96a2726e4b130dafe7d10ba49ee0851/packages/ckeditor5-theme-lark/package.json#L12-L37](https://github.com/ckeditor/ckeditor5/blob/d903bc52c96a2726e4b130dafe7d10ba49ee0851/packages/ckeditor5-theme-lark/package.json#L12-L37)

We have all the deps marked as regular dependencies, but we use them only in **manual test** - so that's purely dev dep. Not sure if that's `true` for all the packages, but certainly most of them, like `ckeditor5-find-and-replace`.

**Comment by przemyslaw-zan** [comment]
Seems like these files are in fact in use in `ckeditor5-theme-lark/theme/`

![](https://user-images.githubusercontent.com/69513154/125416075-46b40374-5228-446b-9ae8-3466f339a5e3.png)

**Comment by mlewand** [comment]
The question is why does our validator says that? Let's take a single example `@ckeditor/ckeditor5-media-embed` package.

I made a `ctrl+shif+f` search in theme package and the only match is in this line:

[https://github.com/ckeditor/ckeditor5/blob/cf9cac01cd89908322faf022fee09f2718dd4275/packages/ckeditor5-theme-lark/tests/manual/iconset.js#L53](https://github.com/ckeditor/ckeditor5/blob/cf9cac01cd89908322faf022fee09f2718dd4275/packages/ckeditor5-theme-lark/tests/manual/iconset.js#L53)

That's a manual test so it's a dev dep. Is there any other media embed usage in there?

**Comment by przemyslaw-zan** [comment]
```css
.ck.ck-code-block-dropdown .ck-dropdown__panel {
```

Perhaps references in css files cause that?

**Comment by psmyrek** [comment]
Currently, the decision if given package should belong to `dependencies` or `devDependencies` depends on this function:

```js
function isDevDependency( absolutePaths ) {
    return !absolutePaths.some( absolutePath => absolutePath.match( /src|theme/ ) );
}
```

A package is a `devDependency` if it is not used in the source and theme.

The bug here is because the `absolutePath` for `ckeditor5-theme-lark` package already contains the `theme` word (from the package name), so all packages imported in this package will always be classified as `dependencies`.

**Comment by pomek** [comment]
Updating the RegExp to check only directories would resolve the problem. Keep in mind that the RegExp should work on both environments: Unix-like (`/`) and Windows (`\`).

**Comment by pomek** [comment]
Fix for the dep-checker was released: https://github.com/ckeditor/ckeditor5-dev/releases/tag/v25.2.6.

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/125447633-b280f334-b2fc-49aa-928c-825e638f67af.png)

**Comment by pomek** [comment]
_Miss click._

**Comment by przemyslaw-zan** [comment]
Fix is in, but some dependencies are still marked as misplaced

![](https://user-images.githubusercontent.com/69513154/125447122-a27a081e-6056-4854-a41f-12b8dda03978.png)

**Comment by pomek** [comment]
On Unix-like OS:

![image](https://user-images.githubusercontent.com/2270764/125448068-d14b37e5-eea0-4b16-ab49-65d74113b9c3.png)

**Comment by przemyslaw-zan** [comment]
```
The following packages are used in the source and should be moved to `dependencies`
- @ckeditor/ckeditor5-basic-styles
- @ckeditor/ckeditor5-core
- @ckeditor/ckeditor5-utils
```

On Windows, these 3 dependencies still refuse to be moved into dev dependencies, but this will probably be a new ticket.
